### ISSUE TITLE
Markdown-processed shortcode used inside table erroneously closes table row.

### ISSUE THREAD

**Issue by dvogel** [gohugoio/hugo#10029]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

### Reproduction

In `src/layouts/shortcodes/support-email.html`:

```
user@example.com
```

In `src/content/_index.md` (or any content page):

```
|Header|
|------|
|prefix1 user@example.com suffix1|
|prefix2 {{% support-email %}} suffix2|
```

Based on [the shortcodes documentation](https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown) for shortcodes with markdown, I would expect this to be recognized by the markdown renderer as an email address and rendered to an anchor tag:

```
<a href="mailto:user@example.com">user@example.com</a>
```

If this was substituted in place of the shortcode I would expect the second row to look like the first. Instead the row is terminated and the suffix is placed in the next row:

![Screenshot from 2022-06-17 13-58-52](https://user-images.githubusercontent.com/45699/174386334-945a31a3-b645-4759-b5f9-0f05126f92cb.png)

The HTML is:

```
<table>
<thead>
<tr>
<th>Header</th>
</tr>
</thead>
<tbody>
<tr>
<td>prefix1 <a href="mailto:user@example.com">user@example.com</a> suffix1</td>
</tr>
<tr>
<td>prefix2 <a href="mailto:user@example.com">user@example.com</a></td>
</tr>
<tr>
<td>suffix2</td>
</tr>
</tbody>
</table>
```

Using the previous behavior in `src/layouts/shortcodes/support-email.html` yields a break both before and after:

```
{{ $_hugo_config := `{ "version": 1 }` }}
user@example.com
```

![Screenshot from 2022-06-17 13-58-35](https://user-images.githubusercontent.com/45699/174386341-d4a650df-b984-4760-a731-e4d063ce9539.png)

### Workaround

Using the `{{< support-email >}}` syntax with `<a href="mailto:user@example.com">user@example.com</a>` in `src/layouts/shortcodes/support-email.html` renders as expected.

**Comment by jmooring** [comment]
Your shortcode has a trailing newline. Chomp the trailing newline:

```
user@example.com
{{- /**/ -}}
```

**Comment by dvogel** [comment]
OMG you're right. I had wondered that but I wasn't suspicious enough. I trusted my editor:

![Screenshot from 2022-06-17 15-17-29](https://user-images.githubusercontent.com/45699/174396174-d4bb541b-e9ca-4c49-b598-db9df2571bee.png)

I should have checked the bytes it was writing out though:

```
$ xxd src/layouts/shortcodes/support-email.html 
00000000: 7573 6572 4065 7861 6d70 6c65 2e63 6f6d  user@example.com
00000010: 0a                                       .
```
