### ISSUE TITLE
Go templates escaping plus sign in .Data.Integrity

### ISSUE THREAD

**Issue by mcexit** [gohugoio/hugo#10025]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v.0.100.2+extended
</pre>

### Does this issue reproduce with the latest release?
Yes

### Description
While this issue may or may not cause issues, it doesn't appear to be standard[^1][^2]. It is also likely to fail if that value were to be used outside of the browser for some reason.

Example:

```HTML
{{- $stylesheet := fingerprint (toCSS (dict "targetPath" "style.css") (resources.Get "sass/main.scss")) }}
<link href="{{ $stylesheet.RelPermalink }}" integrity="{{ $stylesheet.Data.Integrity }}" rel="stylesheet">
```

Renders as:
> Note the `&#43;`

```HTML
<link href="./style.6475f1934962b1b03d102f80c8ad2c662d2e432e92ce430dd577377da694fb23.css" integrity="sha256-ZHXxk0lisbA9EC&#43;AyK0sZi0uQy6SzkMN1Xc3faaU&#43;yM=" rel="stylesheet">
```

[^1]: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
[^2]: https://w3c.github.io/webappsec-subresource-integrity/

**Comment by bep** [comment]
1. This has not caused any issue for me
2. This is an upstream issue in Go templates which you can report there, but I suspect will not be fixed.

**Comment by bep** [comment]
But note that there are ways to work around this if you want to (I suspect the easiest is just to write the entire tag via printf).

**Comment by jmooring** [comment]
Chrome and Firefox interpret this:

```
integrity="sha256-HaUB/dOV0S&#43;7cMR/kEIFtXbmxTt6kvdCOU2uLfrf&#43;ms="
```

as this:

```
integrity="sha256-HaUB/dOV0S+7cMR/kEIFtXbmxTt6kvdCOU2uLfrf+ms="
```

If you run `hugo --minify` and view source you will see the same thing:

```
integrity="sha256-HaUB/dOV0S+7cMR/kEIFtXbmxTt6kvdCOU2uLfrf+ms="
```

If you feel strongly about avoiding the substitution, you can do this:

```text
<link rel="stylesheet" href="{{ .RelPermalink }}" {{ printf `integrity=%q` .Data.Integrity | safeHTMLAttr }}>
```
