### ISSUE TITLE
Add nested section markup render setting

### ISSUE THREAD

**Issue by mcexit** [gohugoio/hugo#10039]
While `{{ .TableOfContents }}` understands the nested nature of section content:

- [Section 1](http://localhost:1313/#section-1)
  - [Section 1.1](http://localhost:1313/#section-11)
  - [Section 1.2](http://localhost:1313/#section-12)
    - [Section 1.2.1](http://localhost:1313/#section-121)

The `{{ .Content }}` variable renders the content as a mostly flat structure. For example, the following markdown:

```
# Section 1
This is section 1.

> This is a blockquote in section 1

## Section 1.1
This is section 1.1

- Section 1.1 list item

## Section 1.2
This is section 1.2

### Section 1.2.1
This is section 1.2.1
```

Renders as:
> Note the section elements (e.g. `<p>`, `<blockquote>`, `<ul>`) are all rendered within the same "section" (no nested wrapping).

```
<h1 id="section-1">Section 1</h1>
<p>This is section 1.</p>
<blockquote>
<p>This is a blockquote in section 1</p>
</blockquote>
<h2 id="section-11">Section 1.1</h2>
<p>This is section 1.1</p>
<ul>
<li>Section 1.1 list item</li>
</ul>
<h2 id="section-12">Section 1.2</h2>
<p>This is section 1.2</p>
<h3 id="section-121">Section 1.2.1</h3>
<p>This is section 1.2.1</p>
```

Therefore, if I wanted to group all content in `Section 1.1` into a single cell using flexbox or grid, there is no way to do so.

I think the `<section>` element[^1] makes the most sense here to show the hierarchy if desired, e.g.:

```
<section>
	<header>
		<h1 id="section-1">Section 1</h1>
	</header>
	<p>This is section 1.</p>
	<blockquote>
		<p>This is a blockquote in section 1</p>
	</blockquote>
	<section>
		<header>
			<h2 id="section-11">Section 1.1</h2>
		</header>
		<p>This is section 1.1</p>
		<ul>
			<li>Section 1.1 list item</li>
		</ul>
	</section>
	<section>
		<header>
			<h2 id="section-12">Section 1.2</h2>
		</header>
		<p>This is section 1.2</p>
		<section>
			<header>
				<h3 id="section-121">Section 1.2.1</h3>
			</header>
			<p>This is section 1.2.1</p>
		</section>
	</section>
</section>
```

[^1]: https://html.spec.whatwg.org/multipage/sections.html#the-section-element

**Comment by nternetinspired** [comment]
No offence, but this doesn't make a whole lot of sense. The ’section elements’ you mention are block-level elements, of which <section> is just one.

A level 2 header (##) is already a subsection of the article, section 2; not section 1.1. It needs no additional section element to be interpreted as such.

Adding a section element in such cases provides 0 additional semantics, just extraneous markup.

Of course there are cases when your content should indeed be within a <section>, an index page for example, but it simply makes no sense here. In the example you provided the section and header elements are entirely superfluous, they add no meaning whatsoever, just additional markup. There's a reason that Markdown does not provide you with a way to do this…

Of course, you can structure your html however you see fit, and Hugo allows you to do that easily. If you want your {{ .Content }} rendered inside a <section> there is nothing stopping you but I can tell you that there is no advantage at all to littering your markup with additional <section> and <heading> elements, it's just additional overhead.

**Comment by nternetinspired** [comment]
Table of contents recognises the inherent structure of the html, as do browsers, without any additional markup because simply using the correct headings is enough to determine the content hierarchy.

**Comment by jmooring** [comment]
Hugo converts markdown to HTML using the [Goldmark](https://github.com/yuin/goldmark/) markdown renderer. Goldmark adheres to the [CommonMark specification](https://spec.commonmark.org/0.30/), which has no provision for the functionality described in this issue.

> Markdown is not a replacement for HTML, or even close to it… For any markup that is not covered by Markdown’s syntax, you simply use HTML itself.
>
> Mark Gruber (co-inventor of markdown)
> https://daringfireball.net/projects/markdown/syntax#philosophy

You can mix raw HTML in your markdown, provided you follow the markdown spec for [HTML blocks](https://spec.commonmark.org/0.30/#html-blocks) (pay attention to blank line requirements) and [raw HTML](https://spec.commonmark.org/0.30/#raw-html).

With this in your site configuration:

```text
[markup.goldmark.renderer]
unsafe = true
```

You can do:

```text
<section>

## Section 1

This is section 1.

> This is a blockquote in section 1

</section>
```

**Comment by skrysmanski** [comment]
This feature would have been useful for JavaScript's `IntersectionObserver` to highlight the sections in the ToC that you're currently viewing - liked demoed here: <https://www.bram.us/2020/01/10/smooth-scrolling-sticky-scrollspy-navigation/#step3>
