### ISSUE TITLE
taxonomy.html and terms.html reversed

### ISSUE THREAD

**Issue by gumaerc** [gohugoio/hugo#10048]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.101.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes, I'm using the latest release

[This discourse thread](https://discourse.gohugo.io/t/taxonomy-list-page-takes-a-wrong-template/20189/2) describes the exact issue I'm experiencing here with the latest version of Hugo today.  I have layouts defined in my Hugo theme at `layouts/learning_resource_types/taxonomy.html` as well as `layouts/learning_resource_types/terms.html` and the `taxonomy` kind seems to be selecting `terms.html` which `term` kinds are selecting the `taxonomy.html` template.  I added debug lines to my template to prove this, with `<div>{{ printf "%#v" .Kind }}</div>` in my `baseof.html` to print the `kind` of the current page, and a literal `<div>taxonomy.html</div>` in my `taxonomy.html` template as well as a `<div>terms.html</div>` in my `terms.html` template.  It results in the following:

![image](https://user-images.githubusercontent.com/12089658/175612721-9fbd09b7-c17e-4266-b608-220ece184830.png)
![image](https://user-images.githubusercontent.com/12089658/175612781-c96d144a-fee5-4bd4-8f45-a5e7f66e0643.png)

As you can see, when the `kind` of the page is `taxonomy`, `terms.html` is being selected whereas if the `kind` is `term`, `taxonomy.html` is being selected.

Side note: we are using the `permalinks` directive to redirect our `learning_resource_types` taxonomy pages to `/resources` which is why you see the URLs for this at `/resources`.

**Comment by bep** [comment]
We have a million tests for this, so I'm pretty sure this works as designed. I don't know your setup, though, so I cannot tell what's happening. 

I suggest you raise a new thread on the forum.

**Comment by gumaerc** [comment]
@bep Okay, will do and thanks for taking a look.  For what it's worth, I was able to reproduce this with a fresh Hugo project as well.

`config.toml`:
```
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[taxonomies]
test_taxonomy = "test_taxonomy"
[outputs]
home = [ 'HTML' ]
page = [ 'HTML' ]
section = [ 'HTML' ]
taxonomy = [ 'HTML' ]
term = [ 'HTML' ]
```

`content/test_pages/test_1.md`:
```
---
test_taxonomy:
 - taxonomy1
---
```

`layouts/test_taxonomy/taxonomy.html`:
```
<html>
<head></head>
<body>
<div>{{ printf "%#v" .Kind }}</div>
<div>taxonomy.html</div>
</body>
</html>
```


`layouts/test_taxonomy/terms.html`:
```
<html>
<head></head>
<body>
<div>{{ printf "%#v" .Kind }}</div>
<div>terms.html</div>
</body>
</html>
```

In the output:
`public/test_taxonomy/index.html`:
```
<html>
<head><script src="/livereload.js?mindelay=10&amp;v=2&amp;port=1313&amp;path=livereload" data-no-instant defer></script></head>
<body>
<div>&#34;term&#34;</div>
<div>taxonomy.html</div>
</body>
</html>
```

`public/test_taxonomy/taxonomy1/index.html`:
```
<html>
<head><script src="/livereload.js?mindelay=10&amp;v=2&amp;port=1313&amp;path=livereload" data-no-instant defer></script></head>
<body>
<div>&#34;term&#34;</div>
<div>taxonomy.html</div>
</body>
</html>
```

Am I missing something here about the terminology?  I was under the impression that "test_taxonomy" here is the Taxonomy, and "taxonomy1" is the term, and the layout selection seems to be obviously reversed.  I uploaded my test project here if you'd like to take a look: https://drive.google.com/file/d/19xizGJJ69an7iA7fkLsEZ10ufm4KKaCJ/view?usp=sharing

**Comment by gumaerc** [comment]
@bep I cleaned up my example and put it into a Github repo for easy access here: https://github.com/gumaerc/hugo-taxonomy-template-bug
