### ISSUE TITLE
relURL is stripping the baseURL path

### ISSUE THREAD

**Issue by mattcone** [gohugoio/hugo#10049]
Hey there! I believe we're experiencing a bug that is possibly related to https://github.com/gohugoio/hugo/issues/9994 and https://github.com/gohugoio/hugo/pull/10002. Someone actually left a couple comments related to this that I think accurately describe the bug:

- https://github.com/gohugoio/hugo/issues/9994#issuecomment-1163592378
- https://github.com/gohugoio/hugo/pull/10002#discussion_r904223194

Prior to v101, we had this set up and it was working:

```
baseURL = "https://example.com/foo"

{{ "/images/logo.svg" | relURL }}

http://localhost:1313/foo/images/logo.svg
```

Now, after the upgrade to v101, we see this:

```
baseURL = "https://example.com/foo"

{{ "/images/logo.svg" | relURL }}

http://localhost:1313/images/logo.svg
```

The `foo` part of `baseURL` is being stripped out by `relURL`. 

### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.101.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes 😄

**Comment by bep** [comment]
```
{{ "/images/logo.svg" | relURL }}

http://localhost:1313/foo/images/logo.svg
````
This was a bug fix in 101 making relURL work the same as absURL.

The gist of it is, res starting with a `/` is considered relative to the server host, remove that and it will work. Your breakage is unfortunate, but it was wrong before.

**Comment by mattcone** [comment]
Thanks for the additional information.
