### ISSUE TITLE
`ul` incorrectly added in `pre`/`code` block

### ISSUE THREAD

**Issue by svennergr** [gohugoio/hugo#10068]
## Description

Hugo is failing to convert HTML in Markdown containing syntax-highlighting in some occasions. 
I created a small example repo at https://github.com/svennergr/hugo-yaml-highlight-bug, which includes the source file https://github.com/svennergr/hugo-yaml-highlight-bug/blob/main/posts/test.md and the output in https://github.com/svennergr/hugo-yaml-highlight-bug/blob/main/public/test/index.html. 

I just noticed, that Github is also failing to render the first language-section correctly.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended darwin/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
yes.

**Comment by jmooring** [comment]
This is working as expected, adhering to the CommonMark specification. [Try it](https://spec.commonmark.org/dingus/?text=%3Cp%3ENot%20working%3C%2Fp%3E%0A%3Cpre%3E%3Ccode%20class%3D%22language-yaml%22%3Etest%3A%201%0A%0Aarray%3A%0A%20%20-%20name%3A%20test%0A%3C%2Fcode%3E%3C%2Fpre%3E).
