### ISSUE TITLE
defaultContentLanguageInSubdir does not apply if only one language is enabled 

### ISSUE THREAD

**Issue by paperdigits** [gohugoio/hugo#10064]
### What version of Hugo are you using (`hugo version`)?

`0.101.0`

### Does this issue reproduce with the latest release?

Yes

We use hugo to build the darktable docs: https://github.com/darktable-org/dtdocs

The translations are generally a bit behind the main English text, since this is about 300 pages worth of instruction.

When we are ready to make a release of the English documentation (this is the only language that needs to be ready at release time, then we update as translations finish), we disable all other languages. We're using the multilingual site configuration. 

When only English is enabled, hugo builds the site as if we were not using multilingual mode. This breaks all our URLs and folder structure, since we expect English to build into the `en` subfolder instead of into the root of `public`.

I'm not sure if my thinking is correct or not, but I think that if multilingual mode is enabled, then hugo should follow the output rules, no matter how many languages are enabled.

**Comment by elstoc** [comment]
To clarify, we disable languages by using `env HUGO_DISABLELANGUAGES="$disabled_languages " hugo --config "$HUGO_CONFIG" -d "$HUGO_DIR"` so all the languages are defined in our config but only the default language is enabled (because `$disabled_languages` includes everything except en)

**Comment by jmooring** [comment]
This issue has been raised before:
<https://github.com/gohugoio/hugo/issues/5299> (closed by stalebot)

MRE

```bash
git clone --single-branch -b hugo-github-issue-10064 https://github.com/jmooring/hugo-testing hugo-github-issue-10064
cd hugo-github-issue-10064
hugo server
```

**Comment by jmichelgarcia** [comment]
Supper annoying that #5299 was closed by stalebot. I just lost 5 hours trying to understand this.
In my case, I only use one language, but would like to nevertheless use url prefixes `/en`.

Keen to hear if anyone has solved this.

**Comment by jmichelgarcia** [comment]
Supper annoying that https://github.com/gohugoio/hugo/issues/5299 was closed by stalebot. I just lost 5 hours trying to understand this.
In my case, I only use one language, but would like to nevertheless use url prefixes `/en`.

Keen to hear if anyone has solved this.
