### ISSUE TITLE
Unneeded whitespace after custom-rendered link

### ISSUE THREAD

**Issue by Wirone** [gohugoio/hugo#10063]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.101.0+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

### Description of a problem

I wanted to render links with `target="_blank"` and I found information that it can be done with custom `layouts/_default/_markup/render-link.html`, so I created it as:

```
<a href="{{ .Destination | safeURL }}" {{ with .Title}} title="{{ . }}" {{ end }}{{ if strings.HasPrefix .Destination "http" }} target="_blank"{{ end }}>{{ .Text | safeHTML }}</a>
```

It works, in general. But when non-white char is right after link's markdown (e.g. `Follow me [on Twitter](https://twitter.com/_Codito_).`), it's rendered with space between linked text and the char. You can see it [in this article](https://blog.codito.dev/2022/06/laravel-pint-a-study-of-ambivalence/) in several places (space before `,`, `)` etc.).

It's really a minor problem, but for purists like me it looks weird 😅

**Comment by jmooring** [comment]
You have a trailing newline in your render hook. Do this insteand:

```
<a href="{{ .Destination | safeURL }}" {{ with .Title}} title="{{ . }}" {{ end }}{{ if strings.HasPrefix .Destination "http" }} target="_blank"{{ end }}>{{ .Text | safeHTML }}</a>
{{- /**/ -}}
```

In the future, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by Wirone** [comment]
I've tried without new line and it worked the same. But `{{- /**/ -}}` trick did the thing, thank you!
