### ISSUE TITLE
Error: unknown command "submodule" for "hugo"

### ISSUE THREAD

**Issue by zhl111** [gohugoio/hugo#10066]
I installed the extended version，How to fix?
![image](https://user-images.githubusercontent.com/29135984/177052087-2e36b011-3918-4520-bee1-53b036f7326c.png)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
