### ISSUE TITLE
ananke theme build fail

### ISSUE THREAD

**Issue by rdfleay** [gohugoio/hugo#10079]
hi, 
i edited the yml to use the 0.91.0 version as the extended did not build, but now the site is built (http://rdfleay.gitlab.io/)
now i have edited again for the ananke theme.. but am now tired of cannot figuring exactly what is needed.. 
<pre>
$ hugo version
hugo v0.81.0-59D15C97+extended linux/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio
git version 2.37.0

# last fail
$ hugo mod init gitlab.com/rdfleay.gitlab.io
WARN 2022/07/10 05:33:35 module "github.com/theNewDynamic/gohugo-theme-ananke" not found; either add it as a Hugo Module or store it in "/builds/rdfleay/rdfleay.gitlab.io/themes".: module does not exist

Error: Error building site: "/builds/rdfleay/rdfleay.gitlab.io/content/post/2017-03-20-photoswipe-gallery-sample.md:10:1": failed to extract shortcode: template for shortcode "gallery" not found

```
# rdfleay.gitlab.io yml
# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:0.91.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production

default:
  before_script:
    - apk add --update --no-cache git go
    - git submodule update --init --recursive
    - hugo mod init gitlab.com/pages/rdfleay.gitlab.io
    - hugo mod get -u github.com/theNewDynamic/gohugo-theme-ananke
    #hugo mod init github.com/ariznaf/fuentes-arizna-alzu.org/tree/ananke-as-module
    #- hugo mod get -u github.com/budparr/gohugo-theme-ananke.git
    #hugo mod init github.com/ariznaf/fuentes-arizna-alzu.org/tree/ananke-as-module
    #$ git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/gohugo-theme-ananke

test:
  script:
    - hugo
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
```

```
# rdfleay.gitlab.io toml
baseurl = "https://rdfleay.gitlab.io"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "salt'd"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"] #"beautifulhugo"
metaDataFormat = "yaml"

```
thanks

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
