### ISSUE TITLE
Functions don't work in translated strings

### ISSUE THREAD

**Issue by isti03** [gohugoio/hugo#10083]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.101.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

### Issue description

I have the following translation in `i18n/en.yaml`:

```yaml
lastmod:
  other: 'Last modified: {{ .Date | time.Format ":date_full" }}'
```

I then use it in a template this way:
```
{{ i18n "lastmod" . }}
```

I get the following error when building the site:

```
WARN 2022/07/11 10:16:36 Failed to get translated string for language "en" and ID "lastmod": template: :1: function "time" not defined
```

**Comment by jmooring** [comment]
The texttemplate parser validates function existence, but that is currently limited to built-in template functions. For example, this works fine in an i18n file.

```
foo = '{{ or . "undefined" }}'
```

Not sure why Hugo's functions aren't in the function map at this point.

**Comment by bep** [comment]
>Not sure why Hugo's functions aren't in the function map at this point.

The `go-i18n` library has its own _template handling_ and has no knowledge of Hugo's template functions etc.

This is unfortunate, and is probably fixable ... but I would strongly recommend keeping the i18n files as simple as possible.

The example in the intro could easily be rewritten as

```yaml
lastmod:
  other: 'Last modified'
```

Which In my head is a better setup (separation of concerns and all that).

Then you can do templating/formatting in the layout template, e.g.:

```handlebars
{{ i18n "lastmod" }}: {{ .Date | time.Format ":date_full" }}
```

**Comment by jmooring** [comment]
> keeping the i18n files as simple as possible

Yeah, the shorthand is somewhat appealing, but that could quickly get out of control:

```
# i18n/en.toml

foo = '{{ partial (path.Join .Language.Lang "my-partial.html") }}'
```

**Comment by bep** [comment]
>but I would strongly recommend keeping the i18n files as simple as possible.

One weekend project I was thinking of doing, to get a better grasp of what's possible with the recent outflow of local large language models (e.g. Llama 2) to create some tooling to translate `i18n/*.toml`, and that task would be much harder if those files was filled with template logic (heck, even handing those files over to a human translator would make him/her hesitate).
