### ISSUE TITLE
Allow `isset` function to accept non-lowercase keynames

### ISSUE THREAD

**Issue by anakinsleftleg** [gohugoio/hugo#10097]
It's out of character with the rest of templating syntax that the key value in question in the function `isset` must be given in lowercase.

Could this not be remedied by having the input argument forced to lowercase by the isset function itself when it runs? Something like `lower input_key` to make it lowercase, then anyone can use whatever casing they want for consistency.

It would also be nice if the docs specified isset will error out if the key doesn't exist at all. Seems like isset ought to return false if the key doesn't exist or if the key exists but is not set or returns empty

**Comment by bep** [comment]
>It's out of character with the rest of templating syntax that the key value in question in the function isset must be given in lowercase.

We have a core `maps.Params` type in Hugo that is used to store user data in a case insensitive way (all keys are lower-cased, which means all lookups are lower cased as well (e.g. when you do `site.Params.FooBar`.)

So, it's certainly within _character_ of the rest of Hugo's templating system.

I do agree that it would be useful if `isset` worked for maps with mixed-case keys, but we cannot do that in a simple way without breaking lots of stuff in the wild.

But I have not used `isset` in "a decade", so I suspect it was a construct that was more useful before we fixed the "truth function" in the Go templates (allowing `if` and `with` to work as expected), so I suggest that we instead consider deprecating `isset`.

**Comment by anakinsleftleg** [comment]
Please excuse my ignorance but is there not a way to make the input to `isset` lowercase (with a `lower()` type function or regex replace) before anything is done and then it all works just as it does now?

Also, @regisphilibert has stated that `isset` is useful for determining whether a key exists in frontmatter or not. It seems to be more appropriate to treat it like a `doesKeyExist()` function. Where `if, with` return false if the key does not exist or if it does exist but is falsy. I can see that distinction being useful.

**Comment by bep** [comment]
OK, @regisphilibert has demonstrated in another thread that `isset` has its use case(s), but it should be rare.

I have not looked at the implementation in years, but if it currently does lower casing I don't think we can just remove it.

I suggest we:

1. Check if target is `maps.Params` then check with lower case only.
2. Else, first check with original case then lower case.
3.

**Comment by anakinsleftleg** [comment]
Just as a point of comparison, the `where` command accepts capitalized keys, and in fact will only work correctly if the leading key is capitalized: 

```
where site.RegularPages "Type" "ne" "page"  --> works
where site.RegularPages "type" "ne" "page"  ---> doesn't work but no error
```
