### ISSUE TITLE
Rebuild when live reload do not changes actual files

### ISSUE THREAD

**Issue by knutov** [gohugoio/hugo#10090]
```
hugo version # installed from brew
hugo v0.101.0+extended linux/amd64 BuildDate=unknown
```

Scenario: content page > call shortcode > call partial.
When partial template changed I see (some data replaced with dots):

```
INFO 2022/07/15 13:18:45 Received System Events: ["......./tabs.html": WRITE "/......./layouts/partials/tabs.html": WRITE]

Change detected, rebuilding site.
2022-07-15 13:18:45.202 +0500
DEBUG 2022/07/15 13:18:45 Rebuild for events ["\"/......./layouts/partials/tabs.html\": WRITE"]
Template changed "......./layouts/partials/tabs.html": WRITE
DEBUG 2022/07/15 13:18:45 Render page ....... to "/a/index.html"
```

But all files in browser are rendered as `layouts/partials/tabs.html` was not changed.

I run hugo with 
```
hugo server  --noHTTPCache -p 10003 --gc --disableFastRender --verbose --debug --verboseLog  --buildDrafts --buildExpired --buildFuture
```

I have to do ctrl+c and run hugo again to render page with actual templates.

**Comment by bep** [comment]
I'm not sure what's happening in your case, but there are some known issues with what I would called transitive dependencies on reload. These will "all" fixed (or at least much improved) in the next Hugo. I will close this issue, though, as we have similar sounding issues.

**Comment by knutov** [comment]
@bep Thanks!

What issue should I subscribe to get notify when the problem will be solved?

**Comment by bep** [comment]
@knutov I would subscribe to the release page ...
