### ISSUE TITLE
resources.Get errors when given an empty string

### ISSUE THREAD

**Issue by anakinsleftleg** [gohugoio/hugo#10101]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

----
## Observed Behavior

When `resources.Get ""` is run, ie. `resources.Get` is given an empty string, it errors out and fails the build. `.Resources.Get` does not have the same issue. 

```
execute of template failed at <resources.Get>: error calling Get: dirs not supported resource types: &{0xc002d15350 0xc002bc8c80}
```

## Expected Behavior

When an empty string is passed to `resources.Get`, it will return a false, as `.Resources.Get` does, and continue processing the build.

**Comment by raygervais** [comment]
I'd like to work on this bug, have been using Hugo for a few years and would love to contribute!

**Comment by Simran-B** [comment]
The issue reported here has apparently been fixed: https://github.com/gohugoio/hugo/pull/10444

I can still trigger the error by passing one or more spaces.

**Comment by jmooring** [comment]
Closed with https://github.com/gohugoio/hugo/pull/10444
