### ISSUE TITLE
Preserve triple hyphens etc. in URLs.

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#10104]
This relates to #7288 -- which was fixed.

I create this just to avoid some yelling about "broken URLs" from @kaushalmodi and friends.

I'm doing some ground work to simplify stuff and also make stuff faster and more effective.

So with #7288 the issue was 

>content/foo--bar.md, the page URL is expected to be <site>/foo--bar/.

With that it does not make much sense to say that `content/foo---bar.md` becomes `foo-bar/`.

We have a test case for the above, but I will change that so that any number of subsequent hyphens are preserved...

**Comment by kaushalmodi** [comment]
> With that it does not make much sense to say that content/foo---bar.md becomes foo-bar/.

Certainly! If the user decided to have 3 hyphens in their content file name, then why override that.

**Comment by jmooring** [comment]
This was implemented in v0.93.0 with https://github.com/gohugoio/hugo/pull/9403 which preserves any number of hyphens.

Path|RelPermalink
:--|:--
`content/foo-bar.md`|`/foo-bar/`
`content/foo--bar.md`|`/foo--bar/`
`content/foo---bar.md`|`/foo---bar/`
`content/foo----bar.md`|`/foo----bar/`

Tested with hugo v0.93.0-07469082+extended
