### ISSUE TITLE
Highlight line position is shifted when Japanese is used in the highlight shortcode

### ISSUE THREAD

**Issue by k1350** [gohugoio/hugo#10102]
When using the highlight shortcode with "linenos=table" and "hl_lines", highlight line position is shifted when Japanese is used.

![image](https://user-images.githubusercontent.com/40417367/179457136-e88f4011-a420-4278-a5c8-435155e35b45.png)

sample repository 
https://github.com/k1350/hugo_sample

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
This behavior is not specific to syntax highlighting. The browser's default height for Latin characters is different that the default height for Japanese characters. For example, with Google Chrome the default height for Latin characters is 18.5 px, while the default height for Japanese characters is 23 px.

Create a simple HTML file, open it with your browser, and use the browser's dev tools to inspect each line:

```html
<p>abcde</p>
<p>あいうえお</p>
```

You can accommodate the difference by overriding the default height. For example:

```css
.highlight {
  line-height: 1.5;
}
```

**Comment by k1350** [comment]
@jmooring I understand. Thank you.
