### ISSUE TITLE
Cannot get attributes in no language identifier in CodeBlock

### ISSUE THREAD

**Issue by chick-p** [gohugoio/hugo#10118]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.101.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

### The issue
Sometimes, I don't specify a language identifier in a Code Block as follows:

````markdown
```{foo=true}
bar
```
````

In the above case, the Render Hooks for Code Block do not receive the attributes.
Is this behavior expected?

I guess this cause is that `attrStartIdx` equals 0  if no language identifier in`getAttributes()`.
Ref. https://github.com/gohugoio/hugo/blob/master/markup/goldmark/codeblocks/render.go#L184-L191

If this behavior is a bug, I guess that be fixed by the below diff. 

```diff
-		if attrStartIdx > 0 {
+		if attrStartIdx != -1 {
```
Ref. https://github.com/gohugoio/hugo/commit/b6b15e57602186dcbef0a61c422bdaa9eb295dca

Thanks!

**Comment by bep** [comment]
This looks like a bug. A PR with a test is welcomed (there are similar tests in there somewhere).

**Comment by chick-p** [comment]
Thank you for your comment.
I have opened #10119
