### ISSUE TITLE
Hugo server doesn't detect changes from VB synced_folder 

### ISSUE THREAD

**Issue by meaz** [gohugoio/hugo#10124]
Hi,

I use vagrant to test hugo on a virtual env. I have set a synced_folder between the guest and the host, so that I can have edit the site directly from the host.
I can run `hugo server` on host without problem.
I can edit a file on the host, for example the config file, and I see `Change of config file detected, rebuilding site.`, which shows that it is updated.
The problem is when I try to edit a file in the synced folder directly from the host. For example, if I edit the config file from the host, I don't see `Change of config file detected, rebuilding site.` But if I check the file from the guest, I do see it was edited. But hugo server doesn't catch it.

Any idea why?

**Comment by bep** [comment]
Hugo uses file events from the OS (e.g. `inotify` on Linux) to detect changes. That may not work well in some situations. I suggest you run it with `hugo server --poll`.

Take further question at https://discourse.gohugo.io/
