### ISSUE TITLE
Multilingual site has wrong sitemap format

### ISSUE THREAD

**Issue by Mecanik** [gohugoio/hugo#10127]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.99.1-d524067382e60ce2a2248c3133a1b3af206b6ef1+extended linux/amd64 BuildDate=2022-05-18T11:18:14Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

The issue I am having is with the sitemap format. As per the documentation and requirements by search engines, the sitemap format should be:

sitemap.xml

```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
  {{ range .Data.Pages }}
  <url>
    <loc>{{ .Permalink }}</loc>{{ if not .Lastmod.IsZero }}
    <lastmod>{{ safeHTML ( .Lastmod.Format "2006-01-02T15:04:05-07:00" ) }}</lastmod>{{ end }}{{ with .Sitemap.ChangeFreq }}
    <changefreq>{{ . }}</changefreq>{{ end }}{{ if ge .Sitemap.Priority 0.0 }}
    <priority>{{ .Sitemap.Priority }}</priority>{{ end }}{{ if .IsTranslated }}{{ range .Translations }}
    <xhtml:link
                rel="alternate"
                hreflang="{{ .Lang }}"
                href="{{ .Permalink }}"
                />{{ end }}
    <xhtml:link
                rel="alternate"
                hreflang="{{ .Lang }}"
                href="{{ .Permalink }}"
                />{{ end }}
  </url>
  {{ end }}
</urlset>
```

sitemapindex.xml

```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	{{ range . }}
	<sitemap>
	   	<loc>{{ .SitemapAbsURL }}</loc>
		{{ if not .LastChange.IsZero }}
	   	<lastmod>{{ .LastChange.Format "2006-01-02T15:04:05-07:00" | safeHTML }}</lastmod>
		{{ end }}
	</sitemap>
	{{ end }}
</sitemapindex>
```

Right? Well the output is not this. 

Please check my sitemap index: https://mecanik.dev/sitemap.xml and then check any of the sitemaps included: https://mecanik.dev/en/sitemap.xml. 

I tried overwriting the output format in layouts/sitemap.xml and layouts/_default/sitemap.xml but no effect. 

How can I fix this? I want the sitemap's for each language to have properly formatted XML.

Many thanks.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by Mecanik** [comment]
So you decided this is not a bug? How did you come to this decision? Please elaborate...
