### ISSUE TITLE
No extended releases for Linux arm64?

### ISSUE THREAD

**Issue by chris-short** [gohugoio/hugo#10134]
Am I misreading the releases page or is there not a Hugo extended version for arm64 Linux?

**Comment by bep** [comment]
No, you are correct. The extended version requires a build setup for C/C++ for the target platform; we're currently cross-building everything from one Docker container, and I haven't been successful in setting up both ARM64 and AMD64 in the same container. I'll admit I haven't tried too hard, and we might be able to improve this by splitting the build somehow ... That said, we have other isues trackingthis, so close this ad a duplicate.

Note that if you're running ARM64 Linux with Go installed, you can do:

```
go install -tags extended github.com/gohugoio/hugo@latest
```

And similar.

**Comment by bep** [comment]
See #8257

**Comment by anthonyfok** [comment]
@chris-short "extended" builds are available as:

* Hugo snap (see <https://snapcraft.io/hugo>)
* Debian/Ubuntu packages: https://packages.debian.org/sid/hugo and https://packages.ubuntu.com/kinetic/hugo

and maybe more for other Linux distributions, though I haven't checked.  See if any of these would suite your needs?  :-)

**Comment by chris-short** [comment]
I'll check those images.
