### ISSUE TITLE
Consider truncating your documentation text files to 80 columns 

### ISSUE THREAD

**Issue by hughes-mann** [gohugoio/hugo#10137]
The markdown formatted documents in your source tree do not comply with the standard UNIX 80 character line length making them potentially difficult to manipulate using UNIX tools and/or incorporate into scripts. Furthermore and perhaps more importantly it makes them significantly less readable (as can be seen below).

I propose 'narrowing' all `.md` files in the directory tree with the fold POSIX tool and imposing appropriate guidelines for the future.

Your software has much bigger issues which I shall point out to the extend I have the time to while working on a proper fork of your work.

the original document
![full_nonsleek](https://user-images.githubusercontent.com/110361229/182053288-044ea5a7-97c3-43f3-a21f-de16e7e30686.png)

fixed using `fold(1)`
![full_sleek](https://user-images.githubusercontent.com/110361229/182053293-1d919a66-f664-4964-b060-349d7a7f9704.png)

**Comment by jmooring** [comment]
Documentation diffs are easier to read when paragraphs are not split into separate lines. Description and example here:
<https://code.dblock.org/2021/06/07/to-wrap-or-not-to-wrap-in-markdown.html>
