### ISSUE TITLE
Hugo binary seems to have external dependency, despite README.md's claim

### ISSUE THREAD

**Issue by flyn-org** [gohugoio/hugo#10136]
Hugo's README.md states "The Hugo binaries have no external dependencies." However, running `hugo server` causes the error `Error: failed to download modules: binary with name "go" not found`. This is fixed by installing the Go tools. So, it seems Hugo has taken on some external dependencies.

I am the maintainer of the Fedora Hugo package. Changing the Hugo package to depend on golang-bin brought in a large volume of dependencies, such as GCC. This is not optimal for some uses, such as CI pipelines, which benefit from small installs. We are trying to come up with a solution for this, but I thought I would investigate where this dependency came from.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.93.3+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by bep** [comment]
Thanks, I have removed that sentence. Some (optional) parts of Hugo does depend on certain binaries being available in the PATH (e.g. `go` and `git` which backs Hugo Modules). I would suggest that you let the user decide if he needs these additional features on the CI server etc.

I suggest you take further questions at https://discourse.gohugo.io/

**Comment by bep** [comment]
https://github.com/gohugoio/hugo/issues/9078#issuecomment-1204159918

**Comment by anthonyfok** [comment]
Hi @flyn-org,

Interesting discussion!

I should add a weak-dependency on Go in the Debian package too.  Besides the existing `Recommends: git`, I should add `Suggests: asciidoctor, golang-any, npm, pandoc, python3-docutils` in the next release.  Go is indeed rather large, so I think it is best we merely _suggests_ to the end user to install Go manually.

Thanks for the neat idea!
