### ISSUE TITLE
Narrow no-break space replaced by a regular space

### ISSUE THREAD

**Issue by yaaax** [gohugoio/hugo#10148]
> 
> 
> ### What version of Hugo are you using (`hugo version`)?
> 
> <pre>
> $ hugo version
> hugo v0.101.0+extended darwin/amd64 BuildDate=unknown
> </pre>
> 
> ### Does this issue reproduce with the latest release?
> Yes

`safeHTML` seems to replace `&#8239;` _(narrow no-break space)_. character by ` ` _(regular space)_.

**Working fine**:
```{{ "before&nbsp;after" | safeHTML }}```
Actual output: "`before&nbsp;after`" 👌

**Not working**:
```{{ "before&#8239;after" | safeHTML }}```
Actual output: "`before after`" ❌
Expected: 👉 "`before&#8239;after`"

See [Narrow no-break space, width variation](https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation)

**Comment by jmooring** [comment]
I am unable to reproduce the behavior.

```
{{ "before&nbsp;after" | safeHTML }} --> before&nbsp;after
{{ "before&#8239;after" | safeHTML }} --> before&#8239;after
```

**Comment by yaaax** [comment]
Ok, maybe not related to `safeHTML` directly. But still the narrow space is replaced by a regular space.
See this test repo:

https://gitlab.com/goodimpact/goodimpact-hugo/issues/issue-10148/

**Comment by jmooring** [comment]
> But still the narrow space is replaced by a regular space.

No, it is not.

This markdown:

```text
x&#8239;x
```

Is rendered as:

```text
x x
```

Now copy and paste that string into this Bash command:

```bash
echo -n "x x" | od -A n -t x1
```

Which produces this output:

```
78 e2 80 af 78
```

`78` is hex for `x`.

`e2 80 af` is hex for the [narrow no-break space](https://www.fileformat.info/info/unicode/char/202f/index.htm).

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by yaaax** [comment]
Oh, you're right, sorry for the noise 😕

Note: the confusion was due to fact that the Chrome dev inspector displays "`&nbsp;`" clearly but displays "`&#8239;`" as a space…
