### ISSUE TITLE
Support date/time ranges in "date" front matter variable

### ISSUE THREAD

**Issue by Jehan** [gohugoio/hugo#10162]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2021-02-09T18:47:48Z (debian 0.80.0-6)
</pre>

### Does this issue reproduce with the latest release?

Also tested with hugo 0.93.3 on Fedora 36; it didn't work either. I didn't test on 0.101.0 which is the latest.

### Issue description

I'd like to be able to add a date range, such as:

```
date = "2003-08-07/10"
```

Which should mean from the 7 to 10th of August 2003.

As far as I can see, ISO 8601 allows time intervals, for various ways to format such intervals, cf. https://en.wikipedia.org/wiki/ISO_8601#Time_intervals

Now this is assuming Hugo uses ISO8601 formatting. It looks like so, yet I couldn't find accurate info on Hugo docs. Best I find is this page which no accurate info: https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

[ which by the way is very confusing:

```
"Monday, January 2, 2006"
    Returns: Friday, March 3, 2017
```

→ ???
But that's off-topic! ]

Anyway, so I see that the front matter has a `publishDate` variable, which can have the publication date (as name says) which won't be an interval. Then we could use the `date` variable as interval when it is meaningful. For instance in our case, we have a page listing past events (conferences) and one page per event. I thought the `date` variable would be the right place to add the conference dates.

**Comment by jmooring** [comment]
Use custom date fields, either scalar or array.

```
+++
start_date = 2023-01-01
end_date = 2023-01-03
conference_dates = [2023-02-01, 2023-02-05, 2023-02-12]
+++
