### ISSUE TITLE
Pagination doesn't work well when there are pages in 'pages' folder

### ISSUE THREAD

**Issue by michaelscodingspot** [gohugoio/hugo#10171]
### What version of Hugo are you using (`hugo version`)?
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

### Does this issue reproduce with the latest release?
Yes

When placing pages in the folder **content\pages**, the pagination from the home page doesn't well work for me. More specifically, the filtering doesn't work. I can't filter to just posts or just pages for example. The reason I believe is that when clicking on the 2nd, 3rd, 4th... pages the url becomes `/pages/1/`, `/pages/2/`, etc.  and since I have a `pages` folder inside `content`, another layout takes over.
When renaming the folder to anything else, the issue resolves but it took me a long time to find the root cause.

**Comment by jmooring** [comment]
I am unable to reproduce the problem. Here's a minimal example:

```bash
git clone --single-branch -b hugo-github-issue-10171 https://github.com/jmooring/hugo-testing hugo-github-issue-10171
cd hugo-github-issue-10171
hugo server
```

**Comment by michaelscodingspot** [comment]
I wasn't able to reproduce on that repo either. Tried to copy everything possible from my project but doesn't reproduce. I'll close for now and play a little more. I'll reopen if I'm able to reproduce.
