### ISSUE TITLE
support for upnp igw / tor / ipfs connectivity

### ISSUE THREAD

**Issue by mh-cbon** [gohugoio/hugo#10173]
Hi,

Have you considered adding support for those technologies out of the box into Hugo,
either via mod or core system, dunno.

for an embedded tor connectivity lib,
https://github.com/ipsn/go-libtor
https://github.com/cretz/bine

for upnp _Internet Gateway_ (the igw thing described in the spec)
https://github.com/huin/goupnp

for IPFS, i admit i dont know, I never took the time myself to dig that tech enough. 
Though, i bet something similar exists.

Along the way, it would be nice to support some free dns providers for upnp related stuff. 
You know people, when they see an IP, unfortunately they go wild.

To give out some context, i am considering hosting my own blog, 
and i was thinking writing a bootstraper around my hugo website setup.
A simple program that would perform the upnp queries to bnd the host, query over a free dns thing to register the IP, open up the tor socket and bnd all the stuff etc etc
I figured i might throw my ideas here before jumping into the usual hack the world thing.

Thanks reading and considering. I look forward to read constructive comments, and hopefully, positive support about that.

**Comment by jmooring** [comment]
Hugo provides a built-in server (run via `hugo server`) to assist with local development only. The built-in server should _not_ be used for production. With this understanding, is your proposal still relevant, and if so, how?
