### ISSUE TITLE
can't install hugo from source

### ISSUE THREAD

**Issue by zhanghe9702** [gohugoio/hugo#10172]
### What version of Hugo are you using (`hugo version`)?

<pre>
zhanghe@zhanghe-System-Product-Name:~/hugo$ git log
commit b017f7cb0136ee33f5d19749a15bf3365a991ac5 (HEAD -> master, origin/master, origin/HEAD)
Author: satotake <doublequotation@gmail.com>
Date:   Sun Aug 7 23:15:28 2022 +0900

</pre>

### Does this issue reproduce with the latest release?
yes
```
zhanghe@zhanghe-System-Product-Name:~/hugo$ go install --tags extended
# runtime/internal/syscall
../goroot/src/runtime/internal/syscall/syscall_linux.go:34:3: //go:uintptrkeepalive is not allowed in the standard library
```
### go version
```
zhanghe@zhanghe-System-Product-Name:~/hugo$ go version
go version go1.18.3 linux/amd64
```

**Comment by bep** [comment]
We're building on Linux on GitHub actions, and that works. I even Googled your error message and got no results, which is a first.

**Comment by anthonyfok** [comment]
Hi @zhanghe9702!

Your name reminds me of the Chinese mariner/explorer hero 郑和 :+1:

I would like to echo what Bjørn Erik said: Hugo has been building without error here on my Debian sid machine, in my Ubuntu VM or LXD container, on Debian build daemons (see <https://buildd.debian.org/status/package.php?p=hugo>), and on Launchpad (see <https://launchpad.net/~gohugoio/+snap/hugo-extended>).

To help us investigate:

1. Please provide more information, specifically, which Linux distribution and version you are using.

2. Please try the most recent Go releases, specifically go1.18.5 and go1.19

3. If the problem persists with the latest Go releases, please run
    ```bash
    go install --tags extended -v -x -a 2>&1 | tee hugo-test-build-issue-10172.log
    xz -9v hugo-test-build-issue-10172.log
    ```
    and attach the resulting hugo-test-build-issue-10172.log.xz to us?

Thanks for your help!

**Comment by zhanghe9702** [comment]
as i known, runtime  is another builtin library in golang, why report `go:uintptrkeepalive is not allowed in the standard library` error :), this marker only searched in `runtime/internal/syscall` package...

**Comment by zhanghe9702** [comment]
golang 1.18.1 OK for install
```
zhanghe@zhanghe:~/hugo$ go install --tags extended 
go: downloading github.com/alecthomas/chroma/v2 v2.2.0
go: downloading github.com/bep/clock v0.3.0
go: downloading github.com/bep/overlayfs v0.6.0
go: downloading github.com/spf13/fsync v0.9.0
go: downloading github.com/bep/godartsass v0.14.0
go: downloading github.com/bep/golibsass v1.1.0
go: downloading github.com/pelletier/go-toml/v2 v2.0.2
go: downloading github.com/tdewolff/parse/v2 v2.6.0
go: downloading github.com/gohugoio/locales v0.14.0
go: downloading github.com/aws/aws-sdk-go v1.43.5
go: downloading gocloud.dev v0.24.0
go: downloading google.golang.org/api v0.76.0
go: downloading github.com/gohugoio/localescompressed v1.0.1
go: downloading github.com/kyokomi/emoji/v2 v2.2.9
go: downloading github.com/jdkato/prose v1.2.1
go: downloading github.com/mitchellh/hashstructure v1.1.0
go: downloading github.com/clbanning/mxj/v2 v2.5.6
go: downloading github.com/niklasfasching/go-org v1.6.5
go: downloading github.com/yuin/goldmark v1.4.12
go: downloading github.com/bep/gitmap v1.1.2
go: downloading github.com/gobuffalo/flect v0.2.5
go: downloading github.com/hairyhenderson/go-codeowners v0.2.3-0.20201026200250-cdc7c0759690
go: downloading github.com/BurntSushi/locker v0.0.0-20171006230638-a6e239ea1c69
go: downloading github.com/cli/safeexec v1.0.0
go: downloading github.com/disintegration/gift v1.2.1
go: downloading golang.org/x/image v0.0.0-20211028202545-6944b10bf410
go: downloading github.com/dlclark/regexp2 v1.4.0
go: downloading github.com/Azure/azure-pipeline-go v0.2.3
go: downloading github.com/Azure/azure-storage-blob-go v0.14.0
go: downloading github.com/google/wire v0.5.0
go: downloading cloud.google.com/go v0.101.0
go: downloading cloud.google.com/go/iam v0.3.0
go: downloading cloud.google.com/go/storage v1.22.0
go: downloading github.com/googleapis/gax-go/v2 v2.3.0
go: downloading golang.org/x/net v0.0.0-20220607020251-c690dde0001d
go: downloading github.com/gohugoio/go-i18n/v2 v2.1.3-0.20210430103248-4c28c89f8013
go: downloading github.com/bep/tmc v0.5.1
go: downloading github.com/bep/gowebp v0.1.0
go: downloading github.com/rwcarlsen/goexif v0.0.0-20190401172101-9e8deecbddbd
go: downloading github.com/muesli/smartcrop v0.3.0
go: downloading golang.org/x/crypto v0.0.0-20211108221036-ceb1ce70b4fa
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/googleapis/go-type-adapters v1.0.0
go: downloading github.com/aws/aws-sdk-go-v2 v1.9.0
go: downloading github.com/aws/aws-sdk-go-v2/config v1.7.0
go: downloading github.com/tdewolff/minify/v2 v2.11.10
go: downloading github.com/sanity-io/litter v1.5.5
go: downloading github.com/bep/goat v0.5.0
go: downloading github.com/getkin/kin-openapi v0.97.0
go: downloading github.com/evanw/esbuild v0.14.43
go: downloading github.com/invopop/yaml v0.1.0
go: downloading github.com/mailru/easyjson v0.0.0-20190626092158-b2ccc519800e
go: downloading github.com/aws/smithy-go v1.8.0
go: downloading github.com/aws/aws-sdk-go-v2/credentials v1.4.0
go: downloading github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.5.0
go: downloading github.com/aws/aws-sdk-go-v2/service/sso v1.4.0
go: downloading github.com/aws/aws-sdk-go-v2/internal/ini v1.2.2
go: downloading github.com/aws/aws-sdk-go-v2/service/sts v1.7.0
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.3.0
zhanghe@zhanghe:~/hugo$ which hugo
/home/zhanghe/go/bin/hugo

```

**Comment by anthonyfok** [comment]
> as i known, runtime is another builtin library in golang, why report `go:uintptrkeepalive is not allowed in the standard library` error :), this marker only searched in `runtime/internal/syscall` package...

The error is reported by the Go compiler, not by Hugo.
这是 Go 在编译 Hugo 时的报错；编译没有成功，Hugo 根本没有被执行，所以不是 Hugo 自己的报错。

> golang 1.18.1 OK for install

Thank you for testing with a different go version.  This shows that it is not a bug in Hugo, but probably a glitch in how go1.18.3 interacted with your other system libraries.  （但奇怪的是，我特意下载了 go1.18.3 来测试，却无法重现你遇见的 `go:uintptrkeepalive is not allowed in the standard library` 错误。 Strangely, I'm unable to reproduce this same error with go1.18.3 either, testing on Debian.）

That said, I highly recommend that you upgrade to go1.18.5 or go1.19, because these latest releases resolve several security vulnerabilities.  强烈建议您升级到 go1.18.5 或 go1.19，因为新版修正了好些安全漏洞。

As it seems to be an isolated incident that is resolved by using a different Go version or by simply recompiling, I don't think this is a Hugo bug, and am hereby closing this bug report.  Please feel free to re-open this bug report if you encounter compilation issue with go1.18.5 or go1.19.
