### ISSUE TITLE
markdown footnotes don't work within columns shortcode

### ISSUE THREAD

**Issue by jpritikin** [gohugoio/hugo#10203]
### What version of Hugo are you using (`hugo version`)?

hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

### Does this issue reproduce with the latest release?

Yes. See https://github.com/jpritikin/coach/blob/main/content/docs/psychedelics/_index.md which I pasted below with a footnote:

---
title: Psychedelics
bookCollapseSection: true
weight: 4
bookToc: false
---

# Psychedelics

{{< details "Show me research on drug harms in the UK" >}}

![Drug harms](nutt-2010-fig2.png)

Nutt, D. J., King, L. A., & Phillips, L. D. (2010). Drug harms in the UK: a multicriteria decision analysis. *The Lancet, 376*(9752), 1558-1565.

{{< /details >}}

{{< columns >}}

## My experience

Psychedelics are substances that reveal and amplify your inner experience.

I have personal experience with

*   Psilocybin
*   Salvia divinorum
*   Cannabis
*   Daime (a.k.a. ayahuasca)

I am a member of
- [Sacred Garden Church](https://sacredgarden.life/)
- [Santo Daime](https://en.wikipedia.org/wiki/Santo_Daime)[^catholic]

{{< hint warning >}}
Psychedelics are not for everybody.
{{< /hint >}}

<--->

<table>
<tr>
<td>
<picture style="display: block;">
<img alt="Sacred mandala" src="sacred_mandala.webp">
</picture>
</td>
<td class='rotate'><div>Credit: Midjourney "sacred mandala"</div></td>
</tr/>
</table>

{{< /columns >}}

## Notes:

[^catholic]: I am a bit embarrassed to be affiliated with Catholicism given its [sordid history](https://en.wikipedia.org/wiki/Catholic_Church). In general, I admire the best of all of the world's religions.

----

Footnote is rendered incorrectly as:

![image](https://user-images.githubusercontent.com/2002771/186581445-92a1acec-7439-47b6-94a6-bd0996e99448.png)

**Comment by jmooring** [comment]
This behavior is caused by:

- The notation used to call the shortcode (`{{< foo >}}` instead `{{% foo %}}`)
- The shortcode itself (passing `.Inner` through `.Page.RenderString`)

Here's a related example:
<https://discourse.gohugo.io/t/35165>

If you need further assistance (questions or troubleshooting) please create a new topic on the forum (https://discourse.gohugo.io/). We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
