### ISSUE TITLE
Configuring Table of content title translation (i18n)

### ISSUE THREAD

**Issue by benoitparis** [gohugoio/hugo#10214]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
 v0.101.0
</pre>

### Does this issue reproduce with the latest release?
it does

----

It seems that there is no way to translate the TOC title. It stays at "Table of contents", when I'd like it to be "Sommaire" in another language. The documentation is unclear on this. I did not find any information either in markup sections or multilingual configuration.

I did find how startLevel, endLevel, and ordered options are used here:

https://github.com/gohugoio/hugo/blob/a7e3da242f98d4799dad013d7ba2f285717640d6/markup/tableofcontents/tableofcontents.go

but the string rendering starts at "<nav id" and the title appears just before that in the HTML.

Can I configure it, and how?

**Comment by jmooring** [comment]
Given this markdown:

```
## Heading Level 2

### Heading Level 3
```

Hugo renders `.TableOfContents` to:

```
<nav id="TableOfContents">
  <ul>
    <li><a href="#hl2">HL2</a></li>
    <li><a href="#hl3">HL3</a></li>
  </ul>
</nav>
```

Hugo does not render a title for the TOC. The issue you are experiencing is related to your templates or theme.

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
