### ISSUE TITLE
Lightweight tags v0.102.0 and v0.102.1 not picked up by snapcraft by default (git describe)

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugo#10225]
Since the switch to Hugoreleaser in v0.102.0, new git tags `v0.102.0` and `v0.102.1` were created as _lightweight_ tags instead of _annotated_ tags.  This has the side effect of our snap/snapcraft.yaml having `version: git`, i.e. using `git describe` (but apparently without `--tags` flag) to detect the latest tagged version, released v0.102.1 as something like `v0.101.0+git47.02bbc3b1` instead.  I ended up overriding the version number in commit ff176d5f61486700ef29270eed08c6efb776b1ee to get it to show `0.102.1`.

Fortunately, there is another way that let us support lightweight tags by replacing `version: git` with `adopt-info` which allows us to support lightweight tags and to customize the version for the hugo snap, e.g.:

```bash
snapcraftctl set-version "$(git describe --tags --always --match 'v[0-9]*' | sed 's/^v//; s/-/+git/; s/-g/./')"
```

I am going to push a commit that does exactly that in a few minutes so that snapcraft would generate the correct version string no matter the tag is annotated or not, with the benefit of removing the initial "v" from the snap version, as the norm seems to be.

@bep, was the change from annotated tags to lightweight tags intentional?  I couldn't find the git tag creation command in Hugoreleaser, but I wasn't looking very hard.  Anyhow, Cheers!

**Comment by bep** [comment]
>@bep, was the change from annotated tags to lightweight tags intentional? 

The tags are now created by GitHub against a specific commit when I hit the "publish release" button. I will see if there's a setting to create annotated tags.

In the old workflow we had to push the tag to GitHub before we created the release, which had all sorts of troubles. The release sometimes failed (e.g. timeout), so I had to close my eyes and delete the remote tag and start again. This was a bad thing, of course, but the alternative would be too much work. One problem was Go's notary database (gosum); if one person did a `go get ...hugo@latest` before I managed to delete the tag, that version was basically in a funky state forever (you could not install via go install).

The new workflow is refreshingly much bettter, as I can do as many test releases as I want (testing the build setup etc.) without having to worry.

But I'll have a look re the tags.

**Comment by bep** [comment]
I don't see any setting for this in the GitHub API, unfortunately.

But, I thought we already did this replacement:

https://github.com/gohugoio/hugo/blob/master/releaser/releaser.go#L154

Maybe the regexp is off, but that's fixable.

If you want to try to fix it, you can:

```
# Check out something that looks like a release branch
checkout -b release-0.123.0
go run -tags release main.go release --step 1 --skip-push
```

And see what that creates.

**Comment by anthonyfok** [comment]
> The tags are now created by GitHub against a specific commit when I hit the "publish release" button. I will see if there's a setting to create annotated tags.

Thank you for your detailed explanation!  I never realized the release workflow was fraught with perils, which I guess has something to do with how GitHub bolts on the "release" concept on top of git tags.  Very valuable lesson indeed!

The use of "Publish release" button is definitely the way to go, especially how this new workflow is so much more robust and reliable.  Thanks for sharing that experience with me!  My team at work mostly uses the "Publish release" button on GitHub too, and it is really good to know its use can alleviate potential problems with manually pushing a git tag and drafting a release afterward.

Judging from https://github.com/isaacs/github/issues/1916 and the subsequent discussion at https://github.com/orgs/community/discussions/4924, I don't think the creation of annotated tags from GitHub's web interface is coming any time soon.  :sweat_smile:

But that's OK: with commit e0ba1a805aaa0d0e8ca2563c498722abb2851293 in place, snapcraft should be able to detect the correct version from the lightweight tags just fine.  :-)

**Comment by anthonyfok** [comment]
> I don't see any setting for this in the GitHub API, unfortunately.
> 
> But, I thought we already did this replacement:
> 
> https://github.com/gohugoio/hugo/blob/master/releaser/releaser.go#L154
> 
> Maybe the regexp is off, but that's fixable.
> 
> If you want to try to fix it, you can:
> 
> ```
> # Check out something that looks like a release branch
> checkout -b release-0.123.0
> go run -tags release main.go release --step 1 --skip-push
> ```
> 
> And see what that creates.

Very cool!  Thanks for showing me the snapcraft string replacement code as well as the release command!  Thanks for writing that magic for modifying snapcraft.yaml!

That said, it looks like modern version of snapcraft has added the ability to set the version and the grade programmatically, something I'm sure wasn't possible when we first started years ago: <https://snapcraft.io/docs/using-external-metadata#heading--scriptlet>

So, instead of fixing the REGEXP for `version:`, I am actually thinking of changing snapcraft.yaml further to read `Suffix` from common/hugo/version_current.go and set the `grade` to `stable` or `devel` accordingly, so that releaser/releaser.go no longer needs to modify snapcraft.yaml.  One less file to worry about.  I'll send a PR in the near future.  :grin:
