### ISSUE TITLE
Asset hugo_0.102.0_Linux-64bit.deb has files in wrong location

### ISSUE THREAD

**Issue by zaitseff** [gohugoio/hugo#10220]
Thanks for creating and releasing Hugo!

The latest release asset for Debian, [hugo_0.102.0_Linux-64bit.deb](https://github.com/gohugoio/hugo/releases/download/v0.102.0/hugo_0.102.0_Linux-64bit.deb), has its built files in the wrong location:

```
$ dpkg-deb -c hugo_0.102.0_Linux-64bit.deb
-rwxr-xr-x root/root     11347 2022-08-29 02:28 ./LICENSE
-rwxr-xr-x root/root     10927 2022-08-29 02:28 ./README.md
-rwxr-xr-x root/root  55280808 2022-08-29 02:35 ./hugo
```

If one were to install this DEB file, it would place the `hugo` binary in the root directory.  It should be something like `/usr/local/bin/hugo` instead.  Similarly, `LICENSE` and `README.md` should be non-executable and placed in something like `/usr/local/share/doc/hugo`.

Previous releases using the old build process did exactly that.

**Comment by zaitseff** [comment]
I haven't investigated any other build assets: similar issues may exist with the new build setup.

**Comment by bep** [comment]
I'm pretty sure this is a "Deb thing" only, thanks for the report, I will fix this tomorrow.

**Comment by zaitseff** [comment]
Thanks for the quick response!  Yes, it seems that all DEB versions (64bit, ARM64, _extended 64bit, ARM64) have this particular issue.

**Comment by brycewray** [comment]
Ah. Am assuming this is why my usual GitHub Action for building the site (with Embedded Dart Sass) failed, with a `hugo: command not found` error, after it installed `hugo_extended_0.102.0_Linux-64bit.deb`:

```
check_suite_focus=true#step:8:8).sh: line 1: hugo: command not found
Error: Process completed with exit code [12](https://github.com/brycewray/hugo_site/runs/8060357563?
```

But, as Scarlett O’Hara would remind us, “Tomorrow is another day.” 😄

**Comment by bep** [comment]
@brycewray yea, thinking about it I should have deleted those Debs when this issue was raised, that would have produced less noise ...

**Comment by bep** [comment]
Just a note, I checked one of the deb archives in v0.101.0;

```
root@ubuntu:~/hugo/debtest# dpkg -c hugo_0.101.0_Linux-ARM.deb
drwxr-xr-x 0/0               0 2022-06-16 07:51 ./usr/
drwxr-xr-x 0/0               0 2022-06-16 07:51 ./usr/local/
drwxr-xr-x 0/0               0 2022-06-16 07:51 ./usr/local/bin/
-rwxr-xr-x 0/0        47710208 2022-06-16 07:26 ./usr/local/bin/hugo
```

Just the binary, no "extra files", which is what I'm going to do here.
