### ISSUE TITLE
Enable config.yaml to exclude sections from RSS

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugo#10224]
Something like:

```yaml
rss:
  exclude:
    sections: [webdev, secret]
```

**Comment by willfaught** [comment]
For what it's worth, I ended up doing this myself with a site parameter and custom logic in the RSS template. Feel free to close if that ability is good enough.

**Comment by chandlerc** [comment]
> For what it's worth, I ended up doing this myself with a site parameter and custom logic in the RSS template. Feel free to close if that ability is good enough.

Do you have a link to an example? I'm hitting the same issue, and it'd likely save me some time figuring it all out myself.

**Comment by willfaught** [comment]
@chandlerc I misremembered. I ended up making the setting per-page instead of per-section:

- https://github.com/willfaught/paige/blob/master/layouts/_default/rss.xml#L11
- https://github.com/willfaught/paige/blob/master/layouts/_default/rss.xml#L39

It would be simple enough to adapt this approach to entire sections, though.

**Comment by jmooring** [comment]
Like many of the requested changes to embedded templates, including shortcodes, this is best handled at the theme or template level.
