### ISSUE TITLE
Illegal shortcode state when using escaped quotes in shortcode arguments

### ISSUE THREAD

**Issue by hugcis** [gohugoio/hugo#10236]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.102.1+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

This issue happens with the latest release `(v0.102.1)` but did not happen with `v0.101.0`.

### Description

Shortcodes with escaped quotes in arguments fail with `Illegal shortcode state`. It was also reported in Discourse (https://discourse.gohugo.io/t/hugo-v0-102-1-illegal-shortcode-state/40285)

#### Create default site ✅
<pre>
$ hugo new site quickstart  
Congratulations! Your new Hugo site is created [...]
$ cd quickstart
</pre>

#### Create default index page with a shortcode with quoted string ✅
<pre>
$ hugo new _index.md
Content "/Users/hugo/testhugo/quickstart/content/_index.md" created
$ echo '{{< figure src="/media/spf13.jpg" title="Steve \"Francia\"" >}}' >> content/_index.md
</pre>

#### Build ❌
<pre>
$ hugo -D
hugo v0.102.1+extended darwin/arm64 BuildDate=unknown
Error: Error building site: "/home/test/quickstart/content/_index.md:7:1": Illegal shortcode state
Total in 7 ms
</pre>

**Comment by jmooring** [comment]
Git bisect says 223bf2800488ad5d38854bbb595d789bc35ebe32 is the first bad commit.

With v0.101.0

```
{{< sc foo="\"wibble\"" >}}  --> (.Get "foo") --> "wibble" (with quotes)
```

With 223bf2800488ad5d38854bbb595d789bc35ebe32

```
{{< sc foo="\"wibble\"" >}}  --> (.Get "foo") --> <nil>
```

MRE

```bash
git clone --single-branch -b hugo-github-issue-10236 https://github.com/jmooring/hugo-testing hugo-github-issue-10236
cd hugo-github-issue-10236
hugo
```
