### ISSUE TITLE
Release Hugo extended binary for Linux arm64 platform 

### ISSUE THREAD

**Issue by odidev** [gohugoio/hugo#10233]
Hi Team, 

I have explored and it looks like you are not releasing Hugo extended binary for Linux arm64 platform. 

It will be really helpful if the binary is released for Linux arm64 platform. 

If required I will be willing to contribute.

**Comment by bep** [comment]
How well have you explored?

<img width="508" alt="image" src="https://user-images.githubusercontent.com/394382/187614149-237540b1-ffae-479e-b690-b78a1e33192d.png">

**Comment by odidev** [comment]
Hi @bep 

Apologies for the trouble I have caused and thanks for sharing the details, I missed the new release and hence raised the issue.

**Comment by bep** [comment]
@odidev no problems, it's only been there for a few days :-)
