### ISSUE TITLE
Raise warning when Scratch variable collides with reserved keywords

### ISSUE THREAD

**Issue by mij** [gohugoio/hugo#10242]
I'm just out of a multi-hour troubleshooting where SerHack was very useful on IRC.

The [LoveIt theme] (https://github.com/dillonzq/LoveIt) with 2000+ stars implements logic to track which JS assets should be included based on which libraries are actually used by a page.

They do so using a Scratch, which they named "this":

- Setting example: https://github.com/dillonzq/LoveIt/blob/master/layouts/shortcodes/echarts.html#L6
- Getting example: https://github.com/dillonzq/LoveIt/blob/master/layouts/partials/assets.html#L130

This was working highly unpredictably, with assets being included in some pages and not in others. The cause of this was also extremely hard to troubleshoot.

Credits to SerHack in IRC to mention that the `this` naming for the scratch may be the cause of the issue. Renaming the scratch to a different value resolved the issue.

It would be nice if Hugo issues a warning when a scratch name is used which may collide with a reserved symbol. Because it works sometimes, and sometimes not, failure to issue a warning will allow developers to accrue heisenbugs in their codes, that are only found long after, and troubleshot at great expense.

**Comment by jmooring** [comment]
The word `this` is not reserved.

> Renaming the scratch to a different value resolved the issue.

I would be interested to see a minimal reproducible example that proves this. I suspect the problem is still present, perhaps intermittently, or more than one thing was changed.

**Comment by bep** [comment]
To my knowledge, there are no such things as "reserved this keys". There may be situations where a theme may use some keys that's intervenes, but if that is a problem, I would say that you will almost also have concurrency issues.

I suggest you start a new thread here:

https://discourse.gohugo.io/
