### ISSUE TITLE
baseURL not applied when host is 127.0.0.1 / localhost, or just a slash.

### ISSUE THREAD

**Issue by mh-cbon** [gohugoio/hugo#10251]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.102.3-b76146b129d7caa52417f8e914fc5b9271bf56fc linux/amd64 BuildDate=2022-09-01T10:16:19Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
yes.

### Issue

Start the server with `hugo_0.102.3_Linux-64bit/hugo server --baseURL=http://127.0.0.1:49100/ --port=47000`, browse to '/', check the links, it displays `href="http://127.0.0.1:47000/...` instead of `href="http://127.0.0.1:49100/`

Tried with `hugo_0.102.3_Linux-64bit/hugo server --baseURL=http://localhost:49100/ --port=47000`, the hostname gets resolved to the local ip.

Tried with `hugo_0.102.3_Linux-64bit/hugo server --baseURL=/ --port=47000` The hrefs are like `href="//:47000/pos...` 

It would be nice if the system is not too smart when `base-url = /` so everything just works flawlessly.

**Comment by bep** [comment]
>It would be nice if the system is not too smart when base-url = / so eve

A slash isn't a valid baseURL.

I suggest you look at `hugo server -h`. There are flags there that can help you with this.

**Comment by mh-cbon** [comment]
Thanks. That did not occur to me that the `appendPort` flag was made for that end too.

**Comment by mh-cbon** [comment]
Hi again, i ran into that issue again, using `-b=/www/` (still an invalid baseURL) It returns a weird url sch as `///www/`.
This seems related to that specific code 
https://github.com/gohugoio/hugo/blob/a5cda5ca4dc9ced8179eb6bcccb1bbdc567afe17/commands/server.go#L696 I guess, it could do `if u.Host == "" && !strings.HasPrefix(s, "/") {` 
I dont see hostnames starting with /, or a scheme based url starting with /
