### ISSUE TITLE
--noHTTPCache flag missing from hugo --help

### ISSUE THREAD

**Issue by callaloo** [gohugoio/hugo#10279]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.101.0
</pre>

### Does this issue reproduce with the latest release?
Not sure. But the flag is missing in v. 0.101.0

**Comment by bep** [comment]
It's only relevant for the server:


<img width="614" alt="image" src="https://user-images.githubusercontent.com/394382/190335610-0ccbebc0-2c1c-41cc-887b-63b6e62879f1.png">
