### ISSUE TITLE
Hugo server cannot find page when file path contains bytes > 0x80

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10287]
With this structure...

```text
content/
├── post/
│   └── hügö.md
└── _index.md
```

...`hugo server` displays "Page Not Found" when visiting `http://localhost:1313/post/hügö/`. 

- This problem is limited to `hugo server`. The page is correctly rendered to public when running `hugo`.
- Problem was introduced in v0.103.0.
- Git bisect says a5cda5ca4dc9ced8179eb6bcccb1bbdc567afe17 is the first bad commit

Ref: <https://discourse.gohugo.io/t/40560/>

MRE:

```bash
git clone --single-branch -b hugo-github-issue-10287 https://github.com/jmooring/hugo-testing hugo-github-issue-10287
cd hugo-github-issue-10287
hugo server
```

**Comment by bep** [comment]
To be clear: This was introduced back when the server redirect feature was added, but obviously became more visible now that we add a default 404 redirect if not set.

**Comment by bep** [comment]
@kusma this issue is closed, if there are related issues they need to be described in a new issue.

**Comment by kusma** [comment]
@bep: I'm well aware. Did you even read what I wrote?

**Comment by bep** [comment]
@kusma yes I read it, but the thing is, my GitHub notification log is very busy, so I rarely read comments on closed threads, which means I need to be strict about this. So, if you still think there is a related issue here, I would appreciate if you could open a new issue.
