### ISSUE TITLE
Allow whitelisting mediaTypes used in resources.GetRemote

### ISSUE THREAD

**Issue by dirtymew** [gohugoio/hugo#10286]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.103.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes

Hi there

I got a build error - `resources.GetRemote : failed to resolve media type for remote resource `

while trying to get remote resources with content types of MS Office files:

- .doc     `application/msword`
- .docx     `application/vnd.openxmlformats-officedocument.wordprocessingml.document`
- .xls     ` application/vnd.ms-excel`
- .xlsx     `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`
- .ppt    ` application/vnd.ms-powerpoint`
- .pptx    ` application/vnd.openxmlformats-officedocument.presentationml.presentation`

MediaType are also added to config file and with other additional MediaTypes like zip `application/zip` `resources.GetRemote ` works ok. Trying to add Options with "Content-Type" to GetRemote request have no effect.

P.S.
also found mistake in [docs](https://gohugo.io/content-management/page-resources/#properties)
correct mime type for PowerPoint  `application/vnd.ms-powerpoint`, not  `application/vnd.mspowerpoint`

**Comment by cyberdean** [comment]
I encounter the same problem, on hugo 0.108.0, with `image/avif` media type. (.avif)

Adding it to config.yaml does not help (same error message)
```yaml
mediaTypes:
  image/avif:
    suffixes:
      - avif
```

**Comment by bep** [comment]
The mime TYPE detection in GetRemote is a little bit restrictive, we don't just look at the suffix. This comes from security concerns, but that means that in its current form there will always be reports like the above.

So I suggest that we allow setting the MediaType directly:

```
{{ $r := resources.GetRemote "https://example.org" (dict "mediaType" "application/msword") }}
```

**Comment by jmooring** [comment]
@bep Would you consider this?

```
[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']
mediaTypes = ['image/avif','^application/vnd.openxmlformats',']
```

This would represent _additional_ media types, so the naming may not be great.

**Comment by bep** [comment]
@jmooring yea, that would probably be a better idea. I don't have a better name on the tip of my tongue.

**Comment by bep** [comment]
@jmooring OK, thanks for bringing this to my attention. Looking back at now, I don't see why we couldn't simply do:

```
{{ $r := resources.GetRemote "https://example.org" (dict "mediaType" "application/msword") }}
```

I don't see any obvious security implications in the above???

**Comment by bep** [comment]
OK, never mind, I think I get it now.

This is about overriding the "content sniffing", so yes, your suggestion makes perfectly sense, let's do that.

**Comment by jmooring** [comment]
If we do this...

```
{{ $r := resources.GetRemote "https://example.org" (dict "mediaType" "application/msword") }}
```

...we would have to know the expected media type in the response header  _before_ making the request. That wouldn't work with this (contrived) example:

content/about.md

```
+++
title = 'About'
download = 'https://example.org/a.foo'
+++
```

```text
{{ with .Params.download }}
  {{ if (urls.Parse .).IsAbs }}
    {{ with resources.GetRemote . }}
      <a href="{{ .RelPermalink }}" download>Download</a>
    {{ end }}
  {{ else }}
    ...
  {{ end }}
{{ end }}
```

So I'm back to...

```
[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']
mediaTypes = ['image/avif','^application/vnd.openxmlformats']
```

or similar.

**Comment by bep** [comment]
>...we would have to know the expected media type in the response header before making the request. That wouldn't work with this (contrived) example:

OK, now I think I get it; so in the examples above:

1. The response header is set to a sensible mime type.
2. But the content sniffing fails to resolve to that same mime type?

Is that correct? So an additional security config would whitelist some types saying we trust the response header value?

**Comment by jmooring** [comment]
> Is that correct?

Yes.

> So an additional security config would whitelist some types saying we trust the response header value?

Yes.

But I think we need to remember that, based on past behavior, someone will inevitably will do this:

```text
[security.http]
mediaTypes = ['.*']
```

But if you aim for your own foot, I think you deserve the consequences.

**Comment by bep** [comment]
>But if you aim for your own foot, I think you deserve the consequences.

I said this before, but: The security config is there mainly to avoid ... spring-guns.

**Comment by stefanv** [comment]
I didn't see any announcement of this in the release notes, and it's a change between 0.111 and 0.112. We now see:

```
Error: failed to create config from result: failed to decode "outputFormats": failed to decode output format configuration: error decoding '': media type "application/atom" not found
```

From the above, it looks like we have to explicitly allow the mimetype?
