### ISSUE TITLE
Extend .Summary and .IsTruncated to be used front matter keys.

### ISSUE THREAD

**Issue by hithismani** [gohugoio/hugo#10288]
Hey!

Not all our posts have content in the "body" of th markdown that needs to be summarised. Some of the strings I'd like summarised are actually in the front matter of the file.

1. Currently, .Summary and .IsTruncated only works for content within the body of the markdown file.
2. I'd like to know if we could extend that feature to the front matter keys as well, because I'd like to maintain the same summary length and truncate logic for the front matter keys too. 
3. Seeing a usage being something like "{{ .Params.founder_message | summary}}" (or .summarize) which ever seems ideal. 

I've been seeing that the only alternative has been to split the string by full stops currently, but I'd like something that maintains summary length from the config. 

Really sorry if this is already present as a feature or in the timeline. I tried my best to search through the docs and GitHub issues beforehand. 

Thanks!

**Comment by jmooring** [comment]
It seems like a partial would be sufficient. For example:
<https://discourse.gohugo.io/t/36676/5>
