### ISSUE TITLE
Multilingual improvements

### ISSUE THREAD

**Issue by mcexit** [gohugoio/hugo#10293]
## Automatically disable kinds for missing content
When enabling additional languages in the config, but without any content for those languages, it is still creating the default outputs for those languages.

> Note: This can be solved by setting `disableKinds` manually in those language-specific configs

Having something like causes errors without disabling the kinds of missing language-specific content:

```
{{if .Description -}}
<meta name="description" content="{{.Description}}" />
{{else -}}
{{	erroridf "description" "Missing .Description" -}}
{{end -}}
```

## Order `.Translations` by `defaultContentLanguage`
The only weight I care about for translations is the default content language. `.AllTranslations` seems to take `defaultContentLanguage` into account but `.Translations` does not unless I specify a weight.

## Consider defaulting `lang.Merge` to first match
I haven't fully thought out how this would work, but essentially it would let you get the first match if one exists and a variable for the language code of the match.

```
{{with .Description | lang.Merge -}}
<meta {{with .LangMerged}}lang="{{.}}"{{end}} name="description" content="{{.}}" />
{{else -}}
{{	erroridf "description" "Missing .Description" -}}
{{end -}}
```

**Comment by jmooring** [comment]
#### Automatically disable kinds for missing content

> Having something like causes errors without disabling the kinds of missing language-specific content

Code defensively by testing for content:

```text
{{ if .File}}
  {{ if .Description }}
    <meta name="description" content="{{ .Description }}">
  {{else -}}
    {{erroridf "description" "Missing .Description" }}
  {{ end }}
{{ end }}
```
#### Order .Translations by defaultContentLanguage

> `.AllTranslations` seems to take `defaultContentLanguage` into account but `.Translations` does not unless I specify a weight.

`.AllTranslations` and `.Translations` are sorted by `weight`. In the absence of weight, they are sorted alphabetically. The `defaultContentLanguage` does not affect the sort order of either `.AllTranslations` or `.Translations`.

If you don't want them sorted alphabetically, add weights.

#### Consider defaulting lang.Merge to first match

The [`lang.Merge`](https://gohugo.io/functions/lang.merge/) function fills in page gaps, not front matter gaps. Use a partial template to get the current language's front matter value, and fallback to another language's front matter value based on language weight (or alphabetically if weight is not set). For example:

<details>
<summary>layouts/_default/baseof.html</summary>

```text
{{ with partial "get-page-param.html" (dict "page" . "param" "description") }}
  <meta lang="{{ .lang }}"name="description" content="{{ .value }}">
{{ end }}
```
</details>
<br>

<details>
<summary>layouts/partials/get-page-param.html</summary>

```text
{{ $value := "" }}
{{ $lang := ""}}
{{ with index $.page.Params $.param }}
  {{ $value = . }}
  {{ $lang = $.page.Language.Lang }}
{{ else }}
  {{ range $p := $.page.Translations }}
    {{ with index .Params $.param }}
      {{ $value = . }}
      {{ $lang = $p.Language.Lang }}
      {{ break }}
    {{ end }}
  {{ end }}
{{ end }}
{{ return (dict "value" $value "lang" $lang) }}
```
</details>
<br>
