### ISSUE TITLE
Pages do not scroll on firefox desktop

### ISSUE THREAD

**Issue by aviita** [gohugoio/hugo#10302]
The is an issue in Azure Citadel site that the content is not scrollable on FireFox (desktop on Windows 11).
https://www.azurecitadel.com/network/vdc/monitor/

There is already some analysis that this is because of use of some old WebKit style CSS:
https://github.com/azurecitadel/azurecitadel/issues/104

### What version of Hugo are you using (`hugo version`)?
hugo_version=0.90.1

Firefox version 104.0.2 (64-bit).

### Does this issue reproduce with the latest release?

Do not know. Not involved with Citadel development, so have not tested this yet.

**Comment by aviita** [comment]
There are also somewhat similar issues, but maybe bit different analysis on firefox mobile:
https://github.com/gohugoio/hugo/issues/6517

Seems this could be different. Should likely dig out which theme the citadel is using.

**Comment by bep** [comment]
I don't see how this could have anything to do with Hugo, this needs to be solved in the template/style etc. source.
