### ISSUE TITLE
update release notes for v0.103.1 to mention spaces in filenames

### ISSUE THREAD

**Issue by kusma** [gohugoio/hugo#10311]
The fix in v0.103.1 also fixed spaces in filenames, which isn't mentioned in the release notes. This can cause confusion, so please consider updating it.

Requested here: https://github.com/gohugoio/hugo/issues/10287#issuecomment-1254804271

**Comment by bep** [comment]
OK, I misunderstood your original comment on the closed issue (I thought there were another code bug :-))

**Comment by bep** [comment]
Fixed
