### ISSUE TITLE
Warn when section's `_index.md` is dated in future with respect to it's content `*.md` instead of silently ignoring to generate new content

### ISSUE THREAD

**Issue by adhadse** [gohugoio/hugo#10323]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.99.0
</pre>

### Does this issue reproduce with the latest release?
With the latest release I wasn't able to reproduce this error (or maybe it's caching issue), To reproduce this with version `0.99.0` or earlier issue or maybe with latest release, **modify section's `_index.md` frontmatter `date` parameter to an earlier timestamp than the section's content `date`. This leads to Hugo silently not generating that section's content without giving any warning.**

**Comment by jmooring** [comment]
I am unable to reproduce the problem as described. Perhaps you are referring to what happens if a section's _index.md is dated in the future.

**Comment by adhadse** [comment]
@jmooring Yes, it the `_index.md` is dated in future, Hugo silently ignores to generate that section content. Although I wasn't able to reproduce with latest `0.104.0` release.

**Comment by jmooring** [comment]
@adhase If a content page's date is in the future, we don't publish without the `-F` option. We're doing the same thing for section pages (_index.md). The same is true if you set a section page's `draft` value to `true` --- it applies to the entire section.

**Comment by adhadse** [comment]
@jmooring 
I think it would be great if we can acknowledge the state and notify the user of what might be wrong. 
- **Giving a warning if the section is dated in future is probably a mistake which can go unnotice** (as it happened in my case)
   `Warning: One section with <no_of_pages> was found dated in future as compared to it's content`
- When generating table with `hugo server`, so that user knows it's not Hugo's fault

|                   | EN   | 
|---|---|
| Pages            |  71  |
|Paginator pages  |   0 |  
|Non-page files   |   0 |  
|Static files     | 334  |
|Processed images |   0 | 
|Aliases          |   5  |
| Sitemaps         |   1  |
|Cleaned          |   0  | 
| **Draft** | 5 | 
| **Section dated in future** | 1 |

**Comment by jmooring** [comment]
> is probably a mistake

That's debatable.

**Comment by Etbanscv** [comment]
I'm gray

**Comment by jmooring** [comment]
Related: https://github.com/gohugoio/hugo/issues/10381

Remember you can always do this as QA check:

```bash
hugo list drafts
hugo list expired 
hugo list future
```

What you're suggesting would require us to do the following for every section page, recursively through subsections:

If the section page (_index.md) is draft or expired or future, and if every page (recursively through subsections) within the section is not draft, and not expired, and not future, then throw a warning.

Which would require us to evaluate and render the pages in a particular sequence instead of concurrently.

I could be wrong, but I just don't see this happening.
