### ISSUE TITLE
Nested shortcode should render in logical order

### ISSUE THREAD

**Issue by mcexit** [gohugoio/hugo#10321]
I think this is related to #7848 but it doesn't affect just code blocks. I think it important to address this because otherwise, what most users are going to do is enable unsafe HTML and it could bite them in the butt later on.

A common use case:

`q.html`
> Shortcode
```go
<q>{{ markdownify .Inner }}</q>
```

`q.md`
> Content
```md
{{<q>}}**Parent** {{<q>}}*Child*{{</q>}}{{</q>}}
```

While certain decisions in how this is done may be intentional, what would make most sense here would be to have the parent in this example render its content separately from the child.

What one may expect, and what is difficult to accomplish here is to render this as:

```html
<q><strong>Parent</strong> <q><em>Child</em></q></q>
```

Instead, what you end up with is:

```html
<q><strong>Parent</strong> <!-- raw HTML omitted --><!-- raw HTML omitted -->Child<!-- raw HTML omitted --><!-- raw HTML omitted --></q>
```

You may end up with multiple levels of nested shortcodes, for instance using the example here [here](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-q-element) you may want to accomplish something like:

```md
{{<small>}}
In {{<cite>}}**Example One**{{</cite>}}, he writes {{<q>}}The **man** said {{<q>}}Things that **are** impossible just take longer{{</q>}}. I
disagreed with him{{</q>}}. Well, I disagree even more!
{{</small>}}
```

Unfortunately, there doesn't appear to be an easy way to do this currently.

**Comment by bep** [comment]
><q>{{ markdownify .Inner }}</q>

The above is (almost) never a right/good thing to do. So you need to come up with a better/more realistic example to start out this discussion.

**Comment by bep** [comment]
OK, let me ask you a different question: What do you mean by "render in logical order"?
