### ISSUE TITLE
Missing docker images on hub.docker.com for version 0.102.0 and upwards

### ISSUE THREAD

**Issue by Flauschbaellchen** [gohugoio/hugo#10324]
The latest docker image on https://hub.docker.com/r/klakegg/hugo is `0.101.0` which was pushed 3 months ago.
When searching for any higher version like `0.102.0` or `0.103.0` no images/tags can be found.

Possibly, the CI/CD does not push those images automatically anymore?

As the installation documentation still points to this repository, I think this is a bug.

**Comment by bep** [comment]
>As the installation documentation still points to this repository, I think this is a bug.

I agree, but I can only ask @klakegg kindly about it.

**Comment by klakegg** [comment]
Will fix it this week. :)

**Comment by klakegg** [comment]
This is fixed, so this issue may be closed.

**Comment by Flauschbaellchen** [comment]
Thanks for fixing it and pushing the missing images to the registry!
