### ISSUE TITLE
.Page.Store is not working in production mode

### ISSUE THREAD

**Issue by ivanduka** [gohugoio/hugo#10322]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.104.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

## Issue

Variables set with .Page.Store.Set are accessible with .Page.Store.Get only when using `hugo server`, but not when building the website with `hugo` command.

##  Source code

I was following the examples from https://gohugo.io/content-management/diagrams/#mermaid-diagrams

My content file `content/index.md` (to trigger the execution of the render hook):
````
```mermaid
Example mermaid code
```
````

The render hook `layouts/_default/_markup/render-codeblock-mermaid.html`:
```go-templates
<div class="mermaid">
  {{- .Inner | safeHTML }}
</div>
{{ .Page.Store.Set "hasMermaid" true }}
```

The template `layouts/single.html`:
```html
<html>
  <body>
    <h1>Mermaid variable: {{ default false (.Page.Store.Get "hasMermaid") }}</h1>
    <div>
      {{ .Content }}
    <div>
  </body>
</html>
```

The file `config.yml` is empty

Running with `hugo server` displays the `hasMermaid` variables as it should, but after building the website with `hugo` it is not working.

Apparently, there is difference in how the render hooks are handled in dev and prod environments.

## Reproducible minimal example: 
```bash
git clone https://github.com/ivanduka/page-store-bug
cd page-store-bug
hugo server
```
This will display the variable that was set in a render hook:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/39438519/192159925-f295e8ff-7bce-4cb4-a8a5-201f0a3191d4.png">

However, when building the website, this variable is not retrievable:
```
hugo && npx http-server public
```
In this case the variable is not set:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/39438519/192159940-26bed222-8504-4e48-90fa-8e7671059a3b.png">

I also tested the same source code with the Hugo from the first release that introduced `.Page.Store` (https://github.com/gohugoio/hugo/releases/tag/v0.93.0) and the same issue is there, so this is probably not a regression.

**Comment by bep** [comment]
```
<html>
  <body>
    <h1>Mermaid variable: {{ default false (.Page.Store.Get "hasMermaid") }}</h1>
    <div>
      {{ .Content }}
    <div>
  </body>
</html>
```

The render hook is invoked in `.Content´ where the variable gets set. You need to switch the order.
