### ISSUE TITLE
Static files get copied into project root folder when using hugo server

### ISSUE THREAD

**Issue by zabatonni** [gohugoio/hugo#10336]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.104.1-8958b8741f552c8024af5194330fbf031544a826+extended windows/amd64 BuildDate=2022-09-26T17:05:45Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
yes

When running hugo server, after few changes to content files and refreshing browser files and folders from static folder appear in project root directory somehow.

**Comment by bep** [comment]
Pretty sure this is the same as #8848 10334

**Comment by zabatonni** [comment]
Don't know if it's the same, but it can be related. When I update config, static files appear in project root folder, but I don't get any error.

**Comment by zabatonni** [comment]
0.104.2 fixed this issue
