### ISSUE TITLE
readFile returns escaped html / svg / xml, cannot inline raw xml

### ISSUE THREAD

**Issue by milahu** [gohugoio/hugo#10330]
https://github.com/gohugoio/hugo/issues/5789#issuecomment-476228077

<blockquote>

An SVG can be inlined by using readfile (or a readfile shortcode).

```
{{ readFile "/static/img/filename.svg" }}
```

</blockquote>

### actual result

svg source is escaped

```html
&lt;svg class=&#34;book-icon&#34; xmlns=&#34;http://
```

### expected result

svg source should be inlined raw

```html
<svg class="book-icon" xmlns="http://...
```

### related

svelte allows this with [@html](https://svelte.dev/tutorial/html-tags)

```svelte
<script>
  let someVariable = '<b>hello</b>'
</script>

<div>
  {@html someVariable}
</div>
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.99.1+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

yes, tested with d8aba18e05895723a6e42ea19be1cfbbed5bf98c

**Comment by jmooring** [comment]
```
{{ readFile "/static/img/filename.svg" | safeHTML }}
```

In the future, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
