### ISSUE TITLE
KaTeX table rendered as literal string

### ISSUE THREAD

**Issue by sorokod** [gohugoio/hugo#10350]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

hugo v0.104.2+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

YES

The following KaTeX snippet renders correctly on https://katex.org/

\begin{array}{c:c}
a & b \\ 
c & d \\
\end{array}

but the generated content from the same bracketed by `$$`s

is rendered as the literal:  
```
$$ \begin{array}{c:c} a & b \ c & d \ \end{array} $$
```

**Comment by jmooring** [comment]
Hugo, by itself, does not render LaTex equations[^1], so this is likely an issue with your theme or JS library. 

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

[^1]: Exception. LaTex equations in reStructuredText (`.rst`) documents are rendered by default
