### ISSUE TITLE
Microsoft Clarity feature update

### ISSUE THREAD

**Issue by Haebuk** [gohugoio/hugo#10368]
hi. I want to add a feature [Microsoft Clarity](https://clarity.microsoft.com/projects) to my blog. 

it requires add a code into index.html head tag. so I did, but when `hugo -t my-theme`, it disappeared.

could you update feature that use Clarity like Google Analytics?

or is there any method to apply Clarity? thank you.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
