### ISSUE TITLE
Add Cloudflare Web Analytics Support

### ISSUE THREAD

**Issue by L1ghtn1ng** [gohugoio/hugo#10369]
This is what the docs say where to put it "Add the JS Snippet below before the ending body tag on any of your HTML pages."

```<script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "add-token-here"}'></script>```

**Comment by jmooring** [comment]
This is easily added to a template while developing your site. There is no need to create yet another internal template that needs to be tested, maintained, etc.

**Comment by L1ghtn1ng** [comment]
I have added it, it is really simple so would not be hard to maintain at all but just thought it would be nice to have it built in for everyone.

On 4 Nov 2022, at 17:46, Joe Mooring ***@***.***> wrote:

﻿

This is easily added to a template while developing your site. There is no need to create yet another internal template that needs to be tested, maintained, etc.
