### ISSUE TITLE
Allow uppercase language codes in urls

### ISSUE THREAD

**Issue by misitebao** [gohugoio/hugo#10375]
Hopefully an option can be provided to allow uppercase language codes in URLs, similar to "disablePathToLower", although I fully understand the original intention of defaulting to lowercase, there are still some users who need to use uppercase language codes in URLs, such as: "pt-BR ", "zh-Hans", etc.

**Comment by jmooring** [comment]
Isn't this a duplicate of your issue https://github.com/gohugoio/hugo/issues/9404?

**Comment by misitebao** [comment]
@jmooring 
Yes, but the question has no follow-up.
