### ISSUE TITLE
When sorting a slice of strings (ascending), the literal "infinity" string always comes last

### ISSUE THREAD

**Issue by maw246** [gohugoio/hugo#10389]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.104.3-58b824581360148f2d91f5cc83f69bd22c1aa331+extended linux/amd64 BuildDate=2022-10-04T14:25:23Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

### Description of the Issue
Given a slice of strings, Hugo treats "infinity" as alphabetically last in the list.  E.g.:
```
{{delimit (slice "foo" "bar" "infinity" "alpha" "beta" "zeta" "yaml" "xylophone" | sort ) ", "}}
```
Produces:
```
alpha, bar, beta, foo, xylophone, yaml, zeta, infinity
```
It seems like `infinity` is being treated as a numeric value despite being defined as a string among other strings.

**Comment by jmooring** [comment]
Confirmed. 

```text
{{ slice "infinity" "z" "a" | sort }}  --> [a z infinity]
```

This isn't new behavior. Same results with v0.54.0.
