### ISSUE TITLE
Default title for nested taxonomies should be the base name

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#10380]
Currently it's possible to do:

```toml
[taxonomies]
"news/category" = "news/categories"
```

And the taxonomy pages will get the paths as expected. The default title, however (when no `_index.md` file is found) is set to `News/Categories`, which I suspect is not a great title.

I'm doing some simplification work in this department now, and had a failing test above, so I'll create an issue to mark that I'll change it so the title becomes the base name (e.g. `Categories`).

**Comment by jmooring** [comment]
Pretty sure we can close this as a duplicate of https://github.com/gohugoio/hugo/issues/11808

**Comment by bep** [comment]
This issue will be auto closed with my PR, so I will make the other a duplicate.

**Comment by bep** [comment]
Never mind, I had them mixed ....
