### ISSUE TITLE
permalinks filename doesn't working well with multilingual file

### ISSUE THREAD

**Issue by cra1nbow** [gohugoio/hugo#10385]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.104.3+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

I set permalinks setting with filename
```toml
[permalinks]
posts = "/:filename"
```

And I wrote files like this structure
```
content
ㄴ posts
    ㄴ test
        ㄴ index.kr.md
        ㄴ index.en.md
    ㄴ test2
        ㄴ index.kr.md
        ㄴ index.en.md
```

then permalink of `posts/test/index.kr.md` is `/index.kr` not `/test`

**Comment by jmooring** [comment]
I am unable to reproduce the problem. Try this:

```bash
git clone --single-branch -b hugo-github-issue-10385 https://github.com/jmooring/hugo-testing hugo-github-issue-10385
cd hugo-github-issue-10385
hugo server
```
