### ISSUE TITLE
Cannot create language-specific 404 template

### ISSUE THREAD

**Issue by jmau111** [gohugoio/hugo#10400]
### What version of Hugo are you using (`hugo version`)?

<pre>
v0.104.3
</pre>

### Does this issue reproduce with the latest release?
yes

### Description

It's not possible to use the folder pattern to have a different 404 per each language.

For example, `layouts/404.html` - `layouts/404.zh.html` won't work.

The only way I can make it work consists of using the `i18n` helper in a block:

```
{{ define "main" }}
{{ i18n "test" }}
{{ end }}
```

It's not very convenient, especially when your 404 layout needs another base template (usually much lighter than the global `baseof`).

My question is the following: is it something known and wanted?

**Comment by jafaican** [comment]
It is a known issue. You need to use the `i18n` folder to translate 404 page (template). But here's to hoping that that will change soon.

**Comment by jmau111** [comment]
@jafaican hi, that would be a nice fix!

**Comment by jmooring** [comment]
This was fixed with v0.123.0.
