### ISSUE TITLE
Two Panel / Three / Four Panel Navigation

### ISSUE THREAD

**Issue by gitexp2050** [gohugoio/hugo#10405]
Hi,

Many apps has multi-level navigation. Please provide the capability to have the sample

Two Panel: https://table.branham.org/#/en/main
Three Panel: https://lwbcast.org/Mobile
Four Panel: Slider Menu like top menu example https://www.codehim.com/menu/bootstrap-4-multi-level-hover-dropdown-menu-bootnavbar/

Thanks

**Comment by bep** [comment]
Thanks for the suggestion, but this can be done with templating/CSS today, and I don't think this fits very well into the core Hugo.
