### ISSUE TITLE
resources.Copy to original resource path points to wrong resource

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10412]
```text
assets/
└── a.jpg    # image is 600x400
```

#### This works as expected...

```text
{{ with resources.Get "a.jpg" }}
  {{ with .Resize "200x" | resources.Copy "foo.jpg" }}
    <img src="{{ .RelPermalink }}" width="{{ .Width }}" height="{{ .Height }}">
  {{ end }}
{{ end }}
```

```html
<img src="/foo.jpg" width="200" height="133">
```

#### But if you try to copy the resource to the original path (a.jpg)...

```text
{{ with resources.Get "a.jpg" }}
  {{ with .Resize "200x" | resources.Copy "a.jpg" }}
    <img src="{{ .RelPermalink }}" width="{{ .Width }}" height="{{ .Height }}">
  {{ end }}
{{ end }}
```

```html
<img src="/a.jpg" width="600" height="400">
```

Note that the `width` and `height` attributes are from the original image, not the resized image.

Why would you want to copy a resource to its original path? To have something other than this:

```html
<img src="/a_hu7ea6bbdd4d289c929adf1f5f39c46d1e_158382_200x0_resize_q75_box.jpg" width="200" height="133">
```

**Comment by bowman2001** [comment]
To copy a resource to its original path is also of concern, when an image is processed more than once. In the first step, images may be resized or cropped, etc. In the second step, a "srcset" is generated, which involves again resizing or filtering. Without copying the result of the first step to the original name, Hugo’s naming scheme concatenates two hashes and other information into the resulting filenames. These names then usually get so long, that Hugo truncates them to avoid problems. The part of the filename string containing  information about the last processing step is usually lost, then.I

**Comment by jmooring** [comment]
If fixing/implementing this is going to be expensive, perhaps we could disallow using the original resource path to avoid unexpected results (e.g., incorrect `.Width` and `.Height`).

**Comment by bep** [comment]
>If fixing/implementing this is going to be expensive or impossible

It was certainly not intended to be used this way. The technical reason is that we use the resource path as a cache key, but even if we fix that there is a "meta question" that I cannot wrap my head around:

If I do:

```
{{ $a := resource.Get "a.json" }}
{{ $acopy := $a | copy "a.json" }}
{{ $a.RelPermalink }}
{{ $acopy.RelPermalink }}
```

What would be the `RelPermalink` values above? If this was the MacOS Explorer, you would maybe imagine it to append a "Copy" suffix or something to the filename. But that would most likely not be the intention in the above.

I do agree it's a bug, but the fix isn't obvious. I'm in the process of simplifying lots of related stuff now, I have this issue in the back of my head while doing so.
