### ISSUE TITLE
Folders containing subfolders with extra files don't get lowercased

### ISSUE THREAD

**Issue by mxmerz** [gohugoio/hugo#10415]
I'm actually not sure if this is intended behaviour, but it seems like a bug to me:

## Steps to reproduce

Create a new hugo project with the following `content` folder structure (all files can be empty):

```
content
├── BAR
│  ├── _index.md
│  └── biz
│     └── some_file.jpg
└── FOO
   └── _index.md
```

When you run hugo on this project, it creates the following output in `public`:

```
public
├── BAR
│  ├── biz
│  │  └── some_file.jpg
│  └── index.xml
├── foo
│  └── index.xml
…
```

* **Expected Behaviour:** Both folder names `BAR` and `FOO` should be lowercased (or both uppercased).
* **Actual Behaviour:** Only the folder `FOO` gets lowercased, `BAR` remains uppercased in the output.

## shell script to recreate the bug

```sh
hugo new site test
cd test

# Create the content
mkdir -p content/FOO content/BAR/biz
touch content/FOO/_index.md
touch content/BAR/_index.md
touch content/BAR/biz/some_file.jpg

# Create an empty layout file.
touch layouts/index.html
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.105.0+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

yes

**Comment by jmooring** [comment]
To clarify, this content structure:

```text
content/
├── BAR/
│   ├── biz/
│   │   └── some_file.jpg
│   └── _index.md
├── FOO/
│   └── _index.md
└── _index.md
