### ISSUE TITLE
--minify breaks space between elements

### ISSUE THREAD

**Issue by QuAzI** [gohugoio/hugo#10424]
With --minify
![image](https://user-images.githubusercontent.com/1897605/200368003-c70a4d61-1a85-4458-ac25-4a9a693667a5.png)

Without --minify
![image](https://user-images.githubusercontent.com/1897605/200368224-abfee7de-0dd5-440f-acce-3435118bb1aa.png)

Theme m10c

HUGO_VERSION: 0.105.0
Extended

**Comment by jmooring** [comment]
We need to see the non-minified HTML.

**Comment by pamubay** [comment]
@QuAzI That's correct behavior, it's `<div>` vs `<div>` elements. `div` is __block-element__

This is the code of your template:

https://github.com/QuAzI/quazi.github.io/blob/4658aefb979423ffb2dd48aaa18fb6327cd239b4/themes/m10c/layouts/_default/single.html#L6-L25

You can test it here:

[go.tacodewolff.nl/minify](https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmh0bWwmc3JjPSUzQ2RpdiUzRUhlbGxvK1dvcmxkKzElM0MlMkZkaXYlM0UlMEQlMEElMEQlMEElM0NkaXYlM0VIZWxsbyslM0NzcGFuJTNFV29ybGQlM0MlMkZzcGFuJTNFKzIlM0MlMkZkaXYlM0UlMEQlMEElMEQlMEElM0NkaXYlM0UlM0NzcGFuJTNFSGVsbG8lM0MlMkZzcGFuJTNFKyUzQ3NwYW4lM0VXb3JsZCUzQyUyRnNwYW4lM0UrJTNDc3BhbiUzRTMlM0MlMkZzcGFuJTNFJTNDJTJGZGl2JTNFJTBEJTBBJTBEJTBBJTBEJTBBJTNDZGl2JTNFJTNDZGl2JTNFSGVsbG8lM0MlMkZkaXYlM0UrJTNDZGl2JTNFV29ybGQlM0MlMkZkaXYlM0UrJTNDZGl2JTNFNCUzQyUyRmRpdiUzRSUzQyUyRmRpdiUzRSUwRCUwQQ==)

---
references:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements
- https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements
