### ISSUE TITLE
Hugo "can't evaluate field Hugo in type *hugolib.pageState" when building site

### ISSUE THREAD

**Issue by McCoyAle** [gohugoio/hugo#10436]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release?
Yes, this is also a follow-up to this issue https://github.com/gohugoio/hugo/issues/10435

### Issue:
After successfully importing a Jekyll project into my Hugo project, Hugo output the following steps to follow:

1. `$ git clone https://github.com/spf13/herring-cove.git /Users/alexandram/test/themes/herring-cove`
2. `$ cd /Users/alexandram/test`
3. `$ hugo server --theme=herring-cove`

When following these commands, it seems that hugo is reporting that it is not able to execute one of the templates due to not being able to evaluate the hugo library page state. This was a jekyll project that was imported into an existing project. The existing project was created using the expected `hugo new site <test>` command. 

`Start building sites …
hugo v0.105.0+extended darwin/amd64 BuildDate=unknown
ERROR 2022/11/14 10:26:58 render of "page" failed: execute of template failed: template: partials/header.html:8:10: executing "partials/header.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
ERROR 2022/11/14 10:26:58 render of "page" failed: execute of template failed: template: partials/header.html:8:10: executing "partials/header.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
ERROR 2022/11/14 10:26:58 render of "page" failed: execute of template failed: template: partials/header.html:8:10: executing "partials/header.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
ERROR 2022/11/14 10:26:58 render of "page" failed: execute of template failed: template: partials/header.html:8:10: executing "partials/header.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
ERROR 2022/11/14 10:26:58 render of "page" failed: execute of template failed: template: partials/header.html:8:10: executing "partials/header.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
Error: Error building site: failed to render pages: render of "home" failed: "/Users/alexandram/test/themes/herring-cove/layouts/index.html:9:17": execute of template failed: template: index.html:9:17: executing "index.html" at <.RSSLink>: can't evaluate field RSSLink in type *hugolib.pageState
Built in 98 ms`

Is there another step that needs to be done regarding the templates when using the import command?

**Comment by bep** [comment]
The field in question was deprecated a long time ago and now removed.

* Use hugo.Generator 
* For RSSLink, see https://gohugo.io/templates/rss/#reference-your-rss-feed-in-head

For further questions/troubleshooting, see https://discourse.gohugo.io/
