### ISSUE TITLE
Add shortcode for render Mastodon toots

### ISSUE THREAD

**Issue by andriisoldatenko** [gohugoio/hugo#10434]
WDYAT?

**Comment by olikami** [comment]
Should be easy enough to implement for anyone, you just need server, user and tootID:

    <iframe src="https://<server>/@<user>/<tootID>/embed" class="mastodon-embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe>

**Comment by weddige** [comment]
https://github.com/gohugoio/hugo/pull/10920#issuecomment-1685302079
> The proposal (https://github.com/gohugoio/hugo/issues/10434) has not been accepted.

What can be done, to move this issue forward? As Hugo comes with shortcodes for Twitter, Instagram and various other social media platforms, it would be only appropriate to also have one for Mastodon.

I'll happily help implementing the feature. If this is not desired at the moment. Until there is a solution in Hugo I'll continue to use my implementation from #11370 and can push an updated version if necessary.

**Comment by jmooring** [comment]
Although it's not my decision to make, I am not in favor of adding any more shortcodes. Instead, I would prefer to deprecate most of the built-in shortcodes, and provide examples in documentation. 

With the introduction of Hugo Modules (implemented long after the built-in shortcodes), it is trivial to include shortcode libraries in a project.

**Comment by andriisoldatenko** [comment]
> Although it's not my decision to make, I am not in favor of adding any more shortcodes. Instead, I would prefer to deprecate most of the built-in shortcodes, and provide examples in documentation.
> 
> With the introduction of Hugo Modules (implemented long after the built-in shortcodes), it is trivial to include shortcode libraries in a project.

OH, it's a good idea, can you please point me to where in the docs should I add an example? and maybe some links for Hugo Modules?

**Comment by jmooring** [comment]
It it trivial for anyone to create their own shortcode based on Mastadon's embed code:

<details>
<summary>layouts/shortcodes/mastadon</summary>

```text
{{- with .Get 0 }}
  <iframe
    src="{{ . }}/embed"
    class="mastodon-embed" style="max-width: 100%; border: 0"
    width="400"
    allowfullscreen="allowfullscreen">
  </iframe>
  <script src="https://fosstodon.org/embed.js" async="async"></script>
{{- else }}
  {{- errorf "The %q shortcode requires a positional parameter: the url of the post. See %s" .Name .Position }}
{{- end }}
```
</details>
<br>

Then call it with:

```text
{{< mastadon "https://fosstodon.org/@gohugoio/112128108928766995" >}}
```

We don't need to add another internal shortcode.

**Comment by broughtupsy** [comment]
> We don't need to add another internal shortcode.

Perhaps document it? Or include a tips and tricks post in the forum.
