### ISSUE TITLE
Method to sort .Colors from dark to light

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10450]
Currently the `.Colors` method returns a slice sorted by dominance, which is great.

It would be convenient to get the darkest and lightest color. For example, use darkest for heading elements, lightest for background.

![image](https://user-images.githubusercontent.com/335669/202576674-0d932084-7d0d-4b17-b15b-aa1d02647cf7.png)

**Comment by andrewd72** [comment]
I had a go with making gradients from images so this is nice.
I might be misunderstanding but I think the sort above works on the whole hex values which will have RRBBGG and with therefore bias the Red?
I think this is related:
https://discourse.gohugo.io/t/convert-hex-to-rgb/29130
And there is some discussion here of perceived luminance that I found interesting:
https://stackoverflow.com/a/596243
Ideally you'd have conversions from hex to RGB and hex to HSL

**Comment by bep** [comment]
@andrewd72 I did some Google searches myself after this issue was raised, and there's lots of stuff to cover to make "everyone happy". I suspect it would be good to find one way of calculating luminance that is generally accepted that works OK for web.

**Comment by rodrigoalcarazdelaosa** [comment]
> @andrewd72 I did some Google searches myself after this issue was raised, and there's lots of stuff to cover to make "everyone happy". I suspect it would be good to find one way of calculating luminance that is generally accepted that works OK for web.

See [this](https://www.w3.org/TR/WCAG21/#dfn-relative-luminance).

**Comment by dogweather** [comment]
This is exactly where I'm going with the work I demo here: 

https://forkful.ai/en/blog/designing-with-dynamic-image-colors-in-hugo-site-gen/

<img width="805" alt="Screenshot 2024-04-13 at 21 12 52" src="https://github.com/gohugoio/hugo/assets/150670/f43a3793-4df8-420d-881e-5dd893c24f39">

---

I researched how to calculate luminance, read [this SO post](https://stackoverflow.com/questions/596216/formula-to-determine-perceived-brightness-of-rgb-color), which pointed to [this nice article showing the author's process](https://alienryderflex.com/hsp.html).

Here's my `Luminance` implementation from the above:

```javascript
{{/* 
	Input is expected to be a CSS-style hex color string (e.g. #RRGGBB).
	Output is the luminance from 0 to 1.

	Luminance = sqrt( 0.299*R^2 + 0.587*G^2 + 0.114*B^2 )

	See: https://alienryderflex.com/hsp.html
	     https://stackoverflow.com/questions/596216/formula-to-determine-perceived-brightness-of-rgb-color
		 https://gohugo.io/methods/resource/colors/
*/}}

{{ $r := (printf "0x%s" (substr . 1 2)) | int }}
{{ $g := (printf "0x%s" (substr . 3 2)) | int }}
{{ $b := (printf "0x%s" (substr . 5 2)) | int }}

{{ $r_norm := div $r 255.0 }}
{{ $g_norm := div $g 255.0 }}
{{ $b_norm := div $b 255.0 }}

{{ return (math.Sqrt (add (pow $r_norm 2 | mul 0.299) (pow $g_norm 2 | mul 0.587) (pow $b_norm 2 | mul 0.114)))}}
```

**Comment by bep** [comment]
@dogweather thanks for that input. I implemented "your" formula in https://github.com/gohugoio/hugo/pull/12374 -- and some quick tests shows that it seem to work well.

**Comment by jmooring** [comment]
@rodrigoalcarazdelaosa makes a good point. The formula he references is also used to calculate the official accessibility [contrast ratio](https://www.w3.org/TR/WCAG21/#dfn-contrast-ratio). So if I want to automatically use darkest/lightest for text/background, I should calculate the contrast ratio first.

Seems like we should stick with the WCAG standard.

**Comment by bep** [comment]
I have pushed an update to the PR that uses the WCAG formula -- the luminance values changes a little, but the relative ordering seem to be the same (at least in my simple test case).
