### ISSUE TITLE
Problem if the url parameter of a page contains a dot

### ISSUE THREAD

**Issue by Strubbl** [gohugoio/hugo#10468]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.107.0-DEV-85e2ac1a4424fdde673b663c37043ece61212f0c+extended linux/amd64 BuildDate=2022-11-21T08:42:40Z
</pre>

### Does this issue reproduce with the latest release?
yes

If i have a post, which has the parameter url set, and this url contains a ".", hugo does not generate the usual folder structure ($url instead of $url/index.html).

E.g.

```
$ grep url content/post/logseq-v0.8.9-and-namespaces.md 
url: logseq-v0.8.9-and-namespaces
```

generates the output file with no file ending and no folder/index.html:
```
$ ll testpublic/logseq-v0.8.9-and-namespaces 
-rw-r--r-- 1 strubbl strubbl 7.9K Nov 22 23:01 testpublic/logseq-v0.8.9-and-namespaces
```

Changing the post to have no dots in the url parameter:
```
$ grep url content/post/logseq-v0.8.9-and-namespaces.md 
url: logseq-v0-8-9-and-namespaces
```

generates the usual output:

```
$ ll testpublic/logseq-v0-8-9-and-namespaces
total 8.0K
-rw-r--r-- 1 strubbl strubbl 7.9K Nov 22 23:29 index.html
```

My expectation would be, that when using dots in the url, the output would be:
```
$ ll testpublic/logseq-v0.8.9-and-namespaces
total 8.0K
-rw-r--r-- 1 strubbl strubbl 7.9K Nov 22 23:29 index.html
```

**Comment by pamubay** [comment]
looks like Hugo will produce `url` path as-is when contains dot `.`. You can add `/` suffix to make Hugo generate clean URL structure.

```
url: logseq-v0.8.9-and-namespaces/
```

**Comment by redsnapper2006** [comment]
it is my first time to create a PR, please feel free to correct me.

**Comment by redsnapper2006** [comment]
@pamubay @bep can you take a little time to check on it? if something goes not well, please feel free to correct me

**Comment by Strubbl** [comment]
stale schmale

**Comment by jmooring** [comment]
The current behavior is correct.

If the front matter `url` field does not contain a dot, or if it ends with a slash  (`url = 'foo.bar.baz/'`), you are telling Hugo to generate a "pretty" url:

```text
public/
└── foo.bar.baz/
    └── index.html
```

If the front matter `url` field contains one or more dots (`url = 'foo.bar.baz'`), and does not end with a slash, the final segment is interpreted as a file extension, which tells Hugo to generate an "ugly" URL:

```text
public/
└── foo.bar.baz
```

We cannot assume that `.baz` is somehow invalid; we do not know the author's intent.
