### ISSUE TITLE
Tags ending in a period are not listed in .Site.Taxonomies.tags

### ISSUE THREAD

**Issue by JPinSPACE** [gohugoio/hugo#10475]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.105.0+extended darwin/arm64 BuildDate=unknown
</pre>

I encountered this issue and after debugging and searching for a solution I found an old post on the Hugo forum reporting the same issue so I'm making an issue here relaying the original poster's findings. Here's the original post: https://discourse.gohugo.io/t/taxonomy-terms-ending-in-periods-behave-inconsistently/36114

To reproduce, just create a tag ending in a period (e.g. "test.") and then view all tags in the rendered site. The test tag will not be in the tag list.

**Comment by romainx** [comment]
Hello,
On my side I've identified the regression between `0.105.0` (not affected by the issue) and `0.110.0` (affected by the issue).
Best.

**Comment by jmooring** [comment]
> I've identified the regression between 0.105.0 and 0.106.0

This is incorrect. Taxonomy terms ending with a period worked in v0.64.1 but not v0.65.0 or later (including v0.111.3).

**Comment by jmooring** [comment]
This is fixed in v0.123.0.
