### ISSUE TITLE
Add hasSuffix alias

### ISSUE THREAD

**Issue by tyytytytyiigo** [gohugoio/hugo#10474]
`strings.HasPrefix` already has an alias of `hasPrefix` but `strings.HasSuffix` has no such alias. This is a request to add `hasSuffix` as an alias of the latter. (A project I am porting over to Hugo requires me to use lots of this string and the non-aliased one is a mouthful).

**Comment by bapps2** [comment]
I support.

**Comment by bep** [comment]
OK, this makes sense to get the symmetry in place.

**Comment by jfish2** [comment]
Hi! I'm new to open source, but I'm a huge fan of Hugo and would love to tackle this issue. If this hasn't yet been worked on, I'll make sure to follow the contribution guide and try to get a PR in as soon as I'm able to.

**Comment by bep** [comment]
@jfish2 You can see the pattern for how we alias these functions here: https://github.com/gohugoio/hugo/blob/master/tpl/strings/init.go#L98

**Comment by jmooring** [comment]
Addressed with https://github.com/gohugoio/hugo/pull/10773
