### ISSUE TITLE
Space in i18n variable causing errors

### ISSUE THREAD

**Issue by jafaican** [gohugoio/hugo#10483]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.107.0-
</pre>

### Does this issue reproduce with the latest release?
Yes. When there is a space between the opening `"` and the i18n key, if the key is a URL, the link fails. For example, assuming the i18n key is 
```
[search]
other = "/search/"
```
Then `{{ i18n " search" }}` breaks the link unless the space is removed.

**Comment by jmooring** [comment]
It is behaving exactly as it should. If you want this to work:

```
{{ i18n " search" }}
```

Then you need this in your i18n file:

```
[" search"]
other = "/search/"

```

**Comment by jafaican** [comment]
I just diagnosed and figured out it is VS code indenting that is adding those spaces. A simple search and replace fixed the issue.
