### ISSUE TITLE
Regression of relURL since 0.101.0

### ISSUE THREAD

**Issue by multun** [gohugoio/hugo#10497]
### What version of Hugo are you using (`hugo version`)?

All versions since 0.101.0 are affected. 0.100.2 is the last known working version.
This breakage was introduced by https://github.com/gohugoio/hugo/pull/10002

### Does this issue reproduce with the latest release?

Yes

### Description

When a baseURL has a path (like so `http://website.com/path/`), relURL fails to take the path into account.
This leads to broken links and javascript failing to load with docsy.

### Reproducer

```sh
# get the site source
git clone --recurse-submodules git@github.com:DGEXSolutions/osrd-website.git
cd osrd-website
# npm install dependencies
docker run --rm -it -v $(pwd):/src -w /src/themes/docsy --entrypoint npm klakegg/hugo:ext-alpine install
# build the website with a working revision
docker run --rm -it -v $(pwd):/src -p 1313:1313 klakegg/hugo:0.100.2-ext-alpine build
grep /js/tabpane-persist.js public/fr/docs/index.html
# build the website with a failing revision
docker run --rm -it -v $(pwd):/src -p 1313:1313 klakegg/hugo:0.101.0-ext-alpine build
grep /js/tabpane-persist.js public/fr/docs/index.html
```

This reproducers observes the result of `<script src='{{ "js/tabpane-persist.js" | relURL }}'></script>` with `baseURL = "https://dgexsolutions.github.io/osrd-website/"`

With the failing revision:
```
<script src='/js/tabpane-persist.js'></script>
```

With the working revision:
```
<script src='/osrd-website/js/tabpane-persist.js'></script>
```

**Comment by jmooring** [comment]
See <https://github.com/gohugoio/hugo/issues/10049#issuecomment-1165948452>

The documentation is correct:
<https://gohugo.io/functions/relurl/>

**Comment by bep** [comment]
This was a bug fix, not a regression.

**Comment by multun** [comment]
@bep The linked issue is indeed a bugfix, but I believe it mistakenly introduced a regression

@jmooring there must be a misunderstanding, the linked comment and case mentioned applies when an url start with a slash, whereas mine does not: according to [documentation](https://gohugo.io/functions/relurl/#input-does-not-begin-with-a-slash), `{{ "js/tabpane-persist.js" | relURL }}` with `baseURL = "https://whatever.com/osrd-website/"` should result in `/osrd-website/js/tabpane-persist.js`

It's also not an issue in my code: out of the box, docsy now has broken links

**Comment by jmooring** [comment]
@multun Let's take further discussion of this to the forum (https://discourse.gohugo.io).
