### ISSUE TITLE
Add IsBlock to the image render hook context

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#10494]
While working on #10493 I see that the template somehow needs to know if we're inline or not.

In HTML

* `img` is an inline element.
* `figure` is a block element.

Mot images in Markdown files is put in their own paragraphs and can be wrapped with a `figure`. But it's not possible to make that into a general rule.

Not sure how easy this is, however.

**Comment by pamubay** [comment]
This is nice, can we also do it for render link? My usage is i want paragraph that contains only a link to render block element.

```md
Hello world

[Hugo Video](https://youtu.be/0RKpf3rK57I)

Hello World

```

The link will render youtube embedded iframe.
