### ISSUE TITLE
[Feature Request] Ordinal for Templates

### ISSUE THREAD

**Issue by jafaican** [gohugoio/hugo#10524]
Can the `.Ordinal` feature be extended to templates? I would like to use it with several images in partials.

**Comment by jmooring** [comment]
An `.Ordinal` is the position of a particular _thing_ within `.Content`. To date, there are only five _things_ that can inject stuff into `.Content`:

1. Codeblock render hooks
2. Heading render hooks
3. Image render hooks
4. Link render hooks
5. Shortcodes

Items 1, 3, and 5 expose the `.Ordinal` method.

**Comment by jafaican** [comment]
I just found the use case I needed can be solved by `{{ range $k, $v := .Value }}` then doing `{{ if $k }}<!-- insert here -->>{{ end }}`. I will close this.
