### ISSUE TITLE
Add support for start offset to the internal youtube shortcode

### ISSUE THREAD

**Issue by sgharms** [gohugoio/hugo#10520]
Sometimes  it's useful to scrub ahead in an embedded video from YouTube. The URLs support a `start=` parameter. Expose that interface? I have a local version of the shortcode that works for me, but this might be useful for others?

**Comment by SandaruKasa** [comment]
Bump

**Comment by SandaruKasa** [comment]
> If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

The pull requests are ready #10575 & #10576 (and have been for over a year), so there is not much work left to be done.

I, personally, am still interested in seeing this merged, even despite [the insistently silent treatment](https://github.com/gohugoio/hugo/pull/11559#issuecomment-1810185406) I have received from the maintainer so far.
