### ISSUE TITLE
[pagination] Support front page being different than page 1

### ISSUE THREAD

**Issue by mildred** [gohugoio/hugo#10533]
Hugo pagination works by generating multiple pages for items, and having the list front page show the items of page 1, such that page 1 and the front page are identical (and page 1 becomes just a redirect to the front page).

It would be great to have the template being able to customize the posts available on the front page and have a page 1 that is different (and no longer a redirect). The template will need to run for page 1 and the front page twice and there should be a way to tell the template author it it is displaying the front page or page 1.

Use case : sort items in ascending order, keeping the oldest item on page 1 and the newest on last page, and the front page would show the latest items. This would ensure that if an item is found on page 1, it will never be shifted to page 2 as new items are created.

**Comment by mildred** [comment]
Thanks, that would do the trick, I believe but I would have preferred to have the archive of all items start at page 1 and not page 2 or mixed on page 1 with the pinned/latest items.

- front page would show: 1 2 3 4 **latest**
  it would contain a configurable selection of the items (last items for example, ordered by latest first)
- page 1 would show: **1** 2 3 4 latest
  it would show the first batch of items sorted by oldest first
- page 2 would show: 1 **2** 3 4 latest
  it would show the next batch of items sorted by oldest first
- ...
- page 4 would show: 1 2 3 **4** latest
  it would show the last (possibly incomplete) batch of items sorted by oldest first

With your trick, I cannot have a page 1 and I must start at 2. Which is really nice, I hadn't thought of something like that.

**Comment by jmooring** [comment]
Let's take further discussion of this to the fourm (https://discourse.gohugo.io). Thanks.
