### ISSUE TITLE
Adding resource transformer for arbitrary exec calls.

### ISSUE THREAD

**Issue by naturedamends** [gohugoio/hugo#10540]
I want the ability to transform plant uml diagrams into ascii which can be passed into goat. 

I'll write the transformer.

Or transform .plantuml into .png etc.

**Comment by jmooring** [comment]
> arbitrary exec calls

Pretty sure that's not going happen.

Take this for a spin instead:

```bash
git clone --single-branch -b hugo-forum-topic-36924 https://github.com/jmooring/hugo-testing hugo-forum-topic-36924
cd hugo-forum-topic-36924
hugo server
```

**Comment by naturedamends** [comment]
{{- with resources.GetRemote $url $opts -}}

+ plant uml server

**Comment by naturedamends** [comment]
@jmooring why not?

**Comment by bep** [comment]
>@jmooring why not? Whats the qualification needed to add a loader to the extended version. 

Because we care about security. There are plenty of discussions in here about this issue, and something "like this" will happen in one form or the other, but we're certainly not adding a carte blanche `os.Exec <site.Params.my_command>`. I'm closing this as duplicate.

**Comment by naturedamends** [comment]
@bep 
> Because we care about security _and_ performance

Whats the issue, if some code, is compromised, it already has readFile and get request, to it can read anything that your user has. ~/.ssh/* etc, and send it to remote server
