### ISSUE TITLE
.TableOfContents should be an empty string for no headers

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugo#10543]
Currently, it produces `<nav id="TableOfContents"></nav>`, so there's no way to test in a template whether there is a TOC to show at all:

```html
{{ if .Params.toc }}
{{ with .TableOfContents }} // always true
<section class="border pe-3 ps-3 pt-3">...{{ . }}...</section> // always shown and visible
{{ end }}
{{ end }}
```

Also, it shouldn't have an ID. If I want it to have an ID, I can wrap it in a div myself:

```html
<div id="TableOfContents">{{ .TableOfContents }}</div>
```

**Comment by razonyang** [comment]
+1, I do that for now:

```go
{{- if and (ne .TableOfContents "") (ne .TableOfContents `<nav id="TableOfContents"></nav>`) }}
{{- end }}
```

**Comment by willfaught** [comment]
Yep, there's a workaround, but I think the default behavior should be changed.

**Comment by arifke254** [comment]
> Also, it shouldn't have an ID. If I want it to have an ID, I can wrap it in a div myself

The ID should remain there for design purposes as it is unique.

**Comment by willfaught** [comment]
> The ID should remain there for design purposes as it is unique.

Unique IDs can be assigned by wrapping with your own div, as I showed. Hugo putting that ID on that div wrapping the list prevents us from putting that exact ID on an outer tag.

**Comment by bapps2** [comment]
I see. `div.whateverclass ul` vs `#TableOfContents`...makes sense.

**Comment by razonyang** [comment]
I'm wondering if it would be better if Hugo could provide a structure variable instead of rendered HTML.

Let's call it `Headings` which has some members as following

| Name | Description
|---|---
| `Title` | The heading title
| `Anchor` | The anchor
| `Children` | Sub headings.

And then we can render the TOC by recursion.

```go
<div class="custom-toc-wrapper">
  {{ template "walk-toc" .Headings }}
</div>

{{ template "walk-toc" }}
  <ul>
    <li><a href="{{ .Anchor }}">{{ .Title }}</a></li>
    {{ with  .Children }}
      {{ template "walk-toc" . }}
    {{ end }}
  </ul>
{{ end }}
```

> Just a thought.
