### ISSUE TITLE
Alias for $.Page.RenderString

### ISSUE THREAD

**Issue by bapps2** [gohugoio/hugo#10546]
Is it possible to get an alias for `$.Page.RenderString`? Perhaps `markdownify` as someone in the forum had proposed?

**Comment by bep** [comment]
>Perhaps markdownify as someone in the forum had proposed?

`markdownify` is the same as `site.Home.RenderString`. We cannot make a `function` alias for a Page `method`. There is, however another issue about making a global `page`, so at some point you will be able to do `page.RenderString`, but we cannot make it any shorter than that.
