### ISSUE TITLE
Add imports option in tocss

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#10555]
I suggest we add a new option to `toscss`, maybe named `imports`.

This would allow to override certain imports and return either a string or a `Resource`, e.g.:

```handlebars
{{ $imports := dict 
   "@myvars" `$color: blue;`
}}
{{ $opts := dict "imports" $imports }}
```

And in the SCSS file you would either use/import the above:

```scss
@use "@myvars";
```

Note the at sign in the above is just a naming convention I used here, it can be anything.

As an added bonus, it would be nice if

* The `imports` value could also be a dict (with variable key/values I assume), so one could do `{{ $opts := dict "imports" (dict "@myvars" site.Params.my_scss_vars) }}`

This is related to another issue where people seem to assume that resources created via `resources.FromString` and similar would be visible to the SCSS importer etc., which I guess could be expected -- but that is harder to fix than the above.

/cc @jmooring

**Comment by jmooring** [comment]
I think you nailed it with your "added bonus" example. Naming the map "imports" _might_ lead people to believe they can somehow import a file, so perhaps name it "varImports" instead. I'm fine either way.


I took it for a theoretical spin:

layouts/partials/func/get-scss-vars.html

```
{{ $heroImageUrl := "" }}
{{ with resources.Get "images/hero.jpg" }}
  {{ with .Fill "1920x1280 webp" }}
    {{ $heroImageUrl = .RelPermalink }}
  {{ end }}
{{ end }}

{{ $textColor := or (site.Params.style.textColor) "#222" }}
{{ $baseFontSize := or (site.Params.style.baseFontSize) "18px" }}

{{ $varImports := dict "@myvars" (dict
    "$hero-image-url" $heroImageUrl
    "$text-color" (or (site.Params.style.textColor) "#222")
    "$base-font-size" (or (site.Params.style.baseFontSize) "18px")
  )
}}

{{ return $varImports }}
```

layouts/_default/baseof.html

```text
{{ $opts := dict
  "targetPath" "css/style.css"
  "transpiler" "dartsass"
  "varImports" (partialCached "func/get-scss-vars.html" .)
}}

{{ with resources.Get "scss/main.scss" }}
  {{ with . | toCSS $opts }}
    <link rel="stylesheet" href="{{ .RelPermalink }}">
  {{ end }}
{{ end }}
```

This would be so much cleaner than having to define the vars in the root Sass import with `.ExecuteAsTemplate`.

**Comment by bep** [comment]
>Naming the map "imports" might lead people to believe they can somehow import a file, so perhaps name it "varImports" instead. I'm fine either way.

Technically it's a way of resolving an import to something that's not mounted inside `assets`. The most common use case would be variable definitions, but I'm not sure we'd want to make that a restriction. People are going to mistake any property name, I suspect, but we still need to call a spade for a spade. But I'm open to better suggestions.

> "varImports" (partialCached "func/get-scss-vars.html" .)

Note that in my suggested set up, you need to 1) Give the import a name and 2) Actually import it in the file you want.

I did think about a slightly more limited/restricted feature that would maybe be easier to understand:

```
{{ $opts := dict
  "targetPath" "css/style.css"
  "transpiler" "dartsass"
  "vars" (dict "$color" "blue")
}}
```

Where we (Hugo) just injects the import at the top of the entry file. 

Thinking about he explanation/documentation work needed for this, I think I like the last one better ...

**Comment by jmooring** [comment]
> I'm not sure we'd want to make that a restriction

Then "imports" is fine.

> I think I like the last one better

If it is possible, great! But if not, what you've outlined is really convenient, despite the nested map. 

:+1: :+1: :+1:
