### ISSUE TITLE
Page.Author and .Authors and Site.Authors do nothing

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugo#10551]
I can't seem to be able to set Page.Author or .Authors. If I set `author:` and `authors:` in frontmatter, they appear in .Params, not .Author or .Authors.

Weirdly, if I set Page.Authors to a string or map instead of a string slice, then Hugo fails with an error:

```
execute of template failed at <.Authors>: error calling Authors: interface conversion: interface {} is maps.Params, not []string
```

Site.Authors seems to do nothing too.

With this site config:

```yaml
author:
  email: example@example.com
  name: Michael Bluth
authors:
  will:
    givenname: will
  nick:
    given_name: nick
```

and with this page frontmatter:

```yaml
author: Hugo Authors
authors: ["will", "nick"]
```

and this page template:

```
1 {{ printf "%#v" .Authors }}
2 {{ printf "%#v" .Author }}
3 {{ printf "%#v" .Params.author }}
4 {{ printf "%#v" .Params.authors }}
5 {{ printf "%#v" .Site.Author }}
6 {{ printf "%#v" .Site.Authors }}
```

This is printed:

```
1 page.AuthorList{}
2 page.Author{GivenName:"", FamilyName:"", DisplayName:"", Thumbnail:"", Image:"", ShortBio:"", LongBio:"", Email:"", Social:page.AuthorSocial(nil)}
3 "Hugo Authors"
4 []string{"will", "nick"}
5 map[string]interface {}{"email":"example@example.com", "name":"Michael Bluth"}
6 page.AuthorList(nil)
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.108.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
@willfaught 

Is there some documentation that lead you down this path? If so, it should be removed. See;
<https://discourse.gohugo.io/t/site-author-usage/31459/8>

**Comment by willfaught** [comment]
https://gohugo.io/variables/site/:

```
.Site.Author
```

https://gohugo.io/variables/page/#access-nested-fields-in-front-matter:

```
---
author:
  given_name: John
  family_name: Feminella
  display_name: John Feminella
---
```

https://pkg.go.dev/github.com/gohugoio/hugo/hugolib#SiteInfo:

```go
type SiteInfo struct {
	Authors page.AuthorList
```

https://pkg.go.dev/github.com/gohugoio/hugo@v0.108.0/resources/page#PageWithoutContent:

```go
type PageWithoutContent interface {
...
	// TODO(bep)
	AuthorProvider
```

**Comment by willfaught** [comment]
Also note that in https://discourse.gohugo.io/t/site-author-usage/31459/8, you suggest using Page.Params.author, not Page.Author:

```
{{ index .Site.Author .Params.author "name" }}
```

**Comment by jmooring** [comment]
`.Page.Author` has been deprecated:

<https://github.com/gohugoio/hugo/blob/master/hugolib/page__meta.go#L132>

`.Page.Authors` has been deprecated:

https://github.com/gohugoio/hugo/blob/master/hugolib/page__meta.go#L142

See also:
<https://github.com/gohugoio/hugo/blob/master/resources/page/page.go#L54-L60>

`.Site.Author` is available per:
<https://discourse.gohugo.io/t/site-author-usage/31459/8>

`.Site.Authors` isn't a thing.

**Comment by willfaught** [comment]
Sure, but deprecated doesn't mean broken or discontinued. Did they never work? That would be different.

**Comment by jmooring** [comment]
To the best of my knowledge they were never implemented, but that's ancient history.

The documentation (https://gohugo.io/documentation/) should reference nothing but `.Site.Author`. If that is not the case, please create an issue in the [docs repository](https://github.com/gohugoio/hugoDocs).

**Comment by jmooring** [comment]
Correction. See <https://github.com/gohugoio/hugoDocs/commit/2c0125b5290494d49334606c451446ebd9df3c21>. 

`.Site.Author` is no longer documented, and will be deprecated at some point.

**Comment by kilasuit** [comment]
@willfaught  They did work as I had this working on a local build on a machine that died on me back in May & I am so annoyed that I hadn't managed to back up my working on the theme that I used it in

**Comment by kilasuit** [comment]
@jmooring is there a blog post explaining why these are being deprecated as right now this to me makes no sense without a better understanding of the though of the future direction of travel

**Comment by kilasuit** [comment]
@jmooring sorry but if people are reliant on prior versions of software that had features that they are using that are then being deprecated it is totally immoral for one to delete that documentation. mark it as not current/archived/not maintained by the project for sure, but don't be so damn cheap as to delete it entirely.

**Comment by willfaught** [comment]
@kilasuit I can't speak for the project maintainers, but I think they're encouraging a new way going forward, where authors are represented as a taxonomy. You can see my first attempt at doing that [here](https://github.com/willfaught/paige/blob/c057d98eb3cce5e9165295989b1d8ebcdad56ee2/layouts/partials/paige-func-authors.html#L3-L7).

**Comment by kilasuit** [comment]
sure encourage but don't belittle those that aren't able to keep up with the pace of change and are set at a specific version for what ever reason that may be, mostly likely wanting stability and not instability

**Comment by willfaught** [comment]
Perhaps you're unfamiliar with Go module versioning, which uses semver. Minor version 0 allows for breaking changes between minor versions. We shouldn't expect API stability until v1.0.0 is released. I would guess they try to minimize breaks, regardless.

**Comment by kilasuit** [comment]
nah i'm well versed with it, I just don't agree at deleting documentation ever when it should be pointed that this is out of date and not being maintained, which is the morally right thing to do and even if it is not the cheap thing to do
