### ISSUE TITLE
Can't index .Site.Author with Page.Params.author

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugo#10559]
Doing `{{ index .Site.Author .Params.author }}` causes an error:

```
execute of template failed at <index site.Author .Params.author>: error calling index: value is nil; should be of type string 
```

I checked, and no value is nil. See below. Indexing with an identical string literal does work.

config.yaml:

```
author:
  george_bluth:
    display_name: George Bluth
  michael_bluth:
    display_name: Michael Bluth
```

Front matter:

```
+++
author = "michael_bluth"
foo = "michael_bluth"
```

Template:

```
<p>.Site.Author: {{ .Site.Author }}</p>
<p>printf "%T" .Site.Author: {{ printf "%T" .Site.Author }}</p>
<p>.Params.author: {{ .Params.author }}</p>
<p>printf "%T" .Params.author: {{ printf "%T" .Params.author }}</p>
<p>eq .Params.author "michael_bluth": {{ eq .Params.author "michael_bluth" }}</p>
<p>index .Site.Author "michael_bluth": {{ index .Site.Author "michael_bluth" }}</p>
```

Output:

```
.Site.Author: map[george_bluth:map[display_name:George Bluth] michael_bluth:map[display_name:Michael Bluth]]

printf "%T" .Site.Author: map[string]interface {}

.Params.author: michael_bluth

printf "%T" .Params.author: string

eq .Params.author "michael_bluth": true

index .Site.Author "michael_bluth": map[display_name:Michael Bluth]
```

Note that `{{ index .Site.Author .Params.foo }}` also results in the same error.

Sorry in advance if I'm missing something obvious, but after many minutes of debugging, I just can't see it.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.108.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
@willfaught Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
