### ISSUE TITLE
Make the module.workspace=off as default

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#10553]
See https://github.com/golang/go/issues/51967

I suspect not many Hugo users use this feature, but if they do, I think the default behaviour is confusing. Having a `go.work` file in the project used for development purposes and add that to your `.gitignore` file would make for a great dev setup, but it would be a pain to have to remember turning it off.

Setting `module.workspace=off` would enable the best of both worlds:

* Default would work great for development.
* Any other use cases could be configured.

**Comment by UtkarshVerma** [comment]
This would be a considerable improvement upon current state where `module.workspace` only accepts the absolute path.

Maybe having the following logic for the config would make sense?
1. `off` by default
2. `on` would tell Hugo to look for `go.work` in the project
3. `<absolute or relative path>` would tell Hugo to use the workspace file at that path.

I can't think of any use case for the third case right now, so it could probably be dropped.
