### ISSUE TITLE
Allow "fast render mode" even if --disableLiveReload is set

### ISSUE THREAD

**Issue by meyerhp** [gohugoio/hugo#10561]
### What version of Hugo are you using (`hugo version`)?
v0.108.0+extended darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### Issue
If you set the `--disableLiveReload` flag when running `hugo serve`, the fast render is also disabled and you can't turn it back on.

This line seems to be the issue:https://github.com/gohugoio/hugo/blob/9a215d6950e6705f9109497e9f38cc3844172612/commands/commandeer.go#L386

My main requirement is I need to run `hugo serve` without injecting the liveReload script but it should still use fastRender.

**Comment by bep** [comment]
I guess I added that conditional assuming that `fastRenderMode` would make no sense without the live reload enabled, but I guess we can adjust that.
