### ISSUE TITLE
figure shortcode puts title inside h4 tag

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugo#10574]
It looks like this:

```html
<figure>
  <img src="https://imgs.xkcd.com/comics/sandwich.png" alt="alt">
  <figcaption>
    <h4>title</h4>
  </figcaption>
</figure>
```

In my opinion, it looks bad. H4 is much too large for caption text.

Also, there isn't a corresponding h3 tag that it's nested under. The number is arbitrary.

It should put the title inside the figcaption tag directly, so we can style figcaption however we want to:

```html
<figure>
  <img src="https://imgs.xkcd.com/comics/sandwich.png" alt="alt">
  <figcaption>title</figcaption>
</figure>
```

Also, I think it's more intuitive to name the parameter "caption" instead of "title."

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.108.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by willfaught** [comment]
Also note that [it conflicts with Bootstrap](https://getbootstrap.com/docs/5.2/content/figures/):

>Anytime you need to display a piece of content—like an image with an optional caption, consider using a &lt;figure&gt;.
>
>Use the included .figure, .figure-img and .figure-caption classes to provide some baseline styles for the HTML5 &lt;figure&gt; and &lt;figcaption&gt; elements. Images in figures have no explicit size, so be sure to add the .img-fluid class to your &lt;img&gt; to make it responsive.
>
>&lt;figure class="figure"&gt;
>&nbsp;&nbsp;&lt;img src="..." class="figure-img img-fluid rounded" alt="..."&gt;
>&nbsp;&nbsp;&lt;figcaption class="figure-caption"&gt;A caption for the above image.&lt;/figcaption&gt;
>&lt;/figure&gt;

**Comment by jmooring** [comment]
First, `caption` and `title` are two different things.
<https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/figure.html>

Second, Hugo's built-in templates are functional examples that you should modify as needed or desired. Simply copy the code above to `layouts/shortcodes/figure.html` to override the built-in template.

Third, by their very nature, the built-in templates are opinionated. I would prefer to remove most of the built-in templates, but I think that ship sailed a long time ago.

In the future, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by jmooring** [comment]
We can't change this without breaking existing sites... it's in the wild.

**Comment by willfaught** [comment]
Is there a plan for a v1 or v2? The change could be made then.
