### ISSUE TITLE
Create built-in templates for link and image render hooks

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10585]
I've been thinking about this for a long time, and [this recent forum topic](https://discourse.gohugo.io/t/how-can-i-convert-markdown-files-contains-relative-link-with-end-with-md-to-hugo-links/42087) prompted me to create this proposal.

In my view, link and image render hooks are essential for:

1. Supporting portable links
2. Determining the URL of a page or resource when:

   - The site is served from a subdirectory (e.g., `https:/example.org/foo/`)
   - Rendering `.Content` instead of `.Summary` on a list page, or within another page
   - Front matter contains `slug` or `url` (or cascaded by ancestor or site configuration)
   - Site configuration contains `permalinks` key
   - Site configuration enables `uglyURLs`
   - Adding content to a multilingual site
   - And maybe some other things that I'm forgetting

Resolution of markdown links is one of the more frequent issues raised on the forum by new users. Without analyzing the data, I'd guess that it is in the top 10, or maybe the top 20.

With built-in templates, it will just... work.

I recognize that built-in templates are, by their very nature, opinionated&#8212;so we'll use mine. The problem with opinions is that everybody has one, as demonstrated by the number of issues and PR's against the existing built-in templates and shortcodes. 

And that makes me somewhat hesitant to do this. But the net improvement in user experience may be worth it.

If we do this, there must be a configuration setting to enable the use of these internal templates, and it must default to `false` to avoid breaking existing sites. And, in my opinion, this is important enough that we might want to include it in the default configuration file generated by `hugo new site foo`. If I were creating a new site, it would be the first change I would make to the site configuration.

**Comment by jmooring** [comment]
To clarify... this proposal is about URL resolution, and nothing else.
- The link render hook **will not** add anchor tags, open external links in a new tab, etc.
- The image render hook **will not** perform any image processing, add a lazy loading attribute, handle markdown attributes when `.IsBlock` is `true`, etc.

Site authors must override the internal templates to add these and other features.

**Comment by bep** [comment]
>If we do this, there must be a configuration setting to enable the use of these internal templates, and it must default to false to avoid breaking existing sites.

So, to get the most out of this proposal (as in: the least amount of questions from new sites/users), what if we defaulted to having these enabled?

**Comment by jmooring** [comment]
> what if we defaulted to having these enabled

structure

```
content/posts/
├── post-1.md
└── post-2.md
```

site config

```
[permalinks]
posts = '/articles/:slug'
```

existing markdown

```
[Post 2](/articles/post-2)
```

If the link render hook does error checking, (e.g., `errorf "Unable to resolve x to a page or resource`), which I think is valuable, we would break their existing links.

If we don't do error checking, we could fall back to the original destination, then we wouldn't break existing sites. Maybe that's the right thing to do to provide the most benefit in the least intrusive way.

**Comment by jmooring** [comment]
We could also do something in between...

```
erroridf "Unable to resolve x to a page or resource
```

**Comment by regisphilibert** [comment]
If we enable this by default I'm afraid this could bring a lot of noise in the discourse. I'm mostly worried about relative URLs which could coincidently be a match to a content filepath. Also for very big sites, Hugo will now try a "GetPage" on every single markdown relative links it finds resulting in a potential increase in build time.

That could be a good use case for the first official Hugo Module (as in "maintained by the Hugo maintainers") or indeed a built-in internal template people can **voluntarily** opt-in.

**Comment by jmooring** [comment]
For example:
- https://discourse.gohugo.io/t/summary-using-images-from-page-bundles/42187

**Comment by jmooring** [comment]
@regis I agree with your concerns about performance. I ran a 1000 page test with 100 images per page:
- With an image render hook: 1593ms (avg of 3 runs)
- Without an image render hook: 540ms (avg of 3 runs)

Yes, it depends on the hook, and the links.

Assuming the destination is not remote, the hook I used looks first for a page resource, falls back to a global resource, and throws an error it it can't resolve the destination. The example destinations were designed to resolve to a global resource, forcing two evaluations per link (worst case for this particular hook).

To reduce friction for new users, I think internal templates make the most sense. This should just work, without having to install Go or do another `git submodule add` and explain that the theme key in site configuration can be an array, and why the element order is important.

The naming needs some thought, but if `hugo new site xxx` produced something like this...

```
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[markup.goldmark.renderhooks]
enableDefaultLinkHook = false
enableDefaultImageHook = false
```

...then new users could flip a switch or two, and I would think this would be fairly easy to document with an admonition on the quick start page:

> We encourage new users to enable both of these options to insure resolution and portability of link and image URLs. See xxx for more information.

Or maybe we leave the default config file as is, and just include the bit to copy and paste in the admonition.

**Comment by regisphilibert** [comment]
I totally agree with the need to simplify src/href references in Markdown so that it just works as expected. It's hard for newcomers to accept/understand that markdown is disconnected from Hugo's own page and asset resolutions. But what if this issue was not about render hook but about link resolution in goldmark? Hugo could simply complement the renderer with a layer of logic on those link/image resolution. As if the user was to replace them with a safe `relref` shortcode.

The problem I have with built-in templates is the following:

What if I need my own render hook while still maintaining the link reference logic from the build-in render hook. I often use render-hook to include some HTML/classes semantics to my links and images. Now I need to
1. Find the internal code in GH (not always easy to find)
2. Identify what link resolution logic I need. (might not be straight forwards for newcomers)
3. Copy said logic in my own render-hook.

Beside by keeping it out of a built-in template, this can work can be coded in Go rather than Go Template.

And because newcomers and advanced users do not have the same expectation of markdown and link resolution, we should still make it a configurable feature.

```
[markup.goldmark.renderhooks]
enableLinkResolution = true
enableImageResolution = true
```

**Comment by jmooring** [comment]
> It's hard for newcomers

Yes. A new user [commented](https://discourse.gohugo.io/t/summary-using-images-from-page-bundles/42187/5?u=jmooring) this morning, "Sounds like it’s impossible to use markdown, with a standard markdown image ref, that works out of the box with Hugo."

> What if I need my own render hook while still maintaining

That's standard procedure for overriding _any_ template or shortcode, regardless of whether it is built-in or provided by a theme/module. 

Think about the built-in pagination template. If it didn't exist, pagination as a feature would be more difficult for new users to implement. As it is now, it just works. Most sites that I have seen do _not_ override the built-in template because the default behavior is sensible.

> Find the internal code in GH (not always easy to find)

That's a documentation issue.

> Identify what link resolution logic I need

I think that can be addressed with (a) documentation-in-code, and (b) well-formatted code. Many of the built-in templates were written before Go provided white space removal, so if/when/range blocks are inline, making them difficult to read.

> might not be straight forwards for newcomers

If we can provide a sensible default, like we have for the pagination template, new users shouldn't have to mess with this anyway.

> Hugo could simply complement the renderer with a layer of logic

Would site authors be able to override the hardcoded logic?

**Comment by regisphilibert** [comment]
> Would site authors be able to override the hardcoded logic?

I guess they would not... But if the logic is not sufficient  (and I'm sure it will be for 99% of the users, especially newcomers targeted here and who expects Markdown Ref + Hugo to just work) one could disable the logic from the config.

I think all your argument are all valid and would welcome the feature either as a built-in template. But I would feel safer (template or otherwise) if it was an opt-in rather than a default.

But then again. It's just about proper documentation.

**Comment by bep** [comment]
>I agree with your concerns about performance. I ran a 1000 page test with 100 images per page:

That doesn't sound very realistic ...

**Comment by jmooring** [comment]
> That doesn't sound very realistic

Yeah, I know. I was trying to get a sense of the difference. Perhaps 1000 pages with 10 images per page would be a better test.

**Comment by jmooring** [comment]
Test of 1000 pages, 10 images per page...

With an image render hook: 472ms (avg of 5 runs)
Without an image render hook: 366ms (avg of 5 runs)

> the hook I used looks first for a page resource, falls back to a global resource, and throws an error it it can't resolve the destination. The example destinations were designed to resolve to a global resource, forcing two evaluations per link (worst case for this particular hook).

**Comment by jmooring** [comment]
> If we don't do error checking, we could fall back to the original destination, then we wouldn't break existing sites. 

Another reason to ignore page/resource not found is the use of `ref` and `relref` shortcodes in existing sites, either built-in or custom. Example:

```
[Post 1]({{< relref "/posts/post-1" >}})
```

**Comment by jmooring** [comment]
Closing in favor of #11933.
