### ISSUE TITLE
Add a function like `findRE` that will return all sub/group matching.

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#10594]
Related topic: https://discourse.gohugo.io/t/regular-expressions-sub-matching-groups-not-supported/15368

I would like to create functions that parse and return some stuff of HTML like following.

```html
<ul>
  <li><a href="#foo">Foo</a></li>
  <li><a href="#bar">Bar</a></li>
</ul>
```

```go
pattern := `<a.*href="(.+)">(.+)</a>`
```

Result (something like this)

```json
[
  [
    "<a href=\"#foo\">Foo</a>",
    "#foo"
    "Foo"
  ],
  [
    "<a href=\"#bar\">Bar</a>",
    "#bar"
    "Bar"
  ]
]
```

**Comment by jmooring** [comment]
I believe that [FindAllStringSubmatch](https://pkg.go.dev/regexp#Regexp.FindAllStringSubmatch) provides the desired functionality, but I am concerned that site developers will have a difficult time wrapping their heads around this.

For your specific example, you can do this:

```
{{ $str := `
  <ul>
    <li><a href="#foo">Foo</a></li>
    <li><a href="#bar">Bar</a></li>
  </ul>
`}}


{{ $s := slice }}
{{ range $match := findRE `<a.+a>` $str }}
  {{ $s = $s | append (
    slice (
      slice
        $match
        (replaceRE `.+"(.+)".+` "$1" $match)
        (replaceRE `.*>(.+)<.+` "$1" $match)
      )
    )
  }}
{{ end }}
```

The resulting data structure (jsonified)...

```
[
  [
    "\u003ca href=\"#foo\"\u003eFoo\u003c/a\u003e",
    "#foo",
    "Foo"
  ],
  [
    "\u003ca href=\"#bar\"\u003eBar\u003c/a\u003e",
    "#bar",
    "Bar"
  ]
]
```

**Comment by razonyang** [comment]
@jmooring Thank you for the workaround, but I'm concerned about the performance between `FindAllStringSubmatch` and the `findRE` +  N x `replaceRE`. I think it is worthwhile if the former has obvious performance. But I don't know how to benchmark.

> but I am concerned that site developers will have a difficult time wrapping their heads around this.

I think it's related to the documentations.

**Comment by bep** [comment]
I don't think we need to benchmark to to show the value, and I have needed this myself in some cases.
