### ISSUE TITLE
Taxonomies not generating as expected

### ISSUE THREAD

**Issue by fissssssh** [gohugoio/hugo#10598]
### What version of Hugo are you using (`hugo version`)?

<pre>
v0.108.0
</pre>

### Does this issue reproduce with the latest release?

no

### Description

I have created 2 taxonomies with config.yaml
```yaml
taxonomies:
  category: categories
  tag: tags
```
and I wrote tag on my post like 

* a.md
   ```md
   ---
   title: "a"
   tags:
     - C#
   ---
   ```
* b.md
   ```md
   ---
   title: "b"
   tags:
     - C#
   ---
   ```
I open `{baseurl}/tags`, it's rendered tag named `C#`

![image](https://user-images.githubusercontent.com/29757779/210249627-0a4a9a10-7a66-4d77-922e-16a61d110c45.png)

 but it show 404 when I clicked, the url is `{baseurl}/tags/c/#/`

![image](https://user-images.githubusercontent.com/29757779/210249662-35bd5337-7468-4777-8c96-36aea9911d34.png)

then I tried add more tag contains special symbols, like `C%`

* a.md
   ```md
   ---
   title: "a"
   tags:
     - C#
     - C%
   ---
   ```
* b.md
   ```md
   ---
   title: "b"
   tags:
     - C#
     - C%
   ---
   ```

`{baseurl}/tags` rendered 2 tags, `C#` and `C%`

![image](https://user-images.githubusercontent.com/29757779/210249778-8d5bed36-8f5a-4161-b174-8058fab31f7b.png)

and I clicked `C%`, its took me to `{baseurl}/tags/c/`(not has %), and the posts are display correctly.

![image](https://user-images.githubusercontent.com/29757779/210249857-55f4eb2a-9e01-432d-bde5-3ffdfe413d80.png)

An interesting thing happened, when I click on the C# tag, the url is the same as before, but it is not 404, and the content display is the same as the result of clicking C%

![image](https://user-images.githubusercontent.com/29757779/210249978-b6ba62f5-f172-4456-b947-3ab22683d003.png)

 I tried add anthoer tag named `C@`, and regenerate site

* a.md
   ```md
   ---
   title: "a"
   tags:
     - C#
     - C%
     - C@
   ---
   ```
* b.md
   ```md
   ---
   title: "b"
   tags:
     - C#
     - C%
     - C@
   ---
   ```
unexpected things happened, `C%` disappeared, and only `C#` and `C@` were left

![image](https://user-images.githubusercontent.com/29757779/210250109-971daa70-b93c-4cba-97b7-871559c297b3.png)

the result of clicking `C@` is the same as the result of clicking `C%` before

![image](https://user-images.githubusercontent.com/29757779/210250177-00b985f4-2aea-4587-b4e4-61d3ee4c23d2.png)

and clicking `C#` will display the result of `C@`

![image](https://user-images.githubusercontent.com/29757779/210250224-1ca253bc-0ae9-4fdc-8b6e-b3d62ea307eb.png)

**Comment by jmooring** [comment]
The problem with the @ symbol [was addressed](https://github.com/gohugoio/hugo/commit/2d217cba5108d30835a5cf10869cfbd0a70d22f7) in v0.109.0.

Related issues:
- https://github.com/gohugoio/hugo/issues/10475
- https://github.com/gohugoio/hugo/issues/8232

@fissssssh In the future, perhaps fewer screen captures? Infinite scroll has its place, but not here. :slightly_smiling_face:
