### ISSUE TITLE
Cannot override rss template from theme that declares one

### ISSUE THREAD

**Issue by jbrodriguez** [gohugoio/hugo#10599]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.109.0+extended darwin/arm64 BuildDate=unknow
</pre>

### Does this issue reproduce with the latest release?
yes

i have a theme that has a posts/rss.xml

i also declare a top level layouts/posts/rss.xml, making some changes to the template

hugo build and server render the theme rss.xml, instead of my modified rss.xml

**Comment by jmooring** [comment]
I am unable to reproduce this with v0.109.0.

Theme directory structure:

```text
themes/foo/layouts/
├── _default/
│   └── rss.xml
└── posts/
    └── rss.xml 
```

Root directory structure:

```text
layouts/
├── _default/
│   └── rss.xml   <-- overrides themes/foo/layouts/_default/rss.xml
└── posts/
    └── rss.xml   <-- overrides themes/foo/layouts/posts/rss.xml
```

**Comment by bep** [comment]
This is pretty well tested, so I suggest you take further questions on https://discourse.gohugo.io/
