### ISSUE TITLE
Posts with more than 10 years are not shown

### ISSUE THREAD

**Issue by joaoheytor** [gohugoio/hugo#10609]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended linux/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

hey team,
not sure why, but posts with more than 10 years are not shown:

![Screenshot_01](https://user-images.githubusercontent.com/13548034/211385947-932bbae2-bfe3-4edc-99ff-8f37b4e51074.png)
![Screenshot_02](https://user-images.githubusercontent.com/13548034/211385952-07962028-e2b2-47be-b1b9-c8a2cbd054fd.png)

Tried to update the version to the latest one, but it seems this bug still exists... :|

**Comment by jmooring** [comment]
This is an issue with your theme, templates, or content&mdash;it is not a bug.

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
