### ISSUE TITLE
Unified enable `sourceMap` field name

### ISSUE THREAD

**Issue by septs** [gohugoio/hugo#10605]
https://github.com/gohugoio/hugo/blob/e402d91ee199afcace8ae75da6c3587bb8089ace/docs/content/en/hugo-pipes/scss-sass.md?plain=1#L38-L39

https://github.com/gohugoio/hugo/blob/e402d91ee199afcace8ae75da6c3587bb8089ace/docs/content/en/hugo-pipes/postcss.md?plain=1#L33-L34

https://github.com/gohugoio/hugo/blob/e402d91ee199afcace8ae75da6c3587bb8089ace/docs/content/en/hugo-pipes/js.md?plain=1#L92-L93

https://github.com/gohugoio/hugo/blob/e402d91ee199afcace8ae75da6c3587bb8089ace/docs/content/en/hugo-pipes/babel.md?plain=1#L61-L62

Unified `sourceMap` field name, i think can simplify expected

**Comment by septs** [comment]
current:

```
{{-
$jsOptions := dict
  "sourceMap" (cond hugo.IsProduction "" "inline")
  "minify" hugo.IsProduction
-}}
{{-
$cssOptions := dict
  "enableSourceMap" (not hugo.IsProduction)
  "outputStyle" (cond hugo.IsProduction "compressed" "")
-}}
{{- with resources.Get "main.ts" | js.Build $jsOptions | fingerprint }}
<script src="{{ .Permalink }}"></script>
{{- end }}
{{- with resources.Get "main.scss" | toCSS $cssOptions | fingerprint }}
<link rel="stylesheet" href="{{ .Permalink }}">
{{- end }}
```

expected:

```
{{-
$options := dict
  "sourceMap" (not hugo.IsProduction)
  "minify" hugo.IsProduction
-}}
{{- with resources.Get "main.ts" | js.Build $options | fingerprint }}
<script src="{{ .Permalink }}"></script>
{{- end }}
{{- with resources.Get "main.scss" | toCSS $options | fingerprint }}
<link rel="stylesheet" href="{{ .Permalink }}">
{{- end }}
```

**Comment by septs** [comment]
expect unified as

```
sourceMap: [
  "inline",
  "external",
  true (enable inline source map),
  false (disable source map)
]
```

**Comment by bep** [comment]
Yea, I agree, but we obviously need to respect the old prop key(s).
