### ISSUE TITLE
Adding option to make all markdown files draft by default.

### ISSUE THREAD

**Issue by memogarcia** [gohugoio/hugo#10607]
I have a lot of markdown files that I would like to publish as blog posts, however, a lot of them are not "ready" to be publish so instead of adding something like this to all my files:

```markdown
---
title: "Title"
date: date
draft: true
---
```

I would like to have an option that sets all my markdown files as draft by default unless I explicitly mark them as `draft: false`

Is there such a configuration I could use? or is this something that needs to be coded?

**Comment by jmooring** [comment]
> Is there such a configuration I could use?

Yes, there is.

<https://gohugo.io/content-management/front-matter/#front-matter-cascade>

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
