### ISSUE TITLE
resources.GetRemote HEAD method errors with unexpected EOF

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10604]
Reference: <https://discourse.gohugo.io/t/42272/3>

When I do this:
```
{{ $url := "https://gohugo.io/img/hugo.png" }}
{{ $opts := dict "method" "head" }}
{{ with resources.GetRemote $url $opts }}
  {{ with .Err }}
    {{ errorf "Unable to get remote resource: %s" . }}
  {{ else }}
    {{ .Content }}
  {{ end }}
{{ else }}
  {{ errorf "Unable to get remote resource: %s" $url }}
{{ end }}
```

I get:

> Unable to get remote resource: error calling resources.GetRemote: failed to read remote resource “https://gohugo.io/img/hugo.png”: unexpected EOF

But the response _is_ captured and cached in:
`/tmp/hugo_cache/my-project/filecache/getresource/6247740232174893946`

**Comment by vanbroup** [comment]
A quick code scan, we should check if the response body is `nil` bore reading it, as a HEAD response doesn't contain a body.

https://github.com/gohugoio/hugo/blob/master/resources/resource_factories/create/remote.go#L138

should check if `res.Body` is `nil`.

I can create a PR to fix and test this next week.

**Comment by bep** [comment]
>should check if res.Body is nil.

I'm checking this now and in @jmooring 's test case the body is not nil, `ContentLength` is reported as 18210, yet Go is throwing this unexpected EOF error. Will need to ... Google this.

**Comment by bep** [comment]
OK, the Mozilla docs are useful here:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

<img width="956" alt="image" src="https://user-images.githubusercontent.com/394382/212656407-08370c10-e2e5-43da-8815-71a94095e624.png">

So, the correct way to handle this is to just ignore the body when the method is HEAD. I will create a pull request.

**Comment by bep** [comment]
... but that said, I don't see the value of a `Resource` object from a HEAD request without the ContentLength etc. response info ... I'll see if I can add that to the mix. We have a `.Data` map that we could stuff this info in.

**Comment by oclero** [comment]
🥳
