### ISSUE TITLE
--cleanDestinationDir flag ignored if static directory is missing

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#10613]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.108.0-a0d64a46e36dd2f503bfd5ba1a5807b900df231d+extended darwin/amd64 BuildDate=2022-12-06T13:37:56Z VendorInfo=gohugoio

</pre>

### Does this issue reproduce with the latest release?
Yes

Currently the `--cleanDestinationDir` flag is ignored when the project is missing a `static` directory. It's been there for a while but I was not able to find an opened or closed issue about this.

**Comment by jmooring** [comment]
I think this is a duplicate of https://github.com/gohugoio/hugo/issues/8433.

**Comment by regisphilibert** [comment]
Ok sorry, I did not seem them related at first 👍
