### ISSUE TITLE
Assets for Windows 64 bit not showing up for any hugo release

### ISSUE THREAD

**Issue by rou-va** [gohugoio/hugo#10618]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version v0.109.0

</pre>

### Does this issue reproduce with the latest release?
I can 't seem to  find the assets for windows 64 bit in any of the releases. Most of the releases don't load any assets in the first  place and the latest release v0.109.0 only has assets for Linux.

**Comment by bapps2** [comment]
1. https://github.com/gohugoio/hugo/releases/download/v0.109.0/hugo_extended_0.109.0_windows-amd64.zip
2. https://github.com/gohugoio/hugo/archive/refs/tags/v0.109.0.tar.gz

**Comment by jmooring** [comment]
See screen capture below:

![image](https://user-images.githubusercontent.com/335669/212489692-ac23cae0-522c-4441-95f5-faadb2e2fd38.png)
