### ISSUE TITLE
Add a "cleanDestinationDir" configuration key

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#10619]
I don't think this is an unusual use case to often have to run the `--cleanDestinationDir` flag when debugging or working on a project's feature. (Esp. with output formats etc...). Also it could be argued that one would always want this when building locally.

We could have a new configuration key `cleanDestinationDir: true` (defaulting to `false` of course) which one could toggle off in production.

My first intention was to propose an abbreviation flag for the popular but lengthy `--cleanDestinationDir` but I don't think we could find a suitable lone letter for this, hence me proposing rather a new config key.

**Comment by jmooring** [comment]
This site configuration option works, it's just not documented... not sure why.

```
cleanDestinationDir = true
```

You can also export HUGO_CLEANDESTINATIONDIR=true/false to your environment.

This would be a little more useful if we addressed https://github.com/gohugoio/hugo/issues/8433.

**Comment by regisphilibert** [comment]
Oh great! Thanks a ton! I would create a ticket in the doc site to document this, but I think the configuration key doc is dynamically generated or is this just for the CLI flags?

**Comment by regisphilibert** [comment]
It's not I'll address this.
