### ISSUE TITLE
warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.

### ISSUE THREAD

**Issue by hiifong** [gohugoio/hugo#10629]
### install from Github source
when i run `CGO_ENABLED=1 go install --tags extended github.com/gohugoio/hugo@latest` command is warning.

OS: MacOS Ventura 13.1 (22C65)
Go:go1.19.5 darwin/amd64

### logs
```shell
# github.com/bep/golibsass/internal/libsass
In file included from json.cpp:2:
../../go/pkg/mod/github.com/bep/golibsass@v1.1.0/internal/libsass/../../libsass_src/src/json.cpp:1289:3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
```

**Comment by Yansre** [comment]
had the same problem,
Is there a temporary solution？

**Comment by bep** [comment]
I have Ventura 13.2 and this works fine for me. I have seen reports about this before, though, and I suspect this comes down to which version of the MacOS SDK you build with. 

>Is there a temporary solution？

We have release binaries.

**Comment by csellington** [comment]
I had this same issue; it was resolved for me by upgrading go to version 1.20.3 (I was using 1.20.1)

**Comment by bep** [comment]
I just hit the "update x code" on my main development Mac, which I guess means I will get this problem, which also means that I need to put a priority to fix it ...

**Comment by bep** [comment]
I upgreaded xcode and now get this **warning**, but note: it's just a warning. I have inspected the 1 usage of `sprintf` and it's not a security issue. So, for now I suggest you ignore this warning. I will see if I can somehow fix this upstream,

```
~/d/g/g/hugo ❯❯❯ go install -tags extended                                         ✘ 130 master ✭
# github.com/bep/golibsass/internal/libsass
In file included from json.cpp:2:
../../../gomod_cache/github.com/bep/golibsass@v1.1.0/internal/libsass/../../libsass_src/src/json.cpp:1289:3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
~/d/g/g/hugo ❯❯❯ echo $?
```

**Comment by hiifong** [comment]
> I upgreaded xcode and now get this **warning**, but note: it's just a warning. I have inspected the 1 usage of `sprintf` and it's not a security issue. So, for now I suggest you ignore this warning. I will see if I can somehow fix this upstream,
> 
> ```
> ~/d/g/g/hugo ❯❯❯ go install -tags extended                                         ✘ 130 master ✭
> # github.com/bep/golibsass/internal/libsass
> In file included from json.cpp:2:
> ../../../gomod_cache/github.com/bep/golibsass@v1.1.0/internal/libsass/../../libsass_src/src/json.cpp:1289:3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
> ~/d/g/g/hugo ❯❯❯ echo $?
> 0
> ```

Thank U
