### ISSUE TITLE
hugo --minify creates invalid HTML with empty tags

### ISSUE THREAD

**Issue by Juhannuspukki** [gohugoio/hugo#10637]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.110.0+extended darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### Bug description

Let us consider the following code:

```html
<div class="container">
  <div class="coloured-status-indicator"></div>
  <p class="status-message">Message</p>
</div>
```

One would expect the same code to appear on the generated website. However, when command hugo --minify is used to generate a website, the HTML output will be as follows:

```html
<div class="container"><div class="coloured-status-indicator"/><p class="status-message">Message</p></div>
```

The result of minification of the empty div is invalid. This results in an unmatched opening div tag in the code. As the W3 validator puts it: _Self-closing syntax (/>) used on a non-void HTML element. Ignoring the slash and treating as a start tag._

A web browser interprets the result to be (for example) something like this, which breaks the layout:

```html
<div class="container">
  <div class="coloured-status-indicator">
    <p class="status-message">Message</p>
  </div>
</div>
```

This issue only occurs when --minify is used. When hugo command is used without flags, output HTML is as expected.

**Comment by jmooring** [comment]
I am unable to reproduce this as described. With the [default minify configuration](https://gohugo.io/getting-started/configuration/#configure-minify), this:

```text
<div class="container">
  <div class="coloured-status-indicator"></div>
  <p class="status-message">Message</p>
</div>
```

become this:

```
<div class=container><div class=coloured-status-indicator></div><p class=status-message>Message</p></div>
```

**Comment by Juhannuspukki** [comment]
Right you are. Upon further research it seems that this issue only occurs if there is a  malformed SVG somewhere in the same partial.
