### ISSUE TITLE
Transpiled hex-string color from config file cannot be used as color in css functions such as `lighten()` and `darken()`

### ISSUE THREAD

**Issue by MJacred** [gohugoio/hugo#10632]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended
</pre>

### Does this issue reproduce with the latest release?

Yes

### Context

Followed documentation from [v0.109.0](https://github.com/gohugoio/hugo/releases/tag/v0.109.0) relase notes as well as https://discourse.gohugo.io/t/initialize-sass-variables-from-hugo-templates/42053/1 for LibSass transpiler

**Cannot use css functions such as `lighten()` and `darken()`, if the value comes transpiled from config file, because it's not a color**

Setup is as follows…

config.yaml
```yaml
params:
  style:
    color_palette_white: '#fff'
```

style.sass
```css
@import "bulma/bulma"
@import "mystyle/core"
```

mystyle/core.scss
```css
@import "hugo:vars";

@import 'partials/something';
// and many more .scss imports
```

mystyle/partials/_something.scss
```css
.something {
  border-bottom: 1px solid lighten($color-palette-white, 5%);
}
```

error log
```
Start building sites … 
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended
Error: Error building site: TOCSS: failed to transform "style.sass" (text/x-sass): "/path/themes/my-theme/assets/mystyle/partials/_something.scss:101:34": argument `$color` of `lighten($color, $amount)` must be a color
Built in 266 ms
```

**Comment by jmooring** [comment]
It looks like everything is injected as a string. I was unable to pass numbers (e.g., RGB values per channel, opacity, etc.), and there doesn't appear to be any _simple_ way to cast in Sass.

**Comment by bep** [comment]
I have labeled this a bug. Not sure what happens here, but we (I) surely need to look closer into how types/values are converted between Go and Dart.
