### ISSUE TITLE
Resource Hints Builder

### ISSUE THREAD

**Issue by septs** [gohugoio/hugo#10631]
I think can add a new api, simplify resource-hints complex, improve page render speed

on page variable (on render hooks and shortcodes using)

```
.ResourceHints.Prefetch <url> <as-type>
.ResourceHints.Prefetch "https://example.com" "document"
.ResourceHints.Preload <url>
.ResourceHints.Prerender <url>
.ResourceHints.Preconnect <url>
.ResourceHints.DNSPrefetch <url>
```

on base of (head partial)

```
{{- range .ResourceHints }}
<link rel="{{ .Rel }}" href="{{ .Href }}" {{- with .As }} as="{{ . }}"{{ end -}}>
{{- end }}
```

or (alternative using method)

```
{{ .ResourceHints }}
```

via [fmt.Stringer](https://pkg.go.dev/fmt#Stringer) use preset template to HTML format (like `.TableOfContents`)

I would like to implement this API if possible on Pull Request

----

References:

1. https://www.w3.org/TR/resource-hints/
1. https://www.smashingmagazine.com/2019/04/optimization-performance-resource-hints/
1. https://blog.cloudflare.com/early-hints/
1. https://developers.cloudflare.com/cache/about/early-hints/
1. https://nitropack.io/blog/post/early-hints

**Comment by evanescente-ondine** [comment]
> I would like to implement this API if possible on Pull Request

Has something been done by someone, that I could test ? I ask since I recently felt the need for a pretty heavy use of such feature, if it had been there...
Yours

**Comment by bep** [comment]
This doesn't make any sense.
