### ISSUE TITLE
[FEATURE] Any possibility of hugo to generate a mind map from a markdown

### ISSUE THREAD

**Issue by marcelcastrobr** [gohugoio/hugo#10645]
Hi all,
 I was wondering if hugo has the ability to create a mind map from a markdown text.
 Something similar to https://github.com/markmap/markmap ?

**Comment by cansurmeli** [comment]
Hey.

As per the [docs](https://gohugo.io/documentation/), no such feature is currently implemented within Hugo.

Plus, as my personal view, I think such a feature is better implemented as a Hugo theme anyway.

Best.

**Comment by Darthagnon** [comment]
You're probably best off using a Hugo theme with [Mermaid JS](https://mermaid.js.org/#/); I'll be adding it to my general shortcode collection at some point.

**Comment by jmooring** [comment]
@marcelcastrobr 

Please search
