### ISSUE TITLE
ref unhandling `maps.Params` input

### ISSUE THREAD

**Issue by septs** [gohugoio/hugo#10646]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

markdown partial:

```markdown
---
title: Japan
ref: { path: '/', lang: 'ja' }
---
```

html template partial:

```plain
relref . .Params.ref
```

error info:

> Error: Error building site: failed to render pages: render of "page" failed: ".../layouts/_default/baseof.html:40:4": execute of template failed: template: _default/single.html:40:4: executing "main" at <partial "content/sitemap" .>: error calling partial: ".../layouts/partials/content/sitemap.html:28:16": execute of template failed: template: partials/content/sitemap.html:28:16: executing "render-sitemap" at <relref . .Params.ref>: error calling relref: unable to cast maps.Params{"lang":"ja", "path":"/"} of type maps.Params to string

**Comment by khayyamsaleem** [comment]
👋🏽 so it looks like hugo doesn't automatically convert golang maps to template dicts. I wouldn't exactly classify this as a bug, but it could make sense (as a feature proposal) to try to parse yaml map values as dicts before assuming it's a string.

If you're trying to use the second signature for `relref` as in [this documentation](https://gohugo.io/functions/relref/), you might have to `range` over `.Params.ref`, collect it into a `dict`, and then pass it into `relref` in your partial.
