### ISSUE TITLE
Data Files eat memory

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#1065]
See

http://discuss.gohugo.io/t/runtime-garbage-collector-found-invalid-heap-pointer/1076/10

**Comment by bep** [comment]
Note to self: Revisit this with Go 1.5.

**Comment by bep** [comment]
I have done some fresh testing on this with 700mb worth of JSON files, which needs 4,5 GB of memory.

I also tested to unmarshall into a `json.RawMessage` and that cuts the memory requirement in half. But the raw message is useless as is ...

So I think the solution is load these objects lazilly, but I have now idea how to do that without breaking the API.

So given 

```
/data/file1.json 
/data/file2.json 
/data/file3.json 
```

{{ .Site.Data.file2.key1 }}

Would only load file2 and preferable also only unmarshal key1 in that file. If `Site.Data` was a method and `file2` and `key1` were arguments to that method, I kind of know how to implement it ... 

Any tips? @spf13 @tatsushid

**Comment by tatsushid** [comment]
If we fulfill both keeping the current template syntax and changing the behavior, I think we need to modify a template AST directly. An parsed template provides `Tree.Root` member and it keeps all parsed template nodes so we can modify them. Please see [the sample code](https://play.golang.org/p/p5RL3CzvKI)

While we can do above, I prefer changing API with an announcement personally.

**Comment by mattpaz** [comment]
Any updates with Go 1.6?  I haven't been monitoring advancements closely, but was thinking about returning to it this summer.   If it requires an API update, any feel for where is might land on a roadmap.  I expect this is an edge case, so I'm not getting my hopes up, but thought i'd check in nonetheless.

**Comment by bep** [comment]
Just about the same with Go 1.6.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by bep** [comment]
Just tested this with 670M worth of JSON data, and it seems to have improved a little. May be the type of data files I use:


```
▶  du -h data && time hugo
671M	data
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
4 regular pages created
16 other pages created
0 non-page files copied
6 paginator pages created
2 tags created
0 categories created
total in 3172 ms
hugo   0.74s  user 1.49s system 65% cpu 3.395 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                788740 MB
page faults from disk:     19
other page faults:         409721
```

Same site, no data:

```
▶ du -h data && time ago
  0B	data
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
4 regular pages created
16 other pages created
0 non-page files copied
6 paginator pages created
2 tags created
0 categories created
total in 17 ms
hugo   0.05s  user 0.02s system 112% cpu 0.059 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                14708 MB
page faults from disk:     9
other page faults:         4048
```

**Comment by bep** [comment]
I'm closing this. This isn't fixed, but for "big data", use `resources.Unmarshal`.
