### ISSUE TITLE
"ref" and "relref" appear to be failing when trying to link to peer documents.

### ISSUE THREAD

**Issue by meidaid** [gohugoio/hugo#10650]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168 windows/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

### Problem description

I have been unsuccessful using "ref" and "relref" in my *.md files.
It always produces the following errors within the web page:

> [en] REF_NOT_FOUND: Ref "tester": "C:\Users\nettl\projects\quickstart\content\english\pages\contributions\index.md:13:24": page not found
> [en] REF_NOT_FOUND: "C:\Users\nettl\projects\quickstart\content\english\pages\contributions\index.md:14:24": page not found  logged 2 error(s) 
> 
> hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168 windows/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
> 
> [Reload Page](http://localhost:1313/contributions/)

The lines in the *.md file causing the errors are as follows:

> * [tester page TEST 1]({{< relref "tester" >}})
> * [tester page TEST 2]({{< ref "tester" >}})

In this case "tester" is a directory that contains an index.md file.

This has been happening since 0.109.0...  so I upgraded to 0.110.0 with the hope that this has been resolved.

Sadly, the problem persists.

**EDIT**
I have downloaded and tested https://github.com/GSA/digitalgov.gov (a HUGO based US government site of more than 9600 pages) that makes heavy use of **ref**.  It produces no errors and the **ref** links work correctly.  **As a result, I am not sure what I am getting wrong -- if anything.**

Any help or inights are appreciated.

Thank you.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
