### ISSUE TITLE
fileExists returned path when file does exists, instead of boolean

### ISSUE THREAD

**Issue by fourjuaneight** [gohugoio/hugo#10658]
### What version of Hugo are you using (`hugo version`)?

v0.110.0

### Does this issue reproduce with the latest release?

Yes.

On v0.109.0, `fileExists` outputs a boolean, as expected.

### Environment

macOS 12.6.2
Hugo installed via Homebrew.

**Comment by jmooring** [comment]
I am unable to reproduce the problem as described.

With this content structure...

```text
content/
├── posts/
│   └── post-1.md
└── _index.md
```

`{{ os.FileExists "content/posts/post-1.md" }}` returns `true`

**Comment by fourjuaneight** [comment]
Thanks for the help 👍🏽
