### ISSUE TITLE
TableOfContentsc causes timeout when {{ exists in code block.

### ISSUE THREAD

**Issue by willhaines** [gohugoio/hugo#10654]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

### Description

I discovered this while using the [geekdocs](https://github.com/thegeeklab/hugo-geekdoc) theme, but as far as I can tell the bug is not specific to that theme.

If your page has:
    1. A code block with the sequence `{{` somewhere in it
    2. That code block is wrapped in a shortcode that renders it to html
    3. A table of contents
then, it will cause a timeout and fail to render.

Oddly enough, removing the table of contents from such a page fixes the problem. As does, having the code block not be wrapped in a shortcode.

### Error message

```
$ hugo server
Start building sites …
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
Error: Error building site: "/tmp/my_hugo/content/posts/my-first-post.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.
Built in 30068 ms
```

### How to reproduce

`layouts/shortcodes/noop.html`
```
{{ .Inner | $.Page.RenderString }}
```

`layouts/shortcodes/toc.html`
```
{{ .Page.TableOfContents }}
```

`content/posts/my-first-post.md`
<pre>
---
title: "My First Post"
date: 2023-01-24T13:08:10-07:00
draft: false
---

{{< toc >}}

## this is a heading

{{< noop >}}
```
this is some code
   containing
     {{ sequence
```
{{< /noop >}}
</pre>

**Comment by jmooring** [comment]
When you include `.TableOfContents` in a shortcode, it forces the current page to be rendered, which includes the shortcode...

:chicken: → :egg: → :chicken: → :egg: → …

See <https://discourse.gohugo.io/t/36758/2>

**Comment by jmooring** [comment]
Re-opening.

**Comment by bep** [comment]
To be clear:

This should work:

In a shortcode in page "foo":

```
{{ .Page.TableOfContents }}
```

Should work.

```
{{ (site.GetPage "foo" ).TableOfContents }}
```

Will create an infinite recursion.

What I suspect is creating a infinite recursion above is the noop shortcode with:

```
{{ .Inner | $.Page.RenderString }}

```

I'm pretty sure it's not about any `{{` in the code block, and I suspect you need to simplify your shortcode setup to make this work.

**Comment by jmooring** [comment]
I can reproduce this as described with v0.100.0 and later, but not with v0.99.1.

Git bisect says 9e904d756be02ca30e4cd9abb1eae8ba01f9c8af is the first bad commit.

```text
git clone --single-branch -b hugo-github-issue-10654 https://github.com/jmooring/hugo-testing hugo-github-issue-10654
cd hugo-github-issue-10654
hugo server
```

**Comment by bep** [comment]
Ah, OK, yea then I understand, thanks for the clarification...
