### ISSUE TITLE
Goldmark: ARIA `role` attribute in Markdown content is not rendered

### ISSUE THREAD

**Issue by MasterKale** [gohugoio/hugo#10661]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1-5AFE0A57+extended darwin/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes, I confirmed it's still an issue with v0.110.0:

```
$ hugo version
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended darwin/arm64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
```

### Context

I was testing out [Hugo's Markdown attribute support](https://gohugo.io/getting-started/configuration-markup/) with the following text in a **.md** file in **content/posts/**:

```
blah blah blah
{.note role="note" data-hello="world"}
```

Hugo drops the `role="note"` attribute when it renders the `<p>` element:

![Screenshot 2023-01-27 at 9 23 29 AM](https://user-images.githubusercontent.com/5166470/215153195-5e7d9101-6100-4ac3-819b-f271feb6235f.png)

It's desirable to be able to define [ARIA attributes like this](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/note_role) for those sites that aim to better support screen readers and accessibility in general.

**Comment by jmooring** [comment]
https://github.com/yuin/goldmark/pull/358
