### ISSUE TITLE
Is there any other way to generate the url path not based on the file name of the markdown

### ISSUE THREAD

**Issue by ns-cn** [gohugoio/hugo#10667]
Is there any other way to generate the url path not based on the file name of the markdown, but based on other way, such as MD5 of the file name. The path of Chinese file name generation is very long after encoding and is not easy to share.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
