### ISSUE TITLE
"hugo --watch" not updating all related files

### ISSUE THREAD

**Issue by echarp** [gohugoio/hugo#10670]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0+extended linux/amd64 BuildDate=2023-01-27T10:03:29Z VendorInfo=debian:0.110.0-1
</pre>

### Does this issue reproduce with the latest release?
It reproduces with 0.109 and 0.110, not with 0.108 and former.

Also tested using the debian packages distributed on github.

### Context

When using `hugo --watch`

### Problem

A modification to an existing file do not regenerate all related files. For example tags or other lists.

A file creation or deletion does work.

### Other way to detect the issue

`hugo --watch` is much faster than usual (which initially was great :))!

**Comment by bep** [comment]
Thanks for this. We do have other similar issues, so I'm closing this for now. We are working on improving this situation, stay tuned. I'm not sure your description is totally correct as to the current situation, but lets just let wait and see if we can do better. 

Also note that there is a `--disableFastRender` flag to the server command that may help, as the default is to just render the page "you're looking at".

**Comment by echarp** [comment]
It would seem the `disableFastRender` flag can be set in the `config` file, and now the `--watch` command is updating all related files correctly!

It is not usable (yet?) as a command line flag when using `--watch`.

Thanks for the great work!!!
