### ISSUE TITLE
Fix shortcode error message

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10672]
When a shortcode is closed, with either a closing tag or self-closing, and neither `.Inner` nor `.InnerDeindent` is evaluated in the shortcode, we currently emit this:

> failed to extract shortcode: shortcode “>}}” has no .Inner, yet a closing tag was provided

Suggest this instead:

> failed to extract shortcode: shortcode “{{ name-of-shortcode }}” does not evaluate .Inner or .InnerDeindent, yet a closing tag was provided

Reference <https://discourse.gohugo.io/t/42190/2>

**Comment by theVJagrawal** [comment]
Can I work on this issue? I am pretty new to open source stuff

**Comment by bep** [comment]
@theVJagrawal go ahead.

**Comment by bep** [comment]
@theVJagrawal I'm going to do this now to make sure we get this into the next release.
