### ISSUE TITLE
Mounting data directory to subdirectory does not allow access by subkey

### ISSUE THREAD

**Issue by ObjectBoxPC** [gohugoio/hugo#10681]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168 linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

### Description

I have an external directory containing JSON data files, which I mount in my site with the following configuration:

```
[[module.imports]]
source = "../external-data"
target = "data/my_section"
```

For this example, suppose that the `external-data` directory contains a `my_data.json` file with the contents `{ "my_key": "my value" }`.

Because the target is the `my_section` subdirectory, I expect to be able to access the data in my templates using `.Site.Data.my_section...`. With the example data given previously, this would be `.Site.Data.my_section.my_data.my_key`. However, this does not work; I have to use `.Site.Data.my_data.my_key`. If I want to have the data under `my_section`, I have to create an `external-data/my_section` subdirectory instead of having it as part of the mount.

**Comment by jmooring** [comment]
Related (both closed by stalebot):
- <https://github.com/gohugoio/hugo/issues/8556>
- <https://github.com/gohugoio/hugo/issues/7616>

**Comment by jmooring** [comment]
As noted in one of the related issues, this...

```text
[[module.mounts]]
source = 'data'
target = 'data'

[[module.mounts]]
source = "../external-data"
target = "data/my_section"
```

...mounts `../external-data/bar.toml` to `data/bar.b`

**Comment by ObjectBoxPC** [comment]
Thanks @jmooring . This seems like a clear duplicate of #7616 . I'm not sure if #8556 is the same issue though. I get the impression that that one had more to do with trying to mount a single file rather than an individual directory.

**Comment by jmooring** [comment]
Because https://github.com/gohugoio/hugo/issues/7616 is closed, let's leave this issue open.

**Comment by michaeltlombardi** [comment]
I just ran into this again in my own work - being able to mount data to the correct subfolder (and thus dot-path) would be hugely helpful for me. I have some monorepos where multiple projects share the same docs site, and this becomes a very funky workaround problem, unfortunately.
