### ISSUE TITLE
lineNos in code block info string throws error with v0.93.0 and later if value is not boolean

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10682]
With v0.92.2 and earlier, either of these work (note the mixed case of the key in the first example):

````text
```text {lineNos=inline}
a
```

```text {linenos=inline}
a
```
````

With v0.93.0 and later, this throws an error:

````text
```text {lineNos=inline}
a
```
````

> 1 error(s) decoding: * cannot parse 'LineNos' as bool: strconv.ParseBool: parsing "inline": invalid syntax

With boolean values, naming the key `lineNos` is not a problem. The error occurs when the value is `inline` or `table` (shorthand notation for setting both `LineNos` and `lineNumbersInTable`).

I tested all of the highlighting options in the info string, using both lower and mixed case key names. The only one that fails is `LineNos`.

Git bisect says 08fdca9d9365eaf1e496a12e2af5e18617bd0e66 is the first bad commit, though I'm not sure how helpful that is given `73 changed files with 1,882 additions and 1,981 deletions.`

I ran into this because I blanked on the key name, so I copied and pasted from the [docs](https://gohugo.io/functions/highlight/#options).

**Comment by khayyamsaleem** [comment]
@jmooring is there additional context to this reproduction, like the site config's values for:

```toml
[markup]
  [markup.highlight]
    lineNos = ??? # anything here?
```

**Comment by jmooring** [comment]
> is there additional context

No. Simple example:


```text
git clone --single-branch -b hugo-github-issue-10682 https://github.com/jmooring/hugo-testing hugo-github-issue-10682
cd hugo-github-issue-10682
hugo
```
