### ISSUE TITLE
Embedded version of 'goat' needs update or CSS change

### ISSUE THREAD

**Issue by berthubert** [gohugoio/hugo#10699]
Again many thanks for Hugo!!

In the latest hugo:
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168 linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio

I encounter the problem that 'goat' ASCII art looks terrible. I use the Minimo theme, but not sure if that is relevant to the issue.

From CSS experts, I hear the problem is that Goat inherits the font settings from the main CSS. This makes things look terrible. 

If I manually add:

```
{{<rawhtml>}}
<style>
text {font-family: monospace; }
</style>
{{</rawhtml>}}
```

Things are good again (since Hugo uses <text>). 

I am also told that newer versions of Goat explicitly set the font: https://github.com/blampe/goat/blob/07bb911fe3106cc3c1d1097318a9fffe816b59fe/svg.go#L51

So an upgrade may resolve this issue.

**Comment by jmooring** [comment]
When I use the minimo theme I see this:

<img alt="screen capture" src="https://user-images.githubusercontent.com/335669/216841205-3bb34c93-73dd-4bec-b5b1-11d71794a684.png" width="500px">

And the font is set in the `svg` element:

![image](https://user-images.githubusercontent.com/335669/216841408-fa3cc451-23fd-427d-b739-db198dbc45ea.png)

**Comment by bep** [comment]
>I am also told that newer versions of Goat explicitly set the font: https://github.com/blampe/goat/blob/07bb911fe3106cc3c1d1097318a9fffe816b59fe/svg.go#L51

We (Hugo) does that, too. But we even provide a template func so you can create your own `svg` markup if needed. I'm closing this. Take further qs at https://discourse.gohugo.io/
