### ISSUE TITLE
Chroma: YAML indentation sometimes doubled

### ISSUE THREAD

**Issue by willhaines** [gohugoio/hugo#10692]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

yes

### Steps to reproduce

1. Create a yaml code block (or highlight shortcode)
2. Include a single-line block scalar in your YAML
3. See that the block scalar content is indented twice as far in the rendered output, compared to the input.

### Example

<pre>
---
title: "Post"
date: 2023-02-02T08:34:04-07:00
draft: false
---

```yaml
one:
  two:
    three: |
      four
    five: |
      six
      seven
```

{{< highlight yaml >}}
one:
  two:
    three: |
      four
    five: |
      six
      seven
{{< /highlight >}}
</pre>

![image](https://user-images.githubusercontent.com/4226764/216715957-2176a8c6-c746-4bcd-a87d-29ffef9aad6a.png)

### Background

As far as I can tell, the problem is not present upstream in https://github.com/alecthomas/chroma

<pre>
$ go version -m ~/bin/hugo | grep -i chroma
        dep     github.com/alecthomas/chroma/v2 v2.4.0  h1:Loe2ZjT5x3q1bcWwemqyqEi8p11/IV/ncFCeLYDpWC4=
</pre>

![image](https://user-images.githubusercontent.com/4226764/216716097-33d31c5f-fa30-4355-bc5f-714dad32ee52.png)

**Comment by jmooring** [comment]
This is a Chroma issue, and it was resolved with https://github.com/alecthomas/chroma/commit/5ca7345671490cbc9dfd3e122a4dfc617e977992. That commit occurred after the release of 2.4.0. We'll get the update when the author rolls another release.

**Comment by willhaines** [comment]
Ah, thanks! Sorry for not digging deep enough upstream!
