### ISSUE TITLE
markdownify creates .File.Path on zero object. Wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}

### ISSUE THREAD

**Issue by thalib** [gohugoio/hugo#10697]
### What version of Hugo are you using (`hugo version`)?

<pre>
PS D:\Git\site> hugo version
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended windows/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

### Issue markdownify  throws warning. 

Below is my template code in which I add bootstrap class to all tables.
```
{{ $old := "<table>" }}
{{ $new := "<table class=\"table table-sm\">" }}
{{ $htmlContent := .Content | markdownify }}
{{ $htmlContent = replace $htmlContent $old $new }}
{{ $htmlContent | safeHTML }}
```

When compiling the site I get a warning, 
I found out this warning is generated by **{{ $htmlContent := .Content | markdownify }}**

```
WARN 2023/02/04 18:30:31 .File.Path on zero object. Wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}
```

I think this is a bug

**Comment by jmooring** [comment]
`.Content` is fully rendered. Do not try to "markdownify" fully rendered content.  You can do this:

```
{{ $old := "<table>" }}
{{ $new := "<table class=\"table table-sm\">" }}
{{ replace .Content $old $new | safeHTML }}
```

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
