### ISSUE TITLE
incorrect escaping

### ISSUE THREAD

**Issue by simevo** [gohugoio/hugo#10707]
### What version of Hugo are you using (`hugo version`)?

The stock package on Debian bookworm:

<pre>
$ hugo version
hugo v0.110.0+extended linux/amd64 BuildDate=2023-01-27T10:03:29Z VendorInfo=debian:0.110.0-1
</pre>

### Does this issue reproduce with the latest release?

Yes, this is the latest release.

### Problem description

I configure a global parameter `baseURL = "/"`, and request it to be inserted as known-safe JavaScript (https://gohugo.io/functions/safejs/) within some backtick-delimited JavaScript strings inside a `<script>` tag.

In certain cases the slash is incorrectly escaped.

### Minimal example

Extract [minimal.zip](https://github.com/gohugoio/hugo/files/10686016/minimal.zip) in `/tmp/minimal`, launch `hugo`, then look at `public/index.html`:

```
      let a = `/</`
      let b = `\//`
      let c = `//`
```

based on the `layouts/shortcodes/home_map.html` shortcode:

```
      let a = `{{ .Site.BaseURL | safeJS }}</`
      let b = `{{ .Site.BaseURL | safeJS }}/`
      let c = `{{ .Site.BaseURL | safeJS }}/`
```

I'd have expected this output:

```
      let a = `/</`
      let b = `//`
      let c = `//`
```

but the slash in the second string is escaped. If you remove the `<` line from the first string, all urls are correctly unescaped.

Something weird is going on!

**Comment by jmooring** [comment]
This seems like a bug in Go's html/template package. If I switch to using Go's text/template package with...

```
[outputFormats.HTML]
isPlainText = true
```
... I get the expected results:

```
 <script>
let a = `/</`
let b = `//`
let c = `//`
</script>
```

**Comment by bep** [comment]
I (think) this should test it in Go: https://go.dev/play/p/uHRYjxnzIaI?v=goprev

But that gives me:

```
let a = `/&lt;/`
let b = `//`
let c = `//`
```

Which I also assume is not correct.

**Comment by bep** [comment]
OK, revisiting this with:

https://go.dev/play/p/Nl4_5-ynidw?v=goprev

Wrapping it in `<script>` makes it behave sensible.

**Comment by jmooring** [comment]
Do you want me to log an issue upstream?

**Comment by bep** [comment]
>Do you want me to log an issue upstream?

Yes, that would be good (I suspect they're a little tired of my issue "spamming").

**Comment by jmooring** [comment]
<https://github.com/golang/go/issues/58460>

**Comment by jmooring** [comment]
The original issue was opened on Dec 3, 2014.
https://github.com/golang/go/issues/9200

**Comment by karelbilek** [comment]
This is a known go bug with no easy solution
