### ISSUE TITLE
Docs wording improvement

### ISSUE THREAD

**Issue by mefrem** [gohugoio/hugo#10705]
The _Getting Started_ guide's [All Configuration Settings](https://gohugo.io/getting-started/configuration/#all-configuration-settings) says

> The following is the full list of Hugo-defined variables with their default value in _parentheses_.

This should be changed to _double quotes_.

<img width="583" alt="Screenshot 2023-02-07 at 9 29 46 PM" src="https://user-images.githubusercontent.com/51917427/217422212-ce1c68ee-f7f4-4f90-878e-3a3cb45a8225.png">

**Comment by jmooring** [comment]
Closed with https://github.com/gohugoio/hugoDocs/commit/596af47f5829ebeae7b00855250b2f0fe3f940e1
