### ISSUE TITLE
hugo import jekyll suggests unmaintained Herring Cove theme

### ISSUE THREAD

**Issue by PaulVittorino** [gohugoio/hugo#10715]
When running `hugo import jekyll`, the output instructs the user to clone the Herring Cove, which is no longer maintained.

<pre>
Importing...
Congratulations! 128 post(s) imported!
Now, start Hugo by yourself:
$ git clone https://github.com/spf13/herring-cove.git sample//themes/herring-cove
</pre>

Those messages come from this line: https://github.com/gohugoio/hugo/blob/2fc2e9c8718db2fe60f03bcf3661f449851cfe5f/commands/import_jekyll.go#L158

Is https://github.com/theNewDynamic/gohugo-theme-ananke a better choice given its usage in the Quick Start? https://github.com/gohugoio/hugo/blob/9a215d6950e6705f9109497e9f38cc3844172612/docs/content/en/getting-started/quick-start.md?plain=1#L48

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
Recommendation:

```text
Now, start Hugo by yourself:

cd hugo
git init
git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke themes/ananke
echo "theme = 'ananke'" > config.toml
hugo server
```
