### ISSUE TITLE
Hugo non-deterministically loading cached versions of pages on local dev

### ISSUE THREAD

**Issue by MattiasMartens** [gohugoio/hugo#10713]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes, I am using the latest relese

## Expected behaviour

My pages reflect the latest updates to my site on local dev.

### Actual behaviour

The local server sometimes serves cached versions of my site. Trying to clear the cache doesn't work (deleting files in the local filesystem, running with flags `--disableFastRender --gc`). When a cached version is served, refreshing doesn't fix it (maybe the browser is caching?). I have to open a new tab.

Refreshing the page with devTools on is a sure-fire way to make the server serve a cached version of the page.

**Comment by bep** [comment]
I'm pretty sure this is the browser cache doing it's job.

You can do one of 2 things:

1. Run with Chrome's dev console with the "cache disabled" box checked (which is default) in the Networks tab. This is what I do.
2. Run `hugo server --noHTTPCache`. This option is a little more drastic compared to 1 and may slow down the page refreshes.

**Comment by MattiasMartens** [comment]
Thanks @bep for the fast response.

- "cache disabled": this setting was already on.
- `hugo server --noHTTPCache`: no apparent effect. refreshing with DevTools open still causes an old version to load.

What is especially odd is that the old version is from several days ago.

It occurs to me I have not tried restarting my computer since I first started seeing this. I will do so and report back.

**Comment by MattiasMartens** [comment]
I also now tried launching Hugo on a different port... At that point the cached version does not come back.

This moves me much farther toward the point of view that this is an issue with Chrome's caching policy, not Hugo's.

**Comment by MattiasMartens** [comment]
Restarting my computer had no effect. However, I now know I can evade this issue by switching ports.

I don’t know why chrome is uncontrollably caching the old version. However I don't think it's an issue with Hugo and I am happy to close.

**Comment by cansurmeli** [comment]
Just out of curiosity, does another browser, say Firefox, have the same behaviour in your condition?

Or even better Brave perhaps since the rendering engines are the same.  Caching policies could be different but merely curious.

Thanks.

**Comment by MattiasMartens** [comment]
The issue turned out to be Chrome specific. It seems they recently married their live-edit-CSS and file-override features, such that if you jimmy some styling to try out a change, that will persist on reload as long as you are in developer mode. I didn't know this and had got used to using a refresh to clear my style experiments. Turning off overrides reverts it to the old behavior.
