### ISSUE TITLE
Thumbnail visibility not working

### ISSUE THREAD

**Issue by asaqib27** [gohugoio/hugo#10728]
Thumbnail visibility is not working. I added it in config.toml as shown below but still thumbnail is showing in both places (list page and post page).
```
[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility
```

**Comment by bep** [comment]
What you describe is not a Hugo feature, so it's not surprising it's not working. I suspect this comes from a theme you're using, but you need to take that with the theme author.
