### ISSUE TITLE
Hide the --theme and -themesDir flags (and deprecate them)

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugo#10737]
`hugo -h` says in part:

```
  -t, --theme strings              themes to use (located in /themes/THEMENAME/)
      --themesDir string           filesystem path to themes directory
```

However, `--theme ../..` works, and has the same result as `--themesDir ../..`, at least on Windows.

The help message for `--theme` should reflect this.

Arguably, `--themesDir` should be deprecated and hidden, since it's redundant.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by ginaesps** [comment]
Hello! Saw this good first issue and took the liberty of creating this PR. Would really appreciate feedback on it @bep @willfaught 
#10761

**Comment by jmooring** [comment]
Given this project structure:

```text
./
├── content/
│   ├── posts/
│   └── _index.md
├── my-themes/
│   ├── theme-a/
│   ├── theme-b/
│   └── theme-c/
└── config.toml
```

To try out a theme I need to do:

```
hugo server --themesDir my-themes --theme theme-b
```

So, not sure we want to do this.

**Comment by willfaught** [comment]
I think we need at least --themesDir to run exampleSites, etc. I don't personally use --theme, but I see the value of it. I might have used it when first trying out a couple themes, before building my own.

@bep What's the rationale for removing both flags?

**Comment by bep** [comment]
>@bep What's the rationale for removing both flags?

That was maybe a bit ... rash. But my _thinking_ was that ...

* We have too. many flags. Server flags should be reserved for _tuning on runtime things_ (e.g. enable logging). If you really want to change theme while running (I suspect that is a rare thing), you can do `HUGO_THEME=foo hugo server` or something.
* But also, as we have introduced new and (sometimes) better ways to do things in Hugo, I really want to consolidate the old way with the new to avoid confusing. And now we have `theme` (which can be a slice of themes) and `module.imports`, which is the same thing but with many more options.

So, to the original title of this issue: We do need `themesDir` (the option, I'm not sure about the flag); that you happen to not strictly need it in all cases, that may be true, but in most setups, we do.

**Comment by willfaught** [comment]
So, instead we would have this?

```sh
$ cd sometheme
$ cd exampleSite
$ HUGO_THEMES_DIR=../.. hugo server
```

**Comment by ginaesps** [comment]
I read the comments and consider correct not wanting to deprecate --theme and --themesDir flags. 
As a new user, it was a bit confusing to understand the usage and if the future is to actually deprecate them, we could guide new users onto knowing better options that Hugo offers. That's why I made a small change upon my PR (instead of hiding and deprecating, changing the help message). What do you think? @willfaught @bep

**Comment by willfaught** [comment]
I don't have a strong opinion on the details. I think switching between themes is rare, and it's fine to force users to change their config file to do it. But I think the case of building a site with a theme that isn't imported as a module, and isn't in the themes directory, is a common one (exampleSite), so that should remain a CLI option. Theme authors shouldn't have to change their config file back and forth when they test their changes.

**Comment by jmooring** [comment]
Not actionable as described. Future consolidation and/or removal of CLI flags and/or configuration options is a separate issue, and not limited to theme-related flags and options.
