### ISSUE TITLE
Proper exposure time values ​​were not always returned when parsing photo files

### ISSUE THREAD

**Issue by WaltCuller** [gohugoio/hugo#10738]
### What version of Hugo are you using (`hugo version`)?
Installed from Homebrew
<pre>
$ hugo version
hugo v0.110.0+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes, at v0.110.0

### Description
I'm using a Hugo photo gallery theme [hugo-shortcode-gallery](https://github.com/mfg92/hugo-shortcode-gallery).
Strange behaviour when parsing EXIF content of photos taken with Nikon cameras.

In general, the exposure time should be expressed in fractions, such as 1/100sec, 1/ 320sec or 10sec.

![](https://user-images.githubusercontent.com/34122242/208235075-17137bbd-fec5-4402-a649-ecaca419ec60.png)
But when I used the Hugo to generate the static pages, the exposure time was expressed in decimals.

I created a [issue](https://github.com/mfg92/hugo-shortcode-gallery/issues/53) for the theme component and request that it should return fractions in more cases.

I forked the latest Hugo repo, used my photos and other brands' raw files downloaded from the web to debug and parse EXIF info.

The conclusion is that Hugo only returns a fraction if the numerator is 1, as it isn't in some case(E.g.: Nikon NEF files or JPEGs generated from NEF), it calculates the result of the fraction. ([source](https://github.com/gohugoio/hugo/blob/e402d91ee199afcace8ae75da6c3587bb8089ace/resources/images/exif/exif.go#L179))
```go
	if n == 1 {
		rv = append(rv, rat)
	} else {
		f, _ := rat.Float64()
		rv = append(rv, f)
	}
```
This is probably not an appropriate way to get the exposure time.

**Comment by bep** [comment]
>The conclusion is that Hugo only returns a fraction if the numerator is 1, as it isn't in some case(E.g.: Nikon NEF files or JPEGs generated from NEF), it calculates the result of the fraction. ([source](https://github.com/gohugoio/hugo/blob/e402d91ee199afcace8ae75da6c3587bb8089ace/resources/images/exif/exif.go#L179))

I have tested this with RAW files (JPEG files generated from those) from a variety of Pentax cameras, a Sony A7R II and Nikon D500 -- and all of these reports a numerator of 1 for exposure time < 1. So I guess this is introduced with the new Nikon Z cameras? 

In any case, I'm not sure what the solution is, but it would be a good start if you could somehow attach an image (preferably just an image of a wall or something, so we can use it for integration testing without having to worry about copyright ...) to this issue.

**Comment by WaltCuller** [comment]
You can try this one.
![shanghai](https://user-images.githubusercontent.com/34122242/210217291-58ff64b0-dfc3-445f-8f11-e659b687655e.jpeg)

**Comment by WaltCuller** [comment]
How about this modification?

**Comment by bep** [comment]
Yea, that looks sensible -- but the test images needs to be in kilobytes and not 10-30 megabytes, and they also need to be obviously not copyrighted. If you can demonstrate this with a small JPG, that would be great.
