### ISSUE TITLE
`hugo gen chromastyles` generates UTF-16 formatted files (which is not supported by Hugo at the moment)

### ISSUE THREAD

**Issue by hugo-sid** [gohugoio/hugo#10747]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended windows/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes. I'm using the latest release.

## What's the issue ?

I encountered the following error while running `hugo server --themesDir ../..` .
```
Error: Error building site: TOCSS: failed to transform "main.scss" (text/x-scss): "C:/Users/abcd/hugo-site/assets/scss/highlight.css:1:1": only UTF-8 documents are currently supported; your document appears to be UTF-16 (little endian) 
Built in 322 ms
```

## Background

I wanted to use custom code highlighting. So, I ran `hugo gen chromastyles --style=catppuccin-macchiato > highlight.css`.
Then I included the following in config.toml.
```
pygmentsUseClasses = true
pygmentsCodefences = true
```

Then I moved the `highlight.css` from root to  `assets\scss\highlight.css` .

Then I called the `highlight.css` file in `assets\scss\main.scss` as follows.
```scss
// assets\scss\main.scss
@import "normalize";
@import "utils";
@import "markup";
@import "fonts";
@import "print";

@import "markdown";
@import "shortcodes";

// Custom code highlighting
@import "highlight";

// Custom defined styles
@import "custom";
```

The `main.scss` is called in `header` partial as follows.
```go
{{- $styles := resources.Get "scss/main.scss" | resources.ExecuteAsTemplate "main.scss" . | resources.ToCSS | resources.Minify | resources.Fingerprint }}
<link rel="stylesheet" href="{{ $styles.RelPermalink }}" {{ template "integrity" $styles }}>
```

## Fix
When I saved `highlight.css` in `UTF-8`, the issue was fixed.

## Thoughts
Don't know why `hugo gen chromastyles` generates UTF-16 formatted file. I don't think it's necessary to add support for UTF-16  in Hugo.

**Comment by bep** [comment]
This is really odd, and not something that I have experienced. Maybe a Windows issue?

**Comment by hugo-sid** [comment]
I just tried running `hugo gen chromastyles --style=doom-one2 > highlight2.css`. This time also the formatting was `UTF-16`.

![image](https://user-images.githubusercontent.com/122173059/220970523-80891860-7f35-46af-a50e-daf94ef33e9d.png)

**Comment by hugo-sid** [comment]
I do remember `hugo gen chromastyles` last year around December. There was no issue then.
I think that time I had Hugo version `v0.108`.

**Comment by jmooring** [comment]
This isn't a Hugo thing. This is a Windows thing. It depends on which terminal you use.

- CMD: UTF-8
- Windows Powershell: UTF-16 LE
- Powershell: UTF-8 

Powershell is the new (7.x) version of Windows Powershell (5.x).

And you can run all of them from within Windows Terminal. This is on my MS stupid list.

**Comment by jmooring** [comment]
And just to round things out, there's also the Azure Cloud Shell and WSL.
