### ISSUE TITLE
livereload can't work after changing the content of all files except hugo.toml

### ISSUE THREAD

**Issue by turtlekey** [gohugoio/hugo#10756]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
yes.

**Comment by bep** [comment]
You need to provide more information.
