### ISSUE TITLE
“Web Server is available at //localhost:1313/” is printed for no baseurl config

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugo#10765]
There’s no URL scheme. I can’t double click it to browse to it, and http://localhost:1313/ _does_ work. What is printed should accurately reflect what's doing.

It was observed that the current behavior can have some support value, since it can hint that the config is invalid. However, in my opinion, this is outweighed by the value of having unsurprising and useful behavior.

See: https://discourse.gohugo.io/t/web-server-is-available-at-localhost-1313-is-printed-for-no-baseurl-config/43139

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by bep** [comment]
>What is printed should accurately reflect what's doing.

It's printing what's configured.

* We have considered added some validation to `baseURL`, but that would probably break more than it should.
* So, if you're not adding a valid `baseURL`, the behaviour you get is undefined. Something may work, others will not.

**Comment by serhack** [comment]
We might want to mention this on the docs.

**Comment by willfaught** [comment]
>It's printing what's configured.

It's printing `//localhost:1313/`; what's configured is `""` (I assume; whatever the unset value is); what it's doing is serving at `http://localhost:1313/`. Thus, 'Web Server is available at //localhost:1313/”' is incorrect. It is not available at `//localhost:1313/`. When you paste that into the browser, it doesn't work.

**Comment by willfaught** [comment]
This could be fixed with a minor wording change. Instead of adding the http://, have it print `Web Server is configured to be available at //localhost:1313/`. Of course, then you'd get the confusion about the behavior not matching that, but again, that would be fixed by my suggestion above.

**Comment by wkoszek** [comment]
I came to Hugo's issues to report this ^^^ issue too and noticed it discussed here. I do have `baseURL` in the config, and start `hugo` during theme development mode with this CLI:

```
hugo server --config wkoszek/config.toml -c wkoszek --themesDir . --theme wktheme -d out
```

and `//localhost:1313/` is also printed. I use iTerm2 on Mac and with this format, I can't CMD+click to open this link. It'd be nice if http://localhost:1313/ was printed in the output somewhere, so that I can jump to the preview quickly.

**Comment by willfaught** [comment]
@wkoszek What's your baseURL set to?

**Comment by wkoszek** [comment]
@willfaught `baseURL = 'koszek.org'`

**Comment by willfaught** [comment]
`baseURL = "http://koszek.org"` should work.

**Comment by wkoszek** [comment]
@willfaught works indeed.

**Comment by jmooring** [comment]
Addressed with documentation update:
https://github.com/gohugoio/hugoDocs/commit/c79319a6ae09f0618cd3fd36445edef49e088e91

<https://gohugo.io/getting-started/configuration/#baseurl>
