### ISSUE TITLE
function "page" not defined

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10774]
hugo v0.111.0-DEV-66f94b4945e804f10be0a04d1365bb3c6e1a4c05+extended linux/amd64 BuildDate=2023-03-01T17:11:44Z

In layouts/_default/single.html

```
{{ page.IsHome  }}
```

> parse failed: template: _default/single.html:4: function "page" not defined

The [integration test](https://github.com/gohugoio/hugo/blob/master/tpl/page/integration_test.go) passes, so I'm not sure what's happening here.

**Comment by bep** [comment]
Hmm...
