### ISSUE TITLE
.ReadingTime fails in i18n templates

### ISSUE THREAD

**Issue by nunomazer** [gohugoio/hugo#10782]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.111.0
hugo v0.111.1
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
I cannot reproduce on Linux or Windows 11 when layouts/_default/single.html contains

{{ .ReadingTime }}

So, we will need a bit more information...

**Comment by bep** [comment]
So, I understand the `what` but not the how/where. To get the `page` global template func working, we added the `context.Context` as first argument to the methods that needed the `page`, but we have plenty of tests for this ... Do you pass the page into the `i18n` function? I guess that is possible, but not something I have done/seen myself.

**Comment by bep** [comment]
OK, thinking about this, this must be the language strings templates. That runs its own template setup (missing all of the template funcs etc.) which finally got very visible and needs a fix.

**Comment by bep** [comment]
OK, so tested that, and while it doesn't work, it does not produce any error, so the above is most likely something else, meaning we need some feedback from @nunomazer

**Comment by nunomazer** [comment]
Thanks @bep for quick answer. I am not the theme creator, I'm using https://github.com/razonyang/hugo-theme-bootstrap.   

> I cannot reproduce on Linux or Windows 11 when layouts/_default/single.html contains
> 
> {{ .ReadingTime }}
> 
> So, we will need a bit more information...

Sorry I am not the theme creator and don't know Hugo enough to answer. I'm using https://github.com/razonyang/hugo-theme-bootstrap.

**Comment by bep** [comment]
Yea, it's almost certainly this:

https://github.com/razonyang/hugo-theme-bootstrap/blob/05f5a2e968e7f8748de6136eae22e626acdeeb5c/i18n/de.toml#L213
