### ISSUE TITLE
page.TableOfContents hangs

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10791]
hugo v0.112.0-DEV-f56ce01ae1a3e5b399410ea8876ebc7321204edd+extended linux/amd64 BuildDate=2023-03-04T21:04:01Z

> Error: Error building site: "/home/jmooring/code/hugo-testing/content/_index.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.

markdown

```
{{< toc >}}
```

layouts/shortcodes/toc.html (no problems)

```
{{ .Page.TableOfContents }}
```

layouts/shortcodes/toc.html (error / timed out)

```
{{ page.TableOfContents }} 
```

Sorry.

**Comment by bep** [comment]
I willl look at this, but:


{{ .Page.TableOfContents }}
{{ page.TableOfContents }} 

The two above isn't the same thing unlsess .Page == page.

**Comment by bep** [comment]
OK; I now understand what's happening.

There's a special construct for shortcodes which allows calling `.TableOfContents` on itself. That isn't available on the `page`so to speak. 

So, 

* your construct is creating an infinite loop, and that is not something that I can fix.
* but it's safe to use `.Fragments` to create the same ToC, assuming you use the correct delimiter.

**Comment by bep** [comment]
Well, it's not very hard to fix -- but it's not a bug.

**Comment by jmooring** [comment]
It should be _very_ far down on your list.

**Comment by bep** [comment]
Also,

```
{{ page.TableOfContents }} 
```

From a shortcode doesn't make much sense as you currently will get the ToC of the first page that calls `.Content` which may or may be a totally different page than you think it is. That particular problem may be fixable (and that would be useful), but that's certainly not "today".
