### ISSUE TITLE
date incorrectly requires buildFuture

### ISSUE THREAD

**Issue by udf2457** [gohugoio/hugo#10795]
At present `date` incorrectly requires the use of the `buildFuture` flag.

According to [the docs](https://gohugo.io/content-management/front-matter/), `buildFuture` should only ever be required for `publishDate`.

Use-case for why this is a bug:

Imagine I am creating a website where one page is a list of past, current and upcoming events. Use of `date` in this context is of critical importance because it allows me to use `.ByDate` to present the events in correct time order.

Why being forced to use `buildFuture` with `date` is unacceptable :

It is unacceptable to require the user to use `buildFuture` with `date` because the user may well still wish to have "hidden" articles (e.g. due to embargo restrictions). 

Therefore the correct use-case for `buildFuture` remains only in association with `publishDate` and **NOT** with `date`/

**Comment by jmooring** [comment]
See <https://gohugo.io/getting-started/configuration/#configure-dates>

If you don't want to use `date` as a fallback for `publishDate`, change your site configuration to:

```text
[frontmatter]
publishDate = ['publishDate']
```

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
