### ISSUE TITLE
Missing sections in academic template demo website

### ISSUE THREAD

**Issue by yyzhou9** [gohugoio/hugo#10792]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.96.0

</pre>

### Does this issue reproduce with the latest release?

Yes

### Issue
The demo picture (attached below) of the [academic template](https://academic-demo.netlify.app/) shows that there are "Interests" and "Education" sections. However, these sections are missing from the demo website. I cloned the template repository and modified the files. Upon further investigation, I found that the "Interests" and "Education" sections exist in the markdown files, but they do not show on the website.

I do not believe that these sections were intentionally disabled, as they are included in the template files. Therefore, I am reaching out to inquire if there is anything I can do to make the "Interests" and "Education" sections appear on the website.

I would greatly appreciate any guidance or assistance you can provide in resolving this issue. Thank you for providing this fantastic template and for your time and attention!

## Demo picture of academic
![A](https://p.ipic.vip/tu6qej.png)

## Demo website of academic
![B](https://p.ipic.vip/tc06uf.png)

**Comment by jmooring** [comment]
This isn't our thing.

Contact the Wowchemy team:
<https://github.com/wowchemy/wowchemy-hugo-themes/discussions>

They also have an active Discord channel:
<https://discord.com/invite/z8wNYzb>

**Comment by yyzhou9** [comment]
Thank you for your prompt reply!
