### ISSUE TITLE
Error "unknown shortcode token" when calling shortcode within fenced code block

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10819]
**N.B. I'm not sure if this is a bug, or if we've fixed a bug.**

Reproducible with v0.111.0 and later.

If a shortcode is called using the `{{< >}}` notation within a fenced code block, Chroma lexes the placeholder, triggering an error such as:

> unknown shortcode token "HAHAHUGOSHORTCODE</span><span style=\"color:#f92672\">-</span><span style=\"color:#a6e22e\">s0</span><span style=\"color:#f92672\">-</span><span style=\"color:#a6e22e\">HBHB"

But this does not happen with all lexers, and may depend on where the shortcode is placed within the codeblock (not sure).

For example, this works:

````text
```bash
{{< sc >}}
```
````

But this throws an error:

````text
```go
{{< sc >}}
```
````

And both of these work:

````text
```bash
{{% sc %}}
```

```go
{{% sc %}}
```
````

What the shortcode does is irrelevant (e.g., it can be empty).

Reference: <https://discourse.gohugo.io/t/43387>  (Kubernetes site)

Simple example:

```text
git clone --single-branch -b hugo-forum-topic-43387 https://github.com/jmooring/hugo-testing hugo-forum-topic-43387
cd hugo-forum-topic-43387
hugo server
```

**Comment by bep** [comment]
>N.B. I'm not sure if this is a bug, or if we've fixed a bug.

I suspect the latter.

When you say "this works":

```md
```bash
{{< sc >}}
```
```

The technical reasons why this fails is that some Chroma highlighters highlights the hyphen in the temporary placeholder, which doesn't work ...

However, the above construct looks a little bit odd since the output of `{{< sc >}}` will not be highlighted by Chroma. ``{{% sc %}}` will.

But we need to fix this anyway.

**Comment by craigbox** [comment]
Thanks @bep!  I'll update the markup used in the Kubernetes docs.

FWIW, it was hard to find this due to #10735. 

```
Error: Error building site: "/Users/craigbox/Documents/Projects/kubernetes.io/content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md:1:1": unknown shortcode token "HAHAHUGOSHORTCODE-s12</span>-HBHB"```
