### ISSUE TITLE
No extended release on fedora

### ISSUE THREAD

**Issue by dasShounak** [gohugoio/hugo#10810]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.111.2-4164f8fef9d71f50ef3962897e319ab6219a1dad+extended linux/amd64 BuildDate=2023-03-05T12:32:20Z VendorInfo=snap:0.111.2
</pre>

### Does this issue reproduce with the latest release?
No

---
### Installation on Fedora
The Fedora repositories doesn't have the Hugo Extended version. I downloaded the dnf package but it was not the extended version. Had to use Go instead.

**Comment by bep** [comment]
I suspect you will get faster response on this if you posted this on the Fedora issue tracker (if one exists).

**Comment by dasShounak** [comment]
Okay. I will look into it.

**Comment by jmooring** [comment]
@dasShounak 

In your original post you show this:

> hugo v0.111.2-4164f8fef9d71f50ef3962897e319ab6219a1dad+extended linux/amd64 BuildDate=2023-03-05T12:32:20Z VendorInfo=snap:0.111.2

That indicates that (a) you installed Hugo as a snap, and (b) it _is_ the extended version.

And with a fresh install of Fedora release 37,:

```
sudo dnf install hugo
hugo version
```

> Hugo v0.98.0+extended linux/amd64 BuildDate=unknown
