### ISSUE TITLE
Use of undocumented API in example code

### ISSUE THREAD

**Issue by septs** [gohugoio/hugo#10817]
https://github.com/gohugoio/hugo/blob/84201e8d5d319399a868e64d20d7a40e5aae2023/resources/page/page.go#L324-L326

https://github.com/gohugoio/hugo/blob/84201e8d5d319399a868e64d20d7a40e5aae2023/docs/content/en/content-management/diagrams.md?plain=1#L54

**Comment by septs** [comment]
Search: https://github.com/search?q=repo%3Agohugoio%2Fhugo+.Store+language%3AMarkdown&type=code&l=Markdown

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues
