### ISSUE TITLE
Feature to skip trailing slash in URL

### ISSUE THREAD

**Issue by incogGod** [gohugoio/hugo#10829]
Feature to give an option to the user whether to skip or show the trailing slash in the URL.

**Comment by jmooring** [comment]
There are two ways to interpret this request.

1\) Do not change the published path, but remove the trailing slash from the generated URL.

Content path|Published path|URL
:--|:--|:--
`/about.md`|`/about/index.html`|`/about`

With this model, when you request `https://example.org/about`, the server will send a 301 redirect request, pointing the browser to `https://example.org/about/`. Every visitor, to every page, will be redirected to a URL with a trailing slash.

2\) Change the published path, and make the URL match.

Content path|Published path|URL
:--|:--|:--
`/about.md`|`/about`|`/about`

With this model, when you request `https://example.org/about`, the server will find the requested file, and serve it. But without an extension, the content-type in the response header is `text/plain` (or whatever that particular server defines as a fallback). Visitors will see plain text, not interpreted HTML.

You can remove the trailing slash by enabling `uglyURLs` in site configuration, but then you will see the extension.

Content path|Published path|URL
:--|:--|:--
`/about.md`|`/about.html`|`/about.html`
