### ISSUE TITLE
New Hugo Site still created with config.toml instead of hugo.toml

### ISSUE THREAD

**Issue by rylim** [gohugoio/hugo#10821]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.111.2-4164f8fef9d71f50ef3962897e319ab6219a1dad+extended windows/amd64 BuildDate=2023-03-05T12:32:20Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

Following https://github.com/gohugoio/hugo/issues/8979 (and also in the [docs](https://gohugo.io/getting-started/configuration/#hugotoml-vs-configtoml)), new hugo sites should be created with `hugo.toml` instead of `config.toml`.

Currently on the latest hugo (`v0.111.2`), new sites are still being created with `config.toml`:

```bash
$ hugo new site new_hugo
Congratulations! Your new Hugo site is created ...

$ cd new_hugo
$ ls -las
total 13
4 drwxr-xr-x 1 User 197121  0 Mar 11 15:30 ./
4 drwxr-xr-x 1 User 197121  0 Mar 11 15:30 ../
0 drwxr-xr-x 1 User 197121  0 Mar 11 15:30 archetypes/
0 drwxr-xr-x 1 User 197121  0 Mar 11 15:30 assets/
1 -rw-r--r-- 1 User 197121 82 Mar 11 15:30 config.toml   // <-- this should be hugo.toml
0 drwxr-xr-x 1 User 197121  0 Mar 11 15:30 content/
0 drwxr-xr-x 1 User 197121  0 Mar 11 15:30 data/
0 drwxr-xr-x 1 User 197121  0 Mar 11 15:30 layouts/
0 drwxr-xr-x 1 User 197121  0 Mar 11 15:30 public/
0 drwxr-xr-x 1 User 197121  0 Mar 11 15:30 static/
0 drwxr-xr-x 1 User 197121  0 Mar 11 15:30 themes/
```

**Comment by deining** [comment]
Please note that this was discussed in a [thread]() on hugo's discourse board already. Comment from there:

```
This is by design. We’ll change what `hugo new` creates at some point in the future.
```

**Comment by rylim** [comment]
> Please note that this was discussed in a thread on hugo's discourse board already. Comment from there:
> 
> ```
> This is by design. We’ll change what `hugo new` creates at some point in the future.
> ```

Got it, thanks!
