### ISSUE TITLE
Variadic math functions do not validate number of args

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10827]
&nbsp;|v0.111.2|v0.111.3
:--|:--|:--
`{{ add 1 }}`|wrong number of args for add: want 2 got 1|no error
`{{ sub 1 }}`|wrong number of args for sub: want 2 got 1|no error
`{{ mul 1 }}`|wrong number of args for mul: want 2 got 1|no error
`{{ div 1 }}`|wrong number of args for div: want 2 got 1|no error
`{{ math.Max 1 }}`|wrong number of args for Max: want 2 got 1|no error
`{{ math.Min 1 }}`|wrong number of args for Min: want 2 got 1|no error

cc @septs

**Comment by septs** [comment]
@jmooring
