### ISSUE TITLE
Cross markdown renderer context use link reference definitions

### ISSUE THREAD

**Issue by septs** [gohugoio/hugo#10832]
for example shortcode:

```go-html-template
{{ .Inner | markdownify }}
```

Article Content:

```markdown
{{< exmaple >}}

[here][here]

{{< /example >}}

[here]: https://example.com
```

Current available method:

```markdown
{{< exmaple >}}

[here][here]

[here]: https://example.com

{{< /example >}}
```

BUT editor (e.g: vscode), cannot distinguish cross context link reference definitions.

Specification: see https://spec.commonmark.org/0.18/#link-reference-definitions

Current `markdownify` or `<page>.RenderString` implementation, cannot access article link reference definitions

**Comment by bep** [comment]
So,

```
{{< example >}}

[here][here]

{{< /example >}}

[here]: https://example.com
```

The inner content of `example` above will never be part of the same Markdown rendering context as the text on the outside. This is the behaviour of `{{<` and should be well defined.

You can do:

```
{{% example %}}

[here][here]

{{% /example %}}

[here]: https://example.com
```

But you can not combine that with `{{ .Inner | markdownify }}` in the shortcode. This may be harder to wrap the head around, but I'm not seeing what you claim to be a bug in this. Could you elaborate?

**Comment by septs** [comment]
https://github.com/septs/hugo-issue-10832

**Comment by bep** [comment]
Sure, I understand why/how it behaves like in your "minimum example", but you need to explain

* Why this is a bug?
* How would you suggest it should behave?

**Comment by septs** [comment]
allow `markdownify` and `<page>.RenderString` use article link reference definitions fallback

edge case, if the problem on render code block

layouts/_default/_markup/render-codeblock-csv.html: (from https://github.com/gohugoio/hugo/issues/10636)

```html
{{- $rows := .Inner | transform.Unmarshal }}
<table>
<thead><tr>{{ range (index $rows 0) }}<th>{{- . -}}</th>{{ end }}</tr></thead>
{{- $rows = after 1 $rows -}}
<tbody>
{{ range $rows -}}
<tr>{{ range . }}<td>{{- . | replaceRE `\\n` "\\\n" | markdownify -}}</td>{{ end }}</tr>
{{ end -}}
</tbody>
</table>
```

Article content:

````markdown
```csv
field 1,field 2
value 1,[here][here-1]
value 2,[here][here-2]
```

[here-1]: https://example.com/page/1
[here-2]: https://example.com/page/2
````

**Comment by septs** [comment]
@bep `{{<` (less-then sign) v.s `{{%` (percent sign) behavior difference can add to documentation?
