### ISSUE TITLE
3rd and 4th Level support in navigational tree

### ISSUE THREAD

**Issue by kashifiqb** [gohugoio/hugo#10837]
While exploring, i could not find the exact location to customize the left side navigation tree. I want to have structure like:

- Home
- -Docs
- --Word
- ---Images
- ---Text
--- Excel
- --- Cells
- --- Workbooks
- --- Worksheets
and so on.

Can this be supported?

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
