### ISSUE TITLE
WebP Exif support

### ISSUE THREAD

**Issue by alexvanderberkel** [gohugoio/hugo#10855]
Currently only JPEG and Tiff are support as file format for reading Exif data from files. I think it would beneficial if also exif data from WebP images could be read within hugo.

**Comment by wild0ne** [comment]
@alexvanderberkel Hey! Could you please provide a user scenario for this enhancement?

**Comment by alexvanderberkel** [comment]
Hej. Of course I can. Think about a gallery of images where you display your images. On that you would like to show also the Exif data of an image. This could be just the camera, aperture, exposure time and ISO. WebP does contain all this data similar to jpg. 

An example could be this https://github.com/mfg92/hugo-shortcode-gallery

**Comment by wild0ne** [comment]
Ok, let me look into this and see what I can do

**Comment by alexvanderberkel** [comment]
Might be it is worth thinking about introducing https://github.com/dsoprea/go-exif if this has not being considered already. The library would allow reading exif data from WebP files if I am not mistaken.  https://github.com/dsoprea/go-webp-image-structure/commit/f9047d252ea5a7142d195918df2759b2dd657b6d

**Comment by jmooring** [comment]
See https://github.com/gohugoio/hugo/issues/8586. Maintenance of [dsoprea/go-exif](https://github.com/dsoprea/go-exif) has been... sporadic.

**Comment by bep** [comment]
I started to implement a new image metadata library, but I got a little overwhelmed when I started to look at IPTC. The EXIF part was relatively straight forward, though (including WebP support), so maybe I should pick up that thread and push IPTC for another time/year.

**Comment by jbsilva** [comment]
> I started to implement a new image metadata library, but I got a little overwhelmed when I started to look at IPTC. The EXIF part was relatively straight forward, though (including WebP support), so maybe I should pick up that thread and push IPTC for another time/year.

This would be awesome.
In my case, I'm very interested in reading Exif XPKeywords (UCS-2) or IPTC Keywords. It would work great with your gallerydeluxe.

**Comment by bep** [comment]
FYI: I have started the work to get my "image meta" library over the finish line (as in: Good enough to be used by Hugo).

* Mostly here: https://github.com/bep/imagemeta/pull/9
* But will end up here: https://github.com/gohugoio/hugo/pull/12651

Nothing to test in the above yet, but soon.
