### ISSUE TITLE
Heading Renderer makes it difficult to support custom classes

### ISSUE THREAD

**Issue by macdweller** [gohugoio/hugo#10856]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.111.2-4164f8fef9d71f50ef3962897e319ab6219a1dad+extended linux/amd64 BuildDate=2023-03-05T12:32:20Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes.

### The Issue
The custom renderer for headings (`render-heading.html`) does not clearly support custom classes specified in Markdown (though Goldmark allows this, and the default heading renderer works correctly).  The only available method is not documented anywhere.

### Proposed Solution
The proposed solution is to promote class to a top level variable on the context passed to the Heading Renderer (eg. `.Class`).  Adjusting the documentation accordingly would not go amiss.

### Workaround
The current workaround is to access an undocumented field (`.AttributesHolder.Attributes.class`).

**Comment by jmooring** [comment]
I don't understand. 

https://gohugo.io/templates/render-hooks/#context-passed-to-render-heading

![image](https://user-images.githubusercontent.com/335669/226487455-d254f6b0-7a4f-47b5-8567-b2895d5c3888.png)

**Comment by macdweller** [comment]
And now I'm just plain wondering what I was ~smoking~ reading.  I read what must have been a very similar page, and I could swear that .Attributes was not listed.  That led to a spelunking of the source code, which led to the workaround (which is also needlessly complicated, because I forgot about golang's automatic member promotion).

Yeah.  Apparently I'm either hallucinating, or I somehow got lost in an older version of the documentation.  Or maybe both.

I guess this one can be closed, and I do apologize for the waste of time.  :-)
