### ISSUE TITLE
disableHugoGeneratorInject is not respected by the RSS feed generator

### ISSUE THREAD

**Issue by hnarayanan** [gohugoio/hugo#10871]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.111.3
</pre>

### Does this issue reproduce with the latest release?

Yes

### The issue

There is a configuration flag called `disableHugoGeneratorInject`. This is currently respected by code in `hugo/publisher/publisher.go` to add/remove the generator information as part of the header in created HTML files.

But the flag is not respected in the default template for the RSS generator that unconditionally inserts `<generator>Hugo -- gohugo.io</generator>` into the rendered content.

**Comment by bep** [comment]
For the HTML home page we _inject_ a generator tag in the rendered HTML if it's not already there. There's no concept of _injection_ in the RSS template, it's just there in the template -- if you don't want it, provide your own template.
