### ISSUE TITLE
error: could not expand include path '~/.gitcinclude'

### ISSUE THREAD

**Issue by songxiaosheng** [gohugoio/hugo#10878]
### What version of Hugo are you using (`hugo version`)?

```hugo--0.111.3.big_sur.bottle.tar.gz```

### Does this issue reproduce with the latest release?

when i use hugo command it show the errors for me  as follow:

```text
hugo
go mod download: git init --bare in /var/folders/nr/7s0q_g410k9_q1v26prwqzyh0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/cache/vcs/98f59a39bbbc2d4de9185a32a3d8790111161ae9778e3e5e32a90c95f026ac9b: exit status 128:
	error: could not expand include path '~/.gitcinclude'
	fatal: bad config line 44 in file /usr/local/git/etc/gitconfig
Error: failed to download modules: failed to execute 'go [mod download]': failed to execute binary "go" with args [mod download]: go mod download: git init --bare in /var/folders/nr/7s0q_g410k9_q1v26prwqzyh0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/cache/vcs/98f59a39bbbc2d4de9185a32a3d8790111161ae9778e3e5e32a90c95f026ac9b: exit status 128:
	error: could not expand include path '~/.gitcinclude'
	fatal: bad config line 44 in file /usr/local/git/etc/gitconfig
 *errors.errorString
Total in 24 ms
```

**Comment by jmooring** [comment]
Best guess...

Hugo's [default security policy](https://gohugo.io/about/security-model/#security-policy) prevents access to the `$HOME` (`~`) environment variable.

Update your site config:

```
[security.exec]
osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|HOME)$']
```

**Comment by songxiaosheng** [comment]
> /var/folders/nr/

may be i delelte the dir /var/folders/nr/  but i don't  know how to fix it

**Comment by jmooring** [comment]
@songxiaosheng 

> i don't know how to fix it

Did you try to update your site configuration as I suggested in my previous comment?

**Comment by songxiaosheng** [comment]
> [security.exec]
> osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|HOME)$']

Sorry, I was running on my personal computer Mac and couldn't find the site configuration

**Comment by jmooring** [comment]
1. If you are running an older version of Git, update to the current version (2.4.0) and try again.

2. I am suspicious of the Homebrew installation of either Hugo or Git. If running the current version of Git does not solve your problem, try changing this:

```
[include]
	path = ~/.gitcinclude
```

to:

```
[include]
	path = /home/user/.gitcinclude (or whatever the absolute path is)
```

**Comment by jmooring** [comment]
@songxiaosheng Please confirm if the error was resolved by my previous suggestions.

**Comment by songxiaosheng** [comment]
> @songxiaosheng Please confirm if the error was resolved by my previous suggestions.

May I ask where this configuration is configured

**Comment by songxiaosheng** [comment]
> @songxiaosheng Look at your Git configuration files: local, global, and system.

ok  thanks i will try it

**Comment by jmooring** [comment]
@songxiaosheng Please confirm if the error was resolved by my previous suggestions.

**Comment by jmooring** [comment]
No response from OP. Closing.
