### ISSUE TITLE
Fallback to single tag for non-array tags

### ISSUE THREAD

**Issue by avidseeker** [gohugoio/hugo#10873]
1. Add `tags: sometag` to `content/index.md` frontmatter.
2. Loop over tags in any layout. E.g:
```
{{ with .Params.tags }}
<ol>
{{ range . }}
{{ $href := print (relURL "tags/") (urlize .) }}
<li>{{ . }}</li>
{{ end }}
</ol>
{{ end }}
```
3. Error: range can’t iterate over sometag

Of course, the problem is solved by `tags: ["sometag"]`, but consider having a fallback, since many other static site generators accept non-array tags, and it's more readable.

Hugo v0.111.3

**Comment by jmooring** [comment]
Use the `.GetTerms` method. It doesn’t care whether the front matter value is scalar or an array.

```
{{ range .GetTerms "tags" }}
  <a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a>
{{ end }}
```
