### ISSUE TITLE
HTML generated for Search form action on pages is incorrect.

### ISSUE THREAD

**Issue by nicholasimon** [gohugoio/hugo#10874]
Sorry, to waste your time, I think this error relates to the theme I am using (not Hugo itself) and not sure how to delete the issue. 

The HTML generated for my index page is below (first time user of Hugo) and as a web designer I am able to fix however just wanted to let you know that it is not adding /pages to the path and search is currently not working using Dfuse unless it is manually changed. Maybe I have not set it up correctly however not sure as I have only just started using. Also, not sure could this be due to the theme I am using (not Hugo itself) sorry to waste your time if it is.

So when I generate the site it creates the HTML below

     <form action='/search' id='search-form' class='search-form'>
     <label>

However the search page is not located at the site root so it only works if you manually change the HTML to add the /pages to the path.

      <form action='/pages/search' id='search-form' class='search-form'>
      <label>

### What version of Hugo are you using (`hugo version`)?

<pre>
[v0.111.3](https://github.com/gohugoio/hugo/releases/tag/v0.111.3)

</pre>

### Does this issue reproduce with the latest release?
Is the latest release.

**Comment by jmooring** [comment]
>  I think this error relates to the theme I am using

Yes.
