### ISSUE TITLE
NixPkg missing from gohugo.io website

### ISSUE THREAD

**Issue by Neon-44** [gohugoio/hugo#10886]
Not really a bug, but I just wanted to let You know that there is a NixPkg (i did not package it, someone else did) of Hugo in the NixOS Repos (https://search.nixos.org).
You do not mention this Package on your Website, so I assumed You don't know about its Existence.

I didn't know how else to contact you, so feel free to close this at your discretion.

P.S. Thanks for all your great Work. I am just starting out with this Project, but I already love it :):)

P.P.S. Do You recommend me to use a native Package or a docker Container for someone starting out just now? :)

**Comment by jmooring** [comment]
> I didn't know how else to contact you

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
