### ISSUE TITLE
Build error using 'menus.toml'

### ISSUE THREAD

**Issue by ColonelBlimp** [gohugoio/hugo#10887]
### What version of Hugo are you using (`hugo version`)?

<pre>
0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended windows/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio

OS: Windows 10
</pre>

### Does this issue reproduce with the latest release?
Yes

## Explanation
I have `config/_default/menus.toml` but hugo throws an error when trying to parse the following:

```
   [menu]
   [[menu.main]]
      name = 'Home'
      weight = 10
```
## Error for above
```
ERROR 2023/04/10 16:08:47 menus in site config contain errors
ERROR 2023/04/10 16:08:47 unable to cast maps.Params{"main":[]interface {}{map[string]interface {}{"name":"Home", "weight":10}}} of type maps.Params to []interface{}
ERROR 2023/04/10 16:08:47 logged 2 error(s)
```

## Also tried:
```
[menu]
[menu.main]
    name = 'Home'
    weight = 10
```
## Error for above
```
ERROR 2023/04/10 16:13:41 menus in site config contain errors
ERROR 2023/04/10 16:13:41 unable to cast maps.Params{"main":maps.Params{"name":"Home", "weight":10}} of type maps.Params to []interface{}
Error: Error building site: logged 2 error(s)
```

## Also tried:
```
[[menu]]
[[menu.main]]
    name = 'Home'
    weight = 10
```
## Now, no error from Hugo... BUT... the following code does not work:

```
{{- range site.Menus.main }}
...
{{- end }}
```

## Another direction
If I remove the menu configuration from the `menus.toml` file and add the following to my `hugo.toml` config file, all is good and even the code above works!

```
baseURL = 'http://localhost:1313'
languageCode = 'en-gb'
title = 'Tumbuka Language'

[menu]
[[menu.main]]
    name = 'Home'
    weight = 10
```

I seem to have run into a brickwall with this. I am not sure if this is a bug or a configuration issue. Any help gratefully received.

Many thanks

**Comment by jmooring** [comment]
> config/_default/menus.toml

When using a configuration directory, the configuration key is determined by the file name.  So you are trying to do this:

```
[[menus.menu.main]]
```

Which is, obviously, wrong.

See <https://gohugo.io/getting-started/configuration/#configuration-directory>

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
