### ISSUE TITLE
Bug: recursive module imports incorrect context issue

### ISSUE THREAD

**Issue by sno544** [gohugoio/hugo#10890]
Could someone doublecheck this code for us? It seems that recursive module loading in a class below is not working as expected.

https://github.com/gohugoio/hugo/blob/d01731d53c7c9492cb9666a1223419691a95006c/modules/client.go#L453

Hugo: [v0.111.3](https://github.com/gohugoio/hugo/tree/v0.111.3)
https://github.com/gohugoio/hugo/commit/5d4eb5154e1fed125ca8e9b5a0315c4180dab192

------------------------------------------------------------------------------

Context: 
ProjectA
 -> go.mod (require ProjectB)
 -> hugo.toml (modules ProjectB)

ProjectB
 -> hugo.toml (modules ProjectC)

ProjectC

__________________________________________________________________
Issue: 
ProjectC is not loaded at all. In client.go above in line 453 it's expected that modules from projectB hugo.toml are imported into projectA go.mod file (go get imports correctly). The function listGoMods() is then called but the first line of this function checks projectA's hugo.toml for the import of projectC. This results in a missing module and a failure to start service.

It is expected that projectA hugo.toml would never know about import in projectB hugo.toml. Based on this in client.go: 453 it appears the wrong hugo module config is used. It should be hugo config from projectB.

func (c *Client) listGoMods() (goModules, error) {
    if c.GoModulesFilename == "" || !c.moduleConfig.hasModuleImport() {
        return nil, nil
    }
...
}

Thanks!

**Comment by bep** [comment]
```
ProjectA
-> go.mod (require ProjectB)
-> hugo.toml (modules ProjectB)

ProjectB
-> hugo.toml (modules ProjectC)

ProjectC
```

The above structure is very common and I have not seen any of the problems you mention. If you can link to a simple and failing Hugo project, this would be easier to discuss.

**Comment by jmooring** [comment]
@sno544 We can reopen this if you provide a reproducible example, but closing for now.
