### ISSUE TITLE
default GitHub Actions CI does not work

### ISSUE THREAD

**Issue by amtoine** [gohugoio/hugo#10898]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.111.3+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
i'm not sure how to test that in a CI :thinking: 

## my issue
i have my personal website `hugo`-based repo [here](https://github.com/amtoine/amtoine.github.io) :yum: 
i wanted to deploy the website automatically with a *GitHub Action*, read the [documentation](https://gohugo.io/hosting-and-deployment/hosting-on-github/) and did the following
- activate "Build and deployment" in the settings of the repo and set it to "GitHub Actions"
- use the default CI proposed below and store it in [`.github/workflows/hugo.yml`](https://github.com/amtoine/amtoine.github.io/blob/main/.github/workflows/hugo.yml)
- let the CI run on every push to `main`

but now i get the [following error :x:](https://github.com/amtoine/amtoine.github.io/actions/runs/4713589936/jobs/8359377832)

**am i doing something wrong?** :open_mouth: 

cheers :wave: :yum:

**Comment by jmooring** [comment]
This is not a bug.

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by amtoine** [comment]
> This is not a bug.
> 
> Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
>
of course, sorry to bother you here :relieved:

**Comment by amtoine** [comment]
and it was really dumb, i just had to mark the pages as `draft: false` and it works perfectly now :yum:
