### ISSUE TITLE
Full Commit Message in .GitInfo

### ISSUE THREAD

**Issue by marchof** [gohugoio/hugo#10905]
**Current Behavior**

The `.GitInfo` object hat a `Subject` field which contains the first line of the commit message

**Proposed Bahavior**

Add another field `Message` with the full commit message.

**Reasoning**

We implemented a content management system based on Git and Hugo. For the meta information it would be useful to present the full commit message, e.g. as a tooltip on top of the subject.

**Comment by bep** [comment]
Yea, we could do that.

This would have to be added to this struct: https://github.com/bep/gitmap/blob/master/gitmap.go#L44

**Comment by marchof** [comment]
@bep Thanks for the quick response and for providing this wonderful piece of software! This feature is not a blocker at all for us.
