### ISSUE TITLE
The deleted post reappears

### ISSUE THREAD

**Issue by shwezhu** [gohugoio/hugo#10908]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 
0.111.3
</pre>

### Does this issue reproduce with the latest release?
yes

I deleted a `md` file under `blog/content/posts/`, when I use `hugo -D`, the corresponding `html` file still exists in `blog/public/posts/`, 

And I tried to delete the `public` folder, and run `hugo -D`, then, the deleted reappeared in my `blog/content/posts/`.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
