### ISSUE TITLE
Allow disableHugoGeneratorInject property to be modified in themes.

### ISSUE THREAD

**Issue by astralchan** [gohugoio/hugo#10910]
Related: Issue [2850](https://github.com/gohugoio/hugo/issues/2850)

# Issue

If I want to disable the meta generator tag on my hugo site, I - and by extension everyone that uses my theme - needs to edit their site's `config.toml` to include: `disableHugoGeneratorInject = true`.

I would like the ability for the theme to disable this.

# Proposal

Allow for the `disableHugoGeneratorInject` property to be changed in a hugo theme's config / theme files. Such that, any site using this theme, will already have it disabled and not have to think about it.

If they want the generator tag, the value of `disableHugoGeneratorInject` in the site's `config.toml` will override the value of the theme's value.

# Reason

I understand the sentiment of (quote from issue [2850](https://github.com/gohugoio/hugo/issues/2850)):

> We spend many, many, many hours implementing this great and FREE piece of software. It is called open source. I think it is very, very, very little to ask from the users in return to include a Hugo generator meta tag on the home page (i.e. only 1 page).

Hugo is an awesome static site build system. If you truly mean "FREE" as in "freedom," I believe this includes the freedom to choose, anything less is restriction.

**Comment by jmooring** [comment]
No.
