### ISSUE TITLE
Error: site config value "en" for defaultContentLanguage does not match any language definition

### ISSUE THREAD

**Issue by Jason2013** [gohugoio/hugo#10917]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended windows/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio

</pre>

### Does this issue reproduce with the latest release?

Yes

[multilangual_bug.zip](https://github.com/gohugoio/hugo/files/11342708/multilangual_bug.zip)
[multilangual_fixed.zip](https://github.com/gohugoio/hugo/files/11342710/multilangual_fixed.zip)

I want to create a site for Russian and Chinese language versions and put each of them in separate folder.
I want to set the Russian language as the default content language.
I don't need the English language version.

I need the following configuration values:

```
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true
```

However, if I add the following configuration:

```
[markup]
[markup.goldmark.renderer]
  unsafe = false
```

and try to start the hugo server locally and the following error message occurs:

```
$ hugo server -p 1314
Error: site config value "en" for defaultContentLanguage does not match any language definition
```

The workaroud is to add an unnecessary English language version and the server can start. But the following configuration values doesn't take effect any more.

```
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true
```

It looks like that the `defaultContentLanguage` is always `en` and `defaultContentLanguageInSubdir` is always `false`.

I think it is a bug.

**Comment by Jason2013** [comment]
This is the workaround version:
[multilangual_workaround.zip](https://github.com/gohugoio/hugo/files/11342930/multilangual_workaround.zip)

I hope the [multilangual_bug.zip](https://github.com/gohugoio/hugo/files/11342708/multilangual_bug.zip) can work without any modification.

**Comment by jmooring** [comment]
In your site configuration, you have placed this:

```
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true
```

within the `markup.goldmark.renderer` table. Those key/value pairs need to be in the root table.

In the future, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
