### ISSUE TITLE
Allow config.toml to set preferred port number, no build lock, gc, and disable fast render

### ISSUE THREAD

**Issue by hollowaykeanho** [gohugoio/hugo#10911]
## Why
Eliminate an external scripting dependency during module distributions. Right now, `hugo server` command requires an external script to unify some critical settings.

Issue not seen for `hugo` command to build the repo.

## Reference
Discussion: https://discourse.gohugo.io/t/merging-hugo-servers-cmd-arguments-into-config-toml/44033

**Comment by hollowaykeanho** [comment]
Update related to https://github.com/ZORALab/Hestia/issues/93

We had decided to keep the `server.cmd` server script mainly because of our another memory related issue here: https://github.com/ZORALab/Hestia/issues/106

The script implementation helps isolate the hugo upstream and us at the downstream which is useful for safe distribution and debugging collaborations between each side.

The design proposal is up to you guys now. No pressure.

**Comment by broughtupsy** [comment]
The 

> ZORALab/Hestia

The project has been archived FYI!

**Comment by hollowaykeanho** [comment]
Hi Hestia developer here. Please go ahead to close the ticket if the feature is at least concern.

As stated in Hugo forum, we won't be using hugo in the future due to Go template limitations (a lot of data processing).

Otherwise, can I close this? Thanks in adv.
