### ISSUE TITLE
Rename or delete of page does not update sets of child pages correctly in "server" mode

### ISSUE THREAD

**Issue by jernst** [gohugoio/hugo#10918]
`hugo v0.111.3+extended`. Long-standing problem.

I have an `_index.md` page that paginates over .RegularPages. Initially, it has three child pages `a.md`, `b.md` and `c.md` and the parent list page shows:

* `a`
* `b`
* `c`

If I now:

* delete `b.md` and
* rename `c.md` to `d.md`

the enumeration in the parent list page changes to

* `a`
* `b`
* `c`
* `d`

while it should really be:

* `a`
* `d`

To get it right, a restart of `hugo server` is required.

**Comment by jernst** [comment]
... and the deleted or renamed pages can still be accessed at the old URL from the browser.

**Comment by jmooring** [comment]
I can reproduce this:

> deleted or renamed pages can still be accessed at the old URL

I cannot reproduce this:

> the enumeration in the parent list page changes to `a b c d`

v0.111.3 linux/amd64

**Comment by stackkrocket** [comment]
> `hugo v0.111.3+extended`. Long-standing problem.
> 
> I have an `_index.md` page that paginates over .RegularPages. Initially, it has three child pages `a.md`, `b.md` and `c.md` and the parent list page shows:
> 
> * `a`
> * `b`
> * `c`
> 
> If I now:
> 
> * delete `b.md` and
> * rename `c.md` to `d.md`
> 
> the enumeration in the parent list page changes to
> 
> * `a`
> * `b`
> * `c`
> * `d`
> 
> while it should really be:
> 
> * `a`
> * `d`
> 
> To get it right, a restart of `hugo server` is required.

Steps to reproduce this?
