### ISSUE TITLE
"hugo new site . ; hugo new theme" results in 404

### ISSUE THREAD

**Issue by flypenguin** [gohugoio/hugo#10923]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.111.3+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

yes

### bug description

i am following a couple of tutorials about building hugo themes, and what i think _should_ work ... does not:

```bash
hugo new site .
hugo new theme test-theme
echo 'theme = "test-theme"' >> config.toml
echo "about that ... " >> content/about.md
echo "indexed" >> content/index.md
hugo serve
```

... results in a "404 page not found" page. in my world view, that _really_ should print a "hello world" or sth ... .

why do i consider this a bug? cause i am confused, and i think to get up and running this should yield a working example, even if it's only a single line of "hello" – or _at least_ some docs about how to proceed further.

**Comment by flypenguin** [comment]
by chance i found out that if i do `echo test >> themes/test-theme/layouts/index.html` i get something displayed.

now, digging through the [home page lookup order](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-home-page) i am even more conviced this might be a bug. if i get this correctly, it _should_ find the templates ...

* `layouts/_default/list.html` (priority 12)
* `layouts/_default/baseof.html` (priority 16)

... and display something – even if it's just a white page.

again - if i get this correctly, which i am not so sure about right now.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
