### ISSUE TITLE
hogo convert destroy the original sequence structure

### ISSUE THREAD

**Issue by ZhangChengLin** [gohugoio/hugo#10937]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo version
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended windows/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio

</pre>

/### Does this issue reproduce with the latest release?

- [x] Yes!

https://gohugo.io/commands/hugo_convert/
https://gohugo.io/commands/hugo_convert_tojson/
https://gohugo.io/commands/hugo_convert_totoml/
https://gohugo.io/commands/hugo_convert_toyaml/

These functions will destroy the original sequence structure, and there seems to be no option not to destroy the structure.
For example, when using the yaml format, sometimes developers use spaces to separate lines with different functions.
I believe that other formats, such as json, are not designed to be sorted alphabetically, which is not conducive to clustering and classification.

**Comment by ZhangChengLin** [comment]
It should be explained that the hugo-bin of npm is used.



The number after convert is not accurate, it is more than the actual number of files changed, 81 files were actually changed, but the result in the command line is 88.

**Comment by bep** [comment]
I'll note this as a bug, but it's in the "will most likely not be fixed" category, as:

* We use upstream libraries to convert to/from JSON etc. These libraries all have their own semantics as to ordering of input.
* I don't see how the order of the keys in front matter matters (other than the visual thing) -- but that is certainly a side effect of "hugo convert"

**Comment by ZhangChengLin** [comment]
The conversion format I thought should just be the conversion format, and the order after conversion should remain the same.
Wait until the need to change before doing additional processing.
Front Matter in yaml format allows blank lines, and json also allows blank lines, which makes these options easy to classify visually, and it is easy to understand that there are some related options between the two blank lines later.
Of course, if it is generally set, the upstream does not know where it is, and it may not be necessary to look at it manually in practice.
After all, this is a batch operation function.
I just came into contact with hugo not long ago, and I haven't used it in the go environment, so maybe the direction of the idea is not correct, I just put it up for reference only.

**Comment by bep** [comment]
>The conversion format I thought should just be the conversion format, and the order after conversion should remain the same.

I agree with you on principle -- but I'm not prepared to spend a million hours creating a JSON and TOML and Yaml converter that will handle this.
