### ISSUE TITLE
The linux extended version is dynamically linked, so it's not standalone.

### ISSUE THREAD

**Issue by jfp42** [gohugoio/hugo#10938]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ 0.111.3
</pre>

### Does this issue reproduce with the latest release?
yes, you cannot use the hugo_extended in an alpine container.

non-extended: hugo_0.111.3_linux-amd64.tar.gz
Hugo: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=lZEHUD-JZKujGOfRo1q7/a4giytfCdTz66ko7ekdV/eu931OlFUqqq7mPIEiQX/uf1bQLD_zJu_VO-QFNmW, stripped

extended: hugo_extended_0.111.3_linux-amd64.tar.gz
Hugo: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, Go BuildID=nYJLQ3_Bnb7NlaDK2Gzn/0RZmCxkxIF0N7Jt1irbJ/tkhTBDqY_2aYFzqJAp79/Lr7YilAbwfKtM5m0EITZ, BuildID[sha1]=5301d57829f1af0f0f3eb76abdca5464892103b1, stripped

**Comment by bep** [comment]
This has been discussed before, so I will not spend time repeating the motivation/reasoning. More info at #10839 etc.
