### ISSUE TITLE
Remove the .PageRef template variable

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10940]
I've seen this used, erroneously, in several forum topics, and I think at least one theme. It just returns the `pageRef` menu property, which negates the reason to define the `pageRef` property in a menu entry.

Site and theme authors should be using `.URL` in their menu templates.

Perhaps there's a reason to use this in a menu template, but I can't think of one.

I removed `.PageRef` template variable from the documentation a while ago.

**Comment by bep** [comment]
This will clearer when the branch I'm working on gets merge, but this is also how it should behave today:

If `pageRef` is set and it resolves to an existing page (using the same semantics as `site.GetPage`) then:

* menuItem.Page will be set.
* menuItem.URL will return `.Page.Permalink`

The problem today (and which I'm about to fix) is that we mix configuration (where `pageRef` belongs) and the end user API (where the `pageRef` isn't needed).

I'm closing this as I will fix this in a bigger context.
