### ISSUE TITLE
Use uber-go/automaxprocs to default GOMAXPROCS aware of Linux CPU Quotas

### ISSUE THREAD

**Issue by BenTheElder** [gohugoio/hugo#10950]
See:
- https://github.com/golang/go/issues/33803
- https://github.com/kubernetes/website/pull/41142

Basically: When using hugo in a container with limited CPU quota, hugo can encounter CPU throttling issues because GOMAXPROCS is defaulted to the underlying hardware core count instead of the allocated CPU limits in the container.

There's something of a defacto standard library for defaulting this in a CPU limit aware way in https://github.com/uber-go/automaxprocs, at least until https://github.com/golang/go/issues/33803 is solved.

Users would still be able to override by setting `GOMAXPROCS` env, and this is a fairly small MIT licensed dependency.

**Comment by bep** [comment]
A note from the sideline, Hugo bases its parallelism on

1. HUGO_NUMWORKERMULTIPLIER env var if set
2. `runtime.NumCPU()`

So, setting `HUGO_NUMWORKERMULTIPLIER=1` (or something) could be a workaround.

**Comment by BenTheElder** [comment]
Ack, thanks!

We're getting good results setting GOMAXPROCS=1 in netlify for Kubernetes (it appears free netlify has ~1 core allocated?)

> runtime.NumCPU()

I think it might? be better to base it on `runtime.GOMAXPROCS(0)` (<1 does not set it and only returns the current value).

Even without that though, AIUI the setting GOMAXPROCS will let go internally do better at scheduling within the CPU quota. 

I filed a sample PR in https://github.com/gohugoio/hugo/pull/10951 for the latter, we've seen automaxprocs fix performance issues with containerized Go more generally, e.g. in Kubernetes's CI unit tests.

**Comment by bep** [comment]
I needed to revert this; a new patch that makes the tests pass is welcomed, but I have not time to investigate this at the moment.

**Comment by BenTheElder** [comment]
I'll look into that 👀

Thank you for all your work on hugo!

**Comment by bep** [comment]
Great; Ideally I would want _no output_ from that library.

**Comment by BenTheElder** [comment]
OK, sorry about that, the root automaxprocs just [calls `maxprocs.Set(macprocs.Logger(log.Printf))`](https://github.com/uber-go/automaxprocs/blob/f6364fccf14450d89bc0bf13c2aa1c05d9f7aefd/automaxprocs.go#L32), if we call `maxprocs.Set()` instead there will be no logging this time (per the godocs, checking the implementation, and local testing).

`go test ./...`  passes with the updated patch, I should've thought to check before filing the last PR.

Filed https://github.com/gohugoio/hugo/pull/10952
