### ISSUE TITLE
[Proposal] Add a variable to describe site's content directory

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#10969]
Hi, I use the `Language.ContentDir` to get the relative path of pages to the site root, which is useful for generating the links to view/edit the pages. But the _internal_ use variable was removed on this [commit](https://github.com/gohugoio/hugo/commit/241b21b0fd34d91fccb2ce69874110dceae6f926#diff-c7cf0d263e118b30aba8670e149a434527d8913c7c1d9ce26fc1934044428651L66), is there a workaround to get the relative path of the pages? Or is it possible to expose a function or variable to achieve this?

Thanks.

**Comment by bep** [comment]
I suggest you do something ala:

```
{{ with .File }}
{{ $relativeToContentDir := .Path }}
{{ end }}
```

Which isn't the same as what you do today as you would need to know that it's inside `content`, but the thing is, with a composite file system (multiple content dirs), there's no golden way of doing this without knowing more ...

Note that if you're talking about links to the files on disk (and not GitHub), you can do:

```
{{ with .File }}
{{ $absoluteFilename := .Filename }}
{{ end }}
```

**Comment by bep** [comment]
We can certainly add "something" to simplify the above, but I don't see what.

**Comment by razonyang** [comment]
Thanks for your suggestions, I want to generate links about the view/edit URLs of GitHub/GitLab, but I didn't figure out a solution.
The `File.Path` isn't enough to describe the path to the site root when `ContentDir` is set.
Is that possible to add a variable on `File` that return the path that includes the `content` folder?
Or can I access the site root path so that I can manually transform the `File.Filename` and get the path I want.

**Comment by jmooring** [comment]
@razonyang This [forum topic](https://discourse.gohugo.io/t/path-to-content-file-from-project-root/44262) might be helpful, specifically:

```text
{{ strings.TrimPrefix (os.Getenv "PWD") .File.Filename }}
```

For this to work, Hugo must be run within the project directory (i.e., cannot use `hugo -s somedir`).

**Comment by jmooring** [comment]
This is what I really really want:

```
{{ strings.TrimPrefix hugo.WorkingDir .File.Filename }}
```

**Comment by razonyang** [comment]
@jmooring Thanks a lot, will try later.

**Comment by jmooring** [comment]
`hugo.WorkingDir ` is not implemented---it is what I want.

**Comment by bep** [comment]
Sure, we can do that, but note that

```
{{ strings.TrimPrefix hugo.WorkingDir .File.Filename }}
```

Will not work for files in themes/modules.
