### ISSUE TITLE
CGO_ENABLED error

### ISSUE THREAD

**Issue by MrHobbie** [gohugoio/hugo#10992]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
not installed yet
</pre>

### Does this issue reproduce with the latest release?
yes

I executed the following:
`CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest`

`# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH`

**Comment by jmooring** [comment]
This is not a bug. If you want to build the extended version from source, you need to install the GCC compiler.

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
