### ISSUE TITLE
.Site.IsServer set as true for hugo v0.112.1 for the main command

### ISSUE THREAD

**Issue by henvic** [gohugoio/hugo#11006]
Hello, it seems that .Site.IsServer is returning true for generating pages using the main command.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.112.1-7c90c19d282cad63fe15220fcfb7936767b70623 darwin/amd64 BuildDate=2023-05-23T17:26:16Z
</pre>

### Does this issue reproduce with the latest release?
Yes.

**Comment by jmooring** [comment]
Confirmed.

**Comment by jmooring** [comment]
This seems to be related:
<https://discourse.gohugo.io/t/44506/3>
