### ISSUE TITLE
Twitter card image is not working

### ISSUE THREAD

**Issue by khanhtc1202** [gohugoio/hugo#11007]
The image for Twitter card is not working even it's generated as expected.
```
<meta name="twitter:image" content="https://pipecd.dev/images/pipecd-cncf-sandbox.png">
```

I checked and confirmed the visibility of the image used for the Twitter card.

I also checked other links from GitHub (which Twitter can show the image from the Twitter card correctly), and they use `twitter:image:src` instead of `twitter:image` for the meta name property. There is no official place I can find which should be used, but I guess we should change that value.

![Screen Shot 2023-05-24 at 8 23 14](https://github.com/gohugoio/hugo/assets/32532742/f4447769-4928-4d99-bf97-ab88289f6b4d)

ref: https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html#L14

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.98.0+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
The [Twitter developer docs](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup) do not contain any references to `twitter:image:src`.

**Comment by jmooring** [comment]
And the example you posted seems to work fine when compositing a tweet:

![image](https://github.com/gohugoio/hugo/assets/335669/5d4e6760-de78-4671-a7c3-a99464bd8954)

By you also have an `og:image` meta element that may take precedence.

**Comment by khanhtc1202** [comment]
Thanks @jmooring for quick response!
Yes, that makes me confused while GitHub uses that `twitter:image:src`, and why does it work instead of `twitter:image`.

This is the [link](https://pipecd.dev/blog/2023/05/19/cncf-sandbox-admission/) I want to use the twitter card image. And you can see that both `org:image` and `twitter:image` are set to this picture: https://pipecd.dev/images/pipecd-cncf-sandbox.png but both are not working

![Screen Shot 2023-05-24 at 9 05 29](https://github.com/gohugoio/hugo/assets/32532742/828bc690-eef7-4600-9a85-a3c4a7bbf5f5)

**Comment by jmooring** [comment]
This also works fine:
<https://pipecd.dev/blog/2020/10/06/announcing-pipecd/>

Running exiftool against some of your card images shows significant differences. Try replacing the image with something else.

Or, perhaps Twitter is caching something.

Please take further discussion to the forum (https://discourse.gohugo.io/). We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
