### ISSUE TITLE
Not clear on how to fix deprecation of custom language parameters

### ISSUE THREAD

**Issue by timmyreal** [gohugoio/hugo#11008]
I've read the change log and I'm still not clear what I'm supposed to do. Here's a section of the error that keeps getting thrown up:
<img width="595" alt="Screenshot 2023-05-23 at 7 34 04 PM" src="https://github.com/gohugoio/hugo/assets/82277734/26b6bcca-5451-4e62-b24f-ed547dfba822">

I understand that I'm supposed to put [languages.en.params] above certain parameters, but it doesn't say which file. It can't be config.toml because none of the parameters throwing errors above (e.g. languages.en.dateformat, languages.en.rtl) are in that file:
<img width="527" alt="Screenshot 2023-05-23 at 7 34 30 PM" src="https://github.com/gohugoio/hugo/assets/82277734/c02babaa-dbff-4d5a-a556-06a4f8ae2a85">

I've also searched within every file in the directory for those parameters but haven't found anything.

I'm sure there's something incredibly simple I can do to fix this, but either the documentation is too sparse or the error messages are not very helpful. I'm a bit flummoxed, so any help at all would be appreciated. Thanks.

**Comment by jmooring** [comment]
<https://github.com/jpanther/congo/blob/dev/config/_default/languages.en.toml#LL3C1-L6C12>

Move `displayName`, `isoCode`, `rtl`, and `dateFormat` under `[params]`.

If you need further assistance, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
