### ISSUE TITLE
Running hugo without config file should throw error

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11019]
Change into an empty directory...

#### v0.111.3

```text
$ hugo

Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
       Run `hugo help new` for details.
```

It also creates a `.hugo_build.lock` file.

#### v0.112.3

```text
$ hugo

hugo v0.112.3-ba6f74e40420d76f15fc8c2358be90f7aca98e0e+extended linux/amd64 BuildDate=2023-05-24T14:42:50Z VendorInfo=gohugoio
WARN 2023/05/24 17:37:09 found no layout file for "html" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2023/05/24 17:37:09 found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2023/05/24 17:37:09 found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

It also generates the following:

```text
./
├── public/
│   ├── categories/
│   │   └── index.xml
│   ├── tags/
│   │   └── index.xml
│   ├── index.xml
│   └── sitemap.xml
├── resources/
│   └── _gen/
│       ├── assets/
│       └── images/
└── .hugo_build.lock

```

**Comment by bep** [comment]
Thanks. I'm going to let these relatively minor things sit for a few days and just fix them all in one patch release.

This release was bound to create some waves/bugs with the massive amount of code changes. I probably got a little tired at the end there and just wanted to get it out the door. But after fixing these recent bugs in the `commands` package of Hugo I can say that it has become a pleasure to code in (esp. with the new `testscripts` setup). The previous version I think I was the only one who dared to make changes to ...
