### ISSUE TITLE
Autocomplete with v0.112.0 and later missing short flags

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11016]
Feel free to close this immediately if this is intentional.

```
$ hugo --
--baseURL               (hostname (and path) to the root, e.g. https://spf13.com/)
--buildDrafts           (include content marked as draft)
--buildExpired          (include expired content)
--buildFuture           (include content with publishdate in the future)
--cacheDir              (filesystem path to cache directory. Defaults: $TMPDIR/hugo_cache/)
--cleanDestinationDir   (remove files from destination not found in static directories)
```

With v0.111.3 and earlier the autocomplete output also contained the short flags (e.g., `-D`).

The man pages produced with v0.112.0 and later include the short flags.

I actually prefer the new format; I find it easier to read.

**Comment by bep** [comment]
So, I also like the new format, but how are folks going to know about the short flags.

Also, the problems with the historical short flags is that they have been sprinkled about a little liberally. In my head, short flags should be used for things you frequently use, not for stuff like -D for --buildDrafts.

I will think a little.

**Comment by bep** [comment]
OK, since the shorthand flags is documented elsewhere, and it is much easier to read in the console, I would say that we keep it as it is.
