### ISSUE TITLE
The `-t` / `--theme` flags were removed from `hugo new`

### ISSUE THREAD

**Issue by yihui** [gohugoio/hugo#11018]
The `-t` / `--theme` flags were removed from `hugo new` (also absent in `hugo new content`): https://github.com/gohugoio/hugoDocs/commit/fb3027dafa391d48922240fc4359cbc4ad1cfdd5#diff-9b75f7a964edc681f1e213d44f1ec7a3d4f5f1678c25f45c78cb238cb2ca052cL62 Was that intentional? If yes, how to create new content using an archetype (`--kind`) in a specific theme? Thanks!

_Originally posted by @yihui in https://github.com/gohugoio/hugo/issues/11015#issuecomment-1561952794_

```sh
$ hugo version
hugo v0.112.3-ba6f74e40420d76f15fc8c2358be90f7aca98e0e+extended darwin/amd64 BuildDate=2023-05-24T14:42:50Z VendorInfo=gohugoio
```

```sh
$ hugo new post/foo.md --theme hugo-xmin
Error: command error: unknown flag: --theme
```

**Comment by bep** [comment]
This is a bug, and I apologise. This was a massive Hugo upgrade on the technical side that we needed to do sooner rather than later, and I guess we (or at least I) was a little tired of it at the end and just wanted to get it out.

**Comment by jmooring** [comment]
@yihui

> how to create new content using an archetype

```
hugo new content --theme mytheme posts/post-1.md
hugo new content -t mytheme posts/post-1.md
```

The `--theme / -t` flag has no effect if you have an archetype in your project folder (as expected, same behavior as < v0.112.0).
