### ISSUE TITLE
The flag `-f` in `hugo new site -f` no longer works

### ISSUE THREAD

**Issue by yihui** [gohugoio/hugo#11015]
The command

```sh
hugo new site test -f yaml
```

throws an error:

```
command error: unknown shorthand flag: 'f' in -f
```

The `--format` flag still works, though. Documentation: https://gohugo.io/commands/hugo_new_site/

### What version of Hugo are you using (`hugo version`)?

```sh
$ hugo version
hugo v0.112.0-0a95d6704a8ac8d41cc5ca8fffaad8c5c7a3754a+extended darwin/amd64 BuildDate=2023-05-23T08:14:20Z VendorInfo=gohugoio
```

### Does this issue reproduce with the latest release?

Yes. The problem can be reproduced with Hugo version >= 0.112.0.

It might be caused by 85b13c105a202baf80796a5eab144d3f74a4cc42.

**Comment by bep** [comment]
The `--format` is now a global flag, and because of that we needed to remove the shorthand (there was a conflict with another flag with the same shorthand).

**Comment by yihui** [comment]
Okay, thanks for the explanation! It will be nice to mention it in the release notes and update the documentation accordingly.

**Comment by yihui** [comment]
@jmooring Thanks!

@bep On a possibly related note, the `-t` / `--theme` flags were removed from `hugo new` (also absent in `hugo new content`): https://github.com/gohugoio/hugoDocs/commit/fb3027dafa391d48922240fc4359cbc4ad1cfdd5#diff-9b75f7a964edc681f1e213d44f1ec7a3d4f5f1678c25f45c78cb238cb2ca052cL62 Was that intentional?

**Comment by jmooring** [comment]
@yihui Please create a new issue; this one is closed.

**Comment by yihui** [comment]
@jmooring Sure: #11018
