### ISSUE TITLE
The development config directory is read when running `hugo`

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11013]
Problem exists in v0.112.0, v0.112.1, v0.112.2.

```text
config/
├── _default/
│   └── config.toml
└── development/
    └── module.toml  <-- BUG: this is read when running `hugo`
```
Minimal example:

```text
git clone --single-branch -b hugo-forum-topic-44506 https://github.com/jmooring/hugo-testing hugo-forum-topic-44506
cd hugo-forum-topic-44506
hugo
```

> Error: failed to load modules: module "foo" not found

Then run:

```text
hugo -e production
```

No problems.

Reference: <https://discourse.gohugo.io/t/44506/3>

---

This could expose sensitive/internal content.

config/development/module.toml

```text
[[mounts]]
source = 'content'
target = 'content'

[[mounts]]
source = 'hidden'
target = 'content'
```

**Comment by jloh** [comment]
I can replicate this on `v0.112.2` as well but my development config is called `testing`:

```
❯ tree config/
config/
├── testing
│   └── config.yaml <-- this file is being loaded
└── development
    └── config.yaml

3 directories, 2 files
```

In `config/testing/config.yaml` I set the `baseurl` to be something different and its being updated:

```
❯ hugo config | egrep '(envi|baseurl)'
baseurl = 'https://testground.example.com'
environment = 'production'
```

vs

```
❯ hugo config -e production | egrep '(envi|baseurl)'
baseurl = 'https://example.com'
environment = 'production'
```

I'm running OSX locally but discovered the bug in Netlify's build env.
