### ISSUE TITLE
v0.112: unannounced change in behavior: media type not found

### ISSUE THREAD

**Issue by stefanv** [gohugoio/hugo#11021]
This is a change we noticed between v0.111 and v0.112.

```
Error: failed to create config from result: failed to decode "outputFormats": failed to decode output format configuration: error decoding '': media type "application/atom" not found
```

The problem can be reproduced by compiling https://github.com/scientific-python/blog.scientific-python.org/ (remember to `git submodule update --init`).

It looks like we may need to add the allowable mimetypes to the config, but either way I don't see the change announced in the release notes.

**Comment by jmooring** [comment]
I didn't see a media type definition for `application/atom` in your site configuration.

When I add this to your site configuration...

```
mediaTypes:
  application/atom:
    suffixes:
    - xml
```

...the site builds without errors. Please verify.

And I don't see `application/atom` on the  list of built-in media types:
<https://gohugo.io/templates/output-formats/#media-types>

So I'm not sure why it worked in v0.111.3.
```

**Comment by bep** [comment]
>Error: failed to create config from result: failed to decode "outputFormats": failed to decode output format configuration: error decoding '': 

The error message above looks odd (the empty string), but I don't see how this could have ever worked. And if it did, you really want to have a defined media type to each of your output format, so I don't think we would want to revert to some buggy undefined behaviour.

But I will have a look at the error message.

**Comment by stefanv** [comment]
Thanks, the patch suggested by @jmooring works.

@kaushalmodi Perhaps something that should be documented on [hugo-atom-feed](https://github.com/kaushalmodi/hugo-atom-feed).
