### ISSUE TITLE
Multilingual multihost issues with Hugo v0.112.3

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [gohugoio/hugo#11020]
### What version of Hugo are you using (`hugo version`)?

`v0.112.3`.

### Does this issue reproduce with the latest release?
Yes.

Hi,

I’m facing some issues with [my site](https://github.com/rodrigoalcarazdelaosa/fisiquimicamente) since updating to Hugo v0.112.3, specifically with images in my `static` folder. The [live version](https://physichemically.com/), built with Hugo v0.111.3, has no issues at all. But, if you build my website with v0.112.3, you’ll notice that some images, specifically the ones stored in `static` and accessed using an `<img>` element, are missing (as no found, as if they’re weren’t there, example here: https://github.com/rodrigoalcarazdelaosa/fisiquimicamente/blob/main/content/en/privacy.md).

My language selector in the menu bar also stopped working.

Can someone tell what do I need to change?

Thank you very much,
Rodrigo

**Comment by jmooring** [comment]
See comments on the related forum topic:

- <https://discourse.gohugo.io/t/multilingual-multihost-issues-with-hugo-v0-112-3/44553/5>
- <https://discourse.gohugo.io/t/multilingual-multihost-issues-with-hugo-v0-112-3/44553/6>

Missing images: cannot reproduce
Language switcher: resolved by adding language weights

With v0.111.3 the language switcher seems to work without language weights, but in my mind that's an invalid configuration.

**Comment by rodrigoalcarazdelaosa** [comment]
The _missing images_ can't be reproduced on a freshly cloned repo and the language switcher indeed works fine when adding weights. Closing. Thanks!
