### ISSUE TITLE
Error install with go

### ISSUE THREAD

**Issue by tanducmai** [gohugoio/hugo#11036]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.112.4
</pre>

### Does this issue reproduce with the latest release?
Yes, I install Hugo a few days ago and it still works normally.
The command was `go install github.com/gohugoio/hugo@latest`.

**Comment by jmooring** [comment]
I am unable to reproduce the problem.

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by tanducmai** [comment]
I received the following issue message:

```text
# github.com/gohugoio/hugo/common/types
go/pkg/mod/github.com/gohugoio/hugo@v0.112.4/common/types/types.go:96:30: undefined: atomic.Int64
# github.com/gohugoio/hugo/common/loggers
go/pkg/mod/github.com/gohugoio/hugo@v0.112.4/common/loggers/loggers.go:35:28: undefined: atomic.Bool
```

**Comment by jmooring** [comment]
Please type `hugo env` and paste the results.

**Comment by jmooring** [comment]
I'm pretty sure you are using an older version of Go. See:
<https://gohugo.io/installation/linux/#build-from-source>

Specifically, item 2.

![image](https://github.com/gohugoio/hugo/assets/335669/09bdd334-6379-4a43-87e8-6863f006bc39)

**Comment by bep** [comment]
@jmooring The 1.18 needs to be bumped to 1.19 -- I thinkg atomic.Bool was added in Go 1.19.

**Comment by jmooring** [comment]
Updated docs and my previous comment.
