### ISSUE TITLE
No Permalinks

### ISSUE THREAD

**Issue by hbiede** [gohugoio/hugo#11033]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.112.3+extended darwin/arm64 BuildDate=unknown
</pre>

## Bug

`.Permalink` is now generating an empty string

### Example

```html
{{ range .Data.Terms.Alphabetical }}
  <h4>{{ .Name }} ({{ .WeightedPages.Count }})</h4>
  <ul>
    {{ range .WeightedPages.Pages }}
      <li><a href="{{ .Permalink }}">{{ .LinkTitle }}</a></li>
    {{ end }}
  </ul>
{{ end }}
```
Above generated below:
```html
<h4>Example Tag (1)</h4>
<ul>
  <li><a href="">Example Name</a></li>
</ul>
```

**Comment by jmooring** [comment]
Unable to reproduce. Try it:

```text
git clone --single-branch -b @@BRANCH@@ @@REPOSITORY@@ @@BRANCH@@
cd @@BRANCH@@
hugo server
```

Then visit `http://localhost:1313/categories/`

**Comment by hbiede** [comment]
This is happening fully reproducibly for me in my portfolio project:
```
git clone git@github.com:hbiede/portfolio.git hugo-github-issue-11033
cd hugo-github-issue-11033
hugo
```
Check the content of `public/tags/index.html`: All links will have `<a href="">`

**Comment by jmooring** [comment]
You have no output formats for .Kind "page"

```json
  "outputs": {
    "home": [
      "HTML",
      "RSS",
      "MANIFEST"
    ],
    "page": [],   '<----------------- PROBLEM
    "section": ["HTML", "RSS"],
    "term": ["HTML"],
    "taxonomy": ["HTML", "RSS"]
  },
```

**Comment by hbiede** [comment]
Ahh. Not sure how that was working on previous versions, but that fixed it. I appreciate the help.
