### ISSUE TITLE
GitHub Action do not recognize hugo.toml

### ISSUE THREAD

**Issue by dudung** [gohugoio/hugo#11035]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.112.3-ba6f74e40420d76f15fc8c2358be90f7aca98e0e+extended windows/amd64 BuildDate=2023-05-24T14:42:50Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Not yet tested.

I have used GitHub action to produce GitHub pages and it gives

```
Run hugo \
Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
       Run `hugo help new` for details.

Total in 1 ms
Error: Process completed with exit code 255.
```
as in [here](https://github.com/dudung/x/actions/runs/5104845206/jobs/9176032800#step:7:16).

After I copied `hugo.toml` to `config.toml`, then it works as in [here](https://github.com/dudung/x/actions/runs/5104845206/jobs/9176032800#step:7:16). I believe that GitHub action do not recognize `hugo.toml` and it is still searching `cofig.toml`.

**Comment by jmooring** [comment]
You need to update your workflow:
<https://github.com/dudung/x/blob/main/.github/workflows/hugo.yml#L34>
