### ISSUE TITLE
v0.112.4 - site.LanguageCode and site.Language.LanguageCode incorrect for monolingual site

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11037]
hugo v0.112.4-e285153d

### Site configuration (monolingual site)

```text
baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'foo'
```

Code|v0.112.3|v0.112.4 actual|v0.112.4 expected|Status
:--|:--|:--|:--|:--
{{ `site.LanguageCode` }}|en-US|en|en-US|:x:
{{ `site.Language.Language Code` }}|NA|en|en-US|:x:

### Site configuration (multilingual site)

```text
baseURL = 'https://example.org/'
title = 'foo'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
languageCode = 'en-US'
weight = 1

[languages.de]
languageCode = 'de-DE'
weight = 2
```

Code|v0.112.3|v0.112.4 actual|v0.112.4 expected|Status
:--|:--|:--|:--|:--
{{ `site.LanguageCode` }}|en-US|en-US|en-US|:heavy_check_mark:
{{ `site.Language.Language Code` }}|NA|en-US|en-US|:heavy_check_mark:

**Comment by bep** [comment]
Incredible.

**Comment by jmooring** [comment]
If you apologize, I may get on an airplane, track you down, and make you go fishing.
