### ISSUE TITLE
Potential deadlock in GroupByParam/ByParam

### ISSUE THREAD

**Issue by sparksp** [gohugoio/hugo#11039]
I recently took a huge leap from v0.85.0 to v0.112.3 (and also tried v0.111.3) and have found my build it hanging more often than not. When it succeeds it builds fast, when it hangs it seems to do so forever. I have this issue locally on my mac, and also on Netlify. I have now wrapped my build script with `until timeout -s SIGABRT 5m hugo ; do : ; done` so that it is forced to retry after 5 minutes until it succeeds, and provides the useful go dump when it fails. I have a recent [Netlify build log](https://app.netlify.com/sites/compassionate-aryabhata-ce7373/deploys/6473963f2285590008ba3f75 ) here, where it took 3 attempts to build - search for "Start building sites" for the top of each attempt. The site code is public at [sparksp/lt-osp](https://github.com/sparksp/lt-osp/tree/rules-v4).

Hopefully someone is able to see something useful in the go dump that might lead to either an issue with my site, or an issue with hugo.

### Version

```
hugo v0.112.3-ba6f74e40420d76f15fc8c2358be90f7aca98e0e+extended linux/amd64 BuildDate=2023-05-24T14:42:50Z VendorInfo=gohugoio
```

### Does this issue reproduce with the latest release?
Yes.

**Comment by jmooring** [comment]
I can reproduce with v0.97.0 and later. The problem seems to be somewhere in this:

<https://github.com/sparksp/lt-osp/blob/rules-v4/themes/lt-osp/layouts/partials/lists/term/ladder.html>

If I comment out the whole thing, the build completes quickly.

**Comment by sparksp** [comment]
Thank-you for looking at this so quickly, and having a work around! Do you know if this is something likely to be resolved in Hugo at some point? I want to know how much effort I should put in to trying to change my logic, or document the worker reduction. It does also seem like something that may trip other people up in the future.
