### ISSUE TITLE
Quotation marks and apostrophes in image alt-text are double-escaped with Goldmark Typographer

### ISSUE THREAD

**Issue by ObjectBoxPC** [gohugoio/hugo#11045]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.112.5-48e33e10af2feb2a0e1c32d04880ed016619f2d8 linux/amd64 BuildDate=2023-05-29T07:27:36Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

### Description

Quotation marks and apostrophes appearing in image alt-text are double-escaped.

The following Markdown:

```
!["They didn't even say 'hello'!" I exclaimed.](https://example.com/image.jpg)
```

is rendered as:

```
<p><img src="https://example.com/image.jpg" alt="&amp;ldquo;They didn&amp;rsquo;t even say &amp;lsquo;hello&amp;rsquo;!&amp;rdquo; I exclaimed."></p>
```

Expected output is:

```
<p><img src="https://example.com/image.jpg" alt="&ldquo;They didn&rsquo;t even say &lsquo;hello&rsquo;!&rdquo; I exclaimed."></p>
```

This is not a bug in Goldmark itself, as using that library directly produces the expected output. The bug actually was previously present in Goldmark ([GitHub issue](https://github.com/yuin/goldmark/issues/321)) but it has been fixed, so now it appears that this bug now has to do with how Hugo handles the data.

**Comment by jmooring** [comment]
Confirmed that Goldmark outptut is correct:

<details>
<summary>main.go</summary>

```text
import (
	"bytes"
	"fmt"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

func main() {
	md := goldmark.New(
		goldmark.WithExtensions(
			extension.Typographer,
		),
	)

	input := `![He said, "Eat at Joe's."](x)`

	var buf bytes.Buffer
	if err := md.Convert([]byte(input), &buf); err != nil {
		panic(err)
	}

	fmt.Println(buf.String())

}
```
</details>
<br>

Confirmed that this is not Go's [html/template](https://pkg.go.dev/html/template) package doing its thing by setting:

```text
[outputFormats.html]
isPlainText = true
```

Note that this only affects the attribute value.

#### Markdown

```text
![He said, "Eat at Joe's."](x)

[He said, "Eat at Joe's."](x)
```

#### Rendered

```html
<img src="x" alt="He said, &amp;ldquo;Eat at Joe&amp;rsquo;s.&amp;rdquo;">

<a href="x">He said, &ldquo;Eat at Joe&rsquo;s.&rdquo;</a>
```

### Example

```text
git clone --single-branch -b hugo-github-issue-11045 https://github.com/jmooring/hugo-testing hugo-github-issue-11045
cd hugo-github-issue-11045
hugo server
```
