### ISSUE TITLE
Shortcodes rendered inside markdown fenced code block

### ISSUE THREAD

**Issue by stefanv** [gohugoio/hugo#11054]
This issue appears in Hugo >= 0.100.

I have a shortcode that displays files in the current document. A simplified version is:

````
{{ $filename := (path.Join .Page.File.Dir (.Get "file")) }}
<div class="readcode-code">
   {{- print "```" (.Get "lang") "\n" (readFile $filename) "```" | safeHTML | markdownify -}}
</div>
````

What I expect is for the markdown parser to leave everything between fenced code blocks alone.
What is happening instead is that shortcodes that appear in the file are rendered.
I am not sure whether this is a feature or a bug, but it's a change in behavior from older versions of Hugo.

### Related issues

#7848 ?

**Comment by bep** [comment]
We introduced shortcode support in `page.RenderString` in Hugo 0.100.0, which was a long asked for feature. Maybe that's it in your case, but I don't see enough context to determine that, but in general: Shortcodes are content agnostic, they know nothing about the surrounding context (e.g. HTML, Markdown). There are ways to signal to Hugo that they should not be part of the Markdown rendering (the delimiters), but again, I'm not seeing enough of your code to say.

**Comment by stefanv** [comment]
Here is the full shortcode: https://github.com/scientific-python/scientific-python.org/blob/main/layouts/shortcodes/readcode.html

Example usage: https://github.com/scientific-python/specs/blob/55c8843cc6ad7df8bf02bc96e458b0008c2292ac/spec-0000/index.md?plain=1#L267

**Comment by stefanv** [comment]
Perhaps what I need to figure out, then, is how to escape shortcodes that appear in Markdown code fences.

**Comment by ww156** [comment]
{{ highlight (readFile $filename) (.Get "lang") }}

**Comment by ww156** [comment]
{{ highlight (readFile $filename) (.Get "lang") }}
but it cat't use render-codeblock hook
