### ISSUE TITLE
Fix the brew build setup

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11050]
`hugo version` outputs:

```
hugo v0.112.5+extended darwin/arm64 BuildDate=unknown
```

Downloaded from GitHub:

```
hugo v0.112.5-48e33e10af2feb2a0e1c32d04880ed016619f2d8+extended darwin/arm64 BuildDate=2023-05-29T07:27:36Z VendorInfo=gohugoio
```

Missing:

* BuildDate
* Commit hash
* VendorInfo (`brew` would be a good value)

**Comment by z0li** [comment]
The issue was on the Homebrew side and does not need any codes change in Hugo.

I've merged a PR on Homebrew and it already looks better starting with v0.115.4:
```
$ hugo version
hugo v0.115.4-dc9524521270f81d1c038ebbb200f0cfa3427cc5+extended darwin/amd64 BuildDate=2023-07-20T06:49:57Z VendorInfo=brew
```

**Comment by jmooring** [comment]
Thank you.
