### ISSUE TITLE
hugo server command fails with template: api/__common.html error

### ISSUE THREAD

**Issue by Sachin-Suresh** [gohugoio/hugo#11060]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.112.4+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

When I run `hugo server`, I get the below error:

```
ERROR 2023/05/28 21:45:40 render of "page" failed: execute of template failed: template: api/__common.html:180:27: executing "openapi3/print-operation" at <.ExtensionProps.Extensions>: can't evaluate field ExtensionProps in type *openapi3.Operation
ERROR 2023/05/28 21:45:40 render of "page" failed: execute of template failed: template: api/__common.html:180:27: executing "openapi3/print-operation" at <.ExtensionProps.Extensions>: can't evaluate field ExtensionProps in type *openapi3.Operation
ERROR 2023/05/28 21:45:40 render of "page" failed: execute of template failed: template: api/__common.html:180:27: executing "openapi3/print-operation" at <.ExtensionProps.Extensions>: can't evaluate field ExtensionProps in type *openapi3.Operation
ERROR 2023/05/28 21:45:40 render of "page" failed: execute of template failed: template: api/__common.html:180:27: executing "openapi3/print-operation" at <.ExtensionProps.Extensions>: can't evaluate field ExtensionProps in type *openapi3.Operation
Built in 22678 ms
Error: error building site: render: failed to render pages: render of "page" failed: execute of template failed: template: api/__common.html:180:27: executing "openapi3/print-operation" at <.ExtensionProps.Extensions>: can't evaluate field ExtensionProps in type *openapi3.Operation 
```

- I am running hugo on Mac 13.4 (22F66).
- Tried uninstalling and installing the latest version of hugo. The same error is shown even in the latest version
- Installed hugo with brew: `brew install hugo`

**Comment by bep** [comment]
I'm guessing this is from the Linode Docs. You should talk to them, but they should have a patched theme in place (I have talked to them) that should work with both old (< 0.112.0) and new Hugo versions.

The short take of it is that the OpenAPI library Hugo uses had a slightly breaking API change in a recent release, which Hugo now has pulled in. 

If they don't have merged this patch yet, I suggest you temporarily downgrade to hugo 0.111.4.

**Comment by Sachin-Suresh** [comment]
Thanks @bep. Where can I find the 0.111.4 version to download manually on Mac machines?
