### ISSUE TITLE
Add HTTPS support to the dev server

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11064]
Which also should have some support for create local trusted dev certificates (the hard part).

**Comment by istr** [comment]
I think the way to go for _the hard part_ would be along the lines of `caddy trust`.

As caddy is written in go, it should be straightforward to carve out the logic from there. The PKI handling is even done in a module.

But if you'd ask me, I would rather go the opposite way and completely discontinue "hugo serve".

Along the philosophy: do one thing and do it really well. Hugo + Caddy already work pretty well as a pair for local development with HTTPS "out of the box". The detour via rendering to disk shouldn't hurt much on a modern development environment (SSD) either.

Hugo is one of the best SSGs today (if not the best). Caddy is pretty decent as a dev and production server. So why not try to focus on integrating these two (only the livereload capability would need to be integrated). Caddy could even use configuration from hugo config directly with very little effort.

/cc @jmooring

**Comment by jmooring** [comment]
> discontinue "hugo server"

Would this mean that users would have to install caddy?

**Comment by istr** [comment]
@jmooring if you go by the principle "cut the logic from caddy and mimic it in hugo" - no.
If you follow the "Unix way" (one tool does one thing) - yes. hugo builds, caddy serves.

The latter was more meant to be "food for thought for strategic direction" of hugo development -- given that there is still a lot to be done (or on the roadmap) for the core functionality of building things.

Of course, deprecating `hugo serve` could have a huge impact on the current user base, but it could help prioritize / focus on other tasks.

It could be as simple as an official statement: "we will not add functionality to `hugo serve`, if you need this function (HTTPS) - use hugo along with a separate local proxy. We give guidance / document on how this could be done."

**Comment by bep** [comment]
>Would this mean that users would have to install caddy?

That's not an option. If we add some server library, it needs to be compiled in.

The `hugo server` is extremely simple by design and that will not change. The problem with adding e.g. Caddy's "trust component" or whatever is that it opens the Pandora Gate or something for people wanting to pull in more Caddy stuff.

I will have a look at how `caddy trust` works and if we can borrow some ... library code from that concept. But we obviously need something simple to use on any platform.

**Comment by istr** [comment]
> or whatever is that it opens the Pandora Gate or something for people wanting to pull in more Caddy stuff.

Exactly and to the point. I'd rather not open this box if I were in your shoes.
So I would recommend to postpone this feature or deliberately not implement it at all.

`hugo serve` is good enough for 90+% of all use cases (and probably for most users). Those (power) users who need local HTTPS in dev already know their way around it.

**Comment by bep** [comment]
No, i actually think `hugo server` really needs `HTTPS`; it has been postponed because it has been a hard problem to tackle. Now, in 2023, there may be tools available that would make this doable.

**Comment by istr** [comment]
> No, i actually think `hugo server` really needs `HTTPS`; it has been postponed because it has been a hard problem to tackle. Now, in 2023, there may be tools available that would make this doable.

Sure, your call. :smiley: In that case I would really take a closer look at caddy, because the UX of `caddy trust` is really good (at least under linux). I would appreciate if it was built in, but still find it dispensable.
