### ISSUE TITLE
 Failed to add secret. Secret names must not start with GITHUB_.  

### ISSUE THREAD

**Issue by AkarinLiu** [gohugoio/hugo#11069]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.112.7-ea3c95a7b0f2140c248c1f40246a2e7acd2ada62+extended windows/amd64 BuildDate=2023-06-02T07:07:11Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
当我尝试添加 "GITHUB_TOKEN"机密信息，却提示如下报错信息：
When I try to add "GITHUB_TOKEN" confidential information, I get the following error message:
```
Failed to add secret. Secret names must not start with GITHUB_. 
```

**Comment by AkarinLiu** [comment]
@github

**Comment by tianheg** [comment]
Please provide the details

**Comment by bep** [comment]
This seems to be in the wrong repository.
