### ISSUE TITLE
Hugo watch (-w) without server injects livereload.js that is unreachable

### ISSUE THREAD

**Issue by istr** [gohugoio/hugo#11061]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.112.6-2ca0fcc4485c74859382ffab4abf8610cdd3771a+extended linux/amd64 BuildDate=2023-06-01T09:03:29Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

# Scenario

Run `hugo -w` (_not_ in server mode) along with `caddy` for local testing to overcome the current limitation that `hugo server` does not yet provide HTTPS (see https://github.com/gohugoio/hugo/issues/4883).

# Observed behavior

When running hugo in build mode with the  `-w` option, but _without_ `server`, the livereload script
```
<script src="/livereload.js?mindelay=10&amp;v=2&amp;port=&amp;path=livereload" data-no-instant defer></script>
```
is injected anyway. However, this is not usable since `hugo -w` does not expose it when not in `server` mode.
The `--liveReloadPort int` and `--disableLiveReload` options are only available for `hugo server` but not for `hugo -w`. 

# Expected behavior
When running `hugo -w` the livereload script is not injected.

# Alternative behavior
When running `hugo -w` the livereload function behaves the same as in `server` mode but the server only serves the livereload hook:

- `hugo -w` livereload enabled, script injected, server started for livereload _only_
- `hugo -w --disableLiveReload` no script injection, no livereload listener
- `hugo -w --liveReloadPort int` script injection, server started for livereload _only_, connect to other port

**Comment by jmooring** [comment]
Confirmed.

This worked as desired in v0.111.3. It stopped working as desired in v0.112.0.

**Comment by jmooring** [comment]
You may be able to use this instead:

```
hugo server --renderToDisk --disableLiveReload --baseURL "https://example.org/"
```
