### ISSUE TITLE
Pipes are not re-run on Page Resources

### ISSUE THREAD

**Issue by trwnh** [gohugoio/hugo#11070]
## Summary

Trying to use Page Resources combined with Pipes will not work. The pipeline is executed once, and will not be re-executed unless you restart the Hugo server.

## Steps to Reproduce

1. Clone https://github.com/trwnh/hugo-bug-reproducibles/tree/page-resources-pipes-scss
2. `hugo serve`
3. Edit `content/section/page/style.scss` and change `color: blue` to `color: red`

### Expected behavior

Live reload changes the color from blue to red.

### Actual behavior

Nothing changes. Hugo server detects a change and rebuild, but it has no effect.

## Misc

The following forum thread may be related:

- https://discourse.gohugo.io/t/asset-pipelines-with-page-resources/25199

However, no conclusion was reached.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.112.3+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by bep** [comment]
We have fixes in the pipeline for this an simular issues about the same, so I'm closing this as a duplicate.

That said, you should be able to fix your current issue by configuring some more coarse grained cache busters, see.

https://gohugo.io/getting-started/configuration/#configure-cache-busters

**Comment by trwnh** [comment]
Is there anywhere I can track progress on the "fixes in the pipeline"? Perhaps some other Github issue I can follow for notifications?
