### ISSUE TITLE
Check if logging to file somehow got lost

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11071]

**Comment by jmooring** [comment]
So, we have a lot of related options, and it's not clear to me how some of these interact with each other.

```
--debug       debug output
--log         enable logging
--logFile     log filepath (if set, logging enabled automatically)
--verbose     verbose output
--verboseLog  verbose logging
```

And there's https://github.com/gohugoio/hugo/issues/9648.

**Comment by bep** [comment]
We also have the related `--quiet` which removes ... everything. But that is also muting non-log print statements (e.g. "Total in ...").
