### ISSUE TITLE
Hugo 0.113 introduced a potential regression

### ISSUE THREAD

**Issue by mreferre** [gohugoio/hugo#11086]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.113.0-085c1b3d614e23d218ebf9daad909deaa2390c9a+extended linux/amd64 BuildDate=2023-06-05T15:04:51Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes. 

Hi there. I have a fairly basic blog that uses Hugo. I have a pipeline that, upon every change I make (e.g. adding a post) does the following (among other things): 
- grab the latest version of Hugo Extended 
- build the site using `hugo` 
- other parts of the pipeline pushes this to S3 but this is irrelevant. 

This pipeline has worked fine until a few weeks ago and from the log I can see it used this hugo version:
```
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
``` 

Today I was trying to add a new post to my blog and my pipeline broke with the following error at build time: 

```


[Container] 2023/06/12 12:12:43 Running command hugo
--
......
145 | Start building sites …
146 | hugo v0.113.0-085c1b3d614e23d218ebf9daad909deaa2390c9a+extended linux/amd64 BuildDate=2023-06-05T15:04:51Z VendorInfo=gohugoio
147 | Total in 889 ms
148 | Error: error building site: process: readAndProcessContent: open /codebuild/output/src674739761/src/github.com/mreferre/blog/public/config.yaml: no such file or directory
149 |  
150 | [Container] 2023/06/12 12:12:44 Command did not exit successfully hugo exit status 1
151 | [Container] 2023/06/12 12:12:44 Phase complete: BUILD State: FAILED
152 | [Container] 2023/06/12 12:12:44 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: hugo. Reason: exit status 1
....
```

I can confirm that by hard-coding in my pipeline the artifact that points to the 0.111 release (`hugo_extended_0.111.3_Linux-64bit.tar.gz`) the build works just fine. 

I had a look at the 0.112 and 0.113 releases but I can't see a major breaking change so I am wondering if this is a bug/regression? 

Unfortunately my blog is in a private repo that I can't open publicly but I am willing to share portions of it if it's helpful for the debugging.

Thanks!

**Comment by bep** [comment]
The error message does not make any sense to me, which suggests that you do something very ... unusual which happened to somehow work in Hugo < 0.112.0.

**Comment by mreferre** [comment]
I should also mention that if I build the site locally on my laptop (MacOS on an M1 MacBook Pro) using the same 0.113.0 version that fails in the pipeline (ran in a CodeBuild Linux x86 environment) it works fine. 

```
$hugo version
hugo v0.113.0-085c1b3d614e23d218ebf9daad909deaa2390c9a+extended darwin/arm64 BuildDate=2023-06-05T15:04:51Z VendorInfo=gohugoio
```

**Comment by mreferre** [comment]
I have tried to build the blog using a cloud IDE running Linux / x86 (basically using the same hugo binary I am using in the pipeline) and it worked fine. 

Everything seem to be pointing to a local issue with the CodeBuild environment configurations I am using (which I have not changed since the last successful run and I doubt there was any breaking change introduced since). 

It drives me nuts.

**Comment by jmooring** [comment]
This project builds and deploys without error using v0.113.0, AWS CodeBuild, and AWS S3 static hosting:
<https://github.com/jmooring/hosting-aws-codebuild>

The [buildspec](https://github.com/jmooring/hosting-aws-codebuild/blob/main/buildspec.yml) is very simple.

I'm closing this, but feel free to open a topic in the forum (https://discourse.gohugo.io/) if you wish to discuss it further. Thanks.

**Comment by mreferre** [comment]
Thanks. I did try with that buildspec for my blog and I am getting the same error (the original error). With the blog example you have in the repo linked it works just fine. So it's this incredibly weird combo of 0.113 + my own blog + codebuild (any other combo that does NOT use one of these three seems to be working). 

I may follow up on Discord after I test this even further. Thanks!
