### ISSUE TITLE
`hugo server -o` for opening the default web-browser

### ISSUE THREAD

**Issue by blyxyas** [gohugoio/hugo#11102]
The `-o` / `--open` flag would open the user's default browser automatically the first time it's build. It doesn't open it in every hot reload, but just after being executed.

Similar to `rustdoc`'s `--open` flag.

**Comment by bep** [comment]
I'm closing this. I have never missed such a feature myself, and it's non-trivial to implement cross platform, and any "this does not work on Solaris" will eventually end up as additional work here and on the forum.
