### ISSUE TITLE
Access "File.Path" of invalid page object generates invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by GrahamDumpleton** [gohugoio/hugo#11113]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.113.0-085c1b3d614e23d218ebf9daad909deaa2390c9a linux/amd64 BuildDate=2023-06-05T15:04:51Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Above is the latest as far as I know.

### Description of issue.

With the following code:

```
{{ $page := .Site.GetPage "does-not-exist" }}

{{ with $page }}
<p>{{ .File.Path }}</p>
{{ else }}
<p>Ouch</p>
{{ end }}

<p>{{ $page.File.Path }}</p>
```

Yes, it is sensible to check using `with $page` before doing anything that it is a valid page object, but if you don't it may be more useful that if you access `$page.File.Path` it would generate a nice error message, or resolve to a null or empty value. Right now it instead gives the more scary error of:

```
Error: error building site: render: failed to render pages: render of "page" failed: "/.../themes/.../layouts/_default/single.html:14:11": execute of template failed: template: _default/single.html:14:11: executing "main" at <$page.File.Path>: error calling Path: runtime error: invalid memory address or nil pointer dereference
```

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
