### ISSUE TITLE
The snap package hangs when calling asciidoctor

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11116]
Introduced in https://github.com/gohugoio/hugo/pull/11101 due to an invalid "strict confinement" test. Transitioning to core22 bumped ruby from 2.7 to 3.0. Snap debugging indicates gemspec permission requirement that was not present with ruby 2.7:

```
= AppArmor =
Time: Jun 15 12:54:59
Log: apparmor="DENIED" operation="file_lock" class="file" profile="snap.hugo.hugo" name="/snap/hugo/x1/usr/lib/ruby/gems/3.0.0/specifications/default/abbrev-0.1.0.gemspec" pid=95381 comm="ruby" requested_mask="w" denied_mask="w" fsuid=1000 ouid=0
File: /snap/hugo/x1/usr/lib/ruby/gems/3.0.0/specifications/default/abbrev-0.1.0.gemspec (write)
Suggestion:
* adjust program to not write to $SNAP

```

Instead of staging the asciidoctor package, consider staging the ruby snap and install the gem.

**Comment by bep** [comment]
OK. I'm not doing any release until over the weekend. I have been burned pretty badly when doing Friday releases before.

**Comment by jmooring** [comment]
Although it _may_ be possible to include Asciidoctor with core22 under strict confinement, I have explored several avenues and cannot get past the Apparmor denials. Conclusions:

1. Revert https://github.com/gohugoio/hugo/pull/11101.
2. Transition to classic confinement (separate issue, no rush).
