### ISSUE TITLE
Empty `<p>` tags gets created when `<img>` is wrapped by `<figure>` in `render-image.html`

### ISSUE THREAD

**Issue by tomy0000000** [gohugoio/hugo#11123]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.113.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

### Description

I have a very simple post that only contains the following:

```markdown
---
title: "My First Post"
date: 2023-06-17T06:09:29+08:00
draft: true
---

[![CC BY-NC 4.0 License](https://licensebuttons.net/l/by-nc/4.0/88x31.png)](https://creativecommons.org/licenses/by-nc/4.0/)

```

Say I have a `render-image.html`:

```html
<img
    src="{{ .Destination }}"
    alt="{{ .Text }}"
/>
```

which yield:

```html
<p>
  <a href="https://creativecommons.org/licenses/by-nc/4.0/"
    ><img
      src="https://licensebuttons.net/l/by-nc/4.0/88x31.png"
      alt="CC BY-NC 4.0 License"
  /></a>
</p>
```

If I changed the `render-image.html` by adding a `<figure>` that wraps `<img>`:

```html
<figure><img
    src="{{ .Destination }}"
    alt="{{ .Text }}"
/></figure>
```

The output now adds additional `<p>` tags before and after the `<figure>` tag:

```html
<p><a href="https://creativecommons.org/licenses/by-nc/4.0/"></a></p>
<figure>
  <a href="https://creativecommons.org/licenses/by-nc/4.0/"
    ><img
      src="https://licensebuttons.net/l/by-nc/4.0/88x31.png"
      alt="CC BY-NC 4.0 License"
  /></a>
</figure>
<p></p>
```

Since the image is wrapped by an `<a>` tag, the first `<p>` tag also contains the anchor.

You can find the source of this example at https://github.com/tomy0000000/hugo-render-image-demo

To add a little observability, I add a short custom CSS that will add a small icon at the end of every `<a>` tag. So this is what I expected: 

![expected](https://github.com/gohugoio/hugo/assets/23290356/94354804-53de-42ac-861a-bbaa136a6a1e)

And this is the actual result:

![actual](https://github.com/gohugoio/hugo/assets/23290356/2e7b9fc1-f95f-4071-9a44-1c29336bd4f5)

Notice the top left icon is attached to the empty `<a>` tag inside `<p>` tag

**Comment by jmooring** [comment]
You are viewing the rendered HTML in your browser's dev tools. The browser adjusts the HTML because what you are actually rendering is invalid HTML. If you view source (typically Ctrl +U) you will see the actual HTML rendered by Hugo.

This is not a bug. It's a configuration issue. Let's move this discussion to the forum (https://discourse.gohugo.io/). We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
