### ISSUE TITLE
dartsass: Look also in `./node_modules` folder for the binary

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#11137]
Would it make sense to look into `./node_modules` for `sass` now that the regular Dart Sass binary is supported? Similar to postcss?

**Comment by jmooring** [comment]
```
$ npm install sass
$ ./node_modules/.bin/sass --embedded --version

sass --embedded is unavailable in pure JS mode.
```

**Comment by XhmikosR** [comment]
v104.0 release notes mention:

>The main new thing in this release is that we now support both major versions of the [Dart Sass](https://github.com/sass/dart-sass/releases) Embedded protocol, which means that you now can use the regular Dart Sass binary.

Am I missing something?

**Comment by bep** [comment]
>Am I missing something?

Maybe. The binary in `node_modules` isn't ... regular -- it's tailored to work with Node JS etc., I guess.

**Comment by jmooring** [comment]
<https://github.com/sass/dart-sass/releases/tag/1.63.0>

> The Dart Sass embedded compiler is now included as part of the primary Dart Sass distribution, rather than a separate executable. To use the embedded compiler, just run sass --embedded from any Sass executable (**other than the pure JS executable**).

**Comment by bep** [comment]
... but does that mean that if we dropped --embedded when running the JS executable ... it would work?

I'm sure they made this upgrade simple to understand.

**Comment by jmooring** [comment]
I've requested a documentation change:
<https://github.com/sass/dart-sass/pull/2022>

**Comment by bep** [comment]
@jmooring would it not be better to request them to make `--embedded` a no-op flag on the JS executable?

**Comment by bep** [comment]
OK, it's compiled to JS, which I guess is not something that we could/would want to use.

```
~/d/m/n/.bin ❯❯❯ ./sass --version                                                                                                       ✘ 1
1.63.4 compiled with dart2js 3.0.4
```

**Comment by jmooring** [comment]
This is covered at a higher level in  https://github.com/gohugoio/hugo/issues/8299.
