### ISSUE TITLE
hugo mod get --help does not print help but passes --help to go get

### ISSUE THREAD

**Issue by jcdny** [gohugoio/hugo#11141]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.112.7+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes

<pre>
$ hugo mod get --help
usage: go get [-t] [-u] [-v] [build flags] [packages]
Run 'go help get' for details.
Error: failed to get ["-d" "--help"]: failed to execute 'go [get -d --help]': failed to execute binary "go" with args [get -d --help]: usage: go get [-t] [-u] [-v] [build flags] [packages]
Run 'go help get' for details.
 *errors.errorString
</pre>

**Comment by bep** [comment]
I agree that this is a bug, but it's a little bit in the nature of how `hugo mod get` works, as we just pass on (most of) the flags to `go get` which does the hard work.
