### ISSUE TITLE
[bug] version 0.114.0 error: undefined: atomic.Int64

### ISSUE THREAD

**Issue by reatang** [gohugoio/hugo#11144]
### What version of Hugo are you using (`hugo version`)?

0.114.0

### Does this issue reproduce with the latest release?

go/pkg/mod/github.com/gohugoio/hugo@v0.114.0/common/types/types.go:96:30: undefined: atomic.Int64

atomic.Int64 need go 1.19

**Comment by jmooring** [comment]
Go version requirements:

- Building Hugo from source requires Go 1.19 or later.
- The Hugo executable requires Go 1.11 or later when working with Hugo Modules. 
- The Hugo executable requires Go 1.18 or later when working with Hugo Modules in workspace mode.

I don't see how this is a bug.

**Comment by bep** [comment]
We support (normally) the current and current-1 Go version, which now is Go 1.19 and Go 1.20.

**Comment by reatang** [comment]
Sorry I might not have expressed myself clearly.
I am a beginner in golang, and some basic knowledge is not perfect enough.

I mean, should I modify "go 1.18" to "go 1.19" in the "go.mod" file.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
