### ISSUE TITLE
Regression: cannot define output formats per language

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11159]
This worked in v0.111.3 and earlier:

```
[languages.de.outputFormats.json]
path = 'xx'
```

With v0.112.0 and later:

> Error: failed to create config from result: failed to decode config for language "de": unknown config key "outputformats"

Reference: <https://discourse.gohugo.io/t/44976>

Minimal example:

```text
git clone --single-branch -b hugo-forum-topic-44976 https://github.com/jmooring/hugo-testing hugo-forum-topic-44976
cd hugo-forum-topic-44976
rm -rf public/ && hugo && tree public
```

**Comment by yimmy23** [comment]
Thank you for your reply!

**Comment by jmooring** [comment]
@yimmy23 The error you reported:

> failed to create config from result: failed to decode config for language "fr": unknown config key "profilemode".

is not related to this issue.

Please create a topic in the forum (https://discourse.gohugo.io/). This is issue is closed.
