### ISSUE TITLE
SEO Issue, Setting Optimized Images to Have Same URL Each Generation

### ISSUE THREAD

**Issue by simeononsecurity** [gohugoio/hugo#11157]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version v0.113.0

</pre>

### Does this issue reproduce with the latest release?
Yes

So with any search engine, we're also hoping our images get indexed as well.  
You can adjust the fingerprint, but there is no good way to standardize the resulting url of an image so that it can be properly cached and so that it's useful when users are searching your images through google, bing, etc. Currently it's only useful if you don't update your site all that often.

My suggestion would be to implement a more standardized file name chems, like input filename, resolution, file extension
So instead of when I optimize photo.png to webp it being `_hu1fccc78bc09fbc5603c157bd73d4669e_170017_134d8f41ac8e8dc20fdf9a9c327222eb.webp`
it should be more like `photo_1200x630.webp`

**Comment by jmooring** [comment]
Use resources.Copy, and set your own pattern via printf.

**Comment by simeononsecurity** [comment]
> Use resources.Copy, and set your own pattern via printf.

I don't mean to be stupid here. But I've researched this and didn't find what you're referring to. It also doesn't explain why this isn't the default behavior. 

@jmooring can you share a resource or codesnippit I could look at?

**Comment by jmooring** [comment]
It isn't the default behavior because you need to invalidate caches, everywhere, when _any_ characteristic changes. See this description of the filename components:

<https://discourse.gohugo.io/t/cache-busting-with-resources-concat/44652/2?u=jmooring>

It the URL to your processed photo is `https://example.org/img/photo_1200x630.webp`, and you later change processing parameters (e.g, quality, resampling filter), or if you change the underlying image data but keep the same filename, the URL will not change. That is not what you want. 

To copy a processed image resource to another name you can do something like:

```
{{ with .Resources.Get "photo.jpg" }}
  {{ $base := strings.TrimLeft (path.Ext .Key) .Key }}
  {{ $ext := path.Ext .Key  }}
  {{ with .Fill "1200x630 webp" }}
    {{ $target := printf "%s_%dx%d%s" $base .Width .Height $ext }}
    {{ with resources.Copy $target . }}
        <img src="{{ .RelPermalink }}" width="{{ .Width }}" height="{{ .Height }}" alt="">
    {{ end }}
  {{ end }}
{{ end }}
```

Which gives you:

```text
public/
├── posts/
│   ├── post-1/
│   │   ├── index.html
│   │   ├── photo.jpg
│   │   └── photo.jpg_1200x630.jpg
│   ├── post-2/
│   │   ├── index.html
│   │   ├── photo.jpg
│   │   └── photo.jpg_1200x630.jpg
│   └── index.html
├── favicon.ico
└── index.html
```

If you need further assistance, please use the forum (https://discourse.gohugo.io/). We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by simeononsecurity** [comment]
> It isn't the default behavior because you need to invalidate caches, everywhere, when _any_ characteristic changes. See this description of the filename components:
> 
> https://discourse.gohugo.io/t/cache-busting-with-resources-concat/44652/2?u=jmooring
> 
> It the URL to your processed photo is `https://example.org/img/photo_1200x630.webp`, and you later change processing parameters (e.g, quality, resampling filter), or if you change the underlying image data but keep the same filename, the URL will not change. That is not what you want.
> 
> To copy a processed image resource to another name you can do something like:
> 
> ```
> {{ with .Resources.Get "photo.jpg" }}
>   {{ $base := strings.TrimLeft (path.Ext .Key) .Key }}
>   {{ $ext := path.Ext .Key  }}
>   {{ with .Fill "1200x630 webp" }}
>     {{ $target := printf "%s_%dx%d%s" $base .Width .Height $ext }}
>     {{ with resources.Copy $target . }}
>         <img src="{{ .RelPermalink }}" width="{{ .Width }}" height="{{ .Height }}" alt="">
>     {{ end }}
>   {{ end }}
> {{ end }}
> ```
> 
> Which gives you:
> 
> ```
> public/
> ├── posts/
> │   ├── post-1/
> │   │   ├── index.html
> │   │   ├── photo.jpg
> │   │   └── photo.jpg_1200x630.jpg
> │   ├── post-2/
> │   │   ├── index.html
> │   │   ├── photo.jpg
> │   │   └── photo.jpg_1200x630.jpg
> │   └── index.html
> ├── favicon.ico
> └── index.html
> ```
> 
> If you need further assistance, please use the forum (https://discourse.gohugo.io/). We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

So cache busting is nice and all, however it works in contrast to how google and other search engines will index your website and images. It's a trade off I believe that many large developers wouldn't make. I could be wrong here, but I would prefer a solution that can accommodate both. 

The proper compromise in my opinion would be to set the following in your netlify.toml or .htaccess file

```toml
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"
 ```

```html
<IfModule mod_headers.c>
  <FilesMatch "\.(jpg|jpeg|png|gif|ico|webp)$">
    Header set Cache-Control "public, max-age=31536000, must-revalidate"
  </FilesMatch>
</IfModule>
```

This sets the images to be cached, but must be revalidated after some time. Sites would only have issue with this if they are changing images often and they would require the same file name and resolution to run into that. So it's only going to be an issue the first time they try to enable the image optimization. So it makes no sense to have the cache busting as a default behavior. 
Not to mention that you could easily change the headers while in development so that they are not cached as long and with cloudflare you can purge the cache manually if you'd like. 

However thanks for the resource and code snippit. I got something that works for me after some trial and effort from that.
```jinja
{{ $detectedimage := "" }}
{{ $og_image := "" }}
{{ if .Params.cover }}
  {{ $cover := resources.Get (.Params.Cover) }}
  {{ $detectedimage = ( .Params.cover | absURL) }}
  {{ if .Params.UseRelativeCover }}{{ $cover = resources.GetRemote (printf "%s%s" .Permalink .Params.Cover) }}{{ end }}
  {{ $optimizedimage := ($cover.Resize "1200x630 webp q80") }}
  {{ $permalink := replace $cover.RelPermalink (printf ".%s" $cover.MediaType.SubType) "" }}
  {{ $filename := printf "%s_%dx%d.%s" $permalink $optimizedimage.Width $optimizedimage.Height "webp" | urlize }}
  {{ $renamedimage := $optimizedimage | resources.Copy $filename }}
  {{ $og_image = $renamedimage.Permalink}}
{{ else }}
  {{ if .Params.images }}
    {{ $og_image = index .Params.images 0 | absURL }}
  {{ else }}
    {{ $og_image = index $.Site.Params.images 0 | absURL }}
  {{ end }}
{{ end }}
<meta property="og:image" content="{{ $og_image }}" />
<meta itemprop="image" content="{{ $og_image }}">
```

I will use the hugo form for help. But I do genuinely believe that the default behavior here is flawed.
