### ISSUE TITLE
Command 'hugo convert' with no arguments: silent exit instead of command synopsis

### ISSUE THREAD

**Issue by deining** [gohugoio/hugo#11165]
The command `hugo convert` fails silently when invoked without subcommand as argument. This wan't the case with older hugo versions, there the synopsis of the command was printed out:

### hugo v.0.114.1 (silent exit)

<pre>
$ hugo convert

</pre>

### hugo v.0.101.0 (synopsis of command is printed out)

<pre>
$ hugo_0.101.0.exe convert
Convert your content (e.g. front matter) to different formats.

See convert's subcommands toJSON, toTOML and toYAML for more information.

Usage:
  hugo convert [command]

Available Commands:
  toJSON      Convert front matter to JSON
  toTOML      Convert front matter to TOML
  toYAML      Convert front matter to YAML

Flags:
  -h, --help            help for convert
  -o, --output string   filesystem path to write files to
      --unsafe          enable less safe operations, please backup first

Global Flags:
      --clock string               set the clock used by Hugo, e.g. --clock 2021-11-06T22:30:00.00+09:00
      --config string              config file (default is path/config.yaml|json|toml)
      --configDir string           config dir (default "config")
      --debug                      debug output
  -e, --environment string         build environment
      --ignoreVendorPaths string   ignores any _vendor for module paths matching the given Glob pattern
      --log                        enable Logging
      --logFile string             log File path (if set, logging enabled automatically)
      --quiet                      build in quiet mode
  -s, --source string              filesystem path to read files relative from
      --themesDir string           filesystem path to themes directory
  -v, --verbose                    verbose output
      --verboseLog                 verbose logging

Use "hugo convert [command] --help" for more information about a command.
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by roshanavand** [comment]
This change is introduced in [v0.112.0](https://github.com/gohugoio/hugo/releases/tag/v0.112.0) via this [commit](https://github.com/gohugoio/hugo/commit/241b21b0fd34d91fccb2ce69874110dceae6f926) and it affects not just `convert` command but also `import`, `new`, `list` and `gen` commands.
