### ISSUE TITLE
Add resources to top level sections without a _index.md file

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11179]
I'm not sure if this is a bug or an enhancement. 

This content:

```text
content/
├── books/
│   ├── book-1.md
│   ├── book-2.md
│   └── section.jpg
└── films/
    ├── film-1.md
    ├── film-2.md
    ├── _index.md
    └── section.jpg
```

With this code in layouts/_default/home.html:

```
{{ range .Sections.ByTitle }}
  <pre>
    .Title --> {{ .Title }}
    .IsSection --> {{ .IsSection }}
    .BundleType --> {{ .BundleType }}
    .Resources.Get "section.jpg" --> {{ .Resources.Get "section.jpg" }}
  </pre>
{{ end }}
```

Produces:

```text
.Title --> Books
.IsSection --> true
.BundleType --> branch
.Resources.Get "section.jpg" --> 

.Title --> Films
.IsSection --> true
.BundleType --> branch
.Resources.Get "section.jpg" --> section.jpg
```

If the "books" section were a branch bundle, then "section.jpg" should be available as a page resource.

Two options:

1. Make .BundleType return nothing for top level sections without _index.md files
2. Treat top level sections without _index.md files as branch bundles.

Option 2 makes more sense to me, but I don't know what it would break.

Same results with v0.54.0 -- this isn't anything new.

**Comment by jmooring** [comment]
Regarding Option 2 in my previous comment: it would improve link/image portability in conjunction with render hooks.

This content structure is common in Hugo and in other markdown environments (GitHub, Obsidian, etc.):

```text
content/posts/  <--- no _index.md. It IS a section, and .BundleType currently (erroneously) returns "branch".
├── kitten.jpg
├── post-1.md
└── post-2.md
```

content/posts/post-1.md

```
![A kitten](kitten.jpg)
```

An image render hook that looks for a page resource won't find the image, and that's how it should be. But, if content/posts were a branch bundle (as .BundleType reports today), the render hook could fall back to the current section. A simplified example:

```
{{ with .Page.Resources.Get .Destination }}
  <img src="{{ .RelPermalink }}" width="{{ .Width }}" height="{{ .Height }}" alt="">
{{ else }}
  {{ with (and (ne .Page.BundleType "leaf") (.Page.CurrentSection.Resources.Get .Destination)) }}
     <img src="{{ .RelPermalink }}" width="{{ .Width }}" height="{{ .Height }}" alt="">
  {{ else }}
    {{ errorf "Resource not found."
  {{ end }}
{{ end }}
```

This works fine today in directories with _index.md files. But the point is, for a top level section, it is common to not have an _index.md file. I understand that this won't work with directories further down the tree that lack _index.md files, and that's fine. The more common scenario relates to the top level section.

This is, to some extent, related to https://github.com/gohugoio/hugo/issues/4583.

Finally, I'm also fine just correcting .BundleType for the top level sections.

**Comment by bep** [comment]
>Two options:

Or:

3. Add a `_index.md` file.

So, this issue is certainly as designed, as

* All first level folders with content in them are sections by definition (mostly to handle older Hugo sites)
* All sections are by definitions branch bundles.
* It's just a technical reason that we're doing the bundling when we're reading the files. And then, later, we create the missing sections for the top level folders (which then does not get the bundled resources).

**Comment by bep** [comment]
OK, thinking about this, I have fixed this in a branch that I had planned to get out the door soon.

**Comment by jmooring** [comment]
Duplicate of https://github.com/gohugoio/hugo/issues/11439
