### ISSUE TITLE
buildStats missing IDs when tags and classes are disabled

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11202]
hugo v0.116.0-DEV-5afc89f

disableTags|disableClasses|disableIDs|expected|actual|status
:--|:--|:--|:--|:--|:--
true|false|false|classes & IDs|classes & IDs|PASS
false|true|false|tags & IDs|tags & IDs|PASS
false|false|true|tags & classes|tags & classes|PASS
true|true|false|IDs|all null|**FAIL**
true|false|true|classes|classes|PASS
false|true|true|tags|tags|PASS

**Comment by bep** [comment]
That's odd ... Thanks for the heads up. I'm guessing that disabling tags is effectively disabling everything, which it shouldn't, I guess.
