### ISSUE TITLE
Add a "none" config option for titleCaseStyle

### ISSUE THREAD

**Issue by cyChop** [gohugoio/hugo#11204]
The [`title`](https://gohugo.io/functions/title/) is great for people who always hesitate about how to capitalize English titles.

However, it only proposes English-style capitalizations. Some languages (as French) don't have such conventions and write titles without capitalizations.

If `title` is used in a theme, it will result in titles being wrongly capitalized in such languages.

Adding a setting that makes `title` a no-op function seems to be the easiest way to address this issue: when the proposed settings don't match the conventions of the language, the webmaster can choose the "none" setting and manually capitalize the titles.

Reference for `titleCaseStyle`: https://gohugo.io/getting-started/configuration/#configure-title-case

**Comment by bep** [comment]
Yes, that is a great idea.

I suggest we use `none`.

Maybe it would also be good to have a very simple `firstupper` style as well, which I suspect would make sense at least in Norwegian (my native language).

**Comment by techmagus** [comment]
> Maybe it would also be good to have a very simple `firstupper` style as well, which I suspect would make sense at least in Norwegian (my native language).

Thank you very much for this! Here in the Philippines, we generally use sentence case in titles that are not book, movie, thesis, dissertation titles (thesis/dissertation can even use sentence case). Everything else, like article titles, are sentence case titles, even local reputable news agencies.

Thank you very much!
