### ISSUE TITLE
safeURL & safeHTML still encodes the punctuation in URL

### ISSUE THREAD

**Issue by itzrahulsoni** [gohugoio/hugo#11210]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended
</pre>

### Does this issue reproduce with the latest release?
Yes

The frontmatter contains a parameter called 

```
cover_image: https://www.bakemyweb.com/files/public/de/69/2770cae8aabc7706c58dde69/i/d4/c6/64997da40192440030ddd4c6/original?name=rss.svg&mimetype=image/svg+xml&cd=inline
```

In one of the partials called header, I am using: 

```
<meta property="og:image" content="{{- .Page.Params.cover_image | safeURL -}}" />
```

Hugo is changing the URL to:

https://www.bakemyweb.com/files/public/de/69/2770cae8aabc7706c58dde69/i/d4/c6/64997da40192440030ddd4c6/original?name=rss.svg&mimetype=image/svg&#43;xml&cd=inline

In this case `+` was converted to `&#43;`

The original URL is:
https://www.bakemyweb.com/files/public/de/69/2770cae8aabc7706c58dde69/i/d4/c6/64997da40192440030ddd4c6/original?name=rss.svg&mimetype=image/svg+xml&cd=inline

Is there a workaround?

I have already tried safeHTML and it exhibits the same behaviour.

**Comment by jmooring** [comment]
```
<meta property="og:image" {{ printf "content=%q" .Page.Params.cover_image | safeHTMLAttr }}>
```

In the future, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by itzrahulsoni** [comment]
Will do. Thanks much. I am curious why this is not considered a bug?
