### ISSUE TITLE
languages.xx.disabled not working with v0.112.0 and later

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11219]
This works as expected with v0.111.3 and earlier:

```
[languages.es]
languageCode = 'es-ES'
weight = 3
disabled = true
```

With v0.112.0 and later, the site above is published (the `disabled` key is ignored) with this warning:

> WARN  config: languages.es.disabled: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.es.params].

**Comment by jmooring** [comment]
See <https://github.com/gohugoio/hugo/issues/4963#issuecomment-406076190>.

I don't think `languages.xx.disabled` was ever documented.

**Comment by bep** [comment]
Workaround: `disableLanguages = ["en']`
