### ISSUE TITLE
hugo snap is unable to deploy to AWS/GCP due to snap confinement misconfiguration

### ISSUE THREAD

**Issue by mattbnz** [gohugoio/hugo#11222]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.115.1-857374e69358f788bd31ddc55255c5c8e3dcfd80+extended linux/amd64 BuildDate=2023-07-03T17:28:25Z VendorInfo=snap:0.115.1
</pre>

### Does this issue reproduce with the latest release? 

Yes  - the HEAD snapcraft.yaml contains the issue 

### Issue Description

The third assumption in the [deploy documentation](https://gohugo.io/hosting-and-deployment/hugo-deploy/#assumptions) is impossible to cleanly fulfil when using hugo installed from snap (one of the supported mechanisms listed at https://gohugo.io/installation/linux/#snap)

Specifically, the listed cloud authentication methods (e.g. `gcloud auth login`, `aws configure`, etc) all rely on credential files located in hidden directories within $HOME which are not accessible to the hugo snap due to the strict confinement policy applied at snapcraft.yaml line 12. 

While specific plugs to access the gitconfig within the `.git` directory are provided, no similar plug configuration is provided for the cloud provider directories making `hugo deploy` essentially impossible to use as per the documented instructions.

### Steps to reproduce

1. Create a hugo site with an s3 deployment configuration
2. Configure AWS credentials via the documented `aws configure` command
3. run `hugo deploy`

### Expected behaviour

Hugo would pick up the configured credentials (via gocloud's default behaviour) from `.aws/credentials` and deploy the site. 

### Observed behaviour

Hugo fails to deploy the site with an obscure and confusing error
```
matt@argon:~/web/hugo$ hugo deploy
Deploying to target "s3" (s3://test-bucket?region=ap-southeast-2)
Error: blob (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

### Suggested Fixes

1. Hugo needs to provide a snap configuration that works with the documented deployment mechanisms, so access to `~/.gcloud`, `~/.aws` and whatever Azure uses needs to be configured in snapcraft.yaml
2. The snap package documentation at https://gohugo.io/installation/linux/ could also be a bit more verbose about the implications of strict confinement - specifically the limitations on accessing dotfiles other than those explicitly allowed, while the limitations on removeable media are specifically noted, the nuance of snaps `home` vs `personal-files` interfaces is unlikely to be obvious or apparent to even a diligent user who clicks through to the confinement link (and even if they do, this is a developer oriented document, not an end-user oriented document!).

**Comment by jmooring** [comment]
Closing in favor of https://github.com/gohugoio/hugo/issues/11126.

If service config/credentials were in _fixed_ locations we could request+add more interfaces. But the location of the service config/credentials can be overridden by env vars. So we end up in the same place if  the path is another hidden directory in the user's `$HOME` path, or a path outside of `$HOME`.

**Comment by jmooring** [comment]
So, #11126 is the optimal way to address this issue, but that's not something we can do quickly. Adding a few more interfaces will cover most scenarios, and will take only a few days for approval.

**Comment by jmooring** [comment]
We received the required approvals yesterday, giving us read access to:
- `$HOME/.aws`
- `$HOME/.azure`
- `$HOME/.config/gcloud`
