### ISSUE TITLE
XML code not highlighted in the expand shortcode.

### ISSUE THREAD

**Issue by vhorvat** [gohugoio/hugo#11238]
<pre>
$ hugo version v115.2
geekdoc theme
https://github.com/thegeeklab/hugo-geekdoc
</pre>

Hello!
While using Hugo powered page for my personal project where in one use case I use expand shortcode with code highlighting function in conjunction, if the code in the expand block is XML it's not highlighted as it should be but parsed instead.

I figured out that if I remove htmlUnescape function from the expand shortcode, everything works fine.
My question is whether is this by design or is this indeed a bug since I don't really know the background why htmlUnescape is used here. If I choose any other programming language to be used for the highlighting inside expand shortcode everything works as regular.

Is there a different proposed way to use expand + highlight function while working with XML?

Thank you!

With **htmlUnescape** used:
![image](https://github.com/gohugoio/hugo/assets/37957537/c5c230a8-ed14-4ef1-afef-f3001a2b9c56)

Without **htmlUnescape** used:
![image](https://github.com/gohugoio/hugo/assets/37957537/8197ffaa-4d7e-49e1-944e-a0da8f4d645e)

With code:
https://gist.github.com/vhorvat/f5071d6e4b191d1829641772d94d959b

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
