### ISSUE TITLE
Error: from config: failed to resolve output format "WebAppManifest" from site config

### ISSUE THREAD

**Issue by jianhaizhang** [gohugoio/hugo#11235]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z
</pre>

Hello, when I run `hugo server` on this template: https://github.com/wowchemy/starter-hugo-research-group, I have this error: "Error: from config: failed to resolve output format "WebAppManifest" from site config". Is there a solution to resolve this? 
I run `hugo mod clean --all' (https://wowchemy.com/docs/hugo-tutorials/troubleshooting/#error-failed-to-resolve-output-format), but the same error happens.

**Comment by jmooring** [comment]
Please ask the Wowchemy team:
[https://github.com/wowchemy/wowchemy-hugo-themes/discussions 8](https://github.com/wowchemy/wowchemy-hugo-themes/discussions)

They also have an active Discord channel:
[https://discord.com/invite/z8wNYzb 2](https://discord.com/invite/z8wNYzb)

In the future, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
