### ISSUE TITLE
Add/modify target parameter for attribution link in figure shortcode

### ISSUE THREAD

**Issue by DewaldDeJager** [gohugoio/hugo#11247]
The [`figure`](https://gohugo.io/content-management/shortcodes/#figure) shortcode has a `target` parameter which allows you to specify the `target` attribute of the anchor tag of the image if the `link` parameter is specified. For example:
```html
{{< figure src="elephant.jpg" link="https://example.com" target="_blank" >}}
```

The `figure` shortcode also has the `attr` and `attrlink` parameters which allow you to specify an attribution for the image's source and link to it. This attribution link always uses the default `target` attribute (`_self`).

This change is to propose either changing the default `target` to `_blank` or to add a parameter to the `figure` shortcode such as `attrlinktarget` which allows the user to specify the target for the link. For the sake of backwards-compatibility, I suggest the latter. An example usage could look like:

```html
{{< figure src="elephant.jpg" attr="Courtesy of Example Site" attrlink="https://example.com" attrlinktarget="_blank" >}}
```

The relevant code that would need to be updated:
https://github.com/gohugoio/hugo/blob/79f15be5b0e47a788f62e50ba3e354c247a65f6b/tpl/tplimpl/embedded/templates/shortcodes/figure.html#L21-L25

And the documentation:
https://github.com/gohugoio/hugo/blob/79f15be5b0e47a788f62e50ba3e354c247a65f6b/docs/content/en/content-management/shortcodes.md?plain=1#L122-L126

**Comment by jmooring** [comment]
Thanks for the suggestion, but we're going to decline. First, opening links in a new tab is, in most situations, [not a great idea](https://www.digital.ink/blog/website-links-new-tab/). Second, it is trivial to override the built-in figure shortcode if a site or theme author wishes to provide additional options.
