### ISSUE TITLE
Support markdownify headings in fragments

### ISSUE THREAD

**Issue by davidejones** [gohugoio/hugo#11241]
## Overview

I'd like to propose that the new [page fragments](https://gohugo.io/variables/page/#page-fragments) functionality is expanded to also capture headings rendered via markdownify.

## Example 

**layouts/shortcodes/short1.html**
```html
<div>
  <p>{{- .Inner | markdownify -}}</p>
</div>
```

**layouts/shortcodes/short2.md**
```md
**Bold Text**
{{ .Inner }}
```

**content/_index.md**
```md
---
title: Test
---

# Intro

This is text under h1 heading

## Section

This is text under h2 heading

{{< short1 >}}

## HTML shortcode
This is text under html shortcode heading

{{< /short1 >}}


{{% short2 %}}

## Markdown shortcode
This is text under md shortcode heading

{{% /short2 %}}

```

**layouts/index.html**
```html
{{- define "partials/headings" -}}
  <ul>
    {{- range $k, $v := .data -}}
       <li id="{{ $v.ID | anchorize }}">
          <a href="#{{ $v.ID | anchorize }}">{{ $v.Title }}</a>
          {{- partial "partials/headings" (dict "data" $v.Headings) -}}
       </li>
    {{- end -}}
  </ul>
{{- end -}}

<nav id="TableOfContents">
  {{- partial "partials/headings" (dict "data" .Fragments.Headings) -}}
</nav>
```

## Current Results with hugo 0.115.2
```
- Intro
   - Section
   - Markdown shortcode
```

## Desired Results 
```
- Intro
   - Section
   - HTML shortcode
   - Markdown shortcode
```

**Comment by davidejones** [comment]
possibly should also appear in `{{ .TableOfContents }}` ?

**Comment by jmooring** [comment]
As you have discovered, in this context you must use the `{{% %}}` notation when calling a shortcode. 

When you use the `{{< >}}` notation, we insert a unique placeholder in the content _before_ the the content is rendered, and then replace the placeholder with the rendered shortcode afterwards. Between those two steps is where we capture `.Page.Fragments` and `.Page.TableOfContents`.

You can use the `{{% %}}` when the shortcode contains HTML with this site configuration:

```toml
[markup.goldmark.renderer]
unsafe = true
```

It's not unsafe if _you_ control the content.

If you don't want to do that, you will have to use an alternate method to generate the TOC, either by [parsing content](https://www.veriphor.com/articles/tables-of-content/#method-4-parse-content) or using a JS library such as [tocbot](https://tscanlin.github.io/tocbot/).

**Comment by jmooring** [comment]
Closing. Use the `{{% %}}` notation as described above.
