### ISSUE TITLE
can't access the resources of a file in the parent folder?

### ISSUE THREAD

**Issue by Leroy-X** [gohugoio/hugo#11253]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version [v0.115.3]

</pre>

### Does this issue reproduce with the latest release?

Hi, hugo can't access the resources of a file in the parent folder, something like this (../img/dog.jpg).

 I've searched google for a day and don't know how to fix it.

I want to put all the images in one folder, I found that I can put the images in the static folder. But I am using the Typora editor, the image path will be automatically converted to (../../static/img/dog.png).

So is it possible to access the parent file path through configuration? The mkdocs I used before did not have this problem. I want to try huogo and hope someone can help me.

Thank you so much!

**Comment by Leroy-X** [comment]
I found that I can set "Use Image Root Path" in Typora to use the static folder, but I still hope hugo to be able to access the parent path :P

Thannks!!!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by Leroy-X** [comment]
Solved, I added uglyURLs=true to the config file, don't know why, but everything seems to work, thanks！
