### ISSUE TITLE
quickstart documentation refers to hugo.toml instead of config.toml

### ISSUE THREAD

**Issue by c-hartmann** [gohugoio/hugo#11250]
[Quickstart Doc](https://gohugo.io/getting-started/quick-start/)

refers to `hugo.toml` instead of `config.toml`, where it says:

`echo "theme = 'ananke'" >> hugo.toml`

but

`hugo new site quickstart`

creates `config.toml` only

**Comment by jmooring** [comment]
There's a prerequisites section. Please read it.

https://gohugo.io/getting-started/quick-start/#prerequisites

**Comment by c-hartmann** [comment]
thx Joe. gotit. i've actually used the installation via Linux (Debian/Ubuntu) package manager (`apt`) and that build is on v0.92.2+extended from Jan 2023. i.o.w. i've followed a recommend installation method bit by bit and failed. you might consider a warning note right beside `apt installl hugo` and a note on how to check the required version with `hugo version` to avoid that trap.
