### ISSUE TITLE
Hugo v0.115.3 Disobeys 'disableLiveReload = true' Config Rendering Setting

### ISSUE THREAD

**Issue by hollowaykeanho** [gohugoio/hugo#11259]
Latest update broke the LiveReload settings where it disobeys the already existing configuration not to be rendered. This is not seen in hugo 0.111.3. Check screenshot:

![screenshot](https://github.com/gohugoio/hugo/assets/7259572/a72cbf85-8b13-4a46-8594-4992f20882d6)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.115.3-5c2e014a5150553a9fa4f9c1eb7dc4db89c0f1ab linux/amd64 BuildDate=2023-07-13T16:11:34Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by hollowaykeanho** [comment]
Means when it is set to be disabled, it should not appear. Hence, the disobdience.

**Comment by bep** [comment]
>Means when it is set to be disabled, it should not appear. Hence, the disobdience.

When _what_ is disabled?

**Comment by hollowaykeanho** [comment]
`disableLiveReload = true`. Left side of the setting.

**Comment by bep** [comment]
OK,

Try 

```
hugo server --disableLiveReload
```

I understand that this may have been possible to set in site config in earlier Hugo versions -- and that got lost in the big flag/commands/config consolidation/rewrite.

I will consider adding this to the main config set, but you will get a faster response by just using the flag.

**Comment by hollowaykeanho** [comment]
> I will consider adding this to the main config set, but you will get a faster response by just using the flag.

Understood. Thank you.
