### ISSUE TITLE
Indentation in shortcode definition leads to pre/code

### ISSUE THREAD

**Issue by Signum** [gohugoio/hugo#11272]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.115.3-5c2e014a5150553a9fa4f9c1eb7dc4db89c0f1ab+extended linux/amd64 BuildDate=2023-07-13T16:11:34Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

### Issue

Indented lines in a shortcode definition are sometimes understood as code, and rendered with `<pre>` and `<code>` tags. As if the file is interpreted as markdown and a line starting with 4 spaces is considered preformatted text.

I like to keep my files clean and indented. The only workaround I could find it not indent the lines.

### Steps to reproduce the issue

Create a shortcode file (e.g. bug.html)

```
<p>
  {{ if eq 1 1 }}
    <ul>
      <li>
        Something here.
        Something here.
        Something here.
        Something here.
      </li>
    </ul>
  {{ end }}
</p>
```

Call the shortcode from any page. E.g.:

```
{{% blocks/bug %}}
```

The output will be:

```html
<p>
</p>
<pre><code>&lt;ul&gt;
  &lt;li&gt;
    Something here.
    Something here.
    Something here.
    Something here.
  &lt;/li&gt;
&lt;/ul&gt;
</code></pre>
```

However I expected it to be:

```html
<p>
    <ul>
      <li>
        Something here.
        Something here.
        Something here.
        Something here.
      </li>
    </ul>
</p>
```

As the file is called **.html** I did not expect it to be parsed as markdown.

### Links

I found the issue discussed but not solved at https://discourse.gohugo.io/t/nested-shortcodes-converting-to-pre-code-blocks/28033/2

**Comment by jmooring** [comment]
> As if the file is interpreted as markdown

That's exactly what should happen when you call a shortcode using the `{{% %}}` notation.

If you don't want it interpreted as markdown, call the shortcode using the `{{< >}}` notation. You will need this in your site configuration:

```
[markup.goldmark.renderer]
unsafe = true
```

It is not unsafe if _you_ control the content.

This is simple one page site that clearly shows what's happening:

```text
git clone --single-branch -b hugo-github-issue-11272 https://github.com/jmooring/hugo-testing hugo-github-issue-11272
cd hugo-github-issue-11272
hugo server
```
