### ISSUE TITLE
Unable to hunt down warning

### ISSUE THREAD

**Issue by kurtbruns** [gohugoio/hugo#11276]
### What version of Hugo are you using (`hugo v0.115.4+extended darwin/arm64 BuildDate=unknown`)?

<pre>
$ hugo version
hugo v0.115.4+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

I'm currently getting the warning below when I build my site, but when I search my layouts directory for either ".File" or ".Dir" there are no instances found. Is there something else I should be checking?

```
WARN  .File.Dir on zero object. Wrap it in if or with: {{ with .File }}{{ .Dir }}{{ end }}
```

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

When you create the forum topic, please include a link to the public repository for your project, or a dummy project that demonstrates the warning.
