### ISSUE TITLE
Env HUGO_DISABLELANGUAGES is not working after v0.111.3 with multiple values

### ISSUE THREAD

**Issue by dbaio** [gohugoio/hugo#11278]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.112.0+extended freebsd/amd64 BuildDate=2023-07-20T22:16:20Z-0300 VendorInfo=freebsd

and

$ hugo version
hugo v0.115.4+extended freebsd/amd64 BuildDate=2023-07-20T22:31:17Z-0300 VendorInfo=freebsd
</pre>

### Does this issue reproduce with the latest release?
yes

---

Behavior with v0.111.3:
```
$ hugo version
hugo v0.111.3+extended freebsd/amd64 BuildDate=2023-03-17T03:01:46Z+0000 VendorInfo=freebsd

$ HUGO_DISABLELANGUAGES=" bn-bd da de el es fr hu id it ja ko mn nl pl ru tr zh-cn zh-tw" hugo config | grep -i disablelanguage
disablelanguages: "bn-bd da de el es fr hu id it ja ko mn nl pl ru tr zh-cn zh-tw"

$  HUGO_DISABLELANGUAGES="fr es" hugo config | grep -i disablelanguage
disablelanguages: "fr es"
```

And now with v0.112.0 and v0.115.4:

```
$  hugo version
hugo v0.112.0+extended freebsd/amd64 BuildDate=2023-07-20T22:16:20Z-0300 VendorInfo=freebsd

$ HUGO_DISABLELANGUAGES=" bn-bd da de el es fr hu id it ja ko mn nl pl ru tr zh-cn zh-tw" hugo config | grep -i disablelanguage
disablelanguages = ['bn-bd da de el es fr hu id it ja ko mn nl pl ru tr zh-cn zh-tw']

$ HUGO_DISABLELANGUAGES="fr es" /usr/local/bin/hugo config | grep -i disablelanguage
disablelanguages = ['fr es']
```

```
$ hugo version
hugo v0.115.4+extended freebsd/amd64 BuildDate=2023-07-20T22:31:17Z-0300 VendorInfo=freebsd

$ HUGO_DISABLELANGUAGES=" bn-bd da de el es fr hu id it ja ko mn nl pl ru tr zh-cn zh-tw" hugo config | grep -i disablelanguage
disablelanguages = ['bn-bd da de el es fr hu id it ja ko mn nl pl ru tr zh-cn zh-tw']

$ HUGO_DISABLELANGUAGES="fr es" /usr/local/bin/hugo config | grep -i disablelanguage
disablelanguages = ['fr es']
```

The intended behavior should be `disableLanguages = ['fr', 'es']`, right?
This other way, hugo is building all languages every time.

**Comment by jmooring** [comment]
With v0.112.0 and later...

This works (disables a single language):

```
HUGO_DISABLELANGUAGES="de" hugo
```

This does not (does not disable any language):

```
HUGO_DISABLELANGUAGES="de fr" hugo
```

**Comment by dbaio** [comment]
> With v0.112.0 and later...
> 
> This works (disables a single language):
> 
> ```
> HUGO_DISABLELANGUAGES="de" hugo
> ```
> 
> This does not (does not disable any language):
> 
> ```
> HUGO_DISABLELANGUAGES="de fr" hugo
> ```


I've changed the PR title to 'is not working with multiple values'. Thanks.
