### ISSUE TITLE
Live reload not working windows and WSL2

### ISSUE THREAD

**Issue by agardnerIT** [gohugoio/hugo#11274]
The live reload isn't working for `.md` changes when running on windows.

I've tried with both Windows and via WSL2.

I'm running via `make` (`choco install make -y`).

I've tried all of the following:

```
docker run --rm -it -v C:/path/lifecycle-toolkit/docs/:/src  -p  1314:1314 klakegg/hugo:0.111.3-ext server -D -p 1314

docker run --rm -it -v C:/path/lifecycle-toolkit/docs/:/src  -p  1314:1314 klakegg/hugo:0.111.3-ext server -D -p 1314 --disableFastRender

docker run --rm -it -e HUGO_VERSION_OVERRIDE=0.115.3 -v C:/path/lifecycle-toolkit/docs/:/src -p  1314:1314 klakegg/hugo:0.111.3-ext server -D -p 1314
```

Note: The content directory structure seems odd to me: https://github.com/keptn/lifecycle-toolkit/tree/main/docs

The markdown file I'm changing is thus:

`root/docs/content/en/docs/install/_index.md`

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

v0.111.3
and
v0.115.3

</pre>

### Does this issue reproduce with the latest release?

yes

**Comment by jmooring** [comment]
Use the `--pole` CLI flag.

See this [FAQ](https://gohugo.io/troubleshooting/faq/#why-isnt-hugos-development-server-detecting-file-changes).

> For example, to poll the project files every 700 milliseconds, use --poll 700ms.
