### ISSUE TITLE
Use os.UserCacheDir instead of /tmp is HUGO_CACHEDIR if not set

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11286]

**Comment by bep** [comment]
@jmooring do you agree with this change? I suspect most of the Hugo Modules related issues are related to the OS messing with the `/tmp` dir.

**Comment by jmooring** [comment]
I'm not sure it buys us anything on Linux or Windows. For Linux, `os.TempDir` looks to `$TMPDIR` (which is usually not set), falling back to `/tmp`. On Windows, we're already using the personal temp directory.

If it helps on macOS we should definitely do it. Most of the cache volatility problems that I have seen are on macOS.

Finally, we need to make sure we don't inadvertently revert https://github.com/gohugoio/hugo/pull/11082.

**Comment by bep** [comment]
Not `os.TempDir` ... `os.UserCacheDir`:

https://pkg.go.dev/os#UserCacheDir

>UserCacheDir returns the default root directory to use for user-specific cached data. Users should create their own application-specific subdirectory within this one and use that.
>
>On Unix systems, it returns $XDG_CACHE_HOME as specified by https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html if non-empty, else $HOME/.cache. On Darwin, it returns $HOME/Library/Caches. On Windows, it returns %LocalAppData%. On Plan 9, it returns $home/lib/cache.
>
>If the location cannot be determined (for example, $HOME is not defined), then it will return an error.

But we will fall back to the current logic if the above fails.

And yes, this is probably a MacOS issue, but that's not an uncommon Hugo workstation.

**Comment by jmooring** [comment]
> Not os.TempDir ... os.UserCacheDir

Well, if you used ALL CAPS, highlighted in yellow, and added some emoji, this issue's title would have been a bit clearer.

Sounds good to me.

**Comment by jmooring** [comment]
OK, there's a Linux issue with the Snap package:

```text
$ /snap/bin/hugo
Error: failed to load config: failed to create cache dir: mkdir /home/jmooring/.cache/hugo/: permission denied
```

Strictly confined Snaps, by default, do not have access to "personal files" (`$HOME/.something`). Let me know when you plan to do this, and I will submit a request to access `$HOME/.cache/hugo/*` (not `$HOME/.cache/hugo_$USER/*`). It takes about a week to get approval.

**Comment by jmooring** [comment]
I'm going to request Snap access for `$HOME/.cache/hugo/` anyway. This will make the cache directory visible and easy to manually clear. Currently you have to do something like:

```
sudo rm -rf /tmp/snap-private-tmp/snap.hugo/tmp/hugo_cache_jmooring
```
