### ISSUE TITLE
[v0.115.4]error calling Fingerprint: <nil> can not be transformed

### ISSUE THREAD

**Issue by Xalaok** [gohugoio/hugo#11283]
```
hugo v0.115.4-dc9524521270f81d1c038ebbb200f0cfa3427cc5+extended windows/amd64 BuildDate=2023-07-20T06:49:57Z VendorInfo=gohugoio

Built in 250 ms
Error: error building site: render: failed to render pages: render of "page" failed: "E:\git\blog\layouts\page\links.html:24:112": execute of template failed: template: page/links.html:24:112: executing "main" at <resources.Fingerprint>: error calling Fingerprint: <nil> can not be transformed
```

**Comment by dryscord** [comment]
Before your issue gets closed...

> Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
>
> When you create the forum topic, please include a link to the public repository for your project, or a dummy project that demonstrates the warning.
