### ISSUE TITLE
snap: Allow access to SSH keys and $HOME/.config/hugo

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11288]
Access to SSH keys is required when users have configured Git to use SSH. For example:

```
[url "git@github.com:"]
  insteadOf = https://github.com/
```

See <https://discourse.gohugo.io/t/error-failed-to-load-modules/45477/>

Access to `$HOME/.cache/hugo` is required in support of https://github.com/gohugoio/hugo/issues/11286.

Both require approval from the Snapcraft team.

**Comment by jmooring** [comment]
The updated Snap package is now available on the "edge" channel. It will be available on the "stable" channel with the next Hugo release. To update your Snap installation to the latest "edge" release:

```text
sudo snap refresh hugo --edge
```

Read/write access to `$HOME/.cache/hugo_cache` is enabled by default (auto-connect).

To enable or revoke access to SSH keys (`$HOME/.ssh`):

```text
sudo snap connect hugo:ssh-keys
sudo snap disconnect hugo:ssh-keys
```

See <https://gohugo.io/installation/linux/#snap>

**Comment by jmooring** [comment]
When I refresh I get 0.116.1...

```
sudo snap refresh hugo --edge
hugo (edge) 0.116.1+git3.8fa8ce3e4 from Hugo Authors refreshed
```

Not sure why yours isn't refreshing. Try:

```
sudo snap remove hugo
sudo snap install hugo --edge
```

**Comment by DazWilkin** [comment]
That worked; I needed to `sudo snap remove hugo` first to get `0.116.1...`

I've reverted git config to include:

```
[url "git@github.com:"]
        insteadOf = https://github.com/
```

And I'm able to deploy.

Thank you for the excellent support!
