### ISSUE TITLE
server: Set interface and port via environment variables

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11284]
`HUGO_SERVERINTERFACE` would do the same as the `--bind` CLI flag.
`HUGO_SERVERPORT` would do the same as the `--port` CLI flag.

This is, obviously, merely for convenience. You could, for example, set `HUGO_SERVERINTERFACE=0.0.0.0` within a Docker container, which simplifies the container entrypoint and CLI flags.

**Comment by bep** [comment]
Would doing it like `GOFLAGS` in Go work:

```
GOFLAGS="-mod=mod" 
```

So,

```
HUGOFLAGS="--port=1414 --bind=0.0.0.0" 
```

?

**Comment by jmooring** [comment]
To verify, these would be appended (to the end) of the command, correct?

Meaning I would get `hugo server --port=1414 --bind=0.0.0.0` instead of `hugo --port=1414 --bind=0.0.0.0 server`.

If true, this would be great. Great solution.

**Comment by jmooring** [comment]
Would the `HUGOFLAGS="--port=1414 --bind=0.0.0.0"` approach break if the command doesn't take those flags? For example:

```
hugo --bind=0.0.0.0
```

Error: command error: unknown flag: --bind
