### ISSUE TITLE
Nested shortcode enables Markdown proicessing although in HTML template

### ISSUE THREAD

**Issue by fnordfish** [gohugoio/hugo#11298]
I'm using pure HTML content files, but out of habit (and also helping with code highlighters) the `{{%` notation for shortcodes.  
While normally, this works just fine and the `.Inner` of a shorcode is just treated as pure HTML, when I use the same shortcode inside another one, Markdown processing is suddenly enabled.

### Sample

Shortcode templates:

`shortcodes/outer.html`:
```
<div class="outer">
    <h3>Hello</h3>
    <div class="inner">
        {{ .Inner }}
    </div>
</div>
```

`shortcodes/foo.html`
```
<a href="{{ .Get 0 }}">{{ .Inner }}</a>
```

`content/sample.html`
```
{{% foo "https://example.com" %}}**Example**{{% /foo %}}
{{% outer %}}
  **TEST**
  {{% foo "https://example.com" %}}Example{{% /foo %}}
  {{< foo "https://example.com" >}}**Example**{{< /foo >}}
{{% /outer %}}

```

Produces this HTML:
```html
<a href="https://example.com">**Example**</a>
<div class="outer">
  <h3>Hello</h3>
  <div class="inner">

    **TEST**
    <a href="https://example.com">
      <p>Example</p>
    </a>
    <a href="https://example.com">**Example**</a>

  </div>
</div>
```

The very first link works as expected.  
The content of the first link inside the `outer` shortcode got wrapped in an extra `<p>` due to markdown processing.  
The last link, disabling further rendering using `{{<` also works as expected.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.104.3-58b824581360148f2d91f5cc83f69bd22c1aa331 linux/amd64 BuildDate=2022-10-04T14:25:23Z VendorInfo=hugoguru
</pre>

### Does this issue reproduce with the latest release?

Yes (`hugo v0.115.4-dc9524521270f81d1c038ebbb200f0cfa3427cc5 linux/amd64 BuildDate=2023-07-20T06:49:57Z VendorInfo=gohugoio`)

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
