### ISSUE TITLE
Version in apt repository manager is very old

### ISSUE THREAD

**Issue by felix-seifert** [gohugoio/hugo#11299]
The website mentions the option to [install hugo via the apt package manager](https://gohugo.io/installation/linux/#debian). When I search for hugo in the apt package manager, I see the latest version is `0.92.2`, which was released in February last year. The current version of hugo is `v0.115.4` and was released last week.

Is it possible to **publish a more recent version of hugo in the apt package manager**? The current version might scare new adopters as even [the quickstart guide mentions the required minimum version to be `v0.112.0`](https://gohugo.io/getting-started/quick-start/#prerequisites). Getting a new version differently is obviously not as easy and convenient.

**Comment by jmooring** [comment]
It depend on your OS version. For example...

Ubuntu 23.04 (Lunar Lobster)
<https://packages.ubuntu.com/search?suite=lunar&arch=any&searchon=names&keywords=hugo>
0.110.0

Ubuntu 22.04.2 (Jammy Jellyfish)
<https://packages.ubuntu.com/search?suite=jammy&arch=any&searchon=names&keywords=hugo>
0.92.2

We try to alert users to these differences in the [installation instructions](https://gohugo.io/installation/linux/#repository-packages). Specifically:

![image](https://github.com/gohugoio/hugo/assets/335669/2e56d99e-baf1-4539-b028-be4db66272ec)
