### ISSUE TITLE
Camel-case taxonomy terms not working

### ISSUE THREAD

**Issue by dominikbraun** [gohugoio/hugo#11305]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.115.1+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

---

### Description

A taxonomy with a camel-cased term, for example `goTutorial`, doesn't work in templates. I'm not sure whether this is intended as I couldn't find any rules about taxonomy names – but I find the behavior surprising.

### Reproduce the issue

Add a taxonomy to the Hugo configuration.

```toml
[taxonomies]
series = 'series'
```

Use the taxonomy in a content file and assign a camel-cased term.

```yaml
---
series:
- goTutorial
---
```

Use the term for iterating over all posts with that term:

```html
<ul>
    {{ range .Site.Taxonomies.series.goTutorial }}
        <li><a href="{{ .Page.RelPermalink }}">{{ .Page.Title }}</a></li>
    {{ end }}
</ul>
```

Nothing will be displayed. **The template will only work when `goTutorial` is renamed to `gotutorial` or `go_tutorial`.**

**Comment by jmooring** [comment]
The identifier is lowercase unless `disablePathToLower` is `true` in your site configuration, but be aware of https://github.com/gohugoio/hugo/issues/9171.

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by dominikbraun** [comment]
Thanks!
