### ISSUE TITLE
Documented workflow for 'Host on GitHub Pages' failing on 'Build with Hugo' step

### ISSUE THREAD

**Issue by mojochao** [gohugoio/hugo#11321]
Following the directions at https://gohugo.io/hosting-and-deployment/hosting-on-github/, I'm seeing the following in the build log.

```
hugo \
    --gc \
    --minify \
    --baseURL "https://sambatv.github.io/cap-portal/"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    HUGO_VERSION: 0.116.1
    GITHUB_PAGES: true
    HUGO_ENVIRONMENT: production
    HUGO_ENV: production
  
Start building sites … 
hugo v0.116.1-[3](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:3)e1ea030a5897addaf9d113d0826709fe07f77c0+extended linux/amd6[4](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:4) BuildDate=2023-08-01T07:24:[5](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:5)4Z VendorInfo=gohugoio

ERROR render of "page" failed: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/blog/baseof.html:33:7": execute of template failed: template: blog/single.html:33:7: executing "blog/single.html" at <partial "scripts.html" .>: error calling partial: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
ERROR render of "page" failed: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/docs/baseof.html:30:7": execute of template failed: template: docs/single.html:30:7: executing "docs/single.html" at <partial "scripts.html" .>: error calling partial: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
ERROR render: failed to render pages: render of "page" failed: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/_default/baseof.html:1[6](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:6):[7](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:7)": execute of template failed: template: _default/search.html:16:7: executing "_default/search.html" at <partialCached "scripts.html" .>: error calling partialCached: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/partials/scripts.html:[8](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:8)4:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
Total in 821 ms
Error: error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): "/home/runner/work/cap-portal/cap-portal/themes/docsy/assets/scss/main.scss:1:1": File to import not found or unreadable: ../vendor/bootstrap/scss/functions.
Error: Process completed with exit code 1.
```

If I run that same hugo command locally in my repository, it works.

Note that this is a private repo, but it's a Docsy themed site with the docsy theme added to the `themes` directory.
I do not have a `vendor` directory in the repo root, but the following vendor directories exist in my `./themes/docsy/node_modules` directory.

```
$ find . -name vendor -type d
./themes/docsy/node_modules/bootstrap/scss/vendor
./themes/docsy/node_modules/chalk/source/vendor
./themes/docsy/node_modules/hugo-extended/vendor
```

I am using the following versions:
* hugo 0.116.1 (extended)
* docsy 0.7.1

How might I go about debugging this issue?

Many thanks in advance.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by zyestin** [comment]
> Following the directions at https://gohugo.io/hosting-and-deployment/hosting-on-github/, I'm seeing the following in the build log.
> 
> ```
> hugo \
>     --gc \
>     --minify \
>     --baseURL "https://sambatv.github.io/cap-portal/"
>   shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
>   env:
>     HUGO_VERSION: 0.116.1
>     GITHUB_PAGES: true
>     HUGO_ENVIRONMENT: production
>     HUGO_ENV: production
>   
> Start building sites … 
> hugo v0.116.1-[3](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:3)e1ea030a5897addaf9d113d0826709fe07f77c0+extended linux/amd6[4](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:4) BuildDate=2023-08-01T07:24:[5](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:5)4Z VendorInfo=gohugoio
> 
> ERROR render of "page" failed: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/blog/baseof.html:33:7": execute of template failed: template: blog/single.html:33:7: executing "blog/single.html" at <partial "scripts.html" .>: error calling partial: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
> ERROR render of "page" failed: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/docs/baseof.html:30:7": execute of template failed: template: docs/single.html:30:7: executing "docs/single.html" at <partial "scripts.html" .>: error calling partial: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
> ERROR render: failed to render pages: render of "page" failed: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/_default/baseof.html:1[6](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:6):[7](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:7)": execute of template failed: template: _default/search.html:16:7: executing "_default/search.html" at <partialCached "scripts.html" .>: error calling partialCached: "/home/runner/work/cap-portal/cap-portal/themes/docsy/layouts/partials/scripts.html:[8](https://github.com/SambaTV/cap-portal/actions/runs/5734839581/job/15541656444#step:8:8)4:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
> Total in 821 ms
> Error: error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): "/home/runner/work/cap-portal/cap-portal/themes/docsy/assets/scss/main.scss:1:1": File to import not found or unreadable: ../vendor/bootstrap/scss/functions.
> Error: Process completed with exit code 1.
> ```
> 
> If I run that same hugo command locally in my repository, it works.
> 
> Note that this is a private repo, but it's a Docsy themed site with the docsy theme added to the `themes` directory. I do not have a `vendor` directory in the repo root, but the following vendor directories exist in my `./themes/docsy/node_modules` directory.
> 
> ```
> $ find . -name vendor -type d
> ./themes/docsy/node_modules/bootstrap/scss/vendor
> ./themes/docsy/node_modules/chalk/source/vendor
> ./themes/docsy/node_modules/hugo-extended/vendor
> ```
> 
> I am using the following versions:
> 
> * hugo 0.116.1 (extended)
> * docsy 0.7.1
> 
> How might I go about debugging this issue?
> 
> Many thanks in advance.

Hi, how did you fix it
