### ISSUE TITLE
Enabling relativeURLs still results in absolute URL in OpenGraph and Twitter Card template

### ISSUE THREAD

**Issue by chuanhhoang** [gohugoio/hugo#11338]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.116.1

</pre>

### Does this issue reproduce with the latest release?
yes

```
  <link rel="canonical" href="./" />
  
    <link
      href="./index.xml"
      rel="alternate"
      type="application/rss+xml"
      title="my new hugo site"
    />
  

  
  <meta property="og:type" content="website" />
  <meta property="og:description" content="" />
  <meta property="og:title" content="my new hugo site" />
  <meta property="og:site_name" content="my new hugo site" />
  <meta property="og:image:type" content="image/jpeg" />
  <meta property="og:url" content="/" />
  <meta property="og:locale" content="en-us" />

  

  
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="my new hugo site" />
  <meta name="twitter:description" content="" />
  <meta name="twitter:domain" content="/" />
```

The og:url and twitter:domain are supposed to be "./" as in  <link rel="canonical" href="./" />

**Comment by jmooring** [comment]
See <https://gohugo.io/content-management/urls/#relative-urls>

First, you really don't want to enable `relativeURLs` unless you are creating a serverless site, navigable via the file system.

Second, the `relativeURLs` search/replace only considers `action`, `href`, `src`, `srcset`, and `url` attributes, as documented.

Third, Hugo's [builtin twitter_cards template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html) does not write a "twitter:domain" `meta` element, so you must be using a custom template, perhaps provided by your theme.

Fourth, excluding scheme and host from `twitter:domain` or `og:url` doesn't make any sense. These should be absolute URLs (e.g., `https://example.org/`).

Finally, if you are using Hugo's built-in [opengraph template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html), and you are seeing this...

```
<meta property="og:url" content="/" />
``` 

...it means that the `baseURL` in your site configuration is incorrect. See [docs](https://gohugo.io/getting-started/configuration/#baseurl).
