### ISSUE TITLE
Bug with using .Scratch and --disableFastRender

### ISSUE THREAD

**Issue by docelic** [gohugoio/hugo#11350]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.117.0-DEV-641390f8f5f5b0ffd57d0fea42ae97d22ab3741e+extended linux/ppc64le BuildDate=2023-08-05T09:40:18Z
</pre>

### Does this issue reproduce with the latest release?
<pre>
$ hugo version
hugo v0.117.0-DEV-7d74cd0cc88716fba813e9e2e229c3b22b828b5f+extended linux/ppc64le BuildDate=2023-08-08T07:13:17Z
</pre>

### Setup

I have a shortcode which generates HTML links. Its side effect is that it saves all links it generates on a page to page's `.Scratch`. Here's the code:

```
{{ $url := .Get 0 }}
{{ $title := or (.Get 1) $url }}
{{ $.Page.Scratch.SetInMap "links" $url $title }}
<a href="{{ $url }}">{{ $title }}</a>
```

Then I have code which, at the end of the page, prints the list of URLs that were collected during page processing.
The code is:

```
{{ $links := .Scratch.Get "links" }}
{{ if $links }}
    {{ range $url, $title := $links }}
    {{ $.Scratch.Add "li" 1 }}
    {{ $.Scratch.Get "li"}}. {{$title}} - {{$url}}<br>
    {{ end }}
    </p>
</div>
{{end}}
```

Then I start the server with options:

```
hugo server  --cleanDestinationDir  \
  --forceSyncStatic --gc -w --disableBrowserError \
  --ignoreCache --disableFastRender --disableLiveReload \
  --renderStaticToDisk --renderToDisk
```

### Problem Description

When I visit the page with links after server start, content displays correctly - as expected.

But if I make any change to any of the site pages, this block of links from the page disappears.

The only way to get it back is to restart the server again.

There are no any errors or unusual messages printed in server log.

I have traced the problem to option `--disableFastRender `. If I do not specify this option, I can modify site pages OK and the block always stays visible/generated. If I do specify it, like shown above, then the block disappears upon any change to the site pages.

Any comments or confirmation would be appreciated, thanks.

**Comment by bep** [comment]
There's a long story here, but can you try to replace your `.Scratch` usage with `.Store`. The only difference is that the latter survives rebuilds.

**Comment by docelic** [comment]
Indeed, with .Store it seems to work. Thank you.

**Comment by jmooring** [comment]
Using .Store is the correct and [documented](https://gohugo.io/methods/page/store/) approach:

> The Store method on a Page object creates a persistent [scratch pad](https://gohugo.io/getting-started/glossary/#scratch-pad) to store and manipulate data. In contrast with the [Scratch](https://gohugo.io/methods/page/scratch/) method, the scratch pad created by the Store method is not reset on server rebuilds.
