### ISSUE TITLE
Extend default theme templates

### ISSUE THREAD

**Issue by ubitux** [gohugoio/hugo#11358]
The default theme proposed by the command `hugo new theme` is kind of light to say the least. There is some content in `baseof.html` referencing a few other (empty) partials: I believe it would make sense to complete these files just enough so that it creates a crude but still functional skeleton.

I'm thinking in particular of:

1. `head.html` (which is already created but empty) could contain something like (and probably other meta such as `.Description`, `.Keywords`, ...):
```html
<head>
  <title>{{block "title" .}}{{with .Title}}{{.}} - {{end}}{{.Site.Title}}{{end}}</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
```
2. `baseof.html` could show how to make use of `.Site.LanguageCode` in the `<html>` tag (and maybe `GetLanguageDirection`?)
3. `header.html` (which is already created but empty) could contain a basic list for the menus (`.Site.Menus`)
4. `single.html` and `list.html` could simply have a `.Content`
5. `list.html` could make use of the pages thing

There is no need for style or anything fancy, but simply show how the information provided by the engine is supposed to be used. This would help theme creators make best use of the engine features as well as providing a barely functional out of the box experience.

**Comment by bep** [comment]
I agree. 

2. it needs to be `.Language.LanguageCode` and `.Language.LanguageDirection` I think.
4. single.html, list.html, index.html all needs to have a `main` define.

Ideally both `hugo new theme` and `hugo new site` should get something runnable, so maybe also add a couple of dummy pages.

On the technical level the `hugo new theme/site` needs to be reworked a little so they can read the "scheleton templates" from a Go embedded fs, which should make it much easier to edit/maintain.

**Comment by jmooring** [comment]
> read the "scheleton templates" from a Go embedded fs

I think at one point we were considering [txtar](https://pkg.go.dev/golang.org/x/tools/txtar#hdr-Txtar_format) for this. Do you prefer the embedded fs approach?

**Comment by bep** [comment]
>Disregard. The embedded fs approach is much easier to maintain. I'm going to take a stab at this.

Yea, there may be use cases for txtar, but it's pretty nice to have all the files expanded to a folder and just edit (and format ...) them.
