### ISSUE TITLE
site.LastChange ignores files in content root

### ISSUE THREAD

**Issue by weddige** [gohugoio/hugo#11354]
`.Site.LastChange` ignores pages, that are not lists. The following picture shows a minimal reproducible example:

![image](https://github.com/gohugoio/hugo/assets/1119426/70b0247d-50ae-4f3a-b5ac-2eef6283cf81)

The content looks like this:

 * content
   * _index.md (lastmod: 2020-02-01)
   * foo.md (lastmod: 2020-02-02)
   * blub
     * index.md (lastmod: 2020-02-03)
   * bar
     * _index.md (lastmod: 2020-01-01)
     * fight.md (lastmod: 2020-01-02)

`.Site.LastChange` only considers the folder `/content/bar/`, where it correctly takes `lastmod` from the latest child `/content/bar/fight.md`.

All the other files, that have a more recent `lastmod` are ignored. If the folder `/content/bar/` is deleted `.Site.LastChange` becomes `0001-01-01 00:00:00 +0000 UTC` instead of using any of the other dates.

If it helps, here are the files to my example: [hogo_lastchange_mre.zip](https://github.com/gohugoio/hugo/files/12319371/hogo_lastchange_mre.zip)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended windows/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
This is fixed in v0.123.0.
