### ISSUE TITLE
Expose antonmedv/expr support as a template function. 

### ISSUE THREAD

**Issue by khayyamsaleem** [gohugoio/hugo#11362]
See https://github.com/antonmedv/expr . 

As soon as I saw this project, I thought of using it to bring `eval` to hugo templates. This will allow a more expressive syntax for a lot of data manipulation tasks that are often found in hugo templates, as well as give an embedded DSL capability to hugo beyond what's offered by the template functions today.

Semantics could be something like:

```html
<div>
   {{ $tweets := getJSON "https://x.com/..." }}
   <!-- the special part -->
   {{ $shorties := evalexpr "all(Tweets, .Size <= 240)"  (dict "Tweets" $tweets) }} 
   {{ range $shorties }}
      <div>{{ .content }}</div>
   {{ end }}
</div>
```

**Comment by khayyamsaleem** [comment]
I wonder if a feature like this belongs in hugo-extended instead of hugo? WDYT, community?

**Comment by khayyamsaleem** [comment]
was this closed as completed? or closed as declined? sorry; been meaning to follow up with more meaningful examples but have been busy. happy to reopen a new issue when i can express the request better.

**Comment by jmooring** [comment]
Declined to lack of follow-up.
