### ISSUE TITLE
modules: Leave newly-created directories in the module cache read-write

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11369]
Although we can use `hugo mod clean` (current project) or `hugo mod clean --all` (all projects) to clear the module cache, sometimes I want to remove the entire hugo cache (e.g., `rm -rf $HOME/.cache/hugo_cache/`). But this fails because the module cache directories are read-only, so I need to do it with elevated permissions (e.g., `sudo rm -rf $HOME/.cache/hugo_cache/`).

https://github.com/gohugoio/hugo/blob/90944aa261acf596af774dcea0db1fc31dccc973/modules/client.go#L459

Is there any downside to:

```text
args := []string{"mod", "download", "-modcacherw"}
```

> -modcacherw
		leave newly-created directories in the module cache read-write
		instead of making them read-only.

**Comment by bep** [comment]
>Is there any downside to:

I suspect the original motivation was to protect against (accidental or not) tampering, but I think having this enabled is causing more issues than it solves.

There's one practical problem with this, though; In the "cache clean" logic, there's a special code path for this cache, which changes permission before removing. I guess we need to wait "some time" before removing that logic, but we should at least test that it works in the new setup.
