### ISSUE TITLE
Convert latex formula to mathml

### ISSUE THREAD

**Issue by mek-yt** [gohugoio/hugo#11363]
Hi,

I really wanted to convert latex formula server side on my hugo website. A major point for refusal of previous proposal was to only include Go dependency to hugo. So when I found [latex2mathml](https://github.com/roniemartinez/latex2mathml) in Python last weekend I choose to translate it to Go [latex2mathml](https://git.sr.ht/~mekyt/latex2mathml).

I wonder if it is okay to include this library in hugo, maybe like a template function `{{ .Params.Formula | latex2mathml | safeHTML }}`. I will be able to create a markup and shortcode with that. If it is okay, where can I create it in this repository I am a little lost.

Thanks

**Comment by neruyzo** [comment]
I tried the first solution but maybe it's firefox/wayland but the SVG from vercel API look compress compare to the mathml version.

The second and third point still use JS from my perspective but the detection of math expression in markdown could be useful.

I am for an automatic detection of expression in markdown and letting the developper choose between MathJAX, KaTeX, vercel API or mathml but having a template function for mathml can be enough for me now.

**Comment by jmooring** [comment]
Closing in favor of #10894.
