### ISSUE TITLE
Issue with hugo new --kind Command

### ISSUE THREAD

**Issue by huyixi** [gohugoio/hugo#11377]
### What version of Hugo are you using (`hugo version`)?

hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended darwin/arm64 BuildDate=2023-08-07T12:49:48Z VendorInfo=brew

<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release?
Yes.

Description:

I've encountered an unexpected behavior when using the hugo new --kind command. Despite specifying the correct archetype path, Hugo defaults to using the default.md archetype.

Steps to Reproduce:

Create a custom archetype, e.g., weekly.md, inside the archetypes directory.
Use the script or command to generate new content using the hugo new --kind archetypes/weekly.md format.
Observe that the generated content is based on default.md and not weekly.md.
Expected Behavior:
When specifying the --kind flag and pointing to a valid archetype, Hugo should generate content based on that archetype.

Actual Behavior:
Hugo defaults to the default.md archetype regardless of the specified archetype using the --kind flag.

Environment:

Operating System: MacOS
I've also ensured that the archetype paths are correct, and the archetypes exist in the specified location. Despite this, Hugo does not seem to recognize or use the specified archetype.

**Comment by jmooring** [comment]
The syntax is:

```text
hugo new content --kind weekly posts/post-1.md
```

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
