### ISSUE TITLE
Some times the browser get stuck in the error view

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11378]
I'm not sure when it happens, but it's annoying as it requires a restart. I have seen this while editing CSS files built with Tailwind. Not sure what, but I need to fix it.

**Comment by broughtupsy** [comment]
I have noticed this issue very consistently for a long time, even with new sites. But I also use Tailwind, so that must be it!

**Comment by joaormatos** [comment]
This can be quite annoying when getting started with Hugo and routinely breaking things in the frontmatter.

For now I'm using this `expect` script as a workaround.
I still have to manually reload the page in the web browser, though...

```expect
#!/usr/bin/expect

set command [list hugo server -D]
set string_to_look_for "unmarshal failed: toml:"
# Disable input timeout
set timeout -1

while {1} {

    puts "Starting the process."
    spawn {*}$command

    expect {
        -re $string_to_look_for {
            puts "Restarting the process..."
            exec kill [exp_pid]
            close
        }
        eof {
            puts "Process exited. Restarting..."
        }
    }

    sleep 1
}
```
Usage:
1. Save this script to `hugo_server.exp`, next to your `hugo.toml`
2. `chmod +x hugo_server.exp`
3. `./hugo_server.exp`

**Comment by bep** [comment]
Thanks for the heads up, I will fix this in the next Hugo release.
