### ISSUE TITLE
Hugo Stats generates encoded class names

### ISSUE THREAD

**Issue by tfsomrat** [gohugoio/hugo#11371]
Hi, I am using the latest version of hugo v0.117.0_extended with tailwind CSS. when I use tailwind arbitrary classes like `[&>p]:text-red-600`, then hugo_stats.json generates class like `[\u0026\u003ep]:text-red-600`. and obviously it does not work. I need exact same class name that I write to generate tailwind CSS styles. hope you will resolve this issue soon. thanks

**Comment by bep** [comment]
It's not uncommon to encode (and then decode) these entities when writing JSON, but I think there is a `SetEscapeHTML` option that we probably should set to `false`.
