### ISSUE TITLE
hugo server remains active using chrome cache?

### ISSUE THREAD

**Issue by djsamperi** [gohugoio/hugo#11397]
### What version of Hugo are you using (`hugo version`)? 
v0.92.2-extended under Ubuntu Linux

### Does this issue reproduce with the latest release?
Did not test with latest release

When testing hugo server locally, Ctrl-C terminates the server (as shown by ps command),
but the chrome session continues to respond as if hugo server is still runnng.

Even after a system reboot, chrome behaves as if hugo server is still running with
port localhost:1313.

The work-around is to clear chrome's cache, but this does not answer the question,
how can cached data permit chrome to respond as if hugo server is still running, unless
it caches the hugo running binary? That would be difficult because the running binary seems
to require 3GB of RAM.

**Comment by jmooring** [comment]
This is a Chrome issue, not a Hugo issue. 

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
