### ISSUE TITLE
IsAncestor desc error/contradiction in release notes v0.100.0

### ISSUE THREAD

**Issue by Kissaki** [gohugoio/hugo#11399]
*This is a bug report for the release notes text, not the software itself.*

The [v0.100.0 release notes](https://github.com/gohugoio/hugo/releases/tag/v0.100.0) state:

> The methods on Page IsDescendant and IsAncestor now returns true for itself, which is obviously the correct behaviour. 

The linked ticket #9925 describes the opposite though.

The release notes text is wrong, right? It should say "now returns false for itself"!?

That would match the current versions behavior too.

**Comment by jmooring** [comment]
Fixed.
