### ISSUE TITLE
Hugo using all the system resources

### ISSUE THREAD

**Issue by YasirRWebDesigner** [gohugoio/hugo#11398]
**Laptop** HP EliteBook 840 G3
**OS** ArcoLinux
**CPU** i5-6300U
**RAM** 8GB
**HUGO** v0.116.1+extended linux/amd64
 
I was working today on my company website and like an hour ago my laptop started showing 99% CPU/Memory usage I couldn't do anything. I had to force restart the laptop. the last it happened I couldn't check what caused it. I resumed working but it just happened again and Hugo was using all the resources.

![swappy-20230826_105240](https://github.com/gohugoio/hugo/assets/32537564/11bfeec5-61be-4782-a37c-0537550cd262)

I was running ```hugo server --watch --verbose --debug --noHTTPCache``` in the built vscode terminal. anyone got any ideas how to fix it or avoid this issue? I am willing to give any logs. nesscary

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
