### ISSUE TITLE
Resources.PostCSS does not work on WSL2

### ISSUE THREAD

**Issue by michael-markl** [gohugoio/hugo#11400]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended linux/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

### Bug description

Using Hugo in a Ubuntu 22.04 WSL2 under Windows 10, together with a postcss asset & config, I get the following error:

```sh
$ hugo
Start building sites …
hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended linux/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=gohugoio

WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
Total in 2566 ms
Error: error building site: POSTCSS: failed to transform "style.css" (text/css): '\\wsl.localhost\Ubuntu\home\markl07\git\hugo-postcss-wsl'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Input Error: Did not receive any STDIN
```

The npm packages `postcss` and `postcss-cli` were locally installed using `npm i`.

To reproduce this error, I have set up a minimal repo here: https://github.com/michael-markl/bug-hugo-postcss-wsl

The expected output is:
```sh
$ hugo
Start building sites … 
hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended linux/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=snap:0.117.0

WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN  
-------------------+-----
  Pages            |  4  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 1270 ms
```

**Comment by jmooring** [comment]
@michael-markl I am unable to reproduce the problem.

```text
C:\Users\joe>wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Running         2
```

Within WSL ...

```text
$ lsb_release -d
Description:    Ubuntu 22.04.3 LTS

$ hugo version
hugo v0.117.0 ...

$ git clone --recurse-submodules https://github.com/michael-markl/bug-hugo-postcss-wsl
$ cd bug-hugo-postcss-wsl/
$ npm ci
$ hugo

WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN
-------------------+-----
  Pages            |  4
  Paginator pages  |  0
  Non-page files   |  0
  Static files     |  0
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Total in 417 ms
```

**Comment by michael-markl** [comment]
Thank you for investigating!

When I have time, I will try and investigate the reason for my error message.

My version of windows and wsl are as follows: (I am unsure if a newer version of WSL (if there is one) or Windows fixed the issue)

```PS
PS C:\Users\markl07> wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3324
```

**Comment by jmooring** [comment]
@michael-markl If you haven't done so already, I suggest that you perform the same steps that I did, within WSL:

```text
$ git clone --recurse-submodules https://github.com/michael-markl/bug-hugo-postcss-wsl
$ cd bug-hugo-postcss-wsl/
$ npm ci
$ hugo
```

The error message in your original post contains "'\\wsl.localhost\Ubuntu\home\markl07\git\hugo-postcss-wsl'", which doesn't make sense (to me) if all files are located and processed within the Ubuntu VM.

**Comment by jmooring** [comment]
> CMD.EXE was started with the above path as the current directory.

I don't understand this message. Why would CMD be started in a Linux VM? You might also try this with a virgin VM, or removing any wsl configuration you may have created. In any event, like I said, I can't reproduce this with a clean system.

**Comment by michael-markl** [comment]
I could figure out my problem now: I forgot that I did not have a node installation inside WSL, but only on the host Windows system.
So any call to npm / node went through the host Windows system, and not only through the WSL.

The solution was easy: Install node on WSL as well.

Thank you @jmooring for helping out!
