### ISSUE TITLE
Impossible to install Hugo most recent version

### ISSUE THREAD

**Issue by carlitador** [gohugoio/hugo#11404]
Hi

I use a laptop with linux mint 19.3. I tried installing hugo via apt install hugo, but this always pointing to 0.4 version (quite outdated).
I tried downloading both amd64 and arm64 packages but I wasn't able to get them running on my machine, which have a x86_64
architecture

Any idea of a workaround ?
thanks

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
