### ISSUE TITLE
SIGSEGV unexpected signal during runtime execution

### ISSUE THREAD

**Issue by Giom-fm** [gohugoio/hugo#11413]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version: hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended linux/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes and v0.113

Building my website results in a SIGSEGV. When repeating the build step without cleaning, its working again.
Logs: [hugo.log](https://github.com/gohugoio/hugo/files/12480088/hugo.log)
The website is a little bigger. Could this be an issue?

|                  |      |
| ---------------- | ---- |
| Pages            | 114  |
| Paginator pages  | 49   |
| Non-page files   | 212  |
| Static files     | 107  |
| Processed images | 3339 |
| Aliases          | 10   |
| Sitemaps         | 1    |
| Cleaned          | 238  |

**Comment by bep** [comment]
As I see it, you seem to have hit a bug in the now deprecated libsass library, which is unlikely to be fixed. You may be able to fix this by adjusting/simplifying your SASS/SCSS, but I would recommend start using Dart Sass (see above).

**Comment by Giom-fm** [comment]
The theme I use currently still relies on libsass. Changing it manually has resulted in errors. I am, due to lack of experience in webdesign, not able to fix the errors. I will inform the author of the theme.
Thanks
