### ISSUE TITLE
Add command hugo new tutorial with a simple site skeleton for beginners.

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#11428]
As [mentioned in the forums](https://discourse.gohugo.io/t/not-a-hugo-issue/45971/14), I think there should be a simple command that creates a skeleton site for new Hugo users to start hacking on. The existing `hugo new site` command doesn't provide quite enough structure for someone new to Hugo to know where to begin. I propose there should be `hugo new tutorial` which creates a very small site that demonstrates a few basic features of Hugo, like baseof.html, the homepage, a content page, and including CSS and JS assets.

**Comment by jmooring** [comment]
Other than the command itself, how is what you propose different from:


```text
hugo new site mysite
cd mysite
hugo new theme mytheme
echo "theme = 'mytheme'" >> hugo.toml
hugo server
```

or

```
hugo new theme mysite --themesDir .
cd mysite
hugo server
```

**Comment by jmooring** [comment]
Are you testing with version 0.118.0 or later? We have tests for this.

**Comment by carlmjohnson** [comment]
I was on 117. I just upgraded. Wow, this new theme is great! My only suggestion is to make it a top level command so that it can hook into the docs like "First , run `hugo new tutorial` in your terminal. Next, …" for a first run tour of Hugo.

**Comment by jmooring** [comment]
> make it a top level command

Covered by #11373.
