### ISSUE TITLE
Scrambled HTML in the codeblock everytime I used the highlight template function

### ISSUE THREAD

**Issue by FZhg** [gohugoio/hugo#11448]
### What version of Hugo are you using (`hugo version`)?
v0.92.0

### Does this issue reproduce with the latest release?
Haven't tried

![image](https://github.com/gohugoio/hugo/assets/22489650/aa12189c-92c4-40ad-a7ae-7f8fa609ba89)

```
<div class="td-card card border me-4">
    <div class="card-header bg-white">
        <a href="{{$ghlink}}" download="{{$filename}}" class="text-end">
            <i class="fa-solid fa-file-arrow-down"></i>
            {{$filename}}
        </a>
    </div>
    <div class="card-body code p-0 m-0">
      {{ with $code -}}
        {{ highlight . $codelang "" -}}
      {{ end -}}
    </div>
  </div>
```

**Comment by jmooring** [comment]
This is not a bug.

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
