### ISSUE TITLE
Module configuration prevent initializing modules (`hugo mod init`)

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#11458]
```sh
$ cat config/_default/hugo.yaml
module:
  imports:
    - path: github.com/hbstack/theme-start

$ hugo mod init example.com/user/repo
Error: failed to load modules: module "github.com/hbstack/theme-start" not found in "/tmp/start-page/themes/github.com/hbstack/theme-start"; either add it as a Hugo Module or store it in "/tmp/start-page/themes".: module does not exist
```

Hi, I encountered an strange issue that couldn't `hugo mod init` with existing module configurations, have to remove/comment those imports first.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended linux/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by Marzal** [comment]
Same problem here with:
hugo v0.123.8+extended linux/amd64
docsy theme
Example: https://gitlab.com/Marzal/mundolibre/-/jobs/6357113230

**Comment by Sapp00** [comment]
same issue for me with any mod I found so far (themes like hugo-xmin, gethugothemes-modules,..).
Same on MacOS with Hugo v0.125.6+extended darwin/arm64 and WSL hugo v0.125.6 linux/amd64

**Comment by aamnah** [comment]
Experiencing same on `hugo v0.127.0-74e0f3bd63c51f3c7a0f07a7c779eec9e922957e+extended linux/amd64 BuildDate=2024-06-05T10:27:59Z VendorInfo=snap:0.127.0`
