### ISSUE TITLE
Minify breaks Mermaid.js graphs.

### ISSUE THREAD

**Issue by aurelienpierre** [gohugoio/hugo#11454]
When building the website with `hugo --minify`, Mermaid.js syntax is broken and graphs show an error. Mermaid relies on Markdown-ish syntax and needs tabs/spaces.

I use the following template in `layout/_default/_markup/render-codeblock-mermaid.html`:

```
<div class="mermaid">
  {{ .Inner }}
</div>
{{ .Page.Store.Set "hasMermaid" true }}
```

An acceptable solution would be to have some sort of tag to add in the div telling Hugo to discard this HTML section when minifying.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.101.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

I don't know.

**Comment by jmooring** [comment]
I am unable to reproduce the problem with v0.101.0 or v0.118.2 (the current release). Try it:

```text
git clone --single-branch -b hugo-github-issue-11454 https://github.com/jmooring/hugo-testing hugo-github-issue-11454
cd hugo-github-issue-11454
hugo server --minify
```

**Comment by jmooring** [comment]
I just noticed this:

```text
{{ .Inner }}
```

I suspect one or more of the characters is being escaped. [Per the documentation](https://gohugo.io/content-management/diagrams/#mermaid-diagrams), do this:

```text
<pre class="mermaid">
  {{- .Inner | safeHTML }}
</pre>
{{ .Page.Store.Set "hasMermaid" true }}
```

**Comment by aurelienpierre** [comment]
I'll try to pull the branch tomorrow. Adding `|safeHTML` didn't fix it. The faulty graph is:

<pre>
```mermaid
mindmap
  Root((vélo))
    (confort)
    ::icon(fas fa-couch)
      [météo]
      ::icon(fas fa-cloud-sun-rain)
        froid
        pluie
        vent
      [posture]
      ::icon(fas fa-running)
        selle
          fessier
        guidon
          poignets
        souplesse
          cervicales
          hanche
          genou
          cheville
        dos
    (sécurité)
    ::icon(fas fa-exclamation-triangle)
      [sur la route]
      ::icon(fas fa-road)
        équipement
          freins
          signalisation
          GPS
        compétences
          code de la route
          agilité
      [au parking]
      ::icon(fas fa-parking)
        antivols
        gardiennage
    (efficacité)
    ::icon(fas fa-cogs)
      vitesse
      distance
      temps
      cargo/bagages
    (santé)
    ::icon(fas fa-heart)
      cardio
      musculation
      poids
    (plaisir)
    ::icon(fas fa-smile)
      exploration
      silence
      sociabilité
```
</pre>

**Comment by jmooring** [comment]
I can't reproduce the problem with your example either.

![image](https://github.com/gohugoio/hugo/assets/335669/d6913d3e-e718-42d2-bc03-88556bc8421b)

I've included your example in the example site above.

**Comment by bep** [comment]
I have not looked at this particular case, but I do agree that we need a way to mark a HTML section ( e.g. a `div`) as "not to be minified".

@tdewolff if I could bother you with a question; is this something that your minfier supports (or could support)?

**Comment by aurelienpierre** [comment]
```
git clone --single-branch -b hugo-github-issue-11454 https://github.com/jmooring/hugo-testing hugo-github-issue-11454
cd hugo-github-issue-11454
hugo server --minify
```
works on my end here. It should be something wrong on my end.

**Comment by tdewolff** [comment]
You can keep white space using the `<pre>` tag, which is specifically for that. Otherwise, you can change the content type using for example `<script type="text/mermaid">...</script>`, which I suppose is more correct as it really is a different content type. Otherwise, content in a regular `<div>` is textual content and follows the HTML spec, which specifies that runs on white space is the same as a single white space character. Mermaid.js should not rely on that in my opinion.

**Comment by jmooring** [comment]
Not reproducible. 

Our [documentation for embedding Mermaid diagrams](https://gohugo.io/content-management/diagrams/#mermaid-diagrams) places the content within a `pre` element; white space is retained.

**Comment by aurelienpierre** [comment]
Facepalm moment… it was indeed the `<pre>` tag that should have been used instead of `<div>` in this context.

Thanks guys.
