### ISSUE TITLE
Some breaking changes planned for Hugo 0.123.0

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11455]
We're planning some big improvements for the next Hugo, and with that comes some changes which some may consider breaking, but I suspect the majority would consider these to be bug fixes/improvements.

**This list is a work in progress.** 

- [x] #11654
- [x] #11453
- [x] #11663
- [x] #11439
- [x] #11556
- [x] #11669
- [x] #11807
- [x] #11808
- [x] #11809
- [x] #11815 
- [x] #10104
- [x] #9192
- [x] #11860

Note to self: Merge #11549 and this issue at some point.

**Comment by funnelact** [comment]
reworking on some techincal issues
