### ISSUE TITLE
Non-breaking spaces in anchors ignored

### ISSUE THREAD

**Issue by nibe** [gohugoio/hugo#11461]
Just a small issue. The `Anchor` passed to the Markdown render hook `render-heading.html` removes non-breaking spaces instead of turning them into dashes like it does for regular spaces.

For example, "Heading with Product Name" (non-breaking space between Product and Name) becomes "heading-with-productname" instead of the expected "heading-with-product-name".

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended darwin/arm64 BuildDate=2023-08-31T11:23:51Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
How are you inserting the non-breaking space into your markdown?

**Comment by jmooring** [comment]
First, the render hook does not have a role in this behavior. Remove your render hook and examine the rendered markdown.

Second, by default, Hugo generates heading IDs following the GitHub standard. If you look at Hugo's [default markdown configuration](https://gohugo.io/getting-started/configuration-markup/#goldmark)...

```toml
[markup.goldmark.parser]
autoHeadingIDType = 'github'
```

To test, create a GitHub gist and you'll see the same behavior.

If you really, really want a unicode no-break space to be represented by a hyphen in heading IDs, you can change the `autoHeadingIDType` to `blackfriday`, but I wouldn't do that. That particular setting is the last artifact of Blackfriday within the Hugo source; we ripped the rest of it out a few years ago, and at some point this will be removed as well.

**Comment by jmooring** [comment]
Here's a gist: <https://gist.github.com/jmooring/3597d36706fd7a01b6e382128efa3e1f>

This is how GitHub renders the gist:

![image](https://github.com/gohugoio/hugo/assets/335669/e11b8c1c-e831-478d-87ce-5bd2c41b959c)

This is how Hugo renders the gist:

![image](https://github.com/gohugoio/hugo/assets/335669/fe8ebb72-3733-4f6c-a036-d97060e43013)
