### ISSUE TITLE
google_analytics_async.html should be deprecated and removed

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#11467]
_internal/google_analytics_async.html no longer works, which is okay because Google removed the version of Google Analytics it uses, but Hugo doesn't emit any warning about it. Hugo should begin emitting a warning to anyone who includes it and remove it at some point down the line.

**Comment by jmooring** [comment]
Duplicate of https://github.com/gohugoio/hugo/issues/10899
