### ISSUE TITLE
hugo new content ignores the --format option

### ISSUE THREAD

**Issue by jc-camosun** [gohugoio/hugo#11462]
### What version of Hugo are you using (`hugo version`)?
0.118.2

### Does this issue reproduce with the latest release?
yes

hugo new content --format yaml still produces +++ for the front matter instead of YAML's ---

**Comment by jmooring** [comment]
Although this flag has been erroneously available when generating new content, it has never had any effect. The flag should be removed from the `hugo new content` command.

**Comment by jc-camosun** [comment]
> Although this flag has been erroneously available when generating new content, it has never had any effect. The flag should be removed from the `hugo new content` command.

If this is the case, how do you generate new content so that it uses YAML for its front matter if you have used `--format yaml` when generating the site?

**Comment by jmooring** [comment]
You can have as many archetypes as you want, using different front matter formats, etc.

**Comment by jc-camosun** [comment]
> You can have as many archetypes as you want, using different front matter formats, etc.

That I understand, but if I used the `--format yaml` flag when generating the site with the `hugo new site` command,  shouldn't the `default.md` also be in YAML, not TOML?

**Comment by jmooring** [comment]
That flag only applies to the configuration format. That is the way it has always behaved.

**Comment by aquada** [comment]
I'm also interested in an answer of the question from 

> > You can have as many archetypes as you want, using different front matter formats, etc.
> 
> That I understand, but if I used the `--format yaml` flag when generating the site with the `hugo new site` command, shouldn't the `default.md` also be in YAML, not TOML?

I am also interested in this. I have created the site with format YAML and it correctly creates a YAML config, but when I create a post it always defaults to TOML front matter. I have tried specifying `metaDataFormat: yaml
` in the hugo.yaml, but it does not resolve the issue.

**Comment by aquada** [comment]
I am still confused as to how can we create content with YAML front matter? I can open another issue, but maybe there is a simple answer? As it stands it will always create TOML. thank you

**Comment by bep** [comment]
>I am still confused as to how can we create content with YAML front matter? I can open another issue, but maybe there is a simple answer? As it stands it will always create TOML. thank you

Content gets created based on archetype templates and Hugo will use whatever front matter format these uses.

**Comment by jtcmedia** [comment]
> archetype templates

Might be a good idea for hugo to output to the console a message that you need to change your archetype templates to YAML manually when the user generates their site with `--format yaml`

**Comment by bep** [comment]
@jtcmedia there is no such flag anymore for `new content`, so the user will get an error.

**Comment by aquada** [comment]
> > I am still confused as to how can we create content with YAML front matter? I can open another issue, but maybe there is a simple answer? As it stands it will always create TOML. thank you
> 
> Content gets created based on archetype templates and Hugo will use whatever front matter format these uses.

that's clarified it, thank you
