### ISSUE TITLE
--appendPort false doesn't work. --appendPort=false does. Str

### ISSUE THREAD

**Issue by bn-l** [gohugoio/hugo#11482]
### What version of Hugo are you using (`hugo version`)?

hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended linux/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio

### Does this issue reproduce with the latest release?

yes (v0.118.2 at time of writing)

Running the appendPort flag will not work:

`hugo server --appendPort false`

But with kw args it will:

`hugo server --appendPort=false`

This is inconsistent with other arguments. E.g. both `--bind 127.0.0.5` and `--bind=127.0.0.5` will work.

It would be good to add a note to the help text.

**Comment by bep** [comment]
That's odd.

**Comment by vladh** [comment]
This is intended. https://github.com/spf13/cobra/issues/1606
