### ISSUE TITLE
Creating More Specific Code Highlights

### ISSUE THREAD

**Issue by nixentric** [gohugoio/hugo#11487]
Is it possible to create code highlights like this in Hugo?

![like this](https://i.ibb.co/bJ8vsXn/Screenshot-2023-09-24-120249.png)

Please answer, thank you.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
