### ISSUE TITLE
.Site.Taxonomies is empty if building of term pages is disable

### ISSUE THREAD

**Issue by carandraug** [gohugoio/hugo#11486]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended linux/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes. I'm using the latest release.

### Issue description

The `.Site.Taxonomies` variable provides a struct with the taxonomy data but it requires that ~the `taxonomy` and~ `term` pages be enabled. ~If either of them is disabled (`disableKinds` confguration), then it will be empty. Note the _and_.~  If `taxonomy` pages are enabled but `term` pages are disabled (`disableKinds` configuration), then `site.Taxonomies` is empty.

I guess it is possible that this is by design but if so, I found it surprising behaviour since a taxonomy may still exist, it's just the building of their pages that has been disabled.

**Comment by jmooring** [comment]
> If either of them is disabled

I'm seeing a different behavior.

||taxonomy enabled|taxonomy disabled
:--|:--|:--
term enabled|both published, map populated|term page published, map populated
term disabled|taxonomy page published, map empty|neither published, map empty

**Comment by carandraug** [comment]
>> If either of them is disabled
>
> I'm seeing a different behavior.

Ups. I re-tested and you're right. Still, I think the core of the issue remains. If building of the `term` pages is disabled, then `.Site.Taxonomies` is empty, which is not obvious (particularly since the `taxonomy` pages are enabled).

**Comment by jmooring** [comment]
Out of curiosity, why do you need to disable the term pages?

**Comment by carandraug** [comment]
> Out of curiosity, why do you need to disable the term pages?

I don't need them so I disable them.

**Comment by jmooring** [comment]
Do this in your site configuration:

```
[[cascade]]
  [cascade._build]
    list = 'never'
    render = 'never'
  [cascade._target]
    kind = 'term'
```

**Comment by jmooring** [comment]
This is working as designed. Won't fix. See:

- <https://github.com/gohugoio/hugo/pull/12056>
- <https://github.com/gohugoio/hugo/pull/12060>
