### ISSUE TITLE
Add support for chroma lexer overrides

### ISSUE THREAD

**Issue by myitcv** [gohugoio/hugo#11496]
As I understand, hugo uses chroma "out of the box". That is, it uses the lexers that are embedded/compiled into https://pkg.go.dev/github.com/alecthomas/chroma/v2. Albeit via a shim of the registry in `github.com/gohugoio/hugo/markup/highlight/chromalexers`. 

For well-established languages this is fine, because they (hopefully) change infrequently. 

We have just submitted (and had merged) an initial version of the [CUE](https://cuelang.org) lexer: https://github.com/alecthomas/chroma/pull/858

My understanding is that the process of support for `.cue` files making its way through to hugo is now that:

1. Make changes to XML-based CUE lexer in Chroma (done)
1. Tag a new version of chroma
1. Upgrade chroma dependency in hugo
1. Tag a new version of hugo

This is quite a lengthy process, especially where tagging new versions is involved.

Given the initial version of the CUE lexer is not yet complete, it is likely that more changes/bug fixes will be required. 

Having each such change go through the pipeline above places a large burden on the maintainers of the chroma and hugo projects.

It also means that iteration on the CUE lexer in a hugo-based environment requires incredibly long cycles of pushing the change through the "pipeline".

A short-term focussed way of shortening that pipeline would be to add configuration to hugo that allows for overrides to the chroma lexer defaults to be specified as filepaths. 

This would allow us to:

* maintain a project-local version of the CUE XML lexer
* specify that our hugo project use that file for `.cue` files
* upstream changes to chroma once they stabilise in our project repo (https://github.com/cue-lang/cuelang.org)

Having briefly looked at the code, hugo already wraps the default chroma lexer registry in `github.com/gohugoio/hugo/markup/highlight/chromalexers`. So the configuration would drive the concept of an overlay within that package.

Would welcome thoughts/feedback on the suggestion, as well as ideas for alternative ways of dealing with this.

**Comment by prnvbn** [comment]
An alternative idea for dealing with this is to use the approach used by hugo for diagrams - https://gohugo.io/content-management/diagrams/ along with [prism.js](https://prismjs.com/). I wanted to add some custom syntax highlighting in a code block - I want the word "when" to be treated as a keyword and for it to be highlighted as well.


Add a custom [code block render hook](https://gohugo.io/render-hooks/code-blocks/) - `layouts/_default/_markup/render-codeblock-boc.html`

```html
{{- $content := .Inner -}}
<pre class="language-boc">
<code class="language-boc" style="margin: 0; padding: 0;">
    {{- $content | htmlEscape | safeHTML -}}
</code>
</pre>

{{ .Page.Store.Set "hasBoCCode" true }}
```

Extend prism ([more detail on how to do that](https://prismjs.com/extending.html)) by adding support for my custom syntax highlighting by adding the following file at `static/js/prism-boc.js`

```js
Prism.languages.boc = {
  keyword: /\b(when)\b/,
  // 'function': /\b\w+(?=\()/,
  // 'string': /"(?:\\.|[^\\"])*"/,
  // 'number': /\b\d+\b/,
  // 'comment': /\/\/.*/
};
```

Updating the baseof template to import the prism scripts

```html
<!--...-->
  <head>
<!--...-->
    {{ if .Store.Get "hasBoCCode" }}
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism.min.css"
      />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>
      <script src="/js/prism-boc.js"></script>
    {{ end }}
<!--...-->
```


The only drawback of this approach is that this will break highlighting for all other code blocks if the prism scripts are loaded (which for me wasn't an issue but isn't particularly ideal).

**Comment by bep** [comment]
I'm closing this for now. This ball may be picked up again in the future, but I don't want to add/maintain more complexity to a setup that works great for 99.999% of the use cases.
