### ISSUE TITLE
Hugo 0.119 no longer builds - issue with js html template parsing

### ISSUE THREAD

**Issue by Samreay** [gohugoio/hugo#11507]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended linux/amd64 BuildDate=2023-09-24T15:20:17Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yup

### What is the issue?

Since upgrading to 0.119, my site no longer builds. I spent some time deleting things out to come to a reproducible HTML template.

This `list.html` template works with 0.119:

```html
{{ define "main" }}

<script type="module">
  const posts = [];
  const card_template = html`<div>${() => posts.map(post => html``)}</div>`
</script>

<h1>{{ .Title }}</h1>

{{ end }}
```

This `list.html` does not:

```html
{{ define "main" }}

<script type="module">
  const posts = [];
  const card_template = html`<div>${() => posts.map(post => html`<p></p>`)}</div>`
</script>

<h1>{{ .Title }}</h1>

{{ end }}
```

My site builds some reactivity in the front end up using `arrow.js` and Hugo simply populats a big old JSON object to use. It seems like nested js HTML templates are no longer allowed in the validation, which means I'll need to roll back until that's supported. @jmooring directed me to this backend ticket: https://go-review.googlesource.com/c/go/+/507995

**Comment by Samreay** [comment]
Hey @bep, I noticed this has the upstream tag on it - do you know what upstream project I should raise an issue with and chase it there to try and reduce the number of things to keep track of by the hugo team? :)

**Comment by bep** [comment]
Note that we run with a "soft fork" of Go's template packages, so if this is merged upstream and is important enough for us, we could consider pulling this in before Go 1.22 gets released.
