### ISSUE TITLE
Add hugo.IsServer as alias of site.IsServer

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#11510]
I was changing some code from `hugo.IsProduction` and I tried writing `hugo.IsServer`, which it turns out does not work. This is should be `site.IsServer` instead. But why? I think the answer is that `site.IsServer` predates the `hugo` action. Now that we have `hugo`, I think `site.IsServer` should be removed from the docs (although maybe not actually removed for a long time) and `hugo.IsServer` should be added.

**Comment by jmooring** [comment]
I agree that's  a better place for it, but also want to clarify that hugo.IsProduction and site.IsServer are two very different things:

```
$ hugo server -e production

{{ site.IsServer }} --> true
{{ site.IsProduction }} --> true
```

And I think `hugo.Environment` is the most useful of the three.

**Comment by carlmjohnson** [comment]
Yeah, I was changing the code because it was testing for prod but it really needed to be testing for server vs compiled.

**Comment by bep** [comment]
Yes, we should do this. I have found that the most useful construct in this department is:

```
{{ if ne hugo.Environment "development"  }}
{{ end }}
```

The above works if you have additional "production like" environments (staging ...).

So, maybe we should add a `hugo.IsDevelopment` too.
