### ISSUE TITLE
Return integrity value as string

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11513]
This isn't broken, but it isn't right either. The `template.HTMLAttr` type is applicable to a key/value pair, not just the value.

https://github.com/gohugoio/hugo/blob/3af8bded26db1fa4c0ab292139371802a14026dc/resources/resource_transformers/integrity/integrity.go#L112-L115

Return a string instead.

**Comment by bep** [comment]
Hmm... I was about to tell you that "this cannot be right", then I read the documentation.
