### ISSUE TITLE
Shortcode escapes closing HTML tags

### ISSUE THREAD

**Issue by john-wilkinson** [gohugoio/hugo#11516]
Please re-open https://github.com/gohugoio/hugo/issues/6006

This is still a bug, and it still functions exactly as described in issue 6006.

It does not appear to be replicatable exclusively with go templates, indicating an issue with Hugo. In particular, it is not seen in partials or layouts outside of shortcodes.

https://go.dev/play/p/ctrTQqXDz_f

**Comment by john-wilkinson** [comment]
Additionally, the behavior is only exhibited if no text follows the template expression `{{ .Inner }}`.

For example, the following does not have an issue:

```
<div>
    <p>
        {{ .Inner }} value
    </p>
</div>
```

Without the text, the closing HTML tags are escaped and put into code blocks:

```
<div>
    <p>
        {{ .Inner }}
    </p>
</div>
```

**Comment by jmooring** [comment]
How are you calling the shortcode from markdown?

**Comment by john-wilkinson** [comment]
This is how I am calling it:

```
{{% box %}}
Some test text.
{{% /box %}}
```

Interestingly, this problem disappears if I use the angle bracket syntax, not putting it through the markdown renderer:
```
{{< box >}}
Some test text.
{{< /box >}}
```

**Comment by jmooring** [comment]
I am unable to reproduce the problem as described. I suspect you are indenting either the text, or the entire shortcode code call, by 4 or more spaces. Per the CommonMark specification, text indented by four or more spaces is an [indented code block](https://spec.commonmark.org/0.30/#indented-code-blocks), which is why your output is wrapped in `pre` and `code` tags.

Please use the forum (https://discourse.gohugo.io/) for additional questions or troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by john-wilkinson** [comment]
Here the simplest steps I can come up with to reproduce it. It is unclear to me why you are unable to reproduce it, it seems incredibly easy to do so.

I am on Windows. Perhaps that is making a difference?

Anyway:

Create a new hugo project:

```
hugo new site demo-6006
cd demo-6006
```


Create the file `layouts/shortcodes/box.html`:

```
<div class="content">
    <div class="box">
        <p>
            {{ .Inner }}
        </p>
    </div>
</div>
```

Create the file `layouts/index.html`:
```
{{ define "main" }}
{{ end }}
```

Create the file `layouts/_default/baseof.html`:
```
<!DOCTYPE HTML>
<html>
    <body>
        {{- block "main" . }}{{- end }}
    </body>
</html>
```

Create the file `layouts/_default/single.html`:
```
{{ define "main" }}
  {{ .Content }}
{{ end }}
```

Create a new content file:
```
hugo new content tests/test.md
```

Edit the contents of the newly created `content/tests/test.md` and add the following:
```
{{% box %}}
Broken
{{% /box %}}
```

Start the server:
```
hugo server -D
```

Navigate to the test page:
```
http://localhost:1313/tests/test/
```

![image](https://github.com/gohugoio/hugo/assets/5498530/45c6cd5e-e631-4a45-89c9-09e6ca296309)

**Comment by jmooring** [comment]
1\) The setup you describe above, calling the shortcode with the `{{% %}}` notation, also requires this in your site configuration:

```text
[markup.goldmark.renderer]
unsafe = true
```

2\) You are not passing `"Broken"` to the shortcode. You are passing `"\nBroken\n"` (or `"\r\nBroken\r\n"` on Windows).

3\) When using the `{{% %}}` notation, you are passing this block to the markdown renderer:

```text
<div class="content">
  <div class="box">
      <p>
          
          Broken

      </p>
  </div>
</div>
```

[try it yourself]: https://spec.commonmark.org/dingus/?text=%3Cdiv%20class%3D%22content%22%3E%0A%20%20%3Cdiv%20class%3D%22box%22%3E%0A%20%20%20%20%20%20%3Cp%3E%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20Broken%0A%0A%20%20%20%20%20%20%3C%2Fp%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E

4\) The markdown renderer, adhering to the [CommonMark specification](https://spec.commonmark.org/0.30/), produces this:

```text
<div class="content">
  <div class="box">
      <p>
<pre><code>      Broken

  &lt;/p&gt;
</code></pre>
  </div>
</div>
```

[Try it yourself]. Hugo and the markdown renderer (GoldMark) are doing exactly what they should be doing. This is not a bug.

5\) You can achieve the desired results by doing either of:

- Reduce indentation within the shortcode. See the [indented code blocks] section in the CommonMark specification.
- Pass `.Inner` through the `chomp` function. See the [HTML blocks] section in the CommonMark specification.

[indented code blocks]: https://spec.commonmark.org/0.30/#indented-code-blocks
[HTML blocks]: https://spec.commonmark.org/0.30/#html-blocks

6\) Signing up for a new Discourse account is pretty easy.
