### ISSUE TITLE
removePathAccents not work for some characters đ

### ISSUE THREAD

**Issue by dhngroup** [gohugoio/hugo#11534]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.119.0
</pre>

### Does this issue reproduce with the latest release?

Characters "đ" are not changed to "d" if removePathAccents: true and urlize tags.

**Comment by jmooring** [comment]
The character `đ` does not have a path accent; it is not a composite character. You want transliteration. 

Closing as duplicate of https://github.com/gohugoio/hugo/issues/9134.

**Comment by dhngroup** [comment]
transliteratePaths = true

Characters "đ" are not changed to "d" if transliteratePaths : true and urlize tags.

DefaultContentLanguage = "vi"

**Comment by jmooring** [comment]
@dhngroup 

#9134 is a proposal; it has not been implemented. That's why the issue is open.
