### ISSUE TITLE
Page bundles linked by translationKey do not share page resources

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11540]
```text
content/
├── en/
│   ├── foo/
│   │   └── foo-1/
│   │       ├── a.jpg
│   │       └── index.md   <-- translationKey = 'baz'
│   └── _index.md
└── pl/
    ├── bar/
    │   └── bar-1/
    │       └── index.md   <-- translationKey = 'baz'
    └── _index.md
```

The a.jpg image is not available as a page resource when rendering content/pl/bar/bar-1.md.

Although the documentation doesn’t specifically state that page resources are shared when using `translationKey` in front matter, it is certainly implied.

Reproducible example:

```text
git clone --single-branch -b hugo-forum-topic-46581 https://github.com/jmooring/hugo-testing hugo-forum-topic-46581
cd hugo-forum-topic-46581
hugo server
```

Reference: <https://discourse.gohugo.io/t/46581>

**Comment by bep** [comment]
I'm in the process of reimplementing this stuff, and this should be fixed when I'm done with that (it's getting close ...).
