### ISSUE TITLE
Module error when running a version of go with MAJOR.MINOR.PATCH

### ISSUE THREAD

**Issue by Chrede88** [gohugoio/hugo#11558]
When running any module commands, Hugo (Go) will add the `patch` release number to the `go.mod` file. This will in turn lead to an error as the code can't handle `go` versions with a patch, e.g. go 1.21.1

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended darwin/arm64 BuildDate=2023-09-24T15:20:17Z VendorInfo=brew
</pre>

<pre>
$ go version
go version go1.21.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes.

**Comment by bep** [comment]
Can you be more specific? What do you do and what error do you get?

I'm running 

```bash
go version go1.21.3 darwin/arm64
```

And have not seen any issues re this, and we're also have lots of tests covering this (which runs the latest Go).
