### ISSUE TITLE
Permalink for RSS feeds is the Atom permalink

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugo#11555]
In http://localhost:1313/rss.xml, I get:

```xml
<atom:link href="http://localhost:1313/atom.xml" rel="self" type="application/rss+xml"/>
```

I want:

```xml
<atom:link href="http://localhost:1313/rss.xml" rel="self" type="application/rss+xml"/>
```

This doesn't work:

```xml
<atom:link href="{{ $page.Permalink }}" rel="self" type="application/rss+xml"/>
```

This does:

```xml
<atom:link href="{{ replaceRE `/atom\.xml$` `/rss.xml` $page.Permalink }}" rel="self" type="application/rss+xml"/>
```

See https://discourse.gohugo.io/t/rss-permalink-is-atom-permalink-somehow/46388.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended darwin/amd64 BuildDate=2023-09-24T15:20:17Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
I am unable to reproduce the problem.

```text
git clone --single-branch -b hugo-github-issue-11555 https://github.com/jmooring/hugo-testing hugo-github-issue-11555
cd hugo-github-issue-11555
hugo server
```

**Comment by willfaught** [comment]
This was the fix for it: https://github.com/willfaught/paige/commit/c44a6b6c081508cc3e29938b6d933d670e446d86

It should be reproducible in the previous commit: https://github.com/willfaught/paige/commit/f00db61ac9956b9318708fe66ebe3010dafae974

**Comment by willfaught** [comment]
`curl http://localhost:1313/rss.xml | grep 'atom:link'`

**Comment by jmooring** [comment]
With the example site that I provided above:

![image](https://github.com/gohugoio/hugo/assets/335669/928664bc-0c74-4de2-9f7f-3a7d2eadd5ef)

![image](https://github.com/gohugoio/hugo/assets/335669/25c98833-68e4-4906-93e7-ae7bc77a5ed8)

**Comment by willfaught** [comment]
Hmm, not sure why it's not reproing for you. Maybe it's the site? Try the exampleSite at https://github.com/willfaught/paige/tree/master/exampleSite. That's one of the two ways I observed it.

**Comment by jmooring** [comment]
This is now a support issue, not a bug. Let's take the conversation back to the forum.
