### ISSUE TITLE
Hugo generator meta tag: W3C warning about trailing slash on void element 

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#11576]
Currently Hugo injects a generator tag at the HEAD of HTML pages that causes the W3C HTML Validator to throw a warning about its trailing slash.

Consider removing the trailing slash.

More info here:

https://github.com/validator/validator/wiki/Markup-»-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values

**Comment by jmooring** [comment]
I am unable to reproduce this as described.

```
hugo new site mysite
cd mysite/
hugo new theme mytheme
echo "theme = 'mytheme'" > hugo.toml
hugo
grep generator public/index.html
```

> `<meta name="generator" content="Hugo 0.119.0">`

hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended linux/amd64

**Comment by onedrawingperday** [comment]
Thank you @jmooring

The project was using Hugo 0.80 for its deployment, switching to 119.0 fixed the W3C trailing slash on void elements warning.
