### ISSUE TITLE
Page Not Found on very first build - disgusting

### ISSUE THREAD

**Issue by ORESoftware** [gohugoio/hugo#11589]
I do these steps:

```bash

hugo new site my-static-site
cd my-static-site
hugo
hugo server -D
```

the shell says:

> Web Server is available at http://localhost:1313/ (bind address 127.0.0.1) 

I got to `localhost:1313` and it says:

> "Page Not Found"

<img width="484" alt="Screen Shot 2023-10-20 at 1 44 19 PM" src="https://github.com/gohugoio/hugo/assets/11139560/731d3751-5722-487a-86a9-fbda9cfa9e6d">

**what the fuck???**

**Comment by ORESoftware** [comment]
I am on a mac, nothing special here

**Comment by jmooring** [comment]
I suggest you:

1. Use the latest version of Hugo (v0.119.0)
2. Follow the instructions as presented in the console

```text
$ hugo new site my-static-site
Congratulations! Your new Hugo site was created in /home/jmooring/temp/my-static-site.

Just a few more steps...

1. Change the current directory to /home/jmooring/temp/my-static-site.
2. Create or install a theme:
   - Create a new theme with the command "hugo new theme <THEMENAME>"
   - Install a theme from https://themes.gohugo.io/
3. Edit hugo.toml, setting the "theme" property to the theme name.
4. Create new content with the command "hugo new content <SECTIONNAME>/<FILENAME>.<FORMAT>".
5. Start the embedded web server with the command "hugo server --buildDrafts".

See documentation at https://gohugo.io/.
$ cd /home/jmooring/temp/my-static-site/
$ hugo new theme my-theme
Creating new theme in /home/jmooring/temp/my-static-site/themes/my-theme
$ echo "theme = 'my-theme'" >> hugo.toml
$ hugo new content notes/follow-instructions.md
Content "/home/jmooring/temp/my-static-site/content/notes/follow-instructions.md" created
$ hugo server --buildDrafts
```

![image](https://github.com/gohugoio/hugo/assets/335669/60a626f9-9f84-4cc6-b5d0-f201b726af2f)

![image](https://github.com/gohugoio/hugo/assets/335669/e43def1e-8a23-450d-b0b1-747d1af27832)

See documentation: <https://gohugo.io/getting-started/quick-start/>

Finally, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by ORESoftware** [comment]
it should just have a default page, with those instructions on it, IMO
