### ISSUE TITLE
Emoji codes are not converted, and disappear, when using the RenderShortcodes method

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11587]
Not sure if we could resolve this by adding the [yuin/goldmark-emoji](https://github.com/yuin/goldmark-emoji/) extension, which solves another problem too, but it's worth a test.

See <https://github.com/gohugoio/hugo/issues/7332#issuecomment-1608424761>.

Tested with `enableEmoji= true` in site configuration.

---
Update: I enabled the yuin/goldmark-emoji extension, and set `enableEmoji= false`. Fixes the problem. I think it makes sense to add that extension, disabled by default.

**Comment by wanqiqiu** [comment]
Hi @jmooring, I would like the work on the issue, please assign it to me if possible!
