### ISSUE TITLE
The "world’s fastest framework for building websites" is a total mess!

### ISSUE THREAD

**Issue by Thierry-3D** [gohugoio/hugo#11590]
I was looking for a solution to publish a blog without programming and found the promising Hugo engine. I followed (with difficulty) the steps to install the required software on my Windows PC, but was always faced with errors and non recognized commands (for example, I added "hugo" to the system path, but it was never known to the pwsh7 console).

Please offer a one-click installer to people that have few or no programming skills!

**Comment by calalloo** [comment]
https://discourse.gohugo.io/t/requesting-help/9132#some-knowledge-required-2
