### ISSUE TITLE
Create padding image filter

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11599]
Return an image resource that you can use with `images.Text` and `images.Overlay`.

```
images.Create WIDTH HEIGHT [BGCOLOR] [FORMAT]
```

- Width and height must be in the range [1,10000] (or something smaller, but put a limit on it).
- Background color is RGBA, with length of 3, 4, 6, or 8 (e.g., `#123`, `#123f`, `#112233`, `#112233ff`. If alpha not specified, opaque. Default is white.
- Format is one of `jpeg`, `webp`, etc. Default is `png`.

The way to handle this today is with a `1x1.png` in the assets directory that you grab as a resource and then resize. 

Reference: <https://discourse.gohugo.io/t/should-it-be-possible-to-pad-an-an-image-using-0-119-image-processing/46684/4>

---

EDIT: Rethinking this, the specific case referenced above, image padding, would probably be handled better with an image filter.

```
images.Pad D1 [D2] [D3] [D4] [BGCOLOR]
```

Where the dimensions use the same syntax as CSS padding (e.g., if you provide one number if affects all sides), and background color is as previously described.

**Comment by bep** [comment]
>The way to handle this today is with a 1x1.png in the assets directory that you grab as a resource and then resize.

That said, I say that the common way today is to use a pretty background image (with some gradient or something) for your overlay images, which is trivial to make in most photo editors.

**Comment by jmooring** [comment]
Agreed. The _primary_ use case behind this suggestions is padding an image, which today is `get+resize+get+overlay`.  

Instead of doing `create+get+overlay`, maybe just a filter so you can do `get+pad`.

**Comment by jmooring** [comment]
Renaming this issue; the ability to pad an image is the primary use case. We can revisit image creation at a later date if needed.
