### ISSUE TITLE
Ampersand character in post content causes RSS feed error

### ISSUE THREAD

**Issue by ozzie-eu** [gohugoio/hugo#11615]
### Hugo version
hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended

### Does this issue reproduce with the latest release?
I updated to the latest release available though the Chocolatey package manager. The issue  persists.

### Error displayed
The displayed error is:
<pre>
This page contains the following errors:
error on line 70 at column 66: xmlParseEntityRef: no name
Below is a rendering of the page up to the first error.
</pre>

### Confirmed Cause
The genrated XML, at the line/colun given, had the '&' character.

### Workaroud
Replaced the '&' with the word "and". It worked fine.

### Suggested Fix
The '&' character should be escaped as "&amp;amp;" on the RSS generator.

**Comment by jmooring** [comment]
I am unable to reproduce the problem as described. Which theme are you using?

**Comment by ozzie-eu** [comment]
> I am unable to reproduce the problem as described. Which theme are you using?
I'm using this one: https://github.com/dataCobra/hugo-vitae

**Comment by jmooring** [comment]
<<https://github.com/ozzie-eu/www-ozzie-eu/blob/main/themes/hugo-vitae/layouts/_default/rss.xml#L48>>

**Comment by jmooring** [comment]
<https://github.com/dataCobra/hugo-vitae/blob/main/layouts/_default/rss.xml#L52>

Hugo is doing as instructed. Please take this up with the author of the theme.

Please use the forum (https://discourse.gohugo.io/) if you have additional questions. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
