### ISSUE TITLE
Using `resources.Copy` on a page resource requires a call to .Publish to render

### ISSUE THREAD

**Issue by NickAnderegg** [gohugoio/hugo#11616]
Bit of an odd one to figure out! I have a shortcode `common-block` that renders the content of headless leaf bundles that are stored under the `content/_common` directory:

```
{{- $blockId := .Get "blockId" -}}
{{- $blockBundleName := printf "/_common/%s" $blockId -}}
{{- $blockBundle := .Site.GetPage $blockBundleName -}}

{{- with $blockBundle -}}
{{- .Content | markdownify -}}
{{- end -}}
```

To render the images on these pages, I have another shortcode `resource/img` that is exclusively used within these headless leaf bundles to render images associated with them. Part of the rendering process involves copying the image to a common directory with a unique name.

Interestingly, the `resource/img` shortcode below works perfectly when the `{{- .Publish -}}` line is included, but if that's removed, the images don't actually get published to the public directory:

```
{{- $caption := .Inner | default "" -}}
{{- $imgName := .Get "name" -}}
{{- $img := .Page.Resources.GetMatch (printf "images/%s*" $imgName) -}}
{{- $pageTitle := .Page.File.ContentBaseName -}}

{{- $imgSuffix := index $img.MediaType.Suffixes 0 -}}
{{- $imgHash := md5 $img.Content -}}

{{- $newPath := printf "/images/common/%s-%s-%s.%s" $pageTitle $imgName $imgHash $imgSuffix -}}

{{ with resources.Copy $newPath $img }}
{{- .Publish -}} <-- BREAKS IF THIS LINE IS REMOVED
<figure>
  <img src="{{ .RelPermalink }}" />
  {{- if $caption -}}
    <figcaption>{{ $caption }}</figcaption>
  {{- end }}
</figure>
{{ end }}
```

My understanding is that `.Publish` is just an explicit call to accomplish the same thing as a call to `.RelPermalink`, so it's a bit odd that I had to include both (and this took absolutely forever to debug!)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended darwin/arm64 BuildDate=2023-09-24T15:20:17Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

This is the latest release.

**Comment by jmooring** [comment]
> headless leaf bundles

Please describe how you are making them headless.

**Comment by NickAnderegg** [comment]
> I am unable to reproduce the problem

Well, this is just baffling. I copied your testing repo, and it seems to be functioning just fine. I've just tried making a bunch of tweaks to my own repo that aligns it with yours, and that didn't resolve the issue.

## The Most Baffling Part

When I run Hugo with the `{{.Publish}}` line commented out, it produces 113 pages, 11 static files, 73 aliases, and 5 non-page files:

```console
> rm -rf public/*; hugo
zsh: sure you want to delete all 21 files in /Users/nickanderegg/CTOai/docs-hugo/public [yn]? y
Start building sites …
hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended darwin/arm64 BuildDate=2023-09-24T15:20:17Z VendorInfo=gohugoio

WARN  common-block `insights-events-definition` not found
WARN  common-block `current-deployment-events` not found
WARN  common-block `future-deployment-events` not found
WARN  common-block `current-change-events` not found
WARN  common-block `trigger-event-formatting` not found

                   | EN
-------------------+------
  Pages            | 113
  Paginator pages  |   0
  Non-page files   |   5
  Static files     |  11
  Processed images |   0
  Aliases          |  73
  Sitemaps         |   1
  Cleaned          |   0

Total in 283 ms
```

And the files rendered to the `public/` dir write the `_common` files out to their own directory (abridged `tree` output shown below):

```console
> tree -L 2 public
public
├── 404.html
├── LICENSE.txt
├── _common
│   ├── some-bundle-a 
│   │   └── images <-- THESE DIRECTORIES CONTAIN `[ORIGINAL FILENAME].png`
│   └── some-bundle-b 
│       └── images
├── docs
│   ├── docs-section-1
│   ├── docs-section-2
│   └── docs-section-3
├── favicon.ico
├── favicon.svg
├── images <- NO IMAGES GET RENDERED HERE
│   ├── logo-dark.svg
│   └── logo.svg
├── index.html
├── index.xml
├── js
│   └── main.min.bde403475065ba7cb488c5a5bebee50c05d424618182903874d14175963225f3.js
└── tags
    ├── index.html
    └── index.xml
```

When I uncomment the `{{.Publish}}` line and run `hugo` again (with a clean `public/` dir), it again produces 113 pages, 11 static files, 73 aliases, and 5 non-page files:

```console
> rm -rf public/*; hugo
zsh: sure you want to delete all 21 files in /Users/nickanderegg/CTOai/docs-hugo/public [yn]? y
Start building sites …
hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended darwin/arm64 BuildDate=2023-09-24T15:20:17Z VendorInfo=gohugoio

WARN  common-block `insights-events-definition` not found
WARN  common-block `current-deployment-events` not found
WARN  common-block `future-deployment-events` not found
WARN  common-block `current-change-events` not found
WARN  common-block `trigger-event-formatting` not found

                   | EN
-------------------+------
  Pages            | 113
  Paginator pages  |   0
  Non-page files   |   5
  Static files     |  11
  Processed images |   0
  Aliases          |  73
  Sitemaps         |   1
  Cleaned          |   0

Total in 250 ms
```

But when I output the tree, the images have been rendered to the correct place... but they're still also rendering to the incorrect place:

```console
> tree -L 3 public
public
├── 404.html
├── LICENSE.txt
├── _common
│   ├── some-bundle-a 
│   │   └── images <-- THESE DIRECTORIES **STILL** CONTAIN `[ORIGINAL FILENAME].png`
│   └── some-bundle-b 
│       └── images
├── docs
│   ├── docs-section-1
│   ├── docs-section-2
│   └── docs-section-3
├── favicon.ico
├── favicon.svg
├── images
│   ├── common
│   │   ├── some-bundle-a-3f7ebcc24e83b8aa5ac576ff96c15c89.png <-- IMAGES ALSO RENDERED IN CORRECT PLACE
│   │   └── some-bundle-b-eb0a95e4a0a0cb869926ea32ee37858f.png
│   ├── logo-dark.svg
│   └── logo.svg
├── index.html
├── index.xml
├── js
│   └── main.min.bde403475065ba7cb488c5a5bebee50c05d424618182903874d14175963225f3.js
└── tags
```

Any guesses as to why it may behave differently in this circumstance depending on whether `{{ .Publish }}` is included? I'll try to create a minimal repo later that has only the absolutely necessary content to try to narrow it down.

**Comment by NickAnderegg** [comment]
Hmm, to add to the above, interestingly, it seems that the files that get written to `public/_common/**` are solely the image files that are loaded by the `img/resources` shortcode. It's (correctly) not attempting to render the pages, but it's still somehow creating the appropriate directory structure for those pages.

**Comment by jmooring** [comment]
Take a look at `content/_common/_index.md` in the example site. Looks like you're publishing your common files, but hard to tell without access to the project.

**Comment by NickAnderegg** [comment]
Aha. In my own `content/_common/_index.md`, I had the value of `render` set to `false`, not `"never"`. Before I added my own `content/_common/_index.md`, there was no index file at the top level of the `_common` directory at all, and each `index.md` file just had

```md
---
headless: true
---
```

to prevent rendering. Here's the file structure I was working with:

```
content
├── LICENSE.txt
├── _common
│   ├── some-bundle-a
│   │   ├── images
│   │   │   └── some-bundle-a.png
│   │   └── index.md <-- MARKED HEADLESS
│   ├── some-bundle-b
│   │   ├── images
│   │   │   └── some-bundle-b.png
│   │   └── index.md <-- MARKED HEADLESS
│   └── some-bundle-c
│       └── index.md <-- MARKED HEADLESS
└── docs
```

In that case, calling `{{.Publish}}` was required. However, I've removed the `headless: true` from the `_common/**/index.md` files and set my `_common/_index.md` to the following:

```md
---
cascade:
  _build:
    list: "never"
    publishResources: false
    render: "never"
---
```

And now it is **successfully**:

1. Rendering the images in the `content/_common/**` bundles to `public/images/common/*`
2. Not rendering any `content/_common/**` text content to `public/_common/*`

## Cause of Current Problem

So if anyone stumbles onto this issue, the solution is to use the `cacade._build` specified above in the `_index.md` of the collection of bundles you don't want to render, rather than putting `headless: true`, which will still cause the page resources to be rendered to their default file structure.

---

## Actual Bug

Thanks for the help narrowing down the problem! However, I haven't marked this issue as closed, because this still feels like a bug:

What appears to be happening is that when a "headless" bundle is being rendered, `.RelPermalink` is going to point to the **known** output URL of that bundle content, but the inclusion of an explicit `{{ .Publish }}` statement causes Hugo to write the resources to the intended destination of `resources.Copy`.

So I think the bug I've actually identified here is that `resources.Copy` fails to properly copy the page resources from `headless` leaf bundles to their target destination unless `.Publish` is explicitly called. Without the presence of the `{{ .Publish }}` line, **the `.RelPermalink` in the following block will use the original path of the resource**:

```go
{{- $img := .Page.Resources.GetMatch (printf "images/%s*" (.Get "name")) -}}
{{ with resources.Copy "new-path.png" $img }}
  <img src="{{ .RelPermalink }}" />
{{ end }}
```

**Comment by jmooring** [comment]
> following block will use the original path of the resource

I didn't see that when creating the example site. I must be missing something.

**Comment by NickAnderegg** [comment]
It's odd, because there is definitely some unexpected behavior, but I'm having trouble narrowing it down to specific conditions that cause it. It's not an urgent issue because I've already found a solution, so I'll return to this later once I have a chance to strip my repo down to the bare minimum and try to induce the issue.

**Comment by jmooring** [comment]
OK, thanks. Will leave this open.
