### ISSUE TITLE
Newly created theme has content in it (example "posts")

### ISSUE THREAD

**Issue by mmueller** [gohugoio/hugo#11624]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.119.0+extended linux/amd64 BuildDate=unknown
</pre>

This was installed through Manjaro's package manager.

### Does this issue reproduce with the latest release?
Yes?

I ran `hugo new site mysite` followed by `hugo new theme mytheme`. The `hugo new theme` command is creating a `content` folder and example posts *inside* the theme, and based on everything I've seen online, it shouldn't be doing that. These posts even show up on the  site. Are themes supposed to have content inside them?

Here's the directory structure I end up with:

<pre>
(~/tmp/mysite)$ hugo new theme mytheme
Creating new theme in /home/mike/tmp/mysite/themes/mytheme
(~/tmp/mysite)$ find -type f
./hugo.toml
./themes/mytheme/theme.toml
./themes/mytheme/README.md
./themes/mytheme/hugo.toml
./themes/mytheme/layouts/partials/footer.html
./themes/mytheme/layouts/partials/header.html
./themes/mytheme/layouts/partials/terms.html
./themes/mytheme/layouts/partials/head.html
./themes/mytheme/layouts/partials/head/css.html
./themes/mytheme/layouts/partials/head/js.html
./themes/mytheme/layouts/partials/menu.html
./themes/mytheme/layouts/_default/home.html
./themes/mytheme/layouts/_default/list.html
./themes/mytheme/layouts/_default/baseof.html
./themes/mytheme/layouts/_default/single.html
./themes/mytheme/content/posts/post-1.md
./themes/mytheme/content/posts/post-3/index.md
./themes/mytheme/content/posts/post-3/bryce-canyon.jpg
./themes/mytheme/content/posts/post-2.md
./themes/mytheme/content/posts/_index.md
./themes/mytheme/content/_index.md
./themes/mytheme/LICENSE
./themes/mytheme/archetypes/default.md
./themes/mytheme/static/favicon.ico
./themes/mytheme/assets/js/main.js
./themes/mytheme/assets/css/main.css
./archetypes/default.md
</pre>

**Comment by jmooring** [comment]
> based on everything I've seen online, it shouldn't be doing that.

As of v0.118.0, that's exactly what it should be doing:
<https://discourse.gohugo.io/t/creating-new-site-and-theme-skeletons-with-v0-118-0-and-later/46018>
