### ISSUE TITLE
hugo.IsServer and hugo.IsDevelopment throw errors

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#11635]
In `hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended linux/amd64 BuildDate=2023-09-24T15:20:17Z VendorInfo=gohugoio` I try to print out all `hugo` information with the following template:

```gotemplate
{{- $names := slice
      ".BuildDate"
      ".CommitHash"
      ".Environment"
      ".Generator"
      ".GoVersion"
      ".IsExtended"
      ".IsProduction"
      ".Version"
      ".WorkingDir" -}}
{{- $items := slice
      hugo.BuildDate
      hugo.CommitHash
      hugo.Environment
      hugo.Generator
      hugo.GoVersion
      hugo.IsExtended
      hugo.IsProduction
      hugo.Version
      hugo.WorkingDir -}}
<table class="debugprint">
  <thead>
    <tr>
      <th class="key">
        <span title="Hugo version information">hugo</span>
      </th>
      <th class="type">Type</th>
      <th class="value">Value</th>
    </tr>
  </thead>
  <tbody>
    {{- range $index, $item := $items -}}
      {{- $slices := slice
          (index $names $index)
          (partial "debugtype.html" $item)
          (partial "debugprint.html" $item) -}}
      <tr>{{- range $index, $item := $slices -}}
        {{- if (eq $index 0) -}}
          <th>{{- . -}}</th>
        {{- else -}}
          <td>{{- . -}}</td>
        {{- end -}}
      {{- end -}}</tr>
    {{- end -}}
  </tbody>
</table>
```

This works. As soon as I introduce `.isDevelopment` and `.isServer` I receive the following errors:

![Selection_005](https://github.com/gohugoio/hugo/assets/83281/f74525cb-0d0a-42fa-9982-fcd73fb6e519)

Based on https://gohugo.io/functions/hugo/ I would expect true/false responses.

**Comment by davidsneighbour** [comment]
The docs didn't show a since label. I Will try with the latest version again tomorrow. I guess I ran into some release-update loop here. After I tested this I saw the new release and after reading the notes again I see those values were added just now :)

**Comment by jmooring** [comment]
@davidsneighbour Yeah, I forgot to add the new-in tags. Thanks for letting me know.
