### ISSUE TITLE
Minify issue (tdewolff/minify #623)

### ISSUE THREAD

**Issue by brycewray** [gohugoio/hugo#11633]
Using Hugo 0.120.0 (macOS on ARM). Apparently a bug was just fixed moments ago in tdewolff/minify:

https://github.com/tdewolff/minify/issues/623

. . . and I have seen it in local testing of Hugo 0.120.0 as follows:

```
Error: error building site: MINIFY: failed to transform "js/lite-yt-embed_2023-10-04_v3-0-0.js" (text/javascript): unexpected return in expression on line 87 and column 39
   87:         if (LiteYTEmbed.preconnected) return;
```

. . . a line which presented no problems prior to Hugo 0.120.0.

**Comment by jmooring** [comment]
@tdewolff Please roll a release when you a moment. Thanks.

**Comment by tdewolff** [comment]
We're all working in parallel it seems! Haha, v2.20.1 just released!
