### ISSUE TITLE
blogs' published date is displayed incorrectly in latest hugo version

### ISSUE THREAD

**Issue by guangchen811** [gohugoio/hugo#11647]
Summary:
After upgrading to the latest Hugo version, the website's published date must be displayed correctly. Downgrading to Hugo 0.115.2 fixes the issue. 

Reproduction Steps:
1. Using Hugo version 0.115.2, the publish date is displayed correctly (see screenshot 1).
2. Upgrade Hugo to the latest version. 
3. The publish date is displayed incorrectly (see screenshot 2).
4. Downgrade Hugo to version 0.115.2 again.
5. The Publish date is displayed correctly again.

<figure>
  <img width="500" src="https://github.com/gohugoio/hugo/assets/103159823/aed66014-f4a2-4332-9e47-81307943a70e" alt="test">
  <figcaption>screenshot 1</figcaption>
</figure>
<figure>
<img width="500" alt="image" src="https://github.com/gohugoio/hugo/assets/103159823/2d03fd49-7529-417a-8911-0c05131783b8">
  <figcaption>screenshot 2</figcaption>
</figure>

The fix is shown in [this commit](https://github.com/guangchen811/guangchen811.github.io/commit/67c13ad31cb4722599d8447a41bb4de27b7e9233) in my blog. I'm not sure what made this bug, but I hope my observation can be helpful.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.120.2-9c2b2414d231ec1bdaf3e3a030bf148a45c7aa17+extended darwin/arm64 BuildDate=2023-10-31T16:27:18Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?
Yes.

**Comment by jmooring** [comment]
With v0.120.0 and later, the `delimit` function returns data type `string` instead of `template.HTML`, so you will have to pipe the output through the `safeHTML` function. The author of the PaperMod theme has aleady made this change:

<https://github.com/adityatelange/hugo-PaperMod/commit/7795c90f6fa106733267481d9ed0518b00f2c62c>
