### ISSUE TITLE
Notes releasenotes Hugo 0.122.0

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11649]
- $page.BundleType() return type changed to string (the old internal string type is removed)
- Processed versions of images will get a slightly different name. We have included the file size in bytes in the filename for images backed by a file, but not for remote images. We have consolidated that code now, so all of the processed images will get the size in the name.

**Comment by ArpitKRS** [comment]
Please /assign this issue to me and let's discuss over it.
