### ISSUE TITLE
Emoji shortcodes different after updating to Hugo 0.120.x

### ISSUE THREAD

**Issue by tobihagemann** [gohugoio/hugo#11668]
I'm not sure if this really qualifies as a bug report, but it severely breaks a lot of blog posts of my website (and potentially others as well). I believe Hugo changed the emoji extension for the markdown parser with 0.120.0, which just uses a different set of emoji shortcodes.

Some examples:
- `:information:` → `:information_source:` (for ℹ️)
- `:downcast_face_with_sweat` → `:sweat:` (for 😓)

To be honest, I don't even know if there is a "standard" for emoji shortcodes, but that's still a breaking change if you heavily rely on emojis on your website.

Was this intended? Maybe this should be added as a breaking change in the release notes? Or is there some other solution out there that could help with the migration from the old shortcodes to the new ones?

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.120.3-a4892a07b41b7b3f1f143140ee4ec0a9a5cf3970+extended darwin/arm64 BuildDate=2023-11-01T17:57:00Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by jmooring** [comment]
Yes, we made a breaking change to emoji processing in [v0.120.0](https://github.com/gohugoio/hugo/releases/tag/v0.120.0). Although referenced in the release notes, the effects of the change are not enumerated. I apologize for the change, but it was necessary for reasons unrelated to shortcode interpretation.

While emojis are somewhat standardized through the Unicode Consortium (https://home.unicode.org/emoji), the shortcodes used to represent them are not. The mapping of shortcode to character depends on the implementation, resulting in (globally) multiple  shortcodes mapped to the same character, and the possibility of name collisions. To give you an idea of the size of this mess, our prior implementation included 1675 aliases, which is both absurd and unmanageable.

The closest thing we have to an emoji shortcode standard is GitHub's implementation.

In v0.120.0 we transitioned emoji processing to the [goldmark-emoji](https://github.com/yuin/goldmark-emoji) extension for [Goldmark](https://github.com/yuin/goldmark), Hugo's default markdown renderer. Goldmark is fast, accurate, and well-maintained. It adheres to the [CommonMark specification](https://spec.commonmark.org/0.30/), and is compatible with [GitHub Flavored Markdown](https://github.github.com/gfm/) (GFM).

Hugo supports GitHub's emoji shortcodes, with the exception of shortcodes that are unique to GitHub (e.g., `:octocat:`).

Here is the the list of supported shortcodes:
<https://github.com/ikatyang/emoji-cheat-sheet/#readme>

There are 1877 shortcodes (including 43 aliases), 22 of which are unique to GitHub.

Again, sorry for the change, but it was necessary.

**Comment by tobihagemann** [comment]
No worries, thank you for the detailed explanation and references. They help me a lot for the transition.
