### ISSUE TITLE
Always add a trailing slash if missing to the configured baseURL

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11669]
E.g. 

* `https://example.com` => `https://example.com/`
* `https://example.com/docs` =>  `https://example.com/docs/`

This is an example of why it can be problematic to expose configuration as API (`site.BaseURL`).

Note that to me the important part is to standardise it, so we could do 

*  `https://example.com/` => `https://example.com`

If that's considered less breaking.

Note that I strongly recommend not using `site.BaseURL´ to construct URLs.

/cc @jmooring

**Comment by jmooring** [comment]
I'd say deprecate the thing, but there'd would probably be a lot of noise.

To standardize, we should make sure it ends with a trailing slash, because I see this more often than I'd like:

```text
<link rel="stylesheet" href="{{ .Site.BaseURL }}css/foo.css">
```

**Comment by bep** [comment]
Yea, and I guess most browsers would be fine with ...

```
<link rel="stylesheet" href="https://example.org//scss/foo.css">
```

**Comment by jmooring** [comment]
Can we add the trailing slash only when it doesn't already exist?

**Comment by jmooring** [comment]
Oh, nevermind, you're going to do that anyway. You were referring to this example:

    <link rel="stylesheet" href="{{ .Site.BaseURL }}/css/foo.css">

**Comment by bep** [comment]
>Can we add the trailing slash only when it doesn't already exist?

Yea, that's the plan.

**Comment by SamusAranX** [comment]
> Note that I strongly recommend not using `site.BaseURL´ to construct URLs.

As someone who's currently doing just that in a theme and an atom feed template, what should I use as a replacement?

**Comment by jmooring** [comment]
<https://gohugo.io/functions/urls/abslangurl/>
<https://gohugo.io/functions/urls/absurl/>
<https://gohugo.io/functions/urls/rellangurl/>
<https://gohugo.io/functions/urls/relurl/>
