### ISSUE TITLE
`fingerprint` resources not working on multihost except the default site

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#11661]
```go
{{ range .Page.Resources.Match "sample*" }}
  {{ $img := . | fingerprint }}
  <a href="{{ $img.RelPermalink }}" target="_blank">{{ .RelPermalink }}</a>
  <img src="{{ $img.RelPermalink }}" style="width: auto; height: 200px;">
{{ end }}
```

```toml
[languages.en]
weight = 1

[languages.zh-hans]
weight = 2
baseURL = "https://zh-hans.example.org/"
```

Content strucutre

```sh
$ tree content/hello
├── index.md
├── index.zh-hans.md
├── sample.gif
└── sample.jpg
```

The fingerprint resources won't be published to sites folder except the default site.

```sh
$ hugo

$ ls public/en/hello  
index.html                                                                   sample.gif
sample.862081bdf97cf8ca7ff865d76807d567830c9a0fa00ebd185be19eec4f09e7a2.gif  sample.jpg
sample.e2298d882fc6cabe5eda75d0efb87f4c42b506cff19fa60aed8104d07a585013.jpg

$ ls public/zh-hans/hello              
index.html  sample.gif  sample.jpg
```

![image](https://github.com/gohugoio/hugo/assets/17720932/ae878dcd-4252-4116-9c6e-9a7a0c296e88)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.120.3-a4892a07b41b7b3f1f143140ee4ec0a9a5cf3970+extended linux/amd64 BuildDate=2023-11-01T17:57:00Z VendorInfo=snap:0.120.3
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by bep** [comment]
Looking at your example, I suspect this is for page resources only (`.Resources`). I would surprised if this was also broken for `/assets` -- as that is a very common pattern (fingerprinting CSS files).

**Comment by bep** [comment]
I'm in the finishing section of rewriting/improving how we do the above, so I have put this on the #11549 list of things I will check.

**Comment by razonyang** [comment]
> Looking at your example, I suspect this is for page resources only (.Resources).

You're right, I used fingerprint for my styles and JS as well, both of them works as expected.

**Comment by bep** [comment]
A quick note; there's certainly a bug here, but even for multihost setups there will be resources that's shared between languages (which gets even more true in next Hugo where we stop duplication of bundled resources), which means that:

* `.RelPermalink` will always work and point to a file that's below each host root.
* `.Permalink` will for these shared resources point below the language's host baseURL.
