### ISSUE TITLE
navigation: Don't export either MenuEntry.IsEqual or MenuEntry.IsSameResource 

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11670]
I can't come up with a scenario where either of these is useful in a menu template.

**Comment by bep** [comment]
Note that we have other cases of exported fields/methods that I have marked as internal in the Go doc (typically interface methods), which means that they should not be documented or used in templates -- and can be renamed/removed at any moment.

I haven't looked at these 2, but

1. If they're not used outside of package, unexport.
2. If it's simple to make it into a func (which it is in this case), do that.
3. Else, add a "This method is for internal use only ..." comment as a comment.
