### ISSUE TITLE
Window scoop install hugo-extended is installing old version of hugo.

### ISSUE THREAD

**Issue by nikhil00shinde** [gohugoio/hugo#11672]
`scoop install hugo-extended` is installing 0.104.5 version of Hugo. It is causing lot's of issue while executing further commands like `hugo new content posts/my-first-post.md` if the version is older it will not run properly. 

I would propose to use `scoop install hugo-extended@new-current-version`, it has drastically reduced my time to resolve issue.

**Comment by jmooring** [comment]
I am unable to reproduce the problem.


![Screenshot 2023-11-05 070625](https://github.com/gohugoio/hugo/assets/335669/4756586f-f7fb-4cdf-86a6-516217f0f8f6)
