### ISSUE TITLE
localization date format for month only

### ISSUE THREAD

**Issue by rainerrose** [gohugoio/hugo#11673]
On https://gohugo.io/functions/time/format/#localization I didn't find a localization date format for month only.

It would be nice for archive pages for example

![month](https://github.com/gohugoio/hugo/assets/99129105/d939dcc8-d6a6-4c2f-93c0-ef4951833647)

for automatic and continuous translation (1) versus (2) like as requested on 

https://github.com/razonyang/hugo-theme-bootstrap/issues/1003#issuecomment-1793743831

**Comment by jmooring** [comment]
Just use the month layout string.

```
{{ .Date | time.Format "January" }}
```

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by rainerrose** [comment]
Oh sorry for that. I will consider it next time.
