### ISSUE TITLE
' page' used in a shortcode presents some not so consistent behaviour 

### ISSUE THREAD

**Issue by fenix011** [gohugoio/hugo#11686]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

0.120 ( it occurs with recent previous versions, too ...)
more precisely : 
hugo v0.120.3
</pre>

### Does this issue reproduce with the latest release?

Yes

---

**Description** : 

```
{{ page.File.BaseFileName }}
```

' page' used in a shortcode presents some not so consistent behaviour : problems occurs only on the first 'hugo server' run, as can be seen in  [a full 10' screencast here](https://data.librebytes.org/s/KeBjyNJJnGHfAZq)

Are we missing something else here ?

Is anything else needed for a proper report ? Just let us know...

**Comment by jmooring** [comment]
<https://gohugo.io/functions/global/page/#be-aware-of-caching>
