### ISSUE TITLE
Add Hugo version to RSS </generator>

### ISSUE THREAD

**Issue by GreenLunar** [gohugoio/hugo#11692]
From: https://ftw.lol/index.xml

Notice element `</generator>`.
```
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>FTW.LOL</title>
<link>//ftw.lol/</link>
<description>Recent content on FTW.LOL</description>
<generator>Hugo -- gohugo.io</generator>
<language>en</language>
<copyright>© 2023 FTW.LOL</copyright>
<lastBuildDate>Tue, 12 Sep 2023 00:00:00 +0000</lastBuildDate>
<atom:link href="//ftw.lol/index.xml" rel="self" type="application/rss+xml"/>
<item>
```
So we know what version we refer to. See #11691

**Comment by jmooring** [comment]
Closing. `disableHugoGeneratorInject` is not exposed to the templates, so there is no way for site authors to opt-out.

**Comment by jmooring** [comment]
Re-open. We're already injecting  <generator>Hugo -- gohugo.io</generator>. Add version doesn't hurt anything.
