### ISSUE TITLE
Binary with name "npx" not found

### ISSUE THREAD

**Issue by jzbor** [gohugoio/hugo#11705]
Hi,
I am trying to build my page using [this](https://github.com/michaelneuper/hugo-texify3) theme, which requires postcss, with Nix.
I have tried adding all the necessary packages as input dependencies, which did not work.
Then I tried creating a FHS environment and running hugo inside of that. This did not work either. In both cases `npx` was available in the `$PATH`, while hugo was complaining it was unable to find it.

The error message is the following:
```
Start building sites … 
hugo v0.120.3+extended linux/amd64 BuildDate=unknown VendorInfo=nixpkgs

ERROR POSTCSS: failed to transform "css/content.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: binary with name "npx" not found
ERROR POSTCSS: failed to transform "css/index.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: binary with name "npx" not found
ERROR POSTCSS: failed to transform "css/single.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: binary with name "npx" not found
ERROR POSTCSS: failed to transform "css/list.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: binary with name "npx" not found
Total in 8139 ms
Error: error building site: POSTCSS: failed to transform "css/common.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: binary with name "npx" not found
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.120.3+extended linux/amd64 BuildDate=unknown VendorInfo=nixpkgs
</pre>

**Comment by jmooring** [comment]
Which theme? You linked to this issue, not the theme.

**Comment by jzbor** [comment]
Oh sorry, forgot to add in the link - fixed it.
It's this one: https://github.com/michaelneuper/hugo-texify3

**Comment by jmooring** [comment]
```
hugo v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df+extended linux/amd64 BuildDate=2023-11-08T11:18:07Z VendorInfo=gohugoio
```

Works for me on Ubuntu:

```text
hugo new site mysite
cd mysite/
git init
git submodule add https://github.com/michaelneuper/hugo-texify3 themes/hugo-texify3
echo "theme = 'hugo-texify3'" >> hugo.toml
cp themes/hugo-texify3/{package*,postcss*} .
npm ci
hugo
```

**Comment by jzbor** [comment]
Seems to work, although I am still not sure, why I am not able to use this with just the binaries and the `npm ci` call does not seem to be documented anywhere.

**Comment by jmooring** [comment]
<https://docs.npmjs.com/cli/v8/commands/npm-ci#description>

**Comment by jzbor** [comment]
No I mean it is not documented that this is necessary for Hugo Pipes to work correctly

**Comment by jmooring** [comment]
You can use either `npm ci` or `npm install`, but `npm ci` is safer.
