### ISSUE TITLE
Manual Summary Shows Image alt Text

### ISSUE THREAD

**Issue by LyonsTechLLC** [gohugoio/hugo#11703]
v0.116.1

Blog summaries set manually with `<!--more-->` cause image alt text to show in the summary -

If I have the following blog post
```
![Database Image](database.png)

Manual summary shows the image alt text
<!--more-->
```

the summary shows as follows -
![image](https://github.com/gohugoio/hugo/assets/129676761/f62d058b-91e4-4509-8144-9efd1624a679)

If I don't manually set the summary and remove `<!--more-->` , the alt text does not show -
![image](https://github.com/gohugoio/hugo/assets/129676761/e55c48d3-4b0c-4371-8f2f-316f9148534d)

**Comment by jmooring** [comment]
I am unable to reproduce the behavior as described. Please try this:

```text
git clone --single-branch -b hugo-github-issue-11703 https://github.com/jmooring/hugo-testing hugo-github-issue-11703
cd hugo-github-issue-11703
hugo server
```

Files of interest:

- content/_index.md (the markdown)
- layouts/_default/home.html (the template that calls `.Summary`)

**Comment by LyonsTechLLC** [comment]
@jmooring I am also unable to reproduce this issue. I haven't seen it pop up again since the day after I reported the issue!
