### ISSUE TITLE
Create AutoOrient image filter

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11717]
This would allow users to fix orientation issues when `.Exif.Tags.Orientation` is one of 2, 4, 5 or 7.

Ref: <https://discourse.gohugo.io/t/image-processing-rotates-images/>

**Comment by jmooring** [comment]
Misc thoughts...

Is there much of a performance hit for reading the EXIF info every time?

Is there a circumstance where users might want to flip x/y even when .Exif.Tags.Orientation is 0 or 1?

**Comment by bep** [comment]
>Is there much of a performance hit for reading the EXIF info every time?

No (there is a one time cost)

I borrowed this from somewhere:

<img width="805" alt="image" src="https://github.com/gohugoio/hugo/assets/394382/f5638764-0084-4d97-b473-48e7e5b6e34b">


>Is there a circumstance where users might want to flip x/y even when .Exif.Tags.Orientation is 0 or 1?

Maybe, but the use case we're talking about here is to get the image back in normal orientation, so a `images.Orientation`that by default took no arguments should be good.

I suspect that `images.Flip` would also be useful, but slightly hard to use for the use case above.

**Comment by jmooring** [comment]
I have a working implementation of this as a _function_...

```text
{{ with resources.Get "Landscape_7.jpg" }}
  {{ with images.AutoOrient . }}
    <img src="{{ .RelPermalink }}" width="{{ .Width }}" height="{{ .Height }}" alt="">
  {{ end }}
{{ end }}
```

...but have not been able to figure out how to access the EXIF data from a filter.

<details>
<summary>tpl/images/images.go</summary>

```go
func (ns *Namespace) AutoOrient(i images.ImageResource) (images.ImageResource, error) {
	var filters = map[int]gift.Filter{
		2: gift.FlipHorizontal(),
		3: gift.Rotate180(),
		4: gift.FlipVertical(),
		5: gift.Transpose(),
		6: gift.Rotate270(),
		7: gift.Transverse(),
		8: gift.Rotate90(),
	}

	if i.Exif() != nil {
		orientation := i.Exif().Tags["Orientation"].(int)
		if orientation > 1 {
			return i.Filter(filters[orientation])
		}
	}

	return i, nil
}
```
</details>

**Comment by bep** [comment]
@jmooring re. filter vs method, I think I had the same "head scratcher" when implementing the Process filter, which I implemented using an interface to pass the "filter options" back to where the filters are applied:

https://github.com/gohugoio/hugo/blob/master/resources/images/process.go#L26

You could e.g. create a new interface ala:

```go

type ImageFilterFromOrientationProvider interface {
   AutoOrient(orientation int) gift.Filter
}
```

And then adjust `imageResource.Filter` to check for the above interface.

**Comment by bep** [comment]
Thinking about the above, I suspect it's cleaner to do something ala:


```
type ImageFilterInitOrientationProvider interface {
   InitOrientation(orientation int)
}
```

And keep all the. orientation logic in the filter.

**Comment by bep** [comment]
I deleted my last comment, that doesn't make sense (we cannot modify the filter), I suggest we do as suggested above, with that we can return `nil` for "no orientation change".
