### ISSUE TITLE
Allow customizing the auto-generated root index.html in a multi-language configuration

### ISSUE THREAD

**Issue by dhilgarth** [gohugoio/hugo#11720]
Currently, if I enable multiple languages and set `defaultContentLanguageInSubdir = true`, hugo automatically generates an index.html in the root directory which redirects to the default language.

I would like a way to customize this file. In my specific case, I would like to add several meta tags around CSP to satisfy validation tools and I also want to change the redirect to use the browser language to determine the target of the redirect.

**Comment by jmooring** [comment]
The built-in template for alias files is here:
<https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/alias.html>

Override this by creating layouts/alias.html.

Then you can do something like:

```go-html-template
{{- if .Page }}
<!DOCTYPE html>
<html lang="{{ site.Language.LanguageCode }}">
  <head>
    <title>{{ .Permalink }}</title>
    <link rel="canonical" href="{{ .Permalink }}">
    <meta name="robots" content="noindex">
    <meta charset="utf-8">
    <meta http-equiv="refresh" content="0; url={{ .Permalink }}">
  </head>
</html>
{{- else }}

WHATEVER YOU WANT IN THE ROOT OF THE SITE

{{- end }}
```

**Comment by dhilgarth** [comment]
Awesome, that's perfect, thanks!

**Comment by jmooring** [comment]
Use the global `site` function to get home page URLs, language codes, etc.

```
{{ range site.Sites }}
  {{ .Home.Permalink }}
  {{ .Language.LanguageCode }}
{{ end }}
```
