### ISSUE TITLE
When use hugo -D generate public fold. please do not generate fold for markdown files. So we can look image in vscode and hugo web without fix relative path

### ISSUE THREAD

**Issue by zhenda-hub** [gohugoio/hugo#11731]
When I write markdown files(first.md) using editors such as typora and vscode, I usually use relative paths to reference local images. But when putting the markdown file into hugo, in order to display the image. I would set up the project directory structure like this:

content
│
├───posts
│   │   emoji-support.md
│   │   _index.md
│   │
│   └───first
│       │   first.md
│       │
│       └───imgs
│               1.jpg
│               2.jpg
│               3.jpg
│
└───series
    └───themes-guide
            _index.md

But when I using "hugo -D" to generate the public folder. I got directory structure like this:

public
│   404.html
├───posts
│   │   index.html
│   │   index.xml
│   │
│   ├───emoji-support
│   │       index.html
│   ├───first
│   │   ├───imgs
│   │   │       1.jpg
│   │   │       2.jpg
│   │   │       3.jpg
│   │   │
│   │   └───first
│   │           index.html

So  in order to display image（1.jpg） in hugo web, I need to modify the relative path:
" ./imgs/1.jpg"  -> "../imgs/1.jpg" to show .

I hope that the structure of the "public" folder generated by hugo is consistent with the file structure of "content", so that it can be compatible with editors such as typora and vscode.

**Comment by jmooring** [comment]
First, your description is unreadable. Please learn to use fenced code blocks (or the ` < > ` button) when including code, directory structures, etc.

Second, the structure of the public directory _is_ consistent with the structure of the content directory, and is required for pretty URLs.

Please search the [forum](https://discourse.gohugo.io/), or raise a new question. This topic has been addressed several times in the past.
