### ISSUE TITLE
snap release cannot download theme

### ISSUE THREAD

**Issue by lrkwz** [gohugoio/hugo#11730]
Steps to reproduce:

1. Fork, clone or download a sample project as https://gitlab.com/pages/hugo/.
2. Install `git` and `go`.
3. [Install](https://gohugo.io/getting-started/installing/) Hugo.
4. Install the theme as a Hugo module:

   ```shell
   hugo mod get -u github.com/theNewDynamic/gohugo-theme-ananke
   ```
5. `watch error`

```plaintext
Error: command error: failed to load modules: failed to download modules: failed to execute 'go [mod download -modcacherw]': failed to execute binary "go" with args [mod download -modcacherw]: go: github.com/theNewDynamic/gohugo-theme-ananke@v0.0.0-20230203204610-a1a99cf12681: invalid version: unknown revision a1a99cf12681
```

Envirnoment:

* Ubuntu 22.04
* Hugo 0.120.4
* go version go1.21.4 linux/amd64

installed from snap

```plaintext
> snap list hugo
Name  Version  Rev    Tracking       Publisher     Notes
hugo  0.120.4  17734  latest/stable  hugo-authors  -
```

Reported on https://gitlab.com/pages/hugo/-/issues/94

**Comment by jmooring** [comment]
Unable to reproduce with hugo v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df+extended linux/amd64 BuildDate=2023-11-08T11:18:07Z VendorInfo=snap:0.120.4.

This is not a bug.

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
