### ISSUE TITLE
support repeated keywords in org mode files as arrays

### ISSUE THREAD

**Issue by augustfengd** [gohugoio/hugo#11743]
Hello! 

Could we be able to specify array values in org mode content over multiple lines instead of suffixing the keywords with `[]`. This would make the syntax less odd aesthetically (imo), and also allow terms to have spaces in them which is already the case for the other markup languages.

I've accidentally and pre-emptively submitted an [implementation](https://github.com/gohugoio/hugo/pull/11741) when I should've created a proposal first. 

The goal would be these two front matters are equivalent.

```org
#+categories: foo bar
#+categories: baz
```

```md
+++
categories = ['foo bar', 'baz']
+++
```

Thanks!

**Comment by jmooring** [comment]
> instead of

That's a breaking change. We'd need to support both.

@kaushalmodi @niklasfasching Thoughts?

**Comment by augustfengd** [comment]
Ah I apologize for my miscommunication. I meant to say `in addition of`: I've left in the **if** clause that handles keywords with `[]` suffixes for backward-compatibility sake.

One thing to note would be that the `[]` suffixed syntax doesn't support multi-word strings as the keyword values are going through `strings.Fields(s string)`. In other words, these would not be the same:
```org
#+categories: foo bar
#+categories: baz
```

```org
#+categories[]: foo bar baz
```

**Comment by niklasfasching** [comment]
I like it better than my `[]` hack, which was strongly guided by just wanting to expand the existing solution to other key names https://github.com/augustfengd/hugo/commit/fad183c4ae55069be9246e64ab1c8b2f43d08d06.

It does remove the ability to specify multiline strings in org front matter I gueee. I never used hugo enough to have any idea whether that's something you want to keep.

**Comment by augustfengd** [comment]
@jmooring what should be the next steps relating to this feature request?

**Comment by jmooring** [comment]
@augustfengd Testing with the current release and with your PR, it seems like the only _functional_ improvement is to allow multi-word taxonomy terms. That alone I think is a valid reason to proceed.

Note that this _is_ a breaking change for those who have been ignoring this warning for the past 4.5 years:

```text
warn: Please use '#+tags[]:' notation, automatic conversion is deprecated.
```

Applicable to taxonomies named "tags", "categories", and "aliases",  this:

```
#+tags: tag-a tag-b
```

...will produce a single term, while it used to produce two terms with a warning.

I'll re-open the PR for review.
