### ISSUE TITLE
Static files not served when deploying to GitHub

### ISSUE THREAD

**Issue by tomaszgarbus** [gohugoio/hugo#11756]
My project: https://github.com/tomaszgarbus/about

Running locally everything is fine. When I deployed to GH Pages (as per https://gohugo.io/hosting-and-deployment/hosting-on-github/), the static files (from /static dir) are not found.

### What version of Hugo are you using (`hugo version`)?
hugo v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df+extended darwin/amd64 BuildDate=2023-11-08T11:18:07Z VendorInfo=brew

<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
> Static files not served

Yes, they are:
<https://tomaszgarbus.github.io/about/portrait.jpeg>

The baseURL in your site configuration is incorrect.

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
