### ISSUE TITLE
Can't build site after upgrading Hugo

### ISSUE THREAD

**Issue by sankayop** [gohugoio/hugo#11757]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.119.0-1
</pre>

### Does this issue reproduce with the latest release?
yes, I have also tried with the gohugo-extended-bin-0.120.4-1 but same error.

### Error:
ERROR render of "page" failed: "/home/me/hugoProject/layouts/_default/baseof.html:3:9": execute of template failed: template: artists/single.html:3:9: executing "artists/single.html" at <partial "head.html" .>: error calling partial: "/home/me/hugoProject/layouts/partials/head.html:3:8": execute of template failed: template: partials/head.html:3:8: executing "partials/head.html" at <partial "schema" .>: error calling partial: execute of template failed: html/template:partials/schema.html: ends in a non-text context: {stateJSDqStr delimNone urlPartNone jsCtxRegexp attrNone elementScript <nil>}

### Workaround:
downgrading package hugo (0.119.0-1 => 0.118.2-2)

**Comment by jmooring** [comment]
@sankayop A reproducible example would be helpful.

**Comment by sankayop** [comment]
Hi @jmooring , I'm not using Hugo on a regular basis so it takes a bit of an effort to get the smallest case but.
Here's a howto to get the error from scratch:
'''
hugo new site quickstart
cd quickstart
git init
cd themes
git clone https://github.com/appernetic/hugo-nederburg-theme.git
cd ..
rm -rf content layouts static hugo.toml
cp -r themes/hugo-nederburg-theme/exampleSite/* .
'''

then remove following lines from following files:
>themes/hugo-nederburg-theme/layouts/partials/head.html:25-28
>themes/hugo-nederburg-theme/layouts/partials/category.html:4-9

then:
'''
hugo server
'''

and you get the site working with 0.118 but not with 0.119 and latest.

I hope it can help making Hugo better :)
btw, it looks indeed very similar to #11507

**Comment by dongorgan** [comment]
Your site has several errors and deprecated functions. Try this modified copy of your site https://filebin.net/eyok6f0unb4y5gkl. Pay attention to the `schema.html` file in particular. That's Hugo's recommended way of writing schema.

**Comment by jmooring** [comment]
The issue is simply reduced to:

```
<script>{ "a" b" }</script>
```

This is user error (missing quotation). Go's html/template package is doing the right thing.
