### ISSUE TITLE
Escape dots when title is being used as permalink

### ISSUE THREAD

**Issue by GeorgeGedox** [gohugoio/hugo#11759]
I simply think that a URL should not contain a dot if it's not an extension for a file or a TLD

Simply having this title `This is a title. Nothing more.` results in this abomination:
```
https://example.org/posts/this-is-a-title.-nothing-more./
```
Instead of this
```
https://example.org/posts/this-is-a-title-nothing-more/
```

I have no idea if this has any SEO implications or anything else but Hugo is the first project where I've seen dots not being filtered out when generating a URL.

**Comment by jmooring** [comment]
> abomination

That's an unfortunate choice of words, and probably not the best way to motivate maintainers of _any_ open source project.

**Comment by GeorgeGedox** [comment]
> > abomination
> 
> That's an unfortunate choice of words, and probably not the best way to motivate maintainers of _any_ open source project.

You are probably right but that is my personal view, I simply cannot stand that kind of URL formatting. It does not affect me as I've started using `url` property to override the url of posts containing dots in title but I've seen past issues #1885 and #3577 where this was not addressed.

It might be the developer's intention to leave the dots in the url but I think it should be at least specified somewhere that this is the intended behavior since I've never seen this before.
