### ISSUE TITLE
dataDir configuration parameter ignored in multilingual site

### ISSUE THREAD

**Issue by sebastianlacuesta** [gohugoio/hugo#11766]
### What version of Hugo are you using?

<pre>
$ hugo v0.120.3+extended linux/amd64 BuildDate=2023-11-07T23:07:34Z VendorInfo=debian:0.120.3-1

</pre>

### Does this issue reproduce with the latest release?
No

### Issue
When using multilingual site and using different `dataDir` for `languages.en` and `languages.es`, I only get data from files for the `languages.en` configuration even for pages from `languages.es`.

For example:

```yml
[languages]

  [languages.en]
  contentDir = 'content/english'
  dataDir = 'data/english'
  languageName = 'English'
  title = 'Title'
  weight = 1
  
  [languages.es]
  contentDir = 'content/spanish'
  dataDir = 'data/spanish'
  languageName = 'Español'
  title = 'Titulo'
  weight = 2
```

Either for English or Spanish, only data files from `data/english` ignoring the config setting at `[languages.es]`.

**Comment by jmooring** [comment]
The data directory is not language specific. If you place `dataDir = something` definitions under a language key in the site configuration, the `dataDir` for _all_ languages is determined by the `defaultContentLanguage` setting. 

Do it this way instead...

```text
data/
├── de/
│   └── foo.toml
└── en/
    └── foo.toml
```

```text
{{ index site.Data site.Language.Lang "foo" "bar" }}
```

If you have additional questions, please use the forum (https://discourse.gohugo.io/). Thanks.
