### ISSUE TITLE
hugo server  404 page not respect current language  in multilingual mode on Windows

### ISSUE THREAD

**Issue by wu0407** [gohugoio/hugo#11777]
My blog is available in two languages, Chinese being the primary language and English being the secondary. When accessing non-existent URLs under the English URL prefix on the Hugo server, the content will not be translated into English. However, it will be automatically translated to English when using `hugo -d`. 
The relate issue https://github.com/HEIGE-PCloud/DoIt/issues/1114

The 404 error page uses the i18n to render.  https://github.com/HEIGE-PCloud/DoIt/blob/main/layouts/404.html
```
{{- define "title" }}
    {{- T "pageNotFound" | printf "404 %v" }} - {{ .Site.Title -}}
{{- end -}}

{{- define "content" -}}
    <div class="page" id="content-404">
        <h1 id="error-emoji"></h1>
        <p class="error-text">
            {{- T "pageNotFoundText" -}}&nbsp;
            <a href="javascript:void(0);" title="{{ T `back` }}" onclick="window.history.back();"><i class="far fa-hand-point-left fa-fw"></i></a>
        </p>
    </div>
    <script type="text/javascript">
        (function() {
            var emojiArray = ['\\(o_o)/', '(˚Δ˚)b', '(^-^*)', '(≥o≤)', '(^_^)b', '(·_·)','(=\'X\'=)', '(>_<)', '(;-;)'];
            document.getElementById('error-emoji').appendChild(document.createTextNode(emojiArray[Math.floor(Math.random() * emojiArray.length)]));
        })();
    </script>
{{- end -}}

```

![image](https://github.com/gohugoio/hugo/assets/7602218/4db53893-3655-40b6-8a8d-4f29eb5f8f28)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df+extended windows/amd64 BuildDate=2023-11-08T11:18:07Z VendorInfo=gohugoio

</pre>

### Does this issue reproduce with the latest release?
Yes

1. clone the repo
```
  git clone https://github.com/wu0407/wu0407.github.io.git
```
2. start hugo server
```
hugo server --noHTTPCache --disableFastRender
```
3.  access the http://127.0.0.1:1313/en/not-exist

**Comment by jmooring** [comment]
See <https://gohugo.io/getting-started/configuration/#_404-server-error-page>

config/_default/server.toml

```text
[[redirects]]
from = '/en/**'
status = 404
to = '/en/404.html'

[[redirects]] # Default content language must be the last entry.
from = '/**'
status = 404
to = '/404.html'
```

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
