### ISSUE TITLE
Hugo 0.121.1 release notes grammar

### ISSUE THREAD

**Issue by dongorgan** [gohugoio/hugo#11788]
> The only change in this release is that the release binaries is compiled with [Go 1.21.5](https://github.com/golang/go/issues?q=milestone%3AGo1.21.5+label%3ACherryPickApproved) which contains some security fixes that's relevant for Hugo. See [here](https://groups.google.com/g/golang-announce/c/iLGK3x6yuNo) for more information.

Should read as follows 

> The only change in this release is that the release binaries are compiled with [Go 1.21.5](https://github.com/golang/go/issues?q=milestone%3AGo1.21.5+label%3ACherryPickApproved) which contains some [security fixes](https://groups.google.com/g/golang-announce/c/iLGK3x6yuNo) that are relevant for Hugo.

**Comment by jmooring** [comment]
Updated.

**Comment by dongorgan** [comment]
Cheers. It is necessary to avoid words like `here` or `click here` as anchor links in A11y.
