### ISSUE TITLE
"hugo new theme" should not impose license

### ISSUE THREAD

**Issue by udf2457** [gohugoio/hugo#11792]
Might I humbly suggest that `hugo` is overstepping the mark by imposing a default MIT license when `hugo new theme` is run.

To speak frankly, it's none of hugo's business what license people use, and its certainly not hugo's business to push a specific license.

Therefore I suggest running `hugo new theme` should result in:

1. an empty `LICENSE` file that has nothing in it except a basic placeholder comment that is nothing more than a clear call-to-action for people to put their choice of license there.
2. the `theme.toml` should also not make reference to MIT, the `license` parameter should be empty

**Comment by jmooring** [comment]
Perhaps there's a language barrier here, but the Hugo project is neither "imposing" nor "pushing" anything.

This is about providing a sensible default. In the context of publishing a theme to <https://themes.gohugo.io/>, omitting a license or including a blank license is not a sensible default.
