### ISSUE TITLE
Hugo 0.121.X Is unable to render site - Content not detected unless renamed while livereload is runnning

### ISSUE THREAD

**Issue by hlpmenu** [gohugoio/hugo#11799]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ 0.121.1 / 0.121.0

</pre>

### Does this issue reproduce with the latest release?
Yes, no change was made to any layout or content files from when it worked on earlier versions.

### System 1
Windows 11
Go 1.20
Hugo 0.121.0
Node.js v18

Editor Vscode
Terminal: Powershell 7

### System 2
Ubuntu 22.04 LTS minimal install
Go 1.21.5
Hugo 0.121.1
Node.js v21

Editor: vscode
Shell: Fish

### Can the issue be replicated on new projects?
Yes

### How i use hugo
I use the /content files just for front matter. In the FM im setting things like url, type,  layout etc, and then use it for SEO data, and for static schema.org script added as a script tag in a parameter.
**Please note the issue persists even with empty or very basic .md files**
Then i specify a unique layout file for each page, where i do If

### Description
Hugo does not detect .md files in the content directory in the latest update. Ive spent hours during the last 3 days troubleshooting it and finding that Hugo does not detect the files at all.
The issue is replicated on both Windows 11(i dont have my exact win 11 version in fromt of me atm)
And ubuntu 22.04 LTS.

Ive created new sites and was able to replicate the issue all the time. 

### Only works when renaming
The only way to get Hugo to detect the content files is to do the following:
1. Run hugo server
2. When server is running, rename the .md file, as an example, "start.md" to anything, like lets say "s.md".
3. livereload then detects the change as "change RENAMED" and "change CREATED" in the console. Now the page works and hugo is reading the file.

When running hugo build then it once again dosent detect the files.

### Troubleshooting

- Reinstalled hugo multiple times using different methods on multiple OS:s and the issue persist.

-Put non-working yaml, html and markdown in the md files that usually would throw an error, but its not detected.

- Created a new site and new files

-Checked the files for bom charachters in both file content and filename.

- Used a standard hugo config, specified content path using both methods in config. Specified config with --config.

- Tested with yaml, toml, json for config and fromt matter.

- hugo.stats.json is not getting the classes for the layouts file used for the non-found .md files.

- Hugo list all lists one file.

- All md files and layout files are valid.

- In ubuntu premissions is set to 777 for the project dir and files

- Ran without post processing.

##
EDIT:
Ive looked at it more and managed to get it to render one of the pages by:
Adding content to the .md while hugo server was running(the pages still was not being served).
Stopping hugo server and immediately running "hugo" without any extra arguments.

That the only way it rendered a page

**Comment by jmooring** [comment]
Unable to reproduce as described.  Please continue the discussion here:
<https://discourse.gohugo.io/t/47439>
