### ISSUE TITLE
Don't make draft/future/expired pages of branch nodes recursively disabled

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11809]
This will be a breaking change for some, but it's meant well -- the current behaviour of special handling taxonomy pages is confusing and less flexible than it could be.

Currently, when we draft a taxonomy page (or e.g. mark it to be published in the future or it's expired):

`categories/_index.md`:

```md
---
title: "The Categories"
draft: true
---

Content.
```

We hide the entire tree from `/categories` and down.

The original intent/semantics of `draft` was to delay publishing of that particular page/content, so with this change we make kind=taxonomy work the same as sections. So, we say:

* For regular pages (leaf nodes) and term pages, the `Page` it's just removed/ignored.
* For home, section, taxonomy
    * we keep the Page node to make the page tree fully navigable.
    * the Page is not rendered and not in any page collection.
    * but you can reach it with `site.GetPage` (and the taxonomy in `site.Taxonomies`).

**Comment by jmooring** [comment]
Seems like the options are...

A. Don't include the term in the taxonomy object
B. Include the term in the taxonomy object, but don't render the term page
C. Include the term in the taxonomy object, and render the "automatic" term page

I'm leaning towards B.

**Comment by jmooring** [comment]
Whatever we choose, behavior should be the same for future/expired.

**Comment by bep** [comment]
I think my thinking is in line with your B, which is in line with how drafted sections work:

* We don't render the list page.
* We keep the page object to make the structure navigable.
* We don't list it anywhere (e.g. site.Pages), but you can reach it via `site.GetPage` and, I guess, also `site.Taxonomies`.

>Whatever we choose, behavior should be the same for future/expired.

Sure, I just used draft as an example.
