### ISSUE TITLE
Mentions of .Site.GoogleAnalytics

### ISSUE THREAD

**Issue by ashtallama** [gohugoio/hugo#11801]
This file has several mentions of `.Site.GoogleAnalytics` that was recently deprecated e.g 
https://github.com/gohugoio/hugo/blob/142558719324aa1628541d556ef1fa2d123f1e68/tpl/tplimpl/template_embedded.go#L241
https://github.com/gohugoio/hugo/blob/142558719324aa1628541d556ef1fa2d123f1e68/tpl/tplimpl/template_embedded.go#L253

And other deprecated features like `.Site.Social` and `.Site.Author` and

https://github.com/gohugoio/hugo/blob/142558719324aa1628541d556ef1fa2d123f1e68/tpl/tplimpl/template_embedded.go#L221

**Comment by jmooring** [comment]
You're looking at a very old commit. The file in question, tpl/tplimpl/template_embedded.go, was removed over 5 years ago with the release of v0.41.0.
