### ISSUE TITLE
Make og:type configurable for .IsPage

### ISSUE THREAD

**Issue by ashtallama** [gohugoio/hugo#11803]
See https://support.google.com/news/publisher-center/thread/123693300?hl=en&msgid=123694514

This can be set in the config, preferably via params.

https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html#L3

**Comment by jmooring** [comment]
This should be handled by site and theme authors by overriding the embedded template to use something under `.Site.Params`.

**Comment by ashtallama** [comment]
I rolled my own using a WP plugin meta.
