### ISSUE TITLE
Omit `UA-` part in GA template

### ISSUE THREAD

**Issue by ytrepidorosonomous** [gohugoio/hugo#11802]
With `UA-` deprecated, I think this part can be omitted?

https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/google_analytics.html#L14

cc @jmooring

**Comment by coliff** [comment]
I agree that it can be removed. This part can be removed too:
```
{{ if $pc.AnonymizeIP }}ga('set', 'anonymizeIp', true);{{ end }}
```
Such an option does not exist at all with GA4 - all hits are anonymized by default and it's impossible to change that.
REF: https://support.google.com/analytics/answer/2763052?hl=en#:~:text=In%20Google%20Analytics%204%2C%20IP%20masking%20is%20not%20necessary%20since%20IP%20addresses%C2%A0are%20not%20logged%20or%20stored.

**Comment by flexxgaad** [comment]
Agreed

**Comment by yaardie** [comment]
Related to #10093 . This looks like a simple fix.
