### ISSUE TITLE
read images in JPEG XL format 

### ISSUE THREAD

**Issue by snicolai** [gohugoio/hugo#11806]
With Safari shipping JPEG XL support, I'd like to experiment with that, as it can make images quite a bit smaller.  Here's an example of how I would like to load and interact with a JPEG XL image.  This is an example of how I use the loaded image from a render-image template. 

```
{{- $src := .Page.Resources.GetMatch (printf "%s" (.Destination)) -}}
{{- if $src -}}

{{- $imgWidth := $src.Width -}}
{{- $imgHeight := $src.Height -}}
{{- with $src.Exif -}}
  {{- $o := .Tags.Orientation -}}
  {{- if or (eq $o 6) (eq $o 8) -}}
    {{- $imgWidth = $src.Height -}}
    {{- $imgHeight = $src.Width -}}
  {{- end -}}
{{- end -}}
/* a bunch of logic here removed that uses $src.RelPermalink */
{{- end -}}
```

**Comment by jmooring** [comment]
Adding decode/encode support for JPEG XL is not going to happen.

1. The only browser to support this format is Safari (https://caniuse.com/?search=JPEGXL)
2. No one has written a native (Go) decoder/encoder
