### ISSUE TITLE
Methods for recently changed  and new files

### ISSUE THREAD

**Issue by privatemaker** [gohugoio/hugo#11811]
I don't know anything about Hugo's internals, nor how to suggest implementing this feature- but I think it would be quite useful to have a site method such as `.Site.RecentlyChanged` which returns a list of files in `content/` and `data/` directories that have recently changed.

Perhaps also `.Site.NewFiles` which could track the `static/` directory, or that could be included in the former method.

This would enable things like [Recent Changes](https://en.wikipedia.org/wiki/Special:RecentChanges?hidebots=1&hidecategorization=1&hideWikibase=1&limit=50&days=7&urlversion=2) page on MediaWiki, as well as [history](https://en.wikipedia.org/w/index.php?title=Static_site_generator&action=history) of a given page.

As far as I can tell, the only way to track new content is with `date` values specified in the frontmater. If there is some way that I am unaware of, perhaps the Docs just need to be updated!!

**Comment by jmooring** [comment]
### Recently modified content

To get a list of recently modified content files...

#### site configuration

```
frontmatter]
lastmod = [':git','lastmod',':fileModTime','date']
```

This will set the `lastmod` date to the last commit date, falling back to `lastmod` in front matter, falling back to OS file modification time, falling back to the `date` field in front matter (or inferred from file name).

See <https://gohugo.io/getting-started/configuration/#configure-dates>.

#### template

This will display the last 5 modified regular pages (excludes home, section, taxonomy, and term pages):

```
{{ range (site.RegularPages.ByLastmod.Reverse.Limit 5) }}
  <h2><a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a></h2>
{{ end }}
```

### Recently created content

Assuming you use front matter date (or the date inferred from the filename) as the creation date...

This will display the last 5 "created" regular pages (excludes home, section, taxonomy, and term pages):

```
{{ range (site.RegularPages.ByDate.Reverse.Limit 5) }}
  <h2><a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a></h2>
{{ end }}
```

### Data files

I would handle this with a script that creates a `/data/metadata.yaml` file, with an entry for each data file, with each entry containing a create and modified date.

**Comment by jmooring** [comment]
Closing this in favor of the existing capabilities described above.

**Comment by privatemaker** [comment]
@jmooring I had not ever used `lastmod` param before. Thank u for taking time to explain these options. Perhaps it would be helpful to add a bit more examples to the docs [RegularPages](https://gohugo.io/methods/site/regularpages/). The link to [sorting methods](https://gohugo.io/methods/pages/) is not as straight forward, intuitive, and educational as it could be.

---

If I understand the second part of what I described above:

> This would enable things like Recent Changes page on MediaWiki, as well as history of a given page.

Would only be possible by using the technique you propose, but then filtering out all but the given file- if that is even possible. Is this correct understanding?

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
