### ISSUE TITLE
Page https://gohugo.io/overview/installing/ - doesn't exists

### ISSUE THREAD

**Issue by lukasz-cpu** [gohugoio/hugo#11814]
Site 

https://gohugo.io/overview/installing/

is not working properly

![firefox_YASkDvccY2](https://github.com/gohugoio/hugo/assets/22981511/a76cd70b-2232-4241-b6ff-facf3923db43)

Transition is coming from this page

![site2](https://github.com/gohugoio/hugo/assets/22981511/088e386e-5013-47d0-a8bb-7632d3d122d9)

**Comment by jmooring** [comment]
Please raise an issue here:
<https://github.com/zhaohuabing/hugo-theme-cleanwhite>
