### ISSUE TITLE
Adding a --datePrefix flag to new content generator

### ISSUE THREAD

**Issue by privatemaker** [gohugoio/hugo#11824]
When working on websites whereby content file naming scheme is:

```
content/
├── blog
│   ├── 2023-08-31-newsletter-1.md
│   ├── 2023-09-30-newsletter-2.md
│   ├── 2023-10-31-newsletter-3.md
...
```

AFAICT, it is not possible to specify the year part in file name `2023-08-31-` unless you do command like:

```
hugo new content content/blog/2023-11-31-newsletter-4.md
```

This works, but if one is injecting the `{{ replace .File.ContentBaseName `-` ` ` | title }}` value in the template, you end up with a title such as: `2023 11 31 Newsletter 4` which is undesirable. 

Perhaps adding flag like `--datePrefix` would do the trick?

```
hugo new content --datePrefix content/blog/2023-11-31-newsletter-4.md
hugo new content --datePrefix content/blog/newsletter-4.md
```

The first option would strips out the date from title (perhaps needing a new value in the archetype). The second option would inject date into filename. Or is some other approach that is preferable or is this just a bad idea?

**Comment by jmooring** [comment]
This is simple to achieve via configuration and archetypes...

### site config

This will set the content `date` to the leading yyyy-mm-dd value, and will use the rest of the file name to set the `slug`:

```
[frontmatter]
date = [':filename', ':default']
```

The `date` will be in the Etc/UTC time zone unless you specify `timeZone = 'something'` in your site configuration.

See <https://gohugo.io/getting-started/configuration/#configure-dates>.


### archetype

```text
+++
title = '{{ replaceRE `^\d{4}-\d{2}-\d{2}-` "" .File.ContentBaseName | replaceRE `-` " " | title }}'
draft = false
+++
```

Note that we don't include a `date` field; there's no need. With the site configuration above, the date is extracted from the filename, but can be overridden as needed by adding a `date `field to your front matter.

Capitalization is determined by the `titleCaseStyle` in your site configuration.

### result

When you do this:

```text
hugo new posts/2023-03-01-my-first-post.md
```

The content file will look like this:

```text
+++
title = 'My First Post'
draft = false
+++
```

And the published site will have this structure:

```text
public/
├── posts/
│   ├── my-first-post/
│   │   └── index.html
│   └── index.html
├── favicon.ico
└── index.html
```

Set [`permalinks`](https://gohugo.io/content-management/urls/#permalinks) in your site configuration to alter the final URLs.

**Comment by jmooring** [comment]
Closing this in favor of the existing capabilities described above.

**Comment by privatemaker** [comment]
@jmooring this makes sense to not bother including such a flag 👍🏻 Perhaps worth adding to [Archetypes](https://gohugo.io/content-management/archetypes/) or elsewhere?
