### ISSUE TITLE
disableKinds: no error when using something invalid

### ISSUE THREAD

**Issue by godalming123** [gohugoio/hugo#11822]
There is no error/warning displayed when `disableKinds` has an invalid value:
```
disableKinds = [ 'somerandomval' ]
```
Having an error is useful because when a user tries to disable part of hugo's built in functionality, they should know if their `disableKinds` option is actually doing anything.
### What version of Hugo are you using (`hugo version`)?
`hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740 linux/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=gohugoio`
### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
Unable to reproduce with v0.121.1

site config

```text
disableKinds = ['somerandomval']
```

build

```text
WARN  Unknown kind "somerandomval" in disableKinds configuration.
Start building sites … 
hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended linux/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=gohugoio
```
