### ISSUE TITLE
Indentation of YAML multiline strings is inconsistent

### ISSUE THREAD

**Issue by concretevitamin** [gohugoio/hugo#11829]
In https://blog.skypilot.co/analyzing-the-whole-mouse-brain-atlas-on-the-cloud-with-skypilot/#create-a-vm-with-a-very-basic-yaml-file I have a `yaml` codeblock:
```yaml
...
setup: |
  pip install --upgrade pip
  conda env update -f /home/analysis/env.yaml  

run: |
  nohup jupyter-lab --no-browser --port 8888 &
```
As you can see, 
- The `setup` multiline string has 2 lines, and are indented 2 spaces;
- The `run` multiline string has 1 line, and is indented 4 spaces.

In the markdown source, both multiline strings are indented 2 spaces.

Anyway to fix this?

Filed https://github.com/adityatelange/hugo-PaperMod/issues/1227 originally and was told this could be a Hugo issue.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.84.4+extended darwin/amd64 BuildDate=unknown
</pre>

**Comment by jmooring** [comment]
This issue was resolved about 9 months ago in v0.111.0 with https://github.com/gohugoio/hugo/pull/10695. Please upgrade.
