### ISSUE TITLE
Static file path not correct

### ISSUE THREAD

**Issue by ithelpm** [gohugoio/hugo#11832]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended windows/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=gohugoio
</pre>

Hello I'm new here and I was trying using a markdown to get my static file like:
`![An Icon](/icon.png)`
and it was response a 404 not found
But if I'm using 
`![An Icon](../../icon.png)`
It will appear as what I expect
It seems like I have to access my static file with relative path.

Note: I'm new here and there's lot's more thing I still learning, If anything wrong please tell me🙏

With my Structure of content:
my-site/
├── archetypes/
├── assets/
├── content/
│      └──posts/
│              └── Post1.md
├── data/
├── i18n/
├── layouts/
├── static/
│      └──icon.png
├── themes/

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
