### ISSUE TITLE
can't evaluate field RenderString in type page.Page

### ISSUE THREAD

**Issue by cold-bin** [gohugoio/hugo#11837]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.120.0-20c3bae2c4839ec993ec3c353da4fd7b09215cd8+extended linux/amd64 BuildDate=2023-10-30T14:06:47Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
no

**Comment by cold-bin** [comment]
or is there any replace?

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by cold-bin** [comment]
`{{- $inner := .Inner | .Page.RenderString -}}`&`{{- $content := $content | .Page.RenderString  -}}`
