### ISSUE TITLE
Customizing taxonomy permalink disconnects it from content structure

### ISSUE THREAD

**Issue by ribtoks** [gohugoio/hugo#11846]
What I'm trying to accomplish: change taxonomy list page title (by creating `content/category/xyz/_index.md` and changing `title` in front matter) together with having custom url to categories (`/blog/category/xyz` instead of `/category/xyz`). 

It works as long as I don't use the permalink modification, however, after the permalink is changed, it never takes the content from `content/category` subdir. Also, if `content/category/xyz/_index.md` will move to `content/blog/category/xyz/_index.md`, it does not hook up the necessary layout, even if overriding front matter's `layout` and `type` variables (to `list` and `category` respectively).

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended linux/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
I am unable to reproduce the problem as described. Try it:

```text
git clone --single-branch -b hugo-github-issue-11846 https://github.com/jmooring/hugo-testing hugo-github-issue-11846
cd hugo-github-issue-11846
hugo server
```

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by ribtoks** [comment]
@jmooring Issue can be reproduced with your repository with a minor change: 

```diff
diff --git a/hugo.toml b/hugo.toml
index 8aeeb80..4f43bd0 100644
--- a/hugo.toml
+++ b/hugo.toml
@@ -7,10 +7,10 @@ disableKinds = ['rss','sitemap']
 category = 'category'
 
 [permalinks.taxonomy]
-category = "/blog/:sections/"
+category = "/blog/category/:slug/"
 
 [permalinks.term]
-category = "/blog/:sections/"
+category = "/blog/category/:slug/"
 
 [[menus.main]]
 name = 'Home'
```

Now, after this, run `hugo serve` and open webpage http://localhost:1313/blog/category/abc - it does not work.
