### ISSUE TITLE
Problems with the url format of images generated by hugo

### ISSUE THREAD

**Issue by Ai-feier** [gohugoio/hugo#11847]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.121.1+extended windows/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes

Problems with the url format of images generated by hugo

When I want to quote the picture.

The format is as follows.
```
! [image-20240102163407543](https://blog-source-mkt.oss-cn-chengdu.aliyuncs.com/blog_source/post/images/%E4%BC%98%E9%9B%85%E7%BB%88% E6%AD%A2.http/image-20240102163407543.png)
```

The local `hugo server` is able to display the image normally.

But when you use `hugo` to generate a website, there is an extra `/`
```
<img src="/https:/blog-source-mkt.oss-cn-chengdu.aliyuncs.com/blog_source/post/images/%E4%BC%98%E9%9B%85%E7%BB%88%E6%AD%A2.http/ image-20240102163407543.png" loading="lazy" alt="image-20240102163407543">
```

my base url is:
```yaml
bashURL: https://ai-feier.github.io
```

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
