### ISSUE TITLE
clean public

### ISSUE THREAD

**Issue by iweixubin** [gohugoio/hugo#11854]
I look forward to adding   `hugo clean`   command

I follow Hugo doc: https://gohugo.io/content-management/page-bundles/
content/
├── about
│   ├── index.md
├── posts
│   ├── my-post
│   │   ├── content1.md   // It will be generate to public directory
│   │   ├── content2.md   // It will be generate to public directory
│   │   ├── image1.jpg
│   │   ├── image2.png
│   │   └── _index.md       //  Branch bundles

after run `hugo` command,I change **_index.md** to **index.md**

content/
├── about
│   ├── index.md
├── posts
│   ├── my-post
│   │   ├── content1.md   // It will not be generate to public directory, but still in public directory
│   │   ├── content2.md   // It will not be generate to public directory, but still in public directory
│   │   ├── image1.jpg
│   │   ├── image2.png
│   │   └── index.md       //  Leaf bundles  !!!!

then, I run  `hugo` command again, but content1 and content2 still in public directory

**Comment by jmooring** [comment]
Use `--cleanDestinationDir`, but due to https://github.com/gohugoio/hugo/issues/8433 you must have a `static` directory (an empty directory is fine) in the root of your project.
