### ISSUE TITLE
`hugo mod get` always updates modules to the latest version

### ISSUE THREAD

**Issue by ajschmidt8** [gohugoio/hugo#11857]
I use a specific version of [Docsy](https://github.com/google/docsy/) (`v0.7.1`) and currently have a `go.mod` file that looks like this:

```go.mod
module github.com/my/project

go 1.21.5

require (
	github.com/google/docsy v0.7.1 // indirect
	github.com/google/docsy/dependencies v0.7.1 // indirect
)
```

Whenever I run `hugo mod get` in my project, it automatically installs the latest version of these dependencies and updates the `go.mod` file accordingly.

This is not what I would expect to happen. I would expect that my specified versions of Docsy are respected and installed.

This is an issue because the latest version of Docsy is not compatible with my current source code (it has breaking changes).

I believe I've traced this issue down to this code block:

- https://github.com/gohugoio/hugo/blob/e40b9fbbcf28c07ad90ae1048e144888414074d7/modules/client.go#L347-L360

The `go` commands that ultimately get executed here are:

```sh
go get -d github.com/google/docsy/dependencies
go get -d github.com/google/docsy
```

Since the versions of these packages (`v0.7.1`) are omitted from the `go get` commands, it seems that `go` automatically updates them to the latest version.

This issue would be resolved if the `go` commands included the package versions like this:

```sh
go get -d github.com/google/docsy/dependencies@v0.7.1
go get -d github.com/google/docsy@v0.7.1
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended linux/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
Related: https://github.com/gohugoio/hugo/issues/7475

**Comment by bep** [comment]
This is in line with the documentation, see

https://gohugo.io/commands/hugo_mod_get/

If you want to run with what you currently have in `go.mod` then don't run any `hugo mod get` command.

**Comment by bep** [comment]
Also note, that if you just want to download modules/confirm your setup without building you can do e.g.

```
hugo config
```

Or similar.

**Comment by ajschmidt8** [comment]
> Also note, that if you just want to download modules/confirm your setup without building you can do e.g.
> 
> ```
> hugo config
> ```
> 
> Or similar.

This worked. I wasn't aware of this. To my knowledge, it's not documented anywhere.

I opened up #11861 to get it documented.
