### ISSUE TITLE
single.html not render if exist a comment in his first line.

### ISSUE THREAD

**Issue by ruannawe** [gohugoio/hugo#11869]
<pre>
$ hugo version
hugo v0.121.2+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes.

### How to reproduce:

If I add a comment in the first line of the file `layouts/_default/single.html`.
```html
<!-- layouts/_default/single.html -->
{{ define "main" }}
<article>
    <header>
        <h1>{{ .Title }}</h1>
    </header>
    <section>
        {{ .Content }}
    </section>
</article>
{{ end }}
```

Will render an empty page.
![image](https://github.com/gohugoio/hugo/assets/9044734/49492d3f-6d72-4e37-b468-66cca92ac958)

If this comment is inside the "define" block will works correctly.

**Comment by jmooring** [comment]
See documentation:
<https://gohugo.io/templates/base/#override-the-base-template>

> Code that you put outside the block definitions can break your layout. This even includes HTML comments. For example...
