### ISSUE TITLE
Syntax highlighting style 'catppuccin-macchiato' not showing highlighted lines

### ISSUE THREAD

**Issue by skrysmanski** [gohugoio/hugo#11862]
When selecting 'catppuccin-macchiato' as highlighting style like so:

```yaml
markup:
  highlight:
    style: 'catppuccin-macchiato'
```

And then writing some code with highlighted lines:

    ```html {hl_lines="3 6"}
    <html>
      <head>
        <title>Hello, HTML</title>
      </head>
      <body>
        <p>Some text here</p>
      </body>
    </html>
    ```

Then the two lines are not highlighted properly:

![highlight-wrong](https://github.com/gohugoio/hugo/assets/914747/f9a2d94a-43d2-4cf9-991f-32334b47cd52)

After some digging, I found out that the 'catppuccin-macchiato' style accidentally uses `color` instead of `background-color` for its line highlighting. I.e. it uses

```css
.chroma .hl { color: #494d64 }
```

but should be using:

```css
.chroma .hl { background-color: #494d64 }
```

So if I switch this (by jumping through some hoops), it looks as expected:

![highlight-correct](https://github.com/gohugoio/hugo/assets/914747/341b9f31-be85-40a6-867a-d9b36ba58504)

I know this *might* be the wrong repo for filing this (the bug could be in the Chroma or even in the Pygments repo). Unfortunately, I'm no Go developer - so I couldn't really describe the problem in the other repos. So my hope is - if you find this bug is not a Hugo bug per se - that you'll file a bug repo in the appropriate repo. Thanks :)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended windows/amd64 BuildDate=2024-01-05T12:21:15Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
This problem was introduced in v0.119.0 when we bumped [alecthomas/chroma](https://github.com/alecthomas/chroma) from v2.8.0 to v2.9.1 with [f0d32455](https://github.com/gohugoio/hugo/commit/f0d32455d2e5648aa0d2e41cb0494db319f0b733).

Chroma introduced the problem in v2.9.0 with [0e7ec95a1](https://github.com/alecthomas/chroma/commit/0e7ec95a1d25b91a8702c08ba3f3c62d5911e3ea), which affected all four of the "catppuccin" style variants.

**Comment by icy-comet** [comment]
It was an oversight at my end @skrysmanski. Until, the embedded `chroma` version is bumped again, you could manually override the `chroma` styles as mentioned [here](https://github.com/icy-comet/catppuccin-chroma-theme).

**Comment by skrysmanski** [comment]
Thank you both for the quick work/fix. :)
