### ISSUE TITLE
imaging: Enable write to EXIF tags

### ISSUE THREAD

**Issue by jessefarinacci** [gohugoio/hugo#11874]
## Background: Hugo

Hugo currently provides read-access to EXIF data for some image formats. Hugo can also limit the EXIF fields available within the processed image, available within templates etc, but Hugo appears not to support any means of actually removing EXIF data from processed images.

Source: https://gohugo.io/methods/resource/exif/
Source: https://gohugo.io/content-management/image-processing/#imaging-configuration

## Background: EXIF

EXIF format supports a free-ish form field called `Copyright`. From the spec:

| Tag ID | Tag Name | Writable | Group | Values / Notes |
| --- | --- | --- | --- | --- |
| 0x8298 | Copyright | string | IFD0 | (may contain copyright notices for photographer and editor, separated by a newline. As per the EXIF specification, the newline is replaced by a null byte when writing to file, but this may be avoided by disabling the print conversion) |

Source: https://exiftool.org/TagNames/EXIF.html

## Feature Request

This is the specific field I'd to be able to set in order to embed my own Copyright / "Watermark" text within each image that Hugo processes. It'd be nice if I could pass it as an image resource filter with specified custom copyright message, but I'd also like to be able to set it in the Imaging configuration section of Hugo configuration. Updating the Hugo example configuration block (see link below) we'd have:

```yaml
imaging:
  bgColor: '#ffffff'
  copyright: 'Copyright example.com, John Doe, 2024. All rights reserved.'
  hint: photo
  quality: 75
  resampleFilter: box
```

Source: https://gohugo.io/content-management/image-processing/#imaging-configuration

## Bonus

**_(I'd be thrilled if we also provided some sort of `stripEXIF boolean` in the imaging configuration to remove everything except the fields set directly, e.g. the `copyright` from this request; this would provide a small measure of defense against hostile image fingerprinting attacks.)_**

**Comment by jmooring** [comment]
To clarify what Hugo does today:

```
assets/
├── a.jpg
└── b.jpg
```

With this...

```
{{ with resources.Get "a.jpg" }}
  <img src="{{ .RelPermalink }}" width="{{ .Width }}" height="{{ .Height }}" alt="">
{{ end }}
```

... the published image retains its EXIF data.

But with this (a processed image):

```text
{{ with resources.Get "b.jpg" }}
  {{ with .Resize "200x" }}
    <img src="{{ .RelPermalink }}" width="{{ .Width }}" height="{{ .Height }}" alt="">
  {{ end }}
{{ end }}
```

... all of the EXIF data is removed.

**Comment by jessefarinacci** [comment]
> ... all of the EXIF data is removed.

Woot! :) Thank you for that confirmation.

> I'd be inclined to handle this after the build

While I think that's perfectly reasonable, I'd argue that this request fits in naturally with the extended functionality that Hugo already provides for image manipulation. Hopefully the feature will be considered for development.

Thanks!

**Comment by bep** [comment]
Writing EXIF tags as in changing the image source file is not something we will ever do, I think. We could do some kind of tag "overrides" so when you do `.EXIF.Tags.Copyright` you would get the value from configuration, but theres certainly ways to do that today as well (with .Params).

**Comment by jessefarinacci** [comment]
The feature request is for processed images to contain the updated EXIF information, not to modify the original source files. Similar to how an existing Hugo image processing filter behaves today, at least from an end user perspective: with sources found under `assets/` or `content/`, and intermediate processed resources ending up in `resources/` directory, and final outputs in the `public/` directory.

I thought @jmooring indicated earlier that Hugo would strip EXIF tags, now I'm re-reading that comment and wondering if I misunderstood it to mean that `public/` images would contain no EXIF information but in reality the end images in `public/` still contain it, but that the information is simply not accessible within Hugo itself.

This isn't my hill. :) If this request is a dead end because it's out of scope, or EXIF is a hairy beast, that's fine let's close the feature request and I'll post-process via shell and dedicated tooling. The requested ability just seems like it fits in quite naturally with the other advanced image processing pipeline features of Hugo; e.g. if I wanted a traditional digital watermark, that is achievable via `images.Overlay` filtering.

Shall I withdraw this request and close the issue?

**Comment by jmooring** [comment]
> in reality the end images in public/ still contain it

a) If the image is copied from the static directory... true
b) If the image is copied as a part of a page bundle... true
c) If the image is captured as a resource (page, global, or remote) then published... true
d) If the image is captured as a resource (page, global, or remote), then processed, then published... **false**

If you have further questions about this, please create a topic in the forum (https://discourse.gohugo.io/).

> The feature request is for processed images

Understood, applicable to (d) above. You are welcome to keep this proposal open, but in my view it is unlikely to be implemented.

Handling this after the build with something like exiftool would allow you to handle all four scenarios above, not just (d), so in my view is a much better approach, not a work around.

**Comment by jessefarinacci** [comment]
Thank you everyone for the interesting discussion touching on internals, I'll close this request now to save work for the robotic janitor.
