### ISSUE TITLE
Add CSV lazyQuotes option to transform.Unmarshal

### ISSUE THREAD

**Issue by Menrath** [gohugoio/hugo#11884]
Sometimes we deal with CSV files that use lazy quotes. The Go library used already supports a setting to support this but within the hugo getCsv function we have no way to pass this as a parameter.

[Example/Background](https://stackoverflow.com/questions/31326659/golang-csv-error-bare-in-non-quoted-field)

**Comment by jmooring** [comment]
Adding this option to [`data.GetCSV`](https://gohugo.io/functions/data/getcsv/) would be messy, and at some point we should deprecate both `data.GetCSV` and [`data.GetJSON`](https://gohugo.io/functions/data/getjson/) in favor of [`transform.Unmarshal`](https://gohugo.io/functions/transform/unmarshal/).

Adding this option to `transform.Unmarshal` makes sense to me.

**Comment by Menrath** [comment]
Yes I tried to add it and make a Pull Request and stopped because it was messy and I am absolutely no golang expert.

**Comment by jmooring** [comment]
Rethinking this, does it even need to be configurable? The current behavior is to throw an error. I can't think of any downside to enabling `LazyQuotes` when using `data.GetCSV` or `transform.Unmarshal`.

**Comment by XoL1507** [comment]
can i comment here?
