### ISSUE TITLE
GetPage returns a page when I think it should return nil

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11883]
I understand that `.GetPage` on both `Page` and `Site` have some fuzziness when finding a page, but I was surprised by this.

```text
content/
├── p1/
│   ├── index.md
│   └── p1.xyz
└── _index.md
```

layouts/_default/home.html

```text
{{ with .Page.GetPage "p1.xyz" }}
  .Page.GetPage: {{ .RelPermalink }}
{{ end }}

{{ with .Site.GetPage "p1.xyz" }}
  .Site.GetPage: {{ .RelPermalink }}
{{ end }}
```

public/index.html

```text
.Page.GetPage: /p1/

.Site.GetPage: /p1/
```

I would expect both methods to return nil because p1.xyz is a page resource, not a page.

**Comment by jmooring** [comment]
It looks like `.Page.GetPage` is working as I would like with https://github.com/gohugoio/hugo/pull/11830, while `.Site.GetPage` still returns p1.

**Comment by bep** [comment]
I have rewritten all of this, but I will put this test case on my "to check list".

**Comment by bep** [comment]
This is fixed in my wip branch, but I have added a test for it.
