### ISSUE TITLE
hugo list future/expired ignores clock flag

### ISSUE THREAD

**Issue by olikami** [gohugoio/hugo#11888]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended darwin/arm64 BuildDate=2024-01-05T12:21:15Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?
Yes

---
When running `hugo list future` the ``--clock`` option is ignored.

For example, I have the following page:
```
---
title: "A few Hugo Shortcodes"
date: 2024-01-22T00:00:00
---
bla bla
```

This is the output of `hugo list future` as right now:
```
% hugo list future                                       
path,slug,title,date,expiryDate,publishDate,draft,permalink
content/posts/2024-01-22 Hugo Shortcodes/index.md,,A few Hugo Shortcodes,2024-01-22T00:00:00+01:00,0001-01-01T00:00:00Z,2024-01-22T00:00:00+01:00,false,https://oli.fyi/2024/a-few-hugo-shortcodes/
```

And this is the output if I try to set the clock for later:
```
% hugo list future --clock "2024-01-25T00:00:00.00+01:00"
path,slug,title,date,expiryDate,publishDate,draft,permalink
content/posts/2024-01-22 Hugo Shortcodes/index.md,,A few Hugo Shortcodes,2024-01-22T00:00:00+01:00,0001-01-01T00:00:00Z,2024-01-22T00:00:00+01:00,false,https://oli.fyi/2024/a-few-hugo-shortcodes/
``` 
I would expect this to not be a future page anymore, having set the clock on the 25th. It does work, and it will build it after the 22nd, but the future command is not working.

**Comment by jmooring** [comment]
Same issue with expired content.

**Comment by jmooring** [comment]
This is regression introduced in v0.112.0, related to the [fix](https://github.com/gohugoio/hugo/commit/e6dc8053bfb94063268fa56404ff076208dc6dc2) for https://github.com/gohugoio/hugo/issues/10972.
