### ISSUE TITLE
`build.buildStats` generates empty `hugo_stats.json`, but `build.writeStats` works

### ISSUE THREAD

**Issue by dvdksn** [gohugoio/hugo#11895]
When using the new `build.buildStats.enable: true` option, the hugo_stats.json is empty.
However when reverting back to the older `build.writeStats` option, hugo_stats.json has all the expected ids.

Repro with `buildStats`:

```console
$ git clone https://github.com/docker/docs.git
$ cd docs
$ npm i
$ hugo
$ wc -l hugo_stats.json
       0 hugo_stats.json
```

With `writeStats`:

```console
$ rm hugo_stats.json
$ hugo
$ wc -l hugo_stats.json
    5757 hugo_stats.json
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended darwin/arm64 BuildDate=2024-01-05T12:21:15Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by dvdksn** [comment]
very possible. It's here: https://github.com/docker/docs/blob/main/hugo.yaml#L39-L41
swapping this with `writeStats` fixes the issue  for me

**Comment by bep** [comment]
https://github.com/docker/docs/blob/7064a49f0609c46e7385708e8e20160ab81b7613/hugo.yaml#L41

It should be `enable`.

See https://gohugo.io/getting-started/configuration/#configure-build

A related tip is to look at the effective config using `hugo config --format yaml`.

**Comment by dvdksn** [comment]
Thank you !
