### ISSUE TITLE
Method on Page to force content rendering

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11897]
Something like this within the `head` element of a template will not work because `.Content` has not been evaluated:

```
{{ if .Page.Store.Get "hasMermaid" }}
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true });
  </script>
{{ end }}
```

So we do something like this instead:

```
{{ $noop := .Content }}
{{ if .Page.Store.Get "hasMermaid" }}
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true });
  </script>
{{ end }}
```

Instead of `Content` you can also invoke `FuzzyWordCount`, `Len`, `Plain`, `PlainWords`, `ReadingTime`, `Summary, Truncated`, or `WordCount`.

Although `{{ $noop := .OneOfTheAbove }}` makes sense to me, it is not intuitive to new or casual users.

I don't have any great suggestions at the moment, so maybe what we have is fine.

**Comment by bep** [comment]
I'm not sure. When passing state around with scratch you're already in advanced territory and needs to understand how things fits together.

```handlebars
{{/* Render content. */}}
{{ $content := .Content }}
{{/* Check if mermaid was used during the content rendering above. */}}
{{ if .Page.Store.Get "hasMermaid" }}
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true });
  </script>
{{ end }}
```

**Comment by jmooring** [comment]
Yeah, this just need to be documented. See https://github.com/gohugoio/hugoDocs/issues/2402.
