### ISSUE TITLE
js.Build unable to resolve file in data directory

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11898]
The intended behavior may have changed at some point, but our documentation states:

> Any imports in a file outside /assets or that does not resolve to a component inside /assets will be resolved by [ESBuild](https://esbuild.github.io/) with the project directory as the resolve directory (used as the starting point when looking for node_modules etc.)

```text
assets/
├── js/
│   └── main.js
└── jsconfig.json
data/
└── data.json
```

assets/js/main.js

```js
import data from "../../data/data.json";
```

There no directory mounts in site config (default mounts).

This stopped working in v0.78.1.

It may just be a documentation issue.

**Comment by bep** [comment]
So, the documentation is correct, I guess, but you need to look in ESBuild's documentation to see where that library looks for stuff. And my guess that's limited to what `package.json` says. If it worked before, it may be an upstream issue, but I would recommend to stick to either `node_modules` or `assets`.

**Comment by jmooring** [comment]
Yeah, I ran across this while verifying that https://github.com/gohugoio/hugo/issues/7544 will be resolved by https://github.com/gohugoio/hugo/pull/11894, but I was unable to reproduce the setup due to this (11898) issue. 

I'm going to close this, and will add a comment to 7544 to indicate the correct approach. The OP in 7544 wanted to access data.json from both JS (esBuild) and `site.Data.data.foo`, which should be handled with a mount.

```
[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'data'
target = 'assets/data'
```

Then in main.js

```
import data from "data/data.json";
console.log(data.foo);
```
