### ISSUE TITLE
Add a build option to duplicate non-page (e.g. images) resources across languages

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11904]
See #11453.

That is mostly a good thing.

But it doesn't work if:

* The multilingual site doesn't have image render hooks.
* The multilingual site have Markup formats (e.g. HTML, Asciidoc) that does not support render hooks.

So,  I suggest that we extend the front matter build options to look something like this:

```toml
[_build]
  list = 'always'
  publishResources = true
  duplicateResourceFiles = true
  render = 'always'
```

When `duplicateResourceFiles = true` we copy non-page resources (e.g. foo.png) for the languages without a dedicated version.

**Comment by jmooring** [comment]
In support of #11453, for multilingual sites with page resources shared between languages, sites will need both link and image render hooks that capture the page resource and use its `.RelPermalink`. 

structure

```
content/
├── my-bundle/
│   ├── index.de.md
│   ├── index.en.md
│   ├── kitten.en.jpg
│   └── notes.en.pdf
├── _index.de.md
└── _index.en.md
```
published

```public/
├── de/
│   ├── my-bundle/
│   │   └── index.html
│   └── index.html
├── en/
│   ├── my-bundle/
│   │   ├── index.html
│   │   ├── kitten.jpg  <-- de site will need image render hook to get this URL
│   │   └── notes.pdf   <-- de site will need link render hook to get this URL
│   └── index.html
├── favicon.ico
└── index.html
```

**Comment by bep** [comment]
@jmooring yea, I have slept on this, and the hook approach doesn't really work. See my revised proposal above.

**Comment by bep** [comment]
I have revised the proposal a little:

* Put the setting in front matter
* Make the default behave the way it does today, which means we can remove #11453, the "noisiest" of the breaking changes, I suspect.

**Comment by jmooring** [comment]
My thoughts...

Not duplicating page resources is a **huge win** for multilingual, single host sites. For something this valuable, it would be great if there were a simple on/off switch somewhere.

The challenges with enabling it by default are:

1. The site must use link and image render hooks to capture the markdown destination as a resource.
2. Markdown is the only content format that supports render hooks.

Item 1 doesn't concern me so much; I have advocated for these before in #10585. Proper resolution of markdown link and image destinations has been a challenge for site, theme, and content authors for a very long time. We can handle this initially with documented examples, and perhaps create embedded templates at some point.

With respect to Item 2:

- 99% of sites use markdown only.
- The other 1% may be entirely of one format, or a mix of formats. For example, I've seen sites where one section is markdown, while another is reStructuredText. I've also seen a mix of formats in the same section.

Enabling render hooks for other content formats is a non-starter, so... **can we limit resource de-duplication to markdown pages?**  There's an edge case that looks like this, but probably uncommon:

```text
content/
└── posts/
    └── post-1/
        ├── a.jpg
        ├── index.de.adoc
        ├── index.en.md
        ├── index.es.org
        ├── index.fr.pdc
        ├── index.it.html
        └── index.pt.rst
```

If we can limit resource de-duplication to markdown pages...

A\) Disable the feature by default with an on switch in site config under `markup.goldmark` (the feature is specific to markdown, and render hooks are limited to Goldmark).

B\) Document its usage.

- Are you using link and/or image render hooks? If no, use these examples, if yes, proceed to next step
- Build site and run link checker (e.g., [muffet](https://github.com/raviqqe/muffet#readme)) to verify internal links
- If you have related errors, compare your render hooks to the examples...

And we have to do B regardless of how this feature is enabled.

**Comment by bep** [comment]
>can we limit resource de-duplication to markdown pages?

I hadn't thought about that, but that actually makes sense and should be a decent compromise.

```bash
content/
└── posts/
    └── post-1/
        ├── a.jpg
        ├── index.de.adoc
        ├── index.en.md
        ├── index.es.org
        ├── index.fr.pdc
        ├── index.it.html
        └── index.pt.rst
```

That looks ... made up. But if we say:

```toml
[markup]
  [markup.goldmark]
        duplicateResourceFiles = false
```

It is the owner of the resource that dictates the behaviour; in the example above (assuming the default content language is `en`), the resource owner is `index.en.md`. The site owner would need to switch to `duplicateResourceFiles = true` in Goldmark to make it work for the other formats.

Does this sound like a plan?

**Comment by jmooring** [comment]
> we probably need some default render hooks 

See https://github.com/gohugoio/hugo/issues/11904#issuecomment-1900837816 for candidates and test cases. I am very comfortable with these for any new sites, and mostly comfortable for existing sites, but difficult to know for certain (there's some wacky stuff out there).

Multilingual, single host sites with existing render hooks will have to run a link checker before going live to make sure their hooks work as required. See my previous comment.

**Comment by bep** [comment]
We could probably safeguard this by doing:

1. Only use the default render hooks when len(languages) > 1 and
2.  add a way to disable

```
[markup]
  [markup.goldmark]
        duplicateResourceFiles = false
        disableDefaultRenderHooks = false
```

**Comment by jmooring** [comment]
Withorks for me.

At some point, though, default render hooks for every site would be good. But that's for another day...

If you're mostly comfortable with the candidate hooks above, let me know and I can submit a PR with tests.

**Comment by jmooring** [comment]
What about something like this instead:

```text
[markup.goldmark.renderhooks.image]
enable = true
multilingualOnly= true

[markup.goldmark.renderhooks.link]
enable = true
multilingualOnly= true
```

This gives us (obviously) granular control, and sets up for future capability. For example:

```
[markup.goldmark.renderhooks.image]
enable = true
multilingualOnly= true
errorLevel = 'warning' # ignore (default), warning, or error (fails the build)

[markup.goldmark.renderhooks.link]
enable = true
multilingualOnly= true
errorLevel = 'warning' # ignore (default), warning, or error (fails the build)

```

**Comment by bep** [comment]
Yea, that makes sense.
