### ISSUE TITLE
.Paginate() : regression (or breaking change?) between 1.110 (and before) and 1.111+ (until latest)

### ISSUE THREAD

**Issue by zwindler** [gohugoio/hugo#11916]
### What version of Hugo are you using (`hugo version`)?

Works as expected
<pre>
hugo version
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
</pre>

Doesn't work as expected
<pre>
hugo version
hugo v0.111.0-3fa8bb8318114cd69315eadd35bda169e6a8ca4b+extended linux/amd64 BuildDate=2023-03-01T20:57:44Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

### Description of issue

I'm trying to create a custom Paginator using .Paginate function. The idea is to "build" future posts (using `--buildFuture` argument) but not display them in index.html. This way, I can share the link to the people I want (the page is builded and accessible) but not displayed for those who don't know the link

Here is the template I've adapted (from https://github.com/CaiJimmy/hugo-theme-stack) :

```
    {{ $pages := where .Site.RegularPages "Type" "in" .Site.Params.mainSections }}
    {{ $notHidden := where .Site.RegularPages "Params.hidden" "!=" true }}
    {{ $notFuture := where .Site.RegularPages ".Date" "le" now }}
    {{ $filtered := ($pages | intersect $notHidden | intersect $notFuture) }}
    {{ $pag := .Paginate ($filtered) }}

    <section class="article-list">
        {{ range $index, $element := $pag.Pages }}
            {{ partial "article-list/default" . }}
        {{ end }}
    </section>
```

When building the site with any version >= 1.111, the Paginator doesn't seem to care what I feed it. `.Paginate($filtered)` always create a pagination of the full list of the pages, independently of what $filtered is (even if it's 1 page, for example, I'll get all).

Reverting to 1.110 or less (1.92 is fine too), the code works, the "future" page is accessible via direct link, but is not displayed in the index.

I've read the https://github.com/gohugoio/hugo/releases/tag/v0.111.0 release and I haven't seen anything **directly** related to Paginator or Paginate function, but I see modifications regarding the Page (fragments)

Thanks for your time, I'm available for further information or testing

**Comment by bep** [comment]
What happens here isn't obvious to me. That said, for your use case I would just create a "hidden" content page with a view, e.g.:

```
---
view: hidden
_build:
  list: never
  render: always
---
```

The above will make the page accessible, but it will never be listed anywhere.

**Comment by zwindler** [comment]
I know my usecase is uncommon so I tried to reproduce with a "blank" theme

https://github.com/zwindler/pagination-issue

But I was unable to reproduce the issue so I guess there is something wrong with the "stack" theme or my code.

Your "hidden" won't help me, since I would need to manually "un-hide" when date has passed. The idea was that a periodic rebuild would reveal posts after now > the article date, without action on my part.

But since I can't reproduce, I'll close the issue.

Thanks for your time

**Comment by bep** [comment]
>Your suggestion to use "hidden" won't help, since I would need to manually "un-hide" when date has passed. 

I think you could use your old approach with my setup, but I may be mistaken.

I suspect your problem is that your theme calls `.Paginate` or `.Paginator` first. This is all static, so the first one will win.

**Comment by zwindler** [comment]
Your are probably right for the last remark

I'll take a look at the hidden again. Thanks :)
