### ISSUE TITLE
Notes/TODOs Hugo 0.123.0

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11938]
* Front matter vs params
* #11999 html files without front matter in content.
* #11894

--------

**Comment by jmooring** [comment]
We also have taxonomic weights:

```text
title = 'Post 1'
tags = ['tag-a']
tags_weight = 30
```

**Comment by bep** [comment]
* I'm skipping the taxonomy "problems" for now, we're not breaking anything.
* Re. related, I think that's a documentation "challenge" -- we're certainly not breaking anything.
