### ISSUE TITLE
Create default link and image render hooks

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11933]
With the implementation of https://github.com/gohugoio/hugo/issues/11453 and https://github.com/gohugoio/hugo/issues/11904 we no longer duplicate page resources per language[^1]. This is applicable to multilingual, single-host sites. 

When resources are not duplicated per language (the default), link and image render hooks are required to properly resolve markdown destinations (links and image).

[^1]: This can be disabled by setting `markup.goldmark.duplicateResourceFiles = true` in site configuration.

Per [this discussion](https://github.com/gohugoio/hugo/issues/11904#issuecomment-1902270945), the site config would be:

```text
[markup.goldmark.renderhooks.image]
enable = true
multilingualOnly = true

[markup.goldmark.renderhooks.link]
enable = true
multilingualOnly = true
```

Candidate render hooks:

<details>
<summary>layouts/_default/_markup/render-image.html</summary>

```text
{{- $u := urls.Parse .Destination -}}
{{- $src := $u.String -}}
{{- if not $u.IsAbs -}}
  {{- with or (.Page.Resources.Get $u.Path) (resources.Get $u.Path) -}}
    {{- $src = .RelPermalink -}}
  {{- end -}}
{{- end -}}
{{- $attributes := dict "alt" .Text "src" $src "title" .Title -}}
<img
  {{- range $k, $v := $attributes -}}
    {{- if $v -}}
      {{- printf " %s=%q" $k $v | safeHTMLAttr -}}
    {{- end -}}
  {{- end -}}
>
{{- /**/ -}}
```
</details>

<details>
<summary>layouts/_default/_markup/render-link.html</summary>

```text
{{- $u := urls.Parse .Destination -}}
{{- $href := $u.String -}}
{{- if not $u.IsAbs -}}
  {{- with or
    ($.Page.GetPage $u.Path)
    ($.Page.GetPage (strings.TrimRight "/" $u.Path))
    ($.Page.Resources.Get $u.Path)
    (resources.Get $u.Path)
  -}}
    {{- $href = .RelPermalink -}}
    {{- with $u.RawQuery -}}
      {{- $href = printf "%s?%s" $href . -}}
    {{- end -}}
    {{- with $u.Fragment -}}
      {{- $href = printf "%s#%s" $href . -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- $attributes := dict "href" $href "title" .Title -}}
<a
  {{- range $k, $v := $attributes -}}
    {{- if $v -}}
      {{- printf " %s=%q" $k $v | safeHTMLAttr -}}
    {{- end -}}
  {{- end -}}
>{{ .Text | safeHTML }}</a>
{{- /**/ -}}
```
</details>

Test site:

```text
git clone --single-branch -b hugo-github-issue-11933 https://github.com/jmooring/hugo-testing hugo-github-issue-11933
cd hugo-github-issue-11933
hugo server
```

**Comment by bep** [comment]
Just to be clear, when I do

```toml
[markup.goldmark.renderhooks.link]
enable = false
```

That toggle is just for the "default templates" not the "user provided" ... or both?

**Comment by jmooring** [comment]
> That toggle is just for...

Yeah, I get it. There's a couple of cases I didn't consider. Let me think about this for a bit.

**Comment by jmooring** [comment]
Here's my thought process on this...

1\) With a multilingual single-host site, do you **always need** link and image render hooks? Yes. So let's hardcode that bit. The default render hook will always be enabled for multilingual single-host sites, and always overridden by a user-provided hook if present.

2\) Is there ever a time, with any type of site, that you would want the default render hooks to override user-provided hooks? No.

3\) Do we need or want a flag to disable both default and user-provided hooks? No. We don't have a flag like that for heading or code block hooks.

So, what about?

```text
[markup.goldmark.renderhooks.image]
enableDefault = false   <-- hardcoded to true for multilingual single-host

[markup.goldmark.renderhooks.link]
enableDefault = false   <-- hardcoded to true for multilingual single-host
```

We wouldn't need the `multilingualOnly` because it would be hardcoded (see item 1).

**Comment by bep** [comment]
Since detecting a `false` that's explicitly set is harder than the other way around, I suggest we do:

```toml
[markup.goldmark.renderhooks.image]
disableDefault = true   <-- hardcoded to false per criteria above.
```

**Comment by jmooring** [comment]
Sounds good to me.
