### ISSUE TITLE
Page.Resources.Get is broken in 0.123.0-DEV

### ISSUE THREAD

**Issue by TiGR** [gohugoio/hugo#11944]
The problem is: hugo now somehow converts resources names - it brings all to lowercase and replaces spaces with dashes, and .Resources.Get no longer work.

For example, we have a page resource named `Test 1.jpg`. Formerly `.Resources.Get "Test 1.jpg"` worked, but not with development version (we've tried it since we really need the optimizations that are coming next version). Also, dumping `.Resources` shows that internally hugo represents that resource name as `test-1.jpg`.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0-DEV+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

No, it works fine in 0.122, but it is broken in dev version (commit ec22bb3).

**Comment by bep** [comment]
>Also, dumping .Resources shows that internally hugo represents that resource name as test-1.jpg.

The problem in your case is, I guess, the spaces in the file name, something I would strongly advice against (In Hugo, but I guess also in general).

I will check this case, though, I see we check both the normalised and the original name, so the above should work.
