### ISSUE TITLE
Nil pointer error instead of warning when checking .File.Something without a backing file

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11956]
Expected warning, got error.

```
content/
└── posts/           <-- no _index.md file in this dir
    └── post-1.md
```

layouts/_default/list.html

```
{{ .File.Lang }} 
```

With v0.122.0: 

> WARN  .File.Lang on zero object. Wrap it in if or with: {{ with .File }}{{ .Lang }}{{ end }}

With hugo v0.123.0-DEV-b332f2:

> Error: error building site: render: failed to render pages: render of "section" failed: "/home/jmooring/code/hugo-testing/layouts/_default/list.html:7:10": execute of template failed: template: _default/list.html:7:10: executing "main" at <.File.Lang>: error calling Lang: runtime error: invalid memory address or nil pointer dereference

**Comment by bep** [comment]
OK, so this may not be on my list of "things to fix", but I 

1. Introduced the WARNING many moons ago as a "deprecation message" to allow people some time to fix their templates.
2. But the above needed lots of autogenerated boilerplate with a way too elaborate interface setup (especially for things that's mostly of internal interest), which I had no intention of maintaining forever. So I made the `File` on page into a simple struct (pointer), which can be nil. So, the error message is not as great, but it means the same.

**Comment by cmahnke** [comment]
Well, from my point of view the new behaviour is actually an improvement, since its's stating the location of the problem. But I have to admit, that the message itself is certainly more cryptic to new users...

**Comment by jmooring** [comment]
> lots of autogenerated boilerplate with a way too elaborate interface setup

> new behaviour is actually an improvement

Closing.
