### ISSUE TITLE
Consider _build vs build

### ISSUE THREAD

**Issue by cmahnke** [gohugoio/hugo#11970]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0-DEV-4174a7866b75c6ae10827cc77dbae0676af8e5eb+extended darwin/arm64 BuildDate=2024-02-01T18:42:55Z

</pre>

### Does this issue reproduce with the latest release?

Yes

## Description

The site is building with Hugo 0.122.0, using the latest dev version it fails with this rather cryptic message:

```
ERROR Failed to create content converter: no content renderer found for markup ""
```

@bep: Cann you please add a hint, like template file and line to be able to narrow it down?

**Comment by jmooring** [comment]
Are you passing "markup" as a key in the options map for .Page.RenderString?  e.g., 

```text
{{ $opts := dict "markup" "pandoc" }}
{{ $s | .RenderString $opts }} → H<sub>2</sub>O
```

**Comment by cmahnke** [comment]
No, neither of both. And just passing a empty string as `markup` in the font matter doesn't seem to trigger this.

But using `disableKinds` let me narrow it down to some template that is only called for `term`'s - I'll check that.

**Comment by bep** [comment]
>Cann you please add a hint, like template file and line to be able to narrow it down?

I added some page info ... But I fail to understand why the above happens.

**Comment by cmahnke** [comment]
@bep: Thanks, that was very helpful.
@jmooring: You were close I've got a field `build` (since it's a site about architecture and uses the field to indicate when a building was topped out). Commenting this out fixes this message. But I can change that...

Thanks both!

**Comment by bep** [comment]
>build (since it's a site about architecture and uses the field to indicate when a building was topped out). Commenting this out fixes this message. But I can change that...

Hmm... I'm not sure I see the connection, but yea, I boldly renamed the `_build` to `build` not thinking that it would have any side-effects...

**Comment by cmahnke** [comment]
Well, I'm just dumping metadata on a object described by a `tag` page in the frontmatter. 
Just to avoid similar issues: This site also uses a `type` front matter field for tag pages to distinguish between buildings and architects.

BTW: I really like the error messages with a reference to the causing content file, this also has the benefit that they aren't eaten up.

**Comment by bep** [comment]
@cmahnke OK. I will see if I can make that change less breaking. Note that we have created a separation between "Hugo page config" and "user defined params", so the recommended setup in 0.123.0 would be:

```
---
title: My page
params:
   myuserparam: foo
   build: some build setup that's not related to Hugo's build/_build
---
```

**Comment by cmahnke** [comment]
@bep Yes, I will do that. I guess the usual deprecation rules will apply for custom front matter fields as well.

Thanks!
