### ISSUE TITLE
Check data issue

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11979]
https://discourse.gohugo.io/t/hugo-can-t-find-site-data-with-a-current-development-build/48093

**Comment by bowman2001** [comment]
I’m using Hugo on Ubuntu 22.04 to build [the documentation repo](https://github.com/bowman2001/perplexdoc) with [the theme](https://github.com/bowman2001/perplex). The theme contains some modules (_vendor) which rely on data files for configuration.

**Comment by bep** [comment]
@bowman2001 #11980 fixes the data issue. There is still one more failure for your site; I have looked at it, and there's a scratch construct there where the value is Get before it's set for a given page. I don't know the source, so it's hard for me what happens here and why this worked before, but the construct looks fragile.
