### ISSUE TITLE
Code blocks without language look bad

### ISSUE THREAD

**Issue by nikhilweee** [gohugoio/hugo#11984]
### Issue Description

This is a follow-up issue of #6589 and #3699. Code blocks without a language render differently. The reason behind this issue has remained the same. When a language is omitted from code blocks, `<div class="highlight">` is absent from the rendered HTML.

The _fix_ suggested in #6589 was to use `guessSyntax=true`. This is more of a workaround than a fix, and it isn't fool proof. There are cases where language is guessed incorrectly, specially in cases where the code block just contains output from a terminal.

A true solution would be to include `<div class="highlight">` regardless of whether a language is set. I assume this could be achieved if the default language is set to `text`.

### Hugo Version
<pre>
$ hugo version
hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended 
darwin/arm64 BuildDate=2024-01-26T15:54:24Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by jmooring** [comment]
The easiest way to handle this is with a code block render hook. This should you get you close:
<https://discourse.gohugo.io/t/change-language-in-highlightcodeblock/47724/4?u=jmooring>

**Comment by nikhilweee** [comment]
Thanks for the suggestion @jmooring. While I can definitely use it to solve my particular use case and add `<div class="highlight">` to all code blocks regardless of language, my suggestion is to make this the default in Hugo.

**Comment by jmooring** [comment]
I'm going to push back on this, and here's why.

markdown|CommonMark HTML|Hugo HTML
:--|:--|:--
`    indented`|`<pre><code>indented</code></pre>`| `<pre><code>indented</code></pre>`
\`\`\`<br>`fenced`<br>\`\`\`|`<pre><code>indented</code></pre>`| `<pre tabindex="0"><code>fenced</code></pre>`

With the exception of the `tabindex` attribute, we are CommonMark compliant. [Try it](https://spec.commonmark.org/dingus/?text=%60%60%60%0Afenced%0A%60%60%60%0A%0A).

And this is _exactly_ why we have a code block render hook... to alter the default rendering behavior.
