### ISSUE TITLE
Put opengraph information where aliases are defined

### ISSUE THREAD

**Issue by coravacav** [gohugoio/hugo#11983]
I think it'd be a nice feature to have anything defined in your frontmatter's `aliases` list have their URLs generated with the redirect and with the open graph information from the file it's redirecting to.

In my use case, I want a short URL to type inside a chatroom and still have the open graph embed pop up.

**Comment by jmooring** [comment]
You should handle that with a custom template:
<https://gohugo.io/content-management/urls/#customize>

The embedded template is here:
<https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/alias.html>
