### ISSUE TITLE
[0.123.0 dev] Key "kind" not allowed in cascade config

### ISSUE THREAD

**Issue by flexxgaad** [gohugoio/hugo#11985]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0-DEV-53f204310ec8362d7084c123e8e16f5bb73dd257+extended windows/amd64 BuildDate=2024-02-03T17:10:38Z
</pre>

### Does this issue reproduce with the latest release?
No

I have cascaded the `kind` in several locations which now throws an error. E.g.

```
Error: error building site: process: readAndProcessContent: "C:\hugo-site\content\posts\news\_index.md:1:1": key "kind" not allowed in cascade config
```

`./posts/news/_index.md`
```
---
title: News
url: news
cascade:
 kind: news
---
```

**Comment by bep** [comment]
There are 2 related changes in the upcoming release:

1. We have added the `kind` (Hugo's keyword, the page kind) to front matter.
2. We have split user defined params into its own section.

So, in your case you can do 1 of 2 things:

1. Rename `kind` to something else.
2. Add it to the `params` section :

```
---
title: News
url: news
cascade:
 params:
    kind: news
---
```

Note that the last option will not work with older Hugo versions.

**Comment by flexxgaad** [comment]
Noted. Went with option 1
