### ISSUE TITLE
[0.123.0 dev] Can't evaluate field Permalink in type string

### ISSUE THREAD

**Issue by flexxgaad** [gohugoio/hugo#11986]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0-DEV-53f204310ec8362d7084c123e8e16f5bb73dd257+extended windows/amd64 BuildDate=2024-02-03T17:10:38Z

</pre>

### Does this issue reproduce with the latest release?
No

Page bundles involved here

```
 execute of template failed: template: partials/head.html:93:46: executing "partials/head.html" at <$img.Permalink>: can't evaluate field Permalink in type string
```

`partials/head.html`

```
    {{- $img := "" }}
    {{- if and (eq .Params.layout "multipage") (eq .Kind "page") }}
    {{- with .Parent.Resources.GetMatch "cover.*" }}
    {{- $img = . }}
    {{- end }}
    {{- else }}
    {{- with or (.Resources.GetMatch "cover.*") (resources.Get "image/cover.jpg") }}
    {{- $img = . }}
    {{- end }}
    {{ end -}}

Line 93: <meta property="og:image" content="{{ $img.Permalink }}">
```
```

**Comment by bep** [comment]
So, it's not finding any image. 

Why that is not possible for me to say without seeing the source. Could you somehow provide me with a link to the source?

**Comment by flexxgaad** [comment]
The issue with the latest dev version occurs when a draft multipage post has no cover image (see [option 2](https://discourse.gohugo.io/t/splitting-an-article-into-multiple-pages-with-a-menu/41592/2)). Should that happen?

**Comment by bep** [comment]
The site in option 2 builds fine for me. Do I need to do something special to make it fail?

**Comment by flexxgaad** [comment]
Try [this repo](https://github.com/flexxgaad/test). Go to `content/articles/testpost` then remove the image and try to build (when draft is set to true). The build fails in my case. Then adding back the image makes the build to succeed.

**Comment by jmooring** [comment]
@flexxgaad

With v0.122.0 and earlier, if you set `draft = 'true'` in an `_index.md` file, neither the section page or any of its descendants were published.

With v0.123.0 and later,  if you set `draft = 'true'` in an `_index.md` file, the section page will not be published, but descendants **will** be published.

In your example, the descendants of the "draft" section page ("Year 2023" and "Year 2024") are now rendered, and they can't find the image since it doesn't exist, which means in your partial `$img` is an empty string... hence the error.

You need to do a couple of things...

First, in your partial, code defensively.

```text
{{ with $img }}
<meta property="og:image" content="{{ .Permalink }}">
{{ end }}
```

Second, to prevent publication of a section page **and** its descendants, cascade some build options.

**Comment by flexxgaad** [comment]
> code defensively.

My publishing schedule always involves having the featured image. So, I avoided doing this to avoid 'cluttering` my open graph tags.

> Second, to prevent publication of a section page **and** its descendants, cascade some build options.

I cascaded `draft: true`. Hoping that is enough.

**Comment by jmooring** [comment]
```yaml
title: Posts
cascade:
  build:
    render: never
    list: never
```

This will not work:

```
title: Posts
cascade:
  draft: true
```

Which is surprising.

**Comment by flexxgaad** [comment]
This breaking change will make publishing a bit harder if we have to keep adding the build options rather than a simpler draft option (archetypes notwithstanding).

**Comment by jmooring** [comment]
> will make publishing a bit harder

Understood, and this is an important breaking change that may publish previously unpublished content.

However, the change was architecturally necessary (or at least advantageous), and new the behavior is less surprising to new users. The "less surprising" assessment is based on the number of related forum topics and GitHub issues, so many that we added items to the FAQ list. See items 2 and 3 on https://gohugo.io/troubleshooting/faq/.

**Comment by flexxgaad** [comment]
The archetypes option with kind flag will work for now. Gotta get used to the new way. Thanks for the work you all do here.
