### ISSUE TITLE
Unable to cascade value of draft field

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11990]
From a section page, this works in v0.122.0 but not in v0.123.0.

```text
[cascade]
draft = true
```

To accomplish the same thing in v0.123.0 you must do this:

```text
[cascade.build]
render = 'never'
list = 'never'
```

**Comment by bep** [comment]
I wrote this test, assuming it to fail, but it doesn't:

```go

func TestCascadeDraft(t *testing.T) {
	files := `
-- hugo.toml --
baseURL = "https://example.org"
-- content/mysection/_index.md --
+++
draft = false
[cascade]
draft = true
+++
-- content/mysection/p1.md --
---
title: "P1"
---
-- layouts/index.html --
Len RegularPagesRecursive: {{ len .RegularPagesRecursive }}|
-- layouts/_default/single.html --
{{ .Title }}|
`

	b := Test(t, files)

	b.AssertFileExists("public/mysection/p1/index.html", false)
	b.AssertFileContent("public/index.html", "Len RegularPagesRecursive: 0|")
}

```

What do I miss?

**Comment by jmooring** [comment]
Sorry about the noise.

If p1.md has `draft: false`, it is not overridden by the cascade, _which is exactly how it should be working_.

So with v0.123.0 the (mostly) fool-proof way to handle this is with:

```text
title: Posts
cascade:
  build:
    render: never
    list: never
```

With v0.122.0 and earlier, setting `draft:true` in the section would ignore the `draft` setting in each of the descendent pages.
