### ISSUE TITLE
Hugo 0.123 can't find html documents in resources

### ISSUE THREAD

**Issue by TiGR** [gohugoio/hugo#11999]
If you have an html file (for example, `doc.html`) and this file is located within a page directory, it is listed in page resources in hugo 0.122 and before. It could be listed in `.Resources`, read from there and rendered.

Example site [here](https://github.com/TiGR/hugo-testing/tree/html-resources-issue). Hugo 0.122 renders "Hello world" in both `/public/test/index.html` and `/public/test2/index.html`. But in Hugo 0.123 `/public/test/index.html` is empty, `.Resources` there is empty too.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0-DEV+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

No, it is broken only in 0.123

**Comment by bep** [comment]
The Hugo `0.122.0` way of handling HTML files inside `/content` was a little ... confusing. I think it went like this:

* HTML files with front matter is always a content file.
* HTML file inside a bundle is a resource.
* HTML file outside of a bundle is just a static files that gets copied to /public.

With a simplification of the above, to prepare for having data from multiple sources (not just files), we have simplified the above, so now it is:

* HTML files with front matter is always a content file.
* HTML files without front matter are static files that gets copied to /public.

I'm not prepared to spend any substantial amount of time fixing/changing this, because that would just complicate things in the future.

**Comment by jmooring** [comment]
To clarify, with v0.123.0...

- HTML files with front matter is always a content file **(and that means it's available as a page resource)**
- HTML files without front matter are static files that gets copied to /public.

So a shortcode can `Resources.Get` the foo.html file in:

```text
content/
└── posts/
    └── post-1/
        ├── a.jpg
        ├── foo.html  <--  has front matter so it is a page resource
        └── index.md
```

**Comment by jmooring** [comment]
@cmahnke I'm correcting my previous response. Handling of files with the "html" extension depends on the file content.

```text
content/
└── posts/
    └── post-1/
        ├── foo.jpg
        ├── index.md
        ├── with-front-matter.html
        ├── with-front-matter.md
        ├── without-front-matter-begins-with-<.html
        ├── without-front-matter-does-not-begin-with-<.html
        └── without-front-matter.md
```

### v0.122.0

File|Page resource|Copied to pubic
:--|:--|:--
foo.jpg|:heavy_check_mark:|:heavy_check_mark:
with-front-matter.html|:heavy_check_mark:|:x:
with-front-matter.md|:heavy_check_mark:|:x:
without-front-matter-begins-with-<.html|:heavy_check_mark:|:heavy_check_mark:
without-front-matter-does-not-begin-with-<.html|:heavy_check_mark:|:x:
without-front-matter.md|:heavy_check_mark:|:x:

### v0.123.0

File|Page resource|Copied to pubic
:--|:--|:--
foo.jpg|:heavy_check_mark:|:heavy_check_mark:
with-front-matter.html|:x:|:x:
with-front-matter.md|:heavy_check_mark:|:x:
without-front-matter-begins-with-<.html|:x:|:heavy_check_mark:
without-front-matter-does-not-begin-with-<.html|:heavy_check_mark:|:x:
without-front-matter.md|:heavy_check_mark:|:x:

**Comment by TiGR** [comment]
So, in v0.123.0 there is no way to load html file as a resource if it contains html?

**Comment by jmooring** [comment]
From my testing it looks like you can load a file with the "html" extension if both of the following are true:

1. It does not have front matter
2. The content does not begin with a `<` character.

**Comment by TiGR** [comment]
So, if it is starts with a newline it would work? Looks extremely odd

**Comment by jmooring** [comment]
No, looks like leading whitespace is ignored. Please test it yourself.

```text
git clone --single-branch -b hugo-github-issue-11999 https://github.com/jmooring/hugo-testing hugo-github-issue-11999
cd hugo-github-issue-11999
rm -rf public/ && hugo && tree public
```

**Comment by TiGR** [comment]
If you add empty frontmatter to html file, or not empty, but without the `title`, the file would appear in resources. If you add the title, it would disappear from the resources, and it won't be copied to public.

Again, extremely odd.

**Comment by cmahnke** [comment]
Even though I'm not a fan of this change, the other 0.123 changes are worth the affort: Just using `readFile` works for me.

**Comment by bep** [comment]
If I don't respond to an issue it doesn't mean I don't care, it means that either 1. busy with work/life or 2. busy with Hugo issues that in my eyes are more important. Handling of HTML files inside `/content` has been filled with somewhat odd legacy rules; I tried to fumble around this and I manage to get all tests passing, so it cannot be all bad. 

I have quickly scanned the code around this, and:

For any HTML file inside `/content`, if the first non-whitespace char is `<` and that is not starting a HTML comment (a common thing is to have the front matter commented out), we just copy it directly to `/public` as it would live in `/static`.

As I said, we probably had a more fine grained logic in 0.122.0, but that train has left the station.


**Are you saying that HTML with front matter (commented out or not) does not work as expected?**

**Comment by TiGR** [comment]
Well, I no longer understand what is "expected behavior". I'd expect that regular html files would appear in resources list. But behavior in 0.123 is this:
<table>
<tr><th>Listed in Resources</th><th>Copied to public</th><th>Content</th></tr>
<tr><td>✔️</td><td>❌</td><td><pre lang="html">This is a regular text in html file</pre></td></tr>
<tr><td>❌</td><td>✔️</td><td><pre lang="html">&lt;p&gt;This is html file&lt;/p&gt;</pre></td></tr>
<tr><td>✔️</td><td>❌</td><td><pre lang="html">---
---
&lt;p&gt;This is html file&lt;/p&gt;</pre></td></tr>
<tr><td>✔️</td><td>❌</td><td><pre lang="html">---
title: Title
---
&lt;p&gt;This is html file&lt;/p&gt;</pre></td></tr>
</table>

I don't see the logic here. In 0.122 it was like this:

<table>
<tr><th>Listed in Resources</th><th>Copied to public</th><th>Content</th></tr>
<tr><td>✔️</td><td>❌</td><td><pre lang="html">This is a regular text in html file</pre></td></tr>
<tr><td>✔️</td><td>✔️</td><td><pre lang="html">&lt;p&gt;This is html file&lt;/p&gt;</pre></td></tr>
<tr><td>✔️</td><td>❌</td><td><pre lang="html">---
---
&lt;p&gt;This is html file&lt;/p&gt;</pre></td></tr>
<tr><td>✔️</td><td>❌</td><td><pre lang="html">---
title: Title
---
&lt;p&gt;This is html file&lt;/p&gt;</pre></td></tr>
</table>

**Comment by bep** [comment]
Can we continue this discussion in #12008
