### ISSUE TITLE
I am using hugo version 0.122 after following the official website quick start tutorial for hugo server, I am unable to clock pages. It didn't generate successfully.

### ISSUE THREAD

**Issue by tianyinggang** [gohugoio/hugo#12006]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version：0.122.0

</pre>

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
