### ISSUE TITLE
Bundled resource pages (e.g. md file) not refreshed on server rebuilds

### ISSUE THREAD

**Issue by TiGR** [gohugoio/hugo#12000]
Example site [here](https://github.com/TiGR/hugo-testing/tree/md-caching-issue). Run it in `hugo server` mode. Then, open `/test/` page. Now, edit `content/test/doc.md` file. Notice in the terminal that hugo notices change, runs rebuild, but still render the old content.

It seems to be related to markdown files only, as other files do reload fine.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0-DEV+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

No, hugo 0.122 and before it works fine.

**Comment by bep** [comment]
Thanks, I guess I didn't test that. On a note related to the issue of duplication; it strikes me as a little bit odd that you have `index.html` as the main bundle page, but have `md` files bundles, but you probably have a good reason.

**Comment by TiGR** [comment]
Well, as a site with a lot of legacy content we have it in all possible ways: with `index.html` and `doc.html`, with `index.html` and `doc.md`, with `index.md` and `doc.md`, and with `index.md` and `doc.html`.

It actually doesn't matter, as the issue appears with both `index.html` and `index.md`.
