### ISSUE TITLE
Global Markdown link references

### ISSUE THREAD

**Issue by mrusme** [gohugoio/hugo#12018]
I am maintaining a relatively large Hugo site and I found myself repeating links as Markdown link references across multiple pages, e.g.:

**Page 1**
```md
This is [my link][my-link].

[my-link]:/my-link/
```

**Page 2**
```md
This is [my link][my-link] again.

[my-link]:/my-link/
```

It would be very helpful if there was a way to specify globally available references for Markdown, either in some configuration or in a central Markdown file that would get included by every Markdown page/post. This file would basically only need to contain the references and links:

```md
[my-link]:/my-link/
[my-link-2]:/my-link-2/
[my-link-3]:/my-link-3/
[my-link-4]:/my-link-4/
[my-link-5]:/my-link-5/
```

This way, every page could use `[my-link]` without explicitly re-referencing it. Also, the moment the centralized Markdown/configuration would change, every page would get the updated link.

**Comment by jmooring** [comment]
layouts/shortcodes/refs.html

```text
[go]: https://go.dev
[hugo]: https://gohugo.io
```

markdown

```text
{{% refs %}}  <-- position on page is irrelevant, could be in an archetype too

[Hugo] is written in [Go].
```

And as shown above, [shortcut reference links](https://spec.commonmark.org/0.31.2/#shortcut-reference-link) save you some time and make the markdown easier to read.

**Comment by mrusme** [comment]
@jmooring as always on point -- thank you very much! I just tested it using `hugo v0.121.0+extended` and it works flawlessly. This solution is exactly what I needed -> closed.
