### ISSUE TITLE
Terms with backing content file is not handled correctly in 0.123

### ISSUE THREAD

**Issue by TiGR** [gohugoio/hugo#12020]
Example [site](https://github.com/TiGR/hugo-testing/tree/missing-taxonomies-issue). I try to list taxonomy terms, according to the docs (it is not changed for 0.123) I can do it like this:

```html
<ul>
  {{ range .Site.Taxonomies.tags }}
    <li><a href="{{ .Page.Permalink }}">{{ .Page.Title }}</a> {{ .Count }}</li>
  {{ end }}
</ul>
```

With the example site, when I run it in 0.122, I get this result in the console:

```
WARN  Listing tags:
WARN  --------------------
WARN  Tag "tag1" "Tag One"
WARN  Tag "tag2" "Tag Two"
WARN  Tag "tag3" "Tag Three"
WARN  
WARN  Listing tags in alphabetical order:
WARN  -----------------------------------
WARN  Tag "Tag One"
WARN  Tag "Tag Three"
WARN  Tag "Tag Two"
```

But when I run it with 0.123, I get this:

```
WARN  Listing tags:
WARN  --------------------
WARN  Tag "tag1" "Tag One"
WARN  
WARN  Listing tags in alphabetical order:
WARN  -----------------------------------
WARN  Tag "Tag One"
```

**Comment by bep** [comment]
Thanks for this. I will fix this during the weekend.

**Comment by jmooring** [comment]
Additional findings...

1. Ranging over an ordered taxonomy (e.g., `site.Taxonomies.tags.ByCount`) has the same problem
1. Ranging over `.Page.GetTerms` works as expected

**Comment by bep** [comment]
Yea, I have spotted the obvious mistake.
