### ISSUE TITLE
Improve implicit render-to-disk behavior when running Hugo server

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12027]
I encountered this while testing https://github.com/gohugoio/hugo/pull/12025.

While the server was running, I changed the draft mode on a term's content page from `false` to `true`, but continued to see the original page title instead of the automatic section title. Stopping and restarting the server did not fix the problem.

Then I ran into the same/similar problems testing other pages, including something like content/example.md.

After panicking, thinking "How did I miss this?", I remembered the render-to-memory => render-to-disk change. I added the `--renderToMemory" flag and everything is working as expected.

**Comment by bep** [comment]
This is odd, but it may explain some other mysteries of recent times. I will have a look at it.

**Comment by bep** [comment]
Is this still an issue or was this issue maybe some of the related functional issues that got fixed?

**Comment by jmooring** [comment]
Yes, this is still an issue, but the details are a bit muddy at the moment due to another term page problem I'm trying to zero-in on.

**Comment by jmooring** [comment]
> This is probably still an issue

No, it's not.
