### ISSUE TITLE
terms backed by files ignore frontmatter title in 0.123.0

### ISSUE THREAD

**Issue by McShelby** [gohugoio/hugo#12031]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.123.0-DEV-e309f82efe1885aa5b8030be48c36ba4432ddd7b windows/amd64 BuildDate=2024-02-10T19:28:03Z
</pre>

### Does this issue reproduce with the latest release?

Until 0.122.0 it was fine. Since 0.123.0 it breaks.

### Desc

In my [theme docs](https://github.com/McShelby/hugo-theme-relearn/tree/main/exampleSite) I am using a [taxonomy term backed by a file](https://github.com/McShelby/hugo-theme-relearn/blob/main/exampleSite/content/tags/its-hidden/_index.en.md). In the file the title is overridden in the frontmatter. The [taxonomy template](https://github.com/McShelby/hugo-theme-relearn/blob/main/layouts/_default/taxonomy.html) uses a [helper template](https://github.com/McShelby/hugo-theme-relearn/blob/main/layouts/partials/pageHelper/taxonomyPages.html) to collect some meta information (title, count, etc) for each term and afterwards [print the term list](https://mcshelby.github.io/hugo-theme-relearn/tags/index.html).

This worked reliably until Hugo 0.123.0. Now it _usually_ prints the terms original title (`It's hidden`) instead of the frontmatter value (`A Secret`). This faulty behavior is not always observable.

I have tried different things:

- the helper template was called as `partialCached`, switching this (and all other occurences of this template call) to `partial` did nothing to the result
- if I move the code of the helper template to the taxonomy template itself it often works correct
- creating a MWE based on `hugo new ...` did not lead to this behavior, it always worked correct (thou it lacked the multilang configuration and amout of pages of theme docs)
- I tried to call the pages `WordCount` to enforce a page rendering, but this also did not help

**Comment by bep** [comment]
I think I fixed this in caba6ba6e78dfd124a60cee321de441f8b21ae11 ...?

**Comment by McShelby** [comment]
> I think I fixed this in [caba6ba](https://github.com/gohugoio/hugo/commit/caba6ba6e78dfd124a60cee321de441f8b21ae11) ...?

Your mentioned commit was already included in my build, but just to make sure I went directly onto your commit. Sadly it still behaves faulty.

````
hugo v0.123.0-DEV-caba6ba6e78dfd124a60cee321de441f8b21ae11 windows/amd64 BuildDate=2024-02-10T16:48:53Z
````

**Comment by bep** [comment]
Ref. this line:

https://github.com/McShelby/hugo-theme-relearn/blob/4bc5529bc8bdb75bf707df94641a17c44a08aecf/layouts/partials/pageHelper/taxonomyPages.html#L11

Specifically, what value is wrong? .Page.Data.Term or .Page.Title?

**Comment by McShelby** [comment]
I've stripped down the helper template to a simple

````
{{- $pages := slice }}
{{- range .Pages }}
  {{- $pages = $pages| append (dict "Title" .Page.Title "Page" .Page "Count" 1 )}}
{{- end }}
{{- $pages = sort $pages ".Title" }}
{{- return $pages }}
````

Now I see **both** titles in the resulting page (pointing to the same page). I really puzzeld. I've also restarted `hugo server` after changing the template but the result stays the same.

![grafik](https://github.com/gohugoio/hugo/assets/11670870/22d56a73-4067-41fd-8d89-49f68c1b2204)

**Comment by bep** [comment]
OK, thinking about this once more, it mos likely the language aspect of your setup that I somehow have broken. I will look closer.

**Comment by bep** [comment]
OK, I had a look at it. Yes, this is a slightly breaking change, but it had good intentions and fixed way more issues than it introduced.

The thing is:

* In v0.122 we normalized the terms/paths before we stored them in such a way that it was really hard to determine the path given a term (especially true with unicode accents removed etc.)
* v0.122 we do some normalisation (lower case, replace space with hyphen), but that normalisation can be easily applied to make GetPage etc. just work.

In your site you have a tag named `it's hidden` and then a content bundle named `its-hidden`.

You can either rename the content bundle or (new in 0.123) set `path=/tags/it's-hidden` in front matter.

**Comment by McShelby** [comment]
Thanks. Fixing the bundle directory from `its-hidden` to `it's-hidden` fixed the issue. This still results in `its-hidden` in the resulting permalink but i guess, that's the how it should work.
