### ISSUE TITLE
server: Browser does not reload when i18n file is changed

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12039]
Although this occurred sporadically with prior versions, the behavior is consistently repeatable with hugo v0.123.0-DEV-21d9057d.

For example, the browser does not reload when changing `i18n/en.toml` from this:

```toml
foo = 'bar'
```

to this:

```toml
foo = 'baz'
```

**Comment by TiGR** [comment]
Actually, I get this when editing page translations (`index.xx.html` files). Hugo makes rebuild, browser reloads, but the translated content stays the same.

**Comment by bep** [comment]
@TiGR please don't pad "I'm having a slightly related issue" to these issues. If you have found another but, please open up another issue describing it.
