### ISSUE TITLE
.GetTerms returns empty set for pages with _build: render: never in 0.123

### ISSUE THREAD

**Issue by TiGR** [gohugoio/hugo#12044]
Say, you have some pages with this code:

```
_build:
  list: local
  render: never
```

That is, you don't need separate files for these files, but you render these pages elsewhere. However, when you get that page, you get weird results. First up, `.GetTerms "tags"` for example returns empty set.

[Example site](https://github.com/TiGR/hugo-testing/tree/broken-getterms-issue). In hugo 0.122 this site shows the following:

```
WARN  Test Page file tags:
WARN  -- Tag One (Test Page)
```

In hugo 0.123:

```
WARN  Test Page file tags:
```

So, it can't list tags. Also, in some a bit more complex environment (can't yet reproduce in simple site), when I dump subpage from a variable I get not `Page(/path/to/page)`, but `Page(nil)` for pages having `_build: render: never`.

**Comment by jmooring** [comment]
I'm not sure about this; it's a complex question involving many use cases. For discussion...

<p>Build options: when should a page's terms contribute to a taxonomy object?</p><br>
<table>
  <tr>
    <th colspan=2></th>
    <th colspan="3">RENDER</th>
  </tr>
  <tr>
    <th colspan=2></th>
    <th>always</th>
    <th>link</th>
    <th>never</th>
  </tr>
  <tr>
    <th rowspan="3">LIST</th>
    <th>always</th>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>?</td>
    <td align=center>?</td>
  </tr>
  <tr>
    <th>local</th>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>?</td>
    <td align=center>?</td>
  </tr>
  <tr>
    <th>never</th>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>?</td>
    <td align=center>:x:</td>
  </tr>
</table>

The cells that I've filled in are, to me, obvious choices. 

If we were starting from scratch, I'd say do this:

<table>
  <tr>
    <th colspan=2></th>
    <th colspan="3">RENDER</th>
  </tr>
  <tr>
    <th colspan=2></th>
    <th>always</th>
    <th>link</th>
    <th>never</th>
  </tr>
  <tr>
    <th rowspan="3">LIST</th>
    <th>always</th>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>:x:</td>
    <td align=center>:x:</td>
  </tr>
  <tr>
    <th>local</th>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>:x:</td>
    <td align=center>:x:</td>
  </tr>
  <tr>
    <th>never</th>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>:x:</td>
    <td align=center>:x:</td>
  </tr>
</table>

The behavior with v0.123.0 is different than v0.122.0, but I think it might be better.

**Comment by TiGR** [comment]
I think that there should be an option to make it work as I describe it: that is, no separate pages are generated, but you can work with these pages, use tags, etc. In our case, we have lists of updates (which a usually just a sentence, and there is no need to make it into a page, but we list all them on some pages). So, we need an ability to render it, but not in separate pages (as it would create about a one hundred thousand unneeded pages).

**Comment by jmooring** [comment]
Rethinking my "if we we're starting from scratch" scenario, I think it should look like this instead:

<table>
  <tr>
    <th colspan=2></th>
    <th colspan="3">RENDER</th>
  </tr>
  <tr>
    <th colspan=2></th>
    <th>always</th>
    <th>link</th>
    <th>never</th>
  </tr>
  <tr>
    <th rowspan="3">LIST</th>
    <th>always</th>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>:x:</td>
  </tr>
  <tr>
    <th>local</th>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>:x:</td>
  </tr>
  <tr>
    <th>never</th>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>:heavy_check_mark:</td>
    <td align=center>:x:</td>
  </tr>
</table>

**Comment by jmooring** [comment]
@TiGR Given my previous comment, I think we should close this.

**Comment by TiGR** [comment]
Yes, I think it works
