### ISSUE TITLE
server: Browser does not reload after changing non-default language content

### ISSUE THREAD

**Issue by TiGR** [gohugoio/hugo#12043]
If you have some translated page, and you edit the translation, server runs refresh, and the page reloads, but it still displays the old content. Example [site](https://github.com/TiGR/hugo-testing/tree/translation-caching-issue). In that site try running `hugo server` and edit `content/_index.es.md`, notice that the rendered content stays the same. This issue does not happen in 0.122.

**Comment by jmooring** [comment]
Changes to content in the default content language work as expected. The reported problem is limited to the other languages.
