### ISSUE TITLE
Hugo Concat leads to broken result files.

### ISSUE THREAD

**Issue by tobijdc** [gohugoio/hugo#12040]
I encountered two bugs when concatinating js files with Hugo Pipes.

# Reproducer

You can follow allong in the **Reproducer Repository**
https://github.com/tobijdc/hugo-js-concat-reproducer

# Bug 1: Unexpected Semicolon

I encountered this, when trying to create a more simple reproducer:

baseOf.html (excerpt)
```
    {{ $test := resources.Get "js/test.js"  }}
    {{ $test2 := resources.Get "js/test2.js" }}

    {{ $jsBundle := resources.Concat "js/bundle1.js" (slice $test2 $test) }}
    <script src="{{ $jsBundle.RelPermalink }}"></script>
```

test.js
```javascript
console.log(variableFromOtherFile);
```
test2.js
```javascript
// i want to be first
var variableFromOtherFile = "I come from another world.. ehhh file I mean. Some non ASCII caracters for goot measure äöüß 哀公問社於宰 abc!";
```

bundle1.js (commited to /results in reproducer)
```javascript
// i want to be first
var variableFromOtherFile = "I come from another world.. ehhh file I mean. Some non ASCII caracters for goot measure äöüß 哀公問社於宰 abc!";
;
console.log(variableFromOtherFile);
```

## Expected

I would not expect the Semicolon between files, as it is not present in either file, nor in the template.

# Bug 2: Encoding of second file breaks

When concatinating files for my actual project (one big json array of data and my game logic), the content of the second file always ends up with random characters (chinese, strange symbols etc.)

baseOf.html (excerpt)
```
    {{ $game := resources.Get "js/game.js"  }}
    {{ $players := resources.Get "js/players400.js" }}

    {{ $jsBundle2 := resources.Concat "js/bundle2.js" (slice $players $game) }}
    <script src="{{ $jsBundle2.RelPermalink }}"></script>
```

leads to

bundle2.js (excerpt, commited to /results in reproducer)
```
    "sum_earnings": 6125
  }
];
㬊ഊ昊湵瑣潩⁮湩瑩慩楬敺畆
```

## Expected

The second file is appended without changes (to it's encoding).

# Analysis

When priting the ".Content" of the concatinated resource in the following way:

`{{ warnf "Test01 resouce content: %s" $jsBundle.Content }}`

For Bug1 the content is printed with the Semicolon. But all other special characters look correct.

![grafik](https://github.com/gohugoio/hugo/assets/1809629/9799d59a-f0c3-43c0-b1cc-8e6499e3be77)

For Bug2 the content is printed readable, but some non ASCII characters are printed with a diffrent encoding. In the following screenshot, missencoding of Korean caracters (but that might just be a `warnf` limitation).

![grafik](https://github.com/gohugoio/hugo/assets/1809629/c52b7386-9504-482c-bdab-ebe15f6cfd8e)

### What version of Hugo are you using (`hugo version`)?

`hugo-extended` `0.122.0` on Windows 10, installed via [scoop](https://scoop.sh/)

<pre>
$ hugo version
hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended windows/amd64 BuildDate=2024-01-26T15:54:24Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes, as 0.122 is the latest release.

If you need any more information or data, I am happy to ammend the reproducer.

**Comment by jmooring** [comment]
Bug 1: an extra semicolon is not a problem

Bug 2: Your assets/js/players400.js file is UTF16-LE encoded.

**Comment by tobijdc** [comment]
Absolutely correct, re-saveing `players400.js` as UTF-8 solves the issue.

Thank you
