### ISSUE TITLE
Don't use the same value in .Data.Term.Title as in .Title

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#12041]
In 0.123.0 we changed the `Title` for kind `term` to be in line with others, but that means that it throws away some value having `.Data.Term` return the same.

I saw a discussion about using the `i18n` func for translation taxonomy terms, and I don't see anything wrong or hard doing something like this:

```handlebars
{{ $i18nKey := printf "%s.%s.title" .Data.Plural .Data.Term }}
{{ $title := i18n $i18nKey | default .Title }}
```

**Comment by McShelby** [comment]
Just for the record, the discussion was about translating the taxonomy name itself, e.g `tags` or `categories`.

Putting term titles in an i18n file is a nice feature but I am not sure if many users would use this as it is easier to achieve this by overwriting the according `_index.md` file.
