### ISSUE TITLE
server: Newly created files are not rendered on refresh

### ISSUE THREAD

**Issue by TiGR** [gohugoio/hugo#12054]
When you start server, and then create a page, it won't appear in rendered pages list. Hugo notices the change, runs rebuild, but the lists stay the same. If you restart hugo, new page appears in the list.

Also, in some more complicated scenarios, new pages do appear in the lists, but they have empty content (empty title, empty content), even though it is not empty.

**Comment by bep** [comment]
I have tested this without any issues (took it for a spin now), so you need to be more specific.

**Comment by TiGR** [comment]
Okay, take for [example](https://github.com/TiGR/hugo-testing/tree/broken-getterms-issue) this example site.

1. Run hugo server
2. Open the server in browser, you'll see a list of pages, there is only one page, Test Page.
3. Make a new page (for instance, create a file `content/test-page-2/index.md`), fill it with some test content
4. Notice hugo runs rerender
5. Check the browser, see the list still showing only one page
6. Restart hugo
7. Check the browser and see that there is that new page in the list.

In hugo 0.122 everything works as expected.
