### ISSUE TITLE
Draft term pages not handled correctly

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12055]
hugo v0.123.0-DEV-9cc65757a

This test fails:

```go
func TestFoo(t *testing.T) {
	t.Parallel()

	files := `
-- layouts/_default/list.html --
|{{ .Title }}|
-- content/p1.md --
---
title: p1
tags: [a]
---
-- content/tags/a/_index.md --
---
title: tag-a-title-override
draft: true
---
  `

	b := hugolib.Test(t, files)

	b.AssertFileContent("public/tags/a/index.html", "|a|")
}
```

Want:

```
|a|
```

Got:

```text
|tag-a-title-override|
```

**Comment by jmooring** [comment]
I'm waiting on some new eye glasses. Just made a couple of edits to the above.

**Comment by jmooring** [comment]
Although the page title rendered above looks wrong to me, I have also lost/forgotten whether we should render the term page at all. Per [this discussion](https://github.com/gohugoio/hugo/issues/11809#issuecomment-1859251239), it seems like we should not render the term page is draft is true, but things may have changed since then.

**Comment by bep** [comment]
>Per https://github.com/gohugoio/hugo/issues/11809#issuecomment-1859251239, it seems like we should not render the term page if draft is true, but things may have changed since then.

* For the other branch nodes, we just disable them so they don't get rendered/listed but keep them to preserve structure.
* Looking at the code, I see that my idea was to just to remove these nodes (which I think makes sense).
