### ISSUE TITLE
Running hugo server outputs public folder

### ISSUE THREAD

**Issue by nathnp** [gohugoio/hugo#12067]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0-3c8a4713908e48e6523f058ca126710397aa4ed5+extended darwin/arm64 BuildDate=2024-02-19T16:32:38Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes

### Details

Running `hugo server` on version 0.123.0 outputs the `public` folder into the project folder. Previous versions would only do this when running `hugo` on its own. This also occurs when using the `-D` draft flag `hugo server -D`.

**Comment by jmooring** [comment]
This is the expected behavior with v0.123.0.  If you wish to render to memory use the `--renderToMemory` command line flag.
