### ISSUE TITLE
macOS build is slower, Linux is about the same

### ISSUE THREAD

**Issue by dvdksn** [gohugoio/hugo#12075]
Building <https://github.com/docker/docs> on the latest release of Hugo results in nearly 2x slower builds. I'm only seeing this on macOS though, when I run the build in Docker (Alpine Linux aarch64) the difference is not as big (though v0.123.0 is slightly slower, about 10%)

v0.123.0 build

```console
$ time hugo
Start building sites … 
hugo v0.123.0-3c8a4713908e48e6523f058ca126710397aa4ed5+extended darwin/arm64 BuildDate=2024-02-19T16:32:38Z VendorInfo=brew


                   |  EN   
-------------------+-------
  Pages            | 1088  
  Paginator pages  |    0  
  Non-page files   |  321  
  Static files     |   99  
  Processed images |    0  
  Aliases          | 1124  
  Cleaned          |    0  

Total in 11240 ms

real	0m11.338s
user	0m30.703s
sys	0m12.036s
```

v0.122.0 build

```console
$ time ./hugo 
Start building sites … 
hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended darwin/arm64 BuildDate=2024-01-26T15:54:24Z VendorInfo=gohugoio


                   |  EN   
-------------------+-------
  Pages            | 1087  
  Paginator pages  |    0  
  Non-page files   |  323  
  Static files     |   99  
  Processed images |    0  
  Aliases          | 1124  
  Sitemaps         |    1  
  Cleaned          |    0  

Total in 6664 ms

real	0m6.765s
user	0m29.331s
sys	0m1.705s
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0-3c8a4713908e48e6523f058ca126710397aa4ed5+extended darwin/arm64 BuildDate=2024-02-19T16:32:38Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by bep** [comment]
I may eventually have a look at it; our benchmarks show that it should be "slightly faster" in general, my manual tests on MacOS shows it to be about the same for the sites I have tested. But I guess it ... depends.

**Comment by jmooring** [comment]
Linux data points, building Docker site, removing resources/ and public/ before each build, average of 5 builds:

- v0.122.0 = 16.1 s
- v0.123.0 = 15.4 s

The difference is in the noise level.

**Comment by dvdksn** [comment]
@jmooring x86 or arm64?

**Comment by bep** [comment]
On my MacBook it builds 

* v0.122: 5.4 seconds
* v0.123: 6.5 seconds

**Comment by bep** [comment]
I'm closing this. Our limited budget doesn't allow us to spend time on debugging individual sites/setups.

**Comment by dvdksn** [comment]
Appreciate that you looked into it!
