### ISSUE TITLE
deploy into github pages with github actions failed. error msg is "failed to load modules"

### ISSUE THREAD

**Issue by teholic** [gohugoio/hugo#12073]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.122.0

</pre>

### Does this issue reproduce with the latest release?
I try to deploy my hugo project into github pages with github actions, I followed with the doc behind,but failed
https://gohugo.io/hosting-and-deployment/hosting-on-github/

here is the error message
https://github.com/teholic/teholic.github.io/actions/runs/7969793655
<img width="1202" alt="image" src="https://github.com/gohugoio/hugo/assets/29173577/df02de7c-f780-45eb-9619-acf2c99767f7">

**Comment by jmooring** [comment]
This is not a bug.

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
