### ISSUE TITLE
Book type fails in 0.123.0

### ISSUE THREAD

**Issue by AliceNN-ucdenver** [gohugoio/hugo#12070]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo version: 0.123.0
</pre>

### Does this issue reproduce with the latest release?

The book type no longer builds when I compare the cache files in 0.123.0 there is just a book.md and no folder as in the 0.122.0 version

ERROR render of "page" failed: "/Users/#/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5@v5.7.1-0.20230420205746-951c7b6f709d/layouts/_default/baseof.html:11:403": execute of template failed: template: book/single.html:11:403: executing "book/single.html" at <.File.UniqueID>: can't evaluate field File in type *source.File
ERROR render of "home" failed: "/Users/#/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5@v5.7.1-0.20230420205746-951c7b6f709d/layouts/_default/baseof.html:11:403": execute of template failed: template: index.html:11:403: executing "index.html" at <.File.UniqueID>: can't evaluate field File in type *source.File
Total in 303 ms
Error: error building site: render: failed to render pages: render of "section" failed: "/Users/#/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5@v5.7.1-0.20230420205746-951c7b6f709d/layouts/_default/baseof.html:11:403": execute of template failed: template: book/list.html:11:403: executing "book/list.html" at <.File.UniqueID>: can't evaluate field File in type *source.File

Using a very simple book layout based on the documentation:

```text
---
title: 🧠 Learn Generative Deep Learning
linkTitle: Generative DL
summary: CSCI 4800 Generative Deep Learning
date: '2021-01-17'
type: book
tags:
  - current
---

{{< figure src="featured.jpg" >}}

{{< toc hide_on="xl" >}}

# CSCI 4800: Generative Deep Learning
## Course Syllabus
### Fall, 2024
```

**Comment by jmooring** [comment]
I hate to pass the buck, but...

You are more likely to receive an accurate and timely response from the Hugo Blox team:
<https://github.com/HugoBlox/hugo-blox-builder/discussions>

They also have an active Discord channel:
<https://discord.com/invite/z8wNYzb>

Wowchemy isn't a thing anymore. They rebranded to HugoBlox, and I have no idea how I would track down the source. For their new stuff they list Hugo version compatibility; you might ask them about compatibility.

**Comment by AliceNN-ucdenver** [comment]
Found this for anyone else that runs into this: 
https://docs.hugoblox.com/reference/update/
https://discord.com/channels/722225264733716590/1175124420315058176/1175161625179852982
