### ISSUE TITLE
resources.Match seems to be renaming files with spaces, and making the resource nil

### ISSUE THREAD

**Issue by BrianLeishman** [gohugoio/hugo#12081]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

### Steps to recreate

```shell
hugo new site hugo-resource-rename
cd hugo-resource-rename
hugo new theme test
hugo new content hello.md
```

Then I added a shortcode

resources.html
```html
{{ range resources.Match `*` }}
    {{ .src }}
{{ end }}
```

referenced the shortcode

hello.md
```markdown
+++
title = 'Hello'
date = 2024-02-20T10:06:32-05:00
+++

Hello, World!

{{< resources >}}
```

Then added a "test doc.txt" in the assets folder, and I get this error

>  render: failed to render pages: render of "page" failed: [1;36m"/home/brian/hugo-resource-rename/themes/test/layouts/_default/single.html:8:5"[0m: execute of template failed at <.Content>: error calling Content: [1;36m"/home/brian/hugo-resource-rename/content/hello.md:8:1"[0m: failed to render shortcode "resources": failed to process shortcode: [1;36m"/home/brian/hugo-resource-rename/layouts/shortcodes/resources.html:2:7"[0m: execute of template failed at <.src>: can’t evaluate field src in type resource.Resource 

If I change `{{ .src }}` to `{{ . }}` in my partial, I see this output

```
Hello, World!
/test-doc.txt 
```

Where it appears to be adding a dash that wasn't there to begin with. If I remove the space myself it works as expected.

**Comment by bep** [comment]
Fixed in #12076

**Comment by BrianLeishman** [comment]
@bep I think that commit is part of the v0.123.1 release, but this issue is unchanged 

```shell
$ hugo version
hugo v0.123.1+extended linux/amd64 BuildDate=unknown
```

> Error: error building site: render: failed to render pages: render of "page" failed: "/home/brian/hugo-resource-rename/themes/test/layouts/_default/single.html:8:5": execute of template failed: template: _default/single.html:8:5: executing "main" at <.Content>: error calling Content: "/home/brian/hugo-resource-rename/content/hello.md:8:1": failed to render shortcode "resources": failed to process shortcode: "/home/brian/hugo-resource-rename/layouts/shortcodes/resources.html:2:7": execute of template failed: template: shortcodes/resources.html:2:7: executing "shortcodes/resources.html" at <.src>: can't evaluate field src in type resource.Resource

```gohtml
{{ range resources.Match `*` }}
    {{ .src }}
{{ end }}
```

**Comment by jmooring** [comment]
@BrianLeishman 

```
{{ range resources.Match `*` }}
  {{ .src }}
{{ end }}
```

In this context, `.src` isn't a thing.

Not sure what you're trying to do. Maybe you want this:

```text
{{ range resources.Match `*` }}
  {{ .Content }}
{{ end }}
```

These are the available methods on a `Resource` object:
<https://gohugo.io/methods/resource/>

`.src` isn't one of them.

This issue is closed. If you need further assistance, please create a new topic on the [forum](https://discourse.gohugo.io/). Thanks.

**Comment by BrianLeishman** [comment]
Ah true, duh, my bad! The files in our real source were images
