### ISSUE TITLE
[REQ] allow `hugo mod vendor` to vendor `purgecss.config.js`

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#12088]
EDITED: Sorry, it should be a feature request other than a bug, but I'm unable to remove the label.

```toml
[[module.imports]]
path = "github.com/hbstack/hb"
```

```sh
$ hugo mod vendor

$ ls _vendor/github.com/hbstack/hb                
assets  hugo.toml  layouts  package.json  postcss.config.js
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0-3c8a4713908e48e6523f058ca126710397aa4ed5+extended linux/amd64 BuildDate=2024-02-19T16:32:38Z VendorInfo=snap:0.123.0
</pre>

**Comment by bep** [comment]
My memory about this may be a little hazy, but I think the current logic is:

1. We vendor everything that has a mount.
2. We create mounts (if not already there) for some predefined *.js files.

I'm not sure we'd want to expand on 2), but I don't see why you cannot just mount your `purgecss.config.js` file yourself.

**Comment by razonyang** [comment]
> I don't see why you cannot just mount your purgecss.config.js file yourself.

You're right, it's more likely a custom JS file, I decide to move related files to `assets`, sorry for the noise.

**Comment by bep** [comment]
>You're right, it's more likely a custom JS file, I decide to move related files to assets, sorry for the noise.

No problem. But note that you can also mount files in the project root (which is often where you want to have these JS config files).
