### ISSUE TITLE
Cannot use .Scratch method in .Render

### ISSUE THREAD

**Issue by Lruihao** [gohugoio/hugo#12089]
At `single.html`, the `.Scratch` method is valid:

```html
{{- $author := .Scratch.Get "author" -}}
```

But via .Render, the `.Scratch` method is invalid:

```html
{{- range $pages.Pages -}}
  {{- .Render "summary" -}}
{{- end -}}
```
In `summary.html`, `.Scratch.Get "author"` got `<nil>`

I don't know why, but what I can confirm is that this bug occurs after updating version 0.123.0.

### Complete code

- [layouts/index.html](https://github.com/hugo-fixit/FixIt/blob/551938f0b418f63abd4eef514f81b9bf39c1ee95/layouts/index.html#L42-L44)
- [layouts/_default/summary.html](https://github.com/hugo-fixit/FixIt/blob/551938f0b418f63abd4eef514f81b9bf39c1ee95/layouts/_default/summary.html#L39)
- [layouts/partials/single/post-author.html](https://github.com/hugo-fixit/FixIt/blob/551938f0b418f63abd4eef514f81b9bf39c1ee95/layouts/partials/single/post-author.html)
- [layouts/posts/single.html](https://github.com/hugo-fixit/FixIt/blob/551938f0b418f63abd4eef514f81b9bf39c1ee95/layouts/posts/single.html#L44)

### What version of Hugo are you using (`hugo version`)?

**This problem occurs in 0.123.0**

<pre>
$ hugo version
hugo v0.123.0-3c8a4713908e48e6523f058ca126710397aa4ed5+extended darwin/arm64 BuildDate=2024-02-19T16:32:38Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by bep** [comment]
`.Scratch` works fine in `.Render`.

**Comment by Lruihao** [comment]
Oh sorry, it's not work fine for my theme:

At summary part, it's bad..
<img width="594" alt="image" src="https://github.com/gohugoio/hugo/assets/33419593/bf644bc2-2200-4c13-986c-936cdc98ec61">

But, at single page,it's work fine like before:
<img width="854" alt="image" src="https://github.com/gohugoio/hugo/assets/33419593/e6d10426-01eb-4411-8a11-ce8188e7de86">

see [post-author.html](https://github.com/hugo-fixit/FixIt/blob/551938f0b418f63abd4eef514f81b9bf39c1ee95/layouts/partials/single/post-author.html#L2)

> It was working fine up to version 0.122.0, but after updating to 0.123.0 it became terrible. Looking forward to your solution.

**Comment by jmooring** [comment]
@Lruihao I am unable to reproduce the problem. I followed your instructions:
<https://fixit.lruihao.cn/documentation/getting-started/>

Instead of asking us to create a new site, configure it, and create content, please create a minimal reproducible example that  consistently fails.

**Comment by Lruihao** [comment]
@jmooring There is a [demo](https://hugo-fixit.github.io/hugo-fixit-starter) [repo](https://github.com/hugo-fixit/hugo-fixit-starter) that can reproduce the problem.

**Comment by jmooring** [comment]
@Lruihao Please provide step-by-step instructions, including which page I am supposed to view to see the problem.

**Comment by jmooring** [comment]
OK, I can _intermittently_ reproduce the problem looking at the home page... with version v0.122.0. 

 **This has nothing to do with v0.123.0.**

It's happening intermittently when you run `hugo server` because scratch pads set with `.Scratch.Set` do not survive server rebuilds. Use `.Store.Set` and `.Store.Get` instead. See:
<https://gohugo.io/methods/page/store/>

And make sure you read the section titled "Determinate values":
<https://gohugo.io/methods/page/store/#determinate-values>

If you need additional assistance please create a new topic in the [forum](https://discourse.gohugo.io/). Thanks.

**Comment by Lruihao** [comment]
@jmooring In fact, I tried before creating this issue Store, but this issue still occurs during the first Hugo serve or build, so I reverse this [commit]().

I will create a discussion on the forum later. Thanks！
