### ISSUE TITLE
Regression: error calling Paginator: pagination not supported for this page: kind: "page"

### ISSUE THREAD

**Issue by skrysmanski** [gohugoio/hugo#12080]
Up until Hugo 0.122, you could (in a partial) check if the current page is paginated like this:

```
{{- if .Page.Paginator -}}
```

Since Hugo 0.123 this is no longer possible. Instead you get this error:

> error calling Paginator: pagination not supported for this page: kind: "page"

I reckon that this could be an intended change, although it's not listed in the list of breaking changes (#11455) and so I thought to better report it. 

The change could be related to #11949 but I never experienced this bug (it simply worked for me).

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0-3c8a4713908e48e6523f058ca126710397aa4ed5+extended windows/amd64 BuildDate=2024-02-19T16:32:38Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by bep** [comment]
This was a bug fix.

You can do something ala:

```
{{- if and .Page.IsNode .Page.Paginator -}}
```

**Comment by jmooring** [comment]
Be careful when using `.IsNode` as suggested above; it returns `true` in the 404 template. See https://github.com/gohugoio/hugo/issues/12162 and https://github.com/gohugoio/hugo/issues/12192.

**Comment by shinyzhu** [comment]
This is interesting. It's still there when I updated to 0.124.1.

Thanks for the `.IsNode` check. That works fine.

> Be careful when using `.IsNode` as suggested above; it returns `true` in the 404 template. See #12162 and #12192.

So are there any other better solutions?
