### ISSUE TITLE
Add Sort By File Path

### ISSUE THREAD

**Issue by BayuAngora** [gohugoio/hugo#12097]
![IMG_20240221_191759](https://github.com/gohugoio/hugo/assets/16639529/0f5bd9c1-f013-467f-ac62-8cd259afdd28)

We can sort by date, title, weight, length, etc.
What if we can sort .ByFilePath (by file path)?

**Comment by jmooring** [comment]
You can easily sort by the logical path using the sort function:

```
{{ $p := sort .Pages "Path" "asc" }}
```

I have already given you a working example here:
<https://discourse.gohugo.io/t/pagination-sort-by-file-path/48371>
