### ISSUE TITLE
ERROR TOCSS: failed to transform file after v0.123.1

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#12094]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.1-3f8434a62fc91a50f4e5bd43a4435d2d301844ff+extended linux/amd64 BuildDate=2024-02-21T08:17:45Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

---

After v0.123.0 (also 0.123.1) we are getting two build failures for our docs:

CI run: https://github.com/twbs/bootstrap/actions/runs/7987176517/job/21809124130?pr=39698

```
1. ERROR TOCSS: failed to transform "/scss/docs.scss" (text/x-scss): "/home/runner/work/bootstrap/bootstrap/site/assets/scss/_variables.scss:17:45": Undefined variable: "$pink-500".
2. ERROR [en] REF_NOT_FOUND: Ref "/docs/5.3/examples/": "/home/runner/work/bootstrap/bootstrap/site/content/docs/5.3/getting-started/rtl.md:68:52": page not found
```

For the second error, the shortcode is this one: https://github.com/twbs/bootstrap/blob/main/site/layouts/shortcodes/docsref.html

v0.122.0 works without errors. Is this due to the [breaking changes](#11455) in v0.123.0 or is it a regression?

Thanks for your hard work!

**Comment by bep** [comment]
>due to the [breaking changes](https://github.com/gohugoio/hugo/issues/12094#11455) in v0.123.0 or is it a regression?

A regression.

**Comment by XhmikosR** [comment]
Should I create a separate issue for the second error?

**Comment by bep** [comment]
My comment above is about the ToCSS (which is in the title) error.
