### ISSUE TITLE
ERROR [en] REF_NOT_FOUND after v0.123.1

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#12096]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.1-3f8434a62fc91a50f4e5bd43a4435d2d301844ff+extended linux/amd64 BuildDate=2024-02-21T08:17:45Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

---

Split from #12094.

CI run: https://github.com/twbs/bootstrap/actions/runs/7987176517/job/21809124130?pr=39698

```
ERROR [en] REF_NOT_FOUND: Ref "/docs/5.3/examples/": "/home/runner/work/bootstrap/bootstrap/site/content/docs/5.3/getting-started/rtl.md:68:52": page not found
```

The shortcode is this one: https://github.com/twbs/bootstrap/blob/main/site/layouts/shortcodes/docsref.html
Examples: https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/examples/_index.md

Going back to v0.122.0 works without errors.

**Comment by olikami** [comment]
I have the same issue, here's a reproducible minimal example:

https://github.com/olikami/relrefdemo
