### ISSUE TITLE
Page resources missing when language variant is draft

### ISSUE THREAD

**Issue by nibe** [gohugoio/hugo#12105]
When you have different language variants of a page (say `example/index.md` and `example/index.de.md`) and one of them is a draft, `.Resources.Get` and `.Resources.GetMatch` return `nil` for any resources.

In Hugo 0.122.0 it worked fine. Here's a minimal, reproducible example. Just unpack it and run `hugo`.
[quickstart.zip](https://github.com/gohugoio/hugo/files/14363853/quickstart.zip)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.1-3f8434a62fc91a50f4e5bd43a4435d2d301844ff+extended darwin/arm64 BuildDate=2024-02-21T08:17:45Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by bep** [comment]
I will test this, but one of the changes in v0.123.0 is that we don't duplicate resources (except in some cases) per language, so _one resource file_ is attached to one language. That also means that if you draft the owning header, that resource also goes away. Does this match what you're seeing?

**Comment by flexxgaad** [comment]
https://github.com/gohugoio/hugo/issues/11986#issuecomment-1925903883

**Comment by jmooring** [comment]
I can confirm the problem. Drafting a non-default language page removes the shared resource for all translations.

```text
git clone --single-branch -b hugo-github-issue-12105 https://github.com/jmooring/hugo-testing hugo-github-issue-12105
cd hugo-github-issue-12105
rm -rf public/ && hugo && tree public
```

Content:

```text
content/
├── de/
│   ├── my-bundle/
│   │   └── index.md   <-- draft = true
│   └── _index.md
├── en/                <-- this is the default content language
│   ├── my-bundle/
│   │   ├── a.jpg
│   │   └── index.md
│   └── _index.md
├── fr/
│   ├── my-bundle/
│   │   └── index.md
│   └── _index.md
└── _index.md

```

Expected output:

```text
public/
├── de/
│   └── index.html
├── en/
│   ├── my-bundle/
│   │   ├── a.jpg
│   │   └── index.html
│   └── index.html
├── fr/
│   ├── my-bundle/
│   │   └── index.html
│   └── index.html
├── favicon.ico
└── index.html
```

Actual output:

```text
public/
├── de/
│   └── index.html
├── en/
│   ├── my-bundle/
│   │   └── index.html
│   └── index.html
├── fr/
│   ├── my-bundle/
│   │   └── index.html
│   └── index.html
├── favicon.ico
└── index.html
```
