### ISSUE TITLE
.Resources.Match .Name converting spaces to hyphens

### ISSUE THREAD

**Issue by ultraflynn** [gohugoio/hugo#12122]
My site has been rendering correctly for several years now and I haven't made any changes to the templates but now I can longer build the site.

I have a range loop over some resources:

<pre>
{{ range .Resources.Match "*.jpg" }}
        {{ $metadata := split .Name "_" }}
        {{ $title := index $metadata 0 }}
        {{ $author := index $metadata 1 }}
        {{ $score := index $metadata 2 }}
        // ...
{{ end }}
</pre>

My site has a large number of images in, with each file name containing 4 items of information separated by a "_". The intention of the code above is to find all the JPG files and process the filename, pulling out these 4 items of information.

What I'm observing is the `.Name' no longer gives me the name of the file as it exists on the disk, it now returns the name of the file, all lowercases and with each space converted to a "-". Although the underscores still exist, the rest of the filename is garbage because all spaces are being converted to hyphens and everything else is lowercased.

### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.123.2-929b91fe75cb0d041f22b4707700dfc117115ad4+extended darwin/arm64 BuildDate=2024-02-22T15:27:15Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
This was an intentional breaking change. Do this instead:

```text
{{ range .Resources.Match "*.jpg" }}
  {{ $metadata := split (path.Base .Key) "_" }}
  ...
{{ end }}
```
