### ISSUE TITLE
Ability to use a generic external HTML generator

### ISSUE THREAD

**Issue by suhail-singh** [gohugoio/hugo#12127]
The RST markup converter uses the external `rst2html` program.  However, it
isn't intended for converting arbitrary markup to HTML.  It has been written
specifically to support the conversion of RST documents to HTML and for Hugo to
leverage that capability.

It would be helpful for a user to be able to provide Hugo an arbitrary
commandline invocation that generates HTML for a given document.  For
flexibility, the provided commandline invocation could, perhaps, have some
placeholder syntax for specifying the name of the file (that is being processed
by Hugo).  Hugo would substitute in the name of the file into the provided
invocation and then invoke the external process for generating the HTML.

With such a capability, a user would be able to, for instance, more easily
customize the generated HTML using a programming language of their choice and/or
reuse existing HTML generators written in other languages.  For instance, having
such a capability one would be able to use Emacs itself to export Org mode
document to HTML (using one of several different possible Emacs Org HTML
exporter packages).

**Comment by bep** [comment]
Adding a general "command line" tool is not something we're going to do (there are discussions about this).

I do, however, have plans on adding some plugin support in this area. This would be Go plugins, but from there you could do whatever you want. This would (potentially) solve some of the current issues with Pandoc, Asciidoc etc., as these new plugins would act as servers the run as long as the build runs.

**Comment by bep** [comment]
>Would patches to that effect would be welcome or unwelcome?

It would not be merged.

**Comment by bep** [comment]
@suhail-singh I will in the implementing issue.
