### ISSUE TITLE
relref still not working properly in 0.123.x

### ISSUE THREAD

**Issue by mbevc1** [gohugoio/hugo#12136]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.123.3-a75a659f6fc0cb3a52b2b2ba666a81f79a459376+extended linux/amd64 BuildDate=2024-02-23T17:09:20Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

After a fix in 0.123.1 `relref` is still not working correctly. So https://github.com/gohugoio/hugo/issues/12096 was closed only for `relrefs` with trailing slash, but it doesn't find files now. Seems like a new regression.

Example:
```
hugo-1  | Watching for changes in /src/{archetypes,content,data,static,themes}
hugo-1  | Watching for config changes in /src/config.yaml
hugo-1  | Start building sites … 
hugo-1  | hugo v0.123.3-a75a659f6fc0cb3a52b2b2ba666a81f79a459376+extended linux/amd64 BuildDate=2024-02-23T17:09:20Z VendorInfo=gohugoio
hugo-1  | 
hugo-1  | ERROR [en] REF_NOT_FOUND: Ref "/content/blog/20220525-view-from-the-top/index.md": "/src/content/blog/20230911-5-cta/index.md:29:77": page not found
...
hugo-1  | Built in 14685 ms
hugo-1  | Error: error building site: logged 3 error(s)
```

**Comment by jmooring** [comment]
Please provide a minimal example. Logs are insufficient.
