### ISSUE TITLE
Images from "branch bundle" are not available for _index.md in 0.123.2

### ISSUE THREAD

**Issue by KOT-OPET** [gohugoio/hugo#12140]
Hello, 
I've been using Hugo and Render.com deployment for [my site](https://ebgdae.ru) for a month. Recently Render.com updated its Hugo package, which resulted in build errors.

This is a fragment from _index.md of [/customshop/](https://ebgdae.ru/customshop/):

```
![](zander.jpg)
...
![](colossus.jpg)
```
Those images are in the same directory as _index.md on my local machine, as well as on my Github repo.

<img width="257" alt="Screenshot 2024-02-24 at 13 51 07" src="https://github.com/gohugoio/hugo/assets/140557966/19f65f51-789a-40ad-be55-724637d0fcef">

My local version builds flawlessly.

However, the newer version of Hugo results in build error:

```
ERROR Image zander.jpg is missing and not external for page customshop/_index.md
ERROR Image colossus.jpg is missing and not external for page customshop/_index.md
```

### What version of Hugo are you using (`hugo version`)?
* v0.121.2 on a local machine;
* v0.123.2 on render.com
both are extended.

### Does this issue reproduce with the latest release?

Not sure; there's no mention of this bug in 0.123.3 changelog, so I assume it's still there.

**Comment by bep** [comment]
Bug reports needs to be very specific for us to be able to look at it and fix it, the best is a link to a runnable example. We have thousands of automated test cases and we, the Hugo maintainers, use `hugo` daily, so any bug reported will be about a corner case that we somehow didn't think about.

**Comment by KOT-OPET** [comment]
Understood. I opened my repo for you:
https://github.com/KOT-OPET/ebgdae

Keep in mind this is a pretty big project, so you probably would want to delete everything from /content/ folder except /content/customshop/ on your copy. Otherwise the build time would be enormous, given there would be no pre-rendered assets.

**Comment by jmooring** [comment]
@KOT-OPET It would be even easier if you were to clone your repo, removing everthing that isn't required to reproduce the issue. Access to a repo is helpful; a minimal reproducible example is even better!

**Comment by jmooring** [comment]
Your site uses [hyas](https://github.com/gethyas/hyas), which is very complex; we're not going to troubleshoot that.

 Please raise your question here:
- <https://github.com/orgs/gethyas/discussions>, OR
- <https://github.com/gethyas/hyas/issues>

**Comment by KOT-OPET** [comment]
ok, thanks! Sorry to bother you and thanks for the quick response
