### ISSUE TITLE
Template lookup order no longer finds layouts/taxonomy/tag.html

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12146]
This worked with v0.122.0 and earlier:

```
layouts/taxonomy/tag.html
```

That template is not found with v0.123.0 and later.

These don't work either:
- layouts/_default/tag.html
- layouts/_default/tag.html.html
- layouts/taxonomy/tag.html.html

Reference: <https://discourse.gohugo.io/t/0-123-removed-my-tag-descriptions/48462>

**Comment by bep** [comment]
Hmm. This test passes:

```go

func TestTaxonomiesTermLookup(t *testing.T) {
	t.Parallel()

	files := `
-- hugo.toml --
baseURL = "https://example.com"
[taxonomies]
tag = "tags"
-- content/_index.md --
---
title: "Home"
tags: ["a", "b"]
---
-- layouts/taxonomy/tag.html --
Tag: {{ .Title }}|
`
	b := Test(t, files)
	b.AssertFileContent("public/tags/a/index.html", "Tag: A|")
}

```

?

**Comment by jmooring** [comment]
The rest of the story...

```
-- content/tags/a/_index.md --
---
title: tag-a-title-override
---
```

**Comment by theory** [comment]
Oh man, thank you for figuring this out and getting it fixed. It was kicking my ass! template path resolution gets complicated quickly.
