### ISSUE TITLE
`cleanDestinationDir` does not remove rss and sitemap files

### ISSUE THREAD

**Issue by akbyrd** [gohugoio/hugo#12147]
RSS files (index.xml) and sitemap files (sitemap.xml) are not removed when using this option. The documentation states "removes files from destination not found in static directories". Neither of those file types are static, so either the documentation should be amended or the option should remove them.

Steps to repro:
* Build a site
* Confirm `public/` directory is populated
* Add something to the site that will cause it to fail to build
* Build site with `--cleanDestinationDir`
* Notice `public/` contains rss and sitemap files

Hugo 0.123.3

**Comment by jmooring** [comment]
I'm not sure I understand this.

By default, unless you disable the `rss` and `sitemap` page kinds in your site configuration, Hugo generates these files every time you build your site. 

If you disable those page kinds in your site configuration, then manually create one in the public directory, if will be removed when you run `hugo --cleanDestinationDir`.

For anyone else stumbling across this, note that the `--cleanDestinationDir` flag doesn't do anything unless you have a `static` directly in the root of your project (even an empty directory is sufficient).

**Comment by akbyrd** [comment]
Ah, it's a misunderstanding on my part. I saw the files and thought they weren't being removed. But they are being removed and subsequently replaced with new versions. It makes sense that individual files are output as they are built, so a failed build is not "all or nothing" and you'll end up with whatever output was compiled before the error.
