### ISSUE TITLE
ignoreLogs = ['cascade-pattern-with-extension'] emits console error

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12151]
With this config...

```text
ignoreLogs = ['cascade-pattern-with-extension']

[[cascade]]
[cascade.params]
foo = 'bar'
[cascade._target]
path = '/p1.md'   <-- will trigger the error that we want to suppress
```

...the build completes as expected with status code 0 (no errors), yet the console displays:

> ERROR cascade target path "/p1.md" looks like a path with an extension; since Hugo v0.123.0 this will not match anything, see  https://gohugo.io/methods/page/path/
You can suppress this error by adding the following to your site configuration:
ignoreLogs = ['cascade-pattern-with-extension']

The test below passes (as it should), but needs a log assertion (I couldn't get that to work).

<details>
<summary>test case</summary>

```go
func TestFoo(t *testing.T) {
	files := `
-- hugo.toml --
disableKinds = ['page','rss','section','sitemap','taxonomy','term']
ignoreLogs = ['cascade-pattern-with-extension']
[[cascade]]
[cascade.params]
foo = 'bar'
[cascade._target]
path = '/p1.md'
-- layouts/index.html --
{{ .Title }}
-- content/index.md --
---
title: home
---
-- content/p1.md --
---
title: p1
---
`

	b, err := TestE(t, files)
	b.Assert(err, qt.IsNil)
}
```
</details>
<br>

Reference: <https://discourse.gohugo.io/t/ignorelogs-cascade-pattern-with-extension-is-ignored/48383>

**Comment by bep** [comment]
>The test below passes (as it should), but needs a log assertion (I couldn't get that to work).

It doesn't log an error, which is correct, which I suspect is the reason you couldn't get it to work.

**Comment by jmooring** [comment]
It may not "log" an error, but an error is displayed in the console:

```text
git clone --single-branch -b hugo-github-issue-12151 https://github.com/jmooring/hugo-testing hugo-github-issue-12151
cd hugo-github-issue-12151
hugo server
```

![image](https://github.com/gohugoio/hugo/assets/335669/be116c1b-b1e2-4625-b8b0-71fb2c1705db)

**Comment by bep** [comment]
Yea, right ... we're logging this before we have configured the ... logger.

**Comment by jmooring** [comment]
Thanks for confirming, and please let me know if there's a simple assertion (or example) for testing stdout and stderr.
