### ISSUE TITLE
Broken emojis after move to goldmark-emoji 

### ISSUE THREAD

**Issue by KwadroNaut** [gohugoio/hugo#12168]
Took me a while to figure out that the move to goldmark-emoji  broke several things. Some emojis are broken, maybe there's a different set that's better to use or you help upstream?

I ran into missing emojis for :mobile_phone: and :laptop: 

### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.123.3
</pre>

Started with [0.120](https://github.com/gohugoio/hugo/commit/272484f8bfab97dbadad49a638a3e4b6af499f15)

**Comment by jmooring** [comment]
Hugo supports GitHub's emoji shortcodes, with the exception of shortcodes that are unique to GitHub (e.g., `:octocat:`).

As exemplified by your comment above, GitHub doesn't support either `:mobile_phone:` or `:laptop:`.

Here is the the list of supported shortcodes:
<https://gohugo.io/quick-reference/emojis/>

This is a [detailed explanation of the change](https://github.com/gohugoio/hugo/issues/11668#issuecomment-1792797629) we made in v0.120.0.
