### ISSUE TITLE
Partial live reload not working for mixed case templates

### ISSUE THREAD

**Issue by FN-FAL113** [gohugoio/hugo#12165]
The css are declared in a style declaration tag. CSS from the parent element are being updated properly in the page but with partials I have to change to different page then go back. I tried updating hugo from v0.123.3 to the latest but no to avail.

OS: Windows 11 (22H2)
IDE: vscode
BROWSER: Chrome/Edge/Firefox

**UPDATE**: Even the partial does not get updated when changing its html, I have tried various arguments like no http cache, ignore cache and disable fast render, still not working unfortunately. The partial is in a loop that receives an iterated regular page context.

### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.123.4-21a41003c4633b142ac565c52da22924dc30637a+extended windows/amd64 BuildDate=2024-02-26T16:33:05Z VendorInfo=gohugoio

</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by FN-FAL113** [comment]
I have to downgrade for now using this version to experience a fully working live reload:
```
hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended windows/amd64 BuildDate=2024-01-26T15:54:24Z VendorInfo=gohugoio
```

**Comment by bep** [comment]
We re-implemented the partial server rebuilds in Hugo `v0.123.0` from a coarse grained to a more fine grained strategy. It's not possible for us with the little information you provide to determine why this isn't working for you. If you want us to look at it, we need a failing running source example. Note that you, in most cases, can get back to a more "coarse grained" approach (which is needed in some use cases, e.g. `TailwindCSS`) by set up some more cache buster rules, see [Cache Busters]( https://gohugo.io/getting-started/configuration/#configure-cache-busters). A related tip would be to run `hugo --logLevel debug` and see how well the current cache buster configuration matches.

**Comment by FN-FAL113** [comment]
Another set of debug messages:
```
Change detected, rebuilding site (#2).
2024-02-27 18:40:52.348 +0800
DEBUG cachebuster: Matching "layouts/partials/postcard.html" with source "(postcss|tailwind)\\.config\\.js": no match
Template added /partials/postcard.html
DEBUG Direct dependencies of "/partials/postcard.html" (*paths.Path) =>
INFO  build:  step process substep resolve page output change set changes 1 checked 35 matches 0 duration 539.8µs
INFO  build:  step process substep gc dynacache duration 606.2µs
INFO  build:  step process substep rebuild templates duration 6.4796ms
INFO  build:  step process duration 14.0897ms
INFO  build:  step assemble duration 0s
INFO  build:  step render substep pages site en outputFormat html duration 0s
INFO  build:  step render substep pages site en outputFormat rss duration 552.4µs
INFO  build:  step render pages 0 content 0 duration 3.2514ms
INFO  build:  step postProcess duration 0s
INFO  build:  duration 17.9574ms
Total in 17 ms
```

**Comment by jmooring** [comment]
@FN-FAL113 See bep's response:

> If you want us to look at it, we need a failing running source example.

That means we need a small test repo that successfully builds and consistently reproduces the condition you describe.

**Comment by FN-FAL113** [comment]
https://github.com/FN-FAL113/hugo-test-partial-live-reload
a partial ```postCard.html``` is utilized as a component to render regular pages.
