### ISSUE TITLE
Symlinks cannot be used for images in Hugo 123 any more.

### ISSUE THREAD

**Issue by rakino** [gohugoio/hugo#12164]
I made a test configuration in [this repo](https://github.com/rakino/hugo-123-symlink-image-test), layout listed below:
```text
.
├── config.toml
├── content
│   └── posts
│       └── test
│           ├── index.md
│           └── test.png -> ../../../test.png
├── go.mod
└── test.png
```

In Hugo 122:

![image](https://github.com/gohugoio/hugo/assets/26847027/7cc682b1-e409-4f52-a487-14895a1f6e7b)

In Hugo 123:

![image](https://github.com/gohugoio/hugo/assets/26847027/df358602-6b9d-4ad0-aaab-e2ab6a0715fd)

**Comment by jmooring** [comment]
This is correct. With v0.123.0 and later you must use module mounts instead.

<https://gohugo.io/getting-started/directory-structure/#union-file-system>
<https://gohugo.io/hugo-modules/configuration/#module-configuration-mounts>

**Comment by rakino** [comment]
Thank you for the explanation! :)
