### ISSUE TITLE
Summary don't include image ![text](path title)

### ISSUE THREAD

**Issue by henrysheehy** [gohugoio/hugo#12160]
Could we exclude the contents (text and title) of `![text](path title)` from the page `.Summary`? A RegEx along the lines of `replaceRE `(!\[.*\]\(.*\)\s*)` "" .RawContent` before applying `.StringRender` should do it. 

Thank you!

**Comment by jmooring** [comment]
The right way to handle this is to _control_ what you want in your summary by either:

1. Creating a manual summary break by placing the string `<!--more-->` somewhere in your markdown, or
2. Defining the summary in front matter

See [docs](https://gohugo.io/content-management/summaries/#summary-splitting-options).

Trying to programmatically remove things from an automatic summary  might be the right thing for you, but not for others.
