### ISSUE TITLE
Empty section pages created when using nested taxonomies

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12188]
Not sure if this is a bug, but the result is different (undesirable) when comparing v0.123.7 to v0.122.0.

#### Scenario

- Multilingual single-host site
- English site has content, Japanese site **has no content**
- Site has a language switcher to switch between langs on each page
- Taxonomies are "nested' by content type (support  for this is not documented, but I've seen it used on several sites):

```text
[taxonomies]
'papers/category' = 'papers/category'
'blog/category' = 'blog/category'
```

#### Expected (v0.122.0)

```text
public/ja/
├── blog/
│   └── category/
│       └── index.html
├── papers/
│   └── category/
│       └── index.html
└── index.html
```

#### Actual (v0.123.6)

```text
public/ja/
├── blog/
│   ├── category/
│   │   └── index.html
│   └── index.html     <-- problem: has section page despite lack of content
├── papers/
│   ├── category/
│   │   └── index.html
│   └── index.html     <-- problem: has section page despite lack of content
└── index.html 
```

#### Why  is this a problem?

When visiting the "blog" section page on the English site, the language switcher indicates that there is a Japanese translation, which is (obviously) just an empty page.

#### Test case

<details>
<summary>test case</summary>

```go
func TestFoo(t *testing.T) {
	t.Parallel()

	files := `
-- hugo.toml --
disableKinds = ['rss','sitemap']
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages.en]
weight = 1
[languages.ja]
weight = 2
[taxonomies]
's1/category' = 's1/category'
-- layouts/_default/single.html --
{{ .Title }}|
-- layouts/_default/list.html --
{{ .Title }}|
-- content/s1/p1.en.md --
---
title: p1
---
`

	b := hugolib.Test(t, files)

	b.AssertFileExists("public/en/s1/index.html", true)
	b.AssertFileExists("public/en/s1/p1/index.html", true)
	b.AssertFileExists("public/en/s1/category/index.html", true)

	b.AssertFileExists("public/ja/s1/index.html", false) // failing test
	b.AssertFileExists("public/ja/s1/category/index.html", true)
}
```
</details>
<br>

Reference: <https://discourse.gohugo.io/t/hugo-attempting-to-build-pages-on-multilingual-site-for-languages-with-no-content/48561/4>

**Comment by AlanBreck** [comment]
Another way in which this causes problems is that templates can fail due to missing data on pages that weren't intended to build, nor have content. For instance, I discovered this due to a template rendering data from the frontmatter, but since it was attempting to build for all defined languages, it was throwing errors. This is resolvable by wrapping in a `with` or `if` block, but if for some reason I wanted it to fail in the absence of data for actual content pages, this would be undesirable.

**Comment by AlanBreck** [comment]
Thank you!
