### ISSUE TITLE
Leap year display in posts list show as 1 a 0001

### ISSUE THREAD

**Issue by sineer** [gohugoio/hugo#12181]
# Today is leap year feb 29th and in my posts it shows up as Jan 1st 0001 ?

when I change the date for 2024-02-28 instead of -29 then it works.

Maybe it is some templating of the awesome-hugo-blog theme I'm using that does that too? I have no idea. 

It only happens every 4 year so maybe no one else noticed?

![image](https://github.com/gohugoio/hugo/assets/395171/dc761685-db7e-4efd-af25-84f0a83b6a45)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0+extended linux/amd64 BuildDate=unknown VendorInfo=gentoo:0.123.0

</pre>

### Does this issue reproduce with the latest release?
I believe it is latest release

**Comment by jmooring** [comment]
Unable to reproduce when testing at 2024-02-29T16:26:44-08:00.

```text
{{ now.Format "2006-01-02" }}          --> 2024-02-29
{{ now | time.Format "2006-01-02" }}   --> 2024-02-29
{{ now | time.Format ":date_medium" }} --> Feb 29, 2024
```

I suggest you reach out to the theme author:
<https://github.com/hugo-sid/hugo-blog-awesome>
