### ISSUE TITLE
Expose `.SitemapAbsURL` to robots.txt

### ISSUE THREAD

**Issue by septs** [gohugoio/hugo#12197]
## Motivation

expose `.SitemapAbsURL`, can simplify robots.txt provide sitemap absolute url complex

especially multi-site, multi-language

## Current Status

- https://github.com/docker/docs/blob/6d1edcc074d47c7e75cefc9823842a33edc61de0/layouts/index.robots.txt#L5
- https://github.com/tinacms/tinacms/blob/d6af1fafadafec6c9dff0c6b481847c6fe333c5b/examples/hugo-quickstart/themes/ananke/layouts/robots.txt#L5
- https://github.com/nugget/www.ropieee.org/blob/38190e6c1a52604f67e189a14c47a0a6be56fd45/layouts/robots.txt#L3
- https://github.com/goupaz/goupaz.com/blob/020687155ffa94b4e9056e527527f0616d1a7425/blog/themes/hugo-geekblog/layouts/robots.txt#L3
- etc

## Expected

```plain
User-agent: *
Sitemap: {{ .SitemapAbsURL }}
{{- range .Sites }}
Sitemap: {{ .SitemapAbsURL }}
{{- end }}
```

## References

https://github.com/gohugoio/hugo/blob/b1de03f398620eb97e005ae01e1955627475b7c9/hugolib/site.go#L543-L551

**Comment by jmooring** [comment]
Using `SitemapAbsURL`[^1] in a robots.txt file would work for:

- Monolingual sites
- Multilingual, multi-host sites

But, as implemented today, it would fail for multilingual, single-host sites. In that case, the robots.txt file should point to the sitemap index, not a sitemap.

[^1]: This was exposed to the templates in v0.111.3 and earlier, removed in v0.112.0.

I'm closing this in favor of https://github.com/gohugoio/hugo/issues/4678.
