### ISSUE TITLE
Global resource isn't published when using an uncommon code construct

### ISSUE THREAD

**Issue by adityatelange** [gohugoio/hugo#12190]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.7-312735366b20d64bd61bff8627f593749f86c964 linux/amd64 BuildDate=2024-03-01T16:16:06Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

### Steps to reproduce

1. Clone PaperMod's exampleSite https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite
2. Build with hugo
3. Observe that public directory does not contain images.

Images are linked on this page https://github.com/adityatelange/hugo-PaperMod/blob/4bdc993b98cc82d1c59efca0774f85811b0bf213/content/posts/papermod/papermod-installation.md?plain=1#L10-L12

**Comment by jmooring** [comment]
Without digging into this too much...

1\) When I build the example site with v0.122.0, I see:

```text
public/assets/
├── css/
│   └── stylesheet.0ede93e9169d0d059603a3eb4a3ecfb1dde2b3ad9f49b4079fc9b78c1a042d13.css
└── js/
    └── search.6414a722d5dffb9b3a958f0cbefccac6b7a82cb0beaa6c759d0d473bb6c7e7cc.js
``` 

There are no images in the above, so this doesn't appear to be anything new.

2\) Why should the images be published to the assets directory?

**Comment by adityatelange** [comment]
> Without digging into this too much...
> 
> 1) When I build the example site with v0.122.0, I see:
> 
> ```
> public/assets/
> ├── css/
> │   └── stylesheet.0ede93e9169d0d059603a3eb4a3ecfb1dde2b3ad9f49b4079fc9b78c1a042d13.css
> └── js/
>     └── search.6414a722d5dffb9b3a958f0cbefccac6b7a82cb0beaa6c759d0d473bb6c7e7cc.js
> ```
> 
> There are no images in the above, so this doesn't appear to be anything new.
> 
> 2) Why should the images be published to the assets directory?

1) My bad they go to public/images instead of public/assets

2)  To use it as a global resource https://gohugo.io/content-management/image-processing/#global-resource

**Comment by jmooring** [comment]
To reproduce:

```text
git clone https://github.com/adityatelange/hugo-PaperMod
cd hugo-PaperMod
git checkout exampleSite
git submodule update --init --recursive
rm -rf public && hugo && tree public/images
```

This worked in v0.122.0, and stopped working in v0.123.0 through v0.123.7.

**Comment by jmooring** [comment]
@adityatelange 

> Another issue site.Home.AllTranslations behaves differently

If it's another issue, open another issue.

**Comment by jmooring** [comment]
Here's the change in behavior...

#### Content
```text
content/
└── _index.md
```

#### Template

I have never seen or used this construct before; not sure if it was ever supposed to work.

```text
{{ with resources.ByType "text" }}
  {{ with .Get "a.txt" }}
    {{ .Publish }}
  {{ end }}
{{ end }}
```

#### Expected (v0.122.0)

```text
public/
├── a.txt
└── index.html
```

#### Actual (v0.123.7)

```text
public/
└── index.html
```

#### Test case

TBD

**Comment by adityatelange** [comment]
@jmooring I don't understand why this is being highlighted as uncommon/questionable code construct?

Global resources are useful and are required when you intend to use a single image with all pages. For example processing images to watermark your images or apply some filter on all of them (read https://adityatelange.in/blog/hugo-watermarking-images/#the-code-snippet-).

**Comment by jmooring** [comment]
> Global resources are useful and are required

I understand that, but I have never seen the construct where the `.Get/.GetMatch/.Match/.ByType` methods are used with a slice of _global_ resources. And obviously there's not an existing test for this. 


I don't have a problem with construct; I like the parallelism:

```
{{ with resources.ByType "text" }}
  {{ with .Get "a.txt" }}
    {{ .Publish }}
  {{ end }}
{{ end }}

{{ with .Resources.ByType "text" }}
  {{ with .Get "c.txt" }}
    {{ .Publish }}
  {{ end }}
{{ end }}
```

**Comment by adityatelange** [comment]
Hi @jmooring, I see this isn't fixed yet. Please check build logs here https://github.com/adityatelange/hugo-PaperMod/actions/runs/8191602302/job/22401179967#step:8:24 Images are not present specifically https://adityatelange.github.io/hugo-PaperMod/images/papermod-cover.png

**Comment by jmooring** [comment]
@adityatelange We fixed _this_ issue, but it looks like there's a matching problem now. I will open a new issue.

FYI, commenting on a closed issue isn't the best approach. Frequently such comments are ignored because... the issue is closed.
