### ISSUE TITLE
Section page resource not published if resource filename partially matches content file name

### ISSUE THREAD

**Issue by mwegnr** [gohugoio/hugo#12198]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.7-312735366b20d64bd61bff8627f593749f86c964+extended linux/amd64 BuildDate=2024-03-01T16:16:06Z VendorInfo=gohugoio

</pre>

### Does this issue reproduce with the latest release?
Yes, reproducible from 0.123.0 to latest (0.123.7)

### Problem Description

When a page-file has the same basename as the resources in the folder, the resources do not get included in the page build with `hugo`. This was different in hugo 0.122.0.

This folder structure 
```
content/news
content/news/renamed_test.pdf
content/news/test.md
content/news/test.png
content/news/test.pdf
content/_index.md
```

results in this page structure 
```
public/index.html
public/news
public/news/index.html
public/news/renamed_test.pdf
public/sitemap.xml
```

When using 0.122.0, the page structure is
```
public/index.html
public/news
public/news/index.html
public/news/renamed_test.pdf
public/news/test.png
public/news/test.pdf
public/sitemap.xml
```

### Minimal Example Project
Project with the example structure above can be found here: https://github.com/mwegnr/hugo-resource-copy

**Comment by jmooring** [comment]
@mwegnr Thanks for this. Note that resources even _beginning_ with the same name are excluded (e.g., news/test-foo.ext).

**Comment by jmooring** [comment]
#### content

```text
content/
└── s1/
    ├── foo.txt
    ├── p1-foo.txt
    ├── p1.md
    └── p1.txt
```

#### Expected (v0.122.0)

```text
public/
└── s1/
    ├── p1/
    │   └── index.html
    ├── foo.txt
    ├── index.html
    ├── p1-foo.txt
    └── p1.txt
```

#### Actual (v0.123.7)

```text
public/
└── s1/
    ├── p1/
    │   └── index.html
    ├── foo.txt
    └── index.html
```

#### Failing test case

<details>
<summary>test case</summary>

```go
func TestFoo(t *testing.T) {
	t.Parallel()

	files := `
-- hugo.toml --
disableKinds = ['home','rss','sitemap','taxonomy','term']
-- content/books/book-1.md --
---
title: Book 1
tags: [fiction]
---
-- content/s1/p1.md --
---
title: p1
---
-- content/s1/foo.txt --
foo.txt
-- content/s1/p1.txt --
p1.txt
-- content/s1/p1-foo.txt --
p1-foo.txt
-- layouts/_default/list.html --
{{.Title }}|
-- layouts/_default/single.html --
{{.Title }}|
	`

	b := hugolib.NewIntegrationTestBuilder(
		hugolib.IntegrationTestConfig{
			T:           t,
			TxtarString: files,
		},
	)
	b.Build()
	b.AssertFileExists("public/s1/index.html", true)
	b.AssertFileExists("public/s1/foo.txt", true)
	b.AssertFileExists("public/s1/p1.txt", true)     // failing test
	b.AssertFileExists("public/s1/p1-foo.txt", true) // failing test
	b.AssertFileExists("public/s1/p1/index.html", true)
}
```
</details>
<br>
