### ISSUE TITLE
I am not sure if it is bug or feature but languageCode in proper format (aa-BB) results with error. 

### ISSUE THREAD

**Issue by AlexeyInwerp** [gohugoio/hugo#12196]
hugo v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended darwin/arm64 BuildDate=2024-01-05T12:21:15Z VendorInfo=brew

this is quite annoying. i am not sure that is is that significant today, but i recall doing a seo to website 8 years ago and de-DE vs de-de DID matter for google search engine, just like it matters to Hugo compilator which yields error "Error: failed to create config from result: failed to decode "languages": config value "de-de" for defaultContentLanguage does not match any language definition". 
I think that people who use static html generators deserve to have direct access to such parameter in a raw format. for now i had to simply override it with my own shortcode but brief googling shown that this issue has many years of history.

**Comment by jmooring** [comment]
Please post your site configuration.

**Comment by AlexeyInwerp** [comment]
https://pastebin.com/ZfS83DMm

**Comment by jmooring** [comment]
The `defaultContentLanguage` determines the translation table, localization rules, and collation sequence. It has nothing to do with the locale displayed in templates (e.g., the `lang` attribute of the `html` element). Use [`.Site.Language.LanguageCode`](https://gohugo.io/methods/site/language/#methods) for the locale displayed in templates.

So your `defaultContentLanguage` might be `de-de`, but you can make your locale `de-DE`, `de_DE`, whatever.
