### ISSUE TITLE
Template lookup order no longer finds layouts/_default/author.terms.html

### ISSUE THREAD

**Issue by earthboundkid** [gohugoio/hugo#12193]
My /authors/ page no longer uses the layouts/_defaults/author.terms.html layout with Hugo 123. Renaming the file to authors.terms.html fixes the issue, but the actual taxonomy is defined as 

```toml
[taxonomies]
  author = "authors"
```

See #12174.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.7-312735366b20d64bd61bff8627f593749f86c964+extended darwin/arm64 BuildDate=2024-03-01T16:16:06Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by earthboundkid** [comment]
Interestingly, author.html works for individual authors, but authors.html does not.

**Comment by jmooring** [comment]
I'm probably missing a key piece of this, but I am unable to reproduce the problem.

#### Site config

```
[taxonomies]
author = 'authors'
```

#### Content

```
authors = ['John Smith','Robert Smith']
```

#### Layouts

```text
layouts/
└── _default/
    ├── author.terms.html <-- renders the authors taxonomy page
    ├── baseof.html
    ├── home.html
    ├── list.html
    └── single.html
```

#### Test site

```text
git clone --single-branch -b hugo-github-issue-12193 https://github.com/jmooring/hugo-testing hugo-github-issue-12193
cd hugo-github-issue-12193
rm -rf public && hugo && cat public/authors/index.html
```

**Comment by earthboundkid** [comment]
Make a content/authors/_index.md and the bug will reproduce.
