### ISSUE TITLE
Draft status ignored by content parser

### ISSUE THREAD

**Issue by MarkRosemaker** [gohugoio/hugo#12208]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.7-312735366b20d64bd61bff8627f593749f86c964+extended darwin/arm64 BuildDate=2024-03-01T16:16:06Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes.

It does not reproduce with the earlier version v0.122.0, meaning the error seems to have been introduced recently.

### Description

A piece of content in draft with an unknown shortcode or other malformed content is not ignored:

```markdown
---
title: "Foo"
draft: true
---

{{< bar >}}

```

Results in error:

```
Error: error building site: process: readAndProcessContent: "/content/foo/index.md:6:1": failed to extract shortcode: template for shortcode "bar" not found
```

Similar if the shortcode is unclosed or there is some other problem with the content:

```
Error: error building site: process: readAndProcessContent: "/content/foo/index.md:8:1": unclosed shortcode action
```

Hugo v0.122.0 builds the site without any issues, it just ignores the content of draft pages.

Note that fixing this bug will probably have a very beneficial impact on performance since there is no need to analyze the content of draft pages at all in the absence of the -D flag.

**Comment by jmooring** [comment]
Confirmed.

**Comment by bep** [comment]
We now parse the pages early for several reasons to read information that we need to place the page correctly into the content tree. You could argue that we could just read the intro/front matter, and then re-parse it later, but that would just be wasteful and I'm complicating the code for that.

Having a `draft` is a way to do copy-edits etc. on some content before publishing it when it's ready, but I don't see why it should be malformed.
