### ISSUE TITLE
`.AllTranslations` includes current language in List with 0.123.0 and above

### ISSUE THREAD

**Issue by adityatelange** [gohugoio/hugo#12207]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.123.7-312735366b20d64bd61bff8627f593749f86c964
</pre>

### Does this issue reproduce with the latest release?

Yes.

---

### Steps to reproduce:
1. Clone `exampleSite` branch of https://github.com/adityatelange/hugo-PaperMod
2. Remove Languages section so that we build only a single language https://github.com/adityatelange/hugo-PaperMod/blob/4bdc993b98cc82d1c59efca0774f85811b0bf213/config.yml#L22-L103
3. Build with hugo 0.122.x and 0.123.x
4. Observe that the `site.Home.AllTranslations` returns 0 pages on 0.122.x and before and returns 1 on 0.123.x

![2024-03-06_21-43](https://github.com/gohugoio/hugo/assets/21258296/5eafd201-17ec-4cb0-9d90-dba34adef587)
![2024-03-06_21-44](https://github.com/gohugoio/hugo/assets/21258296/8dbc9392-5207-4592-b021-c8a125926c30)

PaperMod reference: https://github.com/adityatelange/hugo-PaperMod/issues/1449

**Comment by jmooring** [comment]
I haven't dug into the details here, but as described this sounds like we fixed something that was broken in v0.122.0.

<https://gohugo.io/methods/page/alltranslations/>

> Returns all translations of the given page, including the current language.

<https://gohugo.io/methods/page/translations/>

> Returns all translations of the given page, excluding the current language.

**Comment by adityatelange** [comment]
> I haven't dug into the details here, but as described this sounds like we fixed something that was broken in v0.122.0.
> 
> https://gohugo.io/methods/page/alltranslations/
> 
> > Returns all translations of the given page, including the current language.
> 
> https://gohugo.io/methods/page/translations/
> 
> > Returns all translations of the given page, excluding the current language.

I briefly went through all release notes but couldn't find anything.

Thanks for the quick response, `.Translations` works for the particular use case. Closing.
