### ISSUE TITLE
internal modules: opengraph: breaking change in config between 0.120.4 and 0.123.7

### ISSUE THREAD

**Issue by gfelbing** [gohugoio/hugo#12210]
### What version of Hugo are you using (`hugo version`)?

- before update: `hugo v0.120.4+extended linux/amd64 BuildDate=unknown`
- after update: `hugo v0.123.7+extended linux/amd64 BuildDate=unknown`

### Does this issue reproduce with the latest release?

yes

### Description of the bug

After upgrading from 0.120.4 to 0.123.7 my build broke with:

```
ERROR render of "term" failed: "/home/georg/Workspaces/triptovantasia.com/src/blog/layouts/_default/list.html:3:3": execute of template failed: template: _default/list.html:3:3: executing "_default/list.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:6:15: executing "_internal/opengraph.html" at <partial "_funcs/get-page-images" .>: error calling partial: execute of template failed: template: partials/_funcs/get-page-images.html:18:21: executing "partials/_funcs/get-page-images.html" at <first 1 .>: error calling first: can't iterate over maps.Params
ERROR render of "404" failed: "/home/georg/Workspaces/triptovantasia.com/src/blog/layouts/404.html:3:3": execute of template failed: template: 404.html:3:3: executing "404.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:6:15: executing "_internal/opengraph.html" at <partial "_funcs/get-page-images" .>: error calling partial: execute of template failed: template: partials/_funcs/get-page-images.html:18:21: executing "partials/_funcs/get-page-images.html" at <first 1 .>: error calling first: can't iterate over maps.Params
ERROR render of "taxonomy" failed: "/home/georg/Workspaces/triptovantasia.com/src/blog/layouts/_default/list.html:3:3": execute of template failed: template: _default/list.html:3:3: executing "_default/list.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:6:15: executing "_internal/opengraph.html" at <partial "_funcs/get-page-images" .>: error calling partial: execute of template failed: template: partials/_funcs/get-page-images.html:18:21: executing "partials/_funcs/get-page-images.html" at <first 1 .>: error calling first: can't iterate over maps.Params
```

After googling the issue, I wasn't able to find an issue/forum entry with a similar problem.
I revisited the docs again in regards to the affected module: https://gohugo.io/templates/internal/#configure-open-graph

It turned out that the internal opengraph module nowadays uses the site config `params.images` and expects it to be a list of strings.
I used that field for something else (configured my image processing partials for responsive images).
So this [broke my workflow](https://xkcd.com/1172/).

I fixed it for my case by changing the `params.images` to something else, but I thought it might be useful for someone else facing the same issue.
Maybe it is worth noting it [in the breaking changes changelog](https://github.com/getkin/kin-openapi?tab=readme-ov-file#changelog-sub-v1-breaking-api-changes)?

**Comment by jmooring** [comment]
We made the change about three months ago: <https://github.com/gohugoio/hugo/pull/11688>. I'm sorry we broke your workflow, but this is the only reported occurrence.

Closing as this in not actionable.

**Comment by krischik** [comment]
> but this is the only reported occurrence.

Make that two reported occurrences.

**Comment by krischik** [comment]
> @krischik Comments on closed issues are often ignored.

That's OK. I got an answer in the [Forum](https://discourse.gohugo.io/t/error-calling-first-cant-iterate-over-maps-params/48907/2). Depending on how Google feels people might end up here so having follow on links might help.
