### ISSUE TITLE
Markdown references are not rendered in figure shortcode

### ISSUE THREAD

**Issue by tupaschoal** [gohugoio/hugo#12213]
#5276 introduced markdown rendering on caption and attr of figures, but it is not a complete markdown suport. Using this works:
```
{{< figure src="image.jpg" attr="Picture by [Someone](url.com)" >}}
```
But if you use markdown references, then it doesn't render the hyperlink properly
```
{{< figure src="image.jpg" attr="Picture by [Someone][0]" >}}

[0]: url.com
```

Not sure whether this is fixable or not, but I thought it was worth reporting

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.3-a75a659f6fc0cb3a52b2b2ba666a81f79a459376+extended windows/amd64 BuildDate=2024-02-23T17:09:20Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Didn't test, but it doesn't seem like it was fixed, by the release notes

**Comment by jmooring** [comment]
This isn't possible.

**Comment by tupaschoal** [comment]
I had that fear. Thanks for the quick answer and sorry for the hassle.
