### ISSUE TITLE
Hugo >0.123.5 failing to render most of website menu

### ISSUE THREAD

**Issue by danburd** [gohugoio/hugo#12218]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.8-5fed9c591b694f314e5939548e11cc3dcb79a79c+extended linux/amd64 BuildDate=2024-03-07T13:14:42Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

---

Hugo 0.123.6, 0.123.7, and 0.123.8 is failing to render most of the website menu in the [Book theme](https://github.com/alex-shpak/hugo-book) where 0.123.5 is doing so without issues. Specifically, it's unable to render the pages which exist in a hierarchy of sections - links to pages that are in the menu's root render successfully. I believe that the operative code to render the hierarchical menu is [here](https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/menu-filetree.html), between lines 10 and 25. Sorry that I'm not more knowledgeable about which functions in particular are not working.

[I've filed an issue with the theme](https://github.com/alex-shpak/hugo-book/issues/601), but I suspect the issue is with Hugo itself as I don't believe that breaking changes are purposefully introduced in bugfix releases.

**Comment by jmooring** [comment]
@danburd I am unable to reproduce this as described.

Using Hugo v0.123.8, here's what I did:

```text
git clone --recurse-submodules https://github.com/alex-shpak/hugo-book
cd hugo-book/exampleSite/
hugo server --themesDir ../..
```

Here's what I got:

![image](https://github.com/gohugoio/hugo/assets/335669/3cf4ea61-2800-4b14-905a-4381e80521cc)


Please provide a failing example.

**Comment by danburd** [comment]
**Update**: the issue is only with **headless** page bundles not showing up on the menu. (All of my page bundles were headless, which is why the issue seemed more broad at the time.) That's why the exampleSite worked and mine did not. I don't know if this is an issue with the theme or an issue with Hugo.

**Comment by jmooring** [comment]
I am not comfortable troubleshooting this without access to _your_ project repository. If you are making your bundles "headless" by adding `headless = true` to front matter, use [build options](https://gohugo.io/content-management/build-options/) instead. Again, without access to your site I am just guessing, but this sounds like we _fixed_ a bug rather than introduced a new one.

**Comment by danburd** [comment]
I suppose the correct way to do this is to replace ```headless: true``` with:

```
build:
  render: never
```
Thanks. Closing.
