### ISSUE TITLE
list interface problems

### ISSUE THREAD

**Issue by Dasuanhaohaochi** [gohugoio/hugo#12225]
My hugo project "C:\Users\77187\Desktop\test1\content\english\genes\" has generated the list interface, Can the list interface still be generated in the "C:\Users\77187\Desktop\test1\content\english\genes\Cucumis_sativus\" folder in the genes folder? I feel that it is theoretically possible, but my project has been unable to display the list interface of \Cucumis_sativus\ folder, but my \Cucumis_sativus\ folder to get markdown files were all rendered successfully...

**Comment by Dasuanhaohaochi** [comment]
"C:\Users\77187\Desktop\test1\content\english\genes\Cucumis_sativus\" Is a recursive subfolder under the genes folder

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
