### ISSUE TITLE
Mix RTL and LTR

### ISSUE THREAD

**Issue by be4zad** [gohugoio/hugo#12226]
How to use both LTR and RTL languages in one content? It seems hugo doesn't support it.

However we can fix it manually by this tag in most markdown viewers:

```
<div dir="rtl">
سلام
</dir>
```

But hugo removes it:
```
<!-- raw HTML omitted -->
```

I have not much experience in css but are there any reasons why not hugo doesn't use auto direction?

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
