### ISSUE TITLE
Page resource not published when the extension name is `html`

### ISSUE THREAD

**Issue by masakichi** [gohugoio/hugo#12231]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.8+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes, you can refer to my blog repo for example https://github.com/masakichi/nikki/blob/main/content/posts/%E5%8D%9A%E5%AE%A2%E6%9B%B4%E6%96%B0%EF%BC%9A%E5%A2%9E%E5%8A%A0%E5%88%86%E4%BA%AB%E6%8C%89%E9%92%AE/demo.html this `demo.html` is not published after running `hugo`.

**Edit: v0.122.0 works fine.**

**Comment by jmooring** [comment]
This was an intentional breaking change in v0.123.0. See explanation:

<https://discourse.gohugo.io/t/companion-page-bundle-html-files-not-being-copied-to-subfolder-of-output-directory-anymore/48502/2>
