### ISSUE TITLE
[Bug]: `figure` shortcode is not working for images stored in the same folder as in the markdown blog post for non default languages

### ISSUE THREAD

**Issue by CXwudi** [gohugoio/hugo#12244]
### What version of Hugo are you using (`hugo version`)?

Hugo v0.123.8 extended version

### Does this issue reproduce with the latest release?

I have a folder structure is as following:

```
.
└── content
    └── posts
        └── my-first-post
            ├── img.png
            ├── index.en.md
            └── index.zh-cn.md
```

And my blog has set the default language to English.

Using the `figure` shortcode, I can see that `img.png` is properly showing in `index.en.md` but not `index.zh-cn.md`

The shorcode I used in both markdown file is simply just `{{< figure src="img.png" caption="xxx">}}`.

Downgrading Hugo to v0.121.2 works.

**Comment by CXwudi** [comment]
A reproducible sample can be my repo at https://github.com/CXwudi/personal-blog-source, change the HUGO_VERSION in `.devcontainer\.env` to 0.123.8, and run `./test-local.sh` in the root directory to bring up my blog. Checkout the Chinese version of the first post and you can see 
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/dc0b73e5-8005-4bea-8e5e-e9408bca52db)

**Comment by jmooring** [comment]
@CXwudi Thanks for creating this issue. This will be resolved with https://github.com/gohugoio/hugo/issues/12245.

In the interim, assuming that you are using the embedded figure shortcode described [here](https://gohugo.io/content-management/shortcodes/#figure), create your own to override it:

<details>
<summary>layouts/shortcodes/figure.html</summary>

```text
<figure{{ with .Get "class" }} class="{{ . }}"{{ end }}>
  {{- if .Get "link" -}}
    <a href="{{ .Get "link" }}"{{ with .Get "target" }} target="{{ . }}"{{ end }}{{ with .Get "rel" }} rel="{{ . }}"{{ end }}>
  {{- end -}}

  {{- $u := urls.Parse (.Get "src") -}}
  {{- $src := $u.String -}}
  {{- if not $u.IsAbs -}}
    {{- with or (.Page.Resources.Get $u.Path) (resources.Get $u.Path) -}}
      {{- $src = .RelPermalink -}}
    {{- end -}}
  {{- end -}}

  <img src="{{ $src }}"
    {{- if or (.Get "alt") (.Get "caption") }}
    alt="{{ with .Get "alt" }}{{ . }}{{ else }}{{ .Get "caption" | markdownify| plainify }}{{ end }}"
    {{- end -}}
    {{- with .Get "width" }} width="{{ . }}"{{ end -}}
    {{- with .Get "height" }} height="{{ . }}"{{ end -}}
    {{- with .Get "loading" }} loading="{{ . }}"{{ end -}}
  /><!-- Closing img tag -->
  {{- if .Get "link" }}</a>{{ end -}}
  {{- if or (or (.Get "title") (.Get "caption")) (.Get "attr") -}}
    <figcaption>
      {{ with (.Get "title") -}}
          <h4>{{ . }}</h4>
      {{- end -}}
      {{- if or (.Get "caption") (.Get "attr") -}}<p>
        {{- .Get "caption" | markdownify -}}
        {{- with .Get "attrlink" }}
          <a href="{{ . }}">
        {{- end -}}
        {{- .Get "attr" | markdownify -}}
        {{- if .Get "attrlink" }}</a>{{ end }}</p>
      {{- end }}
    </figcaption>
  {{- end }}
</figure>
```
</details>
<br>
