### ISSUE TITLE
Special character in URL has new behaviour since 0.123.0

### ISSUE THREAD

**Issue by jmichelgarcia** [gohugoio/hugo#12241]
### What version of Hugo are you using (`hugo version`)?
`latest (123.8)`

### When did the problem appear?
`0.123.0`

### Problem
I am using Docsy and I have a file:
- `content/en/docs/Administration/On-Premises Deployments/Architecture & System Requirements/_index.md`

FontMatter wise:
```
---
linkTitle: "Architecture & System Requirements"
title: "Architecture & System Requirements"
weight: "10"
aliases:
  - /en/architecture---system-requirements.html
description: "xxx"
---
```

Until `0.122.0` that page was being rendered with this url:
- `https://[domain]/en/docs/administration/on-premises-deployments/architecture-system-requirements/`

After upgrading to `0.123.0`, it is now being rendered as:
- `https://[domain]/en/docs/administration/on-premises-deployments/architecture--system-requirements/`

notice the `--` instead of `-`.

Is this expected?

I'm going through the release notes and code, to see if I missed anything.
Many thanks!

**Comment by jmooring** [comment]
Reported here as well:
<https://discourse.gohugo.io/t/hugo-v0-123-seems-to-anchorize-terms-in-their-urls-rather-than-urlize-them/48583>

I know we made a "hyphen retention" change to address another issue (I think to retain three consecutive hyphens), but I'm not sure if the above is intentional.

**Comment by jmichelgarcia** [comment]
@bep, is the above here to stay (and therefore I should change my aliases, links and so on), or if this is an unexpected behaviour? Thanks.

**Comment by jmichelgarcia** [comment]
I believe this is the culprit (which I'm assuming is an intentional decision)
https://github.com/gohugoio/hugo/blob/9ca1de09dd397a84dd13e528d8d09930d913d885/common/paths/path.go#L297

**Comment by jmooring** [comment]
Of a **very small** sampling (n=192) of sites in the wild running v0.100.0 or later, 23% are already running v0.123.0 or later, so... even if this wasn't intentional, changing it again may be unwise.

**Comment by jmichelgarcia** [comment]
If it wasn't intentional, I was hoping hugo would offer a way to opt-out (and preserve old behaviour).

**Comment by jmichelgarcia** [comment]
@jmooring looking at it again, the current implementation doesn't make much sense though
it's basically rendering

- `Architecture & System Requirements` as `architecture--system-requirements`
- `Installer (Kubernetes - OpenShift)` as `installer-kubernetes---openshift`

Before I embark on a fixing journey, I wanted clarity on whether this is intentional or not.

**Comment by bep** [comment]
This is mentioned in the list of breaking changes (near the top) that was also in the release notes for v0.123.0:

https://github.com/gohugoio/hugo/issues/11455

https://github.com/gohugoio/hugo/issues/10104

**Comment by jmichelgarcia** [comment]
Thanks @bep and @jmooring 

I think I'm an outlier because we have lots of pages with various special characters and spaces in them, which I will now correct.

I am however still puzzled on why the new behaviour is not consistent though across different characters.
I did a quick check with Docsy and found the following:

| filepath | url |
|--------|----|
| `content/en/docs/Concepts & Tutorials/_index.md` | `/docs/concepts--tutorials/` |
| `content/en/docs/Concepts - Tutorials/_index.md` | `/docs/concepts---tutorials/` | 
| `content/en/docs/Concepts-Tutorials/_index.md` | `/docs/concepts-tutorials/` |
| `content/en/docs/Concepts (Tutorials)/_index.md` | `/docs/concepts-tutorials/` |
| `content/en/docs/Concepts (Tutorials/_index.md` | `/docs/concepts-tutorials/` |

Cheers.
