### ISSUE TITLE
Unable to intersect two term page collections

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12254]
Reference: <https://discourse.gohugo.io/t/intersect-2-term-lists-broken-in-0-123-0-onwards/48765/>

I'd give this a low priority because (a) the use case is uncommon, and (b) there's a cleaner construct (see [this comment](https://discourse.gohugo.io/t/intersect-2-term-lists-broken-in-0-123-0-onwards/48765/2)) that works fine with v0.123.0 and later.

The test case below fails with v0.123.0 and later.

```go
func TestFoo(t *testing.T) {
	t.Parallel()

	files := `
-- hugo.toml --
capitalizeListTitles = false
disableKinds = ['rss','sitemap']
-- content/p1.md --
---
title: p1
categories: [cat-a]
tags: ['tag-b','tag-a','tag-c']
---
-- content/p2.md --
---
title: p2
categories: [cat-a]
tags: ['tag-b','tag-a']
---
-- content/p3.md --
---
title: p3
categories: [cat-a]
tags: ['tag-b']
---
-- layouts/_default/term.html --
{{ $s := slice }}
{{ range site.Taxonomies.tags.ByCount }}
  {{ if intersect $.Pages .Pages }}
    {{ $s = $s | append . }}
  {{ end }}
{{ end }}
{{ $s = uniq $s }}

<ul>
  {{ range $s }}
    <li><a href="{{ .Page.RelPermalink }}">{{ .Page.Title }}</a> ({{ .Count }})</li>
  {{ end }}
</ul>
`
	b := Test(t, files)

	b.AssertFileContent("public/categories/cat-a/index.html",
		`<li><a href="/tags/tag-b/">tag-b</a> (3)</li>`,
		`<li><a href="/tags/tag-a/">tag-a</a> (2)</li>`,
		`<li><a href="/tags/tag-c/">tag-c</a> (1)</li>`,
	)
}
```

**Comment by bep** [comment]
I would be surprised if this was a general "page collections" issue. I see what's happening on the technical side here (we create these terms on demand now so you end up with different objects). This is fixable, of course.

**Comment by jmooring** [comment]
Yeah, I wasn't quite sure how to zero-in on the description in 15 words or less.

**Comment by josineto** [comment]
Thank you, @jmooring and @bep !
