### ISSUE TITLE
Wrong .Parent with pages with overlapping names (e.g. sdk and sdk_exporters)

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12263]
The issue title is a big vague for now.

Reference: <https://discourse.gohugo.io/t/subpage-missing-from-sections-page-list-when-using-0-123-8/48789>

Minimal reproducible example:

```text
git clone --single-branch -b hugo-forum-topic-48789 https://github.com/jmooring/hugo-testing hugo-forum-topic-48789
cd hugo-forum-topic-48789
npm ci
hugo server
```

Then visit <http://localhost:1313/docs/logs/> to see the problem.

You will see "Stdout" in the menu on the left, but that page is not shown in the content listing with v0.123.0 or later.

**Comment by bep** [comment]
I have a fix on its way, but I would recommend the theme author(s) to somehow simplify this construct:

```handlebars
{{ $parent := .Page -}}
    {{ $pages := (where .Site.Pages "Section" .Section).ByWeight -}}
    {{ $pages = (where $pages "Type" "!=" "search") }}
    {{ $pages = (where $pages ".Params.hide_summary" "!=" true) -}}
    {{ $pages = (where $pages ".Parent" "!=" nil) -}}
    {{ if and $parent.File .Parent .Parent.File -}}
        {{ $pages = (where $pages "Parent.File.UniqueID" "==" $parent.File.UniqueID) -}}
    {{ end -}}
```
