### ISSUE TITLE
mounting multilingual content assets breaks bundled resource pages (*.md) live reload

### ISSUE THREAD

**Issue by rcb98** [gohugoio/hugo#12273]
Here's an example [repo](https://github.com/rcb98/test-reload/tree/test/reload-bug) reproducing the issue.

Basically, when the config of the site mounts the `content/{lang_code}` into assets, if you navigate to `/posts/my-first-post` any changes applied to the content markdown file don't refresh until re-running manually. You can see the window refreshing, but the content itself doesn't.

### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo v0.123.8-5fed9c591b694f314e5939548e11cc3dcb79a79c+extended darwin/amd64 BuildDate=2024-03-07T13:14:42Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?
This started to happen with `v.0.123.0`, and in any release before that it worked just fine.

**Comment by jmooring** [comment]
I advise against using this setup. 

For assets related to a page, use page bundles:

```
content/
├── en/
│   ├── posts/
│   │   └── my-first-post/
│   │       ├── index.md
│   │       └── turtle.jpg
│   └── _index.md
└── es/
    ├── posts/
    │   └── my-first-post/
    │       └── index.md
    └── _index.md
```

Otherwise use global assets:

```
assets/
└── images/
    └── kitten.jpg
```

Remove all of your mounts, and change your render hook to:

```text
{{ $image := or (.Page.Resources.Get .Destination) (resources.Get .Destination) }}
{{ if not $image }}
{{ errorf "Image not found: %q" .Destination }}
{{ end }}
<span class="figure">
    <img src="{{ ($image | fingerprint).RelPermalink }}" alt="{{ .Text }}" width="{{ $image.Width }}"
        height="{{ $image.Height }}" style="height: 200px; width: auto" />
    {{ if .Title }}
    <span class="caption">{{ .Title }}</span>
    {{ end }}
</span>
```

Here's your site, reworked slightly:

```text
git clone --single-branch -b hugo-github-issue-12273 https://github.com/jmooring/hugo-testing hugo-github-issue-12273
cd hugo-github-issue-12273
hugo server
```

**Comment by rcb98** [comment]
Thanks for getting back so quickly! I had to make some modifications to the render image hook so it worked in a larger project, but it's up and running now.

Thanks for the help! Closing this now.
