### ISSUE TITLE
uglyURLs with relativeURLs breaks image paths

### ISSUE THREAD

**Issue by zflat** [gohugoio/hugo#12290]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.124.1-db083b05f16c945fec04f745f0ca8640560cf1ec+extended linux/amd64 BuildDate=2024-03-20T11:40:10Z VendorInfo=snap:0.124.1
</pre>

### Does this issue reproduce with the latest release?

Yes

### Description of the issue

I am seeing an issue with an incorrectly resolved image URL. I created a new template and the sample "post-3" has an image with it called "bryce-canyon.jpg". With the following settings, the image url is wrong:

<pre>
baseURL = 'https://example.org/'
relativeURLs = "true"
uglyURLs = "true"
</pre>

If I comment out "uglyURLs" then the link to the image works.

I think the issue is that with "uglyURLs" disabled, the HTML is generated at:

<pre>
public/posts
├── index.html
├── index.xml
├── post-1
│   └── index.html
├── post-2
│   └── index.html
└── post-3
    ├── bryce-canyon.jpg
    └── index.html

</pre>

And with "uglyURLs" enabled, the files are generated at:

<pre>
public/posts
├── index.xml
├── post-1.html
├── post-2.html
├── post-3
│   └── bryce-canyon.jpg
└── post-3.html
</pre>

So the relative location between the HTML and the image asset changes when "uglyURLs' changes and the paths used in the HTML need to reflect the difference.

**Comment by jmooring** [comment]
This is expected. Markdown link and image destinations are, by default, always rendered per the CommonMark specification regardless of context. And by enabling `uglyURLs` you have altered the context.

Add this to your site configuration to enable the embedded link and image render hooks:

```
[markup.goldmark.renderHooks.image]
enableDefault = true
[markup.goldmark.renderHooks.link]
enableDefault = true
```

<https://gohugo.io/render-hooks/links/#default>
<https://gohugo.io/render-hooks/images/#default>

These override the rendering of Markdown link and image destinations, taking into account various settings, including `uglyURLs`.

**Comment by zflat** [comment]
Thanks! Those settings fix the issue for me.
