### ISSUE TITLE
Accumulation of org keywords do not work correctly for taxonomies when there's only one term

### ISSUE THREAD

**Issue by augustfengd** [gohugoio/hugo#12319]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.124.1-db083b05f16c945fec04f745f0ca8640560cf1ec linux/amd64 BuildDate=2024-03-20T11:40:10Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

### Issue description

The new accumulation mechanism of org keywords from https://github.com/gohugoio/hugo/issues/11743 only works when many taxonomy terms are supplied.

If there aren't multiple `#+tags: ...` then the taxonomy terms are not marshalled into a slice and `{{ range .Params.tags }} {{ end }}` fails.

```javascript
// <pre>{{ jsonify (dict "indent" "  ") .Params }}</pre>
{
  "draft": false,
  "iscjklanguage": false,
  "tags": "a",
  "title": "foobar"
}
```

<pre>
$ hugo
Start building sites … 
hugo v0.124.1-db083b05f16c945fec04f745f0ca8640560cf1ec linux/amd64 BuildDate=2024-03-20T11:40:10Z VendorInfo=gohugoio

Total in 8 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/home/augustfengd/learn/hugo/layouts/_default/single.html:4:24": execute of template failed: template: _default/single.html:4:24: executing "_default/single.html" at <.Params.tags>: range can't iterate over a
</pre>

I should've been more thorough with my testing. Can we revert https://github.com/gohugoio/hugo/pull/11741 and stick with the prior `[]` syntax?

**Comment by jmooring** [comment]
@augustfengd I am unable to reproduce the problem as described. Example:

```text
git clone --single-branch -b hugo-github-issue-12319 https://github.com/jmooring/hugo-testing hugo-github-issue-12319
cd hugo-github-issue-12319
hugo server
```

**Comment by jmooring** [comment]
Nevermind. I see the problem now.

**Comment by jmooring** [comment]
@augustfengd I don't think this is a problem. The same thing happens when assigning a scalar value using other front matter formats (e.g., TOML):

```toml
+++
title = 'Posts'
tags = 'red'
+++
```

Yes, with Org Mode front matter you could previously assign a scalar because we checked the keys for "tags", "categories", and "aliases", and decoded to a slice in those cases, but we've been warning users for years to move to the `#+KEY[]` syntax. 

Unless I'm missing something, we're doing what we should be doing.

**Comment by augustfengd** [comment]
@jmooring, ah yeah you make a good point with the TOML example. 

Yes, so we can see the org front matter as allowing us to convey an array when we duplicate the keyword.

Thanks for the perspective. :)
