### ISSUE TITLE
Render the render hooks when calling .Page.RenderShortcodes

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12356]
I have no idea if this is possible.

#### Scenario

1. I have an "include" shortcode [as described in the documentation](https://gohugo.io/methods/page/rendershortcodes/).
2. I invoke the shortcode using the `{{% .. %}}` notation so that the headings in the included file appear in the TOC.
3. The shortcode calls `.Page.RenderShortcodes`.
4. The page I'm including is a leaf bundle that contains a markdown image that references a page resource. For example: `![alt](a.jpg)`.
5. I enabled the embedded image render hook so that the `src` attribute of the `img` element will be relative to the site root.

#### Problem

The image render hook is evaluated relative to the _including_ page, not relative to the _included_ page, resulting in a broken image.

The workaround is to call `.Content` instead of `.RenderShortcodes`, but then the headings of the included page do not contribute to the including page's TOC.

#### Minimal example

```text
git clone --single-branch -b hugo-github-issue-12356 https://github.com/jmooring/hugo-testing hugo-github-issue-12356
cd hugo-github-issue-12356
hugo server
```

#### Notes

If this were possible, I think the site author would need to set `markup.goldmark.renderer.unsafe` to `true`, which isn't great, but it's better than a broken image.

**Comment by bep** [comment]
I'm not sure about the details in the above, but I strongly suspect that this would be solved if 

* For page `$p`
*  For nested shortcodes and renderhooks in `$p.RenderShortcodes`, `.Page` would return `$p`.

Since we now have a `context.Context` passed around everywhere, the above should be possible, but would it be a breaking change? Many would probably consider it a bug fix. Are there other places we would need to apply this?

**Comment by bep** [comment]
I have thought a little about this, and to render the render hooks without rendering the reset of the Markdown would be hard/unpractical.

But I agree that we should fix this. What we could probably do, and I'm thinking out loud here, is for shortcodes rendered with `{{% .. %}}`, include some context in the rendered output as a [SGML Processing Instruction](https://en.wikipedia.org/wiki/Processing_Instruction), e.g.:

```markdown
<?hugo-context path="/posts/page1"?>
## Hello World

Lorem ipsum.

<?hugo-context path="/posts/page2"?>
## Included from page 2
```

And then consider those when considering what to pass as `.Page` to render hooks and shortcodes (or maybe add another method so you can potentially have 2 page contexts).

**Comment by bep** [comment]
I think I have a better way to fix this. Will try to demo it in a PR.
