### ISSUE TITLE
For Hugo server command, always add server address at end of output for convenience

### ISSUE THREAD

**Issue by frjo** [gohugoio/hugo#12359]
When you start the Hugo server you see this output in the terminal:

```
Environment: "development"
Serving pages from disk
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1) 
Press Ctrl+C to stop
```

Command clicking `http://localhost:1313/` (on macOS) open the address in a new browser tab.

You then work on the site and the terminal will show a lot of output. The server address is soon not visible anymore (unless you scroll of course).

I commonly work on multiple sites and keep the servers running for days, if not weeks.

I also work a lot with Django and its server adds the server address after each output. This way you always have quick access to it at the bottom of the terminal window. I find this very convenient.

Would it be possible to add this feature to Hugo as well?

**Comment by bep** [comment]
I guess this makes sense. I suggest we add it before the "Total in ..." so it becomes:

```
Change detected, rebuilding site (#1).
2024-04-11 09:12:35.997 +0200
Source changed /documentation.md
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Total in 30 ms
```

**Comment by jmooring** [comment]
Do we do the same thing with a multihost site?

```text
[languages.en]
baseURL = 'https://en.example.org/'
weight = 1

[languages.de]
baseURL = 'https://de.example.org/'
weight = 2

[languages.fr]
baseURL = 'https://fr.example.org/'
weight = 3

[languages.es]
baseURL = 'https://es.example.org/'
weight = 4
```

```
Change detected, rebuilding site (#1).
2024-04-11 09:12:35.997 +0200
Source changed /documentation.md
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1) en
Web Server is available at http://localhost:1314/ (bind address 127.0.0.1) de
Web Server is available at http://localhost:1315/ (bind address 127.0.0.1) fr
Web Server is available at http://localhost:1316/ (bind address 127.0.0.1) es
Total in 30 ms
```
