### ISSUE TITLE
server: List page doesn't update after creating content

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12362]
Reference: <https://discourse.gohugo.io/t/hugo-server-d-doesnt-show-new-posts-consistently/49266>

This worked as expected < v0.123.0.

####  archetypes/default.md

```text
---
title: {{ replace .File.ContentBaseName "-" " " }}
draft: false
---
```

#### layouts/_default/list.html

```
{{ range .Pages }}{{ .Title }}|{{ end }}
```
#### content

```text
content/
└── p1.md
```

#### actions

Run `hugo server` and look at the home page. You'll see `p1|` as expected.

In a new terminal, while the server is running, create a new page:

```text
hugo new p2.md
```

#### expected

The home page should display `p1|p2|`

#### actual 

The home displays `p1|` (no change)

#### test case

This isn't very helpful because it passes, but perhaps it will be useful as the basis for a different test.

<details>
<summary>integration test</summary>

```go
func TestFoo(t *testing.T) {
	t.Parallel()

	files := `
-- hugo.toml --
disableKinds = ['rss','section','sitemap','taxonomy','term']
-- layouts/_default/list.html --
{{ range .Pages }}{{ .Title }}|{{ end }}
-- layouts/_default/single.html --
{{ .Title }}
-- content/p1.md --
---
title: p1
---
`

	b := hugolib.Test(t, files, hugolib.TestOptRunning())
	b.AssertFileContent("public/index.html", "p1|")

	b.AddFiles("content/p2.md", "---\ntitle: p2\n---").Build()
	b.AssertFileContent("public/index.html", "p1|p2|") // this test passes, which doesn't match reality
}
```
</details>
<br>

**Comment by bep** [comment]
On what OS does this fail? Windows?

**Comment by jmooring** [comment]
OP: hugo v0.124.1+extended linux/amd64 BuildDate=unknown
Me: hugo v0.124.1-db083b05f16c945fec04f745f0ca8640560cf1ec+extended linux/amd64

**Comment by bep** [comment]
I have tested this again and cannot reproduce this on MacOS. I may eventually spin up a Linux VM and test this, but that may take some time.

**Comment by bep** [comment]
I have a test repo that log the filesystem events for the different OSes. Looking at it now I see for created regular files:

MacOS:

```
CREATE        "/var/folders/h1/8hndypj13nsbj5pn4xsnv1tm0000gn/T/TestListEvents885546749/001/regularfile.txt"
```

Ubuntu:

```
CREATE        "/tmp/TestListEvents3296403036/001/regularfile.txt"
WRITE         "/tmp/TestListEvents3296403036/001/regularfile.txt"
```

In the `hugolib.TestRunning` we simulate these events (they doesn't get triggered with the mem fs, also they're very hard to get stable in CI).

But the above can explain what's seen above. I'll take another look.
