### ISSUE TITLE
Can't pass color of type images.ColorHex to images.Padding

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12376]
Found while testing https://github.com/gohugoio/hugo/pull/12374.

This may also affect images.Dither, where we should be able to pass it a slice of  images.ColorHex.

**Comment by bep** [comment]
#12374 is not merged ...

**Comment by jmooring** [comment]
I was assuming it would be because it works great.

**Comment by jmooring** [comment]
Will re-open if necessary.

**Comment by bep** [comment]
I have added note about this in the PR ... I don't mind bugs, but I'm not a big fan of bugs on future code ...
