### ISSUE TITLE
YouTube shortcode for private videos causes error and failure to build site

### ISSUE THREAD

**Issue by max-allan-cgr** [gohugoio/hugo#12383]
```
ERROR The "youtube" shortcode was unable to get remote resource "https://www.youtube.com/oembed?format=json&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMxxxxxx18". failed to fetch remote resource: Forbidden. See "/workspaces/wiki/content/docs/document.md:48:1"
```
I've xxx'ed the actual URL because it is a private video. So Hugo will not be allowed to view it while building the site. Which is probably why it gets a 403. 

In previous versions, I'm assuming you were ignoring the error and the site builds and views perfectly OK. _I_ can view the video, because _I_ am logged in with my Google account.

I suspect this is going to cause a lot of people (with private videos) some pain.

NB this issue is similar to but NOT a duplicate of #12380 . Not a duplicate because they show a screenshot of a video failing to load in 0.124. On our site, videos load perfectly well with 0.124

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.125.0+extended linux/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes, this IS the latest release!

**Comment by xnox** [comment]
> > I suspect this is going to cause a lot of people (with private videos) some pain.
> 
> Having a published site with private videos doesn't sound like a common use case.

It's an internal authenticated wiki site.

**Comment by andgar2010** [comment]
> ```
> ERROR The "youtube" shortcode was unable to get remote resource "https://www.youtube.com/oembed?format=json&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMxxxxxx18". failed to fetch remote resource: Forbidden. See "/workspaces/wiki/content/docs/document.md:48:1"
> ```
> 
> I've xxx'ed the actual URL because it is a private video. So Hugo will not be allowed to view it while building the site. Which is probably why it gets a 403.
> 
> In previous versions, I'm assuming you were ignoring the error and the site builds and views perfectly OK. _I_ can view the video, because _I_ am logged in with my Google account.
> 
> I suspect this is going to cause a lot of people (with private videos) some pain.
> 
> NB this issue is similar to but NOT a duplicate of #12380 . Not a duplicate because they show a screenshot of a video failing to load in 0.124. On our site, videos load perfectly well with 0.124
> 
> ### What version of Hugo are you using (`hugo version`)?
> $ hugo version
> hugo v0.125.0+extended linux/arm64 BuildDate=unknown
> ### Does this issue reproduce with the latest release?
> Yes, this IS the latest release!

Same error

reproduce step:
```md
{{< youtube nEXXXXXXcyQ >}}
```
// YT link private, but work in Hugo version 0.124.1

```
$  hugo serve
Watching for changes in /Documents/homepage/{assets,content,data,i18n,layouts,package.json,static,themes}
Watching for config changes in /Documents/homepage/config.toml, /Documents//homepage/themes/hugo-coder/config.toml
Start building sites … 
hugo v0.125.0-a32400b5f4e704daf7de19f44584baf77a4501ab+extended darwin/arm64 BuildDate=2024-04-16T15:04:41Z VendorInfo=brew

ERROR The "youtube" shortcode was unable to get remote resource "https://www.youtube.com/oembed?format=json&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3AnEXXXXXXcyQ". failed to fetch remote resource: Unauthorized. See "/Documents/homepage/content/posts/{{url-post}}.es.md:49:1"
Built in 310 ms
Error: error building site: logged 1 error(s)
```
