### ISSUE TITLE
Unable to build hugo extended on macos

### ISSUE THREAD

**Issue by popey** [gohugoio/hugo#12382]
### What version of Hugo are you using (`hugo version`)?

I'm trying to build from source, so this question does not apply.

### Does this issue reproduce with the latest release?

I'm trying to build from source, so this question does not apply.

----

I did search for issues with this error, and on the forum. 🙏 

I got a new M3 mac running macOS 14.4. I installed `gcc` and `go` via homebrew.

```
alan@Alans-MacBook-Pro hugo % gcc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
alan@Alans-MacBook-Pro hugo % go version
go version go1.22.2 darwin/arm64
```

I cloned this repo, and ran the following command as per the README.md

`CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest`

It builds a load of super stuff then fails.

```
alan@Alans-MacBook-Pro hugo % CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest
...
...
go: downloading github.com/invopop/yaml v0.2.0
go: downloading github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826
go: downloading github.com/perimeterx/marshmallow v1.1.5
go: downloading github.com/go-openapi/swag v0.22.8
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/josharian/intern v1.0.0
# github.com/gohugoio/hugo
ld: warning: ignoring duplicate libraries: '-lc++', '-lm'
```

**Comment by agriyakhetarpal** [comment]
I think you're using the Clang compiler from the Xcode toolchain and not from Homebrew (most likely that Homebrew's GCC is not prepended to your PATH and there doesn't get picked), but that shouldn't stop you from being able to compile. I'm able to do it for M-series macOS machines in CI with the [most recent release](https://github.com/agriyakhetarpal/hugo-python-distributions/actions/runs/8709664290/job/23889859110) – I think that this warning can be ignored.

**Comment by popey** [comment]
Thanks for the prompt responses. Much appreciated.

@cmahnke  I see no binary created, so I think it's a warning from a tool that dies, and I don't end up with a binary, probably.

@agriyakhetarpal I think you're on to something here.

```zsh
alan@Alans-MacBook-Pro hugo % clang --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
alan@Alans-MacBook-Pro hugo % gcc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
alan@Alans-MacBook-Pro hugo % echo $PATH
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
alan@Alans-MacBook-Pro hugo % ls -l /opt/homebrew/bin/gcc*
lrwxr-xr-x  1 alan  admin  31 16 Apr 22:09 /opt/homebrew/bin/gcc-13 -> ../Cellar/gcc/13.2.0/bin/gcc-13
lrwxr-xr-x  1 alan  admin  34 16 Apr 22:09 /opt/homebrew/bin/gcc-ar-13 -> ../Cellar/gcc/13.2.0/bin/gcc-ar-13
lrwxr-xr-x  1 alan  admin  34 16 Apr 22:09 /opt/homebrew/bin/gcc-nm-13 -> ../Cellar/gcc/13.2.0/bin/gcc-nm-13
lrwxr-xr-x  1 alan  admin  38 16 Apr 22:09 /opt/homebrew/bin/gcc-ranlib-13 -> ../Cellar/gcc/13.2.0/bin/gcc-ranlib-13
```

I tried bodging it in an environment variable but that wasn't enough, although the error is similar, but not the same. Maybe more environment bodging required for the linker?

```zsh
alan@Alans-MacBook-Pro hugo % CXX=/opt/homebrew/bin/g++-13 CC=/opt/homebrew/bin/gcc-13 CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest
# github.com/gohugoio/hugo
ld: warning: ignoring duplicate libraries: '-lstdc++'
```

I gave up on that after finding a suggestion to bodge it a bit with a symlink in `/usr/local/bin` which is further up the `PATH` than xcode

```zsh
alan@Alans-MacBook-Pro bin % sudo ln -s /opt/homebrew/bin/gcc-13 /usr/local/bin/gcc
alan@Alans-MacBook-Pro bin % sudo ln -s /opt/homebrew/bin/g++-13 /usr/local/bin/g++
```

Restarted the shell..

```zsh
alan@Alans-MacBook-Pro hugo % which gcc
/usr/local/bin/gcc
alan@Alans-MacBook-Pro hugo % which g++
/usr/local/bin/g++
alan@Alans-MacBook-Pro hugo % CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest

# github.com/gohugoio/hugo
ld: warning: ignoring duplicate libraries: '-lc++', '-lm'
```

Continued sadness. This isn't a bug in Hugo, clearly, but a support ticket. Should I move this to the forum or something?

**Comment by agriyakhetarpal** [comment]
I think so, yes. It would also be worth cleaning your Go caches with the `go clean` command or by manually deleting the `go-build` folder, which should be present at `Users/alan/Library/Caches/go-build/`, plus any other ancillary folders to see if that resolves the issue. Any compliant C compiler should work in essence, whether it comes from Xcode or so from Homebrew.

**Comment by popey** [comment]
That did i! Thanks so much, and sorry for the noise. 🙏 
I hope this is useful for someone else who searches, anyway.

```
alan@Alans-MacBook-Pro hugo % ./hugo version          
hugo v0.126.0-DEV-8c14d1edc30abb43e1847cba9aa1802fa716f4f8+extended darwin/arm64 BuildDate=2024-04-16T15:21:02Z
```
