### ISSUE TITLE
server: Browser does not refresh after updating Sass file

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12395]
This worked fine in v0.122.0, and fails with v0.123.0 and later.

```text
git clone --single-branch -b hugo-forum-topic-49365 https://github.com/jmooring/hugo-testing hugo-forum-topic-49365
cd hugo-forum-topic-49365
hugo server
```

While the server is running, edit themes/sasstest_theme/assets/scss/index.scss, changing h1.color from red to blue. The site title should change from red to blue.

Reference: <https://discourse.gohugo.io/t/changes-to-sass-stylesheets-are-not-reflected-in-the-browser-via-live-reload/49365>

**Comment by bep** [comment]
1. Tip: Most "browser doesn't refresh after 0.123" issues can be worked around with https://gohugo.io/getting-started/configuration/#configure-cache-busters -- the above should work out of the box, though.
2. Any browser doesn't refresh issue needs information about what OS this is tested/fails on.
