### ISSUE TITLE
Non-section pages added to main menu when using sectionPagesMenu

### ISSUE THREAD

**Issue by MTecknology** [gohugoio/hugo#12399]
### What version of Hugo are you using (`hugo version`)?

First found in hugo_0.123.0_linux-amd64.tar.gz

### Does this issue reproduce with the latest release?

Yes.

Starting in v0.123.0, some warnings were printed:
```
WARN  "aamod/exampleSite/content/contact.md:1:1": duplicate menu entry with identifier "Sample Content" in menu "main"
WARN  "aamod/exampleSite/content/features.md:1:1": duplicate menu entry with identifier "Other Features" in menu "main"
```

Both pages are rendered using their respective titles/names/paths/weights, however there is an additional entry created at the end of the menu which duplicates the contact.md page. In the most recent release, this warning is removed, but the duplicate entry is still created.

The source I am working on is https://github.com/recoverysource/aamod/

**Comment by jmooring** [comment]
The  erroneous "duplicate menu entry with identifier" warning in v0.123.0 was triggered by `sectionPagesMenu = 'main'` in the site configuration. The erroneous warning was removed with https://github.com/gohugoio/hugo/pull/12349 in v0.125.0.

The remaining problem (either resulting from or exposed by #12349) is that `sectionPagesMenu = 'main'` is adding non-section pages (e.g., content/contact.md) to the menu. 

```text
git clone --single-branch -b hugo-github-issue-12399 https://github.com/jmooring/hugo-testing hugo-github-issue-12399
cd hugo-github-issue-12399
hugo server
```
