### ISSUE TITLE
Images in markdown relative to content 

### ISSUE THREAD

**Issue by garvincasimir** [gohugoio/hugo#1240]
Hi, 
I like the idea of having my images close to my content so I create my articles like this:

```
post/my-post.md
post/images/my-post-img.png
```

This displays the images on the single template when ugly urls are turned on but does not display it on the list pages or on any page when ugly urls are turned off. The relative path for the image never gets transformed even with canonifyurls turned on. Maybe there is a setting I am messing?

```
![my img](images/my-post-img.png)
```

I see issue #147 had a discussion that might be related to this. The images are being copied but I am not getting the correct urls in the generated pages.

Any thoughts on this?

**Comment by bep** [comment]
This is currently not possible, but it is (or should be) in front of @spf13's brain ...

Currently you have to have to path relative to the context root (/post/images/...).

**Comment by garvincasimir** [comment]
I would send a pull request but the go code makes me feel dumb. But seriously great to see @spf13 take up this issue. I know it complicates rendering because the link to the image would vary based on the final path of the page it is rendered on.

**Comment by tcurdt** [comment]
I would love to have support for

    posts/2015/some-post-slug/index.md
    posts/2015/some-post-slug/image.png
    posts/2015/some-post-slug/archive.zip
    posts/2015/other-post-slug/index.md

and I want would like that to appear in the output as

    /2015/some-post/slug/index.html
    /2015/some-post/slug/image.png
    /2015/some-post/slug/archive.zip
    /2015/other-post-slug/index.html

**Comment by bep** [comment]
@tcurdt - sure, me too, but I wold hate to do this to reference the image:

```
<img src="/2015/some-post-slug/image.png" />
```
I think that is the hardest mental part about these bundles.

**Comment by tcurdt** [comment]
This actually seems to be working out of the box now.
Getting rid of "posts" folder is a problem though. A work around is to use:

    permalinks:
      post: /:year/:slug/

which isn't quite the same thing though.

**Comment by SvenDowideit** [comment]
@spf13 have you got some ideas on how to implement this? we need it for the Docker docs, but pointers will get me up to speed faster :) (its on my list of things for the next 4 days :)

**Comment by SvenDowideit** [comment]
initial version added in #1398

**Comment by AlexZeitler** [comment]
Is there any progress on using images in markdown relative to content?

**Comment by jygastaud** [comment]
@AlexZeitler : As suggest in #147 I'm using the following workaround.

Contents are in `content/project/my-content/index.md` folder
Images are stored in `static/project/my-content/my-image.png` folder

And in my markdown I can do `![my-image](my-image.png)`

Hugo just will copy the structure without the first "static" folder so generation the html file will have acces to the image.

Hope it helps!

**Comment by AlexZeitler** [comment]
@jygastaud Thanks for your reply.

I created this structure now:

```
content/blog/test-with-path/index.md
static/blog/test-with-path/mypng.png
```

In the md I referenced it  this way ```![some png](mypng.png)```

I also tried

```
content/blog/test-with-path/index.md
static/blog/test-with-path/mypng.png/mypng.png
```

None did work.

**Comment by jygastaud** [comment]
That's weird.
That works for me. See https://github.com/jygastaud/jygastaud.github.io/commit/a415264319dd812670cfd298159fa0347913e1ba which result to http://gastaud.io/article/entityconnect-d8/conversion-form-instance/

You can see structure here : https://github.com/jygastaud/jygastaud.github.io/tree/source

**Comment by garvincasimir** [comment]
@jygastaud please take a look at the original issue again. If you only ever display images on the actual post page then you can work around it. However, if your list pages display posts with images where the image is located relative to the content then the image will not display. Hugo would probably need to take the mark down and write different urls to the same asset based on the context of the page render. 

For example, your list page is www.yoursite.com/blog/ and it has your last 3 posts. A post at www.yoursite.com/blog/mypost.html with a relative image in /blog/images/img1.jpg can use a relative url in mypost.html to reference that image but that url will be incorrect for displaying your last 3 posts. It also gets tricky when you think about ugly vs no ugly urls. My hope was that Hugo could compensate for these different nuances and always write the correct url to the asset. I hope that clarifies it.

**Comment by jygastaud** [comment]
@garvincasimir oh sorry I missed the part that explains that it works on single page but not on list :/
Sorry for the noise.

**Comment by Wysie** [comment]
This issue gets more complicated when permalinks are used. For now I've just turned off permalinks so I can put images in the same folder as my content. It'd be good if the images gets copied along to the permalink folder structure instead of just the generated HTML file. Thanks!

**Comment by riverib** [comment]
It would be good to be able to put images relative to content, since github can preview and display them correctly. With images in /static folder github does not view/preview the images. It's very convenient for less technical users.

We may like it or not, making it work better with github/gitlab is helpful. Currently images don't display on github for hugo projects.

**Comment by saifulwebid** [comment]
Any update to this issue?

**Comment by bep** [comment]
>Any update to this issue?

You just updated it and made me look. Other than that => no.

**Comment by kburns** [comment]
Hi, I'm also interested in this use-case.  I've noticed that if you use a root-relative image path (eg "/gallery/post/image.jpg") in the post content, and set relativeURLs="true" in the site config, then things work fine, and both the list and post html pages get their proper page-relative path for the image ("../gallery/post/image.jpg" in /gallery/index.html and "../../gallery/post/image.jpg" in /gallery/post/index.html).

However, the types of content-relative image paths we'd rather use in the post content (eg "image.jpg" or "./image.jpg") don't seem to be modified by setting relativeURLs="true".  So perhaps extending the relativeURLs routine to first convert these content-relative paths to root-relative paths, and then performing its current function, would be a good approach for making this work?

**Comment by timbunce** [comment]
A content file like `content/foo/bar.md` results in an output file like `publish/foo/bar/index.html` I figured that I could create a `content/foo/bar/` directory and put any 'asset files' referred to by the content file into that directory.

Using @garvincasimir original example...
```
post/my-post.md
post/my-post/my-post-img.png
```
and then in `post/my-post.md` we'd refer to the image using:
```
![my img](my-post-img.png)
```

This seems natural and works fine for our needs (we're not using features like summary pages).

**Comment by madeso** [comment]
Not sure if this is solved or not out of the box, and I'm guessing it's not since the issue is still open, but I've solved it for my theme using a few regexes and where/paginatiors in a few files. Im also not sure if it is robust as my site is only one folder deep, and I've only tried it with pretty urls. I also dont use figure, only standard markdown images, relative to the current folder. Anyways, heres what I did for my custom theme to make it work, hope it is of help to someone :)

A post is like this:
blog/first-post/bones1.png The image I want to display
blog/first-post/_index.md: `![weird bones 1](bones1.png)`
[actual example](https://github.com/madeso/homepage/tree/7fe7f5befb9353d090aa472dbaf93493f283060b/content/blog/wp-turtlebones)

To make the page display correctly in listings and taxonomies I have a partial that (among other things fixes the urls):
```
{{ $newImage := (print "<img src=\"" .Permalink "$1\" alt=$3 $4>") }}
{{ $c2 := $c | replaceRE "<img src=\"(([a-zA-Z0-9]+/)*[a-zA-Z0-9]+\\.[a-zA-Z]+)\" alt=(.*) (.*)>" $newImage }}
```
[like this](https://github.com/madeso/homepage/blob/7fe7f5befb9353d090aa472dbaf93493f283060b/themes/expose/layouts/partials/content.html)

Finally, thre is just one thing left to do, make sure the posts are displayed on stuff.
I do this with a paginator on lists and taxonomies:
```
{{$section := .Section }}
{{ $paginator := .Paginate (where (where .Site.Pages "Section" $section) "RelPermalink" "!=" (printf "/%s/" $section)) }}
```
and a range on the rss template:

`{{ range first 15 (where (where .Site.Pages "Section" $section) "RelPermalink" "!=" (printf "/%s/" $section)) }}`

and a if on both lists and rss to keep the the post appearing when viewing only  _index.md page:
`{{ if eq .RelPermalink (printf "/%s/" .Section) }}`

The section variable might not be necessary anymore but I had scoping problems when I used several ifs instead of a this oneliner.

[rss template](https://github.com/madeso/homepage/blob/7fe7f5befb9353d090aa472dbaf93493f283060b/themes/expose/layouts/_default/rss.xml)

Hugo code custom theme and content: https://github.com/madeso/homepage/
Live: http://madeso.github.io/tags/fail/ (this tag currently contains 3 _index.md posts with local images)

**Comment by garvincasimir** [comment]
Interesting solution @madeso I will definitely try it.

**Comment by nhoizey** [comment]
Isn't this covered by #3651 ?

**Comment by bep** [comment]
>Isn't this covered by #3651 

tYes. I will add this to the list of issues that the commit for that fixes.

**Comment by cdupont** [comment]
Hi guys,
how to make this work with both Hugo and Github?
I have my documentation in markdown with images in the same folder. I would like to render it both with Hugo and Github...
I use Hugo V0.38 with bundles.
If I understood, I need to add some code in the markdown, such as:
```
{{ $logo := .Resources.GetByPrefix "logo" }}
```
But this won't work with Github.

**Comment by venky999** [comment]
Any thoughts on how it works on both GitHub and Hugo

**Comment by RMStoica-zivver** [comment]
@cdupont obviously hugo shortcodes aren't supported in GitHub and probably never will be
one should never use them if one wishes to maintain portability

**Comment by nhoizey** [comment]
If there is no Hugo based solution, I wonder if you could:
- use standard Markdown syntax for images, so that they show up in Github,
- use Hugo to generate the pages HTML with your own templates,
- and then transform the HTML with [images-responsiver](https://nhoizey.github.io/images-responsiver/), a Node.js library (disclaimer: I created it)

It should work well with a few pages, but probably be pretty slow with many.

**Comment by cdupont** [comment]
Actually, I got it working both in Github and vanilla Hugo.
See here for example: https://github.com/Waziup/waziup.io/blob/master/content/documentation/wazidev/sensors/index.md
The images are showing in Github.

**Comment by nhoizey** [comment]
@cdupont perfect! 👍

**Comment by sn0ot** [comment]
### For those still looking for a solution to this issue (as it is not documented in the hugo docs) I will leave a solution here.

To achieve **relative image paths in Hugo in markdowns files**, you should organize your content using Hugo's _newish_ Page Bundles structure, specifically [Leaf Bundles](https://gohugo.io/content-management/page-bundles/#leaf-bundles). This requires using an `index.md` file (not to be confused with `_index.md` used in branch bundles). 

You are probably used to writing posts inside of a markdown file with the name of the file as the post title , for example `post_about_blah.md` and `blah_blah_post.md`. And linking images from the `static/` directory.
```
|--content
|  \__posts
|  |  |--post_about_blah.md  
|  |  |--blah_blah_post.md  
|--static
|  \__images
|  |  |--picture_1.jpg   
|  |  |--picture_2.jpg               
|  |  |--picture_3.jpg   
|  |  |--picture_4.jpg
|  |  |--picture_5.jpg   
|  |  |--picture_6.jpg
```
Images would be rendered as such:

- `http://examplesite.com/images/picture_1.jpg`
- `http://examplesite.com/images/picture_2.jpg`
- `http://examplesite.com//images/picture_3.jpg`
- `http://examplesite.com//images/picture_4.jpg`
- `http://examplesite.com//images/picture_5.jpg`
- `http://examplesite.com//images/picture_6.jpg`

And therefore, images would have to be linked from inside the markdown posts as such:

- `![image](images/picture_1.jpg)`
- `![image](images/picture_2.jpg)`
- `![image](images/picture_3.jpg)`
- `![image](images/picture_4.jpg)`
- `![image](images/picture_5.jpg)`
- `![image](images/picture_6.jpg)`

Now you have to keep track of which image goes with which post, no name conflicts, etc. 

### To link images in your markdown file relative to your post, consider the following leaf bundle directory tree:
```
content
 \__posts 
 |  \__post_about_blah
 |  |  |--index.md
 |  |  |--picture_1.jpg
 |  |  \__images
 |  |  |  |--picture_2.jpg               
 |  |  |  |--picture_3.jpg      
 |  \__blah_blah_post
 |  |  |--index.md
 |  |  |--picture_1.jpg
 |  |  \__images
 |  |  |  |--picture_2.jpg               
 |  |  |  |--picture_3.jpg      
```

In the leaf bundle directory tree example above, `index.md` contains the "words" of your post and the directory in which `index.md` is (in our case `content/posts/post_about_blah` and `content/posts/blah_blah_post`) will be the generated url. The images will be rendered to to following links

- `http://examplesite.com/posts/post_about_blah/picture_1.jpg`
- `http://examplesite.com/posts/post_about_blah/images/picture_2.jpg`
- `http://examplesite.com/posts/post_about_blah/images/picture_3.jpg`
- `http://examplesite.com/posts/blah_blah_post/picture_1.jpg`
- `http://examplesite.com/posts/blah_blah_post/images/picture_2.jpg`
- `http://examplesite.com/posts/blah_blah_post/images/picture_3.jpg`

Therefore inside of the respective `index.md` files you can link to images as follows:

- `![image](picture_1.jpg)`
- `![image](images/picture_2.jpg)`
- `![image](images/picture_3.jpg)`
- `![image](picture_1.jpg)`
- `![image](images/picture_2.jpg)`
- `![image](images/picture_3.jpg)`


NOTE: I made a poor choice of directory names and it looks like linking is the almost the same - so read carefully :)

**Comment by ACupofAir** [comment]
> Hi, I like the idea of having my images close to my content so I create my articles like this:
> 
> ```
> post/my-post.md
> post/images/my-post-img.png
> ```
> 
> This displays the images on the single template when ugly urls are turned on but does not display it on the list pages or on any page when ugly urls are turned off. The relative path for the image never gets transformed even with canonifyurls turned on. Maybe there is a setting I am messing?
> 
> ```
> ![my img](images/my-post-img.png)
> ```
> 
> I see issue #147 had a discussion that might be related to this. The images are being copied but I am not getting the correct urls in the generated pages.
> 
> Any thoughts on this?

I find a feasible method: just [follow this office tutor](https://gohugo.io/getting-started/configuration-markup#:~:text=Image%20Markdown%20example%3A), and change the hook, here is my render-image.html
```html
<p class="md__image">
  {{ if .Title }}
  <img src="{{ .Destination  }}" alt="{{ .Text }}">
  {{ else }}
  <img src="../{{ .Destination }}" alt="{{ .Text }}">
  {{ end }}
</p>
```
If you need ref a image link with http://xxxx, you need link it like this: `![image](https://xxx "title"`
If you need ref a image in the res fold you just link it `![image](res/image.png)`
