### ISSUE TITLE
78MB hugo binary is full of paths and urls

### ISSUE THREAD

**Issue by berthubert** [gohugoio/hugo#12406]
Hi, many thanks for Hugo (hugo v0.125.2-4e483f5d4abae136c4312d397a55e9e1d39148df linux/amd64 BuildDate=2024-04-20T15:29:44Z VendorInfo=gohugoio)

I just checked the binary version I downloaded from github, and it is huge. Furthermore, it contains 42181 github.com urls and thousands of long paths. 

I wonder if "strip" is finding everything it needs to in the hugo binary release. Running strip myself does not decrease the binary size. 

```bash
$ du -h hugo
79M	hugo
$ strings -a -n 10 hugo  | grep -c github
42181
$ strings -a -n 10 hugo  | grep -c /root/
2412
$ strings -a -n 10 hugo  | grep -c /usr/local/
794
```
### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
>I just checked the binary version I downloaded from github, and it is huge. Furthermore, it contains 42181 github.com urls and thousands of long paths.

It stores the dependency information which I guess can explain some of the bove.

**Comment by lyind** [comment]
Sounds more like an issue to be filed in https://github.com/golang/go (if at all)

**Comment by bep** [comment]
I'm closing this, this needs to be improve upstream. If there are some build flags that I dont't know of that could improve this, please open a PR with changes in:

https://github.com/gohugoio/hugo/blob/master/hugoreleaser.toml

**Comment by retsplines** [comment]
Seems like the dependency/module information isn't going away (see https://github.com/golang/go/issues/50501#issuecomment-1010225207) but potentially the baked-in build paths can be cleaned up with the `-trimpath` compiler argument.

**Comment by berthubert** [comment]
It appears there are 180 dependencies in the Hugo binary:
```bash
$ strings -n 10 ./hugo | grep -i github | grep ^dep -c
180
```
Many of the other github.com instances in the binary might in fact be paths, so `-trimpath` could well be very useful to try.

**Comment by mark-kubacki** [comment]
You’d get the list of built-in dependencies using `go version -m` like this:

```console
# go version -m hugo | grep -e "^\s*dep" | wc -l
143
```
