### ISSUE TITLE
Twitter `og:description` doubly escaped by Hugo 0.125.x

### ISSUE THREAD

**Issue by chalin** [gohugoio/hugo#12418]
If you build this [small repro (test-site-2024-04-23.zip)](https://drive.google.com/file/d/1VIOiEZ8tdyI2CR1pTkoT9dqw_r5kdBdu) using Hugo 0.124.1 and 0.125.2, you'll see the following difference in the `content` of `<meta property="og:description">` for http://localhost:1313/docs/page:

```html
0.124.1: <meta property="og:description" content="Test line with a single quote: can&rsquo;t." />
0.125.2: <meta property="og:description" content="Test line with a single quote: can&amp;rsquo;t.">
```

Notice that 0.125.2 doubly escapes the `content`, so that:

- `can&rsquo;t` becomes
- `can&amp;rsquo;t`

This seems wrong to me. WDYT?

---

Below I include a bit more header context.

Hugo 0.124.1:

```html
<meta name="description" content="Test line with a single quote: can&amp;rsquo;t.">
<meta property="og:title" content="Some page" />
<meta property="og:description" content="Test line with a single quote: can&rsquo;t." />
...
<meta name="twitter:description" content="Test line with a single quote: can&rsquo;t."/>
```

Hugo 0.125.2:

```html
<meta name="description" content="Test line with a single quote: can&amp;rsquo;t.">
<meta property="og:url" content="http://localhost:1313/docs/page/">
  <meta property="og:site_name" content="My New Hugo Site">
  <meta property="og:title" content="Some page">
  <meta property="og:description" content="Test line with a single quote: can&amp;rsquo;t.">
  ...
<meta name="twitter:description" content="Test line with a single quote: can&rsquo;t.">
```

**Comment by jmooring** [comment]
I'll look at this again. Here's the challenge in the embedded opengraph template:

```text
{{- with or .Description .Summary site.Params.description | plainify }}
  <meta property="og:description" content="{{ . }}">
{{- end }}
```

The input can be plain text, markdown, rendered markdown, HTML, or anything else. If rendered markdown, it might be wrapped in a `p` element or it might not, depending on how the summary was defined.

**Comment by jmooring** [comment]
Going back through issues, PRs, and forum topics, the best that I have come up with for consistent rendering regardless of how the summary is defined (front matter, with summary divider, without summary divider) is:

```text
{{- with or .Description .Summary site.Params.description | .RenderString | plainify | htmlUnescape }}
  <meta property="og:description" content="{{ . }}">
{{- end }}
```

This handles the following cases the same way:

```text
+++
title = 'Post 1'
summary = "Test <em>line</em> with a **single** quote: can't."
+++
```

```text
+++
title = 'Post 1'
+++

Test <em>line</em> with a **single** quote: can't.
```

```text
+++
title = 'Post 1'
+++

Test <em>line</em> with a **single** quote: can't.
<!--more-->
```

All three produce:

```html
<meta property="og:description" content="Test line with a single quote: can’t.">
```

If this is acceptable:

- [ ] Do the same thing for `og:site_name` and `og:title`
- [ ] Make similar changes to the embedded schema and twitter_cards templates

**Comment by chalin** [comment]
Sounds good, thanks @jmooring. The OTel website has descriptions like the following (which I'm hoping to curate at some point to remove the images, but this is what we have now):

```yaml
description: >-
  <img width="35" class="img-initial" src="/img/logos/32x32/Golang_SDK.svg"
  alt="Go"> A language-specific implementation of OpenTelemetry in Go.
```

And this (markdown):

```yaml
description: >-
  _OTel in Practice_ is a _series_ of talks initiated by some members of the End
  User SIG.
```

Will the solution you propose handle such descriptions as before (or better :)?

/cc @svrnm @theletterf

**Comment by jmooring** [comment]
@chalin 

With the proposed changes, the first is rendered to:

```html
<meta property="og:description" content=" A language-specific implementation of OpenTelemetry in Go.">
```

The second is rendered to:

```html
<meta property="og:description" content="OTel in Practice is a series of talks initiated by some members of the End User SIG.">
```

**Comment by chalin** [comment]
Thanks @jmooring, that LGTM.

**Comment by jmooring** [comment]
@chalin 

In its current implementation, PR #12425 does this:

> the first is rendered to:

```html
<meta property="og:description" content=" A language-specific implementation of OpenTelemetry in Go.">
```
> The second is rendered to:

```html
<meta property="og:description" content="_OTel in Practice_ is a _series_ of talks initiated by some members of the End User SIG.">
``` 

In your second example, note that the markdown is **not** rendered to HTML due to performance concerns related to using .RenderString on every og:description on every page. 

If you want to render the markdown and don't care about a performance hit, use this in the override template...

```text
{{- with or .Description .Summary site.Params.description | .RenderString | plainify | htmlUnescape | chomp }}
```

I have no idea how much this would affect a 10,000 page site.
