### ISSUE TITLE
Public site building simultaneously

### ISSUE THREAD

**Issue by pmbrown** [gohugoio/hugo#12421]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo v0.125.3-474c4c02212cf97712c6fbf4159c68822ea6e078 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### Issue

Whenever I run `hugo server` the public site is being built simultaneously without me running a site build command. Testing with a new empty site produces the same results, as soon as I boot up the server the public site is generated automatically without me running the `hugo` command to build the site.

I updated from v122.0 so missed v123x and v124x but I can replicate the issue with v125.1 and v125.3. I'm running Windows 10.

**Comment by bep** [comment]
>the server the public site is generated automatically without me running the hugo command to build the site.

I'm not totally sure what you mean by this, but 

1. In Hugo v0.123.0 we changed the default behaviour of the server to _write to disk_ (`/public`) instead of to memory. This is what mot people would want and that is especially true for bigger sites.
2. You can get the old behaviour by running `hugo server --renderToMemory`.

**Comment by pmbrown** [comment]
> I'm not totally sure what you mean by this

To publish the site in v0.122.0 and earlier I had to run the command `hugo` seperately, with v0.125.3 running `hugo server` runs the development server *and* publishes the static site in the public directory.

I'd noticed the writing to disk change but figured because the docs still outlined that running the server and publishing the site are two seperate commands nothing had changed. 

Running `hugo server --renderToMemory` does revert the behaviour as suggested, and as I would definitely consider myself a minority user it solves my issue so thank you.
