### ISSUE TITLE
Error suppressed while running server unless browser is open

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12439]
This is new (and undesirable) behavior in v0.123.0 and later. To reproduce:

1. Make sure that none of your browser tabs are pointed to `http://localhost:1313/`.
2. Start hugo server
3. Edit the home page template, inserting this intentionally incorrect template action:

    ```text
    {{ now.Yea }}
    ```

4. Save the template

Expected: Hugo should throw an error.

Actual: No error. Hugo doesn't throw an error until you point your browser to `http://localhost:1313/`.

Reference: <https://discourse.gohugo.io/t/should-this-trigger-an-error/49458>

Last tested with hugo v0.125.4-cc3574ef4f41fccbe88d9443ed066eb10867ada2+extended linux/amd64.

**Comment by bep** [comment]
Try

```
server --disableFastRender  
```

The title of this issue isn't correct:

* We cannot log an error before it happens.
* In fast render mode, we only render the last `n` visited pages with all of its dependencies.
* Before Hugo `v0.123.0` we always also rendered the home page. Now that we have a more robust "partial change tracker", we only render what you look at. Doing the old way is wasteful, esp. in common use cases having big JSON search indexes etc. being hooked to the home page.

**Comment by jmooring** [comment]
I understand, and when running with the `--disableFastRender` flag the error is displayed immediately. I'm inclined to close this because most typos like this are caught as expected, e.g.,

```
  {{ .Stor.Set "foo" "bar" }}
```

>> Error ... can't evaluate field Stor in type *hugolib.pageState
