### ISSUE TITLE
Broken image sources with base64 encoded images

### ISSUE THREAD

**Issue by paranerd** [gohugoio/hugo#12443]
hugo version: 0.125.4

I just found images in my pagefind search on my Hugo site to be broken. After some extensive debugging I found that the issue was likely due to parsing issues with image sources when `src` is in base64:

Hugo encodes

```html
<img src="data:{{ .MediaType.Type }};base64,{{ .Content | base64Encode }}" />
```

into a base64 string that contains `&#43;` (and other `&#XX;` parts) instead of `+`.

I confirmed this by checking the files in `public/`

This is not a problem in any other location on the site where the existing `&#XX;` is "retranslated" into `+` just fine. 

However, it breaks pagefind's `meta.image` which contains the raw (malformed?) base64 string.

A **workaround** for me was:

```js
img['src'] = resultData.meta.image.replaceAll(/&#\d\d;/g, '+');
```

which brings back the images.

I also raised the issue with the pagefind team but since Hugo writes malformed base64 strings so I think this may be a bug worth investigating here.

**Interesting fact:** The issue exists on my MacBook and also on an Ubuntu server but NOT on Cloudflare where I'm deploying to. All versions (Hugo and pagefind) are the same on all systems, however Cloudflare uses the go-build (MacBook uses homebrew, Ubuntu uses snap).

Maybe this helps.

Thank you!

**Comment by jmooring** [comment]
No bug. It's just Go's [html/template](https://pkg.go.dev/html/template) package doing it's thing.

Do this to indicate that `src="foo"` is a safe HTML attribute:

```text
{{ with resources.Get "a.jpg" }}
  {{ $src := printf "data:%s;base64,%s" .MediaType.Type (.Content | base64Encode) }}
  <img {{ printf "src=%q" $src | safeHTMLAttr }}>
{{ end }}
```

**Comment by paranerd** [comment]
Wow... I spent WAY too many hours figuring this out^^
Thanks for the quick response. This indeed solved the issue :-)!
