### ISSUE TITLE
Update from 0.111.3 to 0.124.1 breaks site

### ISSUE THREAD

**Issue by flyn-org** [gohugoio/hugo#12445]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.124.1+extended linux/amd64 BuildDate=2024-04-28T00:00:00+00:00 VendorInfo=Fedora:0.124.1-2.fc41
</pre>

### Issue

I have for several years maintained a site using Hugo and the academic/wowchemy theme. Updating from 0.111.3 to 0.124.1 broke Hugo's ability to build my site:

<pre>
$ hugo
Start building sites … 
hugo v0.124.1+extended linux/amd64 BuildDate=2024-04-28T00:00:00+00:00 VendorInfo=Fedora:0.124.1-2.fc41

ERROR Could not find an author page at `/authors/authors`. Please check the value of `author` in your About widget and create an associated author page if one does not already exist. See https://wowchemy.com/docs/page-builder/#about
Total in 168 ms
Error: error building site: logged 1 error(s)
</pre>

The site uses the following modules:
- github.com/wowchemy/wowchemy-hugo-modules/netlify-cms-academic v0.0.0-20201016182837-be0fa17ac006
- github.com/wowchemy/wowchemy-hugo-modules/wowchemy v0.0.0-20201016182837-be0fa17ac006

This seems related to wowchemy's `layouts/partials/widgets/about.html`, which contains this:
<pre>
{{ $author := "" }}
{{ if .author }}
  {{ $author = .author }}
{{ else }}
  {{ $author = $page.Params.author }}
{{end}}
</pre>
The value `.author` seems to be `"authors"` and `$page.Params.author` seems to be `nil` when building one of my files, but I do not know why. My author value should be `"admin"`, as `content/authors/admin/_index.md` exists.

### Does this issue reproduce with the latest release?

Yes. I have also tried 0.125.4, which exhibits this same problem.

**Comment by jmooring** [comment]
Please raise an issue with the Academic/Wowchemy/Hugo Blox team:
<https://github.com/HugoBlox/hugo-blox-builder/discussions>

They also have an active Discord channel:
<https://discord.com/invite/z8wNYzb>

It looks to me like you are using a very old version of their theme/module.
