### ISSUE TITLE
Shouldn't this check for a `tsconfig.json` in addition to checking `[build.noJSConfigInAssets]`?

### ISSUE THREAD

**Issue by InTEGr8or** [gohugoio/hugo#12453]
Isn't it generally true that if `tsconfig.json` exists, then no `jsconfig.json` needs to be created?

Wouldn't a quick search for a `tsconfig.json` negate the need to create a `jsconfig.json`

And for that matter, shouldn't a check for an already existing `jsconfig.json` be performed? It's overwriting anything I put in there and resetting to a JS version prior to `es2015`, so it's actually breaking any intellisense.

I see the switch that I can put in `hugo.toml` or `config/_default/build.toml`

```toml
[build]
    noJSConfigInAssets = true
 ```
 
 But that doesn't seem to be working.

If the `noJSConfigInAssets` switch were working, it would still require new users who want to use the wonderful Hugo TS integrated environment to web-search this obscure config setting which seems to be easy to not implement properly, as I have apparently struggled with.

https://github.com/gohugoio/hugo/blob/c8e400b621ea7d44e522fb9bfa66d992ccb9ca84/hugolib/hugo_sites_build.go#L423

**Comment by bep** [comment]
>And for that matter, shouldn't a check for an already existing jsconfig.json be performed? 

We need to re-write that file on changes, so without any additional state, the above doesn't make much sense.

>I see the switch that I can put in hugo.toml or config/_default/build.toml

If you put it in `build`, you need to omit the "header":

```toml
noJSConfigInAssets = true
```

**Comment by InTEGr8or** [comment]
I see. I think you mean that you need to rewrite the `jsconfig.json` on other changes. That would mean there is no way for the user to edit that file persistently unless they investigated the upstream changes that create/edit it.

Wouldn't it still be possible to check for a `tsconfig.json` before overwriting?

I think I got it working by adding the `noJSConfigInAssets` to a new `hugo.toml`, but I like your suggestion better.
