### ISSUE TITLE
Browser does not refresh after changing Sass collected with Match

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12456]
The issue title is imperfect... it is certainly not true in the general sense. There's something about ranging through a slice of Sass files that's triggering this.

Reference: <https://discourse.gohugo.io/t/scss-changes-do-not-reload-live/49591>

This works as expected in v0.122.0, but fails with v0.123.0 and later.

```text
git clone --single-branch -b hugo-forum-topic-49591 https://github.com/jmooring/hugo-testing hugo-forum-topic-49591
cd hugo-forum-topic-49591
hugo server
```

Browse to http://localhost:1313/, then make changes to assets/dir/b.scss.

Results:

- Expected: home page shows changes.
- Actual: no change.

Note that changes to assets/a.scss are shown immediately.

---

```text
assets/
├── dir/
│   └── b.scss
└── a.scss
```

layouts/partials/css.html

```text
{{ $a := slice (resources.Get "a.scss") }}
{{ $b := resources.Match "dir/*.scss" }}

{{/* Add styles in a specific order. */}}
{{ $styles := slice $a $b }}

{{ $stylesheets := slice }}
  {{ range $styles }}
  {{ $stylesheets = $stylesheets | collections.Append . }}
{{ end }}

{{ range $stylesheets }}
  {{ with . | resources.ToCSS | fingerprint }}
    <link as="style"  href="{{ .RelPermalink }}" rel="preload stylesheet">
  {{ end }}
{{ end }}
```

**Comment by bep** [comment]
That looks like an odd construct, but I will have a look at it and fix it. 

Note that most of these issues can be worked around with a cache buster entry.

**Comment by adrian5** [comment]
I'm still experiencing this with Hugo `v0.125.7+extended linux/amd64` and Chromium `124.0.6367.155`. The page reloads on edits, but the inserted CSS bundle doesn't change.

**Comment by jmooring** [comment]
@adrian5 This is issue resolved and closed. I suspect you have a different problem. Please create a topic in the [forum](https://discourse.gohugo.io/) where we can gather details and create a reproducible example.
