### ISSUE TITLE
eq on resource `.MediaType` containing `+` fails

### ISSUE THREAD

**Issue by khimaros** [gohugoio/hugo#12466]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.125.5+extended linux/amd64 BuildDate=2024-05-02T10:23:19Z VendorInfo=debian:0.125.5-1
</pre>

### Does this issue reproduce with the latest release?
yes

## details

when iterating over the `.Resources` for a page bundle:

```
{{ if eq .MediaType "application/gpx+xml" }}
  Render GPX
{{ else }}
  unknown media ({{ .MediaType }})
{{ end }}
```

produces the following output:

```
unknown media (application/gpx&#43;xml)
```

i tried `eq .MediaType "application/gpx&#43;xml"` but that also fails.

**Comment by jmooring** [comment]
Can you share a link to the data source?

**Comment by khimaros** [comment]
it is an empty file with the suffix ".gpx"

FWIW, as a a workaround, i have been able to work around this by comparing to .MediaType.SubType "gpx" instead

**Comment by jmooring** [comment]
On a resource object, `MediaType` returns an object, not a string.

You need to do this instead:

```text
{{ with resources.Get "data/foo.gpx" }}
  {{ if eq .MediaType.Type "application/gpx+xml" }}
    Render GPX
  {{ else }}
    unknown media ({{ .MediaType.Type }})
  {{ end }}
{{ end }}
```

**Comment by khimaros** [comment]
there are still some strange things happening with HTML escaping and so on behind the scenes. when i try to render HTML content with `{{ .MediaType.Type }}`, for example as part of an HTML attribute, it has these same problematic escape sequences.

**Comment by jmooring** [comment]
> as part of an HTML attribute

But is it really broken? Your browser interprets it correctly. You're simply seeing Go's html/template package doing its thing.

If you really don't like it, pass the attribute name and value through the [`safeHTMLAttr`](https://gohugo.io/functions/safe/htmlattr/) template function. For example:

```text
<a {{ printf "href=%q" .URL | safeHTMLAttr }}>{{ .Name }}</a>
```

This issue is closed. Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. Thanks.
