### ISSUE TITLE
Hugo fails to compile Markdown files after a specific date

### ISSUE THREAD

**Issue by 2niuhe** [gohugoio/hugo#12477]
When the date in my Markdown file is set to 2024-04-10, Hugo can locate and compile the file without any issues. However, upon changing the date to 2024-05-10, Hugo fails to compile the document, as if it doesn't exist.

```
---
date: "2024-04-10"
lastmod: "2024-04-10"
draft: false
---
```

Steps to Reproduce:

Set the date in the Markdown file to 2024-04-10.
Run Hugo to compile the site.
Note successful compilation.
Expected Behavior:
Hugo should compile the Markdown file regardless of the date set within the file.

Actual Behavior:
Upon changing the date in the Markdown file to 2024-05-10 and attempting to compile, Hugo fails to recognize and compile the document.

Additional Information:

This issue occurs consistently across multiple attempts.
No changes have been made to the configuration or setup of Hugo.
The issue persists even after restarting Hugo.

my hugo config.yaml is 

```yaml
DateFormat: "2016-01-02"
```

<pre>
hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d darwin/arm64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio

hugo v0.125.7-b1d808bc373f53ad37c8966bb02a6aea095db5f8 darwin/arm64 BuildDate=2024-05-08T14:46:24Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

yes

**Comment by jmooring** [comment]
<https://gohugo.io/getting-started/usage/#draft-future-and-expired-content>

> By default, Hugo will not publish content when:
> 
> - The draft value is true
> - The date is in the future
> - The publishDate is in the future
> - The expiryDate is in the past

**Comment by adrian5** [comment]
@2niuhe I ran into the same issue with a project as Hugo's default behavior changed along the way.

You can set [`buildFuture = true`](https://gohugo.io/getting-started/configuration/#buildfuture) in your configuration (e.g. `config/_default/hugo.toml`) to ensure files gets published regardless of date.

**Comment by jmooring** [comment]
> Hugo's default behavior changed along the way.

No, it did not.
