### ISSUE TITLE
Content adapters clip path after last dot

### ISSUE THREAD

**Issue by marchof** [gohugoio/hugo#12493]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.126.0+extended darwin/arm64 BuildDate=2024-05-14T13:24:11Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes

### Description

First of all, many thanks for providing _content adapters_ with the latest release! This is a great addition for data driven sites like https://javaalmanac.io/

I started replacing generated markdown files with content adapters. Some of the paths contains dots, for example:

https://javaalmanac.io/jdk/6/apidiff/1.4/

Now I started dynamically creating these pages, using for example a `path` of `jdk/6/apidiff/1.4/` to generate the page above.

#### Expected behavior

The content is created at `jdk/6/apidiff/1.4/index.html`

#### Actual Behaviour

The content is created at `jdk/6/apidiff/1/index.html`

So for me it looks like the path is clipped at the last dot (`.`). I tried with different paths like `aaa/bbb.ccc/` which is also clipped to `aaa/bbb`.

**Comment by jmooring** [comment]
Test case:

```go
func TestFoo(t *testing.T) {
	t.Parallel()

	files := `
-- hugo.toml --
disableKinds = ['home','section','rss','sitemap','taxonomy','term']
-- content/_content.gotmpl --
{{ .AddPage (dict "path" "s-1.2.3/p-4.5.6" "title" "p-4.5.6") }}
-- layouts/_default/single.html --
{{ .Title }}
`

	b := hugolib.Test(t, files)

	b.AssertFileExists("public/s-1.2.3/p-4.5.6/index.html", true)
}
```

**Comment by jmooring** [comment]
@marchof You can work around this by setting `slug` in the map passed to the `AddPage` method.

**Comment by bep** [comment]
>this be changed to render the full path?

This is marked as a bug, so it will be fixed.

**Comment by marchof** [comment]
@bep @jmooring Thanks for this super-fast fix!
