### ISSUE TITLE
Add function to strip EXIF data from images

### ISSUE THREAD

**Issue by JoelOtter** [gohugoio/hugo#12506]
Hugo has a number of image processing facilities, which can be used to strip EXIF data out of images as a side effect of operations like Resize. However, there doesn't appear to be a way to strip the EXIF data without re-encoding the image, which causes a loss of data if using a lossy format like JPEG or WebP - I personally notice a visible loss of colour information when using these.

It would be useful, I think, to have a `StripExif` function (or perhaps a `strip_exif` directive to `Process`?). I'd be happy to take on doing this work myself if the maintainers are OK with it.

Thanks!

**Comment by jmooring** [comment]
Assuming we can safely and reliably strip the EXIF data without re-encoding, is there ever a reason to _retain_ the EXIF data once an image is published with `Permalink`, `RelPermalink`, or `Publish`? If not, could the EXIF data be stripped by default when invoking these methods (possibly configurable under the imaging key).

I've been aware of this issue for a while, in particular when a content author adds an image in markdown:

```
![alt](image.jpg)
```

An inexperience author has no idea they are publishing the photo's geo location.

Whether we add a new thing, or change the existing things, an image render hook would take care of the above.

**Comment by JoelOtter** [comment]
I suppose it depends on the performance of the EXIF operation - I wouldn't want to risk ballooning a user's built time or repo size without that being opt-in. If however it's very fast and would just happen as part of the image being placed in `public` (as opposed to it going to `resources` first which I think is what happens when we process images) then I think I'm in agreement that stripping the EXIF by default is the right call.

**Comment by bep** [comment]
> However, there doesn't appear to be a way to strip the EXIF data without re-encoding the image,

EXIF is encoded into the image. How do you strip the EXIF without re-encoding the image?

**Comment by JoelOtter** [comment]
"Re-encoding" was perhaps a poor choice of term - I meant without further iterations of JPEG compression or similar.

**Comment by jmooring** [comment]
> How do you strip the EXIF without re-encoding the image?

I have no idea if/how this would be accomplished in Go, but exiftool removes the metadata without touching the raster block. I've tested this by hashing the raster block (not the file itself) before and after stripping the metadata:

```text
# before 
identify -verbose -format %# assets/a.jpg

# strip meta 
exiftool -all assets/a.jpg

# after 
identify -verbose -format %# assets/a.jpg
```

The hash remains unchanged.

**Comment by bep** [comment]
>I have no idea if/how this would be accomplished in Go, but exiftool removes the metadata without touching the raster block.

Yea, I guess there's bytes that could be just trimmed.
