### ISSUE TITLE
Handling of local anchor links in the built in link render hook

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#12503]
In my head this

https://github.com/gohugoio/hugo/blob/3d40aba512931031921463dafc172c0d124437b8/tpl/tplimpl/embedded/templates/_default/_markup/render-link.html#L4

Should only include the anchor part (e.g. `#foo`) and not the `.RelPermalink` to the current page. I'm not totally sure how the different browsers handle this, but I'm pretty sure there's a difference.

I noticed this surface on the forum, see https://discourse.gohugo.io/t/markdown-syntax-render/49835

/cc @jmooring

**Comment by jmooring** [comment]
With the current implementation, if a summary rendered on a list page contains a same-page link, the link will properly resolve to the containing page instead of doing nothing.

**Comment by bep** [comment]
Yea, right, I didn't think about that ... I'll put it on my list to check for "browser behaviour". Anyhow, people are free to add their own template.

**Comment by jmooring** [comment]
While monitoring the Network tab of Chrome's dev tools, I see no difference between `#foo` and `/this/page/#foo`... meaning there's zero network activity either way. The same is true in Firefox.

There may be some other side effect that I'm not aware of, but this approach seems to be fine.

**Comment by jmooring** [comment]
I think we can close this issue per my previous comment.
