### ISSUE TITLE
Deprecate .Site.Sites.First in favor of .Site.Sites.Default

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12513]
Prior to v0.123.0, `.Site.Sites` returned the sites sorted by weight then language key. With v0.123.0 and later, the site corresponding to the default language is first on the list. 

With this config...

```text
defaultContentLanguage = 'de'

[languages.en]
weight = 1

[languages.de]
weight = 2

[languages.fr]
weight = 3
```

...`.Site.Sites.First` now returns the second site, which is exactly what it should be doing. But I think we should rename the method to describe what it does.

If implemented, need to update:

- <https://gohugo.io/methods/page/sites/>
- <https://gohugo.io/methods/site/sites/>

**Comment by 2312So** [comment]
> Antes de v0.123.0, `.Site.Sites`devolvía los sitios ordenados por peso y luego por clave de idioma. Con v0.123.0 y posteriores, el sitio correspondiente al idioma predeterminado es el primero en la lista.
> 
> Con esta configuración...
> 
> ```
> defaultContentLanguage = 'de'
> 
> [languages.en]
> weight = 1
> 
> [languages.de]
> weight = 2
> 
> [languages.fr]
> weight = 3
> ```
> 
> ... `.Site.Sites.First`ahora devuelve el segundo sitio, que es exactamente lo que debería estar haciendo. Pero creo que deberíamos cambiar el nombre del método para describir lo que hace.

@2312so
![repository-open-graph-template](https://github.com/gohugoio/hugo/assets/170082994/d6375b6b-77f5-4df5-a2d3-5235792178ca)
