### ISSUE TITLE
Fix the viewport of content.

### ISSUE THREAD

**Issue by SilverStar323** [gohugoio/hugo#12527]
Whenever the language of 'dark-box' is changed, the viewport of the content also shifts. I believe this is because the height of the \<blockquote\> tags affects the layout, causing the new header to start at the end of the previous \<blockquote\> tag. This makes it difficult to view the content properly. I would like to stabilize the viewport of the content to resolve this issue.

Thanks for your reading.

**Comment by jmooring** [comment]
See <https://discourse.gohugo.io/t/fix-the-viewport-of-content/49944/2?>
