### ISSUE TITLE
sitemap file name not changing when custom filename is specified

### ISSUE THREAD

**Issue by jluiz20** [gohugoio/hugo#12525]
If I am not doing anything wrong, it seems that the newer version is not generating a sitemap with a custom name. I have copied the [configuration from the docs](https://gohugo.io/templates/sitemap-template/#configuration) and changed the `filename` but it is always generating the sitemap with the default `sitemap.xml` name.

this is my config
![image](https://github.com/gohugoio/hugo/assets/9250618/aca5c72b-21a2-4ba4-ac65-a9ee80af8840)

and when I run `hugo` to build the site, the sitemap in the `public` folder is `sitemap.xml` instead of the `sitemap-1.xml` in the configuration.

![image](https://github.com/gohugoio/hugo/assets/9250618/a8cf9513-4b77-4084-b116-478892e3c245)

I know it was working in some versions ago, but I am not sure which one it was working. Also, I can be misconfiguring stuff, so I am sorry I am doing something wrong.

### What version of Hugo are you using (`hugo version`)?
hugo version
<pre>
 v0.126.1+extended
</pre>

### Does this issue reproduce with the latest release?
yes

Thank you for the great project! I love hugo <3

**Comment by jmooring** [comment]
This worked in v0.122.0 and earlier.

**Comment by jluiz20** [comment]
Now it is working in the new version 0.126.2! Thank you @jmooring for the fix!!
