### ISSUE TITLE
Option to not generate aliases for first page of pagination pages

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#12572]
https://discourse.gohugo.io/t/pagination-seems-to-create-aliases/22422/6?u=razon

**Comment by bep** [comment]
We currently have a `paginate` option (meaning: default pagination page size), so we need to consolidate a little. I suggest:

```go
// Loaded from the 'pagination' key in hugo.toml.
struct PaginationConfig {
  defaultPageSize int
  disableAliases bool
}
```

And make sure that the old config setup also works.

**Comment by jmooring** [comment]
We also have `paginatePath`.

**Comment by jmooring** [comment]
I just saw this in a site config:

```text
[languages.en]
weight = 1
paginatePath = "page-en"

[languages.de]
weight = 2
paginatePath = "page-de"
```

The pagination path is different for each language.  Not sure how that's going to work if we include it in the struct above.

**Comment by bep** [comment]
>The pagination path is different for each language. Not sure how that's going to work if we include it in the struct above.

I don't see how that will be a problem, the above will still work. We will want to eventually deprecate `paginatePath` etc., but then the above would look like:

```toml
[languages.de]
weight = 2
[languages.de.pagination]
path = "page-de"
```
