### ISSUE TITLE
Not generating the correct Chroma styles for syntax highlighting themes

### ISSUE THREAD

**Issue by aamnah** [gohugoio/hugo#12580]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.127.0-74e0f3bd63c51f3c7a0f07a7c779eec9e922957e+extended linux/amd64 BuildDate=2024-06-05T10:27:59Z VendorInfo=snap:0.127.0
</pre>

### Does this issue reproduce with the latest release?
Yes, i have the issue on version `0.127.0`

### Hugo is not generating the correct Chroma styles 

I am using the following command

```bash
hugo gen chromastyles --style tokyonight-night > tokyonight-night.css
```

It does generate the styles, but the styles themself are incorrect and do not match the originals. The same styles are generated for various themes.

The following themes had wrong stylesheets generated:

- [tokyonight-day](https://xyproto.github.io/splash/docs/tokyonight-day.html) 
- [tokyonight-moon](https://xyproto.github.io/splash/docs/tokyonight-moon.html)
- [tokyonight-night](https://xyproto.github.io/splash/docs/tokyonight-night.html)
- [tokyonight-storm](https://xyproto.github.io/splash/docs/tokyonight-storm.html)

For example, the original chroma [XML stylesheet for tokyonight-night](https://github.com/alecthomas/chroma/blob/master/styles/tokyonight-night.xml) has the following code

```xml
<entry type="Background" style="bg:#1a1b26 #c0caf5"/>
```
but the generated stylesheet with `hugo gen chromastyles` has

```css
/* Background */ .bg { color:#e5e5e5;background-color:#000; }
```

I'm installing the styles mentioned [here](https://xyproto.github.io/splash/docs/all.html) and comparing them with the original code [here](https://github.com/alecthomas/chroma/tree/master/styles)

**Comment by jmooring** [comment]
The  were added to [github.com/alecthomas/chroma](https://github.com/alecthomas/chroma) in v2.14.0 which was released on 22 May 2024. We're still using v2.13.0.
