### ISSUE TITLE
Support GitHub's Alert Markdown extension

### ISSUE THREAD

**Issue by yoghurtlee-thu** [gohugoio/hugo#12590]
I am currently immersed in the development of a new Hugo theme, which aims to provide users with a seamless experience when writing Hugo blogs using Obsidian. However, when it comes to Callout blocks like this:

> [!important]
> This is a Callout.

Things get stuck. While utilizing shortcodes and regex can be a workaround, it tends to be error-prone and lacks elegance.

Thus, I am curious whether the esteemed Hugo development team would consider enhancing the Markdown parsing engine to natively support GitHub-style Callouts.

Yours sincerely.

**Comment by bep** [comment]
When this was proposed/implemented at GitHub, I suggested they used markdown attributes instead (which is certainly more standard and something Hugo could easily support). 

They chose not to listen to me. But you could, e.g:

````
```callout {level="warning" }
This is a warning.
```
````

And add a code render hook for it.

**Comment by yoghurtlee-thu** [comment]
> When this was proposed/implemented at GitHub, I suggested they used markdown attributes instead (which is certainly more standard and something Hugo could easily support).
> 
> They chose not to listen to me. But you could, e.g:
> 
> ```
> ```callout {level="warning" }
> This is a warning.
> ```
> ```
> 
> And add a code render hook for it.

Thank you for your kind reply, @bep. Using markdown attributes is indeed a more Markdown-standard solution, and I will try it in my development. I might also come up with another solution for our Obsidian users to write with ease.

I won't close this issue, and if there are any breakthroughs, I will update it.

Have a day as amazing as you are :)

**Comment by jmooring** [comment]
GitHub's implementation is OK if you speak English. But for the rest of the planet, not so much.

Using English words in the callout designator (e.g., `[!NOTE]`)  is fine, but the _rendered_ callout type is always English. For example:

```text
> [!NOTE]  
> Das ist meine Notiz.
```

> [!NOTE]  
> Das ist meine Notiz.

The above is just... rude.

We could support this monolignual syntax with a Goldmark extension, or (preferably) provide multilingual support via a blockquote render hook. 

The blockquote render hook would parse the first line, looking for a callout designator (e.g., `[!something]`), and provide this context to the render hook template:

- `.Text` -- The blockquote text.
- `.PlainText` -- The blockquote text as plain text.
- `.Page` -- A reference to the current page.
- `.Ordinal` -- The zero-based ordinal of the blockquote on the page.
- `.Position` -- The position of the blockquote within the page content.
- `.IsCallout` -- Returns `true` if the blockquote has a callout designator.
- `.CalloutType` -- The callout type converted to lowercase.
- `.CalloutText` -- The blockquote text, excluding the callout designator.
- `.CalloutPlainText` -- The blockquote text as plain text, excluding the callout designator.


Ordinal and position are desired but not required. The ordinal is handy for assigning element ids, and the position is handy for error reporting.  Example render hook:

```text
{{ $emojis := dict
  "caution" ":exclamation:"
  "important" ":information_source:"
  "note" ":information_source:"
  "tip" ":bulb:"
  "warning" ":information_source:"

}}

{{ if .IsCallout }}
  <blockquote class="callout callout-{{ .CalloutType }}">
    <p class="callout-heading">
      {{ transform.Emojify (index $emojis .CalloutType) }}
      {{ or (i18n .CalloutType) (title .CalloutType) }}
    </p>
    {{ .CalloutText }}
  </blockquote>
{{ else }}
  <blockquote>
    {{ .Text }}
  </blockquote>
{{ end }}
```

**Comment by yoghurtlee-thu** [comment]
Have there been any breakthroughs here? I wrote a Python script for an All-in-One regex and S3 image upload, and it works well for me for now. However, I'm still hoping for native support for GitHub alerts. Markdown syntax does have its quirks, but it's currently the most widely used format. :)

PS: My dummy Python regex
```py
alert_pattern = re.compile(r'^>\s*\[!(.*?)\]\s*\n((?:>.*\n)*)', re.MULTILINE | re.DOTALL)
def replace_alert(match):
    alert_type = match.group(1).strip()
    content = match.group(2).replace('>', '').strip()
    return f'{{{{< alert "{alert_type}" >}}}}\n{content}\n{{{{< /alert >}}}}'
    
content = alert_pattern.sub(replace_alert, content)
```

**Comment by jmooring** [comment]
I've tested both types of hooks with various scenarios, and both are working really well. I'm working on the docs now, and will probably finish by tomorrow evening.

**Comment by jakeprice-me** [comment]
I've been trying this out following the [new documentation](https://gohugo.io/render-hooks/blockquotes/#alerts) and it works great, thanks to @bep and @jmooring.

I have however noticed that the alert type's seem to be [hardcoded](
https://github.com/bep/hugo/commit/abfdb6c263cfe8e783bcb71683537d4e56131355#diff-bfcae9432cc0532f64a2cdf7f6d21301112aaf1b084cb749cbf82ba6b4558d5bR238) to only accept a few preset types (the five mentioned in GitHub's [alerts documentation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)) - which makes sense because this ticket was for exactly that!

However, it would be quite helpful if we could define additional alert types. I use Obsidian and this change is great because Obsidian does alerts the same way as GitHub, but supports a few more alert types, see [here](https://help.obsidian.md/Editing+and+formatting/Callouts#Supported%20types) for the list (stuff like info, danger etc).

Would @bep consider adding functionality to allow the user to manually define their own alert types in `config.yml`?.

**Comment by jmooring** [comment]
@jakeprice-me Please open a new issue.
