### ISSUE TITLE
Suggestion: front matter field: Retired

### ISSUE THREAD

**Issue by mok0** [gohugoio/hugo#12592]
I would like to suggest a front matter field that signifies that the content is retired. It should function like the "drafts = true" field, but instead is used to retire old and no longer relevant articles, that you want to keep anyway, and perhaps have a special way to display. Yes it is possible to (mis)use the drafts = true field, but that is exactly that, misuse.

**Comment by jmooring** [comment]
Set the expiry date to now.

```text
expiryDate = "2024-06-11"
```

**Comment by bep** [comment]
expiryDate supports this, we will not add another.
