### ISSUE TITLE
Accommodate recent change to Goldmark's strikethrough extension

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12597]
<https://github.com/yuin/goldmark/pull/455>

Prior to this change in [v1.7.2](https://github.com/yuin/goldmark/releases/tag/v1.7.2), Goldmark's strikethrough extension was triggered by wrapping text within a pair of double-tildes:

```text
~~deleted~~
```

This behavior was compatible with Hugo's [extras](https://github.com/gohugoio/hugo-goldmark-extensions?tab=readme-ov-file#extras-extension) extension, so you could use strikethrough and subscripts at the same time:

```text
~~deleted~~
H~2~O
```

Goldmark's strikethrough extension is now triggered by either single- or double-tildes:

```text
~~deleted~~
~deleted~
```

That means you can no longer use use strikethrough and subscripts at the same time.

Possible solutions:

1. Look at prioritization, though initial review by @bowman2001 was not promising
2. Implement a double-tilde strikethrough feature in the extras extension, and use this feature instead of Goldmark's strikethrough extension when subscripts are enabled (or some similar mechanism)

Regardless of the subscript conflict, the Goldmark change is a breaking change.

**Comment by bowman2001** [comment]
About the suggested prioritization: There already was a unit test case to check the compatibility and coexistence of subscript and strike-through for an expression with mixed usage. And I just added another one with a simple strike-through. For now, they are both fine.

When I raise the priority of subscript above strike-through (locally), they both fail (as expected).

**Comment by bowman2001** [comment]
With the current prioritization, both tests pass. 

They will fail if the priority of subscript is raised above strike-through. (Tested locally)

**Comment by jmooring** [comment]
Putting aside the configuration settings for a moment, this is how I think it should work:

1. With a fresh Hugo install, both single- and double-tilde strikethrough should be enabled
2. As soon as you enable subscripts, anything wrapped in single-tildes is a subscript

Assuming we have to add strikethrough to the extras extension, the default config should be:

```text
[markup.goldmark.extensions.extras.striekthrough]
enable = true
```

Which leaves us with this to figure out:

```
[markup.goldmark.extensions]
strikethrough = true/false
```

I suspect that very few users have disabled strikethrough... I can't remember seeing it. So the easiest approach would be to completely remove the above, and note the breaking change if they currently have strikethrough disabled.

**Comment by bowman2001** [comment]
I could implement a new strike-through extension which includes the subscript without the configuration switch for a start. I am currently occupied and won't be able to finish this before the middle of the next month. But this is important to me and I would be happy to contribute.

**Comment by jmooring** [comment]
Just in case there are other near-term upstream bug fixes, I'd rather not wait, so perhaps we can do this in phases.

#### Phase 1

Remove the Goldmark "strikethrough" extension and create an extras "delete" (different name to avoid confusion) extension that _only_ handles double-tildes. This would allow us to bump to Goldmark v1.7.2 without losing current capabilities.

There's some added complexity here because we also use the Goldmark "strikethrough" extension when rendering TOC entries.

#### Phase 2

Make the "delete" extension handle single-tildes if "subscript" is not enabled. This would give us full GFM compatibility, but in my view there's no rush for this. The primary objective should be to maintain current behavior if we bump to Goldmark v1.7.2.

**Comment by bowman2001** [comment]
I already have an implementation of the new delete extension which mimics the behavior of strike-through in the last version 1.7.1 of Goldmark. 

But the new test case in 1.7.2 does complicate things a little, because there is a corresponding change in the strike-through parser to exclude the rendering of more than 2 markup characters like `~~~`. Because we use the same parser for all extra inline tags, this would also affect edge cases like `+++`, `===`, `++++`, and `====`.

I think, that we can adopt this change, because I can't imagine that anyone wants to use `+++insertion++` to produce `<ins>+insertion</ins> or similar cases with `===`. And nested inline tags like `<del><del>doubly deleted</del></del>` which are possible at the moment don't make any sense. 

There is one reasonable edge case which can **not** be implemented with the current approach in phase 1: To use something like `~~CO~2~~~` to produce `<del>CO<sub>2</sub></del>` is reasonable but won't work.

What's your opinion on this?

**Comment by jmooring** [comment]
First, thank you very much for the rapid response. 

Second, please submit a PR to the [hugo-goldmark-extensions](https://github.com/gohugoio/hugo-goldmark-extensions) repository. Although I think I understand what you've described above, I'd like to take it for a spin to be sure.

Third, how we handle this on the Hugo side is probably the tricky part, and I've been giving this more thought. If we assume that only 5% of all sites enable the subscript feature, it would probably be best for the other 95% to continue to use the official Goldmark strikethrough extension instead of the extras extension delete feature. Options:

1\) Handle this with documentation.

> If you enable the extras extension subscript feature you must disable the Goldmark strikethrough extension. To support both subscript and strikethrough, enable the extras extension "delete" feature.

2\) Make the above happen automatically. While this sounds good, I'm afraid we'll end up with some spaghetti code. The additional complexity may not make sense given my 5% usage estimate above.

I inclined to handle this with documentation, at least for now. We can always revisit this in the future.

**Comment by bep** [comment]
>I'm inclined to handle this with documentation, at least for now. We can always revisit this in the future.

Agree.
