### ISSUE TITLE
GoLang v1.22 and Hugo Windows 7 / Server 2008 compatibility post v0.121.0?

### ISSUE THREAD

**Issue by Darthagnon** [gohugoio/hugo#12593]
What version of GoLang is required to build Hugo? [GoLang v1.21.5 breaks compatibility with Windows 7 / Server 2008](https://github.com/golang/go/issues/64622), assuming they don't have [VxKex](https://github.com/golang/go/issues/52188) installed.
- [go.mod currently seems to list v1.20](https://github.com/gohugoio/hugo/blob/7ee36b3718790f1dc4a2722f925acc6e3fd3caea/go.mod)
-  [the release notes for v0.121.1](https://github.com/gohugoio/hugo/releases/tag/v0.121.1) mention a GoLang version bump to v1.21.5 in [this commit](https://github.com/gohugoio/hugo/commit/eb9f1eb657e6782cb3ed13203a58d91adf185640)
- [the tests file still tests vs. GoLang v1.21.x](https://github.com/gohugoio/hugo/blob/7ee36b3718790f1dc4a2722f925acc6e3fd3caea/.github/workflows/test.yml)

This suggests [Hugo v0.121.0](https://github.com/gohugoio/hugo/releases/tag/v0.121.0) is the last version to work unmodified on vanilla Win7, but it is a bit unclear from reading the code.

As long as it is still possible to build Hugo with Go v1.21.4, it can work on Windows 7 (and by extension, Windows 8, 8.1, and older Windows 10)

**Comment by jmooring** [comment]
Hugo v0.121.1 and later require at least Windows 10 or Windows Server 2016.

Starting with 1.21, Go requires at least Windows 10 or Windows Server 2016.

**Comment by bep** [comment]
>As long as it is still possible to build Hugo with Go v1.21.4

That is still possible, but that may not last very long. We (normally) have a "last 2 Go versions" policy, so when Go 1.23 is out, we will start using potentially breaking 1.22 API.
