### ISSUE TITLE
Replace the Google Analytics internal template with Google Tag one.

### ISSUE THREAD

**Issue by bryndin** [gohugoio/hugo#12613]
## Replace the Google Analytics internal template with Google Tag one.

Hugo has the internal GA template, see
Docs: https://gohugo.io/templates/embedded/#google-analytics
Template: https://github.com/gohugoio/hugo/blob/478a9107a68aeb5dac9ea0cec0a347fadb708b64/tpl/tplimpl/embedded/templates/google_analytics.html

Google has Google tags that containerize handling of GA, Facebook Pixel, etc. under the same umbrella. It can replace the custom GA-specific code.

![image](https://github.com/gohugoio/hugo/assets/1129396/6c2b346f-2af4-4eca-be9f-1900f5f4d92a)

**Comment by jmooring** [comment]
We are not going to remove the existing GA template, and if site/theme authors want to use GTM they can create their own partials.

cc: @chalin
