### ISSUE TITLE
Making User Experience Easier

### ISSUE THREAD

**Issue by sidratulmuntahasara** [gohugoio/hugo#12614]
Hola!

I believe we can make Hugo Experience much more easier with easy navigation, as many stuffs gets confusing, especially when it comes to installations and choosing between the Standard and Extended Versions. 
- Not many will have time to sit and read through your pages, looking up for ideas
- People love getting spoon-fed
Henceforth, I suggest making a few changes that could make an easier navigations and their go-to page for help!

Moreover I'd suggest having more cooler templates at Hugo! People don't want the same reused, old, WordPress style static templates.

**Comment by bep** [comment]
>I suggest making a few changes that could make an easier navigations and their go-to page for help!

I don't see any concrete suggestions in the above, but I suspect they fit better at https://github.com/gohugoio/hugoDocs/issues
