### ISSUE TITLE
Error in Hugo Server Build: Nil Pointer Evaluation in Template Partial

### ISSUE THREAD

**Issue by dxvidparham** [gohugoio/hugo#12637]
When running **hugo server -w**, I encountered an error during site build related to a template rendering issue. The specific error message was:

`Error: error building site: render: failed to render pages: render of "home" failed: "/home/dxvidparham/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.5.0/layouts/index.html:52:18": execute of template failed: template: index.html:52:18: executing "index.html" at <partial .section.template .>: error calling partial: "/home/dxvidparham/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.5.0/layouts/partials/sections/skills.html:17:11": execute of template failed: template: partials/sections/skills.html:17:11: executing "partials/sections/skills.html" at <partial "cards/skill.html" .>: error calling partial: "/home/dxvidparham/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.5.0/layouts/partials/cards/skill.html:8:29": execute of template failed: template: partials/cards/skill.html:8:29: executing "partials/cards/skill.html" at <$logoImage.MediaType.SubType>: nil pointer evaluating resource.Resource.MediaType`

To mitigate this issue locally, I made the following modification to /home/dxvidparham/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.5.0/layouts/partials/cards/skill.html at line 8:

```
<div class="col-xs-12 col-sm-6 col-lg-4 pt-2">
  <a class="text-decoration-none" {{ if .url }}href="{{ .url }}" title="{{ .name }}" target="_blank" rel="noopener"{{ end }}>
    <div class="card">
      <div class="card-head d-flex">
        {{ if .logo }}
          {{ $logoImage := resources.Get .logo }}
          {{ if and $logoImage $logoImage.MediaType }}
            {{ if ne $logoImage.MediaType.SubType "svg" }}
              {{ $logoImage = $logoImage.Fit "24x24" }}
            {{ end }}
            <img class="card-img-xs" src="{{ $logoImage.RelPermalink }}" alt="{{ .name }}" />
          {{ end }}
          <h5 class="card-title">{{ .name }}</h5>
        {{ else if .icon }}
          {{ $iconName := .icon }}
          <h5 class="card-title"><span class="{{ $iconName }}"> {{ .name }}</span></h5>
        {{ else }}
          <h5 class="card-title">{{ .name }}</h5>
        {{ end }}
      </div>
      <div class="card-body">
        <p class="card-text">{{ .summary | markdownify }}</p>
      </div>
    </div>
  </a>
</div>
```

This local modification is effective only until the cache is cleared using hugo mod clean. However, the issue persists during deployment, indicating a need for a more permanent solution, possibly requiring a bug fix.

**Hugo Version: _hugo v0.128.1-0ff542b4b9cc7b5cb425bbab8bdb5aace81d0c03+extended linux/amd64 BuildDate=2024-07-02T06:46:41Z VendorInfo=gohugoio_**

**Comment by bep** [comment]
This is not something we can handle in Hugo. You need to verify that the resource exists before using it e.g.

```handlebars
{{ with resources.Get .logo }}
{{ $resized := .Fit "24x24" }}
{{ end }}
````
