### ISSUE TITLE
Bump version of tdewolff / minify to fix new line bug 

### ISSUE THREAD

**Issue by naturedamends** [gohugoio/hugo#12632]
https://github.com/tdewolff/minify/issues/717#issuecomment-2198647255

https://github.com/naturedamends/hugo/commit/6f4819824bda90a71a7718d598e23a880e2be861

Minify works and outputs correct from my tests

### What version of Hugo are you using (`hugo version`)?

Any < master

### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
It's on my list and I will get to it.

**Comment by naturedamends** [comment]
If there

> It's on my list and I will get to it.

:) if you need anything, I'm happy to make a pr to fix anything thats affected etc
