### ISSUE TITLE
Using non-2006 year in date format breaks output

### ISSUE THREAD

**Issue by bryndin** [gohugoio/hugo#12630]
When date formatting uses a year other than the magic "2006" the output breaks.

e.g. this
`<span class="date">{{ .Date.Format "2006/01/02" }} {{ .Date.Format "2005/01/02" }}</span>`

becomes this
`2024/06/27 27018/06/27`

note that "2005", or any other year than "2006" messes up the output.

### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
hugo v0.128.0-e6d2712ee062321dc2fc49e963597dd5a6157660+extended linux/amd64 BuildDate=2024-06-25T16:15:48Z VendorInfo=snap:0.128.0
</pre>

### Does this issue reproduce with the latest release?
yes

**Comment by jmooring** [comment]
This is not a bug. It's doing exactly what you are telling it to do. See <https://pkg.go.dev/time#pkg-constants>.

```text
{{ $t := "2024-06-29T03:46:53-07:00" | time.AsTime }}
{{ $t.Format "2005" }} → 29053
```

`2` => day of the month = 29
`0` => literal = 0
`05` => seconds = 53
