### ISSUE TITLE
YAML format not set in front matter

### ISSUE THREAD

**Issue by kfilipan** [gohugoio/hugo#12666]
When creating new site with YAML format, `default.md` stays with TOML front matter and vice versa. I have pinpointed the problems to changes between versions v0.117.0 and v0.118.0. The comparison was done using Scoop on Windows for both `-f` and `--format` flags. Also, the same is still present in v0.129.0: creation using `--format "yaml"` does not include front matter of `archetypes\default.md` in YAML.

[comp-v0.117.0-v0.118.0-f.log](https://github.com/user-attachments/files/16310656/comp-f.log)
[comp-v0.117.0-v0.118.0--format.log](https://github.com/user-attachments/files/16310657/comp--format.log)
[v0.129.0--format.log](https://github.com/user-attachments/files/16310664/v0.129.0--format.log)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ v0.117.0
$ v0.118.0
$ v0.129.0

</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by yaardie** [comment]
The same applies to the JSON Format.

**Comment by bep** [comment]
We reimplemented the `new site` command (I guess v0.118.0). I have checked and we now use the `--format` flag only for the config file, the rest is simple file copy.
