### ISSUE TITLE
exif: Warning when GPS lat/long not set

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12669]
> WARN  images: "/images/a.jpg": GPSLatitude: failed to convert degrees to decimal: unsupported degree type []uint8

```text
git clone --single-branch -b hugo-github-issue-12669 https://github.com/jmooring/hugo-testing hugo-github-issue-12669
cd hugo-github-issue-12669
hugo server
```

**Comment by bep** [comment]
Thanks for this; I have updated the upstream test suite to panic on warnings (which would have discovered the above issue).
