### ISSUE TITLE
`--watch` not working with helix-editor

### ISSUE THREAD

**Issue by urbantrout** [gohugoio/hugo#12677]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.129.0+extended darwin/amd64 BuildDate=2024-07-17T13:29:16Z VendorInfo=brew
</pre>

### Steps to reproduce:
1. Run `hugo server` or `hugo --watch`
2. Change files in [Helix](https://helix-editor.com/)

### Expected result
Hugo reacts to file changes and rebuilds pages

### Actual result
Hugo reacts to file changes and builds pages, but not all of them and the output is the same as the one without the changes.

This only happens in [Helix editor](https://helix-editor.com/). In `vim` everything works as expected.

**Comment by bep** [comment]
Could you try to run

```
hugo server --logLevel info
```

And note the lines with `livereload` in them when you change something.

You could also try `hugo server --poll 1s`. If that works, the Helix must doing some non-standard way of saving files that does not trigger the expected fs events.

**Comment by urbantrout** [comment]
This is the output with `--logLevel info`

```
Change detected, rebuilding site (#1).
2024-07-25 16:35:34.441 +0200
Template added /_default/baseof.htmlc3gzwd.bck
Template added /_default/baseof.html
INFO  build:  step process substep resolve content adapter change set changes 2 checked 2 matches 0 duration 36.901µs
INFO  build:  step process substep resolve page output change set changes 2 checked 448 matches 0 duration 3.843363ms
INFO  build:  step process substep gc dynacache duration 196.695µs
INFO  build:  step process substep rebuild templates duration 8.210313ms
INFO  build:  step process duration 13.327644ms
INFO  build:  step assemble duration 777ns
INFO  build:  step render substep pages site de outputFormat html duration 20.021809ms
INFO  build:  step render pages 0 content 0 duration 20.075914ms
INFO  build:  step render deferred count 0 duration 917ns
INFO  build:  step postProcess duration 9.17µs
INFO  build:  duration 33.51625ms
Web Server is available at http://localhost:1313/ (bind address 0.0.0.0)
Total in 33 ms
INFO  livereload: build changed 0 files
```

**Comment by urbantrout** [comment]
adding `--poll 1s` fixes the issue.

**Comment by urbantrout** [comment]
This is not a hugo issue but a helix issue.

**Comment by bep** [comment]
>This is not a hugo issue but a helix issue.

Well, that's debatable.

Looking at these 2 lines:

```
Template added /_default/baseof.htmlc3gzwd.bck
Template added /_default/baseof.html
```

I'm guessing that the above is hinting at the problem; I suspect that Helix saves to a temp file and then renames it, nos sure.

**Comment by urbantrout** [comment]
> Well, that's debatable.

**Comment by David-Else** [comment]
> adding `--poll 1s` fixes the issue.

I just spent the day tearing my hair out trying to solve this problem, and this solved it! Maybe there is some better way to deal with this long term than adding `--poll 1s`?

**Comment by kirawi** [comment]
> > This is not a hugo issue but a helix issue.
> 
> Well, that's debatable.
> 
> Looking at these 2 lines:
> 
> ```
> Template added /_default/baseof.htmlc3gzwd.bck
> Template added /_default/baseof.html
> ```
> 
> I'm guessing that the above is hinting at the problem; I suspect that Helix saves to a temp file and then renames it, not sure.

I'd be surprised if this was the issue. Vim does the same thing.

**Comment by jmooring** [comment]
@kirawi We have a few exclusions related to vim, but nothing for .bck files.

https://github.com/gohugoio/hugo/blob/e1becf1dfe31bec65eca585ac66a2d10f1651e42/commands/hugobuilder.go#L779-L794
