### ISSUE TITLE
The development environment is normal, the production environment is blank.

### ISSUE THREAD

**Issue by phantasy36** [gohugoio/hugo#12676]
### What version of Hugo are you using (`hugo version`)?

When can the official Docker image be released? Currently, the Kalkegg's Docker Hub image is one year old, and I am using the one in my NAS; however, the image is at version 0.129.0 in Docker Hub. Since using the Docker Hub image:

Windows 11: Running hugo server through the command on the taskbar and going to localhost:1313 works normally.
My NAS: Going to the IP address of the NAS through 1313: and it shows a blank screen with nothing (Every time I update the content on the NAS, the hugo Docker container is restarted.)

Problem:

Running hugo server through the command on the taskbar works on Windows 11.
When going to localhost:1313 on the NAS, it shows a blank screen with nothing (Every time I update the content on the NAS, the hugo Docker container is restarted.)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
