### ISSUE TITLE
hugo replace "anatomy" menu entry to "Anatomies"

### ISSUE THREAD

**Issue by lither-s** [gohugoio/hugo#12684]
hugo version: v0.129.0

When i define menu entry automatically my "anatomy" folder shows like "Anatomies". Even when i define menu name in site configuration i still can see "Anatomies" as title when i open this menu.
Tested with different themes and different systems server-side and user-side.

**Comment by yaardie** [comment]
Set this to false in your config file https://gohugo.io/getting-started/configuration/#pluralizelisttitles

In future, I suggest you use https://discourse.gohugo.io/ for questions/troubleshooting.
