### ISSUE TITLE
EXIF FNumber is printed in an unexpected form

### ISSUE THREAD

**Issue by Fethbita** [gohugoio/hugo#12718]
When using the following shortcode:
```
  {{ range $index, $image := (sort (resources.Match (.Get 0)) "Exif.Date" "desc") }}
    <figure>
    <img src="{{ $image.RelPermalink }}" alt="{{ $image.Exif.Tags.ImageDescription }}">
    {{ $image_properties := printf "%s sec, f/%s, ISO %d"  $image.Exif.Tags.ExposureTime $image.Exif.Tags.FNumber $image.Exif.Tags.ISO }}
    <figcaption>{{ $image_properties }}</figcaption>
    </figure>
  {{ end }}
```
The result is unexpected. For FNumber 3.6, 18/5 is shown:
<img width="726" alt="image" src="https://github.com/user-attachments/assets/4a3e3145-896b-4865-bed6-8b4560040140">

If the FNumber is printed with format string `%f`, the following appears instead:
```
1/2000 sec, f/&{%!f(uint32=18) %!f(uint32=5)}, ISO 160
```

I think it might be related to #12651.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.131.0+extended
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
Thanks for the report. I will try to improve the `printf` support for the `rat` type in the new [imagemeta](https://github.com/bep/imagemeta) library.

What you can try as a workaround is something like:

```
$f := $image.Exif.Tags.FNumber.Float64
// ... format it with %f
```

**Comment by Fethbita** [comment]
Yup, the workaround works:
```
    {{ $aperture := $image.Exif.Tags.FNumber.Float64 }}
    {{ $image_properties := printf "%s sec, f/%.1f, ISO %d"  $image.Exif.Tags.ExposureTime $aperture $image.Exif.Tags.ISO }}
```

Thank you for the quick response.
