### ISSUE TITLE
Each multi-language post internal assets are missing in the build result

### ISSUE THREAD

**Issue by mu-hun** [gohugoio/hugo#12726]
As discussed in the https://github.com/planetarium/snack.planetarium.dev/issues/186 (referred issuse is in korean, so please use a translator to check), there is a missing assets to build target between 0.88 to latest version in a multilang setup like below posts structure.

```
➜  snack.planetarium.dev git:(main) tree content/posts/2020/10/decentralized-and-online-game-intersect
content/posts/2020/10/decentralized-and-online-game-intersect
├── images
│   ├── bug-report.png
│   ├── orphaned-block.png
│   ├── orphaned-blocks.png
│   └── single-chain.png
├── index.eng.md
└── index.kor.md
```

The image asset path `posts/*/**/<post-name>/images` for each individual post is missing from the build target.

## Temporary workaround

However, when I inserted the empty `index.md` file in each post folder, the image assets were properly included in the build target.

My guess is that the post internal asset (ex `content/posts/*/*.{ png,css,.. etc}`) inclusion algorithm seems to have been changed to work with only `index.md` as main post independent of multi-languages markdown document tracking.

```diff
content/posts/2020/10/decentralized-and-online-game-intersect
+ ├── index.md
├── index.eng.md
└── index.kor.md
```

### Does this issue reproduce with the latest release?

Yes. discovered while upgrading from version 0.88 to 0.123.

**Comment by bep** [comment]
>My guess is that the post internal asset (ex content/posts/*/*.{ png,css,.. etc}) inclusion algorithm seems to have been changed to work with only index.md as main post independent of multi-languages markdown document tracking.

I'm taking this from memory, but the gist of it is:

* In v0.123.0 we simplified this logic to pave the way for content from other data sources (now: content adapters)
* See https://github.com/gohugoio/hugo/releases/tag/v0.123.0
* In your case, I guess it's: https://github.com/gohugoio/hugo/issues/11455
* I don't have access to your site source, so I'm not exactly sure what's happening in your case, but please don't expect me to dig into some external discussions in Korean.

**Comment by mu-hun** [comment]
Thank you for the helpful information.

> I don't have access to your site source, so I'm not exactly sure what's happening in your case, but please don't expect me to dig into some external discussions in Korean.

I apologize if I've been unkind or made you tiring of understanding the additional context. I meant to mention that it's open source with the same repository URL as the discussion: https://github.com/planetarium/snack.planetarium.dev.

**Comment by bep** [comment]
Your default content language is `mis` -- which is where your bundled resources without any language gets attached. The behaviour you describe is as I outline above, and as expected.

**Comment by FarisZR** [comment]
I honestly find the new behavior a bit weird, if an asset isn't tagged for a specific language, it should be available to all languages.

**Comment by jmooring** [comment]
See bep's comments above. More information here:
<https://gohugo.io/content-management/page-resources/#multilingual>
