### ISSUE TITLE
New EXIF library returns an image orientation that doesn't pass (eq $o 6)

### ISSUE THREAD

**Issue by snicolai-blog** [gohugoio/hugo#12733]
I have the following fragment in a render-image.html file to set aspect ratios on images.  This works in hugo prior to the new EXIF library.

```
{{- /* get file that matches the filename as specified as src="" in shortcode */ -}}
{{- $src := .Page.Resources.GetMatch (printf "%s" (.Destination)) -}}
{{- $imgPath := .Destination -}}
{{- if $src -}}

{{- $imgWidth := $src.Width -}}
{{- $imgHeight := $src.Height -}}
{{- with $src.Exif -}}
  {{- $o :=  .Tags.Orientation -}}
  {{- warnf (printf "%s orientation %d width %d height %d" $imgPath $o $imgWidth $imgHeight) }}
  {{- if (or (eq $o 6) (eq $o 8)) -}}
    {{- $imgWidth = $src.Height -}}
    {{- $imgHeight = $src.Width -}}
    {{- warnf "flipping width and height" -}}
  {{- end -}}
{{- end -}}
```

The warnings print out the orientation properly in 0.131, but the eq $o 6 test fails and so the aspect ratio on my image is wrong.  Here are some example warnings where it doesn't flip an image.

```
WARN  birguentrance.jpg orientation 6 width 6960 height 4640
WARN  victoriagate.jpg orientation 1 width 5161 height 4167
```

In hugo 0.131 I have to use the following to get it to work.  It looks like the type returned by .Orientation isn't the same type as before and now fails the eq test.  Converting to a string with printf and comparing strings works in 0.131 and newer.

```
{{- /* get file that matches the filename as specified as src="" in shortcode */ -}}
{{- $src := .Page.Resources.GetMatch (printf "%s" (.Destination)) -}}
{{- $imgPath := .Destination -}}
{{- if $src -}}

{{- $imgWidth := $src.Width -}}
{{- $imgHeight := $src.Height -}}
{{- with $src.Exif -}}
  {{- $o := (printf "%d" .Tags.Orientation) -}}
  {{- warnf (printf "%s orientation %d width %d height %d" $imgPath $o $imgWidth $imgHeight) }}
  {{- if (or (eq $o "6") (eq $o "8")) -}}
    {{- $imgWidth = $src.Height -}}
    {{- $imgHeight = $src.Width -}}
    {{- warnf "flipping width and height" -}}
  {{- end -}}
{{- end -}}
```

These are the example warnings from this changed code that properly flips the aspect ratio:

```
WARN  birguentrance.jpg orientation %!!(MISSING)d(string=6) width 6960 height 4640
WARN  flipping width and height
WARN  victoriagate.jpg orientation %!!(MISSING)d(string=1) width 5161 height 4167
```

What I want is for the same template to work in both systems.  Either document the changes I need to make to my templates to support both types (preferably in the release that breaks it).  Or fix the new library to return types that are compatible with my existing template.

**Comment by bep** [comment]
I think you can work around this by:

```
 {{- $o :=  .Tags.Orientation | int -}}
```

A note mostly to myself here:

* In my new library, I have kept the int data types as dictated by their length, e.g. 2 bytes integer => `int16`.
* I have not checked, but I'm guessing the `eq` function considers `eq int16(6) 6` to be falsy, which smells like a bug in itself.

It's tempting to just change the EXIF types to `int`, but that can lead to overflow issues, which is also not great.

**Comment by snicolai-blog** [comment]
```
 {{- $o :=  .Tags.Orientation | int -}}
```

Works in 0.131, and I haven't tested it in versions prior to 0.130 yet, but I suspect that works there as well.  

My hosting provider that runs hugo doesn't let me control when hugo is upgraded, so I need to support the older hugo version till they upgrade with my templates, but like to test with the newest version so I can see what changes I'll need in the future.

I agree that the proper fix is to fix the comparisons so that eq int16(6) 6 is true for the appropriate operators and types.

**Comment by bep** [comment]
> {{- $o :=  .Tags.Orientation | int -}}

The above should work with "all" Hugo versions (including future).

>eq int16(6) 6

I have checked, and the failing case was `eq uint(6) 6`.
