### ISSUE TITLE
spam report

### ISSUE THREAD

**Issue by qzzhoulu** [gohugoio/hugo#12760]
It was found that the sauroter.de website was used to send phishing emails. Hugo was used on the website. Is there a vulnerability? Please help to investigate.

Sender: srs0=ptka=pn=mail.sauroter.de=dgqdkrozzb@sauroter.de
Subject: 1723600494
Nickname: 1723600494
Time: Wed, 14 Aug 2024 01:48:54 +0000 (UTC)

**Comment by bep** [comment]
>Hugo was used on the website. Is there a vulnerability?

Hugo produces static files (HTML) and cannot not send mail.
