### ISSUE TITLE
Can't upgrade with winget upgrade

### ISSUE THREAD

**Issue by jonsagara** [gohugoio/hugo#12773]
For the past few releases, I have been unable to upgrade hugo with `winget upgrade`, but I can make the upgrade work by using `winget install` instead.

With hugo 0.132.1 installed, I ran the `winget upgrade` command and got the following result:

```
> winget upgrade Hugo.Hugo.Extended
No installed package found matching input criteria.
```

So I ran `winget install` instead, which "upgraded" to 0.132.2:

```
> winget install Hugo.Hugo.Extended
Found Hugo (Extended) [Hugo.Hugo.Extended] Version 0.132.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/gohugoio/hugo/releases/download/v0.132.2/hugo_extended_0.132.2_windows-amd64.zip
  ██████████████████████████████  24.2 MB / 24.2 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "hugo"
Successfully installed
```

Which I verified with `hugo version`:

```
> hugo version
hugo v0.132.2-3fd26c70dff5934ec1802b9563530130ed1bca75+extended windows/amd64 BuildDate=2024-08-14T16:17:21Z VendorInfo=gohugoio
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.132.1
</pre>

### Does this issue reproduce with the latest release?

Yes

### Environment
OS: Windows 11 Version 23H2 (OS Build 22631.4037)
PowerShell 7.4.4
Windows Terminal 1.20.11781.0
winget: v1.8.1911

**Comment by jmooring** [comment]
The Hugo project does not maintain or support the Hugo winget package, which resides here:
<https://github.com/microsoft/winget-pkgs/tree/master/manifests/h/Hugo/Hugo>

Please log an issue here:
<https://github.com/microsoft/winget-pkgs/issues>

**Comment by jonsagara** [comment]
Thank you.

For the curious, here's the issue I created over there: https://github.com/microsoft/winget-pkgs/issues/167845
