### ISSUE TITLE
panic related to translationKey and page resources

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12795]
> panic: interface conversion: *hugolib.pageState is not resource.NameNormalizedProvider: missing method NameNormalized

The panic occurs with [v0.123.4](https://github.com/gohugoio/hugo/releases/tag/v0.123.4) and later, and seems to be triggered (at least in part) by the translationKey field in front matter.

Reproducible example:

```text
git clone --single-branch -b hugo-forum-topic-51282 https://github.com/jmooring/hugo-testing hugo-forum-topic-51282
cd hugo-forum-topic-51282
hugo
```

Reference: <https://discourse.gohugo.io/t/51282>

**Comment by Clickadelic** [comment]
Thanks a lot.
