### ISSUE TITLE
Live reload broken on everything apart from the content directory

### ISSUE THREAD

**Issue by David-Else** [gohugoio/hugo#12794]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.133.0-c9777473d1369f812d727a6c07dc57ad7be7bf62+extended linux/amd64 BuildDate=2024-08-17T19:57:41Z VendorInfo=gohugoio

</pre>

### Does this issue reproduce with the latest release?

Yes, and also in v0.128.2

I have tried `hugo server` and `hugo server --disableFastRender`.

I have created a site using the new built in default theme and modified it a bit. When I change any of my markdown in the content folder it updates at once. When I change something in the layouts i need to press f5 to see the change. When I update something in the partials dir nothing changes AND I need to stop and start the server to see a change.

I have made a repo for you to test the bug https://github.com/David-Else/hugo-bugtest

As an example, run `hugo server` and try to edit any text in `partials/footer.html`. Not even an `f5` will show the changes, but hugo server says:

```sh
Change detected, rebuilding site (#1).
2024-08-24 17:17:12.127 +0100
Template added /partials/footer.htmlknvcsd.bck
Template added /partials/footer.html
Web Server is available at http://localhost:42589/ (bind address 127.0.0.1)
Total in 7 ms
```

I have tried to integrate tailwind in a very basic way, but I don't think that has anything to do with this problem as it is not just styles that are not updating, but text from the HTML templates. Thanks!

**Comment by jmooring** [comment]
I noticed you have a directory content/mastering-the-helix-editor-udemy-course.

Are you using helix editor when testing? If yes, see:
<https://github.com/gohugoio/hugo/issues/12677>

Specifically, this comment:
<https://github.com/gohugoio/hugo/issues/12677#issuecomment-2250516982>

**Comment by David-Else** [comment]
@jmooring Thanks!! Amazing, that was the problem. I will reply in the other thread and close this.
