### ISSUE TITLE
Extend blockquote alerts to support Obsidian types

### ISSUE THREAD

**Issue by jakeprice-me** [gohugoio/hugo#12801]
I've been trying out the new GitHub style alerts from #12590. Following the [new documentation](https://gohugo.io/render-hooks/blockquotes/#alerts) the alerts work great, thanks to @bep and @jmooring.

I have however noticed that the alert type's seem to be [hardcoded](
https://github.com/bep/hugo/commit/abfdb6c263cfe8e783bcb71683537d4e56131355#diff-bfcae9432cc0532f64a2cdf7f6d21301112aaf1b084cb749cbf82ba6b4558d5bR238) to only accept a few preset types (the five mentioned in GitHub's [alerts documentation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)) - which makes sense because this ticket was for exactly that!

It would be quite helpful if we could define additional alert types. I use Obsidian and this change is great because Obsidian does alerts the same way as GitHub, but supports a few more alert types, see [here](https://help.obsidian.md/Editing+and+formatting/Callouts#Supported%20types) for the list (stuff like info, danger etc).

Would @bep consider adding functionality to allow the user to manually define their own alert types in `config.yml`?

**Comment by bep** [comment]
This is the regexp in question:

```
(?i)^<p>\[!(NOTE|TIP|WARNING|IMPORTANT|CAUTION)\]
```

We HTML context here is _the start of a blockquote in a render hook_, so I suspect it would be more than specific enough if we made it slightly less specific...

/cc @jmooring

**Comment by bep** [comment]
Can you take a look at #12815 and see if that works for you?
