### ISSUE TITLE
8-Character Limit for Language Names in i18n/

### ISSUE THREAD

**Issue by matypist** [gohugoio/hugo#12814]
An error makes it impossible to create a language with a name longer than 8 characters, an error that occurs when trying to create a file with a name longer than 8 characters in `i18n/`:

```
Start building sites … 
hugo v0.133.1+extended linux/amd64 BuildDate=unknown

Total in 30 ms
Error: error building site: "art-x-123456789": language: tag is not well-formed
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.133.1+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
<https://gohugo.io/functions/lang/translate/#translation-tables>

> Private use subtags must not exceed 8 alphanumeric characters.

**Comment by matypist** [comment]
> [gohugo.io/functions/lang/translate#translation-tables](https://gohugo.io/functions/lang/translate/#translation-tables)
> 
> > Private use subtags must not exceed 8 alphanumeric characters.

Adding a key to set a custom path for each language would be very useful then 🙏

**Use case:** We are working on a website for students at Sapienza University of Rome, and we are using languages as versions, one for each degree program. Therefore, we would like to have https://sapienzastudents.net/computerscience/ for the Computer Science Master's Degree version of the website, instead of the current https://sapienzastudents.net/29932/, which we are using because we can't have language names longer than 8 characters.

**Comment by jmooring** [comment]
> Adding a key to set a custom path for each language

See https://github.com/gohugoio/hugo/issues/9404
