### ISSUE TITLE
I18n not possible, config files for translations not loaded correctly

### ISSUE THREAD

**Issue by wehrend** [gohugoio/hugo#12826]
when adding i18n functionality for my website, I immediately got these errors 
with my docker image frokm klakegg as well as the version locally installed

sven@kali:~/development/hugo$ hugo --verboseLog
Error: add site dependencies: load resources: loading translations: "/home/sven/development/hugo/i18n/de.yaml:1:1": failed to load translations: unsupported file format <nil>
Total in 2 ms
sven@kali:~/development/hugo$ make up
docker run  -it -v "/home/sven/development/hugo":/src -p 1313:1313 "klakegg/hugo:0.111.3-ext-asciidoctor" server  --disableFastRender --renderToDisk --verbose
Error: add site dependencies: load resources: loading translations: "/src/i18n/de.yaml:1:1": failed to load translations: unsupported file format int
make: *** [Makefile:11: up] Fehler 255
sven@kali:~/development/hugo$ hugo --debug
Error: add site dependencies: load resources: loading translations: "/home/sven/development/hugo/i18n/de.yaml:1:1": failed to load translations: unsupported file format <nil>
Total in 3 ms
sven@kali:~/development/hugo$ hugo --verbose
Error: add site dependencies: load resources: loading translations: "/home/sven/development/hugo/i18n/de.yaml:1:1": failed to load translations: unsupported file format int
Total in 2 ms

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo version
hugo v0.111.3+extended linux/amd64 BuildDate=2023-03-16T08:41:31Z VendorInfo=debian:0.111.3-1

### Does this issue reproduce with the latest release?
no tested yet 

And this is what the file looks like:

params:
baseURL: "http://wehrend.uber.space/"
languageCode: "en-us"
title: "Bits & pieces - Sven Wehrend"
theme: "hugo-book"

menu:
  before:
  - name: "Web-Blog"
    url: "/posts/web/"
    weight: 10

menu:
  before:
  - name: "Synth-Blog"
    url: "/tags/synth/"
    weight: 20

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. When you create a topic on the forum, make sure you provide a link to your project repository.

**Comment by wehrend** [comment]
Dear Joe,
does that mean it is fixed in the current version?
I am limited to those docker releases from klagegg, and I think 0.111.3 was
the last version there.
Should I update it...?

Best,
Sven Wehrend

**Comment by jmooring** [comment]
> does that mean

What it means is, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting.
