### ISSUE TITLE
Hugo v0.134.0 has broken the .Process method

### ISSUE THREAD

**Issue by scorpatu** [gohugoio/hugo#12821]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.134.0

</pre>

### Does this issue reproduce with the latest release?
YES

Error returned below

```
 error calling Process: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
```

[Test site](https://github.com/scorpatu/test). Check the image partial and the list file where it is called.

```
$ hugo env
hugo v0.134.0-77df7bbbff8ce6b56ed693270088de973a87d5ce linux/amd64 BuildDate=2024-09-03T09:54:22Z VendorInfo=gohugoio
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.23.0"
```

**Comment by scorpatu** [comment]
https://gohugo.io/troubleshooting/faq/#i-get-this-feature-is-not-available-in-your-current-hugo-version

**Comment by bep** [comment]
The error message could be better, but I'm guessing that you try to produce webp, and then you need the extended version of Hugo; follow the URL above and it's all explained.
