### ISSUE TITLE
Some Obsidian styled alerts result in invalid HTML

### ISSUE THREAD

**Issue by McShelby** [gohugoio/hugo#12828]
Given the following Markdown:

````md
> [!caution] Callouts can have custom titles
> Like this one.

> [!caution] Title-only callout

> [!note]- Are callouts foldable?
> Yes! In a foldable callout, the contents are hidden when the callout is collapsed

> [!note]+ Are callouts foldable?
> Yes! In a foldable callout, the contents are hidden when the callout is collapsed

> [!info] Can callouts be nested?
> > [!important] Yes!, they can.
> > > [!tip]  You can even use multiple layers of nesting.
````

and the following `render-blockquote.html`

````
{{ warnf "%s" .AlertTitle }}
````

somtimes results in a closing `</p>` at the end of the title

````
WARN  Callouts can have custom titles
WARN  Title-only callout</p>
WARN  Are callouts foldable?
WARN  You can even use multiple layers of nesting.</p>
WARN  Yes!, they can.</p>
WARN  Can callouts be nested?</p>
````

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.134.0-77df7bbbff8ce6b56ed693270088de973a87d5ce+extended windows/amd64 BuildDate=2024-09-03T09:54:22Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by LicketySpliket** [comment]
Not a super frequent contributor to Hugo, but I think the issue is in the following lines:

(blockquotes.go:162)
```go
var blockQuoteAlertRe = regexp.MustCompile(`^<p>\[!([a-zA-Z]+)\](-|\+)?[^\S\r\n]?([^\n]*)\n?`)

func resolveBlockQuoteAlert(s string) blockQuoteAlert {
	m := blockQuoteAlertRe.FindStringSubmatch(s)
	if len(m) == 4 {
		return blockQuoteAlert{
			typ:   strings.ToLower(m[1]),
			sign:  m[2],
			title: m[3],
		}
	}

	return blockQuoteAlert{}
}

```

This Regex terminates the title group at `\n`, not `</p>`, so the `</p>` gets included and passed to the renderer. I fixed it by using this Regex: `^<p>\[!([a-zA-Z]+)\](-|\+)?[^\S\r\n]?([^(\n|<\/p>)]*)\n?`. It checks for termination of the title group at both `\n` and `</p>`.

**Comment by LicketySpliket** [comment]
No worries bep, thanks for testing it.
