### ISSUE TITLE
`summaryLength` applies differently since 0.134.0

### ISSUE THREAD

**Issue by McShelby** [gohugoio/hugo#12837]
Setting a `summaryLength=10` in my `hugo.toml` does not have any effect since 0.134.0.

To test this, my page Markdown was

````md
+++
title = "Branding"
+++

The Relearn theme provides configuration options to change your site's colors, favicon and logo. This allows you to easily align your site visuals to your desired style. Most of these options are exposed through so called color variants.

A color variant lets you customize various visual effects of your site like almost any color, used fonts, color schemes of print, syntax highligtning, Mermaid and the OpenAPI shortcode, etc. It contains of a CSS file and optional configuration options in your `hugo.toml`.
````

**0.134.0**

````
The Relearn theme provides configuration options to change your site’s colors, favicon and logo. This allows you to easily align your site visuals to your desired style. Most of these options are exposed through so called color variants.
````

**0.133.1**

````
The Relearn theme provides configuration options to change your site’s colors, favicon and logo.
````

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.134.0-77df7bbbff8ce6b56ed693270088de973a87d5ce+extended windows/amd64 BuildDate=2024-09-03T09:54:22Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes. It was fine with 0.133.1

**Comment by bep** [comment]
I'm pretty sure that the title of this issue is not correct. So, the implementation is simpler: 

1. The old implementation  converted HTML to plain text, then truncated to whole sentence closest to `summaryLength`.
2. The new implementation truncates to the paragraph closest to `summaryLength`.

**Comment by McShelby** [comment]
I am okay with it, if this is desired behavior. Although a notice in the release would have been great.

I've changed the title of this issue accordingly.

**Comment by bep** [comment]
>Although a notice in the release notes would have been great.

Yea, well, this isn't my day job.

**Comment by bep** [comment]
For others reading this; there is a truncate func (https://gohugo.io/functions/strings/truncate/) that understands HTML that can be used for more ... fine grained control over the length.

**Comment by jmooring** [comment]
I've updated the documentation to reflect the behavioral change:

- <https://gohugo.io/getting-started/configuration/#summarylength>
- <https://gohugo.io/content-management/summaries/#automatic-summary>
- <https://gohugo.io/content-management/summaries/#alternative>
