### ISSUE TITLE
dartsass: Unable to resolve directory paths to directory index files

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12849]
Details: <https://discourse.gohugo.io/t/51528/15>

Applicable to Sass imported as a Hugo module, Hugo is unable to resolve directory paths to directory index files.

For example, this:

```
@use foo/bar
```

does not resolve to any of these:

- `foo/bar/_index.scss`
- `foo/bar/_index.sass`
- `foo/bar/_index.css`

This affects both `@use` and `@forward` rules. See:

https://github.com/gohugoio/hugo/blob/28f621d4a73ca7e97e23b33cbf3780ddab188d24/resources/resource_transformers/tocss/dartsass/transform.go#L137

Based on experimentation, we should resolve to a file instead of a directory when both exist with same base name:

```text
assets/
└── sass/
    ├── foo/
    │   └── _index.scss
    ├── foo.scss
    └── main.scss    <-- @use "foo";
```

In the above, we should resolve to `foo.scss` instead of `foo/_index.scss`.

**Comment by bep** [comment]
What is a "index file" and where is the spec?

**Comment by jmooring** [comment]
<https://sass-lang.com/documentation/at-rules/use/#index-files>

**Comment by jmooring** [comment]
To reiterate, the problem is limited to Sass imported as a Hugo module. If the files exist in the OS file system, directory imports work as expected.

**Comment by cooperaj** [comment]
Thanks for putting my inane forum ramblings together into a bug @jmooring.
