### ISSUE TITLE
The "Quick start" page is too succinct.

### ISSUE THREAD

**Issue by FiableDotBiz** [gohugoio/hugo#12840]
In my opinion, the "[Quick start](https://gohugo.io/getting-started/quick-start)" page is really too short. At the very least, it should be taught how to add a picture in a post, how to add a picture in the front page header, how to add a (second) post, and how to add a non-post, stable, page, so that the result look a bit like a website. Explaining there how to change a page background colour would also be appreciated.

**Comment by jmooring** [comment]
Documentation is managed in its own repository:
<https://github.com/gohugoio/hugoDocs>
