### ISSUE TITLE
Add support for acronym (ABBR) Markdown extension to Hugo

### ISSUE THREAD

**Issue by jsabater** [gohugoio/hugo#12846]
When writing technical documents, and probably other types as well, acronyms are very frequently used. HTML offers the `ABBR` tag for those, such as:

```html
<abbr title="Central Process Unit">CPU</abbr>
```

As of version 0.134.2, Hugo uses [Goldmark](https://gohugo.io/content-management/formats/#formats), a markdown parser written in Go, but the [list of enabled extensions](https://gohugo.io/getting-started/configuration-markup/#goldmark-extensions) does not include the [abbreviations extension](https://michelf.ca/projects/php-markdown/extra/#abbr) of the [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/).

According to the [documentation of Goldmark](https://github.com/yuin/goldmark), this should already be possible. Therefore I presume that the extensions coming with Hugo by default have been handpicked.

Would you consider adding the `abbr` extension of the PHP Markdown Extra package as default for Hugo or, alternatively, instructions on the documentation on how to enable more extensions? I understand something like the following on my `markup.toml` file would be the way to go:

```toml
[goldmark]
  [goldmark.extensions.extras.abbr]
    enable = true
```

I have tried both with and without the `.extras` bit without success.

Thanks in advance and congratulations for such a great software!

P.S. I found prior references to this matter in issue #7360 and on [the](https://discourse.gohugo.io/t/inclusion-of-third-party-goldmark-extensions/23540) [forums](https://discourse.gohugo.io/t/support-for-acronyms/45100).

**Comment by bep** [comment]
I don't see any link to any _Goldmark abbreviation extension_? Or do you propose we implement one in Hugo?

A note to self: I have been thinking about ways to add some _glossary_ support to Hugo, and I even did a test implementation of it (one challenge here is to make it fast). I had an idea to make these abbreviations/glossary terms link to outside definitions (technically taxonomy terms), but maybe doing the inline thing like PHP Markdown Extra could be a good first step.

@jsabater do you or anyone else (@jmooring etc.) know how portable  this syntax is?

https://michelf.ca/projects/php-markdown/extra/#abbr

GitHub doesn't support it, it seems, but it also does not render it as something else, which I guess is good.

---
Markdown Extra adds supports for abbreviations (HTML tag <abbr>). How it works is pretty simple: create an abbreviation definition like this:

*[HTML]: Hyper Text Markup Language
*[W3C]:  World Wide Web Consortium

then, elsewhere in the document, write text such as:

The HTML specification
is maintained by the W3C.

**Comment by jmooring** [comment]
> how portable

It is not natively supported by GitHub, GitLab, VS Code, Typora, or Obsidian. Alternatives that I have seen are shortcodes and link render hooks. For example:

```text
Use {{< abbr HTML >}} when writing the description.

Use [*](HTML) when writing the description.
```

In both cases the definition is the title (or other front matter value) of a corresponding content page (e.g., content/glossary/foo.html), which may or may not be a taxonomy term.

<details>
<summary>layouts/shortcodes/abbr.html</summary>

```text
{{- /*
Renders an abbr element with an optional title attribute.

The first positional argument is the abbreviation. The second positional
argument is the definition.

If you do not provide the second argument, Hugo searches the glossary section
of your project for a page path that matches the first argument, and uses its
title for the definition.

If Hugo cannot find a matching page path it omits the title attribute.

@example {{< abbr HTML "Hypertext Markup Language" >}}
@example {{< abbr HTML >}}
*/}}
{{- with $abbr := .Get 0 }}
  {{- with or ($.Get 1) (site.GetPage (printf "/glossary/%s" $abbr)).Title -}}
    <abbr title="{{ . }}">{{ $abbr }}</abbr>
  {{- else -}}
    <abbr>{{ $abbr }}</abbr>
  {{- end }}
{{- else }}
  {{- errorf "The %q shortcode requires a single positional parameter. See %s" .Name .Position }}
{{- end -}}
```
</details>

**Comment by bep** [comment]
>Use {{< abbr HTML >}} when writing the description.
>Use [*](HTML) when writing the description.

Yea, and both of the above (I guess especially the last one, since it's in some sense is portable) is better than some obscure PHP Markdown Extra  thing.

I'm closing this. We have another issue for the glossary, which I suspect will need some tooling to be good.

**Comment by jmooring** [comment]
@jsabater I have updated my previous comment to include an example of a link render hook. Take the test site for a spin.

**Comment by scorpatu** [comment]
> We have another issue for the glossary

Which issue if you don't mind?

**Comment by bep** [comment]
Just to be clear about my take on this:

* We have several ways to do this in Hugo as is without any additional work.
* I would consider adding an extension to Hugo for this if it was somehow "standard Markdown". That's not the case, so we need to work with what we got.

**Comment by jsabater** [comment]
Thanks for the comments and the help. For future reference, these are the steps to get abbreviations working via link render hooks:

1. Create a `content/glossary` subdirectory and, inside, create one `term.md` file for each term, e.g., `html.md`, `lan.md`, `cpu.md`, and so on. The title of the front matter of each of those files will be the title in the abbreviation.
2. Since you are doing this, you can add a description of the term in the body of the markdown file, and include an `_index.md` file in the folder to have a list page referencing all your terms.
3. Create the path `layouts/_default/_markup` in your website.
4. Download the [embedded link render hook layout file](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/_markup/render-link.html) inside that folder, so Hugo knows how to render the terms in your articles.
5. When writing an article, use the following syntax: 

```text
... we will create a [*](LAN) for all the guests in our cluster ...
```

Pro et contra (personal opinion):

* You have all the terms in one place for all your articles, so you avoid duplicates and reduce the size of the article
* You can extend them with a long description should you want to link to the glossary page in your site menu or something.
* You have to create a file for each term.
