### ISSUE TITLE
Broken Link for 'Dark Mode' Tag on Hugo Themes Page

### ISSUE THREAD

**Issue by felixbd** [gohugoio/hugo#12857]
### What version of Hugo are you using (`hugo version`)?

latest version of the `https://themes.gohugo.io/` webpage

> v0.134.2

### Does this issue reproduce with the latest release?

yes

---------

### Description
On the [Hugo Themes page](https://themes.gohugo.io/), under the **Tags** section, there is a link to the "Dark mode" tag. However, the link is currently broken due to a whitespace character (`%20`) instead of a hyphen (`-`) in the URL.

### Current Behavior
Clicking on the "Dark mode" tag directs to a 404 page:
- Incorrect URL: [https://themes.gohugo.io/tags/dark%20mode/](https://themes.gohugo.io/tags/dark%20mode/)

### Expected Behavior
The link should lead to the correct "Dark mode" tag page:
- Correct URL: [https://themes.gohugo.io/tags/dark-mode/](https://themes.gohugo.io/tags/dark-mode/)

### Steps to Reproduce
1. Go to [https://themes.gohugo.io/](https://themes.gohugo.io/)
2. Scroll down to the **Tags** section.
3. Click on the "Dark mode" tag.
4. Observe that the link leads to a 404 page.

### Suggested Solution
Update the URL for the "Dark mode" tag link to use a hyphen (`-`) instead of a whitespace (`%20`).

**Comment by felixbd** [comment]
GoodFirstIssue

**Comment by bep** [comment]
Wrong repo.
