### ISSUE TITLE
plain markdown resource breaks build

### ISSUE THREAD

**Issue by McShelby** [gohugoio/hugo#12855]
Having a leaf bundle (`content/posts`) with Markdown resources (`content/posts/res-1.md`) fails to build if beginning of Markdown contains certain characters.

`res-1.md`

````md
---

Not allowed to start with a dash as used in dividers `---` or bullet point items `-`.
````

Most likely, it got interpreted as incomplete frontmatter.

This seems like a bug, as I think a resource does not contain meta data defined inside the resource itself.

Test repo: https://github.com/McShelby/hugo-testing/tree/hugo-issue-12855

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.134.2-1c74abd26070b0c12849550c974a9f3f1e7afb06 windows/amd64 BuildDate=2024-09-10T10:46:33Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
The used version is the latest release.

**Comment by jmooring** [comment]
> as I think a resource does not contain meta data


Page resources with [`ResourceType`](https://gohugo.io/methods/resource/resourcetype/) “page” can contain front matter, which allows you to do something like this in a template:

```text
{{ range .Resources.ByType "page" }}
  <h3>{{ .Title }}</h3>
  <h4>{{ .Params.subtitle }}</h4>
  {{ .Content }}
{{ end }}
```

Page resources with `ResourceType` “page” include Markdown, HTML, Emacs Org Mode, AsciiDoc, Pandoc, or reStructuredText (e.g., files with extension `.md`, `.html`, `.org`, `.adoc`, `.pdc`, `.rst`). See [documentation](https://gohugo.io/content-management/formats/#classification) for a complete list of extensions.

I think this issue should be closed. It works as designed.

**Comment by jmooring** [comment]
Front matter is optional, but can't begin with a character that matches the characters in front matter delimiters: `-`, `+`, `{`.

I don't see this changing, so you might open an issue in the docs repository.
