### ISSUE TITLE
.RenderShortcodes generates artifact when used nested in HTML

### ISSUE THREAD

**Issue by McShelby** [gohugoio/hugo#12854]
Configured `renderer.unsafe=true` and then using `.RenderShortcodes` in a shortcode used with `%` generates artifacts in the form of `{{__hugo_ctx pid=3}}`.

Is this intended?

This can be seen in the sample repo in http:/localhost:1313/posts

https://github.com/McShelby/hugo-testing/tree/hugo-issue-12854

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.134.2-1c74abd26070b0c12849550c974a9f3f1e7afb06 windows/amd64 BuildDate=2024-09-10T10:46:33Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes. The used version was the latest.

**Comment by bep** [comment]
>Is this intended?

No, but I'm assuming you're doing something ... unusual that we didn't think of when we implemented this. Because it doesn't always happen.

**Comment by McShelby** [comment]
Hm. I stripped the sample down to the bones. In my view, nothing special here.

**Comment by bep** [comment]
This usage is unusual:

```
{{- range .Page.Pages }}
<h3>{{ .Title | safeHTML }}</h3>
<div>{{ .RenderShortcodes | safeHTML }}</div>
{{- end }}
```

I suggest you read the documentation and/or start a thread in the forum about the intention/use cases of `.RenderShortcodes`. It's a method with very limited but useful use: Including markdown in markdown, so to speak.

**Comment by McShelby** [comment]
For others who may come around: The artifacts seem to be avoided if the shortcode is changed by adding a blank line in front of `.RenderShortcodes`.

````
{{- range .Page.Pages }}
<h3>{{ .Title | safeHTML }}</h3>
<div>

{{ .RenderShortcodes | safeHTML }}
</div>
{{- end }}
````

**Comment by bep** [comment]
For others who may come around:

Please read and understand the documentation at https://gohugo.io/methods/page/rendershortcodes/ and consider if you really need to use this method. It is very useful, but it a special purpose `method`.

If you wrap your `.RenderShortcodes` in a `div` and pipe it to `safeHTML`, the answer is `no`.

**Comment by McShelby** [comment]
Thanks bep for the fix.

Just for clarification, does this fix change your statement from above?

> If you wrap your `.RenderShortcodes` in a `div` and pipe it to `safeHTML`, the answer is `no`.

**Comment by bep** [comment]
>Just for clarification, does this fix change your statement from above?

No.

The fix is to catch an error situation. I will print a warning (that can be turned off) about it.

The only use case I can think of for `.RenderShortcodes` is to include **markdown** blocks. Anything else just doesn't work.

**Comment by bep** [comment]
>Just for clarification, does this fix change your statement from above?

That said, the PR fixes 2 issues with similar symptoms (see test cases); one of them is perfectly valid use ...

**Comment by jmooring** [comment]
@McShelby 

> adding a blank line

Regardless of  changes in #12996, you will still need a blank line, and that is expected per the CommonMark specification for [HTML blocks](https://spec.commonmark.org/0.31.2/#html-blocks). Specifically, read about the end condition for the sixth "type" of HTML block.
