### ISSUE TITLE
Add Resource.Resources (and CSS output in js.Build)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#12866]
While working on #12641 I'm creating a test/demo site "showcasing" all (or most) of the [react-aria](https://react-spectrum.adobe.com/react-aria/getting-started.html) components. The "Vanilla CSS" starter pack imports CSS into the JS files. Hugo doesn't currently support that, but I know people have aske about it, so we might as well tackle it sooner rather than later.

ESBuild, the library we use for this, builds the CSS and returns them in the `outputs` slice (where the first item is the entry point JS). But it's up to the user to [link it into the HTML](https://esbuild.github.io/content-types/#css-from-js).

What I suggest is something ala:

```handlebars
{{ $js := resources.Get "js/main.js" | js.Build (dict "params" (dict "api" "https://example.org/api")) }}
{{ range $js.Resources.ByType "css" }}
<link href="{{ .RelPermalink }}" rel="stylesheet">
{{ end }}
<script src="{{ $js.RelPermalink }}"></script>
```

In the above, ESBuild does not need to know the URL to the CSS, a good thing, since we then are free to do fingerprinting etc. as we please.

Note to self that this may be a good time to clean up the rather ugly way we handle source maps, which is also in the `outputs` slice from ESBuild. One could imagine we would do:

```handlebars
{{ if hugo.IsDevelopment }}
  {{ range $js.Resources.ByType "map" }}
     {{ .Publish }}
  {{ end }}
{{ end }}
```

@cmahnke @jmooring does the above make sense?

**Comment by jmooring** [comment]
The proposed API looks good, but it's unclear to me if the slice of returned resources includes the JS. In other words, are these equivalent?

```text
{{ range $js.Resources.ByType "js" }}
  <script src="{{ .RelPermalink }}"></script>
{{ end }}

<script src="{{ $js.RelPermalink }}"></script>
```

**Comment by bep** [comment]
>First, page resources with extension css or js currently have a [ResourceType](https://gohugo.io/methods/resource/resourcetype/) of text

Yea, right. We need to think about adding some more ways to filter these (I guess you could also use `where`), but I don't think that's the most important part of this.

```handlebars
{{ range $js.Resources.ByType "javascript" }}
  <script src="{{ .RelPermalink }}"></script>
{{ end }}

<script src="{{ $js.RelPermalink }}"></script>
```

That is a good question, and I thought about this. The output from ESBuild is a slice, but there's a implicit parent child relationship there that needs to be understood/handled, so I think that it makes sense to say that in:

```
{{ $js := resources.Get "js/main.js" | js.Build (dict "params" (dict "api" "https://example.org/api")) }}
```

* The `$js` `Resource` represents the `js/main.js` script, which may bundle other modules (either inline or via EMAScript imports (EMAScript imports does not support SRI by design, so we do not have to worry about that).
* The `Resources` built that's not included/bundled in `$js` can be accessed in `$js.Resources`. This will be CSS, source maps etc.

So, I'm leaning against saying that a `Resource` may have a list of sub resources (not including itself).

**Comment by bep** [comment]
>So, I'm leaning against saying that a Resource may have a list of sub resources (not including itself), but I'm open to arguments against it ...

**Comment by bep** [comment]
Having slept on this, I think it would be better to just move to a new method name, e.g. `js.ESBuild` (in line with the others), and return a struct. There's lots of useful debug artifacts in the ESBuild API that's very hard to force into our current API.
