### ISSUE TITLE
arg to turn off nag screen about baseURL, even when baseURL has been set.

### ISSUE THREAD

**Issue by gedw99** [gohugoio/hugo#12878]
As per https://github.com/zeon-studio/hugoplate/issues/149#issue-2546975863

Can we have a flag to turn off the nag screen, at the top of each web page, which says:

"You must replace the baseURL in hugo.toml file when deploying, you can manage this announcement from the params.toml file."

Doing it in config is the time and  place IMHO.

**Comment by jmooring** [comment]
You need to take this up with the author of the theme.
