### ISSUE TITLE
Markdown render hook for tables doesn't recognize unset column alignment

### ISSUE THREAD

**Issue by chalin** [gohugoio/hugo#12886]
As of [v0.134.0](https://github.com/gohugoio/hugo/releases/tag/v0.134.0) (via #12809), [Markdown render hooks for tables](https://gohugo.io/render-hooks/tables/) are supported.

While there are **four possible [column alignment syntaxes](https://www.markdownguide.org/extended-syntax/#alignment)** (see the table below), only three are reported: the `---` (unset) syntax isn't recognized as distinct from left alignment `:---`.

When rendered, a cell from an unset column should have **no `text-align` style** set, but unfortunately, the following hook override fragment won't work:

```liquid
{{- range . }}
  <th
    {{- with .Alignment -}}
      {{ printf " style=%q" (printf "text-align: %s" .) | safeHTMLAttr }}
    {{- end -}}
    >
    {{- .Text | safeHTML -}}
  </th>
{{- end }}
```

References:

- #9316
- #12809

| Column alignment | Syntax |
--- | --- 
**Unset** | `-----`
Left | `:----`
Right | `----:`
Centered | `:---:`

**Comment by jmooring** [comment]
Goldmark handles this as expected (see [playground example](https://yuin.github.io/goldmark/playground/?m=a%257Cb%257Cc%257Cd%250A---%257C%253A--%257C%253A-%253A%257C--%253A%250A1%257C2%257C3%257C4%250A%250A&o=1&v=v1.7.4)).

We should set the default to an empty string.

https://github.com/gohugoio/hugo/blob/d0dca656250d0a04f3a5051ec067022df4b37738/markup/goldmark/tables/tables.go#L123-L133

**Comment by bep** [comment]
>We should set the default to an empty string.

Agree.
