### ISSUE TITLE
Default table alignment triggers common Content Security Policy

### ISSUE THREAD

**Issue by rtfmkiesel** [gohugoio/hugo#12890]
The default option for table alignments is ['left'](https://github.com/gohugoio/hugo/blob/d1ba52f3c3bdc31c2067f986fdb57088d875c01e/markup/goldmark/tables/tables.go#L132). Would it be possible to exclude the style attribute altogether, if no `:` is used to indicate the alignment?

Having inline style tags triggers a [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) which does not allow for `style-src 'unsafe-inline';`.

---

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.135.0-f30603c47f5205e30ef83c70419f57d7eb7175ab+extended windows/amd64 BuildDate=2024-09-27T13:17:08Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
This is a duplicate of #12886 which is resolved by https://github.com/gohugoio/hugo/pull/12889.

**Comment by rtfmkiesel** [comment]
Thanks for the fast response, but it's not quite the issue I am describing.

Using your branch, I get the HTML of `<td style=text-align:>test</td>` when no `:` is used. This still triggers the CSP. The complete `style` attribute would need to be left out. Now, it's just an invalid style attribute.

Output: `<td style=text-align:>test</td>`
Expected: `<td>test</td>`

**Comment by rtfmkiesel** [comment]
The render hook workaround works, thanks for the hint!
