### ISSUE TITLE
Hugo docker cannot find Go binary in PATH

### ISSUE THREAD

**Issue by Int-Circuit** [gohugoio/hugo#12915]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.135 (docker)
</pre>

### Does this issue reproduce with the latest release?
Yes

When using hugo to load the modules from my go.mod file, my CI on GitLab complains that the image hasn't "go" in it's PATH.
See log

[log.txt](https://github.com/user-attachments/files/17294195/log.txt)

**Comment by bep** [comment]
Fixed in #12921 ....
