### ISSUE TITLE
Tag docker image with latest

### ISSUE THREAD

**Issue by eriklilljequist** [gohugoio/hugo#12910]
Hello,

I am running hugo in a gitlab pipeline and would like possibility to pull the latest release from ghcr.

Preferably using semantic versioning so that I can pull latest patches and features with v1 e.g. without risking getting any brealking changes from e.g. v2.

Thank you for a great tool.

**Comment by bep** [comment]
We now have a latest tag on the images:

https://github.com/gohugoio/hugo/pkgs/container/hugo/289536592?tag=latest

>Preferably using semantic versioning so that I can pull latest patches and features with v1 e.g. without risking getting any brealking changes from e.g. v2.

Yea, well, Hugo's still not at v1, so let's worry about that later.
