### ISSUE TITLE
hugo uses `toml` frontmatter in `archetypes/default.md` even when site was created with `--format yaml`

### ISSUE THREAD

**Issue by ajbuz** [gohugoio/hugo#12922]
### What version of Hugo are you using (`hugo version`)?
I think version is irreverent here since it exists from beginning  ?
<pre>
$ hugo version
hugo v0.135.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

### Steps to Reproduce 
```bash
hugo new site --format yaml my-new-site
cat  my-new-site/archetypes/default.md
+++
title = '{{ replace .File.ContentBaseName "-" " " | title }}'
date = {{ .Date }}
draft = true
+++
```
### Expected output
```md
---
title: '{{ replace .File.ContentBaseName "-" " " | title }}'
date: {{ .Date }}
draft: true
---
```

**Comment by bep** [comment]
>I think version is irreverent here since it exists from beginning ?

No it hasn't, but this has been discussed before and is as designed. Hugo uses the front matter templates in the archetype files as-is, there's no YAML to toml conversion. If you want TOML, create archetype files with TOML

**Comment by ajbuz** [comment]
> there's no YAML to toml conversion. If you want TOML, create archetype files with TOML


I don't know if you understood my question or not. What I'm trying to say is I want YAML not TOML in the frontmatter of `archtypes/default.md` like this
```md
---
title: '{{ replace .File.ContentBaseName "-" " " | title }}'
date: {{ .Date }}
draft: true
---
```
 when I create site using   `hugo new site --format yaml my-new-site` command.

**Comment by jmooring** [comment]
Duplicate of https://github.com/gohugoio/hugo/issues/12666
