### ISSUE TITLE
variables do not work with hasPrefix inside render-link

### ISSUE THREAD

**Issue by knutov** [gohugoio/hugo#12929]
<pre>
$ hugo version # from github

hugo v0.135.0-f30603c47f5205e30ef83c70419f57d7eb7175ab+extended linux/amd64 BuildDate=2024-09-27T13:17:08Z VendorInfo=gohugoio
</pre>

`layouts/_default/_markup/render-link.html`:

```
<pre>DEBUG:
	{{ hasPrefix .Destination "http" }}
	{{ eq (substr (.Destination | lower ) 0 4) "http" }}
	{{ findRE `http` .Destination }}
	{{ hasPrefix "https://my.test.link/" "http" }}

	.Destination: {{ .Destination }}
	.Title: {{ .Title }}
	.Text: {{ .Text }}
</pre>
```

and I have this result after render:

```
DEBUG:
	false <--- expected true
	false <--- expected true
	[] <--- expected to find something
	true <--- hasPrefix "https://my.test.link/" "http" works if it is a string, not variable

	.Destination: https://my.test.link/  
	.Title: 
	.Text: link text
```

**Comment by bep** [comment]
I'm pretty sure `hasPrefix` works fine with variables and render-links, but I cannot spot the error in the snippet you posted.

**Comment by knutov** [comment]
It works before.
I just upgraded to the latest hugo version, did fixes for new `.Summary` behavior and started to check is everything else works fine.

Ans this snippet is not working as earlier.

If link inside markdown is `https://my.test.link/` I do expect hasPrefix 'http' to be true - I use it to add `target="_blank"`. With latest version it is not working.

**Comment by knutov** [comment]
my actual snippet (without debug code) is

```
<a href="{{ .Destination | safeURL }}"
	{{- with .Title}} title="{{ . }}"{{ end }}
	{{- if strings.HasPrefix .Destination "mailto" -}} target="_blank" {{end}}
	{{- if or
		( strings.HasPrefix .Destination "http" )
		( strings.HasPrefix .Destination "https" )
		( strings.HasSuffix .Destination ".pdf" )
	-}}
	target="_blank" rel="noopener"{{ end }}>{{- .Text | safeHTML -}}</a>
{{- partial "empty.html" . -}}
```

**Comment by jmooring** [comment]
I am not able to reproduce the problem as described. Try it:

```text
git clone --single-branch -b hugo-github-issue-12929 https://github.com/jmooring/hugo-testing hugo-github-issue-12929
cd hugo-github-issue-12929
hugo server
```

**Comment by knutov** [comment]
> I am not able to reproduce the problem as described. Try it:

Indeed, this minimal example is working correct. What can go wrong in my case?

**Comment by jmooring** [comment]
Does one of your Markdown links use a shortcode for the destination? For example:

```text
[link text]({{< some-shortcode xxxx >}} "link title")
```

**Comment by knutov** [comment]
Well, I found the minimal repoducer based on your branch:

https://github.com/knutov/hugo-testing/tree/hugo-github-issue-12929

https://github.com/knutov/hugo-testing/commit/85593be2c81fc71e0f1bed972b549962725f7a5e

**Comment by knutov** [comment]
> Does one of your Markdown links use a shortcode for the destination? For example:
> 
> ```
> [link text]({{< some-shortcode xxxx >}} "link title")
> ```

yes, it's `param`

**Comment by jmooring** [comment]
Use the `{{% .. %}}` notation instead of `{{< ... >}}`.

**Comment by knutov** [comment]
> Use the `{{% .. %}}` notation instead of `{{< ... >}}`.

It works! Thanks! Is it about https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown ?

**Comment by jmooring** [comment]
Yes, sort of.
