### ISSUE TITLE
Merge Table cells

### ISSUE THREAD

**Issue by overlookart** [gohugoio/hugo#12937]
### Merge Table cells

How to merge cells in “Table render hooks”？

layouts/_default/_markup/render-table.html

**Comment by overlookart** [comment]
[swift-Docc adding tables of data](https://www.swift.org/documentation/docc/adding-tables-of-data 'adding tables of data')

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
