### ISSUE TITLE
Show some additional information for multiple languages sites [in debug mode]

### ISSUE THREAD

**Issue by wehrend** [gohugoio/hugo#12939]
I've come across some difficulties when creating a multilanguage setup. It would help to see in the log file, iff a language switcher has been included. It is hard to create a multilanguage site without this help / support. 
So, iff I run hugo with -v flags, I would ideally have some line showing, language switcher detected or something similar.

If you dont want such a feature, please help me out with my site....

**Comment by jmooring** [comment]
A theme's non-trivial features should be documented by the theme author. A language switcher is a trivial feature, and I would expect it to be present for any theme that supports multilingual configurations.
