### ISSUE TITLE
resources/page: Escaping colon in permalinks erroneously throws error in some circumstances

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12948]
I found this while attempting to document how to escape a colon.

With this front matter:

```text
---
title: p1
url: "/foo\\:bar/:slug/"
---
```

Hugo throws an error:

```text
Error: error building site: render: error expanding "/foo\\:bar/:slug/": permalink ill-formed
```

Although not related to this bug, if I had taken the time to weigh in on the original proposal I would have expressed my concerns about OS compatibility. You cannot use this feature on Windows because the path cannot contain a colon (restricted character). We will have to note in the documentation that you can't use this feature on Windows, but that won't really help for projects with multiple contributors where some use Windows. 

The existing tests pass on Windows because they don't write to disk. 

I think we should consider removing this feature.

**Comment by jmooring** [comment]
If we keep the feature I'll move this comment to a separate issue.

This currently works in front matter:

```text
---
title: p1
url: "/special\\::slug/"
---
```

This currently fails in the site configuration (colon omitted from file path):

```text
[permalinks]
s1 = "/special\\::slug/"
```

**Comment by bep** [comment]
>You cannot use this feature on Windows because the path cannot contain a colon

I wouldn't call this a ... feature, but I see your point.

**Comment by bep** [comment]
@jmooring I have fixed this in #12951 -- but I needed to adjust the test case a little. I have added a comment. The test case looks a little odd, but opening up for colons in Hugo generated paths would create mayhem. I think this falls into the category of "the `url` set in front matter is the user's responsibility", but I'm kind of already regretting going down this rabbit hole.

**Comment by jmooring** [comment]
Understood. Use with `url` front matter only, and don't use it with Windows.

I'm not fond of this rabbit hole either, and would support removing it.

**Comment by bep** [comment]
>I'm not fond of this rabbit hole either, and would support removing it.

Yea, well, maybe. The thing is, this was already possible before we added permalink tokens to the front matter `url` -- which goes to say that we're now fixing a breaking change. I think it helps to call this a bug and not a feature.

There's many characters that's allowed in `url` front matter, but not in paths created by Hugo, so I think it helps to mentally add ... colon to that list.

```go
func isAllowedPathCharacter(s string, i int, r rune) bool {
	if r == ' ' {
		return false
	}
	// Check for the most likely first (faster).
	isAllowed := unicode.IsLetter(r) || unicode.IsDigit(r)
	isAllowed = isAllowed || r == '.' || r == '/' || r == '\\' || r == '_' || r == '#' || r == '+' || r == '~' || r == '-' || r == '@'
	isAllowed = isAllowed || unicode.IsMark(r)
	isAllowed = isAllowed || (r == '%' && i+2 < len(s) && ishex(s[i+1]) && ishex(s[i+2]))
	return isAllowed
}
```
