### ISSUE TITLE
page not generated due to timezone mismatch

### ISSUE THREAD

**Issue by k4lizen** [gohugoio/hugo#12940]
### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
hugo v0.135.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes
##
I'm using this theme: https://github.com/526avijitgupta/gokarna which has this archetype for posts:
```md
+++
title = '{{ replace .File.ContentBaseName "-" " " | title }}'
date = {{ .Date }}
draft = true
+++
```
So when I create a new post, the date gets set automagically. The date seems to be set according to my local timezone. It can easily happen that it's for example `2024-12-3` in my timezone and `2024-12-2` in UTC. This comment (https://github.com/gohugoio/hugo/issues/6325#issuecomment-530777041) says:
```
---
date: 2019-09-12
---
```
> The above will be parsed as midnight UTC.  

As a result, my post will not be loaded because hugo thinks it's in the future. 
#### Recap
If im close to midnight and my timezone is after UTC and I do
`hugo new content posts/thingy.md` then `hugo server`, the post will not appear even though it should.

The workaround is passing `-F` to `hugo server`, however that is highly non-obvious (and doesn't fix the issue for deployment?). I look at the date in the frontmatter, I look at my PC clock, everything seems fine, why would the post I **just created** not appear?

**Comment by jmooring** [comment]
If the archetype used when creating your content looks like this:

```text
+++
title = '{{ replace .File.ContentBaseName "-" " " | title }}'
date = {{ .Date }}
draft = true
+++
```

And you run this command:

```text
+++
title = '{{ replace .File.ContentBaseName "-" " " | title }}'
date = {{ .Date }}
draft = true
+++
```

The resulting Markdown file looks something like this:

```text
+++
title = 'Foo'
date = 2024-10-14T16:45:46-07:00
draft = false
+++
```

The date above is clearly not in the Etc/UTC time zone.

Please use the forum (https://discourse.gohugo.io/) if you have additional questions. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by k4lizen** [comment]
> The date above is clearly not in the Etc/UTC time zone.

I agree, that's exactly what I said.

> Please use the forum (https://discourse.gohugo.io/) if you have additional questions. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

aight

**Comment by k4lizen** [comment]
If anyone stumbles accross the same problem (like this person https://discourse.gohugo.io/t/hugo-does-not-respect-timezone-when-generating-published-posts/33392), make sure the date field (managed by your theme?) includes timezone information. In other words you don't want this: `date: {{ now.Format "2006-01-02" }}` (https://github.com/526avijitgupta/gokarna/blob/fc09ce7645eb309dc70796376f0da042b10f9889/archetypes/posts.md?plain=1#L2).

**Comment by jmooring** [comment]
Dates without offsets are in the Etc/UTC time zone unless you specify [`timeZone` ](https://gohugo.io/getting-started/configuration/#timezone)in your site configuration.

See [docs](https://gohugo.io/content-management/front-matter/#dates).
