### ISSUE TITLE
`page.GetPage` sometimes succeeds but sometimes fails

### ISSUE THREAD

**Issue by xuhdev** [gohugoio/hugo#12950]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.136.0-2939270a3bb78b3799973345c0dab7fa239cef9d+extended linux/amd64 BuildDate=2024-10-15T13:17:24Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

### Description

With `page.GetPage` used in a shortcode:

- When parallel processing is enabled, `page.GetPage` sometimes can get the page but sometimes fails.
- When setting `HUGO_NUMWORKERMULTIPLIER=1`, it can't get the page.

### Reproduce Steps

1. Clone the repo https://github.com/xuhdev/hugo-issue-12950 . This is basically `hugo new site` with two more files:
  - `layouts/shortcodes/my_shortcode.html`:

```html
{{- with page.GetPage (.Get 0) -}}
  {{ .Title }}
{{- else -}}
  {{ errorf "GetPage failed to get %s" (.Get 0) }}
{{- end -}}    
```

 - content/posts/a.md:

```html
date = '2024-10-15T22:45:34-07:00'
title = 'A'
+++++++

{{< my_shortcode "./a" >}}
```

2. Run `HUGO_NUMWORKERMULTIPLIER=1 hugo`, it generates the error `ERROR GetPage failed to get ./a`.
3. Run `HUGO_NUMWORKERMULTIPLIER=4 hugo` multiple times (try 10 times if you keep getting the same result), it sometimes generates the error above, sometimes succeeds:
```
                   | EN  
-------------------+-----
  Pages            |  5  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Cleaned          |  0  

```

**Comment by jmooring** [comment]
<https://gohugo.io/functions/global/page/>

Unless you know what you're doing, don't use the global `page` function.
