### ISSUE TITLE
Dart Sass v1.80.1 deprecation warning

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12961]
Testing Dart Sass v1.80.1 

> WARN  Dart Sass: hugo:vars:0:17: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use string.unquote instead.

Why we're getting this is unclear at the moment.

**Comment by bep** [comment]
https://sass-lang.com/documentation/breaking-changes/import/

**Comment by jmooring** [comment]
This test fails with Dart Sass v1.80.1.

```go
// Issue #12961
func TestDartSassVars(t *testing.T) {
	t.Parallel()

	files := `
-- hugo.toml --
disableKinds = ['page','section','rss','sitemap','taxonomy','term']
-- layouts/index.html --
{{ $opts := dict "transpiler" "dartsass" "outputStyle" "compressed" "vars" (dict "color" "red") }}
{{ with resources.Get "main.scss" | css.Sass $opts }}
  {{ .Content }}
{{ end }}
-- assets/main.scss --
@use "hugo:vars" as v;
body {color: v.$color;}
`

	b := hugolib.Test(t, files, hugolib.TestOptWarn())

	b.AssertFileExists("public/index.html", true)
	b.AssertFileContent("public/index.html", "body{color:red}")
	b.AssertLogContains("! WARN  Dart Sass: hugo:vars") // failing assertion
}
```

**Comment by jmooring** [comment]
https://github.com/gohugoio/hugo/blob/e971b7d866d8834022f0038b094dce4352338f74/resources/resource_transformers/tocss/internal/sass/helpers.go#L52-L58

This solves the problem when using the Dart Sass transpiler:

```go
				varsSlice = append(varsSlice, fmt.Sprintf("%s%s: string.unquote(%q);", prefix, k, v))
			}
		}
	}
	sort.Strings(varsSlice)
	varsStylesheet = `@use "sass:string";` + "\n" + strings.Join(varsSlice, "\n")
	return varsStylesheet
}
```

But the containing function (`CreateVarsStyleSheet`) is called when using either transpiler, so the changes above need to be specific to dart sass, but I haven't found a way to get the transpiler value ("libsass" or "dartsass") within that function.

**Comment by bep** [comment]
>But the containing function (CreateVarsStyleSheet)

I guess adding some kind of identifier as the first arg to CreateVarsStyleSheet would solve it.
