### ISSUE TITLE
Deprecation error during build

### ISSUE THREAD

**Issue by meisterheister** [gohugoio/hugo#12965]
With the latest hugo version the previous warnings became errors now so that I needed to address the issues since the build fails otherwise. When looking into it I realised that I don't use this variable anywhere, so why do I even get this?

> ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Implement taxonomy 'social' or use .Site.Params.Social instead.
> ERROR deprecated: .Site.Authors was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Implement taxonomy 'authors' or use .Site.Params.Author instead.

### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.136.2-ad985550a4faff6bc40ce4c88b11215a9330a74e+extended linux/amd64 BuildDate=2024-10-17T14:30:05Z VendorInfo=snap:0.136.2

</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
