### ISSUE TITLE
Ignore summary separator in code spans, code blocks, and the highlight shortcode

### ISSUE THREAD

**Issue by saaste** [gohugoio/hugo#12973]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.136.1+extended darwin/arm64 BuildDate=2024-10-16T16:05:18Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?
Yes

### Issue
If you want to show an example of a markdown content file using the `highlight` shortcode and markdown contains `<!--more-->` tag, the tag is not visible in the generated output.

Example:
```
{{< highlight md >}}
---
date: "2024-10-20T11:58:09+03:00"
draft: true
title: "Example"
---
Summary
<!--more-->
Content
{{</ highlight >}}
```

Result:
<img width="1188" alt="Screenshot 2024-10-20 at 13 49 33" src="https://github.com/user-attachments/assets/d8e1b080-fc41-4168-a19c-0b96704143bd">

As you can see, `<!--more-->` tag is not visible.

### Workaround
You can add `<!--more-->` twice and the latter tag will be visible.

Example:
```
{{< highlight md >}}
---
date: "2024-10-20T11:58:09+03:00"
draft: true
title: "Example"
---

Summary
<!--more-->
<!--more-->
Content
{{</ highlight >}}
```

Result:
<img width="1182" alt="Screenshot 2024-10-20 at 16 17 16" src="https://github.com/user-attachments/assets/e9878ddd-20e0-4232-a1a6-1f83b83dd0f0">

No you can see the `<!--more-->` tag in the output, but it requires you to write twice in the markdown.

Related forum post: https://discourse.gohugo.io/t/how-to-use-highlight-shortcode-with-more/52041

**Comment by jmooring** [comment]
This use case is uncommon: documenting the use of Hugo's summary separator, as we have done here:
<https://gohugo.io/content-management/summaries/#manual-summary>

To accomplish this you can...

1\) Place a summary separator in the document somewhere before you document its usage, even just placing it just below the front matter as we have done in our own documentation. This works with code spans, fenced code blocks, indented code blocks, and the highlight shortcode.

2\) Create a "more" shortcode to insert the summary separator. This works with code spans, fenced code blocks, and indented code blocks. For example:

layouts/shortcodes/more.html

```text
&lt;!--more--&gt;{{- /**/ -}}
```

example.md

````text
```text
foo
{{< more >}}
bar
```

foo `{{< more >}}` bar
```
````

3\) If you must use the highlight shortcode (e.g.,, the [content format](https://gohugo.io/content-management/formats/) does not support syntax highlighting), override the [embedded template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/highlight.html) to perform a search/replace on some other token.

Given the number of ways to document usage of the summary separator, I don't see us spending any time on this.

**Comment by saaste** [comment]
That is a fair point, and I agree that this is quite rare case. Workarounds solve the problem and are relatively easy to implement, so I agree with your assessment 👍 ☺️
