### ISSUE TITLE
`DisableHugoGeneratorInject` broken?

### ISSUE THREAD

**Issue by catap** [gohugoio/hugo#12976]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.136.3+extended openbsd/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Adding:
```toml
disableHugoGeneratorInject = true
```
into `hugo.toml` doesn't remove:
```
<meta name="generator" content="Hugo 0.136.3">
```
from resulted HTML files.

**Comment by jmooring** [comment]
`disableHugoGeneratorInject = true` tells Hugo not to automatically inject the `meta` element on the home page, and it works as designed. I suspect your theme has hardcoded the `meta` element in one of its templates, or perhaps you've placed this configuration key-value pair beneath a table in your site configuration.

**Comment by catap** [comment]
Thanks for very fast reply!

Indeed it is a bug in used theme.
