### ISSUE TITLE
Taxonomy 'Social' Issue

### ISSUE THREAD

**Issue by The-alpha-male** [gohugoio/hugo#12984]
![image](https://github.com/user-attachments/assets/ec603242-4b7b-49d9-9918-ec5dff95923f)

I have been having this issue and tried all ways to resolve it but nothing seems to work. The theme used is PaperMod and I am running the most recent version of Hugo which is v0.136.5 on Ubuntu 24.04.1 LTS

**Comment by jmooring** [comment]
This is an issue with the theme, not with Hugo itself. 

See <https://github.com/adityatelange/hugo-PaperMod/issues/1573>.
