### ISSUE TITLE
ByParam not playing well with pagination

### ISSUE THREAD

**Issue by ka259** [gohugoio/hugo#12986]
### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
0.136.5
</pre>

### Does this issue reproduce with the latest release?
Yes

Test site https://github.com/ka259/test. (File of interest, `layouts/items/list.html`)

I am trying to paginate the items `.ByParam "price"`, but when I go to page 2 or subsequent pages, then the items show up with a lower price as the starting item. 

What I expect is, for example, page one to have prices 200, 300, 400 and page 2 to have prices 500, 600 and 700 and so on incrementally. But that is not what is happening as you can see when you build the site and visit the items section.

The `ByParam` page says `Returns the given page collection sorted by the given parameter in ascending order.` So, I think it is not playing well with pagination https://gohugo.io/methods/pages/byparam/

**Comment by jmooring** [comment]
You need to filter/sort _before_ you paginate. 

Do this:

```text
{{ range (.Paginate ($p.ByParam "price") 3).Pages }}
```

Not this:

```text
{{ range (.Paginate $p 3).Pages.ByParam "price" }}
```

**Comment by ka259** [comment]
@jmooring this again threw an error on my project. Please run https://github.com/ka259/hugo-test and see the error about paginate. Removing the `.Pages` from the header file (`)).Pages`) and the error disappears.

**Comment by jmooring** [comment]
@ka259 Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
