### ISSUE TITLE
Not all chroma languages supported

### ISSUE THREAD

**Issue by jbirnick** [gohugoio/hugo#12980]
Hugo uses [Chroma](https://github.com/alecthomas/chroma) for syntax highlighting. However, it seems like it doesn't support all the languages that Chroma supports.

For example, Chroma supports the language "Typst", but Hugo does not. (It's neither listed [here](https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages) nor does it work with the current version.)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.136.4+extended linux/amd64 BuildDate=unknown
</pre>

**Comment by jmooring** [comment]
Chrome added the Typst lexer on 6 October 2024 via https://github.com/alecthomas/chroma/commit/114c584bd6102ccd285f2a72170d6f2be18e8b80. Hugo will support Typst at some point after the Chroma project rolls a new release.
