### ISSUE TITLE
Fedora 41: "Error: error building site: assemble: unable to cast <nil> of type <nil> to map[string]interface{}"

### ISSUE THREAD

**Issue by sparklepanic** [gohugoio/hugo#13001]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

hugo v0.126.2+extended linux/amd64 BuildDate=2024-07-18T00:00:00+00:00 VendorInfo=Fedora:0.126.2-3.fc41

</pre>

### Does this issue reproduce with the latest release?

Yes. After updating to Fedora 41, this error occurs during the command `hugo server` or `hugo`.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
