### ISSUE TITLE
Embedded "comment" shortcode

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#13010]
Although I dislike embedding opinionated shortcodes, given the changes in v0.137.0 (raw HTML warnings) a comment shortcode might make sense:

```text
{{- $noop := .Inner -}}
```

Obviously this is not opinionated.

I'm in the process of writing a tips and trick article for the forum, and part of that document explains what to do instead of using HTML comments in Markdown. So instead of each site and theme author having to reinvent the wheel, perhaps we should embed one.

**Comment by bep** [comment]
>we should embed one.

We should.

**Comment by Lruihao** [comment]
@jmooring @bep 
Hey guys, I would like to know if it is possible to support an extended markdown format like [obsidian comments](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Comments).

```markdown
This is an %%inline%% comment.

%%
This is a block comment.

Block comments can span multiple lines.
%%
```
