### ISSUE TITLE
Alias Page.Scratch to Page.Store 

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#13016]
This was prompted by:
<https://discourse.gohugo.io/t/strange-behavior-with-scratch-variable/52288>

That topic is not unique. I estimate this comes up every couple of months.

Deprecating `Page.Scratch` would generate a lot of noise given the number of templates that still use a `Page.Scratch` instead of a variable. This is a hangover from [v0.48.0](https://gohugo.io/news/0.48-relnotes/) and earlier where you could not assign a new value to a variable once it had been initialized. So aliasing one to the other seems like a kinder approach.

We would also update the `Page.Scratch` documentation, noting that you should use `Page.Store` instead and that `Page.Scratch` will probably be removed at some point in the future... sort of a soft deprecation.

The shortcode-scoped Scratch would remain as-is.

**Comment by bep** [comment]
Yea, the original motivation of adding a new method and not change the old one was to prevent breaking change, but I guess it will fix 99 issues for every breakage, so yea.

**Comment by irkode** [comment]
Keep in mind, that currently `Scratch`and `Store`are different containers, so you can have both on one page - guess there are not too many users using it - but also a breaking change imho worth mentioning in the docs/release notes

```
   {{ .Scratch.Set "value" "scratch" }}                   # initialize the scratch
   SCRATCH GET: {{ .Scratch.Get "value" }}                # prints "scratch"
   STORE GET: {{ .Store.Get "value" }}                    # no output
   {{ .Store.Set "value" "store" }}                       # initialize the scratch using same key
   SCRATCH GET: {{ .Scratch.Get "value" }}                # prints "scratch"
   STORE GET: {{ .Store.Get "value" }}                    # prints "store"
```
