### ISSUE TITLE
Simplify URLs of categorys and tags

### ISSUE THREAD

**Issue by lopins** [gohugoio/hugo#13018]
categories/category1/category1.html
categories/category1/category1/index.html
->
categories/category1.html
---
tags/tag1/tag1.html
tags/tag1/tag1/index.html
->
tags/tag1.html
---
Simplify URLs of categorys and tags.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
