### ISSUE TITLE
js.Build's `sourceMap` doesn't work with `resources.Fingerprint`

### ISSUE THREAD

**Issue by mehaase** [gohugoio/hugo#13027]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.136.0+extended darwin/amd64 BuildDate=2024-10-15T13:17:24Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

n/a

### Description

I am using JSBuild to bundle and minify a script I wrote. I am also using resources.Fingerprint for cache busting.

```html
{{ with resources.Get "js/search.js" | js.Build (dict "minify" true "sourceMap" "external") |
resources.Fingerprint }}
    <script src="{{ .RelPermalink }}"></script>
{{ end }}
```

Unfortunately, the sourceMap produced is called `search.js.map` but should be called `search.js.<HASH>.map`. Since it doesn't match the fingerprinted filename, the browser can't find it and use it.

**Comment by jmooring** [comment]
Typically the transpiler code would look something like this:

```text
{{ with resources.Get "js/main.js" }}
  {{ $opts := dict
    "minify" hugo.IsProduction
    "sourceMap" (cond hugo.IsDevelopment "external" "")
    "targetPath" "js/main.js"
  }}
  {{ with . | js.Build $opts }}
    {{ if hugo.IsDevelopment }}
      <script src="{{ .RelPermalink }}"></script>
    {{ else }}
      {{ with . | fingerprint }}
        <script src="{{ .RelPermalink }}" integrity="{{ .Data.Integrity }}" crossorigin="anonymous"></script>
      {{ end }}
    {{ end }}
  {{ end }}
{{ end }}
```

In the above:

Action|Development environment|Production environment
:--|:-:|:-:
fingerprint|:x:|:heavy_check_mark:
minify|:x:|:heavy_check_mark:
create source map|:heavy_check_mark:|:x:

**Comment by mehaase** [comment]
That makes sense, thank you.
