### ISSUE TITLE
--minify produces broken xml when escaping

### ISSUE THREAD

**Issue by WhyNotHugo** [gohugoio/hugo#13034]
<pre>
> hugo version
hugo v0.138.0+extended linux/amd64 BuildDate=unknown
</pre>

`hugo` produces:

```
[...]
tree.&lt;/p&gt;</description>
```

`hugo --minify` produces:

```
[...]
tree.&lt;/p></description>
```

The end result is invalid XML. The issue started manifesting upon applying this commit: https://git.sr.ht/~whynothugo/whynothugo.nl/commit/60d69edb59f2c0514061dfb9bf2c01b98353dacf

The commit introduces the line immediately after the broken code.

The linked repository should serve as a reproduction example; it requires no special setup.

**Comment by bep** [comment]
>hugo --minify produces:

I'm a little confused, but I will check; we only apply minification to HTML output (e.g. not XML files).

**Comment by jmooring** [comment]
> The end result is invalid XML. 

Why is it invalid? 

```text
<description>&lt;p>This is a paragraph.&lt;/p></description>
```

With the above, an XML consumer parses the `description` tag as:

```text
<p>This is a paragraph.</p>
```

**Comment by bep** [comment]
>XML is minified. 

You are right, my memory is faded.

**Comment by jmooring** [comment]
@WhyNotHugo This is not a bug. If you want to add a `<content:encoded>` element to your XML, you need to add a namespace:

```text
<rss version="2.0"
  xmlns:atom="http://www.w3.org/2005/Atom"
  xmlns:content="http://purl.org/rss/1.0/modules/content/">
```

And when you do this, it doesn't matter whether you minify or not... both produce valid xml.

Please use the [forum](https://discourse.gohugo.io/) if you have further questions.
