### ISSUE TITLE
Add --silence-deprecation Dart Sass options (slice?)

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#13045]
I would like to request a feature to silence deprecation warnings from Dart Sass.

```html
{{ $css := resources.Get "index.scss" | toCSS (dict
  "transpiler" "dartsass"
  "silenceDeprecation" "import"
) }}
```

Reference: https://sass-lang.com/blog/import-is-deprecated/#controlling-deprecation-warnings

**Comment by bep** [comment]
We're not adding any "special option" for Dart Sass, but we could probably make it work so you can do:

```
ignoreLogs = ["dartsass-deprecations"]
```

Or something.

**Comment by bep** [comment]
Note that these options must be passed via the protobuf API (https://github.com/bep/godartsass); I assume they are also available there and not just as CLI flags.
