### ISSUE TITLE
Build keeps localhost as url

### ISSUE THREAD

**Issue by cibersheep** [gohugoio/hugo#13052]
<pre>
$ hugo version 0.138.0 snap
$ OS Ubuntu 24.04
$ Theme re-terminal
</pre>

Site structure
![image](https://github.com/user-attachments/assets/44b0cb71-c1ec-48ae-af72-2a24fa6ba974)

When `hugo server` site works fine.

If I build the site `hugo` only index will show baseUrl, other pages/* will show localhost:!313

`<link rel="canonical" href="http://localhost:1313/pages/donacions/" />`

If I try to replace the baseUrl with `hugo -b "url1"` only main index page will show the url1 in the code.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by cibersheep** [comment]
Just for future references:
- pages weren't being build.
- use `_index.md` not `index.md` in root folder

More useful link: https://gohugo.io/content-management/page-bundles/
