### ISSUE TITLE
GitHub release for v0.138.0 gone/deleted ?

### ISSUE THREAD

**Issue by dvdksn** [gohugoio/hugo#13066]
It seems like the GH release for v0.138.0 was deleted sometime today. Probably unintentional?

https://github.com/gohugoio/hugo/releases/tag/v0.138.0

**Comment by MrHinsh** [comment]
@bep this has caused some nock on effects as folks automated builds fail...

![image](https://github.com/user-attachments/assets/e83a4344-4eaf-4eeb-a9e8-b23bd79fc495)

```
Hugo version: 0.138.0
##[debug]Hugo extended: true
##[debug]Operating System: Linux
##[debug]Processor Architecture: 64bit
##[debug]toolURL: https://github.com/gohugoio/hugo/releases/download/v0.138.0/hugo_extended_0.138.0_Linux-64bit.tar.gz
##[debug]homeDir: /home/runner
##[debug]workDir: /home/runner/actions_hugo
##[debug]binDir: /home/runner/actions_hugo/bin
##[debug]tempDir: /home/runner/actions_hugo/_temp
##[debug]Downloading https://github.com/gohugoio/hugo/releases/download/v0.138.0/hugo_extended_0.138.0_Linux-64bit.tar.gz
##[debug]Destination /home/runner/work/_temp/e86f1ea7-8f8c-4f16-ae92-f7e811f80a06
##[debug]Failed to download from "https://github.com/gohugoio/hugo/releases/download/v0.138.0/hugo_extended_0.138.0_Linux-64bit.tar.gz". Code(404) Message(Not Found)
Error: Action failed with error Unexpected HTTP response: 404
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Setup Hugo
```

Im guess it was either unintentional or there was something wrong with the release.

**Comment by bep** [comment]
Yea,  that's me. I needed to re-start the 0.139 release, and I remember some confusion when the delete didn't work and I guess I forgot which release was the current. I'm not sure this is (easily) fixable, though, so I suggest you upgrade or downgrade.

**Comment by bep** [comment]
Well, I guess I can rebuild the release tag ...

**Comment by MrHinsh** [comment]
Its a github action that installs Hugo. 

My note is this has taken out folks builds... looks like there was an issue with 1.32 as well according to the errors listed on the other repo.

**Comment by MrHinsh** [comment]
\No idea how long it takes Githubs cache to expire on "latest".

**Comment by bep** [comment]
The release is back; whether this fixes everything, I don't know -- but it's the best I can do.
