### ISSUE TITLE
Base template slots not filled on 404 page

### ISSUE THREAD

**Issue by Cynosure-North** [gohugoio/hugo#13068]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.139.0-dacef0df92a9a20072b4eaa42003e1a63ace8f41+extended linux/amd64 BuildDate=2024-11-18T16:17:45Z VendorInfo=hugomods
</pre>

I've bisected with past releases and this error seems to have been introduced in release 0.123.0

### Does this issue reproduce with the latest release?
Yes

### Issue

Hugo does not use the base template overrides for 404 pages,  resulting in missing or incomplete pages.

The example below shows the define block being ignored. 

layouts/404.html
```
<h1>404 example</h1>

{{ define "main" }}
  <h1>404 Not Found</h1>
  <p>The page you requested cannot be found.</p>
  <p>
    <a href="{{ .Site.Home.RelPermalink }}">
      Return to the home page
    </a>
  </p>
{{ end }}

{{ if eq 1 1 }}
  <p>true</p>
{{ else }}
  <p>false</p>
{{ end }}

```

public/404.html
```
<h1>404 example</h1>




  <p>true</p>

```

\
\
This example shows there is no 404.html generated in the public folder

layouts/404.html
```
{{ define "main" }}
  <h1>404 Not Found</h1>
  <p>The page you requested cannot be found.</p>
  <p>
    <a href="{{ .Site.Home.RelPermalink }}">
      Return to the home page
    </a>
  </p>
{{ end }}
```

**Comment by jmooring** [comment]
<https://gohugo.io/templates/base/#override-the-base-template>

> Code that you put outside the block definitions can break your layout. This even includes HTML comments. For example...

**Comment by bep** [comment]
See @jmooring 's comment. This is unfortunate, but this is a limitation of Go templates, and not something we can fix.

**Comment by Cynosure-North** [comment]
This doesn't explain the second example in which nothing is generated.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
