### ISSUE TITLE
hugo v0.139.0+extended linux/amd64 

### ISSUE THREAD

**Issue by ThomasGehPunkt** [gohugoio/hugo#13072]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.139.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Hello, we use a CI/CD job for creating the webpage with an docker executor and apline.

Just now we realized that the new version has not anymore an Flag --verbose (-v) which let the whole job exiting with failure.

"hugo --buildFuture --logLevel info -v" <-- not working
and
"hugo --buildFuture --logLevel info" <-- working

This seems like a bug in the newest version.

**Comment by bep** [comment]
It was deprecated for a year (warning then error) then removed. Use `--logLevel info`.
