### ISSUE TITLE
`hugo list all` warnings are being sent to stdout 

### ISSUE THREAD

**Issue by BrianLeishman** [gohugoio/hugo#13074]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.136.0-DEV-5c212a5e39af88ba2acd4561b6bf14e75ee9665e+extended linux/amd64 BuildDate=2024-10-02T19:00:35Z
</pre>

### Does this issue reproduce with the latest release?
Yes

---

My issue is that I use hugo cmds for automations, and if those cmds give error/warning messages, they are also being directed towards stdout, instead of what I'd expect; stderr. For example:

```shell
$ hugo list all
WARN  Hugo front matter key "type" is overridden in params section.
You can suppress this warning by adding the following to your site configuration:
ignoreLogs = ['warning-frontmatter-params-overrides']
path,slug,title,date,expiryDate,publishDate,draft,permalink,kind,section
```

This extra output at the top is breaking my parsing the csv output of this command, and it would be very nice if it was in stderr instead.

**Comment by bep** [comment]
We should fix this, not sure what's the history here. You could do `hugo list all --logLevel error` as a workaround.
