### ISSUE TITLE
Please consider adding a command to generate `jsconfig.json`

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#13096]
Hi, the `jsconfig.json` is really useful for development, however it won't be created without using `js.Build` (correct me if I'm wrong).

Take nested modules development as an use case, which does not invoke `js.Build` directly.

```ts
// example.org/a/assets/modules/a/index.ts
export const a = () => {}
```

I'd like to generate a `jsconfig.json` inside `b` module's assets via a Hugo command (e.g. `hugo mod jsconfig gen`), to enable the intellisense feature.

```ts
// example.org/b/assets/modules/b/index.ts
import { a } from 'modules/a'

console.log(a())
```

**Comment by bep** [comment]
>js.Build (correct me if I'm wrong).

That is correct. 

>Take nested modules development as an use case, which does not invoke js.Build directly.

Why not?

>hugo mod jsconfig gen

How would this work? What should it include?

**Comment by razonyang** [comment]
> How would this work? What should it include?

I tested it on VS code with the same form of `jsconfig.json` generated by `js.Build` (put it under the `/assets` folder of current module/project), and it works.

![image](https://github.com/user-attachments/assets/661affd8-069e-4b08-a06f-de1f04783732)

**Comment by razonyang** [comment]
I tried different configurations again, but autocomplete was not working until I imported the package once.

It's more complex than I initially thought. I'll post a working format if I find it.

**Comment by bep** [comment]
> I'll post a working format if I find it.

So, I think I understand the format (I fiddled with this back when I implemented the `js.Build` setup), but ...

* With `js.Build` I know what JS source folder are in use and where.
* With `hugo mod jsconfig gen`, that is not obvious.
* Also, with `js.Build`, the config is always up-to-date, which is important when the source moves (e.g. by using module workspaces or replacements in `go.mod`)

Also, I suspect in most situations it's practical to do module JS dev with something that runs, e.g. a test project that pulls in one or modules and ... build it with `js.Build`, which gives you what you want.

**Comment by razonyang** [comment]
> With hugo mod jsconfig gen, that is not obvious.

Yes, it's not obvious, I have a simple implementation that maps `paths` by looping through dependency mounts even they are not being imported.

> Also, I suspect in most situations it's practical to do module JS dev with something that runs, e.g. a test project that pulls in one or modules and ... build it with js.Build, which gives you what you want.

Thank you, I will give this approach a try.

**Comment by bep** [comment]
>Thank you, I will give this approach a try.

I assume you have seen this, but workspaces can be really useful for "these" kinds of things:

https://gohugo.io/hugo-modules/use-modules/#module-workspaces

**Comment by razonyang** [comment]
Thank you for providing a comprehensive solution.

I think of a solution that publish the `types` only to NPM, it's static *mapping* rather than dymanic, which maybe much useful and easier to set up.

This request doesn't make much sense, so I'm closing it.

Thank you for taking time on this again.
