### ISSUE TITLE
Text overflow in code block

### ISSUE THREAD

**Issue by arcenik** [gohugoio/hugo#13095]
On the main page and the posts page, code overflow out the of pre code block

![image](https://github.com/user-attachments/assets/124394be-e4f3-4874-83e8-15e5535f446d)

But if I add a overflow: auto in the css

![image](https://github.com/user-attachments/assets/bde7d672-c360-4d98-b342-bab355c67bb3)

Then the problem is fixed and a scroll bar appear when needed

![image](https://github.com/user-attachments/assets/a22b3395-bc0e-4a7a-9ae7-1dc57b3993db)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.139.2+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
