### ISSUE TITLE
Deploy from an existing github pages repo 

### ISSUE THREAD

**Issue by zjjzeng** [gohugoio/hugo#13099]
Hi team, I hope to write blogs in my previous personal pages built on my old laptop. I installed hugo on my mac and cloned my github pages repo into the public directory under hugo site folder. But I didn't have post files and couldnot rebuild the website, based on the repo. Will any tool be added by hugo to solve this kind of problems? Thanks.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
