### ISSUE TITLE
Improve attribute handing in the embedded link, image, and table render hooks

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#13104]
```text
{{- printf " %s=%q" $k $v | safeHTMLAttr }}
```

Per [this comment](https://github.com/gohugoio/hugo/pull/13100#issuecomment-2514228130), remove the construct above from the:
- [embedded link render hook](https://github.com/gohugoio/hugo/blob/487bb96474363070a9b5b22ce4640f80329e91e4/tpl/tplimpl/embedded/templates/_default/_markup/render-link.html) 
- [embedded image render hook](https://github.com/gohugoio/hugo/blob/487bb96474363070a9b5b22ce4640f80329e91e4/tpl/tplimpl/embedded/templates/_default/_markup/render-image.html)
- [embedded table render hook](https://github.com/gohugoio/hugo/blob/487bb96474363070a9b5b22ce4640f80329e91e4/tpl/tplimpl/embedded/templates/_default/_markup/render-table.html)

For the link render hook this is a trivial change that will have no effect on existing sites; you cannot apply Markdown attributes to links.

Changing the others will require some thought, perhaps limiting which of the Markdown attributes to add and how to add them (e.g., `id`, `class`, `style`, `loading`, `width`, `height`, etc.).

**Comment by bep** [comment]
Note that my comment was about converting arbitrary parameters from shortcode `Params` into HTML attributes.

For render hooks, we have validation in place, so `onClick` e.g. should not be passed on to the hook. You could argue that we could do similar with shortcode, but that's hard to do in a general way.
