### ISSUE TITLE
Improve .Page.Fragments.ToHTML

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#13107]
The [`Fragments.ToHTML`](https://github.com/gohugoio/hugo/blob/487bb96474363070a9b5b22ce4640f80329e91e4/markup/tableofcontents/tableofcontents.go#L136-L149) method on `Page` takes three arguments:

```text
func (toc *Fragments) ToHTML(startLevel, stopLevel int, ordered bool) template.HTML {
  ...
}
```

It would be convenient to pass site and/or page parameters to this method, something like:

```text
{{ .Fragments.ToHTML (.Param "toc.startLevel") (.Param "toc.endLevel") true }}
```

The above throws an error with JSON and TOML site/page parameters because the values are unmarshaled to `float64` (JSON) or `int64` (TOML). You can work around this with:

```text
{{ .Fragments.ToHTML (.Param "toc.startLevel" | int) (.Param "toc.endLevel" | int) true }}
```

But it would easier if the method signature were...

```text
func (toc *Fragments) ToHTML(startLevel, stopLevel any, ordered bool) template.HTML {
  ...
}
```

... with `cast.ToIntE`, etc.

**Comment by bep** [comment]
Yea, we could do this (I wish Go generics could help us with this, but I don't think so). Note that should be possible to do:

```handlebars
{{ .Fragments.ToHTML (.Param "toc.startLevel" | int) (.Param "toc.endLevel" | int) true }}
```
