### ISSUE TITLE
Page parameters are not parsed properly when an HTML comment is placed above

### ISSUE THREAD

**Issue by jakubg1** [gohugoio/hugo#13117]
### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
hugo v0.139.3 linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
I'm sure about that, I've tested this on both v0.126.2 and to be sure I've built the newest version from source today. This issue did not appear on the v0.120.4 version, although I did not do proper bisecting yet to confirm which version exactly this bug has been introduced in.

### The Issue
Whenever I'm defining page parameters in the TOML format in a markdown file, I can access them in the templates using blocks like `{{ .Params.title }}` or `{{ .Params.author }}`. Here's an example of that:
```
+++
title = "Article 1"
subtitle = "Lorem ipsum dolor sit amet."
date = "2020-04-01"
thumbnail = "news2.png"
+++
```
However, whenever I put an HTML comment on the line above, like so:
```
<!-- A pesky comment -->
+++
title = "Article 1"
subtitle = "Lorem ipsum dolor sit amet."
date = "2020-04-01"
thumbnail = "news2.png"
+++
```
the parameters are no longer accessible and the following warning appears in the console:
```
WARN  Raw HTML omitted while rendering <file>; see https://gohugo.io/getting-started/configuration-markup/#rendererunsafe
You can suppress this warning by adding the following to your site configuration:
ignoreLogs = ['warning-goldmark-raw-html']
```
Adding the aforementioned to the configuration suppresses the message, but does not fix the problem. The parameters still can not be accessed.

I've made a somewhat-bare-bones example for better illustration: 
[site_bug.zip](https://github.com/user-attachments/files/18044999/site_bug.zip)

When you launch a Hugo server in this directory and open `localhost:1313`, you will see a broken image link. However, when you remove the comment from the `content/news/article1.md` file and save it, the image will properly show up on the main page as the image name is properly passed as a parameter.
That same image will show up regardless of whether the comment exists in an older version such as v0.120.4.

As a person who is extensively using comments in the content files, I'm looking forward to seeing this bug fixed or an alternative solution recommended! I've looked around and it seems like Markdown does not support comments on its own :)

**Comment by jmooring** [comment]
The current behavior is intentional. 

With v0.123.0 and later, content files must start with a front matter delimiter, optionally preceded by whitespace. To add a comment near the top of your file, add a comment within the TOML or YAML front matter:

```yaml
---
# Your comment here.

title: Example
date: 20204-04-01
---
```

With v0.137.1 and later, use the the [comment shortcode](https://gohugo.io/content-management/shortcodes/#comment) to add comments to the body of your Markdown. You can learn more about this change [here](https://discourse.gohugo.io/t/warning-when-mixing-html-and-markdown/52280).

**Comment by jakubg1** [comment]
Alright, thank you for explanation! I'm sorry that I haven't catched this one, I should have!
