### ISSUE TITLE
Destructive transformation of inlined php code with --minify

### ISSUE THREAD

**Issue by doompadee** [gohugoio/hugo#13115]
### What version of Hugo are you using (`hugo version`)?

0.139.3

### Does this issue reproduce with the latest release?

Yes

Hugo fails to correctly minify inlined php code.

Repro: https://github.com/doompadee/hugo-minify-bug

`content/index.md`
```markdown
one
<?php
require $_SERVER['DOCUMENT_ROOT'] . 'test.php';
$form = new Form();
if ($form->submitted()) {
  $form
    ->recipient('recipient@nospam.com', 'Name')
    ->subject('Subject')
    ->rules([
      'name' => 'required',
      'email' => 'required',
      'message' => 'nolink',
    ])
    ->process();
}
?>
two
```

`hugo --minify` yields

`public/index.html`

    <p>one</p>submitted()) {
    $form
    ->recipient('recipient@nospam.com', 'Name')
    ->subject('Subject')
    ->rules([
    'name' => 'required',
    'email' => 'required',
    'message' => 'nolink',
    ])
    ->process();
    }
    ?><p>two</p>

**Comment by bep** [comment]
Inline PHP in HTML? Isn't it better to output `*.php` files? I'm pretty sure that PHP isn't valid HTML5, and I wouldn't expect any HTML minifier to handle it (unless wrapped in `<script>` tags with a proper type).

**Comment by doompadee** [comment]
> Inline PHP in HTML? Isn't it better to output `*.php` files?

Of course, but in this case I need to work with what I've been given. A web server can be configured to let the php interpreter handle `.html` files as well.

Ideally, Hugo should not touch the `<php? ... ?>` markup. The production file contains (well should at the end) several tags, and it seems the first one with an `->` operator gets thrashed. In the example:
    
    <?php
    require $_SERVER['DOCUMENT_ROOT'] . 'test.php';
    $form = new Form();
    if ($form->

seems to be misinterpreted as a removable tag. If Hugo minification can't (or shouldn't) be adjusted, I need to switch to a less general solution. Just wanted to let you know in case it's something that can be addressed. Thanks much for your time.

**Comment by bep** [comment]
The "destructive transformation" you're talking about happens in https://github.com/tdewolff/minify and its HTML minifier, so you need to ask on that issue tracker.

**Comment by doompadee** [comment]
OK, will report upstream. No need to have an open ticket here as well. Thanks.

**Comment by jmooring** [comment]
To mix PHP code with markdown, you need to:

1) Configuring the HTML minifier to ignore everything between and including the PHP tags
2) Configure the Markdown renderer to allow raw HTML

```text

[minify.tdewolff.html]
templateDelims = ['<?php', '?>']

[markup.goldmark.renderer]
unsafe = true
```

The configuration above is safe if  _you_ control the content.

With that site configuration, this Markdown:

```text
I am a **bold** word.

<?php
echo 'Hello, World!';
?>

I am an _emphasized_ word.

I am an <?php=$inline;?> variable.
```

Is rendered to:

```html
<p>I am a <strong>bold</strong> word.</p>
<?php
echo 'Hello, World!';
?>
<p>I am an <em>emphasized</em> word.</p>
<p>I am an <?php=$inline;?> variable.</p>
```

**Comment by doompadee** [comment]
> To mix PHP code with markdown, you need to:

Thanks very much for chiming in. The minify lead already pointed me in the right direction. Somehow I've missed the corresponding configuration section in the docs. My apologies.
