### ISSUE TITLE
Link led to malware site

### ISSUE THREAD

**Issue by betaboy99** [gohugoio/hugo#13125]
Hi,

First time Hugo user. I like what I see so far. I'm in the middle of setting up my first project. 
On the https://gohugo.io/functions/css/postcss/ page under Setup there is a link called PostCSS plugins. I clicked on it to see what I can find there. I was directed to a page that displayed fake virus alert and to download a product to get rid of it. 

The link address when hovered over is: https://www.postcss.parts/

![image](https://github.com/user-attachments/assets/6a0c5e78-fe1a-40ef-af88-4b310a1cd2fa)

**Comment by jmooring** [comment]
Thanks for  letting us know. I've updated the link.
