### ISSUE TITLE
[esbuild] expose the `platform` option to bundle code run on node

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#13136]
Dear Hugo team, I'd like request a feature to specify the `platform` option of esbuild.

**Backgrounds**

There are many static site hosting platforms that support serverless functions (e.g. Cloudlfare Worker), it would be great if we could bundle JavaScript code that runs on node, which provides better integration capabilities.

With the esbuild `platform` option, Hugo can be a Node application packing tool.

**Pros**

1. It's easy to manage, share, and reuse codes between sites through Hugo Modules.
2. Manage configuration in the same place (hugo.yaml and the `params` option of `js.Build`).

I am willing to implement it (I have a working local branch) if this request is accepted.

**Comment by bep** [comment]
Can you elaborate a little about how this ends up in e.g. a Cloudflare worker?

**Comment by razonyang** [comment]
Sure, Cloudflare Pages offer an [advanced mode](https://developers.cloudflare.com/pages/functions/advanced-mode/) for serverless functions, which the entry point is `_worker.js` in output directory (`public`).

However, currently `js.Build` can not bundle code that runs on node, for example,

```
import { platform } from 'process';

console.log(platform)
```

It will result in an error when importing Node built-in modules.

```log
...Could not resolve "process"...
```

With the `platform` option, Hugo will have the ability to build Node app to integrate with serverless functions.
