### ISSUE TITLE
tpl/collections: Allow querify to accept a map argument

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#13131]
The [`collections.Querify`](https://gohugo.io/functions/collections/querify/) template function accepts either of the following argument forms:

```text
{{ collections.Querify "a" 1 "b" 2 }}         --> a=1&b=2
{{ collections.Querify (slice "a" 1 "b" 2) }} --> a=1&b=2
```

But it would convenient if we could do:

```text
{{ collections.Querify (dict "a" 1 "b" 2) }}
```

For example, in our [embedded youtube shortcode] we:

[embedded youtube shortcode]: https://github.com/gohugoio/hugo/blob/989b299b55d3fb48f8447ea69e85e26ee9dc7795/tpl/tplimpl/embedded/templates/shortcodes/youtube.html#L76-L94

1. Build a map of parameters
2. Convert the map into a slice with this construct:

    ```text
    {{ range $k, $v := $params }}
      {{ $s = $s | append $k }}
      {{ $s = $s | append $v }}
    {{ end }}
    ```
3. Pass the slice to `collections.Querify`

It would be more elegant if we could remove step 2 above.

**Comment by bep** [comment]
>{{ collections.Querify (dict "a" 1 "b" 2) }}

We need to remember to sort the keys.

**Comment by bep** [comment]
>So unless I'm missing something, I think that covers the sort.

You're right, I didn't look at the code.
