### ISSUE TITLE
hugo v0.139.4 has wrong version output

### ISSUE THREAD

**Issue by domrim** [gohugoio/hugo#13137]
### What version of Hugo are you using (`hugo version`)?
I've installed hugo 0.139.4 (`go install --tags extended github.com/gohugoio/hugo@v0.139.4`), but:

<pre>
$ hugo version
hugo v0.140.0-DEV
</pre>

### Does this issue reproduce with the latest release?
yeah, this is the latest release. the commit 39c260b5c9d394428acdf6f975ee72f437d97fb5 seems to be the issue in the branch.

**Comment by bep** [comment]
It was a glitch, nothing to be done about it.
