### ISSUE TITLE
Issue with the Go sum database and `v0.139.4`

### ISSUE THREAD

**Issue by LukasGelbmann** [gohugoio/hugo#13147]
It seems that the wrong commit of Hugo is cached in the `proxy.golang.org` mirror and `sum.golang.org` checksum database for `v0.139.4`.

```
$ GOPROXY=direct go mod download github.com/gohugoio/hugo@v0.139.4
go: github.com/gohugoio/hugo@v0.139.4: verifying module: checksum mismatch
	downloaded: h1:kWMmda3dGc5n+cS7W+dgrMxmfTn3vDU1aqfDy/6hIEs=
	sum.golang.org: h1:KvHVT234Kyd3WrjZ83TWuFT3VEf95k2ahqeTV+Z635c=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

```
$ go install -v github.com/gohugoio/hugo@v0.139.4
[...]
$ hugo version
hugo v0.140.0-DEV linux/amd64 BuildDate=unknown
```

### What version of Hugo are you using (`hugo version`)?

```
v0.139.4
```

**Comment by bep** [comment]
I made a mistake and had to restart the release (and by so deleting the release tag). I obviously didn't do this fast enough, so people had `go install`ed the new version.

If someone can point me to a simple way to fix this in the sum database, I can do it. Else I suspect that you wait for `v0.140` (coming next week) or install a binary or clone and build the source.

Either way. With the way Hugo releases (the tag is created as the very last step), this should (almost) never happen. I just forgot and created the issue manually ... And starting over with a new tag would be too much work. Or, so I thougtht.

**Comment by bep** [comment]
OK, I have just started a build for v0.139.5 which will be the same as v0.139.4, which should solve this. Will be out in 10-15 minutes. I'm closing this early.

**Comment by LukasGelbmann** [comment]
Thank you for the quick response. I guess this means this issue only affects people installing Hugo v0.139.4 from source using the standard `go install` toolchain -- as well as any Go projects that depend on `github.com/gohugoio/hugo` v0.139.4. These will all get the mistaken release through the `proxy.golang.org` mirror.

> If someone can point me to a simple way to fix this in the sum database

Sadly, I don't think this is possible. It's immutable by design as far as I understand.

> I have just started a build for v0.139.5

Thank you! It doesn't seem like there's much else you can do. I suppose you could [retract](https://go.dev/ref/mod#go-mod-file-retract) the v0.139.4 version, but I have no experience whatsoever with that.

**Comment by bep** [comment]
https://github.com/gohugoio/hugo/releases/tag/v0.139.5

**Comment by ALF-eV** [comment]
Hey, any chance the remaining assets could be included in v0.139.5?

Right now it only has the source code, so downloading the latest deb using the API isn't working.

Thanks in advance.

**Comment by ALF-eV** [comment]
FWIW, the workaround I found for downloading the latest release _that has a deb_ was to change my command from
`curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep -oP '"browser_download_url": "\K(.*)hugo_extended(.*)linux-amd64.deb' | wget -i -`
to
`curl -s https://api.github.com/repos/gohugoio/hugo/releases | grep -oP '"browser_download_url": "\K(.*)hugo_extended(.*)linux-amd64.deb'| head -n 1 | wget -i -`
That is, get list of releases, instead of latest, and choose the latest to have a deb file.

**Comment by max-sixty** [comment]
Would be great to get a release with release assets if possible! An action we rely on transitively relies on them... https://github.com/gohugoio/hugo/issues/13147
