### ISSUE TITLE
hugo v0.139.4-3afe91d4b1b069abbedd6a96ed755b1e12581dfe+extended linux/amd64 BuildDate=2024-12-09T17:45:23Z VendorInfo=snap:0.139.4

### ISSUE THREAD

**Issue by ScoutmanPt** [gohugoio/hugo#13148]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.139.4-3afe91d4b1b069abbedd6a96ed755b1e12581dfe+extended linux/amd64 BuildDate=2024-12-09T17:45:23Z VendorInfo=snap:0.139.4
</pre>

### Does this issue reproduce with the latest release?
yes

### Issue
Hi, I'm using this hugo template https://github.com/gethugothemes/andromeda-light-hugo , dont have any site.Social or site.Authors on any html template\code  and im still getting this

_ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.140.0. Implement taxonomy 'social' or use .Site.Params.Social instead.
ERROR deprecated: .Site.Authors was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.140.0. Implement taxonomy 'authors' or use .Site.Params.Author instead._

Help?
<img width="237" alt="image" src="https://github.com/user-attachments/assets/7771b46b-d2f1-48f1-bf94-983f809de554" />

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
