### ISSUE TITLE
0.139.5 release is missing assets causing GitHub workflow to fail

### ISSUE THREAD

**Issue by somethingSTRANGE** [gohugoio/hugo#13150]
My automated GitHub Actions workflow fails due to missing assets in the 0.139.5 release.

> ##[debug]Failed to download from "https://github.com/gohugoio/hugo/releases/download/v0.139.5/hugo_extended_0.139.5_Linux-64bit.tar.gz". Code(404) Message(Not Found)
> Error: Action failed with error Unexpected HTTP response: 404

The 0.139.5 release only contains:

1. Source code (zip)
1. Source code (tar.gz)

Previous releases had ~29 assets, such as this list from 0.139.4:

1. hugo_0.139.4_checksums.txt
1. hugo_0.139.4_darwin-universal.tar.gz
1. hugo_0.139.4_dragonfly-amd64.tar.gz
1. hugo_0.139.4_freebsd-amd64.tar.gz
1. hugo_0.139.4_Linux-64bit.tar.gz
1. hugo_0.139.4_linux-amd64.deb
1. hugo_0.139.4_linux-amd64.tar.gz
1. hugo_0.139.4_linux-arm.tar.gz
1. hugo_0.139.4_linux-arm64.deb
1. hugo_0.139.4_linux-arm64.tar.gz
1. hugo_0.139.4_netbsd-amd64.tar.gz
1. hugo_0.139.4_openbsd-amd64.tar.gz
1. hugo_0.139.4_solaris-amd64.tar.gz
1. hugo_0.139.4_windows-amd64.zip
1. hugo_0.139.4_windows-arm64.zip
1. hugo_extended_0.139.4_darwin-universal.tar.gz
1. hugo_extended_0.139.4_Linux-64bit.tar.gz
1. hugo_extended_0.139.4_linux-amd64.deb
1. hugo_extended_0.139.4_linux-amd64.tar.gz
1. hugo_extended_0.139.4_linux-arm64.deb
1. hugo_extended_0.139.4_linux-arm64.tar.gz
1. hugo_extended_0.139.4_windows-amd64.zip
1. hugo_extended_withdeploy_0.139.4_darwin-universal.tar.gz
1. hugo_extended_withdeploy_0.139.4_Linux-64bit.tar.gz
1. hugo_extended_withdeploy_0.139.4_linux-amd64.tar.gz
1. hugo_extended_withdeploy_0.139.4_linux-arm64.tar.gz
1. hugo_extended_withdeploy_0.139.4_windows-amd64.zip
1. Source code (zip)
1. Source code (tar.gz)

**Comment by simonhollingshead** [comment]
Yes, sadly the newest release has a human readable message of

> "It's the same as https://github.com/gohugoio/hugo/releases/tag/v0.139.4 -- go there for release archives."

in it, but my automated workflows can't read English instructions like that, so they construct a download URL with 0.139.5 in, get a 404, and terminate in a failed state.

Anyone who uses https://github.com/peaceiris/actions-hugo with a version of "latest" will be broken by this, for example.

**Comment by getshhi** [comment]
Yes, I also have this issue

**Comment by bep** [comment]
You need to use 0.139.4.  0.139.5 is there only to make `go install` happy.

**Comment by DeathGarurumon** [comment]
Yeah, I have this problem, too. Setting the version as '0.139.4' is OK.

**Comment by omarkohl** [comment]
I appreciate the hard work you invest into hugo! If at all possible it would be very valuable to add assets to the 0.139.5 release (or add a subsequent release with assets) since this breaks all builds that are relying on "latest" hugo and make people like myself spend half an hour trying to figure out what is going on :cry:

Pinning the version to 0.139.4 and then later remembering to unpin it is a feasible workaround.

**Comment by togarashimayo** [comment]
I'm one of the people who uses `latest` as the Hugo version for my website's build. Also rolled back my version to 0.139.4 as a workaround based on @bep and @omarkohl's prompts.
