### ISSUE TITLE
Latest Hugo release version causing issues in Devcontianers

### ISSUE THREAD

**Issue by Mathiyarasy** [gohugoio/hugo#13157]
### What version of Hugo are you using (`hugo version`)?
In devcontainers we use hugo as a feature installed in our images
We are using latest hugo version: 
Picking the latest version from 'tag_name ' of url: https://api.github.com/repos/gohugoio/hugo/releases/latest
After the latest release we are seeing issue as the package is not found in the latest url: v0.139.5
error : curl: (22) The requested URL returned error: 404
<pre>
$ hugo version
$  curl -fsSLO --compressed "https://github.com/gohugoio/hugo/releases/download/v0.139.5/hugo_extended_0.139.5_Linux-64bit.tar.gz"
</pre>

### Does this issue reproduce with the latest release?
Yes. It occurs only after the latest release.

**Comment by bep** [comment]
This has been raised before. Use the search.
