### ISSUE TITLE
Build withdeploy deb archives

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#13166]
See https://discourse.gohugo.io/t/no-debian-option-for-withdeploy-releases-intentional/52790/3

**Comment by ChrisMcKee** [comment]
Just realised that the deployment portion was split out into a new distribution, as all the github actions stopped working 😂
Missed the note at the top of https://github.com/gohugoio/hugo/releases/tag/v0.137.0 having skipped from 130 to 140. Nice binary size reduction though.
