### ISSUE TITLE
common/loggers: Write PrintTimerIfDelayed output to stdErr

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#13171]
In https://github.com/gohugoio/hugo/pull/13138 we made all logging (info, warn, error) log to `stderr` and let `stdout` be reserved for program output.

When you run `hugo` against a project that includes a module that has not been downloaded yet, this is written to `stdout`:

    hugo: collected modules in 962 ms

If you run the command `hugo list all` before the module has been downloaded, the resulting CSV data is invalid.

If seems like the message above should be logged to `stdErr` instead.

https://github.com/gohugoio/hugo/blob/5d64b492f41ca9f805948f33b47672780f9cea7d/modules/collect.go#L509

https://github.com/gohugoio/hugo/blob/5d64b492f41ca9f805948f33b47672780f9cea7d/common/loggers/logger.go#L270-L279

Can we replace the last line in the above with this?

```go
fmt.Fprintf(l.stdErr, "%s in %v ms", name, milli)
```

**Comment by bep** [comment]
>fmt.Fprintf(l.stdErr, "%s in %v ms", name, milli)

Yes. I will do a patch release, possibly Monday.
