### ISSUE TITLE
Ability to disable section list page routes but have valid routes for pages in that section

### ISSUE THREAD

**Issue by pjebs** [gohugoio/hugo#13185]
I have this folder structure:

**/contents**
↳ **/docs**
&emsp;  ↳ **/core concepts**
&emsp;  &emsp;  ↳ `_index.md`
&emsp;  &emsp;  ↳ `load.md`
&emsp;  &emsp; ↳ `routing.md`
&emsp;  ↳ **/getting started**
&emsp;  &emsp; ↳  `_index.md`
&emsp;  &emsp; ↳  `introduction.md`
&emsp;  &emsp; ↳  `project-structure.md`

### Objective

I want these page routes to list the appropriate page (which it is doing correctly):
```
/docs/core-concepts/load    (page)
/docs/core-concepts/routing (page)
/docs/getting-started/introduction    (page)
/docs/getting-started/project-structure (page)
```

I **want a 404 returned** for these routes instead of currently display the list page for the section
```
/docs/core-concepts/ (section list)
/docs/getting-started/ (section list)
```

I followed the instructions below from : https://gohugo.io/content-management/build-options/#example----publish-without-listing

```
+++
title = 'Core Concepts'
[build]
  list = 'never'
  render = 'never'
+++
```

/docs/core concepts/_index.md
/docs/getting started/_index.md

### Problem

It blocks out the entire route tree. Neither the pages or lists get produced.

**Comment by pjebs** [comment]
@bep Are you saying that it's currently not possible?

**Comment by jmooring** [comment]
I am unable to reproduce the problem as described. Try it:

```text
git clone --single-branch -b hugo-github-issue-13185 https://github.com/jmooring/hugo-testing hugo-github-issue-13185
cd hugo-github-issue-13185
rm -rf public/ && hugo && tree public
```

**Comment by pjebs** [comment]
There does seem to be a bug including in your project:

If you were to run this snippet from within a Page that is in the `Core Concepts` or `Getting Started` section:

```
{{ range site.AllPages }}
        {{ .Section }}. <------- Always prints docs.
{{ end }}


{{ range site.Sections }}
        {{ $section := . }}
        {{ if eq $section.Section "docs" }}
          Arrived Here
          {{ range $section.Pages }}
            {{ . }} <------ Empty
          {{ end }}
        {{ end }}
      {{ end }}
```


I don't seem to be able to find the section name "Core Concepts" or "Getting Started".
I don't seem to be able iterate over the Pages of those Sections either.

It's as if the section's list pages are not rendered (That's what I want), but those sections don't even exist, including for the Pages that are inside those sections!

**Comment by jmooring** [comment]
> Always prints docs.

No matter where you are in the tree under the `content/docs` directory, the `Section` method should return `docs` (a string). See <https://gohugo.io/methods/page/section/>.

> I don't seem to be able to find the section name "Core Concepts" or "Getting Started"

You also said:

> I want a 404 returned for these routes


If you want to list the members of a specific section, even when the section's `list` and `render` build options are `never`, use the `Page.GetPage` method and then range over its children. See <https://gohugo.io/methods/page/getpage/>.

```text
{{ range (.GetPage "/docs/core-concepts").Pages }}
  <h2><a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a></h2>
{{ end }}
```

**Comment by pjebs** [comment]
See: https://discourse.gohugo.io/t/ability-to-get-section-names-programmaticall/52872
