### ISSUE TITLE
`union`, `complement`, `symdiff`, and `intersect` not working with resource collections

### ISSUE THREAD

**Issue by rnwst** [gohugoio/hugo#13181]
### Description

As per the title, the set methods provided for collections do not seem to work with global resources. For example:
```html
{{- $styles := resources.Match "css/**.css" }}
{{- $katex := resources.Match "css/**katex*" }}
{{- $complement := complement $katex $styles }}
```
Here, `$complement` contains all resources from `$styles`, not excluding those also found in `$katex`. The functions `union`, `symdiff`, and `intersect` malfunction in similar ways. `intersect` seems to return an empty collection, irrespective of the resource collections provided.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.140.0+extended linux/amd64 BuildDate=unknown
</pre>

**Comment by jmooring** [comment]
To clarify, this works fine:

```text
{{ $a := resources.Get "a.jpg" }}
{{ $b := resources.Get "b.jpg" }}
{{ $c := resources.Get "c.jpg" }}
{{ $d := resources.Get "d.jpg" }}

{{ $abcd := slice $a $b $c $d }}
{{ $cd := slice $c $d}}

{{ $abcd | complement $cd }}
```

But these do not:

```text
{{ $match := resources.Match "*" }}
{{ $match | complement $cd }}

{{ $byType := resources.ByType "image"}}
{{ $byType | complement $cd }}
```

The problem occurs when working with the collections created by `resources.Match` and `resources.ByType`.
