### ISSUE TITLE
`js.Build`'s `externals` option does not work for /assets

### ISSUE THREAD

**Issue by rnwst** [gohugoio/hugo#13183]
### Description and steps to reproduce

Under `assets`, I have a JS file `script.js` with contents
```js
import '/external.js';
```
The file `external.js` has contents
```js
console.log('This file should not be bundled!');
```
In my template, the script is included as follows:
```html
{{- /* Make sure the resource "external.js" is published. */}}
{{- (resources.Get "external.js").Publish }}

{{- $script := resources.Get "script.js" }}
{{- $opts := dict "format" "esm"
                  "externals" (slice "/external.js")
}}
{{- $script = $script | js.Build $opts }}
  <script type="module" src="{{ $script.Permalink }}"></script>
```

### Actual behaviour

The `externals` option seems to have no effect, and the file `external.js` is included in the bundled `script.js`. The bundled file looks as follows:
```js
// ns-hugo-imp:/home/rnwst/src/hugo-test/assets/external.js
console.log("This file should not be bundled!");

```

### Expected behaviour

`external.js` should not be bundled, and the import statement in `script.js` should be left untouched.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.140.0+extended linux/amd64 BuildDate=unknown
</pre>

**Comment by rnwst** [comment]
I created a reproducing example here: https://github.com/rnwst/hugo-testing/tree/hugo-github-issue-13183

**Comment by bep** [comment]
I think I understand what's happening, and I suspect that this works fine for JS packages living in `node_modules`.

**Comment by rnwst** [comment]
Amazing, thank you for fixing this so quickly! Everything is working as expected on latest master.

Hugo is an awesome project, thank you very much for all your hard work!
