### ISSUE TITLE
Installation and mounting of npm bootstrap causes toCSS generations error

### ISSUE THREAD

**Issue by Int-Circuit** [gohugoio/hugo#13191]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.140.0-3f35721fb2c75a1f7cc5a7a14400b66e73d4b06e+extended linux/amd64 BuildDate=2024-12-17T14:20:55Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

### Bug description
Installing Bootstrap with NPM causes errors in hugo, where it complains that there no provided resources in SCSS to CSS transformation. Mount in the node_modules dir is present in config.
 Here is the error log:
```
Error: error building site: render: failed to render pages: render of "/home/mathis/Documents/Git/Freecad-library_Viewer/content/_index.md" failed: "/home/mathis/Documents/Git/Freecad-library_Viewer/layouts/_default/list.html:3:3": execute of template failed: template: _default/list.html:3:3: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "/home/mathis/Documents/Git/Freecad-library_Viewer/layouts/partials/head.html:14:45": execute of template failed: template: partials/head.html:14:45: executing "partials/head.html" at <toCSS $opts>: error calling toCSS: no Resource provided in transformation
```

Here is the site code:
[code.zip](https://github.com/user-attachments/files/18240273/code.zip)

### Is the bug reproducible?
Yes. Bug was succesfully replicated by @rafaelmardojai on latest version of hugo

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
