### ISSUE TITLE
Surprising `resources.Concat` behaviour

### ISSUE THREAD

**Issue by rnwst** [gohugoio/hugo#13192]
### Description

In one of my templates, I conditionally include a CSS resource in the page depending on the value of a page param:
```html
{{- $styles := resources.Match "css/**.css" }}

{{- if not .Params.containsMath }}
  {{- $styles = where $styles "Name" "ne" "/css/katex.css" }}
{{- end }}

{{- range $styles }}
    <meta content="{{ .Name }}" />
{{- end }}

    <style>
      {{- (resources.Concat "css/styles.css" $styles).Content | safeCSS }}
    </style>
```
However, even if the the page param `containsMath` is `true`, the concatenated CSS does not include the contents of `katex.css`. Curiously, I can see in that case that `katex.css` is part of the collection `$styles`, as the corresponding `<meta>` tag is included in the page, when inspecting `http://localhost:1313/posts/post-2/` using devtools:
![image](https://github.com/user-attachments/assets/339cea43-9a82-455e-8490-6fb8f1d6d143)

### Steps to reproduce

```console
git clone --single-branch -b resources-concat-issue https://github.com/rnwst/hugo-testing.git
cd hugo-testing
hugo server --disableFastRender
```

### Actual behaviour

The CSS file `assets/css/katex.css` is not included in the concatenated CSS, even when the page param `containsMath` is `true` and I can see that it is part of the resource collection `$styles`.

### Expected behaviour

The CSS file `assets/css/katex.css` should be included in the concatenated CSS if it is part of the collection `$styles`.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.140.0+extended linux/amd64 BuildDate=unknown
</pre>

**Comment by rnwst** [comment]
Many thanks @jmooring for explaining why this is happening and also for your solution. Perhaps I should've posted this in the forum before opening an issue.

From the documentation, it was not obvious to me that the resource would not be re-computed when running `resources.Concat` again with a different resource collection but with the same cache key. Maybe it is obvious to others though. I had assumed that the first argument to `resources.Concat` is simply the path under which the concatenated resources would be published, if one was to call the `.Publish` method (although I briefly wonder why this was referred to as a "cache key"). It is also not obvious to me why the result of `resources.Concat` should be cached in the first place. If I it is run again with different inputs, it seems natural to me that the result would be different this time around.

I would be keen to hear your thoughts on whether the documentation needs clarification and whether or not the behaviour of `resources.Concat` should be reconsidered.

Thanks again!

**Comment by jmooring** [comment]
> It is also not obvious to me why the result of `resources.Concat` should be cached in the first place. 

Let's use your example but on a larger scale. Let's say we have a 1000 page site where 100 pages have `containsMath` set to `true` in front matter. With caching we only have to concatenate twice; once with `katex.css` and once without. Without caching we would have to concatenate one combination 100 times, and concatenate the other combination 900 times. That's just silly.

If the results of `resources.Concatenate` we not cached, we'd have to refactor your setup into two partials and conditionally call them with the `partialCached` function so that we can... cache. This is about performance.

> From the documentation, it was not obvious to me that the resource would not be re-computed when running resources.Concat again with a different resource collection but with the same cache key. 

Think about that one for a minute. How would we know we have to re-compute if the cache key is the same?

**Comment by rnwst** [comment]
Thanks for your explanations @jmooring, that makes sense.

On a different note, I noticed that when I remove the lines
```
{{- if not .Params.containsMath }}
  {{- $styles = where $styles "Name" "ne" "/css/katex.css" }}
{{- end }}
```
from the stylesheets template and save it while `hugo server` is running (with `--disableFastRender`), that on the subsequent rebuild the concatenated resource `css/styles.css` does not change - i.e. it still does not include `katex.css`. Therefore it seems that this cache persists across builds, even if the underlying template file changes. Is this expected behaviour? I shall direct any future queries to the forum.
