### ISSUE TITLE
Conditional comparison where field is false causes build to fail and exit.

### ISSUE THREAD

**Issue by skoblenick** [gohugoio/hugo#13207]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.140.2+extended+withdeploy darwin/amd64 BuildDate=2024-12-30T15:01:53Z VendorInfo=brew
</pre>

The issue also existed in 1.4.0.

### Does this issue reproduce with the latest release?

Yes.

### Issue

[Boolean Comparison](https://gohugo.io/functions/collections/where/#boolean-comparison) in collection comparison causes the build/serve command to fail.

I have a data folder containing a structure like:

```yaml
# ./data/en/features.yml
- name: feature 1
  paid: true
- name: feature 2
  paid: false
```

Within my theme I have a partial that contains:

```html
      {{ $lang := .Site.Language.Lang }}
      {{ $data := index .Site.Data $lang }}
      {{ range $index, $feature := where $data.features "paid" false }}
        <li class="grid gap-4">
          <div class="flex flex-col gap-3 items-center align-middle">
            <img class="w-10" src="{{ $feature.icon }}" />
            <h4 class="text-md font-bold">
              {{ htmlUnescape $feature.title }}
            </h4>
          </div>
          <p class="">{{ htmlUnescape $feature.description }}</p>
        </li>
      {{ end }}
```

which causes a failure upon running `hugo serve --bind=0.0.0.0 --watch`:

```sh
Error: error building site: render: failed to render pages: render of "/" failed: "themes/my-theme/layouts/_default/home.html:10:7": execute of template failed: template: _default/home.html:10:7: executing "main" at <partial "features/core" .>: error calling partial: "/themes/my-theme/layouts/partials/features/core.html:31:46": execute of template failed: template: partials/features/core.html:31:46: executing "partials/features/core.html" at <$feature.title>: can't evaluate field title in type interface {}
```

However, the same data and template with the flag set to `true` works as expected. I have also attempted to use:

```html
 {{ range $index, $feature := where $data.features "paid" "eq" false }}
 {{ range $index, $feature := where $data.features "paid" "ne" true }}
```

all with the same result. The only method that I have found works is:

```html
 {{ range $index, $feature := where $data.features "paid" "eq" "false" }}
```

which is less than ideal, as it forces me to change the data types and use a `string` rather than a `bool` value for the `paid` and other `bool` type fields.

## Additional notes:

It's a janky workaround and wouldn't work using `build`, but if I modify the partial to `true` on the launch of `serve` command, then modify the partial to `false` after the service is available, the template continues to compile and works as expected.

**Comment by jmooring** [comment]
The `where` condition isn't the problem. This example uses your code (see layouts/_default/home.html) and your data:

```text
git clone --single-branch -b hugo-github-issue-13207 https://github.com/jmooring/hugo-testing hugo-github-issue-13207
cd hugo-github-issue-13207
hugo server
```

Works great. You have a different problem.

Please create a new topic on the [forum](https://discourse.gohugo.io/) where we handle questions and troubleshooting. Thanks.

**Comment by skoblenick** [comment]
Thanks for the example repo, it helped me identify the issue. It was being caused by a malformed structure in my `fr` data file; the english file was in the correctly structure.
