### ISSUE TITLE
{{ .Summary }} includes unwanted text in certain circumstances

### ISSUE THREAD

**Issue by madranet** [gohugoio/hugo#1503]
When using `{{ .Summary }}` within a template, traditional markdown image tags [and their associated `title` and `alt` attributes] are ignored when the summary is created. So in a post beginning with:

```
![Beam me up Scotty!](/images/kirk.jpg "The Captain")

Lorem ipsum dolor sit amet, consectetur adipiscing elit...[etc]
```

The summary is correctly rendered as:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit...[etc]
```

However, if the `{{% figure %}}` shortcode is used to add images:

```
{{% figure src="/images/kirk.jpg" alt="Beam me up Scotty!" title="The Captain" %}}

Lorem ipsum dolor sit amet, consectetur adipiscing elit...[etc]

```

Then the `title` attribute is also included in the generated summary:

```
The Captain Lorem ipsum dolor sit amet, consectetur adipiscing elit...[etc]
```

This is also the case when `caption` is used:

```
{{% figure src="/images/kirk.jpg" alt="Beam me up Scotty!" caption="The Captain" %}}

Lorem ipsum dolor sit amet, consectetur adipiscing elit...[etc]

```

also produces:

```
The Captain Lorem ipsum dolor sit amet, consectetur adipiscing elit...[etc]
```

Interestingly, when both `title` and  `caption` are used, only the content of the `caption` attribute is included in the generated summary.

Also, if a post begins with a list, this is included in the generated summary as well:

```
* Blah Blah
* Waffle Waffle
* Drone Drone

Lorem ipsum dolor sit amet, consectetur adipiscing elit...[etc]
```

Generates the following summary:

```
Blah Blah Waffle Waffle Drone Drone Lorem ipsum dolor sit amet, consectetur adipiscing elit.
```

The same happens when a post begins with `## mardown headers ##`. The content of these is also included in the generated summary.

All of the above make summaries generated by  `{{ .Summary }}` quite messy, when posts do not start with a paragraph of text.

**SUGGESTION:** `{{ .Summary }}` should begin summarising from the first encountered `<p>` tag and should strip out any content between non text-markup tags.

**Comment by mattwoolnough** [comment]
+1. Code blocks turn out quite poorly also.  Not formatted in any way.   Strip the code blocks out as suggested, or just stop the summary at the start of the code.

**Comment by variab1e** [comment]
+1 Agreed- this seems the perfect solutions -- @mattwoolnough  "Strip the code blocks out as suggested, or just stop the summary at the start of the code."

**Comment by qw3ry** [comment]
I have a similar issue: My page is starting with a header:
`# some title`
and this header is included in `.Summary`, but only if I use the `<!--more-->` somewhere in the text.

This problem makes the "`<!--more-->`-feature" quite useless for me as the resulting web page looks awful.

**Comment by madranet** [comment]
Disappointed to see this still hasn't been addressed as of version 0,18

```
$ hugo version
Hugo Static Site Generator v0.18.1 BuildDate: 2016-12-29T17:12:41Z
```

![2017-01-03_14-05-19](https://cloud.githubusercontent.com/assets/669658/21610060/d73dd1ec-d1bd-11e6-8b1e-5449cfaeebd4.png)

**Comment by jhabdas** [comment]
I for one appreciate the simplicity of the [automatic summary split](https://gohugo.io/content/summaries#hugo-defined-automatic-summary-split). It's built-in constraints have moved me to improve my layouts by moving items from the content better expressed in front matter.

**Comment by kleinschmidt** [comment]
This is still an issue: including a fenced code block in the summary is, IMHO, lunacy.

**Comment by pointfourone** [comment]
Is this issue not a point of concern anymore? It's been more than 4 years since this issue was opened. The summary looks messed up no matter which theme I use if I start my blog post with a title or other elements other than `<p>`.

**Comment by jtooker** [comment]
I agree with @pointfourone.  The "automatic" summary works well at removing images and tables, but it leaves headers in.  If it ignored headers too (or if there was a site configuration variable to omit them), I think it would work quite well for me.  Without it, I'm forced to copy the first paragraph or so into my front matter.

**Comment by madranet** [comment]
> I agree with @pointfourone. The "automatic" summary works well at removing images

Summary doesn't remove images in all circumstances. See my original issue posting at the top of the thread.

**Comment by khayyamsaleem** [comment]
Could there be a solution where you could use something like a "summary-ignore" shortcode to mark off content that you want to exclude from a summary?

**Comment by khayyamsaleem** [comment]
envisioning something like:

```
{{% summary-ignore %}}
{{% figure src="/images/kirk.jpg" alt="Beam me up Scotty!" caption="The Captain" %}}
{{% /summary-ignore %}}

Lorem ipsum dolor sit amet, consectetur adipiscing elit...[etc]
```

**Comment by musm** [comment]
Encountering the same problem here

**Comment by AngelCrawford** [comment]
Same Problem. Hoped I could do a workaround with the "replaceRE" Function and Regex, but it didn't worked >.<

**Comment by AngelCrawford** [comment]
As a workaround, I now create my own Summary-Split with a comment. 

```html
{{ $summarySplits := split .Content "<!--start-summary-->" }}
{{ if ge (len $summarySplits) 2 }}
    <!-- If content has the comment "start-summary", start there -->
    {{ index $summarySplits 1 | plainify | truncate 270 }}
{{ else }}
    {{ .Summary| markdownify | truncate 270 " [...]" }}
{{ end }}
```

In my index.md, where the content is at, I add the comment  at my first `<p>`-Tag.

**Comment by willfaught** [comment]
I'm seeing shortcode syntax appearing in .Summary:

```
Basic Code: {{< paige/vimeo "644036051" >}} Result: Video parameter Code: {{< paige/vimeo video="644036051" >}} Result: All parameters Code:
```

**Comment by frankenstein91** [comment]
> envisioning something like:
> 
> ```
> {{% summary-ignore %}}
> {{% figure src="/images/kirk.jpg" alt="Beam me up Scotty!" caption="The Captain" %}}
> {{% /summary-ignore %}}
> 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit...[etc]
> ```

would love it

**Comment by jmooring** [comment]
As of [v0.134.0](https://github.com/gohugoio/hugo/releases/tag/v0.134.0) this is no longer relevant. 

See:
- <https://gohugo.io/content-management/summaries/#comparison>
- <https://gohugo.io/getting-started/configuration/#summarylength>

As a general note, the "automatic" summary does not magically summarize content. Instead, it renders the first N paragraphs depending on the `summaryLength` value in your site configuration.

If your content begins with something other than text, it probably makes more sense to use one of the other summary methods:

- [manual](https://gohugo.io/content-management/summaries/#automatic-summary)
- [front matter](https://gohugo.io/content-management/summaries/#front-matter-summary)
- [strings.Truncate](https://gohugo.io/content-management/summaries/#alternative)


Also note that v0.134.0 and later include a [ContentWithoutSummary](https://gohugo.io/methods/page/contentwithoutsummary/) matho on `Page`.
