### ISSUE TITLE
Github flavored Markdown

### ISSUE THREAD

**Issue by ibes** [gohugoio/hugo#158]
Hi,

I started using Hugo and again have the problem with Markdown, that I think it is really intuitive that a line break in Markdown should be a <br> in the HTML. 

Github has changed this and created GitHub flavored Markdown for this. 

May there be an option to also(?) have the option to render my content as GH flavored Markdown? This would help me make my writing experience quite intuitive. 

I am newer than new to go (not yet really started learning it) so I can't help implementing it. 

Would be nice, to have a config option to just change the markdown render method.

**Comment by invkrh** [comment]
You can switch renders to `github flavored markdown` in blackfriday
https://github.com/russross/blackfriday#other-renderers

But I need an option in Hugo to toggle it. Is it possible ?

**Comment by bep** [comment]
@invkrh take questions at http://discuss.gohugo.io/
