### ISSUE TITLE
baseurl ignored silently

### ISSUE THREAD

**Issue by xaprb** [gohugoio/hugo#170]
My config.yaml:

``` text
--- 
baseurl: "http://www.xaprb.com/"
title: "Xaprb"
params:
    author: "Baron Schwartz"
    subtitle: "Stay Curious!"
    disqus_shortname: "xaprb"
    ga_account: "0xdeadbeef"
    twitter: "@xaprb"
    domain: "xaprb.com"
indexes:
    category: "categories"
...
```

It apparently works fine -- values such as the title, author, subtitle, etc are rendered into templates. But strangely, all URLs are `localhost:1313` -ified. On a hunch, I checked the config.yaml for the hugo docs, and changed my yaml file to:

``` text
title: "Xaprb"
params:
    author: "Baron Schwartz"
    subtitle: "Stay Curious!"
    disqus_shortname: "xaprb"
    ga_account: "0xdeadbeef"
    twitter: "@xaprb"
    domain: "xaprb.com"
indexes:
    category: "categories"
baseurl: 'http://www.xaprb.com/'

---
```

Now it works -- my site's URLs are xaprb.com -ified.

Perhaps an off-topic note, but I do not think that supporting 3 different types of config is actually a merit. I'd support YAML, JSON, or TOML -- but not all three; one is enough. Supporting three is just going to be a source of bugs. Perhaps this bug is an example?

**Comment by zqhong** [comment]
I use this command and fix it.
$ hugo server --theme=greyshade --buildDrafts --bind="0.0.0.0" -v --baseUrl="http://www.example.com/"

**Comment by evrial** [comment]
> Hugo has the behavior that if you call it with server, regardless of the baseurl in the config file it will render all links with localhost:1313.
Thats pretty much a bug, so in case when I'm using nginx reverse proxy and running hugo server from localhost I need to specify `--baseUrl=http://example.com --appendPort=false` istead of just use those params from config file.

**Comment by mikumaycry** [comment]
hugo server --buildDrafts（ignore baseurl in config，use localhost instead ）
hugo --buildDrafts （use baseurl in config）
