### ISSUE TITLE
RSSLink values don't respect (non)uglyUrls

### ISSUE THREAD

**Issue by spf13** [gohugoio/hugo#175]

**Comment by glacjay** [comment]
When I set `uglyUrls` to `true`, `{{ .RSSlink }}` gives me `http://localhost:1313/.xml` instead of `http://localhost:1313/index.xml`. Is that caused by this bug?

**Comment by glacjay** [comment]
@spf13 I think RSS links should not be uglified even when the user specify `uglyUrls = true`, is that correct?

**Comment by spf13** [comment]
correct

--
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by glacjay** [comment]
@spf13 So I think I encounter a bug, when I set `uglyUrls = true`, hugo gives me an incorrect RSS link `http://localhost:1313/.xml`.
