### ISSUE TITLE
.Inner in paired shortcodes should be (markdown) rendered

### ISSUE THREAD

**Issue by RubenN** [gohugoio/hugo#185]
page.html (shortcode)

```
<div>
{{ if isset .Params 0 }}<h3>{{ index .Params 0 }}</h3>{{ end }}
    {{ .Inner }}
</div>
```

test.md: (markdown)

```
{{% page "Step 1" %}}
Select **tasklist** and press 'New filter'

![](createFilter.png)
{{% /page %}}
```

test.html (result)

```
<div>
<h3>Step 1</h3>
Select **tasklist** and press 'New filter'

![](createFilter.png)
</div>
```

test.html (**expected** result)

```
<div>
<h3>Step 1</h3>
Select <b>tasklist</b> and press 'New filter'

<img src="createFilter.png">
</div>
```

**Comment by rca** [comment]
For anyone landing here, check out [this page in the docs](https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown), which states a shortcode called with the following syntax (note `%` instead of `<` and `>`) tells the engine to render `{{ .Inner }}` as markdown:

```
{{% foo %}}
# this is
markdown
{{% /foo %}}
```
