### ISSUE TITLE
helpers: Mmark support incomplete, e.g. missing EXTENSION_ABBREVIATION

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugo#1970]
As @mikhail73 reported in miekg/mmark#60 and https://discuss.gohugo.io/t/the-abbreviations-mmark-does-not-work-in-the-hugo/2867, the current experimental mmark support in Hugo is incomplete.  For example, `EXTENSION_ABBREVIATION` is not enabled, and whether mmark extensions can be customized is a question to me too.  Would be nice to get mmark support on par with Blackfriday support in Hugo.

**Comment by erichgoldman** [comment]
Is there any progress or hacks to get markdown abbreviation support in Hugo? Either in blackfriday or an alternate?

**Comment by bep** [comment]
@erichgoldman use http://discuss.gohugo.io/ for questions

**Comment by anthonyfok** [comment]
Sorry to everybody for my continued tardiness in getting this implemented.  (No, it is not ready yet, and I am not sure when I will have time to work on it again.)

Note to self: Revisit and update PR #2118 when I have time to look at it again.

**Comment by z3to** [comment]
Are there any updates on this? Or is there any way I can add that just for my website?

**Comment by bep** [comment]
Mmark is deprecated so this will not be fixed.
