### ISSUE TITLE
[s390x] TestReplaceShortcodeTokens panics with "slice bounds out of range" error 

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugo#2206]
When the Debian s390x build daemon tries to build hugo_0.16-1, during the `go test` run,  TestReplaceShortcodeTokens panics with "slice bounds out of range error:

```
=== RUN   TestReplaceShortcodeTokens
--- FAIL: TestReplaceShortcodeTokens (0.00s)
panic: runtime error: slice bounds out of range [recovered]
    panic: runtime error: slice bounds out of range

goroutine 1677 [running]:
runtime_dopanic
    ../../../src/libgo/runtime/panic.c:131
__go_panic
    ../../../src/libgo/runtime/go-panic.c:111
testing.$nested5
    ../../../src/libgo/go/testing/testing.go:456
__go_panic
    ../../../src/libgo/runtime/go-panic.c:67
runtime_panicstring
    ../../../src/libgo/runtime/panic.c:216
__go_runtime_error
    ../../../src/libgo/runtime/go-runtime-error.c:70
hugolib.replaceShortcodeTokens
    /«PKGBUILDDIR»/obj-s390x-linux-gnu/src/github.com/spf13/hugo/hugolib/shortcode.go:531
github_com_spf13_hugo_hugolib.TestReplaceShortcodeTokens
    /«PKGBUILDDIR»/obj-s390x-linux-gnu/src/github.com/spf13/hugo/hugolib/shortcode_test.go:603
testing.tRunner
    ../../../src/libgo/go/testing/testing.go:472
kickoff
    ../../../src/libgo/runtime/proc.c:235
created by testing.RunTests
    ../../../src/libgo/go/testing/testing.go:581

goroutine 16 [chan receive]:
runtime_mcall
    ../../../src/libgo/runtime/proc.c:295
chanrecv
    ../../../src/libgo/runtime/chan.goc:269
testing.RunTests
    ../../../src/libgo/go/testing/testing.go:582
testing.Run.pN9_testing.M
    ../../../src/libgo/go/testing/testing.go:514
main.main
    /tmp/go-build616005466/github.com/spf13/hugo/hugolib/_test/_testmain.go:392
runtime_main
    ../../../src/libgo/runtime/proc.c:626

goroutine 17 [syscall]:
    goroutine in C code; stack unavailable
created by runtime_main
    ../../../src/libgo/runtime/proc.c:598

goroutine 18 [finalizer wait]:
runtime_mcall
    ../../../src/libgo/runtime/proc.c:295
runfinq
    ../../../src/libgo/runtime/mgc0.c:2512
kickoff
    ../../../src/libgo/runtime/proc.c:235
created by runtime_createfing
    ../../../src/libgo/runtime/mgc0.c:2577

goroutine 21 [GC sweep wait]:
runtime_mcall
    ../../../src/libgo/runtime/proc.c:295
bgsweep
    ../../../src/libgo/runtime/mgc0.c:1844
kickoff
    ../../../src/libgo/runtime/proc.c:235
created by mgc
    ../../../src/libgo/runtime/mgc0.c:2215

goroutine 1431 [chan send]:
runtime_mcall
    ../../../src/libgo/runtime/proc.c:295
chansend
    ../../../src/libgo/runtime/chan.goc:145
github_com_spf13_hugo_hugolib.emit.pN39_github_com_spf13_hugo_hugolib.pagelexer
    /«PKGBUILDDIR»/obj-s390x-linux-gnu/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:241
hugolib.lexShortcodeRightDelim
    /«PKGBUILDDIR»/obj-s390x-linux-gnu/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:349
github_com_spf13_hugo_hugolib.runShortcodeLexer.pN39_github_com_spf13_hugo_hugolib.pagelexer
    /«PKGBUILDDIR»/obj-s390x-linux-gnu/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:196
kickoff
    ../../../src/libgo/runtime/proc.c:235
created by hugolib.newShortcodeLexer
    /«PKGBUILDDIR»/obj-s390x-linux-gnu/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:188

goroutine 749 [chan send]:
runtime_mcall
    ../../../src/libgo/runtime/proc.c:295
chansend
    ../../../src/libgo/runtime/chan.goc:145
github_com_spf13_hugo_hugolib.errorf.pN39_github_com_spf13_hugo_hugolib.pagelexer
    /«PKGBUILDDIR»/obj-s390x-linux-gnu/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:274
hugolib.lexInsideShortcode
    /«PKGBUILDDIR»/obj-s390x-linux-gnu/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:527
github_com_spf13_hugo_hugolib.runShortcodeLexer.pN39_github_com_spf13_hugo_hugolib.pagelexer
    /«PKGBUILDDIR»/obj-s390x-linux-gnu/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:196
kickoff
    ../../../src/libgo/runtime/proc.c:235
created by hugolib.newShortcodeLexer
    /«PKGBUILDDIR»/obj-s390x-linux-gnu/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:188
FAIL    github.com/spf13/hugo/hugolib   1.836s
```

See the full build log at https://buildd.debian.org/status/fetch.php?pkg=hugo&arch=s390x&ver=0.16-1&stamp=1465794774

**Comment by bep** [comment]
Hard for us to debug this. It would be helpful if you could either post a issue at Go's repo or create a thread at go-dev so the IBM people could have a look at it. This codepath have been running undisturbed without errors on many platforms for years now, so it smells like a s390x issue.

**Comment by anthonyfok** [comment]
Yes, @ bep, you are right indeed: this issue (and another that I am going to file for mips and powerpc architectures) are most likely upstream issues that need to be reported upstreams.

I am just writing these problems down as I see them (from https://buildd.debian.org/status/package.php?p=hugo&suite=sid), and grouping them under "area/cpu-architectures", so I don't forget them.

> ... you could either **post a issue at Go's repo** or **create a thread at go-dev** so the IBM people could have a look at it.

I was wondering where to report this myself, and my brain was blank.  Thanks for the great pointer!  Will do so (hopefully soon).

**Comment by bep** [comment]
Are these issues reported upstream?

**Comment by digitalcraftsman** [comment]
@anthonyfok currently, you're updating the packages for v0.20.*. Unless this issue is still present I would propose to close this issue.

**Comment by anthonyfok** [comment]
Sorry for my tardiness in following up this issue.

The build log of the last attempted build by Debian buildd for hugo 0.18.1-1:

* https://buildd.debian.org/status/fetch.php?pkg=hugo&arch=s390x&ver=0.18.1-1&stamp=1492365110&raw=0

where `go test -v ./...` failed.  The same test errors could be reproduced by the latest gccgo-6 package, i.e.:

    go version go1.6.1 gccgo (Debian 6.3.0-19) 6.3.0 20170618 linux/s390x

The situation improved greatly with the new gccgo-7 package where hugo 0.18.1-1 builds successfully with all `go test -v ./...` tests passed:

    go version go1.8.1 gccgo (Debian 7.1.0-7) 7.1.0 linux/s390x

However, trying to use this latest gccgo-7 to build the latest hugo HEAD (v0.25-DEV) fails with this new (?) test:

```
=== RUN   TestMethodToName
--- FAIL: TestMethodToName (0.00s)
        Error Trace:    templatefuncRegistry_test.go:32
	Error:      	Not equal: 
	            	expected: "MyTestMethod"
	            	actual: "$thunk0"
FAIL
```

But it is a little bit moot now, as there is now actually a new Go native build for s390x, from the golang-1.8-go package in Debian:

    go version go1.8.1 linux/s390x

with which hugo (HEAD) also builds successfully.

So, yes, we can now close this issue.
