### ISSUE TITLE
[alpha mips{,el,64el} powerpc] Compile error at golang.org/x/sys/unix

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugo#2207]
The Debian build daemon fails to build hugo_0.16-1 on alpha, mips, mipsel, mips64el and powerpc architectures (using gccgo) due to the following error when compiling golang.org/x/sys/unix:

```
dh_auto_build -O--buildsystem=golang
    go install -v github.com/spf13/hugo github.com/spf13/hugo/bufferpool github.com/spf13/hugo/commands github.com/spf13/hugo/create github.com/spf13/hugo/helpers github.com/spf13/hugo/hugofs github.com/spf13/hugo/hugolib github.com/spf13/hugo/livereload github.com/spf13/hugo/parser github.com/spf13/hugo/source github.com/spf13/hugo/target github.com/spf13/hugo/tpl github.com/spf13/hugo/transform github.com/spf13/hugo/utils github.com/spf13/hugo/watcher
golang.org/x/sys/unix
github.com/kardianos/osext
github.com/kr/fs
github.com/pkg/errors
# golang.org/x/sys/unix
src/golang.org/x/sys/unix/flock.go:15:30: error: reference to undefined name 'SYS_FCNTL'
 var fcntl64Syscall uintptr = SYS_FCNTL
                              ^
src/golang.org/x/sys/unix/sockcmsg_linux.go:15:30: error: reference to undefined name 'SizeofUcred'
  b := make([]byte, CmsgSpace(SizeofUcred))
                              ^
src/golang.org/x/sys/unix/sockcmsg_linux.go:16:9: error: reference to undefined name 'Cmsghdr'
  h := (*Cmsghdr)(unsafe.Pointer(&b[0]))
         ^
```

and many more lines after that, see https://buildd.debian.org/status/package.php?p=hugo&suite=sid for the overall view.

Individual build logs:
- https://buildd.debian.org/status/fetch.php?pkg=hugo&arch=alpha&ver=0.16-1&stamp=1465835430
- https://buildd.debian.org/status/fetch.php?pkg=hugo&arch=mips&ver=0.16-1&stamp=1465794978
- https://buildd.debian.org/status/fetch.php?pkg=hugo&arch=mipsel&ver=0.16-1&stamp=1465794863
- https://buildd.debian.org/status/fetch.php?pkg=hugo&arch=mips64el&ver=0.16-1&stamp=1465794891
- https://buildd.debian.org/status/fetch.php?pkg=hugo&arch=powerpc&ver=0.16-1&stamp=1465794682

Note that `gccgo` are used on these platforms, though s390x and gccgo builds hugo just fine (except a failed test in #2206), I would still say the culprit is probably at golang.org/x/sys/unix.

It might also have to do with Debian still using go1.6.1 without some related backported fixes that went into go1.6.2.  (Wait, no, that is golang-go, not gccgo...)

TODO: Reproduce on Debian test "porterbox" servers, come up with an MWE (minimal working example) if necessary, and report back upstream.

**Comment by digitalcraftsman** [comment]
It's will be unlikely that we'll fix this issue for Hugo v0.16. Hence I propose to close this issue.

**Comment by anthonyfok** [comment]
Just a final status update at the closing of this issue (Thanks @ bep):

According to https://buildd.debian.org/status/package.php?p=hugo, as of Hugo 0.25.1, MIPS architecture (mips, mipsel, mips64el) now builds successfully (Hurray!), so only alpha and powerpc remains.

And now that I understand the problem a little better: This issue has ~little~ nothing to do with Hugo itself, but rather with golang.org/x/sys adding support (e.g. Linux kernel headers, etc.) for alpha and powerpc, both which are somewhat obsolete anyway, so not a big deal.

**Comment by anthonyfok** [comment]
Please see follow up at https://github.com/golang/go/issues/18031.

PowerPC ((linux/ppc) architecture support is being reviewed at https://go-review.googlesource.com/c/sys/+/262517
