### ISSUE TITLE
Any cross-platform binary syntax highlighters to integrate with Hugo?

### ISSUE THREAD

**Issue by tajmone** [gohugoio/hugo#2222]
Hugo is great, and I'm loving it. What motivated me to switch to Hugo was the "single binary file" philosophy. I had worked with Jekyll and other flat CMSs', but having multiple projects — older ones relying on older versions of the CMS — was becoming a pain. With Hugo you can get away with such issues by keeping separate Hugo binaries in the projects, as easy as that.

But when it comes to syntax highilighting, Pygments reintroduced the burden of maintaining Python + a whole package — which somehow clashes with the one-binary benefit. Of course, JS highlighters provide an easy way out; but still...

I've been looking around for some binary (and cross platform) syntax highlighters, operating similarly to Pygments; but it doesn't look like there is a lot of choice out there...

I've come across Andre Simon's "Highlight", an interesting application which could qualify as a substitute for Pygments:

http://www.andre-simon.de/doku/highlight/en/highlight.php

it's open source, cross platform, fully customizable, works as a CLI tool and also comes with a GUI, and can be used in standalone mode (at least on Windows) or installed. Not a single binary though, it has some dependencies, but surely an easy alternative to having to install Python and Pygments.

I've started experimenting with it, and I'll try to create a shortcode to redirect code to it, and see what I get. So far I've got good testing results, but only by producing full HTML docs from the source — haven't got around to passing and retriving snippets.

Does anyone know of other similar tools?

It would be great to have Hugo handle all the syntax highlighting with either a single binary, or a standalone app — and even greater, if it might handle it by itself in the near future. Surely, not all of Hugo's users might be looking for source code highlighting — many might be creating site not related to computing at all —; but I guess many would be happy with it.

Anyone has any thoughs and suggestions on the issue? or knows about any Go lang projects relating to syntax highlighting?

**Comment by bep** [comment]
>Anyone has any thoughs and suggestions on the issue? or knows about any Go lang projects relating to syntax highlighting?

No, but it is just a matter of time before a quality Go highlighter pops up. It should be easier to implement in Go than many lingos.

**Comment by tajmone** [comment]
Yes, that would be great 'cos it would integrate into Hugo natively. So fare I haven't found any Go lang libs in developement, but I agree that its only a matter of time.

In the meantime I've come to the conclusion that Andre's Highlight is up to task — it handles well snippets in and out of stdstreams, and can output standalon HTML highlighted code (no HTML/body headers). Also, the CLI exe (on Windows) only needs 3 DLLs to go with it, plush the language definitions. It's easier to use than Pygments, especially for langs definitions (RegExs are not mandatory for simple langs).

**Comment by jnboehm** [comment]
what about [Source-highlight](https://www.gnu.org/software/src-highlite/)?  It's written in C++, maybe it could be incorporated through bindings to C++?  Although the last commit dates back almost two years now, so that maybe disqualifies it.  It also relies on the boost regex library, but according to [this](http://petereisentraut.blogspot.de/2009/07/adding-color-to-console-pygments-vs.html), it is quite a bit faster than pygments.

**Comment by bep** [comment]
@jnboehm I'm not sure if the Clang bindings for Go would support this ... But even if it did, we would get an "impossible" build setup -- and would probably have to drop many of the release targets. IMO. not worth it.

**Comment by jnboehm** [comment]
Hmm alright, thanks for your consideration.

**Comment by tajmone** [comment]
@jnboehm , thanks for pointing out Source-highlight, I wasn't aware of it. There currently are no prebuilt binaries for Windows, except for a very outdated version on GnuWin32 packages site, so I couldn't test it, but it seems an interesting.

Andre Simon's "Highlight" can also be used as a dynamic library, which should be simpler to wrap. The sources also provide makefiles for building it as a static library (also for Windows) — so it could be integrated into Hugo's binary by statically linking it. Of course, all this might add some complexity to the building chain of Hugo.

But I admit not having tested this approach, just peeked at it docs.

**Comment by moorereason** [comment]
We solved this issue in Hugo v0.28 with [Chroma](https://github.com/alecthomas/chroma).
