### ISSUE TITLE
Date.Format Internationalization

### ISSUE THREAD

**Issue by tubia** [gohugoio/hugo#245]
Hi,
Maybe I don't understand well the logic of the .Date.Format variable, but it's possible to change the language of the months (for example) when they are displayed?
Something like {{ .Date.Format.IT "30 marzo 2006" }}

**Comment by variadico** [comment]
Hi, there.

I wrote a general-purpose package, called [lctime], that might be able to fix this issue. It uses locales and `strftime` to format dates internationally. In addition, I use `go-bindata` to bundle locale data, which means devs don't have to distribute anything extra with their app.

I was thinking this issue could be easily solved if we could add `lctime.Strftime` as a template function. Then people could use this in their templates.

```
<p>{{strftime "%c" .Date}}</p>
```

The default locale is based on [environment variables]. However, if people want to change the locale, they can start Hugo like this.

```
LC_TIME=es_MX hugo server
```

Or maybe they could add a `locale` field in their `config.yaml` and Hugo could call `lctime.SetLocale` to explicitly set the locale.

Let me know if this is something that sounds interesting. I wouldn't mind opening a PR. Happy holidays! :christmas_tree: 

[lctime]: https://github.com/variadico/lctime
[environment variables]: https://godoc.org/github.com/variadico/lctime
