### ISSUE TITLE
HTML comments stripped?

### ISSUE THREAD

**Issue by jchatard** [gohugoio/hugo#263]
Are HTML comments stripped by Hugo during rendering?

It's not that I mind so much to remove comments, but for conditional comments, this can be annoying... Don't know if it's a bug, or a feature.

``` html
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
```

Becomes:

``` html

```

:-)

Thanks,
Jérémy

**Comment by jononomo** [comment]
What can I do if I don't want comments stripped out?

**Comment by dimo414** [comment]
Has this changed? I'm now seeing comments in my HTML output.

**Comment by spf13** [comment]
@dimo414 I'm not aware of any changes made to the Go template library. What version of Hugo are you using? What Go is it built with?

**Comment by dimo414** [comment]
I'm using Hugo 0.15, via the `hugo_0.15_windows_amd64.zip` Windows binary. Demo:

```
$ hugo version
Hugo Static Site Generator v0.15 BuildDate: 2015-11-25T14:35:20-05:00

$ cat content/post/demo.md
+++
date = "2014-08-10"
title = "demo"

+++

This is text

<!-- this is a comment -->

$ hugo --theme hyde
0 draft content
0 future content
1 pages created
1 paginator pages created
0 categories created
0 tags created
in 13 ms

$ cat public/post/demo/index.html | grep comment
<!-- this is a comment -->
```

**Comment by egorsmkv** [comment]
@boushley 

I use this code:
```
{{ "<!--[if IEMobile 7 ]><html class="no-js iem7"><![endif]-->" | safeHtml }}
```

After render:

```
ERROR: 2016/02/25 html/template: "partials/header.html" is an incomplete template in partials/header.html
```

**Comment by mbertschler** [comment]
Okay so I just discovered that the current state of things is that comments are stripped from template files, but not stripped from content files.

**Comment by dimo414** [comment]
@spf13 is this desired functionality? Could comments be stripped from content files as well?

**Comment by mbertschler** [comment]
@dimo414 as far as I can se Hugo uses the [blackfriday](https://godoc.org/github.com/russross/blackfriday) for markdown rendering. From looking at its documentation it does not provide an option to strip comments, as it probably just treats them like inline HTML.

**Comment by ernsheong** [comment]
A note for onlookers, `safeHtml` has been renamed to `safeHTML` in Hugo 0.14.

**Comment by behindthepage** [comment]
@ernsheong  thanks for your last comment. It saved me time and stress. Really appreciated it.
