### ISSUE TITLE
Theme inheritance

### ISSUE THREAD

**Issue by lebarde** [gohugoio/hugo#2639]
I would appreciate so much that Hugo had theme inheritance abilities. This is what we can do on eg. **[wordpress](https://codex.wordpress.org/Child_Themes)** and this functionality is extraordinary: this way, you can make your own theme based on an existing one, while still getting updates from the base theme. If you don't do so and want to get the updates, you have to merge some git branches (for instance), and that contributes to keep non-developers away from using hugo.

What I suggest is like Wordpress: in the child theme, setting which is the base theme (that can be done inside the theme's config file like `parent = "hugo-material-docs"`), and always preferring a new file when available.

Note: to my mind this functionality does not seem to exist inside any other static site generator for now, but I assume this is a must-have in a widely used static site generator!

What do you think of it?

**Comment by bep** [comment]
>this is a must-have

That is taking it too far, me thinks. There are lots of theme related stuff that comes further up the latter than this one (standards, widgets ...). I think composition may be better than inheritance when it comes to themes.

**Comment by lebarde** [comment]
> There are lots of theme related stuff that comes further up the latter than this one (standards, widgets ...). 

Do you mean functionalities that are more important to develop first?

**Comment by bep** [comment]
>Do you mean functionalities that are more important to develop first?

Yes, I meant to write "ladder".

**Comment by lebarde** [comment]
Okay! I think this is not too difficult a task to develop. For now I'm on the widget development (#2535).

**Comment by MarkDBlackwell** [comment]
On the Hugo discussion site, [this thread](https://discuss.gohugo.io/t/sub-themes-or-theme-families/3938) is similar, to wit:

> What new behavior would we (hypothetically) obtain? Perhaps sub-themes, or theme families.

> So fileOne would be inherited from [parent theme] themeOne, and fileTwo would be inherited from [child theme] themeTwo.

**Comment by bep** [comment]
What Hugo should have is: 

* A way to say that a theme extends another theme, i.e. in some theme config `extends: someother-theme`

It does not need to be hard, but we should probably first address the somewhat clumsy theme addressing scheme.

**Comment by lebarde** [comment]
See also this discussion here:

https://discuss.gohugo.io/t/theme-standards-and-general-experience/6438

**Comment by lebarde** [comment]
@bep, for the naming convention of a config file: Actually a lot of theme designers already use `config` to put a sample *main* config file inside the theme tree, so using this name would break all those themes.

What would you tell about a `theme.toml` (or `theme.yaml`, and so on) for a theme configuration filename? IMO that would be clear enough.

**Comment by rdwatters** [comment]
`theme.toml` is already part of themes; e.g.: 

https://github.com/sethmacleod/aerial/blob/master/theme.toml

**Comment by lebarde** [comment]
Snif… What would be suited best?

If that filename is less used than `config.toml`, maybe we could contact the theme creators who use that name. What would you propose?

**Comment by bep** [comment]
@lebarde please don't start discussions on tiny implementation details when the full picture is so unclear. That is just a waste of everyone's time. I have said it before, but I can say it again: Before we even start to think about theme inheritance, we need to handle external resources in a much better way than it is today. And that is a task much bigger than a simple config file.

**Comment by lebarde** [comment]
@bep Thanks for clearing the situation!

You are right about the fact that the picture is unclear. When I dived into the code I effectively saw that I would have to hook every access to a file to look for a parent. That would be made things most complicated.

> It does not need to be hard

And I may have misinterpreted your statement. Anyway, I did not know (or remember) that you said that. As you said it did not need to be hard, I started to try. I recognize that external resources have to be handled another way before starting that, so I will not go further on that case!

**Comment by bep** [comment]
>When I dived into the code I effectively saw that I would have to hook every access to a file to look for a parent. That would be made things most complicated.

The inheritance part of this is easier than you think, but again, this must come after some other thing.
