### ISSUE TITLE
Problem with YAML configuration and .Site.Params

### ISSUE THREAD

**Issue by CptTina** [gohugoio/hugo#269]
I've been having trouble with using .Site.Params in the header and footer. They worked back when I put them into my test site, then they didn't work all the time anymore. So I built the latest commit now and tried to reproduce the problem in the default docs there.

I realized the default configuration file is now a TOML, while doing that, so I put a .Site.Param in there.

```
[params]
  TitleTestParam = "TitleTestParamContent"
```

I also used this in the footer.

```
#{{ .Site.Params.TitleTestParam }}#
```

It worked, in normal pages and in the indexes when I built it. Then I converted that config to YAML and JSON respectively. It builts for each of the three, but my footer only seems to work with the TOML and JSON configurations.

Am I doing something wrong?

**ADDED:**
I just figured out, that while the section and index indexes seem to display the footer just fine with TOML and JSON config, the meta indexes don't seem to work with either type of config.

**Comment by CelticParser** [comment]
V0.16: 

I am seeing intermittent read issues when using .yml. I had been using yml for a few days then suddenly most settings  were not being read (e.g. esp. Hugo directory settings). It was driving me loco for hours. I switched to toml and everything started working again. I switch back to the yml and it breaks. Next I switch to a 'yaml' version and it works again. Back to 'yml' file and keeps working for awhile. Then, mysteriously out-of-the-blue, breaks again. I use 'make' to run the Hugo commands and I scrub the public and cache directories at each build during development so there is no write collisions. I have run thru the sequences above with random results other than that the toml files always works. We have our own CMS using React and can only work with 'yaml'/'yml'. FYI, the CMS is out of the loop while testing this issue.
