### ISSUE TITLE
Add Ability to Chain Config Files Together

### ISSUE THREAD

**Issue by felicianotech** [gohugoio/hugo#2735]
It is very useful to have a base or main config file and then separate config files that you chain together. An example of this would be environment specific config files for deployment. This is how it is done in a Jekyll project I work with:

```
jekyll build --config _config.yml,_config_production.yml
```

This would allow specific variables to be set only when building for production (and not local testing builds). It looks like [Viper](https://github.com/spf13/viper) itself only supports one config file at a time so we'd need to implement another instance?

I found a forum post with the same request: https://discuss.gohugo.io/t/can-you-chain-multiple-configs-together/1278

**Comment by bep** [comment]
> It looks like Viper itself only supports one config file at a time so we'd need to implement another instance?

We should update Viper to support multiple files. Viper is a @spf13 project, too, so we have commit access :-)

**Comment by bep** [comment]
Fixed in https://github.com/gohugoio/hugo/pull/3532
