### ISSUE TITLE
Feature request - Access page context from menu context

### ISSUE THREAD

**Issue by kamar535** [gohugoio/hugo#2784]
The only variables accessible when rendering a menu item are listed here https://gohugo.io/extras/menus/#what-is-a-menu. It would be great if there was a way to access the page context of the current menu item when rendering the menu. 

**Motivating example**

For example, if a page has the following front matter, 

    ---
    title: Title
    foo: my-foo
    ---

, from the `menu.html` template, is it possible to access the `foo` page variable when rendering the the menu item for the page.

I want to access the `foo` page variable both when rendering `header.html` and when rendering `menu.html` to decorate the page title and the menu item depending on the value of `foo`.

Initial discussion here https://discuss.gohugo.io/t/get-page-variables-from-menu-context/4812/2

**Comment by inlandsee** [comment]
+1.  For the sake of clarity it would be nice to add custom menu vars as desired then access them during render.  At present MenuEnttry ignores the custom style/icon' vars in the example below.  I can  fake it by passing them as pre and post but the code is hard to understand and any additional custom vars require additional monkey business.

+++    
#menuentry ignores style/icon, must pass as pre/post
[menu.user]
    parent="account"
    style="dialog"
    icon="fa-sign-in"      
+++

**Comment by martinburger** [comment]
I would prefer @inlandsee's solution.

Rationale: As far as I understand, "a menu item isn't connected to a page, so I don't think there is a easy way to get to a menu item's page's parameter". [[related Hugo Discussion](https://discuss.gohugo.io/t/can-i-access-archetype-values-when-rendering-a-menu/3626/4)]

Attaching custom attributes to menu entries would be great.
