### ISSUE TITLE
Deprecate preserveTaxonomyNames

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#2835]
It is complicated and should not be needed anymore. It adds maintenance that I would love to get rid of.

**Comment by moorereason** [comment]
Why is it not needed anymore?

**Comment by bep** [comment]
>Why is it not needed anymore?

You can set title in front matter.

It is still convenient -- but I'm not willing to maintain it.

**Comment by bep** [comment]
To put it in the context, I just spent 40 minutes on #2809 -- and I still have not fixed it (some other corner cases bumped to surface once I added some proper tests for it). It made sense when I added it, but it probably was a mistake.

**Comment by moorereason** [comment]
0.18 is a game changer for many things, and I'm trying to make sure I understand.  You mean we can now set the Taxonomy Term title via frontmatter, such as in `context/categories/acteur/gerard-depardieu/_index.md` (as needed in the original issue #1180):

```
+++
title = "Gérard Depardieu"
+++
```

/cc @nicolinuxfr

**Comment by bep** [comment]
>You mean we can now set the Taxonomy Term title via frontmatter

Yes. It will be some "work" if you have many such taxonomies, but I guess it would also be natural with a picture or some other metadata about Mr Depardieu.

But my main point about this issue is to make stuff simpler, so we can make changes without to much worrying about stuff blowing up in unexpected places.

**Comment by bep** [comment]
But your example is slightly wrong, it should be:

```
content/acteur/gerard-depardieu/_index.md
```

**Comment by bep** [comment]
It seems like this issue will be the "fix" for #2809 -- I don't see a simple solution to that. I have spent enough time already, so I think I'm just gonna bite the apple.

**Comment by bep** [comment]
>It seems like this issue will be the "fix" for #2809 -- I don't see a simple solution to that.

OK, I think I found a way.

**Comment by moorereason** [comment]
Good.  I think we're stuck with this feature until we go through a deprecation period.

**Comment by mikhail73** [comment]
I have 200kb size (4000+ strigs) /data/names.yaml for generate taxanomy terms like this http://pokrovsky.newgod.su/authors/%D0%BA%D0%BE%D1%87%D0%B5%D1%88%D0%BA%D0%BE%D0%B2/. 
You want to "deprecate" it?

**Comment by bep** [comment]
@mikhail73 not sure how your taxonomy mapping can have anything to do with `preserveTaxonomyNames`?

**Comment by mikhail73** [comment]
I have in FM authors: ['Кочешков'] and in /data/names.yaml

```
Кочешков:
  fullname: Кочешков Геннадий Николаевич
  shortname: Кочешков Г. Н.
  years:
  job: Ярославский государственный педагогический университет им. К. Д. Ушинского
  transname: kocheshkov
  info: — доктор исторических наук, профессор, заведующий кафедрой отечественной истории.
  url: 
  email:
```

**Comment by mikhail73** [comment]
I believe that the ability to generate content from yaml is the main technological advantage Hugo. The transition from the yaml to the file system is a technological degradation.

**Comment by bep** [comment]
OK, then I guess that will break with the change as described in this issue.

I'm open to alternatives, i.e. alternatives that is cleaner and easier to maintain than the current.

**Comment by mikhail73** [comment]
If this feature is disabled (preservetaxonomynames: false) I get all taxonomy terms in lowercase on [this list](http://andreeva.newgod.su/authors/). Without this feature, сan I save these terms as they are written in the FM?

**Comment by ITSecMedia** [comment]
https://discuss.gohugo.io/t/hugo-0-19-preservetaxonomynames-true-false/5640
