### ISSUE TITLE
Extract date and permalink from filename

### ISSUE THREAD

**Issue by xaprb** [gohugoio/hugo#285]
One of the Jekyll features I enjoy is extracting the date and slug/permalink from the filename so I don't need to specify them in the front matter. It would be nice if Hugo would support this as well.

**Comment by jon49** [comment]
Here's a workaround until the enhancement made for people on linux/macs, or if you're smart and figure out how to do it on windows.

```make
POST_SRC := $(subst ./,,$(shell find ./src/post/ -regextype posix-extended -regex '.*[0-9]{4}-[0-9]{2}-[0-9]{2}-.*\.md'))
POST_DEST := content/post/

default: all

define POSTS_PARSE
_target := $(POST_DEST)$(shell echo $1 | grep -Po '\w+\.md')
POSTS := $$(POSTS) $$(_target)
$$(_target): $1
	date=$$$$(basename $$< | grep -Po '\d{4}-\d{2}-\d{2}'); \
		sed "1 adate: $$$$date" $$< > $$@
endef

$(foreach x,$(POST_SRC),$(eval $(call POSTS_PARSE,$x)))

posts: $(POSTS)

init:
	mkdir -p content/post/

all: posts

.PHONY: all posts init
```

put your original files in `./src/post` and it will export to `./content/post`. Just type `make` for one time use and `watch make` when actively editing files.

**Comment by robsonsobral** [comment]
It's easier to keep the files organized too.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by borisschapira** [comment]
@bep 

* Easier to keep the files organized
* No need to charge the Front-Matter with the info (same goes for the language for example)

**Comment by borisschapira** [comment]
And I'll add: easier to migrate from Jekyll :)

**Comment by xaprb** [comment]
I agree, it's a feature request and valuable for the reasons Boris mentioned.

**Comment by robsonsobral** [comment]
Please, don't give up on this.

**Comment by vassudanagunta** [comment]
@bep, I recommend you add this to the next milestone, and perhaps also #3805, rather than one of the specific solution proposals. There are at least three of those (#3310, #3762, #3859) and I will be adding a fourth! 😄
