### ISSUE TITLE
parser: Unexport YAMLLead etc.

### ISSUE THREAD

**Issue by magikstm** [gohugoio/hugo#2884]
bep already added a todo mentioning it:
`// TODO(bep) Do we really have to export these?`

I'm really new to Go, so I'm unsure if this suggestion is good or not.

I see that only these consts (line 26 to 55) are used elsewhere than that package (all in convert.go):
YAMLLead
TOMLLead
JSONLead

I would suggest adding functions to get them in "parser" such as:
func getJSONLead()
func getTOMLLead()
func getYAMLLead()

Then rewriting these lines in convert.go to use them:
return convertContents(rune([]byte(parser.JSONLead)[0]))
return convertContents(rune([]byte(parser.TOMLLead)[0]))
return convertContents(rune([]byte(parser.YAMLLead)[0]))

Then all these consts could be limited to "parser".

I think the parser should be the only one really knowing these variables.

**Comment by bep** [comment]
1) YAMLLead etc. should be exported.
2) These constants are abused in convert.go as a format identifier. 
3) It isn't really used for any sensible in convert.go so it can be removed. But if not, we can fix that by adding some exported constants in a common package (parser?) with YAML = "yaml" etc.  Which is better than using some roundabout way of getting there.
