### ISSUE TITLE
Docs for RSS template do not seem correct

### ISSUE THREAD

**Issue by cfjedimaster** [gohugoio/hugo#2922]
According to the docs for the default RSS template (https://gohugo.io/templates/rss/), one can include an author name value and see it reflected in the index.xml. In my testing, this was not the case. In fact, I do not see the managingEditor block at all.

**Comment by digitalcraftsman** [comment]
Is this still an issue?

**Comment by cfjedimaster** [comment]
I went to test, but ran into #3638.

**Comment by cfjedimaster** [comment]
Seems to be fixed

**Comment by digitalcraftsman** [comment]
Then I'll close this issue. If the issue is still existing please open a new issue at gohugo/hugoDocs instead.
