### ISSUE TITLE
Article template can't be generated when title contains '+'

### ISSUE THREAD

**Issue by dawnarc** [gohugoio/hugo#2931]
For example, if my article title is "Hello World(C++ example)", hugo would post error when generating, because there are two **plus** characters in title.

**Comment by THoenig** [comment]
Hi.
I can't reproduce this error with hugo v0.19-DEV using different themes. Could you post your hugo version and the name of the theme you used, please?

**Comment by dawnarc** [comment]
@THoenig The name of theme I used is: hugo-tranquilpeak-theme, and hugo version I used is 0.18.1.

**Comment by THoenig** [comment]
@dawnarc I still can't reproduce it. What does the error message say?

**Comment by dawnarc** [comment]
@THoenig As the following pics showed, when click on the link of article, 404 error would be post in browser.
![error-01](https://cloud.githubusercontent.com/assets/3351764/21940891/37576bc4-da01-11e6-8a21-f1ddd29b2b20.png)
![error-02](https://cloud.githubusercontent.com/assets/3351764/21940894/3b0ef07a-da01-11e6-9bf6-7ed28363c318.png)

**Comment by THoenig** [comment]
@dawnarc The problem has something to do with this line in the config:
` post = "/:year/:month/:slug/"`

When the files are copied to "public/\<year\>/\<month\>" the "+" are replaced with " " (space). This doesn't happen if the line is removed.

As a workaround you can either remove the problematic line or add (for example)
`slug = "hello-worldc-plus-plus-example"`
in your post configuration.

**Comment by dawnarc** [comment]
@THoenig I see, Thx very much!
