### ISSUE TITLE
Unable to download gopkg.in/yaml.v1 with git 1.7.1

### ISSUE THREAD

**Issue by whereisaaron** [gohugoio/hugo#297]
```
$ go get github.com/spf13/hugo
```

This would always fail for me on CentOS 6.5 and never complete, though it would work fine in other places. I tracked it down to the 'gopkg.in/yaml.v1' meta package which causes git 1.7.1 to hang. On other hosts with git 1.9.1 it does work.

```
$ git clone https://gopkg.in/yaml.v1 /path/go/src/gopkg.in/yaml.v1
Initialized empty Git repository in /path/go/src/gopkg.in/yaml.v1/.git/
> hangs here <
```

The workaround is to first clone the library directly from github into the expected folder before you run go get. Then 'go get' won't hang.

```
git clone https://github.com/go-yaml/yaml /path/go/src/gopkg.in/yaml.v1
go get -v github.com/spf13/hugo
```

**Comment by NoICE** [comment]
So I need newer git? Bummer. I'm on debian squeeze right now and it has git 1.7.2.5.

**Comment by Hunter-Github** [comment]
The solution is to use `git clone --branch v1` for yaml.v1 and fsnotify.v1, and `git clone --branch v2` for yaml.v2. Other than that, installation goes swimmingly.

**Comment by vmarkovtsev** [comment]
It kind of sucks that I have to write this special workaround for yaml.v2 since it' not allowed to upgrade git in my production env. IMHO this is gopkg.in fault in not testing with all the possible Git versions others may use.
