### ISSUE TITLE
IDN support

### ISSUE THREAD

**Issue by tomap** [gohugoio/hugo#3011]
Hi,

I have an IDN (international domain name), so a domain name with non ascii chars
http://tpî.eu
When using it as a baseurl, hugo transforms it into normalized url http://xn--tp-rja.eu/, which is not nice, and not useful.
It seems it comes from purell:
https://github.com/PuerkitoBio/purell/blob/57f76c276dc73fa5b6924b5248bea2fc8e517e68/purell.go#L168
There does not seem to be a way to set a parameter to not normalize the baseURL into the non pretty http://xn--

Would there be a way of changing that?
Adding a settings, or... ?

The purpose of normalizing urls is to show users that they are not going to go to google.com, but to gôogle.com clearly by displaying xn--gogle-6ta.com

not sure it is useful for the current site url :) (you are already on it)

Than you

**Comment by windo** [comment]
This is still definitely a problem. My domain is õäöü.ee and the whole point of it is to enumerate the "special letters" in Estonian alphabet. Getting these shown as anything but the pure IDN defeats the purpose.

**Comment by tomap** [comment]
Hi, due to this I switched to hexo
Tpî.eu
