### ISSUE TITLE
Links missing trailing slash

### ISSUE THREAD

**Issue by abh** [gohugoio/hugo#302]
Nice work on the new version. One small nit:

Since upgrading our `{{ .Permalink }}` links are missing the trailing slash. Before they were rendered as `http://example.com/foo/`, now `/foo`. Getting rid of the domain is nice, but missing the slash just introduces a useless redirect before the user is served the page.

**Comment by keaeriksson** [comment]
Hi, if you are using AWS to host your Hugo site I wrote a blog post on how to remove trailing slashes using S3, CloudFront and Lamdba@Edge here: https://mocki.io/hosting-a-hugo-site-on-aws-s3-and-cloudfront.
