### ISSUE TITLE
.RSSLink points to wrong destination

### ISSUE THREAD

**Issue by ominty** [gohugoio/hugo#3037]
I use this from the docs:

```
{{ if .RSSLink }}
<link href="{{ .RSSLink }}" rel="alternate" type="application/rss+xml" title="{{ .Site.Title }}" />
<link href="{{ .RSSLink }}" rel="feed" type="application/rss+xml" title="{{ .Site.Title }}" />
{{ end }}
```
and I end up with RSS links in the form of
http://www.example.com/{section-name}.xml
instead of
http://www.example.com/{section-name}/index.xml
where indeed I can find the relevant feed file.

uglyURLs = true             
relativeURLs = true         
canonifyURLs = false        
 V0.18.1

**Comment by ominty** [comment]
I have put a repo here: https://github.com/ominty/ominty-hugoissues/commit/84ea0e0650a0f063209945ac7b855d388790b4dd

**Comment by moorereason** [comment]
This appears to be working correctly in 0.19, which as released yesterday.

**Comment by ominty** [comment]
I had a short look yesterday evening which raised some issues. I'll investigate this evening and come back on this.
