### ISSUE TITLE
Multilingual - Metadata (Taxonomy and Sections)

### ISSUE THREAD

**Issue by Brahmasmi** [gohugoio/hugo#3046]
Can we implement a uniform taxonomy and sections structure across multiple languages, which then gets rendered after translation by Hugo?
Let us consider a fictional rendered URLs example-
1) en-gb/developer/Norway
2) nb-no/developer/Norway
3) nb-no/developer/Norge (slug = Norge)
4) nb-no/utvikler/Norge (path = utvikler, slug = Norge)

According to Hugo's recommended content organization, there would be one folder called developer, which contains the content for Norway in multiple languages. This content contains taxonomy tags, which themselves hold localised values.

Currently, one would need to specify the path and slug on every piece of content to get URL 4 rather than URL 2 - I may be wrong here, I am still trying to wrap my head around this. Furthermore, one would need to create a separate set of taxonomies to represent essentially the same information.

It would be better if Hugo could automatically translate the taxonomies and sections, since putting path and slug on every content would not be a scalable solution.

There was a discussion regarding the taxonomy aspect in #2465 , where @bep mentioned
> But it would be nice to have one taxonomy definition (category -> categories) and have it translated, but that is certainly out of scope of this feature. May have that in mind when fixing Page vs. Node.

The operating example there was "/category/" vs "/kategorien/" as requested by @digitalcraftsman.

There is an additional point here. Assuming that "category = Developer" for en and "kategorien = Entwickler" for de - "/category/Developer/" is functionally equivalent to "/kategorien/Entwickler". Interlinking these directly as translations of each other would be desirable.

Would appreciate any help/input regarding this. I was unable to find any documentation for achieving this - in case I missed out, please point me to the same.

**Comment by bep** [comment]
I understand what you want, and we may get there, but I'm not sure how ...

You may get some inspiration from my site

https://github.com/bep/bepsays.com/blob/master/i18n/en.yaml#L50

Which is quick and dirty, but kind of works for smaller sites.

**Comment by Brahmasmi** [comment]
If the 0.31 Language Multihost edition provides the feature requested in this issue, I would be happy to close this issue. The reason for not being able to ascertain this myself is because I have been away from Hugo for a long time and as such I apologize.

In case this feature is yet to be implemented, I would request that this issue be marked with the "Keep" label. The rationale is explained in the original issue, and I would be happy to discuss any impediments, or alternative mechanisms.

This and #3047 are important for us to support volks globally.

**Comment by bep** [comment]
>The reason for not being able to ascertain this myself is because I have been away from Hugo for a long time and as such I apologize.

I will close this then, because I have no time to look into this, either, and as such I apologize.
