### ISSUE TITLE
hugo new --kind=$string  is doing nothing?

### ISSUE THREAD

**Issue by hloeffler** [gohugoio/hugo#3076]
it seams that `hugo new --kind="string" post/test.md` the --kind= parameter has no impact at all
https://github.com/spf13/hugo/blob/master/commands/new.go#L89

the docs aren't any help either

Version:
Hugo Static Site Generator v0.18.1 BuildDate: 2016-12-30T11:05:34+01:00

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

I will keep this issue open to track the doc improvement.

**Comment by hloeffler** [comment]
thanks,
okay lets start easy:
what are valid values for hugo new --kind=$this
?

**Comment by bep** [comment]
I'm delegating any questions to the forum, on principle -- that is the only way to keep some control of this issue tracker with the limited human resources available.
