### ISSUE TITLE
Data files edits only showing up during LiveReload if data file existed at launch of server. New files are not detected.

### ISSUE THREAD

**Issue by zorn** [gohugoio/hugo#3077]
First, I'd like to say thank you -- really enjoying using Hugo on a fews sites.

I think I found an issue. With my new site I'm trying to use data files to power some of the content. The [docs](https://gohugo.io/extras/datafiles/) say data files work with LiveReload but in my experience the LiveReload only works when editing an **existing** data file. If I launch the local hugo server and then add a data file it is not showing up as an accessible variable.

**Comment by bep** [comment]
I will check. It sounds a little bit strange, but you are probably correct.

I have deliberately not marked this as a bug, as the workaround is easy, and I will not say that this is a very common thing.

**Comment by bep** [comment]
@zorn I have tested this locally with the newest Hugo on `macOS` and TOML data files and can not reproduce this issue.

Can you retest this with the latest Hugo, and if still and issue, provide more information, such as 

* What OS running?
* What data files format used?
