### ISSUE TITLE
proposal: Optional externalize site config

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3090]
This relates to #3088 -- re. @digitalcraftsman comment:

>This proposal defines the authors in the config file instead of using data files as in #1850 . What advantages do you see here? I would rather try to keep the config file flat.

So `author` configuration is site configuration, but because it may potentially be lots of them, we should put them in some special place. 

>Sure, site params must be configured in config.toml ... Oh, expect author params, which must be put in files below /data in a special folder starting with double dash ...

I suggest rather that we make this a general thing:

Site config belongs in `config.toml` and cousins, but it can optionally be put in files below `/data/_config/`. Keys in `config.toml` will always win.

@digitalcraftsman this one is open for discussion.

**Comment by digitalcraftsman** [comment]
I like this generic and flexible approach - it's optional can be done as you like. Putting thinks like author profiles, menu definitions etc. in different data files can definitely improve the maintenance of a large config file.

But how do you distinguish between `data/_config/language/en.toml` and `data/_config/language.en.toml`?

**Comment by bep** [comment]
>But how do you distinguish between data/_config/language/en.toml and data/_config/language.en.toml?

The last one does not make sense the way we parse data files. It will be an object with key "language.en".

I have not analyzed every corner of this proposal, but I think it should be doable.

**Comment by bep** [comment]
Also note that all of the site config that we, for some reason, put in external data files, will have to logically follow the same life cycle as the site config (think live reload), so making it "one thing" makes sense.
