### ISSUE TITLE
Provide hl_lines option in code fences

### ISSUE THREAD

**Issue by Daniel15** [gohugoio/hugo#3104]
Hello!

I originally posted this in the forum (https://discuss.gohugo.io/t/provide-hl-lines-option-in-code-fences/5607) and it was suggested that I post here as a feature request.

I'm aware that Hugo allows the `hl_lines` option to be passed to Pygments using this syntax:

```
{{< highlight js "linenos=inline,hl_lines=2 3" >}}
console.log('hello');
alert('hello 1');
alert('hello 2');
{{< / highlight >}}
```

However, some systems allow code fences to also specify line numbers to highlight, like this:

    ```js{2,3}
    console.log('hello');
    alert('hello 1');
    alert('hello 2');
    ```

For example, see https://zpao.com/posts/adding-line-highlights-to-markdown-code-fences/. This is the approach I'm using on one of my Jekyll sites at the moment.

Is there a way to achieve the same thing using Hugo? More concretely, is there a way to modify the built-in code fence handling to also allow highlighted line numbers to be passed in?

Thanks!

**Comment by bep** [comment]
What other systems and what is the specification of the command format? Is it only line numbers?

**Comment by Daniel15** [comment]
I've seen it in a few places. Unfortunately I didn't make a note of the other places, but here's one implementation that I've used on a few Jekyll-powered sites: https://zpao.com/posts/adding-line-highlights-to-markdown-code-fences/. This version is used on a few React-related sites (at least React and ReactJS.NET), and a GitHub search shows at least 85 sites using it: https://github.com/search?q=%22hl_lines+%3D+lang_parts%5B1%5D.gsub%28%22&type=Code&utf8=%E2%9C%93

**Comment by bep** [comment]
Let me put this way: It would convince me if, say, GitHub had this as a standard in their markup.

**Comment by Daniel15** [comment]
I don't know if it's part of any markdown standard, I've only ever seen it on individual sites rather than listed as a standard anywhere.

**Comment by bep** [comment]
I have checked, and this has to be done in the Markdown renderer(s):

https://github.com/russross/blackfriday/blob/master/html.go#L257

As we receive just the `lang` and the inner content.

So if you really want this, you should post an issue there and link back to this issue.

**Comment by Daniel15** [comment]
Ohh, it's unfortunate that the Markdown parser just spits out HTML rather than providing an AST and allowing you to override parts of the renderer... It's not a very flexible/scalable design 😢  . Oh well. I'll open an issue in that repo.

**Comment by Tzaoh** [comment]
Aparently the author want this feature to be implements in v2. How bad would be to start using blackfriday v2 instead of v1? Would the migration be easily?
