### ISSUE TITLE
Image process handling (nice-to-have proposal)

### ISSUE THREAD

**Issue by wildhaber** [gohugoio/hugo#3158]
### What is this issue all about?

I would like to  breathe new life into the whole part of image processing and bring some traction to this topic. Since it is still on the Hugo roadmap, and at least in my opinion a huge puzzle piece to make Hugo more complete. Hope my proposal below helps in this case.

After reading a lot of other issues sometimes just covering one part of the Image processing I try to bring up a complete idea that covers most of the usecases with the same writing style instead of mixing up incompatible implementations together that leads into missunderstandings when using the code.

One of the main goal was, to make usage of available popular and fast Go Packages/Libraries to make the first step easy.

### Why I write this issue and do not implement the feature?

Unfortunately I am not a Go-Developer, but I can help at delivering proposals from a Hugo user perspective 🙂 

Namings or definitions I use below are **just ideas, feel free to have a different opinion on them**.

## Features

This proposal covers the following features:

 - Image cropping in with content awareness (SmartCrop)
 - Simple cropping
 - Image resize with different interpolations
 - Image Flip / Rotate (maybe according EXIF-Info?)
 - Image Manipulation
    - Brightness
    - Contrast
    - Gamma
    - Hue
    - Saturation
    - Blend modes (image overlay / watermarks)
    - Blur
    - Channel Extraction
    - Painting: Flood Fill
- Image Effects
    - Dilate
    - Edge Detection
    - Emboss
    - Erode
    - Grayscale
    - Invert
    - Median
    - Sepia
    - Sharpen
    - Sobel
    - Unsharp Mask
 - Save images

I know this list looks like a lot of work, but I more or less copied features from existing libraries.

## Libraries

Libraries I have in mind solving all the features above.

**bild**
Purpose: _Image manipulation and effects_
Documentation: https://godoc.org/github.com/anthonynsimon/bild
Repository: https://github.com/anthonynsimon/bild
License: MIT

**resize**
Purpose: resize images
Repository: https://github.com/nfnt/resize
License: MIT

**smartcrop.go**
Purpose: content aware cropping including face-detection
Documentation: https://godoc.org/github.com/muesli/smartcrop
Repository: https://github.com/muesli/smartcrop
License: MIT

Ok, I have to admit having no idea about the size nor performance of these libraries. But they look great in my eyes and are well documented and the API could be used for the implementation 1:1.

---

## Process in the templates

In my eyes, an image process in the template should look like this:

**Open/Load source image** ==> **Process pipeline** ==>  **Save image** ==> (returns an image data including a .Permalink that can be used for including)

In code that could look like this:

```go
// imageProcess (ip)

// 1. Open/Load source image
{{ $image := ipOpen "static/great-picture.jpg" }}

// 2. Process pipeline
{{ $grayscaled := ipGrayscale  $image }}
{{ $blurry := ipGaussianBlur $grayscaled 5.0 }}
{{ $crop := ipCrop $blurry 400 200 "smart" }}

// 3. Save image
{{ $processedImage := ipSave $crop }} // => proposal: save it under <public>/[optional: <configuredImageOutputPath>/]<md5hash>.<extension> (this way it would be easy regarding caching)

// 4. Use the image
{{ with $processedImage }}
<img src="{{ .Permalink }}" width="{{ .Width }}" height="{{ .Height }}">
{{ end }}
```

I see a lot of potential of creating partials and shortcodes out of it. Going with functions provides amazing flexibility vs the Shortcode-Approach discussed in this issue - https://github.com/spf13/hugo/issues/1014.

Basically this is the core way of processing. Below please find a full list of the functionalities specified.

---

#### ipOpen

_Definition:_
```go
ipOpen <path-to-image>
```

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $image := ipOpen "static/great-picture.jpg" }}
```

#### ipSave

_Definition:_
```go
ipSave  [optional: <output-filename> | default: <public>/[optional: <configuredImageOutputPath>/]<md5hash>.<extension>]
```

_Return:_
_map[]_

```json
{
  "Permalink" : "https://example.com/images/d41d8cd98f00b204e9800998ecf8427e.jpg",
  "RelPermalink" : "/images/d41d8cd98f00b204e9800998ecf8427e.jpg",
  "Width" : 400,
  "Height" : 200
}
```

It might get necessary to save the define a default output path for processed images in the `config.toml` like:

```toml
image_output_path = "images-generated/"
```

_Example:_

```go
{{ $processedImage := ipSave $image }}
{{ $processedImageDefineOutput := ipSave $image "special/output-thumbnail.jpg" }}

{{ with $processedImage }}
<img src="{{ .Permalink }}" width="{{ .Width }}" height="{{ .Height }}">
{{ end }}
```

#### ipCrop

_Definition:_
```go
ipCrop <image.Image> <width> <height> [<position : ["smart" | "topleft" | "topcenter" | "topright" | "middleleft" | "middlecenter" | "middleright" | "bottomleft" | "bottomcenter" | "bottomright"] | (slice x0, y0, x1, y1)> | default: "smart" ]
```

_Library Reference:_
 - https://godoc.org/github.com/anthonynsimon/bild/transform#Crop
 - https://godoc.org/github.com/muesli/smartcrop#SmartCrop
> SmartCrop returns a crop map like `{ X, Y, Width, Height, Score }` - this needs to be converted into a [image.Rectangle](https://godoc.org/image#Rectangle).

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $crop := ipCrop $image 400 200 }}
```

```go
{{ $crop := ipCrop $image 400 200 "topleft" }}
```

#### ipResize

_Definition:_
```go
ipResize <image.Image> <width> <height> [<interpolation : "NearestNeighbor" | "Bilinear" | "Bicubic" | "MitchellNetravali" | "Lanczos2" | "Lanczos3" > | default: "Bilinear" ]
```

_Library Reference:_
 - https://github.com/nfnt/resize
 - https://github.com/nfnt/resize/blob/master/resize.go#L81

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $resize := ipResize $image 400 200 }}
```
```go
{{ $resize := ipResize $image 400 200 "Lanczos3" }}
```

#### ipThumbnail

_Definition:_
```go
ipThumbnail <image.Image> <maxWidth> <maxHeight> [<interpolation : "NearestNeighbor" | "Bilinear" | "Bicubic" | "MitchellNetravali" | "Lanczos2" | "Lanczos3" > | default: "Bilinear" ]
```

_Library Reference:_
 - https://github.com/nfnt/resize
 - https://github.com/nfnt/resize/blob/master/thumbnail.go#L27

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $thumbnail := ipThumbnail $image 40 20 }}
```
```go
{{ $thumbnail := ipThumbnail $image 40`
20 "Lanczos3" }}
```

#### ipFlip

_Definition:_
```go
ipFlip <image.Image> <flipAxis : "horizontal" | "vertical">
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild
 - https://godoc.org/github.com/anthonynsimon/bild/transform#FlipH
 - https://godoc.org/github.com/anthonynsimon/bild/transform#FlipV

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $flip := ipFlip $image "horizontal" }}
```
```go
{{ $flip := ipFlip $image "vertical" }}
```

#### ipRotate

_Definition:_
```go
ipFlip <image.Image> <angle>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild
 - https://godoc.org/github.com/anthonynsimon/bild/transform#Rotate

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $rotate := ipRotat`
 $image 60 }}
```

#### ipBrightness

_Definition:_
```go
ipBrightness <image.Image> <change>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#brightness
 - https://godoc.org/github.com/anthonynsimon/bild/adjust#Brightness

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $brighter := ipBrightness `
image 0.25 }}
```

#### ipContrast

_Definition:_
```go
ipContrast <image.Image> <change>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#contrast
 - https://godoc.org/github.com/anthonynsimon/bild/adjust#Contrast

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $contrast := ipContrast $image -0.5 }}
```

#### ipGamma

_Definition:_
```go
ipGamma <image.Image> <gamma>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#gamma
 - https://godoc.org/github.com/anthonynsimon/bild/adjust#Gamma

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $gamma := ipGamma $image 0.4 }}
```

#### ipHue

_Definition:_
```go
ipHue <image.Image> <change>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#hue
 - https://godoc.org/github.com/anthonynsimon/bild/adjust#Hue

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $hue := ipHue $image -42 }}
```

#### ipBlendMode

_Definition:_
```go
ipBlendMode <background-image> <foreground-image> [<blendmode : "Add" | "ColorBurn" | "ColorDodge" | "Darken" | "Difference" | "Divide" | "Exclusion" | "Lighten" | "LinearBurn" | "LinearLight" | "Multiply" | "Normal" | "Opacity" | "Overlay" | "Screen" | "SoftLight" | "Subtract"> | default: "Normal"] [<percentage (necessary for Opacity)> : default: 1]
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#blend-modes
 - https://godoc.org/github.com/anthonynsimon/bild/blend

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $blend := ipBlendMode $background $foreground "Multiply" }}
```
```go
{{ $blend := ipBlendMode $background $foreground "Opacity" 0.5 }}
```

#### ipBlur

_Definition:_
```go
ipBlur <image.Image> <radius> [<method : "Box" | "Gaussian"> | default: "Gaussian"]
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#blur
 - https://godoc.org/github.com/anthonynsimon/bild/blur

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $blurry := ipBlurry $image 5 }}
```
```go
{{ $blurry := ipBlurry $image 17 "Box" }}
```

#### ipExtractChannel 

_Definition:_
```go
ipExtractChannel <image.Image> <channel : "Red" "Green" "Blue" "Alpha">
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#extract-channel
 - https://godoc.org/github.com/anthonynsimon/bild/channel#Channel

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $extractNoRed := ipExtractChannel $image "Red" }}
```

#### ipFloodFill 

_Definition:_
```go
ipFloodFill <image.Image> <point : (slice X Y)> <color : (slice R G B A)> <fuzzy>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#flood-fill
 - https://godoc.org/github.com/anthonynsimon/bild/paint

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $floodFill := ipFloodFill $image (slice 15 366) (slice 255, 0, 45, 255) 15 }}
```

#### ipDilate 

_Definition:_
```go
ipDilate <image.Image> <radius>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#dilate
 - https://godoc.org/github.com/anthonynsimon/bild/effect#Dilate

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $dilate := ipDilat
e $image 3 }}
```

#### ipEdgeDetection 

_Definition:_
```go
ipEdgeDetection <image.Image> <radius>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#edge-detection
 - https://godoc.org/github.com/anthonynsimon/bild/effect#EdgeDetection

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $ipEdgeDetection := ipEdgeDetection $image 1.0 }}
```

#### ipEmboss 

_Definition:_
```go
ipEmboss <image.Image>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#emboss
 - https://godoc.org/github.com/anthonynsimon/bild/effect#Emboss

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $ipEmboss := ipEmboss $image }}
```

#### ipErode 

_Definition:_
```go
ipErode <image.Image> <radius>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#erode
 - https://godoc.org/github.com/anthonynsimon/bild/effect#Erode

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $ipErode := ipErode $image 3 }}
```

#### ipGrayscale 

_Definition:_
```go
ipGrayscale <image.Image>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#grayscale
 - https://godoc.org/github.com/anthonynsimon/bild/effect#Grayscale

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $grayscale := ipGrayscale $image }}
```

#### ipInvert 

_Definition:_
```go
ipInvert <image.Image>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#invert
 - https://godoc.org/github.com/anthonynsimon/bild/effect#Invert

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $inverted := ipInvert $image }}
```

#### ipMedian

_Definition:_
```go
ipMedian <image.Image> <radius>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#median
 - https://godoc.org/github.com/anthonynsimon/bild/effect#Median

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $median := ipMedian $image 10.0 }}
```

#### ipSepia

_Definition:_
```go
ipSepia <image.Image>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#sepia
 - https://godoc.org/github.com/anthonynsimon/bild/effect#Sepia

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $sepia := ipSepia $image }}
```

#### ipSharpen

_Definition:_
```go
ipSharpen <image.Image>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#sharpen
 - https://godoc.org/github.com/anthonynsimon/bild/effect#Sharpen

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $sharpen := ipSharpen $image }}
```

#### ipSobel

_Definition:_
```go
ipSharpen <image.Image>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#sobel
 - https://godoc.org/github.com/anthonynsimon/bild/effect#Sobel

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $sobel := ipSobel $image }}
```

#### ipUnsharpMask

_Definition:_
```go
ipUnsharpMask <image.Image> <radius> <amount>
```

_Library Reference:_
 - https://github.com/anthonynsimon/bild#unsharp-mask
 - https://godoc.org/github.com/anthonynsimon/bild/effect#UnsharpMask

_Return:_
[image.Image](https://godoc.org/image)

_Example:_
```go
{{ $unsharpMask := ipUnsharpMask $image 0.6 1.2 }}
```

## Conclusion

Ok, sorry, for this looooong issue / wishlist. For sure not every function is weighted with the same priority. And obviously all the implementation descriptions above sould be treated as an idea / proposal and not as expected. Any thoughts are highly appreciated :smile:

Final thoughts not covered above:

 - How to deal with different file formats?
 - How to deal with JPEG-Quality?

I really hope, this issue help the Hugo-Project on it's roadmap.

## Update

Finally, I made my first babyfeetsteps in Go and tried to implement the functionalities above.

You can find the current progress in this [Branch / wildhaber:rw-3158-image-process](https://github.com/spf13/hugo/compare/master...wildhaber:rw-3158-image-process) and a [Live Demo](https://imageprocess.gohugohq.com/) of the output is so far.

Currently I'm at the end of my knowledge in go and I don't think I should develop this feature any further. There are places where I would need some help and I'm not even sure, if this is the proper approach to deal with images. My question is now if I should make a very incomplete Pull Request or leave it here in the Issues-Section?

**Comment by nilsnh** [comment]
Hi there, :) I have not yet contributed to Hugo. But I'm interested in this image processing feature and I see that there's a [contribution guide](https://github.com/spf13/hugo/blob/master/CONTRIBUTING.md). 👍 ⚡️ I have done very little Go programming really but I can help out if needed.
