### ISSUE TITLE
Special characters in links lead to 404

### ISSUE THREAD

**Issue by pczajkowski** [gohugoio/hugo#3161]
I'm using **'()** in filenames and permalinks for my blog posts and Hugo is generating it as:
https://blog.liox.eu/2015/12/13/The_book_was_better_Godfather/

But the actual content sits in:
2015/12/13/The_book_was_better_(Godfather)

So I'm getting 404.

v0.20-DEV linux/amd64 BuildDate: 2017-03-08T13:33:46+01:00

**Comment by eamonnmcevoy** [comment]
I'm unable to reproduce this, how are you creating your files?
I've tested with `hugo new "post/test_(folder)/file1.md"` and `hugo new "post/test_(file).md"`

Both tests produced a working links
`http://localhost:1313/post/test_folder/file1/`
and
`http://localhost:1313/post/test_%28file%29/`

**Comment by pczajkowski** [comment]
Just `hugo` in the main folder and it puts output in `public` subfolder. Same happens with `hugo server`.

**Comment by pczajkowski** [comment]
I have URL property set as below:
url: /2015/12/13/The_book_was_better_(Godfather)/
