### ISSUE TITLE
Add support for pages in the union/intersect template function

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugo#3174]
Complex `where`-nestings could be simplified by filtering pages with `union` and `intersect`:

- `union` corresponds to the logical OR operator (x is an element of set A OR set B)
- `intersect` corresponds to the logical AND operator (x is an element of set A AND set B)

Example: find all pages where `.Params.a` equals `"v1"` AND `.Params.b` equals `"v2"`

```
{{ $v1 := where .Site.Pages "Params.a" "v1" }}
{{ $v2 := where .Site.Pages "Params.b" "v2" }}

{{ $filtered := $v1 | intersect $v2 }}
```

**Comment by bep** [comment]
Note that instead of adding support for one and one type, it should support any type that can be compared by `==` and `!=`.

**Comment by digitalcraftsman** [comment]
> Note that instead of adding support for one and one type, it should support any type that can be compared by == and !=.

Makes sense

> And I think you switched AND and OR in the bullet points above.

The typical copy-and-pasting dilemma. It's fixed now.

**Comment by bep** [comment]
@digitalcraftsman if you have no plan of doing this in the next few days, please move this to 0.21.

**Comment by bep** [comment]
@moorereason @digitalcraftsman The intersect func should be fine now, right? It would be cool if we could also get the union up to speed? That would give us a good story on page queries.

**Comment by digitalcraftsman** [comment]
Great! We should also add some nice examples to the docs. We should link from the docs for the `where` template func to examples for `union` and `intersection`.

/cc @rdwatters

**Comment by bep** [comment]
@digitalcraftsman my post was riddled with question marks, which may be good to address before we start worrying about examples.

**Comment by moorereason** [comment]
The `union` enhancements are tracked in #3411.  I hope to get to those in the v0.21 time frame (feel free to claim that issue if you want to do it!).  They should look much like the `intersect` updates in #3328.

I still don't think we support Page comparisons.  We are doing comparisons of basic types.  We don't compare structs.  I looked at comparing Pages a few days ago and ran into an issue with cyclical imports since `tpl/collections` would need to import `hugolib`.

**Comment by bep** [comment]
@moorereason re the cyclic, I had a Git stash laying around, pushed it in https://github.com/spf13/hugo/pull/3484 -- I probably will not complete this, so take what you want ...

You don't really need to test real pages, just make up some structs and slices of struct pointers.

**Comment by Slevin2017** [comment]
If there two range, for example:
{{ $arr1 := slice "1" "2" "3" "2" "5" }}
{{ $arr2 := slice "1" "3" }} 
How can I find different element, for this case 2 and 5?
