### ISSUE TITLE
Tagcloud getting: 'executing "index.html" at <.Name>: can't evaluate field Name in type hugolib.WeightedPages' 

### ISSUE THREAD

**Issue by mpas** [gohugoio/hugo#318]
I am trying to build a tag cloud in the index.html and using the example given in the docs.

<h3>Tags</h3>

{{ range .Site.Taxonomies.tags }}
<a href="/tags/{{ .Name | urlize }}">{{ .Name }}</a>
{{ end }}

But whenever i do this i get an error:
'executing "index.html" at <.Name>: can't evaluate field Name in type hugolib.WeightedPages' 

Am i missing something?

Cheers Marco

**Comment by dvdsgl** [comment]
Similarly, I am trying to list my guides:

```
{{ range .Site.Sections.guides }}
  <li>"{{ .Title }}"
{{ end }}
```

But `.Title` isn't valid on `WeightedPage`. How do I get at the page representation?

**Comment by dvdsgl** [comment]
I've tried:

```
{{ range .Site.Sections.guides }}
  <li>"{{ .Page.Title }}"
{{ end }}
```

But I just get empty strings.
