### ISSUE TITLE
tpl: Add filepath.FromSlash template func

### ISSUE THREAD

**Issue by robsonsobral** [gohugoio/hugo#3187]
Hi!

I just want to let you know that `.File.Dir` can't be used as `where` value on Windows systems due to the different slash.

```
{{ with where $.Site.Pages ".File.Dir" "_home/versions/" }}
```

On Windows it needs to be:

```
 {{ with where $.Site.Pages ".File.Dir" "_home\versions\" }}
```

This is a problem when developing on multiple operational systems.

Thanks!

**Comment by bep** [comment]
This has been discussed, but I don't think we have an issue tracking it.

**Comment by moorereason** [comment]
@robsonsobral, does escaping the `\` solve the issue?

```
{{ with where $.Site.Pages ".File.Dir" "_home\\versions\\" }}
```

**Comment by bep** [comment]
This issue is about multiplatform templates.

**Comment by robsonsobral** [comment]
@moorereason , I'm sorry! I missed your response. I'm sorry.

I believe the file path functions should understand both ways: `/` and `\`.

**Comment by bep** [comment]
>I believe the file path functions should understand both ways: / and \.

What specific path functions are you talking about?

**Comment by robsonsobral** [comment]
Ops! I should have said variables too.

- `.File.Path`
- `.File.Dir`
- `readDir`
- `readFile`

Everything that read a file path.

**Comment by bep** [comment]
.File.Path
.File.Dir

Those are values and not funcs and they cannot "understand both ways".

**Comment by moorereason** [comment]
@robsonsobral,
Is this still an issue for you or did you solve the problem in a different way?  Can you give a fuller explanation of your use case?  Why are you accessing the .File object?

**Comment by robsonsobral** [comment]
@moorereason , probably was to load some partial content. I haven't coding Hugo on Windows for some time. Can you give me some time to test it, please?
