### ISSUE TITLE
Steve's vision for Hugo

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugo#3205]
This issue acts as a reminder for the presentation that @spf13 put together to share his thoughts about ["The Future of Hugo"](https://drive.google.com/file/d/0B-s2yFMZO3LeejNNeXVuRVZIUHc/view). 

At the time of writing certain things mentioned like i18n support and "make everything a node"-transition are already built-in to Hugo.

**Comment by vassudanagunta** [comment]
@digitalcraftsman when did @spf13 put together that presentation? Has his vision been updated since? Has anyone else presented their thoughts on a coherent vision (as opposed to grab-bag of pet features) since?

**Comment by digitalcraftsman** [comment]
Steve created this presentation to communicate his vision on a private channel to the other maintainers. I don't know the exact date when he shared this document but it was months before I created this issue.

> Has his vision been updated since?

No changes have been made since then. Some parts are can be ignored with the latest developments (i.e. the whole nodes vs. pages distinction). Others still have to finds it's way into Hugo.

> Has anyone else presented their thoughts on a coherent vision (as opposed to grab-bag of pet features) since?

Not in this kind of presentation. @bep as lead developer will finally decide on which (new) features will be in the focus. He has a "mental roadmap" of improvements and major features that he would like to see implemented before making a v1.0 release.

AFAIK he hasn't written down what the missing pieces are to complete the puzzle. But the milestones and currently active issues should give you a good picture of where the development is heading towards.

Nonetheless, it would be still interesting to have some kind of outline of his vision.

**Comment by jhabdas** [comment]
I'm particularly interested in the concept of multi-part/multilingual metadata inheritance (Ref: [Slide 16–17](https://drive.google.com/file/d/0B-s2yFMZO3LeejNNeXVuRVZIUHc/view)) as from what I can tell right now there's quite a bit of duplication in my bundles. Perhaps this is something which could be added with the introduction of multi-part pages, if that feature is still on the table, as I saw Steve mention meta inheritance as a feedback point in the multilingual implementation but met some resistance where I feel the original i18n implementor may not have considered the general use case.

**Comment by jmooring** [comment]
Outdated, not actionable.
