### ISSUE TITLE
Create Custom Plugins?

### ISSUE THREAD

**Issue by Naatan** [gohugoio/hugo#321]
Hi there,

Is there a way to create custom plugins for Hugo? I can't seem to find any information on this in the documentation.

Thanks

**Comment by akshaybabloo** [comment]
Not true anymore. See https://stackoverflow.com/a/24641342/3782963

**Comment by RealOrangeOne** [comment]
Discussion has continued over on https://github.com/gohugoio/hugo/issues/3207, in addition to the forum.
