### ISSUE TITLE
Hard linebreaks not working in markdown

### ISSUE THREAD

**Issue by artelse** [gohugoio/hugo#3212]
Am struggling to get linebreaks to work in markdown. In `config.toml` I've added the `[blackfriday]
  extensions = ["hardLineBreak"]` setting. `Hugo config` shows it picked up the setting, but no linebreaks are inserted in compiled markdown files.
One curiosity is when hugo compiles the site, the log shows the used config file to be empty:
`INFO 2017/03/20 23:44:23 Using config file:  `

Hugo version 0.19, macOS 10.12.3

Discussion here:
https://discuss.gohugo.io/t/hard-linebreaks-not-working-in-md/5853

**Comment by rdwatters** [comment]
@artelse As I mentioned on the forums, I am unable to reproduce this error you're having and we are working on similar machines. We will get a lot further if you can share a repo with me to test locally, esp since you're not providing any errors, additional code, etc.

**Comment by bep** [comment]
I just tested this blackfriday setting, and I'm not able to get any hard linebreaks either.

**Comment by bep** [comment]
I have retested it now, I'm not sure what I did wrong the last time, but this works exactly as I expect it to. We even have a test for it:

https://github.com/gohugoio/hugo/blob/master/hugolib/page_test.go#L280

@artelse I suggest you take further troubleshooting on the forum.
