### ISSUE TITLE
 Support configurable repoPath in GitInfo

### ISSUE THREAD

**Issue by willpatera** [gohugoio/hugo#3215]
## Overview

This is a request for an enhancement to [`GitInfo`](https://gohugo.io/extras/gitinfo/) that would enable one to use `GitInfo` for Hugo sites where the `content` directory is a `.git` submodule. 

## Use case / motivation

I have my `content` set up as a submodule for a hugo site so that I can version content independently from the logic of the website and/or theme. 

I would like to be able to utilize `GitInfo` functions to show when each page was revised, by who, and when. All of this logic is available thanks to @bep et al.'s work on [gitinfo](https://github.com/spf13/hugo/blob/master/hugolib/gitinfo.go) and [gitmap](https://github.com/bep/gitmap). But, currently `GitInfo` assumes a single git repo (as far as I understand) and does not yet accommodate submodules. 

Example file tree, where `hugo-website` is the main `.git` repo and `content` is a submodule:

```
/hugo_website
|--.git
|--.gitmodules
|-- content
|    `--.git
|-- themes
|--...etc (other files)
```

## Request
Here are two routes that come to mind:

(a) Automatic discovery - `GitInfo` checks to see if `content` is a `.git` repository and is specified as a `submodule` in `.gitmodules`. If these conditions are met, then `repoPath` is set to `contentRoot`

(b) User sets params - Allow users to set the `repoPath` for `GitInfo` via config options.

Would this be useful to others and/or an enhancement the core team would consider a worthwhile addition?

**Comment by willpatera** [comment]
@EddEdw I would be happy for someone to re-open this issue (and implement this functionality), but I do not have the power to do so myself. 

Based on the lack of comments/interest generated by my original issue, it does not seem like this feature will be implemented :tipping_hand_man:

**Comment by oskarrough** [comment]
A use-case for this feature would be outputting last commit date from a child theme in a git submodule. Does anyone know of a workaround?

**Comment by kaushalmodi** [comment]
@oskarrough You can use `getJSON` and GitHub (even Gitlab) API to get such info for any repo ([example][1] -- Search for `getJSON` in there).

For further discussion, please start a thread on https://discourse.gohugo.io/.

[1]: https://github.com/kaushalmodi/ox-hugo/blob/master/doc/layouts/_default/examples.html

**Comment by s8gv** [comment]
Hi I have a same issue. I need lastmodified timestamp and my content is another .git repo. 
I reached here through https://discourse.gohugo.io/t/gitinfo-for-content-in-separate-git-repository-submodule/5882


Please let me know if there is a workaround other than getJSON. Thanks.
