### ISSUE TITLE
Hugo embedded RSS Should use ".summary" in <description> tag, not ".content"

### ISSUE THREAD

**Issue by DarwinJS** [gohugoio/hugo#3218]
I am using a MailChimp RSS campaign to send a newsletter that shows my articles.

Mailchimp expects the RSS <description> tag is an article *Summary* - not the complete article.

(http://kb.mailchimp.com/merge-tags/rss-merge-tags?_ga=1.105151435.991503548.1486679578)

https://hugodocs.info/templates/rss explains that the embedded RSS puts Hugo's ".content" item in the <description> tag. (and that can be seen if you just pull <site>\index.xml

I believe the Hugo's ".summary" item should be there instead.

The work around is to create an rss.xml in my template with that one change.

That's why I was not getting any clicks - everyone gets the entire articles in the email newsletter!

**Comment by thiagomgd** [comment]
For what I know, this is a matter of configuration.  The RSS services that I know usually let you configure what behavior you want. Maybe adding a new config?

**Comment by DarwinJS** [comment]
@thiagomgd - I linked the MailChimp document - they allow some configuration, but they aren't setup to summarize for you.  They expect full body content would be in a tag `<content:encoded>`.

However, the larger issue would seem to be that the vast majority of RSS reading / interfacing systems expect summaries, not full articles in that field.

**Comment by Cj-Malone** [comment]
See my [PR](https://github.com/spf13/hugo/pull/3341) that adds `content:encoded` or @kropp's [PR](https://github.com/spf13/hugo/pull/3363) that adds a `rssSummary` config option. But @rdwatters doesn't seem enthusiastic about it..

I don't know what feed readers expect summaries, from my experience full content is usually rendered/utilised perfectly.

**Comment by briemarie** [comment]
Yes, I am having the same issue. Owler is not validating our blog feed because of all of the errors that are showing in the descriptions tag (all of the errors pertain to having html not plain text in the description). I would assume that the meta description would go in the rss feed description.
