### ISSUE TITLE
Add support for .tmpl file extension in template lookup order

### ISSUE THREAD

**Issue by moorereason** [gohugoio/hugo#3230]
Primarily driven by the upcoming custom output format feature (#2828).

Rationale:
- Can't assume that we're dealing with HTML-type formats any longer.
- Want a predictable filename for editors to do syntax highlighting of template actions (`{{ ... }}`).

Do we want to drive the potential lookup based upon the Output Format?  So, if we have a "JSON" Output Format, we would lookup:

* index.json
* index.json.tmpl

This would exclude `index.json.html`.  Lookup would essentially be:

* `{{ .Name }}.{{ .Format }}`
* `{{ .Name }}.{{ .Format }}.tmpl`

Original discussion: https://discuss.gohugo.io/t/custom-output-formats-feedback-wanted/5886/2

**Comment by bademux** [comment]
Hello,
"Can't assume that we're dealing with HTML-type formats any longer."
But we still assume a text output?
If not, then maybe it is the way to handle images?

Can I kindly ask for contributors vision of image processing?

Notes:
The only native image processing support: #3158

**Comment by bep** [comment]
>But we still assume a text output?

yes.

**Comment by IRus** [comment]
In Intellij Idea products `*.gohtml` is used for Go Templates

**Comment by IRus** [comment]
Btw, my current workaround is to have `*.gohtml` for every layout `*.html`:

```
├── layouts
│   ├── 404.gohtml
│   ├── 404.html
│   ├── home.gohtml
│   ├── home.html
```

and include `*.gohtml` from `*.html`:

**home.html**
```
{{ template "home.gohtml" . }}
```

**Comment by mwld** [comment]
Another workaround I’m currently using:

1. Include the [Custom Output Format](https://gohugo.io/templates/output-formats/#templates-for-your-output-formats) in the template filename (e.g. `single.html.html` for HTML output format)
1. Assign "*.html.html" as pattern for Go Template file types in the Jetbrains IDE.

Simple *.html files are still being assigned to the HTML file type that way.

**Comment by NiklasPor** [comment]
While writing a [prettier plugin to fix go template](https://github.com/NiklasPor/prettier-plugin-go-template) support I stumbled upon this. It would be really nice for formatters, if GoHugo would support `.tmpl`.

**Comment by WardBenjamin** [comment]
+1, this would simplify usage with IntelliJ IDEA-based editors.

**Comment by justrhysism** [comment]
I'm stunned that the template extension isn't configurable after all this time. Personally, I _really_ don't like naming files with extensions they _aren't_. The templates _aren't_ HTML files `*.html`, they are _Go Templates_ `*.gohtml`.

It obviously isn't a trivial change—what will it take to get this done?

**Comment by davidsneighbour** [comment]
> It obviously isn't a trivial change—what will it take to get this done?

An unpaid go programmer with time at his hand. Or a sponsor who would pay for this feature. 

And... to be honest, it's a larger topic. Because I would assume that it might even make sense to add some form of configuration parameter or variable that enables us to manually set the extension or content type. By the way in IntelliJ based editors it's quite easy to re-assign HTML files to gotemplates (even on a per project base).

**Comment by moorereason** [comment]
> An unpaid go programmer with time at his hand.

I'll claim the "unpaid" title, but I don't have time to be much of a programmer.  😄

I started working on this issue in October but got sidetracked (I'm the ADD poster boy) cleaning up other things in the `output` package (see #7824 and #7984).  Hopefully, I'll be able to finish it up this month to at least get us a PR to review.

**Comment by thobson** [comment]
For anyone using an IntelliJ derivative e.g. Webstorm there is the override file type option which allows you to mark specific .html files as go templates (see screen shots). Not ideal but better than nothing

<img width="401" alt="Screenshot 2021-12-29 at 11 30 20" src="https://user-images.githubusercontent.com/208345/147658097-945ad46a-a8b3-49c3-a6c8-297aa2e92cbe.png">

<img width="492" alt="Screenshot 2021-12-29 at 11 30 29" src="https://user-images.githubusercontent.com/208345/147658100-4bc60e27-5120-42fa-bc65-9ab6142c102e.png">

**Comment by Kovah** [comment]
Is this ever going to happen? 😕

**Comment by nk9** [comment]
I'm interested in this from the syntax perspective. It should be possible to create a great syntax for Go template files, but right now the fact that everything ends in the generic `.html` means you have to manually set the language on either a file or project level. User experience would be much improved if it were automatic.
