### ISSUE TITLE
plainify should remove <style> and <script> sections

### ISSUE THREAD

**Issue by liwenyip** [gohugoio/hugo#3235]
`plainify` doesn't strip contents of `<style>` tags

See source of https://www.liwen.id.au/barbershop-charts/, line 34

Where 
```
<meta property="og:description" content="{{ .Content | plainify | htmlEscape | truncate 200 }}">
```

is resulting in

```
<meta property="og:description" content="Here are some easy-to-follow flowcharts to help you remember the words to popular barbershop songs.
  figure { border: 1px solid lightgrey; } 
(Click to zoom)
Hello Mary Lou .gallery .img4 …">
```

`plainify` should probably strip out the contents of any non-displaying tags e.g. `<style>`, `<script>`, (any others?)

**Comment by bep** [comment]
Weird.

https://github.com/spf13/hugo/blob/86e8dd62f0b1c8adf14e9369b089d209317aaf2d/helpers/content.go#L151

**Comment by bep** [comment]
I think this is an issue where the tags gets escaped before they get to `plainify`.

**Comment by liwenyip** [comment]
Did another test to confirm:

```
{{ plainify "One <span class='red'>red</span> apple. <style>.red {color:red;}</style>" }}
```
results in
```
One red apple. .red {color:red;}
```

**Comment by bep** [comment]
Then I don't see how we can do anything about this ...?

**Comment by liwenyip** [comment]
Having looked at how the `StripHTML` function is implemented - I guess not.

If I understand correctly (I've never programmed in Go before),  `StripHTML` walks through the string one char at a time, so there is no way for it to tell what type of tag it has encountered. I'm guessing it's done this way for speed? (Faster than using regexp?)

I have a workaround:
```
{{ "One <span class='red'>red</span> apple. <style>.red {color:red;}</style>" 
    | replaceRE "(<style>.+?</style>|<script>.+?</script>)" "" | plainify }}
```

I think the [docs](https://github.com/spf13/hugo/blob/f1b1df50589530a6c1dff7c8d2681af5dcd5ebdf/docs/content/templates/functions.md) for `plainify` should state that it doesn't remove the innerHTML of any tags particularly <style> and <script>. Should I make the change and submit a PR?

**Comment by bep** [comment]
The main motivation is speed, of course, but in my last reply, I did not understand the real problem. Now I do. No, let us keep this open and fix it in code (in a fast way). 

We should have a list of keywords that we skip completely. Let us start with `style` and `script`.

**Comment by liwenyip** [comment]
> Let us start with `style` and `script`.
Yes I think these are the ones most likely to be a problem.

http://nadeausoftware.com/articles/2007/09/php_tip_how_strip_html_tags_web_page suggests also stripping `head`, `object`, `embed`, `applet`, `noframes`, `noscript`, `noembed`, but they are all either deprecated, actually contain plain text, or don't normally contain any innerHTML.

**Comment by liwenyip** [comment]
By the way I have solved my original problem by using `<meta property="og:description" content="{{ .Summary }}">` which is obviously a much better solution.

But in the process, I discovered some more weird behaviour:
# Example 1 - expected behaviour
Hugo: 
`<meta property="og:description" content="{{ .Content | plainify | truncate 150 }}">` 

HTML (newlines and whitespace removed): 
`<meta property="og:description" content="Here are some easy-to-follow flowcharts to help you remember the words to popular barbershop songs. figure { border: 1px solid lightgrey; }  (Click to zoom) Hello Mary Lou .gallery .img2 …">`

(plainify doesn't remove contents of `<style></style>`, as already established)

# Example 2 - weird...
Hugo:
`<meta property="og:description" content="{{ .Content | truncate 200 }}">`

HTML:
`<meta property="og:description" content="Here are some easy-to-follow flowcharts to help you remember the words to popular barbershop songs. (Click to zoom) Hello Mary Lou …">`

( `.Content` returns plain text, and even strips contents of `<style></style>` - **is it supposed to do that?**)

# Example 3 - expected behaviour

Hugo:
`<meta property="og:description" content="">{{ .Content | truncate 200 }}`

HTML:
`<meta property="og:description" content=""><p>Here are some easy-to-follow flowcharts to help you remember the words to popular barbershop songs.</p><p></p><style>figure {    border: 1px solid lightgrey;}</style><p>(Click to zoom)</p><h2 id="hello-mary-lou">Hello Mary Lou …</h2>`

So it looks like `.Content` returns plain text only if used inside a HTML tag...

**Comment by bep** [comment]
As you pass the `.Content` into `truncate` I'm not following your argumentation. Not one of your examples show output from `.Content`.

**Comment by liwenyip** [comment]
Sorry, I'll raise a separate issue for this. (I'm still figuring out how Github works, apologies)

**Comment by Astorsoft** [comment]
Hi, any update on this issue? As a typical use case, I'm currently designing a custom RSS output which contains the article's content going through plainify. It now contains the whole podcast player javascript in plain text, which is quite ugly. I've tried the replaceRE but it's not working, I'm guessing because my <script> tag is multiline?

If you want an example of what I'm talking about here is the code

`<description>
              {{ .Content | plainify | htmlUnescape | safeHTML }}
            </description>`

(if I don't htmlUnescape and safeHTML after plainify, all my quotes are htmlencoded)

The output being something like:

`  <description>
               French gibberish, which is the actual content of the article, and then the content of the script tag as you can see below:
 window.podigee = { "options": { "theme": "default", }, "extensions": { "ChapterMarks": { "disabled": false }, "EpisodeInfo": {}, "Playlist": { "disabled": true }, "Transcript": { "disabled": true } }, "podcast": { "feed": "https:\/\/media.blubrry.com\/comptoirsecu\/s\/podcast.comptoirsecu.fr\/CSEC.SECHebdo.2017-05-30.mp3" }, "episode": { "media": { "mp3": "https:\/\/media.blubrry.com\/comptoirsecu\/s\/podcast.comptoirsecu.fr\/CSEC.SECHebdo.2017-05-30.mp3" }, "coverUrl": "http:\/\/localhost:1313\/\/images\/covers\/2017-05-30.jpg", "title": "[SECHebdo] Mai 2017 - 5", "subtitle": "Cloak \x26 Dagger, ACYMA, SAMBACry, BSoD Win8, 2FA \x26 Cloud, Pacemakers, Iris \x26 CCC, Inboxen, etc.", "description": "SECHebdo est une revue de l\x27actualité cybersécurité réalisé en live sur Youtube, généralement le mardi soir.", "chaptermarks": [ { "start": "00:01:30", "title": "Titre"}, ], } }   Notre discord : https://discord.comptoirsecu.fr`

**Comment by Astorsoft** [comment]
Ok, found a solution in https://discourse.gohugo.io/t/replacere-not-working-for-me-solved/5103/6, you just have to add (?m) (?s:YOUR_REGEXP)

<description>
                {{chomp "<![CDATA[\n"}}{{ htmlUnescape .Content | replaceRE "(?m)(?s:<script.+?</script>)" ""| plainify }}{{chomp "]]>\n"}}
            </description>

**Comment by uncompiled** [comment]
If no one has started working on this, I would be interested in tackling this issue.

**Comment by bep** [comment]
@uncompiled that would be great; please don't hesitate to ask.

**Comment by prannayk** [comment]
Is anyone working on this? I would like to jump on this

**Comment by moorereason** [comment]
@prannayk, go for it.

**Comment by martignoni** [comment]
I've used this workaround to generate my `index.json`:
`.Content |  markdownify | safeHTML | replaceRE "(?m)(?s:<(style|script)[^>]*>[^<]*<\\/(style|script)>)" "" | plainify`

**Comment by jmooring** [comment]
This was fixed with https://github.com/gohugoio/hugo/pull/9923 in v0.100.0.
