### ISSUE TITLE
Hugo server doesn't watch the theme's i18n directory if the base i18n directory doesn't exist

### ISSUE THREAD

**Issue by rayjolt** [gohugoio/hugo#3258]
I have a Hugo site with the following basic structure:

```
.
├── archetypes
├── content
├── layouts
├── static
└── themes
    └── mytheme
        ├── archetypes
        ├── i18n
        ├── layouts
        └── static
```

When using Hugo's server with this configuration, Hugo doesn't watch the theme's i18n directory. Editing `themes/mytheme/i18n/en.yaml` doesn't trigger a reload in the browser, but editing a layout template such as `themes/mytheme/layouts/index.html` triggers a reload, complete with the updated translations.

In this configuration, `hugo server -t mytheme --verbose` gives the following warnings in the output:

```
WARN 2017/04/02 13:26:40 Skip i18nDir: lstat /path/to/mysite/i18n: no such file or directory
Watching for changes in /path/to/mysite/{data,content,layouts,static,themes}
WARN 2017/04/02 13:26:40 Skip i18nDir: lstat /path/to/mysite/i18n: no such file or directory
```

This can be fixed by adding an `i18n` directory in the base site directory, producing a tree like this:

```
.
├── archetypes
├── content
├── i18n
├── layouts
├── static
└── themes
    └── mytheme
        ├── archetypes
        ├── i18n
        ├── layouts
        └── static
```

With this directory structure, changes in `themes/mytheme/i18n/en.yaml` cause the browser to refresh the page.

I think that Hugo should watch the `themes/mytheme/i18n` directory even if the base site doesn't have a `i18n` directory.

**Comment by bep** [comment]
@rayjolt I have:

* Checked the code
* Tested this with my own theme

And I cannot reproduce this and the source code looks correct. Is till still an issue for with the latest Hugo?

**Comment by rayjolt** [comment]
I have just tested it with Hugo 24.1, and it is now working correctly.

I notice I didn't mention my Hugo version when filing this bug report - I believe it was 0.19. I'm not sure which one it was, but one of the releases since then must have fixed the problem.
