### ISSUE TITLE
Hugo 0.11 can't see config file with non-default name

### ISSUE THREAD

**Issue by mdwhatcott** [gohugoio/hugo#328]
I've separated my sites into a few separate repositories. The repository in charge of rendering and publishing my sites has all my config files, named after the site they configure. These config files point to the other repositories which contain the markup/templates and content. Up until now (0.11) I've used the --config flag to point to the correct config file but it's not working anymore:

```
$ hugo_0.11 server --config=my-site.yaml
ERROR: 2014/06/09 Config not found... using only defaults, stuff may not work
...
```

Renaming the config file to `config.yaml` makes it work again but this appears to be a breaking change from 0.10.

**Comment by zachdyer** [comment]
When I use `hugo server` it gives me the error `Config not found... using only defaults, stuff may not work.` I'm using version 0.13. Do you need anymore information about this?

**Comment by spf13** [comment]
You need to run hugo in a folder with a config.{yaml, toml, json} file

**Comment by zachdyer** [comment]
I did but I updated my comment with the second error. Did you see that?

**Comment by zachdyer** [comment]
Weird hugo is looking into a path for hugo that isn't in my path variable. Now I'm just confused. Any idea's on how to troubleshoot?

**Comment by dunn** [comment]
are you missing the `static` directory in your project?

**Comment by zachdyer** [comment]
No it's there. But why is hugo using the wrong version? How do I tell Hugo to use the current version. I've tried updating my environmental variable.

**Comment by zachdyer** [comment]
I updated the old path with the new Hugo binary 0.13 and now I get a different error when I use `hugo server Failed to read data from desktop.ini/desktop.ini: Data not supported for extension 'ini'`

**Comment by bep** [comment]
Inside /content, probably.

**Comment by zachdyer** [comment]
Aha I found it. It was hidden from me. This file was created by Google drive sync. @spf13 What should I do about this?
