### ISSUE TITLE
Publish to remote destination

### ISSUE THREAD

**Issue by finferflu** [gohugoio/hugo#3281]
Since I'm publishing to S3, I think it would be much easier if the `--destination` flag supported a remote location, rather than having to manually upload every time. I hope this will be considered as a future enhancement. Thanks!

**Comment by talves** [comment]
Although this would make publishing nice, there are plenty of solutions for publishing to remote services.

I currently use HUGO to build a static site with react components that gets published to Firebase Hosting. The Firebase CLI in node already handles the publishing for me, so I would not use it in HUGO.

I am also thinking you do not want to build directly to your remote until the full build is complete in the case there is an error. Of course, the argument can be made that an error can exist in any transfer, but adds another layer of failure.

[OPINION]
Please do not read this as being critical, just wondering if I am missing something. Why would we not just use a task runner on top of the HUGO project to publish to our remote destinations? I am not sure this is going to be a plus in the long run UNLESS it was created with a plugin system to be able to maintain those publishing providers separately.

**Comment by finferflu** [comment]
@talves, thanks for the feedback. 

I suppose the case in point is AWS Lambda, at least in my case. Rather than having the files created locally and then synced to S3, I think it would be more elegant and perhaps quicker to have Hugo handle the S3 upload.

**Comment by bogem** [comment]
I agree with @talves, although it's in [roadmap](https://gohugo.io/meta/roadmap/).
Deployment tool should be separate from hugo. I think, it's a bit overhead for hugo and considering how many deployment tools there are (for AWS, heroku, firebase, scp, git and etc).

As alternative it could be added an option in config like this:
```toml
deploy = "git push origin master"
```
And if you want to deploy you should execute `hugo --deploy` and at the end of rendering the command in `deploy` will be executed. IMHO it's the simplest solution, but you must have appropriate CLI installed.

**Comment by bep** [comment]
In isolation, this issue isn't very interesting. To get some speed benefits from this, we would have to get a head start, and that isn't really happening with Hugo. So the real speed benefits will be in "only transfer whats changed", and existing S3 tools does this very well (https://github.com/bep/s3deploy is one).

But Hugo is set up with virtual file systems in both end (source, destination), which we use to great benefit in the server mode (mem-mapped files) ... And it would be cool, in the future, to maybe extend this to a "remote streaming update" kind of live update. Suddenly the static isn't that static anymore.
