### ISSUE TITLE
AsciiDoc header metadata

### ISSUE THREAD

**Issue by dobesv** [gohugoio/hugo#3283]
AsciiDoc has it's own kind of metadata format, as described here:

http://www.methods.co.nz/asciidoc/userguide.html#X95

It would be pretty cool if gohugo would support the "native" metadata format of AsciiDoc as an alternative to the YAML/TOML/JSON options currently in use.  This would make the content "pure AsciiDoc".

**Comment by rpwatkins** [comment]
+1
