### ISSUE TITLE
Add indicator to paginator-generated pages

### ISSUE THREAD

**Issue by adiabatic** [gohugoio/hugo#3287]
Previously mentioned on <https://discuss.gohugo.io/t/detecting-whether-the-current-page-is-blog-page-n/6047/>. In short, it'd be nice if paginator-generated pages could be distinguished somehow from other types of pages without generating another paginator.

**Comment by bep** [comment]
>without generating another paginator.

Just a note: You will never create _another_ paginator (there will be at most one), but you may create one that you didn't mean to create.

**Comment by sangaline** [comment]
If it's not too late, I'll chime in and add that I think this would be really useful. One major use-case is adding rel canonical tags to pages. This is currently difficult to do because it isn't easy to access the paginator from a header partial.
