### ISSUE TITLE
Add "dotted" map access as second try in the index func

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3289]
My proposal to fix the index func in the Go std lib was rejected, so we are stuck with maintaining a patched version.

I'm working on some Hugo docs, and have a shortcode that creates HTML tables from a JSON data file:

```
{{< datatable "media" "types" "Type" "Suffix" >}}
```

I could probably have done the splitting in the template, but right now I have accepted that I have two levels, and my data list is available at `.Site.Data.media.types`.  This logic would break if it suddenly was `.Site.Data.hugo.media.types`.

It would be nice if I could do:

```
{{ $mylist := index .Site.Data "media.types" }}
```

I.e. if the index func 

1. First did a map lookup with "media.types"
2. If none found and the string contains a ".", split it and do a nested lookup

/cc @moorereason

**Comment by k3v** [comment]
Hello, is this issue up for grabs? I'm interested in taking a look.

**Comment by blackmichael** [comment]
@bep I'd like to work on this, and I've got a decent amount of Go experience but I'm not entirely familiar with the codebase. Where should I start with this?

**Comment by bep** [comment]
https://github.com/gohugoio/hugo/blob/master/tpl/collections/index.go#L31

**Comment by blackmichael** [comment]
@bep https://github.com/gohugoio/hugo/pull/3974

**Comment by yathuganesh** [comment]
@bep #3974
reminder pull request

**Comment by mknycha** [comment]
I'd like to work on this one, is it still open for a contribution? I have noticed that there was a PR already, but it is not clear to me why it wasn't merged.

**Comment by blackmichael** [comment]
@mknycha looks like I never signed the Contributor License Agreement, oops. Not sure if there was any other reason

**Comment by bep** [comment]
@mknycha I'm sorry that I missed out on this, but where is this PR? I tried to search for it now.

**Comment by blackmichael** [comment]
@bep https://github.com/gohugoio/hugo/pull/3974

**Comment by bep** [comment]
OK, looking at this issue now, and the test cases in the PR from @blackmichael, I realize I didn't fully understand the API of the index func when I created this issue:

See the test cases in #6473 -- which passes with the current implementation.

The thing I've missed was that the index func takes multiple indices (which can be a combination of map an slice indices). So in my example above you can do:

```
{{ $mylist := index .Site.Data "media" "types" }}
```

Or even:

```
{{ $mylist := index .Site.Data "media" "types" 0 }}
```

/cc @blackmichael @regisphilibert @moorereason with the above I'm hesitant to introduce a new "dotted syntax" which would be potentially ambiguous.

**Comment by regisphilibert** [comment]
Damn, always a discovery...
