### ISSUE TITLE
YAML front matter parsing errors kill hugo in server mode

### ISSUE THREAD

**Issue by arsatiki** [gohugoio/hugo#33]
I've mentioned this already in comments of #30, but it might make sense to make an issue out of it.

If I have poor YAML in my front matter, such as no quotes around a string that contains colons, e.g.

```
title: This thing: crashes
```

then servermode hugo will crash in this fashion:

> Invalid YAML in /Users/arasinen/src/postposterous/content/bjing/2010-04-26-hei-maailma.md 
> Error parsing page meta data: YAML error: mapping values are not allowed in this context

My expected result is that the server would not actually crash, but rather print out an error message to stderr. A crashing server breaks the workflow in a non-intuitive way.

It would be nice to have if the error message were printed in red in supporting terminals, but that is not necessary.

Also, it would be nice to have something generated even when metadata parsing fails. Perhaps there should be a variable that says parsing fails. Then template builders can add desired warnings to output themselves.

**Comment by wildskyf** [comment]
Btw, if you want to use colons in your title, you should make it enclosed in quotation marks, such as 
```
title: "This thing: enclosed"
```
