### ISSUE TITLE
Add `float` function to parse string to floating point value

### ISSUE THREAD

**Issue by jpap** [gohugoio/hugo#3307]
Please add a `float` function so that we can convert a string into a floating point number, analogous to the `int` function for integers.

This will allow us to pass named floating point arguments from a shortcode.  

For my use-case, this is to pass a non-integer "aspect ratio" value.  My current workaround is to supply this as a rational two-integer tuple and to perform the division in the template, but is only an approximation when the value is irrational.

**Comment by mimattr** [comment]
Agreed, the addition of a `float` function would be very useful and also allow a single `string` (frontmatter) to contain multiple `float` values using a separator for later expansion/manipulation (template).

Is something similar already on the roadmap?

Many thanks in advance.

**Comment by x3ro** [comment]
Hi from a Hacktoberfestler 👋 I'd like to give implementing this a try!

**Comment by bep** [comment]
@x3ro great; it should live in the `tpl/cast` package; see `ToInt` for inspiration.

/cc @moorereason
