### ISSUE TITLE
Skip docutils tests when no docutils

### ISSUE THREAD

**Issue by hildensia** [gohugoio/hugo#3313]
I just recognized i need to have docutils installed in order to run the tests. Maybe this should be noted somewhere in the documentation.

**Comment by digitalcraftsman** [comment]
@rdwatters was this already covered in your rewrite or in an issue of the hugo-docs-concept repo?

**Comment by bep** [comment]
We should skip those tests if no docutils available. @hildensia  Do you remember what test failed?

**Comment by hildensia** [comment]
No, sorry I can't recall.

**Comment by rdwatters** [comment]
@digitalcraftsman I don't believe so, but I will gladly add. Thanks.

**Comment by bep** [comment]
@rdwatters please don't. This is not a documentation issue.
