### ISSUE TITLE
.deb warnings (for the 64bit system)

### ISSUE THREAD

**Issue by bracuphoth** [gohugoio/hugo#3316]
E: hugo: unstripped-binary-or-object usr/bin/hugo
E: hugo: statically-linked-binary usr/bin/hugo
E: hugo: changelog-file-missing-in-native-package
E: hugo: no-copyright-file
E: hugo: description-too-short ?
E: hugo: extended-description-is-empty
W: hugo: binary-without-manpage usr/bin/hugo

Lintian finished with exit status 1

**Comment by bep** [comment]
I suspect I've seen something similar before ... And I don't think we're going to do anything about it. We have plenty of Linux alternatives. @anthonyfok

**Comment by bep** [comment]
Is this still an issue?

**Comment by anthonyfok** [comment]
Hi!  I just saw this issue yesterday.

For some of the Debian Lintian warnings/errors found in the goreleaser-generated .deb used for release require changes to be made to goreleaser itself, and a feature request was sent to goreleaser's author in goreleaser/goreleaser#314 (July 2017), and the feature will hopefully be added in a future goreleaser v1.0.0.
