### ISSUE TITLE
Add possibility to specify asciidoctor --require argument

### ISSUE THREAD

**Issue by miltador** [gohugoio/hugo#3330]
From `asciidoctor` [manual](http://asciidoctor.org/docs/user-manual/#rendering-control):

> -r, --require=LIBRARY
> 
>Require the specified library before executing the processor, using the standard Ruby require. This option may be specified more than once.
> 

It is basically the way to specify [extensions for `asciidoctor` to use](https://github.com/asciidoctor/asciidoctor-extensions-lab#using-an-extension) during rendering and it accepts paths to `.rb` files.

**Comment by miltador** [comment]
I would like to implement it but I wonder what would be the best way to implement it?
I see it as a config parameter of array of strings, each item is a path to extension.

**Comment by bep** [comment]
Isn't there a global way to configure this for Asciidoctor? Via OS environment or something?

**Comment by miltador** [comment]
It is the only way to do it for now.
