### ISSUE TITLE
twitter shortcode: better error message on missing tweet

### ISSUE THREAD

**Issue by client9** [gohugoio/hugo#3332]
Hello! I'm on a linux version of:

```
hugo version
Hugo Static Site Generator v0.21-DEV linux/amd64 BuildDate: 2017-04-11T21:27:32Z
```

Started getting some strange errors from the twitter shortcode  `{{< tweet 756641193958772736 >}}`

```
ERROR 2017/04/12 16:05:47 Cannot read json from resource 
https://api.twitter.com/1/statuses/oembed.json?id=756641193958772736
 with error message invalid character 'x' looking for beginning of value
```

Investigating, turns out the tweet was deleted, and the json response was

```json
{"errors":[{"message":"Sorry, that page does not exist","code":34}]}
```
The output from hugo isn't wrong per se, but compared to some the other message it seems lacking in detail and unfriendly (where in markdown/document is the problem? what is the error?).  

I'll attempt to take a look at the code later, but if anyone is more familiar with the twitter API, go for it.

thanks for a great projects,

regards,

n

**Comment by jmpesp** [comment]
This may have been fixed as part of 08c0de5cc37cd4e512268b8f72ec5a6c68cd5754
