### ISSUE TITLE
Render shortcodes in their order of appearance

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3359]
See https://discuss.gohugo.io/t/need-help-with-broken-footnote-shortcode/6213/9

* I think shortcodes where processed in order at one point, before we started to track the shortcodes in a map (the keys in the map have a natural order, but the map itself does not)
* But then again, at one point we tried to process the shortcodes in parallel to speed it up, so giving some guarantee in this department will quickly shoot ourselves in the foot, even if it would be fairly simple to do at the moment.
* We could, however, add an `Index` attribute that counts from 0,1 ... and would represent the shortcode's placement in the content file.

**Comment by fj** [comment]
I'd find this valuable. I'd like to be able to replicate the ability to have Hugo tell me what instance of the shortcode this is. That would be valuable for having distinct class names on a per-shortcode-instance basis.

For example, I use shortcodes in Jekyll to get the ability to have margin notes and sidenotes (see https://edwardtufte.github.io/tufte-css/). This requires that I know the index of each call to the shortcodes, which I handle in Jekyll by incrementing an internal variable.

However, Hugo's shortcodes processing is stateless. So either I'd need some way of doing this myself, or I'd need the Index feature, which I think would be quite valuable.
