### ISSUE TITLE
Support layouts per site/language

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3360]
See http://stackoverflow.com/questions/43149074/jekyll-or-hugo-theme-with-multilanguage-support

Hugo has already a good story for multiple languages, but it could fairly easily be made even more powerful by allowing template overrides per site/language.

Doing large portions of localisation via i18n files can be cumbersome, so to be able to create language-specific layout files/partials/shortcodes would be great.

A simple sample would be:

```
layouts
├── _default
│   ├── baseof.html
│   ├── list.html
│   └── single.html
├── _fr
│   ├── _default
│   │   └── list.html
│   └── index.html
└── index.html
```

In the imaginary site above we have a base template set that is used for all sites/languages, but then we override some of the templates for the French language (`fr`). This would also work for themes.

I have prefixed the language with "_" to avoid (hopefully) any section collisions.

**Comment by ngsctt** [comment]
I've been wishing for exactly this as I've been reworking my site into Hugo. It'd be especially helpful for laying pages out according to different typographic conventions (I'm doing English/Japanese, and CVs are very different across the two).

I thought though, that the simpler way might be to use something like:
```
layouts
├── _default
│   ├── baseof.html
│   ├── list.html
│   ├── list.ja.html
│   └── single.html
│   └── single.ja.html
└── index.html
└── index.ja.html
```
Using `filename.ja.html` or `filename-ja.html`, etc. That way, the translations sit side-by-side with each other in the same folder, it matches the translated content system, and presumably you could just double the template search paths (eg. from https://gohugo.io/templates/content/#single-page), like so:

- /layouts/`TYPE`/`LAYOUT`.`LANG`.html
- /layouts/`TYPE`/`LAYOUT`.html
- /layouts/`SECTION`/`LAYOUT`.`LANG`.html
- /layouts/`SECTION`/`LAYOUT`.html
- /layouts/`TYPE`/single.`LANG`.html
- /layouts/`TYPE`/single.html
- /layouts/`SECTION`/single.`LANG`.html
- /layouts/`SECTION`/single.html
- /layouts/_default/single.`LANG`.html
- /layouts/_default/single.html
- /themes/`THEME`/layouts/`TYPE`/`LAYOUT`.`LANG`.html
- /themes/`THEME`/layouts/`TYPE`/`LAYOUT`.html
- /themes/`THEME`/layouts/`SECTION`/`LAYOUT`.`LANG`.html
- /themes/`THEME`/layouts/`SECTION`/`LAYOUT`.html
- /themes/`THEME`/layouts/`TYPE`/single.`LANG`.html
- /themes/`THEME`/layouts/`TYPE`/single.html
- /themes/`THEME`/layouts/`SECTION`/single.`LANG`.html
- /themes/`THEME`/layouts/`SECTION`/single.html
- /themes/`THEME`/layouts/_default/single.`LANG`.html
- /themes/`THEME`/layouts/_default/single.html

Additionally, this shouldn't really disrupt any pre-existing sites, and be relatively easy to add in I think.

**Comment by bep** [comment]
@ngsctt I agree, that is much simpler than what I suggested.
