### ISSUE TITLE
trim should have its arguments switched

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3362]
So 

```
{{ trim "++Batman--" "+-" }}
```

Could become

```
{{ "++Batman--" | trim "+-" }}
```

Not something I'm too keen on fixing, but add an issue as a reminder...

/cc @moorereason

**Comment by moorereason** [comment]
I agree (also affects `hasPrefix`...maybe others).  If we're going to fix/break these, we should do it sooner rather than later.

**Comment by bep** [comment]
Hmm ... Sounds like work.
