### ISSUE TITLE
Update docs vs RSS layouts

### ISSUE THREAD

**Issue by andytson** [gohugoio/hugo#3364]
`/layouts/rss.xml` is only included in the documentation for the Main rss feed https://github.com/spf13/hugo/blob/master/docs/content/templates/rss.md#main-rss

If overriding this file, it overrides Section/Taxonomy/Taxonomy Term RSS too, effectively the same as what `/layouts/_default/rss.xml` should be doing.

As it is, I'm unable to change the home page's RSS feed without also changing these others.

**Comment by bep** [comment]
I'm fairly confident that is not true. 

I spent considerable time and energy to mimic the old behaviour for RSS templates when I recently rewrote the template selection logic.

```
	layoutsRSSHome         = `NAME.SUFFIX _default/NAME.SUFFIX _internal/_default/rss.xml`
	layoutsRSSSection      = `section/SECTION.NAME.SUFFIX _default/NAME.SUFFIX NAME.SUFFIX _internal/_default/rss.xml`
	layoutsRSSTaxonomy     = `taxonomy/SECTION.NAME.SUFFIX _default/NAME.SUFFIX NAME.SUFFIX _internal/_default/rss.xml`
	layoutsRSSTaxonomyTerm = `taxonomy/SECTION.terms.NAME.SUFFIX _default/NAME.SUFFIX NAME.SUFFIX _internal/_default/rss.xml`

```

And while this logic is slightly different from that of the other page kinds, I chose to keep it this way to avoid breaking stuff. 

But you have plenty of ways to secure specific template for say both home page and the taxonomies.

The above is taken from the code and represents the actual logic implemented. 

NAME: The rss output format name, default "rss"
SUFFIX: Default "xml"
SECTION: The section name, taxonomy term name, taxonomy name

If you find that the above is accurate, please close this issue.

**Comment by andytson** [comment]
I've tested it against each type of RSS in version 0.20.2, and the layouts/rss.xml affected each.

I can see from that selection logic this appears to be true with each including NAME.SUFFIX

instead perhaps it should be:

```
	layoutsRSSHome         = `NAME.SUFFIX _default/NAME.SUFFIX _internal/_default/rss.xml`
	layoutsRSSSection      = `section/SECTION.NAME.SUFFIX _default/NAME.SUFFIX _internal/_default/rss.xml`
	layoutsRSSTaxonomy     = `taxonomy/SECTION.NAME.SUFFIX _default/NAME.SUFFIX _internal/_default/rss.xml`
	layoutsRSSTaxonomyTerm = `taxonomy/SECTION.terms.NAME.SUFFIX _default/NAME.SUFFIX _internal/_default/rss.xml`
```

**Comment by andytson** [comment]
or if the original behaviour did this as well, instead the documentation could be updated to reflect this.
