### ISSUE TITLE
Consider empty strings in Param() as "not found"

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3366]
I'm not totally sure about this, but @budparr has a theme where he in front matter (for archetype reasons) have:

```
- featured_image: ""
```

And when doing 

```
{{ .Param "featured_image" }}
```

You will not get the desired effect of getting the image defined in site config. May be something to think about, but we should maybe fix archetypes to allow comments. Keep this as a reminder for a while ...

**Comment by moorereason** [comment]
My initial reaction is to leave `Param` the way it is now.

What's the expected behavior in Bud's case?  Why can't we use `{{ with .Param "featured_image" }}`?

**Comment by rdwatters** [comment]
> What's the expected behavior in Bud's case?

I was under the impression that it's sort of the equivalent of the following [from the docs](https://gohugo.io/templates/variables/#param-method):

`{{ .Params.featured_image | default .Site.Params.featured_image }}`

**Comment by bep** [comment]
@rdwatters is correct; his construction would work with less confusion in this case, but then again, having empty params scattered around seems like a messy ... mess, too, so.

**Comment by budparr** [comment]
It's true that the default only works when the field is gone completely, but it's inevitable that those empty params are going to be there when using an archetype.

**Comment by bep** [comment]
> but it's inevitable that those empty params are going to be there when using an archetype.

It's not **inevitable**. You could just ... delete it, but I get your point.

@fj may have some weight on this, as he reworked these methods some time ago.

**Comment by budparr** [comment]
Not to be argumentative, but the way I set up my sites (and the way I think others will be too in many cases) is to set up archetypes to be clues to an editor like forestry.io as to what fields to show in their interface. So, having those "fields" there, empty or no, is important. Every page needs to have a consistent set of fields whether or not any given field is being used.

**Comment by rdwatters** [comment]
> So, having those "fields" there, empty or no, is important. Every page needs to have a consistent set of fields whether or not any given field is being used.

Agreed. I find I always put the empty string for the value since the generator, if my memory serves, will otherwise put a `nil` value.

**Comment by bep** [comment]
A cleaner solution may be to not put empty strings into the params map when we read the front matter.

**Comment by rdwatters** [comment]
How crazy does it sound to beef up the `default` function instead since it's a more intuitive syntax and also used in other templating languages? 

For example, allowing just a `default` declaration (i.e., without a passed value) to point to the respective  `.Params` in config?

**Comment by moorereason** [comment]
`{{ .Params.featured_image | default .Site.Params.featured_image }}` should work as expected when defined but empty.  @budparr, is this your use case?

@bep, if we don't put the keys in the map, will `.Params.featured_image` give an index error?

Having empty strings in the Params map is fine with me.  Can we detect the difference between `key: ` and `key: ""` (`nil` vs `""`).  If I put `key: ""` in my front matter, I would expect to find it in the Params map as an empty string.

**Comment by budparr** [comment]
@moorereason Yes. I just tested that and it works.

**Comment by moorereason** [comment]
@bep, I think we can close this issue.  The solution is to use

```
featured_image:
```
instead of
```
featured_image: ""
```
In that case, the `{{ .Params.featured_image | default .Site.Params.featured_image }}` construct works as expected.

**Comment by bep** [comment]
>In that case, the {{ .Params.featured_image | default .Site.Params.featured_image }} construct works as expected.

Not sure how that applies to this particular issue?

**Comment by jmooring** [comment]
I would like to close this issue. The `.Param` method on `.Page` was designed to return the value associated with a given key, regardless of whether the value is truthy or falsy.

To ignore falsy values, use this construct instead:

```
{{ or .Params.foo site.Params.foo }}
```

I recently updated <https://gohugo.io/functions/param/>, including the example above.

**Comment by bep** [comment]
>I would like to close this issue. The .Param method on .Page was designed to return the value associated with a given key, regardless of whether the value is truthy or falsy.

No, the `.Param` was designed to return the value in Page front matter for a given key if set, else fall back to the `site.Params` value.

**Comment by jmooring** [comment]
I'm not sure where  the disagreement is. Please let me know if the updated documentation is incorrect:
< https://gohugo.io/functions/param/>
