### ISSUE TITLE
Docs say rssLimit of 15, but RSS not limited at all

### ISSUE THREAD

**Issue by andytson** [gohugoio/hugo#3370]
In Hugo v0.20.2, the full set of pages inside the main/section/taxonomy/term are output in the RSS feed, but the documentation says there is a limit of 15.

Setting an rssLimit myself, it limits the set of pages.

**Comment by andytson** [comment]
it looks like the rssLimit was set to unlimited last month https://github.com/spf13/hugo/commit/fe41bd61bb21fa17a7e80ac8ee804fe010193e7e

**Comment by rdwatters** [comment]
@moorereason FTR, this is already taken care of in the new docs: 

https://hugodocs.info/templates/rss/#configuring-rss

**Comment by andytson-inviqa** [comment]
Is there any reason why that's not in the master branch? https://github.com/spf13/hugo/blob/master/docs/content/templates/rss.md#configuring-rss

**Comment by digitalcraftsman** [comment]
The docs moved into a separate repository. I'll close this issue in favor of https://github.com/gohugoio/hugoDocs/issues/9.
