### ISSUE TITLE
Handle list.json templates in a case insensitive way

### ISSUE THREAD

**Issue by tutume** [gohugoio/hugo#3392]
Hi,

As pointed out by Bjørn [here](https://discuss.gohugo.io/t/how-to-use-the-new-custom-output-formats/6318/3), the Custom Output Format feature is expecting the template filename to be lower-cased. Is that by design? Is there any explanation about it? Or it could be fixed?

**Comment by bep** [comment]
Let us tone down the "fix" and "explanation". It is in line with how the rest of the template logic behaves, but we should **consider** doing something about it. Maybe.

**Comment by tutume** [comment]
Hi, please, sorry if I've sounded rude in any way. English isn't my mother language and usually a try to be as straight and simple as possible to be easier to be undestood. And even so, something I write in a wrong way. By explanation I wasn't actually asking for an explanation, I was asking if "there is a reason for this behavier". An about the part "Or it could be fixed?", should be a question: "Should it be fixed or it should be kept in that way?".

Anyway, thanks again.
