### ISSUE TITLE
all: Use sync.Map instead of sync.Mutex for safe concurent access to map after Go 1.9 release

### ISSUE THREAD

**Issue by bogem** [gohugoio/hugo#3408]
https://github.com/golang/go/commit/959025c0ac97ec3533ef9f3f70d64453352a7b56 introduced `sync.Map` and it provides pretty good performance speedup (https://github.com/golang/go/commit/eb6adc27d56687970dd8a49794ca85acc4cf9097, https://github.com/golang/go/commit/33b92cd6ce46c61a4d00a86b88971534773dd4a8, https://github.com/golang/go/commit/c120e449fbc618f9510387d718de0cef5f73af3a).

We also have some mutexes for map access, that could be replaced with `sync.Map`:
```
$ grep -nr 'sync.Mutex' .
./hugolib/pageCache_test.go:37: var l1 sync.Mutex
./hugolib/pageCache_test.go:38: var l2 sync.Mutex
./tpl/tplimpl/template.go:53:var amberMu sync.Mutex
./tpl/tplimpl/template_resources.go:36: remoteURLLock = &remoteLock{m: make(map[string]*sync.Mutex)}
./tpl/tplimpl/template_resources.go:44: m map[string]*sync.Mutex
./tpl/tplimpl/template_resources.go:50:         lock *sync.Mutex
./tpl/tplimpl/template_resources.go:55:         lock = &sync.Mutex{}
```
```
$ grep -nr 'sync.RWMutex' .
./helpers/general.go:211:       sync.RWMutex
./hugolib/pageCache.go:21:      sync.RWMutex
./hugolib/scratch.go:26:        mu     sync.RWMutex
./hugolib/shortcode.go:173:     sync.RWMutex
./output/layout.go:36:  mu    sync.RWMutex
./tpl/tplimpl/template_funcs.go:435:    sync.RWMutex
./tpl/tplimpl/template_funcs.go:1532:   sync.RWMutex
./tpl/tplimpl/template_funcs.go:1580:   mu sync.RWMutex
./tpl/tplimpl/template_resources.go:39: resCacheMu    sync.RWMutex
./tpl/tplimpl/template_resources.go:43: sync.RWMutex
```

It's just a note to not forget about it.

**Comment by bep** [comment]
We should, but maybe not until Go Go 1.9+1 (if the performance gain is big, I'm willing to drop the "two Go version compability rule"). But we can test and see.
