### ISSUE TITLE
tpl: Add "cached" piped option

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3417]
See #3042

The `partialCached` template func name makes for a bad API.

It would be nice if we could say:

```
{{ partial "head.html" . | cache }}
{{ partial "head.html" . | cache "some-key" }}
```

We would keep the old func as an alias, and this keyword would only work for the `partial` func at the start, but one could imagine we could use it for other things, and maybe add more "options" later.

I guess this would only work for funcs with "vararg room" on the end.

**Comment by digitalcraftsman** [comment]
In other words: the partial func could become more generic in the sense that it could also cache / handle more things than just templates in the future, right?

**Comment by bep** [comment]
No, turn it around: It is the `cache` keyword that is the generic part.

**Comment by digitalcraftsman** [comment]
> No, turn it around: It is the cache keyword that is the generic part

So, `cache` becomes the more generic version of `partialCached`?

**Comment by bep** [comment]
>So, cache becomes the more generic version of partialCached?

Yes. Maybe not relevant for partial, but for, say, images, one could imagine piping several "action options"; `image | rotate 30 | flip`...?

**Comment by digitalcraftsman** [comment]
> images, one could imagine piping several "action options"; `image | rotate 30 | flip`...?

Do you want to cache a composition of template functions this way?

**Comment by bep** [comment]
No.

**Comment by bep** [comment]
And the slightly longer version is:

I would love to come up with a generic "cache func" (how-to-suggestion welcome), but this is just options sent into another func (which can be accumulated).

So both of these are the same:

* `partialCached "head.html"`
* `partial | cached`

The reason we added the `partialCached` variant was because `func Partial(name string, cached bool` is kind of hard to use and document as a template func. And it becomes worse if you get func Partial(name string, cached, pretty bool`.

Then you may end up with:

* `partialPrettyCached "head.html"`

And this breaks down fast if you need some additional and optional cache key etc. So:

* `partial "head.html" | pretty | cache "home-page"`

And please don't ask me what `pretty` is -- I just made it up, but it is a **configuration option** and not a function doing the work.

**Comment by moorereason** [comment]
I agree and understand the reasoning, but the proposed implementation doesn't make sense.  With
```
partial "head.html" . | cached
```
the `partial` will always be executed.  `cached` needs to control execution, so the pipe usage would be rare, I think.

**Comment by bep** [comment]
>proposed implementation doesn't make sense. 

I haven't proposed and implementation, just the API.

**Comment by bep** [comment]
But this isn't really important. Let it linger.
