### ISSUE TITLE
IsMenuCurrent() returns false if menu item defined inside config file

### ISSUE THREAD

**Issue by lebarde** [gohugoio/hugo#3459]
It appears that `IsMenuCurrent` or `HasMenuCurrent` do not return true everytime it should.

- It seems to work for parent/children.
- It seems to always work on homepage.
- It seems to work on menu items defined inside the page/post's frontmatter.

But it seems **not** to work on menu items defined inside the main configuration file.

Is this a confirmed bug? At least this is the case for me.

Reference of discussions this is based upon:
- #2556
- [[discuss] Current navigation](https://discuss.gohugo.io/t/current-navigation/562/15)
- (amongst others)

**Comment by bep** [comment]
>Is this a confirmed bug? At least this is the case for me.

No, but as it depends on the `URL` you set in config to do the matching, it may be hard to get right. Unless you provide a complete and failing example, there is nothing to do here.

**Comment by lebarde** [comment]
I just uploaded a working site where menus do not work: https://github.com/lebarde/apo  
I generated the content using `hugo --buildDrafts`.

As you can see [here](https://github.com/lebarde/apo/blob/2959422a190572ae256ce59d0025b660e6e1394e/public/index.html#L79), the home button is active on the homepage. But on the [biographie/](https://github.com/lebarde/apo/blob/2959422a190572ae256ce59d0025b660e6e1394e/public/biographie/index.html#L124) page the `biographie` menu link is not marked as `active`.

Note that this is the case if I create the menu in the pages' front matters.

**Comment by lebarde** [comment]
One nice resolution would be the ability to define menu items by their identifiers or their routes (I assume that identifiers is easier to implement). In that way you do
```
menu:
  main: 
    - Name: Home
      Title: My home title
      URL: /
      Weight: 10
    - Name: "Biographie"
      Identifier: "biographie"
      Weight: 20
```
Because IMO the page file has to define its identifier (or it is defined automatically, which is the same for me), and *then* you define the menu globally. This is for me a good way to have an overview of the whole menu.

**Comment by Brixy** [comment]
Hi all!

I keep experiencing the same problem. Don’t know whether it is in issue or a problem of understanding.

> Unless you provide a complete and failing example, there is nothing to do here.

Attached you find an example. “Home“ and “blog” are provided with a `cur` class (-> bold text) when active; contact is not.

Thanks!

[zipped.zip](https://github.com/gohugoio/hugo/files/1782181/zipped.zip)

**Comment by cfjedimaster** [comment]
I am seeing the same issue. While my code isn't the exact same as @Brixy - I have a similar setup. Menu is defined in the config file - renders out just fine but IsMenuCurrent fails to work.

**Comment by fabianlaule** [comment]
I'm facing the same issue with `Hugo 0.47.1`

**Comment by kalilsn** [comment]
Solved this for myself just now by adding trailing slashes to my menu items in the config! I didn't realize it was matching by URL, but using `url = "/issues/"` instead of `url = "/issues"` did the trick.

**Comment by sysoce** [comment]
When defining multilingual menus the IsMenuCurrent function does not work as expected.

Expected result: Both menus get the "active" class when navigating to the respective page.
Result: Only the defaultContentLanguage menu gets the active class.

Temporary fix: set the "ja" menus URL to` url    = "/ja/"`


config.toml:

```
defaultContentLanguage = "en"

[languages.en]
weight = 0
languageName = "English"

[[languages.en.menu.main]]
identifier = "home"
url    = "/"
title   = "Home"
weight = 0

[languages.ja]
weight = 10
languageName = "日本語"

[[languages.ja.menu.main]]
identifier = "home"
url    = "/"
title   = "ホーム"
weight = 0
```

menu partial:
```
<ul>
    {{ $currentPage := . }}
    {{ range .Site.Menus.main }}
    <li>
        <a href="{{ .URL | absLangURL }}" class="{{ if $currentPage.IsMenuCurrent "main" . }}active{{ end }}">
        	{{ .Name }}
        </a>
    </li>
    {{- end }}
</ul>
```

**Comment by moorereason** [comment]
Please don't comment on old, closed issues.  Use the discussion forums or open a new issue.
