### ISSUE TITLE
Proposal: allow for keeping text and post-related resources in the same folder

### ISSUE THREAD

**Issue by zjedi** [gohugoio/hugo#3462]
**Requirement:** As a user maintaining posts that frequently refer to resources such as images, I want to keep them in the same folder as the markup file they belong to. It is natural and makes resouce management easier and more robust compared to the current situation of keeping images separately under `static`.

`static` folder still remains valid for resources that are relevant across the whole site (or just multiple posts), but user should not be forced to use it for post content.

Using _shortcode_, such as `{{< figure`  is just a workaround that makes content authors vendor-locked in Hugo and doesn't cover the whole requirement either. It is not desirable to implement this using shortcode.

**Example test case**
Let's imagine we have structure as shown below. In the post `spring-dependency-injection.md` I should be able to make:

1. a simple reference to a local image by using `[the UML](dependency-injection-UML.gif)` or `[the UML](./dependency-injection-UML.gif)`
1. [backwards-compatibility] reference to reusable static resource `/img/spring-logo.jpg` by `[the UML](/img/spring-logo.jpg)` (no change proposed here to keep it backwards compatible)
1. [optional] make a reference to a resource in a subfolder relative to my post location `[Special1](./special-resource-bundle/special-image-1.jpg)` 
1. [optional] make a reference to a resource in a folder higher in the tree, relative to my post location `[Logo](../spring-tutorial-header.jpg)` --- however there would need to be a "safety stop" not to get out of bounds of the hugo site.
```
my-site
├── content
│   └── about
│   └── post
│       ├── Electro
│       ├── Programming
│       │   ├── Java
│       │   │   ├── Spring-Tutorial
│       │   │   │   ├── 01-Introduction
│       │   │   │   │   └── spring-intro.md
│       │   │   │   └── 02-Dependency-Injection
│       │   │   │   │   └── spring-dependency-injection.md
│       │   │   │   │   └── dependency-injection-header.jpeg
│       │   │   │   │   └── dependency-injection-UML.gif
│       │   │   │   │   └── special-resource-bundle
│       │   │   │   │            └── special-image-1.jpg
│       │   │   │   └── spring-tutorial-overview.md
│       │   │   │   └── spring-tutorial-header.jpg
│       │   │   └── 
│       │   └── Go
├── layouts
├── public
├── static
|   └── img
|       └── my-site-header.jpg
|       └── spring-logo.jpg
├── themes
└── config.toml
```

**High-level solution design**
There has already been [discussion ](https://discuss.gohugo.io/t/keep-images-content-together/51) on the topic, but let's define how should it be done in more detail. Resource URL should be automatically composed by Hugo, using the `baseURL` defined in the main config file (`config.toml`) and the output URL of the post.
We should identify and isolate the part of the code that is responsible for calculating the URL. Then we can modify it to sequentially look for resources and stop when the first match is found:

1. path relative to location of the post file
1. as-is current behaviour (static resources, `public` root)

**Potential problems**
I believe Hugo can somehow make the same post available via multiple URLs / categories /tags --- that could cause some trouble, any feedback from the more experienced?

Since I am new to Hugo, I welcome any feedback, cooperators and hints on where one could start. 

By the way, there's also [vision for Hugo]( https://github.com/spf13/hugo/issues/3205) worth browsing.

**Comment by onedrawingperday** [comment]
You can always turn off tags and categories on the config.toml like so:
```
[taxonomies]
tag = ""
categories = ""
```
Other than that, there are already several ways of doing things in Hugo. Your proposal is about adding another one. Since you and possibly other people need it,  why not? Looks interesting.

There are others, who are more experienced than me with Go and the internal workings of Hugo.

**Comment by bep** [comment]
>I believe Hugo can somehow make the same post available via multiple URLs / categories /tags --- that could cause some trouble

You have some good ideas, but to get this done, you would have to get your thoughts away from the `URL` part if this. A bird's eye view of just the `URLs` will get you into a whole lot of trouble. Going the brute-force way of "finding a matching resource" is filled with ambiguity and it scales poorly.

**So you need a solid model that is really easy for the user to understand 
and get right.**

Thinking in Go interfaces, `Page` already implements this interface:

```go
interface Resource {
   Permalink() string
   RelPermalink() string
}
```

(one could imagine special kinds of resources, like images, with width and height and what not, but that is outside the scope of this.)

So, given that we need some kind of `resource bundle`:


```go
interface ResourceBoundle {
   Resources []Resource
}
```

And we need a way to group these resources and to configure them. Let us say that:

* A resource bundle has only one `Page` and that it the `resource master` that contains all the config.
* A resource bundle is contained in one folder and identified by its filename (no directory, so no "../" magic.)
* For pages that are marked as `resource bundles`, Hugo builds a bundle from all the files in that folder.

Of course, `Page` already has a concept of permalink settings etc., so every resource in the same bundle would derive from that.

So, we could maybe then say:

```
{{ if .IsBundle }}
{{ printf "The base URL of this bundle is %s" .BaseURL }}
{{ range .Resources }}
{{ .Permalink }}
{{ end }}
{{ end }}
```

Or from a shortcode:

```
{{ $imgLink := (.Page.Resources.Get "mylolcat.png").Permalink }}
```

It would of course, also be nice if the built-in Markdown syntax would just work:

```
[My funny cat](mylolcat.png)
```

Which we could fairly easily do with the above:

* If "mylolcat.png" is named resource in this page's bundle, then use that URL.
* Else: Leave it as is.

An note that, for the quote that started this: All URLs from `Permalink` and `RelPermalink` is  either absolute or relative to _the server root_, so it does not matter if it is used in different contexts (taxonomies etc.)

Note, that I wrote the above fairly quickly and there may be holes in it, but I kind of like its simplicity.

**Comment by bep** [comment]
Let us continue this in #3651
