### ISSUE TITLE
Hugo should generate an Atom feed and an RSS feed.

### ISSUE THREAD

**Issue by lpar** [gohugoio/hugo#3473]
Now that we have support for custom output formats, I think it's time to fix the problem of Hugo generating a mixture of RSS and Atom in its feed.

I would suggest generating a pure RSS feed and a pure Atom feed, and making the existing default RSS feed a pure RSS feed going forward. That said, my main concern is having a proper Atom feed.

I've got [an Atom feed template](https://gist.github.com/lpar/7ded35d8f52fef7490a5be92e6cd6937) I'm using which I'm happy to contribute, but I'm no expert on templates or Hugo internals so it might be better if someone else cleans it up, removes the Atom from the RSS template, and incorporates it into the internal defaults.

**Comment by cathalgarvey** [comment]
Related: #3487

**Comment by jhabdas** [comment]
I would like to see RSS 2.0 removed entirely with a minor release and Atom made the default. Rather than stating my reasons for this please simply look at the [Atom and RSS comparison](http://www.intertwingly.net/wiki/pie/Rss20AndAtom10Compared) on the Atom Wiki.

**Comment by jhabdas** [comment]
It's [better to choose one not both](https://blog.superfeedr.com/gospel/feeds/atom-or-rss-not-both/). I would like to see RSS 2.0 removed and Atom made the default. Here's a [comparison of RSS and Atom Atom](http://www.intertwingly.net/wiki/pie/Rss20AndAtom10Compared) showing some key differences.

Other reasons to Atom by default:

- Multiple enclosures
- Support for author with out Dublin Core namespace
- It's a standard built to fix the issues of RSS 2.0
- It supports more encoding types
- Unlike JSON Feed **it's an IETF standard**

**Comment by bep** [comment]
A new "feed" is Output Format + Media Type + Template. I would love it if this could have lived outside of Hugo core.

**Comment by jhabdas** [comment]
@bep thoughts on removing default RSS output then and leaving internal templates for each so they're optionally included by theme?

**Comment by lpar** [comment]
(I personally provide only Atom, and if it was up to me I'd rip out the RSS code from Hugo and support only Atom by default, but I was choosing to avoid controversy in the request.)

**Comment by jhabdas** [comment]
Given RSS is intended to support syndication of content it seems the Content Formats shouldn't necessarily be responsible for this behavior - so it seems one should be chosen and something like [Atomic RSS](http://www.tbray.org/ongoing/When/200x/2005/07/27/Atomic-RSS) avoided.

Another useful feature Atom has which fits well into Hugo's content-agnostic direction are [_Containers_](https://www.intertwingly.net/wiki/pie/Containers):

> Containers (synonym: collection) are objects that hold multiple Entries for any purpose.

**Comment by XhmikosR** [comment]
I totally agree that if Hugo is to include support for something it should be Atom. RSS is outdated and limited for the reasons the others have stated above.

**Comment by jhabdas** [comment]
For those looking to add Atom support here's some info shaping up: https://github.com/comfusion/after-dark/issues/32#issuecomment-312515542. Hugo makes it very easy to disable RSS, which is a blessing and very simple giving the IMHO stellar design of Output Formats. 😍

**Comment by lpar** [comment]
What we need in that case is something we can add cleanly to existing themes.
