### ISSUE TITLE
Bug: setting url to "/test" generates links to /test, but the page is actually located at /test/

### ISSUE THREAD

**Issue by arikroc** [gohugoio/hugo#3474]
So on the /posts/ directory, the link will be to /test, but clicking it will redirect you to /test/

Also I think (but not sure) that it showed up without the trailing slash in sitemap.xml

Perhaps good to add the trailing slash on the directory listings if trailing slashes are required

**Comment by bep** [comment]
What **exactly** do you mean by "setting url to /test"?

**Comment by arikroc** [comment]
Good question

I mean doing

```
---
url: "/test"
---
```

the alternative that would produce the expected behavior is

`url: "/test/"`
