### ISSUE TITLE
Feature request: slugify template function

### ISSUE THREAD

**Issue by alanbernstein** [gohugoio/hugo#3475]
This would pass the input through the markdown processor's slugify function. I have a use case for this that may be solvable in another way, but this seems appropriate given the existing functions `humanize`, `plainify`, `markdownify`.

**Comment by rdwatters** [comment]
Would you mind distinguishing betweeen this and [`urlize`](https://hugodocs.info/functions/urlize/)?

**Comment by alanbernstein** [comment]
Oh, I missed that because I was searching for "slugify". Having both wouldn't make sense, but I will instead suggest replacing the implementation of `urlize` with the implementation of `slugify`.

They serve the same purpose, but they don't transform strings in an identical way. For example, I have a markdown section titled "What's next?". `slugify` transforms this to "what-s-next", while `urlize` transforms it to "whats-next". This means my html generated from markdown has a header element with id="what-s-next", while a custom navigation element links to "#whats-next" if I use `urlize`. 

Again, there may be a different/better way to do what I'm doing - I just wanted to report what looked like a missing feature at the time.

**Comment by bep** [comment]
> replacing the implementation of urlize with the implementation of slugify.

How can we do that when there are no implementation of slugify?

We cannot change `urlize` in this way.  You may ask the Blackfriday markdown renderer to fix their "slugify".

**Comment by alanbernstein** [comment]
I'm not sure what you mean, the implementation is at https://github.com/russross/blackfriday/blob/0ba0f2b6ed7c475a92e4df8641825cb7a11d1fa3/markdown.go#L893 .Is this broken? Or does it just not match the `urlize` used in Hugo?

Anyway, I understand if it's not possible here, thanks for your help.

**Comment by bep** [comment]
I understand that there is a mismatch in the two, but I'm not sure how to fix it, that's all.
