### ISSUE TITLE
Enhancement: JSON Feed

### ISSUE THREAD

**Issue by cathalgarvey** [gohugoio/hugo#3487]
As in [here](https://jsonfeed.org/2017/05/17/announcing_json_feed).

**Comment by rdwatters** [comment]
Are you suggesting this be a built-in template or are you just asking for the functionality to build said file? (Spoiler alert: the latter is already possible.)

**Comment by cathalgarvey** [comment]
It's a pretty raw suggestion on my part; I saw a standard that would be cool to see widely adopted, so I'm just putting it in front of my preferred blog platformists. :)

If Hugo gets into providing datestamped content feeds like RSS/Atom, it'd be cool to support at least one new idea too, for the sake of keeping ahead on new trends. Anything JSON wins over XML in my book.

OTOH if Hugo isn't going to centrally manage feeds and will leave this to theme-ers, then so be it; this can be handled by theme authors instead if they desire.

**Comment by jhabdas** [comment]
I'm a huge no on this hype driven feed syntax. I have echoed these opinions in Jekyll Feed gem and opened a couple issues against JSONFeed themselves. There are bad ideas. And then there's JSON Feed.
