### ISSUE TITLE
docs: warning on GitInfo and Shallow Clones

### ISSUE THREAD

**Issue by client9** [gohugoio/hugo#3493]
Hello,

This is a documentation issue (which I'm happy to do a PR but first wanted feedback)

I was using using `enableGitInfo = true` and using {{ .AuthorDate. }}.  Works great locally.

This does *not* work when using https://travis-ci.org or any other system that is using shallow clone checkouts.

Try this in your full clone,
```
git log --name-only --no-merges HEAD
```
great.  This is what https://github.com/bep/gitmap uses.

But when you do that on a `--depth=1` shallow clone, amazingly, _every_ file is listed under one commit (same date, author, everything).

There is nothing we can do about that, except add a warning to 

https://gohugo.io/extras/gitinfo/

saying this should only be enabled on full clones.  

Unless I got this wrong.  I couldn't find a definitive reference on "why does git work this way".

Thoughts welcome, and happy to write a PR on this.

n

**Comment by bep** [comment]
Yes, this is a documentation issue. There is no way this can work without the _last commit for every file_ is available. I think Travis adds depth 50 by default, but there should be ways to override that.

**Comment by client9** [comment]
hi @bep, yeah it's docs issue.    I'll file a PR to add a small generic warning on shallow clones for that page.

You can adjust travis-ci to take more of less of the full clone

```
git:
  depth: 100000
```

or explicitly do a `git fetch --unshallow`  I don't know if we want travis-ci.org specific documentation on gohugo.io  or if there is place to put information on travis-ci.org

**Comment by digitalcraftsman** [comment]
Fixed by https://github.com/gohugoio/hugoDocs/commit/f3c88b081022c945f010cdbfcd25e0008e0c3f5b.
