### ISSUE TITLE
docs: 404 page shows wrong "Last Revision"

### ISSUE THREAD

**Issue by chankeypathak** [gohugoio/hugo#3497]
Go to https://gohugo.io/what

Notice below:

Last revision: January 1, 0001

**Comment by digitalcraftsman** [comment]
For pages automatically generated by Hugo, like the 404 page, that don't rely on content files it would make more sense to default to build time of the website.

**Comment by bep** [comment]
I suggest to add a check for `.LastMod.IsZero`, if true fallback to `.Site.LastChange`.

**Comment by chankeypathak** [comment]
@bep I'm new to Hugo and Go. Let me know in which file the change is required, I'll make an attempt to fix it.

**Comment by bep** [comment]
@chankeypathak https://github.com/spf13/hugo/blob/master/docs/layouts/partials/footer.html#L3

**Comment by chankeypathak** [comment]
@bep Thanks. Just submitted the fix.

**Comment by digitalcraftsman** [comment]
@chankeypathak we plan to switch to a new version of the docs that feature a new design. In the current state the 404 page doesn't show any revision date.

@budparr if you plan to add the last revision to your new design please let new know so we can incorporate @chankeypathak's submitted fix in the design.

**Comment by budparr** [comment]
Hey, @digitalcraftsman I removed that data from the theme for this request: https://github.com/gohugoio/gohugoioTheme/issues/8

**Comment by digitalcraftsman** [comment]
The of the new design is nearly around the corner which doesn't make use of Git to show the date of the last revision. Should this issue then be closed?

**Comment by chankeypathak** [comment]
Sounds OK to me. This can be closed.

**Comment by digitalcraftsman** [comment]
Thank you anyway for your submission @chankeypathak.
