### ISSUE TITLE
Add Solaris build

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3500]
We need this to be merged to get file watching working: https://github.com/fsnotify/fsnotify/pull/196

**Comment by maxmeyer** [comment]
@bep You might want to contact @dago. If he's still into OpenCSW, their build farm might help to build `hugo` on Solaris.

**Comment by bep** [comment]
@maxmeyer the problem isn't as much the building part; we got to get the code to work for Solaris first.

**Comment by moorereason** [comment]
The upstream PR referenced in the OP has been replaced by https://github.com/fsnotify/fsnotify/pull/263.  Getting closer...

**Comment by bep** [comment]
This is now fixed upstream: https://github.com/fsnotify/fsnotify/pull/371
