### ISSUE TITLE
JSON frontmatter parse error

### ISSUE THREAD

**Issue by zenany** [gohugoio/hugo#3511]
The page content for `home.md` is: 

```
{
  "title": "title",
  "categories": ["api"],
  "slug": "api.trade",
  "description": "{"
}

### Page
```

when generate page use hugo, got error:

<img width="570" alt="frontmatter_parse_error" src="https://cloud.githubusercontent.com/assets/2378632/26356021/489c606c-3ffd-11e7-8829-93edb5664f61.png">

there may be something wrong when process `{` in string value

**Comment by moorereason** [comment]
A simplified test:

```json
{"k": "{"}
```
