### ISSUE TITLE
ignore prefix of directory

### ISSUE THREAD

**Issue by zeigerpuppy** [gohugoio/hugo#3513]
It would be useful for the organisation of content to be able to ignore a directory prefix.
in [Daux](http://daux.io/), it's possible to refer to a content path with a prefix number ignored.

e.g:
```
01_first_section
02_next_section
```

These could be linked to by `./first_section` and `./second_section`

This feature is useful as it permits rearranging the working file tree while leaving links intact.
I tried to achieve the same using slugs, but these don't work for containing folder yet.

**Comment by bademux** [comment]
Sort by weight suits well here https://gohugo.io/content/ordering/

My home-brewed static generator relies on file\directory names and after 7 years of usage content base   grows to something like "articles/0/z_myarticle/10_article".
