### ISSUE TITLE
document Blackfriday extensions that are enabled by default

### ISSUE THREAD

**Issue by tpapp** [gohugoio/hugo#3523]
[The documentation](https://gohugo.io/overview/configuration/#configure-blackfriday-rendering) does not list them, but they can be found in the [source](https://github.com/spf13/hugo/blob/e98f885b8af27f5473a89d31d0b1f02e61e8a5ec/helpers/content.go#L259). Had I known about them, it would have made [tracking down](https://discuss.gohugo.io/t/how-to-get-a-from-markdown/6691/4) an issue with `\\\\` simpler.

**Comment by jamesrhea** [comment]
This appears to be complete. https://github.com/gohugoio/hugoDocs/pull/128
