### ISSUE TITLE
New site command throws wrong not empty error

### ISSUE THREAD

**Issue by mbertschler** [gohugoio/hugo#355]
Using `hugo new site /path/to/site` yields error `FATAL: 2014/07/05 /.../ already exists and is not empty`on OSX on a seemingly empty directory.
After showing hidden files there was a `.DS_Store` file in the directory, which is used by the OS X Finder to store view preferences.
The problem is that hidden files are not visible by default, so users might be confused by this error, when Finder shows an empty directory.
Maybe the new site command should ignore standard OS files like `.DS_Store`

**Comment by zachdyer** [comment]
Can I build a new site project in a folder already created with the hugo binary in there? That way other people can just download my project and use hugo right out of the box to update the site without adjusting their `path`.

**Comment by bep** [comment]
Sure. Not sure why you picked this random issue to put the question.

http://discuss.gohugo.io/ is better for questions.
