### ISSUE TITLE
[macOS specific?] hugo server SIGSEGV

### ISSUE THREAD

**Issue by anagio** [gohugoio/hugo#3551]
I'm getting this error when an `i18n` file contains invalid yaml. 

While working on translations copying and pasting I had this in my i18n i've since corrected it to `id` and hugo is building. The full error is below and i'm running `Hugo Static Site Generator v0.19 darwin/amd64 BuildDate: 2017-02-27T11:36:32-05:00`
```
- identifier: amazonlinux
  translation: "Amazon Linux"
```

```
$ hugo server --renderToDisk
Started building sites ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1599494]

goroutine 1 [running]:
github.com/spf13/hugo/hugolib.(*Page).shouldBuild(0xc420bae000, 0xc42029cc00)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/page.go:888 +0x34
github.com/spf13/hugo/hugolib.(*Site).convertSource(0xc4200e0780, 0x1768316)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1192 +0x227
github.com/spf13/hugo/hugolib.(*Site).createPages(0xc4200e0780, 0x175b3f5, 0x9)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1213 +0xc1
github.com/spf13/hugo/hugolib.(*Site).process(0xc4200e0780, 0x101, 0xc42028ae28, 0x2f93b56a202778b0, 0xed0c23f74)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:820 +0xea
github.com/spf13/hugo/hugolib.(*HugoSites).process(0xc4201c93b0, 0xc42028ae60, 0x0, 0x0, 0x0, 0x1b, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/hugo_sites_build.go:141 +0x126
github.com/spf13/hugo/hugolib.(*HugoSites).Build(0xc4201c93b0, 0x101, 0x0, 0x0, 0x0, 0x0, 0xc420299050, 0x1677d20)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/hugo_sites_build.go:49 +0x102
github.com/spf13/hugo/commands.(*commandeer).buildSites(0xc420289140, 0x1, 0x0, 0x6a8e68e6)
	/Users/bep/go/src/github.com/spf13/hugo/commands/hugo.go:721 +0xb5
github.com/spf13/hugo/commands.(*commandeer).build(0xc420289140, 0xc420277afe, 0x1, 0x1, 0xc420298990, 0x16)
	/Users/bep/go/src/github.com/spf13/hugo/commands/hugo.go:499 +0xa4
github.com/spf13/hugo/commands.server(0x1ad8840, 0xc4201c3610, 0x0, 0x1, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/commands/server.go:164 +0x849
github.com/spf13/hugo/vendor/github.com/spf13/cobra.(*Command).execute(0x1ad8840, 0xc4201c35f0, 0x1, 0x1, 0x1ad8840, 0xc4201c35f0)
	/Users/bep/go/src/github.com/spf13/hugo/vendor/github.com/spf13/cobra/command.go:632 +0x3ef
github.com/spf13/hugo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1ad6ec0, 0x1788748, 0xc42006a058, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/vendor/github.com/spf13/cobra/command.go:722 +0x339
github.com/spf13/hugo/commands.Execute()
	/Users/bep/go/src/github.com/spf13/hugo/commands/hugo.go:167 +0x60
main.main()
	/Users/bep/go/src/github.com/spf13/hugo/main.go:26 +0x32
```

**Comment by bep** [comment]
I'm fairly confident that this if fixed. Could you confirm by trying with a newer Hugo?

**Comment by anagio** [comment]
Yes i'll download the latest build to test and close if fixed

**Comment by anthonyfok** [comment]
> Yes i'll download the latest build to test and close if fixed

Hi @anagio!  Were you able to test it with the latest Hugo build, say, v0.24.1?
Many thanks!

**Comment by PellePedro** [comment]
Hi,

I'm also experience the SIGSEGV when rendering i18n on OSX (Sierra), e.g. the multilingual example in the hugo reposotory. I'm using hugo 0.24.1 with homebrew ...logs below.


$ brew info hugo

hugo: stable 0.24.1 (bottled), HEAD
Configurable static site generator
https://gohugo.io/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/hugo.rb
==> Dependencies
Build: go ✔, govendor ✘


$ git clone git@github.com:gohugoio/hugo.git

$ cd hugo/examples/multilingual

$ hugo
Started building sites ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xfcf64]

goroutine 1 [running]:
panic(0x6885c0, 0xc42000c100)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/spf13/hugo/hugolib.(*Page).shouldBuild(0xc4203b0000, 0xc42006dec0)
	/Users/pedro/go/src/github.com/spf13/hugo/hugolib/page.go:889 +0x34
github.com/spf13/hugo/hugolib.(*Site).convertSource(0xc420016fc0, 0x73c25e)
	/Users/pedro/go/src/github.com/spf13/hugo/hugolib/site.go:1187 +0x235
github.com/spf13/hugo/hugolib.(*Site).createPages(0xc420016fc0, 0x72f933, 0x9)
	/Users/pedro/go/src/github.com/spf13/hugo/hugolib/site.go:1208 +0xc1
github.com/spf13/hugo/hugolib.(*Site).process(0xc420016fc0, 0x100, 0xc4202ce1b8, 0x650a89320125a28, 0xed0ed76d3)
	/Users/pedro/go/src/github.com/spf13/hugo/hugolib/site.go:813 +0xd6
github.com/spf13/hugo/hugolib.(*HugoSites).process(0xc4202a28d0, 0xc4202ce1d0, 0x0, 0x0, 0x0, 0x1b, 0x0)
	/Users/pedro/go/src/github.com/spf13/hugo/hugolib/hugo_sites_build.go:141 +0x61
github.com/spf13/hugo/hugolib.(*HugoSites).Build(0xc4202a28d0, 0x100, 0x0, 0x0, 0x0, 0x0, 0xc4202ab600, 0x656a40)
	/Users/pedro/go/src/github.com/spf13/hugo/hugolib/hugo_sites_build.go:49 +0x104
github.com/spf13/hugo/commands.(*commandeer).buildSites(0xc4202914c0, 0x0, 0x0, 0xc41ffeb759)
	/Users/pedro/go/src/github.com/spf13/hugo/commands/hugo.go:721 +0xbd
github.com/spf13/hugo/commands.(*commandeer).build(0xc4202914c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/pedro/go/src/github.com/spf13/hugo/commands/hugo.go:499 +0xa4
github.com/spf13/hugo/commands.glob..func8(0xa831c0, 0xaaa380, 0x0, 0x0, 0x0, 0x0)
	/Users/pedro/go/src/github.com/spf13/hugo/commands/hugo.go:128 +0x15d
github.com/spf13/cobra.(*Command).execute(0xa831c0, 0xc42000c2b0, 0x0, 0x0, 0xa831c0, 0xc42000c2b0)
	/Users/pedro/go/src/github.com/spf13/cobra/command.go:644 +0x23e
github.com/spf13/cobra.(*Command).ExecuteC(0xa831c0, 0x7a8868, 0xfb06, 0xa8bfd0)
	/Users/pedro/go/src/github.com/spf13/cobra/command.go:734 +0x367
github.com/spf13/hugo/commands.Execute()
	/Users/pedro/go/src/github.com/spf13/hugo/commands/hugo.go:167 +0x6d
main.main()
	/Users/pedro/go/src/github.com/spf13/hugo/main.go:26 +0x32

**Comment by bep** [comment]
@PellePedro I suspect you have several versions of Hugo installed; the stack trace you posted does not match 0.24.1:

https://github.com/gohugoio/hugo/blob/v0.24.1/hugolib/page.go#L889

**Comment by sodevious** [comment]
I'm experiencing the same issue, with a fresh newly installed Hugo:

https://gist.github.com/sodevious/af295d51f96052e1b4540f62fded8a7c

`Hugo Static Site Generator v0.25.1 darwin/amd64 BuildDate: 2017-07-11T10:50:08-04:00`

**Comment by sodevious** [comment]
And the previously reported workaround doesn't work: `Error: unknown flag: --renderToDisk`

**Comment by bep** [comment]
@sodevious the "nil panic" you got is unfortunate, but can be for any number of reasons (it means a `Page` is nil), hard to say without seeing your actual site.
