### ISSUE TITLE
Custom language codes not support in multilingual setup

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3564]
https://github.com/nicksnyder/go-i18n/issues/72

/cc @bogem

**Comment by bogem** [comment]
The solution is in https://github.com/nicksnyder/go-i18n/pull/74. Waiting for @nicksnyder's answer.

**Comment by bep** [comment]
@bogem what is the status on this?

**Comment by bogem** [comment]
@nicksnyder fixed it in https://github.com/nicksnyder/go-i18n/pull/79. We should update this library and integrate this feature in hugo

**Comment by bep** [comment]
@bogem I have pulled in the lates go-i18n, could you have a look it at it? We could maybe label it as `Hacktoberfest` and hope someone will chime in during that month? Then we could just help him/her implementing it? Sounds good?

**Comment by bogem** [comment]
@bep yes, sounds good. Anyway, it's easy to solve. If nobody will fix this issue on Hacktoberfest, I will do it.

**Comment by kevingimbel** [comment]
Hey @bep, @bogem - I'd like to contribute but I'm not sure where to start and what needs to be done. Could you give me a heads-up?

As far as I understand the problem was loading languages which do not follow the Unicode CLDR standard naming. From the linked issue in go-i18n I understand that this can be fixed by registering the languages with `RegisterPluralSpec` so that we (hugo) can load whatever languages the user wants to have?

---

I've not yet worked with i18n in hugo, but I've been using hugo for a year or so and follow the development closely. :)

**Comment by bogem** [comment]
> From the linked issue in go-i18n I understand that this can be fixed by registering the languages with RegisterPluralSpec so that we (hugo) can load whatever languages the user wants to have?

You are totally right. All the logic of loading the i18n is in [initFuncs](https://github.com/gohugoio/hugo/blob/873a6f18851bcda79d562ff6c02e1109e8e31a88/i18n/i18n.go#L58). Start there. 
And don't forget to write tests.

**Comment by kevingimbel** [comment]
@bogem thanks! I'll start as soon as I get some free time!

**Comment by bogem** [comment]
Good luck👍
If you need help, don‘t hesitate to write here.

**Comment by kevingimbel** [comment]
@bogem I created a Pull Request #3971 

I had to update the `Update` function from `TranslationProvider `. This package is not tested - where should I add tests now? I tested the modification by creating a demo side and running my modified code against it with a language called "rando".

**Comment by bogem** [comment]
@kevingimbel You should add tests to [i18n_test.go](https://github.com/gohugoio/hugo/blob/master/i18n/i18n_test.go). There are a lot of examples, how you should make tests.

**Comment by bep** [comment]
@bogem I have added this to an upcoming "language themed" Hugo release, and it would be great if you could take some lead on getting the PR in question into a mergeable state. Let me know if you need my help.

**Comment by bogem** [comment]
Sorry, I was on vacation. Now I'm here

**Comment by bep** [comment]
I get some related "nil pointer" now when I run this on my site with two (valid) languages. I think this one needs some more testing.

**Comment by bep** [comment]
I had to revert this to how it behaved before. The fix for this at least broke existing sites. I got a nil pointer in the `Plural` func inside of `go-i18n`. I notice that an empty plural spec is created **even for the valid languages** (which has a built in plural spec) which I don't think makes sense. It doesn't work, for one.

**Comment by kevingimbel** [comment]
@bep Do you think we can do anything about it or is it a `go-i18n` problem?

**Comment by bep** [comment]
@kevingimbel see https://github.com/nicksnyder/go-i18n/pull/83

**Comment by bep** [comment]
I really need this in the upcoming release, so I'm going to take a stab on fixing this myself.
