### ISSUE TITLE
hugo new theme does not create a baseof.html

### ISSUE THREAD

**Issue by juh2** [gohugoio/hugo#3576]
As Block-Templates are the new default I think that the directory layout of a theme created by `hugo new` should reflect this and create a `baseof.html` in `_default`.

**Comment by digitalcraftsman** [comment]
Hello @juh2,

> Block-Templates are the new default I think

We make now assumptions about the user and the structure of his theme. Block templates are still optional, hence the don't have to be used as default.

But I would make sense to encourage theme creators to make use of `baseof.html` since it removes a lot of redundancy. Creating a `baseof.html` when executing `hugo new theme xyz` might also help to increase it's adaption.

If you think `baseof.html` should be created by default then label this issue as a feature request.

What remains is the question whether the adoption of block templates outweights the assumptions of the users and his intended theme structure.

**Comment by juh2** [comment]
Thanks for the clarification. 

I see no obvious button to do label this issue as feature request. 

Could someone with more insight or rights do this?

TIA

**Comment by bep** [comment]
I agree with @juh2 that most would really want a `baseof.html` if they knew about it. But we should then set up a basic structure with a content section etc.

**Comment by rdwatters** [comment]
Here's what is currently generated:

```
.
├── LICENSE.md
├── archetypes
│   └── default.md
├── layouts
│   ├── 404.html
│   ├── _default
│   │   ├── list.html
│   │   └── single.html
│   ├── index.html
│   └── partials
│       ├── footer.html
│       └── header.html
├── static
│   ├── css
│   └── js
└── theme.toml
```

How about the addition of `baseof.html`, `shortcodes`, and `img`? Seems like `content` and `data` should stay independent of the theme scaffolding. Also, I'm not especially firm on `img`:

```
.
├── LICENSE.md
├── archetypes
│   └── default.md
├── layouts
│   ├── 404.html
│   ├── _default
│   │   ├── baseof.html
│   │   ├── list.html
│   │   └── single.html
│   ├── index.html
│   ├── partials
│   │ ├── footer.html
│   │ └── header.html
│   └── shortcodes
├── static
│   ├── css
│   ├── img
│   └── js
└── theme.toml
```

**Comment by bep** [comment]
Let us keep this issue about ... `besof.html` and not add a lot of other issues on top.

**Comment by rdwatters** [comment]
You mentioned a `content` section as well, so I was running with it. Is this in the "beginner" or "easy" category,@bep? Maybe I can give it a shot :smile:

**Comment by digitalcraftsman** [comment]
General tenor of the comments supports this proposal. I would to extend this thought by linking the files together as follows:

Hugo generates `header.html` and `footer.html` by default. So the `baseof.html` would look like this:

```html
{{- partial "header.html" . -}}

{{- block "main" . }}{{- end }}

{{- partial "footer.html" . -}}
```

`404.html`, `list.html`, `single.html` and `index.html` would consist of

```
{{- define "main" }}{{- end }}
```

**Comment by rdwatters** [comment]
I would second the idea of including some partial calls as noted above by @digitalcraftsman. Simple enough to clue in new users and not so complicated that people end up deleting a bunch of scaffolding to get up and running...

**Comment by bep** [comment]
@digitalcraftsman I think the header/footer is an antipattern that the `baseof.html` solves -- and we should fix that. In the example you give, neither the header nor the footer is well-formed HTML document that can easily be edited/formatted by an editor. The `baseof.html` should form a simple and well formed HTML document with closing tags.

**Comment by digitalcraftsman** [comment]
@bep with my understanding of your comment you propose that `baseof.html` should contain the whole skeleton for a page, i.e. it "should form a simple and well formed HTML document with closing tags.".

Would a minimalistic `baseof.html` would look like this?

```html
<html>
    <head>
        <title>Hugo</title>
        <!-- some other stuff -->
    </head>
    <body>
        <div id="content">
        {{- block "main" . }}{{- end }}
        </div>

        <footer>
            <!-- copyright etc. -->
        </footer>
    </body>
</html>
```

I see the inclusion of the `header.html` and `footer.html` in `baseof.html` as a composition of simple templates that form a larger and more complex one.

**Comment by digitalcraftsman** [comment]
Got it.

**Comment by rdwatters** [comment]
If I may get more granular, I would only suggest that there be a `head.html` and a `header.html` since `head.html` tends to get very big very quickly:

```
<html>
    <head>
    {{- partial "head.html" . -}}
    </head>
    <body>
        {{- partial "header.html" . -}}
        <div id="content">
        {{- block "main" . }}{{- end }}
        </div>
        {{- partial "footer.html" . -}}
    </body>
</html>
```

Anything more than this, though, and I'm probably just getting too opinionated :smile:

**Comment by bep** [comment]
@rdwatters sure, but in your example `head.html` would not be well formed.

**Comment by bep** [comment]
This would be a good start:

```html
<html>
    {{- partial "head.html" . -}}
    <body>
        {{- partial "header.html" . -}}
        <div id="content">
        {{- block "main" . }}{{- end }}
        </div>
        {{- partial "footer.html" . -}}
    </body>
</html>
```

**Comment by rdwatters** [comment]
How about...

```html
<html>
    {{- partial "head.html" . -}}
    <body>
        {{- partial "header.html" . -}}
        <div id="content">
        {{- block "main" . }}{{- end }}
        </div>
        {{- partial "footer.html" . -}}
    </body>
</html>
```

**Comment by rdwatters** [comment]
And we crossed streams. Oops.

**Comment by anthonyfok** [comment]
I got here from:
1. #4808 
2. https://discourse.gohugo.io/t/what-are-the-pros-cons-of-using-a-baseof-template-or-the-standard-template/8048/4
3. https://github.com/gohugoio/hugo/issues/3576#issuecomment-307637628

> But it would make sense to encourage theme creators to make use of `baseof.html` since it removes a lot of redundancy. Creating a `baseof.html` when executing `hugo new theme xyz` might also help to increase its adaption.

Sounds like a great idea!

<html>
    {{- partial "head.html" . -}}
    <body>
        {{- partial "header.html" . -}}
        <div id="content">
        {{- block "main" . }}{{- end }}
        </div>
        {{- partial "footer.html" . -}}
    </body>
</html>
```

Hohoho!  Great minds think alike!

Since everyone has come to a consensus, I think it would be interesting to implement it in `hugo new theme` and maybe even in `hugo new site` (in a new interactive mode) with more instruction and guidance to the person starting a new website or a new theme.  With new theme especially, perhaps some guidance can ben written and some recommended licenses be offered...
