### ISSUE TITLE
docs: Document usage of nested sections

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugo#3584]
Nested sections where introduced in Hugo v0.22, i.e. by #3309. @bep created an [example website](http://hugotest.bep.is/). The corresponding source code can be found [here](https://github.com/bep/hugotest)

**Comment by digitalcraftsman** [comment]
Closing this as duplicate in favor of https://github.com/rdwatters/hugo-docs-concept/issues/135.

**Comment by maiki** [comment]
@digitalcraftsman should we reopen this one? We ought to track it here instead, ne?

**Comment by digitalcraftsman** [comment]
Well, this isn't the correct repo to track documentation related issues. But I agree https://github.com/rdwatters/hugo-docs-concept isn't the best place either because there isn't happening much since the rewrite of the Hugo docs.

The compromise would be to open a new issue at https://github.com/gohugoio/hugoDocs and close all others.
