### ISSUE TITLE
Change {{ end }} to {{ endif }}, {{ endrange }} or {{ endwith }}

### ISSUE THREAD

**Issue by Lego2012** [gohugoio/hugo#3589]
Don't know if this is an easy thing but it would make coding life much easier (at least for me). If you have an if statement with another if statement inside and a range or two inside as well it can get weird with all those {{ end }}. Advantage also would be that you can search for all e.g. {{ endif }} in the code for commenting further. Nonsens or not?

**Comment by bep** [comment]
Not nonsens -- but you would have to request this here:

https://github.com/golang/go/issues

I would not be too optimistic, though, these are the top dogs of Google handling these issues, and they fear change.

**Comment by Lego2012** [comment]
Did so, tnx.
