### ISSUE TITLE
Org name change

### ISSUE THREAD

**Issue by ahmetb** [gohugoio/hugo#3590]
Is there a forum where the repository org name change (spf13 &rarr; gohugoio) was discussed?

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting.

**Comment by ahmetb** [comment]
I can't find any good threads there about the decision making behind the name change. :)

**Comment by digitalcraftsman** [comment]
Feel free to open a thread in the forum. It's better suited for such kind of discussions ;)

**Comment by bep** [comment]
But note that this isn't a "org name change" it is a "org creation", which is a totally different thing.
