### ISSUE TITLE
Make the original term names accessible from .Data.Terms or .Site.Taxonomies

### ISSUE THREAD

**Issue by yihui** [gohugoio/hugo#3593]
I commented under https://github.com/gohugoio/hugo/issues/989#issuecomment-289662626 but it was probably not noticed, so I'm posting it as a separate issue.

My use case is to display all category or tag names of a site, and I'm in a dilemma:

- If I use `preserveTaxonomyNames = true`, I get ugly URLs (e.g. `/categories/This is a Category/`);
- If I set it to `false` (default), I get ugly names for humans (`this-is-a-category`).

In the latter case, I could use `string | humanize | title`, but it gives me `"This Is A Category"`. If only the original category names were stored and accessible from `.Site.Taxonomies.categories` or other variables (perhaps `.Site.OrigTexonomies` or `.Data.OrigTerms`?), I wouldn't have to face this dilemma.

**Comment by MunifTanjim** [comment]
It seems like it's not an issue anymore on Hugo v0.24.1

Just set `preserveTaxonomyNames = true` and the rest will be exactly like what you want.

Try it.

**Comment by yihui** [comment]
Interesting. I'm pretty sure this issue existed a few months ago, but as you said, it seems to have gone in 0.24.1. Not sure when it was fixed. Anyway, with `preserveTaxonomyNames = true`, the generated tag path for `This is a Category` is the nice `/tags/this-is-a-category` now. Thanks!

**Comment by ResponSySS** [comment]
To my knowledge this does not fix the issue when reading `.Term` from `.Data.Terms.ByCount` in taxonomy template (`layouts/_default/terms.html`).
