### ISSUE TITLE
Crash on build

### ISSUE THREAD

**Issue by bademux** [gohugoio/hugo#3596]
Hugo craches on processing multilingual site with 4475 md files.

$ hugo version
Hugo Static Site Generator v0.22.1 linux/amd64 BuildDate: 2017-06-13T14:18:34+02:00

$ hugo --verboseLog --logFile log.log
ERROR 2017/06/15 21:26:43 No 'baseURL' set in configuration or as a flag. Features like page menus will not work without one.
<details>
  <summary>Click to expand for crash log</summary>
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
352 regular pages created
702 other pages created
0 non-page files copied
302 paginator pages created
234 tags created
Built site for language pl:
0 draft content
0 future content
0 expired content
262 regular pages created
398 other pages created
0 non-page files copied
184 paginator pages created
134 tags created

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x338 pc=0xa0ea05]

goroutine 124 [running]:
text/template.errRecover(0xc4a5347870)
	/usr/local/go/src/text/template/exec.go:140 +0x1ec
panic(0xafe680, 0xf66360)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
text/template.errRecover(0xc4a5346b78)
	/usr/local/go/src/text/template/exec.go:140 +0x1ec
panic(0xafe680, 0xf66360)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/spf13/hugo/hugolib.(*Page).Parent(0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site_sections.go:59 +0x5
reflect.Value.call(0xbace20, 0xc4bfa2a498, 0x9293, 0xbb152e, 0x4, 0xf976d0, 0x0, 0x0, 0x40b64a, 0xc4a5345ee0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xbace20, 0xc4bfa2a498, 0x9293, 0xf976d0, 0x0, 0x0, 0xad83a0, 0xad83a0, 0xc4880c9468)
	/usr/local/go/src/reflect/value.go:302 +0xa4
text/template.(*state).evalCall(0xc4a5346928, 0xbace20, 0xc4bfa2a498, 0x96, 0xbace20, 0xc4bfa2a498, 0x9293, 0xf22340, 0xc4202a1f50, 0xc42018b6e4, ...)
	/usr/local/go/src/text/template/exec.go:668 +0x51f
text/template.(*state).evalField(0xc4a5346928, 0xbace20, 0xc4bfa2a498, 0x96, 0xc42018b6e4, 0x6, 0xf22340, 0xc4202a1f50, 0xc4201e2170, 0x1, ...)
	/usr/local/go/src/text/template/exec.go:558 +0xe18
text/template.(*state).evalFieldChain(0xc4a5346928, 0xbace20, 0xc4bfa2a498, 0x96, 0xbace20, 0xc4bfa2a498, 0x96, 0xf22340, 0xc4202a1f50, 0xc4201e2160, ...)
	/usr/local/go/src/text/template/exec.go:526 +0x22b
text/template.(*state).evalFieldNode(0xc4a5346928, 0xbace20, 0xc4bfa2a498, 0x96, 0xc4202a1f50, 0xc4201e2170, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:490 +0x118
text/template.(*state).evalCommand(0xc4a5346928, 0xbace20, 0xc4bfa2a498, 0x96, 0xc4202a1f20, 0x0, 0x0, 0x0, 0x18, 0x3, ...)
	/usr/local/go/src/text/template/exec.go:428 +0x837
text/template.(*state).evalPipeline(0xc4a5346928, 0xbace20, 0xc4bfa2a498, 0x96, 0xc4200a1310, 0x0, 0x0, 0x16)
	/usr/local/go/src/text/template/exec.go:406 +0xf2
text/template.(*state).walkIfOrWith(0xc4a5346928, 0xa, 0xbace20, 0xc4bfa2a498, 0x96, 0xc4200a1310, 0xc4202a1f80, 0x0)
	/usr/local/go/src/text/template/exec.go:261 +0xbc
text/template.(*state).walk(0xc4a5346928, 0xbace20, 0xc4bfa2a498, 0x96, 0xf22400, 0xc4201f2180)
	/usr/local/go/src/text/template/exec.go:237 +0x377
text/template.(*state).walk(0xc4a5346928, 0xbace20, 0xc4bfa2a498, 0x96, 0xf22460, 0xc4202a1da0)
	/usr/local/go/src/text/template/exec.go:240 +0x139
text/template.(*state).walkTemplate(0xc4a5346af8, 0xbace20, 0xc4bfa2a498, 0x96, 0xc4202bd7c0)
	/usr/local/go/src/text/template/exec.go:389 +0x267
text/template.(*state).walk(0xc4a5346af8, 0xbadc60, 0xc4901130e0, 0x16, 0xf226a0, 0xc4202bd7c0)
	/usr/local/go/src/text/template/exec.go:245 +0x226
text/template.(*state).walk(0xc4a5346af8, 0xbadc60, 0xc4901130e0, 0x16, 0xf22460, 0xc420293380)
	/usr/local/go/src/text/template/exec.go:240 +0x139
text/template.(*Template).execute(0xc4204d5640, 0xf17e20, 0xc4bfb841c0, 0xbadc60, 0xc4901130e0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:195 +0x20a
text/template.(*Template).Execute(0xc4204d5640, 0xf17e20, 0xc4bfb841c0, 0xbadc60, 0xc4901130e0, 0xc4a5346be0, 0xc4ea4dc2c0)
	/usr/local/go/src/text/template/exec.go:178 +0x53
html/template.(*Template).Execute(0xc420293470, 0xf17e20, 0xc4bfb841c0, 0xbadc60, 0xc4901130e0, 0xc4bfa2c5a0, 0x1e)
	/usr/local/go/src/html/template/template.go:120 +0x8c
github.com/spf13/hugo/tpl/partials.(*Namespace).Include(0xc420264780, 0xc420298199, 0xf, 0xc4bfa2a450, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/tpl/partials/partials.go:73 +0x3fa
github.com/spf13/hugo/tpl/partials.(*Namespace).Include-fm(0xc420298199, 0xf, 0xc4bfa2a450, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/tpl/partials/init.go:32 +0x63
reflect.Value.call(0xaf4f40, 0xc4201b3b60, 0x13, 0xbb152e, 0x4, 0xc4dc92bfb0, 0x2, 0x2, 0xf276a0, 0xb045e0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xaf4f40, 0xc4201b3b60, 0x13, 0xc4dc92bfb0, 0x2, 0x2, 0xf222e0, 0xc4201ee860, 0xbadc60)
	/usr/local/go/src/reflect/value.go:302 +0xa4
text/template.(*state).evalCall(0xc4a53477f0, 0xbadc60, 0xc4901130e0, 0x16, 0xaf4f40, 0xc4201b3b60, 0x13, 0xf22280, 0xc4202d1b00, 0xc420298190, ...)
	/usr/local/go/src/text/template/exec.go:668 +0x51f
text/template.(*state).evalFunction(0xc4a53477f0, 0xbadc60, 0xc4901130e0, 0x16, 0xc4202d1b30, 0xf22280, 0xc4202d1b00, 0xc4201f2900, 0x3, 0x4, ...)
	/usr/local/go/src/text/template/exec.go:536 +0x18e
text/template.(*state).evalCommand(0xc4a53477f0, 0xbadc60, 0xc4901130e0, 0x16, 0xc4202d1b00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:433 +0x6cd
text/template.(*state).evalPipeline(0xc4a53477f0, 0xbadc60, 0xc4901130e0, 0x16, 0xc4200a19f0, 0x0, 0x0, 0x98)
	/usr/local/go/src/text/template/exec.go:406 +0xf2
text/template.(*state).walk(0xc4a53477f0, 0xbadc60, 0xc4901130e0, 0x16, 0xf22100, 0xc4202d1b60)
	/usr/local/go/src/text/template/exec.go:232 +0x55a
text/template.(*state).walk(0xc4a53477f0, 0xbadc60, 0xc4901130e0, 0x16, 0xf22460, 0xc4202d1860)
	/usr/local/go/src/text/template/exec.go:240 +0x139
text/template.(*Template).execute(0xc4204d51c0, 0xf17e20, 0xc4ad324930, 0xbadc60, 0xc4901130e0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:195 +0x20a
text/template.(*Template).Execute(0xc4204d51c0, 0xf17e20, 0xc4ad324930, 0xbadc60, 0xc4901130e0, 0xc420264000, 0x100000000443ac5)
	/usr/local/go/src/text/template/exec.go:178 +0x53
html/template.(*Template).Execute(0xc4202d4180, 0xf17e20, 0xc4ad324930, 0xbadc60, 0xc4901130e0, 0x7, 0xc44f68b470)
	/usr/local/go/src/html/template/template.go:120 +0x8c
github.com/spf13/hugo/tpl.(*TemplateAdapter).Execute(0xc4abcd3f60, 0xf17e20, 0xc4ad324930, 0xbadc60, 0xc4901130e0, 0xc4abcd3f60, 0xc4aa1f1bc0)
	<autogenerated>:3 +0x75
github.com/spf13/hugo/hugolib.(*Site).renderForLayouts(0xc4200e2a00, 0xbb6e54, 0x7, 0xbadc60, 0xc4901130e0, 0xf17e20, 0xc4ad324930, 0xc44f68b400, 0x18, 0x20, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1970 +0xb8
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc4200e2a00, 0xc4aa1f1c00, 0x36, 0xc4aa1f1b00, 0x30, 0xc4901130e0, 0xc44f68b400, 0x18, 0x20, 0x0, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1910 +0xff
github.com/spf13/hugo/hugolib.pageRenderer(0xc4200e2a00, 0xc42f5796e0, 0xc42f579680, 0xc4801da3a0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site_render.go:122 +0x7de
created by github.com/spf13/hugo/hugolib.(*Site).renderPages
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site_render.go:44 +0x156
</details>
//------
UPD:
Problem gone if {{ partial "breadcrumb.html" . }} is removed from _default/list.html and _default/single.html
<details>
  <summary>Click to expand 'breadcrumb.html'</summary>
<ol class="arrows">
  {{ template "section-nav" .Parent }}
</ol>
{{ define "section-nav" }}
	{{ if .Parent }}
		{{ template "section-nav" .Parent }}
	{{ end }}
	<li><a href = "{{ .RelPermalink }}">{{ .Title }}</a></li>
{{ end }}
</details>

**Comment by bep** [comment]
I would guess that you forgot to pass the page into the breadcrumb partial, which is hard to tell without seeing the full site. It would be good if you continue this on discuss.gohugo.io

**Comment by bep** [comment]
Thinking about it, that can not be it, I guess. Reopen.

**Comment by bademux** [comment]
Can be closed,
I fix it by adding sainty nill check before template invoked for the first time.
Thanks.
