### ISSUE TITLE
Taxonomies are only omitted when declared as a site-wide param without properties or to empty strings...

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/hugo#3602]
Tested locally.

1. `config.toml` with `[taxonomies]` and nothing else = no taxonomies created
2. `config.toml` with no form of `[taxonomies]` mentioned = `hugo` builds `/tags` and `/categories`
3. `config.toml` with `[taxonomies]` but each taxonomy set to an empty string = no taxonomies created. 

Not sure if this qualifies as a "bug," but either way I want to update the documentation accordingly since I deleted previous mentions of default taxonomies.

Discourse thread:

https://discourse.gohugo.io/t/turning-off-taxonomy-pages/2622/17

**Comment by bep** [comment]
This works as expected. But you should really focus on `disableKinds` if the goal is to avoid taxonomies.
