### ISSUE TITLE
canonifyUrls relURL and baseurl

### ISSUE THREAD

**Issue by lebarde** [gohugoio/hugo#3603]
Hello,

When `canonifyUrls` is set to true, the `relURL` pipe strips the path url (leaves only the domain). It should 

Here are my settings:

```
baseurl: "http://www.domain.com/new"
canonifyURLs: true
```
In the post, I set:
```
featured: "/img/adrien/adrien01.jpg"
```
And here is the template:
```
{{- if .Params.featured -}}  
  {{- printf "background-image: url(%q);" (.Params.featured | relURL) | safeCSS -}}
{{- end -}}
```

Here are the behaviours:
- With the settings above, I get `background-image: url("/img/adrien/adrien01.jpg");`, whereas `relURL` should prepend `/new/` to the url.
- If I comment the `canonifyURLs` line, I get `background-image: url("/new/img/adrien/adrien01.jpg");`, which is the expected behaviour.

The markdown links generated with blackfriday are well formed with `canonifyURLs: true`, though.

I personnally need `canonifyUrls` to be set to true to have the links inside posts to point to the right locations. For now I get template URLS right XOR post urls right, but not both.

**Comment by bep** [comment]
* `relURL` interprets "/img/adrien/adrien01.jpg" as a URL relative to the server/host root. Try without leading slash.
* Canonify URLs is not supported for inline CSS. I doubt we will, but we need a more focused issue to track that than this one.

**Comment by lebarde** [comment]
Thanks for your comment @bep. I therefore updated my first post, given that this is not about CSS and that it has no effect on the behaviour.

> `relURL` interprets "/img/adrien/adrien01.jpg" as a URL relative to the server/host root.

This is why I am opening this issue. I assume that `relURL` should interpret "/img/adrien/adrien01.jpg" as a URL relative to the server's root, prepend with the path in the baseurl.
