### ISSUE TITLE
Expand Environment Variables in publishDir

### ISSUE THREAD

**Issue by dc0d** [gohugoio/hugo#3604]
In `config.toml` I've set `publishDir = "$HOME/Desktop/public"` and I've got that directory, created literally with name `$HOME`, inside current directory.

Also I've done a `rm -rf $HOME/` and currently going through a bit of stressful times! Silly me!

I'm not sure if this is a bug. Filled this just for the record, in case it is.

**Comment by bep** [comment]
This is not supported, and I doubt we will. What you currently can is to override config vars via OS env, so you can do:

```
HUGO_PUBLISHDIR="$HOME/Desktop/public" hugo
```

I assume that your shell will expand $HOME correctly in the above.
