### ISSUE TITLE
Hugo on Travis CI fails silently if pygments' version is not 2.1.3

### ISSUE THREAD

**Issue by mgmart** [gohugoio/hugo#3608]
If an other version than pygments 2.1.3 is used then code is not rendered at all.

This was discussed on discourse: [No code output with pygments on travis](https://discourse.gohugo.io/t/no-code-output-with-pygments-on-travis/7042)

If it's not possible to quickly add support for 2.2 and 1.x, I would suggest to mention the version needed in the documentation.

Pygments version 1.4 was installed on travis as I used the `apt` approach. Using `pip install` version 2.2 was installed. Being a python-ignorant I did not know how to install a specific version using `pip`.

The mention of `pip install pygments==2.1.3` in the [documentation](https://gohugo.io/overview/installing#installing-pygments-optional) would have helped.

**Comment by DanielGibson** [comment]
FWIW I guess any 2.1 version works, at least for me Hugo 0.20.7 works with pygments 2.1 (from Ubuntu's python-pygments 2.1+dfsg-1)

But I think at least newer versions should be supported and unsupported ones should not just silently fail.
