### ISSUE TITLE
cannnot user LevelError as type Threshold 

### ISSUE THREAD

**Issue by wenchma** [gohugoio/hugo#3609]
github.com/spf13/hugo

./main.go:34: cannot use "github.com/spf13/hugo/vendor/github.com/spf13/jwalterweatherman".LevelError (type "github.com/spf13/hugo/vendor/github.com/spf13/jwalterweatherman".Threshold) as type "github.com/spf13/jwalterweatherman".Threshold in argument to commands.Hugo.Deps.Log.LogCountForLevelsGreaterThanorEqualTo

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
