### ISSUE TITLE
Provide option to remove port number in site baseurl

### ISSUE THREAD

**Issue by chingli** [gohugoio/hugo#361]
I want to match Hugo up with [boxcars](https://github.com/azer/boxcars)(a Static Web/Reverse Proxy Server in Go). My hugo website (example.com) listens on 1313 port, and boxcars listens on 80 port. When I visit http://example.com/ in my browser, I get the right homepage, but all the URLs generated by `.Site.BaseUrl`, `.Permalink` and so on have a port 1313, such as http://example.com:1313 in them, but what I wanted URL is http://example.com. How can I fix it? Many thanks!

**Comment by georgibakken** [comment]
Is this option (`--appendPort`)  also possible to provide for [hugo build](https://gohugo.io/commands/hugo/) ?
