### ISSUE TITLE
How to access iterator value in range

### ISSUE THREAD

**Issue by vivekdwivedi** [gohugoio/hugo#3611]
I am following the creation of a new theme, and I have a very simple use case to show last three blog posts on the home page. 
````
{{- range first 3 .Data.Pages -}}
{{- if eq .Type "blog"}}
<section id="one" class="wrapper spotlight style1">
<div class="inner">
<a href="#" class="image"><img src="images/pic01.jpg" alt="" /></a>
<div class="content">
<h2 class="major">{{ .Title }}</h2>
<p>Lorem ipsum </p>
<a href="{{ .Permalink }}" class="special">Read more</a>
</div>
</div>
</section>
{{- end -}}
{{- end }}
````
Now this code works till the point where I am able to get the title and permalink for my posts, but I want to have separate classes for the `<section>` based on their order. So first section should have `style1` and second should have `style2`. Third will then have `style3`. Is there a way in which I can say that based on the index where the iterator is at, add dynamic classes?

Also, what will be a good way to set and access header images for my posts?

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by rdwatters** [comment]
@bep Just a heads up to change the URL for your forum responses (if you haven't already).
