### ISSUE TITLE
Unable to checkout submodule docs

### ISSUE THREAD

**Issue by cogitamus** [gohugoio/hugo#3624]
Hi,

Running on Debian: Hugo Static Site Generator v0.23-DEV linux/arm BuildDate: 2017-06-16T06:49:29Z

go get -u -v  github.com/spf13/hugo

github.com/spf13/hugo (download)
# cd /home/xyz/go/src/github.com/spf13/hugo; git submodule update --init --recursive
fatal: reference is not a tree: 49afd52aea9249988f1a7b5f41f0b280d9ca7de0
Unable to checkout '49afd52aea9249988f1a7b5f41f0b280d9ca7de0' in submodule path 'docs'
package github.com/spf13/hugo: exit status 1

Results in a 404. https://github.com/gohugoio/hugoDocs/tree/49afd52aea9249988f1a7b5f41f0b280d9ca7de0

**Comment by bep** [comment]
Thanks for the heads up, this should be fixed now.
