### ISSUE TITLE
the url of post is not correct

### ISSUE THREAD

**Issue by jinleileiking** [gohugoio/hugo#3627]
```
hugo server --bind "0.0.0.0" -p 8441 --buildDrafts --theme=hugo_theme_robust

```

```
➜  bookshelf git:(master) ✗ cat config.toml
baseURL = "http://10.64.7.106:8441/"
languageCode = "en-us"
title = "My New Hugo Site"
```

open http://10.64.7.106:8441/post/former/ can show the page. 

bug click the homepage button jump to `http://localhost:8441/post/former/`

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
