### ISSUE TITLE
Provide archetype .Date that works unquoted for both TOML and YAML

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3628]

**Comment by anthonyfok** [comment]
This seems to be a regression that happened between v0.21 and v0.22 based on my **limited/preliminary** testing, and seemingly applies only to TOML, as in the following error:

> ERROR 2017/06/22 13:41:27 failed to parse page metadata for "post/former.md": Near line 2 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got '+' instead

did not appear in v0.21 with an unquoted date in a TOML front matter, and `hugo server` continues to happily serves the website showing apparently correct article dates.

**Comment by bep** [comment]
We switched TOML lib in 0.22.

**Comment by anthonyfok** [comment]
> We switched TOML lib in 0.22.

Thank you so much for your insight!  BurntSushi/toml for front matter TOML since v0.22!
I was looking in completely wrong places.

I went ahead and submitted a PR at BurntSushi/toml#182.  Hope that's the right way to do it.  :-)

**Comment by bep** [comment]
FIxed in 0e1bda34c3343c42020f1289f849ccf18c39e603

**Comment by anthonyfok** [comment]
For reference:
Follow up PR at BurntSushi/toml#185 "Complete the testing for decoding datetime with UTC offset"
