### ISSUE TITLE
hugo convert toYAML on a single file

### ISSUE THREAD

**Issue by yihui** [gohugoio/hugo#3632]
(Feature request moved from #3631)

It will be nice if `hugo convert` works on files. Currently it only works for a directory. For example, `hugo convert toYAML foo.md` converts the metadata to YAML.

**Comment by yihui** [comment]
I don't think this has been implemented yet.

**Comment by yihui** [comment]
Still not implemented yet...

**Comment by yihui** [comment]
Still not implemented yet... (I feel like I'm becoming a bot 😀)

**Comment by yihui** [comment]
Still not implemented yet...

**Comment by yihui** [comment]
Still not implemented yet...

**Comment by yihui** [comment]
Still not implemented yet...

**Comment by yihui** [comment]
Still not implemented yet...

**Comment by yihui** [comment]
Still not implemented yet...

**Comment by yihui** [comment]
Still not implemented yet...

**Comment by jmooring** [comment]
See also <https://discourse.gohugo.io/t/hugo-convert-for-single-md-files/32313/8>.

**Comment by yihui** [comment]
Still not implemented yet and it'll be nice to have this feature... Thanks!

**Comment by yihui** [comment]
Okay, it's been six years, and I'm just giving up :) Please feel free to close it.
