### ISSUE TITLE
Documentation - hugo server - must be started from Hugo/Site/Sitename.com

### ISSUE THREAD

**Issue by aj-th** [gohugoio/hugo#3634]
In the Documentation> http://gohugo.io/overview/quickstart/ when you get down to Step 4-Serve Content

The documentation indicates that you should be able to run `hugo server` from Hugo/Sites/Sitename.com/content/post, but you must start `hugo server` from Hugo/Site/Sitename.com

**Comment by aj-th** [comment]
Or...I am a complete idiot who should not be allowed to touch a keyboard ever again and I should be shamed for my horrible issue requests on GitHub. 

		

		Get Outlook for iOS
	





On Thu, Jun 22, 2017 at 6:53 PM -0400, "Jerry" <notifications@github.com> wrote:












In the Documentation> http://gohugo.io/overview/quickstart/ when you get down to Step 4-Serve Content


The documentation indicates that you should be able to run hugo server from Hugo/Sites/Sitename.com/content/post, but you must start hugo server from Hugo/Site/Sitename.com

**Comment by kevingimbel** [comment]
@aj-th So this issue can be closed?

**Comment by aj-th** [comment]
@kevingimbel - i don't think so. I tested more last night, and nothing I do can get the QuickStart docs to match with my request. I thought I had missed something but testing revealed the same behavior. 

From what I can tell 'Hugo server' must be run from Hugo/Sites/sitename.com and not from inside the directory.

**Comment by onedrawingperday** [comment]
> The documentation indicates that you should be able to run hugo server from Hugo/Sites/Sitename.com/content/post, but you must start hugo server from Hugo/Site/Sitename.com

Where exactly does the documentation state such a thing?

From what I see the documentation at http://gohugo.io/overview/quickstart/#step-4-serve-content reads like this:

> Hugo has an inbuilt server that can serve your website content so that you can preview it. You can also use the inbuilt Hugo server in production. To serve content, execute the following command inside the bookshelf directory.

The bookself directory IS the site directory that was specified earlier in Step 2 of the Quickstart Guide with 
`$ hugo new site bookshelf`

I have never seen anyone suggest that the user could run the hugo server command from within the content directory. One always runs it under the root directory.

This is a non issue and it needs to be closed.
