### ISSUE TITLE
Documentation - QuickStart Guide - Step 8. Customize robust theme

### ISSUE THREAD

**Issue by aj-th** [gohugoio/hugo#3635]
> The first change that we have to make is to use a different default image instead of the one used in the theme. The theme’s default image used in both the list and single view page resides inside themes/hugo_theme_robust/static/images/default.jpg. We can easily override it by creating a simple directory structure inside the repository’s static directory.

> Create an images directory inside the bookshelf/static directory and copy an image with name default.jpg inside it. 

However, if you copy the Hand/Book image, name it default.jpg and place in the Hugo\Sites\ex2.com\static directory as stated above, the page will **not** update with this image.

You should clarify that in this example, you must place the Hand/Book image named default.jpg in the: \Hugo\Sites\bookshelf.com\themes\hugo_theme_robust\static\images, then refresh the page to see the changes you made.

**Comment by aj-th** [comment]
Or...I am a complete idiot who should not be allowed to touch a keyboard ever again and I should be shamed for my horrible issue requests on GitHub. 
		

		Get Outlook for iOS
	





On Thu, Jun 22, 2017 at 7:23 PM -0400, "Jerry" <notifications@github.com> wrote:













The first change that we have to make is to use a different default image instead of the one used in the theme. The theme’s default image used in both the list and single view page resides inside themes/hugo_theme_robust/static/images/default.jpg. We can easily override it by creating a simple directory structure inside the repository’s static directory.




Create an images directory inside the bookshelf/static directory and copy an image with name default.jpg inside it.



However, if you copy the Hand/Book image, name it default.jpg and place in the Hugo\Sites\ex2.com\static directory as stated above, the page will not update with this image.


You should clarify that in this example, you must place the Hand/Book image named default.jpg in the: \Hugo\Sites\bookshelf.com\themes\hugo_theme_robust\static\images, then refresh the page to see the changes you made.

**Comment by aj-th** [comment]
@digitalcraftsman - I confirmed this. I went back last night and retested with the same results.

**Comment by ducreuxr** [comment]
Hi @aj-th , I'm not sure I understand your problem. The page will not update with this image if you put it in bookshelf/static/images/ because the previous image is still cached (I think we can improve the documentation by warning users about it). This part of the documentation is not clear for me, I had to read it two-three times before I get it right. I'm not a native speaker, so I can't tell if I misunderstood because the documentation is not clear enough or because of my English comprehension level :-P.
