### ISSUE TITLE
`hugo new` only accepts the .md extension in Hugo v0.24

### ISSUE THREAD

**Issue by yihui** [gohugoio/hugo#3640]
This starts to fail in 0.24 and used to work in 0.23 and earlier versions of Hugo:

```bash
$ hugo new test.Rmd -v
INFO 2017/06/23 23:59:21 Using config file:
INFO 2017/06/23 23:59:21 attempting to create "test.Rmd" of "" of ext ".Rmd"
Error: open : no such file or directory
```

I don't know what this error message means. Only `hugo new test.md` is permitted now.

**Comment by bep** [comment]
Duplicates #3626 -- it seems to be a pain for many, so I will push v0.24.1 today.

**Comment by yihui** [comment]
Very nice. Thanks!
