### ISSUE TITLE
.IsHome isn't True when using homepage via Markdown

### ISSUE THREAD

**Issue by felicianotech** [gohugoio/hugo#3642]
When I create my homepage via `theme/MY_THEME/layout/index.html`, the variable `.IsHome` is set to `True` as expected.

If I instead, create my homepage as a Markdown file at `content/index.md`, `.IsHome` is not set to `True`.

---
Hugo v0.24.1

**Comment by bep** [comment]
I assume you mean

```
content/_index.md
```

?
