### ISSUE TITLE
Add option to open "current" content file in a browser

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3643]
I saw this question asked somewhere and it would be really useful:

* I guess it would be triggered on the first save of a new content file, but that would be OK. 
* It should have a `hugo server` flag (`browserOpen` ?) + config so it is easy to turn on.
* Default OFF.
* It should handle situations with "mass edits", but I guess that is also an issue with the current?

**Comment by bep** [comment]
I first thought I could use something ala https://github.com/pkg/browser -- but that opens new URLs in new browser tabs, which is annoying and not what we want. 

I guess the only real options is to look at a way to somehow extend livereload to do this (livereload does not support it); we already have a WebSocket server running ... Thinking.

**Comment by bep** [comment]
Yes, hooking into the livereload infrastructure seems to work fine in my very crude test. Will have to look for a cleaner way to do this, but this could be useful.

**Comment by bep** [comment]
Just tested, and the current `livereload.RefreshPath` works fine with content pages (i.e. it navigates to that content page if on another page), so this is going to be slightly more simple than I first imagined, which is good.

**Comment by jhabdas** [comment]
This little feature, is having so much positive impact on my workflow. I'd like to state for the record stopping my React development and moving to Hugo has been one of the best choices I've made in the last 5 years.
