### ISSUE TITLE
Improve live-reload logic for static files

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3644]
See https://github.com/gohugoio/hugo/blob/873a6f18851bcda79d562ff6c02e1109e8e31a88/commands/hugo.go#L962

One thing is that the comment here does not match the implementations. Not much practical impact, but there are room for improvements here:

1. Filter duplicate paths
2. Do hard refresh if > 1

**Comment by jmooring** [comment]
I'm pretty sure this can be closed too. I assume it was addressed in https://github.com/gohugoio/hugo/pull/11894, or is no longer relevant. Changes to static files (e.g., overwriting an image with a different one) works great.
