### ISSUE TITLE
Taxonomy Frontmatter Bug - Description plus link to repo with bug present.

### ISSUE THREAD

**Issue by thewebmastercom** [gohugoio/hugo#3650]
Problem: When using Taxonomies the Front matter variables in the taxonomy _index.md file are not displaying in the taxonomy.html template.

Here is a link to a repo with the code to the bug mentioned below: https://github.com/thewebmastercom/gohugobug

Version 0.24.1

Bugged page: http://localhost:1313/categories/siteground-news/ (obviously, you will want to download the repo to view)

![localhost 1313 categories siteground news](https://user-images.githubusercontent.com/20093256/27557312-121cd674-5ab1-11e7-9f30-82b7708855a3.png)

The content/categories/siteground news/_index.md contains:
```
---
linktitle: News
testparams: This is the Test PARAM
---
```
As you can see in the screenshot, not testparams is present.

If you remove the following from content/hosting-news/example-post.md:
```
categories: 
    - siteground news
```
The testparam will now show, rendering the template correctly, although of course, no posts will be present, because we deleted the category. Here is a screenshot:

![localhost 1313 categories siteground news 1](https://user-images.githubusercontent.com/20093256/27557464-a1496a92-5ab1-11e7-8c9b-29daa035e40c.png)

You will see that for the purposes of this test the website code has been stripped to the bare minimum, allowing, hopefully most other causes to be excluded.

See also discussion here: https://discourse.gohugo.io/t/front-matter-in-taxonomy-templates/7206

If you require further information please let me know.

**Comment by bep** [comment]
The path to the "_index.md" must match the normalized taxonomy path, i.e. what you see on the file system and in the browser:

http://localhost:1313/categories/siteground-news/

So, not "siteground news", but "siteground-news".
