### ISSUE TITLE
cineg

### ISSUE THREAD

**Issue by cogitamus** [gohugoio/hugo#3654]
Hi,

(command) go get -u -v github.com/gohugoio/hugo

(result)
        . . .
        docs/content/showcase/christianmendoza.md
        docs/content/showcase/cineg
Aborting
Updating b463c5a..a544049
package github.com/gohugoio/hugo: exit status 1

(source)
No cineg? Where/why has been asked for this file?
https://github.com/gohugoio/hugo/tree/master/docs/content/showcase

**Comment by anthonyfok** [comment]
Hi @cogitamus,

It is not `docs/content/showcase/cineg` but rather `docs/content/showcase/cinegyopen.md` that `go get` was trying to fetch via `git`.

This looks like some kind of network or system glitch to me such that somehow `go get` got interrupted and thus went aborting.

Care to run `go get -u -v github.com/gohugoio/hugo` again?  It would most likely work.  Closing this issue.

If you have further questions, please continue this conversation on https://discourse.gohugo.io/.
