### ISSUE TITLE
Improve installation experience

### ISSUE THREAD

**Issue by dak-csis** [gohugoio/hugo#3658]
I have been attempting to install Hugo on a fresh install of Debian 8 Jessie for about a week now.

- First I attempted to install through debian packages, however the hugo package is not available for Jessie
- Second I attempted to install Hugo through snap packages, however snap is not available for Jessie
- Third I attempted to install Hugo through source, but the Jessie version of Go gives a mysterious error. Error is likely related to an outdated version of Go
- Installing Go from Source allows me to get as far as installing 'govendor' however package does not get installed even though govendor does not output any error.

So I'm sitting here a week later, many hours wasted on getting going with hugo. All the buzz and excitement about how "easy" hugo is to use is lost on me till this day.

I realize that my bug report is at best unhelpful as all of my issues come from the fact that I'm trying to install Hugo on a wildly popular distribution which chooses to pride itself with having ancient versions of software in it's primary repository, but if any person involved with Hugo would please sit down with a Debian based VM and just... get hugo _installed and working_... and post some guide or even better, publish some official .deb packages for the thing, I think we could increase Hugo's already wild popularity :)

**Comment by anthonyfok** [comment]
Hi @dak-csis,

Debian 9 _Stretch_ is out now, and is the new Debian **stable** version since 17 June 2017!
Would you like to install that instead?  You'll have a much more pleasant experience there!  :-)

**Comment by anthonyfok** [comment]
Hi again, @dak-csis:

If, for some unknown reasons, you are stuck on the _old-stable_ Jessie and cannot upgrade to Stretch or cannot simply do a fresh install of Stretch, then `jessie-backports` is the solution to your woes!

`golang-go` in Jessie is stuck in Go 1.3.3 (see https://packages.debian.org/search?keywords=golang-go), but the Debian Go Team has actually backported the rather modern Go 1.7.4 to jessie-backports!

(Seriously, few Go programs, if any, work with Go 1.3 any more.)

Please visit https://backports.debian.org/Instructions/ to learn how to add jessie-backports to your /etc/apt/sources.list file, and how to install stuff from jessie-backports.  I will leave this as an exercise for you.

But seriously, just upgrade to Debian 9 Stretch!  Do it today!  Your life will be so much simpler!

**Comment by anthonyfok** [comment]
@dak-csis  If you have further questions or comments, please do not hesitate to contact us!
Not here though; please go to https://discourse.gohugo.io/ for our discussion forum!

**Comment by dak-csis** [comment]
Thanks, I'll try with Debian 9 :)

**Comment by anthonyfok** [comment]
> Thanks, I'll try with Debian 9 :)

Awesome!  Please let us know of the experience, @dak-csis!

(Hugo v0.18.1 is in `stretch`, so you can indeed install `hugo` using the `sudo apt install hugo` command, albeit it is an old version.  v0.24.1, or, rather, its updated dependencies, are still being packaged slowly by yours truly... <grin, duck, run>...)
