### ISSUE TITLE
Support gathering git commits/contributors to be rendered on each page.

### ISSUE THREAD

**Issue by pauldotknopf** [gohugoio/hugo#3659]
I am looking to switch from Wyam to Hugo. Wyam has a feature that I really like/need.

* https://wyam.io/modules/gitcommits - This allows pages to render a list of commits on each page.
* https://wyam.io/modules/gitcontributors - Same thing, but a list of contributors.

**Comment by bep** [comment]
We have GitInfo (i.e. last commit), but that has a useful use case, even if it is pushing it performance wise. What you suggest is not something we'd want to add to Hugo core. Once we get some plugin support, maybe, but that is covered by another issue. In the mean time I suggest you write a simple shell script to write the Git log to a data file or something.

**Comment by pauldotknopf** [comment]
I'm circling back to this issue. What is the roadmap for plugin support?

I am willing to make a pull request for this feature, if you are accepting to it.

I'd like to leave the ```.GitInfo``` as-is and add a new ```.GitCommits``` array. This would only be enabled if you pass another command line flag. That way, perf won't be touched unless this command line flag is enabled.
