### ISSUE TITLE
Incorrect error report - accessing index of a map by key

### ISSUE THREAD

**Issue by matfin** [gohugoio/hugo#3664]
Just spotted this while using Hugo v0.24.1. The following error comes up even though things appear to work.

```
ERROR 2017/06/30 09:39:24 Error while rendering "page": template: project/single.html:9:6: executing "project/single.html" at <index .Params.teaser...>: error calling index: cannot index slice/array with type string
```

This is the snippet from my `single.html` template for content of type `project`:

```
{{ index .Params.teaser "cl_version" }}
```

If I also try `{{ .Params.teaser.cl_version }}` I see the error as follows, but it still works:

```
ERROR 2017/06/30 09:56:34 Error while rendering "page": template: project/single.html:10:13: executing "project/single.html" at <.Params.teaser.cl_ve...>: can't evaluate field cl_version in type interface {}
```

This is what the Markdown for the content looks like:

```
---
title:            "Sample Project"
thumbnail:
  cl_version:     "a"
  cl_public_id:   "a"
teaser:
  cl_version:     "1498811499"
  cl_public_id:   "projects/sample-project/kerry-sheep"
date:             "2017-06-30"
description:      "This is the teaser text for a sample project."
prominence:       1
categories:
- "illustration"
---
```

What I am trying to do is access the `cl_version` for the `teaser` and I have read throughout various posts on StackOverflow and others that the approach taken above is the correct one.

I see the error and when I reload the page, I can see the values that I want being printed.

Am I going about this the correct way?

**Comment by bep** [comment]
The error is real enough, we don't make up errors. But please use https://discourse.gohugo.io/ for questions/troubleshooting.
