### ISSUE TITLE
crash/fatal-error/panic with multi-language config.toml & terms.html layout

### ISSUE THREAD

**Issue by MunifTanjim** [gohugoio/hugo#3669]
**Clone & Checkout to example setup branch**:
```
git clone https://github.com/MunifTanjim/hugotest
cd hugotest
git checkout fatal-error-terms-languages
```

**Run**:
```
hugo
```

It will be build alright.

**Add Multiple Language in config**:

- Uncomment the last 2 lines of `config.toml`

**Run again**:

```
hugo
```

There it is... 

```
panic: reflect: Zero(nil) [recovered]
	panic: reflect: Zero(nil)

goroutine 85 [running]:
text/template.errRecover(0xc420597830)
...
...
```

**One of the possible origin point**:

`layouts/_default/terms.html` template content:

```
{{ len ( index .Data.Terms.ByCount 0 ).Pages }}
```

With single language in `config.toml`, it works alright. But with multiple-language `config.toml` hugo crashes.

The `layouts/_default/terms.html` template's output URL is `/tags/`

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. 

I know you could argue that these panics is by definition a bug that we should report in a more user friendly way, but these nil pointers are handled by the Go runtime, and there is nothing we can do about it.
