### ISSUE TITLE
Section seems to conflict with taxonomy when they share the same name

### ISSUE THREAD

**Issue by vjeantet** [gohugoio/hugo#3679]
When a section name has the same value as a taxonomy's term, builded pages seems to conflict.

Issue detected when using nested sections with Hugo v24.1

see https://github.com/vjeantet/hugo-theme-docdock/issues/32 for a full explaination.

Not sure if it's a bug or a know and accepted limitation.

**Comment by bep** [comment]
>Not sure if it's a bug or a know and accepted limitation.

That it is. There are several similar potential naming conflicts. There is an open issue about tracking this and log some kind of warning.

**Comment by vjeantet** [comment]
thanks

**Comment by ringods** [comment]
@bep do you have a pointer of that open issue? I would like to subscribe to notifications for it.
