### ISSUE TITLE
absLangURL should check for valid translation before adding the language prefix

### ISSUE THREAD

**Issue by cosmonawt** [gohugoio/hugo#3683]
I would love the links to only link to content that is already translated.
Say we have this setup:
- The default site language is english
- Some pages which are linked to from the homepage are already translated to German, but not all of them

If I get to the German home page, I want the links in menus to only point to the already translated pages, the other ones should fall back to the default language.
If I have the about page translated, its link should be `/de/about/` but the untranslated blog should use `/blog/`.

I explained this a bit more [here](https://discourse.gohugo.io/t/only-link-to-already-translated-content/7334).

**Comment by bep** [comment]
This isn't possible, I think, but please prove me wrong.

**Comment by cosmonawt** [comment]
I can't think of an easy way, so thats why I was hoping for this to be included in Hugo in the not so far future.

My idea was specifically aimed at menus, so I use that as an example:
If the `URL` of the MenuEntry points to an internal page, Hugo would check all the available translations for that page and see if one matches with the current translation.
`absLangURL` already correctly ignores external links it seems, so theres no problem there.

If it really is not possible to build something "nice and easy" like this, is there a good other way?
One that comes to my mind would be to just add the language prefix to the menus directly and omit `absLangURL`.
