### ISSUE TITLE
--navigateToChanged Not working with Webstorm

### ISSUE THREAD

**Issue by thewebmastercom** [gohugoio/hugo#3687]
As the title says, I cannot get the navigate to changed feature working with Webstorm (jetbrains). Essentially, nothing happens (no change of URL in browser). It just updates the content automatically for URLs already open (i.e. previous functionality works fine).

I have confirmed that it solely relates to webstorm by opening a file in notepad and making a change and everything works as expected (i.e. new webpage loads with the changes).

I am using Windows 10 Pro, Powershell, and Webstorm, and of course Hugo 0.25.

I am not sure what information (if any) might help you, or if it is something that is better directed at Jetbrains. Please let me know if you need anything else from me.

**Comment by bep** [comment]
This is fixed by https://github.com/gohugoio/hugo/commit/7bcc1ce659710f2220b400ce3b76e50d2e48b241

WebStorm behaves strangely, but the above should get it right.
