### ISSUE TITLE
Markdown inline link parsed incorrectly

### ISSUE THREAD

**Issue by NiklasRosenstein** [gohugoio/hugo#3688]
The markdown in my post is the following

```
* PARALLAX &mdash; [Parallax and Distance Measurements](https://gaia.esac.esa.int/documentation/GDR1/datamodel/Ch1/tgas_source.html)
* PHOT_G_MEAN_MAG (Photometric magnitude) &mdash; [Magnitude (astronomy)](https://en.wikipedia.org/wiki/Magnitude_(astronomy))
* L (Galactic Longitude) &mdash; [Galactic coordinate system](https://en.wikipedia.org/wiki/Galactic_coordinate_system)
* B (Galactic Latitude)
```

The second line is parsed incorrectly.

![2017-07-08 22_23_56-nvidia geforce overlay dt](https://user-images.githubusercontent.com/1318438/27988806-2fefa3fa-642c-11e7-95c1-f7e10926d877.png)

If I place it on its own line, it renders fine.

```
[Magnitude (astronomy)](https://en.wikipedia.org/wiki/Magnitude_(astronomy))
```

![2017-07-08 22_24_44-nvidia geforce overlay dt](https://user-images.githubusercontent.com/1318438/27988809-4240bf4e-642c-11e7-86b7-02c284db24c4.png)

*Hugo Static Site Generator v0.20.1 windows/amd64 BuildDate: 2017-04-24T10:51:38+02:00*

**Comment by NiklasRosenstein** [comment]
It works when I escape every underscore in `PHOT_G_MEAN_MAG`. Is that intended?

**Comment by bep** [comment]
> Is that intended?

I believe it is. Words or sentences wrapped in underscores is parsed as italic. If you still believe this is wrong, the correct place to post this would be here: https://github.com/russross/blackfriday/issues (which is the main Markdown renderer used by Hugo).
