### ISSUE TITLE
Docs need updating to include "layout" in front-matter 

### ISSUE THREAD

**Issue by zuriar** [gohugoio/hugo#3691]
In https://gohugo.io/content/front-matter/ there is no reference to the variable "layout" whereas in https://gohugo.io/templates/content/ there is reference to it. This made me question if it was possible, I would suggest adding it in.. thanks

**Comment by rdwatters** [comment]
@zuriar FWIW, this will be included *very* soon in the new docs we are walking on. Also, all docs issues should take place in the new hugoDocs repo: 

https://github.com/gohugoio/hugoDocs

That said, we appreciate the feedback! I can't close this @bep...
