### ISSUE TITLE
Theme removal request

### ISSUE THREAD

**Issue by hk05** [gohugoio/hugo#3697]
Please remove hugo-theme-learn from the themes section, as it is not working properly. At least not in the current release (0.25). The theme has been forked to docdock, which *is* working. 

Second request: in the showcase section, remove the phrase "with source", as many of the cases don't publish the source. Better yet: require all published showcases to include a link to the source code/config.

**Comment by anthonyfok** [comment]
> Please remove hugo-theme-learn from the themes section, as it is not working properly. At least not in the current release (0.25). The theme has been forked to docdock, which is working.

Thanks for the heads up!  But, well, there are still some on-line web services which are not using the latest versions of Hugo, and also we understand that it takes time for Hugo theme authors to catch up.  Wouldn't you think it a little bit too drastic an action to remove a theme from the https://themes.gohugo.io/ website prematurely?  :wink:

But yes, your concern has been relayed to hugo-theme-learn's author who will be upgrading the theme in the near future.  It is not too trivial, as the theme author replied: "This issue will need a lot of work to be done (it's like a complete rewrite). We need to change menu, automatic arrows and breadcrumbs display."

> Second request: in the showcase section, remove the phrase "with source", as many of the cases don't publish the source. Better yet: require all published showcases to include a link to the source code/config.

With the all new https://gohugo.io/ website, this is no longer an issue, but thanks for mentioning it.  :wink:

**Comment by hk05** [comment]
Hi Anthony,

Thanks for taking the time to reply. And yes, I noticed the new website, it looks great! Well done! :-)

BR,

Hans

**Comment by matcornic** [comment]
@hk05 v2 is out : https://github.com/matcornic/hugo-theme-learn & https://learn.netlify.com/en/ ;)

**Comment by bep** [comment]
@vjeantet just a little heads up about the above and what seems like copy-and-paste of your (great) work without proper credits, one random example:

https://github.com/vjeantet/hugo-theme-docdock/blob/master/layouts/shortcodes/children.html
https://github.com/matcornic/hugo-theme-learn/blob/master/layouts/shortcodes/children.html

I know this open-source thing is hard when forks happen.

**Comment by matcornic** [comment]
@bep he's credited here : https://learn.netlify.com/en/credits/ and already thanked here https://twitter.com/matcornic/status/899399049010442240 . 

Bu you were right to write this message. I understand it was not obvious enough, I just added a credit in the README and added him in the license !

**Comment by matcornic** [comment]
And btw, @vjeantet if you want to be credited elsewhere, let me know.

**Comment by vjeantet** [comment]
@bep : no pb @matcornic and I are in touch.

**Comment by vjeantet** [comment]
I fork, he forks, we fork - this is OSS :-)
