### ISSUE TITLE
GitInfo not getting fields (.AuthorName, .Subject, etc) on Linux (and also failing with symlinks)

### ISSUE THREAD

**Issue by rcoreilly** [gohugoio/hugo#3698]
I have EnableGitInfo=true (and also used the command-line switch),  and have included:
{{ .GitInfo.AuthorName }} in my footer.html -- it works perfectly locally on my mac, but on our linux (ubuntu) server, running 16.04 I believe, it fails to find the git info:

WARN 2017/07/13 12:47:01 Failed to find GitInfo for "usr/local/labwiki/content/help/getting_started.md"
INFO 2017/07/13 12:47:01 found taxonomies: map[string]string{"tag":"tags", "group":"groups"}
WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.

ERROR 2017/07/13 12:47:01 Error while rendering "page": template: /usr/local/labwiki/layouts/_default/single.html:14:3: executing "/usr/local/labwiki/layouts/_default/single.html" at <partial "footer.html...>: error calling partial: template: partials/footer.html:3:121: executing "partials/footer.html" at <.GitInfo.AuthorName>: can't evaluate field AuthorName in type *gitmap.GitInfo

is it a git version issue?  on linux:
git --version
git version 1.9.1

on mac:
git --version
git version 2.11.0 (Apple Git-81)

both are running hugo 0.24.1

no spaces in file names..

git works fine for showing me the log of that getting_started.md file.

thanks for any insight you might have on how to get this working!

**Comment by rcoreilly** [comment]
I see that this a partial duplicate of bug #2760 -- our /usr directory is a symlink -- would be great to include a mention of this limitation in the docs at https://gohugo.io/extras/gitinfo/ until the bug is fixed.

However, even now when I run it from a directory without the symlink problem, it seems that the fields of .GitInfo are not being created somehow.  I updated to the latest 25.1 version of hugo, running on linux, 64bit, and any attempt to reference e.g.,  .AuthorName or .Subject information in .GitInfo fails with the same error as above:  <.GitInfo.AuthorName>: can't evaluate field AuthorName in type *gitmap.GitInfo

BUT, if I just include .GitInfo without any field, it does not give an error, and the pages include this kind of information:

{8bcf90517faa6a858ef52d29500c706d77d579b8 8bcf905 fixlinks run on all pages to use just the page na
me without any path -- much more robust once moving pages around Randall C. O&#39;Reilly randy.oreilly@colorado.edu 2017-06-29 14:48:59 &#43;0900 &#43;0900}

so it is definitely getting the information, but somehow missing the fields!

again this same content all works correctly as documented on my mac laptop.

**Comment by bep** [comment]
Duplicates #2760
