### ISSUE TITLE
Code blocks without language look bad

### ISSUE THREAD

**Issue by DanielGibson** [gohugoio/hugo#3699]
If I use a code fence without specifying a language for the highlighter to use (just ` ``` ` instead of ` ```c `), or use the standard markdown four-space-indent-thing, the resulting "code block" doesn't look very good.
The html generated is just `<pre><code> ... </code></pre>`, i.e. the `<div class="highlight">` around it is missing.  
Through that div I can create a nice block with rounded edges and a background color, a bit indented from the normal text around it etc - without that div I just get monospaced text, maybe with some background color, but not as a block.

My workaround is to pass "text" as the used language (` ```text`), so pygments will accept it but not do any real highlighting, but I'd much prefer if (like basically everywhere else where those github-style codefences are supported) I didn't have to.

So it'd be awesome if hugo either added the `<div class=highlight>` around the `<pre><code>` block or passed language "text" to pygments if none is given.

Thanks!

**Comment by DanielGibson** [comment]
Screenshot of the issue (uses a modified lithium theme):

![codeblocks](https://user-images.githubusercontent.com/1216493/28208780-b4c7246a-688f-11e7-8247-d40012ec1356.png)

**Comment by DanielGibson** [comment]
this issue persists (no, using the new highlighter is currently no option for me, it seems to behave differently, I think I'd even have to change my markdown to get it formatted correctly)

**Comment by halogenica** [comment]
I agree, but wanted to be more specific (and suggest renaming the title of this bug). Without providing a language when specifying the code fence, it always defaults to no syntax highlighting (or is treated as regular text). There is an option to guess the intended ```pygmentsCodefencesGuessSyntax = true``` but in my expierience _**this doesn't work**_; it never results in syntax highlighting for me. I've tried both with Chroma and older Pygments. I think this missing feature is the core issue.

**Comment by DanielGibson** [comment]
I wouldn't expect any syntax highlighting (via autodetection of the source language or whatever), just that `<div class=highlight>` `</div>` is around the `<pre><code>` ... `</code></pre>` block, so it looks like a code block with plain text.

**Comment by halogenica** [comment]
I see, you just specifically want to be able to customize the style the code block using the 'highlight' class and not just using the pre/code tags. That clears things up for me, thanks.

**Comment by DanielGibson** [comment]
The main thing is, I want a `<div>` around that block, it would be very handy if it's of the highlight class, but any other (unique) class name I can reference in the CSS would work as well.
I need the `<div>` block so I can specify styling for the code block (background etc).
Just `<pre>` and `<code>` is not sufficient, as that doesn't produce a "block" - see my screenshot in https://github.com/gohugoio/hugo/issues/3699#issuecomment-315327277

**Comment by Jos512** [comment]
Perhaps adding a `<div>` to a code block is needed, but it shouldn't be named `highlight`.

That's because the `highlight` `<div>` class is explicitly added by Hugo when the code block contains a language that is highlighted (as opposed to a plain text code block without syntax highlighting).

It will be code breaking for Hugo users if the `highlight` class also suddenly appear when the code block doesn't use syntax highlighting.

----

> Through that div I can create a nice block with rounded edges and a background color, a bit indented from the normal text around it etc - without that div I just get monospaced text, maybe with some background color, but not as a block.

Is there a strong reason why styling the code block with HTML selector doesn't work for you?

I'm asking because of two reasons. I never had trouble styling code blocks without classes. And what you're asking for is not how Markdown typically works -- from guides I've looked up (like [this one](https://daringfireball.net/projects/markdown/syntax#precode)) Markdown *should* render without a class when you just use ` ``` ` or `  ~~~ `. 

If Hugo should override the default behaviour of the BlackFriday Markdown processor, then I think we need a strong reason why. That's because patching BlackFriday gives ongoining maintenance work for the Hugo team. If I cannot be fixed with CSS selectors, JavaScript, or Hugo's shortcodes then we probably need to add it to Hugo.

**Comment by h4tr3d** [comment]
Issue still present.
