### ISSUE TITLE
metaDataFormat not in use anymore

### ISSUE THREAD

**Issue by arikroc** [gohugoio/hugo#3706]
in config.toml I have

MetaDataFormat = "yaml"

when I do hugo new, I get a file with

+++

(i.e. TOML)

(also, date shows as blank i.e. date = "" instead of being auto filled with creation time, tho maybe that's not a bug just a new feature I'm unaware about)

**Comment by bep** [comment]
In short, you will now get the metadata format of your archetype files. See #3632 -- but we should do something with this `metaDataFormat` config value we're not using anymore. Not sure what.

**Comment by blueyed** [comment]
This should get re-opened.
There is a PR for docs at https://github.com/gohugoio/hugoDocs/pull/554, but occurences in this repo here should get removed, too.
