### ISSUE TITLE
now not available in translations

### ISSUE THREAD

**Issue by roidelapluie** [gohugoio/hugo#3712]
I have
`This page has been generated on {{.Now.Format "2006-01-02"}}.`

in my translations.

But .Now is deprecated:
`ERROR 2017/07/18 07:34:25 Page's Now is deprecated and will be removed in Hugo 0.26. Use now (the template func).`

But :

`This page has been generated on {{now.Format "2006-01-02"}}.`

is not working:

```
Error: Error building site: Failed to load translations in file "en.yaml": unable to parse translation #2 because template: This page has been generated on {{now.Format "2006-01-02"}}.
:1: function "now" not defined
map[id:footer-date translation:This page has been generated on {{now.Format "2006-01-02"}}.
]
```

**Comment by MunifTanjim** [comment]
This can be closed.
