### ISSUE TITLE
`.TableOfContents` is empty when rendering `.mmark` files.

### ISSUE THREAD

**Issue by tammersaleh** [gohugoio/hugo#3719]
### This works correctly with regular `.md` files:

**`layouts/index.html`**:

```
<main>
  <article>
    {{ .Content }}
  </article>
  <aside>
    {{ .TableOfContents }}
  </aside>
</main>
```

**`content/_index.md`**:
```
---
title: "Book"
date: 2017-07-19T13:28:32-07:00
draft: false
---

# one

# two
```

Rendered **`public/index.html`**:

```
<main>
  <article>


<h1 id="one">one</h1>

<h1 id="two">two</h1>

  </article>
  <aside>
    <nav id="TableOfContents">
<ul>
<li><a href="#one">one</a></li>
<li><a href="#two">two</a></li>
</ul>
</nav>
  </aside>
</main>
```

(The `#TableOfContents` element is correctly rendered)

### ...but fails with `.mmark`:

Rename `content/_index.md` to `content/_index.mmark`, and the rendered `public/index.html` becomes:

```
<main>
  <article>
    <h1 id="one">one</h1>

<h1 id="two">two</h1>

  </article>
  <aside>

  </aside>
</main>
```

**Comment by tsaleh** [comment]
(might just be too hard to fix, but would be good to have documented)

**Comment by GregorioMartinez** [comment]
The mmark processor used, https://github.com/miekg/mmark , doesn't support tables of content yet.

An issue was opened https://github.com/miekg/mmark/issues/120 

+1 on having this documented

**Comment by digitalcraftsman** [comment]
**Note for maintainers:** 

- [ ] don't forget to remove the note added in https://github.com/gohugoio/hugoDocs/pull/229 that informs users about this issue

**Comment by jdhao** [comment]
Any news about table of contents for mmark file types?  Is it still not supported?
