### ISSUE TITLE
Docs and implementation disagree on uglify behavior for _index.md

### ISSUE THREAD

**Issue by jpco** [gohugoio/hugo#3720]
Putting this here rather than the docs repository because I'm not sure whether this is an issue with the documentation or the code.

The [ugly URLs](https://gohugo.io/content-management/urls/#ugly-urls) section of the docs claims the file with path `content/about/_index.md` will be rendered to `/about/index.html`.  The actual behavior of hugo (v0.25.1 on Linux) renders it to `/about.html`.

In my opinion the docs describe the correct behavior, for a few reasons: it matches the default behavior of index.html in other web platforms/servers such as Apache, i.e., listing the contents of the directory; it removes awkward "holes" in paths (where should  the path `/about/` point to if not the directory listing?), and makes relationships between section lists and individual pages clearer; and (admittedly, this last one is unlikely to show up in practice) it removes ambiguity in the case where both `content/about/_index.md` and `content/about.md` exist.  The fact the documentation got it wrong in the first place is, I think, evidence the behavior implemented is counterintuitive.

That said, reading older forum posts & issues, it looks like people have asked related questions and been told the `/about.html` behavior is the intended one.  In that case, the documentation just needs to be updated to match.

**Comment by bep** [comment]
The documentation is wrong. You may argue that it should behave differently, but that would be a glass house breaking change.

**Comment by rdwatters** [comment]
I would close this if I had the ability to @bep. Opened new issue: 

https://github.com/gohugoio/hugoDocs/issues/6

@jpco Thank you for catching this. Driving cross country right now but I will fix this tonight when I get to Texas.
