### ISSUE TITLE
hrefTargetBlank not taking effect

### ISSUE THREAD

**Issue by fabianofranz** [gohugoio/hugo#3723]
`hrefTargetBlank = true` in my `config.toml` is not turning external links into `target="_blank"`.

```
$ hugo version
Hugo Static Site Generator v0.26-DEV linux/amd64 BuildDate: 2017-07-14T00:36:28-03:00
```

Happens both on Hugo installed via `go get` (my dev machine) and via `snap` (on Travis).

Side note: thanks a lot @spf13 @bep and other folks for Hugo! Superb set of features and amazingly fast. I'm using it along with Zurb Foundation to build the website of our overlanding trip in http://6overlanders.com/. 

Thanks!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. I know you think this is a bug, but we have had this issue reported many times before, and it is always some issue with the end user's setup.
