### ISSUE TITLE
Add a --content-age-filter flag to hugo server

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3724]
The flag name needs a better name, but the idea comes from @jgreely 's comment in this thread: https://discourse.gohugo.io/t/desktop-code-text-editor-of-choice/7525/16

There may be more permanent solutions to the "really big sites" problem, but this should be easy to implement and of big value for many.

The idea is that for really big sites, 10-100Ks of pages, you don't mind it taking many seconds/minutes when running the production build (on some CI server), but you want to get snappy previews when doing design/new article editing.

So if I could say:

```
hugo server  --content-age-filter=30
```

And only get the last month's worth of content (but all list content, i.e. `_index.md`).

But note that this will only work if we can use the operating system's timestamp for the files. We could read front matter dates, but that throws away some of the value.

**Comment by rdwatters** [comment]
This would be a really cool feature. Just some naming ideas* for posterity:

* `--contentAge=`
* `--contentRecency=`
* `--contentSince=`
* `--contentStarting=`
* `--latestContent=`
* `--maxAge=`
* `--maxAgeInDays=`
* `--mostRecent=`
* `--recentContent=`

\* Assuming the idea isn't a filter (i.e, one or more parameters) as much as it is a cutoff; i.e., "Hugo, only render the last 30 days of content."

**Comment by jgreely** [comment]
I should point out that the way I'm doing it with my script is `--maxPerSection=50`; if I'm testing theme changes, something like `--maxAge=14` might not render any pages in a section affected by the change. If I had a vote, I'd of course vote for "both", but my way would definitely be more complicated, especially with nested sections.
