### ISSUE TITLE
Guillemets (quotes) with spaces

### ISSUE THREAD

**Issue by aurelberra** [gohugoio/hugo#3725]
In 2014 already support was added for angle quotes via Black Friday (#686). These are the French *guillemets*, except that you need non-breakable spaces in French: not "this" nor «that» (as it becomes with `angledQuotes: true` in the config file), but «&nbsp;so&nbsp;».

This option would make a great difference for French users of Hugo!

**Comment by bep** [comment]
I added the "angled quotes" to Black Friday, and I had my own needs (I'm from Norway) in mind when doing so. Could you open up a Black Friday issue with a link back to this issue? 

https://en.wikipedia.org/wiki/Guillemet

**Comment by bep** [comment]
Also see https://github.com/russross/blackfriday/issues/380

**Comment by bep** [comment]
Reopen this: I need to add a config option in Hugo as well.
