### ISSUE TITLE
building site on Mac fails in directory whose name contains accents

### ISSUE THREAD

**Issue by jgreely** [gohugoio/hugo#3726]
[Mac OS X 10.11 (at least), Hugo 0.25.1]

Building a site fails in a directory whose name contains accented characters. See [this thread](https://discourse.gohugo.io/t/solved-hugo-becomes-strange-dont-generate-pages-without-resaving-them/7535) on the forums for details.

I couldn't reproduce his problem when I checked his site out from Github into a directory named Le-Desert-En-Ville, but when I renamed it to Lë-Désert-En-Villē, it looks like it was unable to convert the absolute path to a relative one, as seen in the diff of `public/index.xml`:

```
diff -r public-/index.xml public/index.xml
4c4
<     <title>Ateliers on My New Hugo Site</title>
---
>     <title>My New Hugo Site</title>
6c6
<     <description>Recent content in Ateliers on My New Hugo Site</description>
---
>     <description>Recent content on My New Hugo Site</description>
14c14
<       <link>/voyageurs/juliette-kempf/</link>
---
>       <link>/l%C3%AB-d%C3%A9sert-en-vill%C4%93/content/voyageurs/juliette-kempf/</link>
17c17
<       <guid>/voyageurs/juliette-kempf/</guid>
---
>       <guid>/l%C3%AB-d%C3%A9sert-en-vill%C4%93/content/voyageurs/juliette-kempf/</guid>
...
```

**Comment by agucova** [comment]
I had the exact the same issue, could reproduce.
The folder containing the hugo directory had a spanish tilde, and the contents weren't being generated, I changed the tilde and it now works.

Same errors as the forum thread.
