### ISSUE TITLE
Customize a Theme link is dead

### ISSUE THREAD

**Issue by JulianNorton** [gohugoio/hugo#3729]
> For further theme customization, see Customize a Theme.
`https://gohugo.io/getting-started/quick-start/themes/customizing/#readout`

bottom of https://gohugo.io/getting-started/quick-start/

I'm not sure what the correct link should be

**Comment by digitalcraftsman** [comment]
@bep should know it best as the author of the new quickstart guide.

**Comment by bep** [comment]
OK, I fixed it here: https://github.com/gohugoio/hugoDocs//commit/d51397c2fe1d04c0da965f66eb9faadec91d7d1d
