### ISSUE TITLE
Reduce Docker image size further using "multi-stage builds" in Docker CE 17.06

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugo#3730]
Thanks to @ellerbrock's optimization effort in #3666 and #3674, the Hugo Docker image generated using the Dockerfile was greatly reduced from 428MB to 277MB, but it still looks a bit big.

It turns out that about 250MB is taken up by /usr/local/go, which is needed for building Hugo, but not needed for running Hugo.  So, that got me wondering: Could we build the Hugo Docker image with golang:alpine3.6 (258 MB) like we do now, but use the much smaller alpine:latest (3.96 MB) for the running image?

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
golang              alpine3.6           9f687d7d2a96        3 weeks ago         258 MB
alpine              latest              7328f6f8b418        3 weeks ago         3.96 MB
```

That way, perhaps future Hugo Docker images could be smaller than 25 MB!

It turns out that it was not a trivial thing to do before, but with the hot new Docker CE 17.06 (released 2017-06-28) and its "Multi-stage Builds" feature, it looks like this goal is within reach:

* [Even Smaller Docker Image Sizes](https://blog.replicated.com/optimizing-docker-images-with-multi-stage-builds/)
* [Announcing Docker 17.06 Community Edition (CE) - Docker Blog](https://blog.docker.com/2017/06/announcing-docker-17-06-community-edition-ce/)

@ellerbrock, could you please look into this when you are free?  (No hurries though, as I am sure it will take a while for Docker CE 17.06 to propagate, e.g. Debian is still at Docker 1.13.1 released in February 2017.)  Many thanks!

**Comment by ellerbrock** [comment]
Hi @anthonyfok, good idea.
There are a few ways how we could archive this:

1.) In most cases i build and cleanup inside the container. In that case its isolated in the docker container without any outside dependencies. The important part here is to install and cleanup in one RUN command to avoid hitting the docker cache layer to keep the container size small.

2.) Another solution is to setup a proper CI pipeline (https://docs.travis-ci.com/user/languages/go/) and just copy the executable inside the container. I would only use such a solution if all steps are transparent to ensure that no malicious stuff finds a way inside the container and my network (with [Travis](https://travis-ci.org/) which you use anyway this is possible).

3.) We could also setup a [Automatic Build Task](https://docs.docker.com/docker-hub/builds/) on Docker Hub and define a branch which will trigger a new build with each code push. This also makes it more transparent. You can find examples on my Docker Hub Account [@ellerbrock](https://hub.docker.com/u/ellerbrock/), all my containers are build this way.
I could help with the setup an and automation it if you like. 
Would be nice anyway to have an official Hugo Docker Container available.

Let me know which of those solutions you and your team would prefer to use ...

Cheers Maik

**Comment by anthonyfok** [comment]
> There are a few ways how we could archive this till the new feature is official supported in Docker:

Thanks @ellerbrock!  I'd say we just wait until Multi-Stage Builds official lands in Docker Hub, which should happen really soon now, I guess some time this August?  See docker/hub-feedback#1039

We are in no real hurry to shrink the Docker image size to &lt; 25MB, so let's just take our time, wait, and do it properly _once_ and for all when it is supported officially in Docker Hub infrastructure where we can use a very clean and straightforward Dockerfile.  No need for intermediate hacks that we'd have to throw away in a month or two anyway.

> 1.) In most cases i currently build and cleanup inside the container. In that case its isolated without any further outside dependencies. The important part here is to install and cleanup in one RUN command to avoid hitting the cache layer to keep the container size small.

Yes, I see you are already doing that very diligently.  :-)

> 2.) Another solution is to setup a proper CI pipeline (https://docs.travis-ci.com/user/languages/go/) and just copy the executable inside the container. I would only use such a solution if all steps are transparent to ensure that no malicious stuff finds a way inside the container and my network (with Travis which you use anyway this is possible).

Nah.  I prefer what you currently have in Dockerfile, i.e. building from source, for maximum compatibility and security.

> 3.) We could also setup a Automatic Build Task on Docker Hub and define a branch which will trigger a new build with each code push. This also keep it transparent. You can find examples on my Docker Hub Account @ellerbrock, all my containers are build this way. I could help with the setup an and automation it if you like. Would be nice anyway to have an official Hugo Docker Container available.

That's a nice idea!  What do you think, bep and @spf13?

**Comment by anthonyfok** [comment]
Hi @ellerbrock,

Thank you for drastically shrink the image from 277MB to 27MB!  "Extreme" indeed!

You might like to consider applying this small change to further shrink the image to 20.5MB with the use of `-ldflags '-s -w'`, see commit https://github.com/gohugoio/hugo/commit/9ed48c1c9ae4cd9390f5ef88c8b2b6624e9e247d

```
  -s	disable symbol table
  -w	disable DWARF generation
```

(I initially ran `strip` on it, but it turns out Go can omit those symbol table and DWARF all by itself.)

Cheers,
Anthony

**Comment by ellerbrock** [comment]
thanks for mentioning in https://github.com/dependencies-io/www.dependencies.io/issues/15 👍

**Comment by ellerbrock** [comment]
hi @anthonyfok,

i would say we could close this issue, what do you think?

cheers maik
