### ISSUE TITLE
Make SummayLength configurable 

### ISSUE THREAD

**Issue by Shuenhoy** [gohugoio/hugo#3734]
I saw the code "var SummaryLength = 70" in the hugo/helpers/content.go, however, I use Chinese and that length is too short. I Hope it can be configurable. Thanks!

**Comment by bmon** [comment]
@bep Hi, I'd like to have a go at this issue. Any tips on where to get started?

**Comment by bep** [comment]
@bmon great! I suggest you
 
* Add a new config option named `summaryLength`, default 70.
* Add it as a variable in `helpers.ContentSpec`. There are other vars in this struct that gets their value from the config, so "follow one of them..." to see where the default config is created.
