### ISSUE TITLE
I see the "Aw, Snap!" Chrome crash message when accessing Gohugo official docs website

### ISSUE THREAD

**Issue by cw1427** [gohugoio/hugo#3740]
https://gohugo.io/functions/ got broken,  I can't access it a few days. I suggest to generate a offline version docs, or provide a function to generate it real time.
![gohugo](https://user-images.githubusercontent.com/4980410/28602115-d9615378-71ee-11e7-8816-7a95a6fcb0a2.png)

**Comment by anthonyfok** [comment]
Hi @cw1427, thank you for your feedback.

The https://gohugo.io/ website has been up all these time, and is accessible fine here in North America as well as in Europe.

Are you accessing the website from within the People's Republic of China?  Could it be that Netlify, the web platform where the https://gohugo.io/ website is hosted, got blocked by the Great Firewall of China, at least in your city?

**Comment by anthonyfok** [comment]
> I suggest to generate a offline version docs, or provide a function to generate it real time.

That feature has been available since Day One (or as far as I can remember).  After you have fetched the Hugo source, go inside $GOPATH/src/github.com/gohugoio/hugo and run `hugo server -s docs`, and access your very own copy of Hugo official website at http://localhost:1313/.

Alternatively, assuming you didn't build Hugo from source, you may also run `git clone https://github.com/gohugoio/hugoDocs.git`, change into the hugoDocs directory, then run `hugo server` there.

By the way, there is a QQ group for Hugo set up by @coderzh:

欢迎加入Hugo交流QQ群：512499080

Perhaps you can find out more from others in China whether they can access https://gohugo.io/ or not.

Hope this helps!

**Comment by bep** [comment]
>git clone https://github.com/gohugoio/hugoDocs.git

```
git clone --recursive https://github.com/gohugoio/hugoDocs.git
```

Is the correct command.

**Comment by bep** [comment]
I have tested a few of the options here OK:

https://www.websitepulse.com/tools/china-firewall-test

**Comment by anthonyfok** [comment]
Hi @cw1427,

Friends from the QQ's Hugo 交流群 said, “能访问，墙内”

so it seems you are not "walled in" and you can access Hugo's official website from China.  Yay!

I just looked at your screenshot more carefully, and realized it was not a "website inaccessible" error, but rather, “喔唷，崩溃啦！”, the equivalent of "Aw, Snap! — Something went wrong while displaying this web page", i.e. your copy of Google Chrome (or Chromium-based browser) crashed while trying to load the page.

All I can say it: It works fine here.  Could you try another web browser, say, Firefox?

Google offers their solution here: https://support.google.com/chrome/answer/95669?visit_id=1-636366527668612171-1897872665&p=e_awsnap_rl&rd=1&hl=zh-Hans

I don't know if you can see that page or not, so I have reproduced it below:

----

# 解决“喔唷，崩溃啦！”网页崩溃问题和其他网页加载错误

您之所以会看到“喔唷，崩溃啦”这一错误消息，而没有看到相关网页，是因为 Chrome 在加载网页时遇到问题。

请试试以下解决方法。

### 第 1 步：检查互联网连接状况
确保您的设备已连接到数据网络或 Wi-Fi。

### 第 2 步：清除缓存
Chrome 可能存储了阻止浏览器完整加载该网页的信息。

清除缓存和 Cookie，然后尝试重新加载该网页。

### 第 3 步：关闭其他标签页、扩展程序和应用
您的设备可能内存不足，无法在运行应用、扩展程序和其他程序的同时加载该网站。

要释放内存，请执行以下操作：

* 关闭除显示此错误消息的标签页以外的所有其他标签页。
* 退出正在运行的其他应用或程序，并暂停所有应用或文件下载任务。
* 在计算机上，卸载 Chrome 中不必要的扩展程序。了解如何卸载扩展程序。

在出现错误的标签页上，尝试重新加载该网页。

### 第 4 步：重新启动设备
程序或应用有时会影响网页的正确加载。

1. 重新启动计算机或移动设备。
1. 尝试重新加载该网页。

### 第 5 步：更新 Chrome
1. 打开 Chrome。
1. 依次点击右上角的“更多”图标 ⋮  &gt; 设置。
1. 依次点击左上角的“菜单”图标 ☰ &gt; 关于 Chrome。
1. Chrome 会自动检查是否有可用更新（您可能需要等待几秒钟才能看到）。
    * 如果有更新，您会看到重新启动选项。
    * 如果没有任何说明，则表示您的 Chrome 已是最新版本。

### 第 6 步：检查是否存在恶意软件
如果您使用的是 Windows 设备，请使用 Chrome 清理工具帮助您找到并移除垃圾软件。

如果您使用的是 Mac 或 Linux 计算机，请查看我们有关如何发现和移除垃圾软件的建议。

## 仍无法解决问题？
如果其他网站都能正常打开，只有某个网站发生崩溃，则问题可能是由该网站造成的。

* 如果您尝试了重新加载却仍然无法打开该网站，请点击发送反馈告知我们。
* 开启自动报告错误功能来帮助我们更快地解决页面崩溃问题，或者向 Chrome 报告此问题。
* 联系网站所有者并报告此问题。

您也可以在 Chrome 帮助论坛中发帖寻求帮助。

----

Wait, I just noticed you are using Google Hangouts, so no issue of being "walled in".  (Perhaps you are outside of the "wall"...)  Sorry for my misdiagnosis!

**Comment by cw1427** [comment]
Thanks for verification.  Yes my hangout works well on Chrome and I'm out of the wall.  But still could not access the hugo docs website.  After test access in firebox and IE,  both of them are normal.  I have no idea why my Chrome could not render hugo official doc. website instead of "Aw, Snap!"

I will try to clean the cache about the Chrome for test.

**Comment by anthonyfok** [comment]
> I will try to clean the cache about the Chrome for test.

Thanks!  Did it work?

**Comment by cw1427** [comment]
Unfortunately no.  I use switchOmega Chrome plugin, a few days ago, it works well, but one day the gohugo doc. website suddenly got broken.  But I found a very strange config item appeared in the swithOmega has something to do with gohugo.io,  I'm curious why.  Never mind, will update once got fix.  Thanks a lot.  BTW,  gohugo is perfect, awesome!


![gohugo_issue](https://user-images.githubusercontent.com/4980410/28699105-3bd9867e-737a-11e7-807f-cab379ea4cdd.PNG)

**Comment by anthonyfok** [comment]
If you haven't done so yet, try upgrading to Google Chrome 60.0.3112.78.
This link http://humanum.arts.cuhk.edu.hk/Lexis/lexi-mf/search.php?word=%E5%BC%A6 was crashing my previous Chrome 59, but now working perfectly, so that might do the trick.

**Comment by bep** [comment]
Continue this at https://discourse.gohugo.io/ for questions/troubleshooting.
