### ISSUE TITLE
Some template functions aren't part of a namespace

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugo#3743]
This issue also proposes where these functions shall belong to. I took the freedom to propose an entirely new namespace for some functions.

Feel free to comment.

### `time` namespace

- time
- unix
- adddate

### `collections` namespace

- range

### `fmt` namespace

- format

### New `menus` namespace 

- haschildren
- hasmenucurrent
- ismenucurrent

### `partial` namespace

- render

---

### remaining functions

- get
- getpage
- len
- param
- scratch
- with

**Comment by moorereason** [comment]
Some of these are methods and should not be included in the functions section of the docs.  We need to come up with a different strategy for documenting object methods.

- `Time.Unix` and `Time.AddDate` are methods on a Go [time.Time](https://golang.org/pkg/time/#Time) object.
- The "menus" items you list are methods of the Hugo [MenuEntry](https://godoc.org/github.com/gohugoio/hugo/hugolib#MenuEntry) object.
- I'm assuming `Get`, `GetPage`, and `Params` are methods from different objects in the `hugolib` package.

**Comment by bep** [comment]
For the methods, I suggest creating sub-sections below /functions for `Page`, `Menu`, `Time` (note the upper case first letter). That is a start.
