### ISSUE TITLE
tpl: TestMethodToName fails with gccgo

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugo#3744]
With gccgo-7:

```
$ go-7 version
go version go1.8.1 gccgo (Debian 7.1.0-10) 7.1.0 linux/amd64
```

`go-7 test` produces the following error:

```
=== RUN   TestMethodToName
--- FAIL: TestMethodToName (0.00s)
        Error Trace:    templatefuncRegistry_test.go:32
	Error:		Not equal: "MyTestMethod" (expected)
			        != "$thunk0" (actual)
		
FAIL
FAIL	github.com/gohugoio/hugo/tpl/internal	0.916s
```

Is it safe to just skip the test on gccgo with `// +build !gccgo` in tpl/internal/templatefuncRegistry_test.go (which contains only one test, TestMethodToName())?

Or is this a concern that may cause a gccgo-compiled Hugo to fail with certain templates?

Many thanks!

References:

* https://github.com/golang/go/issues/3901
* https://bugs.launchpad.net/gocheck/+bug/1250253

**Comment by bep** [comment]
>Or is this a concern that may cause a gccgo-compiled Hugo to fail with certain templates?

No, then there would be more template func test failures. I don't remember the code path here, but I expect there to be a symmetry here, so `$thunk0` is an identifier good as any.

**Comment by anthonyfok** [comment]
>Or is this a concern that may cause a gccgo-compiled Hugo to fail with certain templates?
>> No, then there would be more template func test failures. I don't remember the code path here, but I expect there to be a symmetry here, so `$thunk0` is an identifier good as any.

Thank you for your reassurance!  I'll file a PR to accommodate gccgo in TestMethodToName then.
