### ISSUE TITLE
How do I set custom variables?

### ISSUE THREAD

**Issue by aanomm** [gohugoio/hugo#375]
Hi. New to Hugo, but love it so far. Can anyone help my understand custom variables better? I'd like to set some site-wide custom variable to call into templates: for example, a Twitter username that will be used on the Homepage, and the footer of single posts.  I'm using the default config.toml file for config.

**Comment by dguo** [comment]
For anyone else who stumbles on this issue in the future, the relevant section in the docs is [here](https://gohugo.io/variables/site/#the-site-params-variable).

**Comment by zwass** [comment]
Correct link as of this comment: https://gohugo.io/variables/site/#the-siteparams-variable
