### ISSUE TITLE
relLangURL does not use the correct slug

### ISSUE THREAD

**Issue by rauberdaniel** [gohugoio/hugo#3751]
When using custom slugs (defined in the frontmatter of the specific page), `relLangURL` will use the correct language prefix (e.g. `en/` or `de/`) but not the correct slug: it will always use the filename of the content file.

Example:
Site with languages `en` and `de`

`content/photos.en.html` does not have a specific slug 
`cotnent/photos.de.html` has `slug: "fotos"` specified in frontmatter

URLs created by `{{"photos/" | relLangURL}}` will now be `en/photos/` (correct) and `de/photos/` (wrong, should be `de/fotos/`).

**Comment by bep** [comment]
`relLangURL` is stateless -- it has no information about which page you're talking about. 
Please use https://discourse.gohugo.io/ for further questions/troubleshooting.
