### ISSUE TITLE
Create a list of the core third party libraries we use

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3754]
We get very much for free from Blackfriday and many other libraries -- they should be mentioned and thanked in README and docs site.

**Comment by jorinvo** [comment]
As quick reference, these are all directly referenced dependencies. Guess only a selection of the ones most dependent on can be explicitly thanked in the README though.

https://github.com/BurntSushi/toml
https://github.com/PuerkitoBio/purell
https://github.com/bep/gitmap
https://github.com/bep/inflect
https://github.com/chaseadamsio/goorgeous
https://github.com/dchest/cssmin
https://github.com/eknkc/amber
https://github.com/fortytw2/leaktest
https://github.com/fsnotify/fsnotify
https://github.com/gorilla/websocket
https://github.com/hashicorp/go-immutable-radix
https://github.com/kardianos/osext
https://github.com/kyokomi/emoji
https://github.com/miekg/mmark
https://github.com/mitchellh/mapstructure
https://github.com/russross/blackfriday
https://github.com/spf13/afero
https://github.com/spf13/cast
https://github.com/spf13/cobra
https://github.com/spf13/fsync
https://github.com/spf13/jwalterweatherman
https://github.com/spf13/nitro
https://github.com/spf13/pflag
https://github.com/spf13/viper
https://github.com/yosssi/ace
https://gopkg.in/yaml.v2

**Comment by bep** [comment]
* https://github.com/BurntSushi/toml
https://github.com/PuerkitoBio/purell
https://github.com/bep/gitmap
https://github.com/bep/inflect
* https://github.com/chaseadamsio/goorgeous
https://github.com/dchest/cssmin
* https://github.com/eknkc/amber
https://github.com/fortytw2/leaktest
* https://github.com/fsnotify/fsnotify
https://github.com/gorilla/websocket
https://github.com/hashicorp/go-immutable-radix
https://github.com/kardianos/osext
* https://github.com/kyokomi/emoji
* https://github.com/miekg/mmark
https://github.com/mitchellh/mapstructure
* https://github.com/russross/blackfriday
* https://github.com/spf13/afero
https://github.com/spf13/cast
* https://github.com/spf13/cobra
* https://github.com/spf13/fsync
https://github.com/spf13/jwalterweatherman
https://github.com/spf13/nitro
https://github.com/spf13/pflag
* https://github.com/spf13/viper
* https://github.com/yosssi/ace
https://gopkg.in/yaml.v2


I have put an asterisk before what I consider drives the core of Hugo. But @jorinvo -- I suspect there are some left out, I cannot see go-i18n ...

**Comment by jorinvo** [comment]
@bep you're right, sorry. I updated the list above.
Feel free to edit my above comment to mark libraries. Then the list doesn't need to be duplicated.

**Comment by jmooring** [comment]
The dependency list has been included in the README for a long time.
