### ISSUE TITLE
.Date.Local not working

### ISSUE THREAD

**Issue by sysadmiral** [gohugoio/hugo#3755]
I'm using hugo 0.25.1 and in the documentation at: https://gohugo.io/functions/format/ it states you can use `.Date.Local` (in conjunction with dateFormat) to get the local date. However it seems the builtin function `.Date` doesn't accept `.Date.Local` and I get the following error when a template is called:

```
Error: Failed to process archetype file "[REDACTED]/archetypes/default.md": template: default:3:57: executing "default" at <.Date.Local>: can't evaluate field Local in type string
```

Is this an error or am I calling the builtin incorrectly?

**Comment by bep** [comment]
We have another issue that is about updating the archetype docs to the changes I did some time ago -- so I will close this.

So, `.Date` in an archetype file is a date as a string ready to use in the front matter time fields.

If you want the current time and use Local (https://godoc.org/time#Time.Local), try:

```html
{{ now.Local }}
```
