### ISSUE TITLE
Need a way to keep hash keys while sorting

### ISSUE THREAD

**Issue by Astorsoft** [gohugoio/hugo#3763]
Hi, this is linked to the following post on discourse: https://discourse.gohugo.io/t/sort-a-hash-map-with-arbitrary-keys/7655/2

According to the documentation of sort, while it does support maps, it strips keys away and transform it into a slice: https://gohugo.io/functions/sort/

Would it be possible to add an option so that the keys are preserved? I know we can't just return a map as hashmap can't be ordered by design, but this could for example result in a slice of slices, on the form [[key1, value1], [key2, value2]].

**Comment by UjjwalAyyangar** [comment]
Is anyone working on this issue?
