### ISSUE TITLE
CSS Flexbox

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3773]
"Go implementation of CSS flexbox, port of Facebook's Yoga"

https://github.com/kjk/flex

I have no idea how this can be useful for Hugo, if any ... but If a person spent time to port 4,5K lines of C code to Go, it is at least worth a reminder issue, maybe other know CSS flexbox better to imagine something useful ...

**Comment by kevingimbel** [comment]
I don't think this is useful for Hugo. Flexbox is an amazing feature of CSS compared to "traditional" layouting but I don't see a way it could improve Hugo. 

Taken from the [authors blog](https://blog.kowalczyk.info/article/wN9R/experience-porting-4.5k-loc-of-c-to-go-facebooks-css-flexbox-implementation-yoga.html):
> I’m working on desktop GUI apps for Windows in Go.
> As it uses native win32 controls I don’t have to implement my own buttons, list boxes etc.
> However, win32 doesn’t have anything to help you layout things on the screen. Manual positioning is painful.

This is the "problem" Facebook's Yoga is solving: One way to position layouts across devices; They chose to re-implement the Flexbox Spec to make it available for Desktop and Mobile apps, and the original author is solving his problem of creating layouts in Go desktop apps. 

On the web we already have Flexbox support ([support is pretty good, actually](http://caniuse.com/#feat=flexbox)) so I do not see any advantage of implementing a go tool for creating flexbox layouts - it can all be done with "standard" CSS already. 

Just my 2 cent as a Front-End Developer. It may be useful for people who do not know Flexbox and want to take advantage of it, but I think using plain CSS is a better way for websites than using Yoga/Flex.
