### ISSUE TITLE
Please bump major version when making backward incompatible changes

### ISSUE THREAD

**Issue by maruel** [gohugoio/hugo#3782]
When generating on 0.26, I'm seeing:
```
ERROR 2017/08/07 14:50:37 Page's Now is deprecated and will be removed in Hugo 0.27. Use now (the template func).
```

These backward incompatible changes should automatically trigger a major version bump, so that when users update their hugo installation, they know, by the major version change, that a non-backward compatible change occurred and it may require non-trivial change to their website.

I know that using version 1 for such a little change feels like it hurts, but once you'll get to 5, it won't hurt anymore. :)

Reference: http://semver.org/ which the [dep tool](https://github.com/golang/dep) is going to use.

Thanks!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by bep** [comment]
Just to make it clear: Hugo is pre version 1 -- and breaking changes should be expected. We try to avoid it and have a fairly tidy deprecation strategy, but you should read the release notes before you update.

**Comment by maruel** [comment]
The most "roadmap" thing I found is https://gohugo.io/about/roadmap/ but didn't know what defines the requirements for v1.

Not judging, just wondering what makes you feel like the project can't cross v1 yet.

To be clear, I have no problem with backward incompatible changes, I'm totally fine with active refactoring and getting rid of legacy choices.

My point is that from a _user's point of view_, having clear signal in the _versioning scheme_ when a backward incompatible changes happens is useful, as a major version bump is a strong signal that I should go glance at the releases notes this time, vs in general it's not necessary. Asking for users to look at release notes at every single update is missing the point of this request.

That's why I filed it as a bug and not as a general discussion, since it's really up to the maintainer (you) to decide. As an user, I see it as a bug but I understand your reluctance into signalling that Hugo is now "stable" as in v1. What I mean is that once you accept that v2 will have breaking changes from v1, and this is fine, by design, then it doesn't hurt anymore and you can get to v3 as easily.

You already use the patch version occasionally, like 0.25.1, but not major version like described at http://semver.org/.

## More background for this request

There has been two great talks at GopherCon 2017 that made me think about this specifically.

The first is by [Sam Boyer](https://github.com/sdboyer) that introduces the [roadmap towards package management](https://www.youtube.com/watch?v=5LtMb090AZI) and the second is by [Carolyn VanSlyck](https://github.com/carolynvs) specifically [about goland/dep](https://www.youtube.com/watch?v=eZwR8qr2BfI).

**Comment by bep** [comment]
>That's why I filed it as a bug and not as a general discussion, since it's really up to the maintainer (you) to decide.

And so he has.

**Comment by maruel** [comment]
Thanks.
