### ISSUE TITLE
Shortcode with `if isset` for a named param crashes when the param is not set

### ISSUE THREAD

**Issue by Sharon-L** [gohugoio/hugo#3785]
I have a shortcode with the following condition, which aims to test whether a named `$id` parameter was passed (set) in the shortcode call: `{{ if (isset .Params "id") }}`.  
I want to use this to create a shortcode with optional named parameters. However, when I call the shortcode without passing an `$id` parameter, Hugo crashes with the following error:
```
panic: reflect: call of reflect.Value.Int on string Value [recovered]
        panic: reflect: call of reflect.Value.Int on string Value
```
I first encountered the problem with v0.24 of Hugo, and I still encounter it with v0.25.1.
I am running Hugo on Windows 10.

Note:
- When I pass an `$id` parameter to the shortcode (including if I set its value to ""), everything works well.
- Using the same condition but testing for an unnamed parameter (`$0`) — `{{ if (isset .Params 0) }}` — works well and does not crash when the shortcode is called without parameters.

From what I can gather from the Hugo and third-party documentation, my code is standard and should work. For more details and complete code examples, see my [Testing for optional shortocde parameters - isset and with errors support](https://discourse.gohugo.io/t/testing-for-optional-shortocde-parameters-isset-and-with-errors/7439) support discourse thread.

**Comment by moorereason** [comment]
Duplicates #3681.

**Comment by Sharon-L** [comment]
@moorereason If I understand #3681 correctly, the `isset` should not crash Hugo when passed a string value, but the function call should still fail in such cases. If this is true, what is the correct way for testing whether a named parameter was set in the shortcode call (to support optional named parameters)?
