### ISSUE TITLE
Installing Hugo on Google Cloud Shell

### ISSUE THREAD

**Issue by papagunit** [gohugoio/hugo#3787]
I'm having trouble installing Hugo in the [Cloud Shell](https://cloud.google.com/shell/) that runs Deb. It's unable to find the package in the default apt repos (is there one I need to add?) and cannot find snapd either.

I also tried installing it through the 'go get', ran the hugo executable, and it's asking for a config file. How do I create this config file?

Thanks

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
