### ISSUE TITLE
Hugo Doesn't Complete Generation With Large Number of Pages

### ISSUE THREAD

**Issue by teamcoltra** [gohugoio/hugo#3792]
```
Traviss-MacBook-Pro:Demo teamcoltra$ hugo
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
124554 regular pages created
12 other pages created
0 non-page files copied
9967 paginator pages created
1 author created
0 tags created
0 series created
total in 4745107 ms
```

if I narrow the number down to 100 pages the site generates just perfectly...  124554 is the correct number of files, but ~70% of those have unique authors, tags, and maybe 50% have series (which, again, all this is working at small scale already so I know they work).

It's not kicking back errors or anything like that so it's hard to know exactly what is wrong. I realize I am really pushing the boundaries of a normal use case for hugo but I feel like it should still fail gracefully (and there shouldn't really be anything inherently holding it back, if it takes 3+ hours to generate... thats fine by me)

**Comment by teamcoltra** [comment]
Add-on info: Counting the total number of files in public/ is 14,953 ... so I think it "lied" about how many pages it created as well.

**Comment by bep** [comment]
This isn't an issue we can take concrete action on at the moment, so I suggest  https://discourse.gohugo.io/ for questions/troubleshooting. We may get better in this area in the future, but we have other issues to track that.

**Comment by spf13** [comment]
One thing to consider is the memory consumption. You're doing this on a laptop. It may work better on a beefier machine considering the significant workload.

**Comment by teamcoltra** [comment]
Yeah this might be the case, there is also someone on the forums who mentioned this could be a Mac issue that has had a problem in particular with large numbers of files and hugo they gave me some numbers to change. 

That said, this tells me Hugo still needs better error catching. If something is messing it up and not allowing it to complete it's process it shouldn't say/imply it completed successfully, preferably it should say whats up or at least say "expected x didn't complete it"

**Comment by moorereason** [comment]
In an out of memory scenario, I'm pretty sure Hugo will crash.

**Comment by spf13** [comment]
I agree this isn't the best behavior. Unfortunately there isn't really a
lot we can do from within the application. This it really the OS'
responsibility.
