### ISSUE TITLE
Certain Front-Matter Strings Cause Failure

### ISSUE THREAD

**Issue by nraboy** [gohugoio/hugo#3798]
Hi,

This is a mixture of user error and possible bug, but I spent a good hour trying to figure out why I was receiving 403 errors when trying to access the list of tags.

Turns out I had a tag `.htaccess` which was resulting in that same directory being created at build. This is causing my Apache instance to go nuts.

I realize, I probably shouldn't have used a reserved filename, but it might also be a good idea to have Hugo catch this during the build. Or maybe throw an error anyone tries to start a tag with a certain character.

Worth hardening Hugo to prevent silly user errors like this?

**Comment by bep** [comment]
>I realize, I probably shouldn't have used a reserved filename

`.htaccess` is only reserved in the context of Apache, and I have no clue how Hugo could/should handle this in a general way.

Suggestions welcomed.

**Comment by nraboy** [comment]
Maybe have a blacklist of terms and during build time it scans the front-matter and the blacklist and throws an error if there is a match?

I haven't reviewed enough of the Hugo source to know what would be a "best" solution if any.

**Comment by nraboy** [comment]
`.htaccess` for one, but I'm sure it would have to grow over time.

I'll let smarter people than me chime in on this :-)

**Comment by Jos512** [comment]
Why not have the user define his or her own blacklist with a configuration variable? 

There's already an `ignoreFiles` setting; a `reservedFilenames` or `ignoreFilenames` setting fits nicely with that.

A blacklist maintained by the Hugo project members will (a) take up unnecessary development time for possible a lot of outlier cases and (b) will always be running behind new features of whichever server software the user uses.

**Comment by bep** [comment]
>.htaccess for one, but I'm sure it would have to grow over time.

I'm not using Apache, but I may write about Apache ... And in any case, you would not want to "ignore that word", either ... Some kind of encoding ... Not sure about this.
