### ISSUE TITLE
Auto-detect JSON, YAML, TOML, etc.. config

### ISSUE THREAD

**Issue by Xeoncross** [gohugoio/hugo#3802]
Just an idea or food for thought.

Currently, Hugo requires `+++` or  `---` or [some other marker](https://github.com/gohugoio/hugo/blob/master/parser/page.go#L285) which corresponds to TOML/YAML/JSON/HTML. Then Hugo attempts to [parse the page looking for the matching ending]( https://github.com/gohugoio/hugo/blob/master/parser/page.go#L118).

Rather than the whole parser, why not just look for the first block of text and treat it as the config? Then just try TOML/JSON/YAML until one of them returns without error.

https://play.golang.org/p/14Mv8Z-7o8

**Comment by bep** [comment]
As we also use that `+++` etc. indicator to detect if there are any front matter at all, your idea, while it sounds good, would not work. It would work if front matter were mandatory.
