### ISSUE TITLE
LiveReload does not refresh with .xml pages...

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/hugo#3804]
Not sure if this is possible to extend, but I've been working on creating a whole series of XML feeds for a content migration for work and never realized that XML/RSS doesn't reload on content changes. This would be especially useful now that Hugo users are creating their own custom outputs, such as RSS feeds, ATOM, etc...

**Comment by maiki** [comment]
LiveReload won't trigger a refresh, because one does not load javascript on RSS pages, ne? I've run into this issue on other sites that use a LiveReload system.

Do you know of something that works around that restriction, @rdwatters?

**Comment by bep** [comment]
Take this on the discussion forum. Current solution requires JS.
