### ISSUE TITLE
Feature suggest: support [[double brackets]] links between documents

### ISSUE THREAD

**Issue by idealhack** [gohugoio/hugo#3806]
This allows users create internal links more handily. For example, if we want this HTML:

`For instructions about installing, see <a href="/install-hugo">Install Hugo</a>.`

Using Hugo's [current syntax](https://gohugo.io/content-management/cross-references/), it would be:

`For instructions about installing, see [Install Hugo]({{< relref "Install Hugo.md" >}}).`

Using `[[double brackets]]`, it would be:

`For instructions about installing, see [[Install Hugo]].`

So `[[Document Title]]` should be equal to `[Document Title]({{< relref "Document Title.md" >}})`. More than a half bytes and keystrokes saved.

This syntax were wildly adopted in other markups and softwares, such as:

- [MediaWiki](https://www.mediawiki.org/wiki/Help:Links)
- [MoinMoin](https://moinmo.in/HelpOnLinking)
- [OneNote](http://www.onenote-tips.com/tips/linking.html)
- [Notational Velocity](https://github.com/scrod/nv/wiki/Release-Notes) and [nvALT](http://brettterpstra.com/projects/nvalt/)

For myself, I use nvALT to take markdown notes and Hugo for building the website.

P.S. I'm new to Hugo, so if this feature has a better way to be done, feel free to correct me :)

**Comment by bep** [comment]
See #3606
