### ISSUE TITLE
Add errorf template func

### ISSUE THREAD

**Issue by jetwash** [gohugoio/hugo#3817]
I'm working on a heavily data-driven hugo site; virtually all the content is in front matter, and it's all relatively structured.  As a result I tend to have a lot of templates, and they're more complicated than a blog or something where you mostly just need `{{ .Content }}`.

One thing I've struggled a bit with is making sure the input data is formatted correctly. I'd like to add a bit of logic to my templates to verify that required properties exist and, if not, emit an error message. I was thinking something like `errorf`, which would be just like `printf` but output to the console, and cause the build to fail.  That way I could do something like

```
{{ if not .Params.foo }}{{ errorf "foo parameter missing for %s" .URL }}{{ end }}
```

Without this, sometimes Hugo will crash (e.g., if I try to dereference a null pointer) or emit an error message (e.g., passing an unset value to jsonify results in an error about an incorrect number of arguments), but often Hugo will just quietly keep going and I end up with bad data.

I know doing this in the template isn't really ideal, but the only other thing I can think of would be validating against a schema, but I'm not aware of anything for markdown (which is the front matter format I'm using)… Maybe a way to automatically convert front matter to JSON then validate it against a JSON schema?

**Comment by bep** [comment]
I think an `errorf` func would be a great addition.

/cc @moorereason

**Comment by digitalcraftsman** [comment]
Should `errorf` to stdout like the regular log infos or to stderr?

**Comment by bep** [comment]
>Should errorf to stdout like the regular log infos or to stderr?

It should log to the defined `ERROR` logger.

**Comment by bep** [comment]
@bmon no panics/exits here. What you need to: Log to `ns.Deps.Logger.ERROR` (or something).

We have some log counting issue, so any ERROR logging will exit -1 at the end.

**Comment by nemequ** [comment]
It would probably be pretty straightforward to add a `warnf` at the same time (I assume the code would be mostly the same). That could be useful, too...

**Comment by bep** [comment]
@bmon thinking a little about this, template errors can be a bit spammy, so use the "distinct error logger":

https://github.com/gohugoio/hugo/blob/3054a461850485bad3293907720f4c5a9d76cab0/helpers/general.go#L221
