### ISSUE TITLE
Request - Have a way to specify additional files to watch - e.g. 'watchFiles'

### ISSUE THREAD

**Issue by dreamcat4** [gohugoio/hugo#3818]
I suppose this would be the opposite of the existing `ignoreFiles` setting. Therefore it should probably be implemented as a regexp just like ignoreFiles was too.

**Reason for this request:**

I am using asciidoc, and have created a site-wide `config.adoc` configuration file. Which that all of my `.adoc` files include. And is in the page template. This is because asciidoc really needs its own configuration file. And the perfect place to put it would be allongside `config.toml` in the root folder. I would very much like for hugo to watch and reload the site whenever this global asciidoc settings file is updated.

Now I've tried putting my file in content, and static. However it seems most of these default watch folders are not really appropriate for this file as usually Hugo expecting something else in those folders. Causing various little issues depending upon which subfolder its in. So for the time being, I have shoved it in `layouts/`, which seems to be working OK for now. In as far far as I don't know anything else is being broken by that. So hopefully I can keep doing this until this requested feature might be implemented in the future.

Please consider. Kind regards.

**Comment by dreamcat4** [comment]
Ah well it turns out there was something wrong with my temporary workaround. This is for rendering via asciidoctor...

Putting the include file in `layouts/config.adoc` does seem to reload the site whenever that file is changed. However it seems hugo is doing its expected job there so well that its only re-rendering the layout files / html templates. And not re-running all the content/ files through asciidoc. Which is exactly what it should do, and great. It just simply means I can't use layouts/ subfolder as a workaround.

I suppose the takeaway here is that its more complicated than I first thought. A custom watch files list may be ok to re-render the whole site (if the file is located in the root folder /, like existing `config.toml`). However other kinds of files might only be preferred to trigger reloads of the content, or the layout, or the static.

So then why don't I put my `config.adoc` file in `content/config.adoc`, or similar? Well it turns out that doing so does not work in conjunction with the cmdline flag `--navigateToChanged`. Because then saving a change to `content/config.adoc` makes the browser try to navigate to `http://mysite/config.adoc`... which is something that is not meant to be rendered as a content page into html. Its all just some asciidoc variables and settings.

What I actually want to happen is that any `.adoc` files  which contain the include directive:

`include::config.adoc[]`

be re-rendered if the source file `config.adoc` changes. And that would be a significant amount of custom functionality / mappings that hugo should not really want to know about. Given that adoc isnt natively supported and hugo doesnt know about such things.

Hmmph.

**Comment by nu8** [comment]
https://github.com/gohugoio/hugo/pull/7813

**Comment by a8nJ** [comment]
https://github.com/gohugoio/hugo/issues/6662

**Comment by a8nJ** [comment]
To anyone interested in this, I have a patch here:

https://patch-diff.githubusercontent.com/raw/gohugoio/hugo/pull/7813.patch

However I would caution against it. As soon as you starting using `watchFiles`
(or `ignoreFiles`), you incur a time cost in two places. First, you incur a
time cost in that you have to create and maintain an array of regular
expressions for whatever you are matching. This is not so bad. But in addition
to this, when you use `ignoreFiles`, Hugo has to initially loop through all
your patterns to compile:

https://github.com/gohugoio/hugo/blob/0d54a844061e808dd5b4ff4874b2e4bd9df4d556/source/sourceSpec.go#L65-L73

Then, for each file Hugo loops through the compiled patterns:

https://github.com/gohugoio/hugo/blob/0d54a844061e808dd5b4ff4874b2e4bd9df4d556/source/sourceSpec.go#L105-L121

and with Windows, youll notice it even does it twice. As a workaround, you can
put these files in a folder alongside the `content` folder. For example
`readfiles`:

https://github.com/gohugoio/hugo/tree/master/docs/content/en/readfiles

so you might have a layout like this:

~~~
content/march.md
readfiles/march/sunday.txt
readfiles/march/monday.txt
~~~

and a Shortcode like this:

~~~
{{ $s_get := .Get 0 }}
{{ readFile (path.Join .Page.RelPermalink $s_get) }}
~~~
