### ISSUE TITLE
markdownify does not replace any shortcodes

### ISSUE THREAD

**Issue by psistorm** [gohugoio/hugo#3821]
Is there a reason that `markdownify` does not replace shortcodes? I thought this would be rather consistent if any shortcodes that can be used in content files could also be used within text that is "markdownified".

If not I would state such a feature request to allow usage of shortcodes within markdownified texts. I'm trying to do an API documentation with hugo using frontmatter to store possible properties and functions for all methods of a class. And for each method I have possible example text or description that sometimes uses a custom source code shortcode or shortcodes for info/warning boxes.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by bep** [comment]
>If not I would state such a feature request to allow usage of shortcodes within markdownified texts. 

I would turn down such a request. Shortcodes is for content files. `markdownify` is for templates.

**Comment by vitpankin** [comment]
@bep how can I achieve the following then? I have this shortcode to include .md files into other .md files, this is super useful for tabbed content, to have content for each tab into different files:
`includeMarkdown.html`
```
{{ $includePath := (print .Page.Dir (.Get 0)) | printf "./content/%s" }}
{{ readFile $includePath | markdownify }}
{{ .Inner }}
```
also I have number of shortcodes for simplified rendering for blocks like quotes, tips blocks, and etc.

whenever I include files into base .md file - shortcodes does not work, coz `markdownify` render all shortcodes as plain text without any parsing. What did I do wrong?

**Comment by moorereason** [comment]
@vitpankin, please use the forums to discuss what you're wanting to do.

**Comment by JamesTheHacker** [comment]
I agree with OP. This is an issue and this should be implemented. Here's my use case:

```
{{< CardList title="Orangery Designs" description="This is a lead description. Every card list block has one. **If you have any questions feel free to give us a call and we will be happy to help**." >}}
    {{< CardListItem src="/orangeries/capella-orangery-solihull.png" title="The Capella Orangery" >}}
      Some information displayed in card.
    {{< /CardListItem >}}

    ... More CardListItem's ...
{{< /CardList >}}
```

How can I make the text in the lead description bold if I can't use markdownify in the short code?

**Comment by biodranik** [comment]
This feature would be really useful, especially if it can be activated by an additional optional parameter to `markdownify`, or even as a separate function like `markdownifyShortcodes`.
