### ISSUE TITLE
Is windows version of hugo trustfully 0.26?

### ISSUE THREAD

**Issue by the1900** [gohugoio/hugo#3823]
This is output from latest release version for windows. 

``` bash
$ hugo version
Hugo Static Site Generator v0.20 windows/amd64 BuildDate: 2017-04-10T07:14:04+09:00
```

Is this just wrong number or something has a problem with deploy system?

**Comment by bep** [comment]
>Is this just wrong number or something has a problem with deploy system?

Since you are the first to complain, I would suggest a third option: You have an old version floating around in the `PATH`. Try `./hugo version`.

**Comment by the1900** [comment]
@bep  Right before, I downloaded from https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Windows-64bit.zip and run `hugo version` 

The result on powershell.
``` powershell
PS D:\Desktop2\hugo_0.26_Windows-64bit> hugo version
Hugo Static Site Generator v0.20 windows/amd64 BuildDate: 2017-04-10T07:14:04+09:00
PS D:\Desktop2\hugo_0.26_Windows-64bit>
```

**Comment by bep** [comment]
Try my suggestion exactly as I wrote it.

**Comment by the1900** [comment]
Oh I'm sorry it was my mistake. I didn't realize there is a more hugo binary in my path.
Thanks .
