### ISSUE TITLE
Let `hugo server --navigateToChanged` maintain the scroll position if possible

### ISSUE THREAD

**Issue by yihui** [gohugoio/hugo#3824]
When I'm currently viewing a page of which the source Markdown file is being edited, I wish the scroll position of this page in the browser could be maintained when `--navigateToChanged` is enabled for `hugo server`. That is, if Hugo is about to navigate to the same page as the current page in the browser, `location.reload()` should be called instead of `location.href = "NEW_LOCATION"` in JS. I'm not sure if that is possible with Hugo, or it requires upstream support from LiveReload.

**Comment by bep** [comment]
>location.reload()

I'm too lazy to look it up: Is this a standard JS method supported by all browsers?

If so, this should be possible to fix on the Hugo side.

**Comment by bep** [comment]
If someone wants to fix this, here is the location:

https://github.com/gohugoio/hugo/blob/master/livereload/livereload.go#L117

**Comment by yihui** [comment]
Yes, `location.reload()` is fairly standard: https://developer.mozilla.org/en-US/docs/Web/API/Location/reload

I just submitted the PR #3825. Thanks!
