### ISSUE TITLE
Inner mark checks for base templates don't work?

### ISSUE THREAD

**Issue by raphaelcohn** [gohugoio/hugo#3829]
If I change in, same `_default/list.html` the value `{{ define "main" -}}` to `{{- define "main" -}}`, the code checking that a `_default/baseof.html`, the code detecting that a `_default/baseof.html` template in ` hugo/output/layout_base.go` fails.

In essence:-

```go
var (
	aceTemplateInnerMarkers = [][]byte{[]byte("= content")}
	goTemplateInnerMarkers  = [][]byte{[]byte("{{define"), []byte("{{ define"), []byte("{{- define"), []byte("{{-define")}
)

...

needsBase, err := d.ContainsAny(fullPath, innerMarkers)
	if err != nil {
		return id, err
	}

	if needsBase {
currBaseFilename := fmt.Sprintf("%s-%s", filenameNoSuffix, baseFilename)

...

```

**Comment by bep** [comment]
>In essence:-

Can you elaborate on what you mean by "essence"?

**Comment by raphaelcohn** [comment]
What I've put in the code block above are the two pieces of code I believe to be the cause of the problem. Since this is the smallest, most focused piece of code I could find, then this material is the "essence": the essential information required, reflecting the core of the problem.

It is my belief that this code, or something it uses, is the cause of the fault. Of course, it took a while to find, not least because of the rather imprecise and misdirecting tracing messages `--debug` produces, but that's a more minor issue.

**Comment by bep** [comment]
Sure, but did you test this with the latest Hugo code base?

**Comment by raphaelcohn** [comment]
`0.26`

**Comment by bep** [comment]
That was not what I asked. The latest  Hugo code base is `0-27-dev`, and I fixed this some weeks ago. Please reopen if this for some odd reason still does not work.
