### ISSUE TITLE
Unable to create template for custom output format for taxonomy term

### ISSUE THREAD

**Issue by jetwash** [gohugoio/hugo#3831]
Largely copied from https://discourse.gohugo.io/t/custom-output-format-for-taxonomy-terms/8086:

I’m trying to get a taxonomy term to output a JSON version, but not having much success. I've tried adding

```
[outputs]
    taxonomyTerm = [ "HTML", "JSON" ]
```

to [my config.toml](https://github.com/factopolis/factopolis/blob/master/config.toml) right next to similar entries for page, section, home, and taxonomy, and I’ve created [a layout with a *.json extension](https://github.com/factopolis/factopolis/blob/master/themes/factopolis/layouts/taxonomy/claim.terms.json) right next to [the *.html version](https://github.com/factopolis/factopolis/blob/master/themes/factopolis/layouts/taxonomy/claim.html). AFAICT [the documentation](http://gohugo.io/templates/output-formats/#output-formats-for-pages) seems to indicate this should work Hugo doesn’t pick it up. Running hugo -v doesn’t complain about the template being missing, either…

If I add the output formats to my front matter instead, with something like

```
---
title: Whatever
outputs:
- html
- json
---
```

`hugo -v` will complain about not being able to find the relevant template, even though it’s there [right next to](https://github.com/factopolis/factopolis/tree/master/themes/factopolis/layouts/taxonomy) the HTML version, with the *.html version replaced with *.json.

**Comment by jetwash** [comment]
I'm trying to look into this a bit more.  It seems like the template doesn't make it into the list of defined templates in (verified by looking at `t.t.DefinedTemplates()` in [lookup() in tpl/tplimpl/template.go](https://github.com/gohugoio/hugo/blob/d33563b5d79af01260a24cea355160d802b2bd4e/tpl/tplimpl/template.go#L246)). However, the right name does seem to be generated by Hugo (looking at the value returned by [filterDotLess() in output/layout.go](https://github.com/gohugoio/hugo/blob/d33563b5d79af01260a24cea355160d802b2bd4e/output/layout.go#L233)).

**Comment by regisphilibert** [comment]
I am able to build a page for `taxonomyTerm` by setting the output format to "taxonomy":
```
  taxonomy = ["json"]
```
The other way around does not seem to work though.

**Comment by MunifTanjim** [comment]
The relevant discussion posts about this bug:

- [Taxonomy & TaxonomyTerm implementation (naming) is probably incorrect](https://discourse.gohugo.io/t/taxonomy-taxonomyterm-implementation-naming-is-probably-incorrect/10444)
- [Page kind are swapped for “taxonomy” and “taxonomyTerm”](https://discourse.gohugo.io/t/page-kind-are-swapped-for-taxonomy-and-taxonomyterm/10780)
