### ISSUE TITLE
Ugly URLs with override for HTML eat taxonomy term pages

### ISSUE THREAD

**Issue by jetwash** [gohugoio/hugo#3832]
When using ugly URLs, but overriding that for HTML, hugo doesn't create any output for taxonomy term pages. See https://github.com/factopolis/factopolis/tree/uglyurls for an example (claims/index.html and groups/index.html, which are the taxonomy term pages, are missing).

**Comment by bep** [comment]
>See https://github.com/factopolis/factopolis/tree/uglyurls for an example 

There are no uglyURL config in your example.

**Comment by jetwash** [comment]
On Thu, 2017-08-24 at 23:04 +0000, Bjørn Erik Pedersen wrote:
> > See https://github.com/factopolis/factopolis/tree/uglyurls for an
> > example 
> 
> There are no uglyURL config in your example.
> 

Are you looking at the "uglyurls" branch? That's what I linked to, but
I definitely should have been more clear about it since it's pretty
subtle on GitHub. Sorry about that :(

Lines 9 thru 11 of config.toml in that branch are

```
uglyurls = true
[outputFormats.HTML]
    nougly = true
```

If you are looking at the uglyurls branch, I'm confused… what are you
expecting to see?
