### ISSUE TITLE
govendor get github.com/gohugoio/hugo is erroring out

### ISSUE THREAD

**Issue by stevenventimiglia** [gohugoio/hugo#3833]
I even remove all directories, try to fresh install.  No luck.  
Is there any other way to install the dependencies?  I would do so one-by-one, if necessary.

Windows 10 Pro - Avoiding choco.

```
$ govendor get github.com/gohugoio/hugo
# cd .; git clone https://github.com/gohugoio/hugo C:\Users\Steven\Development\Go
\src\github.com\gohugoio\hugo
fatal: could not create leading directories of 'C:\Users\Steven\Development\Go
\src\github.com\gohugoio\hugo': Invalid argument
Error: failed to create repo "https://github.com/gohugoio/hugo" in "C:\\Users\\Steven\\Development\\Go\n\\src\\github.com\\gohugoio\\hugo" exit status 128
```

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
