### ISSUE TITLE
Auto generated section tree menu that replicates content tree structure

### ISSUE THREAD

**Issue by miltador** [gohugoio/hugo#3834]
This is a new feature request and proposal.

Given a following content tree:
```
 └─┬ content\
   ├─┬ help\
   │ ├── instructions.adoc
   │ ├── style-guide.adoc
   │ ├─┬ instructions\
   │ │ ├── documenting-procedure.adoc
   │ └─┬ style-guide\
   │   ├── general.adoc
   ├─┬ misc\
   │ ├── dongle-upgrade.adoc
   ├─┬ posts\
   │ ├── 2015-12-09-system.adoc
   │ ├── 2015-12-10-remote-license.adoc
   ├─┬ products\
   │ ├── air.adoc
   │ ├── archive.adoc
   │ ├── route.adoc
   │ ├─┬ air\
   │ │ ├── 11\...
   │ │ └── 11.adoc
   │ ├─┬ archive\
   │ │ ├── 10\...
   │ │ ├── 11\...
   │ │ ├── 10.adoc
   │ │ └── 11.adoc
   │ ├─┬ route\
   │ │ ├── release-notes.adoc
   │ │ ├── system-recommendations.adoc
```

We are able to automatically generate top-level section menus that will replicate the content structure.
Every menu item will have:
  - `Menu`: set to the top-level section name
  - `Identifier`: set to the relative path of the content file
  - `Parent`: set to the parent section's relative path in the content tree
  - `Name`: taken from page's `title`
  - `Weight`: taken from page's `weight`

Would be nice to be able to manually override some of value if needed in the page's front-matter by declaring the menu entry with the id of it's top-level section.

**Comment by rinetd** [comment]
how to solve  this problem？？？
