### ISSUE TITLE
homeSection to override homepage

### ISSUE THREAD

**Issue by KillyMXI** [gohugoio/hugo#3838]
First described in [discource](https://discourse.gohugo.io/t/replace-homepage-with-an-index-from-certain-section/8126), but since it's more of a feature request, it belongs to here as well, I guess.

Blog that also has other kinds of pages not belonging to main pagination - is a common use case for Hugo.
But being forced to use the `layouts/index.html` in some dodgy way (I mean custom pagination that just mirrors some section pagination) instead of just telling "blog posts is what my site is about" - doesn't feel right.

So I would like to set some section as the default in `config.toml`:
```
homeSection = "post"
```
to make it ignore `layouts/index.html` completely and create index from the posts section at `/` instead of `/post/`.
This will remove unneeded complexity and some architecture limitations for me.

**Comment by bep** [comment]
Bring it to some kind of conclusion in the discussion forum first. I don't like double posts.
