### ISSUE TITLE
Fail to create 404 page

### ISSUE THREAD

**Issue by dominhhai** [gohugoio/hugo#3840]
I placed `404.html` file in the `layout` as [this docs](https://gohugo.io/templates/404/).
However, the 404.html file is not generated by all `$ hugo server` and `$ hugo command`.

My env:
* OS: MacOS
* Hugo: v0.26

What did I wrong?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
