### ISSUE TITLE
Add news feed to http://gohugo.io/news/

### ISSUE THREAD

**Issue by Tafkas** [gohugoio/hugo#3843]
Currently http://gohugo.io/news/ has no news feed. It would be really helpful to have one in order to keep track of Hugo related news.

**Comment by budparr** [comment]
This feed should work: https://gohugo.io/news/index.xml We need to add it to autodisovery, though, which I'll do in the [theme](https://github.com/gohugoio/gohugoioTheme/issues/67).

**Comment by Tafkas** [comment]
Thank you. I looked into the source code of http://gohugo.io/news/ but there wasn't any hint to https://gohugo.io/news/index.xml

**Comment by digitalcraftsman** [comment]
i'll close this issue in favor of https://github.com/gohugoio/gohugoioTheme/issues/67 as this repo isn't about the website per sé.
