### ISSUE TITLE
<!--more--> does not work when inline.

### ISSUE THREAD

**Issue by glockjt** [gohugoio/hugo#3845]
This still doesn't work using v0.26.
Example:
```markdown
Sample text should be slip here <!--more--> but it is not.
```
Results in:
```html
<p>Sample text should be slip here but it is not.</p>
```

Should result in:
```html
<p>Sample text should be slip here</p>
```

However this works using v0.16

**Comment by bep** [comment]
This as designed. You will have to put some newline in there. Not sure why that is a problem.

**Comment by glockjt** [comment]
It used to work.  So this was an unpublished breaking change.  The reason it is a problem is because of the following:

```markdown
Sample text should be slip here
<!--more-->
but it is not.
```

```html
<p>Sample text should be slip here</p>
<p>but it is not.</p>
```
