### ISSUE TITLE
Passing multiple configs doesn't work on Windows

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#3848]
I'm trying to refactor my Hugo configuration files for development, production, staging.

I created a common `config-common.yml` file and the other 3 config files which just set the `baseURL` and a couple of custom `params`.

But it doesn't seem to work for me on Windows:

```
C:\Users\xmr\Desktop\foobar>hugo version
Hugo Static Site Generator v0.26 windows/amd64 BuildDate: 2017-08-07T16:01:07+03:00

C:\Users\xmr\Desktop\foobar>hugo --config=config-common.yml,config-development.yml
Error: Unable to locate Config file. Perhaps you need to create a new site.
       Run `hugo help new` for details. (open config-common.yml,config-development.yml: The system c
annot find the file specified.)


C:\Users\xmr\Desktop\foobar>hugo --config=config-common.yml
ERROR 2017/08/30 13:35:33 No 'baseURL' set in configuration or as a flag. Features like page menus w
ill not work without one.
Started building sites ...
Built site for language en:
0 of 2 drafts rendered
0 future content
0 expired content
9 regular pages created
2 other pages created
0 non-page files copied
0 paginator pages created
total in 27 ms
```

The config files are inside the same directory I'm launching Hugo.

**Comment by Jos512** [comment]
Hugo 0.26 released 23 day ago, and the [pull request](https://github.com/gohugoio/hugo/pull/3532) that implemented this feature is merged 21 days ago. So it's not yet in your Hugo version, it seems.

**Comment by XhmikosR** [comment]
Ah, that makes sense.

Thanks!

**Comment by XhmikosR** [comment]
I just tested 0.27; it works perfect :D
