### ISSUE TITLE
Function to parse URLs

### ISSUE THREAD

**Issue by jetwash** [gohugoio/hugo#3849]
I'd like to be able to extract a domain name from a URL so I can tell people where they are going. I'm using a regex now, but obviously it's a bit naïve. It would be nice to have a function in Hugo to do this.

I figure it would probably make more sense to return a map with entries like scheme, host, port, path, query, *etc.*, instead of restricting it to the domain. Basically, what [Parse in net/url](https://golang.org/pkg/net/url/#Parse) does.

It would also be very useful if it could include the effective TLD+1 in the return value, using the [public suffix list](https://publicsuffix.org/). There is already [a go package](https://godoc.org/golang.org/x/net/publicsuffix) to make it easy.

**Comment by bep** [comment]
To be clear: We can add `net.Parse` (=> `urls.Parse`), but we're not doing some TLD+1.
