### ISSUE TITLE
File watching doesn't work on Linux

### ISSUE THREAD

**Issue by franziskuskiefer** [gohugoio/hugo#3850]
File watching from `hugo server` doesn't seem to work on Arch Linux (Hugo Static Site Generator v0.26 linux/amd64 BuildDate: 2017-08-07T18:27:14+02:00). I see `Watching for changes in <path>/{data,content,layouts,static,themes}` but changing files in any of those folders doesn't get picked up.

**Comment by miltador** [comment]
Try `hugo server --watch`.

**Comment by bep** [comment]
Watching  is default for `hugo server`, and I'm pretty sure it (in general) works on Linux. There can, however, be editors that behaves in a way that we does not currently support. 

* What editor do you use?
* Can you try to do a simple chane in, say `nano` and check if that makes a difference?

/cc @anthonyfok

**Comment by franziskuskiefer** [comment]
I tried editing with Sublimetext, vim, and nano. But it doesn't change anything on the result (they don't get picked up).
The same works fine on Mac for me.

**Comment by anthonyfok** [comment]
Hi @franziskuskiefer:

The file watch feature has been working fine on Linux for quite some time now, so the problem you encountered is news to me.  Could you please provide the following extra information to help us diagnose the issue?  For example:

1. Where did you obtain hugo from?  From the Arch Linux community (e.g. https://www.archlinux.org/packages/community/x86_64/hugo/ )?  Or from pre-built tarball?  Or did you build from source using `govendor`?

2. The filesystem that you are using.  (ext4? btrfs? ZFS? Something else?)

Many thanks!

**Comment by franziskuskiefer** [comment]
I'm using the Arch Linux community package on a dm-crypt encrypted ext4 filesystem.

**Comment by ardianta** [comment]
I think this could not work if you have any error and waring on your template or configuration.

I have test it on Linux Mint Sarah 64bit using:

- __VSCode__ and internal terminal to run server: sometime work, sometime not;
- __Geany__ and external terminal: sometime work, sometime not.

Try to run the server with `--verbose` flag and see the waring and errors.

**Comment by franziskuskiefer** [comment]
The exact same config/theme etc. works fine on Mac.

    INFO 2017/09/04 09:48:15 Using config file: 
    INFO 2017/09/04 09:48:15 using a UnionFS for static directory comprised of:
    INFO 2017/09/04 09:48:15 Base: website/themes/ananke/static
    INFO 2017/09/04 09:48:15 Overlay: website/static/
    INFO 2017/09/04 09:48:15 syncing static files to /
    WARN 2017/09/04 09:48:15 No translation bundle found for default language "en"
    WARN 2017/09/04 09:48:15 Translation func for language en not found, use default.
    WARN 2017/09/04 09:48:15 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
    Started building sites ...
    INFO 2017/09/04 09:48:15 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
    INFO 2017/09/04 09:48:15 Alias "/post/page/1/index.html" translated to "post/page/1/index.html"
    Built site for language en:
    0 draft content
    0 future content
    0 expired content
    23 regular pages created
    48 other pages created
    0 non-page files copied
    2 paginator pages created
    0 categories created
    17 tags created
    total in 29 ms
    WARN 2017/09/04 09:48:15 Skip i18nDir: lstat website/i18n: no such file or directory
    Watching for changes in website/{data,content,layouts,static,themes}
    WARN 2017/09/04 09:48:15 Skip i18nDir: lstat website/i18n: no such file or directory
    Serving pages from memory
    Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
    Press Ctrl+C to stop

**Comment by ardianta** [comment]
@franklinwise I was test again...

Try to clean `public` dir:

```
rm -rf public
```

and then run the server, it works to me.

**Comment by franziskuskiefer** [comment]
Cleaning the public folder doesn't change anything for me.

**Comment by MikhailKlemin** [comment]
I do not know if it necessary to say, but I have exactly same situation on Ubuntu 16.04 and freshly compiled Hugo 0.30 DEV -- it doesn't works.

**Comment by MikhailKlemin** [comment]
The issues are with fsnotify  The solution is there:
https://github.com/howeyc/fsnotify/issues/68

**Comment by MattSurabian** [comment]
Watch is working fine for me. I'm also on Arch Linux and have a luks encrypted ext4 file system but I'm running off master:

```
Hugo Static Site Generator v0.30-DEV linux/amd64
```

**Comment by MikhailKlemin** [comment]
Well, there V0.31 latest version now. 

I  was also sure fsnotify works but I tried this example and found it was not.  

That all I could do

```
package main

import (
	"log"

	"github.com/howeyc/fsnotify"
)

func main() {
log.SetFlags(log.LstdFlags | log.Lshortfile)
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}

	done := make(chan bool)

	// Process events
	go func() {
		for {
			select {
			case ev := <-watcher.Event:
				log.Println("event:", ev)
			case err := <-watcher.Error:
				log.Println("error:", err)
			}
		}
	}()

	err = watcher.Watch("testDir") 
	if err != nil {
		log.Fatal(err)
	}
	
	// Hang so program doesn't exit
	<-done

	/* ... do stuff ... */
	watcher.Close()
}
```

**Comment by thnee** [comment]
For anyone who lands here while googling, the most likely cause for watch not working on linux is that you have too low limits for inotify watches or instances.

Try increasing them.

```
sudo sysctl -n -w fs.inotify.max_user_watches=16384
sudo sysctl -n -w fs.inotify.max_user_instances=512
```
