### ISSUE TITLE
Wrong languageName used for a language, but only sporadically

### ISSUE THREAD

**Issue by vinterdotter** [gohugoio/hugo#3851]
Let me preface this by saying it’s my first Hugo project, and I’m probably doing weird things.

I ported https://www.contributor-covenant.org from hand-generated-everything to Hugo.
I used the sweet multilingual features for the translations.

There’s a page that [lists all the translations](https://www.contributor-covenant.org/translations/), and on the live site, “Português do Brasil” appeared twice, and “Português” did not appear at all, but one of them did indeed link to non-Brazilian Portuguese.

I had not observed this locally, but did when trying to fix it. Then, it fixed itself without any changes.
I saved the config (with no changes) a few times, to rebuild the site. The issue would come and go seemingly at random.

To fix the problem on the live site, we simply hit “Trigger deploy” on Netlify, with no changes, got lucky, and got the desired output.

The language config [looks like this](https://github.com/ContributorCovenant/contributor_covenant/blob/master/config.toml#L107), and the code that lists all translations [is here](https://github.com/ContributorCovenant/contributor_covenant/blob/master/layouts/translations/list.html#L15), and [here](https://github.com/ContributorCovenant/contributor_covenant/blob/master/layouts/partials/translation-row.html).

To reproduce, clone the repo, run `hugo server`, open the translations page, and save the config a few times. This is on Hugo 0.26.

Whether I’m doing something wrong or not, the non-deterministic behavior is very confusing. ☺️

I would also like to say thank you for the wonderful tool. While there’s a lot left to do, the site is much more maintainable now, especially for translators.

**Comment by bep** [comment]
I suspect "{{ range last 1 (where $.Site.RegularPages "Section" "version") }}" is, due to sorting issues, giving you a different page each time, but it is better to  use https://discourse.gohugo.io/ for questions/troubleshooting.

**Comment by vinterdotter** [comment]
I don't think it can be a sorting issue, since the links are always correct, but the corresponding name sometimes isn't. I will check out discourse and the source, thanks!
