### ISSUE TITLE
Clean up Date vs PublishDate

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3854]
Make sure that both `Date` and `PublishDate` is always set to a value if one of them is available.

See `Page.update`. This method extracts front matter into params and the Page struct. There are logic there to handle different "date scenarios", but there are still some cases where a page ends up without a `Date` or a `PublishedDate`.

I suggest that we **before** the `if p.Date.IsZero() && p.s.Cfg.GetBool("useModTimeAsFallback") {` in this method adds some checks:

* If Date.IsZero then set it to PublishedDate
* If PublishedDate.IsZero then set it to Date

To create a test for this, the simplest is probably to create something similar to `TestWordCountWithAllCJKRunesWithoutHasCJKLanguage` in `page_test.go`.

**Comment by hholi** [comment]
I will have a look at it.

**Comment by jfo** [comment]
Is this bug available? Do you mean in your comment something like this?

```diff
diff --git a/hugolib/page.go b/hugolib/page.go
index 306d3373..2f7ebec8 100644
--- a/hugolib/page.go
+++ b/hugolib/page.go
@@ -1147,6 +1147,14 @@ func (p *Page) update(f interface{}) error {
 	}
 	p.Params["draft"] = p.Draft
 
+	if p.Date.IsZero() {
+            p.Date = p.PublishDate
+        }
+
+	if p.PublishDate.IsZero() {
+            p.PublishDate = p.Date
+        }
+
 	if p.Date.IsZero() && p.s.Cfg.GetBool("useModTimeAsFallback") {
 		fi, err := p.s.Fs.Source.Stat(filepath.Join(p.s.PathSpec.AbsPathify(p.s.Cfg.GetString("contentDir")), p.File.Path()))
 		if err == nil {
```

As written, [breaks the build](https://gist.github.com/jfo/45bf268d09c37b39150744a4b0ab9e48) but wanted to see if it's the right ballpark for what you mean.

**Comment by bep** [comment]
>Is this bug available?

Look at @hholi 's comment. So, no.

**Comment by jfo** [comment]
Ok np! I just didn't see any activity and it sparked my interest so I thought I would ask.

@hholi lmk if you'd like any help! I will look for something else for now. 😄
