### ISSUE TITLE
deploy to gitlab failed 

### ISSUE THREAD

**Issue by wdssss** [gohugoio/hugo#3855]
This is my gitlab https://gitlab.com/wxdl/hugo
Use gitlabci to generator hugo public file, but it didn't create index.html.

registry.gitlab.com/pages/hugo:0.26

=======  pages log ===================
$ hugo
Started building sites ...
Built site for language en:
0 of 1 draft rendered
0 future content
0 expired content
0 regular pages created
6 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 8 ms
$ ls -lth public
total 32
drwxr-xr-x    2 root     root        4.0K Sep  2 14:57 categories
-rw-r--r--    1 root     root         486 Sep  2 14:57 index.xml
-rw-r--r--    1 root     root         464 Sep  2 14:57 sitemap.xml
drwxr-xr-x    2 root     root        4.0K Sep  2 14:57 tags
$ cat public/index.html

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
