### ISSUE TITLE
Hugo fails when parsing some Unicode escape sequences in YAML front matter

### ISSUE THREAD

**Issue by tech4him1** [gohugoio/hugo#3857]
If a post contains some Unicode escape sequences in YAML front-matter, like this:
```yaml
description: "\uD83D\uDC68"
```
which is the code form the Emoji `👨`, Hugo errors out while processing that post:
```
Started building sites ...
ERROR 2017/09/03 14:09:24 failed to parse page metadata for "post\\this-post.md": yaml: line 3: found invalid Unicode character escape code
Error: Error building site: Errors reading pages: Error: failed to parse page metadata for "post\\this-post.md": yaml: line 3: found invalid Unicode character escape code for this-post.md
```
Am I doing something wrong here, or is this a bug?

**Comment by bep** [comment]
I very much doubt it is a bug, but if so, you would have to raise an issue here:

https://github.com/go-yaml/yaml

As to emojis, see https://gohugo.io/functions/emojify/

**Comment by tech4him1** [comment]
@bep Thanks for the quick reply, I really doubted it too. I think I finally found the issue: https://github.com/go-yaml/yaml/issues/279.
