### ISSUE TITLE
Section Lists with custom heading

### ISSUE THREAD

**Issue by Koenyn** [gohugoio/hugo#386]
I have the following folder structure, but for some reason the content of Blog.html is not being used as my list for my blog. I've tried adding a section.html into the _default page, but that means I need to add a dynamic title and partial for the introduction, which I can't seem to work out how to do.

What am I missing? Is there something that Hugo is missing?
# Site
- Content
  - Blog
    - article1.md
  - Projects
    - project1.md
- Layouts
  - _default
    - list.html
    - single.html
  - partials
    - footer.html
    - header.html
    - posts.html
  - section
    - Blog.html
    - Projects.html

**Comment by campino2k** [comment]
Perhaps another solution which works with 0.14

Created a content/referenzen.md-File, 
set
 
> type: "referenzen"
> layout : "overview"

Create a referenzen/overview.html

```
{{ partial "header.html" . }}
{{ partial "nav.html" . }}


<article class="content-main">

  <h1>Reflist: {{ .Title }}</h1>

  {{ .Content }}
<ul>

  {{ range where .Site.Pages "Section" "referenzen" }}

  <li>
  <a href="{{ .Permalink }}">{{ .Title }}</a>
  <div class="meta">{{ .Date.Format "Mon, Jan 2, 2006" }}</div>
  </li>

  {{ end }}
</ul>

</article>

{{ partial "footer.html" . }}
```

Put contents to be listed in referenzen/[how-you-like-it.md]

Profit.
