### ISSUE TITLE
RSS/Atom support for data-driven content

### ISSUE THREAD

**Issue by jetwash** [gohugoio/hugo#3862]
Being able to use RSS and Atom feeds for data sources (i.e., a `getFeed` function) could be extremely useful, especially when combined with a cron job to trigger a build/deploy.

It looks like there are a few go libraries which could handle this:

* https://github.com/mmcdole/gofeed
* https://github.com/SlyMarbo/rss
* https://github.com/ungerik/go-rss

**Comment by bep** [comment]
>would be extremely useful

For what? 

Hugo is and will be a static generator, I think. There is another issue about somehow generating pages "on the fly" (and I assume also not writing to disk) based on data files etc., but that will go into the normal Hugo "pipeline", which would end up in whatever output format you want (including RSS if you want).

**Comment by jetwash** [comment]
I can think of lots of use cases off the top of my head. Building a news aggregator is pretty obvious. Or adding a "News" section to a site which pulls in articles off of Medium or from a Wordpress install. Or adding a bit of content to a sidebar instead of just a static link. Or list videos from your YouTube channel, or pictures from Instagram, etc. Maybe a company would want a "Careers" page which pulls their entries from Monster.com. Or pulling in the titles of recently active topics from a community forum.

And that's just the general purpose stuff. A lot of the uses will very be specific to the topic at hand. If you're making a page for a programming language, maybe you want to display the latest packages published to NPM/Crates/CPAN/PEAR/*etc.*, or StackOverflow posts. Maybe a site for a musician would want to pull in a list of upcoming concerts from StubHub/TicketMaster/etc, or songs from SoundCloud. The more interesting use cases are almost always the stuff you don't anticipate.

Sure, this is stuff you could do manually by adding stuff to content/, but that requires specialized knowledge. Why force people to learn how a specific Hugo site works when adding content could be as easy as just adding a video to YouTube, a picture to Instagram, a blog entry to Medium, etc.? Besides, if you only have to add content in one place you don't have to worry about keeping it in sync.

I'm not sure why being a static generator would be a restriction. Just run it however often you want to check for new content. As an example, [Planet Planet](http://www.planetplanet.org/) is a static generator. You just set up a cron job to automatically kick off a build… [Travis CI makes it pretty easy](https://docs.travis-ci.com/user/cron-jobs/) without having to do anything locally, as long as daily is often enough, or if you prefer Netlify you can just [GET a url](https://www.netlify.com/docs/webhooks/#incoming-webhooks) from a cron job to kick off a build.

**Comment by bep** [comment]
>I'm not sure why being a static generator would be a restriction. 

No, but it sets a scope for "what Hugo is". There is a saying about "doing one thing well..."

**Comment by jetwash** [comment]
> No, but it sets a scope for "what Hugo is". There is a saying about "doing one thing well..."

But this doesn't really alter the scope of Hugo. It's still a static site generator. All I'm suggesting is to add a `getFeed` function alongside the [existing](http://gohugo.io/templates/data-templates/#implementation-details) `getJSON` and `getCSV` functions.

**Comment by bep** [comment]
`getJSON` and `getCSV` is already pushing it, and they fall into a more general domain than the `getFeed` thing. I don't want to maintain more `getRemote` something.

**Comment by jetwash** [comment]
I don't think maintenance would be much of an issue; the infrastructure for retrieving remote content is obviously already there (for `getJSON`/`getCSV`), and any bugs in the feed parsing belong in a library you don't maintain, so they wouldn't be your responsibility. It seems like this should only add a few lines of code to Hugo, since the hard parts are either already part of Hugo or in the feed library.

I can understand not wanting to pull in another library and bloat the executable, but IMHO the benefits from this vastly outweigh the costs there.

Since Hugo is your project obviously the final decision is yours, but I would suggest that you ask the community (on discourse, I guess) for opinions before closing this. If people are against it, or generally don't care, it's probably safe to close it, but I have a feeling a lot of people would be extremely interested in this.
