### ISSUE TITLE
What are the 'test' releases useful for?

### ISSUE THREAD

**Issue by leonklingele** [gohugoio/hugo#3866]
Since yesterday I'm alerted by my release checker about various `v0.xtest` / `vtestx` releases of hugo, 23 so far. All of them vanished from Github after a few minutes. Why are they pushed? What are they used for? Can't these tags be created without pushing them?

**Comment by leonklingele** [comment]
https://github.com/gohugoio/hugo/releases/tag/v0.51-test

![hugo-test-release](https://i.imgur.com/He4vRBy.png)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by leonklingele** [comment]
Hi @bep,

is this some kind of auto reply? How should the Hugo documentation help in this case? 🙀 
Seeing that you're the one who created the tags.. are these some release tool tests? No more releases were made after your reply. Guess the "issue" has already been fixed :)

**Comment by bep** [comment]
I don't answer questions on GitHub, hence the auto reply.

And no, it has not been fixed, so there may be more test releases.
