### ISSUE TITLE
Taxonomy as Permalink Configuration Value

### ISSUE THREAD

**Issue by dmgawel** [gohugoio/hugo#3884]
I'd like to propose a new permalink configuration value to join `:year`, `:day` et al. family: `:taxonomy`.

**Expected behavior:**

Given `:taxonomy[taxonomy_name]` is used in permalink config it is then converted to first term (slug) assigned to particular page.

Example: Let's assume we have following taxonomies:

```
taxonomies:
  series: "series"
```

and Page `content/movies/the-mask.md` with content:
```
---
title: "The Mask"
series: ["Comedy"]
---
```
and following permalink configuration:

```
[permalinks]
  movies = "/:section/:taxonomy[series]/:slug/"
```

Our movie page will be then available under `/movies/comedy/the-mask/`.

It might be also usable if one can enable generating aliases based on other terms assigned to page, but it's not necessary.

The same can be achieved via nested Sections, but it's less flexible from content authors perspective (taxonomies can be easily managed via CMS).

What do you think?

**Comment by vassudanagunta** [comment]
I really like this. To me `:taxonomy` would be more useful than `:year` and `:day` in permalinks.

**Comment by cristovaov** [comment]
Sorry for bumping this issue, but I would find this very useful too. 
> I really like this. To me `:taxonomy` would be more useful than `:year` and `:day` in permalinks.

Thank you for looking into this!

**Comment by coreyk** [comment]
This would indeed be very useful. Bump.

**Comment by dmgawel** [comment]
I've been thinking about this functionality for some time, maybe I'll be able to propose some PR. My only doubt at the moment is the situation when page does not have a desired taxonomy assigned to it. All the current permalink configuration values are always present (or have fallback).

Back to my example from original idea:

```
---
title: "The Mask"
---
```

```
[permalinks]
  movies = "/:section/:taxonomy[series]/:slug/"
```

What should Hugo do in such a situation?

I see two possible solutions:
1. Throw an error.
2. Skip the `:taxonomy` and output `/movies/the-mask/`.

WDYT?

**Comment by Nihhaar** [comment]
Any update on this?

**Comment by endlessuniverse** [comment]
@dmgawel Please, can you propose some PR with the second solution: to skip the taxonomy and output section + slug as fallback?
Thanks a lot!

**Comment by endlessuniverse** [comment]
@bep @moorereason @digitalcraftsman 
On second thought, I think the fallback permalink should be the configured one excluding the taxonomy term.
I plan to migrate a WordPress site to Hugo, which uses custom rewrite rules to set a taxonomy term as slug prefix.
Please consider this feature request 🙏 Thank you!!!
