### ISSUE TITLE
Cloak e-mail

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [gohugoio/hugo#3886]
Feature request: cloak email.

Take an email address like example@mail.com. If that was to appear on one of your posts/pages, it could easily be ‘scraped’ or ‘harvested’ automatically to add that email address to a spam list of some sort. Cloaking is all about making that harder to do.

[Joomla!](https://docs.joomla.org/How_to_cloak_email_addresses), [WordPress](https://wordpress.org/plugins/email-javascript-cloaker/) and other popular CMS provides feature named "cloak email". It cause replace any `<a href="mailto:example@mail.com">mailto:example@mail.com</a>` to uglified JavaScript which generate original mailto link after webpage was loaded in browser.

Proposal: implement build-in shortcode for it. It must be implemented in Go because uglify function is should not be trivial.

**Comment by konart** [comment]
Propasal: this should have fallback option (html+css) in case js in turned on. Something like this: https://stackoverflow.com/questions/21421948/protect-e-mail-address-with-css-only

**Comment by shazow** [comment]
Another option is to use an inline base64 data encoded image, if it doesn't have to be linked.

**Comment by dzwiedziu-nkg** [comment]
Email address should be readable by people with disables.

**Comment by danieka** [comment]
I've started working on this feature. I'm done with the html+css variant but it is quite limited, text not selectable, no link and I assume not readable in a screen reader. I think I'll be done with a js variant the next couple of days.

**Comment by danieka** [comment]
@dzwiedziu-nkg I've submitted a PR for this. Let me know if you think the obfuscation is to simplistic.

**Comment by martignoni** [comment]
This would still be a useful feature. What about integrating the pull request https://github.com/gohugoio/hugo/pull/3935?

**Comment by martignoni** [comment]
I still think this would be very useful :-)

**Comment by martignoni** [comment]
Still useful IMHO. Suggesting integration of PR #3935.

**Comment by martignoni** [comment]
Still a good way to minimize spam on a Hugo site.

**Comment by martignoni** [comment]
Just published the `cloakemail` shortcode as a Hugo component: https://github.com/martignoni/hugo-cloak-email. Credits goes to @danieka for the code.

This can be closed as far as I'm concerned.

**Comment by budparr** [comment]
@martignoni Thank you. You inspired me to a theme components section to the Awesome Hugo List: https://github.com/budparr/awesome-hugo
