### ISSUE TITLE
chocolatey package out of date

### ISSUE THREAD

**Issue by pdeva** [gohugoio/hugo#3887]
chocolatey still only has version 0.25.1 of hugo
https://chocolatey.org/packages/hugo/

please update to latest version...

**Comment by bep** [comment]
We don't maintain the Coholatey package -- you should contact the person who created it; we may in the future if we can get it into the build. Right now we have too much other stuff to do to keep track of all the different build managers.

**Comment by bep** [comment]
I'll reopen this as a tracking issue, but it will not happen tomorrow ...
