### ISSUE TITLE
Allow other types than maps in .Site.Data

### ISSUE THREAD

**Issue by felicianotech** [gohugoio/hugo#3890]
The following example YAML file cannot currently be used with Hugo:

```
# ./data/books.yml
- title: "Harry Potter and the Order of the Phoenix"
  author: "J.K. Rowlings"
  pages: 870
- title: "A Wrinkle in Time"
  author: "Madeleine L'Engle"
  pages: 240
- title: "My Side of the Mountain"
  author: "Jean Craighead George"
  pages: 175
```

This is because the root node here would be a YAML sequence (a.k.a a list), which is valid YAML but Hugo doesn't currently support.

This Issue originated in [Hugo Discussion](https://discourse.gohugo.io/t/using-a-list-as-the-root-node-of-a-yaml-data-template/8401).

**Comment by zealic** [comment]
I has tested data file format support for array type:

- [x] JSON
- [ ] YAML
- [ ] TOML
