### ISSUE TITLE
Add Internal Shortcode for Google Play and iTunes

### ISSUE THREAD

**Issue by pacollins** [gohugoio/hugo#3892]
Curious if we could implement an internal short code for getting the meta data for Google Play and iTunes, similar to Twitter, Instagram, Etc. This could be a useful addition for bloggers reviewing apps/music/shows/etc or just for developers to quick reference their app.

[iTunes API](https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/)

There is no official Google Play API, but there is an [unofficial API](https://code.google.com/archive/p/android-market-api/) and I have seen a couple more in my searching.

**Comment by Shadow53** [comment]
Thoughts from a user and theme developer:

There are so many possible shortcodes that people *may* want to use, that I think only the bare minimum should be included as internal shortcodes and the rest in a theme or the site's `layouts/shortcodes` directory itself.

Perhaps a better idea would be to have a set of gists or another method of having a shortcode showcase, similar to the theme showcase, where people can copy the ones they find useful.

Even if the showcase doesn't happen (and I can think of reasons why it wouldn't), I think this case is particular enough that it should be implemented by a theme developer or site owner, not as part of Hugo. Twitter/Instagram/etc. are ubiquitous enough that it makes some sense to include them as internal shortcodes.

**Comment by pacollins** [comment]
I would support a shortcode showcase as well (similar to plug-ins). That being said, I would say iTunes and Google Play are as ubiquitous as the others due to smart phone prevalence.
