### ISSUE TITLE
build: Snap pipeline stopped working

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3908]
* https://launchpad.net/~gohugoio/+snap/hugo says Hugo 0.28 is built OK.
* https://uappexplorer.com/snap/ubuntu/hugo shows Hugo 0.26 as latest

I have no clue, but this Snappy build chain feels all but snappy. 

/cc @elopio @anthonyfok @felicianotech @snapcore

**Comment by anthonyfok** [comment]
Thank you for bringing this up, @bep.

I was wondering about the same shortly after @bep released 0.27.1 on Sep 13,
so I logged in via https://dashboard.snapcraft.io/dev/snaps/ and noticed that while 0.27.1 was built successfully, it was held up: "Revision waiting for review of a previous upload."

The first version where it got stuck on was 0.27, built on 2017-09-11, which is still "Pending Review" after two weeks and thus 0.27, 0.27.1 and now 0.28 remained unpublished to this day.

Hugo snap has been reviewed before it got published in the stable channel, and everything had been fine up to 0.26.  So, what had triggered the need for the snap to be reviewed again?

**Comment by elopio** [comment]
@bep thanks for reporting, and @anthonyfok thanks for the triage.

I've filed https://bugs.launchpad.net/snapstore/+bug/1719382 and somebody from the store team is looking at it right now. Sorry for this.

**Comment by elopio** [comment]
It's already unstuck. We are checking now what went wrong, and I'm filing a few bugs because finding the initial review where it failed was a pain. We need to improve that dashboard.

If you have any other pain points, please let me know so we can put that on the roadmap too.

pura vida.

**Comment by anthonyfok** [comment]
Hi @elopio and Daniel:

Thank you for your quick resolution of this issue.
I have went ahead and pressed the "Release" button in the Snap dashboard
to release the now unstuck snaps (0.27, 0.27.1 and 0.28 for all 5 architectures)
to the Stable channel, and I am happy to report that the Hugo snap is up-to-date once again:

```
$ snap find hugo
Name  Version  Developer     Notes  Summary
hugo  0.28     hugo-authors  -      Fast and Flexible Static Site Generator

$ snap refresh
hugo 0.28 from 'hugo-authors' refreshed

$ snap run hugo version
Hugo Static Site Generator v0.28 linux/amd64 BuildDate: 2017-09-25T09:33:43-06:00
```

Thank you also for opening https://bugs.launchpad.net/snapstore/+bug/1719382 to follow up.
Hope you will be able to find out what happened.

Cheers,
Anthony

**Comment by anthonyfok** [comment]
For completeness sake: The issue was probably first brought up in the discussion forum here:
https://discourse.gohugo.io/t/hugo-0-27-1-released/8361/4
