### ISSUE TITLE
Add a Madoko external helper like there is for Asciidoc, etc.

### ISSUE THREAD

**Issue by zivbk1** [gohugoio/hugo#3912]
I would like to have some site content in Madoko source format. [https://www.madoko.net/](https://www.madoko.net/)

The file extension for Madoko files is .mdk [http://madoko.org/reference.html](http://madoko.org/reference.html)

The command line processor for Madoko files is here. [https://www.npmjs.com/package/madoko](https://www.npmjs.com/package/madoko)

You can use the -f or --fragment command line argument to generate a rendered content fragment instead of a full document. [http://madoko.org/reference.html#sec-commandline](http://madoko.org/reference.html#sec-commandline)

**Comment by miltador** [comment]
The support of `Madoko` could be added to [shimgo](https://github.com/tychoish/shimgo) and integrated using shimmed approach, see PR #3842.

**Comment by bep** [comment]
As this is the first time I hear of it, you have to back if up with some data: How widely used is this?

**Comment by bwklein** [comment]
@bep I received this reply from the developer Daan Leijen who works at Microsoft Research.

> Just shortly, there are now 47000 unique users that used the online system to save a document to a cloud account (like dropbox or onedrive). Daily, there are about 200 users active online. Of course, I cannot see how often people use Madoko as a command line tool but it has been downloaded about 5000 times this year. Madoko-local is quite popular as it allows one to access files on the hard drive directly and run latex locally, but again, I cannot see any statistics there. 

I hope this helps to give this a sense of scale. Daan recently moved the project to GitHub, which you can find here. [https://github.com/koka-lang/madoko](https://github.com/koka-lang/madoko)

Thank you for your consideration.
