### ISSUE TITLE
Incorrect comment and error syntax highlighting in Makefile code blocks using Chroma

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#3917]
Hello,

I [originally opened this issue on the chroma repo][2], but @alecthomas is unable to reproduce this issue using standalong `chroma` CLI binary.. me too.

Here is an example Makefile:

```makefile
# Define below you only need info documentation, the default includes html and pdf
ORG_MAKE_DOC = info pdf card # html
```

Doing `chroma Makefile`, I get:

![image](https://user-images.githubusercontent.com/3578197/30920985-50be5e7e-a373-11e7-8108-f1cd28c6e815.png)

But the highlighting is wrong on hugo+chroma generated HTML:

## Live link

https://scripter.co/building-org-development-version/#customizing-local-dot-mk

The live link can change, so also have the screenshot below

## Markdown source

[Link][1]

```md
-   **`infodir`:** Org Info installation directory. I like to keep the
    Info file for development version of Org in a separate
    directory.

    ```makefile
    infodir = $(prefix)/org/info # Default: $(prefix)/info
    ```
-   **`ORG_MAKE_DOC`:** Types of Org documentation you'd like to build by
    default.  Below enables generation of the Info and
    PDF Org manuals and the Org reference cards (in
    PDF too).

    ```makefile
    # Define below you only need info documentation, the default includes html and pdf
    ORG_MAKE_DOC = info pdf card # html
    ```
```

## HTML code

```html
<div class="highlight"><pre class="chroma"><code class="language-makefile" data-lang="makefile"><span class="nf">infodir = $(prefix)/org/info # Default</span><span class="o">:</span><span class=""> </span><span class="k">$(</span><span class="nv">prefix</span><span class="k">)</span><span class="">/</span><span class="n">info</span></code></pre>
</div></li>

<li><p><strong><code>ORG_MAKE_DOC</code>:</strong> Types of Org documentation you&rsquo;d like to build by
default.  Below enables generation of the Info and
PDF Org manuals and the Org reference cards (in
PDF too).</p>
<div class="highlight"><pre class="chroma"><code class="language-makefile" data-lang="makefile"><span class="c"># Define below you only need info documentation, the default includes html and pdf
</span><span class="c"></span><span class="err">ORG_MAKE_DOC</span><span class=""> </span><span class="err">=</span><span class=""> </span><span class="err">info</span><span class=""> </span><span class="err">pdf</span><span class=""> </span><span class="err">card</span><span class=""> </span><span class="err">#</span><span class=""> </span><span class="err">html</span></code></pre>
</div></li>
```

## Screenshot

![image](https://user-images.githubusercontent.com/3578197/30921305-2a3d39a4-a374-11e7-8496-90b2ef79c0a0.png)

## Hugo + Chroma versions

> Hugo Static Site Generator v0.30-DEV-A354D130:CHROMA-33F604C8 linux/amd64 BuildDate: 2017-09-27T10:25:05-04:00

I built the `hugo` binary using https://gist.github.com/kaushalmodi/456b5ea26b3e869e5d63d4a67b85f676

[1]: https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/blame/a6d11abfc854f07adcb990f856bfcc4f5077d9a9/content/posts/building-org-development-version.md#L50-65

[2]: https://github.com/alecthomas/chroma/issues/42

**Comment by moorereason** [comment]
The issue appears to be with the last line in the code block.  If I put a simple comment line at the end of the code block, the lines above highlight properly.

**Comment by kaushalmodi** [comment]
Thanks! I can now recreate that in chroma too. My editor was auto-adding final newline to the test Makefile, so I never saw it. Probably @alecthomas also has it set that way. Once I allowed the file to not end in a newline, I can recreate the issue with standalone `chroma`.

![image](https://user-images.githubusercontent.com/3578197/30931666-61623550-a393-11e7-98cb-149e09616a73.png)
