### ISSUE TITLE
RSS template should use `PublishDate`

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3918]
``` 
<pubDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" | safeHTML }}</pubDate>
```

**Comment by wwsean08** [comment]
I'd like to pick this up but is there a specific template that this should be applied to or is this just generic updating all themes rss templates?  Mostly asking since I can't find an RSS template in the examples and from searching the hugo codebase.

**Comment by bep** [comment]
@wwsean08 I think we will have to wait until we decide what to do with #3977 -- this isn't as clear as I thought when I opened this issue.

**Comment by jbpratt78** [comment]
Hey @bep, any thoughts since your last comment? Hate to let it go stale :smile:
