### ISSUE TITLE
section/baseof.html ignored

### ISSUE THREAD

**Issue by jbrodriguez** [gohugoio/hugo#3919]
Given this tree

```
hugo
├── content
│   └── posts
│       └── one.md
└── layouts
    ├── _default
    │   └── baseof.html
    ├── partials
    │   └── meta.html
    ├── posts
    │   └── list.html
    └── section
        └── baseof.html
```
I expected ```section/baseof.html``` to be used as base for ```http://<site>/posts```, but it's being ignored in favor of ```_default/baseof.html```.

I tried ```_default/section-baseof.html``` with the same result (not being picked up).

hugo 0.27.1

**Comment by bep** [comment]
See https://github.com/gohugoio/hugoDocs/issues/218

The docs is a little confusing about this, but the main logic is that it looks in the same folder where the main layout lives and then walks up the chain. If you put your base template in /posts it should work better.

**Comment by mjmeyer** [comment]
So given:
```
hugo
├── content
│   └── posts
│       └── one.md
└── layouts
    ├── _default
    │   ├── baseof.html
    |   └── single.html
    ├── partials
    │   └── meta.html
    └── posts
        └── baseof.html
```

Should I expect /posts/one/ to render with /layouts/posts/baseof.html or with /layouts/_default.baseof.html?

With 0.41 I am finding that unless there is a /layouts/posts/single.html, the baseof.html is always coming from _default...which sot of jives with the walking up the chain you describe but seems different than the docs at https://gohugo.io/templates/base/, unless I am misunderstanding something.
