### ISSUE TITLE
Add facebook shortcode

### ISSUE THREAD

**Issue by KmBKeef** [gohugoio/hugo#3922]
Well if there is one for twitter why isnt there one for facebook

**Comment by rdwatters** [comment]
I’m curious about the expected behavior here. The Twitter shortcode embeds a single tweet. What would this embed?

**Comment by KmBKeef** [comment]
Just like amp's facebook and facebook-video [shortcodes](https://gohugo-amp.gohugohq.com/shortcodes/page/2/)

**Comment by kefahi** [comment]
The expected behavior is to embed a single facebook post or video
Here is a direct example from gohugo-amp

```
{{< amp-facebook width="300" height="400" href="https://www.facebook.com/zuck/posts/10102593740125791" layout="responsive" >}}
{{< amp-facebook-video width="680" height="400" href="https://www.facebook.com/zuck/videos/10102509264909801/" layout="responsive" >}}
```

**Comment by routetonull** [comment]
+1 a shortcode to embed a FB post
