### ISSUE TITLE
Is "front matter" just metadata?

### ISSUE THREAD

**Issue by peterlindstrom123** [gohugoio/hugo#3926]
I'm new to Hugo, and it seems to me that "front matter" is just metadata on a piece of content.

If that's the case, how about just calling it metadata? 

Now when you're a new user and see the term "front matter", it's just something you don't understand. It sounds like something special, but it seems it's not. 

But you don't know that when starting out, so it's just a drag on learning to use Hugo!

Another strange thing is that I keep seeing pieces of documentation where there's some code from some obsolete version of the author's website. The code is too old to use the current features that it would be using right now, so it's misleading, but there's usually a comment to that effect.

But if you're going to take the time to write a separate comment about how the code snippet above it is obsolete, why not just fix the code snippet instead? Or if that's too much trouble, maybe just leave it out.

When someone is learning to use Hugo, he doesn't want to keep seeing obsolete code and trying to evaluate whether some of it is still relevant to him, and which parts. The fact that the code is still there implies someone thought it was still useful, but a new user isn't equipped to evaluate that.

**Comment by bep** [comment]
This looks like suggestion for the Hugo docs. Could you post this issue at https://github.com/gohugoio/hugoDocs
