### ISSUE TITLE
Misleading config in Multilingual Mode documentation

### ISSUE THREAD

**Issue by Silvia-** [gohugoio/hugo#3928]
The configuration example in https://gohugo.io/content-management/multilingual/#configure-languages suggests that `params` can be translated within `[Languages.XX.params]`, for example:
```
[Languages.fr.params]
linkedin = "lien-francais"
```
This doesn't work, as explained in #3871 , and should be:
```
[languages.fr]
linkedin = "lien-francais"
```

The examples may also need to be adjusted to TOML case-sensitiveness (I had issues with mixed `[Languages.XXX]` and `[[languages.YYY]]`, solved by using lowercase only).

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues

**Comment by Silvia-** [comment]
I'm sorry @bep , will do, thanks!
