### ISSUE TITLE
Add closing partials

### ISSUE THREAD

**Issue by ianbrandt** [gohugoio/hugo#3929]
It would be great to have closing partials that support `.Inner` content (similar to that of [closing shortcode templates](https://gohugo.io/templates/shortcode-templates/#inner)).

Here's a Bootstrap-y example, 'layouts/partials/closingsection.html':

```html
<section>
    <div class="container">
        {{ .Inner }}
    </div>
</section>
```

Example usage in a 'single.html' template that is overriding a baseof.html template's "main" block:

```html
{{ define "main" }}
    {{ partial "closingsection" . }}
        <div class="row">
            <div class="col-md">I'm a responsive section.</div>
            <div class="col-md">With two columns.</div>
        </div>
    {{ end }}
{{ end }}
```

Even better would be closing partials that support blocks, e.g. 'layouts/partials/blockysection.html':

```html
<section>
    <div class="container">
        <div class="row">
            <div class="col-md">
                {{ block "header" . }}
                    <h1>{{ .Header }}</h1>
                {{ end }}
            </div>
            <div class="col-md">
                {{ block "body" . }}
                    <p>{{ .Body }}</p>
                {{ end }}
            </div>
        </div>
    </div>
</section>
```

And in the 'single.html':

```html
{{ define "main" }}
    {{ partial "blockysection" ( dict "Header" "Section #1" "Body" "Hi, I'm section #1." ) }}
    {{ partial "blockysection" ( dict "Header" "Section #2" ) }}
        {{ define "body" }}
            <p class="lead">{{ .Header }} uses the default header 
                block, but has a custom body.</p>
            <p>Perhaps with a bunch more HTML...</p>
        {{ end }}
    {{ end }}
    {{ partial "blockysection" . }}
        {{ define "header" }}
            <h3 class="text-muted">I've got a custom header.</h3>
            <h1>Section #3</h1>
        {{ end }}
        {{ define "body" }}
            <p class="lead">And a custom body.</p>
        {{ end }}
    {{ end }}
{{ end }}
```

The latter is really what I need, so shortcode templates aren't an answer unless I combine multiple of them, and then the opening and closing tags would span multiple templates.  That's no fun on account of the unclosed/unopened tag warnings in my IDE.  Plus, I'm working on a very HTML-heavy site, so authoring in typed single templates and partials just feels more natural than working in Markdown and shortcodes.

**Comment by ianbrandt** [comment]
See also: https://discourse.gohugo.io/t/block-in-a-partial-and-defining-in-a-page/.

**Comment by ianbrandt** [comment]
Searching around for some prior art, Handlebars has this with their [block syntax](http://handlebarsjs.com/partials.html#partial-block) and specially-named `@partial-block` partial.

**Comment by bep** [comment]
Just a quick note: I'm pretty sure this isn't currently possible with the Go templates, so this should probably be raised at 

https://github.com/golang/go/issues

But I suggest someone looks a little harder into this issue first.
