### ISSUE TITLE
XPath Find and Replace

### ISSUE THREAD

**Issue by jhabdas** [gohugoio/hugo#3930]
Currently Hugo provides two template functions for string parsing within templates:

- [`findRE`](https://gohugo.io/functions/findre/)
- [`replaceRE`](https://gohugo.io/functions/replacere/)

These are useful for basic parsing, but when dealing with XML or HTML regex [is problematic](https://stackoverflow.com/a/1732454/712334). Is there a way I can use XPath instead? Perhaps something like [Scrapy selectors](https://doc.scrapy.org/en/latest/topics/selectors.html)?

**Comment by bep** [comment]
>Is there a way I can use XPath instead?

No, and this **might** have been considered if this was part of Go's stdlib, but I'm not dragging any 3rd party libraries in for this.
