### ISSUE TITLE
Use semver even in minor updates

### ISSUE THREAD

**Issue by nervo** [gohugoio/hugo#3936]
In order to ease maintenance, and continuous integrations, you should use semver even in minor updates.
That means no more `0.28` or `0.29`release, but `0.28.0` and `0.29.0` :)

**Comment by bep** [comment]
Point taken.

**Comment by bep** [comment]
Which is a way of saying we're not doing it: I'm not sure what it solves or makes easier, but I have logic in my release process that I'm not too interested in putting more work into to adapt to this, and ... I like them as is.

**Comment by nervo** [comment]
Seems legit, thx for clarification :)
