### ISSUE TITLE
Ubuntu 16.04 gohugo v0.30-DEV  -- no autoupdate on page edit

### ISSUE THREAD

**Issue by MikhailKlemin** [gohugoio/hugo#3942]
Hello!
I installed and compiled with Go

I just started checking up quick start with ga-hugo-theme it's very nice documentation out there. 
But I have to restart (ctr-c/start)  server  in order to get content pages updated :-( 
I have googled I see ppl have issues with this as well, but I could not found any solution... 

I use Visual Studio Code, but I also tried Gedit - same result.

**Comment by bep** [comment]
Duplicates #3850
