### ISSUE TITLE
CSS changes appear in livereload but disappear on hard reload

### ISSUE THREAD

**Issue by ernsheong** [gohugoio/hugo#3944]
I have a file say `app.css` that initially has some CSS:

```
.foo {
  color: red;
}
```
(version 1)

I add a class to my HTML, and then also add a class to my CSS:

```
.foo {
  color: red;
}

.bar {
  color: green;
}
```
(version 2)

Hugo's live reload reflects the changes in my HTML, but when I do a manual hard reload, the changes disappear and the `app.css` file in my HTML reflects version 1 only. Something is not right here...

Hugo Version: Hugo Static Site Generator v0.29 darwin/amd64 BuildDate: 2017-10-05T16:49:44+08:00

**Comment by ernsheong** [comment]
Furthermore, a restart of server does not reflect the changes as well and the CSS file remains in version 1, even though it is in version 2 in the `static` directory.

**Comment by ernsheong** [comment]
![image](https://user-images.githubusercontent.com/1343284/31261877-a5f7cdd6-aa89-11e7-8559-a9b90e0a0b6e.png)

I was referencing my css with an absolute path, because I share the <head> partial across all my pages. These might be a contributing factors to this issue: 1) the CSS reference is in a partial, and 2) the CSS reference is absolute.

**Comment by bep** [comment]
This is a browser cache issue and nothing (more) that Hugo can do.

Either

1) Turn off the cache in chrome dev console
2) Run with `hugo server --noHTTPCache`
