### ISSUE TITLE
Serving is broken when `uglyURLs: true`

### ISSUE THREAD

**Issue by manastungare** [gohugoio/hugo#3945]
When `--uglyURLs` is true, `hugo server` returns 404s when accessing a URL.

E.g. when `--uglyURLs` is false:
`directory/filename.md` is rendered to `directory/filename/index.html` and served at `directory/filename`.

When `--uglyURLs` is true:
`directory/filename.md` is rendered to `directory/filename.html` but `directory/filename` returns a 404.

Expected:
`hugo server` should continue to serve pages correctly when `--uglyURLs` is set to true.

**Comment by bep** [comment]
This is as designed. UglyURLs means just that. If you have more questions, take it at https://discourse.gohugo.io/

**Comment by manastungare** [comment]
Wow, so far my experience with the Hugo community has been extremely negative.

Thanks for the quick response at least.

**Comment by bep** [comment]
The Hugo community is very supported, but you will have to ask questions on https://discourse.gohugo.io/

This issue tracker is for bug/feature requests only.

**Comment by manastungare** [comment]
The documentation for `uglyURLs` does not say that serving will be broken, so if this is your design decision, at least it should be documented: https://gohugo.io/content-management/urls/#ugly-urls

If something does not work as expected or documented, it is reasonable to expect that users will think it is a bug, and file a bug report for it. This specific issue is not a matter of open-ended discussion, as you suggest it should be, hence my bug report.

If the team is not interested in receiving bug reports like this, that’s fine too. In that case, the policy should be to always post on the forum first, and only for core maintainers to decide whether something is a bug worth fixing and then to file it here.

In your earlier reply, there was also no explanation (not that you owe one); it was simply closed without comment. My previous report with multiple issues (#3906) also got a similar response, hence the general feeling I got from the community was very hostile, even if you or other committers did not intend it to be.

**Comment by bep** [comment]
I you can copy your reply above into a thread on the forum, then I will give you a proper answer.
