### ISSUE TITLE
Inconsistent "children" shortcode results

### ISSUE THREAD

**Issue by jcw** [gohugoio/hugo#3946]
I'm seeing random weirdness in the handling of the `{{% children ... %}}` shortcode - sometimes it shows up in the sidebar (disappearing entries), sometimes in the main pages (missing descriptions).

When I edit a page while viewing in live mode, the front page turns into a mess (as if all subpages are included) - everything  is back to normal after restarting Hugo. I've reported it as <https://github.com/matcornic/hugo-theme-learn/issues/79>, but now I think it's not a problem of the theme but of the shortcode in Hugo itself.

As an example (but the problem really changes on each edit, and even across platforms), see the [docs site](https://docs.jeelabs.org) which is auto-generated from [this GitHub repo](https://github.com/jeelabs/docs). At the moment, the front page shows this:

<img width="232" alt="screen shot 2017-10-06 at 16 32 12" src="https://user-images.githubusercontent.com/148955/31282862-1e33181c-aab4-11e7-91ac-872cebfc4a59.png">

Note the missing descriptions in the first and last entries (IIRC, the problem is always in the first/last). The site's sidebar menu (also auto-generated in the [Learn theme](https://github.com/matcornic/hugo-theme-learn) I presume) also occasionally drops entries, although this only appears to happen with nested menus. Generating from the _same_ files on Mac produces an empty description, but only for the _first_ entry. Very odd...

This is with the Hugo 0.29 binary releases (64-bit) on the latest MacOS 10.13 (for live editing) and Ubuntu 16.04.3 LTS (for generating the final static version).

PS. I can force proper descriptions by saving the home page again while in live mode.

**Comment by Jos512** [comment]
I think this is a better question for the [forums](https://discourse.gohugo.io/). 

The `children` shortcode is from the Learn theme [here](https://github.com/matcornic/hugo-theme-learn/blob/master/layouts/shortcodes/children.html), and from your description I can't tell what the Hugo bug is.

It seems from the description that the shortcode behaves inconsistently. Which is of course a problem, but not necessarily a Hugo issue. From your post I'm more inclined that there's a theme issue or that some theme settings aren't configured properly.

Could you open a topic at the forum? That save the Hugo developers having to provide support on GitHub.

(If this is a Hugo issue, could you share any error messages you got when using that shortcode?)
