### ISSUE TITLE
There is no man page

### ISSUE THREAD

**Issue by nielsk** [gohugoio/hugo#3948]
I installed hugo from source and "man hugo" brings only a "man: No entry for hugo in the manual." Since I can't find anything in the sources about a man page, it seems it is just missing.

There should be man page, so that one can use hugo without going to the website and have the documentation on the cli available. Since hugo is a tool mostly on the cli, documentation should be readable there. Actually there should be at least two:
hugo(8) which explains the general configuration of hugo 
hugo-config(5) (since hugos config can have different file endings) explaining the config-file

**Comment by bep** [comment]
See https://gohugo.io/commands/hugo_gen_man/

This is part of the `brew` installation and some other, and I guess we could do better in this area. But for the source build, you have to build it yourself.

**Comment by nielsk** [comment]
Thanks @bep 
Maybe add this step to the installation-instructions when installing from source. That would already be an improvement.
