### ISSUE TITLE
disableKinds works incorrectly

### ISSUE THREAD

**Issue by Jos512** [gohugoio/hugo#3952]
~~~
hugo env
Hugo Static Site Generator v0.29 windows/amd64 BuildDate: 2017-10-09T07:56:25+02:00
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.9"
~~~

## No disable kinds usage
This command:

~~~
hugo -D
~~~

Renders in `/public/` the following:

~~~
public
├── categories
|   ├── music
|   |   ├── index.xml
|   |   └── index.html
|   ├── movies
|   |   ├── index.xml
|   |   └── index.html
|   ├── index.xml
|   └── index.html
├── tags
|   ├── reviews
|   |   ├── index.xml
|   |   └── index.html
|   ├── soundtrack
|   |   ├── index.xml
|   |   └── index.html
|   ├── index.xml
|   └── index.html
~~~

This is correct, because without `disableKinds` set to disable taxonomy and taxonomy terms I would expect this.

## Disable taxonomy terms
This command:

~~~
hugo --disableKinds=taxonomyTerm
~~~

Renders:

~~~
public
├── categories
|   ├── music
|   |   ├── index.xml
|   |   └── index.html
|   ├── movies
|   |   ├── index.xml
|   |   └── index.html
├── tags
|   ├── reviews
|   |   ├── index.xml
|   |   └── index.html
|   ├── soundtrack
|   |   ├── index.xml
|   |   └── index.html
~~~

I think this is incorrect, because `taxonomyTerm` here doesn't disable the taxonomy terms pages but instead the `index.html` of the main taxonomies (`/tags/index.html` and `/categories/index.html`).

In other words, `--disableKinds=taxonomyTerm` term behaves here like `--disableKinds=taxonomy` should. I base that assumption of how it should work based on the official [definition](https://gohugo.io/content-management/taxonomies/#what-is-a-taxonomy) of 'taxonomy' and 'taxonomy term'.

## Disable taxonomies
With this command:

~~~
hugo --disableKinds=taxonomy
~~~

The website renders like this:

~~~
public
├── categories
├── tags
~~~

Now the taxonomy folders generate, but they're empty. I think this is incorrect too, because the taxonomy terms should remain. (Otherwise there's no point in having the additional `taxonomyTerm` setting.)

## Disable both taxonomies and taxonomy terms
With this command:

~~~
hugo --disableKinds=taxonomy,taxonomyTerm
~~~

Both the `/tags/` and `/categories/` folder don't generate. This behaviour is exactly like [documented](https://gohugo.io/content-management/taxonomies/#hugo-taxonomy-defaults) so correct. 

But in practice this is the same as using `--disableKinds=taxonomy`, with only the additional benefit that `taxonomyTerm` deletes the empty taxonomy folders.

I don't think `taxonomyTerm` is added only to remove empty folders, so I'd say that behaviour is odd too.

----

* I don't have the `disableKinds` configuration variable set in my configuration file, so there's no conflict between the command flag and configuration file.
* I have the `cleanDestinationDir` configuration variable set to `true` to make sure there are no files left over from the previous build.

**Comment by pamubay** [comment]
your example above actually works correctly according documentation in [Taxonomy Templates Docs](https://gohugo.io/templates/taxonomy-templates/)

## Disable Taxonomy Terms
according the docs on [Taxonomy Templates Docs](https://gohugo.io/templates/taxonomy-templates/)

> A taxonomy terms page will be rendered at `example.com/<PLURALTAXONOMYNAME>/` (e.g., http://spf13.com/topics/)

in your example `categories` and `tags` are the **Taxonomy Terms**

## Disable Taxonomy
according the docs on [Taxonomy Templates Docs](https://gohugo.io/templates/taxonomy-templates/)

> A taxonomy will be rendered at `/PLURAL/TERM/` (e.g., http://spf13.com/topics/golang/)

In your example `categories/music` and `categories/movies` is the **Taxonomy**

### Why `categories` and `tags` folder generated?
Because you did not set any `[taxonomies]` configuration in your config file. as the default HUGO will set `categories` and `tags` as your `[taxonomies]` config.

**Yes**, the definition of Taxonomy and TaxonomyTerms are not same between documentation in [Content Management / Taxonomies](https://gohugo.io/content-management/taxonomies/) and [Templates / Taxonomy Templates](https://gohugo.io/templates/taxonomy-templates/)

as in [Content Management / Taxonomies](https://gohugo.io/content-management/taxonomies/) explained like this
```
Moonrise Kingdom            <- Content
    Actors                  <- Taxonomy
        Bruce Willis        <- Term
        Bill Murray         <- Term
    Director                <- Taxonomy
        Wes Anderson        <- Term
```

So, the documentation need to be revised, we need to clearly define what we called as `taxonomy` and `taxonomyTerm`

**Comment by Jos512** [comment]
Thanks for your thorough reply Pamubay. I think you're on to something. If your explanation holds for the Hugo team, the [Content management / Taxonomies](https://gohugo.io/content-management/taxonomies/) page is indeed incorrect.

So my website example has the following meanings for the taxonomies:

~~~
website                     <- Content
    categories              <- Taxonomy term
        music               <- Taxonomy
        movies              <- Taxonomy
    tags                    <- Taxonomy term
        reviews             <- Taxonomy
        soundtrack          <- Taxonomy
~~~

With this explanation:

(1) `hugo --disableKinds=taxonomyTerm` works correctly because it disables the `index.html` and `index.xml` files in `/tags/` and `/categories/`.

(2) `hugo --disableKinds=taxonomy` still works **incorrectly**. Because with that command, the `index.html` and `index.html` in `/tags/` and `/categories/` do not render (as mentioned above). 

But those files in `/tags/` and `/categories/` *should* render, because if I disable my taxonomies (reviews, soundtrack, music, movies), the taxonomy terms (tags, categories) pages should still appear.

Otherwise, there's no point in having the combination of `--disableKinds=taxonomy,taxonomyTerm` to turn both taxonomies and taxonomy terms off. In practice, `--disableKinds=taxonomy` already turns off both (with only the empty taxonomy term folders kept). 

> Why categories and tags folder generated?
> Because you did not set any [taxonomies] configuration in your config file. as the default HUGO will set categories and tags as your [taxonomies] config.

I do have the taxonomies configured in my `config.toml` file, like so:

~~~
[taxonomies]
    category = "categories"
    tag = "tags"
~~~

So this doesn't seem to explain why `--disableKinds=taxonomy` gives empty folders with no taxonomy and taxonomy term pages.

> So, the documentation need to be revised, we need to clearly define what we called as `taxonomy` and `taxonomyTerm`.

I fully agree with that. It's a serious topic because taxonomies are already abstract enough for beginners that conflicting docs pages are terrible. If it were not for you I would never have figured out that some doc pages define taxonomy and taxonomy term differently. Thanks! 😄

**Comment by bep** [comment]
>Otherwise, there's no point in having the combination of --disableKinds=taxonomy,taxonomyTerm to

What happens here, I'm pretty sure, is this:

* If you disable taxonomies, Hugo creates no taxonomies.
* If Hugo creates no taxonomies for a term, Hugo does not create the Page for the term (even if it is enabled)

So you may have a point in that the combination above does not make sense, but it is fairly simple: Don't use it. We're not adding any validation or similar to the `disableKinds` value. That is up to the user.
