### ISSUE TITLE
Menu items inconsistency

### ISSUE THREAD

**Issue by 0xbaadf00d** [gohugoio/hugo#3953]
Sometime items from left menu just disappear (tested with Hugo 0.25.1 and 0.29). I said sometime, cause the issue appear few time (about 1 time / 4 "compilation")

By example I have the following left menu:

```
Book 1
   - Page 1
   - Page 2
   - Page 3
Book 2
   - Chapter 1
         - Page 1
         - Page 2
         - Page 3
   - Chapter 2
         - Page 1
         - Page 2
```

Sometime, when I visit a page (random, issue is not consistent) the left menu remove some links, by example, the above left menu become

```
Book 1
   - Page 1
   - Page 2
   - Page 3
Book 2
   - Chapter 1
         - Page 1
         - Page 2  [VISITED PAGE]
```

![image](https://user-images.githubusercontent.com/1005086/31346240-bd4872d8-ad18-11e7-8920-4ff574521d9d.png)

![image](https://user-images.githubusercontent.com/1005086/31574357-adad0d5c-b0ce-11e7-8b78-703fe1d8977d.png)

With `-v` (verbose), I see no warnings or errors during generation...

**Comment by MunifTanjim** [comment]
Maybe the problem is in your theme's implementation. Which theme are you using?

**Comment by 0xbaadf00d** [comment]
Hi @MunifTanjim 

I'm using the theme "learn" (https://github.com/matcornic/hugo-theme-learn). Here the layout who render the left menu : https://github.com/matcornic/hugo-theme-learn/blob/master/layouts/partials/menu.html
