### ISSUE TITLE
Partial inside Range

### ISSUE THREAD

**Issue by marekmaurizio** [gohugoio/hugo#3958]
The layout:
`
{{ range $service := .Site.Data.pages.services }}
    {{ partial "_service.html" . }}
{{ end }}
`
The partial:
`
<div class="service">
	<a href="{{ $service.url }}" target="_blank">
		<i class="fa fa-{{ $service.icon }}"></i>
		<h3>{{ $service.name }}</h3>
	</a>
</div>
`

How do I access $service inside the partial?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
