### ISSUE TITLE
`.Truncated` not true for manual summary split with no content

### ISSUE THREAD

**Issue by jhabdas** [gohugoio/hugo#3960]
Given the following `md` file in its entirety with manual [summary split](https://gohugo.io/content-management/summaries/):

```
+++
title = "3 Coin 8 GPU GTX1060 3GB Mining Rig"
date = 2017-10-11T16:29:45+08:00
description = "$3000 Mining Rig Build, 8x GTX1060 3GB Build + Performance (ETH/ZEC/XMR)"
youtube = "jMjyZl3ri1E"
build = "3-coin-8-gpu-gtx1060-3gb"
todo = [
  "add newegg referral links"
]
+++
<!--more-->
```

The value of the [Page variable](https://gohugo.io/variables/page/) `.Truncated` is not true. My current workaround is to add a unicode whitespace following the manual summary split, e.g.

```html
<!--more-->&#x20;
```

**Comment by bep** [comment]
>The value of the Page variable .Truncated is not true. 

So, there is **no content after the summary**. That is **not truncated** in my head. Can you explain why you mean this is wrong behaviour?

**Comment by jhabdas** [comment]
The mere presence of a manual summary split should trigger `.Truncated` be truthy regardless of the presence of additional content—otherwise it's not fully manual.

**Comment by bep** [comment]
>otherwise it's not fully manual.

Who said anything about fully manual?

**Comment by jhabdas** [comment]
My inner dialog spoke to me. If the tin says `manual` (as in ”manual summary split”) I'd expect more control. Of course I'm satisfied with my workaround—it is a bit of an edge case I admit. Will close this since I know you have better things to be doing @bep.

**Comment by bep** [comment]
For completeness:

I, and I guess many others, have post listings with conditionals ala ´if .Truncated Read More`. If we changed the meaning of `Truncated` (which now means: There are content below summary) that would be a glass breaking change that would require a really good reason.
