### ISSUE TITLE
Download v1 release of Mage for building

### ISSUE THREAD

**Issue by natefinch** [gohugoio/hugo#3966]
I just cut a release of mage (finally, I know), so there are official v1 binaries that will give you repeatable builds.

https://github.com/magefile/mage/releases/tag/v1

**Comment by bep** [comment]
Is there a good reason why you didn't include the checksums in the release? I can download and calculate myself, but it would help with automation (and reduce work) if you just included that file.

**Comment by natefinch** [comment]
I uploaded them after.... they're there

**Comment by bep** [comment]
OK; Goreleaser can generate these for you as well, if you did not know.

**Comment by natefinch** [comment]
yeah, it was just easier to do it manually this time, than try to figure out goreleaser (since I already had the script to create the binaries).  I'll do that for next time.

**Comment by bep** [comment]
I will update CircleCi (used for the release), but the rest will have to use go get for a while longer.

**Comment by natefinch** [comment]
That goroot problem is now fixed in v1.0.1 - https://github.com/magefile/mage/releases/tag/v1.0.1 and I use goreleaser to put the binary & license in a tar.gz

**Comment by natefinch** [comment]
nevermind, no it's not

**Comment by natefinch** [comment]
For real, fixed this time, checked by two different people in docker and not.
https://github.com/magefile/mage/releases/tag/v1.0.2

**Comment by Hanzei** [comment]
I would like to work on this. Would someone assign me?

**Comment by bep** [comment]
This is not relevant anymore. We use Go Modules and get the correct version that way.
