### ISSUE TITLE
gohugo.io rss / atom is invalid

### ISSUE THREAD

**Issue by gmtju52** [gohugoio/hugo#3975]
HI,

I use the feed  https://github.com/gohugoio/hugo/releases.atom

The generated links are wrong: /gohugoio/hugo/releases/tag/v0.30
this ist not a correct URL.
I'm using JetBrains Omea Reader.

**Comment by gmtju52** [comment]
Using a browser works.
The coorect link should be https://github.com/gohugoio/hugo/releases/tag/v0.30

**Comment by budparr** [comment]
Hey, @gmtju52 I thought we had published the right feed in an autodisovery tag. I'll take care of that. This is the correct public feed (for news, including releases): https://gohugo.io/news/index.xml
