### ISSUE TITLE
sitemap error: Namespace prefix xhtml on link is not defined (in multilingual site)

### ISSUE THREAD

**Issue by MunifTanjim** [gohugoio/hugo#3978]
**Hugo version**: 0.30

0859d9dfe647db3b8a192da38ad7efb5480a29a1 wraps `xmlns:xhtml="http://www.w3.org/1999/xhtml"` with `if .IsTranslated` block.

But as far as I know, `.IsTranslated` will always return `false` for the `sitemap.xml` template. So, `xmlns:xhtml="http://www.w3.org/1999/xhtml"` is never rendered. And it causes the following error:

**Namespace prefix xhtml on link is not defined**

I might be wrong, but I think #3933 should be reverted.

I've tested this on a multilingual site.

**Comment by bep** [comment]
Where do you get that validation error? Is it a "blocker"?

**Comment by MunifTanjim** [comment]
With the mentioned error present, Google Webmasters tool reports that the sitemap.xml file can't be parsed:

**Google Webmasters tool**
![google-webmaster-hugo-sitemap-error](https://user-images.githubusercontent.com/8050659/31670745-1d2f8242-b37a-11e7-9e8f-2f653eba84ed.png)

**Google Chrome browser**
![google-chrome-hugo-sitemap-error](https://user-images.githubusercontent.com/8050659/31670763-240bf370-b37a-11e7-9a04-47b3398fbbc1.png)

**Comment by bep** [comment]
OK, that's not good.

**Comment by git001** [comment]
Answer to https://github.com/gohugoio/hugo/issues/3978#issuecomment-337248361

> .. Is it a "blocker"?

Yes, this prevents me to update from 0.27.1 to 0.3x
