### ISSUE TITLE
hugo -w (aka watch without server) does not pick up changes

### ISSUE THREAD

**Issue by sklar** [gohugoio/hugo#3980]
Recreating files while watching by `hugo -w` doesn't work in `v0.30 darwin/amd64 BuildDate: 2017-10-18T16:02:31+02:00` though `Change detected, rebuilding site`.

**Comment by bep** [comment]
>Recreating files

What exactly do you mean by this?

**Comment by sklar** [comment]
It works fine in `v0.29` and all previous versions.

Steps to reproduce

1. Run `hugo -w`
1. Change content of document placed in `contentDir`
1. Check content of related `publishDir` file - **it is not updated**

**Comment by Jos512** [comment]
Someone else on the [forum](https://discourse.gohugo.io/t/hugo-0-30-released/8815/12) (in the release thread for 0.30) mentioned similar behaviour:

> `hugo -w` (without server) does not work correctly. While it shows the console message like _... 96 regular pages created ... total in 12 ms_ right after updating a source file, the corresponding output file in `public/` remains the same.

**Comment by bep** [comment]
OK, I think I know. My mistake. I will fix for 0.30.1. Thanks for reporting.

**Comment by bep** [comment]
A workaround for Hugo 0.30 is `hugo -w --disableFastRender`.
