### ISSUE TITLE
Improve Quick Install from Source instructions

### ISSUE THREAD

**Issue by galopin** [gohugoio/hugo#3984]
Quick Install instructions are not on par with each other in the:

- [ ] [`README.md`](https://github.com/gohugoio/hugo/blob/master/README.md#build-and-install-the-binaries-from-source-advanced-install) document
  § Choose How to Install > Build and Install the Binaries from Source (Advanced Install)

- [ ] [hugoDocs](https://github.com/gohugoio/hugoDocs) > Getting Started > [Install Hugo](https://github.com/gohugoio/hugo/blob/master/docs/content/getting-started/installing.md#source)
  § Quick Install > Source

I believe [Go Dep](https://github.com/golang/dep) ~~`govendor`~~ is now the way to go (no pun intended) so IMHO `README.md` should be updated accordingly.

> […] Therefore, a simple `go get` is *not* supported because the command is not vendor aware. You must use Go Dep ~~`govendor`~~ to fetch Hugo's dependencies.

BTW, how are you supposed to keep Hugo and its vendored packages up-to-date? Using ~~`govendor` directly or~~ the following `git`/`mage` CLI commands combo? 

> If you want to stay in sync with the Hugo repository, you can easily pull down
the source changes, but you'll need to keep the vendored packages up-to-date as
well.
>
>```
>$ git pull
>$ mage vendor
>$ mage install
>```

The preceding snippet is adapted from the [`CONTRIBUTING.md`](https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#updating-the-hugo-sources) document.

**Comment by galopin** [comment]
Updated the above report to reflect the switch from `govendor` to Go Dep (https://github.com/gohugoio/hugo/commit/30e471b8c66f43b2505ba4a303b5cacb4a5f3af3). [Install Hugo](https://github.com/gohugoio/hugo/blob/master/docs/content/getting-started/installing.md#source) still mentions `govendor` 😕

**Comment by vassudanagunta** [comment]
Wrong repo to report this. Instead: https://github.com/gohugoio/hugoDocs. 

Better yet, fix the docs yourself and do a pull request!

**Comment by galopin** [comment]
@vassudanagunta  You are partially right. When I opened this ticket, there were no such discrepancies between [`CONTRIBUTING.md`](https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#updating-the-hugo-sources) document and [hugoDocs](https://github.com/gohugoio/hugoDocs) > Getting Started > [Install Hugo](https://github.com/gohugoio/hugo/blob/master/docs/content/getting-started/installing.md#source). AFAIK, [`README.md`](https://github.com/gohugoio/hugo/blob/master/README.md#build-and-install-the-binaries-from-source-advanced-install) document belongs to this repository — and not [hugoDocs](https://github.com/gohugoio/hugoDocs) — and it can be misleading. I will follow your suggestion anyway.
