### ISSUE TITLE
URL Management / time zones / Documentation wrong

### ISSUE THREAD

**Issue by erichiller** [gohugoio/hugo#3986]
2 part-er for docs at <https://gohugo.io/content-management/urls/#permalinks>

Using the example from the documentation:
```
[permalinks]
  post = "/:year/:month/:title/"
```
> Only the content under post/ will have the new URL structure. For example, the file content/post/sample-entry.md with date: 2017-02-27T19:20:00-05:00 in its front matter will render to public/2017/02/sample-entry/index.html at build time and therefore be reachable at https://example.com/2013/11/sample-entry/.

1. The documentation is unclear as to whether `/:year/:month/` and in my case `/:year/:month/:day` are using UTC or local time. Thus, to use the example date of `2017-02-27T19:20:00-05:00` would that be rendered as `/2017/02/28/` (UTC) or as `/2017/02/27/` (local).
2. The part of _...and therefore be reachable at `https://example.com/2013/11/sample-entry/.`_ is just wrong and doesn't fit with the rest of the paragraph, I'm guess it is just a mistake.

**Comment by bep** [comment]
Could you move this issue to https://github.com/gohugoio/hugoDocs/issues where it belongs?

**Comment by bep** [comment]
But have a look at this: 

https://play.golang.org/p/4LWEOzMW6Q

There is nothing UTC about your example (-5 hours), and Hugo will use that timezone info.

We will also accept dates without time or timezone info, which will fall back to UTC, but the above example would still be 27th of February.

**Comment by erichiller** [comment]
@bep Correct, after I tested a little I see that Hugo uses the timezone information properly if tested. But the question I had without explicitly seeing it in the documentation was whether Hugo would render URLs in UTC irregardless of local time. and (2) needed fixing no matter.
I will open a ticket with docs.

**Comment by vassudanagunta** [comment]
(I'd test this on my own, but I don't use hugo for blogs/dated posts, and my quick attempt to recreate didn't work.)

@bep Am I understanding this correctly, that the dates associated with content have a time-zone dependency? If they did, that would be wrong. A post dated "2012-10-21" should publish with that literal date regardless of what time zone I happened to be in when I generate the site. It certainly should not result in my site changing if I regenerate it while traveling. An article date is just like a birthday, it's stated as the same day everywhere in the world. 

Posts with full date-times are another matter and I'm not sure what the behavior should be with those.
