### ISSUE TITLE
Hugo 0.30.2 doesn't see subsections with _index.md only in them

### ISSUE THREAD

**Issue by mpaluchowski** [gohugoio/hugo#3989]
Hugo 0.30.2 (haven't tested .0 nor .1 but it _did_ work correctly up to 0.29) seems to be ignoring non-first-level sections which only have `_index.md` in them, both in `.Sections` and `where .Site.Pages "Kind" "section"` queries. 

Ie. for the following structure:

```
/content/a/_index.md
        /b/c/_index.md
          /d/_index.md
            /some-content.md
```

the query `where .Site.Pages "Kind" "section"` will only return:

* `a` and `b` -- because they're first-level
* `d` -- because it contains `some-content.md`

while `c` will be missing.

**Comment by bep** [comment]
Thanks for the report; with the change log from 0.29 I find this strange, but your issue report is good, so I will look at this shortly.

**Comment by bep** [comment]
Do you have a public site source showing this issue?

**Comment by mpaluchowski** [comment]
Yes. Here's my [site](https://github.com/mpaluchowski/triathlon.paluchowski.com) and the corresponding [theme](https://github.com/mpaluchowski/hugo-triathlete).

You can see the issue when you go to [triathlon.paluchowski.com/races](https://triathlon.paluchowski.com/races/) -- there are 4 items on the list, this one built with 0.29 -- but when you build it with 0.30.2 the top 2 items (with the gray headers) will be missing. These are the sections with `_index.md` only.

**Comment by mpaluchowski** [comment]
Oh, wait, _now_ I found the issue. The commit 6a30874f1:

```go
if p.PublishDate.IsZero() {
  p.PublishDate = p.Date
}
```

The two items I have on the `/races` page have both **future dates** (because they're upcoming races I'll be participating in). The above change though interprets these `date` values as future publishing dates and hence the items won't render, unless I pass `--buildFuture` to the build command.

This is obviously _not_ what I want nor expected to happen :) If I wanted a piece of content to be published in the future, I would've used the `publishDate` field explicitly.

Can we get the old behavior back?

**Comment by bep** [comment]
See #3977
