### ISSUE TITLE
The mage gofmt target does not report any errors

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3990]
Also check the vet + lint target. The lint target should not fail, but we should get some sane output of any errors.

/cc @natefinch what was the thought behind your logic here?

Note that I'm about to replace govendor with dep so might wait with the fixes.

**Comment by natefinch** [comment]
Sorry, I forgot that gofmt doesn't exit with a non-zero exit code when it finds unformatted stuff.  I can submit a PR so that we check to see if it outputs any text and fail if it does (and output that text).

**Comment by natefinch** [comment]
lint and vet appear to do the right thing btw

**Comment by natefinch** [comment]
oh sorry, missed the part about lint not failing... it does fail
