### ISSUE TITLE
Can no longer keep Hugo up-to-date from source!?

### ISSUE THREAD

**Issue by galopin** [gohugoio/hugo#3997]
Mage now fails to update vendored packages ⁉️ 

```
$ go get -u github.com/magefile/mage
$ cd ~/Go/src/github.com/gohugoio/hugo
$ git pull
$ mage install
# command-line-arguments
.\mage_output_file.go:330:17: undefined: mg.Context
Error: error compiling magefiles
```

What's going on?

It seems you have made the [move](https://github.com/gohugoio/hugo/commit/f711b170e4bb286ffa544dfdb48cff4e8f74497f) from `govendor` to the standard Go dependency management tool. But I cannot infer this change is the cause of the problem. Looks like it is a [Mage](/magefile/mage)-only problem…

**Comment by galopin** [comment]
@bep I'm afraid that https://github.com/gohugoio/hugo/commit/45ad8ac381ab71aec6f62bc0842934b8bdecd9d7 does not appear to solve the above issue 🐛  

```
$ cd ~/Go/src/github.com/gohugoio/hugo
$ git pull
$ git log --oneline
45ad8ac vendor: Lock mage to v1
133cfd1 mage: Skip Check on Go 1.8
[…]
```

`mage install` yields the exact same cryptic error message.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by galopin** [comment]
Understood but this used to work as described above no later than Friday, i.e. before the https://github.com/gohugoio/hugo/commit/ba0b22ef4491fa70b9f4fc9b091a5192a7eed59f commit… and I also read the friendly manual (#3984). Thank you.

Eventually I was able to rebuild and install Hugo from source by cleaning the whole slate using `go clean -i …` command for both `github.com/kardianos/govendor` and `github.com/gohugoio/hugo` packages — and this time, from the Windows command prompt instead of the Portable Git prompt! 😄 

`Hugo Static Site Generator v0.31-DEV-45AD8AC windows/386 BuildDate: 2017-10-23T16:44:26+02:00`

Kudos for switching to `dep` 🚀

**Comment by bep** [comment]
@galopin the only way this issue tracker is manageable is for us to route everything that resembles a question to the discussion forum.

**Comment by vassudanagunta** [comment]
I'm getting the exact same error: #4003.
