### ISSUE TITLE
Regression in date front-matter parsing

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#3998]
Hello,

Below used to work in v0.30.2:

```md
+++
title = "Date + Time (after UTC)"
date = 2017-09-12T16:10:00+05:30
+++
```

But now (built with `hugo` version *Hugo Static Site Generator v0.31-DEV-45AD8AC3*), I get the below error when I try to run `hugo server`:

```
Started building sites ...
ERROR 2017/10/23 12:05:14 failed to parse page metadata for "posts/date-plus-time-plus-utc.md": Near line 2 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got '+' instead
Error: Error building site: Errors reading pages: Error: failed to parse page metadata for "posts/date-plus-time-plus-utc.md": Near line 2 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got '+' instead for date-plus-time-plus-utc.md
```

I don't get that error if the time-zone is minus-UTC.. example:

```md
+++
title = "Date + Time (after UTC)"
date = 2017-09-12T16:10:00-05:30
+++
```

or if the date is wrapped in double-quotes:

```md
+++
title = "Date + Time (after UTC)"
date = "2017-09-12T16:10:00+05:30"
+++
```

But regardless, this is a regression in date parsing behavior.. earlier dates with positive UTC did not need to be wrapped in quotes.

**Comment by bep** [comment]
>Below used to work in v0.30.2:

But fail in the current source? I have refreshed dependencies, so there may be worth looking into any suspicious changes in `cast`.

/cc @moorereason

**Comment by kaushalmodi** [comment]
> But fail in the current source?

Yes. I don't use `mage` though.. hope that's not the problem. I don't use `mage` as I don't know if it can override `-ldflags` as below:

```bash
dep ensure

hugo_commithash=$(git rev-parse --short HEAD 2>/dev/null)
builddate=$(date +%FT%T%z)

# Update dependent packages from their master branches if building hugo from its
# master branch.
if [[ "${hugo_rev_basename}" == "master" ]]
then
    # https://discourse.gohugo.io/t/building-hugo-with-the-latest-version-of-chroma/8543/2?u=kaushalmodi
    go get -u -v ${chroma_src}/...
    rm -rf "${GOPATH}/src/${hugo_src}/vendor/${chroma_src}"
    chroma_commithash=$(cd "${GOPATH}/src/${chroma_src}" && git rev-parse --short HEAD 2>/dev/null)
    hugo_commithash="${hugo_commithash}:chroma-${chroma_commithash}"
fi

cmd="go build -v \
     -ldflags \"-X ${hugo_src}/hugolib.CommitHash=${hugo_commithash} \
               -X ${hugo_src}/hugolib.BuildDate=${builddate}\" \
     ${hugo_src}"
echo "${cmd}"
eval "${cmd}"
```

[Full `hugo` build script][1]

[1]: https://gist.github.com/9fd32d25b64511b1242a3b1b47a4fa84

**Comment by kaushalmodi** [comment]
I think I found the problem.. After switching to `dep`, looks like `hugo` is forcefully using v0.3.0 of the `toml` dependency, which rolls back that dep to https://github.com/BurntSushi/toml/commit/b26d9c308763d68093482582cea63d69be07a0f0

Whereas, earlier, I see https://github.com/gohugoio/hugo/commit/ba0b22ef4491fa70b9f4fc9b091a5192a7eed59f#diff-bd290170e2912d3e8694db1a151066e5L8 that `hugo` used the latest version of `toml` then, which had this issue fixed in https://github.com/BurntSushi/toml/commit/8482be601623debfad693ca81106d44d3457c1b3.

**Comment by kaushalmodi** [comment]
I confirm this to fix this issue:

```diff
diff --git a/Gopkg.toml b/Gopkg.toml
index 76c1bc81..16e3b800 100644
--- a/Gopkg.toml
+++ b/Gopkg.toml
@@ -2,7 +2,7 @@
 
 [[constraint]]
   name = "github.com/BurntSushi/toml"
-  version = "0.3.0"
+  branch = "master"
 
 [[constraint]]
   name = "github.com/PuerkitoBio/purell"
```

**Comment by bep** [comment]
Can you create a PR?

**Comment by kaushalmodi** [comment]
sure

**Comment by kaushalmodi** [comment]
Related question.. I forgot to commit `Gopkg.lock` (and it did not matter).

So why is `Gopkg.lock` managed by git, if it's anyways autogenerated?

Rebuilding `hugo` after this PR merge shows this change in `Gopkg.lock`:

```diff
diff --git a/Gopkg.lock b/Gopkg.lock
index 2808d92a..12cb6ea0 100644
--- a/Gopkg.lock
+++ b/Gopkg.lock
@@ -2,10 +2,10 @@
 
 
 [[projects]]
+  branch = "master"
   name = "github.com/BurntSushi/toml"
   packages = ["."]
-  revision = "b26d9c308763d68093482582cea63d69be07a0f0"
-  version = "v0.3.0"
+  revision = "a368813c5e648fee92e5f6c30e3944ff9d5e8895"
 
 [[projects]]
   name = "github.com/PuerkitoBio/purell"
@@ -285,6 +285,6 @@
 [solve-meta]
   analyzer-name = "dep"
   analyzer-version = 1
-  inputs-digest = "71384ebc70488fec5f4b1f1d8c89659654dca57f40fd9d6d89b0891203b18ed9"
+  inputs-digest = "9046d783e19de319d8829a48dd75d8eee659c79b4b71215d34ab1a62c8210d79"
   solver-name = "gps-cdcl"
   solver-version = 1
```

**Comment by kaushalmodi** [comment]
> So why is Gopkg.lock managed by git, if it's anyways autogenerated?

Actually, I believe I now understand why committing that is important... For debug purposes.. to keep tracks of what packages update on `dep ensure`. 

Apologies for missing this file in the PR.

**Comment by bep** [comment]
>For debug purposes

No, it has nothing to do with debug purposes. That is the file that is used when you do "dep ensure". Could you create another PR?

**Comment by kaushalmodi** [comment]
> That is the file that is used when you do "dep ensure". 

I didn't understand., `hugo` builds fine even if I delete that file. `Gopkg.lock` gets regenerated.

> Could you create another PR?

In any case, will do that. But just stating my observation that even deleting that file didn't matter.

**Comment by bep** [comment]
Your observations aren't complete.
