### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by davidpelayo** [gohugoio/hugo#4000]
If you access [this document](https://github.com/gohugoio/hugo/blob/master/docs/content/content-management/multilingual.md#menus) and you try to navigate to the [creation of a menu](https://github.com/gohugoio/hugo/blob/master/content-management/menus), the link is broken.

![issue](https://user-images.githubusercontent.com/84540/31903929-0826f7ea-b82a-11e7-9203-a92a72dec872.png)

**Comment by bep** [comment]
This needs to be fixed in another repository, so it would be good to have the issue in that repo. Ref. the other issue.

**Comment by davidpelayo** [comment]
What repo is it @bep?

**Comment by BhaveshSGupta** [comment]
@davidpelayo here: https://github.com/gohugoio/hugoDocs
