### ISSUE TITLE
Documentation on how to write i18n menus needs to be improved

### ISSUE THREAD

**Issue by davidpelayo** [gohugoio/hugo#4001]
I'm newbie in Hugo, but I've spent a few minutes already trying to figure out how to setup a i18n menu, considering that my main menu is defined through content itself, using frontend-matter, and I still don't find any example of this.

So I have my `content/_index.md` with the frontend-matter like follows:

```
---
title: "a single title"
date: 2017-10-23
weight: 99
menu: "main"
---
Content goes here...
```

I've been trying to extend this menu through the configuration fail `config.toml`, but changes don't take effect. 

```
[Languages]
  [Languages.en]
    ...
  [Languages.en.params]
    sitename = "issue example"
  [Languages.en.menu.main]
    url    = "/url/"
    name   = "url"
    weight = 0
```

I deduce the only menu that's getting rendered is the one of the content itself through the frontend-matter, and that's why I'm trying to do it that way.

Any hint?

References checked:
- [Multilingual menus](https://github.com/gohugoio/hugo/blob/master/docs/content/content-management/multilingual.md#menus).
- [Menus](https://gohugo.io/content-management/menus/).

PS: I guess it somehow relates to #3976

**Comment by bep** [comment]
It would be great if you could create these documentation issues in the documentation repository:

https://github.com/gohugoio/hugoDocs/issues
