### ISSUE TITLE
Deploying to Heroku?

### ISSUE THREAD

**Issue by ItsPugle** [gohugoio/hugo#4004]
It'd be really good if their was a guide to deploying to [Heroku](https://heroku.com/) in the Hosting & Deployment docs.

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues

**Comment by ItsPugle** [comment]
Sorry - I didn't see that repository! I've gone and posted this over at [#246](https://github.com/gohugoio/hugoDocs/issues/246).
