### ISSUE TITLE
Add "param" shortcode

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4010]
Looking something like this:

```html
{{- $name := .Get 0 -}}
{{- with (.Page.Param $name }}{{ . }}{{ else }}{{ errorf "param %q not found in %q" $name .Page.Path }}{{ end -}} 
```

**Comment by kaushalmodi** [comment]
Should there be a site params alternative too? Maybe `pparam` and `sparam`?

**Comment by bep** [comment]
>Should there be a site params alternative too? Maybe pparam and sparam?

I assume you know that the above snippet will fall back to Site param if not found in Page. This is the  common requirement. I don't want to add more until I see some neon ads on Time Square in New York saying "we want pparam in Hugo now!" It adds documentation work and those people who really need it can easily add it themselves.

**Comment by bep** [comment]
That said, this shortcode should probably have an optional second argument with a default value if not found.

**Comment by kaushalmodi** [comment]
> I assume you know that the above snippet will fall back to Site param if not found in Page. 

Yes, I read about there somewhere in the docs. But I got misled by the error message `{{ errorf "param %q not found in %q" $name .Page.Path }}`. Should the error then say that that `$name` param was not found in both `.Site` and `.Page` params?

> this shortcode should probably have an optional second argument with a default value if not found.

That will be cool!

**Comment by bep** [comment]
> Should the error then say that that $name param was not found in both .Site and .Page params?

This is an issue asking for a shortcode. This is not the implementation. Your "error text" was better than what I quickly wrote ...
