### ISSUE TITLE
Hugo do not generate  RSS feeds for section, tags...

### ISSUE THREAD

**Issue by anayrat** [gohugoio/hugo#4012]
Hello,

It seems hugo not longer generate RSS feeds for section, tags...

I opened an issue for Academic theme : https://github.com/gcushen/hugo-academic/issues/346

Step to reproduce : 

  * Create a new hugo site
  * Clone academic themes
  * Copy exampleSite
  * Change config.toml : 
```
[outputs]
  home = [ "HTML", "CSS", "RSS" ]
```

  * Look at `http://localhost:1313/tags/academic/` header:

```html
  <link rel="alternate" href="//localhost:1313/index.xml" type="application/rss+xml" title="Academic">
  <link rel="feed" href="//localhost:1313/index.xml" type="application/rss+xml" title="Academic">
```

I don't understand why I don't have `//localhost:1313/tags/academic/index.xml` ?

If I try to look at `//localhost:1313/tags/academic/index.xml` I have "404 page not found"

Hugo version : v0.30.2

Any idea?

Thanks!

**Comment by Shadow53** [comment]
Take another look at the [Output Formats page](https://gohugo.io/templates/output-formats/#output-formats-for-pages):

> The output definition is per Page Kind (i.e, `page`, `home`, `section`, `taxonomy`, or `taxonomyTerm`).

I forget the difference, but you want to enable `"RSS"` for either `taxonomy` or `taxonomyTerm`.

**Comment by anayrat** [comment]
Oh right! Thanks!
