### ISSUE TITLE
googleAnalytics case issue

### ISSUE THREAD

**Issue by robsonsobral** [gohugoio/hugo#4016]
Hi!

A call for `{{ with $.Site.GoogleAnalytics }}` on a template works, but not for `{{ with $.Site.googleAnalytics }}`.

Shouldn't it be just like in the `config.yaml`? `googleAnalytics`?

Thank you.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
