### ISSUE TITLE
Typo in documentation (BlackFriday option "extensionsmask")

### ISSUE THREAD

**Issue by itc-ger** [gohugoio/hugo#4043]
On the following page I spotted a typo:
[Documentation -> Getting Started -> Configuration -> Blackfriday Options](https://gohugo.io/getting-started/configuration/#configure-blackfriday)

I guess the (purpose) description of **extensionsmask** should be:
> Purpose: **Dis**able one or more of Blackfriday’s Markdown extensions (if they aren’t Hugo defaults). 

**En**able -> **Dis**able

See also: purpose of option **extensions**:
> Purpose: Enable one or more Blackfriday’s Markdown extensions (if they aren’t Hugo defaults). 

Plus, maybe the **Blackfriday flag** has also to be altered to
> Blackfriday flag: EXTENSIONMASK_*

`EXTENSION_*` to  `EXTENSIONMASK_*` I guess
I'm not sure about the plural 's' - so please double check my suggestion ;-)

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues
