### ISSUE TITLE
Category listing page URLizes page title

### ISSUE THREAD

**Issue by ghost** [gohugoio/hugo#405]
I have category pages, such as http://leonpaternoster.com/categories/basic-citizen-income/

It looks like it's taking the urlize'd category name (which is 'Basic citizen income') rather than simply outputting the category title. So the page title is Basic-citizen-income rather than Basic citizen income.

The template simply uses

`<h1 class="entry-header-title">{{ .Title }}</h1>`

In an example content file I have:

---

title: Basic citizen income—genius idea the UK will never adopt
author: Leon
excerpt: Free money for everyone makes sense.
layout: post
url: /2013/09/basic-income/
categories:
- Basic citizen income
- Politics
  date: 23 Sep 2013
  ---

**Comment by nd2s** [comment]
Could this be broken again? Getting URL form with:
```
{{ range $name, $taxonomy := .Site.Taxonomies.categories }}
	<li><a href="/categories/{{ $name | urlize }}">{{ $name }}</a></li>
{{ end }}
```

Using latest dev version from master branch.
