### ISSUE TITLE
Youtube video start time

### ISSUE THREAD

**Issue by bluprince13** [gohugoio/hugo#4050]
It's possible to embed a youtube video that starts at a set time like this:

`{{< youtube id="LlqxmQxoAhQ?t=39m21s">}}`

However, the video starts at whatever time you stopped watching it previously.

**Comment by gideondsouza** [comment]
> However, the video seems to start a half minute earlier than it should.

`t=39m21s`
possibly because of the above in your ur!

**Comment by moorereason** [comment]
So, the answer appear to be "no, you can't do that."  See the [embedded Youtube shortcode](https://github.com/gohugoio/hugo/blob/488631fe0abc3667355345c7eb98ba7a2204deb5/tpl/tplimpl/template_embedded.go#L40-L48).  You can't put extra parameters into the `id` field.

But you can make your own youtube shortcode based upon the embedded one, and you're version will override the embedded one.  Additionally, we could consider adding more options to the embedded shortcode to allow more options to be passed.

**Comment by bluprince13** [comment]
Ah okay, I think it'd be useful to include the starttime as an option.

**Comment by solarkennedy** [comment]
With embedded youtube the arg is `start` in seconds, not `t` like a normal url.
You can see this when you click share on youtube and click embedded and then click the "start at" checkbox.

Example:

```
{{< youtube id="abc?start=386" autoplay="false"
```
