### ISSUE TITLE
shortcodes with .ace extensions fail

### ISSUE THREAD

**Issue by igregson** [gohugoio/hugo#4051]
Greetings.

In older versions of Hugo (0.18 I believe, though I'm not certain) it was possible to write shortcodes in ace (e.g. `video.ace`). When trying this with the latest `0.30.2` this no longer seems to work (and I tried adding html before and after ace, e.g. `video.html.ace` and `video.ace.html`, but neither of these worked either). 

Not sure if this is a bug or changed behavior (if it's changed behavior it would be good to update the shortcode and ace docs accordingly).

**Comment by xap5xap** [comment]
Same thing happened to me too
