### ISSUE TITLE
Lookup order of archetype is not honored when theme is specified

### ISSUE THREAD

**Issue by ashishthedev** [gohugoio/hugo#4052]
Even though I've specified a theme and there is an archetype present for a content-section(posts), but the front matter is not being copied from the theme.

Referring section from docs:

https://gohugo.io/content-management/archetypes/
> Lookup Order for Archetypes 
> Similar to the lookup order for templates in your layouts directory, Hugo looks for a section- or type-specific archetype, then a default archetype, and finally an internal archetype that ships with Hugo. For example, Hugo will look for an archetype for content/posts/my-first-post.md in the following order:
> 
> archetypes/posts.md
> archetypes/default.md
> themes/<THEME>/archetypes/posts.md
> themes/<THEME>/archetypes/default.md (Auto-generated with hugo new site)
> If you wish to use archetypes that ship with a theme, the theme field must be specified in your configuration file.

Step1:
Create a new theme:
```$ hugo new theme bingo```

Step2:
Use the theme in config.toml
```$ vi config.toml```
+++
...
theme = "bingo"
+++

Step3:
create a new archetype posts
```$ vi themes/bingo/archetypes/posts.md```
+++
fancyOption = "yay"
+++

Step4: 
Create a new post
```$ hugo new posts/first.md```

Step5:
Inspect the new file
```$ cat content/posts/first.md```
```
---
title: "One"
date: 2017-11-04T18:56:43+05:30
draft: true
---
```

```$ hugo version```
Hugo Static Site Generator v0.30.2 linux/386 BuildDate: 2017-10-27T14:26:46+05:30

**Comment by bep** [comment]
Do you have a default archetype in your project?

**Comment by ashishthedev** [comment]
Yes.
```
.
├── archetypes
│   └── default.md
├── config.toml
├── content
│   └── posts
│       ├── one.md
│       └── two.md
├── data
├── layouts
├── static
└── themes
    └── bingo
        ├── archetypes
        │   ├── default.md
        │   └── posts.md
        ├── layouts
        │   ├── 404.html
        │   ├── _default
        │   │   ├── list.html
        │   │   └── single.html
        │   ├── index.html
        │   └── partials
        │       ├── footer.html
        │       └── header.html
        ├── LICENSE.md
        ├── static
        │   ├── css
        │   └── js
        └── theme.toml
```

**Comment by ashishthedev** [comment]
Also observed that the front matter is in yaml instead of toml.

**Comment by bep** [comment]
>Yes.

Then he behaviour is in line with the documentation. Note that this has been discussed before.
