### ISSUE TITLE
date format in archetypes not possible

### ISSUE THREAD

**Issue by Jos512** [gohugoio/hugo#4053]
Since [Hugo 0.24](https://github.com/gohugoio/hugo/releases/tag/v0.24), archetype files are processed as templates. Thanks to that we can use functions like `replace` and `title` in our archetypes template files.

But `dateFormat` does not work in archetype files, as [reported and confirmed here](https://discourse.gohugo.io/t/specify-date-format-in-archetype/9015).

---

This GitHub issue can be..

- a bug report: if we assume that, when other Hugo functions work in an archetype, `dateFormat` should also.
- or a feature request: if `dateFormat` is deliberately left out, then archetypes become easier to work with when that template function is also available.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
