### ISSUE TITLE
chroma: fenced codeblocks with no language are rendered as <pre></pre> instead of <pre><code></code></pre>

### ISSUE THREAD

**Issue by aktau** [gohugoio/hugo#4056]
See title. I'm wondering if this is intentional. If it is, I'll have to revise my CSS to mostly style the `<pre>` blocks instead of `<code>`.

```
hugo version
Hugo Static Site Generator v0.31-DEV linux/amd64 BuildDate: 2017-11-05T15:14:35+01:00
```

**EDIT**: By "no syntax" I mean code blocks like so:

```
  |```
  |no language, rendered as <pre>content</pre>
  |```
```

versus

```
  |```bash
  |with language, rendered as <pre><code>content</code></pre>
  |```
```

**Comment by bep** [comment]
Yes, it is intentional.

**Comment by aktau** [comment]
Good to know. Thanks!

**Comment by kaushalmodi** [comment]
@aktau 

> I'll have to revise my CSS to mostly style the `<pre>` blocks instead of `<code>`

Or you can just specify "some language".. doesn't have to be a real language. Try:

````
```text
something
```
````

or

````
```foo
something
```
````

or

````
```nolanguage
something
```
````

**Comment by aktau** [comment]
> Or you can just specify "some language".. doesn't have to be a real language. Try:

Great :).

However, my main use case for these types of blocks is when I feel it's nicer to indent code blocks instead of fencing them (I forgot to mention that, but I assume it's the same as fencing without a language).

I find it easier to read my markdown that way.
