### ISSUE TITLE
/layouts/_default/baseof.html seem not to be look for

### ISSUE THREAD

**Issue by kerol2r20** [gohugoio/hugo#4062]
/layouts/_default/baseof.html template file seem not to be seek for render homepage.
I put my own baseof.html but not replace the /theme/<theme_name>/layouts/_default/baseof.html one.

**Comment by dum3ng** [comment]
I have met the same problem.
Hugo seems does not render the site at all when I make  a `/layouts/_default/baseof.html` and delete the `/_default/baseof.html` in the theme folder.

**Comment by bep** [comment]
What Hugo versions?

**Comment by dum3ng** [comment]
hugo: stable 0.30.2 (bottled), HEAD
Installed from homebrew.

**Comment by meAmidos** [comment]
I've just encountered the same problem.

The trick with adding a `list.html` file to the `_default` folder temporary solved the issue.

**Comment by bep** [comment]
>Is this a design purpose( not allow only have baseof.html in _default) or a bug?

Yes, that is by design.
