### ISSUE TITLE
How to make URL end with .html instead of / ? 

### ISSUE THREAD

**Issue by Remonli** [gohugoio/hugo#4065]
Hello, 

How can I keep old URL http://xxx.com/2017/11/10.html when migrate from hexo to hugo ? 
I tried  /:year/:month/:slug/ , but it will be http://xxx.com/2017/11/10/ and /:year/:month/:slug.html
still failed. 

Thanks in advance.
Li

**Comment by vassudanagunta** [comment]
From the README of this repo:

> ### Asking Support Questions
>
> We have an active discussion forum where users and developers can ask questions. Please don't use 

[From the docs](https://gohugo.io/content-management/urls/#ugly-urls). It doesn't look like you looked at either.
