### ISSUE TITLE
Hugo not generating some pages

### ISSUE THREAD

**Issue by LeoTindall** [gohugoio/hugo#4067]
For some reason, some of my pages are not being generated. For instance, I have a file `content/post/thoughts-on-virtual-reality.markdown`. A lot of other files in my `content` directory cause paths like `public/post/title-of-article/index.html` to be generated, as expected, but some, including that one, do not. I cannot figure out why.

This only happens in my `post` subdirectory, not (for instance) my `tutorial` directory.

Repo: https://github.com/leotindall/leotindall.com
Site: https://leotindall.com

**Comment by pamubay** [comment]
remove `layout: post` in `content/post/thoughts-on-virtual-reality.markdown` front matter

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
