### ISSUE TITLE
String Comparison issue in template partial

### ISSUE THREAD

**Issue by RealOrangeOne** [gohugoio/hugo#4072]
Looks like there's a very strange issue with string comparison, primarily when reading directly from frontmatter.

```
{{ .Params.force_summary }}  # true
{{ base64Encode .Params.force_summary }}  # dHJ1ZQ==
{{ base64Encode "true" }}  # dHJ1ZQ==
{{ eq .Params.force_summary "true" }}  # false
{{ eq (base64Encode "true") (base64Encode .Params.force_summary) }}  # true
```

```
---
title: Doesn't matter
force_summary: true
---
```

This code is run inside a partial. It's possible this is because `true` is some kind of reserve word in the comparison, i'm not familiar with the templating engine.

> Hugo Static Site Generator v0.30.2 linux/amd64 BuildDate: 2017-10-21T12:44:04+02:00

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by RealOrangeOne** [comment]
Discussion moved to https://discourse.gohugo.io/t/string-comparison-issue-in-template-partial/9180
