### ISSUE TITLE
v0.30.2 Snap unable to create theme

### ISSUE THREAD

**Issue by OmegaDiamondIT** [gohugoio/hugo#4080]
```
$ hugo new theme 2018
Error: Unable to find theme Directory: /home/ricky/Development/website2018/web2018_frontend/themes/2018

$ mkdir themes/2018
$ hugo new theme 2018
Error: /home/ricky/Development/website2018/web2018_frontend/themes/2018 already exists

Usage:
  hugo new theme [name] [flags]

Flags:
  -h, --help   help for theme

Global Flags:
      --config string    config file (default is path/config.yaml|json|toml)
      --debug            debug output
      --log              enable Logging
      --logFile string   log File path (if set, logging enabled automatically)
      --quiet            build in quiet mode
  -s, --source string    filesystem path to read files relative from
  -v, --verbose          verbose output
      --verboseLog       verbose logging

```

## Context
```
$ hugo version
Hugo Static Site Generator v0.30.2 linux/amd64 BuildDate: 2017-10-19T06:22:46-07:00

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

$ ll
total 48
drwxrwx--- 10 ricky ricky 4096 Nov 13 15:51 ./
drwxrwx---  5 ricky ricky 4096 Nov 13 10:08 ../
drwxrwx---  2 ricky ricky 4096 Nov 13 15:49 archetypes/
-rw-rw----  1 ricky ricky  137 Nov 13 15:54 config.yaml
drwxrwx---  8 ricky ricky 4096 Nov 13 15:49 content/
drwxrwx---  2 ricky ricky 4096 Nov 13 15:33 data/
drwxrwx---  8 ricky ricky 4096 Nov 13 16:53 .git/
-rw-rw----  1 ricky ricky  128 Nov 13 13:05 .gitignore
drwxrwx---  2 ricky ricky 4096 Nov 13 12:58 layouts/
drwxrwx---  2 ricky ricky 4096 Nov 13 12:58 static/
drwxrwx---  3 ricky ricky 4096 Nov 13 17:09 themes/
drwxrwx---  2 ricky ricky 4096 Nov 13 13:03 .vscode/
```

After learning about the containment model problems some have with snap packages I made sure that I was working in a plain subdir of my home folder.

Typically I just make everything manually, but I decided to do it "normally" for once. :P

**Comment by swhalley** [comment]
I ran into this problem (v0.31 on MacOS Sierra). To find the root cause I used the `--debug` and `--log` flags.
```
$hugo new theme my-theme --debug --log
INFO 2017/11/26 14:35:16 Using config file: /Users/me/Documents/workspace/my-blog/config.toml
Error: Unable to find theme Directory: /Users/me/Documents/workspace/my-blog/themes/my-theme
```
After some digging through source of Hugo, turns out my error was because I updated my config.toml (or yaml) file with the new theme name before I tried to generate it. 

The error 
> Error: Unable to find theme Directory: ...

is indicating that it is reading the config file and trying to locate the theme directory.
Try removing the theme line from your config.yaml file and try again.

**Comment by OmegaDiamondIT** [comment]
Good to know there's a workaround. Yes that's exactly what I was doing.

Sounds like the fix would be for Hugo to not attempt to read the current
theme when asked to create a theme.

**Comment by swhalley** [comment]
Not sure the right fix, but here are some of the technical details.
The new theme command is calling here
https://github.com/gohugoio/hugo/blob/6d79beb5f67dbb54d7714c3195addf9d8e3924e8/commands/new.go#L242-L243

which in turn calls into (Where we saw our error)
https://github.com/gohugoio/hugo/blob/6d79beb5f67dbb54d7714c3195addf9d8e3924e8/commands/hugo.go#L397-L402

Looks like this has been the case for 2+ years so it doesn't appear to be something with a recent release that broke this.

Not sure why initializeConfig is called in this case, as the function is already checking if the theme name already exists. If a developer looks into this maybe they will know more as to why this is required.

**Comment by OmegaDiamondIT** [comment]
Looks like it needs the config file in case themesDir is specified.
