### ISSUE TITLE
'source' config variable ignored in NewContent

### ISSUE THREAD

**Issue by jmbcpi** [gohugoio/hugo#4084]
A "source" variable set in config.toml seems to be ignored when running `hugo new`, and new files are always created relative to the current working directory instead.

Script to reproduce:

```
# Make the new site:
cd Desktop
mkdir hugotest
cd hugotest
hugo new site issue-demo

# Move the config.toml file into the current working directory
mv issue-demo/config.toml ./

# Change the source in the config
echo 'source = "issue-demo"' >> config.toml 

# Try to create a new article:
hugo new section/article.html
```

Expected result: 

/Users/john/Desktop/hugotest/issue-demo/content/section/article.html created

Actual result: 

/Users/john/Desktop/hugotest/content/section/article.html created

Workaround:

Use `hugo --source <path> new <section/file>` — this seems to be respected correctly.

Version:

Hugo Static Site Generator v0.30.2 darwin/amd64 BuildDate: 2017-11-08T11:28:06-06:100:

**Comment by bep** [comment]
>A "source" variable set in config.toml seems to be ignored when running hugo new, 

Where did you read about the "source" config variable?

**Comment by jmbcpi** [comment]
https://gohugo.io/getting-started/configuration/#all-variables-toml

Relevant:

```
# filesystem path to read files relative from
source =                      ""
```
