### ISSUE TITLE
Make sure partialCached is "one per partial"

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4086]
https://discourse.gohugo.io/t/is-there-a-way-to-get-really-deterministic-randomness/9235/7

**Comment by bep** [comment]
f5ed04bd4a2ba1a62482b381470f04aad98375f5

**Comment by bep** [comment]
I will have to reopen and revisit this later.

**Comment by swamidass** [comment]
This is great to see finally coming to hugo. Thanks.
