### ISSUE TITLE
Home page showing full path

### ISSUE THREAD

**Issue by matthewgourd** [gohugoio/hugo#4089]
Hi there, apologies if this has been answered elsewhere, but I did look first and found nothing similar.

I have built the beginnings of a developer portal for my company and the first page has an absolute URL of developer.mycompany.com/overview. At the moment, when I open developer.mycompany.com in a browser it resolves to the full URL. How do I get rid of the 'overview' bit of the URL in the browser? I have already set baseURL in config.toml in project directory/themes to be without the overview bit.

Thanks,

Matt

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
