### ISSUE TITLE
Slashes in a taxonomy term break path resolution

### ISSUE THREAD

**Issue by tsuereth** [gohugoio/hugo#4090]
My blog is about video games. So for the taxonomy "games" I have terms such as:

* Kingdom Hearts 358/2 Days
* Retro/Grade
* SHENZHEN I/O

When these taxonomy terms are translated into url-safe slugs, the slashes are left untouched. As a result, the website path to the page for SHENZHEN I/O would be something like `/games/shenzhen-i/o/`

This subsequently breaks the mapping of path "sections" to meaningful information.  When hugo renders content for `games/shenzhen-i/o` it breaks the path into the sections "games" (the parent taxonomy), then "shenzhen-i" (the taxonomy term), then "o" (which is discarded?).

So when a content template looks for pages tagged with the matching taxonomy term, it ends up looking for "SHENZHEN I" -- which doesn't match my posts for "SHENZHEN I/O"

**Comment by bep** [comment]
I assume you know that you can have content files with proper titles for your terms?

So "Retro-Grade" (term) can easily have a title with slashes or whatever.

**Comment by tsuereth** [comment]
I hadn't considered that option, and it does provide a workaround for me; which won't be terribly difficult to maintain, given how few titles have this problem.  Thanks for the suggestion!

It's still a bit non-ideal, since my content will have to remember to use "Retro-Grade" to reference the game "Retro/Grade"

Following the discussion on #4092 , and given that I no longer need a template function for "segment" versus full-path sanitization; would you agree with the longer-term goal of cleaning up how Hugo joins paths together?  (To ensure that paths made of "partOne" "part/Two" "partThree" doesn't include a spurious slash in the second part.)

**Comment by tsuereth** [comment]
On further testing, this workaround actually isn't sufficient for my use-case.

* If I make a content file for the Retro/Grade term at `content/games/retro-grade/_index.md` then references to a term like "Retro-Grade" will resolve it; and if I set the title in this content file to "Retro/Grade" then that term's page will display the title I want.

* However, if I associate a post or page with the game "Retro-Grade" (i.e. `games = ["Retro-Grade"]`) then the only content I can display on that post/page is "Retro-Grade" -- I don't believe there is a way to reverse-lookup the term title "Retro/Grade" from a pre-sanitized string.

**Comment by moorereason** [comment]
The fix for this issue has been reverted in #5519.  Discussions on fixing this without breaking sites that depend on this "feature" can be found in #5520.

**Comment by bep** [comment]
@moorereason are you sure? That was not the intention, and there are wasn't any existing breaking tests ...

**Comment by moorereason** [comment]
Then I'm mistaken.  Thanks for setting me straight.  👍

**Comment by chris-79** [comment]
So, for all slugs… IMO, anything but lowercase and dashes (or underscores) should be removed

Maybe we can have this as a default, but add a config option for special cases? Like:
```
slugs_allow = ["/","(",")"]
```
¯\\\_(ツ)\_/¯

**Comment by jmooring** [comment]
Closing.

The `.Page.GetTerms` method returns the correct results regardless of slashes in term. Example that includes both methods described above:

```text
git clone --single-branch -b hugo-github-issue-4090 https://github.com/jmooring/hugo-testing hugo-github-issue-4090
cd hugo-github-issue-4090
hugo server
```
