### ISSUE TITLE
ref and relref do not work if it is in layout folder

### ISSUE THREAD

**Issue by Mirodil** [gohugoio/hugo#4093]
if you use the following code:
```
{{ relref "content/post/post1.md" }}
```
or
```
{{ relref "post/post1.md" }}
```

hugo throws the following error
```
executing "partials/_left-menu.html" at <relref "content/post...>: error calling relref: invalid Page received in RelRef
```

**Comment by bep** [comment]
See https://github.com/gohugoio/hugoDocs/issues/264

**Comment by Mirodil** [comment]
Thank you link for doc, but does not help at all.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting.
