### ISSUE TITLE
 Builds to Docs directory Broken

### ISSUE THREAD

**Issue by uberdave** [gohugoio/hugo#4094]
Hugo Static Site Generator v0.30.2 linux/amd64 BuildDate: 2017-10-19T06:34:27-05:00

Following the guide to deploy to Github using docs folder; and pushing to Github renders the following:
![_github io-cafejamz_](https://user-images.githubusercontent.com/3323239/32928421-71fba6ac-cb17-11e7-9724-7b30c9e0cd26.png)
Same result occurs when deploying to Firebase.
The site was configured following Hugo Quick Start.

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues
