### ISSUE TITLE
Automatic creation of new <p> class for {{ .Content }}

### ISSUE THREAD

**Issue by jensamunch** [gohugoio/hugo#4095]
I clarified this issue. Hopefully helpful:

**Behaviour**
This:
```
---
title="title
---
"some stuff"
```

together with
```
<p class=lead>{{ .Content }}</p>
```

**Expected outcome**
```
<p class=lead>some stuff</p>
```

**Actual outcome**
```
<p class=lead></p>
<p>some stuff</p>
```

That feels like a bug to me. Maybe because you couldn't see the html tags in previous post
https://github.com/gohugoio/hugo/issues/4074

**Comment by bep** [comment]
Your example does not make much sense to me. I understand you want to add some class to the first paragraph in `.Content`, which isn't currently supported/easily done. It will probably happen eventually. But that is covered in other issues.

You may want open an issue on discuss.gohugo.io to discuss alternative ways to get where you want.

**Comment by jensamunch** [comment]
I think you misunderstand me.

Hugo inserts {{.Content}} into a new <p> class and IGNORES the <p> class within which it was placed.

This:
<p class=lead>{{ .Content }}</p>

Becomes:
<p class=lead></p>
<p>{{ .Content }}</p>

**Comment by kaushalmodi** [comment]
Nesting Markdown inside `div`, `p`, etc HTML tags is not supported at the moment.

The following hack/workaround though might work..

```
<div class="foo">
<div></div>
{{ .Content }}
</div>
```
