### ISSUE TITLE
Feature suggestion: add indexing with algolia

### ISSUE THREAD

**Issue by tjamet** [gohugoio/hugo#4104]
Hi,

I am loving using hugo for websites and am currently using algolia to index my pages.

I have currently implemented it by dumping indexed documents as json and running a curl script to upload all json documents afterwards.

my `config.toml` looks like this:
```
[outputs]
    page = ["HTML", "RSS", "JSON"]
```

the template looks like this:
```
{
    "title": {{ .Title | jsonify }},
    "date": {{.Date.Format "2006-01-02"| jsonify}},
    "plain": {{.Plain | jsonify}},
    "summary": {{ .Summary | jsonify }},
    "reading_time": {{.ReadingTime | jsonify }},
    "objectID": {{ .RelPermalink | jsonify }}
}
```

and the curl script looks like this:
```
find public -name drafts -prune -o -name 'index.json' -exec curl -X POST -H "X-Algolia-API-Key: ${API_KEY}" -H "X-Algolia-Application-Id: ${APPLICATION_ID}" -d @{} "https://${APPLICATION_ID}.algolia.net/1/indexes/${index}" \;
```

I was wondering if there would be an opportunity to get this indexing done by default by the engine, having a `config.toml` like
```
[index]
  algolia.outputs = ["page"]
  algolia.index = <indexName>
  algolia.application_id = <ID>
```
And find a solution not to have the secret in the `config.toml` (command line? environment variable? from a file?)

I would be happy to help having this feature if you think it is interesting for the engine

**Comment by bep** [comment]
Curious: Why do you output one JSON per page? Would it not be better to dump all pages into one JSON?

As to adding this to Hugo, my initial thought is: Not now. Maybe when we get some "processing pipeline" in place, and then hopefully also with some plugin support.

**Comment by tjamet** [comment]
Indeed it would be better, reducing the number of requests at the same time
There are no much more reason than the first thing I got to work
