### ISSUE TITLE
File watching takes a second to detect changes

### ISSUE THREAD

**Issue by asilgag** [gohugoio/hugo#4106]
In Ubuntu, sometimes "hugo server" takes a second to detect file changes before it can regenerate the site.

This does not happen all the time, but it is quite  frequent, half the time more or less: sometimes it detects changes instantly, but other times it takes a second.

Steps to reproduce it:
<pre>
sudo apt update
sudo apt install hugo
hugo new site quickstart
cd quickstart
git init
git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
echo 'theme = "ananke"' >> config.toml
hugo new posts/my-first-post.md
hugo server -D
</pre>

Open a new console and place it side by side with the previous one. Then, trigger a WRITE command on a content:
<pre>
touch -m content/posts/my-first-post.md 
</pre>

Hugo will detect the file change, regenerating the site. Try the above command a few times to detect the problem.

"hugo env" outputs the following:
<pre>
$ hugo env
Hugo Static Site Generator v0.30.2 linux/amd64 BuildDate: 2017-10-19T13:34:27+02:00
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.9.1"-
</pre>

**Comment by bep** [comment]
I suggest you start by creating an issue here:

https://github.com/fsnotify/fsnotify

Note that I don't experience similar problems, but I'm on `macOS`, so this is perhaps OS/kernel version/disk... related. I don't know, but we're not staffed to track upstream issues on this level. 

If you want to discuss this further, use the Hugo forum.
