### ISSUE TITLE
Automatically get a theme

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4108]
We have 185 themes in the themes repo now (!) and `git clone --recursive`, while being a convenient way of "testing different themes", is a big task, even timing out for many people.

This issue may be the start to a more complete `hugo get` command that I have been talking about, which could get some ways of handling external resources such as themes and other components (shortcodes etc.).

But the scope of this is smaller, it is about themes only.

The simple goal is to make this even quicker:

https://gohugo.io/getting-started/quick-start/

**Step 3** should be reduced from:

```bash
cd quickstart;\
git init;\
git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke;\

# Edit your config.toml configuration file
# and add the Ananke theme.
echo 'theme = "ananke"' >> config.toml
```

  To:

```bash
# Edit your config.toml configuration file
# and add the Ananke theme.
echo 'theme = "ananke"' >> config.toml
```

If you want to test another theme, just edit your `config.toml`.

There are lots unsaid in the above, but that is just information hiding so I don't see all the problems that may convince me not to do this.

Some notes to the above:

```
hugo get https://github.com/budparr/gohugo-theme-ananke.git
hugo get -u https://github.com/budparr/gohugo-theme-ananke.git
hugo get -u ./...
hugo get gohugo-theme-ananke
hugo get --prune
```

/cc @digitalcraftsman

**Comment by digitalcraftsman** [comment]
185 themes in an impressive number and I can be cumbersome to clone all of them. I'll think a bit more about the `hugo get` command in the next days.

@bep the code examples for the reduction of step 3 are the same ;)

**Comment by bep** [comment]
>@bep the code examples for the reduction of step 3 are the same ;)

Fixed ... Also note in the above that the current theme repo will be left unchanged, this is just some "lazy Git client" on top of that.

**Comment by digitalcraftsman** [comment]
Isn't this a duplicate of https://github.com/gohugoio/hugo/issues/2648?

**Comment by bep** [comment]
>Isn't this a duplicate of #2648?

No, it is a sub-set of that issue. Much smaller in scope.
