### ISSUE TITLE
hugo server not working 

### ISSUE THREAD

**Issue by kasvijay** [gohugoio/hugo#4109]
Hi,

It seems I have a weird issue with Hugo. The `hugo server -D` works fine for me but not the `hugo server`. If I run `hugo server` I'm unable to see the posts I have created.

My config.toml looks like:
```
baseURL = "https://kasvijay.github.io/vapordocs/"
languageCode = "en-us"
title = "Vijay K A S - iOS Developer && Explorer"
theme = "beautifulhugo"
publishDir = "docs"
canonifyURLs = true
contentDir = "content"
```
I'm trying to deploy it to my Github page. Kindly let me know what is wrong.
My GitHub repo link is https://github.com/kasvijay/vapordocs. You can find the whole repo there.

**Comment by Jos512** [comment]
All of your content files have their draft variable set to `true`. By default, Hugo doesn't turn content that's set to draft into pages. That means `hugo server` works for you as expected: not publishing the draft pages. 

It also explains why, when you force Hugo to publish all draft content with `hugo server -D` the posts *do* appear. If you want, you can force Hugo to generate all draft content like that. For more, see [generating draft content in Hugo](https://www.codestudies.net/hugo/recipes/generate-draft-content/).

Of course, the other solution would be to set the `draft` variable in your content files to `false`, or remove it completely. That way the content is not draft anymore and Hugo builds its regularly.

(You can post future questions on [the Hugo forum](https://discourse.gohugo.io/). GitHub is intended for bug reports and feature requests, while questions like this are for the forum.)
