### ISSUE TITLE
How to add multiple lists in home page

### ISSUE THREAD

**Issue by chanakaDe** [gohugoio/hugo#4110]
Guys, I need to add multiple lists in my gohugo blogging page. As default , it gives only one list. When we create a new post, it automatically adding to that list. But i need to use 3 lists for 3 different kind of posts as shown in the image. How can I do this ? Please help me on this.

![screenshot from 2017-11-21 16-22-21](https://user-images.githubusercontent.com/7803591/33069042-36b6444c-ced9-11e7-9ad5-7ba2cd5cbf9f.png)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
