### ISSUE TITLE
hugo server --appendPort=false stopped working in Hugo 0.31

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4111]
Also, seems like the `baseURL` from CLI in `hugo server` is also not working as expected (or: It is showing wrong address in console; probably the bind address) in "single host mode".

**Comment by bep** [comment]
For `baseURL` the new rule will be:

* If multihost, baseURL from command line is not supported
* Else: Use that value (like before)

**Comment by daftaupe** [comment]
Thanks, I tried v0.31.1 and have no issue anymore !
