### ISSUE TITLE
Bug with Hugo checking minimum required version `min_version`

### ISSUE THREAD

**Issue by gcushen** [gohugoio/hugo#4127]
Hugo is versioned according to the standard 3-part **semantic versioning scheme** i.e. takes the form of X.Y.Z, such as `"0.30.2"`.

However, currently themes incorrectly define the minimum version in `theme.toml`, in the form `0.30`. Note that this **value is stored in both the incorrect format (not the semantic versioning scheme) and the incorrect data structure - it is stored as a decimal (float) rather than the correct data structure for the semantic versioning scheme, which is a string** as detailed above.

**Hugo itself also fails to parse `min_version` correctly** in `theme.toml` when checking if it meets the minimum required Hugo version for a theme. For example, it fails to check the minimum requirements if the version is presented correctly in the form `min_version = "0.30.2"`. The requirements are only checked by Hugo when the version is specified in the invalid format.

This bug should be fixed firstly to be consistent with the version scheme which Hugo is actually using and secondly so a theme can correctly specify the exact minimum required version of Hugo which is compatible with the theme (e.g. if a bug in Hugo 0.30.0 causes problems in the theme, the theme creator will want to specify the patch where the bug is fixed, such as 0.30.2, as the minimum required version).

**Comment by bep** [comment]
>Hugo is versioned according to the standard 3-part semantic versioning scheme i.e. takes the form of "0.30.2".

That is not correct. We have a mix of 2-part (main releases) and 3-part (patch releases).

**Comment by gcushen** [comment]
@bep thanks for your fast response!

So the 3-part semantic versioning scheme is currently only used for patch releases, but the bug still stands that Hugo ignores `min_version` when a correctly formatted patch version is supplied e.g. `"0.30.2"`

Please consider flagging this as a bug since there are compelling reasons why it should be fixed:

> This bug should be fixed firstly to be consistent with the version scheme[s] which Hugo is actually using and secondly so a theme can correctly specify the exact minimum required version of Hugo which is compatible with the theme (e.g. if a bug in Hugo 0.30.0 causes problems in the theme, the theme creator will want to specify the patch where the bug is fixed, such as 0.30.2, as the minimum required version).

**Comment by gcushen** [comment]
Thank you @bep 😃

**Comment by bep** [comment]
I cannot reproduce this. I have seen issues in the wild where people sets the `min_version` to a non-string value, which does not work, i.e.

```toml
min_version = "0.30.1"
```

But this works fine in my tests:


```toml
min_version = "0.30.1"
```

**Comment by gcushen** [comment]
The patch version was correctly formatted as a string.

I was basing this bug report purely on several error logs that were submitted to me over the last few months from theme users where the underlying issue was incompatible Hugo version yet the associated error did not appear in the error logs that were received from the users.

Having just tested this myself, I cannot reproduce the error on Hugo v0.30.2+ when setting to a fake future version `min_version = "0.50.1"`.

Sorry for the noise and thanks again for your time! I suppose perhaps the users may have been using very old versions of Hugo where the version checking logic may have functioned differently, or perhaps the version error was getting overridden somehow.

**Comment by bep** [comment]
>I suppose perhaps the users may have been using very old versions of Hugo where the version checking logic may have functioned differently

Yes, I remember fixing this at one point -- I even have proper tests for this now.

**Comment by dwayneem** [comment]
Now fails with 
`
Error: failed to read module config for "ananke" in "/home/dwayne/quickstart/themes/ananke/theme.toml": unmarshal failed: Near line 11 (last key parsed 'min_version'): Invalid float value: "0.30.2"
`

**Comment by dwayneem** [comment]
Quick start says 
git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke

Should it be using rburgst repository instead?
