### ISSUE TITLE
pygmentsCodeFences breaks mmark code captioning

### ISSUE THREAD

**Issue by cao** [gohugoio/hugo#4129]
Settings pygmentsCodeFences to true breaks mmark code caption functionality. 

Hugo version: 0.31

config.yaml
```
pygmentsCodeFences: true
```

example.mmark
~~~
---
markup: mmark
slug: example
title: Example
---

```bash
highlight bash source code
```
Figure: some bash source
~~~

Expected result: code section with highlighting and code caption.
Actual result: code section with highlighting, missing the code caption.

The caption will be generated when removing the language (`bash` in the example above), but, in turn, it removes the highlighting.

**Comment by jschaf** [comment]
This is still a bug.  I can reproduce on 0.54.0.

**Comment by cao** [comment]
This is still a bug. I can reproduce it with version 0.55.6.
