### ISSUE TITLE
Link to taxonomy lists fails with custom permalinks

### ISSUE THREAD

**Issue by madeso** [gohugoio/hugo#4130]
The links in the samples expects the taxonomy list to be at the default location:
https://gohugo.io/templates/taxonomy-templates/#order-taxonomies
but that will fail with a custom permalink introduced in v0.31 since the page is probably not rendered at /PLURAL/TERM/.

The only workaround I've found is to create a per-term page for the custom link instead of the general _default/terms.html template.

**Comment by bep** [comment]
I think this is a documentation issue. It should be possible to do this without "manual URL construction".

@rdwatters are those your examples?

I'll keep this open for now -- in case this isn't currently possible, we should make it.

**Comment by shaform** [comment]
I am interested in knowing how to support custom permalinks of taxonomy in templates as well. Is it possible to do this now? How?

**Comment by vassudanagunta** [comment]
If PR #4796 is merged, then you won't need to hardcode anymore. You could use 
```
{{% relref "tags" %}}
```
which would be resolved to whatever url `tags` is published to. Likewise a call to `.GetPage "tags"` would return you the page object, from which you could query its actual URL, title or whatever.

I already take advantage of this in my fork of Hugo.

**Comment by vassudanagunta** [comment]
@bep I think this issue should be re-opened.

**Comment by shaform** [comment]
It looks like we could use:

```
{{ with $.Site.GetPage "taxonomy" $type $termName }}
```

Perhaps I should submit a PR to modify the document? Currently it says:

```
 <li><a href="{{ $.Site.LanguagePrefix }}/{{ $data.Plural }}/{{ $value.Name | urlize }}"> {{ $value.Name }} </a> {{ $value.Count }} </li>
```
, which certainly still fails with custom permalinks
