### ISSUE TITLE
Add "contains" operator in where  function to support list pages in nested subdir

### ISSUE THREAD

**Issue by rfancn** [gohugoio/hugo#4131]
If we want to get all pages under specific subdir in some section, we can add _index.md for each section,  and the template corresponding logic  works like below:
```
{{ $currentDir := .Dir }}

{{ range .Site.RegularPages }}
            {{ if hasPrefix .Path $currentDir }}
                {{ .Title }}
            {{ end }}
 {{ end }}
```
Above logic works to list out all pages under each nested section(subdir), but it seems there is no way to generate a collection and build a paginator by `where` function, I also didn't see a way to generate a slice manually.

The quick way to implement above logic, it need add one operator like `contains` in `where`  function to compare the field value `contains` match value, or the more general way is to add a template function like `apply` to returns a new slice filter with a conditional check function.

**Comment by rfancn** [comment]
PR: [4132](https://github.com/gohugoio/hugo/pull/4132) tested works for  layouts/_default/section.html to list all pages under nested subdir. (**Important**: all nested subdir need have corresponding _index.[langugage].md to get it works as expected)
```
{{ $currentDir := .Dir }}
{{ $paginator := .Paginate ( where (where .Site.AllPages "Kind" "page") "Path" "contains" $currentDir ) }}
{{ range $paginator.Pages }}
     {{ .Title }}
{{ end }}
```

**Comment by bep** [comment]
You can easily list `.Sections` and `.Pages` and combine them with `union` and send them into a paginator.

The PR #4132 looks a little bit too big to me -- and would need a really important use case not possible any other way for me to consider merging.

**Comment by rfancn** [comment]
@bep Thanks for your comments, I may not expressed clearly the use case I want to show here, but you may check if the .Section and .Union you mentioned can fix the problem I list here: http://hdget.com/hugo-list-pages-in-nested-dirs/

**Comment by rfancn** [comment]
@bep I just want to filter all those pages under specific nested sub dirs not only root sector , as far as I know,  regardless how much deeper the sub dirs the page sits in, the section always be  the top root dir.
