### ISSUE TITLE
humanize and diacritcs

### ISSUE THREAD

**Issue by robsonsobral** [gohugoio/hugo#4133]
Hi!

`humanize` doesn't uppercase diacritcs.

```
{{ "death" | humanize }} -> Death
{{ "óbito" | humanize }} -> óbito
```
Tested on Hugo Static Site Generator v0.31.1 darwin/amd64 BuildDate: 2017-11-27T13:55:00-02:00

Thank you!

**Comment by bep** [comment]
https://github.com/markbates/inflect/issues/6
