### ISSUE TITLE
Deployed site not working when loaded locally

### ISSUE THREAD

**Issue by VanKurt** [gohugoio/hugo#4134]
I have created my first hugo site. When running it with "hugo server", it looks great.
Then I published the site and tried to open it locally from the file system. Now the site appears to be broken and all garbled up. The Browser reports two errors that are not present when loading the site served by hugo:

> ReferenceError: hljs is not defined[Learn More]
> ReferenceError: mermaid is not defined[Learn More]

The corresponding part in the index.html is the following:

>     <script src="/js/clipboard.min.js?1511940117"></script>
>     <script src="/js/perfect-scrollbar.min.js?1511940117"></script>
>     <script src="/js/perfect-scrollbar.jquery.min.js?1511940117"></script>
>     <script src="/js/jquery.sticky.js?1511940117"></script>
>     <script src="/js/featherlight.min.js?1511940117"></script>
>     <script src="/js/html5shiv-printshiv.min.js?1511940117"></script>
>     <script src="/js/highlight.pack.js?1511940117"></script>
>     <script>hljs.initHighlightingOnLoad();</script>  <<< HERE
>     <script src="/js/modernizr.custom.71422.js?1511940117"></script>
>     <script src="/js/learn.js?1511940117"></script>
>     <script src="/js/hugo-learn.js?1511940117"></script>
> 
>     <link href="/mermaid/mermaid.css?1511940117" type="text/css" rel="stylesheet" />
>     <script src="/mermaid/mermaid.js?1511940117"></script>
>     <script>
>         mermaid.initialize({ startOnLoad: true });   <<< HERE
>     </script>

E.g. the mermaid.js script seems to be located on disk where it should be.

So why can't the page be loaded from the local file system? Is there anything I need to change in my config to make it work?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
