### ISSUE TITLE
Get root URL for all site languages

### ISSUE THREAD

**Issue by andi1984** [gohugoio/hugo#4135]
Is it possible to generate on template level links to the root URL of all site languages like http://test.com, http://test.de etc.? Could not find this option, but maybe I did not find the correct one.

I would like to create a global language switch, so not only when currently viewed post is translated, but globally and in general adding links to all different languages of the main site.

Thx in advance for your help!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
