### ISSUE TITLE
Error in _internal/opengraph.html template

### ISSUE THREAD

**Issue by drlogout** [gohugoio/hugo#4136]
When I include the internal open graph template 

`{{- template "_internal/opengraph.html" . -}}`

I got the following error:

` error calling partial: template: partials/opengraph.html:26:16: executing "partials/opengraph.html" at <.Params.videos>: can't evaluate field Params in type []interface {}`

I checked out the source of the template and found:

https://github.com/gohugoio/hugo/blob/488631fe0abc3667355345c7eb98ba7a2204deb5/tpl/tplimpl/template_embedded.go#L208

```html
{{ with .Params.videos }}
{{ range .Params.videos }}
  <meta property="og:video" content="{{ . | absURL }}" />
{{ end }}
{{ end }}
```
Shouldn't it be `{{ range . }}` instead of `{{ range .Params.videos }}`?

hugo version: v0.31.1

**Comment by bep** [comment]
>Shouldn't it be {{ range . }} instead of {{ range .Params.videos }}?

Yes. How that slipped into the source is a mystery.
