### ISSUE TITLE
Can't evaluate field Parse in urls

### ISSUE THREAD

**Issue by drlogout** [gohugoio/hugo#4140]
`urls.Parse` throws an error:

`at <urls>: can't evaluate field Parse in type interface {}`

I used the example from the [documentation](https://gohugo.io/functions/urls.parse/):

```go
{{ $url := urls.Parse "http://www.gohugo.io" }}	
```

My hugo version is:  v0.31.1

**Comment by moorereason** [comment]
I can't reproduce.

**Comment by drlogout** [comment]
I was using the hugo boilerplate [victor-hugo](https://github.com/netlify/victor-hugo), which pull its own hugo binary. The version of that binary was 0.26 in contrast to the version installed system wide.

After updating the victor-hugo version everything worked as expected.
