### ISSUE TITLE
Hugo complains about missing baseURL when using multilang baseURL

### ISSUE THREAD

**Issue by internetfreak** [gohugoio/hugo#4142]
**Hugo Version:** 0.31.1

When building a site with the latest hugo release, hugo will complain about a missing baseURL in the config or as flag when using the new multilanguage feature for baseURL. If I set the baseURL through --baseURL or language independant, then no error will occur. Even with that error, hugo will build the page correctly using the defined url for all languages

Don't know it this is a oversight or if I use hugo incorrectly, I only wrote in my config what the documentation said.
I also noticed that hugo server correctly starts two servers for my languages (I have de end en defined) but if I start the server without baseURL, both servers will have /en/ in the url, i.e. `http.//localhost:11313/en` and `http://localhost:1314/en`. In this case, only the latter url will actually return the site while the other does not show any kind of error but also not returns any page.

I hope you can follow my words. If something's unclear, just ask and I will explain it again.

**Comment by bep** [comment]
I think I would have to see your project to understand -- but I would check that you have not specified baseURL on the language level (if that is not what you want -- if so, you need it on all languages, hence the complain).

**Comment by internetfreak** [comment]
Here's my current config:
![image](https://user-images.githubusercontent.com/19251027/33521010-3917e9a2-d7c6-11e7-910e-16d5bc2996d9.png)
I masked the url since the page is not ready yet so I don't want the domain to spread too much for now. Normally I should have no issue with this config as each language has its own baseURL and it's uniquie enough.
With this config, if I simply type `hugo` I get this:
![image](https://user-images.githubusercontent.com/19251027/33521029-849c53b8-d7c6-11e7-9fc0-cd3a81816ac7.png)
The same message occurs when I use hugo server.

**Comment by internetfreak** [comment]
Any news on this? This issue still exists in Hugo v0.33. Technically it looks not like a issue but a small error because I have a baseURL set and hugo seems to use it when building the page but still complains about missing a baseURL

**Comment by bep** [comment]
I need to see your site source if I'm going to help you. I have several similar sites working, so I will assume this isn't a bug.

**Comment by internetfreak** [comment]
The site itself is hosted on a private version control system so I cannot make the source public. Aside from a few templates and a bunch of (mostly empty, I often only used title and url in front matter) .md files there's nothing special which should be responsible for that error. The config is still the same as posted above, I only made a few changes and additions regarding the menus.
It does not matter if I call hugo without parameters or with `hugo server`, the message appears for both. For local development and testing I supplied `--baseURL http://localhost`.
As said, because building the links works (with and without explicit baseURL via parameter) I assume that the message is written to the output because hugo sees the baseURL but seems to fail the check for a baseURL and thus complains about it

**Comment by bep** [comment]
What is the exact error message?

**Comment by internetfreak** [comment]
As noted as screenshot above, the error I get is this one: `ERROR 2018/01/19 01:23:52 No 'baseURL' set in configuration or as a flag. Features like page menus will not work without one.
`
The documentation states you need a baseURL per language which I set up as you can see in my config
