### ISSUE TITLE
Hugo Docs > Templates > Homepage Template returns 404

### ISSUE THREAD

**Issue by rohith** [gohugoio/hugo#4148]
Homepage Template in Docs returns 404

![image](https://user-images.githubusercontent.com/5032439/33642402-df137736-da5f-11e7-8655-f71f3f683b0c.png)

**Comment by budparr** [comment]
Thank you. I'm "guessing" it has to do with the "Uncached Content Errors" issue Netlify was having yesterday, either anew or left over from that. http://netlifystatus.com/

**Comment by rohith** [comment]
Thanks, it's back now :thumbsup:
