### ISSUE TITLE
Is there any way to get all images' url in post content ?

### ISSUE THREAD

**Issue by nodejh** [gohugoio/hugo#4150]
For example, I have a post like this:

```
---
title: "A title"
date: 2010-01-01
---
hello hugo.

![img1](https://avatars2.githubusercontent.com/u/10287125)
![img2](https://avatars2.githubusercontent.com/u/10287125)
```

And I want to get images list by a page variable such as `.Title` is "A title".

 e.g.: `.Images` is  an array `["https://avatars2.githubusercontent.com/u/10287125", "https://avatars2.githubusercontent.com/u/10287125"]`

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
