### ISSUE TITLE
mac os release name

### ISSUE THREAD

**Issue by tjamet** [gohugoio/hugo#4159]
Hi,

I am trying to automate hugo installation in a script for unix platforms (mac os and linux mainly) and would like to use some [docker like](https://docs.docker.com/compose/install/#install-compose) command that could look like:
```
sudo curl -L https://github.com/gohugoio/hugo/releases/download/${version}/hugo-`uname -s`-`uname -m` -o /usr/local/bin/hugo
```

I noticed that there are substitutions on go releaser to have, from what I understand, [human readable names] (https://github.com/gohugoio/hugo/blob/master/goreleaser.yml#L44) preventing me from using this kind of automation and I am wondering if it wouldn't be interesting to keep the output of `uname -s` unmodified in the filename?

**Comment by bep** [comment]
No, that would break a lot of other automations. You will have to automate this in another way.
