### ISSUE TITLE
_index.en.adoc is not getting recognized at the homepage level: /content

### ISSUE THREAD

**Issue by pgorod** [gohugoio/hugo#4166]
When I changed my homepage file from `content/_index.en.md` to `.adoc` extension, I started seeing a message on my homepage instructing me on how to start building my site. I investigated, and it’s my theme’s welcome message, because it’s testing content like this:

```go
{{if .Site.Home.Content }} 
{{.Site.Home.Content}}	
{{else}} 
       <h1>Customize your own home page</h1>
       (etc...)
```

It seems it's a bug, _index.en.md is correctly recognized as Home page content, but _index.en.adoc isn’t.

This change from .md to .adoc worked perfectly in the rest of my site, through all the different sub-directories.

**Comment by bep** [comment]
I have now added tests for this, but this works as I expected. Could you have another look at this and see if it still is a problem?

**Comment by pgorod** [comment]
Hi. Thanks for working on this.

I tried changes to the .adoc file and in fact I can get a `_index.en.adoc` Homepage displayed correctly with this content:

```
---
title: "SuiteCRM Documentation"
---

= Welcome to the SuiteCRM Documentation site

Hi, are you there?
```

So I changed things back to how they were and I lost my Homepage again, with this content:

```
---
title: "SuiteCRM Documentation"
---

= Welcome to the SuiteCRM Documentation site

```
Now, I know my Theme does tricks with the main title (level `=`) - it removes it from content and shows it with a special treatment on top. So I tested to see if that was the culprit, and it was.

So this works well:


```
---
title: "SuiteCRM Documentation"
---

== Welcome to the SuiteCRM Documentation site

```
The theme doesn't play with this level of title, so the page appears correctly. 

As far as Hugo is concerned. it seems the problem is empty content. Do you think this is anything that needs to be improved in Hugo, or simply something the theme needs to improve?

**Comment by bep** [comment]
>Do you think this is anything that needs to be improved in Hugo, or simply something the theme needs to improve?

OK, now I understand. No, that is not something we want to do. You can always add a `len` check to the content check to check that it has some length to it.

**Comment by bep** [comment]
Also, there is `.RawContent` that you could check.

**Comment by pgorod** [comment]
I am not proficient enough in these things to work on it myself, yet but I'll take it up with my Theme author to see if he thinks he can improve handling of this situation. Thank you for your help and advice.
