### ISSUE TITLE
develop a CMS base on hugo

### ISSUE THREAD

**Issue by guotie** [gohugoio/hugo#4174]
I want to develop a CMS base on hugo, Plan is following:

1. Add a abstract layer, make hugo read config from database with same API of config files
2. Move all config file to database;
3. Move Content to database;
4. build a web UI, make all hugo cli operations in web UI

any suggestions?

**Comment by kevingimbel** [comment]
Hi @guotie,

I think this question is better suited for the Forum at https://discourse.gohugo.io/

The GitHub Issue tracker is for issues with hugo only, in the Forum however people should be able to help you or give you input on your idea.

---


As for a quick answer: No, this would not make sense and I'd strongly recommend not to try and connect Hugo to a database as you suggested. You can however build a Web App that creates files in a hugo structure and then hugo can generate a site from it.

All the best,
Kevin
