### ISSUE TITLE
[Feature] Way to check value of variables

### ISSUE THREAD

**Issue by mtn** [gohugoio/hugo#4176]
I might just not be aware of the correct way to do this, but I don't think there's a easy way to check the value of one of a template variable. For example, if I want to find what `{{ .Permalink }}` is set to, I'll add it someplace in a template and see what it resolves to. This makes it painful to debug issues on my theme related to this with others who aren't familiar with how Hugo themes work. Is there a better way to do this and if not, would we consider adding one? I realize it's wouldn't be that straightforward since many variables depend on context.

Thanks! 🌳

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by mtn** [comment]
Ah right, sorry about that.
