### ISSUE TITLE
[Enhancement] Support using ‘with’ along with ‘block’

### ISSUE THREAD

**Issue by 1138-4EB** [gohugoio/hugo#4178]
From: https://discourse.gohugo.io/t/use-with-along-with-block/9657

> I’d like to have some code added around every ‘main_header’ block, except when it is not defined:
>
> ```
> {{ with block "main_header" }}
>  <div class="my header">
>  {{ . }}
>  </div>
>{{ end }}
>```

**Comment by bep** [comment]
You need to raise Go template issues/requests here:

https://github.com/golang/go/issues
