### ISSUE TITLE
Chroma does not format "Makefile", requires "makefile"

### ISSUE THREAD

**Issue by hatched** [gohugoio/hugo#4182]
Hugo Static Site Generator v0.31.1 darwin/amd64 BuildDate: 2017-12-23T14:37:55-06:00

When building markdown files with Makefile code blocks if the language tag is "Makefile" it will not add the additional markup to the output, however changing that to "makefile" will. This appears to work correctly when running the last couple versions of chroma standalone.

(not processed)

```
```Makefile
.PHONY: lint
lint: lint-python lint-components lint-js lint-css
```

```
<div class="highlight"><pre class="chroma"><code class="language-Makefile" data-lang="Makefile">.PHONY: lint
lint: lint-python lint-components lint-js lint-css</code></pre></div>
```

(processed)
```
```makefile
.PHONY: lint
lint: lint-python lint-components lint-js lint-css
```

```
<div class="highlight"><pre class="chroma"><code class="language-makefile" data-lang="makefile"><span class="nf">.PHONY</span><span class="o">:</span> <span class="n">lint</span>
<span class="nf">lint</span><span class="o">:</span> <span class="n">lint</span>-<span class="n">python</span> <span class="n">lint</span>-<span class="n">components</span> <span class="n">lint</span>-<span class="n">js</span> <span class="n">lint</span>-<span class="n">css</span>
</code></pre></div>```

**Comment by bep** [comment]
Yes, in Hugo you need "makefile".

**Comment by bep** [comment]
I don't think we do any case fiddling with the language tag before we pass this on to Chroma, but if someone wants to check, I will keep this issue open for a little.

But:

1) Chroma issues should be raised on the Chroma issue tracker.
2) If you still think it is a Hugo issue, you should compare it with the same Chroma version as Hugo uses.

**Comment by hatched** [comment]
@bep I had attempted to reproduce this with v2 and v1.1 of Chroma CLI and was not able to outside of Hugo.

**Comment by hatched** [comment]
I've had a go at this again and while I still can't reproduce it outside of Hugo, I also don't see anything in the code path that would be modifying this string.
