### ISSUE TITLE
 disablePathToLower doesn’t work for taxonomic terms

### ISSUE THREAD

**Issue by wolfgang42** [gohugoio/hugo#4183]
I’m migrating an existing site to Hugo, and trying to preserve the same URL structure. I’ve set `disablePathToLower` to keep the capitalization the same, and this is working fine for posts, but the tags are still having their URLs converted to lowercase. Is there a separate option needed to disable this function for taxonomies?

Version: Hugo Static Site Generator v0.31.1 linux/amd64 BuildDate: 2017-11-27T06:26:24-05:00
OS: Ubuntu 16.04.3 LTS

(Also posted [on Discourse](https://discourse.gohugo.io/t/disablepathtolower-doesnt-work-for-taxonomic-terms/9429) but moved here since I didn't get a response and this looks like an actual bug.)

**Comment by bep** [comment]
Please use the discourse thread.
