### ISSUE TITLE
unable to change date format

### ISSUE THREAD

**Issue by githubgnulinux** [gohugoio/hugo#4189]
In the file 'single.html' of a theme layout directory, the file format was changed:

<span class="post-date">{{ .Date.Format "Mon, 2 Jan 2006" }}</span>

The blog posts show dates incorrect format mm-dd-yy, the correct format is dd-mm-yy

How to change please?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
