### ISSUE TITLE
List of 0.32-DEV Regressions

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4190]
If you test the latest Hugo and find bugs, please report them here. I will attach the fixes to this issue.

**Comment by matcornic** [comment]
`{{.Page.File.Dir}}` does not contain a trailing slash anymore (found with https://github.com/matcornic/hugo-theme-learn/issues/97). Used in Learn and Docdock themes for `attachments` shortcode (cc @vjeantet )
