### ISSUE TITLE
Wrong robots.txt template in Multilingual Multihost

### ISSUE THREAD

**Issue by marcanuy** [gohugoio/hugo#4193]
Using [Multilingual Multihost](https://gohugo.io/content-management/multilingual/#configure-multilingual-multihost) with [robots.txt](https://gohugo.io/templates/robots/) generates a `robots.txt` file directly in `public` but not for each language site, for example, having *spanish* (es) and *english* (en), it currently generates:

```
public/
├── en/
├── robots.txt
└── es/
```

instead of
```

public/
├── en/
|   └── robots.txt
└── es/
    └── robots.txt
```

* Tested with: Hugo Static Site Generator v0.31.1 linux/amd64 BuildDate: 2017-11-27T08:26:24-03:00

**Comment by bep** [comment]
Yea, that sounds like a bug. The workaround would be to turn off it off (`disableKinds = ["robotsTxt"]`) and create a custom output format doing the same.
