### ISSUE TITLE
html content not recognised

### ISSUE THREAD

**Issue by githubgnulinux** [gohugoio/hugo#4194]
The documentation states that front matter changed to 

+++```

will allow content to be written in html.

This does not occur. See latest comment at https://discourse.gohugo.io/t/solved-using-html-for-content-pages-instead-of-markdown/3374

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues

We have tests for HTML as content, and I just did a quick test -- and it works fine. Take further questions on the forum.

**Comment by githubgnulinux** [comment]
Example was given in the discourse web site, what is the error in the example given please?

**Comment by githubgnulinux** [comment]
Have tried to show the actual html code, but the web server converts it. How to show the html so that readers can see if there are errors?
