### ISSUE TITLE
html content not recognised

### ISSUE THREAD

**Issue by githubgnulinux** [gohugoio/hugo#4196]
Re-open request for bug: https://github.com/gohugoio/hugo/issues/4194

Reproduction scenario shown in discourse thread: https://discourse.gohugo.io/t/solved-using-html-for-content-pages-instead-of-markdown/3374/12?u=discourser

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

I follow the discussion site closely. Please don't create this double work for me. It is Christmas and I try to spend some of my holiday time to get the new Hugo 0.32 ready for release.
