### ISSUE TITLE
html content failure

### ISSUE THREAD

**Issue by githubgnulinux** [gohugoio/hugo#4197]
Discourse has a silly limit of 20 posts(!), posting here to save waiting.

https://discourse.gohugo.io/t/solved-using-html-for-content-pages-instead-of-markdown/3374/19

 hugo -D serve -b http://localhost
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
1 regular pages created
10 other pages created
0 non-page files copied
0 paginator pages created
1 tags created
1 categories created
total in 16 ms
Watching for changes in /home/.../{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

uzbl http://localhost:1313

web browser does not show correct render of html elements. Source html below.

+++
title = "test"
date = "2017-12-29T12:15:02-00:00"
categories = ["test"]
tags = ["test"]
+++
<h1>
	Welcome
</h1>
<p>
	test html content
</p>

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
