### ISSUE TITLE
bug report governance

### ISSUE THREAD

**Issue by githubgnulinux** [gohugoio/hugo#4198]
What is the decision making process for bugs?

https://github.com/gohugoio/hugo/issues/4197

A discourse web site contributor states that various html elements need to be removed for html content to be recognised. Which part of the documentation tells the user about this requirement?

The final request to use a localhost base directory was followed, but still the web page fails.

Why is the bug report rejected when all information has been provided?

https://github.com/gohugoio/hugo/issues/4197

There is a bug in html and documentation.

Continuing other post to avoid silly limit (https://discourse.gohugo.io/t/solved-using-html-for-content-pages-instead-of-markdown/3374/19)

Directory structure:

ls
archetypes config.toml config.toml~ content data layouts static themes

Config.toml

languageCode = "en-gb"
title = "My New Hugo Site"
theme = "hyde-master"
[params] DateForm = "1.2.1970"
{{ .Date.Format "Mon, 2 Jan, 2006" }}

ls archetypes/
default.md

---
title: "{{ replace .TranslationBaseName "-" " " | title }}"
date: {{ .Date }}
draft: true
---

ls content
test.html

data, layouts, static directories are empty. Themes contains the ‘hyde-master’ unpacked directory from hugo themes web site.

Also delete the above. You do NOT need to declare DOCTYPE again or open the html and body tags. These should be set by the templates of the theme you use.

Once again. You only type the HTML you need on that page directly below the front matter like so:

test file is now:

+++
title = "test"
date = "2017-12-29T12:15:02-00:00"
categories = ["test"]
tags = ["test"]
+++
<h1>
	Welcome
</h1>
<p>
	test html content
</p>

the layout line was deleted from the file test.html

The elements h1 and p are not recognised.

Is your site generated when you run hugo server? Are there any errors in the console?

Is the test file located under /content/test.html?

hugo -D serve
ERROR 2017/12/29 15:12:10 No ‘baseURL’ set in configuration or as a flag. Features like page menus will not work without one.
Started building sites …
Built site for language en:
0 draft content
0 future content
0 expired content
1 regular pages created
10 other pages created
0 non-page files copied
0 paginator pages created
1 tags created
1 categories created
total in 20 ms
Watching for changes in /home/…/{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

ls content/
test.html

uzbl http://localhost:1313

hugo -D serve -b http://localhost
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
1 regular pages created
10 other pages created
0 non-page files copied
0 paginator pages created
1 tags created
1 categories created
total in 16 ms
Watching for changes in /home/.../{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

Web browser fails to render the html elements.

**Comment by onedrawingperday** [comment]
This issue is redundant. Hugo renders HTML.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
