### ISSUE TITLE
Content pages not rendered correcly, except after an edit followed by a live reload

### ISSUE THREAD

**Issue by nlassaux** [gohugoio/hugo#4200]
I created a page */test/index.md* in content. This one is not rendered when using the command `hugo`. It doesn't work with `hugo server` the first time either but does work after changing a value in this file, triggering its live reloading.

On MacOS New Sierra, `Hugo Static Site Generator v0.32-DEV darwin/amd64`. I installed using `go get`

It looks similar to https://discourse.gohugo.io/t/solved-hugo-becomes-strange-dont-generate-pages-without-resaving-them/7535, but without accents in the path this time. Or is Hugo allergic to French?

The following warnings are displayed:
```
WARN 2017/12/31 03:32:10 No translation bundle found for default language "en"
WARN 2017/12/31 03:32:10 Translation func for language en not found, use default.
WARN 2017/12/31 03:32:10 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
```

Link to a GitHub example: https://github.com/nlassaux/bugcasehugo

**Comment by bep** [comment]
Your Hugo project isn't valid, and the behaviour you see is probably a race between duplicate targets.

See https://github.com/nlassaux/bugcasehugo/pull/1

**Comment by nlassaux** [comment]
It worked perfectly, thank you!

**Comment by samplesizeofone** [comment]
I'm experiencing this problem. Unfortunately the links to the bug case and the associated pull request don't seem to work.

How might I tell if I have a race between duplicate targets?

Thanks!
