### ISSUE TITLE
Self-updating binaries?

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4201]
https://github.com/rhysd/go-github-selfupdate

**Comment by gedw99** [comment]
looks pretty good. 
Goes well with go-releaser

**Comment by RealOrangeOne** [comment]
Assuming it doesnt automatically update, this sounds like a useful feature for OSs without Hugo distributed in their package manager. It'd be nice if the update message was fairly small (ie single line), so it's not too intrusive on say CI jobs, places where Hugo is packaged through the system package manager, or for sites that have to use an older version (for whatever reason)

**Comment by bep** [comment]
Note that this was more of a "this could be interesting" bookmark from me. There are major security questions here.
