### ISSUE TITLE
RSSLink Error

### ISSUE THREAD

**Issue by bretonio** [gohugoio/hugo#4207]
Forgive  me if this is redundant as to problems with RSSLink. I found nothing analogous to my difficulty in Issues.

I have been unable to `push` to my Hugo Web log on Gitlab for several months now. 

The build message for a failed `push` is as follows.

```
Running with gitlab-runner 10.3.0 (5cf5e19a)
  on docker-auto-scale (fa6cab46)
Using Docker executor with image publysher/hugo ...
Using docker image sha256:29bc9a75365afa394c5fbdc153287f93bc5967f5aaa1cc0108775e4a82b9b683 for predefined container...
Pulling docker image publysher/hugo ...
Using docker image publysher/hugo ID=sha256:c82a599708fb3df557ee7fa6d81bd390dbebe4ed8671c3f9d05c11198de702f1 for build container...
Running on runner-fa6cab46-project-1689334-concurrent-0 via runner-fa6cab46-srm-1514817644-8d5b1963...
Cloning repository...
Cloning into '/builds/bretonio/echolalia'...
Checking out 34d56c64 as master...
Skipping Git submodules setup
$ hugo
```
And then comes

```
Started building sites ...
ERROR 2018/01/01 14:41:57 Error while rendering "page": template: theme/post/single.html:5:5: executing "theme/post/single.html" at <partial "head.html" ...>: error calling partial: template: theme/partials/head.html:14:15: executing "theme/partials/head.html" at <.RSSlink>: can't evaluate field RSSlink in type *hugolib.PageOutput
ERROR: Job failed: exit code 1
```
But there is no such file as `theme/partials/head.html` or `single.html`. There is `themes/slim/layouts/post/pages/single.html` and `themes/slim/layouts/partials/head.html`.

Running `hugo` to build the site locally returns no errors.

But navigating to `http://localhost:1313/post/index.xml` with `hugo serve` complains of 

```
error on line 1560 at column 166: Encoding error

```
I have been trying to remove the post in which the error first appears by process of elimination. What else? Adding a `pages` folder to `content`? That is all I can tell you at this point. Need more data I am your man.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by bretonio** [comment]
Okay
