### ISSUE TITLE
Page flicker on navigation

### ISSUE THREAD

**Issue by aral** [gohugoio/hugo#4210]
I’ve noticed, at least on Hugo sites deployed to Netlify, that navigating between pages causes a full refresh and a white flicker that’s very distracting (especially when reading documentation, for example). You can see it on the official docs (navigate between pages and notice that the whole browser window goes white every time and then re-draws entirely):

https://gohugo.io/templates/lists/

You can also see it on a couple of sites that I’ve tested, all hosted on Netlify:

* https://indienet.info/
* https://laurakalbag.com

The Smashing Magazine page doesn’t suffer from the same white flash:

* https://www.smashingmagazine.com

Assuming this has to do with caching-related behaviour.

**Comment by budparr** [comment]
I'm not seeing that behavior, even with a throttled connection. What's your [browser/OS](https://www.whatsmybrowser.org/)?

**Comment by RealOrangeOne** [comment]
As Hugo generates static output which is then served by Netlity's server, this is almost certainly _not_ an issue with Hugo. It's highly discouraged to use Hugo's builtin server in production, as its feature set is completely unnecessary, hence no one does.

This is likely an issue with your setup. Have you been able to reproduce this on another browser / device?

**Comment by bep** [comment]
I'm closing this as this doesn't belong in this repo. I'm not saying it isn't an issue (I does not notice any flicker), but:

* If there is a Netlify issue, this should be reported with them
* If is is a issue with the Hugo site, it should be fixed in the docs site or in the Hugo theme

**Comment by aral** [comment]
Very interesting, different behaviour on different browsers:

* Worst: Safari on Mac (latest versions): Full page white flash between pages
* Moderate: Chrome on Mac (latest versions): Less flicker (background colours remain). Menu redraws/jumps every time.
* None: Firefox on Mac (latest versions): no flicker, page refresh is smooth.

@bep I’ll move this to docs, then. I thought I’d report it here first so you could triage. I’d consider this a major issue as it leads to a white flash during page navigation on latest Safari on Mac but it does need to be narrowed down.

**Comment by RealOrangeOne** [comment]
@aral take a look at my previous comment, what youre describing is highly unlikely to be an issue with Hugo. It's possibly some rendering issue with your machine, have you tried another separate machine?

If you still think this is a Hugo issue, and want some more input, i'd suggest [opening a thread on the forum](https://discourse.gohugo.io/)
