### ISSUE TITLE
.Page.Resources URL issues in multihost setup

### ISSUE THREAD

**Issue by biodranik** [gohugoio/hugo#4217]
For this folder structure and multihost (en and ru) configuration:
```
content/image.png
content/section/another_image.jpg
```
Images are placed to
```
docs/image.png
docs/section/another_image.jpg
```
Expectations:
```
docs/en/image.png
docs/en/section/another_image.jpg
docs/ru/image.png
docs/ru/section/another_image.jpg
```
Due to this bug files from .Resources are unusable in multihost configuration (didn't check for single host/multilanguage/DefaultContentLanguageInSubdir:true config).

**Comment by bep** [comment]
You are right about this issue, seems to be more than one slightly related issue. I will create another issue for the "other".
