### ISSUE TITLE
Syntax highlight - difference between fences and highlight shortcode

### ISSUE THREAD

**Issue by pgundlach** [gohugoio/hugo#4219]
This is somewhat related to #4179

These two code pieces show a different result:

    {{< highlight xml >}}
    <foo attr=" &lt; "></foo>
    {{< /highlight >}}

and

    ```xml
    <foo attr=" &lt; "></foo>
    ```

The first one gives 

    <foo attr=" &lt; "></foo>

The second one gives

    <foo attr=" < "></foo>

I would expect both to render the same (both should give the first result, see #4179).

My config.toml setting 

    pygmentsCodeFences = true
    pygmentsStyle = "manni"
    pygmentsUseClasses = true

Hugo Static Site Generator v0.32.2 darwin/amd64

**Comment by RealOrangeOne** [comment]
I believe this is to do with shortcodes escaping their content. Try using `<` rather than `%` in shortcode.

See https://gohugo.io/content-management/shortcodes/#readout

**Comment by pgundlach** [comment]
@RealOrangeOne The shortcode gives the correct result, the code fence is (IMO) wrong. I don't see how your suggestion would change the output of the code fence.

**Comment by bep** [comment]
No, this is the same as the last fix -- but unfortunately in a different code path.

**Comment by benolayinka** [comment]
I ended up here looking for a solution to this weird issue where

```
{{< highlight yaml >}}
{{< readfile path="/data/foo.yml" >}}
{{< /highlight >}}
```

Was turning some characters into character sequences. Turning the `readfile` shortcode into

`{{ .Get "path | readFile | safeHTML }}`

fixed it
