### ISSUE TITLE
v.0.32.2 fails to generate content, locates some of the static content in localized (en) dir.

### ISSUE THREAD

**Issue by aricart** [gohugoio/hugo#4221]
The new release breaks our build process. No useful warning/error is generated:

Using v0.31.1:

> malaga% hugo -v
> INFO 2018/01/04 11:09:54 Using config file: /Users/synadia/go/src/github.com/nats-io/nats-site/config.toml
> INFO 2018/01/04 11:09:54 syncing static files to /Users/synadia/go/src/github.com/nats-io/nats-site/public/
> WARN 2018/01/04 11:09:54 No translation bundle found for default language "en"
> WARN 2018/01/04 11:09:54 Translation func for language en not found, use default.
> WARN 2018/01/04 11:09:54 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
> Started building sites ...
> INFO 2018/01/04 11:09:54 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
> INFO 2018/01/04 11:09:54 Alias "/blog/page/1/index.html" translated to "blog/page/1/index.html"
> WARN 2018/01/04 11:09:54 [en] Unable to locate layout for "404": [404.html]
> 
> Built site for language en:
> 0 draft content
> 0 future content
> 0 expired content
> 140 regular pages created
> 168 other pages created
> 5 non-page files copied
> 6 paginator pages created
> 4 categories created
> 74 tags created
> total in 192 ms

Using the new release v0.32.2:
> malaga% hugo -v
> INFO 2018/01/04 11:10:34 Using config file: /Users/synadia/go/src/github.com/nats-io/nats-site/config.toml
> Building sites … INFO 2018/01/04 11:10:34 syncing static files to /Users/synadia/go/src/github.com/nats-io/nats-site/public/en
> WARN 2018/01/04 11:10:34 No translation bundle found for default language "en"
> WARN 2018/01/04 11:10:34 Translation func for language en not found, use default.
> WARN 2018/01/04 11:10:34 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
> INFO 2018/01/04 11:10:34 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
> WARN 2018/01/04 11:10:35 [en] Unable to locate layout for "404": [404.html]
> 
>                    | EN   
> +------------------+-----+
>   Pages            | 146  
>   Paginator pages  |   0  
>   Non-page files   |   5  
>   Static files     | 164  
>   Processed images |   0  
>   Aliases          |   0  
>   Sitemaps         |   1  
>   Cleaned          |   0
>
> Total in 176 ms

Any help/hint appreciated.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by bep** [comment]
OK, I have looked at this and there is a bug here somewhere.  There is some mysterious about the language code handling in your project. I haven't experienced it in any of my projects, but I will look at it later and fix it.

```bash
▶ hugo server --renderToDisk

                   | EN
+------------------+-----+
  Pages            | 146
  Paginator pages  |   0
  Non-page files   |   5
  Static files     | 164
  Processed images |   0
  Aliases          |   0
  Sitemaps         |   1
  Cleaned          |   0

Total in 396 ms
Watching for changes in /Users/bep/dev/dump/nats-site/{content,data,layouts,static}
Serving pages from /Users/bep/dev/dump/nats-site/public/en
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```
