### ISSUE TITLE
config.toml changes and hugo server -w

### ISSUE THREAD

**Issue by doocodes** [gohugoio/hugo#4224]
Since the latest release 0.32.2 I noticed following issue.

In the command line I entered:
`hugo server -w`

If I edit any file in the theme everything works as expected. On the other hand if I edit **config.toml** I can see following message in the console:

![untitled](https://user-images.githubusercontent.com/18548453/34596944-fe3408b0-f1e3-11e7-94bd-15e217ea30e1.png)

This is not a mistake. I receive identical output twice. If I edit config.toml again I receive error messages about non existing shortcodes files (my custom shortcodes).

![untitled1](https://user-images.githubusercontent.com/18548453/34597028-75432530-f1e4-11e7-985e-ecd5e4f49733.png)

If I try to build the website everything works OK.

I am using this HUGO build:
https://github.com/gohugoio/hugo/releases/download/v0.32.2/hugo_0.32.2_Windows-64bit.zip

Cheers,
Milos

**Comment by bep** [comment]
@doocodes I have added the missing "total in n ms", but I cannot reproduce your issue. I suspect it is connected to the double write events from the config.toml. We should handle that better, but I don't have time to fix that now. I may test this on Windows when I get my bigger disk on my MacBook installed.

Are you sure this isn't happening because you changed editor or something? Because there are big variations in which and how many file system events the different editors triggers.

**Comment by GrandNewbien** [comment]
Hey bep, I'm having a similar problem. Modifying config.toml doesn't correspond to an update on the site. Running hugo server -v I can see that it receives the WRITE event twice, just as you mentioned above. 

Is there anyway I can prevent this from happening? I'm not sure what changed but it seemed to be working fine a few days ago, but any changes to the config.toml don't update until I restart the hugo server.

**Comment by doocodes** [comment]
@bep No I did not change text editor. My primary IDE is PHPStorm and I use it for everything. By the way I'm currently use HUGO 0.41 and I don't face described issue anymore.

Cheers,
Milos

**Comment by eparadis** [comment]
I'm seeing this exact issue with v0.46 from brew on macOS High Sierra and the 64bit OSX 0.46 released binary.

**Comment by anthonyfok** [comment]
@eparadis Hi, could you please share with us which text editor you are using?  Thanks!

**Comment by anthonyfok** [comment]
Possibly related to #4701 and #4878

**Comment by bep** [comment]
Is this still an issue with 0.47?

**Comment by GrandNewbien** [comment]
Only 0.46 had that issue for me. Updating to anything past it works flawlessly.
