### ISSUE TITLE
v0.29..v0.30.2 Page sort

### ISSUE THREAD

**Issue by matthiasbeyer** [gohugoio/hugo#4227]
Hi,

I know there's a release `> 0.30.2`, but I'm using my distro packages and just want to make sure that this is either fixed in newer releases or at least noticed.

So I build one of my sites using hugo `0.29` ([here](https://imag-pim.org/), see page source). Today I crafted a new article (which shall be published on 8th). When running `hugo server` I noticed that the ordering was reverted (the article `Jan 1, 0001 Hello!` beeing on top, the latest article beeing on bottom of the list at `/blog/`).

You can build the site with the new article by checking out this: [http://git.imag-pim.org/imag-pim.org-matthias/log/?h=future](http://git.imag-pim.org/imag-pim.org-matthias/log/?h=future).

---

I will now go on and package the latest hugo release for my distro and if that does not work downgrade it to 0.29.

**Comment by bep** [comment]
See #3977

**Comment by matthiasbeyer** [comment]
@bep thanks for your fast reply, but I don't see how #3977 is a duplicate of this? I am not talking about future content, but about the ordering of the content! The ordering is reversed in `0.30.*` ... even if I rebuild the version of the site which was published already!

**Comment by bep** [comment]
Sorry for being a little short. Hugo has taken too much of my time lately. The longer explanation is this:

* Your theme orders the pages by `PublishDate` (which I guess fall back to title etc. if that date is not there)
* You don't have any publish date in your front matter
* In Hugo 0.30 we added some logic to make sure you will always have a `PublishDate` (we take the value from date)

So, now you have values for the field you sort on, and the sort order has changed. 

You need to take further question on the forum.

**Comment by matthiasbeyer** [comment]
For future reference: I fixed this issue locally by reversing the order my template lists entries with.
