### ISSUE TITLE
Feature request: Ability to override template type (list vs. single) in frontmatter

### ISSUE THREAD

**Issue by rhewitt22** [gohugoio/hugo#4230]
Sometimes I want a section index to act more like a regular content page rather than listing out the content from a section.  By default all `_index.md` files in the content directory use a `list.html` (or variant) template.

I would like to be able to override this behavior, likely by frontmatter parameter, such that `_index.md` can leverage a `single.html` template with the existing lookup order.

[More details on Discourse](https://discourse.gohugo.io/t/issues-rendering-site-with-v0-32-2/9862/8)

**Comment by bep** [comment]
See https://github.com/gohugoio/hugo/issues/3005
