### ISSUE TITLE
integration of bleve search with hugo

### ISSUE THREAD

**Issue by gedw99** [gohugoio/hugo#4237]
hugoidx is one but its not fully integrated.

i was wondering if there is interest in havign this. 
The big question is if you want it client side or server side. 
The other one is if its compile time or not. For a static site, you can do the indexing all at compile time, and include the inverted index into the actual site, and then access it using javascript.

Lots of consider and loking for what others have done and what worked or them.

**Comment by bep** [comment]
Bleve is great, but would not make sense to (somehow) integrate it with Hugo core. You can easily create data files that can be used to create indexes for Bleve and others.

If you want to discuss this further, I suggest:

https://discourse.gohugo.io/
