### ISSUE TITLE
Snap build for 0.32.3 is stuck

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4249]
It says it is going to build in 12 hours, which has been the status for the last few days:

```bash
in 12 hours (estimated)
```

**Comment by elopio** [comment]
Hey @bep, we had to disable the launchpad builders because of the spectre and meltdown bugs:
https://twitter.com/launchpadstatus/status/948688233029881856
The patches have just landed last night, so things should go back to normal very soon.
