### ISSUE TITLE
Permalink-like configuration for processed images

### ISSUE THREAD

**Issue by pawelurbanski** [gohugoio/hugo#4250]
It i possible to create permalink structure per content type or section. Would it be possible to create the way to specify where and how processed images are stored: globally and per content type or section?
For example:

[Imaging]
blog = "/images/:year/:month/::genfile"
default = "/images/:year/:month/:genfile
Processed files would be copied to the public folder under the path specified. Wordpress has the wp-content/uploads/ folder. Drupal has the Files or some other similar folder.
Such functionality would be helpful when setting cache headers or purging cache or coping image files to a seprate static hosting host.

**Comment by bep** [comment]
No, that is not how this is designed. They inherit their permalink setting from their page.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ if you want to discuss this further.
