### ISSUE TITLE
Slug variables in bundles are ignored

### ISSUE THREAD

**Issue by simonszu** [gohugoio/hugo#4255]
During re-organizing my site to the new bundles feature, i recognized the following issue:

The post title has a german umlaut in it. It is: "Luftdaten: MQTT-Gateway für den Feinstaubsensor". (Notice the ü). I created it as a bundle with two images. After commiting and pushing, this results in two folders:

- a folder called "luftdaten-mqtt-gateway-für-den-feinstaubsensor" with an index.html where the post text is written
- a folder called "luftdaten-mqtt-gateway-f%C3%BCr-den-feinstaubsensor" where all the images associated with the post are stored

Of course, the image paths in the index.html are broken and the images could not be found. 

I tried a workaround with a custom slug variable in the front matter, and added `slug = "feinstaub-mqtt"` to the post's front matter. However, it seems that this slug setting is ignored. There is no according folder created, but only the above two folders. 

I am using hugo 0.32.3 installed from the deb-Package. 

<hr>

**EDIT:** It seems that the issue with non-ASCII-chars is already known and that it got fixed in 0.32.4. However, the custom slug variable in the front matter of the post is still ignored.

**Comment by bep** [comment]
Can you edit you post and remove the strike-throughs. I don't understand what you mean.

**Comment by simonszu** [comment]
Yes, of course. Sorry.

**Comment by bep** [comment]
>However, it seems that this slug setting is ignored.

What are your permalink settings?

**Comment by simonszu** [comment]
My permalink setting is 
```
[permalinks]
  post = "/:year/:month/:title/"
```

I changed it accordingly, and now it works.
