### ISSUE TITLE
Proposal: asset function

### ISSUE THREAD

**Issue by nfisher** [gohugoio/hugo#4268]
It would be nice if there were a function that managed external assets providing the following signature;

```
script  DEST INC_SRI IMMUTABLE [ATTR] SRC...
style  DEST INC_SRI IMMUTABLE [ATTR] SRC...
```
The arguments are as follows;

- **DEST** (string) - base URL relative path.
- **INC_SRI** (boolean) - adds integrity tag with SHA256 sum.
- **IMMUTABLE** (boolean) - adds BASE62(SHA256 sum) as a postfix of the filename prior to the extension.
- **ATTR** - is a map which adds html additional attributes to the tag.
- **SRC** ([]string) - source path for the file(s), multiple will be concatenated.

This would enable the following things;

1. Allow the use of Content-Security-Policy: require-sri-for script style.
2. Fix issues with CDN's that don't cache resources with query params.
3. Allow the assets to be referenced as immutable or at least a very long cache time.
4. Simplify cache busting with one function (e.g. no need to use sha256 and readFile).
5. For pages that are cached the static assets can be made permanently available.

Example Scenario

```Gherkin
Given the user provides the following template sequence:
  {{ script "/js/postman.js", true, true, "static/js/bootstrap.js" }}
When it is processed
Then it should copy the source to the destination folder as named
And it should generate the following tag in the HTML:
  <script type="text/javascript" 
               src="/js/postman-3PVPh0f01T2hWni0XcU5x0jU8Kqdgb64v1avoKGC4G2O.js" 
               integrity="sha256-3vw5dArBhZ2OJ4XtRzIIQJYn6Hrd1fePLeqsuToS1R0="></script>
```

See #621 for discussion on cache-busting.

**Comment by moorereason** [comment]
Please don't put multiple issues into one GH issue.  Rewrite this issue to focus on SRI.

The cache busting enhancement request is #621.
