### ISSUE TITLE
Proposal: Add filepath template namespace

### ISSUE THREAD

**Issue by moorereason** [gohugoio/hugo#4269]
### Proposal

Provide a `filepath` template namespace for handling local system paths.

### Rationale

Right now it's impossible to write cross-platform templates when dealing with local file paths.

I offered PR #4168, but it was rejected.  I'll list below each func I attempted to add in that PR, and we can discuss them.  See that PR for more implementation details.

### Proposed Funcs

All of these are essentially from the [Go stdlib](https://golang.org/pkg/path/filepath/) (not everything from the stdlib is included).

**FromSlash**
See #3187.  (Cc: @robsonsobral)

**ToSlash**
See #2394. (Cc: @glennsarti)

**Base**, **Dir**, **Ext**, & **Split**
All trivial convenience functions.  Added to save users the time of having to implement with template string funcs.

**Separator**
Trivial convenience function.  A must if we don't provide Base, Dir, and Split.

**Clean**
Probably the most complicated to explain in the docs, and the first one I'd cut if we don't want to support it.  No known use case.  I just like clean paths.  :smiley:

**Comment by bep** [comment]
>Right now it's impossible to write cross-platform templates when dealing with local file paths.

I do that all the time. So the above statement cannot be true. I assume you talk about some corner cases?

**Comment by moorereason** [comment]
See issues referenced above.  If those are not accurate, we can close them and this issue.

**Comment by bep** [comment]
My point about asking these questions is that the problems are raised from people using what I would call "accidental APIs", e.g. the really big File that I guess was meant as internal, but Steve somehow started all methods with Uppercase as default.  Which we now must document and support. But continuing this path is not something I'm willing to go (I'm not going to answer questions explaining how to use the file separator on Windows). 

Right now there are 2 persons asking for something like this. 2 persons is not enough interest to add significant work to this project. 

I'm going to let this proposal live for a little, then close it if the above does not change.

We should rather strive to find less low-level solutions to the listed problems.

**Comment by moorereason** [comment]
Documenting a particular use case from https://github.com/devopsdays/devopsdays-web/commit/383daea480c329d893d40358c864618d4c8c7f8f and #2394:

Given files:
```none
content/events/2015-amsterdam/foo.md
data/events/2015-amsterdam.yml
```

Given site config:
```toml
# Set to "/" on *nix and Mac, "\\" on Windows
# Refer to https://github.com/spf13/hugo/issues/2394 for more information
PathSeperator = "/"
```

Existing template usage is:
```
{{ $path := split .Page.Source.File.Path .Site.Params.PathSeperator }}
{{ $event_slug := index $path 1 }}
{{ $e :=  (index .Page.Site.Data.events $event_slug) }}
...
```

The Hugo issue related to this use case asks for a `ToSlash` function, but I would probably use `Dir` and `Base` if it were available:

```
{{ $path := .Page.Source.File.Path | filepath.Dir | filepath.Base }}
```

So essentially, they are using the parent directory name as a key for data lookups.

/cc @mattstratton

**Comment by mattstratton** [comment]
This problem went away a while ago. I think we fixed it in our own code - we don’t have the parameter in use anymore.

**Comment by moorereason** [comment]
@mattstratton,
Thanks for the update.  This is very helpful!  It looks like you're now working with the permalink:

```
{{- $e := (index $.Site.Data.events (index (split ($.Page.Permalink | relURL) "/") 2)) -}}
```
One less argument for adding a `filepath` namespace.
