### ISSUE TITLE
{{ .Content }} in <li></li> generates useless newline that's hard (maby impossible) to remove 

### ISSUE THREAD

**Issue by Asqiir** [gohugoio/hugo#4271]
I made:
`<li>{{ .Content }}</li>`
After the dot, and before the text is an empty newline which I can't remove.
This behavior is caused on the <p>-tag which surrounds `.Content` automatically and which I can't remove.
I propose some function like: | noPinFirstParagraph which makes the first text paragraph not be surrounded by p-tags.
(The function should have a nicer name, of course)

**Comment by bep** [comment]
There is a trim function which you could use, I guess, but you need to ask further questions on https://discourse.gohugo.io/. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by bep** [comment]
Also see

https://gohugo.io/templates/introduction/#whitespace
