### ISSUE TITLE
Linux binary shows current data date and not build date

### ISSUE THREAD

**Issue by it-gro** [gohugoio/hugo#4272]
I'm on debian and updated hugo just now.
```
$ cp /usr/local/bin/hugo  .
$ hugo version
Hugo Static Site Generator v0.32.4 linux/amd64 BuildDate: 2018-01-13T15:47:10+01:00
```

```
$ cp -a /usr/local/bin/hugo  .
$ hugo version
Hugo Static Site Generator v0.32.4 linux/amd64 BuildDate: 2018-01-11T09:58:37+01:00
```
I realize that BuildDate is just showing the file date of the executable - not the real BuildDate.
So it's more a **FileDate** - not BuildDate.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by bep** [comment]
Where did you get that binary?

**Comment by it-gro** [comment]
https://github.com/gohugoio/hugo/releases/download/v0.32.4/hugo_0.32.4_Linux-64bit.deb
installed it.
=> /usr/local/bin/hugo 
I copied it:
`cp /usr/local/bin/hugo .`
=> ./hugo is a copy of the binary with an new timestamp.
`$ hugo version
`
shows BuildDate but it is NOT the BuildDate, it's the FileDate 

I fixed my copy:
`cp -a /usr/local/bin/hugo  .`

But we can reproduce with:
```
$ /usr/local/bin/hugo version
Hugo Static Site Generator v0.32.4 linux/amd64 BuildDate: 2018-01-11T09:58:37+01:00
$ sudo touch /usr/local/bin/hugo version
$ /usr/local/bin/hugo version
Hugo Static Site Generator v0.32.4 linux/amd64 BuildDate: 2018-01-13T17:09:56+01:00
```
So it is not the BuildDate...

**Comment by bep** [comment]
That is curious. I just tested the macOS binary and that shows the build date. I will have a look at it.

**Comment by it-gro** [comment]
https://github.com/gohugoio/hugo/blob/master/commands/version.go
```
// setBuildDate checks the ModTime of the Hugo executable and returns it as a
// formatted string.  This assumes that the executable name is Hugo, if it does
...
// osext is used for cross-platform.
func setBuildDate() {

```
Looks like this is done intentionally (BuildDate := ModTime).
For me it was kind of misleading  - FileDate would have been clear..

**Comment by bep** [comment]
>Looks like this is done intentionally (BuildDate := ModTime).

OK, I see what is going on there ... this obviously works on macOS, but not on Linux. That is some old code someone put there, which does not make much sense. I will fix.

**Comment by it-gro** [comment]
Thx, i was just curious an tried in a windows 7 VM.
https://github.com/gohugoio/hugo/releases/download/v0.32.4/hugo_0.32.4_Windows-64bit.zip
unzipped using default windows 7 extract (and tried with 7zip as well).
```
C:\Users\MyAdmin>c:\apps\bin\hugo.exe version
Hugo Static Site Generator v0.32.4 windows/amd64 BuildDate: 2018-01-13T21:22:58+01:00

```
So hugo.exe has the timestamp when I extraced the zip file.
And this timestamp is shown as BuildDate.

=> 
this is not a linux only issue, but **linux and windows**.
(i just wanted to share this info - unfortunately I'm no yet a go programmer :-/ so I can't provide a PL)

**Comment by bep** [comment]
@it-gro thanks, appreciate the testing. The fix is easy and I will get it into the 0.33 release.

**Comment by it-gro** [comment]
Just as an information. The BuildDate is no longer showing up on Windows 7 (64) and on linux (debian 64):

```
C:\Users\MyAdmin\Downloads\hugo_0.33_Windows-64bit>.\hugo.exe env
Hugo Static Site Generator v0.33 windows/amd64 BuildDate:
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.9.2"
```

```
$ ./hugo env
Hugo Static Site Generator v0.33 linux/amd64 BuildDate: 
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.9.2"
```

Downloaded from https://github.com/gohugoio/hugo/releases
hugo_0.33_Linux-64bit.tar.gz
hugo_0.33_Windows-64bit.zip

I'm not sure if this was the intention.

**Comment by bep** [comment]
>I'm not sure if this was the intention.

The intention was to get rid of the "current date". But I expected you to get _a date_, but I will create another issue for that.
