### ISSUE TITLE
More flexible HTTP header configuration for builtin server

### ISSUE THREAD

**Issue by lrvdijk** [gohugoio/hugo#4277]
Hi all,

I would very much appreciate the ability to control the HTTP headers sent by the Hugo builtin webserver. 

Use case: I'm setting up a personal data science blog, and would like to include some data visualisations made in Javascript in some of my posts. The datasets I want to visualise are often in the form of a gzipped JSON file. I would like to serve these files with the following HTTP headers:

```
Content-Encoding: gzip
Content-Type: application/json
```

Using these headers, when I do an AJAX request with for example jQuery, the browser will handle the gzip decompression and jQuery will handle the JSON parsing. This is easy to configure in a production webserver like nginx, but I would like to use the same configuration in the hugo webserver, because then I can check if the visualisation works when I'm writing the story.

My suggestion would be adding a section to config.toml, where you can modify the HTTP headers sent for certain paths (using wildcards). Please let me know your thoughts, and I am willing to try to code it myself.

Thanks in advance.

**Comment by lrvdijk** [comment]
Relevant thread: https://discourse.gohugo.io/t/multiple-suffixes-for-media-types/9820/5

**Comment by bep** [comment]
This is a development server, and I'm hesitant to add more logic to it. If you somehow can document that this is something wanted by many, we can consider it, but it feels out-of-scope.

**Comment by cseeger-epages** [comment]
i do have the same problem. I want to test a form send to a HTTP POST API endpoint written in golang but since the endpoint is not in the same origin policy it does not work. I need to set the Header to test it and it would be nice to have the ability to add custom headers to the development server.

**Comment by tdelmas** [comment]
It may also be useful with CSP: without the CSP headers things seams to work but once in production they doesn't.

**Comment by seanburlington** [comment]
According to docs this is now possible 

https://gohugo.io/getting-started/configuration/#configure-server
