### ISSUE TITLE
Add language selection to index.html of a multilingual site

### ISSUE THREAD

**Issue by Siassei** [gohugoio/hugo#4279]
Very powerfull feature is missing in hugo. I open the issue based on forum topic
https://discourse.gohugo.io/t/add-language-selection-to-index-html-of-a-multilingual-site/9070

Currently I replace the hugo `index.html` with a own written file. The solution of the forum topic is
```html
<!DOCTYPE html>
<html lang="{{$.Site.Language}}">
  <head>
    <title>xxxx</title>

    <!-- languages - Google way: <link rel="alternate" hreflang="es" href="http://es.example.com/" /> -->
    {{ if .Site.IsMultiLingual }}
    {{ range .Site.Languages }}
    {{ if ne . $.Site.Language }}
    <link rel="alternate" hreflang="{{.}}" href="{{ $.Site.BaseURL }}{{.}}/" />
    {{ end }}
    {{ end }}
    {{ end }}
    <link rel="alternate" hreflang="x-default" href="{{ $.Site.BaseURL }}" />

    <meta name="robots" content="noindex">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="refresh" content="0; url=https://xxx/en" />
  </head>
</html>
```
, need additional resarch, but should work in most browsers.

I had set the `defaultContentLanguageInSubdir = true` option in the config of the hugo project. So, I replace the `/index.html` with
```html
<!DOCTYPE html>
<html>
  <head>
    <title>... what ever ...</title>

    <meta name="robots" content="noindex">
    <meta charset="utf-8" />
    <noscript>
      <meta http-equiv="refresh" content="0;url=en/index.html">
      <!-- languages - Google way: <link rel="alternate" hreflang="es" href="http://es.example.com/" /> -->
      {{ if .Site.IsMultiLingual }}
      {{ range .Site.Languages }}
      {{ if ne . $.Site.Language }}
      <link rel="alternate" hreflang="{{.}}" href="{{ $.Site.BaseURL }}{{.}}/" />
      {{ end }}
      {{ end }}
      {{ end }}
      <link rel="alternate" hreflang="x-default" href="{{ $.Site.BaseURL }}" />
    </noscript>

    <script>
      var getFirstBrowserLanguage = function () {
      	var nav = window.navigator,
      	browserLanguagePropertyKeys = ['language', 'browserLanguage', 'systemLanguage', 'userLanguage'],
      	i,
      	language;

      	// support for HTML 5.1 "navigator.languages"
      	if (Array.isArray(nav.languages)) {
      		for (i = 0; i < nav.languages.length; i++) {
      			language = nav.languages[i];
      			if (language && language.length) {
      				return language;
      			}
      		}
      	}

      	// support for other well known properties in browsers
      	for (i = 0; i < browserLanguagePropertyKeys.length; i++) {
      		language = nav[browserLanguagePropertyKeys[i]];
      		if (language && language.length) {
      			return language;
      		}
      	}
      	return 'en';
      };

      var $pref_lang = getFirstBrowserLanguage ();
      window.location.replace($pref_lang.substring(0, 2) + "/")
    </script>
  </head>
<body>

</body>
</html>
```
**Note:** Two possible solutions are shown. A third way should be to tell the webserver, over the .htaccess, where the languages are placed and the webserver ask the browser client, which language the client are prefer. (I'm not 100% sure, if that is possible)

**Question:** Is there a way to manipulate the `/index.html` directly in an theme? My workaround is a manuall replacement in an upload script.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by nanmu42** [comment]
Met this too.

You may create an `alias.html` in your template's `layout` directory.

Ref: https://github.com/gohugoio/hugo/blob/70a1aa345b95bcf325f19c6e7184bcd6f885e454/docs/content/en/content-management/urls.md#customize

The rendering context for `alias.html` seems to be quite lacking, only `Permalink` is working in my case, but still it is better than nothing.
