### ISSUE TITLE
Syntax Highlighting code that ends with comment results in incorrect highlighting

### ISSUE THREAD

**Issue by halogenica** [gohugoio/hugo#4282]
The following code block ends with a comment, and that comment incorrectly receives an err class. This occurs with both Chroma and Pygments, with both code fences and the highlight shortcode, with and without ```pygmentsUseClasses = true```, and with and without line numbers. It did not occur with HLJS. It is always the last comment regardless of the number of previous lines, and all other comments are highlighted correctly. 
```
{{< highlight javascript >}}
sum = parseInt(num1) + parseInt(num2) // "+" means "add"
alert("Sum = " + sum)  // "+" means combine into a string
{{</ highlight >}}
```
Changing highlight syntax to c++ (instead of javascript) results in the last comment being highlighted as code and not as a comment, but mysteriously without the err class. It has the same conditions as the example above.

<img width="466" alt="syntaxhighlightcomment" src="https://user-images.githubusercontent.com/70501/34975633-9b1b33c2-fa47-11e7-9de9-b72ae4080376.png">

This bug may be related to some previously reported bugs, but note that this is not isolated to Chroma as these other bugs may suggest: https://github.com/gohugoio/hugo/issues/3917, https://github.com/alecthomas/chroma/issues/42

**Comment by bep** [comment]
You need to raise this issue at Chroma and/or Pygments. We're not staffed to track upstream issues on this level.
