### ISSUE TITLE
hugo env: show content of PATH environment variable

### ISSUE THREAD

**Issue by it-gro** [gohugoio/hugo#4283]
We have:
hugo env  #  _Print Hugo version and environment info_

$ **hugo env**
```
Hugo Static Site Generator v0.32.4 linux/amd64 BuildDate: 2018-01-11T09:58:37+01:00
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.9.2"

```

We can see hugo errors like this
`ERROR 2018/01/16 11:12:59 asciidoctor / asciidoc not found in $PATH: Please install.
`

It would we cool, it the **hugo env** command would print the content of the PATH environment as well. Or maybe provide the content of $PATH in the error message above?

Motivation:
https://discourse.gohugo.io/t/asciidoctor-asciidoc-not-found-in-path/10017/3

**Comment by bep** [comment]
Just a quick question to all ... The `hugo env` is a useful command to ask people to run and list the output of. 

Are there any security or "secrecy" downsides to printing the PATH on a public forum?

**Comment by it-gro** [comment]
Hmm, good point. I didn't think about that. 
Now I've to say that it might be indeed unwanted by some users.


Turns out the discourse thread was because of the snap installation.

```
$ which asciidoctor 
/usr/bin/asciidoctor
$ /snap/bin/hugo server
Building sites … ERROR 2018/01/16 23:31:42 asciidoctor / asciidoc not found in $PATH: Please install.
```
while with  /usr/local/bin/hugo (from *.deb) we see no issue. 

I'm not sure if PATH gets changed by the snap environment or if there is a jail (AppArmor, ...) . Maybe a PATH dump would not have shown any issue here ( I expect /usr/bin/ to be in the PATH in the environment of  /snap/bin/hugo  - but I may be wrong)
`lrwxrwxrwx 1 root root 13 Jan 16 23:17 /snap/bin/hugo -> /usr/bin/snap*`

**ls -l $( which hugo )**
would have given me the hint 
(as stated in https://gohugo.io/getting-started/installing/#linux)
So I should have asked for this output ...

**Comment by it-gro** [comment]
In the thread:
@onedrawingperday
> Snap architecture has limitations. It is a separate file system within the main OS.
> So external applications cannot be launched from within the Hugo snap. 

$ /snap/bin/hugo env
Hugo Static Site Generator v0.32.4 linux/amd64 BuildDate: 2018-01-12T05:16:41+01:00
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.9.2"

$ /usr/local/bin/hugo env
Hugo Static Site Generator v0.32.4 linux/amd64 BuildDate: 2018-01-11T09:58:37+01:00
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.9.2"

Besides the BuildDate no difference. Maybe a hint could be given in the error message?

```
$ /snap/bin/hugo server
Building sites … ERROR 2018/01/16 23:18:48 asciidoctor / asciidoc not found in $PATH: Please install.
```
e.g._
...Please install. _(Note that this is not possible if hugo is installed via snap)._

Probably other "external" dependencies are affected as well (?)

**Comment by it-gro** [comment]
> I'm not sure if PATH gets changed by the snap environment or if there is a jail

OK, now I know:

```
# within my snap:
$ ls -la /usr/bin/a*
-rwxr-xr-x 1 root root 22696 Aug 31 23:30 /usr/bin/aa-enabled
-rwxr-xr-x 1 root root 18712 Jul 28  2011 /usr/bin/abootimg
-rwxr-xr-x 1 root root   362 Jul 28  2011 /usr/bin/abootimg-pack-initrd
-rwxr-xr-x 1 root root   272 Jul 28  2011 /usr/bin/abootimg-unpack-initrd
-rwxr-xr-x 1 root root 18888 Jun 14  2017 /usr/bin/addpart
-rwxr-xr-x 1 root root 31440 Mar  2  2017 /usr/bin/arch
lrwxrwxrwx 1 root root    21 Dec 18 16:09 /usr/bin/awk -> /etc/alternatives/awk
```

Outside I have:
```
$  ls -la /usr/bin/asciid*
-rwxr-xr-x 1 root root   310 Mär 13  2016 /usr/bin/asciidoctor
```

So its kind of an overlay.
Showing the PATH would **not** help here...
Sorry - I was just too fast with this one ...

**Comment by Hanzei** [comment]
@it-gro can this issue be closed?

**Comment by it-gro** [comment]
> can this issue be closed?
Since it would not have helped here (path within snap) and there may be security or "secrecy" downsides on printing the PATH on a public forum - I think this issue can be closed.
