### ISSUE TITLE
Content not rendering about/index.md

### ISSUE THREAD

**Issue by Rajan** [gohugoio/hugo#4284]
```
+++

comments = false
date = 2018-01-15
draft = false
showpagemeta = true
showcomments = true
slug = ""
tags = ["rajan", "about", "bio"]
title = "About Me"

+++

Test content here
```

Here's attached the screenshot.
<img width="754" alt="screen shot 2018-01-16 at 7 09 39 pm" src="https://user-images.githubusercontent.com/60307/34991774-d54d2d26-faf0-11e7-99dc-a068be0a90c6.png">

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
