### ISSUE TITLE
<style> and <script> tags in baseof.html break template

### ISSUE THREAD

**Issue by seaneking** [gohugoio/hugo#4286]
Okay, this is a strange one, and I'm not sure what's going on. I have a `baseof.html` template, which seems to break whenever I insert a `<style>` or `<script>` tag outside of a block. I've boiled it down to the following minimal repro:

### Working
baseof.html
```html
<html>
  <head></head>
  <body>
      {{ block "main" .}}{{ end }}
  </body>
</html>
```

single.html
```html
{{ define "main" }}
  <h1>{{ .Title }} </h1>
{{ end }}
```

### Broken
Changing `baseof.html` to either of the following results in Hugo exiting with the following error: `Failed to add template "_default/single.html" in path ... unexpected "&" in block clause`

baseof.html
```html
<html>
  <head>
    <style></style>
  </head>
  <body>
      {{ block "main" .}}{{ end }}
  </body>
</html>
```

baseof.html
```html
<html>
  <head></head>
  <body>
      {{ block "main" .}}{{ end }}
  </body>
  <script></script>
</html>
```

Am I going mad, or is this a known bug?

**Comment by RealOrangeOne** [comment]
Looking at the error message, the error is actually in your `single.html` template rather than `baseof.html`? I'm using both `<script />` and `<style />` tags in `baseof.html` with no issue at all. I assume there's something causing the issue that isn't in this example?

**Comment by seaneking** [comment]
Well, I don't know exactly how Go's template composition works, but I'm pretty sure by the time the error is thrown `baseof` and `single` have already been composed, so the error is actually stemming from `baseof`. The line number in the error supports that too. And, if I remove the content of the block in `single` the error is still thrown.

**Comment by seaneking** [comment]
I'm on Hugo 0.32 if it makes any difference. Also the content using that single template is one of the new 'page bundles' introduced in 0.32.

**Comment by seaneking** [comment]
Has anyone been able to repro this? Still a problem for me on 0.34... Can't figure out what else I can do to debug?

**Comment by RealOrangeOne** [comment]
@seaneking My site works fine with both these tags in. Have you got a repo with this issue in, or could you create a basic repo which has this issue so it'll be easier to diagnose

**Comment by seaneking** [comment]
Sure thing, will make a test repo tomorrow.

**Comment by seaneking** [comment]
Okay, I cloned my broken project to a new repo/folder to start trimming it down for a minimal repro, and somehow building it fresh fixed the error... can only assume there was some crusty artefact somewhere that was causing Hugo to spit the dummy. 

Apologies for the false alarm!
