### ISSUE TITLE
Shortcode inside taxonomy page can't access $.Page.Data variable

### ISSUE THREAD

**Issue by stefanoortisi** [gohugoio/hugo#4289]
I'm using a shortcode inside my taxonomy content file:
`content/categories/_index.md`

Inside the shortcode i need to get the list of my categories and I managed to do it accessing the page variable:
`$.Page.Data`

The weird thing is that the page variable is empty when I build the website, but it comes with data after the first site rebuild (for instance when I save any file after i run "hugo server"). 

Any ideas?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by stefanoortisi** [comment]
@bep I opened a question as you suggested but this is definetely a bug.
