### ISSUE TITLE
Make symbolic links respect the location of the original content files.

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#4291]
Following a topic at the forum about [Assigning content to multiple locations](https://discourse.gohugo.io/t/assign-content-to-multiple-sections/10060/2)

I tested using symbolic links of content files from a nested section into another one.

This works and the content files are rendered in the list page of the second nested section.

But the `.Permalink` context changes based on the second nested section. And unfortunately this results in duplicate pages.

Example
Original content is under:` /content/section/nested_section_1/1.md `
The permalink is: `/section/nested_section_1/1.md`

Symbolic Link of the above content file: ` /content/section/nested_section_2/1.md `
The permalink becomes: `/section/nested_section_2/1.md`

It would be awesome if Hugo got the permalink of a symbolic link from the location of the original content file.

This would give users a very simple way to list the same content under multiple sections and nested sections.

**EDIT**
Ah! I just discovered that it is possible to disable the generation of the duplicate page by setting the original `URL` in the front matter of the original content post. 

@bep If you think that this issue has merit and it's doable, it will be one less front matter parameter that the user will have to manually enter. But otherwise if you feel it's redundant then I'm very sorry for the noise.

**Comment by bep** [comment]
If you create a symbolic link **from inside /content to another place inside /content** you will get duplicate content. This is by design. I think you misunderstand the concept of symbolic links in this context.

**Comment by onedrawingperday** [comment]
Ok. But I managed to turn off duplication by setting the `URL` in the front matter.

Thank you!
