### ISSUE TITLE
Divide .Content in parts

### ISSUE THREAD

**Issue by mauriciogardini** [gohugoio/hugo#4292]
Supposing that this is a normal structure:

content/a.md
```
---
title: "A"
date: 2018-01-10T23:10:07-02:00
draft: true
---

This is a.md
```

layouts/_default/single.html

```
<html>
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  {{.Content}}
</body>
</html>
```

I wanted to achieve something like this in my single.html file:

```
<html>
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <div class="part1">
      {{.Content.part1}}
  </div>
  <div class="part2">
      {{.Content.part2}}
  </div>
</body>
</html>
```

The reason for doing that is that I wanted that the whole markup was in the single.html file, leaving the a.md file only with the post content, divided by "properties", without any markup.

I only see something similar to be possible to be achieved using front matter. Something like this:

content/a.md
```
---
title: "A"
date: 2018-01-10T23:10:07-02:00
draft: true
part1: "This is a really long content. This is a really long content. This is a really long content."
part2: "This is a really long content. This is a really long content. This is a really long content."
---

This is a.md
```

layouts/_default/single.html
```
<html>
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <div class="part1">
      {{.Params.part1}}
  </div>
  <div class="part2">
      {{.Params.part2}}
  </div>
</body>
</html>
```

The problem is that this is probably "overusing" the front matter. Despite that, in scenarios that, for example, part1 has multiple paragraphs, it would have HTML markup as well (in this case, `<p>`s), making the solution that I proposed not appropriate.

Is it possible to be achieved in Hugo (or something similar)? Or am I thinking in the wrong way?

**Comment by Feuerfuchs** [comment]
I had a similar situation when working on my website and found a solution using a shortcode that closes the current `<div>` and starts a new one, optionally with some changes using shortcode parameters.

The layout looks like this:

```
<section class="c-post__main">
    {{- if .Content -}}
        <div class="c-post__content t-content">
            {{ .Content }}
        </div>
    {{- end -}}
</section>
```

The shortcode (named "postSection"):

```
</div>
<div
    class="c-post__content t-content {{ with .Get 0 -}}
        {{- if eq . "wide" -}}
            c-post__content--wide
        {{- else if eq . "fullPad" -}}
            c-post__content--fullPad
        {{- else if eq . "full" -}}
            c-post__content--full
        {{- end -}}
    {{- end }}"
>
```

This is how I can use it in content files:

```
---
# some front matter
# nothing special to do here
---

At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

{{< postSection wide >}}

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,...
```

**Comment by carab** [comment]
Maybe you can use a Page resource from the recent page bundle feature ?

See #4264 as it shows how a content can be split in the main file and a resource.

**Comment by mauriciogardini** [comment]
@Feuerfuchs Interesting approach. It helps, but doesn't solve the specific problem that I have.

Dividing the content is only one part of the problem. The other part is putting the content parts on its appropriate places which, using your approach, I wouldn't be able to.

Anyway, for those who just need to divide the content, it's enough.

---

@carab I think that's the most appropriate approach. From what I understood, using that I would be able to structure my page as follows:

```
my_post
- index.md
- part1.md
- part2.md
- part3.md
```

This is closer to what I need. It isn't ideal, as the content of a single page is split in n files, but it works and it isn't abusing from Hugo's structure.

For this to be ideal (again, for my specific use-case), it would be needed some implementation on archetypes (probably). Supposing that a post in the format above is from a specific category, every time that I execute `hugo new category/my_post.md` (or something similar), Hugo should create a folder with the post name and the 4 files (`index.md`, `part1.md`, `part2.md` and `part3.md`) that composes a post from this category.

By the way, is Hugo new prepared to create pages with page resources? Just omitting the `.md` extension is enough for it to create a folder instead of a folder with the name that I passed instead of a file (sorry for asking, I am far from my work station and can't test this)?

---

The approach that I found some hours ago was placing some dividers in the content. Like this:

```
---
title: "A"
date: 2018-01-10T23:10:07-02:00
draft: true
---

This is a.md

||||||||||

This is also a.md

||||||||||

This is still a.md
```

Then, in the template file, it would do something like this:

```
{{ $content_parts := split .Content "||||||||||" }}

{{ range $cols }}
   <div class="part1">
   {{ index $cols 1 }}
   </div>
   <div class="part2">
   {{ index $cols 2 }}
   </div>
{{ end }}
```

With this approach, all the content is in the same file (`my_post.md`), so I can keep using `hugo new category/my_post.md` to create files of that specific category. Of course, there is some room for improvement, but so far this is the solution that is pleasing me the most.

Despite that, @carab 's suggestion is really interesting, and I think that I can achieve a mixed solution  for my problem (by using part of his solution and part of mine).

**Comment by kaushalmodi** [comment]
This discussion probably belongs on the Discourse forum.  There are multiple ways to do what the OP wants (even more than already discussed in this thread).

**Comment by kaushalmodi** [comment]
So this issue should be closed?

**Comment by mauriciogardini** [comment]
I'll close it, as it was inappropriate for it to be here and, besides that, my doubt was answered.

**Comment by kthornbloom** [comment]
@mauriciogardini - I realize this was awhile ago, but I'm heading down the same path right now. Your example with `split` is great, although it's just outputting literal code instead of rendering the elements properly. Did you get around this issue?
