### ISSUE TITLE
ZSH shell completion

### ISSUE THREAD

**Issue by cristim** [gohugoio/hugo#4296]
The `hugo gen autocomplete` command currently just supports bash, so as a ZSH user I would like this to also be available.

**Comment by bep** [comment]
I want that, too. 

But this has to be solved in Cobra, and there is already an issue for that there:

https://github.com/spf13/cobra/issues/107

**Comment by kyoh86** [comment]
[kingpin](https://github.com/alecthomas/kingpin#bashzsh-shell-completion) supports completion

FYI

**Comment by anthonyfok** [comment]
> spf13/cobra#107

@babysnakes has submitted a pull request spf13/cobra#646, and that appears to be nearing completion, perhaps as soon as this month (June 2018)!  /me feeling hopeful

**Comment by DavidLiedle** [comment]
+1 for zsh! Looks like it stalled on July 4 from the last comment on https://github.com/spf13/cobra/pull/646#issuecomment-402545088

**Comment by babysnakes** [comment]
As noted in [cobra#646](url
https://github.com/spf13/cobra/pull/646), I couldn't work on it on the last couple of months. I'll return to working on it next week.

Sorry if you were waiting for it.
