### ISSUE TITLE
Add .Resources.ByMatch and GetByMatch

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#4301]
Add to Resources a method for retrieving resources using a matching pattern (images/*.jpg)
Uses the same value to match against as the existing ByPrefix

**Comment by bep** [comment]
We should also add GetByMatch fro completeness.

**Comment by bep** [comment]
I will add those to a patch release ... But I will probably wait to see if more bugs "happens" until I go that route. The implementation should be trivial.
