### ISSUE TITLE
Content Not Rendering

### ISSUE THREAD

**Issue by n3integration** [gohugoio/hugo#4302]
I am trying to build a site using hugo that depends on the [material docs](https://themes.gohugo.io/material-docs/) theme. When I run `hugo` to generate the site, the index.html page is being rendered in the `public` directory, but no other files are generated.

#### Steps to Reproduce:
1. hugo new site test
1. cd test && git clone https://github.com/digitalcraftsman/hugo-material-docs.git themes/hugo-material-docs
1. cp themes/hugo-material-docs/exampleSite/config.toml config.toml
1. cp -r themes/hugo-material-docs/exampleSite/content/* content
1. hugo
1. find public -type f -name '*.html' | xargs ls -l

```
3cdf19e9b7e46c57a9bb43ff02199177feb55768 is the first bad commit
commit 3cdf19e9b7e46c57a9bb43ff02199177feb55768
Author: Bjørn Erik Pedersen <bjorn.erik.pedersen@gmail.com>
Date:   Mon Jul 24 09:00:23 2017 +0200

    :sparkles: Implement Page bundling and image handling

    This commit is not the smallest in Hugo's history.

    Some hightlights include:

    * Page bundles (for complete articles, keeping images and content together etc.).
    * Bundled images can be processed in as many versions/sizes as you need with the three methods `Resize`, `Fill` and `Fit`.
    * Processed images are cached inside `resources/_gen/images` (default) in your project.
    * Symbolic links (both files and dirs) are now allowed anywhere inside /content
    * A new table based build summary
    * The "Total in nn ms" now reports the total including the handling of the files inside /static. So if it now reports more than you're used to, it is just **more real** and probably faster than before (see below).

    A site building  benchmark run compared to `v0.31.1` shows that this should be slightly faster and use less memory:

    ```bash
    ▶ ./benchSite.sh "TOML,num_langs=.*,num_root_sections=5,num_pages=(500|1000),tags_per_page=5,shortcodes,render"

    benchmark                                                                                                         old ns/op     new ns/op     delta
    BenchmarkSiteBuilding/TOML,num_langs=1,num_root_sections=5,num_pages=500,tags_per_page=5,shortcodes,render-4      101785785     78067944      -23.30%
    BenchmarkSiteBuilding/TOML,num_langs=1,num_root_sections=5,num_pages=1000,tags_per_page=5,shortcodes,render-4     185481057     149159919     -19.58%
    BenchmarkSiteBuilding/TOML,num_langs=3,num_root_sections=5,num_pages=500,tags_per_page=5,shortcodes,render-4      103149918     85679409      -16.94%
    BenchmarkSiteBuilding/TOML,num_langs=3,num_root_sections=5,num_pages=1000,tags_per_page=5,shortcodes,render-4     203515478     169208775     -16.86%

    benchmark                                                                                                         old allocs     new allocs     delta
    BenchmarkSiteBuilding/TOML,num_langs=1,num_root_sections=5,num_pages=500,tags_per_page=5,shortcodes,render-4      532464         391539         -26.47%
    BenchmarkSiteBuilding/TOML,num_langs=1,num_root_sections=5,num_pages=1000,tags_per_page=5,shortcodes,render-4     1056549        772702         -26.87%
    BenchmarkSiteBuilding/TOML,num_langs=3,num_root_sections=5,num_pages=500,tags_per_page=5,shortcodes,render-4      555974         406630         -26.86%
    BenchmarkSiteBuilding/TOML,num_langs=3,num_root_sections=5,num_pages=1000,tags_per_page=5,shortcodes,render-4     1086545        789922         -27.30%

    benchmark                                                                                                         old bytes     new bytes     delta
    BenchmarkSiteBuilding/TOML,num_langs=1,num_root_sections=5,num_pages=500,tags_per_page=5,shortcodes,render-4      53243246      43598155      -18.12%
    BenchmarkSiteBuilding/TOML,num_langs=1,num_root_sections=5,num_pages=1000,tags_per_page=5,shortcodes,render-4     105811617     86087116      -18.64%
    BenchmarkSiteBuilding/TOML,num_langs=3,num_root_sections=5,num_pages=500,tags_per_page=5,shortcodes,render-4      54558852      44545097      -18.35%
    BenchmarkSiteBuilding/TOML,num_langs=3,num_root_sections=5,num_pages=1000,tags_per_page=5,shortcodes,render-4     106903858     86978413      -18.64%
    ```

    Fixes #3651
    Closes #3158
    Fixes #1014
    Closes #2021
    Fixes #1240
    Updates #3757

:100644 100644 4233d927872988c1e5074842e1cc605e05d79708 44f957d186d17ffb4a04182c380bbfb073d9ebc5 M	Gopkg.lock
:100644 100644 c8f1929743063446f11b417ead70964587a8fd01 cef7427cecea0aa7386d75bed2aff1df633929fd M	Gopkg.toml
:040000 040000 0d99b086cbabdfe78b9b5254fd76491bd4d03d54 7296825d8943e8acab4a031313acb2a14576e666 M	commands
:040000 040000 02c146affb039d241955c69b91b55543855faf15 1bc366bb51816551dbcf137adf3e8abae446942e M	create
:040000 040000 0a365e09814bdc4392a1477ca95c3d60b201972c 19edd2aa2f1215f77edcb05e9a5d75883d1ead4d M	deps
:040000 040000 4bd8e6b17b96777d5dd76bb380cca8f8382c7bce dfa5c902be52a5e0434574c3c1049a6e4104fb1c M	helpers
:040000 040000 10a2bf1f378b411debffdf26c7957f71840e2bc7 6a6a2e11bd65a197ad582a9c9146b05c90888725 M	hugolib
:040000 040000 5029cf64446ff0463c1493b911cdec20fb113df1 46a7da4e5ef6b5ebd3568ef488238f2565efe23a M	i18n
:000000 040000 0000000000000000000000000000000000000000 de49dd30d42617900bb0b4f7f546488eeaa6f63b A	resource
:040000 040000 736233c2b325eaceedf56480e3dce275cdd05a6f 1937ab677892c14a57a63a2cf4b338873d568d96 M	source
```

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by vassudanagunta** [comment]
See also #4259.

**Comment by n3integration** [comment]
@vassudanagunta  - Thanks for the pointer.

@bep - Thanks for the quick reply. The site renders in memory, but does not render to disk. Given the inconsistent behavior, it seems like it might be a bug. If there is an incompatibility with the theme, I was hoping that an error or warning would be displayed to indicate what went awry. 

Another detail worth mentioning is that the `Page` counter goes up or down depending on whether I add or remove files from the `content` directory. However, no additional pages are rendered.

**Comment by seqid** [comment]
same issue happened @n3integration do you have any workaround now?

**Comment by n3integration** [comment]
@seqid - I've rolled back to the commit before `3cdf19e9b7e46c57a9bb43ff02199177feb55768` and rebuilt hugo locally to work around the issue.

**Comment by seqid** [comment]
Thanks @n3integration , I don`t know how i fixed the issue.

i just changed below meta description format in the markdown file.
```
---
author: "Michael Henderson"
date: 2014-09-28
linktitle: Creating a New Theme
title: Creating a New Theme
highlight: true
---
```
to
```
+++
title = "(Hu)go Template Primer"
description = ""
tags = [
    "go",
    "golang",
    "templates",
    "themes",
    "development",
]
date = "2014-04-02"
categories = [
    "Development",
    "golang",
]
highlight = "true"
+++
```

and it will not skip render the markdown file anymore after rebuild.

**Comment by moloscripts** [comment]
@seqid. Thanks! worked for me. Curious to know why does one change the meta description format?
