### ISSUE TITLE
Can't override tags list and single pages

### ISSUE THREAD

**Issue by mauriciogardini** [gohugoio/hugo#4306]
I tried searching for it, but I can't seem to find the solution to override the default tags list and single pages.

The theme I'm using has the following files:

![screen shot 2018-01-20 at 19 29 34](https://user-images.githubusercontent.com/858434/35188144-b42fdf56-fe17-11e7-88be-fbbf83c1bb26.png)

Which files do I have to override in the content and/or in the layouts folder for the customization to work?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
