### ISSUE TITLE
Make ref and relref point to the "page I mean"

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4312]
With the introduction of page bundles, referring to a bundled page has become very verbose:

```
{{< ref "bundle-page/index.md" >}}
```

This proposal is to make the page extension and "index.??" part for bundled pages optional when using `ref` or `relref` shortcodes.

This proposal was originally made [here][1].  The same is copied here for convenience:

---
## Proposal for `ref`/`relref` to work for regular or bundle pages

- Make specifying the `.md` extension optional.

Would it be possible to make this work?

```
{{< ref "page" >}}
```

The idea is to make that **do the right thing** whether the user has:

```text
content/
└── page.md
```

or

```text
content/
└── page.html
```

or

```text
content/
└── page/
    └── index.md
```

or

```text
content/
└── posts/
    └── page.md
```

---

If there is ambiguity, then the current style can be used to make things clear:

```
{{< ref "page.md" >}}
```

or 

```
{{< ref "page.html" >}}
```

or

```
{{< ref "page/index.md" >}}
```

or

```
{{< ref "posts/page.md" >}}
```

This proposal would be backward compatible.. as mentioned above.. the current style can be used to resolve ambiguity.. but the proposed more concise form `{{< ref "page" >}}` should be good in most situations.. and then a user doesn't have to worry if the referenced page is a regular page or a bundle.

**The same proposal applies to `relref` shortcode too.**

---

Also copying @regisphilibert who originally started this discussion. 

[1]: https://discourse.gohugo.io/t/ref-relref-shortcodes-since-page-bundles/10102/3?u=kaushalmodi

**Comment by bep** [comment]
>This proposal is to make the page extension and "index.??" part for bundled pages optional when using ref or relref shortcodes.

Note that the extension is already optional, but I see what you mean by the rest.

**Comment by kaushalmodi** [comment]
> the extension is already optional. 

I didn't know that! And I also didn't try that for some reason. Thinking that extensions were always needed (based on the examples in [documentation][1]), I never used `ref`/`relref`. 

Thanks for that info and implementing the feature requested in this PR. I'll try it out soon. 

[1]: https://gohugo.io/content-management/cross-references/

**Comment by bep** [comment]
>I didn't know that! And I also didn't try that for some reason. 

It is a fairly new addition.
