### ISSUE TITLE
Syntax Highlighting problem with default monokai theme

### ISSUE THREAD

**Issue by laozhu** [gohugoio/hugo#4314]
1. hugo version 0.32.4
2. with `monokai` theme
3. javascript language

```markdown
```javascript
function foo(x = 1, y = 2) { // 这里给x, y设置了默认值
  console.log(x, y)
}
foo() // 1, 2
foo(3, 4) // 3, 4
```

But something went wrong with inline comments, preview below.

![image](https://user-images.githubusercontent.com/1212457/35254753-900da6ec-0026-11e8-918a-690965f34dad.png)

**Comment by bep** [comment]
You need to take this here: https://github.com/alecthomas/chroma/issues

**Comment by laozhu** [comment]
I have moved this issue to [alecthomas/chroma](https://github.com/alecthomas/chroma/issues/106)

**Comment by laozhu** [comment]
Fixed. https://github.com/alecthomas/chroma/issues/106
