### ISSUE TITLE
Strange message when installing on Debian 9

### ISSUE THREAD

**Issue by lobo-tuerto** [gohugoio/hugo#4324]
Hello,

I just installed Hugo in a brand new Debian 9.3 server and got this message:

```
$ sudo snap install hugo
2018-01-24T14:21:33-06:00 INFO snap "core" has bad plugs or slots:
core-support-plug (unknown interface)
hugo 0.34 from 'hugo-authors' installed
```

Seems like command is working since `hugo version` reports:

```
Hugo Static Site Generator v0.34 linux/amd64 BuildDate:
```

What's up with the "bad plugs or slots" message? can it cause any trouble?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by lobo-tuerto** [comment]
Done, thanks!
