### ISSUE TITLE
Error processing shortcode

### ISSUE THREAD

**Issue by saiarung27** [gohugoio/hugo#4325]
<img width="1440" alt="screen shot 2018-01-24 at 2 34 27 pm" src="https://user-images.githubusercontent.com/25520257/35361000-8902021e-0114-11e8-8e0a-d7b4fa4cf5b8.png">
I am getting this error i need help on this, i am using the latest version of hugo 0.34

**Comment by achekulaev** [comment]
I have the same issue that happens randomly. Looks like Hugo does not detect files on a disk properly at all. It is my first experience with Hugo and it does not work reliably for me at all.

Looks at this screenshot:

<img width="1330" alt="compile" src="https://user-images.githubusercontent.com/402007/35369622-ca1ddefc-0156-11e8-9ce0-0679cc05a3d1.png">

Funny that 10 seconds before that Hugo was able to find that file. Then I changed site title in `config.toml` and it suddenly stopped.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by achekulaev** [comment]
@bep it's a pretty obvious bug, not a troubleshooting.
