### ISSUE TITLE
relativeURLs does not apply on resource URLs

### ISSUE THREAD

**Issue by carab** [gohugoio/hugo#4326]
Hello,

Using the `.Permalink` of a resource, and having `relativeURLs = true` in my config, I found that the   resulting URL was not relative to the current context but instead was absolute.

I think it would be expected to be relative because the [docs says](https://gohugo.io/content-management/urls/#relative-urls) that it "will cause Hugo to rewrite all relative URLs to be relative to the current content."

Thank you !

Hugo version : 0.34
System : MacOS High Sierra

**Comment by bep** [comment]
>will cause Hugo to rewrite all relative URLs to be relative to the current content.

Sure, but `.Permalink` is by definition not relative.

**Comment by carab** [comment]
Sorry I mistyped : I was talking about the `.RelPermalink` function.

For example, calling a post resource .RelPermalink from the home will give:

```
/post/mypost/myimage.jpg
```

But I would expect it to be:

```
./post/mypost/myimage.jpg
```

Shouldn't it ?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
