### ISSUE TITLE
Update Google Analytics internal template to new style(gtag.js)

### ISSUE THREAD

**Issue by hanguokai** [gohugoio/hugo#4327]
Hello I found Google Analytics tracing code has updated from old analytics.js to gtag.js .

Some refers:
- https://support.google.com/analytics/answer/1008080
- https://developers.google.com/analytics/devguides/collection/gtagjs/
- https://developers.google.com/analytics/devguides/collection/gtagjs/migration

Look like they are the same for basic usage. I think Hugo's Google Analytics internal template can safely update to new style.

**Comment by wtip** [comment]
Google keeps sending me these reminder emails that I should upgrade my Analytics tracking code.
It would be great if we could get this upgraded.
![image](https://user-images.githubusercontent.com/3502082/102299974-f9105580-3f21-11eb-9bcb-5f607ce910f2.png)

**Comment by chalin** [comment]
I believe that this was addressed by #8287, and so can be closed.

**Comment by StefMa** [comment]
Since the [template is deprecated](https://github.com/gohugoio/hugo/issues/10899), this issue can be closed as obsolete, right?

**Comment by jmooring** [comment]
No longer relevant.
