### ISSUE TITLE
Support page bundles in content root

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4332]
Hello,

This issue was discovered by @RickCogley and [discussed here][1].

The problem is that if a "leaf" bundle (page bundle with `index.md`) directory is put directly under `content/`, it gets rendered using the Section or `list` layout.

This prevents one to convert root level pages like `content/about.md` to page bundle structure: `content/about/index.md`.

[1]: https://discourse.gohugo.io/t/steps-to-go-from-standalone-page-to-bundle-page/10206

**Comment by kaushalmodi** [comment]
In addition, what's surprising is that this behavior is inconsistent (atleast when using `hugo server`, using commit https://github.com/gohugoio/hugo/commit/6413559f7575e2653d76227a8037a7edbaae82aa.

At times, the browser refreshes and shows that page with `single` layout. If I modify the `index.md` file, the browser auto-reloads and could show the same using `list` layout. That's really odd.. while I can consistently make this happen, I cannot figure out what causes `single` layout to load vs `list` layout.

**Comment by kaushalmodi** [comment]
Test file: [Markdown][1] | [Hugo Output][2]

[1]: https://gitlab.com/kaushalmodi/hugo-sandbox/raw/master/content/leaf-bundle-directly-under-content/index.md
[2]: https://hugo-sandbox.netlify.com/leaf-bundle-directly-under-content/

**Comment by bep** [comment]
>In addition, what's surprising is that this behavior is inconsistent (

This a race: it is both a section and a page bundle. It is random who will win.

**Comment by kaushalmodi** [comment]
Thank you! I [confirm the fix][1].

[1]: https://hugo-sandbox.netlify.com/leaf-bundle-directly-under-content/
