### ISSUE TITLE
Permission error when using Hugo on encrypted drive

### ISSUE THREAD

**Issue by begincalendar** [gohugoio/hugo#4336]
I'm running Ubuntu 16.04, using a Veracrypt file-based encrypted drive and have installed Hugo via Snap.

If I clone this repository into a non-encrypted part of the file system (e.g. `/home/me/`) and run `hugo` inside the `examples/blog/` directory (of this repository), everything works as expected.

If I copy `examples/blog/` into a directory within the encrypted mounted drive (e.g. `/media/veracrypt1/`), then I get this error message when I try to run `hugo`:
```
Error: Unable to locate Config file. Perhaps you need to create a new site.
       Run `hugo help new` for details. (open /media/veracrypt1/blog/config.toml: permission denied)


```
...with an exit code: **255**.

I tried using `strace` when running `hugo`, but I can't see any calls to `open()` for the config file, which is odd to me (but then I'm not familiar with Golang).

**Comment by begincalendar** [comment]
Removed the `hugo` Snap, installed `hugo` via the latest `.deb` build and the problem is gone.

I recall having similar file system issues with an unrelated Snap, so I guess the issue lies there.

**Comment by DevAspirerKlaus** [comment]
Just commenting that what @begincalendar did worked for me too. Thanks dude!
