### ISSUE TITLE
--uglyURLs option stopped working in Hugo 0.33

### ISSUE THREAD

**Issue by jmalonzo** [gohugoio/hugo#4343]
Hi,

I've recently upgraded to the latest release and it seems that passing --uglyURLs="true" in the cli doesn't work anymore - i.e., the value of uglyURLs is always 'false'. My workaround atm is to add  `uglyURLs = true` to the config.

FYI this used to work in 0.30.x.

**Comment by bep** [comment]
We will check this out, eventually, but having all these as CLI flags was probably a mistake, as it clutters up the CLI API. They belong in the config, and if you really want to do this you can pass it as OS env vars:

```
HUGO_UGLYURLS=true hugo
```

**Comment by jmalonzo** [comment]
Thanks very much @bep!
