### ISSUE TITLE
AsciiDoctor: paths are relative

### ISSUE THREAD

**Issue by eiswind** [gohugoio/hugo#4344]
I tried Hugo today using some of my asciidoctor files.
I found that includes are very tricky to resolve in hugo, as the are resolved against the site basedir (which is not expected, it should be relative to the file). The same happens with images.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
