### ISSUE TITLE
Update internal twitter card etc. templates to (also) use images in .Resources

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4349]
This is the new order for Twitter card:

* Page.Params.images if set
* Image resources: images with name "*feature*" (priority), "*cover*", "*thumbnail*"
* Site.Params.images if set

The above should not break existing sites.

**Comment by bep** [comment]
https://www.paceup.com/en/blog/be-a-leader/cover_hu4ecce58dc1d90df771d3c7977e1985ac_211485_600x300_fill_q75_box_center.jpg

A Hugo site, uses "cover" for something similar.

**Comment by regisphilibert** [comment]
Yes `GetMatch "**featured*"`  is what I used for my portfolio to find the project's feature image. So I would go with this.
No garantee people won't have non image files called this way though...

**Comment by regisphilibert** [comment]
Wordpress has been using "thumbnail" for the past decade and it doesn't apply anymore

**Comment by bep** [comment]
>No garantee people won't have non image files called this way though...

Not sure how that could be a problem, as long as they don't name them "*.png" and similar. Thumbnail is something different.

**Comment by regisphilibert** [comment]
Oh and I would recommand "**feature*" rather than **featured*"
