### ISSUE TITLE
Test image resize with Caire

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4357]
If this is not too expensive in the performance department, this looks mighty cool:

https://github.com/esimov/caire

**Comment by bep** [comment]
It is interesting, but since even my sunset shot takes 2 minutes to resize with this, I think not suitable for Hugo prime time:

![image](https://user-images.githubusercontent.com/394382/35645280-a20b23dc-06cb-11e8-8725-58d03fb426c9.png)

**Comment by kaushalmodi** [comment]
I was just reading this reddit thread and learnt that the processing times by `caire` were too slow. [Ref][1]

[1]: https://www.reddit.com/r/programming/comments/7ua73q/caire_a_content_aware_image_resize_library_based/dtiz08o/

**Comment by bep** [comment]
Yea, and looking at the image above, I think it is suitable for just some special kind of images.
