### ISSUE TITLE
preserveTaxonomyNames = true doesn't work on tag names, first charakter is still capitalized

### ISSUE THREAD

**Issue by MoritzFago** [gohugoio/hugo#4364]
tags that start with a lower case letter (like `macOS`) get capitalized, even when `preserveTaxonomyNames = true` is set in the `config.toml`. (This is not about the urls, but about the displayed name, which is currently `MacOS`).

Hugo version:
`Hugo Static Site Generator v0.34 darwin/amd64 BuildDate:`
OS: macOS 10.13.3

**Comment by bep** [comment]
This is by design.

**Comment by MoritzFago** [comment]
What do you mean by `Title` i refer to the capitalized Tag titles that are generated by
```html
<div class="content container">
    <ul class="posts">
        {{ range .Data.Pages }}
        <li><a href="{{ .Permalink }}">{{ .Title }}</a> {{ if isset .Params "categories" }} &middot; {{ range .Params.categories }}<a class="label" href="{{ " /categories/ " | absURL }}{{ . | urlize }}">{{ . }}</a>{{ end }} {{ end }}</span>
            &middot; <time>{{ .Date.Format "02.01.2006" }}</time></li>
        {{ end }}
    </ul>
</div>
```
if `preserverTaxonomyNames = true` capitalizes the first character, that is indeed bad design and a bug.

**Comment by rdwatters** [comment]
@MoritzFago I think you'll have better feedback on this if you ask the same questions on the forum:

https://discourse.gohugo.io

**Comment by MoritzFago** [comment]
@bep is there any reason for this design choice? Because if there isn't it's a bug and belongs here. @rdwatters that depends, whether it's a bug or a feature, if the latter is true, then the forums are appropriate.

**Comment by MoritzFago** [comment]
> If this is a bug and you can still reproduce this error on the master branch, please reply with all of the information you have about it in order to keep the issue open.
I just retryed this with this version:`Hugo Static Site Generator v0.42-DEV darwin/amd64` and it is still this way.
> This is by design. Perhaps a bad one. 
I think this is true, because `preserveTaxonomyNames` doesn't actually preserves the names, it just changes how there're altered, not if.

**Comment by bep** [comment]
This is fixes.
