### ISSUE TITLE
~/go/bin/

### ISSUE THREAD

**Issue by cogitamus** [gohugoio/hugo#4374]
Linux debiantop 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux

~/go get -v github.com/gohugoio/hugo puts all stuff in ~/go/bin/ and not in ~/go/
created GOPATH=/home/foo/go/bin; see 'go help gopath' 
Results in:
~/go/bin/bin/ *
~/go/bin/pkg/*
~/go/bin/src/*

~/hugo version
bash: /home/foo/go/bin/hugo: No such file or directory
When I cut out the ~/go/bin/ directory it works.

~/hugo version
Hugo Static Site Generator v0.36-DEV linux/amd64 BuildDate:

Albeit without a actual date.

~/go get -v -u github.com/gohugoio/hugo

Results in adding:
~/go/bin/bin/ *
~/go/bin/pkg/*
~/go/bin/src/*

As the date doesn't show up I can't verify the is an update of ~/go/bin/hugo (shan't be)

Did work like a charm until recently .33-dev.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
