### ISSUE TITLE
Google Search console reports that URL's in sitemap.xml are invalid

### ISSUE THREAD

**Issue by olafghanizadeh** [gohugoio/hugo#4383]
I've added my site to Google Search console and it says that my sitemap is not valid because of invalid URL's. 

I'm using the default template for the sitemaps.

```
<url>
<loc>/root/relative/permalink/content</loc>
<lastmod>2018-01-10T21:27:02+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.5</priority>
</url>
```

**Comment by bep** [comment]
What Hugo version?

**Comment by olafghanizadeh** [comment]
0.34 on Netlify

**Comment by olafghanizadeh** [comment]
Could it be because the sitemap can't show root relative URL's for the content?

**Comment by chx** [comment]
Please share the problematic parts of the sitemap in a gist and link it here.

**Comment by olafghanizadeh** [comment]
The issue here is that for a sitemap to be valid in Google Search Console, the <loc>-url's needs to contain the full URL, including the protocol, i.e. they can't be root relative. 

Bep has a post on the forums on how to make Netlify inject the proper production URL on deploy to make this work correctly.

**Comment by chx** [comment]
For posterity, the discussion was at https://discourse.gohugo.io/t/google-search-console-reports-sitemap-xml-as-invalid/10474/12 and OP used `/` as the `baseUrl`. There's no Hugo bug in here.
