### ISSUE TITLE
Index parameter for posts collection

### ISSUE THREAD

**Issue by midzer** [gohugoio/hugo#4384]
Hi all,
right now I'm trying to port a medium heavy website from Jekyll to Hugo.

With Jekyll I use pre-processing of my posts with a custom plugin before actual rendering of site to assign an upcounting `index` number to each of my Posts. This info is needed for additional database work in a nodejs backend.

For Hugo is there a way to gather this info? I didn't find any info about it in docs or issues.

Cheers
midzer

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
