### ISSUE TITLE
Adding a “last updated” page with the latest changes [on doc]

### ISSUE THREAD

**Issue by divinerites** [gohugoio/hugo#4386]
This issue follows this thread : https://discourse.gohugo.io/t/adding-a-last-updated-page-with-the-latest-changes-on-doc/10412 and request from bep.

- It is difficult to know what are the latest improvements on the documentation.
- We could add a page : “latest changes” with the latest X changes on documentation.

So

- I posted on the above thread a code attempt for a shortcode
- @bep added the need for a  similar page with all TODO (via a new shortcode)
- He propose to create a new section (name?) with a simple list template?

**Comment by vassudanagunta** [comment]
This belongs in the [Hugo Docs repo](https://github.com/gohugoio/hugoDocs), not here.

**Comment by divinerites** [comment]
Oops. I change it. Sorry for the noise
