### ISSUE TITLE
Shortcode lexer fails with multi-line quoted strings

### ISSUE THREAD

**Issue by alexiosc** [gohugoio/hugo#4387]
The issue: even though the shortcode lexer is clearly capable of parsing multi-line shortcodes, the lexer for parsing quoted parameters (`lexShortcodeQuotedParamVal`) isn't. Currently, if it encounters a newline while looking for the closing double quote, it dies with an error message. It *seems* like this isn't the intention.

This makes it an issue when using shortcodes inline because editors may break the line when reformatting.

The code in question is here:

https://github.com/gohugoio/hugo/blob/e02ee7d6ad73f39239cabf08ad2d255559343149/hugolib/shortcodeparser.go#L418-L419

I've temporarily commented out the `\n` check and am testing (admittedly still small) site to see if anything else breaks:

```go
case r == eof: //, r == '\n':
```

Apologies if this breaks convention(s)—this is my first contribution on GitHub (I live under a rock).

**Comment by bep** [comment]
>This makes it an issue when using shortcodes inline because editors may break the line when reformatting.

Then you should get a better formatter.

I understand the issue, but this is not something we can fix.

* I have no idea of the side-effects
* You are the first one to ask about it
* So the cost/value makes it not worth it
