### ISSUE TITLE
Hugo server generates the site in multihost mode but breaks when used as a batch

### ISSUE THREAD

**Issue by pawelurbanski** [gohugoio/hugo#4392]
Following up on my previous issue filed as: #4378.
When I launch Hugo in a server mode the multilingual site in a multihost mode is generated. However when I want to generate the same site by using Hugo as a regular command it breaks giving the error that a baseURL is not set as a configuration option or a parameter at the commandline.
While @bep closed my previous issue, for it was not replicable at one of his sites, I cloned them of Github. They are multilingual, but not multihost, where each language does have its own baseURL.

**Comment by bep** [comment]
>Could you open a thread on https://discourse.gohugo.io/ and take it from there?

Did you follow my advice above?
