### ISSUE TITLE
Resources .Content not available in shortcodes

### ISSUE THREAD

**Issue by matthewdolman** [gohugoio/hugo#4403]
If I have a single .md fie as a resource to a page and I place this in a template:

```
{{ with .Resources }}
	{{ range . }}
		<p>{{ .Title }}</p>
		<div>{{ .Content }}</div>
	{{ end }}
{{ end }}
```

Both the title  and the content of the resource renders

However, if I place this in a shortcode:

```
{{ with $.Page.Resources }}
	{{ range . }}
		<p>{{ .Title }}</p>
		<div>{{ .Content }}</div>
	{{ end }}
{{ end }}
```

Then only the title will render, the content will not.

**Comment by bep** [comment]
This is a known limitation and there are other similar issue(s). You can ask further questions at https://discourse.gohugo.io/

**Comment by matthewdolman** [comment]
It would have been nice if this was in the docs, not sure if I can contribute to that in some way.

I found a workaround so will leave it here in case it is useful to somebody else

shortcode.html
```
{{ partial "partial.html" $.Page }}
```

partial.html
```
{{ with $.Page.Resources }}
	{{ range . }}
		<p>{{ .Title }}</p>
		<div>{{ .Content }}</div>
	{{ end }}
{{ end }}
```
