### ISSUE TITLE
public directory and output not generated

### ISSUE THREAD

**Issue by begueradj** [gohugoio/hugo#4407]
- I tried several themes, but I do not see the `public` folder generated even if my blog runs well.

- Even when I created the `public` folder manually and set `publishDir = "public"` in  `config.toml` file, I see no output files inside `public`.

What am I missing? I need the `public` folder with the output files there.

**Comment by RealOrangeOne** [comment]
Can you paste the logs of your blog building correctly? This sounds like there's an error in the build, and it's in fact not building correctly.

**Comment by begueradj** [comment]
No errors were output, but I have been told in an other forum that I had to run the option `--renderToDisk `.
That solved my problem. And thank you for the help.
