### ISSUE TITLE
markdown link definition does not support angle brackets

### ISSUE THREAD

**Issue by espinielli** [gohugoio/hugo#4408]
The following "classic" markdown [1]

    my [link][id]
    [id]: <http://example.com/>  "Optional Title Here"

fails to be properly converted in Hugo.

It results in

    <p>my <a href="http://example.com/&gt;" title="Optional Title Here">link</a></p>

rather than

    <p>my <a href="http://example.com/" title="Optional Title Here">link</a></p>

I report it here, but maybe it is a Blackfriday isse...

[1] https://daringfireball.net/projects/markdown/syntax#link

**Comment by moorereason** [comment]
Please open an issue in [Blackfriday](https://github.com/russross/blackfriday/issues).
