### ISSUE TITLE
Preserve color palette for PNG images

### ISSUE THREAD

**Issue by aitva** [gohugoio/hugo#4416]
Original post on [Discourse](https://discourse.gohugo.io/t/image-processing-resized-images-are-bigger-than-original/10586).

On my website, the PNG images resized with Hugo are bigger than the original.

For example, with an image called `apercu-slack.png`:
- the original is 1280x920px and weight 26ko
- the resized version is 1024x736px and weight 60ko

The original image:
![apercu-slack](https://user-images.githubusercontent.com/7271737/36309503-2c3d99ee-1325-11e8-83b3-9fbaa6a70c86.png)

The resized version:
![apercu-slack_hu44f56606ae01ef68f036029c27b3bc23_26297_1024x0_resize_box](https://user-images.githubusercontent.com/7271737/36309512-3b1845ae-1325-11e8-9bc3-3e2a8280a8b5.png)

**Comment by bep** [comment]
https://github.com/foobaz/lossypng maybe

**Comment by aitva** [comment]
I have made a repo to test the quality parameter of Golang's `image/png` library. I will try to add `imaging` and `lossypng`.

https://github.com/aitva/golang-png-encoding

**Comment by bep** [comment]
@aitva much appreciated.

**Comment by aitva** [comment]
Hi, I've spent some time toying with the `image` library and here is what I found:

- just encoding and decoding the PNG image through `go` increase its size
- the PNG image I am using come with a color palette, which greatly reduced its size
- passing the image through `imaging` removes its color palette, greatly increasing its size
- using the `lossypng` library does not help, the image quality is affected and the image size increase

The good news is that there is an easy fix ! We can reuse the original color palette on the reduced image.
Thus, we go back to something very close to the original size and the image is not altered:

- original image: 1280x920px and 26297 bytes
- original image through `go`: 1280x920px and 31368 bytes
- resized image: 1024x736px and 47339 bytes
- indexed image: 1024x736px and 23617 bytes

There are more details at https://github.com/aitva/golang-png-encoding

**Comment by bep** [comment]
Thanks for this, really appreciated.
