### ISSUE TITLE
livereload.js is not inserted into file when </body> is omitted

### ISSUE THREAD

**Issue by michaeleverson** [gohugoio/hugo#4420]
In hugo 0.36 `livereload.js` is not inserted into file when `</body>` is omitted, making live reload not work. 

In HTML, the body tag is often optional. Please see: [Google HTML CSS guide](https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags)

Thanks for taking a look.

**Comment by bep** [comment]
For livereload to work, the body tag is mandatory.

**Comment by celtic-coder** [comment]
As noted in https://gohugo.io/getting-started/usage/

> Hugo injects the LiveReload <script> before the closing <\/body> in your templates and will therefore not work if this tag is not present.
