### ISSUE TITLE
Hugo does not like hyphens in data filenames

### ISSUE THREAD

**Issue by RickCogley** [gohugoio/hugo#4421]
I was helping with this: https://discourse.gohugo.io/t/pull-specific-value-string-from-a-json-data-file/10598

... and found that I could not use a data file with a hyphen in the name. Not sure if this is a bug in Hugo or just "the way it is" and a matter of documentation.

**Comment by chx** [comment]
This is a duplicate of https://github.com/gohugoio/hugo/issues/1474
