### ISSUE TITLE
hugo 0.36 rendering single quotes in RSS

### ISSUE THREAD

**Issue by DarwinJS** [gohugoio/hugo#4422]
In RSS it seems hugo references a single quote as exactly `&amp;rsquo;` when I think it might need to be `&rsquo;`

**Comment by sainaen** [comment]
I’m not sure that’s right. `&rsquo;` is an HTML entity, it isn’t predefined in XML documents.

For example, [W3C’s Feed Validator](https://validator.w3.org/feed/#validate_by_input) fails with _XML parsing error: undefined entity_ when [given](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftmp.sainaen.com%2Fhugo-4422%2Frss-rsquo.xml) a feed with `&rsquo;` in the item’s description. (Same feed is [considered valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftmp.sainaen.com%2Fhugo-4422%2Frss.xml) with `&amp;rsquo;`.)
