### ISSUE TITLE
Saddle the buffalo inflect

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4430]
See https://github.com/markbates/inflect/issues/12

**Comment by QuLogic** [comment]
I don't know if you still want to fork it, but just pointing out that markbates/inflect was deprecated for gobuffalo/fflect.

**Comment by moorereason** [comment]
Envy dependency removed from flect: https://github.com/gobuffalo/flect/issues/16

**Comment by QuLogic** [comment]
API-wise, it appears to be missing the `Humanize` function currently.

**Comment by moorereason** [comment]
Thanks, @QuLogic.  I've opened an issue upstream: https://github.com/gobuffalo/flect/issues/19

**Comment by QuLogic** [comment]
It looks like, from the related PRs, that the API should be complete enough for hugo now. I have not looked at the actual code though.

**Comment by jmooring** [comment]
The `github.com/markbates/inflect` dependency was removed in v0.81.0.
