### ISSUE TITLE
Pipe through markdownify

### ISSUE THREAD

**Issue by jensamunch** [gohugoio/hugo#4431]
This has been shot down once but I'd like to try once more:

I have i18n content and in some places want to be able to do URLs on the front-page. We do this as follows:

```
reason4Text: "Blabla.<br>[Read more here](./why-pace/)"
<p class="pace-lead">{{ .Params.reason3Text | markdownify }}</p>
```

It seems to me that content should be separated from logic. But if 
```<br>[Read more here](./why-pace/)```
is removed from the markdown the builds start to fail:

```
ERROR 2018/02/20 20:47:53 Error while rendering "home" in "": template: /Users/jensmunch/Documents/www.paceup.com/layouts/index.html:5:5: executing "main" at <partial "frontpage.h...>: error calling partial: template: partials/frontpage.html:37:55: executing "partials/frontpage.html" at <markdownify>: wrong number of args for markdownify: want 1 got 0
```

What's the best practice here...it doesn't make sense that one should vet content for purity.

J

**Comment by bep** [comment]
>This has been shot down once but I'd like to try once more:

Not sure what "shot it down" before, but I will post my standard reply to these:

Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by jensamunch** [comment]
Ok trying here..
https://discourse.gohugo.io/t/markdownify/10658

I'm super confused.
