### ISSUE TITLE
releaser: Update to latest Goreleaser

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4432]
With native deb support.

**Comment by caarlos0** [comment]
if you need any help on this, let me know!

FWIW: I would like to start contributing to hugo, so if you want I can take care of this issue :D

**Comment by bep** [comment]
>so if you want I can take care of this issue :D

That would be great.  There are 2 things to do here:

1) Make sure the goreleaser config works with the new version
2) Adjust the Docker file.

As the Docker file currently lives in my GitHub repo, I think it is practical that I do that. But if you can confirm that you can create binaries with debs etc. working with the latest Goreleaser, that would be great.

**Comment by caarlos0** [comment]
Nice, I just opened both PRs :D

**Comment by Hanzei** [comment]
Both PRs got merged. Can this issue be closed?
