### ISSUE TITLE
Use of footnotes causes HTML5 validation error

### ISSUE THREAD

**Issue by jonbeebe** [gohugoio/hugo#4433]
If footnotes are used in Markdown (which is very common), Hugo renders the anchor with `rel="footnote"` and this causes an HTML5 validation error:

> Bad value footnote for attribute rel on element a: The string footnote is not a registered keyword.

Suggested fix is to use `data-rel` instead of `rel`. Any HTML that is generated directly by Hugo (and not from user-supplied templates) should always be valid.

**Comment by bep** [comment]
> HTML5 validation error

What validator are you using?

**Comment by jonbeebe** [comment]
@bep I am using the W3C Markup Validation Service: https://validator.w3.org/#validate_by_input

This page shows the valid values for `rel`:
http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions

**Comment by bep** [comment]
A fix for this was commited upstream just 3 days ago:

https://github.com/russross/blackfriday/commit/55d61fa8aa702f59229e6cff85793c22e580eaf5

I will verify that we're at latest BF.

**Comment by jonbeebe** [comment]
@bep Great thanks! Very fast response.
