### ISSUE TITLE
Template enhancement: Add function to return global dot

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#4437]
Let's say I want to create a partial that takes some argument, like a URL or an ID, but that also needs to the global dot, e.g. to get .Site.BaseURL or something. 

Right now, there are two ways to make this work. One, you can pass the partial a `dict` with the argument as one value and the global dot as another value. Two, you can write the argument into Scratch and pass the global dot into the partial.

However, if there were a template function that returns the global dot, you could just pass in the argument and in the partial use `dot` (or whatever it would be called) to get the global dot. This would make writing partials much easier.

**Comment by vassudanagunta** [comment]
I'm a Go newb and even more a Go Templates newb, but shouldn't we be using the mechanisms that Go templates provides rather than creating Hugo-flavored Go Templates? If this is a shortcoming in the Go template package, shouldn't it be addressed there?

**Comment by bep** [comment]
>However, if there were a template function that returns the global dot,

There is no such thing. We cannot fix this even if we wanted to. And if we could do it, it would fall into the "won't fix" category. You can discuss this further on the forum.
