### ISSUE TITLE
Images (Page Resources) are corrupted during build

### ISSUE THREAD

**Issue by crgeary** [gohugoio/hugo#4438]
There have been a few cases where images generated by Hugo are being corrupted while being cropped using `.Fill`. Here is an example of what happens:

![image-day-one_hu3f8d7a4289bf198ce47f3e44328215cb_112684_720x400_fill_q80_box_center](https://user-images.githubusercontent.com/3949335/36485721-abad3926-1714-11e8-9daf-9bfa67fa76e5.jpg)

Hugo v0.35

**Comment by bep** [comment]
What version of Hugo?

**Comment by crgeary** [comment]
Hugo v0.35

**Comment by bep** [comment]
See the release notes for Hugo 0.36.1. That should fix the issue.
