### ISSUE TITLE
insert function suggestion

### ISSUE THREAD

**Issue by baoang** [gohugoio/hugo#4439]
[reference link from Hugo's discussion forum](https://discourse.gohugo.io/t/is-there-any-command-that-can-rename-the-post-files-which-are-weird-encoded/10643?u=baoang)

Hello, hugoers,

May I suggest a new function called `insert` (or whatever you call it)?

I tried one of the hugo theme called [*red lounge*](https://themes.gohugo.io/redlounge/) whose instruction tells that I may [turn off the author display](https://github.com/tmaiaroto/hugo-redlounge#hiding--showing-things) by setting `noauthor = true` in the post md file. However, when handling quite a lot of md posts, it could be easy to have sth. like:

```bash
hugo insert "noauthor = true" filename.md -frontmatter
```
I don't know if this is feasible?

**Comment by baoang** [comment]
Also, I want to suggest a rename function. For example, my wordpress exported file name is something like **%e4%b8%ba%e4%bb%80%e4%b9%88%e8%bd.md**. It has correct Chinese title. If hugo command can rename such file name according to its front matter title (or something like **year-month-date-title.md**), that would save a lot of time.

**Comment by bep** [comment]
These are good suggestions, but they fall outside of the core responsibility of Hugo. They may be useful to some, but not enough to warrant the work. 

I suggest you discuss this at https://discourse.gohugo.io/  -- there may be workarounds for your issues.
