### ISSUE TITLE
Proposal: Have the figure shortcode always set the alt to something

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4441]
Hello,

The HTML5 validator gives this error if `alt` attribute is not specified for an `img` in `figure`.

The `hugo` `figure` shortcode generated HTML does not compulsorily set the `alt` attribute to a non-empty value.

### Error

> An img element must have an alt attribute, except under certain conditions. For details, consult [guidance on providing text alternatives for images][1].

> From line 266, column 33; to line 266, column 74

> `m><figure><img src=images/seconds-to-human-time.png></figu`

### Proposed solution

**>> Inside the `figure` shortcode, set the `alt` attribute value to that of `.Get "src"` if neither `alt` nor `caption` are set by the user. <<**

Here's the relevant snippet from modified `figure` shortcode (*indentation modified just to improve readability*):

```html
        <img src="{{ .Get "src" }}"
             alt="{{ if (or (.Get "alt") (.Get "caption")) }}
                       {{ with .Get "alt"}}
                           {{- . -}}
                       {{else}}
                           {{- .Get "caption" -}}
                       {{ end }}
                  {{ else }}
                       {{- .Get "src" -}}
                  {{ end }}"
             {{- with .Get "width" }}width="{{ . }}" {{ end -}}
             {{- with .Get "height" }}height="{{ . }}" {{ end -}}/>
```

Also copying @budparr @rdwatters for comments.

[1]: http://www.w3.org/wiki/HTML/Usage/TextAlternatives

**Comment by budparr** [comment]
Hmmm. "Decorative" images should definitely not have an alt tag, and if an image should have an alt tag (i.e. the image is information relevant to the page), then the alt tag should be informative, not extraneous or boilerplate language. So from what it sounds like this proposal may subvert the purpose of the alt tag. You could argue that there's information in source, but in my experience not usually.

**Comment by kaushalmodi** [comment]
My thinking was that, with this, the screen-readers would at least have something to read out, like the image file name, in the absence of a real `alt` attribute.

**Comment by kaushalmodi** [comment]
> the alt tag should be informative, not extraneous or boilerplate language.

That makes sense though. So I will close this proposal. 

Thanks for your input.

**Comment by mcluseau** [comment]
clearing empty `alt` induce the following Lighthouse error:

> Informative elements should aim for short, descriptive alternate text. Decorative elements can be ignored with an empty alt attribute.
