### ISSUE TITLE
Make ge, le etc. work with the  Hugo Version number

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#4443]
These days, we rely a lot on Netlify, Forestry which may or may not impose their own version of Hugo.

Plus not every Theme user may be using the last version of Hugo. Even though Themes must indicate a minversion, it would be interesting to be able to add new features like Page Bundle management, while still catering for users using older version of Hugo.

While it is hard to test if a feature is available for a current version, we need to test which version the project is using before calling `.Resources` or other.

The `.Hugo.Version` variable being a [semver](https://semver.org/) string it is not currently testable with common template func like `ge` or `le`

**Comment by bep** [comment]
The problem with any new functionality in this department is that you will have to wait until it's available.

**Comment by regisphilibert** [comment]
> The problem with any new functionality in this department is that you will have to wait until it's available.

Not sure to follow.

**Comment by bep** [comment]
My proposed fix is that you should be able do do:

```html
if get .Hugo.Version "0.35" 
```
But that will not work in Hugo 0.17 (default on Netlify).

**Comment by regisphilibert** [comment]
Yes of course, at least we'll have it post .37 or whenever you'll find time for this.

I don't think there is a better way to approach the issue though :/
