### ISSUE TITLE
GitInfo fails for some files

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4444]

**Comment by bep** [comment]
See https://discourse.gohugo.io/t/list-recently-edited-files/10552/15

**Comment by lufte** [comment]
I read the discourse thread and I understand that this is related to filenames containing spaces. I wanted to point out that I just encountered this issue in files with diacritics in their names.

**Comment by jmooring** [comment]
Unable to reproduce with v0.111.3, using [these examples](https://discourse.gohugo.io/t/list-recently-edited-files/10552/15?u=jmooring), regardless of whether Git configuration `core.quotepath` is `true` or `false`. Not sure when this was fixed. Example:

```text
git clone --single-branch -b hugo-github-issue-4444 https://github.com/jmooring/hugo-testing hugo-github-issue-4444
cd hugo-github-issue-4444
hugo server
```

A problem with file names that contain non-ASCII characters is covered in a separate issue:
<https://github.com/gohugoio/hugo/issues/9810>
