### ISSUE TITLE
A page is never generated

### ISSUE THREAD

**Issue by amoutiers** [gohugoio/hugo#4445]
Hi,

I've a page who is never generated, with hugo 0.31.1 it's ok but not since hugo 0.32
The page is at content/page/le-bateau/caracteristiques/index.md
<img width="295" alt="screenshot at feb 24 15-11-03" src="https://user-images.githubusercontent.com/2652014/36631250-f480fc20-1974-11e8-96ef-0db660df7219.png">
It seems hugo won't watch at this directory level

But if I start hugo with `hugo -w --cleanDestinationDir` command, the website is generated, after I edit the problematic markdown page, change something and save, the page is now generated

**Comment by moorereason** [comment]
Rename the file to `_index.md` after v0.32.  If you have any more questions, use the discussion forums (and start there next time, please).

**Comment by kaushalmodi** [comment]
@amoutiers This might be useful: https://discourse.gohugo.io/t/solved-after-update-0-29-0-35-some-pages-are-no-longer-generated/10443/5?u=kaushalmodi

But then please continue the support questions on the forum.

**Comment by amoutiers** [comment]
Ok, I'll post to the forum, but when renaming to _index.md it leads to others problems (the page disappear from lists ...)
I don't understand why the page is created with the -w arg and save and not without, the behaviour must be the same if there's no issue, and that’s not the case.
