### ISSUE TITLE
Adding tags to posts

### ISSUE THREAD

**Issue by angaunba** [gohugoio/hugo#4451]
Hi,

When adding a "yes" tag to post it's automatically converted to "true" and displayed that way. It does not change when tag is compound, e.g. "say yes".

It's a bug or it's a feature? :)

Cheers!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by angaunba** [comment]
It's not a question it's a irritating bug. Documentation does not say nothing about changing tags to something else that is written in post.

**Comment by angaunba** [comment]
For instance in my markdown I have "tags: [yes, stain, texture]" and when it render itself then "yes" is changed for "True".

**Comment by angaunba** [comment]
It also changes No to False...

**Comment by vassudanagunta** [comment]
It's not a bug. It's specified YAML behavior: http://yaml.org/type/bool.html.

If you want to avoid the implicit type conversion, you need to be explicit about your value's type, i.e. quote your strings.

**Comment by angaunba** [comment]
Thanks for information. Cheers!

**Comment by vassudanagunta** [comment]
np. But please in the future do as @bep said. Unless you know for sure something is a bug, use the forum.
