### ISSUE TITLE
Error: Error building site: imaging: unsupported image format

### ISSUE THREAD

**Issue by brunoamaral** [gohugoio/hugo#4455]
This came up when I upgraded from 0.36 to 0.37. 

If the Page Bundle contains an SVG file, Hugo does not finish the build and instead returns the error above.

I think this happens because imaging does not recognise SVGs as an image format. Other files, like PDF's are not affected.

**Comment by bep** [comment]
>This came up when I upgraded from 0.36 to 0.37.

Did you not get the same error in 0.36?

**Comment by brunoamaral** [comment]
No, even downgraded to 0.36.1 and it's working fine.

**Comment by bep** [comment]
OK, my mistake. The current workaround for 0.37 would be to rename that SVG file to *.xml or something.
