### ISSUE TITLE
Move internal shortcodes and templates into individual files

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4457]
Hello,

At the moment, all the internal shortcodes and templates are inlined in a single file: [`template_embedded.go`][1].

### Proposal

Move the shortcodes and templates from:

```
hugo/tpl/tplimpl/template_embedded.go
```

to:

```
- hugo/tpl/tplimpl/
    template_embedded.go
- hugo/tpl/tplimpl/internal_shortcodes/
    figure.html
    ..
- hugo/tpl/tplimpl/internal_templates/
    opengraph.html
    ..
```

The `template_embedded.go` will still be there, but now instead of inlining all the code in there, it will loop through all the files in `internal_shortcodes` and `internal_templates` and read those in. *That should be possible, right?*

### Advantages

- Easier to read internal shortcodes and templates as they can now be nicely indented.
- Supporting editors can now show the syntax highlighting appropriately for the Go templates.
- Clean git history specific to each shortcode and template.

### Disadvantages

??

[1]: https://github.com/gohugoio/hugo/blob/2e95ec6844bf65a25485bdc8e2638e45788f2dcf/tpl/tplimpl/template_embedded.go

**Comment by jhabdas** [comment]
Another advantage: Easier to unit test.

**Comment by bep** [comment]
>That should be possible, right?

Yes, but it sadly involves an extra "go generate" build step. But I think it's still worth it, so I will do it.

**Comment by kaushalmodi** [comment]
Awesome! Thank you!
