### ISSUE TITLE
References to .Site.Authors need to be cleaned up?

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4458]
Hello,

I had opened up https://discourse.gohugo.io/t/site-authors-not-implemented/10446 on Discourse for discussion, but haven't received any feedback.

The gist of the problem is that internal templates like `twitter_cards` and `opengraph` reference `.Site.Authors`, but no matter what I do, those variables do not get set.

While diving through the Hugo source code through my Go-unexperienced eyes, I realized that those variables are "declared" but never "assigned" (*not sure what the correct Go-lingo is for that*).

You can read the above linked Discourse thread for details and code snippet references.

**Comment by bep** [comment]
This duplicates https://github.com/gohugoio/hugo/issues/3088 and others.

In general, we have some features that does not exist in the documentation, which means "it doesn't exist".

**Comment by kaushalmodi** [comment]
> which means "it doesn't exist"

I can understand that, but then they also need to be cleaned up from the internal templates. I discovered this problem as I am debugging why the templates were not setting the `twitter:creator` meta tag.

That's very confusing.

**Comment by kaushalmodi** [comment]
@bep Would you consider reopening this? This is not a duplicate. This issue is about cleaning up the templates so that they don't refer to the non-functional variables. It plainly causes confusion. 

Once the Author proposal in your referred issue is implemented, the templates can be updated accordingly. 

At the moment, the templates are trying to access an unimplemented feature, which I categorize as a bug.

**Comment by XhmikosR** [comment]
Agreed, this is something I just hit myself.

**Comment by jmooring** [comment]
This issue continues to come up:
- <https://discourse.gohugo.io/t/site-author-usage/31459/3>
- <https://discourse.gohugo.io/t/site-authors-not-implemented/10446>
- <https://discourse.gohugo.io/t/site-authors-in-internal-templates/4181>

**Comment by danielfdickinson** [comment]
When .Site.Authors is a map (as the docs say) this works correctly (according to my testing). I'd argue the docs need to be updated with examples of how to properly configure .Site.Authors rather removing it's usage (I'm planning on doing this today / tomorrow).

Part of the problem is that even hugoBasicExample doesn't do this right (https://github.com/gohugoio/hugoBasicExample/issues/69) but I fix that in (https://github.com/gohugoio/hugoBasicExample/pull/70).

**Comment by jmooring** [comment]
> When .Site.Authors is a map (as the docs say) this works correctly (according to my testing). 

That's great! Please show me how to make it work!

**Comment by danielfdickinson** [comment]
I think I may be misunderstanding part of the this -- .Site.Authors allows to access the keys in the config.toml map which is all that I ever found in the docs. The other issue you mention in https://github.com/gohugoio/hugoDocs/issues/1370 is something I never found or noticed (and I think is a separate discussion/feature).

**Comment by jmooring** [comment]
> `.Site.Authors` allows to access the keys in the config.toml map

Again, please show me how to make this work.

**Comment by danielfdickinson** [comment]
Ok. Oh wait. I didn't notice the plural. .Site.Author is what I was referring to. Sorry for the confusion. I guess the templates really should use .Site.Author.authors (as described in https://discourse.gohugo.io/t/site-author-usage/31459/10), rather than .Site.Authors (and documentation updated).

**Comment by jmooring** [comment]
> I guess the templates really should use .Site.Author.authors ...

That's a separate issue. _This_ issue is about removing the stuff that does not work. We can add stuff that _does_ work if/when there is a consensus on data structure and associated documentation. Currently the data structure of `[author]` in config.toml is whatever the site administrator wants it to be.

**Comment by danielfdickinson** [comment]
Fair enough.  In that case probably the RSS feed shouldn't use hardcoded keys from .Site.Author either, although that is for another PR/discussion, I think.

**Comment by jmooring** [comment]
Personally, I use the [embedded templates](https://github.com/gohugoio/hugo/tree/master/tpl/tplimpl/embedded/templates) as a starting point, copying them to my projects and then tweaking them to meet my needs or match my data structures.

**Comment by danielfdickinson** [comment]
>Personally, I use the embedded templates as a starting point, copying them to my projects and then tweaking them to meet my needs or match my data structures.

@jmooring By that logic why not just update these templates with ``.Site.Author.authors``? I don't quite see how the RSS feed is different than the twitter and opengraph templates in that respect.

**Comment by jmooring** [comment]
Because that's what _I do_. I have no idea what _everyone else does_. 

My objective with this issue and the associated PR is to remove what is broken.

If we want to replace it with something, it should be by consensus. There's a long standing open issue that is directly related to how this is handled, https://github.com/gohugoio/hugo/issues/3088.
