### ISSUE TITLE
Allow theme = ["base", "my-theme" ] (aka theme composition and inheritance)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4460]
I know this has been requested before, in the form of some `extends = some-other-theme`.

This isn't "theme inheritance" in its purest form (which would be "theme1 extends theme2 extends theme3"), more like theme composition. Which is much simpler to understand/implement, but with most of the added benefits.

This relates to my work on https://github.com/bep/html5up-to-hugo -- which, with the current Hugo, becomes less elegant than it could be.

The simple rule is that **the themes' files will form a big overlay/union file system from left to right.**

So:

```toml
theme = ["base", "my-theme" ]
```

* All files in `base` will be used unless there is a file with the same name in `my-theme`.
* This will work with layouts, data, i18n, static (and in the future: content etc.)

What do you say?

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01C7E332KGT7SK0JDX4HQTBQQB/Theme%20composition%20would%20be%20really%20useful)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01C7E332KGT7SK0JDX4HQTBQQB/Theme%20composition%20would%20be%20really%20useful/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01C7E332KGT7SK0JDX4HQTBQQB/I%20don%27t%20think%20so%20%28comment%20below%29)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01C7E332KGT7SK0JDX4HQTBQQB/I%20don%27t%20think%20so%20%28comment%20below%29/vote)

**Comment by bep** [comment]
Note that this is a "proposal", I'm not done with my part of the thinking here -- maybe this belongs in the theme itself etc...

**Comment by RickCogley** [comment]
One thing I see on the forum a lot is, "how can I make page X look _different_ from the rest of the site". Could this facilitate styling a page like that, kind of overriding the theme applied to most of the site?

**Comment by brunoamaral** [comment]
From @bep's description, yes it does. You could for example have your own version of single.html or of a shortcode.

I can see how this is useful. It's the same mechanic that Wordpress uses in creating 'child-themes', but I am not a fan. I remember losing track of whether I was editing the right files.

It's a personal perspective. Others will make it useful and may help produce more themes for Hugo. I don't have the knowledge to comment on the implementation. So I will abstain from voting and may even end up using it anyway.

**Comment by kaushalmodi** [comment]
+1 if I can have my personal "theme" of partial and shortcode collection, and can keep that theme as the secondary theme. 

Thinking of something like:

```
theme = ["actual-theme", "partial-shortcode-collection-theme" ]
```

I've wanted this feature for a while. I had tried symlinking my commonly used partials/shortcodes from a common git repo, but symlinks don't work.

**Comment by Jos512** [comment]
Child themes are a great idea. They should make it easier to get started with Hugo for beginners. And they probably also make it a lot easier for people to update the original, parent theme.

**Comment by bep** [comment]
@RickCogley not sure about your example, but @kaushalmodi 's example is a primary use case, and I think this becomes super-powerful when we get proper dependency management, i.e:

```bash
theme = ["https://github.com/spf13/hyde/v2", "https://github.com/kaushalmodi/shortcode-pack/v1" ]
```

When Russ Cox is done with his brilliant thinking, I'm going to steal his thoughts: https://research.swtch.com/vgo

To me, this is mostly about DRY. On the project side, we can already today extend the theme by adding a `single.html` or overriding a partial etc. But that is not an option. So we get themes like `hydex` and `hydey` -- only slightly different ports of the same theme. If you want to create a new `hyde` theme with some blue colour, this should be possible.

Thinking about it, I think I will try to get this to work both on theme and in project. 

So in `theme.toml` for my new Hyde theme `hyde32`:

```toml
# This theme is based on SPF13's port of Hyde, but with prettier colours.
theme = ["hyde"]
```

And then in my `config.toml`:

```toml
theme = ["hyde32", "partial-shortcode-collection-theme"]
```

The ordered set of file collections will then be:

```bash
hyde, hyde32, partial-shortcode-collection-theme
```

In its first iteration, the end user is responsible for pulling the above 3 themes into /themes -- but the ultimate goal here is to do:

```bash
# Shallow clone, no themes (only referenced in config.toml)
git clone https://github.com/bep/my-site
cd my-site
# hugo will download dependencies if not cached.
hugo 
```

**Comment by regisphilibert** [comment]
I think it will be very useful especially with output formats. If want to add an "api" dimension to your content, all you'd have to do is add a special "api" theme and reference it. Rather than single handedly adding the json templates in your layouts/_default or other.

**Comment by regisphilibert** [comment]
Also it will allow theme developer to release several "extension" for their theme which not everyone will need. Like a "photo gallery" extension or a "Dentist" extension for a theme whose base is made for broader "health" entities.

**Comment by budparr** [comment]
This would be very useful. My use case is similar to @kaushalmodi  in that I keep a set of really basic files (_default layouts, etc.) to reuse on all projects and then layouts/themes for specific types of projects on top of that.

**Comment by bep** [comment]
A development tip: Features like this are hard to get going unless you have a solid and failing test up and running:

```go
const (
		themeStandalone = `
			name = "Theme Standalone"
`
		themeCyclic = `
			name = "Theme Cyclic"
			theme = "theme3"
`
		theme1 = `
			name = "Theme #1"
`

		theme2 = `
			name = "Theme #2"
			theme = "theme1"
`

		theme3 = `
			name = "Theme #3"
			theme = ["theme2", "themeStandalone", "themeCyclic"]
`

		theme4 = `
			name = "Theme #4"
			theme = "theme3"
`

		site1 = `
			theme = "theme4"
`
		site2 = `
			theme = ["theme2", "themeStandalone"]
`
	)
```

With a test that fails to build `site1` and `site2` -- then the fun starts! It is a threshold of boring work to get there.

**Comment by regisphilibert** [comment]
On more use case is "shortcode" bundles. Your theme layout files would only contains shortcode files and people could use them by just adding your theme to their "theme set" and easily upgrade with future updates.

**Comment by bep** [comment]
I just figured out that this would also be really cool for bundling of shortcodes!











:-)

**Comment by regisphilibert** [comment]
Or bundling of output formats templates ! 🎉  
You could even design an "Algolia" search theme "addon" along with script, css, template, output format template etc...

So much possibilities!

**Comment by solutionroute** [comment]
Yep, all those things that we copy from theme to theme, often without changing a single line.  Shortcodes, output formats. Heck even "base" for many. 

Note if it makes dealing with static asset customization (like a site font file or landing image

**Comment by bep** [comment]
Just a quick note that this is still pretty much priority.

In Hugo 0.38 themes got `config.toml` with namespaced `.Params` etc. and this will, of course, extend to these composites. Which will make something really powerful.

**Comment by regisphilibert** [comment]
Can't wait for @kaushalmodi to make a mini-theme out of his debug functionalities! (debugprint and so forth...)

**Comment by kaushalmodi** [comment]
@regisphilibert Thanks! By now, I have couple of "mini-themes" I'd like to roll out once this feature is out:

- Debugging (`debugprint.html` partial, Kind/Type/etc. debug info, etc.)
- ATOM as custom output format
- Better versions of internal shortcodes and templates: `figure`, `opengraph`, `twitter_cards`, ..

**Comment by bep** [comment]
@kaushalmodi @regisphilibert coming back to this issue after some months, I was a little big confused about my own writing above.

Given:


```
theme = ["base", "my-theme" ]
```

On duplicates, what theme would you say should win? `base` or `my-theme`?

**Comment by bmackinney** [comment]
👍 `my-theme`

**Comment by kaushalmodi** [comment]
@bep Of course `my-theme`. 

I can visualize that setup as this pseudo code:

```
theme my-theme extends base-theme
  function single.html
    """
    Only single.html from my-theme overriding that from base-theme
    """
```

**Comment by kaushalmodi** [comment]
If `my-theme` is overriding unwanted layouts and config params, user should trim them out.

**Comment by bep** [comment]
I guess the theme names masked my real question, how about this:

```
theme = ["theme1", "theme2" ]
```

Who should win? Is it now obvious that "theme1" is the base theme? I obviously thought so back in February, just wanted to make sure ...

**Comment by vassudanagunta** [comment]
Be consistent with #4436

**Comment by kaushalmodi** [comment]
> how about this:

>     theme = ["theme1", "theme2" ]

I think either direction (left to right, or right to left precedence) would work; just needs to be documented.

But I would suggest left to right increasing precedence order.. here's a reason:

A user could have this initially:

```toml
theme = ["some-theme"]
```

Then they choose to *steal* certain layouts from a different theme. So they then have:

```toml
theme = ["some-theme", "other-theme"]
```

i.e. they just need to append that to the right. So the delta of change only happen towards the right of that line.

Later, they tweak some portion of that "other-theme" and override just the RSS layout, so it will look like..

```toml
theme = ["some-theme", "other-theme", "my-rss"]
```

What I am getting at is that the initial `theme = ["some-theme"` part stays constant throughout. If the precendence is reversed, the base theme position will keep moving around.

**Comment by regisphilibert** [comment]
`theme-2` 👍 

It is my understanding that in any system, hardware of software, the layer on top will hide/override the layers below. As a left to right reader, it therefore makes sense to me that `theme-2` is the layer on top.

Ultimately of course and that goes without saying, project's layouts should remain the utlimate rulers of this ecosystem :)

**Comment by bep** [comment]
One last question. Since I wrote my test on this, a theme can now have `confit.toml` (i.e. site configuration). I also has a `theme.toml`, which is information about the theme -- we use this info to build the theme site etc.

So, 

With this new feature both the project and the themes can be ... themes.

The question is:

Where to put the `themes'` `theme` configuration. `theme.toml` or `config.toml`?

**Comment by regisphilibert** [comment]
> With this new feature both the project and the themes can be ... themes.

Wait a minute, why?

**Comment by bep** [comment]
>Wait a minute, why?

I added a missing "d" to the above, which may clear things up.

The obvious motivation behind this is to create a new `hyde` port without having to copy-and-paste everything.

So I create my hyde-z theme and configure it to be based on some other theme: `theme = hyde-x`

**Comment by bep** [comment]
>theme = ["some-theme", "other-theme", "my-rss"]

Yes, that makes sense. Another obvious use case would be shortcode collections, so:

```toml
theme = ["my-theme", "cool-shortcodes"]
```

In the above, on duplicate shortcodes, the right will win. If the shortcode exists in the project, that will of course win (as it is today).

**Comment by regisphilibert** [comment]
I see two ways to do this.
**The old way:**
Add your layouts files in `layouts` directory and set your theme as `hyde-x`:
`themes = 'hyde-x'`
**The new way:**
Create a `/themes/hyde-z` directory alongside `themes/hyde-x` and set theme both in your config.toml:
`themes = ['hyde-x', 'hyde-z']`

In both case, your project is not a theme, so I am still confused about your previous sentence :/

**Comment by kaushalmodi** [comment]
> Where to put the themes' theme configuration. theme.toml or config.toml? (and please don't suggest that we merge those files into one ...)

I honestly think of `theme.toml` *less of a functional config* and more of a *meta-data config*.

I think the `theme` should go in `config.toml`. Now.. with that, I believe that if the theme's config.toml has:

```toml
# theme-x's config.toml
theme = [ "theme-x", "cool-shortcodes"]
```

and user's site config.toml has:

```toml
# user's site config.toml
theme = [ "_this_", "my-shortcodes"]
```

*Looks like we will need a **special placeholder** like `"_this_"`?* Otherwise, how will "theme-x" refer just to its own stuff without including the extensions?

Does that effectively become:

```toml
# user's site config.toml
theme = [ "theme-x", "cool-shortcodes", "my-shortcodes"]
```

**Comment by regisphilibert** [comment]
I understand now. I always assumed the user would add themes’ port himself in his config.toml. 

I don’t think a theme should be able to set itself as a layer of another theme. This is prone to inheritance being unknown to the user. 

The port should let the user know he/she needs both themes in his themes directory and reference them both in his project’s config.toml this order.

**Comment by bep** [comment]
@regisphilibert your project is not a theme, but it can be _themed_ ... Which in my English means that you can configure it to use a theme.

@kaushalmodi 

If project is:

```
theme = [ "my-theme", "my-shortcodes"]
```

And theme is:

```
theme = [ "theme-x", "even-cooler-shortcodes"]
```

The final graph will be:


 [ "theme-x", "even-cooler-shortcodes", "my-shortcodes"]


The above assumes that "theme-x" is shallow.

**Comment by bep** [comment]
@regisphilibert maybe ... I'm not totally convinced either way. We have lots of very similar themes as it is today. People create a new theme just to change some minor thing. And since you currently would have to do manual clones, It would not be "unknown to the user".

**Comment by kaushalmodi** [comment]
I'm on a move, so cannot articulate properly right now.. may be do something like:

```toml
# theme config
theme_extensions = ["a", "b"]
```

If user uses that theme without modifying theme-extensions, they inherit the theme's settings as they do now. 

If user wants to add their own extensions, they need to do:

```
# user site config
theme_extensions = ["a", "b","c"]
```

**Comment by bep** [comment]
>In both case, your project is not a theme,

But it can be *themeD*?

**Comment by bep** [comment]
... that said, I see enough questions in the above conclude what we can wait with the "inheritance" part, and start with the simpler setup where a project only can use themes (i.e. composition).

**Comment by kaushalmodi** [comment]
Though, don't you think that having an extra `theme_extensions` for list config param will make this easier and leave the `theme` as a single string value.

**Comment by bep** [comment]
>Though, don't you think that having an extra theme_extensions 

What is the difference between a theme and a theme_extension? Why create one more term if they are the same? "Themes can be composed" is simpler to explain to people than "a project can have a theme. You can also add theme_extensions, which is the same as a theme, but just named differently."

**Comment by kaushalmodi** [comment]
It will blend into the theme extension inheritance that I talked about in my comment earlier. 

With just one theme param, it will get difficult if users want to remove one or more of the extensions from the original theme. 

Having the extensions, using the same example as earlier, user can set the extensions param as follows:

- [] # empty
- a
- a,b,c
- c
- if they don't set, they get the extensions the theme defined (a,b).

**Comment by bep** [comment]
@kaushalmodi you have a point, but if we start with "theme in project only", this can wait. It is a simpler model.

If we somehow need to control order at some point, we could allow the theme as a more complex structure:

```toml
[themes]
[themes.my-theme]
weight = 1
```

Which then could override the default right-to-left order you get.

**Comment by bep** [comment]
>What if the user wants to disable one or more of the theme's default extension? Are you planning to support that?

No (or maybe, but certainly not in the first iteration).

You started the talk about extensions and extensions in the scope as something optional, not me. 

We may leave the "allow theme to set themes" in the first round, but my general view on this is that:

If a theme `theme-a` says that it depends on `theme-b` then  `theme = theme-a ∪ theme-b`. You cannot remove `theme-b` from the theme and expect it to work. This brings in a relevant discussion about transitive dependencies in Go programs (see #4754). It becomes hard when you want to version them etc., but you cannot ignore the problem. And you cannot remove dependencies and expect the program to compile.

But we will have to start simple here. If Hugo gets really popular we can maybe adopt vgo's model ad get versioned imports and `hugo get` etc. 

That said, I have been thinking a little about this when sleeping. And I think we're going to reverse the order of precedence in the `theme` slice compared to what we talked about above.

If may be slightly less intuitive, but it will be consistent with #4436 (/cc @vassudanagunta) and it will solve another problem.

So in the project's `config.toml`:

* `theme = ["cool-shortcodes", "the-theme", "my-base-theme"]`

The precedence is from left to right.

* I have put `cool-shortcodes` first, because I want my shortcodes to be used and not the collection provided by `the-theme`.
* `my-base-theme` is to the far right with the lowest precedence.
* This also works mentally when you think about the project as the ultimate winner.

Also note that we currently do not have a "global identifier" for the themes, so the theme name whatever you name it when you clone it on disk. So you can certainly exclude a theme by putting some empty theme in the named folder. This is another big question that we need to keep out of this discussion.

**Comment by bep** [comment]
>What if the user wants to disable one or more of the theme's default extension? Are you planning to support that?

No (or maybe, but certainly not in the first iteration).

You started the talk about extensions and extensions in the scope as something optional, not me. 

We may leave the "allow theme to set themes" out in the first round, but my general view on this is that:

If a theme `theme-a` says that it depends on `theme-b` then  `theme = theme-a ∪ theme-b`. You cannot remove `theme-b` from the theme and expect it to work. This brings in a relevant discussion about transitive dependencies in Go programs (see #4754). It becomes hard when you want to version them etc., but you cannot ignore the problem. And you cannot remove dependencies and expect the program to compile.

But we will have to start simple here. If Hugo gets really popular we can maybe adopt vgo's model and get versioned imports and `hugo get` etc. 

That said, I have been thinking a little about this when sleeping. And I think we're going to reverse the order of precedence in the `theme` slice compared to what we talked about above.

It may be slightly less intuitive, but it will be consistent with #4436 (/cc @vassudanagunta) and it will make it more clear when you add "extension type themes" to the mix.

So in the project's `config.toml`:

```toml
theme = ["cool-shortcodes", "the-theme", "my-base-theme"]`
```


The theme's `config.toml`:

```toml
theme = ["my-cool-shortcodes", "cool-shortcodes"]`
```

The precedence is from left to right.

* I have put `cool-shortcodes` first, because I want my shortcodes to be used and not the collection (`my-cool-shortcodes`) provided by `the-theme`.
* `cool-shortcodes` is also included in the theme, but will not be included twice.
* `my-base-theme` is to the far right with the lowest precedence.
* This also works mentally when you think about the project as the ultimate winner (far left, before the = sign).

Also note that we currently do not have a "global identifier" for the themes, so the theme name whatever you name it when you clone it on disk. So you can certainly exclude a theme by putting some empty theme in the named folder. This is another big question that we need to keep out of this discussion.

**Comment by regisphilibert** [comment]
So, I'm confused now, as of this commit:
Can `themes` declare their own "dependencies"?

**Comment by regisphilibert** [comment]
Here comes another question, sorry.

If I understand correctly, theme's `config.toml` will bear its own theme declaration, we'll call it theme.theme. So will, as always, the project, we'll call it project.theme.

Now, If I understand the current state of inheritance/overriding of `config.toml`, the project's overrides the theme's.

So no matter what theme.theme is set to, will it not be systematically overridden by project.theme? This is undeniably what the user will expect anyway regarding any setting present in the theme's `config.toml`.

**Comment by bep** [comment]
>Can themes declare their own "dependencies"?

We may _wait with that until a later release_, but I think that will eventually happen.

>So no matter what theme.theme is set to, will it not be systematically overridden by project.theme? 

```
project.theme = something
theme.theme = something_totally_different
```

There is no systematic override in the above?

**Comment by regisphilibert** [comment]
> There is no systematic override in the above?

That is what I thought. Unless the slices will be merged somehow? Every project needing a theme will set a project.theme, thus overriding the theme.theme of its needed theme (which was used to declare some sort of theme dependencies)

**Comment by bep** [comment]
>That is what I thought. Unless the slices will be merged somehow? 

The slices will not be merged, but there 3 rules to be aware of. If you think of the slices from left to right, and continue that thought into the theme.

* If both the project and the theme defines `myshortcodes`  as a dependency, it will only be included once (the first one)
* If `myshortcodes` includes `someother-myshortcodes` which then includes `myshortcodes` it is of course also only included once.
* All other overrides are done on file level. So `layouts/shortcodes/myshort.html` will, on duplicates, the left-most version win.

**Comment by bep** [comment]
And note that `myshortcodes` is supposed to refer to **the same theme**, so it should not matter where it is defined. You just need it. In practice, it may be harder, with versioning etc., but we need to solve that problem later.

**Comment by maiki** [comment]
I don't know how these themes relate to each other, it seems really complicated. I like what I thought was the basic flow of left to right inheritance.

```
theme = ["theme-made-for-project", "maiki-shortcode-collection", "that-one-override-for-the-gallery"]
```
In a CMS like Drupal or WordPress the themes have a direct "lineage", meaning they refer to a single theme as a "parent", though they can be chained along. Anything not fitting in that chain is added as a plugin.

I like that, it is easy to grok and easy to remember. And I already kinda build themes that way, except for using git to layer them on top of each other.

I wanted to point this use-case, but also to comment on the ordering: it should be consistent with the logic behind template inheritance. The default archetype comes to mind, where it makes sense that it isn't overridden, but it appears to be inconsistent with how other templates work.

I feel if the project/base theme is listed last it will be harder to remember and explain )as if it were easy to explain now! Ha!). :smile:

**Comment by bep** [comment]
>it should be consistent with the logic behind template inheritance. 

I think my last proposal is that. If we keep the archetype logic out of this (we really should), then the current order is 1. project 2. theme.

Adding _plural theme_ support you get 1. project 2. themes (and also potentially themes' themes if we go down that route).

A single parent theme is probably easier to understand, but it gives away a ton of flexibility. I'm currently not a big theme user. But I see big needs in re-using and compose my project from _components_ in a simple way (shortcodes etc.). This is the reason I spend time on this feature, any theme inheritance will be an added bonus.

I say that even a component with 1 shortcode is a theme. We could come up with some other name for that, but I suspect that would make this even harder to grasp.

**Comment by bep** [comment]
I cannot decide what is the best _presedence order_. 

Given the theme list below:

```
theme = ["theme1", "theme2", "theme3"]
```

I have deliberately chosen very generic theme names, but you could imagine `base-theme`, `my-shortcode-collection` or whatever.

The question is: When two themes provide the same file (e.g. `layouts/_default/single.html`, who should win? Left or right?


[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CEK1GB4BV6PXKN39W180R708/From%20right%20to%20left%20%28theme3%20wins%20on%20duplicates%29)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CEK1GB4BV6PXKN39W180R708/From%20right%20to%20left%20%28theme3%20wins%20on%20duplicates%29/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CEK1GB4BV6PXKN39W180R708/From%20left%20to%20right%20%28theme1%20wins%20on%20duplicates%29)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CEK1GB4BV6PXKN39W180R708/From%20left%20to%20right%20%28theme1%20wins%20on%20duplicates%29/vote)

**Comment by regisphilibert** [comment]
I did not expect that outcome :) Oh well.

**Comment by bep** [comment]
>I did not expect that outcome :) Oh well.

My head was the other way around when I first thought about this, but revisiting it some months later, it just looked backwards... Reading from left makes `project extends theme1 extends theme2 extends theme3` work as a sentence.

**Comment by regisphilibert** [comment]
Yes with the "extends" notion, it makes a lot of sense.

Here is a thought, I don't think it derails the issue, but stop me if it does.

Can we question the usage of the word "theme" for this config parameter? A theme is really something people take as a skin for their website. But now, it appears a lot of our themes will be something different. Like our already popular exemple of shortcode bundle, or output formats bundle.

I feel the word theme fails to encompass what this layout inheritance will really bring along. I think we need a word used as an umbrella for themes/plugins/addons/extension as it would make more sense in the long term.

**Comment by bep** [comment]
>Can we question the usage of the word "theme" for this config parameter? 

You may question it ...

I think

1) It works if you think a theme as a composite of components and other themes: 

```toml
theme = ["component", "theme2", "another-component"]
```

Put all of those together and you got your theme.

Also, I don't want 2 terms for this, and changing it would be a fair amount of work, and you have to be really convincing to get me down that road.

**Comment by regisphilibert** [comment]
> I think it works if you think a theme as a composite of components and other themes

Again put this way it makes more sense. This should be the way to put it in the doc when the time comes. 

Thanks.

**Comment by maiki** [comment]
I've been thinking of it as everything is a set of one or more templates that operate on your content following a "theme". It could be visual layout, or shortcodes, or an output format, or all of those. So if we explain how we use "theme", it should be fairly straightforward.

I've read this conversation in a lot of projects over the years (naming and "theme"), and it is recurring issue that new users will likely know about themes solely via a PHP CMS. So they have to explain it a bit more. And we kinda have to explain everything a bit more with Hugo, it seems; a lot of folks don't quite grok the simplicity of a  "template + content" workflow. ^_^

**Comment by bep** [comment]
Just a little heads up to people waiting for this: I'm very close to finishing this implementing this now. To get this done, I had to refactor and get real control of all the theme related to filesystem handling. With this issue closed, we will have a fully virtualized filesystem interaction without all the path logic sprinkled around.

And it seems to make Hugo faster, at least for sites with themes. The hugo docs builds about 15% faster on my MacBook.

**Comment by jhabdas** [comment]
https://github.com/gohugoio/hugo/issues/2639 cross-linking for reference

**Comment by easherma** [comment]
I'd like to help with the documentation of this, mainly because I'm still having a hard time wrapping my mind around useful cases. :-D

**Comment by zxdawn2** [comment]
Is there any tutorial on how to use this function? I'm trying to use specific theme ([hugo-resume](https://github.com/eddiewebb/hugo-resume)) for 'about' page and common theme ([AllinOne](https://github.com/orianna-zzo/AllinOne)) for others. Will this function works for this situation?

I've tried this [method](https://github.com/nurlansu/hugo-sustain/issues/7#issuecomment-303346897) to use two themes. But the structure is different and results in the wrong 'about' page.

**Comment by regisphilibert** [comment]
```
theme:
  - hugo-resume
  - allinone
```

The first homonymous template/data/i18n match will overwrite the later.

**Comment by zxdawn** [comment]
@regisphilibert 
Thank you for your reply! I'm the beginner of hugo and focus on contents only.
Not quite understand your comments above.

1. Do you mean put these in the `config.toml`?
```
theme:
  - hugo-resume
  - allinone
```
However, that's `unexpected token`.

2. What's the meaning of `The first homonymous template/data/i18n match will overwrite the later.`?
Do you mean that `i18n` can be used to specify different theme for different menu?
If so, how to do that?
