### ISSUE TITLE
partial vs template recommendation unclear

### ISSUE THREAD

**Issue by rawtaz** [gohugoio/hugo#4461]
In https://gohugo.io/templates/introduction/#includes it says "Starting with Hugo v0.12, *you may* also use the `partial` call for partial templates".

In https://gohugo.io/templates/partials/#use-partials-in-your-templates it says "When using Hugo v0.12 and newer, *be sure to* use the `{{ partial "<PATH>/<PARTIAL>.html" . }}` syntax".

These two pieces of text gives different impressions - it's unclear whether or not you SHOULD use `partial` instead of `template` with Hugo 0.12 and forward, or if it's just an option you have but without recommendation.

In short, one of them should be clarified to match the other :)

**Comment by vassudanagunta** [comment]
this is a docs issue. you should close this one and open it in the docs repo.

**Comment by rawtaz** [comment]
Thanks for the pointer @vassudanagunta.
