### ISSUE TITLE
Create a simple way to list pages with a default language edition if not found

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4463]
See https://discourse.gohugo.io/t/is-there-a-good-example-for-overlay-localization-with-hugo/10788

So, if this is rendering the Chinese site, I should be able to do something similar to:

```html
{{ $pages := .Site.RegularPages | languages.Merge "en" }}
{{ range  $pages }}
{{ . }}
{{ end }}
```

The above should create a page list its default sort which:

* includes all English pages not translated to Chinese
* includes all Chinese pages

I would obviously have to work on the API/naming in the above, but the above is hard to do in the templates, but should be fairly trivial to do in Go.

**Comment by RickCogley** [comment]
Related only because it's the same "multilingual" topic, and I can make another issue if it's indeed an issue-worthy thing, but I'd like to know if I can: 

* list all items of a taxonomy regardless of the language of the pages they are attached to, for something like a generic 404 page.
* create taxo nav href's with something like {{ .URL | absLangURL }} that switches skillfully to what is appropriate for the language, say `/tags/whatever` or `/en/tags/whatever`. In other words, a cleaner way than `href="{{ if eq $thislang "en" }}/en/{{ else }}/{{ end }}tags">`. 

https://discourse.gohugo.io/t/multilingual-site-tag-lists-bug-feature/10688

**Comment by bep** [comment]
@RickCogley you need to take that in another issue.

**Comment by bep** [comment]
OK, naming/computer science experts out there:

```bash
{{ $pages := .Site.RegularPage | languages.Merge $enSite.RegularPages  }}
```

Or is:

```bash
{{ $pages := .Site.RegularPage | languages.Union $enSite.RegularPages  }}
```

Better?

The semantics are:

* includes all pages in the right collection not translated in the left
* includes all pages in the left collection

/cc @digitalcraftsman @moorereason @kaushalmodi

**Comment by kaushalmodi** [comment]
Thanks for the ping. I don't have a strong opinion between Merge and Union, but Merge somehow feels a bit better over here.

**Comment by bep** [comment]
Thinking about it, this is a left join, so ´languages.LeftJoin` would be better ...

**Comment by RickCogley** [comment]
Technically, yes, it appears to be a left join. "Union" has variations,
some of which are like what you stated. "Merge" seems more generic /
humanistic.
A thought occurred to me: Does this type of function exist elsewhere in
Hugo and, should the naming be the same or similar?

>

-- 
*This email message and any attachments are confidential, and are meant to 
be read by the intended recipient only. If you are not the intended 
recipient, we would request you delete this message or any attachments 
without reading or distributing, and kindly advise eSolia Inc. (contacts: 
esolia.com/about <http://esolia.com/about>). Thank you in advance.*

**Comment by kaushalmodi** [comment]
> Thinking about it, this is a left join

TIL about [LEFT JOIN][1]. But even after reading that:

> The LEFT JOIN keyword returns all records from the left table (table1), and the matched records from the right table (table2). The result is NULL from the right side, if there is no match.

If I understand correctly, what we are trying to do here is (changes for our application in bold):

> The LEFT JOIN keyword returns all records from the left table (table1), and the **unmatched** records from the right table (table2). The result is **ALL** from the right side, if there is no match.

So it doesn't technically seem to be LEFT JOIN for folks who might be familiar with that.. or may be I am just wrong :)

[1]: https://www.w3schools.com/sql/sql_join_left.asp

**Comment by bep** [comment]
>So it doesn't technically seem to be LEFT JOIN for folks who might be familiar with that.. or may be I am just wrong :)

You are absolutely right. I'm thinking slowly today.

**Comment by bep** [comment]
I will add `.MergeByLanguage` to the `Pages` to start with. I will see if I add a `languages.Merge` template func -- it may make sense to make this pipe friendly. Not sure.
