### ISSUE TITLE
translationKey not working with Page Resources

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#4465]
Maybe, there is an issue with Page Resources and multilingualism.

Neither

```
── blog/
│   └── my-article
│        └── index.md
│        └── index.de.md
```

nor

```
── blog/
│   └── my-article
│        └── index.md
│        └── mein-titel.de.md
```

seem to work together with `translationKey`.

&nbsp;

_Thank you very much for Page Resources. Together with #4436 this is a web developer’s dream coming true :-)_

**Comment by bep** [comment]
That is odd. Will check.

**Comment by adamhavel** [comment]
This still seems to be an issue. I have a structure like `en/blog/article-name/index.md` and `cs/blog/nazev-clanku/index.md`, linked via `translationKey` (which works for linking between the translations) and I would like them to share a `thumb.jpg`, placed in one of the folders, but the image shows only for that one language.

**Comment by Brixy** [comment]
It seems there are problems with `translationKey` and also with `slug` in combination with Page Resources.

Currently I use this in `config.yaml`:

```
permalinks:
  pages: /:slug/
```

It is the best solution I found—yet, it is a hack.

Can we re-open this issue as it was closed by the stale bot?
