### ISSUE TITLE
{{< highlight js >}} weirdly colors second half of division expression

### ISSUE THREAD

**Issue by looeee** [gohugoio/hugo#4469]
I've opened an issue in Chroma as well, feel free to close this if its not the correct place: https://github.com/alecthomas/chroma/issues/125

When I highlight code as JS it styles the second half of a division expression weirdly. 

![hugo_highlight_bug](https://user-images.githubusercontent.com/5307958/36887345-bb1ce262-1e2b-11e8-9b01-3156265b3dff.png)

I'm not using  any custom styling except setting the background color.

The style being applied to the oddly colored part is:

```css
color: #960050;
background-color: #1e0010;
```

Here's my code (using Hugo shortcode for highlighting):

```js
{{< highlight js >}}
var percentComplete = xhr.loaded / xhr.total * 100;
{{< /highlight >}}
```

Comments are colored grey, so it's not incorrectly flagging it as a comment which I originally thought.

**Comment by bep** [comment]
Let us track this in Chroma.
