### ISSUE TITLE
I can't access image in my markdown file.

### ISSUE THREAD

**Issue by praful-dhabekar** [gohugoio/hugo#4473]
I put " **1st.jpg** " in my theme folder and I'm trying to access it from **first-post.md** which is in post folder. Below is my code for access the image file:

`![The beast](../../themes/hugo-nuo-theme/static/img/1st.jpg "")`

and below is my project structure 

![atom_2018-03-04_21-40-43](https://user-images.githubusercontent.com/23056780/36947627-cb952896-1ff4-11e8-8be3-a9443562cec2.png)
In the screen you can see the **test.html** file, I created to test the code I'm writing in markdown file is working or not and found out it's working. Below is the code I used in html 

`<img src="../../themes/hugo-strata-theme/static/images/1st.jpg" alt="the beast">`

**Comment by brunoamaral** [comment]
once you build the site, the `themes` folder changes and everything there that is actually used by the html, like your image, goes to /static/

Your new path will be /static/images/1st.jpg.

On a related note, seems you are mixing between what is content and what is presentation. I would suggest you look into organising your content in folders (see 'Page Bundle' in the documentation).

**Comment by praful-dhabekar** [comment]
Hi sorry to bother you, I just started out with the hugo and I think I've to dive deep in the documentation, 
thank you for the advice. but I need more suggestion from other people so please it'll be very great if you don't close this issue right away.

**Comment by vassudanagunta** [comment]
This is not the place to ask for help. Please close this issue and ask in the [Hugo Forum](https://discourse.gohugo.io).
