### ISSUE TITLE
Proposal: Adding  a web based editor

### ISSUE THREAD

**Issue by scriptonist** [gohugoio/hugo#4474]
This proposal is based on a roadblock I encountered. 
#### This is my workflow
- Creating new blog post using `hugo new` command
- Editing the `.md` file `vscode` 

#### The problem
- Since I'm not good at English, I encounter grammatical errors while typing. 
- This is not the case in a browser-based editor because we have tools like `gramarly`.

#### Proposal
- If we have some mechanism to edit blog posts in a browser. It can solve my problem.
- some command like `hugo create open <filename> ` - opens a web-based markdown editor wherein we can edit the content.

#### Conclusion
Please feel free to close this issue if we have some better way to solve the problem and please be kind to share your solutions.

**Comment by vassudanagunta** [comment]
You should move your comment to [the existing forum discussion](https://discourse.gohugo.io/t/web-based-editor/155/39) and close this issue.

**Comment by scriptonist** [comment]
Sure thing :smile:
