### ISSUE TITLE
hugo 0.37: Markdown render italic is not worked well

### ISSUE THREAD

**Issue by shui** [gohugoio/hugo#4476]
The original string is `Y*TTTT*Y`.

Expect: <pre>Y*TTTT*Y</pre>

But Hugo 0.37 output is `YTTTTY`, not italic unless I add at least one space before first `*` and after last `*`, like `Y *TTTT* Y`.

I tried many themes, and there was same problem.

**Comment by shui** [comment]
btw, bold `**` is ok

**Comment by bep** [comment]
I'm afraid this is a limitation you would have to live with, but you need to raise the issue here:

https://github.com/russross/blackfriday/issues
