### ISSUE TITLE
Hugo 0.37 on OsX not rendering any content

### ISSUE THREAD

**Issue by giespaepen** [gohugoio/hugo#4477]
I have a project with custom layout. Running **hugo 0.37 on OsX** The hugo server commands only renders my custom sections if the files are touched while hugo server is running. When rendering it to disk, only the index file, categories and tags are rendered.

In order to replicate the bug, I retried with the **quickstart** example (https://gohugo.io/getting-started/quick-start/). Same problem, added theme, added post. Rendered it to disk: nada.

I downgraded to hugo 0.16 on OsX and it works somewhat (probably due to changes in the subsequent version.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by giespaepen** [comment]
I don't agree. I'd consider not working getting started procedures as a bug, since it's the doorstep to your program.
________________________________
Van: Bjørn Erik Pedersen <notifications@github.com>
Verzonden: dinsdag 6 maart 2018 11:15
Aan: gohugoio/hugo
CC: Gie Spaepen; Author
Onderwerp: Re: [gohugoio/hugo] Hugo 0.37 on OsX not rendering any content (#4477)


Thanks for getting in touch, but it feels like this is a question that would be better suited to the Hugo Discussion Forum<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdiscourse.gohugo.io%2F&data=02%7C01%7C%7C136a43e1d4604293064008d5834b23a5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636559281075495865&sdata=zzgBWqeBPjOhHAbLvo0f%2FJ45iLph0wRE8XAr1dT7lSw%3D&reserved=0>. We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in Hugo Documentation<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgohugo.io%2Foverview%2Fintroduction%2F&data=02%7C01%7C%7C136a43e1d4604293064008d5834b23a5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636559281075495865&sdata=KUXXvrrKHulZK5eJskVfKK4bf8vyMKIFsunObh4SODM%3D&reserved=0>.
