### ISSUE TITLE
Add .Site.IsServer to determine if the site was built in server mode

### ISSUE THREAD

**Issue by mydoghasworms** [gohugoio/hugo#4478]
As per the following Discourse discussion:

https://discourse.gohugo.io/t/disable-portions-of-content-while-developing/10860

It would be helpful to put a condition into a template that can determine whether the page is being built/server by `hugo server` (and not necessarily with the `-D` flag, for which there is already a variable).

This would be helpful for the case where you want to test the site in its final form (no drafts) but want to switch off, e.g. analytics or ads.

**Comment by erbesharat** [comment]
I was going to add this option to SiteInfo but I faced a problem, Is it required to write anything else more than adding IsServer field to SiteInfo struct and adding it to the initializeSiteInfo()? Cause I get error ```can't evaluate field IsServer in type *hugolib.SiteInfo``` when I want to test it.

I'm not familiar with Hugo's code that much and I think I'm missing something :smile:

**Comment by kaushalmodi** [comment]
But isn't this already possible by simply checking if `.Site.BaseURL` is `"localhost"`? I do that all the time.

**Comment by bep** [comment]
>But isn't this already possible by simply checking if .Site.BaseURL is "localhost"? I do that all the time.

Not if you run your server with something other than "localhost". I do that all the time. You could, of course, adjust that logic to also check for that hostname, but thaw would hardly be very portable.
