### ISSUE TITLE
Change from http to https for the homepage link of this repo

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4483]
At the top of this repo's page: https://github.com/gohugoio/hugo

![image](https://user-images.githubusercontent.com/3578197/37114165-8fa47ad0-2215-11e8-891d-ddb08b98336f.png)

the URL is using http instead of https.

Secondly, https enforcing is not enabled.. so http://gohugo.io opens as it is without auto-redirecting to https://gohugo.io.

May be @spf13 needs to take care of the latter part.. not sure.

**Comment by bep** [comment]
@spf13 needs to do the last part.

**Comment by kaushalmodi** [comment]
Here too the link needs to be https instead of http in the repo header: https://github.com/gohugoio/hugoThemesSite

Though, for that one (http://themes.gohugo.io/), the https enforcing is enabled.
