### ISSUE TITLE
Create a content adapter (content from /data;  content from sql)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4485]
I was pretty sure we had an issue for this, but I cannot find it.

* It would be good as part of this to create a better abstraction for the "page source".
* It should be possible to merge /data with matches in /content (to provide long text markdown etc.)

A cool prototype for this would be a product catalogue, see:

https://mrjoe.uk/product-page-template-sketch/

**Comment by kaushalmodi** [comment]
This: https://github.com/gohugoio/hugo/issues/140

**Comment by bep** [comment]
I have updated the title to hint at a more general design.

If we make today's "reading files from /content" a `Filesystem Content Adapter`, then we can add:

* Adapter for /data 
* Adapter for SQL databases

If we also manage to abstract away the change notifications from the files, we could have similar live reload functionality for databases via polling. 

Note that since we still want this to be fully static, we have to create some kind of intermediate file representations, so this can still be built by Netlify etc. without access to the database.

**Comment by anagrius** [comment]
This would make Hugo so much easier to use for documentation pages and any page that has a very large number of pages. +1
