### ISSUE TITLE
The Hugo was coredumped on OpenBSD/current

### ISSUE THREAD

**Issue by ssh3** [gohugoio/hugo#4486]
There is a problem with running [Hugo](https://github.com/gohugoio/hugo/releases) on the last OpenBSD snapshot.
```
OpenBSD 6.3-beta (GENERIC.MP) #46: Fri Mar  9 08:22:22 MST 2018

puffy-user@balamut:~$ date; hugo version; tail -n2 /var/log/messages
Sat Mar 10 12:25:28 +10 2018
Abort trap (core dumped)
Mar 10 12:25:28 balamut /bsd: trap pid 2679 tid 365727 type 6: sp c42003c758 not inside 7f7fffbdc000-7f7ffffdc000
Mar 10 12:25:28 balamut /bsd: trap pid 2679 tid 320113 type 6: sp c420050000 not inside 7f7fffbdc000-7f7ffffdc000
```
I think the causes of this behavior is the security changes in the OpenBSD/current.
[The mail thread is describing the similar problem.](https://www.mail-archive.com/misc@openbsd.org/msg159878.html)

**Comment by bep** [comment]
Thanks for the heads up. As I read it, this is a general Go vs the current OpenBSD, and nothing Hugo can do about? I guess this either has to be fixed by OpenBSD or the Go project?

**Comment by ssh3** [comment]
OK, I think, you are right. Thank you for your time. 
Closed.
