### ISSUE TITLE
Allow partial redefinition of the ouputs config

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4487]
In Hugo, the default `outputs` configuration looks like this:

```
[outputs]
  page = ["HTML"] 
  home = ["HTML", "RSS"] 
  section = ["HTML", "RSS"] 
  taxonomy = ["HTML", "RSS"] 
  taxonomyTerm = ["HTML", "RSS"] 
```

This is what you get when doing nothing.

The current behaviour says that _if you provide your own outputs configuration, it must be complete._

We do, however, add `HTML` as a fallback for a missing config entry. But, currently, if you want to add `JSON` to the home page (for a search index), this:

```
[outputs]
  home = ["HTML", "RSS", "JSON"] 
```

Will result in missing `RSS` for the other list types.

This is surprising for users. See https://github.com/gohugoio/hugoDocs/issues/408

* `outputFormats`, `mediaTypes`, `related`, `outputs`, `permalinks`(and maybe others) translates into a `map` in the config.
* For maps with entries of the same type (`mediaTypes`), Hugo allows redefinition of just one or more entries.
* For maps with entries of different types (`related`), you must provide the full configuration. The different entries only make sense in relation to the others.

We will follow the rule in the above and change the way `outputs` behaves.

**Comment by kaushalmodi** [comment]
I confirm the fix in this commit. Thanks!
