### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by jinleileiking** [gohugoio/hugo#4497]
../../ksyun/src/github.com/gohugoio/hugo/helpers/content.go:265:16: undefined: blackfriday.HTML_SMARTYPANTS_QUOTES_NBSP

commit : 0dbf79c2f8cd5b1a5c91c04a8d677f956b0b8fe8

**Comment by jinleileiking** [comment]
I think we should use vendor.

**Comment by jinleileiking** [comment]
go get -u gopkg.in/russross/blackfriday.v2

**Comment by bep** [comment]
>I think we should use vendor.

We do. Read the README -- if still issue, ask at https://discourse.gohugo.io/

**Comment by jinleileiking** [comment]
No vendor directory in source code.

**Comment by jinleileiking** [comment]
```
Build and Install the Binaries from Source (Advanced Install)
Add Hugo and its package dependencies to your go src directory.

go get -v github.com/gohugoio/hugo
Once the get completes, you should find your new hugo (or hugo.exe) executable sitting inside $GOPATH/bin/.

To update Hugo’s dependencies, use go get with the -u option.

go get -u -v github.com/gohugoio/hugo
```

I think it should add dep ensure to make sure the deps in readme.

SHOULD I fork the readme and make a pr?
