### ISSUE TITLE
Make Pages.Prev/Next work like the other Prev/Next methods

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4500]
See the TODO(bep) comments in https://github.com/gohugoio/hugo/commit/79dd7cb31a941d7545df33b938ca3ed46593ddfd

This would be a potentially breaking change, but these are very much undocumented,  but there seems to be 2 discrepancies with these methods:

* They go round and round, so `Pages.Next` will never return nil, which make them ... less than useful.
* They go in the opposite direction of `.Next`;  the semantic is, when the date is used to sort, to navigate to navigate to _newer_ content, `.Prev` takes you back in time.

**Comment by bep** [comment]
@kaushalmodi could you take a quick look at my statements in the 2 bullet points above and tell me if my 2 proposed fixes make sense to you.

**Comment by kaushalmodi** [comment]
Ok, so if I understand this correctly, the above 2 bullet points are the issues and and 2 fixes are:

- Now both return a nil when they reach the end of a slice 
- Now all Next methods move in the same direction, and the Prev methods move in the other direction. 

But what's not clear is what that "direction" is. 

>  the semantic is, when the date is used to sort, use .Next to navigate to navigate to newer content, .Prev takes you back in time.

Is this what is *now* happening consistently for all Next and Prev methods?

**Comment by bep** [comment]
>But what's not clear is what that "direction" is.

The test case below currently fails:

```
p := .Site.RegularPages()[5]
if p.Next() != pages.Next(p) {
    panic("Next != Next")
}
```

So, this isn't the first time we had a similar discussion, and I get confused every time I think about it.

The behavior of `.Next` and `.PrevInSection` is that `.Next` points to the _lesser_ value (depending on the page sort). This is probably mostly driven by the default descending date (if weight not set) sorting:

* Default sort, date, then `.Next` will point to the _newer_ page.
* If weight is used to sort, then `.Next` will point to the page with _less_ weight.
* If sorted by title and titles are `A, B, C`, then `B.Next==A`.

E.g. it points in _reverse_ direction if you look at the slice index, but it points upwards (newer ...) when you list them on a page ...
