### ISSUE TITLE
Default for rssLimit ignored

### ISSUE THREAD

**Issue by pkollitsch** [gohugoio/hugo#4506]
The documentation on rssLimit states a default value of 15. (http://gohugo.io/getting-started/configuration/)
But removing `rssLimit = 10` from my configuration leads to the creation of a very huge file with all entries instead of 15.

**Comment by kaushalmodi** [comment]
Can you move this to an issue on the hugoDocs repo?

**Comment by pkollitsch** [comment]
sure.
