### ISSUE TITLE
Make the title for CLI Documentation more specific..

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4510]
.. like "Command Line Documentation".

At the moment, that title is just "Documentation" (See below).

Ref: https://github.com/gohugoio/gohugoioTheme/issues/63#issuecomment-373843219

![image](https://user-images.githubusercontent.com/3578197/37542460-a30bdb9c-2934-11e8-9140-efdf9028a499.png)

**Comment by bep** [comment]
I think "Commands" would be both short and descriptive enough.

**Comment by bep** [comment]
Not sure where/Algolia picks its titles ...

**Comment by bmackinney** [comment]
> Not sure where/Algolia picks its titles ...

It looks like it groups by the last `category` term, and when no category is set on a doc, it calls it "Documentation"

<img width="490" alt="Screen Shot 2019-09-03 at 7 29 33 PM" src="https://user-images.githubusercontent.com/646061/64221912-51355c80-ce83-11e9-9066-831d5c58fe72.png">

**Comment by dongorgan** [comment]
@jmooring Is this relevant? Based on your comment here https://github.com/gohugoio/gohugoioTheme/issues/63#issuecomment-1803080379

**Comment by jmooring** [comment]
Closed with https://github.com/gohugoio/hugoDocs/commit/a6d9c362c0829af386fac9515fcec2484d67beb5
