### ISSUE TITLE
Nested where + date condition

### ISSUE THREAD

**Issue by Rambobafet** [gohugoio/hugo#4517]
Hi everyone,

I think I fumbled on an issue using `where` conditionnals combined to a `date` comparison.
I opened a thread on the forum (https://discourse.gohugo.io/t/nested-where-date-compare-not-working/10978), tried what someone advised but i'm getting more and more error messages.

Please find my last message on the forum below.

**System information:**
- Win7
- Hugo v0.37

Thanks

________________________________

Here's what I tried and error messages that I got:

```go 
len (where (where .Data.Pages "Section" "bal" ) "(time (.Params.event_info.event_date))" "ge" "now" ) 
```  
=> `error calling where: (time ( isn't a field of struct type *hugolib.Page`
*(I don't really understand this error message btw)*
```go
len (where (where .Data.Pages "Section" "bal" ) (time (.Params.event_info.event_date)).Unix "ge" now.Unix
```
=> `can't evaluate field Unix in type *errors.errorString`

```go
len (where (where .Data.Pages "Section" "bal" ) (dateFormat "20060102" .Params.event_info.event_date) "ge" (now.Format "20060102")) }}
```  
=> `executing "main" at <dateFormat "20060102...>: error calling dateFormat: unable to cast <nil> of type <nil> to Time`

```go
(time .Params.event_info.event_date).After now
```
This one, outside of any where returns the right answer. But if I call it within the where like this:
```go
len (where (where .Data.Pages "Section" "bal" ) (time .Params.event_info.event_date).After now "eq" "true")
```
=> `can't evaluate field After in type *errors.errorString`

If I declare this as a string 
```go
"(time .Params.event_info.event_date).After now"`)
```
=> ` executing "main" at <where (where .Data.P...>: error calling where: (time isn't a field of struct type *hugolib.Page`

```go
len (where (where .Data.Pages "Section" "bal" ) (.Params.event_info.event_date | dateFormat "20060102") "ge" (now.Format "20060102"))
```
=> `executing "main" at <dateFormat>: wrong number of args for dateFormat: want 2 got 1`

**Comment by bep** [comment]
You need to take this on https://discourse.gohugo.io/
