### ISSUE TITLE
Improve comments handling in Remarshal

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4521]
Related to #4520 -- but that will have to wait ... A hard nut.

**Comment by bep** [comment]
@regisphilibert I will have to revisit #4520 later (it was harder than I thought) -- but I have tested a little with comments (added a test for it), and I cannot see any errors (if you position the comments correctly) -- they are removed, yes, but that is currently expected.

**Comment by regisphilibert** [comment]
You are right, I forgot what I wrote myself here at bullet 3: https://github.com/gohugoio/hugoDocs/issues/363#issuecomment-373867623

Which is that the error is triggered only when a commented string contains a `#` like in a URL. We can live with that!

**Comment by bep** [comment]
>Which is that the error is triggered only when a commented string contains a # like in a URL. We can live with that!

That is a problem you would have in any case. I will take one more stab at the other problem ... I have one more idea to test.
