### ISSUE TITLE
Add support for "content root" per language

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4523]
For bigger multilingual documentation sites etc., having all the translated version in the same folder can be a little hard to administer, even if you split into sections/sub folders.

You can, currently, somehow get around this by setting a `translationKey`, but you will still have to put the language code in the file name.

I suggest that we introduce a "content root" setting per language:

```bash
content
├── en
│   └── docs
│       ├── some-doc-1.md
│       ├── some-doc-2.md
│       ├── some-doc-3.md
│       └── some-doc-4.md
└── jp
    └── docs
        ├── some-doc-1.md
        ├── some-doc-2.md
        ├── some-doc-3.md
        └── some-doc-4.md
```

The simple rule being: All content without a language identifier in the filename will fallback to the "root 's language".

**Comment by bep** [comment]
@RickCogley any thoughts/objections?

**Comment by RickCogley** [comment]
No, that looks clean to me. I assume Hugo would be able to determine a file's translation status by comparing the file names, and matching ones that are the same from lang to lang?

**Comment by bep** [comment]
>Hugo would be able to determine a file's translation status by comparing the file names, and matching ones that are the same from lang to lang?

Yes.

**Comment by RickCogley** [comment]
It begs the question though, about bundled assets. I think currently you can put any language-shared images in the bundle, and access them from both files, say, index.md and index.en.md in my case, where index.md is Japanese. I'd have to copy the shared asset to the second bundle folder, no?

**Comment by bep** [comment]
I'm not sure. But note that you don't have to use this and you can mix and match. This is mostly targeted at "big and content heavy" sites.

**Comment by bep** [comment]
@RickCogley I have pondered a little about how to implement this, but now I think I know:

So, given this:

```bash
content
├── en
│   └── docs
│       ├── some-doc-1.md
│       ├── some-doc-2.md
│       ├── some-doc-3.md
│       └── some-doc-4.md
└── jp
    └── docs
        ├── some-doc-1.md
        ├── some-doc-2.md
        ├── some-doc-3.md
        └── some-doc-4.md
```

Will transformed become:

```bash
content
├── en
│   └── docs
│       ├── some-doc-1.md
│       ├── some-doc-2.md
│       ├── some-doc-3.md
│       └── some-doc-4.md
└── jp
    └── docs
        ├── some-doc-1.md
        ├── some-doc-2.md
        ├── some-doc-3.md
        └── some-doc-4.md
```

Will when looket at as "one tree" look like this:

```
content
└── docs
    ├── some-doc-1.jp.md
    ├── some-doc-1.md
    ├── some-doc-2.jp.md
    ├── some-doc-2.md
    ├── some-doc-3.jp.md
    ├── some-doc-3.md
    ├── some-doc-4.jp.md
    └── some-doc-4.md
```

Which would effectively solve all the shared bundle issues you mention.

**Comment by RickCogley** [comment]
@bep works the magic as usual 👍

**Comment by bep** [comment]
>@bep works the magic as usual 👍

@RickCogley I just tested the conceptual technical part and it looks beautiful. Note that I would not have thought of the simple solution without your input.

**Comment by vinniejames** [comment]
Would this improvment still allow still allow a folder structure in the form of:
en/
  Index.MD
  Page.MD
JP/
  Index.MD
  Page.MD 

Scoping this out as a possible framework, our current setup uses the organization above. With 3,000+ source files * 6+ languages, a flat folder structure feels like a regression. Does Hugo support browser accept-languge switching our-of-the-box?

**Comment by bep** [comment]
>Would this improvment still allow still allow a folder structure in the form of

Yes, indeed. For general questions, see https://discourse.gohugo.io/

**Comment by vinniejames** [comment]
Yes, per my edit what is preventing this proposed folder structure now?

**Comment by bep** [comment]
> Yes, per my edit what is preventing this proposed folder structure now?

Read my edits.
