### ISSUE TITLE
Empty Content in "atom.xml" alternative output if outputformat name is capitalized

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4529]
Hello,

I have thoroughly verified the reproducibility of this bug.

---

From https://discourse.gohugo.io/t/bug-empty-content-in-atom-xml-alternative-output-if-outputformat-name-is-capitalized/11170:

I got atom feed generation for my site working fine. But in that process I discovered this strange behavior (most likely a bug).. that I cannot capitalize outputformat `name`.

**Note that I am running the `master` branch built version of `hugo`.**

### Details

Here is the media type and output format definition for atom feed in my site config:

```
[mediaTypes]
  [mediaTypes."application/atom"]
    suffix = "xml"

[outputFormats.Atom]
  # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  name = "atom"
  mediaType = "application/atom"
  baseName = "atom" # generated file = <baseName>.<mediaType."application/atom".suffix> = atom.xml
  isPlainText = false

[outputs]
  home = ["HTML", "RSS", "ATOM"] # default = ["HTML", "RSS"]
```

The atom feed generates fine (the [`atom.xml`][3]), as expected, based on [this `list.atom.xml` template][1].

But if I simply change `name = "atom"` to `name = "Atom"` ([test commit][2]), strange behavior ensues:

Everything in that template still seems to work fine except that the most important part, `.Content` insertion has issues.. [this line in the template][5]:

```
{{ printf "<content type=\"html\"><![CDATA[%s]]></content>" .Content | safeHTML }}
```

Running hugo server:

- Initially the atom feed gets generated with empty content, as if `.Content` were "".
- But if I modify and save the `list.atom.xml` *while* the server is   running, the content gets inserted fine!

Running hugo:

- Here, as there is no chance to regenerate like in the server case, the atom feed will always have empty content.
- You can see the "content-less" atom feed [here][4] generated on Netlify using [that commit][2] where I capitalized `name` value (vs the "content-full" [`atom.xml`][3] where the outputformat `name` was all-lowercase "atom").

*All of that just because I capitalized the outputformat `name`?*

### Screenshots

**Working case (with `name = "atom"`)**

[![image|690x421](https://discourse-cdn-sjc2.com/standard12/uploads/gohugo/original/2X/7/7a9aec26ed950303e2f604e2baf70cd292ada0ff.png)][3]

**Failing case (with `name = "Atom"`)**

[![image|583x311](https://discourse-cdn-sjc2.com/standard12/uploads/gohugo/original/2X/8/86114c74d2508593dde264ab9b48a6aad347f7c1.png)][4]

---

This issue is not seen when setting `name` to any variance of casing *with the condition that the first letter is always lower-case*: `"aTOM"`, `"aTom"`,`"aTOm"`, .. 

The issue occurs only seen when the first letter is capital i.e. `"Atom"`, `"ATOM"`, `"ATOm"`, ..

It's easy to switch back and forth those 2 cases, with hugo server running, and editing/saving just that `name` assignment in `config.toml`. 

*But note that if I modify and save the `list.atom.xml` instead while the server is running, the issue goes away.. until I kill and restart the server.*

---

[1]: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/master/layouts/_default/list.atom.xml
[2]: https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/commit/e295d96784ffff59a0df8d0c97863a62ba309cdc
[3]: http://scripter.co/atom.xml
[4]: https://5ab563f2df995330accb05d3--scripter-co.netlify.com/atom.xml
[5]: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/c49f2c653821ce63366bfc0c9eb05f1edc9948e0/layouts/_default/list.atom.xml#L47

**Comment by kaushalmodi** [comment]
@bep Can this please is categorized appropriately so that it doesn't get auto-closed? Thanks.

**Comment by moorereason** [comment]
@kaushalmodi, can you confirm that this is still an issue?

**Comment by kaushalmodi** [comment]
This issue does not apply any more with the changes in output format suffixes a couple of Hugo versions back.

Now the same Atom feed output format definition looks like this:

```
[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]
[outputFormats.Atom]
  # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  mediaType = "application/atom+xml"
  baseName = "atom" # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
  isPlainText = false
```

While the exact same issue does not persist, I noticed that changing the `baseName` to `"Atom"` instead of `"atom"` has no effect.. it's as if the `baseName` is auto-lower-cased internally.
