### ISSUE TITLE
Make relTargetPathBase an exported field

### ISSUE THREAD

**Issue by rcarmo** [gohugoio/hugo#4531]
I've been trying to "solve" the issue of surfacing images inside nested subfolders in section lists, and would love to have access to `.relTargetPathBase` inside a layout template to rebuild image URLs.

That way I could have a post listing that did something like this: 
```
 {{ if eq .Section "photos" }}
   <!-- Take .Content and try to reformat img src -->
{{ else }}
    {{ .Summary }}
{{ end }]
```

This is because right now it appears to be impossible to have Hugo automatically rewrite SRC paths when you have a nested folder structure, even though I've been investigating the forums and issues for workarounds (I'm trying to move across a site with around 3000 image assets that are inside a `year/month/day` folder hierarchy, and are referenced locally in the `index.md` files -- individual posts render fine, but building a list view that shows images correctly is apparently impossible)

**Comment by rcarmo** [comment]
Bump to keep this as a feature request with the original rationale.

**Comment by bep** [comment]
Can you give a more complete example (link to source?) for what you are trying to do? I don't understand it from the description above.

**Comment by rcarmo** [comment]
I can try to build a (non-working) example, but it’s probably best to explain the scenario:

I have a post-by-folder setup with images alongside markup, and I would like to be able to build a section index (a month or a year) with the title and hero image of each post.

Right now there is no way to do that using relative paths inside a layout template.
