### ISSUE TITLE
it suddenly present rss page though I never try that, and then I failed to go back to the html page

### ISSUE THREAD

**Issue by cheioKID** [gohugoio/hugo#4532]
I am confused about why it suddenly present rss page even though I never try that, like this

This XML file does not appear to have any style information associated with it. The document tree is shown below.

------

```xml
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>hello goodbye</title>
<link>http://cheioKID.github.io/</link>
<description>Recent content on hello goodbye</description>
<generator>Hugo -- gohugo.io</generator>
<language>zh-cn</language>
<lastBuildDate>Sun, 20 Aug 2017 21:38:52 +0800</lastBuildDate>
<atom:link href="http://cheioKID.github.io/index.xml" rel="self" type="application/rss+xml"/>
<item>
<title>About</title>
<link>http://cheioKID.github.io/about/</link>
<pubDate>Sun, 20 Aug 2017 21:38:52 +0800</pubDate>
<guid>http://cheioKID.github.io/about/</guid>
```

I've already try to set **disableRSS = true** in the **config.toml**, but nothing changed, always the rss pages greeting me, evern though I start over again 2 or 3 times. It's really a hard stuff for me, I don't know why and what have I done.

By the way, it is html page as I expect if baseURL turned to "http://localhost:1313/"

Thanks for your kindness and patience, thank you!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
