### ISSUE TITLE
Snap version of hugo throws relocation error

### ISSUE THREAD

**Issue by mominul** [gohugoio/hugo#4533]
I am using the snap version of hugo for sometime. But now I can't run hugo. Every time when I try to run hugo, this error shows up:
```
/snap/hugo/1455/bin/hugo: relocation error: /snap/hugo/1455/lib/x86_64-linux-gnu/libpthread.so.0: symbol __mmap, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```
I have removed and installed hugo snap again, but the error persists.
```
$ snap list
Name   Version    Rev   Developer     Notes
core   16-2.31.2  4206  canonical     core
hugo   0.37.1     1455  hugo-authors  -
rg     0.8.1      15    tasdomas      -
```

I am using Ubuntu 17.10

Thank you for building such a useful project!

**Comment by bep** [comment]
See this thread: https://discourse.gohugo.io/t/hugos-snap-stopped-working/11184/27

I will track this in another issue.
