### ISSUE TITLE
"relocation error" from Hugo snap

### ISSUE THREAD

**Issue by felicianotech** [gohugoio/hugo#4536]
Hugo version installed via snap: v0.37.1

Error message:

> /snap/hugo/1455/bin/hugo: relocation error: /snap/hugo/1455/lib/x86_64-linux-gnu/libpthread.so.0: symbol __mmap, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

This error message happens when using a complex command such as `hugo serve` but even with a simple command such as `hugo version`.

**Comment by bep** [comment]
#4508
