### ISSUE TITLE
themes.gohugo.io show invalid count?

### ISSUE THREAD

**Issue by caarlos0** [gohugoio/hugo#4537]
At https://themes.gohugo.io if I look at the sidebar, it says it has 7 themes with the `docs` tag, but if I click in the link ( https://themes.gohugo.io/tags/docs/ ) it shows only 4.

This probably happens with more tags...

---

![image](https://user-images.githubusercontent.com/245435/37881893-3f7a0c2e-3074-11e8-8aa1-93b001f17488.png)

![image](https://user-images.githubusercontent.com/245435/37881896-44fcb958-3074-11e8-9f33-b1a1c85e0c05.png)

**Comment by olikami** [comment]
This definitely happens with more tags: [Ghost](https://themes.gohugo.io/tags/ghost/) has only 3 (6), [Resume](https://themes.gohugo.io/tags/resume/) 2 (3) and [Dark](https://themes.gohugo.io/tags/dark/) 5 (10).

It seems to be either the double or double-1.

**Comment by digitalcraftsman** [comment]
Possible reasons could be that some themes fail to build (i.e. are not compatible with the latest Hugo version) or are blacklisted. In this case they don't appear in the finally rendered page but are still counted.

**Comment by kaushalmodi** [comment]
This seems very much related to https://github.com/gohugoio/hugoThemesSite/issues/50. Earlier the /tags page probably exposing this underlying issue.

**Comment by bep** [comment]
You need to move this to the theme site repo.

**Comment by caarlos0** [comment]
> You need to move this to the theme site repo.

sorry, done -> https://github.com/gohugoio/hugoThemesSite/issues/51
