### ISSUE TITLE
Option to provide default value for Scratch.Get

### ISSUE THREAD

**Issue by julianoappelklein** [gohugoio/hugo#4542]
Would be nice to have an option to provide a default value when invoking Scratch.Get.
This way, if someone wants, for example, to increment a counter inside a loop, he could do something like:

```
{{ $defaultValue := 0 }} <!-- for clarity only -->

{{ range .Pages }}
  {{ if SOME_CONDITION }}
    $.Scratch.Set "counter1"  ( add ($.Scratch.Get "counter1" $defaultValue) 1 )
  {{ end }}
  {{ if ANOTHER_CONDITION }}
    $.Scratch.Set "counter2"  ( add ($.Scratch.Get "counter1" $defaultValue) 2 )
  {{ end }}
{{ end }}
```

Also, would be cool to have a function $.Scratch.GetInMap with the same feature.

**Comment by bep** [comment]
https://gohugo.io/functions/default/#readout
