### ISSUE TITLE
Hugo and Surge

### ISSUE THREAD

**Issue by miguelmf** [gohugoio/hugo#4544]
Hello,

Is it possible to use hugo with surge.sh? I'm trying but it's working. The site works perfectly when I do "hugo server -D", but after doing "hugo" and "surge public", the output is the following:

http://stillnotworking.surge.sh/ 

Any idea what's happening?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
