### ISSUE TITLE
Options "--cleanDestinationDir" and "--cleanDestinationDirKeepDotFolders"

### ISSUE THREAD

**Issue by htr3n** [gohugoio/hugo#4546]
Hi all,

As hosting my site using `github.io`, I have just set my `github.io` page as a submodule under public.

`git submodule add git@github.com:htr3n/htr3n.github.io.git public`

I've used  the option `--cleanDestinationDir` before (no submodule under `public`) without problems. Now, I realize that the git's metadata (i.e. `.git`) under `public` are all deleted and therefore the submodule is effectively nullified and disconnected. 

I did some research around and found out relevant [reports / suggestions](https://github.com/gohugoio/hugo/issues/3202). Even the option `--cleanDestinationDirKeepDotFolders` was added [here](https://github.com/gohugoio/hugo/pull/3210) in March 2017. Nevertheless, I checked out `hugo version` and did not find the option  `--cleanDestinationDirKeepDotFolders`.

Has the option `--cleanDestinationDirKeepDotFolders` already been incorporated in Hugo or are there any other mitigations for cleaning the destination directory (`public`) but keeping dot files? 

I enclose here some relevant info.

```
$ brew install hugo --HEAD
...
$ hugo version
Hugo Static Site Generator v0.38-DEV darwin/amd64 BuildDate:
$ hugo --help
hugo is the main command, used to build your Hugo site.
...
      --canonifyURLs               (deprecated) if true, all relative URLs will be canonicalized using baseURL
      --cleanDestinationDir        remove files from destination not found in static directories
      --config string              config file (default is path/config.yaml|json|toml)
...
```
Thanks in advance for your help.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by pojebunny** [comment]
Sorry for digging out an old issue, but I'm currently in the same situation with HUGO v0.54.0 installed in /usr/local/bin and a setup for GitHub pages "public" being the build destination and a submodule of the root project directory.

Issuing a " hugo -b "$baseURL" -D --cleanDestinationDir --quiet " command removes everything including the .git file.

**Comment by pojebunny** [comment]
I really don't want to create another account just to leave a single post.
Can you please investigate the issue where --cleanDestinationDir removes .git files?

Thank you
