### ISSUE TITLE
`$.Page.Resources.GetMatch "foo.png"` panics Hugo

### ISSUE THREAD

**Issue by seelensonne** [gohugoio/hugo#4548]
The documentation for [Page Resources](https://gohugo.io/content-management/page-resources/) says:

> **GetMatch:** Same as Match but will return the first match. 

So the following two code snippets (extracted from a custom shortcode) should be identical, right?

**Snippet 1** uses `Match` and retrieves the first element of the slice:

```go
{{ $res := index ($.Page.Resources.Match "foo.png") 0 }}
{{ $res.Name }}
```

**Snippet 2** has the same glob pattern, but uses `GetMatch` instead:

```go
{{ $res := $.Page.Resources.GetMatch "foo.png" }}
{{ $res.Name }}
```
Number one is fine and returns the string `foo.png`.

Number two causes Hugo v0.37.1 to panic with `reflect: Method on nil interface value`.

**Comment by bep** [comment]
It is impossible for me to tell without seeing the full source. I have looked twice at the implementation now, and I cannot see how the two examples should behave differently -- so this must mean that the Error you see is "something else". Both of your examples would fail for an image that does not exist.

So, this would be more robust:

```html
{{ $res := $.Page.Resources.GetMatch "foo.png" }}
{{ with $res }}
{{ .Name }}
{{ end }}
```

You would need to provide a small and failing example for me to look further into this problem.

**Comment by seelensonne** [comment]
I'm terribly sorry, but it seems to have been a false alert, the panic didn't occur in a very simple test case. I'll check the actual site again and report back if I can extract a reliable test case.

Thanks a lot for the quick reply, very much appreciated!
