### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by jpatters** [gohugoio/hugo#4557]
I believe I have run into a race condition. Here is the full error output:

https://gist.github.com/jpatters/ad231868ced67082ca9f2230c233cf41

I ran the go race detector on Hugo while building our site and it returned 18 possible race conditions. I don't have the output from this at hand.

The site I am building is here: https://github.com/forestryio/forestry.io. It happens once every 3 or 4 builds. Sometimes more often.
I have tested on Hugo versions 0.31.1, 0.37.1, and 0.38. (the stack trace is from 0.38)
I am seeing this on macOS 10.13.3 and on Alpine Linux 3.7

**Comment by bep** [comment]
The stack trace is from Go 1.10.1 which none of the Hugo releases is built with, so I assume this is built from source. I will eventually investigate this, but on first look, it looks like a bug in Go.

**Comment by bep** [comment]
So, the problem template is the `list.algolia.json` -- which looks ... unusual.

I suspect this is a case of confusion with the "dot".

* You iterate all pages
* Then call `.Scratch.SetInMap` on those individual pages, which I assume you don't want.
* There are all kinds of concurrency issues in that template. Hugo cannot protect against that without creating full copies on every set. `.Scratch` is thread safe on the inside.
* I understand the scratchiness of Scratch, but you may get some inspiration for a simpler construct here: https://github.com/bep/bepsays.com/blob/master/layouts/index.json

**Comment by jpatters** [comment]
@bep thanks for taking a look. I will make the advised changes to `list.algolia.json` and report back.

I installed the new version with homebrew this morning. Does homebrew rebuild from source? I don't even have go 1.10.1 installed locally. (Latest version I have installed is 1.10)

**Comment by bep** [comment]
>I installed the new version with homebrew this morning. Does homebrew rebuild from source? I

Ah, OK. I forgot abot Brew. They build from source.

**Comment by jpatters** [comment]
Thanks @bep. That fixed the race issues.
