### ISSUE TITLE
snap: build fails with "mage check"

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugo#4578]
"mage check", which runs "go test", gofmt, "go vet", and
"go test -race", fails one way or another especially on
on non-amd64 architectures, and sometimes even on amd64 too.

This problem was introduced when I changed "mage test" to "mage check" in commit 294c0f8 without documenting it.  My apologies.

I will push a fix reverting the change in a short moment.

**Comment by anthonyfok** [comment]
Wow, @ bep, thank you for your _instantaneous_ response!  (I saw you adding the 0.38.1 milestones in mere seconds after I pressed the "Submit new issue" button.  :-)

For reference of some of the failures I was seeing with "mage check":

Successful Builds (only one thus far):

* amd64 ([build 183973](https://launchpad.net/~gohugoio/+snap/hugo-dev/+build/183973)): https://launchpad.net/~gohugoio/+snap/hugo-dev/+build/183973/+files/buildlog_snap_ubuntu_xenial_amd64_hugo-dev_BUILDING.txt.gz

Failed Builds:

* amd64 ([build 184023](https://launchpad.net/~gohugoio/+snap/hugo-dev/+build/184023)): https://launchpad.net/~gohugoio/+snap/hugo-dev/+build/184023/+files/buildlog_snap_ubuntu_xenial_amd64_hugo-dev_BUILDING.txt.gz
    ```
    exec: go test -race ./...
    [...]
    --- FAIL: TestMultiSitesRebuild (12.12s)
    	leaktest.go:90: leaktest: timed out checking goroutines
    ```
* i386 ([build 183976](https://launchpad.net/~gohugoio/+snap/hugo-dev/+build/183976)): https://launchpad.net/~gohugoio/+snap/hugo-dev/+build/183976/+files/buildlog_snap_ubuntu_xenial_i386_hugo-dev_BUILDING.txt.gz
   ```
   exec: go test -race ./...
   go test: -race and -msan are only supported on linux/amd64, freebsd/amd64, darwin/amd64 and windows/amd64
   Error: running "go test -race ./..." failed with exit code 2
   ```
* ppc64el ([build 183978](https://launchpad.net/~gohugoio/+snap/hugo-dev/+build/183978)): https://launchpad.net/~gohugoio/+snap/hugo-dev/+build/183978/+files/buildlog_snap_ubuntu_xenial_ppc64el_hugo-dev_BUILDING.txt.gz
    ```
    fork/exec /tmp/go-build421564141/b281/bufferpool.test: no such file or directory
    FAIL	github.com/gohugoio/hugo/bufferpool	0.011s
    ```

_Maybe_ we could add a check for GOARCH == amd64 before actually running `go test -race ./...` in HugoRace() in magefile.go, but then, maybe not... too much work for no apparent benefit.
Let's just leave the race tests to Travis CI and others.  :wink:

**Comment by bep** [comment]
I don't think running "mage check" everywhere is giving us anything of real value -- I guess it mostly adds work. Which we have plenty.
