### ISSUE TITLE
Add image watermarking

### ISSUE THREAD

**Issue by bademux** [gohugoio/hugo#4595]
All issues related to image watermarking are closed  as native image processing comes to Hugo.
Unfortunatly in image feature set I lack of image watermarking (with test or image)
As far as I can see there is a function in library used by Hugo https://gowalker.org/github.com/disintegration/imaging#Overlay

**Comment by bep** [comment]
The hardest part about doing this is getting the API right, so I would appreciate if someone put some thought into this. 

I.e.

* Should this be configured globally for all images?
* What is a watermark? Text? Another image?
* Etc.

**Comment by bademux** [comment]
Thanks for starting discussion about the topic.
From what I see an image lib API allows to use an image-as-watermark. 
Image is reasonable solution. 'text as watermark' has a lot of variables to be handled, like font type font size, font availability, font position... and so on, I don't think it is worth to implement it, as the only benefit I see is font scalability.

In my opinion watermark have to be 
defined in global config and can be
used from shorthand by watermark name or
used by watermark name as global image watermarking filter.
For global watermark filter we should be able to define what images will be processed by providing image size (width, height), image type, file name; AND operator can be used with properties (like width=60; name=* equals to images with width 60px and any name). 
Watermarking filter should be applied as last one (after resizing,  cropping ...).

Watermark definition should contain 
 name of watermark (used in filter or shorthand),
 image file to be used as watermark,
 x,y coordinate where to put watermark,
  anchor (sometimes called gravity) - from what corner defines start of x,y pos,
 Optionally opacity.

If watermark doesn't fit into image warning can be generated and part that fits can be used, imho

From what I understand automatic about autocrop, the same (but reversed) logic can be reused for watermarking: watermark can be placed on only non hot area.

**Comment by gytisrepecka** [comment]
Image watermarking with `Images.Overlay` is nice, but it doesn't support setting transparency (Alpha) - that's rather useful trying to make watermarks (logos) not too intrusive.

I have [implemented image watermarking](https://source.gyt.is/gytisrepecka/webimg/src/branch/master/watermark.go#L81) using standard Go `image` library.

Would this be something community would find useful?

**Comment by bep** [comment]
@gytisrepecka there is just too many issues/notifications, so I almost never reads comments in closed threads. I suggest you create a new issue and maybe reference this one.

**Comment by gytisrepecka** [comment]
> @gytisrepecka there is just too many issues/notifications, so I almost never reads comments in closed threads. I suggest you create a new issue and maybe reference this one.

Thanks, created #9257 to discuss adding transparency (alpha) setting to `Images.Overlay`.
