### ISSUE TITLE
Using codefences does not obey pygmentsUseClasses setting

### ISSUE THREAD

**Issue by TotallyInformation** [gohugoio/hugo#4596]
Using Hugo v0.38.1

I've set the following in my `config.toml` and generated the `styles.css` file as per the docs.

If I use `{{< highlight langcode >}}`, the styles are used. If I use codefences, the styles are **not** applied.

This is because, when using codefences, the code is not wrapped in a div with the `highlight` style applied and the `data-lang` attribute is not added to the `<code>` tag.

This is certainly not the behaviour [implied in the documentation](https://gohugo.io/content-management/syntax-highlighting/#highlight-in-code-fences) and not the behaviour I would expect.

It makes migration from other platforms really difficult in addition to making it needlessly complex to write posts containing code.

Ideally, this would be fixed so that codefences have the same behaviour as implied in the current documentation. Otherwise, at least the documentation should be updated to reflect what actually happens.

As a footnote, it would also be helpful to noobs if the documentation about generating the syntax.css file were slightly expanded to explain that this file should go in the `static` folder and be included in the master layout `baseof.html`.

In case you think that I am being a little harsh, please let me also take this opportunity to say that Hugo is far and away the best static site generator that I've used. I've only just started using it and I've already been able to create a theme from scratch and migrate a rather gnarly WordPress site. So many thanks for the ongoing efforts.

**Comment by bep** [comment]
>If I use {{< highlight langcode >}}, the styles are used. If I use codefences, the styles are not applied.

We use both of these vairants on the Hugo docs site with pygmentsUseClasses, and that obviously works fine.

**Comment by TotallyInformation** [comment]
BTW, if you want examples, they are on my test site here:

https://confident-carson-5eac42.netlify.com/kb/hugo/hugo-snippets/

**Comment by bep** [comment]
Make sure you set "pygmentscodefences = true" in your site config. I think you would be better off taking further troubleshooting at https://discourse.gohugo.io/

**Comment by TotallyInformation** [comment]
I already have that. I will take this across to discourse then.

**Comment by goncalotomas** [comment]
For those interested in the Discourse post: https://discourse.gohugo.io/t/solved-using-codefences-does-not-obey-pygmentsuseclasses-setting/11442
