### ISSUE TITLE
.Site.RSSLink is a dead link if defaultContentLanguageInSubdir = true

### ISSUE THREAD

**Issue by carmenbianca** [gohugoio/hugo#4615]
The title basically describes the problem well enough. When you have RSS enabled and `defaultContentLanguageInSubdir = true`, then the index.xml files are placed in `/en/index.xml`, `/eo/index.xml`, etc. But `.Site.RSSLink` refers to `{{ .Site.BaseURL }}/index.xml`, which does not exist.

**Comment by bep** [comment]
Will be fixed in #4427

**Comment by carmenbianca** [comment]
Ah, thank you very much for your swift response!
