### ISSUE TITLE
Optional positional params in shortcodes

### ISSUE THREAD

**Issue by paulcmal** [gohugoio/hugo#4619]
Hi,

Following a [discussion](https://discourse.gohugo.io/t/optional-shortcode-parameters-conditional-variables-assignment/) in the forum, I'm opening a bug here.

Currently in Hugo v0.38, when dealing with shortcodes, you can ``.Get`` a missing [named parameter](https://gohugo.io/templates/shortcode-templates/#positional-vs-named-parameters), but not a missing positional parameter.

The former will return an empty string, which integrates perfectly with `with`, `if` or `cond`. The latter will produce errors like so:

> ERROR 2018/03/28 14:51:23 No shortcode param at .Get 1 in page posts/2018/01/projection-de-conquerir-notre-9346.fr.md, have params: [BXv4Txr9CYU]

Like i said on the forum:

> I think the problem is that named parameters when queried by .Get return "" if they don’t exist, while positional parameters [raise an error instantly](https://github.com/gohugoio/hugo/blob/aa6b1b9be7c9d7322333893b642aaf8c7a5f2c2e/hugolib/shortcode.go#L89).

Adressing this issue by returning an empty string when a positional parameter is missing woud allow us to write code like so to handle parameters:

```
{{ $width := cond (gt (len .Params) 1) (.Get 1) "512" }}
```

I'll try to submit a PR soon :)

**Comment by paulcmal** [comment]
I was investigating the tests, and i stumbled upon [TestNestedNamedMissingParam](https://github.com/gohugoio/hugo/blob/master/hugolib/shortcode_test.go#L170). I assumed `{{% div2 %}}d2{{% /div2 %}}` would produce an error because of a missing param, as the shortcode looks like this: 

```
<div {{with .Get 0}} class="{{ . }}"{{ end }}>
```

However, `.Get` always [returns nil](https://github.com/gohugoio/hugo/blob/master/hugolib/shortcode.go#L76) when no params are passed (params length 0). But when it comes to named parameters, [`""` is returned](https://github.com/gohugoio/hugo/blob/master/hugolib/shortcode.go#L98) when a key is missing

Shouldn't these behaviours be harmonized, as they both indicate a missing param?

**Comment by bep** [comment]
>Shouldn't these behaviours be harmonized, as they both indicate a missing param?

I'm no sure I follow. Which test case _fails_ that you mean should pass?

**Comment by paulcmal** [comment]
I'm working on a PR at the moment.

I stumbled upon [this discussion](https://discourse.gohugo.io/t/testing-for-optional-shortocde-parameters-isset-and-with-errors/) in the forums:

> However, when the id parameter is explicitly set to an empty string in the shortcode call (id="") the else clause is executed (the same as when id is not passed at all), unlike what you would expect for an isset condition.

So i would be inclined to return `nil` specifically, but from what i read of the `isset` implementation, this would not address the point that person made. Am i correct to think that both `nil` and `""`'s reflect.IsValid return false and therefore cannot be distinguished on the template side? At the moment I'll go with returning `""` like with named parameters.
