### ISSUE TITLE
Add Resource.Content

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4622]
Which in most cases (JSON etc.) will be a `String`. `Page` already has this, and it is of type `template.HTML`. 

The current workaround for this is, for the non-page resources, I suppose, doing `Readfile`, which does not look too pretty, and it may be hard to get the paths correct. 

One question: Anyone know about a current use case for doing `$image.Content`?

/cc @kaushalmodi @moorereason @regisphilibert and gang

**Comment by regisphilibert** [comment]
Just making sure I understand this feature.

It is the addition of a .Content property on the resource object which evaluates its content no matter its type.

(So we don’t have to identify its type in order to know which property to call to output its content)

**Comment by regisphilibert** [comment]
> One question: Anyone know about a current use case for doing $image.Content?

For svg yes. An easy way to include it inline.

**Comment by RealOrangeOne** [comment]
> One question: Anyone know about a current use case for doing $image.Content?

A potential use for this is to base64 encode it for the `src` attribute. As https://en.wikipedia.org/wiki/Data_URI_scheme describes. However perhaps this is out of scope for this feature?

**Comment by regisphilibert** [comment]
Does this mean you would have to pick a scenario for any file main type or sub type ?

Because JSON and PDF for example could not really behave the same and yet they share the same main type ?

I wonder what kind of fallback could be used as .Content which clearly could not present any. ’nil’ ?

**Comment by bep** [comment]
>Because JSON and PDF for example could not really behave the same and yet they share the same main type ?

I suspect that you complicate this more than needed.

Both `JSON` and `PDF` can be represented as a set of bytes. No problem there. You will have to use this as you see fit, this is not a "content viewer"; that is what the browser and `RelPermalink` is for.

This is for some rare use cases where you want to display content inline. Code examples from files and similar.

**Comment by bep** [comment]
That said, we could probably add the full media type to `Resource` as well, but you should create a separate issue for that and provide a use case.

**Comment by regisphilibert** [comment]
> I suspect that you complicate this more than needed.

I often do.

> Both JSON and PDF can be represented as a set of bytes.

But their `.Content` output will still be different. I'm just trying to understand what will happen if I call `.Content` on an application file other than JSON.

- (application/json Resource).Content => outputs a json string
- (application/pdf Resource).Content => outputs a set of bytes ?

**Comment by bep** [comment]
>But their .Content output will still be different.

I would say that there should be no surprises.

How I currently see it it is:

* Page => `template.HTML`
* All (current) others are `String`

So, `template.HTML` is just a special Go string marker type that tells the template parser not to do magical escaping.

So, getting `JSON` and all the images as a `string` is what you do today when you do `readFile` and is also what `base64` and other relevant funcs expects.

So the use case of @RealOrangeOne would just work, I think:

```bash
src="{{ (.Resources.GetMatch "mylogo.png").Content | base64Encode }}
```

I cannot think of any example where a `[]byte` slice would be useful, and if so, we should add a `bytes` template func to do the conversion.
