### ISSUE TITLE
Add MediaType (of type media.Type) to Resource

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#4625]
For now, the only information about the MIME type of a resource is its main type (stored in `.Type`). 

Which means, there is no conventional way to test if a file is `application/json` or `application/pdf` as both file will return a `.Type` of `application`, same goes for `image/png` or `image/svg+xml`.

In many cases the user will want to properly test a file subtype before using a method only available for such file. 
For ex: `{{ range .Resources.ByType "image" }}` may include file of MIME type `image/svg+xml` on which the `.Resize` method is not available.

Note: I'm afraid simply passing the full MIME type to `.Type` could be a code breaker at this point.

**Comment by bep** [comment]
Fixed in dea71670c059ab4d5a42bd22503f18c087dd22d4
