### ISSUE TITLE
Make .Content (almost) always available in shortcodes

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4632]
The timing issues here is esp. visible now with shortcodes and `.Site.GetPage`. There are chicken and egg situations, so perfect is hard. But we should do better.

**Comment by bep** [comment]
Will take another stab at this.

**Comment by bep** [comment]
@moorereason @anthonyfok @digitalcraftsman @kaushalmodi @regisphilibert and gang: Can you chime in with your clever minds if you have time. This is a fix you are going to like; I should have done this long time ago, but I have not been hit with this issue until now.

I have created a very confusing test section on my test site:
https://github.com/bep/hugotest/commit/6e7462650801f3044c0b0d69b0fe16949ebb89b5
http://hugotest.bep.is/scodes/

It is easier to explain:

* Before this, using `.Content` (and content derived methods) from content pages found via `.GetPage` and similar had an undefined behaviour. Or: It seemed to work sometimes, but not really.
* After this PR: All `.Content` is available **except the content the shortcode itself lives in.** The last point is impossible (please prove me wrong) to solve ...

Benchmarks show "as fast" as before, but there are potential wins if we look closer here, esp. for situations where you don't use the content. But I might delay that until later.

I plan to get this out sooner (Monday) rather than later, so any "no, this looks funky" would be good. We can take it into master tomorrow for people to take it for a spin.

**Comment by moorereason** [comment]
Took a quick peek.  :heart:

What happens if `p1.md` contains `{{< bundle-content "section" "scodes" "p1" >}}`?  Does it behave like `{{< current-page >}}`?

The ToC works from a shortcode but clearly doesn't contain entries from the shortcode output.  Would the ToC contain the full list of entries if used from a normal page template (ie. not in a shortcode)?

**Comment by bep** [comment]
I see that I have commented on the issue, not the PR that lives here:

https://github.com/gohugoio/hugo/pull/4651

**Comment by bep** [comment]
There are some potential data races and I also need to pull out the ToC logic; there was a logical flaw in that. But other than that this looks god.

**Comment by regisphilibert** [comment]
Never investigated shortcode vs `.md`this much, but this will become very important when people decide to use resources of type `Page` to build sections on their page (and call such sections using shortcodes). 
At this point, shortcode will have to behave nicely with the page bundle's `.md` so it's great you're addressing this.
