### ISSUE TITLE
Live-reload does not work when editing layout files AND baseURL has subdir AND fast rendering enabled

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4634]
Hello,

When the baseURL has a subdir (e.g. `https://example.com/foo/`), editing the layout files doesn't cause the live-reload feature to update the page, with the default "fast rendering enabled" state.

I do see that `hugo` is detecting the change in the layout as I see an update like this in the terminal:

```
Change detected, rebuilding site
2018-04-16 10:49:31.223 -0400
Template changed "/home/kmodi/sandbox/hugo/sandbox/subdir-canonify-true/layouts/_default/single.html": WRITE
Total in 15 ms
```

Also I see the page refresh when I edit that layout file, but the actual change is **not** reflected in the browser.

If I kill the server and restart it.. the change is reflected in the HTML/

### Steps to reproduce

1. `git clone https://gitlab.com/kaushalmodi/hugo-sandbox-subdir-canonify-true`
2. `hugo server -p 6767 -b localhost/foo/ --navigateToChanged `
3. Open `http://localhost:6767/foo/posts/post-1/` in your browser.. that page should show up fine.
4. Open the `layouts/_default/single.html` layout file from the cloned repo.
5. Edit the layout file.. for example, add `<p>foo</p>` to the `define "extra"` block:

```
{{ define "extra" }}
<p>foo</p>                               ------------------ This
<p>
    <code>single.html</code> layout
</p>
<p>
    {{ .Content }}
</p>
{{ end }}
```

6. You will see the `hugo server` reflect that this change happened, the browser will refresh.. but still that "foo" paragraph will not appear near the bottom of the page in the browser.
7. Killing and restarting the server, and then refreshing the browser will make that show up.

### Live reload working status when editing the **layout file**

| Live Reload works?        | baseURL contains subdir?       | Fast Rendering enabled?  | Example command |
| ------------- | ------------- | ----- | ----- |
| NO      | **Yes** | **Yes** | `hugo server -p 6767 -b localhost/foo/ --navigateToChanged` |
| Yes      | Yes | No | `hugo server -p 6767 -b localhost/foo/ --navigateToChanged --disableFastRender` |
| Yes      | No | Yes | `hugo server -p 6767 -b localhost --navigateToChanged` |
| Yes      | No | No | `hugo server -p 6767 -b localhost --navigateToChanged --disableFastRender` |

**Comment by bep** [comment]
Why do you need a sub-dir in server mode?

**Comment by kaushalmodi** [comment]
I need to test if the site with deployed on a sub-dir will have all the links working correctly. I was burned by the absURL/relURL issue was was discussed recently in the discourse thread.. the link would be fine on localhost without subdir, but would break when the actual baseURL for deploying had subdir.

**Comment by kaushalmodi** [comment]
@bep can you please remove stale tag from this?

**Comment by divinerites** [comment]
Digging this old post (bited me again) ...

Easy workaround (_thanks to [Bep comment](https://github.com/gohugoio/hugo/issues/4634#issuecomment-381688772)_) is to :

- keep your baseURL with folders
- run hugo with basic baseURL : `hugo server --navigateToChanged --baseURL "http://localhost:1313"`

HTH

**Comment by sth** [comment]
With race detector enabled (`mage hugoRace`) I get the following:

```
Change detected, rebuilding site.
2020-01-02 13:36:37.762 +0100
==================
WARNING: DATA RACE
Write at 0x00c0005c51c8 by goroutine 27:
  github.com/gohugoio/hugo/commands.(*commandeer).rebuildSites()
      /home/sth/devel/hugo/commands/hugo.go:722 +0xcb
  github.com/gohugoio/hugo/commands.(*commandeer).handleEvents()
      /home/sth/devel/hugo/commands/hugo.go:1094 +0xb5e
  github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1()
      /home/sth/devel/hugo/commands/hugo.go:841 +0x2fb

Previous read at 0x00c0005c51c8 by goroutine 51:
  github.com/gohugoio/hugo/commands.(*fileServer).createEndpoint.func1.1()
      /home/sth/devel/hugo/commands/server.go:358 +0x678
  net/http.HandlerFunc.ServeHTTP()
      /usr/lib/go-1.12/src/net/http/server.go:1995 +0x51
  net/http.StripPrefix.func1()
      /usr/lib/go-1.12/src/net/http/server.go:2034 +0x362
  net/http.HandlerFunc.ServeHTTP()
      /usr/lib/go-1.12/src/net/http/server.go:1995 +0x51
  net/http.(*ServeMux).ServeHTTP()
      /usr/lib/go-1.12/src/net/http/server.go:2375 +0x28a
  net/http.serverHandler.ServeHTTP()
      /usr/lib/go-1.12/src/net/http/server.go:2774 +0xce
  net/http.(*conn).serve()
      /usr/lib/go-1.12/src/net/http/server.go:1878 +0x811

Goroutine 27 (running) created at:
  github.com/gohugoio/hugo/commands.(*commandeer).newWatcher()
      /home/sth/devel/hugo/commands/hugo.go:837 +0x3c7
  github.com/gohugoio/hugo/commands.(*serverCmd).server()
      /home/sth/devel/hugo/commands/server.go:264 +0x634
  github.com/gohugoio/hugo/commands.(*serverCmd).server-fm()
      /home/sth/devel/hugo/commands/server.go:131 +0x6d
  github.com/spf13/cobra.(*Command).execute()
      /home/sth/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20190321000552-67fc4837d267/command.go:762 +0x527
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/sth/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20190321000552-67fc4837d267/command.go:850 +0x41b
  github.com/gohugoio/hugo/commands.Execute()
      /home/sth/devel/hugo/commands/hugo.go:89 +0x187
  main.main()
      /home/sth/devel/hugo/main.go:23 +0x87

Goroutine 51 (running) created at:
  net/http.(*Server).Serve()
      /usr/lib/go-1.12/src/net/http/server.go:2884 +0x4c4
  net/http.(*Server).ListenAndServe()
      /usr/lib/go-1.12/src/net/http/server.go:2797 +0x15e
  github.com/gohugoio/hugo/commands.(*commandeer).serve.func1()
      /usr/lib/go-1.12/src/net/http/server.go:3037 +0xfc
==================
Template changed "/home/sth/devel/hugo/hugo-sandbox-subdir-canonify-true/layouts/_default/single.html": WRITE
```

**Comment by jmooring** [comment]
Closing in favor of https://github.com/gohugoio/hugo/issues/10571.
