### ISSUE TITLE
Importing a html link containing polymer component take more time than creating a entire webite

### ISSUE THREAD

**Issue by kbhutiya** [gohugoio/hugo#4635]
I am trying to import a polymer web component in a markdown file and i wanted to import a html file for that,but looked like web component cant work with hugo!Any help will be appreciated!

**Comment by kaushalmodi** [comment]
Please take this to the Hugo Discourse forum: https://discourse.gohugo.io/.

The Issues in this repo are not for support Q&A. Also, when you post on Discourse, you need to post your site source and explain you problem in detail: polymer component? more time than creating entire website? How much times are each? How can anyone on the forum reproduce the exact issue you are seeing?

**Comment by kbhutiya** [comment]
For a starter,
Its an issue which i formally represented as a question!
If you have to create a shortcode for just importing a simple Html file inside a markdown file to load a polymer component ,its def a waste of time!
Doesn’t matter what way u take it!
