### ISSUE TITLE
Allow references to index.md in offline mode 

### ISSUE THREAD

**Issue by kpietak** [gohugoio/hugo#4642]
In offline mode, when the site is working without a web server (for example distributed in ZIP file as documentation or training materials), links to `index.md` files are not working as excepted.  When I have a reference to `index.md`, Hugo  generates links to folder names containing the index file, instead of `index.html` files. For example when I have a page called `chapter/index.md` and have reference to it, Hugo generates links to `/chapter1/` instead of `/chapter1/index.html`.

This is fine when I have a web server, but in offline mode, when the page is open from local file system, the link leads to a directory listing instead of proper page.

The problem was discussed in the [Hugo discussion thread](https://discourse.gohugo.io/t/link-to-index-md-doesnt-work/9356) and [hugo-learn-theme issue](https://github.com/matcornic/hugo-theme-learn/issues/91).

**Comment by rgommers** [comment]
https://discourse.gohugo.io/t/could-not-get-relativeurls-to-work-with-site-baseurl/5301/12 and https://discourse.gohugo.io/t/canonifyurls-relativeurls-interaction/5448 seem related as well. 

After a lot of digging around, this seems to be the way to get a portable bundle of html:
1. Do not set `baseURL`
2. Set `relativeURLs = "true"`
3. Set `uglyURLs = "true"`.

(3) fixes this particular issue, it looks like it just needs documenting. I've tried with the `hugo-learn-theme` example site and with my own; all seems to be fine. @kpietak can you confirm that?

**Comment by pgundlach** [comment]
For me this doesn't work. See the following example (in `layouts/index.html`) :

```html
<!DOCTYPE html>
<html>
<head>
	<title>a title</title>
</head>
<body>
<h1>index.html</h1>

{{ .Content }}

{{ with .Site.GetPage "home" }}{{ .RelPermalink }}{{ end}}

</body>
</html>
```

The link returns `/` instead of `index.html` 

This is the config.toml:

```
languageCode = "en-us"
title = "My New Hugo Site"


uglyURLs = "true"
relativeURLs = "true"
```

**Comment by kpietak** [comment]
@rgommers I confirm that with the 3 settings listed by you, the `hugo-learn-theme` works fine. Thanks! 

The learn theme generates files with the same name as source (markdown) files (e.g. hello-world.md -> hello-world.html) instead of index.html files, so actually I didn't checked the case mentioned by @pgundlach. Maybe someone who is more experienced could check and explain it.

**Comment by pgundlach** [comment]
@moorereason Was closing this issue a deliberate choice? The problem still persists, it is not possible to link to the home page with `{{ .RelPermalink }}`. I have tried with the newest version of Hugo (0.47.1/extended) from Homebrew on my Mac. I am refering to my comment at https://github.com/gohugoio/hugo/issues/4642#issuecomment-384210690. I am asking because you have set the `keep` tag, perhaps closing was a mistake.
