### ISSUE TITLE
.Content vs .Page vs .Resource vs Shortcodes

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4645]
There is currently some dependency issue between shortcodes and the page content in page bundles loaded via .Site.GetPage (i.e. from _other pages_). There is a chicken and egg situation there, but it should be possible to improve it ... some.

A workaround for Markdown resources inside a bundle would be to name it something "not a Markdown file and do)

```bash
{{ ( .GetMatch "mymarkdown.txt ).Content | markdownify }}
```

You will not get shortodes ... But better than nothing. 

/cc @kaushalmodi @regisphilibert and gang

**Comment by regisphilibert** [comment]
I'm confused about the statement.

Is it:

1. This is not currently possible to get a Page Bundle's Resource of `ResourceType` page from a shortcode  using `.GetPage` **or**
2. This is not possible to interpret shortcodes lodged within a Resource of `ResourceType`page grabbed using `.GetPage`.

> You will not get shortodes ... But better than nothing.

Even more confused now :)

**Comment by bep** [comment]
I'm a little bit confused by your question ...

But this is related to the fix in #4632 -- and maybe this is now superfluous, but ... Before that was a little hit-and-miss (concurrency), now at least the rules are well defined. You can still obviously not show content in shortcode from the content page where the shortcode lives ...

The thing is, we have reserved the "*.md" suffix and some others to identify content files, which have some special meaning in Hugo (can have shortcodes etc.). There are no current way to mark a "*.md" file as ... something else.

**Comment by bep** [comment]
I have added two commits that improve this situation. This is all about content files (be it resources or not) in combo with shortcodes.

**Since shortcodes are rendered in content, there is a dependency here that can never be perfect.**  But Hugo's approach to "the behaviour when using .Content from Page  in shortcodes is undefined" isn't really good enough once we start to really use the bundling. Note that this is not a problem for `.Content` in the _other resource types_. Just the Blackfriday/shortcode types. And it is not an issue in regular templates. Just shortcodes.

So with the current master you can safely in a shortcode do `(.Site.GetPage "page" "...").Content` provided the page lives in a "processing group" before the current:

1. Headless bundles
2. Leaf bundles
3. Regular non-bundle pages
4. Branch bundles

I have also made sure that child resources are "content rendered" before its parent, to make sure that they are available in the parent's shortcode.

**Comment by bep** [comment]
That said,

I'm considering adding a way for the user to override above order -- so he/she can mark certain bundles as important ...

**Comment by bep** [comment]
Of course, writing the above and 1 hour on the saxophone got me a better idea (the rubber duck) ... This is a `Page.Content` problem in the shortcodes. So lazy render on demand should do the trick ... I will reopen the other issue.

**Comment by regisphilibert** [comment]
![](https://i.imgur.com/AzuoWUX.gif)
