### ISSUE TITLE
Site build fails if theme uses data/ in theme dir, but theme set using CLI instead of in config

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4649]
The failure happens when:

1. The `data/` file is present in the theme dir
2. Index of that data map is specified in the `config.toml` **of the theme**.
3. `theme` is **not** set in the site's config.toml, but is instead passed through the `-t` flag.

The build works as soon as the point 3 above is changed to:

- Set the `theme` in the site's config.toml instead of passing it via `-t`.

### Steps to reproduce

1. `git clone https://gitlab.com/kaushalmodi/hugo-throwaway-3`
2. `cd hugo-throwaway-3`
3. `hugo -t test-theme`

You will see this error:

> Building sites … ERROR 2018/04/19 12:30:04 Error while rendering "home" in "": template: theme/index.html:7:3: executing "theme/index.html" at <index .Site.Data.foo...>: error calling index: value is nil; should be of type string

### Now set the theme in config instead of via `-t`

1. `echo 'theme = "test-theme"' >> config.toml`
2. `hugo` *(Note that now the theme is not set on command line)*

You will get:

```
                   | EN
+------------------+----+
  Pages            |  4
  Paginator pages  |  0
  Non-page files   |  0
  Static files     |  0
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0
```

### Some debug

The error occurs when an element in the theme's data is accessed using a param set in the **theme's config.toml**. 

So this works: 

```
{{ index .Site.Data.foo "one" }}
```

but this doesn't (**only when setting theme via `-t`**):

```
{{ index .Site.Data.foo (.Param "sel") }}
```

(From the demo site's [`index.html`][1])

---

Hugo version: Hugo Static Site Generator v0.40-DEV-74520D2C

---

/cc @paskal

[1]: https://gitlab.com/kaushalmodi/hugo-throwaway-3/blob/master/themes/test-theme/layouts/index.html

**Comment by kaushalmodi** [comment]
I've verified this bug to exist on 0.38.2 too. So this doesn't have anything to do with the CLI cleanup in 0.39.

**Comment by nonumeros** [comment]
I only get this error is by omitting the params value on the site config file, else is not there (0.40.3)

**Comment by funkydan2** [comment]
I'm not sure if this is the same issue, but I'm having trouble with Hugo not parsing files in my theme's data directory.

For me, this error is a regression in a recent version, first noticed in 42.1

# Steps to reproduce
1. Clone `https://github.com/funkydan2/alpha-church`
2. Run `hugo server` from the exampleSite directory
3. The site appears to build, but viewing `localhost:1313` in a browser displays errors in the data console where hugo hasn't inserted data from libs.toml
4. However, if you copy libs.toml from the theme data directory to the data directory in exampleSite, the site builds and works correctly.

@kaushalmodi, I don't know if my bug is related, but it sounded similar enough. I'll open a new issue is you think it's not the same thing.

**Comment by dzello** [comment]
Having the same issue as @funkydan2 here, first noticed in 0.42 (0.3x works fine).

I can reproduce it by running the [reveal-hugo exampleSite](https://github.com/dzello/reveal-hugo/tree/master/exampleSite). `Site.Data` is empty instead of having values from `../data/reveal_hugo.toml` (`../` points to the theme, one directory up from `exampleSite`).

**Comment by funkydan2** [comment]
For me, the problem appears to be fixed by getting the `themesDir` and `theme` variables set correctly in `config.toml`.

For more info, see https://github.com/gohugoio/hugo/issues/5061

**Comment by kaushalmodi** [comment]
@bep

I confirm this bug on Hugo 0.54-DEV too. Following the exact same recipe from above, I get the below with `hugo -t test-theme`:

> Error: Error building site: failed to render pages: render of "home" failed: "/home/kmodi/sandbox/hugo/hugo-throwaway-3/themes/test-theme/layouts/index.html:7:3": execute of template failed: template: index.html:7:3: executing "index.html" at <index .Site.Data.foo...>: error calling index: value is nil; should be of type string
