### ISSUE TITLE
partial JS with safeJS and for-loop breaks

### ISSUE THREAD

**Issue by qw3ry** [gohugoio/hugo#4661]
I have an issue with some code like `{{ partial "js/code.js" . | safeJS }}`.
The following for-loop has escaped html sequences in it:
```
for(var i = 0; i < numNodes; i++) {
  // some calculations
}
```
gets converted to
```
for(var i = 0; i &lt; numNodes; i++) {
  // some calculations
}
```
(note the `&lt;` in the loop head)

As far as I understand this is not intended behaviour.
This is with hugo 0.39 on archlinux.
I can work around this with `{{ partial "js/code.js" . | htmlUnescape | safeJS }}`

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
