### ISSUE TITLE
With "uglyURLs = true" parts of file name is stripped

### ISSUE THREAD

**Issue by pgundlach** [gohugoio/hugo#4666]
`hugo version`:
`Hugo Static Site Generator v0.40 darwin/amd64 BuildDate: `

I have a page called `foo-makeindex.md` and I try to link to it with `{{ ref . "foo-makeindex.md" }}`. The file name is stripped to `foo-make` (the part `index.html` gets removed) and thus creating a broken link.

I have put all the files in a repository to re-create the issue:  https://github.com/pgundlach/hugoexampleindexhtml

This is the `config.toml`:

    baseURL = "http://example.org/"
    languageCode = "en-us"
    title = "My New Hugo Site"
    
    
    uglyURLs = true
    
This is the `index.html` in `layouts`

```html
<!DOCTYPE html>
<html>
<head>
	<title>a title</title>
</head>
<body>
<h1>index.html</h1>
{{ ref . "foo-makeindex.md" }}
</body>
</html>
```

And this is the result after calling `hugo`:

```html
<!DOCTYPE html>
<html>
<head>
	<meta name="generator" content="Hugo 0.40" />
	<title>a title</title>
</head>
<body>
<h1>index.html</h1>
http://example.org/foo-make
</body>
</html>
```

I would expect the link goes to `http://example.org/foo-makeindex.html`

**Comment by kaushalmodi** [comment]
@bep This looks like a bug. Can you remove the stale tag?
