### ISSUE TITLE
Does hugo support multiple version of docs site

### ISSUE THREAD

**Issue by LakshmiMekala** [gohugoio/hugo#4670]
I am currently making a documentation site using github docs and hugo. I would like to have subfolder in URL for different versions

when i access -> username.github.io/reponame, can i have option to change version i.e., assume i have 2 or more versions, say 0.1v and 0.2v of my releases and i want to have the docs site to have 0.1v, 0.2v versions and i should be able to switch versions using hugo. Is this possible? If yes, could you please let me know the steps.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
