### ISSUE TITLE
.WordCount, .FuzzyWordCount, .ReadingTime is not set on posts with <!--more-->

### ISSUE THREAD

**Issue by timshannon** [gohugoio/hugo#4675]
I recently updated from version .31 to .40.1 (using the pre-compiled deb file in the release), and now some of my older posts have 0 minute read times.

You can see it here: http://tech.townsourced.com/

And here is the line where I'm very simply calling the {{.ReadingTime}} variable in my template:

https://github.com/timshannon/tech.townsourced.com/blob/241eb6763d1708418f2274c8b03c8d3d09c4a5a7/layouts/post/single.html#L16

Not sure why it's working on my newer posts and not my older ones. 

Let me know if there is any additional info I can provide.

**Comment by bep** [comment]
OK, I have reproduced this:

* When you use  then
* .WordCount, .FuzzyWordCount, .ReadingTime is always 0.

Note that all the other fields (PlainWords, Plain, Content) are set correctly in both scenarios. So this is the word stats.

**Comment by dinis-rodrigues** [comment]
@bep Love you

**Comment by dinis-rodrigues** [comment]
> OK, I have reproduced this:
> 
> * When you use `<!--more-->` then
> * .WordCount, .FuzzyWordCount, .ReadingTime is always 0.
> 
> Note that all the other related fields (PlainWords, Plain, Content) are set correctly in both scenarios. So this is the word stats.

Is this fix, implemented by now?
