### ISSUE TITLE
hugo server reload issue

### ISSUE THREAD

**Issue by lincryption** [gohugoio/hugo#4676]
(May be Google Chrome issue)
Files which are used by `hugo server` are somehow cached. Sometimes during building `hugo server` uses old cached files instead of new.

In my case, `static\css\styles.css` did not reload. The server used old cached styles (html always  reloaded as expected and was up to date). At the same time, `hugo` worked as expected so `public\css\styles.css` was up to date.

**To replicate:**
1) Run `hugo server`, then Ctrl+C
2) Edit css file (for example, change font)
3) Run `hugo server`
4) Styles remain the same as before

"Clear storage" via Chrome developer tools and multiple rebuildings with `hugo server --disableFastRender` did not solve the issue.

Solved by editing css file while `hugo server` was running.

Hugo v0.40
https://github.com/lincryption/delta-hugo
Windows 10 Enterprise Version 10.0.16299 Build 16299
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by rammygit** [comment]
I dont see this issue in my site. 
Checked in chrome, firefox and safari. Could not replicate this issue. I am able to see the font changes following your steps.
