### ISSUE TITLE
Highlight YAML issue

### ISSUE THREAD

**Issue by ahmetb** [gohugoio/hugo#4687]
I am seeing different behavior between Hugo v0.38.2 and v0.40.0 (and v0.40.2).

I have a fairly simple `layouts/shortcodes/b.html` that makes things bold (trimmed \n at the end of this file):

    <strong>{{.Inner}}</strong>

I have these 3 code fences in my content (yaml, sh, and _unspecified_):

    ```yaml
    kind: {{<b>}}Service{{</b>}}
    ```

    ```sh
    kind: {{<b>}}Service{{</b>}}
    ```

    ```
    kind: {{<b>}}Service{{</b>}}
    ```

With 0.40.0, the contents of `{{<b>}}` (or any other shortcode) simply does not work **on the `yaml` code fence** (other examples work fine). Output with 0.40.0:

![image](https://user-images.githubusercontent.com/159209/39445153-ee1c0d5c-4c6e-11e8-9afa-afefdd83fb78.png)

Output HTML (note the contents of the shortcode is entirely missing on first div): 
```

<div class="highlight"><pre class="chroma"><code class="language-yaml" data-lang="yaml">kind<span class="p">:</span><span class="w"> </span></code></pre></div>

<div class="highlight"><pre class="chroma"><code class="language-sh" data-lang="sh">kind: <strong>Service</strong></code></pre></div>

<div class="highlight"><pre class="chroma">kind: <strong>Service</strong></pre></div>
```

When I go back to v0.38.2, everything works fine as expected. (Platform: macOS):
![image](https://user-images.githubusercontent.com/159209/39445113-ce321982-4c6e-11e8-94f8-e0e34c4da90a.png)

**Comment by ahmetb** [comment]
Can confirm it's broken on v0.40.2 as well (released 12h ago).

**Comment by bep** [comment]
Looks like the Chroma YAML lexer is doing something funky here. 

Maybe this:

https://github.com/alecthomas/chroma/commit/50a6b50a3b3c289126b04d14ba7e09caf5f476de

It would be good if you could raise an issue on that tracker.

Note that Chroma will receive `<strong>Service</strong>`  and not your shortcode syntax.

**Comment by ahmetb** [comment]
Thanks, reported upstream.

**Comment by moorereason** [comment]
@ahmetb, I'm not able to reproduce this with latest Hugo.  Can you test this scenario again?

**Comment by ahmetb** [comment]
Can't repro in Hugo v0.47/extended anymore.

**Comment by moorereason** [comment]
@ahmetb, please close your upstream issue, too.
