### ISSUE TITLE
Concurrent map writes

### ISSUE THREAD

**Issue by kamilsk** [gohugoio/hugo#4688]
I updated from 0.38.x version to 0.40.2 and have an unstable behavior of Hugo related to concurrent map writes.

Head of stack trace:

```
fatal error: concurrent map writes

goroutine 234 [running]:
runtime.throw(0x1a8633b, 0x15)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:616 +0x81 fp=0xc425715b68 sp=0xc425715b48 pc=0x102bc71
runtime.mapassign_faststr(0x1958640, 0xc4247f2030, 0xc425f61e90, 0x25, 0xc425a21728)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/hashmap_fast.go:779 +0x3ce fp=0xc425715bd8 sp=0xc425715b68 pc=0x100d56e
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).executeShortcodesForDelta(0xc424136cd0, 0xc421c7d7d0, 0x1b, 0xc4205fb598)
	/private/tmp/hugo-20180430-20259-7wnvbf/hugo-0.40.2/src/github.com/gohugoio/hugo/hugolib/shortcode.go:441 +0x17a fp=0xc425715ce0 sp=0xc425715bd8 pc=0x181c27a
```

The problem located here https://github.com/gohugoio/hugo/blob/master/hugolib/shortcode.go#L441

How can I help to fix that without deep diving into the codebase?

**Comment by bep** [comment]
>How can I help to fix that without deep diving into the codebase?

You can help reproducing it. Do you have a link to a repository? I see where it fails, and could probably fix it by some mutex, but it would be nice to reproduce the error first. I have tested plenty of sites without seeing this error.

**Comment by kamilsk** [comment]
> You can help reproducing it

Yep, I am working on it now.

> Do you have a link to a repository?

Unfortunately, it is my private bitbucket repo of personal site. Maybe is it related to not so small shortcodes I have?

```
5.2K - octolab-april-2018.ru.html
4.5K - octolab-february-2018-result.ru.html
3.3K - octolab-february-2018.ru.html
8.5K - octolab-march-2018-result.ru.html
5.6K - octolab-march-2018.ru.html
...
 10K - octolab-january-2018.ru.html
6.3K - octolab-march-2018.ru.html
```

**Comment by kamilsk** [comment]
```bash
$ hugo version
Hugo Static Site Generator v0.40.2-5A9D1324 darwin/amd64 BuildDate: 2018-04-30T23:07:08+0300
```

I built hugo with `-race` flag and have the next data race

```
WARNING: DATA RACE
Read at 0x00c4202849f0 by goroutine 26:
  github.com/gohugoio/hugo/hugolib.(*Page).Render()
      /Users/kamilsk/Development/go/src/github.com/gohugoio/hugo/hugolib/page_output.go:163
...
Previous write at 0x00c4202849f0 by goroutine 31:
  github.com/gohugoio/hugo/hugolib.pageRenderer()
      /Users/kamilsk/Development/go/src/github.com/gohugoio/hugo/hugolib/site_render.go:102
```

**Comment by bep** [comment]
>Unfortunately, it is my private bitbucket repo of personal site. Maybe is it related to not so small shortcodes I have?

>5.2K - octolab-april-2018.ru.html
>4.5K - octolab-february-2018-result

What does the above numbers mean?

**Comment by bep** [comment]
Also, the data race report is not useful without the full report.

**Comment by kamilsk** [comment]
> What does the above numbers mean?

the size in kilobytes

**Comment by kamilsk** [comment]
> Also, the data race report is not useful without the full report.

attached [datarace.log.zip](https://github.com/gohugoio/hugo/files/1963223/datarace.log.zip)

**Comment by kamilsk** [comment]
full log of concurrent map writes [map-corruption.log.zip](https://github.com/gohugoio/hugo/files/1963371/map-corruption.log.zip)

**Comment by moorereason** [comment]
@kamilsk,
Can you provide a minimal example site that triggers this race condition?

**Comment by kamilsk** [comment]
@moorereason, it is difficult to reproduce from scratch. I suggest closing this issue.
