### ISSUE TITLE
Allow shortcode content to be processed by Blackfriday etc.

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4695]
I think the hardest part about this issue is to create an API that is both simple and not in conflict with what people use in the wild.

Currently, we have:

1. `{{% myshortcode %}}` which renders the inner content as markdown. This is the orignal Hugo syntax.
2. `{{< myshortcode >}}` Hugo does nothing to the inner content. This is the most useful, as shortcodes are built for creating inline HTML snippets, and Blackfriday have a tendency to do odd thing to those.

The common thing with the above is that Blackfriday (or Asciidoctor etc.) will never see the rendered shortcode content. We create temporary shortcode placeholders that plays nicely with Blackfriday. This is almost always what you (or I) want, as you can use any HTML constructs and not have to worry about it getting trapped in Blackfriday's smartypants filter etc. In the first versions of Hugo we did it the "other way", and people had all sorts of trouble.

But there are obvious use cases where you want your shortcodes to be part of the markdown files as rendered by Blackfriday. The most obvious is the inclusion of raw markdown data (e.g. from a page: `(Site.GetPage ...).RawContent)`. What you would do today is typically to use `.Content` (already rendered) or `readFile "somefile" | markdownify`, but that content will not participate in the "global context" with table of contents numbering etc.

I think this will be even more useful once we get time set aside to do the Blackfriday v2, where one of the planned benefits is to provide a proper data structure for the ToC for you to present in any way you want (and get rid of the hard-to-style HTML we have today).

So, 

* In my head it should not be too hard to implement.
* But we need a way to "mark a shortcode" to behave "like this". This should probably be in the shortcode definition? As opposed to when you use it?
* So, if we give this thing the keyword name "foo" then we could do ... `{{< myshortcode h-foo "other params" >}}` or maybe `layouts/shortcodes/myshortcode.foo.html`... 

Not pretty ... I don't want to add another delimiter for this unless I really have to.

**Comment by moorereason** [comment]
I know you said you don't want to, but the most intuitive option to me is to use a different action/behavior modifier.

```
{{# myshortcode #}}
```

**Comment by bep** [comment]
@moorereason for this fundamental case you are probably right ... Why the "#"?

**Comment by moorereason** [comment]
I made it up.  Makes me think of Markdown titles.

**Comment by regisphilibert** [comment]
I just realized the difference between the existing delimiters...

I'd like to stress the facts that the "editors", very much unfamiliar with Hugo templating and shortcode limitations, may already have a hard time remembering the difference in usage of both delimiters. 

I suspect (but I may be wrong) that only the programmer will need to be aware of this third variation. So I would suggest we leave the editors out of it and don't add a third delimiter.

I would push for the use the template file naming suggested by @bep (`myshortcode.foo.html`) but since https://github.com/gohugoio/hugo/pull/3434 we already use the file naming for Output Formats, woudn't this lead to potential conflicts?

**Comment by moorereason** [comment]
@bep,
I took another look at this today. I may be backing off of my previous suggestion, but I need some clarification on this proposal.

Here's what I take your proposal to be:

1. The HTML-shortcodes (`{{< >}}`) are **out of scope** for this proposal.
1. The markdown-shortcodes (`{{% %}}`) are **in scope** for this proposal.
1. Allow shortcode output to effect the BF Table of Contents.
1. Allow the full, after-shortcode-rendering Markdown be visible in `.RawContent`.

**Shortcode**
```md
## mysection - {{ .Get 0 }}
```

**Content**
```md
# Title 1

{{% section "Section A" %}}
```

**Expected `.RawContent`**
```md
# Title 1

## mysection - Section A
```

So, am I incorrect on any of this?

I haven't looked at the shortcode rendering pipeline, but would it make sense to not render the shortcode with BF (only do `text/template` rendering) if the parent template is also Markdown?  Just merge the shortcode output into the parent and render once on final?

*(Not sure I'm finished with my thought here, but I gotta run.)*

**Comment by bep** [comment]
@moorereason I read your post and started a reply about "I don't think that would work ..." But I deleted my comment. Thinking harder about it, I think you are spot on.

There are some challenges here (output formats, mainly), but it is the obvious best solution.

>if the parent template is also Markdown

I think the important part here is that if **the root shortcode is markdown** then send it as part of the surrounding content to Blackfriday.

* We render shortcodes inside out, so you will have support for nested HTML shortcodes if you want
* The nested HTML shortcodes are included in what is sent to the MD processor today, so there should not be any change there.

**Comment by maiki** [comment]
There are some old issues here and threads in the forums about the [TOC not picking up headings from shortcodes](https://discourse.gohugo.io/t/table-of-contents-empty-when-headers-within-shortcode/12528). Am I understanding correctly the outcome of this issue will solve the TOC thing? If so I can just link to here as reference.
