### ISSUE TITLE
Hugo 0.40.2 CLI from Homebrew not pass Virustotal test

### ISSUE THREAD

**Issue by tyohan** [gohugoio/hugo#4696]
I'm trying to install Hugo CLI 0.40.2 through Homebrew on my corporate laptop and to able run it, it need to pass VirusTotal test which I was [testing here](https://www.virustotal.com/#/file/33121b8095e11b8a79e230ccc74e6eb02df133205cf8163db71f2df42f4d4ef5/detection). It's not pass the test, with one test failed and detected to has VEXF370.Webshell which not sure what is it. The file that I was uploaded taken from `/usr/local/Cellar/hugo/0.40.2/bin/hugo` on my MacOS 10.13.3.

Any idea what is it?

**Comment by bep** [comment]
No idea. The binary in this case is produced by the core Homebrew theme, if that helps. I tried to google the name of that alert, but got no match.

**Comment by tyohan** [comment]
Noted, decided to install go from binary. Thanks
