### ISSUE TITLE
ERROR Failed to read data from robots.txt/robots.txt: Data not supported for extension 'txt'

### ISSUE THREAD

**Issue by neveeng** [gohugoio/hugo#4704]
can't build site after upgrading Hugo v0.40.2  and gives this error. Before I had v0.32.4 and didn't show any error while building. The file currently in static folder. 

ERROR 2018/05/07 15:21:13 Failed to read data from robots.txt/robots.txt: Data not supported for extension 'txt'

any idea how to fix?

I tried 
disableRobotsTXT = true
disableKinds = ["robotsTxt"]

or moving my robots.txt file to layouts/_default.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
