### ISSUE TITLE
Chops off trailing .Content in one multioutput setup

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4706]
Hello,

I realized that Hugo 0.40.1 introduced a serious regression.

It chops off some of the trailing `.Content`!

- This issue is not seen in `hugo server`.
- It is only seen when the site is built to `public/` using the `hugo` command.

## Bug example

- [~~Live example of this bug~~ (not live any more)][1] (*Search for "Resources" to get to the point of truncated `.Content`*) | [Markdown of that page][3]

Notice the malformed HTML:

![image](https://user-images.githubusercontent.com/3578197/39713106-7c583332-51f3-11e8-8384-feda6fdad299.png)

[This is what I have in the template][2]:

```html
    <h3>Content</h3>
    {{ .Content }}

    {{ if (not .Params.disable_debug) }}
        {{ with .Resources }}
            <hr />
            <h3>Resources</h3>
```

And this is the HTML around the part where the `.Content` ends:

```html
<table>
<thead>
<tr>
<th>Inside <code>&lt;ORG_FILE_DIR&gt;</code></th>
<th>Copied-to location inside BUNDLE</th>
<th>Explanation</th>
</tr>
</thead>

<tbody>
<tr>
<td><code>&lt;ORG_FILE_DIR&gt;/bar/baz/foo.png</code></td>
<td><code>&lt;HUGO_BASE_DIR&gt;/content/&lt;SECTION&gt;/&lt;BUNDLE&gt;/bar/baz/foo.png</code></td>
<td>Even if the <strong>outside</strong> path does not have <code>/static/</code>, it is still inside the same dir as the Org file, 

    
        
            <hr />
            <h3>Resources</h3>
```

**Notice that the ending portion of the table got truncated!**

If I roll back to Hugo 0.40, this bug is gone. See that that table is generated in entirety:

```html
<table>
<thead>
<tr>
<th>Inside <code>&lt;ORG_FILE_DIR&gt;</code></th>
<th>Copied-to location inside BUNDLE</th>
<th>Explanation</th>
</tr>
</thead>

<tbody>
<tr>
<td><code>&lt;ORG_FILE_DIR&gt;/bar/baz/foo.png</code></td>
<td><code>&lt;HUGO_BASE_DIR&gt;/content/&lt;SECTION&gt;/&lt;BUNDLE&gt;/bar/baz/foo.png</code></td>
<td>Even if the <strong>outside</strong> path does not have <code>/static/</code>, it is still inside the same dir as the Org file, so the directory structure is preserved.</td>
</tr>
</tbody>
</table>

<p>See <a href="https://ox-hugo.scripter.co/test/images-in-content/page-bundle-images-in-same-dir/">this other test</a> for an example.</p>


    
        
            <hr />
            <h3>Resources</h3>
```

## How to recreate this issue

1. git clone --recursive -j8 https://github.com/kaushalmodi/ox-hugo
2. cd ox-hugo/test/site
3. hugo -b https://ox-hugo.scripter.co/test/
4. HTML referenced in this report: `./public/bundles/page-bundle-a/index.html`.

*I have yet been unable to create a smaller reproducible version of this bug. But it is 100% reproducible using the above steps.*

- The bug is absent in Hugo 0.40
- The bug is present in Hugo 0.40.1 onwards.

[1]: https://ox-hugo.scripter.co/test/bundles/page-bundle-a/
[2]: https://github.com/kaushalmodi/hugo-bare-min-theme/blob/12bdcda2233445da546cec20ab86f02fb9def5da/layouts/_default/single.html#L52-L58
[3]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/bundles/page-bundle-a/index.md

**Comment by kaushalmodi** [comment]
I wish I could understand the changes in this commit (https://github.com/gohugoio/hugo/commit/288c39643906b4194a0a6acfbaf87cb0fbdeb361) that's the only functional difference between 0.40 and 0.40.1. But that's what introduced this issue.

**Comment by bep** [comment]
For the future, please keep bug titles in a neutral tone. Using movie style titles to draw attention really don't work.

**Comment by bep** [comment]
I cannot see in the example above that the `.Content` is chopped off? You say it is chopped off **after** the content?

**Comment by kaushalmodi** [comment]
> ou say it is chopped off after the content?

No, the trailing portion of the `.Content` is chopped.

If you look at the [Markdown][1] source:

```md
|----------------------------------|--------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|
| `<ORG_FILE_DIR>/bar/baz/foo.png` | `<HUGO_BASE_DIR>/content/<SECTION>/<BUNDLE>/bar/baz/foo.png` | Even if the **outside** path does not have `/static/`, it is still inside the same dir as the Org file, so the directory structure is preserved. |

See [this other test](/images-in-content/page-bundle-images-in-same-dir/) for an example.
```

you will see that the HTML contains the content only up to "it is still inside the same dir as the Org file,":

```html
<td>Even if the <strong>outside</strong> path does not have <code>/static/</code>, it is still inside the same dir as the Org file, 
```

This part from the Markdown file (towards the end) is missing in the HTML:

```md
so the directory structure is preserved. |

See [this other test](/images-in-content/page-bundle-images-in-same-dir/) for an example.
```

---

Note the "good HTML" snippet generated using Hugo 0.40 has this portion:

```html
so the directory structure is preserved.</td>
</tr>
</tbody>
</table>

<p>See <a href="https://ox-hugo.scripter.co/test/images-in-content/page-bundle-images-in-same-dir/">this other test</a> for an example.</p>
```

which is abset in the live example.


[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/bundles/page-bundle-a/index.md

**Comment by bep** [comment]
Also, I don't understand how to build the above project (seems to need Emacs and vc-git etc).

**Comment by kaushalmodi** [comment]
Looks like this issue is on a lot more pages than I thought; surprised why no one else spotted this.

Another example:

- [Markdown][1] | [HTML][2]

Note that all content after "It is necessary to set the Hugo site config variable" below is lost:

```md
**It is necessary to set the Hugo site config variable
`pygmentsCodeFences` to `true` for syntax highlighting to work for
fenced code blocks.**

[^fn:1]: Even if the user has set the `HUGO_CODE_FENCE` value to `t` (via variable, keyword or subtree property), the Hugo `highlight` shortcode will be used automatically instead of code fences if either (i) the user has chosen to either show the line numbers, or (ii) has chosen to highlight lines of code (See the `ox-hugo` documentation on [Source Blocks](https://ox-hugo.scripter.co/doc/source-blocks)).
```

Here's the truncated `.Content` HTML:

```html
<p><strong>It is necessary to set the Hugo site config variable
<

        

        

        <hr />
        <a id="debug"></a>
```

*Something special about me using `<hr />` immediately after `{{ .Content }}`?* :)

![image](https://user-images.githubusercontent.com/3578197/39718098-3ee05fc4-5203-11e8-925f-17c0e1aa6495.png)


[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/posts/source-block-md-with-hugo-shortcodes.md
[2]: https://ox-hugo.scripter.co/test/posts/source-block-md-with-hugo-shortcodes/

**Comment by bep** [comment]
> surprised why no one else spotted this.

Your site does not represent the average Hugo site.

If you could take the PR above for a spin and tell me if that fixes this issue.

**Comment by kaushalmodi** [comment]
> If you could take the PR above for a spin and tell me if that fixes this issue.

I confirm that to fix this issue. Thanks!

> Your site does not represent the average Hugo site.

OK. Not sure what would represent an average Hugo site. The only thing different I am doing in this site is print out all the debug info and implement search. Apart from that, it's pretty bare bones.

In any case, I'd like to understand how my site turned out to be a corner case (if so). Hopefully looking at the tests you add helps me understand that.

Also note that this issue showed up only on doing `hugo`, not `hugo server`. So might be a useful piece to this puzzle too.

**Comment by bep** [comment]
>The only thing different I am doing in this site is print out all the debug info and implement search. Apart from that, it's pretty bare bones.

I will look at this more tomorrow. This is a bug, but I suspected that it relates to your not very _bare bones_ page output definitions:

```bash
▶ find content -name "*.md" | xargs grep outputs
content/search.md:outputs = ["html", "json"]
content/posts/output-html-and-json.md:outputs = ["html", "json"]
content/posts/output-html-and-json.md:tags = ["outputs", "json"]
content/posts/output-html-and-json.md:template lookup hierarchy for the JSON outputs to be created.
content/posts/output-empty.md:title = "Setting empty outputs is fine"
content/posts/output-empty.md:tags = ["outputs", "empty"]
content/posts/output-empty.md:will not set the `outputs` variable in the front-matter at all. So
content/posts/keyword-collection.md:outputs = ["html", "json"]
content/posts/keyword-collection.md:-   [X] `#+hugo_outputs`
```

**Comment by kaushalmodi** [comment]
Aha, to separate out the matches with "outputs" in that:

## Files with `outputs` front-matter

```
> find .  -name "*.md" | xargs grep -P 'outputs ='
./posts/keyword-collection.md:outputs = ["html", "json"]
./posts/output-html-and-json.md:outputs = ["html", "json"]
./search.md:outputs = ["html", "json"]
```

The first two are my tests for setting `outputs`. The last is what implements the test-site-wide search.

## `outputs` as a tag

```
> find . -name "*.md" | xargs grep -P 'tags.*"outputs?"'
./posts/output-empty.md:tags = ["outputs", "empty"]
./posts/output-html-and-json.md:tags = ["outputs", "json"]
```

*Problem to use `outputs` as a tag name?*

---

> I will look at this more tomorrow. 

Thank you! I'll stay tuned! :)

**Comment by bep** [comment]
>Problem to use outputs as a tag name?

No, that was just me being lazy with the grep.

**Comment by anthonyfok** [comment]
Hi @bep!  Sorry for the interruption, but caught a possible typo in your commit log:

> There have been one report of a site with truncated `.Content` after the Hugo `0.41` release.

I guess you meant to say `0.40` or `0.40.1` release there?  Many thanks!

**Comment by bep** [comment]
Just a quick note. I will create a patch release with this tomorrow.

Also note that even if the fix was semi-obvious reading the code, I have not been able to reproduce this outside of the synthetic test site from @kaushalmodi -- I have tested the output before/after this patch for a set of sites, including the pretty big Kubernetes site with 1000+ long content pages in both English and Chinese, with exact same result.

**Comment by kaushalmodi** [comment]
> I will create a patch release with this tomorrow.

Thanks!

> I have not been able to reproduce this outside of the synthetic test site from @kaushalmodi

That definitely makes me feel special 😁. But was the issue caused just because of those `outputs` front-matter in those 3 pages? Apparently no one/very few people use that front-matter?

*Note that my test site is testing **every** Hugo front-matter, for the sake of my `ox-hugo` package.*

**Comment by bep** [comment]
@kaushalmodi I tried to pin-point the exact error case, but I got tired. The tests in this area should be greatly improved as a result of this, and that is great.
