### ISSUE TITLE
Issue with .Render from list templates/multiple output formats

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4708]
This issue was discovered when writing some stress tests for #4706 -- probably not related, but it seems that it can render empty in given situations.

**Comment by bep** [comment]
This is actually as designed, but I will admit slightly confusing if you don't know better.

My test case was perhaps a bit confusing, but if you have a page with output JSON only (as an example) and run `.Render` on that page from a list template for the HTML output, it will not render anything. 

I will keep this open to consider if we can do better.

**Comment by regisphilibert** [comment]
I wonder if this thread is related: https://discourse.gohugo.io/t/api-theme-component-need-help-taming-render-and-scratch/12566
