### ISSUE TITLE
Provide backtrace to the point in template where a function gets called over "nil"

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4710]
Reference: https://discourse.gohugo.io/t/runtime-error-invalid-memory-address-or-nil-pointer-dereference/11881/12?u=kaushalmodi

An example problematic template snippet:

```
{{ (.Site.GetPage "taxonomyTerm" "categories" "foo").Permalink }}
```

Now if that `(.Site.GetPage "taxonomyTerm" "categories" "foo")` returns nil, `hugo` would only print something like:

> Building sites … ERROR 2018/05/08 14:55:46 Failed to render "theme/index.html": runtime error: invalid memory address or nil pointer dereference

That error does not mean that the referenced `index.html` has the problematic statement.. the error could be in any of the nested partials in that file. So the debug becomes time-consuming as you comment/uncomment the template files in halves to narrow down to the actual buggy line in the template.

**Comment by regisphilibert** [comment]
This indeed would shorten many debugging situations.

**Comment by moorereason** [comment]
I'm unable to reproduce this issue now.  Can anyone confirm?

I have an old v0.54.0 binary, and it shows better results even back then.  Not sure what version of Go I used to compile it, though (PS - maybe we should output the Go runtime version in our `hugo version` output).

Here's the changes I tested against the `gohugoioTheme`:

```
diff --git a/themes/gohugoioTheme/layouts/partials/home-page-sections/features-icons.html b/themes/gohugoioTheme/layouts/partials/home-page-sections/features-icons.html
index a7733acdc..239a5a57e 100644
--- a/themes/gohugoioTheme/layouts/partials/home-page-sections/features-icons.html
+++ b/themes/gohugoioTheme/layouts/partials/home-page-sections/features-icons.html
@@ -5,6 +5,7 @@
       {{ range $i, $e := $features  }}
         {{ $features_count := $e | len }}

+        {{ ($.Site.GetPage "foo").Permalink }}
         <div class="w-100{{ if and (eq $i $features_count) (ne (modBool $features_count 2) true) }} w-70-ns {{ else }} w-50-ns {{ end }}ph5-l pv5-l nested-copy-line-height">
           <!-- NOTE:  "if eq $i $features_count" makes the last item a bit wider for balance. If we use an even number of items, we'll want to remove this -->
           <div class="flex-l flex-wrap justify-between">
```

Output:

```
Error: Error building site: failed to render pages: render of "home" failed: "/hugoDocs/themes/gohugoioTheme/layouts/index.html:8:33": execute of template failed: template
: index.html:8:8: executing "main" at <partial "home-page-sections/features-icons" .>: error calling partial: "/hugoDocs/themes/gohugoioTheme/layouts/partials/home-page-se
ctions/features-icons.html:8:33": execute of template failed: template: partials/home-page-sections/features-icons.html:8:33: executing "partials/home-page-sections/features-icons.html" at <($.Site.GetPage "
foo").Permalink>: error calling Permalink: runtime error: invalid memory address or nil pointer dereference
```

**Comment by bep** [comment]
@moorereason this is fixed.
