### ISSUE TITLE
Issue: Goodreads icons do not show up when called within Hugo-academic theme of Hugo/Blogdown

### ISSUE THREAD

**Issue by jananiravi** [gohugoio/hugo#4711]
I'm creating a webpage using Hugo Blogdown (using Hugo-academic theme).
For instance, the GitHub and other social network icons work when called in the config.toml page but not Goodreads:
```
[[params.social]]
    icon = "goodreads"
    icon_pack = "fa"
    link = "//goodreads.com/jananiravi"
```
An almost identical bit that works:
```
[[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/jananiravi"
```

I posted this question earlier on [FortAwesome's Font-Awesome](https://github.com/FortAwesome/Font-Awesome/issues/13078#event-1616350534) and received a response from @tagliala (below)

>Hi!
Thanks for being part of the Font Awesome Community.
I think this issue does not apply here.
Please ask https://github.com/gohugoio/hugo to update font awesome from 4.5 to 5.0.12 or do the upgrade by yourself by forking that project
Hope it helps
Closing here

It would be helpful if the entire fa/io icon packs were updated so that missing icons show up. Thank you!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
