### ISSUE TITLE
Section RSS appending output format to the section name in <title>

### ISSUE THREAD

**Issue by StevenMMortimer** [gohugoio/hugo#4713]
This is a feature request to remove the appending of the output format from the section RSS feed title. For example, if you have a section called "blog" the RSS feed title looks like: 

`<title>Blog-rss on mysite.com</title`

I would expect the title to be only the section name and site title and not include the output format since it is redundant and looks weird. I would want the output to be: 

`<title>Blog on mysite.com</title`

**Comment by bep** [comment]
Yea, we should fix this. I guess I have seen this myself, but noticed it hard enough to do something about it. The current workaround is to provide your own template, but we should fix this.

**Comment by StevenMMortimer** [comment]
Thanks, @bep! I'm not sure if a template fixes this issue? I've tried putting a template at the following locations and none of them work when building a site from Netlify. 

Tried locations: 

  - layouts/index.rss.xml
  - layouts/index.rss.xml
  - layouts/rss.xml
  - layouts/index.xml
  - layouts/_default/index.rss.xml
  - layouts/_default/rss.xml
  - layouts/_default/index.xml
  - layouts/blog/section.rss.xml
  - layouts/blog/index.rss.xml
  - layouts/blog/rss.xml
  - layouts/blog/index.xml

Not really sure what other locations to try or how to specify somewhere else in the build to use the template.

**Comment by jmooring** [comment]
Unable to reproduce with v0.111.3. Not sure when it was fixed.

![image](https://github.com/gohugoio/hugo/assets/335669/3eadef22-ed66-4e82-871f-01689780d4b7)
