### ISSUE TITLE
Huge build times

### ISSUE THREAD

**Issue by nomez** [gohugoio/hugo#4714]
After installing v0.40.3 build time is higher than in v0.40.2 somehow it also affects paginator pages. 

**v0.40.3**
```
                   |  EN   
+------------------+------+
  Pages            | 1986  
  Paginator pages  |  107  
  Non-page files   |    1  
  Static files     |  657  
  Processed images |    0  
  Aliases          |  694  
  Sitemaps         |    1  
  Cleaned          |    0  

Total in 11471 ms

```

**v0.40.2**
```
                   |  EN   
+------------------+------+
  Pages            | 1986  
  Paginator pages  |   78  
  Non-page files   |    1  
  Static files     |  657  
  Processed images |    0  
  Aliases          |  693  
  Sitemaps         |    1  
  Cleaned          |    0  

Total in 1158 ms
```

**Comment by kaushalmodi** [comment]
Can you please share your site source? It's not possible to debug based just on these numbers.

**Comment by moorereason** [comment]
```
Paginator pages  |  107
```
Hmm...

**Comment by bep** [comment]
@nomez thanks for your report. We have solid test coverage in the paginator department and I see no regression in the performance benchmarks, but if you can post a link to your site's source, I will look at it.

**Comment by nomez** [comment]
Sorry it was a bug made by Algolia implementation from [Static site search with Hugo + Algolia](https://forestry.io/blog/search-with-algolia-in-hugo/) I just removed it and now works fine.  I could still send source files (on email) to you if want to see it with Algolia and without it as I couldn't figure out where the bug is and `--debug` and `--verbose` didn't point to nothing more than being stuck on generating algolia .json. :)
