### ISSUE TITLE
newbie questions – “Cannot GET /post/” error

### ISSUE THREAD

**Issue by ultimatesecpro** [gohugoio/hugo#4718]
Hi all,
I have started to work with the **blackburn** theme via **victor-hugo**.
I have couple of newbie questions.

I have added `about.md` by the command `hugo new about.md` to the folder 
`site/content/about.md`.

Similar, I have added a new post by the command ` hugo new post/first.md` to the folder `site/content/post/first.md`.

I have added the following to the `config.toml` file:
```
[[menu.main]]
    name = "Posts"
    ...
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
   ...
    identifier = "about"
    url = "/about/"
```
Unfortunately, when I click on the about link I’ve the following error:

`Cannot GET /about/`

Similar, when I click on the posts link I’ve the following error:

`Cannot GET /post/`

What is missed in my configuration?

I will appreciate any help,

Best regards,
   Michael

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
