### ISSUE TITLE
function "default" not defined

### ISSUE THREAD

**Issue by chumaumenze** [gohugoio/hugo#4719]
I'm getting 
`ERROR: 2018/05/13 15:21:58 template.go:350: template: partials/content_list.html:9: function "default" not defined` 
every time I run `hugo`.
Also whenever I run
 `hugo new "posts/first-post.md"`
it returns `Error: yaml: line 1: did not find expected key`

What's the problem here?

**Comment by chumaumenze** [comment]
Not just `default`, `now` included and some other hugo functions

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
