### ISSUE TITLE
Configure built-in Google Analytics template for GDPR

### ISSUE THREAD

**Issue by rwieruch** [gohugoio/hugo#4723]
Is it possible to configure the built-in GA template?

```
{{ template "_internal/google_analytics.html" . }}
```

25th of May the GDPR will be active, so I would love to be able to add the following configuration to it: `ga('set', 'anonymizeIp', true);`

**Comment by onedrawingperday** [comment]
Relevant discussion and Google Analytics template proposals are at #4616
