### ISSUE TITLE
Either /folder/index.html or /folder/other-file.html works but not both

### ISSUE THREAD

**Issue by manake** [gohugoio/hugo#4724]
I have this:
- /content/folder/index.html
- /content/folder/other-file.html

Behavior:
- When I enter `http://localhost:1313/folder/` it displays index.html.
- When I enter `http://localhost:1313/folder/other-file/` it displays `404 page not found`.

But when I make any change to other-file.html then this now happens:
- When I enter `http://localhost:1313/folder/` it displays /layouts/_default/list.html (should be index.html)
- When I enter `http://localhost:1313/folder/other-file/` it displays other-file.html

It's random and interchangeable. I don't see any logic or fix.

Hugo Static Site Generator v0.40.3 windows/amd64 BuildDate: 2018-05-09T07:47:04Z

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by manake** [comment]
How is this a question? Do you see any question marks there?

This is a bug report: there are 2 separate behaviors (listed above). There should be 1 behavior.

Yes, this is a "genuine bug report".

I see that you (counter-intuitively) decided to make /content/folder/index.html not overwrite /layouts/_default/list.html. I don't like it because I was expecting that index.html will be present at `http://localhost:1313/folder/` but that's OK.

I feel like I already explained what's the problem sufficiently above. This is happening RANDOMLY so I can't provide any exact steps to reproduce this issue.

1. I do `hugo -serve` and (according to your documentation this should not ever happen but it happens):
- `http://localhost:1313/folder/` it displays index.html
- `http://localhost:1313/folder/other-file/` it displays 404 page not found
2. I do a modification to /content/other-file.html and suddenly something else happens (or not) (according to your documentation this is the correct behavior):
- `http://localhost:1313/folder/` it displays /layouts/_default/list.html
- `http://localhost:1313/folder/other-file/` it displays other-file.html
