### ISSUE TITLE
GetPage `kind` param is neither fully respected nor really needed

### ISSUE THREAD

**Issue by vassudanagunta** [gohugoio/hugo#4726]
`.Site.GetPage` takes a `kind` arg, but its implementation only partially respects it. For kind `"page"`, it looks up only *page* Pages, as expected. But for any of the four node-kinds, *home*, *section*, *taxonomy*, and *taxonomyTerm*, it doesn't similarly limit itself.

For example:

- `.Site.GetPage("home", "posts")` doesn't return the one and only page of kind "home", but instead returns the "posts" section page (it's a coincidence that the returned page is the "home" page of the section).
- `.Site.GetPage("section", "categories")` returns a page of kind taxonomyTerm if one or more pages have a category value in their front matter.
- `.Site.GetPage("taxonomy" "funk")` won't return the taxonomy page for "music", but will either fail or return a "music" section or taxonomyTerm page if one existed. Taxonomy GetPage calls must use the fully qualified name, e.g. `.Site.GetPage("taxonomy", "tags/funk")`. But then the "taxonomy" arg is redundant, as the "tags/" prefix already identifies this as a request for a taxonomy page as well as specifying which taxonomy ("tags").

This strange behavior is mostly innocuous, as the above are strange corner cases, and as the paths for any two node kinds, regardless of type, can never be the same.

But if the `kind` arg is eliminated:

- eliminates the potential for confusion/surprise
- simplifies the API
- gives `.Site.GetPage` a signature consistent with the `ref`/`relref` shortcodes, which perform essentially the same function.  

Pull request forthcoming...

**Comment by kaushalmodi** [comment]
This was suggested a while ago here too: https://github.com/gohugoio/hugo/issues/4652.

.. but I didn't know that the behavior was inconsistent (as I never tried putting incorrect Kinds). 

I'd be interested in seeing what you propose in the PR. Would it break all the existing GetPages?

**Comment by bep** [comment]
It think it will save time in the long run if you bring these issues you open to some kind of conclusion before you arrive with a PR.

The big question, in this case, is if it can be done without breaking existing code.

**Comment by vassudanagunta** [comment]
@bep What are the benchmarks I should run for this?
