### ISSUE TITLE
GetPage, rel and relref accept ambiguous refs without warning

### ISSUE THREAD

**Issue by vassudanagunta** [gohugoio/hugo#4727]
Hugo supports "shorthand refs" when looking up or linking to other pages via the `.Site.GetPage` method and the `ref`/`relref` shortcodes. It makes authoring links a little easier, but it introduced number of problems:

- It is too easy for links to point to the wrong page. The author may not even be aware of the ambiguity, so may not now to invoke [the workaround](https://github.com/gohugoio/hugo/issues/4312#issue-290525225).
- Top-level pages and sections do not have a guaranteed-to-be-unique reference, so the workaround is not even available for such pages.
- It is far too easy for a once correct link to suddenly point to the wrong page on subsequent site builds, without warning.

The last one is the most dangerous.

### the ambiguity, illustrated

Take the following content directory:

```
content/
├── _index.md
├── help.md
├── blog
│   └── lessons.md
│   ├── lessons.nn.md
└── lessons
    ├── _index.md
    ├── links
    │   ├── _index.md
    │   └── help.md
    └── tags
        ├── _index.md
        └── help.md
```

The following table shows all the supported ways one can reference each page in calls to `.Site.GetPage`, `ref` or `relref`.  Ambiguous refs are marked with :warning:. Notice that two nodes do not have an unambiguous option. 

| path within `content/`  | "full" ref             | language independent "full" ref | shorthand ref                  |
| ----------------------- | ---------------------- | ----------------------------- | ------------------------------ |
| /_index.md              | (empty string)         |                               |                                |
| /help.md               | **help.md** :warning: | **help** :warning:    |                                |
| /blog                   | blog                   |                               |                                |
| /blog/lessons.en.md     | blog/lessons.md        | blog/lessons                  | lessons.md<br />**lessons** :warning:    |
| /blog/lessons.nn.md     | blog/lessons.nn.md     | blog/lessons                  | lessons.nn.md<br />**lessons** :warning: |
| /lessons/_index.md      | **lessons** :warning: |                               |                                |
| /lessons/links/_index.md | lessons/links |           |   |
| /lessons/links/help.md | lessons/links/help.md | lessons/links/help           | **help.md** :warning:<br />**help** :warning: |
| /lessons/tags/_index.md | lessons/tags |            |   |
| /lessons/tags/help.md  | lessons/tags/help.md  | lessons/tags/help            | **help.md** :warning:<br />**help** :warning:        |

### how a link gets modified without warning on site or Hugo updates  

You carefully checked all your links when you originally authored them. But later, perhaps months later, you or someone else adds a new page or section that inadvertently makes your link references amgiuous. Your originally correct link suddenly and without warning is changed to point to a different target. Only a manual check of all the links on the site would have revealed this change.

Even a Hugo update could result in such a silent change if the new code makes a different arbitrary choice for ambiguous refs.

Example:

1. `{{< ref "ambiguity" >}}` resolves to the intended (and only possible) target:

```
research/ambiguity.md
```
2. Months later, new page is added to the site:

```
blog/ambiguity.md
research/ambiguity.md
```

3. The page that originally pointed to the research page on ambiguity now points to the blog post. This happens silently on republish.

### solution ready 

I've implemented ambiguity detection, and it works great with no impact on performance. The pull requests is pending some questions I need answered. See the [the discussion on the forum](https://discourse.gohugo.io/t/getpage-ref-and-relref-renovations/12103/2).

**Comment by kaushalmodi** [comment]
This is a nice convenience feature though. You don't have to type full paths each time if your slugs are usually something descriptive like "this-is-how-you-peel-an-orange".

Would your PR be producing a warning or error in the case of ambiguity instead of removing this feature? That would be awesome.

**Comment by vassudanagunta** [comment]
I'm leaning strongly toward fail-fast (i.e. error), as warnings are too easy to miss. The error message would tell the users exactly what to do to make the error go away (e.g. "Error: the reference `this-is-how-you-peel-an-orange` in page x.md resolves to more than one page. Replace with a fully qualified path"). 

Thoughts?

**Comment by bep** [comment]
There is a significant performance cost adding such a warning (or alternatively a much more complex implementation).

**Comment by vassudanagunta** [comment]
@bep but if that were not the case you're down with this?

**Comment by vassudanagunta** [comment]
@bep What are the benchmarks I should run for this?

**Comment by vassudanagunta** [comment]
@bep I'd argue that "unsafe" is the right word, using "safe" in the same vein as Go's "type safety". Links are a part of the content, and when a link's target gets silently swapped on a site rebuild, it is no different than a paragraph getting switched with a paragraph from some other page on the site.

I was hoping you'd answer my questions about benchmarks (above) and method signature (under #4652) as I have what I think is a simple, elegant and equally fast solution ready to PR (or discuss on the forum if you prefer).
