### ISSUE TITLE
Hugo errors with exit code 0

### ISSUE THREAD

**Issue by Haroenv** [gohugoio/hugo#4734]
I'm not sure why this is happening, but when I have malformed front matter, Hugo throws an error and stops, but doesn't actually have a status code other than 0. 

```
Started building sites ...
ERROR 2018/05/18 18:04:01 failed to parse page metadata for "widgets/powered-by.md": yaml: line 39: found unexpected document indicator
Error: Error building site: Errors reading pages: Error: failed to parse page metadata for "widgets/powered-by.md": yaml: line 39:found unexpected document indicator for powered-by.md
```

Here is `$0` actually `0`. 

I'm also using `hugo-cli` (from npm) with 0.40.3 set as the Hugo version to use. 

Error seems to be generated 

https://github.com/gohugoio/hugo/blob/b2b500f563c3bb36751a4c1610df113c4daad604/hugolib/page.go#L1747

but I don't know if this is supposed to be swallowed like that. 

Thanks!

**Comment by bep** [comment]
I just tested this, and I cannot reproduce it. Are you sure you don't have any other tool that swallows this exit code? Gulp? Can you test it by invoking Hugo directly from the shell?

**Comment by Haroenv** [comment]
Running “yarn Hugo” also swallows error codes, but that’s still with “Hugo-cli”, the error might be there

**Comment by bep** [comment]
OK, you need to report this with those libraries.

**Comment by McInkay** [comment]
I'm having this situation myself, I have a malformed md file, but it's returning an exit code of 0.

I was running with yarn, but when I remove yarn and run it manually, it still has the same issue.

[Here's the build](https://circleci.com/gh/YaManicKill/pdd/31)

[And here's the code you can clone if you want to test it](https://github.com/YaManicKill/pdd/tree/fix-error-code). The branch fix-error-code has changed the circleci build to not use yarn and has an error in one of the md files, you should just be able to run hugo on that branch and see that it is returning 0 exit code.

Or do you want me to open a new ticket?
