### ISSUE TITLE
generated site content randomly changing without code changes

### ISSUE THREAD

**Issue by henning** [gohugoio/hugo#4736]
I'm working on a simple 5 page website.

I just realized while running "hugo server" and looking at my site, and doing changes (as similar as adding or removing a word in the content .md files), after each rebuild the Home page content from the _index.md file is sometimes included in the home page, and sometimes not.

But there is no logical, reproducible behaviour. On some changes, the content disappears, on some changes, it comes back. 
But it is not as easy as undoing exactly the change made before after which it disappeared and then it comes back. It's totally random. And I tested that now a nearly 100 times.

And, I also just tried additionally to just start and stop the server and check if the content is there or not - even with that, the inlcusion of this content is randomly happening or not. 

The same happens with "normal" generation runs. I can run hugo twice, like this:

    $ hugo 

                       | EN  
    +------------------+----+
      Pages            | 11  
      Paginator pages  |  0  
      Non-page files   |  0  
      Static files     | 13  
      Processed images |  0  
      Aliases          |  2  
      Sitemaps         |  1  
      Cleaned          |  0  

    Total in 40 ms
    $ hugo 

                       | EN  
    +------------------+----+
      Pages            | 11  
      Paginator pages  |  0  
      Non-page files   |  0  
      Static files     | 13  
      Processed images |  0  
      Aliases          |  2  
      Sitemaps         |  1  
      Cleaned          |  0  

    Total in 53 ms

One time the _index.md content is included in public/index.html, the other time not.

Heres gist with the different outputs I get:

https://gist.github.com/henning/7891d98d756be6626ef37d3d4f38455d

Repo: https://github.com/henning/hugo-website 

hugo env:

```
$ hugo env
Hugo Static Site Generator v0.40.3 darwin/amd64 BuildDate: 
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.10.2"
```

Please let me know if and what more I can do to help understanding or solving this problem.

There was an issue in the forum where I asked for help in this: https://discourse.gohugo.io/t/homepage-content-randomly-displayed-or-disappearing/12056

but also after thinking through it - build result changes without code changes in between somehow don't appear to me as they can be a user error, as what the user entered in code didn't change.

**Comment by bep** [comment]
Please wait a little before double-posting here, even if you think it is a bug. We are not many people running this project.

**Comment by henning** [comment]
I disagree, because exactly what you wrote now there the support request IMHO is a bug.

A content generator program allowing for a configuration that makes it generating content randomly different on each run even if input hasn't changed has a bug. 

I expect it to either complain and refuse to run until the configuration is set in a way the program can work properly, or settle on a useful default.
