### ISSUE TITLE
Twitter shortcodes are not properly displayed in Firefox for Linux

### ISSUE THREAD

**Issue by ccamara** [gohugoio/hugo#4737]
When inserting a twitter shortcode (eg: `{{< tweet 997935459417382915 >}}`) the embedded code is properly generated but it is not themed under Firefox for Linux (currently tested in 60.0.1 ), although same page looks great using Chromium or even Firefox for Windows.

Although I have recently updated hugo to v0.40.3, I am not sure it is an issue related to that specific version, since older posts in the live site which were deployed using a previous version stopped working too.

I would also discard a theme-related issue, since the problem persists when using different themes (you can check these URLS from different sites with different themes and hugo versions: http://www.carloscamara.es/blog/2018/05/16/zaragoza-accesible-en-el-pint-of-science-2018/ and http://mapcolabora.org/post/2018-03-25-cronica-mapping-party-las-fuentes/ )

**Comment by pkollitsch** [comment]
I can't recreate your issue on Firefox 60.0.1 on Linux. The Twitter posts look like they should. On a related note, I think you might want to file this with either the firefox team or the twitter team as it's a browser related issue. Try disabling your plugins, clearing cache... all the stuff ;)

**Comment by ccamara** [comment]
I found where the error was: my FF settings were blocking any tracking content, and hence, Twitter was blocked as a result of this configuration.

After disabling that config for the already mentioned domain, tweets were displayed just fine.
