### ISSUE TITLE
Do not return error on .Get "class" and vice versa in shortcodes

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4745]
This makes it very hard to make short and generic code. 

* If positional params are used, I expect ` .Get "class"` to return nil.
* If named params are used, I expect  `.Get 0` to return nil.

**Comment by kaushalmodi** [comment]
I thought that "return nil instead of error on .Get in shortcodes" change was done by @paulcmal about a month or so ago. Does the associated PR make that change more consistent?

**Comment by bep** [comment]
That PR was ... different, but similar, I don't know how to describe it better.
