### ISSUE TITLE
Improve image handling in youtube_simple

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4755]
Seems it is not possible to guess the URL to the best preview image version of a given YouTube video.

Some options to fix this is:

* Adding a positional param isn't easy to do in a non-breaking way (someone has been clever enough to add "class" as a second parameter). Also, this should ideally be a configuration toggle. Having to manually inspect and modify a thousand videos on a site does not sound ideal.
* Find another way to detect image size/whatever
* Integrate with the YouTube API, which probably requires API key handling and sound like work. 

If someone can come up with a simple approach that is also good, we can do it. But we may have to remove the simple variant for now.

/cc @onedrawingperday

**Comment by onedrawingperday** [comment]
@bep 
It seems that the loading of the YouTube `maxresfefault.jpg` thumbnail is relevant to the video aspect ratio.

For example [this video](https://www.youtube.com/watch?v=TJAfLE39ZZ8) is low resolution and yet it has the [correct max res thumbnail](https://i.ytimg.com/vi/TJAfLE39ZZ8/maxresdefault.jpg)
[Here is the JSON response of the video](https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=TJAfLE39ZZ8&format=json)

While [this video](https://www.youtube.com/watch?v=d_EADBnXjXc) that is also low resolution has [the wrong thumbnail](https://i.ytimg.com/vi/EADBnXjXc/maxresdefault.jpg)
[Here is the JSON response of the video](https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=d_EADBnXjXc&format=json)

The low resolution videos with the wrong maxresdefault thumbnail have this value:
`"width": 459`

While videos with the correct thumbnail have: `"width": 480`

I have already tested this in a bunch of videos and I will test it some more to be 100% sure that this is the case.

But if what I found is valid for all cases then we could probably do the thumbnail detection.

If you don't like this approach. Then maybe we should just load the `hqdefault` thumb. This low res image exists for all YouTube videos. Of course it will look bad in high-res. But it's better than nothing.

Anyway let me know what you think and I could PR this later today.

P.S. Again my apologies for the erroneous PR . I shouldn't be doing PRs at 11 o' clock at night after a long day.

**Comment by bep** [comment]
I assume that most newer videos is 720p+ and would have a high-res image. We **really want to show that high res image**. I would even say that it would be better with some false negatives.

So if the 459 rule is good in 9/10 of the low-rez versions, we should go for it.

**Comment by bep** [comment]
Oh, and thanks for following up on this, and don't worry about mistakes, that is the only way to get stuff done.

**Comment by onedrawingperday** [comment]
I'm not done testing yet.

Please gimme 1 more hour. And I'll let you know for sure if the 459 width is the way to do this detection.

> We really want to show that high res image
Yes we do. But there are CSS ways to make a low res thumbnail look passable.

Like overlaying [video scan lines](http://pangolin.com/images/LD2000/MonaLisa_in_laser.jpg) or if you feel like going experimental [a CSS glitch effect animation](https://tympanus.net/Tutorials/CSSGlitchEffect/) with clip-path.

Now I know that you most likely don't want to go down the CSS route but the low res hqdefault thumb is guaranteed to exist for all YouTube videos.

**Comment by onedrawingperday** [comment]
We cannot do the thumbnail detection through the oEmbed endpoint of YouTube.

For example here are the JSON responses of  3 videos:

1st video [JSON](https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=xDCOGHk-0_c&format=json)

2nd video [JSON](https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=YQHsXMglC9A&format=json) 

3rd video [JSON](https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=TJAfLE39ZZ8&format=json)

All of them share the following values:

```
thumbnail_height:	360
thumbnail_width:	480
width:	480
height:	270
```

And only the 1st video displays a high resolution video all the others return that icon.

I've tested way more videos than the above.

It is a mystery how YouTube chooses to display a high resolution video thumbnail.

They don't expose it through the oEmbed endpoint. 

But just FYI they display it in the Open Graph tags of the respective video URLs.

So from here I gues that the only option we got is to overlay the low res with scan lines or something.

**Comment by bep** [comment]
I suspect what we experience here is a matter of caching/lazy thumbnail generation.

Your examples maxresdefault:

https://i.ytimg.com/vi/xDCOGHk-0_c/maxresdefault.jpg
https://i.ytimg.com/vi/YQHsXMglC9A/maxresdefault.jpg
https://i.ytimg.com/vi/TJAfLE39ZZ8/maxresdefault.jpg

hqdefault:

https://i.ytimg.com/vi/xDCOGHk-0_c/hqdefault.jpg
https://i.ytimg.com/vi/YQHsXMglC9A/hqdefault.jpg
https://i.ytimg.com/vi/TJAfLE39ZZ8/hqdefault.jpg

All of these show up fine now in my browser. Are you saying that you see some play icon?

**Comment by onedrawingperday** [comment]
> I suspect what we experience here is a matter of caching/lazy thumbnail generation.

Good catch. I was seeing the gray thumb with the 3 dots.

Ok. I'll test further and let you know of my findings.

Also I have seen your services config but haven't put it to work just yet. If I have a question about it I'll ask.

**Comment by onedrawingperday** [comment]
Here is another [JSON](https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=k8bMaAE8wUQ&format=json) with same values as the above.

And again I am seeing the gray thumb even in a Private Browser Tab instead of a high resolution thumb: [https://i.ytimg.com/vi/k8bMaAE8wUQ/maxresdefault.jpg](https://i.ytimg.com/vi/k8bMaAE8wUQ/maxresdefault.jpg)

What are you seeing on your end?

This is beginning to feel like _trying to find a needle in a haystack_.

__________________

Anyway I know your reservations about using Open Graph tags and this is the last time I'm mentioning them.

There are a couple of Go packages that could probably make our lives a lot easier and offer really useful Simple Mode shortcodes to end users.

https://github.com/dyatlov/go-opengraph
https://github.com/dyatlov/go-htmlinfo

**Comment by bep** [comment]
Even if you throw out the reservations, implementing OG tags in a proper way in Hugo is 20+ hours of work. I'm not prepared to put down that amount of work on this.

I will think about this. If we don't find a solution, we can just push it for a later date.

**Comment by bep** [comment]
I have googled around, and it seems that the only reliable way (without parsing the OG tags, which I have not looked into) is to do a HTTP request. I will consider adding a `httpHeadOnce` with some caching to allow for checking HTTP response codes on remote resources.

**Comment by onedrawingperday** [comment]
You may be on to something.

I just checked the following 2 URLs using an online tool

[This](http://tools.seobook.com/server-header-checker/?page=single&url=https%3A%2F%2Fi.ytimg.com%2Fvi%2FxDCOGHk-0_c%2Fmaxresdefault.jpg&useragent=2&typeProtocol=11) maxresdefault gives a 200. And the thumbnail exists.

But [this](http://tools.seobook.com/server-header-checker/?page=single&url=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fk8bMaAE8wUQ%2Fmaxresdefault.jpg&useragent=1&typeProtocol=11) maxresdefault gives a 404 and the default gray icon thumb is served.

Also I found out that there is a 3rd size sddefault.jpg served by YouTube and that is somewhere between the hqdefault and the maxresdefault. 

For example the second image has sddefault as its maximum resolution. The [server response](http://tools.seobook.com/server-header-checker/?page=single&url=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fk8bMaAE8wUQ%2Fsddefault.jpg+&useragent=1&typeProtocol=11) is 200.
