### ISSUE TITLE
PrivacyConfig raises an error

### ISSUE THREAD

**Issue by yamila-moreno** [gohugoio/hugo#4757]
Hi! I've been through an error today with hugo, with today's version. As it didn't happen with yesterday's version I'm assuming it's something related to the commits of today (may 22nd). Following the error, I'm guessing it has to be related to this line in a today's commit (probably a long shot).

https://github.com/gohugoio/hugo/commit/353148c2bc2cdb9f2eb8ee967ba756ce09323801#diff-b6f13a226785cb790bdcbccf6762ace3L1154

The error raised is:

```
Building sites … ERROR 2018/05/22 23:59:54 Error while rendering "page" in "post/": template: theme/_default/single.html:1:3: executing "theme/_default/single.html" at <partial "head.html" ...>: error calling partial: template: _internal/google_analytics.html:1:16: executing "_internal/google_analytics.html" at <.Site.PrivacyConfig....>: can't evaluate field PrivacyConfig in type *hugolib.SiteInfo
```

I've checked with two different themes and both of them raise the same error, so I'm assuming it has to be directly related to Hugo.

**Comment by onedrawingperday** [comment]
This is related to the upcoming GDPR compliant release of Hugo that will offer site admins various options regarding 3rd party tracking.

The error is because you will need to provide site wide privacy configuration for the GA internal template to work.

The configuration is not yet documented.

**Comment by yamila-moreno** [comment]
Hi @onedrawingperday Thanks for your answer!
My Travis-CI integration is failing (I assume that everyone's will be failing); is there a workaround to get hugo in a previous version? I mean while the release is not ready, and then revert the use of the old version when I can properly apply the needed changes.

**Comment by bep** [comment]
@yamila-moreno I will fix this now. Sorry about the noise and thanks for the heads up.

**Comment by onedrawingperday** [comment]
@yamila-moreno If you see anything else being broken in the coming days please let us know. 

The coming release is very tricky.

**Comment by yamila-moreno** [comment]
Sure! :+1:

**Comment by yamila-moreno** [comment]
It worked! Kudos and thank you very much
