### ISSUE TITLE
`humanize` function should no-op accronyms

### ISSUE THREAD

**Issue by hyprhare** [gohugoio/hugo#4759]
It appears that humanize is does not discriminate ACRONYMS from camelCase.
It probably should?

For example:
"FBI" | humanize => "FBI"
"M.I.T" | humanize => "M.I.T"

Consider excluding PascalCase as well? Not sure if this would prove more irritating than desirable...:
"AmTrack" | humanize => "AmTrack"

Keeping the otherwise expected behavior:
"myActualCamelCase" | humanize => "My actual camel case"
"hole-in-the-wall" | humanize => "Hole in the wall"

**Comment by bep** [comment]
Could you raise the issue here: https://github.com/markbates/inflect
