### ISSUE TITLE
Icons for Simple mode Hugo shortcodes

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#4763]
Related PR: #4747 
Related Issues: #4749 #4764

**Proposal A**
I designed these control icons for use in the Simple Mode Hugo shortcodes inspired by the hexagon that is used in the Hugo logo. 

![hugo-icons](https://user-images.githubusercontent.com/7918298/40473651-755bb0ea-5f45-11e8-9956-62bfca4934a1.png)

I have made 2 variations of the play button for you to choose what you prefer.

**Example display for YouTube/Vimeo with the first play button**

![yt-vimeo-hugo-1](https://user-images.githubusercontent.com/7918298/40473684-8f5a5a46-5f45-11e8-80e9-bec579444e92.png)

**Example display for YouTube/Vimeo with the second play button**

![yt-vimeo-hugo-2](https://user-images.githubusercontent.com/7918298/40473727-aa116bcc-5f45-11e8-9260-8030a03c9338.png)

**Example display for the Speaker Deck Simple Mode Shortcode**

![speaker-deck-hugo](https://user-images.githubusercontent.com/7918298/40473788-d386f742-5f45-11e8-85a7-abb204b9c497.png)

**Proposal B**
As an alternative the following Fork Awesome svg icons can be used in the Hugo Simple Mode shortcodes. The licence for these icons is fully Open Source and is available [here](https://forkawesome.github.io/Fork-Awesome/license/)

![fork-awesome-icons](https://user-images.githubusercontent.com/7918298/40473922-4880377a-5f46-11e8-8e6f-a00e84b173b6.png)

**Example display for YouTube/Vimeo with Fork Awesome play button**

![yt-vimeo-fork-awesome](https://user-images.githubusercontent.com/7918298/40474096-c25d8278-5f46-11e8-9c9a-2508ace50200.png)

**Example display for the Speaker Deck Simple Mode Shortcode with Fork Awesome Icons**

![speaker-deck-fork-awesome](https://user-images.githubusercontent.com/7918298/40473990-77b7014a-5f46-11e8-99dc-320fae852f32.png)

CC/ @bep and anyone else

**Comment by bep** [comment]
I think we should go with the traditional round play button.

**Comment by onedrawingperday** [comment]
Ok. Which play button mine of the Fork Awesome one?

What about Speaker Deck? Is the proposed display what you have in mind for this shortcode?

**Comment by bep** [comment]
Yours. The Fork Awesome license looks too hard to grasp in 10 minutes.

**Comment by onedrawingperday** [comment]
I will send a PR later today for the play icon and ask you to review it.

The markup is different because there is a circle now. 

I will include a release note with a link to the Apache 2 licence in the PR message. Is that good enough?

**Comment by onedrawingperday** [comment]
I am closing this issue since since all simple variants that need icons have been developed except for #4764 

I will send a PR about the Speaker Deck simple variant one of these days and we can discuss if this particular shortcode needs icons there.
