### ISSUE TITLE
GDPR: Create speakerdeck_simple

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#4764]

**Comment by bep** [comment]
Question: What is the privacy problems with the embedded variant? Do SpeakerDeck provide some privacy options that can be turned on? 

I say this, because I start feeling that we spend a little too much time on this, and I don't want special shortcodes to maintain unless really needed. If so, they should be really simple, and I'm not sure how a SpeakerDeck shortcode could fall into that category.

**Comment by onedrawingperday** [comment]
I have outlined the privacy problems with Speaker Deck [here](https://github.com/gohugoio/hugo/issues/4616#issuecomment-386889414)

They offer no privacy options.

Sample oEmbed JSON response from Speaker Deck [here](https://speakerdeck.com/oembed.json?url=https://speakerdeck.com/spf13/mongodb-e-commerce-and-transactions)

**Comment by bep** [comment]
OK, just had to check...

**Comment by onedrawingperday** [comment]
> I'm not sure how a SpeakerDeck shortcode could fall into that category

Basically it will be just a link.

In #4763 I posted a proposal for the display that takes into account the oEmbed JSON.

If you feel that it will be too much CSS to do it like this, then maybe it should be just the presentation title and a View more on Speaker Deck link.

Also note that I have never used the Speaker Deck service and don’t plan to use it.

If you think that it’s overkill for the project to provide a Simple mode for Speaker Deck  feel free to close this issue.

**Comment by onedrawingperday** [comment]
Question for @bep 

I have found out that it is very much possible with Hugo to fetch the slides of a Speaker Deck presentation.

Which of the two possible forms for the Speaker Deck simple variant do you prefer:

1. Fetch the first slide and then when the user clicks on it the presentation opens in a new tab directly on Speaker Deck's player.

2. Fetch all slides within a Hugo site. This would require a carousel (can be done with just CSS) and a simple script for lazy loading the slides (to avoid the HTTP requests on page load).

I am in favor of 1 as it is _the_ simple solution.

But I am just asking you because you may prefer 2, since the content will be directly available from a Hugo site pretty much like it is with the default iframe embed.

Also if anyone else has a preference let me know.
