### ISSUE TITLE
GDPR: Investigate instagram privacy options in their embedded API

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4766]
Maybe we can get rid of the simple variant.

**Comment by onedrawingperday** [comment]
In my honest opinion this will be a waste of your time. 

There are absolutely no privacy options in the Instagram API and in other 3rd party embed APIs.

The only embed API that offers some kind of half-hearted privacy is Twitter's with a `dnt` flag meant to disable tracking from pages with tweet embeds for personalized ads, but still even with that flag Twitter tracks for everything else through its embeds.

The only way to get rid of the Hugo simple variants is to build a mechanism for user consent and if a user does not agree then break/hide the embeds.

Here is a relevant (and short) [discussion](https://github.com/trewknowledge/GDPR/issues/33) about making iframe embeds GDPR compliant from the GitHub repo of a WordPress [GDPR plugin](https://github.com/trewknowledge/GDPR).

**Comment by onedrawingperday** [comment]
Closing.

See commit: https://github.com/gohugoio/hugo/commit/1f244b802eaabb119d38dae00a8c2bbbd3263752
