### ISSUE TITLE
Live-reload does not detect new Page resources

### ISSUE THREAD

**Issue by internetfreak** [gohugoio/hugo#4768]
**Related to this:** https://discourse.gohugo.io/t/livereload-not-rebuilding-page-resources/11715/4

**The issue**
When using hugo with server mode for development reasons and you create a new page bundle, hugo notices the `index.md` file of the bundle and starts rendering it on changes. However, if you also add resources like images to that bundle, they won't be available in `.Resources` unless you restart the server, which slows down developement a lot.

**Expected behavior**
Adding resources to a page bundle should immediately populate `.Resources` to be retrieved using `.Resources.Match` or `.Resources.GetMatch` without requiring to restart the development server.

**Envinronment informations**
Version of Hugo: 0.40.3
OS: Windows 10 Pro x64

**Comment by bep** [comment]
I just tested this with the latest Hugo master, and this works perfectly on `macOS`. 

I tested this on https://github.com/bep/hugotest/tree/master/content/resourcemeta/bundle-with-resource-meta-toml (note that the last commit in this repo requires the latest Hugo dev version):

When server was running:

* Copied a new PNG into that folder. PNG shows up with metadata supplied.
* Delete the same PNG, it vanishes from page.

I tested the above OK on both current master and `v0.40.3`.

**Comment by bep** [comment]
I have not also performed the same test on Windows 10. Works fine for me.

Can you try this one more time; and if this is still an issue, can you describe your steps in  more detail so we can try to identify what happens.

**Comment by internetfreak** [comment]
I tested this again and I'm still able to reproduce using hugo 0.41 on Windows 10. Here are my steps to I did to test:

1. Create a new hugo site
2. Add the following templates:
**layouts/_default/baseof.html**
```html
<!DOCTYPE html>
<html lang="{{ .Site.Language.Lang }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

        <title>
            {{ block "title" . }}
                {{ .Title }} | {{ .Site.Title }}
            {{ end }}
        </title>

        {{ range .AllTranslations}}
            <link rel="alternate" hreflang="{{ .Language }}" href="{{ .Permalink }}" />
        {{ end }}
    </head>
    <body>
        {{ block "content" . }}{{ end }}
    </body>
</html>```

**layouts/index.html**
```
{{ define "content" }}
{{ $posts := where .Site.RegularPages ".Type" "blog" }}
{{ range $index, $element := $posts }}
{{ $featuredImage := $element.Resources.GetMatch "images/hero-image.*" }}
{{ if $featuredImage}}
&lt;img class="featured-post-image" src="{{ $featuredImage.Permalink }}" /&gt;
{{ end }}
{{ end }}
{{ end }}
```
2. Create a new section called **blog**
3. Start hugo by using `hugo server --baseURL http://localhost`
4. Add a page bundle folder using any name
5. Add the following minimal `index.md`
```
+++
title = "Test Pagebundle4"
draft = false
date = 2018-06-11T13:00:00+02:00
+++
This is a test of a pagebundle
```
6. Add a folder called `images` inside of our bundle folder and add any image called `hero-image` in there. The file extension should not matter, I used a license free jpg I found on the internet
7. Note how hugo detects every change we make but if you navigate to `localhost:1313` or reload the page, should you already opened the url, then you notice that the page is still empty
8. Stop hugo and restart it again in server mode. Reload the page and now you see the image being displayed

I hope this helps. As it is a very simple setup I did not create a github repo for this to checkout and reproduce.

**Comment by bep** [comment]
> As it is a very simple setup I did not create a github repo for this to checkout and reproduce.

As I said, I'm not able to reproduce it with a similar simple setup. So the devil is in the details. Someone may eventuallyt look closer into this, but if you can create a runnable GH repo, I can probably look at it sooner rather than later.

**Comment by internetfreak** [comment]
I uploaded the complete working directory I used for testing (including the image, it's CC0 and thus safe to use and distribute) to github, here's the link: https://github.com/internetfreak/pagebundle-bug/tree/master

**Comment by timsluis** [comment]
FYI: the same is happening for me on macOS. Will try to look into it as well.

*Environment information*
Version of Hugo: 0.42.1
OS: macOS 10.13.5

**Comment by iancross-gb** [comment]
I can still reproduce this on Hugo 0.88.1. In my case page resources becomes empty on reload (see https://discourse.gohugo.io/t/resources-empty-with-live-reload/12669). To reproduce use the wowchemy theme's example site:

```
git clone https://github.com/wowchemy/starter-hugo-academic.git
cd starter-hugo-academic
#
# Create a hero which relies on page resources to find it's hero_media
#
cp assets/media/icon.png content/home/hero.png
cat << EOF > content/home/hero.md
+++
widget = "hero"
headless = true
active = true
weight = 10
title = "Broken Hero"
hero_media = "hero.png"
+++
EOF
```
Now run `hugo server`, open the site, observer the large hero image at the top. Now force a reload: `touch content/post/something` and the hero image suddenly disappears as page resources becomes empty. You have to restart hugo server to get it back.

Interestingly if you do `touch content/home/something` the bug is NOT triggered, you have to touch something outside of content/home. Weird.

**Comment by jonsterling** [comment]
This is also happening to me on macos.

**Comment by jmooring** [comment]
Unable to reproduce with v0.111.3 on Linux or Windows. If you cross file system boundaries you may need to use the `poll` flag:

```text
hugo server --poll 700ms
```
