### ISSUE TITLE
standard flag for private page

### ISSUE THREAD

**Issue by matbesancon** [gohugoio/hugo#4770]
I was browsing through discussions to create a page only accessible from URL (not on site map, index, and not visible on RSS)
I found this discussion, last post by @bep in 2016, I was wondering if a standard way of doing this had been added.
My wish would be to be able to share pages for review only before making public, so a public = true/false working almost like drafts
https://discourse.gohugo.io/t/how-can-i-create-a-private-post/4583/4

**Comment by brunoamaral** [comment]
There isn't a standard added. 

If all you need is for the page not to be listed and have a few flags to block search engines from indexing, you can do it with params and a few changes to the template. I have that working with the parameter "unlisted". The source code is here: https://github.com/brunoamaral/future-imperfect-DI
