### ISSUE TITLE
Cannot test simple mode shortcodes with the latest Hugo.

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#4772]
Just submitted PR #4771

I was unable to test the `youtube_simple` shortcode locally with the latest Hugo out-of-the-box. 

The console was throwing the following error: 
 `Unable to locate template for shortcode "youtube_simple" in page "test/youtube.md"` 
I had to manually add a `youtube_simple` shortcode in a test project.

My config had the following:
```
[privacy]
[privacy.youtube]
disable = false
privacyEnhanced = false
simple = true
```

Other new features like the one in #4745 work as expected.

**Comment by bep** [comment]
Your PR has an error in it, which most likely explains this behaviour.

**Comment by onedrawingperday** [comment]
@bep Not sure if the error in #4771 was the cause.

Before I committed anything I compiled from gohugo/master with 
```
git checkout master 
git pull
go build -o hugo main.go
```
hugo version:
`Hugo Static Site Generator v0.41-DEV linux/amd64`

Then cloned your repo from `https://github.com/bep/hugotest` to test it locally.

I got the following
```
Building sites … ERROR 2018/05/25 11:07:22 Unable to locate template for shortcode "instagram_simple" in page "scodes/embedded-unstyled.md"
ERROR 2018/05/25 11:07:22 Unable to locate template for shortcode "instagram_simple" in page "scodes/embedded.md"
ERROR 2018/05/25 11:07:22 Unable to locate template for shortcode "instagram_simple" in page "section1/s1_1/hugo-rocks.md"
Total in 930 ms
Error: Error building site: logged 3 error(s)
```
