### ISSUE TITLE
Notes release 0.41

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4773]
* disqus can be turned off, but has its own "policy agreement"

**Comment by onedrawingperday** [comment]
I just want to note that users of Google Analytics, who do not want to create a user consent mechanism,  have to enable the full set of options that Hugo's Privacy Config offers for their site to be GDPR compliant.

Also in the Admin area of a Google Analytics property users should do the following:
-  Do not enable Advertising Features 
-  Do not enable the User ID
-  Specify the [Data retention](https://support.google.com/analytics/answer/7667196) period 
-  Review Google's [Data Processing Terms](https://support.google.com/analytics/answer/3379636)

If for some reason users do not want to do the above they need to obtain User Consent before they track visitors in their pages with Google Analytics.

**Comment by bep** [comment]
I don't want any words about "do this to be fully compliant". That is lawyers work. You and I cannot tell people to "do this and you are good to go". I'm very careful in this dance when documenting the settings. We provide some tools, you as a user must evaluate your site ...

**Comment by onedrawingperday** [comment]
Ok.

**Comment by bep** [comment]
Notes: #4732 Site.Info

Credits: onedrawingperday jhabdas c it-gro
