### ISSUE TITLE
Add non-cookie GA variant

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4775]
Default disabled.

See https://github.com/gohugoio/hugo/issues/4616#issuecomment-381555942

**Comment by onedrawingperday** [comment]
That's why I wrote it @bep for you to put in Hugo and so that others can benefit.

PS If you need any help with the docs for 0.41 let me know.

**Comment by bep** [comment]
Note to self, async: https://github.com/gohugoio/hugo/issues/4616#issuecomment-386968060
