### ISSUE TITLE
On build: convert JPGs larger than 1M into WEBP

### ISSUE THREAD

**Issue by vitaly-zdanevich** [gohugoio/hugo#4780]
And produced HTML for WEBP must contains `picture` instead of `img` for fallback:

```
<picture>
  <source srcset="img/awesomeWebPImage.webp" type="image/webp">
  <source srcset="img/creakyOldJPEG.jpg" type="image/jpeg"> 
  <img src="img/creakyOldJPEG.jpg" alt="Alt Text!">
</picture>
```

**Comment by bep** [comment]
Can you be more specific?

**Comment by onedrawingperday** [comment]
Also WEBM is not supported by all browsers, so this couldn’t be implemented as things are now.

Maybe this file format will replace JPG or maybe not.

**Comment by vitaly-zdanevich** [comment]
> Also WEBP is not supported by all browsers, so this couldn’t be implemented as things are now.

`picture` tag handle it - Firefox will show JPG.

**Comment by onedrawingperday** [comment]
No support in Safari. https://caniuse.com/#feat=webm

**Comment by vitaly-zdanevich** [comment]
> No support in Safari (desktop and iOS), Edge.

Safari and others support [picture](https://caniuse.com/#search=picture), please see [this article](https://css-tricks.com/using-webp-images/).

**Comment by flother** [comment]
Quite unfairly, JPEG has picked up a bad reputation. With [`mozjpeg`](https://github.com/mozilla/mozjpeg), Mozilla have shown that the assumed inadequacies of JPEG images are caused more by unoptimised encoders than the format itself. You can [read more at Performance Calendar](https://calendar.perfplanet.com/2014/mozjpeg-3-0/).

As a quick example, I took [this 4896×3264 image](https://unsplash.com/photos/5UjBY00ToG0) and then resized and re-encoded it using `libwebp`, `libjpeg`, and Mozilla's drop-in replacement for the latter, `mozjpeg`.

```bash
$ cwebp -resize 800 533 339839-orig.jpg -o 339839.webp
$ convert -resize 800x 339839-orig.jpg TGA:- | cjpeg -outfile 339839-libjpeg.jpg -targa
$ convert -resize 800x 339839-orig.jpg TGA:- | /usr/local/opt/mozjpeg/bin/cjpeg -outfile 339839-mozjpeg.jpg -targa
$ ls -lS 339839*
-rw-rw-rw- 1 matt 5224595 May 29 09:22 339839-orig.jpg
-rw-r--r-- 1 matt   83957 May 30 09:22 339839-libjpeg.jpg
-rw-r--r-- 1 matt   68841 May 30 09:22 339839-mozjpeg.jpg
-rw-r--r-- 1 matt   67340 May 30 09:22 339839.webp
```

You can see that although the `libjpeg` file is around 20% larger than the WebP file, the `mozjpeg` file gets to within 2.2% of the WebP. That's just using the defaults. If I tweak the parameters a little:

```bash
$ convert -resize 800x 339839-orig.jpg TGA:- | /usr/local/opt/mozjpeg/bin/cjpeg -quant-table 3 -optimize -outfile 339839-mozjpeg-optim.jpg -targa -smooth 10
$ ls -lS 339839-mozjpeg-optim.jpg
-rw-r--r-- 1 matt 57857 May 30 09:22 339839-mozjpeg-optim.jpg
```

This gives me a JPEG that's 16.4% *smaller* than the WebP file. The visual differences between all four re-encoded files is barely noticeable — subjectively I think the JPEG output is sharper, but for Web-use there's really little in it.

Now that's just one example of one file, of course, but my point is that WebP isn't definitively, objectively, better than JPEG.

**Comment by carlmjohnson** [comment]
Now that resources exist, this can be revisited as something like `{{ $img := resource.Get "big-picture.jpeg" | toWebM }}`.

**Comment by StephenBrown2** [comment]
I would love to see conversion functions like `toWebP`, `toPNG`, `toJPG`, maybe even `toGIF`, etc, as some recommendations prefer certain formats: https://developers.google.com/speed/docs/insights/OptimizeImages and https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization#selecting_the_right_image_format

**Comment by vitaly-zdanevich** [comment]
`function "resource" not defined`, hugo 0.44

**Comment by onedrawingperday** [comment]
@StephenBrown2 I think it would be best if you opened a separate GitHub issue with your feature request for these img conversion functions.

**Comment by StephenBrown2** [comment]
I was merely extending the suggestion @carlmjohnson made. I would prefer Hugo to not be biased toward one image conversion vs another.

**Comment by cromozooom** [comment]
if possible, this feature will help a lot of us :)

**Comment by kylewelsby** [comment]
This certainly would save me from having to use external services such as https://cloudinary.com/

**Comment by westurner** [comment]
WebP encoding would be a helpful feature.

**Comment by kylewelsby** [comment]
:+1: Bump

**Comment by LeviSchuck** [comment]
would totes like this

**Comment by kylewelsby** [comment]
anyone got a clue on where one could start to implement this?

**Comment by westurner** [comment]
This would definitely be useful.

**Comment by westurner** [comment]
Is there a different script that can be called while building that could
accomplish compress(img, config.compression_params) if stat(img).size >
config.compression_max_size and output a build message if size is still
greater than e.g. compression_max_size?

**Comment by DrSensor** [comment]
This article might be handy for supporting all browsers by choosing appropriate fallback.
https://joshwcomeau.com/performance/embracing-modern-image-formats/

**Comment by carlmjohnson** [comment]
https://www.macrumors.com/2020/06/22/webp-safari-14/ WebP is going to be in every major browser next fall.

**Comment by westurner** [comment]
Looks like https://github.com/gohugoio/hugo/blob/master/resources/images/image.go doesn't yet have:

- support for encoding as WebP
- a file size filter
- a check for an `already-encoded file.name._.webp`

Would the implementation of this feature be similar to https://github.com/gohugoio/hugo/blob/master/resources/images/smartcrop.go ?

**Comment by carlmjohnson** [comment]
The auto-convert part of this feature request strikes me as a mistake. I don't want images to change formats behind my back for no reason. What I would want would be the ability to specify the format and use the picture tag to do swap outs. In the future (5 years?), IE11 will be dead, and everyone will be using a modern browser, and all modern browsers will support WebP, so you can just use everywhere. But until then, you're going to want to use the picture tag, which means there needs to be the ability to spit out both Webp and JPEG given the same source image.

**Comment by StephenBrown2** [comment]
> What I would want would be the ability to specify the format and use the picture tag to do swap outs.

This is what I would want as well. Better to have the capability to convert source images and specify them in a picture fragment.

**Comment by alfinbi** [comment]
bump

**Comment by moorereason** [comment]
This is blocked by #5924, but I'm labeling it as a keeper since it has so many thumbs-up reactions (and I'm tired of the stale bot noise).
