### ISSUE TITLE
Orgmode: double hyphens not converted to em dashes

### ISSUE THREAD

**Issue by soldeace** [gohugoio/hugo#4781]
Hugo currently doesn't render multiple hyphens correctly. Ideally, the double hyphen (--) should be converted to em dash (—). Markdown double hyphens work correctly though.

**Comment by kaushalmodi** [comment]
Hello,

This issue belongs in the Go Org parsing [goorgeous][1] repo. 

@chaseadamsio Are you actively maintaining that project?

[1]: https://github.com/chaseadamsio/goorgeous

**Comment by soldeace** [comment]
Thanks! I'll post the issue there instead.
