### ISSUE TITLE
Toc on k8s.io is not correct if there is a code` in  title ##

### ISSUE THREAD

**Issue by lovejoy** [gohugoio/hugo#4793]
The toc of https://kubernetes.io/docs/setup/independent/high-availability/
have a link https://kubernetes.io/docs/setup/independent/high-availability/#run-code-kubeadm-init-code-on-code-master0-code is not correct 
and there is a correct link https://kubernetes.io/docs/setup/independent/high-availability/#kubeadm-init-master0 
how can the auto generated toc use the correct link ?

**Comment by bep** [comment]
You need to raise Kubernetes issue at their issue tracker:

https://github.com/kubernetes/website/issues

Note: This isn't a Hugo issue. It is probably _my_ fault, but still, not a Hugo issue.

For Hugo questions: https://github.com/kubernetes/website/issues
