### ISSUE TITLE
baseof.html not used unless its executable in Debian

### ISSUE THREAD

**Issue by GregoryVigoTorres** [gohugoio/hugo#4808]
Debian 9
hugo version: Hugo Static Site Generator v0.41 linux/amd64 BuildDate: 2018-05-28T06:30:57Z
(Issue also occurs with https://github.com/gohugoio/hugo/releases/download/v0.41/hugo_0.41_Linux-64bit.tar.gz)

 _default/baseof.html doesn't get used unless it has executable permissions (e.g. 755). Templates render, but they don't inherit from baseof and no errors are raised.

[edit] this has been solved

**Comment by bep** [comment]
That sounds very odd.

/cc @anthonyfok

**Comment by anthonyfok** [comment]
> That sounds very odd.

Indeed... (what does the executable permission have to do with it?)  But first, I'd have to learn how to use baseof.html (or baseof.ace, haha!).  I will investigate further.

**Comment by anthonyfok** [comment]
Hi @GregoryVigoTorres,

Could you please check and see if your path contains the string "baseof" at all?  See Issue #4809 (and proposed fix in PR #4810).  Thanks!

I couldn't reproduce your problem (on Debian sid).  Aside from #4809, `hugo` works equally well with layouts/_default/baseof.html having permission 644 or 755.  Is there a sample repository that you could provide for testing?

**Comment by GregoryVigoTorres** [comment]
I can no longer reproduce this either. 
There's something else going on and I don't know what it is. 
But, I swear yesterday changing the permissions (in another project I can't upload) fixed the problem :)
I initially tried changing the permissions because in the ananke (default?) theme baseof.html has 755 perms.

At any rate, when I try to build the site in the repo below, layouts/_default/baseof.html never gets rendered and there's no error message. I tried with 644 and 755 and neither worked.

[https://github.com/GregoryVigoTorres/hugo_site](https://github.com/GregoryVigoTorres/hugo_site)

**Comment by GregoryVigoTorres** [comment]
Thanks a lot for taking the time to provide such a detailed response to a newbie problem!
Putting everything inside the define block fixes everything.

I'm used to jinja2 and other template engines where blocks can be mixed with markup almost any way you like.


>So, this Go template behaviour is by design, and I think it is a reasonable design to resolve such dilemmas, though some kind of warning when it happens would be nice.  (My guess is that such a warning needs to be exposed by Go itself, might need to file an issue
>upstream for the Go team.)

I also think it would be nice if an error got raised when markup outside a define block is found. 
I'm completely new to go, however, so I think I should gain some more experience with the language before reporting issues upstream.


Gregorio

**Comment by anthonyfok** [comment]
> I'm used to jinja2 and other template engines where blocks can be mixed with markup almost any way you like.

Thank you for that insight!  No wonder quite a few other people got bitten by this issue!

> I also think it would be nice if an error got raised when markup outside a define block is found.

Yes, I think Hugo's main authors have also expressed the same wish.

Speaking as a casual contributor to Hugo, I do not yet know if Go raises such a warning/error so that Hugo can expose it.  I will investigate to satisfy my own curiosity in a new issue #4823.
