### ISSUE TITLE
Customize Params problem， I‘m new user

### ISSUE THREAD

**Issue by Rhinocros** [gohugoio/hugo#4811]
I have customized ".Params.download_link" in "single.html", but each article header can only use "download_link" to pass only one link. How can I make "download_link1", "download_link2"... The cycle is called when publishing, that is, the same page outputs multiple different links

**Comment by RealOrangeOne** [comment]
You could always make `download_link` a list in your frontmatter? All frontmatter formats support lists, and calling `.Params.download_link` will then be iterable

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
