### ISSUE TITLE
ReadingTime doesn’t go well together with code blocks

### ISSUE THREAD

**Issue by jotaen** [gohugoio/hugo#4815]
`ReadingTime` is only based on the word count. This doesn’t work well though for posts that contain a lot of code samples: the usage of whitespace is very much different in code blocks and they usually take significantly more time to read then an equal volume of plain text.

My suggestion is to use a different algorithm for code blocks as for plain text. As an idea, the reading time there could be rather dependent on (net) line length.

If you’re generally down for that idea I’d be willing to give this a shot with a PR.

**Comment by dkyleward** [comment]
Just wanted to second this. I'm new to Hugo, but I have a post with several plotly charts in them. When it renders, the reading time is 1808 minutes! It would be great if it was smart enough to know the difference. Alternatively, it would be fine if I could add a front matter tag to manually override it:

```
readingtime: "8 minutes"
```
