### ISSUE TITLE
`hugo new site` for existing directory

### ISSUE THREAD

**Issue by danburzo** [gohugoio/hugo#4825]
Not something very important, but is there a reason why `hugo new site` would not work with an existing directory? My instinctual workflow is to create a new Github repo, clone it to my computer, and add Hugo to it.

**Comment by danburzo** [comment]
I'm sorry, I 'll show myself out. It's only when I looked in the source code that I noticed the `--force` flag. 😬

**Comment by ITBuddha** [comment]
> I'm sorry, I 'll show myself out. It's only when I looked in the source code that I noticed the `--force` flag. 😬

A year later and I am out the same door....

**Comment by MagicMarvMan** [comment]
Me too 😄

**Comment by BrendanBall** [comment]
imho this isn't very obvious. Other projects have the convention of `--here` so that it creates in the current directory instead of creating a new subdirectory.

**Comment by share-dev** [comment]
hugo new site . --force
