### ISSUE TITLE
Gitlab buildDrafts = true on config file else posts with draft true on front matter would not rendered

### ISSUE THREAD

**Issue by nonumeros** [gohugoio/hugo#4828]
I guess buildDrafts is false by default, so any `draft=true` on the
front matter of the post, would render correctly with `hugo server
<flags/options>`

On the other hand, I've no idea if the recommended`.gitlab-ci.yml`
values somehow conflict with it 

     image: monachus/hugo
     #image: registry.gitlab.com/pages/hugo:latest

     
     variables:
       GIT_SUBMODULE_STRATEGY: recursive
     
     pages:
       script:
       - hugo
       artifacts:
         paths:
         - public
       only:
       - master

But if `buildDrafts = true` is not specified on the config file the
posts would not render. 

 
     baseURL = "http://nonumeros.gitlab.io/clic/"
     languageCode = "en-us"
     title = "My New Hugo Site"
     
     
     #buildDrafts = true
     
     theme = "lanyon"
     copyright = "&copy; 2016. All rights reserved."
     canonifyurls = true
     paginate = 10
     
     [indexes]
       tag = "tags"
       topic = "topics"
     
     
     [menu]
       # Shown in the side menu.
       [[menu.main]]
         name = "Home"
         pre = "<i class='fa fa-home fa-fw'></i>"
         weight = 1
         identifier = "home"
         url = "/"
       [[menu.main]]
         name = "Posts"
         pre = "<i class='fa fa-list fa-fw'></i>"
         weight = 2
         identifier = "post"
         url = "/post/"
       [[menu.main]]
         name = "About"
         pre = "<i class='fa fa-user fa-fw'></i>"
         weight = 3
         identifier = "about"
         url = "/about/"
       [[menu.main]]
         name = "Contact"
         pre = "<i class='fa fa-phone fa-fw'></i>"
         weight = 4
         url = "/contact/"

steps to reproduce

     hugo new site <test>
     cd <test>
     hugo new post/one.md
     hugo new post/two.md

Include the above **config.toml**
Include the above **.gitlab-ci.yml**

     hugo server -t <theme> -D

check `localhost:1313/<test>/`

Everything works as intended, posts show up, so no further changes are
needed

Kill the server

Run 

      hugo -t <theme> -D

Push the changes to Gitlab

check the project `gitlab.com/<username>/<test>/pipelines` and make
sure it passed

Now check the site at `<userame>.gitlab.io/<test>/`

Unless `buildDrafts = true` is specified on **config.toml** file,
posts would not render.

I checked this with 0.37 and 0.41

See https://gitlab.com/pages/hugo/issues/21

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
