### ISSUE TITLE
removePathAccents = true work not stable

### ISSUE THREAD

**Issue by anhchungite** [gohugoio/hugo#4832]
I use removePathAccents = true in config.toml file for remove accented in URL, but seem it work not stable with some characters.

![untitled](https://user-images.githubusercontent.com/28822504/41163976-3fcd3b8a-6b64-11e8-96a9-5aec55a0c442.png)

My permalinks config:
```
[permalinks]
  article = "/:year/:month/:title/"
```

**Comment by kaisax** [comment]
Same for German. Related Issue: https://github.com/gohugoio/hugo/issues/3476 (closed by bot)

**Comment by kuangthien** [comment]
I am facing a same issue :D removePathAccents  cannot detect "đ" as a non-ACSII charactor :D 
It's not safe for a URL , I think

**Comment by tgagor** [comment]
Similar thing with Polish language. We use accented characters like:
`ęóąśłżźćń ĘÓĄŚŁŻŹĆŃ`
they are converted to:
`eoasłzzcn-eoasłzzcn`
Almost good, just `ł` and bigger version `Ł` are not transformed properly.

I can generate slug on my own... but it would be nice if we could cover it.
Please let me know how can I help to get it fixed.

**Comment by andreseduardop** [comment]
Hi. Have you found any solution for this issue?
`removePathAccents` is not yet supported in Hugo's documentation
