### ISSUE TITLE
Hugo crash around multilanguage support

### ISSUE THREAD

**Issue by geeknoid** [gohugoio/hugo#4835]
I've got a working site and adding a [languages] block to my config.toml causes Hugo to crash. To repro:

- Grab https://github.com/istio/istio.github.io as of commit d3bc623376577041111c25ad579c48874967889a

- Add the following to the config.toml file:
[languages]
    [languages.en]
        contentDir = "content"
    [languages.fr]
        contentDir = "content_fr"
        title = "Istio Français"

- Run Hugo 0.41:

   ```
    $ hugo --log --verbose --verboseLog --debug
   ```

You'll get the following stack trace:

Building sites … panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17f93f5]

goroutine 7 [running]:
text/template.errRecover(0xc4227a75a0)
        /usr/local/Cellar/go/1.10.2/libexec/src/text/template/exec.go:137 +0x1d4
panic(0x195e6a0, 0x20f35c0)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
github.com/gohugoio/hugo/hugolib.(*Page).IsPage(...)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/hugolib/page.go:452
github.com/gohugoio/hugo/hugolib.(*Page).URL(0x0, 0x0, 0x0)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/hugolib/page.go:1133 +0x5
reflect.Value.call(0x1a38780, 0xc420b1d590, 0x13a93, 0x1a3eae3, 0x4, 0x2133850, 0x0, 0x0, 0x1a34940, 0x1, ...)
        /usr/local/Cellar/go/1.10.2/libexec/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x1a38780, 0xc420b1d590, 0x13a93, 0x2133850, 0x0, 0x0, 0xc42245a080, 0x13, 0x4e)
        /usr/local/Cellar/go/1.10.2/libexec/src/reflect/value.go:308 +0xa4
text/template.(*state).evalCall(0xc4227a7520, 0x1983180, 0xc420b1d580, 0x99, 0x1a38780, 0xc420b1d590, 0x13a93, 0x1c10440, 0xc4206a8750, 0xc4203b5beb, ...)
        /usr/local/Cellar/go/1.10.2/libexec/src/text/template/exec.go:667 +0x4f1
text/template.(*state).evalField(0xc4205df520, 0x1983180, 0xc420b1d580, 0x99, 0xc4203b5beb, 0x3, 0x1c10440, 0xc4206a8750, 0xc4206f47e0, 0x1, ...)
        /usr/local/Cellar/go/1.10.2/libexec/src/text/template/exec.go:557 +0xcad
text/template.(*state).evalFieldChain(0xc4205df520, 0x1983180, 0xc420b1d580, 0x99, 0x1983180, 0xc420b1d580, 0x99, 0x1c10440, 0xc4206a8750, 0xc420561e20, ...)
        /usr/local/Cellar/go/1.10.2/libexec/src/text/template/exec.go:525 +0x220
text/template.(*state).evalFieldNode(0xc4205df520, 0x1983180, 0xc420b1d580, 0x99, 0xc4206a8750, 0xc4206f47e0, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.10.2/libexec/src/text/template/exec.go:489 +0x118
text/template.(*state).evalCommand(0xc4205df520, 0x1983180, 0xc420b1d580, 0x99, 0xc4206a86f0, 0x0, 0x0, 0x0, 0xc4214f7000, 0x71, ...)
        /usr/local/Cellar/go/1.10.2/libexec/src/text/template/exec.go:427 +0x652
text/template.(*state).evalPipeline(0xc4227a7520, 0x1983180, 0xc420b1d580, 0x99, 0xc4206a65a0, 0x0, 0x0, 0x30)
        /usr/local/Cellar/go/1.10.2/libexec/src/text/template/exec.go:405 +0x10f
text/template.(*state).walk(0xc4227a7520, 0x1983180, 0xc420b1d580, 0x99, 0x1c102c0, 0xc4206a8780)
        /usr/local/Cellar/go/1.10.2/libexec/src/text/template/exec.go:231 +0x4a5
text/template.(*state).walk(0xc4227a7520, 0x1983180, 0xc420b1d580, 0x99, 0x1c10500, 0xc4206a8690)
        /usr/local/Cellar/go/1.10.2/libexec/src/text/template/exec.go:239 +0x11d
text/template.(*Template).execute(0xc4205576c0, 0x1c02fc0, 0xc4223a1730, 0x1983180, 0xc420b1d580, 0x0, 0x0)
        /usr/local/Cellar/go/1.10.2/libexec/src/text/template/exec.go:194 +0x1e6
text/template.(*Template).Execute(0xc4205576c0, 0x1c02fc0, 0xc4223a1730, 0x1983180, 0xc420b1d580, 0xc4205df620, 0x101335c)
        /usr/local/Cellar/go/1.10.2/libexec/src/text/template/exec.go:177 +0x53
html/template.(*Template).Execute(0xc4206a8630, 0x1c02fc0, 0xc4223a1730, 0x1983180, 0xc420b1d580, 0x1983180, 0xc420b1d580)
        /usr/local/Cellar/go/1.10.2/libexec/src/html/template/template.go:122 +0x8c
github.com/gohugoio/hugo/tpl.(*TemplateAdapter).Execute(0xc420b1d4c0, 0x1c02fc0, 0xc4223a1730, 0x1983180, 0xc420b1d580, 0x0, 0x0)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/tpl/template.go:81 +0x76
github.com/gohugoio/hugo/hugolib.aliasHandler.renderAlias(0x1c03420, 0xc42023d400, 0xc4204c0300, 0x1, 0xc4203b4600, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/hugolib/alias.go:84 +0x10f
github.com/gohugoio/hugo/hugolib.(*Site).publishDestAlias(0xc4204bc000, 0x1aa1401, 0xc4203b46f0, 0x2, 0x0, 0x0, 0x0, 0xc420039970, 0xc420039900)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/hugolib/alias.go:107 +0x2b2
github.com/gohugoio/hugo/hugolib.(*Site).renderAliases(0xc4204bc000, 0x1a73386, 0xe)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/hugolib/site_render.go:437 +0x8aa
github.com/gohugoio/hugo/hugolib.(*Site).render(0xc4204bc000, 0xc4227a7ee0, 0x0, 0x0, 0x0)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/hugolib/site.go:1000 +0x285
github.com/gohugoio/hugo/hugolib.(*HugoSites).render(0xc42023cf00, 0xc4227a7ee0, 0x0, 0x0)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/hugolib/hugo_sites_build.go:246 +0x2be
github.com/gohugoio/hugo/hugolib.(*HugoSites).Build(0xc42023cf00, 0x0, 0xc420c060f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/hugolib/hugo_sites_build.go:64 +0x139
github.com/gohugoio/hugo/commands.(*commandeer).buildSites(0xc4202fb450, 0x0, 0x0)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/commands/hugo.go:692 +0x8d
github.com/gohugoio/hugo/commands.(*commandeer).fullBuild.func3(0x8, 0x1aeee50)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/commands/hugo.go:286 +0x2e
github.com/gohugoio/hugo/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc42002de40, 0xc4200af1d0)
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/gohugoio/hugo/vendor/golang.org/x/sync/errgroup.(*Group).Go
        /private/tmp/hugo-20180526-43964-geoga5/hugo-0.41/src/github.com/gohugoio/hugo/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66

The resulting log file is: [log.txt](https://github.com/gohugoio/hugo/files/2087076/log.txt)

If you add 'disableAliases' to config.toml, Hugo doesn't outright crash but it still fails. The resulting log file is: [log-noaliases.txt](https://github.com/gohugoio/hugo/files/2087085/log-noaliases.txt)

I am running Hugo 0.41 on MacOS 10.13.4

**Comment by bep** [comment]
See https://github.com/istio/istio.github.io/pull/1493

You should double-check that PR, I quickly made the build work.

We have an open issue about improving the nil-pointer handling. we usually don't panic, but we should ideally provide a more useful error/stack trace. But I suspect we need some help from the Go team to get there ... It is on my list of TODOS.

**Comment by geeknoid** [comment]
Thank you.
