### ISSUE TITLE
.GetPage "page" "some-headless-bundle" doesn't use the full file path

### ISSUE THREAD

**Issue by stp-ip** [gohugoio/hugo#4837]
Content structure
```
content/headless/index.md
content/blog/headless/index.md
```

Code
```
{{ Site.GetPage "page" "headless" }}
{{ Site.GetPage "page" "blog/headless" }}
```

Both queries result in the same bundle. The bundle from within the blog is always preferred.
Without the headless bundle under the blog section the problem isn't there.

**Comment by bep** [comment]
This is well covered in https://github.com/gohugoio/hugo/pull/4796 and the issues that points to.

For now, you need to control this ambiguity in your naming scheme.

**Comment by stp-ip** [comment]
Thanks for pointing me to the right issues. Seems there was a workaround, but being exact still doesn't work.
```
{{ Site.GetPage "page" "headless/index.md" }}
{{ Site.GetPage "page" "blog/headless/index.md" }}
```
It doesn't enable me to get the actual page from `content/headless/index.md`, which feels really counterintuitive.
