### ISSUE TITLE
Add static filesystem to readFile lookup

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4842]
[Ref][1]

From the example in the above thread, if one needs to refer to a theme's static file, they need to give the full path starting from the site root directory:

```
readFile "themes/hugo-search-fuse-js/static/js/search.js"
```

While it works, it relies on the `themesDir` to be `themes` and the theme name to stay between the theme author and theme user.

I believe, adding static filesystem should allow the below to work:

```
readFile "js/search.js"
```

[1]: https://discourse.gohugo.io/t/is-there-any-way-for-a-theme-to-retrieve-the-themedir-value/12368/2?u=kaushalmodi

**Comment by jmooring** [comment]
I'm not sure when the behavior changed, but v0.111.3 works as desired.

```text
themes/hugo-search-fuse-js/
└── static/
    └── js/
        └── search.js
```

Then read from a template in the project's layouts directory:

```
{{ readFile "/static/js/search.js" }}
```
