### ISSUE TITLE
Install theme documentation discrepancy

### ISSUE THREAD

**Issue by vkatsikaros** [gohugoio/hugo#4844]
The documentation suggests 2 ways of installing a theme:

1) [Quick Start](https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme) `git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke`

2) [Install and Use Themes](https://gohugo.io/themes/installing-and-using-themes/#install-a-single-theme) `git clone URL_TO_THEME`

I understand the implications of git submodules VS cloning the repo but:

a) An inexperienced git user could be confused by the discrepancy.

b) As an experienced git user I am wondering what is the suggested approach in using themes, provided that some minimal theme customization will be needed.

I would expect to see a single theme to be installed in both documentation pages. Alternatively I would expect some comments on suggested approach on theme customization/maintenance.

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues
