### ISSUE TITLE
Make .Paginator work from inside shortcodes

### ISSUE THREAD

**Issue by timsluis** [gohugoio/hugo#4852]
**The issue**
When you use the paginator inside a shortcode, every paginated page contains the same items (which originally belongs only to page 1).

Use the following code inside a shortcode to reproduce:
```
{{- range $.Page.Paginator.Pages -}}
   {{ .Name }}
{{- end -}}
```
Use the shortcode on a section, list or taxonomy page to see the issue.

**Expected behaviour**
Pagination should work normally inside a shortcode. Just as it would inside a layout.

**Environment**
Version of Hugo: 0.42.1
OS: OS X 10.13.4

**Comment by knutov** [comment]
unstale please.

The problem looks actual: 
```
execute of template failed: template: shortcodes/....html:3:28: executing "shortcodes/......html" at <.Paginate>: can't evaluate field Paginate in type *hugolib.ShortcodeWithPage
```
