### ISSUE TITLE
After Update Hugo from 0.41 to 0.42.1 the static files are missing

### ISSUE THREAD

**Issue by joergklein** [gohugoio/hugo#4857]
After Update Hugo from 0.41 to 0.42.1 the static files are missing. 

Hugo version: Hugo Static Site Generator v0.42.1 linux/amd64 BuildDate: 2018-06-13T10:16:36Z

I changed nothing on my Page. I would only update Hugo. This error is on my multi language page. On my single language Page the Update works fine.

**Comment by bep** [comment]
Your config.toml isn't valid TOML, which may or may not be the cause of this. Only maps can follow another map.

**Comment by joergklein** [comment]
Please give me a little help. I don't know were I have to look for
.

**Comment by bep** [comment]
You need to move the "defaultContentLanguage*" settings near the top (above the maps/dicitonaries)

**Comment by joergklein** [comment]
here is my changed config.toml

title = "Example"
languageCode = "en-us"

# Language configuration
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

[languages]
    [languages.en]
        baseURL = "https://example.com/"
        languageName = "Englisch"
        languageCode = "en-us"
        contentDir = "content/en"

    [languages.de]
        baseURL = "https://example.de/"
        languageName = "German"
        languageCode = "de-de"
        contentDir = "content/de"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"

enableRobotsTXT = "true"

theme = "home"
canonifyurls = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[sitemap]
    ChangeFreq = "weekly"
    Priority = ".5"

[params]
    # General information
    author = ""
    description = "Website"
    publisher = "example.com"
    copyright = "example.com"

    # Repository
    provider = "GitLab"
    repo_url = "https://gitlab.com//example/homepage"

    version = "0.1.0"
    logo = "images/Logo-Standard.jpg"

    # Fonts
    googlefonts = [
        "Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic",
        "Roboto+Mono:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic"
        ]

**Comment by bep** [comment]
>[languages]

The above starts a map definition.

>theme = "home"

The above is a single property. That and similar need to be above all maps definition.

Take further questions/trouble shooting on https://discourse.gohugo.io/

We can bring it back here if it is a real bug.

**Comment by StephenBrown2** [comment]
Try putting your TOML in https://toolkit.site/format.html and attempting to parse it.

Pasting what you gave above gives the error 'Value for "contentDir" should not be redefined in the same table.'

Unfortunately I find that TOML isn't always as "Obvious" as it wants to be, but what @bep said is right, you need to put all the single-value items at the top of the file.
