### ISSUE TITLE
Hugo static pages 

### ISSUE THREAD

**Issue by Nate-dogg007** [gohugoio/hugo#4859]
Hi 

I've been having some issues with getting pages to show when using Huge. I'm running this locally. using localhost:1313 my homepage shows, my contact page shows and my blog shows but no content on the blog! so I ran the command "hugo server -D" it created a new localhost:xxxx and the blog content showed but the contact page now results in a 404.

**Comment by Nate-dogg007** [comment]
in layouts, I've created 3 folders _default, blog and contact inside blog and content folder I have list.html and in the content folder, I have a folder called blog with my .md files and a _index.md file. Like 

I said if I run hugo server -D in terminal and use the new localhost its generated I can see all the content but once I run the command hugo server it generates a new localhost and I get a 404.

I have no idea why I can't get the contact page to display

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
