### ISSUE TITLE
broken link 

### ISSUE THREAD

**Issue by yooxinz** [gohugoio/hugo#4860]
There is an invalid link in [highlight.md](https://github.com/gohugoio/hugo/blob/master/docs/content/en/functions/highlight.md).

`Syntax Highlighting` is invalid

**Comment by kaushalmodi** [comment]
@yooxinz The links wouldn't work when clicked in the GitHub .md renders.. All links work on https://gohugo.io/functions/highlight/.

Also, going forward, please file issues related to the doc site at https://github.com/gohugoio/hugoDocs/issues.

**Comment by yooxinz** [comment]
Ok, thanks for getting in touch.
