### ISSUE TITLE
Render in Page bundles not working - was working in 0.40.2

### ISSUE THREAD

**Issue by jrisch** [gohugoio/hugo#4861]
I've used the Render function inside Page bundles extensively throughout the month of april without problems. After having a month long break from coding, I started up again in june, but with the newest versions of Hugo, the `hugo server` command fails with:

`Failed to render "_default/page.html": runtime error: invalid memory address or nil pointer dereference`

You can test with this test site: https://github.com/jrisch/hugo-test

Building the site or running `hugo server` with version 0.40.2 works fine, but newer versions does not.

**Comment by reber0** [comment]
@jrisch I met the same problem, did you solve it?

**Comment by nonumeros** [comment]
@jrisch  I agree with the non-working versions part, but it can't possibly be solely the `Render` function because if you were to have e.g.
      
     {{ define "main" }}
      {{ range .Data.Pages }}
       {{ .Render "codeexample"}}
      {{ end }}
     {{ end }}


instead of 

    {{ define "main" }}
    {{- with .Resources.Match "codeexample.md" }}
    {{- range . }}
    {{ .Render "codeexample" }}
     {{- end }}
     {{- end }}
    {{ end }}

on page.html then you'd notice it works under the latest version

**Comment by jrisch** [comment]
@nonumeros You're correct that the `hugo serve` command works when using your code, but the product page renders empty. :-(

**Comment by jrisch** [comment]
The newest hugo version (0.46) throws a stack trace - don't know if that is helpful:

```
Building sites … ERROR 2018/08/07 11:13:16 Failed to render "_default/page.html": programming error: no mainPageOutput for "products/myproduct/codeexample.md"
ERROR 2018/08/07 11:13:16 Stack Trace:
goroutine 57 [running]:
github.com/gohugoio/hugo/hugolib.stackTrace(0x4b0, 0x4c95113, 0x17)
	/private/tmp/hugo-20180801-41150-1lexkxf/hugo-0.46/src/github.com/gohugoio/hugo/hugolib/page.go:280 +0x76
github.com/gohugoio/hugo/hugolib.(*Site).renderForLayouts.func1(0xc4207ff8a0, 0xc42025a300)
	/private/tmp/hugo-20180801-41150-1lexkxf/hugo-0.46/src/github.com/gohugoio/hugo/hugolib/site.go:1742 +0x135
panic(0x4b12440, 0xc4204de420)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
text/template.errRecover(0xc4207ff790)
	/usr/local/Cellar/go/1.10.3/libexec/src/text/template/exec.go:143 +0x1ba
panic(0x4b12440, 0xc4204de420)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/gohugoio/hugo/hugolib.(*Page).Render(0xc420172000, 0xc4204de3b0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/hugo-20180801-41150-1lexkxf/hugo-0.46/src/github.com/gohugoio/hugo/hugolib/page_output.go:159 +0x163
reflect.Value.call(0x4c41880, 0xc420172000, 0xfa13, 0x4c47533, 0x4, 0xc4204076e0, 0x1, 0x1, 0x4c3c080, 0x1, ...)
	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x4c41880, 0xc420172000, 0xfa13, 0xc4204076e0, 0x1, 0x1, 0x4e28e00, 0xc4206
Total in 3 ms
Error: Error building site: logged 2 error(s)
```

**Comment by nonumeros** [comment]
> The newest hugo version (0.46) throws a stack trace

@jrisch It doesn't. It shouldn't return a stack trace

because of case-insensitive pattern matching  you'd have to `{{- with .Resources.Match "codeexample.md/*" }}`. Notice the  `/*` (unless I'm missing something)

     {{ define "main" }}
     {{- with .Resources.Match "codeexample.md/*" }}
       {{- range . }}
         {{ .Render "codeexample" }}
       {{- end }}
     {{- end }}
     {{ end }}

**Comment by jrisch** [comment]
@nonumeros OK. That fixes the stack trace. But it still renders the product page empty. :-/
