### ISSUE TITLE
Unable to load Disqus

### ISSUE THREAD

**Issue by hakuoku** [gohugoio/hugo#4864]
When I updated Hugo the latest version I met that it didn’t load disqus comments both locally and remotely. So I’ve replaced Hugo’s version in sequence, found v0.34 and former worked successfully.

I include my disqusShortname in params section of config.toml and {{ template "_internal/disqus.html" . }} line in single.html of [Hugo Frais](https://themes.gohugo.io/hugo-frais/) theme properly(maybe).

Where internal template is, such HTML & JS below are embeded with v0.34 but after v0.35 the field goes completely blank.

I used Windows 32bit versions on Windows10 v1803 consistently.

```JavaScript
<div id="disqus_thread">
    Disqus comments not available by default when the website is previewed locally.
</div>
<script>
    var disqus_config = function () {};
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "mydisqususername" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>
    Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
```

**Comment by hakuoku** [comment]
"mydisqususername" is placeholder I set to submit issue here. Actually that line is:

```javascript
s.src = '//' + "hakuoku" + '.disqus.com/embed.js';
```

And the problem with v0.35 and later continues...

**Comment by it-gro** [comment]
I can't reproduce.
Having
```toml
disqusShortname = "it-gro-github-io-hugo-theme-w3css-basic-github-io"
```
in `config.toml`

Using
```
{{ template "_internal/disqus.html" . }}
```
I get this resulting html for disqus:
```
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "it-gro-github-io-hugo-theme-w3css-basic-github-io" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());

```

looks good to me...

```
Hugo Static Site Generator v0.42.1 linux/amd64 BuildDate: 2018-06-13T10:16:36Z
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.10.1"
```

**Comment by hakuoku** [comment]
Sorry, it was my stupid mistake.
I didn't place my disqusShortname line in plain config.toml area but it's params area.  So it hadn't worked.
Thanks for your kind advice, anyway 🙇
