### ISSUE TITLE
Theme Component Scaffolding

### ISSUE THREAD

**Issue by jhabdas** [gohugoio/hugo#4869]
[Theme Components](https://gohugo.io/themes/theme-components/) were introduced in `0.42` with https://github.com/gohugoio/hugo/issues/4467. Running `hugo new -h` on the `0.42.1` CLI produces the following available commands:

```
site        Create a new site (skeleton)
theme       Create a new theme
```

I would like to propose a new scaffolding for theme components called `component` or, if it makes more sense, a flag or subcommand for `theme` to produce a minimum viable theme component.

**Comment by bep** [comment]
>a minimum viable theme component.

That is currently very subjective. One static folder with a file is a component.

**Comment by jhabdas** [comment]
Per the docs:

> Also note that a component that is part of a theme can have its own configuration file, e.g. config.toml. There are currently some restrictions to what a theme component can configure:

> - params (global and per language)
> - menu (global and per language)
> - outputformats and mediatypes

So I was thinking MVP is a `theme new` with a config file containing the above bullet items under comment.

**Comment by jhabdas** [comment]
I'll close this for now as a nice to have. Please feel free to reopen if it interests you Mr Bep.
