### ISSUE TITLE
Test fails on Go 1.11

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4873]
See https://travis-ci.org/gohugoio/hugo/jobs/395910881

**Comment by anthonyfok** [comment]
Thank you so much for bringing this issue to my attention!
No more API breaking change in go1.11 according to golang/go#25968!  I will revert my previous "fix" right away.

**Comment by anthonyfok** [comment]
Full commit log:

Revert "tpl: Support text/template/parse API change in go1.11"

Go developers have undone the breaking API changes in the following commit:

> commit bedfa4e1c37bd08063865da628f242d27ca06ec4
> Author: Daniel Theophanes <kardianos@gmail.com>
> Date:   Thu Jun 21 10:41:26 2018 -0700
> 
>     text/template/parse: undo breaking API changes
> 
>     golang.org/cl/84480 altered the API for the parse package for
>     clarity and consistency. However, the changes also broke the
>     API for consumers of the package. This CL reverts the API
>     to the previous spelling, adding only a single new exported
>     symbol.
> 
>     Fixes #25968
> 
>     Change-Id: Ieb81054b61eeac7df3bc3864ef446df43c26b80f
>     Reviewed-on: https://go-review.googlesource.com/120355
>     Reviewed-by: Daniel Martí <mvdan@mvdan.cc>
>     Reviewed-by: Rob Pike <r@golang.org>
>     Run-TryBot: Daniel Martí <mvdan@mvdan.cc>
>     TryBot-Result: Gobot Gobot <gobot@golang.org>

See golang/go#25968

This reverts commit 9f27091.

Closes #4784
Fixes #4873
