### ISSUE TITLE
ignoreFiles does not work as documented

### ISSUE THREAD

**Issue by raxod502** [gohugoio/hugo#4874]
I cannot get the example from the documentation of `ignoreFiles` to work in a brand new project.

Using Hugo 0.41 on macOS 10.11.6, I created a new site using `hugo new site testing` and added the following to `config.toml` [as per the documentation of `ignoreFiles`](http://gohugo.io/getting-started/configuration/#ignore-files-when-rendering):

```toml
ignoreFiles = [ "\\.foo$", "\\.boo$" ]
```

The documentation says that this should

> cause Hugo to ignore files ending with `.foo` and `.boo` when rendering

but when I create a file at the path `static/example.foo` and run `hugo`, it is copied to `public/example.foo`, i.e. not ignored at all.

It seems that either there is a bug in Hugo or the documentation must be updated.

**Comment by XhmikosR** [comment]
This is still valid and it seems there a PR available #5312

**Comment by stapelberg** [comment]
I’ve sent PR https://github.com/gohugoio/hugo/pull/5649 to address this issue

**Comment by stapelberg** [comment]
This isn’t stale, and I have sent a PR to fix the issue.

**Comment by alertedsnake** [comment]
Ugh, this is exactly the problem I'm having!  Thanks for the fix, I've built hugo from your fork.

**Comment by XhmikosR** [comment]
This is still a valid issue and has a PR

**Comment by XhmikosR** [comment]
This is still a valid issue and has a PR

**Comment by alertedsnake** [comment]
Stale bots are great, aren't they?  This is still a valid issue and has a PR.

**Comment by alertedsnake** [comment]
Still a bug with an open pr! Maybe someone could look at this or disable the stake bot?

**Comment by davidsneighbour** [comment]
The PR has answers with requests and suggestions by @bep that were ignored. Listening to the maintainer of the project might be a better idea than just arbitrarily removing stale labels. Stale means no progress was made on this issue and no progress has been made. The poster of the PR should add the suggestions by bep and then things might happen. 

https://github.com/gohugoio/hugo/pull/5649#issuecomment-553296120

If you understand, that developer resources are sparse on this project then you hopefully understand, that other issues (like bug) are more pressing than this. 

And no, the stale bot does not need to be disabled, he brings exactly that: clarity on stale issues. @stapelberg should amend or discuss the PR OVER THERE, and everyone not able to contribute (me included, I am not good at GoLang) should let issues leave stale. And maybe we should all lean GoLang :)

**Comment by alertedsnake** [comment]
I'm sorry, the stale bot says if we still have the issue on the master branch, to say so. I have done that. Not sure why this needs to be a larger issue.

**Comment by davidsneighbour** [comment]
Wouldn't in that case be something like "@stapelberg, did you see @beps responses on your PR" be better than "Stale bots are great, aren't they"? He already said over at the PR that he has no time to implement the changes. 

It seems to be a larger project to implement that and it's a feature, not a bug. The documentation got updated in the meantime to explicitly put `ignoreFiles` on the content directory only, and the static directory is always copied on file changes. 

If you want a file in static to be ignored, why would that be? I think there might be a conceptual flaw behind this feature request. If files are needed so they can be somehow converted to something else, then a better place might be in assets or even outside of the whole folder system as Hugo knows it (src, stuff). If your editor or IDE places temporary files right next to the file it edits, then it surely has an option to place this file in a filecache somewhere else. Not only hugo bug also other "blind" commands like "git add -A" might add those unwanted files. In the case of git a `git clean` will remove ignored files (`git clean -n` will do a dryrun before). 

See, we are talking and thinking.

**Comment by alertedsnake** [comment]
Still not sure why you're making my comment, which clearly followed the instructions from the stale bot, into a larger issue.  I will apologize for my snark though - I'm not a fan of stale bots, and I let that show.

I'll agree (in reading back to @bep's comment in the PR) that this bug as written could be closed as "fixed" if the `ignoreFiles` feature is now documented, and if we would prefer to discuss the feature request elsewhere.

**Comment by davidsneighbour** [comment]
Over at discourse.gohugo.io is a good place :)

I am not making _your_ comment an issue, I am making the strategy of "bumping" stale-labelled issues on Github an, ehm, issue. Sorry about that. If you look through the issues that were marked as stale today you will see that many just get un-staled by adding nothing to progress them. And if you look through changes that are added in each version you will see, that there are really not many resources to work through these issues. Many of these issues tend to be very specific use cases with very unspecific descriptions and most time can be solved by diving deeper. That's all. As long as the PR is open someone with GoLang coding knowledge might have a look. Let's get this issue go stale.

**Comment by alertedsnake** [comment]
If that's a policy for this repo, it's perfectly fine by me, but again, I was just following instructions provided by the stale bot, assuming this was the desired practice.

**Comment by jmooring** [comment]
This was addressed with a documentation change, https://github.com/gohugoio/hugoDocs/commit/7427a1fc52594320a2abff857de665dacd1cd7e9.
