### ISSUE TITLE
Config changes does not properly reload in server mode

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4878]
Not sure when that happened.

/cc @anthonyfok

**Comment by GrandNewbien** [comment]
I thought this was related to issue [#4424](https://github.com/gohugoio/hugo/issues/4224), where I can confirm double write events on my own machine.

**Comment by bep** [comment]
@GrandNewbien this is a fairly new regression -- we are lacking in test coverage in this area, but I'm using this all the time ...

**Comment by almai** [comment]
Server reload happens only once after the first change of config.toml. 2nd change doesn't get recognized. No output in debug or verbose mode.

Running on v0.45.1, macOS 10.13.5

**Comment by primercuervo** [comment]
I'm facing the same as @almai reports. Running on Ubuntu 18.04. Reload works the first time as expected, but in order to see the changes after that I have to manually restart the server

```
$ hugo version
Hugo Static Site Generator v0.40.1 linux/amd64 BuildDate: 2018-04-25T17:16:11Z
```

**Comment by primercuervo** [comment]
Just tested it with the latest release

```
$ hugo version
Hugo Static Site Generator v0.40.1 linux/amd64 BuildDate: 2018-04-25T17:16:11Z
```

running just `hugo server` or adding the `--disableFastRender` and/or `--ignoreCache` yields to the same result (reload working only once)

**Comment by anthonyfok** [comment]
I wonder if this and #4701 (and #4224 mentioned above) are related.  Need to take a closer look again.
(Sorry I left #4701 and #4702 stale for too long.)

**Comment by almai** [comment]
Yes, this bug is still there, nothing has changed so far. If I change config.toml twice it doesn't get recognized and I have to restart the server.

**Comment by anthonyfok** [comment]
#5205 

> I can confirm the issue still exists in the latest version on Ubuntu 16.04:
> Hugo Static Site Generator v0.53 linux/amd64 BuildDate: 2018-12-24T12:58:43Z
> 
> The first time you save config.toml, it recognizes and reloads, subsequent changes are ignored.

@mpaepper Please test the latest v0.54 and see if the problem is fixed for you.  See also discussions at #5205

**Comment by mpaepper** [comment]
> #5205
> 
> > I can confirm the issue still exists in the latest version on Ubuntu 16.04:
> > Hugo Static Site Generator v0.53 linux/amd64 BuildDate: 2018-12-24T12:58:43Z
> > The first time you save config.toml, it recognizes and reloads, subsequent changes are ignored.
> 
> @mpaepper Please test the latest v0.54 and see if the problem is fixed for you. See also discussions at #5205

Thank you @anthonyfok 
I can confirm it works for me in v0.54 :+1:

**Comment by almai** [comment]
Any update on this. Please let us know what if you will take care of it. Thanks 🙏🏼
