### ISSUE TITLE
Add HTTPS to hugo server

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4883]
Via https://github.com/FiloSottile/mkcert

Only OSX and Linux for now, Windows promised ...

**Comment by akshaybabloo** [comment]
I think the support for Windows has been added

**Comment by Fale** [comment]
As far as I can see, it is now available on Windows as well!

**Comment by wouter-muller** [comment]
What is the status on this? This would be really useful for a current project, where we need to access a remote API that only allows TLS connections...

**Comment by Seirdy** [comment]
I'm not sure what benefit this would add over simply running `hugo -w` and using a dedicated static web server to serve files in the `public/` directory. A rudimentary HTTP server via the `serve` command makes sense for quick testing, but more sophisticated web server features like HTTPS probably belong in a dedicated program. I think Hugo should stick to being an SSG.

**Comment by wouter-muller** [comment]
@Seirdy @bep Thanks for looking into this!

As a (we were hoping temporary) workaround, we are now using Caddy to get TLS, and reverse-proxying Hugo. It works, but it is a relatively complex set-up (we had to do some trickery to get LiveReload working again). Having said that, i do understand that local TLS is maybe not something one can expect from an SSG.

**Comment by jmooring** [comment]
Closing as duplicate of https://github.com/gohugoio/hugo/issues/11064.
