### ISSUE TITLE
Loading failed for the <script> with source “http://localhost:1313/javascripts/modernizr.js”.

### ISSUE THREAD

**Issue by BenBergman** [gohugoio/hugo#4884]
Trying to run my site with hugo 0.42.1 (after using the env var workaround from #4851) results in a broken theme. My site works fine if I downgrade hugo to 0.40 (I happened to have this available in homebrew at the time).

When loading my site with the env var workaround, I get the following message in the browser's JS console:

```
Loading failed for the <script> with source “http://localhost:1313/javascripts/modernizr.js”.
```

`public/javascripts/modernizr.js` exists when I run `hugo server`, but wget also fails to retrieve the file so I'm not sure why it isn't being served. Other files in that directory work fine.

For reference, the theme I'm using is [hugo-material-docs](https://github.com/digitalcraftsman/hugo-material-docs) and their example project (with [minor tweaks](https://github.com/digitalcraftsman/hugo-material-docs/pull/92)) works fine in 0.42.1

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by BenBergman** [comment]
I see someone else just opened a ticket about multilingual sites not pulling contents from themes (#4929) so this ticket can stay close and I will follow that thread instead.
