### ISSUE TITLE
Facilitate pluralization of localized strings

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#4887]
`pluralize` is great to pluralize english language strings. Yet it is useless in other languages.

I can see two options to facilitate this.

1. **optimizing pluralize:**
https://github.com/nicksnyder/go-i18n boasts the implementation of pluralized strings from 200+ languages. Maybe this feature from an already included package can be used. Then `pluralize` takes a second optional parameter in the form of a language code. (Or Hugo can guess the language)

2. **Optimizing i18n function** 
User can enter the plural version of a string directly in their `i18n` file:
```
- id: horse
  translation: "Cheval"
  plural: "Chevaux"
```
`i18n` takes a second optional parameter as a an `int`. If `int` is > 1, Hugo uses `i18n` file's translation plural, if not available, it uses `go-i18n` multilingual pluralize ability to pluralize the string itself. (Or do nothing)
```
{{ i18n "comment" (len .Params.comments) }}
```

Forgive me if there is already an undocumented convenient way of doing this.

**Comment by bep** [comment]
I don't think `go-18n` boasts about that. From the last time I spent time in that domain, it **detects** plurals for a given language, which we support in Hugo. But that is a way to detect either the "one" or the "plural" variant of two strings. "I have one apple" vs "I have many apples". There is no magic translation from the first to the other. You need to maintain that yourself. But you can.

**Comment by bep** [comment]
>Now dropping this "plural guessing" thing, would my second proposition be too complicated to implement? 

I suspect this is a documentation issue. This is supported.

https://github.com/bep/hugotest/blob/master/i18n/en.toml#L1

**Comment by regisphilibert** [comment]
Thanks! I will look into it.

**Comment by regisphilibert** [comment]
This was perfectly documented... https://gohugo.io/content-management/multilingual/#translation-of-strings This is the one part I skipped while improving the Multilingual page, thinking and I quote: "This section is perfect"... 

Sorry about that.
