### ISSUE TITLE
UTF-8-BOM In Layouts Results In Blank Page

### ISSUE THREAD

**Issue by crash-dive** [gohugoio/hugo#4895]
Hugo Version: v0.42.2 windows/amd64 BuildDate: 2018-06-28T12:36:53Z
OS: Windows 10

When certain layouts files start with a BOM the pages fail to render. This does not impact all files though.

Our layout folder contains:

* _default
    * baseof.html
    * home.html
    * section.html
    * single.html
* partials
    * services.html
* shortcodes
    * partial.html

The shortcodes and partials work perfectly fine when they have a BOM. In _default baseof.html works fine with a BOM, however home, section & single do not. When they have a BOM the rendered page is just blank. All our content files have BOMs.

The home, section and single files are really simple and look like:

```
{{ define "main" }}
    {{ .Content }}
{{ end }}
```

Other people have had this problem https://discourse.gohugo.io/t/baseof-html-block-templates-and-list-types-results-in-empty-pages/5612/12

This can obviously be fixed by changing the encoding of the file but all our projects are standardised on with a BOM so it would be great if all files could be the same.

**Comment by bep** [comment]
This looks like a bug in Go: https://github.com/golang/go/issues/28482

I will work around it at our end by trimming away the BOM marker before we send it to the Go parser.

**Comment by crash-dive** [comment]
@bep Just wanted to say thanks for reviewing and fixing this. Hugo is a great tool and all the work done on it is really appreciated!
