### ISSUE TITLE
Modifiable TODO lists in Blackfriday

### ISSUE THREAD

**Issue by psa** [gohugoio/hugo#4899]
Currently, the task list item generates

```
<input type="checkbox" checked disabled class="task-list-item">
```

However, I'd like to have a task list that my users can check off (e.g. bring up a page with a flight packing list and check things off as they go). Could you please add a flag which removes the disabled flag?

**Comment by bep** [comment]
Hugo is a static site generator. How do you suggest we implement this?

**Comment by psa** [comment]
I created a potential implementation in #4901

Obviously, being static, I don't need it to save the changes. Being able to modify the checkboxes in my view of the page is useful (bring up checklist, check things off as I go) though.

**Comment by bep** [comment]
I don't think we can add this to Hugo. People will have expectations when they "check a box", that it will stay checked. Hugo is a static site generator.
