### ISSUE TITLE
I hope I can manage articles like the following folders.

### ISSUE THREAD

**Issue by advsets** [gohugoio/hugo#4907]
First of all, this question has been mentioned before, but it has been closed.
#4558, #4609

I hope I can manage articles like the following folders.
![image](https://user-images.githubusercontent.com/8299627/42390360-30758c70-817e-11e8-954f-a0fc4ba1d382.png)

like [gatsby-starter-hero-blog](https://github.com/greglobinski/gatsby-starter-hero-blog)

I use `{{ printf "%#v" . }}` not found the folders variable，so I can't resolve it.
I hope write a related demo, or give it a train of thought。
Think very much.

**Comment by Jos512** [comment]
You can use [page bundes](https://gohugo.io/content-management/page-bundles/#readout) to keep images and content together in the same folder.

For questions like these, feel free to post them on the [Hugo forum](https://discourse.gohugo.io/). We typically use GitHub only for possible bugs and technical development discussions.

**Comment by advsets** [comment]
ohh ，thank you very much
