### ISSUE TITLE
Tags with upper case characters

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#491]
Does not work as documented.

Tag `SomeTag` will create folder `sometag` and if one then follow the documentation to create links it doesn't work as expected:

`<a href="tags/{{ . | urlize }}">{{ . }}</a>` -> `tags/SomeTag` (also note .the missing slash in front of the URL)

Workaround:

`<a href="/tags/{{ . | urlize | lower }}">{{ . }}</a>`

**Comment by ahonn** [comment]
Same bug! It looks as if no fixed?

I use `.Site.Taxonomies.tags` to get tags, but it return lower case tag name.
`<a href="tags/{{ . | urlize }}">{{ . }}</a>` -> tags/sometag，not  `tags/SomeTag`.

What should I do?

**Comment by rdwatters** [comment]
@ahonn Please ask support related questions on the Hugo forums: https://discuss.gohugo.io

**Comment by salim-b** [comment]
> I use `.Site.Taxonomies.tags` to get tags, but it return some lower case tag name.
> `<a href="tags/{{ . | urlize }}">{{ . }}</a>` -> tags/sometag，not `tags/SomeTag`.
> 
> What should I do?

I stumbled upon this issue while searching for a solution to the same problem. Meanwhile I found the answer, so for reference: Set [`preserveTaxonomyNames = true`](https://gohugo.io/content-management/taxonomies/#preserve-taxonomy-values) in your `config.toml`.
