### ISSUE TITLE
Create Pages from GraphQL queries

### ISSUE THREAD

**Issue by zoosky** [gohugoio/hugo#4910]
This would Hugo enable to adapt to an API based Headless CMS.

Context: 

"Pages from “other data sources”
Currently, in addition to Hugo’s list pages, every URL must be backed by a content file (Markdown, HTML etc.). This covers most use cases, but we need a flexible way to generate pages from other data sources. Think product catalogues and similar."

See http://gohugo.io/news/lets-celebrate-hugos-5th-birthday/

**Comment by lucperkins** [comment]
I'm not necessarily opposed to a feature like this, but to me it seems like it would be very difficult to manage the trade-off between power and simplicity. Allowing users to specify a GraphQL query via configuration might be simple enough, but then where do the fetched pages end up in the directory structure? How often does the fetching happen? How would authentication for GraphCMS/Contentful/whatever be handled?

Right now the "Hugo Way" is to make gathering inputs a process that happens outside of Hugo, with the exception of things like `readFile` and `readJSON`, both of which are much more specific and limited in scope than what you're calling for.

I'm not saying that a GraphQL implementation is impossible *per se*. I'm just skeptical that there's enough similarity across GraphQL content backends to make a feature like this generally useful.

**Comment by lucperkins** [comment]
In a different mood, what would be super cool would be some kind of API standard for GraphQL content gathering, a standard to which existing GraphQL content providers could be pressured to conform. This would provide a solid "contractual" basis for tools like Hugo, Gatsby, Jekyll, Middleman, and the like to provide their own GraphQL implementations. The standard could cover auth*, directory organization, file metadata, etc.

**Comment by zoosky** [comment]
Gatsby has Source Plugins https://www.gatsbyjs.org/docs/create-source-plugin/ that help integrate with a Headless CMS. See https://hackernoon.com/building-a-static-blog-using-gatsby-and-strapi-8b5acfc82ad8

**Comment by regisphilibert** [comment]
Hopefully this would fall under https://github.com/gohugoio/hugo/issues/5074

**Comment by bep** [comment]
Duplicates #5074 (kind of)
