### ISSUE TITLE
Add "extended" to "hugo version"

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4913]

**Comment by anthonyfok** [comment]
PR #4914 is my attempt at this task.  I originally decided to append `/SCSS` to the version, but changed it to `/extended` before submitting the PR  to match what you wrote in the issue title.  The result looks something like this:

```
Hugo Static Site Generator v0.43-DEV-3CEA2932/extended linux/amd64 BuildDate: 2018-07-08T02:42:31-0600
```
