### ISSUE TITLE
releaser: New goreleaser version/setup fails

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4918]
```bash
goreleaser: error: unexpected false, try --help
Error: goreleaser failed: exit status 1
exit status 255
Exited with code 1
```

Not in the mood to debug the above right now.

**Comment by caarlos0** [comment]
seems like an usage error, what flags are you using?

**Comment by bep** [comment]
```
--rm-dist --release-notes  releaseNotesFile --skip-publish=true
```

Looking at the above, I assume it is the last. But it did work, and ... I build those flags dynamically.

**Comment by caarlos0** [comment]
yeah, I was able to reproduce here:

```console
$ go run main.go --skip-publish=true
main: error: unexpected true, try --help
exit status 1
```

maybe something on alecthomas/kingpin :/ 

Will have a look later today.

**Comment by bep** [comment]
>Will have a look later today.

No rush, I can easily work around it.

**Comment by bep** [comment]
@caarlos0 but can I ask you a Goreleaser question:

```bash
go build -ldflags "-extldflags '-static"
```

I cannot get the above ldflags  (i.e. quotes) to work ...

**Comment by caarlos0** [comment]
I think there is a `'` missing?

I just tried here:

```yaml
ldflags: "-extldflags '-static'"
```

and it works...

**Comment by bep** [comment]
But this seems to work:

```bash
 ldflags: 
    - -s -w -X github.com/gohugoio/hugo/hugolib.BuildDate={{.Date}}
    - "-extldflags '-static'"
```

Helps to read the docs...

**Comment by caarlos0** [comment]
Nice :D
