### ISSUE TITLE
Getting MediaType's Suffix deprecated warning even after fixing all deprecations

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4927]
Hello,

I am getting the warning from https://github.com/gohugoio/hugo/pull/4925 even after doing the needed changes:

- https://github.com/kaushalmodi/hugo-atom-feed/commit/b9875371b3cc6d05136fc5e0f08a968f74d8714f
- https://github.com/kaushalmodi/hugo-jf2/commit/22051fed8e22d7dfbc50b52a1bde6fc44273a544
- https://gitlab.com/kaushalmodi/hugo-theme-refined/commit/c94dfc65dbabd7211524aab012281271d2d0fd93

But still I get:

> MediaType's Suffix in config.toml is deprecated and will be removed in a future release.

To recreate this warning do:

```
git clone --recurse-submodules https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io.git scripter.co
cd scripter.co
hugo
```

**Comment by kaushalmodi** [comment]
I also have a side question.. in the PR you mention:

> For one, it was only possible with one file extension per MIME type.
> Now you can specify multiple file suffixes using "suffixes"

So for a mediatype having multiple suffixes, which of those suffix is used for the file extension if that mediatype is used for a custom output format?

Let's say I have this hypothetically:

```
[mediaTypes."application/atom+xml"]
  suffixes = ["xml", "foo"]
[outputFormats.Atom]
  # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  mediaType = "application/atom+xml"
  baseName = "atom" 
  isPlainText = false
```

Earlier it was `suffix = "xml"`, so the generated custom output format file was the "baseName" + "." + "suffix" i.e. "atom.xml". How is the generated file name derived now?

**Comment by kaushalmodi** [comment]
Looks like `OldSuffix` is non-empty and so the warning would always be triggered? https://github.com/gohugoio/hugo/commit/b874a1ba7ab8394dc741c8c70303a30a35b63e43#r29662878

**Comment by bep** [comment]
> How is the generated file name derived now?

In that case we do lookup based on MIME type, so you would get the first.

**Comment by kaushalmodi** [comment]
I can understand associating multiple suffixes (file extensions) to a given mimetype. But what does that have to do with server?

**Comment by bep** [comment]
>But what does that have to do with server?

The server associates suffixes with MIME types. So if you have, say, multiple name standards for SVGs floating around, that can be handled ...
