### ISSUE TITLE
/static from theme(s) not picked up in multihost mode

### ISSUE THREAD

**Issue by lord-re** [gohugoio/hugo#4929]
After upgrading to Hugo 0.42 *Hugo stops including static files from themes/xxx/static/ if it's set up as multi-lingual.

There is an [active thread in the forum](https://discourse.gohugo.io/t/no-static-files-after-hugo-update-from-0-41-to-0-42-1/12481/18) where multiple users experience the same bug.

By downgrading to Hugo 0.41 it works again.

**Comment by bep** [comment]
What happens in Hugo 0.43?

**Comment by lord-re** [comment]
Like in 0.42, no static files from theme.

**Comment by BenBergman** [comment]
For me, the issue only occurs when I have a specific `baseURL` for each language.

**Comment by lord-re** [comment]
Yes, i tried commenting baseURL in each language and it works again.

**Comment by lord-re** [comment]
I confirm this workaround works here too.
