### ISSUE TITLE
SVG not loading/displaying after upgrading to V 0.43_1

### ISSUE THREAD

**Issue by rhewitt22** [gohugoio/hugo#4938]
I just linked up the latest version of hugo using homebrew on my mac.

```bash
$ brew update
$ brew unlink hugo
$ brew install hugo
```

When I fire up the dev server with the new version of hugo my SVG logo no longer loads.

![screen shot 2018-07-12 at 9 54 37 am](https://user-images.githubusercontent.com/3673374/42637712-e4298aac-85b9-11e8-958a-f5ab07e3ef34.jpg)

If I visit the URL of the SVG on the dev server it automatically downloads and appears uncorrupted:

http://localhost:3000/images/svg/logo.svg

I went back to version 0.42.2 and fired up the server without changing anything else -- the logo comes through as expected.

```
$ brew switch hugo 0.42.2
```

![screen shot 2018-07-12 at 9 52 05 am](https://user-images.githubusercontent.com/3673374/42637713-e439028e-85b9-11e8-8ef1-4753c50b2335.jpg)

Is there any more information I can provide that might help get to the bottom of this issue?

**Comment by bep** [comment]
See #4920
