### ISSUE TITLE
Unable to read frontmatter at filepos 1366: EOF

### ISSUE THREAD

**Issue by ygjose** [gohugoio/hugo#4949]
I use Hugo academic theme. Every time when I want to change **talk** under the content file, the deployment from Git to Netlify turn out to be failed. I don't know why?
```
Error: unable to read frontmatter at filepos 1366: EOF
```
or
```
Failed to render "theme/section/talk.html": runtime error: index out of range
```

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
