### ISSUE TITLE
Use local installation of Postcss-cli

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#4952]
To use the new postCSS resource feature in Hugo 0.43, you must have postcss-cli installed on your path. However, ideally, it should be enough to install it into `node_modules/.bin/`. That way your project can document all its requirements in a project specific `package.json` and not need a separate global install. It also eases dealing with multiple projects with different versions of postcss-cli in use.

**Comment by numbfall** [comment]
Local install of postcss-cli is still not working. I get the following error unless I install postcss-cli globally.

```
Building sites … ERROR 2018/08/05 17:46:48 error: failed to transform resource: POSTCSS: failed to transform "css/tachyons.css" (text/css): this feature is not available in your current Hugo version
```

I have postcss in my `node_modules/.bin/` and `node_modules/postcss-cli/bin/`

This is my html

```
{{ $style := resources.Get "css/tachyons.css" | resources.PostCSS }}
```

You need to reopen this issue.

**Comment by tech4him1** [comment]
@numbfall Please be sure you are using Hugo v0.45 or newer -- that was when the fix was added.

**Comment by TheBaronHimself** [comment]
I think it would be useful to have this functionality for themes, too. I.e. Hugo using postcss-cli and any plugins contained in `themes/sometheme/node_modules/.bin`. This way a theme's dependencies could be installed more easily. Or am I being silly?

**Comment by TheBaronHimself** [comment]
@onedrawingperday 

That makes lots of sense, actually. Thanks.

**Comment by inwardmovement** [comment]
Local `postcss-cli` seems to work [on Mac](https://discourse.gohugo.io/t/why-postcss-has-to-be-installed-globally/19680), it should work on Windows too. Can we reopen?
