### ISSUE TITLE
ByLinkTitle seemingly sorts by date if link title not explicitly set

### ISSUE THREAD

**Issue by zombiezen** [gohugoio/hugo#4953]
I have a bunch of content in my Hugo site that I'm sorting by link title in a list template (using `.Data.Pages.ByLinkTitle`).  However, `.ByLinkTitle` appears to not work as documented; it appears to be sorting by date order. `.ByTitle` works as expected.  All of the content being sorted does not have an explicit link title set, but they do all have titles set in the front matter. I'm able to reproduce this on Hugo 0.44.

The site source is [here](https://github.com/zombiezen/gg/tree/42822ca436c3f1bf994ffb77f616be099cbb405f/docs), you can reproduce by changing [this line of layouts/commands/list.html](https://github.com/zombiezen/gg/blob/42822ca436c3f1bf994ffb77f616be099cbb405f/docs/layouts/commands/list.html#L9) to use `.ByLinkTitle` and seeing the effects on `/cmd/`.  Let me know if you need a more minimal reproduction case.

Based on examining the Hugo source briefly, what I'm suspecting here is that `Page.linkTitle` is not being set correctly to the implicit default of title when considering for sort, but I couldn't confirm this with certainty.

**Comment by bep** [comment]
I just checked the code, and it sorts by `linkTitle` only -- which I think is wrong, but not in the way you describe.

I would expect it to sort by `LinktTitle` (the method), which has a fallback to `title` if no `linkTitle` etc. Now you will get odd results for the pages where no value is set for that field in front matter. We should probably also do the same the other way around for ByTitle.

**Comment by zombiezen** [comment]
I don't believe this bug has been fixed.
