### ISSUE TITLE
Add optional language as argument to rel/relref

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4956]
With support for multiple content dirs, it's not possible to do cross-site linking from content files with ref/relref shortcodes. It was never that clever, either. We will improve this further in #4574, but as part of the big `GetPage` overhaul, we should add language code as an optional last argument,  you could do:

```
{{< ref "document.md" "jp" >}}
```

With the above, you will also get the benefit of all the aliases we index a page with. This will work, for one:

```
{{< ref "document" "jp" >}}
```

/cc @kaushalmodi @RickCogley

**Comment by kaushalmodi** [comment]
For clarity, I would suggest a syntax like `{{< ref "document" lang="jp" >}}`

**Comment by bep** [comment]
That syntax is not supported ... But I just noted that we use outputFormat (not documented) as the second argument ... So we need something clever.

**Comment by bep** [comment]
OK, I think we are saved by my sloppiness in docs updates. 

Since shortcodes cannot mix positional and named arguments, I suggest that:

```
{{< ref "document" >}}.
```

Is without options


```
{{< ref src="document" lang="jp" outputFormat="rss" >}}.
```

Is `src` bad?

We have the same variant in a template func, which would have to use a `dict` for the same.

**Comment by bep** [comment]
I think possibly this is better:

```bash
{{< ref ref="document" lang="jp" outputFormat="rss" >}}.
```

@kaushalmodi @regisphilibert ?

**Comment by kaushalmodi** [comment]
> {{< ref ref=

Nooo.. too much "ref" 

Would `path` make sense? because that value can be `foo/document`, or `foo/document.md`.

**Comment by bep** [comment]
>Would path make sense?

Yes.
