### ISSUE TITLE
Hugo extended doesn't run on alpine

### ISSUE THREAD

**Issue by dettmering** [gohugoio/hugo#4961]
I’m using Docker for building Hugo sites with GitLab CI. The Dockerfile can be found here: https://github.com/dettmering/hugo-build/blob/master/Dockerfile and the Docker image here: https://hub.docker.com/r/dettmering/hugo-build/

This worked perfectly until I decided to give the new extended version 0.44 a try. The only thing I changed was the name of the tarball so the _extended_0.44 tarball is downloaded.

Now, when I run the Docker container, I get `/bin/sh: hugo: not found`, even though the hugo binary is in the correct folder.

A hint comes from `file hugo`: `hugo: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=7621f50844b0494c9fa7846a9e1366892aacf6c8, stripped`

Apparently, Alpine can't run those dynamically linked executables. Can we get the hugo extended version to run on Alpine?

**Comment by bep** [comment]
If Alpine cannot run dynamically linked executables, then the answer is currently no -- but I would be surprised if that was true. I'm pretty sure I tested it, but you need glibc. Take further question on the forum.

**Comment by dettmering** [comment]
Thanks, please find my solution here: https://discourse.gohugo.io/t/bin-sh-hugo-not-found-in-docker-container/12983/6?u=till
