### ISSUE TITLE
SASS/SCSS source maps fails on Windows

### ISSUE THREAD

**Issue by Jos512** [gohugoio/hugo#4968]
Originally reported here: 
- [How to use source maps with Hugo 0.43?](https://discourse.gohugo.io/t/how-to-use-source-maps-with-hugo-0-43/12826/3)

Test reproduction Hugo project here: 

- [Hugo source maps error repository](https://github.com/Jos512/hugo-source-maps-error)

-----

## Setup

~~~
hugo env
Hugo Static Site Generator v0.44/extended windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.10.3"
~~~

## The problem

- Source maps do not work. Firefox and Chrome developer tools only show the rendered `.css` file, not which `.scss` actually hold the files.

### Error messages
In Firefox, in the Console tab of the Developer tools, the following appears:

~~~
Source map error: SyntaxError: JSON.parse: bad escaped character at line 6 column 16 of the JSON data
Resource URL: http://localhost:1313/assets/css/style.css
Source Map URL: style.css.map[Learn More] 
~~~

*Note:* To see the error message you'll first need to inspect an element.

In Chrome, in the Console tab of the Developer tools, the following shows:

~~~
DevTools failed to parse SourceMap: http://localhost:1313/assets/css/style.css.map
~~~

## Problem in the source map
The generated source map looks like:

~~~
{
	"version": 3,
	"file": "style.css",
	"sourceRoot": "C:/Temp/hugo-source-maps",
	"sources": [
		"themes\test\assets\assets\css\style.scss",
		"themes/test/assets/scss/_content.scss",
		"themes/test/assets/scss/_footer.scss",
		"themes/test/assets/scss/_header.scss"
	],
	"sourcesContent": [
		"\r\n@import \"themes/test/assets/scss/_content.scss\";\r\n@import \"themes/test/assets/scss/_footer.scss\";\r\n@import \"themes/test/assets/scss/_header.scss\";",
		"main, p {\r\n    font-size: 15px;\r\n}\r\n",
		"footer {\r\n    font-size: 20px;\r\n}",
		"h1 {\r\n    font-family: Cambria, Cochin, Georgia, Times, Times New Roman, serif;\r\n    color: orange;\r\n}\r\nheader {\r\n    font-size: 20px;\r\n}"
	],
	"names": [],
	"mappings": "ACAA,AAAA,IAAI,EAAE,CAAC,CAAC;EACJ,SAAS,EAAE,IAAI,GAClB;;ACFD,AAAA,MAAM,CAAC;EACH,SAAS,EAAE,IAAI,GAClB;;ACFD,AAAA,EAAE,CAAC;EACC,WAAW,EAAE,uDAAuD;EACpE,KAAK,EAAE,MAAM,GAChB;;AACD,AAAA,MAAM,CAAC;EACH,SAAS,EAAE,IAAI,GAClB"
}
~~~

The line number that Firefox complains about is:

~~~
"themes\test\assets\assets\css\style.scss",
~~~

The problem seems to be that the `\` should be `/`, since the other paths in the source map use this format:

~~~
"themes/test/assets/scss/_content.scss",
"themes/test/assets/scss/_footer.scss",
"themes/test/assets/scss/_header.scss"
~~~

**Comment by tech4him1** [comment]
I'm seeing the same problem on Windows. `\` is actually a JSON escape character, so it isn't valid to be used there. I'm assuming this is a problem upstream in LibSASS, but I'll have to check to be sure.

**Comment by bep** [comment]
I suspect it's an issue with the paths Hugo sends LibSASS. We send windows paths on Windows, so "\\" is the separator.

**Comment by machee** [comment]
https://github.com/gohugoio/hugo/blob/d6fde8fa131f3852fa98a8ec5c360e736486cf54/resource/tocss/scss/tocss.go#L83-L90

I think on Windows `sourcePath` ends up with `\`s from `WorkingDir` and `FilePathSeparator`.  Then that gets inserted into the JSON without being escaped.  Probably could just escape it, but may work better to just replace `\` with `/` in that string?

**Comment by bep** [comment]
@machee I suspect the way to go is to use Unix-style slashes on all paths sent to LibSass, but someone has to test it ... I have a Windows VM floating around somewhere... It sounds a little bit counter-intuitive, and is sounds like a LibSASS bug, because we send in absolute file paths here, so it is `c:\ \myproject\\scss` etc.

**Comment by machee** [comment]
Seems like the bug comes _after_ LibSass has run, when replacing "stdin" in the `SourceMapContent`.  At least with the current example LibSass is not returning invalid JSON and does not generate paths with `\` even on Windows.  It's the `Replace` on line 90 that is making the JSON invalid by inserting unescaped `\`.

I may try a Windows build tomorrow but seems like 0236f74f2fd8e65c63ce0cfd383e8acc5819e752 would fix it.
