### ISSUE TITLE
Deprecate absolute lookups for relative ref/relref

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4973]
Ref. the ongoing debate. @vassudanagunta 

For:

```
relref "sect5/page3.md"
```
We will now look first relative to the page it lives in, but will fall back to "/sect5/page3.md", which is commonly used. We cannot just change that overnight. People will scream. 

But we can do it in smaller steps. 

So, I suggest we check for the pattern above and "asks the user politely" to correct it to `relref "/sect5/page3.md"`

**Comment by vassudanagunta** [comment]
Makes sense!
