### ISSUE TITLE
emoji is rendered in code blocks

### ISSUE THREAD

**Issue by splashx** [gohugoio/hugo#4978]
I have `enableEmoji: True` and the following content in a page:

~~~
```
    :az:ab:cd:
```
~~~

It should be rendered as:

![screen shot 2018-07-20 at 14 37 56](https://user-images.githubusercontent.com/1154133/43002847-8a62cfc0-8c2a-11e8-895d-6de0ec362ddd.png)

But instead I get an emoji :ab: instead of `:ab:` - picture:

![screen shot 2018-07-20 at 14 36 52](https://user-images.githubusercontent.com/1154133/43002798-62615136-8c2a-11e8-93e4-32dd12645aac.png)

```
$ hugo version
Hugo Static Site Generator v0.44/extended darwin/amd64 BuildDate: unknown
```

theme: vjeantet/hugo-theme-docdock [latest]

**Comment by kaushalmodi** [comment]
I confirm the bug. Though, it's a Blackfriday bug and an issue should be opened in Blackfriday's repo instead.

**Comment by bep** [comment]
I assume this is with enableemoji enabled, in which this is as designed. You can solve this by turning that off.

**Comment by kaushalmodi** [comment]
> I assume this is with enableemoji enabled, in which this is as designed. 

It's a bug.. why should Blackfriday render emoji's in code blocks?

**Comment by bep** [comment]
> Blackfriday render emojis in code blocks?

Blackfriday doesn't render any emojis.  Emoji is a Unicode character -- if you insert it into a document, the **browser renders it**.

**Comment by kaushalmodi** [comment]
> Blackfriday doesn't render any emojis. Emoji is a Unicode character -- if you insert it into a document, the browser renders it.

Seems like we are talking of different things.

See below:

![image](https://user-images.githubusercontent.com/3578197/43011957-01069872-8c13-11e8-84fc-3470ce75dd82.png)

```
<pre><code>:az🆎cd:
</code></pre>
```

Blackfriday replaced the `:ab:` with that AB emoji i.e. hard-coded it. The browser simply shows that emoji in the default font.

Blackfriday should have left that `:ab:` in the `<pre>`/`<code>` tags as-is.

**Comment by bep** [comment]
I will repeat it one last time: This isn't a Blackfriday issue.

**Comment by kaushalmodi** [comment]
So then, who is replacing the 4-char string `":ab:"` with the Unicode char 🆎 (0x1F18E) in the HTML?

**Comment by splashx** [comment]
> So Hugo has no context of where (in code block? in text?) those emoji strings appear.. and it does a blanket search/replace, right?

If that’s true then any attemp to use unformatted text in the page is doomed. Clearly not the way most apps behave. 

GitHub for example won’t replace it:

~~~
:laughing:
~~~

Which should not be rendered as: 😆

**Comment by tschinz** [comment]
reopen, still the case. Hugo should not replace emoji in code blocks. Should work as in github
`
:smile: 
`
:smile:

**Comment by anup92k** [comment]
Same problem here, still on Hugo v0.67.1 (extended)...
![image](https://user-images.githubusercontent.com/51033013/76806180-05278500-67e1-11ea-9b51-efd6c5fa1a7f.png)

**Comment by dillonzq** [comment]
> Same problem here, still on Hugo v0.67.1 (extended)...
> ![image](https://user-images.githubusercontent.com/51033013/76806180-05278500-67e1-11ea-9b51-efd6c5fa1a7f.png)

@anup92k LoveIt theme uses a special syntax to escape what you want to display.
[https://hugoloveit.com/theme-documentation-content/#escape-character](https://hugoloveit.com/theme-documentation-content/#escape-character)

**Comment by anup92k** [comment]
Thanks ! I didn't understand this part last time.

**Comment by angristan** [comment]
👋 Bumping this issue. I don't think it should be closed?
