### ISSUE TITLE
Allow global ignore of some resource trans. methods per environment.

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#4981]
It is good practice to test `.IsServer` before applying `resource.Minify` and `resources.Fingerprint` to a resource.

Systematically calling a condition for each resource processed may become very tedious when you start using Hugo Pipes's asset transform (ex image process) in a lot of different location in your templates or when most of your templates are inherited from a theme.

I'm proposing (more like enquiring for feasibility) an alternative: To add a new config setting allowing the ignoring of certain asset transformation methods. This way we can safely `.Fingerprint` and/or `.Whatever` our assets without having to test the environement.

```
# config.yaml
ignoreAssetTransform:
  - fingerprint
  - minify
```
```
# config.prod.yaml
ignoreAssetTransform: false
```

**Comment by bep** [comment]
Hmm... I guess we at some point will add some "site config globals" for the different transformations (SCSS etc.), but t.this was not what I had in mind. What I really like with all of this is the what you see is what you get. Without having to hunt down some nested config in some XML files to debug why fingerprinting suddenly stopped working.

**Comment by regisphilibert** [comment]
> Without having to hunt down some nested config in some XML files to debug why fingerprinting suddenly stopped working.

What XML file? I'm talking about a project only configuration parameter (you make a point, themes should not be able to set it).

Let me push my point a bit here.

Currently an `{{ if .IsServer / else }}` statement is needed for every "permalinked" resource. Meaning:

1. As a theme user you cannot force fingerprinting on hugo-sever for temporary testing.
2. As a theme user you cannot rule out fingerprinting on a dedicated non-hugo-server environment, say `staging`.
3. As a project/theme coder, you cannot do 2. without updating your `if` with an environment variable or config parameter unique to your setup.
3. But most importantly Hugo Pipes loses all the one liner jazz it first inspired :)

Lastly, I would add that this fingerprinting on/off switch per environment is common practice among Gulp|Grunt|Webpack users and would be a welcome addition to their Hugo built-in counterpart: Hugo Pipes.

**Comment by bep** [comment]
>What XML file? I

I was talking about the "Gulp XML files", not Hugo.

You can use some other flag than IsServer which would solve most of your concerns. What you want is doable, of course, but I'm not totally convinced. This will look prettier once Go 1.11 is out and we can re-assign variables, and the "one-liner" is only beautiful if I can look at it and tell exactly what it does.

**Comment by bep** [comment]
... but this isn't set in stone, but I feel that this need to linger a little...

**Comment by regisphilibert** [comment]
I build this kind of partials which systematically needs `.Site` in its context...
```
<img src="{{ partial "asset" (dict "site" .Site "asset" "images/logo.svg") }}">
```

```
{{- $site := .site -}}
{{- with resources.Get .asset -}}
	{{- if $site.IsServer -}}
		{{- .Permalink -}}
	{{- else }}
		{{- (. | fingerprint).Permalink -}}
	{{- end -}}
{{- end -}}
```

And start daydreaming about this issue :)
