### ISSUE TITLE
Create and maintain an example starter theme

### ISSUE THREAD

**Issue by polybuildr** [gohugoio/hugo#4983]
**(Feature request)** Would it be possible for the Hugo developers to create and maintain an example starter theme - a "skeleton" theme with no styling or HTML, just a starting point for new themes - file/directory structure (which `hugo new theme` does provide most of...) and basic partials and includes/shortcodes?

I've looked at https://themes.gohugo.io but I'm not sure if any of them can be considered "canonical" and updated to always match Hugo's new releases. I assume it would be too much extra work to maintain a "real" theme with styling and everything, but how about a blank theme that people can take and add HTML structure and styling to themselves?

Sorry if such a canonical theme already exists and I'm not aware of it!

**Comment by polybuildr** [comment]
Friendly ping! :)

**Comment by jhabdas** [comment]
Themes may be themes or they may be theme components. They could be used to build websites or simply to generate web feeds, resize images or simply produce a robots.txt file. Placing any opinion on the theme generator may seem useful but it could limit creativity in the design process. As for defining `main`, last time I checked it's not required. Is that no longer true?

**Comment by jhabdas** [comment]
Themes may be themes or they may be theme components. They could be used to build websites, generate web feeds, resize images or simply produce a robots.txt file. Placing any opinion on the theme generator may seem useful but it could limit creativity in the design process. As for defining `main`, last time I checked it's not required. Is that no longer true?

**Comment by jhabdas** [comment]
I'm not here to argue opinion, just offer it. But I will point out there is one example starter theme which is used as the baseline for all themes in the theme site: https://github.com/gohugoio/hugoBasicExample

If you're looking for a skeleton from which to start that would probably be the best place to start given it's the canonical example used when any individual theme, appearing broken or not, uses when no `exampleSite` is provided.

**Comment by polybuildr** [comment]
> one example starter theme which is used as the baseline for all themes in the theme site: https://github.com/gohugoio/hugoBasicExample

I did not know this existed, thanks for pointing to it! I took a look at it and I can't seem to find any layouts in there, am I missing something? It seems to only suggest that it's the site used to demo different themes but not a theme itself.

**Comment by jhabdas** [comment]
Ack, my bad. You're not missing anything. That's not actually a theme itself but the baseline tester for theme submission. It doesn't handle theme components currently. Thinking about the common case for creating a theme I'll admit could use some work. But if anything were added at this point it'd likely require the `new theme` sub subcommand to take a flag so it knew how to create theme components in addition to themes.

Thinking about `archetypes` I wonder if there'd be a way to define a scaffolding using those. Perhaps something like this: https://github.com/gohugoio/hugo/issues/4535

**Comment by polybuildr** [comment]
Also, a couple of weeks back I actually found an existing Hugo issue for something very similar... tried to look for it right now but could not find it. :/

Found #4839, which seems related, but not the original one.

**Comment by jhabdas** [comment]
Could it have been this one? https://github.com/gohugoio/hugo/issues/4869

**Comment by polybuildr** [comment]
That's not the one I remember. I'll try looking for it again later if I can find some time!

**Comment by jhabdas** [comment]
this just came up in the forums in case anyone wants to lobby for this feature now might be a good time to strike while the iron is hot: https://discourse.gohugo.io/t/having-issues-cant-even-get-started-with-hugo/13681

**Comment by Ziflin** [comment]
@jhabdas Thanks for the heads up. I just replied as I ran into nearly every issue that they had as well. I think just some doc updates and having the _main_ section included so you can actually *see* something initially would be great.

**Comment by polybuildr** [comment]
Sorry, I dropped the ball on keeping this issue active!

I still believe this to be relevant, unless something's changed in Hugo that I haven't been paying attention to. However, I understand that the Hugo team's resources are limited and if there is a reason this request can't be looked into (too many other requests, too hard to fix, or something of the sort) then I can understand that. :)
