### ISSUE TITLE
Hugo extended binaries are dynamically linked

### ISSUE THREAD

**Issue by tesujimath** [gohugoio/hugo#4985]
It's obviously a huge win to have statically linked binaries, since they are maximally portable.

The new extended binaries with integrated SASS support are being built as dynamically linked executables.  These don't work in my minimal container, since I don't have the required dynamic libraries.  

Was this by design, or is it something you can easily fix?

(The integrated SASS support is great BTW.)

**Comment by bep** [comment]
>Was this by design, or is it something you can easily fix?

Yes.

**Comment by tesujimath** [comment]
Yes by design, or yes you can fix it?

**Comment by bep** [comment]
Yes, by design. Distribute glibc++ with every binary is a bad idea, security being the argument that trumps everything. I don't believe in the "maximally portable" argument -- it is convenient for the end user, as he/she does not have to do anything.

**Comment by tesujimath** [comment]
Ok, thanks for the clarification, I'll add those dynamic libraries to my container.
