### ISSUE TITLE
Hugo 0.45 Panic with .Get.Page

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#4989]
`{{ $sections := (.Site.GetPage "section" .Section).Sections.ByWeight }}` in Hugo 0.45 throws a panic.

Related Discourse thread: https://discourse.gohugo.io/t/panic-error-with-getpage-in-hugo-0-45/

Console log
```
Building sites … ERROR 2018/07/23 14:20:48 Failed to render "_default/list.html": runtime error: invalid memory address or nil pointer dereference
ERROR 2018/07/23 14:20:48 Stack Trace:
goroutine 153 [running]:
github.com/gohugoio/hugo/hugolib.stackTrace(0x4b0, 0xef9837, 0x17)
	/home/alex/work/src/github.com/gohugoio/hugo/hugolib/page.go:280 +0x76
github.com/gohugoio/hugo/hugolib.(*Site).renderForLayouts.func1(0xc420b1f8a0, 0xc42046a300)
	/home/alex/work/src/github.com/gohugoio/hugo/hugolib/site.go:1742 +0x135
panic(0xdc2b00, 0x1591eb0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
text/template.errRecover(0xc420b1f790)
	/usr/local/go/src/text/template/exec.go:137 +0x1d4
panic(0xdc2b00, 0x1591eb0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/gohugoio/hugo/hugolib.(*Page).Sections(0x0, 0x0, 0x0, 0x0)
	/home/alex/work/src/github.com/gohugoio/hugo/hugolib/site_sections.go:139 +0x5
reflect.Value.call(0xea6320, 0xc420f8f220, 0x11693, 0xeabf9a, 0x4, 0x15d3cf0, 0x0, 0x0, 0xea0b40, 0x1, ...)
	/usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xea6320, 0xc420f8f220, 0x11693, 0x15d3cf0, 0x0, 0x0, 0xc420fdaa60, 0x13, 0x45)
	/usr/local/go/src/reflect/value.go:308 +0xa4
text/template.(*state).evalCall(0xc420b1f710, 0xea8760, 0xc420716c80, 0x16, 0xea6320, 0xc420f8f220, 0x11693, 0x10883c0, 0xc4206daa00, 0xc42088ec27, ...)
	/usr/local/go/src/text/temp
Total in 5143 ms
Error: Error building site: logged 2 error(s)

```

**Comment by bep** [comment]
@onedrawingperday I can look at this some more, but then I kind of need to know more about your site.

**Comment by onedrawingperday** [comment]
@bep I have posted a [comment](https://github.com/gohugoio/hugo/pull/4991#issuecomment-407362219) in the commit. I had an unrelated issue.

Your commit fixed this issue. I'm closing it.

**Comment by kaushalmodi** [comment]
@bep This workaround looks quite specific to the "section" case. Should a warning be also printed alongside if you plan to deprecate this style some time in the future?

**Comment by bep** [comment]
>Should a warning be also printed alongside if you plan to deprecate this style some time in the future?

I don't print a warning until I deprecate it.

**Comment by kaushalmodi** [comment]
> I don't print a warning until I deprecate it.

OK. I should have phrased it the other way :) I would have thought 2-arg GetPage syntax would be deprecated. That code looks weird as it has special handling of 2-arg GetPage calls only when the kind is "section", and the kind would be completely ignored for all other kinds.. So the implementation is inconsistent.

It would be good to either support all kinds, or deprecate the kind argument altogether.

**Comment by bep** [comment]
OK. I should have phrased it some other way: I have done way too much work on this, so any more non-critical work in this area will have to wait.
