### ISSUE TITLE
Generate integrity hashes

### ISSUE THREAD

**Issue by jhabdas** [gohugoio/hugo#4990]
I'd like to be able to generate the value of an [`integrity` attribute](https://w3c.github.io/webappsec-subresource-integrity/#the-integrity-attribute) in my hugo template given a hashing function, e.g.

```
<script async scr={{ "js/script.js" | relURL }} integrity={{ sha384 (string.ToBinary (readFile "/static/js/script.js") | base64Encode }}>
```

There are some [`openssl` bindings for Go](https://github.com/spacemonkeygo/openssl#openssl-bindings-for-go) though I'm not sure they'd be required if a binary representation of the read file contents can be generated during the build as shown above with the fictitious `string.ToBinary` function. Having the capability to generate `integrity` attributes would help themes developers provide additional security for their users and eliminate this job:

https://github.com/gcushen/hugo-academic/blob/master/data/sri.toml#L16-L18

**Comment by bep** [comment]
See https://gohugo.io/hugo-pipes/fingerprint/

**Comment by jhabdas** [comment]
Sorry I missed that. Thanks you. 🙏

**Comment by jhabdas** [comment]
Thanks, somehow I missed that while looking over the docs. My understanding is browsers will reject `md5` as insecure. Might want to point that out in the docs.

According to spec multiple hashing functions can be generated for a given resource and conforming user agents should provide `sha256`, `sha384` and `sha512`. If multiple are present the strongest will be selected. Given there are two of the three supported by the `fingerprint` function at current my needs are satisfied, and in a much more elegant way. Thanks again.
