### ISSUE TITLE
Javascript lexer adds a line

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4993]
Not sure if the problem is in Hugo or Chrome, but the following will end up being a two line code snippet:

```javascript
var foo = "bar";
```

@kaushalmodi you have any experience with this?

**Comment by bep** [comment]
It seems to be a problem with the Javascript lexer. Change it to Go and it behaves OK.

**Comment by kaushalmodi** [comment]
> It seems to be a problem with the Javascript lexer. Change it to Go and it behaves OK.

Yes, I was going to ask what language that was. I have not seen issue; just tested with emacs-lisp and works OK.
