### ISSUE TITLE
Two remarks about Hugo

### ISSUE THREAD

**Issue by rordi** [gohugoio/hugo#4996]
This is not an issue, but a general remark. I really love Hugo, but I really hate two things about it.  

**1) rendered vs. static and config options**

Anything in `layouts` or `templates` should be rendered without need for additional configuration. Anything that should not be rendered by Hugo should be placed into the `static` folder anyway. As `layouts` / `templates` and `static` are merged by Hugo to the `public` / `dist` folder anyway.

Why does a `robots.txt` in `layouts` require an extra config option `enableRobotsTXT = "true"` config option? If it is in the `layouts` folder, it should simply be rendered without the need for a config option. Why rendering a `list.json` file in `layouts` requires yet another config option under `[outputs]` with a config parameter called `section`? And why is a (robots).txt file treated differently config-wise than a `list.json`? These are things that make Hugo unintuitive.

**2) partials and shortcodes**

There are things, such as a contact address, a Google Maps embed or a social media embed that may be repeated several times in a typical website. Sometimes, I may included them from `content`, sometimes from `layouts`. Currently I have to define such embeds twice: once as a partial and once as a shortcode. It should be at least possible to call a partial from a shortcode, so that, at least, I do not need to duplicate my code.
 
 
Hugo is really great, and there's not even a version 1 out. So I hope these things could be considered for a future release of Hugo, as it will make Hugo more intuitive to use, and friendlier to those starting with Hugo.

**Comment by bep** [comment]
> It should be at least possible to call a partial from a shortcode

It is. 

But I think https://discourse.gohugo.io/ is a better forum for this. As to your first question, you have to remember that Hugo is 5 years ... and old configs such as enableRobotsTXT = "true" isn't changed/removed in a day. I have silently rewritten Hugo a couple of time, but even smaller changes are real work considering the many users out there.
