### ISSUE TITLE
Resource transformation URLs vs. canonifyURLs

### ISSUE THREAD

**Issue by rhewitt22** [gohugoio/hugo#4998]
[Originally posted on Discourse; another user suggested this might be a bug](https://discourse.gohugo.io/t/understanding-targetpath-with-scss-and-hugo-pipes/13176).

I have `canonifyurls: true` in my site config, but it doesn’t seem to be affecting the output of `{{ $style.Permalink }}`; not sure if that's pertinent.

## My CSS partial

```
{{ $options := (dict "targetPath" "/css/main.css" "outputStyle" "compressed" "enableSourceMap" true) }}
{{ $style := resources.Get "sass/styles.scss" | toCSS $options | postCSS | minify | fingerprint }}
<link rel="stylesheet" href="{{ $style.Permalink }}">
```

## Environments

My two environments have different BaseURLs:

* Production: https://www.fws.gov/southeast/
* Staging: https://intranet.fws.gov/region4/demo/

## Output

The link to the generated CSS is broken in both environments; they're missing a subdirectory.

`<link rel="stylesheet" href="https://intranet.fws.gov/region4/css/main.min.80b1bb2f29d8811c1f83e5164d0bd2314717d173a14186aa208c5abe546461ca.css">`

`<link rel="stylesheet" href="https://www.fws.gov/css/main.min.80b1bb2f29d8811c1f83e5164d0bd2314717d173a14186aa208c5abe546461ca.css">`

**Am I doing something wrong with my targetPath? I tried dropping the leading / without any luck.**

**Comment by bep** [comment]
>I have canonifyurls: true in my site config, but it doesn’t seem to be affecting the output of {{ $style.Permalink }}; not sure if that's pertinent.

They're not connected, but what happens if you turn canonifyurls off?

This pipe thing with subfolders in BaseURL certainly works, most of my test sites have that setup.

**Comment by rhewitt22** [comment]
Removing `canonifyurls` seems to have done the trick, actually.

ouput:

`<link rel="stylesheet" href="https://www.fws.gov/southeast/css/main.min.80b1bb2f29d8811c1f83e5164d0bd2314717d173a14186aa208c5abe546461ca.css">`

This is my current work-around

```
{{ $baseurl := printf "%s" .Site.BaseURL}}
{{ if in $baseurl "fws.gov/southeast" }}
  {{ $.Scratch.Set "path" "/southeast/css/main.css" }}
{{ else }}
  {{ $.Scratch.Set "path" "/region4/demo/css/main.css" }}
{{ end }}
{{ $options := (dict "targetPath" ($.Scratch.Get "path") "outputStyle" "compressed" "enableSourceMap" true) }}
{{ $style := resources.Get "sass/styles.scss" | toCSS $options | postCSS | minify | fingerprint }}
<link rel="stylesheet" href="{{ $style.Permalink }}">
```

**Comment by bep** [comment]
I have another issue talking about removing canonifyurls -- but I suspect I cannot do that until I get some kind of "URL rewriter" support in MD. But that setting must be the most expensive flag in the history of computing.

**Comment by shaform** [comment]
[hugoThemes](https://github.com/gohugoio/hugoThemes) is also using `canonifyURLs = true` currently, so the same bug occurs for themes on `https://themes.gohugo.io/`.

**Comment by it-gro** [comment]
@onedrawingperday The buildThemeSite.sh calls _script/generateThemeSite.sh which sets  HUGO_CANONIFYURLS=true.  absURL does not fix this resource permalink issue....

**Comment by shaform** [comment]
It appears that this might be a duplicate of #5226. Suppose #5226 is fixed, then this issue might be closed as well.
