### ISSUE TITLE
can't use short code inside short code in case of syntax highlighting 

### ISSUE THREAD

**Issue by polodev** [gohugoio/hugo#4999]
# highlighting in hugo  
~~~
{{< highlight go-html-template >}}
  {{< highlight html >}}
  {{</ highlight >}}
{{</ highlight >}}
~~~

here I want to show go hugo highlight shortcode in my website but showing unexpected outcome. Another thing is php is not supporting by pygments. I have to write `<?php` before every php code highlighting . I mean its only support `phtml`. 
Thanks

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
