### ISSUE TITLE
PostCSS 6 is broken, use PostCSS 5

### ISSUE THREAD

**Issue by budparr** [gohugoio/hugo#5001]
In 0.44 you can specify an alternative config file name:

```
"config" "./postcss.config.ALTERNATE.js"
```

In 0.45, the above setting throws the following [PostCSS error](https://github.com/postcss/postcss/blob/287567218758cbb08bb508889920ac199008c2ab/lib/processor.es6#L97), indicating there is no config file:

> You did not set any plugins, parser, or stringifier. Right now PostCSS do nothing. Pick plugins for your case on https://www.postcss.parts/ and usemthem in postcss.config.js.

I've put a test case here: https://github.com/budparr/hugo-issue-5001

note that if you merely specify the wrong path, you get the [config not found](https://github.com/gohugoio/hugo/blob/master/resource/postcss/postcss.go#L137) error from Hugo, not the PostCSS error.

**Comment by bep** [comment]
We certainly have a potential for improvement in the test department here ...

Relevant changes in Hugo 0.45 for anyone wanting to debug this:

* We use local postcss if installed
* We read configfile from project or theme

**Comment by budparr** [comment]
I did that and all sorts of other iterations. Thanks

**Comment by budparr** [comment]
I'll close this as it's explained in https://github.com/postcss/postcss-cli/issues/233
