### ISSUE TITLE
Add an option to have the full contents of posts in the RSS feed

### ISSUE THREAD

**Issue by bigblind** [gohugoio/hugo#5002]
I'd like to use m site's feed to syndicate the content to other places, so it needs to contain the full post contents. I know I can adapt the built-in template, but maybe this can be supported with a config option?

I'd be willing to implement this feature as my first contribution.

This makes thue feed rather large, so RSS pagination is also something that might be worth looking into.

**Comment by tobinjt** [comment]
Possible dupe of #4071 ?
+1 on implementing this, thanks!

**Comment by bigblind** [comment]
Yep, looks like it's a dupe.
