### ISSUE TITLE
Hugo gist shortcode broken and not adding raw

### ISSUE THREAD

**Issue by jhburns** [gohugoio/hugo#5003]
The embedded gist markdown seems to be broken currently and does not properly embed into the webpage. Instead, the gist is embedded into a frame that just shows the code of the gist. This is pretty clear in the hugo docs section about gist, [Here](https://gohugo.io/content-management/shortcodes/#example-gist-display). I believe this is happening due to something on GitHub's side not hugo's, but hugo can fix it by getting the raw data instead.

I have also reproduced it locally with version 0.40.1 of hugo.

**Comment by kaushalmodi** [comment]
Not sure what you mean here. I see:

![image](https://user-images.githubusercontent.com/3578197/43298679-ff78ff6a-9124-11e8-9cb0-c480c9343ddb.png)

What did you expect the `gist` shortcode to show?

Also, it's better to start up the discussion in the Hugo Discourse thread first to clarify the problem statement and remove any confusion.

**Comment by rdwatters** [comment]
Perhaps the `highlight` shortcod? Which I’m showing is definitely rendering the HTML angle brackets incorrectly....

**Comment by kaushalmodi** [comment]
> Which I’m showing is definitely rendering the HTML angle brackets incorrectly....

I'm not following that either.. screenshot and link?

**Comment by onedrawingperday** [comment]
> Instead, the gist is embedded into a frame that just shows the code of the gist.

This is how the internal Gist shortcode was meant to work. Also the raw data link always opened in a new tab directly on GitHub. Hugo never fetched the raw data.

For further help please use https://discourse.gohugo.io/

Thanks!
