### ISSUE TITLE
multilanguage mode sitemap.xml overwrite?

### ISSUE THREAD

**Issue by martinrode** [gohugoio/hugo#5004]
I did not find a way to overwrite the sitemap template used to generate the top level sitemap.xml in multilanguage mode. Sitemap inside each language works fine and uses my layout/sitemap.xml. Is there a way to overwrite the builtin for the top level sitemap as well?

**Comment by bep** [comment]
I just addes some lines to the docs about it:

https://gohugo.io/templates/sitemap-template/#sitemap-templates

**Comment by martinrode** [comment]
Thanks Bjørn, I ll check it out.
