### ISSUE TITLE
custom code css class appears a redundant dot

### ISSUE THREAD

**Issue by heavenzone** [gohugoio/hugo#5005]
I use r package blogdown. 
I found that the custom code css class appears a redundant dot using hugo 0.45.
I downloaded the hugo 0.37.1 and tested it again, this issue disappeared.

I have some code in my .md file:

    ```{.output}
    import os
    ```

## the html source code when using hugo 0.45

```
<pre><code class="language-.output hljs">import os
</code></pre>
```

there is an unexpected dot(.) there.

## the html source code when using hugo 0.37.1

```
<pre><code class="language-output">import os
</code></pre>
```

**Comment by bep** [comment]
>I use r package blogdown.

What exactly do you mean by that?

**Comment by rdwatters** [comment]
> What exactly do you mean by that?

I think this, maybe? https://github.com/rstudio/blogdown

**Comment by heavenzone** [comment]
I am sorry for my poor English to make myself clear.

Blogdown uses hugo to build site.

Forget the Blogdown. I tested again with pure hugo enviroment between version 0.45 and 0.37.1.

I just want the code block has a custom css class name.

My md file under content folder is:

    ---
    title: test hugo
    date: '2018-01-14'
    slug: test hugo
    ---

    ### test1

    ```{.custumCss}
    import sys
    print(sys.version)
    ```

    ### test2

    ```python
    import sys
    print(sys.version)
    ```

and my template file `single.html` is:

    <html lang="en">
    <head></head>
    <body>
      <div>
      <h1>{{ .Title }}</h1>
      <h2>{{ .Description }}</h2>
      </div>
      <div>{{ .Content }}</div>
    </body>
    </html>

when I use hugo version 0.45 to server site, I opened the post page and checked the source code:

![](https://gitee.com/heavenzone/picturebed/raw/master/zhonghaoguang.com/2018/2018-07-30-hugo-01.png)

there is an unexpected extra dot.

but when I switch to hugo version 0.37.1, the unexpected dot disppeared.

![](https://gitee.com/heavenzone/picturebed/raw/master/zhonghaoguang.com/2018/2018-07-30-hugo-02.png)

I don't know if this is the hugo's(ver 0.45) issue or I have used the wrong syntax.

I hope I have made myself clear this time \^_\^

**Comment by rdwatters** [comment]
> Which is why I added "exactly" to my question.

Only trying to help :smile: I figured maybe it was a not-so-clear reference to blogdown as an external helper possibly adding the extra dot. Apologies for accidentally hijacking your thread, @heavenzone 🙇
