### ISSUE TITLE
Failed to render "theme/_default/single.html"

### ISSUE THREAD

**Issue by rahmati** [gohugoio/hugo#5016]
When building the website I'm getting the following error:

> Failed to render "theme/_default/single.html": runtime error: invalid memory address or nil pointer dereference

The localhost server shows everything perfectly but when I upload the contents of the public folder, I get the example website with my information on home and contact section.

Any ideas on how I can debug this?

P.S. The code is at https://github.com/rahmati/academic-kickstart

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
