### ISSUE TITLE
Update Chroma dependency before next release

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#5019]
Can you update the chroma dependency before the next release so that https://github.com/alecthomas/chroma/commit/e4dff9a08cad984e9cf8eaa39fb80f2beae10484 gets included?

For future, is the latest chroma HEAD auto-fetched before each release?

**Comment by bep** [comment]
>For future, is the latest chroma HEAD auto-fetched before each release?

No. He should consider doing releases himself. Last Chroma is from March.
