### ISSUE TITLE
Deb package file name for extended Linux 64bit inconsistent with other names 

### ISSUE THREAD

**Issue by martignoni** [gohugoio/hugo#5022]
Name of packages on https://github.com/gohugoio/hugo/releases consistently have a simple **dash** between "Linux" and "32bit" (or "64bit"). Some examples:

- hugo_0.46_FreeBSD-32bit.tar.gz
- hugo_0.46_FreeBSD-64bit.tar.gz
- hugo_0.46_FreeBSD-ARM.tar.gz
- hugo_0.46_Linux-32bit.deb
- hugo_0.46_Linux-32bit.tar.gz
- hugo_0.46_Linux-64bit.deb
- hugo_0.46_Linux-64bit.tar.gz

Only the new extended Linux 64bit package has an **underscore** between "Linux" and "64bit":

- hugo_extended_0.46_Linux_64bit.deb

which can lead to some frustration when reading and copying too quickly and getting 404 errors :-)

I suggest that this name is changed to get the same construction than the others, with a single dash.

**Comment by bep** [comment]
Odd. Any idea, @caarlos0 ?

Note that we currently have a split Goreleaser setup with old and new Goreleaser version... But the name pattern looks to be the same, so this sounds like the deb behaviour has changed.

**Comment by caarlos0** [comment]
Let me take a look :)

**Comment by caarlos0** [comment]
opened a PR :)

**Comment by martignoni** [comment]
Thank you @caarlos0 and @bep.
