### ISSUE TITLE
Data URI shortcut for resources?

### ISSUE THREAD

**Issue by RJacksonm1** [gohugoio/hugo#5024]
Embedding tiny versions of images with an initial page load is a not-entirely-uncommon fallback for lazy loading of images, so users with slow / flaky connections get some vague semblance of the occasional image whilst its loading.

If we consider "resources" as a whole (CSS, JS, videos, text files, ...), they _could_ all be represented as data URIs.

(Although whether they _should_ is a use-case specific question that I'm definitely not in a position to try and answer 🤷‍♂️ ).

Sooo, Is there value in adding a Data URI shortcut for resources?

I'm thinking all it needs to output is:

```
data:{{ .MediaType }};base64,{{ .Content | base64Encode }}
```

Thoughts welcome!

**Comment by denettehay** [comment]
Can I please have my account back this is mine for real. My computer got hack and trying to get my shit back
