### ISSUE TITLE
Long urls or links extend beyond content and overlap sidebar

### ISSUE THREAD

**Issue by waroo** [gohugoio/hugo#5026]
If you have a really long url or link it will extend beyond the border for the main content instead of wrapping.  If you have a sidebar it will overlap the sidebar content.  As an example see the links at the bottom of the following page https://kitefaster.com/2017/05/22/create-today-widget-ios-app-swift/

**Comment by kaushalmodi** [comment]
It's a CSS issue; nothing to do with Hugo (The `header` and `main` tags are set to different widths in your CSS).

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
