### ISSUE TITLE
[Highlight] Dark spaces or ... in cpp code.

### ISSUE THREAD

**Issue by p-groarke** [gohugoio/hugo#5028]
I've tried 3 different themes now, each displays the same artifact. A dark space in templates or dark ... in templates.

![screenshot 2018-08-02 22 04 00](https://user-images.githubusercontent.com/156883/43620318-223c786c-96a0-11e8-9ddd-caea0eac759c.png)
![screenshot 2018-08-02 22 03 57](https://user-images.githubusercontent.com/156883/43620325-2796b02a-96a0-11e8-9f0d-423af116e1bd.png)

The problem seems to be spans, which have a dark background set :
`<span style="color:#960050;background-color:#1e0010"> </span>`

Here is a live example : https://p-groarke.github.io/blog/2018/05/19/declarative-functional-apis-a-k-a-abusing-lambda-parameters/

Note there also seems to be a conflict with that particular theme highlighting.

**Comment by kaushalmodi** [comment]
This is your theme/CSS issue. Also the info you provided is very inadequate.

This issue manager is not for "how-to" questions. For those, use https://discourse.gohugo.io/.

**Comment by p-groarke** [comment]
I changed themes 3 times. Also the info you require isn't very clear.

**Comment by onedrawingperday** [comment]
@p-groarke 
Please open a topic at the Forum https://discourse.gohugo.io/ and include a link to a repository with the source code of your project so that people can look into your issue.

If you cannot share it as is then include some dummy content.

This is the Hugo bugs issue tracker.

Thanks.
