### ISSUE TITLE
Creating new site and new theme renders blank page.

### ISSUE THREAD

**Issue by p-groarke** [gohugoio/hugo#5029]
v0.46 windows/amd64 BuildDate: 2018-08-01T09:01:27Z
```
hugo new site potato && cd potato
hugo new theme nowerky
cat theme = "nowerky" >> config.toml
hugo new post/test.md
hugo server
```
Navigating to your local site renders blank. There are no html files in /public if you run hugo generator.

**Comment by kaushalmodi** [comment]
It's not supposed to work like that (at least not as of now). 

Follow the [Quick Start guide][1] and come over to https://discourse.gohugo.io/ if you have more questions.

[1]: http://gohugo.io/getting-started/quick-start/

**Comment by p-groarke** [comment]
This is expected behavior? O_o
