### ISSUE TITLE
Support processing of animated GIFs

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5030]
See https://github.com/disintegration/imaging/issues/23

**Comment by cooperaj** [comment]
Did you really open this issue 2 minutes before mine at #5031 ?! Thats scary.

Sorry for the OT but I support this issue 👍

**Comment by cooperaj** [comment]
👍 I can look at trying to integrate the example code at disintegration/imaging#23 but my go fu is not strong.

**Comment by vkehayas** [comment]
Since the bot asked...I can see why this feature may not be a priority but it is preventing me from updating to the newest version of hugo-academic ever since it started using image processing of header images (see linked issue). I really think animated images are an appealing feature for header images in blogs and other types of websites.

**Comment by bep** [comment]
Yes, I have flagged this issue as "keep" and we will eventually get to it ...

**Comment by basnijholt** [comment]
Would it take a lot of work to fix this issue?

**Comment by cooperaj** [comment]
In my comment above (https://github.com/gohugoio/hugo/issues/5030#issuecomment-410286337) I think I'd found that it is just a case of doing some extra work around how animated images are processed - which was covered in the disintegration example file.

I've completely forgotten the details though so maybe it's more involved.

**Comment by bep** [comment]
>Would it take a lot of work to fix this issue?

Probably not, but any feature will take at least "some hours" when you consider implementation + tests + docs.

**Comment by xconverge** [comment]
I really wanted this, and took a stab at it. I am way too new to Go and hugo in general to get this working unfortunately, but any advice and pointing in the right direction would help

https://github.com/xconverge/hugo/commit/b469932eb103f6bfff4e3758a7b70dd70a86b1aa

I am having trouble successfully getting an io.Writer to then be able to  gif.EncodeAll

I think I need to clean up the optimization that was done before to prevent writing to files twice, and then somehow force it. Then clean up the resizing bit.

**Comment by kelseygonzalez** [comment]
+1 to the requests for gifs to be supported as featured images for hugo-academic.

**Comment by avanc** [comment]
Is it possible to disable image processing for gifs only? So that animation is not lost by using the original file?

**Comment by davidsneighbour** [comment]
@avanc not by configuration. I would attempt to do that by checking the path to the file and look if the extension is gif. See `.File.Ext` at https://gohugo.io/variables/files/#prose

**Comment by avanc** [comment]
@davidsneighbour Thanks.
With your hint I came up with the following workaround:
```
{{- $ext := path.Ext $image.RelPermalink -}}
{{- if eq $ext ".gif" -}}
  <!-- Do something (or nothing) with gifs -->
{{- else -}}
  <!-- Do something with other images -->
{{- end -}}
```

**Comment by dmilkie** [comment]
Animated gifs don't get any love, but animated **PNGs** are already supported I suspect (it worked in the single small test that I did).  That file is still just a .png file. Use an online converter to get yours into that format
https://ezgif.com/apng-maker

**Comment by bep** [comment]
@avanc a more cleaner solution would probably be:

```
{{ if eq $image.MediaType.SubType "gif" }}
```

**Comment by avanc** [comment]
@bep Thanks for the hint. Looks much cleaner and works as expected.

@dmilkie What version did you use? I have the same problems with APNGs as with the GIFs.

**Comment by dmilkie** [comment]
I am using the Wowchemy Website Builder, academic template, deploying with netlify.com.  From the deploy log it looks like it is using this version:
 Hugo Static Site Generator v0.80.0-792EF0F4/extended linux/amd64 BuildDate: 2020-12-31T13:46:18Z

**Comment by despens** [comment]
Testing with hugo v0.96.0 I don't see support for neither GIF nor APNG (contrary to what @dmilkie mentioned). This would be a fantastic feature to have.

**Comment by alexrichterxyz** [comment]
I am waiting for this too. Would be nice to be able to convert animated GIFs to WEBP.

**Comment by bep** [comment]
>Is it possible to disable image processing for gifs only? So that animation is not lost by using the original file?

I just tested this, and it animates nicely:

```htmbars
  {{ $giphy := resources.Get "images/misc/giphy.gif" }}
  <img src="{{ $giphy.RelPermalink }}" />
```

We don't edit the original.

**Comment by bep** [comment]
>I am waiting for this too. Would be nice to be able to convert animated GIFs to WEBP.

The scope of this particular issue is animated GIFs. WEBP is harder.
