### ISSUE TITLE
AlternativeOutputFormats has wrong RSS MediaType.Suffix

### ISSUE THREAD

**Issue by ePirat** [gohugoio/hugo#5032]
The following snippet from the hugo [rss template documentation](https://gohugo.io/templates/rss/)

```
{{ range .AlternativeOutputFormats -}}
    {{ printf `<link rel="%s" type="%s+%s" href="%s" title="%s" />` .Rel .MediaType.Type .MediaType.Suffix .Permalink $.Site.Title | safeHTML }}
{{ end -}}
```

generates the following HTML:

```
<link rel="alternate" type="application/rss+xml+xml" href="https://example.com/index.xml" title="My Blog" />
```

Note that the `type` has one extraneous `+xml`: `application/rss+xml+xml`

Tested with `Hugo Static Site Generator v0.46/extended darwin/amd64 BuildDate: unknown`

**Comment by bep** [comment]
>Or do you want to track it and fix it in this repo?

No, please fix. I read it wrong.

**Comment by kaushalmodi** [comment]
@ePirat Thanks for reporting this. It's now fixed (see https://gohugo.io/templates/rss/). Next time if you find documentation issues, report them in the https://github.com/gohugoio/hugoDocs repo.
