### ISSUE TITLE
Add an Markdown image processor

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5034]
This relates to #4574 and #3949

Also, see 
* https://github.com/russross/blackfriday/issues/181
* https://talk.commonmark.org/t/consistent-attribute-syntax/272/114

There are lots of stuff here I have not thought through, so I just throwing the ideas down on paper. But people will probably want to do some image processing of the images they refer to in Markdown. I guess we could:

* Create some config with processing instructions per Glob pattern, e.g. "blog/**.jpg" => "Fill 640x300".
* Possibly also take these instructions from a filename convention.

**Comment by regisphilibert** [comment]
I like the filename convention a lot. It gives editor control. 

Ideally this could be mapped with predefined processing sets so editors can only choose between a few “processing sets” defined by the project/theme creator.

**Comment by regisphilibert** [comment]
Blue sky for this: 
glob pattern setting defines defaults. 
Filename convention allow default overwrite by editors using predefined processing set.

**Comment by bep** [comment]
Note to self:

Doing this work, we might take it the extra mile, and add some support for `srcset` to potentially create images in different sizes.

**Comment by onedrawingperday** [comment]
> Note to self:
>
>Doing this work, we might take it the extra mile, and add some support for srcset to potentially create images in different sizes.

If you're going to do the above, it would also be very useful if we could add a `class` attribute to Markdown images through the config (for CSS and lazy loading purposes).

**Comment by onedrawingperday** [comment]
> How is that related to the above?
Ok. It's not related to this particular issue of image processing Markdown images. 

But I just thought that if you're going the extra mile to add a `srcset` attribute to these images through Hugo, a `class` attribute would complement the feature.

**Comment by bep** [comment]
It was mentioned in another thread that we could use HTML (or rather SGML) processing instructions to do this, and that this should be possible to extract from Blackfriday's AST

```
![My image](img.png)<?hugo command="Fit" options="400x300" ?>
```

Or something like that. It that works, It would be totally usable. The above will turn into a HTML comment when viewed on GitHub. And if we're careful about how we create the syntax above it should be a fairly easy search-replace transition once CommonMark gets some kind of standard.

**Comment by jan-xyz** [comment]
Is there still a plan to support this? I would love to have native `srcset` support in Hugo :)

**Comment by bep** [comment]
No, this is supported via the Markdown Render Hooks.
