### ISSUE TITLE
Add support for Babel in resource pipelines

### ISSUE THREAD

**Issue by mpourismaiel** [gohugoio/hugo#5039]
With #4446 we now have resource pipelines which is really great but only works with CSS/Sass/Scss. I have no idea how but having support for Babel sounds really good.

Currently we use Webpack or other tools to build the frontend stuff but with resource pipeline it's easier to let Hugo handle CSS or Sass. Adding support for Babel would make it easier to use newer JS features or even JSX and other stuff.

**Comment by westurner** [comment]
#5764 "Support for ES6 transpilation using Babel" has a PR: #5772
