### ISSUE TITLE
--minify does not work on the script tags in partials

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#5042]
Example:

- [Page minified using **external** minification][1]
- [Page minified using the new `--minify`][2]

View the source of the above 2 HTML pages. The difference will be visually evident in the beginning of the HTML sources.

With *external* minification, the code in script tags gets minified too. The inline script is from [this partial][3]. The partial is included in single.html layout [here][4].

My site uses strict CSP with hashes for inline scripts. As the inline script when using `--minify` did not get minified, I started getting CSP failure for that (functionally, the dynamic TOC works on that page for the external minified version, but not for the other).

It would be great if the inline script can get minified too. If not, I'd like to understand (for documentation) why it did not get minified..
- because of the `minify` switches used by Hugo?
- because that code is in script tags?
- because that inline code is included by a (cached) partial?

Thanks!

[1]: https://scripter.co/time-formatting-in-go/
[2]: https://minify--scripter-co.netlify.com/time-formatting-in-go/
[3]: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/master/layouts/partials/toc_on_side.html
[4]: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/88fbe6a43ebf348c99dd247fdd7a14df453c9f15/layouts/_default/single.html#L32

**Comment by bep** [comment]
That the internal minification is different than some external minification, should not come as a surprise.

As I said in the other thread, I'm not working any more short-term on this particular feature, but if you want to investigate, feel free.

**Comment by kaushalmodi** [comment]
> That the internal minification is different

More than different.. just trying to understand why inline JS in script tags is not getting minified.

**Comment by bep** [comment]
>More than different.

Sure, but the statement is a little like "Hugo behaves differently from Jekyll".

**Comment by bep** [comment]
See https://github.com/gohugoio/hugo/commit/755d1ffe7a22d8ad83485240ff78cf25d501602f

There may be ways to loosen up the matching here, but taking every "<script>" tag as JS sounds a little funky.

**Comment by kaushalmodi** [comment]
Awesome, [adding `type="application/javascript"`][1] fixed this!

> There may be ways to loosen up the matching here, but taking every "<script>" tag as JS sounds a little funky.

I agree.

Thanks!

---

Now no need to update the hashes for CSP when using the `--minify` switch. 🎉 

[1]: https://gitlab.com/kaushalmodi/hugo-theme-refined/commit/ce18a104fd5bfc02ce48286ad09be7afd081bfa5
