### ISSUE TITLE
Wrong pagination on 404 pages

### ISSUE THREAD

**Issue by tyrondis** [gohugoio/hugo#5046]
Hugo version: `v0.46/extended darwin/amd64`

The internal pagination template `_internal/pagination.html` renders additional page links on a 404 page that don't exist and lead themselves to `404`s.

**Comment by bep** [comment]
Why do you include that template on the 404 template?

**Comment by tyrondis** [comment]
I am basically rendering a version of my homepage that contains an info box saying "This page has moved. Maybe you like some of our other posts" and render the same list with pagination.

I could just redirect to the homepage, I still find this bug peculiar though and thought you might wanna know.
