### ISSUE TITLE
disableHugoGeneratorInject is ignored

### ISSUE THREAD

**Issue by bgdnlp** [gohugoio/hugo#5048]
Using "Hugo Static Site Generator v0.46 darwin/amd64 BuildDate: 2018-08-01T09:00:55Z", `toml` config format, binary downloaded from GitHub. The non-extended version.

Setting `disableHugoGeneratorInject = true` has no effect, the generator meta tag is still inserted.

Moving to v0.46 from v0.37, which caused all pages to be marked as changed. With v0.37 the tag is not inserted.

**Comment by bep** [comment]
>Moving to v0.46 from v0.37, which caused all pages to be marked as changed. 

We only insert this tag if 1) is home page 2) there is no generator tag there before 3) disableHugoGeneratorInject is not set

If you are saying that **all the pages** are marked as changed, there must be a different explanation.

Also, this code has been rewritten for 0.47.

**Comment by bgdnlp** [comment]
I'm not sure where to look. The tag inserted is:
```
<meta name="generator" content="Hugo 0.46" />
```

The old tag was:
```
<meta name="generator" content="Hugo 0.37.1" />
```
and it was also present on every page I checked.

My theme was doing cache busting by adding `?unix-time` to every js, which means most (all?) pages were being regenerated every time, I disabled that now. Maybe that has something to do with it?

Anyway, it doesn't really bother me, just noticed and thought I'd let you know. If you say the code was rewritten and the issue is probably something else, please feel free to close the incident. I can retest with 0.47 when the binary is available. If I can help with more information, let me know.

**Comment by bep** [comment]
>and it was also present on every page I checked.

I will eventually check, but since the logic is to add this to home page only (I just checked the code), I suspect that you get that generator tag from the theme itself.

**Comment by bgdnlp** [comment]
And you are right, it's the theme that adds it. Apologies for wasting your time, I'll close the incident. Thank you.
