### ISSUE TITLE
Indeterminate builds on medium complexity site

### ISSUE THREAD

**Issue by jhabdas** [gohugoio/hugo#5052]
Error observed in `0.44` and `0.46`. See https://github.com/gohugoio/hugo/issues/5052#issuecomment-411746684 for proof, https://github.com/gohugoio/hugo/issues/5052#issuecomment-411704933 for error conditions and https://github.com/gohugoio/hugo/issues/5052#issuecomment-411748890 for reduced test case. Possibly related are the errors shown in the below GIF, which mirror a known bug in the `theme` setting as shown in #5061 when using an array value for the setting (as opposed to using an env var or the plural form `themes`).

**Comment by jhabdas** [comment]
This is a little edgier than I thought. Not able to produce a reduced test case, therefore closing.

**Comment by jhabdas** [comment]
To the best of my knowledge this issue was caused by indetermination in the `hugo server` command under a corner case where the following hugo features are combined:

- multilingual leaf bundle
- with page resources


And then `hugo server` successfully watches files and call to a shortcode from the content  is introduced before hugo has a chance to purge the files in the `resources` directory in a full regeneration (which doesn't seem to happen every time even when the directory is manually purged).

**Comment by jhabdas** [comment]
![derp](https://user-images.githubusercontent.com/440298/43899961-112abf90-9c16-11e8-939a-7e93b7e095ee.gif)

Reliably reproducing now, unreliably.

**Comment by jhabdas** [comment]
https://git.habd.as/jhabdas/hugo-indeterminate for test case. reproducing on `0.46` extended darwin build. filevault enabled. to reproduce build, then rebuild, then rebuild some more as shown in the above gif.

**Comment by nonumeros** [comment]
@jhabdas thanks for the test case... it reminded of an issue that happened a while back. Interesting nonetheless.

But if you look at the error `unable to locate template for shortcode "blockquote"` you'd notice it's looking for a template that it can't find. 

So you'd have to create the template on say the **shortcodes** directory and fill its content

     
     <blockquote {{ with .Get "class" }}class="{{ . }}"{{ end }} {{ with .Get "citelink" }}cite="{{ . }}"{{ end }}>
       {{ .Inner }}
       {{ with .Get "citelink" }}
         <cite><a target="_blank" href="{{ . }}">{{ $.Get "cite" }}</a></cite>
       {{ else }}
         <cite>{{ .Get "cite" }}</cite>
       {{ end }}
     </blockquote>

now the issue is gone.

**Comment by jhabdas** [comment]
@nonumeros Looks like you found the source for the blockquote shortcode hugo is erroring on, which exists in the shortcodes directory of the theme. Figuring the error was related to a [lookup order](https://gohugo.io/templates/lookup-order/) bug in hugo I tried copying the custom `blockquote.html` shortcode up from the theme to the site-level yet the bug persisted.

Whenever I see indeterminism in a program it's 9 times out of 10 a race condition. In this case I believe the race is caused by hugo's use of the filesystem, which might be related to this: https://github.com/gohugoio/hugo/issues/1460

**Comment by nonumeros** [comment]
> I tried copying the custom blockquote.html shortcode up from the theme to the site-level yet the bug persisted

With blockquote.html in place at site-level, It could not have persisted neither with 0.46, nor 0.45.1, nor with 0.44. How would you know that? 

I still agree with you: without blockquote.html, I would expect to have a template error all the time.

**Comment by jhabdas** [comment]
> With blockquote.html in place at site-level, It could not have persisted neither with 0.46, nor 0.45.1, nor with 0.44. How would you know that?

But it does _on my machine_.

> I still agree with you: without blockquote.html, I would expect to have a template error all the time.

Totally. And I'm curious if you've tried the test case to reproduce the error given the shortcode _is_ indeed in the lookup order.

**Comment by nonumeros** [comment]
> reproduce the error given the shortcode is indeed in the lookup order.

I did run it with the **shortcode.html** in place or the expected lookup order (going by what the  error message stated in the first place) afterwards and it did not return the expected error. 

Interesting enough on a different machine and with your test case configuration file unmodified running `hugo serve` returned the already known `unable to locate template for shortcode blockquote` a few times, and then surprisingly returned `Error: Unable to find theme Directory: /themes/after-dark` 

So after that message I modified the configuration and omitted the `themesDir` or commented it out. 

The next message that followed was the already known

```
Building sites … ERROR 2018/08/15 06:51:00 Unable to locate template for shortcode "blockquote" in page "post/secure-your-digital-life/index.es.md"
ERROR 2018/08/15 06:51:00 Unable to locate template for shortcode "blockquote" in page "post/secure-your-digital-life/index.md"
ERROR 2018/08/15 06:51:00 Unable to locate template for shortcode "blockquote" in page "post/secure-your-digital-life/index.id.md"
Error: Error building site: logged 3 error(s)

```
So everything good so far from above

But then out of the blue

```
Building sites … ERROR 2018/08/15 06:51:06 Error while rendering "taxonomy" in "": template: _default/taxonomy.html:26:7: executing "_default/taxonomy.html" at <partial "modules.htm...>: error calling partial: template: partials/modules.html:3:7: executing "partials/modules.html" at <partial "modules/fra...>: error calling partial: Partial "modules/fractal-forest/index.html" not found
ERROR 2018/08/15 06:51:06 Error while rendering "taxonomyTerm" in "": template: _default/terms.html:26:7: executing "_default/terms.html" at <partial "modules.htm...>: error calling partial: template: partials/modules.html:3:7: executing "partials/modules.html" at <partial "modules/fra...>: error calling partial: Partial "modules/fractal-forest/index.html" not found
ERROR 2018/08/15 06:51:06 Error while rendering "section" in "": template: _default/list.html:26:7: executing "_default/list.html" at <partial "modules.htm...>: error calling partial: template: partials/modules.html:3:7: executing "partials/modules.html" at <partial "modules/fra...>: error calling partial: Partial "modules/fractal-forest/index.html" not found
ERROR 2018/08/15 06:51:06 Error while rendering "home" in "": template: index.html:26:7: executing "index.html" at <partial "modules.htm...>: error calling partial: template: partials/modules.html:3:7: executing "partials/modules.html" at <partial "modules/fra...>: error calling partial: Partial "modules/fractal-forest/index.html" not found
ERROR 2018/08/15 06:51:06 Error while rendering "page" in "post/secure-your-digital-life/": template: post/single.html:26:7: executing "post/single.html" at <partial "modules.htm...>: error calling partial: template: partials/modules.html:3:7: executing "partials/modules.html" at <partial "modules/fra...>: error calling partial: Partial "modules/fractal-forest/index.html" not found
Total in 153 ms
Error: Error building site: logged 5 error(s)
```
Which never showed up the first time around while running 0.46

**Comment by nonumeros** [comment]
Akin to https://github.com/gohugoio/hugo/issues/5044 the use of
`themes` (when theme components are in use rather than just a theme)
or `theme` (when just a theme is specified on sites' configurations
that require only one rather than the use of multiple themes)
variables should be implemented around this issue thus returning a
warning at best  Not as a simple-minded-shortcut of whatever theme
ought to be used but at the very least as a warning before continuing
building.  Building what anyway if no site ought to be built without
the needed file as your test case error clearly showed.

But this feature of `current version does not supports blah blah blah`
was already implemented on pipes (I think).  so this would  just be a
cosmetic workaround if the real issue is not addressed. I thought that
replacing `theme` in your config file with `theme` on your test case,
would further behave as expected (errors), but I thought to have come
across the same inconsistencies than before, that I can't just
reproduce now.

**Comment by jhabdas** [comment]
Closing without maintainer vetted response.

**Comment by nonumeros** [comment]
>Closing without maintainer vetted response

@jhabdas I like what you did with the code. On the other hand I couldn't find enough info related to `.Inner` for example, so that was the deal breaker for me. 

Reopen the issue. @bep is a good guy. Right @bep ?

**Comment by jhabdas** [comment]
@nonumerous thanks for reproducing. I hadn't seen that you did before closing. I'll keep the test case around for a time but have little stock in furthering this research due to to the unexpected removal of my two-year old theme from the theme site.

**Comment by jhabdas** [comment]
@nonumeros thanks for reproducing. I hadn't seen that you did before closing. I'll keep the test case around for a time but have little stock in furthering this research due to to the unexpected removal of my two-year old theme from the theme site.

**Comment by jhabdas** [comment]
OP closed. Please file a new bug. Thanks.

**Comment by nonumeros** [comment]
@jhabdas  the reason I mentioned earlier about the `.Inner` variable was mainly because by tweaking around with it I noticed that the same effect was present than say by omitting the **less-than**  `<` and **greater-than** `>`  delimiters on each of the blockquote functions for index.md files (index.md, index.es.md, and index.id.md)...

Of course, this is not to say that the issue is resolved. It's clearly not the case. And your code proves it.
