### ISSUE TITLE
[Hugo 0.46] SASS pipeline doesn't work with i18n correctly

### ISSUE THREAD

**Issue by mirkoschubert** [gohugoio/hugo#5053]
Hi, I just want to report a bug in the new SASS pipeline / preprocessor.

### Prerequisites

- I have two languages configured (`en` and `de`).
- The SASS files are under `/themes/mytheme/assets/sass/`.
- The outcome should be `/public/en/assets/css/main.css` and `/public/de/assets/css/main.css`.

### 1st Try: The standard way

First I tried it the way it is described in the Hugo Docs:

```html
{{ $css := resources.Get "sass/main.sass" | toCSS (dict "targetPath" "assets/css/main.css") }}
<link rel="stylesheet" href="{{ $css.Permalink }}" />
```

If I now render the website with `hugo`, the `assets` will be only rendered once directly in the `/public/` directory:

```
public
├─ assets
|  └─ css
|    └─ main.css
├─ de
└─ en
```

Obviously in none of the languages the css file will be loaded correctly. 😏 

### 2nd Try: The correct i18n

Next, I tweaked the code a little bit, so the SASS files would be compiled per language:

```html
{{ $target := printf "%s/assets/css/main.css" .Lang }}
{{ $css := resources.Get "sass/main.sass" | toCSS (dict "targetPath" $target) }}
<link rel="stylesheet" href="{{ $css.Permalink }}" />
```

The rendering process works perfectly. The SASS files will be compiled to both language folders. **But again...** The path of the CSS file won't be written into the HTML file correctly, so the CSS won't be loaded either. Instead the `$css.Permalink` is equal to  `$target`:

```html
<link rel="stylesheet" href="en/assets/css/main.css" />
```

Of course, it should be `assets/css/main.css`.

### 3rd Try: All correct - or not?

So, why shouldn't I simply replace the `$css.Permalink` with the correct path? Just like that:

```html
{{ $target := printf "%s/assets/css/main.css" .Lang }}
{{ $css := resources.Get "sass/main.sass" | toCSS (dict "targetPath" $target) }}
<link rel="stylesheet" href="{{ .Site.BaseURL }}assets/css/main.css" />
```

This should work, **but again...** It won't. 😄 You can read it in the Hugo Docs: Without `$css.Permalink` the SASS files won't be compiled at all. It took quite some time for me to figure that out.

### Conclusion & Proposition

If I'm seeing this correctly and don't miss anything, SASS pipelines won't work with multi language installations for now. Please correct me if I'm wrong.

I would strongly suggest, that SASS should be compiled anyway, even if `$css.Permalink` isn't be present. At least then my third try would be a legit solution for i18n pipelines.

And **please** work on i18n support for SASS pipelines!

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by mirkoschubert** [comment]
Found a [workaround](https://discourse.gohugo.io/t/sass-pipeline-multi-language-bug-provisional-workaround/13477) for now, but **please** fix this!

**Comment by mirkoschubert** [comment]
What the... Seriously? 😠 

If this is the way you treat contributors, I should seriously consider going back to Jekyll and never recommend Hugo again.

**Comment by kevingimbel** [comment]
@mirkoschubert I'm sorry you're apparently having a bad experience with Hugo so far. 

I agree with bep however: what you describe is _not a bug_. You obviously have a different expectation as to how SASS should be compiled in a multi-language setup and quite honestly I do not see the use case for having multiple styles per language at the moment, at least not as default.

If you feel like per-language CSS files should be a thing than please go to the forums and discuss it with others there - Hugo has always had an open conversion about features and feature requests as well as planning features "together". Maybe you'll realise its not needed or maybe others jump in and say: Yeah, that's a thing we should have!

From a healthy discussion we can all benefit but being salty if your request is closed as"not a bug" and saying things like:

> If this is the way you treat contributors, I should seriously consider going back to Jekyll and never recommend Hugo again. 

is not helping anybody.

**Comment by mirkoschubert** [comment]
@kevingimbel Sorry, this was my (maybe too furious) reaction of @bep changing and closing an ongoing discussion about this in the forums, after recommending it here on Github. Therefore, I can't discuss it with others in the forums. 😉 

Correct me if I'm wrong:

So, the **intended** way of using CSS files with Hugo in a multilingual environment is to have them in a common assets directory, right? What about every other common asset (such as JS files, images etc.)? They are copied in the specific language directory. Shouldn't they all go to the same asset folder?

And what about **deploying** websites with multiple languages? While it would work when every installation is a subdirectory on one domain, it won't if every language has its own subdomain or domain! (In my case I have two domains for two languages, so it wouldn't work at all with »common assets«.)

**Comment by kevingimbel** [comment]
> So, apparently the intended way of using CSS files with Hugo in a multilingual environment is to have them in a common assets directory, right?

I believe this is the case, yes. I have little to no experience with multi language setups tho. 

> What about every other common asset (such as JS files, images etc.)? They are copied in the specific language directory by default. Shouldn't they all go to the same asset folder?

Maybe, maybe not. Again I do not have enough multi language setup experience for this.

> And what about deploying websites with multiple languages? While it would work when every installation is a subdirectory on one domain, it won't **if every language has its own subdomain or domain**! (In my case I have two domains for two languages, so it wouldn't work at all with »common assets«.)

That's the use case that was missing from your original issue report and from your forum post. If you have two different domains it makes sense to get assets for each - or have a function to retrieve the asset paths.

I would recommend you to write down what you try to accomplish as detailed as possible and at what point you're missing a feature in Hugo, then open another thread in the forums (or add to the existing, it's been re-opened). We can then all have a discussion about how this is best implemented or if there's a way to have assets for two domains.

**Comment by noreff** [comment]
I belive what was described here by @mirkoschubert is indded bug. I have a website with 11 languages. I use something like this to output js (same logic aplies to css / sass:
```
{{ $built := resources.Get "js/app.js" | babel }}
<script src="{{ $built.Permalink }}" crossorigin="anonymous"></script>
```
For all 11 sites I have same linked to the final js file, which is served from the default language. I also get a CORS problem because of that.
It's also looks like a bug to me, can it be re-evaluated and re-opened?

**Comment by davidsneighbour** [comment]
https://discourse.gohugo.io/t/is-it-possible-to-use-translations-in-assets/20726/4
