### ISSUE TITLE
GitInfo does not work with multiple contentDir's

### ISSUE THREAD

**Issue by geeknoid** [gohugoio/hugo#5054]
I'm getting inconsistent "Failed to find GitInfo" for my site. As I build the site, the errors occur for different files from run to run. It seems alphabetical though. Failures start at a particular file, and then all subsequent files are later alphabetically speaking. Hundreds of files seem fine, and then when it starts failing, a hundred files or so indicate failure.

Since the starting point of the error varies from run to run, this would seem to indicate some sort of race condition.

I've seen this behavior on macOS and Linux, on Hugo 0.44 and 0.46. 

I don't know how long this link will be good for, but here's a Netlify log showing the errors: https://app.netlify.com/sites/preliminary-istio/deploys/5b6dbaf9c6aed63f1bc8831b

The docs I'm trying to build are from https://github.com/istio/istio.github.io

**Comment by bep** [comment]
>Since the starting point of the error varies from run to run, this would seem to indicate some sort of race condition.

Hugo is running many build tasks in parallel (which is why it is so fast).

We should try to improve the error message here, but it isn't easy -- as it seems that your initial Git log operation did succeed.

As this feature requires a Git history long enough to reach each of the "last commits", I suspect that you run `git clone --depth 1` or similar. Which does not work in this case.

**Comment by geeknoid** [comment]
> As this feature requires a Git history long enough to reach each of the "last commits", I suspect that you run git clone --depth 1 or similar. Which does not work in this case.

The repo I'm using is clone with "git clone", no depth limit. All git history is present. You can try cloning the repo I mentioned, you'll hopefully see those git errors as well. I see them locally, and netlify which we use to build our site also uses a plain 'git clone' and also sees the errors.
