### ISSUE TITLE
High use of newline and space

### ISSUE THREAD

**Issue by dfmabbas** [gohugoio/hugo#5069]
Hello . all HTML files generated by hugu, overwhelming characters of newline and space are used.
We're having problems increasing the size and lowering the performance, please fix this problem.

**For example, the sample file generated :**

```
   <a href="//github.com/username" target="_blank" rel="noopener"><img class="icon" src="https://username.github.io/blog/img/github.svg" alt="github" /></a>
        

        

        
            <a href="//twitter.com/username" target="_blank" rel="noopener"><img class="icon" src="https://username.github.io/blog/img/twitter.svg" alt="twitter" /></a>
        

	

        

        

        

        

        
            <a href="//instagram.com/username" target="_blank" rel="noopener"><img class="icon" src="https://username.github.io/blog/img/instagram.svg" alt="instagram" /></a>
        

        

        

        
            <a href="username@r.com"><img class="icon" src="https://username.github.io/blog/img/email.svg" alt="email" /></a>
        

```

**Comment by bep** [comment]
In next Hugo you can do `hugo --minify` which will help with this. The above isn't "produced by Hugo", but an output from the Go templates. There are ways to handle whitespace in templates, but it is currently manual. 

In any case it belongs on the Go tracker: https://github.com/golang/go/issues

I have seen similar issues there, but It seems to be a hard problem.
