### ISSUE TITLE
Display list of GitHub users who have contributed to a page

### ISSUE THREAD

**Issue by jaredbhatti** [gohugoio/hugo#5070]
Summary: 
Boost recognition of documentation contributions by featuring contributor avatars as an author byline.

Example: 
It would be useful to highlight who has contributed to each page in a hugo site by pulling the list of contributors from Github and featuring their avatars in the author byline. Microsoft Azure does this in their content [under the title of each doc](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-technical-overview). 

![image1](https://user-images.githubusercontent.com/6146946/44050265-576ad094-9eeb-11e8-94fc-bfb5b48f0622.png)

Thoughts on how this should be implemented: 

1. Surface document contributors by displaying a byline of the following format: Updated [date] by [avatar]. Contributors: [avatars in reverse chronological order]]
2. Updated date:
  - On hover, display the title of the commit
  - On click, open the commit in GH

3. Avatar behavior (all)
  - On hover: Display the user's display name from GitHub profile (not their handle) (Jared Bhatti, not jaredb)
  - On click: Open the GH user profile

4. Contributor avatars
  - Display 5 most recent contributors (after the most recent contributor) in reverse chronological order
  - If doc has more than six contributors, display a link: All
  - On hover, display a tooltip: "See all N contributors"
  - On click: Open the document on GitHub

**Comment by jmooring** [comment]
This should be handled with a partial that calls the GitHub API with `resources.GetRemote`. For example:

```text
git clone --single-branch -b hugo-github-issue-5070 https://github.com/jmooring/hugo-testing hugo-github-issue-5070
cd hugo-github-issue-5070
hugo server
```

The "list-github-contributors" partial renders something like this...

![image](https://github.com/gohugoio/hugo/assets/335669/27265846-afd5-4471-b92f-546f123838f5)

...where each avatar is linked to the user's GitHub account.
