### ISSUE TITLE
Add RTLCSS support for resource pipelines

### ISSUE THREAD

**Issue by mpourismaiel** [gohugoio/hugo#5079]
With support for [RTLCSS](https://github.com/MohammadYounes/rtlcss) in the pipelines we can have support for multilingual websites a lot more easily. The script is written in JavaScript but I think if the feature is implementable, we can either convert it to Go or think of something so it can be run using NodeJS, that way Babel (#5039) would be implementable as well.

**Comment by stp-ip** [comment]
If that is something, worthwhile for Hugo, there might be engineering resources we can put behind it. Don't want to start anything without a first discussion.

**Comment by bep** [comment]
Why not make this as a postcss plugin?

**Comment by jmooring** [comment]
This is available as a PostCSS plugin:
<https://github.com/elchininet/postcss-rtlcss>

Try it:

```text
git clone --single-branch -b hugo-github-issue-5079 https://github.com/jmooring/hugo-testing hugo-github-issue-5079
cd hugo-github-issue-5079
npm ci
hugo server
```
