### ISSUE TITLE
List view for content type

### ISSUE THREAD

**Issue by leroylee** [gohugoio/hugo#508]
I have created a content type (also called archetype?) called 'assignment' according to the docs. I created a folder under layouts and added a single.html file and a list.html file. The single.html is working great, but hugo seems to be ignoring my list.html and rendering the default. 

Although the content type section says to create list.html (which makes sense) the 'content list section' says that it will never look for that file.
- /layouts/section/SECTION.html
- /layouts/_default/section.html
- /layouts/_default/list.html
- /themes/THEME/layouts/section/SECTION.html
- /themes/THEME/_default/section.html
- /themes/THEME/layouts/_default/list.html

Am I reading this right? Hugo will not check for the file /layouts/SECTION/list.html? Could someone better explain this?

**Comment by paulwalk** [comment]
This just doesn't seem to be true:

>> SECTION is a placeholder for the actual section name. In your case it would be /layouts/section/assignment.html
or 
/layouts/assignment/list.html

the first of these paths works, but the second does not.

As others have said, this seems to be both incorrectly documented, and somewhat counter-intuitive.

**Comment by chaseadamsio** [comment]
@spf13 any chance we can revisit this? I've been struggling with it again this morning and came back to this issue and I think there must be a bug in implementation or the docs need to be updated because this doesn't work.

**Comment by moorereason** [comment]
I've created a new issue for this.  See #2032
