### ISSUE TITLE
New ToC and Footnotes data structures

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5087]
Go 1.11 is right around the corner. With that comes Go modules, which should solve the versioning issues we currently have with an upgrade to Blackfriday v2. I have started some investigations in another project. 

The goal of this first "sprint" is to

1. Upgrade to BF2 in a way that makes it easy to plug in some hooks that we have described in other issues (URL rewriter etc.), allow for renderer per output format etc (HTML, LatEx ...).
2. Add some proper data structures for table of contents and foot notes

This issue discusses 2) Above.

For ToC we currently have this HTML `.TableOfContents` blob. We cannot remove that over night so I suggest we add a new "container" in Page that contains Markdown-related  metadata.

* Name? `.MD.TableOfContents`?

That object will in the first go contain two data structures:

* `.TableOfContents`
* `.Footnotes`

For `TableOfContents`, I suggest a list of:

```bash
Title
Children
Parent
```

For `Footnotes` I suggest a list of:

```
ID
Link
```

Instead of `Link` maybe we should just reuse the term `RelPermalink` etc.

Note that the `Footnotes` list is meant to be used to render "somewhere else" in a template, so we also need a way to not render it in the main content.

**Comment by rdwatters** [comment]
Is it unrealistic to keep `.TableOfContents` with your default behavior above but instead add arguments for start/stop based on `h` element?

```
{{ .TableOfContents 2 3 }}
```

Or the same as your comment above by adding the `.MD` to my example?

**Comment by rgov** [comment]
This goes well with the new render template hook for headings. There is now a `HeadingContext` class which could be used:

https://github.com/gohugoio/hugo/blob/2fd0a5a6781456e88745b370d12aaf5351a020ff/markup/converter/hooks/hooks.go#L37-L48

**Comment by gj52** [comment]
> This goes well with the new render template hook for headings. 

Can we collect this heading structures in a map/list and inject it in render-toc.html?
