### ISSUE TITLE
.Render method doesn't look for the right Output Format tpl file.

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#5090]
In a list template, while ranging on the children pages,   `.Render` (like `.Permalink`) systematically defaults to the the first output format defined for that page.
So if in my project the section output format is set as `section: ['html', 'json']`, and `layouts/type/list.json.json` looks something like that:
```
{{ range .Data.Pages }}
{{ .Render "item" }}
{{ end }}
```

`.Render "item"` will look for `layouts/type/item.html` instead of `layouts/type/item.json`

Blue sky wish: When using the `.Render` method, Hugo uses the current template's (list or single) output format to determine what template file to "render" (this already seem to work on the single template).

Other: User can use `(.OutputFormats.Get "json").Render` which currently returns `can't evaluate field Render in type *hugolib.OutputFormat`

PS: I started this [thread](https://discourse.gohugo.io/t/api-theme-component-need-help-taming-render-and-scratch/12566) a while back before figuring out what the issue was about, it has more detail information about the context.

**Comment by bep** [comment]
This will be fixed as part of #5583 -- sorry that this has taken so long, but I really had to look at this in a bigger picture.
