### ISSUE TITLE
Local installation of postcss-cli doesn't work on Windows

### ISSUE THREAD

**Issue by ericselin** [gohugoio/hugo#5091]
# Problem

Using `postcss-cli` from a local `node_modules` folder within a project currently doesn't work on Windows. The reason is that `postcss` found under `node_modules/postcss-cli/bin` is not executable on Windows.

https://github.com/gohugoio/hugo/blob/6746826689faca5ca09f46725501dceff1a0ebbc/resource/postcss/postcss.go#L101

# Proposed fix

I propose to always try to find the local installation under `node_modules/.bin`. This should work on other environments as well.

P.S. I'm using `Hugo v0.47`

**Comment by numbfall** [comment]
Any update on this? Or a possible work-around? Other than installing `postcss-cli` grobally? I am on v0.49.2

**Comment by jzeneto** [comment]
This still ocurrs with Hugo 0.54 in Windows 10. I agree with @ericselin that this is necessary. And since already there's a pull request, this should be put in mind.

**Comment by gesellix** [comment]
This occurs for me with Hugo v0.55.6/extended in windows/amd64.

Error message:

> Building sites … ERROR 2019/07/14 17:35:16 error: failed to transform resource: POSTCSS: failed to transform "scss/main.css" (text/css): PostCSS not found; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/

Contents of `node_modules/.bin`:

```
λ ls node_modules\.bin\
atob*     autoprefixer*     browserslist*     esparse*     esvalidate*     js-yaml*     postcss*     semver*     which*
atob.cmd  autoprefixer.cmd  browserslist.cmd  esparse.cmd  esvalidate.cmd  js-yaml.cmd  postcss.cmd  semver.cmd  which.cmd
```
