### ISSUE TITLE
Hugo server confused by copying and pasting directories in content

### ISSUE THREAD

**Issue by DrGo** [gohugoio/hugo#5096]
Small inconvenience, 
When I move a dir between two subdirs under content (using cut and paste), hugo server generates html for the moved subdir twice (both in the new and old location). Restarting hugo server fixes the problem.

Thanks,

**Comment by bep** [comment]
What version? If not the last one, you should test it.

**Comment by DrGo** [comment]
Hugo Static Site Generator v0.46/extended darwin/amd64 BuildDate: unknown

**Comment by bep** [comment]
You should try 0.47.

**Comment by DrGo** [comment]
Thanks,
I tried: Hugo Static Site Generator v0.47/extended darwin/amd64 BuildDate: unknown

I am still seeing the same behaviour. 
In case it is helpful, am using this theme https://learn.netlify.com/en/

**Comment by nonumeros** [comment]
it works with the dirs/subdirs' `index.md` files whether you copy or create your own content.. but I agree it defeats the purpose.

**Comment by DrGo** [comment]
Not a major issue. I am just restarting hugo server if I need to copy-paste. Thanks,
