### ISSUE TITLE
Check rasberry build

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5101]
See https://discourse.gohugo.io/t/error-installing-47-on-raspbian/13663

>dpkg: error processing archive ./hugo_0.47_Linux-ARM.deb (--install):
 package architecture (armel) does not match system (armhf)

In Hugo 0.47 we updated Goreleaser to 0.79 (from something very old, but the config should be more or less the same, see: https://github.com/gohugoio/hugo/commit/20148345aa667bfbf4d76b6fa8349f18f80028c2

Does the above ring any bells, @caarlos0 ?

**Comment by caarlos0** [comment]
hm... maybe a bug on nfpm...

will take a look, sorry about the issue :/

**Comment by caarlos0** [comment]
Yeah, I think the package was arm v6 (goreleaser default), so, on build, we just need to set `goarm` to `7`.

**Comment by caarlos0** [comment]
not sure why this is broken only now though... 6 has been the default since the start as far as I remember

**Comment by caarlos0** [comment]
https://github.com/gohugoio/hugo/pull/5102 should fix it.

Is the idea to build for arm6 as well?

if so, we also need to change the name templates...

**Comment by caarlos0** [comment]
> not sure why this is broken only now though... 6 has been the default since the start as far as I remember

maybe GOARM was set as an external environment variable before? (if so, maybe this is a bug on goreleaser indeed - it shouldn't accept those external environment variables).
