### ISSUE TITLE
Set the Content-Type HTTP header to UTF-8 for the RSS/Atom feed

### ISSUE THREAD

**Issue by camilleroux** [gohugoio/hugo#5103]
I had a problem using the default RSS feed generated by Hugo in Discourse.
There are encoding bug during the the import: https://meta.discourse.org/t/bad-encoding-with-atom-import/95242/

The Discourse team say that 

> the best way to solve the problem is to always serve RSS feeds with a Content-Type HTTP header that contains the correct charset.

**Comment by bep** [comment]
What feed are you talking about?

**Comment by camilleroux** [comment]
this one for exemple: https://www.noschangements.fr/posts/index.xml
