### ISSUE TITLE
Table of Contents always renders when h6 is first used

### ISSUE THREAD

**Issue by Isigiel** [gohugoio/hugo#5104]
It seems that no matter what I do, the ToC is always rendered within the {{ .Content }}. I tried setting toc to false in the front matter, even {{ .TableOfContents }} does not render it again.
I'd be happy if I could just disable this feature for my site.

https://gohugo.io/content-management/toc/

Te docs also are outdated in multiple ways

**Comment by Isigiel** [comment]
Okay, further investigations show, that if the first heading is a h6 this behaviour happens, everything lower behaves as expected

**Comment by bep** [comment]
This is a limitation with the current ToC implementation. This will be reworked and fixed in the near future (re. the Blackfriday 2 update discussed elsewhere)

**Comment by Isigiel** [comment]
Thank you @bep , this is is known issue then.
I will close this @kaushalmodi and open another issue on the docs with the sections that seemed weird to me.
Thank you both for the fast response
