### ISSUE TITLE
Special format content hinders the execution of hugo

### ISSUE THREAD

**Issue by sslyxhz** [gohugoio/hugo#5105]
When I paste some special formatted content into the code box, it looks like 

```
//```textplain
{{< ref "blog/post.md" >}} => https://example.com/blog/post/
{{< ref "post.md#tldr" >}} => https://example.com/blog/post/
#tldr:caffebad
//```
```

Then execute the command 
```shell
hugo --gc    // or other hugo command
```
and shown 
```text
Building sites … ERROR 2018/08/22 23:01:51 REF_NOT_FOUND: Ref "blog/post.md": page not found
ERROR 2018/08/22 23:01:51 REF_NOT_FOUND: Ref "post.md": page not found
```

### version info
- /usr/local/Cellar/hugo/0.47.1

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
