### ISSUE TITLE
Documentation: Empty code blocks

### ISSUE THREAD

**Issue by aerohub** [gohugoio/hugo#5108]
https://gohugo.io/contribute/documentation/#standard-syntax

![image](https://user-images.githubusercontent.com/16353578/44533412-23f59080-a6fe-11e8-919b-e3be93868ecc.png)

**Comment by kaushalmodi** [comment]
@aerohub Thanks for pointing this. I have fixed this, but going forward please open Hugo docs issues in its own repo: https://github.com/gohugoio/hugoDocs/issues.

**Comment by kaushalmodi** [comment]
Also, someone can close this issue now :)
