### ISSUE TITLE
Inconsistent markdown rendering of Summary content

### ISSUE THREAD

**Issue by bcongdon** [gohugoio/hugo#5109]
It seems there is a discrepancy in rendering between when a page's summary is user-defined vs. auto-generated.

When the summary is automatically generated, any markdown is stripped. When the `<!--more-->` separator is used, markdown in the summary is rendered as expected.

Minimal example:

### Using automatic summary

A page with content:
```markdown
**Lorem** ipsum dolor sit `amet`, *consectetur* adipiscing elit.

Duis bibendum lobortis nulla, vel dictum velit. Phasellus scelerisque lacus eleifend turpis sagittis tempor. Phasellus mi tortor, consequat in erat ac, sollicitudin aliquam ipsum. Etiam tortor odio, aliquet in ligula et, euismod pulvinar sapien. Ut ut vehicula nisi. Aenean finibus accumsan rhoncus. Suspendisse potenti. Nunc placerat tellus orci, quis semper mi vestibulum vel.
```

... has its `.Summary` rendered as:

```html
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Duis bibendum lobortis nulla, vel dictum velit. Phasellus scelerisque lacus eleifend turpis sagittis tempor. Phasellus mi tortor, consequat in erat ac, sollicitudin aliquam ipsum.</p>
```

### Using `<!--more-->` summary divider

A page with content:
```markdown
**Lorem** ipsum dolor sit `amet`, *consectetur* adipiscing elit.<!--more-->

Duis bibendum lobortis nulla, vel dictum velit. Phasellus scelerisque lacus eleifend turpis sagittis tempor. Phasellus mi tortor, consequat in erat ac, sollicitudin aliquam ipsum. Etiam tortor odio, aliquet in ligula et, euismod pulvinar sapien. Ut ut vehicula nisi. Aenean finibus accumsan rhoncus. Suspendisse potenti. Nunc placerat tellus orci, quis semper mi vestibulum vel.
```

... has its `.Summary` rendered as:

```html
<p><strong>Lorem</strong> ipsum dolor sit <code>amet</code>, <em>consectetur</em> adipiscing elit.</p>
```

---

Is this intended behavior? My expectation would be that markdown rendering should be done for both the auto-generated and user-defined summaries.

For what it's worth, I tested this on `v0.47.1/extended darwin/amd64`.

If this is indeed a bug, I'd be happy to work on submitting a patch.

**Comment by kaushalmodi** [comment]
That's by design.

See the **Cons** in https://gohugo.io/content-management/summaries/#hugo-defined-automatic-summary-splitting.

**Comment by bcongdon** [comment]
Alright, thanks!
