### ISSUE TITLE
Installation instructions for OpenBSD inaccurate, package does not exist.

### ISSUE THREAD

**Issue by Seep1959** [gohugoio/hugo#5122]
https://gohugo.io/getting-started/installing/
> OpenBSD provides a package for Hugo via pkg_add:
> `doas pkg_add hugo`

The package does not exist in OpenBSD 6.1, 6.2, or 6.3 repos.

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues
