### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nonumeros** [gohugoio/hugo#5140]
Running `hugo serve` with 0.45 and later versions  returned `runtime error: invalid memory address or nil pointer dereference` 

Using https://github.com/istio/istio.github.io as a reference, `hugo serve` works fine but as soon as as any modification occurs it throws the error above

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by nonumeros** [comment]
@bep thanks. The first suggestion is a resounding no.
