### ISSUE TITLE
Consider build a fully static extened binary on Linux/macOS

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5148]
This Netlify issue is taking its time:

https://github.com/netlify/build-image/issues/183

I was reminded of this issue watching this talk:

https://www.youtube.com/watch?v=hWNwI5q01gI

They are not building a static binary because of some parts of the `glibc` that requires dynamic linking. 

We build fully static binaries for Windows, because the common Windows user does not hav `glibc` installed. On Linux and macOS this is common.

On minimal Docker setups (as Netlify) is, this is more common.

I see no technical issues building fully static binaries. That should just work.

My concerns have been:

* Bigger binaries. I suspect it would go from 10 to 50 mb.
* I have also seen security been used as an argument. As a bug in `glibc` could be patched faster when dynamically linked.

I'll leave this open-ended.

**Comment by oncletom** [comment]
One benefit I see of this is to _not have to_ commit the `resources/` — which is the case mostly when content is edited by non-technical people, straight on GitHub/GitLab/etc.

On the other hand, it might not be necessary to build a statically compiled Hugo if there is an easy/easier way to link to `glibc` in environments such as TravisCI or Netlify Builds (they look like good targets in term of what can be done).

What do you think?
