### ISSUE TITLE
Is relLangURL non-plain text?

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#5149]
The following snippet only works when `plainify` is added.

```
{{ $currentPage := . }}
{{ range .Site.Menus.main }}
<a href="{{ .URL | relLangURL }}" class="menu-link{{ if eq $currentPage.URL (.URL | relLangURL | plainify ) }} current{{ end }}">{{ .Name  }}</a>
{{ end }}
```

Is this the intended behaviour?

I did not investigate properly, but probably not only `relLangURL` may be affected.

Thanks!

**Comment by onedrawingperday** [comment]
This the Hugo bugs issue tracker. 

Please ask support questions at https://discourse.gohugo.io

Thanks.

**Comment by Brixy** [comment]
Thank you.

I do not need any support because the solution above is working fine.

Yet, I think the behaviour is unintended and maybe should be corrected (not sure, as stated).

**Comment by Brixy** [comment]
> This is a known behavior and not a bug.

Ok. Thanks for your explanation!
