### ISSUE TITLE
Incorrect instructions for installing from source on website

### ISSUE THREAD

**Issue by eskriett** [gohugoio/hugo#5151]
I was following the [getting started guide](https://gohugo.io/getting-started/installing#source) to installing hugo from source.

I think these instructions are now wrong since the transition to using go modules:

```
$ go get github.com/magefile/mage
$ go get -d github.com/gohugoio/hugo
$ cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
$ mage vendor
Unknown target specified: vendor
```
It looks like [this commit](https://github.com/gohugoio/hugo/commit/fdf3c3b8234ed340f40a85fb76d96ae3a9ccf195#diff-3db01cb68c42f27f6422c65fa1175e23) removed the vendor target.

From what I can tell, the instructions in the [README](https://github.com/gohugoio/hugo/blob/master/README.md) for this repo are correct, so it might be worth [updating the documentation](https://github.com/gohugoio/hugo/blob/master/docs/content/en/getting-started/installing.md#fetch-from-github) that appears on the hugo website to align with the README.

**Comment by felicianotech** [comment]
This issue has been resolved in: https://github.com/gohugoio/hugoDocs/pull/611
