### ISSUE TITLE
Hugo in a docker container?

### ISSUE THREAD

**Issue by amca01** [gohugoio/hugo#5152]
Hello,

I know lots of people have got this working; but, well, I haven't!  Up until recently I worked on my website locally, and when it was all looking good I simply uploaded the lot to my VPS, where it was served up by apache.  However, in an effort to clean up and modularize my server I'm putting all my web apps into docker containers.  So I thought I'd try to do the same with my blog.  

I have the following `Dockerfile`:

    FROM nginx:alpine
    COPY ./whats_this/public /usr/share/nginx/html
    EXPOSE 1313

from which I build an image with

    sudo docker build . -t blog

which I try to serve up to the word with 

    docker run -it -p 1313:1313 -d blog:latest

However, I can't access my site - maybe I'm using the wrong url?  I've tried:

    my.vps.net:1313
    blog.my.vps.net:1313
    blog.my.vps.net

But each returns a "404 Page not found" error.  Anyway, if anybody here has any bright ideas (all they need to be is brighter than my 40watt brain), I'd be delighted!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
