### ISSUE TITLE
Not able to access files from unknown folder

### ISSUE THREAD

**Issue by crishna369** [gohugoio/hugo#5158]
When I am looping through a know folder using .Site.Data.folderName, I am not able to access the inner folder name and files in the inner folder. Can anyone explain me the right way to do this. Below is file folder structure.

apis (Main folder>
 |___api1 (Sub folder)
         ______v1.yaml (File)
         ______v2.yaml (File)
 
 | ___api2 (Sub folder>
          ______v1.yaml (File)
          ______v2.yaml (File)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
