### ISSUE TITLE
Go Version check on compilation

### ISSUE THREAD

**Issue by tfragner** [gohugoio/hugo#5162]
I and others faced some issues regarding the latest builds (0.48+). It seems that during compilation of Hugo there is no check regarding the used version of go. 

The support for variable overwrite is really good, but when Hugo is not compiled with go 1.11 there are issues when this new feature is used. Package maintainer for Hugo may not detect this change and build their own packages with go 1.10. This for example is true for ubuntu 18.04 (dev). 

The point is , I think there should be an error during compilation when the minimum go version requirement is not met.

**Comment by karldw** [comment]
@tfragner, the other thing here is that the go version is specified in the snapcraft.yaml file, but the dev snap version (0.48-DEV) was built from 45c9c45, one commit before the snapcraft file was updated to go 1.11. Do you think hugo should still do a version check, or are the build config files enough?

**Comment by bep** [comment]
There will be valid reasons to build Hugo with something other than Go 1.11, and I think this boils down to: If you build from source, you kind of have to know what you're doing.

**Comment by tfragner** [comment]
I am totally with you. It is a question of responsibility. I personally have no problem with reading the changelogs. But is this also true for a user who trusts into the packages provided by a distro? Also when someone runs into this kind of problem it looks like a template problem in the first place like it is the case for the academic theme.
