### ISSUE TITLE
Search widget

### ISSUE THREAD

**Issue by fabrizziosoares** [gohugoio/hugo#5163]
Hi guys,

I tried the search widget but, even following the examples, I could not make it work.
If I type something it shows me nothing.
If you want to check, it is in http://www.fabrizziosoares.me

Thanks for all

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
