### ISSUE TITLE
Do not FirstUpper Taxonomy titles

### ISSUE THREAD

**Issue by Schnouki** [gohugoio/hugo#5172]
Hi,

I'm trying to use tags that are fully lowercase. But even with `preserveTaxonomyNames`, they are "victims" of `helper.FirstUpper()` in https://github.com/gohugoio/hugo/blob/94d0e79d33994b9a9d26a4d020500acdcc71e58c/hugolib/site.go#L1836.

I'm aware of #1880 and #3070, but this is still annoying for me. Would it be possible to add another option to prevent `helper.FirstUpper()` from being called? `preserveTaxonomyCase` maybe?

**Comment by bep** [comment]
> Would it be possible to add another option to prevent helper.FirstUpper() from being called? preserveTaxonomyCase maybe?

No, there are already too many options. So any fix to this must be "optionless".

**Comment by Schnouki** [comment]
Can't disagree with that. I'll try to find a way to solve this without breaking anything for people who rely on the current behavior.

**Comment by kaushalmodi** [comment]
@Schnouki By taxonomy labels, you mean titles? If so, I agree that Hugo should force FirstUpper. 

A user can do so if they wish in their layouts... (or am I missing something?). 

I think I'll be fine with this FirstUpper removed.

**Comment by onedrawingperday** [comment]
> A user can do so if they wish in their layouts... 

They can.

I agree that this should be removed.

**Comment by kaushalmodi** [comment]
Also, turns out that I haven't set preserveTaxonomyNames, so I'm already enjoying the taxonony titles not getting forced to FirstUpper :). So yeah, removing that makes sense.
