### ISSUE TITLE
Build mage with bootstrap.go

### ISSUE THREAD

**Issue by natefinch** [gohugoio/hugo#5179]
I noticed you're installing mage with `go get`. The problem with this is that it doesn't build in all the -version info.  You don't need mage to build mage, there's a bootstrap file that will let you use `go run` to install mage.

This will download the mage source and install it (if you're using a gopath):
```
go get -d github.com/magefile/mage
go run $GOPATH/src/github.com/magefile/mage/bootstrap.go install
```

If you're using modules, you can do it with good old git clone:

```
git clone git@github.com:magefile/mage
go run ./mage/bootstrap.go install
```

note that in the second case, the binary will be copied to where `go env GOPATH` points.

**Comment by bep** [comment]
>The problem with this is that it doesn't build in all the -version info.

What do you mean by that? Is it a "less functional binary" or is it just cosmetics? (i.e. the output of "mage -version").

I don't care about the **cosmetic version info**. I do, however, care about getting the correct version (the one in my `go.sum` file). My tests show that I now at least get the Mage version that I have specified. Do any of your suggestions add any non-cosmetic improvement to that?

**Comment by natefinch** [comment]
If it were me, I would run `mage -version` after building it to ensure I got the right version (since that has been a problem).   If you don't want to do that, then yeah, there's no difference in the way it's built.
