### ISSUE TITLE
[Feature Request] Support unmarshaling of $.Inner yaml/json/toml string within shortcodes

### ISSUE THREAD

**Issue by dcwangmit01** [gohugoio/hugo#5183]
Within shortcodes, there does not seem to be a way to unmarshal data passed in via $.Inner.

I am aware that data files located in the data directory of the project root are automatically unmarshaled and accessible as a data structure.  However, I would like to keep my data (e.g. code samples) embedded within the markdown text itself, rather than placing the code samples in a different directory.

The current hugo code-toggle [example](https://github.com/gohugoio/hugoDocs/blob/master/themes/gohugoioTheme/layouts/shortcodes/code-toggle.html) follows the pattern where it processes data from `$.Inner`.  However the [`remarshal` function](https://github.com/gohugoio/hugo/blob/master/tpl/transform/remarshal.go#L18) that it uses transforms data from `string (e.g. yaml) -> data-structure -> string (e.g. json)`.  I need an `unmarshal` function that transforms data from `string -> data-structure`, at which point the data-structure is accessible.

Example Markdown
```
{{<my-shortcode>}}
osx:   brew install docker
win10: choco.exe install docker
{{</my-shortcode>}}
```

Example Shortcode: my-shortcode.html
```
{{ $myDict := unmarshal $.Inner }}
or
{{ $myDict := $.Inner | unmarshal "yaml" }}

<div>{{ $myDict.osx }}<div>
```

If there's an existing method of unmarshaling and accessing $.Inner as a data struture, please provide guidance.  If there isn't, and if proposal is reasonable, I'm happy to implement the PR.

**Comment by moorereason** [comment]
Closing in favor of #5428
