### ISSUE TITLE
defining a frontmatter menu causes a fatal error

### ISSUE THREAD

**Issue by absurdhero** [gohugoio/hugo#5184]
Adding a menu item to the frontmatter of a section crashes with a go runtime error:

```
Building sites … ERROR 2018/09/07 18:34:31 unable to process menus for "blog": unable to cast []interface {}{map[string]interface {}{"identifier":"blog", "name":"This is the blog section", "title":"blog section", "url":"/blog/", "weight":-110}} of type []interface {} to map[string]interface{}
Total in 13 ms
Error: Error building site: logged 1 error(s)
```

I created my test case based on the documentation at 
https://gohugo.io/templates/menu-templates/#menu-entries-from-the-page-s-front-matter

To reproduce, create a project with an empty config.toml and the following file under
`content/blog/_index.md`:
```
---
title: blog
menu:
  main:
  - identifier: blog
    name: This is the blog section
    title: blog section
    url: /blog/
    weight: -110
---
```

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by absurdhero** [comment]
I not only read the documentation, I used it as the basis for the test case in the ticket.
A dynamic casting error in hugo is not a question/troubleshooting issue.

**Comment by absurdhero** [comment]
For reference, I've reproduced this bug in `v0.48/extended windows/amd64` and in v0.47.

**Comment by bep** [comment]
>I not only read the documentation, I used it as the basis for the test case in the ticket.

You should double check the documentation.
