### ISSUE TITLE
CSS file not applied locally because of MIME type

### ISSUE THREAD

**Issue by ahnsv** [gohugoio/hugo#5185]
Hi, I've run into this situation couple times in both Windows and MacOS.

The way I could replicate this issue is super simple, I just downloaded hugo binary file(which is windows 64 and macos 64, respectively), added to the path, initialized a new site, added a theme with configuration, and ran it. Basically followed the exact instruction, but... idk

And localhost:1313, I get this 
3(index):1 Refused to apply style from 'http://localhost:1313/css/%25!s%28%3cnil%3e%29-style.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

I assumed it's something to do with my go version, so I updated it and repeated the whole process, but, same. `hugo -d` does not get me anything.

Has anyone run into this kind of issue?

**Comment by ahnsv** [comment]
version is 0.48 windows/amd64 built in 2018.08.29

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
