### ISSUE TITLE
0.48 not released on snap

### ISSUE THREAD

**Issue by james-atkins** [gohugoio/hugo#5186]
The most recent [stable snap version](https://snapcraft.io/hugo) is still 0.47.1.

**Comment by bep** [comment]
We know, and we're working on it. See the release thread on the forum.

**Comment by anthonyfok** [comment]
See:

* https://discourse.gohugo.io/t/hugo-0-48-released/13908/9
* https://forum.snapcraft.io/t/go-plugin-go1-11-fails-if-go-mod-exists-in-the-top-level-directory/7546
