### ISSUE TITLE
Add collections.Append

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5190]
For test and docs, make a note about #5188 and types. Support both one and many.

**Comment by bep** [comment]
Note to self.  With Go 1.11 it would be cool if this just worked:

```
{{ $pages := nil }}
{{ range .Pages }}
  {{ if eq .Title "foo" }}
  {{ $pages = $pages | append  . }}
  {{ end }}
{{ end }}
{{ with $pages }}
{{ range .ByDate }}
{{ end }}
{{ end }}
```

**Comment by regisphilibert** [comment]
Would this work on any slice or just page collections?

**Comment by bep** [comment]
>any slice or just page collections?

Any slice.
