### ISSUE TITLE
Recursively merge configurations

### ISSUE THREAD

**Issue by Shadow53** [gohugoio/hugo#5192]
Configuration files are currently merged by Hugo by looping through the keys of a given map and overwriting the values for those keys in another map. This is not done recursively, which leads to scenarios where themes set a bunch of default configuration options nested in a maps under e.g. `params.foo.bar` with the expectation that a user can override an option at `params.foo.bar.baz` while all of the other defaults remain intact.

Instead, all of the theme settings under `params.foo` are wiped out and replaced with a nearly-empty map containing only `params.foo.bar.baz`.

My theme relies heavily on configurations being applied recursively as in the first paragraph, as it has a plugin system that has settings for the bundled plugins. I currently have to manually namespace all of the theme settings and, in the templates, determine whether a setting is set in the user configuration and use the theme namespaced one otherwise. It would greatly reduce boilerplate in the theme to be able to assume things got merged recursively.

The code for merging the maps should include a check to see if a value matching the key is a `map[string]interface{}` and, if so, recursively merge that map first. Everything else, including slices, should remain copied as-is.

There was a [thread](https://discourse.gohugo.io/t/cannot-access-theme-params/11730/5) on the Hugo forums about this, however I never got a response after I clarified how I expected the merging to work and even provided some code demonstrating it. This issue is a follow-up to that thread.

**Comment by bep** [comment]
>I currently have to manually namespace all of the theme settings and, in the templates, determine whether a setting is set in the user configuration and use the theme namespaced one otherwise. 

There is currently an undocumented feature for params you may want to check out: `params.my_theme.foo.bar.baz`. I have not documented it as I'm not sure about it ...

>The code for merging the maps should include a check to see if a value matching the key is a map[string]interface{} and, if so, recursively merge that map first

I see a lot of issues with lots of "should do".  There are two changes I want to do to `foo`:

1) I want to change a value from `a` to `b`
2) I want to remove key `c`

How would that work with your "merge logic"?

**Comment by Shadow53** [comment]
@bep
> There is currently an undocumented feature for params you may want to check out: params.my_theme.foo.bar.baz . I have not documented it as I'm not sure about it ...

I recall that, and I believe the thread I linked was originally due to me not being able to access the `params.my_theme`. Still, the namespacing I've done has effectively done just that, only in the theme configuration file.

> I see a lot of issues with lots of "should do". There are two changes I want to do to foo :
1. I want to change a value from a to b 
2. I want to remove key c 

> How would that work with your "merge logic"?

By "should", I meant to include "in my opinion". To answer your questions:

1. Unless I am misunderstanding, this would just be the user config overriding the theme config as part of the merge process. I understand this to mean the theme config having `params.foo.bar.baz = a` and the site having `params.foo.bar.baz = b`. Neither a nor b are maps, so b would overwrite a.

2. In my mental model, removing preset keys would break things, i.e. a value must be set and the default value is the one used if another isn't specified. So I wouldn't *want* keys to be deleted, because *a* value needs to be set, and the theme configuration file is better than a literal in multiple template files.

Still, I would imagine a key could be considered "deleted" by set to a value that would return `false` in an `if` or `with` statement: a type's zero value. This would work well with unsetting the keys `foo` and `bar`, which are expected to be maps, since none of their keys would be accessible. Unsetting a non-map value is a bit more difficult since toml (maybe yaml too) doesn't have a `null` value that could be parsed differently from a lack of value.

My actual answer is that, if a key can be unset, it probably doesn't need to be set in the first place except by the site's configuration file. And if a site configuration is overriding another site's configuration, it can undo an option in the first config by setting that key to its default value in the theme or the type's zero value.

As I said before, my use case model for this doesn't allow for keys to be deleted without problems. I recognize this is opinionated, though, and respect if you decide to not make it the default behavior. I would ask to at least have an option for that, though, to make it easier for themes like mine that set a lot of default values that must be set to *something*.

Apologies if something doesn't make sense. I am about to go to sleep and can ramble a bit when I'm tired. If I need to clarify anything, let me know and I will get to it in the morning.

**Comment by Shadow53** [comment]
I just had another thought: I would be satisfied with a template function that somehow allowed me to access the correct value - get from top config, unless is nil, then next, and the one after, until something has that key defined. Something like `getParam "foo.bar.baz"` or `getParam "foo.'b.a.r'.baz"` for a key that is literally `"b.a.r" `.

I still think the configurations should be recursively merged, as that makes the most sense to me (and was the behavior I initially expected), but I would settle for having a function or specially namespaced something that would return the value I want.

**Comment by Shadow53** [comment]
Can we revisit discussion on this? With the addition of Hugo modules, I want to split self-contained features from my theme into different modules, each providing necessary default configuration under `params.shortcodes`, `params.sidebar`, etc. My code iterates through these maps, so there's no way to make hardcoding values work.

Currently, if I'm attempting to load three different sidebar modules, only one has its configuration under `params.sidebar`. This causes errors because the theme can't find the other enabled plugins.

**Comment by bep** [comment]
>Can we revisit discussion on this?

Yes, and I'm sorry if I get distracted by other things at times ...

So, I agree we need to do something about this, see my comment in the PR re. that I don't think we can blindly merge without additional info.

That said, I have been experimenting a little with this on my own with "partitioned namespaces" (I came up with that term right now ....), see

https://github.com/bep/hugo-bulma-hero/blob/fec0fa94fa52e56baa87f714aa781830888d835c/config.toml#L11

>each providing necessary default configuration under params.shortcodes, params.sidebar, 

Your examples illustrate the problem: If module A, B, C have `params.sidebar´ with different number of elements the obvious choice would be to:

* Not doing any merging (how could we?)
* Make the end user copy the entire sidebar if he wants to modify it.
