### ISSUE TITLE
assetDir not working with themes

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#5207]
Hi all!

When using e.g.

`assetDir = "static/assets/"`

in config.toml, theme does not work.

Everything works fine

1. if theme default assets folder is used (`/assets/`) or
2. if theme is moved to project folder.

`assetDir` works for case 2).

Thank you!

**Comment by bep** [comment]
This is as designed. Theme can not configure any of the Hugo folders, e.g. i18, data, content, assets. There is a good reason for this.
