### ISSUE TITLE
The Outlook For Taxes in 2010

### ISSUE THREAD

**Issue by angelinviola** [gohugoio/hugo#5209]
As we celebrate leaving 2009   behind, we necessarily turn towards 2010 and start considering what the   future holds. For instance, what does the year hold on the tax front?     2009 was a unique year when it came to personal finance because of the   unheard of tax relief given to taxpayers. There were obvious government   efforts like the cash for clunkers program to rejuvenate the auto industry   and the first-time homebuyer's tax credit to do the same for housing. Then   there were smaller things like the IRS allowing businesses to retroactively   apply losses for up to five past years to gain big refunds. The goal of all   these programs was to stabilize the economy and help us all survive a brutal   period of time. [Poker Online Terpercaya 2018](https://pokerseri.com)     While the 2009 tax breaks were great, all things come to end in finance.   2010 is the year we will see this happen. Most programs are going to run out   in the first quarter or half of the year and there will be no further   extensions. Why? There simply can't be. The government has tried to spend its   way out of the economic mess, but all indications are we are nearing the   point where borrowing is starting to become difficult. Many Americans are   worried about our soaring national debt and devalued dollar and it now   appears investors may be as well. This will necessarily lead to the   government pulling back on tax incentives.[ Daftar Poker Online Terpercaya 2018 ](https://github.com/angelinviola/poker/issues/1)    The other big tax event that seems primed to be implemented in 2010 is the   internet sales tax. If the federal government has debt problems, nearly a   third of all states are in massive trouble with California and Arizona   leading the way. These states are getting pummeled as property tax revenue   dries up with the housing debacle and are looking for new revenue sources.   Most web businesses do not pay sales tax on their sales, which gives them an   advantage over local brick and mortar shops.     Some states have already started trying to go after online sales tax. New   York famously passed a law allowing for the recovery of it so long as the   online business had a single affiliate sale in the state. Instead of   garnering a tax windfall for the state, large entities like Amazon and   Overstock simply terminated all their affiliates in the state! Still, this is   a battle that will eventually lead to a universal online sales tax being   implemented. Given the big shortfalls faced by many states, 2010 seems to be   the year it comes to a head.     Vice taxes are also possibilities in 2010. Online poker seems peaked for a   return with Barney Frank pushing it in exchange for a tax benefit. Other   states are seriously considering expanded gambling options and even that   funny grass smoked by hippies is on the ballot in some progressive states   like California, Oregon and what have you. Will they pass? My crystal ball is   a bit fuzzy, but it would seem that some will.     2010 is shaping up to be the year the bill comes due for all the efforts   made by state and federal government to deal with the economic collapse.   Practically speaking, that means fewer tax breaks and more incremental taxes   wherever you look.
--

**Comment by onedrawingperday** [comment]
I reported you for your Spam to GitHub.

Hope they delete your account. You bot.
