### ISSUE TITLE
Is Online Poker Legal in the USA?

### ISSUE THREAD

**Issue by angelinviola** [gohugoio/hugo#5210]
Online   poker is one Americas favorite pastimes but with recent developments many   Americans still wonder whether playing poker online is actually legal or not.   I am not an attorney and have no legal background but I have done a lot of   research on this topic and have made my own conclusions. [Daftar Poker Online Terpercaya 2018](https://pokerseri.com)    In 2006, the United States passed the Unlawful Internet Gambling   Enforcement Act or UIGEA. The bill was attached to the Safe Ports Act and was   overwhelmingly passed into law. This was the work of two US Senators whom   wanted to end online gambling in the United States.     The UIGEA has been a controversial law ever since it passing. In short the   law makes it illegal for Banks and other financial institutions to knowing   process payments for the purpose of gambling from United States residents.   The Act excluded lotteries and fantasy sports as well as games of skill.   Initially it was thought that online poker would not be effected by the bill [Daftar Poker Online Terpercaya 2018](https://github.com/gohugoio/hugo/issues/5209)   as many viewed poker as a skill game. Unfortunately, as most poker players   know, the Department of Justice considered poker gambling and enforced the   law with the indictment of the owners of some of the largest online poker   sites that still accepted Americans. Poker sites such as Full Tilt, Poker   Stars, Absolute Poker and Ultimate Bet were the first to fall. Subsequent   online poker rooms would also later be indicted and others decided to leave   the US market.     With all that said, does the UIGEA really make playing online poker   illegal? The simple and short answer is no. The law applies only to the   banking institutions and online poker rooms. Nowhere in the law does it state   that any individual who plays online poker is breaking the law. Nor does it   state that making deposits and withdraws from poker sites are illegal. The   onus is on the banks and poker sites to abide by the law.     So how do some poker sites still accept USA players? Many poker sites take   the stance that because they are licensed and regulated in countries outside   the United States and they do not need to abide by the UIGEA. For this reason   they continue to accept existing and new USA poker players. This is a very   "grey" area of the law but hopefully in the near future we will see   full regulation of online poker in the United States. Some states have   already passed bills allowing online poker within their state borders. With   such progress we hope to see poker regulated at a national level soon.
--

**Comment by onedrawingperday** [comment]
I reported you for your Spam to GitHub.

Hope they delete your account. You bot.
