### ISSUE TITLE
Guide to Online Poker Tells

### ISSUE THREAD

**Issue by angelinviola** [gohugoio/hugo#5217]
Being   able to pick up and utilize poker tells is one of the most important skills   to develop when playing poker no matter what the setting, though in an online   sense, reading specific player poker tells can be a challenging aspect and   one that requires careful thought and consideration. Since being able to pick   up and read physical tells is out of the question looking for other tells   that are still present can be a key skill to develop in the online world and   can include: [Poker Online Terpercaya 2018](https://pokerseri.com)    The Stall     Though this has become less of a focus these days due to the fact that many   experienced players utilize this tactic to give false impressions to their   opponents or may simply be playing multiple games at once and thus increasing   their play time necessary each round to decide their course of action,   careful consideration and observations of a delay in plays can be an   important aspect to watch out for. In particular, look for a player who takes   an exceedingly large amount of time before making a call, as this could   indicate a particularly poor hand that they do not feel confident with. A   long time before a raise could also indicate a stronger hand that they are   deciding what to do with and how to proceed into their next play. Regular   stalls with both outcomes could also indicate that the player is playing a [Situs Idn Poker](https://github.com/gohugoio/hugo/issues/5216)  large number of games at once and therefore may be distracted, and should be   targeted for more aggressive plays that could put the player easily at a   disadvantage.     The Chatbox - Going On Tilt     Watch out for when a player becomes unstable and begins verbally attacking   their opponents or the casino in the chatbox - often referred to as going on   "tilt". This means that the player is no longer thinking clearly   and can easily be antagonized into making stupid moves that they might not   make otherwise if they were thinking logically about the cards they are dealt   and how to proceed. When someone goes on tilt it usually means that they are   a weaker target, while a sudden shift away from aggressive chat could   indicate that they may suddenly have a good hand to watch out for, so be   careful.     The Chatbox - Chat Revoked     Often times, chat privileges can be revoked from players for any number of   reasons, ranging from exceedingly derogatory comments to other racial or   ethnic remarks. Chances are that someone who has had their chat privilege   temporarily revoked is someone who can easily go on tilt, and to test this,   try congratulating other players who have excellent hands that win against   this player to see how the player's in-game plays may change. Often you can   catch someone in a situation where they will easily become off balance and go   on tilt for little to no reason.     The Chatbox - Gloating and Whining     Be mindful of any gloating or whining on a player's part. Gloating after a   player makes a number of big plays means that they may become over-confident   and make poor mistakes later on, while constant whiners may simply be used to   whining and this may not indicate that they will play any poorer than usual.   When a gloater loses big, take advantage of his or her dashed spirits as much   as you can, though if a whiner loses out don't expect any major change in   their plays.
--

**Comment by onedrawingperday** [comment]
I reported you for your Spam to GitHub.

Hope they delete your account. You bot.
