### ISSUE TITLE
MTT Poker Strategy For Beginning Poker Players - The Middle Stages

### ISSUE THREAD

**Issue by angelinviola** [gohugoio/hugo#5218]
During the middle stages of a   multi-table poker tournament (MTT), several factors come into play which   affect your strategy. Firstly, there will be a wide range of stack sizes -   ranging from players who have tripled (or more!) early, through to those nursing   small stacks. Secondly the blinds and antes will be a larger proportion of   the average stack, affecting the odds. Finally, while the average ability of   players will be higher than at the start (more bad players bust out early),   there will still be some inexperienced players who got lucky during the   initial stages - these players may even have big chip-stacks!     When deciding whether to play a hand in the mid-stages of a tournament, you   need to bear in mind that the odds have changed. When you have a deep stack, [Poker Online Terpercaya 2018](https://pokerseri.com)  calling a raise to try to hit a hidden set is a profitable play. However,   since you will only hit the 3rd card one time in eight, and will not always   be paid off fully when you do hit - this play can be expensive in the middle   stages. Ensure you have at least 12 times the size of the raise before   calling - this is required to make up for the times you miss and those times   you end up losing the hand, for example to a flush.     Even if you have the required number of chips, you need to bear in mind   that the smallest stack in play is the one that determines the odds. For   example if the player who raised only has 7 time the size of his bet left   behind you can not profitably 'set mine'. Effective stack sizes also affect   your raises, for example if there is a small stack still to act you might end   up having to call their re-raise (since the pot odds would be so large that   this would be correct with any 2 cards). Scanning the stacks before the hand   ensure you are aware of where each player stands. [Situs Idn Poker](https://github.com/gohugoio/hugo/issues/5217)     There are several 'moves' which can be profitable in the middle stages of   MTTs including a timely 3-bet, squeezing a raiser and caller with a large   re-raise and punishing limpers by pricing them out of making a call. While   these can be very profitable, you will need to choose your opponent   carefully. Those inexperienced players who got lucky early will call your   raise with any 2-suited cards, and may even carry on chasing with bottom pair   on the flop. Play hands for value against these foes, preferably from late   position - save the moves for timid opponents or those experienced enough to   be able to fold hands which can not justify a call.
--

**Comment by onedrawingperday** [comment]
I reported you for your Spam to GitHub.

Hope they delete your account. You bot.
