### ISSUE TITLE
Website down | gohugo.io [We know]

### ISSUE THREAD

**Issue by awittenb** [gohugoio/hugo#5221]
Not getting any DNS response right now from the .io authoritative servers for gohugo.io. Other .io sites seem fine.

EDIT (fixed query to show authority section):
```
> SITE=gohugo.io; for auth in $(dig +noall @l.root-servers.net ${SITE} +auth | awk '{print $5}'); do echo ${auth}; dig +noall @$auth ${SITE} +answer +auth; echo; done

a0.nic.io.
io.			900	IN	SOA	a0.nic.io. noc.afilias-nst.info. 1497455744 10800 3600 2764800 900

a2.nic.io.
io.			900	IN	SOA	a0.nic.io. noc.afilias-nst.info. 1497455743 10800 3600 2764800 900

b0.nic.io.
io.			900	IN	SOA	a0.nic.io. noc.afilias-nst.info. 1497455744 10800 3600 2764800 900

c0.nic.io.
io.			900	IN	SOA	a0.nic.io. noc.afilias-nst.info. 1497455744 10800 3600 2764800 900

ns-a1.io.
io.			900	IN	SOA	a0.nic.io. noc.afilias-nst.info. 1497455743 10800 3600 2764800 900

ns-a3.io.
io.			900	IN	SOA	a0.nic.io. noc.afilias-nst.info. 1497455743 10800 3600 2764800 900

```

Sorry if this is the wrong place for this.

**Comment by h4ckninja** [comment]
Came here because I'm running in to the same issue.

**Comment by nirocfz** [comment]
maybe the owner of domain `gohugo.io` forgot to renew, it's expired.

**Comment by intranets-talk** [comment]
Perfect, works fine - thanks. Hope you guys will sort this out.

**Comment by bluestrike2** [comment]
> you guys can manually edit your `hosts` file and add this record.
> 
> ```
> 104.198.14.52 gohugo.io
> ```
> only a temporary solution.

Any chance @ManassehZhou or someone else happens to know the IP address for discourse.gohugo.io as well? It's not listed on the [SecurityTrails record](https://securitytrails.com/domain/gohugo.io/dns0) for the domain and none of the other DNS history tools I'm aware of support .io TLDs. If not, no big deal.

**Comment by neersighted** [comment]
It appears to correspond to `gohugo.hosted-by-discourse.com`, which resolves to `216.218.240.87`.

    216.218.240.87 discourse.gohugo.io

**Comment by onedrawingperday** [comment]
I confirm the issue. The site (Docs, Themes) is down.

Only @spf13 has control of the domain and it expired on the 16th of September.

Only the Forum works right now.

CC / @bep

**Comment by nirocfz** [comment]
It seems that the domain is still expired.

There's a temporary solution, we can still send dns query to its nameserver `ruth.ns.cloudflare.com`, `andy.ns.cloudflare.com` to get the IP manually, and write hosts file.

```
$ dig gohugo.io @ruth.ns.cloudflare.com +short
104.198.14.52

$ dig themes.gohugo.io @ruth.ns.cloudflare.com +short
gohugo.io.
104.198.14.52

$ dig discourse.gohugo.io @ruth.ns.cloudflare.com +short
gohugo.hosted-by-discourse.com.

$ dig gohugo.hosted-by-discourse.com. +short
216.218.240.87
```

**Comment by bep** [comment]
I'll reopen this as this isn't resolved. But please don't fill this thread with suggestions, we know what the issue and solution is.

**Comment by bep** [comment]
This is now fixed.
