### ISSUE TITLE
[Proposal] Add Theme variables

### ISSUE THREAD

**Issue by stp-ip** [gohugoio/hugo#5224]
We currently have variables around Hugo, Site etc.

For theme developers it would come in handy to generate theme information within the html header or footer more easily to make debugging and usage tracking easier.

Proposing the addition of global `Theme` variables:
```
Theme.Name
Theme.URL
Theme.Description
Theme.License
Theme.LicenseURL
Theme.Author
Theme.AuthorURL
```

In addition a new theme version would be great:
```
Theme.Version
```
For `Theme.Version` a new variable within the theme.toml config file is proposed: `version`

Furthermore the addition of a specific attribution variable would make attribution easier:
```
Theme.Attribution
```
For `Theme.Attribution` a new variable within the theme.toml config file is proposed: `attribution`

If this is something worthwhile, we would consider working on it.

**Comment by bep** [comment]
I'm not a big fan of this proposal, but maybe other will chime in.
