### ISSUE TITLE
Hugo 0.48 binary for Linux ARM reports 0.38 with `hugo version`

### ISSUE THREAD

**Issue by emsenn** [gohugoio/hugo#5227]
Hey y'all - I just downloaded the Hugo 0.48 binary for ARM onto my Chromebook, but when I try `hugo version`, I get told it's version 0.38. Is this an issue with the release, or some sort of user error?

**Comment by kaushalmodi** [comment]
What's the permalink of the binary that you downloaded? I don't have ARM, so I cannot verify it. But with the permalink handy, someone else can.

**Comment by emsenn** [comment]
https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-ARM.tar.gz

**Comment by kaushalmodi** [comment]
@emsenn Curious.. Can you print the full string that `hugo version` prints? I'd like to see the "Build Date" portion too. So just paste the whole thing verbatim.

(I am wondering if you already have an older binary, and the newer hugo binary you donwloaded is not in your PATH. To remove that doubt, cd to the directory you downloaded and extracted `hugo`, and do `./hugo version` (with that `./`).

**Comment by emsenn** [comment]
...I do indeed have an older version of Hugo installed, which is odd because I'm on a new chromebook! Thanks.
