### ISSUE TITLE
Data Archetypes?

### ISSUE THREAD

**Issue by awittenb** [gohugoio/hugo#5231]
Is there any support for generating data file "archetypes" under the `data/` directory? I'm currently using toml files with data templates for generating some pages and being able to run something like `hugo new data mydata.toml` to create a skeleton that can show all of the supported fields would be nice.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

If this is a feature request, I still think you need to start a discussion about it first.
