### ISSUE TITLE
 customize the path of CSS

### ISSUE THREAD

**Issue by liangyuanpeng** [gohugoio/hugo#5232]
hi, i want to customize the path of CSS. have anything help me?

**Comment by onedrawingperday** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  GitHub issues are used only for bugs and enhancements. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
