### ISSUE TITLE
ISO8601 issue with internal template

### ISSUE THREAD

**Issue by akshaybabloo** [gohugoio/hugo#5236]
This might not be much of an issue, but when using the internal template such as OpenGraph the datetime's offset `+` or `-` is not shown. Example

```
date: 2018-09-20T16:37:20+12:00
```
is shown as 
```
<meta property="og:updated_time" content="2018-09-20T16:37:20&#43;12:00"/>
```
Instead of
```
<meta property="og:updated_time" content="2018-09-20T16:37:20+12:00"/>
```

I am using Hugo v0.48/extended windows/amd64.

**Comment by bep** [comment]
How is this a problem?

**Comment by rdwatters** [comment]
@akshaybabloo. 

FYI, the escaped HTML for `+` wasn't an issue when I tested it locally using [Facebook's OGP's debugger](https://developers.facebook.com/tools/debug/sharing/). It still converted to UNIX time effectively.

**Comment by felicianotech** [comment]
Hey. This is an issue because `safeHTMLAttr` shouldn't escape "+"s but it is. I see two components here:

1. The line in Hugo doing this is using `safeHTML` when it should probably be using `safeHTMLAttr`.
2. + shouldn't be escaped. This isn't a Hugo issue though as I have tracked it to the `html/template` Go package. I'm investigating if I can do a PR upstream if I understand it well enough.

**Comment by akshaybabloo** [comment]
This did not fix the issue. I still get 

```html
<meta property="og:updated_time" content="2018-09-20T16:37:20&#43;12:00"/>
```

**Comment by akshaybabloo** [comment]
@felicianotech It's not working for me still.

**Comment by felicianotech** [comment]
@akshaybabloo It's not going to until the upstream PR that I linked is merged and a new Hugo release based on that new Go version is released as well.

**Comment by Rarst** [comment]
I've noticed that schema template is still escaping the plus and not using `safeHTMLAttr`:

https://github.com/gohugoio/hugo/blob/c3d433af56071d42aeb3f85854bd30db64ed70b8/tpl/tplimpl/embedded/templates/schema.html#L5-L6

Might have been missed?
