### ISSUE TITLE
Found two local full-text search,Can it be integrated in hugo?

### ISSUE THREAD

**Issue by jerry011235** [gohugoio/hugo#5238]
1. [jekyll local full-text search](https://github.com/Simpleyyt/jekyll-theme-next/search?utf8=%E2%9C%93&q=local_search&type=)
demo: https://simpleyyt.com/jekyll-theme-next/ ,search "is" for example.

2. [ink local full-text search](https://github.com/InkProject/ink)
InkPaper is an static blog generator developed **also by Golang**.
demo: http://www.chole.io/blog/ ,search "InkPaper" for example.

If they can be integrated into hugo，that‘s awesome！
thank you！

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
