### ISSUE TITLE
consistency: hugo new site uses config.toml, but YAML for content

### ISSUE THREAD

**Issue by mariusa** [gohugoio/hugo#5241]
```
hugo new site test
```
config.toml uses TOML format:
```
title = "My New Hugo Site"
```

but archetypes/default.md uses YAML
```
---
title: "{{ replace .Name "-" " " | title }}"
---
```

Please change the default to TOML equivalent, to be consistent. Or, make them both YAML.

**Comment by bep** [comment]
The reason is GitHub's support for YAML front matter. If they would support TOML front matter, we would change. But they don't.

**Comment by mariusa** [comment]
Not sure if you read it by the end.
Please avoid confusion for new users and make them both YAML, in this case.
One should be able to copy
```
title = "My New Hugo Site"
```
from one place to another and have it working.

**Comment by rawtaz** [comment]
@mariusa actually has a point. If we can't move to TOML in a very large part of the contents for sites, then it would be more consistent to keep YAML for the config as well. Why not do that?
