### ISSUE TITLE
Update to go-i18n v2

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5242]

**Comment by QuLogic** [comment]
The final (i.e., non-beta) release appears to be out now.

**Comment by bep** [comment]
There is still an in-progress performance PR in go-i18n that we need.

**Comment by QuLogic** [comment]
For cross-reference, I believe that's https://github.com/nicksnyder/go-i18n/issues/182 and https://github.com/nicksnyder/go-i18n/pull/189.

**Comment by artch** [comment]
What is the ETA on this? We're planning a new project based on Hugo, and would like to use [the new plain format](https://github.com/nicksnyder/go-i18n/issues/85) supported in go-i18n v2, so any timeline would be appreciated.

**Comment by bep** [comment]
You need to ask this question a go-i18n.

**Comment by nicksnyder** [comment]
This performance improvement is now released in go-i18n v2.0.4.

Sorry for the delay here, life is busy :)

**Comment by bep** [comment]
>Sorry for the delay here, life is busy :)

That I know. Thanks.
