### ISSUE TITLE
Update the toml dependency to v0.3.1

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#5244]
Ref: https://github.com/BurntSushi/toml/issues/232

Please gate the work in progress i18n PR until the next toml release because as of today that PR downgrades the toml package and reintroduces a bug that was fixed there: https://github.com/gohugoio/hugo/pull/5243#commitcomment-30595584

**Comment by kaushalmodi** [comment]
@bep Heh, that was quick! I pinged on that toml repo issue and a new release tag was added: **0.3.1**.. please update that WIP PR accordingly.

**Comment by bep** [comment]
In general, I'm watching this closely **before I merge any PR**. And it would be better if you comment on the PR and avoid creating more issues.
