### ISSUE TITLE
Embed an iframe in a blog

### ISSUE THREAD

**Issue by bluprince13** [gohugoio/hugo#5248]
Is there a way to embed an iframe in a blog? When it's for use on a single blog post, there is no point creating a short code for it. Is it possible to embed it directly into the post somehow?

**Comment by onedrawingperday** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/). GitHub issues are used only for bugs and enhancements. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
