### ISSUE TITLE
Add alias to strings.firstUpper (and potentially other `.strings`)

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/hugo#5251]
`strings.FirstUpper` is great in that it adds sentence casing to the list of uppercase, lowercase, and title case.

I was going to submit a PR to add a page for `strings.FirstUpper` to the Functions section of the Hugo docs when I noticed that it needs the following usage:

```
{{$mystring := "how now brown cow"}}
<span>{{$mystring | strings.FirstUpper }}</span>
```

For the sake of consistency, can an alias be added to `strings.FirstUpper` and potentially to the other `strings` methods? With pipes, this feels much cleaner, and within the context of the documents, the `.strings` methods seems out of place . 

E.g.

```
{{ $mystring | upper }}
{{ $mystring | lower }}
{{ $mystring | title }}
{{ $mystring | firstUpper }}
{{ $mystring | trimSuffix "h" }}
{{ $mystring | slicestr 4 }} (so I guess this is a bit inconsistent w/r/t casing, so maybe not the best example....)
etc...
```

**Comment by bep** [comment]
We added namespace to avoid the global namespace. We only add aliases for "core functions" (the new `append` fits nicely into that). String functions is not "core function".

**Comment by rdwatters** [comment]
I see. Thank you for the quick feedback, @bep. My suggestion was more for consistency and end-user ease of use. Are the other aliases I mentioned all part of core functionality?

Nevertheless, this is a cool addition. I’ll try to submit a docs PR tonight. Thanks!

**Comment by bep** [comment]
I and @moorereason spent a significant amount of time refactoring all the template functions into namespaces. It wasn't practical to remove any aliases (that would have been too much work). So the "only aliases for core functions" would only work for "future additions".

I created an issue in the docs repo about refactoring the /funcs section to be in line with the new namespaces (nested sections?). I even created this docs JSON to help with that:

https://github.com/gohugoio/hugoDocs/blob/master/data/docs.json

But I didn't get much response to that. So, anyone wants to improve **consistency in this department should work on the documentation, not adding more aliases.**
