### ISSUE TITLE
need to exclude <script> internals from "word count"?

### ISSUE THREAD

**Issue by DataStrategist** [gohugoio/hugo#5257]
Hi, I'm coming from blogdown, where I opened the following ticket https://github.com/rstudio/blogdown/issues/334. Basically, if I have an htmlwidget in a blogdown article that depends on Hugo, the resulting html file will contain at least one fairly large script... so much so that for example this short article: https://www.amitkohli.com/2018/09/23/2018-07-07-crime-statistics-in-london/ looks like it would take 2 hours to read! :)

Could it be possible to throw away everything between `<script>` tags for the word count?

Thanks!

**Comment by liwde** [comment]
This seems to be related to https://github.com/gohugoio/hugo/issues/3235: `plainify` does not remove the content of `script` and `style` tags as well. The workaround provided there unfortunately doesn't help with the WordCount and ReadingTime...
