### ISSUE TITLE
Build takes up too much memory

### ISSUE THREAD

**Issue by MSG-maniac** [gohugoio/hugo#5262]
I have about 50,000 markdown files, which take up 12GB of memory when building.

**Comment by onedrawingperday** [comment]
This support question belongs to the [Hugo Discussion Forum](https://discourse.gohugo.io/). 

GitHub issues are used only for bugs and enhancements. 

Thank you.

**Comment by gedw99** [comment]
@onedrawingperday How can this be support ! Its an architecture issue that i also hit with hugo.

Nothing to do with usage but a fundamental architectural issue that should be discussed.
