### ISSUE TITLE
Help: how to rename a non-html taxonomy?

### ISSUE THREAD

**Issue by igr** [gohugoio/hugo#5265]
I have a taxonomy layout `/layouts/talks/taxonomy.html` for HTML pages: it's a list of talks. I have enabled custom output, calendar and have a `/layouts/talks/taxonomy.ics` template for ICS files. It is rendered as: `/talks/talk-name/index.ics`.

Is there a way to rename a slug for the custom output file? I want to name it as `event.ics`?

https://github.com/HeapSpace/heapcon2018/tree/master/layouts/talks

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
