### ISSUE TITLE
`hugo server` shows the cached stale results

### ISSUE THREAD

**Issue by rootkea** [gohugoio/hugo#5266]
$ hugo version  
    Hugo Static Site Generator v0.49 linux/amd64 BuildDate: 2018-09-24T10:03:17Z

Steps to reproduce:
1. `hugo new posts/foo.md`
2. `hugo server -D`
3. Browse `localhost:1313/posts/foo` - All OK!
4. Now, add `slug: "bar"` to `foo.md` front matter
5. Browse `localhost:1313/posts/bar` - All OK!

But, now the file `foo.md` is being served on two URLS! `localhost:1313/posts/foo` and `localhost:1313/posts/bar`

6. Now remove `slug: "bar"` from foo.md

Go to `localhost:1313/posts/bar` and confirm that the file is still being served there which shouldn't have happened.

PS - After every change I cleared Firefox cookies and cache. It seems that the only way to get the fresh latest change is to stop existing `hugo server -D` and launch a fresh one.

**Comment by bep** [comment]
This is a limitation with the current design. Is this a real problem?

**Comment by rootkea** [comment]
Ah, it just means I can't really rely on `hugo server` to see the latest changes. Or may be I should make a habit of restarting `hugo server` after couple of changes...

**Comment by bep** [comment]
That’s not accurate. You’re talking about old files after renames, which in most cases should be invisible unless you look for it.

**Comment by bep** [comment]
>The only issue is, I am not really sure if this (cached old file) gets leaked into other pages via functions (.GetPage etc.) or not. (n00b here!)

That does not happen.  But you should also look at the `--disableFastRender` flag.
