### ISSUE TITLE
Invalid memory address when using .CurrentSection

### ISSUE THREAD

**Issue by auburus** [gohugoio/hugo#5268]
Hi, just leaving this here because it has taken me a while to pinpoint the exact error, so just in case one of the maintainers finds this report useful.

##### How to reproduce
Create a new site with hugo `hugo new site example`. Create a file in `layouts/_default/list.html` with the following contents:

```
<p>Go to the current section <a href="{{ .CurrentSection.Permalink }}">{{.Section}}</a></p>
```
run `hugo` or `hugo server` or `hugo -D`.

In a debian 8, with the last release `Hugo Static Site Generator v0.49 linux/amd64 BuildDate: 2018-09-24T10:03:17Z`, this is the output:

```
Building sites … ERROR 2018/09/30 22:56:44 Failed to render "_default/list.html": runtime error: invalid memory address or nil pointer dereference
ERROR 2018/09/30 22:56:44 Stack Trace:
goroutine 30 [running]:
github.com/gohugoio/hugo/hugolib.stackTrace(0x4b0, 0xf4ce4b, 0x17)
	/root/project/hugo/hugolib/page.go:285 +0x76
github.com/gohugoio/hugo/hugolib.(*Site).renderForLayouts.func1(0xc0006c97d0, 0xc00046c000)
	/root/project/hugo/hugolib/site.go:1741 +0x135
panic(0xe1aee0, 0x183cf30)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
text/template.errRecover(0xc0006c96c0)
	/usr/local/go/src/text/template/exec.go:160 +0x1d0
panic(0xe1aee0, 0x183cf30)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/gohugoio/hugo/hugolib.(*Page).Permalink(0x0, 0x0, 0x0)
	/root/project/hugo/hugolib/page.go:1164 +0x5
reflect.Value.call(0xef8920, 0xc000634898, 0xd293, 0xefe7f0, 0x4, 0x187ee60, 0x0, 0x0, 0xef3060, 0x1, ...)
	/usr/local/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0xef8920, 0xc000634898, 0xd293, 0x187ee60, 0x0, 0x0, 0xc0005f8960, 0x1, 0x1)
	/usr/local/go/src/reflect/value.go:308 +0xa4
text/template.(*state).evalCall(0xc0006c9640, 0xefade0, 0xc00014e780, 0x16, 0xef8920, 0xc000634898, 0xd293, 0x1140040, 0xc0006b3860, 0xc000365550, ...)
	/usr/local/go/src/text/template/exec.go:695 +0x6bd
text/template.(*state).evalField(0xc000423640, 0xefade0, 0xc00014e780, 0
```

##### Expected output
Since there is no content, I would expect hugo to not generate anything

##### Dirty fix
Move the `list.html` file into a concrete folder. For instance, if you want to generate a list for your `content/posts/*` files, place this layout into `layouts/posts/list.html`.

I don't know if this is considered a bug or not, but just in case I hope there is enough information here for you to make the decision.

PD: Also, thanks for developing this amazing content generator, I'm really really happy after using it for over 6 months, and my personal website now runs on it :blush:

**Comment by bep** [comment]
Reading the docs:

https://godoc.org/github.com/gohugoio/hugo/hugolib#Page.CurrentSection
This is probably as designed. `CurrentSection` can return nil (for taxonomy type of pages), so if you use it in `list.html` for all list types, you should wrap it with a `with`

**Comment by auburus** [comment]
Oh, the `with` is so clever, thank you for that!

Also, I know that the code is wrong, my concern was more in the terms of having a "friendly" error message like other hugo errors, or if having this error is the expected way.
