### ISSUE TITLE
Extra <p> tags inside lists after code block

### ISSUE THREAD

**Issue by magic-lantern** [gohugoio/hugo#5291]
I'm using 

```bash
$hugo version
Hugo Static Site Generator v0.49/extended darwin/amd64 BuildDate: unknown
```

I have the following example markdown:

```markdown
1. First item.
1. Second item:
    
    ```r
    library(util)
    #some code
    myvar <- c(1, 2, 3, 4)
    ```
    
1. Third item.
1. Fourth item.

* First item.
* Second item:
    
    ```r
    library(util)
    #some code
    myvar <- c(1, 2, 3, 4)
    ```
    
* Third item.
* Fourth item.
```

For the rendered html, list items (`<li>`) before the code block are rendered as `<li>text</li>` whereas list items after the code block are rendered as `<li><p>text</p></li>` This different rendering occurs for both ordered and un-ordered lists.

I expect that all list items are rendered the same regardless of location before or after a code block.

Is this expected behavior? Is there a configuration flag that affects this behavior? Perhaps this is a bug/feature in Blackfriday?

**Comment by aignas** [comment]
@magic-lantern, do you think that https://github.com/russross/blackfriday/pull/521 fixes your issue?

**Comment by magic-lantern** [comment]
Sorry for the delay in getting to this issue. Thanks for pointing out that issue. Looks like  russross/blackfriday#521 references 2 separate issues. russross/blackfriday#485 and russross/blackfriday#495 are different problem than what I am experiencing.

Since I reported this issue, there has been a change in behavior though - not sure if it was due to the bug you mentioned or a different one. I'm now on version:

```
$ hugo version
Hugo Static Site Generator v0.54.0/extended darwin/amd64 BuildDate: unknown
```

Now it seems that list items that include a code block or are the last item in the list are wrapped in a `<p></p>` tag - see html output:

```html
<ol style="list-style-type: decimal">
<li>First item.</li>
<li><p>Second item:</p>
<pre class="r"><code>library(util)
#some code
myvar &lt;- c(1, 2, 3, 4)</code></pre></li>
<li>Third item.</li>
<li><p>Fourth item.</p></li>
</ol>
<ul>
<li>First item.</li>
<li><p>Second item:</p>
<pre class="r"><code>library(util)
#some code
myvar &lt;- c(1, 2, 3, 4)</code></pre></li>
<li>Third item.</li>
<li><p>Fourth item.</p></li>
</ul>
```

Since the behavior now seems more consistent, I think this bug can be closed.

**Comment by user501254** [comment]
@magic-lantern , @aignas 
For me, this still leads to some inconsistent results. Please have a look at the new issue linked above.
