### ISSUE TITLE
Yet another question about adding a new single page to hugo site

### ISSUE THREAD

**Issue by winston-magemojo** [gohugoio/hugo#5292]
Hi, 

I am running version 0.49 (and have experienced this issue with 0.48 too)

I am trying to create a new single page on my hugo site eg: https://www.domain.com/features

I do 

```
hugo new features.md
```
which outputs
```
/frontend/content/features.md created
```
I add the type to this newly created page which now looks like
```
---
title: "Features"
date: 2018-10-07T11:01:10+02:00
draft: true
type: page
---
Content goes here
```
I am using the hugo-fresh theme, which does not have a single page, so I add the template which is located here

```
layouts
├── _default
│   └── single.html
```
Navigating to https://www.domain.com/features gives me

404 page not found

Not sure what I am missing - could you please point me in the right direction

Thanks!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
