### ISSUE TITLE
Add readThemeFile to enable reading data from theme directory

### ISSUE THREAD

**Issue by stp-ip** [gohugoio/hugo#5294]
Some themes might provide data to be injected into layouts.
In a specific case, we are generating a bare-bones layout css file, which will be inlined into the html head.
Currently this is done using readFile, which leads to the problem that the user needs to handle this file.

We would contribute this, if we get a green light.

**Comment by stp-ip** [comment]
This is related to #4842
readThemeFile would cleanly separate user and theme space. #4842 on the other hand would make it easier for the user to overwrite any files.

Happy with both solutions, we should just make a decision and then we can contribute the change.

**Comment by bep** [comment]
There are plenty of ways for a theme to provide data etc. to the project. For the particular use case above, you should look into the `resources` funcs.

**Comment by stp-ip** [comment]
@mpourismaiel could you elaborate on the issues with using resources for this?
