### ISSUE TITLE
Fingerprinting and SRI ordering issue

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#5296]
It seems that to generate the SHA value for an inline script we need to wrap it within a `{{ if  $secureJS.Content }}{{ end }}` before accessing the integrity.

Also see related Forum topic: https://discourse.gohugo.io/t/generate-inline-script-sha-for-content-security-policy/14627

**Comment by bep** [comment]
I will fix this, but note that in the original problem case, adding MIME type to the script would also work:

```html
<script type="{{ $secureJS.MediaType }}" integrity="{{ $secureJS.Data.Integrity }}">{{ $secureJS.Content | safeJS }}</script>
```
