### ISSUE TITLE
cannot install hugo

### ISSUE THREAD

**Issue by if1live** [gohugoio/hugo#5298]
## problem
cannot install hugo

```
$ go get -u github.com/gohugoio/hugo
# github.com/gohugoio/hugo/hugolib
../../gohugoio/hugo/hugolib/hugo_sites.go:72:18: h.Deps.Log.LogCountForLevelsGreaterThanorEqualTo undefined (type *jwalterweatherman.Notepad has no field or method LogCountForLevelsGreaterThanorEqualTo)
../../gohugoio/hugo/hugolib/hugo_sites.go:304:7: h.Deps.Log.ResetLogCounters undefined (type *jwalterweatherman.Notepad has no field or method ResetLogCounters)
../../gohugoio/hugo/hugolib/hugo_sites_build.go:82:21: h.Deps.Log.LogCountForLevel undefined (type *jwalterweatherman.Notepad has no field or method LogCountForLevel)
```

## reason

1. hugo use [github.com/spf13/jwalterweatherman](http://github.com/spf13/jwalterweatherman)
2. hugo use jwalterweatherman's some function
	* LogCountForLevelsGreaterThanorEqualTo()
	* ResetLogCounters()
	* LogCountForLevel()
3. In jwalterweatherman, those functions are removed
https://github.com/spf13/jwalterweatherman/commit/103a6da826d08544f49833dabd4f1cdf8a1038bb#diff-924c0de5ca4574327cfeb621d285053aL100

duplicated #5297

**Comment by bep** [comment]
You need to look into how Go Modules and versioning work.

**Comment by if1live** [comment]
oops. sorry.
I have used hugo for several years.
I did not intend to look for a new installation guide.
it's my fault.
