### ISSUE TITLE
defaultContentLanguageInSubdir=true does not generate subdirectory if there is only one language enabled

### ISSUE THREAD

**Issue by zimmski** [gohugoio/hugo#5299]
With the following configuration (stolen from the Hugo documentation) subdirectories for "en" and "fr" are generated. When I enable "disableLanguages" so that there is only "en" left as a language, no subdirectory for "en" is generated with Hugo v0.49. However, according to the documentation it should be because "en" is marked as the default language.

```
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
#disableLanguages = ["fr"]

[languages]
  [languages.en]
    title = "My blog"
    weight = 1
    [languages.en.params]
      linkedin = "https://linkedin.com/whoever"
  [languages.fr]
    title = "Mon blogue"
    weight = 2
    [languages.fr.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.fr.params.navigation]
        help = "Aide"
```

**Comment by sjgith** [comment]
The same issue occured with v0.51. Is there any solution available. Thanks.
