### ISSUE TITLE
Fedora package outdated.

### ISSUE THREAD

**Issue by c-edw** [gohugoio/hugo#5301]
Hugo is quite outdated in the [Fedora package repository](https://apps.fedoraproject.org/packages/hugo). Is there anybody who might be willing to contact the maintainer and take over responsibility?

**Comment by zwbetz-gh** [comment]
@c-edw While this doesn't address your original question, since you want to use a package manager to install/manage hugo, is using snap an option for you? Snap also includes latest hugo dev versions. 

https://snapcraft.io/hugo

**Comment by c-edw** [comment]
Personally I don't use Snaps, but thank you for making me aware that it's available. I have installed Hugo manually for now. Though, the Hugo installation is so simple that maybe it's not worth chasing after package maintainers. An autoupdate or update notice functionality in Hugo would make it acceptable to not provide distribution packages, in my opinion.

**Comment by bep** [comment]
I think, given the manpower we got, I will close this. Opening up a thread on https://discourse.gohugo.io/ may be a better road to take.
