### ISSUE TITLE
Support numeric sort in ByParam

### ISSUE THREAD

**Issue by smiileTeam** [gohugoio/hugo#5305]
https://github.com/gohugoio/hugo/blob/f1a00b2069ede85feb487d29b9f690396e2402c6/hugolib/pageSort.go#L295

On this method, each value is cast to string so a compare beetwen (int) 9 and (int) 12 gives us 9 result first (instead of 12).
We would love to:
 - have an option to specify we want an order on ints
or
 - have a new method ByIntParam which would do it 
or
 - maybe something that detect both v1 & v2 are ints and compare them without casting

**Comment by bep** [comment]
>maybe something that detect both v1 & v2 are ints and compare them without casting

I suggest we do a variant of the above.

* The different decoders (JSON, TOML, YAML) treats numbers differently, so an int may be `int`, `int64` and I think even `float64`
* If you in one page say `myparam = 2` and in another say `myparam = 2.2`, I think most people expect them to be compared as numbers (2 comes before 2.2)

With that, I suggest that: **If both are numbers, convert both to float64 and compare them.**
