### ISSUE TITLE
go get -v github.com/spf13/hugo - Build Always Fails in Travis

### ISSUE THREAD

**Issue by cloudpayload** [gohugoio/hugo#5308]
The command ""go get -v github.com/spf13/hugo" failed and exited with 2 during .

Travis .yml File: 

language: go
install:
go get -v github.com/spf13/hugo
script:
- hugo version
- make deploy
branches:
  only:
  - master

#####
Logs

**Comment by moorereason** [comment]
Hugo uses Travis to build Hugo, and it works fine.

Hugo master requires Go 1.11+ and uses [Go modules](https://github.com/golang/go/wiki/Modules).  If you have more questions, please use the [Discussion Forums](https://discourse.gohugo.io/).

**Comment by StephenBrown2** [comment]
For reference, hugo's travis file: https://github.com/gohugoio/hugo/blob/master/.travis.yml

**Comment by onedrawingperday** [comment]
Please have a look over here: https://discourse.gohugo.io/t/the-command-go-get-v-github-com-spf13-hugo-failed-and-exited-with-2-during/14601
