### ISSUE TITLE
Add relative aliases

### ISSUE THREAD

**Issue by mjibson** [gohugoio/hugo#5314]
Jekyll has a nice feature in its `redirect_from` front matter (similar to hugo's aliases): if it doesn't start with a `/`, it's a relative URL, otherwise it's absolute. Hugo appears to treat everything as absolute. Being able to use relative aliases is useful because it makes it easy to copy files around in a large hugo project and not have to worry about overlapping aliases.

I'd like to propose that aliases beginning with `./` are relative to the `.URL` of a page. This should allow for backward compat (assuming that very few users have any aliases starting with `./`), and is also pretty clear what it means.

Maybe some weeds to deal with here with index pages, but using this issue as a discussion point.

**Comment by bep** [comment]
This was fixed in 0.55.
