### ISSUE TITLE
Upgrade 'Error: Unable to locate Config file' message

### ISSUE THREAD

**Issue by marekkowalczyk** [gohugoio/hugo#5315]
Consider modifying the error message **‘Error: Unable to locate Config file. Perhaps you need to create a new site. Run hugo help new for details.’** issued in [this usecase](https://discourse.gohugo.io/t/hugo-new-test-md-throws-unable-to-locate-config/14708?u=marekkowalczyk) to include the suggestion: **ou need to call hugo new test.md from the root of the project.**. 

HT [pointyfar](https://discourse.gohugo.io/u/pointyfar/summary).

**Comment by moorereason** [comment]
Fixed by #5317
