### ISSUE TITLE
Issue with directory-based archetypes in theme

### ISSUE THREAD

**Issue by gcushen** [gohugoio/hugo#5318]
I have followed the instructions in the limited documentation on the new dir-based archetypes in order to support it in the Academic theme, however am receiving the error:

**Error: stat WEBSITE_FOLDER/themes/academic/archetypes/archetypes/publication/index.md: no such file or directory**

when running the following command from WEBSITE_FOLDER with Hugo v0.49/extended darwin/amd64:

    hugo new --kind post post/XYZ

For some reason Hugo is looking for `archetypes/archetypes/` instead of simply `archetypes/`. 

The code can be found here: https://github.com/gcushen/hugo-academic/tree/master/archetypes/post

Any ideas?

Thanks!

**Comment by bep** [comment]
I suspect this to be a "theme issue" -- I assume if you put the archetype dir in the project.
