### ISSUE TITLE
error calling slicestr: end argument must be integer

### ISSUE THREAD

**Issue by robsonsobral** [gohugoio/hugo#5326]
Starting with version 0.49, `slicestr` returns an error.

```
    {{ if gt (len .) 150 }}
      <meta name="description" content="{{ . | slicestr 0 150 }}">
    {{ else }}
      <meta name="description" content="{{ . }}">
    {{ end }}
```

Tested with and without diacritics on Windows running versions 0.49 and 0.49.2.

`{{ slicestr . 0 150 }}` works fine.

**Comment by bep** [comment]
I suspect `truncate` would fit your use case better.

**Comment by moorereason** [comment]
@robsonsobral, are you sure?  `slicestr` hasn't changed in a long time (March 2017).  Usage is `slicestr STRING START [END]`.  The pipe usage is putting the string as the last element.

**Comment by robsonsobral** [comment]
@moorereason , I always used the notation with `|` at the beginning. Maybe the change is there.

@bep , thank you for your suggestion!

**Comment by robsonsobral** [comment]
Wow! I already updated hugo on both my computers. I gonna take a look at Netlify settings.
