### ISSUE TITLE
Method invoke in templates panics if the receiver is nil

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5327]
https://github.com/golang/go/issues/28242

**Comment by kaushalmodi** [comment]
Yes fix would be very welcome: https://github.com/gohugoio/hugo/issues/4710.

**Comment by bep** [comment]
This is now merged and fixed upstream.

**Comment by moskomule** [comment]
I got the same error at the same file `.../layouts/_default/single.html:1:1`.

**Comment by moskomule** [comment]
I got the same error at the same file `.../layouts/_default/single.html:1:1`, though I just of ~30 articles.

**Comment by anagio** [comment]
Is there an earlier version of hugo which isn't affected by this bug if so which?

**Comment by hanzei** [comment]
@bep can this be closed?
