### ISSUE TITLE
Check if related.Document is present in a Page

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#5328]
Currently there is no way to detect whether a Page contains Related Content.

I came across this because I needed to make a check for Pages that didn't have Related Content.

See related forum topic: https://discourse.gohugo.io/t/how-to-check-if-a-page-is-part-of-related-content/14735

**Comment by bep** [comment]
Not sure I follow ...

```bash
{{ $related := .Site.RegularPages.Related }}
{{ with $related }}
Yes, the page has {{ len . }} related pages.
{{ end }}
```

**Comment by onedrawingperday** [comment]
I need to check for the pages that have zero Related Content.

For example:
```
{{ $related := .Site.RegularPages.Related . }}
                {{ with $related }} or {{ if $related }}
               <--- Pages with Related Documents --->
{{ else }}
<--- Pages without Related Documents --->
{{ end }}
```

**Comment by bep** [comment]
I assume this will work:

```
{{ $related := .Site.RegularPages.Related }}
{{ if not $related }}
Sadly, this page has no related content.
{{ end }}
````

Or:

```
{{ $related := .Site.RegularPages.Related }}
{{ if eq (len $related) 0 }}
Sadly, this page has no related content.
{{ end }}
```

**Comment by onedrawingperday** [comment]
Unfortunately for some reason the above does not work.

There are more tests with `bool`, `lt`, `len` etc in the Forum topic I linked to above.

I've thrown everything I know at making this condition but it is ignored.

If you want I could upload a Test Repo for you to see.

**Comment by bep** [comment]
I'm pretty sure it works. I think you need to complete this trouble shooting on the forum. If the conclusion is there that this is a bug (which I find very odd), we can recreate an issue here.

**Comment by onedrawingperday** [comment]
I tested further and you're right. I had missed something in the front matter of a content file.

Sorry for the noise.
