### ISSUE TITLE
Folder based archetypes in themes broken

### ISSUE THREAD

**Issue by paulkoppen** [gohugoio/hugo#5334]
Following the [Directories based archetypes](https://gohugo.io/content-management/archetypes/#directory-based-archetypes) tutorial, this only works if the folder `page-bundle` is in the site's `archetypes` folder, and does not work if it is in the theme's `archetypes` folder:

With `mysite/archetypes/page-bundle`:
```
> hugo new tags/invited-talks --kind page-bundle
...mysite/content/tags/invited-talks created
```

With `mysite/themes/mytheme/archetypes/page-bundle`:
```
> hugo new tags/invited-talks --kind page-bundle
Error: FindFirstFile ...mysite/themes/mytheme/archetypes/archetypes/page-bundle/index.md: The system cannot find the path specified.
```

It is mistakenly doubling the `archetypes` folder name. Hugo version `Hugo Static Site Generator v0.49.2/extended windows/amd64 BuildDate: unknown`

(Tangentially, why must the folder name end in "-bundle"? Is the flag `--kind` not enough?)

**Comment by bep** [comment]
#5318
