### ISSUE TITLE
Date parsing does not conform to all valid RFC3339 forms

### ISSUE THREAD

**Issue by raehik** [gohugoio/hugo#5340]
I insert dates in my content files using a Vim shortcut, which formats them like this:

    date: 2006-01-02T15:04:05-0700

Note the omitted colon `:` between the hours and minutes in the timezone. [RFC 3339 pg.13](https://tools.ietf.org/html/rfc3339#page-13) provides a grammar for valid RFC 3339 datetimes, and the colon is optional.

However, Hugo is unable to parse these dates, and sets them all to 0000-00-00. Adding the colon in makes Hugo parse them as normal. I've done some reading on datetimes in Go and have found that they're awkward and weird. But I don't yet understand where or how Hugo parses dates -- I'd love to help solve this problem if someone could get me started.

*(I understand that half my problem is input. Vim uses `strftime`, which only supports `%z -> ±hhmm`. `date -Iseconds` (RFC3339) from coreutils uses  `±hh:mm`, and provides `%:z -> ±hh:mm`. But `strftime` isn't as smart, and having to call a shell function makes it non-portable :( )*

**Comment by moorereason** [comment]
Please post a companion issue upstream at https://github.com/spf13/cast.  [`cast.StringToDate`](https://github.com/spf13/cast/blob/8965335b8c7107321228e3e3702cab9832751bac/caste.go#L1125) needs another format added to cover that case.

**Comment by raehik** [comment]
Thanks, I see how parsing works now. Will make an issue there.

**Comment by raehik** [comment]
Upstream has been merged with new tests passing. Quick Hugo build using cast's master branch shows that it reads this new format just fine. Need to update cast version and then good to close :)

Troubleshooting dependencies & building was surprisingly easy for a first-time go getter! And thanks for this project, love how data-oriented Hugo is.

**Comment by kaushalmodi** [comment]
May be this got fixed for `date`, but it doesn't seem to be fixed for all date fields, like `lastmod`.

For example, this fails the hugo run:

```
lastmod = 2100-12-21T00:00:00+0000
```

**Comment by kaushalmodi** [comment]
Hmm, actually I get a failure even with a colon-less time offset in `date` too:

```
date = 2018-01-23T00:00:00+0000
```

```
hugo v0.91.2-1798BD3F linux/amd64 BuildDate=2021-12-23T15:33:34Z VendorInfo=gohugoio
Error: Error building site: "/home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/elisp/ox-hugo/test/site/content/posts/date-org-time-stamp.md:3:27": unmarshal failed: toml: invalid date-time timezone
```

**Comment by jmooring** [comment]
@kaushalmodi Please open a new issue here, and an upstream issue at https://github.com/pelletier/go-toml. See:
<https://github.com/pelletier/go-toml/blob/v2/decode.go#L76>
