### ISSUE TITLE
theme.toml: Add max version to prevent Hugo breaking user's websites

### ISSUE THREAD

**Issue by gcushen** [gohugoio/hugo#5342]
## Problem

Hugo sometimes has breaking changes, for example `GetPage`.

Themes for Hugo, such as [Academic](https://github.com/gcushen/hugo-academic), have received a large number of issues/complaints from users who have updated Hugo and then discovered that their website is broken due to breaking changes in Hugo, such as `GetPage`, which have not had a chance to be integrated into themes. (Note that this specific breaking change is an example, and is integrated into Academic now.)

It's best practice for dependencies (e.g. themes) of a software project (e.g. Hugo) to be able to specify the min and max versions that are compatible, in order to prevent breaking things.

## Solution

Support a `max_version` option in `theme.toml` and update Hugo's code which checks for min version to **also check for max version**.

This relatively simple change would help prevent breaking changes in Hugo from breaking user's websites.

**Comment by bep** [comment]
>It's best practice for dependencies (e.g. themes) of a software project (e.g. Hugo) to be able to specify the min and max versions that are compatible, in order to prevent breaking things.

What "best practice" are you talking about now? This is an extremely complex area with many opinions and implementation. Just look at the recent debate around Go Modules and their "minimal version selection algorithm" -- which I really like, but I would never label it "best practice". But I suspect that would fit Hugo's case better -- but there are many pieces missing in the puzzle before we're getting there. But I'm not putting a "max_version" into the mix until this is carefully thought through.

**Comment by gcushen** [comment]
My perspective on dependency best practice is based on really popular languages like Python, JS (Node), and Rust - all of which support min/max version ranges. I appreciate not all languages are the same and Go devs generally think pretty outside the box with an open mind when considering a solution rather than following in another language's footsteps. At the end of the day, 

My main point though is that currently Hugo is breaking user's websites.

A short-term fix to prevent breaking user's sites could be for Hugo to only build if the binary is *exactly* the same version as in `theme.toml`. Or at least provide a warning message at the top of console output is the Hugo version differs to `theme.toml`.

Otherwise, many users are getting broken sites without any explanation...
