### ISSUE TITLE
Make the "filename error log format" configurable

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5352]
See #5332

I don't think we should add an "editor config" section yet.

But we can add a **OS environment variable only**: `HUGO_FILE_ERROR_FORMAT` or something like that, where you could describe the format somehow.

**Comment by kaushalmodi** [comment]
The OS env var would be fine too.

> HUGO_FILE_ERROR_FORMAT or something like that, where you could describe the format somehow.

I'd suggest a name like `HUGO_EDITOR_FILE_LINENUM_FORMAT`, and I could hypothetically set that to `"+LINE:COL FILE"`.

Hugo will replace LINE with line number, COL with column number, FILE with absolute file path and create a string `foo`, and then invoke `$EDITOR foo` (where `EDITOR` is another env var and is usually set by default on most (all?) Unix systems).
