### ISSUE TITLE
Allow Scratch.Add with a mix of types

### ISSUE THREAD

**Issue by stp-ip** [gohugoio/hugo#5361]
With the change in v0.49 to restrict scratch to the string type only it broke quite a bit of existing behavior using scratch as a variable (this was necessary before variable overwrite was a thing and also has other benefits).

One behavior that broke was the possibility to assign hugo.PageOutput to scratch.

One occurrence is this line: https://github.com/okkur/syna/blob/master/layouts/partials/helpers/fragments.html#L85

Error output:
```
Building sites … ERROR 2018/10/26 15:14:48 [en] page "/okkur/syna/exampleSite/content/dev/empty-subitems/index.md": render of "page" failed: execute of template failed: template: _default/single.html:4:6: executing "main" at <partial "helpers/fra...>: error calling partial: "/okkur/syna/layouts/partials/helpers/fragments.html:86:17": execute of template failed: template: partials/helpers/fragments.html:86:17: executing "partials/helpers/fragments.html" at <$page_scratch.Add>: error calling Add: append element type mismatch: expected string, got *hugolib.PageOutput

```

We assing a hugo.PageOutput to scratch instead of a plain string.

Related to #5275

**Comment by bep** [comment]
Thanks for the report. I see how this was an unintended change, and I will see if I can fix it, but I suspect that this is both very rare and almost always a sign that something else is wrong.

From what I read from your template, you start out by creating a `string` slice:

```
{{- $page_scratch.Set "sections" (slice "/") -}}
```

Then you do some looping and continue to add `Page` objects to that string slice. I suspect that you need to adjust the logic to work either with strings or `Page` objects -- I don't see where mixing those would help you.

**Comment by stp-ip** [comment]
We'll see how a fix makes sense. Another idea would be to move to the new variable overwrite in Go templates, but that's a much bigger change.

What's your general stance on this. It's a bug, but works as it should be now more than it did before or Hugo should preserve the old way instead of breaking this?
