### ISSUE TITLE
REF_NOT_FOUND does not show where the ref is located

### ISSUE THREAD

**Issue by pjbakker** [gohugoio/hugo#5371]
Situation:

The error in case of a non-existent ref is:
```
ERROR 2018/10/29 11:43:36 [en] REF_NOT_FOUND: Ref "bank": page not found
```

Issue:
It does not show me the context or in which file this error occurred. Thus requiring a grep in order to retrieve the error location.

Solution:
Change error message to include filename of page containing the issue, like:
```
ERROR 2018/10/29 11:43:36 [en] REF_NOT_FOUND: Ref "bank": page not found in "content/financial.md"
```

**Comment by bep** [comment]
What Hugo version have you tested this with?

**Comment by pjbakker** [comment]
Hugo Static Site Generator v0.49.2/extended darwin/amd64 BuildDate: unknown

**Comment by bep** [comment]
Yea, that error isn't all that great ...

**Comment by pjbakker** [comment]
We agree there ;)
