### ISSUE TITLE
Strange error on partial in baseof.html 

### ISSUE THREAD

**Issue by ikemo3** [gohugoio/hugo#5373]
## Steps to reproduce

I made example repository to reproduce error.
https://github.com/ikemo3/hugo-baseof-partial

```
git clone https://github.com/ikemo3/hugo-baseof-partial
cd hugo-baseof-partial
git checkout error
hugo
```

if `{{ partial "baseof.body" . }}` is in baseof.html, this error occured.
if `{{ partial "body" . }}` is in baseof.html, this error not occured.
(master branch in the example repository).

## Actual Results

```
Error: Error building site: "/Users/ikemo/hugo-baseof-partial/layouts/_default/baseof.html:7:5": execute of template failed: template: 404.html:7:5: executing "404.html" at <partial "baseof.body...>: error calling partial: Partial "baseof.body" not found
```

## Expected Results

No error.

## Version

`Hugo Static Site Generator v0.50/extended darwin/amd64 BuildDate: unknown`
installed by Homebrew.

**Comment by bep** [comment]
We currently use "baseof" as an identifier to identify ... base templates. Those are handled specially. I picked "baseof" as a very distinctive name thinking no-one would ever think of calling their other templates that. I could probably add additional checks here, but this is not a priority for me. For now: Consider baseof.* to be reserved for base templates.

**Comment by ikemo3** [comment]
> For now: Consider baseof.* to be reserved for base templates.

This is no problem.
But I was confused by this error, so I would like to update the document.

**Comment by ikemo3** [comment]
I tried reading source code.
(I am a newbie at golang)

In tpl/tplimpl/template.go, isBaseTemplate uses strings.Contains.
Therefore, it seems that partial including `baseof` can not be used.

I will close this ticket and send a document correction.
