### ISSUE TITLE
Consider allowing symlinks below /assets in project

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5374]
https://discourse.gohugo.io/t/symlinks-error-blocks-site-rendering-in-hugo-server-in-0-50/14962/2

**Comment by davidsneighbour** [comment]
Hugo needs either this or has to allow the use of relative paths like "../node_modules...." in concat pipelines. At the moment I have to copy all needed files into the assets folder before using it to concat - which doubles the files "laying around". node_modules has to be outside of the assets directory in root, otherwise, other build scripts won't work.

**Comment by bep** [comment]
@davidsneighbour yes, we need to fix this -- but the problem with symbolic links is that they create its own set of problems/challenges on change detection. I'm not sure that is such a problem inside /assets  -- but I suspect a better solution to this would be to allow multiple asset dirs, e.g.

```
assetDir = ["assets", "node_modules"]
```

And probably also alias the plural version:


```
assetDirs = ["assets", "node_modules"]
```

**Comment by onedrawingperday** [comment]
@bep You asked above and I replied:
>I'm not sure that is such a problem inside /assets

Anyway Happy Holiday!

**Comment by DennisJohnsen** [comment]
I'm currently trying to do a neat way of handling JS and bundling directly in our Hugo based projects, and just now i ran into needing this feature.

My current example is that i have an array of the scripts in my `config.toml` and then i range over that array to use `resources.Concat`.

```toml
[params.js]
    partials = [
        '../node_modules/jquery/dist/jquery.min.js',
        '../node_modules/jquery-validation/dist/jquery.validate.min.js',
        'scripts/generic/global.js',
        'scripts/generic/parallax.js',
        'scripts/generic/format.js',
        'scripts/generic/intro.js',
        'scripts/navigation/smooth-scroll.js',
        'scripts/navigation/sticky-nav.js',
        'scripts/gallery/modal.js',
        'scripts/contact/google-maps.js',
        'scripts/contact/validation.js',
        'scripts/contact/send-mail.js'
    ]
```

```html
{{ $js := slice }}

{{ range .Site.Params.js.partials }}
  {{ $js = $js | append (resources.Get (printf "%s%s" "scripts/" . )) }}
{{ end }}

{{ $scripts := $js | resources.Concat "dist/scripts.js" | resources.Minify }}

<script type="text/javascript" src="{{ $scripts.Permalink }}"></script>
```

The error the above code gives: `<resources.Get>: error calling Get: FindFirstFile F:\Dropbox\Projekter\Hugo\hm-autolakering\assets\node_modules\jquery\dist\jquery.min.js: The syste           m cannot find the path specified.`

Right now, to make it easier for my self, i will just include those two node includes directly into the assets folder. But having the option to move outside the assets folder would be awesome!

**Comment by jmooring** [comment]
It seems like the intent of this issue was resolved with [mounts](https://gohugo.io/hugo-modules/configuration/#module-config-mounts). Can we close this issue?

**Comment by DennisJohnsen** [comment]
> It seems like the intent of this issue was resolved with [mounts](https://gohugo.io/hugo-modules/configuration/#module-config-mounts). Can we close this issue?

You would do source as node_modules and target the same?

**Comment by jmooring** [comment]
If I understand your question, I think you want this:

```
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "node_modules"
target = "assets/node_modules"
```

**Comment by jmooring** [comment]
The intent of this issue was resolved with [mounts](https://gohugo.io/hugo-modules/configuration/#module-config-mounts).
