### ISSUE TITLE
"# more" does not work in org-mode

### ISSUE THREAD

**Issue by fliar** [gohugoio/hugo#5381]
it worked before, but currently I have to replace it with  `<!--more-->`

**Comment by bep** [comment]
Hmm... Thanks for the report.

**Comment by bep** [comment]
This works:

```bash
#+TITLE: T1
#+AUTHOR: A1
#+DESCRIPTION: D1
This is the summary.
# more

This is some more content.	
```

But this doesn't:

```bash
#+TITLE: T1
#+AUTHOR: A1
#+DESCRIPTION: D1
This is the summary.
# more
This is some more content.	
```

Which suggests some newline changes in the reimplemented parser. Will check.

**Comment by bep** [comment]
> Possibly a separate bug

No, it's the same.

**Comment by bep** [comment]
@fliar I have revised the implementation of this and added some more test cases. I'll admit that I don't use Org Mode myself and I have never seen a document with `# more` in it, but I assume it's just a delimiter ... Note that this also kind of worked in Hugo `0.50` but it was very picky about whitespace.

**Comment by kaushalmodi** [comment]
> I have never seen a document with # more in it, but I assume it's just a delimiter

`# foo` is just a comment in Org mode.

Goorgeous considers "# more" as a special comment to insert `<--more-->` in HTML. I wish it used a better syntax like `#+hugo: more`. But that ship has sailed, I guess.

**Comment by fliar** [comment]
@bep I've updated Hugo to 0.51 and the bug is not fixed

here's the test org file I created with `hugo new` command (rename it to test.org)

[test.txt](https://github.com/gohugoio/hugo/files/2566336/test.txt)

Hugo outputs this:

> Test
> 
>  Nov 09 2018, 23:02
> this is summary this is content
