### ISSUE TITLE
Make ERROR when dot is not included in partial

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#5391]
While testing a Theme Submission over [here](https://github.com/gohugoio/hugoThemes/issues/460#issuecomment-435292522) the author had missed the dot in one of his partials like so: 
`{{ partial "footer" }}`

Naturally the partial did not render when running `hugo server` but also there was no ERROR in the console to alert me about the missing dot and I only noticed afterwards, while looking at something else. 

If possible, I think that we need a proper console ERROR for the missing dot in partials.

**Comment by bep** [comment]
>If possible, I think that we need a proper console ERROR for the missing dot in partials.

My instinct told me yes, that we could do.

But I suspect that would break some sites who don't care about the "dot" (i.e. pure text includes).

/cc @kaushalmodi @regisphilibert

**Comment by kaushalmodi** [comment]
I could have one or two partials in my sites where I don't need the dot at all. I'll confirm later today.

**Comment by bep** [comment]
@kaushalmodi my worry isn't about you. I'll not lose too much sleep if you get an error.
