### ISSUE TITLE
Support previous "jsonify" behavior without pretty print JSON

### ISSUE THREAD

**Issue by slathrop** [gohugoio/hugo#5394]
### The Problem
As of 0.50, the **Allow "jsonify" to pretty print JSON** issue, #5040, "breaks" existing code and provides no ability to retain the previous behavior. This issue proposes to solve this problem by either:

1. Reverting "jsonify" to previous behavior and introducing an optional means of pretty printing, **or**
1. At least, to please do the reverse and provide a means of specifying that "jsonify" (or other new function such as "jsonifyPlain") should use/support the previous behavior

### Why?
- There are existing Hugo projects which **use Hugo to generate REST APIs serving JSON**
  - e.g., [here](https://github.com/railroadpm/site/tree/dev#api) and see [here](https://forestry.io/blog/build-a-json-api-with-hugo/)
- These Hugo projects tend to divide-and-conquer by implementing Hugo **shortcodes** and **partials** that **piece-together multiple JSON segments at different indentation levels**
  - Therefore, these projects **do not** expect, from past Hugo behavior, that indentation and formatting will be applied
  - They may prefer to minimize JSON size by eliminating much of the whitespace altogether
  - Or often they may have managed the indentation of multiple JSON segments/fragments as-needed in templates
- The new behavior "breaks" the work that these projects have done to craft their output as desired and offers no way to retain previous Hugo behavior

**Comment by bep** [comment]
OK, I'm sorry, I obviously didn't think before I merged this.

I'll revert it for now, and we can find a better solution (maybe add some kind of option) later.

**Comment by slathrop** [comment]
Cool, many thanks @bep. I definitely like the pretty print option though. 👍

**Comment by SeanPrashad** [comment]
I'd love to help correct my patch that introduced pretty printing behaviour - maybe we should keep two  different options, one with and one without pretty printing?

**Comment by bep** [comment]
>Cool, many thanks @bep. I definitely like the pretty print option though

Yes, we'll do that. But in case I'm doing a 0.50.1 release, I thought the easiest was to revert.

I have reopened the original issue. I guess the alternatives are `{{ "some json" | jsonify "pretty" }}`  (or `{{ "some json" | jsonify "  " }} ` where you add indendation as an option) or `{{ "some json" | jsonifyPretty }}`. I suspect the "pretty" option is better, because then you can somehow configure it.
