### ISSUE TITLE
Fix error message for min version

### ISSUE THREAD

**Issue by gcushen** [gohugoio/hugo#5399]
With `min_version = 0.50` and Hugo version < 0.50, the error received is in the form:

`ERROR 2018/11/03 17:56:00 ACADEMIC theme does not support Hugo version 0.49.2. Minimum version required is 0.5`

The `0.5` in the error message should read `0.50`. Obviously there's a big difference between minor version 5 and 50.

I have checked and this little bug still exists in the latest version (Hugo v.50) - for example, to test, set `min_version = 0.60` in a `theme.toml`.

**Comment by bep** [comment]
>The 0.5 in the error message should read 0.50. Obviously there's a big difference between minor version 5 and 50.

That is true, but I think most people get the real message.

**Comment by bep** [comment]
I have looked at the code. And that value is read from `theme.toml`, so if you say:

```
min_version=0.50
```

Which I suspect is the case here, that is a float == `0.5`.

What you should do is:

```
min_version="0.50"
```

I don't think we can guess here.

**Comment by gcushen** [comment]
@bep Thanks, I assumed that Hugo would force cast min version to string. I'll update the theme code :)

**Comment by gcushen** [comment]
This is perhaps more a docs issue then. All the docs I have seen in the past seem to imply that a float should be used. For example, https://gohugo.io/getting-started/code-toggle/#another-config-toggler

**Comment by gcushen** [comment]
This is perhaps more a docs issue then. The docs imply that a float should be used: https://gohugo.io/contribute/themes/#create-a-theme-toml-file

**Comment by bep** [comment]
> I assumed that Hugo would force cast min version to string.

We do, but how do you convert `1.5` to `"1.50"` without making assumptions?

**Comment by bep** [comment]
An added note: Travis (the build server we use) had a similar issue when Go version rounded "1.10". They accept a float, but "Go 1.1" was not a good choice.

**Comment by gcushen** [comment]
FYI the README in the hugoThemes repo also states that `min_version` should be provided as a float rather than string: https://github.com/gohugoio/hugoThemes

**Comment by jmooring** [comment]
The documentation was updated (not sure when) to show strings in configuration example.

![image](https://github.com/gohugoio/hugo/assets/335669/581f5b15-8659-4145-bf36-b2f177949cb9)

https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration
