### ISSUE TITLE
Verify by Google Webmaster Tool

### ISSUE THREAD

**Issue by Zepeng-Mu** [gohugoio/hugo#5401]
Where should I put my .html file provided by Google in order to verify my website?

I am hosting my website on Netlify. Currently, I put the HTML file under the "content" folder, but webmaster gives me an error saying that file cannot be found.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
