### ISSUE TITLE
Error concatenating JS “Uncaught SyntaxError: Unexpected token *”

### ISSUE THREAD

**Issue by dangelion** [gohugoio/hugo#5403]
I add a concatenated JS like this:

    {{ $jquery := resources.Get "node_modules/jquery/dist/jquery.js" }}
    {{ $swiper := resources.Get "node_modules/swiper/dist/js/swiper.js" }}
    {{ $main := resources.Get "js/main.js" }}

    {{ $scripts := slice $jquery $swiper $main | resources.Concat "js/main.js" | minify | fingerprint }}
    <script type="text/javascript" src="{{ $scripts.Permalink }}" integrity="{{ $scripts.Data.Integrity }}" media="screen"></script>

but in the browser console I have this error:

`Uncaught SyntaxError: Unexpected token *`

Investigating it seems it's due to a comment at the end of some libraries that cause the error, like this:
`//# sourceMappingURL=scrollMonitor.js.map/**`

I think it's the same as here: https://github.com/matthiasmullie/minify/issues/35  (this is not used by Hugo but it's only an example, I can’t find nothing better or more specific.)

I think the problem is not related to the libraries but it's related to **concatenate** tool, because: 
- the same libraries work well when I used Gulp as build tool
- adding the same libraries _individually_ there is no error
- I get error even removing the minify
- I get this error with many and pretty famous libraries

You can see the official discussion here https://discourse.gohugo.io/t/error-concatenating-js-uncaught-syntaxerror-unexpected-token/15065/14

**Comment by bep** [comment]
It would be good if you could raise an issue here:

https://github.com/tdewolff/minify/issues

With a link back to this issue so we can track it.

**Comment by dangelion** [comment]
As I said before I don't think it's related to minify, because disabling it the error persists. It should be related to concatenation

**Comment by vincent99** [comment]
The problem is there's no trailing newline, so the end of your one file is a comment (`//# sourceMap....`) and the next file gets placed on that line and all that code is commented out until that file has a newline in it.  To safely concatenate arbitrary JS files you really need to separate them by a newline and semicolon.

You can work around this by making an "empty.js" that just contains a newline and semicolon, then load it as a resource and stick it between every 2 files in your slice list.

**Comment by vincent99** [comment]
This is still a bug that people are going to hit with the right combination of files to be concatenated..

I looked at the code briefly, the actual concat is [here](https://github.com/gohugoio/hugo/blob/ce8a09a4c0661dece931ab1173e4f09e8e04aa38/resources/resource_factories/bundler/bundler.go#L103) with a built-in `io` method.

So it would seem a fix should check if the media type is JavaScript and  if so inject an extra ";\n" buffer between each pair of input buffers before they are given to the `MultiReader`.
