### ISSUE TITLE
Add collections.SymDiff

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5410]
See #5400

Alias: `symdiff`

**Comment by kaushalmodi** [comment]
Looking at this, makes me think.. may be you should break it out into a separate Go library for Set Theory. That way it will open it up for more contributions, and you just create aliases for the methods in Hugo.

**Comment by bep** [comment]
Hugo's type handling is, in general, not useful outside of Hugo.

**Comment by kaushalmodi** [comment]
Thanks, I was reading the PR in hurry and missed that.

**Comment by bep** [comment]
> Isn't type handling good, usually?

That's a very generic statement to have an opinion either way about. Go 2 will probably come with Generics, which may or may not make our lives easier, but there are a couple of reasons why these template funcs works best as ... template funcs:

* We use `reflect` so we can take any type (Page, int, string ...) and ... complement it etc. This is, of course, in general useful, but isn't very ... pretty to look at.
* The way Go template funcs works makes us make these slightly odd APIs (re. yesterdays discussion). That works in templates, but we would do it differently if a pure Go API.
* And finally, since the different decoder libraries we use (JSON, TOML, YAML) all have their own conception of which types to use for numeric values, we also do some conversion of those etc. which we probably would not care about in a general library.

**Comment by kaushalmodi** [comment]
Thanks for the detailed explanation; makes sense!
