### ISSUE TITLE
Update Mmark engine to the latest

### ISSUE THREAD

**Issue by 747** [gohugoio/hugo#5417]
A few weeks ago I requested them to support multiple footnote references mmarkdown/mmark#25 as the built-in Blackfriday engine currently does. They implemented, but this feature still seems not functional as of Hugo 0.51.

I'd be happy if the latest version of Mmark would be bundled, as it is getting constant update recently. I couldn't actually figure out how the package is managed in Hugo's code base, so please enlighten me if I'm posting on wrong place.

**Comment by bep** [comment]
Note that the current mmark has just the name in common with the "mmark" package we have in Hugo. So this is a question if we should add something new. Or not.

**Comment by moorereason** [comment]
To be clear, Hugo currently supports mmark via the Blackfriday package.  The latest mmark development is not built on Blackfriday and is, therefore, not supported by Hugo at this time.

**Comment by onedrawingperday** [comment]
To be even clearer please see #5124 for the reasons why Hugo cannot switch its Markdown engine at present and support the latest version of Mmark.

**Comment by 747** [comment]
Thank you for the information.
