### ISSUE TITLE
Missing elements after updating Hugo

### ISSUE THREAD

**Issue by Jo-Karl** [gohugoio/hugo#5419]
Good morning,

I initially encountered the following problem that posts would not show up if there was more than one post. I fixed this by updating Hugo, but now a number of elements are missing from the home page.
https://johanneskarl.netlify.com/#about

Namely, the icons for Github and Twitter, the reading time for posts (it still shows the number, but not the min label), the dataset labels for posts, and last the images for the projects.
I did not make any changes to these. Is this due to a bug?

**Comment by bep** [comment]
>Is this due to a bug?

I doubt it, but it's impossible for me to say without additional context. Mainly the source of your Hugo site.

**Comment by Jo-Karl** [comment]
Thanks for the quick response.
Below is a link to the github repository:
https://github.com/Jo-Karl/JoKarl

**Comment by moorereason** [comment]
What versions of Hugo are we talking about here?
