### ISSUE TITLE
(.apib) API Blueprint support

### ISSUE THREAD

**Issue by nkirsch** [gohugoio/hugo#5420]
Any thoughts to supporting `apib` files? https://apiblueprint.org/

FYI, supported as first-class citizen in GH: https://github.com/apiaryio/api-blueprint/issues/52

I'm happy to hack at this if there isn't any strong pushback.

**Comment by moorereason** [comment]
Are you wanting syntax highlighting?  If so, open an issue upstream with [chroma](https://github.com/alecthomas/chroma).  If not, please explain.
