### ISSUE TITLE
Use shortcode inside a one-line shortcode

### ISSUE THREAD

**Issue by opieters** [gohugoio/hugo#5429]
I have the following shortcode: 

```html
<a target="_blank" href="{{ .Get 1 }}">{{ .Get 0 | markdownify }}</a>
```
in `blank_url.html`

In one of my contents pages I would like to reference another page (using `ref` or `relref`) and have it opened in a different window using the above shortcode. However, it looks like this is currently not possible with Hugo.

This might also be useful for the default `figure` shortcode, since links inside a caption are not possible using `ref` or `relref`. 

Possible syntax(?):

```html
{{< blank_url "here" (ref "projects/limecv.md") >}}.
```

**Comment by zwbetz-gh** [comment]
@opieters In the meantime, here is a workaround.

Definition:

```
<a target="_blank" {{ printf "href=%q" .Inner | safeHTMLAttr }}>{{ .Get 0 | markdownify }}</a>```

Usage:

```
{{< blank_url "here" >}}
  {{< relref "projects/limecv.md" >}}
{{< /blank_url >}}
```

**Comment by zwbetz-gh** [comment]
@opieters Thanks to bep, here's a cleaner way.

Updated definition:

```
{{ $page := .Site.GetPage (.Get 1) }}
<a target="_blank" {{ printf "href=%q" $page.Permalink | safeHTMLAttr }}>{{ .Get 0 | markdownify }}</a>
```

Updated usage:

```
{{< blank_url "here" "projects/limecv.md" >}}
```

**Comment by opieters** [comment]
That's already a great workaround for now, but it requires one to maintain two versions of `blank_url`: one for internal pages and one for external pages.

**Comment by zwbetz-gh** [comment]
Your original issue referenced `ref` and `relref`, which only work for internal pages. 

So by asking it to work for external links, you have essentially changed your original requirements. 

But this can still be handled by the shortcode. For example, you could pass an additional argument such as `isExternal`, then update the shortcode logic to handle both internal pages and external links.

**Comment by opieters** [comment]
Indeed, I failed to state that the same short code should work for both internal and extneral links. However, this was my initial intent. 

Indeed, a conditional can fix this. However, this setup does not work with predefined shortcodes. Something that is reference in my initial statement.

**Comment by zwbetz-gh** [comment]
> Indeed, a conditional can fix this. However, this setup does not work with predefined shortcodes. 

I am not sure what the above means. 

But, to make the shortcode work with both internal and external resources, update the definition to be:

```
{{ $text := .Get 0 }}
{{ $ref := .Get 1 }}

{{ if or (in $ref "http://") (in $ref "https://") }}
  <a target="_blank" {{ printf "href=%q" $ref | safeHTMLAttr }}>{{ $text | markdownify }}</a>
{{ else }}
  {{ $page := .Page.GetPage $ref }}
  <a target="_blank" {{ printf "href=%q" $page.Permalink | safeHTMLAttr }}>{{ $text | markdownify }}</a>
{{ end }}
```

Usage examples:

```
{{< blank_url "internal" "projects/limecv.md" >}}

{{< blank_url "external" "https://gohugo.io/" >}}
```

**Comment by opieters** [comment]
What I mean is that Hugo features builtin shortcakes like [`figure`](https://gohugo.io/content-management/shortcodes/#figure). 

Your workaround does not work with them.

**Comment by zwbetz-gh** [comment]
I am still not sure what you mean. Can you give a specific example?

Also, the `figure` shortcode has a `target` param, so you can make the image open in a new tab if you wish.

**Comment by opieters** [comment]
Yes, but not when I want to do something like this:

```
{{< figure src="latex-vs-word.svg" title="LaTeX vs. Word" class="centre-element max-400px-wide" caption="LaTeX versus a typical WYSIWYG word processor. Reproduction from {{< blank_url "this post" "http://www.jaftalks.com/wp/index.php/latex-or-microsoft-word-in-it-organization/" >}} by Hassan Jaffal." >}}
```

The link does not apply to the entire image, just some text in the caption.

**Comment by zwbetz-gh** [comment]
Right, you currently can't pass a shortcode as an argument to another shortcode. 

But, you can still get your desired functionality. 

Just create a custom `figure` shortcode based off the [original](https://github.com/gohugoio/hugo/blob/6818170308994b5f01dec7a559f92d6c7c5ca100/tpl/tplimpl/embedded/templates/shortcodes/figure.html). 

Then instead of using the `caption` param, pass the caption as `.Inner`. See my original reply for reference.
