### ISSUE TITLE
Use 764 for files created

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5434]
In working with #5404 I notice that we create new files (in library helpers here and in Afero) with "0777 // before umask". I understand the need for the execute bit on directories, and while umask is great, it may be a little technical to most people, and we should consider making this something more strict for regular files. 

https://chmodcommand.com/chmod-764/

Opinions @moorereason @kaushalmodi @anthonyfok ?

**Comment by moorereason** [comment]
I think we should defer this to umask.  Don't fight against the host system; work within it.  I suspect that we'll have bug reports that Hugo isn't respecting umask if we make this change.

**Comment by bep** [comment]
@moorereason never mind, I have re-read the code: We create directories with 0777 before umask (we need the execute bit here), but file creation is delegated to `os.Create`, which uses mode 0666 (before umask).
