### ISSUE TITLE
Fix  raw css imports in SCSS

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5435]
See https://github.com/sass/libsass/commit/79c16c99dfbbcbe6de38c48a1d624654653a5c83

I've seen questions about this on the forum, so I add this issue to track this. This behavior is now reverted back to the "old one" in Libsass 3.55, see #5432

To close this issue, we should have a simple test so we get notified if we need to do something (options?) in the future.

**Comment by bep** [comment]
Note: I have updated to latest LibSASS, but I have not have time to look into if this particular issue is fixed. Test help welcome.

**Comment by jmooring** [comment]
With v0.111.3 and the LibSass transpiler...

```
assets/
└── scss/
    ├── a.css
    └── main.scss
```

main.scss|What we do
:--|:--
`@import "a.css";`|plain CSS import
`@import "a";`|import and transpile


This conforms to:
<https://sass-lang.com/documentation/at-rules/import#plain-css-imports>
