### ISSUE TITLE
"# more" does not work in org-mode in 0.51

### ISSUE THREAD

**Issue by fliar** [gohugoio/hugo#5436]
same issue of #5381 , but not fixed in 0.51

I've posted a test org file in #5381 , sorry for duplicating but I cannot reopen the old one

**Comment by bep** [comment]
```bash
---
title: "Test"
date: 2018-11-09T23:02:52+08:00
draft: true
---

this is summary

# more

this is content
```

The above is not "ORG mode front matter". Note that I have fixed/patched/tested this ORG mode format without any existing tests nor spec. And I can say that the above is not something that I plan to support, even if it has worked before. If someone wants to implement this with proper tests, they are welcome.

**Comment by kaushalmodi** [comment]
I am traveling, so won't be able to look at this in detail until 3 weeks from now. 

@bep the example you pasted looks alright. It's not clear if that's what you support now or is just a proposal. 

If it's a proposal, I'd suggest having `#+hugo: more` (#+hugo` is case insensitive as per Org mode spec) instead `# more`.

**Comment by bep** [comment]
>If it's a proposal

It's a failing Org Mode test case (whatever Org Mode is). I just leave this issue open for anyone interested.
