### ISSUE TITLE
When will be merged "fix RelURL and AbsURL when path starts with language" ?

### ISSUE THREAD

**Issue by ivan-meridianbanc-com** [gohugoio/hugo#5437]
When will be merged "fix RelURL and AbsURL when path starts with language" ?

https://github.com/gohugoio/hugo/pull/5369

**Comment by ivan-meridianbanc-com** [comment]
@bep

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
