### ISSUE TITLE
Add argument to make warnings return an error

### ISSUE THREAD

**Issue by roger6106** [gohugoio/hugo#5445]
Our continuous integration system automatically builds and deploys any changes we make in our git repository. For this system, it would be great if we could use an argument that would make hugo exit with an error code if any warnings occur. This would prevent bad changes from being deployed.

**Comment by james-callahan** [comment]
I have a hugo repository that uses git submodules to bring in themes.
If a developer forgets to clone the submodule, then hugo prints a series of warnings e.g.

> WARN 2020/04/14 03:01:48 found no layout file for "HTML" for "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

Unfortunately though, the build process continues and unless the developer reads the logs closely then they don't realise there has been a failure.

Please introduce a command line flag that turns warnings into errors that exit with a non-zero status code. That way build processes can fail immediately.

**Comment by jmooring** [comment]
This was addressed a while ago with the `--panicOnWarning` command line flag.
