### ISSUE TITLE
Unable to embed {{%- inside org SRC block

### ISSUE THREAD

**Issue by nickanderson** [gohugoio/hugo#5446]
I have an org-mode file that contains a SRC block, and I side that code block I am using the string {{%-top-}}. I can't build the page because of a unicode error, of I change the string to something that works, then the code within the block is not correct.

Rendered page

https://cmdln.org/2018/11/16/the-top-mustache-extension-in-cfengine-3/

Relavent Org source

https://github.com/nickanderson/nickanderson.github.io/commit/52959fa8798afebe8c501cc2774264aaa06d575e

**Comment by craigcomstock** [comment]
I just ran into this issue and would love a solution. Maybe I'll look into the code if I can.
