### ISSUE TITLE
Rework the min_version for theme components

### ISSUE THREAD

**Issue by akshaybabloo** [gohugoio/hugo#5450]
Sometimes we might use SCSS and adding support for an extended version of Hugo in `min_version` would help others as a requirement. Example:

```
min_version = "0.51-extended"
```

**Comment by felicianotech** [comment]
I still dislike having a separate extended version in the first place. My first choice would be to have a single build.

If that doesn't happen, then this makes sense.

**Comment by akshaybabloo** [comment]
Adding text so that the bot doesn't close this issue.

**Comment by bep** [comment]
I'm soon going to release a Hugo version with what we somehow have agreed to name **Hugo Modules** which I'm certain that you will really, really like. And with that, these interop issues gets even more important to warn about. 

What suggest is that we replace what we have (the old will still work), with a `hugo_version` config that you can set in `theme.toml`, variants being:

```yaml
hugo_version:
    min: "0.55.0"
```

```yaml
hugo_version:
    min: "0.52.0"
    max: "0.55.0"
```

```yaml
hugo_version:
    min: "0.52.0"
    max: "0.55.0"
    features: ["scss"]
```

Note that I'm happy to discuss making the extended version the "regular" one for Linux, MacOS, and Windows, but as we do support many others, there is no short term realism in getting rid of the extended build for FreeBSD and all the others. I spent a good day getting the current extended builds running, and those were the platforms I could easily test on ... Do the math.

I'm not totally sure what the current values for `features` would be, but I thought it would be better to say `scss` than `extended`.

Any thougts/objections to the above?

/cc @regisphilibert and gang

**Comment by regisphilibert** [comment]
I love that you can add a `max` version as well. 

If we name the last key `features`, I'm afraid people might mistake it for some featured required by the theme. As in `Pipes`, `Related` etc...

Can we limit the `extended` build to `scss` and if another build variation is needed, will it be about just one feature as well?

I am not sure how build variation (already I am doing a poor job at defining it) should be labeled, and if more are going to come, but feature is kind of misleading.

**Comment by bep** [comment]
@regisphilibert you're right. By making it a config struct we can be explicit about it:

```
hugo_version:
    min: "0.52.0"
    max: "0.55.0"
    extended: true
```

**Comment by bep** [comment]
I'll handle this as part of #5996
