### ISSUE TITLE
Use resources from a page bundle in a list template

### ISSUE THREAD

**Issue by sjovang** [gohugoio/hugo#5456]
Is it possible to get resources from a page bundle from a section's list template?

Consider the following:

/content/dummy/test01/index.md:
```
---
title: "Foo"
resources:
- name: cover
  src: cover.jpg
---
Content
```

.../templates/dummy/list.html
```
{{ range .Pages }}
    <h1>{{ .Title }}</h1>
    {{ with $.???.Resources.GetMatch "cover" }}
        <img src="{{ (.Resize).RelPermalink }}">
    {{ end }}
    {{  .Content }}
{{ end }}
```
If I wanted something like an image gallery I could create a Branch Bundle instead of a Leaf Bundle, but here I want to show a thumbnail of the cover image in the list template, and then have more page resources, content, etc. when I display the single.html-template for the post

Is this even possible? I've tried to dig into google, documentation and issues on github but not found anything about it (I might be bad at searching too, if so I'm sorry for that)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
