### ISSUE TITLE
hugo convert does not pick up draft pages

### ISSUE THREAD

**Issue by zwbetz-gh** [gohugoio/hugo#5457]
Output of `hugo env`:
```
Hugo Static Site Generator v0.51 darwin/amd64 BuildDate: 2018-11-07T10:09:45Z
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.11"
```

---

Steps to reproduce:

1. `hugo new site yaml-site --format "yaml"`
1. `cd yaml-site`
1. `hugo new page1.md && hugo new page2.md && hugo new page3.md`
1. `hugo convert toTOML`

---

The output of `hugo convert toTOML` says:

> Error: Unsafe operation not allowed, use `--unsafe` or set a different output path

So I tried: `hugo convert toTOML --unsafe`, and got output:

> processing 3 content files

But when inspecting the front matter of content files, they are still in YAML.

Also see: https://discourse.gohugo.io/t/hugo-convert-totoml-not-working-as-expected/15414

**Comment by bep** [comment]
I had to scratch my head a little about this one. The test case above isn't all that realistic -- the reason why the above fails, is that all the newly created pages are drafts. It should work, of course, but I don't think it ever worked. If you edit the pages and remove the draft flag, everything works smoother.
