### ISSUE TITLE
Handle themes in the new file cache (images, assets)

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#5460]
Following the discussion from https://github.com/gohugoio/hugoThemes/issues/506#issuecomment-440726361 I am opening this issue to report that I am seeing the exact same behavior described over here: https://github.com/gohugoio/hugo/issues/5226#issuecomment-439082609

Reverting commit https://github.com/gohugoio/hugo/commit/5df2b79dd2734e9a00ed1692328f58c385676468 seems to fix the issue.

CC / @digitalcraftsman

**Comment by bep** [comment]
How can that commit be a problem for the "themes site"? It is not released?

**Comment by bep** [comment]
OK, now I see what that issue was all about.

**Comment by onedrawingperday** [comment]
Steps to reproduce.

- Clone theme repo
- `git submodule add https://github.com/desimone/evie-hugo`
- `cd _script/`
- `./generateThemeSite.sh > errors.txt`
- ERROR log: ``` ==== PROCESSING  evie-hugo  ====== 
Building site for theme evie-hugo using its own exampleSite to ../themeSite/static/theme/evie-hugo/
ERROR 2018/11/22 21:05:53 error: failed to transform resource: TOCSS: failed to transform "css/style.css" (text/css): this feature is not available in your current Hugo version
FAILED to create exampleSite for evie-hugo```

Hugo version
```
Hugo Static Site Generator v0.52-DEV-E82B2DC8:CHROMA-1B755A9 linux/amd64 BuildDate: 2018-11-22T20:58:37+0200
```

Here is the relevant commit in the Evie Theme's repository https://github.com/desimone/evie-hugo/commit/9caa8e1ca01f78de9de317f14f4cc0e01b0789e6

From `layouts/partials/header.html`
>{{ $style := slice $e1 $e2 $e3 $e4 $e5 $e6 $e7 $e8 $e10 $e11 $e12 $e13 $e14 $e15 $e16 $e17 $e18 $e19 $e20 $e21 $c | resources.Concat "css/style.css" | resources.ToCSS | minify }}
>	<link rel="stylesheet" href="{{ $style.Permalink }}" />
>	<link rel="stylesheet" type="text/css" href="{{ $style.RelPermalink }}" />

**Comment by bep** [comment]
OK, I see what's happening. Will fix.

**Comment by bep** [comment]
Note that for the "evie Hugo" example, this is not related to any "base path", this was broken in my recently "cache consolidation" PR. 

We cache resources, and in case "feature is not available" (aka Netlify), we fall back to cached SCSS result. The cache consolidation did not consider ... themes, which in most cases would not be visible (you just recache it the first time you run Hugo on the site itself), but not so for the "demo site".

I will fix this, just thought I should add a little context. The cache consolidation code is not in a released Hugo version, and the "relpermalink vs canonify" was an obvious bugfix.
