### ISSUE TITLE
Add variable expansion support in shortcode params

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5463]
See 3) in https://github.com/twbs/bootstrap/issues/24475#issuecomment-441211586

Not sure how this would look like, but something ala Bash's variable expansion, eg.

```
{{< relref "${.Site.Params.version}/features" >}}
```

**Comment by bep** [comment]
>Can’t this already be solved by a simple wrapper shortcode?

Yes. But it is a fairly common problem, and you it would potentially create lots of "wrapper variants" and make the content "unportable".

I don't think I'm solving this unless I can find a simple and fast way to do it -- but there are obvious and useful use cases for this.

**Comment by jicksta** [comment]
I think I've been running into a similar issue.

https://github.com/jicksta/repro-hugo-lexer-issue

I'm trying to render a Hugo page from a data file that passes dynamic data into a shortcode as a parameter. Doing something like:

    {{< myshortcode $somethingdynamic >}}

actually generates an error at the "$" (or at the `.` in the case of `.somethingdynamic`).

Maybe I'm missing something idiomatic about Go / Hugo templating, but shouldn't this be a supported use-case for shortcodes?

More info can be found in the README of the repo linked above.

Thanks btw for all the great work on Hugo so far!

**Comment by XhmikosR** [comment]
This is still a valid request.

**Comment by NorseGaud** [comment]
Big time want for us!
