### ISSUE TITLE
Where function should support float64 comparisons

### ISSUE THREAD

**Issue by pjdufour** [gohugoio/hugo#5466]
I'm trying to filter a JSON array of values returned from the GitHub API where "size" > 0; however, the `where XYZ "gt" 0` function is not working and returns an empty array every time.  Neither does `where XYZ "ge" 1` work. (XYZ is a placeholder).  Maybe there's a formatting issue I'm missing, but I've tried numerous different variations.

The full line is:

```
{{ $repos := getJSON "https://" (getenv "GITHUB_USER") ":" (getenv "GITHUB_TOKEN")  "@api.github.com/orgs/XYZ/repos?per_page=100" }}
{{ $sources := where (where (where $repos "size" "ge" 1) "fork" false) "archived" false }}
```

This works fine when I just filter boolean values.

```
{{ $repos := getJSON "https://" (getenv "GITHUB_USER") ":" (getenv "GITHUB_TOKEN")  "@api.github.com/orgs/XYZ/repos?per_page=100" }}
{{ $sources := where (where $repos "fork" false) "archived" false }}
```

**Comment by moorereason** [comment]
Does `where XYZ "gt" 0.0` work?

**Comment by pjdufour** [comment]
I just tried `xyz "gt" 0.0` and `xyz "ge" 1.0` and neither worked.  What is weird is that having and if `{{ if ge $repo.size 1 }}` within a range works fine, but the where clause doesn't work.
