### ISSUE TITLE
Make it easier to check for Pagination

### ISSUE THREAD

**Issue by Noki** [gohugoio/hugo#5468]
Hi!

I'm currently working on adding the page number of the current page to the title, meta-description, breadcrumb and h1 and use it in rel-prev/next links.

To do so I create a paginator on the homepage and on taxonomy pages. I than tried to check for the created paginator and than append the page number. The code looked like this:

```html
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5">
	<!-- create paginatior if possible and use it for title, description, proper rel canonical, prev and next -->
	{{ if and (ne .Params.ot_showlist false) (or (eq .Kind "home") (eq .Kind "taxonomy")) }}{{ $paginator := .Paginate (where .Pages ".Params.ot_showinlist" "ne" false) }}{{end}}
	<title>
		{{- if .Params.ot_seo_title -}}{{.Params.ot_seo_title}}{{- else if .Title -}}{{ .Title }}{{- else -}}{{ .Site.Title }}{{- end -}}
		{{if (and .Paginator (gt .Paginator.PageNumber 1)) }} - {{ T "page" }} {{ .Paginator.PageNumber }}{{ end }}
	</title>
```

This works on the homepage and on taxonomy pages. However it does not work on other page types where paginator is not supported:

![image](https://user-images.githubusercontent.com/198902/48978165-8bc5c980-f0a7-11e8-9393-4ebe30520593.png)

This means that the template code checking for a paginator needs two if conditions and becomes kind of messy:

```go
{{ if (or (eq .Kind "home") (eq .Kind "taxonomy")) }}{{if (and .Paginator (gt .Paginator.PageNumber 1)) }} - {{ T "page" }} {{ .Paginator.PageNumber }}{{ end }}{{ end }}
```

I would love to see a simpler approach for this. Do I miss something?

Best regards
Tobias

**Comment by bep** [comment]
* You can do `if .IsNode` (or even `if not .IsPage`) which will return true if the current page supports pagination.
* When the above returns `true` you are on your own, so to speak. I don't think we can provide more information, as that will create a catch 22 situation: You need to create a paginator before it exists, and only you know if you ... want one (so this construct of yours doesn't make sense: `if (and .Paginator (gt .Paginator.PageNumber 1))`.

**Comment by Noki** [comment]
Thanks for pointing this out. I was not aware that .IsNode and .IsPage implied that pagination is always supported or never supported. In my mindset there is also the possibility to have paginated articles. ;-)
