### ISSUE TITLE
Add tpl/site

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#5470]
If it's not much more complicated than https://github.com/gohugoio/hugo/issues/5467, it would be useful to also have `site` globally available.

It would save having to pass the Page Context to a template which only a needs few params on top of being able to use a few `.Site` variable/method. (ex: `.Site.IsServer` https://github.com/gohugoio/hugo/issues/4981#issuecomment-414711966)

**Comment by bep** [comment]
I guess that makes sense. But we should probably stop with this one ...

**Comment by regisphilibert** [comment]
Got it. It's all about the complexity/critical ratio. 
It would makes sense that site variables are accessible globally, but again not a critical.
