### ISSUE TITLE
Potential inconistencies in .Page.Dir for Windows

### ISSUE THREAD

**Issue by geeknoid** [gohugoio/hugo#5472]
Seems that .Page.Dir may be slapping an extra \ at the end of returned strings as compared to what happens on Mac & Linux, leading to sites that build on one platform but not the other.

Please see [this bug](https://github.com/istio/istio.io/issues/2917) for the smoking gun.

**Comment by bep** [comment]
.Page.Dir returns a file path, which means that doing manual splits using "/" will not be portable.

Try something ala `(path.Split  .Page.Dir).File`.

**Comment by geeknoid** [comment]
And unfortunately, using path.Split doesn't work well for .Page.Dir since .Page.Dir ends with a /. path.Split ends up returning a Dir value equal to the input path, and a File value of empty.

**Comment by bep** [comment]
As always, improvement PRs to docs are always welcome.

**Comment by MJ-CJM** [comment]
@bep Thank you very much for your reply.
