### ISSUE TITLE
Hugo documentation template

### ISSUE THREAD

**Issue by pjebs** [gohugoio/hugo#5476]
I was wondering where I can get hold of the hugo documentation template (the js, css etc). I'm assuming the documentation is itself created by hugo???

What is the license if it's available.

**Comment by RealOrangeOne** [comment]
The docs repo is at https://github.com/gohugoio/hugoDocs, and the theme is inside it at https://github.com/gohugoio/hugoDocs/tree/master/themes/gohugoioTheme
