### ISSUE TITLE
Frontmatter in html comment is suddenly ignored

### ISSUE THREAD

**Issue by gonapps** [gohugoio/hugo#5478]
I have used v0.46 hugo and there were no problems in front matter.
But now frontmatter in a html comment like this is ignored in v0.51
And I didn't tried other versions.
Is this a bug or an intended change? 
```html
<!--
+++
title = "hello"
+++
-->
```

**Comment by bep** [comment]
I rewrote the page parser in 0.51 (for many reasons), and I may have interpreted the old "comment out" logic.
