### ISSUE TITLE
markdown with mathjax in hugo and pandoc

### ISSUE THREAD

**Issue by libertylocked** [gohugoio/hugo#5480]
Is it possible to write one markdown with mathjax that shows up correctly in both Hugo and PDF compiled by `pandoc --mathjax`? 

Here is example

```
Where $sid\_a$ is Alice's sending mailbox ID, i.e. Alice puts encrypted messages to Bob in a mailbox whose ID is $sid\_a$. Similarly $sid\_b$ is Bob's sending mailbox ID. The $k\_{e}$ is the shared secret for E2E messaging, used to encrypt and authenticate the messages.
```

If I escape the underscores like above, they render correctly in Hugo, but not so much in pandoc's output

![image](https://user-images.githubusercontent.com/1425794/49145480-e3de1500-f2cd-11e8-8e25-4fcabaf1dfd7.png)

If I don't escape the underscores they look messed up in Hugo but compile correctly in pandoc.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
