### ISSUE TITLE
Using site variables in content

### ISSUE THREAD

**Issue by tyacbovi** [gohugoio/hugo#5482]
I am using some string in many pages on the site, so I want to set it to a global variable and reference to it somehow. I have started to tackle this with site variables, but I can not get the variable to be used in the content. Is this the way and I am missing something or there is another?

**Comment by onedrawingperday** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/). GitHub issues are used only for bugs and enhancements.
