### ISSUE TITLE
enableGitInfo does not work in a git bare repo

### ISSUE THREAD

**Issue by micressor** [gohugoio/hugo#5489]
If I have hugo in a `git --bare` repo on the server, `--enableGitInfo` does not work:

`WARN 2018/12/01 16:18:21 Failed to find GitInfo for page "post/x.md"`

In this example, hugo is called on the server via `hooks/post-receive`.

**Comment by bep** [comment]
What is the motivation for using bare repositorites?

**Comment by bep** [comment]
>I did the report because I noticed it and didn't know if hugo intended it that way.

Hugo uses "git log" and parses that. The intention is to ... get the Git info we need. So, `git --bare` obviously behaves differently in this area. It may be fixable, but since it probably requires "some hours" of work, we need a good reason.

**Comment by micressor** [comment]
> ...we need a good reason.

I think the effort would be too much as it works with normal repos.

However, the `WARN` error message was not displayed without the `--debug` option.

Maybe this could be optimized?
