### ISSUE TITLE
Hugo as subdomain website images not rendering

### ISSUE THREAD

**Issue by jnbli** [gohugoio/hugo#5490]
In config.toml, I set baseURL = "http://example.org/tutorial_site/".
Running **hugo server**, the website is hosted on **localhost:1313/tutorial_site/**.
The website works fine except for the images.

My image syntax does not work
`![twitter blue](/twitter-blue.png)` broken
Inspect element shows that hugo is looking for the image in **localhost:1313/twitter-blue.png** when in reality it is located in **localhost:1313/tutorial_site/twitter-blue.png**.

Besides doing
`![twitter blue](/tutorial_site/twitter-blue.png)`
is there a way to get images to work properly.
Ideally, they should work using `![twitter blue](/twitter-blue.png)`.

**Comment by onedrawingperday** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/). GitHub issues are used only for bugs and enhancements. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
