### ISSUE TITLE
Build failing with exit code 0

### ISSUE THREAD

**Issue by McInkay** [gohugoio/hugo#5493]
I'm having an issue where when there's malformed markdown, the site complains and doesn't build properly, but still completes with exit code 0. This leads to my circleci build passing and deploying when there's an issue with the files.

[Here's the build](https://circleci.com/gh/YaManicKill/pdd/31)

As you can see from the image below, there's an error in the markdown for one of the episodes, and it complains, but it is returning exit code 0.

![](https://files.yamanickill.com/Q5J0VJBb.png)

[And here's the code you can clone if you want to test out the issue](https://github.com/YaManicKill/pdd/tree/fix-error-code). The branch fix-error-code has changed the circleci build to not use yarn and has an error in one of the md files, you should just be able to run hugo on that branch and see that it is returning 0 exit code.

I saw #4734 but the response to that seems to be that it was yarns fault. I was running with yarn, but I have changed to not use yarn, and the error code is still 0, so it's not that issue.

**Comment by bep** [comment]
I'm almost certain that we do the correct thing here, so I suspect that you swallow the exit code in some wrapper script (Gulp?)

**Comment by McInkay** [comment]
All I was doing was running yarn to run hugo, but as I mentioned I have changed that and it's still failing.

You can see [in the code that I linked to](https://github.com/YaManicKill/pdd/blob/fix-error-code/.circleci/config.yml) that I am running hugo directly (`run: HUGO_ENV=production ./node_modules/.bin/hugo -v`) in circleci, and when I run this directly on my machine I get exit code 0 as well, it's not just on circleci.

**Comment by bep** [comment]
```bash
dev/dump/pdd  fix-error-code ✔                                                                                                                                                                                                          25d
▶ hugo
Total in 26 ms
Error: Error building site: "/Users/bep/dev/dump/pdd/content/episode/001-continuous-integration.md:13:1": failed to unmarshal YAML: yaml: line 12: found unexpected end of stream

dev/dump/pdd  fix-error-code ✔                                                                                                                                                                                                         25d  ⍉
▶ echo $?
255
```

Works for me. Your me. Your error output suggests that you use an older Hugo version, but I'm pretty sure this has worked fine for ... years. I suggest you take further trouble shooting at https://discourse.gohugo.io/

**Comment by McInkay** [comment]
Interestingly, it was an outdated version of hugo, that I hadn't noticed I was using. I was using one of the npm wrappers and it was using 0.45, which is a few months old. After upgrading to 0.51, [it is working correctly](https://circleci.com/gh/YaManicKill/pdd/40) and returning error code 255.

Sorry for bothering you, I should have checked the version first. Thanks for the help.
