### ISSUE TITLE
Feature: check for new version via CLI

### ISSUE THREAD

**Issue by akshaybabloo** [gohugoio/hugo#5496]
It would be nice to have a feature that checks for new Hugo version whenever the CLI is used. Periodically, maybe a JSON file in the users home directory that has a date and grace period to check for new version.

the URL could be something like - https://hugo.io/releases/current or https://hugo.io/releases (for the complete release history.

You could use GitHub releases (you should note that GitHub has a rate-limiting for people who are not logged in) or host one JSON file to Hugo's website (might increase the requests to the website).

**Comment by coliff** [comment]
GitHub also recently added the feature that you can be notified of new releases: 

![new](https://user-images.githubusercontent.com/18592583/49143222-e145e480-f2fa-11e8-8d13-aaa9c6792e37.png)

**Comment by akshaybabloo** [comment]
@coliff yes using that for now.

It's like NPM CLI that checks for updates availability (though it never gave me the right answer).
