### ISSUE TITLE
Give partials the same template inheritance logic as `.Render`

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#5514]
Currently `.Render` is the only way to benefit from the content directory template logic (based on section/type) with partial templates.
But `.Render` requires a Page context and cannot cache its produced markup (à la `partialCache`).

User can devise a way to replicate this complex template inheritance for its partials using `templates.Exists` etc... but I wonder if Hugo could not sport the feature with minimum if no code breaks at all.

### Basic example
```
layouts
├── _default
│   ├──single.html
│   └── list.html
└── recipes
│    ├── single.html
│    └── partials
│        └── sidebar.html
└── partials
         └── sidebar.html
```

With the above layout directory, user could use the same partial call `{{ partial "sidebar" }}` from both `_default/single.html` and `recipes/single.html` and let Hugo check for the existence of an "overriding" partial.

I'm merely bringing this up to start a discussion for it is hard for me, as a user, to grasp its technical complexity.

**Comment by bep** [comment]
I guess this would be ... possible somehow. But in my head, this is what we have base templates for. Admittedly we should improve the "lookup logic" in that area (there is an issue about that somewhere), but I think that if you want to make an argument for the value of this particular feature, I think you need to come up with a better example than a sidebar (which I think fits much better in the `baseof.html` setting).

**Comment by bep** [comment]
Also, I don't think you would get "the same template inheritance logic as `.Render`" without a ... page; that `.Render` cannot determine its layout without knowing the page.

**Comment by regisphilibert** [comment]
> I think you need to come up with a better example than a sidebar (which I think fits much better in the baseof.html setting)

Yes, then widgets. Widgets in this example would us a different markup depending on the type of the page. Because the data of the widget is just a set of fields in the page's Front Matter, I cannot `.Render "widget.htmt"`.

> .Render cannot determine its layout without knowing the page.

Oh yes.... Didn't think about that. It would mean the partial call somehow must guess which section (directory) to look for. Can't think of any safe way for this to be guessed when `partial` is used.

It's a shame, I would love to see the power of `partialCache` brought to any template file.

**Comment by bep** [comment]
> Didn't think about that. It would mean the partial call somehow must guess which section (directory) to look for. Can't think of any safe way for this to be guessed when partial is used.

As I said, what would probably be possible is to use the partial that lives in the "current template section" (I made that up). e.g. `recipes/single.html` => `recipes/partial/foo.html`.

**Comment by regisphilibert** [comment]
Indeed, wouldn't this get too complicated if partial is used inside of another partial ? Having to navigate back to the initial template file's location?
I think shortcodes use the template logic of regular template files, so I suppose if the "root" template file found is a shortcode, you could identify the directory?
