### ISSUE TITLE
Nested Shortcode is parsed as Markdown

### ISSUE THREAD

**Issue by vai0** [gohugoio/hugo#5516]
I have the following block in my markdown file

````
{{% wrapper %}}
### Execute the code below:
```bash
run licensekey --{{< licensekey >}}
```
{{% /wrapper %}}
````

Where `{{< licensekey >}}` is simply `<span class="license-key">[YOUR LICENSE KEY]</span>`
However, after build - the html comes out as 
```
...
&lt;span class=&quot;license-key&quot;&gt;[YOUR LICENSE KEY]&lt;/span&gt;
...
```
rather than the desired
```
...
run licensekey --<span class="license-key">[YOUR LICENSE KEY]</span>
...
```

Wondering if there's a simple workaround or solution to this.

**Comment by bep** [comment]
>Wondering if there's a simple workaround or solution to this.

Yes, there is, but please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
