### ISSUE TITLE
Headless Bundles Not Working?

### ISSUE THREAD

**Issue by jthomerson** [gohugoio/hugo#5517]
Headless bundles seem to have stopped working for me. I recently upgraded Hugo (now on 0.52, can't remember previous version) and now headless pages are showing in the list of paginated results. Here's how to reproduce it:

```
mkdir /tmp/site
cd /tmp/site
hugo new site -f yml .
git init
git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke; echo 'theme: "ananke"' >> config.yml
hugo new posts/my-first-post.md
hugo new posts/my-second-post.md
hugo new posts/my-third-post.md
vim content/posts/my-second-post.md
# ^^^ add "headless: true" to the front matter
```

Am I doing something wrong?

**Comment by jthomerson** [comment]
Here's the version and file:

```
jrthomer@lappy /tmp/site
[ master ] $ hugo version
Hugo Static Site Generator v0.52/extended darwin/amd64 BuildDate: unknown
jrthomer@lappy /tmp/site
[ master ] $ cat content/posts/my-second-post.md 
---
title: "My Second Post"
date: 2018-12-12T23:40:32-05:00
headless: true
draft: true
---
```

**Comment by bep** [comment]
>Am I doing something wrong?

https://gohugo.io/content-management/page-bundles/#headless-bundle

![image](https://user-images.githubusercontent.com/394382/49923297-5563b900-feb3-11e8-806a-b1114d29a880.png)

**Comment by jthomerson** [comment]
Moral of the story: don't ask questions late at night. I read that sentence half a dozen times as "Only leaf _pages_ can be made headless". Was missing that it has to be an entire _bundle_. 🤦‍♂️ Thanks.

**Comment by bep** [comment]
>Moral of the story: don't ask questions late at night.

No problem, I'm also "headless" late at night :-)

**Comment by jthomerson** [comment]
In case someone else stumbles across this looking for an answer to why they can't get headless _bundles_ to work, there's another very slight nuance that I missed in the documentation that if you miss, can easily send you chasing your tail for hours ... *the index filename differs for branch and leaf bundles*. Pay close attention:

 * A _leaf_ bundle (the only kind that can be headless), requires `index.md`, but
 * A _branch_ bundle (e.g. a page type, like `/posts`, etc), requires `_index.md` (note the underscore)

Hope this helps someone.

**Comment by jthomerson** [comment]
Last comment - I swear: see this article, which is helpful: https://forestry.io/blog/data-relationships-in-hugo/
