### ISSUE TITLE
Does not render italics or \$ properly when Markdown is formatted with Prettier

### ISSUE THREAD

**Issue by ndbroadbent** [gohugoio/hugo#5531]
Prettier converts `*` for italics into `_`. [Prettier playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqAwtesAEB3ASxgAscBXKAEzgCcB9AZ0hrhwCMWBDAawZyM4AbAmH5QcACTIBzCKgA6UEABoQEAA4wC0BslCcaNCHgAKBhLpScAbhAKUVIDpzDc4MAMrqXBKNOQwNGRwqsQwALaCAOrERHAM3mBwHhZEBNZEAJ7I4Ay6qr4MtDAmNJzS4ZzIAGZCRaoAVgwAHgBCZa7uHpzhcAAyvnA1dSEgTc0evtKCcACKZBDww4L1IN40RTQ5lTTclMZKquo0vjBR9iTIABwADEdGRVFl6jnH8bTWQ6osAI5kBCxSuVKstVkVwgQAkFRgwpjN5oshkhaitRjBOGxzpRLkgAEyqQKcAjCPyYcIglBQaBfEBkIoAFQxlhRRQAvqygA).

This sometimes breaks the Markdown parser in Hugo.

### Example 1:

**Input:** `*Content with under_score breaks italic in Hugo*`

**Output:** `_Content with under_score breaks italic in Hugo_`

**Result:**

<img width="432" alt="screen shot 2018-12-17 at 10 43 32 pm" src="https://user-images.githubusercontent.com/139536/50097793-3798aa00-024d-11e9-9aae-beef5c068cae.png">

### Example 2:

**Input:** `*Content with [@twitter_username](https://example.com) breaks italic in Hugo*`

**Output:** `_Content with [@twitter_username](https://example.com) breaks italic in Hugo_`

**Result:**

<img width="507" alt="screen shot 2018-12-17 at 11 16 09 pm" src="https://user-images.githubusercontent.com/139536/50099895-c27ba380-0251-11e9-80a7-916c4c27d0bd.png">

I think this might be a bug, because this should be valid Markdown.

Another issue is that Prettier escapes dollar signs, but Hugo/blackfriday still renders the backslash in the HTML. E.g. `$100` becomes `\$100`. I don't really know about the need for escaped dollar signs, but [it might be something to do with MathJax](https://meta.stackexchange.com/a/263344/156701). I think Hugo should handle escaped dollar signs and transform `\$100` to `$100` when rendering.

Related issues:

* https://github.com/prettier/prettier/issues/3837#issuecomment-447893498
* https://github.com/russross/blackfriday/issues/278

**Comment by ndbroadbent** [comment]
I found an [open issue on the blackfriday repo from 2016](https://github.com/russross/blackfriday/issues/278). Just wanted to raise it here as well to get more visibility.

**Comment by ndbroadbent** [comment]
Not sure if Hugo / blackfriday is aiming to meet the [CommonMark specification](https://commonmark.org/), but if so, then these are bugs: 

https://spec.commonmark.org/dingus/?text=_Content%20with%20under_score%20breaks%20italic%20in%20Hugo_%0A%0A_Content%20with%20%5B%40twitter_username%5D(https%3A%2F%2Fexample.com)%20breaks%20italic%20in%20Hugo_%0A%0A%5C%24100.%0A%0A

**Comment by lukehsiao** [comment]
I'm also seeing a related issue where Hugo will transform `**bold text**` correctly, but does not render `*italics*` or `_italics_` correctly, and instead just prints the `*` or `_`.

\*\*bold text \*\* --> **bold text**
\_italics\_ --> \_italics\_
\*italics\* --> \*italics\*
