### ISSUE TITLE
Error: abort: jekyll root contains neither posts nor drafts

### ISSUE THREAD

**Issue by mesibo** [gohugoio/hugo#5536]
We are facing issue importing a fully functional jekyll site to hugo - details below

$ hugo import jekyll ../jekyllproject .
Error: abort: jekyll root contains neither posts nor drafts

$ hugo version
Hugo Static Site Generator v0.52/extended darwin/amd64 BuildDate: unknown

**Comment by cnyyk** [comment]
same issue.

**Comment by moorereason** [comment]
What version of Hugo?  Can you point us to a working jekyll project that reproduces the issue?

**Comment by cnyyk** [comment]
```bash
tree -d
.
├── _includes
├── _layouts
├── _sass
│   ├── base
│   ├── components
│   ├── layout
│   └── libs
├── _site
│   └── assets
│       ├── css
│       ├── fonts
│       ├── images
│       └── js
└── assets
    ├── css
    ├── fonts
    ├── images
    └── js

18 directories

hugo version
Hugo Static Site Generator v0.54.0/extended darwin/amd64 BuildDate: unknown
```

**Comment by PrFalken** [comment]
hugo looks for directories ending with "_posts" or "_drafts" with files in them, and fails if there is none.
It looks like your project only has posts in the root directory.
Is it an expected behaviour in jekyll to have that kind of layout ?

**Comment by cnyyk** [comment]
actually,
some static pages are placed in root folder.
and all posts are placed in _posts.

**Comment by moorereason** [comment]
@cnyyk, it looks like you shared the directory structure of a jekyll theme.  Hugo doesn't import jekyll themes.  It imports _sites_.

Can you point us to a jekyll _site_ that reproduces the issue?

**Comment by cnyyk** [comment]
> Can you point us to a jekyll _site_ that reproduces the issue?

Sorry for reply late.
That theme include a complete jekyll site, not only a theme.

**Comment by eberkund** [comment]
I have the same issue. It seems like the problem is that the import tool only works with [posts](https://jekyllrb.com/docs/posts/) but not [pages](https://jekyllrb.com/docs/pages/)?
