### ISSUE TITLE
Pipe symbol in yaml corrupts syntax highlighting

### ISSUE THREAD

**Issue by JorritSalverda** [gohugoio/hugo#5551]
Although this is an issue in chroma, where I already created https://github.com/alecthomas/chroma/issues/194 I thought it would be good to get this on your radar. 

There's already a fix in their master branch, but no new release yet. If there's a new release perhaps you can update on your side :)

Thanks

**Comment by JorritSalverda** [comment]
Alec Thomas has tagged the fix as version `0.6.1`.

**Comment by bep** [comment]
We're already at 0.6.2:

https://github.com/gohugoio/hugo/blob/34c49d788c102a370006e476d6f6143a51b2a03d/go.mod#L9

**Comment by JorritSalverda** [comment]
Thanks the actual issue I faced is resolved now.
