### ISSUE TITLE
function "reflect" not defined

### ISSUE THREAD

**Issue by pamubay** [gohugoio/hugo#5564]
Trying new template function `reflect.IsSlice` and `reflect.IsMap`, both doesnt work.
```
{{ reflect.IsMap (dict "key" "value") }}
{{ reflect.IsMap "yo" }}

{{ reflect.IsSlice (slice 1 2 3) }} 
{{ reflect.IsSlice "yo" }}
```

Error output:
`function "reflect" not defined`

hugo version:
`Hugo Static Site Generator v0.53-8FC339DC2529FF77E494A1C12CD1FF9FBCB880A4/extended linux/amd64 BuildDate: 2018-12-24T08:38:38Z`

**Comment by bep** [comment]
You are right, there was a missing piece in that implementation. I have disabled the docs for it for now.

/cc @moorereason
