### ISSUE TITLE
hugo server -t still doesn't work

### ISSUE THREAD

**Issue by felicianotech** [gohugoio/hugo#5569]
Running `hugo server -t <a theme>` still doesn't work.

There's several related Issues, some open and some closed:
- https://github.com/gohugoio/hugo/issues/4851
- https://github.com/gohugoio/hugo/issues/4868

This issue goes back to 10 months ago when support for theme config was added.

I haven't been able to track down exactly where the issue is myself, but I did notice that here (https://github.com/gohugoio/hugo/blob/3f3187de0f62107da19d9341aebd1d8414bff0ea/hugolib/config.go#L469) is where the theme passed by the CLI gets lost. If i disable that line, it works as expected though the tests fail.

**Comment by moorereason** [comment]
Pro Top: Reference a specific commit hash when [linking to a line in a file](https://github.com/gohugoio/hugo/blob/a5744697971d296eb973e04e4259fe9e516b908f/hugolib/config.go#L469); otherwise, the link will not work if the file changes in master.

**Comment by tryzniak** [comment]
I've been working on this issue, and looks like soon it's going to be resolved ;)

**Comment by anthonyfok** [comment]
See also #5061 (as in if this bug is fixed, #5061 can be closed too.)  :-)

**Comment by tryzniak** [comment]
Thank you for the nudge! Will take a look
