### ISSUE TITLE
Restore 0.48 slash handling in taxonomies

### ISSUE THREAD

**Issue by JLKM** [gohugoio/hugo#5571]
To me, taxonomies are the main reason, why Hugo stands out from other static site generators. And the ability to handle multi-level taxonomies inly widens the gap.

The latter, I use in a three level geo-tagging (country/region/city) - [further reading](https://discourse.gohugo.io/t/multi-level-taxonomy/4888/8) - example node:
https://udvandrerne.dk/byer/danmark/midtjylland/sabro/

Unfortunately, this feature is no longer available. From [Hugo 0.48](https://discourse.gohugo.io/t/match-taxonomy-paths-to-former-blog-pattern/15624) all slashes in taxonomies seem to be replaced by dashes.

At least that's what happens in the example node, which no longer gets updated at the old url with slashes. Now the example node above is rendered at:
https://udvandrerne.dk/byer/danmark-midtjylland-sabro/

Hence, no more browsing down the hierarchy from posts about a country to posts about a region in the same country and further to a selected city in that region.

In [this post](https://discourse.gohugo.io/t/match-taxonomy-paths-to-former-blog-pattern/15624) multi-level taxonomies with slashes are considered a "hack". Hence Hugo 0.48 fixes this.

But in my opinion, slashes in taxonomies are not a hack. They are awesome!

I would argue, there is a use case for both:
- taxonomies with slashes preserved
- taxonomies with slashes replaced

A suggestion would be to add a setting - say `preserveSlashesInTaxonomies: true/false` or `replaceSlashesInTaxonomies: true/false`, so that Hugo can deliver a perfect fit in both cases.

Otherwise I'll have to revert to Hugo 0.47 and use this version permanently.

https://discourse.gohugo.io/t/multi-level-taxonomy/4888/11,

**Comment by bep** [comment]
Note that something like this would work:

https://github.com/gohugoio/hugo/issues/5513

But I guess that would be unpractical for many levels.

**Comment by bep** [comment]
@JLKM I was just mentioning it; it's not working for 200 countries + regions, I see that.

**Comment by max-arnold** [comment]
This change caused a regression in the previously fixed issue #3577 (PR #5282) - all articles with a `/` in title are again moved to subfolders.

Does it make sense to create a separate issue for this?

**Comment by JLKM** [comment]
Just to eliminate any doubt: The recent reversion in 0.54 to subfolders generated by slashes in taxonomies works absolutely perfect. A unique and brilliant feature has been restored. Thanks for the good work.

**Comment by soulteary** [comment]
@max I was upgrading an old version of the application recently, and I also encountered this problem.

I solved this problem by create a script to make the url address look the same as before.

Maybe you can look forward to this: https://github.com/gohugoio/hugo/issues/5520
