### ISSUE TITLE
Linux snap:  Error: Failed to create dir: mkdir /var/lib/snapd/void/quickstart: permission denied

### ISSUE THREAD

**Issue by deragon** [gohugoio/hugo#5573]
New user trying the quickstart demo on Linux, got the following:

    $ sudo snap install hugo --classic
    $ cd /tmp  # Just an example; any directory out of the home directory would do the trick.
    $ hugo new site quickstart
    Error: Failed to create dir: mkdir /var/lib/snapd/void/quickstart: permission denied

It does work when I run it from my home directory.  But it should work outside of it too.  According to the documentation:

> Hugo-as-a-snap can write only inside the user’s $HOME directory—and
> gvfs-mounted directories owned by the user—because of Snaps’ confinement
> and security model. More information is also available in this related
> GitHub issue. Use sudo snap install hugo --classic to disable the default
> security model **if you want hugo to be able to have write access in other
> paths besides the user’s $HOME directory.**

Either the documentation needs to be changed or better, that the snap be fixed to work as expected.  All my development directories are outside my home directory, on a different partition.  It should be allowed to run hugo from there.

**Comment by felicianotech** [comment]
Based on [this forum thread](https://forum.snapcraft.io/t/is-snap-install-classic-flag-on-user-side-meant-to-override-the-default-published-strict-confinement-or-is-it-a-bug/5531/5) I don't think running `--classic` for strictly confined snaps is fully supported by Snapcraft.

My vote is then we stop suggesting this and remove it from the docs.

**Comment by felicianotech** [comment]
Open a docs PR for this here -> https://github.com/gohugoio/hugoDocs/pull/715

**Comment by sitthykun** [comment]
$ hugo new site quickstart
Error: Failed to create dir: mkdir /var/lib/snapd/void/quickstart: permission denied

it is hugo v0.91.2+extended linux/amd64 BuildDate=2021-12-23T20:50:11Z.
what should I do?
