### ISSUE TITLE
Metadata stripped after import jekyll

### ISSUE THREAD

**Issue by pjw91** [gohugoio/hugo#5576]
Steps to reproduce:

1. jekyll new jy
2. hugo import jekyll jy hugoout
3. less hugoout/content/post/*.markdown

There's no front matter in the output file, only the markdown content.

After git-bisect, it seems that this bugs is introduced in #5324.
More precisely, it works incorrectly since 129c27e.
In that version, hugo panic at `commands/import_jekyll.go:533`; if comments that line out, it output an empty json-front-matter:
```
---
{}
---
content...
```
After the last commit in that issue, there's no front-matter in the output files.

**Comment by Tarek-g** [comment]
hugo import Jekyll: without Front Matter
the Another way to Migrate to Hugo from Jekyll not work ...

**Comment by sheldonhull** [comment]
For windows users, a quick fix that just worked for me as a newer user trying this out: 

```
choco uninstall hugo-extended -y
choco install hugo-extended -y --version 0.49.2
```

Once that's done, you can switch back to latest by just running 
``` 
choco upgrade hugo-extended -y
```

**Comment by astrodad** [comment]
I'm using 0.55.6 and have the same issue, however I am unable to figure out how to use a previous version of Hugo using brew.

**Comment by LindsayHill** [comment]
Same issue still exists with hugo 0.56.3. `brew` doesn't seem to be able to install an older version, so I downloaded a binary from [here](https://github.com/gohugoio/hugo/releases/tag/v0.49.2). That let me do the initial import, then switch to a more recent version of Hugo.
