### ISSUE TITLE
Correct orientation of JPEGs with EXIF rotation

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#5578]
See https://github.com/golang/go/issues/4341 for details of the underlying problem, but in a nutshell, many common image editors avoid lossy recompression of JPEGs by setting an orientation flag in the EXIF metadata of the file. Unfortunately, Go's image/jpeg library still does not correctly handle this as of Go 1.12 beta, but it's a real pain if you have an image that "looks right" in Finder, Safari, etc. but is incorrectly oriented when processed by Hugo.

**Comment by bep** [comment]
#5181
