### ISSUE TITLE
Emphasis tags not being generated in some cases

### ISSUE THREAD

**Issue by vvasuki** [gohugoio/hugo#5579]
Consider the page https://vvasuki.github.io/saMskAra//mantra/agni/rk/divaspari/ , whose source is at https://github.com/vvasuki/saMskAra/edit/master/content/mantra/agni/Rk/divaspari.md . 

Some emphasis markup is rendered incorrectly. For example, 
```
*(प्रतिज्ञा+ऋक्। अग्रिमायाम् उत्तरम्।)*  
वि॒द्मा ते॑ अग्ने त्रे॒धा *{रूपाणि अग्नि-विद्युत्-सूर्यास्}* त्र॒याणि॑  
वि॒द्मा ते॒ सद्म॒ *{नानाकुण्डेषु}* विभृ॑तम् पुरु॒त्रा *(=बहुधा)*।  
वि॒द्मा ते॒ नाम॑ पर॒मं गुहा॒ यद्  
वि॒द्मा तमुत्सं॒ *(=fount)* यत॑ आज॒गन्थ॑ ।
```
generates
![image](https://user-images.githubusercontent.com/2664797/50554869-75e38f80-0c77-11e9-963b-a196a3ba5d44.png), where `=बहुधा` remains unemphasized.

**Comment by mail6543210** [comment]
It seems that it triggers the extension "Intra-word emphasis suppression" of blackfriday.
https://gohugo.io/getting-started/configuration/#blackfriday-extensions
Under `noIntraEmphasis` it reads:
> The “_” character is commonly used inside words when discussing code, so having Markdown interpret it as an emphasis command is usually the wrong thing. When enabled, Blackfriday lets you treat **all emphasis markers** as normal characters when they occur inside a word.

I've raised an issue to blackfriday (514), and wait.
As a workaround, disable that extension shall fix this issue.

However, neither setting the option to `false` or `true` works.

**Comment by mail6543210** [comment]
It seems that it triggers the extension "Intra-word emphasis suppression" of blackfriday.
https://gohugo.io/getting-started/configuration/#blackfriday-extensions
Under `noIntraEmphasis` it reads:
> The “_” character is commonly used inside words when discussing code, so having Markdown interpret it as an emphasis command is usually the wrong thing. When enabled, Blackfriday lets you treat **all emphasis markers** as normal characters when they occur inside a word.

I've raised an issue to blackfriday (514), and wait.
As a workaround, disable that extension shall fix this issue.

However, neither setting the option to `false` or `true` works.

**Comment by vvasuki** [comment]
There are many more such cases. Another example:
```
नानदम्*(३)*॥  
प्र*([ठू])*त्या*(३)*स्मै*(["])* पीपिइषा*([टि]--"३)*ता*(--"३)*इ।

वा*([त]--"३)*इश्वा*(["का]-%%३)*नि वि*(["] ~~मि~~)*दुषॆऎ भा*([का]%)*रा*(")*अ।  
अ*([धी])*रङ्गामा*(["]-"३)*या, जा*(")*अग्म*([टू])*यो*(%)*हाइ।

आ*([कि])*पा*(-v३)*श्चा*(%)*द*(")*अ,ध्वा*([पि]~~घ्वा~~)*नो*(")*वा, ना*([पि])*रों*(")* हाइ*(")*॥
```
leads to the below

![image](https://user-images.githubusercontent.com/2664797/50672283-011c9800-0f8c-11e9-88c0-cdd44b465521.png)

One expects just the stuff in paranthesis to be emphasized (and this is how jekyll rendered).

**Comment by bep** [comment]
You need to create an issue here: 

https://github.com/russross/blackfriday/issues
