### ISSUE TITLE
Multiple emojis in a row are not rendered after the second

### ISSUE THREAD

**Issue by amyspark** [gohugoio/hugo#5580]
Similar to #2391, I've got three emojis in a row that serve as a sort of section separator.
```html
<span aria-hidden="true">{{ ":star2::thought_balloon::star2:" | emojify }}</span>
```
Hugo renders this block as:
```
 🌟:thought_balloon:🌟 
```

If I add a space between the shortcodes, this is what I get:
```
 🌟 💭 :star2: 
```

My Hugo version is (installed via Homebrew):
```
Hugo Static Site Generator v0.53/extended darwin/amd64 BuildDate: unknown
```

**Comment by felicianotech** [comment]
I'm running Hugo v0.53 installed via the Snap.

With `enableEmoji = true` enabled in my Hugo config, I get all three emojis to work without the Go templating code in Markdown:

`:star2: :thought_balloon: :star2:`

In HTML templates, they need to split up:

```
{{ ":star2:" | emojify }}                                                                                                                                             
{{ ":thought_balloon:" | emojify }}                                                                                                                                   
{{ ":star2:" | emojify }}
```
All three will work and be rendered right next to each other.
