### ISSUE TITLE
Hugo default RSSUri maybe typo error?

### ISSUE THREAD

**Issue by mywaiting** [gohugoio/hugo#5593]
Hello:

I currently read hugo's source code and confuse here:  **v.SetDefault("rSSUri", "index.xml")**

code at:  https://github.com/gohugoio/hugo/blob/master/hugolib/config.go#L633

I find all commit history, and find it maybe a typo.

Is it shoule be RSSUri/rssUri instead of rSSUri ? If yes, I will take a PR ASAP. 

Thanks.

**Comment by bep** [comment]
The settings are case insensitive -- but it should be on your form, so PR welcome.

**Comment by mywaiting** [comment]
Ok, I will do it after my work in company. Thanks
