### ISSUE TITLE
Hugo URL property not rendered properly - wrong casing

### ISSUE THREAD

**Issue by juristr** [gohugoio/hugo#5594]
Hi,

I just migrated my blog from Jekyll to Hugo last week. In order to make sure I preserve the correct URLs, in the migration I've set the `url` property for all my migrated posts. This page here (https://juristr.com/blog/2018/05/dynamic-UI-with-cdk-portals) doesn't work however. This is the URL generated by Hugo on my blog archive (https://juristr.com/blog/archive/ => search for "Dynamic UI with"), but clicking on it it doesn't work.

Turns out it is because the `UI` part in the URL needs to be lower case. Is there a way to fix this?

Source: https://github.com/juristr/juristr.github.com/blob/site/content/blog/2018-05-26-dynamic-UI-with-cdk-portals.md

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by juristr** [comment]
@bep Alright, opened it here: https://discourse.gohugo.io/t/using-url-property-has-issues-with-the-url-casing/16242

Added an issue here first because it very much looked like a bug. But fair enough :)
