### ISSUE TITLE
Using --disableFastRender creates a directory as "isableFastRender" is this correct.

### ISSUE THREAD

**Issue by BhaveshSGupta** [gohugoio/hugo#5600]
I am trying to update gitignore file for hugo https://github.com/github/gitignore/pull/2924, when I was trying out --disableFastRender flag a directory was being created as "isableFastRender". I thought of adding this to ignore files. Is this correct?

**Comment by NoahWilcox** [comment]
Oddly enough this just happened to me too.

The cause I believe is by using

-disableFastRender instead of --disableFastRender
