### ISSUE TITLE
Proposal: Allow passing of user defined content in "hugo new [path]"

### ISSUE THREAD

**Issue by rkunze** [gohugoio/hugo#5601]
I would like to have a way to pass (structured) data to `hugo new [path]`, e.g.
```
hugo new example --params '{ "opinion" : "this is a good idea" }'
```
 and then access this data in an archetype:
```
---
title: "{{ replace .Name "-" " " | title }}"
date: {{ .Date }}
draft: true
---
The creator of this page thinks that {{ .Params.opinion }}.
```

My main use case for this is as a building block for a simple edit web API (think "blog comments" here rather than "full-blown CMS"), where a HTTP POST of `{ "comment": "this is awesome!" }` to `/some/path/comment` would result in a call to 
```
hugo new some/path --kind comment --params '{ "comment": "this is awesome!" }'
```
to create a new comment.

But I think this could come in handy for all cases where you need automatic import of existing structured data in a Hugo site: Just write a matching archetype and feed your existing data to `hugo new`.

If you think this is a good feature for Hugo, I'd be happy to implement it and provide a pull request.

**Comment by bep** [comment]
I think you can somehow do this already, but I'm not sure what the syntax would be. Something ala:

HUGO_PARAMS='{ "comment": "this is awesome!" }' hugo new some/path --kind comment

**Comment by rkunze** [comment]
This would be great, but unfortunately it does not seem to work:
```
> hugo config | grep -i params
params = map[disableinlinecopytoclipboard:true themevariant:blue disablelanguageswitchingbutton:true]
```
spits out the params from my `config.toml` (Yes, I'm using the "learn" theme here), but
```
HUGO_PARAMS='{ "comment": "this is awesome!" }' hugo | grep -i params
```
comes up empty. I.e. setting 'HUGO_PARAMS' _does_ something (it nukes the `params` config entry), but as far as I can see it does _not_ pass anything along to Hugo.

I've tried some other variants (like `HUGO_TEST=something`, `HUGO_PARAMS.TEST=something` etc.), but no joy. What _does_ work is passing in "official" config variables as documented, e.g.
```
> HUGO_TITLE=foobar | grep -i foobar
title = "foobar"
```
Any hints on where to search further? Or should I try to fix/change Hugo so that setting `HUGO_PARAMS` works as outlined above?

**Comment by bep** [comment]
Two things:

* Viper, the config lib we use, allows to set set single settings via OS env, e.g `HUGO_THEME=hyde`. I'm pretty sure that example works.
* At some point I merged a PR allowing maps to be set via JSON strings, but I have not tested that myself.

But what I would like out of this is that we don't add another special `--params` flag, but figure out how we can set "any" config map via OS env.

**Comment by rkunze** [comment]
After some more tests it turns out that passing json in HUGO_PARAMS _does_ work after all. With `archetypes/test.md` as
```
{{ .Site.Params }}
```
and an empty `content` directory, 
```
HUGO_PARAMS='{ "test": "foo", "bar" : "baz" }' hugo new test.md --kind test
```
creates a `content/test.md` with this content:
```
map[mainsections:<nil> test:foo bar:baz mainSections:<nil>]
```

As per the Viper docs, setting HUGO_PARAMS in the environment overrides the `params` settings from lower priority sources, i.e. the `params` values from the config file(s) do not show up here, but I can live with that for my use case.

I'd be happy to write a PR for the Hugo docs documenting this - do you want one?
