### ISSUE TITLE
Builds slow for large sites

### ISSUE THREAD

**Issue by billhennessy** [gohugoio/hugo#5602]
Hugo isn't very fast building and deploying large sites because it regenerates every file. For my site, that over 8,000 files. Even tiny changes take 30 to 60 minutes on Netlify.

I'd like to see either a) a workaround (file structure perhaps) or b) an incremental build. 

Thanks

**Comment by tryzniak** [comment]
Does running `hugo --templateMetrics` show anything extraordinary?

**Comment by bep** [comment]
The initial statement isn't accurate in general. 8000 files should build fine "in seconds" (depends). This means, most likely, that you something ineffective in the templates. The forum is a better place to do troubleshooting: https://discourse.gohugo.io/

**Comment by billhennessy** [comment]
Locally (MacBook Pro w/ 16 GB on MacOS 10.14.2)

Template Metrics:

     cumulative       average       maximum
       duration      duration      duration  count  template
     ----------      --------      --------  -----  --------
  40.270080688s   26.563377ms    67.14826ms   1516  _default/list.html
   5.527900193s    1.436564ms   12.157416ms   3848  _default/taxonomy.html
   4.846863364s    1.598569ms   26.386551ms   3032  _default/single.html
   4.657895478s     211.539µs    6.370487ms  22019  _default/summary.html
   2.457651305s     292.682µs    10.81169ms   8397  partials/head-meta.html
   2.423383672s      96.958µs    6.163546ms  24994  partials/meta-terms.html
   1.153518806s     137.372µs   23.409309ms   8397  partials/sidebar.html
   1.131222798s     343.627µs    6.631664ms   3292  _internal/_default/rss.xml
   212.012927ms      96.238µs     2.72241ms   2203  partials/pagination.html
    170.38404ms      56.195µs    1.396998ms   3032  partials/sharing-icons.html
   161.767951ms  161.767951ms  161.767951ms      1  _internal/_default/sitemap.xml
   115.375768ms       13.74µs    1.314634ms   8397  partials/search.html
    86.626434ms   21.656608ms   23.051916ms      4  partials/recent.html
    11.244612ms       1.339µs     101.627µs   8397  partials/head-custom.html
     1.351558ms    1.351558ms    1.351558ms      1  404.html
      531.466µs     531.466µs     531.466µs      1  _internal/shortcodes/youtube.html
       33.958µs      33.958µs      33.958µs      1  robots.txt


                   |  EN
+------------------+------+
  Pages            | 9618
  Paginator pages  | 2072
  Non-page files   |   27
  Static files     |   16
  Processed images |    0
  Aliases          | 3292
  Sitemaps         |    1
  Cleaned          |    0

Total in 20678 ms


Bill Hennessy
whennessy0725@gmail.com
