### ISSUE TITLE
Shorten "No layout found" Warning

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#5607]
Following https://discourse.gohugo.io/t/error-warning-for-missing-template-that-does-exist/15287

I personally tend to think this warning is a bit verbose, so verbose that I suspect most people miss its meaning despite its helpfulness and don't address it.

I suggest it is reduced to simply mention the output format and page kind concerned:

```
WARN 2018/11/13 18:54:15 Found no layout file for output format "JSON" on "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

**Comment by XhmikosR** [comment]
Maybe also link to a docs page which shows this info?

**Comment by regisphilibert** [comment]
I don’t know how links behave in warnings and if url evolves the warning needs fixing...

I think that if _Hugo Lookup Rules_ is capitalized people will instantly identify it as the right thing to look for in the doc.
