### ISSUE TITLE
Image resource .Title defaulting to filename?

### ISSUE THREAD

**Issue by tashian** [gohugoio/hugo#5609]
I'm not sure if this is a docs issue or a bug.

In the [docs for Page Resources](https://gohugo.io/content-management/page-resources/), the default Title property value is stated as blank

But in v0.53, when I don't supply a title for a resource in the front matter, the default value of .Title for the resource seems to be the filename of the resource. In my case, I'm using title as a way of specifying cover image captions, and I'd like for it to be blank by default.

Here's the template code I'm using for my cover images:

```
    {{ $img := (.Resources.ByType "image").GetMatch "cover" }}
    {{ with $img }}
      <figure>
          {{ $big := .Resize "1232x" }}
          {{ $small := $big.Resize "616x" }}
          <img srcset="{{ $small.RelPermalink }} 1x, {{ $big.RelPermalink }} 2x" alt="{{ $img.Title }}" width="{{ $big.Width }}"  class="mw-100">
          <figcaption>{{ $img.Title }}</figcaption>
      </figure>
    {{ end }}
```

**Comment by bep** [comment]
>I'm not sure if this is a docs issue or a bug.

I'm pretty sure the `Title` has always had this default value.

/cc @regisphilibert

**Comment by regisphilibert** [comment]
Mmm... In my blog post which is anterior to the doc, I mention `.Title` and `.Name` both default to the base filename. Not sure why the doc says different considering I wrote it way back when but this should be fixed indeed.

In any case your test before outputing `$img.Title` could be as simple as:
```
{{ if not eq .Name .Title }}
I have a custom Title
{{ end }}
```

**Comment by regisphilibert** [comment]
Done: https://gohugo.io/content-management/page-resources/

This can be closed.

**Comment by tashian** [comment]
Yay! Thanks. :D
