### ISSUE TITLE
Add flag for showing publish date with hugo list future

### ISSUE THREAD

**Issue by danielcompton** [gohugoio/hugo#5610]
I'd like to build tooling to automatically publish future dated posts once they become current posts. `hugo list future` prints a list of all future dated posts, but not their publish dates. Would a PR be accepted that added a flag to include the publish dates?

**Comment by bep** [comment]
>Would a PR be accepted that added a flag to include the publish dates?

No flag, but adding publishdate to the default output would be fine. Maybe adjust it to some common machine-readable format, CSV?
