### ISSUE TITLE
The global var `site` does not work for mixed-case Params

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#5615]
The bug is as the title says.

Here's a minimum working example:

### `config.toml`

```
baseURL = "http://example.org/"
languageCode = "en-us"
title = "global site var bug"
theme = "test-theme"

[Params]
  # recognized by Hugo
  mainSections = ["posts", "notes"]
  # my custom param
  feedSections = ["posts"]
```

### `index.html`

```
{{ printf `site.Title = %#v <br>` site.Title | safeHTML }}
{{ printf `$.Site.Title = %#v <br><br>` $.Site.Title | safeHTML }}

{{ printf `site.Params.mainSections = %#v <br>` site.Params.mainSections | safeHTML }}
{{ printf `$.Site.Params.mainSections = %#v <br><br>` $.Site.Params.mainSections | safeHTML }}

{{ printf `site.Params.feedSections = %#v <br>` site.Params.feedSections | safeHTML }}
{{ printf `$.Site.Params.feedSections = %#v <br>` $.Site.Params.feedSections | safeHTML }}
```

Above prints:

```
site.Title = "global site var bug" 
$.Site.Title = "global site var bug" 

site.Params.mainSections = []interface {}{"posts", "notes"} 
$.Site.Params.mainSections = []interface {}{"posts", "notes"} 

site.Params.feedSections = 
$.Site.Params.feedSections = []interface {}{"posts"} 
```

Note that `site.Params.feedSections` doesn't return the expected value.

**Comment by kaushalmodi** [comment]
Here's a repo with the above minimum workable example: https://gitlab.com/hugo-mwe/hugo-issue-5615/

1. Clone the repo
2. cd to the dir
3. Run `hugo`

And you will get:

![image](https://user-images.githubusercontent.com/3578197/51340912-2e724700-1a5e-11e9-8827-0fa4f5f78c58.png)

**Comment by bep** [comment]
A bug, alright, but I'm prettu sure that:

```bash
site.Params.mainsections
```

Would work.

**Comment by kaushalmodi** [comment]
> A bug, alright, but I'm pretty sure that:

> site.Params.mainsections

> Would work.

`site.Params.mainSections` (internal param) already works.

Let me try `site.Params.feedSections` (custom param).

**Comment by kaushalmodi** [comment]
I confirm that the mixed case is not supported only for the custom parameters:

![image](https://user-images.githubusercontent.com/3578197/51404962-f254ea00-1b22-11e9-9b73-01a009167abc.png)
