### ISSUE TITLE
Allow user-defined HTTP headers with getJSON and getCSV

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugo#5617]
As suggested in #3395 "Add an HTTP Accept header when downloading JSON", it would be nice if one could add user-defined HTTP headers with getJSON and getCSV, especially the case when some kind of token is needed for authorization, e.g., as described on https://docs.tcgplayer.com/docs/getting-started where a `Authorization: bearer BEARER_TOKEN` HTTP header is required for access.

**Comment by moorereason** [comment]
@roya3000,
I see your edit, but I want to make it clear to anyone reading this issue that your proposal would break the existing API by making the headers required for every invocation (ie. `{{ getJSON "" $url }}`).  That's not going to work.

**Comment by urbantrout** [comment]
This would be a nice feature. Especially in combination with authentication headers.

**Comment by bep** [comment]
This issue has been brought back to life with https://discourse.gohugo.io/t/getjson-http-authorization-request-header/31795/9

So, while we should really implement a proper `resources.GetRemote` with an API that does all of the above, too, we kind of also need to fix these existing methods so people can use this now.

I mostly agree with @almmiko above.

I suggest however that we do:

```go
func (ns *Namespace) GetJSON(args ...interface{}) (interface{}, error)
```

And then check if the last element is a `map[string]interface{}` (which then becomes the headers). You would then do:

```
{{ $json := getJSON "https://example.com/my.json" (dict "myheader" "myheadervalue") }}
```
Or (demonstrating the little bit clumsy API), without any headers:

```
{{ $json := getJSON "https://example.com" my.json"}}
```

**Comment by chamberlainpj** [comment]
Could I be assigned to this issue?

**Comment by bep** [comment]
@chamberlainpj done.

**Comment by atishay** [comment]
Instead of headers, it might be better for the last option to be a dictionary with header as a key. That way we can specify method (PUR/POST/DELETE) and maybe JSON based data. Very useful to invalidate the CDN during build.

**Comment by davidsneighbour** [comment]
> Instead of headers, it might be better for the last option to be a dictionary with header as a key. That way we can specify method (PUR/POST/DELETE) and maybe JSON based data. Very useful to invalidate the CDN during build.

I am not sure if you maybe misunderstand what this issue is about. When the request is sent, users want to add headers to the request. But that won't change the type of the request (GET). Adding POST/PUT/DELETE will require a second request in addition to the original and that is not something this function will be prepared to do.

**Comment by atishay** [comment]
> > Instead of headers, it might be better for the last option to be a dictionary with header as a key. That way we can specify method (PUR/POST/DELETE) and maybe JSON based data. Very useful to invalidate the CDN during build.
> 
> I am not sure if you maybe misunderstand what this issue is about. When the request is sent, users want to add headers to the request. But that won't change the type of the request (GET). Adding POST/PUT/DELETE will require a second request in addition to the original and that is not something this function will be prepared to do.

PUT or POST is not a second request. It is the same request. Here we default to GET right now. Adding Headers is a half measure. Full HTTP support means being able to do PUT and POST as well. We can do headers now and then come back later to add support for POST if that feels like a better solution.

**Comment by davidsneighbour** [comment]
It's hard to explain what I am trying to explain. I think that "getting" a JSON or CSV file is per se a GET request. Adding some form of "header" request to turn it into another type of request is not what this PR is about. Adding more information to the headers to this GET request is what this is about. Sure doing PUT and POST and DELETE would be nice, but that won't be something to "extend" a GETjson request. There is no retrieving of JSON or CSV via PUT/POST/DELETE in this use case. 

Does it make sense to have these functions? Sure. But that's not within this particular feature request. That's all I am saying :) "allow user defined headers with getjson and getcsv" is the title.

**Comment by atishay** [comment]
Ok. No problem. Will still be waiting for ‘GetRemote’
