### ISSUE TITLE
Feature Request: Add front-matter variable for redirecting article to external URL

### ISSUE THREAD

**Issue by purrloftruth** [gohugoio/hugo#5621]
## Summary
A front-matter variable that, when set, will set the permalink for an article to the provided off-site URL instead, and not otherwise build the page; and a page variable that can be used by theme authors to tell if any given page has set that front-matter variable.

# The Problem
I’m working on a website that uses sections to structure specific types of content I’m working on. Some of the specific content in question, I don’t want to have as pages on my site, but as links to external websites that already house the content (e.g., if a story I’ve written is published by some other venue). I see a few different ways of tackling this problem with the current version of Hugo:

1. Put external links in a dedicated article specifically for external links
2. Create articles for each link, and have an extra click out to each external link
3. Create articles for each link, and create a layout that automatically redirects to the external link

Each of these approaches has at least one drawback:

1. A dedicated article for external links pulls them out of the same flow that other members of that content type are kept in and makes it harder to keep all of that content type easily organizable; we lose the ability of Hugo to sort by front matter, etc.
2. Here, we can still use front matter, and add special information on the list pages with all the information we’d want to present, but the links to articles that *are* on-site go straight to the article, and asking users to click an extra link for off-site articles creates more friction.
3. This has the best effect for the end-user, and we can still add all the special information we need to the front matter, but no matter how we actually accomplish this in our layouts, it would have to generate an extra page that is otherwise worthless, and would require us to code and use an extra layout in our theme that would be both theme-specific and require extra work up-front for any other given site developer who wants to do the same thing.

To summarize: even though the effect we want to achieve can be accomplished through extensive templating, doing so comes at the costs of writing extra theme-specific templating that could otherwise be simplified or avoided, and causing otherwise unnecessary pages to be built at compile time.

# The Proposal
I’m proposing support for an external URL redirect predefined variable to be added to the front matter. It should simply expose that URL as the permalink for the article, and not generate a page on site. (Articles that have this variable set should still be able to legally have content, even though they wouldn’t generate a page — let’s say you keep the contents of the article in the file anyway, and the site that originally housed the article goes down; you’d be able to easily remove your redirect and simply have it on your own website again. You could also, for instance, put the summary on your list pages...)

Considering this provides an off-site url, there should probably also be a page variable added that theme authors can query to tell whether or not a particular page is using an off-site URL or not (will be great for those `target="_blank" rel="noopener noreferrer"`s or whatnot, unless we can add them automatically somehow, which I'm not sure about).

What I don’t have is a proposal for exactly what these variables should be called (considering there are already variables called “url” and “aliases” that do similar but distinct things) or the best way to implement this. (I don't know if calling it a "redirect" is the right thing if the implementation is just changing the permalink...) However, if those smarter than me are able to hash those implementation details out here, and if the people who run the project can give some insight on whether this would be a reasonable first contribution, I’m willing to commit to buckle down and learn enough Go (which I, admittedly, haven’t touched at all yet) to contribute this feature myself (keeping in mind those *if*s; I have no idea what I’m doing with Go quite yet and don’t want to do things in a un-Go-like or an un-Hugo-like way).

Looking forward to hearing your thoughts. Thanks for your time, and I hope you and your families are well!

**Comment by thewebmastercom** [comment]
This is doable via templating. I suggest taking the discussion to the forum.

**Comment by purrloftruth** [comment]
> This is doable via templating.

In case it was unclear from what I'd originally written, I've edited my original post to add clarification on why this method is unsatisfactory.

> I suggest taking the discussion to the forum.

I will do that soon. I had thought this was a more appropriate venue.

**Comment by purrloftruth** [comment]
I'm going to make a comment to leave this open, as it's been referenced in another issue. I'm working on a forum post to solicit further feedback, in which I'm going to link this issue, and I'll link here once it's ready. Thanks for your patience.

**Comment by purrloftruth** [comment]
For the time being, since headless bundles have come into being since the time of this feature request, I'm going to attempt to implement it on my site using that. Depending on how successful I am, I may or may not re-open this issue.

**Comment by yuqiliao** [comment]
Just wanted to leave a note to echo the need as documented clearly in the the original post. If this feature is not added, in case anyone is searching for this feature in the future, they may find the following two resources helpful.
reference: https://discourse.gohugo.io/t/how-can-i-redirect-to-an-external-link-on-click-of-header-of-any-blog/9886/5
reference2: https://blog.concannon.tech/tech-talk/hugo-canonical-url/
