### ISSUE TITLE
highlight shortcode should allow optional caption 

### ISSUE THREAD

**Issue by pjebs** [gohugoio/hugo#5624]
It would be great if highlight shortcode allows optional caption at the bottom.

That way we can write code snippets and caption it with the file name.

**Comment by pjebs** [comment]
Still relevant

**Comment by pjebs** [comment]
It is definitely still relevant.

**Comment by looeee** [comment]
Second this. I want to be able to add a caption with the filename since I'm referencing multiple modules one after another.

**Comment by pjebs** [comment]
Does anyone know a workaround?

**Comment by looeee** [comment]
> Does anyone know a workaround?

Write your own highlight shortcode. This on on my todo-list, but it's a very long list at the moment!

However, I think that something like this would work (warning, untested code):

### shortcodes/customHighlights.html

``` 
{{- $caption := .Get "caption" | default "" -}}
{{- $lang := .Get "lang" | default "js" -}}
{{- $options := .Get "lang" | default "js" -}}

{{- $code := .Inner -}}

<div class="custom-highlight">
   {{- highlight $code $lang $options -}}
   <span class="highlight-caption">
      {{- $caption -}}
   </span>
</div>
```

### To use:

```
{{< customHighlight caption="Testing" lang="js" options="linenos=table,linenostart=4,hl_lines=1-3" >}}
// some code here 
{{< /customHighlight }}
```

**Comment by pjebs** [comment]
Still relevant

**Comment by pjebs** [comment]
Still relevant because it'd be so useful for many people.

**Comment by pjebs** [comment]
Still relevant because it'd be so useful for many people.

**Comment by davidsneighbour** [comment]
Overwrite the shortcode via `layouts/shortcodes/highlight.html`. Retrieve the internal shortcode, then add your changes. Because you need that feature it's not a reason to keep developer resources busy and issues open. It CAN be solved easily so let them do other stuff (like fixing bugs). You don't even need to name it `customHighlight.html` as suggested above by @looeee, just use the internal shortcode's name in your own shortcodes directory.

**Comment by looeee** [comment]
> You don't even need to name it customHighlight.html as suggested above by @looeee, just use the internal shortcode's name in your own shortcodes directory.

Yeah, this is now the correct approach. However, I think that's a recent addition and wasn't possible (or I hadn't learned about it) when I made my comment above.
