### ISSUE TITLE
no way to escape shortcode syntax

### ISSUE THREAD

**Issue by pjebs** [gohugoio/hugo#5625]
I am using Syntax highlight shortcode.

My syntax inside is actual hugo shortcode syntax.
There is no way to escape it so hugo parses the shortcode syntax instead of displaying it as it should be.

I also tried with ```     but nothing is displayed.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
