### ISSUE TITLE
Minor regression in Emoji detection

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#5635]
Hello,

I was browsing one of my old posts when I realized that Hugo had stopped rendering `:+1:` as 👍 .

Going through the commit history, I found this recent commit: https://github.com/gohugoio/hugo/commit/9cd54cab20a03475e34ca462bd943069111481ae#diff-2b6430ca571aa476215d342bcbb4d624R226

```
	if !isAlphaNumeric(r) {
			break
```

AFAIK all the emojis from https://www.webfx.com/tools/emoji-cheat-sheet/ are supported by the library that Hugo uses for Emoji parsing. The only failing corner cases in there, I think (haven't looked at each of those codes), are `:+1:` and `:-1:`. 

Can you add `+` and `-` to the valid range of Emoji characters?

**Comment by kaushalmodi** [comment]
I completely missed the underscores .. because they also won't be covered by `isAlphaNumeric`. The underscore case itself will break a lot of cases like `:christmas_tree:` (:christmas_tree:),  `:heart_eyes:` (:heart_eyes:), etc.

**Comment by anthonyfok** [comment]
Actually, `isAlphaNumeric` in parser/pageparser/pagelexer.go does cover the underscore, so the only characters/runes missing are `+` and `-` (hyphen).

**Comment by kaushalmodi** [comment]
@anthonyfok Though I tested that the emojis with underscores in my earlier comment did not work.

**Comment by anthonyfok** [comment]
> @anthonyfok Though I tested that the emojis with underscores in my earlier comment did not work.

Strange... But `:christmas_tree:` does work for me here with Hugo 0.53.

**Comment by kaushalmodi** [comment]
@anthonyfok Odd. Though, thanks for fixing this! I'll rebuild Hugo later and verify.

**Comment by kaushalmodi** [comment]
@anthonyfok I confirm this fix (emojis with `_`, `+`, `-`). Thank you!
