### ISSUE TITLE
Allow nested fields in where clause

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#5637]
Currently the following:

```
{{ $pages := where .Site.RegularPages ".Params.author.name" "John" }}
```
Returns an error. 

Maybe this is similar enough to #5522 that it can be treated in the same timeframe/by the same person.

**Comment by bep** [comment]
I agree that this should just work, but I think I created a very similar issue some time ago, but that doesn't matter too much.

**Comment by tryzniak** [comment]
I'm working on this one. I think this issue is related to #5416.
