### ISSUE TITLE
menus: simplify user experience by removing need for weights

### ISSUE THREAD

**Issue by gcushen** [gohugoio/hugo#5644]
Currently, I understand that `weight` must be specified for each menu item in `menus.toml` to define the order that menu items appear in, otherwise Hugo **defaults to ordering menu items alphabetically**.

To **simplify the user experience** and make it **more intuitive** (especially for new users), can we **consider defaulting menu order to the order that the menu items are defined in**? This would allow us to simplify `menus.toml` by removing the `weights` parameters for typical use cases.

Apologies if I missed anything :)

**Comment by bep** [comment]
A menu is (in most cases) not just 1 list (menu definitions can live in both site config and in page front matter) - and if you want to merge 2 lists you need a sort order.

**Comment by gcushen** [comment]
I think your comment actually strengthens this proposal for **improving the user experience** by simplifying the menu system for beginners as you just highlighted the complexity of the current menu system for a beginner trying to learn to create their main menu.

It's great to have flexibility for advanced users, but **beginners** can and do get overwhelmed, especially as you highlighted - there are multiple approaches to creating menus.

In my experience, one of the first things a beginner wants to do when learning to use a Hugo theme is to create **one** menu at the top of their site using **one** approach (the simplest approach).

First impressions will dictate whether a user sticks with trying to learn Hugo or moves on to a competing product, so why not take the opportunity to improve the user experience by making a relatively small change to essentially not require the user to enter menu `weights`. If no `weight` is set, Hugo could automatically determine the menu order according to the order which the parameters are defined in.

Academic has encouraged a huge number of academics and students to adopt Hugo and many are not from a computer science background. To help attract more of this kind of audience and also to keep existing users in this segment happy, I'm sure these kind of improvements to the user experience will have a nice impact :)
