### ISSUE TITLE
Vim swap files cause hugo to fail

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [gohugoio/hugo#5646]
Opening configuration in vim causes hugo development server to fail with 
```
<...>config/_default/.menus.toml.swp" is not a valid configuration format
```

Possible solution would be to ignore hidden files.

**Comment by tryzniak** [comment]
Maybe we should just read files with extensions that config files support and ignore all others.

**Comment by fberrez** [comment]
Currently writing a fix for this issue.

I am not sure how you had that. Could you let us know how to reproduce this issue?

**Comment by tryzniak** [comment]
Clone [this](https://github.com/bep/hugotest) project, then do `mkdir -p config/_default && touch config/_default/blah.swp` and run `hugo server`. You should see the error.
