### ISSUE TITLE
Bring "case insensitive" sorting to Hugo

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#5661]
It is currently not possible in Hugo to sort things in a "CMS" sensible way due to sorting being case sensitive. 

For ex:
```
{{ range sort (slice "Apple" "aSomething" "Zoo" "Gravy") }}
{{ . }}<br>
{{ end }}
```
will output:
```
Apple
Gravy
Zoo
aSomething
```
Same with `.ByTitle` etc...

I personally can't think of a sorting use case where case sensitivity has value, but this does not matter much if we're facing a Go limitation as the following threads imply.

https://discourse.gohugo.io/t/sort-posts-by-title-case-insensitive/6076
https://discourse.gohugo.io/t/sorting-posts-by-title-case-insensitive/2413

Though maybe some has changed since then and this behaviour could now be aligned with the majority of content sorting use cases' need.

**Comment by bep** [comment]
> "CMS" sensible way

What do you mean by this? Does it take language into account?

**Comment by regisphilibert** [comment]
> What do you mean by this? Does it take language into account?

I mean the way we often sort content. It takes into account languages using cases I guess, which excludes a lot non-european languages. 

But if the point is we should keep both ways of sorting, then by all means yes!

I think many users need "case-insensitive sorting" in Hugo, and that's why I started this issue.

**Comment by bep** [comment]
>But if the point is we should have both ways of sorting, then by all means yes!

I think we need to take this in (baby) steps. We need to properly integrate timezone/locale and with that string collation, but that is a bigger task. Implementing string sorting using unicode case folding would definitively be an improvement. So we start there.

**Comment by bep** [comment]
I assigned this to myself. I have a sketchy implementation somewhere -- but I need to wait until I get my refactoring branch merged (I have moved the page sorting to a different package).
