### ISSUE TITLE
Missing Videos on Quickstart page

### ISSUE THREAD

**Issue by BruceEckel** [gohugoio/hugo#5671]
On https://gohugo.io/getting-started/quick-start/

![image](https://user-images.githubusercontent.com/1001900/52166563-1dffd480-26cc-11e9-8c5d-4ac3843a73a0.png)

**Comment by bep** [comment]
OK ... I never read anything about "automatic archival" when I created these videos. And they have been live for years, way longer than 7 days ... I will look into this.

**Comment by dv-brianmickel** [comment]
This feels relevant:
"The above warning message is already active on asciinema.org, however actual archival is not enabled yet. We’re planning to enable archival on 31st January 2019. On that day all existing unclaimed recordings will be archived, and all new ones that are not claimed within 7 days from upload will be auto-archived (daily)."
https://blog.asciinema.org/post/archival/

**Comment by peaceiris** [comment]
cf. ["This recording has been archived" messages in quick start page · Issue #735 · gohugoio/hugoDocs](https://github.com/gohugoio/hugoDocs/issues/735)
