### ISSUE TITLE
hugo -t ignored when theme set in config.toml

### ISSUE THREAD

**Issue by khimaros** [gohugoio/hugo#5679]
Create a hugo project with a config.toml and a theme defined. Attempt to temporarily override the theme with `hugo -t`, the theme in config.toml is still honored.

**Comment by tryzniak** [comment]
Interesting. I used to think I resolved this bug in #5603 . What version of Hugo are you using?

**Comment by khimaros** [comment]
Built from HEAD about 2 hours ago. Note I am not using `hugo -t server`, just `hugo -t` to generate statically. I tried also with `--noCache --gc --cleanDestinationDir` to no avail.

**Comment by tryzniak** [comment]
I'll give it a look. Thank you!

**Comment by tryzniak** [comment]
Are you building the site with `hugo -t` and then serve it with `hugo server`?

**Comment by khimaros** [comment]
Nope. Building the site with `hugo -t` and then serving with nginx.

**Comment by nonumeros** [comment]
If no theme is set on the config file, then I would expect `hugo -t theme -D` to be honored as soon as `hugo serve` is called thereafter. 

Regardless if theme was set on the config file or not.

And you're correct, a theme set on the init file will override everything else.

When I'm in doubt, a hard refresh is all that may be needed under chrome or chromium.

**Comment by khimaros** [comment]
My preference would be to honor the `-t` flag for build even when a theme is specified in the config.

The command line flag seems to make sense as an expression of intent from the user.

**Comment by nonumeros** [comment]
> honor the -t flag for build even when a theme is specified in the config

the way I see it this is more of an either-or and not both basic scenario. And although I do agree with you, then again, what is the point of having a configuration file with a writable theme on it. Non sequitur at its finest. You could rollback to earlier versions and see the problem for yourself. This is of course with the `serve` flag accompanied by `theme` locally.  If I had to guess, this is more of an nginx configuration problem than hugo.

**Comment by khimaros** [comment]
The idea is that the config specifies default values, but parameters can be overridden by explicit user intent (command line flags). It's a relatively common pattern. Consider ~/.vimrc where you may `set lisp off` but invoking with `-l` overrides it to `on`.

I'm not sure I follow re: nginx. I've confirmed this is not a caching issue. The content of the files (on disk) is not updated to match the theme specified by `-t` on the command line.

**Comment by nonumeros** [comment]
> Consider ~/.vimrc where you may `set lisp off` but invoking with `-l` overrides it to `on`

Good point. 

> I'm not sure I follow re: nginx. I've confirmed this is not a caching issue.

Every malady in Hugo has stemmed from caching issues.
