### ISSUE TITLE
themes use inconsistent param field names and data/

### ISSUE THREAD

**Issue by khimaros** [gohugoio/hugo#5680]
Initially I was very excited by hugo's simple configuration and large variety of themes. I was hopeful that switching between themes would be as simple as modifying the theme name in the config and rebuilding.

However, it has become clear that most themes use different parameter fields to represent the same concept. Some themes use `tagline`, others use `description` or `title`. Some themes use top level params for github username, facebook username, etc, some use a nested `params.social` category for setting these. Some themes pay attention to `menu`, some don't. Some themes require manually copying images into static/ and `avatarurl` ... the list goes on.

The end result is that themes are not compatible with one another in the way one may grow used to with systems such as Ghost or Wordpress.

**Comment by budparr** [comment]
I think this is a very good point. There have been prior discussions here about vetting themes. There is a guideline for theme development, but I don't think it covers such things as common patterns. Also, because Hugo is ~0.5 there has been quite a bit of change over the last couple of years, so a theme created some time ago might not be using patterns present now.

**Comment by khimaros** [comment]
I suspect having some patterns documented, even a nice skel dir that theme developers could start from, would be helpful. Maybe themes that follow those patterns to the T could be given a special tag in the theme directory for extra visibility.

**Comment by khimaros** [comment]
i believe this issue is still relevant

**Comment by davidsneighbour** [comment]
People buy cars. Then they put air fresheners in. Those hangers on the mirrors, you know. I don't get why some people use pine, I like strawberry. I think it should be standardised to strawberry. Nobody should be allowed to switch their air freshener to pine.

cars = hugo
air fresheners = themes
scents = variables

Same same.

I believe this issue is not relevant, but personal preference. :(

**Comment by khimaros** [comment]
i think it creates a significant usability hurdle, as learning the specific incantations of each theme takes time. it would be helpful for hugo to define a common taxonomy for configuration values which theme developers could standardize on.

**Comment by davidsneighbour** [comment]
Please rethink that. A theme is an individualisation of the output of Hugo. The moment where Hugo restricts variables to a naming structure is the moment, the developers of Hugo have to be responsible of what happens in a theme, not the theme developers. Then "external" theme developers will not be able to create themes anymore. It's kind of a Microsoft Sharepoint situation where you can change the header image and the background color and the font. 

Everything in [params] is parameter-work for theme developers and "unregulated". Just try searching for the famous [author] config section. That is a sample of pseudo-regulated variable names. They are ruled, but not really. Some themes use them, others don't. 

If you want a website that looks like any other website and has just some individualised colors and images - then it makes sense. For for the broad use of Hugo it's not something you will ever see coming into live. Hugo creates a site. Theme developers make them look nice. If you have a problem with the way theme devs do things then take it up with them, don't try to limit possibilities.

**Comment by khimaros** [comment]
i didn't intend to advocate for restricting variables or limiting possibilities. i'm suggesting a well lit path for theme devs. there are many common patterns used across themes, but each theme implements them in a different way.

i understand that this is a hard problem to solve. i also believe there are ways to improve usability while remaining flexible.

the simplest solution to this problem is theme dev documentation. provide a list of best practices, config parameters which are used by many themes for a particular purpose.

another, more complex, solution is to show theme features in the theme index by their use of well-known config params. this would provide an incentive but not limit flexibility.

**Comment by khimaros** [comment]
as i think about this more, i prefer the latter solution, as it provides the right incentives for theme developers without forcing their hand. it could also improve discoverability.

to put my money where my mouth is, i've done some early exploration.

start with a local checkout of hugoThemes:

```
$ git clone --recurse-submodules https://github.com/gohugoio/hugoThemes

$ cd hugoThemes
```

count distinct parameters across all themes, ignoring duplicates within a single theme:

```
$ egrep -or '\.Param "[^"]+"' . | sed -r 's/^[^\/]+\/([^\/]+)\/[^\:]+/\1/g' | sort | uniq -u | wc -l
253
```

count of parameters used only once in any theme (note, this under represents the problem, as this would exclude parameters which are used twice in the same theme):

```
$ egrep -or '\.Param "[^"]+"' . | sed -r 's/^[^\/]+\/([^\/]+)\/[^\:]+/\1/g' | sort | uniq -u | cut -d: -f2- | awk '{ print $2 }' | sort | uniq -u | wc -l
155
```

**key finding**: approx 40% of all parameters are only used in only one theme.

top 30 most commonly used params and the number of themes they are used in:

```
$ egrep -or '\.Param "[^"]+"' . | sed -r 's/^[^\/]+\/([^\/]+)\/[^\:]+/\1/g' | sort -u | cut -d: -f2- | awk '{ print $2 }' | sort | uniq -c | sort -rn -k 1 | head -n 30
      9 "description"
      9 "author"
      6 "tags"
      5 "toc"
      4 "image"
      4 "contact"
      3 "youtube"
      3 "twitter"
      3 "title"
      3 "share"
      3 "medium"
      3 "logo"
      3 "linkedin"
      3 "instagram"
      3 "icon"
      3 "gitlab"
      3 "github"
      3 "facebook"
      3 "email"
      3 "authorbox"
      2 "valine.enable"
      2 "utterances.owner"
      2 "tocLevels"
      2 "themecolor"
      2 "socialShare"
      2 "socialOptions"
      2 "showPoweredBy"
      2 "seo.site_name"
      2 "related"
      2 "recent_posts_number"
```

**key finding**: the above are candidates for "best practice" documentation)

a list of all params used in only one theme can be made with:

```
$ egrep -or '\.Param "[^"]+"' . | sed -r 's/^[^\/]+\/([^\/]+)\/[^\:]+/\1/g' | sort | uniq -u
academia-hugo:.Param "slides.highlight_style"
academia-hugo:.Param "slides.theme"
autophugo:.Param "description"
autophugo:.Param "full_quality"
autophugo:.Param "full_width"
axiom:.Param "maxWidthFooter"
axiom:.Param "maxWidthHeader"
axiom:.Param "maxWidthTitle"
base16:.Param "author"
base16:.Param "keywords"
basicwebtheme:.Param "previewfullcontent"
basicwebtheme:.Param "randomorder"
basicwebtheme:.Param "skipTitle"
beautifulhugo:.Param "socialShare"
[...]

**Comment by khimaros** [comment]
i took a pass at extracting recommendations to consolidate using Levenshtein distance:

```
"author"
"Author"
"authors"

"commento"
"comments"

"featured_image"
"feature_image"
"featureImage"

"title"
"Title"
"bigtitle"

"showtoc"
"ShowToc"
"hideToc"

"subtitle"
"SubTitle"

"algolia.params"
"algolia.vars"

"AuthorDesc"
"authorDesc"

"blogHeaderType"
"homeHeaderType"

"enableBlogBreadcrumb"
"enableBreadcrumb"

"enableHomeSidebarTitles"
"enableListSidebarTitles"
```

i can provide more if that would be helpful.
