### ISSUE TITLE
Add site.Scratch

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#5689]
Some user formatted data (therefor not available at the `site`) may be shared by many if not every pages. 

For example a headless bundle storing images will have to be called on almost every pages using `.GetPage`.  Some other bundles (there can be a lot with heavy relationships project) may require filtering, ordering etc…  Also taxonomies containing Front Matters of custom slug will have to be called using `.GetPage` as well. Doing this call for every terms listed on every page could be costly, while a collection of formatted term object retrieved and formatted once and stored at the site level may end up very much cheaper.

If you have to do many .GetPage(ing) and .Scratch(ing) to format, order, filter this data, this whole process repeated inside every page context may bloat up the build time on projects with thousands of pages.

I can only think of one workaround (shared below) but I very much doubt its reliability .

Anyway, if I’m not wrong in thinking this use case has no current satisfactory solution and if this is something doable without endangering the current compartmentalized page system, I would suggest the following:

## Proposal

1. Add a `.Scratch` ability on the `site/.Site` object.
2. (optional) Design a way to perform some operations once and before Hugo starts treating each content file individually (pardon my poor and possibly very wrong schematization of Hugo’s system). 

I really don’t think we need number two though. User would only need to test for the existence of a key in `site.Scratch` and if not finding it, do the desired processing/scratching/populating.
This way, I assume, all of this would only happen once, when Hugo process the first page/file ?

Use cases for this:
- .GetPage (headless bundle etc…)
- .GetPage on taxonomies to store URL, display FM.
- asset processing/bundling (site.Scratch.Get "css")
- getJSON (I think caching keep this a cheap operation but I’m not sure)
- others may chime in

Again, it is hard to say how this suggestion is implementable or if it can even be conceptualized in a Hugo system. I’m expressing a need rather than a problem.
 
## Possible Workaround:
All I can think of would be to identify the first content file to be treated by Hugo (no idea how consistent this `first` would be throughout consecutive builds), and include in its template file 
1. the data processing which returned value would be stored in a variable
1. perform a very permissive `where` clause
2. range (on 1000 + pages 🤯 )
3.  scratching the value of the variable in each and everyone of them for later use.

**Comment by bep** [comment]
How would you control the concurrency? Where do you set your global values?

**Comment by bep** [comment]
I can add a little context:

* Most operations in Hugo is cached on one or more level. This included `GetPage`, `getJSON` etc.
* To make that work in a concurrent build pipeline (which is one of the reasons Hugo is fast), we must use some kind of locking. This prevents both double work and data races.
So, when you do `{{ resource.Get "scss/mystyles.scss" | toCSS | minify | fingerprint }}` and similar, this is guaranteed to both 1) Be thread safe and 2) Processed once only

If you wanted to do something similar with scratch, e.g.:

```bash
{{ $pages := site.Scratch.Get "pages" }}
{{ if not $pages }}
{{ $pages = where .Site.Pages "asdfasdf"  }}
{{ site.Scratch.Set "pages" $pages}}
{{ end }}
```

The above is probably a bad example.

* It would be thread safe
* But it will most likely be invoked multiple times

For long running operations, doing the above 2-3 times vs 3000 may still be worth it ...?

**Comment by regisphilibert** [comment]
Thanks for taking the time, I'll add a better usecase/example before tonight.

**Comment by regisphilibert** [comment]
I'm not sure what `thread safe` means. 

> But it will most likely be invoked multiple times.

Oh I get it, because some pages are processed concurrently? So your next question.

> For long running operations, doing the above 10-20 (I don't know) times vs 3000 may still be worth it... ?

The example you give is very fast to process, see the following:
```
{{ if not site.Scratch.Get "terms" }}
  {{ site.Scratch.Add "terms" slice }}
  {{ range $i, $v := site.Taxonomies.tags }}
    {{ with .GetPage (printf "/%s" $i) }}
    {{ site.Scratch.SetInMap "terms" $i . }}
    {{ end }}
  {{ end }}
{{ end }}
```

I really did not try this, I don't really recall by .Taxonomies is suppose to return, but this gives an idea. With the above, every page could conveniently use `site.Scratch.Get "terms"` when they need the page object of a term and easily retrieve its dynamic permalink, FM etc... without having to invoke those .GetPage more than this one time in the baseof. We could think of storing every terms for every taxonomies.

Displaying a list of terms on thousands of pages with a .GetPage can become easily expansive, especially when you have thousands of posts and as many if not more terms/taxonomies.
So I would imagine in this case `site.Scratch` could help reduce build time, but maybe not.
