### ISSUE TITLE
Best way to support docs from tags/releases/branches

### ISSUE THREAD

**Issue by nrayapati** [gohugoio/hugo#5694]
Tried searching hugo docs and most of the themes available at https://themes.gohugo.io/ but I couldn't find an example on how we can support docs being generated for multiple branches/releases/tags for same repo, similar to other static site generators support.  Appreciate any feedback or pointers. Thank you. 

Any future or ongoing efforts to support this as base feature? 

Example: https://sphinx-rtd-theme.readthedocs.io/en/stable/ 
![versions](https://user-images.githubusercontent.com/4974191/52681800-ca2e9000-2f02-11e9-9c4f-898690855d24.gif)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by nrayapati** [comment]
Thank you @bep
