### ISSUE TITLE
AsciiDoctor: set working dir to dir of current content

### ISSUE THREAD

**Issue by fapdash** [gohugoio/hugo#5695]
## Report

I'm currently evaluating hugo for our asciidoc based website.
As described in #4344, currently relative includes in adoc files are evaluated relative to the hugo root dir, which defeats the purpose of a relative include.

Would you be willing to change this so that the working directory for calls to the externel tool (AsciiDoctor in this case) is set to the directory of the content file that gets converted? Or give this as an option?

### Content file
```adoc
---
title: "Hello, world"
date: 2019-02-13T15:06:05+01:00
---

== Hello, world

include::to_include.adoc[]
```

### to_include.adoc
```adoc
== Abc

```

### Error
`ERROR 2019/02/14 11:26:28 posts/my-first-post/post.adoc: asciidoctor: ERROR: <stdin>: line 9: include file not found: /home/fap/repos/hugo_test/quickstart/to_include.adoc`

**Comment by celtic-coder** [comment]
It would be great if this could be setup as an option. Thanks!

**Comment by patti24k** [comment]
I made a mistake could you please correct my mistake  #5836  sorry for not replying right away very busy I'm trying to move can you please help

**Comment by muenchhausen** [comment]
I created a very first solution for this problem. Still for discussion, because I think some more discussions are required. Anyhow: This solution works so far (without backward compatibility).

**Comment by muenchhausen** [comment]
I have now improved the solution in pull request #6561

**Comment by celtic-coder** [comment]
Hi Derk (@muenchhausen),

Is there any further progress on this PR? 

Kind Regards, 
Liam

**Comment by muenchhausen** [comment]
I have the feeling, that the pull request [6561](https://github.com/gohugoio/hugo/pull/6561) will be merged soon :)

**Comment by benibilme** [comment]
Hello, 
I have the same problem. I have hugo web-site which shares documentation with antora web site. I really need this feature as well.
