### ISSUE TITLE
Extended -  error: failed to transform resource: failed to transform "style.coder.css" (text/x-scss)

### ISSUE THREAD

**Issue by Goevex** [gohugoio/hugo#5696]
I followed the instructions to install the extended hugo version including cloning the right branch. After I build it and run it with the hugo-coder theme, it says:
 `error: failed to transform resource: failed to transform "style.coder.css" (text/x-scss): this feature is not available in your current hugo version`
So I also exported `HOGU_BUILD_TAGS=extended`. But this didn't solve it. Instead I get an extra error running `mage install`:
```
In file included from cencode.c:2:0:
../libsass-build/cencode.c: In function ‘base64_encode_block’:
../libsass-build/cencode.c:50:5: warning: empty declaration
     __attribute__ ((fallthrough));
     ^~~~~~~~~~~~~
../libsass-build/cencode.c:64:5: warning: empty declaration
     __attribute__ ((fallthrough));
     ^~~~~~~~~~~~~
```
I also tried to install postcss and postcss-cli after I read some issues. No change.
So I guess, I'm doing something wrong or forgot something. Maybe you can help me.

Go: 
```
go version go1.11 linux/arm
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build077636673=/tmp/go-build -gno-record-gcc-switches"
```

Hugo: 
```
Hugo Static Site Generator v0.43-DEV linux/arm BuildDate: unknown
GOOS="linux"
GOARCH="arm"
GOVERSION="go1.11"
```

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
