### ISSUE TITLE
Using Hugo Pipes to build sass

### ISSUE THREAD

**Issue by simpson** [gohugoio/hugo#5699]
I am trying to setup a new site on Netlify to build with SASS. I've used this page for a reference: https://gohugo.io/hugo-pipes/scss-sass/, however this doesn't seem to work. Is the SASS pipeline actually working or is this documentation wrong?

**Comment by simpson** [comment]
I am trying to setup a new site on Netlify to build with SASS. I've used this page for a reference: https://gohugo.io/hugo-pipes/scss-sass/, however this doesn't seem to work. Is the SASS pipeline actually working or is this documentation wrong?

**Comment by simpson** [comment]
This is what I added in the header:
```
{{ $styles := resources.Get “sass/test.sass” | toCSS }}
<link rel=”stylesheet” href=”{{ $styles.Permalink }}” media=”screen”>
```
and added an assets folder at the root, with sass/test.sass file

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
