### ISSUE TITLE
Use sort.Slice from Go 1.8

### ISSUE THREAD

**Issue by moorereason** [gohugoio/hugo#5700]
We generally only sort slices, so all of this interface-satisfying boilerplate:

```go
type bySum []result

func (b bySum) Len() int           { return len(b) }
func (b bySum) Swap(i, j int)      { b[i], b[j] = b[j], b[i] }
func (b bySum) Less(i, j int) bool { return b[i].sum > b[j].sum }

func foo() {
    sort.Sort(bySum(b))
}
```
can be replaced with an inline less func:
```go
func foo() {
    sort.Slice(b, func(i, j int) bool { return b[i].sum > b[j].sum })
}
```

### Candidates
- [ ] hugolib.mapKeyValues
- [ ] hugolib.menuSorter
- [ ] hugolib.orderedTaxonomySorter
- [ ] hugolib.pageSorter
- [ ] hugolib.WeightedPages
- [ ] langs.Languages
- [ ] metrics.bySum
- [ ] media.Types
- [ ] output.Formats
- [ ] related.ranks
- [ ] releaser.contribCounts
- [ ] tpl.collections.pairList

**Comment by bep** [comment]
Note that `sort.Slice` will be slightly slower, not that is too important I think -- but most of the above will have to wait for my current working branch to go in -- or it will become a fairly painful merge.

**Comment by bep** [comment]
Also, I think we use the stable sort today, which I think we need to keep, so `sort.SliceStable´ is the right choice.

**Comment by moorereason** [comment]
I agree on both points.  Also, a few of the candidates I listed don't really lend themselves to this simplification.  I mostly wanted to leave notes here for later.
