### ISSUE TITLE
Allow "relative" URL in front matter

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5704]
Currently you can do:

```
---
title: "Search!"
url: "/search.json"
---

```

And we would treat the above as an URL starting from the BaseURL root. Which is good.

But in multi-language setups you would then have to do something ala:

```
---
title: "Custom!"
url: "/en/custom/foo"
---

```

To set a custom URL for that language. Which works.

It would, however, be very useful if we had support for a relative way of doing this. I have quoted the word _relative_ in the issue title, as I'm really not sure what it should be relative to.

This also ties into #5139 and similar.

I would think that this:

```
---
title: "Custom!"
url: "custom/foo"
---

```

Would be relative to the content's language.

/cc @regisphilibert

**Comment by regisphilibert** [comment]
Yes! Most wanted. Language should be abstracted when possible so that if you ever need to update your config to say make your default Lang live in a subdirectory or host langs on subdomain, the ‘url’ Param does not break your Permalink structure.
