### ISSUE TITLE
Allow output formats to be permalinked

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5706]
Currently, when you do `.RelPermalink` on a page, you will get a link to the _main output format_ (normally `HTML`).

We're re-implementing output formats for `0.55`. Most of the output format design still makes good sense, luckily. But when we now get a "fully virtualized" page graph (don't ask), we can do better in this particular case.

The current behaviour makes sense in most situations, though, so we cannot make it the new default. If you list pages for an `RSS` feed, you probably don't want to link back to the `RSS` version of that page (if that existed) ...? Another relevant example would maybe be calendar pages.

But it would make perfect sense in the `AMP` use case, where every page would be navigational. So. I suggest we add a new attribute on `Output Format`, say `Permalinkable` (... or something), that, if set,  will enable this for that format.

/cc @regisphilibert

**Comment by regisphilibert** [comment]
Yes.
Out of curiosity, would this also apply to the following being "called" from within this output format template:
- Prev\Next .Permalink
- PrevInSection/NextInSection .Permalink
- the Paginator's .URLs
- (.GetPage "/xx").Permalink

PS: I'm not saying this is needed for everything, .OutputFormats.Get can be used in out of the ordinary cases.

**Comment by bep** [comment]
>Out of curiosity, would this also apply to the following being "called" from within this output format template

Yes.
