### ISSUE TITLE
leaf bundle layout lookup order is wrong/different than branch bundle

### ISSUE THREAD

**Issue by dotleon** [gohugoio/hugo#5714]
Hugo Static Site Generator v0.54.0-B1A82C61 windows/amd64 BuildDate: 2019-02-01T09:42:02Z

Using Windows 10 latest.

Leaf bundles prioritize the /_default/single.html over /bundlename/bundlename.html

So 

> /content/branch/_index.md

prioritizes 

> /layout/branch/branch.html,

but the 

> /content/leaf/index.md

prioritizes

> /layout/_default/single.html 

over 

> /layout/leaf/leaf.html

Even if you set the layout in the content front matter, it uses the single.html

Example: https://github.com/dotleon/leafbundlelayoutissue

In this example, one would expect /leafbundle/ and /leafbundlewithlayout/ to use the /layout/leafbundle/leafbundle, instead they're using /layout/_default/single.html

BUT

/branchbundle/ is using the /layout/branchbundle/branchbundle.html

**Comment by bep** [comment]
What does the documentation say about this?

**Comment by dotleon** [comment]
Lots of things. https://gohugo.io/templates/lookup-order/

> Hugo searches for the layout to use for a given page in a well defined order, starting from the most specific.

I'd expect my case the most specific, since I set the layout in front matter. Also branch bundles seems to work as expected. It's the leaf bundles that act weird.

Let's see the examples that could apply here:

> Examples: Layout Lookup for Regular Pages
> Single page in "posts" section
> - layouts/posts/single.html.html
> - layouts/posts/single.html
> - layouts/_default/single.html.html
> - layouts/_default/single.html

This means that in my example, the /leafbundle/ should at least use /layout/leafbundle/single.html, but even if I rename it to single.html, it doesn't work as expected, and still uses the default template instead.

**Comment by dotleon** [comment]
I'm getting more and more sure that leaf bundles doesn't follow the documentation at all.
Even if I set the layout, then it should prefer /layout/exampletype/examplelayout.html over anything in /_default/, but it doesn't do that.

**Comment by dotleon** [comment]
Everyting works as expected if I delete /layouts/_default/single.html.

**Comment by bep** [comment]
See this table, which would apply to "leaf bundles":

https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-regular-pages

**Comment by bep** [comment]
I suspect this issue is mostly about the lookup rules being a little har do understand. We may improve on that in the future, but I suggest you take further questions here: https://discourse.gohugo.io/
