### ISSUE TITLE
IETF / ISO-639 mixed case language code support

### ISSUE THREAD

**Issue by sysoce** [gohugoio/hugo#5715]
**Problem:**
Uppercase language codes such as Traditional Chinese "zh-Hant" is converted to lowercase "zh-hant". 

**Suggested solution:**
Add mixed case support for language codes and URLs.

Possible related to #1407

**Comment by bep** [comment]
>**Problem:**
>Uppercase language codes such as Traditional Chinese "zh-Hant" is converted to lowercase "zh-hant".

Why is this a problem?
