### ISSUE TITLE
Add WeightedPages.Page

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5719]
I haven't wanted to do this because I didn't know how to without breaking lots of templates in the wild. But while cleaning up some other stuff, I think I found a way.

So taking one example from the docs:

```html
<ul>
    {{ $type := .Type }}
    {{ range $key, $value := .Data.Terms.Alphabetical }}
        {{ $name := .Name }}
        {{ $count := .Count }}
        {{ with $.Site.GetPage (printf "/%s/%s" $type $name) }}
            <li><a href="{{ .Permalink }}">{{ $name }}</a> {{ $count }}</li>
        {{ end }}
    {{ end }}
</ul>
```

We should be able to rewrite this as:

```html
<ul>
    {{ range .Data.Terms.Alphabetical }}
            <li><a href="{{ .Page.Permalink }}">{{ .Page.Title }}</a> {{ .Count }}</li>
    {{ end }}
</ul>
```

Note that I have replaced `.Name` with `.Title` in the example, because that is probably what you want in most cases. I have removed the `preserveTaxonomyNames` flag -- this will possibly be slightly breaking for some, but the logic was too hard to maintain -- and you can now use`.Title` which will preserve what you write in front matter. 

/cc @regisphilibert

**Comment by regisphilibert** [comment]
This is great!

> But while cleaning up some other stuff, I think I found a way.

Could this finding by any chance allow this improvement to be applied to the `.Site.Taxonomy` object as in:

```
<ul>
    {{ range .Site.Taxonomies.tags }}
            <li><a href="{{ .Page.Permalink }}">{{ .Page.Title }}</a> {{ .Count }}</li>
    {{ end }}
</ul>
```

**Comment by bep** [comment]
>Could this finding by any chance allow this improvement to be applied to the .Site.Taxonomy object as in:

@regisphilibert yes. I just added a test for both the above constructs:

https://github.com/bep/hugo/blob/cdcc7de233ef74a386d54d766d18c6b84e078043/hugolib/taxonomy_test.go#L284

So, the loops gets nicer, but look at the titles!

**Comment by regisphilibert** [comment]
Awesome !
