### ISSUE TITLE
Can't render a mobile friendly tel: number used in url in config.toml

### ISSUE THREAD

**Issue by truedat101** [gohugoio/hugo#5721]
I am attempting to link a mobile friendly phone number following the standard:

tel:+somenumber
or tel://somenumber

In my config.toml, I have:

```
    [[languages.en.menu.secondary]]
    identifier = "talktous"
    name = "Talk To Us"
    url = "tel:+14151112222"
    weight = 120
```

Oddly, this renders as:

http://localhost:1313/embeddedsystems/#ZgotmplZ

(note: the ZgotmplZ)

I'm sure I'm rending some template thing the wrong way, but mailto: just works fine, so I though tel: would work.  Ideas?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by truedat101** [comment]
So not a bug, but a feature of safeURL.  Not obvious, but it is stated that anything not matching http/https/mailto urls will get the funny ZgotmplZ URL.

Here is a reference: https://gohugo.io/functions/safeurl/#prose

Glad this is here because it should now show up in search results.

**Comment by IvanTurgenev** [comment]
this should be global annoying
