### ISSUE TITLE
HUGOMORE42 in pages with HTML sources

### ISSUE THREAD

**Issue by Yajo** [gohugoio/hugo#5723]
Hello, I'm using Hugo 0.54.0 and I find a HUGOMORE42 rendered whenever a `<!--more-->` tag is found in an HTML file.

Example: [this blog post](https://www.recallstack.icu/2018/08/24/la-virgulilla-en-javascript/), which comes [from this source](https://gitlab.com/recallstack/recallstack.gitlab.io/blob/bb6c7681907fd598c5f1668005443c448847bb75/content/post/la-virgulilla-en-javascript.html#L28):

![captura de pantalla de 2019-02-28 17-18-03](https://user-images.githubusercontent.com/973709/53585022-e4ac6e80-3b7c-11e9-8bc3-dd0df249893d.png)

It is also displayed in list views:

![captura de pantalla de 2019-02-28 17-19-26](https://user-images.githubusercontent.com/973709/53585095-0d346880-3b7d-11e9-9c65-b3bb63a393f3.png)

**Comment by DavideMagno** [comment]
Any news on this bug? I have the same problem...
