### ISSUE TITLE
Articles with future dates are published when date is derived from file or folder name

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#5726]
Hi all!

We use

```
[frontmatter]
date = ["lastmod", "date", ":filename"]
```

in config.toml to enable dates in file or folder names.

Yet, `2019-03-02-my-article.md` is published although the file name is a future date. (Front matter lacks any date.)

Wenn I additionally add `date: 2019-03-02` in front matter the article is not published, which is correct.

Thanks for checking.

**Comment by bep** [comment]
Have you set `enablegitinfo`? I think it helps to know that you will get the default setting for the other dates if you don't set it.

**Comment by Brixy** [comment]
Thanks a lot, bep!

Even with `enablegitinfo = true` and `date = [":filename", "lastmod", "date"]` the article is mistakenly published.

(Originally, I put `filename` to the last position to be able to overwrite the file name date with frontmatter—e.g. with `lastmod`—without renaming a file or folder.)

**Comment by bep** [comment]
>Even with `enablegitinfo = true

I meant to suggest to turn if off.

The bottom line: The configuration may be so flexible that it's hard to get right, but the test coverage is exellent, even for your case, so, I'm going to assume that you are doing "something" wrong.

If you still think this is a bug, you need to provide a failing example project.

**Comment by Brixy** [comment]
[This is a minimal setup](/Brixy/hugo-future-publish-issue) with a future post that gets published.

I hope I did not get anything wrong.

THX!

**Comment by Brixy** [comment]
Thank you so much for helping—although it was not a Hugo issue!!
