### ISSUE TITLE
Minify SVG files

### ISSUE THREAD

**Issue by geeknoid** [gohugoio/hugo#5727]
It'd be great to have the --minify command-line option apply to SVG files that are part of the content directory so they get minified along with the HTML.

**Comment by bep** [comment]
You can inline them and minify them when you use them, but doing it for the actual files on disk falls deeply into the "I don't think so department". 

If you have `myimage.svg` or `mydata.json` in a bundle inside `/content`, any processing of those resources are conceptually the same as what we do with JPEG images etc. (`.Fit`, `.Fill` etc.), which means we are creating a new resource with a new name. Same with SVGs:

```
$mysvg := $svg | minify 
```

I can see some value in your suggestion, but I don't think it warrants the effort (it's not trivial, as we cannot expect everyone to want it for all files etc.)

Also, the SVG files inside /content seems very static once put there; why not minify them before you store them?

**Comment by geeknoid** [comment]
We're not using bundles for this stuff. We have a large team of contributors that are dumping content into our doc repo. To include images in their pages, they create an index.md file, put their svg files next to it, and just reference the svg file directly from markdown.

When I look in the resulting `public` directory, I see a nicely minified .html file, but the original untouched .svg files.

I could require the contributors to minify their SVG files before putting them in git, but then they get less readable and is an extra step that our contributors would have to deal with. We could minify in the serving path, but apparently Netlify doesn't handle minification of SVG files, so that's not going to work. Given this, it seems completely reasonable to expect the content preparation pipeline (Hugo) to handle this for us.

**Comment by bep** [comment]
>Given this, it seems completely reasonable to expect the content preparation pipeline

I agree that there are missing pieces in this setup, but I'm pretty sure the answer to this is not some "mass minification of SVG files in content".

This is discussed elsewhere, but you have exactly the same challenge with JPEG files etc. inside content. Currently you need to create some shortcode to process these (minify, resize). This is, of course, suboptimal. I have outlined a solution to this with some Markdown hooks where you could configure or apply some filters to resources you embed in your markdown.
