### ISSUE TITLE
Untransformed images from assets directory not copying to public directory

### ISSUE THREAD

**Issue by turijs** [gohugoio/hugo#5730]
I am running into an issue where untransformed image resources from the assets folder are not being copied into the public directory (even though .Permalink is accessed) when a transformed version of them is created prior.

I have created a minimal project which (at least for me) demonstrates this issue on build: https://github.com/turijs/hugo-issue

This is what I am trying to do on the homepage:
```html
<img src='{{ ((resources.Get "images/image1.jpg").Resize "500x").Permalink }}'>

{{ range readDir "./assets/images/" }}
<img src='{{ (resources.Get (printf "images/%s" .Name)).Permalink }}'>
{{ end }}

<img src='{{ ((resources.Get "images/image2.jpg").Resize "500x").Permalink }}'>
```
But the plain version of image1 does not make it to the public folder after running `hugo`.
```
public/images
├── image1_hu702e1bd1a84809a46dc9d0ff6c1dd170_246083_500x0_resize_q75_box.jpg
├── image2.jpg
└── image2_hu9edba475167d542bfd8aa8a2aa5d5bb1_89925_500x0_resize_q75_box.jpg
```
```
$ hugo version
Hugo Static Site Generator v0.54.0/extended darwin/amd64 BuildDate: unknown
```
I am running Mac OS 10.14.3.

Also wanted to add that I have found hugo to be an amazing tool so far. Thanks in advance for taking time to look into this!

**Comment by bep** [comment]
Hey, and thanks for this. It is a curious bug. There seem to be some ordering/caching issue here, as if you change the order, it works as expected:

```bash
{{ define "main" }}

{{ range readDir "./assets/images/" }}
<img src='{{ (resources.Get (printf "images/%s" .Name)).Permalink }}'>
{{ end }}
<img src='{{ ((resources.Get "images/image1.jpg").Resize "500x").Permalink }}'>
<img src='{{ ((resources.Get "images/image2.jpg").Resize "500x").Permalink }}'>

{{ end }}
```

I will have a look at this later, and add a fix.
