### ISSUE TITLE
Hugo should default to a random cacheDir to avoid collisions on multi-user systems

### ISSUE THREAD

**Issue by khimaros** [gohugoio/hugo#5731]
If you have two users running hugo on the same machine, the default cacheDir of /tmp/hugo_cache collides between the users. This can be overridden in config.toml, but it would be nice to use a random suffix for the directory name as default.

**Comment by bep** [comment]
>This can be overridden in config.toml, but it would be nice to use a random suffix for the directory name as default.

The problem with randomness is that it kind of undermines the value of the cache. I see the problem (we do prefix the caches with the project name, which should reduce it), but I think we need something a bit more stable. Username?

**Comment by khimaros** [comment]
Ahh, I see. It seems that a project name of 'hugo' is common to a few users on my system. I had assumed that was hard coded. Yes. prefixing w/ username would help reduce collisions at least.

**Comment by khimaros** [comment]
Just thinking about this a bit more. A more clever/scalable approach would be to use a hash of the full filesystem path of the project directory.
