### ISSUE TITLE
Introduce logf

### ISSUE THREAD

**Issue by geeknoid** [gohugoio/hugo#5733]
I'm trying to debug some relatively complicated shortcode that fails once in a thousand times when running over our site. It'd be mighty handy if there was some easy way to output stuff to the console as Hugo is running.

Right now, I'm doing this with errorf, but I don't want to fail my builds. I just want to output some text so I can see what's happening and debug my problem.

Thanks.

**Comment by bep** [comment]
Temporary debug statements have a tendency to be forgotten and left there, which creates messy logs ... I agree that `errorf` is sub-optimal, but I don't see any problem with a temporafily failing build? You at least will be reminded to remove those statements once done.

**Comment by moorereason** [comment]
When I trying to debug a situation like this, I usually generate HTML into the pages with a unique string and then ripgrep the output.  I could see where a `logf` or `warnf` function could be useful for some people.

**Comment by geeknoid** [comment]
I had a case where:

- A shortcode is used thousands of times.
- It mostly worked, except in one case where it caused an error.
- The failure in the shortcode happened with no indication of the file in which it was being used.

So generating HTML wouldn't work.

@bep Software generally has an infrastructure for logging. Hugo has one I believe. Not putting in logging because it sometimes gets forgotten doesn't seem like a good rationale IMO. To work around this, you could make it so logf doesn't produce any output unless a particular command-line flag is supplied (--enable-logf or something).

**Comment by geeknoid** [comment]
Sorry, I actually misunderstood how errorf works. I assumed it was immediately terminating template processing for the current template. But it continue as normal and only causes a failure of the whole build. So I can use it to do printf-style debugging of my templates which is what I wanted.

This does explain why I sometimes got unexpected results in failure cases, since I reported an error with errorf and expected the rest of the template to not be processed, but it was. So I need to rejigger some error handling logic...

**Comment by geeknoid** [comment]
Well, turns out I'd still like logf for two reasons:

- Make it a pure logging function. Do not output anything into the generated document. Right now, in order not to disturb the generated output (in a deeply nested template), I end up doing:

  {{ $dummy := errorf "FOO" }}

It'd be nicer not to have that $dummy := in there.

- Make it so duplicate messages don't get erased. I'm trying to trace through a bunch of complicated templates and a bunch of my output is being erased. It makes it difficult to follow the flow through and figure out what's going wrong. I'm going start to use a global counter to make each message different so they all come out, but that's a pain.

Thanks.
