### ISSUE TITLE
`absLangURL` and `absURL` alters BaseURL in Multilingual Mode

### ISSUE THREAD

**Issue by hollowaykeanho** [gohugoio/hugo#5736]
# Problem
`absLangURL` and `absURL` both alter the BaseURL values when constructing the resultant URL.

# When
When BaseURL has path in it. Example:
```
www.example.com/path
```

This is a requirement for [GitLab Project Pages](https://about.gitlab.com/product/pages/) (the one with `username.gitlab.io/projectname`).

# Expectation
When `absLangURL` constructs the URL, it should take the `.Site.BaseURL` as it is. This means:

```
{{ "/media" | absLangURL }} --> www.example.com/path/en-us/media
```

However, it currently generates:
```
{{ "/media" | absLangURL }} --> www.example.com/en-us/media
```

# Affected
Both `hugo server` and `hugo build` on vanilla hugo sites, no themes.

Hugo version: `Hugo Static Site Generator v0.54.0 linux/amd64 BuildDate: 2019-02-01T13:33:06Z`

# Workaround
Build the link using partials or shortcode manually.

For absLangURL:
```
<!-- partials -->
{{- printf "%s%s%s" .Site.BaseURL .Lang "/posts/first" | urlize }}

<!-- shortcode -->
{{- printf "%s%s%s" .Site.BaseURL .Lang ( .Get 0 ) | urlize }}
```

For absURL:
```
<!-- partials -->
{{- printf "%s%s" ( trim .Site.BaseURL "/") "/posts/first" | urlize }} 

<!-- shortcode -->
{{- printf "%s%s" ( trim .Site.BaseURL "/") ( .Get 0 ) | urlize }} 
```

# Test Results
> ![screenshot-2019_03_05_21_36_48](https://user-images.githubusercontent.com/7259572/53809077-db613e80-3f8e-11e9-853e-0450809a2d7b.png)

HTML Code:
```
{{ define "main" }}
        <h2>Using List Layout</h2>
        {{- .Content -}}

        <h2> Test Zone</h2>
        {{ .Lang }}
        <table border=1>
                <tr>
                        <th><p>Title</p></th>
                        <th><p>Values</p></th>
                </tr>
                <tr>
                        <td><p>absLangURL</p></td>
                        <td><p>{{ "/posts/first" | absLangURL }}</p></td>
                </tr>
                <tr>
                        <td><p>absURL</p></td>
                        <td><p>{{ "/posts/first" | absURL }}</p></td>
                </tr>
                <tr>
                        <td><p>Constructed Lang URL</p></td>
                        <td><p>
{{- printf "%s%s%s" .Site.BaseURL .Lang "/posts/first" | urlize }}
                        </p></td>
                </tr>
                <tr>
                        <td><p>Constructed URL</p></td>
                        <td><p>
{{- printf "%s%s" ( trim .Site.BaseURL "/") "/posts/first" | urlize }}
                        </p></td>
                </tr>
        </table>
{{ end }}
```

**Comment by hollowaykeanho** [comment]
The test repo is available at: https://gitlab.com/holloway/hugo-bug

**Comment by bep** [comment]
I'm pretty sure this works as intended. Arguments to the absURL funcs with a leading slash is treated as **host relative**. Try removing the leading slash.

**Comment by hollowaykeanho** [comment]
![screenshot-2019_03_06_07_18_55](https://user-images.githubusercontent.com/7259572/53844281-2bb4bc80-3fe0-11e9-8865-dab0f78943e4.png)

Based on the latest test results above, `absLangURL` and `absURL` are indeed modifying `.Site.BaseURL`: The `fennec` went missing. Is this expected?

----

I upgraded the workarounds with the following partials and its shortcodes to demonstrate how to use them for the URL constructions.

sites/layouts/partials/links/absLangLink.html
```
{{ $url := .url -}}
{{ $langPrefix := .context.Site.LanguagePrefix -}}
{{ $base := printf "%s%s" .context.Site.BaseURL .context.Site.Language.Lang -}}

{{ if (hasPrefix $url $langPrefix) -}}
        {{ $url = strings.TrimPrefix $langPrefix $url -}}
{{ end -}}
{{ if (hasPrefix $url "/") -}}
        {{ $url = strings.TrimPrefix "/" $url -}}
{{ end -}}
{{ printf "%s/%s" $base $url | urlize }}
```

sites/layouts/partials/links/absLink.html
```
{{ $base := .context.Site.BaseURL -}}
{{ $url := .url -}}
{{ $langPrefix := .context.Site.BaseURL -}}

{{ if (hasPrefix $url $langPrefix) -}}
        {{ $url = strings.TrimPrefix $langPrefix $url -}}
{{ end -}}
{{ if (hasPrefix $url "/") -}}
        {{ $url = strings.TrimPrefix "/" $url }}
{{ end -}}
{{- printf "%s%s" $base $url | urlize }}
```

layouts/shortcodes/absLangLink.html
```
{{ partial "links/absLangLink" (dict "context" . "url" (.Get 0)) }}
```

layouts/shortcodes/absLink.html
```
{{ partial "links/absLink" (dict "context" . "url" (.Get 0)) }}
```

Using shortcodes
```
{{< absLangLink "/posts/first" >}}
{{< absLink "/posts/first" >}}
```

**Comment by hollowaykeanho** [comment]
![screenshot-2019_03_06_07_35_32 png](https://user-images.githubusercontent.com/7259572/53845007-84855480-3fe2-11e9-8365-e520e532be96.jpg)

> I'm pretty sure this works as intended. Arguments to the absURL funcs with a leading slash is treated as host relative. Try removing the leading slash.
Yeah, you're right about the leading slash. In that case, this is a false alarm. My bad. =x

**Comment by hollowaykeanho** [comment]
@bep I need to re-open the issue mainly because:

```
{{ .URL | absLangURL }}
```

This line is causing the problem. Unless I trim every leading slash manually, this is going to be very painful process.

**Comment by hollowaykeanho** [comment]
Updated workaround partials after battle tested with themes and production stage. The workaround is the expected experiences for both `absLangURL` and `absURL` equivalents.

**Comment by hollowaykeanho** [comment]
Tested with `baseURL` ended with a slash instead of translating each URL. Both `absLangURL` and `absURL` are working expected, which hence, making `{{ .URL | absLangURL }}` working as expected.

![screenshot-2019_03_12_11_29_32](https://user-images.githubusercontent.com/7259572/54172771-29f46880-44ba-11e9-9c6c-23764ded1564.png)

## Moral of the Issue
For `baseURL`, always end with `slash`, like:

1. `https://www.example.com/`
2. `https://192.168.0.1:8080/`
3. `https://username.gitlab.io/projectname/`

Closing this issue since it's not an issue but some missing point in documentation.
