### ISSUE TITLE
Work around broken boolean logic in Go's template package

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5738]
This issue tracks the work needed to fix/work around these two upstream issues:

https://github.com/golang/go/issues/28391
https://github.com/golang/go/issues/30501

Those issues are mostly put together here because it is most effective to solve them both in one go. The real reason why I'm taking on this now is to get a fix for [#30501](https://github.com/golang/go/issues/30501) which will get a fix in Go at the earliest in Go 1.13 in 3-4 months. The current behaviour is that you would sometimes get boolean logic (with `if`, `with`, `not` etc.)  such that both of statements below would print different output:

```bash
{{ if .AuthenticatedUser }}User is authenticated!{{ else }}{{ end }}
{{ if not .AuthenticatedUser }}{{ else }}}User is authenticated!{{ end }}
```

Or if it was in Go code:

```go
if true != !false {
  log.Fatal("black hole?")
}
```

**Comment by moorereason** [comment]
Wish we could overload `if` and `where`, but since they're keywords and not template functions in `text/template`, we can't do that.

**Comment by bep** [comment]
@moorereason I have a workaround for this ... I will add a PR in a minute, I need you to look at it ...
