### ISSUE TITLE
multiple domains in baseURL

### ISSUE THREAD

**Issue by shibumi** [gohugoio/hugo#5740]
Hi,
I have a website that listens on `www.domain.tld`, `domain.tld` and `foo.domain.tld`.
My baseURL is configured as: `baseURL = "https://domain.tld"`
Therefore my blog works fine when I visit `https://domain.tld`, but when I visit `https://foo.domain.tld` or `https://www.domain.tld` everything looks like garbage. Is there a way to set multiple baseURLs or at least some sort of variable that hugo detects the right baseURL by itself? In Jekyll I just set an empty baseURL and everything worked fine..

**Comment by shibumi** [comment]
nvm.. I just need to set "/" as baseURL

**Comment by AnselmoPfeifer** [comment]
`baseurl                   = "/"`
Thks

**Comment by kls0e** [comment]
but this generates an invalid sitemap.xml
