### ISSUE TITLE
.Site.Title not working in <title>

### ISSUE THREAD

**Issue by akashgurava** [gohugoio/hugo#5742]
I am trying to set the site title using `<title>{{.Site.Title}}</title>` in head. But it’s not working, I did inspect the source and it was an empty title tag. Tried to a static site build even build gave an empty title tag. If I do a similar `<p>{{.Site.Title}}</p>` in the body it works.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
