### ISSUE TITLE
Explicit highlighting breaks rendering with colons

### ISSUE THREAD

**Issue by vladfaust** [gohugoio/hugo#5746]
In the [blog post](https://blog.onyxframework.org/posts/creating-json-apis-with-onyx-part-2/#adding-the-index-endpoint) (scroll a little):

![image](https://user-images.githubusercontent.com/7955682/54079334-a2f19580-42eb-11e9-82f7-c45349aa2545.png)

While in the [source code](https://github.com/onyxframework/blog/blob/master/content/posts/creating-json-apis-with-onyx-part-2.md#adding-the-index-endpoint):

![image](https://user-images.githubusercontent.com/7955682/54079350-e4824080-42eb-11e9-8b27-b37631a5fa7c.png)

We can see that `REST` is gone. 

I initially thought that it is a Chroma [issue](https://github.com/alecthomas/chroma/issues/232#issuecomment-471077942), but seems like the problem is on Hugo side.

The project's config is available at https://github.com/onyxframework/blog/blob/master/config.toml

**Comment by bep** [comment]
#5683
