### ISSUE TITLE
No table of contents for posts generated from pandoc files

### ISSUE THREAD

**Issue by jdhao** [gohugoio/hugo#5747]
In order to support MathJax in hugo posts. I prefer the Pandoc way: just rename the files to to have extension `pdc` and install Pandoc. It works great but one disadvantage is that the generated posts do not have table of contents in it. I wonder how can I remedy this issue?

**Comment by PlushBeaver** [comment]
Any updates on this issue? I imagine this can be done using a Pandoc filter which would export ToC to a temporary file and some code in Hugo to invoke the filter and collect the results. What is unclear is how the filter should be implemented: using Lua/Python/etc would require scripting runtime, however, adding a "Pandoc filter mode" to Hugo binary seems clumsy.
