### ISSUE TITLE
minify strips PHP tags

### ISSUE THREAD

**Issue by ghost** [gohugoio/hugo#5748]
# Steps to Reproduce
Add following line to a template:
`{{ readFile "path/file" | safeHTML }}`

run `hugo --minify`
--> This part gets ommited, when using the `--minify` flag on hugo.

when you run just `hugo` everything is fine.

## How I came up with that:
I am including a php snippet for a contact form into a hugo template. Without the use of safeHTML` <?php` gets translated to `&lt;?php`.

**Comment by moorereason** [comment]
The [upstream minifier](https://github.com/tdewolff/minify) Hugo uses doesn't handle PHP tags.  See https://github.com/tdewolff/minify/issues/35#issuecomment-176094022

**Comment by raspopov** [comment]
I found a workaround at cost of all HTML comments keeping, it's acceptable in my case.
Thanks to @satotake "Add minify config" patch 574c2959b8d3338764fa1db102a5e0fd6ed322d9!

Add next lines to your `config.toml`:
```
[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
	  keepComments = true
```
Of course you must also escape PHP-tags inside partials templates:
```
{{ safeHTML "<?php" }}
...
{{ safeHTML "?>" }}
```
