### ISSUE TITLE
Dumb question about imports and go modules

### ISSUE THREAD

**Issue by rhugga** [gohugoio/hugo#5750]
We're having a helluva time trying to move from dep to go modules. We fix one thing, 5 others break. We fix those, 3 other things break. 

For starters, can someone explain to me why people import like this:

package main
import "github.com/someuser/somepackage"

The file itself may not necessarily even exist on github.com. I don't quite understand why or how people get this to work... or why it is designed that way. Why embed any kind of revision control or versioning system in your code?  We're using an internal onprem install of github and I have yet to get this working. On top of that we are using organizations so my repo path isn't a vanilla github.com/myuser/myrepo.

I can't tell if this is part of our problem moving to go modules. I have structured a project exactly like this one here where you have a single dep.go with one import. I can't for the life of me get this working. Not even close.

The only docs I can find are simple, single-directory, single-package hello world examples. We have a complex application with many packages and package directories at varying depths.

If anyone knows any good sites or docs for this please let me know. I've been searching all morning and haven't found anything that works for us.

Thanks for any help.

**Comment by bep** [comment]
This is the project you want: https://github.com/golang/go/issues
