### ISSUE TITLE
.Site.BaseURL can't include "https:"

### ISSUE THREAD

**Issue by supernum163** [gohugoio/hugo#5753]
I tried to set `baseURL = "https://example.site/"` in `config.toml` file, But the values of `{{ .Site.BaseURL }}` and `{{ .Permalink }}` would be `/`. 

if I set `baseURL = "//example.site/"`, the values would be `//example.site/`. 

Why is this happening, Can't baseURL include "https:"?

**Comment by bep** [comment]
> Can't baseURL include "https:"?

Yes it can.

**Comment by supernum163** [comment]
See my example here.

I set `baseURL = "https://example.site/"` in `/config.toml` file :
![图片](https://user-images.githubusercontent.com/25193929/54338236-4b955180-466c-11e9-9816-243a51407bdc.png)

And using `{{ .Site.BaseURL }}, {{ .Permalink }}` in `/layouts/partials/head.html` :
![图片](https://user-images.githubusercontent.com/25193929/54338272-636cd580-466c-11e9-919f-023fe5bd5bfb.png)

But the URLs don't change as I expected :
![图片](https://user-images.githubusercontent.com/25193929/54338533-1c331480-466d-11e9-852c-2a5897ab42be.png)

Here is my repo : https://github.com/supernum163/wly. Do ignore Chinese characters inside.

**Comment by supernum163** [comment]
I think I've figured out why. The reason is: I served the site on local machine, so hugo will replace `baseURL` to something like `http://localhost:1313/`, and my editor will replace it to `/`. When I serve the site on server,  it would show up correctly.
