### ISSUE TITLE
Allow page-relative alias in front matter

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5757]
This is related to #5704 -- but I suspect even more common a problem. I discovered this while testing the new `--path-warnings` (coming in Hugo 0.55) on some sites.

This is from Let's encrypt's website, a French translation of one of the pages:

```md
---
title: Chaîne de confiance
slug: certificates
top_graphic: 5
aliases: [/certs]
---
```

It's easy to see what has happened here: They have copied the English original and translated the language strings.

The problem is, however, that `/certs` will point to the server root, so it will be a little random which language will get the redirect.

We cannot change the meaning of `/certs` in the example above, but I suggest we do as in #5704 and say that alias definitions not starting with a leading `/` is considered relative to the language root where they belong, e.g.:

```md
---
title: Chaîne de confiance
slug: certificates
top_graphic: 5
aliases: [certs]
---
```

/cc @regisphilibert @kaushalmodi @budparr

**Comment by kaushalmodi** [comment]
> say that alias definitions not starting with a leading / is considered relative to the language root where they belong

I have a feeling that that won't be very intuitive. 

Seeing `aliases: [certs]`, I think that that's the page aliases respective to its current path. 

Is there a possibility to use special variables like `$langroot`? Example: `aliases: [$langroot/certs]`

**Comment by bep** [comment]
>Is there a possibility to use special variables like $langroot? Example: aliases: [$langroot/certs]

How is that more intuitive?

**Comment by kaushalmodi** [comment]
> would a page alias in the same folder be a common enough use case to even be considered? 

I can speak for everyone. But I have uses page aliases many times. It's usually when I have published a post, and then later rename it to something better. 

A very common general purpose application is to have shorturl aliases for each post (which I auto generate and insert to front-matter). 

One can argue that you can use the redirects too. But having aliases for a page in that page's front matter is useful too. 

Just my few cents.

**Comment by bep** [comment]
>I can speak for everyone. But I have uses page aliases many times. It's usually when I have published a post, and then later rename it to something better.

Yea, ok, that's fair. I have probably done the same. I will ... think about it.

**Comment by bep** [comment]
@kaushalmodi I have thought about this, and I think you are right. Pate-relative aliases would solve the above problem and also be more flexible. Some alias variants would be:

* `/myalias`; relative to the host root
* `./myalias` and `myalias`: Relative to the original page output file. So, if you change your permalink settings, the aliases will also move.
* `../../myalias`; same as above, but we will of course not navigate beyond the context root (i.e. the `baseURL`).
