### ISSUE TITLE
Wrong alias root for other HTML output formats (e.g. AMP)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5760]
I was reading some code and test related to this, and the alias path for the AMP type of output formats looks wrong. We create redirect pages for all HTML type of Output Formats. So for:

```bash
public/page/index.html
public/amp/page/index.htm
```

With an alias definition of `/myalias` you would currently get:

```bash
public/myalias/index.html
public/myalias/amp/index.html
```

We have test cases for the above, but to me that looks surprising and obviously wrong.

I would expect:

```bash
public/myalias/index.html
public/amp/myalias/index.html
```

**Comment by bep** [comment]
@regisphilibert could you have quick look at the above and tell me if you agree.

**Comment by regisphilibert** [comment]
This is news to me as I'm fairly unexperienced with HTML output format with a `path` set, AMP included, maybe others will have more use cases to build an opinion upon. 

To me though: 
If we follow the AMP recommended URL structure which have you recreate a sort of "alternate" site, yes, the correction you want tot make is needed. 
But for any other HTML output format, the current behaviour is, I think, adapted to the user's expectation. 

If this correction is limited to AMP, then I agree, if this is for every HTML output formats with a `path` set, then no I don't agree.

**Comment by regisphilibert** [comment]
I just found out that the `path` setting's value is added at the root fo the URL for every HTML (or `isHtml = true`) output formats.

I was not understanding the `path` setting properly.

**Comment by bep** [comment]
>If this correction is limited to AMP, then I agree, if this is for every HTML output formats with a path set, then no I don't agree.

This is relevant for all HTML output formats with PATH set (which is kind of very AMP specific).
