### ISSUE TITLE
Error for blogdown::install_hugo() 

### ISSUE THREAD

**Issue by andrescs91** [gohugoio/hugo#5761]
The latest Hugo version is 0.54.0
trying URL 'https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Windows-64bit.zip'
trying URL 'https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Windows-64bit.zip'
Content type 'application/octet-stream' length 18187152 bytes (17.3 MB)
downloaded 17.3 MB

Hugo has been installed to C:\Users\.................................
Warning message:
In download.file(url, output, ..., method = method) :
  URL 'https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Windows-64bit.zip': status was 'SSL connect error'

**Comment by bep** [comment]
What is the issue? If you have SSL connect issues I think you must take this with GitHub?

**Comment by salim-b** [comment]
In addition to the previous comment: You should really report these kinds of problems in the [blogdown repository](https://github.com/rstudio/blogdown) and not here, since it obviously has nothing to do with hugo itself.
