### ISSUE TITLE
Add a way to tell that you want "legacy behaviour" from inside a template

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5763]
This is related to #4695 -- which, with @moorereason 's proposed solution, is the obviously best solution going forward. I have it implemented in a branch and it works great. Everyone will love this.

There is, however, at least one known breakage in the wild: The Kubernetes website has a shortcode that was cleverly ported from some complex Jekyll logic. It should be possible to improve that situation/remove the need for that construct, but it's used about 1000 times ...

The good thing is that it's easy to keep the old behavior for a given shortcode if we're told to do so.

But we cannot and will not add any more clever shortcode syntax ("if you start the shortcode name with a double pound sign to tell Hugo that you want some other behavior ...") because it would complicate things at it wouldn't really solve the Kubernetes problem.

So, after some thinking, I concluded that we must find a way to add some kind of version flag inside the templates. And if we imagine that we could use this for "other stuff" in the future, it may look something like this:

```bash
{{/* _hugo_config:v=1,someother=32 */}}
{{ range .Site.Pages }}
{{ end }}
```

So any template comment at the start of the template with matches the pattern above will be used to _configure the template_.

I think the above would work great, at least for rare cases like the Kubernetes situation. 

But since I have plenty of regrets about hard to change method/config names from the Hugo past, I want to get the format right (e.g. `hugo_flags:v=1,someother=32`).

It must be distinct (not to be confused with user code) ...

Suggestions? Any good examples from other software projects?

@onedrawingperday @digitalcraftsman @kaushalmodi @regisphilibert @RickCogley @anthonyfok  and gang.

**Comment by bep** [comment]
I think I'm going to stick with JSON:


```bash
{{/* { "_hugo_config": { "version": 1} }  */}}
{{ range .Site.Pages }}
{{ end }}
```

**Comment by bep** [comment]
Since Go throws away comment nodes, it's going to be something ala:

```bash
{{ $_hugo_config := `{ "version": 1} }` }}
```

**Comment by regisphilibert** [comment]
Your recent hint will become handy here:

```
{{ $_hugo_config := `{ 
	"version": 1,
	"other": 2
}` }}
```

**Comment by bep** [comment]
@regisphilibert yes, it was working on this I discovered it (and it puzzles me a little I haven't caught it before) -- I suspect, however, that it will be more useful in "resource from strings" scenarios.

**Comment by moorereason** [comment]
Can you point us to the k8s shortcode you referenced?  I'm curious what this corner case is all about.

**Comment by bep** [comment]
@moorereason I rather not ... Because I wrote that "corner case" :-)
