### ISSUE TITLE
Feature: Add extended code block markdown syntax

### ISSUE THREAD

**Issue by dmulter** [gohugoio/hugo#5768]
The highlight shortcode provides a great solution for more control over code blocks, including line numbers and line highlighting. The downside is the content is no longer parseable Markdown. This interferes with sharing Markdown content with other content tools and sites.

The approach used in Gatsby is quite nice via the [gatsby-remark-prismjs](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/) plugin. A similar approach would basically allow code blocks like:

<pre>
```python{4}
def foo():
  x = 1
  y = 2
  z = 3
```
</pre>

Which would highlight line 4. Copy and paste of the Markdown content to other tools would safely ignore the extended syntax, but still render the code block. I am not suggesting changing the use of Highlight, only extending Markdown support to handle the Highlight shortcode for people.

**Comment by dmulter** [comment]
I often cross-post content between my Hugo powered blog and other content sites. With the current Hugo markdown, I must go back and edit all my code blocks when pasting to other sites. The feature I proposed would solve this problem. I would think others would find it valuable as well. I also think Gatsby could be leading the way others like Hugo might want to emulate.

Thanks for the consideration!

**Comment by bep** [comment]
A variation of this is implemented and comes in Hugo 0.60 in the form of CommonMark attributes (it's still a proposal, but I would suspect closer to spec than the plugin above).

**Comment by bep** [comment]
This is now merged.
