### ISSUE TITLE
Hugo and gitolite

### ISSUE THREAD

**Issue by M1k13** [gohugoio/hugo#5775]
Hey,

Kinda new to all of this. First thanks for Hugo it looks/works great.

Question:
I have my repositories in markdown on my gitolite server and I would like to pull that from gitolite with Hugo so it will build a site from those markdown files.
And if thats possible, can Hugo real time update and display the changes that I make to the markdown documents on the gitolite server?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
