### ISSUE TITLE
Consider making .File on .Page a zero value instead of nil

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5781]
* It's now a method that returns an interface
* It's nil if no set
* The embedded `.File` is deprecated so you need to say `.File.Filename` instead of `.Filename` (you will get a deprecation warning for the latter)
* If you do `.File.Filename` on a Page without a File you will get a nilpointer (a nice error message pointing to the location in Go 1.12.1
* With the latest work on if/with we could make it a zero value work _better_ and create less noise in the wild, but I tend to think that it would be better for people to know that the `File` isn't there (this is what I see in the wild; I think getting the nilpointer will help fix actual bugs in the templates around where people assumes that every Page is backed by a file)

I create this issue as a "thinking issue". What do you think, @moorereason ?

**Comment by bep** [comment]
I have thought a little about this, and I suspect the current solution will create more noise than we'd care for. So I will do this:

* Return a zero value when no file is set that is a proxy that prints a generic warning about wrapping the code in `{{ with .File ...}}`
* That way we avoid the bulk of the noise and site breakage, but help people fix what in most cases is a logical bug

**Comment by onedrawingperday** [comment]
This looks like a great plan!

Once you make a commit let me know and I will take it for a spin.
