### ISSUE TITLE
Content slug contains hash and is breaking the site - again!

### ISSUE THREAD

**Issue by clanstyles** [gohugoio/hugo#5785]
Looks like this was brought up before: https://github.com/gohugoio/hugo/issues/4926 it's still happening. I've reported it there and I would like to see if we can't get this addressed.

Version: ```Hugo Static Site Generator v0.54.0/extended linux/amd64 BuildDate: 2019-02-01T13:31:26Z```

**Comment by bep** [comment]
Can you edit this issue title to be less ... shouting?
