### ISSUE TITLE
RSS feed generation for sections sometimes doesn't generate items (0.54)

### ISSUE THREAD

**Issue by dylanmaassen** [gohugoio/hugo#5786]
Version: Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
OS: Manjaro (and also in a Debian-based Docker container)

Using version 0.54 (I haven't tried other version) yields some interesting results when it comes to generation of the RSS feeds.

For my site I've set up taxonomies for sections called `projects` and `posts`. Both of these taxonomies work fine when it comes down to creating indexes of the pages etc.

However, `hugo` and `hugo serve` sometimes fail to add items to the RSS feeds for these taxonomies. The index.xml files are generated and all of the information is there *except* for the actual items.

This issue happens both locally and in a Debian-based Docker container I use for deployment of my site 

Here's an example of an index.xml generated without any items:
```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Projects on Dylan Maassen van den Brink</title>
    <link>http://localhost:1313/projects/</link>
    <description>Recent content in Projects on Dylan Maassen van den Brink</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <copyright>© 2019 Dylan Maassen van den Brink</copyright>
    
	<atom:link href="http://localhost:1313/projects/index.xml" rel="self" type="application/rss+xml" />
    
    
  </channel>
</rss>
```

And here's an example of an index.xml generated with items:

```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Projects on Dylan Maassen van den Brink</title>
    <link>http://localhost:1313/projects/</link>
    <description>Recent content in Projects on Dylan Maassen van den Brink</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <copyright>© 2019 Dylan Maassen van den Brink</copyright>
    <lastBuildDate>Sat, 23 Mar 2019 17:42:02 +0100</lastBuildDate>
    
	<atom:link href="http://localhost:1313/projects/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>Title</title>
      <link>http://localhost:1313/Title/</link>
      <pubDate>Sat, 23 Mar 2019 17:42:02 +0100</pubDate>
      
      <guid>http://localhost:1313/Title/</guid>
      <description>Description</description>
    </item>
    
  </channel>
</rss>
```

Whether or not it properly includes the items is seemingly random, these two example were generated mere seconds from eachother simply by running `hugo` twice. 

If you have any ideas on how I can better supply you with debugging information, please let me know.

**Comment by bep** [comment]
I suspect you have both a section and a taxonomy that ends up in the same path. In Hugo 0.55 (the current source) we've added a flag (`--path-warning`) that will help you debug this.

**Comment by dylanmaassen** [comment]
And right you are.
 I've removed the taxonomies and the items are now being generated properly.

Cheers!
