### ISSUE TITLE
Add inline SVG support

### ISSUE THREAD

**Issue by westurner** [gohugoio/hugo#5789]
Inline SVGs can be styled with CSS. Is there already a way to inline SVGs in templates (and maybe also with a shortcode)?

This *could* be done with a partial, but is that the best way?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by westurner** [comment]
> This could be done with a partial, but is that the best way?

An SVG can be inlined by using `readfile` (or a `readfile` shortcode). It may be necessary to change the width, height, id, and/or class attributes of the `<svg>` tag; or to wrap the element in a `<div>` with an id and/or class.

```go
{{ readFile "/static/img/filename.svg" }}
```

- https://gohugo.io/templates/files/#use-readfile
- https://gohugo.io/templates/introduction/#includes
