### ISSUE TITLE
Invalid/incomplete shortcode breaks *all* shortcodes

### ISSUE THREAD

**Issue by stephenfin** [gohugoio/hugo#5790]
I'm switching my docs from rST to Markdown and trying to take advantage of shortcodes in the process. However, I am noticing some usability issues in the process. I created something like this:

```
---
title: "Welcome"
date: 2019-03-25T13:43:58Z
---

Hello, world. Here is some text.

{{< gist spf13 7896402 >}}

{{% note %}}
Here is a piece of information I would like to draw your **attention**** to.
{{% /note %}}
```

When I ran `hugo serve`, none of the shortcodes were rendered. I noticed the following logs:

```
Change detected, rebuilding site
2019-03-25 13:48:57.447 +0000
Source changed "/tmp/test-hugo/content/post/welcome.md": WRITE
ERROR 2019/03/25 13:48:57 Unable to locate template for shortcode "note" in page "post/welcome.md"
Total in 13 ms
```

However, I didn't pay much attention to this because the thing still ran and sort of rendered. Eventually I figured out that if I dropped the `{{% note %}}{{% /note %}}` shortcode, the ``{{<gist>}}`` one suddenly started working. Once I'd figured *that* out, I realized that the definition of the former in [the docs](https://gohugo.io/contribute/documentation/#note-admonition) was only given as an example and is not included out of the box.

This has caught me out before and I doubt I'm the only one. Ideally, I think the build/serve operations should fail to run in the above case. Alternatively, I think the broken shortcodes should be replaced with some kind of warning that states that there is an issue (this is what docutils does). In any case, it really shouldn't just fail sort of silently like it's doing here.

I can try fix this myself but I'd like to know if the idea is sound before I invest the time in an unwanted fix.

**Comment by bep** [comment]
>This has caught me out before and I doubt I'm the only one. Ideally, I think the build/serve operations should fail to run in the above case

First, I suspect you are running an old version of Hugo. But are you sure it does not fail to run? And by failing I mean: 1) Log an ERROR and 2) Exit with an exit code != 0

**Comment by stephenfin** [comment]
Thanks for the quick reply. Indeed, my version does look quite old:

```
$ hugo version
Hugo Static Site Generator v0.37.1 linux/amd64 BuildDate
```

(I see the latest appears to be [0.54.0](https://github.com/gohugoio/hugo/releases/tag/v0.54.0)).

This is the version packaged on Fedora. I can probably encourage someone to update this.

You are also correct in suggesting that the exit code is non-zero (255, to be exact) and that stopping the server on error would be painful. The exit code wasn't much more obvious than the error log though.

What are your thoughts on including the errors in the built document when using the server? We probably don't want to include it in the built docs but that could be configurable, I guess.

**Comment by Jos512** [comment]
> What are your thoughts on including the errors in the built document when using the server? We probably don't want to include it in the built docs.

This feature is added in [Hugo 0.50](https://gohugo.io/news/0.50-relnotes/). It's called 'browser error' in Hugo and they don't show when you build the site (only appear with `hugo server`).

>This is the version packaged on Fedora. I can probably encourage someone to update this.

[This](https://copr.fedorainfracloud.org/coprs/daftaupe/hugo/) Fedora Copr version is updated till 0.54. [Here's](https://discourse.gohugo.io/t/hugo-0-54-0-released/16764/3) a list of other places where you can fetch the latest Hugo package.

---

(Hope this comment helps even though it's not vital in solving the issue. It at least saves someone else time spend replying and looking up the links.)

**Comment by stephenfin** [comment]
Excellent, thanks. Seems like this is resolved and I just need to use that Copr or encourage someone to update the main repo. I guess this can be closed now

**Comment by stephenfin** [comment]
For anyone that stumbles upon this, it seems [Fedora 30 will include Hugo 0.54](https://src.fedoraproject.org/rpms/hugo/blob/f30/f/sources). One less thing for me to do \o/
