### ISSUE TITLE
failed to transform "scss/main.scss" (text/x-scss)

### ISSUE THREAD

**Issue by cncal** [gohugoio/hugo#5793]
os: windows 10
hugo version: Hugo Static Site Generator v0.54.0-B1A82C61 windows/amd64 BuildDate: 2019-02-01T09:42:02Z

I am new to hugo and installed it with **Chocolatey** following the [document](https://gohugo.io/getting-started/installing/#chocolatey-windows). An error occured when I executed `hugo server`:
```sh
$ hugo server
error: failed to transform resource: TOCSS: failed to transform "scss/main.scss" (text/x-scss): this feature is not available in your current Hugo version
``` 
Am I doing something wrong?

**Comment by bep** [comment]
See gohugoio/hugoDocs@3f21d09

**Comment by cncal** [comment]
@bep it works for me, thinks a lot.

**Comment by novadaemon** [comment]
Excellent. I had the same problem, but now it's fixed.
