### ISSUE TITLE
Multilingual/Localized images don't respect language weight

### ISSUE THREAD

**Issue by norristh** [gohugoio/hugo#5794]
As discussed [here](https://discourse.gohugo.io/t/localized-image-in-multilingual-leaf-bundle/17409):

See https://gitlab.com/stop-fossil-fuels/stop-fossil-fuels-test

The leaf bundle is in content/spread-strategy/printed-material/

Build the site, then compare

- public/en/spread-strategy/printed-material/
- public/es/difusion-estrategia/materiales-impresos/
- public/ru/spread-strategy/printed-material/

EN is as expected, with zine.jpg

ES may be as expected, with zine.es.jpg. I expected this file would be renamed to zine.jpg, but perhaps that’s not how it’s supposed to work.

RU really confuses me. Even though English has the lowest “weight” value, RU has zine.es.jpg instead of zine.jpg. This seems to contradict “First file found across bundles by order of language Weight.”

I'm using version 0.54.

**Comment by bep** [comment]
>but perhaps that’s not how it’s supposed to work.

Correct.
