### ISSUE TITLE
Live reload still not working

### ISSUE THREAD

**Issue by Akito13** [gohugoio/hugo#5795]
I have the exact same issue described [here](https://github.com/livereload/livereload-js/issues/16) on _Hugo v0.55.0-DEV_.

**Comment by bep** [comment]
You need to be **more specific** about what's not working, as it certainly works for me.

**Comment by Akito13** [comment]
> 
> 
> You need to be **more specific** about what's not working, as it certainly works for me.

Editing and adding posts does not reload the web page.
Editing JS and HTML files does not reload the web page.

Looking at the requests and responses within my browser, I see that they are using my baseURL with the port used by Hugo. I specifically disabled that by using `--appendPort="false"`, because Nginx takes care of correct redirection.

Requests/responses regarding livereload-js should be made with `example.com` and not with `example.com:1313`.

**Comment by bep** [comment]
You can do something ala:

```
hugo server --liveReloadPort=443 --baseURL=https://9774fc3f.ngrok.io --appendPort=false
```

But note that live reload is primary built for the built-in dev server.

**Comment by Akito13** [comment]
> 
> 
> You can do something ala:
> 
> ```
> hugo server --liveReloadPort=443 --baseURL=https://9774fc3f.ngrok.io --appendPort=false
> ```
> 
> But note that live reload is primary built for the built-in dev server.

I don't see any requests anymore but the livereload still is not working. I still have to refresh the page. Port 443 should be correct though, as I am indeed connecting over HTTPS.

**Comment by iangkent** [comment]
Having similar issue while trying to run hugo in kubernetes cluster accessed via ingress from browser.
https://github.com/gohugoio/hugo/issues/1187#issuecomment-490602574
