### ISSUE TITLE
Update Chroma to 0.6.3

### ISSUE THREAD

**Issue by Jos512** [gohugoio/hugo#5797]
Chroma had a new release 2 days ago. This release fixes issues in several syntax highlighters (JavaScript, Kotlin, Rust, Markdown, among others).

Version 0.6.3 also adds new languages: Turing, Matlab, Arduino, Graphql.

The changelog is here: [Chroma 0.6.3 release](https://github.com/alecthomas/chroma/releases/tag/v0.6.3).

**Comment by bep** [comment]
cc8515f18767298da4c6d712d1fd747c7950150b
