### ISSUE TITLE
Compiling and installing Hugo from source on Windows is getting a gcc error and fails

### ISSUE THREAD

**Issue by cmpsoares91** [gohugoio/hugo#5798]
Hello,

I'm trying to install Hugo from source on a Windows machine where I already have Git and Go installed, where I used the instructions from the [docs](https://gohugo.io/getting-started/installing/#fetch-from-github):
```sh
mkdir $HOME/src
cd $HOME/src
git clone https://github.com/gohugoio/hugo.git
cd hugo
go install --tags extended
```

However, I get the following error:
```
C:\tools\Hugo\src (master -> origin)
λ go install --tags extended
# github.com/wellington/go-libsass/libs
exec: "gcc": executable file not found in %PATH%
```

What should I do as a workaround?

Thank you for the support,
Carlos Soares

**Comment by cmpsoares91** [comment]
I'm looking into it as well and it seems to be related with this issue: https://github.com/wellington/go-libsass/issues/37

I'll investigate and maybe we need to add it to the docs later right?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
