### ISSUE TITLE
Fall back to summary set in front matter

### ISSUE THREAD

**Issue by mcdee** [gohugoio/hugo#5800]
Hugo's auto-generated page .Summary is often of no use to me so I write my own as a page variable.  This means, however, that I need to change common templates (e.g. RSS feed) to use said variable.

Is there any interest in a patch that would alter .Summary so that if a page variable called summary was available it used that value rather than auto-generating one from the content?

**Comment by bep** [comment]
Hey,

Short answer is `yes`, and I'm a little bit surprised that we did not already do so.

To create the least amount of surprises, I suggest that we check for `summary` in the following order:

1. The summary split option.
2. The `summary` value in front matter (new)
3. Auto-summary as the last resort

**Comment by mcdee** [comment]
Okay will take a look at this.
