### ISSUE TITLE
css/styles.css not found when using generated content vs hugo server

### ISSUE THREAD

**Issue by kstenerud** [gohugoio/hugo#5803]
When I use `hugo server` to look at my content, the generated page for a blog entry contains:

```html
 <link href="http://localhost:1313/css/styles.css" rel="stylesheet">
```

When I simply generate the content and view it through nginx, it looks like:

```html
<link href="css/styles.css" rel="stylesheet">
```
which resolves to `https://mysite.com/posts/my_first_post/css/styles.css`. Viewing this link returns 404 because there is no css/styles.css generated, so no custom styling gets applied when viewing the static site. However, when viewing via `hugo server`, it resolves fine.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by kstenerud** [comment]
For anyone else experiencing this, it was the themes I'd downloaded that was misbehaving.

A wishlist item: A theme linter so that consumers of themes can feel confident that a theme will work, and you'll get less bug reports. The theme was literally producing unresolvable links in the HTML that somehow managed to resolve when run with `hugo server`. That's bad.
