### ISSUE TITLE
Rendering of mixed lists not consistent

### ISSUE THREAD

**Issue by user501254** [gohugoio/hugo#5804]
Original issue comment https://github.com/MunifTanjim/minimo/issues/212#issuecomment-478317755.

I noticed that Hugo will add the class `.task-list` to any parent/top-level list that has a nested task items. Whereas this is not the case with GitHub rendered markdown `.contains-task-list` class, which is added at respective inner levels only. 
This makes styling difficult.

**Comment by bep** [comment]
>I noticed that Hugo will add the class .task-list to any parent/top-level list that has a nested task items.

But we do so consistently, right? I was a little confused by the title; I assume this is about GitHub doing it differently (and better)?

**Comment by user501254** [comment]
Sorry about the confusing title.
Yes, I do like GitHub's approach of rendering it. It allows for more flexibility/easiness of styling in case of complex nested and mixed lists.

Sample: https://github.com/facelessuser/MarkdownPreview/blob/master/examples/test.md#mixed-lists
![Screenshot from 2019-04-01 23-19-30](https://user-images.githubusercontent.com/6129517/55348429-cf589600-54d4-11e9-98ac-6bd13466479e.png)
