### ISSUE TITLE
Why so many open files?

### ISSUE THREAD

**Issue by marcelloh** [gohugoio/hugo#5817]
I have a tool called modd, that can act on changes too, and doesn't need so many open files. I want to generate a site with approx. 250.000 pages but now I need to raise my ulimit?
when in draft mode, Hugo only need to act upon changes like modd does.
(https://github.com/cortesi/modd)
I can't figure out why a system need that many files open. Can somebody please explain why I need to fix my OS in order to to test drafts?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
