### ISSUE TITLE
Documentation isn't rendering Markdown.

### ISSUE THREAD

**Issue by alexfornuto** [gohugoio/hugo#5829]
Example from [Quick Start](https://gohugo.io/getting-started/quick-start/)

![image](https://user-images.githubusercontent.com/2349184/55758735-3b7b5280-5a1d-11e9-8f31-4852d0046383.png)

Since I'm testing Hugo as a replacement documentation SSG, I'm particularly interested in seeing Markdown working.

**Comment by bep** [comment]
This will be handled in https://github.com/gohugoio/hugoDocs/issues/783
