### ISSUE TITLE
.GitInfo is <nil> in 0.5.5

### ISSUE THREAD

**Issue by tanepiper** [gohugoio/hugo#5830]
Version: `Hugo Static Site Generator v0.55.0-4333CC77F/extended linux/amd64`

With `enableGitInfo = true` - Updating a template and using `.GitInfo.Hash` results in error, as does all `GitInfo` variables.

The error result is as follows:

```bash
executing "partials/sidebar/footer.html" at <.GitInfo.Hash>: can't evaluate field Hash in type *gitmap.GitInfo
```

Checking `.GitInfo` itself results in a `<nil>` output.

**Comment by bep** [comment]
So, we use this on the Hugo site which works fine:

https://gohugo.io/templates/introduction/

Are you saying this error happens only in server mode when doing an edit?

**Comment by tanepiper** [comment]
Never mind, I've since discovered it can't be used in templates outside of a single item or page.  It was added in a sidebar footer, and caused it to fail generating on index pages and taxonomy pages.

**Comment by bep** [comment]
You can wrap it in `with`:

```bash
{{ with .GitInfo }}
{{ .Hash }}
{{ end }}
```

**Comment by jm3** [comment]
FYI only, for new posts not yet added to git, wrapping `.GitInfo` accessors using the `{{ with … }}` guard shown above throws an error, but using `{{ if .GitInfo }}` works fine.

> can't evaluate field GitInfo in type *gitmap.GitInfo

**Comment by Zorrozkk** [comment]
Please unsubscribe it thanks
