### ISSUE TITLE
Out of date menu/.URL/.Hugo templates and docs

### ISSUE THREAD

**Issue by TheBiggerGuy** [gohugoio/hugo#5835]
Hugo docs still suggest a now deprecated `.URL` variable. All Hugo docs and code snippets should not use any deprecated code paths.

On a secondary issue this code snippet now no longer even works (https://github.com/gohugoio/hugo/issues/5828). Can some system be added to auto check the docs actually work? And can it be made policy that any breaking change has to be fully documented before users see Warnings when updating.

Page: https://gohugo.io/templates/menu-templates/ 
Source: https://github.com/gohugoio/hugo/blame/master/docs/content/en/templates/menu-templates.md#L44

**Comment by TheBiggerGuy** [comment]
Found another issue:
```Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.```

Even when https://gohugo.io/variables/hugo/#prose
```We highly recommend using .Hugo.Generator in your website’s <head>. .Hugo.Generator is included by default in all themes hosted on themes.gohugo.io. The generator tag allows the Hugo team to track the usage and popularity of Hugo.```

Removing ```{{ .Hugo.Generator }}``` from my template removes the warning but I can not quickly find the _new_ way of doing it.

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues

**Comment by bep** [comment]
But also: Remember that this release is a day old ... The missing docs updates is mainly due to me getting a little tired of all the work ... :-) We will eventually get there, but any help is appreciated.

**Comment by nonumeros** [comment]
> me getting a little tired of all the work

suck it up buttercup. we love you man ;D

**Comment by inwardmovement** [comment]
@TheBiggerGuy did you actually find the new way of implementing `.Hugo.Generator` ?

**Comment by bep** [comment]
> .Hugo.Generator ?

Try "hugo.Generator"

**Comment by inwardmovement** [comment]
Thank you it did the job.
I created a [PR](https://github.com/gohugoio/hugoDocs/pull/795) adding this in the docs, sorry to not do more.

**Comment by TheBiggerGuy** [comment]
```{{ Hugo.Generator }}``` does not work and ```{{ .Hugo.Generator }}``` still gets a warning with v0.55.2.
* ```Building sites … WARN 2019/04/19 16:38:03 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.```
* ```Error: "site/layouts/_default/baseof.html:14:1": parse master failed: template: section/contributions.html:14: function "Hugo" not defined```

@inwardmovement did you find a working version?

**Comment by inwardmovement** [comment]
`{{ hugo.Generator }}` works for me, maybe it's case sensitive, try "hugo" instead of "Hugo".

**Comment by TheBiggerGuy** [comment]
Thank you @inwardmovement that worked.

so ```{{ .Hugo.Generator }}``` should be translated to ```{{ hugo.Generator }}```
