### ISSUE TITLE
How to 'disable' the website? Meaning, generating a landing/under-construction/under-maintenance page?

### ISSUE THREAD

**Issue by andry-tino** [gohugoio/hugo#5836]
I am using Hugo site generator for my site.

### Problem
Sometimes you are in the need of disabling a website; in this case, Hugo should generate a different `index.html` and **do not** generate any other page. The content of `public/` should only be the landing page and its dependencies.

1. Can this be achieved in the Hugo environment?
2. Is this scenario even included in Hugo?

### Scenarios
Some, but mainly when the site undergoes maintenance and we want to display just a bare landing page with some basic info, alerting the visitor that the site is temporarily down.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
