### ISSUE TITLE
"hugo new" fails on certain path formats

### ISSUE THREAD

**Issue by h-b** [gohugoio/hugo#5837]
Below permission denied error is not expected. It should not make a difference if a relative path is written with or without ./ at the beginning. Particularly the tutorial uses the command [without leading ./](https://gohugo.io/getting-started/quick-start/#step-4-add-some-content)

My configuration: I use Mac OS X and installed hugo as described in the [Fetch from GitHub documentation](https://gohugo.io/getting-started/installing/#fetch-from-github). According to [issue 1765](https://github.com/gohugoio/hugo/issues/1765), other users can reproduce similar problems.

```
~/Documents/github_hugo_issue/my_site> sw_vers -productVersion 
10.14.4
~/Documents/github_hugo_issue> ~/go/bin/hugo version
Hugo Static Site Generator v0.55.0-DEV/extended darwin/amd64 BuildDate: unknown
~/Documents/github_hugo_issue> ~/go/bin/hugo new site my_site
Congratulations! Your new Hugo site is created in /Users/stefan/Documents/github_hugo_issue/my_site.

Just a few more steps and you're ready to go:

1. Download a theme into the same-named folder.
   Choose a theme from https://themes.gohugo.io/, or
   create your own with the "hugo new theme <THEMENAME>" command.
2. Perhaps you want to add some content. You can add single files
   with "hugo new <SECTIONNAME>/<FILENAME>.<FORMAT>".
3. Start the built-in live server via "hugo server".

Visit https://gohugo.io/ for quickstart guide and full documentation.
~/Documents/github_hugo_issue> cd my_site
~/Documents/github_hugo_issue/my_site> ~/go/bin/hugo new content/my_first_page.md
Error: open /my_first_page.md: permission denied
~/Documents/github_hugo_issue/my_site> ~/go/bin/hugo new ./content/my_first_page.md
content/my_first_page.md created
~/Documents/github_hugo_issue/my_site> 
```

**Comment by osadalakmal** [comment]
This is happening because of code added in https://github.com/gohugoio/hugo/commit/2650fa772b40846d9965f8c5f169286411f3beb2. It added lines from https://github.com/gohugoio/hugo/commit/2650fa772b40846d9965f8c5f169286411f3beb2#diff-b0ffa99f961ed79cfc79caffafe34676R119 which now truncate the first component of a given relative path leaving a forward slash prefixed path which on any *nix platform now counts as an absolute path. This of course results in a permission denied error.

**Comment by h-b** [comment]
Thank you! So the code line causing this is (see commands/new.go, function mkdir):

`createpath = strings.TrimPrefix(createpath, s.PathSpec.ContentDir)`

I debugged above problematic case, which is:

`createpath = strings.TrimPrefix("content/my_first_page.md", "content")`

which results in

`createpath = "/my_first_page.md"`

This is consistent with the error message

`Error: open /my_first_page.md: permission denied`

With an input path `createpath = "./content/my_first_page.md"`, the code line does nothing (because content does not start with `"./"`).

What is the intended purpose of that code line? In other words, what is the use case that would be broken if we simply that code line (including the surrounding if block)?

**Comment by osadalakmal** [comment]
I am guessing it added support for archetypes. But I do not know much about the subject so someone more experienced than me will have to chime in.

**Comment by h-b** [comment]
The directory based archetypes were implemented by @bep - I am not an experienced github user, what is the usual strategy to inform him about a potential problem introduced by this commit? Write him a mail or is there some messaging mechanism on github?

This issue causes the tutorial not to work for Mac or Linux users which should give this issue some importance.

Last but not least, does hugo use unit tests? Apparently, there are no unit tests for the commands in the tutorial. Sorry for being a little bit off-topic here.
