### ISSUE TITLE
AsciiDoc: Add support for global document attributes

### ISSUE THREAD

**Issue by mraible** [gohugoio/hugo#5842]
I'm helping to migrate the Okta developer blog from Jekyll to Hugo. We're using both Markdown and AsciiDoc and Jekyll renders AsciiDoc using the following plugins:

```
group :jekyll_plugins do
  gem 'jekyll-asciidoc'
  gem 'asciidoctor-rouge'
end
```

We have most things working in Hugo, but we've discovered (with the help of @mojavelinux) that Hugo doesn't provide a way to pass configuration to an external helper command, like `asciidoctor`. Here's the code that executes Asciidoctor: https://github.com/gohugoio/hugo/blob/master/helpers/content.go#L626-L650

This means I have to define global attributes in every `.adoc` file. For example:

```
:page-liquid:
:source-highlighter: rouge
:icons: font
```

It'd be great if Hugo had a way to pass attributes from the Hugo configuration to the `asciidoctor` command. According to Dan, we're losing a lot of power without that ability.

**Comment by mojavelinux** [comment]
Being able to pass global attributes is essential for using Asciidoctor properly (the `-a` flag). Related to this is the ability to specify extensions to load (the `-r` flag).

One option is to simply allow extra arguments for the asciidoctor to be specified in the Hugo configuration. This would give the user maximum flexibility while only requiring a very small change to Hugo. There are many such options a user may want to specify. See https://asciidoctor.org/man/asciidoctor/

**Comment by m4c0** [comment]
Would it make sense to extend the [markup configuration][1] feature to also accept Asciidoc global attributes?

[1]: https://gohugo.io/getting-started/configuration-markup/

**Comment by jmooring** [comment]
Resolved with https://github.com/gohugoio/hugo/pull/7281
