### ISSUE TITLE
idea: Commento for comments & forums

### ISSUE THREAD

**Issue by jcw** [gohugoio/hugo#5844]
I've just been made aware of a project called [Commento](https://gitlab.com/commento/commento), which allows adding comments to pages, i.e. a discussion forum, not unlike Disqus. It's open source, and the back-end is written in Go.

Perhaps there is a way to combine, or even integrate Commento with/in Hugo?

The benefit of Hugo is that it generates a static site, which is trivial to keep around forever (e.g. archive.org). If the commenting system were to also generate static pages, this would allow the same for weblog that support comments. There could be several ways to do this: re-generate pages after each new comment, or keep a comment server running separately, but extend it to generate final frozen versions of pages once the comment thread is closed, i.e. once inactive.

FWIW, I think a similar mechanism could even be used for active public discussion forums, (re-) generating static pages after each new comment. For many smaller communities, this need not be prohibitive in terms of server load, since all the page **views** would be served from rendered files.

And while I'm at it: there's also the [Caddy](https://caddyserver.com) HTTP(S) server, which IMO makes an excellent front-end for Hugo. No need to integrate anything in this case, it works great as is - I just wanted to mention that **Hugo + Commento + Caddy** (all implemented in Go) would make a splendid trio for personal use, well-suited even for tiny Linux setups, such as a Raspberry Pi.

**Comment by souvikhaldar** [comment]
Is there any good blog link for the same?

**Comment by souvikhaldar** [comment]
This issue is really great and definitely needs more attention.

**Comment by celtic-coder** [comment]
This article, [Integrating comments in Hugo sites with commento](https://msfjarvis.dev/posts/integrating-comments-in-hugo-sites-with-commento/) (Jan 2020), has some brief implementation notes. May not be suitable for everyone, but might provide some possible pointers.
