### ISSUE TITLE
Google+ closure/removal

### ISSUE THREAD

**Issue by pacollins** [gohugoio/hugo#5848]
I need to read all of the contribution docs, otherwise I'd do this myself, but references to Google+ appear in the following places:
```
docs\content\en\content-management\authors.md Line 47
hugolib\site.go Line 675
resources\page\page_author.go Line 39
tpl\tplimpl\embedded\templates\schema.html Line 1
```

**Comment by brunoamaral** [comment]
I was taking a look at this and it's not as cut-and-dry as I thought. The googlePlus link was being used to populate the publisher tag: `<link rel="publisher" href="{{ . }}"/>`

Does anyone know the best practice to use from now on?

Meanwhile, this is my current commit : https://github.com/brunoamaral/hugo/commit/91da13f48f4f20eae7e871c8301372dc7b5e94f6

**Comment by brunoamaral** [comment]
@pacollins this pull request edits those files: https://github.com/gohugoio/hugo/pull/5988

I also found evidence that Google is moving towards using structured data instead of the rel=publisher link. Unless we are missing something, I think we can close this issue.

**Comment by dherbst** [comment]
This was fixed in https://github.com/gohugoio/hugo/pull/5988

**Comment by jmooring** [comment]
Closing per previous comment. Verified changes.
