### ISSUE TITLE
Page menu URLs vs permalinkable output formats

### ISSUE THREAD

**Issue by akshaybabloo** [gohugoio/hugo#5849]
After setting `section = ["HTML", "RSS", "AMP"]` in `config.tomal` all the hyperlinks in the page links to `http://domain.com/amp/...`. This was working fine in 0.54.

**Comment by bep** [comment]
> all the hyperlinks in the page links to 

What do you mean by ALL?

Note that we added a `Permalinkable` config option on the Output Format -- this defaults to true for HTML and AMP. You can turn that off, but you need to add a output format config section.

**Comment by akshaybabloo** [comment]
Any links that have been generated by Hugo that links to other pages in the same domain, not to the external domain. `Permalinkable` is not the problem I guess. 

Does adding `AMP` to sections turn all non-AMP links to AMP? as in `localhost:1313/blog/welcome` to `localhost:1313/amp/blog/welcome` in a page with URL `localhost:1313/blog`? This was not the case in 0.54.

**Comment by bep** [comment]
>Does adding AMP to sections turn all non-AMP links to AMP? as in localhost:1313/blog/welcome to localhost:1313/amp/blog/welcome in a page with URL localhost:1313/blog? This was not the case in 0.54.

No.

I will double check the logic to make sure that we only link from AMP => AMP, but when you now do `.RelPermalink` on a page when rendering the AMP variant, it will link to the AMP variant. 

If this is not what you want, you can turn it off. See above.

**Comment by akshaybabloo** [comment]
> No.

But it's happening to me for some reason.

I am not using `. RelPermalink` BTW I am using `.Permalink`. Are both same?

**Comment by bep** [comment]
>Are both same?

They are conceptually the same, yes.

**Comment by bep** [comment]
@akshaybabloo I have added some more tests for this -- and it behaves exactly as expected.

**Comment by akshaybabloo** [comment]
OK, I am not sure what the problem is then:

The code is here -> https://github.com/akshaybabloo/gollahalli.com

The output options I have in my `config.toml` is:

```toml
[outputs]
  home = ["HTML", "RSS", "AMP", "searchindex"]
  page = ["HTML", "RSS", "AMP"]
  section = ["HTML", "RSS"]
```

Now, I have removed `section` from it but I still get `amp` URL in my nav bar, the code for that is:

https://github.com/akshaybabloo/gollahalli.com/blob/8d31bbc560fd7b0cd7e236e05b9d748194a68e08/themes/Spark/layouts/index.html#L76-L81

```html
        <ul class="uk-nav uk-nav-default">
            {{ range .Site.Menus.main }}
            <li><a href="{{ .URL }}">{{ .Name }}</a></li>
            {{ end }}
            <li><a class="uk-navbar-toggle" href="#modal-full" uk-search-icon uk-toggle></a></li>
        </ul>
```

The `about` and `projects` has amp links I have no idea why.

**Comment by bep** [comment]
OK, the page menus. I understand now. I will fix this, eventually, but you can get back the old behaviour by adding a `AMP` definition with permalinkable turned off:

https://gohugo.io/templates/output-formats#readout

**Comment by akshaybabloo** [comment]
you mean by adding `permalinkable = false` in the `config.toml` right?

**Comment by bep** [comment]
Something llike this:

```
[outputFormats]
[outputFormats.AMP]
permalinkable = false
```
