### ISSUE TITLE
Images are available in the public folder but they have not been displayed in Netlify deploy

### ISSUE THREAD

**Issue by andresalerno** [gohugoio/hugo#5855]
Hi!
I'm trying to deploying a static site using an Hugo Theme through GitHub and Netlify, but i do not know why the images aren't displayed.

In a local environment there is not this problem.

https://github.com/andresalerno/hugo-site-v1

Tks!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
