### ISSUE TITLE
Installing tip requires module support

### ISSUE THREAD

**Issue by kevinburke** [gohugoio/hugo#5859]
Hugo attempts to install v2 of github.com/tdewolff/minify. The way to do this that supports GO111MODULE=off would be to create the directory github.com/tdewolff/minify/v2 and put v2 there, per https://github.com/golang/go/wiki/Modules#how-are-v2-modules-treated-in-a-build-if-modules-support-is-not-enabled-how-does-minimal-module-compatibility-work-in-197-1103-and-111.

The author of minify has not done that which means all of Hugo requires module support for installation or development. See https://github.com/tdewolff/minify/issues/239 for more.

I don't know that it's a great idea to require module support to develop or compile Hugo from tip. (I would personally prefer to stick with the non-module, the files-are-in-the-places-you-expect mode for as long as possible.)

**Comment by bep** [comment]
>I don't know that it's a great idea to require module support to develop or compile Hugo from tip. 

If you don't want to compile Hugo, there are plenty of release binaries available. If you want to discuss "whether this is a good idea or not", you can start a thread here:
https://discourse.gohugo.io/

**Comment by bep** [comment]
And note that Hugo only support Go >= 1.11. All of these have more or less great Module support.

**Comment by kevinburke** [comment]
I do want to compile Hugo, I just don't want to use modules to do it. I'll open a forum ticket.
