### ISSUE TITLE
False WARNINGs in lang prefix check

### ISSUE THREAD

**Issue by limenet** [gohugoio/hugo#5860]
Let me start by saying, I'm so happy with what you did in #5704, #5805, and #5818! We use Hugo to provide a multi-lingual product manual and that change makes onboarding new writers much easier.

We use a CI/CD to deliver our Hugo site which also checks if there are no warnings in the output of `hugo` and unfortunately the warning introduced in f34e6172cf2a4d1d1aef22304ecbc7c8e2d142ff has an edge case.

Please consider the following example where one of the languages is German (`de`):

```yaml
url: 'de/debitorenpreisfindung-zeilenrabatt'
```
Hugo correctly outputs a warning about the language prefix (`de/`). Once I change that to:

```yaml
url: 'debitorenpreisfindung-zeilenrabatt'
```
Hugo unfortunately still outputs the same warning since `de` is (incorrectly) assumed to be a language prefix and not part of the URL.

As per f34e6172cf2a4d1d1aef22304ecbc7c8e2d142ff I know this warning is only active in 0.55. However, I think this might affect a few people and it might confuse people and result in ignoring warnings which is a bad habit.

A solution might be to check whether the supposed prefix is followed by a non-alphanumeric character in https://github.com/gohugoio/hugo/commit/f34e6172cf2a4d1d1aef22304ecbc7c8e2d142ff#diff-5129e7484246c664a01e8bb7c023fa12R384 I'd love to provide a PR but unfortunately my Go skills are virtually non-existent.

What do you think?

**Comment by bep** [comment]
>What do you think?

I think you are right. I will add a fix. I kind of knew this would potentially create false warnings, but I thought it would still be worth it ...

**Comment by limenet** [comment]
@bep thanks for getting back to me so quickly and for adding this to the 0.55.2 milestone! I think the warnings are absolutely worth it :)
