### ISSUE TITLE
Updating usage of .URL on menu entries

### ISSUE THREAD

**Issue by sanderson** [gohugoio/hugo#5868]
Just updated to Hugo 0.55.1 and am updating templates and partials to address some of the changes. So far so good, except that my menus rely on each menu entry's `.URL` property. I know `.Page.URL` [is being deprecated](https://github.com/gohugoio/hugo/issues/4117) and am getting the deprecation warning in my build output. However, when I try to update to using `.RelPermalink` or `.Permalink` in my menu entries, I get the following:

```
... can't evaluate field RelPermalink in type *navigation.MenuEntry
```

How do you avoid using `.URL` in menu entries in 0.55.1+? Is replacing this specific menu entry property still in the works?

**Comment by divinerites** [comment]
.URL is not deprecated for menus. Only for .Page

Just keep them.

If you still have the warnings I guess you have some .Page.URL somewhere

**Comment by divinerites** [comment]
And may be this questions belongs more to discourse.gohugo.io instead of github
