### ISSUE TITLE
add .txt as a supported data format

### ISSUE THREAD

**Issue by eighthave** [gohugoio/hugo#5872]
This may sound odd, but it would be quite useful to have _.txt_ files as a supported file format.  Hugo would use the filename as the key, and just load the full contents of the file into a value field.

The use case is for building websites for Android/iOS apps.  The app store strings are managed in [Fastlane](https://fastlane.tools/), which uses a directory structure with .txt files in it.  This is then used to sync up to Google Play, iTunes, and [F-Droid](https://f-droid).  [Weblate](https://docs.weblate.org/en/latest/formats.html#app-store-metadata-files) supports directly translating those files, so Hugo would then get those translations as well using this .txt mechanism.

**Comment by bep** [comment]
I doubt we will do this as /data -- but I'm pretty sure what you want is possible today, but please ask at https://discourse.gohugo.io/

**Comment by eighthave** [comment]
https://discourse.gohugo.io/t/getting-text-content-from-a-standard-directory-layout-fastlane
