### ISSUE TITLE
Wrong links for regular pages for non-HTML output formats

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#5877]
If I call an Output Format using `(.OutputFormats.Get "that-output).Permalink/.RelPermalink` or simply `.Permalink/.RelPermalink` on a "permalinkable" output formats, the returned url points to the main output format. 

Considering the following bit of code added to `baseof.html`:
```
    this: {{ .Permalink }}
    {{ with .OutputFormats.Get "that-output" }}
      that-output: {{  .Permalink }}
    {{ end }}
```

From a list page (home, section) it would print
```
    this: https://www.example.com/
    that-output: https://www.example.com/that-output.html
```

From a regular page:
```
    this: https://www.example.com/
    that-output: https://www.example.com/
```

**Comment by bep** [comment]
I have added some more test in this area, and cannot reprodce what you see. Could you provide an example site with this behaviour?

**Comment by regisphilibert** [comment]
Of course, here you go: https://github.com/regisphilibert/hugo-permalinks
