### ISSUE TITLE
Build hugo site on Windows very slow

### ISSUE THREAD

**Issue by Rhinocros** [gohugoio/hugo#5880]
Build hugo site on Windows very slow，same site Windows needs more 60 seconds, but on Macos only need 6 seconds
For what? And how can I faster build site on Windows?  Thanks

**Comment by bep** [comment]
This issue isn't possible to reason about without seeing the actual site source.

**Comment by Rhinocros** [comment]
Site's URL is www.digit77.com
Could you help me analyze ,Thanks

**Comment by bep** [comment]
>Site's URL is www.digit77.com

I asked for the **site's source**, not the end result.
