### ISSUE TITLE
highlight shortcode produces different (wrong) results than code fences for type "ini"

### ISSUE THREAD

**Issue by MHerbst** [gohugoio/hugo#5886]
I wanted to add the content of an ini file to a new article. If I use code fences with type ini everything is OK. If I use the highlight shortcode instead, I get additional "new lines". This only happens if the language is set to "ini" or "cfg". With "toml" or "text" everything is fine.

Here is an example.
**Input:**
![image](https://user-images.githubusercontent.com/616792/56496869-82784600-64fb-11e9-9118-5a767604f98f.png)

**Output:**
![image](https://user-images.githubusercontent.com/616792/56496888-91f78f00-64fb-11e9-8003-45238b5791c7.png)

I am using Hugo 0.55.3 on Windows 10 with Chroma syntax highlighting.

**Comment by mxmehl** [comment]
I can reproduce this with the latest version. It only happens with ini, no other syntaxes I tried (~10).

I suggest to reopen this issue.
