### ISSUE TITLE
Any plans for syntax highlighting plugin for WebStorm?

### ISSUE THREAD

**Issue by SilencerWeb** [gohugoio/hugo#5891]
As I can see, Hugo has some plugins for a bunch of editors but not for one of the famous frontend editors and I'm curious are there any plans for a syntax highlighting plugin for WebStorm?

I found only [this workaround](https://stackoverflow.com/a/53102025), but it is still just a workaround.

**Comment by bep** [comment]
The editor plugins for Hugo is driven by the Hugo users, so to speak, so it's hard to predict.
