### ISSUE TITLE
/static cannot be empty

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5895]
Or you get this error:

```
Error: Error copying static files: EOF
```

**Comment by carlmjohnson** [comment]
Cross-linking #6051 which notes this is also true for /content.

**Comment by felicianotech** [comment]
I can't replicate in Hugo v0.58.3.

**Comment by carlmjohnson** [comment]
I believe that Hugo modules resolved this.

**Comment by jmooring** [comment]
Cannot reproduce with either missing or empty `static` directory.
