### ISSUE TITLE
Multilingual Mode: Redirects for sections of defaultContentLanguage are not created

### ISSUE THREAD

**Issue by Nexusger** [gohugoio/hugo#5898]
# Summary
Redirects for the `defaultContentLanguage`in multilingual mode exists only for the root, not for sections. Because of this, `example.org/en/` redirects to `example.org/` but `example.org/en/post` results in `http 404` (if "en" is `defaultContentLanguage`)

# Motivation
As users could reach the site via a deep link (`exmple.org/de/posts/my-first-post`) I'd like to be able to give them the option (additionaly to a language select on my site) to change the language part of the url.

# Expected behaviour
If a site is created with multiple languages a redirect is correctly created for the `defaultContentLanguage` for the root as well as all sections

## If `defaultContentLanguageInSubdir` is `false`

Created redirects:

* `example.org/` serves `/index.html`
* `example.org/post/` serves `/post/index.html` (created from `/post/index.en.md`)
* `example.org/en/` redirects to `example.org/`
* `example.org/en/post` redirects to `example.org/post`

## If `defaultContentLanguageInSubdir` is `true`

Created redirects:

* `example.org/` redirects to `example.org/en/`
* `example.org/post` redirects to `example.org/en/post`
* `example.org/en/` serves `/en/index.html`
* `example.org/en/post/` serves `/en/post/index.html` (created from `/post/index.en.md`)

# Actual behaviour
If a site is created with multiple languages a redirect is *not* correctly created for the `defaultContentLanguage` for sections, *only* for the root

## If `defaultContentLanguageInSubdir` is `false`

Created redirects:

* `example.org/` serves `index.html`
* `example.org/post/` serves `/post/index.html` (created from `/post/index.en.md`)
* `example.org/en/` redirects to `example.org/`
* `example.org/en/post`  -> **`http 404`**

## If `defaultContentLanguageInSubdir` is `true`

Created redirects:

* `example.org/` redirects to `example.org/en/`
* `example.org/post` -> **`http 404`**
* `example.org/en/` serves `index.html`
* `example.org/en/post/` serves `/post/index.html` (created from `/post/index.en.md`)

# Setup
A newly created multilingual site with the following configuration

```
defaultContentLanguageInSubdir = false
defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.de]
    languageName = "Deutsch"
    weight = 2

```
and the following content

```
/content
  /post
    /index.en.md
    /index.de.md
```

and the following layout

```
/layouts
  /_default
    /baseof.html
    /single.html
  /post
    /baseof.html
    /single.html
index.html
```

# Workaround
Creating an entry in `aliases` for each content of the `defaultContentLanguage`. Depending on the `defaultContentLanguageInSubdir` setting the alias has to be the not generated url. For the above example:

## If `defaultContentLanguageInSubdir` is `true`
In `/content/post/index.en.md`
...
aliases: ["/post/"]
...

## If `defaultContentLanguageInSubdir` is `false`
In `/content/post/index.en.md`
...
aliases: ["/en/post/"]
...

**Comment by bep** [comment]
I understand the argument, but my main problem with this is that if we create these redirects for the sections, we should also create redirects for all pages, and that is stretching it. That kind of redirection needs to be handled by a proper router with some kind of pattern matching.

**Comment by Nexusger** [comment]
As there is a workaround which is only needed for the defaultContentLanguage (and in my case this means 3-5 aliases) this isn't really an urgent issue, I'd say. 
But it's documented and someone with a similar problem can use the workaround.
