### ISSUE TITLE
.Summary, .ReadingTime, and .WordCount empty for Asciidoc

### ISSUE THREAD

**Issue by byF** [gohugoio/hugo#5901]
After update from Hugo 0.54.0 to 0.55.4 on macOS 10.14.4, `.Summary` is empty and `.ReadingTime` and `.WordCount` are zero.

Screenshot from `hugo serve` updated version:
![image](https://user-images.githubusercontent.com/592682/56742615-5c5dda80-6775-11e9-95cb-e4613321e73c.png)

Screenshot from my website:
![image](https://user-images.githubusercontent.com/592682/56742638-6c75ba00-6775-11e9-9e42-f39519e9284f.png)

Did I miss some important information about upgrade path? Documentation doesn't suggest anything.

**Comment by bep** [comment]
>Did I miss some important information about upgrade path?

No, that should just work. And it works for me and passes plenty of automated tests -- so there must be something "special" about your site which I fail to understand by looking at some screenshots.

Do you have a link to the site source?

**Comment by byF** [comment]
@bep  I see - I've added you as a collaborator in my repo if that suffices.

**Comment by johnshiver** [comment]
Im also seeing this issue on version: 

`Hugo Static Site Generator v0.55.0-4333CC77 linux/amd64 BuildDate: 2019-04-08T16:40:16Z`

deploy: http://www.johnshiver.org/
source: https://github.com/johnshiver/blog-hugo

Let me know what other information I can provide!
