### ISSUE TITLE
Add `list all` command to CLI

### ISSUE THREAD

**Issue by rusnasonov** [gohugoio/hugo#5904]
I working on extension to [VSCode](https://marketplace.visualstudio.com/items?itemName=rusnasonov.vscode-hugo) and I want to show list of all posts. Would a PR be accepted that added a new command `hugo list all`?

**Comment by bep** [comment]
> Would a PR be accepted that added a new command hugo list all?

It would if you at the same time refactored list future/draft to share a new common code path. They look a little like copy and paste and doing that a third time would not be ideal.

**Comment by bep** [comment]
I can add that the current "file path" logic in these commands isn't entirely correct for all situations (folders outside of the work dir, projects with multiple content dirs). Or, it is possibly correct, but not good enough if you want to use it in an "open file" plugin in VSCode.

I suggest you replace the current logic with `strings.TrimPrefix .Page.Filename workDir`.

**Comment by rusnasonov** [comment]
> It would if you at the same time refactored list future/draft to share a new common code path.

Ok, no problems.

> I can add that the current "file path" logic in these commands isn't entirely correct for all situations 
> I suggest you replace the current logic with strings.TrimPrefix .Page.Filename workDir.

Ok, I'll try to fix that. Replace current logic for all functions (draft, future), or only for new (all)?

**Comment by bep** [comment]
>for all functions (

Yes.

**Comment by rusnasonov** [comment]
@bep I create pr, but build fails with error for go 1.11.10
