### ISSUE TITLE
Unable to detect `nil` explicitly in conditionals

### ISSUE THREAD

**Issue by RealOrangeOne** [gohugoio/hugo#5905]
After the last update to 0.55, i'm no longer able to specify if a value is equal to `nil`. This is especially useful when combined with `where`. https://gohugo.io/functions/where/#unset-fields defines this as possible, although the example is using `.Params`, which I guess behaves slightly differently. 

For example, given a page

```
<p>{{ .Parent }}</p>
<p>{{ eq .Parent nil }}</p>
<p>{{ .File }}</p>
<p>{{ .Permalink }}</p>
```

yields

```
<nil>
false
tags/arch/_index.md
http://localhost:1313/tags/arch/
```

Doing `{{ if .Parent }}` acts false, as expected, meaning it seems `nil != nil` in this new release.

After some naive researching, https://dev.to/pauljlucas/go-tcha-when-nil--nil-hic might have something to do with this?

**Comment by RealOrangeOne** [comment]
Thanks for such a quick fix @bep, but this doesn't appear to be fixed. Or at least it's not in `Hugo Static Site Generator v0.55.6/extended linux/amd64 BuildDate: unknown`

The below code:

```
{{ range where .Site.Pages.ByTitle ".Parent" "!=" nil }}
        <p>{{ .Parent }} {{ eq .Parent nil }}</p>
{{ end }}
```
yields many lines with `<nil> false`. The pages affected seem to all be either taxonomy / taxonomy terms, if that helps anything.

My current fix is to do:

```
{{ range .Site.Pages.ByTitle }}
  {{ if .Parent }}
    <p>{{ .Parent }}</p>
  {{ end }}
{{ end }}
```

Which makes me think it is probably caused by the _fun_ which is `nil` equality checking in Go!

**Comment by bep** [comment]
I don't watch closed issues. Which isn't a way to say that all closed issues are fixed, they're just not on my radar anymore.

**Comment by RealOrangeOne** [comment]
@bep ok, what's the process for getting this issue looked into again? Re-opening the issue, or making a new one?

I'd argue there's definitely still a bug here.

**Comment by bep** [comment]
Making a new one.

**Comment by bep** [comment]
Note that the issue described in the first comment is fixed.

**Comment by RealOrangeOne** [comment]
![image](https://user-images.githubusercontent.com/6527489/58784448-5b716180-85db-11e9-98b6-6cd0e5386c8b.png)

It definitely isn't. But anyway, new issue incoming
