### ISSUE TITLE
Front Matter datetime duplicated timezone value

### ISSUE THREAD

**Issue by retifrav** [gohugoio/hugo#5907]
**Hugo:** v0.54.0/extended darwin/amd64
**OS:** Mac OS 10.14.4 (18E226)

As described in the [discussion thread](https://discourse.gohugo.io/t/front-matter-datetime-duplicated-timezone-value/17853), timezone from the page Front Matter is not always parsed correctly.

For example, date value from

```
---
title: "Some title"
date: 2015-03-25 22:52:11 +0300
tags: [tag, another]
---
```

becomes

```
2015-03-25 22:52:11 +0300 +0300
```

at the rendered page. So parser just duplicates the timezone value.

But what's weird is that in the majority of cases it is actually parsed correctly, so

```
2018-09-22 21:52:45 +0200
```

becomes

```
2018-09-22 21:52:45 +0200 CEST
```

**Comment by retifrav** [comment]
Still reproducible with `v0.57.2/extended`.

And I got how to reproduce it: my current timezone is GMT+2, and if I put any other timezone, like +0300 in my example from above, then the page's datetime gets messed up. And I have a lot of pages like this because I was posting those while being in different timezones, so while their timezones were correct at the moment I was writing them, now there are "not correct" anymore, hence the problem.

**Comment by retifrav** [comment]
Still reproducible with v0.58.3/extended.

**Comment by richardboydii** [comment]
Still open with Hugo 0.73 on WSL / Ubuntu Linux with the following: {{ .PublishDate.Format "2006.02.01 15:04-0500" }}

**Comment by retifrav** [comment]
A minimal website example to reproduce the issue: https://github.com/retifrav/hugo-timezone-duplicate

So, my local system time is:

```
$ date
Mon Jun 29 13:41:20 CEST 2020
```

Hugo version:

```
$ hugo version
Hugo Static Site Generator v0.73.0/extended darwin/amd64 BuildDate: unknown
```

Dates in posts sources:

- [my-first-post.md](https://raw.githubusercontent.com/retifrav/hugo-timezone-duplicate/master/content/posts/my-first-post.md): `2020-06-29T13:23:11+03:00`
- [my-second-post.md](https://raw.githubusercontent.com/retifrav/hugo-timezone-duplicate/master/content/posts/my-second-post.md): `2020-06-29T13:33:23+02:00`

Rendered dates:

- `/posts/my-first-post/`: `2020-06-29 13:23:11 +0300 +0300` ❌
- `/posts/my-second-post/`: `2020-06-29 13:33:23 +0200 CEST` ✅

**Comment by retifrav** [comment]
Looks like the issue originates in the absence of explicit date format, so instead of just

```
{{ .PublishDate }}
```

there should be

```
{{ .PublishDate.Format "2006-01-02 15:04:05 -0700" }}
```

As [explained](https://discourse.gohugo.io/t/front-matter-datetime-duplicated-timezone-value/17853/9) in the discussion forum, when timezone offset is different from the system timezone, Hugo cannot get the abbreviation (CEST, PDT, etc) and just prints the offset second time. While it is now clear why it happens like this, having doubled timezone doesn't look correct.
