### ISSUE TITLE
Chinese characters may not supported by variable Wordcount

### ISSUE THREAD

**Issue by isnanx** [gohugoio/hugo#5913]
Hi, as I write both Chinese and English in my posts, I found it that Chinese characters were not included when counting the words, I doubt if there is something wrong of my usage or it's truly not supported by now, any reference? Thanks.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
