### ISSUE TITLE
"Code Toggle" is missing from the "Getting Started" table of contents

### ISSUE THREAD

**Issue by cdyson37** [gohugoio/hugo#5916]
The right (">") arrow on the right hand side of the [Directory Structure](https://gohugo.io/getting-started/directory-structure/) page links to "Code Toggle", but this page is not mentioned in the table of contents on the left hand side of the page.

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues
