### ISSUE TITLE
Issue with brew install hugo and code.google.com

### ISSUE THREAD

**Issue by wombart** [gohugoio/hugo#592]
Hi,

it seems there is a issue regarding the openpgp module from google.

Wenn trying 
  brew install hugo

I get this

==> go get
    imports github.com/kr/pretty
    imports github.com/kr/text
    imports github.com/mitchellh/mapstructure
    imports github.com/xordataexchange/crypt/config
    imports code.google.com/p/go.crypto/openpgp: exit status 1

So is there anything I can to do fix this.

Thanks.

Best regards.

**Comment by anthonyfok** [comment]
For reference, @spf13 fixed this bug directly with the commit of:

> c8904756f02948c6f7bb900b05cd0aa6b259088e: Removing dependency on go-html-transform (fixing the build).

There may be other related commits in which the replacement functions were written.
