### ISSUE TITLE
Add image processing support for WebP image resources

### ISSUE THREAD

**Issue by Elinvention** [gohugoio/hugo#5924]
I tried this code

```
{{ $imageResource := .Page.Resources.GetMatch "**/*.webp" }}
{{ $resized := $imageResource.Resize "180x" }}
{{ $resized.RelPermalink }}
```
but I get an error:

```
<$imageResource.Resize>: can't evaluate field Resize in type resource.Resource
```

The .ResourceType is correctly identified as image. If I replace that with a jpg version it works.

**Comment by bep** [comment]
`webp` is currently not supported. I guess that is probably not crystal clear in the documentation, and we should eventually support it.

**Comment by bep** [comment]
https://github.com/disintegration/imaging/issues/25

**Comment by geoffreybauduin** [comment]
@bep do you plan to implement the conversion and webp manipulation?

My guess would be to implement a `Convert` function on the resource where you can send a configuration string indicating how to convert. Assuming we'd go for https://github.com/chai2010/webp, we could have the following markup:

```
{{ $webp := (resources.Get "image.jpg").Convert "format=webp lossless=true" }}
```
Code-wise, we'd have to parse the argument to convert, but this would allow using it for other conversions in the future.

**Comment by bep** [comment]
@geoffreybauduin one the API side this is mostly about adding another MIME type / image format. But that just scratches the surface of this. The main problem here is that there is no native Go webp encoder.

**Comment by geoffreybauduin** [comment]
Is having a native webp encoder a must-have for you or would you be fine with a C library?

**Comment by arthurchaloin** [comment]
what is the status of this feature? are you considering using https://github.com/chai2010/webp or will you be waiting for a native go library?

**Comment by pawelurbanski** [comment]
@libvips/libvips is a fantastic library that has a Go binding. It is not Go-native, though.

**Comment by robsonsobral** [comment]
Does [it](https://pkg.go.dev/golang.org/x/image/webp?tab=doc) helps?

**Comment by maruel** [comment]
@robsonsobral  I think it would enables implementing imageConfig, but not manipulation.

**Comment by blaubaer** [comment]
I invested some time to bring WebP encoding to work, via PR #7155. Let's see if the approach will be accepted. 😄

**Comment by awhitford** [comment]
Supporting WebP is great.  However, please be careful not to assume that WebP is always smaller than a JPEG.  I was thrilled to see WebP crush certain JPEG photos, but was also surprised that sometimes WebP created larger files than the original JPEG.  As a result, we may also need a function that serves the files in order by size -- not just format.

**Comment by blaubaer** [comment]
That's true. This might be easy possible in the moment when hugo is at least supporting WebP.

Once we're able to create all formats, we can for example create short codes which are can doing this for us. Before that we need at first:

1. the general support to create WebP images. Currently this seems to be stuck because the PR #7155 was closed with the reference that this issue here (#5924) needs at first be clarified. But unfortunately this seems to be stuck, too. 😞 

2. Add a function to determine the sizes of [page resources](https://gohugo.io/content-management/page-resources/).

3. Create a short code that covers at least the cases where an image will be directly embedded in the content. This should following the logic as described in [this article](https://medium.com/front-end-weekly/html-picture-tag-in-practice-png-and-webp-formats-5a3fc51b5998).

4. Optionally: It might be possible to create a format which we call `optimal-photo` where which we can use as follows:
    ```html
    {{ $image.Resize "600x optimal-photo" }}
    ```

    instead of specific types:
    ```html
    {{ $image.Resize "600x jpeg" }}
    <!-- OR -->
    {{ $image.Resize "600x webp" }}
    ```

**Comment by tjamet** [comment]
Having webp would be nice indeed.

I understand the concerns about not having it as native go library, and having to maintain the binding here as explained in #7155 

What about declaring the feature experimental using https://github.com/chai2010/webp as @arthurchaloin  proposed?

Having it experimental, disabled and not shipped by default, would allow restricting support for it, and even dropping the feature at any time if the maintenance burden appears too high.

In this branch: https://github.com/tjamet/hugo/commit/webp I have a proposal to do so, having webp users to build their own binary using `go build --tags webp github.com/gohugoio/hugo`

Finally, one thought about
> a format which we call `optimal-photo`

IMHO this settings of picture tags should be in the templating side, not in the engine. Picture alternatives has a big adherence with the outer page layout and trying to support all possible things with media selectors, tags, ids, among others would be a pain.
We already have the ability to re-use snippets, and it should be possible to create a snippet that generates the image with something similar to

```
<picture>
    {{- $large := $image.Resize "2840x png" -}}
    {{- $small := $image.Resize "1920x png" -}}
    <source type="{{ $large.MediaType }}" media="(min-width: 1921px)" srcset="{{ $large.RelPermalink }}">
    <img src="{{ $large.RelPermalink }}" style="width: 100%;">
</picture>
```

**Comment by blaubaer** [comment]
@tjamet I've also looked at https://github.com/chai2010/webp but the issues with this one is that this is not a pure GoLang dependency. Otherwise I might have used it already. It requires a GCC to be installed, which makes it quite challenging to use/compile/build on some systems.

**Comment by pawelurbanski** [comment]
What about: https://github.com/libvips/libvips
It points to Go bindings in the readme. It is not native Go, but maybe bindings are somehow easier to handle?
Plus it seems to handle every possible image format under the Sun…

**Comment by willduncanphoto** [comment]
webp support would be dope. Wish I could be more help on implementation. Way over my head.  But the fact that it's even a discussion has me excited. I'm working on simple themes for photographers/journalist to self publish, reduce hosting costs, and modernize their websites/portfolios. The only publication I really see using webp extensively so far is the Washington Post.

In almost all my tests I see compressions pushing photographs to 1/5 the size with next to no loss.

**Comment by blaubaer** [comment]
It is actually implemented. But my PR just was closed and this discussion stalled here. I might be happy to know what I can do instead nothing.

I would be happy to reopen #7155 again and change what needs to be changed...

**Comment by balibebas** [comment]
> I guess that is probably not crystal clear in the documentation, and we should eventually support it.

Eventually came and left. I'd say the docs are pretty clear as when you search for WebP you get pages about Webpack.

**Comment by balibebas** [comment]
> I guess that is probably not crystal clear in the documentation, and we should eventually support it.

Eventually came and went. I'd say the docs are pretty clear as when you search for WebP you get pages about Webpack.

**Comment by balibebas** [comment]
> I guess that is probably not crystal clear in the documentation, and we should eventually support it.

Eventually came and went. I'd say the docs are pretty clear as when you search for WebP you get pages about Webpack. What about this implementation? Does it work: https://github.com/khusika/hugo/commit/81b23343dcb684d202daa45c08c0181fd146f9d6

**Comment by Parent5446** [comment]
> the libraries used currently do not have this included

Just curious, which library is Hugo using for image processing? And has any upstream feature request been filed to them to support WebP? I imagine the easiest solution to Hugo would just be for the underlying library to have it added.

**Comment by onedrawingperday** [comment]
> Just curious, which library is Hugo using for image processing? And has any upstream feature request been filed to them to support WebP? 

Hugo uses https://github.com/disintegration/imaging

There have been [related](https://github.com/disintegration/imaging/search?q=webp&type=issues) issues and pull requests.

**Comment by pawelurbanski** [comment]
Maybe it would be beneficial to consider AVIF as it was posted in some other thread?
AVIF will be gaining in popularity and support. It isdemanding when encoding, but delivers fantastic compression. The libraries are currently in RUST and C though. Once mobile Chromium catches up with support it will have a rather significant marketshare.

**Comment by moorereason** [comment]
@pawelurbanski, this issue is about WebP.  AVIF discussions should be in #7837.

**Everyone**,
Until a native Go implementation exists (no cgo library bindings), Hugo will not support WebP.  We know about `golang.org/x/image/webp`, but it's only a decoder right now (doesn't support encoding).

**Comment by blaubaer** [comment]
I can just recall that there was a solution available and it is still available #7155

**Comment by moorereason** [comment]
@blaubaer, your PR exec's `cwebp` for writing.  That's not native Go.

**Comment by idarek** [comment]
How about something like
https://github.com/chai2010/webp
and 
https://github.com/nickalie/go-webpbin
?

**Comment by moorereason** [comment]
@idarek, both of those projects bind to a C library.  That's not native Go.

**Comment by blaubaer** [comment]
@moorereason There is currently not planned any native implementation of WebP in Golang (for encoding). Therefore there are only 2 ways to support that: Either calling a binary OR embedding C-Code directly into the library.

For sure we can wait until someone is doing it (the porting - you're free to code) and do not implement such important stuff into Hugo (which seems to be important for SEO ratings too - if it is important for [Lighthouse](https://developers.google.com/web/tools/lighthouse/) we can assume it is important for Google, too) OR implement one of the 2 options named above.

For now I solved me issue (although it is not great) with a image proxy that is doing transparent WebP encoding for me. Sad to use such stuff.

**Comment by idarek** [comment]
@blaubaer may hit a point. If you look [google page](https://developers.google.com/speed/webp) they also referring to use cwebp to convert images. Because of that I don't believe creating native Go converter will happen in a future. 

@pawelgrzybek recently posted [his method](https://pawelgrzybek.com/webp-and-avif-images-on-a-hugo-website/) of implementing WebP and AVIF into Hugo using rendering hooks. The encoding is done prior to Hugo build and is not using image.resize aspect, however the output and performance (from PageSpeed Insight view) is impressive.

**Comment by jmooring** [comment]
@pawelurbanski: you can obtain the width and height of a webp image using the [`imageConfig`](https://gohugo.io/functions/images/#imageconfig) function.

For a page resource:

```
{{ $resource := .Resources.GetMatch "a.webp" }}
{{ $path := path.Join "content" $resource.RelPermalink }}
{{ $imgAttributes := imageConfig $path }}
Width: {{ $imgAttributes.Width }}
Height: {{ $imgAttributes.Height }}
```

For a global resource:

```
{{ $resource := resources.Get "a.webp" }}
{{ $path := path.Join "assets" $resource.RelPermalink }}
...
```

If using a global resource, it must be in the `assets` directory. It cannot be in a directory that is [mounted](https://gohugo.io/hugo-modules/configuration/#module-config-mounts) to `assets`.

**Comment by tristan957** [comment]
I don't think that would work if you fingerprint your images.

**Comment by andreseduardop** [comment]
> For a page resource:
> 
> ```
> {{ $resource := .Resources.GetMatch "a.webp" }}
> {{ $path := path.Join "content" $resource.RelPermalink }}
> {{ $imgAttributes := imageConfig $path }}
> Width: {{ $imgAttributes.Width }}
> Height: {{ $imgAttributes.Height }}
> ```

Thanks, @jmooring 
:+1: 
It is the only way that has worked for me to generate the necessary information (width / height) inside the <img> tag

**Comment by MartinHotmann** [comment]
Dont want to sound rude but you guys dont also think its fucking dissapointing that the legendary Imageformat (WEBP) which is developed by Google is not usable in Googles own programming language? While WEBP was found back in 2010 ..

I think its a shame. Not on Hugo, but on goLang in general
