### ISSUE TITLE
Support directory symlinks inside content/

### ISSUE THREAD

**Issue by acalvo** [gohugoio/hugo#5927]
We are building a site translatable into multiple languages, but with a certain section which makes no sense to translate: it should be displayed as-is (in the default language, English) in every language. The reason behind this, if you wonder, is that it's autogenerated API documentation. Moreover, we set custom URLs for this pages in the front matter.

Up until now, we were copying this untranslatable content in every language-folder, and modifying the URL in each front matter to match the one of the corresponding language. Something like this:

```
en/
  api/
    ...
    autogenerated/
      FirstClass/
        FirstClass.md [url: "api/FirstClass"]
      SecondClass/
        SecondClass.md [url: "api/SecondClass"]
    ...
es/
  api/
    ...
    autogenerated/
      FirstClass/
        FirstClass.md [url: "es/api/FirstClass"]
      SecondClass/
        SecondClass.md [url: "es/api/SecondClass"]
    ...
```

It works as expected. But, now with Hugo >=0.55 it is not necessary anymore to add the language bit in the custom URL, so the content of our autogenerated `md` files would be identical across languages. That's why we wanted to get rid of the copying and make use of symlinks.

Creating symlinks to each `md` works like a charm. Something like this:

```
en/
  api/
    ...
    autogenerated/
      FirstClass/
        FirstClass.md [url: "api/FirstClass"]
      SecondClass/
        SecondClass.md [url: "api/SecondClass"]
    ...
es/
  api/
    ...
    autogenerated/
      FirstClass/
        FirstClass.md -> ../../../../en/api/autogenerated/FirstClass/FirstClass.md
      SecondClass/
        SecondClass.md -> ../../../../en/api/autogenerated/SecondClass/SecondClass.md
    ...
```

But this makes us build the whole directory structure just to make the symlinks, which makes little sense. It would be much better to have something like this:

```
en/
  api/
    ...
    autogenerated/
      FirstClass/
        FirstClass.md [url: "api/FirstClass"]
      SecondClass/
        SecondClass.md [url: "api/SecondClass"]
    ...
es/
  api/
    ...
    autogenerated -> ../../en/api/autogenerated
    ...
```

...and this last experiment does not work (gives an error of duplicate identifications on compile). I've been debugging Hugo a bit to see what was going on, and the problem seems to origin in here: https://github.com/gohugoio/hugo/blob/master/hugofs/language_fs.go#L296

Symlinks to folders do enter in that `if` clause, giving them a `virtualname` with the lang mark as if they were regular files. This makes `LanguageDirsMerger` function ( https://github.com/gohugoio/hugo/blob/master/hugofs/language_fs.go#L56 ) keep both references to `autogenerated` dir and traversing them twice (giving the duplicate id error). If symlinks to folders were treated as folders and didn't enter that `if` clause, just one reference to the folder would be stored and every would go OK.

Does this debugging make sense, or did I miss something? Any chance it gets fixed? Thanks! 😀

**Comment by glerchundi** [comment]
Friendly ping, what do you think about this @bep? Thanks!

**Comment by bep** [comment]
@glerchundi I'm sorry, but reading this isn't a priority for me now. I can say this that most of this is will be totally rewamped for the next Hugo. Whether that will somehow solve your problem, I don't know (because I don't know what your problem is).

**Comment by glerchundi** [comment]
Hei, thanks for answering. My problem is the same one explained in [this comment](https://github.com/gohugoio/hugo/issues/5927#issue-439931457) 😛
