### ISSUE TITLE
hugo output error

### ISSUE THREAD

**Issue by nusr** [gohugoio/hugo#5928]
Mac OS 10.14.4 , Go 1.12.4 .,Hugo v0.55.3/extended 

The output is error.

<img width="367" alt="屏幕快照 2019-05-03 下午11 41 06" src="https://user-images.githubusercontent.com/12200340/57149555-89a62a80-6dfe-11e9-98a7-0d8a75895e00.png">

If I change the **index.md** file name, the output is right.Is it a bug?

<img width="367" alt="屏幕快照 2019-05-03 下午11 42 55" src="https://user-images.githubusercontent.com/12200340/57149575-97f44680-6dfe-11e9-853b-dcc4b3be27dc.png">

New user can only post one image in https://discourse.gohugo.io .

**Comment by bep** [comment]
>New user can only post one image in https://discourse.gohugo.io .

I understand that, but then you need to find another place to post your images.
