### ISSUE TITLE
deploy: Deployment to subfolders of a bucket

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5930]
Deployment to subfolders of a bucket, esp. see this commit: https://github.com/bep/s3deploy/commit/56b818b1a4cb5561bd67968236ea600cff56f1b9

**Comment by vangent** [comment]
I'm trying to add better support in Go CDK for this to simplify the code in Hugo.

**Comment by bep** [comment]
Great; a quick note here:

* When a Hugo site is configured with a `baseURL` with a sub-path, I suspect that one would always have this put in its subfolder matching that configuration.
* E.g. https://github.com/bep/hugotest/blob/master/config.toml#L1
* A have a fair amount of similar sites, call it the "poor man's Netlify" or something, as the only thing needed for a new site is a new CDN config with `OriginPath` set to that subfolder.
* I wouldn't be super happy if I had to maintain this in two places.

**Comment by vangent** [comment]
@bep -- my current plan is to support `blob.Bucket` sub-paths via a query parameter in the Go CDK URL. For example, `s3://my-bucket?region=us-west-1&prefix=mysubfolder/` would deploy to `my-bucket` in `mysubfolder/`.

This would mean that there's no explicit new configuration needed in Hugo itself for this feature.

It sounds like that may not be ideal; in your example, you would have `baseURL="https://temp.bep.is/hugotest/"` in your config and then a `deployments` section later on with a target Go CDK URL with a `prefix=hugotest/` query param in it.

Are you suggesting that "hugo deploy" should look at the configured `baseURL`, check if it has a sub-path, and automatically add a `prefix` query parameter to the Go CDK URL if so?

**Comment by bep** [comment]
>Are you suggesting that "hugo deploy" should look at the configured baseURL

I have not thought too hard about this, but what I'm saying is that it should fit together with the rest and by using this you should get some benefits from it being an integrated solution (as opposed to using something ala s3deploy). Having the configuration in one place is a start.  But I think we should also try to avoid double configuration if possible.

So,

So, a little simplied, If I configure `baseURL=https://temp.bep.is/hugotest/` the files will end up below `public/`, but `hugo server` will serve them from `hugotest/` where all the links will point.

If I run `hugo deploy` and the files, end up at the root, that will be surprising behavior to me. I can currently not think of any situation where you would want it to end up somewhere else. So unless someone can, I suggest we just use that value and consider adding some override later.

This also ties into the CDN cache logic when that evolves beyond the `/*`.

**Comment by bep** [comment]
... but note that I'm not totally sure about the above, so please shout if you disagree...

**Comment by bep** [comment]
I have thought a little about it, and I think we're going to stick with your plan and just use the value in `prefix` on the `deployment` config, if set.

Thinking about it, the `baseURL` can have multiple values. We have something called multihost mode for multiple languages, so will typically have:

* https://example.com
* https://example.jp

But it would also be possible to use:

* https://example.com/foo
* https://example.jp/bar

I guess the above ties into when we want to make more granular CDN cache invalidations, but that time, that sorrow.

**Comment by vangent** [comment]
OK, thanks @bep. I just added the "prefix" feature to Go CDK, so once there's a release with it (should be next couple of weeks) I can upgrade Hugo.

Note that my proposal is not a separate `prefix` field in the `deployment` config; rather, the `prefix` (if desired) is part of the URL. For example, `s3://my-bucket?prefix=mysubfolder/` instead of `s3://my-bucket`. I think that still makes sense in light of your last comment, but we'll need to make sure it's documented well.
