### ISSUE TITLE
hugo generates different content when re-run due to randomized ordering

### ISSUE THREAD

**Issue by vangent** [gohugoio/hugo#5934]
To reproduce:

1. Use the latest `hugo` on the `hugoDoc` repo.
2. Run `hugo` to generate the site.
3. Save a copy of the site: `cp -r public public_v1`
4. Run `hugo` again to regenerate the site (no content has changed).
5. Compare: `diff -rq public public_v1`.

Expected: no diffs.
Actual: a couple of `index.html` files have changed. It appears that there's some randomization when ordering links...?

**Comment by bep** [comment]
This is by design. We have a ... `shuffle` func.

**Comment by vangent** [comment]
Interesting. What's the use case for different content each time? It doesn't play particularly nice with the new `deploy` command since you re-upload the page every time.

Also, in https://github.com/google/go-cloud/issues/1994 we're seeing a different `sitemap.xml` each time `hugo` is run (with a [similar delta](https://github.com/google/go-cloud/commit/332c1bde650b09ca2589871809e0ae6) that appears due to random ordering), is `shuffle` used there as well?

**Comment by eliben** [comment]
The default sitemap.xml template (https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/sitemap.xml#L4) seems to use `range` which is unstable over maps? Should it be `range sort`? Or does Hugo expect `range` to be stable when given a map?

**Comment by vangent** [comment]
This is still an issue:

```
# clone of hugo
$ cd docs
$ hugo
...
$ mv public /tmp/public
$ hugo
...
$ diff -rq /tmp/public public
Files /tmp/public/index.html and public/index.html differ
Files /tmp/public/showcase/index.html and public/showcase/index.html differ
```
