### ISSUE TITLE
deploy: Add a better end-to-end test

### ISSUE THREAD

**Issue by vangent** [gohugoio/hugo#5936]
There are some good unit tests, but it would be nice to have a test that does something like:

* Creates a `afero.NewMemMapFs`.
* Creates a bunch of files in that Fs.
* Creates a `Deployer` using a Go CDK `mem://` URL.
* Does a `deployer.Deploy` and verifies that the appropriate number of changes were applied, and that the target looks correct.
* Does another `Deploy` and verifies no changes.
* Add/update/delete a file in the source Fs, re-Deploy and verify that each of the changes are made.
* Etc.

**Comment by bep** [comment]
I just merged a related change, but I'll throw this in as a potential test case, as it was something I remember having a hard time to get right the first time I implemented something similar: The MD5 you get from S3 (and I assume the others) will be of the compressed file, so you would need to compress it before creating the hash for compare.

**Comment by vangent** [comment]
That's a great idea. I'll keep working on this, don't review yet. I need a PR open in order to see the runs on Windows :-(.

**Comment by vangent** [comment]
#5938 is ready for review now.
