### ISSUE TITLE
Add a new alias for the theme config

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5941]
This is related to #5911 

So I have a test site with this inside `config.toml`:

```
theme = [
    "github.com/bep/hugotestmods/mypartials",
    "github.com/bep/hugotestmods/myshortcodes",
    #"github.com/bep/hugo-fresh",
    #"github.com/jeblister/kube"
    "github.com/spf13/hyde"
    #"github.com/alex-shpak/hugo-book"
]
```

In some sense it makes sense to say that "the components in the list makes a theme", but we could probably also create a new alias term that better covers this.

My thoughts about this is to use the word `import` which would be familiar to people doing development.

So `import` (singular) represents a ordered list of imports, _import this_:

```
import = [
    "github.com/bep/hugotestmods/mypartials",
    "github.com/bep/hugotestmods/myshortcodes",
    #"github.com/bep/hugo-fresh",
    #"github.com/jeblister/kube"
    "github.com/spf13/hyde"
    #"github.com/alex-shpak/hugo-book"
]
```

Thoughts? @kaushalmodi @spf13 @regisphilibert @budparr @onedrawingperday @digitalcraftsman and gang.

We should probably also consider the above vs having the import in its own file below /config that can be set per env.

**Comment by onedrawingperday** [comment]
This alias will help newer users get a better grasp of what `theme` stands for in a hugo project's config.

So +1 from me.

**Comment by lebarde** [comment]
I like this idea!
- What would be the priorities for the files used in themes?
- and do you think there should be stricter conventions in themes (at least those presented on the gohugo site) to ensure that stylesheets, partials and all this combine well together into bundles?

I'm more fond of the import rule in that it would be more easy to create strict conventions from scratch.

**Comment by bep** [comment]
@lebarde the priority is documented, and I'm not a big fan of taking a very specific issue and make it about something slightly related.

As to _this particular issue_, I have thought a little, and I think that:

```toml
[module]
import = [
"foo",
"bar"
]
```

Which 1) Makes it possible to put `module.toml` below /config and have easy overrides per environment and 2) Makes room for other related config in the future.

**Comment by lebarde** [comment]
This seems nice to me. About priorities, I was not talking about generic priorities. What if some user wrote:

```
import = [
    "github.com/bep/hugotestmods/someshortcodes",
    "github.com/spf13/someothershortcodes"
]
```
What about a conflict if both repositories created a shortcode/layout/other file with the same path? Say, both created a `layouts/shortcodes/notice.html` file? Would there be a priority (e.g. the last overrites) or naming conventions (`layouts/shortcodes/bep-hugotestmods_notice.html` and `layouts/shortcodes/spf13-someothershortcodes_notice.html`)?

**Comment by regisphilibert** [comment]
https://gohugo.io/themes/theme-components/#readoutJust like current way of things.

**Comment by lebarde** [comment]
Ooops sorry, I had missed it ^^

Thank you both for that explanation :-)
