### ISSUE TITLE
deploy: Write documentation

### ISSUE THREAD

**Issue by vangent** [gohugoio/hugo#5943]
@bep can you suggest where this documentation should go?

https://gohugo.io/hosting-and-deployment/ ?

**Comment by bep** [comment]
Yes, add a new page below

https://github.com/gohugoio/hugoDocs/tree/master/content/en/hosting-and-deployment

We will make it more prominent later, but I suggest you create a new page call `hugo-deploy` with the title `Hugo Deploy` (which marks it as a built-in feature).
