### ISSUE TITLE
Params lower case issue with .GetPage

### ISSUE THREAD

**Issue by marcojakob** [gohugoio/hugo#5946]
For normal pages something like `.Params.myParam` works (it used to be an issue but got fixed in #2590 and #2630).

But for `.Site.GetPage` it does not work. This is how I use it - mostly with headless pages:

### Markdown in "content/settings/general/index.md"

```
+++
headless = true
myParam = "some value"
+++
```

### Template in "layouts/index.html"

```
{{ $settingsPage := .Site.GetPage "/settings/general" }}
{{ $settingsPage.Params.myParam }} 
```

The last line does not return any value while `{{ $settingsPage.Params.myparam }}` does return the correct value.

**Comment by bep** [comment]
I suspect this must be "something else", e.g. you're not getting the page you think you do, a conflicting session? Do you get any output with `{{ $settingsPage.Params.myparam }}`?

**Comment by marcojakob** [comment]
I've tested it with Hugo v0.59.1 and it is still an issuel.

Sorry, for not answering earlier. Somehow missed your question @bep:

> I suspect this must be "something else", e.g. you're not getting the page you think you do, a conflicting session? Do you get any output with {{ $settingsPage.Params.myparam }}?

Yes, I'm getting the right page and I do get a result for `{{ $settingsPage.Params.myparam }}` but no result for `{{ $settingsPage.Params.myParam }}` (with capitalized "P").

The original issue was a misleading because it doesn't matter if it is headless or not (I'll change that). It is a problem with `.Site.GetPage`.
