### ISSUE TITLE
Highlighting transpose for scientific languages

### ISSUE THREAD

**Issue by matbesancon** [gohugoio/hugo#5951]
The bug is likely in Chroma, so I posted it [here](https://github.com/alecthomas/chroma/issues/253), but could it possibly be highlight or hugo-related?

**Comment by matbesancon** [comment]
bump, the issue in chroma has been fixed on their master

**Comment by matbesancon** [comment]
go away bot

**Comment by bep** [comment]
I think we're on the latest Chroma? At least in master.

**Comment by matbesancon** [comment]
Ok thank you, I can close it for now, I'll try to do tests later but the transpose is already tested on Chroma
