### ISSUE TITLE
TableOfContent incorrect if title mar in shortcode

### ISSUE THREAD

**Issue by serako** [gohugoio/hugo#5952]
Hi,
If i put a title in "inner" shortcode the .TableOfContent ignore this.

```
{{% flex %}}
   {{% flex-column %}}
      ## My title A
      Blabla
   {{% /flex-column %}}
   {{% flex-column  %}}
      ## My title B
      blabla
   {{% /flex-column %}}
{{% /flex %}}
```

flex.html
```
<div class ="flex-container">
  {{ printf "%s" .Inner | safeHTML }}
</div>
```
flex-column.html
```
<div class="flex-column" >
  {{ printf "%s" .Inner | safeHTML }}
</div>
```

I try with V0.55 extend on linux deb

**Comment by bep** [comment]
I suspect this is a space issue. Could you try to pull the titles to the left.

**Comment by serako** [comment]
yes space! i correct my code! but...

test.html

`{{ .Inner }}`


```
{{% test %}}

## My title A

Blabla
{{% /test %}}
```
In page My title A like  `<h2>`  and is in TableOfContent
now

```
{{% test %}}
{{% test %}}

## My title A

Blabla
{{% /test %}}
{{% /test %}}
```
In page My title A like `<h2>` but is NOT in TableOfContent

same with {{ printf "%s" .Inner | safeHTML }} in test.html.

**Comment by bep** [comment]
Is this Hugo 0.55.5?

**Comment by serako** [comment]
hugo_extended_0.55.5_Linux-64bit.deb

**Comment by bep** [comment]
You need to do something like this:

```
{{% test %}}
{{< test >}}

## My title A

Blabla
{{< /test >}}
{{% /test %}}
```

**Comment by serako** [comment]
this work fine! But now in my really case my "test.html" is like
```
<div>

{{ .Inner }}

</div>
```
my output is :  ## My title A Blabla  (and not in TOC)
