### ISSUE TITLE
How to publish on GitHub, I have read the manual, but there is a error.

### ISSUE THREAD

**Issue by noweaver** [gohugoio/hugo#5955]
I have read this page, https://gohugo.io/hosting-and-deployment/hosting-on-github/. I encountered the problem in "Step-by-step Instructions" section.

My step is following as;

1. I created two GitHub repositories 'noweaver' and 'noweaver.github.io'.
2. And then, on my Macbook.

```shell
$ hugo new site noweaver
$ cd  noweaver
$ git init
$ git submodule add https://github.com/taikii/whiteplain.git themes/whiteplain

$ vi config.toml
...
:wq!

$ git init
$ git remote add origin https://github.com/noweaver/noweaver.git
$ git submodule add -b master https://github.com/noweaver/noweaver.github.io.git public/
loning into '/Users/ryan/Workspace/GitHub/noweaver/public'...
warning: You appear to have cloned an empty repository.
fatal: 'origin/master' is not a commit and a branch 'master' cannot be created from it
Unable to checkout submodule 'public'
```

I don't know those error messages; `fatal~`

**Comment by gabrielerzinger** [comment]
I believe you have to add 'public' to the end of the command, per the link you used:

git submodule add -b master git@github.com:<USERNAME>/<USERNAME>.github.io.git public

**Comment by noweaver** [comment]
> I believe you have to add 'public' to the end of the command, per the link you used:
> 
> git submodule add -b master [git@github.com](mailto:git@github.com):/.github.io.git public

Sorry, I missed the 'public' above comment. Actually, I wrote the 'public'. Anyway, I fix my issue.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
