### ISSUE TITLE
Get keys of a dictionary

### ISSUE THREAD

**Issue by notramo** [gohugoio/hugo#5959]
Please add a `keys` function that returns all keys in a dictionary.

**Comment by BaibhaVatsa** [comment]
Hi! I wished to work on this issue. Should I write this new function `Keys` in `collections.go` in `tpl/collections` directory?

**Comment by bep** [comment]
`collections.Keys` would make a good signature. And I guess they should be sorted, if possible.

**Comment by BaibhaVatsa** [comment]
Sorry but I am a little confused. What do you mean by "other string sorting"? Do you mean sorting algorithms or inbuilt functions for sorting in Go or does a sorting function already exist in the collections or some other package in Hugo?

**Comment by bep** [comment]
I meant this https://github.com/gohugoio/hugo/blob/master/compare/compare_strings.go#L111

**BUT** ignore that comment. Thinking about this one more time I think that:

```bash
{{ keys := slice }}
{{ range $k, $v := range $map }}
{{ $keys = append $keys $k }}
{{ end }}
```

Should be the same as

```bash
{{ keys := collections.Keys $map }}
```

The Go templates uses it's own sorting (in the fmt package?), which I suspect uses simple string compares.

**Comment by bep** [comment]
But, taking a step back: What would be the use case for this function?

**Comment by bep** [comment]
I'll put this on hold, let us consider this one later.

**Comment by BaibhaVatsa** [comment]
I am very new to Hugo so I might be wrong about this but one use case can be that someone can have a dictionary which maps dates to a collection of articles posted on those dates. Ability to get a list of all keys in that case would mean easier way to create a list of all those dates which can then expand to show list of articles and then that can lead you to the article itself.

**Comment by snicoll** [comment]
I have a use case for this, but maybe I am using the wrong function.

I have a "country" taxonomy (using the ISO code). On the list page, I'd like to list all countries, ordered alphabetically against their name. My idea is to build a dictionary from Title to `Page`. I'd like then take the keys to sort them and iterate over `Page` + human-readable title.

**Comment by jmooring** [comment]
This need for this is infrequent, and more importantly, easily captured with:

```text
  {{ $m := dict "c" 1 "a" 2 "b" 3 }}

  {{ $keys := slice }}
  {{ range $k, $_ := $m }}
    {{ $keys = $keys | append $k }}
  {{ end }}

  {{ $keys }} --> [a b c]
```
