### ISSUE TITLE
Make Goldmark the new default markdown renderer

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5963]
https://github.com/yuin/goldmark

**Comment by bep** [comment]
I've been looking for a solid CommonMark compliant MD processor for a long time, and from what I've seen the above looks very solid.

/cc @kaushalmodi @spf13 and gang.

/cc @yuin I assume you wouldn't mind if we used this in Hugo? I notice that it's already at > v1 so that looks promising.

**Comment by yuin** [comment]
@bep Yes, goldmark passed all [commonmark 0.29 spec tests](https://github.com/yuin/goldmark/blob/master/commonmark_test.go) . Extensions are also tested.

Extensibility that blackfridy does not have should come in useful for applications like Hugo, I would be glad if goldmark could help to Hugo :)

**Comment by kaushalmodi** [comment]
@bep Looks great! Please let this upgrade marinate in the master branch for a while (1 week or so) so that I can upgrade `ox-hugo` in parallel to support it.

**Comment by evankanderson** [comment]
Is this in progress or in the icebox pending developer work?

**Comment by evankanderson** [comment]
Is there a branch this is happening in?

We see *really* atrocious markdown generation on e.g. https://knative.dev/docs/install/knative-with-aks/#installing-knative, so I'm motivated to fix.

(Compare with https://github.com/knative/docs/blob/master/docs/install/Knative-with-AKS.md#installing-knative, which is using GitHub's markdown renderer.)

**Comment by cup** [comment]
Yes please.

Blackfriday, Mmark and others have parsing issues:

- https://github.com/gomarkdown/markdown/issues/134
- https://github.com/mmarkdown/mmark/issues/98
- https://github.com/russross/blackfriday/pull/358

and Goldmark works as expected with my testing.

**Comment by jimangel** [comment]
Enthusiastic +1!

We are seeing some issues with code-block and list rendering on https://kubernetes.io ([example](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components)) since updating to a Hugo .57 (tested on .59 too), it seems to be related to blackfriday.
