### ISSUE TITLE
shortcodes and scripts not evaluated in .Summary

### ISSUE THREAD

**Issue by Lithimlin** [gohugoio/hugo#5966]
This is somewhat similar to [another issue](https://github.com/gohugoio/hugo/issues/3235), but I think it is different enough to get its own issue.
`{{ .Summary }}` currently does not evaluate scripts from shortcodes.

### Example:
I'm using the [hugo-cloak-email theme](https://github.com/martignoni/hugo-cloak-email)/shortcode to cloak email addresses on my website. I'm using it on several pages, including some posts.
On my start page, I'm listing new posts with their summaries. Unfortunately, instead of evaluating the `cloak-email` shortcode script, it displays it in the summary:

Part of the summary and then in the middle of the sentence, a wild .cloaked-e-mail:before { content:attr(data-domain) "\0040" attr(data-user); unicode-bidi:bidi-override; direction:rtl; } var scriptTag = document.getElementById("e159018c021ece52c188cd9c35f6bd45"); var link = document.createElement("a"); var address = "nielgnetsh".split('').reverse().join('') + "@" + "ed.tsi-sf".split('').reverse().join(''); link.href = "mailto" + ":" + address; link.innerText = address; scriptTag.parentElement.insertBefore(link, scriptTag.previousElementSibling); scriptTag.parentElement.removeChild(scriptTag.previousElementSibling) appears! This is really ugly :(

**Comment by bep** [comment]
Thanks, but we don't need more than one issue to track this. 

#3235
