### ISSUE TITLE
customizing html tags

### ISSUE THREAD

**Issue by const-g** [gohugoio/hugo#5967]
Hello, I'd like to know if it's possible to filter the content to modify html tags during the build. Per example, to add a css class to all urls in the content, or to add the new `loading="lazy"` to all images of the content.

Thank you

**Comment by peaceiris** [comment]
@const-g 

You can use [replace | Hugo](https://gohugo.io/functions/replace/)

```
{{ .Content | replaceRE "<p>" "<p class=\"myclass\">" | safeHTML }}
```

**Comment by const-g** [comment]
Ah thanks, will try :)

**Comment by XhmikosR** [comment]
@bep this can be closed
