### ISSUE TITLE
Check live reload vs. .Render

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5969]
https://discourse.gohugo.io/t/i-have-to-run-hugo-serve-everything-i-change-a-html-file/18762/2

**Comment by bep** [comment]
I have tested this locally, and cannot reproduce.

**Comment by eele94** [comment]
Thanks for opening this ticket.

I made a new project and reproduced the problem.
You can clone the project if you want:
https://gitlab.com/eele94/camping

hugo serve -D
go to http://localhost:1313/test/a

change test/single.html and livereloading is not working.

Thanks already!

**Comment by eele94** [comment]
> I have tested this locally, and cannot reproduce.

Thanks for opening this ticket.

I made a new project and reproduced the problem.
You can clone the project if you want:
https://gitlab.com/eele94/camping

hugo serve -D
go to http://localhost:1313/test/a

change test/single.html and livereloading is not working.

Thanks already!

**Comment by eele94** [comment]
@bep hi have you had time to test it?

**Comment by bep** [comment]
No.
