### ISSUE TITLE
Bad, bad error message

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#597]
I'm converting a WP site to Hugo.

Among the steps taken is to write some cleaning-scripts ... Apparently I did something wrong (or my regexp was a little bit too greedy):

`ERROR: 2014/10/30 Unable to read frontmatter at filepos 2545: EOF`

Which file?

**Comment by DanRunfola** [comment]
Managed to come across this today (files to replicate:
https://github.com/DanRunfola/DanRunfola.github.io/tree/fc62523db31e29367553f68254f6f3cab2b77e3e
):

DEBUG 2018/02/07 14:21:14 Template path /home/datalab/Desktop/Git/DanRunfola.github.io/themes/academic/layouts/talk/single.html
DEBUG 2018/02/07 14:21:14 Add template file from path /home/datalab/Desktop/Git/DanRunfola.github.io/themes/academic/layouts/talk/single.html
DEBUG 2018/02/07 14:21:15 Load Data from 2 source(s)
ERROR 2018/02/07 14:21:15 unable to read frontmatter at filepos 249: EOF
ERROR 2018/02/07 14:21:15 unable to read frontmatter at filepos 467: EOF
ERROR 2018/02/07 14:21:15 unable to read frontmatter at filepos 235: EOF

**Comment by HunterGraubard** [comment]
I came across this today.
