### ISSUE TITLE
Permalink with custom output

### ISSUE THREAD

**Issue by akshaybabloo** [gohugoio/hugo#5978]
After 0.55 all the AMP pages with `{{ .permalink }}` have `/amp/` in them, so, for example, the canonical link in an AMP page with:

```html
<link rel="canonical" href="{{ .permalink }}"/>
```

renders as

```html
<link rel="canonical" href="http://localhost:1313/amp/blog/some-page/"/>
```

which is wrong, it would be nice if we can get a custom URL with something like `{{ .permalink "html" }}` without disabling `permalinkable`. If no argument is passed through, let it default to the current output.

**Comment by bep** [comment]
What you need to do is something ala:

{{ with .OutputFormats.Get "html" }}
<link rel="canonical" href="{{ .Permalink }}"/>
{{ end }}
