### ISSUE TITLE
Chroma: Default Setting of `TabWidth` Can't Be Changed

### ISSUE THREAD

**Issue by ewhac** [gohugoio/hugo#5982]
Noticed this last night while playing around with `{{< highlight >}}`.  If I'm reading the code correctly, it looks like the Chroma formatter is being initialized with a hard-coded value for TAB width:

https://github.com/gohugoio/hugo/blob/b5f39d23b86f9cb83c51da9fe4abb4c19c01c3b7/helpers/pygments.go#L303

Further, there appears to be no way for users to change it.

I suggest that the default (whatever it ends up being) be properly documented, and a simple facility provided so users can set it to whatever value they prefer.

**Comment by bep** [comment]
Why is 4 improper?

**Comment by ewhac** [comment]
> Why is 4 improper?

Why are you trying to start a flame war that will accomplish precisely nothing?

Please keep to the point:  The request is for the default to be documented, and for a way for users to change it.

**Comment by bep** [comment]
>Why are you trying to start a flame war that will accomplish precisely nothing?

I'm asking a simple question about this issue's title, which I assume sums up the core of this issue. If that is not the case, you should consider changing the title. I do, however, agree that we need some way to set the `TabWidth`.

**Comment by ewhac** [comment]
What's improper is that a default value was arbitrarily established, *not documented*, and no mechanism put in place to change it.

I have changed the title to something hopefully more value-neutral.
