### ISSUE TITLE
Better way to loop through taxonomies

### ISSUE THREAD

**Issue by aureooms** [gohugoio/hugo#5994]
The documentation gives [two examples](https://gohugo.io/templates/taxonomy-templates/#display-a-single-piece-of-content-s-taxonomies) to show how to display the terms of some taxonomy a single page is assigned to:

```html
{{ $taxo := "tags" }} <!-- Use the plural form here -->
<ul id="{{ $taxo }}">
    {{ range .Param $taxo }}
        {{ $name := . }}
        {{ with $.Site.GetPage (printf "/%s/%s" $taxo ($name | urlize)) }}
            <li><a href="{{ .Permalink }}">{{ $name }}</a></li>
        {{ end }}
    {{ end }}
</ul>
```

```html
{{ $taxo := "directors" }} <!-- Use the plural form here -->
{{ with .Param $taxo }}
    <strong>Director{{ if gt (len .) 1 }}s{{ end }}:</strong>
    {{ range $index, $director := . }}
        {{- if gt $index 0 }}, {{ end -}}
        {{ with $.Site.GetPage (printf "/%s/%s" $taxo $director) -}}
            <a href="{{ .Permalink }}">{{ $director }}</a>
        {{- end -}}
    {{- end -}}
{{ end }}
```

To me there are multiple problems with this approach:
  - We already specified the Singular and Plural version of each taxonomy in the config file, why do we have to fiddle with adding `s` here? Isn't there a simpler way?
  - We first extract the name of the term (`$name`, `$director`) and the need to pass it to `$.Site.GetPage` to finally get the `.Permalink`. This can go wrong with terms that contains spaces, punctuation, or accentuation (for example a `director` named `Aurélien Ooms`). The first example tries to remedy this with `urlize` but [this actually fails on accented terms (a working solution is to use `anchorize`?)](https://github.com/gohugoio/hugoDocs/commit/7cff379f58168066073044d5a4488cc589815ae8#r33705430).

I encountered frustration as I was trying to adapt the above two examples to loop through all defined taxonomies. Here is the code I settled on for the moment.

```html
{{ range $taxo, $terms := .Site.Taxonomies }}
  {{ with $.Param $taxo }}
    {{ if gt (len .) 0 }}
    <h6>
    <strong>{{ $taxo | title }}:</strong>
    {{ range $index, $term := . }}
      {{- if gt $index 0 }}, {{ end -}}
      {{ with $.Site.GetPage (printf "/%s/%s" $taxo ($term | anchorize)) -}}
        <a href="{{ .Permalink }}">{{ .Title }}</a>
      {{- end -}}
    {{- end -}}
    </h6>
    {{- end -}}
  {{ end }}
{{ end }}
```

Ideally we should be able to write something like

```html
{{ range $key, $taxonomy := .Page.Taxonomies }}
    <h6>
    <strong>{{ if gt (len $taxonomy.Terms) 1 }}{{ $taxonomy.Plural }}{{ else }}{{ $taxonomy.Singular }}{{ end }}:</strong>
    {{ range $index, $term := $taxonomy.Terms }}
      {{- if gt $index 0 }}, {{ end -}}
      {{ with $.Site.GetPage (printf "/%s/%s" $key $term.Name) -}}
        <a href="{{ .Permalink }}">{{ .Title }}</a>
      {{- end -}}
    {{- end -}}
    </h6>
{{ end }}
```

There exist a similar problem with the [`.Site.Taxonomies` variable](https://gohugo.io/variables/taxonomy/#use-site-taxonomies-outside-of-taxonomy-templates).  Here is a sample of code:

```html
{{ range $key, $terms := .Site.Taxonomies }}
<h4 class="grey-text">{{ $key | title }}</h4>
<div class="row">
  <div class="col s12">
    {{ partial "taxonomy-collection.html" (dict "Site" $.Site "key" $key "terms" $terms ) }}
  </div>
</div>
{{ end }}
```

Whereas the following would be preferable:

```html
{{ range $key, $taxonomy := .Site.Taxonomies }}
<h4 class="grey-text">{{ $taxonomy.Plural }}</h4>
<div class="row">
  <div class="col s12">
    {{ partial "taxonomy-collection.html" (dict "Site" $.Site "key" $key "$taxonomy" $taxonomy ) }}
  </div>
</div>
{{ end }}
```

The `$key` thing could also be rendered useless by adding a `.Key` variable to `$taxonomy`.

Maybe the docs are not up to date. Or maybe this is not yet implemented. If it is not, I believe it should be.

**Comment by bep** [comment]
I admit I was a little bit tired after the work in Hugo 0.55, but it did address some of your questions. It's even in the documentation, just looked:

```bash
<ul>
    {{ range .Data.Terms.Alphabetical }}
            <li><a href="{{ .Page.Permalink }}">{{ .Page.Title }}</a> {{ .Count }}</li>
    {{ end }}
</ul>
```

```bash
<ul>
    {{ range .Site.Taxonomies.series.golang }}
        <li><a href="{{ .Page.RelPermalink }}">{{ .Page.Title }}</a></li>
    {{ end }}
</ul>
```

**Comment by aureooms** [comment]
I do not understand. I believe the first part of my question is about **single content page** templates that do not have a `.Data.Terms` variable (like the page for a post, is this clear enough? Is this correct?). The second part of the question is about looping over all taxonomies of the `.Site` variable which lacks a proper *keyification* of each taxonomy term.

Your first example is for a Taxonomy page. Your second example assumes you already have a `keyified` version of your Taxonomy Term.

Maybe I am stupid.

**Comment by bep** [comment]
@aureooms I didn't read your post in detail, my comment was a general remark that at least some common constructs are now easier now that you have `WeightedPage.Page` available.
