### ISSUE TITLE
Provide extended for 32bit Windows

### ISSUE THREAD

**Issue by seshaljain** [gohugoio/hugo#5998]
The title pretty much explains itself.
Is this a platform dependent thing?

If I want to build it, where can I find instructions for it?

**Comment by bep** [comment]
>Is this a platform dependent thing?

The short story is this:

The extended version = libSASS which requires a C/C++ build chain for each target platform. I'm not saying that it could not be done, but it's not far up on my list of priorities.

To build it yourself you need to run `go install -tags extended` -- which will probably give an error as you don't have a C/C++  compiler installed. I found these instructions helpful when doing it for 64 bit: https://github.com/golang/go/wiki/WindowsBuild

**Comment by larzza** [comment]
@seshaljain Try this if you like. Its Hugo v.055.5 windows 32bit extended.  
[hugowin32-extended.exe.zip](https://github.com/gohugoio/hugo/files/3236621/hugowin32-extended.exe.zip)

**Comment by bep** [comment]
@larzza if you want to exchange Windows binaries, please do so outside of this tracker.

**Comment by larzza** [comment]
@bep Sure.. just wanted to give a hand... I'll remove it.
