### ISSUE TITLE
Option --path-warnings : Is warning for alias pages correct ?

### ISSUE THREAD

**Issue by divinerites** [gohugoio/hugo#6000]
Not sure if it is a real issue.

- I have 2 alias pages and they have a warning when running `hugo --path-warnings``
- I am not sure if this is the expected behavior, because as it is done on purpose, not sur it deserve a warning.

My `index_en.md`

```yaml
---
title: "We have a new website. Update your bookmarks."
url: "/en/new-website"
aliases: [/index_en.html]
---
```

My `index_nl.md`

```yaml
---
title: "We hebben een nieuwe website. Update uw bladwijzers."
url: "/nl/nieuwe-website"
aliases: [/index_nl.html]
---
```

```
WARN 2019/05/30 12:14:08 Duplicate target paths: 
/Users/didiergeorgieff/Documents/Git/camping-arolla.com/public/en/new-website/index.html (2),
/Users/didiergeorgieff/Documents/Git/camping-arolla.com/public/nl/nieuwe-website/index.html (2)
Total in 975 ms
```

**Comment by bep** [comment]
>because as it is done on purpose, not sur it deserve a warning.

The warning is printed when 2 HTML files is written to the same location on disk. If that is on purpose (not sure why), then fine -- but I cannot see how I can somehow guess the purpose.

**Comment by divinerites** [comment]
mmmm... may be I just misunderstood the way alias works, because when i say on purpose, it is : I put some alias on purpose.

My use case is :

- Old website had an `index_en.html` for english language. This url is referenced by lot of other camping web site so i don't want to just remove it.
- I redone a multi-language with hugo and i set up a "information page" about the new web site, update your bookmark" thing.
- I put an alias from the `index_en.html` to redirect to "/en/new-website".
- I forgot to say that I also use a Netlify redirect with `index.redir` who produce a `_redirects` in public

```
# index.redir : Netlify redirects from aliases
{{ range $p := site.Pages -}}
  {{ range .Aliases }}
    {{  . | printf "%-35s" }}	{{ $p.RelPermalink }} 301!
  {{ end -}}
{{- end -}}
```

```
# _redirect : Netlify redirects from aliases
/index_en.html                     	/en/new-website/ 301!
/index_nl.html                     	/nl/nieuwe-website/ 301!
```

So i was thinking that i will never have the 2 same URL on disk. Hence my remark about that. But maybe (surely) I miss something

<img width="196" alt="Capture d’écran 2019-05-30 à 12 50 44" src="https://user-images.githubusercontent.com/32342823/58628552-48f4e080-82da-11e9-9b17-c81f0a32d42d.png">

**Comment by divinerites** [comment]
Or may be problem is not with alias but the fact I put `url: "/en/new-website"` in my `index_en.md` and I already have a proper `oldurl/_index.en.md` with `url: new-website`

I'll check but seems the mistake is here and not related to alias.
Sorry for the noise.

**Comment by divinerites** [comment]
Yes, removing `url: new-website` on my `oldurl/_index.en.md` rings no more warning.

I have to verify if the redirections works as expected, but that is nor relevant here.

Again sorry for the noise.

**Comment by divinerites** [comment]
Removing `url: new-website` breaks the expected behaviour, but no more warning. This issue closed.
