### ISSUE TITLE
Shortcode escapes closing HTML tags

### ISSUE THREAD

**Issue by fazy** [gohugoio/hugo#6006]
When creating a shortcode with more than one level of nested HTML tags, the closing tags between `{{ .Inner }}` and the final closing tag are escaped (`<` becomes `&lt;`) so that the tags get rendered on the page.

This issue appears to affect 0.55.0 and above (so _possibly_ in [this change set](https://github.com/gohugoio/hugo/compare/release-0.54.0...release-0.55.0) based on some local bisecting).

**Steps to reproduce**

Firstly, run this code in a place where you don't mind creating the `quickstart` directory:

```
hugo new site quickstart
cd quickstart
git init
git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
echo 'theme = "ananke"' >> config.toml
mkdir layouts/shortcodes
cat <<EOF > layouts/shortcodes/details.html
<details>
    <p>
        {{ .Inner }}
    </p>
</details>
EOF
cat <<EOF > content/test.md
# Just testing

{{% details %}}
Here are some details.
{{% /details %}}
EOF
```

Hopefully the above has created a very simple site. Run Hugo as normal:

`hugo server -w`

and visit http://localhost:1313/test/

(incidentally, you could just run `hugo` and check the HTML output; the bug behaves the same way).

**Expected behaviour**

Rendered code wraps the contents of `{{% details %}}` into the provided HTML, i.e. should look like this:

```
<details>
    <p>
        Here are some details.
    </p>
</details>
```

**Actual behaviour**

Closing tag gets escaped:

```
<p><details>
    <p></p>

<p>Here are some details.</p>

<pre><code>&lt;/p&gt;
</code></pre>

<p></details></p>
```

(there seem to be too many `<p>` tags but that's a lesser issue).

**Comment by pamubay** [comment]
Yes, it's already documented here [0.55.0 Release Notes/shortcodes-revised](https://gohugo.io/news/0.55.0-relnotes#shortcodes-revised).

If you want the previous behaviour,  put this line in your shortcode template:
```
{{ $_hugo_config := `{ "version": 1 }` }}
```

**Comment by fazy** [comment]
Thanks, the config switch solves my immediate problem.

However, I don't understand the new behaviour after reading the docs you mentioned and the [docs here](https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown).

Given a shortcode block like this:

```
<details>
    <p>
        {{ .Inner }}
    </p>
</details>
```

invoked like this:

```
{{% details %}}
Here are some details.
{{% /details %}}
```

why does the new behaviour escape the closing `</p>`, making it appear on the page, but not the opening `<p>`?

The behaviour I'm trying to get is for `{{ .Inner }}` to be rendered as Markdown and then inserted into the middle of the block of HTML specified in the shortcode block. As I say, I can get that by reverting to the old behaviour, but it would be useful to understand if we should ever adopt the new behaviour.

**Comment by bep** [comment]
I suspect this is a Go template issue -- and possibly a bug there, but I have not looked closely at this.
