### ISSUE TITLE
Python highlight line numbers break when using hashtag symbol

### ISSUE THREAD

**Issue by MasterGroosha** [gohugoio/hugo#6014]
```
{{< highlight python "linenos=table" >}}
# -*- coding: utf-8 -*-  
token = '110831855:AAE_GbIeVAUwk11O12vq4UeMnl20iADUtM'
{{< / highlight >}}
```
Results in:
![image](https://user-images.githubusercontent.com/2780044/58766950-9e0c4d00-858d-11e9-9773-a7aa7aa11389.png)

When I replace line with hashtag with a line without hashtags:
```
{{< highlight python "linenos=table" >}}
print("Hello world!")
token = '110831855:AAE_GbIeVAUwk11O12vq4UeMnl20iADUtM'
{{< / highlight >}}
```

Then line numbers work fine
![image](https://user-images.githubusercontent.com/2780044/58766962-c5fbb080-858d-11e9-8800-3d74edf5ebd0.png)

**Comment by MasterGroosha** [comment]
The issue is still here with hugo extended v0.58.3 (Windows)

**Comment by moorereason** [comment]
What is the difference in HTML output?

**Comment by MasterGroosha** [comment]
Oh, btw, the issue is still here. I just cannot test it "in HTML output", since I don't understand the question.

**Comment by moorereason** [comment]
You showed us your shortcode and screenshots, but what is the resulting HTML that's generated by Hugo?
