### ISSUE TITLE
document HTML mangling

### ISSUE THREAD

**Issue by SoniEx2** [gohugoio/hugo#6017]
Hugo mangles output HTML, adding stuff like `<meta name="generator" content="Hugo 0.55.6" />` and LiveReload by default. While LiveReload is quite well documented, the meta tag isn't. there are probably other forms of mangling that it does that are hard or impossible to disable. those should be documented as well.

**Comment by coliff** [comment]
I wouldn't say that the meta generator tag is 'mangling' and it is clearly documented in the Getting Started guide too: https://gohugo.io/getting-started/configuration/

>**disableHugoGeneratorInject (false)**
> Hugo will, by default, inject a generator meta tag in the HTML head on the home page only. You can turn it off, but we would really appreciate if you don’t, as this is a good way to watch Hugo’s popularity on the rise.

LiveReload is only used on Live Preview as it's needed for live reloading. It isn't included in the final generated output.

**Comment by bep** [comment]
I will close this. It is documented.
