### ISSUE TITLE
Recommended indentation for TOML

### ISSUE THREAD

**Issue by alexherbo2** [gohugoio/hugo#6022]
What is the recommended indentation for [TOML]?

Sometimes you use indentation and sometimes you don’t.

https://github.com/gohugoio/hugoDocs/blob/master/config.toml

[TOML]: https://github.com/toml-lang/toml

**Comment by bep** [comment]
TOML does not care, which is a relief if you have worked with YAML for a while.

**Comment by alexherbo2** [comment]
Indentation is mixed in the document.

**Comment by bep** [comment]
You need to take that in the correct repo.
