### ISSUE TITLE
How to install hugo-extended on windows with .zip file? 

### ISSUE THREAD

**Issue by lioncruise** [gohugoio/hugo#6028]
I download  `hugo_extended_0.55.6_Windows-64bit.zip`  from the github release page. this .zip file contains 3 files.

![image](https://user-images.githubusercontent.com/12690984/59326216-63867b00-8d18-11e9-83d6-ae79ceba6ca6.png)

Then run `hugo.exe`, but it shows there is no hugo command in cmd terminal.

![image](https://user-images.githubusercontent.com/12690984/59326278-a3e5f900-8d18-11e9-9b98-65476618a335.png)

**Comment by lioncruise** [comment]
solution：https://gohugo.io/getting-started/installing/#quick-install

ctrl+F :  Less-technical Users

**Comment by jmbruel** [comment]
I have the same problem but on Mac (with extended version).

**Comment by lonewolf0x01** [comment]
you solved ti?
