### ISSUE TITLE
Fail graciously with `enableGitInfo = true` in a non-git project

### ISSUE THREAD

**Issue by marcojakob** [gohugoio/hugo#6035]
Hugo (v0.55.6/extended windows/amd64) exits with a fatal error if `enableGitInfo` is set to `true` in a folder that does not contain git info.

> Failed to read Git log: fatal: not a git repository (or any of the parent directories): .git

I don't think it's necessary to quit and raise a fatal error in that case. I'm using the new GitHub template function and others are using my Hugo repo as a template. Then if someone just downloads the repo without using git (there are such people), they face this error. I think a warning would be more than enough.

**Comment by marcojakob** [comment]
The `lastmod` parameter has a [nice mechanism](https://gohugo.io/getting-started/configuration/#configure-front-matter) to fall back to other dates if the git info is not available. Maybe the `enableGitInfo` config could be handled similarly.

Or would this create a problem with the way people are using the [Git Info Variables](https://gohugo.io/variables/git/)?

**Comment by marcojakob** [comment]
For the record: I currently use a **workaround** for this issue. I've removed the `enableGitInfo` from `config.toml` and instead use it as a command line argument. Since I'm using Netlify, my `netlify.toml` looks like this:

```
[build]
publish = "public"
command = "hugo --baseURL $URL --enableGitInfo"

[build.environment]
HUGO_VERSION = "0.55.6"
```

This way if someone downloads the repo without using git and uses Hugo to run, the fatal error does not appear.

**Comment by Spaceface16518** [comment]
I don't think this should be closed. This issue is causing my build to fail on the Vercel platform. With `hugo version`

```plain
Hugo Static Site Generator v0.70.0/extended darwin/amd64 BuildDate: unknown
```

Setting `enableGitInfo = false` causes the build to succeed.
