### ISSUE TITLE
.MediaType.Type is application/rss&#43;xml in 0.55.6, maybe earlier

### ISSUE THREAD

**Issue by teran-mckinney** [gohugoio/hugo#6038]
I found out that `.RSSLink` was deprecated, so I updated my theme to the example here: https://github.com/gohugoio/hugoDocs/blob/master/themes/gohugoioTheme/layouts/_default/baseof.html#L25

This seems to work other than giving a URL encoded output that looks really bizarre. Not sure if it would even work.

This is my output: `<link rel="alternate" type="application/rss&#43;xml" href="http://localhost:1313/index.xml">`

Might this be an issue with my configuration? Thank you!

**Comment by teran-mckinney** [comment]
Ok, looks like the printf example here worked: https://gohugo.io/templates/rss/#reference-your-rss-feed-in-head

Not sure if this is a hugo bug, hugoDocs bug, or something else.

**Comment by bep** [comment]
The `Type` is a Go `string`.  The Go HTML template is a little restrictive in this area, and I don't think it's something we could/should do about it from the Hugo code side of it (we don't know in which context that value will be used).

I do suspect that the encoded version will work fine, though.

**Comment by teran-mckinney** [comment]
Gotcha, thank you!
