### ISSUE TITLE
goreleaser.yml doesn't build hugo-extended-linux with "-extldflags '-static'" 

### ISSUE THREAD

**Issue by larzza** [gohugoio/hugo#6042]
goreleaser.yml doesn't build hugo-extended-linux with "-extldflags '-static'" which means that the executable won't work on, for example, Alpine Linux or in a scratch Docker image.

**Comment by bep** [comment]
This is by design.

**Comment by bep** [comment]
I was short there, but there are plenty of other issues discussing this.

**Comment by larzza** [comment]
Ok, I found one somewhat related (snap) but I guess I have to do a better search then...
