### ISSUE TITLE
Build with alternate dynamic linker/loader?

### ISSUE THREAD

**Issue by ryanerwin** [gohugoio/hugo#6045]
Hello,

I'm trying to build `hugo` to use an alternate dynamic linker/loader, but reguardless of the `-ldflags` or `CGO_LDFLAGS` I always get the same `/usr/lib/ld-linux-x86-64.so.2` and never the alternate linker/loader I tried on the command line....

I've tried everything I can think of... Many many iterations/permutations of:

```
  CGO_LDFLAGS='-I=/opt/dane/lib/ld-linux-x86-64.so.2'
  GO_LDFLAGS='-I=/opt/dane/lib/ld-linux-x86-64.so.2'
  LDFLAGS='-I=/opt/dane/lib/ld-linux-x86-64.so.2'
  cd "${srcdir}"/${pkgname}-${pkgver}
  go build -tags extended -gcflags=-trimpath=x/y \
    -ldflags '-linkmode external -r=/opt/dane/lib -I=/opt/dane/lib/ld-linux-x86-64.so.2'
```

The only workaround I've been able to find is to use `patchelf --set-interpreter /opt/dane/lib/ld-linux-x86-64.so.2 hugo`, but I really would like to properly link the linker/loader while compiling.

**Comment by bep** [comment]
I don't have an answer for you right of the bat. You may try https://discourse.gohugo.io/ -- but I suspect a more specialized forum would be of more help.

**Comment by yerden** [comment]
@ryanerwin did you try `CGO_LDFLAGS="-Wl,--dynamic-linker=/opt/dane/lib/ld-linux-x86-64.so.2"`?
