### ISSUE TITLE
Incompatible version for Glibc in the extended version

### ISSUE THREAD

**Issue by pixelkritzel** [gohugoio/hugo#6047]
Hi, tried to run the extended version on CentOS78 and it crashed with this error:

```
hugo: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by hugo)
hugo: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by hugo)
```

But the funny thing is, it is only the extended version and not the unextended version.

Is there a possibility to fix the build for the extended version? Thank you!

**Comment by bep** [comment]
>Is there a possibility to fix the build for the extended version? Thank you!

The build works, but as the error message says, it requires newer libc versions. You should check with the CentOS communitiy, as this isn't something that we will spend time on at the moment. There are similar issues in here somewhere, so I'm closing this.
