### ISSUE TITLE
Non-Deterministic Disappearing Pages

### ISSUE THREAD

**Issue by geeknoid** [gohugoio/hugo#6050]
We've been chasing a mysterious Hugo problem. One of our tech writers rewrote a chunk of our site and we have been incapable of checkin the change in since it is causing intermittent CI failures:

* Our CI system runs Hugo to generate the site, and then runs htmlproofer to ensure all links are valid. In some percentage of the time (50%?) with this PR, Hugo decides not to generate a portion of our web site and so the link checking fails.

* We use Netlify to build and host our site. With this PR, the previews built by Netlify are ~50% of the time missing a bunch of site pages. The site itself is fully consistent, the auto-generated TOC and sidenav simply don't show the missing pages, like if they didn't exist. Run it through Netlify again, and then the pages may come back.

* I've been able to make this happen a couple times on my machine just running Hugo. I ran Hugo and a bunch of .html files weren't generated in my public directory. Without changing anything, I ran Hugo again and this time the files showed up.

The pages that appear/disappear are related to the files being touched in the PR. If you generate our site, it's the Docs->Concepts->Traffic Management section which ends up being completely empty, except for static svg files. There is simply no .html file produced for the section. It's almost like Hugo is sometimes deciding to treat that whole folder hierarchy as a bundle.

To repeat though, this is non-deterministic. Sometimes it works fine three times in a row and then fails. We've tried a variety of things to pinpoint the issue and in fact at the moment the example PR that I show below removes most of the content from the new files we've added, just leaving the structure in place, and the problem still happens. So there's something about the structure of the files in the PR which is leading Hugo to get confused.

This is using Hugo 0.55.5. The problem has been seen on macOS, on Linux, and in a container. 

Here's the PR that demonstrates the problem: We'll leave it around for your benefit:

https://github.com/istio/istio.io/pull/4502

**Comment by bep** [comment]
What you see is most likely a data race due to parallel processing. I would guess that `hugo --path-warnings` should help you here, but in short:

```
content/docs/concepts/traffic-management/_index.md 
content/docs/concepts/traffic-management/index.md 
```

The above does not work.

**Comment by geeknoid** [comment]
I just tried --path-warnings and no warnings were displayed.

The original site had content/docs/concepts/traffic-management/index.md, the PR changes that to _index.md instead, so both files aren't present at the same time.

That would match the symptoms though. Sometimes Hugo would think it's a directory, sometimes it would treat it as a bundle.

**Comment by bep** [comment]
Yea, well, I'm pretty sure there is some nugget of truth in what I said. I don't have time debugging this. You may have more luck at https://discourse.gohugo.io/ -- I will keep this open if someone finds a real issue in there somewhere.
