### ISSUE TITLE
Don't require empty directories to build

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#6051]
When starting a new project, I like to hook it up to Netlify to get feedback as I go. However, Hugo won't build if the static or content directories don't exist. It will build if they are _empty_, so the directories are not strictly needed. But because Hugo fails to build, it makes me think something is wrong with my Netlify setup etc. and waste time debugging whatever the issue is or isn't. It's harder to find the error too because on my local system, the directories exist, but Git won't let you commit empty directories, so I don't realize that there is a difference between my local setup and the setup of a freshly cloned repository.

I think issuing a warning for missing directories should be enough.

**Comment by thatarchguy** [comment]
You can create an empty file called `.gitkeep` in the directory and you'll be able to add the "empty" directory to your git repository.

**Comment by carlmjohnson** [comment]
Yes but this is not intuitive if you don’t know why the build is failing.

**Comment by bep** [comment]
I agree. I'm doing some really cool stuff in this area at the moment and I will make sure I have this in mind when testing it.

**Comment by jaswdr** [comment]
I tested with a clean build of go and if I remove the `/static` or `/content` folder it builds normally, @carlmjohnson can you check if this error still happens?

**Comment by carlmjohnson** [comment]
It is likely that @bep's work on "Hugo modules" has fixed this issue.

**Comment by jmooring** [comment]
Cannot reproduce with either missing or empty `content` directory.
Cannot reproduce with either missing or empty `static` directory.
