### ISSUE TITLE
Provide external URL for hugo server

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#6054]
`hugo server` echos: “Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)”.

It would be great if Hugo provided an additional external URL—absolutely fantastic for live cross browser testing.

Currently I use this simple bash script (MacOS):

```
function hsip {
    VAR=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | cut -d\  -f2)
    hugo server --bind 0.0.0.0 --baseURL http://$VAR:1313
}
```

**Comment by bep** [comment]
Try: `hugo -b https://external.com` ... I'm not sure what you mean by additional?

**Comment by Brixy** [comment]
Thank you, bep.

This is rather a suggestion than a question.

With my bash script I can access the ‘server version’ of my site on my network, e.g. via an address like `http://123.456.789.20:1313/`. That is: I use `hugo server` on my laptop and can access the site from other devices.

This script above works perfectly for me. But it would be very handy if `hugo server` provided such an individual network address by default.

Sorry if my terminology is not quite correct. “External URL” should probably renamed to “local network address” or something.

**Comment by bep** [comment]
>With my bash script I can access the ‘server version’ of my site on my network, e.g. via an address like http://123.456.789.20:1313/.

Doesn't `hugo server -b http://123.456.789.20` give you exactly that?

**Comment by larzza** [comment]
This is how I do it.

```bash
$ hugo server -b http://$(hostname)/ --bind 0.0.0.0
...
Web Server is available at http://my-machine-name:1313/ (bind address 0.0.0.0)
```

I can now reach the site from my phone (when on the same network) on ```http://my-machine-name:1313```.

**Comment by Brixy** [comment]
```shell
$ hugo server -b http://$(hostname)/ --bind 0.0.0.0
```

Good method!

Ok, I see there are various methods. Then I would simply suggest that `hugo server` provided both the `localhost` *and* the local network address by default because not everyone knows of this very useful opportunity.

**Input**

```
$ hugo server
```

**Output something like**

```
   Local: http://localhost:1313
External: http://123.456.789.20:1313/
```

**Comment by bep** [comment]
>hugo server provided both the localhost and the local network address by default 

Hugo is a static site generator. The `baseURL` is used to create URLs in static HTML pages. We cannot have 2 values at one specific time.

**Comment by Brixy** [comment]
I am not a programmer, bep (but a Hugo user and fan for years). Yet, I think we may be talking of two different things. Sorry in advance if I am wrong :-)

When you start the server with

```
hugo server -b http://$(hostname)/ --bind 0.0.0.0
```

you can access the live site via

1. http://localhost:1313
2. the network address which the script above echoes (from your home network only but with multiple devices other the one running the script)

**indipendently** from the `baseURL``.

Sure—with `hugo` you build the static site with Hugo respecting the `baseURL`.

This is so practical and handy for multiple device testing purposes that in my opinion this should not only be an option but the default.

**Comment by bep** [comment]
`hugo server` is just `hugo` with a file server on top; it's still static. What you want needs to be solved outside of Hugo (`/etc/hosts`?).

**Comment by Brixy** [comment]
This is neither a question nor an issue—just a suggestion.

*The technique I am suggesting has been working for me for years.*

I guess most users do not know of this possibility. That’s why I opened this issue.

Just run the script above on your laptop and access the live site from your cell phone. It’s like magic!
