### ISSUE TITLE
`{{< ... >}}` and TOC

### ISSUE THREAD

**Issue by retorquere** [gohugoio/hugo#6056]
If I use `{{< ... >}}` instead of `{{% ... %}}`, headings (`h1`, `h2`, `h3`) don't show up in the TOC. Possibly related to #5827.

**Comment by bep** [comment]
This is as designed. Please use https://discourse.gohugo.io/ for further questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
