### ISSUE TITLE
Allow custom URLs for home pages

### ISSUE THREAD

**Issue by pawelurbanski** [gohugoio/hugo#6064]
I am using Hugo 0.55.6 Extended Windows 64-bit. The site is a multilanguage site, with pages generated to subdirectories.

There is the following folder structure:

* content/en
* content/pl

Both directories: "en" and "pl" are sources for the respective languages.
The site is generating correctly. The only exception is when I set a custom:

* url to for example: url: "/en/test.html"
* slug to for example: slug: "custom-page"

The files generated for the _index.md, the homepage page located at the root language folders are always as: index.html not the custom provided. Any combination of url or slug does not change this behavior.

My goal is to:

* be able to keep the default language in a subdirectory, but generate the default language homepage to the /index.html file, and overwrite the alias created by default - or at least to a file, which I can move and rename,
* be able to generate custom target files under the url for homepages, which are in other languages, and kept in the _index.md homepage file per language.

Slugs and urls do work without any issues for regular pages.

Thanks for hints/help.checking the issue.

**Comment by pawelurbanski** [comment]
@bep  could you direct me to Hugo modules where I could try to do some initial work on that feature? I unfortunately, do not have such good knowledge of Hugo's package organization. While I am not a Go developer, I guess those changes should not be very difficult. They may take me more time than anyone who knows Hugo's internals well, but I can try and do the initial work.

**Comment by bep** [comment]
@pawelurbanski we first need to decide if we want to do this. You are the first one asking for this, so you need to convince us that adding more complexity in this department is worth it.

**Comment by pawelurbanski** [comment]
Hi Bjorn and others,
I've tried a few possible ways this functionality could be implemented without major changes.

* Provide consistancy with behavior/use cases for regular page type in Hugo. The documentation says, that a homepage is like a regular page with al the page variables. I therefore thought that adding a URL or a slug in a front matter will be consistant and output the desired files,
* Provide consistancy how aliases are created and overridden by Hugo. Every content file replaces an alias file if the names are the same. It is not the case with homepages, especially with the alias file that redirects the root domain URL to the default langauge subdirectory when the default language in subdirectory is enabled.

While I do not know Hugo's code very well, it looks to me, that the homepages included in the _index.md files are processed with slightly different logic. Changes/use cases I provided in the above points would not break the existing behavior, and allow for overwrites when necessary. If the case of slightly different logic holds true, my idea would make the code more simple and universal for all the pages.

Many sites keep language-specific content in subfolders, but the homepage is kept under the root domain. Being able to provide the URL in front-matter, which would overwrite the index.html alias page that redirects to the default langauge subfolder would fix the case. And as I said before, aliases are generated first, so they can be replaced when needed in the default case.

I am ready to spent the time on fixes, should not be that difficult, for I guess it is all about the order when the files are generated. If only could hint me to the Hugo's packages where I should check things out as a quick start.

All the best, Pawel

**Comment by pawelurbanski** [comment]
Dear @bep 
I looked into Hugo's code after generating the site with the --debug flag to spot when the redirect alias is created.
It is created by the function I reference below with my possible addition at the end of the hugolib/site_render.go package. 
I added a config flag in the hugolib.site.go in the languages section, just right next to the defaultContentLanguageInSubdir as bool. Here is my idea:
// renderMainLanguageRedirect creates a redirect to the main language home,
// depending on if it lives in sub folder (e.g. /en) or not.
func (s *Site) renderMainLanguageRedirect() error {

	if !s.h.multilingual.enabled() || s.h.IsMultihost() {
		// No need for a redirect
		return nil
	}

	if s.Info.disableContentLanguageSubdirRedir {
		// Generation of the redirect from root domain is disabled
		// This flag can be either true or false: false by default to
		// keep Hugo's default behavior when the redirect is present.
		return nil
	}

	html, found := s.outputFormatsConfig.GetByName("HTML")
	if found {
		mainLang := s.h.multilingual.DefaultLang
		if s.Info.defaultContentLanguageInSubdir {
			mainLangURL := s.PathSpec.AbsURL(mainLang.Lang, false)
			s.Log.DEBUG.Printf("Write redirect to main language %s: %s", mainLang, mainLangURL)
			if err := s.publishDestAlias(true, "/", mainLangURL, html, nil); err != nil {
				return err
			}
		} else {
			mainLangURL := s.PathSpec.AbsURL("", false)
			s.Log.DEBUG.Printf("Write redirect to main language %s: %s", mainLang, mainLangURL)
			if err := s.publishDestAlias(true, mainLang.Lang, mainLangURL, html, nil); err != nil {
				return err
			}
		}
	}

	return nil
}

Unfortunately, it looks liek this flag has no effect. Hugo compiles correctly, but regargless of setting it to true or false, the alias redirect is generated.

**Comment by pawelurbanski** [comment]
Dear @bep,
I am coming back to this issue. In addition to that there were threads about using slugs for _index.md files. The way files are generated and saved in the publish directory influences the permalinks in menus or when creating translation switches. So it touches a few places. On the other hand the case of the homepage seems to be handled in the code block I quoted.
Because the logic is hardcoded, even if home generation is disabled in disableKinds this redirect alias is still generated at the root of the publish directory. While the homepage makes for a special case, it is also relevant to the final URL, which in almost all cases would be prefered to be the base URL.
Since the homepage is an _index.md file, I would like to get back to work on the branch with a PR I linked in the last comment before the stale bot closed this issue and digg more into Hugos API to handle the logic generating the alias.
