### ISSUE TITLE
Documentation is infuriating

### ISSUE THREAD

**Issue by eaigner** [gohugoio/hugo#6066]
It takes quite a bit for me to write this, but the docs are probably not the best to get anyone started. I used hugo over 3 years ago. I remember it was infuriating just to get the most simple page to work. Many colleagues had the same experience. Now it's 3 years later and I can't remember how anything works and am in the same position again.

Quite honestly you could throw the whole documentation out, because it just does not help at all.

What I actually searched for is just how to render a few pages and hoped to understand how the templates are structured.

The quick start gets you nowhere if you want to start from scratch and don't want to use some blog template.

The docs could be replaced with a single page just quickly explaining the directory structure and how to render and link between 2 pages. Would make much more sense IMHO.

Also most of the examples are completely out of context. It shows a code snippet without almost any clue how that would fit into the puzzle.

I think a good start would be to at least generate a default single page on

    hugo new site quickstart

so someone can make heads and tails out of the structure right then and there. For instance when you create a site with `jekyll` you just immediately know how it works without ever having to consult a quick start.

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues
