### ISSUE TITLE
Add an .editorconfig

### ISSUE THREAD

**Issue by coliff** [gohugoio/hugo#6069]
I think it'd be a good idea to add an `.editorconfig` to the projects root for contributors to easily see the code-formatting style. I imagine the file would be something like this:

```
# https://editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
trim_trailing_whitespace = true

[*.go]
indent_size = 8
indent_style = tab

[*.js]
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

Ref: https://editorconfig.org/. Let me know what you think, I'd be happy to open a PR for this.

**Comment by davidsneighbour** [comment]
Somebody familiar with the codebase should write down the requirements and check if the code is ready for this before "just" adding it. I broke a project recently with an activity like this :)

Other than this :+1:
