### ISSUE TITLE
Make atwiki a target of recommended URLs / atwikiを推奨URLの対象にする

### ISSUE THREAD

**Issue by ikemo3** [gohugoio/hugo#6070]
`@WIKI`

https://atwiki.jp/

こちらのWikiに対し、サブディレクトリを推奨URLとして提示する。

**Comment by peaceiris** [comment]
@ikemo3 リポジトリ間違えてませんか?

I do not think that this issue was created at an appropriate repository.

**Comment by ikemo3** [comment]
I made a mistake. I'm sorry.
