### ISSUE TITLE
Gulp hugo: stop at site building

### ISSUE THREAD

**Issue by YiniXu9506** [gohugoio/hugo#6071]
Our website is using hugo (hugo-bin: 0.17.0) to generate html. 

There is a binary value string in a code block like this:

`\t\002\010$\t\002\010&\t\002\010`

Hugo stop building the site until I remove the special character `$`. The strange thing is if I just write `$` in the code block, hugo builds the site well. However, it comes problem if the `$` inside a string likes above.

I believe it is a bug in building the site. Would you please take a look? Thanks

**Comment by bep** [comment]
Hugo 0.17 is a very, very old version and isn't something we can spend time debugging.
