### ISSUE TITLE
relLangURL with leading slash repeats baseurl sub-directory

### ISSUE THREAD

**Issue by pacollins** [gohugoio/hugo#6073]
When using relLangURL on a site that has a baseurl with a sub-directory, URLs with leading slash cause the sub-directory to repeat.

```
baseurl = "domain.com/subdir/"
[[Main.menu.en]]
url = "/page/"
[[Main.menu.fr]]
url = "/page/"

{{ .url | relLangUrl }}
Outcome   ==> /subdir/subdir/page
          ==> /subdir/fr/subdir/page
Expected  ==> /subdir/page
          ==> /subdir/fr/page
```

This seems like a weird interaction.

Original Issue: pacollins/hugo-future-imperfect-slim#34

**Comment by bep** [comment]
URLs with a leading slash is considered relative to the server host. You may find it "weird", but it is as designed.

**Comment by pacollins** [comment]
But what practical application does repeating the subdir give if it is automatically on the url anyway? The subdir from the baseurl can only be subverted by a hard coded link, right? Wouldn't it be more practical to have it go back to the site root and ignore the subdir in the baseurl? Then hugo sites could be functionally nested inside a larger site. 

```
baseurl = domain.com
domain.com/hugo/index.html ==> Hugo site
```
```
{{ /otherSite/index.html Site | relLangURL }}  ==> domain.com/hugo/[optLang/]hugo/otherSite/index.html
vs
{{ /otherSite/index.html Site | relLangURL }}  ==> domain.com/[optLang/]otherSite/index.html
```
And
```
{{ otherSite/index.html Site | relLangURL }}  ==> domain.com/hugo/[optLang/]otherSite/index.html
vs
{{ otherSite/index.html Site | relLangURL }}  ==> domain.com/hugo/[optLang/]otherSite/index.html
```
