### ISSUE TITLE
Inconsistent param case handling inside with

### ISSUE THREAD

**Issue by VincentTam** [gohugoio/hugo#6077]
# Background
While working on https://github.com/pacollins/hugo-future-imperfect-slim/pull/31, I've created a site param called `gitProvider`.  However, mixed case variable names don't work inside ``{{ with }}``

# Problem

```toml
# config.toml
[params]
  foo = "bar"
  [params.staticman]
    gitProvider = "gitlab"
```

|  | worked | failed |
| --- | --- | --- |
| result | gitlab | |

```go
// Go-HTML template file
{{ with .Site.Params.staticman }}{{ .gitProvider }}{{ end }}    // failed
{{ with .Site.Params.staticman }}{{ .gitprovider }}{{ end }}    // worked
{{ .Site.Params.staticman.gitProvider }}  // worked
{{ .Site.Params.staticman.gitprovider }}  // worked
```

Is it a bug?  It seems that Hugo supports mixed case variables, but not inside `{{ with }}`

I'm using the latest stable version of Hugo on Ubuntu 18.04.

```
$ hugo version
Hugo Static Site Generator v0.55.6/extended linux/amd64 BuildDate: 2019-05-18T11:36:21Z
```

**Comment by jmooring** [comment]
Unable to reproduce with v0.83.
