### ISSUE TITLE
.TableOfContents generate "hahahugoshortcode" text if {{< icon >}} on ## level headers

### ISSUE THREAD

**Issue by divinerites** [gohugoio/hugo#6081]
Hello,

My `{{ .TableOfContents }}` works flawlessly. But when I decided to **add some icon on my headers**, the markdown parsing produced a funny result with `hahahugoshortcode` text 😸 :

from source markdown :

```md
## {{< icon name="fa-battery-1" >}} My title with icon 

my text 1

### My title without icon

my text 2
```

produce this HTML

```html
<nav id="TableOfContents">
<ul>
<li>
<ul>
<li><a href="#hahahugoshortcode-s0-hbhb-my-title-with-icon">HAHAHUGOSHORTCODE-s0-HBHB My title with icon</a>
<ul>
<li><a href="#my-title-without-icon">My title without icon</a></li>
</ul></li>


```

**Comment by divinerites** [comment]
Ah ... may be this is already known, I finally found a reference on this [Bep's post](https://discourse.gohugo.io/t/hugo-0-40-help-test-it/11655) ...

**Comment by plinss** [comment]
I found the fix for this, use the `{{% %}}` syntax for the shortcodes. e.g. 
```
## {{% icon name="fa-battery-1" %}} My title with icon 
```
That will cause the shortcodes to be rendered before being passed to the markdown processor (which generates the .TableOfContent variable)

**Comment by subhashb** [comment]
@plinss's solution works well for icons. But using true shortcodes with separate <style> sections still generates this text in ToC.

**Comment by bep** [comment]
You want to use the `{{%` delimiter in titles.

**Comment by rodrigoalcarazdelaosa** [comment]
> You want to use the `{{%` delimiter in titles.

Is this confirmed to work with Hugo 0.72.0? I'm testing it and the icon shows in the first line of the body of the text, not in the title.

**Comment by rodrigoalcarazdelaosa** [comment]
> > You want to use the `{{%` delimiter in titles.
> 
> Is this confirmed to work with Hugo 0.72.0? I'm testing it and the icon shows in the first line of the body of the text, not in the title.

This is still happening for me with Hugo 0.73.0.

**Comment by rodrigoalcarazdelaosa** [comment]
> This is still happening for me with Hugo 0.73.0.

Also happening with Hugo 0.74.3

**Comment by bep** [comment]
Note that any fix for this issue would be to issue some kind of warning/error instead of the haha... placeholder. The proper tix is what I say above. If you see some other issues related to this, that is something different.

**Comment by rodrigoalcarazdelaosa** [comment]
> Note that any fix for this issue would be to issue some kind of warning/error instead of the haha... placeholder. The proper tix is what I say above. If you see some other issues related to this, that is something different.

I'm using the [Academic theme](https://sourcethemes.com/academic/), which implements [this shortcode](https://github.com/gcushen/hugo-academic/blob/master/layouts/shortcodes/icon.html) to render icons. I copy the code below:
```
{{- if (.Get "name") -}}
  {{- $icon := .Get "name" -}}
  {{- $pack := or (.Get "pack") "fas" -}}
  {{- $pack_prefix := $pack -}}
  {{- if in (slice "fab" "fas" "far" "fal") $pack -}}
    {{- $pack_prefix = "fa" -}}
  {{- end -}}
  {{- $padding_right := (.Get "padding_right") | default 1 -}}{{/* Defaulting to 1 prevents no spacing when minimizing HTML. */}}
  <i class="{{ $pack }} {{ $pack_prefix }}-{{ $icon }} {{with (.Get "padding_left")}}pl-{{.}}{{end}} {{with $padding_right}}pr-{{.}}{{end}} {{if ne (.Get "fixed_width") "false"}}fa-fw{{end}}"></i>
{{- end -}}
```
If I use the shortcode with this syntax `{{< >}}` I see the icon on the header but the _HAHAHUGOSHORTCODE_ text on the ToC, like this:
![image](https://user-images.githubusercontent.com/9049533/88482908-99aaac80-cf64-11ea-922b-0ebc8cb8bd48.png)

If I use the `{{% %}}` syntax then the icon is rendered on the next line below the header, like this:
![image](https://user-images.githubusercontent.com/9049533/88482920-a29b7e00-cf64-11ea-8c84-93288ba8d8e0.png)

I reported this issue on `hugo-academic` and [was referred](https://github.com/gcushen/hugo-academic/issues/1746#issuecomment-644342807) here, but the solution posted here doesn't work for me. I'm also mentioning @gcushen (creator of the [Academic theme]([Academic theme](https://sourcethemes.com/academic/))) just in case.

Thanks for your time!

**Comment by rodrigoalcarazdelaosa** [comment]
> > Note that any fix for this issue would be to issue some kind of warning/error instead of the haha... placeholder. The proper tix is what I say above. If you see some other issues related to this, that is something different.
> 
> 
> 
> I'm using [Wowchemy](https://wowchemy.com/), which implements [this shortcode](https://github.com/wowchemy/wowchemy-hugo-modules/blob/master/wowchemy/layouts/shortcodes/icon.html) to render icons. I copy the code below:
> 
> ```
> 
> {{- if (.Get "name") -}}
>   {{- $icon := .Get "name" -}}
>   {{- $pack := or (.Get "pack") "fas" -}}
>   {{- $pack_prefix := $pack -}}
>   {{- if in (slice "fab" "fas" "far" "fal") $pack -}}
>     {{- $pack_prefix = "fa" -}}
>   {{- end -}}
>   {{- $padding_right := (.Get "padding_right") | default 1 -}}{{/* Defaulting to 1 prevents no spacing when minimizing HTML. */}}
>   <i class="{{ $pack }} {{ $pack_prefix }}-{{ $icon }} {{with (.Get "padding_left")}}pl-{{.}}{{end}} {{with $padding_right}}pr-{{.}}{{end}} {{if ne (.Get "fixed_width") "false"}}fa-fw{{end}}"></i>
> {{- end -}}
> 
> ```
> 
> If I use the shortcode with this syntax `{{< >}}` I see the icon on the header but the _HAHAHUGOSHORTCODE_ text on the ToC, like this:
> 
> ![image](https://user-images.githubusercontent.com/9049533/88482908-99aaac80-cf64-11ea-922b-0ebc8cb8bd48.png)
> 
> 
> 
> If I use the `{{% %}}` syntax then the icon is rendered on the next line below the header, like this:
> 
> ![image](https://user-images.githubusercontent.com/9049533/88482920-a29b7e00-cf64-11ea-8c84-93288ba8d8e0.png)
> 
> 
> 
> I reported this issue on `wowchemy-hugo-modules` and [was referred](https://github.com/gcushen/hugo-academic/issues/1746#issuecomment-644342807) here, but the solution posted here doesn't work for me. I'm also mentioning @gcushen (creator of [Wowchemy](https://wowchemy.com/)) just in case.
> 
> 
> 
> Thanks for your time!

Just wanted to remind this. The proposed solution doesn't work for me as the icon is not rendered on the heading but on the next line below. Maybe it's not a Hugo issue but a Wowchemy issue (related to the above `icon` shortcode). It'd be great if @gcushen could confirm it. Thanks in advance!

**Comment by rodrigoalcarazdelaosa** [comment]
> > > Note that any fix for this issue would be to issue some kind of warning/error instead of the haha... placeholder. The proper tix is what I say above. If you see some other issues related to this, that is something different.
> > 
> > 
> > 
> > I'm using [Wowchemy](https://wowchemy.com/), which implements [this shortcode](https://github.com/wowchemy/wowchemy-hugo-modules/blob/master/wowchemy/layouts/shortcodes/icon.html) to render icons. I copy the code below:
> > 
> > ```
> > 
> > {{- if (.Get "name") -}}
> >   {{- $icon := .Get "name" -}}
> >   {{- $pack := or (.Get "pack") "fas" -}}
> >   {{- $pack_prefix := $pack -}}
> >   {{- if in (slice "fab" "fas" "far" "fal") $pack -}}
> >     {{- $pack_prefix = "fa" -}}
> >   {{- end -}}
> >   {{- $padding_right := (.Get "padding_right") | default 1 -}}{{/* Defaulting to 1 prevents no spacing when minimizing HTML. */}}
> >   <i class="{{ $pack }} {{ $pack_prefix }}-{{ $icon }} {{with (.Get "padding_left")}}pl-{{.}}{{end}} {{with $padding_right}}pr-{{.}}{{end}} {{if ne (.Get "fixed_width") "false"}}fa-fw{{end}}"></i>
> > {{- end -}}
> > 
> > ```
> > 
> > If I use the shortcode with this syntax `{{< >}}` I see the icon on the header but the _HAHAHUGOSHORTCODE_ text on the ToC, like this:
> > 
> > ![image](https://user-images.githubusercontent.com/9049533/88482908-99aaac80-cf64-11ea-922b-0ebc8cb8bd48.png)
> > 
> > 
> > 
> > If I use the `{{% %}}` syntax then the icon is rendered on the next line below the header, like this:
> > 
> > ![image](https://user-images.githubusercontent.com/9049533/88482920-a29b7e00-cf64-11ea-8c84-93288ba8d8e0.png)
> > 
> > 
> > 
> > I reported this issue on `wowchemy-hugo-modules` and [was referred](https://github.com/gcushen/hugo-academic/issues/1746#issuecomment-644342807) here, but the solution posted here doesn't work for me. I'm also mentioning @gcushen (creator of [Wowchemy](https://wowchemy.com/)) just in case.
> > 
> > 
> > 
> > Thanks for your time!
> 
> Just wanted to remind this. The proposed solution doesn't work for me as the icon is not rendered on the heading but on the next line below. Maybe it's not a Hugo issue but a Wowchemy issue (related to the above `icon` shortcode). It'd be great if @gcushen could confirm it. Thanks in advance!

For anyone curious I got around this by directly including the icons without using any shortcode, just using the `<i class="fab fa-linux"></i>` syntax (in the case of [Font Awesome](https://fontawesome.com) icons).

**Comment by ncw** [comment]
I've come across this problem too.

I'll just note that the `{{% %}}` syntax doesn't work if you have `renderer.unsafe = false` and neither does the plain `<i class="fab fa-linux"></i>` solution for the same reason.

It would be nice to fix the table of contents renderer so ignores shortcodes.
