### ISSUE TITLE
Bundle file override language order seems arbitrary

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6082]
I have much simplified the "bundle implemention" and while diffing some sites output, I find some peculiar behavior when having many langauges and you try to reuse non-content files from others. Given this content structure:

```
nn/b1/index.md
en/b1/index.md
sv/b1/index.md
nb/b1/index.md
en/b1/data.json
sv/b1/data.json
```

For the `nb/b1` bundle (no data.json) you will now sometimes get `en/b1/data.json` and sometimes `sv/b1/data.json`.

This is obviously wrong (we should pick one and the same every time), but I have forgotten what it was "supposed to be"? @regisphilibert ?

**Comment by bep** [comment]
To answer myself in the above:

Pick the first available in a sorted language list, starting from the `default content language`.

**Comment by regisphilibert** [comment]
Yes we use the Weight to sort languages. And this order should solve the language "precedence" when dealing with page resources.
