### ISSUE TITLE
miekg/mmark repo is deprecated

### ISSUE THREAD

**Issue by QuLogic** [gohugoio/hugo#6085]
I just wanted to leave a note here that I noticed that the [readme for miekg/mmark states that it's deprecated](https://github.com/miekg/mmark#this-repository-is-deprecated) and has been moved to https://github.com/mmarkdown/mmark

**Comment by QuLogic** [comment]
Though looking at it a bit more closely, that repo is mainly for the executable. The API is not a one-to-one change. It is based on https://github.com/gomarkdown/markdown (which has a Mmark flag) but I'm not sure which one is more appropriate.

**Comment by moorereason** [comment]
We're aware.  mmark's future within Hugo is a little cloudy.  See discussion in #5124.

**Comment by gcushen** [comment]
#5124 was closed a while ago now without any apparent decision being made.

Is there any update on this - especially as the original Blackfriday is no longer really maintained and missing key features for technical content creators such as Mathtex support and citeproc support?
