### ISSUE TITLE
disableKind for Page should still add regular pages to the page collections

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6087]
I had a head-scratcher with this when I tested a theme I built several years ago:

* It's a single home page theme that just lists pages.
* I got an error about a missing single template, so I disabled `page` kind.
* And then the page listing vanished.

This does not make sense. We probably need to revisit the whole `disable` thing, but for now we adjust the behaviour for regular pages:

* If disabled, skip render, but do add them to the page collection so they can be listed if needed.

**Comment by guylyons** [comment]
Is there a repo for the theme?

**Comment by bep** [comment]
It's the `docuapi` theme under my account, but I suspect this use case is common enough: The current workaround is to create an empty `single.html` layout, but that sounds wasteful. I think we need to rethink this whole "disabled semantic" thing, though.
