### ISSUE TITLE
Syntax highlighting ‘specificity’ lower compared to text editors

### ISSUE THREAD

**Issue by lifepeer** [gohugoio/hugo#6088]
I'm using the built-in Chroma syntax highlighter but it seems to lack specificity compared to let's say VSCode or Atom. Consider the following example in JavaScript:

![ggdf](https://user-images.githubusercontent.com/17163509/61190092-fc514300-a696-11e9-8671-ce99d4741253.jpg)

As you can see, the output from Hugo/Chroma is limited in terms of how many different ‘elements’ it recognises.

This is confirmed by using the option `pygmentsUseClasses=true` and inspecting the classes it assigns to elements which are highlighted using different colours in text editors but the same once processed by Hugo/Chroma, for example ‘target’ and ‘offset’ both share the `class="nx"` even though one is a parameter and the other is a method. Another example is ‘this’ and ‘return’ which are both `class="k"`.

This issue is even more striking if you use some other language like R, which looks like there's no syntax highlighting at all… :(

![hfgdh](https://user-images.githubusercontent.com/17163509/61190321-ce6dfd80-a69a-11e9-9b63-bbc6798d6d35.jpg)

Is it possible to set up Hugo/Chroma to differentiate between such elements and assign them different classes, please?

**Comment by bep** [comment]
To get a fix for this, you need to open up an issue in the Chroma issue tracker: https://github.com/alecthomas/chroma/issues

**Comment by lifepeer** [comment]
Roger that, thank you.
