### ISSUE TITLE
Quick Start final step yields empty site

### ISSUE THREAD

**Issue by freelon** [gohugoio/hugo#6093]
When following the Quick Start guide one creates a single content site that is marked as draft. While the guide says to start the server including drafts (-D option) this is not the case for the last step, which just says to run "hugo" to get the site generated. So one is left with basically an empty site and no hint where the post is gone to.

I think it would be good to tell users to either use -D as well or to remove the draft status from the post (or maybe give a warning or info when compiling that states which files are omitted because of the draft state).

**Comment by julia-r** [comment]
I followed the Quick Start Guide as well and also get an empty page as an result. 
But changing the draft status does not fix it. Also I get this warning:
`found no layout file for "HTML" for "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.`

I think it would be a better end of the Quick Start Guide to be able to actually see a page. Because right now I am just confused and don't know how to go on.

**Comment by raluca-san** [comment]
I have run in the same issues. Any solution @julia-r and @freelon ?

**Comment by freelon** [comment]
I haven't used the quick start since then - the -D option didn't help? Did you get any errors/warnings?

**Comment by raluca-san** [comment]
No errors and no warnings. the -D option didn't help. I am still getting a blank website.

**Comment by freelon** [comment]
I just reran the quickstart and have no problem with the output. The test server and also the build is working fine. I'm using version 0.60.1 /extended linux/amd64

**Comment by julia-r** [comment]
It worked for me with a newer version (v0.59.1) and a fairly up to date theme ("indigo").

**Comment by bus710** [comment]
Hi, I also ran to the same issue...

1. The output of getting started doc is fine.
2. Then I commit to keep that work and move to other computers
3. clone and try "hugo server -D" => blank page with below warning.

```sh
bus710@aw17:automation$ hugo server -D
Building sites … WARN 2020/03/02 09:29:02 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/03/02 09:29:02 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/03/02 09:29:02 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/03/02 09:29:02 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/03/02 09:29:02 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/03/02 09:29:02 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

**Comment by emmaguy** [comment]
I ran into this too and found that the issue was that I missed this step in the quickstart guide:

>Then, add the theme to the site configuration:
>`echo 'theme = "ananke"' >> config.toml`

I skimmed past it because I thought it wasn't relevant - from the layout, it looked like it was under the 'for non-git users' section. I think this could be clearer, tbh.
