### ISSUE TITLE
Add a template function to process strings with shortcodes in them.

### ISSUE THREAD

**Issue by zivbk1** [gohugoio/hugo#6094]
With a frontmatter variable like:

`biography = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed nunc vitae turpis eleifend tincidunt. In hac habitasse platea dictumst. {{< figure src="/media/spf13.jpg" title="Steve Francia" >}} Pellentesque viverra a tellus in mollis. Sed vitae congue odio, vitae tristique magna. Mauris id fermentum libero, sit amet ultricies metus. "`

Provide a template function `shortcodify` that will render the figure shortcode into the output string.

This would allow shortcodes to be used in frontmatter data, within data file content, and expand the capabilities of Hugo for pages that require more than one 'content' block.  See the [Sawmill layout technique](https://forestry.io/blog/sawmill-layout-composer-for-hugo-and-forestry/) for an example of this use case, which is already supported by the Forestry.io CMS.

**Comment by bep** [comment]
>Provide a template function shortcodify that will render the figure shortcode into the output string.

Shortcodify? :-)

The shortcode's API requires a `Page`, so it couldn't be used in data files, and I think the "more than one content" block needs to be solved differently. I have plans for that. We could possibly, maybe adjust the shortcode's API to allow different things, and make this somehow work, but that is a rather big change and will need more than one person needing it.

**Comment by bwklein** [comment]
Yeah, I was trying to follow the naming model of some of the other functions. 😄  Call it whatever you like, I really just want the ability to convert a shortcode in the string into the HTML (or whatever) in the shortcode template.

I didn't realize there was a requirement of a `Page`, I assumed that it was more of a converter that took some shortcode name and the (positional or named) variables passed into the process, and replaced that shortcode call into the resulting output based on whatever was in the Shortcode file.

I am a bit surprised that more people haven't run into this yet.  The Sawmill method makes page building so easy for people.  Setting up design components (blocks) of the page and then letting the editor build a page from those components without requiring a developer to build a special layout for every possible combination of blocks the editor might want.

If you want to see the project that I am working on and where I have run into this issue, I'd be happy to show you.

**Comment by zivbk1** [comment]
I would like to have something in my templates like this to process the string and get what I want out of it. `{{ .Section.biography | shortcodify | markdownify }}`

The shortcodes in the string would be rendered and then the output string of that function would pipe into the markdownify function to convert any markdown in the string to HTML.

That's the hopes and dreams I have at the moment. 😄

**Comment by regisphilibert** [comment]
One prominent use case (already most of our recent projects at the moment) for this, is implementing a page builder solution with Hugo. 

When building a page with blocks of data, most of those are saved as Front Matter. It then falls on the developer to range on those blocks and apply the proper data processing/partial loading etc...

In the context of a page builder, Hugo shortcodes are currently unusable by the editor and any search-and-replace workaround cooked up by developers (been there) will never match the reliability and usability of Hugo's shortcode API.

**Comment by nicfits** [comment]
I'm using the Sawmill approach for our clients, and confirm this would be a useful feature for our editors.

**Comment by johndmulhausen** [comment]
Absolutely want this feature, see https://discourse.gohugo.io/t/call-shortcodes-in-markdownified-text/21189 for context

**Comment by regisphilibert** [comment]
@johndmulhausen I answered in your thread.

> The shortcode's API requires a Page

@bep This could simply be required parameter on the newly introduced `shortcodify` function. So we always end up with a page.

```
{{/* layouts/_default/single.html */}}
{{ range .blocks }}
  <div class="text">
   {{ shortcodify .content $ }}
  </div>
{{ end }}
```

**Comment by bwklein** [comment]
I think it is still relevant and seems like it's getting closer to being implemented.

**Comment by regisphilibert** [comment]
We should close in favour of #6703 though

**Comment by bwklein** [comment]
I'm ok with that.

**Comment by goldcoders** [comment]
Any news on this? im currently stucked on shortcodes not being rendered by markdownify 
and I cant also use .RenderString since Im not on The Page Scope but inside a partial.

Hope there is a switch that will trigger  markdownify to render shortcodes
Ive made so many shortcodes but is now useless for clients since the only shortcode that can be rendered properly
is image since it is supported natively by markdown.

Well as far as i can understand shortcodes can only be access by a Page ...

is there a possibility that if i convert my templates to use headless bundle and use that as a page
since we can do {{ $headless := .Site.GetPage "/some-headless-bundle" }}
An individual index and value  of $headless there contains a Page
In theory .Content would be accessible ...
and the only purpose of that page is to house that markdown section 

kinda complex ive been thinking it wholeday but havent implemented it yet...
Im using netlify CMS, it would require me to create a new collection just to house home/contents
then create a relation to fetch that page for just a specific section...

But i hope someone have already create a shortcodify functions :+1:

**Comment by regisphilibert** [comment]
@goldcoders you should track this one instead #6703
