### ISSUE TITLE
Proposal: Plush templating

### ISSUE THREAD

**Issue by lucperkins** [gohugoio/hugo#6095]
Over time, I've learned to like Go's native templating system but I do occasionally miss the "scripting language" feel of templating systems like [Mustache](https://mustache.github.io/) and [Liquid](https://jekyllrb.com/docs/liquid). It would be good if Hugo had a roughly analogous counterpart. This would ease the transition to Hugo for people coming from tools like Jekyll and Middleman and might even draw in some people like me who have become skilled with Go templating by accident.

Enter [Plush](https://github.com/gobuffalo/plush), the templating system from the people who make the [Buffalo](https://gobuffalo.io) web framework. It provides a templating syntax highly reminiscent—though not any kind of direct copy—of Liquid-style engines and even goes beyond them by providing things like [inline functions](https://github.com/gobuffalo/plush#controlling-output). Here's an example (from Plush's `README`):

```liquid
<%= if (names && len(names) > 0) { %>
<ul>
  <%= for (n) in names { %>
  <li><%= capitalize(n) %></li>
  <% } %>
</ul>
<% } else { %>
<h1>Sorry, no names. :(</h1>
<% } %>
```

The equivalent using Go templates (off the top of my head):

```html
{{ if and .names (gt len(.names) 0) }}
<ul>
  {{ range .names }}
  <li>{{ . | uppere }}</li>
  {{ end }}
</ul>
{{ else }}
<h1>Sorry, no names. :(</h1>
{{ end }}
```

Personally, I've come to prefer the latter over time, but it took me *years* to get there. The former has the potential to draw in new users and open up broad new horizons.

If I could get a few pointers on how to accomplish this I'm happy to do the work myself. I've poked around in the `tpl` directory but I'm still not quite sure how to make it happen. It's pretty clear how an HTML engine à la Ace and Amber work but the pre-HTML engine is less clear.

**Comment by bep** [comment]
>but I do occasionally miss the "scripting language" 

I think an addition like this needs something bigger than to just satisfy a "craving".

We have Ace and Amber, but if they compile to Go templates, so much easier to integrate. I don't know the Buffalo people good enough to understand if this is really great or not, but I have lots of questions:

* Does this integrate with Go templates at all? As in: Can we somehow let people use all of the existing partials out there?
* I assume we can plug in Hugo's wast template function library?
* I see no pipe support, so I assume we cannot get Hugo PIpes to work. 
* Does it support any template inheritance/decorators (aka base templates)?
* What is their security model?
* ...

So, it looks cool, and I hate to be the negative one. I expect a response in the line of "people could still use this for stuff without Hugo Pipes etc.", and you would probably be right, but even if we document those shortcomings, we would have plenty of support questions asking why "this and that fails".

**Comment by lucperkins** [comment]
@bep Those are 1000% valid concerns, so there's no harm in being the "negative one" here. I'll respond to your issues one by one:

* I suspect that this does *not* integrate with Go templates. Any given template would need to be "standard" or Plush but I don't see why they couldn't be mixed and matched in a project (though there may be internal considerations that I'm not privy to).
* There does appear to be a [mechanism](https://godoc.org/github.com/gobuffalo/plush#example-Render--CustomHelperFunctions) for adding custom functions via Plush's context object, though I'm not sure how much the existing function interface would need to be adapted to accommodate that system.
* Could you clarify what you mean by pipe support? I'm quite familiar with Hugo Pipes, but I'm not sure what is required for something be "Pipe friendly."
* I currently don't see support for template inheritance, and that would, of course, be a 100% blocker for this, full stop. I'll reach out to the maintainers. If that is not supported and there are no plans for that, we can safely put this feature to rest for the indefinite future.
* I'd need to ask the maintainers about this because it's not readily apparent.

In general, I concede that this is probably a "will not implement" at least for the time being, as I suspect that the necessary conditions aren't yet in place. But I'll keep tabs on it.
