### ISSUE TITLE
hugo creates different content when disableFastRender is false

### ISSUE THREAD

**Issue by shibumi** [gohugoio/hugo#6096]
Hi,
I have the following website in hugo:

https://github.com/shibumi/nullday.de

When I serve the website via `hugo serve` everything is fine, but when I do `hugo serve --disableFastRender` the content on the website is shown differently (the same behavior appears when I just generate the static content via `hugo`.

When I use `hugo serve` the website looks like this:
![](https://paste.xinu.at/G8zO/)

but when I use `hugo serve --disableFastRender` the website looks like this (**NOTE: I didn't change any files.. it's the same content**):
![](https://paste.xinu.at/9YTK/)

Do you have any idea for this behavior? At the moment it looks like a bug for me....

You can compare it to my website https://nullday.de (it's the wrong version at the moment, because  the generated static content is wrong)

Hugo Versions:

on my laptop:
Hugo Static Site Generator v0.55.6/extended linux/amd64 BuildDate: unknow

on my Server:
Hugo Static Site Generator v0.55.6-A5D4C82D2/extended linux/amd64 BuildDate: 2019-05-18T08:08:34Z

**Note: This behavior appears with _both_ versions**

**Comment by bep** [comment]
As fast render is only a server feature, if you say this is happing also for the hugo build, that cannot be it. I suspect you will get better help here: https://discourse.gohugo.io/

**Comment by shibumi** [comment]
@Bep I suspect a bug in this issue.. I have no other explanation for it. It really only happens when I build the content or use `--disableFastRender`. When I use `hugo serve` everything looks great.

**Comment by moorereason** [comment]
Built this locally (from hugo master).  I can confirm that `hugo` and `hugo server` yield different homepages.  It looks like `hugo` and `hugo server --disableFastRender` are using the `layouts/_default/list.html` template instead of the `layouts/index.html` template.  Also confirmed that `hugo server` works as expected.

**Comment by shibumi** [comment]
Ok i've found the reason for this behavior. It's definitely theme related. It happens only when I set `categories = ""` in my config.toml file. When I completely delete this line, everything works as expected.

I don't know if there is something to do in hugo, therefore closing this. Sorry for stealing your time, but this issue took my several days to debug and I was pretty confused about it. I'm happy that it's working now.

**Comment by parisi-n** [comment]
I have the same exact problem with Hugo 0.70: hugo server returns a version, hugo for building the site another. Looks like it is using list.html while building whereas the normal layout when serving the online version.
I have no empty category field in my config.toml though. Is there any workaround?
