### ISSUE TITLE
Add support for parsing citations and Jupyter notebooks via Pandoc and/or Goldmark extension

### ISSUE THREAD

**Issue by gcushen** [gohugoio/hugo#6101]
# Problems

1. Hugo's Goldmark and Blackfriday don't currently support citations using the popular Cite-Proc standard
   1.  What can we do to empower academics and technical content writers to write citations/bibliographies?
1. Currently Jupyter notebooks cannot be parsed by Hugo into Markdown
   1.   Empower data scientists, analysts, and academics by enabling Pandoc to parse Jupyter notebooks (`.ipynb`) into Markdown
1. Different parsers render things like ToC differently - how can we handle this and let the theme know which parser is being used on a page?
1. Currently, the `markup` option is only available on a per page basis - how can we give users the option to
   1. change the default parser to another parser such as Pandoc in order to parse technical content (if say a user prefer to trade off speed for functionality)
   1.  configure each parser's options in `config.toml`  ✅ **Done**

# Potential solution

Implementation stories:

- [ ] **Parse citations** - in scientific and technical writing, it's common to cite references exported by a reference manager such as Zotero. Here's the [Jekyll equivalent as an example](https://github.com/inukshuk/jekyll-scholar). References exported using the common Bibtex or CSL JSON standards and cited in an article could be parsed and a "References" section generated using:
  - by extending the existing Hugo-Pandoc integration by adding support for [Pandoc's Cite-Proc addon](https://pandoc.org/demo/example19/Extension-citations.html)
  - a Hugo parser or Goldmark extension (perhaps based on libraries such as [Goki Pi](https://github.com/goki/pi/tree/master/langs/bibtex) )
- [ ] **Parse Jupyter notebooks (`.ipynb`) into Markdown** - notebooks are a popular way (over 2.5M on Github) to combine markdown, code, and code outputs such as plots and tables. Conversion of `.ipynb` to a Hugo page bundle of markdown and images can be performed:
  - by extending the existing Hugo-Pandoc integration (Pandoc supports notebook conversion)
  - via Jupyter's nbconvert CLI tool ([Hugo PR](https://github.com/gohugoio/hugo/pull/4281))
  - or parsed directly within Hugo
- [x] Enable **choosing the default markup parser for the entire site** via a `markup` option in `config.toml`
   - Now implemented in #5963 
- [ ] **Allow themes to perform different actions depending on Markup**
  - Add site and page variables named `.Markup` so that we can perform different actions in a theme depending on the Markup of that site or page (to handle things like ToC being rendered differently)

**Comment by nancym** [comment]
If this happens, which I would like, please make `markup` a table so those of us who use multiple markup languages have better control. For example:

```
markup:
  mmark:
    - .md
    - .mdown
    - .markdown
  asciidoc:
    - .ad
    - .adoc
    - .asciidoc
  markup-lang:
    - .extension1
    - .extension2
```

Any markup language not specified in this config-file table would use Hugo's defaults, which I've written about at https://www.ii.com/hugo-markup-languages/

**Comment by gcushen** [comment]
I agree with the above comment - in particular, this flexibility of defining Markup for the site would enable Pandoc to parse Jupyter notebooks (`.ipynb`) into Markdown which would be extremely valuable for data scientists/analysts!

**Comment by gcushen** [comment]
**Also, please 🙏 add site and page variables named `.Markup` so that we can perform different actions in a theme depending on the Markup.**

For example, this would enable a theme to generate a TOC using our own Go Templating functionality for Mmark (which doesn't support automatic TOC generation) whereas a theme could automatically use the built-in TOC function if a page's Markup is BlackFriday.

**Comment by gcushen** [comment]
This issue is still relevant. In fact, it's currently the 3rd most upvoted feature request for Hugo.

**Comment by danmackinlay** [comment]
So that this issue is something other than people fending off the stalebot, perhaps we could split it into two: one for jupyter notebook support and one for `pandoc-citeproc`-like citations, each of which is more attainable in a pull-request?

**Comment by alexandrevicenzi** [comment]
I made a shortcode that parses ipynb into markdown, not the best way to solve the problem, but at least I can add a jupyter notebook as part of an article, or even add a dozen of notebooks.

It works like this: `{{<jupyter src="/path/to/jupyter/notebook.ipynb" >}}`

Does this approach sound interesting?

**Comment by ryan4yin** [comment]
> one for jupyter notebook support

I found one pr related to the jupyter support: https://github.com/gohugoio/hugo/pull/4281
