### ISSUE TITLE
deploy: deployment to an S3-compatible endpoint

### ISSUE THREAD

**Issue by vielmetti** [gohugoio/hugo#6116]
In #555 was the first discussion of deploying to S3, and the new `hugo deploy` command documented at https://gohugo.io/hosting-and-deployment/hugo-deploy/ shows how to use the AWS S3 as a deployment target.

There are other services other than AWS S3 that offer an S3-compatible endpoint, notably the self-hosted Minio described at https://min.io/ . It would be useful to be able to run `hugo deploy` and specify an S3-compatible endpoint.

**Comment by vielmetti** [comment]
From the looks of it, this might actually just work right now with suitable options on the s3: configuration string, as described in

https://github.com/google/go-cloud/blob/0801d6ac90be3f08f8a63cb505fdf9914fb4f269/internal/website/content/howto/blob/_index.md

If so, then this simply becomes a documentation question and not a code question. Additional reference docs are at https://godoc.org/gocloud.dev/aws#ConfigFromURLParams

**Comment by vielmetti** [comment]
The relevant document would be

https://github.com/gohugoio/hugo/blob/master/docs/content/en/hosting-and-deployment/hugo-deploy.md

**Comment by vangent** [comment]
Yes, you can specify an S3-compatible endpoint:
https://gocloud.dev/howto/blob/#s3-compatible

I'll send a PR to update the Hugo doc to link there.

**Comment by vangent** [comment]
https://github.com/gohugoio/hugoDocs/pull/877

**Comment by vangent** [comment]
https://gohugo.io/hosting-and-deployment/hugo-deploy/ has been updated with working links to gocloud.dev, and an explicit link for S3-compatible endpoints.

**Comment by vangent** [comment]
I think this issue can be closed, but I can't do it.

**Comment by vielmetti** [comment]
Looks good!
