### ISSUE TITLE
Image.Fit broken on 0.56 / wrong Width & Height

### ISSUE THREAD

**Issue by gj52** [gohugoio/hugo#6120]
image.fit does not change size

{{ $.Scratch.Set "image" (.Fit "370x246") }}{{ $image   := $.Scratch.Get "image" }}
<img  src={{ $image.RelPermalink | relURL}} width={{ $image.Width }} height={{ $image.Height }} >

The new image has the right size but $image.Width gives the original value 1480

**Comment by gj52** [comment]
sorry, my error ..

**Comment by gj52** [comment]
Error confirmed, switching from 0.55.6 to 0.56 
Lost version out of view - > reopened

**Comment by bep** [comment]
A, bugger. I disovered this myself and applied a fix which must have gotten lost somehow ...

**Comment by bep** [comment]
OK, I see where my confusion comes from. It works when you generated it the first time, but not later when read from cache.
