### ISSUE TITLE
"." access in Params changed for uncompatible types

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#6121]
Sorry for the misty title. I am not 100% sure but it seems that something changed with the `with` function in Hugo's latest release. There are several posts in discourse about issues in connection with the with function. 

In my case [1] the $.Param function breaks, saying it can't read type string. In another case it can't work with the result of MatchGet [2] (can't read type resource). 

[1] https://discourse.gohugo.io/t/access-to-param-subkey-stopped-working-in-0-56-0/19839
[2] https://discourse.gohugo.io/t/hugo-56-cant-evaluate-field-fill-in-type-resource-resource/19838

Either something changed in the handling of this function or we have a bug. 

You can use my repo https://github.com/davidsneighbour/samui-samui.de to check. Just clone and run hugo server and after a while it breaks with these errors. It was working in the previous release. 

Hugo Static Site Generator v0.56.0/extended linux/amd64 BuildDate: 2019-07-25T21:42:01Z
Using snap on Ubuntu 19.04

**Comment by bep** [comment]
I pulled the params function out into a common function to reuse it, so that is probably the cause -- but I'm a little surprised as we should have plenty of tests.

**Comment by bep** [comment]
OK, I see now. I see you use a combination of `author` (string) and `author.name`, wich I guess I accidently now throw an error for. Sorry for that.
