### ISSUE TITLE
Error on Windows with FAT32

### ISSUE THREAD

**Issue by gj52** [gohugoio/hugo#6127]
Windows x64 / device is USB FAT32; hugo 0.56.1

E:\hugo>hugo
INFO 2019/07/28 17:55:17 Using config file:
Building sites … INFO 2019/07/28 17:55:17 removing all files from destination that don't exist in static dirs
INFO 2019/07/28 17:55:17 syncing static files to E:\hugo\public\
Total in 2 ms
Error: Error copying static files: chtimes E:\hugo\public\: The parameter is incorrect.

**Comment by bep** [comment]
This is most likely an upstream issue with `os.Chtimes`  and should be reported here: https://github.com/golang/go/issues

I don't use FAT32 myself so this is not something I can follow up on.

**Comment by gj52** [comment]
Answer fom golang: Also, this is the Go issue tracker, and you seem to be having a problem with Hugo, not Go.

**I'm wondering why there is an invalid colon / double dot E:\hugo\public:**

**Comment by bep** [comment]
Can you link to the answer you got from Golang?

**Comment by bep** [comment]
OK, I see the issue on the Go tracker, I'll open another one an link to this one.

**Comment by gj52** [comment]
https://github.com/golang/go/issues/33334

**Comment by bep** [comment]
I created a new issue in https://github.com/golang/go/issues/33335

**Comment by VRandme** [comment]
Atleast in windows + exfat drive I can get around this error by adding
--noTimes command line argument

**Comment by gj52** [comment]
I switched to NTFS and all works fine

**Comment by r0bis** [comment]
> Atleast in windows + exfat drive I can get around this error by adding
> --noTimes command line argument

This is good to know. There are reasons sometimes to use FAT32 and with the error one does not know for sure if files were written actually, or whether hugo aborted processing (e.g. has not copied a few files).

**Comment by michaelboyles** [comment]
Still experiencing this problem using latest release 0.74.3

**Comment by dylan-k** [comment]
I had this problem today. The- `-noTimes` argument helped me to avoid the issue. Is there a solution that doesn't require switching to a different partition or using the argument forever?

**Comment by gj52** [comment]
This is an issue of FAT32 and exFAT design.  The only solution is to switch to NTFS or other filesystems (MAC, Linux).

**Comment by dylan-k** [comment]
I learned I could put `noTimes: true` into the config file at least, so I could fix it and forget it at the command line. Works for me, anyway.

**Comment by ErikMcClure** [comment]
The error message in Hugo should, at the very least, ask "are you on a FAT32 or exFAT system" and suggest enabling the `-noTimes` option instead of simply mysteriously dying and forcing people to google around for a closed issue that gives them the magic flag that makes this work in one of the comments.
