### ISSUE TITLE
.Scratch.Set and .Scratch.Add

### ISSUE THREAD

**Issue by gj52** [gohugoio/hugo#6130]
What happens with

```
.Scratch.Set "Key" "Value1"
.Scratch.Set "Key" "Value2"
```
Have we 2 elements with the same key or one element with the last key?
Please add a comment to the doc.

Thanks

**Comment by bep** [comment]
>Have we 2 elements with the same key or one element with the last key?

Set will overwrite any existing value with the same key. Add will, simply said, append it to the existing value. You should raise any docs issue in the docs repo, but the fastest is probably to create a PR with your clarifications to the docs.
