### ISSUE TITLE
How to create a theme? tutorials are missing

### ISSUE THREAD

**Issue by transwalle** [gohugoio/hugo#6132]
I want to get tips about how to create a theme, but the page is missing, please help.
the missing page: https://gohugo.io/tutorials/creating-a-new-theme/

**Comment by peaceiris** [comment]
Where did you find the URL? It does not seem to exist. And, please post issues like this at [gohugoio/hugoDocs](https://github.com/gohugoio/hugoDocs)

**Comment by transwalle** [comment]
@peaceiris  Thanks a lot!  I didn't find topics about creating themes on gohugo.io, so I get the URL above by search "how to create hugo theme" on google
