### ISSUE TITLE
Docs broken in Chrome: "Blocked script execution"

### ISSUE THREAD

**Issue by clozach** [gohugoio/hugo#6133]
## Issue
The side nav and code toggles are broken for me, presumably due to some CSP issue? At any rate, this error consistently pops up in the Chrome console:

> Blocked script execution in 'https://gohugo.io/documentation/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

## Environment
* Chrome Version 75.0.3770.142 (Official Build) (64-bit)
* macOS Version 10.14.5 (18F203)

## Reproduction
The issue's pretty consistent throughout the site, but not _everything_ is broken, so here are a couple of specific examples on the [Configure Modules page](https://gohugo.io/hugo-modules/configuration/)

- Clicking on "Content Management" in the side nav has no effect
- Clicking on "toml" in the code toggle has no effect

**Comment by bep** [comment]
We have moved the Hugo site source to its own repository, so we would appreciate if you could open this PR directly in `hugoDocs`:  https://github.com/gohugoio/hugoDocs/pulls

**Comment by clozach** [comment]
Sorry. It's no longer happening. Now thinking I should have restarted my machine before writing this up as an issue. 😬
