### ISSUE TITLE
Hugo 0.56.0+ blocks are not generated - 0.55.6 works

### ISSUE THREAD

**Issue by ForceFaction** [gohugoio/hugo#6142]
I'm trying to build a site with hugo 0.56.0+ and code blocks are not inserted (manually copying works). Also Hugo 0.55.6 builds this site just fine.

The code is:
```
{{ range where .Pages "Section" "events" }}
	{{ block "home-card" . }}
	{{ end }}
{{ end }}
```
and
```
{{ define "home-card" }}
<article class="card mb-4">
  <header class="card-header">
    <div class="card-meta">
      {{ .Params.location }}
    </div>
    <h4 class="card-title">
      {{ .Title }}
    </h4>
  </header>

  <div class="card-body">
    <p class="card-text">
      {{ .Content }}
    </p>
  </div>
</article>
{{ end }}
```

The generated files don't contain the contents of this code block.

**Comment by bep** [comment]
As we have plenty of tests on this and blocks are heavilly used in the wild, including Hugo's site, there must be something "special" about your site, which is impossible to judge without seeing the full source.

**Comment by ForceFaction** [comment]
This is a minimal example where i have this problem.
[minimal-example.tar.gz](https://github.com/gohugoio/hugo/files/3446525/minimal-example.tar.gz)

Thank you for the quick repsonse :)
