### ISSUE TITLE
Change linuxbrew to homebrew in docs

### ISSUE THREAD

**Issue by rajvaibhavdubey** [gohugoio/hugo#6151]
- Linuxbrew has been migrated to homebrew
- Similar changes need to be done in the installation docs also 

![Screenshot from 2019-08-01 11-54-50](https://user-images.githubusercontent.com/33062425/62270257-33737280-b453-11e9-94c0-4eb93af84c56.png)

**Comment by XhmikosR** [comment]
You should report and also fix this upstream https://github.com/gohugoio/hugoDocs

This can be closed.
