### ISSUE TITLE
0.56.3 extended binary on Win x64 crashes when creating first post (Ananke theme)

### ISSUE THREAD

**Issue by mrennix** [gohugoio/hugo#6157]
Following Quickstart, using Ananke theme. Step 4: Add Some Content fails:

hugo new posts/my-first-post.md
Error: failed to read module config for "ananke" in "G:\\_src\\web\\quickstart\\themes\\ananke\\theme.toml": unmarshal failed: Near line 11 (last key parsed 'min_version'): Invalid float value: "0.30.2"

**Comment by bep** [comment]
This should fix it: https://github.com/budparr/gohugo-theme-ananke/pull/189

Also, thanks for the Tweet.

**Comment by mrennix** [comment]
Yes thanks, works now, cheers.
