### ISSUE TITLE
v57 cannot parse theme's min_version ,Invalid float value: "0.55.0"

### ISSUE THREAD

**Issue by ikv163** [gohugoio/hugo#6162]
unmarshal failed: Near line 8 (last key parsed 'min_version'): Invalid float value: "0.55.0"

**Comment by bep** [comment]
I will make this more lenient, but this should really be fixed in the source (the theme). 

This is not valid YAML:

```yaml
min_version: 0.55.6
```

Bot these are correct and works:

```yaml
min_version: 0.55
```

```yaml
min_version: "0.55.6"
```

**Comment by bep** [comment]
@onedrawingperday note that I will add a fix for this that will prevent the ERROR (add a warning instead), so you may save some work to hold on with the theme site update until 0.57 (which will be a short release).

**Comment by onedrawingperday** [comment]
Ok. I've already made the rounds, though. At least now I will close the PR to remove an unmaintained theme that broke due to this.

Thanks.
