### ISSUE TITLE
PostCSS config and inline sourcemaps

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#6166]
I was experimenting with Hugo assets, and I noticed that if I don't include a postcss.config.js and pass the PostCSS options directly, then the CSS has the sourcemap inlined with no way to change this, at least AFAICT.

This works without any inline sourcemaps:

```js
// postcss.config.js
module.exports = {
    plugins: [
        require('autoprefixer')
    ]
}
```

```html
{{- $sassOptions := (dict "targetPath" "assets/css/docs.css" "outputStyle" "compressed" "enableSourceMap" true) }}
{{- $style := resources.Get "scss/docs.scss" | toCSS $sassOptions | postCSS | fingerprint }}
<link rel="stylesheet" href="{{ $style.Permalink | relURL }}">
```

This results in inlined sourcemap in docs.css (without using a postcss.config.js file):

```html
{{- $sassOptions := (dict "targetPath" "assets/css/docs.css" "outputStyle" "compressed" "enableSourceMap" true) }}
{{- $postCSSOptions := (dict "use" "autoprefixer" "noMap" true) }}
{{- $style := resources.Get "scss/docs.scss" | toCSS $sassOptions | postCSS $postCSSOptions | fingerprint }}
<link rel="stylesheet" href="{{ $style.Permalink | relURL }}">
```

Resulting CSS:

* with postcss.config.js: https://gist.github.com/XhmikosR/9e1666e421bd7b16894431f8fa79533f/2b1542fad0c5b498d875d0c57d97a03e7b786230
* without: https://gist.github.com/XhmikosR/9e1666e421bd7b16894431f8fa79533f/758476255488b3cab9b8faa13d89c81ed2530c54

It seems `noMap` has no effect without a config file.

**Comment by bep** [comment]
{{- $postCSSOptions := (dict "use" "autoprefixer" "noMap" true) }}


Use "no-map".

I apply a patch that works with both.
