### ISSUE TITLE
Leading whitespace discarded inside fenced code block following list

### ISSUE THREAD

**Issue by isometry** [gohugoio/hugo#6176]
`Hugo Static Site Generator v0.56.3-F637A1EA darwin/amd64 BuildDate: 2019-07-31T12:50:22Z`

The default Blackfriday rendering engine always embeds fenced code blocks immediately following a list item within the list item, and discards all leading whitespace from within the code blocks.

Testcase:

~~~yaml
---
title: "Testcase"
date: 2019-08-07T21:11:09+02:00
markup: markdown
---
* list

```
zero
 one one
  two  two
   three   three
```
~~~

Expected output:

~~~html
<ul>
<li>list</li>
</ul>
<pre><code>zero
 one one
  two  two
   three   three
</code></pre>
~~~

Actual output:

~~~html
<ul>
<li>
<p>list</p>
<pre><code>zero
one one
two  two
three   three
</code></pre>
</li>
</ul>
~~~

**Comment by HanOostdijk** [comment]
With Hugo 0.57.2 and theme Xmin (I asume the theme plays no role here) I get the same.

input:

````
My new list: 

- first entry
- second entry
- third entry

```
my nice code
```
````

Expected output:
```
<p>My new list:</p>

<ul>
<li>first entry</li>
<li>second entry</li>
<li>third entry</li>
</ul>

<pre><code>my nice code
</code></pre>
```

Actual output:

```
<p>My new list:</p>

<ul>
<li>first entry</li>
<li>second entry</li>

<li><p>second entry</p>

<pre><code>my nice code
</code></pre></li>
</ul>
```
I can avoid the problem by inserting a non-empty line or a comment line (`<!-- my comment here -->`) between the list and the code block.

**Comment by onedrawingperday** [comment]
Not that this will help you resolve this particular Blackfriday issue, but currently Goldmark (another markdown engine) is under consideration and planned to become the default Markdown engine in Hugo v.0.58.0

You may want to follow the following issues:
https://github.com/gohugoio/hugo/issues/5963
https://github.com/gohugoio/hugo/issues/6229
