### ISSUE TITLE
Shortcodes are not reloading when inner resources are changed

### ISSUE THREAD

**Issue by totkeks** [gohugoio/hugo#6177]
I have a shortcode to show HTML code examples, both rendered by the browser and the actual code. To keep the examples working properly, I place them and their styles inside a shadow DOM, so the browser ignores the global styles.
This is done by requesting the stylesheet (built in a process parallel to the hugo serve process) as a resource and then passing the link to a javascript that then places it in the shadow dom on creation.
It looks something like this:
```
{{- $styles := resources.Get "dist/main.min.css" | fingerprint -}}
<template class="example" data-styles="{{ $styles.Permalink }}">
```

The problem now is, that when the `main.min.css` file changes, the shortcode using it, is not rebuilt. So I don't see updated styles in my content pages that contain the HTML code examples.
My assumption now is, that the shortcode is not rebuilt, because it does not see the resource as a dependency. Because if I touch the shortcode file, then hugo rebuilds it and the updated css file will be loaded.

**Comment by bep** [comment]
This is a known current limitation (I think there is a similar issue floating around).

But it isn't easily solved.

So what I suggest you do in the meantime is something ala:

```
{{- $styles := resources.Get "dist/main.min.css" -}}
{{ if eq hugo.Environment "production" }}
{{- $styles = $styles | fingerprint -}}
{{ end }}
```

**Comment by totkeks** [comment]
Thanks for your reply! Unfortunately that does not work for me. It still didn't rebuild the shortcode, when I rebuilt the `main.min.css`.
What I did instead now as a workaround, is touching (just triggering a read/write) the shortcode file after the `main.min.css` has been built.
This works, even though it is not a nice way to achieve it.

**Comment by bep** [comment]
> It still didn't rebuild the shortcode, when I rebuilt the main.min.css.

I don't see why it would need to rebuild the shortcode when it's not changing anything, but good you found a way.

**Comment by THS-on** [comment]
Is this the same limitation with data from the data folder?
If I change something in a file that is under data the shortcode is not updated that uses that data.
Is there a workaround for this other than touching the shortcode after a file update?

**Comment by gpit2286** [comment]
I'm also running into this. I have dynamically generated png's and when the data.json file updates, Hugo reloads the page but doesn't reload the data from the json file.  

@bep What about this is hard to implement? I may help give us a better understanding of how to "fix" it.

**Comment by zgoertz** [comment]
Any progress on this bug?

**Comment by bep** [comment]
I'm pretty sure this one should be fixed by now.
