### ISSUE TITLE
<figure> shortcode shouldn't use <h4> in <figcaption>

### ISSUE THREAD

**Issue by patdavid** [gohugoio/hugo#6194]
I just tried using the `<figure>` shortcode and found that the `<figcaption>` uses a heading element (`<h4>`) _inside_ the figcaption.

Semantically this seems wrong to me?  I'd not expect a _heading_ element to exist inside a caption for a figure.  I'm curious if anyone else feels this way?  If so I'm happy to send a PR to make the caption content exist inside `<figcaption>` bare (which seems more semantically correct to me).

Ahh, just realized I made a mistake and forgot about the actual `caption` attribute for the shortcode.

Still - using a heading inside the `figcaption` seems odd - perhaps we can replace `<h4>` with a better tag?

**Comment by peaceiris** [comment]
https://github.com/gohugoio/hugo/blob/aba2647c152ffff927f42523b77ee6651630cd67/tpl/tplimpl/embedded/templates/shortcodes/figure.html#L14-L26

**Comment by skyfaller** [comment]
I'd also like to question the use of `<h4>` heading in the caption for a figure. Why does there need to be any markup inside of figcaption at all? >92% of users are on browsers that support figcaption, including Internet Explorer 9+: https://caniuse.com/#search=figcaption

Is there any reason we can't just use the bare figcaption element? The h4 makes the captions huge in the Hugo theme I'm using, and while I can change that, it just seems like unnecessary markup that requires me to write unnecessary CSS.
