### ISSUE TITLE
warning does not include line number

### ISSUE THREAD

**Issue by tcurdt** [gohugoio/hugo#6203]
I am getting this warning

```
Building sites … WARN 2019/08/13 13:24:32 .File.Path on zero object. Wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}
```

and it's rather hard to figure out which of the `.File.Path` is the problem.

For the sake of completeness I'll add the code in question below (I don't see it yet) but my point is that hugo should tell the line and ideally even the column inside the file.

This is with hugo `v0.56.3/extended darwin/amd64`

```
{{ $self := . }}
{{ $related := len (.Params.related | default "") }}
{{ $cols := 3 }}
{{ $show := 3 }}
{{ $mod := mod $related $cols }}
{{ $sum := add $related $mod }}
{{ $total := cond (ge $sum $show) $sum $show }}

{{ $.Scratch.Set "tiles" (dict $self.File.Path 1) }}

<section class="more">
  <ol>

  {{ range .Params.related }}
    {{ with $.Site.GetPage "page" . }}
      {{ if not (index ($.Scratch.Get "tiles") .File.Path) }}
        <li class="related">
          {{ partial "article_tile.html" (dict "text" "related" "article" .) }}
          {{ $.Scratch.SetInMap "tiles" .File.Path 1 }}
        </li>
      {{ end }}
    {{ end }}
  {{ end }}

  {{ range $post := first 10 (where $.Site.Pages "Section" "posts") }}
    {{ if le (len ($.Scratch.Get "tiles")) $show }}
      {{ with $.Site.GetPage "page" $post.File.Path }}
        {{ if not (index ($.Scratch.Get "tiles") .File.Path) }}
          <li class="recent">
            {{ partial "article_tile.html" (dict "text" "recent" "article" $post) }}
            {{ $.Scratch.SetInMap "tiles" .File.Path 1 }}
          </li>
        {{ end }}
      {{ end }}
    {{ end }}
  {{ end }}

  </ol>
</section>
```

**Comment by bep** [comment]
This has been asked before, but I don't know how to (in a simple way) implement it.

**Comment by tcurdt** [comment]
Bummer. I assume because of the use of the go template language - that is not exposing that information?

**Comment by tcurdt** [comment]
Is there a way to debug (as in step through) templates? Because from reading the code I don't see the problem.

I think `$self` should never be a zero object, `$post` should never be zero as it's coming from `range` (unless I misunderstand the `first 10`) and all other `.File.Path` are wrapped in a `with`.

Better take that to the forum?

**Comment by bep** [comment]
>Better take that to the forum?

Yes.
