### ISSUE TITLE
Broken link on Hugo 

### ISSUE THREAD

**Issue by CarlvinJerry** [gohugoio/hugo#6206]
My website renders something totally different from what is rendered locally. I'd like to think it has something to do with reinstalling the Mainroad theme after the latest Hugo update. Ideally should look something like this 
![Capture1](https://user-images.githubusercontent.com/38648589/62959058-99230f80-be00-11e9-8b54-ce50a3a1bd91.PNG) 

but I'm getting this on the url https://beyondrawdata.rbind.io 

![Capture2](https://user-images.githubusercontent.com/38648589/62959185-ddaeab00-be00-11e9-9541-fa2285825946.PNG). I'm still new to this, I'd appreciate any help out there

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
