### ISSUE TITLE
Page properties returns inv. mem. address despite conditional on 57

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#6210]
I'm getting nil pointer references with the following property even wrapped in a `with`
```
{{ with .WordCount }}
{{ . }}
{{ end }}
```
👉 `error calling WordCount: runtime error: invalid memory address or nil pointer dereference`

- WordCount
- Summary
- Content
Maybe more 🤷‍♂ 

Issue also happens with internal template: `executing "_internal/_default/rss.xml" at <.Summary>: error calling Summary: runtime error: invalid memory address or nil pointer dereference`

I think all it takes is a page with no content.

**Comment by bep** [comment]
I assume the nilpointer is happening inside those methods, so with won't help. Hmm. I would think we would have a million tests for this.

**Comment by bep** [comment]
Quick question before I spend time on this: Anything special about this site of yours?

**Comment by bep** [comment]
Possibly related: https://discourse.gohugo.io/t/nil-pointer-evaluating-resource-resource-resize-in-version-0-57-0/20208

**Comment by regisphilibert** [comment]
I'm sorry I have no time to run test just yet on smaller repos. But yes, always some special stuff in there. I'll try and setup a repo for you, if no noise in the discourse, it must means it's not necessarily a broad issue.

**Comment by brunoamaral** [comment]
I was getting the same error because I had 
```yaml
outputs: "Reveal"
```
instead of 
```yaml
outputs: ["Reveal"]
```

**Comment by bep** [comment]
Yes, I'm suspecting this happens when there for some reason happens to be no output formats defined for a page (I assume "outputs: "Reveal" => []")
