### ISSUE TITLE
Add tpl/sites

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#6211]
This should be labeled as a wish...

I know we should really limit those global function and the [wish was to stop at `site` and `hugo`](https://github.com/gohugoio/hugo/issues/5470#issuecomment-441464382). 
But there's still one page method desperately needed in the layout tree or "returning" partilas and for which we'd rather avoid having to pass the page context all the way down the "tree".

This is `.Sites` which I (maybe just me) often to find the "default language" site when in another language.  (`.Sites.First`)

**Comment by bep** [comment]
You can do ... `site.Sites.First`.
