### ISSUE TITLE
Draft files are not ignored in taxonomies

### ISSUE THREAD

**Issue by akshaybabloo** [gohugoio/hugo#6216]
Any page that is marked as a draft can be seen in the `categories` and `tags`, but the `href` tag is empty.

Example:

Lets say I have a blog file in `content/blog/text-file.md` with title `Text File` and the draft is set to `false`, building this creates a link as `<a href="">Text File</a>`.

Repository to try: https://github.com/akshaybabloo/gollahalli.com

**Update**

The taxonomies used in these pages are also created.

**Comment by jgreely** [comment]
Beat me to filing the bug! My forum post with a stripped-down repeat-by is [here](https://discourse.gohugo.io/t/the-most-recent-draft-article-is-being-partially-included-in-non-draft-builds-in-0-57-0/20210/5).

**Comment by bep** [comment]
Duplicates #6213.
