### ISSUE TITLE
Add validation ERROR for mounted files

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6219]
I saw this in a config in the wild:

```
   - source:           site/static/docs/4.3/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/4.3/assets/img/favicons/favicon.ico
      target:           static/favicon.ico
```

**Mounts are for directories only.**

/cc @XhmikosR

**Comment by XhmikosR** [comment]
Hmm, this actually works already, though...

https://deploy-preview-29161--twbs-bootstrap.netlify.com/favicon.ico

**Comment by XhmikosR** [comment]
Could be because the whole static dir is in a mount before the files?

**Comment by bep** [comment]
>Hmm, this actually works already, though...

Define "works".  Mounts were implemented as "dirs only" and there are plenty of assumptions in the code expecting dirs. So, while it may be possible to make it work for single files, that is certainly not in my time budget to fix. And I would only accept a PR if the change was simple.

**Comment by XhmikosR** [comment]
No, I mean it already works for our case as you can see from the link.

No worries, there's so many things to do, so I understand.

**Comment by bep** [comment]
>No, I mean it already works for our case as you can see from the link.

I see that it "works", my point is: We use these mounts in situations where we assume it's a directory ("get me the list of static directories to watch", "given this filename, what filesystem does it belong to and give me the path relative to that filesystem").

**Comment by XhmikosR** [comment]
I see, alright. I'll remove those, although if this was ever implemented, it would be rad.

**Comment by bep** [comment]
Curious, I understand you want the version number in every path, but why not


Change

```yaml
   - source:           site/static/docs/4.3/assets/img/favicons/favicon.ico
      target:           static/favicon.ico
```

To

```yaml
   - source:           site/static/docs/4.3/assets/img/favicons
      target:           static/4.3/favicons
```

Or something.

**Comment by XhmikosR** [comment]
Because those are supposed to go into the root for old browsers and tools that still request them there.

**Comment by bep** [comment]
OK. Create an issue and describe the use case. Maybe we can do something.
