### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [gohugoio/hugo#6227]
Hi, I'm Yevgeny Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Also, we have a [reward](https://fuzzit.dev/2019/08/12/announcing-rewards-for-go-rust-oss-projects/) program. If you are interested in implementing the fuzzers and the integration yourself I’ll be happy to reward you as well as to get unbiased feedback on how smooth the integration was.

Cheers,
Yevgeny

**Comment by bep** [comment]
I created this issue at one point: #5710 -- and we will eventually get to it. And it's not about the reward, but we prefer to choose the fuzzing platform/integration ourselves. Mostly to keep it maintainable -- Hugo is a fairly old Go project, but the code base is moving fast.

**Comment by yevgenypats** [comment]
@bep sounds good. I'll keep an eye on those issues, so feel free to ping here anytime you think this is relevant.
