### ISSUE TITLE
Posts seems to not render anymore on the front page

### ISSUE THREAD

**Issue by QuentinChevance** [gohugoio/hugo#6230]
Hello,

As you can see on all these demos:
- https://themes.gohugo.io/theme/blackburn/
- https://themes.gohugo.io/theme/hugo-geo/
- https://themes.gohugo.io/theme/hugo-octopress/

The "Posts" section seems to be bugged out, the posts don't appear anymore on the front page.
I don't know if it's an  already known issue or not.

**Comment by bep** [comment]
See https://github.com/gohugoio/hugoThemes/issues/682
