### ISSUE TITLE
Incorrect tag sequence in bfconfig.md

### ISSUE THREAD

**Issue by albert-github** [gohugoio/hugo#6232]
In the file `docs/content/en/readfiles/bfconfig.md` we see on line 27 the statement:
```
    Example: `5/12` renders to <sup>5</sup>&frasl;<sub>12</sub>(<code>&lt;sup&gt;5&lt;/sup&gt;&amp;frasl;&lt;sub&gt;12&lt;/sub&gt;</code>).<br> <strong>Caveat:</strong> Even with <code>fractions = false</code>, Blackfriday still converts `1/2`, `1/4`, and `3/4` respectively to Â½ (<code>&amp;frac12;</code>), Â¼ (<code>&amp;frac14;</code>) and Â¾ (<code>&amp;frac34;</code>), but only these three.</small>
```
i.e. a `</small>` tag without a starting `<small>` tag.

This should probably be without `</small>` or after the 'Caveat' there should be a `<small>` start tag.

Hugo version 0.57.1 (and also in master).

**Comment by XhmikosR** [comment]
Docs issues should be reported and fixed [upstream](https://github.com/gohugoio/hugoDocs)

**Comment by albert-github** [comment]
Reported now as https://github.com/gohugoio/hugoDocs/issues/891

Would be useful to have in the contribution guidelines  (https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#reporting-issues) a small remark about where to report documentation issues.
It now states:
> If you believe you have found a defect in Hugo or its documentation, use the GitHub [issue tracker](https://github.com/gohugoio/hugo/issues) to report the problem to the Hugo maintainers.

so all issues can be reported in this issue tracker.

**Comment by XhmikosR** [comment]
Feel free to submit a PR for that too. And close this one.

**Comment by albert-github** [comment]
As suggested reported documentation to other repository and created new issue #6233 for an update of CONTRIBUTING.md
