### ISSUE TITLE
Incorrect place to report documentation issues

### ISSUE THREAD

**Issue by albert-github** [gohugoio/hugo#6233]
Would be useful to have in the contribution guidelines  (https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#reporting-issues) a small remark about where to report documentation issues.
It now states:
> If you believe you have found a defect in Hugo or its documentation, use the GitHub [issue tracker](https://github.com/gohugoio/hugo/issues) to report the problem to the Hugo maintainers.

so all issues can be reported in this issue tracker.

(previously part of #6232)

**Comment by albert-github** [comment]
As stated in the issue report, it should be made clear where to report documentation issues.

**Comment by peaceiris** [comment]
Open #6617
