### ISSUE TITLE
Breaking changes from v0.56.3 to v0.57.0 and v0.57.1

### ISSUE THREAD

**Issue by jeremyf** [gohugoio/hugo#6235]
First, thank you for your continued effort on supporting a great open source project. I appreciate the time and energy you put forward into this endeavor.

Using v0.56.3 I get the following output and what I consider a successfully built page:

```console
                   |  EN   
+------------------+------+
  Pages            | 1482  
  Paginator pages  |   86  
  Non-page files   |    0  
  Static files     |   73  
  Processed images |  330  
  Aliases          |    7  
  Sitemaps         |    1  
  Cleaned          |    0  
```

When I switch from v0.56.3 to v0.57.0, I get the following and the site won't build:

```console
Building sites … ERROR 2019/08/16 14:05:17 render of "section" failed: "~/git/takeonrules.github.io/themes/hugo-tufte/layouts/_default/page.html:24:13": execute of template failed: template: _default/page.html:3:5: executing "_default/page.html" at <partial "head.html" .>: error calling partial: "~/git/takeonrules.github.io/themes/hugo-tufte/layouts/partials/head.html:24:13": execute of template failed: template: partials/head.html:31:9: executing "partials/head.html" at <partial "jsonld.json" .>: error calling partial: "~/git/takeonrules.github.io/layouts/partials/jsonld.json:24:13": execute of template failed: template: partials/jsonld.json:64:4: executing "partials/jsonld.json" at <partial "single-jsonld.json" .>: error calling partial: "~/git/takeonrules.github.io/layouts/partials/single-jsonld.json:24:13": execute of template failed: template: partials/single-jsonld.json:24:13: executing "partials/single-jsonld.json" at <.Content>: error calling Content: runtime error: invalid memory address or nil pointer dereference
```

When I switch from v0.57.0 to v0.57.1, I get the following output. The homepage does not show pagination, however I can direct link to the posts. Notice the paginator pages count drops to 0.

```console

                   |  EN   
+------------------+------+
  Pages            | 1488  
  Paginator pages  |    0  
  Non-page files   |    0  
  Static files     |   73  
  Processed images |  212  
  Aliases          |    7  
  Sitemaps         |    1  
  Cleaned          |    0  
```

The pagination logic I've fiddled with using 0.57.1 is found https://github.com/jeremyf/hugo-tufte/blob/master/layouts/index.html#L5

I am using the following theme: https://github.com/jeremyf/hugo-tufte.

**Comment by bep** [comment]
I'm sorry for the noise and trouble, but this is a change I have wanted to do for a long time, and since we needed to do 2 more related, but more subtle, changes, now was the time.

See https://github.com/jeremyf/hugo-tufte/pull/1

**Comment by jeremyf** [comment]
@bep Thanks for the quick response. I tested your PR against v0.56.3 and it works. I tested against v0.57.1 and I get the same behavior as reported. I'm prepared to work on a greater refactor of the site and even extract content (as it sits separate and non-publicly) to provide a test case.

I have a functioning install, so this is not an urgent issue. But I would love to be able to stay on a more up to date version of Hugo. So let me know how I can further help.

Again thank you!

**Comment by jeremyf** [comment]
As a follow-on, I did some more digging in my hugo build. I had two paginators declared. One for the main page HTML version and a second for the JSON+LD/Schema.org generation. Originally both paginators had the following (note these were in different files):

```console
# For HTML
{{ $paginator := .Paginate (where .Pages "Type" "post") 5 }}

# For Schema.org
{{ $jsonPaginator := .Paginate (where .Pages "Type" "post") 5 }}

# Result of hugo serve
                   |  EN   
+------------------+------+
  Pages            | 1490  
  Paginator pages  |    0  
  Non-page files   |    0  
  Static files     |   73  
  Processed images |  214  
  Aliases          |    7  
  Sitemaps         |    1  
  Cleaned          |    0  
```

When I merged @bep's PR, I had the following:

```console
# For HTML
{{ $paginator := .Paginate (where .Site.RegularPages "Type" "post") 5 }}

# For Schema.org
{{ $jsonPaginator := .Paginate (where .Pages "Type" "post") 5 }}

# Result of hugo serve
                   |  EN   
+------------------+------+
  Pages            | 1490  
  Paginator pages  |    0  
  Non-page files   |    0  
  Static files     |   73  
  Processed images |  214  
  Aliases          |    7  
  Sitemaps         |    1  
  Cleaned          |    0  
```

When I changed both paginators to use `.Site.RegularPages` instead of `.Pages`, my pagination worked.

```console
# For HTML
{{ $paginator := .Paginate (where .Site.RegularPages "Type" "post") 5 }}

# For Schema.org
{{ $jsonPaginator := .Paginate (where .Site.RegularPages "Type" "post") 5 }}

                   |  EN   
+------------------+------+
  Pages            | 1490  
  Paginator pages  |   87  
  Non-page files   |    0  
  Static files     |   73  
  Processed images |  332  
  Aliases          |    7  
  Sitemaps         |    1  
  Cleaned          |    0  
```

Again many thanks to @bep for your contributions to Hugo.
