### ISSUE TITLE
Conditional Loading of Disqus Comments

### ISSUE THREAD

**Issue by thewismit** [gohugoio/hugo#6242]
At this URL: https://gohugo.io/templates/internal/#disqus you give the script needed to load the Disqus comments, conditionally.

I had to change `var disqus_shortname = '{{ .Site.DisqusShortname }}';` to `var disqus_shortname = '{{ .Site.Params.DisqusShortname }}';` in order to get it working.

I use the hugo-book theme.

I don't know if this is theme related but want to let you know, just in case it is not.

**Comment by davidsneighbour** [comment]
It is theme related. The proper location of the disqus shortname is `.Site`

https://gohugo.io/variables/site/#site-variables-list
