### ISSUE TITLE
Where have the theme creation docs gone?

### ISSUE THREAD

**Issue by JamesTheHacker** [gohugoio/hugo#6243]
Tried to access the docs to develop a new theme. I needed to check a few things and noticed the page is down: https://gohugo.io/themes/creating/

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by JamesTheHacker** [comment]
Hey @bep I'm a member on there. But the reason why I have filed this here is because the documentation for theme creation is 404. It used to be accessible, but is no longer. This means theme developers can not get access to the documentation.

**Comment by JamesTheHacker** [comment]
I found the documentation under templates. My error, I've been using other systems the past couple of months that use the term theme as opposed to templates.
