### ISSUE TITLE
relLangURL adds base url when given value is absolute url with different protocol

### ISSUE THREAD

**Issue by mpourismaiel** [gohugoio/hugo#6244]
When using `relLangURL` and passing it values such as `irc://example`, Hugo thinks the value is relative and prepends base url. I think it's because of this condition which returns false and that url doesn't fall through:

helpers/url.go:218

`(!strings.HasPrefix(in, baseURL) && strings.HasPrefix(in, "http")) || strings.HasPrefix(in, "//")`

I think it should change to another condition which checks if protocol or "//" is provided in the value which would make it an absolute url.

**Comment by ConnorAYoh** [comment]
It would be extremely useful to use different protocols such as tel: and even custom protocols for use in an intranet environment.

**Comment by mpourismaiel** [comment]
I would appreciate any response on this issue.

**Comment by mpourismaiel** [comment]
Any news on this issue?

**Comment by johncassil** [comment]
I'm also trying to use a tel: link and getting http://127.0.0.1:4321/tel:/[phonenumber]
Please fix this!
