### ISSUE TITLE
Why do I have an additional Posts directory on my home page?

### ISSUE THREAD

**Issue by hui305** [gohugoio/hugo#6246]
hugo server -D

 http://localhost:1313/

there is only posts directory on my home page?

who could help me,thx

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by jimmylin212** [comment]
In case you are not found the solution yet. Here is the reference:

https://discourse.gohugo.io/t/not-showing-blog-posts-after-upgraded-to-0-69/24819 
https://github.com/gohugoio/hugo/releases/tag/v0.57.0

> `.Pages` now include sections. We have added `.RegularPages` as a convenience method if you want the old behaviour

Pull your theme for update. Someone should already send PR for this.
