### ISSUE TITLE
0.57.2 RegularPages Performance Issues

### ISSUE THREAD

**Issue by nraboy** [gohugoio/hugo#6247]
Hi,

I just upgraded to 0.57.2 from 0.56 and received the following warning:

```
WARN 2019/08/18 15:36:58 In the next Hugo version (0.58.0) we will change how $home.Pages behaves. If you want to list all regular pages, replace .Pages or .Data.Pages with .Site.RegularPages in your home page template.
```

It wasn't obvious based on the warning where I was experiencing this, but I tracked it down to my **rss.xml** file in my layout.

In my RSS template, I have the following:

```
{{ range .Data.Pages }}
```

The loop for each `<item>` works fine in 0.57.2, but I do realize it will be going away. I changed that line to the following:

```
{{ range .Site.RegularPages }}
```

After changing the line, the warning disappeared, but it took my build time from **~1 seconds** to **~16 seconds**.

Am I using this correctly in my RSS template? My expectation is that my RSS file would include all posts that exist on the site. The documentation is still referencing `{{ .Pages }}`, which I'm assuming is not correct anymore.

Please let me know your thoughts.

Thanks,

**Comment by bep** [comment]
Hey,

I'm guessing here, but I suspect that you're outputting RSS for more than the home page, and if you're rendering every page thousand of times ...

Maybe a snippet like this can help:

```bash
{{- $pctx := . -}}
{{- if .IsHome -}}{{ $pctx = .Site }}{{- end -}}
{{- $pages := $pctx.RegularPages -}}
```

**Comment by nraboy** [comment]
Hi @bep,

I recognize that GitHub issue tickets are not the correct way for support and I'm sorry if this sounds silly, but how do I determine if I'm outputting RSS for more than the home page?

In my **config.json** file, I have the following:

```
"outputs": {
    "home": ["HTML", "RSS", "Sitemap"]
},
```

In addition to the above, I also have this in the `<head>` tags of every page:

```
{{ range  .OutputFormats }}
    {{ printf `<link rel="%s" type="%s" href="%s" title="%s" />` .Rel .MediaType.Type .Permalink $.Site.Title | safeHTML }}
{{ end }}
```

Does the builder generate my RSS output file every time it sees the loop? I would have thought it to generate one time based on the **config.json** file, but maybe I'm wrong.

Also, to add to my questions, what kind of templating Markup is in the example you provided? I'm not sure I've seen tags with the hyphen character before. Does it have a name so I can search the documentation?
