### ISSUE TITLE
'TODO' in file name causes error when generating files

### ISSUE THREAD

**Issue by cobratbq** [gohugoio/hugo#6249]
The word 'TODO' in the file name causes generation to fail with an error. The error itself is rather obscure, as I believe it does not demonstrate the actual error that is reported.

```
➜  site git:(master) ✗ hugo version
Hugo Static Site Generator v0.57.2-A849CB2D linux/amd64 BuildDate: 2019-08-17T17:54:13Z
➜  site git:(master) ✗ hugo
Total in 102 ms
Error: Error building site: no Path provided by map[classifier:zcontent filename:/home/user/dev/site/content/TODO.md fs:0xc000473380 isOrdered:false lang:en mountWeight:2 name:TODO.md opener:0xb54480 ordinal:0 path:TODO.md pathWalk:TODO.md translationBaseName:TODO translationBaseNameWithExt:TODO.md translations:[en] watch:true weight:0] (*hugofs.RootMappingFs)
➜  site git:(master) ✗ git mv content/TODO.md content/TO-DO.md
➜  site git:(master) ✗ hugo

                   | EN   
+------------------+-----+
  Pages            | 174  
  Paginator pages  |   0  
  Non-page files   |   0  
  Static files     |  22  
  Processed images |   0  
  Aliases          |   0  
  Sitemaps         |   1  
  Cleaned          |   0  

Total in 105 ms
```
System: Fedora 30 linux.
Let me know if you need anything more.

**Comment by bep** [comment]
I added a debug conditional in there while developing this, and matched on ... TODO so I should remember to remove it.

**Comment by cobratbq** [comment]
On Mon, 19 Aug 2019 12:14:19 -0700
Bjørn Erik Pedersen <notifications@github.com> wrote:

> I added a debug conditional in there while developing this, and
> matched on ... TODO so I should remember to remove it.
> 

Thank you! Seems like an easy fix. Please note that this is present in
both 0.56 and 0.57 releases. Regards!
