### ISSUE TITLE
Function: partialExists

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#6250]
We have `fileExists` at this time to find out if a file exists. https://gohugo.io/functions/fileexists/

Based on this I think it would be a useful feature, to have a function `partialExists` that works in a similar form, but leaves out the task of "knowing" which themes are used. The function could check in all theme (or even all module?) directories and the root layout/partials folder for a certain partial. 

The use of this (example): I have a theme component that creates Netlify header files. If a certain partial (for instance css-netlify.css) is found it will be preloaded in the `_headers` file. This function would take away the need for a boolean config variable to enable the inclusion.

**Comment by bep** [comment]
We have `templates.Exists`.

**Comment by davidsneighbour** [comment]
perfect and enough.
