### ISSUE TITLE
Generates extra "Posts" entry somehow

### ISSUE THREAD

**Issue by mhatta** [gohugoio/hugo#6251]
I'm using Hugo 0.57.2 (actually 0.57.2-1 on Debian sid) and [hugo-theme-bleak](https://github.com/Zenithar/hugo-theme-bleak) for my blog.

While it worked perfectly fine with Hugo 0.54.0, now 0.57.2 (and I also tried 0.57.0) produces extra "Posts" entry in index.html which looks like:

```html
<article class="post post">

        <div class="inner">
                <a class="post-link" href="https://myblog.org/post/"></a>
                
                <span class="post-meta">
                        <span class="post-date">20 Aug 2019</span>
                </span>
                <h2 class="post-title"><a href="https://myblog.org/post/">Pos
ts</a></h2>
                <p class="post-excerpt"></p>
                <span class="post-more"><a href="https://myblog.org/post/">Re
ad more <i class="fa fa-angle-right"></i></a></span>
        </div>
</article>

(the correct entries follow)
```
I guess some changes between 0.54.0 and 0.57.0 causes this, but can't pinpoint the culprit.  Any suggestions?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by jimmylin212** [comment]
In case you are not found the solution yet. Here is the reference:

https://discourse.gohugo.io/t/not-showing-blog-posts-after-upgraded-to-0-69/24819 
https://github.com/gohugoio/hugo/releases/tag/v0.57.0

> `.Pages` now include sections. We have added `.RegularPages` as a convenience method if you want the old behaviour

Pull your theme for update. Someone should already send PR for this.

**Comment by mhatta** [comment]
Thanks for the reference.  FYI I fixed the theme by myself some time ago https://github.com/mhatta/hugo-theme-bleak
