### ISSUE TITLE
.Truncated is false for short front matter summary

### ISSUE THREAD

**Issue by kerma** [gohugoio/hugo#6252]
Most templates use `.Truncated` to decide when to display "Read more" links. The problem is that when setting summary in the front matter the variable is false. Most likely because the summary will be shorter than the set `summaryLength`. Which probably is the case quite often.

Is there another way to easily figure out when to generate the "Read more" link?

**Comment by kerma** [comment]
So, is it expected behavior or a bug? Based on what I've seen in the templates I'd call it a bug, because the expectation of the .Truncated is that there is more to see.

**Comment by kerma** [comment]
I still think it's a bug. Please confirm, so I can take a stab at solving it.

**Comment by madmansnest** [comment]
I also have this bug.

**Comment by gleicher** [comment]
I use: {{- if or .Truncated .Params.summary }} in my template to get the behavior you describe (read more for truncated or explicit summary)

I think the current way is a feature: you get control over what has a read more or not - you can do things differently for explicit summaries and generated ones (which I have made use of).

**Comment by oefe** [comment]
@gleicher I see your point, but you can treat explicit summaries and generated ones differently even if `.Truncated` would return true for explicit summaries as well. Example: 

```
{{ if .Params.Summary }}
    markup for "read the full story...", handles pages with explicit summaries
{{ else if .Truncated }}
    markup for "read more...", handles pages with generated summaries
{{ end }}
```

The current behavior is at least confusing, and not documented at all. Neither the documentation for `.Truncated` nor the [documentation for Content Summaries](https://gohugo.io/content-management/summaries/) contain any hint of this behavior.

In fact, the [example](https://gohugo.io/content-management/summaries/#example-first-10-articles-with-summaries) in the documentation uses `{{ if .Truncated }}`, and thus fails to create a link for posts with explicit summaries.

At least the documentation should be improved to indicate and explain the actual behavior. However, I think it would be better to fix the behavior to be less surprising.
