### ISSUE TITLE
org-mode headline parse error with footnote

### ISSUE THREAD

**Issue by leenzhu** [gohugoio/hugo#6254]
```
---
title: "some title"
date: 2019-08-22T10:30:00+08:00
draft: false
tags: ["default"]
---

* Title [fn:1]

Given an array of integers, return indices of the two numbers such that they add up to a specific target.
You may assume that each input would have exactly one solution, and you may not use the same element twice.

[fn:1] [[https://leetcode.com/problems/two-sum/]]
```
With the [fn:1] given with headline, hugo reports: 
ERROR 2019/08/22 10:28:01 Could not render org: could not write output: runtime error: index out of range. Using unrendered content.

When remove the footnote, it works OK.

**Comment by leenzhu** [comment]
And here is the hugo version:
$ hugo version
Hugo Static Site Generator v0.57.2/extended windows/amd64 BuildDate: unknown

**Comment by kaushalmodi** [comment]
I'll try doing this today (I've never seen footnotes to headings). Copying @niklasfasching, who is the author of **go-org**.

**Comment by leenzhu** [comment]
It works now, thank you!
