### ISSUE TITLE
languageCode format is wrong

### ISSUE THREAD

**Issue by h0wardch3ng** [gohugoio/hugo#6264]
https://en.wikipedia.org/wiki/Language_code displays `en-US` is example for english.

In https://gohugo.io/getting-started/quick-start/#site-configuration

I think `languageCode = "en-us"` is wrong, the correct is `en-US`.

**Comment by XhmikosR** [comment]
You should submit a PR upstream https://github.com/gohugoio/hugoDocs/blob/master/content/en/getting-started/quick-start.md and close this issue.

**Comment by Las-Wonho** [comment]
I want to work on it. Can I submit for PR for this?

**Comment by ky0nch3ng** [comment]
@XhmikosR @Las-Wonho Thx, I will.

**Comment by Las-Wonho** [comment]
@ky0nch3ng Oh, "I will" mean is you submit PR?
