### ISSUE TITLE
Unused processed images should not be copied to /public

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6266]
I discovered this while tightening up the test suite in this department. One could argue that these images don't hurt anyone, and it was probably implemented like this so speed things up, but they take up disk space and should not be there.

This is a common pattern:

```
{{ $original := resources.Get "sunset.img" }}
{{ $firstStep := $original.Resize "400x" }}
{{ $thumb := $firstStep.Fill "100x100" }}
{{ $thumLarge := $firstStep.Fill "200x200" }}

<img src="{{  $thumb.RelPermalink }}" />
<img src="{{  $thumbLarge.RelPermalink }}" />
```

Currently, all the processed versions of that image (including `$firstStep`) will be copied to /public. This will be even more visible once we add image filters to the mix.

These should follow the rules of how the transformations in Hugo Pipes works (e.g. `fingerprint`, `resources.Get`):

**A processed image will only be published (copied to `/public`) if one of `.RelPermalink` or `.Permalink` is called on that processed image.**

/cc @regisphilibert

**Comment by regisphilibert** [comment]
Yes makes sense, and as the rule keeps being enforced, I think it's time to introduce https://github.com/gohugoio/hugo/issues/6267
