### ISSUE TITLE
Add a publishing method to Resources

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#6267]
For some use cases, we need transformed assets to be published even if their `.RelPermalink`/`.Permalink`are not printed within a Hugo template file. (ex. fonts, images from Mardkdown etc...).

For this reason I think we need a `.resource.Publish` method.

```
{{ with Resources.Match "/fonts/**" }}
    {{ range . }}
         {{ resources.Publish }}
     {{ end }}
{{ end }}
```

**Comment by bep** [comment]
What is wrong with:

```
{{ with Resources.Match "/fonts/**" }}
    {{ range . }}
        $foo := {{ .RelPermalink }}
     {{ end }}
{{ end }}
```

**Comment by regisphilibert** [comment]
True, I didn't realize saving it in a variable would work. Still feel a bit hackish, but it removes any urgency for this issue.
