### ISSUE TITLE
Broken template handling between 0.53 and 0.57.2

### ISSUE THREAD

**Issue by zacharysarah** [gohugoio/hugo#6277]
We're currently running https://kubernetes.io on Hugo 0.53.

We noticed behavior similar to #5615 when the [`deprecationwarning.html` shortcode](https://github.com/kubernetes/website/blob/master/layouts/shortcodes/deprecationwarning.html) renders in [deprecated versions](https://github.com/kubernetes/website/issues/16066). Consequently, we opened a [pull request](https://github.com/kubernetes/website/pull/16104#issuecomment-525655261) to upgrade Hugo from 0.53 to 0.57.2.

Upgrading to 0.57.2 fixes the #5615 behavior, but **breaks template handling for all pages across the site**.

Note that [k/website:#16104](https://github.com/kubernetes/website/pull/16104/files) changes only the site's Hugo version.

For comparison:

Production build (0.53) | Preview build (0.57.2)
---|---
[The Kubernetes API](https://v1-13.docs.kubernetes.io/docs/concepts/overview/kubernetes-api/) | [The Kubernetes API](https://deploy-preview-16104--k8s-v1-13.netlify.com/docs/concepts/overview/kubernetes-api/)

**Comment by bep** [comment]
This is related to https://github.com/gohugoio/hugo/releases/tag/v0.55.0

I'm pretty sure that I created a PR in your repo with a backward-compatible patch. I don't think that PR was merged.

In any case, the newer Hugo version is tested to work fine with the Kubernetes site.

**Comment by zacharysarah** [comment]
@bep 
> I'm pretty sure that I created a PR in your repo with a backward-compatible patch. I don't think that PR was merged.

It looks like the [backwards-compatible fixes](https://github.com/kubernetes/website/pull/13680) did merge, but you asked us to [delay upgrading](https://github.com/kubernetes/website/pull/13982) to 0.55.3.

> In any case, the newer Hugo version is tested to work fine with the Kubernetes site.

Given the extent of breakage in previews for a PR [k/website:16104](https://github.com/kubernetes/website/pull/16104/files) that only upgrades the Hugo version, this doesn't seem quite accurate.

**Comment by bep** [comment]
> that only upgrades the Hugo version, this doesn't seem quite accurate.

Before I released Hugo 0.55 I diffed the output of the Kubernetes site before/after and they came out identical. 

I just tested the Kubernetes site with the version in https://github.com/kubernetes/website/pull/13680 with the latest Hugo and it works fine. You're right that it doesn't work with the current Kubernetes master, but that must just mean that someone has somehow undone the fixes that I applied.

In any case, I don't think we can do anything about it on the Hugo side of it, so I suggest you continue this discussion on the Kubernetes issue tracker.

**Comment by zacharysarah** [comment]
> that must just mean that someone has somehow undone the fixes that I applied.

It turns out we needed to cherry-pick the commit into the `release-1.13` branch. We only merged the 0.55 backwards compatibility commit to `master` when it pointed to `release-1.14` and later.

So, you are correct and all is good now. 🙇

**Comment by bep** [comment]
Great. Now that you're getting the Hugo version up to date, you may want to consider using the new Hugo Modules to split the website and content into versionable modules, and possibly also split content per language, to possibly get something that's easier to manage.
