### ISSUE TITLE
Update chroma

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#6279]
I'm mostly interested in [this fix](https://github.com/alecthomas/chroma/commit/2b493e25561bf41593104280a2ef68e1e357770f).

I'm not sure if they'll release a new patch, or when, opening this to track the chroma update.

**Comment by Jos512** [comment]
Chroma has been updated today. The new version is [v0.6.7](https://github.com/alecthomas/chroma/releases/tag/v0.6.7).

There are a couple new lexers and improvements to existing lexers in this release. :slightly_smiling_face:
