### ISSUE TITLE
PostCSS Doesn't Work When Parent Directory Name Has Space.

### ISSUE THREAD

**Issue by joshmossas** [gohugoio/hugo#6283]
**Before I begin I want to say I'm on Windows 10 so it might be a Windows specific issue**

I was working on a site and couldn't for the life of me get PostCSS to work in Hugo Pipes. I kept getting the following error

![image](https://user-images.githubusercontent.com/31548851/63976244-88b49b00-ca76-11e9-994c-28b742859568.png)

It didn't work until I realized the error was showing the wrong directory name. It was showing "**D:\Modii\Projects\Contentful** " instead of "**D:\Modii\Projects\Contentful Starter\contentful-hugo-starter**"

My folder structure looks like this:
```
└── Projects
    └── Contentful Starter
        └── contentful-hugo-starter
            ├── assets/
            │   └── sass/
            │       └── main.scss
            ├── content/
            ├── layouts/
            ├── config.toml
            ├── postcss.config.js
            └── rest_of_my_hugo_files
```

When I removed the space in the parent directory "Contentful Starter" changing it to "contentful-starter" it began to work properly. So it seems to me Hugo just is having a problem navigating the file structure when one of the files has a space in its name.

PS: Also I did test using Hugo pipes with PostCSS and without. This issue only arises when using PostCSS from my experience.

**Comment by Heasummn** [comment]
I'm still having this issue as of 5/4/2020. I've narrowed down the issue to here: https://github.com/gohugoio/hugo/blob/6add6d77b48cf0aab8b39d7a2bddedb1aa2a52b8/resources/resource_transformers/postcss/postcss.go#L192

Specifically, Go's `exec.Command` will treat spaces in parameters as different parameters, so they must be escaped if they have spaces. 

I do not have the capabilities (right now) to get Hugo building on my machine, but I believe the simplest fix will be somehow escaping the string when passing it to `exec.Command`. 

I believe, but cannot be certain, that this line should fix this issue: 
```go
configFile = `"` + configFile + `"`
```
