### ISSUE TITLE
Resizing images doesn't work when fingerprinting

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#6284]
I have the following snippet in a partial used for a page bundle:

```html
      {{ with index (.Resources.ByType "image") 0  }}
        {{ $img := . }}
        {{ $imgSmall := .Resize "350x" | fingerprint }}
        <figure class="image">
          <img
            alt="{{ $img.Title }}"
            src="{{ $imgSmall.RelPermalink }}"
          >
        </figure>
      {{ end}}

```

I found that it's not resizing the image unless I remove `| fingerprint`.

**Comment by carlmjohnson** [comment]
```
$ hugo version
Hugo Static Site Generator v0.57.2/extended darwin/amd64 BuildDate: unknown
```

Brew installed.

**Comment by bep** [comment]
I will check; I'm pretty sure this is fixed in the latest source, but I'll add a test for it. But note that fingerprinting resized images for "cache busting" is not needed -- as their filename will change when the image changes.
