### ISSUE TITLE
Proposal: add a hook to load custom functions from html/template.FuncMap

### ISSUE THREAD

**Issue by tomVlt** [gohugoio/hugo#6285]
It would be nice to have the ability to inject custom go functions inside Hugo funcMap entrypoint.

**An example:**

Firstly somewhere alongside our hugo project dir we would have another dir containing a _custom_func.so_ file.
Then inside this file we would have any func we need. Let's go with :
```
import (
    "fmt"
)

func HelloHugoVersion(version int) string { 
     v := fmt.Sprintf("Hello, you' re running on hugo v%d", version)
     return v
}
```

Then instantly in our template :

`<p>{{ .HelloHugoVersion 0.57.2 }}</p> outputs <p>Hello, you're running on hugo v0.57.2</p>`

_Note : we could even introduce a custom namespace like .plugin.HelloHugoVersion_

**We may achieve this using go plugin system and the html.FuncMap function:**

https://golang.org/pkg/html/template/#FuncMap
https://golang.org/pkg/plugin/

Add a hook inside Hugo source code to read from the plugin all functions and inject them inside the FuncMap at runtime. 
I let you imagine the possibilities ! For example building souce plugins for almost any data source (the Gatsby way), custom js vm running alongside your template using https://github.com/robertkrimen/otto. And I'm just scratching the surface of go ecosystem.

**Caveat:**

Plugins are not supported for windows users.... Meaning it would instantly introduce some heterogeneity to Hugo ecosystem.

**Comment by bep** [comment]
Hey,

Go plugins are for Linux only and was very much considered an experimental thing -- nobody has worked on that in Go for years, so I don't think we're going to use it.

**Comment by tomVlt** [comment]
Hey bep,

They are available for linux and OSX. 
Got it I understand your concern, meanwhile I can still hook my own funcs and build from source for my own usage.

Have a nice day.
PS module feature is great. I can dynamically load my gohtml from gogs ! Thank you.

**Comment by bep** [comment]
@tomVlt note that this is in itself a good idea, and it has been discussed before, but before we do this the benefits must somehow be greater than the technical aspects/work of it all.

**Comment by tomVlt** [comment]
@bep thank you to underline this. I completely understand your first answer on it, plugin binding is just not mature enough and no idea if it will be some day. I opened this proposal way to early, I didn't check go plugin pckg status....

There might be a workaround using "os/exec" but as you mention:

> the benefits must somehow be greater than the technical aspects/work of it all.

Hope one day to see an out of the box feature like this one :)
Have a nice week.

**Comment by rafalkrupinski** [comment]
On the other hand adding experimental support for plugins in Hugo might create an incentive for someone to continue the work on plugins in Golang.
