### ISSUE TITLE
[Feature Request] hugo server should open in browser after successfully started

### ISSUE THREAD

**Issue by dineshba** [gohugoio/hugo#6293]
After successful started the server, Can we open `localhost:$PORT` in the browser.

May be with a flag

```bash
hugo server  -o
or
hugo server  --open
```

I would love to work on this feature if this is a valid requirement. Thanks

**Comment by XhmikosR** [comment]
This is still a valid request

**Comment by peaceiris** [comment]
See #5595

**Comment by philshem** [comment]
one hack is to _first_ run the command to open the browser and then _second_ launch the hugo dev server. You have to refresh the browser manually, but at least your cursor is there and you can just to cmd-R or whatever hotkey refreshes your browser.

    open http://localhost:1313/ && hugo serve -D
