### ISSUE TITLE
Aliases result in duplicate taxonomy entries

### ISSUE THREAD

**Issue by cshoredaniel** [gohugoio/hugo#6294]
If one aliases a top-level section (e.g. /post as /posts) then taxonomies (and any page traversal) reports the page twice.  So in taxonomies the count for post is doubled (because all post pages also appear as posts pages in the taxonomy).  This also affects .Data.Pages and .Sections range usage.

**Comment by bep** [comment]
>If one aliases a top-level section (e.g. /post as /posts) t

What exactly do you mean by the above?

**Comment by cshoredaniel** [comment]
For example 'hugoBasicExample' has the following the TOML frontmatter for /content/post/_index.md:
```toml
aliases = ["posts","articles","blog","showcase","docs"]
title = "Posts"
author = "Hugo Authors"
tags = ["index"]
```
This effectively aliases /post with /posts, /articles, /blog, /showcase, and /docs, however in the 'hugoBasicExample' case all of those but /posts is part of the ignoreFiles in ``config.toml`` so they have no effect on traversal by .Data.Pages, .Sections, .Data.Terms, etc.

However, /posts appears to those collections as if it were a new and different set of posts, and therefore show up in the collections as if they were a different page from the original/base page.  In the case of .Data.Terms that means they appear in .Count twice, and for .Data.Pages and .Sections that /post and /posts appear as if they were separate content sections.

**Comment by bep** [comment]
OK, thanks. Aliases do not have the side effects you describe. Which means something else is going on, and I'm guessing @onedrawingperday may know: We cannot use symbolic links to somehow alias sections, and especially in the `hugoBasicExample`, which should be ... basic. I think even having section aliases is stretching the "basic" term a little.

**Comment by onedrawingperday** [comment]
There was a change a few days ago in the repo, notably this commit: https://github.com/gohugoio/hugoBasicExample/pull/53

@cshoredaniel Are you testing with the latest above changes?

**Comment by cshoredaniel** [comment]
Ah thanks, I missed that.  Reading through the issue it resolves I guess the problem was actually the symlinks (and affects 56.3 or so too as that's what I'm still on as there was an issue with Travis' Xenial instance with 57.x that I haven't had a chance to dig into yet, in order to file a report -- looks like a libc issue though (segfault), which may have something to do with a newer build host (guessing)).

**Comment by cshoredaniel** [comment]
FYI that gave me a poke to test Travis with 57.x again and 57.2 works fine now, so I've upgraded, and there is no issue to report.
