### ISSUE TITLE
Allow disabling summarization

### ISSUE THREAD

**Issue by mitar** [gohugoio/hugo#6296]
Currently, if I want whole content to be used as the front-page summary, I have to add `<!--more-->` at the end of the post for whole content to be used without any "summarization" (text converted to plain text). It would be great if there would be a way to disable this content conversion and that I could configure that only a manual split should happen and only if `<!--more-->` is provided and in all cases that no special conversion should happen.

**Comment by divinerites** [comment]
May be you can test your inner and decide to use either summary or content ?

Make summary being content seems strange ...

**Comment by mitar** [comment]
> May be you can test your inner and decide to use either summary or content ?

Sorry, but I do not understand what you are asking here.

> Making summary behave like content seems a bit strange ...

I mean, summary is initial content, and then the rest of the content follows. This is why you have [manual summary splitting](https://gohugo.io/content-management/summaries/#manual-summary-splitting). I think this is a pretty common thing.

What I am asking for is that if there is no `<!--more-->` tag present, I would like [the automatic summary splitting](https://gohugo.io/content-management/summaries/#automatic-summary-splitting) to not come into the effect, but would like full content to be used as a summary.

Currently I have the following in my template for the list of posts:

            {{ .Summary }}
            {{ if .Truncated }}
            <p class="read_more_container">
                <a href="{{ .Params.href | default .Permalink }}"
                   class="read_more">
                    Keep reading
                </a>
            </p>
            {{ end}}

I set `summaryLength = 1000000000000000`, but it looks like summary still gets passes through `plainify` automatically. But only if no `<!--more-->` is present. So I would like to disable this automatic conversion/splitting altogether?

**Comment by divinerites** [comment]
I mean : use and test if your {{. Inner }} contains "" and then use either {{ .Summary }} or {{ .Content }}

**Comment by mitar** [comment]
I see. I didn't know I could access raw content or that I could check if it contains `<!--more-->` and that that will not be extracted out. I tried to see how to get this to work but could not make it. Could you write the syntax how to implement such check, please?

**Comment by patdavid** [comment]
Can't you just switch based on the presence of `.Truncated`?

```
{{ if .Truncated }}
    {{ .Summary }}
{{ else }}
    {{ .Content }}
{{ end }}
```

**Comment by mitar** [comment]
No, `.Truncated` does not apply here at all. The problem is not about that.

So if I have `content <!-- more --> content` then `.Truncated` is set. But if I have just `content <!-- more -->` or just `content` then `.Truncated` is not set. I think this is expected behavior.

What is not expected is that if I have `content`, then `plainify` happens, but if I have `content <!-- more -->` then `plainify` does not happen.

**Comment by mitar** [comment]
Existing workaround do not address the issue really.

**Comment by mitar** [comment]
Existing workaround do not address the issue really.

**Comment by mitar** [comment]
Still relevant.

**Comment by mitar** [comment]
Still relevant.

**Comment by mitar** [comment]
Still relevant.

**Comment by jmooring** [comment]
Unless I'm missing something, this addresses the use case as described:

```
{{ if findRE `<!--more-->` .RawContent }}
  {{ .Summary }}
{{ else }}
  {{ .Content }}
{{ end }}
```

We are not adding a configuration option to provide this behavior.

**Comment by mitar** [comment]
Thank you. This indeed works. No need then for a setting.
