### ISSUE TITLE
[0.57.2] .Site.Home.Pages does not include .Site.Home.Sections

### ISSUE THREAD

**Issue by cshoredaniel** [gohugoio/hugo#6297]
It looks like #6238 resulted in inconsistency for .Site.Home.Pages only (.Site.Pages is fine), in which .Site.Home.Pages does not include .Site.Home.Sections.

**Comment by bep** [comment]
#6238 resulted in lots of shouting from people around the interweb -- so I had to temporarily revert that behaviour _for the home page only_. This will be fixed in Hugo 0.58. I have another issue to track that somewhere.
