### ISSUE TITLE
Make png to jpg converter (flatten to specified background color)

### ISSUE THREAD

**Issue by ericselin** [gohugoio/hugo#6298]
I think this would be a killer feature. Serving .png images is less than ideal compared to .jpg. But keeping the master images as large .png files is a must if you want transparency. Hence something like this would be preferred:

```
{{ $png := .Resources.GetMatch "image.png" }}
{{ $jpg := $png.toJPG "#FFFFFF" }}
```

or using filters as in #6255:

```
{{ $jpg := $png.Filter (images.Flatten "#FFFFFF") }}
```

I hope you get my point. We have an eCom site and our product images are large .png files with a transparent background. Right now we flatten these in a separate step into .jpg files with two different backgrounds depending on what the background on the underlying element is. But I think this kind of processing could (and should!) be included by default in hugo.

**Comment by roz3x** [comment]
hey ! the code base is (very ) huge , can you point the specific  file,  where this feature  could be added directly . like template parser or similar file .

**Comment by bep** [comment]
@roz3x we need to agree on the API first. I don't mind adding this "somehow", but we need to consider where/how.

**Comment by roz3x** [comment]
is this something you wanna fix right now , or you want to add in future updates !?

**Comment by bep** [comment]
I don't mind having it fixed now, but we need to know how before doing it. `$img.ToJPG` does not look "right" to me, but this is not something I plan to spend time on right now.

**Comment by jansorg** [comment]
Speaking for my needs, something like this would feel "okay" to me:

```
{{ $png := ... }}
{{ $jpg := $png.Convert("jpeg bg=#ffffff") }}
// or: {{  $jpg := $png.Convert("jpeg #ffffff") }}
// or: {{  $jpg := $png.Convert("jpeg", (dict "bg" "#ffffff")) }}
{{ $webp := $png.Convert("webp") }}
```

My thinking is that the required parameters depend on the target image format. Required parameters have to be passed to `Convert`. If missing, `Convert` will raise an error.
For example, creating a JPG from an image with transparent background needs the background color. A solution with a flatten filter might be harder to get because converting a png to jpeg without flattening before will have to assume a default background color.

A generic `Convert` could be used for all sorts of image formats, i.e. we wouldn't need functions for each format, e.g. `$img.ToPng`, `$img.ToJpeg`, `$img.ToWebP`, `$img.ToJpeg2000`, etc.

**Comment by gnalck** [comment]
This would be useful for our  use-case too. Is there any reason not to have the [specification of image quality](https://gohugo.io/content-management/image-processing/#image-processing-options) (e.g., "q75") be sufficient for automatic conversion of a `png` to `jpg`? Right now the quality indicator is ignored for `png`, but it seems that once this API exists it can now be respected via conversion to jpg.

**Comment by jansorg** [comment]
@gnalck Quality is most probably not enough. There's a default quality setting in the config and it's (probably) not intuitive to output a jpeg if it's defined on the call and a png if the default quality is used. And there might be other formats in the future which support a quality setting.

I spend some time and created a wip PR, changes are at https://github.com/jansorg/hugo/commit/0a309db00fa681f3df5da3de75811f016a1383d9 for now.

This allows to do `$jpg := $png.Resize "400x jpeg q70"` and `$jpg2 := $jpg.Resize "200x200"`, for example.
It's in an early stage, but seems to work well for me locally. It's not yet supporting the flattening background color.

I couldn't find a webp encoder in pure go. https://github.com/chai2010/webp contains a set of C files and https://github.com/nickalie/go-webpbin seems to link to a C library. Not sure if one of them would be okay for Hugo as a dependeny.
There's not Jpeg2000 encoder I could find.

**Comment by bep** [comment]
C libraries is not a route we want to go. Or: We do it only if we really, really need the particular library (e.g. libsass). I'm a little surprised that no company have stepped up and created native encoders for stuff like WebP and progressive jpegs.

**Comment by bep** [comment]
@jansorg we have the converter in place. What we need to close this particular issue is a way to set the background color. Webp is not in the scope of this particular issue. And I would suggest you take any discussions re. webp in another issue.
