### ISSUE TITLE
Changes to source files are not reflected in the browser from v0.55.6 on

### ISSUE THREAD

**Issue by christophlieck** [gohugoio/hugo#6308]
Please see this thread https://discourse.gohugo.io/t/live-reload-broken/20584 for all relevant details, in particular this section https://discourse.gohugo.io/t/live-reload-broken/20584/6

**Comment by bep** [comment]
I assume it's this commit: 95ce2a40e7 ... 

I can see how the above commit would block (wait) for the previous build to fail and make it "feel" like the live reload isn't working. I think I've experienced something similar myself.

The thing is:

* If I have a site that takes 10 seconds to build.
* I make one change, rebuild starts.
* Then, after, 2 seconds, I make another change, a new rebuild starts.

In fast render mode the above should not be something that should happen very often.

@christophlieck can you somehow confirm my theory above. I.e. try to:

* Start server
* With the browser open one some page, do 1 (and only 1) change that should change that page, then wait.

Before 95ce2a40e7 we would just trigger these rebuilds in parallell, which made them feel snappier to the end user, but you had some weird and undefined side effects.

I think we need to do 2 things:

1. Maybe add a log statement (or delay the one we have) until we actually start rebuilding.
2. Consider cancelling the rendering step (which is the time consuming part, and probably the only one we can skip) if we detect a new change while rebuilding.

**Comment by christophlieck** [comment]
@bep Sorry, can't confirm. Even after minutes nothing happens. And, what might be of particular interest, even manually reloading the browser doesn't make the changes appear.

**Comment by christophlieck** [comment]
And, not sure this is relevant, Hugo reports success: "Total in 21 ms" but it doesn't work.

**Comment by christophlieck** [comment]
Apologies, but I'm afraid I've to update this issue again: After having returned to productive work with 0.55.5 it turned out that it is also unstable once updating the browser once not.

To fix this I rolled back to the last version before the commit quoted above, e. g. v0.54.0-B1A82C61 darwin/amd64 BuildDate: 2019-02-01T09:40:48Z which seems to work fine so far.

I therefore now second you suspecting commit 95ce2a4.

**Comment by christophlieck** [comment]
I report back that v0.58.1 fixed this issue for me. I think commit 901077c0 did the trick.
