### ISSUE TITLE
Empty content with "concat | fingerprint"

### ISSUE THREAD

**Issue by brunoamaral** [gohugoio/hugo#6309]
I was using the code below and it worked until Hugo 0.57.x.

```
{{- $print := resources.Get "css/print.css" | resources.Fingerprint -}}
<link href="{{- $print.Permalink -}}" media="print" rel="stylesheet" />

{{ $fontawesome := resources.Get "fontawesome-free-5.9.0-web/scss/fontawesome.scss" | resources.ToCSS (dict "enableSourceMap" false "outputStyle" "compressed") }}
{{ $brands := resources.Get "fontawesome-free-5.9.0-web/scss/brands.scss" | resources.ToCSS (dict "enableSourceMap" false "outputStyle" "compressed") }}
{{ $regular := resources.Get "fontawesome-free-5.9.0-web/scss/regular.scss" | resources.ToCSS (dict "enableSourceMap" false "outputStyle" "compressed") }}

{{- $bootstrap := resources.Get "css/bootstrap.min.css" -}}
{{- $nowUi := resources.Get "scss/now-ui-kit.scss" | resources.ToCSS (dict "enableSourceMap" false "outputStyle" "compressed") -}}

{{- $style := slice $bootstrap $nowUi $montserrat $fontawesome $brands $regular | resources.Concat "css/style.css" | resources.Fingerprint -}}
<link href="{{- $style.Permalink -}}" rel="stylesheet">
```

In 0.58.0, it just returns an empty css file on `hugo server` and build.

**Comment by bep** [comment]
I see many CSS files constructed in the above -- all of them empty?

**Comment by kascme** [comment]
I have a similar problem, but with JavaScript. The generated file is empty if I use ` ... | resources.Fingerprint`. Without fingerprinting I get the expected output. However, I have not fully invested the issue as it does not happen with all files in my case

**Comment by brunoamaral** [comment]
Just tried the whole list of files and they all work isolated. The main style.css works only if I remove .Fingerprint from the variable's settings.

**Comment by bep** [comment]
I'm sorry for the breakage, but I cannot reproduce this. I have plenty of tests in this area, including many working sites that still works on Hugo 0.58.

**Comment by bep** [comment]
OK, nevermind, I can reproduce it. A stupid workaround would be to minify it before you fingerprint it.

**Comment by bep** [comment]
Just so people don't read this and think that Hugo's test suite is full of holes:

This did work before this commit:

```
{{ $combined := slice $a $b $c | resources.Concat "bundle/concat.txt" | minify | fingerprint }}
```

But due to a bug in the `io.Reader` produced by `concat` (it could not be reset), this produced empty files:

```
{{ $combined := slice $a $b $c | resources.Concat "bundle/concat.txt" | fingerprint }}
```

I had tests and sites covering the first variant, but not the latter.
