### ISSUE TITLE
include_relative

### ISSUE THREAD

**Issue by cup** [gohugoio/hugo#6319]
Currently I am using Jekyll. In some folder I have these files:

~~~
readme.md
app.php
~~~

then I have this markup:

~~~
one two three

{% include_relative app.php %}

four five six
~~~

I would like to start using Hugo, but I cannot seem to duplicate this workflow.
I saw this page:

https://gohugo.io/templates/partials

but it looks like the included files must be in a certain folder, and not
alongside the markup as I wish to have.

**Comment by bep** [comment]
Look for shortcodes.

Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by cup** [comment]
@bep thanks for the comment

however can you elaborate? I am new to hugo so just saying "look for shortcodes" isnt really helpful.

**Comment by cup** [comment]
Since @bep answer was pretty awful, here is an actual answer. First download
this:

https://github.com/gohugoio/hugo/blob/master/docs/layouts/shortcodes/readfile.html

and put it as:

~~~
layouts/shortcodes/readfile.html
~~~

might need to create `shortcodes` folder. Then add this to your markup:

~~~
{{% readfile highlight="php" file="content/autumn/app.php" %}}
~~~

if you did these steps in reverse, might need to resave the markup for it to
load the change.
