### ISSUE TITLE
Azure support breaks Solaris compatibility

### ISSUE THREAD

**Issue by fazalmajid** [gohugoio/hugo#6324]
```
local64 ~/go>go get github.com/gohugoio/hugo
# github.com/Azure/azure-storage-blob-go/azblob
src/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:144:7: undefined: mmf
src/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:146:12: undefined: newMMF
src/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:275:13: undefined: newMMF
```

I have zero interest in Azure, and this is breaking my SmartOS hosted environment. Is there a way to disable Azure support in Hugo at compile time?

**Comment by bep** [comment]
>Is there a way to disable Azure support in Hugo at compile time?

Currently, no. But we should at least make sure to turn it off for unsupported platforms.

You're the first Hugo user on Solaris I've heard of. I thought we had a bug in file watching on Solaris (in `fsnotify`)

/cc @vangent 

https://github.com/Azure/azure-storage-blob-go/blob/8a1deeeabe0a24f918d29630ede0da2a1c8f3b2f/azblob/zc_mmf_unix.go#L12

**Comment by uniapi** [comment]
He is **not** the only Solaris user as there are plenty of us!

The same issue:
```
# github.com/Azure/azure-storage-blob-go/azblob
../../Go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/highlevel.go:144:7: undefined: mmf
../../Go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/highlevel.go:146:12: undefined: newMMF
../../Go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/highlevel.go:275:13: undefined: newMMF
```
Still not fixed?

**Comment by jmooring** [comment]
https://github.com/Azure/azure-storage-blob-go/pull/117 was merged on 23 June 2020. Can anyone confirm that _this_ issue is resolved?

**Comment by fazalmajid** [comment]
I can confirm I can build Hugo@latest on my SmartOS (Illumos) box, using Go 1.20.6
