### ISSUE TITLE
Translations does not work in ExecuteAsTemplate

### ISSUE THREAD

**Issue by zygimantas-skinkys** [gohugoio/hugo#6331]
i18n translations does not work in assets.

This is how I process my JS file:

```{{ $scriptJS := resources.Get "js/script.js" | resources.ExecuteAsTemplate (printf "%s/js/script.js" .Lang ) . | resources.Minify | fingerprint }}```

I’m using translations in an usual way:

```{{T "translations_key"}}```

I get my script.js file for every language but only with English translations(English being main language of the site).

Hugo version: 
```Hugo Static Site Generator v0.57.0-9B00E647/extended linux/amd64 BuildDate: 2019-08-14T08:12:12Z```

OS: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

---

Related discussions:
[https://discourse.gohugo.io/t/is-it-possible-to-use-translations-in-assets/20726](https://discourse.gohugo.io/t/is-it-possible-to-use-translations-in-assets/20726)
[https://discourse.gohugo.io/t/style-css-in-multilingual-mode/20754/2](https://discourse.gohugo.io/t/style-css-in-multilingual-mode/20754/2)

**Comment by alex-shpak** [comment]
I can confirm for
`Hugo Static Site Generator v0.59.0/extended darwin/amd64 BuildDate: unknown`

Outside of `ExecuteAsTemplate` `i18n` function works as expected, inside it returns default lang translation.
For now as workaround I use `.Site.Params`, and lang specific param, e.g. `[languages.en.params]`.
