### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by Tom007Cheung** [gohugoio/hugo#6333]
`hugo server -D`
terminal output:

                   | ZH-CN  
+------------------+-------+
  Pages            |    51  
  Paginator pages  |     0  
  Non-page files   |     0  
  Static files     |    41  
  Processed images |     0  
  Aliases          |    18  
  Sitemaps         |     1  
  Cleaned          |     0  

Total in 171 ms
Watching for changes in /home/bunny/Desktop/blog/{archetypes,content,data,layouts,static,themes}
Watching for config changes in /home/bunny/Desktop/blog/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/BunnyBlog/blog.git/ (bind address 127.0.0.1)
Press Ctrl+C to stop
**localhost:1313/:**
404 page not found

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by Tom007Cheung** [comment]
> Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see [Hugo Documentation](http://gohugo.io/overview/introduction/).

Sorry, thank you!
