### ISSUE TITLE
Hugo extended not available as snap

### ISSUE THREAD

**Issue by andrewebdev** [gohugoio/hugo#6337]
Hugo extended isn't in the snap version. Is there any reason this isn't included by default?
If it's important that they are separate app, then maybe `hugo-extended` can be installed alongside `hugo` within the snap package?

**Comment by davidsneighbour** [comment]
Not a bug. Use `--channel=extended` to install extended. To switch from already installed Hugo to Hugo Extended run `snap refresh hugo --channel=extended`.

**Comment by andrewebdev** [comment]
My apologies, didn't realize you had it on a different channel!
