### ISSUE TITLE
Docs - Quick Start - Add a Theme section not displaying properly

### ISSUE THREAD

**Issue by rishiip** [gohugoio/hugo#6341]
While visiting following url, `Add a Theme` section is not displaying properly.

https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme

<img width="1280" alt="Screenshot 2019-09-15 15 56 33" src="https://user-images.githubusercontent.com/7964257/64920188-034d1c80-d7d2-11e9-8396-8673ca49ea65.png">

@bep I am able to pick it up. Please let me know.

**Comment by peaceiris** [comment]
Please, post this at https://github.com/gohugoio/gohugoioTheme

**Comment by rishiip** [comment]
@peaceiris Done - https://github.com/gohugoio/gohugoioTheme/issues/137

**Comment by peaceiris** [comment]
You can close this.
