### ISSUE TITLE
No layout

### ISSUE THREAD

**Issue by vincewenminli** [gohugoio/hugo#6342]
I have installed hugo correctly (I'm sure).
But it warned as following: 
**found no layout file for "HTML" for "home"**

Whatever theme I use, except theme "hyde".

Even thought I forked an published website source code using hugo (https://www.servicemesher.com/ runing okay). It gave the same warning.

The hugo version is : 0.58.1

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
