### ISSUE TITLE
Problems with Hugo Theme in html format

### ISSUE THREAD

**Issue by OleksiyAnokhin** [gohugoio/hugo#6343]
HI, I experience a strange problem with my web-site. 
A blackburn theme worked perfectly and still works locally. But trying to organize the content [properly](https://stackoverflow.com/questions/57914292/organizing-blogdown-hugo-structure-properly-for-automatic-update-of-content), I deleted the Public folder several times.
As a result, now my website works only locally. 
![Capture1](https://user-images.githubusercontent.com/24446791/64997279-37960b00-d8ae-11e9-8cb5-1fc1c10eabd6.PNG)
But when I try to deploy it, HTML looks very dry
![Capture2](https://user-images.githubusercontent.com/24446791/64997372-8643a500-d8ae-11e9-91d8-e47c3788197a.PNG)

I did not make any changes, just deleted Public folder several times. But I suspect the wrong content management here. 
Building sites â€¦ WARN 2019/09/16 18:12:41 found no layout file for "HTML" for "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/09/16 18:12:41 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/09/16 18:12:41 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/09/16 18:12:41 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/09/16 18:12:41 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/09/16 18:12:41 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/09/16 18:12:41 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/09/16 18:12:41 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

**Comment by peaceiris** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting and ask the theme authors. Also see [Hugo Documentation](https://gohugo.io/getting-started/)
