### ISSUE TITLE
MathJax issue in hugo

### ISSUE THREAD

**Issue by dawnarc** [gohugoio/hugo#6344]
If using brackets in title of article, and MathJax was enabled, 
```
+++
title= "[Math]Finding the shortest distance between two lines in 3D"
date= "2019-09-16T16:46:02+08:00"
mathjax= ["ture"]
+++
```
then characters in brackets would be  zoomed in, as shown in following pic:
![MathJax-issue-01](https://user-images.githubusercontent.com/3351764/65023293-0c222780-d965-11e9-9186-c53756744304.png)

but it works fine without brackets in title:
```
+++
title= "(Math)Finding the shortest distance between two lines in 3D"
date= "2019-09-16T16:46:02+08:00"
mathjax= ["ture"]
+++
```
![MathJax-issue-02](https://user-images.githubusercontent.com/3351764/65023454-6f13be80-d965-11e9-9c82-4baf01817f2e.png)

**Comment by peaceiris** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting and ask the theme authors. Also see [Hugo Documentation](https://gohugo.io/getting-started/)

**Comment by dawnarc** [comment]
> Please use https://discourse.gohugo.io/ for questions/troubleshooting and ask the theme authors. Also see [Hugo Documentation](https://gohugo.io/getting-started/)
Thanks @peaceiris , I have asked for help on https://discourse.gohugo.io/, and I have got a solution that replacing MathJax with KaTex, KaTex worked.
https://discourse.gohugo.io/t/mathjax-issue-in-hugo/20837
