### ISSUE TITLE
Hugo New resources adds to root resource dir rather than content dir

### ISSUE THREAD

**Issue by randallmlough** [gohugoio/hugo#6347]
If I have content of type "resources" and I then try to create a new piece of content for that type (ie. `hugo new resources/foo.md`) this content will be added to the root resources dir, not the `content/resources` dir. 

I'm not sure if this was an intentional design decision, but in my mind the main `resources` dir should only be hugo generated content (resized images, bundled js, etc.) and not be included in the `new` command.

To work around this I can do `hugo new content/resources/foo.md` but that doesnt seem ideal. Additionally, an archetype of `resources` doesn't appear to work at all.

**Comment by floxo115** [comment]
Hi! I am new to all of this but I looked into the code and played around a little bit with the CLI and found out that hugo will look if there is a folder with the same name as your wished content type.

So if you have a folder "hello/" and you use "hugo new hello/somecontent.md" the new file will be created as "PATHTOYOURSITE/hello/somecontent.md" and not under the content folder.
