### ISSUE TITLE
RSS template in theme is not overriding __internal/rss.xml

### ISSUE THREAD

**Issue by stou** [gohugoio/hugo#635]
If i understand the docs correctly, putting a template in:

```
/themes/THEME/layouts/_default/rss.xml
```

should override the default in

```
__internal/rss.xml
```

However, the only way I can get this to work is by putting the rss template in the main site, i.e.,

```
/layouts/rss.xml
```

Maybe I am missing something or did I find a bug?

Maybe this is related to #532 since I am using:

```
permalinks:
  post: /:year/:month/:slug/
```

**Comment by mrwullah** [comment]
I have an issue with my .xml file as well. It's a bit different, I can't see the RSS links working www.wasim.blog/index.xml and I didn't change the template "Cactus Plus" files.
