### ISSUE TITLE
Change default sort order for .PrevInSection and .NextInSection

### ISSUE THREAD

**Issue by fractionalJoe** [gohugoio/hugo#6350]
I would like to have the default order set by the order used in the sections list page. Namely, I sort by PublishDate but when using .PrevInSection or .NextInSession the pages are sorted by Date instead. This is disjointed for my users. Is there a work around?

**Comment by felicianotech** [comment]
This would be a question to ask in the forum and not a GitHub Issue.

https://discourse.gohugo.io/

**Comment by fractionalJoe** [comment]
According to the documentation, it is not currently possible. I'm not asking how to do this. I'm stating that the framework currently lacks this capability and I'm providing a use case for why I need it. 

Per https://gohugo.io/variables/page/
> ### .NextInSection
> Pointer to the next regular page within the same section. **Pages are sorted by Hugo’s [default sort](https://gohugo.io/templates/lists#default-weight-date-linktitle-filepath).** Example: `{{if .NextInSection}}{{.NextInSection.Permalink}}{{end}}`.

> ### .PrevInSection
> Pointer to the previous regular page within the same section. **Pages are sorted by Hugo’s [default sort](https://gohugo.io/templates/lists#default-weight-date-linktitle-filepath).** Example: `{{if .PrevInSection}}{{.PrevInSection.Permalink}}{{end}}`.

Per https://gohugo.io/templates/lists#default-weight-date-linktitle-filepath
> ### Default: Weight > Date > LinkTitle > FilePath

**Comment by felicianotech** [comment]
> I'm not asking how to do this.

You should. I suggested the forum so that you can ask and then I can show you. The forum has much more visibility for showing techniques than GitHub Issues has for new users.

**Comment by felicianotech** [comment]
I ended up just doing a write-up for it now. You can find it on the [forum](https://discourse.gohugo.io/t/custom-sort-hugo-single-pages/21442?u=felicianotech).

**Comment by fractionalJoe** [comment]
Thanks for the work around! That helps. Is it possible to move forward with the enhancement request to make it possible to change the default sort order for .PrevInSection or .NextInSession?
