### ISSUE TITLE
How does Hugo specify the same head for all HTML

### ISSUE THREAD

**Issue by geomonlin** [gohugoio/hugo#6352]
How does Hugo specify the same head for all HTML。
e.g:<meta http-equiv="Cache-Control" content="max-age=7200" />
<meta http-equiv="Expires" content="Mon, 20 Jul 2013 23:00:00 GMT" />

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
