### ISSUE TITLE
Automatic Summary splitting sanitizing HTML?

### ISSUE THREAD

**Issue by patdavid** [gohugoio/hugo#6353]
I'd like to be able to push the results of automatic summaries and keep the HTML formatting.

For instance, If the beginning of a post contains markdown like:
```
## First header

This is a first sentence _for example_.
```

It should render like this:
```
<h2>First header</h2>
<p>
This is a first sentence <em>for example</em>.
</p>
```

Automatic summary seems to strip all tags from the text?  Manually adding  is supposed to keep them, but it might be nice to get the summary pre-sanitizing?  We could always pass it through `plainify` if needed.

Or am I missing something (a very real possibility)?

**Comment by bmackinney** [comment]
@patdavid welcome! please use Discourse for support - I think your question was recently asked there at https://discourse.gohugo.io/t/hugo-post-summary/20698

**Comment by patdavid** [comment]
Thanks, I've [posted over there](https://discourse.gohugo.io/t/hugo-post-summary/20698/5?u=patdavid).
