### ISSUE TITLE
allow hl_lines in code fences

### ISSUE THREAD

**Issue by frank06** [gohugoio/hugo#6355]
It should be possible to make up some syntax, e.g. ` ```js/hl_lines=8-13`  in the rendering hook in Hugo to enable options like `hl_lines` in code fences.

Look at this before: https://github.com/gohugoio/hugo/issues/5963

**Comment by colevscode** [comment]
This would be nice, along with the option to enable / disable linenos

**Comment by bep** [comment]
I haven't tested it, but on paper at least this should be supported in Goldmark -- coming in Hugo next.

**Comment by frank06** [comment]
🙌
