### ISSUE TITLE
"range where" does not work on maps of maps

### ISSUE THREAD

**Issue by nikclayton** [gohugoio/hugo#6358]
Hugo version is:  Hugo Static Site Generator v0.58.2-253E5FDC windows/amd64 BuildDate: 2019-09-13T08:06:10Z

This is either a bug report or a feature request, depending on your point of view.

Using `range where` syntax doesn't work on maps of maps, like the content from `.Site.Data.foo`.

This is, technically, OK, since it's only documented as working on arrays.

However, it's confusing, since `range` doesn't normally care what it's ranging over. And if you try and use `range where` with a map Hugo doesn't emit an error warning that what you're trying to do doesn't work.

So, either:

Feature request: `range where` should support maps, or

Bug report: Using `range where` with a map is not supported, but does not produce an error or warning

There's more context in https://discourse.gohugo.io/t/range-where-not-working-simple-if-does/20854

**Comment by jzeneto** [comment]
I have the same problem (iterating over Staticman comments and trying to filter only parent comments)
