### ISSUE TITLE
Alias page template parameter missing for home page

### ISSUE THREAD

**Issue by raoulb** [gohugoio/hugo#6359]
I tried to customize the aliases page template as described [here](https://gohugo.io/content-management/urls/#customize). I can access the `.Permalink` but not the `.Page` variable
which is `nil`.

For testing purpose, my template is:
```
<!DOCTYPE html>
<html>
  <head>
    <title>{{ .Permalink }}</title>
    <meta http-equiv="refresh" content="0; url={{ .Permalink }}"/>
  </head>
  <body>
    <pre>
      |{{ . }}|
      |{{ .Permalink }}|
      |{{ .Page }}|
    </pre>
    </body>
</html>
```
and renders as:
```
<!DOCTYPE html>
<html>
  <head>
    <title>http://localhost:1313/de</title>
    <meta http-equiv="refresh" content="0; url=http://localhost:1313/de"/>
  </head>
  <body>
    <pre>
      |{http://localhost:1313/de &lt;nil&gt;}|
      |http://localhost:1313/de|
      ||
    </pre>
    </body>
</html>
```

The failure is only for the entry page. (I have set `DefaultContentLanguageInSubdir = true` which gives me the `/` -> `/de` redirect.)

I think the issue comes from the function [renderMainLanguageRedirect](https://github.com/gohugoio/hugo/blob/6b76841b052b97625b8995f326d758b89f5c2349/hugolib/site_render.go#L345) which calles [publishDestAlias](https://github.com/gohugoio/hugo/blob/6b76841b052b97625b8995f326d758b89f5c2349/hugolib/site_render.go#L345) with last parameter being `nil`.

**Comment by raoulb** [comment]
The `hugo version` is:
```
Hugo Static Site Generator v0.57.2/extended linux/amd64 BuildDate: 2019-08-18T05:29:32Z
```

**Comment by raoulb** [comment]
This still behaves as described above with
```
Hugo Static Site Generator v0.65.3/extended
```

**Comment by razonyang** [comment]
I have the same problem, any updates?

**Comment by raoulb** [comment]
Still the same as far as I see.

Here is my [minimal example site](https://github.com/raoulb/hugo_issue_aliases).

Run the Hugo development server and:
```
curl http://localhost:1313/
```
yields
```
<!DOCTYPE html>
<html>
  <head>
    <title>http://localhost:1313/de/</title>
    <meta http-equiv="refresh" content="0; url=http://localhost:1313/de/"/>
  </head>
  <body>
    <pre>
      |{http://localhost:1313/de/ &lt;nil&gt;}|
      |http://localhost:1313/de/|
      ||
    </pre>
    </body>
</html>
```
