### ISSUE TITLE
"noopener" for links affected by `hrefTargetBlank` — Hugo or Blackfriday?

### ISSUE THREAD

**Issue by jakejarvis** [gohugoio/hugo#6363]
Building on #6356 which was just merged in 34dc06b032741abac342d7a2a77510ded9b72ae8...

If we wanted to add `rel=noopener` to all links affected by `hrefTargetBlank` would this be a Hugo code change? Or is this a request for Blackfriday since it involves Markdown compiling? (I think they might have already fixed this in v2 anyways but I'm not sure about your current feelings on upgrading [related: #3949]).

Great explanation on why this is so important: https://mathiasbynens.github.io/rel-noopener/ I've held off on enabling `hrefTargetBlank` for specifically this reason, but I'd love to do so. :(

Just wanted to ask before looking into making a PR. Thanks!

**Comment by orf** [comment]
Hah, weird. I have just made this MR to BlackFriday: https://github.com/russross/blackfriday/pull/570

I think it's a black friday change rather than a Hugo one.

**Comment by jakejarvis** [comment]
@orf Literally the exact same time, that's hilarious!

Agreed about the second part, didn't think about backporting over there. I'll close this for now and keep an eye on the progress on your issue, and reopen if we need any changes here. :)
