### ISSUE TITLE
replaceRE no longer working in shortcodes

### ISSUE THREAD

**Issue by ogobrecht** [gohugoio/hugo#6366]
I implemented a shortcode for a TOC with fixes the wrong header levels of the original TOC based on one of the last discussion entires on [this issue](https://github.com/gohugoio/hugo/issues/1778#issuecomment-522222658).

shortcode toc.html:

```
{{ with .Get 0 }}<h2>{{ . }}</h2>{{ end }}
{{ .Page.TableOfContents | replaceRE `<ul>\s*<li>\s*<ul>` `<ul>` | replaceRE `</ul>\s*</li>\s*</ul>` `</ul>` | safeHTML }}
```

You can use it in this way:

```
{{< toc "yourOptionalLevelTwoTocHeader" >}}
```

This was working with Hugo v0.53 but is no longer working in Hugo v0.58.3 - could be that it was broken earlier - v0.58.3 is my current version when I was detecting the issue.

Thanks for your help and the great Hugo project.

**Comment by bep** [comment]
At one point we changed it so when you do `{{%` we evaluate/render the shortcode before we send it to Blackfriday (the markdown parser/renderer). One of the reasons to do so was to get shortcodes to be part of the ToC. But this early eval means that you cannot do what you do.

If you really want to do what you do, you need to either use `{{<` or set a version marker in your shortcode template (see docs). Ask further questions here: https://discourse.gohugo.io/

**Comment by ogobrecht** [comment]
Hi Bjørn Erik,

I use your mentioned call `{{<` (I also tested `{{%`), but the replaceRE does not work - I get in both use cases the unchanged ToC with the header level issue - see HTML comments which parts should be removed by replaceRE:

```html
<h2>Table of Contents</h2>
<nav id="TableOfContents">
<ul><!--should be removed-->
<li><!--should be removed-->
<ul>
<li><a href="#header-1">Header 1</a></li>
<li><a href="#header-2">Header 2</a></li>
<li><a href="#header-3">Header 3</a></li>
</ul></li><!--should be removed-->
</ul>
</nav>
```

This means the evaluation time does not matter and the ToC is rendered as usual by Blackfriday with the header level issue. `replaceRE` seems to do nothing in the context of a shortcode - no idea why.

**Please verify it by implementing the shortcode**

shortcode toc.html:

```
{{ with .Get 0 }}<h2>{{ . }}</h2>{{ end }}
{{ .Page.TableOfContents | replaceRE `<ul>\s*<li>\s*<ul>` `<ul>` | replaceRE `</ul>\s*</li>\s*</ul>` `</ul>` | safeHTML }}
```

test.md:

```md
---
title: Test Hugo shortcode with replaceRE
publishdate: 2019-09-22
---

{{< toc "Table of Contents" >}}

## Header 1
## Header 2
## Header 3
```

Sorry to bother you with this issue. 

Kind regards
Ottmar

**Comment by bep** [comment]
See my last comment about the discussion forum.

**Comment by ogobrecht** [comment]
Hi Bjørn Erik,

thank you for your help. I found a workaround by moving the regex replacements to my layout file single.html - maybe this is useful for others too:

```
<div class="item-content" itemprop="articleBody">
{{ .Content | replaceRE `<nav id="TableOfContents">\s*<ul>\s*<li>\s*<ul>` `<nav id="TableOfContents"><ul>` | replaceRE `</ul>\s*</li>\s*</ul>\s*</nav>` `</ul></nav>` | safeHTML }}
</div>{{ "<!--articleBody-end-->" | safeHTML }}
```

I will wait for the Blackfriday v2 which you mentioned in this new entry: https://gohugo.io/news/lets-celebrate-hugos-5th-birthday/

Hopefully we are then able to use an improved ToC and I can remove my workaround.

Thanks again - seems you were right with the evaluation time. Shame on me...

Kind regards
Ottmar
