### ISSUE TITLE
Bug : smartypantsQuotesNBSP for French Guillemets (« ») is not working

### ISSUE THREAD

**Issue by loup-brun** [gohugoio/hugo#6368]
## Bug description

**Expected**: the [Blackfriday `smartypantsQuotesNBSP` option](https://gohugo.io/content-management/formats/#blackfriday-options) will render non-breaking spaces inside passages wrapped in french guillemets (`«` and `»`).

**Actual result**: non-breaking spaces are never inserted by Hugo.

## Examples

2 behaviors are possible, but Hugo responds to neither of these.

### Case 1: A passage typed with (breaking) spaces

The following sentence

> « Ce passage contient des espaces sécables »

will break at the guillemets, since **the spaces are not converted to non-breaking spaces**.

### Case 2: A passage typed without spaces, e.g.

The following sentence

> «Ce passage ne contient pas d’espaces»

has no space between the words and the guillemets and **Hugo will not insert non-breaking spaces there**.

I have tried accross multiple projects using Hugo, no luck.

## Config

In my `config.yml`, I have the following: 

```yaml
blackfriday:
  smartypantsQuotesNBSP: true
  smartyPants: true
```

The text is rendered using the regular `.Content` variable in page templates.

If I’m doing something wrong with my configuration, let me know.
Otherwise, I think this is a clear bug (because the markdown rendering does not do what it is expected to do.)

**Comment by bep** [comment]
If I read you correctly, your expectation does not match reality.

>« Ce passage contient des espaces sécables »

If the above is what you put in a markdown file, Hugo will not touch it.

If you have `smartypantsQuotesNBSP: true` and put this in the markdown file:

>>"Ce passage contient des espaces sécables"

The above becomes:

>« Ce passage contient des espaces sécables »


With non-breaking space inserted.

**Comment by loup-brun** [comment]
@bep thanks for the reply. However, the following appears incorrect when I test it:

> If you have smartypantsQuotesNBSP: true and put this in the markdown file:
>
>        "Ce passage contient des espaces sécables"
>
> The above becomes:
>
>    « Ce passage contient des espaces sécables »
>
> With non-breaking space inserted.

Is _not_ what happens either.

If I type:

       "Ce passage contient des espaces sécables"

It then renders to:
      
       “ Ce passage contient des espaces sécables ”

**But not with the ‘chevrons’ ( `«` `»`) I was expecting!**

If this is the correct behavior, I guess the Hugo documentation is not clear enough, which leads to a misunderstanding on my part and not actually a bug.

If I have time I'll try to fork the documentation page to help improve what the `smartypantsQuotesNBSP` actually does.

In the meanwhile I’ll fallback to a frontend solution with javascript.

**Comment by bep** [comment]
If you thinkg there is a bug here, you should report it upstream here: https://github.com/russross/blackfriday/issues
