### ISSUE TITLE
Expose `hasCJKLanguage` as a Site Variable to enable multilingual search

### ISSUE THREAD

**Issue by gcushen** [gohugoio/hugo#6374]
## Background

Currently, Hugo config has a `hasCJKLanguage` and Hugo pages can have `isCJKLanguage` to define a site or page as using Chinese, Korean, or Japanese characters.

## The Problem

To implement multilingual frontend search in Hugo, we must use a different search configuration for CJK and non-CJK content. However, currently these parameters are not exposed to themes so there is no variable or function to return whether a site or page has CJK content.

## The Solution

Expose the site (`hasCJKLanguage`) and page (`isCJKLanguage`) parameters as site and page variables.

For site search, `hasCJKLanguage` will be the most important parameter to expose.

**Comment by bep** [comment]
>For site search, hasCJKLanguage will be the most important parameter to expose.

Do you understand that this is the "site owner" telling Hugo that the site may contain CJK language? It's a performance optimization which makes us not having to look at the content for non-CJK sites (e.g. my site in Norwegian).

What search engines are we talking about here? I would be surprised if the big ones do not have this part of their indexing routine.

**Comment by gcushen** [comment]
@bep there's a misunderstanding there, I am not referring to external search providers.

I am referring to the fact that implementing multilingual JS based search, for example **Fuse.js**, in Hugo requires knowing whether or not the site contains a CJK language.

A JS site search algo for a CJK site content requires different params to an non-CJK site.

Hence, exposing the site (`hasCJKLanguage`) and page (`isCJKLanguage`) parameters as site and page variables would resolve this :)

**Comment by gcushen** [comment]
@bep any thoughts on exposing the site (`hasCJKLanguage`) and page (`isCJKLanguage`) parameters as site and page variables in order to enable Hugo sites to have in-built multilingual search (via in-built JS algo) without requiring Hugo site admins to use external multilingual search providers?

Assume a site with content in both Chinese and English for example, without the Hugo template (and thus in-built JS search algo) knowing that a CJK language is present, the text analysis part of the search will fail due to the fact characters must be treated very differently.

**Comment by peaceiris** [comment]
How about detecting your language by `.Site.Language.Lang`?

**Comment by gcushen** [comment]
> How about detecting your language by `.Site.Language.Lang`?

So you are implying that `hasCJKLanguage` is an unnecessary option that should be removed by Hugo team, who should then determine if a site contains CJK by examining `.Site.Language.Lang`?

There are a couple of points here:

1. Why haven't Hugo team implemented what you implied? I'm assuming because it may not be trivial to implement an automatic CJK detection
1. language logic ideally belongs in Hugo itself, where CJK logic is already implemented but not exposed as a parameter to templates - all I'm asking is for it to be exposed as a param
1. a multilingual site can set language to `en` but also set `hasCJKLanguage = true` due to presence of CJK characters in content - from a search perspective, the key thing here is to know `hasCJKLanguage = true` which otherwise wouldn't be known if we just fetched the 'lang' param

**Comment by peaceiris** [comment]
Thank you @gcushen 
I was able to understand your explanation and found the following lines.

https://github.com/gohugoio/hugo/blob/bd98182dbde893a8a809661c70633741bbf63911/hugolib/page__meta.go#L581-L587

If `hasCJKLanguage` is true, Hugo already detects CJK by `cjkRe.Match()`. `hasCJKLanguage` looks unnecessary.

**Comment by bep** [comment]
@peaceiris IsCJKLanguage is not directly connected to `.Site.Language.Lang`.

I'm hesitant about exposing these settings without some thought because that would put a restriction on us in the future if we found a smarter way to do this. The site setting is just a performance thing (if we know it isn't CJK in the site, we don't need to look), so the relevant setting to expose would be `.Page.HasCJKLanguage`. But before doing that I would like to be pointed to a reference to a search engine that does not support this out of the box without being told so? Because I assume that any search indexing would mean tokenizing text, so you would have plenty of time to determine if it's CJK or not.

**Comment by gcushen** [comment]
@bep I mentioned a use case (Fuse.js, or custom client-side JS search engine) for this in a previous comment above (https://github.com/gohugoio/hugo/issues/6374#issuecomment-537154042 ). Essentially, parameters to client-side JS search can vary depending on the presence of CJK content in the index.

Sure, we could perform the same CJK regex from the Hugo Go code in the client-side JS, but (a) it's duplicating work rather than reusing the awesome functionality which you have already implemented in Hugo 😄  , and (b) for performance reasons, it would be preferable to determine CJK in Hugo template at build time rather than later on on client-side 🚀 .

Most multilingual users are perhaps using themes with no search or an external search like Algolia so probably haven't really considered the above points. Currently, Academic has integrated client-side search and this is my main reason for raising this issue to offer better multilingual search results. As Hugo moves more into the JS world, I assume others will follow and there will be more momentum with this kind of thing...

**Comment by bep** [comment]
OK, but we agree that this is limited to `Page.IsCJKLanguage`?
