### ISSUE TITLE
After should accept 0 as an index

### ISSUE THREAD

**Issue by gnalck** [gohugoio/hugo#6388]
### Issue Description
Currently [after](https://gohugo.io/functions/after) blows up if you pass in 0 as the index, which feels like a valid usage that should not crash things. The line that causes this is [here](https://github.com/gohugoio/hugo/blob/6027ee11082d0b9d72de1d4d1980a702be294ad2/tpl/collections/collections.go#L63). 

If this gets maintainer approval I'm happy to make the change myself, given that its only a line or two :).

### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
Hugo Static Site Generator v0.58.1-24277B92 linux/amd64 BuildDate: 2019-09-06T09:19:04Z
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
>If this gets maintainer approval I'm happy to make the change myself,

Approved, but please also add a test case.
