### ISSUE TITLE
Issue: parenthesis has been ignored in website link

### ISSUE THREAD

**Issue by dawnarc** [gohugoio/hugo#6393]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ v0.58.3

</pre>

### Does this issue reproduce with the latest release?
Yes

### Describe
template content:
```
##### Plane (geometry) Equation in 3D

https://en.wikipedia.org/wiki/Plane_(geometry)
```
Result:
![2019-10-06 22_08_04-TestTD - Microsoft Visual Studio](https://user-images.githubusercontent.com/3351764/66270891-f9778000-e88a-11e9-9cdd-aa820a3e4df6.png)

**Comment by bmackinney** [comment]
@dawnarc this looks like an issue with the markdown renderer, not with Hugo. 

Please also ask over on https://discourse.gohugo.io

Over there, I'd answer this with: 
Consider using a different method for adding your link, like those shown here: https://meta.stackexchange.com/questions/13501/links-to-urls-containing-parentheses

**Comment by dawnarc** [comment]
@bmackinney Thanks very much for your suggestion, I have changed method of link expression and it worked.
