### ISSUE TITLE
Page .Kind depends on order of [taxonomies] and disableKinds in config.toml

### ISSUE THREAD

**Issue by ChrisLasar** [gohugoio/hugo#6394]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.58.3/extended linux/amd64 BuildDate: 2019-09-20T11:05:35Z
</pre>

### Does this issue reproduce with the latest release?
See version above

If my `config.toml` shows:
<pre>
[taxonomies]
  wert = "werte"

disableKinds = ["RSS"]
</pre>

My section page at `*/content/erfolg/` becomes `.Kind` of `taxonomy` and its `.Pages` "attribute is empty. Note that the term "erfolg" is not configured to become a taxonomy.

If I switch the configration  order in `config.toml` to: 
<pre>
disableKinds = ["RSS"]

[taxonomies]
  wert = "werte"
</pre>
My section page at `*/content/erfolg/` becomes `.Kind` of `section` and its `.Pages` "attribute contains the pages at this point. This is the behavior I expected.

**Comment by pamubay** [comment]
Yes, it's TOML, do not put `one-liner` config after `[table]` config. You can check more here [TOML#table](https://github.com/toml-lang/toml#table).

The first example will put `disableKinds` nested under `[taxonomies]` config. make the config invalid

First Example:
```
[taxonomies]
  wert = "werte"

disableKinds = ["RSS"]
```
Output:  (in JSON)
```
{
  "taxonomies": {
    "wert": "werte",
    "disableKinds": [
      "RSS"
    ]
  }
}
```

**Second Example:** 
```
disableKinds = ["RSS"]

[taxonomies]
  wert = "werte"
```
Output: (in JSON)
```
{
  "disableKinds": [
    "RSS"
  ],
  "taxonomies": {
    "wert": "werte"
  }
}
```

You can test it here to see TOML to JSON representation [TOMLtoJSON](http://binarymuse.github.io/toml-node/)

**Comment by ChrisLasar** [comment]
Thanks. Took me hours to detect this. Just used TOML because the template did so. Will never use it again ;)

**Comment by nancym** [comment]
I, also, will never use TOML again 😱 (and have written about this in https://www.ii.com/themeless-gitless-intro-hugo/)
