### ISSUE TITLE
hugo server treats static pages different

### ISSUE THREAD

**Issue by Basskrapfen** [gohugoio/hugo#6400]
<pre>
Hugo Static Site Generator v0.58.3/extended linux/amd64 BuildDate: 2019-09-20T11:05:35Z
</pre>

Hi,

I'm currently using the hugo multilang feature with separate folders for every language, including the default language. Hugo will generate a index.html with a forward to the default language in the root folder. I want to replace this default forward file.

To replace the generated index.html in the root folder, I placed a hand-crafted index.html in /static . When generating the page using hugo it behaves as expected, the static file replaces the generated one. But when using hugo server, the generated file is not replaced.

In my opinion both approaches should lead to the same result.

Thanks and regards,
Oliver

**Comment by bep** [comment]
You cannot depend on the order of static vs the others, the last file with a given name will win.
