### ISSUE TITLE
Add recursive variants of .Pages and .RegularPages

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6411]
Currently when you do  `.Pages` or `.RegularPages`, you the pages in the current section, one level deep.

But having a flat view of all the pages below a section (e.g. `blog`) is a common requirement, which in its simplest form isn't hard to do (most people do `where .Site.RegularPages "Section" "blog"` or something). But it gets non-trivial fast.

With the work I'm doing in this area, adding some simple-to-use methods for the above would be trivial.

**The hard part is the naming, so please help.**

Given the home page, 

* `.PagesAll` == `.Site.Pages`
* `.RegularPagesAll` == `.Site.RegularPages`
* `$blog.RegularPagesAll` will give all regular pages in and below `/blog`.

`.RegularPagesAll` is obviously not a good name, which is where I need some help. 

/cc @regisphilibert @kaushalmodi

**Comment by kaushalmodi** [comment]
`.RegularPagesRecursive`? It's a bit wordier but there will be no confusion on what it does.

**Comment by bep** [comment]
>.RegularPagesRecursive? It's a bit wordier but there will be no confusion on what it does.

Maybe. But `Recursive` isn't a particularly common word, and even I'm not sure that it covers what it says.

I thought about `.RegularPagesBelow`.

**Comment by kaushalmodi** [comment]
> But Recursive isn't a particularly common word, and even I'm not sure that it covers what it says.

Here are few common uses of "recurse" .. `grep -r` or `grep --recursive`, `git clone --recurse-submodules ..`. I think it should be pretty evident; just my few cents.

**Comment by bep** [comment]
Yes, it's pretty good, I'll admit that. And it's certainly shorter than the "where clause" needed today.

**Comment by regisphilibert** [comment]
So even though it might not be 100% acurate to what we’re trying to achieve here what about .AllRegularPages

For me recursive is about function calling themselves but here we just want to a flat list of the tree’s leaves right?

There is slight possibility that this brings confusion with the existing site.AllPages which serves a different purpose (cross languages) but I’d take that risk.

**Comment by bep** [comment]
I would kind of also like that these sorted nicely alphabetically. Unless someone chimes in with something fantastic, I think I'll take @kaushalmodi 's side and go with *Recursive.

**Comment by andekande** [comment]
some more ideas:
.CurrentSection.PagesBelow
.CurrentSection.LeafPages
.CurrentSection.DescendantPages

In any case, would you then skip the Sub-Sections themselves from the result ? They can be accessed via the resulting Page anyway.
