### ISSUE TITLE
Add nolist and norender

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6412]
There is certainly a risk adding new top-level front matter keywords, but if we come up some distinctive enough ...

Given my naming suggestion in the title:

* `nolist`:  The page will be rendered and will have a `.RelPermalink`, but will not show up in any of the page collections (`.RegularPages` etc.). If you set this on sections, they will still be reachable via `.Parent` and similar.
* `norender`: The page will not be rendered and will not have a `.RelPermalink`, but will show up in page collections.

A page with both of the above set will behave like a `headless` bundle.

Better names for the above? /cc @kaushalmodi @regisphilibert and gang.

**Comment by kaushalmodi** [comment]
I am a bit confused thinking of all options together.. will need to come up with a table that differentiates:

1. draft = false (default)
2. draft = true
3. nolist
4. norender

In what combinations can those 3 switches be used? We first need to spec that out. 

Once that is clear, we can think of better names.

My first reaction is that we should not add 2 more switches, but just one switch with different possible values. That would disallow people from abusing these switches in random combinations.

**Comment by regisphilibert** [comment]
Has anybody has a use case for `nolist`?

I can think of several, but for all of them, I would still need to grab those pages as a collection for some other use.
Ex:  using their data to build a graph, listing them in a different output format, render a list on another page which refers them etc...
And if no collection can produce them, then you're better off using a headless bundle.

My take on this is, if you don't want pages to surface in your collection, you should content with applying the proper `where` clauses when needed.

But then again, some unforeseen use cases might enlighten me.

**Comment by mcdee** [comment]
> Has anybody has a use case for `nolist`?

These were discussed in #6316

**Comment by regisphilibert** [comment]
Oh yes, just remember now. I made my point there already it seems :) I will reiterate though:

`nolist` will prevent them from being found by Hugo outside of a `.GetPage` which exclude the possibility of finding them "in batch". 
To mention @mcdee's use case, even dynamically producing a list of "private" pages for the client's consumption will not impossible.

So I for one, will never be able to use `nolist`.

**Comment by bep** [comment]
>So I for one, will never be able to use nolist.

I bet you want to use nolist+norender. Which would be similar to what a `headless` bundle (which I eventually will "hide from the docs", so to speak).

* So, `draft` and the other ways to _not build_ pages (expiryDate etc.) tells Hugo _if_ it should be published.
* These 2 new flags tells Hugo _how_ they should be published.

So while certainly related, I think it muddles the discussion to combine them ...

I bring these to new flags into one discussion just because of that, some of the power comes from the combinations.

* nolist+norender = "headless page", you can reach it from `.Site.GetPage` (and also the structural methods like `.Parent`), but they will have no `.RelPermalink`.
* nolist:  Same as any page, but is hidden from any page collection, e.g. `RegularPages`.
* norender: Will not be rendered on its own, and will not have `.RelPermalink` but can be reached from `.Site.GetPage` and is also listed in `RegularPages` etc.

**Comment by regisphilibert** [comment]
> I bet you want to use nolist+norender.

Nope. As I will not be able to build a collection with those content files contrary to the headless bundle where I can `{{ range $headlessBundle.ResourcesByType "page" }}`

**Comment by bep** [comment]
Revisiting this, I think I will add a third flag, but putting this into below `_build`, e.g.:

```yaml
_build:
    list: true
    render: true
    publishResources: true
```

The `headless` option will still work, but the above is obviously more flexible and will work for any page. A `headless` page can then also be configured as:

```yaml
_build:
    list: false
    render: false
    publishResources: true
```

`publishResources` is mostly added here to get rid of lot of special source code for handling of the "headless pages", but I have seen many requesting it -- this is especially useful for sites with big image originals where you only use the resized variants.

/cc @regisphilibert @kaushalmodi and gang.

**Comment by regisphilibert** [comment]
> I also plan to add a pages section in config.toml to allow for default "page config", e.g:

I think the homepage's cascade is a good place to assign global Front Matter defaults. This enables users to globally assign any Front Matter value without having to add any new `keys` to the config file and the documentation that goes with it.

I would add though, and sorry for taking this thread a wee bit astray:
My only reservation about this as a general rule is that currently the `cascade` settings are applied to the current page, and not only the pages below it. This mean such "defaults" in cascade often have to be overwritten from the origin "content file", especially when in the homepage.

If other agree with my statements about using the homepage's cascade to set defaults for everything "front matter". I'll create an issue to revert cascade applying to self.

**Comment by tristan957** [comment]
Could someone point me to the documentation where this is talked about? I am struggling to find it. Searching for it on the docs site comes up empty. Would really like to publish unlisted content for peer review. I saw a way to do it in a discourse page, but that was 2 years before this implementation.

**Comment by regisphilibert** [comment]
look for Build Options

**Comment by tristan957** [comment]
@regisphilibert you're a lifesaver
