### ISSUE TITLE
After throws unhelpful error message on passing invalid index

### ISSUE THREAD

**Issue by BaibhaVatsa** [gohugoio/hugo#6415]
### Issue description
On passing negative indices, ![after](https://gohugo.io/functions/after) throws error message !["can't return negative/empty count of items from sequence"](https://github.com/gohugoio/hugo/blob/096a4b67b98259dabff5ebfbfd879a41999a1ed2/tpl/collections/collections.go#L64) which does not accurately explain the error. Something like "cannot return slice of elements after a negative index" would be more explanatory in my opinion. Any suggestions?

If this gets the approval, I will be more than happy to submit a PR.
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.59.0-DEV-096A4B67 linux/amd64 BuildDate: 2019-10-11T02:36:33-0500
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by BaibhaVatsa** [comment]
I feel that the suggested error message makes more sense for after. Should I submit a PR with the change for after?

First throws !["can't return negative count of items from sequence"](https://github.com/gohugoio/hugo/blob/5f1aafafb40299bb4c8aebf71e05843431eb84c5/tpl/collections/collections.go#L222) which I feel can be changed to something like 
```
sequence length must be non-negative
```
to resemble more of what the Go compiler would throw.

**Comment by bep** [comment]
Sounds good.

**Comment by BaibhaVatsa** [comment]
I was thinking that once #6419 is closed, I will change ![last's throw message](https://github.com/gohugoio/hugo/blob/5f1aafafb40299bb4c8aebf71e05843431eb84c5/tpl/collections/collections.go#L382) also to 
```
sequence length must be non-negative
```
as it would have the same condition as first then.

**Comment by bep** [comment]
I agree.
