### ISSUE TITLE
Last should accept 0 as limit

### ISSUE THREAD

**Issue by BaibhaVatsa** [gohugoio/hugo#6419]
## Issue description
Currently, Last ![throws an error](https://github.com/gohugoio/hugo/blob/5f1aafafb40299bb4c8aebf71e05843431eb84c5/tpl/collections/collections.go#L381) if 0 is passed as a limit even though that usage should not crash things.
Further, ![first accepts 0](https://github.com/gohugoio/hugo/blob/5f1aafafb40299bb4c8aebf71e05843431eb84c5/tpl/collections/collections.go#L221) as a value for limit and returns an empty slice in that case so for consistency last should also accept 0 as limit.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.59.0-DEV-096A4B67 linux/amd64 BuildDate: 2019-10-11T02:36:33-0500
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
I agree. I labeled this as an Enhancement, as I guess there are test cases for it. But you are right, what you say makes much more sense.
