### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by crazy-max** [gohugoio/hugo#6422]
Hi @bep,

As I did for GoReleaser through goreleaser/goreleaser#1149, I thought that Hugo should also benefit from its GitHub Action 🙂

That's why I have created a native [GitHub Action for Hugo](https://github.com/crazy-max/ghaction-hugo) using the [typescript-action](https://github.com/actions/typescript-action).

This [works](https://github.com/crazy-max/ghaction-hugo/blob/master/.github/workflows/ci.yml) (and [passes](https://github.com/crazy-max/ghaction-hugo/commit/e90e0f768b962def5bab65cf0e56d2e02aecf2ea/checks?check_suite_id=262067495)) on all [virtual environments](https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments-and-hardware-resources) supported by GitHub Actions. A "real world" example is [available](https://github.com/crazy-max/crazymax.dev/blob/dev/.github/workflows/website.yml) if you want to take a look.

Like I have done for [GoReleaser Action](https://github.com/goreleaser/goreleaser-action), I would be glad to transfer the repository to gohugoio org.

I can also open a PR to update the documentation as it was the [case for GoReleaser](https://goreleaser.com/actions/).

Keep it up on this project guys!

**Comment by peaceiris** [comment]
This repo is not suitable for spreading. You can share your work at [Hugo forum](https://discourse.gohugo.io/c/announcements).
