### ISSUE TITLE
hugo页面对图片是否支持base64

### ISSUE THREAD

**Issue by VEH47** [gohugoio/hugo#6427]
目前大多数的图片都是用本地存储或第三方生成的链接, 不知道hugo是否支持图片解析为base64

**Comment by bep** [comment]
You need to write in English (or Norwegian) for me to understand.

**Comment by peaceiris** [comment]
@VEH47 I read your message with Google Translation.

- [base64 | Hugo](https://gohugo.io/functions/base64/#readout)

Hugo has the base64 function. Maybe, you can treat your images with this function.

**Comment by VEH47** [comment]
> 您需要用英语（或挪威语）书写才能理解。

At present, most of the pictures are linked by local storage or third-party generation. I don't know if Hugo supports image parsing to base64.

**Comment by peaceiris** [comment]
You can search related topics at https://discourse.gohugo.io/search?q=image%20base64

**Comment by bep** [comment]
>Hugo supports image parsing to base64.

We do. You can pipe the raw content into`base64Encode`,  e.g.

{{ $image.Content | base64Encode }}

https://gohugo.io/functions/base64/#readout
