### ISSUE TITLE
fileExists does not work with concated string

### ISSUE THREAD

**Issue by Flogex** [gohugoio/hugo#6434]
### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
Hugo Static Site Generator v0.58.3-4AAC02D4 windows/amd64 BuildDate: 2019-09-19T15:29:19Z
</pre>

### Does this issue reproduce with the latest release?
Yes

### What I try to achieve
I am creating a Single Page template. I only want to show the avatar of an author if there is a file named after them. Pages can have an _author_ parameter in the front matter.

### How to reproduce
The following code does not work and leads to a build error.

```go
{{ $avatarPath := print "img/authors/" .Params.author ".png" | lower }}
{{ $extendedPath := print  "static/" $avatarPath }}
{{ if fileExists $extendedPath }}
    <img src="{{ $avatarPath | absURL }}" alt="Image of author">
{{ end }}
```

I get this error message:
"Error: Error building site:
  failed to render pages:
  render of "page" failed: "\layouts\\_default\single.html:5:10":
  execute of template failed: template: \_default\single.html:10:7:
  executing "main" at <partial "metadata" .>: error calling partial: "\layouts\partials\metadata.html:5:10":
  execute of template failed: template: partials/metadata.html:5:10: executing "partials/metadata.html" at <fileExists $extendedPath>:
  error calling fileExists: CreateFile \static\img\authors\\\<nil\>.png: The filename, directory name, or volume label syntax is incorrect."

Note that it sometimes works without an error if the Hugo server is already running and I change the file. But the `hugo` command will fail anyway.

### What does work
If I initialize a new variable with `.Params.author`  and apply ` | lower` only to it, the error does not occur.

```go
{{ $author := .Params.author | lower }}
{{ $avatarPath := print "img/authors/" $author ".png" }}
```

If the path is not prefixed by _static/_ it works (also the image will not appear on the page).

```go
{{ $avatarPath := print "img/authors/" .Params.author ".png" | lower }}
{{ if fileExists $avatarPath }}
    <img src="{{ $avatarPath | absURL }}" alt="Image of author">
{{ end }}
```

It also works if I write the path manually:

```go
{{ if fileExists "static/img/authors/sample.png" }}
    <img src="{{ $avatarPath | absURL }}" alt="Image of author">
{{ end }}
```

I am fine using the first working approach with declaring a new variable.

But maybe you can explain to me why this happens?

**Comment by moorereason** [comment]
The issue has more to do with how you're using `print` and the fact that `.Params.author` is undefined (`nil` internally).  When you pass a nil value to `print`, it puts angle brackets around the string representation of the value (`<nil>`).  The angle brackets in the file path are causing the error you see.

My recommendation is to ensure that  `.Params.author` is defined before trying `fileExists`.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
