### ISSUE TITLE
enableRobotsTXT = true causes a "/true" page to be generated

### ISSUE THREAD

**Issue by Kevin4n6** [gohugoio/hugo#6435]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo 0.55.6
Hugo 0.58.3
</pre>

### Does this issue reproduce with the latest release?
Yes

Setting enableRobotsTXT = true in config.toml causes a "hxxps://website url/true" page to be generated for the site with a Title of "True".  The issue goes away when "enableRebotsTXT" is removed or set to 'false'.

**Comment by Kevin4n6** [comment]
This appears to be a bug in the theme and not a bug in hugo.

**Comment by Kevin4n6** [comment]
I have been corrected by the author of the theme that this is an issue with hugo. Reopening.

**Comment by bep** [comment]
I have checked in the code, and I don't see how this can happen.

**Comment by ianrodrigues** [comment]
@Kevin4n6 what are you using?
