### ISSUE TITLE
Stick html and head tags

### ISSUE THREAD

**Issue by ugurcemozturk** [gohugoio/hugo#6436]
### What version of Hugo are you using (`hugo version`)?

<pre>
v0.58.3/extended
</pre>

### Does this issue reproduce with the latest release?
No.

Hey, when I run `hugo serve` or publish the app via `hugo`, 
the <html> and <head> tags are always sticky so the browser wont render properly.

İe output:

```
<!DOCTYPE html>
<html lang="en"><head>
... 
<!-- Head elements here -->
...
</head>
<body>
...
```

Is this a know issue?
Thanks.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
