### ISSUE TITLE
markdown (reference-style) links parsing issue.

### ISSUE THREAD

**Issue by butuzov** [gohugoio/hugo#6438]
### What version of Hugo are you using (`hugo version`)?
```bash
$ hugo version
>Hugo Static Site Generator v0.58.3/extended darwin/amd64 BuildDate: unknown
```

### Does this issue reproduce with the latest release?
Yes

### Description
There are small conflict in reference-style links if markdown "looks" close to inline style (But has space/tab after square bracket).

#### Reproducible Example 

```markdown

* [example_org]
* [example_net](https://example.net)
* [example_com] (this isn't suppose to be link)


[example_org]: https://example.org
[example_com]: https://example.com
```

#### Expected Output 
```html
<ul>
  <li><a href="https://example.org">example_org</a></li>
  <li><a href="https://example.net">example_net</a></li>
  <li><a href="https://example.com">example_com</a></li>
</ul>
```

#### Actual Output 

```html
<ul>
  <li><a href="https://example.org">example_org</a></li>
  <li><a href="https://example.net">example_net</a></li>
  <li><a href="this isn't suppose to be link">example_com</a></li>
</ul>
```

**Comment by butuzov** [comment]
Should this issue be moved to russross/blackfriday  or it's something gohugoio/hugo can deal with?

**Comment by Brixy** [comment]
You are right. This is (probably a blackfriday) bug.

As a dirty hack you can use a non-breaking space before the round bracket or use

```
* [example_com] \(this isn't suppose to be link)
```

Lets hope for Goldmark to come: #5963.
