### ISSUE TITLE
v0.58.3 and v0.59.0 extended running error in centos7.6 x64

### ISSUE THREAD

**Issue by riverlee2014** [gohugoio/hugo#6444]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.58.3 and v0.59.0 extended linux x64
</pre>

### Does this issue reproduce with the latest release?
There is an exception when running in centos 7.6 x64
```shell
hugo: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by hugo)
hugo: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by hugo)
```
screenshot:
![image](https://user-images.githubusercontent.com/7055799/67253010-2c835b80-f4a8-11e9-8f54-6d584c31c712.png)

**Comment by bep** [comment]
The error message says it. I don't know Centos good enough to know how to install a newer version of glibc. You may ask at:

 https://discourse.gohugo.io/

**Comment by riverlee2014** [comment]
I solved this problem by compiling hugo source in centos 7.6. 
The version of os libstdc++  is higher than tip version '3.4.20'.
