### ISSUE TITLE
Allow customizing file names resulted from PaginatePath

### ISSUE THREAD

**Issue by ahmetb** [gohugoio/hugo#6445]
It seems like the only way to get pagination outputs currently is:

- /{{PaginatePath}}/2/index.html
- /{{PaginatePath}}/3/index.html
- ...

However, I need something like

- /index2.html
- /index3.html

mostly because I'm migrating from another CMS and I'd love to preserve the URLs.

----

I propose we offer a global site configuration parameter, with a default:

    PaginatePathFormat: '{{PaginatePath}}'

This value is a text/template executed with values PaginatePath or PageNumber, e.g. in my case I can write:

    PaginatePathFormat: 'index{{PageNumber}}.html'

Is this a sane proposal?

**Comment by bep** [comment]
We currently don't do any variable expansion by Go templates in the configuration. We do have some custom placeholder syntax for permalink config. I understand that people would want "something like this" in the general case, but I'm not ready to spend commit to that change right now.

**Comment by ahmetb** [comment]
This makes sense. Feel free to close this as by-design.
As you said, something like :var format could work better here, though, it likely needs a character around the expression to distinguish it from the rest of the string. At that point, might as well use text/template.
