### ISSUE TITLE
Runtime Error in Hugo 0.59.0

### ISSUE THREAD

**Issue by marmanold** [gohugoio/hugo#6450]
Hugo Version: `Hugo Static Site Generator v0.59.0/extended darwin/amd64 BuildDate: unknown`
OS: macOS Mojave 10.14.6

Issue:

Starting with this version I receive three errors when I generate my site.  Nothing has change in my repository since the previous version of Hugo, so this is a new regression.

My site builds as expected (so far as I can tell), but Hugo produces three runtime errors.

Hugo output from terminal below.  Please let me know what other information you might need.

```bash
Building sites … ERROR 2019/10/22 16:10:49 runtime error: index out of range [2] with length 2
ERROR 2019/10/22 16:10:49 runtime error: index out of range [2] with length 2
ERROR 2019/10/22 16:10:49 runtime error: index out of range [2] with length 2

                   |  EN   
+------------------+------+
  Pages            | 1159  
  Paginator pages  |   60  
  Non-page files   |    0  
  Static files     |   78  
  Processed images |    0  
  Aliases          |  591  
  Sitemaps         |    1  
  Cleaned          |    0  

Total in 626 ms
```

**Comment by bep** [comment]
> Please let me know what other information you might need.

While I agree that this is a bug, I would most likely need access to your project or a Hugo site with this error. If this is a private GitHub project you may consider sharing it with me for a short while so I can run it.

**Comment by marmanold** [comment]
I sent you an invite to the site's repository.  Thank you so much for giving it a look!

**Comment by bep** [comment]
@marmanold thanks, I got it. It's a bug introduced in Chroma, the highlighter we use.

**Comment by bep** [comment]
It's now fixed upstream in Chroma (that was impressively fast!), and I will try to find time to do a patch release later today.
