### ISSUE TITLE
Make readDir return hugofs.FileMetaInfo

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6453]
Which should make it a little easier to use (with the added metadata such as `Path` and `Filename`).

**Comment by BaibhaVatsa** [comment]
Hi! I was interested in working on this. 
I was thinking that a way of implementing this would be making a slice of `hugofs.FileMetaInfo` and then have all the values appended to the slice with the FileMeta having Path and Filename.
However, os.FileInfo already seems to have a Name field to store the filename so the Filename key might not be needed.

**Comment by bep** [comment]
There are already some decorators in there that do the wrapping.

**Comment by BaibhaVatsa** [comment]
Hi! I could find these three functions in ![hugofs/fileinfo.go](https://github.com/gohugoio/hugo/blob/master/hugofs/fileinfo.go): ![fileInfosToFileMetaInfos](https://github.com/gohugoio/hugo/blob/9f46a72c7eec25a4b9dea387d5717173b8d9ec72/hugofs/fileinfo.go#L295),
![decorateFileInfo](https://github.com/gohugoio/hugo/blob/9f46a72c7eec25a4b9dea387d5717173b8d9ec72/hugofs/fileinfo.go#L262), and ![NewFileMetaInfo](https://github.com/gohugoio/hugo/blob/9f46a72c7eec25a4b9dea387d5717173b8d9ec72/hugofs/fileinfo.go#L205) which can wrap FileInfo to FileMetaInfo. The first two are not exported and my solution uses the third:
```golang
contents := make([]hugofs.FileMetaInfo, 0, len(list))
for _, content := range list {
	contents = append(contents, hugofs.NewFileMetaInfo(content, hugofs.FileMeta{
		"Path":     path,
		"Filename": content.Name,
	}))
}
```
