### ISSUE TITLE
Ressources deleted in 0.59.0 with --gc --ignoreCache

### ISSUE THREAD

**Issue by divinerites** [gohugoio/hugo#6455]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.59.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes. This is occuring since the latest 0.59.0

- I have several sites using images functions. Works really fine on 0.58.3 and before.
  - I use `--gc --cleanDestinationDir --ignoreCache` options 
  - my ressources are well generated, and if I open my file browser I can see the ressources being uptated as the process goes. Fine.

- On 0.59.0, all seems to work fine, I can see all the resources/_gen/images being generated and updated, and then at the end they are all removed and the folder becomes empty (and git get all those files missing and propose to commit this file deletion.

- If I remove `--ignoreCache` options and use `--gc --cleanDestinationDir` it seems to work fine.
- If I remove `--gc` options and use `--cleanDestinationDir --ignoreCache` it seems to work fine.

So it seems the  `--gc --ignoreCache` is the problem. And this occurs on every site with hugo images processing.

**Comment by bep** [comment]
I don't remember any related changes for 0.59 that would change this behavior.

That said, from what I see, what you describe is how I would expect it to behave.


* --gc --ignoreCache your telling Hugo to "don't use cache" and then to "delete expired or unused entries from cache"

Cache is good, so I suggest you use it. Have a look in the docs for how to create a more fine grained cache confg (in your case at least keep the images for "some time").

**Comment by divinerites** [comment]
I think I get your point. I was expecting something different.

- `--gc` removes unused entry from cache : yes, I was expecting that.
- The thing is I didn't understood that with `--ignoreCache` => entries are created in cache, but unused => then `--gc` removes all of them because they are unused even if created.
- I was expecting just ignoring them, and `--gc` being first action (it seems it is the last action)

Makes sense, even if may be we could skip entries in cache when both `--gc` and `--ignoreCache` are together.

Thanks a lot Bep for the clarification and the light. Will look for fine tuning the cache.
