### ISSUE TITLE
hugo.Environment ignores HUGO_ENV used by Netlify and Forestry

### ISSUE THREAD

**Issue by gcushen** [gohugoio/hugo#6456]
### What version of Hugo are you using (`hugo version`)?

v0.58.1

### Does this issue reproduce with the latest release?

Yes

### Problem

There are at least two ways to set the environment to development or production in Hugo.

Many users are reporting very confusing behavior to us in the way that `hugo.Environment` ignores `HUGO_ENV`.

Surely, the following statement should be true if either `HUGO_ENV="production"` or if the `-e production` argument is provided, otherwise this behavior can be very confusing to users:

    {{ if eq (hugo.Environment) "production" }}

**Comment by bep** [comment]
You can use `HUGO_ENVIRONMENT`. Does the doc mention `HUGO_ENV`?

**Comment by gcushen** [comment]
Thanks for clarifying.

It appears that both Netlify and Forestry use `HUGO_ENV` though, so it would be logical either they use `HUGO_ENVIRONMENT` or Hugo begins to understand `HUGO_ENV` as the Hugo.Environment?

See

* https://gohugo.io/hosting-and-deployment/hosting-on-netlify/
* https://forestry.io/docs/previews/build-commands/

**Comment by bep** [comment]
You could start by removing the big BUG in the title, then, as this is obviously not that.

**Comment by gcushen** [comment]
Currently, the docs only appear to mention `HUGO_ENV` and not `HUGO_ENVIRONMENT`, hence it appeared to be a bug. Thanks for clarifying that it's an inconsistent use of environment within the community, and I've updated the title to reflect that :)

I assume it would be beneficial to support `HUGO_ENV` in Hugo since a large number of Hugo powered Netlify and Forestry sites already use this approach.

**Comment by gcushen** [comment]
FYI [GitHub states that there are currently ~16,500 files (very rough max. proxy for sites) using the `HUGO_ENV` approach](https://github.com/search?q=HUGO_ENV&type=Code) - perhaps you might find that compelling enough to warrant supporting it as an environment?

**Comment by ianrodrigues** [comment]
+1 for supporting `HUGO_ENV`.
