### ISSUE TITLE
Pipes: assetDir config not finding theme directory

### ISSUE THREAD

**Issue by davidcalhoun** [gohugoio/hugo#6457]
### What version of Hugo are you using (`hugo version`)?

`v0.59.0`

### Does this issue reproduce with the latest release?

Yes.

### Details
First, thank you for Hugo!  It's been a joy to use, and is super fast and configurable.

I'm having a problem using Pipes to transform some CSS with this code that lives in a theme's layout:

```html
{{ $style := resources.Get "css/main.scss" | toCSS | minify | fingerprint }} 
<link rel="stylesheet" href="{{ $style.Permalink }}">
```

When it works, this outputs a processed file to `/public/css/main.min.[hash].css`

However, this only seems to work as long as the source file in the theme folder lives under `/themes/my-theme/assets/`.  If I configure `assetDir = "foo"` in `config.toml`, I expect that Hugo Pipes will instead look under `/themes/my-theme/foo/` as configured, but it doesn't seem to.  Instead it spits out an error that seems to indirectly say that the file can't be found:

```
...
execute of template failed: template: partials/css.html:10:45: executing "partials/css.html" at <toCSS>: error calling toCSS: type <nil> not supported in Resource transformations
```

It's unexpected and confusing if this is the intended behavior.  At the very least the docs should probably have a disclaimer saying that `assetDir` points to the top level only and ignores any similarly-named directory in a theme.

I would be sad if that's the intended behavior though.  It seems reasonable that a theme would have CSS and other assets that could get processed with Pipes.

Thank you in advance!

### Related links
* https://stackoverflow.com/questions/56300442/hugo-assetdir-configuration-for-asset-bundling-pipe-does-not-work-for-themes
* https://github.com/gohugoio/hugo/issues/5207

**Comment by bep** [comment]
Hey,

`assetDir` only works for the main project, and that setting is considered legacy so I'm not going to do anything about it.

You can get what you want with the `modules` and the `mounts` configuration that was introduced recently. See docs. If you have further questions, use https://discourse.gohugo.io/

**Comment by davidcalhoun** [comment]
Thanks, I'll take a look at those new configurations and see if that helps.
