### ISSUE TITLE
_internal/pagination.html causes a lot of empty new lines

### ISSUE THREAD

**Issue by ahmetb** [gohugoio/hugo#6459]
hugo version v0.58.3

Template in question: https://github.com/gohugoio/hugo/blob/v0.58.3/tpl/tplimpl/embedded/templates/pagination.html

I have about ~440 pages of content. When I use `{{ template "_internal/pagination.html" . }}`, as a result I get roughly ~440 blank lines as a result of doing this ([here's a gist](https://gist.github.com/ahmetb/2727ea50321d24991668dfd5632b429e)).

This seems to be 1 empty line per page, despite the only thing that's rendered is this:
![image](https://user-images.githubusercontent.com/159209/67656449-109d1100-f911-11e9-99e6-4420e672207c.png)

It appears like changing this template with the following replacements fixes this issue:

- `{{` &rarr; `{{-`
- `}}` &rarr; `-}}`

If anyone's got a more elegant solutions, that would be great. However, doing this makes the resulting pagination content unindented/less-readable.

**Comment by bep** [comment]
It's a challenge to get this right in the templates. A related tip would be to use `hugo --minify` when building to production.

**Comment by ahmetb** [comment]
That's a fair point. The --minify just makes it harder for me to debug things in production by looking at the source, but I guess one isn't suppose to debug in prod.

Feel free to close this, otherwise I'm happy to make a patch that helps.
