### ISSUE TITLE
Functions in slice_fs.go are unimplemented

### ISSUE THREAD

**Issue by BaibhaVatsa** [gohugoio/hugo#6460]
[ReadDir](https://github.com/gohugoio/hugo/blob/c5e1e8241a3b9f922f4a5134064ab2847174a959/hugofs/slice_fs.go#L113), [OpenFile](https://github.com/gohugoio/hugo/blob/c5e1e8241a3b9f922f4a5134064ab2847174a959/hugofs/slice_fs.go#L109), [Read](https://github.com/gohugoio/hugo/blob/c5e1e8241a3b9f922f4a5134064ab2847174a959/hugofs/slice_fs.go#L242), [ReadAt](https://github.com/gohugoio/hugo/blob/c5e1e8241a3b9f922f4a5134064ab2847174a959/hugofs/slice_fs.go#L246), [Seek](https://github.com/gohugoio/hugo/blob/c5e1e8241a3b9f922f4a5134064ab2847174a959/hugofs/slice_fs.go#L267), [Stat](https://github.com/gohugoio/hugo/blob/c5e1e8241a3b9f922f4a5134064ab2847174a959/hugofs/slice_fs.go#L271), [Sync](https://github.com/gohugoio/hugo/blob/c5e1e8241a3b9f922f4a5134064ab2847174a959/hugofs/slice_fs.go#L275), [Truncate](https://github.com/gohugoio/hugo/blob/c5e1e8241a3b9f922f4a5134064ab2847174a959/hugofs/slice_fs.go#L279), [Write](https://github.com/gohugoio/hugo/blob/c5e1e8241a3b9f922f4a5134064ab2847174a959/hugofs/slice_fs.go#L283), [WriteAt](https://github.com/gohugoio/hugo/blob/c5e1e8241a3b9f922f4a5134064ab2847174a959/hugofs/slice_fs.go#L287), and [WriteString](https://github.com/gohugoio/hugo/blob/c5e1e8241a3b9f922f4a5134064ab2847174a959/hugofs/slice_fs.go#L291) in `hugofs/slice_fs.go` are not implemented and thus panic when called.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.60.0-DEV-C5E1E824 linux/amd64 BuildDate: 2019-10-29T02:50:32-0500
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
Are they ever called?
