### ISSUE TITLE
Java syntax broken highlight

### ISSUE THREAD

**Issue by RichyHBM** [gohugoio/hugo#6476]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
</pre>

Hugo Static Site Generator v0.59.1-D5DAB232 windows/amd64 BuildDate: 2019-10-31T15:22:43Z

### Does this issue reproduce with the latest release?
Yes

I am using chroma, or the default in hugo and noticed that upgrading from 0.54 to 0.59.1 has broken highlighting java code.

Here is a before and after of the code I am referring to:

Before: 0.54
![chrome_No3aArXYPk](https://user-images.githubusercontent.com/5472275/68155205-20d07400-ff41-11e9-8dc7-295303be7571.png)

After: 0.59.1
![chrome_ApdI1HlPQw](https://user-images.githubusercontent.com/5472275/68155219-27f78200-ff41-11e9-9b8f-0983804d1f76.png)

**Comment by bep** [comment]
This looks to be an issue with Chroma and I would appreciate if you could create and issue at https://github.com/alecthomas/chroma/issues which is closer to where it needs to be fixed.

**Comment by anthonyfok** [comment]
bep is right: I was able to reproduce the issue with the `chroma` command-line tool, v0.6.8:

    chroma -s monokai --html sample.java

@RichyHBM, I should have let you do the honour, but I got intrigued by this issue that I went ahead and filed this bug at https://github.com/alecthomas/chroma/issues/297, hence this note to you to avoid duplication of work.

Cheers!

**Comment by anthonyfok** [comment]
Special thanks to upstream author of Chroma for another amazing speedy fix  https://github.com/alecthomas/chroma/commit/3aaf3e542f6703b0811a248571839856d4a6de03 (in mere 20 minutes of receiving the report):

> Thanks for the report, fixed!
> 
> For clarity, this bug was in the lexer and existed prior to [bbc59ac](https://github.com/alecthomas/chroma/commit/bbc59ac372bba400f55f0b5b79d33ec0a431842c), it just wasn't visible.

Wow, and Chroma v0.6.9 with the fix has just been released too!  Woohoo!

**Comment by RichyHBM** [comment]
Wowza, great work guys, very speedy!!
