### ISSUE TITLE
Hugo 0.59.1 blogdown:::serve_site() Building sites … WARN 2019/11/06 08:03:58 .File.TranslationBaseName on zero object. Wrap it in if or with: {{ with .File }}{{ .TranslationBaseName }}{{ end }}

### ISSUE THREAD

**Issue by JeffreyRacine** [gohugoio/hugo#6482]
Greetings, and apologies of this is not a Hugo issue but rather some other issue, but it seems to be related to Hugo hence my post.

Using latest Hugo, R 3.6.1, RStudio 1.2.5001 (all latest), latest versions of all R packages. Running macOS Catalina 10.15.1

Static Hugo website was building fine, now getting the following error:

> blogdown:::serve_site()
Building sites … WARN 2019/11/06 08:03:58 .File.TranslationBaseName on zero object. Wrap it in if or with: {{ with .File }}{{ .TranslationBaseName }}{{ end }}

                   | EN   
+------------------+-----+
  Pages            |  18  
  Paginator pages  |   0  
  Non-page files   |   1  
  Static files     | 435  
  Processed images |   0  
  Aliases          |   3  
  Sitemaps         |   1  
  Cleaned          |   0  

Total in 199 ms
To stop the server, run servr::daemon_stop(1) or restart your R session
Serving the directory /Users/jracine/blogdown/static-hugo-site at http://127.0.0.1:4321

I am unsure where to start, whether this is a Hugo issue, blowdown issue, or otherwise, but pointers would be appreciated. 

Site can be found at https://github.com/JeffreyRacine/static-hugo-site

Thanks!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
