### ISSUE TITLE
Allow dict to create nested structures

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6497]
I'm working on documentation for the revised "markdown etc." and thought I would save some time by code generation. Which would be exellent had it not been for Hugo's limited map support.

What I would want is something ala:

```
{{ $configSection := index $.Site.Data.docs.config $sections }}
{{ $config := dict $sections $configSection }}
```

The `$sections` above is a string slice and would make sure that I could present the docs on the correct level in a "copy pastable" friendly version.

**Comment by regisphilibert** [comment]
> The $sections above is a string slice

Not sure to understand but it seems we're using parsed data as key. Could we also do:

```
{{ $config := dict "greeting.french" "bonjour" }}
```

**Comment by bep** [comment]
Your construct is very ambiguous. Assuming that "." is always used as a separator will not work.

I may have another idea, though. Will be back in a minute ...

**Comment by bep** [comment]
If we allow a map to be passed in as the (optional) first argument, we could do something ala:

```
{{ $config := dict "config" dict }}
{{ $config = $config | dict "markup" dict }}
```

**Comment by regisphilibert** [comment]
Not sure to follow all those `dicts`... What would be the data structure of`$config`  in the end? Also pipe argument order always confuses me, but wouldn't`$config` end up being the last argument of your piped `dict` on the second line, or am I unpiping it wrong?
```
{{ $config := dict "config" dict }}
{{ $config = dict "markup" dict $config }}
```

**Comment by bep** [comment]
My example was slightly wrong:

```
{{  $config := dict }}
{{ $root := dict "config" $config }}
{{ $config = $config | dict "markup" dict }}
```

Which I guess I with the current Hugo could write as:

```
{{  $config := dict "markup" dict }}
{{ $root := dict "config" $config }}
```
But that is not possible to do in a loop.

I guess it boils down to this line:

```bash
{{ $config = $config | dict "markup" "value" }}
```

Which, when thinking about it, could be rewritten as:

```bash
{{ $config = $config | merge (dict "markup" "value" )}}
```

OK, I'll try to implement the docs changes with the above and see if that works.

**Comment by bep** [comment]
OK; so I managed to get my code toggle shortcode change working with this construct:

```bash
{{ $sections := (split . ".") }}
{{ $configSection := index $.Site.Data.docs.config $sections }}
{{ $root := dict }}
{{ $section := "" }}
{{ range $sections }}
{{ $section = . }}
{{ $root = dict $section $root }}
{{ end }}
{{ $code = $root | merge (dict $section $configSection) }}
```

Not particularly simple ... I suspect that my initial suggestion (first comment) was the most sensible one, but I will let this one linger ....

**Comment by regisphilibert** [comment]
I use merge a lot for building dynamic maps within loops, but I found it takes a toll on build time. `Scratch.SetInMap` is way faster.

As an aside: If you're interested in improving overall Hugo handling of data, I'd love to dig up this old thing: https://github.com/gohugoio/hugo/issues/5604

**Comment by bep** [comment]
>If you're interested in improving overall Hugo handling of data

Interested maybe, time, no.

**Comment by bep** [comment]
So, I deleted my "suggested approach" above -- I just couldn't get it right. I'm a little bit tired, but it shows that it's much harder than it should.

I have a patch ready that allows string slices as keys in `dict`, which makes the above construct much simpler:

```bash
{{ $sections := (split . ".") }}
{{ $configSection := index $.Site.Data.docs.config $sections }}
{{ $code = dict $sections $configSection  }}
```

**Comment by regisphilibert** [comment]
I'm guessing here because not sure what the value of `.` or `$.Site.Data.docs.config` is, but first arg is a slice of strings representing keys and second is a slice of whatever representing values.

Pending they both have an equal numbers of item, key/value pairs are created by "paralelling" the two slices?

**Comment by regisphilibert** [comment]
Scrath the above, I understood by reading https://github.com/gohugoio/hugo/pull/6500
