### ISSUE TITLE
Passing in a variable into a with operator

### ISSUE THREAD

**Issue by mcoleman-renovation** [gohugoio/hugo#6498]
### What version of Hugo are you using (`hugo version`)?

<pre>
v0.58.3
</pre>

### Does this issue reproduce with the latest release?

Yes

When I try to execute this code: 
`
{{ with .selections .selectedColor }}
{{ end }}
`

I get this error: 
`
Failed to render pages: render of "page" failed: "/Users/milescoleman/Documents/Projects/bb-amp/bb/themes/bb-amp/layouts/product/basic.html:1402:15": execute of template failed: template: product/basic.html:1402:15: executing "product/basic.html" at <.selections>: selections is not a method but has arguments
`

According to the documentation at https://gohugo.io/templates/introduction/#example-2-with-else, I should be able to insert have an argument along with the collection. I need to pass in the .selectedVariable because I need the `.` rebinding functionality.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
