### ISSUE TITLE
'hugo config' does not respect '--environment' swtch

### ISSUE THREAD

**Issue by frerich** [gohugoio/hugo#6503]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.59.1/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

### How To Reproduce

1. Create a new project:
    ```
    $ hugo new site sample
    [...]
    $ cd sample
    ```

2. Create two configuration files for two environments; define the same param key in each configuration file:
    ```
    $ mkdir -p config/production config/myenv
    $ cat > config/production/config.toml << EOF
    [params]
    mysetting = "production_value"
    EOF
    $ cat > config/myenv/config.toml << EOF
    [params]
    mysetting = "myenv_value"
    EOF
    ```

3. Use `hugo config` to get the value of the `mysetting` parameter in the `myenv` environment:
    ```
    $ hugo config --environment myenv | grep mysetting
    ```

### Expected Behaviour

Print just one line indicating that the `mysetting` parameter assumed the value `myenv_value`.

### Observed Behaviour

A line is printed giving the value of the `mysetting` parameter as defined in the _production_ environment:

```
params = map[mysetting:production_value]
```

**Comment by johnelliott** [comment]
I see this too. The config command also doesn't print the same values that are used when the build runs. For example `hugo -e staging config` contains the incorrect baseURL used in generating the build output for that environment when running `hugo -e staging`.

**Comment by frerich** [comment]
For what it's worth, I can reproduce this in Hugo v0.60.0, too.

**Comment by zbayoff** [comment]
having the same issue on Hugo Static Site Generator v0.63.1-CE9ACEB7 darwin/amd64 BuildDate: 2020-01-23T20:10:12Z
