### ISSUE TITLE
livereload injection should not use document.write

### ISSUE THREAD

**Issue by dashdashzako** [gohugoio/hugo#6507]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.58.3
</pre>

### Does this issue reproduce with the latest release?

Yes

### My setup

This seems to affect at least Chrome MacOS v78.0.3904.97, I have not tested other configurations.

### Description of the problem

In 2016, Google had written an article called ["Intervening against `document.write()`"
](https://developers.google.com/web/updates/2016/08/removing-document-write).

Unfortunately, Hugo livereload [uses this function](https://github.com/gohugoio/hugo/blob/2fc0abd22a37d90b6f1032eef46191a7bddf41bd/transform/livereloadinject/livereloadinject.go#L31), and warnings are being shown in Chrome .

![Google Chrome console screenshot](https://user-images.githubusercontent.com/34937905/68868314-9e417480-06f7-11ea-953f-e7154b7cc1c4.png)

### Possible solutions

As stated in the Google article:

> it might be possible for you to add an `async` attribute to the script element, or for you to add the script elements with DOM API's like `document.appendChild()` or `parentNode.insertBefore()`

Any of these workarounds would be rather easy to add to the injection code.

**Comment by davidsneighbour** [comment]
No issues on browsers on Ubuntu 19.10. Loading `hugo server` site with `localhost:1313` does not bring up any warnings or errors. There might be more to the explicit configuration where Chrome blocks than just "document.write()" in use. I am using (latest) Chrome 78 here.

The linked article references issues with slow networks and document.write being disabled on slow network connections. I don't see how the use of livereload is something that can end up on a slow connection?

**Comment by dashdashzako** [comment]
The warning message given by the browser is very minimalist and doesn't do much beside what is in the screen capture above. The articles don't really help either, and local connection seems pretty much the opposite of slow 🤔 

May be the Chrome team is expanding its `document.write` policy to other kind of connection, but I found no documentation anywhere talking about it.

This is the kind of ticket I could close saying "works on my setup, closing", but at least it may serve as reference if someone encounters the same problem 😄

**Comment by davidsneighbour** [comment]
I wouldn't close it, but do you use a configuration other than localhost:1313? maybe a local ip address or a local hostname that is configured via /etc/hosts?

**Comment by dashdashzako** [comment]
@davidsneighbour I'm updating the issue, there were problems due to my hugo site configuration.

However, if Chrome doesn't block the script, it still shows a warning on MacOS version 78.0.3904.97.

My apologies for the badly reported problem.

**Comment by bep** [comment]
We have all of the information ready at build time (static), so I see no reason to use document.write or other client side techniques.
