### ISSUE TITLE
Allow for empty content directory

### ISSUE THREAD

**Issue by lucperkins** [gohugoio/hugo#6508]
Although the primary, "sweet spot" use case of Hugo is for large sites, I often work on sites that are just a single page (or start out as a single page and then grow larger later on). It may seem a bit silly to use Hugo for that, but I often build single-page sites that make heavy use of the `data` directory, Hugo Pipes, live reloading, and other Hugo features that I'd prefer not to have to reimplement in Webpack/Parcel/`$OTHER_JS_FRAMEWORK`.

And I suspect that I'm not alone in using Hugo this way. It'd be nice to be able to build single-page sites without putting a `.gitkeep` file in the `content` directory just to build the site successfully.

**Comment by bep** [comment]
I think this is fixed in a recent Hugo (I rewamped this logic when I did the modules logic).

I just did this:

```bash
dev/go/dump
▶ mkdir testsite

dev/go/dump
▶ cd testsite

go/dump/testsite
▶ touch config.toml

go/dump/testsite
▶ hugo
Building sites … WARN 2019/11/14 18:40:19 found no layout file for "HTML" for "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/11/14 18:40:19 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/11/14 18:40:19 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN
+------------------+----+
  Pages            |  3
  Paginator pages  |  0
  Non-page files   |  0
  Static files     |  0
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Total in 14 ms
```

**Comment by lucperkins** [comment]
@bep You're right! AFAICT this is now fixed. Thanks a lot, Bjørn. I was using 0.55.* and assumed that was recent enough that this wouldn't have changed, but great to see it.
