### ISSUE TITLE
Enable left-pane TOC (sidebar) design via config .toml

### ISSUE THREAD

**Issue by anindyo** [gohugoio/hugo#6512]
Left-pane navigation (aka left-pane TOC, sidebar) can be designed (topic hierarchy/nesting) only via metadata in each topic .md file. Only the top-nav menu items can be defined and configured in the config.toml file. This make file/structure maintenance very expensive. File addition, file deleting, and content re-organization will call for updating multiple files in a particular content subdirectory. Enabling the config.toml file (or any other central/global file) to decide the left-pane nesting will make maintenance much easier.

**Comment by peaceiris** [comment]
You mean [gohugoio/hugoDocs](https://github.com/gohugoio/hugoDocs)? If yes go to that repository.
