### ISSUE TITLE
Invalid escape code in ld+json script tag

### ISSUE THREAD

**Issue by napuzba** [gohugoio/hugo#6524]
- - -
**What version of Hugo are you using (`hugo version`)?**
Hugo Static Site Generator v0.59.1/extended windows/amd64 BuildDate: unknown

**Does this issue reproduce with the latest release?** 
Yes
- - -
Hugo generate invalid JSON in ld+json script tag when escaping Unicode/special character.

When [validating](https://search.google.com/structured-data/testing-tool/u/0/) you get the error **Bad escape code \x**

The expected escape code for JSON is **\u0000**
- - -
## How to produce

**content/_index.md**
<pre>
---
layout: sample
---
</pre>
**layouts/_default/ sample.html**
<pre>
{{ $title := "a & b" }}
<script type="application/ld+json">{"@type":"WebPage","headline":"{{$title}}"}</script>
</pre>

**output**
<pre>
<script type="application/ld+json">{"@type":"WebPage","headline":"a \x26 b"}</script>
</pre>

**expected output**
<pre>
<script type="application/ld+json">{"@type":"WebPage","headline":"a \u0026 b"}</script>
</pre>

**Comment by saper** [comment]
Probably similar/related to https://github.com/gohugoio/hugo/issues/6695

**Comment by moorereason** [comment]
Closing as duplicate of #6695
