### ISSUE TITLE
Data templates to allow other URL sources than JSON or CSV, for example RSS

### ISSUE THREAD

**Issue by Yannovitch** [gohugoio/hugo#6536]
I really would like to have a similar functionnality to https://www.gatsbyjs.org/packages/gatsby-source-rss-feed/?=rss
What I'm trying to achieve is that, using a webhook or a cron job, when a new item appears in one of my other website, it rebuilds my static Hugo website with a new post displayed in one of the section, linking to the new item on the other website.
I can't force all of my websites to output JSON. For example, I would like to use my Shaarli instance, which output either RSS or REST. Same goes for external website feeds, ...

Many thanks !
Y

**Comment by Yannovitch** [comment]
@bep What do you think of this proposal ?

**Comment by bep** [comment]
Pretty sure we support this already, but you should ask at the forum.

**Comment by Yannovitch** [comment]
@bep https://discourse.gohugo.io/t/data-templates-with-other-sources-than-json-feed/22182

**Comment by Yannovitch** [comment]
@bep Could you check the aforementioned forum post, as you wrote that Hugo support this already, please ?
