### ISSUE TITLE
summaryLength & .Summary results with Goldmark

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#6541]
### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.60.0-DEV
</pre>

### Does this issue reproduce with the latest release?
No, but possibly it will in the next one.

----

In a project's config if I have:
```
summaryLength = 10
```

And call it like so in a template:

```
<meta name="description" content="="{{ .Summary }}" />
```

I am getting more than 10 words and also line breaks are rendered i.e. `\n` or `\r`

**Comment by bep** [comment]
>I am getting more than 10 words 

I don't think that's anything special/new. We don't cut mid-sentence.

**Comment by onedrawingperday** [comment]
Ok.
