### ISSUE TITLE
Broken taxonomy list in a single page template because of some characters

### ISSUE THREAD

**Issue by Vimux** [gohugoio/hugo#6546]
## Briefly

Tag list (or any other taxonomy list) in a single page don't show some page tags because of urlized characters.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.60.0-F2DEA9B0 darwin/amd64 BuildDate: 2019-11-27T10:09:53Z
</pre>

**Other tested versions:**

<pre>
Hugo Static Site Generator v0.54.0-B1A82C61 darwin/amd64 BuildDate: 2019-02-01T09:40:48Z
Hugo Static Site Generator v0.48 darwin/amd64 BuildDate: 2018-08-29T06:33:08Z
</pre>

### Reproduction steps

1. Use current [Example: List Tags in a Single Page Template](https://gohugo.io/templates/taxonomy-templates/#example-list-tags-in-a-single-page-template) as a tag list template:

```
{{ $taxo := "tags" }}
<ul id="{{ $taxo }}">
    {{ range .Param $taxo }}
        {{ $name := . }}
        {{ with $.Site.GetPage (printf "/%s/%s" $taxo ($name | urlize)) }}
            <li><a href="{{ .Permalink }}">{{ $name }}</a></li>
        {{ end }}
    {{ end }}
</ul>
```

2. Add tag "Révolution française" to any post:

```yaml
tags:
  - "Révolution française"
```

### Actual results:

Empty tag list.

### Expected results:

Tag list with a clickable tag.

### Additional notes:

This is happens because .GetPage function assume to get string like:

```
/tags/révolution-française
```

But, because of `urlize`, we have string like:

```
/tags/r%C3%A9volution-fran%C3%A7aise
```

I have two concerns about this:

1. This is expected .GetPage behavior?
1. If answer is yes, then `anchorize` instead of `urlize` could solve this problem for all predicted use cases or not? It works, but maybe this can cause some potential side effects?

I don't know it's a .GetPage or Hugo Docs problem, anyway, this needs some action or clarification.

**Comment by reuixiy** [comment]
My temporary workaround is to use [`urls.Parse`](https://gohugo.io/functions/urls.parse/) to decode URLs, then you can get the page...

```go
{{ $taxo := "tags" }}
<ul id="{{ $taxo }}">
    {{ range .Param $taxo }}
        {{ $name := . }}
        {{ $url := urls.Parse ($name | urlize) }}
        {{ $path := $url.Path }}
        {{ with $.Site.GetPage (printf "/%s/%s" $taxo $path) }}
            <li><a href="{{ .Permalink }}">{{ $name }}</a></li>
        {{ end }}
    {{ end }}
</ul>
```

BTW, you won't have this problem if you use `.Site.Taxonomies.tags` or `.Data.Terms`...

See also:

1. https://discourse.gohugo.io/t/how-decode-urls-in-hugo/7549/6
2. https://github.com/reuixiy/hugo-theme-meme/blob/master/layouts/partials/post-tags.html
3. https://github.com/reuixiy/hugo-theme-meme/blob/master/layouts/partials/tag-cloud.html
4. https://github.com/reuixiy/hugo-theme-meme/blob/master/layouts/partials/taxonomy.html

**Comment by Vimux** [comment]
@reuixiy,

Thank you. Good suggestion. I think about [anchorize](https://gohugo.io/functions/anchorize/) as an [urlize](https://gohugo.io/functions/urlize/) replacement in this particular case. I'm still not sure that this will work for all possible cases.

> BTW, you won't have this problem if you use `.Site.Taxonomies.tags` or `.Data.Terms`...

And this is the main reason why I created the issue here. I'm not a hundred percent sure that this is just Docs problem and I want to get some clarification about this. However, it doesn't negate the fact that Hugo Docs contains mislead section about very popular thing right now.

**Comment by reuixiy** [comment]
Also note that `anchorize` is different from `urlize`, e.g.

```
foo(bar) | anchorize   ->   foo-bar
foo(bar) | urlize      ->   foobar
```

**Comment by gcushen** [comment]
Duplicate of #5687?
