### ISSUE TITLE
Code fence theming not applying to some languages

### ISSUE THREAD

**Issue by aletson** [gohugoio/hugo#6547]
### What version of Hugo are you using (`hugo version`)?

0.60.0

### Does this issue reproduce with the latest release?

Yes

I have my Hugo site configured to highlight code fences with the following options:

```
"markup": {
    "highlight": {
      "style": "solarized-dark"
    }
  },
```

 This works on most code fences, but I noticed on ` ```conf` code fences it is not working and is displaying just plain preformatted text (not themed at all). This is one of the ones listed as "supported" in the syntax highlighting section of the docs; if you use an unsupported language it appears _also_ not to theme that code fence but I'm not sure if that's by design or not. I tried to switch themes but this did not seem to make a difference.

If I go back to 0.59.1 and re-configure my config.json with 

```
"pygmentsCodeFences": true,
  "pygmentsStyle": "solarized-dark",
```

all of these code fences still don't have syntax highlighting, which I'd expect, but they are still themed, which is the behaviour I would expect (all code fences at least have the theme, even if the syntax highlighter doesn't know what to do).

I'm not sure how to word this issue more clearly, so please let me know if there's anything else I can answer.

**Comment by bep** [comment]
>but they are still themed

I'm not sure what you mean by "themed"? Do you expect even made-up languages (e.g. "foo") to be "solarized-dark" in your example? Was that how it behaved in 0.59?

**Comment by aletson** [comment]
Right, sorry, this was not clear. That was the behaviour in 0.59 - no highlighting, but the base background and text colors for the style did apply.

**Comment by bep** [comment]
OK; I suspect this is the same or related to https://github.com/gohugoio/hugo/issues/6565

**Comment by aletson** [comment]
Confirmed; after upgrading to 0.61 and setting `pygmentsCodefencesGuessSyntax` to true in my config, code-fenced blocks where a language is not specified or where the specified language was not working previously now appear with the specified style in config.json  and no highlighting.
