### ISSUE TITLE
\ (Forced line feed) may be ignored

### ISSUE THREAD

**Issue by fu-sen** [gohugoio/hugo#6549]
### What version of Hugo are you using (`hugo version`)?

<pre>
PS (PowerShell)> hugo version
Hugo Static Site Generator v0.60.0-F2DEA9B0 windows/amd64 BuildDate: 2019-11-27T10:11:05Z
</pre>

### Does this issue reproduce with the latest release?
Yes

### Problem description

There is this Markdown as a test:
```
**test**\
test**test**\
**test**test\
test**test**
```

In Hugo v0.60.0, the output is as follows:
![スクリーンショット 2019-11-28 13 33 11](https://user-images.githubusercontent.com/5434159/69777498-e2e30a80-11e3-11ea-9b74-3a13e61f6907.jpg)

Some \ are not converted to <br>:

```
<p><strong>test</strong>\
 test<strong>test</strong>\
 <strong>test</strong>test<br>
 test<strong>test</strong></p>
```

This problem can be avoided by inserting a space before the \:
```
**test** \
test**test** \
**test**test \
test**test**
```

Since v0.59.1 was handled normally, this may require some Markdown modifications.

**Comment by yuin** [comment]
goldmark author here, I've fixed the issue and released the new version.

**Comment by fu-sen** [comment]
Thank you for the quick fix!
I updated to Hugo v.0.60.1 and confirmed this fix.
