### ISSUE TITLE
Support footnote return links

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#6551]
`Version 0.60.0; yes, latest Hugo version is used.` 

Hugo 0.60.0 + Gold is just great! Thank you!

The footnote extension seems to not support return links although they are part of the [PHP Markdown extra](https://michelf.ca/projects/php-markdown/extra/#footnotes).

It is difficult for readers to navigate between the text and footnotes.

Is there a way to enable (and modify) footnote return links?

Thank you!

**Markdown:**

```
That's some text with a footnote.[^1]

[^1]: And that's the footnote.
```

**Output:**

```
…
<section class="footnotes" role="doc-endnotes"><hr><ol><li id="fn:1" role="doc-endnote"><p>And that's the footnote.</p></li></ol></section>
```

**Comment by bep** [comment]
I agree, but I think a fix fits more natural into Goldmark (so more people can appreciate it).

Can you create an issue here: https://github.com/yuin/goldmark/issues

Link back to this issue so we can track it.

**Comment by yuin** [comment]
goldmark author here, I've added back links to the footnote and released new version.
