### ISSUE TITLE
Regression in 0.60.0 for $headless ?

### ISSUE THREAD

**Issue by jensamunch** [gohugoio/hugo#6552]
### What version of Hugo are you using (`hugo version`)?
Moving from 0.59.1 to 0.60.1 quietely (no warnings) stopped showing our headless content.

Here's an example of the code that outputs nothing with 0.60.0

```
<section class="customer-logos section">
	<div class="container">
		<div class="customer-logos-inner section-inner has-top-divider">
			<h2 class="section-title text-center mt-0">{{ .Site.Params.logos }}</h2>
			<div class="customer-logos-wrap is-revealing">
				{{ $headless := .Site.GetPage "page" "headless/customer-logos" }}
				{{ $reusablePages := $headless.Resources.Match "*" }}
				{{ range $reusablePages }}
				<div class="customer-logo">
					<a href="{{ .Params.link }}" target="_blank">
						{{ with .Params.image }}
						{{ $original := resources.Get .  }}
						{{ $coverScaled2x := $original.Resize "x160 center" }}
						{{ $coverScaled1x := ($coverScaled2x.Resize "x80") }}
						<img srcset="{{ $coverScaled1x.RelPermalink }} 1x, {{ $coverScaled2x.RelPermalink }} 2x" src="{{ $coverScaled1x.RelPermalink }}" width="{{ $coverScaled1x.Width }}" height="{{ $coverScaled1x.Height }}">
						{{ end }}
					</a>
				</div>
				{{ end }}
			</div>
		</div>
	</div>
</section>
```

**Comment by jensamunch** [comment]
![image](https://user-images.githubusercontent.com/1650140/69806162-23d62180-11da-11ea-84b6-bf2c835b40e3.png)

**Comment by jensamunch** [comment]
![image](https://user-images.githubusercontent.com/1650140/69806179-2f294d00-11da-11ea-8485-3ff8dab1453f.png)

**Comment by jensamunch** [comment]
![image](https://user-images.githubusercontent.com/1650140/69806204-3fd9c300-11da-11ea-8291-ee497765e67b.png)

**Comment by onedrawingperday** [comment]
This seems related to what has already been reported in the forum about HTML with indentation contained in shortcodes and partials being wrapped in `pre` and `code` elements.

https://discourse.gohugo.io/t/0-60-0-goldmark-html-indentation-in-partial-shortcode-wrapped-in-pre-code/22019/

I have already advised @divinerites to report this bug here.

@jensamunch as a workaround please remove the indentation from the HTML and let us know..

**Comment by jensamunch** [comment]
Ok will try. Super confusing to me since this is a partial template. I wouldn’t expect Hugo to be opinionated about my formatting there. Only in markup. 

Isn’t it normal to beautify HTML code for readability?

**Comment by divinerites** [comment]
Yep @jensamunch it is exactly my thought (written in the #6553).

A Workaround is flatting all HTML in partials called by shortcode.

**Comment by jensamunch** [comment]
Does atom have a plugin that allows me to flatten all files? Seems like a lot of manual work. Hmm I think I’ll Stay on Black Friday

**Comment by jensamunch** [comment]
Hmmm. This doesn't seem to be the same issue. Now back at laptop and there is still no HTML output from flat partial:

```
<section class="customer-logos section">
<div class="container">
<div class="customer-logos-inner section-inner has-top-divider">
<h2 class="section-title text-center mt-0">{{ .Site.Params.logos }}</h2>
<div class="customer-logos-wrap">
{{ $headless := .Site.GetPage "page" "headless/customer-logos" }}
{{ $reusablePages := $headless.Resources.Match "*" }}
{{ range $reusablePages }}
<div class="customer-logo">
<a href="{{ .Params.link }}" target="_blank">
{{ with .Params.image }}
{{ $original := resources.Get .  }}
{{ $coverScaled2x := $original.Resize "x160 center" }}
{{ $coverScaled1x := ($coverScaled2x.Resize "x80") }}
<img srcset="{{ $coverScaled1x.RelPermalink }} 1x, {{ $coverScaled2x.RelPermalink }} 2x" src="{{ $coverScaled1x.RelPermalink }}" width="{{ $coverScaled1x.Width }}" height="{{ $coverScaled1x.Height }}">
{{ end }}
</a>
</div>
{{ end }}
</div>
</div>
</div>
</section>
```

**Comment by bep** [comment]
>Stay on Black Friday

That's tomorrow :-)

This seems to be a bug in Goldmark -- I will take that with him. He is very quick in fixing stuff...

I'm closing this in favour of #6553 .

A general tip about shortcodes and HTML  is that in some cases it can make sense to use the `{{<` separator, which makes sure that the Markdown engine does not mess with  it.

**Comment by jensamunch** [comment]
Actually wait @bep - this is not the same issue.

My headless folder was called "customer-logos". When I changed it to "customerlogos" everything worked again. 

No need to flatten the HTML. So unrelated.

**Comment by jensamunch** [comment]
I'm super confused. It's randomly working and not working...I'm just changing file names and formatting..I can't make any sense of a pattern.

**Comment by bep** [comment]
The bug is that the headless bundle is, for some reason, identified as an orphaned section and removed.

I will fix this, but the workaround would be to not put these bundles in the root, but rather in `posts/mybundle` or something.

**Comment by bep** [comment]
>I'm super confused. It's randomly working and not working...

It's called parallelism ... I found the bug and will fix it soon.
