### ISSUE TITLE
--enableGitInfo throws git error of unknown option -C

### ISSUE THREAD

**Issue by tobiasehlert** [gohugoio/hugo#6554]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.60.0-DEV/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Trying to run the --enableGitInfo flag, but then the hugo server doesn't want to start.

<pre>
Building sites … ERROR 2019/11/29 01:00:37 Failed to read Git log: Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
</pre>

#### Running following Git version

<pre>
$ git version
git version 1.8.3.1
</pre>

**Comment by pamubay** [comment]
Please update your Git.
