### ISSUE TITLE
Links get incorrectly linkified twice

### ISSUE THREAD

**Issue by frerich** [gohugoio/hugo#6557]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.60.0-F2DEA9B0/extended darwin/amd64 BuildDate: 2019-11-27T10:16:12Z
</pre>

### Does this issue reproduce with the latest release?

Yes.

### How to reproduce

1. Create a new site

    ```
    $ ./hugo-0.60.0 new site mysite
    Congratulations! Your new Hugo site is created in /tmp/mysite.
    ...
    $ cd mysite
    ```
2. Create a content file with two links; one in plain text and one using the `[]()` markup:

    ```
    $ echo 'Go to [http://www.example.com](www.example.com) or http://www.example.com.' > content/_index.md
    ```

3. Create a trivial layout for the home page:

    ```
    $ echo '{{ .Content }}' > layouts/index.html
    ```

4. Build the web page

    ```
    $ hugo
    ```

### Expected result

The same HTML code was was produced with Hugo v0.59.1 should be generated, i.e. I expect:

```
$  cat public/index.html
<p>Go to <a href="www.example.com">http://www.example.com</a> or <a href="http://www.example.com">http://www.example.com</a>.</p>
```

Note that both links yield the same HTML.

### Observed result

With Hugo 0.60.0, the first link is marked up twice, i.e. I get an extra `<a>` element:

```
$ cat public/index.html
<p>Go to <a href="www.example.com"><a href="http://www.example.com">http://www.example.com</a></a> or <a href="http://www.example.com">http://www.example.com</a>.</p>
```

### Additional notes

The issue can be mitigated somewhat by disabling the `markup.goldmark.extensions.linkify` option. However, this _also_ disabled linkification of normal links, i..e you get

```
$ cat public/index.html
<p>Go to <a href="www.example.com">http://www.example.com</a> or http://www.example.com.</p>
```

**Comment by bep** [comment]
See https://github.com/gohugoio/hugo/issues/6557
