### ISSUE TITLE
.TableOfContents does not work anymore

### ISSUE THREAD

**Issue by frerich** [gohugoio/hugo#6559]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.60.0-F2DEA9B0/extended darwin/amd64 BuildDate: 2019-11-27T10:16:12Z
</pre>

### Does this issue reproduce with the latest release?

Yes

### How to reproduce

1. Create a new Hugo site

    ```
    $ hugo new site mysite
    Congratulations! Your new Hugo site is created in /tmp/mysite.
    ...
    $ cd mysite
    ```

2. Create a simple homepage document with just three captions:

    ```
    $ cat > content/_index.md << EOF
    heredoc> # Section 1
    heredoc>
    heredoc> Foo
    heredoc>
    heredoc> # Section 2
    heredoc>
    heredoc> Foo
    heredoc>
    heredoc> # Section 3
    heredoc>
    heredoc> Foo
    heredoc> EOF
    ```
3. Create a home page layout which prints the table of contents:

       $ echo '{{ .TableOfContents }}' > layouts/index.html

4. Build the web site

       $ hugo

### Expected behaviour

I expect an `index.html` document with a table of contents providing links to three headers. This is what Hugo v0.59.1 produces:

    $ cat public/index.html
    <nav id="TableOfContents">
    <ul>
    <li><a href="#section-1">Section 1</a></li>
    <li><a href="#section-2">Section 2</a></li>
    <li><a href="#section-3">Section 3</a></li>
    </ul>
    </nav>

### Observed behaviour

No list items are generated in the table of contents. This is what Hugo v0.60.0 produces:

    $ cat public/index.html
    <nav id="TableOfContents"></nav>

**Comment by frerich** [comment]
This issue appears to be specific to the `goldmark` format. Specifying

```
---
markup: blackfriday
---
```

At the top of `_index.md` yields a correct table of contents.

**Comment by bep** [comment]
I think you will find that we have improved the TableOfContents in Hugo. The default config starts the ToC at h2, which is the most common case. But you can change it in your config.toml:

```toml
[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2
```

https://gohugo.io/getting-started/configuration-markup/#table-of-contents

**Comment by frerich** [comment]
I see. Now I have to decide whether I'd like to adjust my site configuration to restore the previous behaviour (i.e. starting the ToC at level 1) or whether it would be more sensible to go through all Markdown documents and bump the header level from `n` to `n+1`.

**Comment by bep** [comment]
I think a common (and probably also recommended for SEO etc.) pattern is to have 1 H1 only per page, and that fits naturally in the template, e.g. `single.html`, using the `.Title` on the page.

**Comment by frerich** [comment]
A quick search-and-replace also came to my mind - alas, our web site contains a few hundred code examples with C++ source code, which happens to use a leading `#` character for preprocessor directives :-/).
