### ISSUE TITLE
Replacement for hrefTargetBlank in Goldmark?

### ISSUE THREAD

**Issue by netmute** [gohugoio/hugo#6562]
**Off topic rant:** I'm so frustrated by the change to Goldmark. A workflow that worked flawlessly for years is now broken in all kinds of surprising ways. I can't even change back to Blackfriday, because that's broken too in 0.60 (that's another issue...)

**On topic:** How can we replicate the functionality of Blackfridays `hrefTargetBlank` in Goldmark?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

And please keep in mind that this is an open source project. A CommonMark compliant Markdown engine has been one of the most requested features in Hugo. And people have spent countless hours of their off work hours time to make this happen and make this transition as smooth as possible. Think about that before you load off your frustrations about not having "links open in a new Window".
