### ISSUE TITLE
css minify loses space after )

### ISSUE THREAD

**Issue by mschoeffmann** [gohugoio/hugo#6563]
### Description
Since I updated from 0.59.1 to 0.60.1, the "| minify" command removes important spaces from CSS:

STYLE TEMPLATE:
<pre>
{{ $cssSite := resources.Get "css/_site.css" | minify }}
{{ $cssQueries := resources.Get "css/_queries.css" | minify }}
{{ $style := slice $cssSite $cssQueries | resources.Concat "css/bundle.css" | fingerprint }}
</pre>

ORIGINAL CSS:
`background: rgba(109, 109, 109, 1) url('/img/slide-home.jpg') no-repeat center center;`

MINIFIED TO:
`background:#6d6d6durl(/img/slide-home.jpg)no-repeat 50%;`

In the minified version is a space missing right after the color and the url - it looks like a missing space after a ")".
The result `#6d6d6durl` results in no background image displayed. And i can imagine the missing space in `)no-repeat` can cause confusion, too?

 ### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.60.1/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by akshaybabloo** [comment]
This is also breaking the AMP pages

**Comment by akshaybabloo** [comment]
Could be fixed in #6756

**Comment by apoorvmote** [comment]
It did not fix in Hugo version 0.68.3

`The mandatory text inside tag 'head > style[amp-boilerplate]' is missing or incorrect.`

Amp validation is still breaking

**Comment by tdewolff** [comment]
I've tested the original issue and this is not an issue (anymore) in `minify`.

**Comment by mschoeffmann** [comment]
Looks fixed now...
`Hugo Static Site Generator v0.76.3/extended darwin/amd64 BuildDate: unknown`
