### ISSUE TITLE
rich text editor for hugo

### ISSUE THREAD

**Issue by msudgh** [gohugoio/hugo#6564]
I'm thinking about developing a rich text editor for Hugo, It made Hugo more mature with a unique feature which allows people to write their thoughts easier and simpler.

Features:

- Markdown/Wysiwyg Editor with live preview
- Autosave posts
- Draft
- Github Integration

Is there any objective for this idea in Hugo roadmap?

**Comment by bugsysop** [comment]
Maybe open a topic in the discussion forum, as this is _not realy_ an Hugo issue...

**Comment by msudgh** [comment]
No problem, Thanks.
