### ISSUE TITLE
0.60.1 Goldmark issue regarding markdown and shortcodes

### ISSUE THREAD

**Issue by jeremyf** [gohugoio/hugo#6573]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
=> 0.60.1
</pre>

### Does this issue reproduce with the latest release?

Yes

### The Issue

I have a shortcode for rendering tables consistently:

```go
{{- $caption := .Get "caption" }}
{{- $table_number := .Get "table_number" }}
<div class="table-wrapper">
<a name="table-{{ $table_number }}"></a>
<table {{ with .Get "unstriped" }}class="unstriped" {{ end }}aria-label="Table {{ $table_number }}{{ if $caption}}: {{ $caption }}{{ end }}">
{{- if $caption }}<caption>Table {{ $table_number}}: {{ $caption | markdownify }}</caption>{{- end }}
{{ .Inner | markdownify }}
</table>
</div>
```

I have content that is basically:

```go
{{% table table_number="42" caption="My Table" %}}
<tr>
<td>20</td>
<td>Goblin (Eberron)</td>
<td>[goo.gl/eYjUk9](https://goo.gl/eYjUk9)</td>
</tr>
{{% /table %}}
```

When I have blackFriday enabled, I see HTML that converts the markdown A-tag to a proper HTML a-tag (e.g. `<td><a href="https://goo.gl/eYjUk9">goo.gl/eYjUk9</a></td>`). When I have goldmark enabled, this does not convert (and I end up with a `<td>[goo.gl/eYjUk9](https://goo.gl/eYjUk9)</td>` rendered on the page.

I can continue to use blackFriday but would prefer to use goldmark, and was wondering about expanding the markdown within a shortcode. I'm also encountering a few other oddities that I believe are goldmark related.

This may be related to #6553. Thank you in advance for your time and energy in the project.

**Comment by moorereason** [comment]
I believe this is part of the switch to a CommonMark-compliant renderer.  My understanding of the [CommonMark spec](https://spec.commonmark.org/0.29/#html-blocks) is that markup within a HTML block will be ignored.

Try this instead:

```
{{% table table_number="42" caption="My Table" %}}
<table>
<tr>
<td>20</td>
<td>Goblin (Eberron)</td>
<td>

[goo.gl/eYjUk9](https://goo.gl/eYjUk9)
</td>
</tr>
</table>
{{% /table %}}
```

Should yield:
```
<table>
<tr>
<td>20</td>
<td>Goblin (Eberron)</td>
<td>
<p><a href="https://goo.gl/eYjUk9">goo.gl/eYjUk9</a></p>
</td>
</tr>
</table>
```

I don't know how to render it without the wrapping paragraph tag.  🤷‍♂ Play around with the [CommonMark dingus](https://spec.commonmark.org/dingus/) and see if you can do better than me.

**Comment by bep** [comment]
I would read the CommonMark spec. I doubt that the above construct is in according with that spec, but if it is, please raise an issue on Goldmark issue tracker. We don't have the resources to follow up upstream issues on such defail here.

**Comment by jeremyf** [comment]
Thanks for the follow-up. Cheers! I'll do what I can.
