### ISSUE TITLE
Line number should not be able to be selected

### ISSUE THREAD

**Issue by yuqingc** [gohugoio/hugo#6578]
### What version of Hugo are you using (`hugo version`)?
0.60

### Does this issue reproduce with the latest release?
yes

Line number in code snippets should not be allowed to select. This makes it hard to copy some codes

The css `user-select: none` should be set.
![image](https://user-images.githubusercontent.com/29723652/70121928-921f5600-16aa-11ea-98f4-30fa0228df26.png)

**Comment by bep** [comment]
You can configure the highlighter to use "table mode", which should solve your problem. See the docs.
