### ISSUE TITLE
Subfolder isn't created when there is no _index.md 

### ISSUE THREAD

**Issue by knoobie** [gohugoio/hugo#6583]
### What version of Hugo are you using (`hugo version`)?

Ubuntu 18 / Hugo Static Site Generator v0.60.0 linux/amd64 BuildDate: 2019-11-27T13:07:43Z 

### Does this issue reproduce with the latest release?

Haven't tried.

### Bug Description

I have to provide a _index.md and a index.md in the register folder, otherwise hugo doesn't create the register folder on compilation. Providing both files results in the following warning: "hugo/content/prod/register" have both index.* and _index.* files, pick one."

* When I use both index.md - everything compiles correctly and I "just" get a warning
* When there is only index.md - there is no folder, just a new "register.html" page
* When there is only _index.md - there is a folder "register" but no index.html in the folder

### Structure

/content
├─/prod
├─_index.md
├─about.md
├─...
├───/register
├───_index.md
├───index.md
├───guide.md
├─/ref
├─...
└─/test
├─...

### config.toml

baseURL = ""
uglyurls = true
enableRobotsTXT = false
disableKinds = ["RSS", "sitemap", "section"]
// sadly not working
// disableLanguages = ["en"]
defaultContentLanguage = "prod"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "EN"
  [languages.prod]
    contentDir = "content/prod"
    languageName = "Production"
    publishDir = "public/"
  [languages.ref]
    contentDir = "content/ref"
    languageName = "Ref"
  [languages.test]
    contentDir = "content/test"
    languageName = "Testsystem"

**Comment by bep** [comment]
>When I use both index.md - everything compiles correctly and I "just" get a warning

Both what?

**Comment by knoobie** [comment]
Both (_index.md and index.md) - sorry for the confusion.

**Comment by bep** [comment]
>uglyurls = true

Set this to false and you will get your folder. There is another issue somewhere discussing this, but that is whether we should create folders for sections when uglyurls = true (the opposite of what you want).

**Comment by knoobie** [comment]
Thanks for the idea! Sadly it doesn't create the desired outcome. 

with uglyurls = true we get (everything fine, just weird that we have to use _index.md and index.md in our folder (could be possible that we currently rely on a bug(?):

![image](https://user-images.githubusercontent.com/3968629/70327216-94162000-1836-11ea-800f-5f5122900831.png)

with uglyurls = false we get:

![image](https://user-images.githubusercontent.com/3968629/70327288-c45dbe80-1836-11ea-9208-77fde214ba28.png)
