### ISSUE TITLE
0.60.x goldmark, single backtick end ignore in inline code

### ISSUE THREAD

**Issue by Marthym** [gohugoio/hugo#6584]
The end of backtick inline code was ignored if not followzed by space !

```
`Text`.`other` = `true`
```
produce 
```
<code>Text`.</code>other<code>=</code> true
```
instead of

```
<code>Text</code>.<code>other</code> = <code>true</code>
```
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.60.1-96066756/extended linux/amd64 BuildDate: 2019-11-29T15:03:40Z
</pre>

### Does this issue reproduce with the latest release?

Not reproduce in 0.59.0

**Comment by bep** [comment]
Thanks for the report. This looks like it could be an issue with Goldmark. Could you create an issue at https://github.com/yuin/goldmark/issues and link back to this issue so we could track it?

**Comment by yuin** [comment]
This probably already resolved in https://github.com/yuin/goldmark/commit/ac8e225cd3a73ade37217c9fbd623ea497bb6f78

**Comment by bep** [comment]
Yes.

```
<p><code>Text</code>.<code>other</code> = <code>true</code></p>
```
