### ISSUE TITLE
Watch tailwindcss-config.js at the root of a project 

### ISSUE THREAD

**Issue by neilmispelaar** [gohugoio/hugo#6585]
Hello,

## Request

It would be great if Hugo could watch for changes to the `tailwindcss-config.js` file when it resides at the root of a project and then rebuild the site when changes are made. 

It is a general (though not required) practice to put the `tailwindcss-config.js` file at the root of a project. However, Hugo does not seem to watch for, or respond to changes to this file (when it's saved at the root of the project). 

## Work around: 
When you put the `tailwindcss-config.js` file in the `/assets/css/` folder Hugo does correctly rebuild the site when changes are saved in the file. 

## Problem: 
The problem with this moving the file is that a few other tools I'm using are opinionated and expect to find the `tailwindcss-config.js` file at the root of the project, so moving it has unintended consequences.

## Possible Suggestion: 
Perhaps an additional flag on the `hugo server` to monitor and rebuild the development site on any file changes in the project directory?

**Comment by moorereason** [comment]
A more general feature request would be to allow additional watch locations to be defined in the Hugo config.  There's no way we're going to hardcode a check for `tailwindcss-config.js` into Hugo.

**Comment by neilmispelaar** [comment]
That makes perfect and complete sense!

Perhaps an additional “watch all files in a project” flag added to the server perhaps? 

Or something like “rebuild on any change”

**Comment by bep** [comment]
I think this should be possible as it is. Don't arrest me if it's not working, but it is possible to mount files (not just directories) via the module config. There are some known limitations (I didn't think about mounting files until the Bootstrap project started doing it).

```toml
[module]
  [[module.mounts]]
    source = "tailwindcss-config.js"
    target = "assets/foo/tailwindcss-config.js"
```

It's a little bit of hack since you're not using the `target` for anything.

**Comment by neilmispelaar** [comment]
Awesome, thank you! I will try that as soon as I can and let you know the results.

**Comment by neilmispelaar** [comment]
I tried the adding the `module` code to my config file and hit some build errors which I have included below. Without the `module` code everything builds fine. 

As a work around, if I make any changes to the `tailwind.config.js` file I will just save a space in my css file which will cause a fill rebuild of the CSS and fix things up.

I would still humbly request an additional flag or configuration value to add additional watched locations, but completely understand that this is a really unique scenario and that the vast majority of Hugo users my not ever have a use for this.     

```
ERROR 2019/12/06 14:55:54 render of "section" 
failed: execute of template 
failed: template: _default/list.html:11:38: executing "site/styles" at <partial "site/styles.html" .>: error calling partial: "/Users/neil.mispelaar/Code/CDESG/website/layouts/partials/site/styles.html:18:32": execute of template failed: template: partials/site/styles.html:18:32: executing "partials/site/styles.html" at <postCSS (dict "use" "tailwindcss" "noMap" true)>: error calling postCSS: type map[string]interface {} not supported in Resource transformations
Built in 3 ms
```

**Comment by bep** [comment]
https://discourse.gohugo.io/ is a better place for questions or troubleshootig.
