### ISSUE TITLE
html code in .md files not working

### ISSUE THREAD

**Issue by DiogoFerrari** [gohugoio/hugo#6586]
I have an _index.md file with html code in a folder /content/software/.

I can create links, insert images, etc., using markdown, but the HTML code is ignored when the website is built. For instance:

This works

```
[a link](http://example.com)
```

But this does not even appear in the website as a link

```
<a href="https://example.com">a link</a>
```

Hugo version: Hugo Static Site Generator v0.60.0
OS: Ubuntu 19.04; linux/amd64
Browser/OS: chromium Version 78.0.3904.108

PS: The problem is not the hugo-academic, apparently (see https://github.com/gcushen/hugo-academic/issues/1454#issue-534156425)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
