### ISSUE TITLE
markdownify bug in 0.60 compared to 0.59

### ISSUE THREAD

**Issue by rgr19** [gohugoio/hugo#6587]
I have shortcode that embeds some file to other `.md` file:

```go
{{- $file := ( .Get 0 ) -}}
{{ if (fileExists $file) -}}
{{- ( print "\n```\n FILE BEGIN : " ( $file )  "\n```\n" ) -}}
<div style="border: thin solid black">
{{- ( print "\n" ) -}}
{{- $file | readFile | markdownify -}}
{{- ( print "\n" ) -}}
</div>
{{- ( print "\n```\n FILE END : " ( $file )  "\n```\n" ) -}}
{{ else }}
{{- ( print "\n```\n NO FILE : " ( $file )  "\n```\n" ) -}}
{{- end }}
```

And similar shortocodes that are based on markdownify. But after updating to 0.60.0 from `snap`. My hugo do not render embedded files properly anymore.

### What version of Hugo are you using (`hugo version`)?
0.59 - > 0.60 

### Does this issue reproduce with the latest release?

Yes. Probably issue is with new markdown engine that was introduced in 0.60.

Anyway, good job in keeping backward compatibility in minor versions. Great sense of versioning!

**Comment by satotake** [comment]
@rgr19 
Can you show us a few of `$file` contents, which are not rendered properly with newer Hugo?
