### ISSUE TITLE
Code blocks without language look bad

### ISSUE THREAD

**Issue by h4tr3d** [gohugoio/hugo#6589]
On Hugo version 0.60.1 issue #3699 are back.

When you specify code block without language tag, extern `<div class="highlight">` is missed.

Possible WA: use language tag `text`, but a lot of articles already affected.

### What version of Hugo are you using (`hugo version`)?

0.59.1 -> 0.60.1

### Does this issue reproduce with the latest release?

Yes. Probably issue is with new markdown engine that was introduced in 0.60.

**Comment by h4tr3d** [comment]
Hmm... Seems issue with option `pygmentsCodefencesGuessSyntax = true`. There is not replacement for It in 0.60.1.

**Comment by moorereason** [comment]
Language guessing was reintroduced in #6569 and will be in the upcoming v0.61.0.

**Comment by satotake** [comment]
I checked this is fixed at least with v0.62.0, as @moorereason said, setting `guessSyntax =true` .
@h4tr3d , how about you?

**Comment by h4tr3d** [comment]
@satotake yes, with 0.62 and `guessSyntax=true` work well for me too.

For documentation:
```toml
[markup]
    [markup.highlight]
    guessSyntax = true
```
