### ISSUE TITLE
List pages not added to taxonomies

### ISSUE THREAD

**Issue by SHiLLySiT** [gohugoio/hugo#6590]
### What version of Hugo are you using (`hugo version`)?

<pre>
v0.60.1-96066756 windows/amd64 BuildDate: 2019-11-29T14:57:23Z
</pre>

### Does this issue reproduce with the latest release?
Yes

### Problem Description
List pages (_index.md) that have been added to taxonomies are not appearing in the resulting taxonomy term pages. Additionally if such list pages are the only pages in a taxonomy, the taxonomy term page is not generated at all. According to [the documentation](https://gohugo.io/content-management/taxonomies/#add-taxonomies-to-content):
> Once a taxonomy is defined at the site level, any piece of content can be assigned to it, __regardless of content type or content section__.

This issue as been reported by three people in [this thread](https://discourse.gohugo.io/t/tagged-sections-not-appearing-on-taxonomy-page/22154) and [this thread](https://discourse.gohugo.io/t/rendering-section-pages-in-taxonomies/21988)

I've attached a zip archive of [a barebones project that replicates the problem](https://github.com/gohugoio/hugo/files/3940397/Hugo.zip). However here are the key parts:

Post (single page) tagged with both _PostOnlyTag_ and _ListAndPostTag_.
```
---
title: "My First Post"
date: 2019-12-09T09:24:26-06:00
tags: ["PostOnlyTag", "ListAndPostTag"]
---

My first post
```

List page tagged with both _ListTag_ and _ListAndPostTag_.
```
---
title: "Post List"
tags: ["ListTag", "ListAndPostTag"]
---
```

Screenshot of the file hierarchy:
![Screenshot_239](https://user-images.githubusercontent.com/950984/70448949-c017e800-1a66-11ea-943d-e2222f79751f.png)

Screenshot of http://localhost:1313/tags/ missing _ListTag_ and the post list page under the _ListAndPostTag_.
![Screenshot_240](https://user-images.githubusercontent.com/950984/70448954-c1491500-1a66-11ea-83aa-31fa31c74331.png)

**Comment by afandian** [comment]
This is biting me as well. Any idea if this is a feature regression? Should I expect this to work?

**Comment by gbmhunter** [comment]
It has now also been reported in [this thread](https://discourse.gohugo.io/t/can-you-add-taxonomies-e-g-tags-to-index-md-pages/22320). This issue also impacts me significantly. @bep any word on whether this is a bug or by design?

**Comment by rkunze** [comment]
I'm affected by this as well. A quick `git bisect` shows that the change in behaviour has been introduced with commit 7ff0a8ee9fe8d710d407e57faf1fda43bd635f28.

@bep: Is this intended?

**Comment by gbmhunter** [comment]
@rkunze nice sleuthing!
