### ISSUE TITLE
<dl> tags html rendering broken in 0.60.0

### ISSUE THREAD

**Issue by lapp0** [gohugoio/hugo#6593]
### What version of Hugo are you using (`hugo version`)?

<pre>
0.60.0
</pre>

### Does this issue reproduce with the latest release?
yes

### Issue

Hello, I have a webpage written in markdown which includes html within `<dl>` tags. Two days ago I ran my deployment pipeline, and the `<dl>`-tag html wasn't rendered. I tried redeploying and the job kept failing. 

I saw that none of my code changes could have possibly impacted this, so I looked at the hugo container version history. I was using `registry.gitlab.com/pages/hugo:latest` (0.60.0), published a week ago. So I tried downgrading to the `0.59.0` container and the html within my `<dl>` tags rendered fine.

I don't know what causes this, just that it was broken between 0.59.0 and 0.60.0.

**Comment by bep** [comment]
You should read the release notes for 0.60.

**Comment by lapp0** [comment]
thanks bep, my mistake
