### ISSUE TITLE
Create some lightweight forks of text/template and html/template

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6594]
Note that any changes will only touch the **template execution**, but I suspect that it's interconnected.

While working on the thing I'm working on, I have created a new design for template changes (a dependency graph). All of this was fine and dandy until I came to the `.Render` method. I could probably have pushed that problem to another day, but I have spent a stupid amount of time today bending a working solution together, only to see my benchmarks slow down 20+ %.

I have thought about this before, but imagined it would be too hard to do, maintain etc. But I suspect that if I script this and patch lightly, the future time and gray hair saved should be massive.

Here are some motivation points as to "why":

* The template funcs are set on the templates, which means that Hugo clones the entire template set to all languages.
* There are no (easy) way to pass an execution context to methods/functions without changing the method signatures.
* There is no (easy) way to inject hooks to control how map lookup/methods gets invoked. One example is the special `maps.Params` in Hugo, which has methods for lower case lookups.
* The method/function invocation is entirely reflection based, which is still pretty fast, but with proper interfaces, we can do better with code generation.

Note that I have been fairly active in wishing stuff on Go's issue tracker, but while I feel they listen, that project, and especially these packages, is moving slower than I would like.

What do you think, @moorereason ?

**Comment by moorereason** [comment]
I share your concern with maintaining a fork and compatibility, but if you can come up with some lightweight interfaces that are easy to maintain, it could make many things easier.

Also, if we could come up with a really tight, generally useful change to the stdlib API, it may have a shot of getting pushed upstream.  Long shot, but we can aim for it.

**Comment by bep** [comment]
This would also, short term, mean deprecation/removal of Ace/Amber, which I don't use. I suspect some people will scream at me for that, but those people are not paying me anything to spend the countless hours needed to maintain/develop it. 

So, this is picking what I think it's the least amount of friction. I have spent countless hours trying to work around the limitation of those packages, and I swill cannot do what I want.

**Comment by bep** [comment]
@moorereason just a quick note: I will write up a proposal early next year for Go. The thing we have done here is surprisingly unintrusive, and it's basically a stricter separation of parsing (the AST) and template execution, which I  think was a mistake in the original design -- and should be a possible sell for a minor Go redesign in this area. There are many issues on Go's issue tracker that would be solved by this.
