### ISSUE TITLE
Changing hugo template files from .html to .gohtml renders the template unusable

### ISSUE THREAD

**Issue by iu4u57k3** [gohugoio/hugo#6597]
I changed all hugo template file extensions from .html to .gohtml for better formatting and correct language reference. 

![hugo_issue](https://user-images.githubusercontent.com/52806368/70506379-23317980-1b50-11ea-965b-1dfcfe3e2d2a.png)

this made the template unusable

![nothing](https://user-images.githubusercontent.com/52806368/70506552-9a670d80-1b50-11ea-9eb1-117619eb8f31.png)

**Comment by iu4u57k3** [comment]
Idea editors must be told that it is a gohtml file and not html file otherwise Ctrl + Alt + L formatting breaks the template code.

**Comment by peaceiris** [comment]
Some text editors can parse the Hugo template with extensions.

e.g. VS Code [Hugo Language and Syntax Support - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=budparr.language-hugo-vscode)

**Comment by iu4u57k3** [comment]
Hello,
I'm using idea comunity edition.
There is a gohtml plugin available for idea that makes it easy to edit gohtml files, that is why I'm using .gohtml extension.

It makes it easy to edit gohtml file.

**Comment by peaceiris** [comment]
> I'm using idea community edition.

Sorry, I missed it.
@iu4u57k3 You mean [Go Template - Plugins | JetBrains](https://plugins.jetbrains.com/plugin/10581-go-template/), right?

**Comment by peaceiris** [comment]
This seems to be duplicate of #3230.
