### ISSUE TITLE
Hugo fails to display changes in browser

### ISSUE THREAD

**Issue by GideonWolfe** [gohugoio/hugo#6602]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.60.1/extended linux/amd64 BuildDate: unknow
</pre>

### Does this issue reproduce with the latest release?

I'm assuming so, I *just* rebuilt and reinstalled Hugo from the AUR to try and fix this issue.

### Issue

I have been using the following method to write pages locally for *months* without any issues.

* I run `hugo server` on a local machine
* Open `localhost:1313` in my browser
* See changes reflected on page when I edit the files

Now, the files are not updating. I edit them and I see the console output of Hugo detects the changes, but they are not updated on the browser. It only seems to be new files as well. I edited the contents of a pre-existing file and the changes were shown, but the file I created today won't even show up.

I tried running with `hugo server --disableFastRender` but this did not help

**Comment by thetanil** [comment]
Did you figure something out here? Just a guess here, but I guess it has to be related to your site or there would be many more people piling on here. I am on 0.61/0.62 and it's working well. If you have your site in a public repo I could see if anything jumps out at me. Maybe try updating to the [current release](https://github.com/gohugoio/hugo/releases/tag/v0.62.0) too? Is the livereload.js script getting appended to your page with the correct port?

**Comment by GideonWolfe** [comment]
Yeah i'm not too sure what happened tbh. I was giving someone a demo on how simple hugo was to use and it just... didn't work.

I wouldn't have been suspicious if not for the fact it was doing the same thing on my desktop at home. Not sure what to say, it seems like it fixed itself within a few hours.

**Comment by adiabatic** [comment]
This kind of thing used to happen to me too, with freshly-created repos, at least.
