### ISSUE TITLE
v0.61.0 ToC does not nest/indent correctly

### ISSUE THREAD

**Issue by J-Siu** [gohugoio/hugo#6613]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.61.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
yes

Live URL: https://johnsiu.com/blog/k8s-installation/
Raw md: https://raw.githubusercontent.com/J-Siu/johnsiu.com/master/content/blog/k8s-installation.md
Theme: https://github.com/Vimux/Binario (latest pull master)

I added following in my config.toml:

```toml
[markup]
  [markup.tableOfContents]
    endLevel = 10
    startLevel = 3
````

The ToC does not nest/indent correctly:
![Screen Shot 2019-12-12 at 2 38 50 AM](https://user-images.githubusercontent.com/3171920/70692423-50ce0e00-1c89-11ea-9e7f-09822247dd71.png)

The 3 lines in red rectangle are level 4 and should be indented.

PS: I tried using the default(removing the markup section) and reduce all headers by 1 level but result is the same.

**Comment by bep** [comment]
This is a styling issue. You need to take this with the theme author. Alternatively you can ask at https://discourse.gohugo.io/
