### ISSUE TITLE
Allow multiple arguments in ne function

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#6619]
This is currently not possible

```
{{ if ne .RelPermalink "/link1/" "/link2/" }}
```

while this is possible

```
{{ if eq .RelPermalink "/link1/" "/link2/" }}
``` 

This may be a good addition because it makes things a lot easier.

Maybe this construct would make sense for `ge`, `gt` …, too?!

**Comment by bep** [comment]
{{ if not(eq .RelPermalink "/link1/" "/link2/") }}

**Comment by le0tan** [comment]
@bep I'd love to give this a try. Would you mind showing me where should I start with?
