### ISSUE TITLE
Hugo export to PDF (save as PDF) option possible?

### ISSUE THREAD

**Issue by bugrakeskin** [gohugoio/hugo#6627]
I am using Hugo in localhost and trying to export my single page as PDF. When i ctrl+p on a page and select a pdf printer it renders all the page with the menus. can anybody solve this?

**Comment by eine** [comment]
Possible dup of #6332.

**Comment by kevingimbel** [comment]
@bugrakeskin Unless there is a special PDF output format you'll need to use CSS to remove parts from the PDF. You can do this with the `@media print` media query, for example the following would hide the elements with classes `sidebar`, `menu` and `footer`. 

```css
@media print {
  .sidebar, .menu, .footer { display: none; } 
}
```

Additional reading:
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media
- https://css-tricks.com/print-stylesheet-approaches-blacklist-vs-whitelist/

**Comment by bugrakeskin** [comment]
@kevingimbel thank Kevin. Ive managed to do that in css. I added to my themes css file and change the names and it worked.
can you show me how to hide the page details..thank you
![resim](https://user-images.githubusercontent.com/58621386/71157956-05e96300-2254-11ea-9d4a-2846262cf785.png)

**Comment by kevingimbel** [comment]
@bugrakeskin I don't know how to do this, I think they are added by the browser when you save the PDF

**Comment by HenrySkup** [comment]
@bugrakeskin Those can be turned off in the browser preferences. 

Because browsers have such strong opinions on print to pdf (and the implementation of the paginated media spec is spotty/in progress) having a pdf output in Hugo would be quite nice

**Comment by julientaq** [comment]
Hey folks, I made a small implementation of paged.js for [www.pagedjs.org](www.pagedjs.org) so you can have a look at it and tell me how it works for you.

Still pretty experimental, but i’d love to have your thoughts.

https://gitlab.pagedmedia.org/julientaq/pagedjs-hugo

If you follow the readme, you’ll get a print button that you can add to any page as part of the template. next step is to add a configurable option in the front matter to show it or not :)
