### ISSUE TITLE
How to resize images??

### ISSUE THREAD

**Issue by leo81122** [gohugoio/hugo#6630]
New to hugo.
I can't use 
![](image_url ?200x200)
or
![](image_url =200x200)
or
![](image_url){: "height = 200" "width = 200"}
or
<img src= "image_url" style= "zoom:90" / >

I can use those in vs code or typora, but can't in hugo!
I can't find answer use google either.

So can anyone just tell me how to resize image in hugo?This just drive me crzy.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
