### ISSUE TITLE
Merge Params with dictionary

### ISSUE THREAD

**Issue by xv-andrii-h** [gohugoio/hugo#6633]
Starting from version 0.60.0 `Params` (page, site, etc.) were changed from `map[string]interface{}` to `Params` type. This means that we can not merge them with dictionary produced by `dict` function:

```
error calling merge: incompatible map types, got maps.Params to map[string]interface {}
```

Maybe it makes sense to update `dict` function to return `Params` type too?

**Comment by bep** [comment]
>Maybe it makes sense to update dict function to return Params type too?

No, that would not make sens. `maps.Params` is lower-case string keys only. But merge should handle it.

**Comment by xv-andrii-h** [comment]
@bep Thank you, such fix is also fine :)
