### ISSUE TITLE
Incorrect handling of formatting in table cells

### ISSUE THREAD

**Issue by frerich** [gohugoio/hugo#6641]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.61.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

Given a Markdown table like

```markdown
Foo|Bar
---|---
`Yoyo`|Dyne
```

Then pasting it in the (supposedly correct) CommonMark editor at https://commonmark.org/help/tutorial/02-emphasis.html (click the 'Try It' button to get to the Marrkdown editor) produces a table with two rows (one for the header, one for the data)  and two rows.  In particular, 'Yoyo' . and 'Dyne' are in separate columns, with 'Yoyo' being formatted with a fixed-width font.

With Hugo, the backticks cause 'Yoyo' . and 'Dyne' to get merged into a single column. Removing the backticks (i.e. removing the formatting) causes two columns to be generated again.

**Comment by bep** [comment]
Thanks for the report. This looks like it could be an issue with Goldmark. Could you create an issue at https://github.com/yuin/goldmark/issues and link back to this issue so we could track it?

**Comment by frerich** [comment]
I considered creating a Goldmark issue but I'm asked to specify which version of Goldmark I'm using - alas, I don't know!

Also, when creating a Goldmark issue, it asks to verify that https://spec.commonmark.org/dingus/ produces different output than Goldmark. Which, in this case, is *not* the case.

In fact, the CommonMark editor at https://spec.commonmark.org/dingus/ and then one used by https://commonmark.org/help/tutorial/02-emphasis.html (after clicking the 'Try It' button) yield _different_ results (I think the latter generates the more plausible result). So I'm not even sure it's a Goldmark bug or just a wrong expectation on my part based on doing the CommonMark tutorial...

**Comment by bep** [comment]
The latest Goldmark renders this:

```html
<table>
<thead>
<tr>
<th>Foo</th>
<th>Bar</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>Yoyo</code>|Dyne</td>
<td></td>
</tr>
</tbody>
</table>
```

Which does look correct to me.

**Comment by bep** [comment]
https://github.com/yuin/goldmark/issues/69

**Comment by frerich** [comment]
Thanks a lot for creating the Go-based Goldmark issue so quickly - it's great to see how active both you as well as Yuin are.  Great job!
