### ISSUE TITLE
Do not return any value in errorf

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6653]
Related to #6652, but lest take it in a separate issue.

This would probably make sense before we got the server error page, but now it's just annoying, esp. for people who want to publish even if there are ERRORs.

**Comment by moorereason** [comment]
What about people who expect the build to fail on `errorf`?

**Comment by bep** [comment]
What about them?

**Comment by moorereason** [comment]
Ignore me.  I misunderstood what you were talking about here. 🤦‍♂
