### ISSUE TITLE
travis: Fix arm build

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6655]
There is a failing test there, which I find har to debug, even if I had time. But it is demotivating watching that red build. 
/cc @anthonyfok

**Comment by anthonyfok** [comment]
Hi @ bep,

I suppose you are talking about this test error on ARM that started to show up about a month ago:

```
--- FAIL: TestImageOps (5.75s)
    quicktest.go:306: 
        error:
          unexpected success
        got:
          nil
        stack:
          /home/travis/src/hugo/hugolib/image_test.go:149
            c.Assert(err, qt.Not(qt.IsNil))
```

Looking through past Travis CI builds, the build error seems to start at around:

* https://travis-ci.org/gohugoio/hugo/builds/616808806: resources/images: Make the image cache more robust (commit d6f7a9e28dfd5abff08b6aaf6fb3493c46bd1e39)

where some of the image test stuff was changed/added.

But it seems that there was an update of Go version from 1.13.1 to 1.13.4.

I'll find time to take a closer look on Debian ARM porterbox machine and see if I can reproduce the test error there and try to come up with a fix in the coming week.
