### ISSUE TITLE
The Dev Server should really be serving custom 404 pages

### ISSUE THREAD

**Issue by LukeWood** [gohugoio/hugo#6656]
would minimize discrepancy between 99% of prod servers and hugo dev server

**Comment by braderhart** [comment]
Would love to see SSL support as well for PWA testing. Currently using HAProxy as a go-between.

**Comment by bep** [comment]
I'm pretty sure there is a duplicate issue somewhere.

**Comment by LukeWood** [comment]
@braderhart why do you need SSL support for PWA testing?  Browser Apis that require HTTPs almost always have a bypass for localhost.  I suppose if your app needs to run on "local.dev" or something similar you'd need it.

**Comment by braderhart** [comment]
That is one of the reasons, additionally you may serve it over your local network to a mobile device for testing and then localhost won't work.

**Comment by LukeWood** [comment]
noted - yeah seems like a welcome addition.  Maybe I'll take a shot at the custom 404 page.   Seems like it should be trivial.

**Comment by LukeWood** [comment]
@bep seems you are the top contributor - any pointers/idea on where I could look in the source to see the entry point of the dev server?

**Comment by LukeWood** [comment]
ah scratch that - I found it.

looks like https://github.com/gohugoio/hugo/blob/master/commands/server.go#L295 would be a good way to add a 404 route.   I'll try to draft up a PR this weekend :)

Thanks for all your hard work on hugo - it's by far my favorite static site generator.
