### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by cup** [gohugoio/hugo#6658]
If you have this setup:

~~~
content\mon.txt
content\tue\index.md
~~~

You get this result:

~~~
Error: Error building site: open C:\sun\public\mon.txt: The system cannot find
the path specified.
~~~

Running a second time seems to fix the problem.

**Comment by thetanil** [comment]
You didn't fill out the New Issue Template, so we don't know what version this is. Also, I don't see .txt as a [supported content type](https://gohugo.io/content-management/formats/#list-of-content-formats), so I wonder what you expect hugo to do here.

**Comment by cup** [comment]
@thetanil

> You didn't fill out the New Issue Template, so we don't know what version this
> is.

ok? unless youve tried to repro my issue above (not likely given your tone), and
been unable to, your comment is not constructive.

> Also, I don't see `.txt` as a supported content type, so I wonder what you
> expect hugo to do here.

well, couple of good choices here:

- ignore the file
- copy file as is to output
- ask user what to do
- allow user to config what to do via `config.yaml`

a bad choice would be what Hugo is doing currently.

**Comment by thetanil** [comment]
It is a constructive comment, because I am trying to help you get help and people don't want to waste their time asking you, which is why they give you a template. Also in the future, standard bug reports show what version, what was expected, what actually happens, and the steps to reproduce the problem. You will have better luck getting help in the future that way.

If you want a file copied to the output folder you should drop it in [static](https://gohugo.io/content-management/static-files/)

Good Luck.

**Comment by cup** [comment]
> It is a constructive comment, because I am trying to help you get help

Frankly I dont need you to "help me get help". I can (and have) done that just
fine myself. If you wish to actually help, rather than "help me to get help",
I would be open to that.

Perhaps you should help yourself: if you had taken even a passing glance at
[my profile](//github.com/cup), you would see that I am not a stranger to Git or
GitHub. So if I post an issue in a certain way it was definitely intention,
whether it aligns with your value system or not.

> and people don't want to waste their time asking you, which is why they give
> you a template. Also in the future, standard bug reports show what version,
> what was expected, what actually happens, and the steps to reproduce the
> problem.

I understand all that, and I took that into account before posting. I am using
the latest released version of Hugo, so in lieu of information most people would
use that as a starting point. I also realize that many issues are caused by
people using old (or very new) versions, which is why I am testing with latest
stable release 0.62.0.

> You will have better luck getting help in the future that way.

Thats your opinion.

> If you want a file copied to the output folder you should drop it in
> [static](https://gohugo.io/content-management/static-files/)

No I am not doing that. and even if I did, it doesnt fix the fact that the
current behavior is broken.

Finally I would please as you not to make any more comments unless they are on
topic and toward actually resolving the problem. I do not care to read your
views of the proper way to report issues, I am quite capable of posting "the
right way" or "the wrong way", and I am well aware of the cost/benefit of both
methods. Cheers.

**Comment by thetanil** [comment]
I just spent some time trying to reproduce this. It appears that any file with a date in the future is filtered out. I tried 

* with toml and yaml
* with a title and without
* in the future 1 day or 100 years

If the file is dated in the future at all, it's removed from both drafts and future.

I was not able to get any configuration of a future file to show up in the list.
