### ISSUE TITLE
ignoreFiles invalid matches

### ISSUE THREAD

**Issue by cup** [gohugoio/hugo#6659]
With this setup:

~~~
content/daylight/day/sunday.txt
content/daylight/index.md
~~~

and this config:

~~~yaml
ignoreFiles:
- day/
~~~

Neither file is created in the output folder. Same goes for these:

~~~yaml
- day/.*
- day\\
- day\\.*
~~~

https://gohugo.io/getting-started/configuration#ignore-content-files-when-rendering

**Comment by cup** [comment]
So the problem was, that my actual setup looks like this:

~~~
monday/content/daylight/day/sunday.txt
monday/content/daylight/index.md
~~~

so `day/` was essentially ignoring everything. Proper config would be:

~~~yaml
ignoreFiles:
- /day$
~~~

Something else I did notice though, is that the match seems to have some kind of
depth limit. For example, with this setup:

~~~
content\daylight\day\wed.txt
content\daylight\index.md
content\daylight\tue.txt
~~~

~~~yaml
ignoreFiles:
- \.txt
~~~

you get this result:

~~~
public\daylight\day\wed.txt
public\daylight\index.html
~~~

**Comment by muv1** [comment]
https://github.com/gohugoio/hugo/issues/7221

**Comment by zor-el** [comment]
Why was this closed? The described confusing behavior (the alleged depth limit) still persists.

**Comment by muv1** [comment]
This was my issue under another account. I had other more important issues, and I solved this one myself as detailed in the other thread.
