### ISSUE TITLE
watchFiles

### ISSUE THREAD

**Issue by cup** [gohugoio/hugo#6662]
This would be the opposite of `ignoreFiles`:

https://gohugo.io/getting-started/configuration#ignore-content-files-when-rendering

or could be called `includeFiles`.

`ignoreFiles` will ignore files that match. `watchFiles` will ignore files that
do not match. My use case is that I put some files alongside markdown files that
that get pulled in with `readFile`:

https://gohugo.io/functions/readfile

These files can have arbitrary extensions and its become a hassle to ignore them
all.

**Comment by cup** [comment]
As a workaround, I renamed any files to ignore like this:

~~~
sunday_.go
monday_.go
~~~

then use this config:

~~~yaml
ignoreFiles:
- _\.
~~~

**Comment by a8nJ** [comment]
https://github.com/gohugoio/hugo/issues/3818
