### ISSUE TITLE
Make `.RenderString` render shortcodes

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#6666]
Now that we have `.RenderString`. The problem mentioned in https://github.com/gohugoio/hugo/issues/6094#issuecomment-513116608 has been lifted and we should consider having `.RenderString` process shortcodes.

### Do we really need this?

When building a page with blocks of data (CMS Blocks,  Page Builders and so on), most of those are saved as Front Matter. It then falls on the developer to range on those blocks and apply the proper data processing/partial loading etc...

In the context of a very nice to have page builder, Hugo shortcodes are currently unusable by the editor and any search-and-replace workaround cooked up by developers (been there) will never match the reliability and usability of Hugo's shortcode API.

### Will it break code.

The `.RenderString` method is fairly new and I don't see anyone including shortcodes in there with the expectation that they would not be processed. So I think: No

**Comment by bep** [comment]
I'm closing this now. Please re-create this next year.

**Comment by regisphilibert** [comment]
Sure... is it the issue number you felt bad about? :)

**Comment by bep** [comment]
No, it's purely a timing issue

**Comment by regisphilibert** [comment]
You got it! And thanks for all the work this year!
