### ISSUE TITLE
Support markdown autolinks with Markdown Render Hooks

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#6667]
```
Hugo 0.62.0
```

Given this render-link.html code

```
<a href="{{ .Destination | safeURL }}"{{ with .Title }} title="{{ . }}"{{ end }}{{ if strings.HasPrefix .Destination "http" }} target="_blank" rel="noopener"{{ end }}>{{ .Text | safeHTML }}</a>
```

[Markdown auto links](https://spec.commonmark.org/0.29/#autolinks) are currently not supported.

In:

```
<http:/test.com>
```

Out:

```
<a href="http:/test.com">http:/test.com</a>
```

In (works as expected):

```
[Test](http:/test.com)
```

Out:

```
<a href="http:/test.com" target="_blank" rel="noopener">Test</a>
```

Thank you!

**Comment by Rarst** [comment]
Goldmark seems to support an even more freeform GFM autolinks without any delimiters https://github.github.com/gfm/#autolinks-extension-

Also completely un-marked-up link is a convention for automated embeds and having them run through hook would be very powerful for that purpose. Think lone twitter link by itself getting turned into full embedded tweet.

**Comment by Brixy** [comment]
Thanks a lot for v0.63.0!

This issue seems to be solved now, too—at least in all my use cases.

**Comment by matteocontrini** [comment]
It doesn't seem to be fixed for me. Autolinks still don't invoke the render hook...

**Comment by DJCordhose** [comment]
I am on 0.71 and it has not been fixed so far.

**Comment by Shelim** [comment]
**0.80** is out and it still does not work.

Workaround: if you want to use hook for adding "`target=_blank"` in your URLs, use different markdown provider in your `config.toml`:
````toml
[markup]
  defaultMarkdownHandler = "blackFriday"
  [markup.blackFriday]
    hrefTargetBlank = true
`````

**Comment by jmooring** [comment]
To clarify, this is an autolink:

```
<https://www.gohugo.io>  
```

And with:

```
[markup.goldmark.extensions]
linkify = true
```

These are also autolinks:

```
www.gohugo.io  
https://www.gohugo.io 
```

**Comment by jmooring** [comment]
Fixed with https://github.com/gohugoio/hugo/pull/8756
