### ISSUE TITLE
Support .Site params with Markdown Render Hooks

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#6668]
```
Hugo 0.62.0
```

Sorry—another question/proposal. But Hugo’t Christmas edition is just wonderful ;-)

---

This may be the intended behaviour, but `.Site` params seem to not be available in Markdown Render Hooks.

With site params theme developers could e.g. define sizes for responsive images or optionally set `target` of links to blank:

```
<a href="…"{{ if and (strings.HasPrefix .Destination "http") (eq .Site.Params.themeSettings.linksExternalBlank "true") }} target="_blank" rel="noopener"{{ end }}>…</a>
```

Thanks again, guys!

**Comment by bep** [comment]
You need to do either:

* .Page.Site.Params
* site.Params
