### ISSUE TITLE
Use SGML Processing Instructions to pass arguments to render hooks

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6670]
This is just me thinking out loud during Christmas. I kind of like the simplicity of it. The idea is to use [SGML Processing Instructions](https://en.wikipedia.org/wiki/Processing_Instruction) as a way to pass parameters to the new and shiny render hooks in Hugo (images and links).

* CommonMark has a proposed/experimental syntax for Markdown attributes. Goldmark has implemented it for titles and code blocks, but the Goldmark author have said that it would be "very hard" to implement it as a general thing for all elements.
* The nice thing about using SGML Processing Instructions is that most Markdown renderers (including GitHub) just ignore them (they will not get rendered). 

One example would maybe look like this:

```markdown
<?params width="400" height="500" ?>
![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")
```

I suggest that we:

* Agree on 1 instruction name, for now, e.g. `params`.
* I think it should work if we just create a stack of length 1 and pop any element into the rendering hook.

/cc @regisphilibert

**Comment by regisphilibert** [comment]
Looks promising in the long term. My feeling though is that Markdown will eventually be just one option among the many #6310 will open to Hugo users. So "roadmap wise" I woudn't put this in front of #6310.

**Comment by bep** [comment]
The road map is also budget constrained. This issue may be easier to finance (cheaper to implement).

**Comment by jmooring** [comment]
With https://github.com/gohugoio/hugo/commit/cd0c5d7ef32cbd570af00c50ce760452381df64e you can pass arguments (attributes) to heading render hooks:

```
# My Heading {data-foo="a" data-bar="b"}
```

The attributes are accessible within the heading render hook via `.Attributes`.

```
{{ range $k, $v := .Attributes }}
  {{ $k }} = {{ $v }}<br>
{{ end }}
```

However, you cannot do the same with either image render hooks or link render hooks because attribute support is limited to headings and blocks (see https://github.com/gohugoio/hugo/commit/2681633db8d340d2dc59cf801419874d572fc704).

**Comment by dfl** [comment]
> With [cd0c5d7](https://github.com/gohugoio/hugo/commit/cd0c5d7ef32cbd570af00c50ce760452381df64e) you can pass arguments (attributes) to heading render hooks:
> 
> ```
> # My Heading {data-foo="a" data-bar="b"}
> ```
> 
> The attributes are accessible within the heading render hook via `.Attributes`.
> 
> ```
> {{ range $k, $v := .Attributes }}
>   {{ $k }} = {{ $v }}<br>
> {{ end }}
> ```
> 
> However, you cannot do the same with either image render hooks or link render hooks because attribute support is limited to headings and blocks (see [2681633](https://github.com/gohugoio/hugo/commit/2681633db8d340d2dc59cf801419874d572fc704)).

I'm really confused because the [configuration markup page](https://gohugo.io/getting-started/configuration-markup) says "Attributes (map) New in v0.82.0." under context for render-link and render-image. It really makes logical sense, can't wait for this feature to just simply work out of the box.

**Comment by chalin** [comment]
Was this closed because it won't be fixed or because it has been implemented? The text above shows "@bep closed this as completed" but I'm not seeing any linked commit or other information that would give evidence of this feature now being supported. Thanks!

**Comment by bep** [comment]
>Was this closed because it won't be fixed or because it has been implemented?

We now have Markdown attributes that solves this:

https://gohugo.io/getting-started/glossary/#markdown-attribute

And yes, I should have commented on this before closing, I sometimes forget that other people watches these issues.
