### ISSUE TITLE
highlight line number config in code fences not respected

### ISSUE THREAD

**Issue by thetanil** [gohugoio/hugo#6672]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.62.0/extended windows/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes, using the latest release.

### Issue

Highlight line number config options for code fences seems to be ignored. While testing this feature I also noticed that the config option 'markup.highlight.lineNos' errors when not presented with a boolean, when in fact there "should be" several options (like table and inline).

### Markdown to reproduce

<pre>
{{< highlight js "linenos=false" >}}
let willDisplayLineNumbers = false
{{< /highlight >}}

``` js "linenos=false"
let willDisplayLineNumbers = true
```
</pre>

**Comment by bep** [comment]
Your markdown attribute syntax is wrong. Also the highlighting config has a separate field for linenumersInTable.

**Comment by thetanil** [comment]
Thanks very much. I missed that the ' was { in the code fences.

**Comment by thetanil** [comment]
@bep 
RE: Configuration

Does [this documentation](https://gohugo.io/getting-started/configuration-markup#highlight) need an update then? I don't know how I should know about the separate field
