### ISSUE TITLE
publish a complex example

### ISSUE THREAD

**Issue by lalebarde** [gohugoio/hugo#6673]
Hi,
That would be nice that you provide with Hugo a complex example involving all hugo functionalities in one single project, a theme and contents.
Regards,
Laurent

**Comment by moorereason** [comment]
We do that already.  It's the Hugo website: https://github.com/gohugoio/hugoDocs

**Comment by lalebarde** [comment]
Thanks  moorereason. Following your link and instructions:

```
git clone https://github.com/gohugoio/hugoDocs.git
cd hugoDocs/
hugo server
Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
       Run `hugo help new` for details.
```
