### ISSUE TITLE
Allow creation of humans.txt

### ISSUE THREAD

**Issue by zaitseff** [gohugoio/hugo#6674]
Currently, the output file `robots.txt` is generated quite elegantly from the template in `layouts/robots.txt`.  It would be nice to be able to generate `humans.txt` in the same way with a template in `layouts/humans.txt`, instead of using workarounds like generating custom home page outputs.  Should I attempt a patch to implement this?

**Comment by bep** [comment]
No, we're not implementing any new special output pages. We have custom output formats for this.
