### ISSUE TITLE
Markdown Images Broken in 0.62.0

### ISSUE THREAD

**Issue by Worldofmatthew** [gohugoio/hugo#6675]
### What version of Hugo are you using (`hugo version`)? 0.62.0

<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release? Yes

Hello,

I am trying to upgrade from 0.58.3 to 0.62.0 and encountered some bugs. I have fixed the HTML rendering one but I have noticed that markdown images no longer render at all and instead just show the markdown used as text.

Markdown used example: `![Screenshot of the order summery of a InnoHosting UK shared hosting package.](/img/2019/ukfake1.png)`

**Comment by thetanil** [comment]
I can't reproduce the issue. Generally speaking, images are working fine, so we're going to have to dig deeper. Can you show the html output? Maybe a more complete example (perhaps the surrounding markdown is throwing off the parser)?

**Comment by Worldofmatthew** [comment]
> I can't reproduce the issue. Generally speaking, images are working fine, so we're going to have to dig deeper. Can you show the html output? Maybe a more complete example (perhaps the surrounding markdown is throwing off the parser)?

Example:

`<html lang="en">
<header>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
    <title> The Fake 1080P Action Camera Being Sold by Argos</title>
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<link href="http://localhost:1313//css/womstyle.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js">
</script>

</head>
<body>
<div class="container-fullwidth">
<div class="container">
<div class="row header justify-content-center pt-2 pb-2">
<div class="col-lg-10  pt-1 pb-1 text-center">
<img src="http://localhost:1313/images/womlogo-2020.png" alt="">
</div>
</div>
</div>
<div class="row menu">
<div class="col-lg-12 p-0">
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="collapsibleNavbar">
    <ul class="navbar-nav mx-auto">
	      <li class="nav-item">
        <a class="nav-link" href="https://worldofmatthew.com/">[Home]</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://worldofmatthew.com/blog/">[Blog]</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-nowrap" href="https://worldofmatthew.com/scam/">[Scam Warnings] </a>
      </li> 
 <li class="nav-item">
        <a class="nav-link" href="https://worldofmatthew.com/review/"> [Reviews]</a>
      </li>	
<li class="nav-item">
        <a class="nav-link" href="https://worldofmatthew.com/technology/">[Technology]</a>
      </li>	
	  <li class="nav-item">
        <a class="nav-link" href="https://worldofmatthew.com/videos/">[Videos]</a>
      </li>	
  <li class="nav-item">
        <a class="nav-link" href="https://worldofmatthew.com/other/">[Others]</a>
      </li>	
    </ul>
  </div>  
</nav>
</div>
</div>
</header>


 
<main>
<div class="container-fluid main">
<div class="container section">
<div class="row p-2 mt-2">
<div class="col-lg-9 col-sm-9 col-md-9 col-xl-9 left pl-0">
 <div class="card pt-2 rounded-0  bg-transparent">
 <article>
    <div class="card-header">
	<center>		<figure class="post__thumbnail">
		<img class="card-img-top" src="../../img/2019/argos1.jpg" alt="Argos store front with a image of a generic action camera superimposed over it.">
		</figure> </center>
    </div>
    <div class="card-body text-center">
      <h1 class="card-title">The Fake 1080P Action Camera Being Sold by Argos</h1>
      <p class="card-text">Date Published:  <time>16.10.2019 </time></p>
       </div>
	   <div class="card-footer"><p>Argos is one of the most well-known retailers in the UK. With the company having over eight-hundred stores across the country, you are rarely far away from one of its locations.
Like many other retailers, Argos also has a large number of items on some kind of special offer at any given time. One of the products Argos has on sale in its clearance section is a Vibe 1080p Action Camera which at just £14.99 sounds like a bargain.
The action camera listed claims to be able to record video at 1080p/30FPS and take photos at 16 megapixels. The fact that the Vibe records at 1080P was confirmed to a user on the questions and answers section of the product page.
<br></p>
<center>
![Screenshot of a Alibaba for a Module that makes use of the H62 sensor.](/img/2019/argos2.jpg)
</center>
<br
<br>
## The Vibe Action Camera is not 1080P ##
<p>To me, a £15 1080p action camera just sounds too good to be true. This feeling of the deal being too good to be true was further correlated when I watched some of the test videos that showed the action camera to have such bad video quality that there was no way the optical resolution was anywhere near 1080p.</p>
<center>
![A screenshot comparing downsampled 720p with the original 1080p video.](/img/2019/7201080fake.jpg)
</center>
<p>I took a screenshot of one of the test videos. Then I made another copy of that screen which I downsampled to 720P in RIOT and re-sized that to 1080p in a photo editing programme.</p>
<p>There was almost no difference between the original &ldquo;1080p&rdquo; screenshot and the downscaled 720p (and re-enlarged to 1080p) screenshot. All test videos I saw had no visual difference between the two resolution which would indicate that the 1080p mode is fake and is in reality just 720p with interpolation used to fake a higher resolution.</p>
<h2 id="the-h62-cmos-sensor">The H62 CMOS Sensor</h2>
<center>
![Screenshot of a Alibaba for a Module that makes use of the H62 sensor.](/img/2019/h62.jpg)
</center>
<p>After seeing from the test videos that the Vibe action camera was incapable of true 1080p video, I noticed one of the unboxing videos showed the specs list on the back of the box. Within those specs list the action camera was listed as having an &ldquo;H62&rdquo; sensor.
Doing a search around alibaba for &ldquo;H62 Cmos&rdquo; showed the sensor to be very commonly used in cheap CCTV and action cameras. Looking through the listings, you find that the &ldquo;H62&rdquo; sensor only has a resolution of 1280x960. This makes it impossible for the Vibe Action Camera to meets its specs of being able to record 1920x1080 video.</p>
<h2 id="the-argos-support-runaround">The Argos Support Runaround</h2>
<p>You would think being such a well known and trusted retailer that Argos would have taken this issue seriously. But when I submitted questions to Argos support over Facebook, they said they wanted me to use their website to ask a question to the questions and answers team.
The same team that just read off the specs list and told a customer the camera was capable of 1080p/30. Not the type of people who you would expect to answer questions on complex topics such as detailed specs of the underlining sensor the action camera used.</p>
<p>After which, I put more pressure on them by telling them straight that I thought the product was fraudulently overstating its&rsquo; capabilities. They came back to me by claiming  the camera that you needed a class 10 micro-SD card for it to record in 1080p but looking at some of the videos it is obvious that the camera deals with memory that is too slow by simply dropping frames.
Another claim Argos support made is that you need a big micro-SD card to record at 1080p, though any mico-SD nowadays will be above 8GB and they never backed this up with anything and I have not seen one reviewer claim to have the camera limit the resolution.</p>
<p>After listening to the bullshit replies, I asked them for an email address so I could contact Argos head office about the fake resolution. To which I was told that there was no email address for head office and would have to send them a letter by the postal system. The idea that Argos does not have an email address for their head office in this day and age comes off as being an unfunny joke.</p>
<p>This runabout is not something anyone should ever expect to see when trying to bring the companies attention to the fact that maybe one of the products they are selling may not function as advertised.</p>
<h2 id="image-sources-and-credits">Image sources and Credits:</h2>
<br>
<b>Header Image (modified to add action camera):</b>
<p>Argos Extra, Waterfront Retail Park, Barry<br>
<a href="http://creativecommons.org/licenses/by-sa/2.0/">cc-by-sa/2.0</a> - 
© <a title="View profile" href="https://www.geograph.org.uk/profile/39302">Jaggery</a> - <a href="https://www.geograph.org.uk/photo/6264996">geograph.org.uk/p/6264996</a></p>
<br>
<b>Video from which the resolution screenshot came from:</b></p>
<p><a href="https://www.youtube.com/watch?v=2KuFLnPjw64">Unboxing and Review | Vibe 1080p Action Camera from Argos!</a> By willcaddy
<br></p>
<p><b>Alibaba listing for the Module that makes use of the H62 sensor:</b></p>
<p><a href="https://www.alibaba.com/product-detail/NEW-Cheap-Model-1-0MP-4_60716107538.html">NEW Cheap Model 1.0MP 4 IN 1 CCTV Camera Module PCB SOI H62 With V20E </a></p>
</div>
  </div>
</article>
</div>
<div class="col-lg-3 p-0 col-sm-3 col-md-3 col-xl-3 mt-2 mt-sm-0 text-center right">
 <div class="card d-none d-sm-block rounded-0  bg-transparent">
    <div class="card-header">
<aside>
	<img class="card-img-top" src="http://localhost:1313/images/wompix1.png" alt="">
    </div>
    <div class="card-body text-center">
	 
	 <b><sidebartext>WorldofMatthew menu:</sidebartext></b>
	 <br>
	 The WorldofMatthew sidebar provides convenient links to featured pages around this website.
	 <hr>
	 <br>
	 <sidebartext>WorldofMatthew Links:</sidebartext>
	 <br>
	<sidebartext><b> <a href="https://worldofmatthew.com/contact/">Contact Me</a><b></sidebartext>
	 <br>
	 <br>
	 <hr>
	  <sidebartext>Free Audiobooks:</sidebartext>
	  <hr>
	  <sidebartext><b> <a href="https://worldofmatthew.com/audiobooks/">Free Remastered Public Domain Audiobooks</a><b></sidebartext>
	  <hr>
	  <sidebartext><b> <a href="https://worldofmatthew.com/free-audiobooks-children/">Free Audiobooks for Children</a><b></sidebartext>
      </div>
</aside>

	  
  </div>
</div>
</div>
</div>
		
	</main>

<footer>
<div class="row mt-2">
<div class="col-lg-12 text-center bg-dark pt-1 pb-1 pl-0 pr-0">
<font color="white"><b>© Matthew Christopher Morgan 2015-2019<b></font>
</div>
</div >
</div>
<script data-no-instant>document.write('<script src="/livereload.js?port=1313&mindelay=10&v=2"></' + 'script>')</script></body>
</html>
</footer>

`

**Comment by Worldofmatthew** [comment]
> I can't reproduce the issue. Generally speaking, images are working fine, so we're going to have to dig deeper. Can you show the html output? Maybe a more complete example (perhaps the surrounding markdown is throwing off the parser)?

Here is an example of a broken page: https://pastebin.com/k1puRzAP

**Comment by bep** [comment]
@Worldofmatthew you need to provide the Markdown that does not work. It's impossible to guess from the output.

**Comment by Worldofmatthew** [comment]
> @Worldofmatthew you need to provide the Markdown that does not work. It's impossible to guess from the output.

Here is the full markdown of that page:

https://pastebin.com/MrSEcRfX

**Comment by thetanil** [comment]
you need empty lines to separate your html from your markdown. try changing it to:
```
<center>

![img](path/to.jpg)

</center>
```

**Comment by thetanil** [comment]
you also have a broken br tag in there which is probably gonna mess you up later

```
<br
<br>
```

**Comment by Worldofmatthew** [comment]
> you need empty lines to separate your html from your markdown. try changing it to:
> 
> ```
> <center>
> 
> ![img](path/to.jpg)
> 
> </center>
> ```

Why is extra spacing suddenly required that is not in normal HTML?

Now to fix a bunch of articles and hope the rules don't randomly change again.

**Comment by thetanil** [comment]
https://gohugo.io/news/0.60.0-relnotes/
