### ISSUE TITLE
sections not rendering with taxonomy starting with same letters

### ISSUE THREAD

**Issue by ominty** [gohugoio/hugo#6676]
Precondition:
You have sections like 
- foobar
- foogit

and also

- johndoe.

This works fine, the pages from the sections are rendered correctly.

Now you define a taxonomy in config.toml
```
[taxonomies]
  foo = "foos"
```
then the first two sections stop rendering any pages.

Disabling the taxonomy
```
[taxonomies]
#  foo = "foos"
```
or renaming it
```
[taxonomies]
  foobase = "foobases"
```
will lead hugo to render correctly again.

As @pointyfar confirmed

https://discourse.gohugo.io/t/section-secret-two-out-of-5-sections-not-rendering/22451/5?u=ominty

this seems to be an issue beginning with hugo 0.57, currently I run 0.58.2 on debian with 0.30.2 on Linuxmint before.

Repo is there (master):
https://github.com/ominty/ominty-hugoissues

**Comment by bep** [comment]
I'm working on a similar case, but cannot reproduce this particular situation, so I assmued it's fixed?

**Comment by jmooring** [comment]
Unable to reproduce with v0.82.

```bash
git clone --single-branch -b hugo-github-issue-6676 https://github.com/jmooring/hugo-testing hugo-github-issue-6676
cd hugo-github-issue-6676
hugo server
```
