### ISSUE TITLE
Inline shortcode regression

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6677]
See https://discourse.gohugo.io/t/inline-shortcode-crashing-hugo-0-62/22495

**Comment by Kissaki** [comment]
It would be helpful if the commit message were self-contained and pointed out what it changes.

Atm. from the release page I can look at the commit and this ticket and see nothing. Then I have to navigate to a forum which has some reproduction case, some reasoning and some caveats split up into several posts.

It would be much appreciated if the Git commit or at least the bug ticket it references were self-contained and explanatory.

**Comment by bep** [comment]
There is 1) What: "inline shortcodes" 2) A failing test case now fixed. That is both self-contained and explanatory.
