### ISSUE TITLE
.RenderString causes <p>'s to be injected into code blocks

### ISSUE THREAD

**Issue by jakejarvis** [gohugoio/hugo#6678]
Happy Almost New Year, friends :)

This bug is a weird one and I'm stumped trying to trace the cause... I noticed my longer code blocks being formatted _incredibly_ oddly today and narrowed down the change to when I started running `.Content` through `.Page.RenderString` on each output type's template (after going crazy playing with new render hooks 🎉).

Some observations:

- This happens when code blocks include chunks of code separated by blank lines — for some reason, each block after the first blank line is detected as a new paragraph which **REALLY** threw off my CSS!
- It appears the last `<p>` tag isn't even being closed?
- Doesn't matter if syntax highlighting is on or off.
- Doesn't matter if line numbers are on/off (or inlined/tabled for that matter).

---

markdown:

````md
```php
line1
line2
line3

hello
test4
test5

hugo6

buggy7
buggy8
```
````

output via `{{ .Content }}` (correct behavior):
```
<div class="highlight"><pre class="chroma"><code class="language-php" data-lang="php">line1
line2
line3

hello
test4
test5

hugo6

buggy7
buggy8
</code></pre></div>
```

output via `{{ .Content | .Page.RenderString }}` (bizarre behavior):
```
<div class="highlight"><pre class="chroma"><code class="language-php" data-lang="php">line1
line2
line3
<p>hello
test4
test5</p>
<p>hugo6</p>
<p>buggy7
buggy8
</code></pre></div>
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.62.0-6608F155/extended darwin/amd64 BuildDate: 2019-12-23T10:29:48Z
</pre>

**Comment by pamubay** [comment]
`.Content` is already processed with markdown processor.

if you want raw content of your markdown file, use `.RawContent` variable.

**Comment by jakejarvis** [comment]
Using `{{ .RawContent | .Page.RenderString }}` seems to have fixed this particular issue, thanks @pamubay! I'll leave this open for now though since this still seems like a weird bug to me, but feel free to close if I'm mistaken and this quirk is just from rendering markdown twice.

(BTW, I started explicitly calling `.RenderString` instead of just plain `.Content` because some output types started choosing the wrong shortcode variants in v0.62.0 (RSS feed had some AMP shortcodes in it, etc) and `.RenderString` fixed that — but maybe that's a different issue altogether?)

**Comment by bep** [comment]
>Using {{ .RawContent | .Page.RenderString }} 

The above does not make much sense to me. Why not use the ready-to-use `.Content`?

**Comment by bep** [comment]
Anyhow, I'm closing this issue. Take this on the forum where it belongs.

**Comment by jakejarvis** [comment]
Apologies @bep, not sure why my shortcodes were glitching before but `.Content` seems to be choosing the appropriate type now, so my original reason for using `RenderString` is irrelevant. Happy New Year 😊
