### ISSUE TITLE
Permalink for tag with # not urlencoded properly

### ISSUE THREAD

**Issue by Luit** [gohugoio/hugo#6682]
When I have a taxonomy term with a `#` in it, its permalink won't work. For example, with a `hugo new site`, I add `content/test.md`:

    ---
    tags: ["#test"]
    ---

and the following `layouts/_default/terms.html`:

    {{ range .Data.Terms.ByCount }}
    <a href="{{ .Page.Permalink }}">{{ .Page.Title }} ({{ .Count }})</a>
    {{ end }}

yields this result at `public/tags/index.html`:

    <a href="http://example.org/tags/#test/">#test (1)</a>

I additionally found a strange redirect behavior in `hugo server`. This redirect loops:

    $ curl -i localhost:1313/tags/%23test
    HTTP/1.1 301 Moved Permanently
    Location: #test/
    Date: Sun, 29 Dec 2019 12:41:08 GMT
    Content-Length: 0

### What version of Hugo are you using (`hugo version`)?

    $ hugo version
    Hugo Static Site Generator v0.62.0-6608F155 linux/amd64 BuildDate: 2019-12-23T10:25:27Z

### Does this issue reproduce with the latest release?
Yes (this is latest, right?)

**Comment by Luit** [comment]
Note: The redirect for `/tags/%23test` should work with things like nginx I presume. It's just inconvenient for when you're running `hugo server`. The rendered site includes a `public/tags/#test/index.html` if I add a `layouts/_default/list.html`, and `hugo server` works if you go to the tag page _with_ the trailing slash included.

**Comment by thetanil** [comment]
@Luit regardless of hugo, hash symbols already have a special meaning in a URL. You might want to rethink what you are doing here. https://en.wikipedia.org/wiki/Fragment_identifier

**Comment by Luit** [comment]
I am aware of that, it's just something that's already present in the set of tags of a site I'm helping migrate from WordPress to Hugo. 

Taking another look at the tag in WP I notice the URL representation for this tag just strips the leading character in these instances (so tag `#test` becomes `test`), just like it normalizes all tags to become lowercase and translates spaces to `-`. Would it be a good idea to handle special characters in tags the same way?

**Comment by Luit** [comment]
In this same site, there's posts by WP put at URLs with different kinds of special characters in the URL like `»`, `’` (right single quotation mark) and `–` (en-dash). Having content filenames with this exact sequence, and the `[permalinks]` section configured to use `:filename` still results in a URL with those characters stripped. I'd say a taxonomy term could follow the same mechanism there.
