### ISSUE TITLE
The shortcode way of including md cause headings missed in TOC

### ISSUE THREAD

**Issue by jcyrss** [gohugoio/hugo#6690]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo_extended_0.62.0_Windows-64bit
</pre>

### Does this issue reproduce with the latest release?
Yes, it is the latest release I'm using.

### description

I know there is existing topic about how to including anther md file into current md file.

The popular way is to use shortcode, so I create a shortcode ‘include’ like the following

```
{{ $file := .Get 0  }}

{{ if strings.HasSuffix $file ".html" }}

{{  $file  | readFile  | safeHTML }}

{{ else if strings.HasSuffix $file ".md" }}

{{  $file  | readFile  | markdownify  }}

{{ end }}
```

and use that shortcode like this

```
{{% include "share/py/requests.md" %}}
```

The big problem of it is , the headings of included markdown file will NOT be put into the TOC of current md file.

I noticed there is a description in Hugo doc, https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown.

> In Hugo 0.55 we changed how the % delimiter works. Shortcodes using the % as the outer-most delimiter will now be fully rendered when sent to the content renderer (e.g. Blackfriday for Markdown), meaning they can be part of the generated table of contents, footnotes, etc.

But that just did not work, the headings inside of the included md still missing.

I packaged all relevant files in my project into a tiny zip file.

https://github.com/jcyrss/baiyueheiyu/files/4007660/hugo-demo.zip

Just unzip it, run ```hugo server```, and browse address ```http://localhost:1313/tut/03/``` will show the problem.

As the following screenshot shows, headings in included md are missed, while I did use shortcode like {{% include "share/requests.md" %}} in the file content\tut\03.md

![image](https://user-images.githubusercontent.com/10496014/71613196-f963f380-2bdf-11ea-9c97-1f428bde7bb9.png)

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by jcyrss** [comment]
Thanks, bep. 
I posted it here because I thought it is likely a bug. That is not the expected behavior as described in the documentation, right?

And it is very easy to reproduce with the zipped project folder. Could you check it out?

**Comment by jcyrss** [comment]
OK , I guess i figured out why.

> In Hugo 0.55 we changed how the % delimiter works. Shortcodes using the % as the outer-most delimiter will now be fully rendered when sent to the content renderer (e.g. Blackfriday for Markdown), meaning they can be part of the generated table of contents, footnotes, etc.

The above description only applies to those shortcodes with included content directly in related html file. 

But for those like having `readFile` command, the file content to be read it's not fully rendered before sent to the markdown processor ( goldmark in my case). 

So I have to write a pre-process script in Python to replace `include` direction with real file content. 

Really hope Hugo guys could solve it in better way.
