### ISSUE TITLE
hugo converts "+" into "\x2b", causing ld+json parsing failure

### ISSUE THREAD

**Issue by cwchentw** [gohugoio/hugo#6695]
### What version of Hugo are you using (`hugo version`)?

Hugo Static Site Generator v0.62.0-6608F155 windows/amd64 BuildDate: 2019-12-23T10:26:18Z

### Does this issue reproduce with the latest release?

Yes.

**Comment by moorereason** [comment]
This is an [upstream issue in Go `text/html`](https://github.com/golang/go/issues/33671).  A fix was committed into Go master on March 27th.

**Comment by codecraf8** [comment]
my site is in production and i am getting the same issue, how do i overcome it? do i upgrade hugo to fix it?

**Comment by bep** [comment]
@moorereason if this is "important enough" I could synch our fork with the Go master...? 

/cc @carlmjohnson

**Comment by carlmjohnson** [comment]
@codecraf8 See this comment for a workaround until Go 1.15: https://github.com/golang/go/issues/33671#issuecomment-602631646

**Comment by codecraf8** [comment]
@carlmjohnson thanks for sending this around, i am new to Go, the snippet is this - https://play.golang.org/p/pNtKGJgTQs0 how / where do i include this?

**Comment by carlmjohnson** [comment]
In your template, change whatever you’re emitting to `{{ $myValue | jsonify | safeJS }}`. You need to use jsonify to get correct escaping and safeJS to make sure the escaped version is not double escaped.

**Comment by newcountrysongs** [comment]
having the same problem here...

**Comment by newcountrysongs** [comment]
In my `<script type="application/ld+json">`
 Dan + Shay becomes
`"name": "Dan \x2b Shay"`

very frustrating

**Comment by carlmjohnson** [comment]
Please upgrade to Hugo 0.71.1. This issue is resolved. If you see an issue with 0.71.1+, open a new issue.
