### ISSUE TITLE
what does the path point at

### ISSUE THREAD

**Issue by jintian93** [gohugoio/hugo#6700]
https://jintian93.github.io/post/assets/1568259158377.png

I have hugo project which local render normal but pushed to git then image can not found. What this path point to in local file folder?

**Comment by jintian93** [comment]
https://github.com/jintian93/jintian93.github.io/tree/master/assets

**Comment by jintian93** [comment]
I do have this file but can not render, how???

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
