### ISSUE TITLE
Shortcodes redundant calling on same rest api 

### ISSUE THREAD

**Issue by yarabaheera** [gohugoio/hugo#6704]
Hi, i have multiples of hugo shortcodes in a page. so each shortcode i need to call rest api. There are redundant calling on same API already. How can i handle this. I did try put all APIs in one partial but i dont find way to retrieve back the data from shortcode. Kindly help. thanks

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
