### ISSUE TITLE
Slash breaks relativeURLs

### ISSUE THREAD

**Issue by inwardmovement** [gohugoio/hugo#6708]
**Hugo version:** `0.62.1`

**Config**
`canonifyURLs: false`
`relativeURLs: true`

---

The `404.html` template can't seem to resolve links correctly when a `/` is in the url:
https://404-test.netlify.com/test = ok
https://404-test.netlify.com/test/ = "/test/" is prepended to all links inside the page, breaking the navigation and styles.

Any idea how to fix that?
[Here is my repo/branch](https://github.com/algosphere/algo-website/tree/404-test)

**Comment by gekart** [comment]
I don't know if this is actually related, but the links in 404.html get rendered relatively, no matter what I do in that file. That doesn't make much sense, e.g. as found in 'layouts/404.html':

```
          <p><img src='{{ "/images/gopher-404.jpg" | relURL }}' style="width:50%" alt="Page not found!"></p>
```

is rendered as:

```
          <p><img src='./images/gopher-404.jpg' style="width:50%"></img></p>
```

Let's say I want to return an error page for `example.com/folder/`, then the link above will result in `example.com/folder/images/gopher-404.jpg` which of course doesn't make sense...

No matter what I do in 404.html, like:

```
          <p><img src="/images/gopher-404.jpg" style="width:50%" alt="Page not found!"></p>
```

 the resulting links are always prepended with a dot.

**Comment by inwardmovement** [comment]
@bep do you have any insight on this please?
