### ISSUE TITLE
Whitespace handling for auto ID generation only considers space and tab

### ISSUE THREAD

**Issue by jkboxomine** [gohugoio/hugo#6710]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.63.0-DEV darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

Whitespace characters other than space or tab (for example, non-breaking space) are not taken into account for auto ID generation when `autoHeadingIDType` is set to `"github"` or `"github-ascii"`. For instance, the heading below produces an auto ID as follows.

`## Template(space)Name(nbsp)Convention` => `template-nameconvention`

The code below seems to be related to this issue.

https://github.com/gohugoio/hugo/blob/master/markup/goldmark/autoid.go#L88-L90

Regarding the example of nbsp, it's common to see nbsp getting mixed in the Markdown content, especially when the content is migrated from other web-based tools such as Confluence. We cannot expect every project to perform clean-up of their content, so this issue needs to be fixed.

**Comment by matteocontrini** [comment]
This might be helpful: https://golang.org/pkg/unicode/#IsSpace

**Comment by bep** [comment]
What does GitHub do with these? Do you have an example from GitHub? Note that if

## Template(space)Name(nbsp)Convention => template-nameconventio

Is what GitHub produces, then that is the correct behaviour according to "the spec".

**Comment by bep** [comment]
@jkboxomine can yo provide a failing test case?

**Comment by jkboxomine** [comment]
@bep , looks like that's the correct behavior for GitHub-compliant auto heading ID.

https://raw.githubusercontent.com/jkboxomine/goldmark-headingid/master/README.md
https://github.com/jkboxomine/goldmark-headingid#test-for-github-heading-id-generation-temporary

**Comment by bep** [comment]
@matteocontrini IsSpace returns true for both vertical and horizontal space, which may or may not be the correct in this case. I don't find GitHub's implementation of this; they seem to do it in some common "HTML pipeline" ...
