### ISSUE TITLE
render-link does not support HTML5

### ISSUE THREAD

**Issue by gj52** [gohugoio/hugo#6714]
### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version 0.62.2
</pre>
### Does this issue reproduce with the latest release?
YES
render-link.html with HTML5 syntax does not render!

`<a href={{ .Destination | safeURL }} {{ with .Title}} title="{{ . }}"{{ end }}{{ if strings.HasPrefix .Destination "http" }} target=_blank rel=noopener{{ end }}>{{ .Text }}</a>
`

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by gj52** [comment]
I think, this is NOT a support issue, but can be a bug!

this works:

`<a href="{{ .Destination | safeURL }}" {{ with .Title}} title="{{ . }}"{{ end }}{{ if strings.HasPrefix .Destination "http" }} target="_blank" rel="noopener"{{ end }}>{{ .Text }}</a>
`
hugo generates an error without apostrophes used.

**Comment by bep** [comment]
Your last example is perfectly fine HTML5.
