### ISSUE TITLE
Change minification flag to be global 

### ISSUE THREAD

**Issue by arturdryomov** [gohugoio/hugo#6724]
Running Hugo with the `--minify` flag does not affect assets. I. e. having a Markdown file which is converted to HTML with referenced CSS asset files will minify the HTML but not CSS. Seems like this can be solved by this:

```html
{{ $style := resources.Match "css/*.css" | resources.Concat "bundle.css" | minify }}
<link rel="stylesheet" href="{{ $style.RelPermalink }}" />
```

This way both HTML and CSS assets are minified. Great! But we have a mirror issue then. Running Hugo without the `--minify` flag will minify CSS and will not minify HTML.

From my point of view it would be better to follow the `--minify` flag globally — both for the target content (HTML in our case) and assets (CSS). This way it would be possible to have a staging environment without the minification and a production environment with it.

**Comment by bep** [comment]
I assume that you mean that this:

```
{{ $style := resources.Match "css/*.css" | resources.Concat "bundle.css" }}
```

Would, when run with `--minify` should behave like this?:

```
{{ $style := resources.Match "css/*.css" | resources.Concat "bundle.css" | minify }}
```

**Comment by arturdryomov** [comment]
Yep!

**Comment by arturdryomov** [comment]
@bep, it is possible to achieve the desired effect with latest configuration changes? Cannot connect dots together 🤔
