### ISSUE TITLE
Allow raw string literals in shortcode params

### ISSUE THREAD

**Issue by cup** [gohugoio/hugo#6726]
If you try a shortcode like this:

~~~
{{< sunday `monday tuesday` >}}
~~~

You get this:

~~~
unrecognized character in shortcode action: U+0060 '`'. Note: Parameters with
non-alphanumeric args must be quoted
~~~

It seems if Go allow this, Hugo should too:

https://golang.org/ref/spec#raw_string_lit

**Comment by cup** [comment]
A note: this does appear to be supported by Go proper:

https://golang.org/pkg/text/template#hdr-Examples

**Comment by hcwong** [comment]
Can I look into this? Thanks!

**Comment by bep** [comment]
@hcwong great, see https://github.com/gohugoio/hugo/blob/master/parser/pageparser/pagelexer_shortcode.go and the corresponding test file.
