### ISSUE TITLE
Hugo Debug error after running Hugo Server v.

### ISSUE THREAD

**Issue by jedidrew42** [gohugoio/hugo#6733]
### What version of Hugo are you using (`v0.62.1`)?

<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release? Yes

Heres my error:
Error: add site dependencies: load resources: loading templates: "/Users/jamesnorman/Desktop/projects/camundacom/camunda.com-new/themes/hugo-bootstrap-premium/layouts/_default/list.html:15:1": parse failed: template: _default/list.html:15: 

I am a NEWBIE to Hugo. After running hugo debug I get message:

DEBUG 2020/01/09 11:50:33 Add template file: name "404.html", baseTemplatePath "", path "404.html"
DEBUG 2020/01/09 11:50:33 Add template file: name "_default/list.html", baseTemplatePath "", path "_default/list.html"

These files exist. Any help is appreciated. I just started a new job and want to figure this out quickly.

**Comment by Jos512** [comment]
Hmm. The error message suggests that the files aren't there. That's odd. :thinking: 

Do you have them in the right folder, following [Hugo's lookup order](https://gohugo.io/templates/lookup-order/)?
