### ISSUE TITLE
Hugo to Wordpress Migration

### ISSUE THREAD

**Issue by jedidrew42** [gohugoio/hugo#6734]
I know we love the speed of Hugo but Wordpress offers so much more in speed as far as putting up content quickly without having to jump into command line and setting up JENKINS AND GITHUB.

So does anyone have a solution for writing a script to batch process all Markdown files into JSON.
I can then run a plugin to move JSON to build posts and pages with one click of button.

THANKS so much HUGO is amazing.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
