### ISSUE TITLE
Allow `querify` to take a lone slice argument.

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#6735]
`querify` helps build URL queries by passing an even number of arguments which are interpreted a set of `key/value` pair à la `dict`.

### Currently 
It is not possible to dynamically generate a set of `key/value` pair to be passed to `querify`.

### Proposal.

Enable the function to take a lone slice of strings argument which would be treated the same way the current string arguments are.

**Comment by bep** [comment]
Note to however implementing this that it cannot be a Go map (not ordered). I suspect improving the slice vs vararg situation discussed elsewhere may help.

**Comment by regisphilibert** [comment]
I edited the issue. I'M mostly thinking about maps created with `dict` and `merge` etc... so we would lose order. I don't see it as a problem in most cases but it might be.

**Comment by importhuman** [comment]
Can I work on this issue?

**Comment by moorereason** [comment]
@importhuman, absolutely.  If you have any questions, let us know.

**Comment by importhuman** [comment]
Is this sufficient to keep my local repository and branches updated and avoid conflicts later, or is there a better protocol?

```
git fetch upstream
git rebase upstream/master
```

**Comment by moorereason** [comment]
@importhuman, invest a few minutes into reading the [Contributing Guide](https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md).  It should help you get started.  It sounds like the **Fetching the Sources From GitHub** section would be of particular interest.

> are GitHub issues better for asking questions, or Discourse?

It depends on how many questions you have 😃, but I'd recommend the **dev** channel in the forums.  GitHub issue fatigue is real.  We don't need any more noise here than we already have.

**Comment by importhuman** [comment]
@moorereason I unintentionally updated mage in my branch, which changed the go.mod & go.sum files. Should I commit only the relevant code changes or these files as well? And do we have to do the [building hugo steps](https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#building-hugo-with-your-changes) after committing our changes, or is it meant for installing Hugo?
