### ISSUE TITLE
TOC doesn't contain <code> anymore (0.60)

### ISSUE THREAD

**Issue by Jos512** [gohugoio/hugo#6736]
### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.62.2/extended windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.13.4"
</pre>

### Does this issue reproduce with the latest release?
Yes, it's actually a new issue.

I could not find in the release notes documented changes to TOC's `<code>` behaviour.

### Before
Earlier, when our Markdown headings contained code, that code would appear as `<code>` in the TOC.

For example:

~~~md
## Hugo's `where` function
Performs filtering.

## `.RenderString` is new
~~~

Renders the following HTML on Hugo 0.55.6:

~~~html
<nav id="TableOfContents">
<ul>
<li>
<ul>
    <li><a href="#hugo-s-where-function">Hugo’s <code>where</code> function</a></li>
    <li><a href="#renderstring-is-new"><code>.RenderString</code> is new</a></li>
</ul>
</li>
</ul>
</nav>
~~~

Note the `<code>` around the words with a backtick.

### Now
With Hugo 0.62.2, `<code>` doesn't appear in the TOC anymore. For example, the same Markdown now makes this TOC:

~~~html
<nav id="TableOfContents">
<ul>
<li>
    <a href="#hugos-where-function">Hugo's where function</a></li>
    <li><a href="#renderstring-is-new">.RenderString is new</a></li>
</ul>
</nav>
~~~

### Repository to replicate
See https://github.com/Jos512/hugo-toc-issue

**Comment by bep** [comment]
>Yes, it's actually a new issue.

So, in Hugo 0.61 it behaved differently?

**Comment by Jos512** [comment]
> So, in Hugo 0.61 it behaved differently?

Sorry, I answered from my own perspective. :man_facepalming: 

To answer it properly, the 'issue' first happened in:

~~~plain
Hugo Static Site Generator v0.60.0/extended windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.13.4"
~~~

And the last good version was:

~~~plain
Hugo Static Site Generator v0.59.1/extended windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.13.1"
~~~
