### ISSUE TITLE
Line break is not working in markdownify

### ISSUE THREAD

**Issue by themefisherDev** [gohugoio/hugo#6737]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.60.2

</pre>

### Does this issue reproduce with the latest release?
maybe...

line break `<br>`is not working in markdownify

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
