### ISSUE TITLE
octocat emoji is not working in markdown.

### ISSUE THREAD

**Issue by schadokar** [gohugoio/hugo#6740]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

Hugo Static Site Generator v0.62.2/extended windows/amd64 BuildDate: unknown
</pre>

**Comment by bep** [comment]
What exactly do you mean by this?

**Comment by schadokar** [comment]
In the content page, the octocat emoji is not converting. If I am writing a post in .md and writing  `:octocat:` it is displaying as it is in html `:octocat:` instead of this :octocat: .

**Comment by VilhelmPrytz** [comment]
But aren't the `:emoji:` specific to GitHub (and not Hugo)?

**Comment by davidsneighbour** [comment]
:D octocat is github-only. It's not an emoji. It's a replacement in Github markup.

**Comment by schadokar** [comment]
Okay, understood. I thought markdown supports it. Thanks for the clarification.
