### ISSUE TITLE
Hugo <erblog theme> page displays wrong command

### ISSUE THREAD

**Issue by p-daemon** [gohugoio/hugo#6741]
### What version of Hugo are you using (`hugo version`)?
v0.55.6/extended darwin/amd64
<pre>
$ hugo version 

</pre>

### Does this issue reproduce with the latest release?
![image](https://user-images.githubusercontent.com/42153231/72242614-72217180-361c-11ea-9ec6-6690dfd36b24.png)
https://themes.gohugo.io/erblog/
The highlighted text should be replaced by `erblog`

**Comment by bep** [comment]
Thanks, but you need to raise this issue here: https://github.com/ertuil/erblog/issues
