### ISSUE TITLE
Link URLs with spaces broken in goldmark

### ISSUE THREAD

**Issue by legends2k** [gohugoio/hugo#6742]
<pre>
$ hugo version
Hugo Static Site Generator v0.62.2/extended darwin/amd64
</pre>

Markdown source in `something.md`

```
[Multi HDD/SSD Partitioning Scheme](https://wiki.debian.org/Multi HDD/SSD Partition Scheme)
```

I see that the rendered content doesn't become a link due to the spaces in the URL.  URL encoding the link fixes the issue.  With version 0.59 I didn't have this issue.

**Comment by legends2k** [comment]
Now, since _goldmark_ adheres to CommonMark, it may be that [the spec deems URL shouldn't have spaces](https://spec.commonmark.org/0.29/#link-destination) when specified in the markdown source.

However, real world URL do have spaces and there would be markdown files with such URLs.

Should Hugo URL-encode links and then pass it on to goldmark?

**Comment by bep** [comment]
>So if it's a spec-deviation, then this becomes an upstream bug, else Hugo might have to URL-encode and pass the link to goldmark?

A fix for this would need to live in Goldmark. I suggest you create an issue there and link back to this issue.

**Comment by legends2k** [comment]
Thanks @bep, but when I started a new issue in Goldmark, I was greeted with

> - [ ] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).

I see that dingus agrees with Goldmark in not making this a link; I don't think this would be accepted as a bug on Goldmark.

However Blackfriday used to accept it. Existing Hugo-compiled sites like mine would be broken due to the MD renderer shift.

**Comment by bep** [comment]
>However Blackfriday used to accept it. Existing Hugo-compiled sites like mine would be broken due to the MD renderer shift.

Hugo has made some adjustments to make this less painful, but we obviously cannot make Goldmark Blackfriday compatible. Creating and maintaining a CommonMark is, I'm guessing, a momentous task -- and I have no ambitions to make "Hugo overrides". If you cannot convince GoldMark to do the adjustments, I suggest you either 1) Encode your URLs or 2) Use Blackfriday.

**Comment by moorereason** [comment]
According to the CommonMark spec, you would need to enclose the link destination with angle brackets if you want to have whitespace:

```
[foo](<https://bar/a b/c d>)
```

**Comment by legends2k** [comment]
I've URL encoded all my links (it's a fairly small site).
