### ISSUE TITLE
JPG image resize processing result looks bad 

### ISSUE THREAD

**Issue by maxwedwards** [gohugoio/hugo#6745]
Tried using the inbuilt image resize processing but the results look poor to me. The following images were resized from 1200 pixels wide to 1250 with quality set to 100 to remove that as a factor. I used hugo and gimp to compare the images.

Resized in Hugo:
![image](https://user-images.githubusercontent.com/1204616/72254137-1a264300-35fb-11ea-8d6c-9ecbca08a914.png)

Resized in gimp:
![image](https://user-images.githubusercontent.com/1204616/72254172-2d391300-35fb-11ea-872f-20ba6ffeb9c8.png)

What is Hugo using to do the image resizing? Using `v0.59.1`.

**Comment by maxwedwards** [comment]
Jagged edges appear on images that are both reduced in size and increased in size.

**Comment by maxwedwards** [comment]
Looking at the code it looks like "github.com/disintegration/gift", that correct?

**Comment by bep** [comment]
It's gift, yes. You may want to try some other resample filter, I suspect the default was chosen for speed and not quality: https://gohugo.io/content-management/image-processing/#resample-filter

**Comment by maxwedwards** [comment]
RTFM!

For this image, Guassian and Linear both look great and Box and NearestNeighbor look bad.

I checked in GIMP and interpolation was set to "Cubic" which sounds box like to a layman.

Thanks @bep!
