### ISSUE TITLE
ref and relref support fallback

### ISSUE THREAD

**Issue by Colstuwjx** [gohugoio/hugo#6747]
Hi team,

The background is that I built a site which enabled multilingual, and the content is mainly written in english, and I did l10n jobs with some languages support, for example, zh-CN.

The expected behavior is that when I do localization from en to zh, if there is any in-doc link, it should target to local relative file, and if we didn't have the target file exist in current directory, it should redirect to the default language based dir.

For example, when I visit a page inside zh-CN pages, there is a link to `Next to scheduler`, which the original url is `/concepts/scheduling/scheduler`, and it would convert to `zh/concepts/scheduling/scheduler` if we actually placed `scheduler` page inside zh-CN pages, if NOT, it would convert to `/concepts/scheduling/scheduler`, which default is directly visit `en/concepts/scheduling/scheduler`.

I have seen the awesome feature about how to do [cross reference](https://www.gohugo.org/doc/extras/crossreferences/) with `ref` and `relref` builtin shortcodes, and it actually works basically, but we still need to ensure that a file exists in current relative dir, rather than `do fallback to default language based dir if the current dir didn't have this file`.

For now, if there is no file exists in current dir, `ref` and `relref` would make hugo build panic, and it's definitely not we expected. How about adding a flag or default fallback url for `ref` and `relref` functions, therefore, we could keep the localization job on-going without adding an useless untranslated page ONLY for placeholder purpose.

Thanks.

**Comment by Colstuwjx** [comment]
related issue: #2637 .

**Comment by bep** [comment]
You can configure ref/relref to produce warnings on "not found".

**Comment by Colstuwjx** [comment]
Hi @bep ,

The actual problem is about how to handle with intra-site linking in translation pages, could you give some suggestions about this? For now, we **MUST** add the `zh` lang prefix for the ref links in zh translation pages by manually, and I think there are three ways to make it automatically adding the lang prefix in translation pages:

1. Using `ref` and `relref`, but it would be painful if we didn't prepare the translated page, and you said we could configure it just product warnings;

2. Add a custom shortcode for adding the lang prefix according the current language and default language, and do fallback if current language doesn't exist, see [this PR](https://github.com/kubernetes/website/pull/18678);

3. Hugo could add something like `makeRefAddLangPrefixByDefault=true` such configuration, and adding the lang prefix for refs by default, if the current language page didn't exist, fallback to alternative language according the `languages` configuration, if no valid alternative language, panic and throws error;

Which one do you think is the suggested way to built the multilingual site? Or Do you have any other suggested ways for acheiving this goal?

It will be appreciated if you could give me some suggestions for fixing this issue, we're confused about this part for months...
Thanks.
