### ISSUE TITLE
deploy command does not write to file specified by --logFile

### ISSUE THREAD

**Issue by eddieh** [gohugoio/hugo#6749]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.62.2/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes, v0.62.2 is the latest.

**Comment by eddieh** [comment]
Does not write to the file when using `--debug` and/or `--verboseLog` flags too.

**Comment by Boehrsi** [comment]
Just tested this with `Hugo Static Site Generator v0.64.1/extended windows/amd64 BuildDate: unknown` and got an empty log file too.
