### ISSUE TITLE
Recursive watcher

### ISSUE THREAD

**Issue by cup** [gohugoio/hugo#6751]
I see currently Hugo is using a loop to add watched directories:

https://github.com/gohugoio/hugo/blob/ddd75f212110a3d6643a07301e377415f3d163bd/commands/hugo.go#L832-L836

Where `watcher` is defined here:

https://github.com/gohugoio/hugo/blob/ddd75f212110a3d6643a07301e377415f3d163bd/watcher/batcher.go#L14-L20

its probably known already, but just in case I wanted to point out that other
watchers are available with built in recursion, for example:

https://github.com/radovskyb/watcher

Example code:

~~~go
package main
import (
   "fmt"
   "github.com/radovskyb/watcher"
   "time"
)
func f_print(c_event chan watcher.Event) {
   for {
      fmt.Println(<-c_event)
   }
}
func main() {
   t_watch := watcher.New()
   t_watch.AddRecursive(".")
   go f_print(t_watch.Event)
   fmt.Println("watching")
   t_watch.Start(time.Millisecond * 400)
}
~~~

**Comment by bep** [comment]
Do you know of any recursive watcher that uses filesystem events and is cross-platform?

Have talked about adding a "poll based" watcher as a fall back in situations where fs events are not supported (Docker?), but this can never (I assume) beat the speed of what we have. And I think that if you look at the "recursive implementation" above, it is somehow walking the directory tree, which is exactly what we do.
