### ISSUE TITLE
Site Taxonomies are empty

### ISSUE THREAD

**Issue by t0nka** [gohugoio/hugo#6758]
in hugo 0.62.2 are my taxonomy pages gone. 

i v got a site with over 5000 pages. every page has at least one taxonomy tag

my hugo instances:
```
Hugo Static Site Generator v0.62.2/extended windows/amd64 BuildDate: unknown
Hugo Static Site Generator v0.62.2/extended mac/amd64 
```

**given**
```
{{ range .Site.Taxonomies }}
        {{ . }}
    {{ end }}
```
gives me:
`map[] map[]`
and no taxonomie term folder is generated

**expeted**:
+ a not empty map
+ created term folders

**hint**
in a prior version (0.55.x) everything worked fine

**Comment by bep** [comment]
It's hard to tell what's happening here with so little information. Do you have a site source you can link to?
