### ISSUE TITLE
</div> tag shows up inside <code> for some unknown reason.

### ISSUE THREAD

**Issue by ec1warc1** [gohugoio/hugo#6759]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version #issue occurs with this release:
Hugo Static Site Generator v0.62.2-83E50184/extended linux/amd64 BuildDate: 2020-01-05T18:57:23Z
</pre>

### Does this issue reproduce with the latest release?
This issue does not occur when using an older release:
<pre>Hugo Static Site Generator v0.57.2/extended linux/amd64 BuildDate: 2019-08-18T05:29:32Z</pre>
![docsy-homepage-extra-div](https://user-images.githubusercontent.com/23389201/72485474-d471a200-37d5-11ea-8c95-679d0db7de44.jpg)

This file seems to be where this is happening: $MY_HUGO_SITE/themes/docsy/layouts/shortcodes/blocks/link-down.html
`{{ with .Parent }}
{{ $id := $.Get "id" | default (printf "td-block-%d" ( add .Ordinal 1 ))  }}
{{ $color := $.Get "color" | default "blue" }}
<a class="btn btn-link text-{{ $color }}" href="#{{ $id }}"><i class="fa fa-chevron-circle-down" style="font-size: 400%"></i></a>
{{ else }}
{{ errorf "The link-down shortcode is supposed to be nested inside a shortcode"}}
{{ end }}`

**Comment by satotake** [comment]
From v0.60, Hugo uses `goldmark` as a default markdown handler instead `blackfriday` . 
While different behaviors between markdown processors result in it, this is specification of commonmark. (related https://github.com/gohugoio/hugo/issues/6553)

`./themes/docsy/layouts/shortcodes/blocks/cover.html` includes `{{ .Inner | markdownify }}` .
For example, the intermediate of `./content/no/_index.html` is

```html
        <p class="lead mt-5">TechOS kan nå lastes ned i <a href="#">AppStore!</a></p>
	<div class="mx-auto mt-5">

	</div>
</div>

```

(Note: blank line following tab char)

markdownify converts into

```html
....
	<p class="lead mt-5">TechOS kan nå lastes ned i <a href="#">AppStore!</a></p>
	<div class="mx-auto mt-5">
<pre><code>&lt;/div&gt;
</code></pre>
</div>
```

As a temporal workaround, you can avoid this by removing tab char just after `{{< blocks/link-down color="info" >}}`.

And this is not markdown but raw html so you can also avoid it by removing markdownify from `{{ .Inner | markdownify}}` in `cover.html`

**Comment by ec1warc1** [comment]
I removed | markdownify from cover.html and it worked. Thanks!
