### ISSUE TITLE
Newlines with shortcode params

### ISSUE THREAD

**Issue by cup** [gohugoio/hugo#6766]
If you try a shortcode like this:

~~~
{{< test `tuesday
wednesday` >}}
~~~

You get this:

~~~
Error: Error building site: "C:\sunday\content\monday.md:3:1": unmarshal failed:
invalid character '{' looking for beginning of object key string
~~~

Similarly this markup:

~~~
test

{{< test `tuesday
wednesday` >}}
~~~

Fails too:

~~~
Error: Error building site: "C:\sunday\content\monday.md:4:11": unterminated raw
string in shortcode parameter-argument: 'tuesday
'
~~~

This is disappointing as Go allows literal newlines in raw string literals:

> in particular, backslashes have no special meaning and **the string may
> contain newlines**.
 
https://golang.org/ref/spec#raw_string_lit

**Comment by bep** [comment]
Your first example looks like "something else". As to your other exampe; is there a reason not to allow newlines in raw parm strings, @hcwong ?

**Comment by hcwong** [comment]
> Your first example looks like "something else". As to your other exampe; is there a reason not to allow newlines in raw param strings, @hcwong ?

@bep Oversight on my part - I forgot about raw strings supporting new lines - I can submit a fix now, its a one-liner.
