### ISSUE TITLE
International Domain Name (IDN) uses percent-encoding instead of punycode-encoding

### ISSUE THREAD

**Issue by oncletom** [gohugoio/hugo#6767]
This is a follow-up on #3011.

I have an accented domain name (`détour.studio`). Its Punycode encoded counterpart is `xn--dtour-bsa.studio`.

Then I added this bit of code in my template to enable feed discovery:

```
{{ $Weeknotes := .Site.GetPage "weeknotes" }}
{{ with $Weeknotes.AlternativeOutputFormats.Get "rss" -}}
  {{ printf `<link rel="%s" type="%s" href="%s" title="%s • %s" />` .Rel .MediaType.Type .Permalink $.Site.Title $Weeknotes.Title | safeHTML }}
{{ end -}}
```

The problem is the page `.Permalink` property outputs the domain name with percent-encoding (as `d%C3%A9tour.studio`), which is considered as invalid.

Within a URL, the domain should be punycode-encoded, and the path should be percent-encoded.

Let me know if you have any question or clarification to decide how to address this issue.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.62.2/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by bep** [comment]
What happens if you set

```
baseURL = "https://xn--dtour-bsa.studio"
```

**Comment by oncletom** [comment]
Smart! It works perfectly like this.

Best fix is no need to fix at all.

Thank you so much 🙂
