### ISSUE TITLE
Temporary files not ignored when (re)building site

### ISSUE THREAD

**Issue by obar** [gohugoio/hugo#6773]
### What version of Hugo are you using (`hugo version`)?

v0.62.2-83E50184/extended linux/amd64

### Does this issue reproduce with the latest release?

Yes

I wasn't sure why I'd often be seeing the live preview of my site break on saves, when the state on the filesystem was fine. Digging into the `no such file or directory` message, I see this has to do with [Emacs lock files](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Locks.html#File-Locks) being followed where I don't believe they should be. The full message is in the form of:

```
Error: add site dependencies: load resources: loading templates: walk: Readdir: decorate: lstat $SITE_ROOT/layouts/partials/$USER@$MACHINE.$PID:$BOOT: no such file or directory
```

Of course the lock file is a symlink pointing to this path, with the prefix `.#` added to the file name in an unsaved, modified buffer.

This is true for both content and templating files, as long as a buffer is open with a modified version. This happens for both `hugo` and `hugo server` commands. It's easiest to reproduce by triggering a rebuild (running `hugo` or saving a change to a different file with `hugo server` running), and having a file open in emacs with a modified state so the lock symlink exists. It seems to also happen as a race condition when editing only a single file with `hugo server` running, where the rebuild reaches the lock symlink before emacs removes it.

I believe `hugo server` ignores events around temporary files so a rebuild isn't triggered, but does not ignore these files in the building of a site. I further believe that, well… that's the wrong behavior.

I have a fix that solves my issue, see imminent pull request.

**Comment by anoduck** [comment]
Brilliant work! Awesome Sauce!

**Comment by obar** [comment]
This bug has now fallen onto the third page of issues, but I believe it's an easy fix so would rather bump than let it get stale. It does affect people, reported [both here](https://github.com/gohugoio/hugo/issues/6526) and [on discourse](https://discourse.gohugo.io/t/unhelpful-error/20670).

Curious about work-arounds that people are using. @kaushalmodi, @masasam, looks like you use emacs and hugo together—could you comment on your approaches to this?

It seems like vim users would be affected as well, which has been [partially addressed for config files](https://github.com/gohugoio/hugo/issues/5646) already but not for other files.

**Comment by kaushalmodi** [comment]
@obar May be because I choose to not create auto-backup files in the same dir as the original file? I customize the `backup-directory-alist` in my Emacs config.. all backup files are dumped in the `/tmp/${USER}/.backups/`.

> could you comment on your approaches to this?

Also my content source is outside the `content/` dir that Hugo watches for content. I edit/create my content in a separate `content-org` dir (which sits parallel to the `content/` dir, and I use my `ox-hugo` package to export from Org to Markdown (which get created in the directory Hugo expects).

**Comment by masasam** [comment]
@obar I'm setting not to create a lock file as follows.

     (setq create-lockfiles nil)

**Comment by obar** [comment]
Thanks for the responses!

@kaushalmodi that's an interesting package, I should look into it. I believe the backups aren't such a concern. They do exist as files if hugo tries to process them, the error is caused by lockfiles which are implemented as symlinks to targets that don't exist. In your case that issue is sidestepped through not editing the files in place but rather generating them from a different path.

Should the docs warn emacs/vim users to configure their editors differently (a note with @masasam's customization of `create-lockfiles` for instance), or is it the wrong behavior for hugo to not be ignoring these files?

**Comment by obar** [comment]
This bug still reproduces per instructions in the first post. It has come up on discourse again [within the past month](https://discourse.gohugo.io/t/live-preview-rebuild-failed/25924). The work around for emacs users is to turn off lockfiles (see [previous discussion](https://github.com/gohugoio/hugo/issues/6773#issuecomment-590164784) in this thread), but that has other side effects for emacs users. I don't know about turning off temporary files in other editors.

Fortunately the patch doesn't need any updates, it works today on master (see [the latest comment](https://github.com/gohugoio/hugo/pull/6774#issuecomment-647641917) on the pull request).

Can I call in a fellow Canadian for help, could you review the pull request to close this bug @anthonyfok ? It's small and doesn't add any new logic so I would think the review should be painless… famous last words ;)

**Comment by bep** [comment]
So, I'm not adding a potentially breaking hard-coded filter to the filesystems.

What would solve this and be generally useful would be if I could configure:

```toml
[files]
ignore = ["assets/**", "content/**.tmp"]
```

Where "assets" etc. would match the "virtual component folder" in Hugo.

Or something, but that would obviously be more work.

**Comment by obar** [comment]
It seems like pre-1.0 is a decent time to introduce this, because the default ignore list should include temporary files generated by common editors and if this filter list is breaking then so would be another feature (although a configurable filter list could be changed more easily by the user).

I'm not wed to the solution I submitted; any fix to this would be great, but I can't see the case where it would break an existing site. Can you give an example? Most of these filters look at the extension and we can agree nobody is intentionally naming their to-be-processed files as `my_post.md.swp` :) The only filter on base of the file name itself (other than what we've discussed already in the pull request, the vim file 4913) involves excluding `#` and `.#` as a prefix, which wouldn't work for hugo content anyway as `#` is the separator for a url fragment. 

With all that said, I'm looking forward to a fix for this regardless of what it looks like. Thanks again!

**Comment by garrison** [comment]
It would be nice if Hugo would ignore temporary files entirely. However, the biggest problem for me is that *even once these temporary files disappear*, the only way I have found to get `hugo server` to notice and successfully serve the site again is to restart it.  This breaks my thought process and work flow, every time.

**Comment by obar** [comment]
@garrison Yes, the server crashes as it tries to process the temp file (in the emacs case, following a symlink to nowhere) so a restart is a must.

> a potentially breaking hard-coded filter to the filesystems

@bep I might have missed something but I don't believe such a filter *can* break any sites (see [my previous comment](https://github.com/gohugoio/hugo/issues/6773#issuecomment-650392273) for reasoning). If that's sound, could this approach work as a stopgap until a more elaborate ignoring system is built?

**Comment by obar** [comment]
This bug still reproduces, see [recent discussion in the associated pull request](https://github.com/gohugoio/hugo/pull/6774#issuecomment-748523547) for confirmation and a potential fix. Merry Christmas!

**Comment by scmbradley** [comment]
I'm also affected by this bug. I've resorted to just manually removing the lockfiles before running `hugo`. 

`hugo version -> Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2020-12-31T20:02:59Z`

**Comment by obar** [comment]
Yeah it's weird that this bug still exists. You don't have to do this manually though as you can apply the fix from the pull request, even though it's over a year old it still works today with no negative side effects. My best guess about why it hasn't been merged: this fix hurts the benchmarks that the project is [very](https://github.com/gohugoio/hugo/search?q=benchmark) [excited](https://github.com/gohugoio/hugo/releases/tag/v0.81.0) about. In practice the impact is negligible and the functionality is only improved, but worse numbers are worse numbers and they don't make for good release notes.

That's only a guess though, we haven't heard back about the only concern [raised](https://github.com/gohugoio/hugo/issues/6773#issuecomment-650362379) then [definitively alleviated](https://github.com/gohugoio/hugo/pull/6774#issuecomment-650288206) 9 months ago. There might be a different reason why Hugo still ships with a crash-and-burn Emacs and Vim bug! Happy Easter :rabbit2: :grin:

**Comment by jmooring** [comment]
I understand that globally disabling the creation of lock files within Emacs is undesirable for some users.

You can locally (per project) disable the creation of lock files by placing a `.dir-locals.el` file in the root of your project directory. For example:

```
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((nil . ((create-lockfiles . nil)))) 
```

I tested this briefly this evening and it seems to work. Given that lock files exist solely to prevent multliple users from simultaneously modifying the same file, within the context of a Hugo project this approach seem more like a solution than a workaround.

**Comment by obar** [comment]
Thanks Joe! I think your solution is a better one than applying the pull request changes and building hugo for new releases, as one has a limited number of hugo projects and this is quite managable. I've still been making sure that the pull request still works so that it could one day get merged.

I still believe it's a work-around for a bug, the default behavior for a tool shouldn't require the user to figure out things like that. Any thoughts there?

A minor side note, there are reasons to want lock files in a single user system.

**Comment by jmooring** [comment]
> the default behavior for a tool shouldn't require the user to figure out things like that

I agree. I have no idea why Emacs chooses to litter my directory with lock files and backup files. I guess that's just the way it's always been, and there's too much intertia to change the default behavior. Oh well, at lease it is configurable.

**Comment by moorereason** [comment]
> I still believe it's a work-around for a bug, the default behavior for a tool shouldn't require the user to figure out things like that. Any thoughts there?

This is not a bug (in either tool).  It's a default feature of hugo colliding with a default feature of emacs.  It's been shown that work-arounds exist in both tools, and @bep said 9 months ago that we won't be hard-coding ignore rules for this into hugo.

**Comment by jmooring** [comment]
@moorereason

Can we please close #6773 (this issue), #6774, and #7345?

**Comment by obar** [comment]
>  and @bep said 9 months ago that we won't be hard-coding ignore rules for this into hugo.

He said "I'm not adding a potentially breaking hard-coded filter" but it was since shown this approach *cannot* break a site. If there's a way to do this in Hugo without a hard-coded filter, should that be made the default? Or perhaps should an error message point a user to Joe's work-around? Just thinking about how to improve the user experience around this.

**Comment by JonathanDoughty** [comment]
As a 30+ year user of emacs who only learned about .dir_locals.el last year I can live with that solution. Still, it seems rather sad that hugo would crash when it stumbles across them 'littering' directories as emacs has been intentionally doing for decades. Had I not stumbled across the discourse discussion I might still be wondering why hugo was having a problem with a file emacs purposely makes difficult for users to even be aware of. Are they hugo's directories, that hugo can insist must be kept pristine for hugo's use? Or are they users' filesystems that hugo is simply visiting? Why doesn't hugo simply ignore all 'hidden' files?

**Comment by scmbradley** [comment]
I'm not sure I understand why the choice is between no filter and a hard coded filter? Why not just some option `.hugoignore` in analogy to how git ignores files? That seems like a decent compromise, and might have other uses? Or am I missing some aspect of the discussion (I haven't looked through the other related discussions,

**Comment by sanford** [comment]
A second vote for .hugoignore (like .gitignore).
