### ISSUE TITLE
Hugo ignores content files

### ISSUE THREAD

**Issue by adrian5** [gohugoio/hugo#6780]
### What version of Hugo are you using?

```
v0.62.2-83E50184/extended linux/amd64 BuildDate: 2020-01-05T18:57:23Z
```

### Does this issue reproduce with the latest release?

Yes

### Issue

I've added a [repo](https://github.com/adrian5/test-hugo-build-issue) to demonstrate the issue. Hugo seems to ignore files in a content section. Running the dev server (`hugo server`), one can make Hugo discover the files by simply saving them (to the filesystem) and refreshing that section's URL.

Similar [issue](https://discourse.gohugo.io/t/hugo-does-not-see-or-build-content-unless-i-save-a-change-to-disk/14819) another user ran into.

**Comment by bep** [comment]
Rename "index.md" to "_index.md".

**Comment by adrian5** [comment]
That indeed fixes the `events/` issue but then `hugo` doesn't produce a `/public/index.html` anymore, and likewise I get nothing under `localhost:1313/` from `hugo server`. How can I resolve this?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
