### ISSUE TITLE
shortcodes creating space after so commas in lists aren't correct.

### ISSUE THREAD

**Issue by dognoir** [gohugoio/hugo#6783]
### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.62.2 linux/amd64 BuildDate: 2020-01-05T20:44:31Z
</pre>

### Does this issue reproduce with the latest release?
 yes.

I've created a shortcode for external links.

`<a href='{{ .Get "link" }}' target="_blank">{{ .Get "text"}}</a>`

I'm using this in to create a list in a sentence where the 'here', 'there', and 'anywhere' are links
<pre>
  you can go here, there, or anywhere.
</pre>

what I get instead is spacing before punctuation 
<pre>
  you can go here , there , or anywhere .
</pre>

What do I need to do make this look right?

**Comment by pamubay** [comment]
you can use `trim` function. [Trim Function](https://gohugo.io/functions/trim/)

```
<a href='{{ .Get "link" }}' target="_blank">{{ trim (.Get "text") " " }}</a>
```

Next time, please post it on the forum first. [Hugo Discourse](https://discourse.gohugo.io/)

**Comment by dognoir** [comment]
T

> you can use `trim` function. [Trim Function](https://gohugo.io/functions/trim/)
> 
> ```
> <a href='{{ .Get "link" }}' target="_blank">{{ trim (.Get "text") " " }}</a>
> ```
> 
> Next time, please post it on the forum first. [Hugo Discourse](https://discourse.gohugo.io/)

This does not work.  It's not the text that has a blank. 

```
the ASUS {{< external_link text="RT-AC88U" link="https://www.asus.com/ca-en/networking/rt-ac88u/" >}}, {{< external_link text="RT-AX88U" link="https://www.asus.com/Networking/RT-AX88U/" >}}, {{< external_link text="RT-AC86U" link="https://www.asus.com/Networking/RT-AC86U/" >}}, {{< external_link text="RT-AC5300" link="https://www.asus.com/ce-an/networking/rt-ac5300/" >}}, 
```
produces this html:

```
 the ASUS <a href="https://www.asus.com/ca-en/networking/rt-ac88u/" target="_blank">RT-AC88U</a>
, <a href="https://www.asus.com/Networking/RT-AX88U/" target="_blank">RT-AX88U</a>
, <a href="https://www.asus.com/Networking/RT-AC86U/" target="_blank">RT-AC86U</a>
, <a href="https://www.asus.com/ce-an/networking/rt-ac5300/" target="_blank">RT-AC5300</a>
, <a href="https://www.asus.com/ca-en/Networking/ROG-Rapture-GT-AC5300/" target="_blank">GT-AC5300</a>
```
it seems to be putting a carriage return which forces a blank on the produced webpage.
