### ISSUE TITLE
Add imgproc shortcode (from docs) as a Hugo built-in

### ISSUE THREAD

**Issue by aormsby** [gohugoio/hugo#6787]
I was recently using the imgproc shortcode to throw up a profile picture, and I found that I was unable to position my image left, center, or right on the page. This was rather necessary to do some basic positioning after sizing my image smaller than my post width, and I made a quick style addition to my local shortcode to account for it.

I thought it might be useful to add to the embedded imgproc shortcode, but I was unable to find the file in the repo to add a PR. (I did find all the other embedded shortcodes, but not imgproc for some reason.) In any case, this may not be the best solution, but it does work. I'd love to hear what anyone thinks about it as a small upgrade to imgproc.

Here's a sample use case and the basic styling I added to the imgproc code listed in the Hugo docs.

**In markdown:**
```markdown
{{< imgproc "img/profile.jpg" Resize "220x" center />}}
```

**Shortcode addition (denoted by dashed lines):**
```html
{{ $original := .Page.Resources.GetMatch (printf "*%s*" (.Get 0)) }}
{{ $command := .Get 1 }}
{{ $options := .Get 2 }}

{{ $position := .Get 3 }}  <--------------------------------

{{ if eq $command "Fit"}}
{{ .Scratch.Set "image" ($original.Fit $options) }}
{{ else if eq $command "Resize"}}
{{ .Scratch.Set "image" ($original.Resize $options) }}
{{ else if eq $command "Fill"}}
{{ .Scratch.Set "image" ($original.Fill $options) }}
{{ else }}
{{ errorf "Invalid image processing command: Must be one of Fit, Fill or Resize."}}
{{ end }}
{{ $image := .Scratch.Get "image" }}
<figure style="padding: 0.25rem; margin: 2rem 0; background-color: #cccc;
--------------->
	{{ with $position}}
		{{ if eq . "right" }} margin-left: auto;
		{{ else if eq . "center" }} margin-left: auto; margin-right: auto;
		{{ end }}
	{{ end }} ">
<---------------
	<img style="max-width: 100%; width: auto; height: auto;" src="{{ $image.RelPermalink }}" width="{{ $image.Width }}" height="{{ $image.Height }}">
	<figcaption>
	<small>
	{{ with .Inner }}
	{{ . }}
	{{ else }}
	.{{ $command }} "{{ $options }}"
	{{ end }}
	</small>
	</figcaption>
</figure>
```

**Comment by bep** [comment]
I'm pretty sure `imgproc` isn't a built-in shortcode in Hugo (it's in the hugoDocs or the theme).

**Comment by aormsby** [comment]
Ooohhhh, I see. That's my mistake. I interpreted the sample in the docs as being a built-in thing on display, but it was just showing off a use case. Sorry about that.

I guess this can go two ways then - close this out as a misunderstanding OR consider adding a new built-in shortcode! It's pretty useful, and I imagine many could use the basic functionality right out of the box. Up to you. 🙂

**Comment by bep** [comment]
So, I wrote that shortcode and I do agree that it's useful. But I assume that there are lots of different opinions of how such a shortcode should look like, making it hard (maybe) to make something very general.

I'll keep this open and reword the title. I the meantime, feel free to copy the source from the docs.
