### ISSUE TITLE
Missing baseof error on use of `template` func in .63

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#6790]
### What version of Hugo are you using (`hugo version`)?
latest:
<pre>
Hugo Static Site Generator v0.63.0-745DDCBB/extended darwin/amd64 BuildDate: 2020-01-23T12:45:55Z
</pre>

Using the `template` function from an output format layout with no attached baseof, I get the following error: 
```
Error: Error building site: [en] page "/Users/cheribibi/Boulot/projets/hugo/baseof-issue/content/blog/_index.md": failed to resolve template: no baseof layout found for "blog/list.json.json":
```

Here is a simple test repo: https://github.com/regisphilibert/gohugo-template-issue

Template in question is [here](https://github.com/regisphilibert/gohugo-template-issue/blob/master/layouts/blog/list.json.json)

**Comment by bep** [comment]
I see why this fails, but when I "redid this" I assumed that this was how it always behaved. Are you saying that this did not fail in 0.62?

**Comment by regisphilibert** [comment]
> Are you saying that this did not fail in 0.62

Yes. It never failed. I use this kind of "same file" template often and never thought the `template` function was bound to a matching baseof template being present.

**Comment by bep** [comment]
OK, I will fix it. Sorry ... :-)
