### ISSUE TITLE
0.63: 404.html layout with base template does not work

### ISSUE THREAD

**Issue by dukebarman** [gohugoio/hugo#6795]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.63.1/extended darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

I couldn't use `{{ define "main" }}` variable in 404.html layout. It generates a warning:
```
INFO 2020/01/24 17:17:56 found no layout file for "HTML" for "404": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
INFO 2020/01/24 17:17:56 found no layout file for "HTML" for "404": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

If I delete this, it's okay but I need add own raw html code from main pages

**Comment by kaushalmodi** [comment]
@bep Thank you. I confirm this fix. 404.html now generates fine.

**Comment by mirkavolakova** [comment]
Unfortunatelly, I'm having the very same issue with Hugo `v0.63.2/extended darwin/amd64` 😞
