### ISSUE TITLE
unexpected trailing dash in auto heading ID for "# heading #"

### ISSUE THREAD

**Issue by lukpank** [gohugoio/hugo#6798]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.63.1/extended linux/amd64 BuildDate: unknown
</pre>

The issue originates in the following commit:

```
a82d2700 markup/goldmark: Make auto IDs GitHub compatible
```

### Does this issue reproduce with the latest release?

Yes

### Problematic document

Having the following markdown document (note trailing space after "Heading2"):

```
# Heading1 #
# Heading2 
```

### Correct auto heading IDs with blackFriday

If I turn on the "blackFriday" markdown parser with:

```
[markup]
  defaultMarkdownHandler = "blackFriday"
```

The generated heading IDs are both correct (no trailing dash):

```
$ ( hugo && grep 'h1 id=' public/tmp/index.html ) | tail -2
<h1 id="heading1">Heading1</h1>
<h1 id="heading2">Heading2</h1>
```

### Incorrect heading ID with goldmark

But If I use the default "goldmark" Markdown parser the generated ID
for the first heading contains unexpected trailing dash:

```
$ ( hugo && grep 'h1 id=' public/tmp/index.html ) | tail -2
  <h1 id="heading1-">Heading1</h1>
<h1 id="heading2">Heading2</h1>
```

### Input to Generate

I checked what enters `(*idFactory).Generate` (from `markup/goldmark/autoid.go`) and for the first heading the input converted to string is "Heading1 " (has a trailing space) and for the second heading it is "Heading2".

**Comment by obar** [comment]
Ran into the same thing (trailing whitespace not trimmed in symmetric heading style) and my solution was to use the asymmetric heading style. Any reason not to file this as a bug in [goldmark](https://github.com/yuin/goldmark) and close this one?

**Comment by jmooring** [comment]
Please reopen:

- This is reproducible with 0.73
- It does not appear to be a Goldmark bug (I will provide further information later today)
- Reproducible with autoHeadingIDType set to either `github` or `github-ascii`
- Not reproducible with autoHeadingIDType set to `blackfriday` 

Examples:

Markdown|Expected HTML|Actual HTML
:--|:--|:--
`# Foo #`|`<h1 id="foo">Foo</h1>`|`<h1 id="foo-">Foo</h1>`
`# Bar {.foo}`|`<h1 class="foo" id="bar">Bar</h1>`|`<h1 class="foo" id="bar-">Bar</h1>`

**Comment by inwardmovement** [comment]
fixes https://github.com/gohugoio/hugo/issues/6870
