### ISSUE TITLE
social icons are not visible

### ISSUE THREAD

**Issue by dogukanerel** [gohugoio/hugo#6800]
<pre>
$ hugo version
Hugo Static Site Generator v0.62.2/extended darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes!

-------------------------

There is no problem when adding social icons in my local environment. Runs smoothly on localhost.

![Screen Shot 2020-01-25 at 18 00 15](https://user-images.githubusercontent.com/19349444/73123104-20260780-3f9d-11ea-903b-427a1348d923.png)

But when i push these code to master, two social icons are not visible!

![Screen Shot 2020-01-25 at 18 00 30](https://user-images.githubusercontent.com/19349444/73123115-48156b00-3f9d-11ea-9849-6e772b3b08ab.png)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
