### ISSUE TITLE
Wrong operation result

### ISSUE THREAD

**Issue by inwardmovement** [gohugoio/hugo#6801]
**Hugo version:** `0.62.1`

---

`(eq $langURL $currentPage.RelPermalink)` returns false yet `$langURL` and `$currentPage.RelPermalink` have the same value.

Demo here:
https://github.com/algosphere/algo-website/blob/develop/layouts/partials/nav.html#L12-L13
https://preview-algo-website.netlify.com/fr/vision/

![image](https://user-images.githubusercontent.com/9438102/73124352-b73d9000-3f9a-11ea-9bf7-5c31aa3a68a8.png)

**Comment by bep** [comment]
The types are different.

**Comment by bep** [comment]
Note that there is another similar issue we will eventually fix
