### ISSUE TITLE
Build issue in Azure DevOps with latest (0.63.1) Hugo executable

### ISSUE THREAD

**Issue by insufficientclearance** [gohugoio/hugo#6802]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.63.1
</pre>

### Does this issue reproduce with the latest release?
Yes

I use Azure Pipelines to deploy site automatically after each commit using _latest_ version of Hugo (Windows 2019 environment). I noticed the tags and categories pages did not render any more - I checked and noticed new 0.63.1 version was in use, versus the 0.62.2 I use locally. I reverted the pipeline to 0.62.2 and that fixed problem, indicating an issue with 0.63.1.

In the attached screenshot you can see the difference in results after 24 hours (1/23 vs. 1/24).

![2020-01-25_143740](https://user-images.githubusercontent.com/1619363/73127058-73d62800-3f80-11ea-8e9d-83778e5056cf.png)

**Comment by bep** [comment]
Thanks for the report, but as we have tested this to work, it must be something "special" with your site. And that is not possible to debug without seeing the source. Could you provide a link to the site's source?

**Comment by insufficientclearance** [comment]
Your point is valid and I expected it - I'll see what I can do, the site is
not open-source at this time.

**Comment by insufficientclearance** [comment]
@bep I found the issue by trial and error - the taxonomies templates I use (e.g. /categories/list.html) have a _Hugo comment_ outside the `define`. From reading the docs I knew HTML comments can be a troublemaker but did not know about Hugo comments. Removing the Hugo comment made everything build correctly with 0.63.2.

```hugo
{{/* List of all categories. */}} {{ define "main" }}
<p>...</p>
{{ end }}
```

**Comment by bep** [comment]
See #6816
