### ISSUE TITLE
invalid .lastmod from git for page with non-ascii characters in its name

### ISSUE THREAD

**Issue by huguesdk** [gohugoio/hugo#6803]
### what version of hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.63.1 linux/amd64 BuildDate: 2020-01-24T01:20:28Z
</pre>

### does this issue reproduce with the latest release?
yes (0.63.1 is the latest version at the time of writing)

### how to reproduce
1.  create a new hugo site with `hugo new site lastmod_test`
2.  edit `config.toml` and add `enableGitInfo = true`
3.  create a new page with `hugo new eĥoŝanĝo_ĉiuĵaŭde.md`
4.  create a new page with `hugo new saluton.md`
5.  init a new git repository at the base of the site with `git init`
6.  add and commit everything with `git add . && git commit -m "initial commit"`
7.  run `hugo server -D`
8.  open http://localhost:1313/sitemap.xml

note that the lastmod date for “eĥoŝanĝo_ĉiuĵaŭde” is the date defined in the front matter, not the date of the git commit, while for “saluton” it is the commit date.

**Comment by reuixiy** [comment]
https://github.com/gohugoio/hugo/issues/3071

**Comment by huguesdk** [comment]
thanks! i fixed it by adding:
```
git config core.quotePath false
```
before calling `hugo` in my build configuration.
