### ISSUE TITLE
Revert to .Type = "page" when empty 

### ISSUE THREAD

**Issue by shantanugoel** [gohugoio/hugo#6805]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.63.1/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

The home page is supposed to be a "page" as mentioned here https://gohugo.io/templates/homepage/ 
However, from 0.63.0 onwards, the .Type for homepage does not return page anymore, rather blank. I believe this is a side effect of #6760 

This was discovered via my use of the beautifulhugo theme, which has this code to select appropriate styling for the subtitle depending on whether a page or post is being generated: https://github.com/halogenica/beautifulhugo/blob/1ff3894b84b1802433b58e22dd22f4eb46a49fa9/layouts/partials/header.html#L70 

Before 0.63.0, it generates "page-subheading" as the class as can be seen on https://shantanugoel.com/ 
0.63.0 onwards, it generates "-subheading" as the class.

**Comment by bep** [comment]
>The home page is supposed to be a "page" as mentioned here https://gohugo.io/templates/homepage/

I don't see anything about this on the page you link to. I don't see anything anywhere in the docs about this. 

The `.Type` gets the value from either 1) Frontmatter or if not set 2) The .Section. It's in the release notes.

**Comment by bep** [comment]
Thinking about this and the reasons behind #6760 are probably not important enough considering the potential for problems with existing sites. I did check the documentation before doing this and assumed this was a hidden and unused feature.

**Comment by shantanugoel** [comment]
Thanks for considering this. Just for completion sake, wrt your comment

> I don't see anything about this on the page you link to. I don't see anything anywhere in the docs about this.

This is what the link I mentioned says:

> Homepage is a Page and therefore has all the page variables and site variables available for use.

which I interpreted to mean that it should have the .Type as page.

**Comment by bep** [comment]
>which I interpreted to mean that it should have the .Type as page.

I admit it can be confusing, but those terms are not the same. `.Type` defaults to the section if not set with `type` in front matter (e.g. first path ... `blog`, `posts`, `docs`). The home page lives in the root folder, so it doesn't have a `.Section`.
