### ISSUE TITLE
footnoteReturnLinkContents not used by Goldmark

### ISSUE THREAD

**Issue by inwardmovement** [gohugoio/hugo#6807]
> v0.62.2/extended windows/amd64

The `footnoteReturnLinkContents` config parameter is not taken into account by Goldmark.

**Comment by bep** [comment]
Is this configuration specificed for Goldmark?

**Comment by inwardmovement** [comment]
I guess no: how can we customize the footnote return link content then?

As a workaround I did it with CSS:
```
.footnote-backref {
    visibility: hidden;

    &::before {
      content: "↑";
      visibility: visible;
    }
  }
```
