### ISSUE TITLE
Error: "C:\Users\wulu\hugo\config.toml:1:1": unmarshal failed: Near line 0 (last key parsed ''): bare keys cannot contain '�'

### ISSUE THREAD

**Issue by eMUQI** [gohugoio/hugo#6812]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.63.1-CE9ACEB7 windows/amd64 BuildDate: 2020-01-23T20:09:17Z
</pre>

### Does this issue reproduce with the latest release?
YES

Hi , when i follow [this page](https://gohugo.io/getting-started/quick-start/) to use hugo
i saw this error.
![image](https://user-images.githubusercontent.com/32332228/73180450-50fa6e00-4150-11ea-8bbb-b56d7fb2e894.png)
my config.toml
![image](https://user-images.githubusercontent.com/32332228/73180510-666f9800-4150-11ea-9556-d24c86e237fc.png)

how to slove this ?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by aasim-akhtar** [comment]
Faced the same issue when using powershell. Open config.toml file using sublime or any other editor
, Goto File-> Reopen with Encoding -> UTF-8. You'll then be able to see those NULL references <0x00>. Just delete them and you'll be good to go.

![sublimescreenshort](https://user-images.githubusercontent.com/43917573/118020652-f2bec200-b377-11eb-9b9b-67da56487151.jpg)

![vsscreenshot](https://user-images.githubusercontent.com/43917573/118020772-1eda4300-b378-11eb-81a7-56bdaac12b83.jpg)
