### ISSUE TITLE
Assets in page bundles

### ISSUE THREAD

**Issue by obar** [gohugoio/hugo#6814]
It would be nice if an `assets` directory could exist within page bundles, with the same behavior as the global version of that directory. That way the original file would not be included in the site by default, only if referenced and likely in a smaller resolution. An original, high resolution image could live a page bundle adjacent to relevant content, and only a smaller resolution image (potentially [with a watermark](https://github.com/gohugoio/hugo/pull/5725)) would make it into `public`.

**Comment by bep** [comment]
>It would be nice if an assets directory could exist within page bundles, with the same behavior as the global version of that directory. 

Isn't that what we got today?

**Comment by obar** [comment]
I don't think so… With a structure like this:

```text
content/
├── about
│   └── index.md
├── posts
│   ├── my-post
│   │   ├── content1.md
│   │   ├── content2.md
│   │   ├── index.md
│   │   └── assets
│   │       ├── image1.jpg
│   │       └── image2.png
│   └── my-other-post
│       ├── index.md
│       └── assets
│           └── image1.jpg
│
└── another-section
```

Running hugo creates the file `public/posts/my-post/assets/image1.jpg`

Does that clear up what I mean by assets directories within page bundles? I might not be using the terminology correctly :)

**Comment by bep** [comment]
OK, then I _think_ I understand.

In the next Hugo release, this is coming:

**Comment by obar** [comment]
Ah interesting, hadn't seen that. Different route to the same result. I'll close this proposal, thanks!
