### ISSUE TITLE
Comment in first row of templates makes the page go blank

### ISSUE THREAD

**Issue by shiftgeist** [gohugoio/hugo#6816]
![image](https://user-images.githubusercontent.com/30648730/73268361-2b667680-41db-11ea-96dd-9e62b1f8e7f3.png) (page is blank)

First row of `layouts/blog/single.html`
```
{{/*  TODO put images in blog folder  */}}
```

When I remove the comment, the page gets rendered.

URL of the page that disappears: http://localhost:8080/blog/article-name/

I am using `_defaults/baseof.html`, but this doesn't show either.

Or am i mistaken and it is a wanted feature?

### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.63.2-934EE21F/extended linux/amd64 BuildDate: 2020-01-27T12:20:42Z
</pre>

(via npm: hugo-bin)

### Does this issue reproduce with the latest release?

Yes

**Comment by bep** [comment]
>Or am i mistaken and it is a wanted feature?

It's a accidental side effect of Hugo 0.63. For now I suggest you move this comment inside the first `define`.

**Comment by shiftgeist** [comment]
That works, thanks!

**Comment by jstromergalley** [comment]
This is still broken in 65.3:

Hugo Static Site Generator v0.65.3-211BA42A windows/amd64 BuildDate: 2020-02-23T09:58:40Z

a base template that starts with a comment results in 0 pages rendered.
