### ISSUE TITLE
The comments page has a link to an indecent page!

### ISSUE THREAD

**Issue by hefnawi** [gohugoio/hugo#6819]
Hello,

I was just going through the various comments systems on this page: https://gohugo.io/content-management/comments/

But one of them,`txtpen` is probably hacked, it redirects to an indecent / obscene page.

Please update/remove it or fix the link issue.

Thanks!

P.S. Also please note that `utterance` is not working at the moment due to a CORS error.

**Comment by bep** [comment]
Looks OK to me. Maybe check your own DNS settings?

**Comment by wdoekes** [comment]
Out of curiosity I clicked some links, and yes:
the "txtpen" Disqus alternative links to https://txtpen.github.io/hn/ which has links to https://github.com/TXTPEN which in turn links to www.txtpen.com -- and _that_ is a defaced page.

@hefnawi: you should take this up with the owner of the txtpen account/domain (@0b01 ? @RickyHan  ?)

**Comment by hefnawi** [comment]
@wdoekes Thanks for your comment, I'll try to reach out to them. :+1:
