### ISSUE TITLE
--ContentDir does not seem to work in 63.1 or 63.2 as it did in 63.0

### ISSUE THREAD

**Issue by jstromergalley** [gohugoio/hugo#6823]
### What version of Hugo are you using (`hugo version`)?

<pre>
 v0.63.2-934EE21F windows/amd64 BuildDate: 2020-01-27T12:14:15Z
</pre>

### Does this issue reproduce with the latest release?
yes

In 63.0 I was able to do a build with a command similar to the following:

<pre>
D:/hugo/hugo_0.63.0_Windows-64bit/hugo.exe
  --source=D:/Projects/test/hugo_master/
  --contentDir=D:/Temp/test/content/dev/1121/
  --destination=D:/Temp/test/public/dev/1121/
</pre>

This produces for example 4 pages

With the same environment if I just switch to 63.1 or 63.2 then 0 pages are generated

<pre>
D:/hugo/hugo_0.63.2_Windows-64bit/hugo.exe
  --source=D:/Projects/test/hugo_master/
  --contentDir=D:/Temp/test/content/dev/1121/
  --destination=D:/Temp/test/public/dev/1121/
</pre>

Results in 0 pages

**Comment by jstromergalley** [comment]
Actually, this appears to be exactly the same issue:

https://discourse.gohugo.io/t/hugo-0-63-1-does-not-render-whole-site/23000/4

Any leading comment in single even just:

<pre>
{{- /* test */ -}}
</pre>

results in 0 files being rendered.

If I remove this line, the expected 4 files are rendered.

**Comment by bep** [comment]
#6816
