### ISSUE TITLE
Single whitespace character after custom link template for Goldmark

### ISSUE THREAD

**Issue by jsonmaur** [gohugoio/hugo#6832]
`Hugo Static Site Generator v0.62.1/extended darwin/amd64 BuildDate: unknown`

I needed a way to make markdown links open in a new tab with `target="_blank"`. Was able to do this in Blackfriday with the `hrefTargetBlank` config option, but for Goldmark I followed the instructions [exactly as outlined here](https://discourse.gohugo.io/t/how-to-open-link-in-new-tab-with-hugos-new-goldmark-markdown-renderer-in-v0-62-0/22540). This works, but for some reason it produces a single space character directly after the link. I've ensured `render-link.html` doesn't have any trailing spaces or lines.

Let me know if this issue would be better filed under the Goldmark library.

Source:
<img width="803" alt="Screen Shot 2020-01-30 at 19 41 39" src="https://user-images.githubusercontent.com/911274/73508254-9c06c200-4398-11ea-9a79-53e7efc7bcfc.png">

Rendered:
<img width="704" alt="Screen Shot 2020-01-30 at 19 42 32" src="https://user-images.githubusercontent.com/911274/73508281-afb22880-4398-11ea-912b-5a377cbe5b67.png">

Console:
<img width="912" alt="Screen Shot 2020-01-30 at 19 40 38" src="https://user-images.githubusercontent.com/911274/73508250-9ad59500-4398-11ea-866e-63ab403e4bba.png">

**Comment by bep** [comment]
> I've ensured render-link.html doesn't have any trailing spaces or lines.

I have added another test for this, to be sure, and that passes (no whitespace added) -- so I'm pretty sure the problem must live in your template, which I don't see.

**Comment by jsonmaur** [comment]
[I've created a sample repo](https://github.com/jsonmaur/hugo-issue-6832) that re-creates the problem, and [here's the built and deployed site](https://nostalgic-hawking-c1488a.netlify.com).

After further investigation, it only seems to happen if the link is directly followed by something other than whitespace. If it's directly followed by whitespace, it doesn't add an additional character.

**Comment by bep** [comment]
See https://github.com/jsonmaur/hugo-issue-6832/pull/1

**Comment by jakejarvis** [comment]
What code editor are you using? I had the same issue — was positive I didn't put a newline at the end but VS Code was adding one automatically every time I saved. Easy fix was to remove the newline with something like `nano`.  :)

**Comment by bep** [comment]
I used VS Code for this. I suspect there is a setting somewhere "to add newline automatic".  In many situations it makes sense, not this.

**Comment by jsonmaur** [comment]
Wait so how did you remove the trailing whitespace in that PR? I can't even tell it's there and am unable to get it removed in sublime, vim, or nano. [You can't even see it in GitHub](https://github.com/jsonmaur/hugo-issue-6832/blob/master/layouts/_default/_markup/render-link.html). Really strange--I've never had this issue before.

Thanks so much for taking the time to look into this.

**Comment by bep** [comment]
>Wait so how did you remove the trailing whitespace in that PR?

I ... deleted it. None of my editors inserts auto-newlines into HTML files. As an added note, I use Bud Parr's Hugo extension in VS Code, but I don't think that has anything to do with this.

**Comment by dirkkelly** [comment]
Thanks @bep, can confirm it was the trailing whitespace in our render-link file.

@jsonmaur if you want to fix it in sublime you need to change your settings to disable the automatic newline

![image](https://user-images.githubusercontent.com/81055/74219197-1dd6e380-4ce7-11ea-9352-ddacc4993dc6.png)

When there is no new line in a file on Github, it will show the red circle cross saying so, eg:
![image](https://user-images.githubusercontent.com/81055/74219226-33e4a400-4ce7-11ea-85c5-4d21863f9d28.png)

**Comment by jsonmaur** [comment]
Yeah, what's really strange is it was happening in other editors as well. Not just Sublime. But good to know the issue is on my end. I'll figure it out. Thanks for the help everyone.
