### ISSUE TITLE
Trigger a warning when .Paginate is called with different page collections

### ISSUE THREAD

**Issue by nerg4l** [gohugoio/hugo#6836]
### What version of Hugo are you using (`hugo version`)?

Hugo Static Site Generator v0.63.2/extended darwin/amd64 BuildDate: unknown

### Does this issue reproduce with the latest release?

Yes

### Issue

In [`docs/content/en/templates/homepage.md`](https://raw.githubusercontent.com/gohugoio/hugo/14a985f8abc527d4e8487fcd5fa742e1ab2a00ed/docs/content/en/templates/homepage.md) there is a code example which contain the following:

```
<!-- Note that .Pages is the same as .Site.RegularPages on the homepage template. -->
```

First of all when I use `.Pages` and `.Site.RegularPages` I get different results so probably the documentation is not up to date. `.Pages` contains the list of the types and `.Site.RegularPages` contains the list of all sites. This probably related to #6510.

However the interesting part happens when I use both on one site. It seems that they override each other.

To be able to reproduce I created https://github.com/nerg4l/hugo-pages-bug 

- When `.Pages` used first: https://github.com/nerg4l/hugo-pages-bug/pull/1/files
- When `.Site.RegularPages` used first: https://github.com/nerg4l/hugo-pages-bug/pull/2/files

The difference of the result is visible in `public/index.html` file.

**Comment by bep** [comment]
Hey, 

The docs is wrong about this, you are right about that. It would be good if you could raise an issue on the docs repo, or even better, a PR.

I had a quick glance at your repo and what happens is this:

* There can only be one paginator per `Page`, and it is created lazily
* So if you invoke `.Paginate` with a different set, later on, you still see the first one. 
* Remember, Hugo is a static site generator.

We used to issue a warning/error about this, not sure why we (I) removed that. I will reword the title of this issue.

**Comment by nerg4l** [comment]
It makes sense in that case. Is this behaviour/limitation of the paginator documented somewhere?

Also I will open a PR for the documentation.
