### ISSUE TITLE
The class property  of task-list 's <ul> needed in goldmark

### ISSUE THREAD

**Issue by AmazingRise** [gohugoio/hugo#6837]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.63.2/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes.

---

Dear developers,
I found a small issue of Hugo's new markdown handler `goldmark`.
Here is a piece of markdown code:
```markdown
- [X] task1
- [ ] task2 
```
In the old markdown handler `blackfriday`, the output HTML should be this:
```html
<ul class="task-list">
<li><label><input type="checkbox" checked="" disabled="" class="task-list-item"> task1</label></li>
<li><label><input type="checkbox" disabled="" class="task-list-item"> task2</label></li>
</ul>
```

But in the new `goldmark`, it will produce:
```html
<ul>
<li><input checked="" disabled="" type="checkbox">task1</li>
<li><input disabled="" type="checkbox">task2</li>
</ul>
```

The difference is the missing property `class="task-list"` of `<ul>`.
Please add this property so theme makers can customize the style of task list.
Then the big black point before each checkbox can be replaced by using class selector in CSS.
![2020-01-31_22-06](https://user-images.githubusercontent.com/8315221/73549460-9afb9080-447d-11ea-86e9-16c1d6d078dd.png)

Thanks!

**Comment by bep** [comment]
Thanks for the report. This looks like it could be an issue with Goldmark. Could you create an issue at https://github.com/yuin/goldmark/issues and link back to this issue so we could track it?

**Comment by AmazingRise** [comment]
Thanks, I've done.
https://github.com/yuin/goldmark/issues/96

**Comment by AmazingRise** [comment]
Closed. He didn't approve this feature. Thanks.

**Comment by yuin** [comment]
@bep @AmazingRise [go-gitea](https://github.com/go-gitea/gitea/blob/27757714d0420192e6139d1e4206446dcefe6531/modules/markup/markdown/goldmark.go#L149) uses their own renderer to render task lists(check boxes). It is easy to change how ast nodes are rendered into HTML in goldmark. If you need some classes for task lists, it is recommended to implement renderers or AST transformers.

**Comment by Fastidious** [comment]
@AmazingRise did you ended up doing some css fu to get rid of bullets on checkboxes list? If so, I would love it if you shared. I am in the same pickle as you were (or are).

**Comment by AmazingRise** [comment]
> @AmazingRise did you ended up doing some css fu to get rid of bullets on checkboxes list? If so, I would love it if you shared. I am in the same pickle as you were (or are).

Hi, @Fastidious 
I've given it up. Because I can't distinguish task lists from nomal lists in CSS.
The only way, I think, is to append property to task lists using Javascript.

**Comment by mdbenito** [comment]
A workaround:
1. Create `layouts/shortcodes/begin-task-list.html` to contain
```html
<span class="begin-task-list"></span>
````
2. Add the following to your CSS:
```css
span.begin-task-list + ul {
    list-style: none;
}
```
3. Use the shortcode before each task list in your markdown:
```markdown
{{< begin-task-list >}}
- [ ] This task won't have a bullet point in the rendered html
- [ ] Neither will this one 
```
