### ISSUE TITLE
Hugo fails to render template when comments present outside blocks

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#6840]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 63.0

</pre>

### Does this issue reproduce with the latest release?

Yes

----

Turns out since .0.63  (maybe the baseof refactoring) adding a comment at the root of a template  (not within blocks) prevents Hugo from building the page. It creates an empty file.

```
{{/* Test comment */}}
{{ define "main" }}
  <h1>{{ .Title }}</h1>
  {{ .Content }}
{{ end }}
```

**Comment by bep** [comment]
A duplicate, and fixed.

**Comment by regisphilibert** [comment]
Sorry about that.

**Comment by bep** [comment]
I've been doing a bug fix day today. I'm going to cut a small release on Monday.
