### ISSUE TITLE
absURL doesn't work with the variable

### ISSUE THREAD

**Issue by nianiaJR** [gohugoio/hugo#6844]
### What version of Hugo are you using (`hugo version`)?
v0.60.1

### Does this issue reproduce with the latest release?
yes

### Problem
the `absURL` function works well like this:
```html
<a href="{{"test" | absURL }}">test</a>
```
but doesn't work when used with variable like this:
```html
<a href="{{.testLink | absURL }}">test</a>
```
How to fix this? thanks.

BTW, the discuss forumn may be too slow to open: https://discourse.gohugo.io/.

**Comment by onedrawingperday** [comment]
The forum functions perfectly well and you need to post your question there.

This is the Hugo bugs and new features tracker. 
You will not get a response for a support question here.

Please close this issue.

**Comment by nianiaJR** [comment]
Ok, done. thanks.
