### ISSUE TITLE
Generate Gopher hole content

### ISSUE THREAD

**Issue by exitnode** [gohugoio/hugo#6845]
It would be great if I could generate content for a gopher hole in parallel to a static web site. This way I could serve the same content to both worlds without any additional manual effort.

**Comment by exitnode** [comment]
I just found this article how it can be done: https://jfm.carcosa.net/blog/computing/hugo-gopher/

**Comment by davidsneighbour** [comment]
And when you are done setting this up don't forget to post to discourse.gohugo.io how you did it. Sounds interesting.

**Comment by bep** [comment]
We need a better "how should a proposal look like", but we obviously need more than this:

* Why is this useful? Is this something most/many people would benefit from?
* How would this fit into Hugo? How would it work, look like?
