### ISSUE TITLE
Automatically sign the number of each image (figure) 

### ISSUE THREAD

**Issue by bosonbeard** [gohugoio/hugo#6846]
I have a  Markdown file. It has images like this:
`![ Some Title](/img/exmpl.png " Some Title"`)`

Will be great if Hugo can automatically number images using hugo so that I get output like example on bellow.

    <figure>
    <img src="/img/exmpl.png" title="Some Title" ><figcaption>Fig1. Some Title</figcaption>
    </figure>

**Comment by thewebmastercom** [comment]
Why not just use CSS Counter, and ::before Selector to add content?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters

**Comment by bosonbeard** [comment]
> Why not just use CSS Counter, and ::before Selector to add content?
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters

excellent! Thanks! I did not know that it was possible.
