### ISSUE TITLE
proposal: Add Resource.ModuleInfo()

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6848]
This relates to:

* #5535
* https://discourse.gohugo.io/t/get-module-source-from-page/23208/4?u=bep

We currently have the related `.Page.File` and `.Page.GitInfo`. `.Page.File` I suspect was intended mostly for internal Hugo use, is fairly big, and is only available on `Page`. So is `GitInfo`.

This proposal suggests we add a new `ModuleInfo()` method on all of the "module backed" resources, which is all of them (excluding `resources.FromString`...).

This means that you can do something ala the below even for resources fetched via `resources.Get`:

```html
{{ $bulma := resources.Get "assets/bulma.sass" }}
{{ with $bulma.ModuleInfo }}
{{ .ModulePath }} => github.com/jgthms/bulma
{{ .Path }} => bulma.sass
{{ with .VCSInfo }}
{{ .AbbreviatedHash }}
{{ end }}
{{ end }}
```

... and of course the same for page resources...

```go

type ModuleInfo interface {
	// Returns the path to this module.
	// This will either be the module path, e.g. "github.com/gohugoio/myshortcodes",
	// or the path below your /theme folder, e.g. "mytheme", or empty
	// if it is the project mount.
	// Slashes are Unix forward slashes.
	ModulePath() string

	// The module version as assigned by Go Modules.
	ModuleVersion() string

	// Path to this resource relative to ModulePath.
	// Note that this will contain the original name before any mounts configuration,
	// and may be different from the one you get when doing .Page.Path.
	// A typical use case would be to construct an URL to this resource on GitHub.
	// Slashes are Unix forward slashes.
	// E.g. "layouts/shortcodes/hello.html".
	Path() string

	// Returns revision info from the version control system backing this file,
	// if any.
	// We currently only support Git.
	VCSInfo() VCSInfo
}
```

The hardest part about this issue is naming, so please help @regisphilibert @moorereason  @onedrawingperday and gang.

**Comment by moorereason** [comment]
`Path` and `ModulePath` is a little confusing, but I can't think of anything clearer.

My only question is about `VCSInfo`. `Page` already satisfies `GitInfoProvider`.  Wouldn't it be just as useful to have resources in the local repo provide GitInfo?  Can we simply extend `Resource` to satisfy `GitInfoProvider` and then have `Page` and `Resource` be module-aware?  So, if you wanted the Git/VCS info, you would do:

```go
{{ $bulma := resources.Get "assets/bulma.sass" }}
{{ with $bulma.VCSInfo }}
{{ .AbbreviatedHash }}
{{ end }}
```
instead of:
```go
{{ $bulma := resources.Get "assets/bulma.sass" }}
{{ with $bulma.ModuleInfo }}
{{ with .VCSInfo }}
{{ .AbbreviatedHash }}
{{ end }}
{{ end }}
```

**Comment by regisphilibert** [comment]
All makes me think that those kind of "meta" could be grouped under the same method.
```
{{ $bulma := resources.Get "assets/bulma.sass" }}
{{ with $bulma.Info }}
  {{ with .Module }}
    {{ .Path }}
  {{ end }}
  {{ with .Git }}
    {{ .AbbreviatedHash }}
  {{ end }}
{{ end }}
```

This might be a lot of work, but would make sure we don't cluster the object root with too many future "info" additions.

This reflection is of course limited by my knowledge on the usgage of `.GitInfo` etc...

**Comment by bep** [comment]
@moorereason the main thought about moving away from `Page.GitInfo` is to 1) reduce the rather big Page interface into smaller parts and 2) The interface above groups tightly related methods -- they will typically be implemented in a struct; e.g. I need the module-info to be able to extract the Git info.

I'll let this linger a little.

**Comment by SirUli** [comment]
@bep did the lingering lead to new ideas? I could really use this :)

**Comment by siddhpant** [comment]
Bump. Is this gonna happen anytime soon?
