### ISSUE TITLE
Add poll based file change detection as fallback

### ISSUE THREAD

**Issue by aormsby** [gohugoio/hugo#6849]
### What version of Hugo are you using (`hugo version`)?

<pre>
v0.63.2
</pre>

### Does this issue reproduce with the latest release?
Yes, this is the latest.

### The issue - virtual dev environment doesn't seem to take /static/style.css into account on reloads

`hugo server -D`
I use the virtual environment a lot (it's great!), but I've noticed that the styles I add to my static.css file are missing when the site reloads on saving a file. The process must be skipping over them somehow. I can force them to be included by saving static.css - the system must include it since it's a marked file at that point. Otherwise, my styles disappear.

This isn't a huge deal, but it's kind of a pain to have to save my changes and then re-save static.css again. If someone could look into this, I'd really appreciate it.

**Comment by bep** [comment]
https://github.com/fsnotify/fsnotify/issues/9
