### ISSUE TITLE
Add yamlify or whatever function to marshal a content to YAML

### ISSUE THREAD

**Issue by onionltd** [gohugoio/hugo#6852]
I have YAML files inside /data directory, in my archetypes/services.yaml I want to do the following to automatically generate content files:

```
---
title: "{{ replace .Name "-" " " | title }}"
date: {{ .Date }}
url: /services/{{ .Name }}.html
---

{{ index $.Site.Data.oniontree.unsorted .Name |  yamlify }}
```

From the shell:

```
$ hugo new services/bbc.yaml
```

Unfortunatelly a yaml marshaller isn't available.

**Comment by bep** [comment]
We have transform.Remarshal used for similar things on the docs site

**Comment by onionltd** [comment]
```
---
title: "{{ replace .Name "-" " " | title }}"
date: {{ .Date }}
url: /services/{{ .Name }}.html
---

{{ index $.Site.Data.oniontree.unsorted .Name |  transform.Remarshal "yaml" }}
```

Did the trick. Why isn't it documented? I see you have already answered same question before: https://discourse.gohugo.io/t/display-yaml-as-text/19830.
