### ISSUE TITLE
Cascade does not work on pages without front matter

### ISSUE THREAD

**Issue by atishay** [gohugoio/hugo#6855]
### What version of Hugo are you using (`hugo version`)?

0.64.0

### Does this issue reproduce with the latest release?
Yes

See https://github.com/atishay/nofm for minimal reproduce-able website. It is deployed on https://confident-leakey-3dfdde.netlify.com

There is the cascade front matter in _index.md

```yaml
cascade:
  key: "Hello"
```

The key shows up in `a.md` and `b.md` which have front matter but not in `c.md` where it is a plain markdown document.

**Comment by bep** [comment]
Fixed in eada236f87d9669885da1ff647672bb3dc6b4954
