### ISSUE TITLE
Warning when building site generated using hugo new site

### ISSUE THREAD

**Issue by aral** [gohugoio/hugo#6859]
### What version of Hugo are you using (`hugo version`)?

v0.64.0-241DB8F7 linux/amd64 BuildDate: 2020-02-04T09:10:23Z

### Does this issue reproduce with the latest release?

Yes.

### Platform

Pop!_OS 19.10 (based on Ubuntu 19.10)

### To reproduce

1. `hugo new site my-site`
2. `cd my-site`
3. `hugo`

### What should happen

Output should resemble the following, with no errors or warnings on a newly-generated site.

```sh
Building sites…

                   | EN  
-------------------+-----
  Pages            |  3  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 12 ms
```

### What actually happens

Output resembles the following with three cryptic warnings:

```sh
Building sites … WARN 2020/02/06 13:03:11 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/02/06 13:03:11 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/02/06 13:03:11 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN  
-------------------+-----
  Pages            |  3  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 12 ms
```

### Proposed fix

Fix whatever is causing the warnings so that a new site, generated using the official command, builds without warnings or errors.

The minimum fix appears to be the following:

1. Add an empty _index.html_ file into the generated _layouts/_ folder
2. Add `disableKinds = ['taxonomyTerm']` to the generated _config.toml_ file.

With those two alterations, a site generated using `hugo new site` builds without warnings or errors.

The above is most likely __not__ also the ideal fix, which might include having the generated index.html file contain some useful Getting Started information for steps the person can take next to start customising the site.

**Comment by ahmetb** [comment]
Funny enough `disableKinds` is supposed to fix this, however in my config.yaml I have the following and I still get this warning for both kinds (layout file doesn't exist –but then, it shouldn't be needing it as OP notes).

```yaml
disableKinds:
- taxonomy
- taxonomyTerm
```

**Comment by carloseabade** [comment]
Hi everyone. I tried fixing this issue with the pull request above. I added a simple index.html similar to https://gohugo.io/ front page. I also disabled kind 'taxonomy'.
This prevented all the warnings.

@bep give me any feedback if this is the desired behaviour, or if i added too much to the skeleton.

**Comment by jmooring** [comment]
@aral 

With v0.119.0

```text
$ hugo new site my-static-site
Congratulations! Your new Hugo site was created in /home/jmooring/temp/my-static-site.

Just a few more steps...

1. Change the current directory to /home/jmooring/temp/my-static-site.
2. Create or install a theme:
   - Create a new theme with the command "hugo new theme <THEMENAME>"
   - Install a theme from https://themes.gohugo.io/
3. Edit hugo.toml, setting the "theme" property to the theme name.
4. Create new content with the command "hugo new content <SECTIONNAME>/<FILENAME>.<FORMAT>".
5. Start the embedded web server with the command "hugo server --buildDrafts".

See documentation at https://gohugo.io/.

$ cd /home/jmooring/temp/my-static-site/
$ hugo new theme my-theme

Creating new theme in /home/jmooring/temp/my-static-site/themes/my-theme

$ echo "theme = 'my-theme'" >> hugo.toml
$ hugo new content notes/follow-instructions.md

Content "/home/jmooring/temp/my-static-site/content/notes/follow-instructions.md" created

$ hugo server --buildDrafts
```

**Comment by jmooring** [comment]
Fixed with https://github.com/gohugoio/hugo/pull/11367.

Related open issue: https://github.com/gohugoio/hugo/issues/11373
