### ISSUE TITLE
Goldmark math render issue

### ISSUE THREAD

**Issue by panda-z** [gohugoio/hugo#6864]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.64.0-241DB8F7 windows/amd64 BuildDate: 2020-02-04T09:09:27Z
</pre>

### Does this issue reproduce with the latest release?
Yes

Goldmark will touch the math code. E.g., `\\` will be rendered as `\<br>`, and `&` will be escaped to `&amp;`.

Example: 
```
$$
\begin{equation}
  \begin{aligned}
  x &= a+b\\ 
  &= c+d
  \end{aligned}
\end{equation}
$$
```

The above math code will be rendered as (mmark)

```
<p><span  class="math">\[
\begin{equation}
  \begin{aligned}
  x &= a+b\\ 
  &= c+d
  \end{aligned}
\end{equation}
\]</span></p>
```

and (Goldmark)
```
<p>$$
\begin{equation}
\begin{aligned}
x &amp;= a+b\
&amp;= c+d
\end{aligned}
\end{equation}
$$</p>
```

**Comment by chazeon** [comment]
They are trying to work out a solution at #6544 #6694.

**Comment by panda-z** [comment]
Thanks. So this is a duplicated issue.
