### ISSUE TITLE
Details tag for collapsible section not working in 0.64.0

### ISSUE THREAD

**Issue by cwholmes** [gohugoio/hugo#6865]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.64.0-241DB8F7 windows/amd64 BuildDate: 2020-02-04T09:09:27Z
</pre>

### Does this issue reproduce with the latest release?

Create an md file with the following contents:
```
<details>
  <summary>Collapsible</summary>

  ```xml
  <p>I am xml</p>
  `` -- should have an extra one, but don't want this closed.
</details>
```

Should look like this:
<details>
  <summary>Collapsible</summary>

  ```xml
  <p>I am xml</p>
  ```
</details>

**Comment by pamubay** [comment]
Set Goldmark `unsafe` option to `true`, 
```toml
[markup.goldmark.renderer]
      unsafe = true
```
Check [Goldmark Documentation](https://gohugo.io/getting-started/configuration-markup#goldmark)
