### ISSUE TITLE
autoHeadingIDType: github punctuation handling

### ISSUE THREAD

**Issue by inwardmovement** [gohugoio/hugo#6870]
### Hugo version
<pre>
Hugo Static Site Generator v0.64.0/extended windows/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

---

Punctuation characters preceded by a space generate a `-`, for example with "french question ?" :
```
/faq/#french-question-
```

which is ugly and makes no sense.
Could you make any trailing `-` be striped from autoID generation please, as it is with `autoHeadingIDType: blackfriday` ?

I'm not using `autoHeadingIDType: blackfriday` as I guess it will be deprecated someday.

**Comment by bep** [comment]
>I'm not using autoHeadingIDType: blackfriday as I guess it will be deprecated someday.

It will not.

**Comment by inwardmovement** [comment]
Following the fix for https://github.com/gohugoio/hugo/issues/6798, can this be solved too please?
`# Test !` outputs `test-` with autoHeadingIDType: github
