### ISSUE TITLE
Add hugo.IsProduction shortcut

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6873]
A common snippet in header files is this:

```
{{ if eq hugo.Environment "production" }}
{{ end }}
```

`production` is the default environment you get when running `hugo`, `development` when running the server.

I think it would be useful and possibly avoid some typos if we created a function for the above, e.g:

```
{{ if hugo.IsProduction }}
{{ end }}
```

PRs welcomed, but remember documentation.

**Comment by hcwong** [comment]
Can I take this?

**Comment by bep** [comment]
@hcwong yes, please. But remember to put a line in the documentation about it (in this repo)

**Comment by chalin** [comment]
> `production` is the default environment you get when running `hugo`, `development` when running the server.

@bep - are these defaults documented somewhere on gohugo.io? Thanks.
