### ISSUE TITLE
Allow scheduling of section pages (_index.md)

### ISSUE THREAD

**Issue by Jos512** [gohugoio/hugo#6875]
I use sections to categorise content. Compared with Hugo's taxonomies, sections have several benefits. They can define custom titles, params, and contain content. Since recently they can also define settings for all posts in a particular section.

But I also schedule all my posts in advance. And that's a problem since with Hugo 0.64, a `date` or `publishDate` front matter variable on a section page has no effect. Those pages are simply rendered, even with future dates. As a result I get empty categories, since the posts haven't published yet.

A good solution for my use case is when the actual section page (`_index.md`) can be scheduled like regular content pages.

(Related: [issue 6312](https://github.com/gohugoio/hugo/issues/6312), which is about section pages respecting the `draft` front matter variable.)

**Comment by bep** [comment]
This will be fixed in next Hugo.

**Comment by Jos512** [comment]
That is great. Thank you. :bowing_man: :slightly_smiling_face:
