### ISSUE TITLE
Provide a way to check homepage of paginated index

### ISSUE THREAD

**Issue by Jos512** [gohugoio/hugo#6876]
I need to run custom Hugo template code on the website's homepage. But I also use pagination to lists posts on that page.

So there are several index pages:

- `example.com/` (<- the website's homepage)
- `example.com/page/2/`
- `example.com/page/3/`

It doesn't seem possible with Hugo 0.64 to somehow check if the current page is `example.com/`.

I tried the variables below. They all return the same value on the website's homepage (`example.com/`) *and* all paginated pages (`example.com/page/n`).

- `.IsHome`
- `.RelPermalink`
- `.Kind`
- `.IsNode`
- `.Permalink`
- `.Content`, a custom param, and `.UniqueID` of `content/_index.md`

(The associated forum topic is [here](https://discourse.gohugo.io/t/how-to-check-if-current-page-is-homepage/23301).)

**Comment by moonbooth** [comment]
I'm still keen on this situation being improved. Would improve the SEO of all paginated Hugo sites.

**Comment by bep** [comment]
Can you not check if the page number == 1?

**Comment by Jos512** [comment]
In my case I want to check in the header and footer whether the current page is the main index page. But the paginator is defined in `index.html` and the pagination renders in `pagination.html`.

I haven't found a way to communicate the page number from outside `pagination.html` to the other Hugo template files.

**Comment by bep** [comment]
The pagination performed lazily, so I would face the same issue as you if I wanted to implement `.IsPaginatedHomePage`  or something.

If your paginator is defined in `index.html` you can get the page number from there on. If you need them in your base template, try "blocks".

**Comment by Jos512** [comment]
> If you need them in your base template, try "blocks".

That's a good idea, thanks.

> The pagination performed lazily, so I would face the same issue as you if I wanted to implement .IsPaginatedHomePage or something.

Gotcha.

I'll close the issue now because it's not possible. Even if it were possible to have Hugo render websites in a different way, it's not worth the effort for this small request.

Thanks for taking a look at this issue. :slightly_smiling_face:
