### ISSUE TITLE
unable to extend theme

### ISSUE THREAD

**Issue by maikelmclauflin** [gohugoio/hugo#6878]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.64.1/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
yes

i'm using the docuapi theme from `github.com/bep/docuapi` seems like if i don't have a file present in my layouts folder structure that does not exactly match my theme it fails, which kinda defeats the purpose of this line, at least to me:
```
For static, layouts (templates), and archetypes files, these are merged on file level. So the left-most file will be chosen.
```
i would assume that i don't need to copy the whole theme into my repo to the folder where it would be. perhaps i am doing something wrong? i have had some spotty performance with hugo overall. not sure if brew had a bad install or what happened.
```
hugo server -D
Building sites … ERROR 2020/02/10 18:18:29 render of "page" failed: "/Users/michaelmclaughlin/go/src/github.com/brave-intl/internal-2/layouts/_default/baseof.html:8:8": execute of template failed: template: _default/single.html:8:8: executing "_default/single.html" at <partial "styles.html" .>: error calling partial: partial "styles.html" not found
ERROR 2020/02/10 18:18:29 render of "home" failed: "/Users/michaelmclaughlin/go/src/github.com/brave-intl/internal-2/layouts/_default/baseof.html:8:8": execute of template failed: template: _default/list.html:8:8: executing "_default/list.html" at <partial "styles.html" .>: error calling partial: partial "styles.html" not found
ERROR 2020/02/10 18:18:29 render of "page" failed: "/Users/michaelmclaughlin/go/src/github.com/brave-intl/internal-2/layouts/_default/baseof.html:8:8": execute of template failed: template: _default/single.html:8:8: executing "_default/single.html" at <partial "styles.html" .>: error calling partial: partial "styles.html" not found
ERROR 2020/02/10 18:18:29 render of "section" failed: "/Users/michaelmclaughlin/go/src/github.com/brave-intl/internal-2/layouts/_default/baseof.html:8:8": execute of template failed: template: _default/list.html:8:8: executing "_default/list.html" at <partial "styles.html" .>: error calling partial: partial "styles.html" not found
Built in 74 ms
Error: Error building site: failed to render pages: render of "page" failed: "/Users/michaelmclaughlin/go/src/github.com/brave-intl/internal-2/layouts/_default/baseof.html:8:8": execute of template failed: template: _default/single.html:8:8: executing "_default/single.html" at <partial "styles.html" .>: error calling partial: partial "styles.html" not found
```
i tried to rebuild the whole project and just used hugo commands as much as i could
```
hugo new site .
```
downloaded the theme directly and put it into themes folder: https://github.com/bep/docuapi

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

Also, if you have a problem with a specific theme, take that on the theme repo.
