### ISSUE TITLE
CONTENT IMAGES APPEAR BROKEN 

### ISSUE THREAD

**Issue by pamelamartello** [gohugoio/hugo#6879]
Hello,
I followed the documentation available on your site to install a HUGO theme and then deploy it through  GIT.
I encountered a problem I can't fix: when I try to change or add an image into my code they all appear to be broken (both on my local server and directly on my website after pushing changes).
All my images are inside the STATIC folder and I use the syntax:  
![text](/img/portfolio/pamela-works/assembly-collection_4-03.png)

For some reason it seems like the images are not being linked although they are inside the correct directory, what could be the issue?

This is my github repo: https://github.com/pamelamartello/20200210-example
website: https://pamelamartello.github.io/20200210-example/portfolio/

I would deeply appreciate any insights about this issue.

Thank you

**Comment by pamelamartello** [comment]
* syntax:

![text](/img/....png)

**Comment by pamelamartello** [comment]
*syntax used:
![]()

**Comment by pamelamartello** [comment]
![alt text](/path/to/image)

**Comment by pamelamartello** [comment]
`![alt text](/path/to/image)`

**Comment by pamelamartello** [comment]
*syntax in Markdown for images:

`![alt text](/path/to/image)`

**Comment by Jos512** [comment]
When I visit your example website, all the images load for me. 

![2020-02-11_13-39-15](https://user-images.githubusercontent.com/13403160/74237461-e90d6100-4cd3-11ea-9dc3-7e5f7f7dc4c9.png)

So I don't understand from the information provided what the problem is. I also took a quick look at your repository but didn't find an issue.

I do think you'd get better help over at the official Hugo forum: https://discourse.gohugo.io/

**Comment by pamelamartello** [comment]
thanks for your help!

The problem is that everything worked fine except that after I ran the first "HUGO" command on gitbash and then I committed the changes into github, after that any new images I try to add into the code they appear to be broken both on my website and my localhost (even though they have the right syntax and are inside the static folder). 

For instance inside https://pamelamartello.github.io/20200210-example/about/ you can find the broken link. 
The images you can see displayed on the current site are all from the exampleSite original code, I didn't modify those, hence you can see them displayed.

don't know if this explains better the issue

hope you could give me any other insight

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

And please don't post issues with all caps.
