### ISSUE TITLE
Simplifying doWithCommandeer

### ISSUE THREAD

**Issue by MarkRosemaker** [gohugoio/hugo#6880]
- **Problem:** purpose of doWithCommandeer unclear, seemingly superfluous
- **Proposal:** coding its functionality directly, replacing with boolean if necessary

I've been examining the code for a couple of days. Even though I didn't understand the purpose of some structs right away, over time they seemed to make a bit more sense.

However, one object seems to me to be superfluous:
`doWithCommandeer func(c *commandeer) error`

It's a field in commandeer and passed around in `newCommandeer` and `initializeConfig`. Do a search for it and you'll find 12 results.
You'll also find that it never does anything except once in `loadConfig`:

```
doWithCommandeer := func(cfg config.Provider) error {
	c.Cfg = cfg
	if c.doWithCommandeer == nil {
		return nil
	}
	err := c.doWithCommandeer(c)
	return err
}
```

That's it: Besides running a previous `doWithCommandeer` (which would only do the same thing), it just assigns `cfg` to `c.Cfg`. Since it's always called like `c.doWithCommandeer(c)`, that would be `c.Cfg = c`.

The only other functionality not mentioned yet is to be passed on to `hugolib.LoadConfig`, which does:

```
if err := d(v); err != nil {
	return v, configFiles, err
}
```

with d being `doWithCommandeer` (an input among other functions) and v being a pointer to a viper (`*viper.Viper`), so it would do `c.Cfg = v` (and err always nil).

Could we simplify this by directly calling `c.Cfg = c` and `c.Cfg = v`? LoadConfig returns the `*viper.Viper` so it can be done.

If necessary, we could replace doWithCommandeer with a boolean telling us which needs to be done.

**Comment by bep** [comment]
I welcome any simplification in this package! And the ugliness is all my fault, but to defend myself a little, a short history:

* The commands package was all globals and no tests.
* So when I had the "get rid of all globals so we can run tests in parallel" I had some really gray hairs when it the commands package. The Cobra API is a little bit clumsy.

That said, now we have decent test coverage, so I suggest that you just "do it" and open a PR.

**Comment by MarkRosemaker** [comment]
Great, will do!

**Comment by MarkRosemaker** [comment]
I think you did a great job btw. Hugo is very sophisticated so there is bound to be some complexity.

Regarding doWithCommandeer, I found out its purpose and decided that a simple renaming will make it much clearer:
#6881
