### ISSUE TITLE
disablePathToLower does not reflect on content titles

### ISSUE THREAD

**Issue by Lednerb** [gohugoio/hugo#6884]
In `config.toml` I've set 

```
disablePathToLower = true
```

My taxonomy pages get rendered correctly, for example:
`http://localhost:1313/tags/GitHub/`

However, the titles will be lowered anyway:
`http://localhost:1313/article/support-and-discussions/`

Is this an intended behaviour?

Title output is done via:

```
<h1 class="article-title"><a href="{{ .Permalink }}">{{ .Title }}</a></h1>
```

In the content's context.

Affected hugo version
`Hugo Static Site Generator v0.64.0-241DB8F7 linux/amd64 BuildDate: 2020-02-04T09:10:23Z`

**Comment by pamubay** [comment]
Yes, if you are using page bundle, the link will generated based on the name of page bundle's directory

```
content
├── article
│   └── support-and-discussions
│       └── index.md (title: Support and Discussion)
```
will generate:
```
/article/support-and-discussions/
```
---
You need to set the `permalinks` option for the `article` section.
```
[permalinks]
   article = "/:sections/:title"
```
will generate:
```
/article/Support-and-Discussion/
```
