### ISSUE TITLE
Hugo renders orgmode files (content/*.org) as if markdown

### ISSUE THREAD

**Issue by theory-wtf** [gohugoio/hugo#6888]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.64.1-C327E75D linux/amd64 BuildDate: 2020-02-09T20:47:32Z
</pre>

### Does this issue reproduce with the latest release?
Yes

## Description of problem
In have a orgmode file (`content/Org Test.org`) which contains:

```
#+title: Org Test
#+date: 2020-02-08
#+draft: false

* This should be a header and not a list item
```
`* This should be a header and not a list item` renders as a list item rather than a header (`*` represents a list item in markdown but a header in orgmode).

The orgmode formating of the front-matter however seems to work fine, e.g. if I change `#+draft: false` to `#+draft: true` it actually becomes a draft item (isn't shown on the site). `#+title: Org Test` also works.

So it seems to recognize orgmode front-matter, but not orgmode content.

**Comment by obar** [comment]
I couldn't reproduce this bug. I get h1 as expected. Anything org-relevant in your config? Can you run `hugo` and share the contents of `public/org-test/index.html`?

(also completely unrelated, since you're using emacs and hugo, can you reproduce #6773?)
