### ISSUE TITLE
Running a command on live reload -OR- try to reconnect the websocket

### ISSUE THREAD

**Issue by michalrus** [gohugoio/hugo#6894]
### A use case

An external command to prepare some assets needs to be *re-run* on live reload (e.g. `make censor` to blur some defined parts of source images). (With current image processing in Hugo, we can only pixelate whole images.)

### Solutions

1. It would be best/most elegant to allow defining a command (`make censor`) to be run on each live reload (`hugo server`).

2. Another option (which I’m using now) would be for the user to use some external directory watcher (e.g. `watchexec`), and make it loop over run-and-kill of `make censor && hugo server`.

But with 2., the browser doesn’t reload the page. So perhaps client JS code should try to reconnect to `hugo server` every second or such.

**Comment by bep** [comment]
I would suggest you mount the target file/folder of `make sensor` into `assets` or something. Since a recent Hugo version even single file mounts gets added to the watch list.

**Comment by michalrus** [comment]
Yes, yes, that’s not a problem!

The issue is that:
* `make censor` has to be *re-run* after some changes trigger the dir/file watcher.

There’s no way currently to do that and have browser reload the page automatically.

**Comment by bep** [comment]
... aha.

**Comment by michalrus** [comment]
I still care about this

**Comment by davidsneighbour** [comment]
Your requirement is a very specific one and not something "normal" users of Hugo would expect or require. Use `--disableLiveReload` to disable the Hugo way of reloading and use a reload library like [https://github.com/livereload/livereload-js](https://github.com/livereload/livereload-js) or [http://livereload.com/](http://livereload.com/). Please close this issue as this is not a bug in Hugo.
