### ISSUE TITLE
Docsy does not seem compatible with latest Hugo version

### ISSUE THREAD

**Issue by arnonzooz** [gohugoio/hugo#6903]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version  v0.64.1/extended darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

It seems that the shortcodes do not work properly with the latest Hugo version (v0.64.1 extended). For example, the blocks on the home page do not appear. Reverting to an older Hugo version (Hugo 0.53) does work. On a side note, I noticed that https://example.docsy.dev/ uses an older Hugo version as well. Please advise.

**Comment by frodriguezsmartclip** [comment]
Hi there @arnonzooz maybe it's related to config.toml?

Because I've used that theme "docsy" too, and I had a problem like that.

It's neccesary to have this in **config.toml**:

```
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      	hardWraps = false
    	unsafe = true
    	xHTML = false
```

So, in the index homepage you can see the blocks working wel.

Regards!! 😄

**Comment by arnonzooz** [comment]
Thank you! That did the trick for the home page. It is still not working when I add https://github.com/rvanhorn/hugo-dynamic-tabs. Do you have any experience with that?

**Comment by frodriguezsmartclip** [comment]
> Thank you! That did the trick for the home page. It is still not working when I add https://github.com/rvanhorn/hugo-dynamic-tabs. Do you have any experience with that?

Glad to help you! 😃 

No, I have no worked with hugo dynamic tabs. But, a quick read, have you install as git clone repo or [manually](https://github.com/rvanhorn/hugo-dynamic-tabs#manual-install)? I think the best may be the 2nd, manual install to attach and merge with your custom theme.

Is there a demo to see in action that dynamic tabs?

**Comment by arnonzooz** [comment]
Hi,

Git it all to work now, including dynamic tabs. Had to replace the % with a <> in my shortcode reference. Not sure where there's a demo you can see (I'm running on my local machine now).

Thanks for helping out! Will close the issue.
