### ISSUE TITLE
Error upgrading hugo version

### ISSUE THREAD

**Issue by mtdsj** [gohugoio/hugo#6904]
Upgrading from version Hugo 0.55.6 to Hugo 0.64.1, I have trouble, the tips are as follows:

$ hugo server
Building sites … ERROR 2020/02/17 16:51:06 Transformation failed: TOCSS: failed to transform "styles/main-rendered.scss" (text/x-scss): this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Built in 289 ms
Error: Error building site: logged 1 error(s)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
