### ISSUE TITLE
hugo serve: nondeterministic behavior for content/index.md

### ISSUE THREAD

**Issue by adiabatic** [gohugoio/hugo#6917]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.64.1/extended darwin/amd64 BuildDate: unknown
</pre>

(the version that comes with Homebrew)

### Does this issue reproduce with the latest release?

Yes.

### Steps to reproduce

On my iMac Pro running macOS Mojave 10.14.6 (the most recent version of Mojave) and Safari 13.0.5:

1. Run `git clone https://github.com/adiabatic/hugotest-gust && cd hugotest-gust`.
1. Run `hugo serve`.
1. Navigate to <http://localhost:1313>.
1. Notice how it says "index.md" on the page and "This is a plain index page." This bit of text is in `content/index.md`, and will be referred to as "`{{ .Content }}` text".
1. Change the top line of `assets/CSS/miscellaneous.scss` to read `a:link, a:visited, a:hover {` (add `a:hover` to the list of selectors). Save the file.
1. Notice how "index.md" and "This is a plain index page." disappear from the live-preview page.
1. Stop `hugo` by pressing Ctrl+C. Restart it by running `hugo serve` again. Notice how the "This is a plain index page."  doesn't come back.
1. Append "I like traffic lights" to the end of `content/index.md` and save the file. Notice how all the `{{ .Content }}` text reappears in the live-preview browser.
1. Stop `hugo` again by pressing Ctrl+C and restart it with `hugo serve`.
1. Refresh the live-preview browser. Notice how the `{{ .Content }}` text is still there.
1. Remove ", a:hover" from `assets/CSS/miscellaneous.scss`. Save the file. Notice how the `{{ .Content }}` text is still there.
1. Remove "I like traffic lights." from the end of `content/index.md`. Save the file. Notice how the `{{ .Content }}` text is still there (as it should be).
1. Re-add ", a:hover" to `assets/CSS/miscellaneous.scss`. Save the file. Notice how the `{{ .Content }}` text is still there (as it should be).
1. Append "// This is the end of the all file" to line 11 of `assets/CSS/all.scss`. Save the file. Notice how the `{{ .Content }}` text disappears.
1. Append ".example" to "Gusts" in `layouts/partials/menubar.html`. Save the file. Notice how the `{{ .Content }}` text still isn't there (I expected it to show up).
1. Remove lines 11 and 12 ("// This is the end of the all file") in `assets/CSS/all.scss`. Save the file. Notice how the `{{ .Content }}` text pops back into the page again.

On my MacBook Pro 2015, running macOS Catalina 10.15.4 Beta (19E224g) with Safari 13.1 (15609.1.15.3.11):

1. Run `git clone https://github.com/adiabatic/hugotest-gust && cd hugotest-gust`.
1. Run `hugo serve`.
1. Navigate to <http://localhost:1313>.
1. Notice how it doesn't have the `{{ .Content }}` text **at all**.
1. Append "I like traffic lights" to line 5 of `content/index.md` and save the file. Notice how the `{{ .Content }}` text pops into view.
1. Add ", a:hover" to the list of selectors in `assets/CSS/miscellaneous.scss`. Save the file. Notice how the `{{ .Content }}` text disappears.

Roughly speaking, editing SCSS makes content disappear, and this disappearance persists through Hugo restarts. However, this isn't quite right, as things didn't go the way I expected when I added in a navbar edit on top of an SCSS edit. This kind of problem seems to go away after I add more content to a Hugo site, but it's frustratingly nondeterministic until then.

I checked <https://gohugo.io/content-management/organization/#path-breakdown-in-hugo> and thought "the homepage isn't obviously a listy thing, so `index.md` should be fine". The content-management section, after all, is where I'd expect to see any mentions of "the homepage is special if you want it to be" documentation. However, after writing most of this bug report, I only then noticed "Homepage Templates" in the list of topics on the left, where it said to use `_index.md`. After moving `index.md` to `_index.md` the nondeterminism stopped cold. The `{{ .Content }}` text stayed put.

(As an aside, I'd expect "use _index.md instead of index.md for the homepage" to be in the content-management section of the docs.)

`hugo --path-warnings`, to its credit, detected "duplicate target paths" for `…/hugotest-gust/public/index.html`, but this sounds like a spurious error — it's not like I have both `_index.md` and `index.md` in `content/`.

While debugging this sort of problem doesn't sound fun at all, it's the sort of problem that a novice user will stumble over, get frustrated at, and drop Hugo because of it. 

Seems related to #6050.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
