### ISSUE TITLE
Hugo Deploy Include/Exclude Filters

### ISSUE THREAD

**Issue by zbayoff** [gohugoio/hugo#6922]
We are currently trying to adopt `hugo deploy` with our large site, but need more fine tuned control over which assets we deploy to s3 and where. We currently deploy our html files to one bucket, and all other static assets (images, videos) to another s3 bucket. We would like to continue serving these static assets from their own bucket (and domain), but that is currently not possible with `hugo deploy`. 

AWS CLI currently provides this functionality: 
https://docs.aws.amazon.com/cli/latest/reference/s3/#use-of-exclude-and-include-filters

Would it be possible to include this functionality with `hugo deploy`?

For example, the config might look like: 
```
[[deployment.targets]]
# An arbitrary name for this target.
name = "live-html"
URL = "s3://<Bucket Name>?region=<AWS region>"
exclude = "*"
include = "*.html, *.xml, *.txt"

[[deployment.targets]]
name = "live-statics"
URL = "s3://<Bucket Name>?region=<AWS region>"
include = "*"
exclude = "*.html, *.xml, *.txt"
```

Here is a similar post in hugo discourse: 
https://discourse.gohugo.io/t/hugo-deploy-include-exclude-filters/23279

Thanks!

**Comment by bep** [comment]
I guess that sounds reasonable. Thoughts, @vangent ?

**Comment by vangent** [comment]
Sounds reasonable.

**Comment by bep** [comment]
OK, for the implementor, please use this for pattern matching:

https://github.com/gohugoio/hugo/blob/master/hugofs/glob/glob.go#L31

It would then look something like this:

```
[[deployment.targets]]
name = "live-statics"
URL = "s3://<Bucket Name>?region=<AWS region>"
include = "**"
exclude = "**.{html,xml,txt}"
```

**Comment by vangent** [comment]
I'll take a look at this.

**Comment by vangent** [comment]
@zbayoff can you give it a try?

**Comment by bep** [comment]
That makes sense (to me, anyway). I created this issue to track it: https://github.com/gohugoio/hugo/issues/7020

In the meantime I think you can disable deleting stuff.
