### ISSUE TITLE
rate of release updates

### ISSUE THREAD

**Issue by jcw** [gohugoio/hugo#6925]
Not really an issue or proposal, merely a humble suggestion: would it be an idea to slow down the rate of official updates a notch or two? I'm using homebrew, and in the past month some 10 updates to Hugo have popped up. More than almost every other homebrew package I use.

As a very (very!) happy user of Hugo, I'm delighted that developments continue to add new features, but they almost never affect me personally - I'm not living on the edge, just using Hugo for a few websites (blogs, docs, etc). For those of us who would appreciate leaving good enough alone (assuming there are others), it would be helpful to have a way to track urgent fixes, without necessarily tracking all the features being thought of and added to Hugo. Note also that the nature of Hugo as static site generator makes it considerably more robust and safer to reduce the rate of release updates than with anything based on active code, running during each website access.

**Comment by bep** [comment]
No.

**Comment by moorereason** [comment]
It sounds like your problem is with homebrew (which I don't use).  Either tell homebrew to [install a particular version](https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula) or stop using homebrew for Hugo.
