### ISSUE TITLE
Show the filename on "render of "page" failed"

### ISSUE THREAD

**Issue by thefrontendguy** [gohugoio/hugo#6926]
Is it possible to output the filename, when the build was stopped by any error?

**Comment by bep** [comment]
We do that in most cases (whenever possible I guess), so you need to be more specific.

**Comment by thefrontendguy** [comment]
The files are created by an CMS. Some files can slightly change. 

Unfortunately I don't know which file causes the <.type> error.

`ERROR 2020/02/21 09:39:53 render of "page" failed: execute of template failed: template: _default/single.html:14:7: executing "main" at <partial "article_short" .>: error calling partial: execute of template failed: template: partials/article_short.html:4:11: executing "partials/article_short.html" at <partial "article" .>: error calling partial: "/hugo/cli/site_read/layouts/partials/article.html:70:42": execute of template failed: template: partials/article.html:70:42: executing "partials/article.html" at <.type>: nil pointer evaluating interface {}.type`

**Comment by bep** [comment]
We should add the page name there, but personally I would find it not very useful in the above situation, as the problem lives in the template, which you have the filename to.

**Comment by thefrontendguy** [comment]
> as the problem lives in the template, which you have the filename to.

Yes. But I lack the information, how to adapt the template. 

That makes it really time consuming, as I have to check the md files manually to see, what exactly went wrong here.
