### ISSUE TITLE
Non-extended version throws "Type <nil> not supported in Resource transformations" instead of warning about unavailable feature

### ISSUE THREAD

**Issue by lowercasename** [gohugoio/hugo#6930]
Hugo: Hugo Static Site Generator v0.65.2-C1EB62512/extended linux/amd64 BuildDate: 2020-02-21T10:47:33Z

This one caught me out because I wasn't aware to begin with that there were non-extended and extended versions. I went back to v0.62 and got the error 'TOCSS … this feature is not available in your current Hugo version', as expected.

**Comment by bep** [comment]
I don't think the v0.62 reference is accurate (but I'm not totally sure)... The "Type nil not..." error is created before we even have looked at what transformation to do. That nil resource will not succeed whether you have the extended version or not.

**Comment by lowercasename** [comment]
Ah, interesting. I'm basing this entirely on the fact that v0.65 extended was the only version where toCss worked for me, with different errors in v0.65 non-extended and v0.62.

(To be clear, the SCSS transformation is now working!)
