### ISSUE TITLE
Disablekinds is not working in latest version

### ISSUE THREAD

**Issue by sureshkumargondi** [gohugoio/hugo#6935]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.65.2/extended darwin/amd6
</pre>

### Does this issue reproduce with the latest release?
yes

In the config.toml file I have made the disable kind for tags and categories not to generate at all. But it's still generating.. 

It was happening from 0.65.1 I guess, I just observed it. 

This is the config.toml code I used 

disableKinds = ["tags", "categories"]

**Comment by bep** [comment]
tags and categories is not valid values for kinds.
