### ISSUE TITLE
ailed to extract shortcode: template for shortcode "notice" not found

### ISSUE THREAD

**Issue by xmasuhai** [gohugoio/hugo#6938]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.65.2-C1EB62512 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
no

### theme

jane

---

```bash
 hugo
Building sites … WARN 2020/02/23 15:19:45 Markup type mmark is deprecated and will be removed in a future release. See https://gohugo.io//content-manag ement/formats/#list-of-content-formats
Total in 259 ms
Error: Error building site: "E:\Documents\HungerValley\xmasuhai.github.io-generator\content\post\Test\shortcode-notice.md:20:1": failed to extract shortcode: template for shortcode "notice" not found
```

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
