### ISSUE TITLE
page.GetTerms "categories" is empty

### ISSUE THREAD

**Issue by gj52** [gohugoio/hugo#6939]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.65.2
</pre>

### Does this issue reproduce with the latest release?
Yes

Every page has  categories defined in frontmatter, 
but  {{ .GetTems "categories" }} is empty.

.getTerms works for me for "tags"  and my defined taxonomy "series"

**Comment by franklsf95** [comment]
Did you figure out why?

**Comment by gj52** [comment]
don't remember (i'm over 60 ;-) )

check, you have

[taxonomies]
   category  = categories 

or 

noting (defaulted)

**Comment by franklsf95** [comment]
@gj52 Thank you so much, that was exactly the issue. I did not have `taxonomies` properly configured in `config.yaml`.
