### ISSUE TITLE
Add math.Sqrt

### ISSUE THREAD

**Issue by StarsoftAnalysis** [gohugoio/hugo#6941]
What would it take to add to Hugo’s templates the ability to calculate square roots?

We already have basic arithmetic (`add`, `mul`, etc.) and some other Go functions (`math.Floor`, `math.Round`, etc.), but not `math.Sqrt`.

Why would I want to calculate square roots? Because I’m trying to display a group of differently-shaped images so that they all take up the same *area* on the screen. See [MathCentral](http://mathcentral.uregina.ca/QQ/database/QQ.09.15/h/colum1.html) for the formula.

So I’d like to be able to use `math.Sqrt` in my shortcode.

Meanwhile, I'll have a look at the code and see if I can come up with a pull request for such a feature.

**Comment by Jos512** [comment]
> See MathCentral for the formula.
> I'll have a look at the code and see if I can come up with a pull request for such a feature.

Luckily we don't have to implement the formula ourselves. :slightly_smiling_face:  Go's `math.Sqrt()` function ([here](https://golang.org/pkg/math/#Sqrt)) provides the capability we need. You can use that function to implement the square root behaviour in Hugo.

It looks like Hugo defines the math functions in [the `math.go` file](https://github.com/gohugoio/hugo/blob/master/tpl/math/math.go). That's a good place to start.

Good luck!

**Comment by StarsoftAnalysis** [comment]
I've created a patch and a pull request -- at least I think I have: I'm not very experienced at this Github thing.
