### ISSUE TITLE
render hook template render-link.html adds newline

### ISSUE THREAD

**Issue by weitblick** [gohugoio/hugo#6949]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.65.3/extended linux/amd64
</pre>

The render hook template render-link.html adds a newline after the rendered content so characters that are directly behind a link are shown in the output with a space, e.g.:

`... some words [a Link](https://weitblick.org). New sentence ...`

`... some words <a href="https://weitblick.org" target="_blank">a Link</a>`
`. New sentence ...</p>`

... some words [a Link](https://weitblick.org) . New sentence ...

**Comment by bep** [comment]
>The render hook template render-link.html 

Hugo does not provide a template with that name. If you have such a template with an extra newline, remove that newline. Hugo does not add anything.

**Comment by weitblick** [comment]
I mean: https://gohugo.io/getting-started/configuration-markup#markdown-render-hooks

**Comment by bep** [comment]
> Try it yourself.

I have, I wrote it. We have had this discussion before, you should check your editor's settings. I suspect it inserts a newline on save.

**Comment by weitblick** [comment]
![no-newline](https://user-images.githubusercontent.com/4954093/75168122-ab262900-5726-11ea-9b1d-e4e6795c07f5.png)
definitly no newline ...

**Comment by bep** [comment]
https://github.com/gohugoio/hugo/issues/6832

**Comment by weitblick** [comment]
thanks a lot for your patience! I double checked it with Linux gedit and vi and I created via comand line vi a new file. There was no newline visible (see above). But with bluefish editor the newline was visible and I was able to delete it. Maybe it helps somebody else with the same problem ...

**Comment by thirtythreeforty** [comment]
In Vim you'd need to set the [`nofixendofline`](https://www.cs.csubak.edu/docs/vim/options.html#'fixendofline') option.
