### ISSUE TITLE
My site build by Hugo have about 1600 posts, hugo server very slow

### ISSUE THREAD

**Issue by Rhinocros** [gohugoio/hugo#6950]
My site build by Hugo have about 1600 posts, ``` hugo server ```  very slow

Need about 8 mins to built

Whether beacuse posts too many?

How make Hugo build more quickly?

Hugo version is 0.62.2

Thanks

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
