### ISSUE TITLE
Duplicate page entries on list pages

### ISSUE THREAD

**Issue by backmes** [gohugoio/hugo#6955]
On my pages, I use some kind of nested categories like "`Releases`", "`Releases/Product_1`", "`Releases/Product_2`", and assign a page to both the generic category "`Releases`" and a specific category like "`Releases/Product_1`".

Starting with Hugo 0.65.0, this generates duplicate entries on the list page "/categories/releases/".

Hugo version which still worked as expected:
`Hugo Static Site Generator v0.64.1-C327E75D/extended linux/amd64 BuildDate: 2020-02-09T20:51:43Z`
Hugo versions which create duplicate entries:
`Hugo Static Site Generator v0.65.0-24AFE2B82/extended linux/amd64 BuildDate: 2020-02-20T09:09:42Z`
`Hugo Static Site Generator v0.65.3-211BA42A/extended linux/amd64 BuildDate: 2020-02-23T10:07:00Z`

**Comment by backmes** [comment]
I dug a little bit deeper, and got the following results:

- When I assign a category "`level1/level2`" to a page, this page will appear in variable `.Pages` of the list page "`/categories/level1`". This is consistent with the behavior on normal list pages, which also contains the pages of all sub directories. So actually releases before 0.65.0 showed an inconsistent behavior, and my pages rely on it. Hrmpf.

- Nonetheless, I could assign two categories "`level1/level2_a`" and "`level1/level2_b`" to a single page. In this case, the page will appear twice in variable `.Pages` of  "`/categories/level1`". I don't think this is the intended behaviour. Of cause, I could use `uniq .Pages` everywhere in my templates, but I actually like using some of the built-in templates.

**Comment by bep** [comment]
> the page will appear twice in variable .Pages of "/categories/level1".

I don't see that behaviour. 

>don't think this is the intended behaviour.

That said, I think what you see is mostly rooted in the fact that the taxonomies are 1 level only. The behaviour you see isn't particulary correct, but we have no tests for this, so it is hard to tell what's the intended behaviour. 

Someone needs to define that and add the proper tests/implementation.

**Comment by backmes** [comment]
> > the page will appear twice in variable .Pages of "/categories/level1".
> 
> I don't see that behaviour.

I just created a sample website to show the behaviour: https://github.com/backmes/website-hugo-6955

Once the site is generated with hugo, ''public/categories/releases/index.html'' shows a duplicate entry for "Release-3", as it is posted in two categories.
