### ISSUE TITLE
TestPara/Time fails randomly on autobuilders

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugo#6963]
While finally starting to catch up with packaging for Debian all the Hugo releases that I missed, I have been seeing several build/test failures on autobuilders such as buildd.debian.org and Snap builder on Launchpad, all with the following error:

```
--- FAIL: TestPara (0.06s)
    --- FAIL: TestPara/Time (0.06s)
        quicktest.go:306: 
            error:
              values are not equal
            got:
              bool(false)
            want:
              bool(true)
            stack:
              /build/hugo/parts/hugo/build/common/para/para_test.go:86
                c.Assert(time.Since(start) < n/2*time.Millisecond, qt.Equals, true)
```

Examples:

* https://buildd.debian.org/status/logs.php?pkg=hugo&arch=i386
** https://buildd.debian.org/status/fetch.php?pkg=hugo&arch=i386&ver=0.63.0-1&stamp=1582322676&raw=0
* https://launchpad.net/~gohugoio/+snap/hugo-dev/+build/849297
** https://launchpadlibrarian.net/466712794/buildlog_snap_ubuntu_xenial_amd64_hugo-dev_BUILDING.txt.gz

I would guess it is happening about 5% of the time.

### What version of Hugo are you using (`hugo version`)?

0.63.0 as seen on Debian

(aside: figuring out how to downgrade minify to 2.6.1 before uploading 0.63.1)

### Does this issue reproduce with the latest release?

Yes, as seen on Snap "hugo-dev" build which follows `master` (0.66.0-DEV)

**Comment by anthonyfok** [comment]
Hi @bep,

Could you please take a look at this when you have time?  This TestPara/Time seems to flaky and failing randomly too often, causing build failures for both Debian builds and for Snaps that I have had to manually trigger rebuilds too many times, that I am tempted to skip TestPara/Time altogether, say, perhaps by running it only when CI=true?

Or is there any way to make it not fail intermittently especially on slow or busy machines?  I must admit I do not understand what the test does (due to my lack of knowledge in parallelism/concurrency), and whether increasing the `n/2*time.Millisecond` timeout to something like `n*time.Millisecond` would defeat the purpose of the test?

Many thanks!

**Comment by anthonyfok** [comment]
Hello moorereason and bep,

Thank you for PR #8070!  That's a great idea!

As seen on https://launchpad.net/~gohugoio/+snap/hugo-extended-dev, some of the first results are in.  Here is a failed test on arm64 for hugo-extended-dev, https://launchpadlibrarian.net/512067121/buildlog_snap_ubuntu_xenial_armhf_hugo-dev_BUILDING.txt.gz:

```
--- FAIL: TestPara (0.06s)
    --- FAIL: TestPara/Time (0.06s)
        para_test.go:87: 
            error:
              values are not equal
            comment:
              52.107429ms >= 50ms
            got:
              bool(false)
            want:
              bool(true)
            stack: 
              /build/hugo/parts/hugo/build/common/para/para_test.go:87
                c.Assert(since < limit, qt.Equals, true, qt.Commentf("%s >= %s", since, limit))
```

And, from https://launchpad.net/~gohugoio/+snap/hugo-dev:

* amd64: 64.992145ms >= 50ms
* arm64: 66.332598ms >= 50ms
* armhf: 59.204865ms >= 50ms

I suspect that the Launchpad autobuilders are rather busy machines, doing parallel builds of multiple packages at the same time, and thus TestPara fails more often here.

TestPara fails a lot less often on https://buildd.debian.org/status/package.php?p=hugo where one package is built at a time, but it still happens especially on slower MIPS and ARM machine, see the "Maybe-Failed" records on e.g. https://buildd.debian.org/status/logs.php?pkg=hugo&arch=mipsel

**Comment by moorereason** [comment]
@bep, I was about to submit a PR to change the limit calculation from `n / 2 * time.Milliseconds` to just `n * time.Milliseconds`.  The failure scenario is that parallelism isn't happening at all not that it's slow.  A failure should take at least 100ms.  Wouldn't you agree?

**Comment by bep** [comment]
I think we have spent enough time on this. If my patch works, let's be pragmatic. The test is in place to prove that the implementation is parallel on multi-CPU systems; we verify that enough times on Travis etc.

**Comment by anthonyfok** [comment]
Wow, that was really quick!  Thank you both @bep and @moorereason!

Yes, I agree that making TestPara CI-only is both pragmatic and failsafe;
fudging the time limit could be making somewhat of a compromise with the original CI test.

Thanks again!
