### ISSUE TITLE
disableHugoGeneratorInject on RSS Template

### ISSUE THREAD

**Issue by aanupam23** [gohugoio/hugo#6965]
Referencing the issue #3453
The default RSS template currently generates the generator tag on RSS page

`<generator>Hugo -- gohugo.io</generator>`

https://github.com/gohugoio/hugo/blob/05a74eaec0d944a4b29445c878a431cd6ae12277/tpl/tplimpl/embedded/templates/_default/rss.xml#L19

Currently disableHugoGeneratorInject disables RSS tag only on homepage but it doesn't affect generator tag on RSS page.

Proposal: My suggestion is to support the disableHugoGeneratorInject on RSS page as well and make it a default behavior of the template.

**Comment by bep** [comment]
The disableHugoGeneratorInject is very HTML specific and something we inject into the HTML output. This isn't the same. If you don't want the generator tag, create your own template.
