### ISSUE TITLE
WindowsXP support dropped as of Hugo 0.55 / Go 1.12

### ISSUE THREAD

**Issue by FBachofner** [gohugoio/hugo#6972]
Post title UPDATED 2020-05-26: see clarification in subsequent posts.
Title now reflects reality.
This post is partially incorrect.

---

Hugo worked fine on WindowsXP through hugo_0.57.2_Windows-32bit

As of 0.58 Go 1.13 is used which mandates at least Windows 7.  [ Attempting to run a current version of Hugo on WindowsXP therefore results in an error message: "not a valid Win32 application" ]

This is not specified anywhere in the (Hugo) releases documentation I could find.

It might be useful to indicate at release hugo_0.57.2_Windows-32bit that it is the "LAST WindowsXP version . . ."

Yes, I know almost no one uses XP anymore and the various reasons for that!  :-)

**Comment by FBachofner** [comment]
I previously wrote "Hugo worked fine on WindowsXP through hugo_0.57.2_Windows-32bit"

I can not duplicate that previous version "success" and perhaps I mistyped and/or misremembered when posting.

**The last version I can make work with WindowsXP 32bit is hugo_0.54.0_Windows-32bit.zip.**

I just tested this a moment ago and it makes sense.  Hugo 0.55.x updated to using Go 1.12.x at which point GoLang apparently no longer supported XP.  GoLang 1.10 was the last version to **_officially_** support XP, but 1.11 apparently still does.

[hugo_0.54.0_Windows-32bit.zip](https://github.com/gohugoio/hugo/releases/tag/v0.54.0) is based on Go 1.11.5

**Comment by FBachofner** [comment]
Interestingly, it turns out Go 1.11 "mandates" > Windows XP
https://go-review.googlesource.com/c/go/+/87175/

Indeed, as of 1.11, GoLang installer checks for >= Windows 7 SP1
https://go-review.googlesource.com/c/build/+/103856/

However, Hugo 0.54 (which is based on Go 1.11) seems to run just fine on 32bit Windows XP.

**Comment by FBachofner** [comment]
I was curious as to why Hugo 0.54 still worked given that it is based on Go 1.11 (where XP is no longer supported).

This SO post discusses similar experiences:
https://stackoverflow.com/questions/52137098/go-after-1-10-and-support-of-windows-xp

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
