### ISSUE TITLE
cannot load github.com/bep/golibsass/internal/libsass: no Go source files

### ISSUE THREAD

**Issue by ckuelker** [gohugoio/hugo#6980]
building/installing hugo from source fails (after using https://gohugo.io/getting-started/installing/)

<pre>
export VER=0.65.3
git clone --branch v$VER --single-branch --depth 1  $URL hugo-$VER
cd hugo-$VER
go version
go version go1.13.7 linux/amd64
go build --tags extended
...
build github.com/bep/golibsass/internal/libsass: cannot load github.com/bep/golibsass/internal/libsass: no Go source files
</pre>

Not sure how to fix this issue.

### Does this issue reproduce with the latest release?

Yes, the latest clone of the git repository reproduces the error: Latest commit
b66d38c

### Additional information
<pre>
lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
</pre>

go environment

<pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/$USER/.cache/go-build"
GOENV="/home/$USER/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/srv/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/$USER/g/github.com/golang/go1.13.7"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/$USER/g/github.com/golang/go1.13.7/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/tmp/hugo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build184159906=/tmp/go-build -gno-record-gcc-switches"
</pre>

**Comment by pamubay** [comment]
Try installing using the steps from [CONTRIBUTING.md#building-hugo](https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#building-hugo-with-your-changes)

**Comment by ckuelker** [comment]
Following now https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#building-hugo-with-your-changes

Building the **non extended** version of hugo 0.64.1 and 0.66.0-DEV works just fine on my system
with and **without** mage.

<pre>
 cd /tmp
 git clone https://github.com/gohugoio/hugo.git hugo-0.66.0-dev
 cd hugo-0.66.0-dev
 mage hugo
 ./hugo version
 Hugo Static Site Generator v0.66.0-DEV-B66D38C4 linux/amd64 BuildDate: 2020-02-28T09:42:31+0100
</pre>

However also with mage hugo do **not** build/install the **extended** version and the error is very similar.

```
HUGO_BUILD_TAGS=extended mage install  
build github.com/bep/golibsass/internal/libsass: cannot load github.com/bep/golibsass/internal/libsass: no Go source files
Error: running "go install -ldflags -X github.com/gohugoio/hugo/common/hugo.commitHash=b66d38c4 -X github.com/gohugoio/hugo/common/hugo.buildDate=2020-02-28T09:47:18+0100 -tags extended github.com/gohugoio/hugo" failed with exit code 1
```
