### ISSUE TITLE
hugo crashes with enableGitInfo=true and log.showSignature=true in ~/.gitconfig

### ISSUE THREAD

**Issue by jaakristioja** [gohugoio/hugo#6985]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.65.3-211BA42A linux/amd64 BuildDate: 2020-02-23T09:59:37Z
</pre>

### Does this issue reproduce with the latest release?
That was the latest release binary from https://github.com/gohugoio/hugo/releases/download/v0.65.3/hugo_0.65.3_Linux-64bit.tar.gz.

### So what is the problem
If I have `enableGitInfo = true` in my `config.toml` then `hugo server` crashes:

<pre>
$ hugo server
Building sites … panic: runtime error: index out of range [5] with length 1

goroutine 82 [running]:
github.com/bep/gitmap.toGitInfo(0xc000876000, 0x30, 0x1b70f21, 0x1, 0x0)
        /go/pkg/mod/github.com/bep/gitmap@v1.1.1/gitmap.go:128 +0x3f7
github.com/bep/gitmap.Map(0xc000040094, 0x21, 0x0, 0x0, 0x21, 0x1, 0x0)
        /go/pkg/mod/github.com/bep/gitmap@v1.1.1/gitmap.go:90 +0x4cd
github.com/gohugoio/hugo/hugolib.newGitInfo(0x1feb980, 0xc000342d80, 0xd, 0x401, 0x7f247bc9c400)
        /root/project/hugo/hugolib/gitinfo.go:41 +0x6a
github.com/gohugoio/hugo/hugolib.(*HugoSites).loadGitInfo(0xc000774b40, 0x20300000000000, 0x7f247be52fff)
        /root/project/hugo/hugolib/hugo_sites.go:378 +0x8b
github.com/gohugoio/hugo/hugolib.newHugoSites.func4(0x400, 0x7f247bc9c500, 0x20300000000000, 0x7f247be52fff)
        /root/project/hugo/hugolib/hugo_sites.go:344 +0x2e
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
        /root/project/hugo/lazy/init.go:97 +0x136
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc0007b62c8, 0xc0006b8848)
        /root/project/hugo/lazy/once.go:53 +0x146
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc0007b62a0, 0x20, 0x20, 0x1b6cf40, 0x18)
        /root/project/hugo/lazy/init.go:79 +0x5b
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
        /root/project/hugo/lazy/init.go:102 +0xbc
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc0007b60e8, 0xc0006b89a8)
        /root/project/hugo/lazy/once.go:53 +0x146
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc0007b60c0, 0x7f247b977148, 0xc0008f47e0, 0x1fe1120, 0xc0006ca110)
        /root/project/hugo/lazy/init.go:79 +0x5b
github.com/gohugoio/hugo/hugolib.(*HugoSites).gitInfoForPage(0xc000774b40, 0x204bf00, 0xc0007f2b40, 0x0, 0x0, 0x1b74697)
        /root/project/hugo/hugolib/hugo_sites.go:170 +0x37
github.com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode(0xc000782670, 0xc0006a9140, 0xc000918000, 0x0, 0x0, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:133 +0x35f
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages.func1(0xc00069e980, 0x13, 0x18ba380, 0xc0006a9140, 0xc0006b8d00)
        /root/project/hugo/hugolib/content_map_page.go:358 +0x16d
github.com/armon/go-radix.recursiveWalk(0xc0006a91d0, 0xc000921df0, 0xc0bdbe)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf0
github.com/armon/go-radix.recursiveWalk(0xc0006a9230, 0xc000921df0, 0xf35e32)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc0006a9380, 0xc000921df0, 0x0)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc0006836e0, 0xc000921df0, 0x0)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.(*Tree).Walk(...)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages(0xc000782670, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:331 +0xec
github.com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc000782670, 0x404d15, 0xc0000a45a0)
        /root/project/hugo/hugolib/content_map_page.go:709 +0x68
github.com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0xd91c3f, 0x1b71501)
        /root/project/hugo/hugolib/content_map_page.go:776 +0x2e
github.com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0xc0002aef68, 0x1)
        /root/project/hugo/common/para/para.go:52 +0x2f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0007f2690, 0xc0008f4580)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
</pre>

**Comment by jaakristioja** [comment]
It seems that this is caused by Hugo not properly handling

<pre>
[log]
    showSignature = true
</pre>

in `~/.gitconfig`.

**Comment by shubhamshahare** [comment]
I tried to recreate this bug using following steps . Also added attribute enableGitInfo.  But there was no runtime error. 
```
(venv) ➜  quickstart git:(master) ✗ ~/Downloads/hugo_0.65.3_Linux-64bit/hugo version
Hugo Static Site Generator v0.65.3-211BA42A linux/amd64 BuildDate: 2020-02-23T09:59:37Z

(venv) ➜  quickstart git:(master) ✗ hugo new site quickstart

(venv) ➜  quickstart git:(master) ✗ cat config.toml
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
enableGitInfo = true


(venv) ➜  quickstart git:(master) ✗ ~/Downloads/hugo_0.65.3_Linux-64bit/hugo server 
Building sites … WARN 2020/03/31 03:02:45 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/03/31 03:02:45 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/03/31 03:02:45 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN  
-------------------+-----
  Pages            |  3  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 2 ms
Watching for changes in /home/shubham/Hugo/Sites/quickstart/{archetypes,content,data,layouts,static}
Watching for config changes in /home/shubham/Hugo/Sites/quickstart/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by jaakristioja** [comment]
> I tried to recreate this bug using following steps . Also added attribute enableGitInfo. But there was no runtime error.

Do you also have GPG-signed commits in that git repository?

**Comment by shubhamshahare** [comment]
Hi @jaakristioja  I have recreated above mention issue.  As there is dependency on gitmap library. 

```
[log]
    showSignature = true
```
with showSignature enabled in gitconfig , gitmap library is unable to parse as expected . As it was also showing GPG key in log output.

**Comment by dragtor** [comment]
@bep  If there are any changes in dependent library whose version got changed from x.x.x to x.x.x+1 . How we should handle this change in Hugo go.mod , as current release version is 0.68.0 , and I want to make changes for version 0.65.3 ? how it will reflect to preceding version too? Or will it introduce new version of Hugo v0.65.4 .

**Comment by bep** [comment]
Just create a PR that updates the git-map deps only and I'll merge it ... and it will be in the next version (whatever version that will be).

**Comment by jaakristioja** [comment]
Thanks! :-)
