### ISSUE TITLE
Potential bug source/prevention of reporting an error

### ISSUE THREAD

**Issue by MarkRosemaker** [gohugoio/hugo#6988]
In hugolib/pages_capture.go, you have:

```
func (c *pagesCollector) Collect() (collectErr error) {
	defer func() {
		collectErr = c.proc.Wait()
	}()

	if len(c.filenames) == 0 {
		// Collect everything.
		collectErr = c.collectDir("", false, nil)
	} else {
		...
	}

	return
}
```

What's the purpose of the assignment `collectErr = c.collectDir("", false, nil)`? Doesn't it get overridden anyway by the deferred function?
I'm using Hugo as inspiration for my own project and implementing this code prevented the program from reporting the error that collectDir returned.

I'm not sure whether I'm missing something or not and it's not technically a bug (yet) but I propose making a check if collectErr is nil before overwriting the variable in the deferred function.

**Comment by bep** [comment]
You are right, thanks.
