### ISSUE TITLE
Add date based pagination

### ISSUE THREAD

**Issue by jamietanna** [gohugoio/hugo#6992]
On sites with a large amount of content that is pushed many times a day, site rebuilds require lots of files changing (due to pagination).

However, if we could paginate based on a date, this would mean that it'd be easier to see all the content for a given day, as well as changing as few pages as possible when updating the site.

**Comment by bep** [comment]
You can paginate by date, but you need to take questions on the forum.

**Comment by jamietanna** [comment]
Thanks bep - it looks like https://discourse.gohugo.io/t/pagination-and-group-by-date/1441/3 should handle this. 

Are you happy if I keep this issue open until I've confirmed if Hugo supports what I am hoping for?

**Comment by jamietanna** [comment]
FYI I have raised https://discourse.gohugo.io/t/date-based-pagination-one-list-page-per-day/23870/3 as I don't believe the example above solves my issue.

**Comment by jamietanna** [comment]
This doesn't seem to have been answered on the forums as a thing that is possible, so I'd still appreciate this to be a feature request.

(Originally published at: https://www.jvt.me/mf2/2020/07/6qysj/)

**Comment by ricardoferreiracosta08** [comment]
I resolved this issue with this code:

```
<ul>
{{ range (.Paginate (.Data.Pages.GroupByDate "2006 January")).PageGroups  }}
{{.Key}}
{{ range .Pages }}
        <li><a class="title" href="{{ .Permalink }}">{{ .Title }}</a></li>
{{ end }}
{{ end }}
</ul>

{{ template "_internal/pagination.html" . }}
```
In my example, I used GroupByDate by year and month ("2006 January")

**Comment by jamietanna** [comment]
Hey Ricardo, although that does work, it's not _quite_ what I'm looking for. I'm hoping to get an archives style setup, where I can list, on a single page, all content from i.e. October 2020. With the above, if a month has too much content, it is split over multiple pages

**Comment by jamietanna** [comment]
This is still a feature it'd be good to have

**Comment by leahoswald** [comment]
I would love such a feature too.

**Comment by raoulb** [comment]
Me too. Pagination by arbitrary page groups defined manually would be great.

**Comment by jmooring** [comment]
> I'm hoping to get an archives style setup

Closing in favor of https://github.com/gohugoio/hugo/issues/448.

**Comment by jamietanna** [comment]
Would this be able to get closed as Not Planned? So it's clearer to folks that it's not yet been implemented
