### ISSUE TITLE
Add config build.UseResourceCacheWhen

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6993]
E.g

```toml
[build]
useResoureceCacheOnly = true
```

Will only use the pre-built transformations inside /resources/_gen.

We do this a fallback today when a transformation fails because you're running with the non-extended version, no PostCSS installed ...

The reason we did this was that it took a year before Netlify installed the extended version.

The reason this isn't the default behaviour is that the cache key is produced from the main resource file and the properties in the transformation, we don't consider imported SCSS files, as one example.

But there are obvious situations where this could be really useful:

* If you have a very stable theme/UI -- rebuilding the resources on every build on a content change is wasteful even if it is "Hugo quick"
* If you want the many people on the internet to edit the content and want as easy install as possible (`hugo server`)
* And possibly also just to save Netlify build minutes

Ideally you should be able to somehow set this per theme/component, but that is a little bit of a mind-twister.

/cc @regisphilibert

**Comment by regisphilibert** [comment]
This is gold!

**Comment by bep** [comment]
OK, so I was testing with `purgeCSS` and Tailwind on an 1100 pages Hugo site ... and the full Hugo build took 40 seconds to complete... Without purging took 3 seconds (many images).

So, while that example really says something about how badly this issue is needed; @budparr if you watch these notices, I understand that purgecss needs to do some work, but is it this slow or is it me doing something completely stupid?

**Comment by budparr** [comment]
Are you running Purge on output HTML or templates? Templates is much quicker of course.

**Comment by bep** [comment]
>Are you running Purge on output HTML or templates? 

On output. I don't see how you can purge based on the templates (assuming you have some dynamic class constructs).

**Comment by regisphilibert** [comment]
> On output. I don't see how you can purge based on the templates (assuming you have some dynamic class constructs).

Well you whitelist some. Not ideal but saves times.

@bep on a plane here, but you could try running PurgeCSS with node on your output dir without Hugo. It might be that it is just slow...

**Comment by budparr** [comment]
Exactly. We use whitelist. Build times are everything for us, so it's worth the extra work to build on templates. 

Ideally we'd just run our CSS locally and not in production, which would allow us to run on output HTML (because locally the extra time doesn't matter as much).

**Comment by bep** [comment]
OK, that makes sense. Thanks.

**Comment by budparr** [comment]
Totally agree. We are embracing modules wholeheartedly and have thought about this issue. But our first priority is having our clients not wait too long for builds.
