### ISSUE TITLE
Provide latest release also for debian

### ISSUE THREAD

**Issue by damnms** [gohugoio/hugo#7003]
Feature Request
_Is your feature request related to a problem? Please describe._
I would like to have the latest version of hugo on my debian machine

_Describe the solution you'd like_
apt-get update && apt-get upgrade

_Describe alternatives you've considered_
downloading manually and checking all few days to see if an update is available, check if its security related, check if it has an impact, etc.

_Additional context_
I don't like using binaries from release pages like github etc. as i then have to take care of updates. This might work when a server only runs 1-2 applications, but for a mail server as example, it has to check roundcube, postfixadmin, etc. - therefore i really like apt. apt-get update and i am fine. even better: i can configure it, so it automatically installs security related updates.

edit: i understand that the official repo may not update hugo that often, but many other applications i use (sky, postgresql, matrix-synapse etc.) provide their own debian compatible repo with latest versions. would be really nice if that would be possible!

**Comment by bep** [comment]
You need to take this on the Debian issue tracker.

**Comment by damnms** [comment]
did you read my edit?
