### ISSUE TITLE
in Hugo v0.65.3 broken logic range  .Pages.ByWeight

### ISSUE THREAD

**Issue by bosonbeard** [gohugoio/hugo#7008]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version  v0.65.3

</pre>

### Does this issue reproduce with the latest release?
yes

pages no longer rank by weight. Weight has no effect on ranking. In version v0.62.2 and v0.64.1 everything worked correctly.

**Comment by bep** [comment]
This isn't a statement that can be true in general (we have millions of tests depending on this sort working as it should), so it must be something "else" in your site, which is hard to tell without seeing the source.

**Comment by bosonbeard** [comment]
> This isn't a statement that can be true in general (we have millions of tests depending on this sort working as it should), so it must be something "else" in your site, which is hard to tell without seeing the source.

I think you're right. The problem was in my system. I could not reproduce the bug after reboot.
