### ISSUE TITLE
Destination of render-link can't be validated if destination is inside a param

### ISSUE THREAD

**Issue by karamme** [gohugoio/hugo#7010]
When we have this markdown file:

<pre>
+++
title = "test"
mylink = "https://www.example.com"
+++

This is an external [link](https://www.example.com)

Another external [link]({{< param "mylink" >}})
</pre>

and this render-link.html:

<pre>
{{ .Text }} -> {{ .Destination }} -> {{ strings.HasPrefix .Destination "http" }}
</pre>

The output will be this:

<pre>
This is an external link -> https://www.example.com -> true

Another external link -> https://www.example.com -> false
</pre>

My expectations are that the second link should validate to ´true´ as well. I tried ´print´ to parse the variable, but I could not get the second case to work. Maybe this behaviour can be fixed in an upcoming release. Thanks.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.66/extended windows/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

yes

**Comment by marcellmars** [comment]
I don't know if what would you like to see in Hugo will eventually end up there but here is another way how you could do that...

If you make your own shortcode for example _layouts/shortcodes/prms.html_ and inside _prms.html_ you have:
```
{{ printf "[%s](%s)" (.Get 0) ($.Page.Param (.Get 1)) | $.Page.RenderString }}
```

this should do the job:

```
+++
title = "test"
mylink = "https://www.example.com"
+++

This is an external [link](https://www.example.com)

Another external {{< prms "link" "mylink" >}}
```

**Comment by jmooring** [comment]
Instead of:

```
Another external [link]({{< param "mylink" >}})
```

Do this:

```
Another external [link]({{< param "mylink" >}})
```
Duplicate of #7416.

**Comment by karamme** [comment]
Thanks for the input. Rendering the param does indeed help, so I will close this issue and keep track of the other one.
