### ISSUE TITLE
Enable static builds for hugo_extended releases

### ISSUE THREAD

**Issue by bew** [gohugoio/hugo#7011]
Hello,

I'm hitting #5166 when trying to use hugo_extended on an old CentOS machine.

I noticed that the normal build (not extended) is statically built (so no issues with an old glibc), but the extended version of hugo is dynamically built and thus fails to find the exact same glibc version as your build system.

I checked in the [`goreleaser.yml`](https://github.com/gohugoio/hugo/blob/cb12f41a969a569cc00d5a45d5bfa846baffa45c/goreleaser.yml) file and I see that for the `hugo_extended_windows` build, you explicitely build it in static mode:
https://github.com/gohugoio/hugo/blob/cb12f41a969a569cc00d5a45d5bfa846baffa45c/goreleaser.yml#L36

Whereas for the linux builds it is never explicitly specified.

Also I don't unserstand why the normal hugo build (not extended) is built statically even though it is not mentionned as a build flag.. I'm not familiar with go' build toolchain, so maybe there is a rule in the compiler that makes the build static in some cases?

Anyway, is it possible to **enable static build for linux versions of the hugo_extended release** ? so that we could use the hugo / hugo_extended binaries anywhere, regardless of the installed glibc version.

Thank you in advance

**Comment by bep** [comment]
This has been discussed before. Use the search.

**Comment by bew** [comment]
Thank you for your answer,
I know it has been discussed before, and the recommended method is to either upgrade the glibc version or build hugo from source.

In the other issues about this, I didn't find any mention on **enabling static build** for hugo_extended, like the normal build.

If hugo_extended was built statically, there would be no issue with running it on a system with an old glibc version, hence this issue.
