### ISSUE TITLE
homebrew installation seems quite out of date

### ISSUE THREAD

**Issue by trauts2** [gohugoio/hugo#7013]
### What version of Hugo are you using (`hugo version`)?
0.62

<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release?
N/A

I see the latest release is Hugo 0.66.0, however homebrew is far behind at 0.62.2

`Tue Mar  3 15:30:10 CST 2020
Stuarts-MacBook-Pro:~ stu$ brew upgrade hugo
Warning: hugo 0.62.2 already installed`

Is there a trick to getting more recent releases via homebrew for Hugo?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
