### ISSUE TITLE
Add http in front of url when running hugo

### ISSUE THREAD

**Issue by shiftgeist** [gohugoio/hugo#7015]
![image](https://user-images.githubusercontent.com/30648730/75854800-3a030780-5df1-11ea-81b7-e2d32df50ed3.png)

The problem is that the link is not clickable in the terminal.

```diff
- Web Server is available at //localhost:8080/ (bind address 127.0.0.1)
+ Web Server is available at http://localhost:8080/ (bind address 127.0.0.1)
```

**Comment by bep** [comment]
![image](https://user-images.githubusercontent.com/394382/75862684-9b31d780-5dff-11ea-9103-5405ba37c6d7.png)

You need to fix your `baseURL`. We could _maybe_ do some magic here for the built-in server, but I rather prefered that you corrected the input.
