### ISSUE TITLE
0.66: page reference is ambiguous (with repro)

### ISSUE THREAD

**Issue by artch** [gohugoio/hugo#7016]
<pre>
$ hugo version
Hugo Static Site Generator v0.66.0/extended windows/amd64 BuildDate: unknown
</pre>

I'm getting `page reference is ambiguous` on v0.66.0 for my site:

```
C:\Hugo\sites\test>hugo
Building sites … Total in 22 ms
Error: Error building site: failed to render pages: render of "home" failed:
"C:\Hugo\sites\test\layouts\index.html:5:7": execute of template failed:
template: index.html:5:7: executing "main" at <$.Site.GetPage>: error calling GetPage: page reference "/docs/1" is ambiguous
```

I've attached a [minimal repro site](https://github.com/gohugoio/hugo/files/4287105/test.zip) with this error. The structure of the `content` folder is the following:
```
content
├── docs
│   └── 1.md
└── news
    ├── 1.en.md
    ├── 1.md
    └── about
        ├── 1.en.md
        └── 1.md
```

The error disappears if I remove any of the two `1.en.md` files in `news`, although the error is related to `docs/1.md` file, so it's obviously a bug.

**Comment by AndreSteenbergen** [comment]
Running into the same issue; I am using overrides of an _global directory inside; a script goes up the tree, but is able to find 2 _global directories, and it raises this error. The script was working in previous version.
