### ISSUE TITLE
Hugo fails to import module after GitHub repo renamed

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#7019]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.65.0-24AFE2B82/extended darwin/amd64 BuildDate: 2020-02-20T09:07:35Z
</pre>

### Does this issue reproduce with the latest release?
Yes but has been failing since firs try on 62.0

Following this [thread](https://discourse.gohugo.io/t/hugo-fails-downloading-module-after-repo-name-change/23420)

### Step to reproduce:
1. Import a module hosted on GitHub
2. Rename the repository for said module
3. Update config file from project with new repo name
4. Run `hugo` or `hugo mod [anything]`

Result is hugo failing with `parsing go.mod: unexpected module path`

Hugo works fine if project imports the old path, relying on GitHub redirects.

**Comment by bep** [comment]
I'm pretty sure I've done this (several times): The thing is, in your renamed GitHub repo there is a `go.mod` file -- you need to edit that by hand with the new path.

**Comment by regisphilibert** [comment]
🤦‍♂ or course!

**Comment by regisphilibert** [comment]
I updated the module. Still same problem. I tried removing any mention of the module from config or `go.sum` and `tidy` + `clean` or doing `   `hugo mod get github.com/theNewDynamic/hugo-module-tnd-socials`.

Nothing 🤷‍♂

**Comment by bep** [comment]
Here is a few tips for you:
 
* In the project that is using this module, edit the go.mod and replace its version string with, say, master, or even delete the entire line manually
* If that fails, clean the cache ... either with `hugo mod clean` or `hugo mod clean --all`.

Also, If you have an older Go version, I would recommend you upgrade.

**Comment by regisphilibert** [comment]
Thanks a ton!
