### ISSUE TITLE
deploy: Make delete respect Include/Exclude Filters

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7020]

**Comment by bep** [comment]
I have thought a little about this, and if I were to split my site into domains, I would split it into different buckets or into different subpaths in the same bucket. Either way, there would only be files matching the filters in that bucket/path. So, when I delete I probably always want to clean it up completely, and in case I change my filters, that means "all files".

So, I'm not sure this issue is needed/wanted.

/cc @zbayoff @vangent

**Comment by zbayoff** [comment]
@bep @vangent I understand your viewpoint. For our use case, we have processes that create files outside of Hugo in our pipeline and upload them to the remote bucket. We need to be able to exclude those files from being deleted. This process works for us currently with AWS CLI, so we were hoping to replicate this behavior with `hugo deploy`.

**Comment by vangent** [comment]
Was this fixed in #7024 ?

**Comment by bep** [comment]
@vangent I think so, I'm closing it -- if it's still is an issue, we'll need to create another one.
