### ISSUE TITLE
Add .keep files to skeleton to get from scaffold to VCS with less friction

### ISSUE THREAD

**Issue by bitmvr** [gohugoio/hugo#7021]
Currently the skeleton generates a site with empty directories. `git` and other Version Control Systems (VCS) will ignore empty directories. There is a common pattern of using an empty file called `.keep`. This will allow one to quickly store a project skeleton in their VCS without having to manually create files before pushing. I'm not necessarily pushing that this should be the default behavior, but the option would be nice.

```
bash-3.2$  find . -not -path '*/.git*'
.
./archetypes
./archetypes/default.md
./resources
./resources/.keep
./resources/_gen
./resources/_gen/images
./resources/_gen/assets
./content
./content/.keep
./layouts
./layouts/.keep
./static
./static/.keep
./config.toml
./data
./data/.keep
./themes
./themes/.keep
```

> **Learn More:** https://medium.com/@kinduff/hey-git-please-keep-those-folders-eb0ed37621c8

**Comment by Traumflug** [comment]
Not direct part of the proposal: `resources/` shouldn't go into the VCS repository. According to documentation, it's for generated stuff only (and gets created by Hugo as needed): https://gohugo.io/getting-started/directory-structure/#directory-structure-explained

**Comment by Traumflug** [comment]
Opinion on this proposal: such .keep files are very specific to the VCS in use. Git needs them, other VCSs don't. And Hugo AFAIK makes no distinction between an empty folder and a not existing one, so adding empty folders to the repo is moot.
