### ISSUE TITLE
Consider not deprecating Mmark support

### ISSUE THREAD

**Issue by oblitum** [gohugoio/hugo#7022]
Math support (both MathJax or KaTeX) and other enhanced extensions have been working great by taking advantage of `.mmark` files since circa 2015. Many people are relying on Mmark for their posts due to that. As per https://github.com/gohugoio/hugo/issues/6544#issuecomment-595323813, since release 0.60, Mmark has been marked deprecated, with potential future removal. In the release notes there's no rationale for the removal of Mmark, it's happening as some side effect for the replacement of Blackfriday for Goldmark, which serves only plain Markdown, not the Mmark dialect.

Given that Mmark has been available besides Blackfriday all this time, wouldn't it be nicer to keep operating in the same model and leave Mmark besides Goldmark and break almost no users instead of breaking all Mmark users?

In case removal is going to happen regardless, it would be good to have the reason published. I have not yet found a note why Mmark should go due to Blackfriday, given that packages are distinct.

**Comment by bep** [comment]
The rationale:

1. The package is marked as deprecated upstream, so any bugs etc. will not be fixed.
2. Reduce package/binary size.
2. To reduce maintenance. We have a test suite that covers mmark that we need to maintain and check when we make changes elsewhere. Also, we have do support here and on the forum (answer questions, handle bug requests).

All of the above may not bee too much for mmark alone, but it adds up in the long run. We're not staffed like Microsoft, so to speak, and you should have a look at my "notification board" related to Hugo ... I need less work, not more.

**Comment by oblitum** [comment]
> The package is marked as deprecated upstream, so any bugs etc. will not be fixed.

FWIW, it's marked deprecated, but for the old one (for a good time already), because there's a newer one, which I thought Hugo was making use of by now.

**Comment by bep** [comment]
>which I thought Hugo was making use of by now.

We don't. And it's not a "new package", it's a totally "new thing".

**Comment by oblitum** [comment]
I don't get your tone, as it's a new package for sure (by the same author, for the same purpose, with same math features). The main issue here is not what package is used, but dropping support for _the dialect_, which is what's user facing, the most sad part of all this is not to be able to author in Mmark anymore. The usual approach in these situations is to stick to the old dependency until a migration to the new one finally lands at some point. I do get you were not involved in the addition of Mmark [when it was added](https://github.com/gohugoio/hugo/pull/862) (I started using Hugo when it was still under spf13's repository) and seems not to care about it enough to not mind breaking the users that have been relying on it these years.

I know this is open source and you now may be managing the project on your free time for free. Still, to have a user base broken this way, requiring all their files to be rewritten and file extensions changed, strongly points that the project isn't sanely reliable anymore.

**Comment by bep** [comment]
>I don't get your tone,

I'm sorry that I was a little short. My inbox is long, which kind of illustrates the core of this problem.

>The usual approach in these situations is to stick to the old dependency until a migration to the new one t lands at some point.

The new dependency is something totally new, something completely different. If added, it should be added with the identifier "mmark2" or something. But that discussion needs to be raised in another issue.
