### ISSUE TITLE
Upgrade Mmark to version 2 instead of dropping it entirely

### ISSUE THREAD

**Issue by oblitum** [gohugoio/hugo#7023]
As suggested at https://github.com/gohugoio/hugo/issues/7022#issuecomment-595431010, this issue has been raised for the consideration of upgrading support for the Mmark dialect to [version 2 onwards](https://mmark.miek.nl/), instead of dropping support for `.mmark` files entirely.

**Comment by oblitum** [comment]
> If this is a feature request, and you feel that it is still relevant and valuable, please tell us why.
This issue will automatically be closed in the near future if no further activity occurs. Thank you for all your contributions.

Still pretty important and relevant given there's no seamless option as Mmark for math rendering [according to reports](https://github.com/gohugoio/hugo/issues/6544#issuecomment-595265026), it's still the best one can get.

**Comment by oblitum** [comment]
No further info besides https://github.com/gohugoio/hugo/issues/7023#issuecomment-653687542 and that people seem to support this request.

**Comment by mohkale** [comment]
Did this change go through? I've just noticed all the block-level attributes I had for lists or other elements seem to have stopped working after a recent hugo upgrade. So now I see literal `{.some-class}` in the output. I believe goldmark supported these but only for headings and blackfriday doesn't seem to support them at all. The docs still mention block-level attributes, but they no-longer seem to be working :cry:.

**Comment by oblitum** [comment]
@mohkale sources still point to mmark v1.

**Comment by mohkale** [comment]
@oblitum 

That's strange. Must be a configuration update or something to that affect. I've downgraded to v0.85.0 and everything seems to be working again.

**Comment by oblitum** [comment]
Oh no. Mmark is set to be removed on 0.88!

As most upvoted currently we're at position 29 out of 605 open issues. Upvote count is roughly 1/10 of the most upvoted issue.

**Comment by oblitum** [comment]
This is still just as relevant today as it was before. Anyway, I personally don't care anymore, I've pinned the last version of hugo that supported Mmark (which has been dropped already in the latest versions) on all installations I have because I'm not willing to convert all my Mmark contant to another thing just to **miss** features. Feel free to close.

**Comment by oblitum** [comment]
Closed as **not** completed.
