### ISSUE TITLE
error when hugo <command> run with hugo 0.66

### ISSUE THREAD

**Issue by Shurikken** [gohugoio/hugo#7025]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version = 0.66

</pre>

### After upgrade hugo i have this error when i use hugo commande with MAC OS Sierra
hugo server
SIGILL: illegal instruction
PC=0x406a670 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc00016b4d8 sp=0xc00016b4d0 pc=0x406a670
strings.(*Builder).WriteString(...)
	/usr/local/Cellar/go/1.14/libexec/src/strings/builder.go:123
strings.Join(0xc00055e000, 0xf4, 0xf4, 0x58365c8, 0x1, 0xc00016b608, 0x400f688)
	/usr/local/Cellar/go/1.14/libexec/src/strings/strings.go:442 +0x2d6 fp=0xc00016b5b0 sp=0xc00016b4d8 pc=0x40fde16
github.com/alecthomas/chroma.Words(0x0, 0x0, 0x5836873, 0x2, 0xc00055e000, 0xf4, 0xf4, 0xc000041000, 0x84)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/alecthomas/chroma@v0.7.1/regexp.go:144 +0xe5 fp=0xc00016b638 sp=0xc00016b5b0 pc=0x4564aa5
github.com/alecthomas/chroma/lexers/s.init()
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/alecthomas/chroma@v0.7.1/lexers/s/systemverilog.go:43 +0x1a774 fp=0xc00016bda8 sp=0xc00016b638 pc=0x46a9694
runtime.doInit(0x692b360)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc00016bdd8 sp=0xc00016bda8 pc=0x40456aa
runtime.doInit(0x6938540)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016be08 sp=0xc00016bdd8 pc=0x4045677
runtime.doInit(0x6931f40)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016be38 sp=0xc00016be08 pc=0x4045677
runtime.doInit(0x69300e0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016be68 sp=0xc00016be38 pc=0x4045677
runtime.doInit(0x6930080)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016be98 sp=0xc00016be68 pc=0x4045677
runtime.doInit(0x693c940)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016bec8 sp=0xc00016be98 pc=0x4045677
runtime.doInit(0x6932ec0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016bef8 sp=0xc00016bec8 pc=0x4045677
runtime.doInit(0x6941280)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016bf28 sp=0xc00016bef8 pc=0x4045677
runtime.doInit(0x69408e0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016bf58 sp=0xc00016bf28 pc=0x4045677
runtime.doInit(0x69285a0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016bf88 sp=0xc00016bf58 pc=0x4045677
runtime.main()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc00016bfe0 sp=0xc00016bf88 pc=0x4038aae
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00016bfe8 sp=0xc00016bfe0 pc=0x4068df1

rax    0x2e3
rbx    0x2ea
rcx    0xc00016b580
rdx    0x7
rdi    0xc0005602e2
rsi    0xc000560000
rbp    0xc00016b5a0
rsp    0xc00016b4d0
r8     0x58472a0
r9     0x2e2
r10    0xc00016b580
r11    0x2e3
r12    0xc000560000
r13    0x757
r14    0x5c18420
r15    0x0
rip    0x406a670
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0

**Comment by bep** [comment]
This looks to be an issue with Chroma and I would appreciate if you could create and issue at https://github.com/alecthomas/chroma/issues which is closer to where it needs to be fixed. It would be good if you could link back to this issue so we can track the progress.

**Comment by ValentinChevoleau** [comment]
hi @bep i'm sorry :)

for track the progresse : https://github.com/alecthomas/chroma/issues/342 

best regards,

**Comment by alecthomas** [comment]
There's almost zero chance SIGILL is caused by Chroma, it's most likely a hardware issue, or compiler/runtime issue.

**Comment by alecthomas** [comment]
Specifically, it is most likely [this issue](https://github.com/golang/go/issues/37459).

**Comment by ValentinChevoleau** [comment]
hi @alecthomas 
i'm so sorry but i don't understand who can i fix my problem.
Could you help me 
thank you so munch

**Comment by mxmerz** [comment]
I had the same problem with an old 2010 MacBook Pro, all my Go apps produced this same error message. As @alecthomas said, this seems to be [issue #37459 of golang/go](https://github.com/golang/go/issues/37459). They fixed the issue on 2020-02-26 and [created a backport of the fix to Go 1.14](https://github.com/golang/go/issues/37478). Go 1.14.1 was released 2020-03-19 (see issue comments) and fixes the bug for me.
I assume updating Go and/or Hugo should solve your problem.

**Comment by Shurikken** [comment]
hi 
brew integrate a new go version and my problem is fixed. thank you every body end sorry for my small level.
have a nice day
