### ISSUE TITLE
Check if we can add resource transformation options without invalidating existing cache

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7036]
See https://github.com/gohugoio/hugoThemes/issues/814

In Hugo 0.66 I added a new bool config to the PostCSS config struct (import support); we include a hash of this struct in the hash used to detect changes. The hashing library we use for this says in the documentation that the hash will change if a field is added -- even if it has a zero value. 

I, of course, did not think about this. 

I'm not sure I'm willing to do the work needed to create Hugo 0.65 compatible hashes (that train has left -- people need to rebuild their themes and commit the new /resource content).

But I'll open this issue to think if we can prevent this in the future. It should not be too often, but it's annoying when it happens.

I have committed new sources to my DocuAPI theme, I assume that will work once it gets an update in the theme repo.

/cc @onedrawingperday @digitalcraftsman

**Comment by onedrawingperday** [comment]
> I have committed new sources to my DocuAPI theme, I assume that will work once it gets an update in the theme repo.

It does work. The following is from the latest Netlify deploy log.
```
9:14:59 PM:  ==== PROCESSING  docuapi  ======
9:14:59 PM: docuapi is whitelisted
9:14:59 PM: Building site for theme docuapi using its own exampleSite to ../themeSite/static/theme/docuapi/
```

Thanks for looking into this. 

I will notify the other theme authors about the need to regenerate their resources and reference this issue.
