### ISSUE TITLE
behavior of os.Stat is different by OS

### ISSUE THREAD

**Issue by doowonee** [gohugoio/hugo#7037]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.67.0-7F1DA3EF/extended linux/amd64 BuildDate: 2020-03-09T20:44:34Z
</pre>

### Does this issue reproduce with the latest release?
 yes

# What I want to do

I tried to get file size of static files via `os.Stat`. 

# list.html in section directory in Windows 

`{{ $stat := os.Stat "test.jpg" }}` $stat is `/site-root-path/content/primary-language/test.jpg` 
`{{ $stat := os.Stat (path.Join "static" "test.jpg") }}` $stat is `/site-root-path/static/test.jpg` 

# list.html in section directory in Ubunt 18.4 LTS
`{{ $stat := os.Stat "test.jpg" }}` $stat is `/site-root-path/content/primary-language/test.jpg` 
`{{ $stat := os.Stat (path.Join "static" "test.jpg") }}` $stat is `/site-root-path/content/primary-language/static/test.jpg`

# What I expected

as you see `os.Stat` always work relative path of content directory unlike Windows so I could not get the file size of static files when I deploy on netlify. How should I do?

**Comment by narrenfrei** [comment]
> I could not get the file size of static files when I deploy on netlify.

Same problem here. Can't deploy my site on netlify, because I'm using os.Stat to get the file size. (In my case for a page resource.)
