### ISSUE TITLE
invalid BaseURL when it is not set

### ISSUE THREAD

**Issue by prashant-shahi** [gohugoio/hugo#7044]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.63.2-934EE21F linu
x/amd64 BuildDate: 
</pre>

### How to reproduce

For `v0.58`, when I don't set any Base URL, the `.Site.BaseURL` variable is blank.

For the `v0.63`,  let's say for a domain `abcd-1234.surge.sh` when I don't set any Base URL, the `.Site.BaseURL` variable is `abcd-1234`.

I believe that it should be either blank or the complete URL `abc-1234.surge.sh`.
Do let me know if this is intended.

**Comment by bep** [comment]
The baseURL should be a valid URL with protocol and all, e.g. `https://example.org`. Neither of your examples matches that. We should consider adding some validation to this, but that would break many sites in the wild using `/` etc.

**Comment by prashant-shahi** [comment]
@bep, My bad. Now, I have edited the PR description to include `https` as well.

This clearly looks like a bug to me as the same code worked well for Hugo `v0.58`.
