### ISSUE TITLE
YouTube Shortcodes don't work

### ISSUE THREAD

**Issue by RebelCoderRU** [gohugoio/hugo#7047]
### What version of Hugo are you using?

<pre>
$ hugo version
1) Hugo Static Site Generator v0.68.0-DEV/extended linux/amd64 BuildDate: unknown
2) Hugo Static Site Generator v0.65.3/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes.

### Issue:
YouTube shortcode does not display a video. It plays in the background, but there is no image. Space is also allocated for the size of the video frame:

![image](https://user-images.githubusercontent.com/20476773/76522043-d070a200-645d-11ea-8e0b-36414f07677a.png)

Even example templates that include YouTube videos as a 'rich content' don't display YT Videos.

### Browser tested on:
Firefox: 75.0b2 (64-bit)
Chromium: Version 80.0.3987.122 (Official Build) Arch Linux (64-bit)

### System:
Manjaro Linux x86_64 
Kernel: 5.5.7-1-MANJARO

**Comment by onedrawingperday** [comment]
This is a support question that belongs in the forum: https://discourse.gohugo.io/

In the [Hugo Themes Showcase](https://themes.gohugo.io/) most theme demos display sample content that displays an example of the YouTube Privacy Enhanced Shortcode like [over here](https://themes.gohugo.io//theme/hugo-swift-theme/post/rich-content/#youtube-privacy-enhanced-shortcode).

As shown in the link above the shortcode works fine with the latest Hugo version.

**Comment by jakehell** [comment]
I'm not able to reproduce.

Used the following:
```
OS: Lubuntu 18.04 i386
Hugo version: Hugo Static Site Generator v0.68.0-DEV linux/386 BuildDate: unknown
Browser: Firefox 72.02
```

![2020-03-15-123528_1280x800_scrot](https://user-images.githubusercontent.com/5951826/76707047-19249700-66ba-11ea-8ae9-9c889f2bdd00.png)

**Comment by jmooring** [comment]
I am also unable to reproduce the issue. Tested:

```html
{{< youtube id="w7Ft2ymGmfc" autoplay="true" >}}
```

with the following in `config.toml`:

```toml
[privacy.youtube]
privacyEnhanced = false
```

I get the same (favorable) results with: 

```toml
[privacy.youtube]
privacyEnhanced = true
```

Tested with `Hugo Static Site Generator v0.69.2/extended linux/amd64 BuildDate: 2020-04-24T12:43:32Z`.
