### ISSUE TITLE
About "The world’s fastest framework for building websites."

### ISSUE THREAD

**Issue by fredericgermain** [gohugoio/hugo#7050]
Can you share some data about this claim?
I could not find anything in the documentation/blog. How does it compare to other static site generators?

This claim is written either in the project title or in **bold** on your website so I guess you made a solid assessment at some point?

I could only find [here](https://spf13.com/project/hugo/).
`A typical website of moderate size can be rendered in a fraction of a second. A good rule of thumb is that Hugo takes around 1 millisecond for each piece of content. It’s so fast that it will render the site in less time than it takes to switch to your browser and reload.`

I've just tried zola, a rust static site generator. It could handle 10000 (empty) documents in 800ms. So it's more than 10 times faster than hugo?

**Comment by bep** [comment]
This is a slogan. Marketing. Hugo is a very _rapid_ development framework (fast rebuilds on changes in dev server etc.) and in general very fast builds.

I can write a static generator that builds 100000 something much faster than Hugo. No problem. But Hugo is fairly feature-packed by now so that would be comparing  apples to tomatoes.

The current slogan cannot be documented, you are correct about that. But it's a great slogan.

**Comment by bep** [comment]
I can add that what is stated in the documentation about 1 page per ms is old information. Also, generating 10000 empty documents is (almost) all about disk io.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by fredericgermain** [comment]
Ok. Fair enough.

As you said, it's quite easy to do faster. Especially you can never two implementations have exactly the same features. And there would be no point anyway. Zola claims it also has more features than Hugo on their readme. But the list of features is documented their (though probably not up to date).
I don't care about zola that much, I've only used gatsbyjs in the past. I've just know a rust generator would also be fast.

But having quite some experience in computing, I just felt that claim was a big lie in my face somehow. But maybe it was true when hugo was being developed though. And zola came after and was actually just inspired by your project.

I'd also say diskio wouldn't impact much the performance on our computer with GBs of RAM and swap these days (except of course in the first run from reboot), it's mostly about CPU and code efficiency.
