### ISSUE TITLE
Server not refreshing with content change (windows/linux)

### ISSUE THREAD

**Issue by billthefarmer** [gohugoio/hugo#7053]
Raised as a query on discourse &ndash; https://discourse.gohugo.io/t/hugo-server-not-refreshing-with-content-change/23858.

I am using the kraiklyn theme which uses hierarchical content files to generate a single web page for docs. Hugo version 0.64 works correctly and updates the web page when a content file changes. Hugo 0.65.3 and 0.66 update correctly if the config file changes, but not if a content file changes. The changes are detected and the site is rebuild according to the shell output. The web page refreshes but does not change. There does not seem to be any difference in the output between the versions processing the same changes that I can see.

As another user has reported the same problem on discourse I am reporting a bug.

**Comment by marsavela** [comment]
I am joining this. I have not tested different versions, so I shall report back shortly, but lately I've been having this issue as well. I will test and report back.

**Comment by billthefarmer** [comment]
Just tested v0.67.1-4F44227B windows/amd64, issue still present.

**Comment by billthefarmer** [comment]
Curiouser and curiouser &ndash; I removed the draft flag from the front matter of a post in my blog. The post appeared in the list of recent posts in the sidebar, but not in the site index until I restarted the server. The site index uses shortcut code...
```html
<!--
    Site index shortcut from categories
  -->
{{ if .Get 0 }}
{{ $category := .Get 0 }}
<section>
  <h3>{{ title $category }}</h3>
  <ul>
    {{ with (index .Site.Taxonomies.categories $category) }}
    {{ range .Pages.ByTitle }}
    <li><a href="{{ .Permalink }}">{{ safeHTML .LinkTitle }}</a></li>
    {{ end }}
    {{ end }}
  </ul>
</section>
{{ else }}
<section>
  {{ range $key, $value := .Site.Taxonomies.categories }}
  <h3>{{ title $key }}</h3>
  <ul>
    {{ range $value.Pages.ByTitle }}
    <li><a href="{{ .Permalink }}">{{ safeHTML .LinkTitle }}</a></li>
    {{ end }}
  </ul>
  {{ end }}
</section>
{{ end }}
```
I don't understand what the `{{ if .Get 0 }}` at the start is about, I think I copied this code from an example in the docs.

**Comment by dceuppens** [comment]
Same issue here. Changes in md files do regenerate the site but nothing changes in the browser until I stop & restart the server. Using hugo server --noHTTPCache --disableFastRender --ignoreCache but the additional parameters don't seem to work.

**Comment by billthefarmer** [comment]
This appears to be fixed in the latest release &ndash; v0.68.3-157669A0 windows/amd64 BuildDate: 2020-03-24T12:04:36Z.

**Comment by flibustenet** [comment]
Still doesn't refresh when content change with today pull.
`Hugo Static Site Generator v0.69.0-DEV linux/amd64 BuildDate: unknown`

It see the change and reload the page but the content stays the same. The content is not parsed (if there is a syntax error it doesn't see the error). I did try with and without `--disableFastRender --renderToDisk --noHTTPCache --ignoreCache`

**Comment by flibustenet** [comment]
My bad, i had a bad config file with `content` directory in `staticDir`.
Now i can confirm that for me it works now, even without `--disableFastRender` and any other option. Maybe this issue can be closed.

**Comment by rodrigoalcarazdelaosa** [comment]
I'm _suffering_ this with Hugo 0.74.3, working with macOS 10.15.6
