### ISSUE TITLE
mailto link with subject does not render 

### ISSUE THREAD

**Issue by juh2** [gohugoio/hugo#7054]
A link like this 

[Linktext](mailto:foo@bar.com?subject=This is my subject)

does not render anymore.

hugo 0.67

**Comment by Brixy** [comment]
You need to replace spaces with `%20`.

This should work:

```
[Linktext](mailto:foo@bar.com?subject=This%20is%20my%20subject)
```

**Comment by DirtyF** [comment]
Same thing happens for images containing spaces in the filename, they don't get rendered, Hugo will display the original Markdown source. Not sure it's it a Goldmark or Hugo issue. This was working before (0.58.2)

![](/static/images/image 2.jpg)

**Comment by jmooring** [comment]
From the [CommonMark specification](https://spec.commonmark.org/0.29/#link-destination):

> A link destination consists of either
> 
> a sequence of zero or more characters between an opening < and a closing > that contains no line breaks or unescaped < or > characters, or
> 
> a nonempty sequence of characters that does not start with <, does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

This specification is applicable to both links and images, and Goldmark adheres to the specification. Your options:

1. URL Encoding as suggested by @Brixy:

```
[Linktext](mailto:foo@bar.com?subject=This%20is%20my%20subject)
```

2. Encapsulate within `<>`:

```
[Linktext](<mailto:foo@bar.com?subject=This is my subject>)
```

**Comment by DirtyF** [comment]
Try to explain that to contributors using a WYSIWYG, uploading and linking to an image in a CMS.  😩
