### ISSUE TITLE
SCSS @import ERROR after latest commit (1a8af7d)

### ISSUE THREAD

**Issue by pamubay** [gohugoio/hugo#7063]
### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.68.0-DEV-1A8AF7D4/extended linux/amd64 BuildDate: 2020-03-17T09:03:32+0700
</pre>

### Does this issue reproduce with the latest release?
Yes

After this commit https://github.com/gohugoio/hugo/commit/1a8af7d4f087256710ae0bdf504ed53c0c24a211 SCSS @import doesnt work.

Error:
```
Error: Error building site: TOCSS: failed to transform "styles/file.scss" (text/x-scss): SCSS processing failed: file "stdin", line 11, col 16: Undefined variable: "$font-sans". 
```

The Problem, The RegEx also match the `.scss` @import
https://github.com/gohugoio/hugo/blob/1a8af7d4f087256710ae0bdf504ed53c0c24a211/resources/resource_transformers/tocss/scss/client.go#L79
![regex_bug](https://user-images.githubusercontent.com/18132440/76816058-d1288000-6831-11ea-928d-6b3d270658d8.png)

Should be:
```
.*(@import "(.*\.css)";).*
```

**Comment by bep** [comment]
Thanks! That was a stupid mistake. Odd that I didn't have a test catching it.
