### ISSUE TITLE
Allow generating GUID with a function

### ISSUE THREAD

**Issue by undergroundwires** [gohugoio/hugo#7068]
**Use-case**: I have shortcodes that can be used multiple times on same page. I need to create a unique HTML element in shortcodes and then populate its content with JS.
**Problem**: If elements do not have unique ID then JS populates all elements on the page.
**Proposed solution**: Allow a function like `createGuid` so I can set that as elements ID and retrieve it with JS.

**Comment by bep** [comment]
The problem with GUID is that it would be different every time. 

For your shortcodes you can use the shortcode Ordinal as the ID (or at least a part of it) (`.Oridinal`).

**Comment by undergroundwires** [comment]
Hi  @bep , thanks for the awesome library and that you maintain it. `.Ordinal` actually solves my problem. I did not know it existed. I should have probably opened this issue on `hugo` forums instead of here. Closing this now to not pollute the issues.

**Comment by undergroundwires** [comment]
Hi @bep , thanks for the awesome tool and that you maintain it. `.Ordinal` actually solves my problem. I did not know it existed. I should have probably opened this issue on hugo forums instead of here. Closing this now to not pollute the issues.
