### ISSUE TITLE
Line breaks in summary not translated into p tags

### ISSUE THREAD

**Issue by inwardmovement** [gohugoio/hugo#7069]
<pre>
Hugo Static Site Generator v0.67.1/extended windows/amd64 BuildDate: unknown
</pre>

---

[Front Matter Summary docs](https://gohugo.io/content-management/summaries/#front-matter-summary) says:

> Markup can be used within the summary.

But line breaks in the `summary` frontmatter variable are not translated into `<p>` tags.
Applying ` | markdownify` doesn't fix.

It would be great to render paragraphs in `.Summary` via the `summary` frontmatter variable.

**Comment by satotake** [comment]
It works as you expect.

Some notes.
- What kind of format you are using? if it is yaml, you may need `|` symbol.
  - More details: https://yaml-multiline.info/
- You need an empty line (2 line breaks, `\n\n`) to wrap texts with `<p>` 


You can refer [my reproducible example](https://github.com/satotake/hugo-test/tree/issue-7069)
Tested with `Hugo Static Site Generator v0.65.2/extended darwin/amd64 BuildDate: unknown` .

@inwardmovement

**Comment by inwardmovement** [comment]
@satotake Ok thanks! I didn't know about the `|`. It seems not very suitable when working with a CMS/non dev content editors though, but it's good to know that it's possible.
