### ISSUE TITLE
Hugo Docker does not load a theme

### ISSUE THREAD

**Issue by Adeljoo** [gohugoio/hugo#7071]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.64.1 

</pre>

**Comment by Adeljoo** [comment]
I am using this hugo docker to https://hub.docker.com/r/monachus/hugo/dockerfile build my website but it does not load the theme.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
