### ISSUE TITLE
<img> generated from markdown ignores `canonifyURLs`

### ISSUE THREAD

**Issue by nekr0z** [gohugoio/hugo#7073]
### What version of Hugo are you using (`hugo version`)?
v0.67.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes.

I organize content so that images for `posts/some_post.md` are all stored in `posts/some_post/` so I can reference images with just a filename without any path. I expect the generated `<img>` tags to respect `canonifyURLs`, but they don't: even with `canonifyURLs` set to `true` I get `<img src="picture.png">`.

**Comment by bep** [comment]
I suspect you misunderstand/have too big faith in what `canonifyURLs` does -- and I'll admit the documentation does not help:

* It makes "baseURL relative" URLs absolute. These URLs must start with a `/`.
* We do not know anything about the "relative context" when doing this, hence your example is left alone.

If you want to solve this, I suggest making your posts into bundles and bundle the images with the markdown. Also see https://portable-hugo-links.netlify.com/
