### ISSUE TITLE
SIGILL: illegal instruction Hugo commands fail

### ISSUE THREAD

**Issue by Greg-Boggs** [gohugoio/hugo#7080]
Hugo doesn't work on older Macs anymore. It fails because of a bug in Go 1.14 that should be fixed soonish. I tried compiling Hugo with Go 1.13, but I wasn't getting it to work.

So, if you get this error, I got around it by using the older hugo v0.63.2.

You can find out more here: https://github.com/golang/go/issues/37459

**Comment by bep** [comment]
You need to take this at the Go issue tracker.
