### ISSUE TITLE
Add resources.GetRemote

### ISSUE THREAD

**Issue by iinfin** [gohugoio/hugo#7083]
As far as I'm aware current SRI function requires `resources.Get`, which requires the file to be in assets folder.

I think it'd be nice if we can use it also with external files
Thanks!

**Comment by bep** [comment]
We have another issue about `resources.GetRemote` which would solve this (and more).

**Comment by iinfin** [comment]
Ah yes, `GetRemote` sounds like a convenient solution! It could make external sources modular and make the site flexible overall (to copy/inline, minify, hash them during build)

I suppose you're referring to [#5686 PR](https://github.com/gohugoio/hugo/pull/5686) though, seems to be closed due to inactivity.

**Comment by atishay** [comment]
This can be very useful for also fetching images from external sources and processing them to the right size before bundling. 

https://github.com/gohugoio/hugo/pull/5686 has been inactive for a while though.

**Comment by c-nv-s** [comment]
I'm a little confused.
I was checking if anyone has added a feature request that supports performing generic POST requests to a url or generic http requests. 
I can see there are a few related linked issues here  e.g #5686  and #5255 but can't tell if it was actually agreed to implement a generic http request feature?

**Comment by atishay** [comment]
I think GetRemote is about fetching CSS, JS, or image files from remote endpoints. I don't think a post request would be inside of a get.

This is very useful, for example, in getting Avatars from gravatar in filling comment forms.

**Comment by jmooring** [comment]
Addressed with https://github.com/gohugoio/hugo/pull/9185
