### ISSUE TITLE
Single line HTML comments not allowed at beginning of file

### ISSUE THREAD

**Issue by halvorsanden** [gohugoio/hugo#7092]
I updated from 0.63.2 to 0.68.1 and started getting the following error when building: `Error building site: "~/[project/hugo-folder]/content/code-examples/html/example.html:2:1": plain HTML documents not supported`

It seems like it is caused by a change introduced in 0.67. I have tested with 0.65.3 and 0.66 and they both work. (I haven’t tested 0.68.2, as it’s not available via brew or hugo-bin ATM.)

I use a shortcode to embed a lot of code example files in my pages: 
`{{ readFile (.Get "file") | safeHTML }}`
Said files have no front matter, they’re just code snippets.
The issue appears only when embedding files starting with html comments, like 
`<!-- Simple example -->`. 
If I add a new line after the initial `<!--`, there is no problem.

By the looks of PR https://github.com/gohugoio/hugo/pull/7034/, comments at the start of the file should be allowed. But judging by line 38 at https://github.com/gohugoio/hugo/pull/7034/files#diff-41a70a11df8b82baa79e943c68f1c59eR34-R44 it seems like it only applies when there is a new line after the opening comment tag. Shouldn’t line 39 also be `false`, or that Hugo at least allow for single line comments at the start of embedded files?

**Comment by bep** [comment]
The "is plain HTML detector" is probably a little ... crude, but it is there to separate HTML with front matter and those that do not, and it is a common pattern to wrap front matter in a comment.

In earlier Hugo version we treated all HTML files without front matter as Go templates, which had a lot of issues that I guess most people were happy to get rid off.

I would welcome a simple fix, but I think something like #7088 is a little too much.
