### ISSUE TITLE
hugo version isn't accurate on each release

### ISSUE THREAD

**Issue by jfmatth** [gohugoio/hugo#7094]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.69.0-DEV linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

The problem i have is even though i checkout a different branch / release, the ```hugo version``` returns the same thing, is that right?

**Comment by bep** [comment]
>is that right?

No, which suggest you have an issue with your build/path setup. I suggest you raise a question here: https://discourse.gohugo.io/
