### ISSUE TITLE
`replace` and `replaceRE` don't work in shortcode anymore

### ISSUE THREAD

**Issue by Jos512** [gohugoio/hugo#7095]
As [reported on the forum](https://discourse.gohugo.io/t/replace-tableofcontents-id-in-rendered-toc/24222) and confirmed there by another user, string functions like `replace` and `replaceRE` don't work in shortcodes anymore.

This _page_ template code works:

~~~
{{ replace .TableOfContents "TableOfContents" "toc" | safeHTML }}
~~~

Creating the _shortcode_ equivalent doesn't perform the replacement operation:

~~~
{{ replace .Page.TableOfContents "TableOfContents" "toc" | safeHTML }}
~~~

The issue happens when I call the shortcode with `{{<toc>}}` and with `{{%toc%}}`.

### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.68.3/extended windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.14.1"
</pre>

### Does this issue reproduce with the latest release?
Yes.

### Since when does the issue happen?
The problem started with [Hugo 0.55](https://github.com/gohugoio/hugo/releases/tag/v0.55.0). The issue wasn't present with the version before that, [Hugo 0.54](https://github.com/gohugoio/hugo/releases/tag/v0.54.0).

### Is there an example site to replicate?
Yes, I uploaded an example site here: https://github.com/Jos512/hugo-shortcode-issue

That repository has `example-post.md` call the `toc.html` shortcode with `{{<>}}` and `{{%%}}` format. The content of that shortcode is:

~~~
{{ replace .Page.TableOfContents "TableOfContents" "toc" }}
~~~

### How does the problem happen with the example site?
On Hugo 0.54, both `{{<toc>}}` and `{{%toc%}}` output:

~~~html
<nav id="toc"> <ul> <li> <ul> <li><a href="#heading-1">Heading 1</a></li> <li><a href="#heading-2">Heading 2</a></li> </ul></li> </ul> </nav> 
~~~

This is correct; `TableOfContents` is replaced by `toc`.

On Hugo 0.55, both `{{<toc>}}` and `{{%toc%}}` output:

~~~html
<nav id="TableOfContents">
<ul>
<li>
<ul>
<li><a href="#heading-1">Heading 1</a></li>
<li><a href="#heading-2">Heading 2</a></li>
</ul></li>
</ul>
</nav>
~~~

This is incorrect; the `replace` function doesn't replace "TableOfContents" with "toc" anymore.

### What Hugo versions did you use for this test?
~~~plain
Hugo Static Site Generator v0.55.0/extended windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.12.2"
~~~

~~~plain
Hugo Static Site Generator v0.54.0/extended windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.11.5"
~~~

**Comment by bep** [comment]
Yes, that does not work and It will not be fixed. The TableOfContents is not available when we render the shortcode (think about it).

**Comment by bep** [comment]
@satotake and note that adding this as a "data container" would have the same problem. The shortcode  is part of the ToC, so you get a "chicken and egg" problem. Please tell me how, but open a new issue.
