### ISSUE TITLE
IsAncestor with Similar Section Names

### ISSUE THREAD

**Issue by gary-kim** [gohugoio/hugo#7096]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.69.0-DEV/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes. I've tried it on the latest release and the current master.

Downstream issue: matcornic/hugo-theme-learn#388

If you have two sections in which one section is a prefix of another section, `.IsAncestor` will say that the longer section is also an ancestor of the shorter prefix section.

So in my case, `lighting` is considered an ancestor of `lighting-design` even though they are different sections altogether.

https://github.com/matcornic/hugo-theme-learn/blob/b5c759a3c7ba7a7303a538f7d1982ec578812684/layouts/partials/menu.html#L99-L106

Seems to be a result of `.IsAncestor` checking by using `strings.HasPrefix`.
https://github.com/gohugoio/hugo/blob/b6e097cfe65ecd1d47c805969082e6805563612b/hugolib/page__tree.go#L52-L54

**Comment by bep** [comment]
Yea, that's a bug.   I guess something like:

```go
return strings.HasPrefix(ref2.key, ref1.key + "/"), nil 
```

Should fix it.
