### ISSUE TITLE
`hugo server` applies syntax highlighting but `hugo --gc --minify` does not

### ISSUE THREAD

**Issue by bobbywlindsey** [gohugoio/hugo#7100]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.68.3
</pre>

### Does this issue reproduce with the latest release?

Yes

### The issue

`hugo server` applies syntax highlighting but `hugo --gc --minify` does not. As an example, `hugo server` produces this:

![image](https://user-images.githubusercontent.com/14844961/77722330-758d8d80-6fbb-11ea-8cad-1a968314219a.png)

While `hugo --gc --minify` produces this:

![image](https://user-images.githubusercontent.com/14844961/77722347-85a56d00-6fbb-11ea-9c20-4ddd9df64d74.png)

**Comment by pamubay** [comment]
Are you sure it's not CSS Problem?

i tried both `noClasses = true` and `noClasses = false`, both are works. The code highlighted correctly.
```
Hugo Static Site Generator v0.69.0-DEV-4A39564E/extended linux/amd64 BuildDate: 2020-03-27T09:47:52+0700
```
Please use [Forum](https://discourse.gohugo.io/) for troubleshooting.

**Comment by bobbywlindsey** [comment]
Yeah I don't think it's a CSS problem. The underlying html structure between the two are different, as if Hugo is not recognizing the code as syntax.

I'll see what I can find in the Forums as well.

**Comment by bobbywlindsey** [comment]
I think this problem is actually a problem with Netlify.
