### ISSUE TITLE
dpkg remove

### ISSUE THREAD

**Issue by g0rbe** [gohugoio/hugo#7102]
<pre>
68.3
</pre>

### Does this issue reproduce with the latest release?

Yes

Installed hugo from .deb package. Works good.
`dpkg -i hugo_0.68.3_Linux-64bit.deb`

I found out that i need hugo extended, removing...

`apt remove hugo` or `dpkg -r hugo`

While removing hugo:

```
dpkg: warning: while removing hugo, directory '/usr/local' not empty so not removed
```

Removing hugo wants to remove `/usr/local`.
And dont know what is removed too.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by cshoredaniel** [comment]
This should be reopened.  I forgot to report it but I can confirm it is 
a bug in the .deb packaging not user error.

I don't use the .deb any more which is why I forgot.

**Comment by cshoredaniel** [comment]
For what it's worth I've made the same mistake in my own .deb packages.
