### ISSUE TITLE
All content being read as draft pages

### ISSUE THREAD

**Issue by arlyon** [gohugoio/hugo#7108]
**Hugo Version (at time of writing):** v68.3

**edit**: seems like the cause was the `_index.md` with draft set to true. I see the value in temporarily disabling an entire folder, but maybe a warning would be useful? I'm not sure why it was set to be a draft previously, but it used to not have an effect.

My content is suddenly only being rendered with drafts enabled:

```
$ hugo
Building sites … 
                   | EN  
-------------------+-----
  Pages            |  2  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 16  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 65 ms
```

```
$ hugo -D
Building sites …
                   | EN  
-------------------+-----
  Pages            | 67  
  Paginator pages  |  2  
  Non-page files   |  0  
  Static files     | 16  
  Processed images |  0  
  Aliases          | 26  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 172 ms
```

```
$ hugo list all
path,slug,title,date,expiryDate,publishDate,draft,permalink
content/articles/ironbuild.md,,Ironbuild,2019-12-17T23:04:01Z,0001-01-01T00:00:00Z,2019-12-17T23:04:01Z,false,https://blog.arlyon.dev/articles/ironbuild/

... etc
```

```
$ hugo list drafts
content/articles/integrating-a-scripting-engine-into-unity.md
content/syntax.md
content/_index.md
```

Surely if all my content were being detected as drafts, then `hugo list` would list them all? Not sure when the issue started appearing; my other hugo project builds fine even with the same version.

- working repo: https://github.com/arlyon/resume
- broken repo: https://github.com/arlyon/blog

**Comment by pamubay** [comment]
Yes, it's from this issue fix https://github.com/gohugoio/hugo/issues/6927#issuecomment-589977872

**Comment by Jos512** [comment]
> seems like the cause was the _index.md with draft set to true. I see the value in temporarily disabling an entire folder, but maybe a warning would be useful? I'm not sure why it was set to be a draft previously, but it used to not have an effect.

This feature was added in [Hugo 0.65](https://github.com/gohugoio/hugo/releases/tag/v0.65.0).

Before 0.65, a section page would render even in all posts in that section were draft (or scheduled for the future). That was not ideal either. In your case, it would mean that the `/articles/` page did publish, but was empty when posts in `/content/articles/*.md` were all draft.

I agree that a warning or notification would have helped in this situation, but that's in hindsight and unfortunately not something we can change anymore now (1.5 month after Hugo 0.65).

**Comment by arlyon** [comment]
Happy to close, I'm sure this issue is helpful to those who find it on google anyways, and there is no clear solution.
