### ISSUE TITLE
AsciiDoc -- Hugo Server Breaks on Trivial Parser WARNINGs.

### ISSUE THREAD

**Issue by madranet** [gohugoio/hugo#7109]
```
MacOSX 10,14,xx
Hugo: v0.63.1/extended darwin/amd64 BuildDate: unknown
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
This is a pretty much a duplicate of a post [I've made on the Hugo Discussion Forum](https://discourse.gohugo.io/t/asciidoc-hugo-server-shouldnt-break-on-warnings-only-errors/24335).  Not sure where it'll gain the most eyeballs.

----

Having successfully converted all pages of my existing Hugo site from `markdown` to `asciidoc`; now, whenever I build the site, Hugo spits out an unending screed of `section title out of sequence` errors:

```
<snip>

ERROR 2020/03/30 11:23:02 2013-03-15-ios-prototyping-prerequisites.adoc: asciidoctor: WARNING: <stdin>: line 52: section title out of sequence: expected level 1, got level 3
ERROR 2020/03/30 11:23:02 2013-03-15-ios-prototyping-prerequisites.adoc: asciidoctor: WARNING: <stdin>: line 77: section title out of sequence: expected level 1, got level 3
ERROR 2020/03/30 11:23:03 2015-02-27-samsung-android-memory-error.adoc: asciidoctor: WARNING: <stdin>: line 48: section title out of sequence: expected level 1, got level 2
ERROR 2020/03/30 11:23:06 2012-05-12-getting-stuff-into-and-out-of-your-ios-devices.adoc: asciidoctor: WARNING: <stdin>: line 7: section title out of sequence: expected level 1, got level 3
ERROR 2020/03/30 11:23:06 2012-05-12-getting-stuff-into-and-out-of-your-ios-devices.adoc: asciidoctor: WARNING: <stdin>: line 17: section title out of sequence: expected level 1, got level 3
ERROR 2020/03/30 11:23:06 2012-05-12-getting-stuff-into-and-out-of-your-ios-devices.adoc: asciidoctor: WARNING: <stdin>: line 27: section title out of sequence: expected level 1, got level 3
ERROR 2020/03/30 11:23:06 2012-05-12-getting-stuff-into-and-out-of-your-ios-devices.adoc: asciidoctor: WARNING: <stdin>: line 35: section title out of sequence: expected level 1, got level 3

<snip>
```

I'm not certain the exact reason  `asciidoctor` throws up these `WARNING`s [it can get quite pernickerty at times] But that's besdie the point. The problem is that [as you can see from the terminal output above]  whilst `asciidoctor` is outputting `WARNING`s [which, in this case are about completely trivial issues], Hugo is interpreting them as `ERROR`s and thus  reporting that the site build failed and therefore not running the local server at the end of the build process.

```
Error: Error building site: logged XXX error(s)
```

However, in actuality, the `asciidoc` parser has actually processed all the content files successfully, since there were only non-critical warnings generated.  I can see the pages created in my `public` folder and, looking at the source code, they are perfectly fine. 

SUGGESTED SOLUTION:

* Hugo needs to distinguish between a `WARNING` coming back from the `asciidoc` parser and an `ERROR` and not to abandon site building on `WARNING`s only

or

* Provide a way of passing config options to `asciidoctor`, so we can configure it not to spew out non-vital warnings, so Hugo doesn't think parsing has failed.

Incidentally: whilst I can workaround this problem by building the site and then spinning up a Python webserver from the command line, to test it, this is far from ideal. 

Firstly because it makes building the preview site a 2-step and non-automatic process,  but mainly because Hugo takes an age to build the site because of handling these hundreds of unimportant `WARNING`s that the `aciidoctor` parser is returning. 

My build time has gone up from a few seconds [and instantly on subsequently editing a single file] to several minutes which, of course, has to be repeated for every single edit, as Hugo's server is not running at the end of the process. Therefore the entire site needs painfully s-l-o-w-l-y rebuilding for every single change.

**Comment by madranet** [comment]
Just for the record, I ran `time` on `hugo server` today in my c.340 page blog:

```
hugo server --renderToDisk  125.03s user 26.27s system 327% cpu 46.220 total
```

Up from a few seconds to over two minutes because of the constant `asciidoc` Warnings/Errors --and then a few seconds more, after that to fire up a Python server so I can actually preview the site!

**Comment by boydkelly** [comment]
Asciidoctor has a command line option for this:
--failure-level LEVEL        set minimum logging level that triggers non-zero exit code: [WARN, ERROR, INFO] (default: FATAL)

I tried the following in my config but it didn't work   :(
Shouldn't hugo implement this?

```
markup:    
   asciidocext:    
      backend: html5    
      workingfoldercurrent: true  
      failure-level: FATAL  
      includedir: ../include/
```
