### ISSUE TITLE
Add feature to humanize function for floats: round them.

### ISSUE THREAD

**Issue by jasikpark** [gohugoio/hugo#7110]
Currently I'm using printf for displaying my image metadata,

```go-html-template
{{ with $src.Exif }}
  <ul>
      {{ with .Tags.ApertureValue }}<li>Aperture: {{ (printf "%.2f" .) }}</li>{{ end }}
      {{ with .Tags.BrightnessValue }}<li>Brightness: {{ (printf "%.2f" .) }}</li>{{ end }}
  </ul>
   {{ end }}
```

```go-html-template
{{ with $src.Exif }}
  <ul>
      {{ with .Tags.ApertureValue }}<li>Aperture: {{ (humanize .) }}</li>{{ end }}
      {{ with .Tags.BrightnessValue }}<li>Brightness: {{ (humanize .) }}</li>{{ end }}
  </ul>
   {{ end }}
```

**Comment by Jos512** [comment]
I can see that rounding floats might be a way to 'humanize' text, especially when the value is something like `1.00000000001`. And perhaps two decimal digits are a good way to 'standardise' values.

But what about the decimal point? Some countries use a dot, others a comma ([overview of those countries](https://en.wikipedia.org/wiki/Decimal_separator#Arabic_numerals)). So while `12.34` might be a humanised version of 12.343231 for person A, it might be wrong for person B.

Luckily we already have [the `lang.NumFmt` function](https://gohugo.io/functions/numfmt/) for those use cases. And in other cases [the `math.Round` function](https://gohugo.io/functions/math/) works well.

**Comment by jasikpark** [comment]
Ok, cool -- I could not find lang.NumFmt for my life -- maybe something in the documentation adding some keywords about formatting floats could be added so it shows up in search?
