### ISSUE TITLE
toCSS: commented out @import statements appear in CSS output

### ISSUE THREAD

**Issue by backmes** [gohugoio/hugo#7111]
When SCSS files contain lines with commented out `@import` statements, theses import statements appear (as real statements, not within a comment!) in the generated CSS files.

With Hugo version 0.67 this still worked as expected. 

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.68.3-157669A0/extended linux/amd64 BuildDate: 2020-03-24T12:13:38Z
</pre>

### Does this issue reproduce with the latest release?

yes.

**Comment by backmes** [comment]
I created an example to demonstrate this at  https://github.com/backmes/website-hugo-7111

**Comment by bep** [comment]
LibSASS doesn't really support import of regular CSS files, which is why I created a (temporary) workaround for these some time ago. I'm not going to spend time on improving that fix, as I expect this will be fixed upstream.

In the meantime, I suggest you remove the import statements that you do not want/neex.

**Comment by backmes** [comment]
> LibSASS doesn't really support import of regular CSS files, which is why I created a (temporary) workaround for these some time ago. I'm not going to spend time on improving that fix, as I expect this will be fixed upstream.

I just was surprised that something in a comment would appear as actual statement in the output, therefore I thought this was a "real" bug, not the result of some workaround...

> In the meantime, I suggest you remove the import statements that you do not want/neex.
I already did.
