### ISSUE TITLE
[Goldmark] Typographer does not replace apostrophes next to letters with accents (such as è)

### ISSUE THREAD

**Issue by loup-brun** [gohugoio/hugo#7113]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 
Hugo Static Site Generator v0.68.3/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

**Yes.**
I was having this issue with older versions of Hugo (such as `v0.65.0`).
Updating to the latest (`v0.68.3`) did not solve the issue.

### The problem

I appreciate using the `typographer` extensoin for rendering markdown using Goldmark.
The extension usually works well, **except when apostrophes are next to characters with an accent, such as an ‘e’ with accent aigu ‘é’**.

With accent aigu ‘é’, apostrophe is not replaced:
![With accent aigu ‘é’, apostrophe is not replaced](https://user-images.githubusercontent.com/9596476/78077583-9caadd00-7376-11ea-9629-1f9214f4d651.png)

With no accent, apostrophe correctly replaced:
![With no accent, apostrophe correctly replaced](https://user-images.githubusercontent.com/9596476/78077617-a9c7cc00-7376-11ea-9ba3-bd88439128f7.png)

I know this is an issue related to Goldmark, but the maintainer asks to open an issue here first (since Goldmark “is not dedicated to Hugo”).

**Comment by bep** [comment]
Thanks for the report. This looks like it could be an issue with Goldmark. Could you create an issue at https://github.com/yuin/goldmark/issues and link back to this issue so we could track it?

**Comment by loup-brun** [comment]
Issue has been fixed upstream in the Goldmark repo, see here:

https://github.com/yuin/goldmark/issues/121#event-3226543144

Thanks!

**Comment by loup-brun** [comment]
Thank you!
