### ISSUE TITLE
Markup render hooks shouldn't add extra whitespace around its rendered HTML tags

### ISSUE THREAD

**Issue by marcellmars** [gohugoio/hugo#7114]
I have few custom links which I added into _render-image.html_ and after they get rendered there is always extra new lines and spaces around the HTML tags the hooks render. I hoped that **hugo --minify** will take care of that but it doesn't. I tried to trim those inside of the _render-image.html_ by adding dashes into **{{ }}** - no luck.

The main annoyance in my case is that the rendered HTML (<a href...) adds a space before comma in a sentence which many sees as a very sloppy writing practice.

I use **v0.68.3/extended**  version of Hugo.

**Comment by bep** [comment]
Short answer is: We don't. You need to check your templates (which is the long story, but please use https://discourse.gohugo.io/ for that).
