### ISSUE TITLE
Use HTML tag blacklist instead of no raw html for Goldmark

### ISSUE THREAD

**Issue by geekman** [gohugoio/hugo#7115]
I understand the need for not allowing arbitrary HTML in Markdown content for security, but Markdown is quite limiting in certain aspects. For example, I resort to using `<sub>` and `<sup>` for subscript and superscript because it seems that these can't be unambiguously parsed by CommonMark in order to be included in the specs. I also commonly see the `<details>` tag being used to hide verbose information in some READMEs. I'm quite sure there's more of these cases.

GitHub allows raw HTML in repository READMEs and I would imagine they have the same security concerns as well. It seems that they have thought about this and opted to use a blacklist of HTML tags instead: <https://github.github.com/gfm/#disallowed-raw-html-extension->. From the link, the blacklisted tags are:

```
<title>
<textarea>
<style>
<xmp>
<iframe>
<noembed>
<noframes>
<script>
<plaintext>
```

Would this be a good compromise for security, but still allow flexibility in Markdown content?

**Comment by bep** [comment]
>Would this be a good compromise for security,

Not really. That said, I have some plans (and an issue) to add Bluemonday (a Go HTML sanitizer), which would be an excellent option.

**Comment by geekman** [comment]
Awesome. Integrating a proper sanitizer is definitely better than a blacklist.

**Comment by maelle** [comment]
For others browsing, #6530 🙂
