### ISSUE TITLE
Hugo Qucikstart dont work 

### ISSUE THREAD

**Issue by mattiashem** [gohugoio/hugo#7122]
### What version of Hugo are you using (`hugo version`)?

<pre>
FROM golang

RUN mkdir /root/src
WORKDIR /root/src
RUN git clone https://github.com/gohugoio/hugo.git
WORKDIR /root/src/hugo
RUN go install --tags extended
WORKDIR /src/

</pre>

### Does this issue reproduce with the latest release?
Yess cloned the latest git 

<pre>
root@2b21e24c1a12:/src# hugo new site quickstart
Congratulations! Your new Hugo site is created in /src/quickstart.

Just a few more steps and you're ready to go:

1. Download a theme into the same-named folder.
   Choose a theme from https://themes.gohugo.io/ or
   create your own with the "hugo new theme <THEMENAME>" command.
2. Perhaps you want to add some content. You can add single files
   with "hugo new <SECTIONNAME>/<FILENAME>.<FORMAT>".
3. Start the built-in live server via "hugo server".

Visit https://gohugo.io/ for quickstart guide and full documentation.
</pre>

<pre>
root@2b21e24c1a12:/src# cd quickstart/
</pre>

<pre>
root@2b21e24c1a12:/src/quickstart# git init
Initialized empty Git repository in /src/quickstart/.git/
root@2b21e24c1a12:/src/quickstart# git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
Cloning into '/src/quickstart/themes/ananke'...
remote: Enumerating objects: 1613, done.
remote: Total 1613 (delta 0), reused 0 (delta 0), pack-reused 1613
Receiving objects: 100% (1613/1613), 4.22 MiB | 6.83 MiB/s, done.
Resolving deltas: 100% (892/892), done.
</pre>

<pre>
root@2b21e24c1a12:/src/quickstart# echo 'theme = "ananke"' >> config.toml
</pre>

<pre>
root@2b21e24c1a12:/src/quickstart# hugo new posts/my-first-post.md
Error: module "mytheme" not found; either add it as a Hugo Module or store it in "/src/quickstart/themes".: module does not exist
</pre>

Tested it 2 weeks ago and then today again. Build the docker image to get the latest Hugo, Then run the commands from the quickstart.

**Comment by bep** [comment]
Please post documentation related issues here: https://github.com/gohugoio/hugoDocs/issues

**Comment by mattiashem** [comment]
But are the docs wrong ore the app ?

**Comment by arcooke** [comment]
I'm having the same issue on Solus.  Ran through the process twice with the same results.

$ hugo version
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T19:59:31Z

```
me@ac-desktop ~/Source/ramblings $ git init
Initialized empty Git repository in /home/me/Source/ramblings/.git/
me@ac-desktop ~/Source/ramblings $ git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
Cloning into '/home/me/Source/ramblings/themes/ananke'...
remote: Enumerating objects: 1613, done.
remote: Total 1613 (delta 0), reused 0 (delta 0), pack-reused 1613
Receiving objects: 100% (1613/1613), 4.22 MiB | 12.75 MiB/s, done.
Resolving deltas: 100% (892/892), done.
me@ac-desktop ~/Source/ramblings $ hugo new posts/first.md
Error: module "gohugo-theme-ananke" not found; either add it as a Hugo Module or store it in "/home/me".: module does not exist
me@ac-desktop ~/Source/ramblings $ hugo new posts/first.md
Error: module "gohugo-theme-ananke" not found; either add it as a Hugo Module or store it in "/home/me/Source/ramblings/themes".: module does not exist
me@ac-desktop ~/Source/ramblings $ 
```
