### ISSUE TITLE
Allow to set page anchors as target for aliases

### ISSUE THREAD

**Issue by fri-sch** [gohugoio/hugo#7126]
Say I have a page with a section for projects at `/projects` and single pages for each of `/projects/project1`, `/projects/project2`, etc.
Now I also have a home page at `/index.html`, that contains a list of projects generated from the `projects` section. This list has an anchor and can be accessed via `/#projects`.

I would like to be able to redirect from the blank projects section index at `/projects` to the list anchor on the home page at `/#projects`. An alias set in `_index.md` seems like the proper way to do this, but this will always target the home page and not the anchor inside the home page.

**Comment by fri-sch** [comment]
Basically I'm thinking of something as described here: https://discourse.gohugo.io/t/alias-redirect-to-anchors/2764/9.

**Comment by cdupont** [comment]
I think this would be a nice feature.
I often have multiple pages merged into one, so having aliases targeting anchors would be nice.
In term of implementation, how do you think it look like?
For example:
```
aliases:
   - /oldPage#oldAnchor #newAnchor
```
Or more explicitly:
```
aliases:
   - old-location: /oldPage#oldAnchor
     new-location: #newAnchor
```

**Comment by fri-sch** [comment]
I don't think we to reference the source and the target of the alias as it is defined in the _index.md of the source location, just like other aliases. So we just need to handle the anchor targets. I have no idea what is needed to implement this, though.

```
aliases:
  - /test#projects
  - /test#about
```

**Comment by prdsoftware** [comment]
+1  This would be a great feature to have.  For a documentation site, we often consolidate multiple pages into just one, and use the headings/anchors for the different sections.  As we re-structure the documentation, this type of feature would be very handy.
