### ISSUE TITLE
Redirect in _index.md -> plain HTML documents not supported

### ISSUE THREAD

**Issue by m33s33ks** [gohugoio/hugo#7135]
Hello
A recent Update in Hugo broke a simple redirect I had in my __index.md.
Now I tried to find out what the hugo way of doing this would be but had no luck.

I want the starting point of my application to be a directory, in this case /posts/.
But afaik the entry point will always be _index.md.
How can I implement the functionality I had with this version of hugo?

Here is what was in my _index.md

`<meta http-equiv="refresh" content="0; url=/posts"/>`

Thanks for your help

**Comment by sams96** [comment]
Have you tried renaming `_index.md` to `_index.html`?

**Comment by m33s33ks** [comment]
I just tried that and oddly enough, the error is gone but it's also not redirecting.

**Comment by cshoredaniel** [comment]
I've noticed Firefox at least often doesn't redirect nowadays. Sometimes 
I get a message to allow, but not always.  Suspect it's security thing 
that's buggy in that case.  So it might be a browser issue.

**Comment by m33s33ks** [comment]
> I've noticed Firefox at least often doesn't redirect nowadays. Sometimes I get a message to allow, but not always.  Suspect it's security thing that's buggy in that case.  So it might be a browser issue.

I tested it in multiple browsers, it's not working in any of them.
Thanks for the heads up though!

**Comment by m33s33ks** [comment]
Alright I found the solution to the problem in a new issues post: https://github.com/gohugoio/hugo/issues/7296

If I insert 
---
---
before 
<meta http-equiv="refresh" content="0; url=/posts"/>

in _index.md the behaviour is as it used to be and no error is thrown.
Cheers
