### ISSUE TITLE
Check cache handling on Netlify

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7136]
I have a site with many images with a build time that suggests something fishy. Committing resources/_gen/images fixes it, but that should not be needed.

**Comment by jpcaruana** [comment]
My solution is to force remove `_gen` folders before runnning hugo, and build is ok on netlify

In my `netlify.toml` file:

    command = "find . -name _gen -exec rm -rf {} + ; hugo --gc --minify"

Hope this helps

**Comment by bep** [comment]
That isn't the problem I'm trying to solve here.

**Comment by jpcaruana** [comment]
Too bad :(

**Comment by hennessyevan** [comment]
Maybe a netlify build plugin could be useful?
