### ISSUE TITLE
hugo site without theme will return empty page

### ISSUE THREAD

**Issue by haobug** [gohugoio/hugo#7137]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.68.3-157669A0 linux/amd64 BuildDate: 2020-03-24T12:05:34
</pre>

### Does this issue reproduce with the latest release?
yes

steps to reproduce issue.
```
git clone https://github.com/cdlug/cdlug.github.io
cd cdlug.github.io
hugo server --bind 0.0.0.0 
```
start another terminal window
```
wget localhost:1313
cat index.html
```
there will be nothing in index.html

**Comment by jmooring** [comment]
The `config.toml` file sets `theme = "even"`, but `themes/even` is an empty directory. This site is clearly misconfigured, and Hugo emits plenty of warnings to advise you of the problem:  

> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2020/05/08 08:47:03 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

**Comment by nekr0z** [comment]
The repository lacks a template that would satisfy [temlpate lookup rules](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-home-page) for homepage, hence no homepage is generated.

In other words, Hugo works as expected and documented here.

It can be argued that it would be sensible for Hugo to provide basic default templates for the default pages (at least for `single` and `list`) the same way it is done for RSS, but Hugo doesn't provide those (yet?).

**Comment by haobug** [comment]
Since it’s misconfigured and there is no built in fallback DEFUALT theme please help to close this issue.

**Comment by haobug** [comment]
I have checked with the boy submitted the code. His initial idea which caused the blank error is to refer the theme as an external standalone dependency instead of copy it into our own repository to reduce the codebase size and keep up to date with theme upstream. Therefore He configured it as git submodule. 

> It can be argued that it would be sensible for Hugo to provide basic default templates for the default pages (at least for single and list) 

agreen,
can Hugo provides a kind of built-in fallback theme or just gives an _visible_ error message in the generated HTML page content.

**Comment by davidsneighbour** [comment]
no.
