### ISSUE TITLE
scss: Slow building Foundation

### ISSUE THREAD

**Issue by haberdashPI** [gohugoio/hugo#7138]
### What version of Hugo are you using (`hugo version`)? 

Hugo Static Site Generator v0.68.3/extended darwin/amd64 BuildDate: unknown

### Does this issue reproduce with the latest release?

To my knowledge 0.68.3 is the latest release

## Slow performance

When including the [Foundation](https://get.foundation/sites/docs/sass.html) styles into my project using the built in support for scss in hugo, the performance drops dramatically as I uncomment the `@include` statements shown below. On `@include foundation-button-group;` hugo hangs for as long as 2 minutes (I have not run past 2 minutes).

I am using version 6.6.2 of Foundation.

```scss
@import 'foundation';

// Global styles
@include foundation-global-styles;
@include foundation-forms;
@include foundation-typography;

// Grids (choose one)
@include foundation-xy-grid-classes;
// @include foundation-grid;
// @include foundation-flex-grid;

// Generic components
@include foundation-button;
@include foundation-button-group;
@include foundation-close-button;
@include foundation-label;
@include foundation-progress-bar;
@include foundation-slider;
@include foundation-switch;
@include foundation-table;
// Basic components
@include foundation-badge;
@include foundation-breadcrumbs;
@include foundation-callout;
@include foundation-card;
@include foundation-dropdown;
@include foundation-pagination;
@include foundation-tooltip;

// Containers
@include foundation-accordion;
@include foundation-media-object;
@include foundation-orbit;
@include foundation-responsive-embed;
@include foundation-tabs;
@include foundation-thumbnail;
// Menu-based containers
@include foundation-menu;
@include foundation-menu-icon;
@include foundation-accordion-menu;
@include foundation-drilldown-menu;
@include foundation-dropdown-menu;

// Layout components
@include foundation-off-canvas;
@include foundation-reveal;
@include foundation-sticky;
@include foundation-title-bar;
@include foundation-top-bar;

// Helpers
@include foundation-float-classes;
// @include foundation-flex-classes;
@include foundation-visibility-classes;
// @include foundation-prototype-classes;
```

**Comment by bep** [comment]
I assume this is an upstream issue: https://github.com/sass/libsass

Hugo runs: https://github.com/sass/libsass/releases/tag/3.6.3

You may get speedier response reporting the issue upstream.

**Comment by bep** [comment]
What you can try is to try Hugo 0.64 and see if that speeds it up.

**Comment by bep** [comment]
Just to be clear: 0.65 was the time where we did an upgrade of LibSASS -- I have seen some reports on their tracker about some performance issues, but have not experienced it with any of the frameworks that I have thrown at it (Bootstrap, Bulma).

**Comment by haberdashPI** [comment]
Yes, using Hugo 0.64 seems to speed things up a bit; and if I uncomment out `foundation-button-group` hugo no longer hangs.

**Comment by UtkarshVerma** [comment]
I can confirm this on Hugo v0.74.3. For me, however, the build doesn't even complete. I waited for 5 minutes and the build was still going on, which is weird because my machine has 8GB RAM and a AMD Ryzen 5.

I hope this is fixed upsteam soon, because I really want to try out the new JS bundling and other features of Hugo. I'm currently stuck on v0.64.1. :disappointed:

**Comment by UtkarshVerma** [comment]
I did a preliminary test using Hugo v0.75 and things seem to work now :)

> Some warnings are displayed for SCSS like:
>```
>DEPRECATION WARNING on line 135 of /home/subaru/GitHub/bitbanged.com/themes/hugo-yoru/assets/scss/foundation/util/_color.scss:
>!global assignments won't be able to declare new variables in future versions.
>Consider adding `$alert-color: null` at the top level.
>```
> But I think I the bug is probably fixed.

**Comment by bep** [comment]
Yes, we pulled in a new version of LibSASS. Thanks for the feedback.
