### ISSUE TITLE
`unsafe: true` does not work - html is always omitted

### ISSUE THREAD

**Issue by iaktern** [gohugoio/hugo#7139]
Hi,

it seems that `unsafe: true` for goldmark does not work. 

I've loaded the newest version, created the project of the quick start tutorial and added `unsafe: true` like described in the [docu](https://gohugo.io/getting-started/configuration-markup/#goldmark) - but every  HTML is still omitted.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.68.3-157669A0 linux/amd64 BuildDate: 2020-03-24T12:05:34Z
</pre>

### Does this issue reproduce with the latest release?
yes 

Just a short remark because I struggled with this breaking change after the update to version >0.60: I think it's really unusual to disable HTML by default. And, because hugo uses such a feature-restricted markdown parser, it would even be more user-friendly to allow HTML.  E.g. I don't know of any better method for arbitrary (not header-related) in-page linking than introducing a `<span id="">` somewhere in the text.  And I have some other use cases that require HTML. (If hugo's goal is to not write any HTML inside a Markdown file, then maybe a more advanced Markdown parser, which e.g. supports [MultiMarkdown](https://rawgit.com/fletcher/human-markdown-reference/master/index.html#simple_table), would be a better solution.)

**Comment by bep** [comment]
>it seems that unsafe: true for goldmark does not work.

It does.

**Comment by iaktern** [comment]
Okay, now I'm confused. Following the [Quick Start](https://gohugo.io/getting-started/quick-start/), here is exactly what I did:

```
1. hugo new site 200407_TestUnsafe
2. cd 200407_TestUnsafe
3. git init
4. git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
5. echo 'theme = "ananke"' >> config.toml
6. hugo new posts/my-first-post.md
```

Then I changed `my-first-post.md` to the following:
```
---
title: "My First Post"
date: 2020-04-07T09:23:47+02:00
draft: false
markup:
  goldmark:
    renderer:
      unsafe: true
---

<!-- just a comment -->

Hello World

<div>2nd Hello from inside HTML</div>
```

the final  `hugo` command creates a HTML file with this content:
```
...
    <div class="..."><!-- raw HTML omitted -->
<p>Hello World</p>
<!-- raw HTML omitted -->
<ul ...
```

Is there something I did wrong?

**Comment by jmooring** [comment]
Put this in config.toml, _not_ in your markdown files:

```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```
See <https://gohugo.io/news/0.60.0-relnotes/>.

**Comment by iaktern** [comment]
Great, that works - thank you!

Sorry, I can't really read that in the release notes or documentation. (There is just a very short "_config_.yaml|toml|json" indicating this.) What brought me to this thinking is this part in the [documentation](https://gohugo.io/content-management/formats/#list-of-content-formats): 

> "The markup identifier is fetched from either the markup variable in front matter or from the file extension. For markup-related configuration, see Configure Markup."

Since it directly links the [Configure Markup docu](https://gohugo.io/getting-started/configuration-markup/) with all possible configurations, I thought it is also possible to put it into the front matter. 

Maybe it would be helpful to clearly state that in the documentation. Thanks
