### ISSUE TITLE
Nested lists output <pre><code> instead of lists

### ISSUE THREAD

**Issue by sprajagopal** [gohugoio/hugo#7142]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.68.0-DEV linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
This is the latest version.

Nested lists such as this:
<pre>
###### Level 6 {#level-6}
-    Level 7
    -    Level 8
        -    Level 9
            -    Level 10
</pre>
produce the following html:

```
<article class="article" class="blog-post">      
<h2 id="level-2">Level 2</h2>
<h3 id="level-3">Level 3</h3>
<h4 id="level-4">Level 4</h4>
<h5 id="level-5">Level 5</h5>
<h6 id="level-6">Level 6</h6>
<ul>
<li>Level 7</li>
</ul>
<pre><code>-    Level 8
    -    Level 9
        -    Level 10
</code></pre>      
</article>
```
Expected behaviour would be the actual nesting of `<ul>` tags

**Comment by cshoredaniel** [comment]
You've used 4 spaces -- in markdown that translates as 'pre-formatted block'

It's not a bug in Hugo.  Please use the forum 
(https://discourse.gohugo.io) for support.

**Comment by bep** [comment]
I think this is in according to commonmark spec, in any case you need to bring it up on the Goldmark issue tracker.

**Comment by kaushalmodi** [comment]
Yep, I confirm that on [this commonmark dingus][1]. If anyone has any ideas to get around this limitation, let me know.

[1]: https://spec.commonmark.org/dingus/?text=%23%23%20Level%202%20%7B%23level-2%7D%0A%0A%23%23%23%20Level%203%20%7B%23level-3%7D%0A%0A%23%23%23%23%20Level%204%20%7B%23level-4%7D%0A%0A%23%23%23%23%23%20Level%205%20%7B%23level-5%7D%0A%0A%23%23%23%23%23%23%20Level%206%20%7B%23level-6%7D%0A%0A-%20%20%20%20Level%207%0A%0A%20%20%20%20-%20%20%20%20Level%208%0A%0A%20%20%20%20%20%20%20%20-%20%20%20%20Level%209%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20%20%20%20Level%2010
