### ISSUE TITLE
Add basic "post publish" resource transformation support

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7146]
E.g.:

```html
{{ $css := $css | postCSS | minify  | fingerprint  | resources.PostProcess }}
```

The above would allow `postCSS` to run "class purging" etc. and keep the fingerprint and minify behaviour intact. 

A pre-warning that purgeCSS is very slow if you run on the full /public if site is big -- so consider running it on templates only. I have some plans in this department (to create a CSS class map as part of the regular build).

**Comment by bep** [comment]
This actually works great.

![image](https://user-images.githubusercontent.com/394382/78704001-7b646680-790b-11ea-86a4-af9bfffc79b2.png)

Above is a Tailwind site with and without the purgeCSS ... 1.7MB down to 12K is not bad value.

**Comment by Rarst** [comment]
FYI noticed that release notes link to https://gohugo.io/hugo-pipes/postprocess/ but it 404s at the moment.

Soo excited to see this ship! 😊

**Comment by bep** [comment]
So, WHILE I'm doing the release, there may be 404s... The world isn't perfect.
