### ISSUE TITLE
Add support for PostProcess page encryption and password protection

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#7154]
With the introduction of the `resources.PostProcess` method in Hugo [0.69.0](https://gohugo.io/news/0.69.0-relnotes/) I would like to propose adding support for something like the [`npm-staticrypt-cli`](https://github.com/robinmoisson/staticrypt#cli) (or a similar library) so that we can encrypt and password protect HTML pages on demand, like for example by checking for the existence of a front matter parameter.

**Comment by GoGoGoDoge** [comment]
Why this is closed? I think it is a valid feature request.
