### ISSUE TITLE
hugo snap fails

### ISSUE THREAD

**Issue by aplatypus** [gohugoio/hugo#7156]
### What version of Hugo are you using (`hugo version`)?

<pre>
 $ sudo snap install hugo
hugo 0.69.0 from Hugo Authors installed
 $ hugo version
bash: /usr/bin/hugo: No such file or directory
</pre>

### Does this issue reproduce with the latest release?
As far as I know this is the latest release, stable snap channel

I have reverted to the linux apt installer, because that workes, albeit not as up to date.

```
sudo apt install hugo
```

Honestly, I'm  not sure why people like snaps.  I have yet to fone ONE that actually works satisfactorily.  This is ubuntu 19.10 and was only installed fresh a few months ago.

**Comment by maueroats** [comment]
This is likely a user error. 
Snap should be installed in /snap/bin/hugo.
Gather the following additional information:
```
$ ls -l /usr/bin/hugo
$ ls -l /snap/bin/hugo
$ echo $PATH
$ /snap/bin/hugo version
```

**Comment by aplatypus** [comment]
Hi -- Seems this failure is a snap built-in that prevents snap running with a HOME directory that isn't "`home/$USER`" -- That's 100% of the linux and unix sites I use, so we are a snap free organisation.  I can't see how something can claim a universal installer status when it does not comply with common-place set-up patterns.
