### ISSUE TITLE
Update hugo to use WithAllClasses from Chroma

### ISSUE THREAD

**Issue by acahir** [gohugoio/hugo#7167]
Modify hugo to use `WithAllClasses()` when running `hugo gen chromastyles --style=monokai > syntax.css` to [create CSS stylesheet](https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css).

[Small change in chroma](https://github.com/alecthomas/chroma/issues/346) to output all css class definitions, even if they have redundant coloring with current style. Prevents any modifications to the style from missing elements.

I believe it's only a matter of changing `WithClasses` to `WithAllClasses` [here](https://github.com/gohugoio/hugo/blob/bfb9613a14ab2d93a4474e5486d22e52a9d5e2b3/commands/genchromastyles.go#L71). 

I will try to see if I can submit a PR, but haven't actually tried compiling hugo yet (still unfamiliar with Go) so noting this here.

**Comment by bep** [comment]
>I believe it's only a matter of changing WithClasses to WithAllClasses here.

Yes, but we also need to update the Chroma version (could ask him to tag a release version?)

**Comment by acahir** [comment]
Good point. I'll add it to the chroma issue.
