### ISSUE TITLE
defaultContentLanguageInSubdir redirects without trailing slash

### ISSUE THREAD

**Issue by matteosuppo** [gohugoio/hugo#7175]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.69.0-4205844B/extended linux/amd64 BuildDate: 2020-04-10T09:16:58Z
</pre>

### Does this issue reproduce with the latest release?
Yes

### Expected behaviour
Accoding to the docs:

> defaultContentLanguageInSubdir (false)
Render the default content language in subdir, e.g. content/en/. The site root / will then redirect to /en/.

### Observed behaviour
The site root / will redirect to /en (without the trailing slash)

**Comment by matteosuppo** [comment]
I believe the culprit is this line: https://github.com/gohugoio/hugo/blob/master/hugolib/site_render.go#L388

**Comment by ernsheong** [comment]
```
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
```

Is generating all assets in `public/en` instead of `public`. Any workaround?

Hugo Static Site Generator v0.69.2/extended darwin/amd64 BuildDate: unknown
