### ISSUE TITLE
_index.md fails when starting with a shortcode

### ISSUE THREAD

**Issue by supercobra** [gohugoio/hugo#7176]
### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
</pre>

Hugo Static Site Generator v0.69.0/extended darwin/amd64 BuildDate: unknown

### Does this issue reproduce with the latest release?

Yes , same version.

How to reproduces:

Any used `_index.md` will bomb if starting with a shortcode:

$cat _index.md

    {{< youtube KIRah9Niuss >}}
    ## youtube shortcode above

Error message:
 
`Error: Error building site: "/_index.md:1:1": unmarshal failed: invalid character '{' looking for beginning of object key string`

Note: it works well if file `_index.md` starts with a regular markdown item. E.g. `# title`.

**Comment by bep** [comment]
That shortcode is mistaken for JSON front matter. Fixable, Ig

**Comment by supercobra** [comment]
Why closed?
