### ISSUE TITLE
Errors are not written to --logFile

### ISSUE THREAD

**Issue by Jumwah** [gohugoio/hugo#7177]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

Hugo Static Site Generator v0.69.0-4205844B/extended linux/amd64 BuildDate: 2020-04-10T09:16:58Z
</pre>

### Does this issue reproduce with the latest release?
Yes

### Issue
Using `--logFile` does not redirect error messages to the logfile, they're only dumped to stderr.

    $ hugo --logFile ./log.txt
    Building sites … Total in 228 ms
    Error: Error building site: "/path/to/my/markdown.md:18:12": unclosed shortcode

    $ cat log.txt
    WARN 2020/04/16 01:51:53 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
    WARN 2020/04/16 01:51:53 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

When specifying a logfile, errors should also write to that.  It's OK if they write to stderr too.

### Why is this an issue?
I'm using CloudBuild to build our site, and I need a downstream tool to report errors.  Cloudbuild only forwards on output written to a specific file.  It does not forward on stderr.

My Hugo cloudbuilder is based on distroless, and thus does not even have a shell so I can use a shell command to redirect stderr output.

**Comment by pamubay** [comment]
enable the `--verboseLog` flag?

**Comment by Jumwah** [comment]
It outputs more information, but errors still go the shell.
