### ISSUE TITLE
Warning "you need the extended version to build SCSS/SASS" not triggered when it should

### ISSUE THREAD

**Issue by mbugert** [gohugoio/hugo#7182]
When attempting to transform SCSS with the standard (non-extended) hugo version, a warning is supposed to be printed which informs users that the extended version is required to perform this action. Because of a bug, since 0.67.1 (up to including 0.69.0), this warning only appears if resource caching is disabled in the site config.

### How to reproduce
1. Install any non-extended hugo with version 0.67.1 or higher
2. Set up basic website with a theme that uses SCSS, for example [the noteworthy theme](https://github.com/kimcc/hugo-theme-noteworthy)
3. Remove `themes/noteworthy/resources` folder
4. Run `hugo server`
5. In 0.67.0 the error message was:
`Building sites … ERROR 2020/04/18 09:41:41 Transformation failed: TOCSS: failed to transform "css/main.scss" (text/x-scss): resource "scss/css/main.scss_48b060fe05b0a273d182ef83c0605941" not found in file cache. Check your Hugo installation; you need the extended version to build SCSS/SASS.`
in all later versions up to 0.69.0 the message only is:
`Building sites … ERROR 2020/04/18 09:37:04 TOCSS: failed to transform "css/main.scss" (text/x-scss): resource "scss/css/main.scss_48b060fe05b0a273d182ef83c0605941" not found in file cache`

### Cause
The problem is this line:
https://github.com/gohugoio/hugo/blob/2b28e5a9cb79af2a8d70c80036f52bcf5399b9df/resources/transform.go#L422
If resource caching is enabled, the following block with the "you need the extended version" warning is skipped, and the resulting error message is only the generic one.
I'm not a Go person myself, so I would appreciate if someone else could look into fixing this.

I went through a few frustrating hours because of this... :disappointed:

**Comment by james-richardson-zuhlke** [comment]
This bug still appears to be present. installing hugo:
```
$ sudo snap install hugo
hugo 0.74.3 from Hugo Authors installed
```

then creating site:

```
$ hugo
Total in 17 ms
Error: Error building site: TOCSS: failed to transform "scss/style.scss" (text/x-scss): resource "scss/scss/style.scss_b95b077eb505d5c0aff8055eaced30ad" not found in file cache
```

whereas using:
```
snap install hugo --channel=extended
hugo (extended/stable) 0.74.3 from Hugo Authors installed
```

works correctly.

**Comment by time4tea** [comment]
This bug still appears to be present:

installing:
```
$ sudo snap install hugo
hugo 0.74.3 from Hugo Authors installed
```

running:

```
$ hugo
Total in 17 ms
Error: Error building site: TOCSS: failed to transform "scss/style.scss" (text/x-scss): resource "scss/scss/style.scss_b95b077eb505d5c0aff8055eaced30ad" not found in file cache
```


whereas installing:

```
$ snap install hugo --channel=extended
hugo (extended/stable) 0.74.3 from Hugo Authors installed
```

works correctly

**Comment by gz-wangxm** [comment]
I has been suffering from this problem for days, because the documentation did NOT point this out. I suggest updating the documentation [here](https://gohugo.io/hugo-pipes/scss-sass/) to remind users to use the extended version.

**Comment by dharmjit** [comment]
HI, I am getting the same error on `hugo --gc --minify` with extended version as well. `hugo server -D` is working fine
```hugo version
Hugo Static Site Generator v0.80.0-792EF0F4/extended linux/amd64 BuildDate: 2020-12-31T13:46:18Z
```

**Comment by cdoss-bbox** [comment]
Does your baseURL have a subdirectory? If so you need to set `canonifyURLs` and `relativeURLs` to true

`baseurl = "//example.com/blog/"

relativeURLs=true
canonifyURLs=true`

It took me hours but I found the answer here:
https://discourse.gohugo.io/t/make-home-to-be-subdirectory/4345/7

**Comment by isoceles** [comment]
I ended up having this same error when trying to deploy to Github Pages. It turned out to be because my baseURL had a subdirectory.
If your baseURL has a subdirectory you will need to set `canonifyURLs` and `relativeURLs` to `true` in your config.toml file.

`baseurl = "//example.com/blog/";

relativeURLs=true
canonifyURLs=true`

I burned some hours on this but eventually found the above answer here:
https://discourse.gohugo.io/t/make-home-to-be-subdirectory/4345/7

**Comment by amdjml** [comment]
I am getting this same error when trying to deploy the site using github action. I keep getting the following message when the site is being bulit:

`WARNING: calling IsSet with unsupported type "ptr" (*hugolib.SiteInfo) will always return false.
Error: Error building site: TOCSS: failed to transform "scss/style.scss" (text/x-scss). Check your Hugo installation; you need the extended version to build SCSS/SASS.
Total in 61 ms
Error: Process completed with exit code 255.`

Any idea how to fix this?

**Comment by bep** [comment]
@amdjml try https://discourse.gohugo.io/

As to the bug itself, that seems to be fixed.
