### ISSUE TITLE
Open Graph and Twitter Cards titles aren't markdownified

### ISSUE THREAD

**Issue by MichaelSchmidle** [gohugoio/hugo#7185]
The internal templates ``opengraph.html`` and ``twitter_cards.html`` don't markdownify a page's title (while a page's summary does get markdownified).

I realized this after I wanted to use ``---`` in a page title to be replaced with an ``&mdash;``. The summary on the same page contains a ``'`` which properly is converted to ``&rsquo;``.

Edit: This also is the case in the RSS feed. Titles don't get markdownified there either.

### What version of Hugo are you using (`hugo version`)?
0.69.0

### Does this issue reproduce with the latest release?
Yes

**Comment by MichaelSchmidle** [comment]
FYI: Also the case with 0.69.2

**Comment by MichaelSchmidle** [comment]
Issue still persists in v0.73.0 for titles in Open Graph and Twitter Cards as well as the RSS feed.

Any reason why this ticket has been ignored so far? It's a rather minor issue, agreed. Yet I'd have expected a comment, a label or some kind of reaction after more than two months. This is the first issue I've opened in this repository so I wonder if I haven't reported the issue properly or if I overlooked something?

**Comment by MichaelSchmidle** [comment]
The issue still persists in v0.79.1.

The head's title is markdownified correctly:
``<title>Accelerate Your Website&mdash;With Your Logo · Ypertex Blog</title>``

The Open Graph and Twitter Cards aren't markdownified properly:
``<meta property="og:title" content="Accelerate Your Website---With Your Logo" />`` and ``<meta name="twitter:title" content="Accelerate Your Website---With Your Logo"/>``

The same applies for the RSS feed.

**Comment by MichaelSchmidle** [comment]
I just discovered that this issue has been fixed with Hugo 0.87.0 (or earlier). Thanks!

**Comment by jmooring** [comment]
@MichaelSchmidle

The title in the embedded templates is not "markdownified", nor should  it be.

https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html#L1
https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html#L20

Perhaps something changed in the theme you are using.
