### ISSUE TITLE
Add variable for when site was generated

### ISSUE THREAD

**Issue by rawtaz** [gohugoio/hugo#7187]
While migrating a site from Jekyll to Hugo I couldn't find an equivalent for Jekyll's `site.time` variable (as listed in [here](https://jekyllrb.com/docs/variables/#site-variables). This variable represents the time *when the site was generated*.

The closest to this I've found in Hugo is `.Site.LastChange` which however isn't the same thing (it represents the date for when content last changed, which might not be the same date as when you generate the site), and of course `.Hugo.BuildDate` which is a totally different thing (represents when the Hugo binary was built).

I therefore suggest adding a `.Site.BuildDate` or similarly named variable, that represents *the date/time when Hugo was used to actually build the site*.

Use case: For example in a copyright notice.

**Comment by divinerites** [comment]
Just do this, and you have your build date/time.

```
Copyright : {{ now.Format "2006" }}
Build on : {{ dateFormat "2 Jan 2006 15:04" now }}
```

**Comment by rawtaz** [comment]
@divinerites That totally works. Thanks! I guess there's not much point of such a variable then, but I'll leave the issue open so the maintainers can make the decision.
