### ISSUE TITLE
putting several youtube videos on one page does not work as expected

### ISSUE THREAD

**Issue by copepod** [gohugoio/hugo#7189]
The videos change order or do not display at all. Also it would be good to be able to supply a width.

Hugo Static Site Generator v0.68.3-157669A0 windows/amd64 BuildDate: 2020-03-24T12:04:36Z

**Comment by jmooring** [comment]
I was unable to reproduce the reported problem with `Hugo Static Site Generator v0.69.2/extended linux/amd64 BuildDate: 2020-04-24T12:43:32Z` using the following markdown:

```md
# Super Chicken

{{< youtube dAHlGeVGp-4 >}}

# Tom and Jerry

{{< youtube M8tqOh8T62o >}}

# Looney Tunes

{{< youtube WDmNwyVNqHE >}}
```
