### ISSUE TITLE
Regression in v0.69: using `resources.Get` in scss file

### ISSUE THREAD

**Issue by acalvo** [gohugoio/hugo#7197]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.69.0-4205844B darwin/amd64 BuildDate: 2020-04-10T09:10:40Z
</pre>

### Does this issue reproduce with the latest release?
Yes.

I have the following statement in a `scss` file:
```css
background-image: url('{{ (resources.Get "img/bg.jpg" | fingerprint ).Permalink }}');
```

Then, in a template file I'm using it like this:

```html
{{ $style := resources.Get "scss/all.scss" | resources.ToCSS (dict "outputStyle" "compressed") | resources.ExecuteAsTemplate "style.css" . | resources.PostCSS | fingerprint }}
<link href="{{ $style.Permalink | relURL }}" rel="stylesheet" type="text/css">
```

Up to Hugo v0.68.3 it worked like a charm: it was translated into something like

```css
background-image:url('img/bg.3e3a2a7a159fbf54d2439bce397785641390145417399ce4766e21ee9625d7ef.jpg');
```

Hugo dealt with the image (the given route existed), etc.

After upgrading to Hugo v0.69 the output CSS keeps being the same but the image doesn't exist anymore (404), so it isn't shown. This happens both when compiling for production and on `hugo serve`.

I assume this is a regression, isn't it?

**Comment by bep** [comment]
I don't see what you mention above could have ever worked.

**Comment by acalvo** [comment]
@bep Any other way of achieving this in v0.69, then?

I was using this method because a few months ago I asked for help in https://discourse.gohugo.io/t/fingerprinting-resources-used-in-css/20980 and you suggested it. But I might have misunderstood it or there may be a better way of achieving it!

Any further help around this is appreciated 😊

**Comment by bep** [comment]
>Any other way of achieving this in v0.69, then?

Yes, using the ExecuteAsTemplate function. But please use the forum for questions.

**Comment by acalvo** [comment]
I was already using `ExecuteAsTemplate`... But after further research the problem was as simple as that I was **not** using the `extended` version of Hugo v0.69 🤦‍♂️.

The cache (`resources` folder) was kept from the previous version so there were no SCSS errors (unless you deleted that folder). The only visible consequence was the one I reported: the missing output image. With the `extended` version everything works as expected.

Sorry for the invalid bug report and thanks for your work! 😊
