### ISSUE TITLE
[question] hugo PR preview solution 

### ISSUE THREAD

**Issue by TommyLike** [gohugoio/hugo#7201]
Hey guys,
    we are using hugo as our website framework to deploy our official website on kubernetes, as more and more github pull requests coming in we'd like to provide a preview link based on code of PR. therefore does anyone know whether theres is a existing project doing the things we need? (something like a kubernetes operator that download pr codes, start a new instance,and expose the website via sub_url? ) or maybe there are something more simplier solution.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
