### ISSUE TITLE
-- minify CSS  removes quotation from strings with blanks

### ISSUE THREAD

**Issue by gj52** [gohugoio/hugo#7212]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo 0.69.2

</pre>

### Does this issue reproduce with the latest release?
YES

-- minify removes quotation

```
feed {
	font-family: "Source Sans Pro", Helvetica, "sans-serif";
}
```
goes to 
```
feed {
	font-family:  Source Sans Pro, Helvetica, sans-serif;
}
```

IF strings contains blanks, the quotes MUST stay here.

**Comment by palant** [comment]
I verified under https://go.tacodewolff.nl/minify that the current version of the minifier library still shows this behavior. IMHO this behavior is correct however given CSS syntax. To quote https://developer.mozilla.org/en-US/docs/Web/CSS/font-family:

> Font family names must either be given quoted as strings, or unquoted as a sequence of one or more identifiers. This means that punctuation characters and digits at the start of each token must be escaped in unquoted font family names.

So "Source Sans Pro" doesn't need to be quoted, "Source Sans 12" or "Source Sans .NET" on the other hand do. That seems to match the library's implementation.

**Comment by Traumflug** [comment]
Similar issue: #6621

**Comment by tdewolff** [comment]
@palant is correct that removing quotes here is completely valid. If this causes a bug, please file a bug report at https://github.com/tdewolff/minify
