### ISSUE TITLE
hugo new ignoring archetype when using content in filepath

### ISSUE THREAD

**Issue by tyler71** [gohugoio/hugo#7217]
### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.69.2-EC9DCF30/extended linux/amd64 BuildDate: 2020-04-24T07:57:53Z
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.14.1"
</pre>

### Does this issue reproduce with the latest release?
Yes

___

This will reproduce the file in archetypes/projects.md
```
hugo new projects/test.md
```
This will show the default one and *not* include the content of `projects.md`
```
hugo new content/projects/test.md
```

Both produce a file at `content/projects/test.md`

I would expect both to include the content of archetype projects.md

**Comment by tyler71** [comment]
This continues to occur with `v0.74.2-48565DE6/extended`

**Comment by tyler71** [comment]
This continues to occur with `v0.79.1-EDB9248D linux/amd64 BuildDate: 2020-12-19T15:42:17Z`

For quicker testing
```
VERSION=0.79.1
apt-get update && apt-get install -y wget
wget "https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.deb"
apt-get install ./hugo_${VERSION}_Linux-64bit.deb

hugo new site demo
cd demo

cat archetypes/default.md | sed 's;title:.*;title: Demo;' > archetypes/demo.md

# This works
hugo new demo/test1.md

# This doesn't work
hugo new content/demo/test2.md

cat content/demo/test1.md content/demo/test2.md
```

**Comment by davidsneighbour** [comment]
This is not a bug. Archetypes are only applied when `hugo new` starts with the section name that is configured with an archetype file. You have no archetype file for `content`. The proper use is `hugo new section/path...` which is pretty well discussed in the documentation: https://gohugo.io/content-management/archetypes/#what-are-archetypes - there is no "deduction" what part of your path is a section for which to lookup an archetype.
