### ISSUE TITLE
.File.Dir on zero object

### ISSUE THREAD

**Issue by muv1** [gohugoio/hugo#7220]
Putting either one of these:

~~~
{{ .File.Dir }}
{{ .Page.File.Dir }}
~~~

into `layouts/_default/section.html`, produces this:

~~~
Building sites … WARN 2020/04/27 17:18:39 .File.Dir on zero object. Wrap it in
if or with: {{ with .File }}{{ .Dir }}{{ end }}
~~~

but using either with `layouts/shortcodes/a.html` works fine. Tested with
Hugo 0.69.2.

**Comment by bep** [comment]
Only this {{ .File.Dir }}

Produces that warning. It works fine, but it will break some time in the future.

**Comment by muv1** [comment]
What youve said is not correct, from my own testing.

However it seems the issue was I was trying to treat entries like `categories` and `tags` as files, when they are perhaps virtual files. So it would make sense that they dont have File access like a normal page.
