### ISSUE TITLE
ignoreFiles and layouts folder

### ISSUE THREAD

**Issue by nu8** [gohugoio/hugo#7221]
I currently use this to ignore everything except Markdown:

~~~yaml
ignoreFiles:
- \.[^m]
- \.m[^d]
- \.md.
~~~

However I noticed that it ignores **everything**, even files in **layouts**.
This seems to contrast with the documentation:

> The following statement inside `./config.toml` will cause Hugo to ignore
> **content** files ending with `.foo` and `.boo` when rendering:
>
> `ignoreFiles = [ "\\.foo$", "\\.boo$" ]`

<https://gohugo.io/getting-started/configuration#ignore-content-files-when-rendering>

**Comment by muv1** [comment]
Workaround:

~~~yaml
ignoreFiles:
- content/.*\.[^m]
- content/.*\.m[^d]
- content/.*\.md.
~~~

**Comment by zor-el** [comment]
In addition, I suggest to improve the documentation to make it clear

1. what the regular expressions apply to: Only the file name? The full path? The relative path? (And relative to what?)
1. how they are applied (weather they can match anywhere or from the beginning of a string)

Because for ex. the pattern to ignore a content subfolder like [described here](https://discourse.gohugo.io/t/ignore-a-directory/8880/2) doesn't work any more, and it is unclear why without the information listed above.

**Comment by muv1** [comment]
> I second this. In particular, I can't figure out why `ignoreFiles:
> ["\.suffix$"]` ignores `content/post/foo/file.suffix` but not
> `content/post/foo/bar/file.suffix`. I guess there could be an interference
> with page bundle handling, but that's unclear.

If you have a file like:

~~~
content/sunday/monday/a.go
~~~

You need this:

~~~
content/sunday/_index.md
~~~

Else the file will remain.

> **Update:** To make things even more confusing, `ignoreFiles: ["/bar$"]`
> ignores the entire `content/post/foo/bar` directory (as well as any other
> directory named `bar` under content), but `ignoreFiles: ["/bar/"]` doesn't.
> confused

If I have something like `content/sunday/index.md`, then `/sunday/` does ignore
it, not sure what you are trying to do.

>     1. what the regular expressions apply to: Only the file name? The full
>     path? The relative path? (And relative to what?)

The input string is the entire path. So for Windows, that is something like

~~~
C:\sunday\content\monday\index.md
~~~

>     2. how they are applied (weather they can match anywhere or from the
>     beginning of a string)

You can match from beginning or end or both, as long as you respect that the
input is in the form I just mentioned.

**Comment by zor-el** [comment]
@muv1, thanks for the response.

> If I have something like content/sunday/index.md, then /sunday/ does ignore
it, not sure what you are trying to do.

``` bash
$ ls -1 content/post/sunday/
index.md
README.txt
monday
$ ls -1 content/post/sunday/monday/
_index.md
a.go
b.txt
c.png
```

I'm trying to ignore either the entire `monday` folder, or specific files within it (I've got both use cases). So far, `/monday$` and `/monday` do ignore the folder, but `/monday/` doesn't. Also, `\.txt$` ignores `README.txt` but not `b.txt`. The behavior is the same with or without `monday/_index.md`.

**Comment by muv1** [comment]
It just seems like you have the wrong setup. I have just tested this. If you
start with this:

~~~
content/sunday/_index.md
content/sunday/sun.go
content/sunday/monday/index.md
content/sunday/monday/mon.go
~~~

You can use this to kill a whole folder:

~~~yaml
ignoreFiles:
- /content/sunday/monday/
~~~

and this for a specific file:

~~~yaml
ignoreFiles:
- /content/sunday/monday/mon.go$
~~~

again, if you are wanting to ignore stuff, you need to have `_index.md` files
in the right places for `ignoreFiles` to be properly honored.

**Comment by zor-el** [comment]
@muv1 not sure what you mean by "the wrong setup", but I believe we've got different use cases. Here are mine:

I have blog posts that are "page bundles", where some page resources exist in sub-folders of the post folder, but they also contain stuff not meant for deployment, like this:

```
$ ls -1 content/post/PLACEHOLDER/         # note the `/post/` folder
index.md
assets
code_samples

$ ls -1 content/post/PLACEHOLDER/assets
image.png
graph.png
graph.dot # source of graph.png
```

1. I want to ignore `*.dot` files in anywhere below `content`.
1. I want to ignore every `code_samples` folder below `content`.

The intuitive setting doesn't seem to work.

```yaml
ignoreFiles:
- \.dot$
- /code_samples/
```

Do you have an explanation why, and how to achieve that instead?

**Comment by muv1** [comment]
If you want `ignoreFiles` to be honored, you must have `_index.md` in the
correct places. For example, if you have something like this:

~~~
content/sunday/index.md        BAD
content/sunday/sun.go
content/sunday/monday/index.md
content/sunday/monday/mon.go
~~~

If you want `monday` or anything inside it to be ignored, the above setup wont
work as you havent created a branch bundle:

<https://gohugo.io/content-management/page-bundles>

So, before doing anything with anything with `ignoreFiles`, go back. Look over
all your entries that you might want to ignore. and make sure, in each case,
that the parent has a `_index.md`. If your content is deeply nested, that might
mean you need to create `_index.md` at multiple depths. Once thats all done,
then add the ignore rules.

Please do not comment further on this line of questioning, as its off topic for
this thread. This thread is about the `layouts` folder, no the basics of Hugo.

**Comment by zor-el** [comment]
> Please do not comment further on this line of questioning, as its off topic for
this thread. This thread is about the layouts folder, no the basics of Hugo.

Why so rude, mate? To me the issue reads very much like an issue about confusing documentation of `ignoreFiles` (quote straight from your issue text: *"This seems to contrast with the documentation"*), and I just wanted to *second* that as an info to the devs, that's all. So I wasn't actually addressing you when I posted my 1st comment, but the Hugo devs. If you didn't want a subsequent discussion, you could have just stayed out of it.

No need to respond. I'm outa here.

**Comment by nu8** [comment]
https://github.com/gohugoio/hugo/issues/3811

**Comment by nu8** [comment]
To anyone interested, I updated my patterns to this:

~~~yaml
ignoreFiles:
- /content/.*/.*/.*/.*/
- /content/.*\.[^m]
- /content/.*\.m[^d]
- /content/.*\.md.
~~~

Same as before, but first line is new. Its to catch Rust build files, as some
of them dont have an extension:

~~~
rust\target\debug\build\serde-743f9119809042f4\output
~~~
