### ISSUE TITLE
Jsonify is escaping characters

### ISSUE THREAD

**Issue by zbayoff** [gohugoio/hugo#7229]
### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.63.1-CE9ACEB7 darwin/amd64 BuildDate: 2020-01-23T20:10:12Z

</pre>

Test:

{{ $testDict := dict "\<any-key\> " “value”}}
{{ $testDict | jsonify }}

gives:

{"\u003cany-key\u003e":“value”}

Is this a bug with jsonify or is there a hugo function I’m missing? Even a short term fix/hack would be greatly appreciated. 
Thanks!

**Comment by bep** [comment]
It's the Go HTML template doing its ... job.

Try

```
{{ $testDict | jsonify | safeJS }}
or

{{ $testDict | jsonify | safeHTML }}
```

**Comment by zbayoff** [comment]
@bep Those don't work unfortunately. I had to resolve with a replace:
```
replace (replace $testDict "\\u003c" "<") "\\u003e" ">"
```

**Comment by bep** [comment]
That function just delegates to Go's JSON package, so not sure what's going on ... But I'll reopen.

**Comment by FuadEfendi** [comment]
Confirming, still doesn't work, `htmlUnescape` doesn't help. I use this naive snippet to keep HTML tags unescaped:
```
{{- $output := ($scratch.Get "pages") | jsonify -}}
{{- $output2 := replace (replace $output "\\u003c" "<") "\\u003e" ">" -}}
{{- $output3 := replace $output2 "\\n" "" -}}
{{- replace $output3 "\\u0026" "&" -}}
```

**Comment by jmooring** [comment]
There's nothing wrong with escaping those characters. See this roundtrip:

```text
{{ index (dict "<key>" "val" | jsonify | transform.Unmarshal) "<key>" }} --> val
```

If you really don't want to escape `&`, `<`, and `>`, do this:

```text
{{ dict "<key>" "val" | jsonify (dict "noHTMLEscape" true) }}
```

See <https://gohugo.io/functions/encoding/jsonify/>
