### ISSUE TITLE
Add `update` template funcs to change maps and slices

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#7232]
I once wrote a proposal (https://github.com/gohugoio/hugo/issues/5604) for a complex data manipulation API which I now find unnecessary except for the ability to build on maps.

For now the only way to build on maps is either using `.Scratch` (SetInMap) or the [merge](https://gohugo.io/functions/merge/#readout) function which tends to be much slower.

<del>A problematic data race (https://github.com/gohugoio/hugo/issues/7230#issuecomment-622334415) was recently surfaced on `.Scratch.SetInMap`. Applying a patch for it might slow the build of other more common usage.</del>

This proposal explores building on maps without Scratch.

## Proposal

Introduce a global function to build on maps

### 1. Use the existing `append` function 
It is currently reserved for slices. This means the improved `append` would test for the input data type, and upon finding a `map`, expect 3 arguments instead of 2:
- initial map
- key
- value

If key already exists, it would be overwritten.

```
{{ $data := dict }}
{{ $data = append $data "key" "value" }}
```

### 2. A new function, yet to be named 
It would take 3 parameter
- initial map
- key
- value

If key already exists, it would be overwritten.

```
{{ $data := dict }}
{{ $data = appendToMap $data "key" "value" }}
```
### 3. `keyVals`

I know we use a [`keyVals` function](https://gohugo.io/content-management/related/#relatedto-keyvals-keyvals2-) (undocumented outside of Related Content) I have no idea if this could be useful in this context, but some might chime in.

## Also
This would remove the use of `.Scratch.SetInMap` and allow the future retirement of `.Scratch`. This was a great feature, but a workaround to now lifted Go Template limitations.

**Comment by bep** [comment]
The thing is, from your problematic case earlier:

```html
{{ $data := partialCached "foo" }}
{{ $data = $data  | append "key" "value" }}
```

The above would have exactly the same concurrency issues; the panic is one thing, but I since multiple threads are working on the same data structure -- the end result seems to be pretty random.

**Comment by regisphilibert** [comment]
> The above would have exactly the same concurrency issues; 

Fair enough, but I think this proposal still has value.

**Comment by bep** [comment]
I think we need to let `append` be about slices -- people coming from Go will be confused.

The performance problem with `merge` is that it makes a copy on every invocation -- which we could avoid by adding a `mergeUpdate` variant (or something).

Maybe better would be to add a `update` template func (name?) -- which would in it's name make it clear that we mutate the data you send in.

```
{{ $data = $data  | update "key" "value" }}
```

**Comment by regisphilibert** [comment]
I think `update` is great. I've been looking for a term that would make it obvious it's to update Maps and nothing else... but I can't find anything better so I'm all for `update`

**Comment by bep** [comment]
We should make it work for slices to, so:

```
{{ $data = $data  | update 0 "value" }}
```

Would work.

I thought about `set` as well, but that probably makes people think it creates a `Set`.

**Comment by regisphilibert** [comment]
> We should make it work for slices to

I'm looking for a use case but can't find one. Beside how could one know which index to update in the slice? Is there a way to identify the index of a value in a slice? An `indexOf` of some sort.

**Comment by bep** [comment]
There is certainly some "shooting in the foot" potential for such a function, (`.Params | update "randomparam" "foo"`), but we can worry about that later.

> An indexOf of some sort.

You can get it when ranging, e.g. `{{ range $index, $element := myslice }}` -- and I'm pretty sure I got that syntax wrong. Anyway, we can start with maps.

**Comment by bep** [comment]
Just got a cool showcase in for the docs site.

**Comment by regisphilibert** [comment]
> There is certainly some "shooting in the foot" potential for such a function, (.Params | update "randomparam" "foo"), but we can worry about that later.

Same for `.Params.authors | append "randomparam" "foo")` I guess...

Are `.Params` and `dict "key" "value"` of the same data type, can't we forbid some data types as input?

**Comment by bep** [comment]
>Same for .Params.authors | append "New Author" I guess...

No, that does not change the slice.

**Comment by moorereason** [comment]
`update` seems too vague to me.  I like `set`, but had the same reaction as @bep -- it's also a little too vague.

What about `setitem`?
```
{{ $data = $data  | setitem "key" "value" }}
```

**Comment by bep** [comment]
```
{{ $data = $data  | put "key" "value" }}
```

???

**Comment by regisphilibert** [comment]
Maybe ask the discourse for ideas?

**Comment by regisphilibert** [comment]
`put`, `update`, or `assign` which could be another lead, tends to let the user think more than one can be set.

I think `set` is the way to go, it is short, and aalready used in Javascript (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set)

If we want to make it less evasive, maybe we could start wrapping map functions in a keyword: `map.Merge`, map.Set`.
`slice.Append` could be introduced as well...

**Comment by moorereason** [comment]
@regisphilibert, your `set` example from Javascript is a method on Map objects, not a function, so there's inherently less ambiguity.

Of the options presented so far, I still like `setitem` the most.  I found a couple other implementations using this naming convention:
* Python uses [`__setitem__`](https://docs.python.org/3/reference/datamodel.html#object.__setitem__) and `__getitem__` to provide map-like functionality to classes.
* The Web Storage API uses [`setItem`](https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem) with a key+value pair.  Granted these are methods, but it just shows that there are other approaches in the Javascript community.

While googling around, I saw another option: the Rust `std::collections::HashMap` library uses [`insert`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.insert) to add/update a map.  Again, it's a method.  Not sure what I think about this option yet.

**Comment by regisphilibert** [comment]
I like `insert`. 
`setitem` is also good, it's just hard to read without case, I'm always struggling with `getenv` :)

**Comment by instance-id** [comment]
Is there no way to do this currently? 

I have a data template that I am having "Jsonified" based on a json.json file and I was leaving the date field set as "" expecting to be able to do something like:

(Shortened)
```Go
{{ range $log := $chlog }}
{{ if eq (index $log "date") "" }}
{{  (index $log "date") = (now.Format "2006-01-01") }}
```

Which didn't work, so I tried to see if this would:
(shortened)
 ```go
{{.Scratch.Add "tomlData" $chlog}}
{{ range (.Scratch.Get "tomlData") }}
{{ if (eq (index . "date") "") }}
{{ .Scratch.SetInMap "tomlData" (index . "date") (now.Format "2006-01-01") }}
{{end}}
{{end}}
{{- jsonify (.Scratch.Get "tomlData") -}}
```

That didn't work either. Is there some way to replace a blank value in a map

**Comment by moorereason** [comment]
@instance-id, please use the discussion forums for help with using Hugo.
