### ISSUE TITLE
port 1313 already in use, attempting to use an available port

### ISSUE THREAD

**Issue by cikichen** [gohugoio/hugo#7237]
![image](https://user-images.githubusercontent.com/1478821/80864260-1e629300-8cb4-11ea-8bd7-226ef634687c.png)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.69.2/extended linux/amd64 BuildDate: unknown

$ hugo env
Hugo Static Site Generator v0.69.2/extended linux/amd64 BuildDate: unknown
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.14.2"
</pre>

**Comment by frerich** [comment]
Can you still reproduce the issue? If so, just to double-check: what does 

```
nc -v localhost 1313
```

print?

**Comment by DHowett** [comment]
I'm seeing this on Windows as well.
After terminating the development server a couple of times, it can never get 1313 back.

```
% nc -v localhost 1313
nc: connect to localhost (127.0.0.1) port 1313 (tcp) failed: Connection refused
```

Confirming that there's nothing listening on 1313:

```
libra ~ # get-nettcpconnection -localport 1313 # (as admin)
Get-NetTCPConnection: No MSFT_NetTCPConnection objects found with property 'LocalPort' equal to '1313'.  Verify the value of the property and retry.
```

![image](https://user-images.githubusercontent.com/189190/90354710-ebdc6c00-dffe-11ea-9899-6d6abdbe6902.png)

Sorted by port, this is where I would expect to find `1313`.

**Comment by DHowett** [comment]
This could be a [Hyper-V port reservation](https://blog.sixthimpulse.com/2019/01/docker-for-windows-port-reservations/). If I check `netsh int ipv4 show excludedportrange protocol=tcp`, I do have an excluded port range  that covers 1313.

@cikichen Is this also true for you?

**Comment by cikichen** [comment]
> This could be a [Hyper-V port reservation](https://blog.sixthimpulse.com/2019/01/docker-for-windows-port-reservations/). If I check `netsh int ipv4 show excludedportrange protocol=tcp`, I do have an excluded port range that covers 1313.
> 
> @cikichen Is this also true for you?

Yes, it is a reserved port on Windows
