### ISSUE TITLE
TableOfContents using website root for link creation

### ISSUE THREAD

**Issue by b4d** [gohugoio/hugo#7238]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.69.2-EC9DCF30 linux/amd64 BuildDate: 2020-04-24T07:48:20Z
</pre>

### Does this issue reproduce with the latest release?
Yes.

### The problem

The problem is that `{{ .TableOfContents }}` creates links like this:
`https://b4d.sablun.org/#intro`

instead of full link with the blog post:

`https://b4d.sablun.org/blog/2020-04-20-247ctf-com-web-administrative-orm/#intro`

So it uses website root without the suffix of the post.

Anybody has the same problem?

**Comment by b4d** [comment]
The issue is still reproducible in:

```
Hugo Static Site Generator v0.74.3-DA0437B4 linux/amd64 BuildDate: 2020-07-23T16:22:34Z
```

**Comment by b4d** [comment]
Okay, found a solution, apparently you need to use:

```
baseurl = ""
```

instead of

```
baseurl = "https://b4d.sablun.org"
```

in your config file.


To fix the direct links to base url add an `/` at the end:

```
{{ .Site.BaseURL }}/
```

**Comment by toby3d** [comment]
I ran into the same problem of broken anchor links to the home in Hugo v0.79.0, but I can't fix it through configuration edits. None of the following methods solve the problem:
* `baseUrl: /`
* `baseUrl: http://localhost:1313`
* `baseUrl: http://localhost:1313/`
* Remove `baseUrl` key
