### ISSUE TITLE
Comment in first row of templates still makes the page go blank

### ISSUE THREAD

**Issue by jstromergalley** [gohugoio/hugo#7243]
### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.69.2-EC9DCF30 windows/amd64 BuildDate: 2020-04-24T07:51:17Z
</pre>

### Does this issue reproduce with the latest release?
yes

Issue #6816 was closed, however this issue was never resolved.  A single that starts with a comment (if that single is based on a baseof) will fail to render.

```
{{- /*
	-----------------------------------------
	Block Name:
		foo

	Description:
		results in 0 pages rendered
	-----------------------------------------
*/ -}}
{{- define "foo" -}}
....... some template contents ......
{{- end -}}
```

Removing the initial comment allows rendering. The last time this worked was v63.x

**Comment by jstromergalley** [comment]
This is also a potential workaround:

```
{{- define "workaround" -}}{{- end -}}
{{- /*
	-----------------------------------------
	Block Name:
		foo

	Description:
		results in 0 pages rendered
	-----------------------------------------
*/ -}}
{{- define "foo" -}}
....... some template contents ......
{{- end -}}
```

**Comment by pamubay** [comment]
You can use the comment without the dash `-`, just simply:
```
{{/* 

 Comment

*/}}
```
that comment block is not going to produce whitespace tho. No need to use extra `-` dash.

**Comment by jstromergalley** [comment]
@pamubay Thanks for the heads up. We use the {{- -}} as a pattern that less technical authors can follow as a general rule.  You are correct though that they can be omitted if the multi-line comment is snuggled up to the opening and closing braces.

Alas, this does not resolve the actual issue though that child templates that begin with a comment in any form will not render a result.

Rather than be stuck at 63.x we now place a dummy block

`{{- define "workaround" -}}{{- end -}}`

at the beginning of these files, though that feels wrong.

**Comment by regisphilibert** [comment]
> Alas, this does not resolve the actual issue though that child templates that begin with a comment in any form will not render a result.

Not in any form, in the form you use:
```
{{- /*
comment
*/ -}}
```

As pointed out by @jstromergalley you don't need the `-` and removing them IS your workaround. 

Maintaining an open source project consumes a lot of time, when fixing the comment issue in baseof, it appears this superfluous syntax was not covered, by design or omission. Until someone wishes to cover it, you can simply remove the `-` and all will be well.

**Comment by jstromergalley** [comment]
Thanks @regisphilibert .  Just to be clear, these specific style of comments *DO* work at the start of the document...

`{{/* Comment */}}`

**Comment by regisphilibert** [comment]
Correct.
