### ISSUE TITLE
Obsolete attribute align on td with Goldmark

### ISSUE THREAD

**Issue by tdelmas** [gohugoio/hugo#7244]
### Does this issue reproduce with the latest release? Yes
The markdown
```md
| Tag (decimal)         | Tag (hex)             | Type                  |
| ---------------------:| ---------------------:| --------------------- |
| 2                     | 02                    | INTEGER               |
```

With Goldmark generate html containing

```html
<td align="right">2</td>
```

Witch is not valid: the align attribute is obsolete https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td#attr-align and marked as ERROR with html5validator.

Hugo should allow the configuration of css class to replace those deprecated attributes. 

Apparently Goldmark provides a way to do so: https://github.com/yuin/goldmark/pull/78#issuecomment-568905772

Posted first in https://discourse.gohugo.io/t/obsolete-attribute-align-on-td-with-goldmark/25021

**Comment by bep** [comment]
Only if the last part of https://github.com/yuin/goldmark/pull/78#issuecomment-622670551 gets implementedd. We're not adding any special HTML rendering logic in Hugo to handle this.

**Comment by yuin** [comment]
goldmark v1.2.0 has been released. Table extension gets a new option.
https://github.com/yuin/goldmark/commit/bd58441cc141c6455d2ed592a4f1d01adee4211a

**Comment by moorereason** [comment]
Removed `upstream` tag as `goldmark` now supports options to control this.

**Comment by jmooring** [comment]
Closing in favor of #11434.
