### ISSUE TITLE
Add syntax highlighting for httpd, relayd servers

### ISSUE THREAD

**Issue by hucste** [gohugoio/hugo#7246]
Hi, 

As, apache or nginx, better, please add a chroma lexer for httpd and relayd servers. (OpenBSD's native webserver and proxy)

Syntaxe of thoses servers are quasi-same as nginx!

Thanks!

**Comment by moorereason** [comment]
This request needs to be made in the chroma project.

**Comment by hucste** [comment]
ok. Where is this project, please?
