### ISSUE TITLE
Add additional directories to watch in config.toml

### ISSUE THREAD

**Issue by bwklein** [gohugoio/hugo#7248]
I have 2 documents in the content tree that `include` a source file outside of content in a folder at the root level of the project called "includes".  I would like to tell Hugo to watch for changes in that folder and reload the site as it does for files in assets, content layouts, etc.

**Comment by bep** [comment]
Have a look at the mount feature in Hugo. If you mount that folder to somewhere inside your project (e.g `/assets`), it gets added to the watch list.

**Comment by bwklein** [comment]
That works well enough for me. I'll close this issue with that as the solution.

**Comment by bep** [comment]
Just and added note: If you add a mount configuration to your project, you need to make it complete (e.g. add content, layouts, static ... whatever you use). This seem to trick many users, but it behaves like this for noble reasons.
