### ISSUE TITLE
Babel broken on Windows

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#7251]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.70.0/extended windows/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

yup

So, I tried to test drive the new Babel pipes addition :) On Windows I get the following error:

```
C:\Users\xmr\Desktop\bootstrap>ver

Microsoft Windows [Version 10.0.18363.815]

C:\Users\xmr\Desktop\bootstrap>node -v && npm -v
v12.16.3
6.14.4

C:\Users\xmr\Desktop\bootstrap>npm ls @babel/cli @babel/core
bootstrap@4.3.1 C:\Users\xmr\Desktop\bootstrap
+-- @babel/cli@7.8.4
+-- @babel/core@7.9.6
`-- stylelint@13.3.3
  `-- @stylelint/postcss-css-in-js@0.37.1
    `-- @babel/core@7.9.6  deduped


C:\Users\xmr\Desktop\bootstrap>npm run docs-serve
> bootstrap@4.3.1 docs-serve C:\Users\xmr\Desktop\bootstrap
> hugo server --port 9001 --disableFastRender

Building sites … Built in 1828 ms
Error: Error building site: BABEL: failed to transform "js/main.js" (application/javascript): fork/exec C:\Users\xmr\Desktop\bootstrap\node_modules\@babel\cli\bin\babel.js: %1 is not a valid Win32 application.
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! bootstrap@4.3.1 docs-serve: `hugo server --port 9001 --disableFastRender`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the bootstrap@4.3.1 docs-serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmr\AppData\Roaming\npm-cache\_logs\2020-05-06T13_08_14_971Z-debug.log
```

**Comment by bep** [comment]
How can something new be broken? :-)

I'll admit, I haven't tested this on Windows, but it works fine on MacOS. Can you tell me if there are any executables inside `C:\Users\xmr\Desktop\bootstrap\node_modules\@babel\cli\bin`?

**Comment by XhmikosR** [comment]
The file is there, but Windows doesn't support shebangs. Hence if you want to run that file you need to do `node foo.js` or `node.exe foo.js`.

```
C:\Users\xmr\Desktop\bootstrap\node_modules\@babel\cli\bin>node babel.js --version
7.8.4 (@babel/core 7.9.6)
```

My guess is that it's due to that. How are you calling postcss BTW? It should be the same way.

**Comment by XhmikosR** [comment]
@bep Now that I think about it more, I believe if one has installed the 2 packages globally, they won't hit this issue, because npm adds executable files in PATH. If you want to access the local executable files, you should access them in `./node_modules/.bin/babel`.

So this issue should be present only for local installations.

**Comment by bep** [comment]
I think I see it now ... I based the Babel implementation on top of an old PR -- and that was based on an older PostCSS implementation. We have since fixed this for PostCSS. I will get these in line and test on Windows.
