### ISSUE TITLE
Broken Homepage

### ISSUE THREAD

**Issue by craigmpeters** [gohugoio/hugo#7255]
### What version of Hugo are you using (`hugo version`)0.70.0

<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release?
Yes

The issue is with the homepage and older templates there is no guide (and please do not link to the previous issue) on how to migrate older templates to new templates.  This is very very **very** bad form to put breaking changes like this in non major versions, I am sorry but it is.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
