### ISSUE TITLE
/ before separator for getCSV

### ISSUE THREAD

**Issue by fundor333** [gohugoio/hugo#7258]
### What version of Hugo are you using (`hugo version`)?

Hugo v0.70.0 Mac install with brew

### Does this issue reproduce with the latest release?

Yes

### The bug

I am using getCSV for importing a csv from the web and this file launch an error

`
ERROR 2020/05/08 00:06:05 Failed to get CSV resource "https://raw.github.com/Gelma/LugMap/master/db/veneto.txt": failed to parse CSV file https://raw.github.com/Gelma/LugMap/master/db/veneto.txt: record on line 2: wrong number of fields`
`

This error is when you have the separetor after a / .

You can reproduce this bug with this code in a template file

`
{{ $url := print "https://raw.github.com/Gelma/LugMap/master/db/veneto.txt" }}
{{ $sep := "|" }}
{{ range $i, $r := getCSV $sep $url }}
<p>{{ index $r 0 }}</p>
<p>{{ index $r 1 }}</p>
<p>{{ index $r 2 }}</p>
<p>{{ index $r 3 }}</p>
<p>{{ index $r 4 }}</p>
<br>
{{ end }}
`

**Comment by jmooring** [comment]
Your CSV file is invalid. See:

<https://gohugo.io/templates/data-templates/#specs-for-data-formats>  
<https://tools.ietf.org/html/rfc4180>

Section 2, item 4 of RFC4180 states:

> Each line should contain the same number of fields throughout the file.

Some of the records in your file contain a phone number, others do not. Here's [a clean file with the phone numbers removed](https://gist.githubusercontent.com/jmooring/d9220a54bdd897abe38e45cd9fe9c7a7/raw/4605eac2e13121ed647952aded9baba1a7e7d921/hugo-github-issue-7258.txt).

**Comment by moorereason** [comment]
As @jmooring noted, your CSV file is improperly formatted.
