### ISSUE TITLE
URL not working?

### ISSUE THREAD

**Issue by rifkiaz** [gohugoio/hugo#7259]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 7

</pre>

### Does this issue reproduce with the latest release?

I can't download Hugo with .deb version because forbidden
![image](https://user-images.githubusercontent.com/23344569/81350646-9b46a000-90ec-11ea-832b-c29abcd21d4a.png)

**Comment by gibranv** [comment]
I think that was related to a problem with their download services. Now it works.

**Comment by rifkiaz** [comment]
yes it works again, thanks!
