### ISSUE TITLE
rel/relref fails to resolve properly when dots in filename

### ISSUE THREAD

**Issue by rawtaz** [gohugoio/hugo#7260]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.70.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What is the problem?
A relative (or absolute) reference *without file suffix* to another post in the same section works fine when the filename of the referenced post doesn't have a dot in the filename - the following works fine and generates a link properly:  `{{< relref "2016-08-22-foo-bar" >}}`

However, when the referenced post's filename has dots in it, it doesn't work:  `{{< relref "2016-12-13-foo-0.3.1-bar" >}}`

Adding the referenced file's suffix makes it work - the following generates a link properly:  `{{< relref "2016-12-13-foo-0.3.1-bar.md" >}}`

### What are the symptoms of the problem?
`ERROR 2020/05/08 17:43:20 [en] REF_NOT_FOUND: Ref "2016-12-13-foo-0.3.1-bar": "/some/path/to/site/content/blog/2016-12-18-foo-0.3.2-bar.md:6:46": page not found`

### Other comments
I understand it's a complex thing to try the possible combinations of files, but I have a gut feeling that it should be perfectly doable to make sure to try all relevant file suffixes added to the original referenced filename. Hence I think this is a bug rather than intended or wanted behavior.

**Comment by rdrgn** [comment]
+1

After upgrading Hugo from v0.60 to v0.69, I faced the same issue on my existing website.

**Comment by rawtaz** [comment]
@rdrgn Are you saying that this problem wasn't there with version 0.60? That is, in v0.60 `{{< relref "2016-12-13-foo-0.3.1-bar" >}}` worked as expected (finding and linking to the post for the file `2016-12-13-foo-0.3.1-bar.md`)? If so, that's good to know.

**Comment by rdrgn** [comment]
Yes. There was no problem while I used v0.60 or older versions.
However, I'm not sure which version is the cause because I hadn't been upgrading Hugo frequently (and I'm not so familiar with recent versions).

In my case, I used dots in directory names like `20200510.foo/index.md` and linked by writing `{{< ref "20200510.foo" >}}`.

**Comment by rdrgn** [comment]
`{{< ref "20200510.foo/index.md" >}}` works in my case!
`.foo` in `{{< ref "20200510.foo" >}}` may just be interpreted as a file extension.
So it is possible that my problem mentioned in the comment above and your issue are different...

I'm sorry for being so hasty. 😢 
I'm waiting for the contributor's comments.

**Comment by rawtaz** [comment]
This issue is still in need of review, let's not have the stale bot close it.

**Comment by rawtaz** [comment]
@stale Would you stop interfering with this issue that still needs review from a core maintainer? Your input is completely irrelevant and unwanted, you ignorant idiot. Whoever programmed you should learn to make you realize when an issue has been marked as not-to-be-stale once such that you then don't try to stale it again..

**Comment by tohn** [comment]
Not sure if this is related, but it also doesn't work if I want to link to `sitemap.xml` via `relref`.

**Comment by rawtaz** [comment]
I completely understand if there's no time for maintainer's to deal with the project. That's one thing. But having a bot automatically close issues just because noone attends them is 100% wrong. Just because an issue isn't attended does not mean it's not still a problem.
