### ISSUE TITLE
Hooks does not work in RenderString unless Page.Content is invoked first

### ISSUE THREAD

**Issue by gandhiShepard** [gohugoio/hugo#7265]
RenderHooks fail to be applied to frontmatter markdown strings, unless you make a call to .Content before the call to the frontmatter key you need rendered to markdown.

Example 1 (fail):
```
<div>{{ .Params.text | $.Page.RenderString }}</div>
```
This will not apply RenderHooks to the .text fronmatter property.

Example 2 (fail):
```
<div>{{ .Params.text | $.Page.RenderString }}</div>
<div>{{ .Content }}</div>
```
This will not apply RenderHooks to the .text fronmatter property either.

Example 3 - The hack (Pass):
```
<div>{{ .Content }}</div>
<div>{{ .Params.text | $.Page.RenderString }}</div>
```
This will make the RenderHook work for both outputs. However, in this case, I have an empty .Content variable. I'm only placing it above the call to .RenderString in order to get the RenderHook to be applied to the frontmatter markdown string contained in the .Params.text property.

I’m sure that RenderHooks were conceived for use with .Content because that’s were the content is! But RenderHooks provides a super power when used on frontmatter strings as well.

I use Forestry.io as a Content Management System for Hugo. As such, I can change the layout of the page if I store the content in the frontmatter as opposed to the .Content area. 

So, in the end, I cam make this work, but it is a hack. To make this more clear I spun up a quick site so you can see this behavior:
https://brownerd.gitlab.io/renderhookissue/

Here is the source code as well:
https://gitlab.com/brownerd/renderhookissue

Please advise.

P.S. Hugo is AMAZING!

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 
0.70.0
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
This is a bug.

Note that you can assign the content to a variable, so this is a better "hack":

```bash
{{ $notused := .Content }} }}
<div>{{ .Params.text | $.Page.RenderString }}</div>
```

**Comment by gandhiShepard** [comment]
True. That makes more sense for the work around. Also, I think there is an extra set of `}}` in your snippet after .Coment. Correct? Much respect.
