### ISSUE TITLE
/usr/bin/hugo: No such file or directory 

### ISSUE THREAD

**Issue by alvinsim** [gohugoio/hugo#7269]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.70.0-7F47B99E linux/amd64 BuildDate: 2020-05-06T11:18:50Z
</pre>

### Does this issue reproduce with the latest release?
Yes.

I installed the hugo binaries (https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.deb) in my Debian system (_version 10 running on WSL_). Each time I run 'hugo', it will output:` -bash: /usr/bin/hugo: No such file or directory.`

I did remove it and run the install again but it still shows the same error message.

Below is the output when doing the install.

```
$ sudo dpkg -i hugo_0.70.0_Linux-64bit.deb
Selecting previously unselected package hugo.
(Reading database ... 59738 files and directories currently installed.)
Preparing to unpack hugo_0.70.0_Linux-64bit.deb ...
Unpacking hugo (0.70.0) ...
Setting up hugo (0.70.0) ...

```

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
