### ISSUE TITLE
category_map or tag_map for hugo (nickname for tags)

### ISSUE THREAD

**Issue by kkworld** [gohugoio/hugo#7271]
My native language isn't English, and I am not a professional programmer. So sorry for my expression...

---

Recently I found out that if I use CJK character as a tag, the URL would be like ".../tags/XXX(the CJK character tag name)/..." Sometimes the server doesn't recognize it, and may cause some code change problem. And also I just don't want CJK character in URLs.

When I search the internet, I found that HEXO got "category_map" for these situation. It's like define a nickname for the tags and the URL goes like ".../tags/nickname/..."

Please help me if there is a way for Hugo to set tag nicknames. And that would be thankful.

**Comment by reuixiy** [comment]
I was a Hexo user too, so try this:

1. Add the following lines into your `config.toml`:
   ```toml
   [permalinks]
       categories = "/categories/:slug/"
       tags = "/tags/:slug/"
   ```
2. Create a new file for this category/tag, for instance, you have a tag named `中文`, then create a `content/tags/中文/_index.md` file, then add:
   ```toml
   slug = "chinese"
   ```

Additionally, you may need to add `titile = "中文"` to correct the title.

**Comment by kkworld** [comment]
> I was a Hexo user too, so try this:
> 
> 1. Add the following lines into your `config.toml`:
>    ```toml
>    [permalinks]
>        categories = "/categories/:slug/"
>        tags = "/tags/:slug/"
>    ```
> 2. Create a new file for this category/tag, for instance, you have a tag named `中文`, then create a `content/tags/中文/_index.md` file, then add:
>    ```toml
>    slug = "chinese"
>    ```
> 
> Additionally, you may need to add `titile = "中文"` to correct the title.

Thanks for help.

I've found this solution you mentioned in someone's blog. And I tried that yesterday. But I didn't add "title = 中文". And it didn't work out. 

So, ...
Where should I add this? Should I add it in the same "_index.md" file?
I will try this evening.

**Comment by kkworld** [comment]
> I was a Hexo user too, so try this:
> 
> 1. Add the following lines into your `config.toml`:
>    ```toml
>    [permalinks]
>        categories = "/categories/:slug/"
>        tags = "/tags/:slug/"
>    ```
> 2. Create a new file for this category/tag, for instance, you have a tag named `中文`, then create a `content/tags/中文/_index.md` file, then add:
>    ```toml
>    slug = "chinese"
>    ```
> 
> Additionally, you may need to add `titile = "中文"` to correct the title.

OMG, actually I found the solution in YOUR blog!
Thanks again. 
...
And why are we talking in English...

Hope Hugo could do something for the suggestion

**Comment by kkworld** [comment]
I tried and it didn't work out.
Maybe it is different because I'm using different theme. I don't know.
