### ISSUE TITLE
RSS: Allow custom output formats to render all links as absolute

### ISSUE THREAD

**Issue by palant** [gohugoio/hugo#7272]
RSS feeds aren't allowed to use relative links. This is an issue for any custom RSS output. The way I read the source code, the code path rendering all links in `.Content` as absolute is reserved for the default RSS format and cannot be used by custom formats. Maybe it should be configurable?

**Comment by palant** [comment]
As mentioned in the description, any custom RSS feed output has to be unnecessarily complicated, translating relative links into absolute "manually". This is still an issue.

**Comment by Seirdy** [comment]
Seconding this; was just the W3C's feed validator [recommends against relative URLs](https://validator.w3.org/feed/docs/warning/ContainsRelRef.html) in RSS feeds.

**Comment by palant** [comment]
Absolutely, relative URLs in feeds are highly problematic. Had a relative link once by mistake and some feed readers resolved then relative to the feed URL rather than post URL.

For reference, for the MemE theme we use this template to resolve relative links “manually” but it is quite a hack:

https://github.com/reuixiy/hugo-theme-meme/blob/e927542dbe1cb8329acfe475bcd77df2361118f8/layouts/partials/utils/make-links-absolute.html

This was introduced in https://github.com/reuixiy/hugo-theme-meme/issues/141.

**Comment by juchom** [comment]
I just came this issue and thanks to @palant it is solved with make-links-absolute.html

@palant could you please explain what this line is doing ?

```
{{ partial "utils/make-links-absolute.html" (dict "$" . "content" .Content) | html }}
```

Thanks

**Comment by palant** [comment]
@juchom This line invokes the `utils/make-links-absolute.html` template, passing `.` (context) and `.Content` as parameters. The processed content is then put through `html` filter and output.

**Comment by bep** [comment]
You can do this with a link render hook. I'm not prepared to cook up something special for this.

**Comment by Seirdy** [comment]
On Mon, Jun 14, 2021 at 08:24:33AM -0700, Bjørn Erik Pedersen wrote:
>You can do this with a link render hook. I'm not prepared to cook up something special for this.

Thought I'd share for anyone who has this issue and doesn't want to 
figure out how to do this with render hooks: I put together a solution 
using render hooks that works if your site BaseURL is a subdirectory: 
https://git.sr.ht/~seirdy/seirdy.one/tree/master/item/layouts/_default/_markup/render-link.rss.xml

Unlike some of the existing render-links examples I've seen, I made sure 
it also worked for sites whose BaseURLs are subpages of shared domains.

-- 
/Seirdy
