### ISSUE TITLE
Please document the Extended version

### ISSUE THREAD

**Issue by rgov** [gohugoio/hugo#7273]
I've been using Hugo for a while but just learned about the existence of "Hugo Extended" that seems to have SCSS support. However the differences between the versions are not really highlighted explicitly in the documentation so it's not really clear.

1. Why would I ever _not_ want to use the extended version?

2. The Install page explains how to get it in certain circumstances. But it is not mentioned for macOS, even though in the Releases page there's both a regular and extended version. It turns out that `brew` installs the extended version by default.

3. The only real documentation seems to be a minor "note" in the [0.43 release notes](https://gohugo.io/news/0.43-relnotes/).

My true preference though would be to eliminate this distinction.

**Comment by bep** [comment]
>My true preference though would be to eliminate this distinction.

That would require setting up and test a Go and C++ build chain for all the 20+ platforms we support.

There are reasons to not use the extended (if you don't use SCSS, and esp. if you run in an environment without libc, e.g. a tiny Docker container).

But we have a Documentation repo that is better suited for this issue:

https://github.com/gohugoio/hugoDocs/issues

**Comment by rgov** [comment]
Ok. Would you please move the issue to that repo with the "Transfer Issue" button in the side panel, so this context is preserved?
