### ISSUE TITLE
Permalink for taxonomy list page cannot be singular

### ISSUE THREAD

**Issue by gcushen** [gohugoio/hugo#7274]
Hugo users have requested to change the permalink for taxonomy list pages, such as to make it singular, however it appears that Hugo does not currently allow for this.

Issue: The following `config.toml` snippet correctly changes the URL of taxonomy term pages, but the taxonomy list page still remains at the old URL of `example.com/tags/` rather than `example.com/tag/`.

```
[permalinks]
    tags = "/tag/:slug/"
```

As requested by Hugo users at
- https://github.com/gcushen/hugo-academic/issues/1693#issue-617393065
- https://discourse.gohugo.io/t/permalink-for-taxonomy-list-page/25149?u=neutreno

### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.70.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by mitchellolsthoorn** [comment]
This is possible by using the `url` option. In the example below:

config/_default/config.yaml:
```
permalinks:
  tags: "tag/:slug/"
  ... <existing permalinks>
```

content/tags/_index.md:
```
---
url: tag
---
```

both the archive page and the individual tag pages are singular.
