### ISSUE TITLE
Build succeed with "hot reload", but fail when started from fresh "hugo server -D", resource became <nil>

### ISSUE THREAD

**Issue by StupidDuck** [gohugoio/hugo#7279]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.70.0-7F47B99E windows/amd64 BuildDate: 2020-05-06T11:17:50Z
</pre>

### Does this issue reproduce with the latest release?
yes

In a template, this builds fine, always :
<pre>
	{{ $source := .Params.featured_image }}
	{{ printf "%#v" $source }}
	{{ $featuredImageResource := .Resources.GetMatch (print $source) }}
	{{ printf "%#v" $featuredImageResource }}
</pre>

Then if I add one line, save my file, and this build fine in "hot reload" (watch), but fails if I build from a fresh "hugo server -D" command
<pre>
	{{ $source := .Params.featured_image }}
	{{ printf "%#v" $source }}
	{{ $featuredImageResource := .Resources.GetMatch (print $source) }}
	{{ printf "%#v" $featuredImageResource }}
	{{ $test := $featuredImageResource.ResourceType }}
</pre>

It fails on the last line, the resource "$featuredImageResource" became nil

<pre>
Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: execute of template failed: template: _default/list.html:16:3: executing "main" at <.Render>: error calling Render: failed to execute template ["post"] v: "C:\Users\Gilles\Projects\blog\themes\twenty-twenty-slim\layouts\_default\post.html:62:35": execute of template failed: template: _default/post.html:62:35: executing "_default/post.html" at <$featuredImageResource.ResourceType>: nil pointer evaluating resource.Resource.ResourceType
</pre>

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by Pinolpier** [comment]
Ok, I have exactly this problem. Currently running

hugo version
Hugo Static Site Generator v0.75.1/extended darwin/amd64 BuildDate: unknown

on macos 10.15.7 catalina.

I have not found any forum post regarding this. Is it solved or is there any help available on this?
