### ISSUE TITLE
Double-hyphens in post URLs reduce to single-hyphens; regression introduced in v0.50 causes links to break

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#7288]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.70.0-7F47B99E linux/amd64 BuildDate: 2020-05-06T11:18:50Z
</pre>

### Does this issue reproduce with the latest release?

Yes

---

**Expected behavior**: If the content file is named `content/foo--bar.md`, the page URL is expected to be `<site>/foo--bar/`.

**Observed behavior**: If the content file is named `content/foo--bar.md`, the page URL becomes `<site>/foo-bar/` (note that the double-hyphen becomes single-hyphen).

I believe this regression was caused ~~after the switch to Goldmark.~~ in https://github.com/gohugoio/hugo/commit/e421696d.

### Recipe to reproduce this issue

1. `git clone https://gitlab.com/hugo-mwe/double-hyphens-in-post-urls` (Content file: https://gitlab.com/hugo-mwe/double-hyphens-in-post-urls/-/blob/master/content/post--with--double--hyphens.md )
2. `cd double-hyphens-in-post-urls`
3. hugo

Above demo site is also deployed at https://determined-leakey-137470.netlify.app/ .

#### Observed output

In `public/index.html`, we will see:

```html
    <body lang="en">
        
        
            <p>Page link = /post-with-double-hyphens/</p>
```

#### Expected output

```html
    <body lang="en">
        
        
            <p>Page link = /post--with--double--hyphens/</p>
```

### Same issue reported by other users

- https://discourse.gohugo.io/t/force-hyphens-in-url/23958

### Seriousness of this regression

I have quite a few pages with double-hyphens.. Double hyphens are used as idea separator in URLs. Here are few examples:

```
posts/deeply-nested-org-todo-headings--h1.md
posts/deeply-nested-org-todo-headings--h2.md
posts/deeply-nested-org-todo-headings--h5.md
posts/deeply-nested-org-todo-headings--h6.md
posts/deeply-nested-org-todo-headings--default-h.md
posts/filling-not-preserved-for-chinese-characters--preserve-filling-off.md
posts/filling-not-preserved-for-chinese-characters--preserve-filling-on.md
```

I link to these pages for references, and now they break because now double-hyphens are auto-reduced to single-hyphens. 

Can the number of hyphens specified by the user in the content file name be preserved?

**Comment by bep** [comment]
>I believe this regression was caused after the switch to Goldmark.

No, I think this is how it has been behaving for several years.

**Comment by kaushalmodi** [comment]
Indeed, this change happened about 1.5 years back in https://github.com/gohugoio/hugo/releases/tag/v0.50 .

Sincere request to allow users to retain their hyphens where they need them.

I only landed up on this today as I was tracing through one of the old ox-hugo tests linked in old issues.

**Comment by kaushalmodi** [comment]
Making the best guess from the changelog.. probably this caused it?: https://github.com/gohugoio/hugo/commit/fae48d7457de96969ec53349194dcbfa45adc269 /cc @moorereason

**Comment by kaushalmodi** [comment]
@bep This can be made a non-breaking fix if the double-hyphens are retained at least when the user has explicitly set the permalinks option to use the `:filename`. Example:

```toml
[permalinks]
  "/" = "/:filename/"
```

Right now, even with this option set, when the file name is `post--with--double--hyphens.md`, the permalink is `/post-with-double-hyphens/`. Can the filename faithfulness be retained with the `:filename` used for permalinks option?

Thanks.

**Comment by kaushalmodi** [comment]
@bep Can you please look at this issue? This one issue is still bugging me.
