### ISSUE TITLE
Goldmark's Typographer extension should be disabled by default

### ISSUE THREAD

**Issue by rgov** [gohugoio/hugo#7289]
Goldmark's Typographer extension, which is intended to change straight quotation marks to "smart" curly quotes, has a number of issues in which it chooses the wrong character, effectively inserting typos into the transformed content. These are not rare edge cases but happen in common text. For instance,

    *The Great Gatsby*'s narrator is Nick Carraway.

transforms into the following, with the quotation mark curled the wrong way. (Hard to see on GitHub, sorry.)

> *The Great Gatsby*&lsquo;s narrator is Nick Carraway.

This can be difficult to catch in a site with thousands of punctuation marks, but it can be a source of embarrassment by making the page look as though it were not proofread.

Moreover, Typographer only attempts to handle punctuation rules for English text, and content in other languages may be corrupted to a greater extent.

The Goldmark maintainer does not have plans to develop Typographer further to address known issues, and has said that the best time to apply the transformation is after HTML has been generated.

The [SmartyPants](https://daringfireball.net/projects/smartypants/) perl script is the original tool for performing these transformations, and it operates on HTML after all shortcodes, etc. have been rendered, rather than on Markdown itself.

My recommendation would be to disable Typographer by default, and offer a way to pass rendered Markdown content through SmartyPants (or another tool) before it is embedded in the template.

**Comment by jmooring** [comment]
See https://github.com/yuin/goldmark/releases/tag/v1.1.31.

This purportedly resolves:
https://github.com/yuin/goldmark/issues/39
https://github.com/yuin/goldmark/issues/127
https://github.com/yuin/goldmark/issues/128
https://github.com/yuin/goldmark/issues/129

**Comment by bep** [comment]
@jmooring thanks for the heads-up. I have updated Goldmark.

I don't agree about this issue. I understand there have been issues, but I still feel that the default settings in Hugo should reflect the end goal and not what fits the situation right now.
