### ISSUE TITLE
Markdown Render Hook for Footnotes?

### ISSUE THREAD

**Issue by maelle** [gohugoio/hugo#7291]
I'd like to be able to use the markdownified content of a footnote as its footnote link title, to make the footnote content accessible on hover without using JavaScript.

I.e. at the moment

```markdown
footnote.[^bla]

[bla]: I am the text of the footnote
```

Will give

```html
 <p>footnote.<sup id="fnref:1"><a href="#fn:1" class="footnote-ref" role="doc-noteref">1</a></sup</p>

<li id="fn:1" role="doc-endnote">
<p>I am the text of the footnote <a href="#fnref:1" class="footnote-backref" role="doc-backlink">&#x21a9;&#xfe0e;</a></p>
</li>
```

And I'd like to get

```html
 <p>footnote.<sup  id="fnref:1"><a title="I am the text of the footnote" href="#fn:1" class="footnote-ref" role="doc-noteref">1</a></sup</p>

<li id="fn:1" role="doc-endnote">
<p>I am the text of the footnote <a href="#fnref:1" class="footnote-backref" role="doc-backlink">&#x21a9;&#xfe0e;</a></p>
</li>
```

I asked about this [in the forum](https://discourse.gohugo.io/t/how-to-add-title-tooltip-with-footnote-content-to-footnote-link/25498) but after reading about [Markdown hooks for headers](https://github.com/gohugoio/hugo/issues/6713) I wondered whether I was looking for a Markdown render hook for footnotes, and whether it might be useful for others. If not, I'll try to hack something else -- and I'm sorry if I missed something in the docs.

**Comment by bep** [comment]
I would say that that needs to be solved in another way.
