### ISSUE TITLE
hugo mod vendor on Windows gets access denied recreating _vendor

### ISSUE THREAD

**Issue by pjeby** [gohugoio/hugo#7303]
With a theme project configured to use modules, `hugo mod vendor` only works if the `_vendor` directory does not already exist.  Otherwise, it deletes the directory and immediately fails with:

```
Error: mkdir E:\Users\pje\projects\libris-hugo\_vendor: Access is denied.
```
If I rerun the command immediately afterwards, it works.  It then fails again the next time the vendor command is run.

On the theory that perhaps this was because the filesystem included the vendor directory, I tried adding `--ignoreVendor`, but this had no apparent effect on the error or its frequency.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.69.2/extended windows/amd64 BuildDate: unknow
</pre>

### Does this issue reproduce with the latest release?
Yes, with:
```
Hugo Static Site Generator v0.71.0/extended windows/amd64 BuildDate: unknown
```
###

**Comment by dante8300** [comment]
Managed to reproduced this with an earlier version 
```
PS C:\Users\dante\Desktop\projects\codemagic-docs> hugo version
Hugo Static Site Generator v0.61.0/extended windows/amd64 BuildDate: unknown
```

**Comment by dante8300** [comment]
Never mind, i just needed to restart, probably my issue is not relevant to the case.

**Comment by jmooring** [comment]
Unable to reproduce:

- Windows 11 (fresh install)
- Hugo v0.124.0
- Go 1.21.4

**Comment by XoL1507** [comment]
one thing, it is posible to recover password my master email of meta. by the way thank you for your understanding..
