### ISSUE TITLE
Hugo crashes if /etc/gitconfig exists, even if it's empty

### ISSUE THREAD

**Issue by gerrywastaken** [gohugoio/hugo#7306]
<pre>
$  hugo version
Hugo Static Site Generator v0.70.0 linux/amd64 BuildDate: 2020-05-13T17:31:37Z
</pre>

When I have any `/etc/gitconfig` hugo crashes, but stops crashing as soon as I rename the file:

<pre>
> cat /etc/gitconfig

> hugo serve -D
Building sites … ERROR 2020/05/23 14:29:36 Failed to read Git log: fatal: unknown error occured while reading the configuration files
Built in 37 ms
Error: Error building site: logged 1 error(s)

> sudo mv /etc/gitconfig /etc/gitconfig_nope

> hugo serve -D

                   | EN  
-------------------+-----
  Pages            | 14  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  4  
  Processed images |  0  
  Aliases          |  1  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 39 ms
Watching for changes in [redacted]/{archetypes,content,data,layouts,static,themes}
Watching for config changes in [redacted]/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/foo/ (bind address 127.0.0.1)
Press Ctrl+C to stop

</pre>

**Comment by davidsneighbour** [comment]
What happens if you run `git log` while having an empty `/etc/gitconfig`? If that one fails you should open a ticket in Git instead of Hugo.

In my local system (Ubuntu 20.04, latest Hugo via Snap) no errors occur. I have a gitconfig with setup, not empty.

**Comment by davidsneighbour** [comment]
I just tested with an empty `/etc/gitconfig` and no error was thrown. You might have to add your git version, file rights and system setup to this issue.

**Comment by gerrywastaken** [comment]
`git log` produces no issues and certainly would have been the thing I noticed first :grin: 

```
>  git version
git version 2.20.1
```

**Comment by gerrywastaken** [comment]
<pre>
> ls -lah /etc/gitconfig
-rw-r--r-- 1 root root 126 mei 22 11:22 /etc/gitconfig
</pre>

**Comment by gerrywastaken** [comment]
I'll try the latest version of hugo just in case.

**Comment by gerrywastaken** [comment]
That's not possible as the latest snap isn't up to date.

@davidsneighbour actually by searching for snap in the issues I found another issue has already reported this so I'm closing this:
https://github.com/gohugoio/hugo/issues/6226
