### ISSUE TITLE
Check Site.LastChange and Home.LasMod

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7310]
See https://discourse.gohugo.io/t/a-way-to-get-last-commit-date-for-the-whole-repo/25665/8

**Comment by jmooring** [comment]
To clarify intent, with `enableGitInfo = true`, the `.Site.LastChange` value will only change if the _content_ changes, correct?

For example, if I modify `.gitignore` and commit the change, `.Site.LastChange` will remain unchanged. Correct? This is what I would expect.

**Comment by bep** [comment]
>value will only change if the content changes, correct?

Yes, the GitInfo is used to set dates to individual files (which then is used to determine `.Site.LastChange`). Only the content files (e.g. `.md`) is considered here.

**Comment by eallion** [comment]
I think all files fetch the last commit is better.
I used a shell script to display the last commit hash in the `footer`.
`GitInfo` does not working well, because `footer` is a global tpl. 

@bep

**Comment by jmooring** [comment]
> .Site.LastChange chould show the most recent non-zero .LastMod

It does.

> .Site.Home.Lastmod will be the same as Site.LastChange if you have no content file [or date] for the home page

It is.

> else it will get that date.

It does.

This works as described.
