### ISSUE TITLE
Render hooks not always called by .RenderString

### ISSUE THREAD

**Issue by Traumflug** [gohugoio/hugo#7312]
v0.71.0, the currently latest version.

----
There are a couple of similar reports about render hooks not called by `.RenderString`, but I think this is another variant.

In hope to make debugging easier, I boiled down my fairly complex site to about the minimum reproducing the issue: [merchants-www-debug.tar.gz](https://github.com/gohugoio/hugo/files/4674162/merchants-www-debug.tar.gz) (1.1 kiB).

I build with `hugo server --gc --renderToDisk`, pages are then http://localhost:1313/pages/test.html (works) and http://localhost:1313/ (doesn't work, text _"render-link.html called!"_ and `target="_blank"` in HTML missing). Visible content of both pages is created by the same template.

**Comment by bep** [comment]
Pretty sure this is fixed by https://github.com/gohugoio/hugo/commit/9698b0dab11f52d52145e85ff71311d2f103cb4e

The current (stupid) workaround is to make sure you do `{{ $tmp := .Content }}` or something before you invoke RenderString.

**Comment by Traumflug** [comment]
Yes, indeed fixed. Thank you so much!
