### ISSUE TITLE
Investigate 0.71.1 template err

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7317]
https://github.com/matcornic/hugo-theme-learn/blob/master/layouts/partials/menu.html#L100
https://discourse.gohugo.io/t/error-in-learn-theme-after-upgrade-from-hugo-0-71-0-to-0-71-1/25816

**Comment by qiwenmin** [comment]
should the line 100 of menu.html be:

```
{{if and .IsSection (or (not .Params.hidden) $.showhidden)}}
```

**Comment by qiwenmin** [comment]
I created a pr. Hope it fixes this issue.

https://github.com/matcornic/hugo-theme-learn/pull/403

**Comment by bep** [comment]
You are right ... Odd that the above didn't fail before.
