### ISSUE TITLE
thead and tbody classes do not appear in hugo_stats.json

### ISSUE THREAD

**Issue by jeromew** [gohugoio/hugo#7318]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.71.1-A301F6B2 windows/amd64 BuildDate: 2020-05-25T09:12:07Z

</pre>

### Does this issue reproduce with the latest release?
yes

It seems that when I add classes on a thead or tbody element, they are not added to the list of classes the appear in hugo_stats.json. Classes added to other elements are discovered as expected.

I could not find in the code where is defined the list of html elements that are navigated during parsing. Could it be that thead and tbody are missing from this list ?

I could not find an explanation to what I observe other than a special case regarding thead and tbody.

when html contains

````html
    <table class="cl1">
    <thead class="cl2"><tr class="cl3"><td class="cl4"></td></tr></thead>
    <tbody class="cl5"><tr class="cl6"><td class="cl7"></td></tr></tbody>
    </table>
````

only `cl1` appears in hugo_stats.json

**Comment by bep** [comment]
I have pushed a fix in a PR. My mistake, it seems that the net/html parser does not handle isolated thead elements etc. I have revised the strategy by just making everything a DIV (but storing the original element tag).

**Comment by jeromew** [comment]
thanks for the quick response. In fact I was going to update the issue it seems it is not related to thead or tbody, but all elements inside table.

With

````html
<table class="cl1">
    <tr class="cl3"><td class="cl4"></td></tr>
    <tr class="cl6"><td class="cl7"></td></tr>
    </table>
````

I also get only `cl1`

**Comment by bep** [comment]
Yes, I saw that -- this should handle it: https://github.com/gohugoio/hugo/pull/7320
