### ISSUE TITLE
resources.PostProcess breaks fingerprinting

### ISSUE THREAD

**Issue by Traumflug** [gohugoio/hugo#7319]
Version 0.71.1.

----
Using example code straight from the [documentation](https://gohugo.io/hugo-pipes/postprocess/) (first code example) ...
```
{{ $css := resources.Get "css/main.css" }}
{{ $css = $css | resources.PostCSS | minify | fingerprint | resources.PostProcess }}
<link rel="stylesheet" href="{{ $css.RelPermalink }}">
```
... fails with:

_[...] execute of template failed: template: partials/head.html:31:25: executing "partials/head.html" at <fingerprint>: error calling fingerprint: *postpub.PostPublishResource can not be transformed_

**Comment by bep** [comment]
>Using example code straight from 

I'm pretty sure that is not the case. PostProcess needs to be the last step in the chain. I use the above construct all the time without issues.

**Comment by Traumflug** [comment]
Thanks. Then I have to investigate closer.

**Comment by Traumflug** [comment]
Got it. Two mistakes at once.
- My build script stashes automatically for production builds.
- `fingerprint` was placed after `PostProcess`.

Sorry for the noise.
