### ISSUE TITLE
Feature request: ESBuild pipeline

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#7321]
[ESBuild](https://github.com/evanw/esbuild) is a very fast JavaScript bundler written in Go. It would be nice if in addition to minifying out of the box, Hugo could also bundle JS files. 

Usage might looks like:

```html
{{ $jsOptions := dict "minify" true "sourceMap" false "module" true }}
{{ $js := resources.Get "js/entrypoint.js" | toJSBundle $jsOptions | fingerprint }}
<script type="module" src='{{ $js.RelPermalink }}'></script>
```

And entrypoint.js could import files in the ES6 style:

```javascript
import { onLoad } from './utils.js';
import myFunc from './my-func.js';

onLoad(myFunc);
```

With all the concatenation and tree shaking happening automatically.

**Comment by bep** [comment]
See https://github.com/evanw/esbuild/issues/152

**Comment by bep** [comment]
How did that project get under my radar? Oh, well, hope the Hugo boss accepts this proposal.

**Comment by carlmjohnson** [comment]
I thought you were the Hugo boss? If it's not you, then is it [him](https://en.wikipedia.org/wiki/Harald_V_of_Norway)?
