### ISSUE TITLE
Possible regression in 0.71.1..."can't give argument to non-function not"

### ISSUE THREAD

**Issue by Houndie** [gohugoio/hugo#7325]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.71.1

</pre>

### Does this issue reproduce with the latest release?
Yes, in fact, it only reproduces with the latest release, 0.70.0 works fine.

Attempted to build my hugo site results in an error in my theme code: 

```
Error: Error building site: failed to render pages: render of "page" failed: "/path/to/project/themes/syna/layouts/_default/baseof.html:10:9": execute of template failed: template: _default/single.html:10:7: executing "_default/single.html" at <partial "helpers/fragments-renderer.html" (dict "page_scratch" .Scratch)>: error calling partial: "/path/to/project/themes/syna/layouts/partials/helpers/fragments-renderer.html:10:9": execute of template failed: template: partials/helpers/fragments-renderer.html:10:9: executing "partials/helpers/fragments-renderer.html" at <(not (isset .Params "slot")) (ne .Params.slot "")>: can't give argument to non-function not (isset .Params "slot")
```

I've opened a ticket with the theme to track progress in case it's a theme issue: https://github.com/okkur/syna/issues/773

However, given that this only occurs with the new version of hugo, this seems like a hugo regression instead, especially given that this is a point release and the release notes don't indicate any other changes.  Looking at the changelog for the latest version and the error message, I think it's possible that [these changes](https://github.com/gohugoio/hugo/commit/6c3c6686f5d3c7155e2d455b07ac8ab70f42cb88#diff-981fbfeb374ac30e53aac700cbc33234L32) (look for file  tpl/internal/go_templates/texttemplate/funcs.go ) have something to do with it, but I'm unsure of what's actually going on there to be sure.

**Comment by Houndie** [comment]
Update:  I was right on the commit, wrong on the specific file change. `c34bf485` does not produce the error, and `6c3c6686` does.  However, rolling back the change to the builtins map that i linked above does not fix the issue.

(which honestly makes sense, I'm not sure why the builtins map becoming a function would change anything anyway :-) )

**Comment by Houndie** [comment]
Offending line is actually the one printing the error message, the check appears to be new.

Not sure if this check is just being overzealous, or if this was always a bug and hugo is just now catching it.

Removal of the following line fixes the issue.

https://github.com/gohugoio/hugo/commit/6c3c6686f5d3c7155e2d455b07ac8ab70f42cb88#diff-1c50b1d5dcb6c2dab26e537fc9112e2bR465

**Comment by bep** [comment]
We have had a similar error report before. And as in that case, I'm pretty sure that this discovered a logical flaw in the template. As: This is a bug fix.

Note that we synch in changes from Go's stdlib, but have not done that in some time. I did it to fix one painful bug, but got this on top.

This is basically yourconstruct

```html
(`{{ if (not (true)) (ne "foo" "bar") }}{{ end }}
```

The above does not make sense.

If you rewrite it to:

```html
(`{{ if and (not (true)) (ne "foo" "bar") }}{{ end }}
```

It executes without error.

**Comment by Houndie** [comment]
Yup, that appears to have been almost exactly it :-D.

Thanks for taking the time to look into this for me.
