### ISSUE TITLE
Syntax highlighting: horizontal scrollbar missing when linenos is inline or false

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#7326]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.71.1/extended linux/amd64 BuildDate: 2020-05-25T13:06:06Z
</pre>

### Does this issue reproduce with the latest release?

Yes

### Problem Description

When highlighting code, if `linenos` is `inline` or `false`, the horizontal scrollbar is not present within the highlighted code. Instead, a horizontal scrollbar appears at the bottom of the browser window.

### To Reproduce the Problem

```bash
git clone --single-branch -b hugo-github-issue-7326 https://github.com/jmooring/hugo-testing hugo-github-issue-7326
cd hugo-github-issue-7326
hugo server
```

**Comment by jmooring** [comment]
Still reproducible.

```
git clone --single-branch -b hugo-github-issue-7326 https://github.com/jmooring/hugo-testing hugo-github-issue-7326
cd hugo-github-issue-7326
hugo server
```

**Comment by mireille-raad** [comment]
One thing that might help is customizing the css yourself for `div.highlight pre`

You can set 
```css
div.highlight pre {
    overflow-x: auto;
} 

```

make sure that you do **NOT** have these properties that make the text wrap.

```css
white-space: pre-wrap;
word-break: break-word;
```

**Comment by jmooring** [comment]
The behavior changed (favorably) in v0.93.0 due to ea54a99ca5c4ed9e66574553f6c057fb83d0aca3. Working as expected with this styling:

```css
.highlight div,
.highlight pre {
  overflow-x: auto;
}
```

Tested with all combinations of `lineNos` and `lineNumbersInTable`.
