### ISSUE TITLE
baseurl with subpath and custom css miss slash in path

### ISSUE THREAD

**Issue by thierrybo** [gohugoio/hugo#7328]
Hugo v0.71.0-06150C87/extended linux/amd64 BuildDate: 2020-05-18T16:15:29Z

```
baseURL = "http://domain/site/"

[params]
    # Custom CSS
    custom_css = ["css/molokai.css","css/custom.css"]
```

here is the generated html :

```
      <link rel="stylesheet" href="/sitecss/molokai.css">
    
      <link rel="stylesheet" href="/sitecss/custom.css">

```

instead of: 

```
      <link rel="stylesheet" href="/site/css/molokai.css">
    
      <link rel="stylesheet" href="/site/css/custom.css">
```
This is more a feature request for "consistency", just to write custom css paths always the same way (no beginning slash) whatever the baseurl is.

**Comment by jmooring** [comment]
@thierrybo This is related to the theme (or custom templates) you are using. Please post this question to the issue queue for the relevant theme. Or, if you are not using a theme, please post this question to the [discussion forum](https://discourse.gohugo.io). In any event, please close this issue. Thanks.
