### ISSUE TITLE
Fatal crash with all configurations of "paired shortcodes"

### ISSUE THREAD

**Issue by Aescetic** [gohugoio/hugo#7329]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.71.1/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

This is the latest release.

### Explanation

"Paired shortcodes" as described [here](https://gohugo.io/content-management/shortcodes), namely:

```
{{% mdshortcode %}}Stuff to `process` in the *center*.{{% /mdshortcode %}}
```

&

```
{{< highlight go >}} A bunch of code here {{< /highlight >}}
```

...Produce a fatal crash identical to the crash described in issue #7322. This issue may also be related to issue #7106.

I've examined the code surrounding shortcodes, and it is clearly very fragile, but the immediate problem can be solved with minor changes.

**Comment by bep** [comment]
There are thousands of "paired shortcodes" in Hugo sites that I somehow manage, and I have yet to experience a crash, so your general statement above isn't true.

Lets take this in #7322.
