### ISSUE TITLE
autoheadingIdType, char in anchor

### ISSUE THREAD

**Issue by kbhawkey** [gohugoio/hugo#7331]
### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version

Hugo Static Site Generator v0.70.0-7F47B99E/extended linux/amd64 BuildDate: 2020-05-06T11:26:13Z
</pre>

### Does this issue reproduce with the latest release?
Have not checked.

The link to a heading contains characters that are not escaped for use as a link.
For example,

```
## What's wrong
```
Auto-generates the link as `what-s-wrong`

If I use a shortcode in the Markdown to generate some localized text,
```
## {{% heading-whatswrong %}}
```
The shortcode looks like,
```
{{- T "heading-whatswrong" -}}
```
Generates the link as `what-39-s-wrong`

I have tried to configure the parser a number of ways.

Using Goldmark parser configured as,
```
[markup]
 [markup.goldmark]
   [markup.goldmark.renderer]
     unsafe = true
  [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "blackfriday"
  [markup.goldmark.extensions]
      typographer = true
```

**Comment by bep** [comment]
>{{- T "heading-whatswrong" -}}

My best guess is that there are some escaping going on.

You could try:

{{- T "heading-whatswrong" | safeHTML -}}

**Comment by kbhawkey** [comment]
Thanks for the reply.
Yes, that works!
As a side note, if I refer to the same shortcode in the file as,
```
## {{< heading-whatswrong >}}
```
The link is:
```
#hahahugoshortcode-s9-hbhb
```
And the link appears in the TOC as that string.

**Comment by kbhawkey** [comment]
Thanks!
/close

**Comment by bep** [comment]
That said, I would probably do:

```html
## {{% heading "whatswrong" %}}
```

Which avoids having to create one shortcode per heading.

**Comment by kbhawkey** [comment]
Good. Just wrote a single shortcode to handle all headings. Thanks.
