### ISSUE TITLE
Emoji are rendered within code and code blocks

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#7332]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.71.1/extended linux/amd64 BuildDate: 2020-05-25T13:06:06Z
</pre>

### Does this issue reproduce with the latest release?
Yes

### Problem Description

Emoji strings with code (single backticks) or code blocks (triple backticks) are rendered to images. They should remain as strings.

By comparison, GitHub does not transform emoji strings when they appear in code.

I came across this problem while trying to document the use of emoji strings. Not very important...

**Comment by maelle** [comment]
Having a way to escape emojis in code as on GitHub (where `:grin:` won't be rendered as :grin:) would be nice indeed.

**Comment by maelle** [comment]
I suppose we can already do that with HTML entities but it's a few more characters to type. :slightly_smiling_face:

**Comment by jmooring** [comment]
Workaround per @maelle: use `&#58;grin&#58;` instead of `:grin:` in your markdown.

**Comment by cobber** [comment]
I just posted [this issue](https://github.com/yuin/goldmark-emoji/issues/3) to [goldmark-emoji](https://github.com/yuin/goldmark-emoji) and was promptly told to come back here :-|

> goldmark is not dedicated for Hugo.
> If you have an issue 'via' Hugo, Please submit issues in Hugo repository.

So here I am :smile:

Here's my original issue:

I have a table full of MAC addresses, some of them containing e.g. `:de:` which gets translated to :de:, even though it is surrounded by back-ticks.

e.g.: *(with fake data)*

| What I See        | What I Expect       |
|-------------------|---------------------|
| ab:cd:01:de:ef:02 | `ab:cd:01:de:ef:02` |

I have wrapped all of the data in backticks, but that has no effect on goldmark, but works here on github.

I have not found any way to disable the emojification, e.g. `\:de:` just adds a `\` before the emoji, `:\de:` disables the emoji, but leaves a spurious `\` in my data, killing copy-pastability.

I'm using goldmark v1.4.4 via Hugo v0.93.0

**Comment by jmooring** [comment]
Either set `enableEmoji = false` in site configuration, or insert a [zero-width space](https://unicode-table.com/en/200B/) between the colon and the string.

**Comment by cobber** [comment]
> Either set `enableEmoji = false` in site configuration, or insert a [zero-width space](https://unicode-table.com/en/200B/) between the colon and the string.

As clever as those solutions might be...
- I don't want to have ***no emojis***, just not in code blocks
- inserting invisible characters does not help when dealing with copy/paste-able data. That would result in data which *looks ok* but is ***silently and invisibly broken***

**Comment by jmooring** [comment]
@cobber Inserting invisible characters is a particularly poor idea. Sorry about that. Seemed like a good idea at the time...

**Comment by jmooring** [comment]
The [yuin/goldmark-emoji](https://github.com/) extension did not exist when emoji support was added to Hugo, and that extension seems to handle these cases as desired. We could retain our `emojify` template function, but replace everything else.

I do not understand what impact that would have on alternate content formats (HTML, adoc, org, etc.).

I'd love to make this somebody else's problem, particularly when the "somebody else" is `yuin/goldmark`. That project is exceptionally well-maintained.

**Comment by bobbygryzynger** [comment]
I worked around this particular issue by leaving emoji rendering off by default and adding an emoji shortcode.

Content:
```
{{< emoji ":+1:" >}}  Everything is A-OK. Carry on!
```

Shortcode (`emoji.html`):
```
{{ .Get 0 | emojify }}
```

**Comment by jmooring** [comment]
I looked into the [yuin/goldmark-emoji](https://github.com/yuin/goldmark-emoji/) extension:

- It has full coverage of [GitHub emojis](https://api.github.com/emojis) (a few gaps will be filled when [#5](https://github.com/yuin/goldmark-emoji/pull/5) is merged).
- Emoji shortcodes in code blocks, fenced code blocks, and inline code are not converted (what this issue is about)
- Adding 5 lines of code (excluding tests/docs) we can do:

```toml
[markup.goldmark.extensions]
emoji = true
```

But this is overridden if `enableEmoji` in the configuration root is `true`, and I think that's OK. We support emoji in markdown (goldmark), org mode, asciidoctor, pandoc, and rst. And we do that by parsing the content _before_ we hand off to the renderer.

So, if you are only using emoji in markdown, the configuration would be:

```toml
enableEmoji = false # default is false

[markup.goldmark.extensions]
emoji = true # default is false
```

So, that's quick to do.

As a second and optional step, we could (perhaps) replace kyokomi/emoji with yuin/goldmark-emoji in [hugo/helpers/emoji](https://github.com/gohugoio/hugo/blob/master/helpers/emoji.go).
