### ISSUE TITLE
feature: could we provide a default template for {{.TableOfContents}}

### ISSUE THREAD

**Issue by hitzhangjie** [gohugoio/hugo#7340]
some themes doesn't provide a good experience in displaying TOC:
- collapsible
- indent
- auto numbering
- scroll if toc too long
...

could we provide a default template for this?
I think it's a little difficult and time consuming to implement this, or find a such theme.

**Comment by gj52** [comment]
a render-toc.html  would be nice.

**Comment by XhmikosR** [comment]
Allowing for ToC customization would allow us to use our scrollspy plugin on our docs. We'd definitely like to see this added :)
