### ISSUE TITLE
Expand redirect support to include dynamically generated _redirects files

### ISSUE THREAD

**Issue by jakejarvis** [gohugoio/hugo#7343]
Love the new local redirects feature. Just a quick thought/request:

Since the syntax is already being advertised as compatible with Netlify's, would it make sense to expand support to include their [`_redirects` files](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file) at the root of the build directory as well?

A lot of sites (including gohugo.io it seems) create it dynamically [as a Hugo layout](https://github.com/gohugoio/gohugoioTheme/blob/master/layouts/index.redir) for nicer HTTP 301/302 aliases instead of the default `<meta http-equiv="refresh" ...>` tags. It's a different syntax than the TOML `[[redirects]]` but it would be nice to cover all the bases and test these locally on top of the config file redirects while we're at it.

**Comment by bep** [comment]
My use case for the new redirect feature is URL rewrites for SPA (or SPA similar stuff), which you kind of have to have running locally to be able to test it. This was a little bit the same with HTTP headers -- setting up security policy header config with no local way of testing it can be a real pain...

So, `_redirects` -- we could do that, but I'm not sure. They are 

1. A little binary in nature, either they work or they don't
2. I'm not too keen on that tight coupling with Netlify ... It kind of made sense in the cases above, but for redirect files there are many variants, ...

**Comment by jakejarvis** [comment]
That's true, I hesitated to use the word "dynamically" for that reason. I'm not all that familiar with SPAs so if there's no use for the `_redirects` file in that world then feel free to close this. :)

**Comment by bep** [comment]
No, it can stay open ... Others may chime in with clever thoughts about this than mine.
