### ISSUE TITLE
Html special characters inside text links

### ISSUE THREAD

**Issue by finex** [gohugoio/hugo#7346]
> Are you using a render hook to rewrite the link? If so, please point me to the code for your render hook.

You're right: I've wrote a custom render template for adding `target="_blank"` on external links but the text was printed using `{{ .Text }}`. I've solved adding `| safeHTML` filter.

**Comment by jmooring** [comment]
I am unable to reproduce the problem with `Hugo Static Site Generator v0.72.0/extended linux/amd64 BuildDate: 2020-05-31T18:10:04Z`

See https://github.com/jmooring/hugo-gh-issue-7346.

**Comment by hawkeye116477** [comment]
I can reproduce that.

For example I write:

`* [I don't care about cookies](abp:subscribe?location=https%3A%2F%2Fwww.i-dont-care-about-cookies.eu%2Fabp%2F&amp;title=I%20don%27t%20care%20about%20cookies)`. then Hugo converts it to  ![2020-06-04_21-25](https://user-images.githubusercontent.com/19818572/83801712-e7641080-a6a9-11ea-8cb6-40b4fc0dd911.png).

**Comment by jmooring** [comment]
I am still unable to reproduce the problem. I added your latest example to <https://github.com/jmooring/hugo-gh-issue-7346>.

Are you using a render hook to rewrite the link? If so, please point me to the code for your render hook.

**Comment by hawkeye116477** [comment]
`Are you using a render hook to rewrite the link? `

Ah, yes, sorry I forgot about it, now is fine :smile:

**Comment by jmooring** [comment]
@hawkeye116477:

Please close this issue. In the future, please post problems such as these to the [Hugo Forum](https://discourse.gohugo.io/).

**Comment by hawkeye116477** [comment]
I didn't opened issue, @finex did that.

**Comment by finex** [comment]
Hi, I simply installed Hugo 0.71 and created a markdown file with the code I've described on the first post. The Hugo settings are the default except for the "unsafe" setting. I will try again with 0.72 on the next days. 😀

**Comment by jmooring** [comment]
I changed config.toml as shown below, and still cannot reproduce the problem.

```
[markup.goldmark.renderer]
unsafe = true
```

**Comment by finex** [comment]
> Are you using a render hook to rewrite the link? If so, please point me to the code for your render hook.

You're right: I've wrote a custom render template for adding `target="_blank"` on external links but the text was printed using `{{ .Text }}`. I've solved adding `| safeHTML` filter.
