### ISSUE TITLE
ref shortcode doesn't work with org files

### ISSUE THREAD

**Issue by fcevado** [gohugoio/hugo#7348]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.69.0/extended linux/amd64 BuildDate: unknow
</pre>

### Does this issue reproduce with the latest release?
didn't tested, i'm using a system wide installation for hugo
https://packages.gentoo.org/packages/www-apps/hugo

if I have a `content/path/to/file.org` and use `{{< ref "path/to/file.org" >}}` it raises with a `REF_NOT_FOUND` error.

**Comment by bep** [comment]
Try to prepend it with a "/".

**Comment by fcevado** [comment]
it doesn't work too... i've already tried with no `path/to/file`, `/path/to/file`, `path/to/file.md`(i don't know if hugo outputs a md file from the org one so i thought it worth the try) and `/path/to/file.md`.

**Comment by bep** [comment]
I'm  not a big org users, so I'll have to ask: Do shortcodes in general work fine?

**Comment by fcevado** [comment]
they work, i've only tested the `gist` one, but since it worked i didn't tested the others. i can test all of them if it helps.

**Comment by bep** [comment]
No, I was just after a confirmation on a binary level.

**Comment by bep** [comment]
OK, I will eventually check. Maybe @niklasfasching can chime in. I don't see why org files should behave differently in this situation.

**Comment by olif** [comment]
As a ugly hack until this is fixed you can refer to the org-file by using `.md` as extension instead of `.org`. (Tested with v0.71.1).

**Comment by niklasfasching** [comment]
No idea :/

**Comment by pmatiash** [comment]
It is working for me on v0.81.
So for `{{ ref . "post/dir1/dir2/b.org" }}` I've got: `http://localhost:1313/post/dir1/dir2/b/`.
Please let me know if I understood the problem incorrectly.

**Comment by fcevado** [comment]
@pmatiash i gonna test with most recent versions.

**Comment by jmooring** [comment]
Unable to reproduce. This works as expected:

```text
[[{{< relref "tests/org-2.org" >}}][Org 2]]
```
