### ISSUE TITLE
Hugo server ignoring baseURL from config.toml

### ISSUE THREAD

**Issue by KalleDK** [gohugoio/hugo#7353]
### What version of Hugo are you using (`hugo version`)?
Tested with latest and two others
<pre>
Hugo Static Site Generator v0.69.2/extended linux/amd64 BuildDate: unknown
Hugo Static Site Generator v0.71.1/extended linux/amd64 BuildDate: unknown
Hugo Static Site Generator v0.72.0-8A7EF3CF linux/amd64 BuildDate: 2020-05-31T12:07:45Z
</pre>

### Does this issue reproduce with the latest release?
Yes

### Steps
<pre>
hugo new site mydomain
cd mydomain
sed -i 's/example.org/mydomain.com/' config.toml
hugo config | grep baseurl
# baseurl = "http://mydomain.com/"
hugo server
# ...
# Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
# ...
hugo server --baseURL="http://mydomain.com"
# ...
# Web Server is available at http://mydomain.com:1313/ (bind address 127.0.0.1)
# ...
</pre>

**Comment by bep** [comment]
This is by design. If you want to use something other than localhost in the dev server, use `--baseURL`.

**Comment by KalleDK** [comment]
Aaah okay. Couldn’t find anything about this in the documentation.

https://gohugo.io/commands/hugo_server/
https://gohugo.io/getting-started/configuration/#all-configuration-setting

Are there other settings ignored by design? So that I can make a PR with it mentioned for future people like me :)
