### ISSUE TITLE
Img Shortcode behavior different after Hugo upgrade from 0.6+ to 0.70.0

### ISSUE THREAD

**Issue by tomott12345** [gohugoio/hugo#7354]
I recently upgraded to Hugo version 0.70.0 from a 0.6 version. I'm on Mac so I used brew to do this. Prior to the upgrade, I was using the following image shortcode to resize my images (source: https://laurakalbag.com/processing-responsive-images-with-hugo/). 

`{{/* get file that matches the filename as specified as src="" in shortcode */}}
{{ $src := .Page.Resources.GetMatch (printf "*%s*" (.Get "src")) }}

{{/* set image sizes, these are hardcoded for now, x dictates that images are resized to this width */}}

{{ $tinyw := default "500x" }}
{{ $smallw := default "800x" }}
{{ $mediumw := default "1200x" }}
{{ $largew := default "1500x" }}

{{/* resize the src image to the given sizes */}}

{{ .Scratch.Set "tiny" ($src.Resize $tinyw) }}
{{ .Scratch.Set "small" ($src.Resize $smallw) }}
{{ .Scratch.Set "medium" ($src.Resize $mediumw) }}
{{ .Scratch.Set "large" ($src.Resize $largew) }}

{{/* add the processed images to the scratch */}}

{{ $tiny := .Scratch.Get "tiny" }}
{{ $small := .Scratch.Get "small" }}
{{ $medium := .Scratch.Get "medium" }}
{{ $large := .Scratch.Get "large" }}

{{/* only use images smaller than or equal to the src (original) image size, as Hugo will upscale small images */}}
{{/* set the sizes attribute to (min-width: 35em) 1200px, 100vw unless overridden in shortcode */}}

<img 
  {{ with .Get "sizes" }}sizes='{{.}}'{{ else }}sizes="(min-width: 35em) 1200px, 100vw"{{ end }}
  srcset='
  {{ if ge $src.Width "500" }}
    {{ with $tiny.RelPermalink }}{{.}} 500w{{ end }}
  {{ end }}
  {{ if ge $src.Width "800" }}
    {{ with $small.RelPermalink }}, {{.}} 800w{{ end }}
  {{ end }}
  {{ if ge $src.Width "1200" }}
    {{ with $medium.RelPermalink }}, {{.}} 1200w{{ end }}
  {{ end }}
  {{ if ge $src.Width "1500" }}
    {{ with $large.RelPermalink }}, {{.}} 1500w {{ end }}
  {{ end }}'
  {{ if .Get (print $medium) }}
    src="{{ $medium.RelPermalink }}" 
  {{ else }}
    src="{{ $src.RelPermalink }}" 
  {{ end }}
  {{ with .Get "alt" }}alt="{{.}}"{{ else }}alt=""{{ end }}>`

I would call the shortcode like this `{{< img="image.jpg" alt="Some alt caption" >}}` and it would process all the images and display them correctly. 

After the upgrade of Hugo, the behavior changed. It would process only the first image and then show the same image for all the other images. For example, if I had in my directory:
- Image1
- Image2
- Image3

It would process only Image1 and show Image1 in place of Image2 and Image3, despite my explicitly calling the shortcode as {{< img="image2.jpg" alt="Some alt caption 2" >}} and {{< img="image3.jpg" alt="Some alt caption 3" >}}

**Comment by jmooring** [comment]
> I would call the shortcode like this `{{< img="image.jpg" alt="Some alt caption" >}}`

Is this a typographical error?

**Comment by tomott12345** [comment]
I checked that, it there was a typo it would throw an error in the dev server. It was working before and I successfully processed several images that would show up exactly where they are called in the markdown post.

**Comment by tomott12345** [comment]
Closing.
