### ISSUE TITLE
Cannot get localised BaseURL (multilingual)

### ISSUE THREAD

**Issue by sergioisidoro** [gohugoio/hugo#7361]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

### Issue
Neither `{{.Site.BaseURL}}` nor `{{ .Site.BaseURL | absLangURL}` returns the localised base URL in single host setup

**Expected behaviour** 
While at `localhost:1313/pt-pt/page_a` clicking  `{{.Site.BaseURL}}` or `{{ .Site.BaseURL | absLangURL}}` should link to `localhost:1313/pt-pt/`

We can configure `baseURL` in the language, as it is documented in the multihost, but that should not be required for the general multilanguage case.

**Comment by bep** [comment]
`baseURL` giives you the value of the `baseURL` config.  When running the server, the story is a little bit longer, but there is no language involved.

If you want to discuss this further, please open a new thread at https://discourse.gohugo.io/

**Comment by sergioisidoro** [comment]
@bep That makes sense, but shouldn't `{{ .Site.BaseURL | absLangURL}}` return the localised BaseURL? https://gohugo.io/functions/abslangurl/

I can open a thread on the discourse tho...
