### ISSUE TITLE
.Site.GetPage doesn't find page

### ISSUE THREAD

**Issue by ArcoMul** [gohugoio/hugo#7362]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.72.0/extended windows/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
yes

---

When creating a new empty project with a new empty theme, when I use the following code in my single.html template, it doesn't print the title of the contact page:
```
  {{ $contactPage:= .Site.GetPage "/contact" }}
  Title: {{ $contactPage.Title }}
```

The structure of my content folder is:

```
content/
  contact/
    index.md
```

Content of index.md:

```
---
title: Contact
---

# Contact
```

Interesting thing is that the title does get printed when I resave index.md (on live reload). When restarting the server, or when building, the title of the page doesn't print though.

Any idea what's going on here?

**Comment by jmooring** [comment]
I am unable to reproduce this behavior. Please post this support question to the [Hugo Forum](https://discourse.gohugo.io/), including a link to the public repository for your site.

**Comment by ArcoMul** [comment]
For whoever arrives here using Google. In my case this was solved by not having a `content/index.md` file, but renaming that file to `content/_index.md`. Why or how I don't know, but it solves it :-)
