### ISSUE TITLE
Digital Asset Links not served

### ISSUE THREAD

**Issue by es0329** [gohugoio/hugo#7363]
### What version of Hugo are you using?
`0.72.0`

### Does this issue reproduce with the latest release?
Yes, atm `0.72.0` _is_ the latest.

### Description
I'm on a quest to use `static/.well-known/assetlinks.json` with hopes of serving it the root of my custom-domain site. However, I'm only able to view the file via browser while running `hugo server`. When I deploy, navigating to that url receives `404`. A [recent release](https://github.com/fishworks/fish-food/pull/740) seemed to contain pertinent work.

**Comment by jmooring** [comment]
I am unable to reproduce this behavior. The file displays as expected while running `hugo server` and after deployment to an Apache virtual host. I suspect it is a configuration issue. Please post this support question to the [Hugo Forum](https://discourse.gohugo.io/), including a link to the public repository for your site.
