### ISSUE TITLE
Ability to throw validation errors in custom shortcodes

### ISSUE THREAD

**Issue by khayyamsaleem** [gohugoio/hugo#7367]
With more complex hugo shortcodes, sometimes input could be validated against a regular expression or against a data source. It would be nice if the implementer of the shortcode could **`"throw"`** their own custom error in the event that:
- an input is not found in a data source (think about how relref fails when the doc path is wrong)
- an input does not match a regular expression (an email field is not populated by an email)
- an input could not be parsed into an expression (invalid date)

I think this could be quite useful and allow for more user-friendly shortcodes that could instruct a documenter on what they could be doing wrong when using a custom shortcode.

**Comment by bep** [comment]
You can use `errorf` -- and if you add `.Position` you will get contextual info about "where".
