### ISSUE TITLE
Markdownify and .Summary sometimes produce an unclosed <p> tag

### ISSUE THREAD

**Issue by AlanLynn** [gohugoio/hugo#7372]
### What version of Hugo are you using?

<pre>
$ hugo version
Hugo Static Site Generator v0.72.0/extended windows/amd64 BuildDate: unknown
</pre>

### To reproduce:

1. Add the following to the top of a content .md file.
```md
+++
summary = """
## Header

Paragraph of text
"""
+++
```
2. View the rendered summary.

### Expected result:

```html
<h2 id="header">Header</h2>
<p>Paragraph of text</p>
```

### Actual result:

The closing `</p>` tag for the paragraph is missing.

```html
<h2 id="header">Header</h2>
<p>Paragraph of text
```

### Additional bug?

When a single line summary is provided, no `<p></p>` tag is rendered at all. It's possible that this is the expected behavior, but it feels incorrect to me. A user could very easily make the following mistake, thinking that paragraph tags would be added in both examples.

```md
summary = """
Single paragraph
"""
```

```md
summary = """
Paragraph 1

Paragraph 2
"""
```

If that is the expected behavior, is there at least a way to ensure that the summary is always processed by markdown?

**Comment by AlanLynn** [comment]
I found the problematic function: `TrimShortHTML` in [helpers/content.go](https://github.com/gohugoio/hugo/blob/9c9987535f98714c8a4ec98903f54233735ef0e4/helpers/content.go#L315)

Commit history:

* April 5, 2019: [hugolib: Consider summary in front matter for .Summary](https://github.com/gohugoio/hugo/commit/3a62d54745e2cbfda6772390830042908d725c71)
* March 27, 2020: [helpers: Fix TrimShortHTML](https://github.com/gohugoio/hugo/commit/9c9987535f98714c8a4ec98903f54233735ef0e4)

But before we think about fixing the `TrimShortHTML` function, can we take a minute to ask: Should the function even exist? What is the purpose of removing `<p></p>` from a single paragraph? To me, that seems like it creates more problems that it solves, but I would like to hear what other people think.

**Comment by AlanLynn** [comment]
Curiously, I noticed that `TrimShortHTML` is also used in the [`Markdownify`](https://github.com/gohugoio/hugo/blob/366ee4d8da1c2b0c1751e9bf6d54638439735296/tpl/transform/transform.go#L110) function. That feels even more presumptive to me.

**Comment by divinerites** [comment]
for mardownify I ended up with this systematic code. I guess you can adapt for summary.
But i agree that is not consistent as a default behaviour.

```
{{ with .Content }}
      {{ $markdown := . | markdownify }}
      {{ if not ( strings.Contains $markdown "<p>" ) }}
            <p>{{ $markdown }}</p>
      {{ else }}
            {{ $markdown }}
      {{ end }}
{{ end }}
```

**Comment by divinerites** [comment]
also see https://github.com/gohugoio/hugo/issues/7069

**Comment by divinerites** [comment]
One of the problem is that .Content and .Summary *are* markdown (see Bep's comment here https://github.com/gohugoio/hugo/issues/2616#issuecomment-255179057).

But when we have **one** line in .Content or in .Summary, there is no <p> tag, so it mess often with our css styles.
So we are driven to use markdownify to have a consistent <p> css behaviour.
Then this problem. 
Then my systematic hack.

**Comment by AlanLynn** [comment]
Clearly I am not the only one frustrated by `markdownify` and `.Summary` producing **sometimes** HTML.

See also:
* #3040
* #6398

The average person expects a function named `markdownify` to do a standard markdown filter. Any behavior other than this should be need to be explicitly configured. It feels very odd to me that we should need to fight for something called `markdownify` to behave as standard markdown. The function is not named `markdownifyExceptSingleParagraphs`.

**Comment by hollowaykeanho** [comment]
Replicate this issue consistently with `markdownify`. 

When feeding the following with ` markdownify $html | safeHTML`:

```
### My Card Title Here
This can be written in Markdown where it will be processed into HTML
automatically.
```

I got a missing `</p>` with its generated HTML output:

```
<h3 id="my-card-title-here">My Card Title Here</h3>
<p>This can be written in Markdown where it will be processed into HTML
automatically.
```

I'm on:
```
Hugo Static Site Generator v0.78.2-959724F0 linux/amd64 BuildDate: 2020-11-13T10:08:14Z
```

**Comment by jpinto3488** [comment]
Running
```
Hugo Static Site Generator v0.80.0-792EF0F4 windows/amd64 BuildDate: 2020-12-31T13:37:57Z
```
I confirm markdownify on a single line text parameter will not wrap the content into `<p></p>`

Having following in front-matter:
```
zone2Content: |-
    Lorem *ipsum* dolor sit amet
```
On the layout I'm doing the following:
```
{{ .Params.zone2Content | markdownify }}
```
The result is:
```html
Lorem <em>ipsum</em> dolor sit amet
```
Expected result would be:
```html
<p>Lorem <em>ipsum</em> dolor sit amet</p>
```

note: if there are multiple lines, the <p> tags are being added correctly. The problem occurs only when there's a single line of content.
