### ISSUE TITLE
Disabling disqus on some pages

### ISSUE THREAD

**Issue by gerrywastaken** [gohugoio/hugo#7373]
I don't wish to display a disqus comments section on non pages that are not posts, such as the privacy policy, terms and conditions, about page etc. I looked at the code but I couldn't see a simple way to do this without adding my own replacement partial. Would Hugo be open to this feature being added if it doesn't currently exist?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by gerrywastaken** [comment]
@bep sorry, this was a proposal for adding this feature. I looked at the Hugo documentation and the source code, did not find anything for this so I'm assuming it doesn't exist. Are you suggesting that I missed this option.

Here is the Hugo documentation for Disqus which doesn't mention anything about being able to disable this per page without creating a partial: https://gohugo.io/templates/internal/#disqus

**Comment by bep** [comment]
> Are you suggesting that I missed this option?

I'm suggesting what I said above.

**Comment by gerrywastaken** [comment]
It really seems like there is a misunderstanding about my request, but fair enough. I really appreciate all the work you have put into Hugo. I've looked through the history and I can see you have been consistently working on this project for years and so I'm very grateful for that. Thank you. :)

For anybody else ending up here, there seems to be no page level param governing the showing or hiding of disqus, only site wide settings. See here: [templates.autogen](https://github.com/gohugoio/hugo/blob/6205d56b85fea31e008cd0fef26805bab8084786/tpl/tplimpl/embedded/templates.autogen.go#L96) and [disqus.html](https://github.com/gohugoio/hugo/blob/6205d56b85fea31e008cd0fef26805bab8084786/tpl/tplimpl/embedded/templates/disqus.html)

However if you are lucky the theme you are using may have added one. The default ananke theme unfortunately [only has a site level config](https://github.com/budparr/gohugo-theme-ananke/blob/91715191544ceb747c78014b8d56c247e73759e4/layouts/_default/single.html#L52) but some [other themes have undocumented page params](https://github.com/qqhann/hugo-primer/blob/35053484e37ce935168d2f6ad24fa75d0398d6a1/layouts/_default/single.html#L36). You should check the **layouts/_default/single.html** file within your theme to see what it has. If it doesn't have one I suggest forking and submitting a MR for it.

I still think it would be better to have a consistent setting within the default disqus template so that this setting is not different on every theme, but at least there is a work around.
