### ISSUE TITLE
Misleading warning during build

### ISSUE THREAD

**Issue by bubelov** [gohugoio/hugo#7377]
### What version of Hugo are you using (`hugo version`)?

0.72.0

### Does this issue reproduce with the latest release?

Yep

A few days ago, I stumbled upon an interesting option which instructs PostCSS to inline imports:

> inlineImports [bool] Default is false. 

> Enable inlining of @import statements. It does so recursively, but will only import a file once. URL imports (e.g. @import url('https://fonts.googleapis.com/css?family=Open+Sans&display=swap');) and imports with media queries will be ignored. Note that this import routine does not care about the CSS spec, so you can have @import anywhere in the file. Hugo will look for imports relative to the module mount and will respect theme overrides.

Which is pretty nice because I wanted to get rid of Hugo extended + Bootstrap with SCSS overrides and experiment with Hugo + vanilla CSS instead. Here is how I use it now and it works like a charm:

```html
{{ $css := resources.Get "css/main.css" | resources.PostCSS (dict "inlineImports" true) | minify | fingerprint }}
<link rel="stylesheet" href="{{ $css.RelPermalink }}">
```

Before, I used PostProcess with a plugin that trimmed Bootstrap a bit and it also worked fine. The problem is, now I see the following warning during Hugo build process:

> You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.

I believe it's not completely true. Yes, I don't use any plugins now but PostCSS isn't useless here and it obviously does something that I need it to do. Assuming I'm not doing something wrong here, I think it would be nice to hide this warning for the users like me who have only this particular use case in mind.

**Comment by davidsneighbour** [comment]
That error message comes directly from PostCSS. It actually starts running and does NOT receive any plugins so it does NOTHING. You might want to just add autoprefixer as a plugin and you will see, that the message disappears. 

You could remove the `resources.PostCSS (dict "inlineImports" true) |` part (remove only one pipe) and no more notices will come. I do not expect an empty config and inlineImports set to true to do anything in PostCSS

**Comment by bep** [comment]
>A few days ago, I stumbled upon an interesting option which instructs PostCSS to inline imports

Just to be clear: The import inlining is performed before the CSS is sent to PostCSS. 

For this particular issue, I suggest you start a thread on the forum.

**Comment by bubelov** [comment]
Well, the doc lists `inlineImports` among PostCSS options so the implementation details seem to be leaking there. Anyway, thanks for a clarification.
