### ISSUE TITLE
VSCode-Consistent alternative to relref

### ISSUE THREAD

**Issue by BoltonBailey** [gohugoio/hugo#7381]
Currently, the standard way of linking to another page within a Hugo website is to use the ref or relref shortcodes. For example with the directory structure
```
content
| - posts
  | - post1.md
  | - post2.md
```
I could have post2.md contain the relref shortcode
```[link]({{<relref "post1.md">}})```

I would like to propose an alternative way of specifying relative links, namely
```[link](./post1.md)```

This has the benefit of working well with the VSCode editor, which will syntax-highlight this correctly, and will allow you to option-click on the link to open the linked file. I think it also meets the [stated purpose of shortcodes](https://gohugo.io/content-management/shortcodes/), namely to avoid the use of raw html and not to contradict the beautiful simplicity of markdown's syntax.

**Comment by jmooring** [comment]
The functionality you describe (syntax highlighting and follow link) would be useful, but should be provided via an extension to Visual Studio Code. Redefining what is rendered by a standard markdown link will be unexpected behavior.

I use [Path Autocomplete for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete) to insert paths, and [Hugo Language and Syntax Support](https://marketplace.visualstudio.com/items?itemName=budparr.language-hugo-vscode) when working on Hugo projects.

Options:

1. Hunt for an existing extension that will do what you want.
2. Look for a relevant extension (.e.g., [Hugo Language and Syntax Support](https://marketplace.visualstudio.com/items?itemName=budparr.language-hugo-vscode)) and submit a pull request.
3. Use a [Markdown Render Hook](https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks).

**Comment by BoltonBailey** [comment]
@jmooring I agree that syntax highlighting and follow link within VSCode should be implemented as a VSCode extension.

I am not sure why you think this proposal redefines standard markdown link behavior. As I see it, what I am proposing *is* standard markdown link behavior. Some references I found [here](https://daringfireball.net/projects/markdown/syntax#link) and [here](https://spec.commonmark.org/0.29/#links) seem to be either ambivalent on, or explicitly allow markdown links to be relative paths.

**Comment by jmooring** [comment]
There are three components of this discussion:

1. Syntax highlighting and following links within Visual Studio Code
2. Relative paths within markdown links
3. How markdown links are rendered

### Item 1

This should be implemented as a Visual Studio Code extension.

### Item 2

Hugo has no problem with relative paths within markdown links; they work as defined in the [CommonMark Spec](https://spec.commonmark.org/0.29/#links).

### Item 3

According to the CommonMark Spec, this markdown:

```md
[foo](./bar.md)
```

must be rendered to HTML as:

```html
<a href="./bar.md">foo</a>
```

If I understand your proposal, you would like this to rendered to something like

```html
<a href="./bar.html">foo</a>    [OR]
<a href="./bar/">foo</a> 
```

When you run `hugo` or `hugo server`, a markdown (.md) file is converted to an HTML file (.html), and the file name and path are controlled by settings in `config.toml` such as [`uglyurls`](https://gohugo.io/content-management/urls/#ugly-urls) and [`[permalinks]`](https://gohugo.io/content-management/urls/#permalinks). Unlike a markdown link, the `relref` shortcode is aware of these settings and performs the relevant transformations to file name and path.

Here's a minimal site to see this in action:

```
git clone https://github.com/jmooring/hugo-github-issue-7381
cd hugo-github-issue-7381
hugo server
```

If you have additional questions about markdown links, please post to the [Hugo Forum](https://discourse.gohugo.io/).

**Comment by BoltonBailey** [comment]
Ok, this makes sense. Thank you for the explanation.
