### ISSUE TITLE
Look for a babel.config.[js/json]

### ISSUE THREAD

**Issue by inwardmovement** [gohugoio/hugo#7382]
Shouldn't Hugo by default look for a [babel.config.json](https://babeljs.io/docs/en/configuration#babelconfigjson) instead of a `babel.config.js`?

(all Babel code examples are in JSON also)

**Comment by bep** [comment]
Here is a babel file of mine:

```js
babel.config.js
module.exports = {
        presets: [
                [
                        '@babel/preset-env',
                        {
                                useBuiltIns: 'entry',
                                corejs: 3
                        }
                ]
        ]
};
```

Which is JS. You can add `console.log` to the above and it will print.
