### ISSUE TITLE
Broken ref in comment causes "ref not found error".

### ISSUE THREAD

**Issue by BoltonBailey** [gohugoio/hugo#7385]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown
</pre>
(I initially was on 0.65.3, then updated and got the same error.)

### Does this issue reproduce with the latest release?
Yes.

Minimal working example:

Start a new site as in the quickstart tutorial
```
hugo new site quickstart
cd quickstart
git init
git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
echo 'theme = "ananke"' >> config.toml
hugo new posts/my-first-post.md
```

Then make the following for content/posts/my-first-post.md
```md
---
title: "My First Post"
date: 2020-06-14T17:04:28-04:00
draft: true
---

This [link]({{<relref "my-first-post.md">}}) works

<!-- This [link]({{<relref "my-nonexistent-post.md">}}) causes the server to fail, even though its commented -->
```

I get the following error

```
[en] REF_NOT_FOUND: Ref "my-nonexistent-post.md": "/Users/boltonbailey/Desktop/test/quickstart/content/posts/my-first-post.md:9:18": page not found
Rebuild failed:

Logged 1 error(s)
Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown

Reload Page
```

**Comment by jmooring** [comment]
Wrapping a shortcode call in HTML comments will hide the output, but will not (as you have learned) skip rendering.

If you want to hide the output _and_ skip rendering:

```html
<!-- {{</* shortcode */>}} -->
```

See:
<https://discourse.gohugo.io/t/how-to-comment-out-shortcodes-in-markdown/14893/10>

Additionally, unless you have set

```toml
[markup.goldmark.renderer]
unsafe=true
```

in `config.toml`, the HTML comment will be rendered as `<!-- raw HTML omitted -->`.

Please post your support questions to the [Hugo Forum](https://discourse.gohugo.io/). Thanks.
