### ISSUE TITLE
hugo version not equal with brew

### ISSUE THREAD

**Issue by fourcels** [gohugoio/hugo#7387]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.50-DEV darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
<pre>
$ brew info hugo
hugo: stable 0.72.0 (bottled), HEAD

$ brew upgrade hugo
Warning: hugo 0.72.0 already installed

$ hugo server
ERROR 2020/06/15 09:35:13 CODEX theme does not support Hugo version 0.50. Minimum version required is 0.72.0
</pre>

**Comment by kevingimbel** [comment]
@fourcels This sounds like an issue with your environment, please run the following in a terminal: 

```
$ which hugo
$ ls -l $(which hugo)
```

If you are using the homebrew version it should look like this

```
$  ls -l $(which hugo)
lrwxr-xr-x  1 kevingimbel  admin  30 Jun 15 09:50 /usr/local/bin/hugo -> ../Cellar/hugo/0.72.0/bin/hugo
```

I assume you have hugo installed elsewhere in your path (e.g. in your `$GOPATH/bin`?)

**Comment by fourcels** [comment]
@kevingimbel Thank you
I have found `hugo` in `$GOPATH/bin`
