### ISSUE TITLE
Error building site: failed to render pages

### ISSUE THREAD

**Issue by chrisdoherty4** [gohugoio/hugo#7390]
### What version of Hugo are you using (`hugo version`)?

Found in 0.71.1

### Does this issue reproduce with the latest release?

Yes

### Overview

Build a site that contains the following index.html layout.

```
{{ define "main" }}

{{ with .Site.GetPage "/posts" }}
{{ range first 5 ((where .Pages ".Params.private" "!=" true) sort .Data.Pages "Date" "desc")}}

{{ end }}
{{ end }}

{{ end }}
```

```
Error: Error building site: failed to render pages: render of "home" failed: "/<projectroot>/pages/layouts/index.html:15:26": execute of template failed: template: index.html:15:26: executing "main" at <(where .Pages ".Params.private" "!=" true) sort .Data.Pages "Date" "desc">: can't give argument to non-function where .Pages ".Params.private" "!=" true
```

This works without issue in 0.71.0 and before. https://github.com/gohugoio/hugo/commit/6c3c6686f5d3c7155e2d455b07ac8ab70f42cb88 seems to introduce the regression but I haven't looked into exactly why.

**Comment by bep** [comment]
It is a bug fix, not a regression, but take any further questions at https://discourse.gohugo.io/
