### ISSUE TITLE
user /tmp/hugo_$USER instead of /tmp/hugo_cache

### ISSUE THREAD

**Issue by qnxor** [gohugoio/hugo#7391]
Using 0.72 compiled from master from 2 days ago on Ubuntu 16.04 with go 1.14. Hugo by default uses /tmp/hugo_cache to store temp files. This is a problem on a multiuser system like ours. For example, one user runs `hugo server` on their project folder. Another user attempt to run `hugo` and fails as it can't write to `/tmp/hugo_cache` being owned by the previous user.

I know it can be overcome by `--cacheDir` but it would be better to have hugo by default use `/tmp/hugo_$USER` instead of the hardcoded `/tmp/hugo` (better never to hardcode things in general anyway). Or make it a random unique dir if it's easier for cross-OS compatibility, making sure gc is doing its job.

**Comment by jmooring** [comment]
You can also do something like this in `~/.bashrc`:

```
export HUGO_CACHEDIR="hugo_cache_$USER"
```

**Comment by qnxor** [comment]
Indeed, and that's perhaps a better workaround than using --cacheDir, but I was advocating that this is best addressed in the default implementation.

**Comment by jmooring** [comment]
> this is best addressed in the default implementation.

Agreed.

**Comment by jmooring** [comment]
Related: https://github.com/gohugoio/hugo/issues/5487

**Comment by jmooring** [comment]
If you don't mind having all of your caches under source control (unless specifically ignored), you can also override the default location in [`config.toml`](https://gohugo.io/getting-started/configuration/#configure-file-caches). If all caches are set to `:resourceDir/_gen`, a `hugo_cache` directory in created in `/tmp` but remains empty. I have no idea if there are negative side effects. I am certain there is a Very Good Reason for placing the caches for getcsv, getjson, and modules in a temporary location outside of the project directory.

**Comment by qnxor** [comment]
That's another useful workaround, thanks. I guess avoiding the repo is just general good practice (folks accidentally adding them to source control and then committing large sets on every commit). I found many hugo themes which do not ignore /resources (but ignore /public).

**Comment by bep** [comment]
If you read https://gohugo.io/getting-started/configuration/#configure-file-caches

There have been some thinking in this area, see the `:project` placeholder.

Some of the caches should be safe to share between users/projects.

**Comment by travier** [comment]
Another option is to use the paths as specified by https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html first and then to default to an hard-coded value.

Quick workaround I used for reference:
```
HUGO_CACHEDIR="${PWD}/.hugo_cache/" hugo ...
```

**Comment by jmooring** [comment]
See https://github.com/gohugoio/hugo/issues/9452 (closed as duplicate) for additional detail.
