### ISSUE TITLE
Fetching Release notes of github in a hugo page (or copy release notes into a docker)

### ISSUE THREAD

**Issue by Adeljoo** [gohugoio/hugo#7396]
I am looking for a way to fetch release notes automatically into a hugo page, then developer can have a look at latest release notes in the website. I use one of the hugo docker to build my website.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
