### ISSUE TITLE
layouts/sitemap.xml first character gets substituted

### ISSUE THREAD

**Issue by lorcalhost** [gohugoio/hugo#7400]
### Describe the bug

When a custom `sitemap.xml` file is present in `/layouts/` the generated `sitemap.xml` files have the first character (`<`) substituted with `&lt;`

### To Reproduce

1. Create a custom `sitemap.xml` file in the `/layouts/` directory
2. Run command `hugo` to build the site
3. See first character of newly generated `sitemap.xml` files

### Expected behavior

`layouts/sitemap.xml` 's content is copied in every built `sitemap.xml` file without the first character being corrupted

### Technical details:

* Hugo Version: v0.72.0-8A7EF3CF
* Browser/OS: Windows 10

Using theme [Academic](https://github.com/gcushen/hugo-academic)

**Comment by bep** [comment]
This is a quirk with Go's templates, and I don't think you will convince them that it's a bug.

See this for a workaround:

https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/sitemap.xml#L1

**Comment by lorcalhost** [comment]
Thanks for the workaround @bep 

Ever since this problem started appearing, something else started happening: when building the website many new random newlines are added to all generated html files, do you happen to know if these things are connected?
