### ISSUE TITLE
Limit `publishResources: false` to images

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#7401]
Hi all!

For most projects I organize media files within `/content/` in corresponding page folder, e.g.

```
content
├─ a-page
│  ├─ index.md
│  ├─ image.jpg
│  └─ audio.mp3
└─ blog
   └─ 2020-06-17-a-post
       ├─ index.md
       ├─ image.jpg
       └─ audio.mp3
```

I would like to remove unprocessed (original) images using

```
cascade:
  _build:
    publishResources: false
```

in `/content/_index.md`.

Yet, also mp3, PDF, SVG and other media files are removed, which probably makes sense as they are unprocessed, too.

Is there a way to remove unprocessed JPG, PNG, and GIF files and keep all other media files?

**Comment by winduptoy** [comment]
@Brixy According to the [build options docs](https://gohugo.io/content-management/build-options/):

> Setting this to false will still publish Resources on demand (when a resource’s `.Permalink` or `.RelPermalink` is invoked from the templates) but will skip the others.

So I've found that the following workarounds will work:
1. Reference the resource's `.RelPermalink` somewhere in your template (maybe loop through all resources and ignore certain file extensions, if that suits your use case).
2. Use the following shortcode:

**layouts/shortcodes/resourcePermalink:**
```
{{ ($.Page.Resources.GetMatch (.Get 0)).RelPermalink }}
```

**in Markdown:**
```
[Download PDF]({{< resourcePermalink "my_document.pdf" >}})
```
