### ISSUE TITLE
"Output Format Definitions" doc lists name (lowercase), not Name (capital)

### ISSUE THREAD

**Issue by RollingStar** [gohugoio/hugo#7402]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.72.0-8A7EF3CF windows/amd64 BuildDate: 2020-05-31T12:08:42Z
</pre>

### Does this issue reproduce with the latest release?

Yes

https://gohugo.io/templates/output-formats/#output-format-definitions

The table at the above link lists a **n**ame, with a lowercase N, but hugo uses a capital N internally.

This works:

```
{{ range .AlternativeOutputFormats -}}yyy
{{ .Name }} <link rel="{{ .Rel }}" type="{{ .MediaType.Type }}" href="{{ .Permalink | safeURL }}">xxx</a>
{{ end -}}
```

![image](https://user-images.githubusercontent.com/4810902/84949007-89c4c080-b0ba-11ea-8c99-4eb84bf386a3.png)

This doesn't:

```
{{ range .AlternativeOutputFormats -}}yyy
{{ .name }} <link rel="{{ .Rel }}" type="{{ .MediaType.Type }}" href="{{ .Permalink | safeURL }}">xxx</a>
{{ end -}}
```

**Comment by RollingStar** [comment]
Still exists

**Comment by jmooring** [comment]
The section of the documentation that includes `name`, `mediaType`, `path`, etc. (camelCase) describes the configuration options. The case is correct.

There's a section further down that page, [List Output Formats](https://gohugo.io/templates/output-formats/#list-output-formats), that provides example template code. The case is also correct.

**Comment by RollingStar** [comment]
Maybe I'm just not doing it right. I found that doc page and I thought it was relevant to my issue. Where should I, as an end user, have learned that the configs are camel case but stuff like .Name is capitalized? If I wanted a list of attributes to work from (like .Name), where would I find that?

**Comment by jmooring** [comment]
@RollingStar Please open an issue in the [documentation repository](https://github.com/gohugoio/hugoDocs). I think what you're asking for is a page [like this](https://gohugo.io/variables/files/) for the Output Format variables.
