### ISSUE TITLE
respectDoNot track should be enabled by default

### ISSUE THREAD

**Issue by gerrywastaken** [gohugoio/hugo#7403]
I've just noticed that the default for `respectDoNotTrack` is false which then leads to the following

https://github.com/gohugoio/hugo/blob/755d1ffe7a22d8ad83485240ff78cf25d501602f/tpl/tplimpl/embedded/templates/google_analytics.html#L34

Which isn't just choosing to do nothing with the visitor's setting, it is overriding it and pretending they set it to false. This doesn't seem like the right default for Hugo to choose. I think it's better for Hugo to respect the visitors setting by default and then allow the site owner to actively choose to ignore this if they wish to take on that risk. But I don't think that should be the default. Thoughts?

**Comment by davidsneighbour** [comment]
Do not track is actually dead: https://en.wikipedia.org/wiki/Do_Not_Track

So disabling it for now and removing in a future version makes sense.

**Comment by gerrywastaken** [comment]
Yeah well, if the position is that it is dead then there should not be any code acting on it. Currently Hugo is acting on it, just in a way to seems to ignore what the user requested by default.

As far as I understand Google Analytics would also have access to this variable and they can decide if it's necessary to respect it. But if Hugo is going to read this value and act on it, then I don't think the right default is to override it.

**Comment by davidsneighbour** [comment]
There is definitely something to be done about it.

**Comment by bep** [comment]
When we added these settings the defaults were aimed at "not breaking things", not "the most private".

**Comment by gerrywastaken** [comment]
I'm trying to think more along the lines of what would be best for the Hugo project. I think swapping the default to true and allowing users to disable it if they wish would be best. Currently, Hugo is making a decision that many users may not even be aware of. I certainly wasn't until I look at the code that was being generated.

I understand what you mean about not breaking things. I think removing this check and leaving the handling of reading and acting on the check to Google, would also achieve this.
