### ISSUE TITLE
Add resources.Put(targetPath)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7406]
See discussion in: https://discourse.gohugo.io/t/babel-ts-file-extension-remains-ts/26318/6

I answered a little hasty in that thread, as I had forgot my own API in this area. For `ToCSS` we have a `TargetPath` option, for babel and postCSS we have not (mostly because, I think, I assumed you would want the same path as the input).

Instead of adding TargetPath to every transformer function that could potentially need it, I suggest we add a `resources.Copy` function that takes the `targetPath` as the only argument. So you could do:

```
{{ $myTypeScript := resources.Get "myjs.js" | babel | resources.Copy "mytypescript.ts" }}
```

Note that a current workaround for the above would be:

```
{{ $js := resources.Get "myjs.js" | babel  }}
{{ $ts := slice $js | resources.Concat "mytypescript.ts" }}

```

@regisphilibert  -- the master of naming things, do you think the above is a good idea and that the function name is good?

**Comment by regisphilibert** [comment]
This is a great idea. Now when I read `Copy` I'm tempted to think I'll end up with duplicates and maybe others will.

Unless it's programatically crazy to use `put` as a method name, I think `.Put` would be a good counter to `.Get` and give a sense that this will define "where" the file will live (is put) when published.

Also, whenever dealing with temporary files (php upload etc...), people are used to `move`. But again, it's still pointing to an action which is not really happening... nothing really gets moved...

**Comment by bep** [comment]
>Now when I read Copy I'm tempted to think I'll end up with duplicates and maybe others will.

You kind of do if you construct it like this:

```
{{ $js := resources.Get "myjs.js" | babel  }}
{{ $ts := $js | resources.Copy "mytypescript.ts" }}
```
I kind of like `.Put`, too, but let it linger.

**Comment by bep** [comment]
Given the discussion above, what would be the best name for this new function:

[![](https://api.gh-polls.com/poll/01EB42SZHSD1R109CAT58RTQ7M/resources.Copy)](https://api.gh-polls.com/poll/01EB42SZHSD1R109CAT58RTQ7M/resources.Copy/vote)
[![](https://api.gh-polls.com/poll/01EB42SZHSD1R109CAT58RTQ7M/resources.Put)](https://api.gh-polls.com/poll/01EB42SZHSD1R109CAT58RTQ7M/resources.Put/vote)

**Comment by jmooring** [comment]
Addressed by https://github.com/gohugoio/hugo/pull/9920
