### ISSUE TITLE
Open Browser after the server has started

### ISSUE THREAD

**Issue by Lunchb0ne** [gohugoio/hugo#7410]
When serving, for testing have an option to automatically open the browser. This would be a very nice to have feature.

I can start working on this ASAP

**Comment by bep** [comment]
This has been discussed before.

**Comment by Lunchb0ne** [comment]
It _is_ possible to do this without a dependency, I saw that maintaining tests and other things in the build chain was your main gripe.

**Comment by bep** [comment]
Can you post a link to the issue so I can have a look at what "my gripe was"?

**Comment by Lunchb0ne** [comment]
[This one](https://github.com/gohugoio/hugo/issues/5595#issuecomment-453427406)

**Comment by mireille-raad** [comment]
will this launch a new instance of the default browser or will it open a new tab?

**Comment by Lunchb0ne** [comment]
It'll open a new tab if the browser is already opened.

**Comment by korney4eg** [comment]
why not create a wrapper for it like
```bash
hugo server &
open localhost:1313
```

with whatever configuration you like?
