### ISSUE TITLE
Incremental Build For Production Build

### ISSUE THREAD

**Issue by goldcoders** [gohugoio/hugo#7412]
Hi Is there a way we can Implement an Incremental build which Speed up deployment process

On For Example Netlify / Vercel or any other third party Hosting Site....

Build Time Increases As Number of Content Increases....

So I think It is Better For Production to Have a Incremental Build....

Instead of Rebuilding the Whole Site , and All Contents...

Hugo Will  Just Build One Page if Only One Page Has Changed...

**Comment by bep** [comment]
Yes, but I'm pretty sure this has its own issue(s) somewhere.
