### ISSUE TITLE
styling code in shortcodes creates whitespaces that mess-up html

### ISSUE THREAD

**Issue by mireille-raad** [gohugoio/hugo#7418]
I am creating a shortcode that reads code from a [jupyter notebook](https://jupyter.org/) and displays it in a hugo theme.

I am using vscode as my code editor.

If I use new lines or tabs or spaces in my code, this results in a lot of whitespace in the rendered html... this messes up the rending. 

This is best explained in a screenshot.

## code: 
<img width="424" alt="Screen Shot 2020-06-22 at 4 13 41 PM" src="https://user-images.githubusercontent.com/521705/85331329-f1588280-b4a3-11ea-8246-2ceb24b088f7.png">

## White-spaces in the html

<img width="426" alt="Screen Shot 2020-06-22 at 4 14 47 PM" src="https://user-images.githubusercontent.com/521705/85331363-ff0e0800-b4a3-11ea-8d99-83ce2837856f.png">

<img width="183" alt="Screen Shot 2020-06-22 at 4 15 04 PM" src="https://user-images.githubusercontent.com/521705/85331371-02a18f00-b4a4-11ea-9ff4-d05848c5446c.png">

Notice how the pattern matches the code.

The only way to get rid of the spaces, is to have everything on one line, which makes the code impossible to read, even with line wraps on.

If I put things in ONE line of code 

<img width="1296" alt="Screen Shot 2020-06-22 at 4 12 21 PM" src="https://user-images.githubusercontent.com/521705/85331679-8eb3b680-b4a4-11ea-889d-229eb58a131a.png">

It renders correctly 
<img width="1005" alt="Screen Shot 2020-06-22 at 4 23 27 PM" src="https://user-images.githubusercontent.com/521705/85331781-c28edc00-b4a4-11ea-832e-23324f26b81c.png">

as opposed to the previous case where it was rendering tons of empty lines 

<img width="994" alt="Screen Shot 2020-06-22 at 4 13 56 PM" src="https://user-images.githubusercontent.com/521705/85331838-df2b1400-b4a4-11ea-861e-c0d51b102f84.png">

I feel we should be able to style code in shortcodes without create whitespaces in html. is there a way around this? 

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.69.0/extended darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
You can remove whitespace around your templating code with this notation:

```
{{- foo -}}
```

See <https://gohugo.io/templates/introduction/#whitespace>.

We have an active [discussion forum](https://discourse.gohugo.io) where users and developers can ask questions. Please don't use the GitHub issue tracker to ask questions.

**Comment by mireille-raad** [comment]
🤦 *facepalm*

Thanks for hint! this was in the introduction, not sure how I missed it!
