### ISSUE TITLE
Add front matter hidden: true option?

### ISSUE THREAD

**Issue by joethorley** [gohugoio/hugo#7419]
I frequently find myself producing draft pages (that may or may not be posts) that I share with collaborators to review prior to making public by sharing the link to the page with them. The draft information is not sensitive enough to be password protected (which is a pain but I do when necessary) however in order to avoid confusing people I still like those pages to be hidden in the sense that someone can't find them by searching online or on my Hugo site or looking at the sitemap etc. 

I am using the hugo-academic theme 

https://github.com/gcushen/hugo-academic 

and have customized several key files including 404.html, index.json, sitemap.xml and partials/custom_head.html to achieve the desired results.

When I asked the maintainer of hugo-academic (@gcushen) if he was interested in incorporating into the theme he suggested I contact you directly 

https://github.com/gcushen/hugo-academic/pull/1741#issuecomment-646664318

Is Hugo interested interested in incorporating this functionality? Note I am not sufficiently to proficient to make a pull request but would be happy to input to the process.

**Comment by jmooring** [comment]
Please look at front matter [Build Options](https://gohugo.io/content-management/build-options/).

We have an active [discussion forum](https://discourse.gohugo.io) where users and developers can ask questions. Please don't use the GitHub issue tracker to ask questions.

**Comment by joethorley** [comment]
Apologies - I have reread the Build Options and when I am next updating my website will play with them to understand their behaviour more fully.
