### ISSUE TITLE
Creating an official IRC #hugo channel on Freenode

### ISSUE THREAD

**Issue by lord-re** [gohugoio/hugo#7421]
We (some irc users) would like to have an official Hugo channel on Freenode.
For now there is two channel ( #hugo and ##hugo ).

Following Freenode guidelines, channels with only one # should be official and should be affiliated with their project.
As the channel is (for now at least) unofficial it's not perfectly clean and it could be deleted.
That's why there is a second channel (##hugo).

The IRC community is splitted between these two channels, having only one would be better for the project and for random irc users.

To make it official **one of the gohugo representative ( @spf13 or @bep ) would have to agree on making it official and naming someone to take care of the channel**.

> 21:29:04     Lord │ I wanted to gather some information now with you then open an issue on their github explaining how to do it
> 21:29:13        @e │ well, they'll need a representative on irc
> 21:29:34     Lord │ dumb question : how will you know they truly are representative ?
> 21:29:59     Lord │ they are 2 main devs
> 21:30:35        @e │ in this case if you opened an issue ideally they'd say "we want X to represent us to freenode" and then we'd read that
> 21:31:09      Lord │ ok thank you :-)

Thank you for considering this request.

If you are ok, you'll have to send an email to freenode (i can provide the address, or you can reach #freenode on irc.freenode.net).

edit : just found this gist mentionning what's required : https://gist.github.com/AbstractBeliefs/f82487dc7d7db54d7c94740c25c08084

**Comment by jmooring** [comment]
My initial reaction: I think it is better to have one knowledge base, not two.

**Comment by rawtaz** [comment]
Please note that for there to be an official #hugo channel, the official project owners/maintainers wouldn't have to actually be active in *managing* the channel - this can be done by assigned operators like @lord-re and even myself if need be (I'm not very active though, just hanging out after building one single Hugo site) - but the maintainers which will be registered as the *founders* of the channel must be contactable in case the operators need assistance with some configuration of the channel.

**Comment by rawtaz** [comment]
> My initial reaction: I think it is better to have one knowledge base, not two.

Yeah. That's why we're suggesting merging #hugo and ##hugo :)

**Comment by rawtaz** [comment]
This issue still needs direction from project representatives.

**Comment by spf13** [comment]
Happy to support this. I don't spend time on IRC anymore. Would need @bep
or community members to moderate.
