### ISSUE TITLE
analytics: Disable GA on localhost

### ISSUE THREAD

**Issue by alexandrevicenzi** [gohugoio/hugo#7422]
### Problem

Built-in templates for Google Analytics are enabled on localhost, aka development server.

### Solution

Disable GA templates as done in Disqus if localhost is detected.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.71.1
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by alexandrevicenzi** [comment]
I'm more than happy to send a patch fixing this, as long as someone says it's ok to do so.

**Comment by jmooring** [comment]
I think you accomplish this with configuration settings. See <https://gohugo.io/getting-started/configuration/#configuration-directory>.

```txt
├── config
│   ├── _default
│   │   └── config.toml
│   ├── development
│   │   └── config.toml
│   └── production
│       └── config.toml
```

config/_default/config.toml:

```toml
googleAnalytics = ""
```

config/production/config.toml
[production]
googleAnalytics = ""

[production]
googleAnalytics = "your-code-here"

**Comment by moorereason** [comment]
I'm sure _someone_ is running hugo locally behind a proxy in a production environment.  While we don't recommend that setup, this feature request would break that setup.  I'd prefer to see you use the existing configuration options mentioned above by @jmooring.

**Comment by davidsneighbour** [comment]
That needs some documentation I think at the place of the analytics documentation. At least a little notice :)

**Comment by jmooring** [comment]
Actually, it's easier than I originally proposed. Two methods:

1. Conditionally include the template in `baseof.html` or wherever:

   ```html
   {{ if not .Site.IsServer }}
     {{ template "_internal/google_analytics.html" . }}
   {{ end }}
   ```

2. The template will not be rendered if `googleAnalytics` is not present in `config.toml`. So...

   ```txt
   ├── config
   │   ├── _default
   │   │   └── config.toml
   │   └── production
   │       └── config.toml
   ```

   config/_default/config.toml:

   ```toml
   # googleAnalytics = "your-live-code-here" (or eliminate the entry)
   ```

   config/production/config.toml:

   ```toml
   googleAnalytics = "your-live-code-here"
  ```

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
