### ISSUE TITLE
Manual summary split includes HTML in org mode

### ISSUE THREAD

**Issue by shlevy** [gohugoio/hugo#7423]
Given:

```org
#+TITLE: test-post

Here is a test with a [[http://example.com][link]].

How will splitting behave?
```

I get this as the `.Summary`:

```html
Here is a test with a link.  How will splitting behave? 
```

If I change it to this:

```org
#+TITLE: test-post

Here is a test with a [[http://example.com][link]].

# more

How will splitting behave?
```

I get:

```html
<p>
Here is a test with a <a href="http://example.com">link</a>.
</p>
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.72.0/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Unknown (`0.73` just released).

**Comment by shlevy** [comment]
@chaseadamsio Do you still work on org-mode support?

**Comment by niklasfasching** [comment]
Works as documented [here](https://gohugo.io/content-management/summaries/#manual-summary-splitting)

> Content that comes before the summary divider will be used as that content’s summary and stored in the .Summary page variable with all HTML formatting intact.

And markdown behaves the same. It's not an org mode bug, though. I understand the confusion though - didn't expect that either. 

Related: https://discourse.gohugo.io/t/hugo-post-summary/20698/5

**Comment by shlevy** [comment]
Interesting! Definitely confusing behavior, but works as expected I suppose. Will close this, I can do explicit summaries for my use case.
