### ISSUE TITLE
0.53.0-relnotes does not exist

### ISSUE THREAD

**Issue by a-p-o** [gohugoio/hugo#7432]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.73.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes.

It seems the [docs/content/en/variables/site page][1] is referring to a page that does not exist.

On line 25, `0.53.0` is used instead of `0.53`. So, the reference becomes `https://gohugo.io/news/0.53.0-relnotes/` instead of [`https://gohugo.io/news/0.53-relnotes/`][2].

I have not checked, but I suspect other relnotes links may be broken.

[1]: https://github.com/gohugoio/hugo/blob/master/docs/content/en/variables/site.md#L25
[2]: https://gohugo.io/news/0.53-relnotes/

**Comment by jmooring** [comment]
Please close this. Created issue in docs repo (https://github.com/gohugoio/hugoDocs/issues/1161).
