### ISSUE TITLE
Language code in resource filename kept in RelPermalink

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7437]
As in the example below:

```bash
index.md
style.en.css
style.fr.css
```

The language indicators tells Hugo what language/site they belong to, but currently these would be published to `https://example.com/style.en.css` and `https://example.com/style.fr.css`.

The above was never intended, and probably the reason why we did not discover #7436

**Comment by dryscord** [comment]
Is this also why my images in page bundles show up as  e.g. `image.fr.jpg`?

**Comment by gunponteet** [comment]
Will this be available in the next version?

**Comment by bep** [comment]
I'm closing this issue for now. This is unfortunate, but these resources (esp. images) needs to have URLs that's ... guessable/portable.
