### ISSUE TITLE
Duplicate Time Zone Offset in Hugo for PublishDate.Format

### ISSUE THREAD

**Issue by richardboydii** [gohugoio/hugo#7438]
Hugo creates a double-entry for Time zone.

Following code: 

Site Updated: {{ .PublishDate.Format "2006.02.01 15:04-0500" }}

Results in: 

Site Updated: 2020-06-28 12:55:13 -0500 -0500

### What version of Hugo are you using (`hugo version`)? 0.73

Hugo Static Site Generator v0.73.0-428907CC linux/amd64 BuildDate: 2020-06-23T16:30:43Z

<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
Unable to reproduce with the information provided here or in https://github.com/gohugoio/hugo/issues/5907. Please create a topic in the [discussion forum](https://discourse.gohugo.io), and post a link to the public repository for your site, or a minimal example site where you can consistently reproduce the problem.

Additionally, the date format string that you provided is incorrect. The timezone offset is represented by -0700. See <https://gohugo.io/functions/format/#gos-layout-string>.

**Comment by retifrav** [comment]
There is already [a post](https://discourse.gohugo.io/t/front-matter-datetime-duplicated-timezone-value/17853) in the discussion forum about that, I created it along with the #5907.

Good idea about adding a minimal example website to reproduce the issue, I've just [created one](https://github.com/retifrav/hugo-timezone-duplicate). Also wrote a bit more detailed [comment](https://github.com/gohugoio/hugo/issues/5907#issuecomment-651131206) in the original issue.

**Comment by carlmjohnson** [comment]
` {{ .PublishDate.Format "2006.02.01 15:04-0500" }}` is formatted incorrectly. 05 refers to seconds in the Go magic date format. The timezone is 07.

**Comment by carlmjohnson** [comment]
Site Updated: {{ .PublishDate.Format "2006.02.01 15:04-0500" }} Is wrong. In Go, the timezone is -0600. 5 is the number of seconds.
