### ISSUE TITLE
Alternate Shortcode for youtube-nocookie

### ISSUE THREAD

**Issue by jwhevans** [gohugoio/hugo#7441]
YouTube offers a privacy-enhanced embed for GDPR compliance. Links are made against youtube-nocookie.com instead of youtube.com. Using YouTube-nocookie.com stops an HTTP cookie from being sent. I think this would be a nice option/addition to the standard shortcodes.

**Comment by bep** [comment]
I think we already do that if you enable 
https://gohugo.io/about/hugo-and-gdpr/#youtube

**Comment by jwhevans** [comment]
Thanks bep. You are correct. I tested this on my site and it does build the embed to youtube-nocookie.
