### ISSUE TITLE
Support inline partials

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7444]
This is currently not possible:

```
{{ $v := partial "foo" . }}

{{ define "partials/foo" }}
Partial
{{ end }}
```

You can use the `template` syntax, but that does not support assigning the result to a variable ...

**Comment by pamubay** [comment]
Amazing!! :confetti_ball: 

i use `define` and `template` a lot. 
The inability to assign the result into variable, 
in some cases it forces me to write a partial file even though the code is quite small. :disappointed: 

Thanks for your work. :partying_face:

**Comment by bep** [comment]
Yes, I think this will be a welcomed addition for many. It will look like this:

```go-html-template
Value: {{ partial "my-inline-partial" . }}

{{ define "partials/my-inline-partial" }}
{{ $value := 32 }}
{{ return $value }}
{{ end }}
```

/cc @regisphilibert
