### ISSUE TITLE
Shortcode for AMP output not rendered on the fly

### ISSUE THREAD

**Issue by coldeaclaudia** [gohugoio/hugo#7448]
AMP shortcode isn't rendered unless Hugo is restarted.

<pre>
Hugo Static Site Generator v0.73.0-428907CC windows/amd64 BuildDate: 2020-06-23T16:32:10Z
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.14.3"
</pre>

config.toml

```
[outputs]
page = ["HTML", "AMP"]
```

MD post

`{{< figureimage src="/images/blog/blah.jpg" alt="Blah" href="https://blah.com/" site="blah.com" url="https://blah.com/" width="640" height="427" >}}`

figureimage.html

`<figure><img src="{{.Get `src`}}" alt="{{.Get `alt`}}"><figcaption>Photo by <a href="{{ .Get `href` }}" target="_blank" rel="noopener noreferrer">{{ .Get `alt` }}</a> on <a href="{{ .Get `url` }}" target="_blank" rel="noopener noreferrer">{{ .Get `site` }}</a></figcaption></figure>`

figureimage.amp.html

`<amp-img src="{{.Get `src`}}" alt="{{.Get `alt`}}" width="{{.Get `width`}}" height="{{.Get `height`}}"></amp-img>`

**Comment by bep** [comment]
>AMP shortcode isn't rendered unless Hugo is restarted.

Are you saying that it only shows the second time you start the server? Or do you mean that _changes to the shortcode_ does not show unless it's restarted?

If It's the latter, I thought we had tests for  that...

**Comment by coldeaclaudia** [comment]
> Or do you mean that _changes to the shortcode_ does not show unless it's restarted?

This one.

**Comment by jakejarvis** [comment]
I can confirm this — doesn't even trigger the live reload for me. Will test out the PR when it's merged and report back. :)

**Comment by bep** [comment]
I apologise for this. This used to work, but I broke it when making this "template dependency change" graph thing more general, which I guess all in all will be a good thing. On step forward.

**Comment by jakejarvis** [comment]
No worries at all, it now works perfectly for me on AMP templates so thanks! 👍
