### ISSUE TITLE
/static/.htaccess changes not detected by `hugo -w` but seen by `hugo`

### ISSUE THREAD

**Issue by qnxor** [gohugoio/hugo#7450]
This is on Linux with hugo 0.72 compiled from master about a week ago. I placed a .htaccess file in /static/.htaccess. I have a `hugo -w` process running which is working fine to detect all changes made to .md, .css or other files.

If I make changes to this .htaccess file in /static then `hugo -w` doestn't detect any changes. However, if I kill the `hugo -w` process and then launch it again (or launch it without `-w`) then the changed .htaccess is pushed to /public.

Sounds like a bug rather than expected behavior. Perhaps it's ignoring files whose name start with `.` when it shouldn't?

**Comment by dotjay** [comment]
+1

I've just experienced this same issue. It appears that Hugo doesn't watch for changes to dot files like `.htaccess`

**Comment by davidsneighbour** [comment]
In what scenario would the Hugo development server require to watch `.htaccess` files?

**Comment by dotjay** [comment]
I'm running a Hugo site with [site.js](https://sitejs.org/), which has [built-in deployment sync support](https://github.com/small-tech/site.js/blob/master/README.md#sync). Since I'm running my generated content on an Apache server, I use `static/.htaccess` to ensure that my generated content syncs my changes to `.htaccess` to my production server.

**Comment by bep** [comment]
So, in the change watcher I think we ignore changes to `.` files, mostly for a good reason (we could probably be smarter about this). But I'm pretty sure they're still copied to /public, which is what you want.

**Comment by jmooring** [comment]
Both `hugo server` and `hugo -w` copy the `.htaccess` file to the public directory as expected.

Neither `hugo server` nor `hugo -w` detects changes to the `.htaccess` file. This is intentional.
