### ISSUE TITLE
Infinite reload without changes

### ISSUE THREAD

**Issue by Ikedia** [gohugoio/hugo#7454]
Hello, everyone!
After I've upgraded to the latest version. I have continuous reloading of the site after running **hugo server**
I've downgraded to my previous version but issue still here. Also building became too slow.
After I make changes to my files it pasts few seconds, before **"Change detected, rebuilding site."** appears. With no address of changed file. After first change, there is non stop reloading each 1-2 seconds, even I made no changes.

Any ideas why it happens? Haven't found anything helpful.

Thanks for the time spent.

**MacOS Catalina 10.15.5 (19F101)**

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.61.0
$ hugo version 0.73.0
</pre>

### Does this issue reproduce with the latest release?
yes

```
hugo server

                   |  EN
+------------------+------+
  Pages            |    8
  Paginator pages  |    0
  Non-page files   |    0
  Static files     | 1444
  Processed images |    0
  Aliases          |    0
  Sitemaps         |    1

  Cleaned          |    0

Built in 4514 ms
Watching for changes in /Users/.../git-projects/mnc/mnc/{archetypes,assets,content,static,themes}
Watching for config changes in /Users/.../git-projects/mnc/mnc/config.yml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

Change detected, rebuilding site.
2020-07-03 16:00:06.277 +0300
Rebuilt in 2408 ms

Change detected, rebuilding site.
2020-07-03 16:05:20.190 +0300
Rebuilt in 1201 ms

Change detected, rebuilding site.
2020-07-03 16:05:26.194 +0300
Rebuilt in 1233 ms
```

**Comment by davidsneighbour** [comment]
Can you maybe run hugo with `-v, --verbose verbose output` so we can see if there is any additional output then? I had an IDE doing code optimization once in the background and that "touched" all files which resulted in them being "changed".

**Comment by Ikedia** [comment]
@davidsneighbour sure here it is 
```
hugo -v
INFO 2020/07/03 16:45:41 No translation bundle found for default language "en"
INFO 2020/07/03 16:45:41 Translation func for language en not found, use default.
INFO 2020/07/03 16:45:41 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the s
ite language or the default language.
INFO 2020/07/03 16:45:41 Using config file:
Building sites … INFO 2020/07/03 16:45:41 syncing static files to /Users/.../git-projects/mnc/mnc/public/

                   |  EN
+------------------+------+
  Pages            |    8

  Paginator pages  |    0
  Non-page files   |    0
  Static files     | 1444
  Processed images |    0
  Aliases          |    0
  Sitemaps         |    1
  Cleaned          |    0

Total in 4155 ms
```

**Comment by davidsneighbour** [comment]
`hugo server --verbose` ;) that's where it reloads infinitely.

**Comment by davidsneighbour** [comment]
Also, you have two versions of hugo in your description... which one is running when you run `hugo server`? 0.73.0 or 0.61.0?

**Comment by Ikedia** [comment]
Oh, sorry :) Now running 0.61.0. The problem is that I've changed nothing to config. Only updated version to latest and as I remember it worked yesterday, but not today.

```
hugo server --verbose
INFO 2020/07/03 16:49:57 No translation bundle found for default language "en"
INFO 2020/07/03 16:49:57 Translation func for language en not found, use default.
INFO 2020/07/03 16:49:57 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the s
ite language or the default language.
INFO 2020/07/03 16:49:57 Using config file:
Building sites … INFO 2020/07/03 16:49:57 syncing static files to /

                   |  EN
+------------------+------+
  Pages            |    8
  Paginator pages  |    0

  Non-page files   |    0
  Static files     | 1444
  Processed images |    0
  Aliases          |    0
  Sitemaps         |    1
  Cleaned          |    0

Built in 3488 ms
Watching for changes in /Users/.../git-projects/mnc/mnc/{archetypes,assets,content,static,themes}
Watching for config changes in /Users/.../git-projects/mnc/mnc/config.yml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

Change detected, rebuilding site.
2020-07-03 16:50:48.625 +0300
INFO 2020/07/03 16:50:48 No translation bundle found for default language "en"
INFO 2020/07/03 16:50:48 Translation func for language en not found, use default.

INFO 2020/07/03 16:50:48 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the s
ite language or the default language.
INFO 2020/07/03 16:50:48 Using config file:
INFO 2020/07/03 16:50:48 syncing static files to /
Rebuilt in 2193 ms

Change detected, rebuilding site.
2020-07-03 16:50:55.619 +0300
INFO 2020/07/03 16:50:55 No translation bundle found for default language "en"
INFO 2020/07/03 16:50:55 Translation func for language en not found, use default.
INFO 2020/07/03 16:50:55 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the s
ite language or the default language.
INFO 2020/07/03 16:50:55 Using config file:
INFO 2020/07/03 16:50:55 syncing static files to /
Rebuilt in 1168 ms
```

**Comment by davidsneighbour** [comment]
It's interesting that it's syncing static files on each iteration. I would think that it's there where something "unkosher" is going on. Are you sure nothing (anti virus, backup scripts, open editor) is accessing these files in the static directory?

On linux I would run `lsof +r10 | grep '/path/to/the/static/dir/` to see if a process is touching a file in that folder. 

I am not sure how to check on a Mac what process is using/writing/reading a file, maybe the following link will help:

https://serverfault.com/questions/315091/find-out-which-process-is-writing-into-a-specific-directory

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
