### ISSUE TITLE
Add versioned formulaes at Homebrew so more versions of Hugo could be available 

### ISSUE THREAD

**Issue by chow1026** [gohugoio/hugo#7456]
Hi,

I have recently switched to a new MacOS machine and am setting up Hugo from scratch along with [the Academic theme](https://sourcethemes.com/academic/). 

I took the typical Hugo installation step for MacOS, via Homebrew. Homebrew only keeps the one main version of the formulae of Hugo, currently the latest release of Hugo (v0.73.0).  This release however doesn't work with the last stable version of [Academic theme v4.8.0](https://sourcethemes.com/academic/updates/v4.8.0/).  In fact, I had to go back till Hugo release v0.70.0 for it to work. This version however is not available on brew as versioned formulae. 

Since Hugo releases are done quite frequently, and the themes usually takes some time to adopt to the the newer releases. Would it make sense to have it as versioned formulaes like [PHP](https://github.com/Homebrew/homebrew-core/search?q=php&unscoped_q=php) or [PostgreSQL](https://github.com/Homebrew/homebrew-core/search?q=php&unscoped_q=postgresql) does as part of the Homebrew-core?

**Comment by bep** [comment]
>Would it make sense to have it as versioned formulaes like PHP or PostgreSQL does as part of the Homebrew-core?

What do they do?

**Comment by chow1026** [comment]
I actually had submitted a couple PRs for those versions, [v0.72.0](https://github.com/Homebrew/homebrew-core/pull/57332) and [v0.70.0](https://github.com/Homebrew/homebrew-core/pull/57334).  The reviewers posted some questions, some I was able to clear, some I need support from you. 

- There need to be a clear public statement on Hugo website/documentation about support for older versions, something like [PHP](https://www.php.net/supported-versions.php) and [PostgreSQL](https://www.postgresql.org/support/versioning/). 
- There need to be a branch for the release version 0.70.0. For some reason it is only a tag. You may see the comment regarding this [here](https://github.com/Homebrew/homebrew-core/pull/57334#issuecomment-653738381). 

You may follow the PR links above for details and comment directly. 

Thank you! 

PS: I had skipped Hugo v0.71.1 because it didn't work for me and I thought to try out the Homebrew PR workflow first. If you would like for me to create the brew formulae for v0.71.1 and submit a PR, I am happy to do that.

**Comment by bep** [comment]
>There need to be a branch for the release version 0.70.0.

That is not something we can do.

**Comment by chow1026** [comment]
That's a bummer. 

Is v0.70.0 not a supported version? 

Is there other alternative you'd propose?

**Comment by bep** [comment]
>Is v0.70.0 not a supported version?

What exactly do you mean by that?

**Comment by chow1026** [comment]
I get what you mean.  Homebrew however might view the maintenance of releases, branches/tags differently. They see a release needs to be a branch, that signifies actually those versions are maintained/supported. 

A tagged release is only acceptable if a patched version like v0.70.1 is expected.  [Here](https://github.com/Homebrew/homebrew-core/pull/57334#issuecomment-653738381) is their full explanation.

**Comment by bep** [comment]
>Versioned formula are only acceptable for 0.70.0 if upstream plans to release something like 0.70.1 in the future. Just a tag existing for an older version is not signifying intend in that direction.

To me it looks like they want a branch just to "signal intent". Hugo has released plenty of patch releases, see:

https://github.com/gohugoio/hugo/releases/tag/v0.73.0

That should be proof of "actively maintained".

On that page you will also find binaries from MacOS back to the very first version of Hugo, which should give you what you want.

**Comment by chow1026** [comment]
Thank you, noted. I'll relay your message. Look forward to seeing the statement regarding the supported older versions too. 

Also, a last question:
Is there a reason why among tags here, there is `v0.70.0` 
![Screenshot 2020-07-06 at 9 10 25 AM](https://user-images.githubusercontent.com/16604634/86546747-e81dea00-bf68-11ea-99ef-2c6863be1a4d.png)

but on branches, there isn't a `release-0.70.0`?
![Screenshot 2020-07-06 at 9 10 44 AM](https://user-images.githubusercontent.com/16604634/86546790-10a5e400-bf69-11ea-84c5-c4b67bbcc810.png)

**Comment by SMillerDev** [comment]
What homebrew needs to allow versioned formula is an intent by upstream to continue development on two different versions. Otherwise we'll just ship the latest version. 

Something like https://www.php.net/eol.php

It seems however that hugo development is being done on the latest version, which is absolutely fine for homebrew. It just means we only ship that latest version.
