### ISSUE TITLE
Expose DefaultContentLanguage in Site variables

### ISSUE THREAD

**Issue by EpicEric** [gohugoio/hugo#7463]
Currently, there's no way to get the default language of the site (other than assuming it has the smallest weight in the list of `AllTranslations`, with some caveats). This variable would be useful for creating conditions, for example (in my case) to check if a localized documentation is up-to-date with the original page.

**Comment by regisphilibert** [comment]
Though not very intuitive, `.Sites.First.Language` will give you what you're looking for (`.Sites.First.Language.Lang` returns the language code)

**Comment by EpicEric** [comment]
Is there any documentation for `.Sites.First` or `.Sites`? I can't seem to find it in Hugo Docs.

**Comment by jmooring** [comment]
https://gohugo.io/variables/page/#page-variables
