### ISSUE TITLE
Documentation pages not working! 

### ISSUE THREAD

**Issue by djtimone** [gohugoio/hugo#7465]

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by djtimone** [comment]
ok thanks. I mean some pages didn`t work like that
https://gohugo.io/hugo-modules/configuration/

пн, 6 июл. 2020 г. в 23:29, Bjørn Erik Pedersen <notifications@github.com>:
