### ISSUE TITLE
Hugo generating invalid single quotes

### ISSUE THREAD

**Issue by CorruptComputer** [gohugoio/hugo#7470]
Hugo replaces single quotes (`'`) in md files with `&rsquo;` in the generated HTML which breaks some layouts and fonts.
Causes situations like this: (that isn't a space, the extra space is part of the `&rsquo;` character)
![image](https://user-images.githubusercontent.com/5573038/87036955-899b7a80-c1b9-11ea-9dfb-0451dab3f7d4.png)

Manually changing all the `&rsquo;` with regular `'` fixes the issue.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.73.0-428907CC windows/amd64 BuildDate: 2020-06-23T16:32:10Z
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
The behavior is configurable. Please post your question to the [discussion forum](https://discourse.gohugo.io), and close this issue. Thanks.

**Comment by CorruptComputer** [comment]
Is it configurable? Looking through [this](https://gohugo.io/getting-started/configuration/) page the only thing I find related to quotes is this:
```
[minify.tdewolff.html]
    keepQuotes = true
```

Which doesn't change anything related to the output of the quotes.

**Comment by jmooring** [comment]
We have an active [discussion forum](https://discourse.gohugo.io) where users and developers can ask questions. Please don't use the GitHub issue tracker to ask questions.
