### ISSUE TITLE
How to set a context path?

### ISSUE THREAD

**Issue by jay763190097** [gohugoio/hugo#7471]
When I set baseURL, It can change some pathes. But .css .js files can not work.

**Comment by jay763190097** [comment]
![截图录屏_选择区域_20200711184846](https://user-images.githubusercontent.com/16317178/87222570-35ee8400-c3a7-11ea-828c-d26f5fd94598.png)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by jay763190097** [comment]
set ``canonifyurls = true`` in config.tml file,It can solve this problem.

**Comment by sundowndev** [comment]
I have the same issue with static assets. Setting canonifyurls in config.yml doesn't fix anything. The documentation is throwing me off... How something as simple as including static assets is so complicated.
