### ISSUE TITLE
No fall-through to list.html with taxonomy.html and without term.html

### ISSUE THREAD

**Issue by tvendelin** [gohugoio/hugo#7472]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.73.0-428907CC/extended darwin/amd64 BuildDate: 2020-06-23T16:37:47Z
</pre>

### Does this issue reproduce with the latest release?
Yes

I have created a `taxonomy.html` template to iterate through terms showing the count of pages for each. This cannot be achieved with `{{ range .Pages }}` (`{{ .Count }}` ) not accessible, hence specific template.

I do not need anything beyond `list.html` capabilities for a page listing the terms, so `list.html`, the bottom default, should suffice. However, due to strange lookup order, Hugo tries to use `taxonomy.html` for that purpose, and fails, of course, as it tries to iterate over `{{ range .Data.Terms.ByCount }}` instead of `{{ range .Pages }}`. Now I have to copy `list.html` to `term.html` and maintain essentially one file for the price of two.

It is documented that the lookup _is_ performed in this way, but I still consider it a bug. AFAIK, `taxonomy.html` and  `term.html` serve completely different purposes. Why on earth would someone need one instead of another?

**Comment by bep** [comment]
See: https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-term-pages

**Comment by tvendelin** [comment]
I have read it quiet thoroughly (see the original message). It is unclear, though, what is the benefit of this lookup behavior. It just forces the user to create two identical pages in many cases.

**Comment by jmooring** [comment]
@tvendelin  I have replied to <https://discourse.gohugo.io/t/what-term-html-can-that-list-html-cannot/26874>. Please close this issue.
