### ISSUE TITLE
<.Site.Config.Service...>: can't evaluate field RSS in type services.Config

### ISSUE THREAD

**Issue by shrish83** [gohugoio/hugo#7476]
This theme seems to be working great in my local development environment in Rstudio, but it generates some errors while deploying it to Netlify. I checked my code and it doesn't seem to have any error. All the error messages point to the layouts/_default/rss.xml:9:19": execute of template failed: template: _default/rss.xml:9:19: executing "_default/rss.xml" at <.Site.Config.Service...>: can't evaluate field RSS in type services.Config
I have also attached a screenshot of the complete errors as reported by netlify.
link to my code: https://github.com/shrish83/My-Blog

![Screenshot (124)](https://user-images.githubusercontent.com/58556695/87251414-2ba4b680-c489-11ea-838f-7f89c114c22a.png)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
