### ISSUE TITLE
Anchor enumeration: Ability to iterate through anchors in pages

### ISSUE THREAD

**Issue by drush** [gohugoio/hugo#7482]
**STORY**

A page has many anchors to sections of the page.  As a developer, I'd like to be able to build menus deep-linking into specific page sections via these anchors programatically.

From a Page context, enumerate all the anchors on a page.

```
{{ range .Anchors }}
  <li><a href="{.Permalink}">{{ .Title }}</a></li>
{{ end }}
```

**Comment by jmooring** [comment]
The `.TableOfContents` page variable contains a _rendered_ list of heading anchors and titles. See <https://gohugo.io/getting-started/configuration-markup/#table-of-contents> for configuration options. 

If this list of anchors is sufficient, you could easily create a map from the rendered TOC to index/iterate as needed.
