### ISSUE TITLE
Hugo with skip render

### ISSUE THREAD

**Issue by panakour** [gohugoio/hugo#7485]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ v0.74.1
</pre>

I am using the Hugo Standard library as a tool using golang to build something (headless cms).

I build the site with the flag to skip rendering any files using the code:`site.Build(hugolib.BuildCfg{SkipRender: true})` . But for some reason the following files created every time the `Build` method is executed. 
![image](https://user-images.githubusercontent.com/12927166/87579647-eaa5df80-c6de-11ea-87de-5c322132f4b5.png)

The site I use has the structure:
![image](https://user-images.githubusercontent.com/12927166/87579794-2b9df400-c6df-11ea-9426-f4e49be8d279.png)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by panakour** [comment]
> Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see [Hugo Documentation](http://gohugo.io/overview/introduction/).
 
Yes, but this is a bug isn’t it ?
