### ISSUE TITLE
Error: IncompleteSignature regression in v0.74.1

### ISSUE THREAD

**Issue by kaihendry** [gohugoio/hugo#7492]
Not present in v0.73.0

https://discourse.gohugo.io/t/error-incompletesignature/27025/2 has the details

**Comment by jmooring** [comment]
@kaihendry Can we close this issue? I checked the last run and saw no errors:
<https://github.com/kaihendry/dabase.com/runs/2644962610?check_suite_focus=true#step:4:26>
