### ISSUE TITLE
RSS feed with full content

### ISSUE THREAD

**Issue by TyGu1** [gohugoio/hugo#7502]
For submitting a Hugo blog to r-Bloggers one has to submit a feed with full content.
In previous Hugo versions this could be achieved by modifying:
`<description>{{ .Summary | html }}</description>
`to
`<description>{{ .Content | html }}</description>,
`see https://stackoverflow.com/questions/48997278/how-do-i-get-my-blogdown-blog-on-r-bloggers/.

It does not seem to be doable with that Approach anymore. How can i achieve rss feed with full Content for Hugo Version 0.73.0+

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Version 0.73.0
</pre>

### Does this issue reproduce with the latest release?

I am using uhgo through https://github.com/shenoybr/hugo-goa and r blogdown.

**Comment by carlmjohnson** [comment]
Hugo still outputs full RSS feeds. See https://github.com/spotlightpa/poor-richard/blob/master/layouts/news/rss.xml for a working example.

**Comment by fcevado** [comment]
Is something planned for a bigger change on the EmbeddedTemplate? I noticed that recently and I was planning to do a PR that adds an option like `rssFullContent` adding a content node for the actual content of the entry. I know that rss doesn't include a content node in its spec, but atom does:
https://validator.w3.org/feed/docs/atom.html#recommendedEntryElements
