### ISSUE TITLE
Support ESBuild source maps

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7504]
See #7499

**Comment by bep** [comment]
Note: I see that ESBuild supports both inline and external source maps -- if inline maps works fine in Chrome/Safari, then I suggest we start with that (simplest).

**Comment by Vincent-Carrier** [comment]
I think a good default would be to enable inline sourcemaps when Hugo is in dev mode and external sourcemaps in prod mode.

**Comment by bep** [comment]
I don't want to have any "IsProduction" logic anywhere. If people want to turn on source maps they need to do so themselves -- they can easily make that condition.

**Comment by jmooring** [comment]
This was addressed with https://github.com/gohugoio/hugo/pull/7610 in v0.75.0.
