### ISSUE TITLE
themes.gohugo.io Takes like a million years to load

### ISSUE THREAD

**Issue by stoneric** [gohugoio/hugo#7506]
This is about "The world’s fastest framework for building websites" claim.

themes.gohugo.io is slow as...mud?

**Comment by Jos512** [comment]
I don't see that happening on my end. [This webpage test](https://webpagetest.org/result/200722_FR_f51a97c7a262f3c9db987a8c80b87d8d/) also shows good results. I don't see anything in Netlify's status that points to a performance issue, although that certainly is possible of course.

Do you still experience high load times at this time?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
