### ISSUE TITLE
Image with space in their name does not work with goldmark.

### ISSUE THREAD

**Issue by JeanDaniel-Fischer** [gohugoio/hugo#7511]
### What version of Hugo are you using (`hugo version`)?
0.74.1

### Does this issue reproduce with the latest release?
yes

We upgrade to 0.74.1 from 0.55 and detected an issue on image contributed into the content. With foldmark the following failed and output the markdown version :

![](/uploads/my image.jpg)

It is working with blackfriday. As image are contributed through Forestry we cannot make sure that image name is without space.

**Comment by JeanDaniel-Fischer** [comment]
I have found a workaround for existing file, I can enclose between <> my url and it works. Maybe it should be pointed in the documentation to help other people that are migrating to goldmark ?

**Comment by jmooring** [comment]
Encapsulating within `<>` is not a workaround; it is required per the CommonMark spec:
<https://spec.commonmark.org/0.29/#link-destination>

>A link destination consists of either
> -  a sequence of zero or more characters between an opening < and a closing > that contains no line breaks or unescaped < or > characters, or 
> - a nonempty sequence of characters that does not start with <, does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)
