### ISSUE TITLE
favicon.ico and manifest.webmanifest support

### ISSUE THREAD

**Issue by dfang** [gohugoio/hugo#7519]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3/extended darwin/amd64 BuildDate: unknown

</pre>

### Does this issue reproduce with the latest release?
0.74.3 is the latest version for now

favicon.ico and manifest.webmanifest are there in public folder, but got 404 error in network tab.

<img width="1435" alt="Screen Shot 2020-07-28 at 10 42 28 AM" src="https://user-images.githubusercontent.com/1277047/88612972-0b970900-d0bf-11ea-858b-bccfa3808685.png">

and open url http://localhost:1313/favicon.ico, got `404 page not found`

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by dfang** [comment]
for everyone coming here from google, https://gohugo.io/getting-started/directory-structure/

create a static folder, and put it in static root.
