### ISSUE TITLE
Custom languages in markdown highlight syntax do not generate <div class="highlight"> 

### ISSUE THREAD

**Issue by chrvo** [gohugoio/hugo#7521]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.74.3
</pre>

### Does this issue reproduce with the latest release?
yes

### Setup
We use prism.js as syntax highlighter and we added programmatically support for new languages.

### Problem
```` markdown
``` test
nice source code
```
````
does not generate the enclosing \<div class="highlight">\</div>.

As a result the css styling is partially broken.

**Comment by pamubay** [comment]
Can't reproduce.
i'm on
```
Hugo Static Site Generator v0.75.0-DEV-E5591E89/extended linux/amd64 BuildDate: 2020-07-29T01:53:59+0700
```

please close this issue and move to https://discourse.gohugo.io

**Comment by satotake** [comment]
I do not why but this seems to be an intended behavior as a [test case](https://github.com/gohugoio/hugo/blob/2fa851e6500752c0cea1da5cfdfc6d99e0a81a71/markup/goldmark/convert_test.go#L239) says.

An easy workaround is using html in markdown 

``` gfm
<div class="highlight">

``' test
nice source code
``'

</div>
```

Note: Please make markup's `unsafe` setting true in your `config.toml` like

```toml
[markup]
[markup.goldmark.renderer]
unsafe = true
```
See [config section in docs](https://gohugo.io/getting-started/configuration-markup#config)
