### ISSUE TITLE
No proper return from partials with `0` as arg

### ISSUE THREAD

**Issue by malcom** [gohugoio/hugo#7528]
Passing `0` integer as an argument to  partial template func with return statement (as a function substitute) prevents this "function" from returning the correct value. It looks like the `0` as partial argument is treated as `nil` context.

Template:
```
add42: 50: {{ partial "add42.tpl" 8 }}
add42: 42: {{ partial "add42.tpl" 0 }}
```

Output:
```
add42: 50: 50
add42: 42: 
```

File `partials/add42.tpl`
```
{{ $v := add . 42 }}
{{ return $v }}
```

This issue is reproducable with the latest release.

**Comment by iburago** [comment]
I just ran into this problem, as well. The bug manifests itself not
only when the passed context argument is zero, but also when
it is any empty value: nil, false, empty string, slice, or dictionary.
