### ISSUE TITLE
No proper URL in hugo server response

### ISSUE THREAD

**Issue by asaqib27** [gohugoio/hugo#7530]
##### Hugo Version
v0.74.3/extended

##### Issue

After executing command `Hugo Server` I am not receiving proper URL string in the output.
Instead, it shows `//localhost:1313/` it should be `http://localhost:1313/`

**Comment by jmooring** [comment]
We have an active [discussion forum](https://discourse.gohugo.io) where users and developers can ask questions. Please don't use the GitHub issue tracker to ask questions.

**Comment by asaqib27** [comment]
Closing this this issue and open a discussion on forum.
