### ISSUE TITLE
Why does fetching index.json need knowledge of baseurl & port?

### ISSUE THREAD

**Issue by dsculptor** [gohugoio/hugo#7533]
### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version

v0.74.3/extended darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### Repro details
- Run hugo in a docker on port 80 (very common use case) with search enabled. (`[outputs]` directive in config.toml)
- Port map the docker container `-p 8080:80`. 
- Search functionality will not work - because index.json will fail to load. (as its fetching from http://localhost:80 )
- Set `baseURL -> localhost:8080` => IT WON'T work either. Because PORT is taken from `--port` option in hugo server.

I believe that for this purpose, backend/JS code does not even need to know the value of baseURL or the external service URL. The JS should simply send requests to `/endpoint` instead of `http://baseURL:PORT/endpoint`

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by dsculptor** [comment]
@bep seems like a bug to me than an FAQ thing.
