### ISSUE TITLE
"What links here", help with a backreference implementation

### ISSUE THREAD

**Issue by thiderman** [gohugoio/hugo#7537]
Hello,

At our company, we are using Hugo to produce our internal documentation. Something we've been wanting is a way to have pages show what other pages link to them. This has been [asked for by others][discourse], who were told that such a feature does not currently exist.

Since we desire to have this feature, we would like to help implementing it. But, we need some pointers. We just spent an hour trying to find a good place to start, but sadly could not find a good spot.

So, basically what we want is to have access to something like `.Page.BackRefs` when rending a page. This would be an array of other `Page` objects, so that we could loop over them and create simple lists using their title and their refs.

Firstly, does this sound like an okay idea? If it does, do you have any suggestions on how it would be implemented? Our perhaps naive idea was to just walk over all the page nodes, collect what references they contain, and then populate a hashmap with a `ReferencedPage: [ReferencingPages]` structure. So, when looking up the backreferences to a `Page`, we can use this hashmap and find all the pages that references it.

Again, this is less of a feature request and more of an inquiry for places to start. We're happy to implement it, we just want to make sure we go about it in a good way that's compatible with the project!

[discourse]: https://discourse.gohugo.io/t/what-links-here-backlinks/14757

**Comment by bep** [comment]
I don't know how to simply implement this myself, so I don't have a suggestion.

**Comment by jmooring** [comment]
Duplicate of https://github.com/gohugoio/hugo/issues/8077.
