### ISSUE TITLE
Front matter param overwrites same param on other content files

### ISSUE THREAD

**Issue by gabrielmaldi** [gohugoio/hugo#7539]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

-----

This is my folder structure:

<img src="https://user-images.githubusercontent.com/3728897/89695287-d2923c00-d8e9-11ea-8565-6672e19fef4f.png" width="300px">

Each of the 3 content files has a `courseName` param with different values:

```
+++
emailTemplate = "course-template"
courseName = "Course 1"
+++
```
```
+++
emailTemplate = "course-template"
courseName = "Course 2"
+++
```
```
+++
emailTemplate = "course-template"
courseName = "Course 3"
+++
```

The template just renders the param from the front matter:

```html
Welcome to the course "{{ .Params.courseName }}"!
```

And the `single.html` layout glues everything together:

```html
{{ $page := readFile (printf "layouts/partials/%s/%s.html" (path.Dir .File.Path) .Params.emailTemplate) | resources.FromString ".html" | resources.ExecuteAsTemplate "" . }}
{{ $page.Content | safeHTML }}
```

When I build running `hugo --verbose --ignoreCache --gc` the output is the same for all 3 files:

`public/emails/courses/course-1/index.html`
```html
Welcome to the course "Course 3"!
```
`public/emails/courses/course-2/index.html`
```html
Welcome to the course "Course 3"!
```
`public/emails/courses/course-3/index.html`
```html
Welcome to the course "Course 3"!
```

Of course the expected output is for each file to render its own param: `Course 1`, `Course 2`, `Course 3`.

-----

I created a repro repo. The first commit only contains what is generated by running `hugo new site`. The second commit contains the files I added (as detailed above) and the output generated by building.

https://github.com/gabrielmaldi/hugo-params-bug

Thanks!

**Comment by pamubay** [comment]
**First**, why all produces same output `Course 3".
it because `resources.FromString` and `resources.ExecuteAsTemplate` are cached.

The cache key used by both function above is the target path. 
so you need to generate unique target path for each function invocation. you can use something like `now.Unix` or anything.

**Second**, i don't know what are you trying to do here.
```
{{ $page := readFile (printf "layouts/partials/%s/%s.html" (path.Dir .File.Path) .Params.emailTemplate) | resources.FromString ".html" | resources.ExecuteAsTemplate "" . }}
{{ $page.Content | safeHTML }}
```
But, if i understand correctly, you want to excute partial template where the location of template based on the `path.Dir`  and `.Params.emailTemplate`. if yes, then you can just called the normal partial function.

```
{{ $page := printf "%s/%s.html" (path.Dir .File.Path) .Params.emailTemplate }}
{{ partial $page . }}
```

**Comment by gabrielmaldi** [comment]
Thanks, @pamubay!

I can't use `partial` because it strips comments (maybe there's a way to preserve them?), and I'm generating HTML emails, which need stuff like:

```
<!--[if gte mso 9]>
  <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG />
      <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </o>
  </xml>
[endif]-->
```

I changed `resources.FromString ".html"` to `resources.FromString .File.Path` and now everything works perfectly!
`now.Unix` produces the same value every time in my build (probably Hugo is just too fast 😄).
And I didn't need to change `resources.ExecuteAsTemplate "" .`.

Thanks again 😊

**Comment by pamubay** [comment]
Try this

```
{{ `<!--[if gte mso 9]>
  <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG />
      <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </o>
  </xml>
[endif]-->` | safeHTML }}
```

**Comment by gabrielmaldi** [comment]
That works, thank you!

I'm still going to stick with my convoluted solution because most of these email templates have at least 50 or more comment sections like that, and other people copy and paste them from other tools, so requiring them to wrap every comment with `{{ `` comment `` | safeHTML }}` is most likely going to lead to bugs.

But thanks for that information, I'm it will be useful sooner than later 😊.
