### ISSUE TITLE
preserveTaxonomyNames FALSE not changing single Polish characters ( Ł ł )

### ISSUE THREAD

**Issue by idarek** [gohugoio/hugo#7542]
<pre>
$ hugo version 0.74.3
</pre>

I have converted my blog to Hugo and trying to match old links with new one. 
Hugo by default generating tags with accented characters as I see. As I don't want that, I added preserveTaxonomyNames in FALSE state to config and in most cases its sorted, but not all characters are changed.

This is not working for Polish language
`ł > l`

**Comment by idarek** [comment]
@bep could you advise, are fix for this been implemented in 0.75 released now?

**Comment by davidsneighbour** [comment]
According to https://discourse.gohugo.io/t/what-part-of-hugo-is-responsible-for-changing-characters/28578 it's only one single character that is not transformed. All other characters are transformed.

**Comment by moorereason** [comment]
I don't pretend to understand Unicode normalization and transformation, but here are some clues.

I believe the transformation is [happening here](https://github.com/gohugoio/hugo/blob/d48a98c477a818d28008d9771050d2681e63e880/common/text/transform.go#L27), by way of [UnicodeSanitize](https://github.com/gohugoio/hugo/blob/d48a98c477a818d28008d9771050d2681e63e880/helpers/path.go#L138).

We're doing Unicode normalization and removing the [`Mn`](https://golang.org/pkg/unicode/#Mn) category of Unicode characters.  While [playing around with the logic](https://play.golang.org/p/Su9lbBtognf), I discovered that `ł` falls into the [`Ll`](https://golang.org/pkg/unicode/#Ll) category of lowercase letters.

**Comment by idarek** [comment]
Yes, its fall (shall be changed to) Ll and been surprised that all other characters (ąśćźżęóń) are converted correctly but not this one single character. Any chance to implement a fix for that somehow?

**Comment by idarek** [comment]
Hi, Just want to bump and ask if there is any progress with fixing issue with this single character in polish that shall be converted from "ł" to "l"

**Comment by Wirone** [comment]
Problem remains on Hugo v0.96, `ł` and `Ł` are the only polish letters that are not converted in slugs.

**Comment by idarek** [comment]
The problem remains on Hugo v0.111.3, ł and Ł are the only Polish letters that are not converted in slugs due to confusion of this symbol with the pound sterling symbol £ (U+00A3).

**Comment by jmooring** [comment]
The `preserveTaxonomyNames` configuration option was removed in v0.55.0. The desired functionality is proposed in https://github.com/gohugoio/hugo/issues/9134.
