### ISSUE TITLE
ESBuilder not rebuilding when an imported JSON content changes

### ISSUE THREAD

**Issue by butaca** [gohugoio/hugo#7544]
When an imported JS file changes, ESBuilder rebuilds as excepted, however it doesn't rebuild when an imported JSON changes (for example: `import data from "../../data/data.json";`)

### What version of Hugo are you using (`hugo version`)?
<pre>
v0.74.3
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
Yes, this is a known issue; I have an ongoing branch that improves this, and I will have this issue in mind when I finis it. The challenges are:

* We don't want to, as an example, do 3-4 seconds PostProcess on every unrelated file change.
* For /assets, the implementation is currently rather crude.
* I will improve that, but it will "never" be perfect, so ...
* We may (big maybe) also want to consider marking some processing step as so fast that we just repeat them on every change ...

That said, a lot of Hugo's logic lives around a common root below /assets. ESBuild is currently a little special in that it does not support Hugo's virtual file system (we will improve that), but I think you can get your things working if you store your JS and JSON files below `/assets/js` and avoid the "../.." into data.

**Comment by butaca** [comment]
Thanks. I moved the json files to`/assets/js/data` and it works as expected. I had to change the hugo data dir to `/assets/js/data` though because the files are also used in hugo (that's why I had them under `/data`).

**Comment by bep** [comment]
>I had to change the hugo data dir to /assets/js/data

Note that you can mount folders multiple times to different destinations.

**Comment by butaca** [comment]
> you can mount folders multiple times to different destinations

Not sure what you are referring to. 🤔

**Comment by bep** [comment]
Search for "mount" in the Hugo docs. But in your case, since ESBuilder does not (currently) respect Hugo's file system, you need to put the data file (or folder) where it can find it, then mount it again into /data.

**Comment by jmooring** [comment]
See <https://github.com/gohugoio/hugo/issues/11898#issuecomment-1899342081> for the correct configuration with v0.78.1 and later. This issue is resolved by https://github.com/gohugoio/hugo/pull/11894.

```text
git clone --single-branch -b hugo-github-issue-7544 https://github.com/jmooring/hugo-testing hugo-github-issue-7544
cd hugo-github-issue-7544
hugo server
```
