### ISSUE TITLE
Running minification will issue warnings about usage of Decimals option

### ISSUE THREAD

**Issue by dorinlazar** [gohugoio/hugo#7545]
When I run with minification enabled I get for each article a warning:
> WARNING: SVG option `Decimals` is deprecated, using as `Precision` instead. Be aware that `Decimals` meant the number of digits behind the dot while `Precision` means the number of significant digits. Example: 1.23 with `Decimals=1` would give 1.2 but with `Pecision=1` gives 1. The default `Decimals=-1` is now `Precision=0` which prints the whole number.

This happens regardless of any decimals: settings in the config file.

### What version of Hugo are you using (`hugo version`)?

Hugo Static Site Generator v0.69.0/extended linux/amd64 BuildDate: unknown

### Does this issue reproduce with the latest release?
This is the latest release I can access (I'm using prebuild binaries from Fedora distribution)

**Comment by bep** [comment]
You should take this with whoever builds this "Fedora distribution" -- as their build setup seems to be broken,

**Comment by dorinlazar** [comment]
Confirmed, not reproduced with the latest version. I'll investigate on the Fedora Rawhide.
