### ISSUE TITLE
JSON templates lookup fails except when building

### ISSUE THREAD

**Issue by xlegs** [gohugoio/hugo#7550]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.73.0/extended linux/amd64 BuildDate: unknown
</pre>

I have two sections, Projects and Universities, where I want Hugo to generate JSON and HTML outputs. The JSON for Universities works perfectly, but the JSON file for Projects is using the template for University.

I made a post about it here: https://discourse.gohugo.io/t/json-output-uses-the-wrong-template/27284

Upon further investigation, the lookup order works when running `yarn build` but not when running `watch` or `preview`.

Here is a portion of my `package.json`:
```
  "scripts": {
    "lint": "eslint src",
    "start": "run-p start:**",
    "start:hugo": "hugo -d ../dist -s site -vw",
    "start:webpack": "webpack-dev-server --config webpack.dev.js --hot",
    "preview": "run-p preview:**",
    "preview:hugo": "npm run start:hugo -- -D -F",
    "preview:webpack": "npm run start:webpack",
    "prebuild": "rimraf dist",
    "build": "npm run build:webpack && npm run build:hugo",
    "build:preview": "npm run build:webpack && npm run build:hugo:preview",
    "build:hugo": "hugo -d ../dist -s site -v",
    "build:hugo:preview": "npm run build:hugo -- -D -F",
    "build:webpack": "cross-env NODE_ENV=production webpack --config webpack.prod.js"
  },
```

A sample repo with this issue can be found at https://github.com/xlegs/hugo-error-demo

**Comment by bep** [comment]
The template lookup in Hugo is all about "get me the most specific" template. Looking at your project, you have a `list.json.json` and then in the other section a `list.json`... Without discussing the sensibility of it all, it looks to me like list.outputFormat.mediaType is more specific than the other even if it's in a different section.

**Comment by xlegs** [comment]
Even if I name all the files to list.json.json, `yarn start` does not build my projects index.json properly. `yarn build` does. Why does it not work consistently?
