### ISSUE TITLE
Hugo extended BuildDate shows as unknown on Windows 10

### ISSUE THREAD

**Issue by jflipp** [gohugoio/hugo#7551]
Here's a minor bug.

I use hugo v0.74.3 and hugo extended v0.74.3 on Windows 10 64 Bit.

When I execute the version subcommand, I get the following output.

<pre>
C:\Test> C:\Test\hugo_0.74.3_Windows-64bit\hugo.exe version
Hugo Static Site Generator v0.74.3-DA0437B4 windows/amd64 BuildDate: 2020-07-23T16:23:30Z

C:\Test> "C:\Test\hugo_extended_0.74.3_Windows-64bit\hugo.exe version
Hugo Static Site Generator v0.74.3/extended windows/amd64 BuildDate: unknown
</pre>

We see that the regular version of Hugo shows a reasonable BuildDate, but the extended version of Hugo shows **BuildDate: unknown**.

Maybe you want to look into this.

As far as I know, v0.74.3 is currently the latest release of Hugo.

Thank you.

**Comment by jmooring** [comment]
Unable to reproduce with v0.83.1.

```
hugo v0.83.1-5AFE0A57+extended windows/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio

```
