### ISSUE TITLE
Hugo render code block error

### ISSUE THREAD

**Issue by dungdm93** [gohugoio/hugo#7553]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.73.0-428907CC/extended linux/amd64 BuildDate: 2020-06-23T16:40:09Z
</pre>

### Does this issue reproduce with the latest release?
I have this code block
```
yyyy-MM-dd H:m:s
```
And this is rendering result:
![Screenshot from 2020-08-13 18-49-29](https://user-images.githubusercontent.com/6848311/90131104-c698f500-dd95-11ea-8154-436812801f63.png)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
