### ISSUE TITLE
Brackets in explicit urls are stripped

### ISSUE THREAD

**Issue by mikegoatly** [gohugoio/hugo#7555]
## What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3/extended windows/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

I'm porting an existing site to Hugo, so don't have much choice in some historical URLs.

When I have a page that includes this:

```
---
url: "/2008/1/11/Good-Uses-for-SQL-Server-2005-Common-Table-Expressions-(Part-1).aspx"
---
```

Links to the file are rendered as: `http://localhost:1313/2008/1/11/good-uses-for-sql-server-2005-common-table-expressions-part-1.aspx` - i.e. without any of the brackets.

When trying to follow the link, the page reports an error:

> This page contains the following errors:
>
> error on line 3 at column 55: EntityRef: expecting ';'
>
> Below is a rendering of the page up to the first error.

The URL management documentation suggests that this is the correct way to explicitly state a URL, and I can't see anything there that would indicate that characters such as this are unacceptable.

**Comment by mikegoatly** [comment]
On a related note, I'd also observe that the casing of the URL isn't honoured and is converted to lowercase which will break existing links from search engines

**Comment by SirUli** [comment]
Could it be that this is related to:

- https://discourse.gohugo.io/t/allow-aliases-with-htm-suffix/28780
- https://github.com/gohugoio/hugo/issues/7827

**Comment by jmooring** [comment]
Unable to reproduce with v0.83.1.

```bash
git clone --single-branch -b hugo-github-issue-7555 https://github.com/jmooring/hugo-testing hugo-github-issue-7555
cd hugo-github-issue-7555
hugo server
```
