### ISSUE TITLE
Codewalks

### ISSUE THREAD

**Issue by chewxy** [gohugoio/hugo#7556]
Hi,
Codewalks are very useful in a lot of programming tutorial websites. [This](https://golang.org/doc/codewalk/sharemem/) for example, is Go's codewalk on sharing memory. 

I would like to add this feature to Hugo - I've in fact started already (the fork is at https://github.com/chewxy/hugo) . 

I would like some guidance as to how to get it to properly work and get it merged into mainline.

## What is a Codewalk ##

A codewalk is a combination of a `.xml` file, and source code file(s). The `.xml` file provides the commentaries on the source code file. 

In this context, I think the page bundle feature, combined with directory based archetypes work very well. 

## What I've Done So Far ## 

What I have done so far is add a [new markup type](https://github.com/chewxy/hugo/tree/master/markup/codewalk) (called `codewalk`), and added code to register it to the `markup` package.

I'm now figuring out how page bundles work because I can't seem to pass any docs to the converter.

**Comment by bep** [comment]
Thanks,

But I'm not convinced that this belongs top this repo. The Go example you're given does not live in Go's repository, also, Hugo isn't built to be used as a library, so I don't see many relevant end user examples.

**Comment by chewxy** [comment]
Fair enough, though I would like to correct one statement: the codewalk example DOES [https://github.com/golang/go/tree/master/doc/codewalk](live in the Go repository).

Would an alternative to make this be like the pandoc/rst/asciidocext renderer work - i.e. make this an external markup program - would that be acceptable?
