### ISSUE TITLE
TOC incorrect link when Header is a link 

### ISSUE THREAD

**Issue by jhollowe** [gohugoio/hugo#7557]
When a Heading is a link (`## [Heading](https://example.com)`), the  Table of Contents entry is that link, rather than the link to the section on the current page (so `https://example.com` instead of `this.site/path/to/page#heading`).

It seems that the issue is the rendering of the markdown *after* the TOC has been created. This overwrites the internal link with the header's link. Any other markdown formatting is also applied to the TOC (such as bold, italic, etc). This seems to be the incorrect behavior as the TOC should be consistent and not reliant on the formatting of the headers. However, I believe any emoji or other replacements should still be included in the TOC.

[See here for the location of the problem](https://github.com/gohugoio/hugo/blob/master/markup/tableofcontents/tableofcontents.go#L140)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3-DA0437B4/extended linux/amd64 BuildDate: 2020-07-23T16:30:30Z
</pre>

### Does this issue reproduce with the latest release?
yes

**Comment by ericbjones** [comment]
just confirming same problem still exists
```
❯ hugo version
Hugo Static Site Generator v0.78.0/extended darwin/amd64 BuildDate: unknown
```
```
# I'm not worried about that BuildDate: unknown, probably just because I am on a mac as I am reporting this but you can see  I am on the latest version, and this also happens on the Linux box where I do the builds for production.
```

Here is what the resulting HTML looks like for the TOC for me when I have links in my headers:
```
<li>
    <a href="#a-link-as-a-headinghttpswwww3schoolscomtagstag_hnasp"></a>
    <a href="https://www.w3schools.com/tags/tag_hn.asp">A Link As A Heading</a>
</li>
```
it makes two links in the TOC.  The first is empty for the > text < portion so it cant be clicked and the second shouldn't be there at all.
That is the anchor id that is generated so the first link would be functional otherwise

```
<h2 id="a-link-as-a-headinghttpswwww3schoolscomtagstag_hnasp">
    <a href="https://www.w3schools.com/tags/tag_hn.asp">A Link As A Heading</a>
</h2>
```
original markdown is
```
## [A Link As A Heading](https://www.w3schools.com/tags/tag_hn.asp)
```
and my TOC shortcode is
```
{{ if (.Params.toc) }}
<aside>
    Table of Contents:
    {{.TableOfContents}}
</aside>
<hr>
{{ end }}
```

**Comment by davidsneighbour** [comment]
also existing on 0.79.0
