### ISSUE TITLE
Open Graph and Social Image / Card Generation

### ISSUE THREAD

**Issue by sirinath** [gohugoio/hugo#7558]
Can we have the ability to generate Open Graph and social cards using an HTML template? Any page properties can be used. This will be open in different specified screen sizes and saved as an image and also populate relevant variables to be used with internal templates.

The generated card image can look like:

![image](https://user-images.githubusercontent.com/637415/90911070-0eeb8f00-e3f6-11ea-82c6-392a48010deb.png)

Generating these images conveniently for all posts currently is a pain point.

**Comment by nsebhastian** [comment]
Hi @sirinath this might help you out. I want to try it out but currently AFK https://github.com/Ladicle/tcardgen
