### ISSUE TITLE
Prevent parsing of shortcodes inside code blocks

### ISSUE THREAD

**Issue by craigcomstock** [gohugoio/hugo#7561]
This is essentially the same as https://github.com/gohugoio/hugo/issues/5446 but instead of for org file, for a markdown (md) file.

I can't include a CFEngine mustache template in a source code block without the shortcode parser complaining.

```
{{%-top-}}
```

in a markdown content file gives me this when running `hugo server -D`

```
Error: Error building site: "/home/craig/tmp/unreasonablefarm.org/content/clogs/support-4724-skipping-cron.md:397:38": unrecognized character in shortcode action: U+002D '-'. Note: Parameters with non-alphanumeric args must be quoted
```

I worked around the issue by changing the text to `{ {%-top-}}`.

Granted, I understand now that {{%, {{@ and {{# are all special [CFEngine extensions](https://docs.cfengine.com/docs/3.12/reference-promise-types-files.html#template_method-mustache-extensions) to mustache. Regardless though I wonder how you would include examples of shortcodes in a markdown/org post?

### What version of Hugo are you using (`hugo version`)?

From debian (pureos actually) testing:

<pre>
$ hugo version
Hugo Static Site Generator v0.54.0/extended linux/amd64 BuildDate: 2019-06-04T19:16:36Z
</pre>

### Does this issue reproduce with the latest release?

Yes. 0.74 has this problem as well:

ERROR 2020/08/14 12:37:13 "/home/craig/tmp/unreasonablefarm.org/content/clogs/cfengine-personal-policy.md:2135:59": unrecognized character in shortcode action: U+002D '-'. Note: Parameters with non-alphanumeric args must be quoted

### Proposal

Add something to the parser to notice blocks which could contain examples of shortcodes/mustache templates (https://gohugo.io/content-management/formats/#list-of-content-formats) and skip evaluating those blocks with the shortcodes parser.

For org it would be `+#BEGIN_*` to `+#END_*`
For md it would be triplebacktick or tripletilde to start/end blocks.

**Comment by bep** [comment]
> I wonder how you would include examples of shortcodes in a markdown/org post?

You do this:

```
{{</* myshortcode */>}}<p>Hello <strong>World!</strong></p>{{</* /myshortcode */>}}
```

**Comment by olehermanse** [comment]
@bep The issue here is that we want to render something that starts with `{{%`, but doesn't end with `%}}`:

```
{{%-top-}}
```

The hugo shortcode "trick" allows this:

```
{{%/*-top-*/%}}
```

to be rendered to:

```
{{%-top-%}}
```

But does not allow omitting the second `%`:

```
{{%/*-top-*/}}
```

that gives an error:

```
Error: Error building site: "/northern.tech/cfengine/website/content/blog/2018/cfengine-3-12-0-lts-released.md:85:32": comment must be closed
```

**Comment by aleksandrychev** [comment]
Workaround:
 printing needed code via a simple shortcode (layouts/shortcodes/print.html):
`{{ index .Params 0 }}`

and then you can use it in your content as:
`{{% print  `{{%-top-}}` %}}`
