### ISSUE TITLE
Extra / in link url

### ISSUE THREAD

**Issue by jienius** [gohugoio/hugo#7562]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

Running hugo serve, the generated link tags have an extra / in its URL
```
<link rel="icon" href="http://localhost:1313//favicon.ico">
```

**Comment by santosh** [comment]
What does `baseURL` of your config file says?
