### ISSUE TITLE
Add limit option for replaceRE and replace

### ISSUE THREAD

**Issue by dmgawel** [gohugoio/hugo#7586]
I'd like to propose adding an optional `limit` param for `replaceRE` and `replace` functions that works exactly the same as `limit` in `findRE`.

Example use case: Process article content and automatically add links to glossary terms for first occurrences of every word from glossary.

cc: @fplanque

**Comment by bep** [comment]
That sounds good.

**Comment by moorereason** [comment]
I've submitted a PR for consideration that updates `replace`.

The stdlib [`regexp` package](https://golang.org/pkg/regexp/) doesn't provide a limited replace function.  [A proposal issue](https://github.com/golang/go/issues/40198) exists, but there's no movement yet.
