### ISSUE TITLE
.File.Dir and .FilePath return absolute paths when used in directory based archetypes

### ISSUE THREAD

**Issue by thomasmarkrea** [gohugoio/hugo#7589]
I have a directory based archetype and a standard archetype:

```
archetypes
├── test-bundle
│   └── index.md
└── test.md
```

Both `.md` files are identical and just include:

```
{{ .File.Dir }}
```

New content created from the standard archetype contains a path relative to `content/` as expected (https://gohugo.io/variables/files/):

```bash
hugo new -k test blog/test.md
cat content/blog/test.md
# blog/
```

However, new content created from the directory based archetype contains the full path:

```bash
hugo new -k test-bundle blog/test
cat content/blog/test/index.md
# /home/tom/projects/test-hugo-dir/content/blog/test/
```

I assume the issue is somewhere in https://github.com/gohugoio/hugo/blob/master/create/content.go and the `NewContent`/`newContentFromDir` functions but my Hugo/Go knowledge is not enough to work out exactly what.

---

Example repository:
https://github.com/thomasmarkrea/test-hugo-dir

---

Related forum post:
https://discourse.gohugo.io/t/file-dir-returns-absolute-path/27621

---

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3-DA0437B4 linux/amd64 BuildDate: 2020-07-23T16:22:34Z
</pre>

also tested on 

<pre>
$ hugo version
Hugo Static Site Generator v0.72.0-8A7EF3CF/extended linux/amd64 BuildDate: 2020-05-31T12:14:23Z
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
Confirmed. Reproduced with Hugo Static Site Generator v0.75.0-DEV/extended linux/amd64 BuildDate: unknown.

**Comment by jmooring** [comment]
Possibly related:
<https://discourse.gohugo.io/t/32155/6>
