### ISSUE TITLE
why two modules in go.mod for same things

### ISSUE THREAD

**Issue by ghost** [gohugoio/hugo#7592]
github.com/BurntSushi/toml
github.com/pelletier/go-toml

github.com/russross/blackfriday
github.com/yuin/goldmark

**Comment by qlcom** [comment]
@bep but github.com/BurntSushi/toml isn't latest toml spec compliant. you should remove this package.

**Comment by davidsneighbour** [comment]
I blocked @qlcom, but that last message... hehe... anyway... what's the policy against/about trolls?

**Comment by bep** [comment]
> what's the policy against/about trolls?

We have so few trolls that we don't need a policy.

qlcom isn't so off base with this, his main problem is that he thinks creating even more issues about the same will get the right attention. I think the main reason we're still using BurntSushi is performance, but as I have a year old performance related pull request open in that repo, it may be timely to rethink that.
