### ISSUE TITLE
May be we can simplely add .json/.toml/.yaml as new content formats, just like .md or .html

### ISSUE THREAD

**Issue by bin16** [gohugoio/hugo#7593]
### Why this proposal?

- Markdown is weak, and shortcodes are not so... friendly, it's Hugo-specific and a little hard to read.
- JSON is widely used, with unlimited possibility to express, it could be something like AST generated from other tools.
- TOML and YAML are good to read, and all the three parser are included in Hugo.

With this way, developers could create applications to generate/edit the data file, and render them with hugo, for example, some personal activities like tweets, short and have no titles.

And, some crawlers could download personal data as json files, they can be put here and generate an article easily.

### Why not saving data in front matter, it support all the three formats?

Yes, that's a way, with some adapters, not so direct. But it's not be a big change, parsing json file, and adding the data to somewhere like `.Page.Params`

**Comment by davidsneighbour** [comment]
https://gohugo.io/templates/output-formats#readout <-- what about this functionality?

**Comment by bin16** [comment]
@davidsneighbour thanks, but I want json in, not as output

**Comment by davidsneighbour** [comment]
I did that the following way:

1. json in the page bundle, as in 

https://github.com/davidsneighbour/hugonewsletter.com/tree/master/content/newsletter/201910

2. conversion from json to html via single page template

https://github.com/davidsneighbour/hugonewsletter.com/blob/master/layouts/newsletter/single.html

but maybe I misunderstand the full setup you want to achieve.

**Comment by bin16** [comment]
@davidsneighbour That's Great! It's what I want, reading a JSON file and rendering it in the template. Thanks a lot for your example. 

Now I'm closing this issue
