### ISSUE TITLE
add possibility for different location than root for static assets when generating static html

### ISSUE THREAD

**Issue by jozefRudy** [gohugoio/hugo#7597]
Hi, 

it would be very helpful if we could optionally define other location than root of (public) folder where static assets are copied. It is obviously not only copy location (that could be done manually) but also links to static items generated inside htmls.

It would not only be cleaner deployment, but also one possible use case is to have hugo generated content as  part of server rendered site, however only for blog or documentation section (where servers usually serve static assets under specific folder).

Something like:

staticTarget: static

**Comment by moorereason** [comment]
Such as the `staticDir` [configuration option](https://gohugo.io/getting-started/configuration/)?

**Comment by jozefRudy** [comment]
no, exactly opposite.

staticDir (“static”)
A directory or a list of directories from where Hugo reads static files. Also see Module Mounts Config for an alternative way to configure this directory (from Hugo 0.56).

I would not like to change SOURCE, but DESTINATION. @moorereason

**Comment by jozefRudy** [comment]
If it is a problem or no one is willing to do that, I can possibly dive into hugo and try to suggest a solution as PR.

**Comment by jozefRudy** [comment]
actually, after digging depper, this seems to solve the problem:

```
module:
  mounts:
  - source: static
    target: static/static
```
