### ISSUE TITLE
Failed to read Git log: Unknown option: -C

### ISSUE THREAD

**Issue by zhangguanzhang** [gohugoio/hugo#7600]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3-DA0437B4 linux/amd64 BuildDate: 2020-07-23T16:22:34Z
</pre>

### Does this issue reproduce with the latest release?
yes

**Steps to reproduce the issue:**
1. clone the repo
```
git clone https://github.com/kubernetes/website.git
cd website
git submodule update --init --recursive
grep enableGitInfo  config.toml 
 enableGitInfo = true
```
2. build
```
$ hugo server --buildFuture
Building sites … ERROR 2020/08/26 13:49:41 Failed to read Git log: Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

```
3. other try, change ` enableGitInfo = true` to false and build
```
 vi config.toml 
 hugo server --buildFuture
Building sites … ERROR 2020/08/27 10:16:53 TOCSS: failed to transform "scss/_case-studies.scss" (text/x-scss): resource "scss/scss/_case-studies.scss_f300667da4f5b5f84e1a9e0702b2fdde" not found in file cache
Built in 28981 ms
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68" not found in file cache
```
seem this line
https://github.com/gohugoio/hugo/blob/1ce3e7d521fdb5d315b06028ef19860dc2e43bf1/releaser/git.go#L277

**Comment by jmooring** [comment]
The -C option was added in git version 1.8.5, released in 2013. The latest version is 2.28, released on 26 July, 2020.

With a current version of git installed I am unable to reproduce either of your problems.

Please close this issue, and in the future please use the [Hugo Forum](https://discourse.gohugo.io/) for support questions. Thanks.

**Comment by zhangguanzhang** [comment]
oops, the latest version on CentOS 7 is
```
git --version
git version 1.8.3.1
```
so I update the git
```
curl https://setup.ius.io | sh
yum makecahe
yum install -y git224
```
and the problem is gone
