### ISSUE TITLE
Images with spaces in name are not displayed

### ISSUE THREAD

**Issue by pendraggon87** [gohugoio/hugo#7606]
### What version of Hugo are you using (`hugo version`)? Latest

<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release? Yes

When trying to display an image with spaces in the name (e.g. /images/cool pic.png), the markdown text appears.  When using the NetlifyCMS, or any other markdown preview, images load fine.  Navigating to the absolute path works fine.  However, this doesn't get rendered properly when using goldmark.  e.g.

![some text](/images/cool pic.png)

**Comment by jmooring** [comment]
Spaces in the link destination are not allowed per the CommonMark spec:
<https://spec.commonmark.org/0.29/#link-destination>

>A link destination consists of either
> -  a sequence of zero or more characters between an opening < and a closing > that contains no line breaks or unescaped < or > characters, or 
> - a nonempty sequence of characters that does not start with <, does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

Do this instead: `![some text](</images/cool pic.png>)`

In the future, please use [Hugo Forum](https://discourse.gohugo.io/) for support issues. Please close this issue. Thanks.

**Comment by iantierney** [comment]
It took me HOURS to find this was my error. Maybe mark-down should support spaces in files names, its not the 90's!
