### ISSUE TITLE
Would it be possible to support for source map support in Build.js?

### ISSUE THREAD

**Issue by richtera** [gohugoio/hugo#7607]
https://github.com/gohugoio/hugo/blob/0256959a358bb26b983c9d9496862b0fdf387621/resources/resource_transformers/js/build.go#L154

Would it be possible to read a sourceMap true inside of the build options, or will the sourcemap output not get stored in the right place because the target is a path and not a directory?

**Comment by bep** [comment]
There is already an open issue about this.
