### ISSUE TITLE
Pagination does not work with .RegularPagesRecursive, or sub-sections

### ISSUE THREAD

**Issue by amdw** [gohugoio/hugo#7609]
### What version of Hugo are you using (`hugo version`)?

```
Hugo Static Site Generator v0.74.3 linux/amd64 BuildDate: unknown
```

### Does this issue reproduce with the latest release?

Yes

### Problem

I am trying to use `.Paginate .RegularPagesRecursive` in a list template, to create a paginated list of all the pages in `.RegularPagesRecursive`, but this does not work. When I try to do it, my paginated list contains no pages.

I put together a simple reproduction of this problem in the following repo:

https://github.com/amdw/hugorepro

There are 15 stories under `/news` here, one in each of the sub-sections `2018`, `2019` and `2020`.

The problem is with the page `/news`. I would like it to show all 15 stories, which I have tried to achieve using `.Paginate .RegularPagesRecursive` in [the list template](https://github.com/amdw/hugorepro/blob/master/layouts/_default/list.html#L8), but this results in an empty page.

I'm not 100% sure this is a bug, as [this documentation page](https://gohugo.io/templates/pagination/#list-paginator-pages) says you have to:

> Select a subset of the pages with the available template functions and ordering options, and pass the slice to `.Paginate`

which implies that `.Paginate` requires an argument that is a *subset* of `.Pages`, not an arbitrary list of pages. All the examples on that documentation page use such subsets.

However, I did find forum discussions like [this one](https://discourse.gohugo.io/t/how-to-list-pages-from-each-section-and-subsection/13950) which suggest that what I'm doing should work, and [this test](https://github.com/gohugoio/hugo/blob/42e150fbfac736bd49bc7e50cb8cdf9f81386f59/hugolib/hugo_sites_rebuild_test.go#L83) seems to do something similar.

Another surprising behaviour I found is that the same thing (empty `/news` page) happens if you simply use `.Paginator`. I understand why you wouldn't get all 15 stories in this case, because [the docs](https://gohugo.io/variables/page/#pages) make clear that `.Pages` only gives you *first-level* pages. But there are three of those, so I don't understand why we don't at least get three pages here.

### Request

If this behaviour is a bug, it would be great if it could be fixed.

If it's intentional, then I'd appreciate some guidance as to how I can make the `/news`, `/news/2018`, `/news/2019` and `/news/2020` pages each contain a paginated list of all the regular pages under the respective directories. This seems like a very simple requirement, but I've been completely unable to find a way to do it, despite investing several hours.

I'm happy to move this question to the forum, but as mentioned, [this](https://discourse.gohugo.io/t/how-to-list-pages-from-each-section-and-subsection/13950) was suggested there, and it did not work for me, hence this bug report.

I'd also like to know if it's intentional that `.Paginator` doesn't pick up the sub-section list pages. If it's expected that `.Paginator` only picks up regular pages, then the documentation should probably mention that. I'm happy to send a PR for that, if someone can confirm it's the intended behaviour.

Many thanks in advance!

**Comment by bep** [comment]
See 

https://github.com/amdw/hugorepro/blob/5733a9b579f716c9bfafdd4e9e3cc36a37078c6d/layouts/_default/list.html#L8

You must make sure to invoke either Paginate or Paginator, no both (the first will win). Take further questions on the forum.

**Comment by amdw** [comment]
Many thanks! You are right - the following commit fixes the problem:

https://github.com/amdw/hugorepro/commit/7eed5d6f5ab2038ae37d4356ee294109d1b645e0

The issue was that argument evaluation is eager, so using `cond` like this with two different paginator implementations does not work.

I will send a documentation pull request for this later.
