### ISSUE TITLE
Raise an error if .Paginator/.Paginate called with different collections

### ISSUE THREAD

**Issue by amdw** [gohugoio/hugo#7611]
On #7609 I learned that if there is more than one call to `.Paginator` or `.Paginate` during the course of generating a page, the user is unlikely to get the behaviour they expected. The first of these calls will always "win" in terms of generating the pagination side effects.

If I'm understanding correctly, the second and subsequent calls are never going to do anything useful, and allowing them does not seem to have any benefit.

I think it would be much more user-friendly to generate an error when there is more than one call to the pagination functions in the course of generating any page, rather than ignoring the second and subsequent calls and letting the first one "win". It would be much less surprising and confusing for the user.

Does that make sense, and is it possible?

Many thanks in advance!

**Comment by bep** [comment]
I think we did that at point, but we cannot throw and error if you do `.Paginate` etc. multiple times, that is perfectly normal (which is the main reason we cache the result of that operation). We would have to check that it's called with a different page set.
