### ISSUE TITLE
.Permalink behaves differently between server mode and in generated HRML

### ISSUE THREAD

**Issue by jernst** [gohugoio/hugo#7614]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

This seems to be the latest release.

### The Problem:

``.RelPermalink``, in ``hugo server`` mode, produces ``//localhost:1313/foo/bar/``.

``.RelPermalink``, in ``hugo`` HTML generation mode, produces ``/foo/bar/``.

That makes it difficult to produce some text, as I am just trying to do, that is the fully-qualified URL of a page (so if the user prints out the page, the URL of some other page appears in print). Because I tried in ``hugo server`` mode, everything looked fine (I prepended ``https:``) and then in live mode it was missing the hostname.

It would also be useful to define more clearly in the documentation what ``.RelPermalink`` is actually supposed to mean. Does it mean it generates ``../../somewhere/`` or ..? And ``.Permalink`` is supposed to contain the hostname, port, protocol etc etc or not? Examples would be helpful in the docs.

**Comment by bep** [comment]
What is the value of `baseURL`?

**Comment by jernst** [comment]
```
baseurl       = "/"
```

**Comment by bep** [comment]
Set that to a valid URL (e.g. `https://example.com`) and you should be good to go.

**Comment by jernst** [comment]
I don't want to do this, because I am running the same site in two places: one as a staging site, and one as a production site, and they have different hostnames.

Also, if '/' is an invalid setting, what about emitting an error message? In no case should it produce inconsistent output IMHO.
