### ISSUE TITLE
Improve warning message for missing layout file

### ISSUE THREAD

**Issue by richtera** [gohugoio/hugo#7617]
Currently when a layout file is missing the output is
[0] ROOT: WARN 2020/09/02 08:11:40 found no layout file for "JSON" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
It would be nice to add the corresponding content file path or something more about a proposed layout file name.

**Comment by jmooring** [comment]
![image](https://user-images.githubusercontent.com/335669/91980139-cdf85200-ecf4-11ea-8292-3c5c240b1b31.png)

**Comment by bep** [comment]
We have had several rounds with this discussion. The problem is, if you're missing a layout for kind `Page` and have a site with 10K pages, more context will flood the log and not be very helpful ... at all.

**Comment by richtera** [comment]
Totally agree. I was hoping to include the layout name if there was a layout defined so that at least all three "names" would be there.
