### ISSUE TITLE
Add a feature to index function to allow keys being a slice

### ISSUE THREAD

**Issue by richtera** [gohugoio/hugo#7618]
When calling `(index data "key" "subkey" "subsubkey")` it's hard to dynamically access the data. It would help a lot if index supported either `(index data "key.subkey.subsubkey")` or `(index data (slice "key" "subkey" "subsubkey"))` as well.
Otherwise to retrieve information by specifying the "index from a variable" is not easy.
Our current workaround to the problem is a partial. This reads the location in the data specified by .Params.data which is a slice assigned within our content.
```hugo
{{ $scratch := newScratch }}
{{ if .Params.data }}
  {{ $scratch.Set "data" $.Site.Data }}
  {{ range .Params.data }}
    {{ if $scratch.Values.data }}
      {{ $scratch.Set "data" (index $scratch.Values.data .) }}
    {{ end }}
  {{ end }}
{{ end }}
{{ return $scratch.Values.data }}
```

**Comment by bep** [comment]
Arrest me if I'm wrong, but I think that the last argument of `index` is a vararg, so this should work:

```bash
index $data key subkey subsubkey
```

I understand that that does not solve your question, but we have had many similar questions about the other vararg functions.

I'm not sure how easy this is, but it would be nice if we could do something ala:

```html
{{ index $data (expand $myslice) }}
```

/cc @moorereason

**Comment by richtera** [comment]
That would also be a great solution and more general to call any function with args from a slice. Does a pipeline fill varargs?

**Comment by bep** [comment]
>Does a pipeline fill varargs?

Yes. But note that I'm not totally sure how to solve this without doing any changes to the "Go stdlib runtime".

**Comment by richtera** [comment]
Right, kind of like `{{ index $data $myslice... }}` that would be cool.

**Comment by bep** [comment]
>{{ index $data $myslice... }}

Well, no, that may be a stretch.

**Comment by moorereason** [comment]
I wouldn't recommend `{{ index $data "1.2.3" }}` since that could be a valid index/key.  Assuming that `index` could be extended to support a slice of indices, you could accomplish the same thing with `{{ index $data (split "1.2.3" ".") }}`.

**Comment by richtera** [comment]
Ok, it might be easier to implement a new function `{{ indexIn $data $keySlice }}` for example. But I think both would be a great solution to the weird `{{ range ... }}` hack.
