### ISSUE TITLE
Hugo produces Unexpected Goldmark (CommonMark) Behavior 

### ISSUE THREAD

**Issue by HenrySkup** [gohugoio/hugo#7619]
> v0.74.3/extended darwin/amd64

Hi, This is in reference to [this thread](https://discourse.gohugo.io/t/not-sure-if-this-is-a-hugo-or-goldmark-bug/27985). 

Basically: Hugo is introducing a bug into Goldmark's HTML rendering when it encounters custom HTML elements (e.x. `<custom-element>...</custom-element>`) within markdown -- especially multi-line instances.  

----

When my markdown is:

```md
# Title 

<custom-element>
    <div>This will be "slotted" into the custom element.</div>
</custom-element>

```

the resulting HTML is :

```html
<h1>Title</h1>
<p><custom-element></p>
  <div>This will be "slotted" into the custom element.</div>
</custom-element>
```

----

As per the spec, the expected behavior should be :

```html
<custom-element>
  <div>This will be "slotted" into the custom element.</div>
</custom-element>
``` 

Note the lack of any `<p>` tags.

> **N.B.** 
> As per the spec, if the MD was `<custom-element></custom-element>` (one line) the resulting HTML should be wrapped in `<p>` tags.

**Comment by bep** [comment]
>Hugo is introducing a bug into Goldmark's HTML rendering 

Why is this a Hugo and not a Goldmark problem?

**Comment by jmooring** [comment]
I tested with direct usage of Goldmark, and it produced the expected results.

**Comment by jmooring** [comment]
Interesting find. Removing the hyphen from the custom element name resolves the problem. For example, this works:

```html
<customelement>
Foo
</customelement>
```

while this does not:

```
<custom-element>
Foo
</custom-element>
```

**Comment by schindld** [comment]
Just want to clarify this part:

> Per the HTML spec, custom elements must contain a hyphen in the name.

Browsers won't render custom elements properly unless they have a hyphen in their name. It treats it as an unknown tag (still renders its text content).

Hugo wrapping the custom element's tag in a <p> tag, breaks the custom element's layout if the layout contains any block-level elements...which is pretty common.

**Comment by schindld** [comment]
I just updated to hugo v0.80.0, and it's fixed!

**Comment by jmooring** [comment]
Confirmed that this is fixed. @HenrySkup, please close this issue.
