### ISSUE TITLE
i18n should respect .Site language

### ISSUE THREAD

**Issue by ABuffEr** [gohugoio/hugo#7620]
Hi,
I started to using Hugo a month ago or so, experiencing some issues with multilingual mode. To explain a bit, I have a lot of pages in Italian, that is main language, under /content, and some others in English, under /content/en/. Main (Italian) home lists posts from all languages, showing information (like date, "continue reading" label and comment counter) localized according to post language. Now, take reading label for example (comment counter is a little more complex, I wrote an article about it, that I'd like sharing for documentation). But to obtain this result I had to use .Site.Params.param mechanism, because of i18n always returns translation from (in this case) main home language, and I found no way to force it to other language.

**Comment by bep** [comment]
>f i18n always returns translation from (in this case) main home language

No that's not true, and there are plenty of sites out there to prove that.

Take further questions at https://discourse.gohugo.io/
