### ISSUE TITLE
Add EXIF data to images that are not page/global resources.

### ISSUE THREAD

**Issue by rhyst** [gohugoio/hugo#7636]
You can get exif data for images that are page or global resources:

https://gohugo.io/content-management/image-processing/#exif

You can also get data about images that are not page or global resources using `imageConfig`:

https://gohugo.io/functions/images/#imageconfig

By doing something like:

```
{{- range $index, $file := (readDir $filePath) }}
    {{- with (imageConfig $file.Name) }}
        // Do something with height/width
    {{- end }}
{{- end }}
```

But you the imageConfig function does not provide the exif data for these images. My use case is generating static image galleries where the images are kept separate to the site content (i.e. you have lots of images and don't want to commit them to a repo). This works well but it would be nice to get the exif data to extract the image descriptions for captions etc.

**Comment by jmooring** [comment]
You can [mount](https://gohugo.io/hugo-modules/configuration/#module-config-mounts) your external image directories to `assets`, then access the images as global resources. In config.toml, something like:

```
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "foo"
target = "assets/images/gallery"
```

**Comment by rhyst** [comment]
Thanks for your response, that looks interesting but can you loop over a directory using global resources? The documentation seems mostly about using single images, whereas I am trying to generate galleries without manually specifying every image.

Sorry if this is just me not understanding the documentation and again thanks for taking the time to respond.

**Comment by bep** [comment]
>can you loop over a directory using global resources

Yes.

Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by rhyst** [comment]
Is there a specific bit of the documentation that covers this? Like I said I could only find sections referring to use of single images

**Comment by bep** [comment]
See my last comment.
