### ISSUE TITLE
modules: Make ignoreVendor a glob pattern

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7642]
I've worked a little with module vendoring lately, and found a couple of issues that should be easy to fix.

There may be several reasons to do vendoring, but one may be that you want to mount a private repo. And in that situation comes a couple of situations:

1. You may not want/need to vendor all of the modules.
2. Currently, if you want to do edits in server mode on one of them, you would typically add a replace statement to `go.mod` and run the server. But if you have vendored your dependencies you must also remember to run with `hugo --ignoreVendor`. And that would require you to have access to all the remote modules (including the private one).

I suggest that we do two improvements:

1. Make `--ignoreVendor` a gob pattern so you can ignore just one/some packages, e.g. `--ignoreVendor **/private*`, default `**` (all).

2. Add a `noVendor` flag to the module imports config, meaning nothing would be written to `_vendor` for that module:

```toml
[[imports]]
path = "github.com/bep/myshortcodes"
noVendor=true
```

/cc @regisphilibert

**Comment by regisphilibert** [comment]
I've not played with vendoring too much yet. This makes a lot of sense though!
