### ISSUE TITLE
Add an experimental "hugo npm install" command

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7644]
I have been struggling with some npm (e.g. node_modules) dependency setup with Hugo Modules, and I suspect I'm not alone.

I have been avoiding this issue for some time now, but I think I'm going to try out something simple. I'll call this "experimental" in the sense that as a Hugo feature it may be changed or possibly even removed (if it doesn't really work) in a future version without too much notice.

The premise here is that 1) It's not really practically possible to specify "path to package.json" etc. when running "npm install" and 2) While there is a defined lookup order for `node_modules` folders, that order is strictly file system hierarchical -- which doesn't really match how Hugo works in this area.

So, my current idea is that:

* A Hugo module can have a `package.json` in its module root (which can be different from the Git repo root)
* In Hugo, we have a well defined import order for all of these

So, if we 

1. Loop these modules in reverse order
2. Write their package.json file to a (common) temp folder and run `npm install`
3. When done, move the `node_modules` folder to the main project.

/cc @regisphilibert @budparr does this sound wild enough?

**Comment by regisphilibert** [comment]
So this would mean all the imported Module's `package.json`s, merge their dep and devDep entries into one big list and install them all?

I can see it as a way for Hugo Modules to specify their won npm packages and so would avoid having to ask the user to install x or x npm package (PostCSS, Tailwind etc...). 

I'd love to play with that!

**Comment by bep** [comment]
>So this would mean all the imported Module's package.jsons, merge their dep and devDep entries into one big list and install them all?

Well, the end result will be _like that_, but I'm certainly not implementing that logic. My thinking is that a simple loop and then creating this "node_modules" overlay.

But I kind of don't know how this would work until I/we tried it out, hence the "experimental label".

**Comment by bep** [comment]
... maybe a merge of the dependency sections would be simpler/faster -- I will experiment.

**Comment by bep** [comment]
OK, I have thought a little more about this, and I think a good middle ground for this would be to:

* When running `hugo npm install` I will look for a `package.hugo.json` (and only that)
* The full dependency list will be written to `package.json`
* This way it will be really transparent what the final "thing" is -- and you can commit it to Git and it will build right out of the box on Netlify etc. And it would be easy to implement. 

Also, I've had a fair amount of Tailwind "minor version" breakage lately, so if I get time I will probably implement this using minimal version selection:
 
https://about.sourcegraph.com/blog/the-pain-that-minimal-version-selection-solves/
