### ISSUE TITLE
Dependabot opens PRs in Hugo forks.

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#7645]
Not sure how this can be fixed but the recent addition of dependabot.yml seems to activate it in Hugo forks.

See the flood of PRs in my fork over here:

https://github.com/onedrawingperday/hugo/pulls

Also there is an open issue about this behavior in the dependabot repo:

https://github.com/dependabot/dependabot-core/issues/2198

**Comment by davidsneighbour** [comment]
Quick and dirty fix: comment `@dependabot ignore this dependency` on each of the PRs. Quicker and dirtier fix: Block @dependabot from your fork.

**Comment by onedrawingperday** [comment]
Thanks @davidsneighbour will try blocking Dependabot.

Also I will leave this issue open for now. Maybe there will be a fix at some point.

**Comment by onedrawingperday** [comment]
Blocking Dependabot does not work. 

Currently they are asking users to delete old forks and then re-create them so the they are upfraded to v2 of dependabot that does not come with this issue! See this: [comment](https://github.com/dependabot/dependabot-core/issues/2198#issuecomment-649444075)

Lots of the 5.3K forks of Hugo were created before v2 of dependabot. Some these have Pull Requests history that users may not want to discard.

I left a comment at the dependabot repo over [here](https://github.com/dependabot/dependabot-core/issues/2198#issuecomment-690316728) but I don't expect a fix anytime soon.
