### ISSUE TITLE
AsciiDoc TableOfContents doesn't handle `code` properly

### ISSUE THREAD

**Issue by helfper** [gohugoio/hugo#7649]
When a title in AsciiDoc contains `` `inlined code` ``, it doesn't appear in the table of contents and multiple entries are created with the text surrounding it.

For example, this AsciiDoc:
```
== Some `code` in the title
```

Will generate a TOC with two entries pointing to the same place:

* Some
* in the title

(This is handled correctly in Markdown.)

**Comment by nancym** [comment]
I just installed v0.75.0/extended and none of my AsciiDoc TOCs are showing up. I use `:toc: macro`, which I wrote about in https://discourse.gohugo.io/t/asciidoc-and-toc-shortcode/19668/4. I really appreciate all the new AsciiDoc support so thank you all for that! For now, unfortunately, I need to revert to v0.74.3/extended.

**Comment by helfper** [comment]
@nancym That's because #7099 introduced a breaking change. I'm not a fan of the way things were done there, because it's a breaking change without leaving a flag to fall back on the previous behaviour. At the moment, it's not possible to preserve the ToC generated by Asciidoctor, you'd have to (re-)generate it on the Hugo side with the `.TableOfContents` variable.

**Comment by nancym** [comment]
Thank you for https://github.com/gohugoio/hugo/pull/7702#issue-488288326! Meanwhile I've played around with `.TableOfContents` in AsciiDoc layout files and will probably eventually use this so that my `.adoc` and `.md` content TOCs will look the same. But it's great to have the option to use pre-existing AsciiDoc TOCs.
