### ISSUE TITLE
Hugo extended for linux ARM processor

### ISSUE THREAD

**Issue by apoorvmote** [gohugoio/hugo#7657]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.74.3

</pre>

### Does this issue reproduce with the latest release?
Which file to use to install **extended hugo** on linux **ARM** computer.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by apoorvmote** [comment]
I have already asked that question https://discourse.gohugo.io/t/how-to-install-hugo-extended-on-linux-arm/28098

**Comment by bep** [comment]
... 4 hours ago?
