### ISSUE TITLE
downloaded zip file too large

### ISSUE THREAD

**Issue by ratheesh-kr** [gohugoio/hugo#7658]
### What version of Hugo are you using (`hugo version`)?

<pre>v0.74.3</pre>

### Does this issue reproduce with the latest release? Yes

Hello,

We are setting up hugo modules for our site.
We’re trying to mount a set of files  from a large private repo . The repo is about 1.00GB.

and we get an error like the following

**go get github.com/repo-name: downloaded zip file too large.**

Is there any limit to the repo size that we can mount? ad we have only master branch is there.

Can any one help us to solve the issue.

Thank you.

**Comment by bep** [comment]
This is backed by Go Modules. If I read their code correct, they have currently a hard-coded upper size-limit per module set at 512MB. This is unfortunate, but not something I can fix right now. So your best bet would be to split your repo into smaller modules, which may also make them easier to manage ...

**Comment by ratheesh-kr** [comment]
@bep Thank you for the confirmation.
