### ISSUE TITLE
Extend ability to get params from filename

### ISSUE THREAD

**Issue by b4D8** [gohugoio/hugo#7666]
Originally posted on the [forum](https://discourse.gohugo.io/t/set-page-params-from-filename/28122).

---

I believe the filename is the first, most natural and universal place to store basic metadata relative to a file's content, making it easy to sort, filter and select files, so we can find the file of interest and gain access to the information it contains. 

While Hugo relies on the files stored in the `/content` directory as its database, I find it could **leverage the filenames to be used to set params just like basic metadata** and make them really usable (like in a `range` in the context of a list of content).

Thanks to #4494 we already can can get both `date` and `slug` from filename.
My proposal is to extend this ability to other params like (by priority to me):

- `weight` because for long lists of content ordered by weight, it's way easier to have things shown in order in the filesystem and possibly be able to reorder content from the filename (so it removes the risk of inconsistency in the dual book if weight in filename is set in front-matter and replicated in the filename for ease of use).

- `date` without the format limitation: `YYYY-MM-DD` (for instance I would prefer `YYMMDD` reconciled with current century) and with `datetime` support (see #5974 and #7298).

- and possibly whatever custom param either set alone (`value` in filename and `key` in config toggler) or as `key:value` pairs.

For this ability to reach its full potential the behavior should be set in the config toggler including:
1. filename pattern and format definition (if not hardcoded like current `date`)
2. whether extracted values override the front-matter or serve as fallback

As for 1. I find @jmooring's [approach](https://discourse.gohugo.io/t/set-page-params-from-filename/28122/10) really convenient:

```
[frontmatter.books]
# Example: 2010-09-14_my-title_100.md
filenamePattern = `^(\d{4}-\d{2}-\d{2})_(.+)_(\d+)`
date = $1
title = $2
weight = $3

[frontmatter.movies]
# Example: 2010-09-14_99_my-title.md
filenamePattern = `^(\d{4}-\d{2}-\d{2})_(.+)_(\d+)`
date = $1
title = $3
weight = $2
```

As for 2. it would follow the same logic as #4494, extending the `:filename` "special date handler":

```
[frontmatter]
date = [":default",":filename"]
weight = [":filename",":default"]
title = [":default",":filename"]
```

This would also pave the way to have content without front-matter (see #6098 )

Of course, alternatively third parties do provide actual working solutions to override `.Page.Params`
  - Bash script like [this one](https://discourse.gohugo.io/t/set-frontmatter-params-in-list-template/14645/8)
  - [R](https://www.r-project.org/) users can also leverage [ymlthis](https://cran.r-project.org/web/packages/ymlthis/vignettes/introduction-to-ymlthis.html) wrapped in [blogdown](https://bookdown.org/yihui/blogdown/)'s function [yml_blogdown_opts](https://ymlthis.r-lib.org/reference/yml_blogdown_opts.html)

Hope this proposal will catch your attention.

Thanks for developing Hugo!

**Comment by jiacai2050** [comment]
I came across this when convert my Jekyll-style site to Hugo, I would like my posts organzied like `:year-:month:-:day-:slug.md`, and have url as `{root}/:year/:month/:day/:slug/`, maybe we can just extend permalinks to add a new keyword: `:jekyll`, and config looks like this

```toml
[permalinks]
  posts = "/:jekyll/"
```
related discussion: https://discourse.gohugo.io/t/extracting-date-and-slug-from-filename/8394/8
