### ISSUE TITLE
hugo new with "-c" parameter does not create files in correct content dir

### ISSUE THREAD

**Issue by KevinGimbel** [gohugoio/hugo#7676]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

---

I have a multi language site and when I create a new blog post with the following command the files are created in `content/en` instead of `content/de`.

```bash
$ hugo new -c content/de blog/2020-09-13-ich-buk-sauerteig-brot/index.md
/Users/kevingimbel/Development/private/kevingimbel.de/2020/content/en/blog/2020-09-13-ich-buk-sauerteig-brot/index.md created
```

I also tried with `-c de` but it always creates the file in the `content/en` directory.

### Expected behaviour

The content should be created in the correct content direcroty, `content/de`.

### Additional info

- My full `config.toml` is available at https://github.com/kevingimbel/kevingimbel.de/blob/master/config.toml

**Comment by kevingimbel** [comment]
I think the problem is here somewhere around: https://github.com/gohugoio/hugo/blob/master/commands/new.go#L84

From my example command above this would result in
```go
# createPath := args[0]
createPath := "blog/2020-09-13-ich-buk-sauerteig-brot/index.md"
```

but this does not contain any info about the content dir.

**Comment by zackertypical** [comment]
I have the same problem.
I use `hugo new zh/readme.md`, it created in the en folder
`/content/en/zh/readme.md created `

**Comment by jmooring** [comment]
Related to https://github.com/gohugoio/hugo/issues/5233
