### ISSUE TITLE
Drafts are shown always

### ISSUE THREAD

**Issue by MSVO** [gohugoio/hugo#7687]
![image](https://user-images.githubusercontent.com/12222151/93068232-d27c1d80-f699-11ea-906b-5070c19bcad7.png)

## Problem
Posts containing the property `draft: true` are not supposed to be served by default. But when I tried the [quickstart](https://gohugo.io/getting-started/quick-start/) example, drafts are shown. The drafts are served even after explicitly setting `buildDraft` to `false`
  
## Steps to reproduce issue
```
hugo new site myblog
cd myblog
git init
git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
echo 'theme = "ananke"' >> config.toml
hugo serve -D
```
  
The new post created by `hugo new` contains the following content
```
---
title: "My First Post"
date: 2020-09-14T14:31:35+05:30
draft: true
---
```

## Failed efforts to resolve the problem
1. Tried adding a line `buildDraft = false` in `config.toml`
2. Tried using another theme
  

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
>hugo serve -D

Remove the "-D" flag.

**Comment by MSVO** [comment]
My bad, I didn't know `-D` stands for `--buildDrafts`. Thank you.

> > hugo serve -D
> 
> Remove the "-D" flag.

My bad. Thank you.

For anyone who runs into the same issue, see `man hugo`. It says `-D` option is short for `--buildDrafts`.
