### ISSUE TITLE
Using "with" in conjunction with .Exif produces runtime error for PNG images

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#7688]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.76.0-DEV/extended linux/amd64 BuildDate: unknow
</pre>

### Does this issue reproduce with the latest release?

Yes.

### Background

The [documentation](https://gohugo.io/content-management/image-processing/#exif) and [this forum topic](https://discourse.gohugo.io/t/exif-error/20586/2) suggest using `with` to avoid errors when attempting to read EXIF data while ranging through a directory of images that contains one or more PNG files. Hugo's ability to read EXIF data is limited to the JPEG and TIFF formats.

### Problem

Using this approach results in "error calling Exif: runtime error: invalid memory address or nil pointer dereference."

### To reproduce the problem:

I will post a minimal failing example shortly.

**Comment by bep** [comment]
See my comment in the forum.

**Comment by jmooring** [comment]
The nested `with` does not seem to be working either.  Minimal failing example:

```
git clone --single-branch -b hugo-github-issue-7688 https://github.com/jmooring/hugo-testing hugo-github-issue-7688
cd hugo-github-issue-7688
hugo server
```

**Comment by jmooring** [comment]
Pushed minimal failing example again to fix comment syntax.

**Comment by bep** [comment]
OK, a PNG image, yes then I think I understand.
