### ISSUE TITLE
Anchor hyperlinks case sensitive

### ISSUE THREAD

**Issue by Stono** [gohugoio/hugo#7694]
Hey, 
Currently anchor links are rendered with the correct casing, but the `id` is subsequently rendered in lower case, thus breaking the anchor when your item contains an upper case character.

For example:
<img width="546" alt="Screenshot 2020-09-14 at 18 11 01" src="https://user-images.githubusercontent.com/1486729/93116776-a9698600-f6b5-11ea-9537-e0ebc0f9ae24.png">

However:
<img width="529" alt="Screenshot 2020-09-14 at 18 11 19" src="https://user-images.githubusercontent.com/1486729/93116819-b4241b00-f6b5-11ea-902e-c1686a52ea94.png">

**Comment by vitkhab** [comment]
Hey, @Stono. I was trying to investigate the issue but couldn't reproduce it. Can you provide source code of a test page and theme you are using?
