### ISSUE TITLE
Support More/All ESBuild options

### ISSUE THREAD

**Issue by HenrySkup** [gohugoio/hugo#7697]
Hi, ran across an issue trying to import an `.svg` and then have ESBuild resolve the import. (I'm. getting : `File extension not supported: ../logo.svg`).

As per [this issue](https://github.com/evanw/esbuild/issues/236) this should be possible if you are able to specify the `loader` option. 

From the Hugo docs, it is not clear how to specify this.  Could we map the options dict to the flag names to be able to access all the options?

[Full list of options](https://github.com/evanw/esbuild#command-line-usage)

**Comment by shafiemukhre** [comment]
@bep Is there a way to access all other ESBuild options? It is not clear to me as well from the [Hugo documentation](https://gohugo.io/hugo-pipes/js#options). For example I want to access [JSX factory](https://esbuild.github.io/api/#jsx-factory) and [JSX fragment](https://esbuild.github.io/api/#jsx-fragment) options in order for to use Preact inside Hugo, however I do not know to how to add this options in Hugo. Is this possible?

**Comment by shafiemukhre** [comment]
I solved this (only for ESBuild options to use Preact) after looking at this question on discourse: https://discourse.gohugo.io/t/javascript-build-jsx-factory/30268

`JSXFactory` and `JSXFragment` options are supported in the [source code](https://github.com/gohugoio/hugo/blob/d90e37e0c6e812f9913bf256c9c81aa05b7a08aa/resources/resource_transformers/js/options.go#L75), however it was not mentioned in Hugo JavaScript Building documentation page. Should I make a pull request to update this page: https://gohugo.io/hugo-pipes/js? 

I also created a minimal example of using Preact in Hugo with ESBuild, here is the public repo: [github.com/shafiemukhre/preact-hugo-esbuild](https://github.com/shafiemukhre/preact-hugo-esbuild)

**Comment by bep** [comment]
>Building documentation page. Should I make a pull request to update this page:

@shafiemukhre  Yes, please. but please do it in the docs repo.

As to adding "all options": ESBuild is evolving fast and he is adding options all the time; most option need some thinking on the Hugo side, so adding one option isn't cost free (at its minimal we need to update the documentation).
