### ISSUE TITLE
Do not fail when a partial is missing

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7706]
For background, see: https://discourse.gohugo.io/t/how-do-i-override-base-template-blocks-from-a-theme-component/28207/12?u=bep

I propose that for we cannot find the template in `partial` we return an empty string instead of failing.

This makes a lot of constructs much simpler, esp. in theme setups, and I don't see much negative effects.

```html
{{ with partial "mayExist" . }}The partial existed and returned/rendered: {{ . }}{{ end }
```

[![](https://api.gh-polls.com/poll/01EJEN10MPG1ES4FEDW7F2YY5Y/Yes%2C%20do%20not%20ERROR%20on%20missing%20partial%20template)](https://api.gh-polls.com/poll/01EJEN10MPG1ES4FEDW7F2YY5Y/Yes%2C%20do%20not%20ERROR%20on%20missing%20partial%20template/vote)
[![](https://api.gh-polls.com/poll/01EJEN10MPG1ES4FEDW7F2YY5Y/No%2C%20we%20need%20that%20to%20catch%20spelling%20mistakes%20in%20the%20templates%20etc.)](https://api.gh-polls.com/poll/01EJEN10MPG1ES4FEDW7F2YY5Y/No%2C%20we%20need%20that%20to%20catch%20spelling%20mistakes%20in%20the%20templates%20etc./vote)

**Comment by davidsneighbour** [comment]
How about a notice instead of an error?

**Comment by bep** [comment]
>How about a notice instead of an error?

Not sure what you mean by an "error"; but in my head: Either you define the above situation as a normal thing and use it as such (use `with` to wrap your optional theme partials) or you depend on the partial being there.

**Comment by davidsneighbour** [comment]
I see a difference between ERROR and WARN. Error stops the compilation of the site and a warning prints a warning on the CLI, but continues to compile the site. I understand the two options above as either print an error and stop compilation or stay silent about it and continue the compilation. A middle way imho would be to print a warning on the CLI. Maybe I am not really getting the issue though ;) 

On a deeper dive I think the following code would solve the issue for everyone:

```
{{ if templates.Exists ( printf "partials/%s" $partialPath ) }}
  partial exist and can be used
{{ else }}
  theme author can add instructions how to silence this message or add the partial
{{ end }}
```

... which makes me voting for "yes, do not error" now.

**Comment by rsolvang** [comment]
My problem is that `with` in combination with `partial` is not working as I expect it to. It would be intuitive if `with` works the same way as with undefined (nil) variables – no code and no error. This is how things currently behaves:

`{{ with .Params.something }}{{ . }}{{ end }}`
Silently ignored without errors if variable is not found.

`{{ with partial "doesNotExist" . }}{{ . }}{{ end }}`
Gives error if partial does not exist.

`{{ partial "doesNotExist . }}`
This throws an error as expected.

It would be very helpful for `{{ with partial "doesNotExist" . }}{{ . }}{{ end }}` to not throw errors in regards to building Theme Components.
