### ISSUE TITLE
hugo server shoud print a URL with protocol, not just //localhost:1313/

### ISSUE THREAD

**Issue by schoettl** [gohugoio/hugo#7709]
IMO this is a **usability issue for developers**:

`hugo server` prints
```
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
```

The developer always wants to open the address in the browser but they
1. cannot click the link
2. cannot use terminal shortcuts to open the link (e.g. Alt-U in urxvt)

I understand that the address is more generic this way – it suggests "use your protocol of choice".

But it would be better if `hugo server` would print
```
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
```

- This would be OK from security perspective if the server binds to 127.0.0.1
- The URL is click-able and can be opened via terminal shortcuts
- HTTPS doesn't work anyway by default (for me)

Would you accept an PR fixing this?

**Comment by davidsneighbour** [comment]
Check your config.toml. For me the http is printed in all hugo setups and is clickable in the terminal. The development server is not a production server, so https is not required.

**Comment by schoettl** [comment]
Oh, thanks. `baseURL` was set to `/` (which I took from a tutorial template).

Setting it to `https://domain.tld/` works.
