### ISSUE TITLE
Make "with partial" not give an error when partial does not exist

### ISSUE THREAD

**Issue by rsolvang** [gohugoio/hugo#7720]
I would like `with` in combination with `partial` not to produce a "partial not found" error. It would be intuitive if `with` works the same way as with undefined (nil) variables – no code and no error. This is how things currently behaves:

`{{ with .Params.something }}{{ . }}{{ end }}`
Silently ignored without errors if variable is not found / defined.

`{{ with partial "doesNotExist" . }}{{ . }}{{ end }}`
Gives error if partial does not exist.

`{{ partial "doesNotExist . }}`
This throws an error as expected and this behaviour should not be changed.

It would be very helpful for `{{ with partial "doesNotExist" . }}{{ . }}{{ end }}` _not_ to throw errors in regards to building Theme Components.

My current solution it to make use of empty inline partials, but I find it less elegant:
`{{ define "partials/some/directory/doesNotExist" }}{{ end }}{{ partial "some/directory/doesNotExist" . }}`

_Originally posted by @rsolvang in https://github.com/gohugoio/hugo/issues/7706#issuecomment-694862412_ (and slightly rewritten)

**Comment by davidsneighbour** [comment]
I read somewhere in Discourse that this is impossible because `with` does not know what the `partial` function does and the partial function is throwing the error (or warning?). Can you test if using `{{else}}` before the `{{end}}` silences it?

**Comment by rsolvang** [comment]
> Can you test if using `{{else}}` before the `{{end}}` silences it?
No, just tried it and it does not silence the error.

**Comment by jmooring** [comment]
Duplicate of https://github.com/gohugoio/hugo/issues/7706
