### ISSUE TITLE
Autoprefixer 10 / PostCSS 8 break Hugo build

### ISSUE THREAD

**Issue by inwardmovement** [gohugoio/hugo#7722]
[Autoprefixer 10](https://github.com/postcss/autoprefixer/releases/tag/10.0.0) / [PostCSS 8](https://github.com/postcss/postcss/releases/tag/8.0.0) break Hugo build:
```Error: Cannot find module 'postcss'```

Hugo version:
```Hugo Static Site Generator v0.74.1/extended windows/amd64```

https://github.com/postcss/postcss/issues/1421

Is there a quick workaround?

**Comment by inwardmovement** [comment]
Temporarily fixed by using `postcss-cli@7` and `autoprefixer@9`

**Comment by bep** [comment]
>Is there a quick workaround?

```
  "autoprefixer": "~9.7.6",
```

For the future, please take these issues up with the upstream projects, or ask on the forum.
