### ISSUE TITLE
amp-script Script hash not found or incorrect for amp-script

### ISSUE THREAD

**Issue by apoorvmote** [gohugoio/hugo#7729]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.75.1

</pre>

### Does this issue reproduce with the latest release?
Yes 

I get following error message
```
amp-script Script hash not found or incorrect for amp-script[script="hello-world"].js. 
You must include <meta 
name="amp-script-src" 
content="sha384-6FlT3Nsv_toaZHleLVjcNK4SLgMUAzs02tV7EQBsyC35AUB7twCU-QCQ_aE_bMiC"
>
```
The official [document](https://amp.dev/documentation/components/amp-script/?format=websites#calculating-the-script-hash) recommends following solution

```js
const crypto = require('crypto');
const hash = crypto.createHash('sha384');

function generateCSPHash(script) {
  const data = hash.update(script, 'utf-8');
  return (
    'sha384-' +
    data
      .digest('base64')
      .replace(/=/g, '')
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
  );
}
```
Here what I have tried 
### Trial1

```html
{{ $built := resources.Get "js/auth/sign-up.js" | resources.Fingerprint "sha384" }}
<meta name="amp-script-src" content={{$built.Data.Integrity}}>
``` 
I get the same error as above

### Trial 2
```html
{{hmac "sha384" }}
```
I get following error
```
error calling hmac: hmac: sha384 is not a supported hash function
```
### Trial 3
```html
{{ sha384 "my text" }}
```
I get following error
```
function "sha384" not defined
```
### Workaround
Yes if I copy paste from error then it work but 
- I cannot do this for 100's of files
- I run CI-CD to deploy website and I can't read error message there.

**Comment by blackb1rd** [comment]
**I believe this is not a hugo issue.**

Amp report hash of "hello-world.js" script error but your code is generate hash for "js/auth/sign-up.js" script.

And I think, amp need hash per script.

Are you sure the gohtml-template syntax is correct?

```html
{{ $built := resources.Get "js/auth/sign-up.js" | resources.Fingerprint "sha384" }}
{{<meta name="amp-script-src" content={{$built.Data.Integrity}}>}}
```
or below is the correct one?
```html
{{ $built := resources.Get "js/auth/sign-up.js" | resources.Fingerprint "sha384" }}
<meta name="amp-script-src" content={{$built.Data.Integrity}}>
```

**Comment by apoorvmote** [comment]
@blackb1rd 
I am sorry I made mistake while writing question
```
{{/*<meta name="amp-script-src" content={{$built.Data.Integrity}}>*/}}
```
That code was commented out while I tried other solution and I removed comment and copy pasted code. I actually tried the following and it threw the error
```html
<meta name="amp-script-src" content={{$built.Data.Integrity}}>
````

**Comment by apoorvmote** [comment]
@blackb1rd 
> Amp report hash of "hello-world.js" script error but your code is generate hash for "js/auth/sign-up.js" script.

hello-world is actually the ID of local component
```html
<script id="hello-world" type="text/plain" target="amp-script">
     {{ safeHTML (resources.Get "js/auth/sign-up.js").Content }}
</script>
```

**Comment by blackb1rd** [comment]
What is the output of {{$built.Data.Integrity}}?
What is the error?

**Comment by apoorvmote** [comment]
> What is the output of {{$built.Data.Integrity}}?

`<meta name="amp-script-src" content="sha384-OMiI23W1WG+LeiU1/NSlyPkihosxVO6vsKF0LhejhXG/WhfbR07cMEh1QpuyWThO">`

> What is the error?
```
error.js:208 amp-script Script hash not found or incorrect for amp-script[script="sign-up"].js. 
You must include <meta name="amp-script-src" 
content="sha384-ulXtuCCBszAzwyNAozMq3h_MAW2VeP2Gh7mRGojBrlLfOHWdxibAJmHTn5WE2K_4">. 
See https://amp.dev/documentation/components/amp-script/#script-hash.​​​
```

**Comment by blackb1rd** [comment]
Whitespace and newline is causing the output hash is different.
```html
<script id="hello-world" type="text/plain" target="amp-script">
     {{ safeHTML (resources.Get "js/auth/sign-up.js").Content }}
</script>
```

You code have the **whitespace** and **newline**.

**Example:**
"console.log('hello')" get result hash as "JEnTFJ+xD2h3lK6x+XlNmwfcn1hXQ0Ocp9IznvK/daQZ6OiHpYYu+r5yR0bCmug8"
"console.log('hello')\n" get result hash as  "Gr+7DoDmRwwOzrKNeTdzGQ8kUHKE7fQizSxxiVFvYg/bYLZPPe233BAERMdbH2GT"

I did check hugo generate the correct Fingerprinting:
"console.log('hello')" -> "JEnTFJ&#43;xD2h3lK6x&#43;XlNmwfcn1hXQ0Ocp9IznvK/daQZ6OiHpYYu&#43;r5yR0bCmug8"

And You could use [Replace](https://gohugo.io/functions/replace/) function to be the correct value as "JEnTFJ+xD2h3lK6x+XlNmwfcn1hXQ0Ocp9IznvK/daQZ6OiHpYYu+r5yR0bCmug8"

**Comment by apoorvmote** [comment]
@blackb1rd 
As mentioned in [question](https://github.com/gohugoio/hugo/issues/7729#issue-708239325) official document says to replace any `+` with `-`. There I could use [Replace](https://gohugo.io/functions/replace/) function.

> I did check hugo generate the correct Fingerprinting:
"console.log('hello')" -> "JEnTFJ+xD2h3lK6x+XlNmwfcn1hXQ0Ocp9IznvK/daQZ6OiHpYYu+r5yR0bCmug8"

How did you verify if that generated Fingerprinting passes validation for `amp-script`? Otherwise it's not correct.
