### ISSUE TITLE
Support making language content with `hugo new` in directory format

### ISSUE THREAD

**Issue by ngdangtu-vn** [gohugoio/hugo#7732]
So far, we can only create language content with `hugo new` in file format (`hello-world.en.md`). But making language content in dir format (`content/en/post/hello-world.md`) has it own advantange, and yet there is no support from `hugo new` for it. I think it's time for us to support this feature. My short-term proposal would be like this:
```bash
# long flag
hugo new post/hello-world.md --language-code en

# short flag
hugo new post/hello-world.md -c en # the `c` can be understood as content or code in language-code
```

In a long-term, my proposal would be a bit interactive CLI. So what do you think?

[A discussion from forum could be found here](https://discourse.gohugo.io/t/how-to-create-content-for-multiple-languages-with-hugo-new-command/28301)

**Comment by davidsneighbour** [comment]
Don't forget page bundles. I have a deep sitting issue that I grudgingly accept at the moment, a new leaf bundle has to be created via explicit `hugo new post/hello-world/index.md` call. 

Maybe this can be combined into a rework of how `hugo new post` works in general. 

Idea (without knowledge of how hugo internals work):
- add configuration variables that define
  - if a new post should create a post in all defined languages
  - if a new post should be created as leaf bundle or markdown file

Then running `hugo new post/something` will create a new post according to the configuration above.

**Comment by divinerites** [comment]
At the moment, we do not have a default language failover if there is a missing translation `lang.page.md`.
But sometimes we do not want an empty `lang.page.md`. So the solution is to be sure to have all language pages and for example copy `en.page.md` to `lang.page.md`. So we have a page in this language, even if it is in english.

So A good addendum would be to have an option to create the page in all declared languages.
Something ala `--language-code all`.
