### ISSUE TITLE
Hugo sometimes uses a wrong foldername for a multilingual site

### ISSUE THREAD

**Issue by Barsonax** [gohugoio/hugo#7733]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.75.1/extended windows/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

It seems that hugo sometimes uses a wrong foldername for a multilingual site. We have a markdown file named `demos.de.md` and it outputs the html to a folder named `demos` instead of `de`

The frontmatter of `demos.de.md`
```
{
  "title": "Live Demos",
  "summary": "Join us for a live product demo! ",
  "url": "/demos",
  "translationKey": "demos"
}
```

Our language section of our config:
```json
    "DefaultContentLanguage": "en",
    "languages": {
        "de": {
            "languageName": "Deutsch",
            "baseUrl": "",
            "languageCode": "de"
        },
        "en": {
            "languageName": "English",
            "baseUrl": "",
            "languageCode": "en"
        },
        "fr": {
            "languageName": "Français",
            "baseUrl": "",
            "languageCode": "fr"
        },
        "nl": {
            "languageName": "Nederlands",
            "baseUrl": "",
            "languageCode": "nl"
        }
     }
```

![image](https://user-images.githubusercontent.com/19387223/94278643-5c09d600-ff4b-11ea-9ee2-f4be35615df7.png)

![image](https://user-images.githubusercontent.com/19387223/94278577-472d4280-ff4b-11ea-9bd6-ed9738b52a44.png)

**Comment by davidsneighbour** [comment]
You "literally" telling Hugo to do exactly this with this line:

```
"url": "/demos",
```

Try `slug` instead of `url`.

**Comment by Barsonax** [comment]
> You "literally" telling Hugo to do exactly this with this line:
> 
> ```
> "url": "/demos",
> ```
> 
> Try `slug` instead of `url`.

No it should end up in `de/demos` instead of `/demos` because of the language. All the other markdown files have this in the frontmatter as well and there it works correctly.

**Comment by davidsneighbour** [comment]
Can you link a public sample repo to test this? My conspiracy theory would be, that "demos" starts with "de" and irritates hugo somehow, but that is quite an outlandish possibility.

**Comment by Barsonax** [comment]
Actually I also reproduced similar behavior with enos.en.md. It seems that if the file starts with the languagecode this happens.

**Comment by pamubay** [comment]
I believe it's related with this PR,

[fix RelURL and AbsURL when path starts with language #5369](https://github.com/gohugoio/hugo/pull/5369#issuecomment-553847078)

**Comment by Steiniche** [comment]
@davidsneighbour you can look at the PR @pamubay linked above it shows the exact behaviour and how to reproduce it.
It happens when the language code (en) is part of the slug (environmental) then the URL becomes /environmental and not /en/environmental.
@Barsonax The PR is now 2 years old and many of us have asked what can be done to get it merged but there is no answer for that yet I'm afraid.
The work around for you is to hardcode the URL e.g. in a menu you would do this:

```
        # /de/ is hardcoded into the URL due to this bug: https://github.com/gohugoio/hugo/pull/5369
      - identifier: demos
        url: "/de/demos/"
        name: "Demos"
```
