### ISSUE TITLE
Add a step in main Hugo README.md file on running after building with go

### ISSUE THREAD

**Issue by TahomaSoft** [gohugoio/hugo#7736]
### What version of Hugo are you using (`hugo version`)?
v0.75.1, from master branch on github
<pre>
$ hugo version
</pre>
### Does this issue reproduce with the latest release?
Yes.  Using the latest release.

## Problem Is ##
For a new user of go, it isn't clear what happens to the hugo executable after running the build instructions `go install.`
I suggest adding a short paragraph of looking in `$GOPATH/bin`. 

### Gotta Patch? ###
Yes. Sending pull request.

**Comment by DeathWofl** [comment]
apply for hacktoberfest?

**Comment by TahomaSoft** [comment]
The PR I put in isn't eligible for Hacktoberfest. A Berliner Weiẞe, maybe. :+)

**Comment by flatroof** [comment]
not sure if this is the relevant thread but i've just installed via brew and now have this 500M folder of go which is really not what i had intended.

So can i burn this go folder now or do i need to keep it around for eternity. as the home page said "There is lots of talk about “Hugo being written in Go”, but you don’t need to install Go to enjoy Hugo. Just grab a precompiled binary!" well i didn't know brew would install go, i assumed it just would pull the latest build.

```
du -hc /usr/local/Cellar/go/1.16.3
529M total
```

**Comment by flatroof** [comment]
ok.. so i did `brew uninstall go` and that worked fine. any other heavy i can remove? only have 250G SSD here.

**Comment by flatroof** [comment]
Others may have similar concern when first installing to see 500M gobble up. No need to be rude, i searched for what i thought was a relevant post as people who will build w go and who don't want to keep go around should be aware in the readme.
