### ISSUE TITLE
When enable the Sourcempas the Chrome Developer Tools shows the "stdin" as css file path and i cannot debug the SASS files

### ISSUE THREAD

**Issue by khanakia** [gohugoio/hugo#7744]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.75.1/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

I have just strated using hugo and i have searched in all the forums i did not find any way to solve this. What happening is i have hugo sourcemaps enabled for SASS files and i want to debug the css but it shows the stdin in developer tools and does not shows any _scss files path so i cannot know from which sass files that code is coming.

I am using this code 
```
{{ $options := (dict "targetPath" "assets/css/style.css" "outputStyle" "expanded" "enableSourceMap" true) }}
  {{ $style := resources.Get "sass/main.scss" | resources.ToCSS $options}}
  <link rel="stylesheet" href="{{ $style.Permalink | relURL }}">
```

<img width="1395" alt="Screenshot 2020-09-28 at 2 38 20 PM" src="https://user-images.githubusercontent.com/2174170/94413299-843a4480-0198-11eb-99ca-2b89e558dadb.png">

**Comment by bep** [comment]
This should work, but you need to point Chrome to your projects for it to resolve the paths correctly. I don't remember exactly, ask at the forum.

**Comment by davidsneighbour** [comment]
Click on tab "Sources", then look under localhost:1313 for your sass files. This is a support request for how to use chrome, not really Hugo related. 

- https://code.tutsplus.com/tutorials/developing-with-sass-and-chrome-devtools--net-32805
- https://www.sitepoint.com/using-source-maps-debug-sass-chrome/

**Comment by khanakia** [comment]
@davidsneighbour  Not exactly because i am working with HUGO in development mode and when in development mode HUGO serving files using PIPELINE and that's why it shows the ``stdin`` as file name as i shown in the screenshot above. So even if i map which i tried already the above solution you gave none of them is working. It's still says ``stdin``

**Comment by bep** [comment]
@davidsneighbour 's advice above is correct. It says `stdin` because it techically is that.
