### ISSUE TITLE
Improve shortcode doc for javascript code

### ISSUE THREAD

**Issue by djibe** [gohugoio/hugo#7745]
Hi, I don't know if there is a better solution, but it is the only way I found to write javascript in a shortcode.

https://discourse.gohugo.io/t/inner-javascripts-in-shortcodes-shows-as-pre/21095/8?u=djibe

I think it could be cool to add this to official doc.

Thx

**Comment by jmooring** [comment]
If you feel strongly about this, submit the issue to the documentation repository:
<https://github.com/gohugoio/hugoDocs>
