### ISSUE TITLE
Hugo server stops working after repeated restarts

### ISSUE THREAD

**Issue by FelixBenning** [gohugoio/hugo#7757]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.75.1-A4A7BAB7 linux/amd64 BuildDate: 2020-09-15T06:46:04Z 
</pre>
(docker hugo:ubuntu)

So I basically just went through the quickstart tutorial and now I tried out a bunch of themes. So I installed multiple themes as git submodules. For this reason I ended up repeatedly stopping and starting the server (inside a docker container).

The site started to load slower and slower until it just did not load at all. The F12 Network says that a lot of files were never received.

I tried

- passing `--network=host` to the docker container. (Maybe the network is the problem - now it shouldn't be (I think))
- repeatedly reloading with F5
- deactivate the browser cache in F12
- repeatedly reload again

it just did not reload. At that point it was late in the evening, so I just called it a day. Curiously I tried again today and things worked again in the beginning until it started to slow down again. Now firefox simply refuses to load the site.

During the writing of this report I realized that I have not yet tried a different browser: apparently edge works right now. I will give an update if edge shows the same behavior after some time.

It might also be a chache issue with firefox? I don't know.

**Comment by jmooring** [comment]
@FelixBenning Can we close this issue?

**Comment by FelixBenning** [comment]
forgot about this - I think I just installed hugo outside docker at some point did not encounter any issues there. No idea if docker is still acting up, maybe it is related to resource constraints within a docker container. Close it if you want :)
