### ISSUE TITLE
Hugo minify breaks sitemap.xml

### ISSUE THREAD

**Issue by adityatelange** [gohugoio/hugo#7766]
### What version of Hugo are you using (`hugo version`)?

`v0.75.1 linux/amd64 BuildDate: 2020-09-15T14:24:46Z`

### Does this issue reproduce with the latest release?
Yes. (Latest is v0.75.1 as of now)

---
With `hugo --minify`, hugo minifies everything including sitemaps.

Validatos give error: `XML declaration allowed only at the start of the document`.
Generally 1st line is meant only for xml tags declatarion : `<?xml version="1.0" encoding="utf-8" standalone="yes"?>` but minify makes everything in one line.

This also affects google search console's sitemap submittions and shows error as `Sitemap could not be read`.

p.s. Also is there any way we could disable minification for certain path or something ?

**Comment by davidsneighbour** [comment]
https://gohugo.io/getting-started/configuration/#configure-minify

**Comment by davidsneighbour** [comment]
Just in case you missed it (it's pretty invisible) there is a search field in the documentation site in the navigation bar. Maybe that field should be made white so be more prominent. Searching for "hugo --minify" turns up the link above that solves your issue.

**Comment by adityatelange** [comment]
> https://gohugo.io/getting-started/configuration/#configure-minify

Oh that's great! completely missed it. Thank you :)
