### ISSUE TITLE
Hugo 0.75.1 improperly escapes HTML in the header.html partial, while version 0.74.3 handled it correctly

### ISSUE THREAD

**Issue by CRCulver** [gohugoio/hugo#7769]
I am using Hugo 0.75.1 (0.75.1-1 as packaged by Debian bullseye) and I am experiencing an issue by which `{{ .Title | markdownify }}` does not work properly in the theme’s `header.html` partial (HTML is escaped instead of being passed through into the final output), while it does work properly in the theme’s `single.html` file (HTML is not escaped and is passed through to the final output). Specifically, the problem is as follows:

In my Hugo-based website, I often use `<span>` tags within my post titles. As an example, take a post where the title given in the header of the Markdown file is as follows:

```
title: 'This is a title with Spanish: <span lang="es">Hola!</span>'
```

In the single.html partial of my Hugo theme, `<h2 class="posttitle">{{ .Title | markdownify }}</h2>` works correctly, it passes `This is a title with Spanish: <span lang="es">Hola!</span>` to the final HTML of the page.

However, in the header.html partial of my Hugo theme, `<title>{{ .Title | markdownify }}</title>` does **not** work. Instead, Hugo passes an escaped string to the final HTML of the page: `<title>This is title with Spanish: &lt;span lang=&#34;es&#34;&gt;Hola!&lt;/span&gt;</title>`

I have created a [minimal working example](https://github.com/CRCulver/nonworking-blog/) in a Github repository.

Now, I posted a question [at Stackoverflow](https://stackoverflow.com/questions/64095087/hugo-do-not-escape-html-in-a-page-title-when-generating-title-tag-in-the-hea) under the assumption that there might be something wrong with my setup. However, in the Stackoverflow discussion thread, another user reports that he gets correct output on Hugo version 0.74.3. Therefore, has a bug been introduced into 0.75.1?

**Comment by davidsneighbour** [comment]
The "title" in the HEAD tag does not allow HTML, only inline text. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title

I did not test your repo, but it's probably the browser that encodes your tags there.

**Comment by CRCulver** [comment]
No, it is not the browser. Reading the raw HTML output generated by Hugo, it is clear that Hugo is escaping the HTML.

In fact, if the browser (Firefox in my case) got the unescaped HTML, it would handle it without problems. In spite of your link, `<span lang="XX">` tags in the `<title>` for the sake of language markup are common, and at least the W3C’s validator regards them as valid HTML.

**Comment by davidsneighbour** [comment]
What I am saying is, that if the tag would contain other HTML tags it would be improper content for the head>title tag. Maybe the change is not a bug but a fix. You can't have HTML in the title tag. You can have HTML in a h1-6 tag. The way Hugo handles it now is proper. I would strip all html in the title tag instead of transforming it.

**Comment by CRCulver** [comment]
Again, HTML in the `<title>` tag validates according to the W3C, so this is a reasonable matter for disagreement both according to the standard and according to real-world usage. What I am trying to ascertain with this Issue report is whether this change in Hugo 0.75.1 (if Hugo 0.74.3 really did handle it different) is intentional and documented.

**Comment by davidsneighbour** [comment]
Ok, I am clinking myself out now. Before I go, here is a screenshot of the specification of HTML. 

![Selection_048](https://user-images.githubusercontent.com/83281/95007276-1da1a480-0638-11eb-8614-36743aa28912.png)

**Comment by blackb1rd** [comment]
I belive, this is a hugo issue:

### partial

```html
 <title><span></span> {{ .Title | safeHTML  }}</title>
 <titlee><span></span> {{ .Title | safeHTML  }}</titlee>
{{ .Title | safeHTML  }}
```

### result:

`cat public/example.html`

```html
    <title>&lt;span>&lt;/span> This is a post with Spanish: &lt;span lang=&#39;es&#39;&gt;Hola!&lt;/span&gt;</title>
    <titlee><span></span> This is a post with Spanish: <span lang='es'>Hola!</span></titlee>
This is a post with Spanish: <span lang='es'>Hola!</span>
```

**Comment by jmooring** [comment]
Text is the only permitted content for the `<title>` and `<textarea>` elements per the HTML specification, and Hugo renders these elements accordingly. This is not a bug.
