### ISSUE TITLE
hugo mod clean fails if config.toml is invalid

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#7772]
```
Hugo Static Site Generator v0.75.1-A4A7BAB7/extended linux/amd64 BuildDate: 2020-09-15T06:57:20Z
```

I am experimenting with Hugo modules. A repo I have created as module is downloaded properly, but the config.toml in that repo has `config.toml` as content because I committed it this way ;) This is wrong and hugo server fails obviously. I try to clean the modules using `hugo mod clean` and it fails with the same error. 

```
[21:08:10][patrick@bookra] ~/Projects/Me/davids-neighbour.com (+1|%0|!12176|0)
❯ hugo mod clean
Error: failed to read module config for "github.com/davidsneighbour/davids-neighbour.com-fonts" in "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/davidsneighbour/davids-neighbour.com-fonts@v0.0.0-20201004141132-25953c904a35/config.toml": unmarshal failed: Near line 0 (last key parsed ''): bare keys cannot contain '.'
```

I think `hugo mod clean` should not try to verify anything in the modules it is supposed to remove.

**Comment by bep** [comment]
>I think hugo mod clean should not try to verify anything in the modules it is supposed to remove.

The module imports live in the config. We need to read that to do the job at hand.

**Comment by davidsneighbour** [comment]
I fail to understand that (no Go knowledge here). Could we just add a notice on this error to remove the /tmp/hugo-cache directory by hand?

**Comment by bep** [comment]
It's hard to be smart about every possible error situation.

In this case I guess ` hugo mod clean --all` would be the medicine.

**Comment by davidsneighbour** [comment]
works. closing this now :)
