### ISSUE TITLE
Make js.Build fully support modules

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7777]

**Comment by bep** [comment]
@richtera I have played with your PR a little in the last few days, but in the meantime I notice that ESBuild has a new `plugin` branch that looks to be mostly feature complete and about to be merged ... It has both a concept of resolver and loader, both of which looks to have some real potential once we wrap our head around it. 

Below is a rough draft of a resolver. It's missing some pieces and I'm not totally sure I understand all of the plugin API, but my initial tests with the below tells me that this could be the solution I have "dreamt about".


```go
Plugins: []func(api.Plugin){
			func(plugin api.Plugin) {
				plugin.SetName("hugo")
				plugin.AddResolver(api.ResolverOptions{Filter: ".*"},
					func(args api.ResolverArgs) (api.ResolverResult, error) {

						impPath := args.Path

						if args.Importer != "<stdin>" {
							relDir := fs.MakePathRelative(args.ResolveDir)
							impPath = filepath.Join(relDir, args.Path)
						}

						var m hugofs.FileMeta

						// First the path as is.
						fi, err := fs.Fs.Stat(impPath)

						if err == nil {
							if fi.IsDir() {
								if fi, err := fs.Fs.Stat(filepath.Join(impPath, "index.js")); err == nil {
									m = fi.(hugofs.FileMetaInfo).Meta()
								}
							} else {
								m = fi.(hugofs.FileMetaInfo).Meta()
							}
						} else {

						}

						if m != nil {
							return api.ResolverResult{Path: m.Filename(), Namespace: ""}, nil
						}

						// Set either Path or External to resolve.

						return api.ResolverResult{Path: "TODO", Namespace: "NAMESPACE"}, nil
					})

			},
```

**Comment by richtera** [comment]
Yes that could be used as well. Might work better since we wouldn't need to write any files. It wouldn't provide visibility to an IDE. Do you want to resolve this for an IDE or just for compile time? I see problems with IDE integration that would really get convoluted and complicated but if we solve only the compile time stuff I think that might be an appropriate first step.

**Comment by bep** [comment]
1) The primary goal is compile time, we can fix the editor issue later. 2) I had problems getting the tsconfig approach to work with modules (as in: Hugo Modules living on GitHub and imported by their path) beyond the simple use cases (I'm sure that's fixable) 3) The above is much faster and 4) It's easier to understand/maintain.

**Comment by richtera** [comment]
Ok. Sorry I got really busy the last few weeks. Hoping to get some time freed up.
