### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by vidhyav656** [gohugoio/hugo#7781]
https://github.com/gohugoio/hugo/pull/5159 following the discussion here. It would be great to consider the CoC again now. As Hugo has grown in huge scale and considering the community out there. Thank you.

**Comment by moorereason** [comment]
Is there an ongoing conduct problem in the community?

**Comment by davidsneighbour** [comment]
You know, in the Thai language there is no term for "maintenance", only for "repairs". Things have to be broken to be repaired while keeping them working properly (aka maintaining them) would save money, time and resources. I learned early on that maintaining something prepares you for when it's needed. So asking if there is an "ongoing" problem is like waiting until something breaks before we start thinking about how to repair. A code of conduct is quite easily creatable and would help in a lot of cases. One point would be issues that start with impolite wording. 

It will be easier to point to an existing COC when the time comes for it's use than start thinking about how to react to that case.

**Comment by saracope** [comment]
Also looking for a code of conduct for the community...
