### ISSUE TITLE
0.76.0 i18n .Count regression

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7787]
https://discourse.gohugo.io/t/0-76-0-i18n-gone-wrong/28689/5

**Comment by digitalcraftsman** [comment]
I've noticed this as well after upgrading the Hugo version for www.themes.gohugo.io (see [build logs](https://app.netlify.com/sites/hugothemes/deploys/5f7caa64310cfd0008abebf0)).

**Comment by digitalcraftsman** [comment]
The Hugo version for building www.themes.gohugo.io has been bumped to 0.76.2 earlier today. But the build log still shows the following error message that been appearing since 0.76.0:

    4:38:57 PM: Error: add site dependencies: load resources: loading translations: 
    "/opt/build/repo/minimo/i18n/oc.toml:1:1": failed to load translations: no plural rule registered for oc

**Comment by bep** [comment]
That is certainly not **this** particular issue.

**Comment by digitalcraftsman** [comment]
Shall I open a new one?
