### ISSUE TITLE
i18n build error when key contains dot

### ISSUE THREAD

**Issue by gabrielmaldi** [gohugoio/hugo#7794]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.76.2-207913F3/extended darwin/amd64 BuildDate: 2020-10-07T09:06:43Z
</pre>

### Does this issue reproduce with the latest release?

Yes

-----

When building, I get: `Error: add site dependencies: load resources: loading translations: "en.toml:1:1": failed to load translations: Near line 0 (last key parsed ''): bare keys cannot contain '.'`

This is my `en.toml` file:

```toml
shop_nextPage.other = "Show more"
```

If I quote the key (ie. `"shop_nextPage.other"`) I get: `i18n|MISSING_TRANSLATION|en|shop_nextPage`.

This worked fine in `0.75.1`, got broken in `0.76.0`.

Thanks!

**Comment by gabrielmaldi** [comment]
Just tested `v0.76.3` and can confirm fc6abc39c75c152780151c35bc95b12bee01b09c fixed this issue. Thanks!
Should I close it or are you keeping it open for another reason?

**Comment by 89z** [comment]
https://github.com/gohugoio/hugo/issues/7799
