### ISSUE TITLE
Check loading of language files for unknown languages

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7798]
```bash
"/opt/build/repo/minimo/i18n/oc.toml:1:1": failed to load translations: no plural rule registered for oc
```

I know we support this, but it may have changed subtly with the upgrade of go-i18n. Maybe we're using the languages defined in the project?

/cc @digitalcraftsman

**Comment by bep** [comment]
https://github.com/nicksnyder/go-i18n/issues/231

**Comment by digitalcraftsman** [comment]
I've just upgraded the theme site to the 0.76.3 release of Hugo and the error messages disappeared. Thanks for the bug fix 👍
