### ISSUE TITLE
i18n: Lang with symbol dash ("-") ex.: "pt-br" not render

### ISSUE THREAD

**Issue by MarlonLuan** [gohugoio/hugo#7804]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.76.3
</pre>

### Does this issue reproduce with the latest release?
Yes

In 0.75.1 its work

minimal reproducible:
https://github.com/MarlonLuan/hugo-0.76.x

**Comment by bep** [comment]
It's a bug and I will fix it, but the explanation is that we have suddenly become case sensitive as to the official language code casing, so. `pt-BR` works ... But I will make sure so both works.
