### ISSUE TITLE
Feature request: Support templating in content files

### ISSUE THREAD

**Issue by wiseman** [gohugoio/hugo#7815]
Is there a reason I can't use Go template expressions in content/markdown files?

**Comment by davidsneighbour** [comment]
Because it's Markdown. If you want to add template logic to content files you use Shortcodes.

**Comment by pamubay** [comment]
You can use [Inline Shortcodes](https://gohugo.io/templates/shortcode-templates/#inline-shortcodes)

**Comment by wiseman** [comment]
@pamubay Thanks, that gets the functionality at least. Though it seems strange that Hugo makes it more inconvenient to access the template language just because you're in a content file, right?  Is there any principled reason that there isn't an `enableTemplatesInContent` param, that lets me use the template language directly, without having to go through the extra work and complexity of defining a shortcode, which may only be used in one place?

@davidsneighbour I mean, it's not really just markdown, right, since shortcodes can be used? Something is already processing the markdown, looking for and evaluating shortcodes.

**Comment by davidsneighbour** [comment]
https://gohugo.io/content-management/shortcodes/#what-a-shortcode-is

> Hugo loves Markdown because of its simple content format, but there are times when Markdown falls short. Often, content authors are forced to add raw HTML (e.g., video <iframe>’s) to Markdown content. We think this contradicts the beautiful simplicity of Markdown’s syntax.
> 
> **Hugo created shortcodes to circumvent these limitations.**

**Comment by wiseman** [comment]
I find that having to create one-off shortcodes is significantly less elegant, and more verbose than allowing the use of the template language in content. I'm forced to have some of my content in another file, in a completely different directory. Why not offer the choice to users?

I feel like there's a bit of a parallel with anonymous functions. You don't need them; You can always create a named function. But in practice, the overhead of creating a named function is actually significant (and in this case, essentially, I need to create a named function in another file.)

**Comment by bep** [comment]
>I find that having to create one-off shortcodes is significantly less elegant, and more verbose than allowing the use of the template language in content. I

It has been mentioned earlier in this thread. You can inline shortcodes.
