### ISSUE TITLE
capitalized menu.main.url and content subdirectory not work with disablePathToLower = true 

### ISSUE THREAD

**Issue by asepsiswu** [gohugoio/hugo#7819]
##  hugo generates files with lower-case folder when disablePathToLower = true 

config.toml
disablePathToLower = true
[[menu.main]]
    url = "/Post/"
    name = "Posts"
    weight = 3

content/Post  

-   http://localhost:1313/Post/  is in the list page and `disablePathToLower = true` works, but it is blank.  
-   However,  http://localhost:1313/post/  is not blank .
-   **both Post and post directory exist in public folder**

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.75.1/extended linux/amd64 BuildDate: unknown

$ uname -a
Linux asepsiswu 5.8.11-1-MANJARO #1 SMP PREEMPT Wed Sep 23 14:35:40 UTC 2020 x86_64 GNU/Linux

</pre>

### Example test case

``` bash
hugo new site quickstart
cd quickstart
git init
git submodule add https://github.com/calintat/minimal.git themes/minimal

# use exampleSite config and content
cp themes/minimal/exampleSite/config.toml .
cp -r themes/minimal/exampleSite/content .

# add disablePathToLower = true  at top
sed -i '1 i\disablePathToLower = true' config.toml

# change main.menu post to Post
sed  -i 's:post/:Post/:' config.toml

mv content/post content/Post                      

# generate public files
hugo

## post and Post directory exist  
ls public 

hugo server -D

```

**Comment by pamubay** [comment]
Actually it's unrelated with the menu. 

The **real bug** is the section and its paginated pages does not respect the `disablePathToLower` flag.

the **regular pages** correctly rendered under `Post`,
```
/Post/creating-a-new-theme/index.html
/Post/goisforlovers/index.html
/Post/hugoisforlovers/index.html
...
```

But, **the section and it's paginated pages** rendered under `post`
```
post/index.html
post/page/1/index.html
...
```
