### ISSUE TITLE
hugo server fails to serve the site when baseURL contains a subpath without hostname

### ISSUE THREAD

**Issue by yihui** [gohugoio/hugo#7823]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.76.4
</pre>

### Does this issue reproduce with the latest release?

Yes.

### Reproducible example

Here is a small reproducible example: [server-baseurl.zip](https://github.com/gohugoio/hugo/files/5366829/server-baseurl.zip)

In `config.yaml`, it has `baseurl: "/subpath/"`. Then we run `hugo server`:

```
Start building sites … 

                   | EN  
-------------------+-----
  Pages            | 32  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  2  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 87 ms
Watching for changes in .../{content,layouts,themes}
Watching for config changes in .../config.yaml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:1313///subpath/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

Open http://localhost:1313///subpath/ and it shows `404 not found`. http://localhost:1313/subpath/ and http://localhost:1313 don't work, either.

It works if I specify the full URL like `baseURL: http://example.org/subpath/`, but I prefer not hardcoding the protocol or domain in the base URL.

**Comment by bep** [comment]
That is not a valid baseURL.

**Comment by yihui** [comment]
I'm sure it worked before, although I'm not sure which version of Hugo broke it. Being able to set a base URL without the protocol or hostname makes the generated website more portable, i.e., the site can be moved to any domain and works with any protocols.

**Comment by yihui** [comment]
Okay, it seems to work again if I remove the leading slash, i.e. use `baseURL: subpath/` instead of `baseURL: /subpath/`. I'm closing this issue for now. Thank you!
