### ISSUE TITLE
Failed to get translated string for language "art-x-language"

### ISSUE THREAD

**Issue by maximilian-lindsey** [gohugoio/hugo#7838]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.76.5

</pre>

### Does this issue reproduce with the latest release?

Yes and also with version 0.76.4.

It **doesn't happen** with version 0.74.0

### Problem

We are getting a long list of warning for like this for all our languages ("de","fr","es","it","nl","fr-be","nl-be", "pl", "bg", "ro", "hu", "cz","com","at"), that causes our build pipelines buffer to exceed it's limits:

16:12:12  WARN 2020/10/15 14:12:12 Failed to get translated string for language "art-x-cz" and ID "ratings": %!s(<nil>)
16:12:12  WARN 2020/10/15 14:12:12 Failed to get translated string for language "art-x-cz" and ID "showmore": %!s(<nil>)
16:12:12  WARN 2020/10/15 14:12:12 Failed to get translated string for language "art-x-cz" and ID "techdata": %!s(<nil>)
16:12:12  WARN 2020/10/15 14:12:12 Failed to get translated string for language "art-x-cz" and ID "defaultHeadline": %!s(<nil>)
16:12:12  WARN 2020/10/15 14:12:12 Failed to get translated string for language "art-x-cz" and ID "showmore": %!s(<nil>)
16:12:12  WARN 2020/10/15 14:12:12 Failed to get translated string for language "art-x-cz" and ID "homepage": %!s(<nil>)
16:12:12  WARN 2020/10/15 14:12:12 Failed to get translated string for language "art-x-cz" and ID "Modelle": %!s(<nil>)
16:12:12  WARN 2020/10/15 14:12:12 Failed to get translated string for language "art-x-cz" and ID "techdata": %!s(<nil>)
16:12:12  WARN 2020/10/15 14:12:12 Failed to get translated string for language "art-x-cz" and ID "showmore": %!s(<nil>)
16:12:12  WARN 2020/10/15 14:12:12 Failed to get translated string for language "art-x-cz" and ID "introtext": %!s(<nil>)
16:12:12  WARN 2020
16:12:12  
16:12:12  Build failed: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded

There is no trace of any language "art-x-cz or similiar in our codebase.

Could you please look into this?

Thanks a lot for your support

**Comment by maximilian-lindsey** [comment]
Maybe this is related to https://github.com/gohugoio/hugo/issues/7822 ?

**Comment by mhuberas24** [comment]
this is only the case for the "artifical" languages we use. In our case com, cz, and test. Renaming _index.cz.md to _index.cs.md and changing the configs rermoved the above mentioned error. So it seems to be related how hugo (go) handles the custom languages

**Comment by bep** [comment]
I will have a look at this soonish, but today I'm busy busy with other things. This i18n upgrade from v1 to v2 was certainly more painful than I expected, but hopefully it's worth it.

**Comment by goose3228** [comment]
I'm having the same issue, had to downgrade to 0.75, but was unable to reproduce outside of CI - worked fine locally.

**Comment by rue2020** [comment]
...same thing here, confirmed for 7.6.5 - not a dealbreaker, since page renders fine, nevertheless a bit concerning.

**Comment by rue2020** [comment]
confirmed for version 7.7.

**Comment by maximilian-lindsey** [comment]
I got the warning locally again when I just ran it with Hugo Static Site Generator v0.78.0/extended darwin/amd64

**Comment by jmooring** [comment]
Does anyone have a minimal reproducible example of this with v0.82 or later?

**Comment by dbelcher** [comment]
> Does anyone have a minimal reproducible example of this with v0.82 or later?

Sent a minimal sample to reproduce this via PM.

**Comment by jmooring** [comment]
@dbelcher Thank you.

Minimal reproducible example...

The `layouts/_default/single.html` template calls `i18n` twice, once for a singular translation, and once for a plural translation.

```bash
git clone --single-branch -b hugo-github-issue-7838 https://github.com/jmooring/hugo-testing hugo-github-issue-7838
cd hugo-github-issue-7838
hugo server
```

Results:

```text
WARN 2021/04/09 13:51:15 Failed to get translated string for language "art-x-kr" and ID "cat": %!s(<nil>)
WARN 2021/04/09 13:51:15 Failed to get translated string for language "art-x-kr" and ID "cat": %!s(<nil>)
WARN 2021/04/09 13:51:15 Failed to get translated string for language "art-x-tw" and ID "cat": %!s(<nil>)
WARN 2021/04/09 13:51:15 Failed to get translated string for language "art-x-tw" and ID "cat": %!s(<nil>)
```

Now comment out the Japanese and Korean sections in `config.toml` and run `hugo` again:

```text
WARN 2021/04/09 13:53:00 Failed to get translated string for language "art-x-tw" and ID "cat": %!s(<nil>)
WARN 2021/04/09 13:53:00 Failed to get translated string for language "art-x-tw" and ID "cat": %!s(<nil>)
```

Now do this:

```bash
rm i18n/jp.toml i18n/kr.toml
hugo
```

No warnings. I don't understand.

**Comment by rockingdice** [comment]
I've experienced the same issue with latest version `hugo v0.82.1-60618210`
I used custom language 'cht' and 'jp', they cannot be translated correctly. I've upgraded the client from a fairly old version (~2019), is there anything that I missed like any configuration?
