### ISSUE TITLE
Individual Theme per Language not working

### ISSUE THREAD

**Issue by hanneskuettner** [gohugoio/hugo#7845]
When trying to set the theme(s) for a specific language only hugo does not seem to apply the theme at all.

I verified that for the following configuration hugo only resolves theme layouts when the `theme-common` is enabled for all languages but not if it's only enabled for specific languages.

```
baseURL = "http://example.org/"
title = "My New Hugo Site"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
#theme = ["theme-common"]

[languages]
    [languages.en]
        languageCode = "en"
        weight = 1
        contentDir = "content/en"
        theme = ["theme-common"]
```

I prepared a small test repository that demonstrates the problem. 
https://github.com/hanneskuettner/hugo-theme-for-language

I would expect hugo to render the `index.html` with the content "Single Common" from the `theme-common` layouts `single.html` file but instead I get the warning `found no layout file for "HTML" for kind "page":` and an empty page.
This works as expected if you uncomment line 6 in the `config.toml`.

I've had a look in the `globalOnlySettings` variable and could not find `theme` in the as such I would expect this to work.
https://github.com/gohugoio/hugo/blob/5914f91b6c980e42693661d5fd5640e237691df6/langs/language.go#L33

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.76.5/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
That is not a feature/supported in Hugo.

**Comment by hanneskuettner** [comment]
That's a shame! I guess I will close this issue then.
Maybe we should start documenting which settings are supported per language and which aren't because so far I've found information all over the place, e.g. [your own quote from two years ago](https://discourse.gohugo.io/t/solved-enable-disable-custom-output-format-per-language/14103/5).

**Comment by shauntarves** [comment]
Is this something that can be added to the feature roadmap?
