### ISSUE TITLE
Read PNG file headers

### ISSUE THREAD

**Issue by Arty2** [gohugoio/hugo#7857]
Allow to read the headers of local (?) files to extract arbitrary information. In my case, this will allow to [read transparency](https://stackoverflow.com/a/41302302/2798678) details from well-formed PNG headers.
I am not familiar with Golang, but perhaps related to methods provided in [pkg/mime](https://golang.org/pkg/mime/multipart/).

Original community thread: [Detect transparency in image resource with imageConfig (?)](https://discourse.gohugo.io/t/detect-transparency-in-image-resource-with-imageconfig/28889/3)

**Comment by bep** [comment]
A proposal needs to be more concrete. I certainly don't know how to extract "arbitrary information" from a file and make that into something general usable.

**Comment by Arty2** [comment]
You're right, it cannot be abstracted like that. Let me try to reformulate this into something more specific for PNG images:

This proposal is about implementing a method to extract the [IHDR headers](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.IHDR) from PNG images. These headers store information about an images width and height, Bit depth, compression, transparency etc.

Reading the headers only (assuming the PNG is well formed) could return an object similar to the EXIF information from JPEG files.
