### ISSUE TITLE
Remove duplication of menu

### ISSUE THREAD

**Issue by trinhpham** [gohugoio/hugo#7859]
Hi guys,

I am facing an issue that my site has a lot of pages (~9k) so the generated menu part seems to be very big (~1.8MB). It is included into every single page, so you can guess the total duplicated size I have to put into the host.
Should we separate the menu part into single file then dynamically load it when a page is loaded?

Thanks

**Comment by davidsneighbour** [comment]
It's your themes task to do that, not Hugos. Have a look at partials and partialCached specifically: https://gohugo.io/functions/partialcached/#readout
