### ISSUE TITLE
RelPermalink on images used in srcset attribute does not result in same path as in src attribute 

### ISSUE THREAD

**Issue by petebannister** [gohugoio/hugo#7863]
hugo version 
Hugo Static Site Generator v0.76.5/extended windows/amd64 BuildDate: unknown

(choco package)

```
<img srcset="
          /img/burne_jones-kode_exhibition_hu75f5943da3c6e5da83f05a89648fc3dd_67639_240x0_resize_q75_box.jpeg 240w,
          /img/burne_jones-kode_exhibition_hu75f5943da3c6e5da83f05a89648fc3dd_67639_320x0_resize_q75_box.jpeg 320w,
          /img/burne_jones-kode_exhibition_hu75f5943da3c6e5da83f05a89648fc3dd_67639_600x0_resize_q75_box.jpeg 600w,
          /img/burne_jones-kode_exhibition_hu75f5943da3c6e5da83f05a89648fc3dd_67639_1200x0_resize_q75_box.jpeg 2x" 
    src="../../../img/burne_jones-kode_exhibition_hu75f5943da3c6e5da83f05a89648fc3dd_67639_600x0_resize_q75_box.jpeg"
    alt="" draggable="false">
```
This is more of an issue for sites that use a sub-path.

**Comment by jmooring** [comment]
Related to https://github.com/gohugoio/hugo/issues/8734

**Comment by petebannister** [comment]
Is this fixed?

**Comment by davidsneighbour** [comment]
> Is this fixed?

Follow the initial issue at #8734.

**Comment by petebannister** [comment]
The later issue #8734 does not mention srcset which would require much more specific processing than other attributes that can contain URLs.  Seems related but actually different.

**Comment by petebannister** [comment]
Ok actually it does mention srcset - should have read all the comments more clearly
