### ISSUE TITLE
Adding a render hook for blockquotes

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#7876]
Short version: I propose to add a render hook for blockquote markup. Current Markdown just adds a blockquote tag around it, but I would like "better quotes" in my code.

Long version:

- I have a shortcode currently that adds a blockquote with some extra formats: `{{< quote source="link to the source" title="title for the source link" >}}quote{{</quote>}}` will add some code with a `cite` element and in there a link to the source
- Using [remark](https://github.com/remarkjs/remark) and [remark-lint-write-good](https://www.npmjs.com/package/remark-lint-write-good/v/1.2.0) will mark my shortcode as bad quite often because I am employing a "no passive voice" policy and people in quotes tend to talk a lot in passive voice.
- I have to add manually `<!--lint disable write-good-->` brackets around these shortcoded quotes
- using remark on a simple blockquote markdown line (`> the quote`) does not fail (seems like they already catch language by "others", but I can't add a link to the source. 

Another workaround would be:

```
> The secret to creativity is knowing how to hide your sources. 
> -- <cite>[Albert Einstein][1]</cite>

[1]: http://www.quotedb.com/quotes/2112
```

but that introduces HTML into my markdown which I consider bad style too.

**Comment by maelle** [comment]
Although I had not thought of blockquotes, this reminds me of my wondering about render hooks for all sorts of tags. https://discourse.gohugo.io/t/markdown-render-hooks-for-all-the-things/28782

**Comment by bep** [comment]
I have said this before, but: we're not adding render hooks for "all sorts of tags", including blockquotes. Adding styles to tags needs another solution.

**Comment by davidsneighbour** [comment]
The cite element is not a style. It's a sub-element to demark the source of a blockquote. You closed this without reading the issue on top. There is no way to write a cite element with proper markdown and without adding HTML to the markdown.

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite
- https://stackoverflow.com/questions/2002120/citing-the-author-of-a-blockquote-using-markdown-syntax

**Comment by maelle** [comment]
PS: yes I used the wrong word, tag, and created confusion sorry. :see_no_evil:

**Comment by bep** [comment]
See #7548
