### ISSUE TITLE
Make the nodeploy build tag into deploy (default off) and create a separate build

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7878]
We recently introduced a `nodeploy` build tag, allowing people to opt out of the `hugo deploy` feature.

I'm considering if it would be a good idea to disable that in the default + extended builds and add another (for MacOS, Linux and Windows) built with deploy+extended.

**Comment by jmooring** [comment]
I understand why we currently need two builds, but it causes problems. This is a _partial_ list of forum topics resulting from users installing the wrong build:

- <https://discourse.gohugo.io/t/12831>
- <https://discourse.gohugo.io/t/13844>
- <https://discourse.gohugo.io/t/13913>
- <https://discourse.gohugo.io/t/14933>
- <https://discourse.gohugo.io/t/15555>
- <https://discourse.gohugo.io/t/17627>
- <https://discourse.gohugo.io/t/20182>
- <https://discourse.gohugo.io/t/24858>
- <https://discourse.gohugo.io/t/25887>
- <https://discourse.gohugo.io/t/27224>
- <https://discourse.gohugo.io/t/27333>
- <https://discourse.gohugo.io/t/27632>
- <https://discourse.gohugo.io/t/27933>
- <https://discourse.gohugo.io/t/28042>
- <https://discourse.gohugo.io/t/28264>
- <https://discourse.gohugo.io/t/28315>
- <https://discourse.gohugo.io/t/28550>
- <https://discourse.gohugo.io/t/28791>

Improving the error message might reduce the number of forum topics created, but it would not reduce the number of erroneous installations.

I am concerned that a third installation option might create more problems than it solves.

**Comment by bep** [comment]
>I understand why we currently need two builds

So, this issue isn't about removing a build, and I do think that this is slightly different than the `extended` version thing, which doing the numbers game would probably show up as a feature most people want/uses vs `hugo deploy` that very few uses? But I see your point, I just raised this topic to think about it. The `deploy` command adds lots of dependencies and megabytes to the build.
