### ISSUE TITLE
Hugo is rendering newlines from shortcodes

### ISSUE THREAD

**Issue by Barsonax** [gohugoio/hugo#7887]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.76.5/extended windows/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

### Problem

Hugo seems to render additional newlines which messes up the layout

Input
```md
{{< callout >}}
**Note**: You can view the other selectors by clicking the ellipsis {{< AppElement type="button" >}}...{{< /AppElement >}} in the selector value field.
{{< /callout >}}
```

Callout shortcode
```html
<div class="callout">
  {{ .Inner | markdownify }}
</div>
```

AppElement shortcode
```html
{{ $classes := (dict "menuitem" "v--menuItem" "button" "v--button" "savebutton" "v--button v--save" "tab" "v--tab") }}
{{ $key := .Get "type" }}
{{ $class := index $classes $key }}
<span class="a-appElement {{ $class }}">
  {{ .Inner | markdownify }}
</span>
```

Output:
```html
<div class="callout">
<p><strong>Note</strong>: You can view the other selectors by clicking the ellipsis</p>
<span class="a-appElement v--button">
  …
</span> in the selector value field.

</div>
```

### Workaround
This seems to be caused by newlines in the AppElement shortcode. Removing these fixes the layout issue however Hugo should remove these itself as it leads to some very ugly oneliner code:

AppElement shortcode
```html
{{ $classes := (dict "menuitem" "v--menuItem" "button" "v--button" "savebutton" "v--button v--save" "tab" "v--tab") }}{{ $key := .Get "type" }}{{ $class := index $classes $key }}<span class="a-appElement {{ $class }}">{{ .Inner | markdownify }}</span>
```

Output:
```html
<div class="callout"><strong>Note</strong>: You can view the other selectors by clicking the ellipsis <span class="a-appElement v--button">…</span> in the selector value field.</div>
```

**Comment by capnfabs** [comment]
FWIW you can use `-` at the start and end of template calls to remove leading / trailing whitespace.

For example:

```
{{ $classes := (dict "menuitem" "v--menuItem" "button" "v--button" "savebutton" "v--button v--save" "tab" "v--tab") -}}
{{ $key := .Get "type" -}}
{{ $class := index $classes $key -}}
<span class="a-appElement {{ $class }}">
  {{- .Inner | markdownify -}}
</span>
```

If you need to get rid of a newline at the end of the file (because your editor adds it automatically or something) you can write something like this as your last line:
```
{{- /*Chomp chomp */ -}}
```

Which does nothing (it's a comment!), except for remove leading and trailing whitespace.

**Comment by Barsonax** [comment]
> FWIW you can use `-` at the start and end of template calls to remove leading / trailing whitespace.
> 
> For example:
> 
> ```
> {{ $classes := (dict "menuitem" "v--menuItem" "button" "v--button" "savebutton" "v--button v--save" "tab" "v--tab") -}}
> {{ $key := .Get "type" -}}
> {{ $class := index $classes $key -}}
> <span class="a-appElement {{ $class }}">
>   {{- .Inner | markdownify -}}
> </span>
> ```
> 
> If you need to get rid of a newline at the end of the file (because your editor adds it automatically or something) you can write something like this as your last line:
> 
> ```
> {{- /*Chomp chomp */ -}}
> ```
> 
> Which does nothing (it's a comment!), except for remove leading and trailing whitespace.

This seem to fix the issue entirely without having to resort to ugly code. Thanks!
