### ISSUE TITLE
{{ $paginator := .Paginate (where .Data.Pages "Type" "posts") }} returned content is wrong in the version above hugo 0.56

### ISSUE THREAD

**Issue by MarcoEpsilon** [gohugoio/hugo#7894]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.56.0-45F4EB98 linux/amd64 BuildDate: 2019-07-25T16:38:06Z
</pre>

### Does this issue reproduce with the latest release?
The problem is still exist above hugo version 0.56

**Comment by Jos512** [comment]
What does 'content is wrong' mean? There are dozens of ways that something can be wrong.

**Comment by MarcoEpsilon** [comment]
Normally, in hugo 0.56, the statement output under content/posts etc xxx.md(non draft) page, but above hugo 0.56, the statement is only output "Posts"  page

**Comment by bep** [comment]
This was a breaking change at some point to get all the pages collections symmetrical. What you want is:

```
{{ $paginator := .Paginate (where .RegularPages "Type" "posts") }} 
```
