### ISSUE TITLE
Map merge crashes build when trying to replace string value with map

### ISSUE THREAD

**Issue by LandGod** [gohugoio/hugo#7899]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.76.5/extended windows/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes. 

When running the command `hugo server` on my computer, the build crashes when trying to perform a map merge where a value being replaced is a string and is being replaced with a map. Since nested maps are supported, and since variable types are not enforced, it seems like this behavior should definitely be allowed. After seeing this issue with my code, I distilled it down to a few test cases which you can see below, that clearly demonstrate the issue. 

```
{{/*  This works */}}
{{ $testDict :=                 (dict "someKey" "a string value" ) }}
{{ $testDict = merge $testDict  (dict "someKey" "any other string" ) }}
{{ $testDict = merge $testDict  (dict "someKey" (dict "innerKey" "innerval" ) ) }}

{{/*  This works  */}}
{{ $testDict :=                 (dict "someKey" (dict "innerKey" "innerVal") ) }}
{{ $testDict = merge $testDict  (dict "someKey" "any string" ) }}

{{/*  This Works  */}}
{{ $testDict :=                 (dict "someKey" (dict "sameInnerKey" "innerval" ) ) }}
{{ $testDict = merge $testDict  (dict "someKey" (dict "sameInnerKey" "different innerval" ) ) }}

{{/*  This Works  */}}
{{ $testDict :=                 (dict "someKey" (dict "notSameInnerKey" "innerval" ) ) }}
{{ $testDict = merge $testDict  (dict "someKey" (dict "differentInnerKey" "different innerval" ) ) }}

{{/*  This Works  */}}
{{ $testVar := "string" }}
{{ $testVar = (dict "someKey" "someVal" ) }} 

{{/*  This Crashes  */}}
{{ $testDict :=                 (dict "someKey" "a string value" ) }}
{{ $testDict = merge $testDict  (dict "someKey" (dict "innerKey" "innerval" ) ) }}
```

<details>
  <summary>I don't think it changes anything, but just in case it helps, here is the code that I originally found this bug with for some additional context:</summary>

  ```
  {{ if $currentBundledProduct }}
    {{/* There is no variant select for bundled items, so default to variant 0 if product has multiple */}}
    {{ if not $currentBundledProduct.variant }}
      {{ $currentBundledProduct = merge $currentBundledProduct (dict "variant" (index $currentProduct.variants 0).id ) }}
      {{ if (eq $currentBundledProduct.subscription "seeVariants") }}
        {{ $currentBundledProduct = merge $currentBundledProduct ( dict "subscription" (index $currentBundledProduct.variants 0).subscription )  }}
      {{ end }}
    {{ end }}
  {{ end }}
  ```
  `$currentBundledProduct` is a map. `$currentBundledProduct.variants` is a slice. If the length of 
  `$currentBundledProduct.variants` is less than 2, then `$currentBundledProduct.subscription` is a map. If the slice length is more than 1, it is instead set to the string `"seeVariants"`. `$currentBundledProduct.variants[index].subscription` is alwasy a map. 

  So here, when we encounter a case in which we want to display the product with no option for the user to pick from different variants, then we just want to replace `"seeVariants"` with the map from `variants[0].subscription`. This substitution triggers a crash.
</details>

**Comment by moorereason** [comment]
Two things:

- The first example does _not_ work for me.  Can you confirm?
- What do you mean by "crash?"  For me the build fails with `error calling merge: reflect: Key of non-map type string`.  "Crash" to me means a panic with a stack trace.

**Comment by moorereason** [comment]
Nevermind.  I see a stack trace after writing a Go test.

**Comment by LandGod** [comment]
> Two things:
> 
> * The first example does _not_ work for me.  Can you confirm?
> * What do you mean by "crash?"  For me the build fails with `error calling merge: reflect: Key of non-map type string`.  "Crash" to me means a panic with a stack trace.

Yes, apologies for the poor terminology. I am getting the same error you mention there and it is causing the build to fail. That's what I meant by "crash". 

Thank you.
