### ISSUE TITLE
Add a command line flag for the 'data' directory like --themeDir

### ISSUE THREAD

**Issue by plasmobit** [gohugoio/hugo#7902]
Hello,
I miss a flag for the hugo.exe to configure the data directory (similar to -l, -c and --themeDir).

The related use case is to generate static HTML documents (reports) on the fly by calling hugo.exe with different data-set locations. The data-input dir and the output dir shall vary in this use case for each generation.

Thanks for the great work!

// Used hugo version: "Hugo Static Site Generator v0.76.5-60F0725B windows/amd64 BuildDate: 2020-10-14T15:16:53Z"

**Comment by bep** [comment]
I would say that we're not adding more "dirs flags". There is already too many ways to configure this. Note that you can set these config settings as environment variables, e.g. `HUGO_DATADIR=foo hugo`.
