### ISSUE TITLE
Is it possible to support asciidoctor-kroki?

### ISSUE THREAD

**Issue by edl7878** [gohugoio/hugo#7911]
As documentation Some Asciidoctor parameters can be customized in Hugo  mentioned:

extensions:
Possible extensions are asciidoctor-html5s, asciidoctor-bibtex, asciidoctor-diagram, asciidoctor-interdoc-reftext, asciidoctor-katex, asciidoctor-latex, asciidoctor-mathematical, asciidoctor-question, asciidoctor-rouge.

when try to set extensions = ["asciidoctor-html5s", "asciidoctor-kroki"], error occurred:
ERROR 2020/10/30 21:23:55 Unsupported asciidoctor extension was passed in. Extension `asciidoctor-kroki` ignored.

Is it possible to support asciidoctor-kroki?

**Comment by edl7878** [comment]
A PR has been made to satisfy this feature request:

https://github.com/gohugoio/hugo/pull/7919

**Comment by onedrawingperday** [comment]
Isn't this issue  fixed by https://github.com/gohugoio/hugo/commit/01dd7c16af6204d18d530f9d3018689215482170 that allows for arbitrary Asciidoc extension via path validation?
