### ISSUE TITLE
Humanize add spaces between hastags letters

### ISSUE THREAD

**Issue by PrimozGodec** [gohugoio/hugo#7912]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.77.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

I use `humanize` function to make my title uppercase (since title function does not work for my language where only the first letter of the title is uppercase). When text which I am humanizing contains a hashtag and is uppercase, Hugo splits letters after hashtag sign with spaces. Example:
```
{{humanize "this is a #TITLE"}} → "This is a # t i t l e"
```  
I know that humanize is used for changing URLs to human-readable text but even in cases of URLs, I do not know why it should be useful. I think it is a bug.

The bonus would be to add an another `titleCaseStyle` where the only first letter of the text is upper case, this will support title styles for other languages which have the only first letter of the title upper.

**Comment by xoxys** [comment]
It's not only hashtags, every full uppercase word is getting separated by spaces:

```
{{ "this is a TEST" | humanize }} -> "This is a t e s t "
```

**Comment by susiwen8** [comment]
I think this is a upstream issue, [markbates/inflect](https://github.com/markbates/inflect) cause this issue.
