### ISSUE TITLE
Content mounted via modules does not have a "GitInfo"

### ISSUE THREAD

**Issue by SirUli** [gohugoio/hugo#7922]
### What version of Hugo are you using (`hugo version`)?

0.77.0

### Does this issue reproduce with the latest release?
It is the latest release

### Description
When i mount another repository into the content folder as a module, i do not get content for the "GitInfo" variable - means i do not see the hash or AuthorName or AuthorDate. Is there any way to get these?

Thanks in advance!

Best Regards, Uli

**Comment by bep** [comment]
This is a know issue, there is an open issue about this somewhere.

**Comment by SirUli** [comment]
Meh - i didn't search with "GitInfo" - now i found it: https://github.com/gohugoio/hugo/issues/5533

Sorry for that - closing!
