### ISSUE TITLE
Domain & IP conflict

### ISSUE THREAD

**Issue by DenizParlak** [gohugoio/hugo#7925]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.78.0-FD62817B linux/amd64 BuildDate: 2020-11-03T13:16:39Z
</pre>

### Does this issue reproduce with the latest release?
Yes

Hi,

Currently I'm using VPS (CentOS) and try to serving the web site with:

hugo server -b http://domain_name/ --bind 0.0.0.0 -p 80

and my baseUrl is same like 'http://domain_name/', then if I visit IP address instead of domain name:

<img width="1371" alt="Screen Shot 2020-11-03 at 23 22 31" src="https://user-images.githubusercontent.com/11199794/98032050-d96b1500-1e2c-11eb-8ceb-dacd2980a783.png">

~~and I can't access through domain name, it still showing hosting provider's page. If I set IP address on command, site working well with IP address but same result for domain name, seems like a htaccess issue. What am I missing?~~

edit: Please ignore second question, first one (screenshot) still on going even I visit domain name & ip address as well.

**Comment by moorereason** [comment]
Sorry you're having trouble, but please use the [Hugo forums](https://discourse.gohugo.io/) for general support questions.  Github issues are strictly for bug reports and enhancement requests.  Thanks
