### ISSUE TITLE
Not able to open PDF after publish

### ISSUE THREAD

**Issue by add0212** [gohugoio/hugo#7927]
I have added few PDF file using static folder
{{%attachments title="Sprint Notes" pattern=".*(pdf)"/%}}
after publishing my site, I'm not able to open these PDF files. It should open files at "(https)://sitename/notes/sprint-notes/file1.pdf"

While it tries to open it at "(https)://notes/sprint-notes/file1.pdf"

please ignore () before and after https

**Comment by davidsneighbour** [comment]
Please find out, where the attachment shortcode comes from (probably the theme author) and post that one. Or even better, open a topic at discourse.gohugo.io. This is not a bug in Hugo.

**Comment by jorgisimo90** [comment]
Are u serious?
