### ISSUE TITLE
watcher does not detect changes made by another pod

### ISSUE THREAD

**Issue by shaozi** [gohugoio/hugo#7930]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.78.0-FD62817B linux/amd64 BuildDate: 2020-11-03T13:16:39Z
</pre>

### Does this issue reproduce with the latest release?

Yes

Did not see this issue with v 0.73.0. Upgrade to 0.76.5 and saw this issue, also verified 0.78.0 has it too.

### Description

** Edit: found it cannot detect changes caused by another pod modifying the content **

I have a kubernetes pod that runs `hugo -w` and watching content folder:
```sh
/documents $ hugo -w
Start building sites …

                   | EN
-------------------+------
  Pages            | 404
  Paginator pages  |   0
  Non-page files   |  31
  Static files     |   0
  Processed images |   0
  Aliases          |   0
  Sitemaps         |   1
  Cleaned          |   0

Watching for changes in /documents/{archetypes,content,layouts}
Press Ctrl+C to stop
Watching for config changes in /documents/config.yaml
```

`/documents` is an nfs share on k8s node and is mapped into the pod with a persistent volume.
 
~~When I change the file in content folder, hugo does not rebuild. If I modify the config.yaml, it rebuilds.~~

When change content from the same container, it works fine. However, if I change content from another pod, which share the same disk through the same persistent volume, it does not detect the change.

**Comment by moorereason** [comment]
We use [fsnotify](https://github.com/fsnotify/fsnotify) for file watching capabilities.  From their README:

> **Why don't notifications work with NFS filesystems or filesystem in userspace (FUSE)?**
>
> fsnotify requires support from underlying OS to work. The current NFS protocol does not provide network level support for file notifications.
