### ISSUE TITLE
unexpected behaviour when adding paragraphs to a list in markdown

### ISSUE THREAD

**Issue by leanderlaugs** [gohugoio/hugo#7940]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version v0.77.0/extended linux/arm64
</pre>

### Does this issue reproduce with the latest release?
0.77.0/ext is the newest available for my system. Using an Android phone as only computer prevented me from doing a build to a more recent ext.version.

---

When making a list in markdown the generated html is a very clear and simple structure. However when a paragraph is added to one of the list items:
```
* List
* List

    Paragraph

* List
```
then all the other list items are then treated as paragraphs as well. So instead of:
```
<ul>
<li>List
<li>List
<p>Paragraph</p>
<li>List
</ul>
```
It now becomes:
```
<ul>
<li><p>List</p>
<li><p>List</p>
<p>Paragraph</p>
<li><p>List</p>
</ul>
```
The paragraph tags are only added to the list items on the same level.

**Comment by pamubay** [comment]
Hugo is using Goldmark, and [Goldmark](https://github.com/yuin/goldmark) is based on Commonmark Spec.

I tried on commonmark online test, and it's produces same output as Hugo (Goldmark).

[commonmark test](https://spec.commonmark.org/dingus/?text=*%20List%0A*%20List%0A%0A%20%20%20%20Paragraph%0A%0A*%20List)

**Comment by leanderlaugs** [comment]
So we can say this is outside of Hugo's responsibility? It's easy to style around it, so that's not the worry.

**Comment by jmooring** [comment]
Yes, this is outside of Hugo's responsibility. Hugo is doing exactly what it should be doing, according to the CommonMark specification. See <https://spec.commonmark.org/0.29/#lists>.

> A list is loose if any of its constituent list items are separated by blank lines, or if any of its constituent list items directly contain two block-level elements with a blank line between them. Otherwise a list is tight. (The difference in HTML output is that paragraphs in a loose list are wrapped in `<p>` tags, while paragraphs in a tight list are not.)

Please close this issue.

**Comment by leanderlaugs** [comment]
Issue closed as it appears to be by design.
