### ISSUE TITLE
Allow importing page resources in js.Build

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7944]
With the latest addition in Hugo 0.78 you can now import JS files etc. relatively from `assets`. You can also pass params to the JS files, e.g.

```html
{{ $js := resources.Get "js/main.js" | js.Build (dict "params" (dict "api" "https://example.org/api" ) }}
```

And then in your JS file:

```js
import * as params from '@params';
```

A natural extension to this would be to do something ala:

```html
{{ $js := resources.Get "js/main.js" | js.Build (dict "page" .) }}
```
And then in the JS file:

```js
import { hello4} from '@page/utils';
```

Where `utils.js` would be a resource inside the page bundle. There are some "cache-busting" challenges (that I'm already working on a general solution for), but I think the above would make sense...?

This will tie into code splitting, ref https://esbuild.github.io/api/#splitting

This is esp. true when importing big, common dependencies. I'm not totally sure how to solve that, it needs some thinking.

**Comment by HenrySkup** [comment]
Would this page-specific resource be built after the page? i suppose this would allow for `Scratch` to be passed along? i don't have a particular use case in mind -- perhaps something could be tallied up during page rendering and passed along?
