### ISSUE TITLE
Check dot imports vs node_modules

### ISSUE THREAD

**Issue by richtera** [gohugoio/hugo#7948]
### What version of Hugo are you using (`hugo version`)?
Hugo Static Site Generator v0.78.1/extended darwin/amd64 BuildDate: unknown

### Does this issue reproduce with the latest release?
I am compiling some js code with "js.Build"
I have a file called "util.js" which I import using `import { method } from "./util"` and then I am also import the npm module "url" from "npm install url" using `import { parse } from "url"`. Inside of the url module there is also an import from "./util" and it's getting resolved to my util.js module and causing crashes. This seems to indicated it's resolving modules by names and not resolved paths.

**Comment by richtera** [comment]
The code works if I rename my local file "utilities", so I think that seems to validate the name import.

**Comment by bep** [comment]
OK, it looks like it's some odd going on with the `.` imports that needs a fix. Thanks for the report.
