### ISSUE TITLE
Custom variables support for menu items

### ISSUE THREAD

**Issue by Chrede88** [gohugoio/hugo#7951]
I would like to see support added for custom variables in menu items. The current supported variables are quite limited and makes it hard to give theme users more customization options.

Adding custom variables could be placed under `params`, which is consistent with standard Hugo.

```
[menu]

[[menu.item]]
    identifier = "id"
    name = "name"
    url  = "home/"
    weight = 1
    pre = "<p>pre html</p>"
    post = "<p>post html</p>"

    [menu.item.params]
         customVar = "custom"
```

I can see that others also previously have raised this: #5953

**Comment by bep** [comment]
I agree.
