### ISSUE TITLE
image.Fill return zero byte image when image is smaller than the dimensions given

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7955]
Not sure what happens, but in my case I had an image that was about 650x550 and applied this:

```
$img.Fill "600x600"
```

**Comment by jmooring** [comment]
This only happens when the anchor is "Smart", set either implicitly (default) or explicitly.

The other nine anchor values produce the expected results.

**Comment by jmooring** [comment]
Starting with a 650x550 image...

Fill Size|Result
:--|:--
600x600|FAIL
600x550|FAIL
600x510|FAIL
600x509|FAIL
600x508|FAIL
600x507|PASS

650:600 as 550:x --> solve for x --> 507.69...

So, if the aspect ratio is the same or narrower than the original, no problems.

Also, running the [smartcrop cli](https://github.com/muesli/smartcrop#simple-cli-application) produces the expected results without error. For example:

```bash
smartcrop -input puppy.jpg -output puppy-modified.jpg -width 600 -height 600
```

**Comment by bep** [comment]
I have a failing test for this in #8651 -- if I switch out our custom resizer with Smartcrop's default, it passes, but that is not an option (as that would add yet another big image library, and I remember I spent some time to avoid that in the first place). On surface, our resizer should behave the same. Hmm...

**Comment by bep** [comment]
OK, there seems to be a rounding difference in the 2 resizing libraries.

650x550 => downsized with 472x0:

1. 472x399 (us)
2. 472x400 (smartcrop)

400 seems to be rounded up from `399,384615384615385`.

Forcing it to be 400 makes the test pass, but this looks like a upstream bug.

**Comment by EmpireJones** [comment]
I believe I'm still seeing this in 0.84.1.

For each image, I have a loop, generating multiple sizes, at multiple quality levels, to target an ideal number of pixels per byte.

When I resize with Resize or Fill, and smart crop is enabled (default), various images have zero content length.

When I switch to a Center anchor, all images seem to be generated.

hugo v0.84.1-4BD65E22+extended linux/amd64 BuildDate=2021-06-24T11:44:23Z VendorInfo=gohugoio

**Comment by bep** [comment]
Please don't comment on closed issues. If this is still an issue, create a new issue.
