### ISSUE TITLE
Trim all whitespace in elements written to hugo_stats.json

### ISSUE THREAD

**Issue by yaaax** [gohugoio/hugo#7958]
### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
Hugo Static Site Generator v0.78.2/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

---

I have a markdown content file with a form element declared on several lines :
```
<form
  action="[URL]"
  method="POST"
>
```

I run `hugo server -e production`

**EXPECTED**: a "form" tag is added in `hugo_stats.json` tags list
**ACTUAL**: a "form\n" tag is added in `hugo_stats.json` tags list

Note: The issue does not happen if the form is declared in one line :
```
<form action="[URL]" method="POST">
```

**Comment by udaya2899** [comment]
I'm looking to contribute to Hugo. This will be my first issue in a big project. Let me know if this is simple enough for me to make as a PR. Also, please guide me with more context if any

**Comment by bep** [comment]
>Edit2: Would using json.Compact

I don't know what that does, but I was thinking more inline of doing `strings.TrimSpae` on all the Classes, IDs etc. in 

https://github.com/gohugoio/hugo/blob/master/publisher/htmlElementsCollector.go#L233

**Comment by yaaax** [comment]
My skills in Go language are pretty poor at the moment, I let you fix that one 😅
Happy to see the fix for a bit of learning.

_My 2 cents : trimming the spaces while parsing HTML elements, as suggested by @bep, is probably more efficient than calling a function like `json.Compact` after building an entire json._

**Comment by udaya2899** [comment]
@bep 

https://github.com/gohugoio/hugo/blob/master/publisher/htmlElementsCollector.go#L234 has the `strings.TrimSpace` already.  Am I missing something then?
