### ISSUE TITLE
Hugo server does not apply changes made to resources included via resources.Get in shortcodes

### ISSUE THREAD

**Issue by mfg92** [gohugoio/hugo#7960]
I have a shortcode that uses `resources.Get` to load a CSS file to incude it. I use that shortcode in a markdown page.
When I start hugo server (`./hugo.exe server -D  --disableFastRender --gc --bind 0.0.0.0`) the shortcode works as expected and all is styled correctly. 

Now to the problem: When I change the mentioned CSS file, hugo server detects the change and reloades the browser tab. But the style change is not there.
If, for instance, I change the color of something in the CSS file, the color is not changed after the reload. But if I stop hugo server and start it again, the color changes.

### Example shortcode to demonstrate the problem:
_project_root/layouts/shortcodes/test.html_:
```html
<link rel="stylesheet" href="{{ (resources.Get "test.css").RelPermalink }}" media="screen">

<hr>
```

_project_root/assets/test.css_:
```css
hr {
    width: 100%;
    color: #F00;
}
```

some markdown file:
```md
...
{{< test >}}
...
```

I'm using Hugo version 0.78.2 on Windows 10.

Here you can find the real life shortcode project: https://github.com/mfg92/hugo-shortcode-gallery/blob/865699e9f33637655a701fb811bc20225befce7c/layouts/shortcodes/gallery.html#L71

**Comment by bep** [comment]
Yea -- I have a working branch that reworks these things. It should not not bre too long.

**Comment by Cereal2nd** [comment]
Any updates on this? this is still the case in hugo 0.81 ...
