### ISSUE TITLE
There might be something not checked in

### ISSUE THREAD

**Issue by richtera** [gohugoio/hugo#7972]
Trying to use master

Getting this when executing "go install"

```
go: finding module for package github.com/gohugoio/hugo/watcher
commands/hugo.go:57:2: no matching versions for query "latest"
```

**Comment by ardnew** [comment]
I just encountered the same issue and discovered `watcher` is indeed missing from branch `master`. The docs do not mention it, but you'll want to change to another branch which does have it included:

```
git checkout stable
go install
```
