### ISSUE TITLE
safeJS improperly escaping < character when applied to partials

### ISSUE THREAD

**Issue by jeremielp** [gohugoio/hugo#8001]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.75.0-FEF924BA windows/amd64 BuildDate: 2020-09-14T09:19:16Z
</pre>

### Does this issue reproduce with the latest release?
Not tested

### Bug Report

Despite using `safeJS` attribute, the character `<` is replaced by `&lt;` when the JS code is inserted from a partial, while not affected when the string is directly passed in the markup. I tried to change the extension (no impact) and add safeHTML (makes things worse).

The character `>` is fine in all cases.

See tests definition and compiled results below:

**baseof.html**
```
1
<script>{{ "var i = 10; if (i > 8 || i < 4) { console.log('a', (32 >> 1) + (8 << 2)); }" | safeJS }}</script>
2
<script>{{ partial "safejs.html" . | safeJS }}</script>
3
<script>{{ partial "safejs.js" . | safeJS }}</script>
4
<script>{{ partial "safejs.html" . | safeJS | safeHTML }}</script>
5
<script>{{ partial "safejs.js" . | safeJS | safeHTML }}</script>
```

**partial.html** / **partial.js** (same content - just wanted to test if extension had an impact)
```
var i = 10; if (i > 8 || i < 4) { console.log('a', (32 >> 1) + (8 << 2)); }
```

**Compiled html file**
```
1
<script>var i = 10; if (i > 8 || i < 4) { console.log('a', (32 >> 1) + (8 << 2)); }</script>
2
<script>var i = 10; if (i > 8 || i &lt; 4) { console.log('a', (32 >> 1) + (8 &lt;&lt; 2)); }</script>
3
<script>var i = 10; if (i > 8 || i &lt; 4) { console.log('a', (32 >> 1) + (8 &lt;&lt; 2)); }</script>
4
<script>"var i = 10; if (i \u003e 8 || i \u0026lt; 4) { console.log('a', (32\u003e\u003e 1) + (8 \u0026lt;\u0026lt; 2)); }"</script>
5
<script>"var i = 10; if (i \u003e 8 || i \u0026lt; 4) { console.log('a', (32 \u003e\u003e 1) + (8 \u0026lt;\u0026lt; 2)); }"</script>
```

**Comment by moorereason** [comment]
It's odd that only the `<` is encoded by the Go `html/template` engine.  However, the solution to your problem is to setup a custom output format for javascript files that uses the Go `text/template` engine.   Use something like this and the 3rd example should work:

```toml
[outputFormats]
  [outputFormats.JS]
  mediaType = "application/javascript"
  isPlainText = true
```

Maybe this should be baked into the defaults in Hugo [like many other formats](https://gohugo.io/templates/output-formats#output-format-definitions).  @bep, what do you think?

**Comment by jeremielp** [comment]
@moorereason, I can confirm that your solution works. Thanks!

```
3
<script>var i = 10; if (i > 8 || i < 4) { console.log('a', (32 >> 1) + (8 << 2)); }</script>
```
