### ISSUE TITLE
Add command line option to stop build on duplicate paths 

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#8005]
One can `hugo --path-warnings` to print warnings on duplicate target paths. I'd like to stop the build (error instead of warning) when this happens. Something like `hugo --path-errors` ...

Yes, I can grep the output, but it would be easier if it were built-in.

Please close this issue if it has no chance of happening.

**Comment by bep** [comment]
I understand the use case, but it would be good if we could somehow keep the number of flags down:

```
--i18n-warnings
--path-warnings
```

As as a side note, we should get these in line with the rest and use `camelCase`.

But both of the above would be a candidate for a boost in log level. Maybe not possible/practical to somehow combine these flags ...

Also, the above flags are meant as temporary debug tools. What you talk about is probably a config option, e.g. `pathWarningsLogLevel`.

**Comment by acanalis** [comment]
I hit a wall today with some silent duplicates, so +1. In fact, I would prefer if the default behavior of plain `hugo` command were to fail immediately. Unless there's someone out there overwriting files on purpose?

**Comment by bep** [comment]
>Unless there's someone out there overwriting files on purpose?

That will be a little bit of a lottery.

**Comment by jmooring** [comment]
Resolved with:

`hugo --printPathWarnings --panicOnWarning`
