### ISSUE TITLE
Generate footnote items without <p>

### ISSUE THREAD

**Issue by Meiryo7743** [gohugoio/hugo#8006]
### What version of Hugo are you using (`hugo version`)?

```
$ hugo version
Hugo Static Site Generator v0.75.1/extended windows/amd64 BuildDate: unknown
```

### Does this issue reproduce with the latest release?

Yes.

---

Building a website with Goldmark, I found that `<li>` in footnotes has `<p>` as its children. However, this behavior is incorrect because, accroding [the MDN Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li) and Lighthouse's audit logs, `<li>` is allowed to contain [Flow content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Flow_content) only, which does not include `<p>`.

It would better to generate footnote items with content text and HTML elements belonging to the flow content.

#### Current

```html
<section class="footnotes" role="doc-endnotes">
    <hr>
    <ol>
        <li id="fn:1" role="doc-endnote">
            <p>
                This is a footnote. <a href="#fnref:1" class="footnote-backref" role="doc-backlink">↩︎</a>
            </p>
        </li>
    </ol>
</section>
```

#### Expected output

```html
<section class="footnotes" role="doc-endnotes">
    <hr>
    <ol>
        <li id="fn:1" role="doc-endnote">
            This is a footnote. <a href="#fnref:1" class="footnote-backref" role="doc-backlink">↩︎</a>
        </li>
    </ol>
</section>
```

**Comment by pamubay** [comment]
![flow-element](https://user-images.githubusercontent.com/18132440/100711963-975dd080-33e4-11eb-957d-a0cae79f493f.jpg)

**Comment by Meiryo7743** [comment]
Oops! I have misread the documentation. In addition Lighthouse didn't log such an error ... There is nothing wrong with that.

Maybe I was a little tired. Sorry for the inconvenience.
