### ISSUE TITLE
Missing md files when buildDrafts.

### ISSUE THREAD

**Issue by jinfagang** [gohugoio/hugo#8007]
I have a md file under posts

![image](https://user-images.githubusercontent.com/21303438/100850420-be88d080-34be-11eb-88e9-6ce72ef49f53.png)

all other md can generate html and seen, except this one.

Is that my file name not properly? Why?

**Comment by jinfagang** [comment]
this is all my content:

```
---
title: 2021的FLAG试行版
date: 2020-12-02 15:41:31
category: 默认分类
draft: true
---
本文介绍 2021的FLAG试行版
<!-- more -->

# 2021的FLAG试行版
```

**Comment by jmooring** [comment]
If you ran `hugo -D` and this page wasn't generated, then perhaps the `date` value was in the future. There does not appear to be a problem with the file name. 

Also note that date values without an offset are considered UTC, so it's best to use a `date` value such as `2021-04-08T08:43:40-07:00`.

In the future please use the Hugo forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
