### ISSUE TITLE
Estimated reading time calculation

### ISSUE THREAD

**Issue by BNolet** [gohugoio/hugo#8011]
I would like to be able to modify the calculation on which the estimated reading time is based. Somewhere in the forums I saw that it may be based on 220 words per minute, but I'd like to be able to change that.

**Comment by davidsneighbour** [comment]
It's easily solvable with some template magic:

https://kodify.net/hugo/strings/reading-time-text/#solution-count-words-then-compute-reading-time

```
{{ $readTime := mul (div (countwords .Content) 220.0) 60 }}

{{ $minutes := math.Floor (div $readTime 60) }}
{{ $seconds := mod $readTime 60 }}

<p>Reading time: {{ $minutes }} {{ cond (eq $minutes 1) "minute" "minutes" }} and
    {{ $seconds }} {{ cond (eq $seconds 1) "second" "seconds" }}.</p>
```

Exchange the 220.0 with your number, maybe make it configurable in your config.

**Comment by BNolet** [comment]
I'm not asking for a workaround though, I'm asking for this to be a parameter that can be changed in the .toml file.

**Comment by davidsneighbour** [comment]
This is not a workaround. It's how reading time is calculated. It's literally a three-line solution you want to use developer and documentation writing time to implement something which is not a core feature of Hugo. There is a reason Hugo has a templating system.

**Comment by BNolet** [comment]
I'm sorry, I was under the impression that this was a feature of hugo that themes took advantage of. Is this something that was previously declined as a feature?

**Comment by CarsonSlovoka** [comment]
You can also use the ``.WordCount`` or ``.FuzzyWordCount``to helps you.

see more: [page-variables](https://gohugo.io/variables/page/#page-variables)
