### ISSUE TITLE
About unlinked resources.

### ISSUE THREAD

**Issue by TokoPolo** [gohugoio/hugo#8014]
Hugo pulls all resources in the page bundles, including those that cannot be reached via links to the deployment directory. Scoured the web and yet have not found a behavior to avoid that. The use case is independent site development by various people and adding the repositories as submodules in which case all the auxiliary resources in the repositories are pulled (but not needed by the site). If not, then this is a feature request for such a scheme to be implemented.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by TokoPolo** [comment]
Good. Now that's what I call excellent discourse. (/s if you still don't get it).
