### ISSUE TITLE
Extended release tarball

### ISSUE THREAD

**Issue by harrisondnash** [gohugoio/hugo#8016]
Where can I find the extended version of the 0.68.3 release please for MacOS? 

Alternatively, do you have any other recommendations for installing an older extended version of hugo please? 

Thank you :)

**Comment by davidsneighbour** [comment]
Did you see this when you added your bug report?

![Selection_082](https://user-images.githubusercontent.com/83281/101137100-dd16d500-3640-11eb-867a-e546d4b059e7.png)

On Github, in every project that has releases, you go to the homepage of the project (https://github.com/gohugoio/hugo) then look at the right column and see a "Releases" section. There you click the "+ number releases" link and end up on the releases page (https://github.com/gohugoio/hugo/releases). There you scroll through the releases and select the one you look for. 

0.68.3 is here: https://github.com/gohugoio/hugo/releases/tag/v0.68.3

And the mac extended version is down below in the list.

For future support requests please use the discourse. This here is for real bugs and feature requests and you probably be overlooked. Discourse reactions are faster.

**Comment by harrisondnash** [comment]
Thank you. Will do-
