### ISSUE TITLE
TOCSS: failed to transform

### ISSUE THREAD

**Issue by harrisondnash** [gohugoio/hugo#8017]
Hello, 
I get the following error when I run 
`
hugo server
`

```
2020/12/03 19:51:32 TOCSS: failed to transform "styles/styles-dark.scss" (text/x-scss): resource "scss/styles/styles-dark.scss_f4320040a399b68ce06274b21a585702" not found in file cache
```

I've tried with the most recent extended version of hugo as well as older versions that aren't extended. 
MacOS

Any idea how to fix this? 

I've also tried:
```
 snap install hugo --channel=extended
Interacting with snapd is not yet supported on darwin.
This command has been left available for documentation purposes only.
```
Thank you for your help!

**Comment by davidsneighbour** [comment]
This too please ask in the support forum, but I guess it will solve itself with your other request in #8016

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
