### ISSUE TITLE
.Name / .Title of resized images stays the same as original image

### ISSUE THREAD

**Issue by hobiah** [gohugoio/hugo#8022]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.75.0-FEF924BA windows/amd64 BuildDate: 2020-09-14T09:19:16Z
</pre>

### Does this issue reproduce with the latest release?
Not tested on latest release

---
Here is the code in the layout:
```
{{ $img := resources.Get "1.jpg" }}
{{ $imgr := $img.Resize "100x" }}

$img.RelPermalink
> {{ $img.RelPermalink }}
$img.Permalink
> {{ $img.Permalink }}
$img.Name
> {{ $img.Name }}
$img.Title
> {{ $img.Title }}

$imgr.RelPermalink
> {{ $imgr.RelPermalink }}
$imgr.Permalink
> {{ $imgr.Permalink }}
$imgr.Name
> {{ $imgr.Name }}
$imgr.Title
> {{ $imgr.Title }}
```

Below the result.

```
$img.RelPermalink
> /1.jpg
$img.Permalink
> http://example.org/1.jpg
$img.Name
> 1.jpg
$img.Title
> 1.jpg

$imgr.RelPermalink
> /1_hu530744065350dcb9282d03f6cd251505_108311_100x0_resize_q75_box.jpg
$imgr.Permalink
> http://example.org/1_hu530744065350dcb9282d03f6cd251505_108311_100x0_resize_q75_box.jpg
$imgr.Name
> 1.jpg
$imgr.Title
> 1.jpg
```

 I was expecting `$imgr.Name` (and possibly `$imgr.Title` too) to show the following line. Instead, they still show the name of the original ressource. I can extract the name from `$imgr.RelPermalink`, but that would be better to update `$imgr.Name`
```
> 1_hu530744065350dcb9282d03f6cd251505_108311_100x0_resize_q75_box.jpg
```

**Comment by bep** [comment]
I see where you're coming from, but this is by design. The thing is, I'm not sure what you would ever want to do with ` 1_hu530744065350dcb9282d03f6cd251505_108311_100x0_resize_q75_box.jpg`; the hash etc. info is meant for the system not as a presentation.

**Comment by hobiah** [comment]
I want to read the content of the resized file to convert it to base64
