### ISSUE TITLE
CSS does not update with "hugo serve"

### ISSUE THREAD

**Issue by 89z** [gohugoio/hugo#8026]
I am using this:

~~~
Hugo Static Site Generator v0.79.0-DEV windows/amd64 BuildDate: unknown
~~~

and if I run `hugo serve`, then make a change to `static/main.css`, I get this:

~~~
Change of Static files detected, rebuilding site.
2020-12-05 10:18:00.304 -0600
Syncing main.css to C:\test\
~~~

but the file being served is still the old version. Am I doing something wrong?

**Comment by 89z** [comment]
Looks like running once with `--ignoreCache` solved the issue. `--noHTTPCache` might work too, but I cant get it to break again to test.

**Comment by kirillbobyrev** [comment]
For anyone finding this in the future: both `--ignoreCache` and `--noHTTPCache` did not work for me, I had to "Disable cache" in Chrome Developer Tools.
