### ISSUE TITLE
render-image wrapped in p-tags

### ISSUE THREAD

**Issue by gj52** [gohugoio/hugo#8027]
<pre>
$ hugo version
0.79.0
</pre>

### Does this issue reproduce with the latest release?

YES

####

I'm using render-image with html figure elements and get it wrapped with paragraphs  
`<p><figure ..   </figcation></p>`

this is not valid in HTML 5, but most browsers ignore it.

Markdown

`![](images/qrcodefeed.png "Sample QR Code")`

 HTML

```
<p>
<figure>
<img loading=lazy  src=/post/2019/05/07/qr-codes/images/qrcodefeed.png
 width=150 height=auto alt="Sample QR Code" >
<figcaption>Sample QR Code</figcaption>
</figure>
</p>

```

**Comment by davidsneighbour** [comment]
- Do you have empty lines before and after the image markdown?
- What is your markdown configuration?

Have a look if this post in the Hugo Discourse solves your support request:

https://discourse.gohugo.io/t/headings-without-ids-images-not-in-p-tags/22304

**Comment by gj52** [comment]
Yes, i have blank lines 

- removed figure from render-image / use only img
- do NOT use p-tag in render-image - replaced with span (for replacing figcaption)

makes the W3C validator happy

ended up with this
https://github.com/gj52/HugoSample/blob/master/themes/photon/layouts/_default/_markup/render-image.html

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
