### ISSUE TITLE
Empty .GitInfo object in partials

### ISSUE THREAD

**Issue by mijorus** [gohugoio/hugo#8028]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo version: 0.79
OS: Windows 10

</pre>

## Issue
The .GitInfo object is empty in partials. I have tried both with the flag `--enableGitInfo ` and  `enableGitInfo   = "true"` in config.toml.

Git is installed system wide. I get the same result when compiling on netlify's servers

**Comment by bep** [comment]
>The .GitInfo object is empty in partials.

That would depend on what you send as argument to a partial, which is up to you. I'm confident that if you pass a page with `.GitInfo`, that should also be available in the partial.

I suggest you take further questions at https://discourse.gohugo.io/
