### ISSUE TITLE
Modules: Error / warning if Go not installed

### ISSUE THREAD

**Issue by cmlnet** [gohugoio/hugo#8032]
Would it be possible that using `hugo mod init` (or / and `hugo mod get`) throws an error or warning if Go is not installed on the system?

Of course the documentation states that installing Go is an prerequisite for using the module functionality. However, I failed to understand that prerequisite and I wondered why `hugo mod init` did just nothing (no output even with the debug or verbose option; on MacOS Bigsur). A warning or error would have saved me some time searching for what I missed.

**Comment by jamesallured** [comment]
I'm just taking a look at this and I was wondering whether anybody could tell me more about this line in the documentation:

> This is not needed if you only operate on modules inside /themes or if you have vendored them via “hugo mod vendor”.

I don't think that a blanket "_if Go isn't installed, return some kind of error_" approach would work if we want to preserve this behaviour.

**Comment by cmlnet** [comment]
Maybe, a possible solution would be to display the warning only for the commands `hugo mod init` and `hugo mod get`?

If I understand the concept then these commands require Go to be installed or otherwise do just nothing.

**Comment by jmooring** [comment]
> Would it be possible that using hugo mod init (or / and hugo mod get) throws an error or warning if Go is not installed on the system?

With v0.111.3, and Go _not_ installed:

```text
hugo mod init foo
```

> Error: failed to init modules: binary with name "go" not found
