### ISSUE TITLE
Can't evaluate field Param in type create.ArchetypeFileData

### ISSUE THREAD

**Issue by bitcrazed** [gohugoio/hugo#8037]
### What version of Hugo are you using (`hugo version`)?
Hugo Static Site Generator v0.79.0-1415EFDC windows/amd64 BuildDate: 2020-11-27T09:06:43Z

### Does this issue reproduce with the latest release?
Yes

### Archetype

Filename: ./archetypes/default.md

```markdown
---
title: "{{ replace .Name "-" " " | title }}"
author: "{{ .Param "author" }}"
date: {{ .Date }}
images:
    - "/images/bcz-64.png"
draft: true
---
```

### Invocation
```cmd
hugo new posts/wibble.md
```

### Error:
```
Error: Failed to process archetype file "default.md":: execute of template failed: template: default:3:12: executing "default" at <.Param>: can't evaluate field Param in type create.ArchetypeFileData
```

Have also tried:

```markdown
author: "{{ .Param "author" }}"
```
and:
```markdown
author: "{{ .Param.author }}"
```
and many other permutations. 

Whatever I try, Hugo doesn't appear to be able to find anything called $.Param, $.Params, .Param, .Params or anything similar, and always returns the error text above (with the contents of <...> changed for each type of Param access).

**Comment by pamubay** [comment]
the content file not yet created, so it's doesnt make sense to use `.Param`.
_(yes, i know `.Param` has fallback to Site Params.)_

if you want access **Site Params** then use `.Site.Params.author`

**Comment by bep** [comment]
Maybe we should make this more explicit in the documentation, but the object you get in create __is not a Page__.

**Comment by bitcrazed** [comment]
Thanks for the info.

I've changed my archetype's `author` field to:

```md
author: "{{ .Site.Params.author }}"
```

and declared the following in my `config.toml`:

```toml
[Params]
author = "Rich Turner"
```

Hugo now correctly emits the expected front-matter in my blog posts:

```md
---
title: "Welcome"
author: "Rich Turner"
date: 2020-12-14T14:54:34-08:00
draft: true
---

!<--more-->

```
