### ISSUE TITLE
Add support for Microsoft Clarity analytics

### ISSUE THREAD

**Issue by matsbror** [gohugoio/hugo#8039]
Hugo has built in support for Google Analytics. Microsoft Clarity is another free analytics option and Wowchemy has built support for it and could just as well be built into Hugo.

If you agree, I could do it and submit a pull request.

**Comment by techmagus** [comment]
If this will be added as a built-in, don't forget to add a filter to not load the script when viewing in localhost. My Clarity ended up tracking localhost:1313 too.

Based on what's in the Disqus shortcode, I added this bit:
```
if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
return;
}
```

So it's now: (currently hardcoded in my ```head.md``` file.
```
<script>
(function(c,l,a,r,i,t,y) {
	if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
		return;
	}
	c[a]=c[a]||function() { (c[a].q=c[a].q||[]).push(arguments) };
	t=l.createElement(r);
	t.async=1;
	t.src="https://www.clarity.ms/tag/"+i+"?ref=bwt";
	y=l.getElementsByTagName(r)[0];
	y.parentNode.insertBefore(t,y);
})
(window, document, "clarity", "script", "CLARITY_ID_HERE");
</script>
```
