### ISSUE TITLE
.Resources.ByType "video" return empty result

### ISSUE THREAD

**Issue by wangchucheng** [gohugoio/hugo#8052]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.78.2
</pre>

### Does this issue reproduce with the latest release?

Yes

### Description

I want to access video files by `.Resources.ByType "video"`, but the result is empty. I also look at [mediaType.go](https://github.com/gohugoio/hugo/blob/master/media/mediaType.go#L125), which shows that `.mp4` and `.webm` is supported.

After more tests, I found that video can be accessed by using its suffix. For example, I can access `1.mp4` by `.Resources.ByType "mp4"`, and access `1.webm` by `.Resources.ByType "webm"`. But none of these can be accessed by `.Resources.ByType "video"`.

But for images, I can use `.Resources.ByType "image"` to access it instead of `.Resources.ByType "png"`, which is totally contradictory to videos.

I was suggested to open an issue for this in hugo community.

See also https://discourse.gohugo.io/t/resources-bytype-video-return-empty/29975

**Comment by onedrawingperday** [comment]
This is a request for a new method i.e. `.Resources.ByType "video"`

**Comment by wangchucheng** [comment]
> This is a request for a new method i.e. `.Resources.ByType "video"`

Thanks for your supplement, I thought it was a bug before😝

**Comment by cmahnke** [comment]
See also #7671.
This would also be a great opportunity to provide a `video` shortcode, similar to `figure` to make video content a first-class citizen in the Hugo ecosystem, without relying on external services like Youtube and Vimeo.

This would also make a nice Christmas present ;)

**Comment by martignoni** [comment]
@cmahnke Meanwhile, you can use this: https://github.com/martignoni/hugo-video. Not so nice Christmas present, but still :-)

**Comment by bep** [comment]
There is a special case in there for images ... not sure why I put that in there, I must have thought about the generic application/text types not being very useful. But the documentation is clear, so we need to fix this.

**Comment by wangchucheng** [comment]
> There is a special case in there for images ... not sure why I put that in there, I must have thought about the generic application/text types not being very useful. But the documentation is clear, so we need to fix this.

Thanks for the incoming fix! And another strange bug (I think) is videos can be accessed by methods like `.Resources.ByType "webm"`, but they will not be included in production files (`public` folder). So the link will renturn a 404 error.

**Comment by bep** [comment]
> videos can be accessed by methods like .Resources.ByType "webm", but they will not be included in production files (public folder). So the link will renturn a 404 error.

The above is certainly not related to this particular issue.
