### ISSUE TITLE
Header elements in html shortcode file should be parsed and pulled into TableOfContents

### ISSUE THREAD

**Issue by bgdeutsch** [gohugoio/hugo#8055]
It would be a great enhancement to have `h2` or `h3` HTML elements parsed from a shortcode file and pulled into `.TableOfContents`. 

Currently headers (`h2` or `h3`) in a markdown file are rendered in the `TableOfContents` and it works great: 

`mymarkdown.md`: `## Overview`

While header elements (`h2` or `h3`) in a shortcode file are not rendered in the `TableOfContents`:

`myshortcode.html`: `<h2>Overview</h2>`

**Comment by XhmikosR** [comment]
While I see the value of this, I think it will be a quite breaking behavior. Not sure how this can be made smooth. Maybe by introducing a config option?

**Comment by bep** [comment]
Header elements from shortcodes are pulled into .TableOfContents if

* the shortcode produces markdown headers
* the shortcode is included with the `{{%` delimiter.
