### ISSUE TITLE
 Add images.Overlay filter

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#8057]
A while back I opened [this topic](https://discourse.gohugo.io/t/feature-request-option-for-adding-whitespace-around-an-image/24788) in the forum.

This is a missing feature that causes me grief again and again.
So I decided to post in the GitHub issues tracker hoping that perhaps someone someday might look into it.

Use case: Square product thumbnails need to be generated from portrait product photos.

Current situation: If one uses for example `{{- $thumb := ($original.Resize "1080x1080").RelPermalink }}` they will end up with a distorted image since `.Resize` does exactly as told without any concept of respecting the aspect ratio. Similarly if one were to use `{{- $thumb := ($original.Fit "1080x1080").RelPermalink }}` they would end up with an image that respects the original aspect ratio but is not square.

~~I have sort of forgotten~~ As far as I can tell the library that Hugo uses for image processing is https://github.com/disintegration/imaging/  if you think that this issue does not belong here, let me know and I will open an issue upstream.

**Comment by bep** [comment]
>{{- $thumb := ($original.Fit "1080x1080").RelPermalink }} they would end up with an image that respects the original aspect ratio but is not square.

What about `.Fill`?

**Comment by onedrawingperday** [comment]
> What about `.Fill`?

Unfortunately it crops the image with Smartcrop.

I will post all of the things I've tried for your reference:

1. `{{- $thumb := ($original.Fill "1080x1080").RelPermalink }}`
![1500_hu77205ecf3c461ac981b377ddc9927806_227804_1080x1080_fill_q75_box_smart1](https://user-images.githubusercontent.com/7918298/102326839-95bc0d00-3f8d-11eb-9df9-ec26cdb9aad7.jpg)

2. `{{- $thumb := ($original.Resize "1080x1080").RelPermalink }}`
![1500_hu77205ecf3c461ac981b377ddc9927806_227804_1080x1080_resize_q75_box](https://user-images.githubusercontent.com/7918298/102327186-082ced00-3f8e-11eb-922c-0429831d00f2.jpg)


3.  `{{- $thumb := ($original.Fit "1080x1080").RelPermalink }}`
![1500_hu77205ecf3c461ac981b377ddc9927806_227804_1080x1080_fit_q75_box](https://user-images.githubusercontent.com/7918298/102327095-e5023d80-3f8d-11eb-877a-baec27195ab8.jpg)

**Comment by bep** [comment]
>Unfortunately it crops the image with Smartcrop.

Sure, but that is an option -- you can put the anchor for the crop wherever you want.

**Comment by onedrawingperday** [comment]
># Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight

I am afraid that I do not follow. 

If I do:

`{{- $thumb := ($original.Fill "1080x1080 center").RelPermalink }}` I end up with:
![1500_hu77205ecf3c461ac981b377ddc9927806_227804_1080x1080_fill_q75_box_center](https://user-images.githubusercontent.com/7918298/102327857-fef05000-3f8e-11eb-9125-3ef029e88225.jpg)

`{{- $thumb := ($original.Fill "1080x1080 top").RelPermalink }}` I end up with:

![1500_hu77205ecf3c461ac981b377ddc9927806_227804_1080x1080_fill_q75_box_smart1](https://user-images.githubusercontent.com/7918298/102327982-26dfb380-3f8f-11eb-990d-3ff268be3080.jpg)

And so on for the other anchors.

My desired output would be:

![square](https://user-images.githubusercontent.com/7918298/102328045-39f28380-3f8f-11eb-9018-b73fe20d74db.jpg)

As far as I can tell there is no way to add whitespace on the left and on the right of the original image.

**Comment by bep** [comment]
OK, I understand. I thought your main point was to get it ... square.

If you don't want to crop it, why use Fit and make it square in CSS (e.g. center it in a square div)?

**Comment by onedrawingperday** [comment]
I am trying to generate a CSV Output Format with Hugo, so that it can be used by Facebook/Instagram to auto-update a product catalog.

The square format profuct photo is a requirement. 

Oh well never mind... 🙄

I’ll just carry on running imageMagick to add the whitespace after generating a thumb with Hugo’s  `.Fit` method  -even though it turned out being a nightmare to maintain-.

**Comment by bep** [comment]
Thinking about this, I think this fits better in the `.Overlay` method we discussed earlier. That has several use cases. of course (one being adding text to images?), but I imagine you could do something ala:

```
{{ $img := $someImage | $whiteSquare.Overlay }}
```

I'm not totally sure I got the order of the arguments right in the above, but the concept should be clear?


It was discussed here https://github.com/gohugoio/hugo/issues/4595

**Comment by bep** [comment]
I will add a PR with a new Overlay filter function that you can test out later today... I think it will work great and have lots of other use cases.

**Comment by onedrawingperday** [comment]
As I understand it the `.Overlay` method in the Disintegration [Doc](https://gowalker.org/github.com/disintegration/imaging#Overlay) and the related `OverlayCenter` a used can define a background image in the desired dimensions and use another image to overlay it on top.

For example in my use case something like:

```
{{/* whiteSquare.jpg is a white background 1080x1080px fetched as a .Resource */}}
{{ $whiteSquare := resources.Get "/whiteSquare.jpg" }}
{{- $thumb := ($original.Fit "1080x1080").RelPermalink | $whiteSquare.Overlay }}
```

Would do the job nicely.

Looking forward to your Pull Request. I will test it as soon as possible.
