### ISSUE TITLE
images.Overlay: Add a way to control the generated filename

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#8066]
Following 3ba147e

With
```
{{ $logo := resources.Get "/logo.png"  }}
{{ img := resources.Get "/product.jpg" }}
{{ $overlay := $img.Filter (images.Overlay $logo 50 50 )}}
```
The generated file will inherit its filename from the `$img` file along with the file hash.
e.g.
`product-hu1233ec6ce0adea4b2e640fdffe0d5b13_34826_filter_3369228290977307821.jpg`

But in the reverse scenario, when a product image is overlaid on top of a white square the filename is inherited from the white square file.

```
{{ $whiteSquare := resources.Get "/whiteSquare.jpg"  }}
{{ img := resources.Get "/product.jpg" }}
{{ $thumb = ($whiteSquare.Filter (images.Overlay $img $width $height)).RelPermalink }}
```
The generated filename is:
`whiteSquare-hu1233ec6ce0adea4b2e640fdffe0d5b13_34826_filter_3369228290977307821.jpg`

This seems kind of like a hard problem. 

Is it possible to add a flag or switch to control the generated filename?
Or if that is not possible how can one replace the filename so that it is the desired one?

In any case everything else works fine.
This is great and thanks a lot.

**Comment by bep** [comment]
This has been discussed before -- the current workaround is to use `resources.Concat` (I have not tested that on images, but I assume it will work)...

I think the other issues suggests a new ´resources.Rename` function. Anyhow, I'm not prepared to add this to every function of this sort.

**Comment by onedrawingperday** [comment]
Thanks a million!

For reference, it is possible to output the desired filename in the reverse scenario with:
```
{{ $thumb = ((slice $whiteSquare | resources.Concat $thumb).Filter (images.Overlay $thumb $width $height)).RelPermalink }}
```

I'm closing this issue.

Also everything works fine with `images.Overlay` as far as I tested.
