### ISSUE TITLE
Add a security policy to all repositories in @gohugoio

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#8074]
See #8073 - this repo (and probably the others too) have no security policy set up. It's as easy as adding a `SECURITY.md` to the repo-root. I propose to do that in all gohugo repositories. A sample I always use quick and dirty on my own repos: https://github.com/dnb-hugo/garuda/blob/main/SECURITY.md

Afraid of spam? Use a private mailing list or the public email address that Github provides and can be changed if too much spam arrives (see https://github.com/settings/emails)

**Comment by bep** [comment]
PR welcome. Use my email; gmail handles spam beautifully.
