### ISSUE TITLE
Putting two ordered lists next to each other causes them to merge into one big list with paragraphs

### ISSUE THREAD

**Issue by trwnh** [gohugoio/hugo#8076]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.79.0/extended linux/amd64 BuildDate: unknown
</pre>

### Steps to reproduce

Put two ordered lists next to each other, like so:

```
1. First item
1. Second item
1. Third item
1. Fourth item

1. First item
1. Second item
1. Third item
1. Fourth item
```

### Expected behavior

Two ordered lists are rendered, like so:

```
<ol>
<li>First item</li>
<li>Second item</li>
<li>Third item</li>
<li>Fourth item</li>
</ol>
<ol>
<li>First item</li>
<li>Second item</li>
<li>Third item</li>
<li>Fourth item</li>
</ol>
```

### Actual behavior

One large extended ordered list is rendered, with paragraphs inside each list item.

```
<ol>
<li><p>First item</p></li>
<li><p>Second item</p></li>
<li><p>Third item</p></li>
<li><p>Fourth item</p></li>
<li><p>First item</p></li>
<li><p>Second item</p></li>
<li><p>Third item</p></li>
<li><p>Fourth item</p></li>
</ol>
```

**Comment by moorereason** [comment]
This is working as designed.  See how the [reference implementation of CommonMark handles this scenario](https://spec.commonmark.org/dingus/?text=1.%20First%20item%0A1.%20Second%20item%0A%0A1.%20First%20item%0A1.%20Second%20item%0A).  If you want to discuss ideas for how to work around the spec, try opening a discussion on the [Hugo forums](https://discourse.gohugo.io/).

**Comment by trwnh** [comment]
Well, this doesn't occur for *un*ordered lists... despite the reference implementation you linked, in fact, joining unordered lists, Hugo does not join unordered lists separated by a double line-break.

**Comment by davidsneighbour** [comment]
That seems to not be true [on that same playground](https://spec.commonmark.org/dingus/?text=1.%20First%20item%0A1.%20Second%20item%0A%0A1.%20First%20item%0A1.%20Second%20item%0A%0A*%20First%20Item%0A*%20Second%20Item%0A%0A*%20First%20Item%0A*%20Second%20Item%0A). Maybe something else is interfering.

**Comment by trwnh** [comment]
Yeah, the playground ignores double-line-breaks on both ol + ol and ul + ul. It's just that in Hugo, I've noticed double-line-breaks being ignored only on ol + ol, not on ul + ul. It seems to be due to ul having multiple ways to express lists (-, *, or +), while ol has only one way to express (d.)
