### ISSUE TITLE
Native KaTeX support

### ISSUE THREAD

**Issue by robbienohra** [gohugoio/hugo#8080]
Any reason why we can't just make _KaTeX_ a default supported template shortcode in hugo?

**Comment by iranvir** [comment]
I guess because there are various competing standards. I, for example, love using MathJAX instead.

**Comment by robbienohra** [comment]
Hm not sure if the fact that there is more than one possible implementation should be an argument to not support at least one by default hehe. For example there are alternative implementations of syntax highlighting as well like prism.js, highlight.js etc. and yet Hugo still at least provides some native support for syntax highlighting in markdown. But I get your point! 😊
