### ISSUE TITLE
Google moving way from analytics.js to gtags.js

### ISSUE THREAD

**Issue by Bas-Man** [gohugoio/hugo#8081]
Hi,

I have been getting some email from google about new analytics. Attaching an image.
It looks like the internal google Analytics code might need to be updated to support this.

<img width="555" alt="analytics-gtags" src="https://user-images.githubusercontent.com/6175103/102746497-c511b600-43a1-11eb-99c6-745053cb6c18.png">

**Comment by onedrawingperday** [comment]
Duplicate of #7954

Also related: #7893
