### ISSUE TITLE
[Security] XSS on hugo through mermaid

### ISSUE THREAD

**Issue by SakiiR** [gohugoio/hugo#8085]
Hey !

I managed to inject html/javascript content from a markdown sheet with the following payload:

```markdown
{{<mermaid align="left">}}
graph TD;
 A[test];
 click A "/test" "<img src=x onerror='alert(document.domain)'>"
{{< /mermaid >}}
```

I think this is due to an outdated version of mermaid.

**Comment by bep** [comment]
Thanks for this.

`mermaid` is not a built-in Hugo shortcode, and I don't think it's fair to assume Hugo to be responsible for how third-party libraries treat strings that gets passed to them.

You need to take this with the `mermaid` (whatever that is) project.

**Comment by SakiiR** [comment]
For some reasons, gitlab is using the same library and is not vulnerable.

On the other hand, hackmd.io is vulnerable, and uses the same library.

I don't really know in details why this triggers here, but you can get this fixed by adding the mermaid shortcode:

```html
<!-- layouts/shortcodes/mermaid.html -->
<div class="mermaid" align="[...]">
{{ .Inner | HtmlUnescape }}
</div>
```
