### ISSUE TITLE
Add deferred template blocks

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8086]
* This is in ref to #8077.
* This also related to `resources.PostProcess`

There are certain things we would want to do in Hugo but cannot because it's either 1) Very expensive (build time) to do or 2) Impossible (ref. `resources.PostProcess` and CSS purging which needs the build to complete before it can do its job).

Note that I'm not saying that would be easy to implement, I just say that it would be cool/useful.

What I'm suggesting would be a way to deffer template processing until after the build, somehow storing away the `dot` context passed to it, e.g.:

```html
Some regular template blocks:
{{ range .Pages }}{{ .Title }}{{ end }}

{{ defer (dict "page" . "someotherParam" "foo") }}
{{ range .page.BackLinks }}
{{ .Title }}
{{ end }}
{{ end }}
```

The `BackLinks` above is just an example of a thing that we cannot effectively calculate upfront.

/cc @regisphilibert and gang.

**Comment by regisphilibert** [comment]
This seems promising but to this day I fail to find any other use case than Backlinks, except maybe info about the build on the `site` level. (Build time etc...)

In any case, there should be a system for singling out methods available only inside `defer` blocks. Maybe `.Page.Defer.Backlinks`, `.Site.Defer.Build.Duration` ? 

While the word defer works great in a template context, it does not work so great as a page method, I'm just using it as an example.

**Comment by bep** [comment]
>In any case, there should be a system for singling out methods available only inside defer blocks. Maybe .Page.Defer.Backlinks, .Site.Defer.Build.Duration ?

What you propose above is a variant of `resources.PostProcess` -- which is useful, but relatively complex behind the scenes, and with some shortcomings. This is, as one example, not possible:

```
{{ $css := $css | resources.PostProcess }}
{{ $upper := $css.Title | upper }}
```

Not the greatest example. But the `defer` keyword solves the above in a much cleaner and powerful way. If we implement `defer` I will probably eventually deprecate/remove `resources.PostProcess`.

The more I think about this, the more I like it.

**Comment by regisphilibert** [comment]
I see! Then I can see more present benefits and can't wait for the future ones!

**Comment by bep** [comment]
Thinking a little about this, we cannot "invent new syntax" (because of code formatters etc.), so what I now think makes most sense is to use the `with´ keyword, e.g.:
```
{{ with defer (dict "page" . "someotherParam" "foo") }}
{{ range .page.BackLinks }}
{{ .Title }}
{{ end }}
{{ end }}
```

Where `defer` wold be a template func that just echoes what it gets -- but that happens after the build.

**Comment by swamidass** [comment]
I like this. It would be great to have.
