### ISSUE TITLE
Run go mod tidy executes in forks

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#8117]
I updated my Hugo fork and due to https://github.com/gohugoio/hugo/commit/4d2b6fc4c0e714f3f1ed345d6d75ed1662948791 an action was triggered on my fork: https://github.com/onedrawingperday/hugo/actions/runs/462827377

Is this how things are supposed to be?

**Comment by bep** [comment]
>Is this how things are supposed to be?

1) I think you need to ask GitHub about that.
2) I think we've had a similar discussion before.

**Comment by onedrawingperday** [comment]
> 2. I think we've had a similar discussion before.
We did have such a discussion in https://github.com/gohugoio/hugo/issues/7645 but it was related to Dependabot.

Things are getting messy and I don't like it one bit.
Guess I'll have to learn to live with the odd action triggers and the associated notifications.

P.S. I've no time to ask GitHub support.

**Comment by davidsneighbour** [comment]
Go to your project settings, select actions on the left and read on the right. You can enable certain actions or disable them all. Technically speaking Github started recently to not enable actions on forks... Recently, so for an old project you need to manually disable it.
