### ISSUE TITLE
Page refreshes in Browser but the content does not

### ISSUE THREAD

**Issue by chevdor** [gohugoio/hugo#8118]
## Issue

Page refreshes in Browser but the content does not.

See also #7053. I updated to the latest version but this issue remains. I am using the meghna-hugo theme and markdown files. I have another site using Asciidoc where I never had this issue. Here I am using markdown.

When I change and save a .md file under content, I see hugo rebuilding. I also see the browser refreshing. However the content is NOT updating unless I stop and restart the hugo server.

I tried running the server as `hugo server --disableFastRender --renderToDisk --noHTTPCache --ignoreCache`without any improvement on the issue.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version => Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by joelgrimberg** [comment]
+1 - same issue on my system.

**Comment by chevdor** [comment]
For what this is worth, when I modify some yml, the site **does** update properly. The issue seems to come from all the -md files.

**Comment by jmooring** [comment]
I am unable to reproduce this problem with v0.83.1, and the referenced issue (https://github.com/gohugoio/hugo/issues/7053) was closed by the OP; their site was misconfigured.

@chevdor @joelgrimberg If either of you can reproduce this issue with v0.83.1 or later, please provide a minimal reproducible example.

**Comment by chevdor** [comment]
I tested the following:
- `hugo v0.83.1+extended darwin/amd64 BuildDate=unknown`
- `hugo server -D`
- change some .md under the content folder
- I pretty much changed nothing related to content/config since the report

Results:
- hugo rebuilds
- browser refreshes
- changes show up 🎉 

So for me, this is a **PASS**.
Thanks for the ping @jmooring.

I am closing this issue, @joelgrimberg I suggest opening a new one if you still see issues.

**Comment by seandlg** [comment]
I've had a similar issue with the [Anatole](https://themes.gohugo.io/anatole/) theme.

It turns out that the problem arised with Hugo's [multilingual mode](https://gohugo.io/content-management/multilingual/). I had a dangling `menus.en.toml` file for which no further language entry existed in the respective `language.toml` file. Is this expected / intended behavior?

**Comment by jmooring** [comment]
@seandlg If you can provide a minimal reproducible example (a repository), create a new issue.

**Comment by TenSketch** [comment]
> I tested the following:
> 
> * `hugo v0.83.1+extended darwin/amd64 BuildDate=unknown`
> * `hugo server -D`
> * change some .md under the content folder
> * I pretty much changed nothing related to content/config since the report
> 
> Results:
> 
> * hugo rebuilds
> * browser refreshes
> * changes show up 🎉
> 
> So for me, this is a **PASS**.
> Thanks for the ping @jmooring.
> 
> I am closing this issue, @joelgrimberg I suggest opening a new one if you still see issues.

I'm using .86. the issue is still there. What is the solution?
Kindly elaborate.
