### ISSUE TITLE
Front Matter - Tags ending with a space are not built

### ISSUE THREAD

**Issue by jwhevans** [gohugoio/hugo#8119]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0/extended darwin/amd4 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
This bug is reproducible in v0.78 - v0.80. I have not checked previous versions.

### Description of Bug
When adding tags to the front matter of a post, if one or more tags ends with a space then CR rather than a visible character, the post is not built into the site.

e.g.

#### this front matter contains a hidden space at the end of the books tag. the post will not build
```
---
title: "Example Title"
slug: "example slug"
date: 2021-01-11T07:00:00-05:00
draft: false
publishdate: 2021-01-11T07:00:00-05:00
tags:
- books  
- economy
---
```
#### this front matter does not contain a hidden space at the end of the books tag. the post will build
```
---
title: "Example Title"
slug: "example slug"
date: 2021-01-11T07:00:00-05:00
draft: false
publishdate: 2021-01-11T07:00:00-05:00
tags:
- books
- economy
---
```
### Desired and/or expected behavior
I would expect that the system ignore any trailing whitespace when generating tags.

**Comment by krashanoff** [comment]
I would be interested in looking into this, but I can't reproduce the issue on my system using `v0.79.1` or `v0.80.0`.

```sh
$ hugo version
Hugo Static Site Generator v0.79.1-EDB9248D linux/amd64 BuildDate: 2020-12-19T15:42:17Z
```

Then, using CRLF line endings on a post:

```
---
title: "Post"
date: 2020-01-08T00:00:00-05:00
draft: true
tags:
  - tagone
  - trailingspacetag 
---
```

Browser caching disabled, the post and its tag page build as expected. Same thing happens using `Hugo Static Site Generator v0.80.0-792EF0F4 linux/amd64 BuildDate: 2020-12-31T13:37:58Z`. Is there a something that I'm missing?

**Comment by jmooring** [comment]
Unable to reproduce with v0.82.
