### ISSUE TITLE
Feature request: Template function that lists layout look up candidates

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#8127]
It can be hard to tell which layout files Hugo considers when rendering a template (see e.g. #7964). To make this easier for developers it would be nice if we could do something like:

```html
This page considered using:

<ul>
{{ range layoutCandidates }}
  <li>
    {{ if .Exists }}<strong>{{ end }}{{ .Path }}{{ if .Exists }}</strong>{{ end }} {{ if .Active }} * Used {{ end }}
  </li>
{{ end }}
</ul>
```

`.Active` is maybe less important because it will always be the first `.Path` that exists, but it might be nice.

**Comment by kontralto-rob** [comment]
I would like this feature. It would be really helpful for my toggle-able debugging view.
