### ISSUE TITLE
Using babel includes warnings in output file.

### ISSUE THREAD

**Issue by richtera** [gohugoio/hugo#8136]
It seems warning messages generated within a babel build will be captured and output into the compiled output file.

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes.

![image](https://user-images.githubusercontent.com/708186/104384084-df513680-54fe-11eb-9b6b-7cbab87026aa.png)

**Comment by bep** [comment]
You need to take this with the Babel project and tell them to write these warnings to `stderr` and not to `stdout`.

**Comment by richtera** [comment]
Ok will do. In the mean time we might need to output to a temp file instead if a stream but that makes sense then.

**Comment by richtera** [comment]
It looks like babel specifically only supports input pipes
![image](https://user-images.githubusercontent.com/708186/104458164-fe8caa00-5578-11eb-89c1-9fed71b59fb3.png)

**Comment by richtera** [comment]
FYI https://github.com/babel/babel/pull/12626
I think most of the time we will need to use --out-file though, because otherwise I don't know how to detect whether the babel config has sourcemaps turned on. We could of course always add --source-maps to override those settings, but it might be best to leave those settings inside of the babel.config.js. Does that make sense?

**Comment by richtera** [comment]
Never mind... https://github.com/babel/babel/issues/2484 sourceMaps config inside of the babel config files don't seem to work reliably. It's definitely better to add sourceMaps to the options of the babel pipeline.

**Comment by jmooring** [comment]
Fix (https://github.com/babel/babel/pull/12626) was included in babel v7.12.13 (2021-02-03).
