### ISSUE TITLE
Shipping a static binary

### ISSUE THREAD

**Issue by iranvir** [gohugoio/hugo#8140]
Hey folks!
I have been using Hugo binary by downloading directly from the GitHub releases page on my Alpine Linux environment.
Recently, I ran into this issue where the binary won't run because now it is being dynamically linked against glibc (Alpine uses musl C library). Below is the executable's description as shown in a Fedora system.

```
Fedora:/usr/bin $ file hugo
hugo: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, Go BuildID=frbd_O6hHVlWirUSCm5W/fo2bwRMlcwlc4mYOrR2L/HFV7snVjbD3RScTdvVvu/ARlCyrnP7_f5PPX88GYA, BuildID[sha1]=7a544c8081985cb962da2ba6cf5c14879bb58cd7, stripped
```

Is there a reason for this shift? I really loved being able to grab a static binary, and run it, without having to worry about the underlying Linux Distribution.

Thanks!

**Comment by moorereason** [comment]
What release file are you downloading from GH?  I just tested `hugo_0.80.0_Linux-ARM64.tar.gz`, and it's statically linked.  See the [build config here](https://github.com/gohugoio/hugo/blob/v0.80.0/goreleaser.yml#L14).

Fedora has it's own build system, so ask the Fedora package maintainers about that.  I don't think that's us.

**Comment by iranvir** [comment]
I got the binary from Hugo's GitHub release page. Below is the URL I passed into wget to download the tar. I don't use whatever Fedora ships.
`https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_extended_0.80.0_Linux-64bit.tar.gz`

**Comment by moorereason** [comment]
The extended version is not statically linked because it's linked against the libsass library.  Download the non-extended release.

If you need the sass functionality, v0.80.0 has [support for dartsass](https://github.com/gohugoio/hugo/commit/cea157402365f34a69882110a4208999728007a6), which is still in beta.  See the Hugo docs at https://gohugo.io/hugo-pipes/scss-sass/.
