### ISSUE TITLE
Hugo does not render .page TLD domain names into proper hyperlinks in HTML

### ISSUE THREAD

**Issue by cmosetick** [gohugoio/hugo#8143]
`hugo` does not render hyperlinks for `https://g.page/<some-string-here>`.  

Example that does not render into a hyperlink by hugo 0.80.0:
https://g.page/TrailsEndTaphouse

`g.page` is a newer URL shortner for Google Business seen in Google Maps occasionally now.
It is similar to the existing goo.gl shortner.

However, goo.gl hyperlinks are rendered properly into html by `hugo`.

Reference:  
https://support.google.com/business/answer/9273900

> After you verify your business, you can create a short name for your Business Profile to make it easier for customers to find you.
When you share your short name, customers can enter the name’s URL in the browser’s address bar to go directly to your Business Profile. For example, customers can search for 'g.page/[yourcustomname]' in the address bar to find your business.

### What version of Hugo are you using (`hugo version`)?

```
0.80.0
```

### Does this issue reproduce with the latest release?
Yes

```
whois g.page

Domain Name: g.page
Registry Domain ID: 2D271B90D-PAGE
Registrar WHOIS Server: whois.nic.google
Registrar URL: http://www.charlestonroadregistry.com
Updated Date: 2020-09-13T15:09:34Z
Creation Date: 2018-07-30T15:09:34Z
Registry Expiry Date: 2021-07-30T15:09:34Z
Registrar: Charleston Road Registry Billable
Registrar IANA ID: 9998
```

**Comment by moorereason** [comment]
Fixed upstream in goldmark v1.3.2.

**Comment by cmosetick** [comment]
Hi @bep @moorereason This issue has been fixed upstream and has been closed here in this tracker but I do not see a new `hugo` release that contains this fix yet.

https://github.com/gohugoio/hugo/releases

**Comment by moorereason** [comment]
Yep.  That's how things work here.  The fix will be included in the next Hugo release.
