### ISSUE TITLE
Questions about url

### ISSUE THREAD

**Issue by hantaotaohan** [gohugoio/hugo#8145]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

lasts

</pre>

### Does this issue reproduce with the latest release?

Questions about url

Vimwiki has long been used to write its own documents, but there was a url problem with rendering

Example:

first.md:
         [test](test)

hugo run:
        open first。
                https://xxx.io/first/
        open test。
                https://xxx.io/first/test/
 
I want open test。
         https://xxx.io/test/

I myself tried to modify some functions from vimwiki to fix the markdown link style from the [test](test) ->  [test](/test), but the problem is that some aspects of vimwiki will be affected

So, I would like to ask how to deal with this problem from the hugo side?

**Comment by moorereason** [comment]
General support questions should be directed to the [Hugo Discussion Forums](https://discourse.gohugo.io/).  Thanks
