### ISSUE TITLE
Missing step in quick start guide

### ISSUE THREAD

**Issue by akxlr** [gohugoio/hugo#8147]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

The gif in step 4 of the [Quick Start](https://gohugo.io/getting-started/quick-start/) says

<pre>
~/quickstart$ hugo new posts/my-first-post.md
/Users/bep/quickstart/content/posts/my-first-post.md created 
</pre>

When I ran this, the `content` directory was not created. `posts` was instead created directly under `quickstart`, and when I ran `hugo server -D` as instructed, I couldn't see the post. 

<pre>
quickstart$ hugo new posts/my-first-post.md
/Users/me/quickstart/posts/my-first-post.md created
</pre>

It took me a while to figure out that I needed to create the `content` dir and `mv` the `posts/my-first-post.md` under it.

**Comment by jizusun** [comment]
The same also happened to me, and it's so confusing.

**Comment by jmooring** [comment]
I'm not sure exactly what you did, but step 2 of the quick start is:

```
hugo new site quickstart
```

which generates this structure:

```
quickstart/
├── archetypes
│   └── default.md
├── content
├── data
├── layouts
├── static
├── themes
└── config.toml
```
