### ISSUE TITLE
better pandoc support

### ISSUE THREAD

**Issue by jirib** [gohugoio/hugo#8152]
Hi,

it would be nice to have better pandoc integration as I feel commonmark has limitations and pandoc markdown can do much more things. Examples:

- ability to have TOC made by pandoc, just like asciidoctor support (`enableTOC: false` - to pass `--toc` to pandoc, `preserveTOC = false` - to override pandoc TOC html code `<nav id="TOC" role="doc-toc">`with hugo `.TableOfContent` variable; it would be probably nice also to be able to define css selector to find pandoc TOC as one could change pandoc template.
- extra args, eg. to define `--template <file>` or `--data-dir <dir>` ...

**Comment by jwflory** [comment]
If better Pandoc support means that my `toc` appear in AsciiDoc-based HTML, that would be a big win. I see it appear in my local previews with the [Asciidoctor.js extension](https://github.com/asciidoctor/asciidoctor-browser-extension), but it would be nice for the table-of-contents attribute to make it to the generated HTML by Hugo for my site.

**Comment by jirib** [comment]
> If better Pandoc support means that my `toc` appear in AsciiDoc-based HTML, that would be a big win. I see it appear in my local previews with the [Asciidoctor.js extension](https://github.com/asciidoctor/asciidoctor-browser-extension), but it would be nice for the table-of-contents attribute to make it to the generated HTML by Hugo for my site.

Have you tried this?

> By default, Hugo removes the table of contents generated by Asciidoctor and provides it through the built-in variable .TableOfContents to enable further customization and better integration with the various Hugo themes. This option can be set to true to preserve Asciidoctor’s TOC in the generated page.  
-- https://gohugo.io/content-management/formats/#external-helper-asciidoctor

**Comment by jirib** [comment]
BTW, I more wanted to use pandoc markdown with all its extensions, not just TOC...

**Comment by yaxu** [comment]
I had a look at making pandoc more configurable today, the first time I've written any go code but getting somewhere - I managed to get citeproc support working.

I noticed the mathjax support doesn't seem to actually work.. Pandoc does the processing but mathjax itself isn't loaded. I'm not a TeX math user so left that as-is.

**Comment by yaxu** [comment]
As far as I can tell, the YAML header doesn't get passed to pandoc, is that intentional? I can add more parameters to this PR https://github.com/gohugoio/hugo/pull/8610 , but it would be nice to set things in the header too.

**Comment by jirib** [comment]
FYI PR #7529

**Comment by yaxu** [comment]
Ah thanks, somehow I didn't look for previous PRs and now I see there is this one too: https://github.com/gohugoio/hugo/pull/4800

PR https://github.com/gohugoio/hugo/pull/7529 looks great, far more developed than mine. I think being able to configure the existing pandoc support is a really important feature for a lot of people. It would be great to see this merged.

**Comment by danmackinlay** [comment]
In case anyone wants citation support right now you can use [blogdown](https://bookdown.org/yihui/blogdown/#) which invokes pandoc in a separate pass and bypasses hugo's hardcoded pandoc rendering.
