### ISSUE TITLE
Issue with graphical-models name

### ISSUE THREAD

**Issue by JMante1** [gohugoio/hugo#8153]
Am getting the error: Alias "\tag\graphical-models.\page\1\index.html" contains component with a trailing space or period, problematic on Windows. When using hugo with academic and a local server build.

### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.80.0-792EF0F4 windows/amd64 BuildDate: 2020-12-31T13:37:57Z
</pre>

### Does this issue reproduce with the latest release?
I'm Not sure

**Comment by davidsneighbour** [comment]
So... what's the point in `grapical-models.` about? That's not something that works on any operating system. If that is an `academic`-specific issue please take it to their support forum.

**Comment by Fontanapink** [comment]
Same problem here! That is a tag. The full error reads:

```
ERROR 2021/01/24 14:59:00 Alias "\tag\graphical-models.\page\1\index.html" contains component with a trailing space or period, problematic on Windows
Error: Error building site: failed to render pages: cannot create "\tag\graphical-models.\page\1\index.html": Windows filename restriction
```

**Comment by moorereason** [comment]
> `Windows filename restriction`

Files with a trailing period are not valid filenames on Windows.  There's nothing Hugo can do to fix that.
