### ISSUE TITLE
Add support for domain-level redirects

### ISSUE THREAD

**Issue by jwflory** [gohugoio/hugo#8154]
# Summary

Add support for configurable domain-level redirects if a Hugo site moves

# Background

I have moved some Hugo sites from GitHub to GitLab, and others from GitLab to GitHub. In those cases, there is not an easy solution to redirect Git{x} Pages sub-domain from one site to another. In both cases, I am running a Hugo site. One gets regular updates and the other has a banner saying it is out-of-date and does not have current information. I would like to redirect the same site on a previous domain to another site, also powered by Hugo.

There does not seem to be an alternative option to this. I have control of publishing HTML content, but I have no control over the domain provided to me. Some kind of HTML redirect seems like a possible workaround for this.

# Details

Best case scenario, this could be defined in page/post front-matter, or the site `.toml` config. In my case, I want to redirect an entire site (`myproject.git1.io/* -> myproject.git2.io/$1`). I'm not sure what kind of implementation would make sense from a Hugo maintainer point-of-view.

# Outcome

Better support for redirecting one Hugo site to another when DNS is not controlled

**Comment by moorereason** [comment]
Hugo gives you everything you need already.  Put the HTML meta redirect tags in your old site templates.  What do you want more than that?

**Comment by jwflory** [comment]
Hi @moorereason, thanks for clarifying. I was able to do this with a template in `layouts/_default/baseof.html`. I was hoping I could get a clever way to pull in the full URL (i.e. `example.com/p1` goes to `new.com/p1`, `example.com/p2` goes to `new.com/p2`, etc. However, it isn't critically important.

Also for anyone who comes along later, the below tool was super helpful to handle clean redirects across multiple browsers, and to help out with S.E.O. with canonical redirect.

http://insider.zone/tools/client-side-url-redirect-generator/
