### ISSUE TITLE
js: Add Shims option

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8165]
This is meant to improve the situation as described in https://gohugo.io/hugo-pipes/js#shimming-a-js-library

The above works, but it

1. Requires you to edit `package.json`
2. It only works from the project (i.e. it's not practical to do this in a theme/module)

 I have invested some time today looking for a better way, and to cut a very long story short:

I suggest we add add a `shims` config option that works similar to the `browser` element in `package.json`, but resolves files inside the composite `assets`. So you would do:

```html
{{ $shims := dict "react" "js/shims/react.js"  "react-dom" "js/shims/react-dom.js" }}
{{ $js = $js | js.Build dict "shims" $shims }}
```

You obviously still needs to create the shim files, but that is simple enough. Thoughts?

I have tested the above, and it works.

/cc @chrischute @richtera

**Comment by chrischute** [comment]
This sounds like a worthwhile improvement. It felt heavy to edit package.json and force the shims to be a project-wide setting.

Is this enabled by a new feature in ESBuild? I remember [this issue](https://github.com/evanw/esbuild/issues/283) where the ESBuild creator recommended the package.json `browser` approach.

**Comment by bep** [comment]
>Is this enabled by a new feature in ESBuild? 

It's the "import resolver" plugin feature. Not very new.

Note that my main problem isn't the package.json editing -- it's the project relative (or absolute) file paths.

**Comment by chrischute** [comment]
Got it. Well I support the change, happy to review or update documentation when it's time.

**Comment by richtera** [comment]
I think it would be a good idea. I don't understand how the compiled shims' `<script>` tags would be configured and output (i.e. fingerprint, Integrity and sourcemaps)?

**Comment by bep** [comment]
>I don't understand how the compiled shims' <script> tags would be configured and output (i.e. fingerprint, Integrity and sourcemaps)?

In my head, this should just work.

**Comment by bep** [comment]
But, @chrischute -- a question: Given that you have React/ReactDOM included from CDN, what are the scenarios where you need to do an import? I can understand third-party apps, but in your own files?

I'm trying to come up with a failing example, but now all my earlier test setups seems to work fine without any react imports, even though I swear they didn't before...

**Comment by chrischute** [comment]
> Given that you have React/ReactDOM included from CDN, what are the scenarios where you need to do an import? I can understand third-party apps, but in your own files?

I might be misunderstanding the question, but the main reason I import React is to make the IDE happy. I.e., I want to locally have React in my package for code completion, but want to use the CDN in production. Does that answer your question?

**Comment by bep** [comment]
>Does that answer your question?

It does; I have, however, not looked at this problem with those eyes.

**Comment by chrischute** [comment]
OK great, maybe you can see an easier solution given this info.

**Comment by richtera** [comment]
This is very similar to using jsconfig or tsconfig files. ESBuild still does read those to resolve import and require. Using a shims variable is probably more elegant although jsconfig and tsconfig are read and understood by visual studio and adding production version of jsconfig or tsconfig is possible. Adding shims is definitely more elegant.
