### ISSUE TITLE
blocks in rss.xml do not render since v0.63.0

### ISSUE THREAD

**Issue by zerovip** [gohugoio/hugo#8170]
### Description

Hi, all.

I think `{{ block "foo" . }}` is a good way to reuse my codes, so I wrote a lot of blocks, not only in HTML templates but also in XML templates. XML templates don't have a `baseof`, so I just put the `{{ block "foo" . }}` in `_default/rss.xml` and define blocks in `_default/list.xml`.

This works fine, until v0.63.0. It's been a long time, but actually I just noticed this problem recently. I did some search but I didn't find any reports. Let me know if this one duplicates.

I bisected the commits and found that c6d650c8c8b22fdc7ddedc1e42a3ca698e1390d6 is the first bad commit. But this commit contains too many changes, and it seems that v0.63.0 made a really big improvement. So I decide to post this here to see if anyone can tell me what was going on. I wonder is it a bug, or hugo deliberately do not support for that?

### Steps to reproduce

I wrote [a very simple example site](https://github.com/zerovip/hugo-xml-block-test) so that this problem can be reproduced easily.

```bash
$ git clone https://github.com/gohugoio/hugo.git

$ git clone https://github.com/zerovip/hugo-xml-block-test

$ cd hugo && git reset --hard 8585b388
$    # 8585b388 is the last good commit

$ go install

$ cd ../hugo-xml-block-test && ~/go/bin/hugo server
$     # now open localhost:1313/ and check the rss page, they should work fine.

$ cd ../hugo && git reset --hard c6d650c8
$     # c6d650c8 is the first bad commit

$ go install

$ cd ../hugo-xml-block-test && ~/go/bin/hugo server
$    # now refresh the broswer, you will see the blocks in rss don't render any more.
```

**Comment by bep** [comment]
Hmm ... surprises me that a bug like that has survived so long.

@moorereason is this related to "that other" issue?

**Comment by moorereason** [comment]
@bep, what other issue are you referring to?  #8149 doesn't resolve this issue.

**Comment by bep** [comment]
Ok @zerovip I misunderstood the problem -- I'm not sure how that site could have worked in < 0.63 (I guess you was lucky with the order of things), but you need to read up on the documentation of Base templates: https://gohugo.io/templates/base/#readout

Note that the naming is important: `block` constructs that is meant to be implemented by `define` needs to live in `baseof.*` files (e.g. `baseof.xml`).

Take further questions at https://discourse.gohugo.io/

**Comment by zerovip** [comment]
> `block` constructs that is meant to be implemented by `define` needs to live in `baseof.*` files (e.g. `baseof.xml`).

Thank you very much, @bep ! I only read the [lookup order](https://gohugo.io/templates/lookup-order/) before, I didn't find a `baseof.xml` and then thought there was no `baseof.xml`, I was wrong. I rename the `rss.xml` to `baseof.xml` and everything works as I expected. Thank you for your hint! I should try that first.

Sorry if I didn't make it clear at the beginning, which misled you and waste your time. Thanks again for your helpful reply, I read the documentation of Base templates and now I understand them.
