### ISSUE TITLE
render-heading.rss.xml doesn't work

### ISSUE THREAD

**Issue by stereobooster** [gohugoio/hugo#8176]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

## Bug

`render-heading.html` works as expected. I can see custom headings in HTML output. But I see same output for RSS as well. Hugo ignores `render-heading.rss.xml` and `render-image.rss.xml`.

Reproducible example is here https://github.com/stereobooster/hugo-bug-rss

PS. thanks for the project ❤️

**Comment by jmooring** [comment]
Problem reported again today:
<https://discourse.gohugo.io/t/rss-specific-render-hook-not-working/31647>
