### ISSUE TITLE
Make the argument to .Render (optionally) be a map with type and layout keys

### ISSUE THREAD

**Issue by NicoHood** [gohugoio/hugo#8182]
.Render currently only supports LAYOUT parameter. But I also need to pass a custom TYPE to the render function, as I do not want to specify the type on each page explicit and the default lookup is not useful in my usecase.

https://gohugo.io/functions/render/

To better understand the issue, here is my usecase: I want to build a modular homepage with multiple markdown files that are all rendered differently. I am using a Leaf bundle here and iterate through all page resources. I found no better way to do that. Also I needed to specify the slug for the homepage in index.html itself. If you got a better solution, [please let me know](https://discourse.gohugo.io/t/is-it-possible-to-have-a-homepage-not-using-index-md/30906). Nevertheless I think the extra parameter is useful!

content:
```
- home
 |- index.md (type: modular, layout: single, slug: '')
 |- 01_introduction.md (layout: text) -> dont want to specify type: modular
 `- 02_faq.md (layout: questions) -> dont want to specify type: modular
```

theme:
```
- layouts
 `- modular
  |- single.html
  |- text.html
  `- questions.html
```

layouts/modular/single.html
```html
{{ define "main" }}
  <h1>{{ .Title }}</h1>
  
  <br>
  {{ .Content }}
  <br>

  {{ with .Resources.ByType "page" }}
    {{ range . }}
      <!-- Here I want to specify the type of the parent -->
      {{ .Render .Layout $.Type }}
    {{ end }}  
  {{ end }}

{{ end }}
```

**Comment by bep** [comment]
I think I understand it, but I suspect this would be a better solution:


```html

  {{ with .Resources.ByType "page" }}
   {{ $param : (dict "type" $.Type) }}
    {{ range . }}
      {{ .Render $param }}
    {{ end }}  
  {{ end }}
```

That way we can check if it's a string (=l layout) and make room for other options in the future.

**Comment by NicoHood** [comment]
Sure, so you mean something like this:
```
.Render [LAYOUT] [TYPE]
```

And by specifying a dict, you can leave out the `LAYOUT` option and explicitly set the `TYPE`. Makes sense.

**Comment by bep** [comment]
````
.Render [LAYOUT] [TYPE]
```

I'm not totally sure what the above means, but the logic behind the scenes have the appropriate logic, so if you do:

```
.Render (dict "layout" "foo" "type" "bar")
```

It will pick the most specific template ("foo").

**Comment by NicoHood** [comment]
```
├── _default
│   ├── baseof.html
│   ├── list.html
│   └── single.html
├── bar
│   ├── baseof.html
│   ├── foo.html
│   ├── list.html
│   └── single.html
└── index.html
```

From what I understand is, that I currently can only change the layout (foo, list, single,..), but not the type (_default, bar, posts, ...). So it will not only pickup the layout, but also check for the layout type.

**Comment by bep** [comment]
I suspect I was a lttle bit off in my last answer. I do suspect that what I suggest would actually solve your problem AND  be simple to implement, a win win.

**Comment by regisphilibert** [comment]
I would love this to be addressed. Not necessarily to be able to enforce the type but to be able to pass data on top of the page context!

**Comment by kontralto-rob** [comment]
@regisphilibert  You might instead consider using a partial if you want to pass additional data to a view template.
