### ISSUE TITLE
Template block in partial not overriden

### ISSUE THREAD

**Issue by inwardmovement** [gohugoio/hugo#8188]
Let's say I override the `title` block in the homepage template:

**index.html**
```
{{ define "title" }}{{ .Site.Title }} | {{ .Site.Params.description }}{{ end }}
```

It is working if I include the `title` block in `baseof.html`:

**baseof.html**
```
<title>{{ block "title" . }}{{ .Title }} | {{ .Site.Title }}{{ end }}</title>
```

But it is not working if I include the `title` block in a partial and then import the partial in `baseof.html`:

**baseof.html**
```
{{ partial "head" . }}
```

**head.html**
```
<title>{{ block "title" . }}{{ .Title }} | {{ .Site.Title }}{{ end }}</title>
```

Then the title content seems to be the last known or "Hugo default" title.

<pre>
Hugo version 0.76.5
</pre>

**Comment by pamubay** [comment]
Duplicate #7936
