### ISSUE TITLE
Full/absolute URL for image links in RSS feeds

### ISSUE THREAD

**Issue by patdavid** [gohugoio/hugo#8200]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0/extended windows/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

### Issue
When generating RSS feeds any <img> links in the content that use a relative (local) path to the image keep them:

With content as:
```
├── My New Post
│       │   ├── index.md
│       │   ├── image.png
```

in `index.md`:
```html
...
<img src="image.png">
...
```

This works perfectly well for actual post content on the website, but the RSS feed maintains the same img source (not using an absolute path).  This breaks the RSS rendering of the content in some feed readers.

I was hoping to perhaps fix this with a regex replace in the RSS template, but re2 in go doesn't support forward/negative lookaheads to deal with this (ie: _not_ replacing src path if it's already absolute).

Any ideas or thoughts about pushing absolute src paths for images in RSS feeds?

**Comment by zerovip** [comment]
[Render hooks](https://gohugo.io/getting-started/configuration-markup#markdown-render-hooks) should help, but seems that there is a #8176 (?)

**Comment by patdavid** [comment]
We've had limited success with `layouts/_default/_markup/render-image.html` and adding a full URL there (this _does_ get picked up by the RSS template as part of `{{ .Content | html }}`.

However, this doesn't seem to work for `<figure> <img> ...` - my guess is that using the figure shortcode skips(ish) the markdown conversion for the render-image.

**Comment by stereobooster** [comment]
AFAIK Render hooks only work for markdown, but not for HTML tags or shortcodes

this works:

```md
![alt](./path.jpg)
```

this doesn't

```md
<img src="" />
{{< img src="" >}}
```
