### ISSUE TITLE
Unable to override deployment.targets.1.URL with environmental variable HUGO_DEPLOYMENT_TARGETS_1_URL

### ISSUE THREAD

**Issue by macyabbey** [gohugoio/hugo#8208]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0-792EF0F4/extended darwin/amd64 BuildDate: 2020-12-31T13:44:15Z
</pre>

### Does this issue reproduce with the latest release?
Yes

I believe this is caused by the configuration key "URL" being all upper case in the configuration file, which is in the documentation.

from hugolib/config.go

```
	// Apply environment overrides
	if len(d.Environ) > 0 {
		// Extract all that start with the HUGO prefix.
		// The delimiter is the following rune, usually "_".
		const hugoEnvPrefix = "HUGO"
		var hugoEnv []types.KeyValueStr
		for _, v := range d.Environ {
			key, val := config.SplitEnvVar(v)
			if strings.HasPrefix(key, hugoEnvPrefix) {
				delimiterAndKey := strings.TrimPrefix(key, hugoEnvPrefix)
				if len(delimiterAndKey) < 2 {
					continue
				}
				// Allow delimiters to be case sensitive.
				// It turns out there isn't that many allowed special
				// chars in environment variables when used in Bash and similar,
				// so variables on the form HUGOxPARAMSxFOO=bar is one option.
				key := strings.ReplaceAll(delimiterAndKey[1:], delimiterAndKey[:1], delim)
				key = strings.ToLower(key)
				hugoEnv = append(hugoEnv, types.KeyValueStr{
					Key:   key,
					Value: val,
				})

			}
		}
	}
```

I could also be way off - unfamiliar with codebase and language

**Comment by bep** [comment]
How does this look in your config file?

**Comment by macyabbey** [comment]
[@bep] toml file, relevant section:

```
[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "dev"
URL = "s3://xxx"
```
I attempted to:

- not define URL in the configuration toml file
- define as empty/nonsense string
- Use env variable of HUGO_DEPLOYMENT_TARGETS_0_URL in case it was a zero based / 1 based indexing issue

None of that worked.

I also tried not defining deployment.targets in the toml configuration file, and instead setting it entirely through an environmental variable as serialized JSON, which did not seem to work. I thought maybe the issue there was my configuration files were all TOML so perhaps I needed to serialize TOML instead. 

However, it seemed that the viper library should allow an environment variable as described in this issue. After more digging, I guessed having the configuration key be all caps was the source of why it was not working.

**Comment by bep** [comment]
Yes, setting a slice item value via env is not supported (there is another open issue about this, I think).
