### ISSUE TITLE
Error page on mobile with weird design

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#8217]
```
$ hugo version
Hugo Static Site Generator v0.80.0-792EF0F4/extended linux/amd64 BuildDate: 2020-12-31T13:46:18Z
```

This is what I see on mobile (via Chromium > Developer Tools > set viewport to mobile size) if an error occurs:

![Selection_112](https://user-images.githubusercontent.com/83281/107222666-caa58700-6a47-11eb-8f1d-d34c87fbcb60.png)

It appears there needs to be some re-styling for smaller viewport widths. What falls into my eye is, that it's not just the same design as on desktop, it's larger fonts... maybe just some config variable got messed up?

**Comment by nternetinspired** [comment]
Is the error message inside <pre> tags?
