### ISSUE TITLE
[Tooling]: Add a translations extractor tool to Hugo

### ISSUE THREAD

**Issue by CarlSchwan** [gohugoio/hugo#8218]
Hi,
One of the problem when internationalizing a huge Hugo website is that you need to be able to solve the following problems:

* Extract individual strings and give them into a format that translation tools can use (e.g. gettext but other standard formats too)
* Synchronize changes, when a string gets modified in the original language, the translators should get notified and be able to update their strings.
* markdown file for each language should be generated from the original language file and the translation files

These are hard problems and we (in KDE) worked on a small python script that is able to solve these problems for our use cases: https://invent.kde.org/websites/kde-org/-/blob/master/translations.py. It supports only the shortcodes we use in kde.org, no inline HTML support, and requires some small changes in the original markdown file.

For example following text:

```
* Hello

## This is a title

{{< img src="URL" alt="My alt" caption="My caption" >}}
```

will extract the following strings for the translators and additionally add some metadata (locations of the string, it is a title, it is a list element, ...)

* Hello
* This is a title
* My alt
* My caption 

Then these strings are translated, a new file for each language is generated with the translations.

I wonder if this script could be ported to Go and then upstreamed to Hugo as a helpful CLI tool. Would it be something that Hugo developers are interested in? If yes, it would probably be good to discuss what features exactly this tool should provide. In KDE, we have configurations for what named field we should extract from shortcodes, what keys in the front matter should be extracted and what files should be extracted (because we don't want to translate the 1400 pages from kde.org). We also are only interested in gettext support since our tooling is based on gettext, but I guess others want more export formats.

**Comment by ognarb** [comment]
So I have been thinking a bit more about the configuration to exclude or include page to the list of translatable pages and I think this could probably use some frontmatter configuration keys: `translatable: true` or `extractTranslation: true`. This would have the advantage that we can probably reuse quite a bit of Hugo internals to fetch every page that we want to make available for translators. And we can use Front Matter Cascade to reduce the need to map every page with this key.

I'm currently looking at Hugo source code to see if I could reuse the parser :) I shall try to create a prototype next week.
