### ISSUE TITLE
please help: Academic Theme: custom types of publications

### ISSUE THREAD

**Issue by GuidoBo** [gohugoio/hugo#8226]
I am helping a friend with her new website for a 501c NGO using Academic. We are both thrilled by Hugo and the Academic. Now here is what we didn't get to work:

For publications there is like a list with definitions on what exactly is the type of publication (e.g. report, book, paper, etc.). What do we need to do if we **want our own classification/nomenclature here**, e.g. "filed brief", "public submission"? Or alternatively: where can we edit the translation for the publication classes?

Regards,

Guido

**Comment by ognarb** [comment]
Github issues shouldn't be used for support requests. You should probably try https://discourse.gohugo.io/ instead.

**Comment by anthonyfok** [comment]
> Github issues shouldn't be used for support requests. You should probably try https://discourse.gohugo.io/ instead.

Thanks to @ognarb's advice, @GuidoBo has started a new thread on Hugo Discourse at https://discourse.gohugo.io/t/academic-theme-customize-publication-nomenclature/31178

Closing this GitHub issue.
