### ISSUE TITLE
Less CSS preprocessor support

### ISSUE THREAD

**Issue by dmgawel** [gohugoio/hugo#8230]
Less [1] is a neat and widely used CSS preprocessor. I'd like to propose adding support for Less language as part of Hugo Pipes.

### Less usage

Less is a second most popular CSS preprocessor [2]. Contrary to what some of the industry articles might state, Less is nowhere near dead, deprecated or obsolete. It's used in many projects [3], including notable examples like StackExchange design system [4], WeChat official UI kit [5] or earlier versions of TailwindCSS. 

### Less vs Sass

One could say: "Why should we add support for another preprocessor? Isn't Sass enough?". While quite similar in terms of features and syntax, they differ fundamentally in used paradigm. Sass is an imperative language (like JS), while Less is declarative (like CSS itself) [6]. Each of these languages may work better for different projects, taking into account project needs or developer preferences. Thus, in my opinion, it makes sense to support both.

### Less in Hugo

I think that the way Less is written makes it a good candidate for Hugo. Official Less implementation is pure JavaScript, with both CLI and programmatic API available. It is also possible to use environment-free function that takes file manager as a parameter [7]. That opens door to support Hugo's virtual union filesystem and offer the same powerful import resolution we have in `js.Build` since v0.78.0.

### References 

[1] http://lesscss.org/
[2] https://www.npmtrends.com/less-vs-stylus-vs-node-sass-vs-sass
[3] https://github.com/less/less.js/network/dependents?package_id=UGFja2FnZS00OTM1MzY1ODc%3D
[4] https://github.com/StackExchange/Stacks
[5] https://github.com/Tencent/weui
[6] https://web.archive.org/web/20151029232810/https://getcrunch.co/2015/10/08/less-the-worlds-most-misunderstood-css-pre-processor/
[7] http://lesscss.org/usage/#developing-less-how-to-run-less-in-other-environments

**Comment by gandhiShepard** [comment]
Why not Stylus as well? At best, the option to choose between Scss, Sass, Less and Stylus would be nice. The ability to specify the preprocessor in the config.toml would be nice. The default could remain scss/sass. In the end it comes down to productivity. Different teams and people simply work faster and better with other preprocessors.

**Comment by bep** [comment]
Is there a solid **native Go** implementation?

**Comment by dmgawel** [comment]
@bep Unfortunately no. I'd definitely mention that 😉

**Comment by bep** [comment]
>Unfortunately no. I'd definitely mention that 😉

Yes, that's true. Your proposal is well written and your arguments are sound.

My take on integrating with these JS tools is that it needs to _do a thing that we have to have and there are no native options_.  PostCSS (purge css) and Babel (we added that pre ESBuild) may be two examples of that. As a side effect of PostCSS we got reasonable TailwindCSS support. 

The thing is, adding this stuff has cost. One thing is the performance, but also the integration/maintainance cost. You have no idea of the amount of gray hair I accumulated trying to make sense of how config/dependency loading worked (differently) between these tools :-)

I used LESS myself some years ago,  but you're the first (as I remember) who have asked for LESS support in Hugo, so I suspect we need more hands in the air ("I want, I want!") before we can add it.

**Comment by dmgawel** [comment]
@bep I understand your position, that totally makes sense. Let's wait and see if there's more interest.

**To all readers:**
If you'd find Less integration into Hugo Pipes useful, please give a thumbs up to my original message. Please avoid commenting, unless you have something new to share (i.e. you're in the middle of writing a native Go compiler for Less 😛).

**Comment by aep** [comment]
scss no longer supports native either, so eventually someone will have to figure out how to wrap the nodejs ecosystem anyway.

**Comment by bep** [comment]
>scss no longer supports native either, so eventually someone will have to figure out how to wrap nodejs.

Not sure what you mean by this, but Hugo have support for both LibSASS and Dart Sass.

**Comment by aep** [comment]
> > scss no longer supports native either, so eventually someone will have to figure out how to wrap nodejs.
> 
> Not sure what you mean by this, but Hugo have support for both LibSASS and Dart Sass.

Interesting. Didn't work the last time I tried on arm/linux. Will try again.

**Comment by aep** [comment]
Nope still doesn't work. Neither on Mac/arm (so all new apple devices).  if these are not supported, ignore my comment. Will be looking into forking then to add something native.
