### ISSUE TITLE
Hash sign (#) in taxonomy terms not properly sanitized

### ISSUE THREAD

**Issue by michaelroland** [gohugoio/hugo#8232]
### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.80.0/extended windows/amd64 BuildDate: unknown
</pre>
<pre>
Hugo Static Site Generator v0.80.0-792EF0F4/extended linux/amd64 BuildDate: 2020-12-31T13:46:18Z
</pre>

### Does this issue reproduce with the latest release?

Yes, tested with the latest (0.80.0) version on Windows and Linux.

### Issue

When a taxonomy term contains one or more `#` (hash sign) characters, the first hash sign character is not sanitized (escaped to `%23`) in URLs generated for the term page. Consequently, the browser will treat the path segement following the hash sign as fragment identifier and not as part of the path. If a taxonomy contains more than one hash sign, only the first one is not sanitized, all subsequent hash signs are properly sanitized to `%23`.

### Example

- `testtaxonomy = [ "Testterm#" ]`
  - generates a directory named "testterm#"
  - URL (.RelPermalink) becomes "/testtaxonomy/testterm#/"
- `testtaxonomy = [ "Test#term#" ]`
  - generates a directory named "test#term#"
  - URL (.RelPermalink) becomes "/testtaxonomy/test#term%23/"
- `testtaxonomy = [ "Test#te#rm#" ]`
  - generates a directory named "test#te#rm#"
  - URL (.RelPermalink) becomes "/testtaxonomy/test#te%23rm%23/"

### Expected behavior

All occurrences of `#` should be escaped in the resulting URLs or, better yet, `#` characters should be removed from the generates filenames at all. Considering that other potentially problematic characters (such as `!?§$%&*=,:;|(){}[]<>"`) are already removed from the generated filenames, I'm rather surprised that `#` is not. I therefore believe that this would be the more logical solution. In my opinion, the same applies to `.` (dot), `+` (plus), `~` (tilde), `_` (underscore), [and potentially any other non-word character that I missed] which are currently kept as-is. This would have the benefit of also mitigating issues like #8153.

**Comment by david-bakin** [comment]
See also related #4926.  It would be sweet if I could have a tag `C#`...

**Comment by michaelroland** [comment]
This issue is still observable in the lastest release. Tested with

```
hugo v0.98.0-165d299cde259c8b801abadc6d3405a229e449f6+extended windows/amd64 BuildDate=2022-04-28T10:23:30Z VendorInfo=gohugoio
```

**Comment by michaelroland** [comment]
This issue is still observable in the latest release. Tested with
```
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended windows/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
```
