### ISSUE TITLE
Config: Additional file locations/lookup order

### ISSUE THREAD

**Issue by LukeTOBrien** [gohugoio/hugo#8233]
Hello,

I use Hugo in my own site and I find it excellent.

I have created some shortcodes and I am interested in creating more and I would like to share them so rhat others can use what I have created.  
I use NPM for my devlopment, I found a [hugo-bin](https://www.npmjs.com/package/hugo-bin) package which is easy way to use HUGO and I have been thinking about publishing my shortcodes to NPM.

The problem is that the shortcodes have a local [file location(https://gohugo.io/templates/shortcode-templates/#file-location), if I had my shortcodes as a package they would be located in the `node_module` folder - Something like:  
`./node_modules/my-package/shortcodes/shortcode.html`.

So therefore I would need to adde `./node_models/my-package/` to the [lookup order](https://gohugo.io/templates/lookup-order/) in `config.toml`.  

Does this make sence to people?  
If this doesn't currently exist then I would like to suggest it.

**Comment by bep** [comment]
What you want is possible as is; have a look at https://gohugo.io/hugo-modules/configuration/#module-config-mounts

**Comment by bep** [comment]
As a side note: I would just drop the publishing to NPM step and just import your GitHub repos as Hugo Modules (see docs).
