### ISSUE TITLE
Auto-updater?

### ISSUE THREAD

**Issue by drupol** [gohugoio/hugo#8251]
Hello,

I'm a user of the [Symfony CLI](https://symfony.com/download) which is written in Go.
Every now and then, it asks for auto-updating itself, I just press `Y` and a few seconds later, it's done.

Do you think it would be possible to provide such a thing for Hugo? It would be so useful.

WDYT?

**Comment by akshaybabloo** [comment]
That would be good provide the original binary file is not downloaded by a package manager.

I think this could be checked using the `which hugo` (Linux) or `where hugo` (windows), if it shows up with any of the existing package manager path then ignore the upgrade (I guess) and just show that there is an update available. If not update it.

**Comment by bep** [comment]
I once thought this would be a great idea, now I'm not so sure. Several problems with this:

* Hard to do well in a cross-platform way
* Hard to do securely

**Comment by drupol** [comment]
The way I see the thing is that It would download the release straight from Github.

Why would it be unsecure?

I think, as far as I remember, there is a way to retrieve the latest release of a project with one single rest call.

**Comment by bep** [comment]
>Why would it be unsecure?

https://en.wikipedia.org/wiki/Man-in-the-middle_attack

**Comment by drupol** [comment]
Obviously it would use `https`, to mitigate the risk of MIDM attack...

**Comment by coliff** [comment]
I currently use the excellent **[hugo-bin](https://github.com/fenneclab/hugo-bin/)** project, it makes installing and updating Hugo super-easy. Hugo is update quite regularly so without hugo-bin, manually downloading, unzipping and moving hugo.exe to the right folder is a pain.

I would **LOVE** to see the hugo-bin project moved to the gohugoio organization and be an official distribution method. [I know that @XhmikosR would too!](https://github.com/fenneclab/hugo-bin/issues/32) :-)

I would imagine most developers using Hugo are already making use of `package.json` to keep their dependencies up-to-date so makes sense to me to be able to install and update Hugo from here too.

**Comment by drupol** [comment]
> I currently use the excellent **[hugo-bin](https://github.com/fenneclab/hugo-bin/)** project, it makes installing and updating Hugo super-easy. Hugo is updated quite regularly so without hugo-bin, manually downloading, unzipping and moving `hugo.exe` to the right folder can be a pain.

Ok, but this needs nodejs! I don't think we should rely on another technology for doing that.
People here are concerned with security, I don't think adding another layer (especially that one) is a good idea.

It's fully possible to do it in go, let's use go.
