### ISSUE TITLE
`HasCurrentMenu` only matches on URL with `/` appended

### ISSUE THREAD

**Issue by stefanv** [gohugoio/hugo#8254]
I notice that `IsMenuCurrent` only matches correctly if the URL in the config has a trailing `/`.  I.e., I need to specify:

```
  [[menu.main]]
    name = "ItemName"
    identifier = "foo"
    url = "/foo/"
    weight = 40
```

but **not**

```
  [[menu.main]]
    name = "ItemName"
    identifier = "foo"
    url = "/foo"
    weight = 40
```

[The docs](https://gohugo.io/content-management/menus/) always use such trailing slashes, so this may well be by design.  If so, would a PR for a line in the documentation be helpful?

### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
Related https://github.com/gohugoio/hugo/issues/9150
