### ISSUE TITLE
Google Analytics internal templates change

### ISSUE THREAD

**Issue by djatwood** [gohugoio/hugo#8261]
There's `google_analytics.html` and `google_analytics_async.html`. Both templates load asynchronously but the "async" one allows preloading.

> While the Google Analytics tag described above ensures the script will be loaded and executed asynchronously on all browsers, it has the disadvantage of not allowing modern browsers to preload the script.

> The alternative async tag below adds support for preloading, which will provide a small performance boost on modern browsers, but can degrade to synchronous loading and execution on IE 9 and older mobile browsers that do not recognize the async script attribute. Only use this tag configuration if your visitors primarily use modern browsers to access your site. 

[View in docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tag)

What do you think about changing the way we define GA in the config?
```toml
[googleAnalytics]
  id = "UA-PROPERTY_ID"
  preload = true
```

Or at the very least change the name from `google_analytics_async.html` to `google_analytics_preload.html`?

**Comment by djatwood** [comment]
There is no option to not use the async attribute when using v4 gtag.js see #8264

**Comment by coliff** [comment]
I don't think we should rename those older Universal Analytics templates, it could break for users/themes which depend on it. I guess aliases/redirects could be setup, but that complicates things.

It's clear from Google that Universal Analytics will no longer receive updates and they are pushing for all users to update to using GA4, so I suggest we leave these older templates as they are.
