### ISSUE TITLE
Version 0.81.0 build fails due to missing dependency `io/fs` in golang 1.15

### ISSUE THREAD

**Issue by Bronek** [gohugoio/hugo#8265]
### What version of Hugo are you using (`hugo version`)?

<pre>
0.81.0
</pre>

Here is what happens if I try to build with go 1.15.8:

<pre>
$ go install --tags extended
go: downloading github.com/gobwas/glob v0.2.3
. . . 
tpl/internal/go_templates/texttemplate/helper.go:11:2: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)
</pre>

I think this is related to https://github.com/golang-migrate/migrate/issues/480 

To reproduce:
1. clone https://github.com/Bronek/build-hugo - prerequisites are: `make` and (`docker` or `podman`), on Linux
2. bump version number near the top of `Makefile`
3. issue `make build` - this will download docker image `golang:1.15.8-buster` and then run the build inside the container

**Comment by bep** [comment]
Hugo 0.81.0 need Go >= 1.16 to build. That is unfortunate, but not something that I can fix.

**Comment by ericlentz** [comment]
In that case, you need to update the Dockerfile:

0.81.0 has: FROM golang:1.15-alpine AS build
