### ISSUE TITLE
.Scratch.Add creates two quotation marks

### ISSUE THREAD

**Issue by cascading-jox** [gohugoio/hugo#8266]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: unknown (from Fedora 33 repo)
</pre>

### Does this issue reproduce with the latest release?

Yes, I just tested it with the binary for 0.81. 

### The bug
I was testing different ways to add parameters to schema tags and using this `{{- .Scratch.Add "social_media_links" 1 -}}` seemingly creates two quotation marks which in my case makes the JSON array invalid. 

#### A bit off topic in case someone else needs a workaround: 
Using something like this:
 ```Hugo
    {{ .Scratch.Add "test" (slice .Params.instagram_url .Params.facebook_url) }}
    {{ apply (.Scratch.Get "test") "urlize" "." }}	
```
Creates a perfect array of strings that you can put in an array in JSON. 

Edit: I just realized it also creates two extra quotation marks but it solves my issue I had in the schema tag.

Edit2: Using trim like this makes no difference: 
```Hugo
{{- trim (.Scratch.Add "test" (slice .Params.instagram_url .Params.facebook_url)) "\"" -}}
```
Edit3: .Scratch.Set also creates two quotation marks but not .Scratch.Get. I think for now I will just move the the initiation to somewhere outside the JSON object.

**Comment by davidsneighbour** [comment]
Edit 1: This is a SUPPORT question. you should have opened it over at the discourse as was advised when you opened the issue. 

When you "print" out a variable, then Hugo shows it as it's defined, which adds the `"` to the code. You need to format them like the following:

```
{{ printf "%s" $variable }}
```

And it's printed as you defined. The %s means string. Other formats - read the docs: https://gohugo.io/functions/printf/#readout

**Comment by cascading-jox** [comment]
I apologize, I guess my inexperience caused me to believe it was a bug.

**Comment by davidsneighbour** [comment]
No problem, for the future feel free to look by at discourse.gohugo.io - help comes quicker there and if it's a bug we will find that out too :) hope the printf solves your problem.

**Comment by cascading-jox** [comment]
I did not quite get what you mean with "when you print out a variable" since I am not printing anything intentionally just adding to `.Scratch` and that adds the `"`. I will probably open a thread on the discourse soon though, maybe we should discuss it there.

**Comment by cascading-jox** [comment]
Not so surprisingly I found a [post](https://discourse.gohugo.io/t/scratch-set-outputting-double-quotes-when-used-in-script-tag/30298/6) about it but I have no idea about the reasoning for it. To me it looks like unexpected behavior.
