### ISSUE TITLE
Upper Case Letters in Path Cause Resource Match to Fail

### ISSUE THREAD

**Issue by kc0bfv** [gohugoio/hugo#8267]
### What version of Hugo are you using (`hugo version`)?

Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2020-12-31T20:02:59Z

Just tried it on this one too:

hugo v0.81.0-59D15C97 linux/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio

### Does this issue reproduce with the latest release?

Yes.

### Problem

I'm having an issue like the one rhyst posts about here: https://discourse.gohugo.io/t/upper-case-letters-in-path-causing-match-to-fail/28069

If rhyst has already posted a bug - I'm sorry.  I couldn't find it.

In short - if I try to use resources.Match to grab a global resource, globs only match results with fully-lowercase paths.  There is a workaround - putting a * in the directory parts of globs.  The post above demonstrates this well, but I've got a full minimal example here:

https://github.com/kc0bfv/hugo_asset_glob_prob

And the result from building is here:

https://github.com/kc0bfv/hugo_asset_glob_prob/blob/main/public/index.html

Which looks like the text towards the bottom.

I expected resources.Match to use a case insensitive glob, like ".Resources.Match" is supposed to.  ( https://gohugo.io/content-management/page-resources/#methods )  Case-sensitive globs would be fine, but regardless, I wouldn't expect only lowercase path matches...

```
Matching "Time/*"
* time/timeTime.png
* time/timetime.png

Matching "time/*"
* time/timeTime.png
* time/timetime.png

Matching "*Time/*"
* Time/TimeTime.png
* Time/Timetime.png
* time/timeTime.png
* time/timetime.png

Matching "*time/*"
* Time/TimeTime.png
* Time/Timetime.png
* time/timeTime.png
* time/timetime.png
```

**Comment by bep** [comment]
>hugo v0.81.0-59D15C97 linux/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio


Are you sure you use the version above? I say this because I remember fixing exactly that bug in that release.

**Comment by kc0bfv** [comment]
I just re-downloaded that release from github, and re-ran it on my demo site, and got the same output.

Yup.  Thanks for all you do @bep.

**Comment by jmooring** [comment]
Duplicate of https://github.com/gohugoio/hugo/issues/7686, logged by @rhyst on Sep 14, 2020.

**Comment by kc0bfv** [comment]
You're right.  Dang.  I searched for that username and several terms he used, too.  That one didn't pop up. Strange.
