### ISSUE TITLE
Non functional binaries for hugo extended v0.81.0 linux/amd64

### ISSUE THREAD

**Issue by antoniofagardo** [gohugoio/hugo#8268]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo extended v0.81.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

* Tried to run `hugo version` on a fresh set of binaries from the latest extended version 0.81.0 for linux/amd64 downloaded from github and the command return `/bin/ash: hugo: not found`

* Tried the same process w/ the 0.81.0 for linux/amd64  (standard, not the extended one) and the binaries work as expected

**Comment by pamubay** [comment]
Which package? the **hugo_extended_0.81.0_Linux-64bit.tar.gz** or **hugo_extended_0.81.0_Linux-64bit.deb** one?

I tried hugo_extended_0.81.0_Linux-64bit.tar.gz, works perfectly.

if the error message `/bin/ash: hugo: not found`, i suspect the hugo binary not under `PATH`.

What is your OS?

**Comment by antoniofagardo** [comment]
I am using **hugo_extended_0.81.0_Linux-64bit.tar.gz** inside a Dockerfile on macOS High Sierra

I also thought it was a `PATH` problem at first but even calling the binary from its location produces the same results:
```
/workspaces/ecommerce-wood $ hugo version
/bin/ash: hugo: not found

/workspaces/ecommerce-wood $ /usr/local/bin/hugo version
/bin/ash: /usr/local/bin/hugo: not found

/workspaces/ecommerce-wood $ ls -la /usr/local/bin/
total 45832
drwxr-xr-x 1 root root     4096 Feb 21 01:01 .
drwxr-xr-x 1 root root     4096 Feb 19 13:20 ..
-rwxr-xr-x 1 root root      315 Feb 19 13:20 code
-rwxr-xr-x 1 root root 46917496 Feb 19 17:54 hugo
```

If I change **hugo_extended_0.81.0_Linux-64bit.tar.gz** to **hugo_0.81.0_Linux-64bit.tar.gz** everything work as expected


My Dockerfile:
```
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.154.2/containers/alpine/.devcontainer/base.Dockerfile

# [Choice] Alpine version: 3.12, 3.11, 3.10
ARG VARIANT="3.12"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-alpine-${VARIANT}

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
ARG HUGO_VERSION="0.81.0"
RUN if [ $(uname -m) == "x86_64" ]; then RELEASE="hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz"; else RELEASE="hugo_${HUGO_VERSION}_Linux-ARM64.tar.gz"; fi \
    && wget -c https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${RELEASE} -O - | tar -xz -C /tmp \
    && mkdir -p /usr/local/bin \
    && mv /tmp/hugo /usr/local/bin/hugo
```

**Comment by pamubay** [comment]
Ahh, docker.
Yes, the extended version has dynamically linked library for libsass to work.

[Hugo Documentation](https://gohugo.io/getting-started/installing/#docker) recommends this Docker Images https://hub.docker.com/r/klakegg/hugo/

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
