### ISSUE TITLE
Implement the --version option

### ISSUE THREAD

**Issue by yuguamax** [gohugoio/hugo#8272]
Why don't you implement the --version option that Gnu recommends to implement?

**Comment by davidsneighbour** [comment]
Probably because it's programmed in Go and Go has the same behaviour like Hugo:

```
go version
hugo version
```

It's also not licensed under a GNU license, so what GNU recommends is not really a requirement here?

**Comment by yuguamax** [comment]
In the first place, the option to connect two hyphens originated in Gnu.
It's strange that --help is there but --version is not.

**Comment by bep** [comment]
The short answer is that we use a CLI framework for this (Cobra). You should ask the question in that upstream project.
