### ISSUE TITLE
Squash.io integration?

### ISSUE THREAD

**Issue by emiquelito** [gohugoio/hugo#8275]
Hello Hugo Community!

I'm with [Squash.io](https://www.squash.io/) and we wanted to support the Hugo project by providing on-demand test environments for each Pull Request (i.e: a complete staging environment for each PR, running your full stack). Our service is free for Open Source projects like Hugo and we would be able to increase our standard limits as needed to provide great user experience for Hugo developers and contributors.

Here is how it works, you push a branch of code, create a Pull Request and Squash automatically posts as comment with a unique URL where you can test the branch changes in isolation (it usually takes just a few minutes for an environment to spin up):

![squash-url](https://user-images.githubusercontent.com/98694/108773052-0c8bfe00-751b-11eb-8fad-7334b11b80bf.png)

Squash can also spin up a new environment for each commit within a PR, and give you a pass or fail if it can receive a success HTTP response. You can also run any existing front-end tests (Selenium, TestCafe, etc) on top of this Squash environment.

![squash-check2](https://user-images.githubusercontent.com/98694/108773348-6ee4fe80-751b-11eb-92e3-d9262192264e.png)

### Squash setup

Let me know if you like the idea of using Squash on this project. If so, we would be happy to create a Pull Request with a Squash YAML file so you don't have to invest any time on this.

**Comment by bep** [comment]
We already have a setup using GitHub actions building and testing Hugo on all of Linux, MacOS and Windows. How is the above better than that?

https://github.com/gohugoio/hugo/actions/workflows/test.yml

**Comment by emiquelito** [comment]
@bep I'm glad you asked ;-) A traditional CI/CD build like the one you have with GitHub actions will run a series of scripts and shut it down after a pass and fail.

Squash is about building your full stack, making sure it's accepting HTTP requests and then allowing you to test it (as an end user) from a unique URL - the environment then [remains active for several hours](https://www.squash.io/auto-shutdown-policies/) giving you enough time to test it, it doesn't spin down after the build is done like a regular CI/CD. Your app's code, specific for a given branch, runs on its own Virtual machine.

With that being said the 2nd part of my comment, where we can configure Squash to run for each commit, would be somewhat similar to your current GitHub actions setup. The main difference is that again, Squash will actually check if your app is responding to HTTP requests before it shuts it down.

Let me know if this makes sense and if you have any other questions.

**Comment by lucperkins** [comment]
@emiquelito Squash seems like a good service overall, but unfortunately I don't think that this project is a good use case for it. Hugo isn't really an "app," it's a static site generator that builds HTML (or other assets) and then quits. So there isn't a long-running process that would need to stay active after the CI/CD runs are finished.

**Comment by bep** [comment]
@lucperkins is right, we do start a web server as part of the test suite, but we close it down as part of the tests. But I do fill a void in the market, though, that Hugo may need in the future. Once an app gets a set of Cypress or similar test cases, it's not obvious how to integrate that with, say, Netlify PR builds.
