### ISSUE TITLE
Not at all spam ... i was away from my desk and the pull request was blocked 

### ISSUE THREAD

**Issue by MjAbuz** [gohugoio/hugo#8284]
### What version of Hugo are you using (`hugo version`)?
https://github.com/gohugoio/hugo/pull/8283#issue-580430955

<pre>
$ hugo version

</pre>

**Comment by MjAbuz** [comment]
I am  not sure ...those are security issues that i saw dependbot was pushing

**Comment by moorereason** [comment]
We do get occasional spam issues/PRs.  I assumed that's what your PR was since it appears to be useless.  Whatever you were doing in your branch doesn't need to be merged here.
