### ISSUE TITLE
.OuputFormats.Get returns main OF's .RelPermalink when baseName includes `/index` 

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#8292]
### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.80.0-792EF0F4/extended darwin/amd64 BuildDate: 2020-12-31T13:44:15Z
</pre>

### Does this issue reproduce with the latest release?
Yes

### Step to reproduce
1. Create output format of mediatype `text/html` with `baseName` as dir like `something/index` or `something/other/index`
```
outputFormats:
  excerpt:
    baseName: excerpt/index
    mediatype: text/html
```
2. Use `(.OutputFormat.Get "excerpt").RelPermalink`

### Result
`.RelPermalink` returns the main output format relative permalink.

### Expected Result
`.RelPermalink` returns the permalink of the `excerpt` output format which has been created at `/book/my-book/excerpt/index.html`

**Comment by jmooring** [comment]
@regisphilibert,

Not sure if this is a bug or a desired enhancement. 

<https://gohugo.io/templates/output-formats#configure-output-formats>

> baseName
> the base **filename** for the list filenames (homepage, etc.). Default: index.

I interpret `filename` to mean a filename without path. Could you do this instead?

```
[outputFormats]
[outputFormats.excerpt]
path = "excerpt"
mediaType = "text/html"
```

With this configuration `(.OutputFormats.Get "excerpt").RelPermalink` returns the expected result.

**Comment by regisphilibert** [comment]
`path` is prepended to the default url:

Your configuration would create the file at `website.com/excerpt/book/index.html` what I need is the default path: `website.com/book/excerpt/index.html`

The emphasized use case was back when `amp` was a thing and you wanted your website almost replicated under an `/amp/` directory.
