### ISSUE TITLE
Support for request logging?

### ISSUE THREAD

**Issue by justinclift** [gohugoio/hugo#8295]
Would it be feasible for Hugo to do basic request logging for the server, to aid users developing their websites?

Maybe something like:

```
DEBUG 2021/03/03 09:54:29 Received request: /foo/bar/index.html
DEBUG 2021/03/03 09:54:29 Received request: /img/img1.png
DEBUG 2021/03/03 09:54:29 Received request: /css/style.css
(etc)
```

Asking because I hit a strange problem where the **rendered** page (according to the log) was giving a 404, when clicking on it's corresponding **rendered** link.  Which AFAIK should never happen. :wink:

With Hugo seeming to not have any option to show the requests it's receiving, it was impossible to narrow down where things were going wrong.  eg "Is the link incorrect?", "Is there JS mucking with things?", etc.

Having looked through the Discourse and seen a few other people ask the same question over the years, they seem to be pointed towards this:

&nbsp; &nbsp; https://discourse.gohugo.io/t/does-should-hugo-server-in-verbose-mode-log-http-requests-and-all-errors/8156/10

Personally, I'm surprised it's not already part of either **--debug** or **--verbose** logging, which seem like the right kind of area for figuring out what's occurring.

It's been a few years since the above Discourse thread though, so I'm wondering if it'd be feasible to add these days?  Hugo has gotten more complicated over the years, and stuff like this helps users learn it + diagnose issues (even if just eliminating things).

**Comment by BA1RY** [comment]
Hi, I would like to work on this. How should I go about implementing this?

**Comment by justinclift** [comment]
@moorereason ^^^ Ping?

**Comment by bep** [comment]
@moorereason I removed the GoodFirstIssue -- a proposal is never a good first issue. We need to decide 1) If we want to do something like this and 2) if yes to 1, what?

**Comment by bep** [comment]
My 50 cents about this:

* Hugo is a static site generator, we mostly care about files written to disk.
* For 404 errors etc. you have pretty good support in browsers
* I have never thought about this as something that I would need when using Hugo
* This is the first issue (as I remember) asking for this

**Comment by justinclift** [comment]
@moorereason No worries. :smile:

@bep There have been several people asking for variations of this, when looking through the GitHub Issues and and Discourse.  At least, to me they seem to be asking for this in one way or another. :smile:

Should I make a list for you to look through/confirm?
