### ISSUE TITLE
Use the new embed package to embed the buit-in Hugo templates

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8297]
https://golang.org/doc/go1.16#library-embed

Would replace this script:

https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/generate/generate.go

**Comment by shimst3r** [comment]
@bep may I take a look at this? I'd really like to give back to the Hugo community and this looks like a doable feature for me. :smile:

**Comment by bep** [comment]
@shimst3r great! Shout if you have any questions.

**Comment by shimst3r** [comment]
@bep great :smile: 

Just to make sure I've got this right: This is going to be a "drop-in" replacement for existing functionality, so my objective would be to make the tests in `hugo/hugolib/embedded_templates_test.go` pass using `pkg/embed`?

**Comment by bep** [comment]
>so my objective would be to make the tests in hugo/hugolib/embedded_templates_test.go pass using pkg/embed?

Yes.

**Comment by shimst3r** [comment]
Thanks a lot for your quick answer. :bow:

**Comment by shimst3r** [comment]
@bep I've opened a merge request. Hopefully I didn't commit too many Go sins at once. :sweat_smile:
