### ISSUE TITLE
Bundle Dart Sass into Hugo installation process

### ISSUE THREAD

**Issue by peaceiris** [gohugoio/hugo#8299]
According to the documentation, Hugo seems to have a plan to bind the Embedded Dart Sass as the same as LibSass (Hugo extended). I expect that the improvement will be done at [bep/godartsass] with [embed package] known as a new feature in Go 1.16.

[bep/godartsass]: https://github.com/bep/godartsass
[embed package]: https://golang.org/doc/go1.16#library-embed

> The transpiler to use, valid values are libsass (default) and dartsass. Note that the Embedded Dart Sass project is still in beta (beta 5 at the time of writing). The release is scheduled for Q1 2021. We will try to improve the installation process by then, but if you want to use Hugo with Dart Sass you need to download a release binary from Embedded Dart Sass (Hugo after 0.81.0 requires beta 6 or newer) and make sure it’s in your PC’s $PATH (or %PATH% on Windows).
>
> https://gohugo.io/hugo-pipes/scss-sass/#options

Is that possible? And, is there any plan to bind the Embedded Dart Sass into Hugo?

## Related Links

- [Binding Embedded Dart Sass into Hugo - feature - HUGO](https://discourse.gohugo.io/t/binding-embedded-dart-sass-into-hugo/31554)
- [sass/dart-sass-embedded](https://github.com/sass/dart-sass-embedded): A wrapper for Dart Sass that implements the compiler side of the Embedded Sass protocol
- [bep/godartsass]: Go API backed by the native Dart Sass Embedded executable.
- [Integrate Dart Sass · Issue #495 · peaceiris/actions-hugo](https://github.com/peaceiris/actions-hugo/issues/495)

**Comment by bep** [comment]
>Is that possible? And, is there any plan to bind the Embedded Dart Sass into Hugo?

We cannot (I'm probably sure about that) embed this into Hugo's binary (the embedded files in Go 1.16 is not executable).

What we may consider (or: we should just do it, but nothing comes for free, it takes time) is to create "installables" (e.g. MSI on Windows) that would package this together and handling the PATH setup etc. We're already building deb packages for Linux and that should be possible to add.

I think it then boils down to this issue:

https://github.com/goreleaser/goreleaser/issues/1295

**Comment by peaceiris** [comment]
I see.

Besides MSI and Linux deb packages, other package management tools (like homebrew) will need to update the installation process to include the Embedded Dart Sass in the future, I think.

**Comment by bep** [comment]
I do suspect that we need to consolidate the installation options at some point. I'm getting dizzy about the current situation. Re. brew we could have our own "brew tap" -- then we could build "everything" as part of the official release.

**Comment by XhmikosR** [comment]
Hello everyone. We recently started hitting a deprecation error in our Sass code and we try to migrate to Dart Sass only. But AFAICT Hugo needs an external binary file dependent on OS, so we can't move forward, because that would make things a lot more complicated.

Just wondering if there's been any progress, thanks!

**Comment by davidsneighbour** [comment]
Is it a deprecation ERROR or WARNING? Node SASS is supported until December 2022 and you should ignore or disable these warnings (if they are warnings) before you panic :) If it's errors then post your SASS code in the discourse and we try to make it compatible.

**Comment by bep** [comment]
>Just wondering if there's been any progress, thanks!

You will, in general, notice it on the issue if there is a progress.

**Comment by XhmikosR** [comment]
It's warnings only, but they are quite noisy so we are looking at ways of moving forward: https://github.com/twbs/bootstrap/issues/34051

**Comment by TenSketch** [comment]
How to install dart sass in hugo? I'm using ubuntu and brew in my system. 
[https://github.com/sass/dart-sass-embedded/tree/1.0.0-beta.9](https://github.com/sass/dart-sass-embedded/tree/1.0.0-beta.9)

**Comment by jmooring** [comment]
@TenSketch Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by robsonsobral** [comment]
Dart SASS reached stable releases at Feb 01, 2022. The current version is [1.50](https://github.com/sass/dart-sass-embedded/releases/tag/1.50.0)

**Comment by bep** [comment]
I have no idea how to _simply and safely and for all platforms_ do this. Suggestions welcome, but please consier the 3 keywords  __simply and safely and for all platforms_.

**Comment by onodera-punpun** [comment]
It seems like dart doesn't even support musl (see: https://github.com/sass/dart-sass-embedded/issues/85), so _for all platforms_ seems to be an impossibility, since big distros like Alpine Linux use musl.

**Comment by bep** [comment]
>big distros like Alpine Linux use musl.

I'm not sure I would call Alpine Linux a "big distro", but I get your point ...

**Comment by robsonsobral** [comment]
Since some days ago, Dart SASS embed has ARM 32bit versions. I'm not sure, but I guess it now covers all platforms of Hugo Extended.

**Comment by onodera-punpun** [comment]
Still no support for various distros that use musl, such as Alpine Linux: https://github.com/sass/dart-sass-embedded/issues/106

**Comment by bep** [comment]
As to _this_ particular issue, I guess what we practically could do is:

* Add Dart Sass to the Linux Debs where it's supported.
* Create a new MacOS .pkg (I have done some foundation work on this elsewhere)

But I need to shift my focus away from this particular area for a little now, but I will return.

**Comment by robsonsobral** [comment]
I hope everything is fine, @bep ! Thank you!

**Comment by bep** [comment]
@robsonsobral sure, by focus shifting I meant  just "away from software packaging" which is fun for a little ...

**Comment by merchako** [comment]
As a data point, Hugo potentially breaks the moment someone uses modern CSS in SCSS, for example

```lang-css
background-color: hsl(var(--my-purple-hsl) / 50%) ;
```

And it's quite difficult for even moderately seasoned developers to remedy, as you can [see in this thread](https://discourse.gohugo.io/t/installing-dart-sass-embedded/32468/13), as the installation and configuration process for [dart-sass-embedded](https://github.com/sass/dart-sass-embedded) isn't clear.

Hugo's error message doesn't help

> Error: Error building site: TOCSS-DART: failed to transform "styles.scss" (text/x-scss). You need dart-sass-embedded in your system $PATH.: this feature is not available in your current Hugo version, see [https://goo.gl/YMrWcn](https://goo.gl/YMrWcn) for more information

This link is a red herring, which strongly suggests that the current version isn't extended, and then installing the extended version will fix the issue.

> you need the Hugo extended version, or else you may see an error message similar to the [above]… We release two set of binaries for technical reasons. The extended version is not what you get by default for some installation methods. 

If it's not a priority to package Hugo with an automatic installation of Embedded Dart Sass, I would encourage those who know how to correct the relevant documentation.

**Comment by jmooring** [comment]
@merchako I've created an issue in the docs repository.

**Comment by bep** [comment]
>If it's not a priority to package Hugo with an automatic installation of Embedded Dart Sass, I would encourage those with the know-how to correct the relevant documentation.

It's a high priority, but I just don't know how to do it.

**Comment by jmooring** [comment]
For Linux users, it is included in the Snap package.

**Comment by robsonsobral** [comment]
While DART doesn't support Alpine, there's nothing that can be done. So...

**Comment by merchako** [comment]
> It's a high priority, but I just don't know how to do it.

@bep, I saw you apparently solve it for this person in the [previously-reference thread](https://discourse.gohugo.io/t/installing-dart-sass-embedded/32468/13). Unfortunately, there wasn't a lot of context about specifics, so it took me almost a day to figure out. Here's the gist of it:

## To make modern SASS work with Hugo
1. Install [Dart Sass Embedded](https://github.com/sass/dart-sass-embedded) as a binary 
    [How to install a binary on each OS](https://zwbetz.com/how-to-add-a-binary-to-your-path-on-macos-linux-windows/)
2. And add the folder that encloses its executable to your path ([how to](https://zwbetz.com/how-to-add-a-binary-to-your-path-on-macos-linux-windows/))
    For example, in `~/.zshrc` on macOS
   ```
    export PATH="${HOME}/bin/sass_embedded:${PATH}"
    ```
3. Restart your terminal and check your path. 
   ```
    echo $PATH
    ```
    The result should have `sass_embedded/` in it, at least. Unfortunately, it's not easy to test that the path is actually working since the folder itself isn't an executable. 
3. Restart `hugo server`

Does that help at all? I assume y'all know a whole lot more than me. Posting that outline would have made a huge difference, especially the specifics and links to the articles about appending the path. As a macOS user, I would absolutely love it if `dart-sass-embedded` could be included in a Homebrew tap like y'all did for Snap.

**Comment by robsonsobral** [comment]
```scss
    &::after {
      float: right;

      color: palette('gray', 'light');

      content: ', ';

      @supports selector(:has(:checked)) {
        content: none;
      }
    }
```

![image](https://user-images.githubusercontent.com/931642/205346536-e18121ac-900b-4aef-bdcd-dc402d7fe304.png)

😭

**Comment by bep** [comment]
@merchako so, I know how to install Dart Sass, but the little bit of a challenge here is to integrate this with the release process in a practical and more or less complete way; I could probably add this to the Linux Deb + create a MacOS pkg installer, but we would then get complaints from the others (Windows users, Brew users).

**Comment by robsonsobral** [comment]
> but we would then get complaints from the others (Windows users, Brew users).

😠 👿 😡

**Comment by jmooring** [comment]
@bep I've created stand alone installers for Snap, Chocolatey, and Scoop. Keeping track of status for these and other package managers here:
<https://github.com/gohugoio/hugoDocs/issues/1921#issuecomment-1328063077>

**Comment by bep** [comment]
@jmooring I really applaud the work you're doing with this. I can note that the RPC model that's used with the Dart Sass integration has renewed my optimism that we could get rid of the "hugo extended" version and finally get a decent plugin system in Hugo. I have done some more field work on this here and other places: https://github.com/bep/execrpc

**Comment by bep** [comment]
If you run `hugo env` in Hugo >= 0.108.0 you will no see if and what version of Dart Sass you have installed:

```bash
~/d/g/g/hugoDocs ❯❯❯ hugo env                                                                                                master
hugo v0.109.0-DEV-cc574ef1200986ab287eca40db59053ccdd205d6+extended darwin/arm64 BuildDate=2022-12-06T13:50:51Z
GOOS="darwin"
GOARCH="arm64"
GOVERSION="go1.19.3"
github.com/sass/libsass="3.6.5"
github.com/webmproject/libwebp="v1.2.4"
github.com/sass/dart-sass-embedded/protocol="1.1.0"
github.com/sass/dart-sass-embedded/compiler="1.56.1"
github.com/sass/dart-sass-embedded/implementation="1.56.1"
```

**Comment by robsonsobral** [comment]
Does [this](https://github.com/sass/embedded-host-node) helps?

**Comment by shyim** [comment]
Did you think about looking first into PATH and when not try to download the right dart-sass-embedded version to the users tmp and use that binary? Of course packaging dart-sass-embedded is the better choice, but so you could release it with an fallback for all those users that won't have installed it.

**Comment by bep** [comment]
>Did you think about looking first into PATH and when not try to download the right dart-sass-embedded version to the users tmp and use that binary? 

Not sure if you're talking to me here, but the _download to tmp and use that binary_ is the hard part here, if you want to do it in a secure way with version control etc.

**Comment by onodera-punpun** [comment]
An update on the musl/alpine-linux situation; dart-sass-embedded is now available in the testing repository.

**Comment by onodera-punpun** [comment]
Testing this out right now, and using dart-sass my sass files compile just fine, however using Hugo and dart-sass-embedded I get the following error:

```
Error: Error building site: TOCSS-DART: failed to transform "sass/main.sass" (text/x-sass): "assets/sass/partials/_typography.sass:0:18": expected "{".
Total in 1542 ms
```

The file looks as follows:

```sass
html, body
	-webkit-font-smoothing: antialiased
	-moz-osx-font-smoothing: grayscale
	color: var(--text-color)
	font-family: 'IM Fell English', serif
	text-rendering: optimizeLegibility

h1
	font-weight: 400
	-webkit-hyphens: manual

	i
		font-size: 90%
		font-style: italic
		text-transform: lowercase
```

**Comment by jmooring** [comment]
@onodera-punpun I am unable to reproduce the problem using the indented Sass you posted.

```text

dart-sass-embedded --version

  "protocolVersion": "1.2.0",
  "compilerVersion": "1.56.2",
  "implementationVersion": "1.56.2",
  "implementationName": "Dart Sass",
  "id": 0
```

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by onodera-punpun** [comment]
Thanks! Posted it on the forum with more steps to reproduce this: https://discourse.gohugo.io/t/dart-sass-embedded-does-not-build-valid-sass-files/43184

**Comment by rickdgray** [comment]
Dart Sass Embedded github is now archived. Looks like they moved the embedded build into the primary Dart Sass repo. The current build of embedded works well currently but who knows how long that'll be.

**Comment by jmooring** [comment]
@rickdgray 

Embedded Dart Sass was deprecated in favor of [Dart Sass](https://github.com/sass/dart-sass). Hugo [v0.114.0](https://github.com/gohugoio/hugo/releases/tag/v0.114.0) and later are compatible with both Dart Sass (v1.63.4 and later) and Embedded Dart Sass (v1.62.1 and earlier). 

To install Dart Sass:

OS|Package manager|Site|Installation
:--|:--|:--|:--
Linux|Homebrew|[brew.sh](https://brew.sh/)|`brew install sass/sass/sass`
Linux|Snap|[snapcraft.io](https://snapcraft.io/dart-sass)|`sudo snap install dart-sass`
macOS|Homebrew|[brew.sh](https://brew.sh/)|`brew install sass/sass/sass`
Windows|Chocolatey|[chocolatey.org](https://community.chocolatey.org/packages/dart-sass-embedded)|`choco install sass`
Windows|Scoop|[scoop.sh](https://scoop.sh/#/apps?q=sass)|`scoop install sass`

You may also install [prebuilt binaries](https://github.com/sass/dart-sass/releases/latest) for Linux, macOS, and Windows.

**Comment by jmooring** [comment]
At this point I'm not sure it's worth spending any time on this. 

In my view, Hugo has three primary[^1] external dependencies: Git, Go, and Dart Sass. You can [make the case that these are optional](https://gohugo.io/installation/macos/#prerequisites), but I'd estimate that (a) Git is required 99% of the time, (b) Go is _currently_ required 30% of the time, and (c) Dart Sass is _currently_ required 5% of the time. The Go and Dart Sass percentages will, obviously, increase over time.

We don't bundle Git or Go, so why should we bundle Dart Sass?

- Dart Sass [installation is fast and easy](https://gohugo.io/hugo-pipes/transpile-sass-to-css/#installing-in-a-development-environment) on macOS, Linux, and Windows.
- Some percentage of developers will already have Dart Sass installed, and I suspect a high percentage of those will be at 1.63.5 or later within a few weeks/months.

I think any effort in this area should focus on package managers that provide Hugo installers: Homebrew, Chocolatey, and Scoop. Each of these package managers have Dart Sass installers as well, so adding Dart Sass as a package dependency is, for the most part, trivial.

The Hugo Snap package for Linux already bundles all of the primary and secondary dependencies, including Dart Sass.

[^1]: The secondary external dependencies are Node.js, Asciidoctor, Pandoc, and rst2html. We don't bundle these either.

**Comment by jmooring** [comment]
No longer actionable.
