### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by highOnBytes** [gohugoio/hugo#8300]
Hi,

My name is Damien Mather, I am a software dev (now turned website owner) from Melbourne (Aus). I run a website called SecurityGladiators.com. It is a blog about internet security, online privacy, streaming etc.

I think your project is great, and I am planning a write-up of your project on my site, our users will really find it usefull.

I am interested in donating to the project on a monthly/yearly basis.

What sort of sponsorship/donor packages do you offer?

Regards

Damien.

**Comment by davidsneighbour** [comment]
![Selection_122](https://user-images.githubusercontent.com/83281/110075028-bd648980-7db4-11eb-92d9-91a1ba71aaea.png)

:)

**Comment by bep** [comment]
@highOnBytes he's right. That is currently the option we have for individual sponsors.

**Comment by highOnBytes** [comment]
Hi @bep 

I see you're from Norway, my wife is Danish (we only just moved back to Australia from Copenhagen in 2019) and we have lots of family up there in Oslo and Alesund. We go there often, a great place just very expensive beer!

If I become a sponsor, can I also get listed on the home page (https://gohugo.io/)  like Brave, Linode and eSOLIA?

I won't need any time for help each month for projects.

Regards

Damien
