### ISSUE TITLE
FirstSection returns wrong value for taxonomy nodes

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8307]
Working on something else, I have a failing test that looks like it should not. `mycategory.FirstSection` shold return the `categories` branch, now it returns the home page.

**Comment by importhuman** [comment]
I'd like to take this up, but I'm not sure if I'm looking in the right place. Couldn't find anything with `mycategory`, is this the `FirstSection` function in `page__tree.go`, or the `getFirstSection` function in `content_map.go`?
