### ISSUE TITLE
Idea: Autosize for twitter card image

### ISSUE THREAD

**Issue by uPagge** [gohugoio/hugo#8315]
If your feature-image is larger than 4096x4096 pixels, then twitter will not display your image. It would be great if the picture was compressed automatically for this `{{- template "_internal / twitter_cards.html". -}}`

So far, unfortunately, I had to write a manual twitter card generator

**Comment by bep** [comment]
I do agree that we could possibly do something about this, but if you dump your images directly from your 45.7 megapixels Nikon D850 camera, I would say that would be an error situation that should be fixed by the user and not Hugo. Maybe we should fail the build?

**Comment by uPagge** [comment]
Well, I can say that it was not a photograph, but an illustration from the Internet. I agree that this may be a user problem, but it is definitely not worth falling on the assembly. After all, the user may really want to insert images with such quality in the preview of his article, and thus we will forbid him to do so.

It might be worth warning the user with a WARN. But in my opinion, the best solution would be to automatically create a version of the picture for twitter and substitute it.
