### ISSUE TITLE
Malformed character constant when using a mix of single/double quotes with double curly Hugo syntax inside templates

### ISSUE THREAD

**Issue by PaulPineda** [gohugoio/hugo#8322]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.81.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Version above is currently the latest

### Summary of the problem
Using the following in the a template file (in my case a `list.html` or `single.html` in `./layouts/_default/` result in the above error (see bottom of issue for full content of template file:
```html
<time datetime="{{ .Date.Format '2006-01-02T15:04:05Z07:00' }}">
    {{ .Date.Format "Mon, 02 Jan 2006 00:00" }}
</time>
```

### Expected behaviour
The template is parse without errors

### Actual behaviour 
The following error is rendered in place of the site content in the browser
```
Rebuild failed:

Process: loading templates: "{ROOT_OF_HUGO_PROJECT}/layouts/_default/single.html:4:1":parse failed: template: _default/single.html:5: malformed character constant: '2006-01-02T15:04:05Z07:00'
```
### Workarounds
Error free template parsing is achieved by:
* swapping the single quote with double quotes

```html
<time datetime='{{ .Date.Format "2006-01-02T15:04:05Z07:00" }}'>
    {{ .Date.Format "Mon, 02 Jan 2006 00:00" }}
</time>
```

* using backticks (`) instead of the single quote
```html
<time datetime="{{ .Date.Format `2006-01-02T15:04:05Z07:00` }}">
    {{ .Date.Format "Mon, 02 Jan 2006 00:00" }}
</time>
```

### Technical notes:
The full content of the `single.html` template file was:
```html
<article>
  <h1>{{ .Title }}</h1>
  <h3>
    by {{ .Params.author }} on
    <time datetime="{{ .Date.Format '2006-01-02T15:04:05Z07:00' }}">
      {{ .Date.Format "Mon, 02 Jan 2006 00:00" }}
    </time>
  </h3>
  <p>{{ .Content }}</p>
</article>

```

**Comment by jmooring** [comment]
This is the expected behavior. In golang:
- Single quotes are used to enclose [rune literals](https://golang.org/ref/spec#Rune_literals)
- Double quotes are used to enclose [interpreted string literals](https://golang.org/ref/spec#String_literals)
- Back quotes (a.k.a. backticks) are used to enclose [raw string literals](https://golang.org/ref/spec#String_literals)

Please close this issue. Thanks.

**Comment by PaulPineda** [comment]
@jmooring Thanks for the quick response. Might it not be useful to amend the docs such that the backticks syntax is used in such cases (if at least to ease the use cases for those that do not have a golang background)?

Happy to raise a PR to do so but would need guidance on the best place in the docs to locate this amendment

**Comment by jmooring** [comment]
This page:
<https://gohugo.io/templates/introduction/>

encourages the reader to visit this page:
<https://golang.org/pkg/text/template/>

which has these examples:
<https://golang.org/pkg/text/template/#hdr-Examples>

PR's should be raised here:
<https://github.com/gohugoio/hugoDocs>

**Comment by PaulPineda** [comment]
@jmooring started off by amending the docs example that lead me to this error :) https://github.com/gohugoio/hugoDocs/pull/1357
