### ISSUE TITLE
[Hope] Add syntax highlighting for NSIS (.nsi, .nsh)

### ISSUE THREAD

**Issue by CarsonSlovoka** [gohugoio/hugo#8326]
I can't find the "highlight" about NSIS([Nullsoft Scriptable Install System](https://nsis.sourceforge.io/Main_Page)) on the [syntax-highlighting](https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages) page. 

It would be great if you could add ("nsi", "nsh") to the highlight. Thanks!

----

👉[link](https://nsis.sourceforge.io/Category:Syntax_Highlighting) about *Contains NSIS syntax files for different text editors, browsers, and websites.*

**Comment by moorereason** [comment]
We use [chroma](https://github.com/alecthomas/chroma) for syntax highlighting.  You'll want to make your request there.

**Comment by CarsonSlovoka** [comment]
@moorereason, thank you for reminding me. I have put this issue to chroma ([chroma-issues-459](https://github.com/alecthomas/chroma/issues/459)).
