### ISSUE TITLE
Create toc

### ISSUE THREAD

**Issue by uPagge** [gohugoio/hugo#8330]
If I use title in shortcode like this

![изображение](https://user-images.githubusercontent.com/40397740/111071730-9874c280-84e8-11eb-9474-5f23a22df965.png)

Then the title does not get into the toc. Is this a bug or can it be fixed somehow by configuration?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
