### ISSUE TITLE
extension for SUB and SUP

### ISSUE THREAD

**Issue by gj52** [gohugoio/hugo#8334]
nice extension from https://github.com/OWS/commonmark-sup-sub-extensions

welcome to implement in Hugo?? Would be a nice addon.

**Code:**
10^2^
10~2~
**Result:**
10<sup>2</sup>
10<sub>2</sub>

**Comment by gj52** [comment]
the sub is with "\~" - don't work, select another char...

**Comment by moorereason** [comment]
This would first need to be implemented separately as a [goldmark](https://github.com/yuin/goldmark) extension.
