### ISSUE TITLE
Allow configDir on config.yaml

### ISSUE THREAD

**Issue by robsonsobral** [gohugoio/hugo#8337]
Hi!

I know that this "inception" thing looks crazy, but let me try to explain.

I'm developing a theme and some sites using it. Sometimes I need to run `hugo server --configDir exampleSite/config`, before to start to develop, and sometimes I need to run `hugo server`.  So I added  `hugo server --configDir exampleSite/config` to `package.json`. The mess increases as my co-workers sometimes forget that, among a lot of Hugo projects, only this one needs to be run using NPM scripts, specially if this is their first contact with Hugo.

If I could add `configDir: exampleSite/config` as the single configuration at config.yaml in project root, all projects could be run and build by the same way: `hugo server`.

Is that too weird?

Thank you all.

**Comment by terkelg** [comment]
I'm having that issue too. I have a project structure where the entire hugo site is inside a `src` directory.
I would like to be able to run `hugo` from the project root without having to specify `-s src` for all internal and external tools. My current solution is to use symlinks. Would be nice if you could define the `-s` flag in a config in the root or point to another config.

**Comment by bep** [comment]
So you suggest that we should read the config before we can read the config?

**Comment by robsonsobral** [comment]
No, the other way around. I'm suggesting we should read the config **after** we have read the config.

The same way environment configs override the default ones, the process of reading a new config `configDir` should override the previously read ones.

We can say I'm suggesting a recursion.

Thank you, @bep .

**Comment by robsonsobral** [comment]
Yeah, it's still relevant to read both.
