### ISSUE TITLE
Markdown Render Hooks | strong, em, q

### ISSUE THREAD

**Issue by uPagge** [gohugoio/hugo#8348]
I don't know, maybe this is in the plans, but it would be nice to be able to override the behavior of other elements from markdown, according to the principle of image, link and heading.

This would provide more flexibility. For example ** this in markdown wraps the text in strong, I would like to override this behavior, as I think it is not entirely correct.

That is, such overrides will allow you to use markdown markup in your own way, while not breaking the semantics of html5.

I hope I was able to convey my point and the translator did not distort anything: D

**Comment by davidsneighbour** [comment]
What you want is another markdown language. Double asterisk is the mark for strong/bold in Commonmark, which is used in Goldmark, which is the default markdown parser. Changing the meaning of markdown is not what renderhooks are for, they are to add information or structure to tags.

https://commonmark.org/help/

To change whatever you want to change you should retrieve the un-processed markdown content, do a regexp and replace the characters you want to interpret different and then send the rest trough markdownify.
