### ISSUE TITLE
Add rpm packages to github releases

### ISSUE THREAD

**Issue by FarisZR** [gohugoio/hugo#8350]
hi

i have noticed that their is no rpm in github releases
this would be very helpful for rpm-based distro users like fedora and opensuse

**Comment by jmooring** [comment]
Tested today with fresh installation of Fedora 33. Three methods of installation.

#### Package Manager

```
$ sudo dnf install hugo -y
$ hugo version

Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: unknown

```

#### Snap


```
$ sudo dnf install snapd -y
$ sudo ln -s /var/lib/snapd/snap /snap
$ sudo reboot
$ sudo snap install hugo --channel=extended/stable
$ /snap/bin/hugo version

WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2020-12-31T20:02:59Z

```

### RPM

1. Visit <https://src.fedoraproject.org/rpms/hugo>
2. Select a version of Hugo corresponding to your version of Fedora
3. Download the file for your architecture (e.g., hugo-0.80.0-1.fc33.x86_64.rpm)

```
$ sudo yum localinstall hugo-0.80.0-1.fc33.x86_64.rpm -y
$ hugo version

Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: unknown
```

**Comment by fareszr** [comment]
Correct their are ways to get rpm packages but they are not the latest version and not directly from Hugo, and the only way to get hugo-extended is to use the tar archive.


It would be nice to have rpm packages directly from Hugo

**Comment by jmooring** [comment]
I understand, but to be clear, all of the the methods described in my last comment install the _extended_ version.

**Comment by fareszr** [comment]
> I understand, but to be clear, all of the the methods described in my last comment install the _extended_ version.

not the latest one,

**Comment by aplatypus** [comment]
Do people realise that snap pachaging don't work on Linux unless the home directory is on the same disk as the root directory?  

Personally, I'm not putting my home on the root drive.  No, the soft mount workaround doesn't work.

AT LEAST can we have a flatpak packagin solution that will work everywhere (as far as I know for now)?

And its open source too (as @fareszr reminds us).
