### ISSUE TITLE
When running hugo server, http is not prepended to localhost making a broken URL

### ISSUE THREAD

**Issue by DarrienG** [gohugoio/hugo#8356]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.82.0+extended darwin/amd64 BuildDate=unknown
</pre>

If you run, it will show a bunch of output:

```
hugo server -D
Start building sites …

                   | EN
-------------------+-----
  Pages            | 14
  Paginator pages  |  2
  Non-page files   |  1
  Static files     | 18
  Processed images |  0
  Aliases          |  4
  Sitemaps         |  1
  Cleaned          |  0

Built in 42 ms
Watching for changes in /Users/dglasser/developer/webdev/blog/{archetypes,content,static,themes}
Watching for config changes in /Users/dglasser/developer/webdev/blog/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
```

But note the: `Web Server is available at //localhost:1313/ (bind address 127.0.0.1)` which should have http://localhost:1313, otherwise it is pointing to a weird file path.

### Does this issue reproduce with the latest release?
This is the latest release. I have not tested with master.

**Comment by jmooring** [comment]
The baseURL in config.toml should be something like `http://example.org/`, not `/`. In the future please ask questions at https://discourse.gohugo.io/. We prefer to use GitHub to track bugs and enhancements.

**Comment by DarrienG** [comment]
It still seems like a bug that unless you prepend `http(s)://` to your baseURL it does not properly show http://localhost in output. base urls are generally not bound by their transfer type (http, https, tcp, ws, etc.) and that removing it removes the transfer type at the beginning.

IIRC the hugo server only serves over http, so it should _always_ prepend http to the baseURL. I don't think it's ever right to leave the transfer type out, or replace it with a different one.
