### ISSUE TITLE
TOC and shortcode

### ISSUE THREAD

**Issue by uPagge** [gohugoio/hugo#8358]
I noticed an unpleasant feature related to shortcode and TOC

If the chapter ends up in shortcode, like this:

```
{{< short >}}
## Test
{{</ short>}}
```

Then the header is missing in the TOC. This gives me a lot of hassle, had to use 2 shortcodes to get around this. But this is very inconvenient to maintain.

```
{{< short >}}
## Test
{{< short-end >}}
```

**Comment by davidsneighbour** [comment]
It is very hidden in the documentation (so that I didn't find it) but to have your headers from shortcode in the TOC you need to load the shortcodes via `{{% shortcode %}}`.

**Comment by jmooring** [comment]
<https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown>

> Shortcodes using the % as the outer-most delimiter will now be fully rendered when sent to the content renderer (e.g. Blackfriday for Markdown), meaning they can be part of the generated table of contents, footnotes, etc.

**Comment by uPagge** [comment]
@davidsneighbour Unfortunately it didn't work for me. Perhaps there is something else to be done?

![изображение](https://user-images.githubusercontent.com/40397740/112349742-0a63bd80-8cda-11eb-8e87-089ca0ff6612.png)

![изображение](https://user-images.githubusercontent.com/40397740/112349904-2ebf9a00-8cda-11eb-9fac-46d71ed2a047.png)

![изображение](https://user-images.githubusercontent.com/40397740/112349944-38e19880-8cda-11eb-9b2d-3c26621e7e30.png)

![изображение](https://user-images.githubusercontent.com/40397740/112350754-747c6280-8cda-11eb-9e04-e450daf28eaf.png)

**Comment by jmooring** [comment]
From my previous comment:

> Shortcodes using the % as the outer-most delimiter will now be fully rendered

Your shortcode template need only contain `{{ .Inner }}`. 

Please do not use GitHub to ask questions; that's what the forum is for:
<https://discourse.gohugo.io/>
