### ISSUE TITLE
Transfer paragraph attributes to image when used as a block

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8362]
See discussion in https://discourse.gohugo.io/t/is-it-possible-to-use-attribute-lists-with-render-hooks/31374/6?u=bep

So, images are by definition an inline element, but it most typically is used in block contexts, e.g.:

```md
This is some text.

![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")
{ .myclass }

And then some more text.

```

I have not tested the above, but I suspect that the attributes list `{ .myclass }` will be applied to the surround paragraph block.

Since the parsing complexity prevents us from adding attributes to links/images, an option may be to transfer the surrounding block's attributes to the image.

We can certainly have an option to toggle this off, but I suspect that most people would say that the attribute above belongs to the image and not the paragraph.

Thoughts?

**Comment by HenrySkup** [comment]
For images that are treated as blocks this make sense.

but it does raise the question of what the config option should be... such as:
- "treat images as blocks"
- "treat "orphan" images as blocks"
- "treat images with attributes as blocks"

Just a thought:
Would it be possible to do something similar to how footnotes are treated for inline elements (<img> and <a>)?  would that help with the parsing complexity?

**Comment by bep** [comment]
@HenrySkup thanks for your input.

1) As to the config option, I think it should be very specific. We're not "treating images as blocks" -- they're still an inline element that happens to be surrounded by a block (paragraph). So, something ala `moveParagraphAttributesToImageBlocks` or ... something.

2) I don't understand the footnote reference, but when working with Goldmark, it's much easier to reason with its AST (instead of the actual markdown text) and say stuff ala "if an image is the only child of a paragraph, then ...".

**Comment by HenrySkup** [comment]
> 2\. I don't understand the footnote reference, but when working with Goldmark, it's much easier to reason with its AST (instead of the actual markdown text) and say stuff ala "if an image is the only child of a paragraph, then ...".

I was thinking about something like:

```
This would be some normal text. ![alt](url "title){^1} Bla bla bla.


{^1}: attribute list
```

but I now realize that this would prob be just as difficult and quite a departure from markdown syntax.

However on the forum @jmooring made [an excellent comment](https://discourse.gohugo.io/t/is-it-possible-to-use-attribute-lists-with-render-hooks/31374/9).  An i realized that I too had hacked together a render hook for this... though haven't been using it...

[Gist here.](https://gist.github.com/HenrySkup/fa8abe26ac387f139f04f256cf28629e)

If I remember correctly, there were some issues creating a properly formatted HTML string.

**Comment by HenrySkup** [comment]
> 2\. I don't understand the footnote reference, but when working with Goldmark, it's much easier to reason with its AST (instead of the actual markdown text) and say stuff ala "if an image is the only child of a paragraph, then ...".

Just found [this in the common mark spec](https://spec.commonmark.org/0.27/#example-545), which is *kind of* what I meant... i think.
