### ISSUE TITLE
Page resources do not work in multilingual mode

### ISSUE THREAD

**Issue by ansmirnov** [gohugoio/hugo#8366]
I created the following page structure: https://github.com/ansmirnov/hugo-multilang-example/tree/master/site/content/hi

The hello page has two languages: main Russian and additional English. The hello directory contains images referenced by both versions of the page.

After rendering, the Russian version of the page works, but the English page contains a broken link. The content of the hello directory is not accessible from the additional language page.

The problem can be solved by using file names like image.en.png for resources. However, this method leads to unnecessary duplication if the resources are the same in the Russian and English versions of the page (eg, photos).

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

hugo v0.82.0+extended
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
See <https://gohugo.io/content-management/page-resources>

> Page resources are available for page bundles only, i.e. a directory with either a index.md, or _index.md file at its root. 

Restructure your content into page bundles.

```
content
└── hi
    ├── hello
    │   ├── image.png
    │   ├── index.en.md
    │   └── index.md
    └── hello2
        ├── index.en.md
        └── index.md
```

In the future please use the [forum](https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and enhancements. Thanks.
