### ISSUE TITLE
--navigateToChanged redirect to wrong output if multiple exists

### ISSUE THREAD

**Issue by lord-re** [gohugoio/hugo#8367]
I've configured hugo to output gemini files. It works perfectly.
But when using **hugo server --navigateToChanged** you edit one of your content file and save it, your browser will get redirected to the gemini output instead of the html output.

I tried ordering the output array but it doesn't change the behavior.
I tried many hugo version but still got the exact same behavior.

Is there a way to change this behavior ? **When you browse an html output, you should only be live-redirected to an html output**.

**Comment by jmooring** [comment]
I am unable to reproduce this behavior. Please post your question to the [forum](https://discourse.gohugo.io/), with a link to a repository that demonstrates the problem. We prefer to use GitHub for verified bugs and enhancements. Thanks.
