### ISSUE TITLE
Heavy memory cost for replaceRE with group

### ISSUE THREAD

**Issue by wzdlc1996** [gohugoio/hugo#8374]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.81.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

### Example Code

I found this issue during building the site within this partial code

```
{{ $rddcont := .Content }}
{{ $rddcont = $rddcont | replaceRE "([^\\$])([$][^\\$]+?[$])([^\\$])" "$1, $2, $3" }}
```
When replaceRE tries to join the matched groups with non-whitespace characters, my 16G memory gets out of range. By replace the new string as "$1 $2 $3" this issue disappears. I am not sure if this issue exists on other platform because I use hugo on majaro linux.

**Comment by moorereason** [comment]
> By replace the new string as "$1 $2 $3" this issue disappears.

Interesting.  What if you replace with `$1_ $2_ $3`?

**Comment by wzdlc1996** [comment]
> > By replace the new string as "$1 $2 $3" this issue disappears.
> 
> Interesting. What if you replace with `$1_ $2_ $3`?

This issue appears again

**Comment by moorereason** [comment]
> When replaceRE tries to join the matched groups with non-whitespace characters,

I don't think it has to do with non-whitespace characters.  I think has more to do with the number of characters added in the replacement.  I would expect it to also fail with 2 spaces on each side of `$2` (as in `$1  $2  $3`).  I think adding those extra characters is ballooning the memory usage to a point that you run out of memory.

Hugo is very memory hunger, but I'm wondering if there's something else going on here.  What kind of content are you processing?  Is your site source available?

If you care to play around with the underlying Go code, here's [a Go playground](https://play.golang.org/p/dcPkDpN9s5I) that replicates [how `replaceRE` works in Hugo](https://github.com/gohugoio/hugo/blob/v0.82.0/tpl/strings/regexp.go#L51-L88).

**Comment by wzdlc1996** [comment]
>What kind of content are you processing? Is your site source available?

Yes, the repository is at [wzdlc1996/AllinOne](https://github.com/wzdlc1996/AllinOne), the involved template is at [layout/partial/escapeMathjaxEscape/html](https://github.com/wzdlc1996/AllinOne/blob/master/layouts/partials/escapeMathjaxEq.html). I try to use this code to automatically handle the math experiment in mathjax with `\` in it such that I can write it in normal latex manner instead of use `\\`.

> I would expect it to also fail with 2 spaces on each side of $2 (as in $1 $2 $3). 
If you mean with `$1  $2  $3`, it does not cause memory issue. The replace format of `$1_$2_$3`, `$1\n$2\n$\3`, `$1\t$2\t$3`, and `$1$2$3` can all cause this issue, so I think it is related to the type of joining character, only multiple `space` is ok.
