### ISSUE TITLE
Add actually cached percentage column to --templateMetrics

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#8375]
This is about [this topic in discourse](https://discourse.gohugo.io/t/what-does-hugo-know-when-doing-template-metrics/32018).

I am proposing to add a column to the CLI parameter --templateMetrics in addition to "cache potential" that shows how many of the calls to that partial were actually cached. In a properly set up template structure this would lead to an easy 100/100 for partials that are actually cached and one does not need to go through all templates and see, if those "potentially cached" partials are already cached.

**Comment by moorereason** [comment]
I've submitted a PR to address this issue. PTAL

**Comment by davidsneighbour** [comment]
While you are touching this whole calculation: I just had a very arbitrary weird `cachable` column that I can't reproduce or explain:

```
          0   47.981692ms   23.990846ms   26.010678ms      2  newsletter/single.html
  -51240955760304224   45.815675ms     254.531µs    5.470965ms    180  partials/func/hook.html
        100   42.964632ms    2.864308ms   20.827679ms     15  partials/sidebar.html
```

for some reason there is a large negative number instead of a 0 to 100 for the hook.html file. That is a partial that I use to call, well, hooks per installation. An easy way to add stuff to themes (like analytics code in the footer or some ads between posts). 

Use https://github.com/dnb-hugo/hugonewsletter.com if you want to replay the issue, but I am not 100% sure I have all updates to the modules up. The partial in question is in https://github.com/dnb-hugo/hooks and I did not change things there today and don't remember seeing that weird number before today.
