### ISSUE TITLE
An error was reported while building the service

### ISSUE THREAD

**Issue by tiantian-chen** [gohugoio/hugo#8378]
Am getting the errors:
ERROR 2021/03/31 15:11:48 Alias "\en\tags\populusl.\page\1\index.html" contains component with a trailing space or period, problematic on Windows
ERROR 2021/03/31 15:11:48 Alias "\en\tags\vitis-vinifera-l.\page\1\index.html" contains component with a trailing space or period, problematic on Windows
ERROR 2021/03/31 15:11:48 cannot create "\en\tags\vitis-vinifera-l.\page\1\index.html": Windows filename restriction
Total in 117 ms
Error: Error building site: failed to render pages: cannot create "\en\tags\populusl.\page\1\index.html": Windows filename restriction

When using hugo with  local server build.

### What version of Hugo are you using (`hugo version`)?
0.32.4
<pre>
$ hugo version
0.32.4
</pre>

### Does this issue reproduce with the latest release?
yes
0

**Comment by bep** [comment]
1) If this issue still persists in a new Hugo version, why do you still run a very old version?
2) I'm not sure what the current behaviour is (ref. question 1), but why do you end your tags with a period?

**Comment by tiantian-chen** [comment]
Sorry, I've found the solution now.thank you

**Comment by cybarspace** [comment]
@tiantian-chen What was the solution?

<details>

<summary>
I'm having a similar problem.
I ran <code>hugo</code> this morning and got these errors:
</summary>

```
Start building sites … 
ERROR 2021/04/03 10:01:12 render of "taxonomy" failed: "/home/sage/ZENITH/NextCloud/Personal/System/Work/SOFT/github-projects/cybarspace.github.io/layouts/_default/baseof.html:45:97": execute of template failed: template: _default/list.html:45:97: executing "_default/list.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type
ERROR 2021/04/03 10:01:12 render of "section" failed: "/home/sage/ZENITH/NextCloud/Personal/System/Work/SOFT/github-projects/cybarspace.github.io/layouts/_default/baseof.html:45:97": execute of template failed: template: _default/list.html:45:97: executing "_default/list.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type
ERROR 2021/04/03 10:01:12 render of "taxonomy" failed: "/home/sage/ZENITH/NextCloud/Personal/System/Work/SOFT/github-projects/cybarspace.github.io/layouts/_default/baseof.html:45:97": execute of template failed: template: _default/list.html:45:97: executing "_default/list.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type
ERROR 2021/04/03 10:01:12 render of "term" failed: "/home/sage/ZENITH/NextCloud/Personal/System/Work/SOFT/github-projects/cybarspace.github.io/layouts/_default/baseof.html:45:97": execute of template failed: template: taxonomy/tag.html:45:97: executing "taxonomy/tag.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type
Total in 69 ms
Error: Error building site: failed to render pages: render of "home" failed: "/home/sage/ZENITH/NextCloud/Personal/System/Work/SOFT/github-projects/cybarspace.github.io/layouts/_default/baseof.html:45:97": execute of template failed: template: index.html:45:97: executing "index.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type
```

</details>

I'm on `hugo v0.82.0+extended linux/amd64` on Manjaro Linux.

**Comment by tiantian-chen** [comment]
> @tiantian-chen What was the solution?
> 
> I'm having a similar problem. Oddly, this didn't happen before, I just noticed it today.
> 
> I ran `hugo` and got these errors (click to expand):
> I'm on `hugo v0.82.0+extended linux/amd64` on Manjaro Linux.
I found that the name of the filename contains Spaces. Substituting the Spaces for underscores is the solution.

**Comment by cybarspace** [comment]
I see. Thanks for the info. My problem was a bit different. Hugo 0.82 changed `MediaType.Suffix` to `MediaType.FirstSuffix.Suffix`, but the theme I use hasn't been updated for it yet. I changed it and now it works fine.
