### ISSUE TITLE
Fix data generated for documentation

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#8379]
The second column of this table is incorrect:
<https://gohugo.io/templates/output-formats#output-format-definitions>

![a](https://user-images.githubusercontent.com/335669/113221381-c3297f80-9239-11eb-9117-0581c857491d.png)

This is a recent change.

**Comment by davidsneighbour** [comment]
I don't think it's incorrect. It's just not nicely displayed. The last (or pre-last) release brought more details in `mediaType` values.

**Comment by davidsneighbour** [comment]
It should probably parsed to something like `{{ $item.firstSuffix.mainType}}/{{ $item.firstSuffix.subType }}`

**Comment by jmooring** [comment]
Well, it is incorrect from the standpoint of the shortcode on the docs site. This change needs to happen on the data generation side, not the data consumption side.
