### ISSUE TITLE
Integration of hugo server with 3rd party apps via REST

### ISSUE THREAD

**Issue by moshemarciano** [gohugoio/hugo#8382]
I was on a search for a tool that will enable me to produce HTML content that incorporates live data and data based 'flow decisions' in the final HTML. 

It then striked me that HUGO can probably be the best tool for the job with its extensive processing and formatting options, themes and the built-in HTTP server. 

I realize HUGO main goal is to be a static generator, however the existence of a web server opens the door to additional usage use cases such as acting also as a live and advanced templating engine or micro service for other apps who need to create HTML pages on-the-fly as part of their flow.   

Upon further research, as far as I can tell, I saw that there is currently two ways to handle data:

* static files in the /data folder, I can write new files and up-to-date data, but I couldn't find any way to tell the layout template to access file X as there is no way to pass a parameter to the rendering flow
* getJSON could do the trick but I would have to invoke HUGO from the app and then ask HUGO to getJSON from the app, a bit of an awkward flow. On top of that it seems getJSON will need a hard coded URL, so again no way to identify which data I need dynamically.

It looks to me that enabling such a feat, at least at one implementation idea, would not require much more than just allowing to POST to the the built-in web server with a data payload which could then be consumed inside the template as if it was obtained via getJSON or any one of the existing data formats/MIME types. The rest of the behaviour should be exactly the same.

another (optional) idea is to support GET query params and give the template access to them, that would also open more usage possibilities for integration with scripts, apps and automation tools.

**Comment by jmooring** [comment]
See <https://gohugo.io/functions/getenv/>.

Use one or more environment variables to pass URLs, file paths, etc. You can even pass complex data structures (e.g., JSON, TOML).

```bash
MY_JSON_URL="http://country.io/continent.json" hugo
```

template

```text
{{ $data := getJSON (getenv "MY_JSON_URL") }}
{{ range $k, $v := $data }}
  {{ printf "%s = %s" $k $v }}<br>
{{ end }}
```

In the future please use the [forum](https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and enhancements.

**Comment by moshemarciano** [comment]
Hi @jmooring thanks for responding. 

I understand the env option but that is only viable as long as you plan on a very naive integration. 

What if my app is multithreaded and needs to invoke Hugo to generate HTML from several threads? Which environment variable should I use in the template in such case? Not sure it can scale with the load requirements. 

Still think this is a needed enhancement and willing to try and create a PR for it if that's OK. Let me me know. 

I took note of the forum guideline. Thanks

**Comment by jmooring** [comment]
@moshemarciano I wouldn't spend any time on a PR without an indication from the project maintainer (@bep) that it has any chance of being accepted. The built-in HTTP server is limited and exists solely to assist during site development.
