### ISSUE TITLE
Code blocks not rendered well in post summaries

### ISSUE THREAD

**Issue by cgay** [gohugoio/hugo#8384]
### What version of Hugo are you using (`hugo version`)?

```
$ hugo version
hugo v0.82.0-9D960784 linux/amd64 BuildDate=2021-03-21T17:28:04Z VendorInfo=gohugoio
```

### Does this issue reproduce with the latest release?

Yes, this is the latest release, downloaded yesterday.

### The Problem

Hi, I just started using Hugo yesterday. Looks great so far, but one problem I ran into right away is that when code blocks appear near the beginning of a post they are included in the summaries on the front page under Recent Posts, but they're not rendered as code blocks. This obviously doesn't look great. See the attached image. The source for that post is [here](https://github.com/cgay/cgay.github.io/blob/a7e45a3b72636c0270716a0e16b4c11c0164fb45/content/posts/first-post.md).

I'm sure I can find a work-around, such as adding more content before the code block or if there's a configuration option to change how much shows up in the summaries, or just leave it the way it is, but I wanted to let you know about it.

<img width="971" alt="index html-with-code-snippet" src="https://user-images.githubusercontent.com/491829/113430038-78c61100-93a7-11eb-83a9-14bc5dd5eb7a.png">

Thanks!

**Comment by nicky-chen** [comment]
the same with you

**Comment by nicky-chen** [comment]
like this ![image](https://nicky-chin.cn/api/v1/picture/github_fd92e302753d93cb5aa80f525c671fea99e478f2/c1kkucild7tcu96qgu40)

**Comment by davidsneighbour** [comment]
Please close this bug report and open a post on https://discourse.gohugo.io. You started yesterday with Hugo and this is not a bug, but a misunderstanding about how these things work. A quick fix is to add a `description="whatever the postpreview should read"` to the frontmatter of that post. A better fix is to check the layout file that creates this preview and evaluate if HTML tags are stripped, Markdown is parsed or whatever happens there. 

All that are support questions and when you opened this issue you should have seen a link to the support forum and the reminder to please ask support questions in the forum.

**Comment by cgay** [comment]
ok, thanks. Yes, I missed the very clear note to use Discourse. Sorry.
