### ISSUE TITLE
deploy: Log NotFound on delete as warnings, but continue

### ISSUE THREAD

**Issue by ctindel** [gohugoio/hugo#8388]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.0-DEV+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

<pre>
$ hugo deploy
Deploying to target "aws" (s3://mybucket?region=us-east-2)
Identified 0 file(s) to upload, totaling 0 B, and 1 file(s) to delete.
Encountered 1 errors.
Error: blob (key "/sib_rss.xml") (code=NotFound): NotFound: Not Found
	status code: 404, request id: 6E8GGR5ZS32N7QM8, host id: suH2JTHRFTzMFIE9k3taAjiWwZEwpLnpICmDzPJNEGEvYgK380Fb4QOROJks0MtaH53noQJVu1k=

$ aws s3 ls s3://mybucket/sib_rss.xml
</pre>

The file sib_rss.xml does not exist in that directory I don't know why hugo is trying to delete it.  Is it possible hugo is seeing the file in the CDN listing instead of looking in the s3 bucket directly?

As an aside, lets say there was a sib_rss.xml file there and I didn't want hugo to delete it?  Is there an example somewhere showing how to use the exclude functionality to not delete this file?  I tried adding

exclude = "sib_rss.xml"

to the config.toml file and it didn't work around this problem.

**Comment by bep** [comment]
> Is it possible hugo is seeing the file in the CDN listing instead of looking in the s3 bucket directly?

No.

As to your other question, try https://discourse.gohugo.io/

**Comment by bep** [comment]
> I even tried removing the file but still no go:

Delete from where?

**Comment by ctindel** [comment]
What I meant was I ran the aws s3 rm command just to be sure the file wasn't actually there in the s3 bucket.  Is there some kind of debug logging i can enable to figure out why it thinks there's a file it needs to delete?

**Comment by vangent** [comment]
There is some additional `INFO` level logging in the "deploy" package that might give a bit more state (but not much); @bep can probably best describe how to enable it.

Can you show what `aws s3` shows as the listing for the directory (`aws s3 ls` or `aws s3 list`, not sure)? Feel free to elide anything private, but in particular does it show that file?. Make sure that when you're issuing `aws s3` commands that you're using the same region as your `hugo deploy` config (`region=us-east-2`), that could be the source of discrepancies.

The Go CDK code for this is fairly simple, it's just calling `ListObjectsV2` (https://github.com/google/go-cloud/blob/v0.22.0/blob/s3blob/s3blob.go#L406), there's really no way for it to be making up a filename.

**Comment by vangent** [comment]
The key `/sib_rss.xml` is also interesting due to the leading slash. Is it possible you have a file in your bucket with that name? It wouldn't shock me if things didn't work quite right in that scenario.

**Comment by ctindel** [comment]
Its weird, it's happening intermittently now and not reproducible every time.  I wonder if s3 has some weird consistency problem or i'm hitting some kind of cache.  Let's see if it happens tomorrow at all.

**Comment by vangent** [comment]
According to the internets, S3 is only eventually consistent for deletes, so that seems possible. Doing a list via the `aws s3` CLI would be interesting, to see exactly what you get back (and whether it is consistent).

**Comment by ctindel** [comment]
I can tell you that when it was happening, I did that list several times (with grep for example) and saw no such file.  I also looked in the s3 console and it wasn't there.

I've added this to just get around the issue for now and also because I don't want hugo trying to delete the extra xml file I put in the directory.

exclude = "*rss*.xml"

**Comment by davidejones** [comment]
Not sure if this helps but I've seen this before. For us it was because we happened to have 2 deploys running at the same time to the same targets and one deploy would be ready to delete the file but it had already been deleted by the other so we would get this error. 

Try the hugo deploy command with `--log --verbose --debug` flags and see if you notice anything else in the output

**Comment by bep** [comment]
I suggest that we check the error, if `NotFound` then just log it as an warning, but don't fail.
