### ISSUE TITLE
Support cactus.chat for comments

### ISSUE THREAD

**Issue by Juliaria08** [gohugoio/hugo#8389]
This is a proposal to support cactus.chat for adding comments and if you selfhost you can change the instance...

**Comment by jmooring** [comment]
No changes are required to Hugo's code base. The Cactus Comments [Quick Start](https://cactus.chat/docs/getting-started/quick-start/) documentation describes "the easiest way to embed Cactus Comments on your website."

**Comment by Juliaria08** [comment]
Ok :( i wanteed a snipet like it has for markdown docs
