### ISSUE TITLE
Treatment of some fields not easy to understand (it changes the original .Params value)

### ISSUE THREAD

**Issue by richtera** [gohugoio/hugo#8390]
<pre>
$ hugo version
hugo v0.82.0+extended linux/amd64 BuildDate=unknown
</pre>

### Reproduce
Although pubdate is a custom value I use and expect to retrieve using .Params.pubdate it's being detected as a standard publishdate field. That itself is ok, but I think .Params.pubdate should allow retrieval of the original value even though the field was detected and converted into .PublishDate

With a file containing frontmatter:
```yaml
pubdate: 2016 Aug
```

```hugo
{{ warnf "%s %v %v %v" .RelPermalink .Params.pubdate .PublishDate .Params.publishdate }}
```
outputs

```sh
WARN 2021/04/06 08:56:47 /view/bxrSod8QSSMZos95B2hN/pubmed/27220979/ <nil> 2016-05-25 00:00:00 +0000 UTC 2016-05-25 00:00:00 +0000 UTC
```

It's also not not decoding the date correctly if the pubdate doesn't contain day or month information. I am not quite sure how it picks May instead of August. In my use case this is not a big deal, but my file generator uses "pubdate" as a formatted publication date of a journal which is a date of an issue and not a day of the year and therefore doesn't really contain days and sometimes doesn't contain months for yearly publications. As a workaround I have renamed the pubdate field in my metadata generator, but it seems when hugo does field calculations it should probably leave the original values in Params.

**Comment by jmooring** [comment]
See <https://gohugo.io/getting-started/configuration/#configure-dates>

> Also note that Hugo have some built-in aliases to the above: lastmod => modified, publishDate => pubdate, published and expiryDate => unpublishdate. With that, as an example, using pubDate as a date in front matter, will, by default, be assigned to .PublishDate.

**Comment by richtera** [comment]
Ok, it just seems tricky if dates are partials and then there is no way to get the original field value. I will try to turn off date conversions an see if that works.

**Comment by jmooring** [comment]
@richtera

When I do this:

```
---
title: Test
pubdate: 2016 Aug
draft: false
---
```

With this:

```
{{ warnf "%s %v %v %v" .RelPermalink .Params.pubdate .PublishDate .Params.publishdate }}
```

I get this:

```
WARN 2021/04/07 09:01:39 /post/test/ <nil> 0001-01-01 00:00:00 +0000 UTC <nil>
```

Which is exactly what I expect. 

The input for any date field must be in a format that Hugo can parse. This might be useful reading:
<https://github.com/gohugoio/hugo/issues/8285#issuecomment-813682508>

**Comment by richtera** [comment]
I agree for .PublishDate but why could .Params.pubdate not just contain the original value (i.e. why should .Params not just contain the raw metadata) When using metadata downloaded from another system it's not always possible to rename fields. I have a workaround by translating the metadata coming from pubmed and renaming the pubdate to be formattedpubdate. BTW I do see the correct Year when I try this.

**Comment by jmooring** [comment]
> but why could .Params.pubdate not just contain the original value

Because it's an alias to .PublishDate, not a separate slot to store a value. An alias _points_ to something else.

There's one man in a room, and his name is Robert. Sometimes his friends call him Bob or Rob. There are not three men in the room. Bob and Rob are aliases of Robert; they _point_ to Robert.

Please take additional discussion to the forum (https://discourse.gohugo.io/). Thanks.
