### ISSUE TITLE
Mantain the empty vars with the correct format

### ISSUE THREAD

**Issue by kinti** [gohugoio/hugo#8392]
### What version of Hugo are you using (`hugo version`)?
hugo v0.81.0-59D15C97+extended darwin/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio
<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release?
Yes

for example:
```
<meta name="application-name" content="{{ .Title }} | {{ .Site.Title }}">
<meta property="og:site_name" content="{{ .Site.Params.sitename }}">
<meta name="description" content="{{ .Params.meta_description }}">
<meta itemprop="description" content="{{ .Params.meta_description }}">
<meta property="og:description" content="{{ .Params.meta_description }}">
```

If there are no content in one of these meta content tags, the output is this:
```
<meta name="application-name" content="Inicio">
**<meta property="og:site_name" content>
<meta name="description" content>
<meta itemprop="description" content>
<meta property="og:description" content>**
```

The error:
When there is no content in a given tag, at least in these type of **metatags**, the system can't eat the ="", system must leave empty only the tag, `<meta property="og:description" content="**{{ .Params.meta_description }}**">`

Proposal:
If there is no content in a tag, mantain the variable but empty correctly, as this: `<meta property="og:description" content="">`

Thank you

**Comment by pamubay** [comment]
This is optimization done by `--minify` flag optimization. More on https://github.com/tdewolff/minify

If you build without `--minify` the double quotes is preserved:
```
<meta property="og:site_name" content="">
```
Meanwhile, with `--minify` flag produces this output:
```
<meta property="og:site_name" content>
```

I've also tried, apply this config:
```
minify:
  tdewolff:
    html:
      keepQuotes: true
```

But It's **doesnt work**. 

More about [Minify Config](https://gohugo.io/getting-started/configuration/#configure-minify)

**Comment by jmooring** [comment]
@kinti What harm does the current behavior cause? Is there a particular system that does not handle the output correctly?

**Comment by kinti** [comment]
> What harm does the current behavior cause? Is there a particular system that does not handle the output correctly?

https://validator.w3.org/ output as invalid

**Comment by jmooring** [comment]
@kinti 

Please copy and paste the contents of [this gist](https://gist.github.com/jmooring/711e17f4659c9dbdd0c3adf323240014) into <https://validator.w3.org/#validate_by_input>.

The validation error:

> The itemprop attribute was specified, but the element is not a property of any item.

So the _only_ offending line is:

```html
<meta itemprop="description" content>
```

Change it to:

```html
<meta itemprop="description" content="foo">
```

The validator returns the same error. 

The validation error is not related to the `content` attribute, or its lack of a specific value. Instead, the error is caused by lack of [`itemscope`](https://www.w3.org/TR/microdata/#dfn-itemscope). 

To get the page to validate, add the boolean `itemscope` attribute to either the `<head>` or the `<html>` element; I'm not sure which one is better.

In the future please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements.

**Comment by kinti** [comment]
But alt="" => alt yes
This is a bug,

**Comment by jmooring** [comment]
@kinti I do not mean to be difficult, but can you please explain why changing `alt=""` to `alt` is a problem? To the best of my knowledge these are functionally equivalent for both boolean and non-boolean values, and do not cause validation errors.

Please copy and paste the contents of [this gist](https://gist.github.com/jmooring/1bac265fa9b8f20f44a5c0e031247ab7) into <https://validator.w3.org/#validate_by_input>.

**Comment by kinti** [comment]
@jmooring

put an empty alt without ="" in the code please, 

"Image report

The img elements of the page are shown below categorized by their type of textual alternative. Please review that the images in each group match that group’s definition.
Empty textual alternative—Omitted from non-graphical presentation

The following images are marked to be omitted from non-graphical presentations (alt="").

Purely decorative images belong in this category. Also, iconic images that are redundant with text next to them belong here.

If the page would become less understandable if the presence of an image was concealed, the image doesn't belong here. In that case, a textual alternative should be supplied or if the markup generator does not have a textual alternative available (because the user refused to provide it), the alt attribute should be omitted by the markup generator. "
