### ISSUE TITLE
Error copying static files: chtimes ... operation not permitted

### ISSUE THREAD

**Issue by Kzer-Za** [gohugoio/hugo#8395]
<pre>
hugo v0.81.0+extended linux/amd64 BuildDate=unknown

</pre>

I am using Linux, but the site folder is on an NTFS disk. When I run hugo, I get an error:

```
INFO 2021/04/07 12:03:47 Using config file: 
Start building sites … 
INFO 2021/04/07 12:03:47 syncing static files to /mnt/Data/My_Doc/Sites_Hugo/shadrina.me/public/
Total in 61 ms
Error: Error copying static files: chtimes /mnt/Data/My_Doc/Sites_Hugo/shadrina.me/public/: operation not permitted
```
This happens only on the NTFS volume, if I copy the site folder on an ext4 partition, the site is built without errors. However, I need to keep the project on the NTFS disk.

Also, the static files actually *are* copied successfully; so this error, as far as I can tell is a false warning. Probably this is connected to the fact that the NTFS disk is mounted with root owner, but with full permissions:

```
drwxrwxrwx 1 root root 4,0K Apr  7 12:03 ./
```

**Comment by jmooring** [comment]
```
touch foo.txt
touch -a foo.txt 
touch -m foo.txt 
chmod 666 foo.txt 
sudo chown root:root foo.txt 
touch -a foo.txt 
touch -m foo.txt 
```

> touch: setting times of 'foo.txt': Operation not permitted
> touch: setting times of 'foo.txt': Operation not permitted

So even though I have write permissions, I cannot update the atime or mtime values, which is what the [chtimes](https://golang.org/pkg/os/#Chtimes) function attempts to do.

I don't think this is a false error, and am inclined to close this issue.

[Ubuntu 20.04.2 LTS with Linux 5.8.0-48-generic x86_64]
