### ISSUE TITLE
writeStats adds comments and doctype to used tags

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#8396]
```
❯ hugo version
hugo v0.82.0-9D960784+extended linux/amd64 BuildDate=2021-03-21T17:28:04Z VendorInfo=gohugoio
```

When setting build > writeStats to true Hugo writes a list of used tags into hugo_stats.json. In my list the first two items appear to be erroneous, a comment start (comment end is missing) and the `!doctype` which can't be accessed via CSS anyway. 

I am only aware of the use of this file for purgecss so it might not be a bug if this is useful for any other use case, but I am failing to find usecases for comment-start and doctype. 

If they make sense, then comment-end should be part of the list, so this is a bug in either case ;]

```
{
  "htmlElements": {
    "tags": [
      "!--",
      "!doctype",
      "a",
      ...
```

**Comment by bep** [comment]
I'll reopen this; we should try make this as clean as possible, but there will be false positives.

**Comment by dirkolbrich** [comment]
I narrowed it down to the `func (c *cssClassCollectorWriter) insertStandinHTMLElement(el string) (string, string)` method within `publisher/htmlElementsCollector.go`.
In here a `<!DOCTYPE html>` line is converted to `<div html>` and a `<!-- comment -->` line to `<div comment -->`, which disguises these lines for the next step as a standard html.ElementNode, instead as a html.DoctypeNode or html.CommentNode, which would be discarded.

I have added a simple filter (see branch https://github.com/gohugoio/hugo/compare/master...dirkolbrich:writestats-exclude-comments-and-doctype), but I'm stuck with the lowercase `<!doctype html>` line. If I add this to the filter, a lot of errors for `github.com/gohugoio/hugo/hugolib` appear and a lot of tests blow up.

```go
// The net/html parser does not handle single table elements as input, e.g. tbody.
// We only care about the element/class/ids, so just store away the original tag name
// and pretend it's a <div>.
func (c *cssClassCollectorWriter) insertStandinHTMLElement(el string) (string, string) {
	tag := el[1:]

	if strings.HasPrefix(tag, "!DOCTYPE") ||
		// if activating this line, tests for github.com/gohugoio/hugo/hugolib blow up
		// if leaving it out, "!doctype" (lowercase) gets written to publisher.HTMLElements.Tags
		// strings.HasPrefix(tag, "!doctype") ||
		strings.HasPrefix(tag, "!--") {
		return el, ""
	}

	spacei := strings.Index(tag, " ")
	if spacei != -1 {
		tag = tag[:spacei]
	}
	tag = strings.Trim(tag, "\n ")
	newv := strings.Replace(el, tag, "div", 1)
	return newv, strings.ToLower(tag)
}
```

```bash
> hugo version
hugo v0.82.0+extended darwin/amd64 BuildDate=unknown
```
