### ISSUE TITLE
Make sure "Total in ..." is the last thing printed to console

### ISSUE THREAD

**Issue by mawillcockson** [gohugoio/hugo#8403]
With `hugo serve` and file watching enabled, Hugo indicates a build run has started with the message "`Change detected, rebuilding site.`".

Hugo does not appear to print an equally consistent message to indicate it is no longer building the site.

On successful builds, the last line is usually something like "`Total in # ms`".

However, error messages may be printed after this line.

---

The motivation for this is to write a `problemMatcher` for a [Visual Studio Code Task][].

VSCode Tasks support a long-running, background task. The `problemMatcher` parses the stdout of the executed command, and uses regular expressions to collect information about errors.

VSCode must know when a build run is started, and when it ends. After a build run, it populates the UI with error information.

`endsPattern` is a regular expression that matches whichever line is printed at the end of a build run.

I don't know of one that works in a general case.

My current working attempt is:

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "preview (hugo server)",
            "type": "process",
            "command": "hugo",
            "args": [
                "serve",
                "--bind", "0.0.0.0",
                "--port", "1313",
                "--source", "${workspaceFolder}"
            ],
            "detail": "Generate a live preview of the website",
            "echoCommand": true,
            "isBackground": true,
            "isBuildCommand": true,
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "clear": false,
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
            },
            "runOptions": {
                "instanceLimit": 1,
                "runOn": "folderOpen",
            },
            "suppressTaskName": true,
            "problemMatcher": {
                "owner": "external",
                "applyTo": "allDocuments",
                "fileLocation": "absolute",
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": "Change detected",
                    "endsPattern": "Build finished",
                },
                "pattern": {
                    "kind": "location",
                    "regexp": "^\\s*?([A-Z]+)\\s+[\\d/]+\\s+[\\d:]+\\s(.*?\"((.*):(\\d+):(\\d+))\".*)$",
                    "severity": 1,
                    "file": 4,
                    "line": 5,
                    "column": 6,
                    "message": 2,
                }
            }
        }
    ]
}
```

[Visual Studio Code Task]: <https://code.visualstudio.com/docs/editor/tasks> "Documentation and Guide on Visual Studio Code Tasks"

**Comment by bep** [comment]
If I understand you correctly, your main problem with the current situation is that we print errors after the "Total in ..."; if we fix that (as in: make sure the "Total in" is the last thing printed, then the current text would work?

**Comment by mawillcockson** [comment]
Yes, that would work.

If a different message would work better, that would be awesome. I understand that `Total in ...` may not make sense in every situation. For example, template errors.

As long as the message is:

- [x] deterministic
- [x] always present

that would satisfy this proposal.

**Comment by bep** [comment]
>Total in ... may not make sense in every situation

Yea, well, nothing is perfect -- and we had that message, like, forever, so I bet there are existing tooling out there that relies on that message.

**Comment by mawillcockson** [comment]
I appreciate your realism.

[From a cursory search, people are relying on `Total in ...`.](https://github.com/search?q=hugo+%22Total+in%22&type=code)

It may have been obvious, but to be complete, the last requirement would be:

> - [x] deterministic
> - [x] always present
- [x] printed exactly once

**Comment by bep** [comment]
I had a quick look at that part of the code, and I think we use the term "Rebuilt in ..." when a config file changes (which triggers a full rebuild).

So, to summarize this task:

1. Change the text to always say "Total in ..." (pull out into a function)
2. Refactor the code so that any error gets printed first

**Comment by PavloGl** [comment]
Hi!
Could I be assigned to this issue?

**Comment by meehawk** [comment]
@PavloGl I have already started to work on this issue do you want to chime in?

**Comment by PavloGl** [comment]
@meehawk no problem, I'll find another one

**Comment by meehawk** [comment]
> I had a quick look at that part of the code, and I think we use the term "Rebuilt in ..." when a config file changes (which triggers a full rebuild).
> 
> So, to summarize this task:
> 
> 1. Change the text to always say "Total in ..." (pull out into a function)
> 2. Refactor the code so that any error gets printed first

@bep the method `c.timeTrack` which causes the log to be output is prefixed by a `defer` so it should be logged at the end of the `rebuildSites` method after all the errors have been logged in. Do we still need to handle `2` in that case ?

**Comment by jhollowe** [comment]
@meehawk yeah, #2 is still needed because the actual handling of the errors (printing them out) happens [outside of the `rebuildSites` function](https://github.com/gohugoio/hugo/blob/76c95f55a5d18290baa7f23667161d4af9fb9b53/commands/hugo.go#L1116)

Currently, the output is
> Change detected, rebuilding site.
2021-06-12 03:11:14.190 +0000
Source changed "/path/to/file.md": WRITE
Total in 2 ms
ERROR 2021/06/12 03:11:14 Rebuild failed:
ERROR 2021/06/12 03:11:14 "/path/to/file.md:30:1": failed to extract shortcode: template for shortcode "asdf" not found

Where the preferred result would be
> 2021-06-12 03:11:14.190 +0000
Source changed "/path/to/file.md": WRITE
ERROR 2021/06/12 03:11:14 Rebuild failed:
ERROR 2021/06/12 03:11:14 "/path/to/file.md:30:1": failed to extract shortcode: template for shortcode "asdf" not found
Total in 2 ms

I'll make a PR to make sure the time is always printed after the errors have been printed

**Comment by jhollowe** [comment]
@mawillcockson This is the [Hugo VS Code tasks file](https://github.com/jhollowe/blog/blob/main/.vscode/tasks.json) I ended up with. It isn't perfect, but it gets all the errors even if it sometimes randomly removes errors that are still present. (feel free to make a PR if you make it better)
