### ISSUE TITLE
Extra closing tags left when using truncate and safeHTML function on HTML with nested div tags.

### ISSUE THREAD

**Issue by SethThoburn** [gohugoio/hugo#8405]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo v0.82.0+extended darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### Issue
To reproduce:
Set `$content` equal to:
```
<div>
     <div>
      Lorem ipsum dolor sit amet.
     </div>
</div>
<p>Lorem ipsum dolor sit amet.</p>
```

Using functions like this:
`{{ $content | safeHTML | truncate 100 }}`

Expected output:
```
<div>
    <div> Lorem ipsum dolor sit amet. </div>
</div>
<p>Lorem ipsum dolor sit amet. …</p>
```

Actual output:
```
<div>
    <div> Lorem ipsum dolor sit amet. </div>
</div>
<p>Lorem ipsum dolor sit amet. …</p>
</div>
</div>
```

As you can see, Hugo closes the divs which have already been closed. This seems to happen whenever you nest two of the same tag within each other.

**Comment by jmooring** [comment]
Unable to reproduce the problem as described.

```bash
git clone --single-branch -b hugo-github-issue-8405 https://github.com/jmooring/hugo-testing hugo-github-issue-8405
cd hugo-github-issue-8405
hugo server
```

Then visit `http://localhost:1313/post/test/` and view source.

See `layouts/_default/single.html` for code.
