### ISSUE TITLE
Could I use custom markdown processor? 

### ISSUE THREAD

**Issue by HerbertHe** [gohugoio/hugo#8407]
I noticed that hugo is using Goldmark as markdown processor. As a frontend developer, here are too many interesting extensible methods with markdown. 

Could I use custom markdown processor instead of Goldmark? 

Maybe it is a good idea for the guys that write their own markdown! 🌝 I thought the markdown processor Lute is also a great markdown processor.

**Comment by jmooring** [comment]
> Could I use custom markdown processor instead of Goldmark?

No.

In the future please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements.
