### ISSUE TITLE
Using Ugly URLs and _index.md for directories

### ISSUE THREAD

**Issue by RogerBlasco** [gohugoio/hugo#8412]
Please pardon in that I've not posted any technical query before, nor is English my total first language. 
I would very much like the communities assistance in what I view as a bug, if possible, do review the below: 

1. When one sets: 
uglyURLs = true
in their Hugo sites Config file 
this sets files such as: 
/content/get-help/now.md 
as a url: /content/get-help/now.html

This is fantastic. In this case I'm porting over a very large, very old site. So keeping existing URL structures, will be very good/imperative. 

2. However, in the existing site, each directory (such as /content/) has an index.html - 

so on the site I'm porting, /get-help/  is browse-able and gives one the content of /get-help/index.html

3. I've found other threads over time 1 or 2, which broach this, unfortunately one where the person posting was being particularly rude and feel that prohibited cooperative workings, so I wanted to take a chance (apologize on that persons behalf),  and post the above issue and propose: 

If one is using uglyURLs = true
Can their be an option to still allow _index.md when in a directory, to resolve to that directories name. such as 
/get-help/_index.md
resolve to: 
/get-help/

while having uglyURLs on. 

In their is already a method to do this, please pardon the difficulty and thank you all for your time. 

(Please note, I am aware and am in the interim using aliases in the markdown file's header material to cope with this, but I want to ensure I am building these sites in the best possible way, again, thank you everyone for your time)

### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
v.081.0
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by davidsneighbour** [comment]
The community is at https://discourse.gohugo.io. Please close this bug report and start a conversation over there :)

**Comment by RogerBlasco** [comment]
Pardon the difficulty, thank you for your time. I believe this is now closed by Mr j. mooring.
