### ISSUE TITLE
development hugo not building, go dependency difference between 1.15 and 1.16

### ISSUE THREAD

**Issue by flowerbug** [gohugoio/hugo#8416]
When trying to build current development version of hugo I get the following error:

me@ant(160)~/src/github/hugo$ git branch
* master
* 
me@ant(161)~/src/github/hugo$ git pull
Already up to date.

me@ant(162)~/src/github/hugo$ go build
tpl/internal/go_templates/texttemplate/helper.go:11:2: package io/fs is not in GOROOT (/usr/lib/go-1.15/src/io/fs)

The files mentioned are used in version 1.16 but I don't see them in go version 1.15.

I did install go version 1.16 but the error persists so I'm guessing there is some reference in hugo itself which is doing this.

In the meantime I have gotten the binary version of hugo and it works as it should.

**Comment by jmooring** [comment]
I am unable to reproduce the problem. The current development version of Hugo (c2d8f87) builds without error with go 1.16. 

In the future please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements.
