### ISSUE TITLE
hugo_stats.json: bad tag if html element contains tab character 

### ISSUE THREAD

**Issue by yaaax** [gohugoio/hugo#8417]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.82.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

#### Steps to reproduce
1. One markdown file needs to contain an HTML element (e.g. `form`) declared on several lines, **with tabs for indentation**, as this example:
```
<form
	action="[URL]"
	method="post"
>

## Random markdown content
Foo bar
```
2. Run `hugo server -e production`

#### Expected:

Tag `"form"` should be added within the list of tags within `hugo_stats.json`file.

#### Actual:

Tag `"form\n\taction=\"[URL]\"\n\tmethod=\"post\""` is added within the list of tags in `hugo_stats.json` file.

#### Note:

The issue does not happen if the form is declared in one line :
```
<form action="[URL]" method="POST">
```

Similar issue already raised here: #7958 
Maybe also related to #8396

**Comment by jmooring** [comment]
I am unable to reproduce the problem.

```bash
git clone --single-branch -b hugo-github-issue-8417 https://github.com/jmooring/hugo-testing hugo-github-issue-8417
cd hugo-github-issue-8417
hugo server
```

Also, according to the [CommonMark specification](https://spec.commonmark.org/0.29/#html-blocks), an HTML block must be followed by a blank line. That is why the page renders incorrectly. You can [try it here](https://spec.commonmark.org/dingus/?text=%3Cform%0A%20%20action%3D%22%5BURL%5D%22%0A%20%20method%3D%22post%22%0A%3E%0A%23%23%20Random%20markdown%20content%0AFoo%20bar%0A).

**Comment by yaaax** [comment]
Thanks @jmooring for your advice regarding the blank line.

I've managed to reproduce the issue with tabs instead of spaces for indentation.

Note: I'm not sure if it's a good practice or not 🤔
I personally prefer tab vs spaces for indentation, in general, that's why I've set up [prettier](https://prettier.io/) to format my files that way.. but there might by something wrong here?

**Comment by jmooring** [comment]
Thank you. I've update the minimal reproducible example, and the title of this issue. The simplest failing example is:

```
<hr[TAB]id=a>
```

The [CommonMark specification](https://spec.commonmark.org/0.29/#tabs) provides many examples of using tabs for indentation, so your preference is technically sound.
