### ISSUE TITLE
Minify ignores `precision: 0` config param and converts JS and JSON numbers to scientific notation by default

### ISSUE THREAD

**Issue by thegreatsunra** [gohugoio/hugo#8418]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.81.0-59D15C97+extended darwin/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio

hugo v0.82.0-9D960784+extended darwin/amd64 BuildDate=2021-03-21T17:28:04Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes (hugo v0.82.0)

### Describe the issue:

The Hugo docs indicate that for the CSS, JS, JSON, and SVG [minify configs](https://gohugo.io/getting-started/configuration/#configure-minify), `precision` is set to `0` by default. The current source code, however, seems to indicate that's not currently the case for JS and JSON: https://github.com/gohugoio/hugo/blob/3d5dbdcb1a11b059fc2f93ed6fadb9009bf72673/minifiers/config.go#L44-L45

...it appears `precision` is currently only being set to `0` for SVG and CSS.

[The `Precision` parameter](https://github.com/tdewolff/minify/blob/master/json/json.go#L26) from `tdewolff/minify` should be exposed for configuration for JSON and JS, in addition to SVG and CSS. Currently, setting the config parameter `minify.tdewolff.json.precision` to `0` does not seem to have the desired effect, as the minified output that results appears to be the exact same output as not providing a `precision` config value at all.

I believe this issue was introduced in #8259 https://github.com/gohugoio/hugo/pull/8259/files#diff-50afd03ceba68ec4aeb65a643fe7e5a63c2953e33cae5190a8b57cc8214de78dL46

I can reproduce it in Hugo 0.81.0 and Hugo 0.82.0.

I am unable to reproduce it in Hugo 0.80.0.

**Comment by bep** [comment]
>...it appears precision is currently only being set to 0 for SVG and CSS.

That is true, but the value is an `int` which gets `0` as its zero (initial) value.

As this seems to be an upstream issue, I would appreciate if you could raise this issue here with a link back to this issue:

https://github.com/tdewolff/minify/issues

**Comment by thegreatsunra** [comment]
Thanks, @bep!

Closing this issue as it stemmed from my misunderstanding of what, exactly, is meant by the `Precision` parameter in `tdewolff/minify` and what a `0` value in particular is meant to achieve there. I take solace that [I was not alone](https://github.com/tdewolff/minify/issues/400#issuecomment-822630523) in my confusion. 😅 

Better yet, [this recently merged PR](https://github.com/tdewolff/minify/pull/401) adds a `KeepNumbers` boolean to the JSON minifier, which satisfies my use case and should go out in the next release of `tdewolff/minify`.
