### ISSUE TITLE
hugo server fails to refresh when filename includes NFC characters in MacOS

### ISSUE THREAD

**Issue by ironsand** [gohugoio/hugo#8429]
I'm using hugo inside a Dropbox folder in MacOS.
Dropbox renames a NFD Unicode filename to NFC automatically.
And when the filename includes NFC characters, hugo fails to refresh the content.

```
$ hugo new posts/ü.md
/Users/ironsand/Dropbox/www/mysite/content/posts/ü.md created
$ hugo server -D --disableFastRender
# edit the file here
# -----------------------
Change detected, rebuilding site.
2021-04-16 18:42:33.639 +0900
Source changed "/Users/ironsand/Dropbox/www/mysite/content/posts/ü.md": WRITE
Total in 144 ms
```
hugo detects when the file changed, but the change doesn't appear in the browser.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.82.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes

**Comment by bep** [comment]
As a workaround you can ... rename the file.

**Comment by roointan** [comment]
Related to issue #2203 , and commit 39df772 (I'm working on this issue, first time contribution)
