### ISSUE TITLE
Hugo doesn't build locally on re-install: `Building sites … WARN (date) found no layout file for "HTML" for kind "page"`

### ISSUE THREAD

**Issue by thor314** [gohugoio/hugo#8430]
### What version of Hugo are you using (`hugo version`)?
Hugo Static Site Generator v0.74.3/extended linux/amd64 BuildDate: 2020-07-29T18:11:24Z

I cloned the [repo](https://github.com/thor314/thor-blog) my site lives at on a new machine, and now hugo doesn't build locally. The [site](https://thork.net/) is building remotely, however. 

When I run `hugo` locally, I get the following: 
```
$ hugo 
Building sites … WARN 2021/04/16 12:17:50 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/04/16 12:17:50 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/04/16 12:17:50 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
... (a bunch more lines like this)
```
Have I failed to download some package on re-install of `hugo`?

**Comment by pamubay** [comment]
the theme is git submodule, make sure use `–recurse-submodules` flag when clone the repo.

or manually init and update submodule after git clone
```
git submodule init
git submodule update
```

**Comment by thor314** [comment]
thanks!

> the theme is git submodule, make sure use `--recurse-submodules` flag when clone the repo.
> 
> or manually init and update submodule after git clone
> 
> ```
> git submodule init
> git submodule update
> ```
