### ISSUE TITLE
Azure deployment with service principal (without blob key)... possible?

### ISSUE THREAD

**Issue by andrewconnell** [gohugoio/hugo#8434]
> _Posted [by the suggestion of @bep](https://discourse.gohugo.io/t/azure-deployment-with-service-principal-without-blob-key-possible/32409) after posting in the forum. @vangent_ 

I've poked around the source to try to figure out how the cloud deployment works & to possibly add this feature but so far coming up empty. I'm currently deploying my site to Azure using the built-in CLI `deploy` command and injecting the Azure storage blob account name & key as envvars. However, a more secure option is to not use keys, rather use service principals.

I *think* **hugo deploy** is using the Aure CLI under the covers for the deployment... 

When using account names & keys, the Azure CLI expects both to be either environment variables or passed in as parameters when uploading to the storage container. Appears Hugo does this via environment variables (that's how I have it working in my GH action).

But if you want to use a service principal, you make the following changes:
1. login to Azure via the Azure CLI: `az login --service-principal --tenant $TENANTID --username $CLIENTID --password $CLIENTSECRET`
1. omit the storage key from the Azure CLI command envvars/arguments, but add the argument `--auth-mode login` to the Azure CLI storage blob command

So the question... is this possible today but if not, any pointers in the codebase (yes, I've checked the `/deploy` folder and still unclear) where I could create an issue & ultimately PR to contribute?

**Comment by vangent** [comment]
`hugo` deploy uses the Go Cloud Development Kit under the covers (Go CDK, http://gocloud.dev).

It supports a couple of different authentication mechanisms through env variables, include `AZURE_STORAGE_KEY` and `AZURE_STORAGE_SAS_TOKEN`. See https://gocloud.dev/howto/blob/#azure for more, and https://docs.microsoft.com/en-us/azure/storage/blobs/authorize-data-operations-cli for more from the Azure side.

As near as I can tell the `--auth-mode login` you are referencing is specific to the `az` CLI.

Depending on how `AZURE_STORAGE_AUTH_MODE` works (see https://docs.microsoft.com/en-us/azure/storage/blobs/authorize-data-operations-cli#set-environment-variables-for-authorization-parameters, it's the env variable version of --auth-mode), it might just work (I doubt it, but try it!). It *might* be possible to add support for it to https://github.com/google/go-cloud/tree/master/blob/azureblob; if you'd like to try, open a bug and/or pull request there. If it's implemented in the `az` CLI, then that's not likely though.

No changes would be required in Hugo for that.

HTH

**Comment by andrewconnell** [comment]
Thanks... that's helpful. I wasn't aware of that environment variable setting. I tried it without success.  So the next step is to poke around the go-cloud project to see if I can add support upstream that Hugo can leverage. 

Thanks again!
