### ISSUE TITLE
Enhancement: built-in shortcode for alert boxes

### ISSUE THREAD

**Issue by scruloose** [gohugoio/hugo#8437]
Documentation sites seem to be one of the big use-cases for Hugo — it is my primary use case, for sure.

In documentation, alert boxes to call the reader's attention to a piece of information (often with three levels for "info", "warning", and "danger" or similar) are very widely used and come in *really* handy. As far as I know, this isn't supported in Markdown, at least not in the mainstream dialects of Markdown I've encountered. Alert boxes might be second place on my list of things I wish Markdown supported, after dictionary lists. (I've never 100% forgiven Markdown for supporting unordered and ordered but not dictionary lists. But I digress.)

So far, I have tried three different documentation-oriented Hugo themes. Every one of them had implemented a custom shortcode for alert boxes. And, naturally, they all used slightly different syntax, so switching themes also means rewriting every instance of an alert box shortcode in my Markdown "content" files.

Admittedly, that's a simple search and replace job, but... a significant part of what makes a tool like Hugo so amazing is the degree to which it eliminates the need for tedious search and replace jobs, isn't it?

So, I would suggest that Hugo be enhanced with a built-in shortcode for alert boxes. Traditionally, as I mentioned, there are often three severity levels, usually referred to by names like "warn" or "info". However, since some folks use more levels, and naming is inconsistent, I suggest just accepting an integer, so the user can define as many severity levels as they want. So something like:
```
{{< AlertBox level=1 >}}
This is the lowest severity level, used to indicate an item of particular interest,
though not necessarily a hazard.
{{< /alert>}}
```
I think that would extend Hugo's capabilities in a small but useful way, by providing a consistent and easy-to-remember mechanism to incorporate alert boxes in any page of any Hugo site.

**Comment by jmooring** [comment]
[Goldmark](https://github.com/yuin/goldmark), the markdown renderer we use, has a built-in definition list extension which is enabled by default.

This markdown:

```md
term 1
: This is the definition of term 1.

term 2
: This is the definition of term 2.
```

Produces this HTML:

```
<dl>
<dt>term 1</dt>
<dd>This is the definition of term 1.</dd>
<dt>term 2</dt>
<dd>This is the definition of term 2.</dd>
</dl>
```

See <https://gohugo.io/getting-started/configuration-markup#configure-markup>.

**Comment by scruloose** [comment]
@jmooring That's excellent! Thanks for pointing it out. Sometimes a digression pays off.  ;-)

@davidsneighbour That's a fair point, of course. I must admit I'm very new to Hugo and not very experienced with web development. My experience so far is that yes, alerts as a feature is widely available and widely used, but (maybe due to different theme writers' choice of different frontend source kits?) there's no consistent syntax for using them, which is kind of a pain.

If adding it to Hugo's built-in shortcodes is not the right place to ask for a consistent implementation, any pointers as to what would be the right forum for that? Given that (as far as I know) there's no alert-box HTML element, I assume there's no chance of adding it at the Markdown parser level...
