### ISSUE TITLE
Hugo CI

### ISSUE THREAD

**Issue by s3561128** [gohugoio/hugo#8440]
Hey, I am trying to build a CI with Hugo static website and also deploying on firebase. I don't know how to create a cloudbuild.yaml file for HTML and can someone help me to build a CI with these codes. Please find my codes here https://github.com/s3561128/147-cloud-build-firebase.git

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
