### ISSUE TITLE
Error running on Windows when starting hugo version

### ISSUE THREAD

**Issue by vildasha** [gohugoio/hugo#8449]
`hugo version
Exception 0xc0000005 0x0 0x7ffe11e20fff 0x165be950000
PC=0x165be950000
signal arrived during external code execution

syscall.Syscall(0x7ffe11a3a050, 0x3, 0xc00053c840, 0x0, 0x800, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/syscall_windows.go:330 +0xe9
golang.org/x/sys/windows._LoadLibraryEx(0xc00053c840, 0x0, 0x800, 0xc, 0xc, 0x0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/zsyscall_windows.go:2143 +0x96
golang.org/x/sys/windows.LoadLibraryEx(0x2df1d59, 0xb, 0x0, 0x800, 0xc00052c990, 0xc00052c990, 0xc00052c8d0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/zsyscall_windows.go:2139 +0x9f
golang.org/x/sys/windows.loadLibraryEx(0x2df1d59, 0xb, 0xc00052c901, 0xc00052c990, 0xc00052c990, 0xc00052c990)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/dll_windows.go:407 +0x66
golang.org/x/sys/windows.(*LazyDLL).Load(0xc000888ab0, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/dll_windows.go:242 +0xca
golang.org/x/sys/windows.(*LazyProc).Find(0xc000888b70, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/dll_windows.go:305 +0xc5
github.com/mattn/go-ieproxy.getUserConfigFromWindowsSyscall(0x30, 0x1659925b060, 0x110)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy_windows.go:101 +0x38
github.com/mattn/go-ieproxy.writeConf()
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy_windows.go:34 +0x69
sync.(*Once).doSlow(0x4037608, 0x2ed7f98)
        /usr/local/go/src/sync/once.go:68 +0xf7
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/mattn/go-ieproxy.getConf(...)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy_windows.go:23
github.com/mattn/go-ieproxy.GetConf(...)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy.go:36
github.com/mattn/go-ieproxy.proxyMiddleman(0x2030001)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/proxy_middleman_windows.go:12 +0x1c5
github.com/mattn/go-ieproxy.GetProxyFunc(...)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/proxy_middleman.go:10
github.com/Azure/azure-pipeline-go/pipeline.newDefaultHTTPClient(0x58e2a004)
        /go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:208 +0x2d
github.com/Azure/azure-pipeline-go/pipeline.init()
        /go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:202 +0x29

goroutine 7 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000198000)
        /go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:276 +0xd4
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:34 +0x72
rax     0x7ffe08f255d4
rbx     0x93d
rcx     0x41
rdi     0xffffffffffbadd11
rsi     0xc000007a
rbp     0x0
rsp     0x1a13ffeb60
r8      0x0
r9      0x0
r10     0x0
r11     0x93c
r12     0x7ffe11c30000
r13     0x0
r14     0x0
r15     0x7ffe08f255d4
rip     0x165be950000
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b`

**Comment by jmooring** [comment]
Please download the latest version (v0.82.1) and try again:
<https://github.com/gohugoio/hugo/releases/download/v0.82.1/hugo_extended_0.82.1_Windows-64bit.zip>

**Comment by vildasha** [comment]
Downloaded latest version, same error

`C:\Users\xxx>hugo version
Exception 0xc0000005 0x0 0x7ffe52a00fff 0x2367def0000
PC=0x2367def0000
signal arrived during external code execution

syscall.Syscall(0x7ffe51c7a050, 0x3, 0xc000036960, 0x0, 0x800, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/syscall_windows.go:330 +0xe9
golang.org/x/sys/windows._LoadLibraryEx(0xc000036960, 0x0, 0x800, 0xc, 0xc, 0x0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/zsyscall_windows.go:2143 +0x96
golang.org/x/sys/windows.LoadLibraryEx(0x29f1d59, 0xb, 0x0, 0x800, 0xc0006f9410, 0xc0006f9410, 0xc0006f9350)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/zsyscall_windows.go:2139 +0x9f
golang.org/x/sys/windows.loadLibraryEx(0x29f1d59, 0xb, 0xc0008bf401, 0xe6af73, 0x2367db113b0, 0x0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/dll_windows.go:407 +0x66
golang.org/x/sys/windows.(*LazyDLL).Load(0xc0008ef530, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/dll_windows.go:242 +0xca
golang.org/x/sys/windows.(*LazyProc).Find(0xc0008ef5f0, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/dll_windows.go:305 +0xc5
github.com/mattn/go-ieproxy.getUserConfigFromWindowsSyscall(0x1000000000030, 0x2367db113b0, 0x110)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy_windows.go:101 +0x38
github.com/mattn/go-ieproxy.writeConf()
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy_windows.go:34 +0x69
sync.(*Once).doSlow(0x3c37608, 0x2ad7f98)
        /usr/local/go/src/sync/once.go:68 +0xf7
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/mattn/go-ieproxy.getConf(...)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy_windows.go:23
github.com/mattn/go-ieproxy.GetConf(...)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy.go:36
github.com/mattn/go-ieproxy.proxyMiddleman(0x2030001)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/proxy_middleman_windows.go:12 +0x1c5
github.com/mattn/go-ieproxy.GetProxyFunc(...)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/proxy_middleman.go:10
github.com/Azure/azure-pipeline-go/pipeline.newDefaultHTTPClient(0xedc45231)
        /go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:208 +0x2d
github.com/Azure/azure-pipeline-go/pipeline.init()
        /go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:202 +0x29

goroutine 20 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00008e800)
        /go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:276 +0xd4
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:34 +0x72
rax     0x7ffe496955d4
rbx     0x93d
rcx     0x41
rdi     0xffffffffffbadd11
rsi     0xc000007a
rbp     0x0
rsp     0xb704ffefd0
r8      0x0
r9      0x0
r10     0x0
r11     0x93c
r12     0x7ffe52810000
r13     0x0
r14     0x0
r15     0x7ffe496955d4
rip     0x2367def0000
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b`

**Comment by jmooring** [comment]
I am unable to reproduce with Win 10 64-bit. Could your security software (e.g., virus scanner) be causing this?

**Comment by vildasha** [comment]
disabled windows firewall and uninstalled security program Webroot, same issue. what else can I check? I also tried creating new user and still the same issue

**Comment by jmooring** [comment]
1. Move the executable to C:\Temp (create the directory if you need to).
1. Open a cmd window and run `hugo --version`
1. If it fails again, close the cmd window, and then open a new one _as administrator_, and test again

**Comment by vildasha** [comment]
`C:\Temp>hugo --version
Exception 0xc0000005 0x0 0x7ffe52a00fff 0x27d50680000
PC=0x27d50680000
signal arrived during external code execution

syscall.Syscall(0x7ffe51c7a050, 0x3, 0xc00003e930, 0x0, 0x800, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/syscall_windows.go:330 +0xe9
golang.org/x/sys/windows._LoadLibraryEx(0xc00003e930, 0x0, 0x800, 0xc, 0xc, 0x0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/zsyscall_windows.go:2143 +0x96
golang.org/x/sys/windows.LoadLibraryEx(0x24a1d59, 0xb, 0x0, 0x800, 0xc00074f770, 0xc00074f770, 0xc00074f6b0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/zsyscall_windows.go:2139 +0x9f
golang.org/x/sys/windows.loadLibraryEx(0x24a1d59, 0xb, 0xc00074f701, 0xc00074f770, 0xc00074f770, 0xc00074f770)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/dll_windows.go:407 +0x66
golang.org/x/sys/windows.(*LazyDLL).Load(0xc0005bb890, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/dll_windows.go:242 +0xca
golang.org/x/sys/windows.(*LazyProc).Find(0xc0005bb950, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20210104204734-6f8348627aad/windows/dll_windows.go:305 +0xc5
github.com/mattn/go-ieproxy.getUserConfigFromWindowsSyscall(0x30, 0x27d2afcb060, 0x110)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy_windows.go:101 +0x38
github.com/mattn/go-ieproxy.writeConf()
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy_windows.go:34 +0x69
sync.(*Once).doSlow(0x36e7608, 0x2587f98)
        /usr/local/go/src/sync/once.go:68 +0xf7
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/mattn/go-ieproxy.getConf(...)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy_windows.go:23
github.com/mattn/go-ieproxy.GetConf(...)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/ieproxy.go:36
github.com/mattn/go-ieproxy.proxyMiddleman(0x2030001)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/proxy_middleman_windows.go:12 +0x1c5
github.com/mattn/go-ieproxy.GetProxyFunc(...)
        /go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.1/proxy_middleman.go:10
github.com/Azure/azure-pipeline-go/pipeline.newDefaultHTTPClient(0x5690120a)
        /go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:208 +0x2d
github.com/Azure/azure-pipeline-go/pipeline.init()
        /go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:202 +0x29

goroutine 9 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0001b6280)
        /go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:276 +0xd4
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:34 +0x72
rax     0x7ffe496955d4
rbx     0x93d
rcx     0x41
rdi     0xffffffffffbadd11
rsi     0xc000007a
rbp     0x0
rsp     0xde4d9feca0
r8      0x0
r9      0x0
r10     0x0
r11     0x93c
r12     0x7ffe52810000
r13     0x0
r14     0x0
r15     0x7ffe496955d4
rip     0x27d50680000
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

C:\Temp>`

**Comment by jmooring** [comment]
Well this is obviously _something_ specific to your environment. Do you have another PC you can test with? What's different about your environment compared to a Win 10 46-bit laptop that you buy off the shelf today?

**Comment by jmooring** [comment]
From webroot's site:

> If you are uninstalling SecureAnywhere to troubleshoot an issue, we recommend you reboot your computer and test the issue before reinstalling.

Did you reboot after uninstalling whatever Webroot packages you had installed?

**Comment by vildasha** [comment]
it works on another pc.

**Comment by vildasha** [comment]
I was able to fix the issue completely uninstalling webroot and rebooting the PC. Will try to install webroot back and report.

**Comment by jmooring** [comment]
This is a Webroot problem, not a Hugo problem. I suggest you contact their customer support department. 

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
