### ISSUE TITLE
Enhance the countwords function to handle special characters

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#8479]
Current behavior:

Statement|Actual|Expected|Status
:--|:--|:--|:--
|`countwords "Here's to you..."`|3|3|Pass
|`countwords "Here’s to you..."`|8|3|Fail
|`countwords "Here’s to you…"`|11|3|Fail

These are just two examples of special characters that cause problems; there are others.

The .WordCount page method handles these correctly.

**Comment by bep** [comment]
I'm not totally sure how this fail, but there is obviously a faulty CJK language detection in there, which makes some of the examples above count runes instead. We have the same logic in `.WordCount`, so it should be possible to look at that.

**Comment by ResamVi** [comment]
Hello!
I'm new to contribute: [Here's](https://github.com/gohugoio/hugo/pull/8488) a PR using the same logic as proposed:
