### ISSUE TITLE
[Feature Request] Add support for Cloudflare Web Analytics

### ISSUE THREAD

**Issue by miynat** [gohugoio/hugo#8482]
**Feature request**

Cloudflare provides a free analytics feature for websites - https://www.cloudflare.com/web-analytics/

Is it possible to add support for Cloudflare Web Analytics in addition to existing Google Analytics integration?
It would be great to have a built-in integration for that web analytics tool, as the built-in support for Google Analytics here -  https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/google_analytics_async.html

Thanks in advance.

**Comment by sid-r-singh** [comment]
I would love to have Cloudflare Web Analytics integration with Hugo.
