### ISSUE TITLE
Make a md5 URLs

### ISSUE THREAD

**Issue by cesuogui** [gohugoio/hugo#8484]
If we don't use English title or filename. We wil get a long long URLs.
Such as  UrlEncode:
`http://localhost:1313/sale/%E6%8B%9B%E5%95%86%E8%8A%B1%E5%9B%AD%E5%9F%8E-3%E5%AE%A42%E5%8E%85-%E5%8D%97/`

If we can use md5 to encode URL.
`http://localhost:1313/sale/f4c1ad2c35fc14c1a843109fcf899f93/`
or shorter
`http://localhost:1313/sale/35fc14c1a843109f/`

If we want to make a QRcode , The shorter URL will have more advantage.

config.yaml
```
permalinks:
  /:filemd5/
```
or
```
permalinks:
  /:titlemd5/
```

**Comment by davidsneighbour** [comment]
I don't think this has the importance to be implemented as a feature. What you should do instead is to use the `slug` parameter in the frontmatter and create an md5 hash of the title there. I am not sure if the following works, in your archetype:

```
---
title: "{{ replace .Name "-" " " | title }}"
date: {{ .Date }}
slug: "{{ .Name | md5 }}"
description: "This is meta description"
---
```

If the archetype is not able to use md5 as function I would think of this as a better proposal for implementation.

**Comment by bep** [comment]
I think @davidsneighbour is right here ... Part of me would want to add some scripting capabilities to configuration (e.g. for permalinks) (we may get there if we add Cue as a config format), in this particular case I think you would be better off creating that short URL by hand. It will probably be shorter -- but more importantly more readable and typeable.

**Comment by cesuogui** [comment]
> 我不认为将其作为功能来实现很重要。您应该做的是使用`slug`frontmatter中的参数并在其中创建标题的md5哈希。我不确定您的原型是否适用于以下情况：
> 
> ```
> ---
> title: "{{ replace .Name "-" " " | title }}"
> date: {{ .Date }}
> slug: "{{ .Name | md5 }}"
> description: "This is meta description"
> ---
> ```
> 
> 如果原型不能使用md5作为函数，我会认为这是实现的更好建议。

**Comment by cesuogui** [comment]
> I don't think this has the importance to be implemented as a feature. What you should do instead is to use the `slug` parameter in the frontmatter and create an md5 hash of the title there. I am not sure if the following works, in your archetype:
> 
> ```
> ---
> title: "{{ replace .Name "-" " " | title }}"
> date: {{ .Date }}
> slug: "{{ .Name | md5 }}"
> description: "This is meta description"
> ---
> ```
> 
> If the archetype is not able to use md5 as function I would think of this as a better proposal for implementation.

Thanks for your advice
