### ISSUE TITLE
In v0.83.0 : i18n|MISSING_TRANSLATION WARN messages for keywords not used in i18n

### ISSUE THREAD

**Issue by divinerites** [gohugoio/hugo#8492]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

SInce v0.83.0, I now have WARN messages, but for keywords I do not use in i18n.

Most of those keywords seems belonging to my `[[menu.main]]` section.
But `fullscreen` is not, and I see nothing obvious for those.

example for 1 site:

```
i18n|MISSING_TRANSLATION|fr|banner
i18n|MISSING_TRANSLATION|fr|about
i18n|MISSING_TRANSLATION|fr|team
i18n|MISSING_TRANSLATION|fr|contact
i18n|MISSING_TRANSLATION|fr|portfolio
i18n|MISSING_TRANSLATION|fr|rdv
i18n|MISSING_TRANSLATION|fr|moreinfo
i18n|MISSING_TRANSLATION|fr|fullscreen
i18n|MISSING_TRANSLATION|fr|all
```

and also (closing #8493) this 

```
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "banner": message "banner" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "banner": message "banner" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "about": message "about" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "about": message "about" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "team": message "team" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "team": message "team" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "contact": message "contact" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "contact": message "contact" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "portfolio": message "portfolio" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "portfolio": message "portfolio" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "banner": message "banner" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "about": message "about" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "team": message "team" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "contact": message "contact" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "portfolio": message "portfolio" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "rdv": message "rdv" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "rdv": message "rdv" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "rdv": message "rdv" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "rdv": message "rdv" has no plural form "one"
WARN 2021/05/01 18:11:04 Failed to get translated string for language "fr" and ID "rdv": message "rdv" has no plural form "one"
```

**Comment by jmooring** [comment]
@divinerites,

What do you mean when you say, "I do not use in i18n?"

**Comment by divinerites** [comment]
> What do you mean when you say, "I do not use in i18n?"

- They are not in my `/i18n/fr.yaml` and other language, 
- those are keywords I do not use either in `{{ i18n "keyword" }}`

**Comment by jmooring** [comment]
Search your site (including theme) for `i18n ` and `T ` (alias).

**Comment by divinerites** [comment]
> Search your site (including theme) for `i18n ` and `T ` (alias).

Yes. First thing I have done. 

And done this on all my themes. They all have the same WARN, even if they all have different themes.

**Comment by divinerites** [comment]
Tried other checks. This is a false missing translation report (nor menu related)

```
$ hugo --i18n-warnings | grep i18n
i18n|MISSING_TRANSLATION|fr|quick_links
i18n|MISSING_TRANSLATION|fr|contact_info
i18n|MISSING_TRANSLATION|fr|update
i18n|MISSING_TRANSLATION|fr|access
i18n|MISSING_TRANSLATION|fr|fullscreen
i18n|MISSING_TRANSLATION|fr|keep_in_touch
i18n|MISSING_TRANSLATION|fr|adress
i18n|MISSING_TRANSLATION|fr|date_open
i18n|MISSING_TRANSLATION|fr|hours_open
```

### File : `/i18n/fr.yml`
```
- id: adress
  translation: Adresse

- id: date_open
  translation: Dates d'ouverture
- id: hours_open
  translation: Heures d'ouverture

- id: update
  translation: Mise à jour

- id: access
  translation: Schéma d'accès
  ```

**Comment by bep** [comment]
OK, I scratched my head a little here as the upstream library actually both returns the correct message, but also an error ... So, it kind of works even with all of these warnings. OK, that's fixable.

**Comment by divinerites** [comment]
> OK, I scratched my head a little here as the upstream library actually both returns the correct message, but also an error ... So, it kind of works even with all of these warnings. OK, that's fixable.

Oh yes ... I forgot the obvious !!!
I checked and it seems that all my build are correct. So only WARN but nothing wrong (as far i can see) on the builds.

**Comment by jmooring** [comment]
@divinerites Can you share a repository with me, privately if you wish? I do not understand why are receiving an i18n warning about the keys you don't use. For example, `quick_links`, `fullscreen`, etc.

**Comment by divinerites** [comment]
> @divinerites Can you share a repository with me, privately if you wish? I do not understand why are receiving an i18n warning about the keys you don't use. For example, `quick_links`, `fullscreen`, etc.

Done. And I can add you to other repository as well if needed. Thanks a lot for the help on this one.

**Comment by divinerites** [comment]
> For example, `quick_links`, `fullscreen`, etc.

Quick_links is used by i18n, but not fullscreen.

**Comment by divinerites** [comment]
Tested you [patch](https://github.com/gohugoio/hugo/commit/ececd1b122c741567a80acd8d60ccd6356fa5323), bep and I have no more WARN :-)

jmooring, I double check the fullscreen WARN and it is not used by i18n. I do not have this WARN anymore with bep's patch.

**Comment by jmooring** [comment]
<https://github.com/divinerites/divinerites-maps/blob/master/i18n/en.toml#L1>
<https://github.com/divinerites/divinerites-maps/blob/master/i18n/fr.toml#L1>
<https://github.com/divinerites/divinerites-maps/blob/master/i18n/nl.toml#L1>

**Comment by divinerites** [comment]
Ohhhhhhhh ... I'm so dumb.
Really sorry for losing your time.
