### ISSUE TITLE
site.GetPage "privacy.md" finds tags/privacy even if there is not a "privacy.md" file.

### ISSUE THREAD

**Issue by bryanjhogan** [gohugoio/hugo#8494]
### What version of Hugo are you using (`hugo version`)?
v0.82.0-9D960784+extended

### Does this issue reproduce with the latest release?
yes

### Description
I'm using the Wowchemy Academic theme, version - v0.0.0-20210413192202-ab8d28988e0e.

It has a Privacy link in the footer that is supposed to show if the file "Privacy.md" exists and is not a draft. 

I have deleted that file, but I have blog posts tagged with the word "Privacy". 

The theme's site_footer.html uses this call `{{ if site.GetPage "privacy.md" }}` and even though there is no "Privacy.md", the call finds the tag for privacy and resolves to true and adds a link to the footer. 

https://github.com/wowchemy/wowchemy-hugo-modules/blob/main/wowchemy/layouts/partials/site_footer.html

**Comment by jmooring** [comment]
If content/privacy.md is present:

```
{{ (site.GetPage "/privacy.md").RelPermalink }}  --> /privacy/
{{ (site.GetPage "privacy.md").RelPermalink }}   --> /privacy/
{{ (.GetPage "/privacy.md").RelPermalink }}      --> /privacy/
{{ (.GetPage "privacy.md").RelPermalink }}       --> /privacy/
```

If content/privacy.md is _not_ present:

```
{{ (site.GetPage "/privacy.md").RelPermalink }}  --> /tags/privacy/
{{ (site.GetPage "privacy.md").RelPermalink }}   --> /tags/privacy/
{{ (.GetPage "/privacy.md").RelPermalink }}      --> empty string
{{ (.GetPage "privacy.md").RelPermalink }}       --> empty string
```

<https://gohugo.io/functions/getpage>

If I were the theme author I would use `.GetPage` (method on .Page) with an absolute path.

**Comment by bryanjhogan** [comment]
Thanks @jmooring, that resolved it.

**Comment by bep** [comment]
I'm closing this, as I don't think we're going to do something about it.

**Comment by bryanjhogan** [comment]
Thanks @bep, nothing to do, thanks again to @jmooring for this help.
