### ISSUE TITLE
Add a convertTo method to WEBP

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#8496]
Thank you for the new WEBP support.

Currently -as per the Doc- one can do:
`{{ $images = $images | append ($img.Resize "300x webp") }}`

However there are instances when a user (like this one over [here](https://discourse.gohugo.io/t/images-webp-just-convert-solely/32653)) would wish to simply convert a JPG file to WEBP without resizing but with specifying the quality of the WEBP file.

If appropriate please consider adding a `convertTo` method (or whatever other namespace you consider appropriate).

For example something like:
`{{ $images = $images | convertTo "q50 webp" }}`

**Comment by davidsneighbour** [comment]
For image processing in general that would be a good functionality (jpg, png).

**Comment by jmooring** [comment]
I'm pretty sure this is covered in https://github.com/gohugoio/hugo/issues/8439.

**Comment by onedrawingperday** [comment]
@jmooring 

Right. How could I forget.

Basically in #8439 there is a proposal for an `images.EncodeTo` method.

Thank you for the heads up.

I am closing this issue in favor of #8439
