### ISSUE TITLE
disableKinds with taxonomy should be recursive (also disable term)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8498]
While doing some restructuring work, I have a failing test that is a little head-scratching.

I have `disableKind = ["taxonomy"]`, yet I have an assertion about a term page that should exist.

I know changing this may potentially be breaking, but I suspect that I applied the above logic before we got the build options, which would allow you to disable rendering of, say, the `categories` list page, while still keep all the terms.

**Comment by jmooring** [comment]
I think this should be closed. While testing https://github.com/gohugoio/hugo/pull/10847 I ran across this structure, which is pretty handy for some sites.

```toml
disableKinds = ['taxonomy']

[permalinks.term]
'tags' = '/:title/'
```

**Comment by jmooring** [comment]
This issue was inadvertently closed as completed in https://github.com/gohugoio/hugo/pull/11894. As desired, we continue to render term pages when taxonomy pages are disabled.

```text
disableKinds = ['taxonomy']
```

Result:

```text
public/
├── posts/
│   ├── post-1/
│   │   └── index.html
│   └── index.html
├── tags/
│   ├── tag-a/
│   │   └── index.html
│   └── tag-b/
│       └── index.html
└── index.html
```

Verified with hugo v0.123.0-DEV-60d954c7
