### ISSUE TITLE
Layout for Homepage Template being Overridden by ./layouts/_default/list.html

### ISSUE THREAD

**Issue by joshmossas** [gohugoio/hugo#8501]
### What version of Hugo are you using (`hugo version`)?

```bash
$ hugo version
hugo v0.82.1-60618210+extended windows/amd64 BuildDate=2021-04-20T11:02:50Z VendorInfo=gohugoio
```

### Does this issue reproduce with the latest release?

Yes

### The Issue

Basically the title. `layouts/_default/list.html` is overriding `layouts/index.html`. 

I've gone down the list specified [here](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-home-page), and `layouts/_default/list.html` is taking priority over all of them. I took a video below showing the issue.

https://user-images.githubusercontent.com/31548851/117097521-83225480-ad31-11eb-96ff-1fb50bf77d62.mp4

Thanks appreciate the time. Not sure if I'm doing something wrong or if it's something specific to my system, but I've been experiencing the issue for a while now.

**Comment by joshmossas** [comment]
I'll also add creating `layouts/section/list.html` also overrides `layouts/index.html`

**Comment by jmooring** [comment]
I'm sorry, but I am unable to reproduce either of these behaviors. We prefer to use the Hugo forum (https://discourse.gohugo.io/) for questions and troubleshooting. Would you mind opening a topic there, and sharing a public repository where we can reproduce the behavior? Thanks.
