### ISSUE TITLE
Add .Scratch.DeleteInMap

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#8504]
Unless we revive either https://github.com/gohugoio/hugo/issues/7232 or https://github.com/gohugoio/hugo/issues/5604 `Scratch` will remain the only efficient way to edit maps in Hugo.

## The problem
For now, the only thing missing is a way to remove a key from a map stored in a `Scratch` key.

([.Scratch.Delete](https://gohugo.io/functions/scratch/#delete) will remove a key from the the `Scratch` instance itself.

## Proposal

The method called `.DeleteInMap` to resonate with the familiar `.SetInMap`, would take two parameters: 
the key for the map, and the key to remove.

```
{{ $s := newScratch }}
{{ $s.Set "data" (dict
  "hello" "bonjour"
  "goodbye" "au revoir"
  "car" "voiture"
) }}

{{ $s.DeleteInMap "data" "car" }}
```

**Comment by meehawk** [comment]
I would love to work on this issue. I am a new contributor here. Any pointers would be wonderful @bep @regisphilibert

**Comment by bep** [comment]
@meehawk it's in the `common/maps` package; add the method + a test + a line in the documentation (in this repo in the /docs folder).

**Comment by meehawk** [comment]
@bep for some reason I am having issues setting up mage to run tests. I currently use windows and I followed all the instructions to install mage locally but for some reason my system does not recognise the `mage` as a valid command

**Comment by meehawk** [comment]
@bep gotcha I will try setting up LiteIDE.

**Comment by meehawk** [comment]
@bep I was having issues with a package called `io/fs`. I tried recloning the repo and running `go install` again but I still keep getting the following error

```
tpl\internal\go_templates\texttemplate\helper.go:11:2: package io/fs is not in GOROOT (C:\Program Files\Go\src\io\fs)
```

Running `go version` gives the following output:

```
go version go1.15.8 windows/amd64
```

Does hugo require a certain version of `go` for the build to be successful?

**Comment by bep** [comment]
Hugo needs >= Go 1.16 to build (we usually support 2 versions, but that wasn't possible with 1.16.).

**Comment by meehawk** [comment]
Aah that explains why it would earlier build but now it wont. I will try to upgrade the version. Thank you so much

**Comment by meehawk** [comment]
@bep Just raised a PR
