### ISSUE TITLE
Front matter parameter outputs does not work with empty list

### ISSUE THREAD

**Issue by Andful** [gohugoio/hugo#8510]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1+extended linux/amd64 BuildDate=2021-05-02T17:25:32Z
</pre>

### Does this issue reproduce with the latest release?
Yes

### Reproduction
if I set the front-matter of a markdown the following:
```yaml
---
outputs: []
---
```
The default outputs are emitted.

### Expected behavior
No file should be emitted from that specific markdown.

**Comment by bep** [comment]
>No file should be emitted from that specific markdown.

That's not how this works, and I don't think the docs says that either.

If no outputs are set for a page it will fall back to the defaults configured in your site config.

If you want to not render a given page you need to use other tools, e.g. the `_build` keyword.
