### ISSUE TITLE
External plugin from template

### ISSUE THREAD

**Issue by holyhope** [gohugoio/hugo#8511]
Hello,

I have a proposal to be able to call external program on build.

On #796 there was security concerns about being able to execute any binary on the host.
A suggestion was to whitelist those program by creating a symlink in a local folder.

My new concern is about input/output of the program. It is not that easy to forward all arguments, options and results.

So I opened #8507 in order to propose an other first approach.
Instead of being able to run binaries with all security concerns, I suggest to call [go plugin](https://golang.org/pkg/plugin/) placed in a `plugins/` directory. With ability to check if a plugin is installed.

IMO next steps are:
- Requires Name and Version to plugin
- Have some kind of gallery of plugin
- if this is to restrictive switch to an `exec` function that will call binaries.

What do you think?

**Comment by holyhope** [comment]
I added samples in the [last commit of the PR](https://github.com/gohugoio/hugo/pull/8507/commits).

The summary is that we are able to call go plugin using the following markup:

```gotmpl
{{ plugin.Get "my-plugin" "TheFunction" | plugin.Call }}
```

**Comment by holyhope** [comment]
I have some concerns about what I produced:

1. IMO hugo should not look for plugin in theme folders.
   Not sure about the filesystem lookup and inheritance I implemented for `plugins/` folder. Does hugo will actually look for `plugins/` directory in theme folders?
2. I committed a compiled go plugin because I was not sure when it should be built. I added `mage CompileTest` to reproduce the build.

WDYT?

**Comment by pierreozoux** [comment]
About examples, I have something in mind for documenting open source projects.

I'd like to have a shortcode, like `screenshot` and a url as an arg, and at build time, "hugo" would go and get a screenshot of the url.
(Probably with the help of https://playwright.dev/docs/screenshots/ for instance)
