### ISSUE TITLE
BaseURL ignores hugo server --bind

### ISSUE THREAD

**Issue by calebzulawski** [gohugoio/hugo#8514]
<pre>
$ hugo version
hugo v0.83.1-5AFE0A57 linux/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
</pre>

When using `hugo server --bind=<ip>` I would expect `.Site.BaseURL` to use that IP address instead of `localhost`.

**Comment by bep** [comment]
No, .Site.BaseURL has its own configuration and flag.
