### ISSUE TITLE
Add some hook API for code blocks

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8520]
I was reminded by this tweet

https://twitter.com/natfriedman/status/1391862005095485440?s=20

That the above isn't easy to do in Hugo ... Which we should fix.

**Comment by davidsneighbour** [comment]
The tweet you referenced added a copy link to a code-snippet. That code snippet in relation to Hugo can be anything from an arbitrary layout or my own shortcode to internal shortcodes or the markdown rendering. If your proposal only covers the last two it's probably not the same. But then that's not much more than what markup renderhooks already implement?

**Comment by bep** [comment]
OK, let me be more specific.

In Hugo you can do this:

```toml
[markup]
  [markup.highlight]
    codeFences = true
```

Which will render all markdown code blocks ("´´´html") with the Chroma highlighter. We add surrounding DIV with a class, but you have no way of controlling the markup.

So, what I would like to enable is to allow people to put, say, a template inside `_markup/render-code.html` with something like this:

```html
<div class="hightlight">
<button @click="copy-code()">Copy Code</button>
{{ .Code }}
</div>
```

Or something ... 

See https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks

**Comment by ardianta** [comment]
I need this hooks. If you run programming site or documentation site and don't want to edit your contents, this would be the best solution. I know we can wrap code blocks in shortcode like this:

```markdown
{{< custom-pre >}}
` ``go
// code here
` ``
{{< /custom-pre >}}
```

But, what if we have lot of contents to edit. Its time consuming.

**Comment by mofirouz** [comment]
Big +1 for this please - see https://discourse.gohugo.io/t/render-hooks-for-markdown-code-fences/36188/2
