### ISSUE TITLE
Display version when building

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#8531]
Instead of this:

```txt
Start building sites … 

                   | EN  
-------------------+-----
  Pages            |  9  
  Paginator pages  |  0  
  ...
```

Display this:

```txt
Start building sites … 
hugo v0.84.0-DEV+extended linux/amd64 BuildDate=unknown

                   | EN  
-------------------+-----
  Pages            |  9  
  Paginator pages  |  0  
  ...
```

Justification: faster resolution of issues such as:
- <https://discourse.gohugo.io/t/image-markdown-render-hook-not-working-on-netlify/32876>
- <https://discourse.gohugo.io/t/image-exif-data-shortcode-nil-pointer-evaluating-resource-resource-relpermalink/32643>

**Comment by bep** [comment]
But only for the initial build.
