### ISSUE TITLE
Syntax highlighting of JavaScript is different under 0.83.1 as compared to 0.82.0

### ISSUE THREAD

**Issue by chalin** [gohugoio/hugo#8532]
After upgrading to Hugo **v0.83.1 (+extended darwin/amd64)** from 0.82.0, I've noticed that leading underscores in JavaScript variable names are formatted differently.

For example, consider this code:

```js
var PROTO_PATH = __dirname + '/../../../protos/route_guide.proto';
```

This is the appearance when built with Hugo 0.83.1:

> <img src='https://user-images.githubusercontent.com/4140793/118200845-16d7dd00-b424-11eb-9cc2-2cd7c2c4c3c9.png' width=550>

Notice how the color of the leading underscore characters (`__`) differs from the color of the rest of the identifier `__dirname`.

cc @nate-double-u

**Comment by chalin** [comment]
The config file for the project I'm observing this for is here: https://github.com/grpc/grpc.io/blob/main/config.yaml. The only difference relative to the [highlighting defaults](https://gohugo.io/getting-started/configuration-markup#highlight), is that the style is set to `manni`.

**Comment by jmooring** [comment]
We updated the [chroma](https://github.com/alecthomas/chroma) syntax highlighter from v0.8.2 to v0.9.1.

I think this is change that is causing the problem:

<https://github.com/alecthomas/chroma/commit/881d54f096b115a34bbaa6585915e3840ec46fcd#diff-12f3e5a2dbe731b9b91b6e604b0f7e1b8928ae8ceaee52b7f014752b25d82005L33-R33>

**Comment by bep** [comment]
To get a fix for this, you need to open up an issue in the Chroma issue tracker: https://github.com/alecthomas/chroma/issues

**Comment by chalin** [comment]
Done: https://github.com/alecthomas/chroma/issues/507

**Comment by chalin** [comment]
> Done: [alecthomas/chroma#507](https://github.com/alecthomas/chroma/issues/507)

And now released! Release https://github.com/alecthomas/chroma/releases/tag/v0.9.4:

- Fixes the problem reported in this issue via https://github.com/alecthomas/chroma/commit/6a6cf1764db914057a47d8fb782924f27dd3a7b9
- Includes support for **console syntax highlighting** (https://github.com/alecthomas/chroma/pull/551)! \o/
