### ISSUE TITLE
> OK, I scratched my head a little here as the upstream library actually both returns the correct message, but also an error ... So, it kind of works even with all of these warnings. OK, that's fixable.

### ISSUE THREAD

**Issue by githubnew-pro** [gohugoio/hugo#8534]
> OK, I scratched my head a little here as the upstream library actually both returns the correct message, but also an error ... So, it kind of works even with all of these warnings. OK, that's fixable.

Oh yes ... I forgot the obvious !!!
I checked and it seems that all my build are correct. So only WARN but nothing wrong (as far i can see) on the builds.

_Originally posted by @divinerites in https://github.com/gohugoio/hugo/issues/8492#issuecomment-830798873_

**Comment by davidsneighbour** [comment]
spam
