### ISSUE TITLE
Support for lastmod in Org Mode timestamp formats

### ISSUE THREAD

**Issue by pprevos** [gohugoio/hugo#8536]
I am using hugo v0.83.1+extended linux/amd64 BuildDate=unknown

Org Mode uses a timestamp format that is only partially 

In [issue 7433](https://github.com/gohugoio/hugo/pull/7433), Hugo was modified so that it could parse Org timestamps in the `.Date` variable. 

This does not seem to work when using the `lastmod` variable. 

Example:

`#+lastmod: 2021-05-15`

Renders as expected.

`#+lastmod: <2021-05-15 Sat>` or `#+lastmod: [2021-05-15 Sat]` does not render as the `.Lastmod` parameter defaults to the `.Date` variable.

Would it be possible to have Hugo recognise Org Mode timestamps for all [frontmatter date formats](https://gohugo.io/getting-started/configuration/#configure-front-matter)?

**Comment by bep** [comment]
Sorry for the late response, yes, we should fix this. I suggest adding `lastmod`, `publishdate` and `expirydate` to that list.

**Comment by pprevos** [comment]
Thanks!

My workaround is to use plain text (`2029-05-16`), but using Org mode (`[2029-05-16]`) dates is neater because it offers other Emacs functionality.

**Comment by AnandaIlyasa** [comment]
Hello @bep , I am a beginner and I would like to take this issue for my first contribution. Could you give me a guidance to work on this issue?

**Comment by johannesengl** [comment]
@bep Created a PR for this. Would appreciate a review :)
