### ISSUE TITLE
Install Method

### ISSUE THREAD

**Issue by rubstudent** [gohugoio/hugo#8537]
There are different descriptions on the github and in the documentation (quickstart, installation) about how to get/install hugo.
None of them mentions that Hugo is available as atp-get package. For me this is the easiest way to get it under ubuntu. Installing Homebrew ist something i dont want and installing go and then installing hugo from the git repo throws me a cannot load io/fs: malformed module path "io/fs": missing dot in path element. I never used go before and i expect the installation to work under a clean ubuntu installation (i test installations in a vm). 

Knowing that it is available in apt (i only checked later) would have saved me quite some time and im wondering why its not listed.

**Comment by jmooring** [comment]
See <https://gohugo.io/getting-started/installing/#debian-and-ubuntu>.

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
