### ISSUE TITLE
Blog Numeration

### ISSUE THREAD

**Issue by rubstudent** [gohugoio/hugo#8541]
I dont like sorting my posts by date but prefer giving them numbers instead as i mostly dont write down the dates. Id like the option to use numbers instead of dates for the blog. I think this would be a good idea.

**Comment by davidsneighbour** [comment]
This is a support request, not a bug. You can sort by weight or any other frontmatter in Hugo.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
