### ISSUE TITLE
.debs missing license metadata

### ISSUE THREAD

**Issue by tidux** [gohugoio/hugo#8555]
Steps to reproduce:

1. Download latest release .deb for your architecture on Ubuntu
2. Open it with a graphical package manager frontend. 
3. notice that the license field says "Proprietary"

This gives a false impression of Hugo being closed source.

**Comment by bep** [comment]
Hmm, we do set it in the config: https://github.com/gohugoio/hugo/blob/f518b4f71e1a61b09d660b5c284121ebf3b3b86b/goreleaser.yml#L148
