### ISSUE TITLE
Plainify summary text in internal meta templates

### ISSUE THREAD

**Issue by shelbyspees** [gohugoio/hugo#8562]
If not a bug, it's at least an interesting quirk. I recently started using [semantic line breaks](https://sembr.org) in all my markdown files, including my blog. I tend to use Hugo's `<!--more-->` feature to [generate a post summary](https://gohugo.io/content-management/summaries/#manual-summary-splitting), and this summary gets used in a number [internal templates](https://github.com/gohugoio/hugo/tree/master/tpl/tplimpl/embedded/templates) for Schema.org, Twitter cards, and OpenGraph metadata. These internal templates are preserving the hard line breaks, which then show up in link previews in chat apps and on social media.

I'll use the example of [a recent blog post I wrote](https://shelbyspees.com/2021/05/19/polywork/) (archived [here](https://web.archive.org/web/20210523012346/https://shelbyspees.com/2021/05/19/polywork/)). Here's [that post's summary text](https://github.com/shelbyspees/website/blame/2949eec63ba4f2f46b1607234d44c4431f7fa49e/content/posts/2021/polywork.md#L14-L19) with semantic line breaks:

```markdown
Back in April I was lucky to get an early invite to
[Polywork](https://www.polywork.com/)
and I'm really liking the platform so far.
If you've ever wished you could point people to a single site that shows
all the cool stuff you've done and some more cool stuff you're working on,
Polywork is for you.
```

The post itself renders fine, but when I shared the post in Discord, the summary text had kept all the hard line breaks:

![screenshot of blog unfurl in discord with seemingly random line breaks in the page summary](https://user-images.githubusercontent.com/5217772/119244932-0ca39600-bb2a-11eb-89a2-81a63812dea0.png)

Definitely not what I was going for. I poked around in devtools on that page and noticed that `<meta name="description" ...>` behaves normally, but `<meta name="twitter:description" ...>` and `<meta itemprop="description" ...>` maintain the hard line breaks.

![screenshot of blog post HTML in Chrome devtools showing one description that looks like normal text, and more descriptions with seemingly random line breaks](https://user-images.githubusercontent.com/5217772/119245189-15956700-bb2c-11eb-8d4b-640ef5a68044.png)

It turns out that in my site's theme, [`<meta name="description" ...>` uses the `plainify` function on the summary](https://github.com/shelbyspees/hugo-theme-hello-friend-ng/blob/413547dacf9fc51c7858c914b8f53a82e7a98b7e/layouts/partials/head.html#L5):

```tpl
<meta name="description" content="{{ if .IsHome }}{{ .Site.Params.homeSubtitle }}{{ else }}{{ .Summary | plainify }}{{ end }}" />
```

Hugo's internal templates for Schema.org, Twitter cards, and OpenGraph don't use plainify on summary text, and that seems to explain why they're all maintaining the hard line breaks, which then get grabbed by third parties and rendered in link previews.

Would it make sense to call plainify on the summary text in these internal templates? If so, I'd be willing to open a PR with the change.

**Comment by chalin** [comment]
I think that this is still relevant because the issue hasn't been resolved, and hopefully will be addressed by #9856 or similar.
