### ISSUE TITLE
Menu items are sometimes excluded when being generated

### ISSUE THREAD

**Issue by binhonglee** [gohugoio/hugo#8567]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

yes

Here's a recording of the repro. Essentially menu items are inconsistently included in the generation (including server command).

https://user-images.githubusercontent.com/16726210/119271679-64d4a980-bbb7-11eb-9bcb-1ca9a05a5414.mp4

Source code: https://github.com/binhonglee/blog

Specifically [`config.toml`](https://github.com/binhonglee/blog/blob/2c34a3919a4dd4b630e267e69d374a51cb6b8093/config.toml#L6) which has menu defined and the [theme partial](https://github.com/binhonglee/CustomPaper/blob/dde545ef752f570868235472ddd27018446e9b2c/layouts/partials/header.html#L65) where `.Site.Menu.main` is referenced.

**Comment by jmooring** [comment]
1\. If you can build Hugo from source, please test again with https://github.com/gohugoio/hugo/commit/785a31b5b84643f4769f9bd363599cbcce86f098 or later.
2\. Please provide a minimal reproducible example. Videos can be helpful to demonstrate a problem, but more is required to identify the cause.

**Comment by jmooring** [comment]
In your config.toml file, change:

```
[Menu]
```

to 

```
[menu]
```

Do the same with the other tables in your configuration.
