### ISSUE TITLE
Mysterious quote mark behaviour by Hugo (undocumented?)

### ISSUE THREAD

**Issue by nabilfreeman** [gohugoio/hugo#8569]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

---

Hi there!

I have found some strange behaviour with quote marks in our Hugo templates. Here's a little example using a phone number string `+447712345678` which I am embedding into some structured data markup.

`"telephone": {{ . }}`

results in

`"telephone": "+447712345678,`

Hugo seems to automatically add quotes when it's inside JSON.

But if you wrap quotes yourself, Hugo behaves differently.

`"telephone": "{{ . }}",`

results in

`"telephone": "\u002b447712345678",`

It's now escaped the + sign and knows not to wrap the string in quotes. I think this is rather odd as it doesn't seem to be documented, demonstrates some awareness of the content it's inside rather than being than being a pure templating lang and it makes me worry about the predictability of Hugo in edge cases like this.

Is there any explanation for the above? Thank you!

P.s. Hugo is awesome 💥

**Comment by nabilfreeman** [comment]
I found a semi-related issue #8266 which was closed. Maybe it's a similar reason?

**Comment by bep** [comment]
The behaviour you see is Go HTML templates in action, which is probably well documented upstream. That said, I suspect you would have it easier if you created these JSONs using something ala:

```
{{ $data := dict "telephone" ""+447712345678" "name" "foo" }}
{{ $json := $data | jsonify }}
```
