### ISSUE TITLE
os.Stat fails on empty JSON file. 

### ISSUE THREAD

**Issue by eazolan** [gohugoio/hugo#8571]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1-5AFE0A57 windows/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

> Yes

I'm trying to get Hugo to ignore a data file if it's empty. But when running os.Stat on an empty JSON file, it dies. I think it's failing the "Is this really a JSON file" check.

Adding [{}] to the JSON file allows the the server to come up and run.

```
{{ $ga_stat := os.Stat "data/GA_status.json" }}
{{ if gt $ga_stat.Size 4 }}
```

I don't think this is limited to JSON files. When I was testing this, I think I had the same problem with CSV files with no data in them. But I didn't take notes on that.

**Comment by jmooring** [comment]
@eazolan I am unable to reproduce the problem. 

> when running os.Stat on an empty JSON file, it dies

What does this mean? Is there an error message?

**Comment by eazolan** [comment]
This is the error I get from the command line when the JSON starts out correct, but is replaced with an empty file. Which happens when the database has no data to output:

> Watching for changes in C:\Users\d4zolae\Desktop\webdev\Hugo\{archetypes,content,data,layouts,static,themes}
> Watching for config changes in C:\Users\d4zolae\Desktop\webdev\Hugo\config.toml
> Environment: "development"
> Serving pages from memory
> Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
> Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
> Press Ctrl+C to stop
> 
> Change detected, rebuilding site.
> 2021-05-25 14:33:40.481 -0600
> Data changed "C:\\Users\\d4zolae\\Desktop\\webdev\\Hugo\\data\\GA_status.json": WRITE
> Total in 4 ms
> ERROR 2021/05/25 14:33:40 Rebuild failed:
> 
> ERROR 2021/05/25 14:33:40 Failed to load data: failed to load data: unmarshal failed: unexpected end of JSON input

This is from the web page:
> Rebuild failed:
> 
> Failed to load data: failed to load data: unmarshal failed: unexpected end of JSON input
> hugo v0.83.1-5AFE0A57 windows/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
> 
> Reload Page

**Comment by jmooring** [comment]
How is this is related to `os.Stat`?

**Comment by davidsneighbour** [comment]
You need to check if your string is empty before trying to unmarshal it. Not a bug.

**Comment by eazolan** [comment]
> How is this is related to `os.Stat`?

Going over it with you, it looks like it has more to do with Hugo checking the data directory for valid data files. Is there a more precise phrasing for that? I can edit the bug report title.

**Comment by eazolan** [comment]
> You need to check if your string is empty before trying to unmarshal it. Not a bug.

You can't check any of the data in the file if Hugo thinks the data file is inactive. How do you check a string that Hugo won't look at?

**Comment by jmooring** [comment]
This will ensure that (a) the file exists, and (b) the file is not empty.

```
{{ $f := "data/foo.json" }}
{{ if fileExists $f }}
  {{ if ne (os.Stat $f).Size 0 }}
    {{ range $k, $v := site.Data.foo }}
      {{ $k }} = {{ $v }}<br>
    {{ end }}
  {{ end }} 
{{ end }} 
```

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
