### ISSUE TITLE
math.div not working

### ISSUE THREAD

**Issue by tnatanael** [gohugoio/hugo#8572]
### hugo 0.83.1
hugo-bin 0.71.1

<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release?
yes

I get this error when compiling bootstrap docs, i used math.div in my code in detriment of standard sass / operator.

Error: Error building site: TOCSS: failed to transform "scss/docs.scss" (text/x-scss): SCSS processing failed: file "/home/dev/projects/bootstrap/scss/_functions.scss", line 227, col 15: Invalid CSS after "  @return math": expected expression (e.g. 1px, bold), was ".div($v1, $v2);" 
ERROR: "docs-build" exited with 255.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
