### ISSUE TITLE
Strange behavior of .Permalink when relativeURLS: true 

### ISSUE THREAD

**Issue by sot-tech** [gohugoio/hugo#8580]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1-5AFE0A57+extended linux/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
yes

Configuration set to:
```yaml
relativeURLS: true 
canonifyURLs: false
```

There is sample layout snippet:
```html
{{ define "body-class" }}template-search{{ end }}
{{ define "head" }}
    {{- with .OutputFormats.Get "json" -}} 
		<b>{{/* GOOD href: '../search/index.json' !!!*/}}</b>
        <link rel="preload" href="{{ .Permalink }}" as="fetch" crossorigin="anonymous">
    {{- end -}}
{{ end }}

{{ define "main" }}
<b>{{/* GOOD action: '../search/', BUT BAD data-json: '/search/index.json' */}}</b>
<form action="{{ .Permalink }}" class="search-form"{{ with .OutputFormats.Get "json" -}} data-json="{{ .Permalink }}"{{- end }}>

{{/* ... */}}

{{ end }}
```

Expected:
```html
<link rel=preload href=../search/index.json as=fetch crossorigin=anonymous>
<!-- ... -->
<form action=../search/ class=search-form data-json=../search/index.json>
```

Got:
```html
<link rel=preload href=../search/index.json as=fetch crossorigin=anonymous>
<!-- ... -->
                                               <!--↓↓ there's no 'relative' -->
<form action=../search/ class=search-form data-json=/search/index.json>
```

Itried `{{ .RelPermalink }}`, `{{ .RelPermalink | relURL }}`,  `{{ .Permalink | relURL }}`, `{{ relURL .Permalink }}` (_by the way, what the difference between last 2 ways?_), result the same.
It's okay when site located in root context (_http://example.local_), but in subpath (_http://example.local/test_) there is an 404 because of invalid link.

**Comment by jmooring** [comment]
First, your sample layout snippet uses `.Permalink`. This will _always_ generate an absolute URL, regardless of the `relativeURLs` configuration setting. From the [documentation](https://gohugo.io/getting-started/configuration/#all-configuration-settings):

> relativeURLs (false)
> Enable this to make all relative URLs relative to content root. **Note that this does not affect absolute URLs.**

Second, with this template code:

```html
<form action="{{ .RelPermalink }}" data-json="{{ .RelPermalink }}">
```

the URL in the `action` attribute will be transformed, but the other URL will remain untouched. URL transformations are limited to the the `src`, `href`, `url`, `action`, and `srcset` attributes.

Third, to answer your question, "What the difference between last 2 ways?" please read:
<https://gohugo.io/templates/introduction/#pipes>

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
