### ISSUE TITLE
Replace underlying Exif library 

### ISSUE THREAD

**Issue by chrillek** [gohugoio/hugo#8586]
I suggest to replace the current Exif library, which has not been worked on in the last two years and poses some problems with 
https://github.com/dsoprea/go-exif
That one is actively developed and seems to be able to read IPTC data, too. Which would open up a lot more possibilities for image handling.
Cf. https://discourse.gohugo.io/t/chance-of-changing-the-exif-module/33112

**Comment by bep** [comment]
I have labeled this `GoodFirstIssue`, which I'm not totally sure about -- but it's a very isolated issue that does not require deep knowledge of Hugo's internals. 

Anyhow, PR is welcome.

We should try to preserve the existing API if possible. If we need to extend it for the IPTC data, we will do that.

**Comment by danedavid** [comment]
Hi, I'd like a shot at this.
From what I understand we need to remove [this possibly outdated Exif library](https://github.com/rwcarlsen/goexif) and add a new one, possibly https://github.com/dsoprea/go-exif , update all imports while keeping the API same, right?

**Comment by bep** [comment]
>update all imports while keeping the API same, right?

Yes, that would be a good approach.

**Comment by serhack** [comment]
Any news?

**Comment by bep** [comment]
https://github.com/dsoprea/go-exif doesn't seem to. be maintained, so this issue is in waiting mode, I guess.

**Comment by serhack** [comment]
Thanks for the update

**Comment by bronger** [comment]
Off-topic: FWIW, I find go-exif very hard to understand and to handle, mostly because it lacks _complete_ examples and because (at least I) fail to find high-level functions. It feels a little bit like assembler. Possibly, you’ve had a similar impression, and if so, have you considered alternatives? I would love to hear about them.

**Comment by bep** [comment]
@bronger I agree about what you're saying. I was only considering go-exif because it actually made some of our failing test cases pass ... I don't know of any current great options, though, but I'm a little surprised, as this should not be rocket science.
