### ISSUE TITLE
Multi Host support - Allow BaseURL to generate dynamically at runtime - window.location.hostname

### ISSUE THREAD

**Issue by Simonl9l** [gohugoio/hugo#8587]
# Proposal
 Would it be possible to have a backwards compatible option to instead have the BaseURL use `window.location.hostname` and `window.location.protocol` via JS in the client to construct the URL's dynamically to the resources in the page headers.

One can ensure ones host/domain does can not generally get spoofed with CORS `allowed-origins` configurations (given extensive browser support).

# Background

I get to DevOps components that other team members put together. I'm new to Hugo so please excuse my possible ignorance of capabilities but have searched the discourse forum and here before submitting this issue/proposal.

As I understand it today the BaseURL is used in the build process and that value is rendered/hard coded into the links in `index.html` another HTML page headers for the various resources, js, css, fonts etc.

This means that one can't deploy a given build to multiple hosts. It's build per host?

Say as part of a DevOps I want to deploy to an s3 container for each environment. The development CI/CD environment is only accessible form internal networking as say `http://mysite.<environment>.internal_dns_name` and for other environment its also available publicly via `http://mysite.<environment>.my_public_domain.com` that is served up via cloudfront.

_*Note: production <environment> is empty (omitting extra period) for production._
We use this pattern extensively with other runtimes for other deployed components, however this does not appear possible with Hugo. 

We depend on this pattern to switch users between different components based on various cnames. Such that one can take ones current `window.location.hostname` and peel off the cname and and another an open a new window or redirect to that new host name. We also use the `window.location.protocol`to construct the target url such that we keep protocols in sync - we don't use https for our internal hosts.

This also helps in a whitelisted service offering scenario. One then just need to do DNS foo - not manage multiple deployments of essentially the same site.

**Comment by bep** [comment]
Hugo is a static site generator, so that's not possible.

**Comment by Simonl9l** [comment]
@bep As followup...seem all I needed to do was remove any mention of `baseurl` in any of the `config.toml` files and this remove that configuration base url from any generated links, such that all links then start with a `/` and will then root from the active host.

This might help other struggling with the same issue as a newbie, and better response than `that's not possible`.
