### ISSUE TITLE
Environment Variable with html is split by '=' in config.SplitEnvVar.

### ISSUE THREAD

**Issue by xqbumu** [gohugoio/hugo#8589]
can't pass Environment Variable with html, because the variable is split by config.SplitEnvVar with '='.

i will fix it with pr later.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

yes

**Comment by bep** [comment]
Why do you need HTML in env variables?
