### ISSUE TITLE
Support an operator for chaining multiple go-template commands in a single mustache

### ISSUE THREAD

**Issue by atishay** [gohugoio/hugo#8597]
In the latest Hugo version, we can have newlines in the template code. This allows us to write multiline template code. The only piece missing to enable using go template as a language for longer programming constructs is the ability to write multiple independent functions. Adding an operator to chain commands could make this a reality. 

A suggestion would be use *semi-colons*, popular as line terminators in a lot of programming languages, unused in Hugo so far.

Would love to write something like the following:

```
{{
      with site.Title;
            printf "%s" (. | humanize);
     else;
          printf "No title";
     end;
}}
```

equivalent to:

```
{{with site.Title}}
    {{printf "%s" (. | humanize)}}
{{else}}
  {{printf "No title"}}
{{end}}
```

If we want to stick to the prefix format for operators, it is okay to have ; as a starting parameter as well. We could mentally think of `{{;  ;}}` as multi command template while internally it is `{{; function 1 ; function 2; noop}}` in the prefix format.

**Comment by bep** [comment]
You need to raise this issue upstream (Go stdlib), but I suspect it will most likely be discarded.

**Comment by atishay** [comment]
Created https://github.com/golang/go/issues/46588

**Comment by jmooring** [comment]
The upstream issue was [declined](https://github.com/golang/go/issues/46588#issuecomment-880097914).
