### ISSUE TITLE
Add image dithering filter to build low-tech websites

### ISSUE THREAD

**Issue by rdelaage** [gohugoio/hugo#8598]
It would be great to be able to select a filter to dither image and reduce final website size in image processing. The [lowtech magazine](https://solar.lowtechmagazine.com/) use a filter to dither images. We could have the same in hugo by using [this library](https://github.com/makeworld-the-better-one/dither) and it could be selecting in [image processing](https://gohugo.io/content-management/image-processing/) filters.

**Comment by bep** [comment]
We could add this **if we could do it by not adding another dependency**. I think the standard library has a simple dithering filter, which I think should be good enough for this.

**Comment by diantanjung** [comment]
I want to solve this issue

**Comment by diantanjung** [comment]
hi @bep 
Is there any documentation for debugging and testing for hugo project? I have changed in filter.go add add some file. But after I run mage install, the change does not work. Is I miss something?

**Comment by diantanjung** [comment]
Ok, Please explain the features of the dithering image. If any input and output images will be very helpful.

**Comment by bep** [comment]
I don't have any stake in this other than that I'll most likely end up maintaining what's added. But I was originally thinking about using `draw.FloydSteinberg` ... but I haven't researched this.

https://golang.org/pkg/image/draw/

**Comment by diantanjung** [comment]
https://github.com/disintegration/gift/issues/25

**Comment by diantanjung** [comment]
hi bep, Could I use `draw.FloydSteinberg` (but I modified it) to implement `gift.Filter`? 
Or Is there another approach?

thanks
