### ISSUE TITLE
Improve pagination performance

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#8599]
The [embedded pagination template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/pagination.html) ranges through every pager while rendering every pager. The number of iterations increases quadratically in relation to the number of content pages.

n = (c/p)^2 where

- n = iterations
- c = content pages
- p = content pages per pager

Using the default number of content pages per pager (10):

Content Pages|Iterations
--:|--:
100|100
1,000|10,000
10,000|1,000,000
25,000|6,250,000
50,000|25,000,000
75,000|56,250,000

There have been a couple of related forum issues over the past month:
- <https://discourse.gohugo.io/t/slow-build/32745>
- <https://discourse.gohugo.io/t/build-performance/33093>

PR to follow...

**Comment by bep** [comment]
I don't understand the math above.

* The template ranges over every pager every time it's built
* But paginators are only available to list pages (e.g. sections and the home page) which should be a small number compared to the total?

**Comment by jmooring** [comment]
Let's say there are 10,000 posts.
And we use the default `paginate` value of 10.
And there is one list template, layouts/_default/list.html.

The list template is called 1000 times in order to generate:

```text
public/post/page/1
└── index.html
public/post/page/2
└── index.html
...
...
public/post/page/1000
└── index.html
```

Each time the list template is called, it calls the pagination template.

Each time the pagination template is called, it does this:

```
{{ range .Paginator.Pagers }}
  ...
{{ end }}
```

And `.Paginator.Pagers` contains 1000 items.

**Comment by jmooring** [comment]
I've got a candidate fix, but it still needs some fine tuning. Performance gains are promising...

Testing a site with 10,000 pages. One list page is paginated, with 10 content pages per pager.

ID|Description|Average of 3 runs (seconds)
:--|:--|:--
1|No pagination|1.6
2|Existing embedded pagination template|20.1
3|New pagination template|1.9
