### ISSUE TITLE
Hugo crashes when adding invalid data file to data directory.

### ISSUE THREAD

**Issue by eazolan** [gohugoio/hugo#8601]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1-5AFE0A57 windows/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes.

Hugo server crashes when:
1. You use JSON files in your data directory
2. AND you add a new 0 byte JSON file, or change one of the JSON files to 0 bytes

When you add a new 0 byte file, you don't even have to reference it in your code. I think Hugo is evaluating it for validity.

I've gone over this on the Hugo discourse page with another: https://discourse.gohugo.io/t/hugo-crashes-when-theres-a-data-file-with-no-data-in-it/33189/4

**Comment by FrappeFortyTwo** [comment]
Hey, I've made a PR for this issue [here](https://github.com/gohugoio/hugo/pull/8603). Looking for feedback.

P.S It's my first contribution here.

**Comment by ReCodee** [comment]
is this issue still relevant?
If yes, then I'd like to work on this issue
