### ISSUE TITLE
post does not use url defined in section frontmatter

### ISSUE THREAD

**Issue by shermelin** [gohugoio/hugo#8614]
### What version of Hugo are you using (`hugo version`)?
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2021-06-06T22:08:35Z (debian 0.80.0-6+b4)

### Does this issue reproduce with the latest release?
Not sure, I cannot get go to properly install hugo from source...

First of all, thanks for the great work on hugo! It allowed us to set up our web site.

Regarding my issue, we have a multilingual site (english, french), with the following content organisation:

```
content
    |--- section1
    |           |--- _index.fr.md
    |           |--- _index.en.md
    |           |--- post1
    |           |        |--- index.fr.md
    |           |        |--- index.en.md
    |           |--- post2
    |           |        |--- index.fr.md
    |           |        |--- index.en.md
```

We define the url for "section1" in _index.en.md so that the section nicely appears translated in english in the url, navigation bar...

However, when we go on the pages for the posts, the url used switches back to the folder name. Defininf "url" in _index.fr.md" in addition does not help.

This is not the expected behaviour to me and I do not want to hardwire the url in all my subposts...

Thanks for considering this issue.

**Comment by jmooring** [comment]
Specify the `url` in the front matter for section pages, and use the [permalinks](https://gohugo.io/content-management/urls/#permalinks) configuration for content pages. To define a permalink for a particular language, place it under the language key in the site configuration.

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
