### ISSUE TITLE
Markdown render hook for code blocks

### ISSUE THREAD

**Issue by janoszen** [gohugoio/hugo#8637]
It would be nice to be able to customize code block rendering similar to [how links and images can be customized](https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks).

## Use case

This would allow for creating customized code display blocks, e.g. full width code blocks in otherwise non-full width containers, etc. without the use of short codes.

**Comment by jmooring** [comment]
Duplicate of https://github.com/gohugoio/hugo/issues/8520
