### ISSUE TITLE
Could I add Front Matter auto based on markdown file information

### ISSUE THREAD

**Issue by starsareintherose** [gohugoio/hugo#8638]
Could I add Front Matter auto based on markdown file information?
I would export some notes from my markdown notebook, I want to auto-use them to hugo. any solution?

**Comment by jmooring** [comment]
You can set any of the dates (`date`, `expiryDate`, `lastmod`, or `publishDate`) by:

a) Extracting if from the filename, or
b) Using the last modification timestamp from the file system, or
c) Using the git author date

See <https://gohugo.io/getting-started/configuration/#configure-dates>.

You cannot set `.Title` automatically, although this has been requested before:

- <https://github.com/gohugoio/hugo/issues/1116>
- <https://github.com/gohugoio/hugo/issues/3390>
- <https://github.com/gohugoio/hugo/issues/3805>
- <https://github.com/gohugoio/hugo/issues/4341>
- <https://github.com/gohugoio/hugo/issues/6098>
- <https://github.com/gohugoio/hugo/issues/7370>
- <https://github.com/gohugoio/hugo/issues/7666>
- <https://github.com/gohugoio/hugo/pull/3859>
- <https://github.com/gohugoio/hugo/pull/4359>
- <https://github.com/gohugoio/hugo/pull/5337>

If it were me, I would write a short script to prepend frontmatter to the exported files.

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
