### ISSUE TITLE
Set Asciidoc attributes by language

### ISSUE THREAD

**Issue by dbaio** [gohugoio/hugo#8640]
Hi.

Is there a way to set Asciidoc attributes by languages?

I'm doing this:
config/_default/languages.en.toml:
<pre>
[markup.asciidocext.attributes]
    lang = "en"
</pre>

config/_default/languages.pt-br.toml:
<pre>
[markup.asciidocext.attributes]
    lang = "pt-br"
</pre>

But it always adds the same attribute value, in this case, `pt-br`.

<pre>
INFO 2021/06/13 16:46:11 Rendering articles/example/_index.adoc with /usr/local/bin/asciidoctor using asciidoctor args [-a lang=pt-br --no-header-footer -] ...
</pre>

Thank you!

**Comment by jmooring** [comment]
The only thing I could find in the [documentation](https://gohugo.io/content-management/multilingual/):

> Only the obvious non-global options can be overridden per language. Examples of global options are baseURL, buildDrafts, etc.

I'm not sure what this means, but I suspect the `[markup]` key is considered global.

**Comment by bep** [comment]
>Is there a way to set Asciidoc attributes by languages?

No.

**Comment by dbaio** [comment]
Thank you for the answers.
Is this a complicated thing? Do you have any guidance here, please?

**Comment by jmooring** [comment]
What do you wish to achieve by calling asciidoctor with `-a lang=xx`?

**Comment by dbaio** [comment]
> What do you wish to achieve by calling asciidoctor with `-a lang=xx`?

Thanks for asking.

The FreeBSD Documentation has two main areas, Documentation (several books and articles) and Website [1].

We recently migrated it from Docbook to Hugo/Asciidoctor. It's very extensive, we have about 1k .adoc files.

And now we want to add several includes based on each language [2].

One example:

```
include::shared/en/urls.adoc[]
include::shared/pt-br/urls.adoc[]
```
-->

```
ifdef::lang[include::shared/{lang}/urls.adoc[]]
```
there are other files like this.

We use for translations `po4a` and `Weblate`, and these include's with $lang (which aren't translatable) will help because we won't need to change it manually after converting the translation (`.po` file) back to `.adoc`.

That's why we need that `-a lang=xx` parameter or another way to pass Hugo variables to Asciidoctor.

Any tip/advice here is very appreciated. 
And thanks for your time.

1 - https://github.com/freebsd/freebsd-doc
2 - https://raw.githubusercontent.com/freebsd/freebsd-doc/main/documentation/content/en/articles/committers-guide/_index.adoc

**Comment by jmooring** [comment]
layouts/shortcodes/lang.html

```
{{ .Page.Language.Lang }}
{{- /* Chomp trailing newline */ -}}
```

And then your include might look like this:

```
include::shared/{{% lang %}}/urls.adoc[]
```

**Comment by dbaio** [comment]
@jmooring that will help, thank you so much.

**Comment by jmooring** [comment]
You are welcome. In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks!
