### ISSUE TITLE
dot `.` cannot be used in heading id

### ISSUE THREAD

**Issue by reorx** [gohugoio/hugo#8648]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

## Problem: dot `.` cannot be used in heading id

markdown:
```
## My Heading {#foo.bar.baz}
```

html:
```
<h2 id="foo" class="bar baz">My Heading</h2>
```

According to the document of goldmark: https://github.com/yuin/goldmark/#attributes
the syntax of declaring id and attributes to heading is `{#id .className attrName=attrValue class="class1 class2"}`,
but when hugo renders it, `#foo.bar.baz` is not treated as a whole HTML id, instead, `.bar` `.baz` are parsed as class names despite there's no spaces in between.

The expected result is `<h2 id="foo.bar.baz">`, and if class name is added, i.e. `{#foo.bar.baz .qux}`, the result should be `<h2 id="foo.bar.baz" class="qux">`.

**Comment by bep** [comment]
Thanks for the report. This looks like it could be an issue with Goldmark. Could you create an issue at https://github.com/yuin/goldmark/issues and link back to this issue so we could track it?

**Comment by reorx** [comment]
Sure, I was intented to post the issue in goldmark, but the questions they asked for new issues are too complicated 😅, I didn't have enough time to validate, so I just posted it here as a memo. I'll reproduce this problem by goldmark library later after working hours :)

**Comment by bep** [comment]
I suspect this issue as described above should be enough for him.
