### ISSUE TITLE
Cannot access .Name in if .HasChildren

### ISSUE THREAD

**Issue by Corfucinas** [gohugoio/hugo#8649]
### What version of Hugo are you using (`hugo version`)?
hugo v0.84.0-DEV+extended linux/amd64 BuildDate=unknown

### Does this issue reproduce with the latest release?

Yes, commit `d392893cd7` has the problem

------------

Seems pulling the latest commit on master has some bug, building my website with commit `d392893cd7` makes this code not produce anything

```
<ul class="navbar-nav">
          {{ range .Site.Menus.main }}
          {{ if .HasChildren }}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              {{ .Name }}
            </a>
            <div class="dropdown-menu">
              {{ range .Children }}
              <a class="dropdown-item" href="{{ .URL | absURL }}">{{ .Name }}</a>
              {{ end }}
            </div>
          </li>
          {{ else }}
          <li class="nav-item">
            <a class="nav-link" href="{{ .URL | absURL }}">{{ .Name }}</a>
          </li>
          {{ end }}
          {{ end }}
        </ul>
```

Section is missing

![image](https://user-images.githubusercontent.com/53630064/122021520-4f3e5280-cdf8-11eb-9c4e-6824874e7f86.png)

**But if I build it with the previous commit `a886dd53b8032` , it works**

![image](https://user-images.githubusercontent.com/53630064/122021271-1aca9680-cdf8-11eb-84b9-7c4112fd767f.png)

**Comment by jmooring** [comment]
I was not able to reproduce this problem with d392893 when the menu entries are defined in the site configuration.

```bash
git clone --single-branch -b hugo-github-issue-8649 https://github.com/jmooring/hugo-testing hugo-github-issue-8649
cd hugo-github-issue-8649
hugo server
```

**Comment by bep** [comment]
@Corfucinas can you please clean up the title of this issue; a short description about what the issue is about, remove any conclusion/label ("bug") and commit reference. Thank you.
