### ISSUE TITLE
Footnote not rendering correctly in shortcodes

### ISSUE THREAD

**Issue by KevinWang15** [gohugoio/hugo#8656]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

---

### Markdown to reproduce this issue

```markdown

Hello world [^1]

{{< figure src="http://lorempixel.com/400/200" caption="**footnote** will not render here [^2]" >}}

[^1]: Footnote 1
[^2]: Footnote 2

```

### Result

![image](https://user-images.githubusercontent.com/10173472/122336902-1cb76580-cf70-11eb-9a86-786eb3ac4fd5.png)

---

I would expect Footnote 2 (which was `markdownify`ed in the shortcode) to render correctly too.

I understand it may be due to that we don't have the context in shortcode markdownify, but is there any workaround to this? I use custom shortcode and footnote a lot, I would very much appreciate it if I could get footnote to work in shortcode.

**Comment by davidsneighbour** [comment]
Markdownify will not show up in the "global scope" of the page. Using .RenderString will probably work. 

https://gohugo.io/functions/renderstring/#readout

This is a support request, please use the Hugo Discourse next time.

**Comment by KevinWang15** [comment]
Thanks for the quick reply @davidsneighbour , I will use Discourse next time.

Regretfully, I wasn't able to get `.RenderString` to work..

### layouts/shortcodes/test.html

```html
<div>
    {{ .Inner | .Page.RenderString }}
</div>
```

### content/posts/my-first-post.md

```markdown
---
title: "My First Post"
date: 2021-06-17T13:16:04+08:00
draft: true
---

Hello world [^1]

{{< test >}}
**footnote** will not render here [^2]
{{< /test >}}

[^1]: Footnote 1
[^2]: Footnote 2
```


### result

![image](https://user-images.githubusercontent.com/10173472/122341688-59865b00-cf76-11eb-992b-63f51346b8a9.png)

**Comment by jmooring** [comment]
If you really want to do this...

#### Step 1 - Change site configuration

```toml
[markup.goldmark.renderer]
unsafe = true
```

#### Step 2 - Create custom figure shortcode

layouts/shortcodes/myfigure.html

```html
<figure{{ with .Get "class" }} class="{{ . }}"{{ end }}>
  {{- if .Get "link" -}}
    <a href="{{ .Get "link" }}"{{ with .Get "target" }} target="{{ . }}"{{ end }}{{ with .Get "rel" }} rel="{{ . }}"{{ end }}>
  {{- end -}}
  <img src="{{ .Get "src" }}"
    {{- if .Get "alt" }}
    alt="{{ with .Get "alt" }}{{ . }}{{ end }}"
    {{- end -}}
    {{- with .Get "width" }} width="{{ . }}"{{ end -}}
    {{- with .Get "height" }} height="{{ . }}"{{ end -}}
  /><!-- Closing img tag -->
  {{- if .Get "link" }}</a>{{ end -}}
  <figcaption>
    {{ with (.Get "title") -}}
      <h4>{{ . }}</h4>
    {{- end }}
    {{ .Inner }}
    {{- if .Get "attr" -}}<p>
      {{- with .Get "attrlink" }}
        <a href="{{ . }}">
      {{- end -}}
      {{- .Get "attr" | markdownify -}}
      {{- if .Get "attrlink" }}</a>{{ end }}</p>
    {{- end }}
  </figcaption>
</figure>
```

#### Step 3 - Markdown

```md
Hello world [^1]

{{% myfigure src="https://place-puppy.com/400x200" %}}
**footnote** will not render here [^2]
{{% /myfigure %}}

[^1]: Footnote 1
[^2]: Footnote 2
```

**Comment by KevinWang15** [comment]
@jmooring Thank you so much!

It seems that using `{{% .. %}} {{% /.. %}}` instead of `{{< .. >}} {{< /.. >}}`, and using `{{ .Inner }}` without `markdownify` or `.Page.RenderString` solves the problem.

`goldmark` seems to be the only MarkdownHandler to do this.

This saved my day 👍 👍
