### ISSUE TITLE
Shortcode content rendered inside markdown list under certain circumstances

### ISSUE THREAD

**Issue by masbaehr** [gohugoio/hugo#8657]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.83.1-5AFE0A57+extended windows/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

To reproduce you can use the following code. I'm not entirely sure what triggers this. If I do 2 CR/LF it works correctly. So please advice if i'm doing something wrong or if this may be a bug in the markdown processor  - or maybe related to some windows/linux cr/lf problem. Thanks

shortcode: specialp.html
```
<p style="font-style: italic; font-weight: bold;">{{index .Page.Params.special}}</p>
```

test markdown
```
---
special: "my special text"
---
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
- xxxxxxxxxxxxxx 
- xxxxxxxxxxxxxx
- xxxxxxxxxxxxxx
- xxxxxxxxxxxxxx
- xxxxxxxxxxxxxx
- xxxxxxxxxxxxxx
​
{{<specialp >}}
```
![image](https://user-images.githubusercontent.com/38694044/122346413-35f8eb80-cf49-11eb-8c0f-1c9e9028757c.png)

**Comment by davidsneighbour** [comment]
[Discourse](https://discourse.gohugo.io) - that is a note you should have seen when opening this bug report that is not a bug.

`index` works differently from what you are doing there. It's `index collection indexid`. So it would be `index .Page.Params "special"`. But as I wrote: Open your SUPPORT REQUESTS at the place the links when you opened this issue told you to.

**Comment by masbaehr** [comment]
Sorry for posting. Won't do again. I was convinced this was some bug. By the way it was completely unrelated to the wrong usage of index, but was caused by an invisible ZERO-WIDTH-SPACE between the CR LF. So after removing it , it is working 

![image](https://user-images.githubusercontent.com/38694044/122414414-6bbcc500-cf87-11eb-8114-fad649f75d38.png)
