### ISSUE TITLE
releaser: Update from Goreleaser 0.156.2 to  0.169.0 broke the release build

### ISSUE THREAD

**Issue by sephore** [gohugoio/hugo#8665]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.84.0-2C4689F7 linux/amd64 BuildDate=2021-06-18T14:55:54Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes. Just tried to download the `hugo_extended_0.84.0_Linux-64bit`, but it doesn't seem to be the extended version (can't build SCSS/SASS).

```
Start building sites … 
hugo v0.84.0-2C4689F7 linux/amd64 BuildDate=2021-06-18T14:55:54Z VendorInfo=gohugoio
Built in 798 ms
Error: Error building site: TOCSS: failed to transform "css/main.scss" (text/x-scss). Check your Hugo installation; you need the extended version to build SCSS/SASS.
```

**Comment by davidsneighbour** [comment]
Your version does not say it's extended. So it's not. What's the problem?

**Comment by sephore** [comment]
But I downloaded the `hugo_extended_0.84.0_Linux-64bit`...? Shouldn't it be the extended version?

**Comment by davidsneighbour** [comment]
Your `hugo --version` says no. You either did not install it properly or your path is not pointing to the extended version.

Extended should look like this:

```
hugo v0.83.1-5AFE0A57+extended linux/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
```

note the `+extended` in the name.

**Comment by jmooring** [comment]
I have confirmed the problem.

**Comment by sephore** [comment]
Thanks @jmooring !

I was SERIOUSLY starting to question my sanity...

**Comment by bep** [comment]
I'm in the process of fixing this; it's probably an upstream Goreleaser bug (or a breaking change I didn't catch), but that is a worry for another day (I'll repurpose this issue to track that). But there will be new binaries up soon.

**Comment by bep** [comment]
New and correct binaries are now up.

**Comment by bep** [comment]
@caarlos0 at first glance, do you have an idea what this can be? Bug in Goreleaser? I updated from 0.156.2 to 0.169.0, and now the binary IDs seem to be mangled (the first binary end up in both archives): https://github.com/gohugoio/hugo/blob/a7e3da242f98d4799dad013d7ba2f285717640d6/goreleaser.yml#L74

**Comment by caarlos0** [comment]
@bep probably this https://github.com/goreleaser/goreleaser/issues/2300

will do a new release right away

**Comment by caarlos0** [comment]
https://github.com/goreleaser/goreleaser/releases/tag/v0.170.0 

released, sorry for the inconvenience 🙏

**Comment by bep** [comment]
>released, sorry for the inconvenience 🙏

No problem. Having created so many stupid bugs myself have made me very tolerant to towards upstream bugs.
