### ISSUE TITLE
Missing binaries in release assets 0.84.0

### ISSUE THREAD

**Issue by peaceiris** [gohugoio/hugo#8666]
https://github.com/gohugoio/hugo/releases/tag/v0.84.0

![Screen Shot 2021-06-19 at 1 48 26](https://user-images.githubusercontent.com/30958501/122593358-80d94700-d0a0-11eb-8937-2440866853c5.png)

**Comment by peaceiris** [comment]
I think that dep is trying to fix #8665

**Comment by bep** [comment]
I'm in the process of fixing this; it's probably an upstream Goreleaser bug (or a breaking change I didn't catch), but that is a worry for another day.

**Comment by bep** [comment]
Yes, I deleted the binaries ... there will come another set soon.
