### ISSUE TITLE
Add .ContentMap.Headings

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8670]
See #8643 and other related discussions.

We have talked about this before, but I suggest that we just start out with the ToC.

This is the current ToC type:

```go
type Headings []Heading

type Heading struct {
	ID   string
	Text string

	Headings Headings
}
```

* We should probably add `Level` to the above
* Is `.ContentMap` a good top level name for this data? Assuming we add more later.

With that you should be able to render a ToC with a recursive template ...

```
{{ template "render-headings" .ContentMap.Headings }}

{{ define "render-headings }}
{{ range . }}
{{ .Text}}
{{ template "render-headings" .Headings }}
{{end }}
{{ end }}
{{ end }}
```

**Comment by jmooring** [comment]
Is this related to https://github.com/gohugoio/hugo/issues/5087?

**Comment by bep** [comment]
Yes.
