### ISSUE TITLE
Add pride shortcode

### ISSUE THREAD

**Issue by earlng** [gohugoio/hugo#8675]
I want to introduce a shortcode that will change the font color of the included text to depict the pride-rainbow. 

I've already developed a simple `.html` shortcode that works on my site. This is the markdown input:
```
{{< pride >}}And what could be more beautiful than love?{{< /pride >}}
```
Here is the [output](https://imgur.com/a/YxyEoDx).

I would like to create a PR to add it to hugo. I've already forked the repo, but I found that there are 3 different shortcode directories:

1. `\hugo\docs\layouts\shortcodes`
2. `\hugo\docs\_vendor\github.com\gohugoio\gohugoioTheme\layouts\shortcodes`
3. `\hugo\tpl\tplimpl\embedded\templates\shortcodes`

Do I need to add the `pride.html` file to all 3 of these folders?

I've also read the contribution guide, but I didn't see if there was any other additional requirements I need to do specifically for shortcode contributions?

Sorry for the trouble, and thank you for the help!

**Comment by jmooring** [comment]
@earlng Nicely done. Instead of a PR, you should create a "Tips and Tricks" topic on the Hugo forum (https://discourse.gohugo.io/). But do it soon---it's June!

**Comment by earlng** [comment]
@jmooring you mean add an entry on the forum of how a user could introduce the shortcode in their installations manually?

**Comment by jmooring** [comment]
Yes. Include the template code and show how to call it from markdown.

**Comment by earlng** [comment]
I see. Added an entry in the forum.

The link is [here](https://discourse.gohugo.io/t/pride-shortcode/33473) for the curious. Thanks!
