### ISSUE TITLE
Merge configuration, but not from non-modules

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#8676]
### What version of Hugo are you using (`hugo version`)?

<pre>
❯ hugo version
hugo v0.84.0-2C4689F7B+extended linux/amd64 BuildDate=2021-06-18T17:14:27Z VendorInfo=gohugoio
</pre>

### Problem:

I have a system of modules, that import modules(, that import modules). The last one in that chain is Bootstrap itself which has a config.yml with Hugo configuration, but NOT a go.mod. This config gets merged into my configuration and defines plenty of `Params` that break everything. 

I was able to disable that behaviour, see https://discourse.gohugo.io/t/new-config-merging-loads-bootstrap-site-config-into-mine/33468/5

BUT

I think this is a bug in Hugo, as the last part in the chain (the Bootstrap repo) is NOT a (Hu)Go module. It defines modules that I think is working but wrong usage and should be solved with configuration of folder paths. I would expect a that repo without go.mod to not appear anywhere in my configuration. 

If you think this is expected behaviour and not a bug please take the time to elaborate a bit so I can understand the thought process behind it. 

[Bootstraps config.yaml file](https://github.com/twbs/bootstrap/blob/main/config.yml)

**Comment by bep** [comment]
You need to put `_merge = "none"` in the params section (or on the level of the params section that is relevant) in the project/module that imports that Bootstrap project.

I understand that this was a slightly breaking change, which is why I did such elaborate work to allow people to opt out of it.

**Comment by davidsneighbour** [comment]
The issue refers NOT to merging of configuration in general, but merging of a configuration that comes from a NON-module. I can silence it, but I would not expect any arbitrary import that has a config.yaml/toml to infiltrate the configuration. If there is no go.mod in an import, then hugo should not import it's config.

**Comment by bep** [comment]
>but merging of a configuration that comes from a NON-module.

Every `import` is a module, whether it lives in /themes or ... whatever. I'm not sure what you're asking for here? 

>but I would not expect any arbitrary import that has a config.yaml/toml to infiltrate the configuration.

Arbitrary? You imported it, so it's hardly arbitrary. The change in `params` merging was done to solve a pretty big pain for theme authors -- theme authors don't care if a module is imported via "Go modules" or a submoule.

**Comment by davidsneighbour** [comment]
> Arbitrary? You imported it, so it's hardly arbitrary.

If _importing_ something makes it a Go module then that should be noted somewhere very prominent. I was operating under the assumption that a module has to say "hi, I am a module" (go.mod) to be a module. 

That means Hugo trusts everything I am importing. I think a warning in the docs is appropriate as Hugo is getting more and more copypaste-users. 

I am saying nothing against the new merging by the way, just noting, that I would not expect a github path to be a module if the repository does not announce itself as module. Comparably to me putting Bootstrap into the static directory instead of the themes directory before, but I guess with modules we don't have this type of distinction.
