### ISSUE TITLE
highlight-tag ignoring scroll area in its box area.

### ISSUE THREAD

**Issue by ghost** [gohugoio/hugo#8681]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

highlight-tag ignoring scroll area in its box area.
Hugo creates table-tag which is included highlight-tag has the following style attribute from a code mark(```) of markdown.
`<table style="border-spacing:0;padding:0;margin:0;border:0;width:auto;overflow:auto;display:block;">`

I think highlight-tag must involves scroll area in its box area.
so I guess the margin of style attribute of the table element should be "auto".

![ignoring-scroll-area](https://user-images.githubusercontent.com/11960211/122793085-c04ca100-d2f5-11eb-9463-2fd512e3c500.jpg)

**Comment by jmooring** [comment]
This is a CSS issue. Closing.
