### ISSUE TITLE
hugo v0.81.0 mangling " into &quot; regardless of blackFriday/goldmark, typographer, etc

### ISSUE THREAD

**Issue by sometato** [gohugoio/hugo#8682]
I seem to get this with blackFriday or goldmark.

With goldmark, I can disable typographer, and single ticks no longer get converted. However, double quotes always get converted to `&quot;`. Same thing with blackFriday.

Is there a way around this?

Thank you!

**Comment by jmooring** [comment]
Why is this is a problem? Is it breaking something?

**Comment by davidsneighbour** [comment]
This is a support issue. Please open a thread on discourse.gohugo.io with a code sample of the layout that is transforming unsafe characters. You probably will need to use `safeHTML`, `safeAttr` or `safeJs` at these points.
