### ISSUE TITLE
Hugo not generating posts in gitlab pages (gitlab-ci)

### ISSUE THREAD

**Issue by IshoAntar** [gohugoio/hugo#8683]
I think this should be documented somewhere in the official documentation,
because i just spent way too much time than i care to admit on this and solved it after
stumbling upon a random blog post.

When generating sites using GitLab's CI, Hugo does *not* generate any posts in the `public` directory.

In order to make it work, one should do:

```sh
mkdir .public
hugo -d .public
mv .public public
```

When outputting directly into `public` everything is generated correctly, *except* posts. which is...weird!

So, either the bug (?) should be fixed (might be on gitlab's side, though).
Or, add a note somewhere in the docs for people willing to use gitlab pages that
generating the site directly in the `public` directory won't work.

**Comment by jmooring** [comment]
I am unable to reproduce the reported behavior with content under `post/` or `posts/`. Here's a working example I deployed using this documentation: <https://gohugo.io/hosting-and-deployment/hosting-on-gitlab/>.

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
