### ISSUE TITLE
Update Chroma to v0.9

### ISSUE THREAD

**Issue by nonodename** [gohugoio/hugo#8687]
Chroma recently updated to v0.9 fixing a number of bugs and (selfishly) adding new language support.

Could we get hugo updated to [0.9.2](https://github.com/alecthomas/chroma/releases/tag/v0.9.2)?

**Comment by jmooring** [comment]
Already available in v0. 84. See release notes.

**Comment by nonodename** [comment]
My bad. Misunderstood the go packages. Thx for confirming.
