### ISSUE TITLE
"Defaultcontentlanguage" makes "content.xx" change refresh not work

### ISSUE THREAD

**Issue by volfclub** [gohugoio/hugo#8688]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.84.0-2C4689F7B+extended windows/amd64 BuildDate=2021-06-18T17:14:27Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
**YES**

---

Look like this config i18n:
<pre>
defaultContentLanguage = "ru"

[languages.ru]
  languageName = 'Russian'
  contentDir = 'content.ru'
  weight = 3
</pre>

or

<pre>
defaultContentLanguage = "zh"

[languages.zh]
  languageName = 'Chinese'
  contentDir = 'content.zh'
  weight = 1
</pre>

Then edit the markdown file under content.ru or content.zh, the browser will refresh, but the web page will not change 😥.

<pre>
Change detected, rebuilding site.
2021-06-22 22:55:06.934 +0800
Source changed "F:\\Blind\\Documents\\Github-Volf\\fourry\\content.ru\\_index.md": WRITE
Total in 20 ms
</pre>

Of course, if you edit the config file, it works.

<pre>
Change of config file detected, rebuilding site.
2021-06-22 23:08:02.936 +0800
…
Rebuilt in 2032 ms
</pre>

---
Temporary solutions:

<pre>
defaultContentLanguage = "ru"

[languages.ru]
  languageName = 'Russian'
  contentDir = 'content'
  weight = 3
</pre>

---

This is my Hugo repo: https://github.com/volfclub/fourry , Hugo theme is [book](https://github.com/alex-shpak/hugo-book).

**Comment by pamubay** [comment]
Based on your repo you have this structure:
```
.
└── root/
    ├── content      # English contentDir
    ├── content.ru  # Russian contentDir
    ├── content.zh  # Chinese contentDir
    └── ...
```

In you repo, rename the `contentDir` directory for English language from `content` to `content.en`. Then set the config accordingly:

```
[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 2
``` 

I've tested it and it works.

**Comment by volfclub** [comment]
> 
> 
> Based on your repo you have this structure:
> 
> ```
> .
> └── root/
>     ├── content      # English contentDir
>     ├── content.ru  # Russian contentDir
>     ├── content.zh  # Chinese contentDir
>     └── ...
> ```
> 
> rename the `contentDir` directory for English language from `content` to `content.en`. Then set the config accordingly:
> 
> ```
> [languages.en]
>   languageName = 'English'
>   contentDir = 'content.en'
>   weight = 2
> ```
> 
> I've tested it and it works.

Thx，It Work！🎉
