### ISSUE TITLE
Section level leaf bundles use wrong page template

### ISSUE THREAD

**Issue by raoulb** [gohugoio/hugo#8695]
If I have a leaf bundle `content/sec_leaf/index.md` on "top-level"/"section-level", the template `layouts/_default/single.html` is used. The expectation would be `layouts/sec_leaf/single.html` (if existent).

With a branch bundle `content/sec_branch/_index.md` instead, everything works as expected,
and `layouts/sec_branch/list.html` gets used.

Reading the [documentation](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-regular-pages) I think that row 1 in that table applies to the leaf bundle case and the choice should be "2". However, the leaf bundle seems to fall through straight to "4". One level deeper it works as expected, choosing the template by the section which is implied by the file path. (The branch bundle case is handled by row 2 of [this table](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-section-pages) where it stops at "6".)

I made a [minimal example site](https://github.com/raoulb/hugo_issue_sllb).

BTW: Of course I can fix this with an explicit `type` front matter as demonstrated [here](https://github.com/raoulb/hugo_issue_sllb/blob/master/content/sec_leaf_2/index.md).

The relevance of this issue arises from pages like "about", "contact" etc which logically are pure leaf bundles and might need different layouts.

This issue seems similar to report #5714.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.84.0-2C4689F7B linux/amd64 BuildDate=2021-06-18T17:14:27Z VendorInfo=gohugoio
</pre>

**Comment by bep** [comment]
>If I have a leaf bundle content/sec_leaf/index.md on "top-level"/"section-level", 

In your example the section is the root section, so to me it looks like it behaves exactly as designed.

**Comment by raoulb** [comment]
Hmm. After consulting the `.Section` page variable I might agree.

If bundles are not just the files *within* a directory but together with the containing directory, then I need to reconsider.
The [documentation](https://gohugo.io/content-management/page-bundles/) can be read this way ("is a directory", "is any directory") for both bundle types.
The (top-level) branch bundles then each span a new section for themselves while the leaf bundles do not?
(Because they are "attached" directly to the root section.)

But this contradicts the documentation on [sections](https://gohugo.io/content-management/sections/), no? The first paragraphs there read: 
> A Section is a collection of pages that gets defined based on the organization structure under the content/ directory.
> By default, all the first-level directories under content/ form their own sections (root sections).

A leaf bundle at this level is not included in the "default" setting then?
Does this "by default" implicitly mean: unless changed by the `type` front matter field?
(Uh, and another reference to "root". Then "content/" is *the* root and each section right beneath it is a *root section*, right?)

And then there is the [.Section](https://gohugo.io/variables/page/#section-variables-and-methods) page variable carrying a note:
> For nested sections, this is the first path element in the directory

which may add to this confusion as well.

If I am convinced that this "works as expected" then I need to agree with your final comment at #5714
> I suspect this issue is mostly about the lookup rules being a little har do understand.

and one should clarify the documentation.


BTW: My use case arises from a single "top-level" page (like "about") where I wish to load additional content from markdown files for use within the specialized template. Now, either I make this page a leaf bundle and use `*.md` page resources (which I think would be the proper way) but then need to explicitly construct a section or assign a layout directly to use my template. If I make it a branch bundle instead and use GetPage (because only non-md page-resources here) I need to suppress the publication of all other md files as pages on their own in the `_build` options. Both ways are just 95% straight forward.

**Comment by jmooring** [comment]
@raoulb

If you have specific suggestions to improve the documentation, pull requests are welcome at https://github.com/gohugoio/hugoDocs.

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by raoulb** [comment]
@jmooring I gave it a try: https://github.com/gohugoio/hugoDocs/pull/1482
