### ISSUE TITLE
Error: from config: failed to decode related config: empty related config provided

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8701]
Happens when including a theme/module with a related config, which, with the default merge strategy, ends up as an empty map. That should be handled smoother at the receiving end as well, I guess, but we need to make sure that these empty maps does not appear in the final config.

**Comment by davidsneighbour** [comment]
I always like to chime in when I hear "let's get rid of an empty map". I do not understand what that would mean in sense of Go variable handling, but having an "empty array" (object, map) is a quite often used strategy in other less, ehm, high(?) languages. 

Something like (if len settings 0) would not work with the above plan, right?
