### ISSUE TITLE
Race condition leading to duplication in generated URLs

### ISSUE THREAD

**Issue by moomop** [gohugoio/hugo#8704]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.84.1-4BD65E22+extended linux/amd64 BuildDate=2021-06-24T11:44:23Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
yes - v0.84.1 is currently the latest release

### Description
I'm seeing an issue where some generated URLs are duplicated so the output html can contain errors such as e.g. the repetition in the url shown below.

`<img alt="" itemprop="image" src="http://moopi/coffeenow/post/2021/05/setting-up-the-blog-i-getting-started-with-hugo/http://moopi/coffeenow/post/2021/05/setting-up-the-blog-i-getting-started-with-hugo/old_fashioned_typewriter.jpg"/>`

This happens randomly about 25% of times that I generate my site. If I set HUGO_NUMWORKERMULTIPLIER=1 then I no longer see the issue (so this is ok as a workaround for me). I think this indicates that there is some kind of race issue.

Guessing it could potentially be similar to the race conditions mentioned in https://github.com/gohugoio/hugo/issues/5926 or https://github.com/gohugoio/hugo/issues/7230. 

If anyone is likely to want to investigate this, please let me know and I can probably provide a reproducer (I can reliably reproduce it locally with a script that repeatedly runs hugo on a private repo). Not sure how likely it is to have a common root cause to another open issue.

**Comment by jmooring** [comment]
Whether this issue is investigated now or in the future, a minimal reproducible example would be helpful.

**Comment by jmooring** [comment]
Investigation is not possible without a minimal reproducible example. Closing.

**Comment by moomop** [comment]
Would a reproducer in the form of a cut down version of my site (but still containing the theme as a submodule) be useful?
I'm thinking that would be reasonably easy for me to provide but that trying to strip back the theme to provide a more minimal test might be more effort than is worthwhile for now.

**Comment by jmooring** [comment]
Strip it down to the point where you're comfortable sharing it, but make sure the problem can be reproduced.

**Comment by moomop** [comment]
Please see https://github.com/moomop/hugo-8704 for a reproducer.
I'm guessing the issue is exposed by the use of .Scratch in https://github.com/moomop/hugo-8704/blob/main/layouts/_default/summary.html. 
Should mention that I am very new to hugo and go templates so feel it's possible I have some basic error in that template. However, my understanding is that there shouldn't be any way to write a template that gives unpredictable results?

**Comment by jmooring** [comment]
Findings:

1. Your test passes if I remove your override of `themes/hugo-tranquilpeak-theme/layouts/_default/summary.html`.
2. This is the the line that generates the duplicate:
    <https://github.com/moomop/hugo-8704/blob/main/layouts/_default/summary.html#L28>
3. There is no reason to use a Scratch anywhere in this template. Use `:=` to initial a var, and use `=` to update its value.
4. Without spending a lot of time trying to understand the nuances of this template, this should fix the problem:

```diff
diff --git a/layouts/_default/summary.html b/layouts/_default/summary.html
index 9154256..d0cfd80 100644
--- a/layouts/_default/summary.html
+++ b/layouts/_default/summary.html
@@ -24,10 +24,10 @@
 {{ end }}
 
 {{if .Scratch.Get "thumbnailImage"}}
-{{if .Page.Resources.Match  (.Scratch.Get "thumbnailImage") }}
-  {{ .Scratch.Set "thumbnailImage" (printf "%s%s" .Permalink (.Scratch.Get "thumbnailImage")) }}
+{{with .Resources.GetMatch  (.Scratch.Get "thumbnailImage") }}
+  {{ $.Scratch.Set "thumbnailImage" .Permalink }}
 {{ else }}
-  {{ .Scratch.Set "thumbnailImage" ((.Scratch.Get "thumbnailImage")| absURL) }}
+  {{ $.Scratch.Set "thumbnailImage" ((.Scratch.Get "thumbnailImage")| absURL) }}
 {{ end }}
 {{ end }}
```

**Comment by moomop** [comment]
Thanks very much. Can confirm that the suggested change does fix the problem that I was seeing.
Also thanks for the pointer about not needing to use Scratch here.
