### ISSUE TITLE
Problem with categories with Unicode and/or zero-width non-joiner character

### ISSUE THREAD

**Issue by shahryareiv** [gohugoio/hugo#8706]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1
</pre>

### Does this issue reproduce with the latest release?
Yes,

Normally when one wants to access a taxonomy using `index`  the key should be `urlize`ed since it seems that is the way the keys are stored. However, if a category (maybe also tags?) is in a none Latin script (for example Persian) then its `urlize` form is unicode-escaped which does not reutrn result for `index`. For example, `index Site.Taxonomies.categories (urlize $some_category_indexterm) ` does not work if the category name is "دسته اول".

The second problem is when the category name has  zero-width non-joiner character (\u200C), which somehow is removed. For example, category name "دسته‌ها" should be searched like "دستهها" (note the change from the 2nd to 3rd character from left).

One could bypass this problem by using an alternative code instead of `urlize`, like this `(replace (replace ( $some_category_indexterm | lower) " " "-") "\u200c" "")`, but probably that is better to have a fix in the Hugo code.

**Comment by jmooring** [comment]
This was resolved in v0.123.0.
