### ISSUE TITLE
The "Netlify default cache dir logic" does not work

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8710]
Setting `HUGO_CACHEDIR=/opt/build/cache/hugo_cache/` in the environment does, however, do the trick. But we really need to fix this. This isn't a new issue though.

**Comment by Y4er** [comment]
I am using cloudflare pages service to host hugo, but the latest version of hugo 0.84.3 reported an error when building

```
Error: failed to create cache dir: mkdir /opt/build/cache: permission denied
```

I think there is a problem with the creation of the $TMPDIR/hugo_cache/ directory. Should there be a better design for the cache directory?

**Comment by ccampb13** [comment]
hey @Y4er, having the same issue on Cloudflare pages. Were you able to find a workaround for this?

**Comment by Y4er** [comment]
@ccampb13 

setting the `HUGO_CACHEDIR` env var like this:

![image](https://user-images.githubusercontent.com/40487319/124208422-16052280-db1a-11eb-99ba-40756bb2c53c.png)

look here https://github.com/gohugoio/hugo/issues/8714

**Comment by Y4er** [comment]
or set HUGO_VERSION=0.84.4

https://github.com/gohugoio/hugo/releases/tag/v0.84.4

**Comment by ascorbic** [comment]
Hi. I work on integrations at Netlify, and maybe we should work together to implement a more robust solution. I brought this up [on Twitter](https://mobile.twitter.com/ascorbic/status/1410621497127968775), but maybe Netlify should set the `HUGO_CACHEDIR` env var when building Hugo sites, rather than you needing special Netlify-specific logic in the code.

**Comment by ccampb13** [comment]
Thanks, @Y4er! That did the trick!

**Comment by bep** [comment]
@ascorbic yea, that could be a good idea. But note that this issue wasn't really a problem until I started doing stupid things ...

To the cloudflare users in here: Setting HUGO_CACHEDIR to something that gets persisted between builds can be a big win in build time, see

https://gohugo.io/getting-started/configuration/#configure-file-caches
