### ISSUE TITLE
0.84.3 breaks deployments on Cloudflare Pages

### ISSUE THREAD

**Issue by HorayNarea** [gohugoio/hugo#8714]
Since 0.84.3 deployments on Cloudflare Pages are broken, as far as I can tell the problem boils down to this commit:

https://github.com/gohugoio/hugo/commit/6c8c0c8b6a0b39b91de44d72a7bd1cd49534a0f1

Cloudflare Pages sets these environment variables:

[cloudflare-pages-env.d451584b-3b9e-49a6-9f43-006a4ae62185.log](https://github.com/gohugoio/hugo/files/6737125/cloudflare-pages-env.d451584b-3b9e-49a6-9f43-006a4ae62185.log)
(generated by deploying https://github.com/HorayNarea/cloudflare-pages-env and setting the build command to `./run.sh`)

As you can see, in line 74 they also set `NETLIFY=true` but `DEPLOY_PRIME_URL` is not set, so that means the cache-directory is now also set to `/opt/build/cache/hugo` when deploying on Cloudflare Pages which leads to a failed build as you can see in this screenshot & build log:

![screenshot](https://user-images.githubusercontent.com/1871153/123881653-768f3680-d945-11eb-817d-e69c6f49d175.png)

[gecko-space.b4bd25b5-4e7e-40fd-833a-6128ca0b0e5b.log](https://github.com/gohugoio/hugo/files/6737085/gecko-space.b4bd25b5-4e7e-40fd-833a-6128ca0b0e5b.log)

**Comment by bep** [comment]
>As you can see, in line 74 they also set NETLIFY=true 

Are you kidding me?

**Comment by jmooring** [comment]
For future reference, Cloudflare no longer sets the NETLIFY env var. This is true for both Cloudflare Workers and Cloudflare Pages.
