### ISSUE TITLE
Transparency problem when converting 32-bit images to WebP

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#8729]
Example:

![image](https://user-images.githubusercontent.com/335669/124651775-33a2f680-de50-11eb-93f1-d1bdbda16a5a.png)

Minimal reproducible example to follow...

**Comment by jmooring** [comment]
Minimal reproducible example:

```bash
git clone --single-branch -b hugo-github-issue-8729 https://github.com/jmooring/hugo-testing hugo-github-issue-8729
cd hugo-github-issue-8729
hugo server
```

**Comment by bep** [comment]
The (my) upstream encoder works correctly here: https://github.com/bep/gowebp/commit/a20a4dad3c67ee28dfa1fd20dd7d7cf27434521c

Which narrows down the options ...
