### ISSUE TITLE
Empty .GitInfo object in partials

### ISSUE THREAD

**Issue by chenkai0520** [gohugoio/hugo#8737]
When Chinese is included in the path Empty .GitInfo object in partials

<img width="363" alt="截屏2021-07-08 下午5 32 29" src="https://user-images.githubusercontent.com/30174970/124899241-81fff300-e012-11eb-8bb6-048cd8777389.png">

### What version of Hugo are you using (`hugo version`)?
<pre>
Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
true

**Comment by bep** [comment]
You need to pass the page to the partial for .GitInfo to be available. But please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
