### ISSUE TITLE
Hugo server should try to show 404 page on HTTP 404

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#874]
See

http://discuss.gohugo.io/t/how-to-test-404-html-on-local-server/681

**Comment by EricR** [comment]
I tried tackling this yesterday and found it surprisingly difficult:

`serveFile`, which is used by FileServer, doesn't expose an actual error. Instead it has a NotFound handler that it uses when it can't find a file on the file system, which you cannot get around using. See http://golang.org/src/net/http/fs.go#L356 . As of right now, changing this in the standard library is currently a TODO.

I tried implementing my own ResponseWriter type that intercepted `WriteHeader` to call a handler that handles 404s. However, at that point NotFound had already been called and the response had been written to, so this doesn't seem to be a valid option.

Other options I can think of
* Implement our own version of http.FileServer which can allow for 404 handling. This is what [Martini does](https://github.com/go-martini/martini/blob/master/static.go#L53).
* Speaking of which, we could use Martini for mux and it's static file handler in server.go. How do hugo developers feel about including third party libraries like this?
* Maybe there's some clever way to get our own version of FileSystem to return a 404.html when it can't find the file? Sounds kind of like overkill to me to address this issue, though.

What do other people think?

**Comment by bep** [comment]
I thought this would be simple when I jotted down the issue. Maybe @bradfitz could shed some light on this. I think he's the main person behind the http package in Go.

I know @spf13 would hate to increase the binary size with Martini just to get some proper 404 handling.

**Comment by spf13** [comment]
I've considered adding in httprouter though. Especially if we add a rest API. 
 
https://github.com/julienschmidt/httprouter

**Comment by EricR** [comment]
Definitely in favor of the simplest, smallest solution for this. httprouter looks very nice :+1:

**Comment by rustyoz** [comment]
I just tackled this and the solution I came up with was an enhanced/stipped down http.FileServer handler. 



https://github.com/rustyoz/hugo/commit/4a4cebfccbb0663afa6547daf513d1506c8bc97a

**Comment by rustyoz** [comment]
A better solution to what I created would be to substitute the standard http package with https://github.com/Masterminds/go-fileserver

**Comment by bep** [comment]
@rustyoz I agree, but it still feels that the `FileServer` devs should have made this extensible in the first place. When they sober up from GopherCon I will post an issue; but that will be Go 1.6 at best. 

I guess this discussion can hold until we decide what to do about a REST api.

**Comment by surajmandalcell** [comment]
Anyone resolved this issue?

**Comment by biodranik** [comment]
It's better to keep this issue open (or fix it before closing) for more convenient localhost development.

**Comment by solutionroute** [comment]
Related then, adding something in documentation would be a sufficient measure. Currently searching the new (and much improved!) documentation site for 404 returns no results. 

https://gohugo.io/templates/404/

At the very end (in Automatic Loading), something like:

Hugo's built in server *will not* automatically load your custom 404.html file, but you can test the appearance of your custom not-found page by navigating your browser to /404.html.

**Comment by kaushalmodi** [comment]
@solutionroute Done! :)

**Comment by solutionroute** [comment]
Cool, thanks. I'll try submitting doc PRs myself. 

Cheers
Mike
