### ISSUE TITLE
hugo serve results in `panic: non-positive interval for NewTicker`

### ISSUE THREAD

**Issue by MikhailKlemin** [gohugoio/hugo#8744]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
$ hugo v0.86.0-DEV+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
I just build several sites and all of them produce same error. Build fine, but serve does not work with 
``` 
Watching for changes in /home/mike/hugo/mysite/{archetypes,assets,content,data,i18n,layouts,static,themes}
panic: non-positive interval for NewTicker

goroutine 391 [running]:
time.NewTicker(0x0, 0x74bb11411bbdc838)
        /usr/local/go/src/time/tick.go:24 +0x151
github.com/gohugoio/hugo/watcher/filenotify.(*filePoller).watch(0xc002bedf00, 0xc002be6aa0)
        /home/mike/Downloads/hugo/watcher/filenotify/poller.go:145 +0x53
created by github.com/gohugoio/hugo/watcher/filenotify.(*filePoller).Add
        /home/mike/Downloads/hugo/watcher/filenotify/poller.go:69 +0x1d8
```

**Comment by bep** [comment]
What arguments do you pass to `hugo server`?

**Comment by MikhailKlemin** [comment]
No arguments. Just `hugo serve`

**Comment by MikhailKlemin** [comment]
Not sure if this is how it should be, I mean `go install` should have been pull correct packages.

**Comment by jmooring** [comment]
Unable to reproduce problem.

```
mkdir ~/temp
cd ~/temp
git clone https://github.com/gohugoio/hugo.git
cd ~/hugo
go install
```

**Comment by bep** [comment]
>Not sure if this is how it should be, I mean go install should have been pull correct packages.

It should, but you need to bring any problems with the Go compiler up here: https://github.com/golang/go/issues

Note that we also provide pre-built binaries for many platforms.
