### ISSUE TITLE
Shortcodes not behaving the same with `--minify` flag than without

### ISSUE THREAD

**Issue by duck-dev** [gohugoio/hugo#8748]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version v0.83.1
</pre>

### Does this issue reproduce with the latest release?
Yes, my website has been deployed with GitHub Actions using 'latest' for the Hugo version, so I assume it used v0.85.0, which is the latest version right now and the problem occured there too.

### The problem briefly explained
Building my site **with** the `--minify` flag makes my shortcodes behave slightly different. Precisely, there is no space between the word before the content wrapped into the shortcode layout and this content. 
**Without** using `--minify`, the same Markdown yields different result (with a normal space, as expected).

See **The problem in detail**, **Example 1** and **Example 2** for further information and examples to reproduce the issue.

### The problem in detail
I noticed that my shortcodes don’t behave the same in the deployed site (hosted with GitHub Pages, deployed with [GitHub Actions](https://github.com/marketplace/actions/hugo-setup) as described in the [official documentation](https://gohugo.io/hosting-and-deployment/hosting-on-github/)) as in a local build (built locally with `hugo server` or `hugo server -D`, localhost).

In my locally built site, the shortcode behaves as expected. It’s a simple shortcode formatting the content of it. The only problem is, that even though I actually added a space between the text and the declaration of the shortcode (see examples below), it doesn’t add a space in the deployed site on GitHub Pages, whereas it behaves as expected in a locally built site.

After a [conversation](https://discourse.gohugo.io/t/shortcodes-not-behaving-the-same-in-deployed-site-as-in-local-build/33794) with @bep on the Hugo forum, we came to the conclusion that it's most likely an issue with the built-in minifier in Hugo, because I never used `--minify` in my local builds, whereas the action deployed the page with GitHub pages using `--minify`. That's why I'm creating this issue. Going even further, I tried to use `--minify` for my local build (`hugo server --minify` in the command line) and I managed to reproduce the issue on a local build too.

### Example 1
- Markdown content (inside a simple block of text):
```md
Apart from the {{<link `index.html` `_blank`>}}official API reference{{</link>}}
```

- Shortcode `link.html`:
```html
<head>
    <style>
        .shortcode-link {
            color:#fc3f65;
        }

        .shortcode-link:visited {
            color:#fc3f65;
        }

        .shortcode-link:active {
            color: #c92d4c;
        }
    </style>
</head>

{{ $p0 := .Get 0 }}
{{ $p1 := .Get 1 }}
{{ $inner := .Inner }}
<a href="{{ $p0 }}" target="{{ $p1 }}" class="shortcode-link">{{$inner}}</a>
```

- **Without** `--minify` (**expected** result, with space):
![image](https://user-images.githubusercontent.com/61479436/125296042-2a20ff00-e326-11eb-8d5a-6fb5752abba2.png)

- **With** `--minify` (**unexpected** result, without a space between `the` and `official API reference`):
![image](https://user-images.githubusercontent.com/61479436/125296099-3907b180-e326-11eb-8ea5-488a0a8de5e2.png)

### Example 2
- Markdown content (inside a simple block of text):
```md
The {{<codeline>}}[SerializeField]{{</codeline>}} attribute makes sure that the field is exposed to the inspector
```

- Shortcode `codeline.html`:
```html
<head>
    <style>
        .single-code-line {
            font-family: CodeMono;
            background-color: #202020;
            color:white;
            padding-left: 7px;
            padding-right: 7px;
            text-align: justify;
            word-wrap: break-word;
        }
    </style>
</head>

<code class="single-code-line">{{ .Inner }}</code>
```

- **Without** `--minify` (**expected** result, with space):
![image](https://user-images.githubusercontent.com/61479436/125296480-9e5ba280-e326-11eb-832e-a37c3e99d86e.png)

- **With** `--minify` (**unexpected** result, no space between `The` and `[SerializeField]`):
![image](https://user-images.githubusercontent.com/61479436/125296623-c3e8ac00-e326-11eb-9f54-dfe0fb88fa46.png)

**Comment by jmooring** [comment]
First, `<head>` does not belong here. It must be the first child of the `<html`> element.
See <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head>.

Second, `<style>` does not belong here.
See <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#technical_summary>.

**Comment by davidsneighbour** [comment]
I don't think that is the reason for the issue, mostly because the link is still red in the first example and in the second example nothing is removed. Most modern browsers can work around wrong markup. The issue at hand seems to be that hugo minify removes spaces around the shortcode in certain circumstances. Might be an upstream issue.

**Comment by duck-dev** [comment]
Yes, excuse me for these examples. It was a quick example I made based on my code, which actually does look like that, just not with the <head>. I included it, because I had previous positive experiences by adding the <head>. But with or without that, the issue is still the same.

> The issue at hand seems to be that hugo minify removes spaces around the shortcode in certain circumstances. Might be an upstream issue.

So, `--minify` is still the issue, right? Can I somehow workaround that (without having to abandon `--minify`, which isn't recommended anyway or is it really an internal issue, which would need to be fixed on your side?

**Comment by davidsneighbour** [comment]
`{{-` removes all spaces left of the golang-template-tag. `-}}` removes all whitespaces right of the tag.

**Comment by jmooring** [comment]
@duck-dev 

<details>
<summary>This is an example of the HTML produced by your markdown+shortcode</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0">
  <title>Test</title>
</head>
<body>

<h1>Test</h1>
<p>Apart from the <style>
  .shortcode-link {
    color: #fc3f65;
  }

  .shortcode-link:visited {
    color: #fc3f65;
  }

  .shortcode-link:active {
    color: #c92d4c;
  }
</style>
  
<a href="path" target="_blank" class="shortcode-link">official API reference</a>
</p>

</body>
</html>
```

</details>

You have a `<style>` element within a `<p>` element. Now copy and paste this HTML into a [validator](https://validator.w3.org/#validate_by_input):

<img src="https://user-images.githubusercontent.com/335669/125305731-71d26700-e2e3-11eb-994d-ae97b2533b53.png" height="200">

Either move the `<style>` element, or place the CSS in a CSS file.

Yes, the browsers that I tested did not complain about the invalid HTML, but that doesn't mean that the minifier should be modified to accommodate HTML that doesn't follow the specification.

**Comment by bep** [comment]
A closed issue is ... closed. If this issue is still relevant, open another issue.
