### ISSUE TITLE
resources.Concat fails if resource file has numbers in it's name

### ISSUE THREAD

**Issue by danisztls** [gohugoio/hugo#8766]
**Version:** `hugo v0.85.0+extended linux/amd64 BuildDate=unknown`
**Last release**: Yes.

### Code
```html
{{ $pre := resources.Get "js/pre.js" }}
{{ $redirect := resources.Get "js/modules/i18n-redirect.js" }}
{{ $preBundle := slice $pre $redirect | resources.Concat "js/pre.js" }}

{{ if ne (hugo.Environment) "local" }}
  <!-- development -->
  {{ $preBundle = $preBundle | resources.Minify }}
{{ end -}}

<script src="{{ $preBundle.Permalink }}" async></script>
```

### Error
`at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat`

### Solution
Renaming the file to a name without numbers. Eg `redirect.js`.

**Comment by pamubay** [comment]
Cannot reproduce. works for me using number as a name.

```
hugo v0.86.0-DEV-8DDBC954+extended linux/amd64 BuildDate=2021-07-06T17:16:57+0700
```

**Comment by bep** [comment]
The error message may be bad, but it has nothing to do with the filename.

**Comment by danisztls** [comment]
Sorry. I reproduced it again but it isn't that the filename can't have numbers on it but that it was wrong *(pointing to a file that didn't exist)*.
