### ISSUE TITLE
Expected error is not thrown while running hugo server in fast render mode

### ISSUE THREAD

**Issue by sweetyoru** [gohugoio/hugo#8778]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.85.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Unknown

### Details
Currently, i have a template with code like this:

<img src="{{ (.Page.Resources.GetMatch "img.png").Permalink }}"></img>

Normally, the code run just file and the site is built with no error. But when i change the config file, hugo return this error:
```
executing "partials/my_patiral.html" at <"img.png">: nil pointer evaluating resource.ResourcePermalink
```
But when i delete all code in my_partial.html and rebuild the site, then repaste the code and rebuild, no error happens this time.

**Edit 1:**
As i notice, when the error happens, i can just delete all code that refer to .Page.Resources in that template, and put {{ .Page.Resources }}, then rebuild, then change back to old code and rebuild, this will fix the error everytime it happens, not sure why.

**Comment by sweetyoru** [comment]
After some more tries, i notice that the error only go away if i change the code back after hugo server is up

**Comment by sweetyoru** [comment]
After more tries, the nil bug always appear when i add --disableFastRender flag

**Comment by ptgott** [comment]
@sweetyoru So it's easier for others to reproduce this, what change did you make to the config file? Was it a particular field?

**Comment by sweetyoru** [comment]
No change was make to the config file. I believe the root cause is problem with caching when testing code without building it from the start.

**Comment by jmooring** [comment]
@sweetyoru 

Can you provide concise, specific instructions to consistently reproduce this behavior? Or better yet, can you provide a minimal reproducible example?

**Comment by sweetyoru** [comment]
- Step 1: `hugo new site test`
- Step 2: create content/test/a with following files:
  + a.md
  + img.md
- Step 3: create layouts/_default/baseof.html with following content:

```
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
	{{ block "body" .}}
	{{ end }}
</body>
</html>
```

- Step 4: create layouts/test/single.html with following content:

```

Now you should this error

**Comment by jmooring** [comment]
The error is correct, but should be thrown regardless of whether or not hugo server is running in fast render mode.

**Comment by bep** [comment]
The fast render mode means we render pages on demand, that also means that we cannot show error not triggered.
