### ISSUE TITLE
Javascript Minification Bug

### ISSUE THREAD

**Issue by funkydan2** [gohugoio/hugo#8785]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.86.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

### Bug Report

With Hugo 0.86.0 (I think this might go back to [at least 0.84.2](https://discourse.gohugo.io/t/since-hugo-v0-84-2-my-javascript-size-went-to-400-mib/33869)), minification breaks some javascript.

Without minification `hugo` produces:
```
<script>
    $(document).ready(function() {
      if ($("#player").length) {
        const player = new Plyr('#player', {settings: ['speed']});
      }
    });
  </script>
``` 
But with `hugo --minify` it is reduced to
```
<script>$(document).ready(function(){if($("#player").length)})</script>
```
(Code is produced from [this partial](https://github.com/funkydan2/alpha-church/blob/9421d23efe872ae686ea018ea2b9fc0a27ba928c/layouts/partials/scripts.html#L54).)
(The variable declaration of the object is removed.)

As suggested in the [above discourse thread](https://discourse.gohugo.io/t/since-hugo-v0-84-2-my-javascript-size-went-to-400-mib/33869), setting
```
[minify]
minifyOutput = true
disableJS = true
```
in the config gets around this issue, as does not passing `--minify`.

**Comment by davidsneighbour** [comment]
I am pretty sure this is due to `player` not being used anywhere else in the code. maybe `console.log` the `player` variable to see if it stays then. That should be an issue in the minifier library then, or maybe they even thought about unused-variables there and have some form of keepit-config-parameter for that.

**Comment by funkydan2** [comment]
@davidsneighbour you might be on to something there and I can see why it would do that. Though I don't see that feature listed [in the minify library's README](https://github.com/tdewolff/minify/tree/v2.9.17#js).

I'm pretty sure this behaviour is new(ish). But if the solution is my theme only works without minification, I can live with that.

**Comment by jmooring** [comment]
https://github.com/tdewolff/minify/issues/428

**Comment by jmooring** [comment]
@funkydan2 With [tdewolff/minify v2.9.20](https://github.com/tdewolff/minify/releases/tag/v2.9.20) your code is minified to: 

```js
$(document).ready(function(){})
```

Closed with https://github.com/gohugoio/hugo/pull/8819.
