### ISSUE TITLE
Add --date CLI flag

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#8787]
Some builds are run daily with expectations regarding dates. 

It would be interesting to be able to test drive the build on a with date so that Hugo time functions (`now` etc...) uses the time passed through the flag instead of the machine time.

This would allow users to make sure the expected behaviour on or after a certain date/time works as expected.

Parameter could be the same as what the [`time`](https://gohugo.io/functions/time/#readout) function is currently expecting.

```
hugo --date 2023-07-04
```

```
hugo --date 2016-05-28T10:30:00.00+10:00
```

I suspect this might be tricky, but if not, I'd regret not suggesting it.

**Comment by bep** [comment]
I'm not sure how to do this, but you would somehow need to set the system clock.
