### ISSUE TITLE
Make time.Format localized

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8797]
https://github.com/go-playground/locales

It looks beautifully complete, and has a lot of the stuff that many people ask about, esp. date formatting:

https://github.com/go-playground/locales/blob/master/rules.go#L45

Not sure how to go about with this (esp. considering go-i18n, but I suspect we can take this in 2 round), but one should be able to do something ala:

```
Week day: {{ site.Language.Translator.WeekDayShort .Date }}
```

Translator ...?

/cc @jmooring @regisphilibert

**Comment by jmooring** [comment]
Given `date = 2021-02-26T05:22:00-07:00` in frontmatter, I am hopeful that something similar to this would be possible...

Content|Code|Result
:--|:--|:--
post/foo.en.md|`{{ .Date.Format "Mon, January 2, 2006"}}`|Fri, February 26, 2021
post/foo.es.md|`{{ .Date.Format "Mon, January 2, 2006"}}`|V, febrero 26, 2021

**Comment by regisphilibert** [comment]
I think it's great to wrap this in `.Date.Localize` so we can have: `.Date.Localize.MonthAbbreviated`, `.Date.Localize.MonthWide` etc... 

Though I think we'll have to document what those wordings means (WeekdayNarrow, WeekdayShort, WeekdayWide etc...) I couldn't find any examples in the two links shared in this thread.

**Comment by jmooring** [comment]
@regisphilibert

Examples:
<https://github.com/go-playground/locales/blob/master/en_US/en_US.go#L61-L74>

**Comment by bep** [comment]
>post/foo.es.md | {{ .Date.Localize.Long }} | el viernes 26 de febrero de 2021

What if I want to list the Spanish posts on the English site?

**Comment by regisphilibert** [comment]
> What if I want to list the Spanish posts on the English site?

It's an edge case and you should work for it :)

People will need to understand that `.Date.Localize` is a page method and as such it relies on the page's data to find the proper language to use. 

But we could also introduce a way to create a localized date.  Maybe `timeLocalized` which would take a second parameter for the language:

```
{{ $EsDate := timeLocalized .Date "es" }}
```

**Comment by jmooring** [comment]
@bep You are making my head hurt.

**Comment by bep** [comment]
>It's an edge case and you should work for it :)

You, maybe, but why should _I_ work for it.

```
Week day: {{ site.Language.Translator.WeekDayShort .Date }}
```

The above would solve it for all cases without any magic. And it's much simpler to implement and also more efficient.

**Comment by regisphilibert** [comment]
> Now, I do have a few questions, number 3 being the most important (You can find them better formatted on the page shared above)

As _you_ I mean the users who want to print spanish content on their english pages.

I can live with you suggestion and it does improve the way people have dealt with localized date before (data file + i18n) but you will still have to work with several methods to build one date.

A simple example to write: **Tuesday: February 4 2021** in engish and **Mardi: 3 février 2006** in french (I'm not even considering the `2nd`, `3rd` issue.

```
<time datetime="{{ .Date.Format "2006-01-02T15:04:05-0700" }}">
{{ if eq site.Language.Lang "fr" }}
 {{ site.Language.Translator.WeekDayLong .Date }}: {{ .Date.Format "2" }} {{ site.Language.Translator.MonthWide .Date }}  {{ .Date.Year }}
{{ else }}
{{ .Date.Format "Monday: January 2 2006  }}
</time>
```
I guess what most users would be thrilled about is an easy way to print a localized date similar to `.Date.Format` without the gymnastic illustrated above.

**Comment by bep** [comment]
We could try go make a `site.Language.Translator.FormatDate` method that works the same as `time.Format`.

**Comment by bep** [comment]
Or we could do `time.Format .Date`.

**Comment by regisphilibert** [comment]
It's all in the perspective of UX/DX. 

If you're working with english date you can rely on the page .Date object which sports its own `.Format` but if using another language, you should use `site.Language.Translator.FormatDate .Date`. 

Which means theme creators will need to use systematically that translator method on the site.Language which seems a bit remote. As people are used to using `.Date.Format` from the page context and `dateFormat` from the rest, I wonder how we can introduce something similar or even the same with an optional third argument for the language code.

**Comment by bep** [comment]
@regisphilibert I'm scoping down this particular issue into making `time.Format` (which we already have, which also supports a string input) localized.
