### ISSUE TITLE
error calling Menus: cannot convert <nil> to maps.Params

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#8825]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.86.0-41C6C52E+extended darwin/amd64 BuildDate=2021-07-21T09:53:14Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes but not on 85.0, might have something to do with cascade in config.

I'm leaving this here, if this message does not speak by itself, I'll try and share more and reproduce the error on a simple project (it's currently happening on a rather complex one).

A simple ` {{ with site.Menus }}` is currently triggering this.

**Comment by bep** [comment]
I have added #8830 which should remove the error, but even if I think that solution is sound enough (treat nil Params as empty Params), I'm curious as to why ...

This is a `config.toml` (?) with a menu item with `params`?

**Comment by regisphilibert** [comment]
Actually I found the culprit... I had left something like this in one of the content files (an empty params key):

```
titlte: ...
menus:
  main: 
    parent: journal
    weight: 2
    params:
```

**Comment by bep** [comment]
I suspected the above, so I tried to create a failing test for it ... In TOML, but ah, YAML decodes empty maps to nil. How liberating.
