### ISSUE TITLE
Upgrade minify to fix ES6 corruption issue.

### ISSUE THREAD

**Issue by bwklein** [gohugoio/hugo#8831]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1-5AFE0A57+extended linux/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Requires an update of tdewolff/minify to a version released after 2021-07-29.
https://github.com/tdewolff/minify/commit/9f73f9dc12fca9139be5633b4ea335467ddc0103

### Problem

There was a regression in the minify library that corrupted ES6 format code in <script> tags.
https://github.com/tdewolff/minify/issues/429
This has been resolved, and Hugo just needs to pull in the latest version of the library.

**Comment by bep** [comment]
>This has been resolved, and Hugo just needs to pull in the latest version of the library.

There is no version with this patch as far as I can see. Can you ask upstream for a new tagged version?

**Comment by bwklein** [comment]
I've made the request.
