### ISSUE TITLE
Validate specified timezone against IANA database

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#8832]
### Case 1: Site Configuration

If an invalid `timeZone` is specified in the site configuration, the failure is silent. Example:

```tonl
timeZone = "America/LosAngeles"   # Should be America/Los_Angeles
```

### Case 2: Time Function

If an invalid timezone is specified as the optional second argument to the [`time`](https://gohugo.io/functions/time/) function, the failure is also silent (the build continues without error or warning). However, the error is rendered on the page (easy to miss and then inadvertently deploy). Example:

```
{{ time "2020-07-31T09:29:26" "America/LosAngeles" }}
```

This renders:

```text
unknown time zone America/LosAngeles
```

**Comment by bep** [comment]
The second case above is #8835 -- I separated that into its own issue, because that is more general and technical. We do return an error on invalid timezone in `time.AsTime`, but due to some technical mumbo jumbo, that error does not transform into a real error when you use the short form `time`.
