### ISSUE TITLE
Hugo keeps rebuilding the site when VSCode windows has focus

### ISSUE THREAD

**Issue by duel-adn** [gohugoio/hugo#8834]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.86.1+extended darwin/amd64 (via homebrew)
</pre>

### Does this issue reproduce with the latest release?

yes

### Description

It is a rather strange behaviour. I have a moderately large site (130 pages) all markdown and I manage it with VSCode on MacOS Big Sur on Intel.

When I launch Hugo from the terminal integrated with VSCode the site keeps rebuilding even though there are no real changes.

When I launch Hugo from a standalone terminal, this **does not happen**, when the VSCode window is not active (e.g. it is on a different virtual desktop) however, when the VSCode windows gains focus again, Hugo starts rebuilding the site, even if no interaction is performed in VSCode.

Don't know whether this is a VSCode or a Hugo issue, but I think that pointing out this strange behaviour can be useful.

**Comment by jmooring** [comment]
In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
