### ISSUE TITLE
safeHTMLAttr splits string with spaces into separate attributes

### ISSUE THREAD

**Issue by ayoisaiah** [gohugoio/hugo#8837]
When I use `safeHTMLAttr` as below:

```
{{ "class=red blue" | safeHTMLAttr }}
```
it produces

```
class="red" blue
```

instead of

```
class="red blue"
```

I wanted to confirm if this is a bug or expected behaviour?

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.86.1-F6821B88 linux/amd64 BuildDate=2021-07-30T10:13:35Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
Incorrect usage:

```
{{ $attr := "class=red blue" | safeHTMLAttr }}
<p {{ $attr }}>foo</p><br>
```

Correct usage:

```
{{ $attr := `class="red blue"` | safeHTMLAttr }}
<p {{ $attr }}>foo</p><br>

- OR - 

{{ $attr := printf "class=%q" "red blue" | safeHTMLAttr  }}
<p {{ $attr }}>foo</p><br>
```

**Comment by ayoisaiah** [comment]
Thanks @jmooring

**Comment by jmooring** [comment]
In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
