### ISSUE TITLE
Add clearscreen feature to hugo server command

### ISSUE THREAD

**Issue by inwardmovement** [gohugoio/hugo#8848]
Like https://rollupjs.org/guide/en/#watchclearscreen

**Comment by bep** [comment]
Why do people want this?

**Comment by inwardmovement** [comment]
To live in the present?

**Comment by bep** [comment]
>To live in the present?

Isn't that what ... scrolling is for?

**Comment by inwardmovement** [comment]
When sometimes (most of the time?) you don't need to see the history of precedent builds/watch, then there's no point in cluttering the screen with it. I think that's the main reason why "people want this".

**Comment by bep** [comment]
> I think that's the main reason why "people want this".

Sure, I need to play a little devils advocate on these "nice to have" issues. You are the first to ask for this, though. And I, myself, am very much used to look at the server output as a `tail -f` of a server log. But that's me. Let other chime in, if you get a fair amount of "thumbs up", we can do this.

**Comment by SirUli** [comment]
I actually want to see the history - sometimes to see if the build was taking longer or shorter, sometimes just to see which parts have been recently rebuilt. For me there is no point in the clearing (i actually hate it when tools do that).

**Comment by inwardmovement** [comment]
> I actually want to see the history - sometimes to see if the build was taking longer or shorter, sometimes just to see which parts have been recently rebuilt. For me there is no point in the clearing (i actually hate it when tools do that).

It would be an option.
