### ISSUE TITLE
youtube video instead image

### ISSUE THREAD

**Issue by anibal-aguila** [gohugoio/hugo#8854]
Hi, there are some way to substitute the cover image with youtube video code on the main site and into the post?

![image](https://user-images.githubusercontent.com/49025536/128228421-caa9a969-d5bc-4379-b73b-65874dcc8574.png)

thanks in advance,

**Comment by jmooring** [comment]
You created the same issue in three repositories:
- <https://github.com/gohugoio/hugo/issues/8854>
- <https://github.com/onweru/hugo-swift-theme/issues/74>
- <https://github.com/onweru/newsroom/issues/37>

Please don't do that.

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
