### ISSUE TITLE
Markdown: reference-style links broken across newline

### ISSUE THREAD

**Issue by harding** [gohugoio/hugo#8855]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.87.0-B0C541E4+extended linux/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes (this is the latest release).

### Issue

Reference-style links broken across a newline are incorrectly rendered.  For example, this text:

```markdown
This is a [test][foo
bar] 1...2..3...

[foo bar]: /
```

Produces this output:

![latest](https://user-images.githubusercontent.com/61096/128237161-9cbaedfd-4660-4d6a-bbb1-8bd8106aa42d.png)

CommonMark says it should render correctly: https://spec.commonmark.org/dingus/?text=This%20is%20a%20%5Btest%5D%5Bfoo%0Abar%5D%201...2..3...%0A%0A%5Bfoo%20bar%5D%3A%20%2F

Relevant config file:

```text
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
```

(Thanks for all your work!)

**Comment by jmooring** [comment]
Yes, your example should work per <https://spec.commonmark.org/0.30/#example-540>.

Please log an issue upstream (<https://github.com/yuin/goldmark/issues>) and link back to this issue. Thanks.

**Comment by yuin** [comment]
goldmark author here, I've fixed the issue and released a new version.
