### ISSUE TITLE
lang.FormatCurrency & lang.FormatAccounting do not allow PRECISION < 2

### ISSUE THREAD

**Issue by divinerites** [gohugoio/hugo#8858]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.87.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes.

Not sure if it is related to the "Add new localized versions of lang.FormatNumber etc." from v0.87.0, or if it is intended (not on doc)  but I can't get PRECISION = 0 or 1 for `lang.FormatCurrency` & `lang.FormatAccounting`

```
{{ 100 | lang.FormatCurrency 0 "CHF" }}<br>
{{ 100 | lang.FormatCurrency 1 "CHF" }}<br>
{{ 100 | lang.FormatCurrency 2 "CHF" }}<br>
{{ 100 | lang.FormatCurrency 3 "CHF" }}<br>
{{ 100 | lang.FormatAccounting 0 "CHF" }}<br>
{{ 100 | lang.FormatAccounting 1 "CHF" }}<br>
{{ 100 | lang.FormatAccounting 2 "CHF" }}<br>
{{ 100 | lang.FormatAccounting 3 "CHF" }}<br>
{{ 100 | lang.FormatNumber 0 }}<br>
{{ 100 | lang.FormatNumber 1 }}<br>
{{ 100 | lang.FormatNumber 2 }}<br>
{{ 100 | lang.FormatNumber 3 }}<br>
```

produce

```
100,00 CHF
100,00 CHF
100,00 CHF
100,000 CHF
100,00 CHF
100,00 CHF
100,00 CHF
100,000 CHF
100
100,0
100,00
100,000
```

**Comment by ptgott** [comment]
I'm attempting to reproduce the issue via unit tests in my feature branch ([see the diff here](https://github.com/ptgott/hugo/compare/master..ptgott/issue-8858)). I've reproduced the issue with `*Namespace.FormatCurrency()` and `*Namespace.FormatAccounting()` when the precision is zero, though not one:

```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestFormatNumbers$ github.com/gohugoio/hugo/tpl/lang

--- FAIL: TestFormatNumbers (0.00s)
    --- FAIL: TestFormatNumbers/FormatAccounting (0.00s)
        /Users/paulgottschling/OneDrive/Programming/active-repos/hugo/tpl/lang/lang_test.go:118: 
            error:
              values are not equal
            got:
              "100,00 CHF"
            want:
              "100 CHF"
            stack:
              /Users/paulgottschling/OneDrive/Programming/active-repos/hugo/tpl/lang/lang_test.go:118
                c.Assert(gotFr, qt.Equals, "100 CHF")
            
    --- FAIL: TestFormatNumbers/FormatCurrency (0.00s)
        /Users/paulgottschling/OneDrive/Programming/active-repos/hugo/tpl/lang/lang_test.go:103: 
            error:
              values are not equal
            got:
              "100,00 CHF"
            want:
              "100 CHF"
            stack:
              /Users/paulgottschling/OneDrive/Programming/active-repos/hugo/tpl/lang/lang_test.go:103
                c.Assert(gotFr, qt.Equals, "100 CHF")
            
FAIL
FAIL	github.com/gohugoio/hugo/tpl/lang	0.024s
FAIL
```

I'm working on reproducing this via Hugo template (see my unit test in language_test.go), though I'm still getting acquainted with the repo and haven't managed to get the site to build in the test.

**Comment by ptgott** [comment]
Reproduced this in a unit test that builds the site with the template provided in the issue description (https://github.com/ptgott/hugo/blob/97d12f274272b3fb6824a14cef2f8e0449b05569/hugolib/language_test.go#L141):

```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestLanguageCurrencyAccountingZeroAndOne$ github.com/gohugoio/hugo/hugolib

--- FAIL: TestLanguageCurrencyAccountingZeroAndOne (0.01s)
    /Users/paulgottschling/OneDrive/Programming/active-repos/hugo/hugolib/language_test.go:173: No match for "FormatCurrency with precision 0: 100 CHF<br>" in content for public/fr_ch/index.html
        
        
        FormatCurrency with precision 0: 100,00 CHF<br>
        FormatCurrency with precision 1: 100,00 CHF<br>
        FormatCurrency with precision 2: 100,00 CHF<br>
        FormatCurrency with precision 3: 100,000 CHF<br>
        FormatAccounting with precision 0: 100,00 CHF<br>
        FormatAccounting with precision 1: 100,00 CHF<br>
        FormatAccounting with precision 2: 100,00 CHF<br>
        FormatAccounting with precision 3: 100,000 CHF<br>	
        
        "\n\nFormatCurrency with precision 0: 100,00 CHF<br>\nFormatCurrency with precision 1: 100,00 CHF<br>\nFormatCurrency with precision 2: 100,00 CHF<br>\nFormatCurrency with precision 3: 100,000 CHF<br>\nFormatAccounting with precision 0: 100,00 CHF<br>\nFormatAccounting with precision 1: 100,00 CHF<br>\nFormatAccounting with precision 2: 100,00 CHF<br>\nFormatAccounting with precision 3: 100,000 CHF<br>\t\n"
FAIL
FAIL	github.com/gohugoio/hugo/hugolib	0.034s
FAIL
```

**Comment by ptgott** [comment]
@divinerites It looks like `FormatAccounting` and `FormatCurrency` call the `FmtAccounting` and `FmtCurrency` methods of a `locales.Translator` (https://github.com/gohugoio/hugo/blob/d6c8cd771834ae2913658c652e30a9feadc2a7b7/tpl/lang/lang.go#L83-L109), and always leaving two figures after the decimal is the way these functions are supposed to work (e.g., see: https://github.com/gohugoio/locales/blob/cc6f7907f4213235afe4048a13ea83ed5b213002/fr_CH/fr_CH_test.go#L1010).

@bep should this behavior be documented?

**Comment by jmooring** [comment]
Most currencies have two minor units, but per ISO 4217 there are 17 currencies with zero minor units: BIF, CLP, DJF, GNF, ISK, JPY, KMF, KRW, PYG, RWF, UGX, UYI, VND, VUV, XAF, XOF, XPF.

The [go-playground/locales](https://github.com/go-playground/locales) module, from which [gohugoio/locales](https://github.com/gohugoio/locales) was forked, has no provision for minor unit determination. The minimum number of minor units is always two. For example:

<https://github.com/go-playground/locales/blob/master/en/en.go#L334-L343>

There are two reasons for displaying zero minor units:
1. Stylistic. For example, I want to display $100 instead of $100.00, even though $100.00 is technically correct)
2. Technical. It doesn't make sense to display ¥100.00 because the Japanese yen has no minor units; it should always be displayed as an integer.

I cannot think of a valid reason to display one minor unit, but there could be.

**Comment by divinerites** [comment]
> 1. Stylistic. For example, I want to display $100 instead of $100.00,

This exactly my use case.
The minor units are useless for our customers and we want our prices to be short.

But I can understand why it is technically like this now.
