### ISSUE TITLE
Highlight shortcode produces weird results with longer code blocks

### ISSUE THREAD

**Issue by vendion** [gohugoio/hugo#8861]
With a code block of ~54 lines the resulting output is broken in two significance ways:

1. The number column of the "table" looks off
2. It add extra blank lines at the end of the output

How the highlighted code block looks in Qutebrowser
![Screenshot_20210806_071012](https://user-images.githubusercontent.com/145018/128501968-33abd8eb-4026-4e2b-a230-9c58babf9657.png)

How the highlighted code block looks in Firefox
![Screenshot_20210806_071216](https://user-images.githubusercontent.com/145018/128502157-545cb122-88e6-4676-ba00-47a2936a9292.png)

Affected page: https://vendion.me/blog/2021/08/05/using-git-to-generate-changelogs/#writing-out-the-changelog-file
Content file: https://git.sr.ht/~vendion/vendion.me/tree/master/item/content/posts/using-Git-to-generate-changelogs/index.md?view-source#L94

As you can see in the content file this code snippet does not have 88 lines.

**Comment by vendion** [comment]
Forgot to add in Hugo version, which may be useful:

hugo v0.85.0-724D5DB5+extended freebsd/amd64 BuildDate=2021-07-05T14:23:03Z+0000 VendorInfo=freebsd

**Comment by jmooring** [comment]
This is related to the _length_ of one or more of the lines, not the _number_ of lines.

This is a CSS issue, not a Hugo issue. I suspect you have `white-space` set to `pre-line` or `pre-wrap` instead of `pre`.

**Comment by vendion** [comment]
Where would that be set? All my markup settings are the default as per [this pgae](https://gohugo.io/getting-started/configuration-markup) as I'm not overriding anything in [my own config](https://git.sr.ht/~vendion/vendion.me/tree/master/item/config.toml) nor am I setting anything at the [content level](https://git.sr.ht/~vendion/vendion.me/tree/master/item/content/posts/using-Git-to-generate-changelogs/index.md?view-source#L94).

**Comment by jmooring** [comment]
The nix theme uses Bootstrap:
<https://github.com/LordMathis/hugo-theme-nix/blob/master/layouts/partials/head.html#L15>

```
pre code {
  padding: 0;
  font-size: inherit;
  color: inherit;
  white-space: pre-wrap;           /* THIS IS THE PROBLEM */
  background-color: transparent;
  border-radius: 0;
}
```

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
