### ISSUE TITLE
Duplicate methods of generating shell completion scripts

### ISSUE THREAD

**Issue by marckhouzam** [gohugoio/hugo#8862]
This may not be considered a bug, but I wanted to make the maintainers aware of the situation.

```
$ hugo gen autocomplete -h |head -1
Generates a shell autocompletion script for Hugo.

$ hugo completion -h | head -2
Generate the autocompletion script for hugo for the specified shell.
```

To facilitate the use of shell completion, Cobra 1.2 automatically provides a "completion" command (https://github.com/spf13/cobra/releases/tag/v1.2.0).  This command needs to be explicitly disabled for programs that don't want to use it (https://github.com/spf13/cobra/blob/master/shell_completions.md#adapting-the-default-completion-command).

Hugo 0.87.0 moved to Cobra 1.2.1 and has inherited this new "completion" command.

Note that the "completion" command provided by Cobra is more complete that the one defined in Hugo:
- it provides completion descriptions for Powershell and Bash
- it allows individual users to disable completion descriptions for all shells with the `--no-descriptions` flag
- it uses bash completion V2 which has a 250-line script instead of the 3200-line one generated by Hugo

It is in part to avoid projects missing some of these subtle tweaks that Cobra provides the completion command itself.

### What version of Hugo are you using (`hugo version`)?
0.87.0

### Does this issue reproduce with the latest release?
Yes

**Comment by austintraver** [comment]
Thank you for catching this @marckhouzam , I was using the other one by mistake prior to seeing this issue. 

The `zsh` completions I'm getting now (generated via `hugo completion`) are *incredibly* comprehensive. For those reading this looking to do the same, redirect the output of `hugo completion zsh` to a file named `_hugo`, and locate it within one of the subdirectories set in the `${fpath}` array. Your shell will load the completions the next time you start up a new session.

[Supporting `zsh` documentation](https://zsh.fyi/completion-system#initialization)
