### ISSUE TITLE
Hugo server detects change but does not update 

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#8863]
Setup:

1. Markdown includes a shortcode
2. The shortcode calls a partial
3. The partial contains text

Action:

1. Start hugo server
2. Add some text to the partial

What happens: 

1. The change is detected
2. The site is rebuilt
3. The rendered page is **not** updated in the browser

Reference: <https://discourse.gohugo.io/t/34122>

---

To reproduce:

```bash
git clone --single-branch -b hugo-github-issue-8863 https://github.com/jmooring/hugo-testing hugo-github-issue-8863
cd hugo-github-issue-8863
hugo server
```

Visit `http://localhost:1313/post/test/`

Then, in a separate terminal:

```bash
echo "xxx" >> layouts/partials/foo.html
```

**Comment by DeminYu98** [comment]
Same problem in taxonomies update! 
When append a new class, it wont't appear in category unless clear the browser cache.

**Comment by Ascent817** [comment]
I am having the same problem!

**Comment by eth0-02** [comment]
me too changes not taking place despite a rebuild
