### ISSUE TITLE
Padding issues in Safari

### ISSUE THREAD

**Issue by BDHU** [gohugoio/hugo#8867]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.87.0-B0C541E4 linux/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

Recently, I was compiling my site using my customized [theme](https://github.com/BDHU/hugo-theme-mini),  which is forked from the [mini theme](https://github.com/nodejh/hugo-theme-mini).  The current tag page is shown [here](https://www.bodunhu.com/blog/tags/). The site is generated using hugo `0.83.1`.

However, hugo `0.87.0` (as well as 0.86.x) generated pages has an issue on Safari on Apple devices. The issue is illustrated in the picture below (iPhone Xs, iOS 14):

<p align="center">
  <img width="400" src="https://user-images.githubusercontent.com/9762261/128612650-8c8c7a84-b777-4035-aea1-25b620c0a04b.jpg" alt="Sublime's custom image"/>
</p>

The right padding of every tag's background is ignored. The CSS attributes for `tag` can be found at [https://github.com/BDHU/hugo-theme-mini/blob/master/static/css/style.css#L466](https://github.com/BDHU/hugo-theme-mini/blob/master/static/css/style.css#L466). This problem occurs only on Apple devices with newer version such as hugo `0.87.0` and `0.86.x`. Firefox and Chrome on Windows, Linux, and Android systems don't appear to have such problem even with the latest hugo versions.  hugo `0.83.x` generates correct right padding on all devices include iPhone. Not sure if there are behavior changes in hugo or it's simply a problem related to the theme itself.

**Comment by braderhart** [comment]
I don't want to speak out of place, but it is my understanding that issues here are specific to Hugo software development and you'd want to direct any theme issues to the theme author.
