### ISSUE TITLE
Add a path.Clean function

### ISSUE THREAD

**Issue by brendan-mccoy** [gohugoio/hugo#8885]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.87.0-B0C541E4+extended windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

The issue I'm seeing in windows is that, when using `.File.Path` like so: `<a href="{{ $geekdocRepo }}/{{ $geekdocEditPath }}/{{ .File.Path }}">` or rather, in the theme I'm using, `<a href="{{ $geekdocRepo }}/{{ $geekdocEditPath }}/{{ $.Scratch.Get "geekdocFilePath" }}">`, the backslashes that would be returned in .File.Path used elsewhere will be replaced with %5c, which will cause broken hyperlinks that were built using .File.Path.

I reckon this stems from Windows using backslashes in paths unlike mostly everything else that uses forward slashes (though Windows will accept forward slashes in powershell and explorer). I'm not familiar enough with how URLs to say whether or not the making the HTML parser just not escape backslashes into $5c on URLs, though there's probably plenty of HTML reasons why this gets done.

Without having reviewed the underlying code, I suppose these are possible fixes for this particular breakage (whether they are suitable for other uses, I don't know).

1. Convert the Windows path backslashes to forward slashes on any dot properties, like .File.Path
2. Don't escape backslashes when parsing, or don't escape them when they are in hyperlinks

Probably 1 is a better idea, I can kinda noodle some reasons 2 would break things in my head, but I'm not certain.

In the meantime, I can use `<a href="{{ $geekdocRepo }}/{{ $geekdocEditPath }}/{{ replace ($.Scratch.Get "geekdocFilePath") "\\" "/" }}">` in my partial instead, but it seems to me hugo should internally use the same style of slash independent of OS.

As an aside, if you don't want people who use the search for existing issues or coming from Google to contribute to those extant issues, lock them when they pass your arbitrary age limit that isn't documented, re:https://github.com/gohugoio/hugo/issues/5515#issuecomment-897995182. Perhaps this could be updated alternatively: https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#reporting-issues.

**Comment by pamubay** [comment]
if you want to handle slash difference between os you need to use [`path.Join`](https://gohugo.io/functions/path.join/) function. 
From documentation:
>Note: All path elements on Windows are converted to slash ('/') separators.

e.g.:
```
<a href="{{ path.Join $geekdocRepo  $geekdocEditPath  .File.Path }}">
```

Read More: [path.Join](https://gohugo.io/functions/path.join/)

**Comment by bep** [comment]
There is a longer story here, but the `.File` object is more or less what Go gives us, and they decided some moons ago to keep the slashes as, so I don't think we want to do anything with that. Also, it's very rarely needed.

You can work around this today by `path.Join .File.Dir`.

But I do suggest that we add a `path.Clean` function that does a 

```
filepath.ToSlash 
path.Clean
```

**Comment by bradcypert** [comment]
@bep Mind if I take a crack at this?

**Comment by bep** [comment]
@bradcypert go ahead.

I would expect it to be the output of doing `path.Clean(filepath.ToSlash("foo\bar\biz.txt"))`. And I'm pretty sure none of those do any suffix-removal.

**Comment by bradcypert** [comment]
Sounds good! Here's a PR: https://github.com/gohugoio/hugo/pull/9005
