### ISSUE TITLE
Time zone is ignored in some dates format with space separators

### ISSUE THREAD

**Issue by malcom** [gohugoio/hugo#8891]
On Hugo 87 some variation of RFC3339/ISO8601 dates with space separators (for better human readability) are incorrectly parsed or handled - time zone offset is ignored:

```
{{ "2006-01-02 15:04:05 -07:00" | dateFormat "2006-01-02T15:04:05-07:00" }}
```

```
Hugo87: 2006-01-02T15:04:05+00:00
Hugo86: 2006-01-02T15:04:05-07:00
```

**Comment by tuziemon** [comment]
I sent a pull request to upstream
[https://github.com/spf13/cast/issues/118](https://github.com/spf13/cast/issues/118)
