### ISSUE TITLE
Embed go timezone database in Windows build

### ISSUE THREAD

**Issue by malcom** [gohugoio/hugo#8892]
Hugo87 with specified `timeZone` in config exit on Windows with msg:
```
Error: invalid timeZone for language "en": The system cannot find the path specified.
```

This is a known problem with golang time lib on Windows (golang/go#21881, golang/go#38453) with missing `zoneinfo.zip` file.

User workaround for this problem could be:
- extract `zoneinfo.zip` file from golang distribution and set the path for it in env `%ZONEINFO%`
- install golang distribution

But, it seems a much better solution would be to embed the binary content of this file when building the windows version. Package [tzdata](https://pkg.go.dev/time/tzdata) provides an embedded copy of the timezone database.

**Comment by bep** [comment]
One learns something new every day. We have tests that run on Windows, but those servers all have Go installed.

I have pushed a fix for this, a fix I don't have any easy way to verify myself. I assume it will work, but it would be good if someone could chime in and tell me that it works.

**Comment by malcom** [comment]
I could test, but I'm not a Go programmer, so if you provide the v0.88-dev build, I'll check on Win7 and 10.

**Comment by bep** [comment]
[hugo088.exe.zip](https://github.com/gohugoio/hugo/files/6986686/hugo088.exe.zip)

@malcom attached is the dev build (extended version) for Windows.

**Comment by malcom** [comment]
I tested and confirm that it works correctly :)
