### ISSUE TITLE
resources.Get throwing error with argument from shortcode parameter

### ISSUE THREAD

**Issue by danisztls** [gohugoio/hugo#8896]
## Environment
`hugo v0.87.0+extended linux/amd64 BuildDate=unknown`

## Issue
I don't know if this is a bug or just a *leaky abstraction* but inside a shortcode...

**...this work as expected:**

```html
{{ $src := "image.jpg" }} 
{{ $image := resources.Get $src }}
<img src="{{ $image.RelPermalink }}">
```

**while this doesn't:**

```html
{{ $src := .Get "src" }} 
{{ $image := resources.Get $src }}
<img src="{{ $image.RelPermalink }}">
```

throwing this error:

`Error: Error building site: "/site/content/my-page.md:56:1": failed to render shortcode "image": failed to process shortcode: "/site/themes/my-theme/layouts/shortcodes/image.html:8:18": execute of template failed: template: shortcodes/image.html:8:18: executing "shortcodes/image.html" at <$image.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink`

**Comment by danisztls** [comment]
Is this related to #7960?

**Comment by jmooring** [comment]
How are you calling the shortcode?

**Comment by bep** [comment]
Curious, what do you mean by _leaky abstraction_ in this particular context?

**Comment by danisztls** [comment]
@jmooring I'm not using page bundles.

The shortcode is called by the following on `content/section/page.md`

```liquid
{{< image src="/img/subdir/image.jpeg" alt="Description" width="640" height="400">}}
```

Note: I moved the `img` dir to `assets/`.

Note 2: Currently I'm using it without problems with `src="{{ .Get "src" }}"` and images under `static/`.

**Comment by jmooring** [comment]
In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by danisztls** [comment]
> Curious, what do you mean by _leaky abstraction_ in this particular context?

Because in my limited high level (superficial) undestanding the method `resources.Get` can be used like this. But maybe there are limitations for it that are not clear to anyone reading the documentation or at least for me.

> That said, `resources.Get` is the exact same function in both scenarios.

It is but the later does not work.

**Comment by danisztls** [comment]
@jmooring Thanks and in the future I will to that. But as far as I know this is not invalid and not solved. Why it is invalid?

**Comment by danisztls** [comment]
Link to dicussion (just opened): https://discourse.gohugo.io/t/resources-get-throw-error-if-argument-is-a-shortcode-parameter/34299
