### ISSUE TITLE
Expose timezone configuration to templates

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#8902]
#### Syntax

```
{{ .Site.TimeZone }}
```

#### Justification

I was trying to write a partial that would accept timezone (location) as one of its args:

```
{{ partial "my-time-func" (dict "time" .Lastmod "location" "America/Denver") }}
```

It would be nice to be able to do this as well:

```
{{ partial "my-time-func" (dict "time" .Lastmod "location" site.TimeZone) }}
```

I will submit a PR if approved.

**Comment by bep** [comment]
We currently have `*time.Location` set as an unexported field on `Language`. The `time` func currently use `time.LoadLocation` to load the location, which is, I suspect, a non-trivial operation. 

I'm not sure you would ever need the time zone string, so I suggest we:

Export location and allow both a string and a `*time.Location` in the time func, so you can do `{{ time "2020-10-20"  site.Language.Location }}`.
