### ISSUE TITLE
Org-mode link abbreviations don't work

### ISSUE THREAD

**Issue by tsoutsman** [gohugoio/hugo#8921]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.87.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

# The issue
Org-mode allows for link abbreviations as follows:
```
#+TITLE: Example
#+LINK: foo https://google.com

[[foo]]
```
but Hugo does not understand these and sends you to the `/foo` subpage as if the link abbreviation didn't exist.

This issue is not present in the equivalent Markdown:
```markdown
---
title: Example
---

[foo]

[foo]: https://google.com
```

Hugo seems to be using [go-org](https://github.com/niklasfasching/go-org/) as its Org parser. According to [this issue](https://github.com/niklasfasching/go-org/issues/19) go-org should support link abbreviations. I don't know Go and how dependencies work, but could Hugo potentially be using an outdated version of go-org?

**Comment by bep** [comment]
We use github.com/niklasfasching/go-org@v1.5.0 -- the latest release.
