### ISSUE TITLE
Make kind=404 into a more general status kind

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8924]
I'm doing some consolidation work in this area, which will get all of Hugo's `Pages` into the same data structure.

The `404` kind is mostly internally in Hugo, I hope (there may be some CSS classes in the wild), but it does not make much sense to have such a specific kind, esp. considering the open issues(s) asking for more error/status pages.

So, I suggest we rename it to `status` (as in HTTP status). We should probably also let people set (or override) it in front matter, but that is a slightly different issue.

The default `build` options for these status pages will be that:

* They will be rendered
* They can be fetched via `site.GetPage "404"` etc.
* But they will not be promoted to any page collection

/cc @regisphilibert @jmooring

**Comment by regisphilibert** [comment]
Really glad this is on the roadmap, but it raises a few questions.

If this is about creating a new kind then I suppose this would mean new template files like `layouts/_default/status.html`, `layouts/post/status.html`

How would the user pass a status value through Front Matter for a kind? And how would they choose the proper template for any given status code: `layouts/_default/status.404.html`?

**Comment by jmooring** [comment]
@bep Thanks for the shout, but I've never understood the need for the built-in 404 functionality in a production environment (configured accordingly) when you can do:

```
content
└── errors/
    ├── 400.md
    ├── 401.md
    ├── 403.md
    ├── 404.md
    └── _index.md
layouts
└── errors/
    └── single.html
```

content/errors/_index.md

```toml
[_build]
  list = 'never'
  render = 'never'
[cascade._build]
  list = 'never'
```

**Comment by bep** [comment]
You are both right. @jmooring the 404 is mostly a "historic thing" ... But I'll leave this issue open. I will keep the 404 kind (for now) and just make it behave as described above (re the default build options).

**Comment by SelfAdjointOperator** [comment]
\*Bumping / showing interest\*
It is a bit funny that `layouts/404.html` is treated specially but say `layouts/403.html` isn't

**Comment by bep** [comment]
This is fixed.
