### ISSUE TITLE
Add outputFormat.Ugly

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8927]
I'm in the process of getting the 404 and some other similar pages into the same data structure as the rest, and in its default setup, 404 pages is _ugly_, that is, they get rendered to `/404.html`. 

This has been asked for by others before. The current workaround for similar stuff is to set the global `uglyURLs=true` and then set `noUgly=true` on the `OutputFormat`. This isn't particular practical.

**Comment by BBaoVanC** [comment]
Just to clarify - do you mean a property in `hugo.yaml` that's `outputFormats.[format_name].ugly`? And presumably this would deprecate the `.noUgly` field?
