### ISSUE TITLE
Weird cache-related issue with image processing .Resize

### ISSUE THREAD

**Issue by geekman** [gohugoio/hugo#8931]
### What version of Hugo are you using (`hugo version`)?

It's the official release of 0.87 Extended for Windows 64bit:

    $ hugo version
    hugo v0.87.0-B0C541E4+extended windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio

### Does this issue reproduce with the latest release?

Yes

# Minimal Test Case

Blank site, generated using `hugo new site`, with just these files.

`content/posts/a/index.md`: just a post. content is unimportant. 
`content/posts/a/file.jpg`: JPEG image as a resource to the post

`layouts/_default/single.html`:
```
{{ range .Resources }}
	{{ .Name }} {{ .MediaType }}

	{{ $webp := .Resize "100x webp" -}}
	{{ $webp.Name }} {{ $webp.MediaType }}
{{ end }}
```

Run `hugo` to generate the files:
```
D:\hugotest>hugo
Start building sites …
hugo v0.87.0-B0C541E4+extended windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
WARN 2021/08/26 22:42:34 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/08/26 22:42:34 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/08/26 22:42:34 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/08/26 22:42:34 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN
-------------------+-----
  Pages            |  5
  Paginator pages  |  0
  Non-page files   |  1
  Static files     |  0
  Processed images |  1
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Total in 66 ms
```

Inspect the output is correct, as expected:
```
D:\hugotest>more public\posts\a\index.html

        file.jpg image/jpeg

        file.jpg image/webp
```

Run `hugo` again:
```
...
                   | EN
-------------------+-----
  Pages            |  5
  Paginator pages  |  0
  Non-page files   |  1
  Static files     |  0
  Processed images |  1
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Total in 39 ms
```

Inspect the output file again:
```
D:\hugotest>more public\posts\a\index.html

        file.jpg image/jpeg

        file.jpg image/jpeg
```

Notice the output of `$webp.MediaType` is now `image/jpeg`.

I understand that files are generated in `resources/_gen` and those need to be GC-ed. But specifying `--gc` to Hugo doesn't fix the problem.

It can only be fixed when the whole `resources` directory is deleted.

The file contents itself is correct. `$webp.Content` will get a WebP image, not a JPEG one, but the MIME type is wrong here.

I don't think this is supposed to happen, as it's working correctly the first time. Subsequent builds, or `hugo serve`, will yield weird results because of this.

**Comment by jmooring** [comment]
Verified. This cost me a couple of hours today, trying to figure out why the `MediaType` was wrong when building `<source>` elements within a `<picture>` element.

MRE: 

```bash
git clone --single-branch -b hugo-github-issue-8931 https://github.com/jmooring/hugo-testing hugo-github-issue-8931
cd hugo-github-issue-8931
```

The first run will look fine.

```bash
hugo && cat public/tests/test-1/index.html
```

The next run will be wrong:

```bash
hugo && cat public/tests/test-1/index.html
```

To obtain the correct results, you _must_ remove the cached images:

```bash
rm -rf resources/_gen/images/* && hugo && cat public/tests/test-1/index.html
```

Summary:
1. The problem _appears_ to be limited to the value of `MediaType`. 
2. The problem _always_ occurs when running hugo server.
3. You can work around the problem when running hugo (but not hugo server) by removing the cache before each run, which can be expensive.

**Comment by jmooring** [comment]
This came up again today:
<https://discourse.gohugo.io/t/mediatype-of-converted-image-resource-does-not-change-after-conversion/38215>
