### ISSUE TITLE
i18n functionality breaks with some language codes

### ISSUE THREAD

**Issue by jamiebrynes7** [gohugoio/hugo#8934]
### Description

If you use a language code like `zh_CN` or any other with underscores, you will be unable to use the [string localization functionality](https://gohugo.io/content-management/multilingual/#translation-of-strings) in Hugo.

This is because when Hugo loads in the `i18n` files, the language code is transformed:

https://github.com/gohugoio/go-i18n/blob/4c28c89f8013a686b0ef5a0ebcb063a586a3ba7f/v2/i18n/parse.go#L23

This causes a transformation like: `zh_CN` -> `zh-CN`, meaning when we attempt to lookup the translation func for `zh_CN`, its not found: 

```
INFO 2021/08/27 11:55:35 Translation func for language zh_cn not found, use default.
```

While such a language code isn't standard, the [docs do suggest that this would work](https://gohugo.io/content-management/multilingual/#missing-translations)

> From Hugo 0.31 you no longer need to use a valid language code. It can be anything.

A possible fix would be to do a similar transformation before looking up the translation func:

https://github.com/gohugoio/hugo/blob/f55d2f43769053b80b419a690554e747dc5dcede/langs/i18n/i18n.go#L51-L64

You can find a repro case at https://github.com/jamiebrynes7/hugo-repro-i18n

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.87.0-B0C541E4+extended windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by past-due** [comment]
Possibly related: #7982
