### ISSUE TITLE
Add hugo.Deps

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8949]
There are situations where it would be useful to have the Hugo Module dependency information available in the templates (mostly, for JS libraries built from /assets, to know: What version of this library is currently running?).

So I propose we add `hugo.Deps` that lists the dependencies with some basic info:

* Path (e.g. `github.com/bep/mylib`)
* Version (e.g. `v1.0.0`)
* Hash (source hash)

~~And then a lookup method so you can do `$mylib := hugo.Deps.ByPath "foo"`~~

**Comment by regisphilibert** [comment]
Do we need a lookup method? Can't `where` do the job?
