### ISSUE TITLE
minify | fingerprint does not work with an explicit new Date()

### ISSUE THREAD

**Issue by yolpsoftware** [gohugoio/hugo#8954]
### What version of Hugo are you using (`hugo version`)?
The issue appears in Hugo 0.81.0 and higher versions up to the current 0.88.0. The bug is not in 0.80.0 or previous versions. I suspect the cause to be in https://github.com/gohugoio/hugo/commit/66beac99c64b5e5fe7bec0bda437ba5858d49a36

<pre>
hugo v0.81.0-59D15C97+extended windows/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

## Issue

We have various Javascript files that we include in the layout with

```
{{ range .Resources.Match "*.js" }}
  {{ $js := . | minify | fingerprint }}
  <script defer type="text/javascript" src="{{ $js.RelPermalink }}" integrity="{{ $js.Data.Integrity }}"></script>
{{ end }}
```

One Javascript file contains an explicit date creation: `new Date(2002, 04, 11)`. This file does not get minified, and the `integrity` attribute is wrong such that the file is not loaded by the browser.

I isolated the problem to the following minimal Javascript file:

```
new Date(2002, 04, 11)
```

If this file gets included via `. | minify | fingerprint`, the file is not minified in the output, and the integrity attribute is erroneous.

If the explicit Date creation is removed or replaced by the equivalent `new Date(1021068000000)`, the problem goes away.

**Comment by jmooring** [comment]
I tested this with the [tdewolff/minify online demo](https://go.tacodewolff.nl/minify?q=bWltZT10ZXh0JTJGamF2YXNjcmlwdCZjc3MtcHJlY2lzaW9uPTAmasSZxJvEncSfxKHEo8SlxKfEosSaxJzEnsSgxKLEpCZzdmfEscSqxLTErcS3cmM9bmV3K0RhxIUoMjAwMsSJQyswNMWPKzExKSUzQg==):

```text
legacy octal numbers are not supported in arguments on line 1 and column 16
    1: new Date(2002, 04, 11);
                      ^
```

Workaround: replace `04` with `4`.

Underlying problems:
1. tdewolff/minify seems to use strict mode when parsing
2. Hugo doesn't capture/throw errors from tdewolff/minify

**Comment by yolpsoftware** [comment]
Yes, at least we should see a warning. I didn't notice the problem at first and then pushed some changes to our staging environment. Turns out, on one of the pages, one javascript file didn't load anymore. Hugo still seems to include the file, but it is not minified.

**Comment by jmooring** [comment]
A simple failing test:

```
{{ (resources.FromString "temp.js" "const a = 04" | minify).Content }}
```

This produces nothing, and should throw:

```
legacy octal numbers are not supported in expression on line 1 and column 11
    1: const a = 04
                 ^
```
