### ISSUE TITLE
hugo: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by hugo)

### ISSUE THREAD

**Issue by rrjanbiah** [gohugoio/hugo#8955]
### What version of Hugo are you using (`hugo version`)? 

hugo_extended_0.88.0_Linux-64bit.deb 

<pre>
$ hugo version
hugo: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by hugo)
</pre>

### Does this issue reproduce with the latest release?

Yes

### Context

1. Installed `hugo` in Ubuntu 16.04 using `sudo apt-get install hugo` and that installed older version (0.16?? forgot it)
2. Tried to setup 'portio' theme and came across SAAS not compiling issue (https://github.com/StaticMania/portio-hugo/issues/17) and came to know that I have to install hugo extended from the releases using `sudo dpkg -i hugo_extended_0.88.0_Linux-64bit.deb`
3. Then the whole `hugo version` command started to fail with: `hugo: /lib/x86_64-linux-gnu/libm.so.6: version ``GLIBC_2.29' not found (required by hugo)
hugo: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version ``GLIBCXX_3.4.26' not found (required by hugo)
`
4. Searched for solution and https://stackoverflow.com/questions/36816570/glibcxx-3-4-21-not-defined-in-file-libstdc-so-6-with-link-time-reference/60728921#60728921 fixed `hugo: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version ``GLIBCXX_3.4.26' not found (required by hugo)`
5. After that, getting `hugo: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by hugo)` for `hugo version'. Couldn't find any solution for  `GLIBC_2.29' not found` error.

**Comment by jmooring** [comment]
Options:

1. Upgrade your distribution to 19.04 or later
2. Use snap (fast, easy)

   ```bash
   sudo snap install hugo --channel=extended/stable
   ```

3. Use [brew](https://brew.sh/)

   ```bash
   sudo apt-get install curl
   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   # Then perform "Next steps" as shown
   brew install hugo
   ```

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by klakegg** [comment]
@jmooring, what changed in 0.88.0 from 0.87.0 regarding support for older Linux versions?

**Comment by jmooring** [comment]
Reopening. I did not realize that this was new behavior.

**Comment by klakegg** [comment]
The 4th option is to download Hugo 0.88.0 from over here:
https://github.com/hugoguru/dist-hugo/releases/tag/v0.88.0

**Comment by chrisrummel** [comment]
Yes this is a new behaviour, I am on Ubuntu 16.04 LTS here (can't update since it is a hosted vserver), 0.87 was fine, 0.88 throws the errors mentioned above. System is on glibc 2.23.

**Comment by bep** [comment]
So, I got this on the Hugo Netlify builds as well {where the solution is to ugrade the never non-legacy builds). I will sew how  can somehiw fiix---this.

**Comment by jakejarvis** [comment]
Vercel too, unfortunately. If anyone needs an urgent workaround it's always possible to build the site via GitHub Actions or another CI and push the output to Netlify/Vercel from there.

**Comment by bep** [comment]
I have "fixed" this in 0.88.1 by downgrading the build image, but keep this issue open to track the "proper fix".

**Comment by brycewray** [comment]
@jakejarvis Can confirm this fixes the Vercel build issue:
https://gm-typographer.vercel.app/

**Comment by bep** [comment]
>Hugo too if this is a Go 1.17 change, right

Note that this is not a Go change. I rebuild a Docker image on Go upgrades and there seem to be a "apt get" in there that has auto upgraded libc, which was not intentional.
