### ISSUE TITLE
Multilingual page with slug produces wrong .RelPermalink

### ISSUE THREAD

**Issue by Kissaki** [gohugoio/hugo#8970]
hugo version  
hugo v0.88.1-5BC54738+extended windows/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio

As per [documentation page](https://gohugo.io/content-management/multilingual/#localizing-permalinks) slugs can be changed with front matter (for non-default-languages).

However, a pages .RelPermalink links to wrong slug - the file folder name.

The .Language value is correct and the .RelPermalink does link to the correct language subpath.

**Comment by techmagus** [comment]
Do you have a sample repo which reproduces what you encountered? There are different ways to setup a multilingual site, for example in my case, I use folder-based setup like so:

```
/content/blog/eng-ph/
/content/blog/nihongo/
/content/blog/hangugeo/
```
which shows up respectively as:
```
example.com/
example.com/ja/
example.com/ko/
```
With this setup, I don't have problems using slug, aliases, and url frontmatter params.

^^

**Comment by Kissaki** [comment]
I think setting the slug simply does not work - contradicting the documentation. All pages will use the folder name.

I will try to create a sample project soonish.

**Comment by flortsch** [comment]
Also stumbled upon this. You have to set the permalink setting to actually use the slug variable I think.

**Comment by Kissaki** [comment]
I verified the behavior in a clean new project.

The [Multilingual Mode - Localizing permalinks documenation says](https://gohugo.io/content-management/multilingual/#localizing-permalinks):

> Because paths and filenames are used to handle linking, all translated pages will share the same URL (apart from the language subdirectory).
> 
> To localize the URLs, the slug or url front matter param can be set in any of the non-default language file.
> […]
> At render, Hugo will build both /about/ and /fr/a-propos/ while maintaining their translation linking.

Notable also [Bypassing default linking](https://gohugo.io/content-management/multilingual/#bypassing-default-linking) with `translationKey`.

The first paragraph is very confusing. It says “all translated pages share the same URL”, which seems to directly contradict the translation key linking of different URLs as well as the second paragraph saying localized pages can configure a different slug or URL. I don’t get that?

From my testing leaf bundles behave to my expectations for the most part. TranslationKey linking works, and setting slugs works.

Unexpected to me on leaf bundles: The slug being used is not the folder name but the slugified title (so differing between languages too).

For branch bundles, it uses the folder name. Setting a slug has no effect.

**Comment by Kissaki** [comment]
I see.
