### ISSUE TITLE
You need the extended version to build SCSS/SASS

### ISSUE THREAD

**Issue by kamzar1** [gohugoio/hugo#8975]
hugo v.  v0.88.1-5BC54738
Windows 10
Followed the instructions here:
[quick-start Step-5](https://gohugo.io/getting-started/quick-start/#step-5-start-the-hugo-server)
Throws:

```
c:\Hugo\Sites\sample.net>hugo server -D
Start building sites …
hugo v0.88.1-5BC54738 windows/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
Error: Error building site: TOCSS: failed to transform "ananke/css/main.css" (text/css). Check your Hugo installation; you need the extended version to build SCSS/SASS.
Built in 52 ms
```

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by reinerj** [comment]
Same problem on MacOS with grew and binary package:

hugo v0.88.1+extended darwin/arm64 BuildDate=unknown

Error: Error building site: TOCSS: failed to transform "scss/style.scss" (text/x-scss): SCSS processing failed: file "stdin", line 131, col 12: no mixin named mobile
Built in 26 ms

Same code compile on a linux system with the same release without problems

**Comment by jmooring** [comment]
@reinerj 

1. Closed issues are... closed. 
2. You have a different problem. 
3. Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
