### ISSUE TITLE
Preact/compat support for js build

### ISSUE THREAD

**Issue by zner0L** [gohugoio/hugo#8977]
If one wants to seriously use preact with React components, one needs to be able to alias React with `preact/compat` in the resolve. This can be done by using a esbuild plugin, as suggest in [this issue](https://github.com/evanw/esbuild/issues/266#issuecomment-787212174). That is actually very similar to how [the shims are currently done](https://github.com/gohugoio/hugo/blob/022c4795510306e08a4aba31504ca382d41c7fac/resources/resource_transformers/js/options.go#L180) in hugo. It seems, however, that these only work for imports from the `assets` folder and not for aliasing in the `node_modules`. Since I am not that familiar with how hugo handles this, I don't know why this is.

To support preact/compat in the js build, I am proposing two options:
 - somehow allowing shims to also affect the `node_modules` (if there is reason why this is a bad idea, please tell me, I want to learn!)
 - add another option `aliases` that work like suggested in the aforementioned issue comment

**Comment by bep** [comment]
I haven't looked into the preact case, but you're not correct with a general remark saying that "shims does not work with node_modules".

I have an example of it working here:

**Comment by zner0L** [comment]
Hm, I looked at your example, but that does not address my problem. I am not trying to shim an import *from* `node_modules`, I am trying to shim an import, were the importing file *is located in* `node_modules`. The way I read [your code](https://github.com/gohugoio/hugo/blob/1cabf61ddf96b89c95c3ba77a985168184920feb/resources/resource_transformers/js/options.go#L210), this is not handled by the shim plugin, though, but only by esbuild.

This is consistent with the errors I get when I try to use your example:
```
ERROR 2021/09/17 14:49:33 js.Build failed: Could not resolve "react" (mark it as external to exclude it from the bundle)
```

**Comment by bep** [comment]
OK, then I understand, but I still don't understand why it doesn't work. It would probably be easier if you could create a small example project on GitHub.

**Comment by zner0L** [comment]
I forked your example project to demonstrate: https://github.com/zner0L/hugoTestProjectJSModImports

To me, its seems like the problem is that if the importer is not in the the `assets` folder, the default resolver is used without using the potentially rewritten path:
https://github.com/gohugoio/hugo/blob/1cabf61ddf96b89c95c3ba77a985168184920feb/resources/resource_transformers/js/options.go#L209-L215

I assumed this is expected behavior, but if there is no good reason for this, it should be easy to change.

**Comment by tedeh** [comment]
I had this problem too. Preact would work with Hugo but any dependencies in `node_modules` that themselves `require`'d React would fail on Hugo compile. Such as for example `react-bootstrap`.

For me the solution was to add the following dependencies in my `package.json`:

```json
{
  "dependencies": {
    "react": "npm:@preact/compat@17.0.2",
    "react-dom": "npm:@preact/compat@17.0.2"
  }
}
```

It sort of looks like an alias, doesn't it? Quacks like a duck and all that... I didn't even need to use the Hugo `js.Build` shims option.

This was actually mentioned in the issue @zner0L linked, per this comment: https://github.com/evanw/esbuild/issues/266#issuecomment-787219187
