### ISSUE TITLE
.Date.Format "02 Jan 2020, 15:04" computes incorrect year

### ISSUE THREAD

**Issue by TiTi** [gohugoio/hugo#8983]
### What version of Hugo are you using (`hugo version`)?

<pre>
v0.88.1
</pre>

### Does this issue reproduce with the latest release?

yes

### The issue

When using:
```
{{ .Date.Format "02 Jan 2020, 15:04" }}
```
The output if completely incorrect for the year.
For instance, with `date: 2018-12-09T21:57:00+01:00` in my article markdown, i get: `09 DEC 9090, 21:57`
Expected:  `09 DEC 2018, 21:57`

If i switch to:
```
{{ .Date.Format "02 Jan 2006, 15:04" }}
```
everything is fine in the output...

Other samples:
* `date: 2018-12-03T00:05:00+01:00` => `03 Dec 3030, 00:05`
* `date: 2017-08-06T22:40:00+01:00` => `06 Aug 6060, 22:40`
* `date: 2017-07-31T22:55:00+01:00` => `31 Jul 31310, 22:55`
* `date: 2015-05-18T20:42:00+01:00` => `18 May 18180, 20:42`

Did i miss something or is it a bug with "2020" ?

**Comment by bep** [comment]
>Did i miss something or is it a bug with "2020" ?

`2006` is the only valid Go date format identifier for year.
