### ISSUE TITLE
Missing docker images for version v0.88.1

### ISSUE THREAD

**Issue by olblak** [gohugoio/hugo#8987]
It appears that version 0.88.1 is not available on DockerHub.
I assume it should have been published considering that the release [v0.88.1](https://github.com/gohugoio/hugo/releases/tag/v0.88.1) is published 

```docker pull klakegg/hugo:0.88.0-asciidoctor ``` works, but ```docker pull klakegg/hugo:0.88.1-asciidoctor``` is not

**Comment by bep** [comment]
You need to ask @klakegg  about this.
