### ISSUE TITLE
Allow block templates to return their value

### ISSUE THREAD

**Issue by doompadee** [gohugoio/hugo#8988]
I don't know whether this is feasible, but just as you already can with partial functions, it would be nice to be able to store the output of base blocks. This would allow me to control the execution order of my templates and enable inter template communication.

For example: I have a shortcode that generates HTML code that uses a few icons from a font so I have to include this font with all my pages. But I would prefer to add the font only to those pages that actually use it.

Another case is a shortcode that dynamically generates css styles. I currently have to use an inline style tag, but I would prefer to be able to add the style information to the head section (to be compliant with the spec and improve performance).

`baseof.html`
```html
...
{{ $main := block "main" . }}{{ end }}
{{ $head := partial "head.html" . }}
{{ $head }}
<body>
{{ $main }}
</body>
...
```

**Comment by jmooring** [comment]
@doompadee

> I have a shortcode that generates HTML code that uses a few icons from a font so I have to include this font with all my pages. But I would prefer to add the font only to those pages that actually use it.

> Another case is a shortcode that dynamically generates css styles. I currently have to use an inline style tag, but I would prefer to be able to add the style information to the head section.

It seems like both of these examples are easily addressed with `.HasShortcode`.

<https://gohugo.io/templates/shortcode-templates/#checking-for-existence>

**Comment by doompadee** [comment]
@jmooring
On first glance, yes. But `.HasShortcode` unfortunately does not work if you use pagination. Shortcodes present on included subpages are not detectable on the root page. Therefore the need for a different mechanism (or maybe expand the current one).

I'd really love this feature. Currently I rely on scratchpad with results in a horrible development experience, because it is always cleaned up on rebuilds.
