### ISSUE TITLE
substr trim barfs on 1char

### ISSUE THREAD

**Issue by josephborg** [gohugoio/hugo#8993]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.81.0-DEV/extended openbsd/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

```
{{ $path := "/"}}
{{ $path := ( substr $_path 0 -1 ) }}
{{ $path :=  printf "/js/%s/%s" $path "code.js" }}
```
produces:

```js//boot.js```

not a problem for unix paths but it's not expected behaviour.

if I change ```$path``` to ```"XX/"``` the output is as expected ```js/XX/boot.js```

**Comment by jmooring** [comment]
In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
