### ISSUE TITLE
config baseUrl with https://example.io/ but got https://example.io:1313/ for static file

### ISSUE THREAD

**Issue by tmsi-io** [gohugoio/hugo#8999]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.88.1-5BC54738
</pre>

### Does this issue reproduce with the latest release?
i'm a new user for hugo , when i use command like this:
<pre>
hugo server --theme=hyde --buildDrafts --source=/opt/blog   --config config.toml  --baseUrl=https://example.io/
</pre>
and set a nginx proxy with port 80  between hugo and browser.
i got css file path eg: https://example.io:1313/a.css in browser html content, but i want get  https://example.io/,  any config can do this?

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
