### ISSUE TITLE
Expose paginate as a site variable

### ISSUE THREAD

**Issue by thinegen** [gohugoio/hugo#9003]
Currently, the paginators default pagesize can only be accessed through `Paginator.PageSize`. This results in the Paginator caching the call with its arguments and leads to constructs such as

```
{{ $paginator := "" }}
{{ if $someBool }}
  {{ $paginator = .Paginate $pagesToPaginate .Site.Params.specialPageSize }}
{{ else }}
  {{ $paginator = .Paginate $pagesToPaginate }}
{{ end }}
{{ range $paginator.Pages }}
```
to change a lists PageSize dynamically.

A nicer version would be something like 

```
{{ $pageSize := .Site.Paginate }}
{{ if $someBool }}
  {{ $pageSize = .Site.Params.specialPageSize }}
{{ end }}
{{ $paginator := .Paginate $pagesToPaginate $pageSize }}
{{ range $paginator.Pages }}
```

**Comment by bep** [comment]
I see where you're coming from. I have been hesitant to expose configuration values to the templates, as whenever we've done it in the past it has in general been a bad idea for several reasons.

In your example above, what makes the first version ugly is that you have to init the variable to a different type. If you had written the above in Go, I'm not sure I would agree about the "prettier":

```go
var paginator Paginator
if pageSize != 0 {
   paginator = Paginate(pageSize)
} else {
   paginator = Paginate()
}
```

The above is admittingly more verbose than in other languages (e.g. JavaScript), but ...

Is this possible?

```html
{{ $paginator := null }}
{{ if $someBool }}
  {{ $paginator = .Paginate $pagesToPaginate .Site.Params.specialPageSize }}
{{ else }}
  {{ $paginator = .Paginate $pagesToPaginate }}
{{ end }}
{{ range $paginator.Pages }}
```

**Comment by thinegen** [comment]
Yeah, i wouldnt mind the construct in other languages. The alternative looks nicer, but it threw an error: `function null not defined` (under `hugo v0.88.1+extended linux/amd64 BuildDate=unknown`). I am going to leave it like it is, since it works.

If you think it's valuable, I could add the snippet (with the quotes) as a hint in the docs under `/templates/pagination/#additional-information`.

**Comment by jmooring** [comment]
@bep Would you accept a PR that would allow you to do this?

```
{{ $pageSize := 0 }}
{{ if $someBool }}
  {{ $pageSize = .Site.Params.specialPageSize }}
{{ end }}
{{ $paginator := .Paginate $pagesToPaginate $pageSize }}
```

If page size is <= 0, use the default value instead. PR would include docs update.

**Comment by reorx** [comment]
Subscribed to this issue, currently I'm using the code below:

```
{{ $paginator := "" }}
{{ if (.Param "paginate") }}
  {{- $paginator = .Paginate $pages (.Param "paginate") }}
{{ else }}
  {{- $paginator = .Paginate $pages }}
{{ end }}
```
> Didn't use `null` because `function "null" not defined`.

Would really wish it to be:

```
{{ $paginator := .Paginate $pages (.Param "paginate" | default .Site.Paginate) }}
```
