### ISSUE TITLE
Question regarding commit ecf025f in the README

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#9025]
I recently updated my Hugo fork and I am quite perplexed by the following commit:

[ readme: Remove tracking image](https://github.com/gohugoio/hugo/commit/ecf025f006f22061728e78f2cf50257dde2225ee)

Since when did the Hugo README contain a tracking pixel? Also who is the contributor @kambojshalabh35 ? He is not in the repo's [contributors list](https://github.com/gohugoio/hugo/graphs/contributors)? 

Please do take the time to clarify.

**EDIT**
Also this is not a proposal, so please remove that tag from this issue.

**Comment by kambojshalabh35** [comment]
> I recently updated my Hugo fork and I am quite perplexed by the following commit:
> 
> [ readme: Remove tracking image](https://github.com/gohugoio/hugo/commit/ecf025f006f22061728e78f2cf50257dde2225ee)
> 
> Since when did the Hugo README contain a tracking pixel? Also who is the contributor @kambojshalabh35 ? He is not in the repo's [contributors list](https://github.com/gohugoio/hugo/graphs/contributors)?
> 
> Please do take the time to clarify.
> 
> **EDIT** Also this is not a proposal, so please remove that tag from this issue.

sir, actually there was a tracking image " [![Analytics](https://ga-beacon.appspot.com/UA-7131036-6/hugo/readme)](https://github.com/igrigorik/ga-beacon) " and as their server was not responding and there were no updates regarding so from the tracking image maintainers, so it's better to remove the link. 

If you think it was not the right decision to remove it, please apologize to me.

**Comment by onedrawingperday** [comment]
@kambojshalabh35 

This is the master repository for the Hugo static site generator: https://gohugo.io/ 

I browsed the [README's history](https://github.com/gohugoio/hugo/blob/64f88f3011de5a510d8e6d6bad8ac4a091b11c0c/README.md) just before your commit and I couldn't find any trace of a tracking pixel.

Not sure what is going on here. Were you given permission to commit directly in this repo?

Perhaps @bep knows something.

This seems like an issue for GitHub support.

**Comment by kambojshalabh35** [comment]
> @kambojshalabh35
> 
> This is the master repository for the Hugo static site generator: https://gohugo.io/
> 
> I browsed the [README's history](https://github.com/gohugoio/hugo/blob/64f88f3011de5a510d8e6d6bad8ac4a091b11c0c/README.md) just before your commit and I couldn't find any trace of a tracking pixel.
> 
> Not sure what is going on here. Were you given permission to commit directly in this repo?
> 
> Perhaps @bep knows something.
> 
> This seems like an issue for GitHub support.

![image](https://user-images.githubusercontent.com/71832334/136741778-e63de24e-49d6-49db-9d7a-fb8f7055878d.png)

Sir, you can clearly see here the tracking image was present there and the image was not responding.

**Comment by onedrawingperday** [comment]
Right. So I looked further back into the repo history and it seems that tracking has been present in the README since the very beginning.

https://github.com/gohugoio/hugo/commit/247db151fa296d26c84a4f78199470e80f156a96

Ok. I'm closing this issue now. 

Sorry for the noise @kambojshalabh35
