### ISSUE TITLE
releaser: Set up fat binaries for macOS

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9035]
https://github.com/goreleaser/goreleaser/releases/tag/v0.182.1

I suggest we just produce fat binaries for macOS; a little bigger files, but much easier for people to reason about.

**Comment by XhmikosR** [comment]
@bep a quick question since I'm not familiar with macOS and I'm in the middle of updating https://github.com/fenneclab/hugo-bin: does the new binary support ia32 too? Or is it only x64 and arm64?

**Comment by bep** [comment]
>Or is it only x64 and arm64?

Only 64 bit; but we have not produced 32 bit MacOS binaries for some time now (they stopped supporting that in Go at some point).

**Comment by XhmikosR** [comment]
Thanks! I'll adapt the package then.

**Comment by XhmikosR** [comment]
BTW I don't suppose you know how one can test arm64 on either Windows or macOS? Testing this would increase our coverage and the chances to break things.
