### ISSUE TITLE
Lighthouse accessibility analysis complains about deprecated `doc-endnote` roles

### ISSUE THREAD

**Issue by schnerring** [gohugoio/hugo#9054]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.88.1-5BC54738+extended windows/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

Running Lighthouse accessibility tests on [github.com/hugoBasicExample/content/post/markdown-syntax.md](https://github.com/gohugoio/hugoBasicExample/blob/master/content/post/markdown-syntax.md) returns the following error:

```text
Some ARIA parent roles must contain specific child roles to perform their intended accessibility functions.
```

The culprit is the `section.footnotes` element. It turns out the [docs linked to the error](https://web.dev/aria-required-children/?utm_source=lighthouse&utm_medium=devtools) reference [version 1.1 of the ARIA specification](https://www.w3.org/TR/dpub-aria-1.1/) which states:

> The doc-endnote and doc-bilbioentry roles are being deprecated due to their incompatibility with the core ARIA inheritance model for roles (i.e., ARIA’s list role cannot be satisfied by list item roles in a module)

I'm not sure what the way forward is. See also:

- https://github.com/w3c/epubcheck/issues/1018
- https://github.com/GoogleChrome/lighthouse/issues/12432

**Comment by schnerring** [comment]
So https://github.com/w3c/epubcheck/issues/1018#issuecomment-809385963 states:

> Moving forward, there will just be footnotes [`doc-footnote`], and if you want to make a list of them just wrap them in a list.

And https://github.com/w3c/epubcheck/issues/1018#issuecomment-809376951 clarifies:

> NOTE
> The doc-endnote role was designed for use as a list item, but due to clarifications in the WAI-ARIA specification, it is not valid as a child of the list role. As the doc-endnotes role already identifies a section of endnotes, authors are instead advised to use the list and listitem roles when native HTML elements cannot be used to structure the entries. The doc-footnote role can be used within each list item to identify individual notes when necessary.

So we just use `doc-footnote` instead? Is this a concern for Hugo or the upstream markdown renderers?

**Comment by tristan957** [comment]
This got fixed upstream: https://github.com/yuin/goldmark/issues/258. It looks like it was included in the 1.4.12 release.

**Comment by jmooring** [comment]
@tristan957 

FYI

Goldmark now conforms to v1.1 of [the spec](https://www.w3.org/TR/dpub-aria-1.1/#doc-endnotes), but Chrome's Lighthouse needs to catch up. It complains:

> Elements with an ARIA [role] that require children to contain a specific [role] are missing some or all of those required children.

This has been addresses in Lighthouse 9.5, which is expected to be included with Chrome v101.

**Comment by tristan957** [comment]
Oops. Thanks for the additional context. Looks like Chromium v101 and maybe hugo 0.98.0 will be a match made in heaven :)
