### ISSUE TITLE
Emoji doesn't render if it's the first element on the page

### ISSUE THREAD

**Issue by ljdn** [gohugoio/hugo#9064]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.88.1+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
