### ISSUE TITLE
:time_full and :time_long do not include timezone outside of Daylight Savings Time 

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9084]
Tested with https://github.com/gohugoio/hugo/commit/75c9b893d98961a504cff9ed3c89055d16e315d6

This code:

```text
{{ $dates := slice
  "2020-03-06T11:00:00-07:00"
  "2020-03-07T11:00:00-07:00"
  "2020-03-08T11:00:00-07:00"
  "2020-03-09T11:00:00-07:00"
  "2020-10-30T11:00:00-07:00"
  "2020-10-31T11:00:00-07:00"
  "2020-11-01T11:00:00-07:00"
  "2020-11-02T11:00:00-07:00"
}}

{{ range $dates }}
  {{ time.Format ":date_medium" . }} {{ time.Format ":time_full" . }}<br>
{{ end }}
```

Produces:

```
Mar 6, 2020 11:00:00 am
Mar 7, 2020 11:00:00 am
Mar 8, 2020 11:00:00 am Pacific Daylight Time
Mar 9, 2020 11:00:00 am Pacific Daylight Time
Oct 30, 2020 11:00:00 am Pacific Daylight Time
Oct 31, 2020 11:00:00 am Pacific Daylight Time
Nov 1, 2020 11:00:00 am
Nov 2, 2020 11:00:00 am
```

In `TZ=America/Los_Angeles` in 2020, Daylight Savings Time began on March 7 at 2:00 AM and ended on November 1 at 2:00  AM.

**Comment by bep** [comment]
This is probably an ommitance of mine, and I will fix it, but I kind of always assumed `time.Format` to be used with `.Date` (which, hopefully, have correct tz info).

What happens if you try:

```
{{ $dates := slice
  "2020-03-06T11:00:00-07:00"
  "2020-03-07T11:00:00-07:00"
  "2020-03-08T11:00:00-07:00"
  "2020-03-09T11:00:00-07:00"
  "2020-10-30T11:00:00-07:00"
  "2020-10-31T11:00:00-07:00"
  "2020-11-01T11:00:00-07:00"
  "2020-11-02T11:00:00-07:00"
}}

{{ range $dates }}
  {{ time.Format ":date_medium" (. | time) }} {{ time.Format ":time_full" (. | time) }}<br>
{{ end }}
```

???

**Comment by bep** [comment]
Never mind, that doesn't work as _you_ expect, either.

**Comment by jmooring** [comment]
> I kind of always assumed time.Format to be used with .Date

`{{ .Date | time.Format ":time_full" }}`

YAML Front Matter|Result
:--|:--
`date: 2020-03-07T11:00:00-07:00`|11:00:00 am
`date: 2020-03-08T11:00:00-07:00`|11:00:00 am Pacific Daylight Tim

**Comment by bep** [comment]
>If the above statement is true, we can close this issue.

Yes, to me that statement looks correct. And in any case, we do have some fallback logic (or the `cast` library does) for when there is no timezone/offset info in the date string, but in this case its Go's `time.Parse` that does the job -- and it seems to determine that the zone abbreviation is somehow ambigous.
