### ISSUE TITLE
Double timezone information for .publishDate

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#9096]
### What version of Hugo are you using (`hugo version`)?

```shell
> hugo version
hugo v0.88.1-5BC54738+extended linux/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
```

### Does this issue reproduce with the latest release?

Yes, the version above is the latest release

### What happens:

In my frontmatter I have the following values:

```yaml
---
date: 2021-10-28T21:56:41+07:00
publishDate: 2021-10-28T21:56:41+07:00
lastmod: 2021-10-28T21:56:41+07:00
---
```

The following layout:

```gotemplate
<span class="publishing-date" title="{{- .PublishDate -}}">
  {{- .PublishDate | time.Format ":date_full" -}}&nbsp;
  {{- i18n "at" | default "at" -}}&nbsp;
  {{- .PublishDate | time.Format ":time_short" -}}
</span>
```

results in the following HTML:

```html
<span class="publishing-date" title="2021-10-28 21:56:41 +0700 +07">Thursday, October 28, 2021&nbsp;at&nbsp;9:56 pm</span>
```

Note that the title attribute shows `+07:00 +07` which is doubling the timezone. It seems this bug was reported before in #5907 and went stale. 

My system time format:

```bash
> date
Fri Oct 29 05:50:26 PM +07 2021
```

And in my config I set a timezone:

```toml
timeZone = "Asia/Bangkok"
```

This behaviour makes it impossible (well, harder) to parse the title attribute into a date object in JavaScript. It seems that GoHugo seems to process the `publishDate` individually instead of just piping it through.

The same is happening on the `.Date` output.

It seems that GoHugo somehow gets the `+07` from my system time, while all other time formats are using `+07:00`

**Comment by davidsneighbour** [comment]
So how does `publishDate: 2021-10-28T21:56:41+07:00` result in `publishDate: 2021-10-28T21:56:41+07:00 +07` then?
I know several ways around this, but that does not solve the issue of GoHugo creating a string with two timezone indicators.

**Comment by jmooring** [comment]
That is what I was trying to explain, albeit not very well. 

1. In your front matter, the `publishDate` is of type `string`.
2. When Hugo unmarshals the front matter, the type becomes `time.Time`.
3. The `time.Time` type is complex:

   - <https://pkg.go.dev/time#Time>
   - <https://cs.opensource.google/go/go/+/refs/tags/go1.17.2:src/time/time.go;l=127-148>

4. To make a time.Time value fit for human consumption, it should be formatted:

   ```text
   {{ .PublishDate | time.Format "2006-01-02T15:04:05-07:00" }}
   ```

In my view, the format of an _unformatted_ time.Time value is irrelevant.

**Comment by bep** [comment]
>In my view, the format of an unformatted time.Time value is irrelevant.

And it's certainly not something I would ever want to mess with. This is Go internals, and any issue should be raised at their issue tracker.
