### ISSUE TITLE
Add `DeactivateScript` option to Tweet shortcode to improve privacy

### ISSUE THREAD

**Issue by nabbisen** [gohugoio/hugo#9098]
I use as [kiprotect / klaro](/kiprotect/klaro) as Cookie consent.
Their documentation [says](https://heyklaro.com/docs/getting-started) modifying inline scripts enables to let no third-party scripts loaded without consent.

I got an idea that adding the feature to built-in "Tweet" shortcode would make me (and maybe more developers) happier 🙂
My idea consists of these change sets:

[`hugo/config/privacy/privacyConfig.go`](../blob/master/config/privacy/privacyConfig.go) : 

```diff
  // Twitter holds the privacy configuration settingsrelated to the Twitter shortcode.
  type Twitter struct {
  	Service `mapstructure:",squash"`
  
  	// When set to true, the Tweet and its embedded page on your site are not used
  	// for purposes that include personalized suggestions and personalized ads.
  	EnableDNT bool
+ 
+ 	// If deactivateScript mode is enabled, JS is kept from being executed by default.
+ 	// - case disabled: <script async src="... 
+ 	// - case enabled:  <script async type="text/plain" data-type="application/javascript" data-name="twitter" data-src="...
+ 	DeactivateScript bool
  
  	// If simple mode is enabled, a static and no-JS version of the Tweet will be built.
  	Simple bool
  }
```

[`hugo/tpl/tplimpl/embedded/templates/shortcodes/twitter.html `](../blob/master/tpl/tplimpl/embedded/templates/shortcodes/twitter.html) : 

```diff (line=8)
- {{ $json.html | safeHTML }}
+ {{- If $pc.DeactivateScript -}}
+ {{- $jsonHTML := (replace $json.html "<script async src=\"" "<script async type=\"text/plain\" data-type=\"application/javascript\" data-name=\"twitter\" data-src=\"") -}}
+ {{- else -}}
+ {{- $jsonHTML := $json.html -}}
+ {{- end -}}
+ {{ $jsonHTML | safeHTML }}
```

... and maybe also:

- `hugo/config/privacy/privacyConfig_test.go`
- ` hugo/docs/content/en/about/hugo-and-gdpr.md `
- `hugo/hugolib/testhelpers_test.go`
- `hugo/tpl/tplimpl/embedded/templates.autogen.go` (?)

**Comment by bep** [comment]
I'm not sure I understand -- have in the above prevents the script from being loaded?

**Comment by nabbisen** [comment]
> I'm not sure I understand -- have in the above prevents the script from being loaded?

@bep
Yes, prevented. The script tag is made "text/plain" which will not be loaded at boot. Well, when it's coverted to "application/javascript" whose data-src attr also to src, the script will be loaded.
Thank you for your time.

**Comment by bep** [comment]
>Well, when it's coverted to "application/javascript" whose data-src attr also to src, the script will be loaded.

When and who does that?

**Comment by nabbisen** [comment]
Who: External library or own custom JS.
Therefore,
When: They work. It'll be possibly Hugo's business.
Well, "own custom JS" can be generated in Hugo in the same way as [`twitter_simple.html`](../blob/master/tpl/tplimpl/embedded/templates/shortcodes/twitter_simple.html) generates own CSS.

**Comment by jmooring** [comment]
@nabbisen I understand the concept, but I think it is better implemented as needed.

Site authors should copy the [embedded template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/twitter.html) to shortcodes/tweet.html and then modify as needed.

I recommend closing this issue.

**Comment by nabbisen** [comment]
@jmooring 
Thank you for your comments!! OK. I'll close it.

Besides, I copied built-in "tweet" shortcode template (`tpl/tplimpl/embedded/templates/shortcodes/twitter.html`) as you described, and modified it to implement privacy consent. I leave the diff which might be possibly helpful in the future.

```diff
- {{ $json.html | safeHTML }}
+ {{- $jsonHTML := (replace $json.html "<script async src=\"" "<script async type=\"text/plain\" data-type=\"application/javascript\" data-name=\"twitter\" data-src=\"") -}}
+ {{ $jsonHTML | safeHTML }}
```

This works well with importing Klaro! at the foot(.html) like this:

```html
<link rel="stylesheet" href="https://cdn.kiprotect.com/klaro/v0.7/klaro.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script>
// https://heyklaro.com/docs/integration/annotated-configuration
var klaroConfig = { ... };
</script>
<script src="https://cdn.kiprotect.com/klaro/v0.7/klaro-no-css.js" crossorigin="anonymous" referrerpolicy="no-referrer" defer></script>
```
