### ISSUE TITLE
Tweet shortcode broken API Error

### ISSUE THREAD

**Issue by elax46** [gohugoio/hugo#9105]
### What version of Hugo are you using (`0.88.1`)

<pre>
$ hugo version
hugo v0.88.1-5BC54738 windows/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
yes

### Descrition error
I wanted to update the executed version of Hugo and I updated the ```netlify.toml``` but at the rebuild the es was presented

<pre>
ERROR 2021/10/30 20:54:31 Failed to get JSON resource "https://api.twitter.com/1/statuses/oembed.json?id=1378314424239460352&dnt=false": Failed to retrieve remote file: Forbidden, body: "{\"error\":\"Sorry, you are not authorized to see this status.\",\"request\":\"\\/1\\/statuses\\/oembed.json?id=1378314424239460352&dnt=false\"}"
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Error: Error building site: logged 2 error(s)
</pre>

After the error I have on netlify I have verified that also in local giving the command ```hugo server -D``` it appears in the same way.  I specify that the problem also occurs with older versions of Hugo

### Additional description
Although the request #8130 is already open, I also open this as it seems to me that the thing has not been at the moment. Since I have numerous tweets embedded it is a bit complicated to go and delete them

**Comment by jmooring** [comment]
The twitter shortcode _does_ need to be updated, but your error is not related to the API.

<https://twitter.com/xxx/status/1378314424239460352>

> This Tweet is from a suspended account.
