### ISSUE TITLE
Wrong spelling of "Montag" from time.Format

### ISSUE THREAD

**Issue by raoulb** [gohugoio/hugo#9107]
The german translation of the weekday name "monday" is wrong. The following code

```
{{ time.Format "Monday" "2021-11-01" }}<br>
{{ time.Format "Monday" "2021-11-02" }}<br>
{{ time.Format "Monday" "2021-11-03" }}<br>
{{ time.Format "Monday" "2021-11-04" }}<br>
{{ time.Format "Monday" "2021-11-05" }}<br>
{{ time.Format "Monday" "2021-11-06" }}<br>
{{ time.Format "Monday" "2021-11-07" }}<br>
```

produces

```
Mo.tag
Dienstag
Mittwoch
Donnerstag
Freitag
Samstag
Sonntag
```

with `Mo.tag` instead of `Montag`. The others are correct. Hugo is configured as:

```
languageCode = "de-de"
defaultContentLanguage = "de"

timeZone = "UTC"
```

A minimal working example can be found [here](https://github.com/raoulb/hugo_issue_timeformat).

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.88.1-5BC54738 linux/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by jmooring** [comment]
There's a problem with month names as well.

```text
{{ time.Format "January" "2021-01-01" }} --> Jan.uar
{{ time.Format "January" "2021-02-01" }} --> Feb.ruar
{{ time.Format "January" "2021-03-01" }} --> März
{{ time.Format "January" "2021-04-01" }} --> Apr.il
{{ time.Format "January" "2021-05-01" }} --> Mai
{{ time.Format "January" "2021-06-01" }} --> Junii
{{ time.Format "January" "2021-07-01" }} --> Julii
{{ time.Format "January" "2021-08-01" }} --> Aug.ust
{{ time.Format "January" "2021-09-01" }} --> Sept.tember
{{ time.Format "January" "2021-10-01" }} --> Oktober
{{ time.Format "January" "2021-11-01" }} --> Nov.ember
{{ time.Format "January" "2021-12-01" }} --> Dezember
```

**Comment by jmooring** [comment]
This seems to happen when

1. The day or month name is capitalized in the target language, AND
2. A day or month abbreviation in the target language matches a few characters of the format string

Affected languages include: Afrikaans (af), German (de), Swiss German (gsw), maybe some others

**Comment by davidsneighbour** [comment]
Double ii on Juni and Juli is wrong too.

**Comment by bep** [comment]
This looks like a Bangles bug.

**Comment by bep** [comment]
Note that this is only wrong for the Go layout strings, it is OK for `:date_long` etc.

**Comment by raoulb** [comment]
Cool. Thanks for the quick fix!
