### ISSUE TITLE
Evaluate moving the partialCache lock

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9117]
See: https://github.com/gohugoio/hugo/blob/41e9e9fe14eb53f830404c9c76893e01c34fa034/tpl/partials/partials.go#L222

The above does not optimal and should be easy to benchmark. The above reduces lock contention, but it may not be optimal for this use case.

This was brought up in https://discourse.gohugo.io/t/how-to-ensure-partial-is-executed-just-once/35411/5 -- but note that even with the above change, a cache is not a lock.

**Comment by web-apply** [comment]
good job
