### ISSUE TITLE
missing binary  / wrong binary for Raspberry / Raspbian armv7l vs. armhf

### ISSUE THREAD

**Issue by gj52** [gohugoio/hugo#9128]
### What version of Hugo are you using (`hugo version`)?

0.89

### Does this issue reproduce with the latest release?

download hugo_0.89.0_Linux-ARM.deb and install on Raspbian

root@pi4:/home/hugo/hugo/_raspbian# dpkg -i hugo_0.89.0_Linux-ARM.deb
dpkg: Fehler beim Bearbeiten des Archivs hugo_0.89.0_Linux-ARM.deb (--install): ## ERROR installing
 Paket-Architektur (armv7l) passt nicht zum System (armhf)  ##  does not match architecure armhf

**Comment by bep** [comment]
Probably this commit: https://github.com/goreleaser/goreleaser/commit/d7e1bcc1f069bc294abe9032c9209f271dc60745

@caarlos0 sorry for "mentioning you" like this, but when you say "armv7 on linux is usually armv7l", what do you base that on?

To fix the above particular issue, I assume I can I just do:

```
    goarch:
      - amd64
      - 386
      - arm
      - arm6
      - arm64
```

**Comment by gj52** [comment]
I'm using an Raspberry 4 for education ...

The German error text says:

The image is for armv7l architecture, but the HW/OS is arm

HTH

**Comment by caarlos0** [comment]
@bep no problem

I mean that as far as I've seen, when GOARCH=arm and GOARM=7 it is a `arm7l` instead of `armhf`, that's why that change was made

@gj52 you'll likely need the arm6 package (which should be armhf)

**Comment by caarlos0** [comment]
will likely need to change some name templates as well, e.g. https://github.com/gohugoio/hugo/blob/master/goreleaser.yml#L170

probably something like:

```yaml
file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}{{ with .Arm }}{{ . }}{{ end }}"
```

**Comment by bep** [comment]
I have released 0.89.1 where I have reverted the "Goreleaser MacOS fat binary" update, which I assumes also fixes this issue, but I'll keep this issue open to track the comeback of that feature.

**Comment by gj52** [comment]
Thanks,

now working, perfect!

**Comment by caarlos0** [comment]
hmm, so maybe my accessment of that was wrong 🤔 

will revert the commit for now...

thanks @bep

**Comment by caarlos0** [comment]
https://github.com/goreleaser/goreleaser/commit/1e718d2db0a612fe79e25292889c9ca10a97e563

**Comment by gj52** [comment]
Version 0.93.3 works! Thanks

**Comment by jmooring** [comment]
@gj52 Have you tested the v0.111.3 binary?

I'm pretty sure we can close this issue. Hugo has been using [gohugoio/hugoreleaser](https://github.com/gohugoio/hugoreleaser)  instead of [goreleaser/goreleaser](https://github.com/goreleaser/goreleaser) since [v0.102.0](https://github.com/gohugoio/hugo/releases/tag/v0.102.0).
