### ISSUE TITLE
Add filter to themes.gohugo.io allowing elimination of unusable versions of themes

### ISSUE THREAD

**Issue by morciej** [gohugoio/hugo#9133]
I am searching Hugo themes, trying to find all the ones that are usable to me. The **highest version I can use** is 0.68. I am not willing to download latest Hugo version; what is in the repositories for Linux Mint Uma/Focal is what I am willing to use.

**Perhaps add a filter "Maximum Hugo version" to the page "themes.gohugo.io"** so that people don't have to waste time looking for a nice theme that turns out to require Hugo version they don't have access to, upon opening the theme's page.

Alternatively, display the lowest Hugo version required for each theme as a caption.

**Comment by RoneoOrg** [comment]
You can use "[PF Filterable Hugo Themes](https://pfht.netlify.app/)" to filter themes by Hugo versions.

See in the right Sidebar, the tab "Version" : you can even select "Every Hugo version Less than or equal to" Hugo 0.68!

The dataset was updated 6 months ago, but the update process [is documented](https://github.com/pointyfar/hugo-themes-filter). 

I've discovered this tool today, I would love to have your feedback if you give it a try.

Side note: I'm currently working on [another tool](https://jamstack.club) to showcase and filter Hugo themes, feel free to add your usecase to the [feature requests](https://github.com/RoneoOrg/jamstack.club/issues)

**Comment by morciej** [comment]
Thanks. Yes, I tried it. It works well. Combining images with filtering would be even nicer. Good luck with Jamstack!
