### ISSUE TITLE
Hugo 0.89.1 drops line after empty line in indented code fence in list item

### ISSUE THREAD

**Issue by dengste** [gohugoio/hugo#9137]
I am using the following markdown:

```markdown
* This is a list item
    ```
    This is a test

    This line will be dropped.
    This line will be displayed.
    ```
```

Hugo 0.89.1 will not render the line following the empty line in the indented code fence. It will  be displayed if either the empty line is removed, the code fence is not indented, or if the list item is removed.

This used to render fine with 0.88.1, so this is a regression. I could reproduce this problem using the 'quickstart' guide with the Ananke theme right away.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.89.1-B6A4AE4A linux/amd64 BuildDate=2021-11-05T15:44:32Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by bep** [comment]
This fixes it:

```
go get: downgraded github.com/yuin/goldmark v1.4.2 => v1.4.1
```
