### ISSUE TITLE
Title not displaying correctly when start with word ISO

### ISSUE THREAD

**Issue by idarek** [gohugoio/hugo#9139]
<pre>
hugo v0.89.1+extended darwin/arm64 BuildDate=unknown
</pre>

When first word in Title of the post is ISO, title is not generating correctly.

Example:
```
title: 'ISO 7091 Plain washers - Basic dimensions'
```

Title displaying only `washers - Basic dimensions`

When you remove `ISO` word you:
```
title: '7091 Plain washers - Basic dimensions'
```

Title displaying `7091 Plain washers - Basic dimensions`

Hence its a bug with wording.

```
Fun fact is that this is some wider bug, as I can see that same issue in Wordpress, which is strange
```

**Comment by jmooring** [comment]
Unable to reproduce. Please provide a minimal reproducible example. Thanks.

**Comment by idarek** [comment]
Just a clarification, it's title in <head>


But... I cannot reproduce as well. That's strange. After restarting server it generate titles correctly and even this that got : in them.

I will try to see over days but if I cannot find how this happens please close.
