### ISSUE TITLE
Pagination: consider dropping href="#" for disabled buttons since it is an invalid fragment id

### ISSUE THREAD

**Issue by chalin** [gohugoio/hugo#9149]
Great update in #8602 @jmooring!

Could we drop the invalid anchors (`href="#"`) for disabled buttons?

```html
<a href="#" aria-disabled="true" ...>
```

It's tripping link checking. For example, see https://github.com/gohugoio/hugo/blob/805c24c32c9b1f118c5f3693bfe1176d4efe4d9c/tpl/tplimpl/embedded/templates/pagination.html#L43

Prior to #8602, the previous button omitted the `href` attribute when there was no previous page.

/cc @austinlparker @nate-double-u

**Comment by jmooring** [comment]
@chalin Yes, I will look at this. Link checking is one problem, but the primary driver is that the fragment resolves to the server root when serving from a subdirectory with a `<base href="{{ site.BaseURL }}">` element.
