### ISSUE TITLE
Hugo new command STDOUT changed in v0.89.0

### ISSUE THREAD

**Issue by chanix95** [gohugoio/hugo#9157]
### Problem
The output of 
`hugo new --kind ARCHETYPE PATH/TO/FILE.md`
 has changed after the [archetype re-implementation Pull Request.](https://github.com/gohugoio/hugo/pull/9045). To be more precise, [line 103 of hugo/create/content.go](https://github.com/gohugoio/hugo/blob/v0.88.1/create/content.go#L103) has been removed. As @bep requested in this [support post](https://discourse.gohugo.io/t/hugo-new-command-stdout-changed-in-v0-89-0/35531), I am opening this issue to put that print statement back in.

### What version of Hugo are you using (`hugo version`)?
The issue affects v0.89.0 v0.89.1 and v0.89.2

### Does this issue reproduce with the latest release?
yes

Thanks a lot!!

**Comment by bep** [comment]
Note: These log statements will show if you add the `-v` flag, but I will fix this.
