### ISSUE TITLE
`hugo new posts/my-first-post.md` command fails with hugo modules

### ISSUE THREAD

**Issue by eyllanesc** [gohugoio/hugo#9166]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.89.2+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

------------------------

I have followed the steps of the tutorial:[ Hugo modules for “dummies”](https://discourse.gohugo.io/t/hugo-modules-for-dummies/20758) and it works correctly but when i want to create a new post using `hugo new` command I get:

<pre>
$ hugo new posts/my-first-post.md -v
Error: open : no such file or directory
</pre>

If I don't use hugo modules but gitmodules or download the theme in the themes folder then I have no problems.

**Comment by bep** [comment]
There isn't enough information here to determine what's happening. The part about "this not working with Hugo modules" is obviously not correct, as all of my projects (in which have tested this with), works fine here.

**Comment by eyllanesc** [comment]
@bep Do you require any information from me? I have tested the demo that you indicate and I cannot create the .md from the archetypes when I set the theme using hugo modules, but I can when I use git modules or copy the theme directly.

**Comment by eyllanesc** [comment]
@bep The error message I get with `hugo v0.89.3+extended` is:

```console
$ hugo new posts/my-first-post.md -v
Error: could not determine content directory for "posts/my-first-post.md"
```

The config.toml is:

```toml
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
```

And the structure of the project is:


```console
├── archetypes
│   └── default.md
├── config.toml
├── content
├── data
├── go.mod
├── go.sum
├── layouts
├── resources
│   └── _gen
│       ├── assets
│       │   └── css
│       │       └── ananke
│       │           └── css
│       │               ├── main.css_bb5467e0521bbea6b1e66429f6ec028e.content
│       │               └── main.css_bb5467e0521bbea6b1e66429f6ec028e.json
│       └── images
├── static
└── themes
```

The `hugo serve` command works:

```console
Start building sites … 
hugo v0.89.3+extended linux/amd64 BuildDate=unknown

                   | EN  
-------------------+-----
  Pages            |  7  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  1  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 123 ms
Watching for changes in /home/eyllanesc/blog/{archetypes,content,data,layouts,static}
Watching for config changes in /home/eyllanesc/blog/config.toml, /home/eyllanesc/blog/go.mod
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by eyllanesc** [comment]
@bep The error message I get with hugo v0.89.3+extended is:

```console
$ hugo new posts/my-first-post.md -v
Error: could not determine content directory for "posts/my-first-post.md"
```

Steps to reproduce the problem:

<pre>
$ hugo new site quickstart
Congratulations! Your new Hugo site is created in /home/eyllanesc/test_blog/quickstart.

Just a few more steps and you're ready to go:

1. Download a theme into the same-named folder.
   Choose a theme from https://themes.gohugo.io/ or
   create your own with the "hugo new theme <THEMENAME>" command.
2. Perhaps you want to add some content. You can add single files
   with "hugo new <SECTIONNAME>/<FILENAME>.<FORMAT>".
3. Start the built-in live server via "hugo server".

Visit https://gohugo.io/ for quickstart guide and full documentation.

$ cd quickstart
$ echo theme = \"github.com/theNewDynamic/gohugo-theme-ananke\" >> config.toml
$ hugo mod init eyllanesc/quickstart
WARN 2021/11/15 22:48:28 module "github.com/theNewDynamic/gohugo-theme-ananke" not found; either add it as a Hugo Module or store it in "/home/eyllanesc/test_blog/quickstart/themes".: module does not exist
go: creating new go.mod: module eyllanesc/quickstart
go: to add module requirements and sums:
        go mod tidy
$ hugo server
hugo: downloading modules …
go get: added github.com/theNewDynamic/gohugo-theme-ananke v0.0.0-20211001175655-869b03ea78b6
hugo: collected modules in 13637 ms
Start building sites … 
hugo v0.89.3+extended linux/amd64 BuildDate=unknown

                   | EN  
-------------------+-----
  Pages            |  7  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  1  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 415 ms
Watching for changes in /home/<user>/test_hugo/quickstart/{archetypes,content,data,layouts,static}
Watching for config changes in /home/<user>/test_hugo/quickstart/config.toml, /home/eyllanesc/test_blog/quickstart/go.mod
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
^C 
$ hugo new posts/my-first-post.md
Error: could not determine content directory for "posts/my-first-post.md
$ tree
.
├── archetypes
│   └── default.md
├── config.toml
├── content
├── data
├── go.mod
├── go.sum
├── layouts
├── resources
│   └── _gen
│       ├── assets
│       │   └── css
│       │       └── ananke
│       │           └── css
│       │               ├── main.css_bb5467e0521bbea6b1e66429f6ec028e.content
│       │               └── main.css_bb5467e0521bbea6b1e66429f6ec028e.json
│       └── images
├── static
└── themes
</pre>

**Comment by eyllanesc** [comment]
@bep The error message I get with hugo v0.89.3+extended is:

```console
$ hugo new posts/my-first-post.md -v
Error: could not determine content directory for "posts/my-first-post.md"
```

Steps to reproduce the problem:

<pre>
$ hugo new site quickstart
Congratulations! Your new Hugo site is created in /home/<user>/test_hugo/quickstart.

Just a few more steps and you're ready to go:

1. Download a theme into the same-named folder.
   Choose a theme from https://themes.gohugo.io/ or
   create your own with the "hugo new theme <THEMENAME>" command.
2. Perhaps you want to add some content. You can add single files
   with "hugo new <SECTIONNAME>/<FILENAME>.<FORMAT>".
3. Start the built-in live server via "hugo server".

Visit https://gohugo.io/ for quickstart guide and full documentation.

$ cd quickstart
$ echo theme = \"github.com/theNewDynamic/gohugo-theme-ananke\" >> config.toml
$ hugo mod init eyllanesc/quickstart
WARN 2021/11/15 22:48:28 module "github.com/theNewDynamic/gohugo-theme-ananke" not found; either add it as a Hugo Module or store it in "/home/<user>/test_hugo/quickstart/themes".: module does not exist
go: creating new go.mod: module eyllanesc/quickstart
go: to add module requirements and sums:
        go mod tidy
$ hugo server
hugo: downloading modules …
go get: added github.com/theNewDynamic/gohugo-theme-ananke v0.0.0-20211001175655-869b03ea78b6
hugo: collected modules in 13637 ms
Start building sites … 
hugo v0.89.3+extended linux/amd64 BuildDate=unknown

                   | EN  
-------------------+-----
  Pages            |  7  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  1  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 415 ms
Watching for changes in /home/<user>/test_hugo/quickstart/{archetypes,content,data,layouts,static}
Watching for config changes in /home/<user>/test_hugo/quickstart/config.toml, /home/<user>/test_hugo/quickstart/go.mod
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
^C 
$ hugo new posts/my-first-post.md
Error: could not determine content directory for "posts/my-first-post.md
$ tree
.
├── archetypes
│   └── default.md
├── config.toml
├── content
├── data
├── go.mod
├── go.sum
├── layouts
├── resources
│   └── _gen
│       ├── assets
│       │   └── css
│       │       └── ananke
│       │           └── css
│       │               ├── main.css_bb5467e0521bbea6b1e66429f6ec028e.content
│       │               └── main.css_bb5467e0521bbea6b1e66429f6ec028e.json
│       └── images
├── static
└── themes
</pre>

**Comment by eyllanesc** [comment]
@bep The error message I get with hugo v0.89.3+extended is:

```console
$ hugo new posts/my-first-post.md -v
Error: could not determine content directory for "posts/my-first-post.md"
```

Steps to reproduce the problem:

<pre>
$ hugo new site quickstart
Congratulations! Your new Hugo site is created in /home/user/test_hugo/quickstart.

Just a few more steps and you're ready to go:

1. Download a theme into the same-named folder.
   Choose a theme from https://themes.gohugo.io/ or
   create your own with the "hugo new theme <THEMENAME>" command.
2. Perhaps you want to add some content. You can add single files
   with "hugo new <SECTIONNAME>/<FILENAME>.<FORMAT>".
3. Start the built-in live server via "hugo server".

Visit https://gohugo.io/ for quickstart guide and full documentation.

$ cd quickstart
$ echo theme = \"github.com/theNewDynamic/gohugo-theme-ananke\" >> config.toml
$ hugo mod init eyllanesc/quickstart
WARN 2021/11/15 22:48:28 module "github.com/theNewDynamic/gohugo-theme-ananke" not found; either add it as a Hugo Module or store it in "/home/user/test_hugo/quickstart/themes".: module does not exist
go: creating new go.mod: module eyllanesc/quickstart
go: to add module requirements and sums:
        go mod tidy
$ hugo server
hugo: downloading modules …
go get: added github.com/theNewDynamic/gohugo-theme-ananke v0.0.0-20211001175655-869b03ea78b6
hugo: collected modules in 13637 ms
Start building sites … 
hugo v0.89.3+extended linux/amd64 BuildDate=unknown

                   | EN  
-------------------+-----
  Pages            |  7  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  1  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 415 ms
Watching for changes in /home/user/test_hugo/quickstart/{archetypes,content,data,layouts,static}
Watching for config changes in /home/user/test_hugo/quickstart/config.toml, /home/user/test_hugo/quickstart/go.mod
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
^C 
$ hugo new posts/my-first-post.md
Error: could not determine content directory for "posts/my-first-post.md
$ tree
.
├── archetypes
│   └── default.md
├── config.toml
├── content
├── data
├── go.mod
├── go.sum
├── layouts
├── resources
│   └── _gen
│       ├── assets
│       │   └── css
│       │       └── ananke
│       │           └── css
│       │               ├── main.css_bb5467e0521bbea6b1e66429f6ec028e.content
│       │               └── main.css_bb5467e0521bbea6b1e66429f6ec028e.json
│       └── images
├── static
└── themes
</pre>

**Comment by eyllanesc** [comment]
Duplicate of #9177
