### ISSUE TITLE
Redefine disablePathToLower setting for the section structure 

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9171]
Edit in 14. oct 2023: I'm about to do this. So, after this, you can still preserve mixed case URLs

* The URLs built from permalinks config that fetches values from the tokens that's not a part in the canonical path, e.g., `:title`. `:slug` etc.
* URLs defined as `url` in front matter can be whatever you like.
* But all URLs parts coming from the (new) canonical content path will always be lower cased.

Some examples of such canonical paths:

```
/ (home page)
/mysection (a section)
/mysection/mypage (a page/bundle)
/categories (a taxonomy)
/categories/mycategori (a term)
```

----
I have never used the `disablePathToLower` in any of my many Hugo sites, but I assume some do an will get mad at me if I just remove it without discussion ...

I'm doing some long-needed simplifications/improvements in this area to pave way for some features that I think many would like/want. And to do that we need some unified path normalization (to be able to quickly find stuff, but also to be able to quickly merge content from different sources etc.) -- and preserving this case information in the file paths just seems too expensive to me (implementation/test cases and performance/memory).

I assume people who want this want it because it ... looks prettier? I cannot imagine any CEO argument.

I have thought about a middle ground that would allow mixed-case URLs for the title/slug part of the URL, e.g:

```
https://example.com/posts/My-Cool-Blog-Post/
```

Would be OK, but 

```
https://example.com/MyBlog/My-Cool-Blog-Post/
```

Would not be possible.

But that would make not the below construct truthful (or: it would be hard to make it truthful):

```
{{ $url := "https://example.com/posts/My-Cool-Blog-Post/" }}
Should be true: {{ eq $url ($url | urlize }}
```

Thoughts?

**Comment by jmooring** [comment]
> Thoughts?

Start throwing a deprecation warning to get a feel for how many sites this would effect. The scenario I imagine is, "Hey, Google and Bing have indexed hundreds of pages of my Very Important Blog. I've spent years optimizing SEO. Now, because my web server is case sensitive, all those links on Google and Bing are broken."

**Comment by davidsneighbour** [comment]
I also have done years of SEO and always used lowercase URLs because Windows is case-insensitive and Linux is case sensitive and both (hosting options) are always crashing against each other. I never understood people doing URLs with uppercase characters. This will end in some form of discussion of paradigms. It should have been lowercased over the full URL from the beginning ;)

For the "hey I have done years of work on SEO" user case I have the "hey, add a proper sitemap" response. Most search engines understand lower/uppercase confusion these days anyways and are able to move "google juice" to new URLs.

It's important to have a proper full documentation about it, that's all in my opinion.

**Comment by jmooring** [comment]
I really hope someone isn't generating JSON at `https://example.org/API/FOO` on a case sensitive server. That seems like a self-inflicted wound with deferred pain.

**Comment by bep** [comment]
>Start throwing a deprecation warning to get a feel for how many sites this would affect. 

Sure, but I cannot do this _without doing it_, so any deprecation warning would warn about something that already happened. 

I have thought further about this and preserving the case in these URLs AND adding new features to Hugo comes at a fairly high cost (mostly developer cost, but also a performance penalty) and even then, we most likely end up in a half assed state with lots of ambiguity and unclear documentation ... I don't think I'm prepared to go the extra mile and spend, say, 20 hours, to preserve a setting that I have never used and never will use and (I hope) didn't add myself in the first place.

**Comment by bep** [comment]
An added note: I will release one or more beta versions of Hugo 0.90.0, which may allow us to get a feel for this before we pass it out to the wolf pack.

**Comment by DevBeatDad** [comment]
@bep If only my mentor would get back to me so I could know how I can better help with this repo.

**Comment by sergio-carlavilla** [comment]
We use this approach in FreeBSD as you can see here [https://www.freebsd.org/releases/13.0R/announce/](https://www.freebsd.org/releases/13.0R/announce/)

When you remove this option, we cannot use this kind URL, am I correct?

**Comment by DominoPivot** [comment]
Removing this feature would break all mixed-case links on an existing website hosted on a case-sensitive server. This could break links to existing Hugo site as well as internal links within the site, and also prevent anyone from migrating an existing site with mixed-case URLs to Hugo, something I've done before.

Sure, in an ideal world, your server is configured to normalize casing so any request gets redirected to the canonical, lowercase version, but people use static site generators specifically in situations where they don't control the server that hosts their site.

**Comment by sergio-carlavilla** [comment]
Ah, no problem, we handle it in another way, no need this anymore :)

**Comment by bep** [comment]
I'm closing this. Working my way through all of this I found a simple way to preserve the old behaviour.  I still don't think this config option is a great idea, but I will close.
