### ISSUE TITLE
hugo new /post/test.md Error: could not determine content directory for

### ISSUE THREAD

**Issue by crazyhl** [gohugoio/hugo#9183]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.89.4+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by bep** [comment]
Try without the leading slash ("/").

**Comment by crazyhl** [comment]
thx it works
