### ISSUE TITLE
.Title missing on content (e.g. markdown) .Resources

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9197]
When accessing a markdown file as a global resource (`resources.GetMatch "a.md"`), everything works as expected. The `.Title` is populated (equivalent to `.Name` as expected), the `.Permalink` and `.RelPermalink` are available, the `.MediaType` is `text/markdown`, and the `.Content` is raw.

When accessing a markdown file as a page resource (`.Resources.GetMatch "b.md"`), the `.Title` , `.Permalink`, and `.RelPermalink` are missing, the `.MediaType` is `application/octet-stream`, and the `.Content` is fully rendered.

```text
content/
├── tests/
│   └── test-1/
│       ├── b.md
│       └── index.md
└── _index.md

assets/
└── a.md
```

Variable|Global Resource|Page Resource
:--|:--|:--
`.Name`|`a.md`|
`.Title`|`a.md`|`b.md`
`.Permalink`|`http://localhost:1313/a.md`|
`.RelPermalink`|`/a.md`|
`.MediaType`|`text/markdown`|`application/octet-stream`
`.Content`|`raw`|`rendered`

I expected the Page Resource to behave just like the Global Resource.

MRE:

```bash
git clone --single-branch -b hugo-github-issue-9197 https://github.com/jmooring/hugo-testing hugo-github-issue-9197
cd hugo-github-issue-9197
hugo server
```

**Comment by jmooring** [comment]
I also expected the markdown Page Resource to behave like other Page Resources. 

```
content/tests/test-2/
├── index.md
├── sample.docx
├── sample.md
├── sample.pdf
└── sample.txt
```

When I `{{ range .Resources }}`

```text
.Name = sample.docx
.Title = sample.docx
.Permalink = http://localhost:1313/tests/test-2/sample.docx
.RelPermalink = /tests/test-2/sample.docx
.MediaType = application/vnd.openxmlformats-officedocument.wordprocessingml.document

.Name = sample.pdf
.Title = sample.pdf
.Permalink = http://localhost:1313/tests/test-2/sample.pdf
.RelPermalink = /tests/test-2/sample.pdf
.MediaType = application/pdf

.Name = sample.txt
.Title = sample.txt
.Permalink = http://localhost:1313/tests/test-2/sample.txt
.RelPermalink = /tests/test-2/sample.txt
.MediaType = text/plain

.Name = sample.md
.Title =                                # MISSING
.Permalink =                            # MISSING
.RelPermalink =                         # MISSING
.MediaType = application/octet-stream   # INCORRECT
```

**Comment by bep** [comment]
The missing Permalink is by design -- the content resource files are meant to be included and will never be published on its own (so the Permalink will be empty).

**Comment by jmooring** [comment]
> The missing Permalink is by design

This came up in the context of generating portable links for page resources. A link render hook looks first for a matching page, then for a matching resource it can't find a page.

```markdown
[Some page)(post/post-2.md)
[A PDF file](my.pdf)
[A markdown file)(my.md)
```

The render hook works great for everything but markdown files when they are page resources.

**Comment by bep** [comment]
>The render hook works great for everything but markdown files when they are page resources.

That sounds like a problem with the render hook. It does not make sense to "look for a page resource" if the goal is to link to it.

**Comment by jmooring** [comment]
> It does not make sense to "look for a page resource" if the goal is to link to it.

I apologize; my description was unclear. The goal is to provide _portable_ links to both pages _and_ files. Scenario:
- Site is served from a subdirectory (`baseURL = 'https://example.org/hugo/'`)
- List page displays `.Content` of every page in its `range`

markdown

```
[Test 2](/tests/test-2)

[Sample PDF](sample.pdf)
```

layouts/_default/_markup/render-link.html

```text
{{ $u := urls.Parse .Destination }}
{{ $href := $u.String }}
{{ if not $u.IsAbs }}
  {{ with site.GetPage $u.Path }}
    {{/* It's a page */}}
    {{ $href = .RelPermalink }}
  {{ else }}
    {{/* Maybe it's a link to a page resource like a PDF file */}}
    {{ with .Page.Resources.GetMatch $u.Path }}
      {{ $href = .RelPermalink }}
    {{ else }}
      {{ warnf "The link to %q on page %q appears to be broken." $u.Path .Page.Path }}
    {{ end }}
  {{ end }}
{{ end }}
<a href="{{ $href }}">{{ .Text | safeHTML }}</a>
```
This (simplified) render hook works as expected for every page and file, unless the file is a markdown file. 

The un-simplified render hook has an additional fallback, looking for a global resource if it can't find a matching page resource. So our work around, when we need to provide a portable link to a markdown file, is to place the file in `assets/`.

This is not a big deal, just an unexpected difference between a markdown file as a page resource and a markdown file as a global resource.

**Comment by bep** [comment]
>This is not a big deal, just an unexpected difference between a markdown file as a page resource and a markdown file as a global resource.

If you have a `Permalink` it can be linked to; this is the same behaviour for any resource.

So, if you do:

```
{{ $u := urls.Parse .Destination }}
{{ $href := $u.String }}
{{ if not $u.IsAbs }}
  {{ with site.GetPage $u.Path }}
    {{/* It's a page */}}
    {{ $href = .RelPermalink }}
  {{ else }}
    {{/* Maybe it's a link to a page resource like a PDF file */}}
    {{ with .Page.Resources.GetMatch $u.Path }}
    {{ with .RelPermalink }}
      {{ $href = .RelPermalink }}
    {{ end }}
    {{ else }}
      {{ warnf "The link to %q on page %q appears to be broken." $u.Path .Page.Path }}
    {{ end }}
  {{ end }}
{{ end }}
<a href="{{ $href }}">{{ .Text | safeHTML }}</a>
```

Note that you can have `_build` config that tells Hugo to _never_ publish any resource, which will make PDFs, images etc. also return empty `Permalink`.

**Comment by bep** [comment]
Also, re missing `.Title`, I think that logic is the same as for other content pages (title from front matter).

**Comment by jmooring** [comment]
> Note that you can have _build config that tells Hugo to never publish any resource, which will make PDFs, images etc. also return empty Permalink.

Hmm. My test results are different, and match our documentation.

> publishResources 
> 
> If set to true the Bundle’s Resources will be published. **Setting this to false will still publish Resources on demand (when a resource’s .Permalink or .RelPermalink is invoked from the templates) but will skip the others.**

**Comment by jmooring** [comment]
Closing in favor of #12274.
