### ISSUE TITLE
'hugo server" has incorrect mime/type for javascript files.

### ISSUE THREAD

**Issue by snhmibby** [gohugoio/hugo#9200]
<pre>
$ hugo version
hugo v0.90.0-DEV+extended linux/amd64 BuildDate=unknown
</pre>

Hello, I have a javascript file that defines a class. I build it with js.Build and output format 'esm', because it defines functions I want to use later.
Unfortunately, the Hugo dev server serves the file with a mimetype of text/plain, which is not accepted in modern browsers as a module, which makes it difficult to test locally.
The js file is [here](https://github.com/snhmibby/www.degroteeik.be/blob/main/assets/components/gallery/gallery.js)
I build it at the bottom of [this shortcode](https://github.com/snhmibby/www.degroteeik.be/blob/main/layouts/shortcodes/bundle-gallery.html)

**Comment by bep** [comment]
You can define your own media type, which will be added to the server on startup.
