### ISSUE TITLE
Add hugo to winget

### ISSUE THREAD

**Issue by X7md** [gohugoio/hugo#9201]
# Add to winget for windows

Winget:
https://github.com/microsoft/winget-cli

https://gohugo.io/getting-started/installing/

**Comment by icy-comet** [comment]
I was looking into this, but it seems like `winget` needs a direct link to the setup/binary and can't handle zips/tars or archives of any kind (atleast for now). Is it possible to include the binary *itself* in the GitHub releases rather than zips? @bep

**Comment by sitiom** [comment]
Already in Winget:
- https://github.com/microsoft/winget-pkgs/pull/96098
- https://github.com/microsoft/winget-pkgs/pull/96099

**Comment by jmooring** [comment]
I am opposed to adding this, but not because of the packages themselves. 

I just spent over an hour trying to get Winget working on a Windows 11 system. To get Winget you have to install Microsoft.DesktopAppInstaller. I tried via Windows Store and directly from GitHub. Fail.

I'm sure it's fixable, but I gave up. The other package managers that we list (Chocolately and Scoop) are easy to install, uninstall, repair, etc.

**Comment by bep** [comment]
I agree with @jmooring -- I haven't tested winget myself, but we're already very fragmented in this area -- and pushing the limits for what we can maintain with the current "work force".

**Comment by X7md** [comment]
> I am opposed to adding this, but not because of the packages themselves.
> 
> I just spent over an hour trying to get Winget working on a Windows 11 system. To get Winget you have to install Microsoft.DesktopAppInstaller. I tried via Windows Store and directly from GitHub. Fail.
> 
> I'm sure it's fixable, but I gave up. The other package managers that we list (Chocolately and Scoop) are easy to install, uninstall, repair, etc.

Most of new devices with preinstall `windows 11` have preinstall `winget` and `windows terminal`, all programs and tools in my new `Thinkpad T14s` I installed it  from `winget`, e.g: `chrome, golang, nodejs, git, dart`... and I recommend all my friend with windows to use `winget`.

**Comment by sitiom** [comment]
> I just spent over an hour trying to get Winget working on a Windows 11 system. To get Winget you have to install Microsoft.DesktopAppInstaller. I tried via Windows Store and directly from GitHub. Fail.

Huh? Just update "App Installer" from Microsoft Store and Winget should work. What problems are you specifically having?
