### ISSUE TITLE
js.Build params and multi-language

### ISSUE THREAD

**Issue by p-fruck** [gohugoio/hugo#9223]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes, tested with
<pre>
hugo v0.89.4-AB01BA6E linux/amd64 BuildDate=2021-11-17T08:24:09Z VendorInfo=gohugoio
</pre>

### Description
I want to dynamically add parameters (a simple string array) to a js file. Assume the following setup:

index.html:
```html
{{ with index site.Data.sample site.Language.Lang }}

  {{ $js := resources.Get "js/my-script.js" | js.Build (dict "params" .text) }}
  {{ if eq hugo.Environment "production" }}
  {{ $js = $js | minify | fingerprint }}
  <script src="{{ $js.RelPermalink }}" integrity="{{ $js.Data.Integrity }}"></script>
  {{ else }}
  <script src="{{ $js.RelPermalink }}"></script>
  {{ end }}

{{ end }}
```

data/sample/en.yml
```yaml
text:
  - first text
  - second text
```

data/sample/de.yml
```yaml
text:
  - erster text
  - zweiter text
```

### Expected Behavior
On my german page, a js file with content `[ 'erster text', 'zweiter text' ]` should be included.
On my english page, a js file with content `[ 'first text', 'second text' ]` should be included.

### Current Behavior
On both my german and my english page, the js file has the content `[ 'first text', 'second text' ]`. If I use hugo to directly template the texts into html, the pages shows correct behavior, so it is not an issue with my multi-language setup.

When building hugo in production mode, the js file is minified. In both my `en/js` and my `de/js` subfolder, I can see that two files were built, e.g.
```
$ ls public/en/js
my-script.min.13045798bd4ffdf5f6028171b284f2c002b2935e6290c20138a014aaeec9f6cc.js
my-script.min.57594674ede04fcd8ea70c2a38c817cec1ae872d9f79fbe496615bcdc63be34a.js
```

However, on both pages only the english version is included into the html page.

**Comment by pamubay** [comment]
IIRC, i had this kind of problem before, and it's related to the filename of the resources has the same `targetPath`.

I suggest to try publish each lang script with different `targetPath`.

```diff
{{ with index site.Data.sample site.Language.Lang }}

++ {{- $targetPath := print "js/my-script-" site.Language.Lang ".js" }}
   {{ $js := resources.Get "js/my-script.js" | js.Build (dict "params" .text "targetPath" $targetPath) }}
  
  {{ if eq hugo.Environment "production" }}
    {{ $js = $js | minify | fingerprint }}
      <script src="{{ $js.RelPermalink }}" integrity="{{ $js.Data.Integrity }}"></script>
    {{ else }}
      <script src="{{ $js.RelPermalink }}"></script>
    {{ end }}

{{ end }}
```

Dont forget to run it first with `--gc` flag to clear previous cached resources

**Comment by bep** [comment]
There is two problems here, I'm about to fix the second, so I'll focus on the fist; you need to somehow include the language code in `targetPath` when you pass it to `js.Build`.
