### ISSUE TITLE
HTTPS page has internal links to HTTP: Lets Hugo stick with what main address is.

### ISSUE THREAD

**Issue by idarek** [gohugoio/hugo#9225]
I noticed recently, that in some of my markdown files I refer to link (like www.example.com) without creating it as a link `[www.example.com](https://www.example.com)`.

Once generated, this www. links are converted into clickable links which is fine, but the problem arrise when your website is HTTPS but default and links are converted into HTTP resulting issues: HTTPS page has internal links to HTTP.

It will be nice if default conversion will maintain how site is set. If main address is http:// convert to http:// but when in config address is https:// all default links from markdown when converted shall be with https:// but default.

**Comment by pamubay** [comment]
Try disable `linkify` feature:

```diff
markup:
  goldmark:
    extensions:
++    linkify: false
```

**Comment by idarek** [comment]
That's just how to turn off, but I am more rather about different thing.

**Comment by jmooring** [comment]
See <https://github.com/yuin/goldmark/issues/267>.

If implemented, we would still need to figure out how to set the value. Changing the value based on the `baseURL` or `.IsServer` might be [surprising](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and could result in 404s.

I suggest setting the value in site configuration, with a default value of `http` to avoid breaking existing sites. 

Personally, I think @pamubay is correct.  `www.example.org` is ambiguous.

**Comment by idarek** [comment]
Hmm that make sense.

**Comment by jmooring** [comment]
[yuin](https://github.com/yuin/) explained that the behavior (inserting `http`) is defined in the GFM spec:
<https://github.github.com/gfm/#autolinks-extension->

So this isn't going to happen.
