### ISSUE TITLE
figure shortcode respects height, but ignores width

### ISSUE THREAD

**Issue by tlindsay42** [gohugoio/hugo#9226]
figure shortcode respects height value, but ignores width. Able to duplicate in Chrome, Firefox, incognito for both, as well as both the local server and published site- including editing the img tag via dev tools.

### Example

<pre>
{{< figure src="/images/avatars/bio-photo.jpg" alt="Troy Lindsay headshot" height="50" width="50" >}}
</pre>

![image](https://user-images.githubusercontent.com/11078689/144171143-d9914db3-03fb-48f1-aa62-2bff6e4290a0.png)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.89.4-AB01BA6E+extended windows/amd64 BuildDate=2021-11-17T08:24:09Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
@tlindsay42 I am unable to reproduce the behavior.

```bash
git clone --single-branch -b hugo-github-issue-9226 https://github.com/jmooring/hugo-testing hugo-github-issue-9226
cd hugo-github-issue-9226
hugo server
```
