### ISSUE TITLE
Remove Page.Page()

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9227]

**Comment by jmooring** [comment]
Will this stop working?

layouts/_default/single.html

```text
{{ partial "foo" . }}
```

layouts/partials/foo.html

```text
{{ .Page.Title }}
```

**Comment by bep** [comment]
>Will this stop working?


... Yes. Maybe that was a bit rash ... I guess people have this construct to make the templates more portable (between shortcodes and page) ...

**Comment by bep** [comment]
OK, I'll drop that idea ...
