### ISSUE TITLE
Check issue with remote resources.Get and Hugo server

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#9233]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ Hugo version

hugo v0.90.0-DEV+extended darwin/arm64 BuildDate=unknown

</pre>

### Does this issue reproduce with the latest release?
No

I just built Hugo from source and tested commit [0eaaa8f](https://github.com/gohugoio/hugo/commit/0eaaa8fee37068bfc8ecfb760f770ecc9a7af22a) that introduces XML support in Hugo. 

Using the [provided example](https://github.com/gohugoio/hugo/commit/0eaaa8fee37068bfc8ecfb760f770ecc9a7af22a#diff-21f6e8b806add9daa9c00243b808d10459b255687aa2ef1beb45090e7c1c3f19R67-R75):
```
{{ with resources.Get "https://example.com/rss.xml" | transform.Unmarshal }}
     {{ range .channel.item }}
         <strong>{{ .title | plainify | htmlUnescape }}</strong><br />
         <p>{{ .description | plainify | htmlUnescape }}</p>
         {{ $link := .link | plainify | htmlUnescape }}
         <a href="{{ $link }}">{{ $link }}</a><br />
         <hr>
     {{ end }}
 {{ end }}
```
Upon first execution of the `hugo server` command I am always getting the following error:
`<transform.Unmarshal>: error calling Unmarshal: MIME "application/rss+xml" not supported`

However if I execute `hugo server` first and then paste the above code and hit save, then the remote RSS output is displayed as expected.

Furthermore I am unable to render the contents of the RSS image element from a feed e.g.
```
  <image>
    <url>https://example.com/image/example.gif</url>
    <title>Example</title>
    <link>https://example.com</link>
  </image>
```
I tried `{{ .image.url }}`, `{{ .image.title }}`, `{{ .image.link }}`.
They all return empty. Is rendering of this element supported?

Anyway I thought you may want to know.

cc: @bep @vanbroup

**Comment by vanbroup** [comment]
Thanks for your feedback, do you have a link to the RSS feed or a complete example RSS file that is showing them problem?

Have you tried dumping the results for debugging using:

```
{{ with resources.Get "https://example.com/rss.xml" | transform.Unmarshal }}
     {{ . }}
 {{ end }}
```

**Comment by onedrawingperday** [comment]
By using 

>{{ with resources.Get "https://example.com/rss.xml" | transform.Unmarshal }}
>     {{ . }}
> {{ end }}

I am getting a map of the feed.

Regarding the image issue I mentioned above,I just realised that most feeds, embed the image inside CDATA typically within the `<description>` element.

I tried rendering it with: `<p>{{ .description | safeHTML }}</p>` and I am getting HTML output but I am still unable to render the images although the HTML seems ouputted.

Here are is a sample feed I tested:

https://hyperallergic.com/feed/

Of course all of the above is displayed after the project is served as I mentioned above.

Anyway, thank you for all your hard work in implementing this feature.
It does seems quite complicated though as I've seen all sorts of different feed setups.

P.S. The unmarshall error that I mention above still happens. I only get output if I already have the server running and then fetch the remote feed.

**Comment by bep** [comment]
Thanks for the heads up, that sounds like a issue that needs looking into...

**Comment by onedrawingperday** [comment]
@vanbroup 

I just figured it out and I am able to render remote images locally with `{{ .description | safeHTML }}`.

The problem I encountered earlier was CORS related, due to the project's server configuration.

Anyway sorry to bother. 
Everything seems to work just fine with the new XML support.
Now Hugo can be used as a RSS  reader!

Again thanks so much for this!

The `transform.Unmarshal` error on first server load remains, as mentioned above.

**Comment by vanbroup** [comment]
> I just figured it out and I am able to render remote images locally with {{ .description | safeHTML }}.\n\nThe problem I encountered earlier was CORS related, due to the project's server configuration.

This is why the example is using:
{{ .description | plainify | htmlUnescape }}

The embedding of third party HTML comes with significant security risk and should only be used if you completely trust the source.

**Comment by vanbroup** [comment]
> The `transform.Unmarshal` error on first server load remains, as mentioned above.

I will try to replicate this issue later today.

What is the command you are using to start the server?

**Comment by onedrawingperday** [comment]
Simply `hugo server`

**Comment by bep** [comment]
Info: I'm planning on doing a Hugo release on Monday.

/cc @jmooring

**Comment by vanbroup** [comment]
> @vanbroup
> 
> I just figured it out and I am able to render remote images locally with `{{ .description | safeHTML }}`.

You can also use this method, which is safer than just including third party HTML on your side. 

```html
{{ with resources.Get "https://example.com/feed/" | transform.Unmarshal }}
     {{ range .channel.item }}
        <div style="display: inline-block;">
            {{ $desc := (.description | transform.Unmarshal) }}
            {{ with resources.Get (index $desc.img "-src") }}
            {{ $img := .Fill "200x200 smart" }}
            <img src="{{ $img.Permalink }}" style="float: left; margin-right: 10px;"/>
            {{ end }}
            <div>
                <strong>{{ .title | plainify | htmlUnescape }}</strong><br />
                <p>{{ .description | plainify | htmlUnescape }}</p>
                {{ $link := .link | plainify | htmlUnescape }}
                <a href="{{ $link }}">{{ $link }}</a><br />
            </div>
        </div>
        <hr />
     {{ end }}
 {{ end }}
```
Please note that this downloads and processes images locally, this prevents any CORS issues but keep in mind that images might hold copyrights. You probably want to consider usage and include a copyright notification.

**Comment by vanbroup** [comment]
> Simply `hugo server`

I have not yet been able to replicate your issue, until now, what operating system are you using?

Can you also test with a new hugo site, using the default config? Just to make sure that this is not triggered by any of the config settings.

**Comment by onedrawingperday** [comment]
>You probably want to consider usage and include a copyright notification.

Thank you very much for the method you posted above.
My use case is the following: 
I would like to mirror my Instagram posts on my website.
Currently I am using a third party service to generate the Instagram RSS, up until now I was rendering what I needed with a Python tool.

Your method will be simplifying my workflow.

I already sort of anticipated that there was a method to get the `img -src` embedded in a RSS `description` element but I hadn't had the time to explore it just yet.

This feature is way cooler than I thought.

**Comment by onedrawingperday** [comment]
>what operating system are you using?
I am on the latest macOS 12.0.1 

Just checked with another skeleton Hugo project, unfortunately again the error is there:
```
Start building sites … 
hugo v0.90.0-DEV+extended darwin/arm64 BuildDate=unknown
ERROR 2021/12/03 11:07:25 render of "section" failed: "/Users/alex/Downloads/thethousandkingdoms-main/layouts/_default/list.html:2:91": execute of template failed: template: _default/list.html:2:91: executing "main" at <transform.Unmarshal>: error calling Unmarshal: MIME "application/rss+xml" not supported
ERROR 2021/12/03 11:07:25 render of "section" failed: "/Users/alex/Downloads/thethousandkingdoms-main/layouts/_default/list.html:2:91": execute of template failed: template: _default/list.html:2:91: executing "main" at <transform.Unmarshal>: error calling Unmarshal: MIME "application/rss+xml" not supported
ERROR 2021/12/03 11:07:25 render of "section" failed: "/Users/alex/Downloads/thethousandkingdoms-main/layouts/_default/list.html:2:91": execute of template failed: template: _default/list.html:2:91: executing "main" at <transform.Unmarshal>: error calling Unmarshal: MIME "application/rss+xml" not supported
ERROR 2021/12/03 11:07:25 render of "section" failed: "/Users/alex/Downloads/thethousandkingdoms-main/layouts/_default/list.html:2:91": execute of template failed: template: _default/list.html:2:91: executing "main" at <transform.Unmarshal>: error calling Unmarshal: MIME "application/rss+xml" not supported
Error: Error building site: failed to render pages: render of "section" failed: "/Users/alex/Downloads/thethousandkingdoms-main/layouts/_default/list.html:2:91": execute of template failed: template: _default/list.html:2:91: executing "main" at <transform.Unmarshal>: error calling Unmarshal: MIME "application/rss+xml" not supported
```

**Comment by onedrawingperday** [comment]
I just tested the above method:

```
{{ with resources.Get "https://example.com/feed/" | transform.Unmarshal }}
     {{ range .channel.item }}
        <div style="display: inline-block;">
            {{ $desc := (.description | transform.Unmarshal) }}
            {{ with resources.Get (index $desc.img "-src") }}
            {{ $img := .Fill "200x200 smart" }}
            <img src="{{ $img.Permalink }}" style="float: left; margin-right: 10px;"/>
            {{ end }}
            <div>
                <strong>{{ .title | plainify | htmlUnescape }}</strong><br />
                <p>{{ .description | plainify | htmlUnescape }}</p>
                {{ $link := .link | plainify | htmlUnescape }}
                <a href="{{ $link }}">{{ $link }}</a><br />
            </div>
        </div>
        <hr />
     {{ end }}
 {{ end }}

```

Unfortunately I am getting another error. 

```
ERROR 2021/12/03 11:24:04 render of "section" failed: "/Users/alex/Downloads/test/layouts/_default/list.html:5:57": execute of template failed: template: _default/list.html:5:57: executing "main" at <transform.Unmarshal>: error calling Unmarshal: interface conversion: interface {} is string, not map[string]interface {}
```

Apparently [`transform.Unmarshal`](https://gohugo.io/functions/transform.unmarshal/) has a problem with the input:
` {{ $desc := (.description | transform.Unmarshal) }}`

**Comment by vanbroup** [comment]
I think that could happen if the description doesn't contain any HTML, it might need a `with` or a string content check before trying to unmarshal.

**Comment by onedrawingperday** [comment]
Ok, I will try later today and report back.

**Comment by vanbroup** [comment]
I was able to replicate the `MIME "application/rss+xml" not supported` problem on `darwin/amd64`, @bep any idea why this works on Linux and Windows but not on MacOS?

**Comment by bep** [comment]
>any idea why this works on Linux and Windows but not on MacOS?

I have no idea ... It suggests that the MIME type haven't been properly parsed into a "Hugo MediaType", but It does not make much sense to me ... I'm on MacOS so I could eventually look at it.

**Comment by onedrawingperday** [comment]
I forgot to mention that I am on macOS ARM / M1 chip.

**Comment by vanbroup** [comment]
I was able to solve the problem by adding the `rss` file extension to my config file:

```
mediaTypes:
  application/rss+xml:
    suffixes:
    - xml
    - rss
```

This doesn't explain why is works after the server is started and why it works on Linux and on Windows.

Adding the `rss` extension in the default config (here: https://github.com/gohugoio/hugo/blob/master/media/mediaType.go#L171) solves the problem.

I will create a pull request to get this sorted.

**Comment by onedrawingperday** [comment]
@bep
The above fix by @vanbroup also works on my end.

Also I just tested the method posted above for downloading and processing images with a feed that contains HTML and everything works flawlessly.

The Instagram feed I'm checking has a different setup. I suppose that I will figure it out eventually.

Thank you both so much. This new feature offers plenty of new possibilities.

**Comment by onedrawingperday** [comment]
Just in case someone else tries to render an image in Hugo from a remote XML feed and the [above method](https://github.com/gohugoio/hugo/issues/9233#issuecomment-985363756) throws the aforementioned error because the input element is perceived as a string, I was able to render the remote image as follows.

Remote input sample:
<details>
  <summary> (click to expand)</summary>
 <description><![CDATA[The It [revisited] (detail), digital collage, dimensions variable, 2011-2021<br/><br/>#onedrawingperday<br/><img src="https://scontent-cdg2-1.cdninstagram.com/v/t51.2885-15/fr/e15/s1080x1080/251604405_3135819613318088_7081904035945418342_n.jpg?_nc_ht=scontent-cdg2-1.cdninstagram.com&_nc_cat=108&_nc_ohc=PQ-XLq-q7IAAX_OWLY4&edm=AAuNW_gBAAAA&ccb=7-4&oh=d33a202f9f2a1bc0729bdb427e1e8553&oe=61B288BE&_nc_sid=498da5" alt="Photo by Alexandros on November 03, 2021. May be a drawing." width="1080" height="1080"/>]]></description>
</details>

Template code:
```
    {{ $img := findRE `src="([^"]+)"` .description 1 | print }}
    {{ $img = $img | replaceRE `\[src="([^"]+)"\]` `${1}` | urls.Parse }}
 {{ with resources.Get $img }}
            {{ $img := .Fill "200x200 smart" }}
            <img src="{{ $img.Permalink }}" style="float: left; margin-right: 10px;"/>
            {{ end }}>
```
**Notes**

- The `print` function after `findRE` is required because otherwise Hugo throws the cryptic error:
`unable to cast []string ... of type []string to string`

- `urls.Parse` is required to decode the remote image link
