### ISSUE TITLE
Add spotify shortcode support

### ISSUE THREAD

**Issue by pnijhara** [gohugoio/hugo#9248]
Currently, hugo is supporting only Twitter, Vimeo, Instagram and Youtube's shortcode. It would be great (and a really huge help) if hugo supports podcast services.

**Comment by felicianotech** [comment]
Any examples of another project doing this or how it might look?

**Comment by pnijhara** [comment]
@felicianotech, I found https://github.com/Lednerb/bilberry-hugo-theme using spotify shortcode for rendering. I am not sure how they are using it. But you might give a look at the example site and understand the stuff.

**Comment by pnijhara** [comment]
Similarly, https://github.com/eshlox/simplicity is also using some additional shortcodes like for speakerdeck which is also very uselful.

**Comment by jmooring** [comment]
Instead of creating yet another opinionated, built-in shortcode, create a custom shortcode to embed the various Spotify widgets ([example](https://www.veriphor.com/articles/spotify-widgets)).
