### ISSUE TITLE
Error: nil pointer evaluating resource.Resource.Permalink - when the resource is valid

### ISSUE THREAD

**Issue by mckoss** [gohugoio/hugo#9250]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.89.4-AB01BA6E+extended linux/amd64 BuildDate=2021-11-17T08:24:09Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

I have a page bundle, with an image file, profile.jpg, in the page's images subdirectory.  A page template
with this code reports an error (as if the file was not found).

```
{{ $image := .Resources.GetMatch "images/profile.*" }}
{{ $image.Permalink }}
----
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: testimonials/single.html:11:9: executing "main" at <partial "testimonial" .>: error calling partial: "/home/mckoss/src/ra-website/themes/ra-theme/layouts/partials/testimonial.html:7:9": execute of template failed: template: partials/testimonial.html:7:9: executing "partials/testimonial.html" at <$image.Permalink>: nil pointer evaluating resource.Resource.Permalink

```

BUT, change the code to this:

```
{{ $image := .Resources.GetMatch "images/profile.*" }}
{{ with $image }}
    {{ $image.Permalink }}
{{ end }}
```

Produces NO ERROR - and outputs the permalink just fine (I was originally trying to .Resize this Page resource) - but this test case produces the same result.

I also confirmed in the non-with case that $image is not itself nil:

```
{{ printf "%#v: ---> %v" $image $image }}
---
&resources.resourceAdapter{commonResource:resources.commonResource{}, resourceTransformations:(*resources.resourceTransformations)(0xc00045f0c0), resourceAdapterInner:(*resources.resourceAdapterInner)(0xc0004defa0)}: ---> images/profile.jpg
```

So, it seems that the {{ with }} statement (while I agree is better coding practice) - has the side-effect of validating the resource reference.

EXPECT: In the case of a found resource, to be able to reference it's properties and methods WITHOUT having to first
test if the result of GetMatch is non-nil.

**Comment by jmooring** [comment]
Unable to reproduce.
I suspect that one or more of the pages rendered with this code does not have the resource that the code is looking for. 

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by bep** [comment]
@jmooring is right; these things are kind of hard to reason about when we do things in parallel and you have 1000s of something.

**Comment by mckoss** [comment]
If you'd like to see a reproducible case - I created this repro for you.

https://github.com/mckoss/hugo-bug-repro
