### ISSUE TITLE
hugo.exe new 软件/a.md，home页生成目录    软件s，我想把s去掉，中文没有这样变复数。

### ISSUE THREAD

**Issue by yinhanghang** [gohugoio/hugo#9256]
hugo version
hugo v0.89.4-AB01BA6E windows/amd64 BuildDate=2021-11-17T08:24:09Z VendorInfo=gohugoio

hugo.exe new 软件/a.md
![image](https://user-images.githubusercontent.com/52708329/145154332-b69b1bdd-411d-49d7-9596-efb6cab93b0a.png)

配置的list.html
![image](https://user-images.githubusercontent.com/52708329/145154425-4ed86404-8530-4e49-9a13-e8f82e09f4fd.png)
没有自己添加s，我感觉可能是hugo自动变为复数，使用中文，很不习惯这样，希望可以帮助我

**Comment by sunzhe96** [comment]
有一个比较直观的方式：在中文目录下建立一个`_index.md`，比如`软件/_index.md`，然后在yaml中写你想要显示的标题。

**Comment by bep** [comment]
Sorry, but I don't understand the language given. We need to have these GitHub issues written in English. I suggest you post your question in Chinese at https://discourse.gohugo.io/
