### ISSUE TITLE
Add transparency option to images.Overlay

### ISSUE THREAD

**Issue by gytisrepecka** [gohugoio/hugo#9257]
Image watermarking was introduced with [v0.80.0](https://github.com/gohugoio/hugo/releases/tag/v0.80.0) and can be used calling [Images.Overlay function](https://gohugo.io/functions/images/#overlay). It is nice, however, to make watermark (logo that is overlayed on top of original image) less intrusive, it makes sense to set transparency (alpha channel) value like this (bottom-right logo has Alpha value 70 out of 100):

![Watermarked image](https://source.gyt.is/gytisrepecka/webimg/raw/commit/cbae5c1c980e4e863ce3e23d041c8c37a8645a03/cmd/webimg/result_img.jpg)

I have [implemented image watermarking](https://source.gyt.is/gytisrepecka/webimg/src/branch/master/watermark.go#L81) using standard Go `image` library, so it would not be difficult to add Alpha setting to `Images.Overlay`. Default parameter could be 100 (overlayed image is not transparent at all), but when correct number specified, it could get transparent at specified rate.

Would this be something community would find useful to be added to [image processing](https://gohugo.io/content-management/image-processing/)?

Related issues: #4595, #8057.

**Comment by bep** [comment]
I would welcome such a change.

A note to others looking at this issue: The Overlay function does support Alpha channel today, so if you overlay an image with transparency, that is preserved (which I guess is good enough for most watermarking situations -- it's not hard to edit 1 image by hand).

**Comment by gytisrepecka** [comment]
> I would welcome such a change.
> 
> A note to others looking at this issue: The Overlay function does support Alpha channel today, so if you overlay an image with transparency, that is preserved (which I guess is good enough for most watermarking situations -- it's not hard to edit 1 image by hand).

Would be cool to have an ability to set a level of transparency in shortcode parameter as bright images might look better with watermark having smaller visibility value while darker images might require 90-100% of watermark visibility.

I will make a Pull Request with this modificiation 🤓 Is it better to modify Overlay filter or create a separate one?

**Comment by bep** [comment]
>Is it better to modify Overlay filter or create a separate one?

Add an option. Call it _opacity_ (which is what PhotoShop uses), 0-100%.

**Comment by gytisrepecka** [comment]
Because current `Overlay` filter is [implemented specifically](https://github.com/gohugoio/hugo/blob/master/resources/images/overlay.go#L31) for usage with [gift](https://github.com/disintegration/gift) library, there is really no good way to implement _opacity_ setting to overlayed image rather than modifying `disintegration/gift` library itself so that it would use [DrawMask](https://pkg.go.dev/image/draw#DrawMask) like [I did](https://source.gyt.is/gytisrepecka/webimg/src/commit/cbae5c1c980e4e863ce3e23d041c8c37a8645a03/watermark.go#L81) and would support _opacity_ as additional attribute to it's DrawAt [options](https://github.com/gohugoio/hugo/blob/9c24b86e4b634d7db761a3e57c1b64fead880aff/resources/images/overlay.go#L38).

However, it doesn't seem like `disintegration/gift` is maintained anymore.

So my idea is to tidy up [code.gyt.is/webimg](https://source.gyt.is/gytisrepecka/webimg) so that it would support image objects (instead of file paths) and create it as stand-alone filter. `Watermark` perhaps? Or that looks redundant from Hugo filters point-of-view?

**Comment by bep** [comment]
>However, it doesn't seem like disintegration/gift is maintained anymore.

Not sure what you mean by that; it has 2 open issues 0 open PRs.

A general comment to this is that for a transparency option to be considered in Hugo, it needs to be small/simple. Adding another third-party image library does most likely not fall into that category.

**Comment by gytisrepecka** [comment]
Well, [the library](https://github.com/disintegration/gift) hasn't been updated in almost 2 years, but I'll see if contributing to it makes sense.

Thanks, I think considering current Overlay filter implementation, adding `opacity` should not be a part of Hugo and the issue can be closed.

**Comment by jmooring** [comment]
Superseded by https://github.com/gohugoio/hugo/issues/11471
