### ISSUE TITLE
Provide easier access to Regex capturing groups

### ISSUE THREAD

**Issue by chrillek** [gohugoio/hugo#9272]
Currently, FindRE and ReplaceRE allow using capturing groups, but access to them in Hugo is not easily possible. Something like [FindAllStringSubmatch](https://cs.opensource.google/go/go/+/go1.17.5:src/regexp/regexp.go;l=1190) from the GO RegEx package would be a welcome addition to FindRE

**Comment by merwok** [comment]
It is relevant for the original stated use case.

**Comment by jmooring** [comment]
Superseded by #10594.
