### ISSUE TITLE
date is not working

### ISSUE THREAD

**Issue by songproducer** [gohugoio/hugo#9273]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.90.0+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes

This is what I've forked:
https://github.com/render-examples/hugo-quick-start

Date shows up as January 1, 0001.

Here is my config:

```
baseURL = "https://example.com"
footnoteReturnLinkContents = '↩'
languageCode = "en-us"
title = "My site"
theme = "ananke"
[permalinks]
  posts = '/:year/:month/:title/'
[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

```

Here is my post frontmatter:

---
title: "My First Post"
date: .Date
---

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
