### ISSUE TITLE
remote resouces.Get and Script caches  (not a bug)

### ISSUE THREAD

**Issue by gj52** [gohugoio/hugo#9274]
HI,

how can we define the stored location for remote files.
I tried with a remote mathjax script and it is stored in the root foder.
I like to define a cache dir for scripts ... js or getjs does not work.

from my partial

```
{{ $fill := resources.Get "https://polyfill.io/v3/polyfill.js?features=es6"  | minify }}
{{ with $fill }} <script defer src={{ .RelPermalink }} ></script> {{ end}}
{{ $jax := resources.Get "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" | minify}} 
{{ with $jax }} <script id="MathJax-script" defer src={{.RelPermalink }}></script>{{ end }}
```
ending up with 

```
<script defer="" src="/polyfill_12517151231422109024.min.js"></script>
<script id="MathJax-script" defer="" src="/tex-mml-chtml_8654962730841299996.min.js"></script>
```

Would like to have it unter /js

**Comment by bep** [comment]
There is a longer story here (we have talked about a `resources.Copy` or `resources.Rename` function) ...

You can currently workaround it with `resources.Concat` which takes a `targetPath` option, but ...

In your case I would recommend you use the minifier in `js.Build`; set `minify=true` and `targetPath=whatever.js` and that should work.

I suggest you take further questions at https://discourse.gohugo.io/
