### ISSUE TITLE
Hugo Archetypes - Problem with dots in the file name

### ISSUE THREAD

**Issue by sergio-carlavilla** [gohugoio/hugo#9276]
<pre>
$ hugo version
hugo v0.89.4-AB01BA6E+extended freebsd/amd64 BuildDate=2021-11-17T19:30:45Z+0000 VendorInfo=freebsd
</pre>

### Does this issue reproduce with the latest release?

Yes

1º Create a folder in the archetypes

<pre>
mkdir archetypes/new-release
</pre>

2º Add an _index.adoc file

3º Run the hugo new command

<pre>
hugo new --kind new-release releases/15.0R
</pre>

And the output:

<pre>
Error: target path "releases/15.0R" is not a known content format
</pre>

**Comment by bep** [comment]
> releases/15.0R

Try releases/15.adoc or releases/15.ad

**Comment by sergio-carlavilla** [comment]
This doesn't solve the problem the idea it's to create a folder not a file.
The folder name should be 15.0R or 15.1R
