### ISSUE TITLE
Multilingual mode: hugo new cannot determine  content directory for second language

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#9284]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.91.0-DEV+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes.

---

This issue came up in the forum earlier: https://discourse.gohugo.io/t/error-creating-new-post-error-failed-to-resolve-post-to-a-archetype-template/36043/

A user with a bilingual Hugo project that uses `/en/` and `/it/` mapped to the respective content directories `content/english` and `content/italian` is unable to create a new content file with the command `hugo new` for the second language.
```
hugo new italian/post/filename.md
Error: could not determine content directory for "/content/italian/post/filename.md"
```

I was able to reproduce the above in one of my own multilingual projects.
There were no issues with my project in the past but now I am also getting the `failed to resolve` error when I try to create a content file under the second language's `contentDir`.

**Comment by KitsuneSolar** [comment]
@onedrawingperday #9204 
a similar case?

**Comment by onedrawingperday** [comment]
@KitsuneSolar 

No. We did not get an error in this case.
