### ISSUE TITLE
Release notes stopped appearing on the GoHugo.io-website

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#9286]
If it's done manually, then someone forgot to add the release notes to the website. If it's done automatically, something is broken. 

https://gohugo.io/news/ - release notes for 0.90.0 and 0.90.1 are missing.

**Comment by bep** [comment]
We stopped doing it. Too much work, now releases is GH only.

**Comment by davidsneighbour** [comment]
Well, wouldn't that be a nice test of the capabilities of getJSON then? Add a list of recent releases with https://docs.github.com/en/rest/reference/repos#releases linking to the release pages.
