### ISSUE TITLE
hugo new command: add support for data files under the dataDir

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#9287]
Currently the `hugo new ` command creates a file that is a known content format (.md, .html)  under the `contentDir`.

Please consider expanding the `hugo new` command to allow for the creation of known data file formats (.yml, .json, xml, .csv) under the `dataDir`.

I do have a use case, where I am creating a data file for consumption in Hugo templates, whenever a remote resource is updated.  Currently I have to rely on shell commands to generate the data file and keep it updated -which is not particularly ideal-. 

Also https://github.com/gohugoio/hugo/issues/9243 is related to this proposal.

**Comment by bep** [comment]
>I do have a use case, where I am creating a data file for consumption in Hugo templates, whenever a remote resource is updated.

How would this new thing work with the above use case?

**Comment by onedrawingperday** [comment]
I am using an archetype that fetches remote data and renders a JSON object.

When I execute `hugo new` I would like to be able Hugo to generate a `.json` file under the `dataDir`.
For example: `hugo new data/api.josn`

Currently I am using `hugo new content/api.md` 
Then with a shell script I am changing the file extension from `.md` to `.json` 
And moving the file to the data directory so that it can be consumed by the data templates.

Of course whenever I need to overwrite the JSON I have to execute the `rm` command.
That's why I tagged #9243 as related to this issue since a `hugo new --force` flag would make overwriting easier.

Anyway I suppose that this is a low priority issue.
But one can have Hugo generate data files from remote sources today.
It is limiting that `hugo new` only works for `.md` or `.hml` content files and not data files.
