### ISSUE TITLE
--editor option affected by security.exec.allow in 0.91.x

### ISSUE THREAD

**Issue by jgreely** [gohugoio/hugo#9315]
Starting in 0.91.0 and 0.91.1, `hugo new --editor emacs post/006666.md` started failing with:

```
Content "/Users/jgreely/sitetest/content/post/006666.md" created
Editing "/Users/jgreely/sitetest/content/post/006666.md" with "emacs" ...
Error: access denied: "emacs" is not whitelisted in policy "security.exec.allow"; the current security configuration is:

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|HOME|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.91.1-F4235057 darwin/amd64 BuildDate=2021-12-22T15:31:06Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by bep** [comment]
You need to add `emacs` to the whitelist.

**Comment by jgreely** [comment]
So, long-time basic functionality now requires copy-pasting an array of regular expressions into your config file and editing it. Seems like a bad idea, but whatever.

**Comment by davidsneighbour** [comment]
That's a breaking change, but Hugo is a pre-release program (version 0). 

It should however treat all it's CLI commands with dignity and a documented explanation how to set them up properly. I would expect the `--editor` CLI flag documentation to somehow explain that it requires additional setup to work at all.

**Comment by bep** [comment]
>So, long-time basic functionality now requires copy-pasting an array of regular expressions into your config file and editing it.

You can either do that or set an environment variable.

**Comment by bep** [comment]
Just to be clear:

* I added this security config primarily for myself: As part of helping people with they Hugo issues I run many random Hugo sites on my computer, and wanted better control of what external programs that gets executed and what information they get. 
* I could maybe have made the `--editor` flag/config setting work without change, but it wasn't obvious to me -- and it was certainly not obvious to me that it would be worth the extra work.

This is my current Hugo OS env:

```
# Hugo env
export HUGO_CACHEDIR=/Users/bep/dev/hugo_cache
export HUGO_SECURITY_FUNCS_GETENV="^HUGO_"
export HUGO_SECURITY_EXEC_OSENV="(?i)^(PATH|PATHEXT|APPDATA|HOME|TMP|TEMP|TERM)$"
export HUGO_SECURITY_EXEC_ALLOW="^(dart-sass-embedded|go|npx|postcss)$"
```
And yes, I understand that nothing is 100% secure, but the above gives me enough confidence to build "rando" Hugo sites on my computer, something I would never do with a JS based generator.

**Comment by jgreely** [comment]
+1 for adding this new limitation to documentation and release notes.
