### ISSUE TITLE
Markdown render hook - table

### ISSUE THREAD

**Issue by coliff** [gohugoio/hugo#9316]
[Markdown render hooks](https://gohugo.io/getting-started/configuration-markup#render-hook-templates) are awesome!

I'd be very happy to see support added for tables too. Some use cases could be to add specific `position:sticky` classes to the headers, default CSS classes, wrapping the table in a div for horizontal scrolling of the the table on smaller screens etc.

**Comment by bep** [comment]
I agree about the awesomeness, but they are a "hammer solution" that I would prefer to limit its use... Could you not add CSS classes using attributes?

**Comment by coliff** [comment]
Users can easily add classes to the `<table>` itself like so:

```
| Language        | Setting |
| --------------- | ------- |
| U.S. English    | en-us   |
| Korean          | ko      |
| Turkish         | tr      |
{.table}
```

but often I'd like to add JavaScript interactivity to elements _within the_ table - e.g. needing to use specific CSS classes on the `<thead>` or `th` etc... or sometimes adding specific IDs for integrating JavaScript enhancements for table sorting etc.

**Comment by michaeltlombardi** [comment]
A use case for this that I have is turning markdown tables into interactive roll tables - a visitor can click on a column to select a random row or random cells in each row based on a dice roll called by JavaScript.

I have workarounds for this, but they move my module users further from "normal" Markdown and my user base is indie tabletop game authors rather than web devs or tech writers.

There's other use cases I can think of, like marking a table as sortable or filterable, or otherwise adding more interactivity to the table. AFAIK, any of these sorts of things requires writing a shortcode today.

**Comment by jmooring** [comment]
Some thoughts about how this might work...

The render hook would receive the following context:

- `.Attributes` -- The Markdown attributes, if any.
- `.Ordinal` -- The zero-based ordinal of the table on the page.
- `.Page` -- A reference to the current page.
- `.THead` -- A slice of table header rows, where each row is a slice of table cells.
- `.TBody` -- A slice of table body rows, where each row is a slice of table cells.

Each table cell would be a `struct`:

```go
type TableCell struct {
	Text        template.HTML
	Alignment   string // left, center, or right
}
```

The render hook would look something like this:

```html
<table>
  <thead>
    {{ range .THead }}
      <tr>
        {{ range . }}
          <th style="text-align: {{ .Alignment }}">{{ .Text }}</th>
        {{ end }}
      </tr>
    {{ end }}
  </thead>
  <tbody>
    {{ range .TBody }}
      <tr>
        {{ range . }}
          <td style="text-align: {{ .Alignment }}">{{ .Text }}</td>
        {{ end }}
      </tr>
    {{ end }}
  </tbody>
</table>
```

**Comment by bep** [comment]
So, while @jmooring 's proposed API makes sense, this seems, to me at least, like a lot of effort needed for marginal gain/interest. Hugo's proposal process lacks some ways to measure interest, but I see a handful of "thumbs up" in the above comments, which to me sounds like a marginal feature.

**Comment by jmooring** [comment]
I don't have sense of how many developers would take advantage of this, but I know we've had a few forum topics related to [Bootstrap tables](https://getbootstrap.com/docs/5.0/content/tables/). For example, it would be very convenient to render every table like this:

```html
<div class="table-responsive">
  <table class="table">
    ...
  </table>
</div>
```

**Comment by sebastiancarlos** [comment]
> [Bootstrap tables](https://getbootstrap.com/docs/5.0/content/tables/). For example, it would be very convenient to render every table like this:
> 
> ```html
> <div class="table-responsive">
>   <table class="table">
>     ...
>   </table>
> </div>
> ```

That's exactly my use-case, by the way.

**Comment by bep** [comment]
@jmooring looking at this, I see that Goldmark renders attributes for table rows and cells; I'm having a hard time wrapping my head around what kind of attributes this could be ... If so, I think I need to have a look into the new iterators in Go 1.23 to see if I can make row/cell into rangeable structs ...

**Comment by haroldhadrada** [comment]
Wrapping the tables with a division is my main use case. Right now I am manipulating the .Content with replaceRE to achieve that. Kudos on the progress here!
