### ISSUE TITLE
Wrong Permalink for resource in multihost mode when baseURL in one language has a sub path

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9324]
I'm doing some  code simplification and have a test failure that looks like a bug.

I have a case with 
* Multiple language, each with it's own `baseURL`
* The English language also has a sub-path (`baseURL = "https://example.com/docs"`), the others not
* Still, the resources for French gets prefixed with the `/docs` path.

**Comment by jmooring** [comment]
Duplicate of https://github.com/gohugoio/hugo/issues/10912.
