### ISSUE TITLE
[Sharing a shortcode] I created a shortcode to display and run code in post

### ISSUE THREAD

**Issue by gingerhot** [gohugoio/hugo#9328]
I created a shortcode [hugo-gitfx](https://github.com/gitx-io/hugo-gitfx) to display and run code in Hugo. Also [a blog](https://gitx.io/post/hugo-with-gitfx/) to show its usage.

**Comment by davidsneighbour** [comment]
Please post in https://discourse.gohugo.io under the Tips and tricks category.
