### ISSUE TITLE
Allow configuring table of contents in front matter

### ISSUE THREAD

**Issue by undergroundwires** [gohugoio/hugo#9329]
I'd like to be able to set `startLevel = 2` on page level (in front matter). Each page has different content and often different content organization.

So this is a feature request about allowing configuring `[markup.tableOfContents]` content page level additional to global site level in configuration file.

It would the an allow to use `{{ .Page.TableOfContents }}` with page-specific needs.

**Comment by nikhilweee** [comment]
This would be much appreciated! I was thinking having a shortcode for toc (just like highlight) which allowed block-level configuration. Something like `{{<toc startlevel=2 endlevel=3 ordered=false>}}` would be really cool.
