### ISSUE TITLE
Hugo.Extended build Under libstdc++.so.6.0.19 

### ISSUE THREAD

**Issue by MIngPAPA** [gohugoio/hugo#9330]
Hello, 
Here is my proposal. 

When I use CentOS 7 to install the hugo-extended, it always gets error which shows the version of libstdc++ is too low.
```
hugo: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by hugo)
hugo: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by hugo)
```
Under centos 7, the default enviornment is
-  gcc  4.8.5
-  libstdc++.so.6.0.19
-  glibc 2.17

If the forward compatibility is promised by hugo-extended, that will be very helpful!

**Comment by bep** [comment]
This has been discussed before. This project isn't big enough that we can provide binaries for more than the most common setups. If that doesn't work for you, I suggest you build it from source.
