### ISSUE TITLE
Make resources folder optional

### ISSUE THREAD

**Issue by ifrican** [gohugoio/hugo#9331]
I don't use it, so is there a way to stop it from being generated during a build? Same for `.hugo_build.lock`.

**Comment by bep** [comment]
Both of these files/directories are used by Hugo.

**Comment by afrophi** [comment]
> Both of these files/directories are used by Hugo.

I don't use both personally and they keep being generated with every `hugo` or `hugo serve` command hence I keep having to delete both on every build to stop 'littering' my repo. They are empty. Maybe a simple command in config file would suffice?
