### ISSUE TITLE
Add method to detect a Page Bundle

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#9332]
This is a proposal for a method to detect whether a page is a bundle.

Something like `.IsBundle` or if you consider making it even more explicit `.IsBranch` and `.IsLeaf`

The reason for this request comes from this forum topic:
https://discourse.gohugo.io/t/show-taxonomy-content-if-defined/36257

However in the past I have also wanted a simple way to perform this check.

In my use case I needed this method for conditionally generating Open Graph images etc, and do something like:
```
{{ if eq .Page.IsBundle }}
<--- use the first image found in the bundle --->
{{ else }}
<--- use the image specified in the project's config --->
{{ end }}
```
Sure there are other methods to do the above.
But still I think that this request has merit as it would simplify template logic and a project's setup i.e. less front matter parameters.

**Comment by jmooring** [comment]
The `.BundleType` method returns `leaf`, `branch`, or an empty string. So you can do:

```
{{ if .BundleType }}
<--- use the first image found in the bundle --->
{{ else }}
<--- use the image specified in the project's config --->
{{ end }}
```

**Comment by davidsneighbour** [comment]
> The .BundleType method returns leaf, branch, or an empty string.

Does it do that documented and "official"? The documentation search does return 0 results for BundleType (I have the feeling that the documentation search might need some usability updates, but 0 results might point to it not being mentioned). If that is working then it should be documented and "set in stone" so it doesn't disappear.

**Comment by jmooring** [comment]
It's been around for almost four years ([#4662](https://github.com/gohugoio/hugo/issues/4662)). There's a open documentation issue: [#785](https://github.com/gohugoio/hugoDocs/issues/785).
