### ISSUE TITLE
Feature: specify path to lockFileBuild

### ISSUE THREAD

**Issue by hazcod** [gohugoio/hugo#9336]
We should be able to specify the location of the build lock file.
In my case my sources are mounted readonly, so the lock file cannot be written and thus the build fails.

**Comment by LukeDeWaal** [comment]
Could you perhaps post some more information regarding this error such as the output when the build fails?

**Comment by bep** [comment]
The lock file needs to be in a known and stable place or it would lose its value (as an inter process lock file). I understand the problem, but the solution can not be an option to specify the path.
