### ISSUE TITLE
nil pointer evaluating resource.Resource.MediaType

### ISSUE THREAD

**Issue by Kuhlig** [gohugoio/hugo#9338]
Started with https://toha-guides.netlify.app/posts/getting-started/prepare-site/
added author.yaml file in /data/en/ 

Changed
image: "http://localhost:1313/images/default-avatar_hu9bf48a08e17db6472c2e32b73058a6bb_47653_148x148_fit_box_3.png"
OR 
image: "images/author/soe_face.png"
OR 
image: "https://hugo-toha.github.io/images/author/john_hu7f9991f5b5d471ecdfc6cff3db1a9fe6_6397_148x148_fit_box_3.png"

Got error 

Rebuild failed:

Failed to render pages: render of "home" failed: execute of template failed: template: index.html:49:8: executing "index.html" at <partial "sections/home.html" .>: error calling partial: "/home/rob/WEBSITEII/themes/toha/layouts/partials/sections/home.html:31:44": execute of template failed: template: partials/sections/home.html:31:44: executing "partials/sections/home.html" at <$authorImage.MediaType.SubType>: nil pointer evaluating resource.Resource.MediaType

when commenting # Image line everything works fine

Thanks for help - greate template!

 .... home.html:31:44: ....

{{/* apply image processing. don't use "Fit" in svg or gif because its not supported */}}
{{ if and $authorImage (and (ne $authorImage.MediaType.SubType "svg") ( ne $authorImage.MediaType.SubType "gif")) }}
  {{ $authorImage = $authorImage.Fit "148x148" }}
{{ end }}
{{/* get file that matches the filename as specified as src="" in shortcode */}}
{{ $src := resources.Get $backgroundImage }}

anything i can do?
cu rob

### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.91.2+extended linux/amd64
</pre>

### Does this issue reproduce with the latest release?
YES

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by Kuhlig** [comment]
ok - sorry
