### ISSUE TITLE
Add page template function

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9339]
We have several issues discussing something like this (re partials and `.Render`), but I haven't found a way (or at least not a reasonably simple way) to implement it ...

... until now.

This function will return the _top level data context_  (the `Page`) when called from anywhere (shortcodes, partials, render hooks, view templates).

So you would do:

`partials/mypartial`:

```
{{ render.Context.Title }}
```

Will print the entry Page's title.

My explanation above may not be perfect, but this is plenty useful -- the hard part is getting the name right.

/cc @regisphilibert @jmooring etc.

**Comment by bep** [comment]
Since this "context" is always a `Page`, maybe we could just call it ... `page`, which would be analogue to the `server` global.

So, in the top level `single.html` etc. template, these will be the same:

````
{{ .Title }}
{{ page.Title }}
```

**Comment by jmooring** [comment]
The issue I remember with `.Render` is <https://github.com/gohugoio/hugo/issues/8182#issuecomment-801194305>, where it would be convenient to do something like:

```
{{ .Render "summary" (dict "page" .Page "myVar" "foo") }}
```

It doesn't seem like the proposed `page` function would address this particular case  (`myVar` isn't on `.Page`). Please comment.

Also, what is the difference between `page.Title` and `$.Title`? It seems like both return the top level data context.

**Comment by bep** [comment]
OK, I  may have forgot what the ".Render problem" was ... but I suspect I'm talking about "another one".

>Also, what is the difference between page.Title and $.Title? It seems like both return the top level data context.

So,

```
{{ $.Title }}
{{ page.Title }}
```

The above would only be the same in the _entry_ template (e.g. `single.html`).

**Comment by jmooring** [comment]
Does that mean I would be able to call a partial without passing the page context? 

layouts/_default/single.html

```
{{ partial "render-some-page-stuff" }}
```

layouts/partials/render-some-page-stuff.html

```
Title: {{ page.Title }}<br>
Date: {{ page.Date }}<br>
```

**Comment by regisphilibert** [comment]
We have `site` which is a invoking the page's `.Site` method throughout. 

So it would make sense that this is called `page`.

I think this is great, the more simple the context passed to a partial is — and now we'll never need to pass the page — the better. 

I don't foresee any problems. Except making sure users understand the fact that any template be it a partial a ".Render" or a returning partial are bound to a page and even though it has no consequence it might create confusion when using `partialCached` where your partial might end up with the same `page`. But that's just logical and only concerns users using the new feature.

**Comment by bep** [comment]
>Does that mean I would be able to call a partial without passing the page context?

Yes.

**Comment by bep** [comment]
>partialCached where your partial might end up with the same page.

That is true, but that is also a "problem" you would have today.
