### ISSUE TITLE
Deprecate undocumented .File.Extension 

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9352]
`.File.Ext` is documented.
`.File.Extension` is not documented.

See <https://github.com/gohugoio/hugo/blob/master/source/fileInfo.go#L73-L77>:

```
// Extension gets the file extension, i.e "myblogpost.md" will return "md".
Extension() string

// Ext is an alias for Extension.
Ext() string // Hmm... Deprecate Extension
```

Documentation: <https://gohugo.io/variables/files/>

**Comment by sara-meie** [comment]
I'd like to take a crack at this one. I assume you want to use helpers.Deprecate to deprecate the function so that it will show a warning when used. Probably also refactor any usage of Extension() in the actual codebase as well?

**Comment by bep** [comment]
@sara-meie that is a sensible approach, yes.
