### ISSUE TITLE
armv7l   Error running Hugo: Illegal instruction

### ISSUE THREAD

**Issue by dufei99** [gohugoio/hugo#9353]
### What version of Hugo are you using (`hugo version`)?
<pre>

# ./hugo --version
Illegal instruction
</pre>
（hugo_0.91.2_Linux-ARM.tar.gz）

root# uname -a
Linux MiWiFi 2.6.36.4brcmarm #16 SMP PREEMPT Tue Dec 21 07:59:19 CET 2021 armv7l Tomato

root# cat /proc/cpuinfo
Processor       : ARMv7 Processor rev 0 (v7l)
processor       : 0
BogoMIPS        : 1998.84

processor       : 1
BogoMIPS        : 1998.84

Features        : swp half thumb fastmult edsp
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : Northstar Prototype
Revision        : 0000
Serial          : 0000000000000000

**Comment by tomml** [comment]
Same here with hugo_0.93.1_Linux-ARM.tar.gz:

```
cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 0010
Serial          : 00000000ea9d971b
Model           : Raspberry Pi Model B Plus Rev 1.2
```

**Comment by janekska** [comment]
The same with:
hugo_0.104.3_linux-arm.tar.gz


root@zipitz2:/usr/local/bin# cat /proc/cpuinfo
processor       : 0
model name      : XScale-PXA270 rev 7 (v5l)
BogoMIPS        : 155.39
Features        : swp half thumb fastmult edsp iwmmxt
CPU implementer : 0x69
CPU architecture: 5TE
CPU variant     : 0x0
CPU part        : 0x411
CPU revision    : 7

Hardware        : Zipit Z2
Revision        : 0000
Serial          : 0000000000000000

**Comment by bep** [comment]
@janekska the linux-arm archive is currently built with `GOARM=7` which, on paper at least, should work on ARM >= 7. If you read your specs right, you're at ARM 5. We don't have the capacity to build for every ARM variant out there, so your best bet is to build this yourself, e.g. `GOARM=5 GOARCH=arm go install`.

**Comment by janekska** [comment]
>  `GOARM=5 GOARCH=arm go install`.

Somme beginner questions:

Is this goes to one command line? Or should I put these as env variables in a config file or system?

If I install Go on my windows - are these parameters will be enough to compile Hugo for my arm linux? Or should I compile on Go linux?
