### ISSUE TITLE
Could hugo add a new config parameter to allow add a prefix to images url

### ISSUE THREAD

**Issue by hitzhangjie** [gohugoio/hugo#9354]
I use `typora` as my markdown editor, normally I store images into the assets folder alongside the markdown files.

For example, helloworld.md references an image helloworld.png:

.......
![helloworld](assets/helloworld.png]
.......

This image is rendered normally in `typora` editor, now I want to build it with hugo, the generated HTML <img> src="assets/helloworld.png" will be an error link. It should prefixed with '/blog/' (my markdown is under content/blog/).

The easiest way I think is to modify the markdown content, ![content](/blog/assets/helloworld.png), but this way will be very inconvenient, considering following writing. 

I read the document but didn't find some documents about solving this kind of problem. If there's some config parameters to help work around this, please let me know.

If there's no such parameters, could we add one to prefix the image url generated in HTML.

Or, could `hugo` automatically copy the images to "$publishDir/blog/assets/helloworld.png", if hugo works like this, then it would be nice. `ox-hugo` has a feature like this, please see: https://ox-hugo.scripter.co/doc/image-links/.

**Comment by bep** [comment]
I suspect you can get what you want by adding a Markdown render hook template to your project, see https://github.com/bep/portable-hugo-links

**Comment by hitzhangjie** [comment]
@bep I modified the layout/blog/single.html, change the {{.Content}} to {{replace .Content "src=\"assets/" "src=\"/blog/assets/"}}.
It works. This method is easy, but not very clean.

I will learn the project you mentioned above. Thanks very much.

**Comment by bep** [comment]
>This method is easy, but not very clean.

Yea, you should certainly look at render hooks and file mounts. Take further questions on the forum.
