### ISSUE TITLE
NewContentEditor option doesn't accept arguments for editor

### ISSUE THREAD

**Issue by lamyseba** [gohugoio/hugo#9356]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.89.4+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
I suppose

Some editors can be lauched with command line options. Eg Kate editor has a -s option to open file within a chosen session.
If I put
<pre>
newContentEditor: "kate -s mySessionName"
</pre>
in my `config.yml` file, I get an error
> Error: exec: "kate -s mySessionName": executable file not found in $PATH

Removing the `-s mySessionName` options makes things work as expected.
Searching about this problem, I found it should be solved since v0.77 in https://github.com/gohugoio/hugo/commit/d48a98c477a818d28008d9771050d2681e63e880, but I'm still getting the problem. Is there a regression?

**Comment by davidsneighbour** [comment]
Run `which kate` in your CLI, then add the proper path to kate into your configuration. Something like `/usr/bin/kate` probably. You can _never_ assume that anything is using the same paths that you have configured in your terminal session.

**Comment by lamyseba** [comment]
Thanks @davidsneighbour for your answer.  That is not the solution. Kate is in `/usr/bin`, and I already tried to put
```
newContentEditor: "/usr/bin/kate -s mySessionName"
```
and this gives me
> Error: exec: "/usr/bin/kate -s pauavelo.fr": stat /usr/bin/kate -s mySessionName: no such file or directory

And, as I said previously, just writing 
```
newContentEditor: kate 
```
works fine, without arguments and without full path. So the path is found. The problem are the arguments.

**Comment by jmooring** [comment]
> Is there a regression?

Yes, introduced with https://github.com/gohugoio/hugo/commit/9185e11effa682ea1ef7dc98f2943743671023a6.
