### ISSUE TITLE
Add a --panicOnWarning flag

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9357]
This issue is especially targeted at deprecation warnings. These textual references without a file/template context (filename, line number) is sometimes very hard to debug. It would be much nicer if I could do `hugo server --panicOnWarning` and just iterate until the warnings go away.

We should also print that flag as part of the deprecation message.

/cc @jmooring

**Comment by carlinmack** [comment]
Perhaps intentional but this flag does not panic on `WARN`

```go
Start building sites …
hugo v0.92.0-B3549403+extended linux/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio
WARN 2022/01/12 23:07:10 .File.TranslationBaseName on zero object. Wrap it in if or with: {{ with .File }}{{ .TranslationBaseName }}{{ end }}
```
