### ISSUE TITLE
Cannot set default frontmatter format

### ISSUE THREAD

**Issue by ktprograms** [gohugoio/hugo#9363]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.91.0+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

When creating a new site with `hugo new site blog -f toml`, the configuration file is correctly in a toml format, but when creating new posts with `hugo new test.md`, the frontmatter is in a yaml format.

As far as I can see, there isn't any configuration option to set the default frontmatter format, so this issue can be solved one of two ways:
- Add a option in the configuration file for which frontmatter format to use.
- In the documentation for options for `hugo new site`, don't mention that the `-f` option can control the `config & frontmatter format`

**Comment by ktprograms** [comment]
@bep Is there any way to create a new post with toml frontmatter?

**Comment by bep** [comment]
@ktprograms the "hugo new" post now uses whatever format lives in the archetype file -- so what you want to do is to create a custom template(s) in the /archetype folder. We used to respect the mentioned setting, but it became really complicated to maintain after we got archetype folder and templating support ...

**Comment by ktprograms** [comment]
@bep I see. Thanks.

So I would either modify the syntax in the `archetypes/default.md` file, or add a `archetypes/toml-frontmatter.md` file and use it with `hugo new -k toml-frontmatter name-of-post.md`, right?

**Comment by bep** [comment]
Yea, that's right -- I would probably just edit the default...

**Comment by donny-stacks** [comment]
> 
> 
> 
> 
> ### What version of Hugo are you using (`hugo version`)?
> 
> 
> 
> <pre>
> 
> $ hugo version
> 
> hugo v0.91.0+extended darwin/arm64 BuildDate=unknown
> 
> </pre>
> 
> 
> 
> ### Does this issue reproduce with the latest release?
> 
> Yes
> 
> 
> 
> When creating a new site with `hugo new site blog -f toml`, the configuration file is correctly in a toml format, but when creating new posts with `hugo new test.md`, the frontmatter is in a yaml format.
> 
> 
> 
> As far as I can see, there isn't any configuration option to set the default frontmatter format, so this issue can be solved one of two ways:
> 
> - Add a option in the configuration file for which frontmatter format to use.
> 
> - In the documentation for options for `hugo new site`, don't mention that the `-f` option can control the `config & frontmatter format`
