### ISSUE TITLE
Hugo 0.74.0 and later breaks asciidoc based website

### ISSUE THREAD

**Issue by billziss-gh** [gohugoio/hugo#9367]
I have an asciidoc based website in this repository: [`winfsp.web`](https://github.com/winfsp/winfsp.web). Building the website with latest hugo versions breaks any HTML files derived from original asciidoc documents.

For example, the page at https://winfsp.github.io/doc/Frequently-Asked-Questions/ has the following (correct) HTML source when building with `0.73.0`:

```
          <h1>Frequently Asked Questions</h1>
<div class="sect1">
<h2 id="_general">General</h2>
<div class="sectionbody">
<div class="qlist qanda">
```

And the following (incorrect) HTML source when building with `0.74.0`:

```
          <h1>Frequently Asked Questions</h1>
<p>= Frequently Asked Questions
:source-highlighter: pygments</p>
<p>== General</p>
<p>[qanda]</p>
```

The source for the relevant asciidoc file can be found here: https://github.com/winfsp/winfsp.web/blob/master/content/doc/Frequently-Asked-Questions.asciidoc

### How to reproduce

- Install `asciidoctor` and the `pygments.rb` gem.
- `git clone --recursive https://github.com/winfsp/winfsp.web.git`
- Change to the `winfsp.web` directory and run `make public`. (You may need to change the `Makefile` to point to the appropriate version of hugo such as `0.73.0` and `0.74.0`.)

### What version of Hugo are you using (`hugo version`)?

Any version from `0.74.0` onwards exhibits this problem. Version `0.73.0` does not exhibit the problem.

```
$ hugo version
Hugo Static Site Generator v0.74.0-D2B11626 darwin/amd64 BuildDate: 2020-07-13T10:30:21Z
```

### Does this issue reproduce with the latest release?

Yes. The issues reproduces with hugo version `0.91.2` that is currently the latest release.

**Comment by jmooring** [comment]
I was able to build your site with the latest version of Hugo (v0.91.2) by:

1. Changing the file extensions from `.asciidoc` to `.adoc` (or to `.ad` if you prefer)
2. Adding the following to the site configuration:

```yaml
security:
  exec:
   allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
```

See <https://gohugo.io/about/security-model/#security-policy>

> Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by billziss-gh** [comment]
> In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

I will continue maintaining that this is a bug that should be fixed. If you track it in #9074 that is fine for me, but your advice to use the forum is counter-productive.

I have a website that works with an older version of hugo and that stopped working with recent versions. Your solution is to perform intrusive surgery on my website (change the file extensions). But this is simply a workaround for a problem that needs to be fixed.
