### ISSUE TITLE
Investigate .RenderString regression

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9383]
See https://discourse.gohugo.io/t/multilingual-related-page-renderstring-regression-in-0-92/36555/16?u=bep

I'm pretty sure this came from https://github.com/gohugoio/hugo/pull/9342 -- but I'm also pretty sure that that PR surfaced an already existing bug re output formats and `.Translations`, so I think we need to understand and fix the real issue rather than reverting the above.

@ptgott

**Comment by ptgott** [comment]
Thanks for the heads up. I’ll have time to look into this over the weekend and possibly today.

**Comment by danielfdickinson** [comment]
FYI I discovered this issue (with @jmooring's help) through another route:

Quoting Joe:

>TLDR: Invoking .Page.RenderString on a page without a backing file throws an erroneous warning

The full discussion is in https://discourse.gohugo.io/t/0-92-new-warning-when-section-has-no-index/36590
