### ISSUE TITLE
`anchorlinenos` and `lineanchors` attributes do not work when using with code fences

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#9385]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.92.0-B3549403 linux/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

### Hugo Discourse discussion

https://discourse.gohugo.io/t/bug-anchorlinenos-true-attribute-doesnt-work-when-using-code-fences/36564

### Reproducible example

- [source repo](https://gitlab.com/hugo-mwe/hugo-mwe/-/tree/anchorlinenos)
- [Rendered HTML showing the issue][1]
- [Markdown content file](https://gitlab.com/hugo-mwe/hugo-mwe/-/raw/anchorlinenos/content/posts/anchor-line-numbers.md)

**Steps to reproduce the problem**

```shell
git clone https://gitlab.com/hugo-mwe/hugo-mwe
cd hugo-mwe
git checkout anchorlinenos
./srv.sh
```

### Analysis

It looks like the `anchorlinenos` and `lineanchors` attributes get passed on as-is to the rendered HTML without being treated as special attributes for creating line number hyperlinks.

I see this when I look at the source of the [above test HTML page][1]:

![image](https://user-images.githubusercontent.com/3578197/149570941-31b418ef-df51-46c9-817d-ed9ee924b43b.png)

Possibly related code:

https://github.com/gohugoio/hugo/blob/fcbbbef22dac2967c9096c6f1a0aff9b50d7a4cb/markup/goldmark/render_hooks.go#L149-L154

The link anchoring feature was added in https://github.com/gohugoio/hugo/commit/fb0f2cc718a54fd0774a0367e0a60718b5731de5 but the new attributes probably still need to be added in `render_hooks.go`. /cc @fjorgemota

[1]: https://anchorlinenos--hugo-mwe.netlify.app/posts/anchor-line-numbers/

**Comment by jmooring** [comment]
When using code fences, the available options are limited by the [yuin/goldmark-highlighting](https://github.com/yuin/goldmark-highlighting) module (upstream).

The `hl_style` option should be added to the `attributeExcludes` map.

More info:
https://discourse.gohugo.io/t/36564/3

**Comment by kaushalmodi** [comment]
I really wanted to move away from using the `highlight` shortcode completely because of https://github.com/gohugoio/hugo/issues/4717. But now I will use it only when I need to use `anchorlinenos`.

I'll close this issue given that this is recognized as an expected behavior.

**Comment by jmooring** [comment]
> But now I will use it only when I need to use anchorlinenos

Or set the default in site configuration:

```toml
[markup.highlight]
anchorLineNos = true
```

**Comment by kaushalmodi** [comment]
@jmooring 

> Or set the default in site configuration

Yeah, I realized that that worked. But my sites have hundreds of code blocks and I don't want to enable the anchors for every line.

That makes me think.. why does enabling that variable in site config work even for code fences?

**Comment by kaushalmodi** [comment]
I think that if Hugo makes the `anchorLineNos=true` value propagate from the code fence attribute to wherever it needs to set, then this issue will be resolved. Because setting that var in the global site config definitely works.

**Comment by kaushalmodi** [comment]
@bep Can you please take a look at this?

Is it possible to make this work by any change from the Hugo side?

````
```emacs-lisp { linenos=table, anchorlinenos=true, lineanchors=org-coderef--xyz }
(save-excursion
   (goto-char (point-min))
```
````

Right now, the line anchors don't get enabled if we use code fences; they work only with the `highlight` shortcode.

1. I am seeing that you are refactoring a lot of code around goldmark code block rendering and I am hoping that this is a good time to fix this while you are working on that code base.
2. I haven't seen any response on https://github.com/yuin/goldmark-highlighting/issues/25.

**Comment by bep** [comment]
There are now 1 handling of this config so I assume that your case will now just work, but I would soonish merge my work into master branch, and would appreciate if "someone else" could verify this then.

**Comment by kaushalmodi** [comment]
@bep Thanks! Yes, the latest master has fixed this bug. To avoid regression, I added a small test in https://github.com/gohugoio/hugo/pull/9562. The test passed locally, but is failing in the CI for a reason I don't understand.
