### ISSUE TITLE
Do not render hl_style as an HTML attribute

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9390]
The [yuin/goldmark-highlighting](https://github.com/yuin/goldmark-highlighting) module accepts the following attributes: `linenos`, `linenostart`, `hl_lines`, and `hl_style`.

For example:

`````
```bash {linenos=table linenostart=4 hl_lines=["4-6",9] hl_style=emacs}
#!/usr/bin/env bash

mul() {
  foo=$1
  bar=$2
  echo $((foo * bar))
}

mul 6 7
```
`````

These attributes have special meaning, and should not be rendered as HTML attributes in the wrapping element.

We already do this for `linenos`, `linenostart`, and `hl_lines`. We just need to add `hl_style` to the list.

**Comment by kaushalmodi** [comment]
From the docs, the variable for setting the style is just "style": https://gohugo.io/getting-started/configuration-markup#highlight

While this is being fixed, can you also make the attribute for highlighting style consistent between highlight shortcode and code fences?

**Comment by jmooring** [comment]
@ While this is being fixed, can you also make the attribute for highlighting style consistent between highlight shortcode and code fences?

No. First, when using code fences, the syntax is determined by yuin/goldmark-highlighting. Second, even if we were able to somehow alias the option name, using `style` would be a poor choice because `style` is a standard HTML attribute, and you would end up with invalid CSS in the style attribute of the wrapping div.

**Comment by kaushalmodi** [comment]
I meant using `hl_style` (and documenting only that) for the highlight shortcode and deprecating the `style` attribute there.

**Comment by jmooring** [comment]
That's a separate issue, affecting the shortcode, the function, related tests, and documentation for each. If you feel strongly about it, create a new proposal.

**Comment by kaushalmodi** [comment]
> If you feel strongly about i

It's mainly to prevent user confusion. May be a table in the documentation would suffice that would compare the names and availability of various attributes for highlight shortcode vs the code fence style.

**Comment by jmooring** [comment]
> May be a table in the documentation

That's a separate issue. If you feel strongly about it, please create a new proposal in the documentation repository. Thanks.
