### ISSUE TITLE
Caching Hugo modules in ~/.cache/hugo/modules

### ISSUE THREAD

**Issue by UtkarshVerma** [gohugoio/hugo#9392]
I use Hugo modules all the time and it works great. However, one minor annoyance that I face is that it downloads the modules to `/tmp/hugo_cache/modules`. This means that I lose the cached modules after a reboot.

Would it be possible to have a configurable env var for specifying where Hugo caches its modules, and I mean modules alone. I tried changing `HUGO_CACHE` and it works but as it also caches build files, I don't want to use it as I want avoid too many writes to my HDD.

**Comment by pamubay** [comment]
Never tried cofiguring cache, but have you tried this? [Configure Caches](https://gohugo.io/getting-started/configuration/#configure-file-caches)

```
caches:
  modules:
    dir: :cacheDir/modules
    maxAge: -1
```

> :cacheDir
This is the value of the cacheDir config option if set (can also be set via OS env variable HUGO_CACHEDIR). It will fall back to /opt/build/cache/hugo_cache/ on Netlify, or a hugo_cache directory below the OS temp dir for the others. This means that if you run your builds on Netlify, all caches configured with :cacheDir will be saved and restored on the next build. For other CI vendors, please read their documentation. For an CircleCI example, see this configuration.

**Comment by UtkarshVerma** [comment]
@pamubay Thank you. I set this systemwide through:
```sh
export HUGO_CACHES_MODULES=$XDG_DATA_HOME/hugo"
```
