### ISSUE TITLE
“Smart” punctuation + quotes

### ISSUE THREAD

**Issue by skyfaller** [gohugoio/hugo#9397]
While @brycewray and I suspect it’s Goldmark-caused rather than Hugo-caused, the Goldmark developer seems to require Goldmark issues that are observed in Hugo to be proposed as Hugo issues before he will have anything to do with them. The relevant Goldmark bug is here: https://github.com/yuin/goldmark/issues/180

This issue occurs with the Typographer extension in Hugo — including the most recent release, 0.92.0 — if goldmark is the selected parser. It doesn’t occur if Blackfriday is the selected parser and “smart” punctuation is activated. (Sadly, Blackfriday is deprecated and the last commit in its repo is from Oct 26, 2020.)

Consider the following text in a Markdown file:

```markdown
John's dog is named Sam. The Smiths' dog is named Rover.
```

Expected result: Each apostrophe should be a “smart”/curly apostrophe (`&rsquo;`), given the default behavior of goldmark’s Typographer extension.

Actual result: Only the singular possessive (`John's dog`) has the “smart”/curly apostrophe, while the plural possessive (`Smiths' dog`) has the “dumb”/straight apostrophe (`&apos;`).

There are many other examples where the "smart" quotes fail to operate correctly, as shown on these two demo pages:

- https://gm-typographer.vercel.app/
- https://www.maximumethics.dev/blog/2021/03/smart-quotes/

This issue has been mentioned in the Hugo forums multiple times:
- https://discourse.gohugo.io/t/smart-quotes-do-not-work-properly-in-hugo-with-goldmark/34266
- https://discourse.gohugo.io/t/curly-quotes-with-hugo/36441

While the bug may be upstream, [the upstream maintainer does not speak English fluently](https://github.com/yuin/goldmark/issues/180#issuecomment-769640321) and does not feel comfortable dealing with this issue, while many Hugo users speak English and may be able to fix it.

Please remove the "stale bot" equivalent that closed [the previous Hugo issue](https://github.com/gohugoio/hugo/issues/8099) so that we don't have to keep making meaningless updates to keep the still valid issue alive. 

Thanks in advance for any help or consideration this issue may receive.

### What version of Hugo are you using (`hugo version`)?

<pre>
> hugo version
hugo v0.92.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes.

**Comment by brycewray** [comment]
@skyfaller For what it's worth, I actually did create a Hugo issue about this (https://github.com/gohugoio/hugo/issues/8099) before creating the one for goldmark, as per the requirements of @yuin — but, yesterday, the Hugo repo auto-closed it because of its age and inactivity. 🤷‍♂️

**Comment by brycewray** [comment]
Hugo 0.93.0 with goldmark 1.4.7 definitely fixed all issues I’d previously reported; see the newly updated version of my [test site](https://gm-typographer.vercel.app/). Outstanding!

**Comment by davidsneighbour** [comment]
language... :D
