### ISSUE TITLE
Bump version of Chroma

### ISSUE THREAD

**Issue by Niols** [gohugoio/hugo#9406]
Hello there,

Chroma has a new release, [v0.10.0](https://github.com/alecthomas/chroma/releases/tag/v0.10.0), fixing some issues and adding a few lexers. (It's actually a shame that it was released one day after the last release of Hugo!) Would it make sense to bump Chroma's version for the next major version of Hugo?

Best,  
Nicolas “Niols” Jeannerod

**Comment by bep** [comment]
See #7602 9381

**Comment by Niols** [comment]
Dammit, I'm so sorry, I checked issues about this but not PRs. My bad.
