### ISSUE TITLE
Babel blocked by security policy in Hugo v0.91+

### ISSUE THREAD

**Issue by acalvo** [gohugoio/hugo#9420]
Not sure if it's intended or not, but https://gohugo.io/hugo-pipes/babel/ is blocked by default by the security policy introduced in Hugo 0.91.

This can be solved simply adding it to de config file, for example:

```json
  "security": {
    "exec": {
      "allow": [
        "^dart-sass-embedded$",
        "^go$",
        "^npx$",
        "^postcss$",
        "^babel$"
      ]
    }
  }
```

Anyway, it might not be intended as I see no refs to the default block in https://gohugo.io/hugo-pipes/babel/ ...

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.92.0+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes.

**Comment by jmooring** [comment]
> Not sure if it's intended 

This is the intended behavior.

The error message describes the problem:

> "babel" is not whitelisted in policy "security.exec.allow"

The error message also displays the current configuration

> the current security configuration is:
>
>  [security.exec]
>    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
