### ISSUE TITLE
Hugo attempting to interpret shortcode syntax that's inside a markdown code snippet

### ISSUE THREAD

**Issue by dbrat43** [gohugoio/hugo#9429]
I have a hugo site which dynamically pulls READMEs from different sources. One of the READMEs explains how to use shortcodes and provides an example inside of a code snippet like so: `{{< shortcode-name >}}`

Hugo throws the following error when pulling this README as it tries to interpret the shortcode syntax: "Unable to locate template for shortcode shortcode-name "

Is there any way to have Hugo ignore the shortcode syntax when it's encapsulated in some type of example format?

**Comment by jmooring** [comment]
See <https://discourse.gohugo.io/t/35494/3>

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
