### ISSUE TITLE
failed to extract shortcode

### ISSUE THREAD

**Issue by Lassy1106** [gohugoio/hugo#9432]
### it shows "failed to extract shortcode: template for shortcode "alert" not found?"

<pre>
$ Start building sites … 
hugo v0.92.0+extended darwin/amd64 BuildDate=unknown
Error: Error building site: "/Users/huanglaxi/zz/themes/academic/content/en/home/papers.md:69:1": failed to extract shortcode: template for shortcode "alert" not found

</pre>

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
