### ISSUE TITLE
Invoking .Page.RenderString on a page without a backing file throws an erroneous warning

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9433]
This was introduced in v0.92.0, and is still present in v0.92.1. 

MRE:

```bash
git clone --single-branch -b hugo-github-issue-9433 https://github.com/jmooring/hugo-testing hugo-github-issue-9433
cd hugo-github-issue-9433
hugo 
```

> .File.Path on zero object. Wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}

The warning is triggered in layouts/_default/list.html, line 4:

```
{{ .RenderString "foo" }}
```

References:
- <https://discourse.gohugo.io/t/36590/5>
- <https://github.com/gohugoio/hugo/issues/9383#issuecomment-1013704831>

**Comment by bep** [comment]
Thanks ... We should have made that an error long time ago, but I guess we cannot do that in a patch release ...

**Comment by jmooring** [comment]
> We should have made that an error

Please clarify. Should I update the documentation to indicate that this method should not be used on pages that are not backed by file?
