### ISSUE TITLE
Add sensible fallback for permalink :token when not backed by a file

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9448]
> WARN 2023/02/17 09:40:41 .File.TranslationBaseName on zero object. Wrap it in if or with: {{ with .File }}{{ .TranslationBaseName }}{{ end }}

This is not a new warning; it exists as far back as v0.55.4, but does not exist in v0.54.0 (I didn't test those in between).

And the warning makes sense. But it took me a couple of minutes to figure out what was causing it.

```toml
[permalinks]
tags = "/foo/:filename/"
```

With this content structure:

```text
content
├── post/
│   └── test.md
└── _index.md
```

Where content/post/test.md has:

```toml
tags = ['tag-a']
```

This is obviously resolved with:

```text
content/
├── post/
│   └── test.md
├── tags/
│   └── tag-a/
│       └── _index.md   <-- now there's a file
└── _index.md
```

This was a self-inflicted wound; I'm not even sure what the user was trying to accomplish. 

Although the warning message is accurate...
1. The user wasn't able to identify the cause.
2. The resulting URL is `http://localhost:1313/foo/` instead of `http://localhost:1313/foo/something`

I'm not sure if this is just a documentation issue, or if we should substitute the slug when there isn't a backing file (if that's even possible) and throw a more descriptive warning.

MRE

```bash
git clone --single-branch -b hugo-github-issue-9448 https://github.com/jmooring/hugo-testing hugo-github-issue-9448
cd hugo-github-issue-9448
hugo server
```

**Comment by bep** [comment]
We should try to pick a sensible fallback to the filename in this case, I'm not sure what (I have not looked at the options).

**Comment by jmooring** [comment]
The `".File.TranslationBaseName on zero object"` warning will be seen more frequently as users begin to define permalinks for sections (https://github.com/gohugoio/hugo/pull/10847). I think we need fallbacks for:

```
:title
:slug
:slugorfilename
:filename
```

Example config:

```
[languages.de.permalinks.term]
tags = 'my-tags-de/:slug'
```

**Comment by bep** [comment]
@jmooring thanks, I merged that permalink issue knowing that it needed some tweaking/testing. The gist of the above is that we should never see that warning from Hugo code.

**Comment by bep** [comment]
Note that when this issue was created it was at least the intention that every page that we applied this permalink config to would be backed by a content file (e.g. page==kind). This premise has now changed, and we need to fix this.
