### ISSUE TITLE
Version 92.1 breaks hugo serve with pagination errors (render of "section" failed), up to version 92.0 works

### ISSUE THREAD

**Issue by sean-kintone** [gohugoio/hugo#9451]
Hugo 0.92

`hugo v0.92.1+extended darwin/arm64 BuildDate=unknown
ERROR 2022/02/01 16:50:43 render of "section" failed: "/Users/seanluse/code/developers-site/sites/global/themes/test-developers-theme/layouts/list/twoColumnLayout.html:14:57": execute of template failed: template: list/twoColumnLayout.html:14:57: executing "main" at <(.Paginate .CurrentSection.Pages).Pages>: error calling Pages: runtime error: invalid memory address or nil pointer dereference
ERROR 2022/02/01 16:50:43 render of "section" failed: "/Users/seanluse/code/developers-site/sites/global/themes/test-developers-theme/layouts/list/allArticlesCard.html:19:31": execute of template failed: template: list/allArticlesCard.html:19:31: executing "main" at <.Paginator>: error calling Paginator: 'pager size' must be a positive integer
ERROR 2022/02/01 16:50:43 render of "section" failed: "/Users/seanluse/code/developers-site/sites/global/themes/test-developers-theme/layouts/list/twoColumnLayout.html:14:57": execute of template failed: template: list/twoColumnLayout.html:14:57: executing "main" at <(.Paginate .CurrentSection.Pages).Pages>: error calling Pages: runtime error: invalid memory address or nil pointer dereference
Error: Error building site: failed to render pages: render of "section" failed: "/Users/seanluse/code/developers-site/sites/global/themes/test-developers-theme/layouts/list/allArticlesCard.html:19:31": execute of template failed: template: list/allArticlesCard.html:19:31: executing "main" at <.Paginator>: error calling Paginator: 'pager size' must be a positive integer
Built in 1072 ms
`

version 92.0

`hugo v0.92.0+extended darwin/amd64 BuildDate=unknown
Built in 973 ms
Watching for changes in /Users/seanluse/code/developers-site/sites/global/{archetypes,content,data,i18n,layouts,package.json,static,themes}
Watching for config changes in /Users/seanluse/code/developers-site/sites/global/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
`

**Comment by sean-kintone** [comment]
Sorry if this is already reported. Didn't seem like it

**Comment by jmooring** [comment]
@sean-kintone I am unable to reproduce this. Can you provide a reproducible example? A link to your project repo would be ideal. Thanks.

**Comment by sean-kintone** [comment]
Sorry for the delay. Notifications...

Does this help?

The `Paginate` is being called in the following two templates:
* `allArticlesCard.html`
* `twoColumnLayout.html`

File structure

```txt
layouts/
  ├ list/
    ├ allArticlesCard.html
    ├ twoColumnLayout.html
```

### allArticlesCard.html
```html
<section class="main--content--article--section">
  <div class="main--content--article--section--header">
    <h2 class="main--content--article--section--header--title heading2">{{ .Title }}</h2>
  </div>
  <div class="main--content--article--section--contents">
    <p class="main--content--article--section--contents--introduction">{{ .Description }}</p>
    <ul class="block-link">
      {{- range .CurrentSection.Sections }}
      <li class="block-link--item">
        <div class="block-link--item--list">
          <h3 class="block-link--item--list--title">{{ .Title }}</h3>
          <ul class="block-link--item--list--list">
            {{- range (.Paginator .Site.Params.pagesOfCardListPerCard ).Pages}}
            <li>
              <a href="{{ .RelPermalink }}">{{ .Title }}</a>
            </li>
            {{- end }}
          </ul>
          {{- if ge .Paginator.TotalPages .Site.Params.pagesOfCardListPerCard }}<a class="block-link--item--list--seemore" href="{{ .RelPermalink }}">{{ i18n "see_more" }}</a>{{- end }}
        </div>
      </li>
      {{- end }}
    </ul>
  </div>
</section>
```


### twoColumnLayout.html
```html
<section class="main--content--article--section">
  <div class="main--content--article--section--header">
    <h2 class="main--content--article--section--header--title heading2">{{ .Title }}</h2>
  </div>
  <div class="main--content--article--section--contents">
    <p class="main--content--article--section--contents--introduction">{{ .Description }}</p>
    <ul class="block-list">
      {{- range (.Paginate .CurrentSection.Pages).Pages }}
      <li class="block-list--item">
        <a class="block-list--item--link" href="{{ .RelPermalink }}">
          <h3 class="block-list--item--link--title">{{ .Title }}</h3>
          <p class="block-list--item--link--description">{{ .Description }}</p>
        </a>
      </li>
      {{- end }}
    </ul>
  </div>
  {{ partial "pagination.html" . }}
</section>
```

**Comment by jmooring** [comment]
@sean-kintone Thanks, but no, this doesn't help. I can't reproduce the problem from a few lines of code. A reproducible example is a complete site, perhaps pared down to the bare minimum, where we can `git clone`, build, and see the error.

**Comment by sean-kintone** [comment]
It was something on our end... Sorry for the trouble, closing now.
