### ISSUE TITLE
The Website that I uploaded is not same as the one I saved in my localhost

### ISSUE THREAD

**Issue by 0xdroopy** [gohugoio/hugo#9457]
Hey Team,
I am facing an issue and trying after 12 hours continuously please help me out. I made my website on localhost which looked like this-

![image](https://user-images.githubusercontent.com/98838160/152110788-d2c4a10a-ec31-4956-a677-c0872c0e87f3.png)
But when I uploaded it to github successfully with all the steps , It is coming like this -

![image](https://user-images.githubusercontent.com/98838160/152110888-a243c423-b2f1-4247-b5f2-23a8b19715f7.png)

Please help me out as soon as possible

**Comment by 0xdroopy** [comment]
@jmooring Please help me out as soon as possible

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by 0xdroopy** [comment]
Please help me there

**Comment by 0xdroopy** [comment]
SIr
@jmooring
