### ISSUE TITLE
Configuration option to invoke a command upon build

### ISSUE THREAD

**Issue by tobast** [gohugoio/hugo#9460]
# Idea

I believe it would be nice to have a configuration option to put in the `config.*` file, maybe under `build`, eg. `build.prebuild_hooks`, that would allow the user to specify a collection of hooks to be run before actually building the static pages. It would probably look somewhat like

```yaml
build:
  prebuild_hooks:
  - "make -C scss"
  - "make -C pictures"
```

# Rationale

In my setup, I have a few different Hugo websites, each in its git repository. I use git hooks to automatically deploy the website: whenever a change is pushed onto the main branch, the production server pulls the latest code and runs `hugo` to build the website, effectively deploying the new version.

I often have a few things I would like to run before actually building my site: this could be scss to compile to css, thumbnails to extract out of images, etc; these files usually do not belong in Git since they are automatically generated from files that are same Git repository.

I could, of course, add a line to invoke my scripts in the hookscript before running `hugo`; however, I do believe it would make for a nicer workflow and cleaner configuration if simply running `hugo` could take care of all the invocations that have to run behind the scenes.

**Comment by davidsneighbour** [comment]
Wouldn't that just mean you run `prehook && hugo` instead of `hugo` on deploy? Adding a completely new build system to Hugo will probably open a lot of doors, but also let all the dust and leaves in. I too use a hook system, but this one is _outside_ of hugo and hugo runs as part of it.

**Comment by tobast** [comment]
I definitely agree that this is not *at all* required, and `prehook && hugo` just works. It just seems like a matter of convenience to me. I also deploy automatically my Hugo websites with ansible, and I have a generic role for that; it just seems more convenient to me to have some place to configure that to have a functioning website, I need to run the script named `foo.sh` before.

The thing I do for now is to run something like `[ -x ./prehook.sh ] && ./prehook.sh ; hugo` in my webhook handler to keep it generic — some websites have prehooks, not all —, but it works only because this is my repository and I know the name should be `prehook.sh`. The configuration for this name lies outside of the repository, and it slightly annoys me.

But yep, altogether I agree that if it is not trivial to implement (I don't have a clue about Hugo's internal structure), it might be overkill unless plenty of people also have usecases for this.

**Comment by jmooring** [comment]
@tobast 

This should be safe for _anyone_ to do with _any_ Hugo project:

```
git clone --recurse-submodules some-hugo-project
cd foo
hugo
```

If the project's config file looks like this...

```yaml
build:
  prebuild_hooks:
  - "rm -rf $HOME"
```

...not good.

**Comment by tobast** [comment]
@jmooring That's a fair point. If no mechanism already exists in Hugo that would make it unsafe to run `hugo` on an untrusted project, then I agree it's a bad idea.

**Comment by davidsneighbour** [comment]
![](https://gif-free.com/uploads/posts/2017-04/1492604903_mind-blown-woah-reaction.gif)
