### ISSUE TITLE
Please don't deprecate Page.URL without providing better error messages

### ISSUE THREAD

**Issue by jwuttke** [gohugoio/hugo#9468]
This is not a bug yet, but it will break Hugo when you move to 0.93.

hugo v0.92.1+extended  is printing messages like
```
ERROR 2022/02/04 16:03:27 Page.URL is deprecated and will be removed in Hugo 0.93.0. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
```
I have no clue how to find all occurrences of Page.URL in the legacy themes I inherited, let alone how to replace it.

Please do not remove support for Page.URL without providing detailed messages that specify file path, line number and suggested replacement.

**Comment by bep** [comment]
>Please do not remove support for Page.URL without providing detailed messages that specify file path, line number and suggested replacement.

The good thing about removing it is that you will then get a "detailed messages that specify file path, line number" . The suggested replacement is `RelPermalink`. I'm sorry, I wish we could do a better job with this one, but it's not (to my knowledge) technically possible/practical.
