### ISSUE TITLE
tpl/internal/go_templates/texttemplate/helper.go:11:2: package io/fs is not in GOROOT

### ISSUE THREAD

**Issue by logan-bobo** [gohugoio/hugo#9470]
I am given the following error on the latest release during install and running 
`go install --tags extended`
### What version of Hugo are you using (`hugo version`)?
 v0.92.1

### Does this issue reproduce with the latest release?
yes

Note the Go version is also
go1.17.6

**Comment by jmooring** [comment]
Unable to reproduce with:
`go version go1.17.6 linux/amd64`

When you're in the root of the hugo source directory, what's the output from:

```
whereis go
which go
go version
```

**Comment by logan-bobo** [comment]
looks like the issue is with GH actions. This issue can be closed
```
go: /usr/bin/go /usr/local/go /usr/local/go/bin/go
/usr/bin/go
go version go1.15.15 linux/amd64
``
