### ISSUE TITLE
Build error with github.com/pelletier/

### ISSUE THREAD

**Issue by EduRam** [gohugoio/hugo#9473]
While building Hugo from todays git clone version, I have the following error:

<pre>
$ go version
go version go1.18beta2 linux/amd64

$ git log -1
commit 9262719092d6ec8e034c7a097575defe8611dadb (HEAD -> master, origin/master, origin/HEAD)

$ go build -x -v
...
...
...
0.084s # cd /home/e/go/pkg/mod/cache/vcs/5fc8a6833fc262d7a365ce89f874516d37470daefa52149126edb8776dd883fa; git -c core.autocrlf=input -c core.eol=lf archive --format=zip --prefix=prefix/ c3ba3ef97abbc154a9acc1b0164a022f48e5fd6e
verifying github.com/pelletier/go-toml/v2@v2.0.0-beta.6: checksum mismatch
        downloaded: h1:TA3qh4Cq1VOjh4AJnMHrUFbAsIbD7OnOvpaIRYsU0sI=
        go.sum:     h1:JFNqj2afbbhCqTiyN16D7Tudc/aaDzE2FBDk+VlBQnE=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
</pre>

**Comment by davidsneighbour** [comment]
Delete go.sum. Retry.

**Comment by EduRam** [comment]
Hi! Thanks for the tip @davidsneighbour. 
Managed to build by deleting these entries from "mod.sum", and running again "go mod tidy".

github.com/niklasfasching/go-org v1.6.0 
github.com/pelletier/go-toml v1.9.3
github.com/pelletier/go-toml v1.9.4
github.com/pelletier/go-toml/v2 v2.0.0-beta.3.0.20210727221244-fa0796069526 github.com/pelletier/go-toml/v2 v2.0.0-beta.6

**Comment by bep** [comment]
@EduRam editing `go.sum` does not sound like a ... great idea. This sounds like a corrupted download. I suggest you try to clean out your mod cache and try again. Since this works fine for me, GitHub CI and many others, I don't see how that checksum can be wrong.
