### ISSUE TITLE
Add native support for CODEOWNERS

### ISSUE THREAD

**Issue by marshall007** [gohugoio/hugo#9474]
We are experimenting with Hugo as an alternative to `middleman` (and a bunch of custom Ruby code) for building the [GitLab handbook](https://about.gitlab.com) ([source](https://gitlab.com/gitlab-com/www-gitlab-com/)).

One thing we do in Ruby currently is parse the `CODEOWNERS` file(s) in the repo so that we can surface metadata on each page regarding who the content maintainer is. I think native support for this makes sense as a logical extension of the [Git Info Variables](https://gohugo.io/variables/git/) already supported by Hugo.

See [`hairyhenderson/go-codeowners`](https://github.com/hairyhenderson/go-codeowners) as a sample implementation of a `CODEOWNERS` parser in Go. The implementation is fairly straightforward and supports conventional paths used by both GitHub and GitLab.

My initial thinking is that it would make sense to expose this metadata under the existing `.GitInfo` object for each page, but it might make more sense as a new property on the page object so that the parsing of `CODEOWNERS` files can be opted into separate from `enableGitInfo`.

I'd be happy to work on the initial implementation if we can agree this makes sense to be integrated natively. Cheers!

**Comment by bep** [comment]
@marshall007 The CODEOWNERS construct is a GitLab/GitHub "thing", right, it's not a Git convention?

**Comment by marshall007** [comment]
@bep that's right, it is also supported by less popular Git hosting providers like JetBrains Space, so I think it is a common enough convention to warrant support despite that.

If you disagree I would appreciate your thoughts on how we might go about incorporating the functionality external from Hugo. It is the only real blocker for us to start porting GitLab's content sites to Hugo, so I am eager to find a solution in some form.

You can see an example of how we use this metadata in the sidebar of our company handbook pages: https://about.gitlab.com/handbook/values/
