### ISSUE TITLE
plain HTML documents not supported error for Markdown content that starts with HTML

### ISSUE THREAD

**Issue by ElnuDev** [gohugoio/hugo#9482]
If one has some Markdown content that starts with HTML and has no front matter, Hugo will throw the error "plain HTML documents not supported" regardless of whether or not `markup.goldmark.renderer.unsafe = true` is set in the configuration. If one adds any non-HTML content or even an empty front matter to the document, the error goes away.

### What version of Hugo are you using (`hugo version`)?

First v0.91.2 that is shipped in the Debian repos, then the latest v0.92.1 from Homebrew. Both have the same issue.

```
$ hugo version
hugo v0.91.2-1798BD3F linux/amd64 BuildDate=2021-12-23T15:33:34Z VendorInfo=gohugoio
```
```
$ hugo version
hugo v0.92.1+extended linux/amd64 BuildDate=unknown
```

### Does this issue reproduce with the latest release?

Yes

**Comment by bep** [comment]
> If one adds any non-HTML content or even an empty front matter to the document, the error goes away.

That is what you need to do. I don't think we're going to complicate the parser to support this case -- I'm certainly not spending time on it and I'm only merging a PR if it's simple.

**Comment by jmooring** [comment]
Duplicate of #7296. See also #6098.
