### ISSUE TITLE
LiveReload injection snippet for custom output type is hardcoded to 127.0.0.1

### ISSUE THREAD

**Issue by domolicious** [gohugoio/hugo#9493]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.92.1-85E2E862+extended linux/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

I recently started using custom output formats and I noticed that the LiveReload injection snippet is different from the snippet used otherwise. I suspect it may be a little outdated and it doesn't acknowledge the server configuration.

This is what I get _appended_ to the `<body>` tag when using a custom output format.
```
<script src="http://127.0.0.1:35729/livereload.js?ext=Chrome&amp;extver=2.1.0"></script>
```

This is what I get _prepended_ to the `<head>` tag while using the default (html) output format.
```
<script src="/livereload.js?mindelay=10&amp;v=2&amp;port=80&amp;path=livereload" data-no-instant="" defer=""></script>
```

I serve hugo inside a VM like this so naturally the 127.0.0.1 address is not what I want.
```
sudo hugo server --bind 0.0.0.0 --port 80
```

and my `config/_default/config.toml` is
```toml
[outputFormats]
[outputFormats.Portrait]
baseName = "portrait"
mediaType = "text/html"
```

I would expect the LiveReload functionality for custom output formats to use the same snippet that default output format is using.

**Comment by jmooring** [comment]
This:

```
<script src="http://127.0.0.1:35729/livereload.js?ext=Chrome&amp;extver=2.1.0"></script>
```

is not added by Hugo.

**Comment by domolicious** [comment]
@jmooring You're right, my bad. It appears that was added by the [LiveReload](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei) extension that I am using for Google Chrome. The extension seems to be adding the script tag if it can't find one already existing.

That clears a bit of confusion and the issue is actually about the script tag not getting injected at all when using a custom output format.

**Comment by jmooring** [comment]
@domolicious Please update the issue title and description.

**Comment by jmooring** [comment]
@domolicious 

The livereload snipped is injected for output formats where `isHTML` is `true`. By default, this value is `false`. This will do what you want:

```toml
[outputFormats]
[outputFormats.Portrait]
baseName = "portrait"
mediaType = "text/html"
isHTML = true
```

Try it:

```bash
git clone --single-branch -b hugo-github-issue-9493 https://github.com/jmooring/hugo-testing hugo-github-issue-9493
cd hugo-github-issue-9493
hugo server --renderToDisk

Ctrl+C

grep livereload public/index.html
grep livereload public/potrait.html
```

**Comment by domolicious** [comment]
@jmooring That's it!

Adding `isHTML = true` solves the issue. Thank you for taking the time to help me.

(You closed the issue so I will not update title and description)
