### ISSUE TITLE
Crop images without resizing

### ISSUE THREAD

**Issue by johnsvenn** [gohugoio/hugo#9499]
At the moment Hugo has image processing methods for `Fit`, `Fill`, `Resize`, and `Filter`. I think it would be very useful to have the ability to `Crop` an image without resizing (using the disintegration/gift `CropToSize` method). This would use `Anchor` in exactly the same way as the existing `Fill` method to position the crop.

I've already implemented this locally and if anybody else would find this useful I will add tests, update the docs and submit a PR.

**Comment by bep** [comment]
>I think it would be very useful to have the ability to Crop an image without resizing 

Yes, we should probably add this, but in what situations would you use this and not `Fill`?

**Comment by johnsvenn** [comment]
My use case is that I have several hundred very large detailed images (generative art) and I wanted to create smaller thumbnail / summary images that just showed a part of the image but without resizing so none of the detail is lost.

**Comment by bep** [comment]
@johnsvenn OK, a pull request would be welcomed. Just put new documentation in the /docs folder of this repo.

**Comment by johnsvenn** [comment]
Thanks @bep  

Will do.
