### ISSUE TITLE
Sort pages by title length

### ISSUE THREAD

**Issue by nobe4** [gohugoio/hugo#9509]
Follow up of https://github.com/gohugoio/hugo/pull/9507

I couldn't find any way to achieve a `{{ range .Pages.ByTitleLength }}` ordering of pages via the existing methods. 

The main issue I was facing was that only fixed strings seems to be used during ordering:

```golang
{{ range sort .Pages "Title" }}
// OK

{{ range sort .Pages "len(Title)" }}
// len(Title) isn't a field of struct type page.Page

{{ range sort .Pages "len .Title" }}
// len isn't a field of struct type page.Page

{{ range sort .Pages "Title.len" }}
// len is neither a struct field, a method nor a map element of type string

{{ range sort .Pages "Title.length" }}
// length is neither a struct field, a method nor a map element of type string
```

So it seemed that a simple way to achieve that was to have a sorting method similar to `ByLength` (which sorts by content length).

**Comment by jmooring** [comment]
This will do what you want:

```
{{ $pages := slice }}
{{ range site.RegularPages }}
  {{ $pages = $pages | append (dict "titleLength" (len .Title) "page" .) }}
{{ end }}

{{ range sort $pages "titleLength" "asc" }}
  <h2><a href="{{ .page.RelPermalink }}">{{ .page.LinkTitle }}</a> ({{ .titleLength }})</h2>
{{ end }}
```

This is the first time that I have seen a need to sort by title length, so I'm not sure it's worth the effort to implement, document, and maintain.

**Comment by nobe4** [comment]
I agree that it's not worth a full feature if it's been the first time someone requests this.
Many thanks for providing a working example 🙏
