### ISSUE TITLE
regression: Panic when "markup.highlight.linenos" set to table or inline

### ISSUE THREAD

**Issue by kbyyd24** [gohugoio/hugo#9518]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.92.2+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

In my `config.yml`, the following config will reproduce the issue:

```yml
markup:
  highlight:
    linenos: table # or inline
```

Then run `hugo server`, got the follwing output:

```shell
❯ hugo server -p 4000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x16041f2]

goroutine 1 [running]:
github.com/gohugoio/hugo/hugolib.newHugoSites({{0x261e550, 0xc0007ac810}, 0xc000785940, 0x0, {0x0, 0x0}, {0x2619a90, 0xc0004b7770}, {0x0, 0x0, ...}, ...}, ...)
        github.com/gohugoio/hugo/hugolib/hugo_sites.go:398 +0x832
github.com/gohugoio/hugo/hugolib.NewHugoSites({{0x261e550, 0xc0007ac810}, 0xc000785940, 0x0, {0x0, 0x0}, {0x2619a90, 0xc0004b7770}, {0x0, 0x0, ...}, ...})
        github.com/gohugoio/hugo/hugolib/hugo_sites.go:527 +0x11d
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
        github.com/gohugoio/hugo/commands/commandeer.go:419 +0x4f8
sync.(*Once).doSlow(0xc0004b7770, 0x2135260)
        sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        sync/once.go:59
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc0004140f0)
        github.com/gohugoio/hugo/commands/commandeer.go:377 +0x8a5
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0x1, 0x1, 0xc00019a1c0, {0x25c8620, 0xc000784a80}, 0xc00017f640, {0x0, 0x0, 0x0})
        github.com/gohugoio/hugo/commands/commandeer.go:195 +0x310
github.com/gohugoio/hugo/commands.initializeConfig(0x52, 0x65, 0x50, 0x213ab6b, {0x25c8620, 0xc000784a80}, 0xc00087fc88)
        github.com/gohugoio/hugo/commands/hugo.go:125 +0x31
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc000784a80, 0xc0003c7680, {0xc00087fcf0, 0x0, 0x0})
        github.com/gohugoio/hugo/commands/server.go:242 +0x1ce
github.com/spf13/cobra.(*Command).execute(0xc0003c7680, {0xc00017f600, 0x2, 0x2})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0006aac80)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/gohugoio/hugo/commands.Execute({0xc00003c090, 0x3, 0x3})
        github.com/gohugoio/hugo/commands/hugo.go:92 +0xb4
main.main()
        github.com/gohugoio/hugo/main.go:23 +0x58
```

**Comment by jmooring** [comment]
First, the panic is new in v0.92.2. In v0.92.1 and earlier, your configuration produced:

>Error: add site dependencies: create deps: 1 error(s) decoding:
>
> * cannot parse 'Highlight.LineNos' as bool: strconv.ParseBool: parsing "table": invalid syntax

Second, your configuration is invalid. In site configuration `markup.highlight.lineNos` is a boolean value. To enable line numbers and render the code in a table:

```toml
[markup.highlight]
lineNos = true
lineNumbersInTable = true
```

To enable line numbers and render them inline:

```toml
[markup.highlight]
lineNos = true
lineNumbersInTable = false
```

When using the highlight function in a template, the highlight shortcode in your markdown, or code fences in your markdown, you can use the short hand notation:

>**lineNos=inline**
>equivalent to `lineNos=true `and `lineNumbersInTable=false`
>
>**lineNos=table**
equivalent to `lineNos=true` and `lineNumbersInTable=true`

**Comment by jmooring** [comment]
Bisection indicates problem was introduced with a2a660ed1209528b075a21af84fc0ed3e7b266ef.

**Comment by kbyyd24** [comment]
Thank you @jmooring .

I think I misunderstood the document of [highlight shortcode](https://gohugo.io/content-management/syntax-highlighting/#highlight-shortcode), the `lineNos` in shortcode is different with [highlight config](https://gohugo.io/getting-started/configuration-markup#highlight).

**Comment by jmooring** [comment]
@kbyyd24 I am re-opening this because the panic is a regression in a2a660e.

**Comment by kbyyd24** [comment]
> @kbyyd24 I am re-opening this because the panic is a regression in https://github.com/gohugoio/hugo/commit/a2a660ed1209528b075a21af84fc0ed3e7b266ef.

Ok, np~
