### ISSUE TITLE
Fix or optimize issues workflow script

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#9522]
The workflow script for issues is suboptimal. I can say that without "probably" because the behaviour I am experiencing is, that every day in the morning (UTC+7) exactly 100 issues get locked/marked stale by the bot. Not more or less. This points to some form of limit. I was thinking to let it run its course and that the bot might someday be finished with all legacy issues, but then again, this is going on for weeks now. I think there might be a deeper issue.

Proposal 1: add manually workflow definition so the workflow can be run manually (if the issues touched per workflow run are limited somehow)

Proposal 2: optmise the setup:
```
          issue-inactive-days: 7
```
In my opinion, this is the culprit, because the note of the bot that this issue is stale is an activity and this basically leaves us with 700 issues max before an already stale issue is admonished again. Set this to either something higher (30) or in combination with Proposal 3 to something like 10 or even higher

Proposal 3: close issues that are stale.
```
          days-before-issue-stale: 600
          days-before-pr-stale: 200
          days-before-issue-close: -1
          days-before-pr-close: -1
```
This lets the bot NEVER close issues that are stale, which leads to the weird behaviour described above. Let's set that to 7, so those issues can be closed. Also, the issue-stale and pr-stale days look very large to me. An issue is marked inactive after 7 days, but stale after 600 days?

Worst case scenario is that "disgruntled" developers and issue openers will complain about "their" issue being closed, but we can always say, that this is a hygienic way to keep the project management clean. 

I somehow feel like the overall setup should be along the lines of something like this:

```
issue-inactive-days: x days
days-before-issue-stale: x + 1/2 x days
days-before-issue-close: 1/2 x - 1 days
```

Sample: An issue is inactive after 30 days, stale after 45 and gets closed on day 59 or 60.

**Comment by bep** [comment]
Yea, I have probably missed a lots of real notifications because of this ... I just assumed that it was going to end one day.

**Comment by jmooring** [comment]
@davidsneighbour 

> every day in the morning (UTC+7) exactly 100 issues get locked/marked stale by the bot.

At this point the legacy issues have been processed by the updated workflow.

Is it OK to close this issue now?
