### ISSUE TITLE
Bug with linking to markdown filenames containing a period

### ISSUE THREAD

**Issue by egonelbre** [gohugoio/hugo#9534]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.92.2-90B0222A windows/amd64 BuildDate=2022-02-16T12:08:50+0200
</pre>

### Does this issue reproduce with the latest release?

Yes.

---

When using a such as `describe-config.yaml.md`, then the links to that file does not work.

`content/_index.md`:
```
[Link](describe-config.yaml.md)
```

`content/describe-config.yaml.md`:
```
Hello
```

This will create a link `<a href="describe-config.yaml.md">Link</a>` instead of `<a href="describe-config.yaml">Link</a>`.

**Comment by bep** [comment]
I don't think we're going to "fix this". The "." delimiter should be considered to be reserved to delimit the identifiers (extension, language), so I suggest that you rename your file.

**Comment by egonelbre** [comment]
AFAIU, the code seems to handle the extension as everything after the last period. To me the behavior seems inconsistent in that case.

For example, in this case the "describe-config.yaml.md" shouldn't be rendered due to invalid extension.

**Comment by egonelbre** [comment]
Ah, ok, gotcha, now I understand. It ends up conflicting with `example.en.md` and similar.
