### ISSUE TITLE
can't use  title that included '%2b'

### ISSUE THREAD

**Issue by notqualia** [gohugoio/hugo#9535]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.92.1+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes

i create a new post
hugo new post/xxxx%2bxxx.md
hugo -D
then i enter the site,click the title,got a url 
http://localhost:44113/post/xxxx+xxx and 404
wish got a way to use % in title and not cause 404

**Comment by jmooring** [comment]
If you do this:

```
hugo new post/xxxx+xxx.md
```

You can access the page with:

```
http://localhost:1313/post/xxxx+xxx/

OR

http://localhost:1313/post/xxxx%2bxxx/
```

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
