### ISSUE TITLE
`.Paginator` still uses `.URL`

### ISSUE THREAD

**Issue by pacollins** [gohugoio/hugo#9536]
Was getting an error saying `.URL` was deprecated for `.NextInSection`, so I adjusted all of the `.URL` in my page to page navigation but resulted in an error that `.Paginator.Next` does not accept `.Permalink`.

Maybe this is by design in some way, but it seems like an inconsistency that would be worthwhile adjusting.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.89.1
</pre>

### Does this issue reproduce with the latest release?

Not tested, but the docs seems to suggest that it is consistent.

**Comment by jmooring** [comment]
`.URL` has been deprecated as a method on .Page. It has _not_ been deprecated in the context of menus or pagination.

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
