### ISSUE TITLE
Provide a way for Hugo modules to load a specific branch from a repo

### ISSUE THREAD

**Issue by rootwork** [gohugoio/hugo#9541]
As far as I can tell from the Hugo modules [config docs](https://gohugo.io/hugo-modules/use-modules/#get-a-specific-version) and [CLI docs](https://gohugo.io/commands/hugo_mod_get/), while there is a way to load a specific version of a module, there's no way to load a specific branch from a repo.

This would be really useful for local testing. I know that [`replace` directives](https://gohugo.io/hugo-modules/use-modules/#make-and-test-changes-in-a-module) and [`replacements` options](https://gohugo.io/hugo-modules/configuration/#module-config-top-level) exist but if, for instance, you're testing _someone else's_ work you'd first have to clone their branch locally to do that. Being able to load a module by its repo's branch would be faster.

**Comment by jmooring** [comment]
Here's an example of getting a particular branch:

```
hugo mod get github.com/jmooring/hugo-content@create-article-4
```

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
