### ISSUE TITLE
Add page.Store (a page.Scratch variant)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9546]
We currently have a `page.Scratch` as a _scratch pad_ for each page. 

This gets reset on server rebuilds, and that's not something we can/want change.

This has the unfortunate side effect that scratch values written to page in, say, a shortcode, is not visible on server rebuilds (unless the content is also rebuilt).

I have thought a fair amount on the above, and have concluded that the easiest is just to add a new method:

```go
type ScratchProvider interface {
	// Scratch returns a Scratch that can be used to store temporary state.
	// Note that this Scratch gets reset on server rebuilds. See Store() for a variant that survives.
	Scratch() *maps.Scratch

	// Store returns a Scratch that can be used to store temporary state.
	// In contrast to Scratch(), this Scratch is not reset on server rebuilds.
	Store() *maps.Scratch
}
```

/cc @jmooring @regisphilibert

**Comment by regisphilibert** [comment]
It's an edge case for me, so I'm not sure I can really help other than with naming.

But I wonder if this new method could be safe to reuse throughout the build. This would allow user to safely attach some information to a page and rely on it from any templates and through the rest of the build... See it as a way to complement a page, before in a near future we are able to __create__ a page from data.

This is an addition I'd be excited about, but I suppose it relies on one ability to store this data at the earliest time in the build...
