### ISSUE TITLE
Improve Ordinal usage with lineAnchors in codeblock render hooks

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9567]
Related to using the .Ordinal in the lineAnchors value when anchorLineNos is true...

1. Is this supposed to happen automatically? If so, under what conditions? I can't make it happen.
2. I see [this code](https://github.com/gohugoio/hugo/blob/master/markup/highlight/highlight.go#L153-L156), but I don't think the containing function is ever called.
3. Although an HTML5 id attribute may begin with a number, to be compatible with CSS/JS selectors it should not begin with a number (see https://github.com/gohugoio/hugo/issues/8997). Perhaps we can prepend the .Ordinal with hugo-hl- or hl-.

**Comment by bep** [comment]
You are right, the `Ordinal` is there and ready to use, but it's not in use in the default codeblock renderer, but it should. And you are right, we should prepend something.
