### ISSUE TITLE
Improve attribute vs options in new code blocks setup

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9571]
Me and @jmooring had a discussion about "namespacing" for the code language to distinguish between Chroma lexers/languages and custom code hooks. I suggest we let this be up to the user. Partly because GitHub seems to have chosen a flat namespace for this (e.g `mermaid` diagrams), secondly, it adds complexity that we need to explain to people and removes potential flexibility.

But ...

I think we should improve the attribute handling a little. Currently, we have a set of reserved options that we put in a separate map (`.Options`), see below. But some of them are rather generic (e.g. `style`) and may be likely to be used by "custom hooks".

So what I suggest would be to:

1. Check if `language` is a known Chroma lexer.
2. If yes, put the reserved attributes in `.Options`.
3. Else, put all in `.Attributes`.

```go
// Markdown attributes used as options by the Chroma highlighter.
var chromaHightlightProcessingAttributes = map[string]bool{
	"anchorLineNos":      true,
	"guessSyntax":        true,
	"hl_Lines":           true,
	"lineAnchors":        true,
	"lineNos":            true,
	"lineNoStart":        true,
	"lineNumbersInTable": true,
	"noClasses":          true,
	"nohl":               true,
	"style":              true,
	"tabWidth":           true,
}

```

**Comment by jmooring** [comment]
_For future reference only. I am not suggesting that we change anything._

The namespace train left the station a long time ago. Yet another seven-year [CommonMark discussion](<https://talk.commonmark.org/t/mermaid-generation-of-diagrams-and-flowcharts-from-text-in-a-similar-manner-as-markdown/1882>) lingered without resolution. Others took the lead, so we have a de facto standard as implemented by:
- [GitLab](https://docs.gitlab.com/ee/user/markdown.html#diagrams-and-flowcharts) in 2017
- [Gitea](https://gitea.io/) in 2020
- [JetBrains](https://www.jetbrains.com/help/idea/markdown.html#diagrams) in 2020
- [GitHub](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) in 2022
- This [Microsoft Visual Studio Code Extension](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) in 2017
- And others...

**Comment by jmooring** [comment]
@bep Can you please hold off on this change for 24 hours?

**Comment by bep** [comment]
Yea, I can even wait until Monday ...

**Comment by bep** [comment]
I have a few other things to get into the next Hugo release (which will be surprisingly useful), which would be likely to be done thursdayish ...

**Comment by jmooring** [comment]
Please proceed with this. Without this change things become a bit more difficult. Thanks.
