### ISSUE TITLE
Expose .ChromaLexer (or boolean) within the codeblock render hook template

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9573]
With a generic hook (render-codeblock.html), it would helpful to know if `.Lang` is a known Chroma lexer. We could return the lexer used (or nil) , or a boolean. 

Something like...

```
{{ if .KnownChromaLexer }}
  {{ $r := transform.HighlightCodeBlock . }}
  {{ $r.Body }}
{{ else }}
  my stuff
{{ end }}
```

**Comment by bep** [comment]
How about `IsChroma`?

OK, looking back at `transform.HighlightCodeBlock` is also suspect we also need to adjust that a little. I notice that the returned struct has a `Body` and a `Highlighted` method that currently just returns `Body`. With this it's not possible, I think, for a user to render its own `<div>`, so I suggest we:

1. Let `Body` be ... the inner parts.
2. Let `Highlighted` return the full `<div>` with HTML attributes.

**Comment by bep** [comment]
Not that we will ever replace Chroma as the highlighter of choice, but how about `CanHighlight`, meaning "Chroma has a lexer for this language".

**Comment by jmooring** [comment]
I want to clarify this statement:

> Within the render hook we "can highlight" anything we want

This example has come up at least once, either here or on the forum. The user wants to highlight log files, and found that the best available lexer is for `ini` files.

````
```log 
2022-02-26T09:37:26-08:00 Backup started
2022-02-26T09:38:31-08:00 Backup failed: unable to connect to 93.184.216.34
```
````

Chroma does not have a `log` lexer, for obvious reasons, but the string inside the code fences _can_ be highlighted. As I write the code to handle this, I run into a problem:

```
{{ $lang := .Lang }}
{{ if eq $lang "log" }}
  {{ $lang = "ini" }}
{{ end }}
{{ if $lang | hasLexer }} <-- I think this would need to be a function
  ...
{{ end }}
```
