### ISSUE TITLE
Internal template render-codeblock-mermaid is not available

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9576]
Testing with 5f65c17a12213cedbc8cf1348bbf0d98335e4cfb

The layouts/_default/_markup directory is present but empty.

baseof.html contains

```
<head>
  ...
  {{ if .Store.Get "hasMermaid" }}
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
  {{ end }}
</head>
```

markdown

````
```mermaid
gantt
  title A Gantt Diagram
  dateFormat  YYYY-MM-DD
  section Section
  A task           :a1, 2014-01-01, 30d
  Another task     :after a1, 20d
  section Another
  Task in sec      :2014-01-12, 12d
  another task     :24d
```
````

Rendered as:

```html
<pre tabindex="0"><code class="language-mermaid" data-lang="mermaid">gantt
  title A Gantt Diagram
  dateFormat  YYYY-MM-DD
  section Section
  A task           :a1, 2014-01-01, 30d
  Another task     :after a1, 20d
  section Another
  Task in sec      :2014-01-12, 12d
  another task     :24d
</code></pre>
```

I cannot view the chart.

I _can_ view the chart if I copy the [internal template](https://raw.githubusercontent.com/gohugoio/hugo/master/docs/layouts/_default/_markup/render-codeblock-mermaid.html) to `layouts/_default/_markup/render-codeblock-mermaid.html`.

**Comment by bep** [comment]
There is no such thing as an internal Mermaid template. I thought about adding it, but the current situation requires the user to do some extra work (include a script at the bottom).

We may add this in the future, but not now.
