### ISSUE TITLE
HTML lang attribute missing: Add <html lang=""> to META redirect pages (aliases)

### ISSUE THREAD

**Issue by dw-andrewsfasteners** [gohugoio/hugo#9586]
Some SEO tools reporting missing `<html lang="">` on meta redirect pages related to `aliases` in markdown files. Can we get this added, please? (with relevant reference to `{{ .Site.LanguageCode }}`)

Example:
```
<!doctype HTML>
<HTML>
<head>
<title>https://example.com/alias-link/</title>
<link rel=canonical href=https://example.com/correct-link/>
<meta name=robots content="noindex">
<meta charset=utf-8>
<meta http-equiv=refresh content="0; url=https://example.com/alias-link/">
</head>
</html>
```

**Comment by davidsneighbour** [comment]
Just for posterities sake, this should NOT be added to Hugo. See https://discourse.gohugo.io/t/add-html-lang-to-meta-redirect-pages-layout-alias-html/37433/ for argumentation.

**Comment by jmooring** [comment]
I see no harm in making this change, and am in favor of generating HTML that does not throw validation errors.

**Comment by bep** [comment]
>that does not throw validation warnings or errors.

Me too (unless there is a great reason not to).

We have a little bit ambiguous "language code" at the moment, so I would suspect we do:

`{{ site.LanguageCode | default site.Language.Lang }}`
