### ISSUE TITLE
Attributes with underscore in code block render hooks

### ISSUE THREAD

**Issue by jyniybinc** [gohugoio/hugo#9590]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.93.0-07469082+extended linux/amd64 BuildDate=2022-02-28T08:30:42Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

### Description
It seems attributes with underscore (`_`) are ignored. I am trying to implement `hl_lines` and it does not appear when I print `.Attributes`.

**Comment by pamubay** [comment]
All Chroma options accessible via `.Options`
