### ISSUE TITLE
`alt` text in images does not escape any double quotes

### ISSUE THREAD

**Issue by jamietanna** [gohugoio/hugo#9594]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

hugo v0.92.2+extended linux/amd64 BuildDate=unknown

</pre>

### Does this issue reproduce with the latest release?

Yes

### Issue

For the given Markdown:

```markdown
![Referrer breakdown to "Search Engines", "Direct Entry" and "Websites"](https://media.jvt.me/94fec39807.png)
```

The following HTML is rendered:

```html
<p><img src="https://media.jvt.me/94fec39807.png" alt="Referrer breakdown to "Search Engines", "Direct Entry" and "Websites""></p>
```

But note that the quotes are not escaped, which trips up some HTML parsers.

**Comment by bep** [comment]
Is this the default renderer? No image render hook used?

**Comment by davidsneighbour** [comment]
Seems like it, I have no render hooks and a copy paste did exactly that. 

![20220302-21:03:37_Selection_001](https://user-images.githubusercontent.com/83281/156376546-6d1dd188-b154-43d9-88a3-c5a9cbb6618d.png)

**Comment by jamietanna** [comment]
OK, so a fresh site does _not_ have this, it's definitely related to the following configuration in my `config.toml`:

```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
    typographer = false
    [markup.goldmark.renderer]
    # allow inline HTML, such as spoiler warnings
    unsafe = true
  [markup.tableOfContents]
  startLevel = 1
  endLevel = 6
  ordered = false
```

**Comment by jamietanna** [comment]
It appears to be related to the `typographer` configuration, as with it set, we see:

```html
<p><img src="https://media.jvt.me/94fec39807.png" alt="Referrer breakdown to &ldquo;Search Engines&rdquo;, &ldquo;Direct Entry&rdquo; and &ldquo;Websites&rdquo;"></p>
```

**Comment by davidsneighbour** [comment]
my markup config:

```
################################################################################
# see https://github.com/yuin/goldmark/#built-in-extensions
# see https://gohugo.io/getting-started/configuration-markup#goldmark
################################################################################
[goldmark]

[goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[goldmark.parser]
attribute = true
autoHeadingID = true
autoHeadingIDType = "github"

[goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false

[highlight]
anchorLineNos = true
codeFences = true
guessSyntax = true
lineAnchors = "code"
lineNos = true
lineNumbersInTable = true
noClasses = false
tabWidth = 2
style = "xcode"

[tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
```

My typographer is true.

**Comment by jamietanna** [comment]
This is what I'm testing with:

<details>

<summary><code>content/posts/hello.md</code></summary>

```markdown
---
title: hi
---

The post

![the "example"](https://media.jvt.me)


![Referrer breakdown to "Search Engines", "Direct Entry" and "Websites"](https://media.jvt.me/94fec39807.png)

another
```

</details>

<details>

<summary><code>layouts/posts/single.html</code></summary>

```html
<article id="content">
  {{ .Content }}
</article>
```

</details>

<details>

<summary><code>config.toml</code></summary>

```toml
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
```

</details>

Which renders:

```html
<article id="content">
  <p>The post</p>
<p><img src="https://media.jvt.me" alt="the &ldquo;example&rdquo;"></p>
<p><img src="https://media.jvt.me/94fec39807.png" alt="Referrer breakdown to &ldquo;Search Engines&rdquo;, &ldquo;Direct Entry&rdquo; and &ldquo;Websites&rdquo;"></p>
<p>another</p>

</article>
```

Note that I don't see a configuration change when I have `[goldmark]` but I do when I have `[markup.goldmark]`.

I'm currently thinking that the `typographer` is what's causing this

**Comment by davidsneighbour** [comment]
I have `[goldmark]` because the configuration is in `config/_default/markup.toml`. In that case it does not require the `markup.` part.
