### ISSUE TITLE
Permalink for OutPutformat incomplete

### ISSUE THREAD

**Issue by bertrandkeller** [gohugoio/hugo#9598]
### What version of Hugo are you using (`hugo version`)?
0.93.0 

Permalink for Output Format seems to be incomplete.

I have output format for content in a Section (audits).

content/audits 
 -> Project-1
 -> Project-2
 -> Project-3

Permalinks are all the same with `audits/baseName.html` where as it should be `audits/Project-1/baseName.html`

**Comment by bep** [comment]
This is by design, thinking that in most cases you have a cannonical output format (e.g. HTML), but you can override this behaviour per output format, set `permalinkable=true`, see:

https://gohugo.io/templates/output-formats/#configure-output-formats

**Comment by bertrandkeller** [comment]
`permalinkable=true` is setted, it was working before the 0.93.0.
I found a workaround. But it could be bugged.

**Comment by bertrandkeller** [comment]
I have to reproduce the bug with different versions of Hugo and I write you a comment if I have more information.

**Comment by bep** [comment]
Thanks, the best would be a link the failing site.

**Comment by bertrandkeller** [comment]
Test between 0.92 and 0.93.3

Permalink seems normal.
