### ISSUE TITLE
Regression: readDir now reads inside of theme directory

### ISSUE THREAD

**Issue by stefanv** [gohugoio/hugo#9599]
There seems to be a change in the search base paths used by `readDir` between `hugo v0.92.2-CDF6A0D6` and `hugo v0.93.1-E9669FED`.

When I compare the outputs of `readDir .`, I observe that with the latest version `readDir` returns results from **both** `.` and `themes/my-theme`, whereas the old version only read from `.`.

**Comment by stefanv** [comment]
My take was that Resources would be the correct way to find files across theme and project, but that readDir would be very explicit in where it reads.

It's ironic, because looking at our readDir-using code (which led me to spot this change), it's clear that what we should be using resources instead.

**Comment by bep** [comment]
>My take was that Resources would be the correct way to find files across theme and project,

That is one take, but any folder below `/assets` is only a _composite_ if you make it so; if you put files in `/assets/nothemesfileshereplease` you should be safe.

**Comment by bep** [comment]
I'm going to fix this particular issue by reverting to the old behaviour; also see #9604
