### ISSUE TITLE
Add environment (e.g. production) as a new filter to _cascade.target

### ISSUE THREAD

**Issue by mrusme** [gohugoio/hugo#9612]
Hey there,

After looking this up and [confirming](https://discourse.gohugo.io/t/skipping-page-building-depending-on-environment-config/37502) this was not possible (thanks again @jmooring!) I would like to propose a feature, that works similar to the `draft` keyword, but allows specifying the environment(s) for which pages/posts shall be built for. Specifically, I suggest adding an `environment` keyword, which would accept a list of values:

```yaml
environment:
  - production
  - staging
  - development
```

This would allow for per-page/-post management of individual pages/posts, in which individual teams work on parts of a large Hugo deployment, in which none of them (but one admin-team) have access to the actual environment configuration files. Through a keyword inside the pages/posts, teams could individually decide to which environments pages/posts would get deployed to, without having the admin-team involved for adjusting the `cascade._target` configuration.

I would appreciate thoughts on this! Thank you.

**Comment by bep** [comment]
Yes, something like this would certainly be useful. I don't think, however, that we would want to add some other `draft` type of _thing_ (Hugo already has enough buttons ...).

I'm thinking out loud here, but what if we did:

```bash
[[cascade]]
[cascade._build]
list = false
render = false
[cascade._target]
 environment = '{production,staging}'
```

**Comment by mrusme** [comment]
The way I understood this solution it would require people maintaining pages to also get access to the environment configuration(s). As mentioned before I ran into multiple situations where it's not easily possible to provide that and where it would make sense to have per post/page configuration.

**Comment by CathrinePaulsen** [comment]
Hi, I would like to try this issue. If I understand correctly, this involves adding environment as a new keyword to the PageMatcher?

**Comment by bep** [comment]
@CathrinePaulsen yes, I think that would be the simplest approach. We may want to refactor this at some point, but for now I suggest  you just get the environment from `p.Site().Hugo().Environ()` (or something). There should be some tests that you can expand upon.
