### ISSUE TITLE
Support global partialCached

### ISSUE THREAD

**Issue by doompadee** [gohugoio/hugo#9616]
I have a relatively costly partial that I want to cache once per site.

{{ $ids := partialCached "func/ids.html" site }}

But no matter what I've tried, I can't get Hugo to execute the partial only once. Metrics show values between 94-98% cached. I assume this is because of parallel execution with different workloads before the cache becomes hot?

Therefore I'd like to propose a feature to be able to deal with this kind of situation to let Hugo know it should wait with further invocations until the first invocation has ended.

Maybe use a different keyword to instruct Hugo to switch strategies?

{{ $ids := partialGlobalCached "func/ids.html" site }}

An alternative might be to provide the global context, but this could be problematic for existing code?

{{ $ids := partialCached "func/ids.html" $ }}

I think it should be relatively easy to employ something like async/await to deal with the parallelism while the first invocation is still running.

**Comment by bep** [comment]
I think it should be relatively easy to employ something like async/await to deal with the parallelism while the first invocation is still running.

You would think so, and I thought so, too. I implemented this in Hugo 0.93.0, applied a fix for it in 0.93.1, then had to revert it in 0.93.2 ... There is at least one open issue about this, so closing this. I have written more about this elsewhere.

**Comment by bep** [comment]
OK, I'll reopen this, I thinking about this, this should be possible if we change the cache to be a `sync.Map`
