### ISSUE TITLE
Refinement of the highlight `hl_inline` option

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#9635]
@bep Thanks for implementing https://github.com/gohugoio/hugo/pull/9634!

Looking at the test in the PR, I believe that the hl_inline attribute won't syntax highlight the code. 

1. We will need an outer `<span class="chroma">` for the default chroma generated stylesheets to work for syntax highlighting. The default chroma generated CSS apply the rules to `.chroma .FOO` classes. So without the outer "chroma" class, that CSS won't work. 
2. The `<span class="line">` needs to be removed (I had mentioned this in https://github.com/gohugoio/hugo/issues/9442#issuecomment-1036277327 just yesterday, so it was missed). The problem is that the default style for `.chroma .line` is `display: flex;`. So if that `"line"` class is retained, the inlined code moves around as the browser viewport resizes!
3. Additionally, it will be good to have a special class like "hl-inline" or "inline" in the outermost span tag so that the user can customize the CSS just for the inline code blocks. 

There's a simple incremental fix if the user is setting `noClasses = false`: 

Replace `<span class="line">` with `<span class="chroma inline">` somewhere in https://github.com/bep/hugo/blob/1a991e5b2bc3207c99b87d60ca54340d61763468/markup/highlight/highlight.go#L71 maybe?

That will resolve all of the above points. 

---

~Though, I am not sure how this will behave when the user configures `noClasses = true`.  I'll need to test out that case.~

I have tested `noClasses = true` and that works **only if** we remove Chroma injected `display:flex;` style. Details in https://github.com/gohugoio/hugo/issues/9635#issuecomment-1062998742.

**Comment by bep** [comment]
Hmm...

**Comment by kaushalmodi** [comment]
I also realized that when `cfg.Hl_inline` is `true`,  `cfg.LineNos` will need to be overridden to `false` regardless of the user's default linenos config in the site config.toml.

**Comment by kaushalmodi** [comment]
## Testing with `noClasses = true` (inline CSS styling)

## Testing with `highlight` shortcode with `hl_inline=true`

It does not work because the default `display: flex;` messes up the "inline-ness".

### Markdown
```md
something {{< highlight emacs "hl_inline=true" >}}(message
"this highlight shortcode"){{</highlight>}} something
```

### Rendering

![image](https://user-images.githubusercontent.com/3578197/157462280-76c5615a-5442-43a5-83a3-c369e8f16e7f.png)

## Testing with a custom shortcode that removes `display:flex;`

### `hl_inline` shortcode

```html
{{- (highlight .Inner (.Get 0) "hl_inline=true")
     | replaceRE ` style\s*=\s*"display:\s*flex;?\s*"` ``
     | safeHTML -}}
```

### Markdown
```md
something {{< hl_inline emacs >}}(message "this highlight
shortcode"){{< /hl_inline >}} something
```

### Rendering

![image](https://user-images.githubusercontent.com/3578197/157463274-01f0a204-c541-4ab6-be0e-dc06d037cbe2.png)

---

## Testing with `noClasses = false` (CSS styling using `.chroma` classes)

## Testing with `highlight` shortcode with `hl_inline=true`

It does not work because inline code is not wrapped in `chroma` class.

### Markdown
```md
something {{< highlight emacs "hl_inline=true" >}}(message
"this highlight shortcode"){{</highlight>}} something
```

### Rendering

![image](https://user-images.githubusercontent.com/3578197/157465337-673f081f-1a27-45f0-8737-1059b18338a1.png)

## Testing with a custom shortcode that removes the `line` class and adds `chroma` class

### `hl_inline` shortcode

```html
{{- (highlight .Inner (.Get 0) "hl_inline=true")
     | replaceRE ` style\s*=\s*"display:\s*flex;?\s*"` ``
     | replaceRE `<span class="line">` `<span class="chroma inline-src">`
     | safeHTML -}}
```

### Markdown
```md
something {{< hl_inline emacs >}}(message "this highlight
shortcode"){{< /hl_inline >}} something
```

### Rendering

![image](https://user-images.githubusercontent.com/3578197/157465542-d7f49e72-43c5-4948-be4f-fe8ae7949e2e.png)

**Comment by bep** [comment]
>There's a simple incremental fix if the user is setting noClasses = false:

Hehe.
