### ISSUE TITLE
fileExists seems broken on v0.93.3

### ISSUE THREAD

**Issue by bertrandkeller** [gohugoio/hugo#9636]
Hugo
v0.93.3

I downgraded to 0.92.2 and it work fine. 
I have an error with fileExists with this version. 

I execute a readDir after a condition on a path with fileExists. ReadDir display an error because fileExists is set at true.

**Comment by bep** [comment]
We need more information, the best would be a link the failing site.

**Comment by bertrandkeller** [comment]
The error is simple. The `fileExists` is bypassed and ReadDir fail.

```
ERROR 2022/03/10 16:01:18 render of "page" failed: "/var/folders/yg/nkrj2pj541s6p509c1bmqcsw0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/disic/frago@v1.4.0/layouts/_default/baseof.html:65:11": execute of template failed: template: accessibility/single.html:65:11: executing "accessibility/single.html" at <readDir "/static/assets/css">: error calling readDir: failed to read directory "/static/assets/css": open /Users/…/dinum/dsn-audits/dila/static/assets/css: no such file or directory
```

```
{{ if (fileExists "/static/assets/css") }}
  {{ range readDir "/static/assets/css" }}{{ if ne .Name "fonts.css" }}
  <link rel="stylesheet" href="{{ $.Site.BaseURL | default "/" }}assets/css/{{ .Name }}" media="print" onload="this.media='all'" />
  <noscript>
    <link rel="stylesheet" href="{{ $.Site.BaseURL | default "/" }}assets/css/{{ .Name }}" media="screen">
  </noscript>
  {{ end }}
 {{ end }}

{{ end }}
```

**Comment by bertrandkeller** [comment]
Small precision,

`assets/css` exists in the assets folder. But no in the `static/assets/css`.

Maybe `fileExists` say there is something in static from `assets/css` where as readDir says their is nothing in `static/assets/css`.

The code is present for overriding the theme with `static` element.

**Comment by jmooring** [comment]
I am not able to reproduce the problem, nor am I able to guess how you have structured or configured your project.

Please provide a link your project repository. If you can’t share your repository for whatever reason, create a dummy repo that you *can* share, which reproduces the problem you’re experiencing.

Please help _us_ to help _you_. Thanks.

**Comment by bertrandkeller** [comment]
I don't no if it is easy to configure : 
https://github.com/DISIC/frago/
_There is an exampleSite_

**Comment by bertrandkeller** [comment]
Actually, 

`static/assets/css` is coming from the theme. And not from the main repo.

In 0.92, `static/assets/css` it is readFile, in 0.93 and after Not.
In 0.92, `static/assets/css` FileExists, in 0.93 and after FileExists too.

**Comment by gauntface** [comment]
I've just tried building my site on Fedora with `hugo v0.93.3+extended linux/amd64 BuildDate=unknown` and running into this issue as well. Previously `fileExists "/assets"` would return false and now returning true resulting in a readDir error.

Downgrading on Fedora (`sudo dnf downgrade hugo`) installs `Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: unknown` results in fileExists returning false.

Repro case is here: https://github.com/gauntface/gaunt.dev

**Comment by gauntface** [comment]
It looks like in the newer versions of hugo it will look for directories nested (i.e. not at the root of the project).

This repo reproduces the change in behavior: https://github.com/gauntface/hugo-file-exists-test

**Comment by gauntface** [comment]
NOTE: The `assets` directory in the repro is in the `themes/example/` directory, not the content directory.

It looks like the docs were updated to explain that os.FileExists and os.Stat methods will try to find the directory/file, so it seems like it's not possible to reliably look for files in specific locations.
