### ISSUE TITLE
hugo server -D works but hugo server --disableFastRender breaks navbar

### ISSUE THREAD

**Issue by deput-d** [gohugoio/hugo#9645]
Hello I am testing a simple bootstrap theme and ran into an issue.

I am running Ubuntu 20 under WSL and installed hugo using the following deb:
- https://github.com/gohugoio/hugo/releases/download/v0.94.0/hugo_0.94.0_Linux-64bit.deb

While I am testing the site with `hugo server -D`, it works, but when using `hugo server --disableFastRender`, it breaks the navbar's dropdown.

Is there no longer a way to refresh the build when changes are detected? It appears --disableFastRender is no longer working like it used to on previous versions. I noticed the quickstart documentation no longer recommends it as well. Please advise.

**Comment by deput-d** [comment]
This is an issue with WSL & file permissions, not hugo. If I find a fix I will update, but wsl has been nothing but a headache. Any recommendations are apprecaited.

**Comment by deput-d** [comment]
works with extended version:
- https://github.com/gohugoio/hugo/releases/download/v0.94.0/hugo_extended_0.94.0_Linux-64bit.deb

**Comment by deput-d** [comment]
works with extended version:
- https://github.com/gohugoio/hugo/releases/download/v0.94.0/hugo_extended_0.94.0_Linux-64bit.deb

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by deput-d** [comment]
Thanks. This is a verified issue in this environment you could easily re-create in a matter of minutes. 

I will update if I find a workaround by installing Hugo on windows instead of the Linux subsystem.
