### ISSUE TITLE
Include HTTP requests in log output

### ISSUE THREAD

**Issue by marshall007** [gohugoio/hugo#9646]
Remote HTTP requests are not logged even with `--verbose --verboseLog` enabled. In my experience, calls to functions like `getJSON` and `resources.GetRemote` are one of the most likely things you get wrong during development. They are also the most likely cause for slow builds. It would be great if we could get visibility on these request.

I propose that we log all HTTP requests (perhaps even including local `resources.Get` as well) and at minimum display the following:

- HTTP method
- URL
- status
- content length
- content type

In fact I think there's a good argument to be made that such output should be included by default and `--verbose` should include a pretty-printed response body (at least for content types that make sense llike JSON).

I also think we should include aggregate information in the build output:

```diff
                   | EN  
 ------------------+-----
  Pages            | 83  
  Paginator pages  |  0  
  Non-page files   | 22  
  Static files     |  1  
  Processed images |  4  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0

+          | Avg Time
+ ---------+---------
+ 200  | 5 | 526ms
+ 500  | 1 | 3.67s
```

As an aside I cannot tell what `--verboseLog` is intended to do vs `--verbose`.

**Comment by bep** [comment]
>In fact I think there's a good argument to be made that such output should be included by default and --verbose should include a pretty-printed response body (at least for content types that make sense llike JSON).

What is that good argument?

**Comment by marshall007** [comment]
@bep I believe this is answered by the issue description:

> In my experience, calls to functions like `getJSON` and `resources.GetRemote` are one of the most likely things you get wrong during development. They are also the most likely cause for slow builds. It would be great if we could get visibility on these request.

Even if you don't buy into logging requests by default, I think logging HTTP request metadata as `INFO` and response bodies as `DEBUG` would be fairly uncontroversial. I'm not aware of a way to control the granularity of what is included in the log, but if that's already possible then there's probably no reason to include HTTP requests by default.

It's difficult to get this today. If you want to debug an HTTP request you basically have to write it out to the page AFAIK. This is not always easy especially if you have abstractions in the form of partials in place that return HTTP responses instead of rendering content. There are no helper functions that allow you to write to the log.

**Comment by marshall007** [comment]
Related to #9667
