### ISSUE TITLE
 'hugo server --renderStaticToDisk' failing in windows

### ISSUE THREAD

**Issue by mgenge254** [gohugoio/hugo#9647]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo env
hugo v0.94.0-63B23660+extended windows/amd64 BuildDate=2022-03-10T09:46:36Z VendorInfo=gohugoio
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.17.6"
</pre>

### Does this issue reproduce with the latest release?
Yes, see below.
```
$ hugo server --renderStaticToDisk
Error: add site dependencies: create deps: create PathSpec: mkdir C:\Users\Site\public\: file does not exist
```

**Comment by bep** [comment]
I have spent some time this morning looking into this, and yes, it fails on Windows, but I don't see a simple fix, so I think I need to revert it for now.

The core gist of it is that we use Afero's `CopyOnWriteFs` as the `Destination`, which should cover both the serving and publishing; this works on MacOs, at least, but on Windows it seem to try to propagate writes (MkDirs) up to the readable layer. I'm not sure I got the details here right, but this at least need a closer look.

I will push som better server tests so we can avoid this in the future.
