### ISSUE TITLE
Remove the file logging flags (log, logFile, verboseLog)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9648]
Also the `debug` flag, which isn't useful.

These have been there since the early days, and I'm not even sure they work. If people want to log to file, they need to pipe the output.

**Comment by davidsneighbour** [comment]
They work(ed). Not really an enhancement if those features are gone ;) But piping is ok I guess. Does Hugo use STDERR and STDOUT or only STDOUT? That seems to be of help in deciding how to pipe in Bash.

**Comment by davidsneighbour** [comment]
I am back, please re-consider. Running hugo for instance via `npm-run-all` will result in piping of Hugo-only output to be impossible. I have a case where I run multiple scripts/apps/servers in parallel with one command. Doing that with removed logging options will have a lot of output in that piped file and there is no indicator which lines are by Hugo.
