### ISSUE TITLE
Enhance hugo list to report posts from a single section

### ISSUE THREAD

**Issue by jgreely** [gohugoio/hugo#9661]
I often find myself using `hugo list` to extract per-section metadata ("list all the future posts in the sidebar miniblog section"), but this requires scanning the entire site and discarding 99% of the output, which wastes a lot of time when you have 10,000+ posts.

I propose adding an optional second argument to `hugo list` that restricts the search to a single section or subsection:

```
hugo list all|drafts|expired|future [section]

# show only recipes from the mcarchive site
hugo list all mcarchive
# show only draft cheesecake recipes
hugo list drafts mcarchive/cheesecakes
```

**Comment by jmooring** [comment]
Seems like this would be sufficient...

```bash
hugo list all | grep "foo"
```

**Comment by jgreely** [comment]
> Seems like this would be sufficient...

If you don't care how long it takes to extract 100 lines from 10,000+, yes.

**Comment by jmooring** [comment]
Maybe I'm missing something. I have a text file with 10,000 lines.

```
$time cat junk.txt | grep turtle

real	0m0.053s
user	0m0.002s
sys	0m0.031s
```

**Comment by jgreely** [comment]
My example is about running `hugo list all` with 10,000 _posts_, not running `cat foo` with 10,000 _lines_.

**Comment by jmooring** [comment]
Try this:

```
git clone --single-branch -b hugo-github-issue-8602 https://github.com/jmooring/hugo-testing hugo-github-issue-8602
cd hugo-github-issue-8602
hugo list all | grep "90-pages"
```

The site has over 10,000 pages. The "90-pages" section has... 90 pages.

It's less than a second to grep.

**Comment by jgreely** [comment]
Congratulations on your fast SSD.

**Comment by jgreely** [comment]
Small Amazon EC2 instance:

```
% find content -type f -name \*.md | wc -l
9609

% time hugo list all > /tmp/jfoo

real	0m6.877s
user	0m2.140s
sys	0m0.507s
```

**Comment by jmooring** [comment]
I'm not sure how Hugo can help with that.

With the test repository noted above, I changed all the content in one section to `draft = true`, then compared the results.

```bash
$ time hugo list drafts

real	0m1.759s
user	0m1.318s
sys	0m0.317s
```

```bash
$  time hugo list all | grep "10-pages"

real	0m1.755s
user	0m1.298s
sys	0m0.333s
```

The times were essentially the same.
This is on an AWS t2.micro instance.
