### ISSUE TITLE
Make WARN about no layout file an ERR

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [gohugoio/hugo#9668]
I got this warning.

`WARN 2022/03/13 16:56:42 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.`

I see no reason why this is a warning. It is IMHO an error because some of my content is not translated by hugo into html. So if hugo is not able to make it's job it is an error not a warning.

Maybe this is to much for default behavior but I would like to have a FATAL and a break at the point where problems like this arise.

**Comment by bep** [comment]
This has been discussed in length before, and we concluded that the current behaviour is the best one. Also, changing it now would be a big breaking change that I'm not prepared to work overtime for.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Can you reference the past discussion please? This would help me the decisions behind that.
