### ISSUE TITLE
Break up when there is no theme

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [gohugoio/hugo#9669]
Do not let hugo run when there is no theme.
IMHO this is a fatal error which should stop every other steps.

If there are use-cases where there is a good reason for running hugo without a theme then make that use-cases optional; e.g. via `--allow-no-theme`.

Maybe related: #9667

**Comment by bep** [comment]
Running Hugo without a theme is very common, so that is not something we can or will change.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
But it does not work out of the box (in my case).
