### ISSUE TITLE
dartsass: Support @debug, @warn etc. 

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9683]
See https://github.com/bep/godartsass/issues/6

**Comment by davidsneighbour** [comment]
Please include @error in this. I think it would be useful to stop processing at that point and dartsass would do that. If you think devs should not be able to "break out" of the stylesheet creation (I wouldn't understand what is going on under the hood there) then maybe "catch" an @error and output something along the lines of "@error encountered but ignored". 

A good use case for these features is in my opinion the opportunity for me as theme developer to let the user know that his selection of colors for instance is ok, but might result in bad contrasts. Or tell them that a variable is not set that could make their life better and what defaults are used. Makes sense somehow.

**Comment by bep** [comment]
@error is already handled (it fails the build). There particular issue is about _logging_, and the scope is very narrow.

**Comment by davidsneighbour** [comment]
https://www.sitepoint.com/using-sass-error-warn-and-debug-directives/
