### ISSUE TITLE
REF_NOT_FOUND error not thrown when using an invalid link with a header

### ISSUE THREAD

**Issue by dbrat43** [gohugoio/hugo#9685]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version v0.92.1
</pre>

### Does this issue reproduce with the latest release?
Have not tried because the latest binary is not yet available in my firm

### Issue
When using the relref shortcode in a hyperlink to point at a file in Hugo's filesystem I want to render, hugo will build successfully when a page that does not exist is referenced with a header. I briefly looked through the discourse and did not seem to find any chatter about this issue.

The test cases are listed below:

hugo will build as expected:
`[Some page]({{< relref "../page" >}})`

hugo will not build and will throw an error as expected:
`[Some page]({{< relref "../pa" >}})`

hugo will build despite the page not existing:
`[Some page]({{< relref "../pa#some-header" >}})`

hugo will build despite the header not existing:
`[Some page]({{< relref "../pa#some-h" >}})`

**Comment by jmooring** [comment]
> hugo will build despite the header not existing

The `ref`/`relref` shortcodes and functions resolve to a page, not to an element id (what you refer to as a "header") within the page. See https://github.com/gohugoio/hugo/issues/6863. 

> hugo will build despite the page not existing:

I cannot reproduce this behavior. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by dbrat43** [comment]
Ah ok, makes sense. 

As for the second point, my browser must have been caching the page and thus not showing the error when I would play with the relref path and hugo would reload.
