### ISSUE TITLE
Add support for Go's net/url JoinPath

### ISSUE THREAD

**Issue by mattdeluco** [gohugoio/hugo#9694]
I ran into an issue trying to use `path.Join` to join a path to a Permalink (I'm new to Hugo and Go): `path.Join` uses `filepath.Join` under the hood, which calls `filepath.Clean`. Among other things, `Clean` will remove any consecutive slashes, clobbering `https://` in `.Permalink`, making it for example `https:/example.com/path/to/a/thing`. Go's `path.Join` also does the same thing with its own implementation of `Clean`.

I dug around and found there's a [very recently added](https://github.com/golang/go/issues/47005) (March 9th) `JoinPath` function in `net/url`. I think it may have missed Go 1.18 by 5 days: it would be a convenient addition to Hugo on the next release of Go.

**Comment by bep** [comment]
>path.Join uses filepath.Join under the hood, which calls 

I'm pretty sure the above isn't true, but you are right, we are going to use the new JoinPath, but assuming it's not backported to Go 1.18, I suspect we need to wait until Go 1.20.
