### ISSUE TITLE
GetRemote for partial

### ISSUE THREAD

**Issue by mahdi1dev** [gohugoio/hugo#9699]
Hello
I have a lot of sites built using hugo and the problem is that they all have the same layout.
I need a feature that makes me put partials in one place "like a github repository" and retrieved "using something like resources.GetRemote completely".
for example
```
{{ partial resources.GetRemote "https://github.com/username/repo/raw/main/partials/header" . }}
```

**Comment by bep** [comment]
You could import your common layouts as an Hugo Module, see the docs.

**Comment by mahdi1dev** [comment]
Currently it suffices. But you need to fetch partials and remote codes like resources.GetRemote

**Comment by mahdi1dev** [comment]
> You could import your common layouts as an Hugo Module, see the docs.

Currently it suffices. But you need to fetch partials and remote codes like resources.GetRemote.
