### ISSUE TITLE
resources.GetRemote: Add more detail to `.Err`.

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#9708]
Currently,  the `.Err` method of a `resources.GetRemote` only returns the status error text (`Unauthorized`, `Not Found`, etc...) while preventing access to the response's body.

Many API's will send a JSON body along their erroring response to give more detail on the error. Something like:

```
{
    "errors": [
        {
            "code": "DATE_NOT_RECENT"
        }
    ]
}
```

Currently we cannot have access to the body and this information. Having this would tremendously help debugging HTTP requests.

Maybe:

```
{{ with $result := resources.GetRemote $url }}
  {{ with .Err }}
    {{ warnf "%#v" .Content}} or {{ warnf "%#v" $result.Content }}
  {{ else }}
    {{ with .Content | unmarshal }}
      {{ warnf "%#v" . }}
    {{ end }}
  {{ end }}
{{ end }}
```

**Comment by bep** [comment]
Note that we cannot (or we can, but it isn't practical) return both `.Err´ and `.Content`, but we can add more information to `.Err`. We could/should probably add some generic fields:

```
{{ with $result := resources.GetRemote $url }}
  {{ with .Err }}
    {{ warnf "HTTP Status Code: %d Response Body: %#v" .Status .Content}}
  {{ else }}
    {{ with .Content | unmarshal }}
      {{ warnf "%#v" . }}
    {{ end }}
  {{ end }}
{{ end }}
```
