### ISSUE TITLE
Custom heading markdown render hook not reflected in .TableOfContents

### ISSUE THREAD

**Issue by doompadee** [gohugoio/hugo#9721]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.94.0-63B23660+extended linux/amd64 BuildDate=2022-03-10T09:46:36Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

In order to address a problem with duplicated heading ids with custom pagination, I'm using a custom markdown render hook for headings. But then I run into an issue with the provided table of contents: it does not pick up the custom heading ids and the links don't work!

```
<nav id="TableOfContents">
  <ul>
    <li><a href="#lâcher-prise">Lâcher prise</a></li>
  </ul>
</nav>


<h1 id="MYceremonies">Cérémonies</h1>

<h2 id="MYlâcher-prise">Lâcher prise</h2>
```

Here is a minimal project for reproduction: [repro.zip](https://github.com/gohugoio/hugo/files/8349583/repro.zip)

**Comment by pamubay** [comment]
Duplicate #8383
