### ISSUE TITLE
Expose underlying error messages for postcss

### ISSUE THREAD

**Issue by leemorrisdev** [gohugoio/hugo#9730]
When using the extended binary with postcss, I wonder if there's a way the error messages can be improved in some scenarios.  I've spent some time today a little puzzled with this error message:

```
Error: Error building site: POSTCSS: failed to transform "scss/main.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
```

After triple-checking I was using hugo extended, and had the node modules installed, I dug into the hugo source code and my issue was actually due to not having `npx` on my path (node/npm were).  It looks like any errors with the npx call get handled as if postcss is not supported.

It'd be great if we could get something like:

```
Error: Error building site: POSTCSS: npx: not found
```
where `npx: not found` is what I get when I try from a shell.

**Comment by ToddBradley** [comment]
Oh man, I know exactly how you feel. I am dealing with this same error right now, and have found 3 different root causes and suggested fixes online for it. Unfortunately, none of them fixed my problem. I hoped that turning on `--verbose` would help, but that only makes hugo tell me more about things that are working right, not about things that are breaking.

**Comment by xonev** [comment]
I'm getting this exact same error message, and I haven't been able to get to the bottom of it:

```
hugo version
hugo v0.115.3+extended darwin/arm64 BuildDate=unknown
```

```
which npx
/Users/sajo/.nvm/versions/node/v18.16.1/bin/npx
```

```
ls themes/hugo-product-launch/node_modules
. . . postcss-cli . . .
```

**Comment by jmooring** [comment]
@xonev 

You are using nvm, so I am suspicious of environment variables. Hugo's [default security policy ](https://gohugo.io/about/security-model/#security-policy) with v0.115.2 and later allows access to a predefined list of environment variables:

```text
[security.exec]
osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG)$']
```

Please change this to:

```text
[security.exec]
osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|NPM_)$']
```

And test again.

**Comment by mattomis** [comment]
I am seeing this same error, adding an entry to the security.exec block had no effect. I am not using npx.

**Comment by jaypipes** [comment]
> @xonev
> 
> You are using nvm, so I am suspicious of environment variables. Hugo's [default security policy ](https://gohugo.io/about/security-model/#security-policy) with v0.115.2 and later allows access to this predefined list of environment variables:
> 
> ```
> [security.exec]
> osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG)$']
> ```
> 
> Please change this to:
> 
> ```
> [security.exec]
> osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|NPM_)$']
> ```
> 
> And test again.
> 
> To allow access to all environment variables:
> 
> ```
> [security.exec]
> osEnv = ['.*']
> ```

@jmooring I tried both of the above. No change... I'm also using `nvm`, like @xonev, and getting the same `binary with name "npx" not found` message, even though it's in my path:

```
$ which npx
/home/jaypipes/.nvm/versions/node/v19.4.0/bin/npx
```

Any other ideas?
