### ISSUE TITLE
Hugo deploy slow when s3 storing large multipart files

### ISSUE THREAD

**Issue by davidejones** [gohugoio/hugo#9735]
**Note this appears to be a somewhat known issue according to the source code comments. Would love to figure out a direction for improving this** 

### What version of Hugo are you using (`hugo version`)?

I believe this issue exists with any hugo version containing the deploy functionality.
For reference I am using `hugo v0.89.4-AB01BA6E+extended`

### Does this issue reproduce with the latest release?

Yes

### What is Hugo Deploy doing?

Hugo deploy does some MD5 compare of remote files and local files to determine differences and whether to upload.

If you have multipart uploads in s3 this results in them not having an MD5 that can be used for comparison. Hugos current solution is for reliability and is to download the file and generate a MD5 of the contents and then compare like usual.
[Source Code Example of this Here](https://github.com/gohugoio/hugo/blob/db1562e134fc4182cfd063058e9ecd0316a0d906/deploy/deploy.go#L576)

### What is the problem?

If you have an s3 bucket with many large multipart files then the time to deploy can be very slow. This is because its downloading each of these to create MD5s for comparison.

Include/exclude filters may work to a point but isn't ideal

### Solutions

Some suggestions from **vangent** in an similar issue here  https://github.com/google/go-cloud/issues/1898

1. One option is to fallback to Size comparison when no MD5 instead of generating. 
   _This might not be as reliable but 99% of the time should work. perhaps this could be an optional flag?_

2. Consider saving an MD5 hash (or any other hash) explicitly in Metadata. 
   _Perhaps a `Hugo-Hash` attribute is stored on objects and replaces the current obj.MD5 and is used for compare?_

**Comment by jmooring** [comment]
@davidejones Was this issue resolved by #9742? The commit message states "improves" but it is not clear to me what remains to be fixed.

**Comment by davidejones** [comment]
@jmooring Yes this issue is resolved by 9742!
