### ISSUE TITLE
CSS min() and max()

### ISSUE THREAD

**Issue by Blue-Nomad** [gohugoio/hugo#9736]
### What version of Hugo are you using?

```
0.96.0
```

### Does this issue reproduce with the latest release?

Yes

### The issue

CSS min() and max() functions should support mixed units, see https://developer.mozilla.org/en-US/docs/Web/CSS/max - vw, px, em, and rem are all used in the examples with each other.

When using this with hugo, we get:

```
TOCSS: failed to transform "css.scss" (text/x-scss): SCSS processing failed: file "", line 0, col 0: Incompatible units: 'px' and 'vw'. 
```

I'm currently having to use clamp() so I can use multiple units, as that works.

**Comment by jmooring** [comment]
Hugo transpiles SCSS to CSS using `libsass` by default. Use the `dartsass` transpiler instead.

Instructions:
<https://discourse.gohugo.io/t/37718/16>
