### ISSUE TITLE
hugo --minify breaks URL encoded

### ISSUE THREAD

**Issue by IGLOU-EU** [gohugoio/hugo#9740]
Hi HuGophers,

### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
hugo v0.96.0 linux/amd64 BuildDate=unknown
</pre>
Build with `go install github.com/gohugoio/hugo@latest` 5 mn ago.

### Trouble
In my template, I use emoji with rel="icon". To do that, I use URL encoded SVG format (for w3c validation)
```html
<link rel="icon" href="data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20100%20100%22%3E%3Ctext%20y=%22.9em%22%20font-size=%2290%22%3E💾%3C/text%3E%3C/svg%3E" />
```

But, with `--minify flag, every space `%20` are converted to space
```html
<link rel=icon href="data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22%3E%3Ctext y=%22.9em%22 font-size=%2290%22%3E%F0%9F%92%BE%3C/text%3E%3C/svg%3E">
```

**Comment by jmooring** [comment]
See <https://github.com/tdewolff/minify/issues/475>

**Comment by tdewolff** [comment]
Thanks for raising this issue. Unfortunately, the specification isn't clear about this and it wildly depends on the browser. The current encoding was tested with all major browsers, but perhaps we missed one. For which renderer/browser does this cause an issue for you? Just now testing in Firefox and Chrome it seems to work fine.

**Comment by jmooring** [comment]
I didn't have any problems rendering the minified HTML. The problem is that it doesn't validate with `https://validator.w3.org/`.

> Unfortunately, the specification isn't clear about which characters should be URL encoded and which not,

 I understand.

I thought I could work around the ambiguity by base64 encoding, but minify determines that (in this case) base64 encoding produces a longer string, and reverts to plain text.
