### ISSUE TITLE
Expand support for singular/plural translation to include other types of grammatical numbers

### ISSUE THREAD

**Issue by HelmetOwl** [gohugoio/hugo#9763]
Some languages have more types of grammatical numbers than just singular and plural, such as dual and trial. See here: [https://en.wikipedia.org/wiki/Grammatical_number#Types_of_number](https://en.wikipedia.org/wiki/Grammatical_number#Types_of_number).

I propose support be added for the translator to specify a range of numbers for which each translation will apply and keep the "other" category too because one inevitably gets to a point where a translation applies to the rest of the numbers. For example, one could specify translations for: 1, 2, 3+; or 1, 2-3, 4+; or 1, 2, 3-7, 8+.

A loose example of this for an English reading time display:
1: one minute to read;
2: a couple of minutes to read;
3-4: a few minutes to read;
5+: '{{.Count}} minutes to read'.

Obviously, writing it like this is optional in English, but in some languages it's grammatically required and might take the form of morphing the word "minute" like in this hypothetical example:
1: one minute to read;
2: two minuto to read;
3-4: '{{.Count}} minuta to read';
5+: '{{.Count}} minuti to read'.

**Comment by jmooring** [comment]
This is already supported via CLDR pluralization rules:
<https://unicode-org.github.io/cldr-staging/charts/41/supplemental/language_plural_rules.html>

i18n/pl.toml

```toml
[day]
one = "{{ . }} miesiąc"
few = "{{ . }} miesiące"
many = "{{ . }} miesięcy"
other = "{{ . }} miesiąca"
```

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
