### ISSUE TITLE
Allow slice type as `.GetRemote` headers options

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#9770]
Currently `.GetRemote` `headers` option only takes a `map`, which prevents the creation of [POST mutlipart/form-data request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST) for the reasons detailed below.

This proposal's purpose is to lift this limitation by optionally giving more control (and responsibility) to the user over headers structure.

### The problem
Currently, using a map as `headers` options:
1. Every `key/value` pair must result in `Key: value`, which prevents adding lone strings like boundaries used in multipart requests.
2. It's impossible to send multiple headers with same key, which is necessary in multipart requests. 
3. It prevents controlling the order of the headers, as golang will reorder every key in alpha.

This is an example of a mutliipart request headers as used to [create an entry in a famous company's News API](https://developer.apple.com/documentation/apple_news/create_an_article#2970453):

```
Content-Type: multipart/form-data; boundary=535e329ca936f79a19ac9a251f7d48f7
Authorization: HHMAC; key="xxx"; signature="xxx"; date="2015-03-05T03:00:27Z"
--535e329ca936f79a19ac9a251f7d48f7
Content-Type: application/json
Content-Disposition: form-data; filename=article.json; name=article.json
{
 content of json
}
--535e329ca936f79a19ac9a251f7d48f7
Content-Type: image/jpeg
Content-Disposition: form-data; filename=mountain-lions.jpg; name=my_image
{
binary content of mountain-lions.jpg
}
--535e329ca936f79a19ac9a251f7d48f7--
```

### The proposal

Allowing the `headers` option to be passed as a slice/array as well. Though using an array for headers would shift the responsibility of correctly formating the headers to the user, it would give them more control. 

For example, user could create the aforementioned request by doing:

```
{{ $headers := slice
  `Content-Type: multipart/form-data; boundary=535e329ca936f79a19ac9a251f7d48f7`
  `Authorization: HHMAC; key="xxx"; signature="xxx"; date="2015-03-05T03:00:27Z"`
}}
{{ with "partial/GetData" $ }}
  {{ $headers = $headers | append "--535e329ca936f79a19ac9a251f7d48f7" }}
  {{ $headers = $headers | append "Content-Type: application/json" }}
  {{ $headers = $headers | append "Content-Disposition: form-data; filename=article.json; name=article.json" }}
  {{ $headers = $headers | append (. | jsonify) }}
{{ end }}
{{ with resources.Get $.Params.image }}
  {{ $headers = $headers | append "--535e329ca936f79a19ac9a251f7d48f7" }}
  {{ $headers = $headers | append (printf "Content-Type: %s/%s" .MainType .SubType) }}
  {{ $headers = $headers | append (printf "Content-Disposition: form-data; filename=%s; name=my_image" .Name) }}
  {{ $headers = $headers | append .Content }}
{{ end }}
{{ $headers = $headers | append "--535e329ca936f79a19ac9a251f7d48f7--" }}
{{ with resources.GetRemote $url (dict "method" "POST" "headers" $headers) }}
  🎉
{{ end }}
```

**Comment by regisphilibert** [comment]
> I'm pretty sure that is possible

If so I'd love to know how.  Would love to be also able to address **1.**. I've yet to find a use case for **3.** but I think it could come handy.

**Comment by bep** [comment]
>Allowing the headers option to be passed as a slice/array as well

* The HTTP API in  Go is a string map with string slices, and I'm not prepared to write low level HTTP code to support requirements I don't understand.
* You can do `dict "myheader" slice "a" "b" "c"`
* I assume you can also have 1 empty key

```go
type Header map[string][]string
```

I'm closing this. I suggest create threads on the forum for similar topics.

**Comment by regisphilibert** [comment]
> I'm closing this. I suggest create threads on the forum for similar topics.

I had created one last week: https://discourse.gohugo.io/t/advanced-getremote-headers-usage-with-multipart-form-data/38112

**Comment by bep** [comment]
Good; what I'm saying is that a GitHub issue cannot start out with lots of undefined questions, it has to be well defined, and this is only well defined in the title.

**Comment by regisphilibert** [comment]
> and this is only well defined in the title.

I obviously disagree with that statement, otherwise I would have not hit the "submit new issue" button.

I'll try your suggestion and post your answer in the thread.

Thanks.
