### ISSUE TITLE
Add a --noBuildLock flag

### ISSUE THREAD

**Issue by sftim** [gohugoio/hugo#9780]
For local development, the [Kubernetes project](https://kubernetes.io/) runs Hugo in a container, with the website source mounted in read-only (there is a tmpfs that Hugo renders to).

Recent Hugo releases try to lock the source directory, which fails because of the read-only mount. I'd welcome a mechanism to bypass the lock file creation for the within-a-container case; we know it's actually safe to have Hugo try to run inside the container and to run outside it as well.

**Comment by bep** [comment]
You're not the first asking for something similar, so I guess we should do that. If someone is quick with a PR, I may get it in the 0.97 release...
