### ISSUE TITLE
[v0.97.0] hugo server PostProcess wrong/unprocessed permalink

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#9788]
```html
<!doctype html>
<html lang="{{ .Lang }}">
  <head>
    {{- $options := dict "targetPath" "assets/bundle.min.css" "outputStyle" "compressed" "includePaths" (slice "node_modules") -}}
    {{- $style := resources.Get "scss/index.scss" | toCSS $options | resources.PostCSS | fingerprint | resources.PostProcess -}}
    <link rel="stylesheet" href="{{ $style.Permalink }}" integrity="{{ $style.Data.Integrity }}" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello World</h1>
  </body>
</html>
```

1. `hugo server` not working.

```text
hugo v0.97.0-c07f3626e7c8160943591f4d209977efa02c3dca+extended linux/amd64 BuildDate=2022-04-14T08:45:07Z VendorInfo=gohugoio

<link rel="stylesheet" href="__h_pp_l1_2_Permalink__e=" integrity="__h_pp_l1_2_Data.Integrity__e=" crossorigin="anonymous">
```

2. `hugo server --renderToDisk` works as expected.

```text
hugo v0.97.0-c07f3626e7c8160943591f4d209977efa02c3dca+extended linux/amd64 BuildDate=2022-04-14T08:45:07Z VendorInfo=gohugoio

<link rel="stylesheet" href="http://localhost:37979/assets/bundle.min.de5eadfd48d2043210f12189a24cb4ada1fb1f5a3d085b292a389d40dc75099f.css" integrity="sha256-3l6t/UjSBDIQ8SGJoky0raH7H1o9CFspKjidQNx1CZ8=" crossorigin="anonymous">
```

3. `hugo-v0.96.0 server` works as expected.

**Comment by razonyang** [comment]
Thanks for your reply.

I was confused by the inconsistent default behavior of `hugo server` between `0.96.0` and `0.97.0`. The former version works great, the CSS was purged, so that the final site is predictable.

**Comment by bep** [comment]
>I was confused by the inconsistent default behavior of hugo server between 0.96.0 and 0.97.0.

OK, are you saying that this worked by default in `hugo server´ (render to memory) in earlier releases?

>I think it's reasonable to apply it to local environment as well.

Yea, well, if you're fingerprinting your CSS running the local dev server, you effectively have to regenerate every HTML page on every CSS change, which is not something I would want.

**Comment by bep** [comment]
Yea, OK, I think I understand where I got this wrong, I will have a look at it. Sorry for the noise.
