### ISSUE TITLE
Error calling markdownify

### ISSUE THREAD

**Issue by pale-bluedot** [gohugoio/hugo#9798]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.97.0
</pre>

### Does this issue reproduce with the latest release?
I haven't tried the latest as it was advised to stick with 0.97.0.

### Problem 
I was trying to add a page today but I was met with this error when building. I deleted the new page and any of the new code for the [menu] in config.toml but the error is still popping up. Using latest version of [tella theme](https://github.com/opera7133/tella). I posted on the theme's issue github as well as I'm not sure where the problem is.

`PS C:\Coding\Hugo\sites\bike-north-bergen> hugo Start building sites … hugo v0.97.0-c07f3626e7c8160943591f4d209977efa02c3dca windows/amd64 BuildDate=2022-04-14T08:45:07Z VendorInfo=gohugoioError: Error building site: "C:\Coding\Hugo\sites\bike-north-bergen\themes\tella\layouts\_default\_markup\render-link.html:1:162": execute of template failed: template: _default/_markup/render-link.html:1:162: executing "_default/_markup/render-link.html" at <markdownify>: error calling markdownify: text is already rendered, repeating it may cause infinite recursion`

render-link.html file:
`<a href="{{ .Destination | safeURL }}"{{ with .Title}} title="{{ . }}"{{ end }}{{ if strings.HasPrefix .Destination "http" }} target="_blank"{{ end }}>{{ .Text | markdownify }}</a>`

**Comment by jmooring** [comment]
The error message is telling you what's wrong: 

> "_default/_markup/render-link.html" at <markdownify>: error calling markdownify: text is already rendered

Passing `.Text` through `markdownify` or `.Page.RenderString` in a render hook is nonsensical. It is already rendered.

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
