### ISSUE TITLE
Cannot use Hugo with ASDF

### ISSUE THREAD

**Issue by rgalanakis** [gohugoio/hugo#9811]
### What version of Hugo are you using (`hugo version`)?

hugo v0.97.0-c07f3626e7c8160943591f4d209977efa02c3dca+extended darwin/arm64 BuildDate=2022-04-14T08:45:07Z VendorInfo=gohugoio

(extended)

### Does this issue reproduce with the latest release?

Yes

### Issue

When running with ASDF, Hugo errors trying to run `npx`. This has to do with how it sanitizes or modifies the environment to invoke out to `npx`.

```
> cat .tool-versions
nodejs 16.13.1
hugo extended_0.97.0
> npx --version
8.1.2
> which npx
/Users/rob/.asdf/shims/npx
> asdf which npx
/Users/rob/.asdf/installs/nodejs/16.13.1/bin/npx
> hugo serve
Start building sites … 
hugo v0.97.0-c07f3626e7c8160943591f4d209977efa02c3dca+extended darwin/arm64 BuildDate=2022-04-14T08:45:07Z VendorInfo=gohugoio
ERROR 2022/04/21 14:13:22 POSTCSS: failed to transform "sass/styleguide.css" (text/css): unknown command: npx. Perhaps you have to reshim?
```

And to fix I was able to do:

    PATH=`asdf which npx | xargs dirname`:${PATH} make up-ui

I suspect this is related to #9800 but am not certain. Other than fixing this in Hugo, or working around as given, is there any way to customize the exec behavior?

**Comment by jmooring** [comment]
Let’s see if an environment variable is being blocked. In your site configuration:

[security.exec]
  osEnv = ['.*']

**Comment by rgalanakis** [comment]
Yup, that fixed it @jmooring. It's a reasonable workaround to find the offending environment variable and include it there?

**Comment by jmooring** [comment]
The default config is:

```toml
[security.exec]
  osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
```

Try:

```toml
[security.exec]
  osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$','(?i)^ASDF']
```

**Comment by jmooring** [comment]
> could the error message hint towards this solution

I think it did:

> Perhaps you have to reshim?

This smelled like an ASDF message, because it certainly isn't a Hugo message. From there I read about ASDF, learned that it depends on env vars, and there you go.

**Comment by rgalanakis** [comment]
I knew it had to do with ASDF due to the reshim message, but I had to look at the Hugo source to understand it was due to env vars. In other words: you knew about Hugo exec's use of env vars and had to read about ASDF; most Hugo users that hit an error like this will know about their environment but have to read about Hugo exec.

It seems like, if the exec fails, it'd be nice to include a link to some help- the issues due to missing env vars could be a lot more obscure than this, I think. LMK if you're open to it. I understand these sorts of UX edge cases are usually annoying for maintainers to fix, but it's hard to see how much time is saved in the aggregate by handling them.

**Comment by jmooring** [comment]
Hugo has no idea why `npx` failed. Perhaps the `asdf` framework needs to emit more explicit messages.

**Comment by rgalanakis** [comment]
I meant (and wrote) that Hugo should add a link to some docs any time the exec fails, nothing to do with ASDF. But if you're not interested you should close the issue.

**Comment by rgalanakis** [comment]
For the sake of anyone stumbling upon this, the final set of env vars needed was:

```yaml
security:
  exec:
    osEnv:
      - '(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$'
      - ASDF_DIR
      - HOME
```

**Comment by jmooring** [comment]
> Hugo should add a link to some docs any time the exec fails

I'll let @bep make that call.

To me, the more important question is, does the value provided by this security mechanism outweigh its cost? We've had a number of issues since this was implemented.

- https://discourse.gohugo.io/t/38303/
- https://discourse.gohugo.io/t/37397/
- https://discourse.gohugo.io/t/37090/
- https://discourse.gohugo.io/t/36180/
- https://discourse.gohugo.io/t/36146/
- https://github.com/gohugoio/hugo/issues/9741
- https://github.com/gohugoio/hugo/issues/9732
- https://github.com/gohugoio/hugo/issues/9333

When I create a site that I expect to be cloned, I can include the security settings in the config file, in which case you are only protected if you have set the corresponding env vars. For example, in .bashrc:

```
export HUGO_SECURITY_FUNCS_GETENV="^HUGO_"
export HUGO_SECURITY_EXEC_OSENV="(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$"
export HUGO_SECURITY_EXEC_ALLOW="'^dart-sass-embedded$', '^go$', '^npx$', '^postcss$'"
```

So, perhaps we could set the default to `osEnv = ['.*']`, and you would still be protected if you have set your local env. Just a thought...

**Comment by bep** [comment]
>To me, the more important question is, does the value provided by this security mechanism outweigh its cost? 

Without this security mechanism, I'm not using Hugo, but that's my 50 cents.

>When I create a site that I expect to be cloned, I can include the security settings in the config file.

Sure you can, but that's also fairly easy for me to reason about, looking at the top level config.

> in which case you are only protected if you have set the corresponding env vars to be more restrictive. 

Which I have. Which makes me not only protected, but always protected from all sites.

>So, perhaps we could set the default to osEnv = ['.*'], and you would still be protected if you have set your local env to be more restrictive. Just a thought...

We cannot have a default security setting set to its most insecure setting. Especially considering that 95% or all Hugo sites does not need these external executables (number taken out of a hat), and 4.99 of the remaining are perfectly fine with the defaults (again numbers out of a hat).

This recent news story should be a good read:

https://github.blog/2022-04-15-security-alert-stolen-oauth-user-tokens/

I'm not saying that Hugo's security setup is perfect and bullet proof and all, but at least we're trying. Having the full OS environment leak via some random theme, that is not trying. This situation isn't going to get any easier in the future, and it's a little bit scary to think of all the build tools out there with access to the full OS.

**Comment by giuliohome** [comment]
You mean **ADFS** in the title, meaning Active Directory Federation Services.

Yesterday I spent hours before finding out that I had to set `osEnv = ['.*']` in the security section of toml configuration! 

Yeah at least a message hint would help next one.

**Comment by jmooring** [comment]
This was a security configuration setting, resolved by adding `ASDF` to `security.exes.osenv` in site configuration. See <https://gohugo.io/about/security-model/>.
