### ISSUE TITLE
Add attribute (id) support for Markdown definition lists

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9815]
I'm doing some work behind the scenes to generate the outline of a new reference section for the new documentation site, and I would really like to use

* h2 headings for the bigger topics
* definition lists for the smaller topics (e.g. list of options)

But to do that we need a way to somehow link to them, e.g.:

```md
Mydef {#myid}
: This is mydef.
```

Note that any concept of "auto id" is not in the scope of this issue.

**Comment by jmooring** [comment]
This hijacks the link render hook, but works...
<https://discourse.gohugo.io/t/automatically-add-id-attribute-to-dt-element/38191/2>

**Comment by bep** [comment]
I may be a little too conservative for that workaround ... I'll see how hard it is to get a proper solution.

**Comment by bep** [comment]
Never mind, this works and is plenty good enough for me:

```md
Mydef
: This is mydef.
{#myid}
```
