### ISSUE TITLE
Footnotes not rendered by markdownify when passed into shortcodes.

### ISSUE THREAD

**Issue by gbmhunter** [gohugoio/hugo#9816]
I use an "img" shortcode to display images with captions in markdown files. I'm using the format:

```
{{% img src="img.png" width="500px" caption="Caption with footnote[^footnote-1]." %}}
```

However, even though I am calling `markdownify` on the caption (within the shortcode), the footnote does not get parsed into a "1", "2", "3", e.t.c, and I'm left with the plain text "[^footnote-1]" in the image caption.

**Comment by jmooring** [comment]
Assuming that [this](https://github.com/gbmhunter/blog/blob/master/layouts/shortcodes/img.html) is your shortcode, do this:

```diff
diff --git a/layouts/shortcodes/img.html b/layouts/shortcodes/img.html
index 18ca26b0d..3dc478fa7 100644
--- a/layouts/shortcodes/img.html
+++ b/layouts/shortcodes/img.html
@@ -38,7 +38,8 @@
     {{- if (.Get "caption") -}}
     <figcaption>
       <p>
-        {{- .Get "caption" | markdownify -}}
+
+ {{ .Get "caption" -}}
       </p>
     </figcaption>
     {{- end -}}
```

Notes:

1. When placing markdown within HTML blocks, the opening element must be followed by a blank line. See <https://spec.commonmark.org/0.30/#html-blocks>.
2. If you indent markdown by four or more spaces, it is rendered as a code block. See <https://spec.commonmark.org/0.30/#indented-code-blocks>.
3. There is no need to pass the caption through the `markdownify` function.

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by gbmhunter** [comment]
Thanks for the tips @jmooring ! I did as you suggested, and no change in the output. However, it's still probably a fault with my code, I'll move the discussion over to discourse.

**Comment by gbmhunter** [comment]
Ok yup my futher mistake, I had to replace the `{{-` style delimiters when calling `img` to use `{{%` instead.
