### ISSUE TITLE
resources.Get generates multiple copies for multiple languages

### ISSUE THREAD

**Issue by Ice-Hazymoon** [gohugoio/hugo#9828]
```html
{{- $manifest := resources.Get "manifest.json" | resources.ExecuteAsTemplate "manifest.json" . }}
<link rel="manifest" href="{{ $manifest.RelPermalink | absLangURL }}">
```

If the default language of my site is English, there is also an Chinese language. I want to have access to two copies of `/manifest.json` and `/zh/manifest.json`

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
