### ISSUE TITLE
Resized image exposes dimensions of original image

### ISSUE THREAD

**Issue by despens** [gohugoio/hugo#9847]
```console
$ hugo version
hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended linux/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=mage
```

When creating a resized version of an image, the original image's Width and Height are exposed in the image object, not the scaled values:

```gotemplate
Load original image (physical width 1080 px)
{{ $image := $.Page.Resources.GetMatch (.Get "image.png") }}
Scale to 600 px width
{{ $image_scaled := $image.Resize "600x" }}
Check for dimensions of scaled image:
{{ $image_scaled.Width }}
==> 1080
(should be 600)
```

Is the image perhaps only scaled later in the process?

**Comment by jmooring** [comment]
@despens Please provide a link to the original image.

**Comment by despens** [comment]
I am sorry I made a mistake (don't ask). Took me only one day to figure it out. 😅 This bug is invalid, please excuse.
