### ISSUE TITLE
Sorting is not stable

### ISSUE THREAD

**Issue by freud14** [gohugoio/hugo#9865]
Hi,

I'm trying to sort a slice of dicts by two different fields but when calling sort twice, it seems the order is not kept stable. Here is a reproducible example. 
```go
{{ $values := slice (dict "a" 1 "b" 2) (dict "a" 3 "b" 1) (dict "a" 2 "b" 0) (dict "a" 1 "b" 0) (dict "a" 3 "b" 1) (dict "a" 2 "b" 2) (dict "a" 2 "b" 1) (dict "a" 0 "b" 3) (dict "a" 3 "b" 3) (dict "a" 0 "b" 0) (dict "a" 0 "b" 0) (dict "a" 2 "b" 0) (dict "a" 1 "b" 2) (dict "a" 1 "b" 1) (dict "a" 3 "b" 0) (dict "a" 2 "b" 0) (dict "a" 3 "b" 0) (dict "a" 3 "b" 0) (dict "a" 3 "b" 0) (dict "a" 3 "b" 1) }}
{{ sort (sort $values "b") "a" }}
```
which outputs the following:
<pre>
[map[a:0 b:0] map[a:0 b:0] map[a:0 b:3] map[a:1 b:2] map[a:1 b:2] map[a:1 b:1] map[a:1 b:0] map[a:2 b:0] map[a:2 b:2] map[a:2 b:0] map[a:2 b:0] map[a:2 b:1] map[a:3 b:1] map[a:3 b:1] map[a:3 b:1] map[a:3 b:0] map[a:3 b:0] map[a:3 b:0] map[a:3 b:3] map[a:3 b:0]] 
</pre>

For each unique value of "a", the values of "b" should be sorted. In this example, we can see for a=1, the values of b are in this order: 2, 2, 1, 0.

Do you know some workaround?

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.98.0-165d299cde259c8b801abadc6d3405a229e449f6+extended linux/amd64 BuildDate=2022-04-28T10:23:30Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by freud14** [comment]
If I understand correctly the code base, this line https://github.com/gohugoio/hugo/blob/f2946da9e806c2bafbdd26707fe339db79bd980b/tpl/collections/sort.go#L180 should be change to `sort.Stable(p)` to make the sorting stable.

**Comment by jmooring** [comment]
Given this map:

```
{{ $m := slice
  (dict "a" 1 "b" 2)
  (dict "a" 2 "b" 2)
  (dict "a" 1 "b" 1)
  (dict "a" 2 "b" 1)
}}
```

You currently have to do something like this:

```
{{ $s := slice }}
{{ range $m }}
  {{ $s = $s | append .a }}
{{ end }}

{{ range ($s | uniq | sort) }}
  {{ range sort (where $m "a" .) "b" }}
    {{ range $k, $v := . }}
      {{ $k }}: {{ $v }}<br>
    {{ end }}
  {{ end }}
{{ end }}
```

It would be great if you could do this instead:

```
{{ range sort (sort $m "a") "b" }}
  {{ range $k, $v := . }}
    {{ $k }}: {{ $v }}<br>
  {{ end }}
{{ end }}
```
