### ISSUE TITLE
Pagination: Incorrect Total Pages

### ISSUE THREAD

**Issue by dennexequiel-mmdc** [gohugoio/hugo#9879]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version v0.98.0

</pre>

### Does this issue reproduce with the latest release?
No

**Comment by dennexequiel-mmdc** [comment]
Hi, 

I have custom pagination on a web page. When I added new content, it seemed that the page number returned was incorrect, and because of that, I have the last page that doesn't have a list.
![image](https://user-images.githubusercontent.com/101326244/168011429-1a41c909-1b6c-42b1-98c8-1200605bd1a4.png)


By the way, I'm using the default number of paginate which is 10.

**Comment by bep** [comment]
Looking at the iteration, I would say that you have misunderstood how pagination works in Hugo. I would suggest you open up a new topic at:

https://discourse.gohugo.io/

**Comment by dennexequiel-mmdc** [comment]
> Looking at the iteration, I would say that you have misunderstood how pagination works in Hugo. I would suggest you open up a new topic at:
> 
> https://discourse.gohugo.io/

Thanks, @bep. I just opened a topic: https://discourse.gohugo.io/t/pagination-incorrect-total-pages/38587
