### ISSUE TITLE
highlightling: Remove noHl (which has undefined behaviour)

### ISSUE THREAD

**Issue by hofbi** [gohugoio/hugo#9885]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.95
</pre>

### Does this issue reproduce with the latest release?

I am using the docker version, so waiting for https://github.com/klakegg/docker-hugo/pull/64 to be merged

### Problem

Based on https://github.com/wowchemy/wowchemy-hugo-themes/issues/2708, we observed 

> `<span>` instances are being inserted by Hugo which we would assume shouldn't happen when Hugo is configured with `noHl: true`. It's either a Hugo bug with the `noHl` option or there's an opportunity for Hugo team to allow the Hugo code block parser to be used to detect Mermaid diagram code blocks without highlighting any code or injecting any `<span>`.

The `<span>` instances being inserted cause rendering issues for code blocks in markdown slides.

**Comment by jmooring** [comment]
> I don't know what noHl was meant to mean

Same here, but I do know that the behavior changed a bit when we removed <https://github.com/yuin/goldmark-highlighting> in v0.93.0.

This option/attribute has never been documented, other than its presence in docs.json. If it were up to me, I'd remove the option and see what breaks in the wild.

**Comment by bep** [comment]
@hofbi I understand that the action suggested above does not solve your issue.
