### ISSUE TITLE
Bug in absLangURL in multilingual mode

### ISSUE THREAD

**Issue by Ice-Hazymoon** [gohugoio/hugo#9887]
<pre>
$ hugo version

hugo v0.98.0-165d299cde259c8b801abadc6d3405a229e449f6+extended windows/amd64 BuildDate=2022-04-28T10:23:30Z VendorInfo=gohugoio
</pre>

footer.html

```
href="{{- "/index.xml" | absLangURL -}}"
```

In development

```
href="//localhost:1313/zh-cn/sitemap.xml"
```

In production

```
href="zh-cn/sitemap.xml"
```

I expect it to be `/zh-cn/sitemap.xml`

When I set the `.Site.baseURL`, it all works fine, Is he a feature or a bug?

**Comment by jmooring** [comment]
Feature.

In the future, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
