### ISSUE TITLE
Chroma: Rust highlighting fails with raw multiline string not terminated by semicolon

### ISSUE THREAD

**Issue by dradtke** [gohugoio/hugo#9890]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.98.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

Here is a screenshot of the issue:

![rust-highlight-issue](https://user-images.githubusercontent.com/929204/168303895-d0e1d866-f6bf-4236-a9a9-f59e9869ac42.png)

Note how the string highlighting continues past the end of the function. Changing it to end with a semicolon fixes it:

![rust-highlight-fixed](https://user-images.githubusercontent.com/929204/168304546-482aea2b-d814-4ba9-8aad-4e16f22a6d84.png)

This may just be an issue with the underlying Chroma library, but I figured I would start here since Hugo is how this issue was surfaced.

**Comment by bep** [comment]
To get a fix for this, you need to open up an issue in the Chroma issue tracker: https://github.com/alecthomas/chroma/issues

**Comment by jmooring** [comment]
This has been resolved upstream. Just waiting for a new release...
