### ISSUE TITLE
org-mode front matter ignored when document contains a property drawer

### ISSUE THREAD

**Issue by dinkonin** [gohugoio/hugo#9898]
### What version of Hugo are you using (`hugo version`)?
<pre>
hugo v0.98.0+extended linux/amd64
</pre>

When parsing an org file(org-roam note in my case) , hugo fails to get the {{ .Title }} of the document if it has a top level property drawer (added by  `org-id-get-create`). 

This does not work until I delete the drawer:
```
:PROPERTIES:
:ID:       04515c80-d5af-4aa1-801b-ffcc7411cd29
:END:

#+TITLE: Nice title

* Content
```

Maybe hugo should omit property drawers when parsing org-files, or maybe just the top-level one ?

**Comment by dinkonin** [comment]
After thinking about it some more and reading [the org manual](https://orgmode.org/org.html#Property-Syntax) on properties. Maybe properties drawers should not be ommited but parsed. A top level property drawer might be a nice way to pass front matter data to hugo.

**Comment by bep** [comment]
This looks like an issue that should be reported at https://github.com/niklasfasching/go-org/issues

**Comment by dinkonin** [comment]
Maybe I've misread something but according to this [This](https://github.com/niklasfasching/go-org/issues/35#issuecomment-642135375), go-org does not see the front matter keywords in org files ?

**Comment by dinkonin** [comment]
> I don't know what a "property drawer" is, why not pull that drawer below the metadata?
A property drawer in org is a collection of metadata valid for the sub-tree (heading) where they are placed, if it's placed in the beginning of the document (or buffer in emacs) these properties are valid for the whole document.

According to the org-mode [manual](https://orgmode.org/manual/Property-Syntax.html):
> Properties can be inserted on buffer level. That means they apply before the first headline and can be inherited by all entries in > a file. **Property blocks defined before first headline needs to be located at the top of the buffer, allowing only comments above.**

So I don't think they could safely be pulled below, I just tested it and yes emacs fails to parse them if the above convention is not followed.

**Comment by mandos** [comment]
@dinkonin 
Did you check setting property in this way?

> Properties can also be defined using lines like:

`#+PROPERTY: NDisks_ALL 1 2 3 4`
