### ISSUE TITLE
Dev server is broken in 0.99 when using the Multilingual Multihost mode

### ISSUE THREAD

**Issue by freud14** [gohugoio/hugo#9901]
The dev mode for Multilingual Multihost seems to be broken in 0.99. It is not broken in 0.98. Here are the steps to reproduce.
* Create a new site:
  ```sh
  hugo new site quickstart
  ```
* Edit config.toml:
  ```toml
  defaultContentLanguage = 'en'
  [languages]
    [languages.en]
      baseURL = 'https://example.com'
      title = 'My blog'
      weight = 1
    [languages.fr]
      baseURL = 'https://example.fr'
      title = 'Mon blogue'
      weight = 2
  ```
* Run:
  ```sh
  hugo server
  ```
  resulting in:
  <pre>panic: runtime error: index out of range [1] with length 1
  
  goroutine 1 [running]:
  github.com/gohugoio/hugo/commands.(*serverCmd).server.func1(0xc000301770)
          /root/project/hugo/commands/server.go:222 +0x6e5
  github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc000301770)
          /root/project/hugo/commands/commandeer.go:390 +0x702
  github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0x1, 0x1, 0xc000301590, {0x2874040?, 0xc000370bc0}, 0xc0003dd9a0, {0x0, 0x0, 0x0})
          /root/project/hugo/commands/commandeer.go:226 +0x310
  github.com/gohugoio/hugo/commands.initializeConfig(0x0?, 0x0?, 0x0?, 0x22fabba?, {0x2874040?, 0xc000370bc0?}, 0x1d0?)
          /root/project/hugo/commands/hugo.go:125 +0x31
  github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc000370bc0, 0xc000213900, {0xc00024c500?, 0xa56e40?, 0xc0007ffd00?})
          /root/project/hugo/commands/server.go:249 +0x1cd
  github.com/gohugoio/hugo/commands.(*commandsBuilder).newServerCmdSignaled.func1(0xc000213900?, {0x39fa650?, 0x0?, 0x0?})
          /root/project/hugo/commands/server.go:96 +0x36
  github.com/spf13/cobra.(*Command).execute(0xc000213900, {0x39fa650, 0x0, 0x0})
          /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
  github.com/spf13/cobra.(*Command).ExecuteC(0xc00084f400)
          /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
  github.com/gohugoio/hugo/commands.Execute({0xc00003c050, 0x1, 0x1})
          /root/project/hugo/commands/hugo.go:92 +0xb4
  main.main()
          /root/project/hugo/main.go:23 +0x57</pre>

If you remove the `baseURL` fields, the `hugo server` command seems to work as expected.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.99.0-1de333e7a3fc863672ec6d6cd53ba66dbcdd2305+extended linux/amd64 BuildDate=2022-05-16T08:10:56Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

It does with 0.99. The problem is not there in 0.98.

**Comment by rodrigoalcarazdelaosa** [comment]
Happening to me as well with [my repo](https://github.com/rodrigoalcarazdelaosa/fisiquimicamente).
