### ISSUE TITLE
Hugo Serve localhost link should include http for IDE users

### ISSUE THREAD

**Issue by elibroftw** [gohugoio/hugo#9904]
//localhost links are not openable by IDE's like VS Code. It's a pain the ass to copy and paste the URL especially on Mac's where the URL changes between server instances. I suggest using http://localhost:XXXX links instead to make it clear to IDE's that it is a URL.

**Comment by jmooring** [comment]
With a properly configured `baseURL` (e.g., `baseURL = 'https://example.org/'`) the link is correct.

**Comment by elibroftw** [comment]
You're right. This issue only exists when the baseURL is not set!

**Comment by elibroftw** [comment]
I still think this is a bug though. Shouldn't it work without baseUrl set? Or at least tell you to set Base URL?

**Comment by jmooring** [comment]
Setting the `baseURL` to `/` is valid for a site that is accessed via the file system instead of via a server. So it is doing what it should be doing. This is a not a bug. Please take further discussion to the forum (<https://discourse.gohugo.io/>).
