### ISSUE TITLE
Smart quote rendering should not happen inside HTML <code> blocks in Markdown content

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#9911]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.99.1
</pre>

### Does this issue reproduce with the latest release?
Yes

### Bug Recipe

Put this in your Markdown content file

```md
In Nim, <code class="inline-src language-nim" data-lang="nim">echo "hello"</code> will print
_hello_.
```

[Deployed test showing this issue](https://bug-smart-quote-conversion-in-code-element--hugo-mwe.netlify.app/posts/double-quotes-in-html-code-elements/)
- [Markdown source file for this test](https://gitlab.com/hugo-mwe/hugo-mwe/-/raw/bug-smart-quote-conversion-in-code-element/content/posts/double-quotes-in-html-code-elements.md)

### Expected output

The double quotes inside the HTML `<code>` block should have remained the exact same, as straight quotes.

### Observed (incorrect) behavior

![image](https://user-images.githubusercontent.com/3578197/169543522-752d761e-a7bc-4faf-a57c-871832728685.png)

Those double quotes are getting transformed into curved quotes, probably by GoldMark.

### References

- https://github.com/kaushalmodi/ox-hugo/issues/638#issuecomment-1132911542

**Comment by jmooring** [comment]
<https://github.com/yuin/goldmark/issues/308>

**Comment by kaushalmodi** [comment]
@jmooring That's awesome! Thanks for taking time to come up with that bug recipe in Go. You are filling my _Go-fu_ void 😃 .

**Comment by jmooring** [comment]
The upstream maintainer is [reluctant to make any changes](https://github.com/yuin/goldmark/issues/308#issuecomment-1133943364). I'm not sure where that leaves us.

**Comment by kaushalmodi** [comment]
Closing this as it's out of the scope of Hugo. 

I have a workaround for this problem. 

Below renders without the typographer messing up the quotes:

```md
In Nim, <span class="inline-src language-nim" data-lang="nim">`echo "hello"`</span> will print
_hello_.
```
