### ISSUE TITLE
Crash when partial template is edited

### ISSUE THREAD

**Issue by hsn10** [gohugoio/hugo#9915]
99.1

Hugo server windows build always crashes when I edit theme partial template.

_hugo server --noHTTPCache --disableFastRender --ignoreCache --buildDrafts_

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x20 pc=0x1923da1]
> 
> goroutine 129 [running]:
> github.com/gohugoio/hugo/commands.(*commandeer).handleEvents(0xc0002e93b0, 0xc001889860, 0xc000d835b0, {0xc000418000?, 0x22, 0x40}, 0xc0002e93b0?)
>         /root/project/hugo/commands/hugo.go:1106 +0x721
> github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1()
>         /root/project/hugo/commands/hugo.go:887 +0x26c
> created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
>         /root/project/hugo/commands/hugo.go:878 +0x38d

**Comment by bep** [comment]
I'm not able to reproduce this, but I don't have any "server Windows" to test this on.

**Comment by hsn10** [comment]
Can you get from debugger line where it crashes using that call stack?

**Comment by hsn10** [comment]
I edit theme _beautiful Hugo_ This is bug is quite old, it always crashed for me (2 years back).

**Comment by jmooring** [comment]
Unable to reproduce with v0.112.5 on Linux or Windows when testing with the [Beautiful Hugo](https://github.com/halogenica/beautifulhugo) theme as described.
