### ISSUE TITLE
Some of the ApacheConf code highlight aliases don't work

### ISSUE THREAD

**Issue by Rarst** [gohugoio/hugo#9931]
The [documentation](https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages) lists following aliases for ApacheConf code highlight:

```
ApacheConf
aconf, apache, apacheconf, conf, htaccess
```

I've noticed that out of those `conf` and `htaccess` don't work, ending up in `fallback` language:

<pre>
# Works
```aconf
ExpiresActive On
```
```apache
ExpiresActive On
```
```apacheconf
ExpiresActive On
```

# Doesn't work
```conf
ExpiresActive On
```
```htaccess
ExpiresActive On
```
</pre>

Not sure if this could be documentation and/or upstream issue, Chroma Playground doesn't expose aliases to try, only language selection by name.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.99.1-d524067382e60ce2a2248c3133a1b3af206b6ef1+extended windows/amd64 BuildDate=2022-05-18T11:18:14Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes.

**Comment by bep** [comment]
Thanks for this. The documentation data is generated here:

https://github.com/gohugoio/hugo/blob/b80853de90b10171155b8f3fde47d64ec7bfa0dd/helpers/docshelper.go#L19

I may have misunderstood the logic ... Fixes are welcome ...

You can test the above with:

```
  go run main.go gen docshelper
```

And then look at the generated `docs/data/docshelper.json` file.

**Comment by Rarst** [comment]
Not set up for Go stuff, just a user. :)

From quick search of Chroma source it doesn't currently (v2 beta) contain the latter aliases

**Comment by bep** [comment]
>Not set up for Go stuff, just a user. :)

Sure, I wrote the above as a general remark to everyone.

Yes, Chroma is in v2 now, Hugo still is on v1, which may explain it.
