### ISSUE TITLE
TestDecodeConfig/Basic fails in 0.99.1

### ISSUE THREAD

**Issue by tastytea** [gohugoio/hugo#9935]
I'm getting this error when running `go test -race "./..." -tags extended`:

```
--- FAIL: TestDecodeConfig (0.01s)
    --- FAIL: TestDecodeConfig/Basic (0.00s)
        config_test.go:83:
            error:
              values are not equal
            got:
              bool(false)
            want:
              bool(true)
            stack:
              /var/ram/hugo/modules/config_test.go:83
                c.Assert(hv.IsValid(), qt.Equals, true)

FAIL
FAIL    github.com/gohugoio/hugo/modules        22.640s
```

`export HUGO_BUILD_TAGS=extended && ./mage hugoRace && ./mage -v check` yields the same result.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ ./hugo version
hugo v0.99.1-d524067382e60ce2a2248c3133a1b3af206b6ef1+extended linux/amd64 BuildDate=2022-05-18T11:18:14Z
</pre>

### Does this issue reproduce with the latest release?

Yes.

### Workaround

Changing `max = "0.99.0"` to `max = "0.99.1"` in https://github.com/gohugoio/hugo/blob/v0.99.1/modules/config_test.go#L51 makes the error go away but i don't know if that is the right fix. 😊

**Comment by bep** [comment]
I was about to say that "it works for me and on GitHub", but it actually fails on my MacBook, too. Must me some combination of test flags ... Curious. Ok, thanks for the heads up.
