### ISSUE TITLE
Language title overwrites site title

### ISSUE THREAD

**Issue by hahn-th** [gohugoio/hugo#9956]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.99.1-d524067382e60ce2a2248c3133a1b3af206b6ef1+extended windows/amd64 BuildDate=2022-05-18T11:18:14Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
yes

If i add 
```
languages:
  de:
    languagedirection: rtl
    title: Deutsch
    weight: 1
```
to my config.yaml, the variable `.Site.Title` outputs "Deutsch" instead of the original title. If i remove the line `title: Deutsch` from config,  .Site.Title contains the original site title.

```
<title>{{ .Page.Title }} | {{ .Site.Title }}</title>
```
![grafik](https://user-images.githubusercontent.com/15319212/171059573-a41f89e2-6c61-42d5-8287-1f6434ba0e0d.png)

![grafik](https://user-images.githubusercontent.com/15319212/171059743-9b4809dc-fd4f-4a90-a8b3-ab6fcc555a05.png)

**Comment by jmooring** [comment]
This is working as designed, allowing you to display the site title in different languages. If you want to provide a language name for each of the sites, but use the same title for each site:

```
baseURL = 'https://example.org/'
title = 'My Site'

[languages.en]
contentDir = 'content/en'
languageName = 'English'
languageCode = 'en-US'
weight = 1

[languages.es]
contentDir = 'content/es'
languageName = 'Español'
languageCode = 'es-ES'
weight = 2
```

In the future, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by hahn-th** [comment]
Many thanks! And yes, it makes sense and follows the hugo philosophy.
