### ISSUE TITLE
Can't nest shortcodes with `.Page.RenderString` when goldmark security is enabled (the default)

### ISSUE THREAD

**Issue by roberth** [gohugoio/hugo#9967]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.100.0-DEV+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

#9948 seemed like exactly the solution is was looking for, but I can't get it to render nested shortcodes correctly and securely.

I expected shortcodes to work as an authorization of sorts for emitting fancy tags that goldmark can't just accept normally. This works well for non-nested shortcodes, but breaks down with nesting.

Let's look at an example. In my content, I have

```handlebars
{{< segment class="center aligned" >}}

Some **markdown** text.

{{< button href="https://example.com?callToAction=1" class="ui button huge primary" label="Get Started" icon="arrow alternate circle right" >}}

{{< /segment >}}
```

When `segment.html` is as follows, the `button` HTML is escaped and displayed on the page with `<`'s and all:

```handlebars
<div class="ui segment {{ .Get "class" }}">
  {{ .Inner | .Page.RenderString }}
</div>
```

When I remove `.Page.RenderString`, the HTML is passed through without escaping, but it also fails to render the markdown before the button, and it pokes a leak in the goldmark security. The same happens when I rename it to `segment.md`.

This leads to my question: am I using this new feature correctly?

Also, although I am unfamiliar with the code, I suppose a crucial implementation question is: how can privileged snippets produced by shortcodes be passed along without creating opportunities for the content to insert arbitrary html?

Here's my `button` definition for completeness:

<details>

```
<a {{ with .Get "href" }}href="{{.}}"{{ end }}
   {{ with .Get "class" }}class="ui button {{.}}"{{ end }}
  >
  {{ .Get "label" }}
  {{ with .Get "icon" }}
    <i class="ui icon {{.}}"></i>
  {{ end }}
</a>
```

</details>

**Comment by bep** [comment]
>This leads to my question: am I using this new feature correctly?

Short answer is no. I suggest you take this at https://discourse.gohugo.io/

**Comment by roberth** [comment]
@bep But it's a new feature. How is the community supposed to know how to use it within a week of the release, without documentation? At least, I didn't see any documentation in the PR or the commits that followed the merge.
I guess I'll post a question there then.

**Comment by roberth** [comment]
... or maybe not. I'm a bit tired of rephrasing my question for different media and I have other things I need to do. I'll avoid nesting shortcodes for the time being.

Sorry for the noise. I hope you guys will clarify how to compose shortcode components in the docs at some point. It's a powerful feature, especially when combined with something like Netlify CMS.

Anyway, I'll be sending you some coffee on GitHub Sponsors. Hope that helps with what you're doing :)

**Comment by bep** [comment]
>I hope you guys

I hope you understand that when you say _guys_, it's not a big enterprise. If we (I) didn't redirect questions to the forum, this project would break pretty fast.

So, 

* Shortcode support in RenderString is new
* Shortcode support in Hugo is very old, and nesting of shortcodes is pretty decently documented
* Doing `{{ .Inner | $.Page.RenderString }}` is not something that I even considered doing, but I would say that it's almost never the right thing to do, esp. if `.Inner` contains shortcodes.
* If you have nested shortcodes that you want to have rendered by Goldmark, you need to understand the `{{%` shortcode delimiter.
