### ISSUE TITLE
TOML dates no longer support equality tests against `now`

### ISSUE THREAD

**Issue by aaronpowell** [gohugoio/hugo#9979]
I recently upgraded from an old version (in the 0.50's I think) and have noticed a problem with a template that does a filter against some data that's in TOML using dates.

I have items such as the following:

```toml
{ date = 2022-06-20, name = "End to end GraphQL (workshop)", link = "https://ndcmelbourne.com/agenda/end-to-end-graphql/daba56ef9e98", event = "NDC Melbourne 2022" },
```

And use it in a template like so:

```html
{{ if .Site.Params.speaking.enable }} {{ with .Site.Params.speaking }}
<section id="speaking" class="container">
    <div>
        <h2>{{ .title }}</h2>
        {{ $talks := where .talks "date" ">" now }} {{ if eq (len $talks) 0 }}
        <p>{{ .noTalks }}</p>
        {{ else }}
        <ul class="talk-list">
            {{ range sort $talks "date" "asc" }}
            <li>
                {{ partial "talk" . }}
            </li>
            {{ end }}
        </ul>
        {{ end }}
    </div>
    <div>
        <p>{{ .content }}</p>
        <h3>
            <a href="/talks/" title="Available Talks">My Available Talks</a>
        </h3>
    </div>
</section>
{{ end }} {{ end }}
```

Upon upgrading to the latest version, the `where` condition no longer works, I'm assuming because the two types (the TOML date and `now`) can no longer be compared.

Repo containing the full code is here: https://github.com/aaronpowell/aaronpowell.github.io

Relevant files are:
- TOML: https://github.com/aaronpowell/aaronpowell.github.io/blob/main/src/config.speaking.toml
- Template: https://github.com/aaronpowell/aaronpowell.github.io/blob/main/src/themes/aaronpowell/layouts/partials/speaking.html

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.100.1-0afb4866e345d31cbbcbab4349e43f1d36122806+extended linux/amd64 BuildDate=2022-06-01T10:11:48Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by bep** [comment]
We have a similar issue in #9949 -- which is harder to fix.

This one, though, is fixable. Thanks for the report and sorry about the site breakage.

**Comment by aaronpowell** [comment]
> We have a similar issue in #9949 -- which is harder to fix (but that one has a good workaround).
> 
> This one, though, is fixable. Thanks for the report and sorry about the site breakage.

No worries about the breakage, just my blog so it's not the end of the world 😝

I had seen #9949 and thought they might be related, but it was different enough to raise seperately.
