### ISSUE TITLE
Update to Google Analytics 4

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9987]
Whatever that means.

I know there are other issues mentioning this, but I haven't had time to look into it.

I got the below warning for the gohugo.io sites, which means that it's ... time:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/394382/172419620-1c48d6d0-6eed-4d9e-b127-b20280a91743.png">

**Comment by coliff** [comment]
related: we should mention in the docs that Universal Analytics is deprecated.
https://gohugo.io/templates/internal#google-analytics

**Comment by chalin** [comment]
> related: we should mention in the docs that Universal Analytics is deprecated. https://gohugo.io/templates/internal#google-analytics

Done via https://github.com/gohugoio/hugoDocs/pull/1770

**Comment by chalin** [comment]
@dep - I don't think that anything more needs to be done on the Hugo side of things to support GA4. The warning is for the website, so maybe this issue should be transferred to https://github.com/gohugoio/hugoDocs?

Also, as you mention, there are a few related issues that can probably be closed since GA4 is already supported, such as:

- https://github.com/gohugoio/hugo/issues/4479#issuecomment-1175433475
- https://github.com/gohugoio/hugo/issues/4327#issuecomment-1175431781
- https://github.com/gohugoio/hugo/issues/8549#issuecomment-1175435918

There might be others.

**Comment by sspaeti** [comment]
I'm opened an issue on [Quartz](https://github.com/jackyzha0/quartz/) regarding Google Analytics. But I think it's an error in the Google Analytics Template. Quatz uses this: `{{ template "_internal/google_analytics.html" . }}` which does not produce a correct Google Analytics Tracker.

See details analysis here: https://github.com/jackyzha0/quartz/issues/194. Not sure if it's related to GA4, but it seems like a bug right now. I added the solution what worked for me in the issue.

**Comment by bmaciejm** [comment]
We are experiencing the same problem, using the Hugo template analytics does not work, when adding it manually via the snippet from Google its working.

 Hugo `_internal/google_analytics.html` template adds:
```
<script async src="https://www.googletagmanager.com/gtag/js?id={TAG}"></script>
  <script>
   var doNotTrack = false;
   if (!doNotTrack) {
   window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());
   gtag('config', '{TAG}', { 'anonymize_ip': false });
   }
   </script>
```
  
The (working) snippet from Google Analytics is:
```
<script async src="https://www.googletagmanager.com/gtag/js?id={TAG}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{TAG}'); 
</script>
```
There are two differences:
- the `doNotTrack` flag, which is actually set to false so code inside if should be triggered, it does not look like a cause
- the last line of the script is different, hugo template is using the `{anonymize_ip`:false} when GA snippet is not, as this is only difference(except of the flag mentioned above) I think it is the cause.

I've also found that there is an issue for removing `anonymize_ip` as it is not needed(and as it seems causes  problems with GA at the same time) ->  https://github.com/gohugoio/hugo/issues/10093

**Comment by coliff** [comment]
As Universal Analytics (UA) is deprecated and [will stop collecting traffic by July 2023](https://support.google.com/analytics/answer/10089681?hl=en#:~:text=On%20July%201%2C%202023%2C%20standard%20Universal%20Analytics%20properties%20will%20no%20longer%20process%C2%A0data) my recommendation would be to mark the 'Universal Analytics' integration as deprecated in Hugo.

- The W3C disbanded the ['Do Not Track' working group in January 2019](https://en.wikipedia.org/wiki/Do_Not_Track), Safari doesn't support it and the vast majority of sites don't honour the setting anyway. Therefore this setting could be marked as deprecated in Hugo too.
- The 'anonymize_ip' feature is on by default in GA4 and can not be disabled. Therefore I think this setting can be deprecated in Hugo too.

Removing the code for these will simplify the script and make things easier to maintain.

**Comment by bep** [comment]
@coliff I try to add GA to a new site today, and see if I understand it...

**Comment by bep** [comment]
So, I have upgraded one and added GA4 to a new site today, and the current (non async) variant works great. I have removed the async variant example from the docs.

What I see, though, which is unrelated to this, is that Google PageSpeed gives me a 7 point penalty adding the tag script (I have tested adding it a few different places (head, before body end)... 

<img width="184" alt="image" src="https://user-images.githubusercontent.com/394382/191213229-0e0e3c86-def6-4e9b-8d52-8a293e29f81b.png">

**Comment by coliff** [comment]
> Google PageSpeed gives me a 7 point penalty adding the tag script (I have tested adding it a few different places (head, before body end)...

Yes, this is an unfortunate downside to GA4. It loads more JS compared to Universal Analytics. Did you use the correct script implementation though? It should **always** load async.

**Comment by bep** [comment]
I loaded `_internal/google_analytics.html` ...

**Comment by bep** [comment]
I'm pretty this is handled, closing.
